### ISSUE TITLE
Git-submodule tries to run /usr/bin/perl

### ISSUE THREAD

**Issue by rkennedy** [termux/termux-packages#1]
The git-submodule script relies partially on Perl. It's hard-coded to run /usr/bin/perl, which isn't where the Termux Perl package installs that command. Looks like an additional patch is needed for the Git package.

**Comment by fornwall** [comment]
Thanks! Fixed in git 2.4.6-1 which has been pushed to the apt repo (so an "apt update && apt -y upgrade" will fix it for you).

**Comment by bprosnitz** [comment]
I am seeing this again in git 2.6.1
