### ISSUE TITLE
[Request] Python 2.7

### ISSUE THREAD

**Issue by icebal** [termux/termux-packages#10]
Python 3.X is great to have, and to be up to date, but seeing as how python 2.7 is still widely used i was wondering if you could include it in the repository? if this needs a package maintainer i would understand.

**Comment by vainikkaj** [comment]
:+1: 

For me, it's been a bit of a suprise that 2.7 is still so widely used even though 3.x has been out quite a while.

**Comment by fornwall** [comment]
A python2 package has now been added and should be available for installation after an `apt update`!

The `python` program is still python3, so one needs to invoke `python2` to get the older python version (and `pip2` to get pip for python 2).

Try it out and let me know how it works (re-open this issue or create a new one for any problem)!

**Comment by vainikkaj** [comment]
Thanks. It's a pity that my tablet refuses to co-operate at the moment, but once I get it working again I'll take this for a spin.

**Comment by arunbangalore** [comment]
Works great..able to use Python 2 ...thanks

**Comment by Quantaindew** [comment]
How do I use the idle, does it even have one ?
