### ISSUE TITLE
clang: broken libllvm dependency 

### ISSUE THREAD

**Issue by rsanjuan87** [termux/termux-packages#10007]
Primarily affects libllvm and subpackages. golang is also affected as it depends on clang. Should be hopefully fixed in a few hours when libllvm is uploaded

➜  ~ pkg install golang
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang : Depends: libcompiler-rt but it is not going to be installed
         Depends: libllvm (= 14.0.0) but 13.0.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by xtkoba** [comment]
This is because binary packages of `libllvm` and its subpackages were uploaded in an inconsistent way. Hopefully this is resolved by manually triggering rebuild of `libllvm` package (<a href="https://github.com/termux/termux-packages/actions/runs/2165248811">in CI</a>), which will take several hours to complete.

**Comment by thunder-coding** [comment]
@xtkoba, I've recently triggered a rebuild of libllvm, should be available in 4 hours on main repo

**Comment by xtkoba** [comment]
@thunder-coding Thanks! I didn't notice that. Then please stop mine.

**Comment by thunder-coding** [comment]
Maybe you might be interested in joining the Gitter/Matrix space where we often share progress on stuff.
https://gitter.im/termux/dev. I had mentioned 
there about re-running all failed upload due to outage of fosshost mirror.

**Comment by xtkoba** [comment]
And apparently the Grimler mirror has them in a consistent way. So a workaround would be to switch to using it temporarily, maybe?

**Comment by thunder-coding** [comment]
Should be fixed now!
