### ISSUE TITLE
Unable to compile ruby with custom prefix

### ISSUE THREAD

**Issue by gouravkhunger** [termux/termux-packages#10001]
### Problem description

Hi!

I am trying to compile the ruby package to use inside my app with a custom prefix.

Now I have tried a lot of environment set up: 

- Using docker on my m1 mac. It got some qemu related warnings so I moved to github actions using ubuntu
- I tried the container on github actions but it weirdly failed at some steps.
- I ended up using a similar [package.yml](https://github.com/termux/termux-packages/blob/master/.github/workflows/packages.yml) github action that termux has. (Without the upload to hosting part)

What I did:

- Changed `TERMUX_APP_PACKAGE` in `scripts/properties.sh` from `com.termux` to `com.github.gouravkhunger.jekyllex` (my app package)
- Removed the `-I` flag [here](https://github.com/termux/termux-packages/blob/master/.github/workflows/packages.yml#L137) because all dependencies need to be rebuilt for my prefix.
- Dispatching the workflow with these packages as input: `libandroid-support libffi libgmp readline openssl libyaml zlib ruby` (If I passed just ruby it failed to find dependencies so I had to pass manually).

Dependencies for ruby build correctly before ruby compilation fails (this is from `output` folder when I ran it on my laptop):

<img width="802" alt="image" src="https://user-images.githubusercontent.com/46792249/163111266-532f00e4-c1f3-4eab-810a-342d064225e1.png">

But ruby gives these errors (these are from github actions, but locally too, errors were same):

![image](https://user-images.githubusercontent.com/46792249/163110142-51a6dfbb-0751-44c0-809e-b5193b2d5653.png)

For some reason `sh` binary wasn't there in the required location.

So with help from termux discord server, I added the package `dash` to the workflow input. Now I passed `libandroid-support libffi libgmp readline openssl libyaml zlib dash ruby`.

This thing gave this weird error:

![image](https://user-images.githubusercontent.com/46792249/163110391-955a3a57-ee71-42c5-9df6-cab689a17593.png)

From further support, I was told to symlink `bash` to `sh`. I tried these:

- Building `bash` instead of `dash` as after build process, bash would install in `$PREFIX/files/usr/bin/`. But this gave the same "(" error.
- Symlinking `./bin/bash` to `$PREFIX/files/usr/bin/sh`. This was also error prone. If I had dash compiled and installed, it would say file already exists. can't symlink. If I force linked after compiling dash, it would overwrite the file and again report no such file.

But recent compiling for [`ruby`](https://github.com/termux/termux-packages/actions/runs/2155520245) on termux gets successful.

Can someone help me with what could be causing the error with this `sh` file? I need this for [my open source project](https://github.com/jekyllex) and I will happily credit back to the termux team for helping with this project!

Thank you!

### What steps will reproduce the bug?

Change `$PREFIX` and try compiling for ruby. I guess that is the problem with this.

### What is the expected behavior?

It should compile...
or the error log must be a bit clearer on what the issue might be.

### System information

Earlier I tried running compilation on m1 mac running Monterey 12.3.1 with docker 4.5.0

But because of some `qemu` emulator error on docker on m1 / rosetta, I am using Github actions similar to what termux has.

**Comment by xtkoba** [comment]
Seems like your `$PREFIX/bin/sh` is not for build host but for target host. Note that our build system has a hack for that:

https://github.com/termux/termux-packages/blob/567e93723336fc71cdc30cd96e39bc7df0d0d470/scripts/build/termux_step_override_config_scripts.sh#L37-L39

**Comment by Grimler91** [comment]
We return from that function and skip that hack for builds without -i or -I though, so I would say it's a bug in the build scripts: https://github.com/termux/termux-packages/blob/567e93723336fc71cdc30cd96e39bc7df0d0d470/scripts/build/termux_step_override_config_scripts.sh#L2-L3

**Comment by gouravkhunger** [comment]
Since `TERMUX_ON_DEVICE_BUILD` is false if compilation is not being done on Android:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/46792249/163115044-5c9502a4-c3dd-4cd6-a143-48fb70748301.png">

So I need to change

```shell
if [ "$TERMUX_ON_DEVICE_BUILD" == true ] || [ "$TERMUX_INSTALL_DEPS" == false ]; then 
 	return 
fi
```

to

```shell
if [ "$TERMUX_ON_DEVICE_BUILD" == true ]; then 
 	return 
fi
```
Because I need to rebuild dependencies too (without `-I`) flag. Is that right?

**Comment by xtkoba** [comment]
Oh yeah, `$PREFIX/bin/sh` hack should be applied regardless of `TERMUX_INSTALL_DEPS`.

@gouravkhunger That should suffice for personal usage. We will make a more graceful change.

**Comment by gouravkhunger** [comment]
Thanks @xtkoba. Is there any way I could help contribute to this fix? Will be glad to contribute 😄

**Comment by Grimler91** [comment]
> Thanks @xtkoba. Is there any way I could help contribute to this fix? Will be glad to contribute smile

Changing so that the hack is run at the top of the function

```sh
if [ "$TERMUX_ON_DEVICE_BUILD" == false ]; then
  # Make $TERMUX_PREFIX/bin/sh executable on the builder, so that build
  # scripts can assume that it works on both builder and host later on:
  ln -sf /bin/sh "$TERMUX_PREFIX/bin/sh"
fi

if [ "$TERMUX_ON_DEVICE_BUILD" == true ] || [ "$TERMUX_INSTALL_DEPS" == false ]; then
  return
fi
```

should work, feel free to open a PR, thanks

**Comment by xtkoba** [comment]
@gouravkhunger Then please test if PR #10002 works.

**Comment by gouravkhunger** [comment]
Oh, I was about to make the PR 😄 

Anyways, the change I made for my personal use - I suppose it is working correctly. After building ruby, now gem is being compiled which was never reached before. I suppose it works.

As soon as the current ongoing build is done I will try building with your PR and review. Thanks!
