### ISSUE TITLE
Include Pyinstaller in build-essentails

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#10005]
Pyinstaller can be installed through pip and can make standalone python script executable

**Comment by xtkoba** [comment]
#876

**Comment by T-Dynamos** [comment]
![Screenshot_2022-04-14-07-45-38-436_com termux](https://user-images.githubusercontent.com/68729523/163300644-3619cfd1-0556-4ed8-b9a6-fe9115143c0a.jpg)
*But its working*
