### ISSUE TITLE
[Bug]: clang-14: error: unknown argument: '-gcc-toolchain'

### ISSUE THREAD

**Issue by rendiix** [termux/termux-packages#10014]
### Problem description

Can't compile using cmake, error appears as shown below
![Screenshot_20220414-170106618_1](https://user-images.githubusercontent.com/16639978/163363343-b9edefdf-0dbd-4927-b89b-9e40fbbb856b.jpg)

### What steps will reproduce the bug?

clang -gcc-toolchain -dM -E - < /dev/null

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.190-perf #1 SMP PREEMPT Tue Mar 8 00:02:53 CST 2022 aarch64 Android
Device manufacturer:
asus
Device model:
ASUS_I001DE

```

**Comment by xtkoba** [comment]
A workaround would be to use `--gcc-toolchain` (leading double-hyphen) instead of `-gcc-toolchain` (leading single-hyphen).

(For reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1745129.)

**Comment by rendiix** [comment]
> 

Using double hyphen does not solve the problem
![Screenshot_20220414-183939300 (1)](https://user-images.githubusercontent.com/16639978/163383632-55d379b0-a0aa-4c85-8c7a-1273cfbbaf7a.jpg)

**Comment by xtkoba** [comment]
Needs to be of the form `--gcc-toolchain=/some/where`, apparently.

**Comment by rendiix** [comment]
> 

Thanks, nice hack
