### ISSUE TITLE
[Bug]: neovim-nightly: Broken `TERMUX_PKG_VERSION` due to auto-update

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#10020]
### Problem description

https://github.com/termux/termux-packages/commit/f25920866172f31478361b174e30908be0046fba

### What steps will reproduce the bug?

Probably auto update

### System information

I understand this is an auto-update

**Comment by xtkoba** [comment]
ping @MrAdityaAlok

**Comment by MrAdityaAlok** [comment]
@Maxython thank you! For reporting. Should be fixed now.
