### ISSUE TITLE
Package request: miredo

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#1002]
There are some patches [here](https://dan.drown.org/android/src/miredo/) that could be used as a basis.
I'm not sure this could work without root though.

**Comment by xtkoba** [comment]
Relies on `pthread_cancel`.

**Comment by twaik** [comment]
Does not comply [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last change was `Mon, 28 Oct 2019 07:47:15 +0300 (06:47 +0200)` so I am considering the project is inactive.
