### ISSUE TITLE
[Bug]: natpmpc does not open ports

### ISSUE THREAD

**Issue by Austcool-Walker** [termux/termux-packages#10035]
### Problem description

The natpmpc Package doesn't open the requested ports via command line but segfaults.
it seems to run but it doesn't open any ports. when using with the g flag it just segfaults.

### What steps will reproduce the bug?

screenshot sums it up.
![Screenshot_20220415-185430_Termux](https://user-images.githubusercontent.com/61804916/163650900-38bbe804-bf1a-4932-a1a4-cbe30151dc89.jpg)

### What is the expected behavior?

Its suppost to open ports when I call the proper commands udp and tcp for the apple airport routers

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
git/stable 2.35.3 arm [upgradable from: 2.35.2]
glib-bin/stable 2.72.1 arm [upgradable from: 2.72.0-1]
glib/stable 2.72.1 arm [upgradable from: 2.72.0-1]
natpmpc-static/stable 20150609-2 arm [upgradable from: 20150609-2]
natpmpc/stable 20150609-2 arm [upgradable from: 20150609-2]
pango/stable 1.50.7 arm [upgradable from: 1.50.6]
pcre2/stable 10.40 arm [upgradable from: 10.39-2]
Android version:
9
Kernel build information:
Linux AugustusXVIII-iShitOS-SM-T380 3.18.120 #1 SMP PREEMPT Mon Sep 7 17:13:02 EDT 2020 armv7l Android
Device manufacturer:
samsung
Device model:
SM-T380
u0_a237@:/data/data/com.termux/files/home$
```

**Comment by xtkoba** [comment]
The segfault part will be fixed in `natpmpc` version `20150609-3`. Nothing else should be changed.

**Comment by Austcool-Walker** [comment]
Thanks it doesn't segfault but still doesn't open the ports ngrok also doesn't seem to work.... Termux or android it self is blocking port forwarding :/ works fine on a desktop computer tho...

**Comment by Austcool-Walker** [comment]
Upnpc detects the upnp devices on my network tho odd enough.

**Comment by Austcool-Walker** [comment]
It probably needs patches to the actual programs code to fix the
```
~ $ natpmpc -a 9999 9999 tcp 999999
initnatpmp() returned -3 (FAILED)
~ $ natpmpc -g ipv4adress
initnatpmp() returned -8 (FAILED)
~ $ natpmpc -g ipv4address
initnatpmp() returned -8 (FAILED)
~ $ natpmpc -g ipv4address -a 3003 3003 tcp 999
initnatpmp() returned -8 (FAILED)
~ $ natpmpc -g ipv4address -a 3003 3003 tcp 9999
initnatpmp() returned -8 (FAILED)
~ $
```

**Comment by Austcool-Walker** [comment]
It works you have to tell it where the ip4 address of the airport is solved!
![Screenshot_20220417-135320_Termux](https://user-images.githubusercontent.com/61804916/163726578-64e61b11-a826-4705-b20d-02eb9f2bbc19.jpg)
