### ISSUE TITLE
[Bug]: xdelta3 is broken on Arm for patching large files

### ISSUE THREAD

**Issue by truboxl** [termux/termux-packages#10036]
### Problem description

So far I am unable to patch any ROM using xdelta3 on Arm. I keep getting error:
```
xdelta3: non-seekable input is short: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent
```

On aarch64, it is working correctly. Not sure about other arches.

### What steps will reproduce the bug?

There maybe other way to test xdelta3, but I haven't find any good .xdelta files and source files for testing patching...

### System information

termux-info:
```
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22825772 #1 SMP PREEMPT Mon Dec 13 15:05:19 +07 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A307GN
```

**Comment by xtkoba** [comment]
I have no access to repro. Please test the artifact in https://github.com/termux/termux-packages/actions/runs/2175978987 and report whether or not it solves the issue.

**Comment by truboxl** [comment]
Thanks. That does seem to fix the problem for xdelta3 on arm.
