### ISSUE TITLE
dpkg-add-architecture doesn't work?

### ISSUE THREAD

**Issue by skysider** [termux/termux-packages#1005]
My android arch is aarch64 and I want to debug an arm program with gdb，it says  `warning: '/system/lib64/libion.so': Shared library architecture aarch64 is not compatible with target architecture arm.`, so I want to install gdb:arm version, and when I execute dpkg-add-architecture arm and then apt update, it doesn't update arm package list.

**Comment by xeffyr** [comment]
Termux doesn't support multiarch (multilib) installations.
