### ISSUE TITLE
How upgrade TeXLive [texlive-installer]

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#10050]
After you released the binaries of TL2022 there is a mismatch for users which have installed TL with `texlive-installer` (aka `termux-install-tl`) because the packages refers to TL2021 while the binaries are for TL2022:

```
tlmgr --repository my_local_repo/tlnet --update --list

tlmgr: Local TeX Live (2021) is older than remote repository (2022)
Cross release updates are only supported with
   update-tlmgr-latest.sh [...]
[...]
```

Really `update-tlmgr-latest.sh` works with Termux?

Maybe you should add some statements on how to do this to the wiki or some other place.

The syste is

```
termux 0.118, Android 11
```

**Comment by Grimler91** [comment]
Texlive-installer needs to be updated for 2022 before it can work. I need to re-do/check the patches and test it a bit more before pushing the update. I haven't tested `update-tlmgr-latest.sh` at all, so no idea how well that works

To use the installer with texlive 2021 in the meanwhile you can specify a 2021 repo, as suggested in https://github.com/termux/termux-packages/issues/9896.

Leaving this open until texlive-installer has been updated.

**Comment by angelog0** [comment]
I still get the same issue,

```
$ tlmgr --repository ~/storage/localapps/tlrepo/tlnet update --list

tlmgr: Local TeX Live (2021) is older than remote repository (2022).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```

I have updated both my local repo and Termux...

**Comment by angelog0** [comment]
Just for completeness

```
$ dpkg -l | grep -i texlive
ii  texlive-bin           20220403-1     aarch64      TeX Live is a distribution of the TeX typesetting system. This package contains architecture dependent binaries.
ii  texlive-installer     20220403       all          Wrapper around texlive's install-tl script
```

**Comment by Grimler91** [comment]
Install texlive 2022 with `termux-install-tl`. You can try `update-tlmgr-latest.sh` but as mentioned I haven't tested it so no idea if it works well
