### ISSUE TITLE
[Bug]: Unable to run gradle

### ISSUE THREAD

**Issue by jhonboy121** [termux/termux-packages#10066]
### Problem description

Unable to run gradle. Screenshot and logcat of abort message attached.

Screenshot:
![Screenshot_20220419-080609_Termux](https://user-images.githubusercontent.com/53824362/163909280-488c44b4-d2f0-4217-8ca7-c106bbf5ad9f.png)

Logcat:
[Logs-2022-04-19-08-11-34.zip](https://github.com/termux/termux-packages/files/8509403/Logs-2022-04-19-08-11-34.zip)

### What steps will reproduce the bug?

Install gradle with pkg. Run gradle and execution will be aborted.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.14.275-Dora-3.0 #12 SMP PREEMPT Mon Apr 18 16:24:31 IST 2022 aarch64 Android
Device manufacturer:
OnePlus
Device model:
GM1911 
```

**Comment by xtkoba** [comment]
Seems like just an instance of #7332. Please migrate there. Thanks.

**Comment by jhonboy121** [comment]
Ah yes, mb. Thanks!
