### ISSUE TITLE
[Bug]: texinfo: Info dir not updated automatically

### ISSUE THREAD

**Issue by pabl0** [termux/termux-packages#10064]
### Problem description

By default, there is no `$PREFIX/share/info/dir `file. For Emacs users, this means unless the user has some packages installed (that include documentation in info format), the "(dir)Top" directory node is empty. For each package installed under `~/.emacs.d/elpa`, Emacs will add the directory to `Info-directory-list` and populate the directory, but it's still missing almost all info documents, including Emacs itself (and elisp, org, etc).

For users of standalone info reader, the top directory is always empty, but I don't think most people bother with the standalone reader.

You can access all info documentation in Emacs by calling info with `C-u` `C-h` `i` prefix argument and specifying the .info file name, but this user experience is not nearly as nice as having the directory, as is the case in most desktop distros.

I propose that a similar mechanism that's in Debian would be implemented in Termux.

I believe all you need to do is to create `texinfo.triggers` with:

```
interest-nowait /data/data/com.termux/files/usr/share/info
```
and make `texinfo.postinst` do something like:

```
for file in $PREFIX/usr/share/info/*
do
    install-info --info-file="$file" --dir-file=$PREFIX/usr/share/info/dir
done
```

(See `/usr/sbin/update-info-dir` in Debian for a bit fancier version.) The `man` package in Termux already uses the trigger mechanism to run `makewhatis -Q`.

### What steps will reproduce the bug?

Run emacs and type `C-h` `i` for info. If packages are installed, you will see the documentation for those packages, otherwise you will see a very empty directory.

### What is the expected behavior?

All info documentation shipped by packages in `$PREFIX/share/info`will be listed in the info directory in Emacs or the standalone info reader.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.astra.in.ua/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.148 #1 SMP PREEMPT Wed Jul 14 00:33:32 CST 2021 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
CMR-W09
```

**Comment by xtkoba** [comment]
I'm interested in this.
