### ISSUE TITLE
[Package]: qtwebengine

### ISSUE THREAD

**Issue by thiled** [termux/termux-packages#10070]
### Package description

The Qt WebEngine module provides a web browser engine that makes it easy to embed content from the World Wide Web into your Qt application on platforms that do not have a native web engine.

Qt WebEngine provides C++ classes and QML types for rendering HTML, XHTML, and SVG documents, styled using Cascading Style Sheets (CSS) and scripted with JavaScript. HTML documents can be made fully editable by the user through the use of the contenteditable attribute on HTML elements.

### Source code URL

https://github.com/qt/qtwebengine/tree/v5.15.9-lts

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

To get better html5 compatibility for modern web pages.
It's a significant package that will make revolution of the termux-x11 environment

**Comment by leapofazzam123** [comment]
It uses Chromium/Blink, so there's a low chance of it actually working on Termux

**Comment by thiled** [comment]
Ok.termux-x11 worked in proot distros, so it's not a problem.

**Comment by xtkoba** [comment]
<a href="https://bugs.gentoo.org/show_bug.cgi?id=669082">QtWebengine is notoriously time-consuming to build.</a> I highly doubt if the build completes in GitHub Actions CI (within 6 hours).

**Comment by xtkoba** [comment]
There are several package requests that depend on this. Please don't close this issue even if it is virtually unpackageable.
