### ISSUE TITLE
[Bug]: qt based packages failed to open with segmentation fault while using xserver xsdl.

### ISSUE THREAD

**Issue by xu3s** [termux/termux-packages#10097]
### Problem description

as the title said, when i try to open qt based packages when using xserver xsdl.it throws segmentation fault
but somehow it work fine when opened using termux:x11.

while i would like to use termux:x11 mainly,but it keep crashing on me and sometimes it just doesn't work with my need.
i have asked this on discord but got no answer.

gdb log : https://www.dropbox.com/s/gjy15lu5t6stptw/gdb.txt?dl=0

### What steps will reproduce the bug?

open qterminal, otter-browser or any other qt based packages

### What is the expected behavior?

the apps/packages just work just fine

### System information

~ $ termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.astra.in.ua/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.org/apt/termux-x11 x11 main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.153-perf+ termux/x11-packages#1 SMP PREEMPT Thu Feb 20 17:26:22 CST 2020 aarch64 Android
Device manufacturer:
asus
Device model:
ASUS_X00TD

**Comment by xtkoba** [comment]
Not reproducible on my environment (Android 8.1.0 aarch64 asus/WW_X01AD).

I installed "x.org.server" through Google Play and launched it, then

```bash
export DISPLAY=:0
otter-browser # or qterminal
```

and the Qt app just launches fine.

**Comment by xu3s** [comment]
Thats weird, the bug still occur on my devices, i will try to look what setting that I've changed that was causing this

**Comment by twaik** [comment]
@xu3s Qt was updated a few times, is it still reproducible?

**Comment by twaik** [comment]
Can not reproduce this. Probably it was fixed.
