### ISSUE TITLE
libandroid-posix-semaphore support for qt5 And PyQt5

### ISSUE THREAD

**Issue by ar664** [termux/termux-packages#10104]
I suggest building with semaphore support now that we have libandroid-posix-semaphore.
https://github.com/termux/x11-packages/blob/ae193d67e3f0bda6a591e94c2410ab27badd7c8c/packages/qt5-qtbase/termux-build-qmake.sh#L79

Because when I try to do `pip install PyQt5`  this is the current error I get.
![Screenshot_20220309-122414_Termux](https://user-images.githubusercontent.com/11823835/157496617-dd22a300-7df4-42d1-9cb8-4e9df17a8508.jpg)

**Comment by xtkoba** [comment]
IPC support for Qt5 has already been added. As for PyQt5, please migrate to #10165. Thanks.
