### ISSUE TITLE
Consider setting TMPDIR

### ISSUE THREAD

**Issue by malbarbo** [termux/termux-packages#1010]
Many programs needs to create temporary files, termux packages are patched to use "@TERMUX_PREFIX@/tmp" instead of /tmp, but external compiled programs (like rust programs) are not. Setting TMPDIR (in @TERMUX_PREFIX@/etc/profile?) would allow these programs works without users intervention.

**Comment by fornwall** [comment]
Thanks - `TMPDIR` is exported starting with version `0.49` of Termux, which has just been released and should be available as an update shortly!

**Comment by malbarbo** [comment]
Thank you!
