### ISSUE TITLE
[Package]: Tux Paint

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#10101]
### Package description

Tux Paint is a free, award-winning drawing program for children ages 3 to 12 (for example, preschool and K-6). Tux Paint is used in schools around the world as a computer literacy drawing activity. It combines an easy-to-use interface, fun sound effects, and an encouraging cartoon mascot who guides children as they use the program.

### Home page URL

https://tuxpaint.org/

### Source code URL

http://sourceforge.net/projects/tuxpaint/files/tuxpaint/0.9.27/tuxpaint-0.9.27.tar.gz/download

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I tried but missing header files
![Screenshot_2022-03-26-12-37-31-113_com termux](https://user-images.githubusercontent.com/68729523/160228965-654252ed-f5c8-454d-a371-8b8c633bfa93.jpg)
I was in termux-chroot environment and it also depends on sdl2 would it have same issue as kivy termux/x11-packages#638 ?

**Comment by T-Dynamos** [comment]
We got all dependencies now we can try build

**Comment by ChiefMikeK** [comment]
just wondering why the request and devs effort for this f-droid already has a native apk?
- [Tux Paint | F-Droid - Free and Open Source Android App Repository](https://f-droid.org/en/packages/org.tuxpaint/ )
- and here is the tarball 
-    ` https://f-droid.org/repo/org.tuxpaint_9270_src.tar.gz `

**Comment by T-Dynamos** [comment]
> just wondering why the request and devs effort for this f-droid already has a native apk?
> 
> * [Tux Paint | F-Droid - Free and Open Source Android App Repository](https://f-droid.org/en/packages/org.tuxpaint/)
> * and here is the tarball
> * `https://f-droid.org/repo/org.tuxpaint_9270_src.tar.gz`
This issue enables support for sdl opengl  and added sdl-gfx and sdl-pango by which programs other than tux can work
