### ISSUE TITLE
[Package]: kid3-cli

### ISSUE THREAD

**Issue by GUUser91** [termux/termux-packages#10105]
### Package description

Audio tag editor

### Home page URL

https://kid3.kde.org/

### Source code URL

https://invent.kde.org/multimedia/kid3

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Marco-9456** [comment]
What's the name of the package?
I tried pkg install kid3-cli and it didn't work

**Comment by GUUser91** [comment]
It's called kid3

**Comment by Marco-9456** [comment]
> It's called kid3

```
pkg install kid3
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Checking availability of current mirror:
[*] https://packages-cf.termux.dev/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package kid3
```

**Comment by GUUser91** [comment]
Try this
>apt-get update && apt-get upgrade -y
then this
>pkg install x11-repo
Then install kid3
>pkg install kid3

**Comment by Marco-9456** [comment]
Thanks, that worked, I didn't know that it was on a different repo.
