### ISSUE TITLE
[Package]: real libEGL, libGLESv1_CM, libGLESv2, libGLESv3

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#10118]
### Package description

EGL/GLESv1/GLESv2/GLESv3 libraries

### Source code URL

https://android.googlesource.com/platform/frameworks/native

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Hi.
A problem of using hardware accellerating in termux is simple: it is not possible to create platform's compatible native windows and/or hardware buffers and use them with existing libEGL/GLESv1/GLESv2. But we can use android-emugl and anbox sources to create something like GLES streaming to another activity or program. Android Studio's emulator and Anbox already use emugl so I think it is possible to use it in our project.
I already started porting anbox source but I can not check if it works because I can not build Android's EGL/GLES/system core libraries without Android's build system, compiler reports thousands of errors. Ubuntu and Debian have debhelper scripts for building it.
Is there someone who can port those?

**Comment by DLC01** [comment]
Couldn't ANGLE also theoretically run atop the system vulkan driver to Provide hardware accelerated OpenGL ES

**Comment by licy183** [comment]
> Couldn't ANGLE also theoretically run atop the system vulkan driver to Provide hardware accelerated OpenGL ES

`libvulkan.so` in Android doesn't contain symbols like `vkCreateXcbSurfaceKHR` but it has symbols like `vkCreateAndroidSurfaceKHR`. As we use OpenGL to render a X11 window, I don't think vulkan from Android is able to use.

**Comment by licy183** [comment]
Hello. I've noticed the application mentioned in termux/termux-packages#14517, and it seems related to this issue.

If I understand correctly, this application uses `virgl` as Gallium driver in mesa. This driver works in a chroot environment (and I think it is also possible to work in Termux), and redirects some commands to `virglrender`. `virglrender` is running in an Android application, and thus it is able to use some hardware acceleration on Android using Android's EGL.

About how to IPC between the driver and the Android application, the UNIX socket is used in this application, and originally it may need root permission to create the socket file. I think it is possible to replace it with `abstract namespace` UNIX socket, and thus no root is needed, just like what is done in `libandroid-shmem`.

Source code: https://github.com/alexvorxx/VirGL-Overlay-Rebuild

**Comment by twaik** [comment]
I think we can achieve this in termux, but to use it with X11 apps we must make some draw-back to regular x11 surface. [Link](https://gist.github.com/RikkaW/be3fe4178903702c54ec73b2fc1187fe) to source code implementing overlays from regular `app_process` started Java code.

**Comment by dontknowhy** [comment]
So it's 2023.
Is there any improvement?

**Comment by twaik** [comment]
No.

**Comment by dontknowhy** [comment]
> No.

A sad story😭👉📱
A nice [https://www.bilibili.com/video/BV1GJ411x7h7](video) from China)

**Comment by ThieuMinh26** [comment]
> Source code: https://github.com/alexvorxx/VirGL-Overlay-Rebuild

Can you port this to termux ?

**Comment by twaik** [comment]
Actually it is possible to make this without using any Java API's. But it will require patching virgl itself. Android supports rendering to offscreen surface `eglCreatePixmapSurface`. After rendering you can download image back using `glReadPixels`. To avoid copying this image many times you can read it into XShmImage. After that image will be ready to be drawn on X11 window (XShmPutImage). 
To make this approach compatible with proot/chroot Xserver's you should avoid using `XShmCreateImage` and use:
1. `xcb_shm_attach_fd` (will not work in chroot in the case if file descrioptor is ashmem, will work in proot launched with `--ashmem-memfd`, see related [issue](https://github.com/termux/proot/issues/258)).
2. `shm_create_segment` (will work with proot launched with `--ashmem-memfd`, see related [issue](https://github.com/termux/proot/issues/258), will work with chroot in the case if `/run/shm`, `/var/tmp` and `/tmp` are mounted as tmpfs or memfd syscall is enable in kernel config). 

After attaching file descriptor wit one of this it will be possible to write image we got to some drawable (window or pixmap) in X server using `xcb_shm_put_image` call.

**Comment by twaik** [comment]
@licy183 ?

**Comment by licy183** [comment]
> @licy183 ?

Of course we can enable virgl frontend in mesa, but I wonder whether libEGL will work or not without JNI. AFAIK libEGL.so can be dynamic loaded but `eglInitialize` will fail.

**Comment by twaik** [comment]
> Source code: https://github.com/alexvorxx/VirGL-Overlay-Rebuild

After reading code of this repo I realized that we actually can patch it work directly with android's libEGL. I do not know how much overhead has zink but according to [this](https://ivonblog.com/en-us/posts/termux-virglrenderer/) it anyway will work faster than llvmpipe and also will allow users to use semi-real/piped hardware acceleration in proot/chroot. As far as I see it we should patch it to work without `epoxy`, work with `--use-egl-surfaceless` by default without option to disable it. And instead of blitting buffer to SurfaceView as it was done in android virgl fork mentioned above we should use `glReadPixels` into some shared memory attached to X server with `xcb_shm_attach_fd` or `xcb_shm_create_region`. And after that blit it to xserver with `xcb_shm_put_image` or maybe by some function of present extension, I am not sure about that. I used such a copying in `termux-x11` and it worked pretty fast.

**Comment by twaik** [comment]
> I wonder whether Android native libEGL will work or not without JNI. AFAIK libEGL.so can be dynamic loaded but eglInitialize will fail.

It will work. libhybris and android opengl tests are using it without jni.

**Comment by twaik** [comment]
I am not sure how to avoid linking it to libEGL/libGLESv2 of mesa, libglvnd or epoxy. Is there a way to direct-link it to /system/bin/libEGL.so or /system/bin64/libEGL.so without making dlsym?

**Comment by twaik** [comment]
@mittorn Can you help us please?

**Comment by twaik** [comment]
You used very outdated version of virglrenderer. 526 behind master.

**Comment by twaik** [comment]
As far as I see [he did not really patch virglrenderer](https://ivonblog.com/en-us/posts/termux-virglrenderer/#3-compile-virglrenderer), it worked out of the box. He only patched some pathes. But he used zink as a backend so it can be a bit more complicated.

**Comment by licy183** [comment]
Emmm... I'll try the latest branch this afternoon (UTC+8).

Yeah, that blog actually redirect the OpenGL rendering operations from proot environment to native Termux, and render OpenGL using zink in the native Termux side. It don't use Android's GLES.

**Comment by ThatMG393** [comment]
@twaik how about this?
https://github.com/ThatMG393/gpu_accel_termux

**Comment by twaik** [comment]
And I think it is a reason why it is not fast as it could be. We've seen it can work inside Android application so it definitely can work with Android's libraries and not mesa.

**Comment by twaik** [comment]
> @twaik how about this? [gpu_accel_termux](https://github.com/ThatMG393/gpu_accel_termux)

I am talking about avoiding using mesa. Your scripts does just the opposite thing.

**Comment by ThatMG393** [comment]
What if you symlink the libraries? I'm pretty sure all the libs above are stored in `/system/lib` & `/system/lib64`. If not then we patch it to work.

**Comment by twaik** [comment]
I do not want to make any symlinks because it can interfere with mesa, epoxy or glvnd. Maybe we can compile epoxy (patched to open Android libraries only) statically and build virglrenderer with that. It still will use mesa, but we will make less patches and we will be able to change path to those libraries using environment variables (like in licy183's repo). IMHO it would be helpful.

**Comment by ThatMG393** [comment]
@twaik The `/vendor/lib(64)/egl` contains only these files (for me): `egl.cfg libGLES_meow.so  libMEOW_gift.so libMEOW_trace.so libGLES_mali.so  libMEOW_data.so  libMEOW_qt.so`, how can we use that?

**Comment by twaik** [comment]
We cant. They are dlopened by libEGL/libGLES in runtime.

**Comment by licy183** [comment]
I still wonder whether Android GLES will work without JNI. Following is the test result using Python's ctypes.

PS: I don't have a PC with me right now. I'll do a more detailed test in the afternoon.

```
Python 3.11.2 (main, Feb 11 2023, 14:06:23) [Clang 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> android_EGL = ctypes.CDLL('/system/lib64/libEGL.so')
>>> disp = android_EGL.eglGetDisplay(0)
>>> disp
-206159232
>>> android_EGL.eglInitialize(disp, 0, 0)
0
>>>
```

**Comment by twaik** [comment]
It will work. But I doubt about latest virglrenderer because it seems to rely on GBM and lots of mesa extensions. Maybe we should go the same way mittorn went and not to use builtin egl support.

**Comment by twaik** [comment]
> I still wonder whether Android GLES will work without JNI. Following is the test result using Python's ctypes.

[Those tests](https://cs.android.com/android/platform/superproject/+/master:frameworks/native/opengl/tests/) are built as native binaries and do not require JNI.

**Comment by twaik** [comment]
I really hope drawable target (I mean id used in X11) is exposed to virglrenderer. Because I can not find it.

**Comment by licy183** [comment]
Emmm... I can confirm that `/system/lib(64)/lib{EGL,GLESv2,GLESv2}.so` can do off-screen rendering without JNI. But I think there is a lot of work for us to do to make virgl frontend in native Termux mesa able to use the virglrenderer over Android GLES backend...

**Comment by twaik** [comment]
I think it is not. Virpipe is designed to work in virtual machines. And it actually works without rebuilding inside proot. The only problem is to make up-to-date virglrenderer work with xcb instead of mesa.

**Comment by twaik** [comment]
`vrend_winsys.c` and `vrend_winsys_glx.c` seem to be very straightforward. I think we can simply write file like `vrend_winsys_android.c` which will have all the functions from `vrend_winsys.c` (partially stubbed) and will implement functionality from `vrend_winsys_glx.c`, but targetting on android surfaceless egl api. After disabling `vrend_winsys.c`, `vrend_winsys_egl.c`, `vrend_winsys_glx.c` and other sources not related to Android we will get Android backend. But I still doubt how to draw back to window. It looks like window id is stored in `target` or `handle` field. But I am not sure.

**Comment by licy183** [comment]
Emmm... IIUC, `mesa` on guest GPU (here is the OpenGL libraries in the package `mesa` from Termux) will send some rendering data to `virgl_test_server` through the pipe `$PREFIX/tmp/.virgl_test`, and then `virgl_test_server` will render them using the OpenGL functions on host GPU (here is Android GLES), so I think we should do some patches on `vrend_winsys_egl.c`...

**Comment by twaik** [comment]
Maybe we do not need it at all, we simply do not have gbm available. Can we use `vrend_winsys_glx.c` as a base? And a question is how to identify a drawable to which we should draw and where is the code called on `eglSwapBuffers` or `glxSwapBuffers`...

**Comment by twaik** [comment]
We have zink, llvmpipe, virpipe working so this issue can be closed...

**Comment by SwuduSusuwu** [comment]
> We have zink, llvmpipe, virpipe working so this issue can be closed...

Those allow to execute _OpenGLES_ programs, but those do not give the headers which `clang++` uses to produce _OpenGLES_ programs:
```
~/fish $ clang++ fish.c++
fish.c++:1:10: fatal error: 'GLES2/gl2.h' file not found
    1 | #include <GLES2/gl2.h>
      |          ^~~~~~~~~~~~~
1 error generated.
~/fish $
```
Does this overlap, or should open a new issue for [`libgles-dev`](https://installati.one/install-libgles-dev-ubuntu-20-04/)?

**Comment by licy183** [comment]
`pkg install libglvnd-dev`
