### ISSUE TITLE
[Package]: Tenacity

### ISSUE THREAD

**Issue by bilrou** [termux/termux-packages#10113]
### Package description

Tenacity is an easy-to-use, privacy-friendly, FLOSS, cross-platform multi-track audio editor/recorder for Windows, macOS, Linux and other operating systems.
                               

### Home page URL

https://tenacityaudio.org/  

### Source code URL

https://github.com/tenacityteam/tenacity

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

As a result of the closing of termux/x11-packages#112

**Comment by 3ls-it** [comment]
<img width="1569" height="1199" alt="Image" src="https://github.com/user-attachments/assets/0b6a8672-8e1b-43b0-9445-339524a01745" />

I have a working package build for Tenacity v1.3.4 which has FFmpeg8 support backported in from Tenacity v1.4-alpha1.  
Any interest?? I was motivated to get this working as I refuse to use Audacity.

**Comment by TomJo2000** [comment]
Send it in as a PR, we'll get it reviewed.

**Comment by 3ls-it** [comment]
> Send it in as a PR, we'll get it reviewed.

I'm happy to. I have a few items to tidy up, then do a host build test to make sure it's reproducible. I've been doing on-device builds on my tablet, so I need to make sure that my `build.sh` is ok.

**Comment by 3ls-it** [comment]
> Send it in as a PR, we'll get it reviewed.

I've opened a PR #28638
