### ISSUE TITLE
[Package]: Ardour

### ISSUE THREAD

**Issue by bilrou** [termux/termux-packages#10112]
### Package description

the digital audio workstation  Ardour is a multichannel hard disk recorder (HDR) and digital audio workstation (DAW). It can be used to control, record, edit and run complex audio setups
                                                                                             

### Home page URL

https://www.ardour.org/  

### Source code URL

https://github.com/Ardour/ardour

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Workaround needed for `pthread_cancel()`.
