### ISSUE TITLE
'st' aka suckless terminal segfault - CRITICAL

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-packages#10124]
### Problem description

Wanted to set up a complementary graphical desktop using termux and VNC following https://wiki.termux.com/wiki/Graphical_Environment on a clean termux setup.

st fails to launch and exits with segmentation fault

### What steps will reproduce the bug?

on a clean setup:

pkg update
pkg install *-repo
pkg install i3 st dmenu

export DISPLAY=:1
vncserver -localhost

i3& (works)
st& (segfault)

### What is the expected behavior?

st should launch

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.113-22501734 termux/x11-packages#1 SMP PREEMPT Thu Oct 7 17:52:58 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T970

```

**Comment by xtkoba** [comment]
Turns out to be *not* related to the main issue in #10150 itself but related to <a href="https://github.com/termux/termux-packages/issues/10150#issuecomment-1102318823">an error reported in this comment</a>. We should treat this as a separate issue.
