### ISSUE TITLE
[Bug]: I get an error when I try to import frida in update 15.1.12

### ISSUE THREAD

**Issue by arjatr** [termux/termux-packages#10129]
### Problem description

I get an error when I try to import frida in update 15.1.12
![Screenshot_20211212-150201328](https://user-images.githubusercontent.com/38409272/145724132-fa9c6c47-0e80-43f1-ab17-5cda01dffb44.jpg)

### What steps will reproduce the bug?

updating version

### System information

Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/root.list.bak
deb https://www.grimler.se/termux-root-packages-24 root stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.243-pixel-g86d2da2c2a83-ab881ba1b70d termux/termux-root-packages#1 SMP PREEMPT Sun Nov 22 22:52:36 UTC 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model: 
Mi A2

**Comment by Grimler91** [comment]
Fixed finally, probably it was frida-elf-cleaner causing the issue, so avoiding frida's cc/cxx wrappers (and purely using termux's toolchain) fixes the issue

**Comment by Grimler91** [comment]
As @sceext2 pointed out `pip install frida` seem to work these days as well, so our package is rather superfluous these days, since static frida-server can be downloaded from frida's release page and python bindings installed through pip
