### ISSUE TITLE
clang issue

### ISSUE THREAD

**Issue by harisont** [termux/termux-packages#1013]
Can't compile a c file including sys/shm.h, I guess that library is missing.

**Comment by its-pointless** [comment]
try installing libandroid-shmem-dev

**Comment by harisont** [comment]
I had tried that already, it didn`t work. I installed both libandroid-shmem and libandroid-shmem-dev

**Comment by Grimler91** [comment]
libandroid-shmem-dev installs it for me. What does `find $PREFIX -name shm.h` tell you?

**Comment by harisont** [comment]
/data/data/com.termux/files/usr/include/linux/shm.h

**Comment by vishalbiswas** [comment]
you also need to add `-landroid-shmem` to linker flags

**Comment by harisont** [comment]
Oh ok, thank you very much!
