### ISSUE TITLE
[Bug]: Bochs' "Bus error".

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#10132]
### Problem description

Hello, Termux community. I have a problem. When I start Bochs on ARM32 I get a "Bus error" error.
Detailed description of the error: termux/x11-packages#447, termux/x11-packages#448, termux/x11-packages#451, termux/x11-packages#454, termux/termux-packages#7645, termux/termux-packages#7695.
Attempts to fix: termux/x11-packages#456, termux/x11-packages#468 (both unsuccessful).

### What steps will reproduce the bug?

1. Install Termux and Bochs on 32-bit ARM device.
2. Launch any OS on Bochs.
3. Finish! Bus error!

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 3.18.140-19180804 termux/x11-packages#1 SMP PREEMPT Thu Jun 24 18:55:07 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J400F

```

**Comment by xtkoba** [comment]
I believe this can be closed now that `bochs` package has been purged for arm. Thanks.
