### ISSUE TITLE
aircrack-ng: broken package

### ISSUE THREAD

**Issue by drygdryg** [termux/termux-packages#10149]
After updating aircrack-ng with commit dc4178c891f5fb0fde7af29370ea8fa0fc20d367, I started seeing issues with airodump-ng and aircrack-ng.

Steps to reproduce:
1. Install `aircrack-ng` package
2. Run `aircrack-ng`
3. Run `airodump-ng` with target interface like `mon0`

Expected behavior: aircrack-ng should show help, airodump-ng should work correctly.
Actual behavior: aircrack-ng crashes with error:
`Could not open '/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa.so': dlopen failed: library "/data/data/com.termux/files/usr/lib/libaircrack-ce-wpa.so" not found`
airodump-ng crashes with error:
```
stack corruption detected (-fstack-protector)
Aborted
```
![image](https://user-images.githubusercontent.com/43933400/110231973-d04d9a00-7f2b-11eb-9041-ccae8536bc13.png)

Additional information: Android 11, Termux 0.108.

Everything worked fine, but it looks like the commit dc4178c891f5fb0fde7af29370ea8fa0fc20d367 broke everything.

**Comment by 2096779623** [comment]
Close it, the problem didn't occur on my device now.
