### ISSUE TITLE
[Bug]: x11vnc exit with reason: "Caught signal: 11"

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#10146]
### Problem description

So i'm running both `Xvfb` (Virtual Framebuffer) and `x11vnc` at the same time. And running some apps like PlasmaShell or Something like Plasma Store inside proot.

When applying themes from Plasma Store / Settings, x11vnc exit by itself with "caught signal: 11" in logs. Even you start it again, it will exit with same log "caught signal: 11" again after connecting atleast 5-10 second.

### What steps will reproduce the bug?

* Make sure you have ANY plasma app installed in your proot
* In Native Termux, Launch Virtual Framebuffer (Xvfb) server, then launch x11vnc server after starting Xvfb server
* Bind your X11 Socket that created by Xvfb to your proot rootfs.
* Launch some plasma apps like Store, Settings, Then do some changes like Change Theme, Cursor, Wallpaper, or other on it.

### What is the expected behavior?

Xvfb is still running. While `x11vnc` exit by itself with `caught signal: 11` error in log files.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
Updatable packages:
proot/stable 5.1.107-42 aarch64 [upgradable from: 5.1.107-41]
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.77+ termux/termux-packages#1 SMP PREEMPT Fri May 28 23:13:48 CST 2021 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1820

```

**Comment by thunder-coding** [comment]
@Yonle is this issue still reproducible? If so please re-open this issue

**Comment by twaik** [comment]
Is this still reproducible?

**Comment by Yonle** [comment]
This is an old issue, and i've changed my host.

No time for reproducing the issue.
