### ISSUE TITLE
[Package request] Reaver

### ISSUE THREAD

**Issue by tahmidamit** [termux/termux-packages#10158]
Reaver implements a brute force attack against Wifi Protected Setup (WPS) registrar PINs. I tried a lot of compiling and it just wouldn't install. It would be a great help if you could just add this to the package manager.

https://github.com/t6x/reaver-wps-fork-t6x

I tried compiling. It always gave this error .
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: wpsmon.o: in function `monitor':
/data/data/com.termux/files/home/reaver-wps-fork-t6x/src/wpsmon.c:332: undefined reference to `ualarm'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: wpsmon.o: in function `parse_wps_settings':
/data/data/com.termux/files/home/reaver-wps-fork-t6x/src/wpsmon.c:433: undefined reference to `ualarm'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:123: reaver] Error 1
$

**Comment by drygdryg** [comment]
Reaver was patched to build with Bionic libc, and now it is successfully being built in Termux.
https://github.com/t6x/reaver-wps-fork-t6x/pull/357

**Comment by 2096779623** [comment]
> Not serving hacking, phishing, spamming, spying, ddos functionality

Close it now.

**Comment by Mradi678** [comment]
Can i use this tool in termux

**Comment by truboxl** [comment]
@Mradi678 please ask in https://github.com/termux-user-repository/tur
