### ISSUE TITLE
Suckless Simple Terminal gives a aborted

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#10150]
![IMG_20210806_220545](https://user-images.githubusercontent.com/86137443/128531693-09c933d1-62fd-459b-860e-743756f2a500.jpg)

**Problem description**
Can't run Suckless Simple Terminal it giving me aborted (sigabrt)

**Steps to reproduce**

Start a tigervnc server
export a display server export DISPLAY=:1
Open a st

**Expected behavior**

I want to open suckless simple terminal

**System information**

Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24 stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 main
Updatable packages:
m4/stable 1.4.19 aarch64 [upgradable from: 1.4.18-3]
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf-g43fb8887b4f5 termux/x11-packages#1 SMP PREEMPT Wed Jul 21 00:37:56 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2007J20CG

**Comment by xtkoba** [comment]
The error reported in https://github.com/termux/termux-packages/issues/10150#issuecomment-1102318823 is not relevant to tagged pointers but seems kind of "invalid `free()`" which is also reproducible on my environment (Android 8.1.0 aarch64). I would like it to have a separate issue, #10124. Thanks.
