### ISSUE TITLE
webkit2gtk: some binaries do not have DT_RUNPATH

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#10159]
**Problem description**

Some binaries of package `webkit2gtk` are not compiled with `DT_RUNPATH`. As result, they fail to start because necessary libraries can't be found.

```
~ $ WebKitWebDriver 
CANNOT LINK EXECUTABLE "WebKitWebDriver": library "libsoup-2.4.so" not found
linker: CANNOT LINK EXECUTABLE "WebKitWebDriver": library "libsoup-2.4.so" not found
~ $ /data/data/com.termux/files/usr/libexec/webkit2gtk-4.0/jsc
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/webkit2gtk-4.0/jsc": library "libjavascriptcoregtk-4.0.so" not found
linker: CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/webkit2gtk-4.0/jsc": library "libjavascriptcoregtk-4.0.so" not found
```

**Comment by xtkoba** [comment]
This is no longer an issue, as of `webkit2gtk` version `2.32.4-2`. I have confirmed that every binary under `bin/`, `lib/` and `libexec/` has a correct `DT_RUNPATH` entry for aarch64 DEB package. Thanks.
