### ISSUE TITLE
gocryptfs / encfs request

### ISSUE THREAD

**Issue by misterhsp** [termux/termux-packages#10153]
Please add gocryptfs and/or encfs to Termux for Rootuser if possible.

Thanks in advance...

**Comment by CodeCubeNeo** [comment]
Can you also add gocryptfs?

**Comment by misterhsp** [comment]
I uploaded a static binary here some time ago.

https://forum.xda-developers.com/t/exe-static-linux-binaries-for-arm-android-cryptsetup-encfs-f2fs-tools-testdisk-photorec.3709380/post-85842109

**Comment by misterhsp** [comment]
gocryptfs 2.3 static (aarch64)

https://forum.xda-developers.com/t/exe-static-linux-binaries-for-arm-android-cryptsetup-encfs-f2fs-tools-testdisk-photorec.3709380/page-26#post-87430953

**Comment by xtkoba** [comment]
Packaging request for gocryptfs is handled in #11891.
