### ISSUE TITLE
Please add PyQt5

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-packages#10165]
**Package description**

PyQt5 is a set of libraries for compatibility between qt5 and python, I would like and I'm sure I wouldn't be the only one you'd like to have this package added to. 

I get this error when installing using pip : 

![Screenshot_20210617-193320](https://user-images.githubusercontent.com/64093255/122488665-8e5cd700-cfa3-11eb-8712-5398242a9f20.png)

**Link to home page and sources**
1. Home page:  https://sourceforge.net/projects/pyqt/files/PyQt5/

**Comment by codemona** [comment]
Is it (PyQt5 and PyQtWebEngine) possible to build for python3.9 or python3.10?
