### ISSUE TITLE
package request : python-gi

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-packages#10161]
**Package description**

Python3-gi is a package that offers the possibility to make gtk apps with python, currently only one dependency (I think) is missing so that it can work. 

**Link to home page and sources**
1. Home page:https://pygobject.readthedocs.io/en/latest/getting_started.html
2. Source code:https://github.com/GNOME/pygobject

**Comment by lakeledr-glitch** [comment]
On Windows, Python treats backslashes as escape characters (`\t`, `\n`, etc.), 
so copying a path directly from Explorer can cause weird results like tabs showing up.  

You can either use a raw string like `r"D:\testfolder"` or normalize the path automatically.

If you want a one-liner that also cleans `../` and expands `~` for cross-platform use, 
you can try this tiny utility I wrote called [ipathy](https://pypi.org/project/ipathy/):

```python
from ipathy import ipathy
print(ipathy("D:\\testfolder"))
# → D:/testfolder
