### ISSUE TITLE
Proposal: grub2

### ISSUE THREAD

**Issue by mvasi90** [termux/termux-packages#10174]
**Package description**
grub2 is a boot loader for Linux.

**Link to home page and sources**
1. Home page: https://www.gnu.org/software/grub/
2. Source code: https://git.savannah.gnu.org/git/grub.git/

**Additional information**
This tool is necessary to make a USB device bootable from Android.
A mobile device is more portable than a laptop.

Thank you.

**Comment by twaik** [comment]
It is not possible to make Android devices bootable without invoking some kernel API's not available on Android devices.

**Comment by twaik** [comment]
I do not hink we can make bootable USB sticks without root tools. It is problematic even with rooted device.
