### ISSUE TITLE
tsu in wrong repo; compile newer version __v3__ this repo

### ISSUE THREAD

**Issue by ChiefMikeK** [termux/termux-packages#10180]
**Package description**
Gain root shell on Termux   
**su** and **sudo** with environment locking

**Link to home page and sources**
1. Home page: https://github.com/cswl/tsu/
2. man(1) https://raw.githubusercontent.com/cswl/tsu/v3.x/docs/tsu.scd

**Additional information**
older version of this pkg is **incorrectly** the base repo.  
https://github.com/cswl/tsu/issues/49
also needs manpage compiled

**Comment by Cebtenzzre** [comment]
tsu is at version 8.6.0 now, so this can be closed.

**Comment by blaccboy66612** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
