### ISSUE TITLE
the rails gem install faild

### ISSUE THREAD

**Issue by zlfera** [termux/termux-packages#102]
first,thank you very much.
when i install rails ,the problem has arisen

 gem install rails --no-ri
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
        ERROR: Failed to build gem native extension.

    /data/data/com.termux/files/usr/bin/ruby -r ./siteconf20151221-20016-1kvezph.rb extconf.rb
mkmf.rb can't find header files for ruby at /data/data/com.termux/files/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/json-1.8.3 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/extensions/arm-linux/2.2.0/json-1.8.3/gem_make.out

**Comment by fornwall** [comment]
> mkmf.rb can't find header files for ruby at /data/data/com.termux/files/usr/lib/ruby/include/ruby.h

Run `apt install ruby-dev` to the the `include/ruby.h` file.

To be able to install rails you will first have to install the `nokogiri` gem in a special way: Install dependencies with

    apt install ruby-dev libxml2-dev libxslt-dev pkg-config make gcc

then install nokogiri with

    gem install nokogiri -- --use-system-libraries

The reason that --use-system-libraries is needed is that otherwise nokogiri tries to build a bundled version of libxml2, which won't work due to scripts there assuming that /bin/ exists (which it doesn't on Android). Linking against the system libraries should however be fine and just save space, since the libxml2 package in Termux contains the patches from upstream that nokogiri wants!

After doing this installation you should be able to install rails - reopen this issue if not!

**Comment by zlfera** [comment]
thanks for your help! the rails is installed,but anthor problem has appeared,when i 'rackup'
this rails app.
###
[~/develop/ruby/xinran/]rackup
/data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from /data/data/com.termux/files/home/develop/ruby/xinran/config/application.rb:7:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /data/data/com.termux/files/home/develop/ruby/xinran/config/environment.rb:2:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /data/data/com.termux/files/home/develop/ruby/xinran/config.ru:3:in `block in <main>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from /data/data/com.termux/files/home/develop/ruby/xinran/config.ru:in `new'
        from /data/data/com.termux/files/home/develop/ruby/xinran/config.ru:in `<main>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
        from /data/data/com.termux/files/usr/bin/rackup:23:in `load'
        from /data/data/com.termux/files/usr/bin/rackup:23:in `<main>'
[~/develop/ruby/xinran/]
###
i do not this is the rails problem or the termux problem. please help me. Thank you.
