### ISSUE TITLE
Gimp : GNU Image Manipulation Program

### ISSUE THREAD

**Issue by CrackByte** [termux/termux-packages#10206]
**Package description**
A cross-platform image editor available for GNU/Linux. I looked through it's dependencies and it seems like it could be possibly ported onto termux. (Maybe..)

**Link to home page and sources**
1. Home page: https://www.gimp.org/
2. Source code: https://github.com/GNOME/gimp

**Comment by B0rner** [comment]
Hey, i like to use gimp on an Intel based Chromebook without using the Chrome OS Linux container.
Is it possible with termux an this gimp package?
I'm new to termux.
What I have todo ro get gimp@termux running?
Is there an documentation for that case?

Thank you.
