### ISSUE TITLE
execinfo.h

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#1020]
Hello,

I'm trying to use the segfault-handler npm module but it does not build because it needs `execinfo.h`.
On Debian this file is part of `libc6-dev` but it does not seem to be available on Termux.
Do you think ti would be possible to add it?

**Comment by fornwall** [comment]
The functions exposed by `execinfo.h` is not available on Android. See [this Stackoverflow question and answers](http://stackoverflow.com/questions/8115192/android-ndk-getting-the-backtrace).

Would a stub header help to get things to compile (but not actually producing any backtrace)?

**Comment by Rudloff** [comment]
Thanks but I don't think a stub would be very useful.
I guess I will have to use gdb instead.

**Comment by goodevilgenius** [comment]
@fornwall That might help me. I'm having this issue because I'm trying to compile `node` in Termux. Compilation fails with `'execinfo.h' file not found`, so if I could get that stub header, that might let me compile node.

**Comment by xeffyr** [comment]
> I'm trying to compile node in Termux. 

Node shouldn't require `execinfo.h` when building for Android if properly [configured](https://github.com/termux/termux-packages/blob/master/packages/nodejs/build.sh).

**Comment by goodevilgenius** [comment]
@xeffyr I didn't configure anything. I'm trying out [`nave`](https://github.com/isaacs/nave) under Termux. I just did `nave install latest`, and it automatically downloaded the latest source and tried to compile it.

But, it has the source downloaded now, so maybe I can see if I can tweak it and see if it'll work.

**Comment by wuxb45** [comment]
What's the proper way to write portable code for the missing header? Is there something like #ifdef termux?

**Comment by xeffyr** [comment]
@wuxb45 Use either `#ifdef __ANDROID__` or `#ifdef __TERMUX__`.
