### ISSUE TITLE
Package Request: cifs-utils

### ISSUE THREAD

**Issue by christianrondeau** [termux/termux-packages#10215]
https://wiki.samba.org/index.php/LinuxCIFS_utils

The goal is to be able to access and mount windows network shares. Alternatives are also welcome! 

    mount -t cifs -o username=USERNAME,password=PASSWORD //192.168.0.1/share /mnt/share

**Comment by twaik** [comment]
Closing this.
As mentioned above this package requires building kernel module. Termux does not implement DKMS or anything similar. And anyway it will not work since in most cases original kernel source is not available on target device.
