### ISSUE TITLE
Mesa: glxgears crashes on 32bit ARM devices

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-packages#10226]
**Problem description**

The window comes out for a few seconds and then disappears

![Screenshot_20210726-122626](https://user-images.githubusercontent.com/64093255/127032377-f4cc25ec-1f05-49ea-aeb5-eefc9f4f893d.png)

Info:
Android 8.0 32 bits
2GB of ram
DE: lxqt
WM: Openbox 
Using vnc

In proot it works, but in termux anything related to OpenGL does not want to work

**Steps to reproduce**

**Expected behavior**

**Comment by xtkoba** [comment]
Note that `mesa-demos`, the package that contains `glxgears`, has been disabled now. This issue is not worth being open.
