### ISSUE TITLE
Package request: Nethack and / or UnNethack

### ISSUE THREAD

**Issue by abers** [termux/termux-packages#1023]
While I realise it is currently possible to play both via SSH, I often find myself on trains with either poor or no internet. Also while there are apps for both on the playstore they do not allow customization of font and colour-scheme and don't recognise all the keys on my physical keyboard. Would be great if it was possible to install these locally via termux instead.

**Comment by its-pointless** [comment]
its annoying to cross compile but easy to compile nethack on device.  Apply this [patch](http://its-pointless.github.io/sys-unix-hints-linuxf.patch). 
`sh sys/unix/setup.sh sys/unix/hints/linux`

**Comment by Neo-Oli** [comment]
@its-pointless Here's where I'm stuck:
```
wget -N "https://sourceforge.net/projects/nethack/files/nethack/3.6.0/nethack-360-src.tgz"
tar -xf nethack-360-src.tgz
cd nethack-3.6.0
patch -p0 <../sys-unix-hints-linuxf.patch
for f in `find -type f`;do
    echo $f
    sed -i 's%/bin/sh%sh%g' $f
done
sh sys/unix/setup.sh sys/unix/hints/linux
make
make install
```
Now I am getting lex  dgn_comp.l
```
make[1]: lex: Command not found
make[1]: *** [Makefile:333: dgn_lex.c] Error 127
make[1]: Leaving directory '/data/data/com.termux/files/home/.bootstrap-builddir/nethack/nethack-3.6.0/util'
make: *** [Makefile:190: dungeon] Error 2
```

Do you now what step I've been missing?

**Comment by its-pointless** [comment]
flex is lex

**Comment by Neo-Oli** [comment]
@its-pointless Thanks. I symlinked lex to flex and now it works. Although it puts the executable in a very weird place, but I guess I can live with that.

**Comment by sdrausty** [comment]
I would like to see this too.

**Comment by kenneth-Q** [comment]
Is this still going on?
I can not find any thing by apt search nethack.
📲

**Comment by its-pointless** [comment]
#2648 ... 
I have it available on my apt repo gcc_termux...

**Comment by xeffyr** [comment]
Package is now available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install nethack
```

In future, it likely will be moved to https://github.com/termux/game-packages.
