### ISSUE TITLE
Select URL doesn't recognise URLs pointing to localhost or localhost:port

### ISSUE THREAD

**Issue by mindbound** [termux/termux-packages#1024]
URLs of the form `http://localhost:port` are not listed in the Select URL submenu (see screenshot). Termux v0.49, Android Marshmallow 6.0.1, armv7 (Samsung Galaxy Tab A).

![tmp_11255-screenshot_20170517-084456250678449](https://cloud.githubusercontent.com/assets/1147991/26140146/bc96b5b4-3add-11e7-93c4-6d8b3a7cc7e6.png)

**Comment by Wetitpig** [comment]
This is a problem of the app rather than the packages.

**Comment by mindbound** [comment]
You're right, I'll move it over there.
