### ISSUE TITLE
[Bug]: github actions: error with gpg

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#10259]
### Problem description

The package cannot be built due to a gpg error. [For example.](https://github.com/termux-pacman/termux-packages/runs/6106739704?check_suite_focus=true)  
[List other packages.](https://github.com/termux-pacman/termux-packages/actions?query=is%3Afailure)

### What steps will reproduce the bug?

auto-update

### System information

This is github actions.

**Comment by Grimler91** [comment]
Should be fixed now, after re-running an upload job for x11-packages, thanks for reporting
