### ISSUE TITLE
[PROPOSAL] Regarding order of auto updating packages

### ISSUE THREAD

**Issue by MrAdityaAlok** [termux/termux-packages#10261]
## Problem

Currently, we assume that a package is not coupled with any specific version of it's dependencies. Therefore,
we update them individually without any specific order. But this assumtion fails for package families like `lxqt` which requires all it's family members to be of specific version.

Although we would have to manually update dependencies in such situation (if they can not be auto-updated), but we can atleast decide order of updation for packages that can be auto-updated.

## Here's my solution/proposal

- Write dependency graph for each package in a json file (otherwise we would have to compute same thing on each run). This graph will only contain dependencies that can be auto-updated, not all.
  - File would be in some what following format:
    ```json
    {
      "package1": ["list of its dependencies"],
      "package2": ["list of its dependencies"]
    }
    ```
- Then decide order of updation from it, at run time (using [topological sorting](https://en.m.wikipedia.org/wiki/Topological_sorting)).

#### Regarding updation of dependency graph

I suggest that we use github action.

For the sake of further explanation, let's assume workflow's name to be `update_graph.yml`.

Whenever (on push only) `packages.yml` workflow runs, a script would check (unless `%ci:no-graph` tag is applied):

  - if dependency has changed of
  - or if auto-update has been enabled for

  packages affected by this push and trigger `update_graph.yml`'s dispatch event with all the required information to update the graph file.

**OR** we may update this manually too 😅.

_Any suggestion or changes are welcome!_

_Again: this is just a proposal. Feel free to close this if you all do not consider this to be problem._

(ping everyone: @termux)

**Comment by Grimler91** [comment]
Would the json file be generated on the fly, or kept separately and maintained?

We are solving sort of the same problem with the [buildorder.py script](https://github.com/termux/termux-packages/blob/master/scripts/buildorder.py), it decides which order to build packages, which should be the same order as one would like to update them (I think), so maybe it would be possible to extend that script for these purposes

**Comment by MrAdityaAlok** [comment]
> Would the json file be generated on the fly?

No, I suggest to generate only when auto update state is changed (i.e enabled or disabled) or its dependencies list changes. Otherwise we would be computing same thing on each run.

> 
> We are solving sort of the same problem with the [buildorder.py script](https://github.com/termux/termux-packages/blob/master/scripts/buildorder.py), it decides which order to build packages, which should be the same order as one would like to update them (I think), so maybe it would be possible to extend that script for these purposes

Yes, it would be more or less the same order. I will look into it and think about extending for auto updating too.

*I should have proposed this in matrix only. No use of such long writings....😅*
