### ISSUE TITLE
[Package]: Dunst 

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/termux-packages#10262]
### Package description

Lightweight and customizable notification daemon

### Home page URL

https://dunst-project.org/

### Source code URL

https://github.com/dunst-project/dunst

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Not yet , but I will try it afterwards

**Comment by xtkoba** [comment]
Packaged in commit 3e123608f9df09a6c7ed8ce5ed711d657da8f10d.
