### ISSUE TITLE
Apache arrow[Package]: 

### ISSUE THREAD

**Issue by Haiz14** [termux/termux-packages#10280]
### Package description

Info: Apache Arrow defines a language-independent columnar memory format for flat and hierarchical data, organized for efficient analytic operations on modern hardware like CPUs and GPUs. The Arrow memory format also supports zero-copy reads for lightning-fast data access without serialization overhead.

### Home page URL

https://arrow.apache.org/

### Source code URL

https://github.com/apache/arrow

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

The documentation  ( https://arrow.apache.org/docs/3.0/r/articles/install.html ) says to install this package using R, but installing R is really problematic on termux one needs to use chroot.

**Comment by Haiz14** [comment]
Tried installation using https://github.com/apache/arrow/blob/master/docs/source/developers/cpp/building.rst, i used this preset --preset ninja-release-python

Got this error : https://pastebin.com/5yyAw16b

**Comment by Haiz14** [comment]
I want to install python package ``pyarrow`` but it requires this cpp dependency.

**Comment by Haiz14** [comment]
I have successfully built the files of the package but i have no idea on how to make a package out of them. Can anyone help ?
```tree
u0_a283@localhost ~/a/c/b/release (master)> tree
.
├── libarrow.so -> libarrow.so.800
├── libarrow.so.800 -> libarrow.so.800.0.0
├── libarrow.so.800.0.0
├── libarrow_dataset.so -> libarrow_dataset.so.800
├── libarrow_dataset.so.800 -> libarrow_dataset.so.800.0.0
├── libarrow_dataset.so.800.0.0
├── libarrow_engine.so -> libarrow_engine.so.800
├── libarrow_engine.so.800 -> libarrow_engine.so.800.0.0
├── libarrow_engine.so.800.0.0
├── libarrow_python.so -> libarrow_python.so.800
├── libarrow_python.so.800 -> libarrow_python.so.800.0.0
├── libarrow_python.so.800.0.0
├── libparquet.so -> libparquet.so.800
├── libparquet.so.800 -> libparquet.so.800.0.0
├── libparquet.so.800.0.0
└── libsubstrait.a

**Comment by xtkoba** [comment]
Yeah, building on device manually is one thing, and building and packaging on CI is another. Only witches and wizards can do the latter.

**Comment by Haiz14** [comment]
How to package a build ?

**Comment by MrAdityaAlok** [comment]
@Haiz14 You will have to write a build recipe.  Learn more here: https://github.com/termux/termux-packages/wiki/Creating-new-package. 
Prebuilt binaries are not accepted.

There's a sample/bootstrap `build.sh` in `samples/`. You may want to start from there.

**Comment by Haiz14** [comment]
I installed `pkg i libarrow-python` but it's not being imported in python

```python
~►python -c "import pyarrow"   Traceback (most recent call last):                              File "<string>", line 1, in <module>                        ModuleNotFoundError: No module named 'pyarrow'
```

**Comment by Haiz14** [comment]
After `pip install pyarrow` the module gets imported but it gives another error 
```python
~►python -c "import pyarrow"   Traceback (most recent call last):                              File "<string>", line 1, in <module>                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: dlopen failed: cannot locate symbol "PyBaseObject_Type" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyarrow/lib.cpython-311.so"...
```

**Comment by nacho00112** [comment]
I'm not able to import pyarrow.orc it raises `ModuleNotFoundError: No module named 'pyarrow._orc'`
