### ISSUE TITLE
Package request: Kotlin

### ISSUE THREAD

**Issue by gut5** [termux/termux-packages#1028]
After yesterday's news of Kotlin becoming a first-class language for Android, I think this would be nice to have.

**Comment by its-pointless** [comment]
if i remember correctly it requires the java jvm. which is not quite ready yet

**Comment by yenon** [comment]
Maybe this will work without a jvm: https://github.com/JetBrains/kotlin-native/

**Comment by addisaden** [comment]
+1

**Comment by vishalbiswas** [comment]
@yenon looks interesting. I'll try it.

**Comment by ralphmujar** [comment]
+1

**Comment by sdrausty** [comment]
```
pacman -Ss kotlin
community/kotlin 1.2.21-1
    The Kotlin programming language
```
Reveals that kotlin is available on device in Arch Linux in Termux PRoot.  

```
pacman -S kotlin
resolving dependencies...
:: There are 2 providers available for java-environment>=8:
:: Repository extra
   1) jdk8-openjdk  2) jdk9-openjdk

Enter a number (default=1): 1
looking for conflicting packages...

Packages (24) hicolor-icon-theme-0.17-1  java-environment-common-3-1  java-runtime-common-3-1
              jdk8-openjdk-8.u111-1  jre8-openjdk-8.u111-1  jre8-openjdk-headless-8.u111-1
              kbproto-1.0.7-1  libice-1.0.9-2  libsm-1.2.2-2  libx11-1.6.5-1  libxau-1.0.8-3
              libxcb-1.12-1  libxdmcp-1.1.2-1  libxext-1.3.3-1  libxmu-1.1.2-1  libxt-1.1.5-1
              nspr-4.18-1  nss-3.35-1  xcb-proto-1.12-3  xdg-utils-1.1.2-1  xextproto-7.3.0-1
              xorg-xset-1.2.3-1  xproto-7.0.31-1  kotlin-1.2.21-1

Total Download Size:    66.88 MiB
Total Installed Size:  187.70 MiB

:: Proceed with installation? [Y/n]
```
Shows us this is a serious install.  Enjoy kotlin and more than eighty four hundred packages on device today through https://sdrausty.github.io/TermuxArch/

**Comment by AnikHasibul** [comment]
Still any hope in termux package repo?

**Comment by its-pointless** [comment]
It works as well as java sdk does. Just tried it then and compiled hello world. The openjdk package is disabled because it doesn't work that well.

**Comment by hyperpallium** [comment]
The kotlin compiler needs `invokedynamic` [Kotlin compiler on android](https://stackoverflow.com/questions/49185851/kotlin-compiler-on-android), which is a Java 8 feature only available in android 8. [`invokedynamic` on android sdk<26 (Oreo)?](https://stackoverflow.com/questions/49441260/invokedynamic-on-android-sdk26-oreo)

So, it "should" run on android 8 - perhaps someone could try this?

Alternatively, it seems that [kotlin compiler only required java 8 from `Kotlin 1.1.2`](https://www.infoworld.com/article/3192713/java/jetbrains-boosts-kotlin-language-compiler-ide-integration.html) - perhaps previous versions will work on all android versions?

**Comment by pycadelic** [comment]
Any progress with making available a kotlin package natively for termux, without arch?

Even if it works only on android 8+, it would be a good addition.

**Comment by kel12345678** [comment]
sorry it s not discussion but i need help i searc few month but no idea

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install d8
```
