### ISSUE TITLE
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "jpeg_destroy_huffman_index" referenced by "libskia.so"...

### ISSUE THREAD

**Issue by franciscod** [termux/termux-packages#103]
Sometime before today, `play-audio` worked perfectly on my env. Not now :(

```
$ play-audio file.mp4
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "jpeg_destroy_huffman_index" referenced by "libskia.so"...

$ play-audio --help
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "jpeg_destroy_huffman_index" referenced by "libskia.so"...

$ play-audio
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "jpeg_destroy_huffman_index" referenced by "libskia.so"...
```

**Comment by franciscod** [comment]
On this stackoverflow question, (stackoverflow.com/questions/28789407/android-native-crash-at-system-lib-libskia-so) user3613696 complains that some app of his worked intermittently on some devices due to Google Play Service updates on the background... but I don't know how to check this

**Comment by fornwall** [comment]
Can you paste the output from `uname -a`?

**Comment by franciscod** [comment]
`Linux localhost 3.4.42-ge38d020-00009-g8ea813e #1 SMP PREEMPT Tue Sep 22 14:10:04 PDT 2015 armv7l Android`

on a XT1032 with Android 5.1

**Comment by fornwall** [comment]
The `play-audio` utility links to `libOpenSLES`, which by chaining links to `libskia`, which links to both `libpng` and `libjpeg`. So if either one of those libraries are installed in Termux in `$PREFIX/lib/` they will cause the above problem.

**Comment by fornwall** [comment]
Thanks! Fixed in the `0.3` version of play-audio, which can be installed with a `apt update && apt upgrade`.

**Comment by franciscod** [comment]
There's problems with files containing spaces. I'm fixing it :)

**Comment by franciscod** [comment]
Now it works, thank you! Following the spaces issue on #110
