### ISSUE TITLE
Estou tendo problemas em executar o "wpscan" no termux, alguém poderia me ajudar nesta questão?

### ISSUE THREAD

**Issue by 918mthzx** [termux/termux-packages#10308]
### Problem description

![Screenshot_2022-04-24-08-42-36-702_com termux](https://user-images.githubusercontent.com/104304849/164974783-e6cdda0f-f307-43fb-bed3-5dc1b973af57.jpg)

### What steps will reproduce the bug?

git clone https://github.com/wpscanteam/wpscan.git
cd wpscan
gem install bundler
bundle install
cd lib
chmod 777 wpscan.rb
ruby wpscan.rb
Porém no "ruby wpscan.rb" está dando o erro, assim como mostrei na imagem. 

### System information

Android 12

Ruby 3.1.2

Termux 0.118.0

**Comment by Grimler91** [comment]
Looks like an issue with the wpscan gem and not termux or our ruby. Open an issue in their repo.

**Comment by 918mthzx** [comment]
> 

Obrigado, mas como posso fazer isso?
