### ISSUE TITLE
[Bug]: Missing usr/include/aio.h

### ISSUE THREAD

**Issue by Leif-W** [termux/termux-packages#10304]
### Problem description

The package `manpages` includes several pages for aio, and the package `ndk-sysroot` has the file `usr/include/linux/aio_abi.h`, but there is no `usr/include/aio.h`.  There is a package `libaio` which provides a `usr/include/libaio.h`.  But `usr/include/linux/aio_abi.h` and `usr/include/libaio.h` define and declare different data types and functions.

### What steps will reproduce the bug?

Install Termux, packages manpages, libaio, dpkg, clang, optionally mlocate, findutils (to verify installed files by searching file system).

Optionally:

`man aio.h`
Copy/paste example C code.
Compile with clang.
See error about missing aio.h.

### What is the expected behavior?

If the `aio.h` and associated function manpages (`man -k aio`) exist, then I should be able to `#include <aio.h>` in code.  Otherwise, perhaps the aio manpages were erroneously included?  Are POSIX aio kernel functions available to users in Android?  Is it root-restricted?  Is there a user level version?  Is it broken or otherwise limited?  If available, what actually provides the aio.h functionality?

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=28256
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 main
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.19.113-23719630 #1 SMP PREEMPT Mon Mar 28 14:12:52 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N986U1
```

**Comment by licy183** [comment]
`<aio.h>` is marked as a missing functionality now in Android bionic libc. See https://android.googlesource.com/platform/bionic/+/master/docs/status.md.

**Comment by Leif-W** [comment]
Thanks for the info.  Further searching, I found the change when that
status.md file was updated, first mentioning aio missing functionality.

https://android-review.googlesource.com/c/platform/bionic/+/568082

Maybe the associated manpages should be removed as well?

Although this functionality is missing from BIONIC, does it still exist in
the kernel?  There's no other way to get to the functions?

**Comment by licy183** [comment]
In my point of view, they may be still existed in the kernel, but may be disabled by SELinux or something else. If they are really needed, you could port it from musl or glibc, and test whether it is available, just as `libandroid-*` packages in the repo.
