### ISSUE TITLE
[Bug]: Problem with Debian buster proot xfce4

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#10301]
### Problem description

I am attempting to install xfce4 within the proot Debian build and getting errors regarding adwaita-icon-theme.

Getting:-
The following NEW packages will be installed:
  adwaita-icon-theme
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
32 not fully installed or removed.
Need to get 10.9 MB of archives.
After this operation, 27.0 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main arm64 adwaita-icon-theme all 3.38.0-1 [10.9 MB]
Err:1 http://deb.debian.org/debian bullseye/main arm64 adwaita-icon-theme all 3.38.0-1
  Connection timed out [IP: 199.232.46.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/a/adwaita-icon-theme/adwaita-icon-theme_3.38.0-1_all.deb  Connection timed out [IP: 199.232.46.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

### What steps will reproduce the bug?

apt install adwaita-icon-theme

### What is the expected behavior?

Item should install .

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=2245
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.org/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Fri Sep 17 17:16:18 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003
```

**Comment by xtkoba** [comment]
This is not a Termux issue. See for example https://www.reddit.com/r/linux4noobs/comments/n6yhaf/debian_x86_can_not_connect_to_debdebianorg_for/.

**Comment by macerg** [comment]
Ok, it's not a termux problem, it's a Debian repo problem but some assistance with fixing or reporting would be appreciated.
