### ISSUE TITLE
[Gtk3] Please enable introspection in gtk3

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-packages#10313]
Hi, currently gobject-introspection works fine in termux, it would be nice to enable this feature in gtk3 so that pygtk works smoothly.

![Screenshot_20220424-093329](https://user-images.githubusercontent.com/64093255/164981733-d4561b14-867f-4aa0-bc87-a590e1cc00d2.png)

**Comment by xtkoba** [comment]
Duplicate of #10138.
