### ISSUE TITLE
[Bug]: openjdk-17: jlink produces ELFs having unsupported flags

### ISSUE THREAD

**Issue by tempaccforissue** [termux/termux-packages#10323]
### Problem description

In Termux, if I use the jlink tool, it produces a runtime successfully, but then if I try to run any of the binaries in that runtime, that binary and the libraries it is linked to show multiple warnings: `WARNING: /path/to/library.so has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)`

### What steps will reproduce the bug?

Create a project like this:
```
HelloWorld
│
├── lib
├── out
└── src
    ├── test
    │   └── HelloWorld.java
    └── module-info.java
```

HelloWorld.java:
```
package test;

public class HelloWorld {
    public static void main(String... args) {
        System.out.println("Hello, world!");
    }
}
```

module-info.java:
```
module helloworld {
    requires java.base;
    
    exports test;
}
```

Compile the sources and archive the class files into a jar:
```
javac `find src -name *.java` -d out
jar cef test.HelloWorld lib/helloworld.jar -C out .
```

Now run the jlink tool to create a minimal runtime image required for this small application along with a launcher script:
```
jlink -p lib --add-modules helloworld --launcher hello=helloworld \
    --no-header-files --no-man--pages --compress 2 --output runtime
```

This should create the application runtime image in the directory named `runtime`.

Now go to the `runtime/bin` directory and run `./hello`, which runs successfully but shows the unsupported flags of some libraries located in the `runtime/lib` directory. Also you can run `./java`, and it itself should also show the same warning.

### What is the expected behavior?

jlink should be able to generate runtime image which can be run perfectly without showing any warning.

[Currently, a workaround is to remove these unsupported flags using the termux-elf-cleaner tool.]

### System information

termux-info:
```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID               TERMUX_APP_PID=4693
TERMUX_IS_DEBUGGABLE_BUILD=0             TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24 stable main
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 main
Updatable packages:
ca-certificates/stable,stable 1:2022.03.29 all [upgradable from: 1:2022.02.01]
gnupg/stable 2.3.5 arm [upgradable from: 2.3.4]
gpgv/stable 2.3.5 arm [upgradable from: 2.3.4]
harfbuzz/stable 4.2.1 arm [upgradable from: 4.2.0]
Android version:
10
Kernel build information:
Linux localhost 4.9.193-perf-g743cb02
#1 SMP PREEMPT Mon Oct 25 17:15:39 CST 2021 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 8A
```

**Comment by tempaccforissue** [comment]
Same warnings are found after building an application image using the jpackage tool. jpackage depends on the jlink to create a runtime image under the hood, but jpackage itself also produces some ELFs which also have the same unsupported flags.

**Comment by tempaccforissue** [comment]
Any way to list all the ELFs in a directory with unsupported flags so that I can remove them using the termux-elf-cleaner tool?

**Comment by agnostic-apollo** [comment]
It's user responsibility to run `termux-elf-cleaner` on custom built binaries. The tool is provided for exactly this reason. Use a `bash` function for `jlink` + `termux-elf-cleaner`  to automatically do it.

https://wiki.termux.com/wiki/FAQ#Why_does_a_compiled_program_show_warnings

>Any way to list all the ELFs in a directory with unsupported flags so that I can remove them using the termux-elf-cleaner tool?

They will automatically be skipped.

https://github.com/termux/termux-elf-cleaner/blob/v1.10/termux-elf-cleaner.cpp#L172
