### ISSUE TITLE
[Bug]: CI failing to build any package (Is openjdk 8 installed?)

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#10332]
### Problem description

CI fails to build any package, saying that

```
================================================================

Package: 000invalid

Syntax check: PASS

Error: /usr/lib/jvm/java-8-openjdk{,-amd64} not found. Is openjdk 8 installed?

================================================================

A problem has been found in 'packages/000invalid/build.sh'.
Checked 0 packages before the first error was detected.

================================================================
##[error]Process completed with exit code 1.
```

### What steps will reproduce the bug?

Push a commit that triggers Packages CI.

Example: https://github.com/termux/termux-packages/actions/runs/2222625495

### What is the expected behavior?

CI should build package without error.

### System information

GitHub Actions

**Comment by xtkoba** [comment]
I suppose this is relevant to commit a7e384c1d9819435a80ad908626abd35fb2fb4ce. @Grimler91 any ideas?

**Comment by Grimler91** [comment]
Yeah, lets revert it for now: https://github.com/termux/termux-packages/commit/4798011417c7bdddd54ca8f69f16edec4fb355c7
