### ISSUE TITLE
[Drivers] Add drivers for opengl

### ISSUE THREAD

**Issue by T-DynamosFans** [termux/termux-packages#10348]
https://user-images.githubusercontent.com/96837234/165354572-d40c76f1-3896-4f33-ad8d-8c711ce09db0.mp4

It's to slow as compared to a compiled kivy application on android
![Screenshot_2022-04-26-22-30-51-367_com realvnc viewer android](https://user-images.githubusercontent.com/96837234/165354282-cd009c22-3652-4f5c-807a-af97c7d6d74f.jpg)

**Comment by truboxl** [comment]
Possible to provide the source? Mesa is using software rasteriser?

**Comment by truboxl** [comment]
Closing in favor of #10103 for alternative driver. We already have GL4ES btw, see https://github.com/termux/x11-packages/pull/466 on how to use.
