### ISSUE TITLE
[Package]: AppImage

### ISSUE THREAD

**Issue by anshiq** [termux/termux-packages#10354]
### Package description

Does termux support AppImage format which is specialy designed for termux.

### Home page URL

https://appimage.org/

### Source code URL

https://appimage.org/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Nothing

**Comment by 2096779623** [comment]
#1278

**Comment by wmcbtech30** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/1278. search for existing issues before opening a new one!
