### ISSUE TITLE
Liblzo fail

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#1036]
The source of the [mirror](http://www.oberhumer.com) has been down. Does anyone have a mirror suggestion? Thanks

**Comment by vishalbiswas** [comment]
Its working for me.

**Comment by Wetitpig** [comment]
Really? 
![screenshot_20170520-133708](https://cloud.githubusercontent.com/assets/25080795/26273373/c171c7aa-3d61-11e7-8d3b-be4cb9f0fae1.png)

**Comment by Wetitpig** [comment]
Also [here](https://gitlab.com/Wetitpig/termux-packages/builds/16767598)

**Comment by vishalbiswas** [comment]
it is down right now

**Comment by Wetitpig** [comment]
I am closing this issue, as there is a corresponding pull request now.
