### ISSUE TITLE
[New Mirror] NJUPT

### ISSUE THREAD

**Issue by kawhicurry** [termux/termux-packages#10379]
Main | deb https://mirrors.njupt.edu.cn/termux/apt/termux-main stable main
-- | --
Root | deb https://mirrors.njupt.edu.cn/termux/apt/termux-root root stable
X11 | deb http://mirrors.njupt.edu.cn/termux/apt/termux-x11 x11 main

The mirror from Nanjing University of Posts and Communications.

**Comment by 2096779623** [comment]
@Grimler91
