### ISSUE TITLE
kivy 

### ISSUE THREAD

**Issue by dcvcv** [termux/termux-packages#10382]
### Package description

Please add kivy package support

### Home page URL

https://www.kivy.org

### Source code URL

https://github.com/kivy/kivy.git

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

https://github.com/kivy/kivy.git

**Comment by xtkoba** [comment]
```bash
pip install kivy
```
