### ISSUE TITLE
ncmpcpp problem

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/termux-packages#10395]
### Problem description

When I try to launch ncmpcpp, it tell me `bad system call`.

![Screenshot](https://user-images.githubusercontent.com/87801676/165901914-e76c1d4f-f6ea-40e2-98d2-4ee6b55941b8.jpg)

P.s : I've configured mod and ncmpcpp config

### What steps will reproduce the bug?

*as shown in above*

### What is the expected behavior?

ncmpcpp will work 

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP_PID=753
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+4b3b1a5                                  Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.19.95-perf+ #1 SMP PREEMPT Wed Mar 9 15:55:27 CST 2022 aarch64 Android
Device manufacturer:
vivo
Device model:
V2027
```

**Comment by MrAdityaAlok** [comment]
@NoNameMan1231 uncomment following line in your mpd.conf and ping me if your issue is fixed.
```
#bind_to_address		"/data/data/com.termux/files/usr/var/run/mpd.socket"
```
Must me around line 91.
