### ISSUE TITLE
Lunch pycharm

### ISSUE THREAD

**Issue by Corleone1986** [termux/termux-packages#10401]
$ apt update -y && pkg install curl proot tar -y && curl https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu20/ubuntu20.sh | bash && touch pycharm.sh && echo "#! /usr/bin/bash" > pycharm.sh && echo "./start-ubuntu20.sh<<echo"./start-pycharm.sh"">> pycharm.sh && echo "./start-pycharm.sh">> pycharm.sh && chmod ugo+x pycharm.sh && touch pycharm-install && echo "apt update -y && apt upgrade -y && apt install wget -y && wget https://gitlab.com/mrognor/pycharm-on-android/-/archive/master/pycharm-on-android-master.tar.gz && tar -xvf pycharm-on-android-master.tar.gz && cd pycharm-on-android-master && chmod ugo+x pycharm-install.sh && ./pycharm-install.sh && cd">pycharm-install.sh && chmod ugo+x pycharm-install.sh && ./start-ubuntu20.sh<pycharm-install.sh && rm ./pycharm-install.sh && rm ./pycharm-install && echo "Pycharm mounted and loaded. You can start it using ./pycharm.sh command (or you can type ./p and press tab)"
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.bintray.com:443
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.bintray.com:443
Hit:2 https://packages.termux.org/apt/termux-main stable InRelease
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by Corleone1986** [comment]
Help me

**Comment by licy183** [comment]
See #6726.

**Comment by Corleone1986** [comment]
I dont undestand

**Comment by licy183** [comment]
Use `termux-change-repo` to switch mirror and run `pkg up` to upgrade all the packages. Seems like you are using a very old version of `termux`. If possible, please download it from `F-Droid` or `Github Release`.

**Comment by FernandoJoaquimJofrisse** [comment]
Muito obrigado 🫂🫂🫂
