### ISSUE TITLE
[Package]: openjdk-18

### ISSUE THREAD

**Issue by HelpyFazbear** [termux/termux-packages#10424]
### Package description

JDK 18 is the open-source reference implementation of version 18 of the Java SE Platform, as specified by by JSR 393 in the Java Community Process.

### Home page URL

https://openjdk.java.net/projects/jdk/18/

### Source code URL

https://github.com/openjdk/jdk18/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_Please do not remove openjdk-17 from repo, keep both until openjdk-19 launch_

**Comment by xtkoba** [comment]
We won't package non-LTS versions of OpenJDK. Thanks.
