### ISSUE TITLE
[Package]: libgtk-3-dev ,libxml2-dev

### ISSUE THREAD

**Issue by anshiq** [termux/termux-packages#10428]
### Package description

libgtk-3-dev ,libxml2-dev are not present in termux repo. I was trying to compile BlueFish code editor these two tool are must require to compile the bluefish. 

### Home page URL

http://archive.debian.org/

### Source code URL

http://archive.debian.org/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
`gtk3` in x11 repo and `libxml2` in main repo.
