### ISSUE TITLE
Emacs + termux-open-url = segfault

### ISSUE THREAD

**Issue by mardukbp** [termux/termux-packages#1042]
In eshell I tried `termux-open-url http://www.google.com` and I got a segmentation fault. I would really like to be able to open links in org-mode.

Thanks for this awesome app!

**Comment by Grimler91** [comment]
Hi, same issue as in https://github.com/termux/termux-app/issues/315?

Which arch and android version do you have?

**Comment by mardukbp** [comment]
Yep, same issue. I am running Android 7.0 on a Galaxy Tab S2 with a Snapdragon 652 (ARMv8-A). As per the comments in the issue you linked, it seems to be a problem with Nougat. Hopefully someone will figure out a solution. I guess it is better to close this issue.
