### ISSUE TITLE
[Bug]: cant use apt update

### ISSUE THREAD

**Issue by TUNBudi06** [termux/termux-packages#10449]
### Problem description

I cant update apt because error of unexpected file size

Even try to changing the repo

` Termux primary host (USA) selected
    Changing main repository                                    Running apt update
Ign:1 https://packages.termux.org/apt/termux-main stable InRelease
Get:1 https://packages.termux.org/apt/termux-main stable InRelease [14.0 kB]                                                    Get:2 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages [413 kB]                                         Err:2 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages
  File has unexpected size (414324 != 413430). Mirror sync in progress? [IP: 216.18.208.173 443]
  Hashes of expected file:
   - Filesize:413430 [weak]                                        - SHA512:65e26bb3c81010bc19f9b4147d01f93f73b433e2b60d2a1850c9033524028b220c39131d75847eb0b6514692fc23f893d369d7c15ee950c1b5b408f5ce8095de
   - SHA256:d20017f3724caef5477f052e72ada09bbd896e5acb99f295a9859d3e2a47b512
   - SHA1:2126dbad1dd80a7e4cd2c533769b537a4cc66cd6 [weak]          - MD5Sum:87f336cfb425bc7d19c0a994d10a61e2 [weak]               Release file created at: Mon, 02 May 2022 00:28:04 +0000
Fetched 14.0 kB in 15s (954 B/s)                                Reading package lists... Done
E: Failed to fetch https://packages.termux.org/apt/termux-main/dists/stable/main/binary-aarch64/Packages.bz2  File has unexpected size (414324 != 413430). Mirror sync in progress? [IP: 216.18.208.173 443]                                                       Hashes of expected file:
    - Filesize:413430 [weak]
    - SHA512:65e26bb3c81010bc19f9b4147d01f93f73b433e2b60d2a1850c9033524028b220c39131d75847eb0b6514692fc23f893d369d7c15ee950c1b5b408f5ce8095de
    - SHA256:d20017f3724caef5477f052e72ada09bbd896e5acb99f295a9859d3e2a47b512
    - SHA1:2126dbad1dd80a7e4cd2c533769b537a4cc66cd6 [weak]
    - MD5Sum:87f336cfb425bc7d19c0a994d10a61e2 [weak]
   Release file created at: Mon, 02 May 2022 00:28:04 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
~ $ `

My android is 12L

### What steps will reproduce the bug?

Try update packages

### What is the expected behavior?

apt update

### System information

termux-info:

```
[*] Termux primary host (USA) selected
    Changing main repository                                    [*] Running apt update
Ign:1 https://packages.termux.org/apt/termux-main stable InRelease
Get:1 https://packages.termux.org/apt/termux-main stable InRelease [14.0 kB]                                                    Get:2 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages [413 kB]                                         Err:2 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages
  File has unexpected size (414324 != 413430). Mirror sync in progress? [IP: 216.18.208.173 443]
  Hashes of expected file:
   - Filesize:413430 [weak]                                        - SHA512:65e26bb3c81010bc19f9b4147d01f93f73b433e2b60d2a1850c9033524028b220c39131d75847eb0b6514692fc23f893d369d7c15ee950c1b5b408f5ce8095de
   - SHA256:d20017f3724caef5477f052e72ada09bbd896e5acb99f295a9859d3e2a47b512
   - SHA1:2126dbad1dd80a7e4cd2c533769b537a4cc66cd6 [weak]          - MD5Sum:87f336cfb425bc7d19c0a994d10a61e2 [weak]               Release file created at: Mon, 02 May 2022 00:28:04 +0000
Fetched 14.0 kB in 15s (954 B/s)                                Reading package lists... Done
E: Failed to fetch https://packages.termux.org/apt/termux-main/dists/stable/main/binary-aarch64/Packages.bz2  File has unexpected size (414324 != 413430). Mirror sync in progress? [IP: 216.18.208.173 443]                                                       Hashes of expected file:
    - Filesize:413430 [weak]
    - SHA512:65e26bb3c81010bc19f9b4147d01f93f73b433e2b60d2a1850c9033524028b220c39131d75847eb0b6514692fc23f893d369d7c15ee950c1b5b408f5ce8095de
    - SHA256:d20017f3724caef5477f052e72ada09bbd896e5acb99f295a9859d3e2a47b512
    - SHA1:2126dbad1dd80a7e4cd2c533769b537a4cc66cd6 [weak]
    - MD5Sum:87f336cfb425bc7d19c0a994d10a61e2 [weak]
   Release file created at: Mon, 02 May 2022 00:28:04 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
~ $
```

**Comment by T-DynamosFans** [comment]
Same on arm
```
$ apt update
Ign:1 https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce InRelease
Get:2 https://packages-cf.termux.org/apt/termux-main stable InRelease [14.0 kB]
Hit:3 https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce Release
Ign:4 https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce Release.gpg
Get:5 https://packages-cf.termux.org/apt/termux-main stable/main arm Packages [408 kB]
Err:5 https://packages-cf.termux.org/apt/termux-main stable/main arm Packages
  File has unexpected size (408934 != 408269). Mirror sync in progress? [IP: 104.21.20.145 443]
  Hashes of expected file:
   - Filesize:408269 [weak]
   - SHA512:ef3b372b060e5f07abecab02e842f1eb2a8a475639ce68552aa58fad77b452f35e0a84a86430a74e33bcfea5febdb0a7d4399fee7904b7893ffee22161b693f6
   - SHA256:cc3ca4d2656084df7f23e9677f154a1dcef9f20b7bb6f1360b538cff6a909ac9
   - SHA1:e89cd6b286ee1cbbea5909d7397eb9ea92808ca7 [weak]
   - MD5Sum:d07372117946fb04a711fe04f9e51e09 [weak]
  Release file created at: Mon, 02 May 2022 00:28:04 +0000
Get:6 https://packages.termux.org/apt/termux-x11 x11 InRelease [14.0 kB]
Get:7 https://packages-cf.termux.org/apt/termux-main stable/main arm Contents (deb) [1803 kB]
Err:7 https://packages-cf.termux.org/apt/termux-main stable/main arm Contents (deb)

Get:8 https://packages.termux.org/apt/termux-x11 x11/main arm Packages [94.5 kB]
Get:9 https://packages.termux.org/apt/termux-x11 x11/main arm Contents (deb) [1246 kB]
Fetched 1368 kB in 11s (125 kB/s)
Reading package lists... Done
E: Failed to fetch https://packages-cf.termux.org/apt/termux-main/dists/stable/main/binary-arm/Packages.bz2  File has unexpected size (408934 != 408269). Mirror sync in progress? [IP: 104.21.20.145 443]
   Hashes of expected file:
    - Filesize:408269 [weak]
    - SHA512:ef3b372b060e5f07abecab02e842f1eb2a8a475639ce68552aa58fad77b452f35e0a84a86430a74e33bcfea5febdb0a7d4399fee7904b7893ffee22161b693f6
    - SHA256:cc3ca4d2656084df7f23e9677f154a1dcef9f20b7bb6f1360b538cff6a909ac9
    - SHA1:e89cd6b286ee1cbbea5909d7397eb9ea92808ca7 [weak]
    - MD5Sum:d07372117946fb04a711fe04f9e51e09 [weak]
   Release file created at: Mon, 02 May 2022 00:28:04 +0000
E: Failed to fetch https://packages-cf.termux.org/apt/termux-main/dists/stable/main/Contents-arm.gz
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
Termux Info
```
Termux Variables:
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# sources.list.d/termux-desktop-xfce.list
deb [trusted=yes arch=all] https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce extras
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.190-perf-gba91b47 #1 SMP PREEMPT Tue Mar 8 15:43:19 CST 2022 armv8l Android
Device manufacturer:
Xiaomi
Device model:
M2006C3MII
```

**Comment by baovietnam2000** [comment]
same problem, but two days ago can run apt update and apt upgrade comment. Today run again and have error as above. I am trying fix it but not fix yet.

**Comment by alexvng** [comment]
Also having same problem. Using `termux-change-repo` and switching to Grimler's as suggested in other threads does not help. Device is Pixel 4a, android version is 12.

**Comment by GuriZenit** [comment]
Probably the server is down

**Comment by GuriZenit** [comment]
Actually we can't do anything, even installing any package shows the same error.

**Comment by baovietnam2000** [comment]
> Actually we can't do anything, even installing any package shows the same error.

yes, correctly

**Comment by GuriZenit** [comment]
I just found the solution for now. Use `termux-change-repo` and select the Alibaba mirror.

**Comment by baovietnam2000** [comment]
I found and fixed successful:
1. run command "termux-change-repo"
2. at first screen: select all
3. at second screen, select the second , if not success, select next untill run successful.
My termux can update and upgrade now

**Comment by GuriZenit** [comment]
> Also having same problem. Using `termux-change-repo` and switching to Grimler's as suggested in other threads does not help. Device is Pixel 4a, android version is 12.

Maybe you don't select first with space before enter. Go to Grimler's and press space, then enter.

**Comment by baovietnam2000** [comment]
> I just found the solution for now. Use `termux-change-repo` and select the Alibaba mirror.

tks my dear, I follow your comment then fixed successful

**Comment by TUNBudi06** [comment]
Still cant to update it,even i try lot of them.and i cant find Alibaba repository

**Comment by baovietnam2000** [comment]
> Still cant to update it,even i try lot of them.and i cant find Alibaba repository

in second screen, just select the second, and enter

**Comment by TUNBudi06** [comment]
'''[*] Termux primary host (USA) selected
    Changing main repository
[*] Running apt update
Get:1 https://packages.termux.org/apt/termux-main stable InRelease [14.0 kB]
Get:2 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages [413 kB]
Err:2 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages
  File has unexpected size (414324 != 413430). Mirror sync in progress? [IP: 216.18.208.172 443]
  Hashes of expected file:
   - Filesize:413430 [weak]
   - SHA512:65e26bb3c81010bc19f9b4147d01f93f73b433e2b60d2a1850c9033524028b220c39131d75847eb0b6514692fc23f893d369d7c15ee950c1b5b408f5ce8095de
   - SHA256:d20017f3724caef5477f052e72ada09bbd896e5acb99f295a9859d3e2a47b512
   - SHA1:2126dbad1dd80a7e4cd2c533769b537a4cc66cd6 [weak]
   - MD5Sum:87f336cfb425bc7d19c0a994d10a61e2 [weak]
  Release file created at: Mon, 02 May 2022 00:28:04 +0000
Reading package lists... Done
E: Failed to fetch https://packages.termux.org/apt/termux-main/dists/stable/main/binary-aarch64/Packages.bz2  File has unexpected size (414324 != 413430). Mirror sync in progress? [IP: 216.18.208.172 443]
   Hashes of expected file:
    - Filesize:413430 [weak]
    - SHA512:65e26bb3c81010bc19f9b4147d01f93f73b433e2b60d2a1850c9033524028b220c39131d75847eb0b6514692fc23f893d369d7c15ee950c1b5b408f5ce8095de
    - SHA256:d20017f3724caef5477f052e72ada09bbd896e5acb99f295a9859d3e2a47b512
    - SHA1:2126dbad1dd80a7e4cd2c533769b537a4cc66cd6 [weak]
    - MD5Sum:87f336cfb425bc7d19c0a994d10a61e2 [weak]
   Release file created at: Mon, 02 May 2022 00:28:04 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
~ $'''


Still unable

**Comment by TUNBudi06** [comment]
```~ $ termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.14.186-GearKernel-v1-Stockholm #1 SMP PREEMPT Fri Mar 18 11:17:01 UTC 2022 aarch64 Android
Device manufacturer:
realme
Device model:
M2102K1C
~ $```

My termux info

**Comment by licy183** [comment]
Select a mirror in the list rather than `packages(-cf).termux.org` and try again. There seems to be something wrong with the main repo.

**Comment by tigran123** [comment]
I had the same problem, executed `termux-change-repo` and switched to `grimler.se` repository and now `pkg upgrade` works.

**Comment by TUNBudi06** [comment]
Well right now is working because IM literally don't know when use graphic ui is just be tap it to choose,but im using Arrow in the keyboard lol😅


That why the repo not change and still using main host
