### ISSUE TITLE
[Bug]: Cannot install Texlive (actually, pdflatex) (updated)

### ISSUE THREAD

**Issue by distobs** [termux/termux-packages#10459]
### Problem description

Texlive will not install.

After installing the updated (2022) version of TexLive, I executed `termux-install-tl`. After the installation ended, it said that it was going to apply some patches, then asked me to press 'c' to continue. I could not even press the key, as the program aborted (it said "[1] aborting...) immediately.

### What steps will reproduce the bug?

1. `apt install texlive-installer -yq`
2. `termux-install-tl`

### What is the expected behavior?

Install texlive correctly.

Well, actually I was able to use pdftex after the installation, but not pdf*la*tex, which was not even installed (at least not to $PATH)

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=5520
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.113-perf-g7d9395c051b3 #1 SMP PREEMPT Wed Nov 10 19:41:42 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2010J19SL

```

**Comment by Grimler91** [comment]
Did you change any of the settings in the install-tl TUI? Which scheme did you install?

> not pdflatex, which was not even installed (at least not to $PATH)

pdflatex format file needs to be generated, and PATH updated before `pdflatex` works. If installer failed at patching step then that have not yet been done, try running installer again

**Comment by distobs** [comment]
I didn't change anything in the configs.

I will try to rerun the installer.

**Comment by distobs** [comment]
It worked. Just a matter of rerunning the installer :).

I'm sorry for wasting your time.
