### ISSUE TITLE
termux-info: wrong version

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#1045]
I'm using 0.50 and it says 0.48:
```Termux version:
<=0.48
Installed Termux apps:
package:com.termux.api  installer=org.fdroid.fdroid
package:com.termux  installer=org.fdroid.fdroid
Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.0-perf-gcfd5b27 #1 SMP PREEMPT Fri May 12 11:39:13 BST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
6.0.1
Device manufacturer:
Fairphone
Device model:
FP2
```

**Comment by Wetitpig** [comment]
It must be fixed for every Termux version.

**Comment by sdrausty** [comment]
After upgrading from f-droid v.48 to f-droid v.50 -- ditto:
![screenshot_20170525-225058](https://cloud.githubusercontent.com/assets/27742457/26478840/1135edea-419d-11e7-8f20-cdebd0184c6a.png)
![screenshot_20170525-225207](https://cloud.githubusercontent.com/assets/27742457/26478847/1e2b1aa2-419d-11e7-8a3d-d9235b6ac4f8.png)

😀

**Comment by Neo-Oli** [comment]
It is like that because there is currently no way to detect the termux version from termux itself. When I did this script I put <=0.48 in there because I was hoping there would be a way to detect it when the pull request was merged. It requires an update to the main termux-app. My suggestion is that Termux create a file, maybe in /data/data/com.termux/version, where it put the current version number.

**Comment by Rudloff** [comment]
We could use aapt to do this.
First to get the APK path:
```bash
pm list packages -f|grep "com.termux\$"
```
Then to get the version:
```
aapt dump badging /data/app/com.termux-2/base.apk|grep versionName
```


If you create a file containing the current version, I suggest you use the standard `os-release` [format](https://www.freedesktop.org/software/systemd/man/os-release.html) used by most Linux distributions.

**Comment by Neo-Oli** [comment]
@Rudloff Hmm... that leaves me with `ERROR: dump failed because the resource table is invalid/corrupt.`
Anyway,  this is not a good solution, because it means that aapt would need to be pre-installed on Termux. 

But I like your os-release suggestion.

**Comment by Rudloff** [comment]
Any news on this?

I think we could add the following info into an os-release file:
```
NAME="Termux"
VERSION="0.59"
ID=termux
PRETTY_NAME="Termux 0.59"
VERSION_ID="0.59"
HOME_URL="https://termux.com/"
BUG_REPORT_URL="https://github.com/termux/termux-app/issues"
```

**Comment by xeffyr** [comment]
Version is no longer shown after fixing https://github.com/termux/termux-packages/issues/1426. Closing.
