### ISSUE TITLE
[Package]: add some mate-desktop packages

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-packages#10468]
### Package description

several mate-desktop components are missing

### Home page URL

https://github.com/mate-desktop

### Source code URL

https://github.com/mate-desktop

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

a while ago I compiled many mate apps successfully on my device (using the source files provided by debian), I only had difficulty with mate-settings-manager and caja in cross-compilation

**Comment by truboxl** [comment]
Closing. Caja and mate-settings-daemon has been packaged. Please be specific if you meant other apps not yet packaged.
