### ISSUE TITLE
[Package]: Gnu Octave

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#10482]
### Package description

Powerful mathematics-oriented syntax with built-in 2D/3D plotting and visualization tools

### Home page URL

https://www.gnu.org/software/octave/index

### Source code URL

https://ftp.gnu.org/gnu/octave/octave-7.1.0.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by tathastu871** [comment]
Requires Fortran compiler

**Comment by xtkoba** [comment]
Duplicate of #387.
