### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mdsarowarhossain** [termux/termux-packages#10491]
### Problem description

Cannot access android/data section in iternal storage 

### What steps will reproduce the bug?

Make features to accses Android/data directory files 

### System information

termux-info:

```

```
Android 11

**Comment by T-DynamosFans** [comment]
Invalid
For storage
```
termux-setup-storage
```
Now you can cd /sdcard or cd storage/shared

**Comment by Mdsarowarhossain** [comment]
> Invalid
> For storage
> ```
> termux-setup-storage
> ```
> Now you can cd /sdcard or cd storage/shared

am already give this permission
