### ISSUE TITLE
gtksourceview major version mismatches gtkmm major version

### ISSUE THREAD

**Issue by xloem** [termux/termux-packages#10500]
I tried to build gtksourceviewmm and noticed this inconsistency.

termux-packages has gtkmm-3 and gtksourceview4 . This appears at a first glance to mean there is no release of https://gitlab.gnome.org/GNOME/gtksourceviewmm that builds, newer ones wanting a gtkmm upgrade, and older ones wanting a gtksourceview downgrade.

**Comment by xtkoba** [comment]
Yes, you can request different versions of gtkmm and/or gtksourceview. Thanks!
