### ISSUE TITLE
Package request: Older php(5) for mediawiki

### ISSUE THREAD

**Issue by prid** [termux/termux-packages#1050]
The newest version of php (7.1+) is not well supported by mediawiki, I'm running a mediawiki server on my phone. It'd be greatly appreciated if php5 is added as a package.

**Comment by Wetitpig** [comment]
Actually how much storage for packages is there?

**Comment by tigran123** [comment]
Oh, does the included (7.1.x) php actually work with apache2 in Termux? When I started apache (apachectl start) and pointed the browser to the phone (having copied by web application, this one [http://urantiaexplorer.org](urantiaexplorer.org) to the place where "It worked" index.html file was) the server did not handle index.php, i.e. it just displayed the source.

So, I need to enable PHP in apache's httpd.conf, but I can't see the libphp.so module anywhere. So, how do I do that? Or do I need some other package which contains the php module that will be used by apache in Termux?

**Comment by Neo-Oli** [comment]
@tigran123 OP was probably using some other web server (apache2 is brand new in termux) like lighttpd or nginx. PHP works fine when used as CGI or as a FastCGI server. This should work in apache2 too. But I agree it would be nice to have the php module in apache2. @tigran123 you should create a separate issue for that.

**Comment by tigran123** [comment]
Thanks, I've done that: #1074

**Comment by fornwall** [comment]
[Mediawiki now officially supports php 7.1](https://www.mediawiki.org/wiki/Compatibility#PHP), so I'll close this issue.

If someone wants to host a php5 Termux package it would be great, but I think that for the core package repository we should focus on php7!
