### ISSUE TITLE
gh miss comletion script

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-packages#10521]
See <https://github.com/cli/cli/blob/cf4b73ff958b272cf3c9c0cf9351459f76b793a0/pkg/cmd/completion/completion.go>, in other distribution, after compiling, they will generate the completion script auto.

**Comment by xtkoba** [comment]
Should be fixed by commit e70ca1281eba1e054fe458c69b6ee7e4e8bc265b. Thanks.
