### ISSUE TITLE
Some packages available on apt not present in packages/ directory

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#1053]
Why are `speex` and `lrzsz` missing from the list?

**Comment by Wetitpig** [comment]
And also `man-dev`

**Comment by xeffyr** [comment]
lrzsz was moved to disabled packages ([commit](https://github.com/termux/termux-packages/commit/4da01a4d6a8fcf0bf5aa389eee6f614f0d863f4f)), and 'man-dev' is part of the package 'man'.

**Comment by fornwall** [comment]
Thanks - they were old remains which has now been removed from the apt repository.
