### ISSUE TITLE
[Package]: NodeJS 18 

### ISSUE THREAD

**Issue by zairullahdev** [termux/termux-packages#10531]
### Package description

Update NodeJS please i need it

### Home page URL

https://nodejs.org

### Source code URL

https://github.com/nodejs/node

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

No, i didn't try yet

**Comment by xtkoba** [comment]
#10265

**Comment by thunder-coding** [comment]
Apparently #10266 is blocked due to #102777

**Comment by thunder-coding** [comment]
Fixed by #10265
