### ISSUE TITLE
Extract tar file with hard links

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#1054]
Hello,

I need to extract tar files that contain hard links. (They're not created by me so I can't recreate them without the links.)
I get this error when using tar:
```
Cannot hard link to './foo': Permission denied
```
I understand this is a limitation of Android.

But do you think it might be possible to patch tar to either:
* Ignore the links and continue extracting.
* Create a symlink instead.
* Copy the entire file instead of trying to create a link.

**Comment by Wetitpig** [comment]
Have you checked this?
`--hard-dereference     follow hard links; archive and dump the files they refer to`

**Comment by Neo-Oli** [comment]
You can use proot for this. It will convert hardlinks to symlinks.

`proot --link2symlink tar -C gentoo -xf stage3-arm64-arm64-20170223.tar.bz2`

**Comment by Rudloff** [comment]
`--hard-dereference` only works when creating archives, not extracting them.
But proot seems to do the trick, thanks!
