### ISSUE TITLE
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.3" not found

### ISSUE THREAD

**Issue by Abhin7363** [termux/termux-packages#10550]
Please help me to fix this

**Comment by xtkoba** [comment]
Update your `openssl` package or alternatively

```bash
pkg up
```

**Comment by thunder-coding** [comment]
Follow #9050 on how to recover from a broken environment. Also with 3de8caaa47d714d7e5cd7d7a159f678c61e04c02, partial upgrades should not be possible. Should have done this fix earliest itself, but didn't notice it during OpenSSL upgrade
