### ISSUE TITLE
[Package]: Vs code

### ISSUE THREAD

**Issue by iamanshik** [termux/termux-packages#10568]
### Package description

Vs code is a open source code editor.

### Home page URL

https://code.visualstudio.com/

### Source code URL

https://github.com/microsoft/vscode/releases

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by wmcbtech30** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/7641
