### ISSUE TITLE
Tab completion for man command broken in Bash

### ISSUE THREAD

**Issue by brbsix** [termux/termux-packages#1056]
Tab completion for the man command is broken in the Bash shell. To illustrate this, enter `man` <kbd>Tab</kbd> and you will be presented with the following:

> 'Command'  'w3mman'   No         did        from       package
> 'w3m'      Command    command    found,     mean:      you

The completion script runs `manpath` in an attempt to get *MANPATH*, but the command is not available.
As an end user, this can be remedied by adding the following to your *~/.bashrc* (or shell initialization file):

    export MANPATH=$PREFIX/share/man${MANPATH:+:$MANPATH}

As a more permanent solution, the man completion script in the bash-completion package should probably be patched with something along the lines of:

    --- /data/data/com.termux/files/usr/share/bash-completion/completions/man	2017-03-07 02:16:02.000000000 -0800
    +++ man	2017-05-25 10:05:07.344987728 -0700
    @@ -57,9 +57,7 @@
         fi
     
         local manpath="$MANPATH"
    -    [[ -z $manpath ]] && \
    -        manpath=$( manpath 2>/dev/null || command man -w 2>/dev/null )
    -    [[ -z $manpath ]] && manpath="/usr/share/man:/usr/local/share/man"
    +    [[ -z $manpath ]] && manpath="$PREFIX/share/man"
     
         # determine manual section to search
         local sect

**Comment by fornwall** [comment]
Thanks a lot - your proposed patch has been applied in version `2.5-1` of the bash-completion package, which is now available in the package repository!
