### ISSUE TITLE
[Package]: libadwaita

### ISSUE THREAD

**Issue by gmg137** [termux/termux-packages#10570]
### Package description

Building blocks for modern GNOME applications.

 I rely on this library when I want to compile many gtk4 applications.

### Home page URL

https://gitlab.gnome.org/GNOME/libadwaita

### Source code URL

https://gitlab.gnome.org/GNOME/libadwaita

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I tried to compile the library, but it requires gtk4 version >= 4.5.

**Comment by xtkoba** [comment]
Newer `gtk4` has build issue with respect to EGL which is not supported on Termux (currently). Ref: #10504. We have to solve this first, unless any older version of `libadwaita` supports as old version of `gtk4` as `4.3.0`.
