### ISSUE TITLE
Server issues 

### ISSUE THREAD

**Issue by prasantdebnath** [termux/termux-packages#10582]
I am prasant debnath recently I have install termux and was trying to update , upgrade and trying to install mariadb in termux as i have to do project. But i am unable to install because of the server issues.cna you please  solve this issue as soon as possible.

Thank you

**Comment by MrAdityaAlok** [comment]
Paste output of `termux-info` command.

**Comment by MedzikUser** [comment]
Is termux installed from play store? If so, then install from fdroid.

**Comment by thunder-coding** [comment]
Seems like you should see #6726
