### ISSUE TITLE
[Bug]: Bash ... Permission denied

### ISSUE THREAD

**Issue by unweyalazar** [termux/termux-packages#10591]
### Problem description

Good morning. I wanted to report a problem with the library "clang" because when I use it and put the command g++ [file] I get "bash: ./a.out: Permission denied" I would like to know how to solve it.

### What steps will reproduce the bug?

Use the clang package with a file and try to run it with the command "g++ [c++ file]" and use the command "./a.out".

### What is the expected behavior?

The .cpp file to be executed 

### System information

termux-info:

bash: ./a.out: Permission denied

**Comment by MrAdityaAlok** [comment]
Plase paste output of `termux-info`. If possible then also your 'file'.

**Comment by MedzikUser** [comment]
`chmod +x a.out`

**Comment by MrAdityaAlok** [comment]
Plase paste output of `termux-info`. If possible then also your 'file'.

**Comment by MrAdityaAlok** [comment]
> `chmod +x a.out`

I think it should have executable permission by default? (Unless and until it is compiled out $PREFIX)

**Comment by MedzikUser** [comment]
> > `chmod +x a.out`
> 
> I think it should have executable permission by default? (Unless and until it is compiled outside $PREFIX)

The compiler should set the binary as executable. I don't know the details, I wrote a command that *may* help.

**Comment by agnostic-apollo** [comment]
Likely trying to execute file in external storage `/sdcard`, that is not supported, its mounted as `noexec`. Compile under `$HOME`.

https://wiki.termux.com/wiki/Internal_and_external_storage

**Comment by itsmeallejandro** [comment]
I have a similar problem trying to run a file ![Screenshot_2023-10-22-11-56-29-17_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/termux/termux-packages/assets/107738117/3d27575b-9fe9-46d9-8b5e-10459f56e4c5)
