### ISSUE TITLE
Package request: gnuit

### ISSUE THREAD

**Issue by rlfrazier** [termux/termux-packages#1059]
Hello,

It would be useful to have GNUIT, which I've been using as a shell browser/file manager since it came out in the 1990s.

Best wishes,
Bob

----- cut here -----

gnuit - GNU Interactive Tools
Introduction to gnuit

gnuit (GNU Interactive Tools) is a set of interactive text-mode tools, closely integrated with the shell. It contains an extensible file system browser, an ascii/hex file viewer, a process viewer/killer and some other related utilities and shell scripts.

It can be used to increase the speed and efficiency of most of the daily tasks such as copying and moving files and directories, invoking editors, compressing and uncompressing files, creating and expanding archives, compiling programs, sending mail, etc. It looks nice, has colors (if the standard ANSI color sequences are supported) and is user-friendly.

One of the main advantages of gnuit is its flexibility. It is not limited to a given set of commands. The configuration file can be easily enhanced, allowing the user to add new commands or file operations, depending on its needs or preferences.

----- cut here -----

**Comment by its-pointless** [comment]
#1062 
if you want to use it now you can use my repo instructions in gcc_termux

**Comment by rlfrazier** [comment]
Thanks.  

Gnuit still does what it did in 2009.  I have been using TeX/LaTeX for much longer, and TeX was finished (except for bugs) in about 1990 (my dissertation from 1991 formats today exactly as it did then).  That work isn't being done on some software can be a good sign, i.e., it is fit for purpose.  

Best wishes,
Bob

**Comment by fornwall** [comment]
Thanks to @its-pointless the package is now available for installation!
