### ISSUE TITLE
Backspace does not work in SSH session

### ISSUE THREAD

**Issue by weilbaum** [termux/termux-packages#1061]
When I'm pressing the backspace key of my keyboard while connected to termux via openssh, instead of deleting text left of the cursor, it adds spaces. The left arrow key is not working also. 

`stty -a` gives me the following output:
```
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0I'm running termux on Android 7.1.1. 
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```
Ctrl+V Backspace also results in `^?`. `stty erase ^?` didn't help.

I'm running termux on Android 7.1.1, OpenSSH_7.5p1.

**Comment by fornwall** [comment]
Which terminal emulator do you use when connecting to Termux over openssh?

**Comment by weilbaum** [comment]
I'm using termite. I do not have any issues with other SSH connections.

**Comment by fornwall** [comment]
What is your TERM environment variable when running under termite (as shown when running `echo $TERM`)?

Also, when ssh:ed into Termux using termite, could you:

1. Run `apt install vtutils` 
2. Run `vtshowkeys`.
3. Press backspace on your keyboard.

and write the output here?

**Comment by weilbaum** [comment]
```
$ echo $TERM
xterm-termite
$ ssh <phone-ip> -p 8022
-bash-4.4$ vtshowkeys
0177 127 0x7F Delete			^?
```
I hope that's sufficient.

**Comment by xeffyr** [comment]
Added fix in https://github.com/termux/termux-packages/commit/9568028c655ed4e13a67274ea80ac4de2886437a.
