### ISSUE TITLE
[Bug]: $ curl -s https://sever.99phanmem.com/khatool CANNOT LINK EXECUTABLE "curl": library "libssl.so.1.1" not found Aborted

### ISSUE THREAD

**Issue by lam123abclam** [termux/termux-packages#10622]
### Problem description

![Screenshot_20220511-174215](https://user-images.githubusercontent.com/100073875/167831496-2a0aec2b-d91d-4969-a4f5-552459da972b.png)

### What steps will reproduce the bug?

Help me

### System information

termux-info:

```

```
CANNOT LINK EXECUTABLE "curl": library "libssl.so.1.1" not found
Aborte

**Comment by thunder-coding** [comment]
Do not open duplicate tickets. #10621
