### ISSUE TITLE
[Package]: Awesome shell packages

### ISSUE THREAD

**Issue by bidyut-741** [termux/termux-packages#10623]
Feature Request: awesome shell packages.

Please add:-

• Shell = elvish, es, ion, ksh93, ngs, oksh, osh, tcsh, xonsh, yash, zsh
• CLP = bashhub, cod, ddgr, fz, how2, has, pdd, q, qfc, tldr, xiki, xplr
• Directory = bd, up
• Developers = bcal, cloc 
• System = atop, bashtop, btop, ls++, lsp, duc, gt5, gdu, dua
• Downloading and Serving = balls
• Apps = ansiweather, ansi, dstask, pcalc, pockyt, wego, wttr.in
• Games = bash2048, sedtris
• Shell Script = ansi, dispatch, esh, revolver, ts, urchin

**Comment by wmcbtech30** [comment]
Unacceptable in terms of packaging policies, packages such as xonsh can be installed in pip. and others can be manually installed easily.

**Comment by Grimler91** [comment]
And others are already packaged
