### ISSUE TITLE
keyboard does not open when using editors, such as vim, emacs

### ISSUE THREAD

**Issue by jhegedus42** [termux/termux-packages#1063]
how to reproduce the bug:

1) open termux
2) enter `vim` at prompt
3) press `i`
4) write "hello"
5) hide the keyboard
6) tap the editor
7) the keyboard does not come up

This is strange because the keyboard comes up if I am at the command prompt.

So what's the difference between an editor and the command prompt?

Sliding from the left 500 times a day to bring up the keyboard starts to be slowly a little tiresome. :(

Any suggestions ? How to solve this issue?

Is there a workaround? 

Maybe I can trigger some event from emacs to bring up the keyboard? Maybe execute a script and bind it to "/" ?  (The special key "/" is still visible on the auxilary keyboard, even if I close the main keyboard.)

**Comment by Harshiv-Patel** [comment]
yes, there should be some gesture like double click that can shiw/hide the keyboard.

**Comment by jhegedus42** [comment]
but what i dont understand is why it does not work for vim/emacs and does work for command line ?

if I could figure out this then i could find a workaround ...

**Comment by jhegedus42** [comment]
btw, I just noticed that it does not work in tmux either... 

I guess it does not work anywhere else than at the main prompt ... 

any idea why is that ? it is really strange... how can it work at bash prompt and not work anywhere else? is this some terminal setting issue ? maybe some event does not get forwarded? maybe some mouse event?

is it possible to run some script from command line that will open the keyboard? then i could run that script from emacs when there is a mouse event (a tap)

**Comment by Harshiv-Patel** [comment]
It seems to be a mouse event issue, as vim randomly goes into Visual mode from command mode upon screen touchEvents.

**Comment by jhegedus42** [comment]
yeah, same happens with emacs, but with emacs evil - insert mode, the mouse works perfectly... really strange

**Comment by Harshiv-Patel** [comment]
> The current workaround is to pull out the menu from the left and press the Keyboard button to make the keyboard show.

How about a settings-option that would map one of the hw volume +/- keys to show or hide keyboard upon press. Slightly faster then pull-out menu. Just as an options though.

**Comment by Neo-Oli** [comment]
> This may be fixed in the future, perhaps by always requesting the keyboard to be shown on touch events, even when mouse events are sent to a terminal program. Note that this would prevent one from using mouse-aware programs with the keyboard hidden - but I don't know how important or useful use case that is?

Please don't. I can think of multiple scenarios where this would be incredibly annoying. 
- Reading weechat and switching buffers by tapping on buffer line
- Reading documents in neovim and switching buffers by tapping tabline
- Using w3m in mouse mode
- Switching panes or windows in tmux
Please make this at least an option.


> Maybe I can trigger some event from emacs to bring up the keyboard? Maybe execute a script and bind it to "/" ? (The special key "/" is still visible on the auxilary keyboard, even if I close the main keyboard.)

Perhaps if we implement https://github.com/termux/termux-api/issues/27, this could work.

**Comment by codebam** [comment]
In vim disable mouse mode in the default config

**Comment by alex-rug** [comment]
I'm experiencing the same problem in tmux as well? Any ideas?
