### ISSUE TITLE
Cordova Requirements

### ISSUE THREAD

**Issue by apolbox** [termux/termux-packages#1064]
I'm from indonesia,

So please translate my language hehehe

Saya menginstall cordova projek dan saya mengalami beberapa masalah,

Dan saat saya ketikan perinta "cordova requirements" saya menemukan error sebagai berikut :

cordova requirements

Requirements check results for android:
Java JDK: not installed                         Failed to run "javac -version", make sure that you have a JDK installed.                        You can get it from: http://www.oracle.com/technetwork/java/javase/downloads.

Android SDK: not installed
Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
Android target: not installed
android: Command failed with exit code ENOENT
Gradle: not installed
Could not find gradle wrapper within Android SDK. Could not find Android SDK directory.
Might need to install Android SDK or set up 'ANDROID_HOME' env variable.
                                                Requirements check results for ios:             Apple OS X: not installed
Cordova tooling for iOS requires Apple OS X
Error: Some of requirements check failed

**Comment by fornwall** [comment]
Hello!

A `javac` program is not yet available in Termux, track https://github.com/termux/termux-packages/issues/324 for that!

Note that even with javac available, we are probably rather far from being able to use Cordova on-device, as it requires the full Android SDK which is a rather complex beast. Have a look at https://sdrausty.github.io/buildAPKs/easilyBuildAndroidAPKsonDevice for an alternative, lightweight way of building android apps on-device in the meantime!

**Comment by sdrausty** [comment]
@apolbox     Java, javac and jar available through:
# [TermuxArch](https://github.com/sdrausty/TermuxArch)

Now you can install Arch Linux in Termux 📲 on your smartphone and tablet. More information at https://sdrausty.github.io/TermuxArch

Java is available through https://sdrausty.github.io/TermuxArch/ Just follow the easy install instructions at https://sdrausty.github.io/TermuxArch/docs/docs/install or simply copy and paste the following into your Termux window:

```
cd && git clone https://github.com/sdrausty/TermuxArch
./TermuxArch/setupTermuxArch.sh
```
Read more about the Arch Linux package manager at [duckduckgo arch+linux+install+java+pacman.](https://duckduckgo.com/?q=arch+linux+install+java+pacman&atb=v90-2__&t=cros&ia=qa)

To install java run `pacman -Syy; pacman -Su; pacman -S jdk8-openjdk`


![screenshot_20171109-220204](https://user-images.githubusercontent.com/27742457/32641053-cedfdcfe-c599-11e7-9c73-b185e70e9c6a.png)
![screenshot_20171109-222326](https://user-images.githubusercontent.com/27742457/32641590-d5541d4a-c59c-11e7-8855-e151bc217acc.png)
