### ISSUE TITLE
[Bug]: Pulseeffects doesn't work

### ISSUE THREAD

**Issue by mjuned47** [termux/termux-packages#10643]
### Problem description

Running pulse effects automatically closes when start music/video file in vlc
![Screenshot_2022-05-13-16-05-33-395_com termux](https://user-images.githubusercontent.com/68558066/168305265-649243b0-b1ba-4745-b13c-9d208e2abbc7.jpg)

### What steps will reproduce the bug?

Install x11 vlc player 
Install pulse effects
Install tightvncserver
Start vncserver
Start vlc player with following code(according to display number, here its 1) :
DISPLAY=:1 qvlc
Same way start Pulseeffects
Open any vnc viewer
Open any mp3 file in vlc player

### What is the expected behavior?

Pulseeffects should work normally but it is closing automatically

### System information

Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=681
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
curl/stable 7.83.1 aarch64 [upgradable from: 7.83.0-1]
git/stable 2.36.1 aarch64 [upgradable from: 2.36.0]
gtkmm3/x11 3.24.6 aarch64 [upgradable from: 3.24.5]
libass/stable 0.16.0 aarch64 [upgradable from: 0.15.2-4]
libcurl/stable 7.83.1 aarch64 [upgradable from: 7.83.0-1]
libglibmm-2.4/stable 2.66.4 aarch64 [upgradable from: 2.66.2]
libsqlite/stable 3.38.5 aarch64 [upgradable from: 3.38.3]
mesa/x11 22.0.3 aarch64 [upgradable from: 21.3.7-5]
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g040a88f #1 SMP PREEMPT Thu Nov 7 00:28:25 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 4

**Comment by xtkoba** [comment]
```
Thread 1 "pulseeffects" received signal SIGABRT, Aborted.
0x000000200081f658 in abort () from target:/system/lib64/libc.so
(gdb) bt
#0  0x000000200081f658 in abort () from target:/system/lib64/libc.so
#1  0x000000200087ad30 in __stack_chk_fail () from target:/system/lib64/libc.so
#2  0x0000005555826fdc in (anonymous namespace)::on_message_latency (gst_bus=<optimized out>, message=<optimized out>, pb=0x2003da3900) at ../easyeffects-4.8.6/src/pipeline_base.cpp:139
#3  0x000000200093abd8 in g_cclosure_marshal_VOID__BOXEDv () from target:/data/data/com.termux/files/usr/lib/libgobject-2.0.so
#4  0x0000002000937e0c in ?? () from target:/data/data/com.termux/files/usr/lib/libgobject-2.0.so
#5  0x000000200094a894 in g_signal_emit_valist () from target:/data/data/com.termux/files/usr/lib/libgobject-2.0.so
#6  0x000000200094b030 in g_signal_emit () from target:/data/data/com.termux/files/usr/lib/libgobject-2.0.so
#7  0x00000020015b2b78 in gst_bus_async_signal_func () from target:/data/data/com.termux/files/usr/lib/libgstreamer-1.0.so
#8  0x00000020015b3208 in ?? () from target:/data/data/com.termux/files/usr/lib/libgstreamer-1.0.so
#9  0x0000002001c69280 in g_main_context_dispatch () from target:/data/data/com.termux/files/usr/lib/libglib-2.0.so
#10 0x0000002001c69548 in ?? () from target:/data/data/com.termux/files/usr/lib/libglib-2.0.so
#11 0x0000002001c695c0 in g_main_context_iteration () from target:/data/data/com.termux/files/usr/lib/libglib-2.0.so
#12 0x0000002001a0345c in g_application_run () from target:/data/data/com.termux/files/usr/lib/libgio-2.0.so
#13 0x00000055557c2df8 in main (argc=1, argv=0x7ffffffa48) at ../easyeffects-4.8.6/src/pulseeffects.cpp:57
(gdb)
```
