### ISSUE TITLE
Error in new version of termux from f-droid 

### ISSUE THREAD

**Issue by Siddharth0kumar** [termux/termux-packages#10645]
`E: Failed to fetch https://dl.kcubeterm.me/termux-packages-24/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://dl.kcubeterm.me/termux-packages-24 stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.`

Please solve it please

**Comment by xtkoba** [comment]
Superseded by #10647.
