### ISSUE TITLE
Error in new version of termux with pkg update and other commands 

### ISSUE THREAD

**Issue by Siddharth0kumar** [termux/termux-packages#10647]
`E: Failed to fetch https://dl.kcubeterm.me/termux-packages-24/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://dl.kcubeterm.me/termux-packages-24 stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.`

Please termux community solve it.......

**Comment by agnostic-apollo** [comment]
Use `termux-change-repo` to switch to a different mirror for all your repos. The dl.kcubeterm.me domain has not been renewed and only @kcubeterm can/should fix it.

We can remove it from approved list of mirrors for now in `termux-tools`. Can anybody else do it, I am away from laptop keyboard.

**Comment by kcubeterm** [comment]
@agnostic-apollo look like latest termux(bootstrap) version don't packed with latest termux-tools.

**Comment by agnostic-apollo** [comment]
The F-Droid release was made in jan 2022 before your feb url change.

**Comment by kcubeterm** [comment]
then let's do another release man. otherwise fdroid and playstore version will give same feel :)

**Comment by agnostic-apollo** [comment]
Been thinking on doing that now. Bootstrap scripts need to be updated and termux domain changed, some other fixes. That needs some work. Maybe end of next week.

**Comment by 2096779623** [comment]
> Been thinking on doing that now. Bootstrap scripts need to be updated and termux domain changed, some other fixes. That needs some work. Maybe end of next week.

Fixed?
