### ISSUE TITLE
invalid symbolic link in texlive-bin

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-packages#10642]
in `$PREFIX/bin/texlive`, there are many invalid symlink, like tlmgr. Why not
remove them?

**Comment by Grimler91** [comment]
If you install scheme-full through texlive-installer they will point to the correct script. The good thing with having these broken symlinks is that [command-not-found picks them up](https://github.com/termux/command-not-found/blob/master/termux-packages/commands-arm-07a6725.h#L5975), which would not be the case if symlinks are setup in texlive-installer installation script

**Comment by Freed-Wu** [comment]
I see. So it is not a bug, just a compatible setting. Thanks for your answer.
