### ISSUE TITLE
fontforge[Package]: 

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#10650]
### Package description

Fontforge is a font editor. It can create and edit a wide variety of font files.

### Source code URL

github.com/fontforge

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Yes, it compiles on my Samsung WiFi tablet (no phone) unrooted, 32-bit arm, xfce4 desktop, on Android 11. It was necessary to remove references to getpwent() from the source code. Apparently that resource is not in Termux clang or gtk.

Three executables: fontlint, fontimage, and fontforge. The first two are CLI and work as expected. But fontforge is GUI and fails xfce4. Nothing appears in the GUI. If launched from command line, "Bus Error". No further informjation. Using valgrind did not provide anything obvious.

The fontforge GUI does work in 'proot-distro archlinux' with xfce4, on the same machine. Direct from package distribution, or compiled. Both work.

**Comment by xtkoba** [comment]
This is a bit off-topic but "Bus error" on arm is typically caused by unaligned memory accesses. The following code will trigger a bus error when compiled for arm with some optimizations (e.g. `-O1`):

```c
#include <stdlib.h>
#include <stdint.h>

__attribute__((__noinline__))
void foo(uint64_t *n, size_t len)
{
  size_t i;
  for (i = 0; i < len; i++)
    n[i] = 1;
}

int main(void)
{
  char *a = malloc(sizeof(uint64_t) + 1);
  if (!a) abort();
  foo((uint64_t *)(a + 1), 1);

  return 0;
}
```

I would use `gdb` to debug this:

```
Program received signal SIGBUS, Bus error.
foo (n=<optimized out>, len=<optimized out>) at align.c:9
10          n[i] = 1;
(gdb) disassemble
Dump of assembler code for function foo:
   0xaaaab444 <+0>:     cmp   r1, #0
   0xaaaab448 <+4>:     bxeq  lr
   0xaaaab44c <+8>:     mov   r3, #0
   0xaaaab450 <+12>:    mov   r2, #1
=> 0xaaaab454 <+16>:    strd  r2, [r0]
   0xaaaab458 <+20>:    add   r0, r0, #8
   0xaaaab45c <+24>:    subs  r1, r1, #1
   0xaaaab460 <+28>:    bne   0xaaaab454 <foo+16>
   0xaaaab464 <+32>:    bx    lr
End of assembler dump.
(gdb) info reg
r0             0xf7497db1          4148788657
r1             0x1                 1
r2             0x1                 1
[...]
```

Usually we can devise some workaround for this type of errors, but some packages (e.g. `bochs`) exclude arm build due to this unresolved.

**Comment by rallg** [comment]
I can make the "Bus error" go away, by launching xfce4 via a different method. But still serious problems. More info:

1. Fontforge requires libm.so (math lib) even with clang and llvm. I do not know why. When I create a symlink in $PREFIX/lib leading to the libm.so in Android /system/lib, then build succeeds. Note that /system/lib/libm.so is itself a symlink to somethin in /apex. I do not think that this is the cause of the problem, since one of the working CLI programs uses libm.so, via libfontforge.so.

2. If installed to $PREFIX/local. then it is necessary to use env or alias to LD_LIBRARY_PATH there. This is not necessary if installed to $PREFIX.

3. With valgrind, I do see numerous problems relating to memory alignment. The blame is usually placed at "Can't make sense of .ARM.exidx section mapping". Also problems relating to uninitialized variable in $PREFIX/lib/libgobject-2.0.so.

4. Possibly related: On my xfce4 installation, both xfce4-terminal and qterminal crash, also crashing xfce4 and the Xserver. As wiith fontforge, problems are not observed when I use xfce4 via proot-distro archlinux, on the same machine.

5. Again, the non-GUI fontforge executables work. So the problem must have something to do with interaction between the GUI executable, and the Xserver or xfce4.
