### ISSUE TITLE
How to deal with programs that require either gnupg or gnupg2?

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#1066]
`pass` requires either `gnupg` or `gnupg2`. It works with both. I happen to use it with `gnupg2` and would like to uninstall `gnupg`, but `pass` lists it as a requirement. Is there perhaps some mechanism in apt that would allow me to skip the `gnupg` requirement if `gnupg2` is already installed?
Or should we remove the `gnupg*` requirement entirely? `pass` doesn't need it to build the package and it will fail somewhat gracefully if neither is available: 
`/data/data/com.termux/files/usr/bin/pass: line 365: gpg: command not found`

**Comment by fornwall** [comment]
I think we should aim to remove `gnupg` version 1 and only keep `gnupg2` (and let the `gnupg` program be provided by `gnupg2`). Latest ubuntu already does this.

So, a first step towards dropping `gnupg` 1 is to transition the packages depending on it to instead depend on `gnupg2`:

1. pass
2. texlive
3. apt (through gpgv)

So a pull request to update `pass` to depend on `gnupg2` is welcome!

**Comment by Neo-Oli** [comment]
I opened a pull request for that now. Could we not create an empty package named `gnupg` that simply depends on gnupg2? Then people could still call `apt install gnupg`. This would also mean we wouldn't need to change any dependencies.
