### ISSUE TITLE
[Bug]: curses can send utf-8 characters to a xterm that is not in utf-8 mode.

### ISSUE THREAD

**Issue by billblake2018** [termux/termux-packages#10676]
### Problem description

Curses sends the obvious utf-8 character for ACS_LARROW (and at least ACS_RARROW) when TERM=xterm.  This is fine if one's xterm is in utf-8 mode.  But at least my xterm (on FreeBSD; I'm using ssh to get into termux) is not in utf-8 mode by default, and in any case curses shouldn't be assuming the mode of the xterm.  (To make matters more annoying, the left arrow character in my xterm is unreadable.  But that's hardly curses' fault.) I solved my problem by just not using the problematic ACS_ characters in my curses application, but this could be an annoyance for others.

### What steps will reproduce the bug?

Connect into termux via ssh, with one's terminal an X window xterm not in utf-8 mode.  Write a program using curses to send an ACS_LARROW to the screen and run it under termux.  Instead of getting a left arrow, you'll get an 'a' with a circumflex (from the first character of the three bytes of the utf-8 that should display a left arrow).  Other oddball things may happen from the other two characters.

### What is the expected behavior?

The expected behavior is to show something more or less like a left arrow.  On my system, curses shows '<', since that will display properly no matter what mode the xterm is in.  But curses should not use utf-8 characters for the ACS characters (or anywhere else), since it is not (as far as I know) possible to determine whether the xterm is in utf-8 mode.

### System information

termux-info:

```
Termux Variables:
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
Updatable packages:
clang/stable 14.0.3-1 arm [upgradable from: 14.0.1]
curl/stable 7.83.1 arm [upgradable from: 7.83.0]
dpkg/stable 1.21.7 arm [upgradable from: 1.21.1-1]
gpgv/stable 2.3.6 arm [upgradable from: 2.3.5]
libcompiler-rt/stable 14.0.3-1 arm [upgradable from: 14.0.1]
libcurl/stable 7.83.1 arm [upgradable from: 7.83.0]
libgnutls/stable 3.7.5 arm [upgradable from: 3.7.3]
libllvm/stable 14.0.3-1 arm [upgradable from: 14.0.1]
libxml2/stable 2.9.14 arm [upgradable from: 2.9.13]
lld/stable 14.0.3-1 arm [upgradable from: 14.0.1]
llvm/stable 14.0.3-1 arm [upgradable from: 14.0.1]
lsof/stable 4.95.0-1 arm [upgradable from: 4.95.0]
nano/stable 6.3 arm [upgradable from: 6.2]
openssl-1.1/stable 1.1.1o arm [upgradable from: 1.1.1n]
openssl/stable 3.0.3 arm [upgradable from: 3.0.2]
termux-keyring/stable 3.4 all [upgradable from: 3.3]
termux-tools/stable 0.176 all [upgradable from: 0.175]
texinfo/stable 6.8-1 arm [upgradable from: 6.8]
Android version:
11
Kernel build information:
Linux localhost 4.19.127+ #1 SMP PREEMPT Mon Mar 7 03:14:35 CST 2022 armv7l Android
Device manufacturer:
motorola
Device model:
moto g pure

```

**Comment by xtkoba** [comment]
I suppose this is because `nl_langinfo(CODESET)` always returns `"UTF-8"`:

https://github.com/termux/termux-packages/blob/7c06b80bdbf2b472f35073feddfcb31639c9e97f/ndk-patches/langinfo.h#L146

See also the implementation of `_nc_unicode_locale()` in `ncurses/tinfo/lib_setup.c` from ncurses tarball.

Configuring with `am_cv_langinfo_codeset=no` may solve the issue. I have submitted a PR for this (#10681), but I cannot evaluate the drawbacks. So everyone please test. Thanks!
