### ISSUE TITLE
network_interface gem compile error

### ISSUE THREAD

**Issue by swg0101** [termux/termux-packages#1067]
When installing the network_interface gem using the command:
gem install network_interface -v '0.0.1'

I am getting the following error - is this related to ifaddrs.h? I already have the latest ndk-sysroot package installed:
ndk-sysroot/stable,now 14-1 arm [installed]

Any ideas?

---

current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/network_interface-0.0.1/ext/network_interface_ext
make "DESTDIR="
compiling netifaces.c
In file included from netifaces.c:2:
./netifaces.h:75:26: error: invalid application of 'sizeof' to an incomplete type 'struct sockaddr_in'
    case AF_INET: return sizeof (struct sockaddr_in);
                         ^      ~~~~~~~~~~~~~~~~~~~~
./netifaces.h:75:41: note: forward declaration of 'struct sockaddr_in'
    case AF_INET: return sizeof (struct sockaddr_in);
                                        ^
./netifaces.h:77:27: error: invalid application of 'sizeof' to an incomplete type 'struct sockaddr_in6'
    case AF_INET6: return sizeof (struct sockaddr_in6);
                          ^      ~~~~~~~~~~~~~~~~~~~~~
./netifaces.h:77:42: note: forward declaration of 'struct sockaddr_in6'
    case AF_INET6: return sizeof (struct sockaddr_in6);
                                         ^
2 errors generated.
make: *** [Makefile:243: netifaces.o] Error 1

make failed, exit code 2

**Comment by timwr** [comment]
I'm so confused. I was able to install network_interface with this patch: https://github.com/tux-mind/network_interface/tree/patch-1 the first time.
After a trying a clean install I'm running into the error above. Any ideas?

**Comment by timwr** [comment]
It seems to work after this workaround:
https://github.com/timwr/network_interface/commit/b27310f274c239d13ba65b339278cff39171cb20
Required for https://github.com/termux/termux-packages/issues/715

**Comment by Systemad** [comment]
Have anyone solved this?

My netifaces.h seems to be empty

**Comment by ahad-47** [comment]
error occurred while installing
network_interface (0.0.1), and Bundler cannot continue.
Make sure that `gem install network_interface -v
'0.0.1'` succeeds before bundling.

**Comment by ahad-47** [comment]
Tried installing patch and everything that was suggested

**Comment by xeffyr** [comment]
Closing since issue has no relation to official packages.
For those who tries to install Metasploit and can't deal with dependencies: https://wiki.termux.com/wiki/Metasploit_Framework.
