### ISSUE TITLE
texlive install fails because of year mismatch in paths

### ISSUE THREAD

**Issue by ysalmon** [termux/termux-packages#1068]
Hello,
I have been trying to reinstall TeXLive recently. While this had worked partially in the past, I now encounter an error during the postinstall script.

Namely, errors with ```sed``` complaining about non-existing paths (eg. ```/data/data/com.termux/files/usr/opt/texlive/2016/tlpkg``` and so on).  I suspect this is related to the fact that the termux texlive package now installs texlive 2017 (as shown earlier in the log).

**Comment by Grimler91** [comment]
Thanks for reporting.

As a quick fix, before a fix has been commited, replace the URL in termux-install-tl with `ftp://ftp.tug.org/texlive/historic/2016/install-tl-unx.tar.gz` and then run termux-install-tl again.

**Comment by Grimler91** [comment]
My previous post didn't help unfortunately. We'll need to switch to texlive 2017 instead if we want to use the tlnet installer. I'll open a pull request shortly.
