### ISSUE TITLE
[Bug]: github active: compilation error in update "termux-services: Rebuild..."

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#10690]
### Problem description

https://github.com/termux-pacman/termux-packages/actions/runs/2328874380

### What steps will reproduce the bug?

Auto-add [commit](https://github.com/termux/termux-packages/commit/ded24b528567311f7ad1bac4433b0141c1db3d61)

### System information

This is github actives

**Comment by Grimler91** [comment]
Should have been fixed in https://github.com/termux/termux-packages/commit/abc972d5b3fd6294030991cf2f4037e3f81985a4

**Comment by xtkoba** [comment]
Yeah, this was pretty much expected and so I qualified the commit as `%ci:no-build` and manually triggered the build of each package one by one. Any problems?
