### ISSUE TITLE
[Package]: GNOME Web (epiphany)

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#10706]
### Package description

Web is the web browser for the GNOME desktop and for elementary OS, based on the popular WebKit engine.

### Home page URL

https://wiki.gnome.org/Apps/Web

### Source code URL

https://download.gnome.org/sources/epiphany/42/epiphany-42.2.tar.xz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

As `webkit2gtk` is now available at termux packages, GNOME Web maybe able to be another good alternative of `surf` as it gives user friendly interface.

**Comment by rallg** [comment]
If all you need is a browser other than surf, the recently-added 'otter-browser' looks good.

**Comment by JKGrandmaster** [comment]
GNOME Web epiphany

PKG install epiphany
