### ISSUE TITLE
[Bug]: openjdk-17: libsplashscreen reports libgif.so.7 not found

### ISSUE THREAD

**Issue by tempaccforissue** [termux/termux-packages#10705]
### Problem description

I've downloaded the Netbeans IDE (zip archive) from their official site, unzipped it into `~/netbeans`, then tried to launch it from VNC Viewer app with the command: `~/netbeans/bin/netbeans`, and it crushes saying:
```./netbeans
java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/opt/openjdk/lib/libsplashscreen.so: dlopen failed: library "libgif.so.7" not found
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:311)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:281)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:814)
	at java.base/java.lang.System.loadLibrary(System.java:1948)
	at java.desktop/java.awt.SplashScreen$1.run(SplashScreen.java:135)
	at java.desktop/java.awt.SplashScreen$1.run(SplashScreen.java:133)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.SplashScreen.getSplashScreen(SplashScreen.java:132)
	at org.netbeans.core.startup.Splash.<init>(Splash.java:122)
	at org.netbeans.core.startup.Splash.getInstance(Splash.java:60)
	at org.netbeans.core.startup.Main.start(Main.java:271)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### What steps will reproduce the bug?

.

### What is the expected behavior?

Netbeans should start properly.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=30258
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture: arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24 stable main
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 main
Updatable packages:
ncurses-ui-libs/stable 6.3-1 arm [upgradable from: 6.3]
ncurses/stable 6.3-1 arm [upgradable from: 6.3]
termux-tools/stable,stable 0.178 all [upgradable from: 0.177]
Android version:
10
Kernel build information:
Linux localhost 4.9.193-perf-g743cb02
#1 SMP PREEMPT Mon Oct 25 17:15:39 CST 2021 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 8A
```

**Comment by xtkoba** [comment]
```
$ readelf -Wa opt/openjdk/lib/libsplashscreen.so |grep RUNPATH
  0x000000000000001d (RUNPATH)      Library runpath: [/data/data/com.example.ruby/usr/opt/openjdk/lib:$ORIGIN]
```

Proposed workaround:

```bash
ln -sf $PREFIX/lib/libgif.so.7 $PREFIX/opt/openjdk/lib/
```

Also `libjpeg.so` and `libpng16.so` may need the same care.

**Comment by tempaccforissue** [comment]
> Proposed workaround:
> 
> ```shell
> ln -sf $PREFIX/lib/libgif.so.7 $PREFIX/opt/openjdk/lib/
> ```

Worked like a charm!

![Screenshot_2022-05-17_17-32-24](https://user-images.githubusercontent.com/102426645/168801986-44d9ff6f-6080-4444-a67c-bcfee2922959.png)

![Screenshot_2022-05-17_17-33-45](https://user-images.githubusercontent.com/102426645/168802010-51160e3e-1b5a-4f02-84d6-9b0ed3bd6d13.png)

**Comment by Grimler91** [comment]
Or modify [flags-cflags.m4](https://github.com/termux/openjdk-mobile-termux/blob/master/make/autoconf/flags-cflags.m4#L57) to add our libdir to runpath (seems more future-proof than symlinking libraries). I'm running a test build to see if that seems doable.

Could probably also replace the "$ORIGIN" entry in the runpath, I guess that is not used(?)

**Comment by tempaccforissue** [comment]
Can you add netbeans as a package? 🙃

**Comment by tempaccforissue** [comment]
> @tempaccforissue if someone figures out how to cross-compile it for termux, and it fulfills the [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy), sure

I wonder why it needs to be built for Termux when it works out of the box just by downloading the official distribution, unzipping and hitting run? (although it crashed for the libplashscreen which it is not responsible for)

**Comment by Grimler91** [comment]
The vast majority of our packages are built from source. This makes the build and packaging process transparent, and some potential issues might be caught during compilation.

Having a public build recipe also makes it easier for users to make modifications and/or fixes to the package (it's easy to modify and build a package).

**Comment by tempaccforissue** [comment]
> The vast majority of our packages are built from source. This makes the build and packaging process transparent, and some potential issues might be caught during compilation.

Building it on a mobile device will be nightmare because the source code is huge! And I don't have a PC, nor I know better about CI/CD or docker. May someone comes to help.
