### ISSUE TITLE
pip upgrade packages failed

### ISSUE THREAD

**Issue by mengyyy** [termux/termux-packages#1071]
Today i want to update python-telegram-bot from 5.3.1 to 6.0.1 but it failed.
Then i want to use source code to install, but git failed.
At last i download the source code to install success, but i use `pip freeze` , the version of python-telegram-bot is still 5.3.1.
I uninstall 5.3.1  and install from souce code success. 
The same pip update problem arise when i update requests.

**Comment by Neo-Oli** [comment]
Please run `packages upgrade`. There was a problem with git being broken, but it should be resolved now.
