### ISSUE TITLE
[Bug]: python_crossenv setuptools version issue: bdist_wininst not found

### ISSUE THREAD

**Issue by xloem** [termux/termux-packages#10715]
### Problem description

Every now and then I try to make progress on #2724 and most recently I'm stuck on this unexpected [python crossenv issue](https://github.com/benfogle/crossenv/issues/98): `ModuleNotFoundError: No module named 'distutils.command.bdist_wininst'`

Does anybody have advice on this? The crossenv developer said it did not reproduce for them. There's scant documentation on termux python crossenv. Bisection of the issue can be very slow due to how long it takes to run a build.

### What steps will reproduce the bug?

```
git clone https://github.com/xloem/termux-packages
cd termux-packages
git checkout e0c2525f77daf6cb5ea2f5c194ef94c9bf5ef4f2
scripts/run-docker.sh ./build-package.sh libtorch
```

### What is the expected behavior?

There shouldn't be indication of old versions of python distutils. Use of distutils in cross builds should not trigger a crash.

### System information

termux-packages 9eb2d6d13e1ba13f55104d95cd20956ffbebabab
termux/package-builder 8ddfa11507b2

**Comment by Grimler91** [comment]
Something to test would be to rebase your branch, and build with `-i`, as in `scripts/run-docker.sh ./build-package.sh -i libtorch`, in case building dependencies make a difference (we tend to not do builds without `-i/-I` since it takes longer time)

**Comment by xtkoba** [comment]
This also affected `matplotlib` and `python-apt`. I workaround this by applying the following patch:

https://github.com/termux/termux-packages/blob/07ab08fb59bd82ad5047e292eada10bfa5106fea/packages/matplotlib/setuptools-44.1.1-no-bdist_wininst.diff

in the following way:

https://github.com/termux/termux-packages/blob/07ab08fb59bd82ad5047e292eada10bfa5106fea/packages/matplotlib/build.sh#L54-L56

**Comment by xloem** [comment]
is this a bug in termux, python_crossenv, or not a bug?

**Comment by Grimler91** [comment]
Yeah, looks like it should have been fixed in commit https://github.com/pypa/setuptools/commit/60da370778026872e44d44c3a0429bfc2b242504

**Comment by xloem** [comment]
it sounds like it could be fixed by a build step that updates setuptools or adds a local setuptools to python's sys path

**Comment by Grimler91** [comment]
Will probably work out of the box when we update the ubuntu version in the docker image to 22.04

**Comment by xtkoba** [comment]
This is no longer an issue given that we use Ubuntu 22.04 Docker image. Thanks.

**Comment by xloem** [comment]
Thanks for updating this.

I don’t oresently have the torch recipe on my radar any more, but it could return some day.
