### ISSUE TITLE
MISSING PACKAGE: tor for aarch64

### ISSUE THREAD

**Issue by ladar** [termux/termux-packages#10733]
### Problem description

For some reason there doesn't appear to be a tor package for 64-bit arm devices anymore. The 32-bit arm, x86 and x86_64 packages are all available for with 0.4.6.10.

### What steps will reproduce the bug?

# On aarch64 device.
```
~ $ apt install tor
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package tor is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'tor' has no installation candidate
~ $ apt install torsocks
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 torsocks : Depends: tor but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### What is the expected behavior?

The package should install.

### System information

```
~ $ termux-info
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=3641
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 5.10.66-android12-9-ab22305000 #1 SMP PREEMPT Tue May 3 08:33:01 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 6
```

**Comment by ladar** [comment]
To see the missing package:

**Comment by ladar** [comment]
Any idea why the package would be here, but not in the master repo linked above:

https://grimler.se/termux-packages-24/pool/main/t/tor/

**Comment by xtkoba** [comment]
Now rebuild triggered. Thanks!

https://github.com/termux/termux-packages/actions/runs/2351713696

**Comment by ladar** [comment]
And here:

https://grimler.se/termux/termux-main/pool/main/t/tor/

**Comment by ladar** [comment]
This repo shows the -2 build, but the aarch64 version is missing for -3.

https://termux.librehat.com/apt/termux-main/pool/main/t/tor/

**Comment by xtkoba** [comment]
Seems like revbump needed (just triggering without revbump fails to upload).

Retry: https://github.com/termux/termux-packages/actions/runs/2351769490

**Comment by xtkoba** [comment]
(Actually rebuild without revbump seems to work. Probably just a matter of some lags.)

Now DEBs should be populated in packages.termux.org. Thanks.
