### ISSUE TITLE
[Bug]: ls: cannot open directory '.': Permission denied

### ISSUE THREAD

**Issue by Mdsarowarhossain** [termux/termux-packages#10732]
### Problem description

When I am trying to open android data folder in  I am seeing this error.  ls: cannot open directory '.': Permission denied. 
I am already give termux-setup-storage  allow. My Android version is 11

### What steps will reproduce the bug?

Allowed term termux application to use all kind of directory

### What is the expected behavior?

I want to access Android data folder by tarmax

### System information

termux-info:

```

```download from fdroid

**Comment by Grimler91** [comment]
Dont know what directory you are trying to access, but termux cannot access "all" directories (without root)

**Comment by Mdsarowarhossain** [comment]
> Dont know what directory you are trying to access, but termux cannot access "all" directories (without root)

I want to access android/data/spck.io/file/project
This directory is valid


com.spck.io is a package name of an application which is am installed.  My android version is 11

**Comment by Igo-XD** [comment]
Saya ingin mengakses Android/data/spck.io/file/project
Direktori ini valid

spck.io adalah nama paket dari aplikasi yang diinstal. Versi android saya adalah 11

**Comment by Igo-XD** [comment]
.../Android/data $ ls
ls: cannot open directory '.': Permission denied

Help me please!!!

**Comment by Igo-XD** [comment]
.../Android/data $ ls
ls: cannot open directory '.': Permission denied

Help me please!!!
