### ISSUE TITLE
ssh/rsync to Android 5 (Nexus 10) doesn't work over USB anymore

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#1073]
I normally rsync my files to Nexus 10 tablet over USB cable using port forwarding:

```
$ adb forward tcp:2222 tcp:2222
$ rsync --delete --size-only -rvW . localhost:sd/Books/
```

(inside Termux sshd is started with "sshd -p 2222").

This used to work before, but now it just hangs. I tried unplugging USB cable and plugging it back in. Revoking USB debugging authorisation and granting it again. Killing adb server on the workstation and restarting it. Nothing helps. It just hangs like this:

```
$ rsync --exclude-from=nexus10.exclude --delete --size-only -rvW . localhost:sd/Books/Science/
sending incremental file list
```

Also, when rsync is started, the `adb shell` session in another terminal hangs as well, i.e. I can no longer type any commands to it and have to kill that session. But adb devices shows nothing wrong:

```
$ adb devices
List of devices attached
R32D100RVZK	device
```

Trying to start `adb shell` hangs as well. And `ssh localhost` hangs as well.

So, as a last resort, I had to turn on WiFi on both the router and Nexus10 and rsync over WiFi (normally I keep WiFi off as microwave radiation should not be used anywhere near humans).

**Comment by alive4ever** [comment]
`sshd` with the port forwarding setup doesn't listen on `localhost`. It listens on `localhost:2222`.

For this to work, add port number to ssh command.

`ssh -p 2222 user@localhost`/

Without port number, ssh will connect to port 22 which is not available since the tcp forwarding listens on port 2222.

For rsync to work, add `-e` switch to explicitly select the correct port.

`rsync -e 'ssh -p 2222' user@localhost:/sdcard ~/sdcard`

**Comment by tigran123** [comment]
@alive4ever As I said, this worked before. Obviously, I had the following in my ~/.ssh/config:

```
$ cat ~/.ssh/config 
Host localhost
 Port 2222
Host nexus10
 Port 2222
Host nexus10e
 Port 2222
Host 192.168.57.101
 Port 2222
Host 192.168.1.30
 Port 2222
Host umi
 Port 2222
Host umis
 Port 2222
Host tether
 Port 2222
```

**Comment by alive4ever** [comment]
Have you tried with another good usb cable?

**Comment by tigran123** [comment]
@alive4ever Good point. But this Nexus10 device has a peculiar feature --- USB debugging authorisation works only with the USB cable that came with it. So, with any other USB cable "adb devices" always reports this device as "unauthorized". I tried revoking USB debug authorisation from Android Settings side, but it didn't help. I.e. it revoked it ok, but the dialog prompting for the new authorization never appeared. And when I plugged in the "official" USB cable the authorization dialog appeared and "adb devices" and even "adb shell" worked fine. But when I tried to rsync it hang and all other sessions, i.e. "adb shell" and "ssh localhost" also hang.

**Comment by alive4ever** [comment]
How about using latest adb binary from [android platform tools](https://developer.android.com/studio/releases/platform-tools.html)?

**Comment by tigran123** [comment]
I use the latest adb that is installed on Ubuntu 16.02:

```
$ adb version
Android Debug Bridge version 1.0.32
Revision debian
```

I regularly do "apt update ; apt upgrade" so it can't be too old. I suppose I could install the very latest one manually...

**Comment by tigran123** [comment]
UPDATE: I have upgraded adb to the latest version:

```
$ ./adb  version
Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android
```

and the problem is still there, i.e. attempting rsync hangs everything and makes the device change status to "offline".

**Comment by tigran123** [comment]
UPDATE: I have performed factory reset on this Nexus 10 tablet and the problem disappeared. I.e. re-installed Termux, openssh etc and now I am running rsync over USB with no problems....
