### ISSUE TITLE
[Bug]:  fontconfig does not honor local.conf

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#10743]
### Problem description

File `$PREFIX/etc/fonts.conf` includes `/system/fonts`. This may not be appropriate for many users (such as myself),
since it includes numerous fonts that I cannot use. That makes it difficult to choose fonts in a graphics or document program.

If I add file `$PREFIX/etc/local.conf` then run `fc-cache -r`, no effect. I see that `51-local.conf` is enabled in xdg, so that is not the problem.

No joy if I add or edit files in `~/.config/fontconfig`.

Only solution is to edit `$PREFIX/fonts/fonts.conf` then run `fc-cache -r`.

But `$PREFIX/fonts/fonts.conf` warns me that any edit may be lost on updates.

### What steps will reproduce the bug?

Repeat edit `fonts.conf` then run `fc-cache -r` with and without `/system/fonts` included. With or without file `local.conf`.

### What is the expected behavior?

With file `local.conf` not containing `/system/fonts`, the Android system fonts should not appear in the list of fonts available to programs. Note: This device is not rooted. 32-bit.

### System information

termux-info:

```
Termux Variables:
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.sahilister.in/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22626479 #1 SMP PREEMPT Wed Feb 16 19:15:27 +07 2022 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T510
```

**Comment by xtkoba** [comment]
Do you `<reset-dirs />`? (See also `$PREFIX/share/fontconfig/conf.avail/05-reset-dirs-sample.conf`.)

**Comment by rallg** [comment]
Thanks. That was the problem. Issue closed.

After I copied the above-mentioned *05 file into `$PREFIX/etc/fonts/conf.d` then ran `fc-cache -r` again, all good.
