### ISSUE TITLE
Please include PHP module to work with apache2 in php package

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#1074]
I have tested the apache2 package in Termux and it seems to work very nicely, but at present there is no way to handle PHP because libphp.so module is missing. Presumably it should come with the php package as that is where the source is.

**Comment by vishalbiswas** [comment]
keep in mind that php is php7 in termux so you'll need to load libphp7.so in apache2 config.
I've opened #1075

**Comment by fornwall** [comment]
@tigran123 Thanks to @vishalbiswas there is now a `php-apache` package available - could you try it out and see if it works (I made a build change but haven't tested if myself)?

**Comment by tigran123** [comment]
@fornwall I have added these lines to httpd.conf:

```
LoadModule php7_module /data/data/com.termux/files/usr/libexec/apache2/libphp7.so

<FilesMatch \.php$>
    SetHandler application/x-httpd-php
</FilesMatch>
```

and also index.php to DirectoryIndex directive, like this:

```
<IfModule dir_module>
    DirectoryIndex index.php
</IfModule>
```

And it worked! Thank you very much. I didn't realise that my web application works fine with PHP 7. So now I don't need PHP 5 anymore! :)

**Comment by rafciozet** [comment]
😍

**Comment by tigran123** [comment]
Something must have changed in two years because now I follow my own instructions of two years ago (see the message above) and it doesn't work, i.e. I get `index.php` file loaded by the browser as a text file, instead of being executed by the php interpreter. I have installed `php-apache` package of course. Any ideas?

**Comment by Keskebeu** [comment]
After adding the lines in httpd.conf this is what I get:
Syntax error on line 69 of /data/data/com.termux/files/usr/etc/apache2/httpd.conf: LoadModule takes two arguments, a module name and the name of a shared object file to load it from
