### ISSUE TITLE
[Package]: mdbook-generate-summary

### ISSUE THREAD

**Issue by 0ompaLoompa** [termux/termux-packages#10759]
### Package description

A tool to automatically generate mdBook SUMMARY.md files

### Home page URL

https://crates.io/crates/mdbook-generate-summary

### Source code URL

https://github.com/younata/mdbook-generate-summary

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
`Cargo.toml` says that license is MIT but no license file is found. We cannot legally package this.
