### ISSUE TITLE
termux-chroot uses wrong timezone

### ISSUE THREAD

**Issue by paradigm** [termux/termux-packages#1076]
The timezone within termux-chroot appears incorrect:

    $ date
    Thu Jun  8 20:23:30 EDT 2017
    $ termux-chroot
    $ date
    Fri Jun  9 00:23:38 GMT 2017

I tried poking through the output of `strace date` to see if I could figure out what the difference was between the two environments but nothing stood out as obvious.  It appears to be doing something different from reading `/etc/localtime` as one would expect on traditional Linux distros.

Setting `$TZ` in my shell's rc file does resolve the issue for me, personally (provided I don't cross timezones and forget to update this...), but I expect this will surprise others.  Whatever is utilized to get the timezone in a normal termux instance should be made to work in a termux-chroot one as well.

Thanks!

**Comment by tinydynamite00** [comment]
The discrepancy between machine time and the timezone shown in a chroot environment is a well documented phenomenon. In fact, were you to chroot a full distro, an initial step in your setup would be to run <code>dpkg-reconfigure tzdata</code>, which takes you through ncurses, dialog driven time configuration menus. Basically, a chroot jail has no way of accessing/querying DNS directly nor can it precisely query the machine on which it runs - it is, after all, an arbitrarily configured system itself; virtual, if you prefer. 

If this topic is of more interest to you, run a search; any combination of the following: '/etc/localtime', 'chroot', 'ln -sf /usr/share/zoneinfo/*' will be informative.

**Comment by paradigm** [comment]
Were I running a traditional distro such as Debian in a chroot, then yes - all that would be applicable.  I could run `dpkg-reconfigure tzdata` to set the timezone, or edit `/etc/localtime`, etc.  However, I do not believe that to be the case here.  That's not *quite* what `termux-chroot` does.  For one thing, there's no `/etc/localtime` or `/usr/share/zoneinfo/` involved here, either within or outside of the `termux-chroot` environment.

Some background on termux in general to illuminate why `termux-chroot` exists, at least as I understand it: Termux distributes packages patched to work directly in Android without abstractions such as `chroot` or root access needed to, for example, create a `/bin`.  While this works great for the specially patched software provided by Termux's repository, it causes problems with things like `#!/bin/sh` scripts (as there's no `/bin/sh`!).  To avoid requiring everyone patch everything for use in Termux, it provides [termux-chroot](https://github.com/termux/termux-packages/blob/master/packages/proot/termux-chroot) in the [proot package](https://github.com/termux/termux-packages/tree/master/packages/proot) which makes a `chroot`ed environment (well, sort of - chroot(2) requires root, so it uses proot instead) and remaps things via mounts (well, again, root-less proot mechanisms, but the same idea) so all of the existing Termux software works while also ensuring things like `#!/bin/sh` work.  Essentially, Termux lets you chose if you want to go abstraction free or, if you need, use some light abstraction to make a more familiar environment.

Thus, `termux-chroot` already maps *most* things needed for the chroot-ish environment to work within the environment as they do outside of it.  [Poke around the source here to get a feel for what it already does](https://github.com/termux/termux-packages/blob/master/packages/proot/termux-chroot).

The goal of issue is to get it to do one more thing: whatever is necessary for timezone information to work within the environment as it does outside.  As mentioned in my original post, whatever is being used here, it's not `/etc/localtime`.

**Comment by michalbednarski** [comment]
I'd guess this is because tzdata on Android can be read from following locations:

# /data/misc/zoneinfo/current/tzdata
* Updates of this file are done by `ConfigUpdater` system application independently of system updates.
* This location is not mounted into `termux-chroot`, so it won't be used inside chroot
* I suppose it exists on your device and is used when you're not in `termux-chroot`

# /system/usr/share/zoneinfo/tzdata
* Location used only if `/data/...` file couldn't be read
* Updated only as part of system updates

**Comment by fornwall** [comment]
@michalbednarski Perhaps the whole `/data/` directory should be mounted by `termux-chroot`?

**Comment by paradigm** [comment]
Adding `/data` to the mounts in termux-chroot locally fixed the time zone issue for me.  Experimenting with it throughout the day, I've not run into any new issues as a result.

**Comment by paradigm** [comment]
I added `/data` to the mounts in termux-chroot and experimented with it.  It seemed to work fine until I realized I left my `$TZ` change in place.  Upon removing it I found that the `/data` mount was insufficient to resolve the issue.

Checking with `strace`, it doesn't look like `/data/misc/zoneinfo/current/tzdata` is being used for timezone information anyways, either in or out of `termux-chroot`:

    $ strace -tvf -s999 date 2>&1 | grep 'tzdata'
    21:46:17 openat(AT_FDCWD, "/data//misc/zoneinfo/current/tzdata", O_RDONLY) = -1 ENOENT (No such file or directory)
    21:46:17 openat(AT_FDCWD, "/system//usr/share/zoneinfo/tzdata", O_RDONLY) = 3
    21:46:17 read(3, "tzdata2016j\0\0\0\0\30\0\0xX\0\7Z\332", 24) = 24
    21:46:17 openat(AT_FDCWD, "/data//misc/zoneinfo/current/tzdata", O_RDONLY) = -1 ENOENT (No such file or directory)
    21:46:17 openat(AT_FDCWD, "/system//usr/share/zoneinfo/tzdata", O_RDONLY) = 3
    21:46:17 read(3, "tzdata2016j\0\0\0\0\30\0\0xX\0\7Z\332", 24) = 24
    $ termux-chroot
    $ strace -tvf -s999 date 2>&1 | grep 'tzdata'
    01:46:54 openat(AT_FDCWD, "/data//misc/zoneinfo/current/tzdata", O_RDONLY) = -1 ENOENT (No such file or directory)
    01:46:54 openat(AT_FDCWD, "/system//usr/share/zoneinfo/tzdata", O_RDONLY) = 3
    01:46:54 read(3, "tzdata2016j\0\0\0\0\30\0\0xX\0\7Z\332", 24) = 24
    01:46:54 openat(AT_FDCWD, "/data//misc/zoneinfo/current/tzdata", O_RDONLY) = -1 ENOENT (No such file or directory)
    01:46:54 openat(AT_FDCWD, "/system//usr/share/zoneinfo/tzdata", O_RDONLY) = 3
    01:46:54 read(3, "tzdata2016j\0\0\0\0\30\0\0xX\0\7Z\332", 24) = 24

**Comment by paradigm** [comment]
After some additional digging, I found [that apparently the timezone is acquired via something called `getprop` / `__system_property_get`](https://github.com/termux/termux-packages/issues/448).  Running `getprop persist.sys.timezone` resulted in my timezone in a normal termux shell but not in `termux-chroot`.

With this in mind, I reviewed the strace logs in and out of `termux-chroot`, grepping for `prop`, and noticed a difference when reading `/property_contexts`.  Adding that to the `termux-chroot` mounts (and double checking that I've disabled my shell rc's `$TZ` work-around), it appears this resolves the issue.  `date` now has the timezone in and out of `termux-chroot`

I propose adding something along the lines of:

    # Needed for getopt calls.  Such calls are used for things like getting the
    # timezone.
    ARGS="$ARGS -b /property_contexts:/property_contexts"

to `termux-chroot`.

**Comment by Neo-Oli** [comment]
Binding /property_contexts also fixes https://github.com/termux/termux-api/issues/89

**Comment by fornwall** [comment]
Nice findings!

Does https://github.com/termux/termux-packages/pull/1081/files look good?

**Comment by paradigm** [comment]
Looks good to me!

**Comment by fornwall** [comment]
The above pull request was merged into version `5.1.105-1` of the proot package, so this issue should now be fixed!

**Comment by kaushalmodi** [comment]
I ended up on this thread as I was surprised to see the time showed by Termux Emacs to be in GMT 00 or UK time zone. E.g. it's 5am EST, but the time shown within Emacs is 10am. 

I couldn't follow this thread.. is there something I need to put in my Termux config locally to fix this?

**Comment by Neo-Oli** [comment]
@kaushalmodi Is your problem at all related to `termux-chroot` or is it a general problem running emacs. I just tested it on my phone and emacs shows the correct time inside and outside of `termux-chroot`. Can you run `pkg up` to see if you can update any packages?

**Comment by Neo-Oli** [comment]
I tested it even with TZ unset and it still works. What is the output of `getprop persist.sys.timezone` on your device? It should print the correct timezone. 
In by .bash_profile I have the following set because some self-compiled or pip/gem installed programs may still require it (khal for example):
`export TZ=$(getprop persist.sys.timezone)`

**Comment by kaushalmodi** [comment]
The `getprop` outputs `America/New_York` correctly. 

>  I tested it even with TZ unset 

Try doing `(setenv "TZ" "")` within Emacs. I'd be surprised if you still saw the correct time (unless you *are* in UTC 00 time zone :))

https://www.gnu.org/software/emacs/manual/html_node/elisp/Time-Zone-Rules.html

**Comment by Neo-Oli** [comment]
> `(setenv "TZ" "")`

Yeah, you're right. That causes the time zone to be wrong. You may want to create a separate issue for this. In my opinion TZ should be set by default.

**Comment by jean** [comment]
It looks like this issue affects `tzdata` in Python:
https://github.com/regebro/tzlocal/issues/55

**Comment by KatravathShankar** [comment]
> The timezone within termux-chroot appears incorrect:
> 
> ```
> $ date
> Thu Jun  8 20:23:30 EDT 2017
> $ termux-chroot
> $ date
> Fri Jun  9 00:23:38 GMT 2017
> ```
> 
> I tried poking through the output of `strace date` to see if I could figure out what the difference was between the two environments but nothing stood out as obvious. It appears to be doing something different from reading `/etc/localtime` as one would expect on traditional Linux distros.
> 
> Setting `$TZ` in my shell's rc file does resolve the issue for me, personally (provided I don't cross timezones and forget to update this...), but I expect this will surprise others. Whatever is utilized to get the timezone in a normal termux instance should be made to work in a termux-chroot one as well.
> 
> Thanks!

Date time of upadate

**Comment by KatravathShankar** [comment]
Update date te
