### ISSUE TITLE
[Bug]: add dependency for lv2

### ISSUE THREAD

**Issue by mjuned47** [termux/termux-packages#10766]
### Problem description

To avoid error during installation of lv2 package
Add libxslt as dependency
![Screenshot_2022-05-21-11-22-21-110_com termux](https://user-images.githubusercontent.com/68558066/169637843-73ca890d-4f90-4a11-b125-4db1d6fc41d2.jpg)

### What steps will reproduce the bug?

Install lv2 package
During installation of other dependency through pip 
Libxslt is missing thus gives error

### System information

Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=19306
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g040a88f #1 SMP PREEMPT Thu Nov 7 00:28:25 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 4

**Comment by 2096779623** [comment]
wiki.termux.com/wiki/python
See How To Install lxml.
