### ISSUE TITLE
[Bug]: pkg: line 142: syntax error in expression (error token is "8 9 11 12 13 14 16")

### ISSUE THREAD

**Issue by UltraStudioLTD** [termux/termux-packages#10778]
### Problem description

When I try to use <kbd>pkg</kbd> it shows following error:

```
Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://mirror.mwt.me/termux/main: ok
[*] https://termux.sahilister.in/apt/termux-main: ok
[*] https://plug-mirror.rcac.purdue.edu/termux/termux-main: ok
[*] https://termux.mentality.rip/termux-main: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://termux.librehat.com/apt/termux-main: bad
[*] https://termux.astra.in.ua/apt/termux-main: ok
[*] https://packages-cf.termux.org/apt/termux-main: ok
[*] https://dl.kcubeterm.com/termux-main: ok
/data/data/com.termux/files/usr/bin/pkg: line 142: 7
8
9
11
12
13
14
16: syntax error in expression (error token is "8
9
11
12
13
14
16")
```

### What steps will reproduce the bug?

When mirrors aren't updated running `pkg upgrade` or `pkg install [something]` or `pkg update`. I haven't tested anything else.

### What is the expected behavior?

To complete job without error

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=6266
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.kcubeterm.com/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.186-g759c88b6c5dc #1 SMP PREEMPT Wed Jan 12 11:21:08 WIB 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8 Pro
```

**Comment by zairullahdev** [comment]
use apt instead pkg, maybe the developer typo at writing script

**Comment by agnostic-apollo** [comment]
`IFS` not being restored. Will fix it.

https://github.com/termux/termux-packages/commit/f1a83c58feaa9c96cfd82a5598ee475860e527f3#diff-926df3194e5f727be3fefbac2278032a4b2331fa147ddb70c3898602a23765a4R198

#10486

**Comment by Maxython** [comment]
> `IFS` not being restored. Will fix it.
> 
> [f1a83c5#diff-926df3194e5f727be3fefbac2278032a4b2331fa147ddb70c3898602a23765a4R198](https://github.com/termux/termux-packages/commit/f1a83c58feaa9c96cfd82a5598ee475860e527f3#diff-926df3194e5f727be3fefbac2278032a4b2331fa147ddb70c3898602a23765a4R198)
> 
> #10486

Ok, I see. I will fix it.

**Comment by agnostic-apollo** [comment]
I have to make other changes, will do it myself, no worries.

**Comment by UltraStudioLTD** [comment]
> use apt instead pkg, maybe the developer typo at writing script

I am using <kbd>apt</kbd> as replacement for now, it's just that I kinda like <kbd>pkg</kbd>'s automatic mirror management.

**Comment by Maxython** [comment]
> I have to make other changes, will do it myself, no worries.

Yes, but also need to fix another error in pkg. This is related to the `TERMUX_MAIN_PACKAGE_FORMAT` value.

**Comment by agnostic-apollo** [comment]
I assume that's for people who updated from very old `termux-tools` version whose `login` script didn't export the variable. Variable can be expanded with `${TERMUX_MAIN_PACKAGE_FORMAT-}` to prevent error and can default to `debian`. Although, now priority needs to be given to `TERMUX_APP_PACKAGE_MANAGER` (`apt`/`pacman`) anyways.

**Comment by zairullahdev** [comment]
So we can close now?

**Comment by UltraStudioLTD** [comment]
> So we can close now?

Yes.

**Comment by agnostic-apollo** [comment]
This is currently not fixed. The `termux-tools` `v0.180` will be released soon with the fix, will notify when it is.

**Comment by agnostic-apollo** [comment]
The `termux-tools` `v0.180` is out on default repository and will be available on other mirrors when they sync. Users can switch to default repo with `termux-change-repo` and can update to it with `apt update; apt install termux-tools`

https://packages.termux.org/apt/termux-main/pool/main/t/termux-tools/

**Comment by kumkee** [comment]
> The `termux-tools` `v0.180` is out on default repository and will be available on other mirrors when they sync. Users can switch to default repo with `termux-change-repo` and can update to it with `apt update; apt install termux-tools`
> 
> https://packages.termux.org/apt/termux-main/pool/main/t/termux-tools/

I can't use this solution. When I try `apt update` I encounter [this bug](https://github.com/termux/termux-app/issues/1958). Over there, the solution was to `pkg update` which leads to this bug.

How do I come out of the dead loop, please?

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#google-play-store-deprecated

https://github.com/termux/termux-app#installation

**Comment by kumkee** [comment]
> 

Mine is the latest version 0.118.0 and was installed from F-Droid in April or May. 
`pkg` used to work back then.
