### ISSUE TITLE
[Package]: mGBA

### ISSUE THREAD

**Issue by zairullahdev** [termux/termux-packages#10779]
### Package description

A Gameboy emulator

### Home page URL

https://mgba.io

### Source code URL

https://github.com/mgba-emu/mgba

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
> Support for OpenGL 1.1 or newer is also required, with OpenGL 3.2 or newer for shaders and advanced features.

**Comment by Pihuchoudhary** [comment]
I am Instagram hack

**Comment by xtkoba** [comment]
For developers, this software does not seem to involve `qtopengl`. For example, <a href="https://github.com/gentoo/gentoo/blob/2dc57d72ada009425ab74d4ff46064a17d477782/games-emulation/mgba/mgba-0.9.3-r2.ebuild">this ebuild from Gentoo Portage</a> does not list it as a dependency (of any types).
