### ISSUE TITLE
[Bug]: ncspot needs to be built without MPRIS support

### ISSUE THREAD

**Issue by asolidtime** [termux/termux-packages#10772]
### Problem description

The currently packaged version of ncspot is built with MPRIS support, so, if there's no running Xserver or D-Bus daemon, it attempts to start one, fails, and crashes:
```
$ ncspot
thread '<unnamed>' panicked at 'Failed to connect to dbus: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)', src/mpris.rs:175:14
```
This can be fixed by building it without MPRIS support:
```
$ cargo build --release --no-default-features --features pulseaudio_backend,cursive/pancurses-backend
```
although this would disable external media controls for people using it with a working D-Bus setup, so I was unsure about submitting a pull request.

### What steps will reproduce the bug?

```
pkg install ncspot
ncspot
```
Then, login and try to play a song.

### What is the expected behavior?

Normal playback happens.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=784
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.kcubeterm.com/termux-main/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 5.4.147-qgki-24105351-abG991USQU5CVDB #1 SMP PREEMPT Thu Apr 21 17:58:36 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G991U
```

**Comment by MrAdityaAlok** [comment]
Shouldn't this be a feature request upstream?

 As you said, it might break working setup of others.

**Comment by asolidtime** [comment]
Sorry, wdym by upstream? ncspot?

**Comment by MrAdityaAlok** [comment]
> Sorry, wdym by upstream? ncspot?

Yes, I ment ncspot.

**Comment by MrAdityaAlok** [comment]
> (IMHO) Would it be a good idea to split ncspot into two packages, with and without MPRIS support?

Yes, I was too thinking of seperating ncspot into two paclages:
- `ncspot`: without X support
- `ncspot-mpris` with X support in `x11-repo`

I'll do it ASAP.

**Comment by asolidtime** [comment]
Thanks!
