### ISSUE TITLE
[Bug]: graphviz has linking errors

### ISSUE THREAD

**Issue by toomails9999** [termux/termux-packages#10777]
### Problem description

all graphviz command have linking errors
cannot locate symbol "glob" referenced by "/data/data/com.termux/files/usr/lib/libgvc.so"...

### What steps will reproduce the bug?

1. type circo, twopi, patchwork or any

### What is the expected behavior?

graphviz starts linking

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Can't reproduce the issue, and you haven't provided termux-info so can't tell what is wrong in your env, but I would guess outdated packages
