### ISSUE TITLE
[Package]: fontforge

### ISSUE THREAD

**Issue by drakulaboy** [termux/termux-packages#10781]
### Package description

FontForge allows you to edit outline and bitmap fonts. You may create new ones or modify old ones. It is also a format converter and can interconvert between PostScript (ascii & binary Type1, some Type3, some Type0), TrueType, OpenType (Type2), CID, SVG
TLDR: it can edit, create fonts with command line and Python Scripting 

### Home page URL

https://fontforge.org/en-US/

### Source code URL

https://github.com/fontforge/fontforge

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
#10650

**Comment by MrAdityaAlok** [comment]
> ❯ apt search fontforge
Sorting... Done
Full Text Search... Done
fontforge-gtk/x11 20220308 aarch64
  A free (libre) font editor

We already have fontforge packaged as `fontforge-gtk`. You should check before requesting.


**Note:** it is in x11-repo, so first do:
```bash
 apt upgrade && apt install x11-repo
```

**Comment by drakulaboy** [comment]
oh, it was in another repo, thank you very much!
