### ISSUE TITLE
[Bug]: pkg is not working anymore

### ISSUE THREAD

**Issue by azclub-ltd** [termux/termux-packages#10782]
### Problem description

when I try to install or update packages using pkg, it show me the following error:-

/data/data/com.termux/files/usr/bin/pkg: line 197: TERMUX_MAIN_PACKAGE_FORMAT: unbound variable

### Steps to reproduce the behavior.

All I found in the internet is to use apt instead of pkg.

### What is the expected behavior?

It should install or update packages.

### System information

* Termux application version: v0.118
* Android OS version: 9
* Device model: Oppo A1k

**Comment by agnostic-apollo** [comment]
The `termux-tools` `v0.180` is out on default repository with the fix and will be available on other mirrors when they sync. Users can switch to default repo with `termux-change-repo` and can update to it with `apt update; apt install termux-tools`

https://packages.termux.org/apt/termux-main/pool/main/t/termux-tools/
