### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wahyu6070** [termux/termux-packages#10790]
### Problem description

$ curl                                                CANNOT LINK EXECUTABLE "curl": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libssh2.so in namespace (default)

### What steps will reproduce the bug?

P

### What is the expected behavior?

.

### System information

~ $ termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list                                          deb https://packages.termux.org/apt/termux-main/ stable main                                                    Updatable packages:                                     apt/stable 2.5.0 aarch64 [upgradable from: 2.3.13-3]    bash/stable 5.1.16-1 aarch64 [upgradable from: 5.1.12-2]ca-certificates/stable 1:2022.03.29 all [upgradable from: 1:2021-10-26-0]                                       command-not-found/stable 1.75 aarch64 [upgradable from: 1.71]
coreutils/stable 9.1 aarch64 [upgradable from: 9.0]
dash/stable 0.5.11.5-1 aarch64 [upgradable from: 0.5.11.5]                                                      debianutils/stable 5.7 aarch64 [upgradable from: 5.5]
dialog/stable 1.3-20220117-0 aarch64 [upgradable from: 1.3-20211214-0]                                          dpkg/stable 1.21.7 aarch64 [upgradable from: 1.21.1]    ed/stable 1.18 aarch64 [upgradable from: 1.17-4]
findutils/stable 4.9.0-1 aarch64 [upgradable from: 4.8.0]
gawk/stable 5.1.1-1 aarch64 [upgradable from: 5.1.1]
gpgv/stable 2.3.6 aarch64 [upgradable from: 2.3.4]
gzip/stable 1.12 aarch64 [upgradable from: 1.11-3]
inetutils/stable 1.9.4-13 aarch64 [upgradable from: 1.9.4-12]
libcap-ng/stable 2:0.8.3 aarch64 [upgradable from: 1:0.8.3-pre1-0]
libcrypt/stable 0.2-5 aarch64 [upgradable from: 0.2-3]
libevent/stable 2.1.12-1 aarch64 [upgradable from: 2.1.12]
libexpat/stable 2.4.8 aarch64 [upgradable from: 2.4.2]
libgcrypt/stable 1.10.1 aarch64 [upgradable from: 1.9.4]
libgmp/stable 6.2.1-1 aarch64 [upgradable from: 6.2.1]
libgnutls/stable 3.7.5 aarch64 [upgradable from: 3.6.16-1]
libgpg-error/stable 1.45 aarch64 [upgradable from: 1.43]
libmpfr/stable 4.1.0-1 aarch64 [upgradable from: 4.1.0]
libnghttp2/stable 1.47.0 aarch64 [upgradable from: 1.46.0]
libssh2/stable 1.10.0-2 aarch64 [upgradable from: 1.10.0]
libtirpc/stable 1.3.2-1 aarch64 [upgradable from: 1.3.2]
libunistring/stable 1.0 aarch64 [upgradable from: 0.9.10-5]
lsof/stable 4.95.0-1 aarch64 [upgradable from: 4.94.0-1]
nano/stable 6.3 aarch64 [upgradable from: 6.0]
ncurses/stable 6.3-1 aarch64 [upgradable from: 6.2.20200725-6]
pcre2/stable 10.40 aarch64 [upgradable from: 10.39-2]
termux-am-socket/stable 1.3.0 aarch64 [upgradable from: 1.02]
termux-exec/stable 1:1.0 aarch64 [upgradable from: 1:0.9]
termux-keyring/stable 3.4 all [upgradable from: 2.4]
termux-licenses/stable 2.0-2 all [upgradable from: 2.0-1]
termux-tools/stable 0.180 all [upgradable from: 0.155]
unbound/stable 1.15.0-1 aarch64 [upgradable from: 1.13.2-1]
util-linux/stable 2.38 aarch64 [upgradable from: 2.37.2-1]
zlib/stable 1.2.12 aarch64 [upgradable from: 1.2.11-5]
Android version:
12
Kernel build information:
Linux localhost 4.14.278-SiLonT-Zeta/c58754fb #1 SMP PREEMPT Sat May 14 08:37:53 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
A69DC0DF
~ $ curl
CANNOT LINK EXECUTABLE "curl": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libssh2.so in namespace (default)
~ $

**Comment by licy183** [comment]
Upgrade your pakcages. `pkg up`.

**Comment by thunder-coding** [comment]
Follow #9050 on how to recover from broken environment
