### ISSUE TITLE
cant install shellcheck

### ISSUE THREAD

**Issue by xuiv** [termux/termux-packages#10796]
`
Setting up haskell-th-abstraction (0.4.3.0) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-th-abstraction (--configure):
 installed haskell-th-abstraction package post-installation script subprocess returned error exit status 1
Setting up haskell-statevar (1.2.2) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-statevar (--configure):
 installed haskell-statevar package post-installation script subprocess returned error exit status 1
Setting up haskell-tagged (0.8.6.1) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-tagged (--configure):
 installed haskell-tagged package post-installation script subprocess returned error exit status 1
Setting up haskell-dlist (1.0) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-dlist (--configure):
 installed haskell-dlist package post-installation script subprocess returned error exit status 1
Setting up haskell-primitive (0.7.3.0) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-primitive (--configure):
 installed haskell-primitive package post-installation script subprocess returned error exit status 1
Setting up haskell-regex-base (0.94.0.2) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-regex-base (--configure):
 installed haskell-regex-base package post-installation script subprocess returned error exit status 1
Setting up haskell-indexed-traversable (0.1.2) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-indexed-traversable (--configure):
 installed haskell-indexed-traversable package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of haskell-witherable:
 haskell-witherable depends on haskell-indexed-traversable; however:
  Package haskell-indexed-traversable is not configured yet.

dpkg: error processing package haskell-witherable (--configure):
 dependency problems - leaving unconfigured
Setting up haskell-diff (0.4.1) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-diff (--configure):
 installed haskell-diff package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of haskell-semialign:
 haskell-semialign depends on haskell-tagged; however:
  Package haskell-tagged is not configured yet.
 haskell-semialign depends on haskell-indexed-traversable; however:
  Package haskell-indexed-traversable is not configured yet.

dpkg: error processing package haskell-semialign (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of shellcheck:
 shellcheck depends on haskell-diff; however:
  Package haskell-diff is not configured yet.

dpkg: error processing package shellcheck (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-contravariant:
 haskell-contravariant depends on haskell-statevar; however:
  Package haskell-statevar is not configured yet.

dpkg: error processing package haskell-contravariant (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-regex-tdfa:
 haskell-regex-tdfa depends on haskell-regex-base; however:
  Package haskell-regex-base is not configured yet.

dpkg: error processing package haskell-regex-tdfa (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-scientific:
 haskell-scientific depends on haskell-primitive; however:
  Package haskell-primitive is not configured yet.

dpkg: error processing package haskell-scientific (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-assoc:
 haskell-assoc depends on haskell-tagged; however:
  Package haskell-tagged is not configured yet.

dpkg: error processing package haskell-assoc (--configure):
 dependency problems - leaving unconfigured
Setting up haskell-base-compat (0.12.1) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-base-compat (--configure):
 installed haskell-base-compat package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of haskell-comonad:
 haskell-comonad depends on haskell-tagged; however:
  Package haskell-tagged is not configured yet.
 haskell-comonad depends on haskell-indexed-traversable; however:
  Package haskell-indexed-traversable is not configured yet.

dpkg: error processing package haskell-comonad (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-distributive:
 haskell-distributive depends on haskell-tagged; however:
  Package haskell-tagged is not configured yet.

dpkg: error processing package haskell-distributive (--configure):
 dependency problems - leaving unconfigured
Setting up haskell-base-orphans (0.8.6) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-base-orphans (--configure):
 installed haskell-base-orphans package post-installation script subprocess returned error exit status 1
Setting up haskell-splitmix (0.1.0.4) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-splitmix (--configure):
 installed haskell-splitmix package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of haskell-indexed-traversable-instances:
 haskell-indexed-traversable-instances depends on haskell-tagged; however:
  Package haskell-tagged is not configured yet.
 haskell-indexed-traversable-instances depends on haskell-indexed-traversable; however:
  Package haskell-indexed-traversable is not configured yet.

dpkg: error processing package haskell-indexed-traversable-instances (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-strict:
 haskell-strict depends on haskell-assoc; however:
  Package haskell-assoc is not configured yet.

dpkg: error processing package haskell-strict (--configure):
 dependency problems - leaving unconfigured
Setting up haskell-integer-logarithms (1.0.3.1) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-integer-logarithms (--configure):
 installed haskell-integer-logarithms package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of haskell-base-compat-batteries:
 haskell-base-compat-batteries depends on haskell-base-compat; however:
  Package haskell-base-compat is not configured yet.

dpkg: error processing package haskell-base-compat-batteries (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-quickcheck:
 haskell-quickcheck depends on haskell-splitmix; however:
  Package haskell-splitmix is not configured yet.

dpkg: error processing package haskell-quickcheck (--configure):
 dependency problems - leaving unconfigured
Setting up haskell-hashable (1.3.5.0) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-hashable (--configure):
 installed haskell-hashable package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of haskell-attoparsec:
 haskell-attoparsec depends on haskell-scientific; however:
  Package haskell-scientific is not configured yet.

dpkg: error processing package haskell-attoparsec (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-aeson:
 haskell-aeson depends on haskell-semialign; however:
  Package haskell-semialign is not configured yet.
 haskell-aeson depends on haskell-dlist; however:
  Package haskell-dlist is not configured yet.
 haskell-aeson depends on haskell-attoparsec; however:
  Package haskell-attoparsec is not configured yet.
 haskell-aeson depends on haskell-strict; however:
  Package haskell-strict is not configured yet.
 haskell-aeson depends on haskell-quickcheck; however:
  Package haskell-quickcheck is not configured yet.
 haskell-aeson depends on haskell-tagged; however:
  Package haskell-tagged is not configured yet.
 haskell-aeson depends on haskell-th-abstraction; however:
  Package haskell-th-abstraction is not configured yet.
 haskell-aeson depends on haskell-indexed-traversable; however:
  Package haskell-indexed-traversable is not configured yet.
 haskell-aeson depends on haskell-primitive; however:
  Package haskell-primitive is not configured yet.
 haskell-aeson depends on haskell-base-compat-batteries; however:
  Package haskell-base-compat-batteries is not configured yet.
 haskell-aeson depends on haskell-scientific; however:
  Package haskell-scientific is not configured yet.
 haskell-aeson depends on haskell-witherable; however:
  Package haskell-witherable is not configured yet.
 haskell-aeson depends on haskell-hashable; however:
  Package haskell-hashable is not configured yet.

dpkg: error processing package haskell-aeson (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-bifunctors:
 haskell-bifunctors depends on haskell-base-orphans; however:
  Package haskell-base-orphans is not configured yet.
 haskell-bifunctors depends on haskell-comonad; however:
  Package haskell-comonad is not configured yet.
 haskell-bifunctors depends on haskell-th-abstraction; however:
  Package haskell-th-abstraction is not configured yet.
 haskell-bifunctors depends on haskell-tagged; however:
  Package haskell-tagged is not configured yet.

dpkg: error processing package haskell-bifunctors (--configure):
 dependency problems - leaving unconfigured
Setting up haskell-transformers-compat (0.7.1) ...
ghc-pkg: Couldn't open database /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d for modification: {handle: /data/data/com.termux/files/usr/lib/ghc-8.10.7/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
dpkg: error processing package haskell-transformers-compat (--configure):
 installed haskell-transformers-compat package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of haskell-semigroupoids:
 haskell-semigroupoids depends on haskell-distributive; however:
  Package haskell-distributive is not configured yet.
 haskell-semigroupoids depends on haskell-tagged; however:
  Package haskell-tagged is not configured yet.
 haskell-semigroupoids depends on haskell-hashable; however:
  Package haskell-hashable is not configured yet.
 haskell-semigroupoids depends on haskell-contravariant; however:
  Package haskell-contravariant is not configured yet.
 haskell-semigroupoids depends on haskell-transformers-compat; however:
  Package haskell-transformers-compat is not configured yet.
 haskell-semigroupoids depends on haskell-bifunctors; however:
  Package haskell-bifunctors is not configured yet.
 haskell-semigroupoids depends on haskell-base-orphans; however:
  Package haskell-base-orphans is not configured yet.
 haskell-semigroupoids depends on haskell-comonad; however:
  Package haskell-comonad is not configured yet.

dpkg: error processing package haskell-semigroupoids (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-onetuple:
 haskell-onetuple depends on haskell-base-orphans; however:
  Package haskell-base-orphans is not configured yet.
 haskell-onetuple depends on haskell-hashable; however:
  Package haskell-hashable is not configured yet.

dpkg: error processing package haskell-onetuple (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-these:
 haskell-these depends on haskell-hashable; however:
  Package haskell-hashable is not configured yet.
 haskell-these depends on haskell-assoc; however:
  Package haskell-assoc is not configured yet.

dpkg: error processing package haskell-these (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-vector:
 haskell-vector depends on haskell-primitive; however:
  Package haskell-primitive is not configured yet.

dpkg: error processing package haskell-vector (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-time-compat:
 haskell-time-compat depends on haskell-base-orphans; however:
  Package haskell-base-orphans is not configured yet.
 haskell-time-compat depends on haskell-hashable; however:
  Package haskell-hashable is not configured yet.

dpkg: error processing package haskell-time-compat (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-data-fix:
 haskell-data-fix depends on haskell-hashable; however:
  Package haskell-hashable is not configured yet.

dpkg: error processing package haskell-data-fix (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-uuid-types:
 haskell-uuid-types depends on haskell-hashable; however:
  Package haskell-hashable is not configured yet.

dpkg: error processing package haskell-uuid-types (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-random:
 haskell-random depends on haskell-splitmix; however:
  Package haskell-splitmix is not configured yet.

dpkg: error processing package haskell-random (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-text-short:
 haskell-text-short depends on haskell-hashable; however:
  Package haskell-hashable is not configured yet.

dpkg: error processing package haskell-text-short (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of haskell-unordered-containers:
 haskell-unordered-containers depends on haskell-hashable; however:
  Package haskell-hashable is not configured yet.

dpkg: error processing package haskell-unordered-containers (--configure):
 dependency problems - leaving unconfigured
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
`

**Comment by 2096779623** [comment]
Before this bug was fixed use this command to install shellcheck (via python):
`pkg i python && pip3 install shellcheck`

**Comment by MrAdityaAlok** [comment]
@xuiv please paste output of `termux-info`.

**Comment by 2096779623** [comment]
But shellcheck works fine:
```shell
~ $ shellcheck
No files specified.

Usage: shellcheck [OPTIONS...] FILES...
  -a                  --check-sourced            Include warnings from sourced files
  -C[WHEN]            --color[=WHEN]             Use color (auto, always, never)
  -i CODE1,CODE2..    --include=CODE1,CODE2..    Consider only given types of warnings
  -e CODE1,CODE2..    --exclude=CODE1,CODE2..    Exclude types of warnings
  -f FORMAT           --format=FORMAT            Output format (checkstyle, diff, gcc, json, json1, quiet, tty)
                      --list-optional            List checks disabled by default
                      --norc                     Don't look for .shellcheckrc files
  -o check1,check2..  --enable=check1,check2..   List of optional checks to enable (or 'all')
  -P SOURCEPATHS      --source-path=SOURCEPATHS  Specify path when looking for sourced files ("SCRIPTDIR" for script's dir)
  -s SHELLNAME        --shell=SHELLNAME          Specify dialect (sh, bash, dash, ksh)
  -S SEVERITY         --severity=SEVERITY        Minimum severity of errors to consider (error, warning, info, style)
  -V                  --version                  Print version information
  -W NUM              --wiki-link-count=NUM      The number of wiki links to show, when applicable
  -x                  --external-sources         Allow 'source' outside of FILES
                      --help                     Show this usage summary and exit

~ $ vim a.sh
~ $ shellcheck a.sh

In a.sh line 1:
#/data/data/com.termux/files/usr/bin/bash
 ^-- SC1113 (error): Use #!, not just #, for the shebang.

For more information:
  https://www.shellcheck.net/wiki/SC1113 -- Use #!, not just #, for the sheba...
~ $ cat a.sh
#/data/data/com.termux/files/usr/bin/bash
echo test
```

**Comment by MrAdityaAlok** [comment]
@xuiv it seems that ghc-pkg is unable to open filesystem lock on your device. I haven't seen/heard of an Android variant that disallows filesystem locking. Where are you trying to install it?

**Comment by xuiv** [comment]
`
~ $ termux-info
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
0.181
Android version:
7.1.2
Kernel build information:
Linux localhost 3.14.29 #1 SMP PREEMPT Wed Mar 7 19:32:34 CST 2018 aarch64 Android
Device manufacturer:
Phicomm
Device model:
p230

`

**Comment by xuiv** [comment]
> Before this bug was fixed use this command to install shellcheck (via python): `pkg i python && pip3 install shellcheck-py`

thanks
