### ISSUE TITLE
[Bug]: pkg error selecting mirror

### ISSUE THREAD

**Issue by joshcangit** [termux/termux-packages#10791]
### Problem description

when I install or update packages using `pkg`, it throws error after scanning mirrors:
```
/data/data/com.termux/files/usr/bin/pkg: line 142: 7
8
9
10
11
12
13
14
16: syntax error in expression (error token "8
9
10
11
12
13
14
16")
```

> No, I'm sure this is not related to #10782.

### What steps will reproduce the bug?

Using `pkg` to **install or update** packages, e.g. `pkg up`, should trigger the error.
If a mirror is already set, first do `pkg clean` before installing or updating will trigger the error.

> The error only occurs when selecting a mirror.
> No issue when scanning mirrors or updating from already selected mirror.

### What is the expected behavior?

It should seamlessly go from scanning mirrors to selecting a mirror then to updating from selected mirror.
In short, it should **install or update** packages.

> I use a temporary fix which is the previous version of the `pkg` script.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=20913
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
nodejs/stable 18.2.0 aarch64 [upgradable from: 17.9.0-1]
termux-tools/stable 0.180 all [upgradable from: 0.179]
Android version:
12
Kernel build information:
Linux localhost 4.14.113-23727351 #1 SMP PREEMPT Tue Mar 8 08:35:06 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G973F
```

**Comment by agnostic-apollo** [comment]
Duplicate of #10778

Check https://github.com/termux/termux-packages/issues/10778#issuecomment-1134286983

**Comment by joshcangit** [comment]
Oh, nevermind.
I was updating from outdated mirrors.
The `termux-info` clearly shows the very latest version of `termux-tools`.
