### ISSUE TITLE
./configure not found

### ISSUE THREAD

**Issue by 4thirteen2one** [termux/termux-packages#1079]
When I download a zlib achieve preparing to compile and install it, it tells me "./configure : bad interpreter: /bin/sh: no such file or directory"

**Comment by fornwall** [comment]
Android (and thus Termux) does not have `/bin/sh`, which the configure file assumes in the shebang line. Either:

1. Run the configure file as `sh ./configure`.
2. Fix the shebang line with `termux-fix-shebang configure` before running `./configure`.
3. Install the `proot` package and run `termux-chroot` to enter a chroot-like jail which emulates a traditional file system with `/bin/sh` and more, and then run `./configure`.

Also, note that for zlib you do not need to build it, as it's part of the Android platform, so you can just include `<zlib.h>` and link with `-lz` when building.
