### ISSUE TITLE
[Bug]: texlive-bin commands not recognized

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-packages#10800]
### Problem description

I installed texlive with:
```
pkg install -y texlive-bin texlive-installer
termux-install-tl
```
Then I tried to do an update:
```
tlmgr update --self
tlmgr update --all
```
But I got this error:
```
The program tlmgr is not installed. Install it by executing:
 pkg install texlive-bin
```
Searching around some other issues here, I tried:
```
termux-patch-texlive
```
But the problem persisted. Then, at the end of https://github.com/termux/termux-packages/issues/9010, it is suggested to run:
```
mktexlsr
mtxrun --generate 
updmap-sys
fmtutil-sys --all
```
But the first command gives me the same error that `tlmgr`
Any ideas?

I have to say that I just updated the termux app from 0.117 to 0.118 (I did a fresh install). In 0.117 I didn't have this issue. Already updated and upgraded the system before trying this.

### What steps will reproduce the bug?

Already given the steps in the description of the issue

### What is the expected behavior?

`tlmgr` and other commands from `texlive-bin` should be recognized.

### System information

termux-info:

```
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=4723
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.astra.in.ua/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
0.181
Android version:
12
Kernel build information:
Linux localhost 4.14.180-perf-g5d6f377 #1 SMP PREEMPT Sat Feb 26 00:53:45 CST 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2102J20SG

```

**Comment by kurokirasama** [comment]
> Termux needs to be restarted or `$PREFIX/etc/profile.d/texlive.sh` sourced after installation for `$PREFIX/bin/texlive/` to be added to PATH.
I did source it
> Other possible reasons could be that you chose a scheme in the install-tl TUI that did not include tlmgr. Which scheme did you install? 
I just went with the defaults
>Did installation finish without error? If it finished without error then it should have printed an info message that [`$PREFIX/bin/texlive/` needs to be added to PATH](https://github.com/termux/termux-packages/blob/master/packages/texlive-installer/installer.sh#L68-L70)
Probably yes because I did not see the source message. 

I'll try again taking into account this considerations

**Comment by kurokirasama** [comment]
@Grimler91 Here's the log file: [logFile](https://yadi.sk/d/qrk8B_Ti_INlxw)
I see some errors there, but at the end it says:
```
Welcome to TeX Live!


See /data/data/com.termux/files/usr/share/texlive/index.html for links to documentation.
The TeX Live web site (https://tug.org/texlive/) contains any updates and corrections. TeX Live is a joint project of the TeX user groups around the world; please consider supporting it by joining the group best for you. The list of groups is available on the web at https://tug.org/usergroups.html.


Add /data/data/com.termux/files/usr/share/texlive/texmf-dist/doc/man to MANPATH.
Add /data/data/com.termux/files/usr/share/texlive/texmf-dist/doc/info to INFOPATH.
Most importantly, add /data/data/com.termux/files/usr/share/texlive/bin/aarch64-linux
to your PATH for current and future sessions.
```
I know how to add to PATH, but what are MANPATH and INFOPATH?

**Comment by Grimler91** [comment]
Looks like the installation worked without issues.

The path `/data/data/com.termux/files/usr/share/texlive/bin/aarch64-linux` shouldn't exist, we use `/data/data/com.termux/files/usr/bin/texlive` instead, so it's that folder that needs to be added to path. 

After those messages the installation script tries to patch some scripts and setup symlinks and so on:

```
Add /data/data/com.termux/files/usr/share/texlive/texmf-dist/doc/man to MANPATH.
Add /data/data/com.termux/files/usr/share/texlive/texmf-dist/doc/info to INFOPATH.
Most importantly, add /data/data/com.termux/files/usr/share/texlive/bin/aarch64-linux
to your PATH for current and future sessions.
Logfile: /data/data/com.termux/files/usr/share/texlive/install-tl.log
[*] Installation done.

    Some scripts need to be fixed before they will work in termux.
    The script termux-patch-texlive will now be run to try to fix
    known problems. If your texlive breaks in the future after running
    tlmgr update --all
    then you might be able to fix it by running this script.

Press 'c' to continue
Checking if $PREFIX/opt/texlive/TLUtils.pm.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/crossrefware.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/pdfjam.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/texconfig.sh.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/texdef.pl.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/texmf.cnf.diff can be applied.. Yes
Checking if $PREFIX/opt/texlive/tlmgr.pl.diff can be applied.. Nope
[*] Generating format pdflatex with fmtutil
[*] Running updmap
[*] Setting up symlinks
[*] All done. Restart the shell or source
    /data/data/com.termux/files/usr/etc/profile.d/texlive.sh
    to add the texlive programs to $PATH.
```

**Comment by kurokirasama** [comment]
I see, it's
```
source /data/data/com.termux/files/usr/bin/texlive
```
once enough, or it should be done every time termux starts?

**Comment by kurokirasama** [comment]
Hey @Grimler91 Well, I tried both and now `tlmgr` is recognized, but now I got this error when trying to update:
```
Can't locate TeXLive/TLConfig.pm in @INC (you may need to install the TeXLive::TLConfig module) (@INC contains: /data/data/com.termux/files/usr/texmf-dist/scripts/texlive /data/data/com.termux/files/usr/tlpkg /data/data/com.termux/files/usr/lib/perl5/site_perl/5.34.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.34.1 /data/data/com.termux/files/usr/lib/perl5/5.34.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.34.1) at /data/data/com.termux/files/usr/bin/texlive/tlmgr line 91.
BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/bin/texlive/tlmgr line 91.
```

**Comment by Grimler91** [comment]
No need to put anything in ~/.bashrc. The profile script adds the texlive folder to path:
```
$ cat $PREFIX/etc/profile.d/texlive.sh
export PATH=$PATH:/data/data/com.termux/files/usr/bin/texlive
```
and is [sourced automatically on login](https://github.com/termux/termux-packages/blob/master/packages/bash/etc-profile#L1-L5)

> I got this error when trying to update:
> 
> ```
> Can't locate TeXLive/TLConfig.pm in @INC (you may need to install the TeXLive::TLConfig module) (@INC contains: /data/data/com.termux/files/usr/texmf-dist/scripts/texlive /data/data/com.termux/files/usr/tlpkg /data/data/com.termux/files/usr/lib/perl5/site_perl/5.34.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.34.1 /data/data/com.termux/files/usr/lib/perl5/5.34.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.34.1) at /data/data/com.termux/files/usr/bin/texlive/tlmgr line 91.
> BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/bin/texlive/tlmgr line 91.
> ```

Most likely this should be fixed by `termux-patch-texlive`, so try that and then update all again

**Comment by kurokirasama** [comment]
OK, I reinstalled fresh all again. Same issues, but know, sourcing `$PREFIX/etc/profile.d/texlive.sh` make `tlmgr` recognizable again, but its lost after closing termux.

**Comment by Grimler91** [comment]
What shell are you using?

**Comment by kurokirasama** [comment]
`bash`

**Comment by Grimler91** [comment]
I don't have an explanation then. 

Closing termux, as in closing all shells, and then opening a new termux shell should source the profile scripts. It works for me:
```
$ echo $foo

$ echo "export foo=bar" > $PREFIX/etc/profile.d/test.sh
$ exit
```
after opening a new session:
```
$ echo $foo
bar
```

**Comment by kurokirasama** [comment]
thanks for your help, at least now I can use it, an extra line in `.bashrc` doesn't hurt ;)

**Comment by Grimler91** [comment]
No problem, thanks for testing
