### ISSUE TITLE
Package node version 8.x

### ISSUE THREAD

**Issue by italomaia** [termux/termux-packages#1080]
Version 8.x had some major improvements in network usage. Maybe it is enough reason to update it.

**Comment by fornwall** [comment]
There exists a `disabled-packages/nodejs-current` for building version 8.x of node. It currently doesn't build, so help is welcome here:

Build the dependencies with `./build-package openssl && ./build-package c-ares`, and then investigate the build failure with `./build-package.sh disabled-packages/nodejs-current/`!

**Comment by TheDiamondYT1** [comment]
@fornwall Try and build Node js v7

**Comment by its-pointless** [comment]
I got arm version of nodejs to build...

**Comment by fornwall** [comment]
Since two weeks ago a `nodejs-current` package is now available.

(1) Install `nodejs` to get the current LTS version (currently 6.11.2).
(2) Install `nodejs-current` to get the latest/bleeding edge version (currently 8.4.0).

**Comment by TheDiamondYT1** [comment]
@fornwall Can you update `nodejs-current` to v8.5.0? It includes some useful filesystem features.
