### ISSUE TITLE
Auto update failing for libusb

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#10821]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the libusb package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating libusb [Current version: 1.0.26]
parse error: Invalid numeric literal at line 1, column 20
ERROR: Failed to parse tag name from: '<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
{
  "url": "https://api.github.com/repos/libusb/libusb/releases/64059265",
  "assets_url": "https://api.github.com/repos/libusb/libusb/releases/64059265/assets",
  "upload_url": "https://uploads.github.com/repos/libusb/libusb/releases/64059265/assets{?name,label}",
  "html_url": "https://github.com/libusb/libusb/releases/tag/v1.0.26",
  "id": 64059265,
  "author": {
    "login": "tormodvolden",
    "id": 2403928,
    "node_id": "MDQ6VXNlcjI0MDM5Mjg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2403928?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tormodvolden",
    "html_url": "https://github.com/tormodvolden",
    "followers_url": "https://api.github.com/users/tormodvolden/followers",
    "following_url": "https://api.github.com/users/tormodvolden/following{/other_user}",
    "gists_url": "https://api.github.com/users/tormodvolden/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tormodvolden/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tormodvolden/subscriptions",
    "organizations_url": "https://api.github.com/users/tormodvolden/orgs",
    "repos_url": "https://api.github.com/users/tormodvolden/repos",
    "events_url": "https://api.github.com/users/tormodvolden/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tormodvolden/received_events",
    "type": "User",
    "site_admin": false
  },
  "node_id": "RE_kwDOAOa5JM4D0XeB",
  "tag_name": "v1.0.26",
  "target_commitish": "master",
  "name": "v1.0.26: libusb 1.0.26",
  "draft": false,
  "prerelease": false,
  "created_at": "2022-04-10T08:57:16Z",
  "published_at": "2022-04-10T17:48:35Z",
  "assets": [
    {
      "url": "https://api.github.com/repos/libusb/libusb/releases/assets/62154429",
      "id": 62154429,
      "node_id": "RA_kwDOAOa5JM4DtGa9",
      "name": "Do.not.use.the.tar.gz.--.please.download.the.tar.bz.--.txt",
      "label": null,
      "uploader": {
        "login": "tormodvolden",
        "id": 2403928,
        "node_id": "MDQ6VXNlcjI0MDM5Mjg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2403928?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tormodvolden",
        "html_url": "https://github.com/tormodvolden",
        "followers_url": "https://api.github.com/users/tormodvolden/followers",
        "following_url": "https://api.github.com/users/tormodvolden/following{/other_user}",
        "gists_url": "https://api.github.com/users/tormodvolden/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tormodvolden/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tormodvolden/subscriptions",
        "organizations_url": "https://api.github.com/users/tormodvolden/orgs",
        "repos_url": "https://api.github.com/users/tormodvolden/repos",
        "events_url": "https://api.github.com/users/tormodvolden/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tormodvolden/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "text/plain",
      "state": "uploaded",
      "size": 306,
      "download_count": 651,
      "created_at": "2022-04-10T19:56:20Z",
      "updated_at": "2022-04-10T19:56:21Z",
      "browser_download_url": "https://github.com/libusb/libusb/releases/download/v1.0.26/Do.not.use.the.tar.gz.--.please.download.the.tar.bz.--.txt"
    },
    {
      "url": "https://api.github.com/repos/libusb/libusb/releases/assets/62146777",
      "id": 62146777,
      "node_id": "RA_kwDOAOa5JM4DtEjZ",
      "name": "libusb-1.0.26-binaries.7z",
      "label": null,
      "uploader": {
        "login": "tormodvolden",
        "id": 2403928,
        "node_id": "MDQ6VXNlcjI0MDM5Mjg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2403928?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tormodvolden",
        "html_url": "https://github.com/tormodvolden",
        "followers_url": "https://api.github.com/users/tormodvolden/followers",
        "following_url": "https://api.github.com/users/tormodvolden/following{/other_user}",
        "gists_url": "https://api.github.com/users/tormodvolden/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tormodvolden/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tormodvolden/subscriptions",
        "organizations_url": "https://api.github.com/users/tormodvolden/orgs",
        "repos_url": "https://api.github.com/users/tormodvolden/repos",
        "events_url": "https://api.github.com/users/tormodvolden/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tormodvolden/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "application/x-7z-compressed",
      "state": "uploaded",
      "size": 3006894,
      "download_count": 7840,
      "created_at": "2022-04-10T17:46:57Z",
      "updated_at": "2022-04-10T17:46:59Z",
      "browser_download_url": "https://github.com/libusb/libusb/releases/download/v1.0.26/libusb-1.0.26-binaries.7z"
    },
    {
      "url": "https://api.github.com/repos/libusb/libusb/releases/assets/62146772",
      "id": 62146772,
      "node_id": "RA_kwDOAOa5JM4DtEjU",
      "name": "libusb-1.0.26-binaries.7z.asc",
      "label": null,
      "uploader": {
        "login": "tormodvolden",
        "id": 2403928,
        "node_id": "MDQ6VXNlcjI0MDM5Mjg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2403928?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tormodvolden",
        "html_url": "https://github.com/tormodvolden",
        "followers_url": "https://api.github.com/users/tormodvolden/followers",
        "following_url": "https://api.github.com/users/tormodvolden/following{/other_user}",
        "gists_url": "https://api.github.com/users/tormodvolden/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tormodvolden/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tormodvolden/subscriptions",
        "organizations_url": "https://api.github.com/users/tormodvolden/orgs",
        "repos_url": "https://api.github.com/users/tormodvolden/repos",
        "events_url": "https://api.github.com/users/tormodvolden/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tormodvolden/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "text/plain",
      "state": "uploaded",
      "size": 833,
      "download_count": 189,
      "created_at": "2022-04-10T17:46:49Z",
      "updated_at": "2022-04-10T17:46:50Z",
      "browser_download_url": "https://github.com/libusb/libusb/releases/download/v1.0.26/libusb-1.0.26-binaries.7z.asc"
    },
    {
      "url": "https://api.github.com/repos/libusb/libusb/releases/assets/62146796",
      "id": 62146796,
      "node_id": "RA_kwDOAOa5JM4DtEjs",
      "name": "libusb-1.0.26.tar.bz2",
      "label": null,
      "uploader": {
        "login": "tormodvolden",
        "id": 2403928,
        "node_id": "MDQ6VXNlcjI0MDM5Mjg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2403928?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tormodvolden",
        "html_url": "https://github.com/tormodvolden",
        "followers_url": "https://api.github.com/users/tormodvolden/followers",
        "following_url": "https://api.github.com/users/tormodvolden/following{/other_user}",
        "gists_url": "https://api.github.com/users/tormodvolden/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tormodvolden/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tormodvolden/subscriptions",
        "organizations_url": "https://api.github.com/users/tormodvolden/orgs",
        "repos_url": "https://api.github.com/users/tormodvolden/repos",
        "events_url": "https://api.github.com/users/tormodvolden/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tormodvolden/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "application/x-bzip",
      "state": "uploaded",
      "size": 620534,
      "download_count": 22196,
      "created_at": "2022-04-10T17:47:09Z",
      "updated_at": "2022-04-10T17:47:10Z",
      "browser_download_url": "https://github.com/libusb/libusb/releases/download/v1.0.26/libusb-1.0.26.tar.bz2"
    },
    {
      "url": "https://api.github.com/repos/libusb/libusb/releases/assets/62146789",
      "id": 62146789,
      "node_id": "RA_kwDOAOa5JM4DtEjl",
      "name": "libusb-1.0.26.tar.bz2.asc",
      "label": null,
      "uploader": {
        "login": "tormodvolden",
        "id": 2403928,
        "node_id": "MDQ6VXNlcjI0MDM5Mjg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2403928?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tormodvolden",
        "html_url": "https://github.com/tormodvolden",
        "followers_url": "https://api.github.com/users/tormodvolden/followers",
        "following_url": "https://api.github.com/users/tormodvolden/following{/other_user}",
        "gists_url": "https://api.github.com/users/tormodvolden/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tormodvolden/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tormodvolden/subscriptions",
        "organizations_url": "https://api.github.com/users/tormodvolden/orgs",
        "repos_url": "https://api.github.com/users/tormodvolden/repos",
        "events_url": "https://api.github.com/users/tormodvolden/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tormodvolden/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "text/plain",
      "state": "uploaded",
      "size": 833,
      "download_count": 187,
      "created_at": "2022-04-10T17:47:04Z",
      "updated_at": "2022-04-10T17:47:04Z",
      "browser_download_url": "https://github.com/libusb/libusb/releases/download/v1.0.26/libusb-1.0.26.tar.bz2.asc"
    }
  ],
  "tarball_url": "https://api.github.com/repos/libusb/libusb/tarball/v1.0.26",
  "zipball_url": "https://api.github.com/repos/libusb/libusb/zipball/v1.0.26",
  "body": ""
}'</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2022-05-26 12:17:22 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/2390539287">2390539287</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by MrAdityaAlok** [comment]
Maybe no github server was available to handle request at that moment.

Closing, works now.
