### ISSUE TITLE
Java on Termux

### ISSUE THREAD

**Issue by LobsterMan123** [termux/termux-packages#10828]
I've noticed there is a version of Java 9 available for Termux, but it is headless (i.e. can't save, create or manipulate images).  Is there a Termux recommended Java (that runs with actual commands like _java -cp myJar.jar package.myJar_) available that isn't headless?  Since Alpine Termux has a desktop associated with it, if I were to install it, can it run the standard java, or do I need to use the headless Java 9 even with Alpine?

**Comment by agnostic-apollo** [comment]
Termux natively only supports `java` via `openjdk-17` package.

Linux distros run with proot/chroot will have their own.

**Comment by LobsterMan123** [comment]
Would you please tell me what is/are the command(s) in order to install
Java 17 in Termux?  Thanks.

Oscar

**Comment by agnostic-apollo** [comment]
`pkg install openjdk-17`

**Comment by LobsterMan123** [comment]
Wonderfulm and I have a folliw-up question.  Do you know if this openjdk 17
is headless?  Will it lack java's awt?  I hope this is not too specific a
question.  Thanks.

Oscar
