### ISSUE TITLE
[Bug]: No Fortran compiler found error despite having libgfortran5 installed

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-packages#10823]
### Problem description

Hello, 

I'm trying to compile R 4.2.0, but when doing `./configure\` I got this error:
```
configure: error: No Fortran compiler found
```

I'm doing something wrong??

### What steps will reproduce the bug?

```
cd ~
mkdir -p $PREFIX/local/R-4.2.0
mkdir downloads
cd downloads
wget https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/base/R-4/R-4.2.0.tar.gz
tar -xzvf R-4.2.0.tar.gz
cd R-4.2.0
./configure --enable-R-shlib --prefix=$PREFIX/local/R-4.2.0
```

### What is the expected behavior?

`./configure` step should finish so we can continue with `make` and `make install`

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=320
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.kcubeterm.com/termux-main/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
Updatable packages:
All packages up to date
termux-tools version:
0.182
Android version:
12
Kernel build information:
Linux localhost 4.14.180-perf-g5d6f377 #1 SMP PREEMPT Sat Feb 26 00:53:45 CST 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2102J20SG

```

**Comment by MrAdityaAlok** [comment]
`libgfortran5` is gnu fortran runtime library and from third-party repo, so no help there.

We do not have any proper fortran compiler officially packaged. We `lfortran`, but it currently in development and doesn't support all fortran features. .

**Comment by RalfWerner** [comment]
> [Bug]: No Fortran compiler found

see: https://github.com/termux/termux-app/issues/1700#issuecomment-671289403 / https://github.com/its-pointless/its-pointless.github.io and https://github.com/termux/termux-packages/pull/9043#issuecomment-1058352949
