### ISSUE TITLE
[Package]: tini

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#10824]
### Package description

A tiny but valid `init` for containers.

### Home page URL

https://github.com/krallin/tini

### Source code URL

https://github.com/krallin/tini/releases/tag/v0.19.0

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

*This should solve several issues regarding daemons that gets killed by Android.*

**Comment by wmcbtech30** [comment]
This is good for containers and handling zombie processes, while I don't guarantee this package to be useful in some OEMs that don't have agreesive killing (even with optimizations off) and generates static binary upon packaging. thus there will be no actual uses cases if it was dynamically compiled
