### ISSUE TITLE
[Package]: Non-headless Java 9 

### ISSUE THREAD

**Issue by LobsterMan123** [termux/termux-packages#10829]
### Package description

Would you please make a non-headless version of Java 9 for Termux?  The following version of Java 9 was wonderful except that it was headless and prevented me from manipulating and programatically creating image files:

http://archive.org/download/openjdk-9-jre-headless_9.2017.8.20-1_x86_64/openjdk-9-jre-headless_9.2017.8.20-1_arm.deb

A comparable product to the above (which uses standard Java compiler) which includes Java image/figure processing capabilities (i.e. awt) would be wonderful.  Thanks.

### Source code URL

http://archive.org/download/openjdk-9-jre-headless_9.2017.8.20-1_x86_64/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by MrAdityaAlok** [comment]
We already have `openjdk-17`. Also, we cannot/will not provide multiple versions of same package. (Due to less disk space)

**Comment by LobsterMan123** [comment]
Would you please tell me if the jdk-17 that you do currently have if it has
awt to generate and work with boxes and figures?  Thanks.

Oscar
