### ISSUE TITLE
packages-cf.termux.org down

### ISSUE THREAD

**Issue by joshuafvr** [termux/termux-packages#10834]
If you are on android < 7 then you need to go for one of the android-5 apks from CI build: https://github.com/termux/termux-app/actions/runs/2373736679

_Originally posted by @Grimler91 in https://github.com/termux/termux-app/issues/2790#issuecomment-1135944954_

**Comment by joshuafvr** [comment]
![Screenshot_2022-05-28-02-13-06](https://user-images.githubusercontent.com/74902842/170804126-8b6685ce-3e81-403e-a7a1-8fddafac1489.png)
After successful installation any command I input keeps failing why??😔😔

**Comment by 2096779623** [comment]
Mirror is syncing?
Replacing sources with `termux-change-repo`.

**Comment by agnostic-apollo** [comment]
Thanks for the report. It seems that redirection of https://termux.org to https://termux.dev done by @Grimler91 few hours ago is also redirecting https://packages-cf.termux.org to  https://termux.dev.  Even android `7+` is affected. Only @Grimler91 can fix it, wait for him.

**Comment by joshuafvr** [comment]
> Use `termux-change-repo` to change source.

Ok

**Comment by joshuafvr** [comment]
> Thanks for the report. It seems that redirection of https://termux.org to https://termux.dev done by @Grimler91 few hours ago is also redirecting https://packages-cf.termux.org to https://termux.dev. Even android `7+` is affected. Only @Grimler91 can fix it, wait for him.

Ok boss I will

**Comment by Grimler91** [comment]
Should be fixed now, sorry for the mess!

**Comment by thunder-coding** [comment]
> Should be fixed now, sorry for the mess!

Thanks for fixing it. Maybe from next time consider notifying us in Gitter termux/dev when tinkering the DNS/CNAME configs

**Comment by Grimler91** [comment]
Yepp, that is a good idea

**Comment by joshuafvr** [comment]
> Yepp, that is a good idea

Where can I get my personal token

**Comment by joshuafvr** [comment]
![Uploading Screenshot_2022-05-28-08-31-22.png…]()
