### ISSUE TITLE
[Package]: chicken (A practical and portable scheme system)

### ISSUE THREAD

**Issue by vyuh** [termux/termux-packages#10845]
### Package description

CHICKEN is a compiler for the Scheme programming language. It produces portable and efficient C and supports the R5RS and R7RS (work in progress) standards, and many extensions. It runs on Linux, OS X, Windows, many Unix flavours, and aims to be...

- Free: Distributed free for use and modification under the BSD License (freedom to user and developer).
Simple
- Lightweight on dependencies (a C toolchain and GNU Make) and easy to install.
- Portable: Runs on many platforms, including x86, x86-64, ARM, MIPS, SPARC64 and PowerPC.
- Extensible: Many libraries and extensions are available at Eggs Unlimited and new ones can be easily created.
- Well documented: Wiki, Manual and API reference provide updated and detailed documentation about CHICKEN use.
- Actively supported: Mailing lists and an IRC channel (#chicken on Libera.Chat) for useful and kind support.

### Home page URL

https://www.call-cc.org/

### Source code URL

https://code.call-cc.org/releases/5.3.0/chicken-5.3.0.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

This compiled and installed on my termux device with the command `make PLATFORM=android PREFIX=$HOME/PREFIX/chicken-5.2.0 install`. It works well.

Other details about build process can be found in in the README file's Installation section. See: https://code.call-cc.org/cgi-bin/gitweb.cgi?p=chicken-core.git;a=blob_plain;f=README;h=1f2302753f827e5893ada45cb9ff0f2d1991f7c1;hb=e31bbee51ae2b892d624ad2736c624111c15ca9c

**Comment by vyuh** [comment]
@MrAdityaAlok Hi. When will this start showing in `pkg search chicken` or `apt search chicken` command in Termux?

**Comment by MrAdityaAlok** [comment]
> @MrAdityaAlok Hi. When will this start showing in `pkg search chicken` or `apt search chicken` command in Termux?

It is available immediately in Main (https://packages-cf.termux.org) and @Grimler91(https://grimler.se) repo, mirrors might take same time (depends upon there sync interval).
