### ISSUE TITLE
[Package]: stairspeedtest-reborn

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#10847]
### Package description

Proxy performance batch tester based on Shadowsocks(R) and V2Ray.

### Source code URL

https://github.com/tindy2013/stairspeedtest-reborn/archive/refs/tags/v0.7.1.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

require:  
* curl
* openssl
* PNGwriter
* libpng
* freetype
* zlib
* yaml-cpp
* libevent 
* pcre2
* rapidjson
* shadowsocks-libev (need to build)
* shadowsocksr-libev ('ss-local' installed as the name 'ssr-local') (need to build)
* v2ray-core
* trojan (need to build)

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last commit was 2 years ago so I consider this project is dead/frozen.
