### ISSUE TITLE
[Bug]: Package conflict termux-tools, libnotify

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#10841]
### Problem description

`pkg up` tells me that I may upgrade `termux-tools`. But when I do that, error:

```
Preparing to unpack .../termux-tools_0.183_all.deb ...
Unpacking termux-tools (0.183) over (0.182) ...
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/termux-tools_0.183_all.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/bin/notify-send', which is also in package libnotify 0.7.9-13
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/termux-tools_0.183_all.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

I have seen this sort of message before, very rarely.

I cannot easily remove `libnotify` as it is a dependency for `xfce4`, which is critical for my installation.

### What steps will reproduce the bug?

`pkg up` repeated, same problem.

### What is the expected behavior?

If `libnotify` is the same version, I expect that it will be ignored. If upgrade, upgrade. If downgrade, ignore.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
termux-tools/stable 0.183 all [upgradable from: 0.182]
termux-tools version:
0.182
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22626479 #1 SMP PREEMPT Wed Feb 16 19:15:27 +07 2022 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T510
```

**Comment by agnostic-apollo** [comment]
Caused by #10831 implemented by @pvonmoradi

**Comment by wmcbtech30** [comment]
I think the best way of solving this is either renaming the wrapper script of `notify-send` to `termux-notify-send` or something else or replace `notify-send` binary from `libnotify` to termux's one just to satisfy dependency but all notifications would go to Android and requires the user to install Termux:API or revert the commit

**Comment by pvonmoradi** [comment]
Or we can move the wrapper script to a separate package in conflict with either or X or `libnotify` so the user has to decide which one to use.

**Comment by wmcbtech30** [comment]
Right. I think we can use that method of using separate packages (either termux's one or the native x11 package) on user's choice. probably the best way to solve the problem.

**Comment by pvonmoradi** [comment]
@MrAdityaAlok What do you think? Should I create a repo and link to it similiar to any other package as described [here](https://github.com/termux/termux-packages/wiki/Creating-new-package)? Since the package would be a mere shell script, wouldn't it be against the project guidelines of not packaging shell/python/perl,etc scripts?

**Comment by MrAdityaAlok** [comment]
> Should I create a repo and link to it similiar to any other package as described [here](https://github.com/termux/termux-packages/wiki/Creating-new-package)?

Please do it. We can make an exception.

Also, tag versions. But set `TERMUX_PKG_AUTO_UPDATE=false` for security reasons. We should not update scripts without review.

PS: I have plans to replace script with a `c` (or any other compiled language) program, so this exception won't last long.
