### ISSUE TITLE
I cant install node js

### ISSUE THREAD

**Issue by Aik-202** [termux/termux-packages#10858]
### Problem description

I tried install node js, anytime I try installing it I get this error:
Setting up nodejs-lts (16.15.0) ...
CANNOT LINK EXECUTABLE "node": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/node"...
dpkg: error processing package nodejs-lts (--configure):
 installed nodejs-lts package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs-lts
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

### What steps will reproduce the bug?

Installing node js
Pkg install nodejs

### System information

termux-info:

```

```
Setting up nodejs-lts (16.15.0) ...
CANNOT LINK EXECUTABLE "node": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/node"...
dpkg: error processing package nodejs-lts (--configure):
 installed nodejs-lts package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs-lts
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by Grimler91** [comment]
upgrade your packages, `pkg upgrade`
