### ISSUE TITLE
[Package]: tageditor

### ISSUE THREAD

**Issue by GUUser91** [termux/termux-packages#10850]
### Package description

Audio tag editor

### Home page URL

https://github.com/Martchus/tageditor

### Source code URL

https://github.com/Martchus/tageditor

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by GUUser91** [comment]
@rallg

The kid3-cli program is not good with using certain characters in the tags. For example if you tag song titles containing pipe characters like the song called | solar stasis | by the artist sevenism, then the song title is converted into a blank space. Another example is if you use emojis and different font text like 𝐀𝐦𝐞 in the tags, they get converted into asian characters. So if you use a scrobbler, these songs either get scobbled as blank or have asian characters in the titles.

tageditor by Martchus doesn't have this problem.

**Comment by rallg** [comment]
@GUUser91 

Well then, ignore my comment. It just shows how old I am (nine years older than Madonna). Pipes and emojis in song titles?!
