### ISSUE TITLE
[Bug]: Icons not working well for terminal and nvim lualine

### ISSUE THREAD

**Issue by The-knd** [termux/termux-packages#10864]
### Problem description

I apologize in advance if this is not the place to ask about this type of problem.

After Downloading ```Hack``` font from ```https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip``` the reloaded the app. it seem that the font is applied but the icons are missing.

![Screenshot_20220530-183424](https://user-images.githubusercontent.com/91854421/171069910-1ab0e44d-d66f-445f-b503-7fee02509379.png)

![Screenshot_20220530-183646](https://user-images.githubusercontent.com/91854421/171069931-2b4b00f3-d9ac-4b3c-8b1d-edf193f3444c.png)

### What steps will reproduce the bug?

I start with a fresh install of Termux, then run ```pkg update && pkg upgrade```.

```pkg install```:
build-essential
tree
lsd
git
neovim
python
nodejs

Install ```packer.nvim```, download an putting ```Hack``` font in ```~/.termux/``` as ```font.ttf```.

The config of neovim ```https://github.com/The-knd/base-nvim-termux```

### What is the expected behavior?

Something like this

![108650377-bd64af80-74bf-11eb-9c55-fbfc51b39fe8](https://user-images.githubusercontent.com/91854421/171068883-cf7e9886-a3bc-4db6-979d-93395398a437.png)

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=22421
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
0.184
Android version:
9
Kernel build information:
Linux localhost 3.18.120-perf-g6acc6d1e21f5 #1 SMP PREEMPT Thu Apr 16 04:52:11 CDT 2020 armv7l Android
Device manufacturer:
motorola
Device model:
moto g(6)
```

**Comment by wmcbtech30** [comment]
Try the nerd font variant of Hack font
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack

**Comment by The-knd** [comment]
I tried with ```https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf``` and then this is the result

![Screenshot_20220530-202718](https://user-images.githubusercontent.com/91854421/171075315-1c4ed90d-257a-4496-bb4d-24495a1c0a34.png)

![Screenshot_20220530-202811](https://user-images.githubusercontent.com/91854421/171075338-d79fb90f-c9a0-447d-946c-184d41c62f69.png)

**Comment by wmcbtech30** [comment]
You probably did not download the font file correctly, what command did you use to change and download font?

**Comment by The-knd** [comment]
I used ```curl -fLo 'Hack Regular Nerd Font Complete Mono.ttf' https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf``` to download it and then ```cp Hack\ Regular\ Nerd\ Font\ Complete\ Mono.ttf .termux/font.ttf```

**Comment by masrur10rahman** [comment]
Have you reloaded termux after font installation ?

**Comment by MrAdityaAlok** [comment]
> I used `curl -fLo 'Hack Regular Nerd Font Complete Mono.ttf' https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf` to download it and then `cp Hack\ Regular\ Nerd\ Font\ Complete\ Mono.ttf .termux/font.ttf`

Your url is wrong. You are downloading html file instead of ttf. First click on that file then you will get an option to download raw file. Use that url.

Here it is:
```sh
curl -Ls https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf -o font.ttf
```

**Comment by The-knd** [comment]
Thanks a lot. 💚
