### ISSUE TITLE
[Bug]: Repository is under maintenance or down

### ISSUE THREAD

**Issue by pasindu6000** [termux/termux-packages#10861]
### Problem description

Bruh pls help me get rid of this bug

### What steps will reproduce the bug?

Aaaaaaa

### What is the expected behavior?

Aaaaaaa

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
I suppose you have installed termux from google play. Install termux from f-droid or github instead (see https://github.com/termux/termux-app#Installation)
