### ISSUE TITLE
ffmpeg not redistributable

### ISSUE THREAD

**Issue by Millak** [termux/termux-packages#1087]
$ ffmpeg -L
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with Android clang version 3.8.275480 (based on LLVM 3.8.275480)
  configuration: --arch=aarch64 --as=aarch64-linux-android-clang --cc=aarch64-linux-android-clang --cxx=aarch64-linux-android-clang++ --cross-prefix=aarch64-linux-android- --disable-avdevice --disable-ffserver --disable-static --disable-symver --disable-lzma --enable-cross-compile --enable-gpl --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-libx264 --enable-libx265 --enable-libxvid --enable-libvpx --enable-nonfree --enable-openssl --enable-shared --prefix=/data/data/com.termux/files/usr --target-os=android --enable-neon
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
This version of ffmpeg has nonfree parts compiled in.
Therefore it is not legally redistributable.

I believe in order to fix this version of ffmpeg being non-free the 'enable-nonfree' and 'enable-openssl' flags need to be removed.

**Comment by fornwall** [comment]
Thanks a lot - this has been fixed in the updated version `3.3.2-1` of the ffmpeg package that is now available!

**Comment by pranavg189** [comment]
Sadly, this breaks streaming support which was present in ffmpeg which means mps-youtube will not work with termux from now on :-(

**Comment by Millak** [comment]
In guix we build it with gnutls

**Comment by pranavg189** [comment]
Yes, that is possible.  When streaming audio is played using ffmpeg, it gives following error:

[ffmpeg] https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.

So, yes, rebuilding ffmpeg with gnutls can solve this issue. :-)

**Comment by Neo-Oli** [comment]
This is pretty inconvenient for me, since I use one of my old phones exclusively as a music streaming device and now half my streams don't work anymore. :/

**Comment by its-pointless** [comment]
adding --enable-gnutls to ffmpeg build should fix that

**Comment by pranavg189** [comment]
@Neo-Oli Same for me too :-)

**Comment by fornwall** [comment]
I just pushed an updated version `3.3.2-2` that links against gnutls and should support https. Does it work ok?

**Comment by fornwall** [comment]
With [openssl likely switching to apache license in the future](https://www.openssl.org/blog/blog/2017/03/22/license/) it will hopefully be ok to build ffmpeg with openssl again - but for now I guess one has to stay with gnutls to distribute ffmpeg binaries.

**Comment by pranavg189** [comment]
@fornwall  Yes, it works. Thanks for updating the package.
