### ISSUE TITLE
[Package]: ttfautohint

### ISSUE THREAD

**Issue by j0ng4b** [termux/termux-packages#10881]
### Package description

From https://freetype.org/ttfautohint/doc/ttfautohint.html:

> ttfautohint is a library written in C that takes a TrueType font as the input, removes its bytecode instructions (if any), and returns a new font where all glyphs are bytecode hinted using the information given by FreeType’s auto-hinting module. The idea is to provide the excellent quality of the auto-hinter on platforms that don’t use FreeType.

The use case of this package is primally for build fonts from source, so would be nice if this is added.

### Home page URL

https://freetype.org/ttfautohint/

### Source code URL

https://download.savannah.gnu.org/releases/freetype/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by rallg** [comment]
Although the algorithms used by FontForge are very different from those used by ttfautohint, perhaps the existing `fontforge-gtk` program will suit your needs? It can open a TrueType font (and many other formats) and autohint.

**Comment by j0ng4b** [comment]
Sadly in this case `fontforge-gtk` can't help because I'm was trying to build [Iosevka font](https://github.com/be5invis/Iosevka) from source and it needs `ttfautohint` to build hinted fonts, but unhinted fonts works perfectly, anyway, I successfully build `ttfautohint` with:

```./configure --disable-dependency-tracking --without-qt --without-doc --enable-static --disable-shared CC=clang LD=ld.lld AR=llvm-ar RANLIB=llvm-ranlib```
