### ISSUE TITLE
emacs --daemon, åäö doesn't work

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#1088]
Running emacs in daemon mode is a nice feature in termux as it speeds up the startup of emacs. However, certain keys (both on virtual and hardware keyboard) does not work as they should.

(I haven't checked other language's special keys but I'm guessing the same problem exist in other languages)
When I run `emacs --daemon` followed by `emacsclient test` and then press å, ä or ö on my keyboard, other commands are started instead for åäö being inserted. 
For å I get "query replace: ", for ä something about ispell and ö nothing.

I have reproduced the issue on two arm devices running android 6 and android 7. 

To reproduce (if you do not have åäö on your virtual keyboard), install Swedish ("Svenska") as an input language in your device's settings and then try inserting åäö in `emacs --daemon` mode.

**Comment by Grimler91** [comment]
German's ü, ä and ö have the same problem.

**Comment by Grimler91** [comment]
`query replace` is normally reached with `alt+%` so it seems like å is mapped to that key combination in emacs --daemon mode

**Comment by Grimler91** [comment]
This is still happening with emacsclient.

**Comment by xtkoba** [comment]
Worked around by typing

```
M-x set-locale-environment RET C.UTF-8 RET
```

or equivalently by eval'ing

```elisp
(set-locale-environment "C.UTF-8")
```

There seem to be quite a few number of Q&A for this on the web, where the aforementioned workarounds are borrowed from.

Maybe we can patch Emacs to hardcode this?
