### ISSUE TITLE
link problem using radare2

### ISSUE THREAD

**Issue by dac4755** [termux/termux-packages#1089]
I think this is a problem with termux. I installed radare2 and can run it without a problem on a Pixel (android 7.1.2). When I invoke the web server interface it throws a link error for the shell:

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/sh": "/system/lib/libc.so" is 32-bit instead of 64-bit

I'm not sure why it doesn't find /system/lib64/libc.so. LD_LIBRARY_PATH is set to /data/data/com.termux/files/usr/lib/ - I tried setting that specifically adding /system/lib64 but that didn't matter.

To get this error I open Termux and run r2:
$ r2 /system/bin/ls
[0x0000b6fc]> =H
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/sh": "/system/lib/libc.so" is 32-bit instead of 64-bit
Starting http server...

**Comment by fornwall** [comment]
This seems to happen when running r2 on a binary under `/system/bin/`, but not when running on a Termux binary like `$PREFIX/bin/sh`, right?

That's a bit strange.

**Comment by fornwall** [comment]
Thanks for reporting - this has been fixed in the updated version `1.5.0-1` of the radare2 package that is now available!

**Comment by dac4755** [comment]
Thanks for the quick update!
