### ISSUE TITLE
[Package]: roguelike game ToME 2

### ISSUE THREAD

**Issue by petrmachcz** [termux/termux-packages#10904]
### Package description

ToME 2 is my favorite game. It is very sophisticated and I would like to have it in Termux.

### Source code URL

https://github.com/tome2/tome2

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by MrAdityaAlok** [comment]
https://github.com/termux/termux-packages/pull/10923#issuecomment-1149448967
