### ISSUE TITLE
Clang++ linker error in termux 

### ISSUE THREAD

**Issue by HarshSharma-0** [termux/termux-packages#10901]
Output of clang++
~ $ clang++ c.out  -o hello -v
clang version 14.0.4
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
 "/data/data/com.termux/files/usr/bin/ld.lld" --sysroot=/data/data/com.termux/files -pie -EL --fix-cortex-a53-843419 --warn-shared-textrel -z now -z relro -z max-page-size=4096 --hash-style=gnu --enable-new-dtags -rpath=/data/data/com.termux/files/usr/lib --eh-frame-hdr -m aarch64linux -dynamic-linker /system/bin/linker64 -o hello /data/data/com.termux/files/usr/lib/crtbegin_dynamic.o -L/data/data/com.termux/files/usr/lib -L/system/lib64 c.out -lc++_shared /data/data/com.termux/files/usr/lib/clang/14.0.4/lib/linux/libclang_rt.builtins-aarch64-android.a -l:libunwind.a -ldl -lm -lc /data/data/com.termux/files/usr/lib/clang/14.0.4/lib/linux/libclang_rt.builtins-aarch64-android.a -l:libunwind.a -ldl /data/data/com.termux/files/usr/lib/crtend_android.o
ld.lld: error: c.out:2: unknown directive: using
>>> using namespace std;
>>> ^
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)

How can i solve this??

**Comment by Grimler91** [comment]
Fix your code I guess. You haven't shared what c.out contains and/or how it was created so hard to help

**Comment by HarshSharma-0** [comment]
#include<iostream>
using namespace std;

int main(){
std::cout<<"hello";
return 0;
}

This is the program i have written

**Comment by HarshSharma-0** [comment]
>>>#include<iostream>
using namespace std;

int main(){
std::cout<<"hello";
return 0;
}

The code i have written

**Comment by HarshSharma-0** [comment]
> Fix your code I guess. You haven't shared what c.out contains and/or how it was created so hard to help

>>>#include<iostream>
using namespace std;
int main(){
std::cout<<"hello";
return 0;
}

The code i have written. here in comment  'iostream'  is not showing but i have included it.

**Comment by thunder-coding** [comment]
Rename your file from `c.out` to some other with an extension that is used with C++ files like `file.cpp` or `file.cc`. clang in the above assumes your file to be a object file and hence just runs the linker. **Not a Termux bug neither a bug in LLVM. You need to learn how to properly invoke compiler commands**
