### ISSUE TITLE
I'm not able to install zphisher

### ISSUE THREAD

**Issue by Munassae1234** [termux/termux-packages#10905]
$ git clone https://github.com/htr-tech/zphisher.git
Cloning into 'zphisher'...
remote: Enumerating objects: 1490, done.
Receiving objects:   1% (19/1490), 12.01 KiB | 2.0Receiving objects:   2% (30/1490), 12.01 KiB | 2.0Receiving objects:   2% (36/1490), 20.01 KiB | 5.0Receiving objects:   3% (45/1490), 20.01 KiB | 5.0Receiving objects:   3% (55/1490), 28.01 KiB | 6.0Receiving objects:   4% (60/1490), 28.01 KiB | 6.0Receiving objects:   5% (75/1490), 28.01 KiB | 6.0Receiving objects:   5% (77/1490), 36.01 KiB | 6.0Receiving objects:   6% (90/1490), 36.01 KiB | 6.0error: RPC failed; curl 56 OpenSSL SSL_read: Software caused connection abort, errno 103
error: 8118 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by Grimler91** [comment]
Fix your internet connection I guess, not a termux problem
