### ISSUE TITLE
[Bug]: termux is not installing bootstrap because of  termux.net/bootstrap host is not working

### ISSUE THREAD

**Issue by tanveer188** [termux/termux-packages#10924]
### Problem description

 **i just install termux on my samsung j2 having android 5 when i open it . it will not installing bootstrap pkg and after that i check the same issue on git hub but solutions not work**

### What steps will reproduce the bug?

just by opening bootstrap 
actual termux.net website is not opening

### What is the expected behavior?

termux will install bootstrap

### System information

termux-info
not working
hel}
....
even app is not opening
help
help help
....
please help
not opening

**Comment by MrAdityaAlok** [comment]
Have you installed from playstore? Please install from [f-droid](https://f-droid.org/en/packages/com.termux/), playstore builds are deprecated.

**Comment by Grimler91** [comment]
This seem to be on android-5 though, for that see https://github.com/termux/termux-app/wiki/Termux-on-android-5-or-6

**Comment by MrAdityaAlok** [comment]
> This seem to be on android-5 though, for that see https://github.com/termux/termux-app/wiki/Termux-on-android-5-or-6

Ahh..missed that. Thanks!

**Comment by Mnkgoeng45** [comment]
I just installed termix on my samsung j2 core amd its not opening
