### ISSUE TITLE
[Package]: ciso

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#10937]
### Package description

PSP ISO compression tool.

Would be useful for people using the PPSSPP emulator to compress their games.

### Source code URL

https://github.com/jamie/ciso

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Compiles successfully with no issues, I tried to package this in #10936 but failed miserably because I'm still not used to the termux build system so I'll let someone else handle it.

**Comment by alexmyczko** [comment]
Please tell us where you have 1.0.2 from, or fix your version number! https://repology.org/project/ciso/versions

**Comment by TomJo2000** [comment]
> Please tell us where you have 1.0.2 from, or fix your version number! https://repology.org/project/ciso/versions

Version 1.0.2, pulled directly from the releases section of the repository.
https://github.com/jamie/ciso/releases/v1.0.2

This appears to be the latest (feature) commit.

**Comment by alexmyczko** [comment]
so sorry, am blind

**Comment by TomJo2000** [comment]
No worries
