### ISSUE TITLE
Unable to start mpd 

### ISSUE THREAD

**Issue by Xarchuser** [termux/termux-packages#1093]
I wonder if I forget to install a dependency, I don't think so... I face the following issue: 

`Starting mpd the music player daemon`
`WARNING: linker: Unsupported flags DT_FLAGS_1=0x8`
`WARNING: linker: Unsupported flags DT_FLAGS_1=0x8`
`CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "avpriv_cga_font" referenced by "libavcodec.so"...`

All the packages have been upgraded properly. What did I do wrong? Thanks.

**Comment by its-pointless** [comment]
`WARNING: linker: Unsupported flags DT_FLAGS_1=0x8`
So its a 5.1 rom i take it?
That is normal
`CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "avpriv_cga_font" referenced by "libavcodec.so"`

that is not. What is likely happening is that there is libavcodec.so from your android  rom loading before the termux one. 

To rectify could you list directory contents from /system/lib /system/vendor/lib ? 

Some roms do things do very vendor specific things that make it hard to debug. But most of the time it can be fixed.

**Comment by Xarchuser** [comment]
![screenshot_2017-06-20-14-37-03-663_com termux](https://user-images.githubusercontent.com/29339012/27347284-73350ffc-55c6-11e7-96a9-ef6671d0dc1f.png) 
It's a 5.1 rom, and yes you're right..  Could you help me fix it, I think deleting the libavcodec.so is not a good idea, (from system without root its impossible).. 
Thank you

**Comment by its-pointless** [comment]
I would never recommend removing it from rom. Its read only for a reason. 
Could you download http://its-pointless.github.io/tracefile 
chmod +x tracefile
don't use screen shots much easier to apt install pastebinit
./tracefile mpd > mpd.trace
Then 
pastebinit mpd.trace
copy the url here

**Comment by Xarchuser** [comment]
I'm sorry I'm new to the Github..... But the tracefile gives me this output : 

`Died  at ./tracefile line 18.`

**Comment by its-pointless** [comment]
install strace
apt install strace

**Comment by Xarchuser** [comment]
Ok here's the link 

> https://pastebin.com/tdSNCZ3V

**Comment by its-pointless** [comment]
okay what is happening is thatthere is an issue with preload line length. The command provided to preload libraries for  mpd is too long so it doesn't preload libraries after libavcodec.so. The symbol "avpriv_cga_font" is in our libavutil.so but it clearly loads 
`/system/lib/libavutil.so` not our libavutil
 `/data/data/com.termux/files/usr/lib/libavutil.so`

There is probably a way to get it to work for you. I will try ina few days. you could experiment removing unneded preloads in the script. just back up the mpd script in the bin dir before or you will to reinstall mpd again.

**Comment by its-pointless** [comment]
could you try 
wget https://its-pointless.github.io/ffmpeg-compat_0.1_arm.deb
dpkg -i ffmpeg-compat_0.1_arm.deb
mpd-c 
?

**Comment by Xarchuser** [comment]
Thank you very much, it worked fine for me, I tried as you said before, removing unneeded preloads in the script, but didn't work,I had suspected of the ffmpeg, because both programs use the same libs, but I didn't know how to solve, now I will configure the ncmpcpp.
