### ISSUE TITLE
Dark-phish: options 24

### ISSUE THREAD

**Issue by Gtjames777** [termux/termux-packages#10930]
### Problem description

After I install dark-phish on termux successfully, I use option '24' bitcoin after I click on the option 24 it will show ngrok server and php after that it will only show 'waiting for credentials' without going further
![Screenshot_20220608-125515](https://user-images.githubusercontent.com/107179538/172811926-aa8e8dfa-43bc-4bfb-8573-ad86f8df50d1.png)

### What steps will reproduce the bug?

After installing the dark-phish
Python3 dark-phish.py
Option 24

### What is the expected behavior?

Stranded at 'waiting for credentials' 

### System information

termux-info:
apt update

$ apt upgrade

$ apt install python3

$ apt install curl

$ apt install php

$ apt install git

$ git clone https://github.com/Cyber-Anonymous/Dark-Phish

$ pip3 install requests

$ pip3 install wget

$ cd Dark-Phish

$ python3 dark-phish.py
```

```

**Comment by 2096779623** [comment]
**https://wiki.termux.com/wiki/hacking**
