### ISSUE TITLE
new mirror adding request

### ISSUE THREAD

**Issue by CyberRex0** [termux/termux-packages#10942]
- Region: Japan
- Internet connection: 1Gbps FTTH (No transfer limited)
- Sync per 6 hours
- Supported repositories: `main`, `root`, `x11`

deb sourcelist:
```
deb https://mirrors.cbrx.io/apt/termux/termux-main main stable
deb https://mirrors.cbrx.io/apt/termux/termux-root root stable
deb https://mirrors.cbrx.io/apt/termux/termux-x11 x11 stable
```

Since my home internet uses IPoE, I cannot use the HTTP(S) port with IPv4.
Therefore, Cloudflare is used in between to convert from IPv6 to v4.
I hope you will add Termux mirror in Japan, as it does not yet exist.
Thank you in advance.

**Comment by 2096779623** [comment]
@Grimler91

**Comment by Grimler91** [comment]
Great, thanks!
