### ISSUE TITLE
[Package]: mercurial

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#10946]
### Package description

Mercurial is a free, distributed source control management tool. It efficiently handles projects of any size and offers an easy and intuitive interface.

### Home page URL

https://www.mercurial-scm.org/

### Source code URL

https://www.mercurial-scm.org/release/tortoisehg/targz/tortoisehg-6.1.3.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by licy183** [comment]
Actually it can be installed using `pip install mercurial`, so I don't think it is necessary to be added in the main repo.

**Comment by 2096779623** [comment]
> Actually it can be installed using `pip install mercurial`, so I don't think it is necessary to be added in the main repo.

idk,thanks!

**Comment by theamericanaccount** [comment]
@2096779623 if you want to handle mercurial as a normal package and not through pip, given you are using the pacman based environment, an universal build recipe is available at [mercurial-ur](https://github.com/themartiancompany/mercurial-ur) and a binary armv7l package has been published on the [fur](https://github.com/themartiancompany/fur).

**Comment by TomJo2000** [comment]
> given you are using the pacman based environment, an universal build recipe is available at [mercurial-ur](https://github.com/themartiancompany/mercurial-ur)

This looks to be an [AUR](https://aur.archlinux.org/) package build.
Our environment is also not exactly `pacman` based.
We offer both Apt and Pacman as package management options, but this does not make Termux compatible with AUR package builds.

> and a binary armv7l package has been published on the [fur](https://github.com/themartiancompany/fur).

Unfortunately we cannot utilize pre-built binaries as they are not compiled against the prefix used by Termux.
Compiling mercurial from the upstream makefile shouldn't be a major issue though.

I'm not sure to what degree a "native" Termux package for mercurial is necessary, or adds anything if it installs fine through pip.

**Comment by theamericanaccount** [comment]
I know your environment quite well.

I have de facto made AUR packages compatible with termux, months ago, through a makepkg extension called reallymakepkg](https://github.com/themartiancompany/reallymakepkg) and unifying recipes sources for GNU, Termux, and Msyn2/MinGW into a new decentralized incensorable repo called the Ur.

Its binary fallback, the fur, hosts binary packages compatible with termux.

Over 500 source packages are already confirmed compatible, the general intent is to stop all of this useless duplication of work.

I am actually extending all of archlinux sources compatible with termux with the intent of making apparent how both archlinux and termux team are acting against everybody interest by working separately.

**Comment by theamericanaccount** [comment]
@tomJo
for example [this is the unified build recipe http mirror repository for `nspr`](https://github.com/themartiancompany/nspr-ur), which when built with `reallymakepkg`, it will generate a working package on both arch and termux.

I'll tell you one of the very few things termux packages usually need adjustments for are related to the fact somehow termux has chosen to follow debian nomenclature without adding provides and arch linux simply do not care to add provides for debian nomenclature.

Overall considering how, why and with what kind of general indifference I have then been thrown out from arch after 15 years, I would tell you to immediately stop trusting any work group which sets up its project as a big silo and is able to easily remove you from between your own work and your own users.

In this regard termux and github do not fare pretty well, but actually this is a general issue you can find almost everywhere in the 'free as in freedom' space.
How can I say, start assuming anybody could be a paid agent charged with keeping your work only accessible to a very selected niche.
