### ISSUE TITLE
php iconv not working

### ISSUE THREAD

**Issue by whoisterencelee** [termux/termux-packages#1095]
Seems iconv is not working on PHP, try:

<?php
   iconv('' , '//IGNORE', '')
?>

is this because libiconv is replaced by libandroid-support?

**Comment by fornwall** [comment]
Could you update the snippet to try out (seems to have been lost in formatting)?

**Comment by whoisterencelee** [comment]
Oops, I forgot to put in quotes.  Here it is:

`<?php
iconv( '', '//IGNORE', '')
?>`

**Comment by whoisterencelee** [comment]
OK, just narrowed it down.

I just tried the following and it worked, so I guess //IGNORE or //TRANSLIT is not supported by libandroid's implementation of iconv.

`<?php
   $test = iconv( 'UTF-8', 'ISO-8859-1', '')
 ?>`

According to [php iconv function](http://php.net/manual/en/function.iconv.php)  this is required and I found it in Roundcube's rcube_charset.php which is called pretty much used everywhere.

**Comment by whoisterencelee** [comment]
Seems roundcube can also use mbstring, in that case, let's not brother with fixing iconv.  Just need these to return false, in which case roundcube will not use these options.

iconv( '', '//IGNORE', '')
iconv( '', '//TRANSLIT', '')

Actually, any unknown charmaps should return false.

**Comment by its-pointless** [comment]
Yeah iv also run into limitations of libandroids implimentation of iconv when compiling R. I believe libandroid uses musl libc implimentation of iconv

**Comment by vishalbiswas** [comment]
@its-pointless everything in libandroid-support is from musl

**Comment by xeffyr** [comment]
Closing since should be fixed.

Sample from https://github.com/termux/termux-packages/issues/1095#issuecomment-309789405 does not produce errors:
```
[~]:$ cat test1.php
<?php $test = iconv( '', '//IGNORE', '') ?>
[~]:$ php test1.php
[~]:$
```

Conversion seems working too:
```
[~]:$ cat test2.php 
<?php
  echo 'Original: €', PHP_EOL;
  echo 'TRANSLIT: ', iconv("UTF-8", "ISO-8859-1//TRANSLIT", '€'), PHP_EOL;
  echo 'IGNORE: ', iconv("UTF-8", "ISO-8859-1//IGNORE", '€'), PHP_EOL;
?>
[~]:$ php test2.php
Original: €
TRANSLIT: EUR
IGNORE: 
[~]:$
```
