### ISSUE TITLE
[Pacman]: package dependencies

### ISSUE THREAD

**Issue by Sarisan** [termux/termux-packages#10951]
### Problem description

apt optionally depends on x11-repo that cannot be installed with pacman. I guess there may be other packages that depend on x11-repo or root-repo

### What steps will reproduce the bug?

Run `pacman -S apt`
You will see
```
Optional dependencies for apt
    gnupg [installed]
    x11-repo
```

### What is the expected behavior?

Packages installed with pacman shouldn't depend on x11-repo or root-repo

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=pacman
TERMUX_APP_PID=10800
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=pacman
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Server = https://s3.amazonaws.com/termux-main.pacman/aarch64
[x11]
Server = https://s3.amazonaws.com/termux-x11.pacman/aarch64
[root]
Server = https://s3.amazonaws.com/termux-root.pacman/aarch64
Updatable packages:
All packages up to date
termux-tools version:
0.186
Android version:
11
Kernel build information:
Linux localhost 4.14.245-QuicksilveR-ginkgo-v2.5/a2dbd412 #1 SMP PREEMPT Mon Oct 4 02:10:01 CEST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8
```

**Comment by agnostic-apollo** [comment]
Not sure why its in `TERMUX_PKG_SUGGESTS`. I guess can be removed.

https://github.com/termux/termux-packages/blob/3ee0b7b09d27fec0292b2cf315e1c6bd38b2bcfb/packages/apt/build.sh#L14

https://github.com/termux/termux-packages/commit/7e6a37fe#diff-01d0f209c1e3382bf322db95a81b617fe9615609059fed8008f35a58249acb21
