### ISSUE TITLE
[Bug]: Update to LLVM 14.0.4 broke rust package 

### ISSUE THREAD

**Issue by aemmitt-ns** [termux/termux-packages#10958]
### Problem description

Update to LLVM 14.0.4 broke rust package as rustc 1.61.0 is on LLVM 14.0.3 

```
$ rustc -vV
rustc 1.61.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: aarch64-linux-android
release: 1.61.0
LLVM version: 14.0.3
```

### What steps will reproduce the bug?

1. `pkg install rust`
2. attempt to build anything
3. get error `CANNOT LINK EXECUTABLE "rustc": library "libLLVM-14.so" not found`

### What is the expected behavior?

Build succeeds, it succeeded previously until i updated the rust package from 1.56 to the current version 1.61 

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_VERSION=0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.kcubeterm.com/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
0.186
Android version:
12
Kernel build information:
Linux localhost 5.4.147-qgki-24105351-abG998USQU5CVE8 #1 SMP PREEMPT Sat May 21 13:22:41 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G998U
```

**Comment by sk0kanik** [comment]
Maybe you upgrade rust, without upgrading libllvm. It is recommended to upgrade all packages using ``pkg up``.

**Comment by aemmitt-ns** [comment]
i updated both. it turned out to be some cache issue though. it still isnt building but for separate issues now. gonna close thanks

**Comment by buttaface** [comment]
LLVM 14.0.4 is supposed to be binary-compatible with 14.0.3, so Rust should keep working when LLVM is updated. If that aspect is causing any problem, let us know.
