### ISSUE TITLE
Neovim remote netrw

### ISSUE THREAD

**Issue by ExarchD** [termux/termux-packages#1096]
I see an issue when trying to open remote files with neovim with the lastest package. 
`Error detected while processing function provider#clipboard#Executable:`
`line   52:`
`E580:  :endif without :if:   endif`

Continuing past this error are a bunch more. Ultimately the remote file loads successfully.
The same error doesn't exist with the same vimrc in vim, so I doubt its my config. 
It looks like the master was recently pulled from the git repo, so maybe the latest version had an issue?

**Comment by fornwall** [comment]
Thanks a lot for reporting! It was an error introduced in the latest package update, but now fixed in version `0.2.1~20170620` that is now available as an update.
