### ISSUE TITLE
[Package]: telegram-bot-api

### ISSUE THREAD

**Issue by Sarisan** [termux/termux-packages#10989]
### Package description

Telegram Bot API server

### Home page URL

https://core.telegram.org/bots

### Source code URL

https://github.com/tdlib/telegram-bot-api

### Packaging policy acknowledgement

- [x] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

```
cmake -S telegram-bot-api -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH="$pkgdir$prefix"
cmake --build build --target install
```

**Comment by rom38** [comment]
pkg install telegram-bot-api

**Comment by rom38** [comment]
![изображение](https://user-images.githubusercontent.com/7855190/175256283-be9e581c-d832-4a9a-9049-32ac0772222a.png)
