### ISSUE TITLE
Termux Hangs in Processing

### ISSUE THREAD

**Issue by NimaDolatabadi** [termux/termux-packages#10985]
I have a software completely compiled and defined inside bashrc
This software is a command line based and when i'm running it feels kinda stuck,
It has to go to the next line and show:
SAC>
and there i can type my commands.
But it feels kinda stuck..
I hope you can help me!
Regards.
Nima

![Screenshot_20220615-130618.png](https://user-images.githubusercontent.com/32169409/173783304-b9b5b823-144b-4243-aade-5758f37f5cd3.png)

**Comment by Grimler91** [comment]
Most likely a problem with the program you are running. 

Since we don't have access to the program and you haven't linked to the source code or told us how you configured and compiled it, there's not really anything for us to do here
