### ISSUE TITLE
Error scraping number with termux

### ISSUE THREAD

**Issue by LARBY06** [termux/termux-packages#10994]
I am unable to scrap member with your tut of termux, I downloaded from f droid and still the background was different from what I have in your video 
![2F95D24C-DC9D-45C1-AAD5-D889B370479B](https://user-images.githubusercontent.com/107110793/173965094-623eea9e-f3b9-4086-b960-5962c6ba8dd1.jpeg)
 So when I get to TELEGRAM SCRAPER ADDER $Is it keeps telling me no command is found 
![0EC1DA5B-BE3A-43F7-8F3B-AD54B4136B7D](https://user-images.githubusercontent.com/107110793/173965228-6f2ed413-8d40-44fe-913d-09d5f6e5645e.jpeg) and lastly when I get to select group you want to scrap member from, it won’t proceed because it not enabling me scrap number it keep bringing errors

**Comment by Grimler91** [comment]
github.com/termuxprofessor has nothing to do with us

**Comment by LARBY06** [comment]
What is your recommended way or site, how do I get off there pls it’s important.

**Comment by Grimler91** [comment]
Termux does not have tutorials or a recommended way to scrape telegram. You are on your own.
