### ISSUE TITLE
emacs crashes on startup

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#11]
Emacs seems to crash on startup a lot.

One working configuration is Android 5.1 with more columns than 72.

**Comment by bet** [comment]
Android 6.0 works with my phone landscape, too, hangs buzzing with it portrait. Nexus 5 stock Marshmallow.

**Comment by jasalt** [comment]
I'm hoping for a mg (micro emacs) package meanwhile this is broken.

**Comment by timoc** [comment]
i have this same issue with crashing emacs. i would prefer jasspa though, as it has much better support for macros etc.

**Comment by bet** [comment]
I'm using zile, it doesn't cover the range of functions as gnu emacs, but, like my personal favourite jove, it's closer in weight (disk and memory footprint, and cpu) to vi, while still having an emacs editing model and keybindings.

**Comment by timoc** [comment]
I saw zile in the package list. I will check it out, but jasspa has all of that that and spell checking etc.

**Comment by fornwall** [comment]
There is hope :)! I have update the emacs package to version `25.0.92`, which is a prerelease for the upcoming 25.1 version of emacs. This update, together with more patching of emacs to make it work, should lead to emacs starting up regardless of screen size - re-open this issue if it still crashes!

**Comment by bet** [comment]
First time I installed it on my Nexus 5, it crashed, whether in portrait or landscape. However, after uninstalling and reinstalling Termux from f-droid, it worked. Thanks!

**Comment by fornwall** [comment]
Yes, those whi previously installed the old version can update to the new one with `apt update && apt upgrade`.

**Comment by timoc** [comment]
Worked with an:
```
apt-get update ;  apt-get autoremove ; apt-get autoclean ; apt-get upgrade
```
