### ISSUE TITLE
packages.termux.dev has issues

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#11007]
### Discussed in https://github.com/termux/termux-packages/discussions/10976

<div type='discussions-op-text'>

<sup>Originally posted by **buttaface** June 13, 2022</sup>
It redirects to packages.termux.dev which is down. Is this planned? packages-cf.termux.dev still works.</div>

**Comment by Grimler91** [comment]
It's a problem with fosshost's ipv6 -> ipv4 proxy, similar to https://github.com/termux/termux-app/issues/2650. Has been reported to fosshost's, but haven't heard back yet

**Comment by 2096779623** [comment]
```
C:\Users\Administrator>nslookup packages.termux.org
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  fe80::1

non-authoritative answer:
Name:    packages.termux.org
Addresses:  2606:4700:3030::6815:1491
          2606:4700:3030::ac43:c121
          172.67.193.33
          104.21.20.145


C:\Users\Administrator>nslookup -type=ns packages.termux.org
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  fe80::1

termux.org
        primary name server = clark.ns.cloudflare.com
        responsible mail addr = dns.cloudflare.com
        serial  = 2280631813
        refresh = 10000 (2 hours 46 mins 40 secs)
        retry   = 2400 (40 mins)
        expire  = 604800 (7 days)
        default TTL = 3600 (1 hour)
```

In China it redirects normally to `packages.termux.dev`.

**Comment by Grimler91** [comment]
packages.termux.org, packages-cf.termux.org and packages-cf.termux.dev all goes through cloudflares proxy and works, while packages.termux.dev goes straight to fosshost which fails if you are unlucky and it resolves to 216.18.208.171 or 216.18.208.172

**Comment by 2096779623** [comment]
> @2096779623 yeah you are right, issue is only with packages.termux.dev (after we enabled proxy'ing by cloudflare I believe)
> 
> fosshost's proxy has 5 IP addresses, 216.18.208.170 - 216.18.208.174 (see `dig packages.termux.dev`). For 171 and 172 connection fails, while for the other ones it works fine:
> 
> ```
> $ curl --resolve "packages.termux.dev:80:216.18.208.171"  http://packages.termux.dev
> <html>
> <head><title>500 Internal Server Error</title></head>
> <body>
> <center><h1>500 Internal Server Error</h1></center>
> <hr><center>openresty/1.19.9.1</center>
> </body>
> </html>
> $ curl --resolve "packages.termux.dev:80:216.18.208.170"  http://packages.termux.dev
> # success
> ```

I tested `packages.termux.dev` using some site for website speed testing and found that some regions HTTP status code is 500, as you said

**Comment by agnostic-apollo** [comment]
Have pushed 3b76d37 and a3e68e2 to try to fix package upload issue.

**Comment by Grimler91** [comment]
Should probably revert my [attempt to fix it](https://github.com/termux/termux-packages/commit/1615ccc894cff648b96e617039a8a1e7921cea96) then ;)

**Comment by agnostic-apollo** [comment]
I am probably starting to go blind I guess ;)

**Comment by Grimler91** [comment]
Ooor I should communicate more :)

**Comment by agnostic-apollo** [comment]
Lolz.

Why did you revert bc9834df in d090e2139 instead of 1615ccc8?

**Comment by Grimler91** [comment]
Yeah, good question. `git log`'ed `.github/` to find my previous commit, instead of `scripts/`. I need glasses I guess

**Comment by agnostic-apollo** [comment]
Ah, thanks for fixing.

>I need glasses I guess

Well, they didn't help me ;)

**Comment by Anonymous1231-dev** [comment]
> > @2096779623 yeah you are right, issue is only with packages.termux.dev (after we enabled proxy'ing by cloudflare I believe)
> > fosshost's proxy has 5 IP addresses, 216.18.208.170 - 216.18.208.174 (see `dig packages.termux.dev`). For 171 and 172 connection fails, while for the other ones it works fine:
> > ```
> > $ curl --resolve "packages.termux.dev:80:216.18.208.171"  http://packages.termux.dev
> > <html>
> > <head><title>500 Internal Server Error</title></head>
> > <body>
> > <center><h1>500 Internal Server Error</h1></center>
> > <hr><center>openresty/1.19.9.1</center>
> > </body>
> > </html>
> > $ curl --resolve "packages.termux.dev:80:216.18.208.170"  http://packages.termux.dev
> > # success
> > ```
> 
> In fact, all four IPs(216.18.208.170 - 216.18.208.174) have issues.
> 
> I tested `packages.termux.dev` using some site for website speed testing and found that some regions HTTP status code is `500`, as you said.
> 
> Failed IP List:
> 
> 1. 216.18.208.172
>    
>    * Chengdu,Sichuan,China
>    * Taiyuan,Shanxi,China
>    * Shiyan,Hubei,China
>    * Dalian,Niaoning,China
>    * Baoding,Hebei,China
>    * Chengdu,Sichuan,China
>    * Shanghai,China
>    * Zhenzhou,Henan,China
> 2. 216.18.208.171
>    
>    * Suqian,Jiangsu,China
>    * Hohhot,Inner
>    * Mongolia,China
>    * Moldova
> 3. 216.18.208.173
>    
>    * Xian,Shanxi,China
>    * Changsha,Hunan,China
>    * XinXiang,Henan,China
>    * Beijing,China
>    * LA,America
>    * Frankfurt(AWS), Germany
>    * Malaysia
>    * Seoul, Korea
>    * Turkey
> 4. 216.18.208.170
>    
>    * Jingyang,Sichuan,China
>    * Urumqi,Xinjiang,China
> 5. 216.18.208.174
>    
>    * Shanghai,China
>    * Hangzhou,Zhejiang,China
>    * Hefei,Anhui,China
>    * Shenzhen(Aliyun),China
>    * Mumbai, India
> 
> * **List may not be complete.**

Hello, I'm actually a Malaysian. `216.18.208.171` can't load for me while port `173` got no problem

**Comment by 2096779623** [comment]
> Contributor

But the speed test website gives different results:
![image](https://user-images.githubusercontent.com/57583560/174469222-dc65d870-7c76-4aa2-bcb3-8170962c5746.png)

**Comment by Anonymous1231-dev** [comment]
I using curl... But when I use chrome, none of all working... :(

**Comment by Anonymous1231-dev** [comment]
> Maybe you're lucky! But the speed test website gives different results:
> ![image](https://user-images.githubusercontent.com/57583560/174469222-dc65d870-7c76-4aa2-bcb3-8170962c5746.png)
> 

By the way, what toll is it?

**Comment by 2096779623** [comment]
> > Maybe you're lucky! But the speed test website gives different results:
> > ![image](https://user-images.githubusercontent.com/57583560/174469222-dc65d870-7c76-4aa2-bcb3-8170962c5746.png)
> 
> By the way, what tool is it? Want to check it out

https://www.itdog.cn/http/

This website is in Chinese and needs translation.

**Comment by Anonymous1231-dev** [comment]
![Screenshot_2022_0619_151103](https://user-images.githubusercontent.com/87801676/174470023-1a7bc680-26d2-41f9-9638-805b25279065.jpg)
216.18.208.171 is dead...

**Comment by 2096779623** [comment]
> ![Screenshot_2022_0619_151103](https://user-images.githubusercontent.com/87801676/174470023-1a7bc680-26d2-41f9-9638-805b25279065.jpg) 216.18.208.171 is dead...

Maybe it's all dead..

**Comment by Anonymous1231-dev** [comment]
> > ![Screenshot_2022_0619_151103](https://user-images.githubusercontent.com/87801676/174470023-1a7bc680-26d2-41f9-9638-805b25279065.jpg) 216.18.208.171 is dead...
> 
> Maybe it's all dead..

_sad noises_

**Comment by Anonymous1231-dev** [comment]
> > ![Screenshot_2022_0619_151103](https://user-images.githubusercontent.com/87801676/174470023-1a7bc680-26d2-41f9-9638-805b25279065.jpg) 216.18.208.171 is dead...
> 
> Maybe it's all dead..

Yes, it's true...

_sad noises_

**Comment by 2096779623** [comment]
@Grimler91 `Cloudflared` package upload failed:
```shell
Checking packages.termux.dev ip access
success: 216.18.208.1[72](https://github.com/termux/termux-packages/runs/6972289827?check_suite_focus=true#step:4:73)
[18:20:45]: Failed to upload 'debs/cloudflared_2022.6.3_aarch64.deb'. Server/proxy dropped connection during upload.
[18:20:45]: Aborting any further uploads to this repo.
[18:20:45] Deleting uploads temporary directory...
[18:20:45] Warning: server returned 000 code while deleting temporary directory.
Error: Process completed with exit code 1.
```

**Comment by Grimler91** [comment]
Yeah, it fails occasionally, re-running the failed job usually works

**Comment by 2096779623** [comment]
@Grimler91 

![image](https://user-images.githubusercontent.com/57583560/174736702-9a491216-695c-4c33-9b70-b0cbc16c004c.png)

500 Internal Server Error with `packages-cf.termux.dev`, this is a problem with Cloudflare: https://lazybag.app/cloudflare-20220621/

**Comment by peerau** [comment]
This should be resolved on fosshost's side.

**Comment by agnostic-apollo** [comment]
@peerau Thanks a  lot. Seems to be working fine now. I assume it was ngninx `map` hash table size issue as per fosshostorg/aarch64@5017bab5 and fosshostorg/aarch64@9eea9541?

http://nginx.org/en/docs/http/ngx_http_map_module.html
http://nginx.org/en/docs/stream/ngx_stream_map_module.html
http://nginx.org/en/docs/hash.html

```
REPOSITORY_URL="https://packages.termux.dev"
REPOSITORY_DOMAIN="$(echo "$REPOSITORY_URL" | cut -d'/' -f3)"
for ip in $(dig -t a +short "$REPOSITORY_DOMAIN" | sed '1d'); do
    if [ $(curl -s -o /dev/null -w "%{http_code}" --resolve "$REPOSITORY_DOMAIN:80:$ip" "http://$REPOSITORY_DOMAIN") = "200" ]; then
        echo "success: $ip"
    else
        echo "failed: $ip" 
    fi
done
success: 216.18.208.171
success: 216.18.208.172
success: 216.18.208.174
success: 216.18.208.173
success: 216.18.208.170
```

**Comment by peerau** [comment]
Correct - apologies are in order, I have been sick the past few weeks and wasn't able to push it :(

**Comment by agnostic-apollo** [comment]
No apologies necessary, health should be a priority. Hopefully, you are better now :)

**Comment by Grimler91** [comment]
Great, thanks @peerau! Works in my tests as well, so I think we can close this
