### ISSUE TITLE
[Bug]: can't build package vlc on termux docker

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11018]
### Problem description

[Bug]: can't build package vlc on termux docker

[vlc-build-log.txt](https://github.com/termux/termux-packages/files/8933572/vlc-build-log.txt)

### What steps will reproduce the bug?

./build-package.sh -i vlc

### System information

termux-info:

```

```

**Comment by johndebia2022** [comment]
6 days not even a response ?? this is odd !!

**Comment by Grimler91** [comment]
Build issue most likely started after [libcaca update to 0.99.beta20](https://github.com/termux/termux-packages/commit/11b8c1f1687ce12d1ce6862fa790ea2aa6b062fc)
