### ISSUE TITLE
[Bug]: choose time space...in crackinsta

### ISSUE THREAD

**Issue by NAYAK0** [termux/termux-packages#11015]
### Problem description

In crackinsta....
In python crack.py
I wrote username.....
I wrote 1. ....at Bruce fore attack time space ....
I is not working
![IMG_20220618_165030](https://user-images.githubusercontent.com/107019758/174435345-76b7b00e-d631-4dbd-b60e-0036d48a668d.jpg)

### What steps will reproduce the bug?

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/crackinsta/crack.py", line 108, in <module>
    sess = instabrute.Login(password)
  File "/data/data/com.termux/files/home/crackinsta/crack.py", line 83, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
This is not a termux problem, and not something we'll help with.
https://wiki.termux.com/wiki/Hacking
