### ISSUE TITLE
Addind /usr/bin/env symlink

### ISSUE THREAD

**Issue by enedil** [termux/termux-packages#1101]
Hello. Afaik, a lot of well written open source software starts with `#!/usr/bin/env interpreter` shebang. Is it possible to either symlink `/usr/bin/env` to /data/data/com.termux/file/usr/env` (requires root, so optional), or (maybe better), replace all calls dynamically.

**Comment by Neo-Oli** [comment]
You can replace all calls by using "termux-chroot" which is part of the proot package. If you run `termux-chroot` directories like /bin and /usr/bin point to the right location. But filesystem calls will be significantly slower when running under termux-chroot.

**Comment by fornwall** [comment]
@enedil If you have root you can create the symlink yourself. Termux will not do that by itself to avoid messing with the system outside the app installation dir.

As @Neo-Oli says, using `termux-chroot` is another option that works also for non-root.
