### ISSUE TITLE
ssh-keygen is generating huge keys

### ISSUE THREAD

**Issue by wrsg** [termux/termux-packages#1102]
I'm on stock Android 7.1.1, running ssh-keygen and the RSA and Ed25519 keys and the sizes of these are coming out at between 400gb - 1tb for the different files.

**Comment by fornwall** [comment]
I'm unable to reproduce this. Are you using any special options when running ssh-keygen? Which CPU architecture are you running on (`uname -m`) and on which device?

Is anyone else able to reproduce the problem?

**Comment by wrsg** [comment]
Just tried again, it seems okay now. Not sure if it was the file manager I used (Mixplorer) but probably worth noting for future reference.

Nexus 6.
armv7l.

I tried it with ed25519 and the default (RSA) but it creates huge keys both times. No other options used.
Again, it's fine now.

**Comment by fornwall** [comment]
Thanks for the information! Let's close this for now and re-open if it seems to happen (with the output of `ls -lha ~/.ssh/`, to see the file sizes).

**Comment by wrsg** [comment]
So this should remain closed, but Mixplorer is definitely reporting the wrong sizes, I probably should contact the Mixplorer author.

**Comment by tinydynamite00** [comment]
@wrsg Have you tried forcing a media scan? It works a bit different on 7.0+ You can try going into Settings > Storage > Tap 'Manage Storage'.
