### ISSUE TITLE
[Bug]: How to revert root-repo packages, everything is broken.

### ISSUE THREAD

**Issue by Salim9304** [termux/termux-packages#11024]
### Problem description

"pkg update" got an error related to "root-repo".  On Github, I saw that the repository was archived and merged with the regular packages.  I did "pkg uninstall root-repo", "pkg update", "termux-change-repo".  Didn't help, any package from root-repo, like "testdisk" is missing.  pkg list installed does not see root packages, how to return?  And please update the wiki-documentation.
https://wiki.termux.com/wiki/Package_Management

### What steps will reproduce the bug?

...

### System information

termux-info:

v.018

**Comment by licy183** [comment]
Just install the `root-repo` package. `pkg install root-repo`. The repos are maintained in this git repository as mono repos but actually the packages are stored in separated apt repos.

**Comment by Salim9304** [comment]
> 

This is what I did before posting the issue.  and i got an error
`
Unpacking root-repo (2.0) ...
Setting up root-repo (2.0) ...
Downloading updated package list ...
Get:3 https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease [7397 B]
Ign:1 https://packages.termux.dev/apt/termux-root root InRelease
Hit:2 https://packages.kcubeterm.com/apt/termux-main stable InRelease
Ign:1 https://packages.termux.dev/apt/termux-root root InRelease
Ign:1 https://packages.termux.dev/apt/termux-root root InRelease
Err:1 https://packages.termux.dev/apt/termux-root root InRelease
  Could not handshake: The TLS connection was non-properly terminated. [IP: 216.18.208.171 443]
Fetched 7397 B in 11s (675 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://packages.termux.org/apt/termux-root/dists/root/InRelease  Could not handshake: The TLS connection was non-properly terminated. [IP: 216.18.208.171 443]
W: Some index files failed to download. They have been ignored, or old ones used instead
`

**Comment by licy183** [comment]
`termux-change-repo`, then change to a mirror rather than `packages(-cf).termux.org/dev`, and try `apt update && apt install root-repo`. Seems that `packages(-cf).termux.org/dev` have connection issues.

**Comment by Salim9304** [comment]
I wrote about this in my first message that everything is broken, and it doesn’t help to update or choose a mirror. 

 Please pay attention to the problem.  Currently not working.

**Comment by Grimler91** [comment]
> it doesn’t help to update or choose a mirror

You need to switch the root repo to another mirror, not just the main repo. In your mangled log output above you clearly have not switched the root repo to another mirror
