### ISSUE TITLE
Node on android 5,6

### ISSUE THREAD

**Issue by danicaStarR** [termux/termux-packages#11032]
### Feature description

Can you guys upgrade the node js package on android 5,6 (to v17) (even if only once)
**i really need it**

### Additional information

plz

**Comment by Grimler91** [comment]
There are no plans to work on/update android-5/6 packages. 

Please motivate why someone should spend time on this, and in particular why v17 (which is neither a LTS or current release), should be added. "i really need it" is not really a valid reason.

**Comment by danicaStarR** [comment]
@Grimler91 When I install linux (like Ubuntu) in termux, how does the apt in ubuntu that comes with them work?

**Comment by Grimler91** [comment]
Not sure I understand the question, it works the same as apt always does

**Comment by thunder-coding** [comment]
As @Grimler91 has noted that there is no plan to work on Android 5/6 packaging again as it will lead to maintainers having to do more work than before. If you need Node.js 17/18 you are free to build it yourself locally.

**Comment by iTzVoko** [comment]
> If you need Node.js 17/18 you are free to build it yourself locally.

Can you provide me with the step by step guide on how to build NodeJS and other packages?

I know how to build it a bit, but I want to share my build into termux-main-21 repo in grimler.se and packages.termux.dev repos.

I can use UserLAnd with NodeSource to install NodeJS-LTS easily, but I like how termux is lightweight and have less problems than others.

Thanks for helping!
