### ISSUE TITLE
[Package]: aircrack-ng

### ISSUE THREAD

**Issue by sans404-dev** [termux/termux-packages#11042]
### Package description

Release 1.7 available for aircrack-ng

### Home page URL

https://www.aircrack-ng.org/

### Source code URL

https://github.com/aircrack-ng/aircrack-ng/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

1. git clone https://github.com/aircrack-ng/aircrack-ng.git
2. bash autogen.sh
3. bash configure
4. make

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking
