### ISSUE TITLE
[Package]: Pyjion

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#11052]
### Package description

Pyjion - A JIT for Python based upon CoreCLR

### Home page URL

https://github.com/tonybaloney/Pyjion

### Source code URL

https://github.com/tonybaloney/Pyjion/archive/refs/tags/1.2.6.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

```
-- Using Python headers /data/data/com.termux/files/usr/include/python3.10
CMAKE_HOST_SYSTEM_PROCESSOR: aarch64
CMAKE_SYSTEM_PROCESSOR: aarch64
-- Enabling UNIX Patches
-- Detected CPU arch aarch64
-- Enabling ARM64
CMake Error at CMakeLists.txt:184 (message):
  Cant locate .NET 6


-- Configuring incomplete, errors occurred!
See also "/data/data/com.termux/files/home/Pyjion/CMakeFiles/CMakeOutput.log".
```

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last 1.5 years only dependabot commits/PRs were merged so I consider the project is inactive.
