### ISSUE TITLE
[Bug]: The repository deb.kcubeterm.me is under maintenance or down (wrong sources.list URL?).

### ISSUE THREAD

**Issue by BReduardokramer** [termux/termux-packages#11061]
### Problem description

I've reseted the Termux, I've tried pkg install root-repo and x11-repo and apt full-upgrade and the server deb.kcubeterm.me was in maintenance or down, so it not worked at all.

### What steps will reproduce the bug?

I've reseted the Termux, I've tried pkg install root-repo and x11-repo and apt full-upgrade and the server deb.kcubeterm.me was in maintenance or down, so it not worked at all.

It says this:
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
What the problem is that? Also I've been using Termux for a long time now, but I changed the repo to work, it should be works at all, I will contact the administrator of the site deb.kcubeterm.me (which have the error) of the repo page. 

### What is the expected behavior?

The repository should be working at all. If the solution does not work, I'll change the repository to the other one. 

### System information

termux-info:

```
Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://packages.termux.org/apt/termux-main: bad
[*] https://deb.kcubeterm.me/termux-main: ok
[*] https://termux.mentality.rip/termux-main: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://termux.librehat.com/apt/termux-main: ok
Picking mirror: https://deb.kcubeterm.me/termux-main
Get:3 https://deb.kcubeterm.me/termux-main stable InRelease [507 B]
Err:3 https://deb.kcubeterm.me/termux-main stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Ign:1 https://packages.termux.dev/apt/termux-games games InRelease
Ign:2 https://packages.termux.dev/apt/termux-science science InRelease
Ign:1 https://packages.termux.dev/apt/termux-games games InRelease
Ign:2 https://packages.termux.dev/apt/termux-science science InRelease
Ign:1 https://packages.termux.dev/apt/termux-games games InRelease
Ign:2 https://packages.termux.dev/apt/termux-science science InRelease
Err:1 https://packages.termux.dev/apt/termux-games games InRelease
  Could not handshake: The TLS connection was non-properly terminated. [IP: 216.18.208.172 443]
Err:2 https://packages.termux.dev/apt/termux-science science InRelease
  Could not handshake: The TLS connection was non-properly terminated. [IP: 216.18.208.172 443]
Reading package lists... Done
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
```

**Comment by agnostic-apollo** [comment]
Use `termux-change-repo` to switch **all** your mirrors to something other than kcubeterm and default repo and then run `pkg upgrade`.
