### ISSUE TITLE
Termux I can't use in nethunter pls help 

### ISSUE THREAD

**Issue by Hariharan4545** [termux/termux-packages#11064]
![Screenshot_2022-06-24-11-45-32-16_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/108116005/175474249-15c7f5d7-3eb7-4063-b3c4-515f0cd0a933.jpg)

Pls help way to found out this problem

**Comment by T-Dynamos** [comment]
Invalid Issue 
Might be android battery optimisation issue

**Comment by 2096779623** [comment]
Please use the issue template to submit issues.
