### ISSUE TITLE
[Bug]: building package 'outfieldr' on termux docker failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11079]
### Problem description

building package 'outfieldr' on termux docker failed
[build_log.txt](https://github.com/termux/termux-packages/files/8985137/build_log.txt)

### What steps will reproduce the bug?

start termux docker => build package 'outfieldr'

### What is the expected behavior?

build should succeed

### System information

ubuntu 21 running termux docker [latest]

**Comment by johndebia2022** [comment]
./lib/iguanaTLS/src/main.zig:1029:26: error: attempt to dereference non-pointer type 'std.rand.Random'

**Comment by licy183** [comment]
In #9137, `zig` has been upgraded to `0.9.1`. But [outfieldr](https://gitlab.com/ve-nt/outfieldr) has not bumped a version number after supporting `zig 0.9.1`. The `master` branch of `outfieldr` can be successfully built.

**Comment by Grimler91** [comment]
> I am building using termux docker 'latest' and it failed

Failed because outfieldr doesn't support zig 0.9.1. As @licy183 said it will work again when a new version of outfieldr is released.

Closing since there's no need for us to rebuild outfieldr, so let's just wait for the next release

**Comment by Grimler91** [comment]
(You can build from outfieldr master branch, or add a patch from their repo to fix the issue if you need to build it before that happens)
