### ISSUE TITLE
ecj and dx fail with "Failed to initialize runtime"

### ISSUE THREAD

**Issue by tliebeck** [termux/termux-packages#1107]
I'm unable to start ecj or dx, running latest from F-Droid (0.52), ecj/dx are up-to date.

They respond with "Failed to initialize runtime (check log for details)".  I'm not certain which log I should be checking, home directory is empty.

I've tried this on a few devices, some work, some do not.  May be a LineageOS specific issue:

So far have tested on 3 Lineage OS 7.1.2 devices (Nexus 6, Nexus 5, Samsung Note 3) and all fail with this issue.  Lineage builds are pretty up to date (no older than a week or two).

Samsung S7 Edge and PIxel C (the tablet thing)  work fine.  Both are stock, though the latter is running Android 8 preview (latest).

I did try invoking ecj as root on the Nexus 6, and it did at least start (i.e. display no-args help message).  Did not attempt to actually use it.  As root, the PATH is set to use the system's /usr/bin rather than Termux's.  

Any suggestions appreciated, and thanks for all the work on this awesome project!

**Comment by sdrausty** [comment]
Please give https://sdrausty.github.io/buildAPKs/reallyEasilyBuildAndroidAPKsonDevice a try; Let us know what you think?

**Comment by joakim-noah** [comment]
Likely same as #900.

**Comment by tliebeck** [comment]
@sdrausty That's what I'm using :)  Works great on the S7/PixelC.  No joy on the Lineage devices.

@joakim-noah Yes, this appears to be a dupe of #900, (apologies, I did search, just not for the right terms).

**Comment by sdrausty** [comment]
@tliebeck What kind of lineage devices are you using?

**Comment by tliebeck** [comment]
@sdrausty Sorry didn't see this....yes, stock Lineage root access (addonsu module).  Just tried disabling on one of them, no effect.

**Comment by Ssimplus** [comment]
I have the same problem - Lineage OS, Termux 0.53 from F-Droid on Oneplus 3T.

If you comment out the following two lines in /data/data/com.termux/files/usr/bin/dalvikvm 

export ANDROID_DATA=/data/data/com.termux/files/usr/var/android/
mkdir -p $ANDROID_DATA/dalvik-cache

then dalvikm, ecj, and dx work and you can build apks.

You can also use tsu in termux and modify the LD_LIBRARY_PATH and PATH variables to include the termux /usr/lib and /usr/bin respectively if you want to use root.

I posted more detail in #900.
