### ISSUE TITLE
[Bug]:  configure: exit 77

### ISSUE THREAD

**Issue by Xao1** [termux/termux-packages#11076]
### Problem description

Compilation package error "configure: exit 77"

### What steps will reproduce the bug?

./build-package.sh -i /home/ubuntu/termux-packages/packages/php

### System information

termux-info:

```
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='aarch64-unknown-linux-android'
target_alias=''
target_cpu='aarch64'
target_os='linux-android'
target_vendor='unknown'

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "PHP"
#define PACKAGE_TARNAME "php"
#define PACKAGE_VERSION "8.1.6"
#define PACKAGE_STRING "PHP 8.1.6"
#define PACKAGE_BUGREPORT "https://bugs.php.net"
#define PACKAGE_URL "https://www.php.net"

configure: exit 77
```

**Comment by Grimler91** [comment]
Works fine here. Doesn't seem like you are using our docker image, so maybe you haven't installed the host dependencies in [setup-ubuntu.sh](https://github.com/termux/termux-packages/blob/master/scripts/setup-ubuntu.sh)
