### ISSUE TITLE
Using travis to build PRs

### ISSUE THREAD

**Issue by stephengroat** [termux/termux-packages#1108]
I'm not saying this is 100% ready, but just an idea. Using Docker and Travis to build each package as a PR is received. I don't think that the `xargs bash -c` is ready for primetime, but it could be re-written to something much cleaner

[A travis example](https://travis-ci.org/stephengroat/termux-packages/builds/246408440)

```
language: generic
sudo: required
services:
  - docker
script:
  - mkdir debs && chmod 777 debs
  - git diff --name-only --diff-filter=AM $TRAVIS_COMMIT_RANGE | awk -F/ '{print $2}' | xargs bash -c '</dev/tty ./scripts/run-docker.sh ./build-package.sh "$@"'
```

**Comment by vishalbiswas** [comment]
@stephengroat you don't need to use docker, if you use the ubuntu image directly. Also, we can add `$HOME/.termux-build` to cache. debs folder is automatically created.
And travis-ci may not be able to build packages that take a really long time e.g. libllvm
A build matrix needs to be created to build for all arches.

**Comment by fornwall** [comment]
Travis builds would be great! We could blacklist the packages taking too much time to build to start with.

**Comment by stephengroat** [comment]
@fornwall are you looking for a `sh` script or would something like python or ruby be acceptable?

**Comment by fornwall** [comment]
@stephengroat Python or ruby would be fine!
