### ISSUE TITLE
[Bug]: txikijs build failure

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11085]
### Problem description

builder@d13baff4d445:~/termux-packages$ ./build-package.sh -i txikijs
termux - building txikijs for arch aarch64...
Downloading https://packages-cf.termux.org/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  37633      0 --:--:-- --:--:-- --:--:-- 37633
Downloading https://packages-cf.termux.org/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   3892      0 --:--:-- --:--:-- --:--:--  3892
gpg: Signature made Sun 26 Jun 2022 12:35:49 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.com>" [ultimate]
Downloading https://packages-cf.termux.org/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  36897      0 --:--:-- --:--:-- --:--:-- 36897
Downloading https://packages-cf.termux.org/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   3685      0 --:--:-- --:--:-- --:--:--     0
gpg: Signature made Sun 26 Jun 2022 08:39:34 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.com>" [ultimate]
Downloading https://packages-cf.termux.org/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  65273      0 --:--:-- --:--:-- --:--:-- 65273
Downloading https://packages-cf.termux.org/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1589      0 --:--:-- --:--:-- --:--:--  1589
gpg: Signature made Fri 24 Jun 2022 10:11:18 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.com>" [ultimate]
Downloading dependency libnghttp2@1.48.0 if necessary...
Found libnghttp2 in https://packages-cf.termux.org/apt/termux-main/dists/stable
extracting libnghttp2...
Downloading dependency ca-certificates@1:2022.04.26 if necessary...
Found ca-certificates in https://packages-cf.termux.org/apt/termux-main/dists/stable
extracting ca-certificates...
Downloading dependency ca-certificates-java@1:2022.04.26 if necessary...
Found ca-certificates-java in https://packages-cf.termux.org/apt/termux-main/dists/stable
extracting ca-certificates-java...
Downloading dependency zlib@1.2.12 if necessary...
Found zlib in https://packages-cf.termux.org/apt/termux-main/dists/stable
extracting zlib...
Downloading dependency openssl@3.0.3 if necessary...
Found openssl in https://packages-cf.termux.org/apt/termux-main/dists/stable
extracting openssl...
Downloading dependency openssl-tool@3.0.3 if necessary...
Found openssl-tool in https://packages-cf.termux.org/apt/termux-main/dists/stable
extracting openssl-tool...
Downloading dependency libssh2@1.10.0-2 if necessary...
Found libssh2 in https://packages-cf.termux.org/apt/termux-main/dists/stable
extracting libssh2...
Downloading dependency libcurl@7.83.1 if necessary...
Found libcurl in https://packages-cf.termux.org/apt/termux-main/dists/stable
extracting libcurl...
Downloading dependency curl@7.83.1 if necessary...
Found curl in https://packages-cf.termux.org/apt/termux-main/dists/stable
extracting curl...
Cloning into '/home/builder/.termux-build/txikijs/cache/tmp-checkout'...
remote: Enumerating objects: 219, done.
remote: Counting objects: 100% (219/219), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 219 (delta 23), reused 132 (delta 14), pack-reused 0
Receiving objects: 100% (219/219), 940.29 KiB | 2.83 MiB/s, done.
Resolving deltas: 100% (23/23), done.
Submodule 'deps/libuv' (https://github.com/libuv/libuv) registered for path 'deps/libuv'
Submodule 'deps/wasm3' (https://github.com/saghul/wasm3.git) registered for path 'deps/wasm3'
Cloning into '/home/builder/.termux-build/txikijs/cache/tmp-checkout/deps/libuv'...
Cloning into '/home/builder/.termux-build/txikijs/cache/tmp-checkout/deps/wasm3'...
Submodule path 'deps/libuv': checked out 'e8b7eb6908a847ffbe6ab2eec7428e43a0aa53a2'
Submodule path 'deps/wasm3': checked out '5e8638aa6ad38d7004108390bacb5dbcf0df67c4'
remote: Enumerating objects: 4272, done.
remote: Counting objects: 100% (4272/4272), done.
remote: Compressing objects: 100% (1198/1198), done.
remote: Total 4129 (delta 2951), reused 3923 (delta 2840), pack-reused 0
Receiving objects: 100% (4129/4129), 2.55 MiB | 9.86 MiB/s, done.
Resolving deltas: 100% (2951/2951), completed with 98 local objects.
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/saghul/txiki.js
 * [new tag]         v22.2.0    -> v22.2.0
 * [new tag]         v22.2.1    -> v22.2.1
 * [new tag]         v22.2.2    -> v22.2.2
 * [new tag]         v22.3.1    -> v22.3.1
 * [new tag]         v22.4.1    -> v22.4.1
M       deps/libuv
Note: switching to 'ffa4b191eeb23984d502b183a1f521be717f1eb5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at ffa4b19 vm: use a 10MB default stack size
Applying patch: CMakeLists.txt.patch.beforehostbuild
Downloading https://cmake.org/files/v3.23/cmake-3.23.2-linux-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43.8M  100 43.8M    0     0  19.5M      0  0:00:02  0:00:02 --:--:-- 19.5M
-- The C compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- No build type selected, default to Release
-- Building in Release mode
-- Building with GNU 11.2.0 on Linux-5.10.102.1-microsoft-standard-WSL2
-- C flags:
-- C Debug flags:   -g -ggdb -O0 -fno-omit-frame-pointer
-- C Release flags: -O3 -DNDEBUG -g
-- Performing Test UV_LINT_W4
-- Performing Test UV_LINT_W4 - Failed
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER_MSVC
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER_MSVC - Failed
-- Performing Test UV_LINT_NO_CONDITIONAL_CONSTANT_MSVC
-- Performing Test UV_LINT_NO_CONDITIONAL_CONSTANT_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_EMPTY_TU_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_EMPTY_TU_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_FILE_SCOPE_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_FILE_SCOPE_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_NONSTATIC_DLIMPORT_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_NONSTATIC_DLIMPORT_MSVC - Failed
-- Performing Test UV_LINT_NO_HIDES_LOCAL
-- Performing Test UV_LINT_NO_HIDES_LOCAL - Failed
-- Performing Test UV_LINT_NO_HIDES_PARAM
-- Performing Test UV_LINT_NO_HIDES_PARAM - Failed
-- Performing Test UV_LINT_NO_HIDES_GLOBAL
-- Performing Test UV_LINT_NO_HIDES_GLOBAL - Failed
-- Performing Test UV_LINT_NO_CONDITIONAL_ASSIGNMENT_MSVC
-- Performing Test UV_LINT_NO_CONDITIONAL_ASSIGNMENT_MSVC - Failed
-- Performing Test UV_LINT_NO_UNSAFE_MSVC
-- Performing Test UV_LINT_NO_UNSAFE_MSVC - Failed
-- Performing Test UV_LINT_WALL
-- Performing Test UV_LINT_WALL - Success
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER - Success
-- Performing Test UV_LINT_STRICT_PROTOTYPES
-- Performing Test UV_LINT_STRICT_PROTOTYPES - Success
-- Performing Test UV_LINT_EXTRA
-- Performing Test UV_LINT_EXTRA - Success
-- Performing Test UV_LINT_UTF8_MSVC
-- Performing Test UV_LINT_UTF8_MSVC - Failed
-- Performing Test UV_F_STRICT_ALIASING
-- Performing Test UV_F_STRICT_ALIASING - Success
-- summary of build options:
    Install prefix:  /usr/local
    Target system:   Linux
    Compiler:
      C compiler:    /usr/bin/cc (GNU)
      CFLAGS:

--   DISABLE_WASM: OFF
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
----
Generator:  Unix Makefiles
Compiler:   GNU
Build Type: Release
LTO:        ON
Flags:          -Dd_m3HasTracer -Wall -Wextra -Wparentheses -Wundef -Wpointer-arith -Wstrict-aliasing=2 -Werror=implicit-function-declaration -Wno-unused-function -Wno-unused-variable -Wno-unused-parameter -Wno-missing-field-initializers -Wjump-misses-init -Dd_m3HasWASI
Debug flags:   -g -ggdb -O0 -fno-omit-frame-pointer -ggdb -O0
Release flags: -O3 -Wfatal-errors -fomit-frame-pointer -fno-stack-check -fno-stack-protector -march=native
----
--   DISABLE_CURL: OFF
--   USE_SYSTEM_CURL: ON
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
-- Not using system Curl, using built-in curl project instead.
CMake Error at CMakeLists.txt:73 (add_subdirectory):
  The source directory

    /home/builder/.termux-build/txikijs/host-build/deps/curl

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/builder/.termux-build/txikijs/host-build/CMakeFiles/CMakeOutput.log".
See also "/home/builder/.termux-build/txikijs/host-build/CMakeFiles/CMakeError.log".
builder@d13baff4d445:~/termux-packages$

### What steps will reproduce the bug?

build package

### What is the expected behavior?

build should succeed

### System information

termux docker on ubuntu 21

**Comment by Grimler91** [comment]
Thanks for reporting, should be fixed in updated docker image when build for https://github.com/termux/termux-packages/commit/1ef9a5d5d28f8364c22ef44ffde888a78c6e9f06 finishes
