### ISSUE TITLE
[Package]: k2pdfopt latest version 

### ISSUE THREAD

**Issue by ajay9634** [termux/termux-packages#11089]
### Package description

Please update package to k2pdfopt 2.53 version because old version of K2PDFOPT is missing some features 

### Home page URL

https://www.willus.com/k2pdfopt/

### Source code URL

https://www.willus.com/k2pdfopt/src/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by ajay9634** [comment]
I didn't mention an error in this app because I thought it would fix after update but it's still remain

Issue is-
Only default mode is working perfectly with reflow text but other mode -  fitwidth, fitpage, crop etc  are not working
And This is error
FORTIFY: fseeko: null FILE*
![Screenshot_2022-07-05-11-23-06-545_com termux](https://user-images.githubusercontent.com/78233144/177259406-98d42cc2-5ec4-4892-9566-cb7dc84c1703.jpg)

Aborted

**Comment by ajay9634** [comment]
Only bin package from official website is working perfectly in Linux pc

**Comment by sylirre** [comment]
@ajay9634 `FORTIFY: fseeko: null FILE*` is a subject for new issue.
