### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Xao1** [termux/termux-packages#11083]
### Problem description

The software package cannot be compiled after the TERMUX_APP_PACKAGE value in the properties.sh file is changed

### What steps will reproduce the bug?

After modifying TERMUX_APP_PACKAGE in properties.sh

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Well what error do you get, and what does "the software package" mean? 
We can't read your mind..

**Comment by Xao1** [comment]
The package could not be built after changing the value of TERMUX_APP_PACKAGE in properties.sh

**Comment by Xao1** [comment]
Run the `./build-package.sh -i /root/termux-packages/packages/nginx `command.
Prompt error  `. /configure: error: the invalid value in --with-ld-opt="-L/data/data/com.example/files/usr/lib -Wl,-rpath=/data/data/com.example/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -landroid-glob`

**Comment by Grimler91** [comment]
Have you compiled and uploaded all nginx dependencies somewhere, and then changed repo urls in [termux_step_setup_variables.sh](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_setup_variables.sh)? 

If not then you can't use the -i flag and need to build nginx and all dependencies from source with `./build-package.sh /root/termux-packages/packages/nginx`

**Comment by Xao1** [comment]
can't use the -i flag ,It's still the same mistake

**Comment by Xao1** [comment]
If TERMUX_APP_PACKAGE is the default value, it can be built normally
,It cannot be constructed when TERMUX_APP_PACKAGE is "com.example"

**Comment by Grimler91** [comment]
Just changed TERMUX_APP_PACKAGE and built nginx without any issues.

Make sure you have a clean environment and not a mix of com.termux and com.example packages in $PREFIX (use the clean.sh script).

**Comment by Xao1** [comment]
Which operating system is used?

**Comment by Grimler91** [comment]
Our docker image: https://hub.docker.com/r/termux/package-builder/

**Comment by Xao1** [comment]
Thank you very much，The problem has been solved

**Comment by Xao1** [comment]
With clean.sh, you still can't build the package( It worked last night, but not now
