### ISSUE TITLE
[Package]: Vale

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#11084]
### Package description

A syntax-aware linter for prose built with speed and extensibility in mind.

### Home page URL

https://vale.sh

### Source code URL

https://github.com/errata-ai/vale

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Package is written in pure Go so it should be quick and easy to package like many other go packages.

**Comment by rallg** [comment]
Only 64-bit, if that makes a difference.

**Comment by ravener** [comment]
Nowhere it says it's only for 64-bits, the default binary downloads are 64-bit only but the code should still compile everywhere.
