### ISSUE TITLE
[Package]: v language

### ISSUE THREAD

**Issue by Xao1** [termux/termux-packages#11096]
### Package description

v language

### Home page URL

https://github.com/vlang/v/

### Source code URL

https://github.com/vlang/v/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
`pkg i vlang`
https://github.com/termux/termux-packages/blob/d8f95ece3640d8c49bd883ed446b0bab01f49b00/disabled-packages/vlang/build.sh
