### ISSUE TITLE
Any way to simplify paths? chroot/proot?

### ISSUE THREAD

**Issue by franciscod** [termux/termux-packages#111]
Currently package build scripts have to be use `$TERMUX_PREFIX` everywhere. 

- Any absolute path is really long, with a repeating `/data/data/com.termux/files/`. 
- `TERMUX_PREFIX` isn't available in bash (but this could be fixed easily)
- Even if the variable is available on bash, many configuration files (and some binaries) need the path  to be prefixed.

Imagine there's no prefix... :dancers: 

But, is it possible? What challenges we need to get through?

**Comment by fornwall** [comment]
I guess the current two non-root alternatives are:

1. [fakechroot](https://github.com/dex4er/fakechroot) - "fakechroot replaces some libc library functions (chroot(2), open(2), etc.) by ones that simulate the effect of being called with root privileges"
2. [proot](http://proot.me/) - "user-space implementation of chroot, mount --bind, and binfmt_misc. [..] relies on ptrace, an unprivileged system-call available in every Linux kernel."

Both of them have stubs in [disabled-packages](https://github.com/termux/termux-packages/tree/master/disabled-packages) but does not build. A first step would be to make any of these packages build, then we could try it out and make utilities for setting it up inside Termux.

**Comment by cswl** [comment]
@fornwall
Getting either fakeroot or proot to link against bionic is gonna be a tough one as both of them require glibc specific extensions.
However a static build of proot might work . Infact I tested a static arm distributed binary from http://portable.proot.me/proot-arm  and it runs..
A quick busybox setup seems to work.. though I havent tested it extensively.

![alt text] (http://i.imgur.com/1QCPDPc.jpg "screen shot")

**Comment by fornwall** [comment]
Closing this issue as there is no need to keep an open issue about fakechroot and proot - support for them will come when someone has the time to do it.
