### ISSUE TITLE
Dev info, possible urgency to switch from Google Play to F-droid.

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#11103]
I just got a message about one of my apps (Kindle). Soon, Google Play will no longer permit in-app purchases of new books. They will have to be purchased by other means, then added to the app.

Perhaps this is related to switching Termux from Google Play to F-Droid. Maybe what "might happen" is now something that "will happen." I do not know.

**Comment by agnostic-apollo** [comment]
Nothing to do with Termux.

https://arstechnica.com/gadgets/2022/05/amazon-kindle-book-purchases-are-the-next-google-play-billing-casualty/
