### ISSUE TITLE
Publish changelog in packages

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#1110]
Hello,

On Debian we can use `apt-get changelog` in order to see what has changed in a package.
It would be useful to have the same thing on Termux.

The command is already there in apt, it only needs a changelog file in `/usr/share/doc/<package-name>/changelog`.

I guess it might be too much work to write a changelog for each package manually but maybe it could be automated from commit messages?

**Comment by vishalbiswas** [comment]
many packages come with a `NEWS` or `CHANGELOG` file

**Comment by Rudloff** [comment]
I'm talking about a maintainer changelog, which is different from an upstream changelog.
It typically contains things like "Upgrade package to 1.0.2" or "Fix ARM builds".
Here is an example from Debian: http://metadata.ftp-master.debian.org/changelogs/main/p/proot/stable_changelog
