### ISSUE TITLE
[Bug]: Cant run frida without frida-server

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#11113]
### Problem description

i try run frida with ```sudo frida -p 0``` and got this error :
```
patching selinux policy
     ____
    / _  |   Frida 15.1.27 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Local System (id=local)
Attaching...                                                    
**
Frida:ERROR:../../../frida-core/src/agent-container.vala:20:frida_agent_container_create_co: assertion failed: (container.module != null)

Bail out! Frida:ERROR:../../../frida-core/src/agent-container.vala:20:frida_agent_container_create_co: assertion failed: (container.module != null)
Aborted
```
or in python
```
Python 3.10.5 (main, Jun  7 2022, 03:53:14) [Clang 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida
>>> frida.attach(0)
patching selinux policy
** 
Frida:ERROR:../../../frida-core/src/agent-container.vala:20:frida_agent_container_create_co: assertion failed: (container.module != null)

Bail out! Frida:ERROR:../../../frida-core/src/agent-container.vala:20:frida_agent_container_create_co: assertion failed: (container.module != null)
Aborted
```

### What steps will reproduce the bug?

```sudo frida -p 0``` or in python:
```
>>> import frida
>>> frida.attach(0)
```

### What is the expected behavior?

here result if i use ```sudo frida -H 127.0.0.1:27042 -p 0```:
```
patching selinux policy
     ____
    / _  |   Frida 15.1.27 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to 127.0.0.1:27042 (id=socket@127.0.0.1:27042)
Attaching...                                                                                                                    
[Remote::SystemSession ]->
```

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=31487
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://plug-mirror.rcac.purdue.edu/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.17
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Wed Sep 16 18:28:51 WIB 2020 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 6A

```

**Comment by 2096779623** [comment]
https://github.com/frida/frida-core/issues/63

**Comment by Grimler91** [comment]
Is frida-server running? (How did you start it?)
Do you get different behaviour if run from a tsu shell rather than with sudo?

**Comment by kyzsukii** [comment]
> Is frida-server running? (How did you start it?) Do you get different behaviour if run from a tsu shell rather than with sudo?
running sudo or in tsu the result remains the same

cant run

**Comment by kyzsukii** [comment]
> [frida/frida-core#63 (comment)](https://github.com/frida/frida-core/issues/63#issuecomment-276918622)

![Screenshot_2022-06-30-16-15-22-910_com termux](https://user-images.githubusercontent.com/105912131/176627848-6540d80f-935d-4ea9-902e-d6f11472a00f.jpg)

still got that error

**Comment by Grimler91** [comment]
Is `frida-server` running or not? That is, have you started `frida-server` before trying to run `frida`?

**Comment by kyzsukii** [comment]
> Is `frida-server` running or not? That is, have you started `frida-server` before trying to run `frida`?

not running.
i want run frida without frida-server but that error piss me off

**Comment by Grimler91** [comment]
And have you tried first starting `frida-server`, so that `frida` has something to connect to?

Have you tried other processes than `0`?

**Comment by kyzsukii** [comment]
already try with `frida-server` and work fine but i want to run `frida` without `frida-server` but got that error

already try another process and still got that issue

**Comment by Grimler91** [comment]
Is `frida` suppose to work without `frida-server`? Sounds weird to me, then there is nothing to connect to

**Comment by kyzsukii** [comment]
> Is `frida` suppose to work without `frida-server`? Sounds weird to me, then there is nothing to connect to

yaps just go to `/data/local/tmp` and spawn some app or process.

**Comment by kyzsukii** [comment]
like:
 ```
~$ tsu
~# cd /data/local/tmp
/data/local/tmp# frida -no-pause -f com.example.app
```

its no needed `frida-server`
but now i got error like above
