### ISSUE TITLE
[Package]: hydroxide update

### ISSUE THREAD

**Issue by julianfairfax** [termux/termux-packages#11118]
### Package description

The latest commit to hydroxide is essential update that makes it compatible with Proton's new domain. The hydroxide package should be updated to it. There is, however, no release for this new version in the upstream repo yet.

### Source code URL

https://github.com/emersion/hydroxide/commit/b11846dbb34e95bdebdfb4f928bdef23efd8dca2

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Current version is 0.2.23, which is here: https://github.com/termux/termux-packages/blob/master/packages/hydroxide/build.sh

**Comment by julianfairfax** [comment]
> Do you know if the developers are planning to tag a release anytime soon?

No i don't know.

**Comment by MrAdityaAlok** [comment]
We won't update until upstream creates a release.
