### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Zusyaku** [termux/termux-packages#11116]
### Problem description

i have a problem with termux mirror packages ... some termux packages are incomplete on some mirrors...i installed pkg install tigervnc (ustc mirror example) it can't be installed and i tried in another mirror it works

### What steps will reproduce the bug?

just tell me best mirror in asia and have all packages

### System information

termux-info:

```

```

**Comment by Maxython** [comment]
Can you send a screenshot of the error when installing on this mirror?

**Comment by 2096779623** [comment]
> i have a problem with termux mirror packages ... some termux packages are incomplete on some mirrors...i installed pkg install tigervnc (ustc mirror example)

![Screenshot_20220630-221409](https://user-images.githubusercontent.com/57583560/176700235-98b44769-b471-42d5-9ca2-41b0e5e9d343.png)

ustc mirror is available, installing `tigervnc` requires installing `x11-repo`.
