### ISSUE TITLE
inetutils logger doesn't write to syslog

### ISSUE THREAD

**Issue by wryun** [termux/termux-packages#1112]
It doesn't appear to use openlog/syslog/closelog and attempts to write to /dev/log or sockets directly, none of which work on normal android (which I think needs to end up calling __android_log_print). Not an easy fix, I guess...

**Comment by fornwall** [comment]
There is a native android logging utility at `/system/bin/log`:

```sh
$ /system/bin/log
USAGE: /system/bin/log [-p priorityChar] [-t tag] message
	priorityChar should be one of:
		v,d,i,w,e
```

I'm thinking of removing logger from inetutils and point at that one instead, would that work for you (or would you like logger for compatibility with existing scripts)?

**Comment by sdrausty** [comment]
I'm wondering why /system/bin/ isn't somewhere in $PATH anyway?

Using `/system/bin/log` seems to be an ideal solution @fornwall

**Comment by wryun** [comment]
Ah, didn't realise there was that log command - thanks! Yes, that's a fine substitute for my purposes, though I'm wondering if there's a nice way to improve discoverability...

(e.g. install a 'logger' that's a wrapper, or errors out with a helpful message by /system/bin/log ? A bit ugly, I guess)
