### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by juanse22** [termux/termux-packages#11124]
### Problem description

Cada vez que intento actualizar los paquetes de termux o instalar git no me deja

### What steps will reproduce the bug?

pkg install git
Checking availability of current mirror: ok
Get:1 https://packages.termux.dev/apt/termux-main stable InRelease [14.0 kB]
Reading package lists... Done
E: Release file for https://packages.termux.org/apt/termux-main/dists/stable/InRelease is not valid yet (invalid for another 1d 21h 53min 38s). Updates for this repository will not be applied.
~ $ pkg update
Checking availability of current mirror: ok
Get:1 https://packages.termux.dev/apt/termux-main stable InRelease [14.0 kB]
Reading package lists... Done
E: Release file for https://packages.termux.org/apt/termux-main/dists/stable/InRelease is not valid yet (invalid for another 1d 21h 53min 18s). Updates for this repository will not be applied.
~ $ apt upgrade
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

### What is the expected behavior?

Intento clonar un repositorio y no me deja me dice pkg install git  y le presionó y aparece esto git clone https://github.com/sivel/speedtest-cli.git
The program git is not installed. Install it by executing:
 pkg install git
~ $ pkg install git
Checking availability of current mirror: ok
Get:1 https://packages.termux.dev/apt/termux-main stable InRelease [14.0 kB]
Reading package lists... Done
E: Release file for https://packages.termux.org/apt/termux-main/dists/stable/InRelease is not valid yet (invalid for another 1d 21h 48min 26s). Updates for this repository will not be applied.

### System information

termux-info:

```

```Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.19.136-perf+ #1 SMP PREEMPT Thu Apr 28 09:42:28 CST 2022 aarch64 Android
Device manufacturer:
vivo
Device model:
V2027

**Comment by agnostic-apollo** [comment]
>Thu Apr 28 09:42:28 CST 2022

You seem to be opening issues from the past. @termux does not provide support for time travelled users.
