### ISSUE TITLE
[Bug]: termux/package-builder docker image cann't work

### ISSUE THREAD

**Issue by leleliu008** [termux/termux-packages#11126]
### Problem description

![Screenshot from 2022-07-01 21-48-02](https://user-images.githubusercontent.com/3040852/176907413-39fecc8f-9546-4312-bd75-6cb4843e5bdb.png)

### What steps will reproduce the bug?

**step1. fetch `termux-packages` from github**
```
git clone https://github.com/termux/termux-packages
```

**step2. create `termux-package-builder` docker container**
```
podman create -it -v ~/termux-packages:/home/builder/termux-packages --name termux-package-builder termux/package-builder
```

**step3. start `termux-package-builder` docker container**
```
podman start termux-package-builder
```

**step4. enter `termux-package-builder` docker container**
```
podman podman exec -it termux-package-builder bash
```

**step5. excute `setup-termux.sh`**
```
sudo ./scripts/setup-termux.sh
```
![Screenshot from 2022-07-01 21-48-02](https://user-images.githubusercontent.com/3040852/176907413-39fecc8f-9546-4312-bd75-6cb4843e5bdb.png)

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
`setup-termux.sh` is suppose to be run in `termux`. Run `setup-ubuntu.sh` to set up ubuntu.
