### ISSUE TITLE
[Bug]: pip install openvc-python-headless error

### ISSUE THREAD

**Issue by Fraggod** [termux/termux-packages#11125]
### Problem description

When i right `pip install opencv-python-headless`
It showing me error
Full log
https://pastebin.com/raw/SuizgY0L
Main error

https://pastebin.com/raw/H7r0bz7p
I hope someone can fix this

### What steps will reproduce the bug?

Idk

### What is the expected behavior?

Install successfully 

### System information

termux-info:
Termux Variables:                                                                               TERMUX_APK_RELEASE=F_DROID                                                                      TERMUX_APP_PACKAGE_MANAGER=apt                                                                  TERMUX_APP_PID=15592                                                                            TERMUX_IS_DEBUGGABLE_BUILD=0                                                                    TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0                                                                          Packages CPU architecture:                                                                      aarch64
Subscribed repositories:
# sources.list
deb https://packages.nscdn.top/termux-main stable main                                          Updatable packages:
All packages up to date                                                                         termux-tools version:
1.17                                                                                            Android version:
9                                                                                               Kernel build information:                                                                       Linux localhost 4.14.98-perf+ #1 SMP PREEMPT Fri Jul 24 19:04:09 CST 2020 aarch64 Android       Device manufacturer:                                                                            vivo                                                                                            Device model:                                                                                   vivo 1920_20
```

```

**Comment by Grimler91** [comment]
If you don't want to use termux's opencv-python, then you need to build from source and apply the same ANDROID_NO_TERMUX hack as we do in our build script: 
https://github.com/termux/termux-packages/blob/b1d0d45be918b6bf9a40b75d026af08b9a927327/packages/opencv/build.sh#L14-L33

Also make sure you have all the [dependencies](https://github.com/termux/termux-packages/blob/b1d0d45be918b6bf9a40b75d026af08b9a927327/packages/opencv/build.sh#L12) installed.
