### ISSUE TITLE
[Bug]: rust package does not work

### ISSUE THREAD

**Issue by pro465** [termux/termux-packages#11135]
basically #10958 but errors out as `CANNOT LINK EXECUTABLE "cargo": library "libssl.so.3" not found`

*note* im using LLVM 14.0.5

**Comment by thunder-coding** [comment]
You probably did a partial upgrade. See #9050 on how to recover

**Comment by pro465** [comment]
@thunder-coding well the instructions there seem outdated, but i got it fixed by running `pkg install openssl` after being mode aware of its existenceby the discussion there, so thanks anyway!

**Comment by thebluetropics** [comment]
@pro465 thank you so much, it worked by installing `openssl` package.

**Comment by pro465** [comment]
You're welcome @thebluetropics ! I'm glad to be able to help.
