### ISSUE TITLE
[Questions] : How to make bootable usb using termux?

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#11139]
And also included instructions on wiki

**Comment by 2096779623** [comment]
I guess Termux can't do this for now, try DriveDroid (root).

**Comment by T-Dynamos** [comment]
Can't be using `dd`

**Comment by truboxl** [comment]
https://play.google.com/store/apps/details?id=eu.depau.etchdroid
if you use USB OTG

**Comment by Grimler91** [comment]
What issues do you have with `dd`? Something like this works fine for me, usb is bootable: 

```
$ tsu
# dd if=alpine-standard-3.16.0-x86_64.iso bs=4M of=/dev/block/sde status=progress
155189248 bytes (155 MB, 148 MiB) copied, 20 s, 7.7 MB/s
37+0 records in
37+0 records out
```

**Comment by T-Dynamos** [comment]
Did you `umount` the usb first ?

**Comment by Grimler91** [comment]
If it is auto-mounted then it needs to be `umount`ed. Either from something like `/mnt/media_rw/XXXX-XXXX` or `/dev/block/vold/public:X,XX` (check where it is mounted with `sudo mount`)

**Comment by T-Dynamos** [comment]
Thanks

**Comment by Manamama** [comment]
FYI: [isodrive](https://github.com/nitanmarcel/isodrive)
