### ISSUE TITLE
npm install returns npm ERR: tar.unpack untar error

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#1113]
In my internal storage I create a folder **test**
then I `cd` into it using `cd /storage/emulated/0/test`

Then I run `npm init` command.
The initial setup questions are asked and the **package.json** file is created, till here everything works fine.

Then I wanted to install jquery as a dependency so I run the command:

`npm install jquery --save`

Then  I get the following errors

`npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/jquery/3.2.1/package.tgz
npm WARN test@1.0.0 No repository field.
npm ERR! Linux 3.4.0-lineageos-gbe4ae0d
npm ERR! argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "install" "jquery"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path /storage/emulated/0/vue-projects/test/node_modules/.staging/jquery-61c91999/package.json
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall utime

npm ERR! Error: EPERM: operation not permitted, utime '/storage/emulated/0/vue-projects/test/node_modules/.staging/jquery-61c91999/package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, utime '/storage/emulated/0/vue-projects/test/node_modules/.staging/jquery-61c91999/package.json'
npm ERR!     at Error (native)
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'utime',
npm ERR!   path: '/storage/emulated/0/vue-projects/test/node_modules/.staging/jquery-61c91999/package.json',
npm ERR!   fstream_finish_call: 'utimes',
npm ERR!   fstream_type: 'File',
npm ERR!   fstream_path: '/storage/emulated/0/vue-projects/test/node_modules/.staging/jquery-61c91999/package.json',
npm ERR!   fstream_class: 'FileWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:306:21',
npm ERR!      'FSReqWrap.oncomplete (fs.js:123:15)' ],
npm ERR!   parent: 'test' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

What shal i do?

npm ERR! Please include the following file with any support request:
npm ERR!     /storage/emulated/0/vue-projects/test/npm-debug.log
`

**Comment by Neo-Oli** [comment]
Can you try this in the home directory `~/` instead of the internal SD Card? It's probable that the filesystem of `/stroage/emulated/0/` doesn't support something that npm needs.

**Comment by ra-va-krish** [comment]
But could i acess the file afterwrds using my file explorer

**Comment by ra-va-krish** [comment]
There its getting installed but I want the test fokder to be acessible from my file explorer

**Comment by ra-va-krish** [comment]
But could i acess the file afterwrds using my file explorer

**Comment by ra-va-krish** [comment]
There ur gets installes but i want the test folder acessible from my file explorer

**Comment by CesarD** [comment]
Happened to me too, but while installing packages for an angular-cli generated app.
From folder on /sdcard failed, but from $home worked fine. 
Unfortunately if I work on $home, my phone app's data partition will quickly run out of space, so it would be great to make it work on sdcard.

**Comment by meeple142** [comment]
I am the same. Can use npm in home folder but not in shared storage. I just got around the issue by git cloneing the repo from github instead of using npm in storage/emulated/0/  in for a simple lib. I know this does not run `install` like npm does but for the simple lib I needed it worked. Sill a big bummer can't just use npm directly. What can I do to help figure out what is going on?  Or help more? I would really like this? :)

**Comment by its-pointless** [comment]
easy solution is to install yarn

**Comment by meeple142** [comment]
thanks @its-pointless but ended up with the same utime error. Found https://github.com/termux/termux-app/issues/240#issuecomment-274344873 and npm now works in shared storage

**Comment by lucasgonze** [comment]
Followed @meeple142's pointer and used npm -g. It worked.

**Comment by lucasgonze** [comment]
Handy detail for folks who don't read through into that link: you *can* npm install in termux as long as you're in internal storage which only termux can write to. And you can npm install -g if you are in external storage. What you can't do is both.

The problem this creates is using Android or ChromeOS tools on files you are admin'ing in termux. For example, you can't use a GUI editor on code in internal storage, and you can't npm install in external storage.

**Comment by fornwall** [comment]
@lucasgonze 

> For example, you can't use a GUI editor on code in internal storage

Note that you can do that, as long as the editor supports the Storage Access Framework in Android. As an example, [Turbo Editor](https://play.google.com/store/apps/details?id=com.maskyn.fileeditor) does that (enable "Use the Storage Access Framework" from the right hand drawer in Turbo Editor).

**Comment by lucasgonze** [comment]
Whoa. That is magic. Thanks for the incantation.
I saw a reference to the Storage Access Framework but didn't know how to take advantage of it.
