### ISSUE TITLE
[Package]: glib-static

### ISSUE THREAD

**Issue by searemind** [termux/termux-packages#11147]
### Package description

Is there any possibility that static libraries for glib and all glib extensions be built and added to the Termux Repositories?
On that note, can static libraries for gtk2, gtk3, qt5, libcairo, pango, harfbuzz (and harfbuzz-icu), webkitgtk, etc. be also added?
My reason for asking is so that portable binaries for multiple softwares could be built using these and building these huge libraries on-device is going to be a pain for me.

### Source code URL

https://docs.gtk.org/glib

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I have built cairo and harfbuzz on-device before (and also a port of webkit for fltk called webkitfltk).. statically none of them required extensive patches, just simple build error mitigations.

**Comment by sylirre** [comment]
Static libc is in `ndk-multilib` package.

I'd recommend against linking with static libc. It is not a standard GNU libc, but rather Bionic. In Termux the supplied static libc is targeted specifically at Android 7.0. Using it on any other Android version potentially leads to issues (e.g. DNS resolution won't work if used on Android 8+).

> On that note, can static libraries for gtk2, gtk3, qt5,

> My reason for asking is so that portable binaries for multiple softwares could be built using these

You will not get the portable software with these libraries when linked statically. They are dependent on data files (which can't be compiled-in: e.g. glib schemas, fonts, images, QML) and X windowing system (external non-library software which can't be statically linked with your program).

Static libraries do not make software smaller. Their size exactly same, just machine code is embedded inside program executable file.

**Comment by searemind** [comment]
i do not want static libraries for fully static binaries because i am aware of the dns resolution problems.. (unless using musl/cares)

but i *can* make the software i build be only dependent on libc.so and libdl.so which is very much portable and totally caters to my use-case, which is running these apps in another terminal emulator app (for which i have already compiled an X Server *statically*)

i think/hope that the glib data file locations can be defined with appropriate environment variables too..

static libraries, especially for qt would make it much easier for me to build more software.. otherwise i'll just make do with what i have

**Comment by sylirre** [comment]
> which is running these apps in another terminal emulator app

Well, there is another issue: hardcoded paths. They can't be changed through environment variables.

Example 1: https://github.com/termux/x11-packages/blob/master/packages/qt5-qtbase/ssl_certificate_path.patch#L21

Example 2: https://github.com/termux/termux-packages/blob/master/packages/glib/glib-gspawn.c.patch

That's out of scope patching everything to handle paths dynamically.
