### ISSUE TITLE
> Zlib is available in termux repo.

### ISSUE THREAD

**Issue by Achraf-hub** [termux/termux-packages#11140]
> Zlib is available in termux repo.

But i need zlib1g-dev and zlib1g

because its required by buildozer.

_Originally posted by @Tanishq-Banyal in https://github.com/termux/termux-packages/issues/6298#issuecomment-766295850_

**Comment by Achraf-hub** [comment]
You can fix this issue by running `termux-chroot` before running `buildozer`
buildozer expecte zlib to be 
`/usr/include/zlib.h`
but in termux it is in
`$PREFIX/include/zlib.h`
By running `termux-chroot`, $PREFIX will be `/usr`

**Comment by sylirre** [comment]
In Termux, zlib1g and zlib1g-dev is same `zlib` package.

**Comment by Tanishq-Banyal** [comment]
> You can fix this issue by running `termux-chroot` before running `buildozer`

Thanks for reply, But i have already moved on from termux environment.

Now i just use Arch Linux chroot on my Rooted phone. I only use termux as a terminal emulator now.

**Comment by T-Dynamos** [comment]
> > Zlib is available in termux repo.
> 
> But i need zlib1g-dev and zlib1g
> 
> because its required by buildozer.
> 
> _Originally posted by @Tanishq-Banyal in [#6298 (comment)](https://github.com/termux/termux-packages/issues/6298#issuecomment-766295850)_

Only works on amd64 (64bit) , on phone you can use github actions
