### ISSUE TITLE
BuG:  1. Failed to fetch https://packages , 2.Some index files failed to download. They have been ignored, or old ones used instead

### ISSUE THREAD

**Issue by Irtija123456** [termux/termux-packages#11143]
### Problem description

![Screenshot_20220704-015334_Termux](https://user-images.githubusercontent.com/108630874/177055287-87994c42-53da-48bf-b0d0-987df63cddad.jpg)

### What steps will reproduce the bug?

I don't know why this error is showing that,

"E: Failed to fetch https://packages-cf.termux.org/apt/termux-main/dists/stable/main/binary-aarch64/Packages  File has unexpected size (428092 != 427866). Mirror sync in progress? [IP: 172.67.200.228 443]"

"E: Some index files failed to download. They have been ignored, or old ones used instead."

### What is the expected behavior?

It goes just smoothly but now is showing this. Even I can't download any packages in termux but why is this happening? I want a clear answer to this. I have seen many times that different issues occur frequently but never get a solve. What are you guys doing. Please, do something quick to resolve this as soon as possible. Otherwise it is getting impossible to work in termux. 

### System information

termux-info:
Model no :  Samsung Galaxy M40 ( SM-M405F)
```
Android version:  android 9.0 pie
```

**Comment by Irtija123456** [comment]
I see this every time I write any command to download a package. For example,  "  pkg update && pkg upgrade "
                                Or       "  pkg install python "
Or if I try to install any packages it shows the error and stops in midway ! ! ! ? ! ! !

**Comment by Grimler91** [comment]
This should have been fixed. Switch to another mirror with `termux-change-repo` if not

**Comment by brand7noronha** [comment]
But why is the termux main mirror link having issues? Any idea?

**Comment by TomJo2000** [comment]
> But why is the termux main mirror link having issues? Any idea?

Please don't "necrobump" old issues.
This particular problem has been solved for over 2 years.

If you are having a new issue with the Termux mirrors please open a new issue.
