### ISSUE TITLE
[Package]: mesa-static

### ISSUE THREAD

**Issue by searemind** [termux/termux-packages#11157]
### Package description

A static libGL.a can be built for mesa (using the software rasterizer) but for some reason linking it with anything causes a segmentation fault. Has a successful static build of mesa been done on android yet?

### Home page URL

https://www.mesa3d.org/

### Source code URL

https://gitlab.freedesktop.org/mesa/mesa

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I have successfully *built* it on-device, but it is unusable in its current state.

**Comment by xtkoba** [comment]
We use Meson to build `mesa` package. As opposed to Autotools, Meson does not build static libraries by default. Moreover, no package in our repo does not require static mesa. So it is not going to be packaged.
