### ISSUE TITLE
[Package]: libcairo-static

### ISSUE THREAD

**Issue by searemind** [termux/termux-packages#11153]
### Package description

static libraries for cairo can be easily built with no changes to existing code

### Source code URL

https://github.com/freedesktop/cairo

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

i have built cairo statically on-device many times and it would be nice to have in the repos too..

**Comment by Grimler91** [comment]
What's wrong with the static cairo package we already have?

```
$ apt search libcairo-static
Sorting... Done
Full Text Search... Done
libcairo-static/stable 1.16.0-9 arm
  Static libraries for libcairo
```

**Comment by searemind** [comment]
i'm so sorry.. i didnt see it at first.. i'll close the issue
