### ISSUE TITLE
[Package]: harfbuzz-static

### ISSUE THREAD

**Issue by searemind** [termux/termux-packages#11152]
### Package description

static libraries for harbuzz can be easily built and as far as i know, it is the default way to build it unless declared otherwise.

### Source code URL

https://github.com/harfbuzz/harfbuzz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

i have built it statically on-device many times.. it would be nice to have it in the repos itself

**Comment by xtkoba** [comment]
We use Meson to build `harfbuzz` package. As opposed to Autotools, Meson does not build static libraries by default. Moreover, no package in our repo does not require static harfbuzz. So it is not going to be packaged.
