### ISSUE TITLE
[Bug]: npm login have bug, password cannot be written

### ISSUE THREAD

**Issue by Normioffi** [termux/termux-packages#11150]
### Problem description

II would like to try to log in to npm with termux, but when I type my username, skip a line, I switch to the password, but strangely, the password is impossible to fill, whether it is the physical keyboard or the virtual, I tried everything, it does not work and it leaves a blank box

### What steps will reproduce the bug?

First step, go on termux
Second step, makes the npm login command
Step Three, enter your username, skip a line, and you will see the error

### What is the expected behavior?

That I can put my password to log in

**Comment by sylirre** [comment]
Password is not echoed to console, you won't see it when typing. Sane behavior on all Linux-based systems.
