### ISSUE TITLE
[Package]: Quick JS

### ISSUE THREAD

**Issue by X7md** [termux/termux-packages#11158]
### Package description

a small and embeddable Javascript engine. It supports the ES2020 specification including modules, asynchronous generators, proxies and BigInt.

In short (Small JavaScript Engine)

### Home page URL

https://bellard.org/quickjs/

### Source code URL

https://github.com/bellard/quickjs

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by X7md** [comment]
I actually try search but... before open this issue

```bash
> apt search qjs
Sorting... Done
Full Text Search... Done
> apt search quick
Sorting... Done
Full Text Search... Done
> apt search quick
Sorting... Done
Full Text Search... Done
```
But no results...

**Comment by sylirre** [comment]
QuickJS is available for all architectures, so just either `apt update` or switch to another mirror.

![k](https://user-images.githubusercontent.com/107305601/177168968-cf6d837d-7331-4c12-b42f-07143a5a9b28.png)

**Comment by X7md** [comment]
I will see... 

Thanks
