### ISSUE TITLE
[main/binutils]: use `/system/bin/linker{64}?` as default linker in linker

### ISSUE THREAD

**Issue by vincentARM** [termux/termux-packages#11159]
Hello.
I write ARM assembly program (32 or 64 bits) with termux and android. its work fine.
But when i use the X11 library with this script 👍 
`
echo "Compilation 32 bits de "$1".s"

as -o $1".o"   $1".s" -a >listing.txt

#gcc -o $1 $1".o"  -e main

ld -o $1 $1".o"   ~/asm32/routines32And.o -e main -lX11 -L/usr/lpp/X11/lib  

ls -l $1*  

echo "Fin de compilation."
`
No compilation error but execution error 👍 
~/.../rosetta/asm3 $ animLetter
bash: ./animLetter: No such file or directory

After many days of research and testing the problem comes from an error in the dynamic library loader program which does not exist in the termux environment.
see the command strings of the executable:
~/.../rosetta/asm3 $ strings animLetter |more
**/usr/lib/ld.so.1**
XNextEvent
XDestroyWindow
XSetStandardProperties

I modify the compilation script with this 👍 
`
#compilation assembleur
#echo $0,$1

echo "Compilation 32 bits de "$1".s"

as -o $1".o"   $1".s"    -a >listing.txt

ld -o $1 $1".o"  ~/asm32/routines32And.o -e main -lX11 -L/data/data/com.termux/files/usr/lib -ldl -lc -dynamic-linker /system/bin/linker -pie /data/data/com.termux/files/usr/lib/libX11.so  

ls -l $1*  

echo "Fin de compilation."
`
The compilation is ok and execution is OK

the strings command display 👍 

~/.../rosetta/asm3 $ strings animLetter |more
/system/bin/linker
XNextEvent
XDestroyWindow

Can someone modify the script of the linker to no longer have this error and avoid having to make the changes in our script.

Sorry for my bad english ! it is a goggle traduction.

**Comment by sylirre** [comment]
Need to change only relevant architectures, e.g.
```.diff
diff -uNr binutils-2.38/bfd/elf32-arm.c binutils-2.38.mod/bfd/elf32-arm.c
--- binutils-2.38/bfd/elf32-arm.c	2022-01-22 14:14:07.000000000 +0200
+++ binutils-2.38.mod/bfd/elf32-arm.c	2022-07-06 19:51:24.083970342 +0300
@@ -2306,7 +2306,7 @@
 
 /* The name of the dynamic interpreter.  This is put in the .interp
    section.  */
-#define ELF_DYNAMIC_INTERPRETER     "/usr/lib/ld.so.1"
+#define ELF_DYNAMIC_INTERPRETER     "/system/bin/linker"
 
 /* FDPIC default stack size.  */
 #define DEFAULT_STACK_SIZE 0x8000
diff -uNr binutils-2.38/bfd/elfnn-aarch64.c binutils-2.38.mod/bfd/elfnn-aarch64.c
--- binutils-2.38/bfd/elfnn-aarch64.c	2022-01-22 14:14:07.000000000 +0200
+++ binutils-2.38.mod/bfd/elfnn-aarch64.c	2022-07-06 19:50:57.715734024 +0300
@@ -2356,7 +2356,7 @@
 
 /* The name of the dynamic interpreter.  This is put in the .interp
    section.  */
-#define ELF_DYNAMIC_INTERPRETER     "/lib/ld.so.1"
+#define ELF_DYNAMIC_INTERPRETER     "/system/bin/linker64"
 
 #define AARCH64_MAX_FWD_BRANCH_OFFSET \
   (((1 << 25) - 1) << 2)

```
