### ISSUE TITLE
libm.so.6 not found in nokogiri gem.

### ISSUE THREAD

**Issue by Gh0st-sniper** [termux/termux-packages#11163]
### Problem description

`rails new ` command throws the following error : 

![Screenshot_2022-07-05-16-06-31-06_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/77871514/177309756-b436a4d2-6683-4b31-8fe8-12f0734398b2.jpg)

![Screenshot_2022-07-05-16-06-44-94_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/77871514/177309777-c2d8c51f-76b8-4189-a99d-468974c41697.jpg)
 
Attaching for your reference. The issue is with nokogiri it seems . Nokogiri was installed with the following command: 

`   gem install nokogiri --platform=ruby -- --use-system-libraries ` 

### What steps will reproduce the bug?

1. ` gem install nokogiri --platform=ruby -- --use-system-libraries `
2. gem install rails .
3. rails new (project_name)

### What is the expected behavior?

The expected behaviour is that rails should create the project with all dependencies installed.

### System information

termux-info:

```
Termux Variables:                               TERMUX_APK_RELEASE=GITHUB                       TERMUX_APP_PACKAGE_MANAGER=apt                  TERMUX_APP_PID=17061
TERMUX_IS_DEBUGGABLE_BUILD=1                    TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0                          Packages CPU architecture:
aarch64                                         Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
Updatable packages:                             apt/stable 2.5.1 aarch64 [upgradable from: 2.5.0-1]                                             curl/stable 7.84.0 aarch64 [upgradable from: 7.83.1]                                            git/stable 2.37.0 aarch64 [upgradable from: 2.36.1]                                             inetutils/stable 2.2 aarch64 [upgradable from: 1.9.4-13]
libcurl/stable 7.84.0 aarch64 [upgradable from: 7.83.1]
liblz4/stable 1.9.3-1 aarch64 [upgradable from: 1.9.3]
libnghttp2/stable 1.48.0 aarch64 [upgradable from: 1.47.0]
termux-am-socket/stable 1.5.0 aarch64 [upgradable from: 1.4.0]
termux-keyring/stable 3.7 all [upgradable from: 3.6]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-2]
termux-tools/stable 1.19 all [upgradable from: 1.14]
termux-tools version:
1.14
Android version:
11
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Fri Jan 21 01:00:47 CST 2022 aarch64 Android
Device manufacturer:
OnePlus
Device model:
IV2201
```

**Comment by tomty89** [comment]
AFAICT the nokogiri.so in concern isn't even built during gem install but would simply be downloaded as a binary file, and the file isn't built for Android/bionic/Termux.

Either way this isn't an issue in any of the termux packages. There's essentially nothing we can do for ruby gems or anything alike (such as python pip packages). (Well you can pass messages like what Termux is and what are the libc and library naming in Android to upstream and see if they can get some support in.)

In some cases you might get things working by specifying some linker flag but in this case that is not even relevant, apparently.

**Comment by xtkoba** [comment]
Essentially a duplicate of https://github.com/termux/termux-packages/discussions/8583.
