### ISSUE TITLE
Ubuntu zetsy is error without tsu

### ISSUE THREAD

**Issue by hariswhdn** [termux/termux-packages#1116]
If i run ubuntu without tsu, it will error. I try to install ubuntu and reinstall termux many times but i still get this error.

I have proot, but i dont know how to use it. I want to use proot instead tsu.
I already searching every error on google, i cant solve it. I am new on linux, hope i get solved this. Thank you, great apps.

./startubuntu.sh
groups: cannot find name for group ID 1015
groups: cannot find name for group ID 1023
groups: cannot find name for group ID 1028
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 50020
bash: /root/.bash_profile: Permission denied
root@localhost:~# exit
logout
bash: /root/.bash_logout: Permission denied
$ tsu
# ./startubuntu.sh
root@localhost:~#

**Comment by Neo-Oli** [comment]
I'm closing this in favor of https://github.com/Neo-Oli/termux-ubuntu/issues/2, which has also been opened by you at the correct place.
