### ISSUE TITLE
[Bug]: in "apt list" output, random duplicate "stable"

### ISSUE THREAD

**Issue by vinc17fr** [termux/termux-packages#11165]
### Problem description

When I run `apt list` (possibly via `pkg list-installed`), some lines of the output get a duplicate `stable`.

### What steps will reproduce the bug?

```
% apt list termux-keyring
Listing... Done
termux-keyring/stable,stable,now 3.7 all [installed]
```

### What is the expected behavior?

One should get
```
termux-keyring/stable,now 3.7 all [installed]
```

This issue appeared just after the latest upgrade (but it was already occurring in the past).

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.19
Android version:
12
Kernel build information:
Linux localhost 4.14.113-24230781 #1 SMP PREEMPT Thu May 26 08:51:42 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N975F
```

**Comment by 2096779623** [comment]
I can't reproduce this.

**Comment by vinc17fr** [comment]
This issue still occurs with apt 2.5.2-3.

**Comment by xtkoba** [comment]
Seems like your `$PREFIX/etc/apt/sources.list` (and possibly `sources.list.d/*`) are somehow misconfigured.

For example, this can happen when `sources.list` looks something like:

```
# The main termux repository, behind cloudflare cache:
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# The main termux repository:
deb https://packages.termux.dev/apt/termux-main/ stable main
```

which should not with clean installation.

**Comment by vinc17fr** [comment]
I was using the default configuration. Anyway, I've just checked again and retried, and I can still reproduce the issue with a single deb line: #12071.
