### ISSUE TITLE
[Package]: logo-ls

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#11178]
### Package description

modern ls command with beautiful Icons and Git Integrations . Written in Golang

### Home page URL

https://github.com/Yash-Handa/logo-ls

### Source code URL

https://github.com/Yash-Handa/logo-ls

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
![tstmp_20220707172333](https://user-images.githubusercontent.com/57583560/177739993-3258f3b5-61bc-4602-8fbe-a48fffae84a9.png)

**Comment by kyzsukii** [comment]
need nerd font to display logo

**Comment by wmcbtech30** [comment]
We have equivalent packages
* [exa](https://github.com/termux/termux-packages/tree/master/packages/exa)
* [lsd](https://github.com/termux/termux-packages/tree/master/packages/lsd)

They function the same, exa one has git supported. you have any elaboration why is this going to be added? does it have some features absent in those two packages?

**Comment by kyzsukii** [comment]
thanks, i never look that

**Comment by remo7777** [comment]
https://github.com/utfeight/logo-ls-modernized.git

**Comment by TomJo2000** [comment]
@remo7777  if you'd like to make a package replacement request please open a new issue.
You can have a look at the request for replacing `exa` with `eza` as an example.
- #17681

**Comment by Biswa96** [comment]
The last commit of the fork repository https://github.com/utfeight/logo-ls-modernized.git was a year ago.

**Comment by TomJo2000** [comment]
Under the [current packaging guidelines](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) this package would not be eligible for packaging.
- The only packages are from the AUR and Termux.
- The original hasn't seen any development in 4 years, the fork mentioned above hasn't received any in16 months, and only contains very minor fixes to adapt to NerdFonts 3.0.
- The package builds without any patches or shenanigans.
- The functionality provided by `logo-ls` is duplicated by both `lsd` and `eza` in large part.

I think we should upgrade that replacement request into a move request to the 
[TUR](https://github.com/termux-user-repository/tur)  and just patch the broken NerdFont symbols in the original.
Or just drop the package entirely.

**Comment by remo7777** [comment]
> @remo7777 if you'd like to make a package replacement request please open a new issue. You can have a look at the request for replacing `exa` with `eza` as an example.
> 
> * [Please consider changing exa to eza. #17681](https://github.com/termux/termux-packages/issues/17681)

That's what I understood.  But all icons are removed day by day. Did I mention about exa or eza? I use both logo-ls and eza. And I'm worried about logo-ls.

**Comment by twaik** [comment]
He said to take a look to see how it should be done. Not to take a look at exa or eza themselves.
