### ISSUE TITLE
Privoxy has no user manual

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#1117]
According to the config file the user manual should be in 
```
user-manual /data/data/com.termux/files/usr/share/doc/privoxy/user-manual/ 
```
This path doesn't exist and I don't think the manual is installed anywhere else. 

If you visit http://config.privoxy.org, while running privoxy you can configure privoxy in the browser. A lot of links on that page link to the config file, which leads to errors on that page.

**Comment by vishalbiswas** [comment]
adding `TERMUX_PKG_KEEP_SHARE_DOC=yes` to the build.sh fixes this

**Comment by Neo-Oli** [comment]
Can confirm, update fixed it.
