### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by azizdeanda** [termux/termux-packages#11171]
### Problem description

![image](https://user-images.githubusercontent.com/42995895/177515703-3ef78dbc-18cc-47bc-bed4-6031ab442979.png)

### What steps will reproduce the bug?

./start-ubuntu.sh promble issuess how to fix this

### System information

termux-info:

```

```

**Comment by thunder-coding** [comment]
Contact the person from where you got the script. We have nothing to do with it
