### ISSUE TITLE
[Bug]: libspdlog build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11175]
### Problem description

[libspdlog.txt](https://github.com/termux/termux-packages/files/9056953/libspdlog.txt)

### What steps will reproduce the bug?

building

### System information

termux-info:

```

```

**Comment by licy183** [comment]
`libspdlog` uses `fmt` as build dependency, so I think this is no need for us to rebuild this package after `fmt` is updated. But anyway, we need to update `libspdlog`.
