### ISSUE TITLE
[Package]: sysprop

### ISSUE THREAD

**Issue by RohitVerma882** [termux/termux-packages#11184]
### Package description

sysprop used to generate .sysprop file to .cpp or .java format.

### Source code URL

https://android.googlesource.com/platform/system/tools/sysprop

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

sysprop_cpp and sysprop_java executable

**Comment by rallg** [comment]
I looked at the linked web page. Is that something specific to Android software development API, requiring a rooted device or a non-Android computer? Or is it something that Termux developers, or ordinary users, would find useful? Not clear.

**Comment by switchroute** [comment]
Try installing android sysprop from a third party repo [Android-sysprop](https://github.com/rendiix/rendiix.github.io)
