### ISSUE TITLE
kali linux installation time error

### ISSUE THREAD

**Issue by Jasssg** [termux/termux-packages#11186]
after executing the command './install-nethunter-termux' showing error "Rootfs corrupted, please run this installer again or download the file manually" plz solve the problem 
![Screenshot_2022-07-07-09-34-58-31_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/108751467/177721042-ad5f6856-0b8d-452c-9106-41e33033aa1a.jpg)

**Comment by 2096779623** [comment]
> Its not duplicate its another problem

**Comment by 2096779623** [comment]
> Its not duplicate its another problem

1. We are not solving issues of third-party programs & scripts.
2. We are not helping with hacking & pranking.
