### ISSUE TITLE
[Package]: cli-file-manager

### ISSUE THREAD

**Issue by kyzsukii** [termux/termux-packages#11180]
### Package description

This is a basic file manager that runs inside your terminal.
This tool is designed for Linux.
It's fully responsive and incredibly fast.

### Source code URL

https://github.com/0l1v3rr/cli-file-manager

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
> Not serving duplicated functionality
> Please avoid submitting packages which duplicate functionality of already present ones.
> The more useless packages in repositories, the less overall packaging and service quality - remembering that our resources are limited?

Please tell me how this bag is different from #11179?

**Comment by Dsmxx** [comment]
> ### Package description
> 
> This is a basic file manager that runs inside your terminal.
> This tool is designed for Linux.
> It's fully responsive and incredibly fast.
> 
> ### Home page URL
> 
> _No response_
> 
> ### Source code URL
> 
> https://github.com/0l1v3rr/cli-file-manager
> 
> ### Packaging policy acknowledgement
> 
> - [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).
> 
> ### Additional information
> 
> _No response_
