### ISSUE TITLE
[Package]: Corgi : Command Bookmarker/Snippet tool

### ISSUE THREAD

**Issue by OilSubjectLoss7** [termux/termux-packages#11198]
### Package description

Just like pet but better.
It can save and execute multiple commands, unlike pet.

### Home page URL

https://github.com/DrakeW/corgi

### Source code URL

https://github.com/DrakeW/corgi

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by langfoster** [comment]
{uncreas}
^blue-tacp
>1.gv

**Comment by OilSubjectLoss7** [comment]
corgi seems to have a problem with finding `fish` HISTFILE(history command file)
 can this be fixed somehow?

**Comment by 2096779623** [comment]
> corgi seems to have a problem with finding `fish` HISTFILE(history command file) can this be fixed somehow?
> 
> `corgi new` `Could not find HISTFILE in env - Using default based on shell type`

https://github.com/termux/termux-packages/blob/ffcc34d3f1183ddbbcf8277d0b893b5b831ae29b/packages/corgi/build.sh#L32

**Comment by 2096779623** [comment]
![Screenshot_20220721-084245](https://user-images.githubusercontent.com/57583560/180105931-44b35e0d-2b54-46af-9196-075ae91c6906.png)

I don't know why it kills my `bash`😓
Temporary workaround: 
1. [Enter failsafe](https://wiki.termux.com/wiki/Recover_a_broken_environment)
3. `cd ../usr/bin`
4.  3. `./apt reinstall bash`
5. Relaunch the termux

it writes some weird numbers inside bash:
![Screenshot_20220721-084728](https://user-images.githubusercontent.com/57583560/180106286-6b94f525-b906-4092-b9f8-5570ddc4d1b3.png)

**Comment by OilSubjectLoss7** [comment]
oof it broke my shell too

**Comment by 2096779623** [comment]
> oof it broke my shell too

I will make a PR to fix this,do not use `corgi` during this time
