### ISSUE TITLE
Switch from libgcc to compiler-rt

### ISSUE THREAD

**Issue by joakim-noah** [termux/termux-packages#1120]
Since the NDK has switched to clang, surely it would be better for Termux to use [compiler-rt](https://compiler-rt.llvm.org) instead?  Maybe it's worth trying to compile several packages with compiler-rt and see if anything breaks.

**Comment by alive4ever** [comment]
#72 has some information regarding libgcc and compiler-rt

**Comment by fornwall** [comment]
Note that the NDK hasn't switched to compiler-rt yet (but probably plans to): https://github.com/android-ndk/ndk/issues/294

The easiest way would be to wait for the NDK to start using compiler-rt and use it in Termux, just like libgcc is now, but for now we could look into packaging it ourselves.

**Comment by DanAlbert** [comment]
You can probably close this. This isn't a detail that NDK users should have to think about. We'll make the switch inside the NDK and it will make its way downstream to you.

**Comment by joakim-noah** [comment]
We've already switched to libc++ too, so Termux precedes the NDK.  At the very least, we could provide an optional compiler-rt package, that users could choose to rely on in place of the libgcc package that clang automatically pulls in.
