### ISSUE TITLE
very big pulseaudio problem

### ISSUE THREAD

**Issue by dontknowhy** [termux/termux-packages#11208]
### Problem description

pulseaudio died in android12
stdoutput(run pulseaudio):
W: [pulseaudio] core.c: Failed to allocate shared posix-shm memory pool. Falling back to a normal memory pool.
E: [pulseaudio] ltdl-bind-now.c: Failed to open module /data/data/com.termux/files/usr/lib/pulse-14.2/modules/module-sles-sink.so: dlopen failed: library "libigfxmanager.so" not found: needed by /system/lib64/libiGraphicsCore.honor.so in namespace (default)
E: [pulseaudio] module.c: Failed to open module "module-sles-sink".
E: [pulseaudio] ltdl-bind-now.c: Failed to open module /data/data/com.termux/files/usr/lib/pulse-14.2/modules/module-sles-source.so: dlopen failed: library "libigfxmanager.so" not found: needed by /system/lib64/libiGraphicsCore.honor.so in namespace (default)
E: [pulseaudio] module.c: Failed to open module "module-sles-source".
E: [pulseaudio] socket-server.c: bind(): Unknown error 98
E: [pulseaudio] socket-server.c: bind(): Unknown error 98
E: [pulseaudio] module.c: Failed to load module "module-simple-protocol-tcp" (argument: "rate=44100 format=s16le channels=2 source=0 record=true port=12345"): initialization failed.
E: [pulseaudio] module-tunnel.c: Failed to create stream.

### What steps will reproduce the bug?

pulseaudio --start

### What is the expected behavior?

load modules
and play sound

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12545
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main
# sources.list.d/pointless.list
deb https://mirrors.ustc.edu.cn/termux-its-pointless/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.ustc.edu.cn/termux/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.14
Android version:
12
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Jun 30 11:59:27 CST 2022 aarch64 Android
Device manufacturer:
HONOR
Device model:
BRT-W09

```
PS:DO NOT ASK ME FOR THE KERNEL VERSION

**Comment by tomty89** [comment]
This is apparently some kind of vendor-specfic linker/linking issue/flaw. I'm afraid that there's probably nothing we can do.

You may try to workaround it with something like: `LD_PRELOAD=/system/lib64/libigfxmanager.so pulseaudio --start` though. Or use `module-aaudio-sink` *instead*.

**Comment by dontknowhy** [comment]
> This is apparently some kind of vendor-specfic linker/linking issue/flaw. I'm afraid that there's probably nothing we can do.
> 
> You may try to workaround it with something like: `LD_PRELOAD=/system/lib64/libigfxmanager.so pulseaudio --start` though. Or use `module-aaudio-sink` *instead*.

module-aaudio-sink is working!!!

**Comment by ArieSR91** [comment]
If you have pulseaudio problem in wine-hangover, edit your wine launcher and don't set XDG_RUNTIME_DIR. Give comment #XDG_RUNTIME_DIR=${TMPDIR}
