### ISSUE TITLE
Pillow has no support of webp format

### ISSUE THREAD

**Issue by NatuRao** [termux/termux-packages#11212]
### Problem description

I tried converting some .jpg files to pdf from python using Pillow, and it's showing me the following warning.

warning: image file could not be identified because WEBP support is not installed
Exception: cannot identify image file '<imagepath>/<imagename>'

I tried install libwebp using 'pkg install libwebp'. But it is not working...

Any solution?

### What steps will reproduce the bug?

Converting the .jpg to pdf

### System information

termux-info:

```
Version 0.118.0 (118) 
```

**Comment by sylirre** [comment]
The issue here is that you installed (more specifically - built) Pillow without libwebp support.

Try this:
* Uninstall Pillow module.
* Clear pip cache.
* `pkg install libwebp`. (omit this step if already done)
* Install Pillow again.

**Comment by NatuRao** [comment]
@sylirre Thank you so so much, It worked! 
But I still wonder why .jpg files need webp support... but thank you for your help.
