### ISSUE TITLE
[coreutils] du spits NICE nonsense

### ISSUE THREAD

**Issue by alive4ever** [termux/termux-packages#1121]
`du` from coreutils spits additional output.
```
$ du -sh ~/.bashrc
NICE
NICE
output=4.0K
4.0K    /data/data/com.termux/files/home/.bashrc
```
`busybox du` outputs is good.
```
$ busybox du -sh ~/.bashrc
4.0K    /data/data/com.termux/files/home/.bashrc
```

**Comment by fornwall** [comment]
Thanks for reporting!

This was the result of a debug patch which was committed by mistake when diagnosing a build issue - it has now been fixed in version `8.27-3` of the coreutils package which is available as an update.
