### ISSUE TITLE
[Package]: glibc

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#11230]
### Package description

*For many centuries and mankind, the termux project has been a slave to the unstable and hysterical bionic library.  The developers tried to save themselves from this and for this they created a proot that allows you to run glibc. But bionic caught on to the developers' plans and started deliberately slowing down every glibc process. Bionic was willing to do anything to keep termux a slave to his system. But I managed to find a secret recipe that allows you to compile a working glibc without proot on termux.  Bionic started to slowly lose control over termux, and because of this, he began to put spokes in the wheels in my new project. Therefore, I urge users and developers to revolutionize the termux project so that bionic completely loses control of termux. Glory to the freedom of termux.*  

Attention: this is all a joke!!!

### Source code URL

https://github.com/Maxython/glibc-for-termux

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by T-Dynamos** [comment]
Here is probably the best option for this package request: https://github.com/termux-user-repository/tur.

**Comment by mohammadj44** [comment]
> ### Package description
> 
> *For many centuries and mankind, the termux project has been a slave to the unstable and hysterical bionic library.  The developers tried to save themselves from this and for this they created a proot that allows you to run glibc. But bionic caught on to the developers' plans and started deliberately slowing down every glibc process. Bionic was willing to do anything to keep termux a slave to his system. But I managed to find a secret recipe that allows you to compile a working glibc without proot on termux.  Bionic started to slowly lose control over termux, and because of this, he began to put spokes in the wheels in my new project. Therefore, I urge users and developers to revolutionize the termux project so that bionic completely loses control of termux. Glory to the freedom of termux.*  
> 
> Attention: this is all a joke!!!
> 
> ### Home page URL
> 
> _No response_
> 
> ### Source code URL
> 
> https://github.com/Maxython/glibc-for-termux
> 
> ### Packaging policy acknowledgement
> 
> - [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).
> 
> ### Additional information
> 
> _No response_

@mohammadj44

**Comment by mohammadj44** [comment]
@mohammadj44 `My Public Address to Receive KCS 0xc8A114de0650A417761CF148124a2B5a04019Fa5

Pay me via Trust Wallet: https://link.trustwallet.com/send?coin=10000321&address=0xc8A114de0650A417761CF148124a2B5a04019Fa5`

**Comment by Maxython** [comment]
> Here is probably the best option for this package request: https://github.com/termux-user-repository/tur.

Does TUR support regular gcc compilation (without android ndk)?

**Comment by T-Dynamos** [comment]
> gcc



> > Here is probably the best option for this package request: https://github.com/termux-user-repository/tur.
> 
> Does TUR support regular gcc compilation (without android ndk)?


TUR uses same building scripts what Termux does. So all building mechanism is same.
