### ISSUE TITLE
[Bug]: Can't delete or modify file or folder with external file manager

### ISSUE THREAD

**Issue by tfarhan00** [termux/termux-packages#11247]
### Problem description

Everytime i try to delete or rename the file or folder it's always throw an error "unable to modify" 

### What steps will reproduce the bug?

When u try to delete/rename the file/folder with third party file manager in this case i'm using Acode

### What is the expected behavior?

Delete/rename any file/folder with external app flawlessly

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7131
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
Updatable packages:
termux-tools/stable 1.20 all [upgradable from: 1.19]
termux-tools version:
1.19
Android version:
12
Kernel build information:
Linux localhost 4.9.292-gab4493f31457-ab8272301 #0 SMP PREEMPT Tue Mar 8 09:05:39 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 3a

```

**Comment by 2096779623** [comment]
Android restricts third-party apps from doing these things.

**Comment by liminalcat** [comment]
> Android restricts third-party apps from doing these things.

Okay thanks, i thought it's something that could be configured within the termux itself
