### ISSUE TITLE
Laravel tinker hangs and displays not output 

### ISSUE THREAD

**Issue by Gh0st-sniper** [termux/termux-packages#11241]
` php artisan tinker` command opens PSY shell to interact with a model . 

Everything works fine until u switch to some other app and come back to termux , the PSY shell hangs and shows no output .

![Screenshot_2022-07-14-09-08-18-08_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/77871514/178893920-a65ff6f7-c8fd-4d44-ae16-37946852138f.jpg)

**Comment by Grimler91** [comment]
Check `adb logcat` to see if the process was killed in the background

**Comment by Gh0st-sniper** [comment]
Sharing the screen shot of `adb logcat ` 
![Screenshot_2022-07-14-20-46-09-18_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/77871514/179017002-d1ac7266-5531-4a26-b9d3-6aa6da6ce60a.jpg)

**Comment by Gh0st-sniper** [comment]
I'm sorry but I don't understand the logs  ..

**Comment by 2096779623** [comment]
> I'm sorry but I don't understand the logs ..

https://stackoverflow.com/questions/3707880/using-adb-logcat-with-a-real-phone-and-not-the-emulator

**Comment by Gh0st-sniper** [comment]
There is a lot of output  but how do I find termux-specific data in the logs?

**Comment by 2096779623** [comment]
> There is a lot of output but how do I find termux-specific data in the logs?

You don't need to look it up, just upload it here.

**Comment by Gh0st-sniper** [comment]
> > There is a lot of output but how do I find termux-specific data in the logs?
> 
> You don't need to look it up, just upload it here.

https://drive.google.com/file/d/1VbJQktNF3wFgJ5auE4lhsRNEt-olbg9s/view?usp=drivesdk


Please find the link of the log output.

**Comment by 2096779623** [comment]
> https://drive.google.com/file/d/1VbJQktNF3wFgJ5auE4lhsRNEt-olbg9s/view?usp=drivesdk

[log2.txt](https://github.com/termux/termux-packages/files/9117918/log2.txt)

**Comment by Grimler91** [comment]
It's killed to free more memory it seems:

```
07-15 10:07:12.629 I/AthenaService( 1507): MemoryGuardAction: check & kill orphan process...
07-15 10:07:12.629 I/AthenaService( 1507): MemoryGuardAction: found orphan process [1][25106][10256]php
07-15 10:07:12.644 I/AthenaService( 1507): MemoryGuardAction: kill orphan process [1][25106][10256]php(psysh (loop))(0)
07-15 10:07:12.644 I/AthenaService( 1507): OplusClearSystemService : K [25106][10256][psysh (loop)(0), reason: 71
07-15 10:07:12.644 I/Process ( 1507): Sending signal. PID: 25106 SIG: 9
07-15 10:07:12.645 I/AthenaService( 1507): MemoryGuardAction: [FINISH] type: 392, 1516MB, 1800MB, -73MB, appcare=19, 328ms
```

So try to disable battery optimisations and similar for termux, check https://dontkillmyapp.com/oneplus.

Closing since there's nothing termux can do to prevent android from killing processes

**Comment by Gh0st-sniper** [comment]
I truly appreciate the quick responses from you guys. Cheers ! 👏
