### ISSUE TITLE
[Bug]: Wrong header path when building

### ISSUE THREAD

**Issue by matlink** [termux/termux-packages#11262]
### Problem description

I would like to add support of LZO on the bacula-fd package. For that, I add liblzo as a depency.
However, when building the package bacula-fd, the build script is looking at the wrong place for the headers : 
```
Downloading dependency liblzo@2.10-3 if necessary...
Found liblzo in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting liblzo...
checking /usr/include/lzo/lzoconf.h usability... no
checking /usr/include/lzo/lzoconf.h presence... no
checking for /usr/include/lzo/lzoconf.h... no
```
since they are in /data/data/com.termux/files/usr/include, it fails to find them. Making a symlink from /usr/include/lzo to /data/data/com.termux/files/usr/include/lzo works.

The bacula compile script supports the option `--with-lzo=${DIR}` but setting it to `${TERMUX_PREFIX}/include` does not solve the issue.

How could I resolve this?
Thank you.

### What steps will reproduce the bug?

I compile using docker

**Comment by Grimler91** [comment]
> The bacula compile script supports the option --with-lzo=${DIR} but setting it to ${TERMUX_PREFIX}/include does not solve the issue

Usually the `--with` args expect just `$PREFIX` and not `$PREFIX/include`. If that doesn't work then check config.log and/or the configure.ac/autom4te script that does the check to see what it actually does

**Comment by matlink** [comment]
You are right, setting `--with-lzo=${TERMUX_PREFIX}` fixes it. Thanks!
