### ISSUE TITLE
[Package]:  CuteFish De

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#11278]
### Package description

Its a desktop env for linux giving mac os look 

### Home page URL

https://github.com/cutefishos

### Source code URL

_Not Provided_

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Is any problem with it?
Contains following packages :
   1) cutefish-calculator  2) cutefish-core  3) cutefish-dock
   4) cutefish-filemanager  5) cutefish-icons  6) cutefish-kwin-plugins
   7) cutefish-launcher  8) cutefish-qt-plugins  9) cutefish-screenlocker
   10) cutefish-settings  11) cutefish-statusbar  12) cutefish-terminal
   13) cutefish-wallpapers

**Comment by zairullahdev** [comment]
Can you try the compiler suggested?

**Comment by zairullahdev** [comment]
Or change another compiler
