### ISSUE TITLE
Mpv stuttering terribly starting with Android 7.1 with bluetooth.

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#1127]
I recently updated my Android (and every time I do I have to create an issue starting with "I recently updated my Android...") to 7.1.1. Ever since then mpv has been skipping and stuttering. I've been using this same setup for more than a year now. I investigated extensively what the problem could be. Did all the battery optimization and settings reset that has been suggested in the many forum threads over the years for similar issues. 
Testing reveals:
1. It only happens when connecting to a bluetooth device. It works fine over speakers.
2. It happens with various kinds of bluetooth devices
3. It only happens with mpv on Termux. Using the Youtube App works fine. I also set up mpd and ncmpcpp and it works fine with that too. 

I suspect this may be very hard to debug and it probably only affects me, but it basically killed my entire audio listening on my phone :(

**Comment by tyzoid** [comment]
Both the mpv app, and mpv via termux stutter on bluetooth for me.

**Comment by tyzoid** [comment]
Adding `--audio-buffer .5` to increase the default buffer from 200ms to 500ms appears to resolve the issue.

**Comment by Neo-Oli** [comment]
Oh wow. That really does seem to help.

**Comment by Neo-Oli** [comment]
I created a pull request, which should enable that option by default. The man page states:

>This option should be used for testing only. If a non-default
>value helps significantly, the mpv developers should be
>contacted.

**Comment by Neo-Oli** [comment]
The  audio-buffer workaround resolves this issue for Termux. Although I hope this gets fixed upstream, so that the workaround can be removed again.
