### ISSUE TITLE
Unable to update packages. Connecting to some repos failing.

### ISSUE THREAD

**Issue by chiranjeevdas96** [termux/termux-packages#11287]
**running pkg update returns the following:**

> Checking availability of current mirror: bad
> Testing the available mirrors:
> [*] https://dl.bintray.com/termux/termux-packages-24: bad
> [*] https://grimler.se/termux-packages-24: bad
> [*] https://main.termux-mirror.ml/: bad
> [*] https://termux.mentality.rip/termux-packages-24: bad
> Using fallback mirror: https://termux.org/packages
> CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found
> CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found
> 0% [Working]

it is a fresh install in a device that never had termux installed before

**checked the repos manually by visiting each in a browser and pinging from within termux.**
_https://dl.bintray.com/termux/termux-packages-24_ returns "502 bad gateway"
_https://grimler.se/termux-packages-24_ works fine
_https://main.termux-mirror.ml_ redirects a bunch before ublock origin blocks it from loading a 'badware' page
_https://termux.mentality.rip/termux-packages-24_ works fine
_https://termux.org/packages_ works. redirects to https://packages.termux.dev/apt/termux-main/

assuming isp related issue tried different isps and vpns issues persist.
even with the issues, 2/4 repos and the fallback are reachable by browser on phone as well as other computers.

any help is appreciated

**Comment by 2096779623** [comment]
Download the latest version from [here](https://github.com/termux/termux-app#installation).

**Comment by sylirre** [comment]
https://github.com/termux/termux-app#installation

**Comment by chiranjeevdas96** [comment]
oh. thank you. maybe dev can add this as comment on the playstore.
will try the fdroid release.

**Comment by agnostic-apollo** [comment]
> maybe dev can add this as comment on the playstore.

Can you tell us where exactly on play store the dev should add the comment?

**Comment by chiranjeevdas96** [comment]
i apologise. there are indeed two notes pertaining to this description. 
as the notes are only visible upon opening the package page, scrolling down and clicking the 'About this app' section again, i had missed it thus far.

but case in point, since there are no plans to further support the playstore release, the fact that the package is deprecated in my opinion takes precedence over the one line description.

regardless, it was lack of due diligence on my part and i apologise once again.

**Comment by agnostic-apollo** [comment]
> as the notes are only visible upon opening the package page, scrolling down and clicking the 'About this app' section again

Not sure where else a dev can even put a note on playstore. You also missed pinned issue and link in bug report issue template.

But anyways, none of the active termux devs have access to playstore account, so we can't do anything. If we did have access, app would have been unpublished long ago. It is what it is.

And apology accepted.
