### ISSUE TITLE
Social engineering Toolkit In Termux

### ISSUE THREAD

**Issue by Techzindia** [termux/termux-packages#1128]
Hey! guys Any Chance To Run Setoolkit In Termux.

**Comment by Auxilus** [comment]
@Techzindia please comment in existing issue for SEToolkit and delete this issue https://github.com/termux/termux-packages/issues/1128

**Comment by Techzindia** [comment]
ok thanks for informing

**Comment by MVenkatesh1996** [comment]
frds have any chance to install social engineering tool in termux

**Comment by Wh1te5had0w** [comment]
_sis sitecloner working?_

**Comment by Muhaiminkp** [comment]
[Sorry. This feature is not yet supported in Windows or Metasploit was not found.]
I have installed Metasploit
Then  how to connect Metasploit path to set in trmux please help e
