### ISSUE TITLE
[Bug]: i have install x11-repo if i try downloading packeg in x11 repo it said package not found plz help me i try to change repo but it only all mirror asia mirror plz help

### ISSUE THREAD

**Issue by Baba01hacker69** [termux/termux-packages#11286]
### Problem description

Plz help me I try to download package from  x11 repo it said package not found but I have downloaded x11 repo its not with its with all packages plz help me and this also happens with root-repo plz help I try to change repo but it was showing world mirror asia mirror etc plz help

### What steps will reproduce the bug?

 I don't know how this happened but help me

### What is the expected behavior?

Cannot download frome other repo like x11 and root-repo I try to download all famous tool frome x11 and root repo like wireshark-gtk aircark-ng etc plz help me 

### System information

Termux info
Version:1.18.0
Download from fdorid 
Type=usr

**Comment by Grimler91** [comment]
`pkg update && pkg install x11-repo root-repo` should do it. Show some actual log output if that doesn't work
