### ISSUE TITLE
crunch for termux #981

### ISSUE THREAD

**Issue by themastersunil** [termux/termux-packages#1129]
anyone can solve this issue????

**Comment by themastersunil** [comment]
This issue is solved. Run command excecute..
apt update && upgrade 
apt install pip
pip install wordlist

**Comment by azadoraha** [comment]
pip not found in pkg

**Comment by Hax4us** [comment]
There is no any separate package for pip just install python 3 by `apt install python`
If you want Python 2 so just `apt install python2` 
Then you can use `pip` from python 3 and `pip2` from python2 :)
