### ISSUE TITLE
[Bug]:  error when connecting to sshd for sftp connection.

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#11296]
### Problem description

When connecting to termux sshd server for sftp service I get the following error:-

`sftp -P8022 user@192.168.1.100
Received message too long 169876315
Ensure the remote shell produces no output for non-interactive sessions.`

Found the following fix on internet:-

Configure your server to use the internal sftp server adding the following directive to /etc/ssh/sshd_config:

Subsystem sftp internal-sftp

That way, it will not use the user shell to launch the sftp server program.

### What steps will reproduce the bug?

sftp into termux with sshd active.

### What is the expected behavior?

Connect ok.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=11974
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.mwt.me/termux/x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://mirror.mwt.me/termux/root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.21
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Fri Sep 17 17:16:18 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003

```

**Comment by Grimler91** [comment]
It's related to the new motd message from https://github.com/termux/termux-packages/pull/11250, maybe sftp doesn't like escape sequences in the motd.

Silencing the motd message with `touch ~/.hushlogin` makes `PREFIX/libexec/sftp-server` work again

**Comment by macerg** [comment]
Ok, thanks for the information.On 20 Jul 2022 20:56, Henrik Grimler ***@***.***> wrote:
It's related to the new motd message from #11250, maybe sftp doesn't like escape sequences in the motd.
Silencing the motd message with touch ~/.hushlogin makes PREFIX/libexec/sftp-server work again

**Comment by sylirre** [comment]
For `rsync` there similar issue was reported on Reddit: https://www.reddit.com/r/termux/comments/w3jr96/comment/igx2ktl/

We need a proper way for checking whether shell is non-interactive instead of relying on arguments count. Here is what we have currently in login script:
```
if [ $# = 0 ] && [ -f @TERMUX_PREFIX@/etc/motd ] || [ -f @TERMUX_PREFIX@/etc/motd.sh ] && [ ! -f ~/.hushlogin ] && [ -z "$TERMUX_HUSHLOGIN" ]; then
```

**Comment by sylirre** [comment]
The fix will be available in termux-tools update v1.22.

**Comment by macerg** [comment]
Thanks, great work team!

**Comment by macerg** [comment]
Still problems after update:-
`u0_a247@localhost:~$ apt search termux-tools
Sorting... Done
Full Text Search... Done
termux-tools/stable,stable,now 1.21 all [installed]
  Basic system tools for Termux

u0_a247@localhost:~$ sftp -P8022 user@localhost
Received message too long 169876315
Ensure the remote shell produces no output for non-interactive sessions.`

**Comment by macerg** [comment]
That's fixed it, thanks!
