### ISSUE TITLE
[Package]: Homebridge

### ISSUE THREAD

**Issue by brainstorm** [termux/termux-packages#11293]
### Package description

Homebridge is a lightweight NodeJS server you can run on your home network that emulates the iOS HomeKit API. It supports Plugins, which are community-contributed modules that provide a basic bridge from HomeKit to various 3rd-party APIs provided by manufacturers of "smart home" devices.

### Home page URL

https://homebridge.io/

### Source code URL

https://github.com/homebridge/homebridge

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Has some packaging work done for Debian here: https://github.com/homebridge/homebridge-apt-pkg

**Comment by sylirre** [comment]
`npm i -g homebrigde` installs it successfully.

![Screenshot_20220721-101230](https://user-images.githubusercontent.com/107305601/180152600-29eee10b-8c44-4a63-9e37-b19025dd8b7f.png)

**Comment by sylirre** [comment]
Don't upgrade `npm` installed with `nodejs` package. If you do so, patches applied during Termux packaging will be discarded and you will get the mentioned `EACCES` error.
