### ISSUE TITLE
[Bug]: New motd breaks rsync

### ISSUE THREAD

**Issue by Eskuero** [termux/termux-packages#11297]
### Problem description

Since the new motd upgrade (https://github.com/termux/termux-packages/commit/4334a09875febdf913d22c775844998de809b18c) I can't rsync succesfully from my tablet to my desktop as I used to (this is just to pull the Downloads folder in the internal storage)

```
[eskuero@4cx4 ~]$ rsync -a tablet:storage/shared/Download/ $HOME/Backup/Downloads/
protocol version mismatch -- is your shell clean?
(see the rsync manpage for an explanation)
rsync error: protocol incompatibility (code 2) at compat.c(608) [Receiver=v3.2.4]
```
I renamed the motd script so it uses the old one (according to the check at https://github.com/termux/termux-packages/blob/master/packages/termux-tools/login#L5) and it started working again.

`.../usr/etc $ mv motd.sh motd.sh.bak`

### What steps will reproduce the bug?

1. Have the new motd
2. Try to rsync any folder

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.21
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22626479 #1 SMP PREEMPT Wed Feb 16 19:15:27 +07 2022 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T510
```

**Comment by sylirre** [comment]
Fixed in termux-tools v1.22.
