### ISSUE TITLE
[Bug]: unicorn new version build failed for [arm+i686]

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11303]
### Problem description

[unicorn-arm-log.txt](https://github.com/termux/termux-packages/files/9155692/unicorn-arm-log.txt)
[unicorn-i686-log.txt](https://github.com/termux/termux-packages/files/9155693/unicorn-i686-log.txt)

### What steps will reproduce the bug?

build new version

### System information

termux docker on ubuntu 21

**Comment by sylirre** [comment]
Fixed.
