### ISSUE TITLE
WireShark Installation and running on termux

### ISSUE THREAD

**Issue by JaDugarALi** [termux/termux-packages#1131]
have any one tried installing wireshark in termux

**Comment by Auxilus** [comment]
@JaDugarALi There isbbit of a problem , WireShark uses wifi card , on Android we don't have that , if @vishalbiswas can configure WireShark to use wifi module in android then we might be able to run it ..

**Comment by Auxilus** [comment]
I tried @jadugarali , didn't succeeded

**Comment by cr4shcod3** [comment]
Only in GNURoot Debian. You can apt-get install wireshark

**Comment by cr4shcod3** [comment]
And also. to start the gui program you need to run it on LXDE server. There is a tutorial about installing it.

**Comment by Auxilus** [comment]
@JaDugarALi tshark which is terminal version of Wireshark can be installed once https://github.com/termux/termux-packages/pull/1681 is merged

**Comment by xeffyr** [comment]
thask is already available in termux-root-packages: https://github.com/termux/termux-root-packages/tree/master/packages/tshark

**Comment by Yisus7u7** [comment]
Hello, wireshark does not read me any packets tcp, udp, etc..., and apart, why not bring the option to analyze WiFi?

**Comment by xeffyr** [comment]
@Yisus7u7 Device must be rooted and wireshark should be running under `tsu`.

**Comment by Yisus7u7** [comment]
Hmmm, I didn't know, but then for one not to get confused should move it to root repo
![Screenshot_20210224-104115](https://user-images.githubusercontent.com/64093255/109026326-a07dd700-768d-11eb-9dab-8aae508ee2d8.png)

**Comment by xeffyr** [comment]
> then for one not to get confused should move it to root repo

Confusing only for those who DOES NOT have experience with these packages and in general never had experience with normal Linux distributions. I really don't care about such cases.

Wireshark by itself is X11 graphical package and root here is only needed for capturing traffic. Analyzing existing pcap files does not require root. Moving it to root packages will cause dependency issues (supplementary repositories like root-repo or x11-repo do not share each other) as well as ownership issues (root-repo and x11-repo have different hostings).

`bash` and `coreutils` are restricted without root, e.g. you can't do `ls /data` or `rm /system/app/Bloatware/Bloatware.apk` without root. But restricted usage is not a reason to move package into root-repo. Btw root-repo already has `tshark`, which is a headless wireshark build.
