### ISSUE TITLE
[Bug]: I can't able to update my package on termux.

### ISSUE THREAD

**Issue by Kishore750** [termux/termux-packages#11322]
### Problem description

![Screenshot_20220722_192109](https://user-images.githubusercontent.com/85425535/180454125-6497af9b-9926-4124-997a-a9f137360681.jpg)
I can't able to upgrade or update packages.It shows  [Possible cause: repository is under maintenance or down (wrong sources.list URL?).]
Like this.I try to install ubuntu on termux but I can't 

### What steps will reproduce the bug?

Please help me 

### System information

termux-info:

```

```
Checking availability of current mirror: ok       Get:1 https://grimler.se/termux-packages-24 stable InRelease [16.8 kB]
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:1 https://grimler.se/termux-packages-24 stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  502  Bad Gateway                                Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release                              502  Bad Gateway                                Reading package lists... Done
W: GPG error: https://grimler.se/termux-packages-24 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B
E: The repository 'https://grimler.se/termux-packages-24 stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

**Comment by 2096779623** [comment]
> Google Play Store distribution source is deprecated and shouldn't be used anymore.

You'll need to uninstall it and proceed with installation instructions shown there: https://github.com/termux/termux-app#installation

**Comment by licy183** [comment]
Checkout https://github.com/termux/termux-packages/issues/6726, or download newer version of termux from F-Droid/Github Release.
