### ISSUE TITLE
[Bug]: pip install orjson -> feature `edition2021` is required

### ISSUE THREAD

**Issue by araczkowski** [termux/termux-packages#11321]
### Problem description

orjson and maturin can't be installed via pip

### What steps will reproduce the bug?

```
pip install orjson
pip install maturin
```

the error is
> feature `edition2021` is required

### What is the expected behavior?

```
pip install orjson
pip install maturin
```
succes installation

### System information

termux-info:

```
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.113 #1 SMP PREEMPT Mon Apr 26 09:09:55 UTC 2021 armv7l Android
Device manufacturer:
AI-Speaker
Device model:
AIS-PRO1

```

**Comment by licy183** [comment]
I cannot reproduce it. What is your version of rust? Run `apt update && apt upgrade` to install the latest version of rust and try something like `CARGO_BUILD_TARGET=aarch64-linux-android pip install maturin`.

**Comment by araczkowski** [comment]
thanks @licy183 after upgrade ```pip install maturin``` works :+1: 
but I can't build wheel

```
CARGO_BUILD_TARGET=aarch64-linux-android pip wheel maturin -w wheels
```

the error is:
```
error occurred: Failed to find tool. Is `aarch64-linux-android-ar` installed?
```

any idea how to solve this? thanks

**Comment by 2096779623** [comment]
> thanks @licy183 after upgrade `pip install maturin` works 👍 but I can't build wheel
> 
> ```
> CARGO_BUILD_TARGET=aarch64-linux-android pip wheel maturin -w wheels
> ```
> 
> the error is:
> 
> ```
> error occurred: Failed to find tool. Is `aarch64-linux-android-ar` installed?
> ```
> 
> any idea how to solve this? thanks

`pkg i binutils`

**Comment by araczkowski** [comment]
Successfully built maturin, Successfully built orjson

thank you @2096779623

**Comment by codemona** [comment]
Please add this packages to termux because building this package using this comand make my phone slow and it takes lots of time building.
```
CARGO_BUILD_TARGET=aarch64-linux-android pip install maturin
```

**Comment by urbanonymous** [comment]
For the newbie that wants to install fastapi in termux

pkg i python
pkg i rust
pkg i binutils
CARGO_BUILD_TARGET=aarch64-linux-android pip wheel maturin -w wheels

then

pip install orjson
pip install maturin
pip install fastapi
