### ISSUE TITLE
[Bug]: x265 missing acceleration on aarch64?

### ISSUE THREAD

**Issue by Randrianasulu** [termux/termux-packages#11334]
### Problem description

Because termux packages x265 3.5 I think it misses some cpu acceleration merged in x265 master per this bugreport

https://bitbucket.org/multicoreware/x265_git/issues/563/patch-neon-arm64-improvements

### What steps will reproduce the bug?

X265 per se works

### What is the expected behavior?

X265 works faster

### System information

termux-info:

```
$ termux-info
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=25224
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb http://mirror.mephi.ru/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb http://mirror.mephi.ru/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.23
Android version:
11
Kernel build information:
Linux localhost 4.14.193 #1 SMP PREEMPT Thu Jul 8 13:58:00 CST 2021 aarch64 Android
Device manufacturer:
DEXP
Device model:
K38
```

I actually build x265 with patch from https://github.com/Vargol/ffmpeg-apple-arm64-build on aarch64 device but not tested it ...without this patch vanilla sources fail. Termux patches x265 but as far as I can see does not add new asm files.

**Comment by licy183** [comment]
It seems that `libx265` in termux has disabled assembly (https://github.com/termux/termux-packages/blob/3958def066e6cf2ce8aab9f8f318ec06b6bde493/packages/libx265/build.sh#L32). I will try to work on this.

**Comment by jeevatattva** [comment]
> It seems that `libx265` in termux has disabled assembly (
> 
> https://github.com/termux/termux-packages/blob/3958def066e6cf2ce8aab9f8f318ec06b6bde493/packages/libx265/build.sh#L32
> 
> ). I will try to work on this.

Assembly code is disabled for `arm` architecture, check https://github.com/termux/termux-packages/issues/7586, and not for `aarch64`. In issue above, the target platform is `aarch64`. You can just look into those Apple `arm64` patches for improved performance. I use the patch-set for building static `ffmpeg` on `termux`.

**Comment by truboxl** [comment]
I guess we can cherry pick the patch https://bitbucket.org/multicoreware/x265_git/commits/4bf31dc15fb6d1f93d12ecf21fad5e695f0db5c0 since it got merged as noted in https://bitbucket.org/multicoreware/x265_git/issues/563/patch-neon-arm64-improvements ...

Or we wait for next release...
