### ISSUE TITLE
OSIF tool data fetching issue and traceback 

### ISSUE THREAD

**Issue by Irtija123456** [termux/termux-packages#11332]
### Package description

osif github tool is a social media information gathering tool which was made to gather someones sensitive  information such as email or phone number. But for some times, it isn't working as it should. An unusual error is occurring while using the "osif" tool. For say if I give a command get_data or dump_id or phones it is working smoothly. Rather it stops in the midway showing traceback file no 1204 and "error" failed to fetch all friends data. This error occurs each and every time I give any of theirs commands. I think there is a algorithm problem inside the tool or it doesn't work any longer. I think it is not capable of collecting data from newly published websites or due to the strong security chain system of the social media sites. So the tool needs an update to work smoothly and fetch the required data.

### Home page URL

https://github.com/ciku370/OSIF

### Source code URL

 CiKu370/OSIF

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I hope this problem will be solved sooner but surely. 

osif github tool is a social media information gathering tool which was made to gather someones sensitive  information such as email or phone number. But for some times, it isn't working as it should. An unusual error is occurring while using the "osif" tool. For say if I give a command get_data or dump_id or phones it is working smoothly. Rather it stops in the midway showing traceback file no 1204 and "error" failed to fetch all friends data. This error occurs each and every time I give any of theirs commands. I think there is a algorithm problem inside the tool or it doesn't work any longer. I think it is not capable of collecting data from newly published websites or due to the strong security chain system of the social media sites. So the tool needs an update to work smoothly and fetch the required data.

**Comment by Irtija123456** [comment]
Yes it's a big problem

**Comment by zairullahdev** [comment]
https://wiki.termux.com/wiki/Hacking

Get this closed mods

**Comment by sylirre** [comment]
@Irtija123456 

This is a packaging policy violation.

There is a reason why we require everyone to read https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy and click checkbox if agree. This isn't going to be packaged.

I'm going to delete this issue, not sure if my reply copy will be on your email.
