### ISSUE TITLE
[Bug]: ripgrep-all x64 failure

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11343]
### Problem description

[ripgrep-all_x64.txt](https://github.com/termux/termux-packages/files/9175918/ripgrep-all_x64.txt)

### What steps will reproduce the bug?

build package

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
First rust package that is affected by https://github.com/android/ndk/issues/1614 it seems. At least it is detected during compilation and not just runtime
