### ISSUE TITLE
[Bug]: jbig2enc arm build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11345]
### Problem description

[jbig2enc-arm.txt](https://github.com/termux/termux-packages/files/9176014/jbig2enc-arm.txt)

### What steps will reproduce the bug?

build package for arm

### System information

termux-info:

```

```

**Comment by ALSULTAN** [comment]
modifying the build.sh as below should fix it:


```
termux_step_pre_configure() {
	sh autogen.sh
	if [ $TERMUX_ARCH = arm ]; then
		LDFLAGS+=" $("$CC" -print-libgcc-file-name)"
	fi
}
```

**Comment by johndebia2022** [comment]
Greet @ALSULTAN fixed
