### ISSUE TITLE
[Bug]: golang buildmode plugin not supported on android/arm64

### ISSUE THREAD

**Issue by mayef** [termux/termux-packages#11351]
### Problem description

https://pkg.go.dev/cmd/go#hdr-Build_modes

![image](https://user-images.githubusercontent.com/58973492/180731350-2e1349d7-dbd3-498c-8b38-490e90d4c4bb.png)

### What steps will reproduce the bug?

just run 
`go build -buildmode=plugin your_go_file.go`

### What is the expected behavior?

run the command above successfully, and produce a binary file 'your_go_file.so'

### System information

termux-info: 0.118.0 on Android 10
golang/stable: 1.18.3

**Comment by sylirre** [comment]
This should be asked on upstream. `android` GOOS target may not support the all Golang compiler features.

Can be reopened if that will be confirmed to be a bug on Termux side.
