### ISSUE TITLE
[Bug]: gimp build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11357]
### Problem description

[gimp.txt](https://github.com/termux/termux-packages/files/9187126/gimp.txt)

### What steps will reproduce the bug?

build pkg

### System information

termux-info:

```

```

**Comment by 2096779623** [comment]
https://github.com/2096779623/termux-packages/runs/7514768094?check_suite_focus=true

https://github.com/2096779623/termux-packages/blob/fix-issues-11357/x11-packages/gimp/build.sh

```bash

(glib-compile-resources:13177): GLib-GIO-CRITICAL **: 06:53:39.006: g_subprocess_wait: assertion 'G_IS_SUBPROCESS (subprocess)' failed

(glib-compile-resources:13177): GLib-GObject-CRITICAL **: 06:53:39.006: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gimp-color-picker-cursors.gresource.xml: Failed to close file descriptor for child process (Operation not permitted).

(glib-compile-resources:13176): GLib-GIO-CRITICAL **: 06:53:39.007: g_subprocess_wait: assertion 'G_IS_SUBPROCESS (subprocess)' failed

(glib-compile-resources:13176): GLib-GObject-CRITICAL **: 06:53:39.007: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gimp-tool-cursors.gresource.xml: Failed to close file descriptor for child process (Operation not permitted).
make[2]: *** [Makefile:937: gimp-tool-cursors.c] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:958: gimp-color-picker-cursors.c] Error 1
make[2]: Leaving directory '/home/builder/.termux-build/gimp/build/cursors'
make[1]: *** [Makefile:856: all-recursive] Error 1
make[1]: Leaving directory '/home/builder/.termux-build/gimp/build'
make: *** [Makefile:757: all] Error 2
Error: Process completed with exit code 2.
```

https://gist.github.com/nathabonfim59/b088db8752673e1e7acace8806390242

Why ???🤔

Is it a Docker problem?

**Comment by licy183** [comment]
I have just updated the `profile.json`. Please check if this issue exists or not. Thanks!

**Comment by 2096779623** [comment]
> I have just updated the `profile.json`. Please check if this issue exists or not. Thanks!

Still exists.

https://github.com/2096779623/termux-packages/actions/runs/2737916314

**Comment by licy183** [comment]
> > I have just updated the `profile.json`. Please check if this issue exists or not. Thanks!
> 
> Still exists.
> 
> https://github.com/2096779623/termux-packages/actions/runs/2737916314

Maybe we need to disable `seccomp`, which needs more discussion.

What will happen if we don't update `gimp` to `2.10.32`?

**Comment by 2096779623** [comment]
> Maybe we need to disable `seccomp` for docker, which needs more discussion.

If disabled `seccomp`, it will work.
https://github.com/2096779623/termux-packages/runs/7516482823?check_suite_focus=true

**Comment by ifurther** [comment]
It is similar this error [moby/moby#43595](https://github.com/moby/moby/issues/43595#issue-1235100312)
