### ISSUE TITLE
[Bug]: Using lychee without root

### ISSUE THREAD

**Issue by buddhist-uni** [termux/termux-packages#11352]
### Problem description

Running `lychee` on my non-rooted device yields:

```
Error: Failed to create request client

Caused by:
    0: Network error
    1: builder error: error reading DNS system conf: No such file or directory (os error 2)
    2: error reading DNS system conf: No such file or directory (os error 2)
```

### What steps will reproduce the bug?

1. Have a non-rooted termux
2. `pkg install lychee`
3. `lychee somelinks.txt`

### What is the expected behavior?

It pings the links

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=23262
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.nscdn.top/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.23
Android version:
12
Kernel build information:
Linux localhost 4.14.190-perf-24274428-abA725FXXU4BVE3 #1 SMP PREEMPT Mon May 16 14:04:18 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A725F
```

**Comment by buddhist-uni** [comment]
Any ideas, @thunder-coding ?

**Comment by 2096779623** [comment]
> Any ideas, @thunder-coding ?

Shh, don't bother him.

https://github.com/termux/termux-packages/discussions/11221

**Comment by thunder-coding** [comment]
Maybe an error caused by some library used by lychee. A candidate for upstream reporting once the root of the issue is found

**Comment by thunder-coding** [comment]
It seems to be a candidate for upstream reporting. I'll handle this, so that my programming skills don't get rust in these 2 years :)

**Comment by thunder-coding** [comment]
It seems like the OpenSSL crate locked by Cargo.lock for lychee is broken. Updating deps, and building seems to work pretty well. Probably the next update should come with new dependencies.

Even the master branch of lychee is broken, as it seems to come with a broken OpenSSL crate. Hope that helps. I'm not going to fix this, will wait for a new version of lychee to be released which will hopefully come with newer crates. In case you want this to be fixed, ask upstream to release new version of send PR yourself

**Comment by buddhist-uni** [comment]
I see... Thankfully they're updating fairly regularly these days, so I'll just wait for v0.11 (v1.0?)

Thanks for looking into it, and sorry for disturbing your studies! If you fail your entrance exams, you're always welcome at OBU ;)
