### ISSUE TITLE
[Bug]: `ssh termux -- tmux a` return an error: "no server running on /data/data/com.termux/files/usr/tmp/tmux-10064/default"

### ISSUE THREAD

**Issue by cnst** [termux/termux-packages#11354]
### Problem description

When trying to `ssh` into a new Termux installation with `-- tmux a` passed as the command line arguments to `ssh`, I'm getting the following error:

```
% ssh -t 192.168.43.16 -p 8022 -oHostKeyAlias=Termux_CB_20220722 -- tmux ls
no server running on /data/data/com.termux/files/usr/tmp/tmux-10064/default
Connection to 192.168.43.16 closed.
```

I've tracked this to being a regression from about 9 months ago from https://github.com/termux/termux-packages/commit/f8e73d466068c8eb2b5c4e44a663a5c38374e1cf#diff-a1b9af0962ea7d9ffc1a977faa1f4886f7cff0d71e401babfcca7ae6258446ebR26

### What steps will reproduce the bug?

Within a running `tmux` instance, the following confirms the presence of the bug:

```
% unset TMUX{,_TMPDIR}
% sh -c 'tmux ls'
no server running on /data/data/com.termux/files/usr/tmp/tmux-10064/default
% sh -l -c 'tmux ls'
0: 4 windows (created Mon Jul 25 11:41:37 2022) (attached)
% sh -c 'tmux ls'
no server running on /data/data/com.termux/files/usr/tmp/tmux-10064/default
% ll ../usr/tmp/tmux-10064/default ../usr/var/run/tmux-10064/default
srw-rw---- 1 u0_a64 u0_a64 0 Jul 25 15:11 ../usr/tmp/tmux-10064/default
srwxrwx--- 1 u0_a64 u0_a64 0 Jul 25 11:41 ../usr/var/run/tmux-10064/default
%
```

Refer to [`session.c::do_child()` in OpenSSH](http://bxr.su/o/usr.bin/ssh/session.c#do_child) for the explanation of how OpenSSH executes the login shell vs. the supplied command:

```
1387    /*
1388     * Execute the command using the user's shell.  This uses the -c
1389     * option to execute the command.
1390     */
1391    argv[0] = (char *) shell0;
1392    argv[1] = "-c";
1393    argv[2] = (char *) command;
1394    argv[3] = NULL;
```

### What is the expected behavior?

With an `unset TMUX{,_TMPDIR}`, there should be no difference between:

* `sh -c 'tmux ls'`
* `sh -l -c 'tmux ls'`

Both should work, regardless whether or not `-l` is provided.  Otherwise, `ssh termux -- tmux a` won't work.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=2455
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64

Device manufacturer:
Google
Device model:
jacuzzi
```

**Comment by tomty89** [comment]
We may consider patching [this line](https://github.com/tmux/tmux/blob/3.3a/tmux.h#L77). The thing is, can you `tmux a` *anyway*? I always get:
```
open terminal failed: not a terminal
```
if I try to run it "remotely".

**Comment by cnst** [comment]
The "not a terminal" error is because `ssh` does not allocate the pseudo-terminal by default when you try to run a command remotely; that's why both me and the prior OP are using the `-t` option of [`ssh(1)`](http://mdoc.su/o/ssh.1#t).

**Comment by tomty89** [comment]
Okay, but then when I use `-t`, I cannot seem to  reproduce the problem you've bumped into:
```
$ ssh -p 2222 127.0.0.1 -- printenv TMUX_TMPDIR                            $ ssh -t -p 2222 127.0.0.1 -- printenv TMUX_TMPDIR
/data/data/com.termux/files/usr/var/run
Connection to 127.0.0.1 closed.
$ (unset TMUX_TMPDIR; ssh -t -p 2222 127.0.0.1 -- printenv TMUX_TMPDIR)
/data/data/com.termux/files/usr/var/run
Connection to 127.0.0.1 closed.
```
The ssh server was even started with:
```
(unset TMUX_TMPDIR; sshd -p 2222)
```

Not that I oppose we switch to the patch approach though.

**Comment by tomty89** [comment]
I have a clue why it doesn't work for you now. It's true that normally env var exported with profile.d script will not be available for ssh-run commands. However, `login` is apparently always run in the process, and in Termux, `login` is a script starts a shell (we don't have all the PAM / user session whatsoever stuff):

https://github.com/termux/termux-packages/blob/26e9f91517758d5862235f8cecf9de01997a5d7d/packages/termux-tools/login#L49-L53

I don't know why it doesn't work for you exactly though. Maybe it's because the shell you use doesn't treat / support `-l` like the others? Or perhaps you are not using this `login` for some reason?
