### ISSUE TITLE
[Bug]: clang package does not provide versioned symlink for clang++

### ISSUE THREAD

**Issue by Oblomov** [termux/termux-packages#11366]
### Problem description

The clang package provides clang-NN (with NN being the version, e.g. 14 currently) as a binary and several symlinks including clang and clang++. However, no versioned clang++ (e.g. clang++-14) symlink is provided. Some building environments assume that it should be present.

### What steps will reproduce the bug?

 ```
$ ls $(command -v clang)++*
/data/data/com.termux/files/usr/bin/clang++
```

### What is the expected behavior?

The command should list the versioned symlink too 

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5080
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.aliyun.com/termux/termux-packages-24 stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.aliyun.com/termux/x11-packages x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.23
Android version:
11
Kernel build information:
Linux localhost 4.14.113-user+ #1 SMP PREEMPT Sun Apr 24 11:48:44 CDT 2022 aarch64 Android
Device manufacturer:
motorola
Device model:
motorola one vision
```

**Comment by licy183** [comment]
I think such a symlink can be added when next release of llvm is bumped.

**Comment by Oblomov** [comment]
Sure, no problem. BTW, if I'm not mistaken clang 15 was branched a few days ago.

**Comment by buttaface** [comment]
Can you give an example of a project that needs this, ie where did you run into this problem? I know that the Ubuntu clang package adds this versioned symlink because it allows installing multiple clang versions, which we don't, and if LLVM itself doesn't, I'm skeptical of just doing it because of that.

**Comment by Oblomov** [comment]
GPUSPH, when asked to build explicitly with clang, will use the versioned symlink.

**Comment by buttaface** [comment]
[I don't see any indication of that](https://github.com/GPUSPH/gpusph/search?q=clang), do you know where in their build config? Does that even work on Android, as I don't think CUDA is available?

**Comment by Oblomov** [comment]
Sorry, I should have specified. The possibility to build with Clang and without CUDA (and on Android in Termux) part is in a branch that has not been integrated in master. [Here's a link to the relevant part of the Makefile in the correct branch](https://github.com/GPUSPH/gpusph/blob/spheric2022/Makefile#L353).

**Comment by buttaface** [comment]
Alright, I don't think this is generally useful, but I'll look into adding it when we bump clang for the NDK 25 update, #11422.
