### ISSUE TITLE
Can't install tiger vnc

### ISSUE THREAD

**Issue by krisdowis** [termux/termux-packages#11362]
I can't install tigervnc and other x11 packages e.g xcfe4 lxqt etc.

I already tried the following 

Changing repo
Changing mirrors
Changing source list
Updating apt

![Screenshot_20220727-093105_Termux.jpg](https://user-images.githubusercontent.com/81590267/181201810-75970851-c0c4-4414-9094-b77f4ef89c43.jpg)![Screenshot_20220727-093059_Termux.jpg](https://user-images.githubusercontent.com/81590267/181201871-c1eb10c6-53a7-4fb6-84e0-86f4bc91c80e.jpg)![Screenshot_20220727-092141_Termux.jpg](https://user-images.githubusercontent.com/81590267/181201937-0617c576-722e-4a43-afe7-4f0e60500e46.jpg)

**Comment by 2096779623** [comment]
`termux-info` plz.

**Comment by Sardarfarhan** [comment]
Price Ka ha packages
Ke

**Comment by zairullahdev** [comment]
Edit `$PREFIX/etc/apt/sources.list` into 

```
deb https://grimler.se/termux-packages-24 stable main
```

**Comment by OrdinaryEnder** [comment]
> Edit `$PREFIX/etc/apt/sources.list` into
> 
> ```
> deb https://grimler.se/termux-packages-24 stable main
> ```

It should be

```
deb https://grimler.se/termux-packages-24 stable main
```

**Comment by wmcbtech30** [comment]
ditto

**Comment by 2096779623** [comment]
Why can't you `pkg rei x11-repo` so it doesn't break the main repo.

**Comment by zairullahdev** [comment]
welp it's just remove the repo text and readd

**Comment by zairullahdev** [comment]
Oops ur got it wrong buddy

**Comment by zairullahdev** [comment]
It should
```
deb https://grimler.se/termux-packages-24 stable X11
```

**Comment by OrdinaryEnder** [comment]
No there's no x11 repo in grimlers repo, is it removed?

**Comment by OrdinaryEnder** [comment]
Maybe tryna reset ur termux?

**Comment by OrdinaryEnder** [comment]
I got tigervnc in here

**Comment by OrdinaryEnder** [comment]
![Screenshot_2022_0727_162834](https://user-images.githubusercontent.com/109149031/181213286-a5c5a601-181c-4038-8a4d-2b5f8b12b814.png)

**Comment by wmcbtech30** [comment]
`termux-change-repo` maybe sufficient enough. try changing repos and run `pkg install tigervnc`?

**Comment by krisdowis** [comment]
> `termux-info` plz.

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=23324
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
Updatable packages:
All packages up to date
termux-tools version:
1.23
Android version:
12
Kernel build information:
Linux localhost 4.14.186-24084238 #1 SMP PREEMPT Sat Jun 11 00:24:57 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A315F

```

**Comment by krisdowis** [comment]
> `termux-change-repo` maybe sufficient enough. try changing repos and run `pkg install tigervnc`?

I tried didn't work

**Comment by krisdowis** [comment]
> No there's no x11 repo in grimlers repo, is it removed?



Yes there is no tigervnc in grinler repo don't waste your time 
I already tried

**Comment by krisdowis** [comment]
> It should
> ```
> deb https://grimler.se/termux-packages-24 stable x11
> ```

It didn't work

**Comment by krisdowis** [comment]
> > Why can't you `pkg rei x11-repo` so it doesn't break the main repo.
> 
> This worked perfectly 🥰  
> Thanks

Now I can install all root packages including lxqt and others

**Comment by krisdowis** [comment]
I will be closing issue as it has been solved 

![Screenshot_20220727-173610_Termux.jpg](https://user-images.githubusercontent.com/81590267/181301848-7f7a7f10-12e7-4c6a-9ee5-d3320978de12.jpg)

Use `pkg rei x11-repo`
