### ISSUE TITLE
Encoding issue(?) åäö displayed as ''$'\303\245\303\244\303\266'

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#1136]
I'm not sure which update introduced this but I just noticed that files with none english characters in the name look weird.

Try 

```
touch åäö
ls åäö
```

And you'll see this: 
![image](https://user-images.githubusercontent.com/18900601/28239754-480136ce-6973-11e7-87ca-9cba1f18b4a5.png)

**Comment by Neo-Oli** [comment]
I'm also seeing this. Seems to be an issue with coreutils, as busybox ls shows it correctly.

**Comment by fornwall** [comment]
Should be fixed now after the latest coreutils update.

There might be some more problems like this scattered after the big recent changes:

- Transition to unified headers.
- Putting libandroid-support on a diet.
- The libc++ update.

Just keep reporting them so we iron them out!
