### ISSUE TITLE
Npm install sqlite3 fails

### ISSUE THREAD

**Issue by TAUFEEQ1** [termux/termux-packages#1137]
running npm install sqlite3 fails.Help would be appreciated

**Comment by TAUFEEQ1** [comment]
Upgrading to newer version of node returns this after upgrade
node
CANNOT LINK EXECUTABLE DEPENDENCIES: library "libc++_shared.so" not found

**Comment by fornwall** [comment]
Run `pkg update` to update to latest version of all packages. Does that make node work again?

**Comment by TAUFEEQ1** [comment]
after updating packages,node works,however gyp seems to require python2
inorder to install sqlite3 driver.

**Comment by fornwall** [comment]
@TAUFEEQ1 Ok, great!

So after installing python2 it works with `npm install sqlite3`?

**Comment by TAUFEEQ1** [comment]
Yes,it works...its time we closed this issue. Thank you for your help
On Jul 16, 2017 15:44, "Fredrik Fornwall" <notifications@github.com> wrote:

@TAUFEEQ1 <https://github.com/taufeeq1> Ok, great!

So after installing python2 it works with npm install sqlite3?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/termux/termux-packages/issues/1137#issuecomment-315606788>,
or mute the thread
