### ISSUE TITLE
[Bug]: repository is under maintenance or down (wrong sources.list URL?).

### ISSUE THREAD

**Issue by obeythesystem** [termux/termux-packages#11378]
### Problem description

I can't even update. 
It's been 2 days since i install termux and I can't even update to use it properly 

### What steps will reproduce the bug?

I don't know

### What is the expected behavior?

To run it properly 

### System information

termux-info:

```

```
repository is under maintenance or down (wrong sources.list URL?).

**Comment by 2096779623** [comment]
Please provide log or screenshot, and `termux-info`.

**Comment by obeythesystem** [comment]
![Screenshot_20220729_103725](https://user-images.githubusercontent.com/74136283/181671254-2445c076-38c8-4137-9072-97879d585aad.jpg)
Look

**Comment by 2096779623** [comment]
> ![Screenshot_20220729_103725](https://user-images.githubusercontent.com/74136283/181671254-2445c076-38c8-4137-9072-97879d585aad.jpg) Look

Download the latest version of Termux [here](https://github.com/termux/termux-app#installation).

**Comment by obeythesystem** [comment]
Thank you bro it works
