### ISSUE TITLE
Segmentation fault findutils/stable,now 4.6.0-2 aarch64

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1138]
Segmentation faults after last update abound. 
![screenshot_20170715-212654](https://user-images.githubusercontent.com/27742457/28243764-72939cc0-69a4-11e7-91ca-cd6322f55d90.png)

```
$ find . -name AndroidManifes

[2]+  Stopped                 find . -name AndroidManifes
$ fg
bash: fg: job has terminated
[2]+  Segmentation fault      find . -name AndroidManifes
$ find . -name Andro

[2]+  Stopped                 find . -name Andro
$ fg
bash: fg: job has terminated
[2]+  Segmentation fault      find . -name Andro
```

These segmentation faults in find have affected the successful builds on https://github.com/sdrausty/buildAPKs for example https://github.com/sdrausty/buildAPKs/blob/master/scripts/buildOne.sh

```
Writing symbols for class R.
ecj begun
Segmentation fault
Eclipse Compiler for Java(TM) v20161117-1814, 3.12.2
```
Which seg faults at:
```
echo "ecj begun"
ecj -d ./obj -classpath $HOME/../usr/share/java/android.jar \
	     -sourcepath ./app/src $(find src -type f -name "*.java")
```

Needless to say https://github.com/sdrausty/buildAPKs/blob/master/scripts/buildAll.sh which uses find exclusively seg faults now too. It was amazing watching it build hundreds of APKs on device. 

Can someone fix `find` please?
findutils/stable,now 4.6.0-2 aarch64 [installed]
OS: Android 6.0.1 aarch64

**Comment by Neo-Oli** [comment]
Seeing this too with the command `find $HOME -type f -not -path "$HOME/bin"`. It's very annoying. A great number of scripts have stopped working.

**Comment by fornwall** [comment]
Can you update and verify that it works now (libandroid-support v20 should fix the problem)?

**Comment by sdrausty** [comment]
@fornwall  Thanks for the quick fix😀

**Comment by kcroshan682** [comment]
Segmentation fault 
After reinstalling
