### ISSUE TITLE
[Package]: hexer

### ISSUE THREAD

**Issue by ywx** [termux/termux-packages#11397]
### Package description

Hexer is an interactive binary editor (also known as a hexeditor) with a Vi-like interface. Its most important features are multiple buffers, multi-level undo, command-line editing with completion, and binary regular expressions.

### Home page URL

https://devel.ringlet.net/editors/hexer/

### Source code URL

https://gitlab.com/hexer/hexer

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Screenshots:
https://screenshots.debian.net/package/hexer

**Comment by 2096779623** [comment]
Termux already has many hex viewers:

```bash
~ $ pkg se hex
Checking availability of current mirror:
[*] https://mirrors.ustc.edu.cn/termux/apt/termux-main: ok
Sorting... Done
Full Text Search... Done
chocolate-doom/x11 3.0.1-10 aarch64
  Historically-accurate Doom, Heretic, Hexen, and Strife ports.

deutex/stable 5.2.2 aarch64
  WAD composer for Doom, Heretic, Hexen, and Strife

hexchat/x11 2.14.3-24 aarch64
  A popular and easy to use graphical IRC (chat) client

hexcurse/stable 1.60.0-4 aarch64
  Console hexeditor

hexedit/stable 1.6 aarch64
  view and edit files in hexadecimal or in ASCII

hexyl/stable 0.10.0 aarch64
  A command-line hex viewer

ired/stable 0.6-2 aarch64
  Minimalist hexadecimal editor

libuber-h3/stable 3.7.2 aarch64
  A hexagonal hierarchical geospatial indexing system

radare2/stable 5.7.4 aarch64
  Advanced Hexadecimal Editor

watchexec/stable 1.18.11 aarch64
  Executes commands in response to file modifications
```

Tell me how this editor is different from other editors/features.

**Comment by rallg** [comment]
My 32-bit Termux has hexyl, hexedtt, and I can build Ghex.
