### ISSUE TITLE
'KHR/khrplatform.h' file not found

### ISSUE THREAD

**Issue by ItzZyann** [termux/termux-packages#11390]
Hello so uh, idk where to start but uh.
I have this problem, its probably from cmake or clang. But i always have this issue while building my binary (shared object) code, it always gives me a error which is the khrplatform.h file not found or a directory.
Can someone help me.
I cant compile / build my code without this khrplatform.h

Here is the console:
root@localhost:/sdcard/mymod# sh build.sh
-- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6                            -- Detecting C compiler ABI info                                              -- Detecting C compiler ABI info - done                                       -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped                                                                        -- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /sdcard/mymod/build
[-50%] Building CXX object CMakeFiles/gdmod.dir/src/main.cpp.o                In file included from /sdcard/mymod/src/main.cpp:1:
In file included from /sdcard/mymod/include/gd/gd.h:4:
In file included from /sdcard/mymod/include/gd/MenuLayer.h:4:
In file included from /sdcard/mymod/include/cocos2dx/include/cocos2d.h:42:
In file included from /sdcard/mymod/include/cocos2dx/actions/CCActionInterval.h:30:
In file included from /sdcard/mymod/include/cocos2dx/base_nodes/CCNode.h:34:
In file included from /sdcard/mymod/include/cocos2dx/platform/android/CCGL.h:40:
/data/data/com.termux/files/usr/include/GLES2/gl2platform.h:28:10: fatal error: 'KHR/khrplatform.h' file not found
#include <KHR/khrplatform.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/gdmod.dir/build.make:76: CMakeFiles/gdmod.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/gdmod.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
root@localhost:/sdcard/mymod#
![Screenshot_2022-07-30-20-24-25-00_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/85970053/181914228-3b3db84d-ad91-4de3-81e8-2b3968d849e5.jpg)

**Comment by Grimler91** [comment]
mesa provides KHR/khrplatform.h

**Comment by ItzZyann** [comment]
wdym mesa? you mean imma install mesa package?

**Comment by Grimler91** [comment]
Yes, `pkg install mesa`

**Comment by ItzZyann** [comment]
theres no package called mesa, as what termux says. is there any way to install that or any github git?

**Comment by ItzZyann** [comment]
theres no package called mesa, as what termux says. is there any way to install that or any github git?

**Comment by 2096779623** [comment]
> 

丶

> theres no package called mesa, as what termux says. is there any way to install that or any github git?

pkg i python
pip3 install mesa

**Comment by Grimler91** [comment]
It's in x11-packages, so x11-repo needs to be installed first:
 
```
pkg install x11-repo
pkg install mesa
```

Don't think the python package provides headers like khrplatform.h

**Comment by ItzZyann** [comment]
oh okay, thanks to all you both! i really appreciated ur help :D
