### ISSUE TITLE
Can you please add a VNC for Termux :)

### ISSUE THREAD

**Issue by cr4shcod3** [termux/termux-packages#1140]
There are some tools that needs to be run in a GUI like wireshark and any other tool. I hope there is :).

**Comment by vishalbiswas** [comment]
I have one but you'll need to compile it yourselves https://github.com/vishalbiswas/termux-packages/tree/x11

**Comment by cr4shcod3** [comment]
@vishalbiswas Can you tell me how?

**Comment by sdrausty** [comment]
It appears that VNC is available. See https://wiki.termux.com/wiki/VNC

**Comment by xeffyr** [comment]
VNC is available in this repository: https://github.com/xeffyr/termux-x-repository. Follow the instructions about adding it to sources.list and then you can install package tigervnc.

**Comment by xeffyr** [comment]
X11 packages (VNC server too) are available here: https://github.com/xeffyr/termux-extra-packages.

**Comment by Snow344** [comment]
Page not found...

**Comment by xeffyr** [comment]
@Snow344 Page found. Just moved to https://github.com/termux/x11-packages.

**Comment by Snow344** [comment]
Thank you!

Leonid Plyushch <notifications@github.com> escreveu no dia segunda,
1/10/2018 à(s) 21:03:
