### ISSUE TITLE
cmake android ndk

### ISSUE THREAD

**Issue by ItzZyann** [termux/termux-packages#11400]
Hello im here again, sorry. But this problem is just a small, so uh.
Apperantly after compiling my code, and check what android ndk was i used it says in binary file that i use android ndk r23c instead of r17c
i compile my code on cmake.
Is there any way to setup or change the cmake android ndk thing to my main r17c ndk? i cant build it with r23c cuz it uses arm64, since r17c uses armeabi-v7a

here is a screen shot,

the r17c one is a old one, i compile this using ndk-build so since cmake is easier to build i switched it but after that instead of r17c it replaced as r23c, so any body know how to change android ndk on cmake?
Thanks for someone who help me :D
![Screenshot_2022-07-31-20-02-06-40_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/85970053/182025856-35523edb-2495-42b1-8df1-e419431aee00.jpg)
![Screenshot_2022-07-31-20-01-42-10_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/85970053/182025858-18d934dd-3ce6-40a4-a6b7-638f75bd8468.jpg)

**Comment by ItzZyann** [comment]
Also compiling my code to r23c and add to a game it crash
But using r17c it looks perfectly fine

**Comment by Grimler91** [comment]
Doesn't seem like this has anything to do with termux

**Comment by ItzZyann** [comment]
hmm, ye
