### ISSUE TITLE
[Bug]: Perl suddenly fails for a script previously working

### ISSUE THREAD

**Issue by jiang-qian** [termux/termux-packages#11409]
### Problem description

I have been using Diogenes, a frontend of Greek and Latin text database written in perl, on Termux, for several years without issue. Indeed, I provided the developer with instruction of how to run it on Android with Termux:
https://d.iogen.es/d/mobile.html
in the section "Running Diogenes on Android"

Recently, it suddenly fails to run: showing error:
Starting Diogenes...
Can't load '/data/data/com.termux/files/home/perl5/lib/perl5/aarch64-android/auto/Encode/Encode.so' for module Encode: dlopen failed: cannot locate symbol "Perl_is_utf8_char_helper" referenced by "/data/data/com.termux/files/home/perl5/lib/perl5/aarch64-android/auto/Encode/Encode.so"... at /data/data/com.termux/files/usr/lib/perl5/5.36.0/XSLoader.pm line 94.
 at /data/data/com.termux/files/home/perl5/lib/perl5/aarch64-android/Encode.pm line 12.
BEGIN failed--compilation aborted at /data/data/com.termux/files/home/perl5/lib/perl5/aarch64-android/Encode.pm line 13.
Compilation failed in require at /data/data/com.termux/files/home/diogenes/server/diogenes-server.pl line 28.
BEGIN failed--compilation aborted at /data/data/com.termux/files/home/diogenes/server/diogenes-server.pl line 28.

### What steps will reproduce the bug?

Follow the instruction here
https://d.iogen.es/d/mobile.html
in section "Running Diogenes on Android".
The instructions were geared towards people not knowing how to use termux and linux commands. But essentially, it involves copying over all the databases and files from this website
https://github.com/pjheslin/diogenes
to termux and then run the purely perl based server.

It has always been reproducibly working, after copying the diogenes installation over and simply run the server written purely in perl:
~/diogenes/server/diogenes-server.pl

I can provide more info about how to get it to work as needed (it used to work, at least!)
I would appreciate any pointers for debugging this!

### What is the expected behavior?

It should start a local web server where one can then use the database through the browser:

~/diogenes/server/diogenes-server.pl
Starting Diogenes...

Startup complete. You may now point your browser at this address:
http://127.0.0.1:8888

### System information

termux-info:

```

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.24
Android version:
12
Kernel build information:
Linux localhost 5.10.81-android12-9-00001-geba40aecb3b7-ab8534902 #1 SMP PREEMPT Tue May 3 02:46:17 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 6 Pro

**Comment by tomty89** [comment]
Any particular reason you are not using the perl package from the Termux repo? Where/How exactly do you get/build the one you use?

**Comment by jiang-qian** [comment]
Oh! Thank you for your eagle eye debugging! I forgot that I have a custom perl installation from long ago and an execution path setting prioritizing it. Removing the custom install fix the issue!
