### ISSUE TITLE
[Package]: instabot

### ISSUE THREAD

**Issue by vijaygore** [termux/termux-packages#11403]
### Package description

Free Instagram python bot, [private Instagram API emulator]

### Home page URL

https://pypi.org/project/instabot/

### Source code URL

https://github.com/ohld/igbot/tree/master/instabot/api

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by licy183** [comment]
`instabot` is not longer maintained, and it could be installed on device.
```
apt install freetype libimagequant libjpeg-turbo libraqm libtiff libxcb littlecms python zlib
MATHLIB="m" pip install numpy
pip install Pillow
pip install instabot
````

So I think we will not add this package.
