### ISSUE TITLE
[mirror URL change]: termux.sahilister.in/apt to mirrors.sahilister.in/termux

### ISSUE THREAD

**Issue by sahilister** [termux/termux-packages#11414]
My mirror hosted on https://termux.sahilister.in/apt/ has been migrated to a new home at https://mirrors.sahilister.in/termux/. Please update the URLs with following information

deb https://mirrors.sahilister.in/termux/termux-main stable main 
deb https://mirrors.sahilister.in/termux/termux-root root stable
deb https://mirrors.sahilister.in/termux/termux-x11 x11 main

The mirror now has a 1 Gbps line, rsync from https://grimler.se every 6 hours and serves data over HTTP and HTTPs. 

PS - I plan to keep https://termux.sahilister.in around for a month, post that will add a redirect to new URL.

**Comment by sahilister** [comment]
Not able to remove "bug report" tag.

**Comment by 2096779623** [comment]
Changed in https://github.com/termux/termux-tools/commit/d8acef723b8ae11ec71eec1b231db23ffa65cdc0 and https://github.com/termux/termux-packages/wiki/Mirrors/b76e0ba070cf8b65893fb5133508c2745d36275a .
