### ISSUE TITLE
[Package]: Fifth Web Browser

### ISSUE THREAD

**Issue by searemind** [termux/termux-packages#11411]
### Package description

Fifth is a Web Browser for Linux written in FLTK using a version of WebKit (webkitfltk). It is very lightweight and does not support any form of multimedia streaming. If linked with static libraries and lzma-compressed, the resulting binary has a size of just 15 MB which could be a great solution for people looking for web browsers on Termux.

### Home page URL

http://fifth-browser.sourceforge.net/

### Source code URL

https://github.com/clbr/fifth

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I have successfully compiled both webkitfltk and fifth on device before. However, there is a weird bug which is that whenever a <script> tag is loaded (when JS parsing is turned on in the browser), it segfaults. I discussed this with the author of fifth, and they could not help much: https://github.com/clbr/fifth/issues/31

i do not have the resources nor time to be able to build a debug version of webkitfltk and investigate more into the problem, so if anyone can help, it would be appreciated.

**Comment by rallg** [comment]
Consider the existing "Otter" browser in Termux.

**Comment by searemind** [comment]
> Consider the existing "Otter" browser in Termux.

I'm aware of its availability but it takes up almost 300 MB including all of its dependencies, so i was just suggesting a smaller webkit-based alternative.. (and that someone would be able to debug a problem with it hehe)

either way, the build process is pretty simple too

**Comment by luciodaou** [comment]
Is it safe to use Fifth? Last update was 6 years ago.

**Comment by rallg** [comment]
From about 4-5 years ago, it seems that Fifth has some unresolved issues, probably due to changes in dependencies. I do not see Fifth among the offerings at Arch Linux, which is a bad sign.

**Comment by searemind** [comment]
It probably isn't safe and for sure isn't up to date.. i was looking for small, lightweight browsers which i could use through tigervnc on android (other than dillo and netsurf which while commendable, can't really render a lot of websites correctly..) the only problem other than security for fifth is that it segfaults whenever any <script> tag is loaded..

i understand if it won't be possible to port it in its current state, and thanks for your support. 

i have an ~almost working version already..

**Comment by xtkoba** [comment]
Depends on <a href="https://github.com/clbr/webkitfltk">WebkitFLTK</a> that is not well mantained, just like QtWebKit for Otter Browser (#12813). Not going to be packaged due to security concerns. Thank you for your understanding.
