### ISSUE TITLE
[Bug]: While using LLDB process dies instantly after the watchpoint hits on Android 12 device

### ISSUE THREAD

**Issue by DDeveloper16** [termux/termux-packages#11416]
### Problem description

Hello All. I was trying to debug an application and I set a watchpoint on an memory address. As soon as the watchpoint hit, the process died within a moment. This is the same case for GDB as well but it didn't happen on my other phone with Android 10. I have increased the phantom process limit as well so something else is wrong.

![image](https://user-images.githubusercontent.com/80547198/182242285-9e01ea5b-51c2-49cc-81c9-92de04dc5943.png)

I am new to Github so please forgive me for any mistakes. Thank you

- I am using a OnePlus Nord 2

### What steps will reproduce the bug?

1. Attach LLDB or GDB with an application on Android 12
2. Set a watchpoint on a memory address and wait for it to hit.

### What is the expected behavior?

The process would die instantly or within a moment after the watchpoint hits. 

### System information

termux-info:

```
unsupported 
Packages CPU architecture: aarch64 
Subscribed repositories: 
# sources.list 
deb https://packages.termux.dev/apt/termux-main/ stable main
Updatable packages:
Running as root. Cannot check package updates. 
termux-tools version: 
1.24
Android version:
12
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Wed Jun 29 22:19:30 CST 2022 aarch64 Android
Device manufacturer: OnePlus
Device model: Pixel 6
```

**Comment by buttaface** [comment]
I'm not sure debugging GUI apps is even supposed to work. I thought that required running under adb.

**Comment by DDeveloper16** [comment]
> I'm not sure debugging GUI apps is even supposed to work. I thought that required running under adb.

It did work but not anymore in Android version 12

**Comment by buttaface** [comment]
Maybe they tightened up the security recently then? Any idea, @Grimler91 or @sylirre?

**Comment by sylirre** [comment]
That can be SELinux, try `/system/bin/setenforce 0`.

**Comment by DDeveloper16** [comment]
No SELinux isn't the cause. It's on enforcing mode  for my A10 as well but it didn't affect the functionality of the debugger. Furthermore I set it to permissive on my A12 but still it crashed.

I found one interesting thing in Logcat though when the process died:
![Uploading Screenshot_2022-08-04-16-19-57-08_410eeff8afae61ccae598031845fc169.jpg…]()

**Comment by buttaface** [comment]
Oh, you're running as root, no wonder, didn't notice that. I don't think we support such usage so closing, but feel free to keep discussing.

**Comment by agnostic-apollo** [comment]
You should post full logcat output around the time of crash. You can take it with `adb shell logcat -d > logcat.txt` or `su -c "logcat -d > /sdcard/logcat.txt"` and then extract relevant portions and remove any private data.

>I don't think we support such usage

We have like a whole `root-repo` ;)

**Comment by buttaface** [comment]
Yes, but lldb is not a root package: we can't be expected to provide support for arbitrary root usage of random packages, though if anybody here wants to keep discussing such lldb usage, I encouraged that.

**Comment by DDeveloper16** [comment]
> You should post full logcat output around the time of crash. You can take it with `adb shell logcat -d > logcat.txt` or `su -c "logcat -d > /sdcard/logcat.txt"` and then extract relevant portions and remove any private data.
> 
> > I don't think we support such usage
> 
> We have like a whole `root-repo` and some main repo package binaries require it too. ;)

I will do that. Thank you. 



> Yes, but lldb is not a root package: we can't be expected to provide support for arbitrary root usage of random packages, though if anybody here wants to keep discussing such lldb usage, I encouraged that.

Is GDB a root package? I face the same thing ok GDB as well.

**Comment by sylirre** [comment]
The list of root packages is there: https://github.com/termux/termux-packages/tree/master/root-packages. Neither `gdb` or `lldb` are listed there.

However it is not possible to guarantee that these packages will work as expected when used to debug Android system processes. The matter is not about root or non-root permissions but rather about that Android OS behavior.
