### ISSUE TITLE
install scrapy returns clang error code 1

### ISSUE THREAD

**Issue by AndrewMcSwain** [termux/termux-packages#1142]
Android 6.0
1pip install scrapy` in global or a virtualenv returns 

`
arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/data/data/com.termux/files/usr/include/python3.6m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.6/c/_cffi_backend.o
    c/_cffi_backend.c:2:10: fatal error: 'Python.h' file not found
    #include <Python.h>
             ^~~~~~~~~~
    1 error generated.
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-766090y9/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-apuz72oy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-766090y9/cffi/`

**Comment by Grimler91** [comment]
The file Python.h is provided by the `python-dev` package. Install it with `pkg install python-dev` and try again.

**Comment by AndrewMcSwain** [comment]
same issue in virtualenv. i'll check it in global when i have unlimited internet access.

**Comment by AndrewMcSwain** [comment]
the problem persists in both virtualenv and global even after installing `python-dev`

**Comment by AndrewMcSwain** [comment]
after comparing the error messages, this time, after having installed `python-dev, a different file is missing:

In virtualenv:
``arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/data/data/com.termux/files/usr/include/python3.6m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.6/c/_cffi_backend.o
    c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found
    #include <ffi.h>
             ^~~~~~~
    1 error generated.
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-rco2n958/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-5ijq9ds5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-rco2n958/cffi/``

In global:
/data/data/com.termux/files/usr/tmp/xmlXPathInitf_5nnc5g.c:1:10: fatal error: 'libxml/xpath.h' file not found
    #include "libxml/xpath.h"
             ^~~~~~~~~~~~~~~~
    1 error generated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-n1yeqvj6/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-am7661md-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-n1yeqvj6/lxml/

**Comment by AndrewMcSwain** [comment]
I have libffi and libxml2 installed and updated.

**Comment by vishalbiswas** [comment]
`apt install libxml2-dev libffi-dev`

**Comment by AndrewMcSwain** [comment]
i have both of those installed.

**Comment by AndrewMcSwain** [comment]
Sorry for not adding this step. I have run `pkg install libffi-dev libxml2-dev openssl-dev` and still getting an error for xml2/xpath.

**Comment by vishalbiswas** [comment]
On my device
`Successfully installed Automat-0.6.0 PyDispatcher-2.0.5 Twisted-17.5.0 attrs-17.2.0 constantly-15.1.0 cryptography-2.0 cssselect-1.0.1 hyperlink-17.2.1 incremental-17.5.0 lxml-3.8.0 parsel-1.2.0 pyOpenSSL-17.1.0 pyasn1-0.2.3 pyasn1-modules-0.0.9 queuelib-1.4.2 scrapy-1.4.0 service-identity-17.0.0 w3lib-1.17.0 zope.interface-4.4.2`

**Comment by AndrewMcSwain** [comment]
I dont see how showing your device readout helps mine install packages properly.

Here's mine: 
more:        pkg help
$ pkg install libxml2-dev
Get:1 http://termux.net stable InRelease [1666 B]
Get:2 http://termux.net stable/main all Packages [3828 B]
Get:3 http://termux.net stable/main arm Packages [54.7 kB]
Fetched 60.2 kB in 1s (47.2 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
libxml2-dev is already the newest version (2.9.4-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

When I run `pip install scrapy` i get the following error messag. It seems as though the installation is looking for libxml in the wrong place.

/data/data/com.termux/files/usr/tmp/xmlXPathInitph9rq81q.c:1:10: fatal error: 'libxml/xpath.h' file not found
    #include "libxml/xpath.h"
             ^~~~~~~~~~~~~~~~
    1 error generated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-sd37_ws3/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-ldk_01j4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-sd37_ws3/lxml/

**Comment by vishalbiswas** [comment]
are you running it in virtualenv? don't

**Comment by xeffyr** [comment]
Header files of libxml2-dev located in $PREFIX/include/libxml2/libxml, so compiler cannot find "libxml/xpath.h".

For workaround just do this:
```
ln -s $PREFIX/include/libxml2/libxml $PREFIX/include/libxml
```

**Comment by AndrewMcSwain** [comment]
i ran what you said, but there`s a new error. am i going to need to do this file by file? 

error message 
`In file included from src/lxml/lxml.etree.c:515:
    src/lxml/includes/etree_defs.h:23:10: fatal error: 'libxslt/xsltconfig.h' file not found
    #include "libxslt/xsltconfig.h"
             ^~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    Compile failed: command 'arm-linux-androideabi-clang' failed with exit status 1
    creating data
    creating data/data
    creating data/data/com.termux
    creating data/data/com.termux/files
    creating data/data/com.termux/files/usr
    creating data/data/com.termux/files/usr/tmp
    cc -I/usr/include/libxml2 -c /data/data/com.termux/files/usr/tmp/xmlXPathInit5ltgsmwb.c -o data/data/com.termux/files/usr/tmp/xmlXPathInit5ltgsmwb.o
    /data/data/com.termux/files/usr/tmp/xmlXPathInit5ltgsmwb.c:2:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
    main (int argc, char **argv) {
    ^
    1 warning generated.
    cc data/data/com.termux/files/usr/tmp/xmlXPathInit5ltgsmwb.o -lxml2 -o a.out
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-zp2v17sr/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-e5era6ot-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-zp2v17sr/lxml/
$`

**Comment by xeffyr** [comment]
AndrewMcSwain, did you have libxslt-dev installed ? lxml requires full installation of libxml2 and libxslt.

**Comment by AndrewMcSwain** [comment]
I was lacking the `libxslt-dev` package. I installed it and now  `pip install scrapy` has returned with no error messages.

To get it working, I had to manually installed each of the ...`-dev` packages as described in this thread, as well as make a symlink to the proper libxml2 location.

**Comment by AndrewMcSwain** [comment]
Why was this issue closed if it's still an issue? just tried installing on a new old phone andam running into error code 1 again `----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-16umj9h5/cffi/ (failure to locate compiler). `

Here's what i ran `pkg install libffi-dev libxml2-dev openssl-dev libxslt-dev; ln -s $PREFIX/include/libxml2/libxml $PREFIX/include/libxml; pip install scrapy`

**Comment by vishalbiswas** [comment]
Have you forgot to install clang?
