### ISSUE TITLE
[Bug]: cec-client: library "libcec.so.6" not found

### ISSUE THREAD

**Issue by uwe-007** [termux/termux-packages#11462]
### Problem description

Running "cec-client -l" after "pkg install cec-client" produces
"dlopen failed: library "libcec.so.6" not found"

After creating symlink "ln -s libcec.so libcec.so.6" in /data/data/com.termux/files/usr/lib it runs.

(But doesn't work on my fire tv stick.)

### What steps will reproduce the bug?

pkg up
pkg install cec-client
cec-client -l

### What is the expected behavior?

no error message

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://dl.kcubeterm.com/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://dl.kcubeterm.com/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.24
Android version:
9
Kernel build information:
Linux localhost 4.14.87+ #1 SMP PREEMPT Tue Jun 28 11:10:12 UTC 2022 armv7l Android
Device manufacturer:
Amazon
Device model:
AFTKA


```

**Comment by T-Dynamos** [comment]
@uwe-007 
Try this
```
ln -s $PREFIX/lib/libcec.so  $PREFIX/lib/libcec.so.6
```
