### ISSUE TITLE
[Bug]: ldc build failure

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11464]
### Problem description

[ldc-failure.txt](https://github.com/termux/termux-packages/files/9261775/ldc-failure.txt)

### What steps will reproduce the bug?

build package

### System information

termux-info:

```

```

**Comment by ALSULTAN** [comment]
Check this out it will fix your building problem: #11580

**Comment by johndebia2022** [comment]
Thanks @ALSULTAN and @Grimler91 it did solve my issue
