### ISSUE TITLE
Bettercap

### ISSUE THREAD

**Issue by Systemad** [termux/termux-packages#1146]
I was wondering if anyone has installed bettercap successfully.
I think I managed to do so (?), However when running a command I get this output.
```
$ bettercap --help
This software must run as root.
```
Running with bash (am I supposed to?
```
/data/data/com.termux/files/usr/bin/bettercap: line 9: require: command not found
/data/data/com.termux/files/usr/bin/bettercap: line 11: version: command not found
/data/data/com.termux/files/usr/bin/bettercap: bettercap: line 15: syntax error near unexpected token `('
/data/data/com.termux/files/usr/bin/bettercap: bettercap: line 15: `  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding'
```
Please excuse my limited knowledge, thank you.

**Comment by Systemad** [comment]
Nvm this, ruby 1.9.x is required. Anyone knows how to install that version?

**Comment by vishalbiswas** [comment]
Its literal, you need root access to run bettercap

**Comment by Systemad** [comment]
Bettercap does work with tsu .
Closing this.
