### ISSUE TITLE
no man page for find

### ISSUE THREAD

**Issue by AndrewMcSwain** [termux/termux-packages#1147]
`man find` returns no man page. it'd be nice to have a more complete linux terminal!

**Comment by Neo-Oli** [comment]
That's because you don't actually have find installed. You're using the busybox version. Install real find with `pkg install findutils`

**Comment by sdrausty** [comment]
@AndrewMcSwain `apt install findutils` and you will find a `man` page for `find`.
![screenshot_20170717-173946](https://user-images.githubusercontent.com/27742457/28291146-3638ce84-6b17-11e7-90b9-4f1af895ee32.png)
