### ISSUE TITLE
[Bug]: Backup Errors

### ISSUE THREAD

**Issue by zak-admin** [termux/termux-packages#11488]
### Problem description

I was trying to backup and got `permission denied` errors. I found it was because in proot-distro the following points will not be accessible. 

- /apex (only Android 10+)
- /data/dalvik-cache
- /data/data/com.termux
- /sdcard
- /storage
- /system
- /vendor

### What steps will reproduce the bug?

exclude above mentioned mount points in the script.

### What is the expected behavior?

Backup with no errors

### System information

termux-info:

```
Termux Variables:                                          TERMUX_APK_RELEASE=F_DROID                                 TERMUX_APP_PACKAGE_MANAGER=apt                             TERMUX_APP_PID=2646                                        TERMUX_IS_DEBUGGABLE_BUILD=0                               TERMUX_MAIN_PACKAGE_FORMAT=debian                          TERMUX_VERSION=0.118.0                                     Packages CPU architecture:                                 arm                                                        Subscribed repositories:                                   # sources.list                                             deb https://packages-cf.termux.dev/apt/termux-main stable main                                                        Updatable packages:                                        psmisc/stable 23.5 arm [upgradable from: 23.4]             pulseaudio/stable 16.1-1 arm [upgradable from: 14.2-10]    rsync/stable 3.2.4-1 arm [upgradable from: 3.2.4]          termux-keyring/stable 3.8-1 all [upgradable from: 3.8]     termux-tools version:                                      1.24
Android version:                                           10
Kernel build information:
Linux localhost 4.9.193-perf-g743cb02 #1 SMP PREEMPT Mon Oct 25 17:15:39 CST 2021 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 8A
```

**Comment by sylirre** [comment]
If using `proot-distro`, then correct way to back up it is shown there: https://github.com/termux/proot-distro#backing-up-distribution. If you want to manually back up the rootfs, all mount points with restricted access should be excluded. For example `tar` has `--exclude` option for this.

That's intended behavior to set up these mount points on rootfs as default mode of `proot-distro` expects usability of Termux environment (you can use tools from `$PREFIX/bin` and number of things like Termux:API).

This is not a bug.

**Comment by zak-admin** [comment]
@sylirre `--exclude` was not working for me. I don't know whether I used it wrong way instead I used including all wanted.

```bash
tar -zcf /sdcard/writo/backup/$(date +%d-%m-%Y)-backup.tar.gz -C /data/data/com.termux/files ./home ./usr/bin ./usr/etc ./usr/include ./usr/lib ./usr/libexec ./usr/opt ./usr/share ./usr/tmp ./usr/var/krb5kdc ./usr/var/log ./usr/var/run ./usr/var/service ./usr/var/lib/apt ./usr/var/lib/dpkg ./usr/var/lib/proot-distro/dlcache ./usr/var/lib/proot-distro/installed-rootfs/debian/bin ./usr/var/lib/proot-distro/installed-rootfs/debian/boot ./usr/var/lib/proot-distro/installed-rootfs/debian/etc ./usr/var/lib/proot-distro/installed-rootfs/debian/home ./usr/var/lib/proot-distro/installed-rootfs/debian/lib ./usr/var/lib/proot-distro/installed-rootfs/debian/media ./usr/var/lib/proot-distro/installed-rootfs/debian/mnt ./usr/var/lib/proot-distro/installed-rootfs/debian/opt ./usr/var/lib/proot-distro/installed-rootfs/debian/proc ./usr/var/lib/proot-distro/installed-rootfs/debian/root ./usr/var/lib/proot-distro/installed-rootfs/debian/run ./usr/var/lib/proot-distro/installed-rootfs/debian/sbin ./usr/var/lib/proot-distro/installed-rootfs/debian/srv ./usr/var/lib/proot-distro/installed-rootfs/debian/sys ./usr/var/lib/proot-distro/installed-rootfs/debian/tmp ./usr/var/lib/proot-distro/installed-rootfs/debian/usr ./usr/var/lib/proot-distro/installed-rootfs/debian/var
```

For now I am using only debian. If I start to use another distribution. Again I will need to add more. I think it would be better to update a proper script in termux wiki as well to exclude folders and files with no permissions.

**Comment by sylirre** [comment]
Tar is sensitive to command line argument order, especially when it comes to file selection. To avoid mistakes, put the `--exclude` option at very beginning.

```
tar \
  --exclude "./usr/var/lib/proot-distro/*/apex" \
  --exclude "./usr/var/lib/proot-distro/*/data" \
  --exclude "./usr/var/lib/proot-distro/*/dev" \
  --exclude "./usr/var/lib/proot-distro/*/linkerconfig" \
  --exclude "./usr/var/lib/proot-distro/*/proc" \
  --exclude "./usr/var/lib/proot-distro/*/sdcard" \
  --exclude "./usr/var/lib/proot-distro/*/system" \
  --exclude "./usr/var/lib/proot-distro/*/vendor" \
  -zcf /sdcard/backup-test.tgz \
  ./usr
```

> I think it would be better to update a proper script in termux wiki as well to exclude folders and files with no permissions.

Silencing errors isn't convenient. If file can't be read, user should be notified about that. Note that `tar` doesn't stop on errors. It continues archiving even if encountered a permission denial, just problematic files will be skipped.

The list of no-permission directories created by PRoot Distro is not fixed. Every mount point made with `--bind` option will have same permission issues. Why `proot` creates directories with no permissions and whether this can be changed, please ask in https://github.com/termux/proot.

Updated variant of `tar` command:
```
tar \
  --ignore-failed-read \
  --warning=no-failed-read \
  -zcf /sdcard/backup-test2.tgz \
  ./usr
```
It will ignore all read failures. As examples on Wiki are generic, that's up to user which extra options pass to `tar`. No Termux environments are same.

For `termux-backup` script that is part of `termux-tools` I will add an option to suppress all read failures.
