### ISSUE TITLE
[Package]:  podman

### ISSUE THREAD

**Issue by zak-admin** [termux/termux-packages#11489]
### Package description

Termux is being more friendly even to non-root users. But unfortunately containerization technology such as docker requires root. However there is another competing containerization technology named podman which can run rootless. So I think it will be useful to learn containerization and development from mobile without root.

### Home page URL

https://podman.io/

### Source code URL

https://github.com/containers/podman

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by licy183** [comment]
Duplicated of #10188.

**Comment by sylirre** [comment]
Just FYI: it is not possible to run `podman` and in general any other containerization tool in rootless mode on Android. Linux kernel there lacks important features such as `user namespaces`, which actually used to implement this rootless mode.
