### ISSUE TITLE
libarrow-cpp-static requires libarrow-cpp version 7.0.0 but is at 8.0.1.1

### ISSUE THREAD

**Issue by binnisb** [termux/termux-packages#11496]
### Problem description

![Screenshot_20220806-234434_Termux](https://user-images.githubusercontent.com/1642748/183267068-7839cc6f-6cf9-42dc-8beb-8904c47737e6.jpg)

### What steps will reproduce the bug?

`pkg install libarrow-cpp-static`

### What is the expected behavior?

correct dependencies

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5755
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:                                                                                                                                                            aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
Updatable packages:
All packages up to date
termux-tools version:                                                                                                                                                                 1.24                                                                                                                                                                                  Android version:                                                                                                                                                                      12                                                                                                                                                                                    Kernel build information:
Linux localhost 4.19.113-24281538 #1 SMP PREEMPT Thu Jun 16 18:50:06 KST 2022 aarch64 Android
```

**Comment by binnisb** [comment]
I'm not sure if anyone is actively maintaining this, so I'm tagging those I've seen doing some work on it, and maybe you can point me where the creation of libarrow-cpp-static happens?

@Haiz14 @xtkoba @Mause @tomty89

**Comment by Haiz14** [comment]
```bash
pkg search libarrow
Sorting... Done
Full Text Search... Done
libarrow-cpp/stable 8.0.1-1 aarch64 [upgradable from: 7.0.0-1]
  C++ libraries for Apache Arrow

libarrow-cpp-static/stable 7.0.0 aarch64
  Static libraries for libarrow-cpp

libarrow-python/stable 8.0.1-1 aarch64 [upgradable from: 7.0.0-1]
  Arrow CPython extensions

~ $
```

**Comment by licy183** [comment]
Since https://github.com/termux/termux-packages/commit/54cbcf315c172e1807c38b952c13e31c893f1f8d, we have diabled the static library for libarrow-cpp, so no libarrow-cpp-static will be created as deb package. But due to some bugs in our building system, libarrow-cpp-static will not be added to `deleted_list.txt`, so this package will not be removed from the apt repo either. Maybe https://github.com/termux/termux-packages/blob/master/.github/workflows/packages.yml#L109 is the bug line. 

Ping @Grimler91, maybe we need manually delete this package.

https://github.com/termux/termux-packages/blob/54cbcf315c172e1807c38b952c13e31c893f1f8d/packages/libarrow-cpp/build.sh#L15

https://github.com/termux/termux-packages/blob/dd5a535cd0b0241e96d57b4b1181e9142d68017e/.github/workflows/packages.yml#L101-L110

**Comment by Haiz14** [comment]
Since `libarrow-cpp-static` is deleted form repo you gotta build it from source using cmake and then install it using ``pkg``. @binnisb . ( I built it once on termux, it's pretty simple).

Or wait till maintainers add the package back in the near future.

**Comment by binnisb** [comment]
Thanks.

I believed it was the static files that were missing, but maybe I am missing how to point to them when I install pyarrow??

running `pip install pyarrow` I get this:

![Screenshot_20220807-090438_Termux.jpg](https://user-images.githubusercontent.com/1642748/183279443-9c58b384-021c-4f40-adaa-0ee331c5fcce.jpg)

Do I need to add some flag to point to these files?

**Comment by Grimler91** [comment]
> Ping @Grimler91, maybe we need manually delete this package.

Done, will be removed next time repo is re-published. Thanks for pointing it out!

**Comment by Grimler91** [comment]
@binnisb Isn't `pyarrow` the same as our `libarrow-python` package?

**Comment by binnisb** [comment]
Not sure, I am trying to install `streamlit` which has pyarrow as a dependency and it still tries to install it after `pkg install libarrow-python`.

**Comment by binnisb** [comment]
> @binnisb Isn't `pyarrow` the same as our `libarrow-python` package?

I'll start a new issue regarding streamlit install not working since the static one is resolved :)

**Comment by tomty89** [comment]
@binnisb It requires arrow 9.0.0: https://github.com/apache/arrow/commit/5b859fda1ae5baec20a3ef54c279d9915e66dd98
