### ISSUE TITLE
Package request: perl and get-flash-videos

### ISSUE THREAD

**Issue by yuphorian6** [termux/termux-packages#115]
Please package get-flash-videos which depends on perl.

get-flash-videos is available for debian.
https://github.com/monsieurvideo/get-flash-videos
https://packages.debian.org/jessie/get-flash-videos

**Comment by fornwall** [comment]
Thanks, I've it to the [package suggestions page](https://termux.com/package-suggestions.html)!

**Comment by Neo-Oli** [comment]
Hi, I am reopening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by sarimak** [comment]
Thanks to existing Python package and its "youtube-dl" script, a workaround for get-flash-videos exists:
apt install python; pip install youtube-dl; youtube-dl <URL>

Supported sites: https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md

**Comment by rgh36167** [comment]
cool, it would be worth to advertise this a bit more. Maybe package a get-youtube-dl script?

**Comment by sarimak** [comment]
What's better, thanks to https://plus.google.com/+FredrikFornwall/posts/hsLDeWB38i3 you can share a Youtube link to youtube-dl in Termux and let it download the stuff in few taps. With a bit of scripting, you can do the same also for other data sources like torrents. ;-) Example:
```
$ cat bin/termux-url-opener
python /data/data/com.termux/files/home/bin/open.py "$1"
$ cat bin/open.py
#!python3

import os
import sys

if sys.argv[1].endswith('.torrent'):
    os.system('transmission-daemon -w ../sdcard/downloads')
    os.system('transmission-remote -a "{}"'.format(sys.argv[1]))
    os.system('transmission-remote -l')
else:
    os.system('cd ../sdcard/downloads; youtube-dl "{}"'.format(sys.argv[1]))

```

**Comment by voidzero** [comment]
Thanks!

**Comment by xeffyr** [comment]
Perl is available: `pkg install perl`.

Regarding `get-flash-videos` - this thing use too much of external perl modules (though, some are optional):
```
perl-module-find
perl-term-progressbar
perl-www-mechanize
perl-compress-zlib (optional) – Required for some sites
perl-crypt-rijndael (optional) – Required for some sites
perl-data-amf (optional) – Required for some sites
perl-lwp-protocol-https (optional) – Required for some sites
perl-lwp-protocol-socks (optional) – Required for some sites
perl-xml-simple (optional) – Required for some sites
```

We do not package perl modules and they should be installed with `cpan`.
