### ISSUE TITLE
unable to run apt-update on termux on android

### ISSUE THREAD

**Issue by sasman20** [termux/termux-packages#11502]
### Problem description

[](url
![Screenshot_20220807-160801_Termux](https://user-images.githubusercontent.com/52384047/183297994-6ae544a6-e9a4-497c-a76a-60fcf14c0b0f.jpg)
)

### What steps will reproduce the bug?

typing apt-update

### What is the expected behavior?

it should update the packages but it didnt work 

### System information

termux-info:

```

```
see above

**Comment by licy183** [comment]
Seems that you are using an old version of Termux. Please download the lastest release from Github Release or Fdroid.

**Comment by sylirre** [comment]
Issue is there not with old Termux version but with a partial upgrade.

Use `termux-reset` or `rm -rf $PREFIX`, restart the application and upgrade all packages before installing something: `yes | pkg upgrade`.
