### ISSUE TITLE
Installing Streamlit requires pyarrow and fails

### ISSUE THREAD

**Issue by binnisb** [termux/termux-packages#11509]
### Problem description

I have a virutal environment managed by `poetry`. I have successfully installed all other dependencies such as `numpy`, `zmq` etc. I have installed
```
pkg install libarrow_cpp
pkg install libarrow_python
```

and they are in `com.termux/files/usr/lib`.

I can't import `pyarrow` in python after this, so I did 

`poetry add pyarrow` 

which does not succeed.

![Screenshot_20220808-120328_Termux](https://user-images.githubusercontent.com/1642748/183394296-f28b7032-4f43-4b27-8ded-b0c3087cfa1b.jpg)
![Screenshot_20220808-120737_Termux](https://user-images.githubusercontent.com/1642748/183394399-d1dc8b64-7946-4c77-8480-a52345f50cda.jpg)
![Screenshot_20220808-120746_Termux](https://user-images.githubusercontent.com/1642748/183394467-e42ce668-67b0-49c3-accc-bc43625ba1dd.jpg)

### What steps will reproduce the bug?

```
pkg install libarrow_cpp
pkg install libarrow_python

pip install pyarrow
```

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5755
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
Updatable packages:
clang/stable 14.0.6-1 aarch64 [upgradable from: 14.0.6]
libcompiler-rt/stable 14.0.6-1 aarch64 [upgradable from: 14.0.6]
libllvm/stable 14.0.6-1 aarch64 [upgradable from: 14.0.6]
lld/stable 14.0.6-1 aarch64 [upgradable from: 14.0.6]
llvm/stable 14.0.6-1 aarch64 [upgradable from: 14.0.6]
termux-tools version:
1.24
Android version:
12
Kernel build information:
Linux localhost 4.19.113-24281538 #1 SMP PREEMPT Thu Jun 16 18:50:06 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T870

```

**Comment by tomty89** [comment]
Answered in your original report.

**Comment by binnisb** [comment]
@tomty89 You mean streamlit requires arrow 9.0.0 but what is available in termux is 8.0.0 ? So I could pin streamlit to an older version that requries arrow 8? Or is it possible to update the package in termux to 9?

**Comment by tomty89** [comment]
Well apparently the error occurs when pyarrow is built.

You can try installing pyarrow 8.0.0 specifically before you install streamlit:
```
MATHLIB="m" pip install pyarrow==8.0.0
```
(The `MATHLIB` env var is for numpy that gets pulled in.)

Hopefully it would prevent pip from pulling the latest version (i.e. 9.0.0) of pyarrow. I have no idea what streamlit needs though. Just TIAS.

**Comment by binnisb** [comment]
This worked! Thanks!
