### ISSUE TITLE
[Bug]: graphviz: cannot locate symbol "glob"

### ISSUE THREAD

**Issue by peternowee** [termux/termux-packages#11503]
### Problem description

Many Graphviz executables have linking errors, at least `dot`, `neato`, `twopi`, `circo`, `fdp`, `sfdp`, `patchwork`, `osage`.

Possibly the same issue as https://github.com/termux/termux-packages/issues/10777.

### What steps will reproduce the bug?

Just run one of them:

    $ dot
    CANNOT LINK EXECUTABLE "dot": cannot locate symbol "glob" referenced by "/data/data/com.termux/files/usr/lib/libgvc.so"...
    Aborted

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=8810
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.24
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf-g7b625a0 #1 SMP PREEMPT Mon Mar 4 14:31:59 CST 2019 armv7l Android
Device manufacturer:
motorola
Device model:
Moto G (5) Plus
```

**Comment by 2096779623** [comment]
```bash
~ $ dot -V
dot - graphviz version 2.50.0 (0)
~ $ pkg info graphviz
Package: graphviz
Version: 2.50.0
Maintainer: @termux
Installed-Size: 2695 kB
Depends: libandroid-glob, libc++, libcairo, pango, libexpat, libltdl, librsvg, libgd, zlib
Breaks: graphviz-dev                                   Replaces: graphviz-dev
Homepage: https://www.graphviz.org/
Download-Size: 737 kB                                  APT-Manual-Installed: yes
APT-Sources: https://mirrors.hit.edu.cn/termux/apt/termux-main stable/main aarch64 Packages
Description: Rich set of graph drawing tools
```

I can't reproduce this either.

**Comment by licy183** [comment]
I can't reproduce this either, probably you can change another mirror and reinstall it.

```
~ $ dot -V
dot - graphviz version 2.50.0 (0)
~ $ termux-info
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18062
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.24
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf-g10af704 #1 SMP PREEMPT Wed Jul 7 13:06:12 CST 2021 armv8l Android
Device manufacturer:
Xiaomi
Device model:
MIX 2S
~ $
```

**Comment by truboxl** [comment]
Might be due to this...
https://android.googlesource.com/platform/bionic/+/master/libc/libc.map.txt#1373

**Comment by tomty89** [comment]
Yes, and currently libgvc.so is not to libandroid-glob.so. We'll probably need to patch [this file](https://gitlab.com/graphviz/graphviz/-/blob/2.50.0/lib/gvc/Makefile.am) if we want it to.

The thing is for some reason when I try to work around the issue on my Android O device with `LD_PRELOAD` or `patchelf`, segfault occurs after making use of either. I don't know if it's just my device, or whether linking properly instead would help.
