### ISSUE TITLE
Mirror in India | mirror.albony.xyz

### ISSUE THREAD

**Issue by Albonycal** [termux/termux-packages#11539]
URL: https://mirror.albony.xyz/termux
Location: India
Bandwidth: 0.5G
email: admin@albony.xyz
*excluded repo: x11*

**Comment by sylirre** [comment]
Rather than mirroring `termux-ndk-r25`, you can include x11 repo.

We expect that all repositories are mirrored. The list can be found at https://github.com/termux/termux-packages/wiki/Mirrors. Don't mirror development repositories and other stuff not listed there.

Also note that if some host decides to make a partial mirror, it is not viable for adding into our mirror selector (`termux-change-repo`).

**Comment by Albonycal** [comment]
so

`--exclude termux-ndk-r25`
sure, I will mirror the x11 repo too :+1:

**Comment by Grimler91** [comment]
> so
> `--exclude termux-ndk-r25` ?

Yeah (I wasn't aware the temporary repo is `rsync`'able, should fix that)

**Comment by Albonycal** [comment]
did you change something? restarted rsync  ig
![image](https://user-images.githubusercontent.com/67057319/184151940-1d0cafc6-af40-4fdf-8e28-6c2039bce0b2.png)

**Comment by Grimler91** [comment]
Updated config and restarted, probably because of that

**Comment by Albonycal** [comment]
looks like its done syncing

**Comment by 2096779623** [comment]
How often is it synchronized?

**Comment by Albonycal** [comment]
every 53 minutes

**Comment by Albonycal** [comment]
any updates on this?

**Comment by Grimler91** [comment]
Added to termux-tools in https://github.com/termux/termux-tools/commit/942a8aefc2071a571a8347940728559484523204, will be part of next termux-tools update, thanks!

**Comment by Albonycal** [comment]
I think it should be added to the wiki too? right? 
![image](https://user-images.githubusercontent.com/67057319/184544625-4b02c377-bfc8-47ad-a40c-4ba3f9171635.png)

Thanks!

**Comment by 2096779623** [comment]
> I think it should be added to the wiki too? right? 
> 
> Thanks!

Added in https://github.com/termux/termux-packages/wiki/Mirrors/c27d888e0d67212904704556fce86657674fb4b2 .
