### ISSUE TITLE
[Bug]: npm install [Error - EPERM: operation not permitted]

### ISSUE THREAD

**Issue by DorukAysor** [termux/termux-packages#11533]
### Problem description

It shows this error whenever I downloaded some large npm packages...like ```NightMare, Puppeteer, @adiwajshing/baileys, whatsapp-web.js``` etc...

But doesn't show up while downloading minor npm packages... ```Axios, Cheerio, Fs, Http``` etc...

Plz help me fixing the installation...

![IMG_20220811_135038](https://user-images.githubusercontent.com/100999469/184093250-5229433e-029a-4f05-a708-5b0087bda165.jpg)

### What steps will reproduce the bug?

npm install

### What is the expected behavior?

It must have installed the required file...
In the mentioned location...

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=4289
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://plug-mirror.rcac.purdue.edu/termux/termux-main stable main
Updatable packages:
nodejs/stable 18.7.0 aarch64 [upgradable from: 18.4.0]
termux-tools/stable,stable 1.26.0-1 all [upgradable from: 1.26.0]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-8]
termux-tools version:
1.26.0
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.77+ #2 SMP PREEMPT Fri Mar 19 20:17:40 CST 2021 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH1909
```

**Comment by Grimler91** [comment]
Install to termux's home directory instead, the shared storage filesystem has limitations (like that symlinks are not allowed)
