### ISSUE TITLE
[Bug]: Trigger Rally build crash on aarch64 - SDL problem?

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-packages#11540]
### Problem description

Hello

I am working on porting the Trigger Rally game to Termux. While the game builds correctly on x86_64, it no longer builds correctly on aarch64. The problem seems to be the SDL.

https://hastebin.com/linivaloka.rb

If you want manually build:
http://192.166.219.24/openalut.tar.7z
http://192.166.219.24/trigger-rally.tar.xz

### What steps will reproduce the bug?

Just build using my source

### What is the expected behavior?

The same results as on x86_64

### System information

termux-info:

```

```

**Comment by ar664** [comment]
Did you link the pulse audio library? ```-lpulseaudio```

**Comment by IntinteDAO** [comment]
@ar664 Yep, it fixed (lpulse exacly)

```
aarch64-linux-android-clang++ -o ../bin/trigger-rally  PEngine/app.o  PEngine/audio.o  PEngine/fxman.o  PEngine/model.o  PEngine/physfs_rw.o  PEngine/render.o  PEngine/terrain.o  PEngine/texture.o  PEngine/util.o  PEngine/vbuffer.o  PEngine/vmath.o  PSim/engine.o  PSim/rigidbody.o  PSim/sim.o  PSim/vehicle.o  Trigger/game.o  Trigger/main.o  Trigger/menu.o  Trigger/render.o -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -L/data/data/com.termux/files/usr/lib -lSDL2 -L/data/data/com.termux/files/usr/lib -lSDL2_image -lSDL2 -lGL -lGLU -lGLEW -lSDL2 -lSDL2_image -lphysfs -lopenal -lalut -ldl -lc -ltinyxml2 -lpulse -lX11 -lXext -lXfixes -lXcursor -lXinerama -lXrandr -lXss -lXi -lXxf86vm
strip	../bin/trigger-rally
strip: Unable to recognise the format of the input file `../bin/trigger-rally'
```

I wonder if something can be done about it. The error as I understand it is due to the linker being used in the x86_64 version for aarch64 applications? I am not familiar with C++ unfortunately.

**Comment by tomty89** [comment]
It seems to be some kind of weirdness in the static built of libSDL(2). I've experienced some similar issue with the recent rev bump of the dependents of pulseaudio (that are also dependents of SDL(2) IIRC), but they somehow fixed themselves with "quick build" or so. The only workaround that we may want / I can think of is to disable static builds of libSDL(2). (I'm not an x11-on-Termux user so I'm not interested in investigating further.)

**Comment by IntinteDAO** [comment]
Thank you for your answers. I've updated my "package" with trigger-rally for now, if anyone wants to improve / continue development they can legitimately take it.

**Comment by ar664** [comment]
> Thank you for your answers. I've updated my "package" with trigger-rally for now, if anyone wants to improve / continue development they can legitimately take it.

So is it working now? The error above just looked like the -o flag didn't work, try ```--output=filename```

**Comment by IntinteDAO** [comment]
> So is it working now?

X86 works, ARM not :/

> The error above just looked like the -o flag didn't work, try --output=filename

I don't know if I did it correctly, but it displayed the same problem. However, the binary according to the file command is probably correct

trigger-rally: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, not stripped

**Comment by truboxl** [comment]
Hi, can you provide the link to the source code in another location? Your IP address is not publicly accessible.

**Comment by IntinteDAO** [comment]
> Hi, can you provide the link to the source code in another location? Your IP address is not publicly accessible.

Maybe your ISP block this IP. 

https://dev.intinte.org/openalut.tar.7z
https://dev.intinte.org/trigger-rally.tar.xz

**Comment by xtkoba** [comment]
The build script is calling `strip` directly. `$STRIP` (which expands to `llvm-strip`) should be used instead. On a typical GNU/Linux system `strip` belongs to GNU Binutils and cannot strip non-native binaries.
