### ISSUE TITLE
[Bug]: valgrind build failed nd25

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11564]
### Problem description

[log.txt](https://github.com/termux/termux-packages/files/9332826/log.txt)

### What steps will reproduce the bug?

build

### System information

termux docker

**Comment by Grimler91** [comment]
Could you paste the last ~250 lines of the log here directly when opening an issue? Makes error visible directly (compared to me first downloading the log, opening it with an editor and scrolling to the bottom)

**Comment by johndebia2022** [comment]
aarch64-linux-android-clang -m64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare  -O -g -fno-omit-frame-pointer -fno-strict-aliasing -fpic -fno-builtin  -O2 -Oz -nodefaultlibs -shared -Wl,-z,interpose,-z,initfirst -nostdlib -m64 /home/builder/.termux-build/_cache/android-r25-api-24-v0/lib64/clang/14.0.6/lib/linux/libclang_rt.builtins-aarch64-android.a -Wl,--whole-archive ../coregrind/libreplacemalloc_toolpreload-arm64-linux.a -Wl,--no-whole-archive -L/data/data/com.termux/files/usr/lib-Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -ovgpreload_memcheck-arm64-linux.so vgpreload_memcheck_arm64_linux_so-mc_replace_strmem.o
clang-14: warning: argument unused during compilation: '-static-openmp' [-Wunused-command-line-argument]
../coregrind/link_tool_exe_linux 0x58000000 aarch64-linux-android-clang  -Oz  -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -o memcheck-arm64-linux  -m64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare  -O2 -static -nodefaultlibs -nostartfiles -u _start -Wl,--build-id=none -m64 /home/builder/.termux-build/_cache/android-r25-api-24-v0/lib64/clang/14.0.6/lib/linux/libclang_rt.builtins-aarch64-android.a memcheck_arm64_linux-mc_leakcheck.o memcheck_arm64_linux-mc_malloc_wrappers.o memcheck_arm64_linux-mc_main.o memcheck_arm64_linux-mc_main_asm.o memcheck_arm64_linux-mc_translate.o memcheck_arm64_linux-mc_machine.o ../memcheck_arm64_linux-aarch64-setjmp.o memcheck_arm64_linux-mc_errors.o ../coregrind/libcoregrind-arm64-linux.a ../VEX/libvex-arm64-linux.a -lgcc ../coregrind/libgcc-sup-arm64-linux.a
clang-14: warning: argument unused during compilation: '-static-openmp' [-Wunused-command-line-argument]
ld: error: undefined symbol: getauxval
>>> referenced by cpu_model.c
>>>               cpu_model.c.o:(init_have_lse_atomics) in archive /home/builder/.termux-build/_cache/android-r25-api-24-v0/lib64/clang/14.0.6/lib/linux/libclang_rt.builtins-aarch64-android.a

ld: error: undefined symbol: __system_property_get
>>> referenced by cpu_model.c
>>>               cpu_model.c.o:(init_have_lse_atomics) in archive /home/builder/.termux-build/_cache/android-r25-api-24-v0/lib64/clang/14.0.6/lib/linux/libclang_rt.builtins-aarch64-android.a

ld: error: undefined symbol: strncmp
>>> referenced by cpu_model.c
>>>               cpu_model.c.o:(init_have_lse_atomics) in archive /home/builder/.termux-build/_cache/android-r25-api-24-v0/lib64/clang/14.0.6/lib/linux/libclang_rt.builtins-aarch64-android.a
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Makefile:1134: memcheck-arm64-linux] Error 1
make[3]: Leaving directory '/home/builder/.termux-build/valgrind/build/memcheck'
make[2]: *** [Makefile:1494: all-recursive] Error 1
make[2]: Leaving directory '/home/builder/.termux-build/valgrind/build/memcheck'
make[1]: *** [Makefile:898: all-recursive] Error 1
make[1]: Leaving directory '/home/builder/.termux-build/valgrind/build'
make: *** [Makefile:761: all] Error 2

**Comment by johndebia2022** [comment]
```
ld: error: undefined symbol: getauxval
ld: error: undefined symbol: __system_property_get
ld: error: undefined symbol: strncmp

```

**Comment by johndebia2022** [comment]
Issue solved
