### ISSUE TITLE
[Bug]: tvheadend build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11562]
### Problem description

[tvheadend.txt](https://github.com/termux/termux-packages/files/9332243/tvheadend.txt)

### What steps will reproduce the bug?

build

### System information

termux docker

**Comment by Grimler91** [comment]
Also investigated/tracked in https://github.com/termux/termux-packages/pull/11567

**Comment by Grimler91** [comment]
Fixed in https://github.com/termux/termux-packages/pull/11567
