### ISSUE TITLE
[Bug]: libgcrypt build failed ndk25

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11587]
### Problem description

configure:3882: aarch64-linux-android-clang  -fstack-protector-strong -Oz -no-integrated-as  -I/data/data/com.termux/files/usr/include -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now conftest.c  >&5
/usr/bin/as: unrecognized option '-EL'
clang-14: error: assembler command failed with exit code 1 (use -v to see invocation)
configure:3886: $? = 1
configure:3924: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libgcrypt"
| #define PACKAGE_TARNAME "libgcrypt"
| #define PACKAGE_VERSION "1.10.1"
| #define PACKAGE_STRING "libgcrypt 1.10.1"
| #define PACKAGE_BUGREPORT "https://bugs.gnupg.org"
| #define PACKAGE_URL ""
| #define PACKAGE "libgcrypt"
| #define VERSION "1.10.1"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;

|   return 0;
| }
configure:3929: error: in `/home/builder/.termux-build/libgcrypt/build':
configure:3931: error: C compiler cannot create executables

[libgcrypt.txt](https://github.com/termux/termux-packages/files/9333772/libgcrypt.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by tomty89** [comment]
no integrated as needs to be removed and that probably means we need disable-asm on more platforms

**Comment by truboxl** [comment]
Added the ability to include GAS on demand in #11615
Should be able to help with this
