### ISSUE TITLE
[Bug]: libmdbx build failed ndk 25

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11586]
### Problem description

/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:505:37: error: expected concept name with optional arguments
  { a.envisage_result_length() } -> std::same_as<size_t>;
                                    ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:506:47: error: expected concept name with optional arguments
  { a.write_bytes(&array[0], size_t(42)) } -> std::same_as<char *>;
                                              ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:511:23: error: expected concept name with optional arguments
  { a.is_empty() } -> std::same_as<bool>;
                      ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:512:37: error: expected concept name with optional arguments
  { a.envisage_result_length() } -> std::same_as<size_t>;
                                    ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:513:47: error: expected concept name with optional arguments
  { a.write_bytes(&array[0], size_t(42)) } -> std::same_as<char *>;
                                              ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:520:27: error: expected concept name with optional arguments
  { a.is_erroneous() } -> std::same_as<bool>;
                          ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:517:27: error: use of undeclared identifier 'ImmutableByteProducer'
concept SliceTranscoder = ImmutableByteProducer<T> &&
                          ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:527:30: error: unknown type name 'MutableByteProducer'
          MDBX_CXX20_CONCEPT(MutableByteProducer, PRODUCER)>
                             ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:527:51: error: template parameter missing a default argument
          MDBX_CXX20_CONCEPT(MutableByteProducer, PRODUCER)>
                                                  ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:526:38: note: previous default template argument defined here
          typename CAPACITY_POLICY = default_capacity_policy,
                                     ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:529:33: error: expected expression
make_buffer(PRODUCER &producer, const ALLOCATOR &allocator = ALLOCATOR());
                                ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:529:23: error: use of undeclared identifier 'producer'
make_buffer(PRODUCER &producer, const ALLOCATOR &allocator = ALLOCATOR());
                      ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:533:30: error: unknown type name 'ImmutableByteProducer'
          MDBX_CXX20_CONCEPT(ImmutableByteProducer, PRODUCER)>
                             ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:535:19: error: unknown type name 'PRODUCER'
make_buffer(const PRODUCER &producer, const ALLOCATOR &allocator = ALLOCATOR());
                  ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:538:30: error: unknown type name 'MutableByteProducer'
          MDBX_CXX20_CONCEPT(MutableByteProducer, PRODUCER)>
                             ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:538:51: error: template parameter missing a default argument
          MDBX_CXX20_CONCEPT(MutableByteProducer, PRODUCER)>
                                                  ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:537:29: note: previous default template argument defined here
template <class ALLOCATOR = legacy_allocator,
                            ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:540:38: error: expected expression
                                     const ALLOCATOR &allocator = ALLOCATOR());
                                     ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:539:48: error: use of undeclared identifier 'producer'
inline string<ALLOCATOR> make_string(PRODUCER &producer,
                                               ^
/home/builder/.termux-build/libmdbx/src/src/../mdbx.h++:543:30: error: unknown type name 'ImmutableByteProducer'
          MDBX_CXX20_CONCEPT(ImmutableByteProducer, PRODUCER)>
                             ^

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[10/18] Building C object CMakeFiles/mdbx.dir/src/alloy.c.o
ninja: build stopped: subcommand failed.
builder@3734a7c6abeb:~/termux-packages$
[libmdbx.txt](https://github.com/termux/termux-packages/files/9333740/libmdbx.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Also investigated/tracked in https://github.com/termux/termux-packages/pull/11579
