### ISSUE TITLE
[Bug]: netcat-openbsd build failed ndk25

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11591]
### Problem description

aarch64-linux-android-clang  -fstack-protector-strong -Oz  -I/data/data/com.termux/files/usr/include -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-add-needed netcat.o atomicio.o socks.o `/home/builder/.termux-build/_cache/android-r25-api-24-v0/bin/pkg-config --libs libbsd`  -o nc
ld: error: unknown argument '--no-add-needed'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:14: nc] Error 1

[netcat-openbsd.txt](https://github.com/termux/termux-packages/files/9333787/netcat-openbsd.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by tomty89** [comment]
Probably we need to replace the flag somewhere with `--no-copy-dt-needed-entries`

**Comment by johndebia2022** [comment]
Solved
