### ISSUE TITLE
[Bug]: mplayer build failed ndk25

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11604]
### Problem description

aarch64-linux-android-clang -MMD -MP -D_ISOC99_SOURCE -I. -Iffmpeg  -fstack-protector-strong -Oz -fno-asynchronous-unwind-tables -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE   -I/data/data/com.termux/files/usr/include -DPIC -D_REENTRANT -I/data/data/com.termux/files/usr/include  -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/freetype2 -I/data/data/com.termux/files/usr/include/libpng16 -I/data/data/com.termux/files/usr/include -DZLIB_CONST -I/data/data/com.termux/files/usr/include/opus -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include -c -o av_opts.o av_opts.c
av_helpers.c:54:34: error: no member named 'decode' in 'struct AVCodec'
                    if(s->codec->decode)
                       ~~~~~~~~  ^
av_helpers.c:57:34: error: no member named 'decode' in 'struct AVCodec'
                    if(s->codec->decode)

[mplayer.txt](https://github.com/termux/termux-packages/files/9334573/mplayer.txt)


### What steps will reproduce the bug?

build

### What is the expected behavior?

_No response_

### System information

termux-info:

```

```

**Comment by tomty89** [comment]
We can try 1.5, although we probably need a SVN snapshot.
