### ISSUE TITLE
[Package]: discordo

### ISSUE THREAD

**Issue by rihaq** [termux/termux-packages#11607]
### Package description

A lightweight, secure, and feature-rich Discord terminal client

### Home page URL

https://github.com/ayntgl/discordo

### Source code URL

https://github.com/ayntgl/discordo

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by T-Dynamos** [comment]
![Screenshot_2022-08-15-22-18-12-562_com termux](https://user-images.githubusercontent.com/68729523/184679222-674a7656-2fe6-4671-896e-8c6890ab0b73.jpg)
Nice!, I will add this tomorrow!
