### ISSUE TITLE
w3m:  unspecified dependency on package:  perl

### ISSUE THREAD

**Issue by dredmorbius** [termux/termux-packages#1160]
**Problem:**  unspecified dependency on package:  perl

**Symptoms:**  Some internal CGI support scripts don't work, e.g., w3mhelp.cgi

**Demonstration:**

    w3m $PREFIX/libexec/w3m/cgi-bin/w3mhelp.cgi

Alternately, run:  

    w3m -B

Press:  H
(upper-case H)

**Expected:**  Current Keymap File page is presented.

**Actual:**  Blank page.

**Workaround:**  Manually install perl:

    apt install perl

**Fix:**  Specify perl as dependency.

**Comment by dredmorbius** [comment]
Package info:

**Comment by dredmorbius** [comment]
Package info:
```

Package: w3m
Version: 0.5.3.20170102
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 1507 kB
Depends: libgc, ncurses, openssl
Homepage: http://w3m.sourceforge.net/
Download-Size: 617 kB
APT-Manual-Installed: yes
APT-Sources: http://termux.net stable/main arm Packages
Description: Text based Web browser and pager
```

**Comment by vishalbiswas** [comment]
perl is more of a recommended-dependency, but we don't have "recommends" (optional dependencies) in termux, yet. not super-hard to implement, though

**Comment by dredmorbius** [comment]
@vishalbiswas This is arguably a bug in Debian, in that its w3m _doesn't_ require _or_ recommend perl, but perl is part of the standard Debian installation.  (I think it ought to be _essential_, I'm checking on that).

Since Termux doesn't require Perl in the same way, the dependency omission becomes evident.

**Comment by fornwall** [comment]
perl is a relatively heavy dependency (`74.1 MB` install size, compared to `1638 kB` for w3m) and I would guess that most w3m users doesn't need the functionality added by perl, which makes me hesitant adding it as a dependency. Thoughts?

**Comment by dredmorbius** [comment]
I'd suggest it as "recommended".

Alternatively, rewriting the CGI with an interpreter that is present might work.  The main problem is that the help and support files are perl executables.  Unless there's some fallback, all that happens is that these silently fail.  That's what I'd experienced, and it took a while for me to sort out _why_ that was happening -- first I had to figure out that the online help was command-based, where it was, and why it wasn't working.

That was a few months of frustration....

```

dirlist.cgi:     Perl script text executable
multipart.cgi:   Perl script text executable
w3mbookmark:     ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
w3mdict.cgi:     a /data/data/com.termux/files/usr/bin/sh script, ASCII text executable
w3mhelp.cgi:     Perl script text executable
w3mhelperpanel:  ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
w3mmail.cgi:     Perl script text executable
w3mman2html.cgi: Perl script text executable
```

**Comment by its-pointless** [comment]
you could move all the stuff that doesn't work without perl into a sub package and have the subpackage depends on perl.
