### ISSUE TITLE
[Bug]: php-imagick needs libomp.so

### ISSUE THREAD

**Issue by errr-maxx** [termux/termux-packages#11600]
### Problem description

I installed `php` and `php-imagick`, enabled  `imagick` in `php.ini` and now when i start php server i get this warning:

`Warning:  PHP Startup: Unable to load dynamic library 'imagick' (tried: /data/data/com.termux/files/usr/lib/php/imagick (dlopen failed: library "/data/data/com.termux/files/usr/lib/php/imagick" not found), /data/data/com.termux/files/usr/lib/php/imagick.so (dlopen failed: library "libomp.so"; not found: needed by /data/data/com.termux/files/usr/lib/php/imagick.so in namespace (default))) in Unknown on line 0`

and Imagick extension do not work and is reported as not loaded

### What steps will reproduce the bug?

Install `php` and `php-imagick`
Enable `Imagick` extension in `php.ini`
Run php and try to use `Imagick` extension or try to find it in `var_dump(get_loaded_extensions());` output

### What is the expected behavior?

`Imagick` loads and works

### System information

termux-info:

```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1+a080909
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~98TSZIIRvxwHVFlgTZZBvQ==/com.termux-8HsxzUC_z5WYTvQBpViYDQ==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=5739
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c172,c258,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c172,c258,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10684
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+f1d411a
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+f1d411a
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
Updatable packages:
clang/stable 14.0.6-2 aarch64 [upgradable from: 14.0.6-1]
gdk-pixbuf/stable 2.42.9 aarch64 [upgradable from: 2.42.8-1]
libcompiler-rt/stable 14.0.6-2 aarch64 [upgradable from: 14.0.6-1]
libllvm/stable 14.0.6-2 aarch64 [upgradable from: 14.0.6-1]
lld/stable 14.0.6-2 aarch64 [upgradable from: 14.0.6-1]
llvm/stable 14.0.6-2 aarch64 [upgradable from: 14.0.6-1]
psmisc/stable 23.5-1 aarch64 [upgradable from: 23.5]
strace/stable 5.19 aarch64 [upgradable from: 5.18]
termux-keyring/stable,stable 3.9 all [upgradable from: 3.8-1]
termux-tools version:
1.26.0
Android version:
11
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Tue Jun 14 21:11:29 CST 2022 aarch64 Android
Device manufacturer:
realme
Device model:
RMX2155
```

**Comment by tomty89** [comment]
Hmm, perhaps `-static-openmp` no longer has any effect? Maybe we should remove libomp.so (i.e. leaving libomp.a there only) when we set up the toolchain?
