### ISSUE TITLE
[Bug]: ltrace build failed ndk25

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11603]
### Problem description

Applying patch: ltrace-elf.c.patch
Applying patch: sysdeps-linux-gnu-proc.c.patch
aclocal: warning: couldn't open directory 'config/m4': No such file or directory
autoreconf: error: cannot create config/autoconf: No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config/autoconf'.
libtoolize: copying file 'config/autoconf/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'config/m4'.
libtoolize: copying file 'config/m4/libtool.m4'
libtoolize: copying file 'config/m4/ltoptions.m4'
libtoolize: copying file 'config/m4/ltsugar.m4'
libtoolize: copying file 'config/m4/ltversion.m4'
libtoolize: copying file 'config/m4/lt~obsolete.m4'
configure.ac:56: installing 'config/autoconf/compile'
configure.ac:32: installing 'config/autoconf/config.guess'
configure.ac:32: installing 'config/autoconf/config.sub'
configure.ac:59: installing 'config/autoconf/install-sh'
configure.ac:59: installing 'config/autoconf/missing'
Makefile.am: installing 'config/autoconf/depcomp'
[ltrace.txt](https://github.com/termux/termux-packages/files/9334552/ltrace.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Also investigated/tracked in https://github.com/termux/termux-packages/pull/11577

**Comment by Grimler91** [comment]
Fixed by https://github.com/termux/termux-packages/pull/11577
