### ISSUE TITLE
[Bug]: Java : dlopen failed: library "libc.so.6" not found

### ISSUE THREAD

**Issue by ShelfCat** [termux/termux-packages#11606]
### Problem description

I'm trying to host minecraft server in termux and get : "java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/tmp/jansi-2.4.0-9b1c6d1e92d917dd-libjansi.so: dlopen failed: library "libc.so.6" not found".For minecraft server it isn't necessary library,but some plugins needs it.

### What steps will reproduce the bug?

Download papermc , agree to Mojang EULA , run the server.

### What is the expected behavior?

Java finds library "libc.so.6" and not throws exception.

### System information

termux-info:
```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=30895
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.26.0
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-g0bde30b #2 SMP PREEMPT Mon Oct 8 13:33:13 CST 2018 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
CPN-L09
```

**Comment by sylirre** [comment]
Unfortunately you will need to use PRoot in order to run original MC executable. It uses JNI libraries dependent on GNU libc.

This is not a bug.

**Comment by OrdinaryEnder** [comment]
You can get @Maxython glibc for running that, I'm not sure it's work or not
