### ISSUE TITLE
[Bug]: graphviz: Format: "jpg" not recognized

### ISSUE THREAD

**Issue by peternowee** [termux/termux-packages#11613]
### Problem description

Graphviz is missing some output format, such as `jpg`.

Last known good: 2.44.1-2.
First known bad: 2.50.0-1.
I don't know about the versions between 2.44.1-2 and 2.50.0-1.

Different `$PREFIX/lib/graphviz/config6` of versions 2.44.1-2 and 5.0.0:
[config6.20210627.graphviz-2.44.1-2.bak.txt](https://github.com/termux/termux-packages/files/9339687/config6.20210627.graphviz-2.44.1-2.bak.txt)
[config6.20220814.graphviz-5.0.0.bak.txt](https://github.com/termux/termux-packages/files/9339686/config6.20220814.graphviz-5.0.0.bak.txt)

Not sure, but some other formats seem to have gone missing as well: `gif`, `jpg`, `svgz`, `vmlz`, `vrml`, `wbmp`, `webp`, `xbm`. Perhaps for varying reasons (e.g. issues upstream, different dependency issues, etc.). I only know for sure that I had `jpg` working in 2.44.1-2.

### What steps will reproduce the bug?

```shell
$ dot -V
dot - graphviz version 5.0.0 (0)
$ echo "graph g { a }" | dot -Tjpg >test.jpg
Format: "jpg" not recognized. Use one of: canon cmap cmapx cmapx_np dot dot_json eps fig gd gv imap imap_np ismap json json0 mp pdf pic plain plain-ext png pov ps ps2 svg tk vdx vml x11 xdot xdot1.2 xdot1.4 xdot_json xlib
$ dot -Tjpg
Format: "jpg" not recognized. Use one of: canon cmap cmapx cmapx_np dot dot_json eps fig gd gv imap imap_np ismap json json0 mp pdf pic plain plain-ext png pov ps ps2 svg tk vdx vml x11 xdot xdot1.2 xdot1.4 xdot_json xlib
```

### What is the expected behavior?

No error.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=8810
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.27.0
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf-g7b625a0 #1 SMP PREEMPT Mon Mar 4 14:31:59 CST 2019 armv7l Android
Device manufacturer:
motorola
Device model:
Moto G (5) Plus
```

**Comment by tomty89** [comment]
Basically 290ae05 was a bad call. The cmake files in graphiviz are not at all in better shape / more maintained in graphviz.

**Comment by Grimler91** [comment]
I believe switching to cmake was also done to workaround https://github.com/android/ndk/issues/1614, which was a new issue at the time. Reverting and adding `LDFLAGS=$($CC -print-libgcc-file-name)` should be possible
