### ISSUE TITLE
[Bug]: new issue on termux-elf-cleaner.

### ISSUE THREAD

**Issue by Anonymous2716** [termux/termux-packages#11612]
### Problem description

I ran `termux-elf-cleaner` in some binary files after building them. Such as the aapt wrapper.  And a few more . all of them gives this  error:
```
CANNOT LINK EXECUTABLE "./p": empty/missing DT_HASH/DT_GNU_HASH in "/data/data/com.termux/files/home/p" (new hash type from the future?)
```

### What steps will reproduce the bug?

Running the binary after patching with `termux-elf-cleaner`.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=813
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
ltrace/stable 1:0.7.3-4 aarch64 [upgradable from: 1:0.7.3-3]
termux-tools version:
1.27.0
Android version:
9
Kernel build information:
Linux localhost 4.4.146 #2 SMP PREEMPT Wed Sep 9 18:47:45 CST 2020 aarch64 Android

```

**Comment by Grimler91** [comment]
It's because default API level is now 21, should work as before if `--api-level 24` is specified. We should change so it defaults to termux's API level though

**Comment by Anonymous2716** [comment]
@Grimler91 api level stepped down to support android 5?  And it workd.

**Comment by Grimler91** [comment]
> @Grimler91 api level stepped down to support android 5?

Yeah, the `--api-level` arg was introduced in a recent update. To keep compatibility with how termux-elf-cleaner worked before default target api level should be 21 when cross-compiling packages, but for the package we provide on device the default target api level should definitely be the level that termux targets

**Comment by Anonymous2716** [comment]
@Grimler91  when building packages (open jdk) on device I got

 ````
/data/data/com.termux/files/home/termux-packages/packages/openjdk-17/build.sh: line 45: /data/data/com.termux/files/home/.termux-build/_cache/android-r25-api-24-v1/devkit.info: No such file or directory
```

**Comment by Grimler91** [comment]
openjdk is not supported for building on device, build recipe needs to be adjusted (right now it deletes files in $PREFIX, but luckily it failed earlier than that)

**Comment by Anonymous2716** [comment]
@Grimler91  I specified -I did that prevent from Erasing ?

**Comment by Grimler91** [comment]
No, the actual build recipe [deletes files](https://github.com/termux/termux-packages/blob/master/packages/openjdk-17/build.sh#L101), but as mentioned you are safe because it failed earlier. 

I pushed https://github.com/termux/termux-packages/commit/971d64e01bfd729bbfeb9b264bb8ecb1e1b83959 to prevent on device builds until I have fixed the build recipe to be safe for on device builds
