### ISSUE TITLE
[Bug]: proxmark3-git build failed (arm) ndk-25

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11618]
### Problem description

error: ran out of registers during register allocation
[-] CC entropy.c
1 error generated.
make[2]: *** [Makefile:88: obj/hardnested_bf_core_NEON.o] Error 1
make[1]: *** [Makefile:832: deps/hardnested/libhardnested.a] Error 2
make[1]: *** Waiting for unfinished jobs....

[proxmark3-git.txt](https://github.com/termux/termux-packages/files/9345122/proxmark3-git.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Also investigated/tracked in https://github.com/termux/termux-packages/pull/11573
