### ISSUE TITLE
[Package]: yukimi

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#11629]
### Package description

 Anime/Manga command-line interface backed up by Tenka

### Home page URL

https://yukino-org.github.io/wiki/yukimi/installation/

### Source code URL

https://github.com/yukino-org/yukimi

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Biswa96** [comment]
The repository has been archived by the owner on Jun 8, 2023.

**Comment by TomJo2000** [comment]
Same deal as #11630

> Unless there's a maintained fork I guess we're closing this then.
> Though I can't find a single package of it on repology.
> Not even an AUR package.
> 
> If there is a maintained fork perhaps under a different name feel free to comment in here and perhaps we can get this reopened.
