### ISSUE TITLE
[Package]: JD-GUI

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#11625]
### Package description

JD-GUI is a standalone graphical utility that displays Java source codes of ".class" files. You can browse the reconstructed source code with the JD-GUI for instant access to methods and fields.

### Home page URL

https://github.com/java-decompiler/jd-gui

### Source code URL

https://github.com/java-decompiler/jd-gui

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

How to build JD-GUI ?
> git clone https://github.com/java-decompiler/jd-gui.git
> cd jd-gui
> ./gradlew build 
generate :

"build/libs/jd-gui-x.y.z.jar"
"build/libs/jd-gui-x.y.z-min.jar"
"build/distributions/jd-gui-windows-x.y.z.zip"
"build/distributions/jd-gui-osx-x.y.z.tar"
"build/distributions/jd-gui-x.y.z.deb"
"build/distributions/jd-gui-x.y.z.rpm"
How to launch JD-GUI ?
Double-click on "jd-gui-x.y.z.jar"
Double-click on "jd-gui.exe" application from Windows
Double-click on "JD-GUI" application from Mac OSX
Execute "java -jar jd-gui-x.y.z.jar" or "java -classpath jd-gui-x.y.z.jar org.jd.gui.App"
How to use JD-GUI ?
Open a file with menu "File > Open File..."
Open recent files with menu "File > Recent Files"
Drag and drop files from your file explorer
How to extend JD-GUI ?
> ./gradlew idea 
generate Idea Intellij project

> ./gradlew eclipse
generate Eclipse project

> java -classpath jd-gui-x.y.z.jar;myextension1.jar;myextension2.jar org.jd.gui.App
launch JD-GUI with your extensions

How to uninstall JD-GUI ?
Java: Delete "jd-gui-x.y.z.jar" and "jd-gui.cfg".
Mac OSX: Drag and drop "JD-GUI" application into the trash.
Windows: Delete "jd-gui.exe" and "jd-gui.cfg".

**Comment by Anonymous2716** [comment]
JD GUI works by default even of not a package. Just download the jar file. Bytecode viewer too.

**Comment by Anonymous2716** [comment]
@ArjunaKumarMohanta you need to setup a GUI environment. Probably termux-x11 or vnc . then in there in terminal you can just run ```java -jar jd-gui.jar```  there you go.

**Comment by Anonymous2716** [comment]
![Screenshot_20220819-200436_1](https://user-images.githubusercontent.com/78570872/185636329-64ba9ec7-4815-4d33-bb63-41fa26b9943f.png)
 


@ArjunaKumarMohanta

**Comment by Anonymous2716** [comment]
@ArjunaKumarMohanta setup a GUI environment https://wiki.termux.com/wiki/Graphical_Environment . Or checkout other github repos like https://github.com/adi1090x/termux-desktop set it up. And then run in there. Or post on reddit.com/r/termux  to ask how to do it. Then download jdgui and run it.

**Comment by Anonymous2716** [comment]
@ArjunaKumarMohanta  

First basic preparation I assume you have done it all.

 `pkg update`

`pkg upgrade`

`pkg install openjdk-17 xfce4 tigervnc`

Then setup vnc:

`mkdir ~/.vnc`

`cd ~/.vnc`

`echo "xfce4-session &" > xstartup`

`chmod +x xstartup`

Now download the jd-gui jar file from here:

http://java-decompiler.github.io/#jd-gui-download 
Or here
 https://github.com/java-decompiler/jd-gui/releases

Then start the vncserver :

`vncserver`

It will ask to set a password. Set it .

Then install a vnc viewer e.g. realvncviewer -play store , avnc - fdroid , bvnc etc.

Then login there :

![Screenshot](https://user-images.githubusercontent.com/78570872/186523082-83298ad3-919f-419c-9b64-a1cc79386496.png)

And then start jdgui as I showed in the previewes comment :
Open up the terminal then.

`java -jar jd-gui.jar`


Bytecode-viewer works the same way too.


Alternatively  you can use jadx in termux . without setting up any of this.

**Comment by Anonymous2716** [comment]
@ArjunaKumarMohanta  sometimes it has issues . but it works fine last time I tried. File > save all sources.

**Comment by Anonymous2716** [comment]
@ArjunaKumarMohanta visit their github page. It doesn't require any modifications or any special setup. Just use as it is.
