### ISSUE TITLE
[Bug]: "libgcc_s.so.1" not found while running Lavalink server 

### ISSUE THREAD

**Issue by OrdinaryEnder** [termux/termux-packages#11624]
### Problem description

Openjdk Complain there's no libgcc_s.so.1

Logs:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'websocketConfig' defined in URL [jar:file:/storage/emulated/0/Lavalink.jar!/BOOT-INF/classes!/lavalink/server/config/WebsocketConfig.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'socketServer' defined in URL [jar:file:/storage/emulated/0/Lavalink.jar!/BOOT-INF/classes!/lavalink/server/io/SocketServer.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'koeOptions' defined in class path resource [lavalink/server/config/KoeConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [moe.kyokobot.koe.KoeOptions]: Factory method 'koeOptions' threw exception; nested exception is java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/tmp/lava-jni-natives/1660647834699/libudpqueue.so: dlopen failed: library "libgcc_s.so.1" not found: needed by /data/data/com.termux/files/usr/tmp/lava-jni-natives/1660647834699/libudpqueue.so in namespace (default)
```

### What steps will reproduce the bug?

running lavalink.jar (java -jar Lavalink.jar)

### What is the expected behavior?

Running the server

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1+ba2836b
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=17547
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
libresolv-wrapper/stable 1.1.7-3 aarch64 [upgradable from: 1.1.7-2]
termux-tools/stable 1.27.0-1 all [upgradable from: 1.26.0-1]
termux-tools version:
1.26.0
Android version:
11
Kernel build information:
Linux localhost 4.19.127-g8f9631c3c-dirty #1 SMP PREEMPT Mon Jun 20 16:29:07 CST 2022 aarch64 Android
Device manufacturer:
vivo
Device model:
V2026
```

**Comment by Grimler91** [comment]
Please improve the `What steps will reproduce the bug?` section. `running lavalink.jar` is not exactly clear, what is lavalink.jar? How are you running it?

**Comment by OrdinaryEnder** [comment]
```
java -jar Lavalink.jar
```

**Comment by Grimler91** [comment]
I still have no idea what `lavalink.jar` or `Lavalink.jar` you are using, since I can't read your mind. 

Duckduckgo shows many hits related to lavalink.jar. Maybe you are using one of the many versions from https://github.com/freyacodes/Lavalink, or maybe one of the many versions from https://github.com/Cog-Creators/Lavalink-Jars, who knows..

**Comment by OrdinaryEnder** [comment]
> I still have no idea what `lavalink.jar` or `Lavalink.jar` you are using, since I can't read your mind.
> 
> Duckduckgo shows many hits related to lavalink.jar. Maybe you are using one of the many versions from https://github.com/freyacodes/Lavalink, or maybe one of the many versions from https://github.com/Cog-Creators/Lavalink-Jars, who knows..

I using official one (https://github.com/freyacodes/Lavalink)

**Comment by tomty89** [comment]
I don't think there's much we can do here anyway if the program / library is designed / built to be used with shared gcc-libs. It's obviously has nothing to do with our jdk or any of the packages in our repo:
```
dlopen failed: library "libgcc_s.so.1" not found: needed by /data/data/com.termux/files/usr/tmp/lava-jni-natives/1660647834699/libudpqueue.so
```

**Comment by xtkoba** [comment]
Similar to the <a href="https://github.com/termux/termux-packages/issues?q=is%3Aissue+libjansi">`libjansi` case</a>, the pre-built JAR contains native libraries built for GNU/Linux, not for Android.
