### ISSUE TITLE
[Package]: tanoshi

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#11630]
### Package description

Selfhosted web manga reader

### Home page URL

https://faldez.github.io/tanoshi

### Source code URL

https://github.com/faldez/tanoshi

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Biswa96** [comment]
The repository has been archived by the owner on Aug 5, 2023.

**Comment by TomJo2000** [comment]
Unless there's a maintained fork I guess we're closing this then.
Though I can't find a single package of it on repology.
Not even an AUR package.

If there is a maintained fork perhaps under a different name feel free to comment in here and perhaps we can get this reopened.
