### ISSUE TITLE
mosh segfaults after each connection loss

### ISSUE THREAD

**Issue by immae** [termux/termux-packages#1163]
I recently upgraded the mosh package, which is now to version 1.3.0. Since then it segfaults each time I lose the connection. Before that (I installed it ~middle june and didn't upgrade it until yesterday) I didn't have any problem.

Is it possible to revert to previous version of mosh? If I can do anything to help investigate... (I saw no "verbose" option for mosh)

**Comment by immae** [comment]
It's certainly due to d946e67c5b86dd990ffa0e5654b2a514b787aeb9
which rebuilt mosh 1.3.0-1 -> 1.3.0-2

1.3.2 also has the segfault problem

**Comment by immae** [comment]
It's certainly due to d946e67c5b86dd990ffa0e5654b2a514b787aeb9
which rebuilt mosh 1.3.0-1 -> 1.3.0-2

1.3.2 also has the segfault problem

**Comment by fornwall** [comment]
Thanks for reporting! Which cpu arch is this on (what is the output of `uname -m`)?

**Comment by fornwall** [comment]
Also, which device and Android version (and possibly what ROM) is this?

After some quick testing I'm unable to reproduce the problem after testing on a 32-bit arm device running Android 6.0, and a 64-bit arm device running Android 7.1, so it would be valuable with information allowing me to reproduce the problem!

**Comment by immae** [comment]
thanks @fornwall. The output of uname -m is "armv71". I think (almost sure) it's a 32bits. The OS is a android 7, on a fairphone2 with the fairphone Open OS installed.

**Comment by immae** [comment]
Hmm, it's a Marshmallow, so Android 6 actually, sorry.

**Comment by fornwall** [comment]
Thanks a lot for the help!

Can you update all packages (`pkg up`), which should bring mosh at version 1.3.2-1 and libprotobuf at version 3.3.2-2, and verify that it works now?

**Comment by immae** [comment]
Yay it works, thanks :)

**Comment by immae** [comment]
Hi, This issue should be reopened, I got the issue again recently, with the same phone

**Comment by tomty89** [comment]
#3801 should fix it.
