### ISSUE TITLE
[Package]: fcitx5

### ISSUE THREAD

**Issue by EdwardZhangLink** [termux/termux-packages#11645]
### Package description

Fcitx 5 is a generic input method framework released under LGPL-2.1+.

Fcitx [ˈfaɪtɪks] is an input method framework with extension support. Currently it supports Linux and Unix systems like freebsd. Fcitx supports typing with many languages all over the world with a large number of engines.

Fcitx has a slim core while provides powerful features with addons. It is easy to customize fcitx to satisfy your own needs. 

### Home page URL

https://fcitx-im.org/

### Source code URL

https://github.com/fcitx/fcitx5

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
Adding input methods may not be useful.

**Comment by EdwardZhangLink** [comment]
> Adding an input method probably won't help much.

Maybe it can be used in VNC?

**Comment by 2096779623** [comment]
> Maybe it can be used in VNC?

Maybe.
