### ISSUE TITLE
'remind' segfaults when given directory argument as input (package: remind)

### ISSUE THREAD

**Issue by dredmorbius** [termux/termux-packages#1164]
## Bug:  `remind` segfaults when given directory argument as input.

The remind manpage states that a directory will be scanned for files to produce
output:

    If filename happens to be a directory rather than a plain file, then
    Remind reads all of the files in that directory that match the pattern
    "*.rem".  The files are read in sorted order; the sort order may depend
    on your locale, but should match the sort order used by the shell to
    expand "*.rem".

When this is attempted, remind exits with errors and fails to produce a report
of reminders.

## Bug reproduction

    a204@localhost:~/reminders$ pwd
    /data/data/com.termux/files/home/reminders
    u0_a204@localhost:~/reminders$ ls
    main.rem
    u0_a204@localhost:~/reminders$ remind ~/reminders/
    /data/data/com.termux/files/home/reminders/(1): Error reading: I/O error
    u0_a204@localhost:~/reminders$ remind .
    .(1): Error reading: I/O error
    u0_a204@localhost:~/reminders$ remind -v ~/reminders/
    /data/data/com.termux/files/home/reminders/(1):
    [1]+  Stopped                 remind -v ~/reminders/
    u0_a204@localhost:~/reminders$
    [1]+  Segmentation fault      remind -v ~/reminders/

## Package info
    
    Package: remind
    Version: 3.1.15
    Maintainer: Fredrik Fornwall <fredrik@fornwall.net>
    Installed-Size: 446 kB
    Homepage: https://www.roaringpenguin.com/products/remind
    Download-Size: 120 kB
    APT-Manual-Installed: yes
    APT-Sources: http://termux.net stable/main arm Packages
    Description: Sophisticated calendar and alarm program

**Comment by fornwall** [comment]
Thanks - this has been fixed in version `3.1.15-1` of the remind package which is now available as an update!
