### ISSUE TITLE
[Package]: libv4l2 and libv4l1

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#11666]
### Package description

libv4l is a collection of libraries which adds a thin abstraction layer on
top of video4linux2 devices. The purpose of this (thin) layer is to make it
easy for application writers to support a wide variety of devices without
having to write seperate code for different devices in the same class.

### Home page URL

https://github.com/philips/libv4l

### Source code URL

https://github.com/philips/libv4l

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Its 13 years old and giving some weird errors
```
control/libv4lcontrol.c:260:16: error: called object type 'int' is not a function or function pointer
        minor == minor(st.st_rdev))
                 ~~~~~^
control/libv4lcontrol.c:419:17: warning: implicit declaration of function 'shm_open' is invalid in C99 [-Wimplicit-function-declaration]
  if ((shm_fd = shm_open(shm_name, (O_CREAT | O_EXCL | O_RDWR),
                ^
control/libv4lcontrol.c:420:6: error: use of undeclared identifier 'S_IREAD'
                         (S_IREAD | S_IWRITE))) >= 0)
                          ^
control/libv4lcontrol.c:420:16: error: use of undeclared identifier 'S_IWRITE'
                         (S_IREAD | S_IWRITE))) >= 0)
                                    ^
control/libv4lcontrol.c:423:42: error: use of undeclared identifier 'S_IREAD'
    shm_fd = shm_open(shm_name, O_RDWR, (S_IREAD | S_IWRITE));
                                         ^
control/libv4lcontrol.c:423:52: error: use of undeclared identifier 'S_IWRITE'
    shm_fd = shm_open(shm_name, O_RDWR, (S_IREAD | S_IWRITE));
                                                   ^
1 warning and 5 errors generated.
make[1]: *** [Makefile:79: control/libv4lcontrol.o] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/libv4l/libv4lconvert'                                          make: *** [Makefile:5: all] Error 2
```

I need it for building ssr (simple screen recorder)

**Comment by rootvip** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by T-Dynamos** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

![Screenshot_2022-08-20-22-57-20-685_com android chrome](https://user-images.githubusercontent.com/68729523/185759220-ee9aba75-6b9f-485e-975d-b7d052bbeee6.jpg)
Strange

**Comment by 2096779623** [comment]
Lol
