### ISSUE TITLE
[Bug]: $ apt update Reading package lists... Done E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again) E: Unable to lock directory /data/data/com.termux/files/usr/var/lib/apt/lists/

### ISSUE THREAD

**Issue by satish9772** [termux/termux-packages#11663]
### Problem description

$ apt update
Reading package lists... Done
E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again)
E: Unable to lock directory /data/data/com.termux/files/usr/var/lib/apt/lists/

### What steps will reproduce the bug?

$ apt update
Reading package lists... Done
E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again)
E: Unable to lock directory /data/data/com.termux/files/usr/var/lib/apt/lists/

### What is the expected behavior?

$ apt update
Reading package lists... Done
E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again)
E: Unable to lock directory /data/data/com.termux/files/usr/var/lib/apt/lists/

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Seems like apt might be running in another termux session, or maybe
termux was force-closed in the middle of an update or something.

If apt is not running in a separate session then remove the lockfile
and try again: `rm $PREFIX/var/lib/apt/lists/lock`.
