### ISSUE TITLE
[Bug]: bootstrap install failed 

### ISSUE THREAD

**Issue by lentas1** [termux/termux-packages#11662]
### Problem description

i get error message from bootstrap

### What steps will reproduce the bug?

i get this when i open app

### System information

termux-info:
(''')
a52s
(''')

**Comment by lentas1** [comment]
![Uploading Screenshot_20220820-151958_Termux.png…]()

**Comment by lentas1** [comment]
![Screenshot_20220820-151958_Termux](https://user-images.githubusercontent.com/88710364/185745921-c41ed821-46da-4df0-bb4b-27004598caec.png)

**Comment by lentas1** [comment]
i have galaxy a52s

**Comment by OrdinaryEnder** [comment]
Maybe ur using old termux, new termux doesn't need connection to install bootstraps

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation
