### ISSUE TITLE
Libarchive package corrupt in pacman 

### ISSUE THREAD

**Issue by yutontaku** [termux/termux-packages#11671]
![Screenshot_20220821-113534_Termux~2](https://user-images.githubusercontent.com/77633135/185786164-932e5b70-6de3-4a92-9e40-d3091276f07b.png)
If I install it via pacman -U all ok
![Screenshot_20220821-114218_Termux~2](https://user-images.githubusercontent.com/77633135/185786335-8550f236-55df-4ef1-a02d-c5cd9c908500.png)

**Comment by Maxython** [comment]
Thank you for report. Now everything is fixed, try installing `libarchive` again.
```
pacman -Sy libarchive
```
