### ISSUE TITLE
charmbracelet / skate

### ISSUE THREAD

**Issue by eggbean** [termux/termux-packages#11686]
### Package description

Skate is simple and powerful. Use it to save and retrieve anything you’d like—even binary data. It’s fully encrypted, backed up to the cloud (that you can self-host if you want) and can be synced with all your machines.

This is really useful for storing data (strings and even binary) securely and syncing with other devices.

I believe there is at least one other package from charmbracelet that is already available in termux (glow).

### Source code URL

https://github.com/charmbracelet/skate

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I have not tried compiling it on termux yet, but when running the arm64 build from releases I get this error when trying to link to other hosts:

```
$ skate link

You can link the SSH keys on another machine to your Charm
account so both machines have access to your stuff. Keys
can be unlinked at any time.

Uh oh: dial tcp: lookup cloud.charm.sh on [::1]:53: read udp [::1]:42569->[::1]:53: read: connection
refused
```

**Comment by jstetten** [comment]
'glow' & 'gum' are both in the main repo. 'skate' though would be an order of magnitude more useful if it could be made to work.

You'd think it would be highly dependent on the core Charm cloud FS package to be working first though, right?

**Comment by eggbean** [comment]
@jstetten I don't think so, as that runs on their servers, doesn't it? We are just dealing with the client for Android here.

**Comment by xtkoba** [comment]
Packaged in commit 9751274326dfc25fe24d32b0e675e2bf18e8eed7.

**Comment by eggbean** [comment]
Cool, thanks!
