### ISSUE TITLE
proot-distro ubuntu - Menu items

### ISSUE THREAD

**Issue by anonimo82** [termux/termux-packages#11683]
Hello everyone.
I successfully installed proot-distro ubuntu and built zink, so I now have HardWare acceleration with Termux-X11, and I installed my Apps with proot-distro, now I have a sort of Ubuntu with HW acceleration and I can launch virtually any App from Terminal (Termux session, when doing "xhost +, proot-distro login ubuntu --shared-tmp, and setting variables (like DISPLAY)".
Now, I'd like to have my Apps in the Applications menu, so something which can "hook" my Apps from proot-distro and show them in the menu.
Is it possible at all?

I also have another, minor issue: when I'm not using MHL, I have a very small interface (I labor to see any text or GUI elements - buttons, menus, etc). Is it possible to lower the resolution to, say, 1280x720?

Thanks for any help.

**Comment by truboxl** [comment]
Since the mentioned app `lmms` and window manager `fluxbox` are from proot-distro Ubuntu, there's nothing can be done in Termux.

If you need to have an entry in your Application Menu, refer online guides on creating `.desktop` for `lmms` as mentioned by others.
