### ISSUE TITLE
Suggestion:  have resolv-conf show system resolver(s) by default

### ISSUE THREAD

**Issue by dredmorbius** [termux/termux-packages#1168]
AFAICT the Termux resolv-conf package consists simply of the static file $PREFIX/etc/resolv.conf, and that points to the default Google nameservers 8.8.8.8 and 8.8.4.4

Any possibility of having this follow whatever the Android default nameserver(s) are instead?  Or at least as an option?

(NB:  This isn't a huge problem, but I just reinstalled most/all Termux packages and was stymied by my resolver behaviour ... varying.)

**Comment by fornwall** [comment]
See #1174 for more information (I'm closing this issue in favour of that one).

Most packages use libc and thus the android default, only certain packages (`dnsutils`, `nmap` and `dirmngr` from gnupg2) uses resolv.conf directly and would need to be patched to instead use the android system ones.
