### ISSUE TITLE
[Bug]: termux can't detect SwiftKey keyboard 

### ISSUE THREAD

**Issue by lewdpatriot** [termux/termux-packages#11689]
### Problem description

Can't detect SwiftKey keyboard, so I have to switch to other keyboard to use it

### What steps will reproduce the bug?

open the app and try to type using swiftkey.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=576
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
Updatable packages:
libnghttp2/stable 1.49.0 aarch64 [upgradable from: 1.48.0]
libx11/stable 1.7.2-2 aarch64 [upgradable from: 1.7.2-1]
termux-tools version:
1.27.0
Android version:
11
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu May 5 20:25:30 CST 2022 aarch64 Android
Device manufacturer:
realme
Device model:
RMX2002
```

**Comment by T-Dynamos** [comment]
What do you mean by 
> Can't detect SwiftKey keyboard, so I have to switch to other keyboard to use it

**Comment by lewdpatriot** [comment]
> What do you mean by
> 
> > Can't detect SwiftKey keyboard, so I have to switch to other keyboard to use it

pressing keys dosen't work

**Comment by T-Dynamos** [comment]
I remember this bug, After typing you have to type a space to see what you have typed. This can be easily fixed by turning off a option in Swift Keyboard's Settings > Typing > (I forgot option)

**Comment by agnostic-apollo** [comment]
https://wiki.termux.com/wiki/Terminal_Settings#Workaround_issues_with_some_keyboards

**Comment by lewdpatriot** [comment]
Got it. Thanks again
