### ISSUE TITLE
[Package]: lite

### ISSUE THREAD

**Issue by babaric-dev** [termux/termux-packages#11690]
### Package description

It is a new text editor with many features, and it is extremely lightweight.

### Source code URL

https://github.com/rxi/lite

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by T-Dynamos** [comment]
I found no difference between lite and lite-xl.
and we already have lite-xl.
