### ISSUE TITLE
[Package]: httrack

### ISSUE THREAD

**Issue by maaaaz** [termux/termux-packages#11697]
### Package description

HTTrack is a [free](http://www.gnu.org/philosophy/free-sw.html) ([GPL](http://www.gnu.org/licenses/gpl.txt), libre/free software) and easy-to-use offline browser utility.

It allows you to download a World Wide Web site from the Internet to a local directory, building recursively all directories, getting HTML, images, and other files from the server to your computer. HTTrack arranges the original site's relative link-structure. Simply open a page of the "mirrored" website in your browser, and you can browse the site from link to link, as if you were viewing it online. HTTrack can also update an existing mirrored site, and resume interrupted downloads. HTTrack is fully configurable, and has an integrated help system.

WinHTTrack is the Windows (from Windows 2000 to Windows 10 and above) release of HTTrack, and WebHTTrack the Linux/Unix/BSD release. 

### Home page URL

https://www.httrack.com/page/1/en/index.html

### Source code URL

https://www.httrack.com/page/1/en/index.html

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Some compilation information there: https://github.com/Hax4us/httrack_In_termux

**Comment by sylirre** [comment]
Closing since this is a request of already present package.

**Comment by maaaaz** [comment]
Sorry, being sure that had checked, maybe in the wrong repo :)
