### ISSUE TITLE
[Package]: nmon

### ISSUE THREAD

**Issue by maaaaz** [termux/termux-packages#11692]
### Package description

[`nmon`](https://pkgs.org/download/nmon) is a performance monitor for Linux

### Home page URL

http://nmon.sourceforge.net/pmwiki.php

### Source code URL

http://nmon.sourceforge.net/pmwiki.php?n=Site.CompilingNmon

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by maaaaz** [comment]
I tried unsuccessfully to find an alternative to `nmon` in Termux: https://itsfoss.com/linux-system-monitoring-tools/

So we all look forward having `nmon` :-)

**Comment by Grimler91** [comment]
I guess it requires root since it parses /proc and/or /sys

**Comment by maaaaz** [comment]
No, you can use nmon without being root.

**Comment by Grimler91** [comment]
On android?

**Comment by maaaaz** [comment]
I don't know, but on Linux for sure.

**Comment by maaaaz** [comment]
Thanks !
