### ISSUE TITLE
[Package]: vlan

### ISSUE THREAD

**Issue by maaaaz** [termux/termux-packages#11695]
### Package description

This package contains integration scripts for configuring vlan interfaces via ifupdown (/etc/network/interfaces).

For further details see vlan-interfaces(5) man page in this package. Please note that these integration scripts only supports a limited set of interface naming schemes, which means you might be better off with writing your own ifupdown hooks using ip(route2) directly in /etc/network/interfaces rather than using this package. 
It currently also ships a wrapper script for backwards compatibility called vconfig, that replaces the old deprecated vconfig program with translations to ip(route2) commands.
This compatibility shim might be dropped in future releases, please use ip(route2) commands directly.
Your kernel needs vlan support for this to work, see "modinfo 8021q".

https://pkgs.org/download/vlan

### Home page URL

https://tracker.debian.org/pkg/vlan

### Source code URL

https://salsa.debian.org/debian/vlan

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by sylirre** [comment]
Just curious, what usage of **vlan** on Android devices? Note that vlan is not available in standard kernel builds for Android OS.

**Comment by maaaaz** [comment]
Thanks for asking! 

For instance, with an small-factor Android device (TV box or anything else), when :
* you don't want to connect your untrusted device on a trusted network
* or perform penetration tests on a network which requires your device to be in a specific VLAN

I didn't know it was not present in standard kernel build, as Android is a regular OS, and regular OS have this capability since several years (Windows, Linux etc.).

**Comment by maaaaz** [comment]
Thanks !
