### ISSUE TITLE
[Package]: pev

### ISSUE THREAD

**Issue by maaaaz** [termux/termux-packages#11702]
### Package description

`pev` is a tool to get information of PE32/PE32+ executables (EXE, DLL, OCX etc) like headers, sections, resources and more.

https://pkgs.org/download/pev

### Home page URL

https://github.com/merces/pev

### Source code URL

https://salsa.debian.org/debian/pev

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
This repository has been archived by the owner. It is now read-only.

> Packages must be active, well-known projects
> Software available in major Linux distributions has more chances to be included into Termux repositories. We will not accept outdated, dead projects as well as projects which do not have active community.
