### ISSUE TITLE
[Information] packages.termux.dev may be shutdown at some point

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#11705]
On Sunday 28th of August Fosshost will decommission its service that we use for hosting `packages.termux.dev`. 

Termux have to find another provider, probably we will go for a paid service using funds from our [open collective](https://opencollective.com/termux) (thanks all you backers!). Since we only have a few days to deal with this there will definitely be some issues in the interim. To try to decrease amount of issues we will redirect [packages.termux.dev](https://packages.termux.dev) to the [grimler.se](https://grimler.se) mirror, and change so default mirror is that one.

If you have issues installing/updating starting 28th of August you might have to change to another mirror with the `termux-change-repo` tool.

**Comment by buttaface** [comment]
> Termux have to find another provider, probably we will go for a paid service using funds from our [open collective](https://opencollective.com/termux)

Glad to hear it, as [that's what I suggested last year](https://github.com/termux/termux-packages/issues/6348#issuecomment-833341732). We should also look into cutting wasted traffic from having our CI download the same packages over and over again.

**Comment by buttaface** [comment]
As I also suggested last year, the opencollective donation link should be added to the Termux motd so all actively updating users see it. Ideally, we'd pre-fund enough for at least 6 months of paid hosting before signing up for our own service, while I don't think the current balance would even pay for a couple months.

**Comment by sylirre** [comment]
FossHost continues to work in near future:
> To All Projects Using Fosshost's AARCH64 Platform:
>
> We're writing today to update you regarding the future of Fosshost, and our AARCH64 platform specifically.
>
> Today following an emergency meeting of the Fosshost directors we've taken the decision to continue operating AARCH64 for the near-term future.
>
> The team will be working from a list of critical issues with our project compiled by our Thomas, our CEO, over the next several months, with an eye to ensuring sustainability for our project, transparency with our community and, above all, justifying the trust so many FOSS projects have shown in Fosshost.
>
> As part of this decision applications will remain closed until further notice.
>
> We look forward to sharing details of the challenges we face with our project as well as our plans for the future.

Doesn't mean that we shouldn't look for a new host though.

**Comment by agnostic-apollo** [comment]
Yes, we should still look. Can even put fosshost as backup, specially if it shuts down after near-term future.

**Comment by agnostic-apollo** [comment]
I guess should also try to maintain a minimum balance for hosting costs in our open collective from now on and make payouts to devs as long as the balance would remain above the limit.

**Comment by Grimler91** [comment]
Closing this since fosshost seem to continue to be available for now, but as mentioned we will anyways look at setting up a new, more reliable, main host.

**Comment by buttaface** [comment]
Is the cloudflare mirror down now?

**Comment by agnostic-apollo** [comment]
Yes, fosshost server issue. Didn't get time to look more into it, likely fosshost would need to be notified since issue hasn't been solved automatically and network status shows nothing down and no tweet.

>Issue seems to be ipv6 connection to fosshost, including ssh over ipv6. But ipv4 like [packages.termux.dev](http://packages.termux.dev/) or ssh over ipv4 is working. Rebooting didn't help.

https://matrix.to/#/!rrHhKvLYtBVDOISphu:gitter.im/$qdJsDcdZ3D5wWMJO_SUtg71zbCYlw7njhtJrDso6vSI?via=gitter.im&via=matrix.org&via=aria-net.org

https://fosshost.org/status

https://support.fossho.st/

**Comment by agnostic-apollo** [comment]
I created a fosshhost ticket a few hours ago, waiting for response.

**Comment by agnostic-apollo** [comment]
>The issue with IPv6 connectivity seems to have been resolved by the DC. There was an issue with routing so it wasn't announced to the global internet.

Fosshost support says issue has been resolved on their end.
