### ISSUE TITLE
How to install .exe file in gui environment

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#11714]
Please give commands to install it

**Comment by rallg** [comment]
Normalley, .exe files are windows executables. They will not work on Termux, which is based on Linux. So, the best available command may be,  "Buy yourself a computer with Windows operating system."

**Comment by IntinteDAO** [comment]
Well, in theory you can use ARM64 Windows apps on Termux using Wine, but most (99.9%) Win Apps are not for ARM64

If you want to use Wine application, you can use Exagear for that, but it's risky, cause Exagear is not supported and you can only download it from strange websites
