### ISSUE TITLE
[Bug]: sed ignores LC_ALL=C despite documentation shown by searching LC_ALL in: info sed

### ISSUE THREAD

**Issue by jidhub** [termux/termux-packages#11719]
### Problem description

Version 4.8 of sed ignores the environment variable LC_ALL on termux, but not on Debian Linux or on Nixos Linux.

LC_ALL=C specifies to sed, and other commands like sort, to parse bytes instead of multi-bytes, according to the documentation.

### Steps to reproduce the behavior.

pkg install sed
info sed
 # search for LC_ALL then copy the command, which is:
printf 'a\u03A3b' | LC_ALL=C sed 's/./X/g'

This prints "XXX", but documentation specifies that it should print "XXXX" instead.

### What is the expected behavior?

It shoud conform to the documentation: sed should print XXXX instead of XXX.

### System information

* Termux application version: 0.118.0 installed by Fdroid.org
* Android OS version: 12 (yeah I know, officially not supported but it works nonetheless fine enough, I appreciate very much the result); [adb shell "/system/bin/device_config put activity_manager max_phantom_processes 2147483647"](https://github.com/termux/termux-app/issues/2366#issuecomment-955149284) somehow works
* Device model: Samsung Fold 3 5G SM-F936B/DS

**Comment by xtkoba** [comment]
Sorry for the spammy "added a commit" messages.

In fact Android (Bionic libc) does support C locale, but we patch NDK and force UTF-8 locale to avoid some sort of bugs; see message in commit a328a50407c41d634d48c886c4c198465b817d4a. FYI, `MB_CUR_MAX` in <a href="https://github.com/termux/termux-packages/blob/126e1d0c1ac793e8ae59489b09db8bea0a15265b/ndk-patches/langinfo.h">`<stdio.h>`</a> and `nl_langinfo{,_l}` in <a href="https://github.com/termux/termux-packages/blob/126e1d0c1ac793e8ae59489b09db8bea0a15265b/ndk-patches/23c/stdlib.h.patch">`<langinfo.h>`</a> are affected.

https://github.com/termux/termux-packages/blob/126e1d0c1ac793e8ae59489b09db8bea0a15265b/ndk-patches/23c/stdlib.h.patch#L17
https://github.com/termux/termux-packages/blob/126e1d0c1ac793e8ae59489b09db8bea0a15265b/ndk-patches/langinfo.h#L146

PR #11958 is a proposed way to effectively revert these modifications to NDK and yet avoid potential bugs with respect to locales.

**Comment by malferta49** [comment]
What is the output of: LC_ALL=C pacman -V|tail -n3|base32|head -1 ?
