### ISSUE TITLE
[Package]: nelua

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#11726]
### Package description

Minimal, efficient, statically-typed and meta-programmable systems programming language heavily inspired by Lua, which compiles to C and native code.

### Home page URL

https://nelua.io

### Source code URL

https://github.com/edubart/nelua-lang

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Everything you need is in the GitHub repository and a simple `make` gets the job done. This should be an easy addition.

**Comment by 2096779623** [comment]
https://github.com/2096779623/termux-packages/runs/8050524179?check_suite_focus=true
```shell
gcc \
	-DMAXRECLEVEL=400 -DLUA_USE_RPMALLOC -DNDEBUG -DLUA_USE_LINUX  \
	-Isrc/lua  \
	-std=gnu99 -O2  \
	src/hasher.c src/lfs.c src/luainit.c src/onelua.c src/sys.c src/lpeglabel/lpcap.c src/lpeglabel/lpcode.c src/lpeglabel/lpprint.c src/lpeglabel/lptree.c src/lpeglabel/lpvm.c src/srpmalloc/srpmalloc.c  \
	-o nelua-lua \
	-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,-E  -lm -ldl 
gcc: error: unrecognized command-line option ‘-static-openmp’
make: *** [Makefile:81: nelua-lua] Error 1
Error: Process completed with exit code 2.
```

I can't find `-static-openmp` in Makefile :p .

**Comment by ravener** [comment]
It's right there after the -L, also you will need to patch the Makefile to use `CC` variable instead of calling `gcc` directly, since Android cross-compilers are involved.

On another note I personally faced that issue of the flag not recognized but fixed it by updating my llvm installation so too old versions does not support it. I assume this is running in CI? If so, then the lack of the `CC` variable patching explains it, it might have tried to use the distribution's `gcc` which may not support the flag.
