### ISSUE TITLE
Package Request: openldap

### ISSUE THREAD

**Issue by denzuko** [termux/termux-packages#1172]
I noticed we have krb5 but no ldap, smb or snmp. Could we get ldap support?

**Comment by its-pointless** [comment]
Iv added an openldap package to my repo could you test it please?

**Comment by denzuko** [comment]
looks good

**Comment by xeffyr** [comment]
Package available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install openldap
```

Untested.

**Comment by kusmantopratama** [comment]
@xeffyr how to enable ldap as php extension?
