### ISSUE TITLE
Fail to connect ssh to IDN

### ISSUE THREAD

**Issue by sntgchns** [termux/termux-packages#11729]
### Problem description

Hello, it is a pleasure for me to get in touch with you, I cannot leave aside the comment that the Temux application is wonderful, it works very well.
My request is about wanting to start an ssh connection to a server that is in an international domain name (IDN) ->
https://en.m.wikipedia.org/wiki/Internationalized_domain_name
For example, when connecting via "ssh name@ñoñañe
![Screenshot_20220826-200019_Termux](https://user-images.githubusercontent.com/86539574/187001630-4a5b1721-b99c-4e0b-9749-12362b278754.jpg)
.com]" an error is returned (attached file), something that does not happen on linux or windows when doing ping or ssh to that domain name or others IDN's.
Without further ado, thank you!

### Steps to reproduce the behavior.

Do ssh name@oñoña.com

### What is the expected behavior?

Connect to ssh name@oñoña.com

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
Seem to work fine for me. Please fill in the bug report template and provide info about your device. What is your output of `termux-info`?

**Comment by Grimler91** [comment]
You could also try converting url to punnycode first and see if that makes a difference: https://www.sslchecker.com/idn_converter

**Comment by sntgchns** [comment]
Thankyou for the response. Doing the request with the 'translated' IDN works fine, my device is an smartphone, samsung galaxy A52.![Screenshot_20220827-104041_Termux.jpg](https://user-images.githubusercontent.com/86539574/187032853-aa819199-4ca5-4b40-9372-d20083495b1b.jpg)
Best regards

**Comment by Grimler91** [comment]
Can you visit the site in a normal browser on your device?

**Comment by sntgchns** [comment]
> Can you visit the site in a normal browser on your device?

Yes, without problem.

**Comment by Grimler91** [comment]
I'll retract my previous statement, doesn't seem to work for me either, except if url is converted first

**Comment by licy183** [comment]
I can reproduce this issue on my Linux Laptop (Ubuntu 22.04), but I cannot reproduce it on a Windows machine. So is it an issue of `openssh`?

```
~$ ssh test@soñora.com
ssh: Could not resolve hostname so\303\261ora.com: Name or service not known
~$ ping soñora.com
PING soñora.com (104.21.73.74) 56(84) bytes of data.
64 bytes from 104.21.73.74 (104.21.73.74): icmp_seq=1 ttl=128 time=258 ms
^C
--- soñora.com ping statistics ---
2 packets transmitted, 1 received, 50% packet loss, time 1002ms
rtt min/avg/max/mdev = 258.034/258.034/258.034/0.000 ms
``` 

```
>ssh -o ConnectTimeout=3 test@soñora.com
ssh: connect to host so\303\261ora.com port 22: Connection timed out

>ping soñora.com

正在 Ping xn--soora-pta.com [2606:4700:3036::6815:494a] 具有 32 字节的数据:
来自 2606:4700:3036::6815:494a 的回复: 时间=279ms

2606:4700:3036::6815:494a 的 Ping 统计信息:
    数据包: 已发送 = 1，已接收 = 1，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 279ms，最长 = 279ms，平均 = 279ms
Control-C
^C
```

Actually, `openssh` uses `getaddrinfo` to resolve domains (https://github.com/openssh/openssh-portable/blob/master/ssh.c#L271), but `getaddrinfo` seems unable to resolve the domains with IDN on Ubuntu 22.04 or Android.

```
# test-program.c
#include <arpa/inet.h>
#include <netdb.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>

int main(int argc, char **argv) {
  if (argc != 2) {
    printf("Usage: %s hostname|ip\n", argv[0]);
    exit(1);
  }
  struct addrinfo hints;
  struct addrinfo *res, *cur;
  int ret;
  struct sockaddr_in *addr;
  char ipbuf[16];
  int port;

  memset(&hints, 0, sizeof(struct addrinfo));
  hints.ai_family = AF_INET;   /* Allow IPv4 */
  hints.ai_flags = AI_PASSIVE; /* For wildcard IP address */
  hints.ai_protocol = 0;       /* Any protocol */
  hints.ai_socktype = SOCK_DGRAM;
  ret = getaddrinfo(argv[1], NULL, &hints, &res);
  if (ret != 0) {
    fprintf(stderr, "%s\n", gai_strerror(ret));
    exit(1);
  }

  for (cur = res; cur != NULL; cur = cur->ai_next) {
    addr = (struct sockaddr_in *)cur->ai_addr;
    printf("IP: %s\n", inet_ntop(AF_INET, &addr->sin_addr, ipbuf, 16));
  }
  freeaddrinfo(res);
  exit(0);
}
```

Ubuntu 22.04:

```
~$ ./output soñoña.com
Name or service not known
```

Termux (on Bluestacks):

```
~$ ./output soñoña.com
No address associated with hostname
```

**Comment by ChiefMikeK** [comment]
Q: Does percent encode %F1 work?
> so%F1o%F1a.com

**Comment by ChiefMikeK** [comment]
Q: Does percent encode %F1 work?
> so%F1o%F1a.com  

By the way 303=␠̃(combing tilde) and 261=ɡ(IPA voiced velar stop)

**Comment by licy183** [comment]
> Q: Does percent encode %F1 work?
> 
> > so%F1o%F1a.com

Won't work. URL Decoding doesn't support by `getaddrinfo`.

**Comment by xtkoba** [comment]
Kind of upstream issue because OpenSSH does not have option to enable IDN support.

A workaround is to use `idn2` command bundled with the `libidn2` package:

```
$ curl http://españa.icom.museum/
curl: (6) Could not resolve host: españa.icom.museum

$ curl http://`idn2 españa.icom.museum`/
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

(Note that `curl` could be built to support IDN which as of now is not enabled in our package.)
