### ISSUE TITLE
vim syntax works c#

### ISSUE THREAD

**Issue by ExtinctDrift19** [termux/termux-packages#11736]
### Discussed in https://github.com/termux/termux-packages/discussions/11727

<div type='discussions-op-text'>

<sup>Originally posted by **ExtinctDrift19** August 27, 2022</sup>
works syntax color c#</div>

**Comment by ravener** [comment]
Look for plugins like https://github.com/OrangeT/vim-csharp

This is not related to Termux, we do not package vim plugins.
