### ISSUE TITLE
Package Request: c-kermit

### ISSUE THREAD

**Issue by denzuko** [termux/termux-packages#1173]
Any chance we can get c-kermit added?

**Comment by gtellalov** [comment]
I didn't succeed in building ckermit, because it seems that it requires glibc. I built gkermit instead. You can find it here: https://github.com/gtellalov/termux-packages/commit/2de01eecde1d7baf88ae336c172521976495c86c

**Comment by denzuko** [comment]
The scripting features of ckermit would have been a big help but at least this is a start. Thanks for porting gkermit @gtellalov.

**Comment by sdrausty** [comment]
@denzuko ckermit is available via Arch Linux in Termux PRoot. 
```
[11:12 home ]$ pacman -Ss kermit
community/ckermit 9.0.302-6                                                      Portable scriptable network and serial communication software
```
See https://sdrausty.github.io/TermuxArch/ for more information.
