### ISSUE TITLE
[Bug]: adb cannot locate symbol "pthread_cond_clockwait"(platform-tools-33.0.1)

### ISSUE THREAD

**Issue by wyhxf** [termux/termux-packages#11731]
### Problem description

~ $ adb
CANNOT LINK EXECUTABLE "adb": cannot locate symbol "pthread_cond_clockwait" referenced by "/data/data/com.termux/files/usr/bin/adb"...

### What steps will reproduce the bug?

~ $ adb
CANNOT LINK EXECUTABLE "adb": cannot locate symbol "pthread_cond_clockwait" referenced by "/data/data/com.termux/files/usr/bin/adb"...

### System information

termux-info:
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=17842
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.iscas.ac.cn/termux/apt/termux-main stable main
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
Updatable packages:
All packages up to date
termux-tools version:
1.29.1
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Tue Jun 7 11:26:07 CST 2022 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
SPN-AL00

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/blob/f103ac030a7fcc42e97f1e1773564d21af7ec26e/packages/android-tools/build.sh#L5

Don't use your own built adb to report bugs.
