### ISSUE TITLE
[Package]: monkey audio port

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#11730]
### Package description

For adding support of APE audio file format to shntool

```
TERMUX_PKG_HOMEPAGE=https://monkeysaudio.com/
TERMUX_PKG_DESCRIPTION="Lossless Monkey audio codec"
TERMUX_PKG_LICENSE=custom
TERMUX_PKG_LICENSE_FILE=LICENSE
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=3.99.6
TERMUX_PKG_SRCURL=https://github.com/fernandotcl/monkeys-audio/archive/refs/tags/release-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=0d279bf2042ac5a8fc57674de0f20a4c78f8f33926346d98949bc312c76860f1
TERMUX_PKG_DEPENDS="yasm"
TERMUX_PKG_FORCE_CMAKE=true
```

### Home page URL

https://monkeysaudio.com/

### Source code URL

https://github.com/fernandotcl/monkeys-audio/archive/refs/tags/release-3.99.6.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by tathastu871** [comment]
cp: cannot stat '/data/data/com.termux/files/home/.termux-build/_cache/android-r25-api-24-v1/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so': No such file or directory

**Comment by 2096779623** [comment]
ndk-multilib

**Comment by rallg** [comment]
If you read the Widipedia page regarding Money's Audio (and other resources), you will note that (1) Although in principle it can be used anywhere, it is not open source. (2) It is CPU-intensive, meaning that it is unlikely that most Android devices would be able o use it properly.

**Comment by tathastu871** [comment]
> If you read the Widipedia page regarding Money's Audio (and other resources), you will note that (1) Although in principle it can be used anywhere, it is not open source. (2) It is CPU-intensive, meaning that it is unlikely that most Android devices would be able o use it properly.

Not cpu intensive already used it within termux proot ubuntu

**Comment by tathastu871** [comment]
Any prgoess
cmake .. make make install seems to work

**Comment by xtkoba** [comment]
There is no permission to redistribute, as mentioned <a href="https://lists.debian.org/debian-legal/2007/09/msg00079.html">here</a>. We cannot legally package this.

**Comment by tathastu871** [comment]
The Monkey's Audio SDK and source code can be freely used to add
> APE format playback, encoding, or tagging support to any product, free
> or commercial
