### ISSUE TITLE
[Package]: LÖVE Game Framework

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#11742]
### Package description

LÖVE is an awesome 2D game framework for Lua.

### Home page URL

https://love2d.org

### Source code URL

https://github.com/love2d/love

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

There seems to be already `love10` in x11-packages but it's an outdated version and seems to be added due to a dependency for another package. I request the latest version `11.4` to be packaged for general use within an x11 environment (uses SDL) the previously added package might be conflicting though so be careful of that.

**Comment by OrdinaryEnder** [comment]
> ### Package description
> 
> LÖVE is an awesome 2D game framework for Lua.
> ### Home page URL
> 
> https://love2d.org
> ### Source code URL
> 
> https://github.com/love2d/love
> ### Packaging policy acknowledgement
> 
>     * [x]  I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).
> 
> 
> ### Additional information
> 
> There seems to be already `love10` in x11-packages but it's an outdated version and seems to be added due to a dependency for another package. I request the latest version `11.4` to be packaged for general use within an x11 environment (uses SDL) the previously added package might be conflicting though so be careful of that.

![Screenshot_2022_0828_172047](https://user-images.githubusercontent.com/109149031/187069117-0b9ea6d1-1f10-4863-9eab-5fbe44f289e2.png)

**Comment by OrdinaryEnder** [comment]
It's already available

**Comment by 2096779623** [comment]
> It's already available

>> There seems to be already love10 in x11-packages but it's an outdated version and seems to be added due to a dependency for another package. I request the latest version 11.4 to be packaged for general use within an x11 environment (uses SDL) the previously added package might be conflicting though so be careful of that.

**Comment by OrdinaryEnder** [comment]
> > It's already available
> 
> > > There seems to be already love10 in x11-packages but it's an outdated version and seems to be added due to a dependency for another package. I request the latest version 11.4 to be packaged for general use within an x11 environment (uses SDL) the previously added package might be conflicting though so be careful of that.

Seem we just need update for this

**Comment by 2096779623** [comment]
> Seem we just need update for this

We don't know why xtkoba named this package `love10` .

**Comment by OrdinaryEnder** [comment]
> We don't know why xtkoba named this package `love10` .
Maybe for version?

**Comment by 2096779623** [comment]
> Maybe for version?

It's unlikely.

**Comment by sylirre** [comment]
Seems like for version. This package was required for `bytepath` package (disabled) which seems to be not maintained on upstream anymore.

**Comment by ravener** [comment]
Also audio seems to be broken in the existing package:
```
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
```
Worth checking this issue as the package gets updated.

**Comment by OrdinaryEnder** [comment]
> 

Use mpv method for that

**Comment by USMP-lancer** [comment]
tbh i personally want this to play mari0 on the go, id used the mobile app but it has a sizing issue, being too large
