### ISSUE TITLE
[Package]: flyctl 

### ISSUE THREAD

**Issue by pk-628996** [termux/termux-packages#11759]
### Package description

it is a command line tool to manage app on fly.io

### Home page URL

fly.io

### Source code URL

https://github.com/superfly/flyctl

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
What's wrong with the flyctl package we already have? https://github.com/termux/termux-packages/blob/master/packages/flyctl/build.sh

**Comment by pk-628996** [comment]
how to install

**Comment by pk-628996** [comment]
I cannot install as i have arm cpu please fix it both for calibre and flyctl

**Comment by sylirre** [comment]
One or more of Go dependencies used by Flyctl **does not support 64bit CPUs** at source code level. Therefore we exclude packaging for ARM and i686 devices.

This is not Termux-specific issue. 32bit builds seem to be stopped after https://fly.io/blog/fly-changelog-may-15th-2020/.
