### ISSUE TITLE
[Package]:  Inno Setup

### ISSUE THREAD

**Issue by rc-chuah** [termux/termux-packages#11766]
### Package description

Inno Setup is a free installer for Windows programs. First introduced in 1997, Inno Setup today rivals and even surpasses many commercial installers in feature set and stability.

### Home page URL

https://jrsoftware.org/isinfo.php

### Source code URL

https://github.com/jrsoftware/issrc

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
Are you kidding? This software can only run on Windows.

Btw, we can package `innoextract`.
