### ISSUE TITLE
Does Anyone Want to Have More Native Space on Device?

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1176]
After an enormous file is created on the external SD card, it is formatted as a [native Android filesystem]( https://www.google.com/search?q=what+is+the+android+file+system). Then it is **mounted** as a native filespace **in $HOME as** the **nonroot** Termux single user using [`mount loopback device`](https://www.google.com/search?q=mount+loopback+device) or similar.

This issue is fairly simple in Linux: **create file of a specific GB size > format filesystem in file > mount filesystem in file via loop device nonroot**. This sequence is impossible today on external micro SD storage in Termux on Android. You might even be mounting a filesystem from a file via loop device nonroot on a notebook or desktop without knowing it when you mount a USB stick, CD, DVD or similar.

![screenshot_20170804-121408](https://user-images.githubusercontent.com/27742457/28977096-aac4fb42-790e-11e7-96f9-775afe3924dd.png)

Creating and utilizing an enormous native Android filesystem on the external SD card should be doable in some `chroot` or `proot` fashion, possibly even without using `chroot` or `proot`. What is your opinion? 

https://plus.google.com/109614420080028230010/posts/H7Av31MSK39

Even though this is a fairly simple issue in Linux **(create file > format filesystem in file > mount filesystem in file via loop device)**, it is impossible in Termux at present.﻿

Https://www.google.com/search?q=mount+non+root+user+site%3Atldp.org 
This has been added here to clarify root and nonroot mounts. Linux Deploy https://github.com/meefik/linuxdeploy mounts a beautiful filesystem after downloading on device...

What about "Debian Noroot"? Does this app have the code we are seeking? It appears to mount an image from a file. "The scripts for creating Debian images are located in directory "img" https://github.com/pelya/debian-noroot/tree/master/img "To prepare image, run these scripts:" from https://github.com/pelya/debian-noroot/blob/master/README.md

https://play.google.com/store/apps/details?id=com.cuntubuntu

![screenshot_20170803-132456](https://user-images.githubusercontent.com/27742457/28945285-ded31ea0-7873-11e7-97a4-8d711da227b5.png)

Screenshot of Debian Noroot running on an Android smartphone.

https://github.com/pelya/debian-noroot

"Run Debian on top of Android with a single click. No root required! Should work on any high-end device! Unleash full unrestricted desktop environment onto your mobile device! Instant frustration guaranteed! (unless you're using mouse or stylus) [and keyboard]."

```
git clone https://github.com/pelya/debian-noroot
cd debian-noroot
git submodule init
git submodule update //doesn't work, requires passphrase!?
ack loop
ack mount 
ack device
ack img
```

**Disclaimer:** I usually only use Termux in Android, the APKs and the other goodies built on device (a smartphone). Please see https://sdrausty.github.io/buildAPKs/reallyEasilyBuildAndroidAPKsOnDevice **This issue was last reedited 20170803 UTC for clarity of topic.**

**Comment by vishalbiswas** [comment]
mounting requires root. mounted virtual file system is slower than the real deal. maximum file size on sdcard will be 3.9GB, so thats the maximum $PREFIX/home size. I have 6 GB on internal.

**Comment by Harshiv-Patel** [comment]
there is no execute permission for external SD card(usually) but there are many files that do not require execute permission like clang's 'include' and 'lib' directories or '$vimruntime' and such other files. These types of files can be safely put in "~/storage/external-1/".
Perhaps one could set symlinks for such directories and keep only 'bin' folder in internal device storage. 
It would be less reliable compared to internal storage as well as slower.
Please share your views about this idea.

**Comment by sdrausty** [comment]
@vishalbiswas sizeTest.file was 4799196216 bytes. 4.8G is bigger than 3.9G. Any idea on how to make `mount` mount file system as Termux user is a hurdle just as formatting is. This should be doable...

Search `mount non root user`
https://unix.stackexchange.com/questions/96625/allow-non-superusers-to-mount-any-filesystem

**Comment by sdrausty** [comment]
@Harshiv-Patel This issue is about creating a virtual space on the external SD.

**Comment by sdrausty** [comment]
Source code links:
YAFFS http://www.aleph1.co.uk/gitweb/?p=yaffs2.git;a=summary
mount https://github.com/karelzak/util-linux
LVM https://github.com/steven676/lvm2

This looks like three package requests. Can somebody add the `package request` label please.

**Comment by sdrausty** [comment]
Quite possibly this issue can be closed, excepting LVM in lew of https://github.com/termux/termux-app/issues/375  Open
Is it possible to grant permission for Termux to use loop devices? #375

 If anyone wants, it can always be brought up as a separate package request for LVM (Logical Volume Manager).

**Comment by sdrausty** [comment]
Can https://wiki.termux.com/wiki/PRoot help in resolving this matter? 

https://github.com/termux/proot

**Comment by sdrausty** [comment]
__Evidently, we can launch activities without root by passing the --user 0 flag to am start:__ from https://github.com/termux/termux-app/issues/206

**Comment by sdrausty** [comment]
@xeffyr suggests porting a kernel subsystem to Termux to accomplish mount in Termux userspace.  This appears to be a valuable doable suggestion.

**Comment by sdrausty** [comment]
"Can we create an addon like Termux:Widget that would emulate the kernel mount subsystem?"  https://github.com/termux/termux-app/issues/511  

> Is there a possibility to create something like Termux:Widget that would emulate the kernel subsystem? Or a Termux package? This should enable much space on devices.

**Comment by timnolte** [comment]
So given my Termux problems:
- it can't see my SD Card when running under ARC on my Chromebook
- it has no permissions to set the execute bit on files within ~/storage, like under Downloads
- it can't even mount a loopback file

I'm feeling like my hopes of a local VIM development environment that can be easily backed up and restored are doomed. I was really hoping for a full local web development environment via Termux but without at least one of those options about working it's pretty much a no go without going back to developer mode with crouton, which sort of defeats the point of a Chromebook.

**Comment by projectextremum** [comment]
As far as I know, you can't set execute permissions on the files without root on SD card.

`proot` could have an extension for mounting a filesystem image virtually, it needs some work and no one seem to have done it though.

@sdrausty Noroot debian seems like simple debootstrap in its home directory.

But you can mount non-executable dirs like `usr/share` to external SD card via symbolic links, which will save some space.

By the way I would like to know if there is a way to get `pacman` not to install man pages and i18n / Unicode packages. Perhaps I am not getting time to read `pacman`/`libalpm`docs.

Many apps do not allow to be moved to SD card although there is no problem with that. Someone may write a script to unpack such `apk`s, edit `storageLocation` in manifest and repackage then sign it. 

Last way is to get a better SD card and and set default storage to SD card, if a phone permits it.

I am also curious to know if all these binary stuff can be included in an add-on app, say named com.termux.termuxarch, and the add-on app then could be moved to SD card. And it should allow accessing filesystem in /mnt/asec/com.termux.termuxarch-2/assets/rootfs at least as a `cow` base layer.
