### ISSUE TITLE
request MySQL

### ISSUE THREAD

**Issue by kuburan** [termux/termux-packages#1177]
Please, add `mysql-client` `mysql-server` for termux

**Comment by vishalbiswas** [comment]
mariadb is not sufficient?

**Comment by kuburan** [comment]
can i login into mysql database with mariadb ?

**Comment by kuburan** [comment]
Ohh, sorry i dunno about that, after search some article i found my answer, im new using database i'll close this issue.

**Comment by sdrausty** [comment]
Please reopen this issue. https://www.google.com/search?q=database+popularity+mqsql

**Comment by ladbhupesh** [comment]
While using mariadb in termux gives this error :

$ mysql -u root -p
Enter password:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/data/data/com.termux/files/usr/tmp/mysqld.sock' (2)

How can I fix it???
