### ISSUE TITLE
[Bug]: Cannot Link Executable : Qemu

### ISSUE THREAD

**Issue by mjuned47** [termux/termux-packages#11777]
### Problem description

Running under gdb shows :
Symbol "td_init" not found in libthread_db: undefined symbol: td_init

### What steps will reproduce the bug?

Install qemu and just run

### What is the expected behavior?

Should run normally 

### System information

Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
apt/stable 2.5.2-3 aarch64 [upgradable from: 2.3.13-3]
bash/stable 5.1.16-1 aarch64 [upgradable from: 5.1.12-2]
ca-certificates/stable 1:2022.07.19 all [upgradable from: 1:2021-10-26-0]
command-not-found/stable 2.1.0 aarch64 [upgradable from: 1.71]
coreutils/stable 9.1 aarch64 [upgradable from: 9.0]
curl/stable 7.85.0 aarch64 [upgradable from: 7.81.0]
dash/stable 0.5.11.5-1 aarch64 [upgradable from: 0.5.11.5]
debianutils/stable 5.7 aarch64 [upgradable from: 5.5]
dialog/stable 1.3-20220526-0 aarch64 [upgradable from: 1.3-20211214-0]
dos2unix/stable 7.4.3 aarch64 [upgradable from: 7.4.2]
dpkg/stable 1.21.9 aarch64 [upgradable from: 1.21.1]
ed/stable 1.18 aarch64 [upgradable from: 1.17-4]
findutils/stable 4.9.0-1 aarch64 [upgradable from: 4.8.0]
gawk/stable 5.1.1-1 aarch64 [upgradable from: 5.1.1]
gpgv/stable 2.3.7 aarch64 [upgradable from: 2.3.4]
gzip/stable 1.12 aarch64 [upgradable from: 1.11-3]
inetutils/stable 2.3-1 aarch64 [upgradable from: 1.9.4-12]
libc++/stable 25-2 aarch64 [upgradable from: 23b-3]
libcap-ng/stable 2:0.8.3 aarch64 [upgradable from: 1:0.8.3-pre1-0]
libcrypt/stable 0.2-5 aarch64 [upgradable from: 0.2-3]
libcurl/stable 7.85.0 aarch64 [upgradable from: 7.81.0]
libevent/stable 2.1.12-2 aarch64 [upgradable from: 2.1.12]
libexpat/stable 2.4.8-1 aarch64 [upgradable from: 2.4.2]
libgcrypt/stable 1.10.1-1 aarch64 [upgradable from: 1.9.4]
libgmp/stable 6.2.1-2 aarch64 [upgradable from: 6.2.1]
libgnutls/stable 3.7.6 aarch64 [upgradable from: 3.6.16-1]
libgpg-error/stable 1.45 aarch64 [upgradable from: 1.43]
liblz4/stable 1.9.4 aarch64 [upgradable from: 1.9.3]
libmpfr/stable 4.1.0-1 aarch64 [upgradable from: 4.1.0]
libnghttp2/stable 1.49.0 aarch64 [upgradable from: 1.46.0]
libssh2/stable 1.10.0-2 aarch64 [upgradable from: 1.10.0]
libtirpc/stable 1.3.2-1 aarch64 [upgradable from: 1.3.2]
libunistring/stable 1.0 aarch64 [upgradable from: 0.9.10-5]
lsof/stable 4.95.0-1 aarch64 [upgradable from: 4.94.0-1]
nano/stable 6.3 aarch64 [upgradable from: 6.0]
pcre2/stable 10.40 aarch64 [upgradable from: 10.39-2]
procps/stable 3.3.17-2 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.5-1 aarch64 [upgradable from: 23.4]
termux-am-socket/stable 1.5.0 aarch64 [upgradable from: 1.02]
termux-exec/stable 1:1.0 aarch64 [upgradable from: 1:0.9]
termux-keyring/stable 3.9 all [upgradable from: 2.4]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-1]
termux-tools/stable 1.29.1 all [upgradable from: 0.155]
unbound/stable 1.15.0-1 aarch64 [upgradable from: 1.13.2-1]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-7]
util-linux/stable 2.38 aarch64 [upgradable from: 2.37.2-1]
zlib/stable 1.2.12-1 aarch64 [upgradable from: 1.2.11-5]
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g040a88f #1 SMP PREEMPT Thu Nov 7 00:28:25 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 4

**Comment by Grimler91** [comment]
Which qemu are you running? We have quite a few qemu packages and executables

**Comment by mjuned47** [comment]
qemu-system-x86-64-headless/stable 7.0

**Comment by sylirre** [comment]
`qemu-system-x86-64` package doesn't have linking error.

> Symbol "td_init" not found in libthread_db: undefined symbol: td_init

This is not same as "Cannot link executable". Also warning is not error. In any case, this is more like gdb issue than of QEMU, as the latter does not link with `libthread_db`. I'm closing the issue.
