### ISSUE TITLE
[Information]: Android NDK r25b has released

### ISSUE THREAD

**Issue by licy183** [termux/termux-packages#11771]
https://github.com/android/ndk/wiki/Changelog-r25.
So should we update?

**Comment by Grimler91** [comment]
Yeah, we should. It is a minor release so should be no need to rebuilt libc++ dependent packages as I understand it

**Comment by buttaface** [comment]
Btw, I saw a NDK dev say somewhere on their github that their libc++ should be backwards-compatible, and that devs should file issues if that ever breaks. I thought we rebuilt on major NDK updates more because of other possible breaking changes, for example, compiler updates that change behavior.

**Comment by Grimler91** [comment]
Alright, great, then I guess we don't have to rebuild all those packages for future updates :)

**Comment by buttaface** [comment]
Found the comment I had in mind, android/ndk#1694.
