### ISSUE TITLE
[Bug]: mosh needs to be rebuilt against new libprotobuf

### ISSUE THREAD

**Issue by monoidic** [termux/termux-packages#11787]
### Problem description

The libprotobuf package has been updated without rebuilding mosh (perhaps among other reverse dependencies). Attempting to run mosh to connect to a server yields this error:
```
CANNOT LINK EXECUTABLE "mosh-client": cannot locate symbol "_ZN6google8protobuf8internal14ArenaStringPtr3SetENS2_12EmptyDefaultERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEPNS0_5ArenaE" referenced by "/data/data/com.termux/files/usr/bin/mosh-client"...
```
The immediate fix is to bump mosh's revision number to rebuild it against the new libprotobuf.
A more generic solution for issues like changing SONAMEs and symbol names etc. in the future would be nice, though it would require significant effort to introduce.

### What steps will reproduce the bug?

1. Have mosh and libprotobuf (dependency) updated to the latest available versions
2. Attempt to use mosh to connect to a server

### What is the expected behavior?

The connection succeeds.

### System information

termux-info:
```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=6196
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.dev/apt/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.29.1
Android version:
13
Kernel build information:
Linux localhost 4.19.239-gf0caf26d8587-ab8714951 #1 SMP PREEMPT Mon Jun 13 07:25:22 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 5
```

**Comment by licaon-kter** [comment]
Seeing this again.

There's nothing I can do locally?

**Comment by licaon-kter** [comment]
@sylirre mirror changing works nice, choose europe, some ok some bad, it selects one from china...

Did this twice...

Tell me which mirror is the correct one?

**Comment by licaon-kter** [comment]
Ok, mosh works, in itself.

I'm having this issue with mosh-git.

**Comment by licaon-kter** [comment]
There's none *now*, eg. Installing mosh earlier today removed it.

Dunno where I got it from so yeah, glad something works in the end :)
