### ISSUE TITLE
Rsync not working on latest dev build of Chrome OS (Version 61.0.3163.13 (Official Build) dev (64-bit))

### ISSUE THREAD

**Issue by zackbleach** [termux/termux-packages#1178]
I'm using Chrome OS Version 61.0.3163.13 (Official Build) dev (64-bit) and when running `rsync` it fails to link and start. I get:

```
CANNOT LINK EXECUTABLE "rsync": cannot locate symbol "__moddi3" referenced by "/usr/bin/rsync"...
[1]    7764 abort (core dumped)  rsync
```

From what I can see, we've had this problem with other executables after updates, i.e: https://github.com/termux/termux-packages/issues/223

**Comment by fornwall** [comment]
Thanks for reporting! These kind of problems should be fixed by rebuilding the packages with the current toolchain.

I've done so now, can you update with `pkg up` and verify that it works?

**Comment by zackbleach** [comment]
🎉 it works! Thanks for the quick 🚢
