### ISSUE TITLE
[Bug]: MariaDB error

### ISSUE THREAD

**Issue by gphg** [termux/termux-packages#11781]
### Problem description

The mariadb daemon won't start and it shutting down seconds later. I have no idea what's going on. This only happened today. I don't think I do some misconfiguration, if it requested I can send the mysql.ini.

### What steps will reproduce the bug?

1. Run mariadb daemon normally as explained on wiki `mysqld_safe &`.

### What is the expected behavior?

Run normally.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.cqupt.edu.cn/termux/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.29.1
Android version:
10
Kernel build information:
Linux localhost 4.9.190 #1 SMP PREEMPT Wed Oct 14 15:47:23 CST 2020 aarch64 Android
Device manufacturer:
ELEVATE
Device model:
LUNA G5
```

mariadb errror log originally located on `$PREFIX/usr/var/lib/mysql/localhost.err`

[localhost.err.txt](https://github.com/termux/termux-packages/files/9466731/localhost.err.txt)

**Comment by sylirre** [comment]
Seems like something with database. Stop MySQL daemon and try this:
```
cp -a $PREFIX/var/lib/mysql $PREFIX/var/lib/mysql.bak
rm -rf $PREFIX/var/lib/mysql
mkdir $PREFIX/var/lib/mysql
mysql_install_db --user=$(whoami)
```

Then start MySQL daemon again and check if it works.

**Comment by gphg** [comment]
It works. How do I restore the backed up databases?

Another question. My normal way of terminating the daemon is via pkill or simply exit the shell session. Is this safe way?

**Comment by sylirre** [comment]
> How do I restore the backed up databases?

Try this.

1. Restore old directory
  ```
  rm -rf $PREFIX/var/lib/mysql
  mv $PREFIX/var/lib/mysql.bak $PREFIX/var/lib/mysql
  ```

2. Rename or delete logfile(s): `ib_logfile0`, `ib_logfile1`, etc which exist.
  ```
  mv $PREFIX/var/lib/mysql/ib_logfile0 $PREFIX/var/lib/mysql/ib_logfile0.bak
  ```

3. Try to start MySQL server
  ```
  mysqld_safe
  ```

> My normal way of terminating the daemon is via pkill or simply exit the shell session.

```
pkill -TERM mariadbd
```

Other ways may lead to corrupted database.
