### ISSUE TITLE
[Bug]: error install pillow, libLLVM-14.so not found

### ISSUE THREAD

**Issue by aldyansyahcp** [termux/termux-packages#11794]
### Problem description

i try to install pillow termux, and then get an error like this,
<a href="https://pastebin.com/98xZpjQe"> pastebin </a>
then i searching in google to solved those error from tutorial to solving from uninstalling rust, clang, install from LDFLAGS=-L/ystem/lib64  & upgrading all packages, then i don't know the way out to solved it.

### What steps will reproduce the bug?
this history zsh to fixing error, from uninstalling rust, clang changing LDFLAGS 
![Screenshot_20220902-011738](https://user-images.githubusercontent.com/43259253/187985838-0c71b0b3-c6c6-41df-b3fb-d99ef8bb9a67.png)

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=24200
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://plug-mirror.rcac.purdue.edu/termux/termux-main stable main
# sources.list.d/termux-desktop-xfce.list
deb [trusted=yes arch=all] https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce extras
# x11-repo (sources.list.d/x11.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.29.2
Android version:
9
Kernel build information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Wed Aug 26 05:21:28 CST 2020 aarch64 Android
Device manufacturer:
asus
Device model:
ASUS_X00TD

```

**Comment by Grimler91** [comment]
I can't reproduce the issue. 

Can you run `aarch64-linux-android-clang` when not compiling pillow? Does libLLVM-14.so exist in $PREFIX/lib?

**Comment by aldyansyahcp** [comment]
> I can't reproduce the issue.
> 
> Can you run `aarch64-linux-android-clang` when not compiling pillow? Does libLLVM-14.so exist in $PREFIX/lib?

if without compiling pillow, does like this & i try search file libvvlm not found cannot executable
![Screenshot_20220902-044514](https://user-images.githubusercontent.com/43259253/188018529-12161a9c-e808-461d-82a3-0cfd6df6adfb.png)

**Comment by licy183** [comment]
I think you need to reinstall libllvm. Try `apt update &&apt reinstall libllvm`.

**Comment by licy183** [comment]
I think you need to reinstall libllvm. Try `apt update && apt reinstall libllvm`.
