### ISSUE TITLE
[Bug]: [Process completed (signal 9) - press Enter]  Error with andriod 12

### ISSUE THREAD

**Issue by rahulbharti-blog** [termux/termux-packages#11798]
### Problem description

When I update my Sumsung Galaxy A7 to **Andriod 12** . Termux work obnormaly and kill the termux process by **[Process completed (signal 9) - press Enter]**.......
Whenever I open a app like Chromium , Firefox or any havey app ( using Ram more than 250MB)  , termux crusse....... showing **[Process completed (signal 9) - press Enter]**

### What steps will reproduce the bug?

I Don't Know

### System information

termux-info: f-driod

**Comment by Grimler91** [comment]
See the [README](https://github.com/termux/termux-app/blob/master/README.md):

> NOTICE: Termux is broken on Android 12. Android OS will kill any (phantom) processes greater than 32 (limit is for all apps combined) and also kill any processes using excessive CPU. You may get [Process completed (signal 9) - press Enter] message in the terminal without actually exiting the shell process yourself. Check the related issue https://github.com/termux/termux-app/issues/2366, [issue tracker](https://issuetracker.google.com/u/1/issues/205156966), [gist with details](https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8) and https://github.com/termux/termux-app/issues/2366#issuecomment-1009269410 on how to disable trimming of phantom processes. A proper docs page will be added later. An option to disable the killing should be available in Android 12L or 13, so upgrade at your own risk if you are on Android 11, specially if you are not rooted.

**Comment by sajeeds4** [comment]
# For Android 12L & Android 13:

./adb shell "settings put global settings_enable_monitor_phantom_procs false"



# For Android 12：

./adb shell "/system/bin/device_config set_sync_disabled_for_tests persistent; /system/bin/device_config put activity_manager max_phantom_processes 2147483647"
