### ISSUE TITLE
[Package]: Bun

### ISSUE THREAD

**Issue by SunPodder** [termux/termux-packages#11801]
### Why do you want to add this package to Termux?

Bun is a Javascript runtime which embeds JavaScriptCore. It is faster!

### Source code URL

https://github.com/oven-sh/bun

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by sylirre** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/11188
