### ISSUE TITLE
mosh broken

### ISSUE THREAD

**Issue by 143981** [termux/termux-packages#11813]
CANNOT LINK EXECUTABLE "mosh-client": cannot locate symbol "_ZN6google8protobuf8internal14ArenaStringPtr3SetENS2_12EmptyDefaultERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEPNS0_5ArenaE" referenced by "/data/data/com.termux/files/usr/bin/mosh-client"...

**Comment by 2096779623** [comment]
`termux-info` plz.

**Comment by licy183** [comment]
Please switch to the default mirror using `termux-change-repo` and run `pkg update` to update `mosh`.

**Comment by 143981** [comment]
> Please switch to the default mirror using `termux-change-repo` and run `pkg update` to update `mosh`. It should have been fixed by [ff784d7](https://github.com/termux/termux-packages/commit/ff784d7a9aa62176dee312bf1511524eb0779f94).

thank you
