### ISSUE TITLE
[Package]: Calibre

### ISSUE THREAD

**Issue by pk-628996** [termux/termux-packages#11829]
### Why do you want to add this package to Termux?

I cannot install calibre as i have arm cpu please fix it .

### Home page URL

https://calibre-ebook.com/

### Source code URL

git@github.com:kovidgoyal/calibre.git

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
Duplicate of #6583 .
