### ISSUE TITLE
Libevent tmux error compile cloud9

### ISSUE THREAD

**Issue by kucingpoi-id** [termux/termux-packages#11821]
I have problem build libevent-2.1.8-stable in cloud9 core

```
CCLD     libevent.la
  CCLD     libevent_core.la
  CCLD     libevent_extra.la
  CC       evthread_pthread.lo
  CCLD     libevent_pthreads.la
  CC       libevent_openssl_la-bufferevent_openssl.lo
  CCLD     libevent_openssl.la
  CC       sample/dns-example.o
sample/dns-example.c:169:41: warning: result of comparison of constant -1 with expression of type 'char' is always true [-Wtautological-constant-out-of-range-compare]
        while ((opt = getopt(c, v, "xvc:Ts:")) != -1) {
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~
1 warning generated.
  CCLD     sample/dns-example
  CC       sample/event-read-fifo.o
  CCLD     sample/event-read-fifo
ld.lld: error: undefined symbol: arc4random_addrandom
>>> referenced by evutil_rand.c:198
>>>               evutil_rand.o:(evutil_secure_rng_add_bytes) in archive ./.libs/libevent.a
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:1406: sample/event-read-fifo] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/.c9/libevent-2.1.8-stable'
make: *** [Makefile:1248: all] Error 2

real    5m1.388s
user    3m19.452s
sys     1m29.288s
~/c9sdk $
```

I not really know termux support cloud9 becouse less topik of cloud9 installing on termux.

But i look termux support libevent-2.1.12-stable on package dev.

My point about "unable initialize pty.js" problem. They are required installing tmux-2.2, libevent-2.1.8, and ncurses-6.0 compile prosedure.

How do fix this?

`
Linux localhost 4.4.22+ #4 SMP PREEMPT Fri Sep 4 01:06:44 CST 2020 aarch64 Android
Android OS: 7.1.1
Model: CPH1729
`

**Comment by Grimler91** [comment]
We have a bunch of patches in our repo that you need to apply for compilation to work when targeting termux/android: https://github.com/termux/termux-packages/tree/master/packages/libevent

Seems pretty unlikely that your endgoal package strictly requires libevent 2.1.8, probably it requires libevent >= 2.1.8, i.e. 2.1.12 probably works as well
