### ISSUE TITLE
Fish is broken when using UTF-8 characters

### ISSUE THREAD

**Issue by christianrondeau** [termux/termux-packages#1183]
Please find https://github.com/fish-shell/fish-shell/issues/4269 for more details.

* fish 2.6.0
* os termux `Linux localhost 3.18.14-11422779 #1 SMP PREEMPT Thu Jun 1 19:35:14 KST 2017 aarch64 Android` with `TERM=xterm-256color`

Going back into the history using the up key sometimes jumbled my lines (one character is repeated at the beginning of the command, and modifications are then offset by one). 

I tried to simplify my problem, and I realized the issue was my prompt using the lambda character. 

I tried to then just type `¥` in fish and I had this:

![fish utf-8 bug on Termux](https://i.imgur.com/fXGWJ1g.jpg) 

The first three commands used the up key. Note the missing prompt. Also note the missing space in the second command. In the third, I only typed ¥ once. In the fourth, I typed ¥, then backspace, then "oops". 

It feels like a character vs byte count issues. 

Here's what I have tested, on Termux (bash and fish), Linux Alpine (both directly on a VM and in a brand new Docker instance in fish), and Bash on Ubuntu on Windows (both bash and fish).

I copied the `α` character from here http://www.fileformat.info/info/unicode/char/3b1/index.htm, and ran:

    echo "α" > test

Then, on all installations:

    cat test | od -t x1 -t c
    0000000 ce b1 0a
            316 261  \n
    0000003

Indeed, `ceb1` matches the utf-8 code on fileformat.info. I also tried `isutf8` in `moreutils`, and `iconv -f UTF-8 test`, everything confirms it is indeed valid utf-8, and that the character is valid. The only place where it breaks is when using fish _on_ termux.

Any suggestion are welcome.

Side note: right now, just typing a unicode character, from SwiftKey or Hacker's keyboard, or pasting from a unicode reference website, breaks the terminal (characters are offset, so when I use backspace, it removes one but actually deletes another). Initially, everything seemed broken because I used the lambda (`λ`) character as my prompt, but the behavior is very similar whenever I type any utf-8 character. So, hopefully, these are actually the same issues!

**Comment by faho** [comment]
Related to 845a978a46710b19066f6393ec593e88706b1576?

Fish does `setlocale(LC_ALL, "")`, so it looks like that applies.

**Comment by fornwall** [comment]
Thanks! I've now rebuilt fish into version `2.6.0-2` to get the MB_CUR_MAX fix. Can you update to that version and see if the issue is fixed there?

**Comment by faho** [comment]
Yes, that works for me!

**Comment by christianrondeau** [comment]
It's working perfectly, both in readline and in the prompt! Hats off, that was impressive!
