### ISSUE TITLE
python 3.6.2 installation issue

### ISSUE THREAD

**Issue by themastersunil** [termux/termux-packages#1184]
![s70731-090104](https://user-images.githubusercontent.com/26903066/28761787-d47e01ba-75ce-11e7-9d62-d0de4cd46648.jpg)

Rom: flyme 6
Phone: Meizu M2
Issue is that I'm able to install python 3.6.2 after complete 96% process...
Please help me. 😥

**Comment by Grimler91** [comment]
Since this is a duplicate of #1166, you can close this issue in favor of that one.
