### ISSUE TITLE
[Package]: notcurses

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#11858]
### Why do you want to add this package to Termux?

Because its a library for building complex, vibrant textual user interfaces (TUIs) on modern terminal emulators.

### Home page URL

https://nick-black.com/dankwiki/index.php/Notcurses

### Source code URL

https://github.com/dankamongmen/notcurses

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by buribu** [comment]
#8860
