### ISSUE TITLE
[Package]: zellij

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#11857]
### Why do you want to add this package to Termux?

Better Alternative of tmux and it has image support

### Home page URL

https://zellij.dev

### Source code URL

https://github.com/zellij-org/zellij

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
https://github.com/zellij-org/zellij/issues/1021

**Comment by xJonathanLEI** [comment]
The original repo doesn't compile on Termux yet, but here's what you can do right now until the PRs merge:

https://github.com/zellij-org/zellij/issues/1021#issuecomment-1301587011

I will submit a Termux package PR (with patches if the upstream PRs won't be merged by then) after I daily drive with it on Android more.

**Comment by xJonathanLEI** [comment]
Hey it's me again. I've been working on pushing for Android support in Zellij. Zellij just [released](https://github.com/zellij-org/zellij/releases/tag/v0.33.0) a new version containing a few fixes for making it work on Android. The only thing really missing there is the `wamser` bump (https://github.com/zellij-org/zellij/pull/1833), which can be easily handled with just a 3-line patch.

I want to work on adding this package, but I noticed that the contribution guide mentions the `help-wanted` tag, which is not present in this issue. Is it the case that contribution is only accepted for tagged issues? Or can I still submit a PR for this? Thanks!

**Comment by Grimler91** [comment]
You are very welcome to submit a PR! 

(We tend to add the help-wanted tag to issues that we do not know how to solve, or issues that might require too much work for too little reward (in our opinion))
