### ISSUE TITLE
[Bug]: jupyter launch error

### ISSUE THREAD

**Issue by kawuwa** [termux/termux-packages#11867]
### Problem description

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/data/com.termux/files/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 51, in <module>
    from .ipkernel import IPythonKernel
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 17, in <module>
    from .comm import CommManager
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/ipykernel/comm/__init__.py", line 1, in <module>
    from .comm import *  # noqa
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/ipykernel/comm/comm.py", line 12, in <module>
    from ipykernel.kernelbase import Kernel
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 35, in <module>
    import psutil
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/__init__.py", line 102, in <module>
    from . import _pslinux as _psplatform
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: dlopen failed: cannot locate symbol "ethtool_cmd_speed" referenced by "/usr/lib/python3.10/site-packages/psutil/_psutil_linux.cpython-310.so"...

the kernel restart failed
😭

### What steps will reproduce the bug?

help

### System information

termux-info:

```

```
newest

**Comment by 2096779623** [comment]
https://www.sqlsec.com/2018/05/termux.html#Jupyter-Notebook

**Comment by kawuwa** [comment]
> https://www.sqlsec.com/2018/05/termux.html#Jupyter-Notebook

python-dev无法下载😭

**Comment by 2096779623** [comment]
Dont't use chinese here :p .
`pkg i python pkg-config git clang libzmq ipython -y`
`pip3 install jupyter`

**Comment by kawuwa** [comment]
> Dont't use chinese here :p . `pkg i python pkg-config git clang libzmq ipython -y` `pip3 install jupyter`

Thank you very much !
But I cant download ipython though I try to use the chinese source

**Comment by 2096779623** [comment]
> Thank you very much ! But I cant download ipython though I try to use the chinese source

`pip3 install iython`

**Comment by kawuwa** [comment]
> > Thank you very much ! But I cant download ipython though I try to use the chinese source
> 
> `pip3 install iython`

I download them ,but not solve the problem 😭,thank you all the same🙏

**Comment by kawuwa** [comment]
> > Thank you very much ! But I cant download ipython though I try to use the chinese source
> 
> `pip3 install iython`

I download them ,but not solve the problem 😭,thank you all the same🙏

**Comment by tomty89** [comment]
I don't think (python-)psutil supports Android. I got through the `ethtool_cmd_speed` problem by patching `linux/ethtool.h`:

```
$ git diff $PREFIX/include/linux/ethtool.h{~,}
diff --git a/data/data/com.termux/files/usr/include/linux/ethtool.h~ b/data/data/com.termux/files/usr/include/linux/ethtool.h
index 741ea2a..d0f2eaa 100644
--- a/data/data/com.termux/files/usr/include/linux/ethtool.h~
+++ b/data/data/com.termux/files/usr/include/linux/ethtool.h
@@ -905,3 +905,7 @@ struct ethtool_link_settings {
   __u32 link_mode_masks[0];
 };
 #endif
+static __inline__ __u32 ethtool_cmd_speed(const struct ethtool_cmd *ep)
+{
+        return (ep->speed_hi << 16) | ep->speed;
+}
$
```

But then after recompiling/reinstalling:
```
>>> import psutil
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/meh/lib/python3.10/site-packages/psutil/_common.py", line 398, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/meh/lib/python3.10/site-packages/psutil/_pslinux.py", line 285, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/home/meh/lib/python3.10/site-packages/psutil/_common.py", line 400, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/home/meh/lib/python3.10/site-packages/psutil/_pslinux.py", line 268, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/home/meh/lib/python3.10/site-packages/psutil/_common.py", line 727, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
PermissionError: [Errno 13] Permission denied: '/proc/stat'
>>>
```

**Comment by kawuwa** [comment]
> I don't think (python-)psutil supports Android. I got through the `ethtool_cmd_speed` problem by patching `linux/ethtool.h`:
> 
> ```
> $ git diff $PREFIX/include/linux/ethtool.h{~,}
> diff --git a/data/data/com.termux/files/usr/include/linux/ethtool.h~ b/data/data/com.termux/files/usr/include/linux/ethtool.h
> index 741ea2a..d0f2eaa 100644
> --- a/data/data/com.termux/files/usr/include/linux/ethtool.h~
> +++ b/data/data/com.termux/files/usr/include/linux/ethtool.h
> @@ -905,3 +905,7 @@ struct ethtool_link_settings {
>    __u32 link_mode_masks[0];
>  };
>  #endif
> +static __inline__ __u32 ethtool_cmd_speed(const struct ethtool_cmd *ep)
> +{
> +        return (ep->speed_hi << 16) | ep->speed;
> +}
> $
> ```
> 
> But then after recompiling/reinstalling:
> 
> ```
> >>> import psutil
> Traceback (most recent call last):
>   File "/data/data/com.termux/files/home/meh/lib/python3.10/site-packages/psutil/_common.py", line 398, in wrapper
>     return cache[key]
> KeyError: (('/proc',), frozenset())
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/data/data/com.termux/files/home/meh/lib/python3.10/site-packages/psutil/_pslinux.py", line 285, in <module>
>     set_scputimes_ntuple("/proc")
>   File "/data/data/com.termux/files/home/meh/lib/python3.10/site-packages/psutil/_common.py", line 400, in wrapper
>     ret = cache[key] = fun(*args, **kwargs)
>   File "/data/data/com.termux/files/home/meh/lib/python3.10/site-packages/psutil/_pslinux.py", line 268, in set_scputimes_ntuple
>     with open_binary('%s/stat' % procfs_path) as f:
>   File "/data/data/com.termux/files/home/meh/lib/python3.10/site-packages/psutil/_common.py", line 727, in open_binary
>     return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
> PermissionError: [Errno 13] Permission denied: '/proc/stat'
> >>>
> ```
> 
> (I'm on Android 10 though. On some older version the problem might not exist.)

Thank you very much! Inspired by you, I downloaded the lower version of psutil and solved the problem successfully!

**Comment by kundor** [comment]
> Thank you very much! Inspired by you, I downloaded the lower version of psutil and solved the problem successfully!

What lower version? I have tried psutil versions back to 5.3.1 (down from the current 5.9.2) and still get the same error.

**Comment by kawuwa** [comment]
Maybe you can try 5.9.0 or 5.8.9 ...🤔



---Original---
From: "Nicholas ***@***.***&gt;
Date: Wed, Oct 12, 2022 00:27 AM
To: ***@***.***&gt;;
Cc: "Wukang ***@***.******@***.***&gt;;
Subject: Re: [termux/termux-packages] [Bug]: jupyter launch error (Issue#11867)




  
Thank you very much! Inspired by you, I downloaded the lower version of psutil and solved the problem successfully!
  
What lower version? I have tried psutil versions back to 5.3.1 (down from the current 5.9.2) and still get the same error.

**Comment by kawuwa** [comment]
> > Thank you very much! Inspired by you, I downloaded the lower version of psutil and solved the problem successfully!
> 
> What lower version? I have tried psutil versions back to 5.3.1 (down from the current 5.9.2) and still get the same error.

Maybe you can try 5.9.0 or 5.8.9 ...🤔

**Comment by kundor** [comment]
There is no version 5.8.9 (https://pypi.org/project/psutil/#history). I tried 5.8.0 and 5.9.0 and still got `PermissionError: [Errno 13] Permission denied: '/proc/stat'`. :(
