### ISSUE TITLE
[Package]: rirc

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#11876]
### Why do you want to add this package to Termux?

A terminal irc client in C

### Home page URL

https://rcr.io/rirc/

### Source code URL

https://github.com/rcr/rirc

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
"A terminal irc client in C" doesn't answer the question "Why do you want to add this package to Termux?", please elaborate.

I guess this is your seventh irc client request. You still haven't answered [my question from April](https://github.com/termux/termux-packages/issues/9876#issuecomment-1087695480) about why you need so many different irc clients

**Comment by aicynide** [comment]
@Grimler91 Because It works™, since 1988. IM networks come and go, I lost count on them, IRC stays.
I also want to ask you when download is possible using curl then why wget , axel, curl, aria2c, nzbget, apkeep, googledrive-downloader, rtorrent, transmission, croc exist in termux repo? When everything possible using nano then why emacs, vi, vim, pico , micro, neovim, zile, tilde , sed, kivi, leafpad,  featherpad, gedit etc. Exist in termux repo?
Let me answer because developer aren't stupid that yhey  would make clone of other app, they have different use, and unique features.
I know irc isn't preferred by modern people but it still works.
All irc clients aren't same. I guess I had explained you earlier why I had requested gclone, fclone, lclone etc. Read that again please.
Similary, irc is just a protcol. If you hate irc apps then don't use them , just fire up telnet and explore the protocol at its most basic (and least user friendly).I think then all irc clients should be removed termux repo and suggest user to use it using telnet. oof
let's take an example of popular irc client - irssi. Its very powerful and configurable yet people prefer weechat, the reason is irssi development has become slow and irssi doesn't have gui frontend. There is web, android, ios and desktop gui client for weechat but irssi doesn't, so most people use weechat but since irssi is lightweight its still preferred by many people. Now let's compare srain, dxirc, Konversation, kvirc and hexchat. srain UI is nice and different from regular irc client but its little buggy in Windows, on other hand dxirc has 2 frontend- qt & fox.  Hexchat has largest userbase since it supports xdcc best. Some people may choose Konversation because of its clean UI. kvirc is feature-rich but bloated. These apps wouldn't be liked by users who already use quassel or smuxi because unlike the above mentioned clients, quassel and smuxi lets you connect to irc 24/7. Quassel and smuxi aren't ircd like znc and has its own protocol to connect to quassel-core or smuxi-server. 
See people may want to use smuxi because besides irc it supports xmpp-, google chat,twitter and campfire. Although its similar to quassel but quassel doesn't support other apps like xmpp/twitter. Although smuxi is better than quassel, smuxi doesn't have web/ios/android app like quassel. Do you want people to stick to 1 app? Other Apps made by the devs are garbage? 
You may say now Thunderbird, pidgin, weechat, irssi also support multiple IM apps but smuxi wins here because you can host smuxi server in vps and never miss any message.
gamja, kiwiirc, thelounge, convos are web client then why need all apps? Just use 1 app. NO. 
because gamja and kiwiirc are like regular irc client and doesn't store messages like thelounge or convos. So in this battle only thelounge and convos survived.
Besides the difference in their UI, convos support random profile picture and link preview and pastebin viewer in chat. Both thelounge and convos has different use case.


Now coming to rirc. rirc isn't bloated like weechat or irssi. It doesn't have script support or perl dependency.
It is lightweight and tiny irc client.
So please add rirc for the users to just a app for using irc, that's it. It should 1 thing correctly i.e. handle irc properly and rirc does that 

Thank You
I hope you understand

**Comment by Grimler91** [comment]
> rirc isn't bloated like weechat or irssi. It doesn't have script support or perl dependency.
It is lightweight and tiny irc client.

Great, that answers the question for rirc, thanks.

The point of the package request template and the packaging guidelines is to make it possible for maintainers and package porters to see what packages that are useful/cool/popular. Porters need to determine which packages are worth spending time and energy on, and disk space on host. To allow that this type of information should be filled in in the package request.

**Comment by aicynide** [comment]
I am aware about vps storage limitations. Quite surprised android being a popular os, donation of termux is low or no non-profit organisation helping our community. 
Seeing less developers in termux team, sometime I fear it might die. Like fornwall, xeffyr left...
I'm a student. I never personally bought server myself. If server was access was sold in shop or can be bought offline like movie ticket, it was easy to buy server by making excuses to parent.

**Comment by T-Dynamos** [comment]
> Seeing less developers in termux team, sometime I fear it might die. Like fornwall, xeffyr left...

Xeffyr was back as @sylirre

**Comment by aicynide** [comment]
> Xeffyr was back as @sylirre

Any news about @xtkoba ?

**Comment by Grimler91** [comment]
They are both well as far as we know. Everyone are free to work as much or as little as they want to on termux-related things

**Comment by T-Dynamos** [comment]
> > Xeffyr was back as @sylirre
> 
> Any news about @xtkoba ?

He got back with your comment.blush #11907

**Comment by 2096779623** [comment]
> They have no obligation to work on any of those requests and are free to contribute whenever they want. If you want faster resolution of requests, either send a pull request yourself or offer a bounty.

**Comment by rihaq** [comment]
> > Any news about @xtkoba ?
> 
> He is back with your comment 😱 #11907

😎
