### ISSUE TITLE
Add Termux bootstrap sha256sum to bootstrap releases

### ISSUE THREAD

**Issue by babaric-dev** [termux/termux-packages#11874]
It will make checking sha256sum easier

**Comment by babaric-dev** [comment]
Just add a .sha256sum file to every architecture of the bootstrap in future releases.
Should be easy enough :)

**Comment by 2096779623** [comment]
> Should be easy enough :)

You can PR :) .

**Comment by babaric-dev** [comment]
I'd like to, but idk which file generates the release

**Comment by babaric-dev** [comment]
I'd like to, but idk which file generates the release

**Comment by 2096779623** [comment]
> I'd like to, but idk which file generates the release

https://github.com/termux/termux-packages/blob/52e7728ba3acf1f7975e8247899fbaf791439540/.github/workflows/bootstrap_archives.yml#L51

**Comment by babaric-dev** [comment]
After a nights sleep, I finally got some idea and made a PR #11916

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/commit/4af58fc0163ff3d12de75166d8677d99dbb65c8f
