### ISSUE TITLE
[Package]: bcrypt-cli

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#11875]
### Why do you want to add this package to Termux?

Its a cli tools for hashing password with bcrypt

### Home page URL

https://github.com/ryicoh/bcrypt-cli

### Source code URL

https://github.com/ryicoh/bcrypt-cli

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
This package does not declare a license.
