### ISSUE TITLE
[Package]: esbuild

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#11873]
### Why do you want to add this package to Termux?

An extremely fast JavaScript and CSS bundler and minifier

### Home page URL

https://esbuild.github.io

### Source code URL

https://github.com/evanw/esbuild

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Package is written in Go and compiles without any issues on Termux.

**Comment by 2096779623** [comment]
https://github.com/evanw/esbuild/blob/master/scripts/browser/package.json#L3

https://github.com/rishabhrpg/puppeteer-on-termux

**Comment by ravener** [comment]
@2096779623 no it does not require electron, ignore those package.json stuff, focus on the golang code only, that's all we need for the cli tool.

**Comment by 2096779623** [comment]
> @2096779623 no it does not require electron, ignore those package.json stuff, focus on the golang code only, that's all we need for the cli tool.

But its use on nodejs is temporarily impossible :p .
Let's try to build it with golang.

**Comment by ravener** [comment]
> > @2096779623 no it does not require electron, ignore those package.json stuff, focus on the golang code only, that's all we need for the cli tool.
> 
> But its use on nodejs is temporarily impossible :p .
> Let's try to build it with golang.

Yeah we can't do anything about nodejs usage since npm needs to manage that when you use it in your app, hence its up to the main package author to do that. They already support arm64 npm binaries but said he won't add arm.

Outside of node, the cli tool alone is more than enough, can be used independently from nodejs, to bundle/minify css/js and such.
