### ISSUE TITLE
[Package]: termbot

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#11883]
### Why do you want to add this package to Termux?

Full-fledged terminal emulator in discord

### Home page URL

https://github.com/polyzium/termbot

### Source code URL

https://github.com/polyzium/termbot

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
https://github.com/termux-user-repository/tur/commit/c87106302564411f0eaee1711606eb2eb619199f

Added in tur.
