### ISSUE TITLE
[Package]: tb

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#11882]
### Why do you want to add this package to Termux?

termbin client which uses either nc or ncat

### Home page URL

https://git.kyoko-project.wer.ee/akoizumi/posix-sh-tools

### Source code URL

https://git.kyoko-project.wer.ee/akoizumi/posix-sh-tools/src/main/bin/tb

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by pvonmoradi** [comment]
Both links are `404`ing

**Comment by aicynide** [comment]
> Both links are `404`ing

It would be fixed soon

**Comment by rallg** [comment]
Why would this be of interest to most Termux users? Have you tried to build it?
