### ISSUE TITLE
[Package]: gocryptfs

### ISSUE THREAD

**Issue by CodeCubeNeo** [termux/termux-packages#11891]
### Why do you want to add this package to Termux?

It is a basic crypto filesystem tool like encfs. It would be really awesome for termux to support it.

### Home page URL

https://nuetzlich.net/gocryptfs/

### Source code URL

https://github.com/rfjakob/gocryptfs

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by rihaq** [comment]
Not possible in non-root phone since there's libfuse dependency

**Comment by CodeCubeNeo** [comment]
Droidfs can handle it. How do they achieve that?

**Comment by rallg** [comment]
From its guthub project page, I see that the application also can do things such as play media files. But Termux has issues with that, for other reasons. In short, it looks like you would be better off using the F-Droid app, rather than asking for it to sit within Termux. As far as I can tell from reviewing the features, placing it within Termux would add nothing that the F-Droid app does not already have.

**Comment by railgauge** [comment]
I am able to create the static binary of gocryptfs, initialize a folder and mount it, and write/read files. Tested on Android 9 and 12. 

This would be a very useful and practical package to add to Termux. You can mount to the root namespace in a subdirectory of /sdcard and then any standard app will transparently use encryption for your photos/music/documents. 

How to:
```
apt install golang
git clone https://github.com/rfjakob/gocryptfs.git
cd gocryptfs
./build-without-openssl.bash

mkdir ~/plain ~/cipher
sudo ~/gocryptfs/gocryptfs -init ~/cipher
sudo ~/gocryptfs/gocryptfs -allow_other -nosyslog ~/cipher ~/plain
echo "test write" > ~/plain/testfile1.txt
ls -lah ~/plain ~/cipher
sudo umount ~/plain
```

NOTE: Use -nosyslog else you will get an error "Transport endpoint is not connected" when trying to write files. 

I am getting one issue still, that being that after entering your password the mount is successful but the terminal is locked up and will not respond to further inputs including CTRL+C, CTRL+Z, CTRL+D. Thus after mounted you must open a new terminal to access the files. 

Here is a more verbose output for those who know more than me. Probably something to do with "Unknown opcode 2016".

```
sudo ~/gocryptfs/gocryptfs -allow_other -nosyslog -fusedebug ~/cipher ~/plain
Password:
Decrypting master key
The option "-allow_other" is set. Make sure the file permissions protect your data from unwanted access.
00:52:06.596555 callFusermount: executing ["/data/data/com.termux/files/usr/bin/fusermount3" "/data/data/com.termux/files/home/plain" "-o" "max_read=131072,default_permissions,fsname=/data/data/com.termux/files/home/cipher,allow_other,subtype=gocryptfs"]
00:52:06.658413 rx 1: INIT n0 {7.23 Ra 0x80000 NO_OPEN_SUPPORT,FLOCK_LOCKS,AUTO_INVAL_DATA,POSIX_LOCKS,EXPORT_SUPPORT,BIG_WRITES,SPLICE_WRITE,READDIRPLUS_AUTO,ASYNC_READ,ATOMIC_O_TRUNC,DONT_MASK,SPLICE_MOVE,IOCTL_DIR,SPLICE_READ,READDIRPLUS,ASYNC_DIO,WRITEBACK_CACHE}
00:52:06.658599 tx 1:     OK, {7.23 Ra 0x80000 ASYNC_READ,READDIRPLUS,NO_OPEN_SUPPORT,BIG_WRITES,AUTO_INVAL_DATA 0/0 Wr 0x20000 Tg 0x0}
00:52:06.659049 rx 2: GETATTR n1 {Fh 0}
00:52:06.659377 tx 2:     OK, {tA=1s {M040700 SZ=4096 L=2 10012:10012 B8*4096 i0:0 A 1668209159.945633 M 1668214246.748443 C 1668214246.748443}}
00:52:06.659584 rx 3: LOOKUP n1 [".go-fuse-epoll-hack"] 20b
00:52:06.659662 tx 3:     OK, {n18446744073709551615 g0 tE=0s tA=0s {M0100644 SZ=0 L=1 0:0 B0*0 i0:18446744073709551615 A 0.000000 M 0.000000 C 0.000000}}
00:52:06.659787 rx 4: GETATTR n18446744073709551615 {Fh 0}
00:52:06.660137 tx 4:     OK, {tA=0s {M0100644 SZ=0 L=1 0:0 B0*0 i0:18446744073709551615 A 0.000000 M 0.000000 C 0.000000}}
00:52:06.660423 rx 5: OPEN n18446744073709551615 {O_RDONLY,0x20000}
00:52:06.660473 tx 5:     OK, {Fh 18446744073709551615 }
00:52:06.661006 Unknown opcode 2016
00:52:06.661144 tx 6:     34=numerical result out of range
00:52:06.661388 rx 7: POLL n18446744073709551615
00:52:06.661469 tx 7:     38=function not implemented
00:52:06.661710 rx 8: FLUSH n18446744073709551615 {Fh 18446744073709551615}
00:52:06.661777 tx 8:     OK
Filesystem mounted and ready.
00:52:06.662360 rx 9: RELEASE n18446744073709551615 {Fh 18446744073709551615 0x20000  L0}
00:52:06.662396 tx 9:     OK
```

**Comment by CodeCubeNeo** [comment]
Thank you for actually testing the thing. Really awesome.
