### ISSUE TITLE
.gitignore missing

### ISSUE THREAD

**Issue by mklein994** [termux/termux-packages#119]
There needs to be a .gitignore file at the root of the repository to prevent generated files or backup files from being tracked. See https://github.com/github/gitignore for good examples. You can even include some for your own global .gitignore (see https://help.github.com/articles/ignoring-files/#create-a-global-gitignore for details). Sorry if you already knew this, I'm just mentioning this in light of commit 77a8de7, where a .swp file was committed.

**Comment by fornwall** [comment]
Thanks!
