### ISSUE TITLE
[Bug]: Tectonic package crashes on startup due to Rust/JNI issue

### ISSUE THREAD

**Issue by pkgw** [termux/termux-packages#11900]
### Problem description

The Termux package of Tectonic crashes on startup.

There is some investigation of the issue in https://github.com/tectonic-typesetting/tectonic/issues/926. The crash stems from the `app_dirs2` Rust crate, which attempts to use a JNI context pointer that is uninitialized in the Termux environment. My understanding is that Termux provides a somewhat unusual environment for Android software, so some local patching might be the most appropriate solution. See also https://github.com/rust-windowing/android-ndk-rs/issues/126 .

Also, the package is a little out of date.

### What steps will reproduce the bug?

1. Install `tectonic`
2. Run `tectonic` on the command line

### What is the expected behavior?

It runs.

Actual behavior:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/ndk-glue-0.3.0/src/lib.rs:54:39
```

### System information

(I don't have this information since I'm filing the bug on behalf of Tectonic users.)

**Comment by Grimler91** [comment]
Sounds like same issue we had with tealdeer: https://github.com/termux/termux-packages/commit/ff9aaad94b27feafc5d0639c78bec3103d7a5850 / https://github.com/termux/termux-packages/pull/9072, so we should be able to apply the same hack for tectonic

(issue was that https://github.com/rust-windowing/android-ndk-rs/ only supports java apps on android, and not environments like termux)

**Comment by pkgw** [comment]
Thanks for the prompt follow-up! As discussed in the linked issues we're hoping to fix up our use of `app_dirs2` to avoid the issue, but from what I understand (which is not much — I don't know anything about Android dev) a local patch seems like a potentially reasonable short-term plan.

**Comment by MarijnS95** [comment]
That seems like a terrible workaround, IMO; you won't get any fixes from the newer `app_dirs2`.

In my eyes this is something that should be coordinated on a higher level; i.e. Rust apps shouldn't _assume_ to be running in an Android _app environment_ whenever the target triple happens to include `target_os = "android"`.

**Comment by Grimler91** [comment]
> That seems like a terrible workaround, IMO; you won't get any fixes from the newer `app_dirs2`.

I agree, I probably should have filed an issue in android-ndk-rs to discuss it last time we looked at it.

> In my eyes this is something that should be coordinated on a higher level; i.e. Rust apps shouldn't _assume_ to be running in an Android _app environment_ whenever the target triple happens to include `target_os = "android"`.

Sounds very helpful for termux and forks. Rust is not my strong suite, so I'm glad it has been brought to your attention

**Comment by MarijnS95** [comment]
For now it seems like we're patching this up in `app_dirs2` as that's - as far as I'm aware - pretty much the only non-UI app that should sensibly function in and "outside" of Android apps while providing different behaviour for each. Let me know if this issue pops up again so that we can think up a more widespread solution (which we haven't really found thus far).

**Comment by Grimler91** [comment]
I upgrade to 0.9.0 and implemented the hack in https://github.com/termux/termux-packages/commit/b5f249310a3721d95f06fb69dd1335740d2c944e and https://github.com/termux/termux-packages/commit/dbb30152285c22f260a6588387a13fded80a8493. 

I'll keep an eye out for that `app_dirs2`, me or someone else from here can probably help with testing if testers are needed
