### ISSUE TITLE
[Package]: ttyc

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#11915]
### Why do you want to add this package to Termux?

Its a ttyd client. ttyd doesn't work properly in mobile browser. Ctrl key, alt key etc. and copying doesn't work in browser android. So need a cli client to use remote ttyd

### Home page URL

https://github.com/Depau/ttyc

### Source code URL

https://github.com/Depau/ttyc

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Although a pre-built binary for android is provided, a https://github.com/termux/termux-packages/pull/9721 treatment is required to fix /etc/resolv.conf nameserver bug to make it working

**Comment by aicynide** [comment]
@T-Dynamos Although a pre-built binary for android is provided, a https://github.com/termux/termux-packages/pull/9721 treatment is required to fix /etc/resolv.conf nameserver bug to make it working

**Comment by T-Dynamos** [comment]
Do you tested the artifacts?
