### ISSUE TITLE
NPM INSTALL <module> | Cannot Find Module

### ISSUE THREAD

**Issue by ItsPedruu** [termux/termux-packages#1191]
Hi,
I've been installing the module "eris" in everywhere, I installed in `/` `/storage/sdcard0` `/data/data/com.termux/files/home/` and with the "--save" or "-g"
And, when i run the main.js that returns "Cannot find Module "eris" 
I've been trying install this for at least 1 hour!

**Comment by ItsPedruu** [comment]
I solved it, basically i moved my project to the original node folder. And who is the genious? Isn't me! 😢

**Comment by priest2** [comment]
I don't know how to intall module on termux
