### ISSUE TITLE
[Bug]: ttyc: /data/data/com.termux/files/usr/bin/ttyc: 2: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#11927]
### Problem description

Getting this error when running ttyc 
`/data/data/com.termux/files/usr/bin/ttyc: 2: Syntax error: newline unexpected`

### What steps will reproduce the bug?

Install ttyc: `pkg ins ttyc`
Run `ttyc`

### System information

termux-info:

```

```

**Comment by T-Dynamos** [comment]
Seems buggy binary
![Screenshot_2022-09-15-09-41-47-233_com termux](https://user-images.githubusercontent.com/68729523/190312559-700de995-9bb7-4692-9979-c96dc7a43147.jpg)
