### ISSUE TITLE
[Package]: cloneit

### ISSUE THREAD

**Issue by rihaq** [termux/termux-packages#11923]
### Why do you want to add this package to Termux?

Its a very useful tool to download specific github folder or file

### Home page URL

https://github.com/alok8bb/cloneit

### Source code URL

https://github.com/alok8bb/cloneit

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
This package does not declare a license.

**Comment by rallg** [comment]
Also, beside not declaring a license, it is not clear why the package is necessary. Why not other git meithods?

**Comment by rihaq** [comment]
@2096779623 added license
