### ISSUE TITLE
Auto update failing for ledger

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#11930]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the ledger package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating ledger [Current version: 3.2.1]
ERROR: No 'latest-release-tag' found (https://api.github.com/repos/ledger/ledger/releases/latest).
Try using 'newest-tag'.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2022-09-15 00:35:58 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/3056947034">3056947034</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by truboxl** [comment]
Might be a fluke. Closing...
