### ISSUE TITLE
[Package]: eww

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#11940]
### Why do you want to add this package to Termux?

I want this for this rice https://github.com/gh0stzk/dotfiles

### Home page URL

https://github.com/elkowar/eww

### Source code URL

https://github.com/elkowar/eww/archive/refs/tags/v0.4.0.tar.gz

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Just too lazy to build it

**Comment by rallg** [comment]
It is not obvious whether 9or not that would be generally useful. Have you tried to build it?

**Comment by T-Dynamos** [comment]
> It is not obvious whether or not that would be generally useful. Have you tried to build it?

> Just too lazy to build it
