### ISSUE TITLE
Package concerns regards to discord-related packages

### ISSUE THREAD

**Issue by wmc3000** [termux/termux-packages#11948]
I've seen some modified discord clients present in Termux packages such as [`discordo`](https://github.com/termux/termux-packages/tree/master/packages/discordo)

The use of modified or custom clients would have the risks of Account Termination and discord terms of service mentions about unofficial/3rd party clients

[Someone banned from using discord due to the violation of Terms of Service by using this custom client](https://github.com/Bios-Marcel/cordless#i-am-closing-down-the-cordless-project)

it's a bad idea to keep or maintain these packages under the main repository that involves no official way of allowing 3rd party clients as per Terms of Service and not available to install on-demand in major distributions. I think complying with service's Terms of Service regards to third party (proprietary) clients should be required before adding these kinds of packages to reduce risks of account termination.

**Comment by xtkoba** [comment]
As the initial packager of <a href="https://github.com/mk-fg/reliable-discord-client-irc-daemon">`rdircd`</a>, I'm already aware of this issue.

As per packaging policy with respect to <a href="https://wiki.termux.com/wiki/Hacking">hacking tools</a>, I will remove a package if it makes script kiddies possible to spam through the Discord service with the slightest knowledge of programming. I doubt if that is the case though.

**Comment by T-Dynamos** [comment]
Also then #11938

**Comment by wmc3000** [comment]
While custom clients can be a good frosting over plain clients. it wouldn't be appropriate to package in the main repository, custom clients would have extra capabilities exposed to end-users that discord wouldn't normally do. which was good for selfbots which could violate the Terms of Service.

If keeping package to exist rather than asking user to compile something from scratch, a user/3rd party repository for these kinds of packages would be a good idea, [In Arch, 3rd party clients are in AUR while official ones are in the main repo](https://wiki.archlinux.org/title/Discord#Third-party_clients). If discord might officially release a CLI version of the client then I guess it's appropriate to package it here? aligning the package standards from other distros would be a good consistency.

Although the ToS is unclear about legislating these modded clients, the obvious from what you're doing is enough to terminate your account. likely this issue could subject to change but for my opinions, I don't encourage users risking their account being terminated using these utilities unless smart enough to prevent it.

**Comment by wmc3000** [comment]
I guess this can be closed if this is objectionable. as technically the main repository do not have official clients yet.

**Comment by OrdinaryEnder** [comment]
> I guess this can be closed if this is objectionable. as technically the main repository do not have official clients yet.

Seem impossible since it closed source, maybe ur can ask to discord support for source and build up for termux

**Comment by wmc3000** [comment]
doesn't matter? why would discord prioritize Termux platform if proper clients already existed. anyway pretty much nothing I can do on my side
