### ISSUE TITLE
operation not permitted:'lib'

### ISSUE THREAD

**Issue by wkddnjset** [termux/termux-packages#1197]
Hello!!!
when I create virtualenv directory an error occurs
`$ pwd                                                                                                                                             /storage/3265-3432/Android/data/com.termux/files/python/django                                                                                    $ python -m venv vr_python                                                                                                                        Error: [Errno 1] Operation not permitted: 'lib' -> '/storage/3265-3432/Android/data/com.termux/files/python/django/vr_python/lib64'`

I also tried
`$ virtualenv vr_python
`

but it has same error
`......'[Errno 1] Operation not permitted'), ('/data/data/com.termux/files/usr/lib/python3.6/config-3.6m', '/storage/3265-3432/Android/data/com.termux/files/python/django/vr_python/lib/python3.6/config-3.6m', '[Errno 1] Operation not permitted'`

please help...ㅠㅠ

**Comment by xeffyr** [comment]
You are trying to create virtualenv on external SD card, so virtualenv cannot create symlinks and/or set executable permissions. Try to do this in your $HOME directory.
