### ISSUE TITLE
Hello packaging policy. How is it going?

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#11974]
![It's now broken. What to do now?](https://user-images.githubusercontent.com/63401712/190884700-0f1b16a8-7773-4443-ae9d-4bf2dd555f7d.png)

> - Packages must be active, well-known projects
> Software available in major Linux distributions has more chances to be included into Termux repositories. We will not accept outdated, dead projects as well as projects which do not have active community.

My question is why almost nobody notice this? Lot of packages that i see here is mostly a package that unavailable in Majot Linux Distributions, Like, 3rd party discord client? Is it available on Debian apt repository anyway?

> - Not installable through cpan, gem, npm, or pip
> These packages should be installable through cpan, gem, npm, pip and so on.
> 
> Packaging modules for Perl, Ruby, Node.js, Python is problematic, especially when it comes to cross-compiling native extensions.

I still see several packages that installable through cpan, gem, npm, or pip.

> - Not serving duplicated functionality
> Please avoid submitting packages which duplicate functionality of already present ones.
> 
> The more useless packages in repositories, the less overall packaging and service quality - remembering that our resources are limited?

Also this?

Feel free to share your thoughts here.

**Comment by xtkoba** [comment]
I suppose these parts are not for developers but for requesters. A package request should satisfy these criteria and should contain a description such that these are actually satisfied. On the other hand, developers should be free to write a new package not necessarily conforming to these rules, unless it damages the project seriously (like a hacking tool or a too-large package).

**Comment by Yonle** [comment]
> I suppose these parts are not for developers but for requesters.

Yep, These parts are for requesters. Majority of requester only check the "I've read the packaging policy" and then just request anyways.

**Comment by xtkoba** [comment]
IMHO, a package request should be downvoted (:-1:) by contributors if it breaks these rules. I have hardly ever seen such a situation though.

**Comment by Yonle** [comment]
> IMHO, a package request should be downvoted (:-1:) by contributors if it breaks these rules. I have hardly ever seen such a situation though.

I think this should be fine.

**Comment by rallg** [comment]
I am not a developer (or even a programmer), but I have noticed the large number of relatively obscure new package requests, particularly with no attempt at bulding, or even looking for dependencies. If I can try to build something (working or not) before requesting it, surely more knowledgeable users can also do that.

Also, I wonder how many of those requests are not useful except for root users, or for those with relatively powerful machines? The requests rarely have tags, and we cannot expect the Termux developers to examine every situation.

**Comment by xtkoba** [comment]
Apparently no one is actually willing to improve the policy. Closing.

**Comment by twaik** [comment]
Issue template was updated (923a2d2af13938b35d222f4373cd624accb7509e) so now users should specify how exactly project not comply to our packaging policy.
