### ISSUE TITLE
[Bug]:  binutils vs. binutils-is-llvm, programs ldd and ar.

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#11993]
### Problem description

Sometimes, when I try to build source code from elsewhere (non-rooted, 32-bit ARM), the compiler fails when it cannot find program `ldd` or `ar`. Possibly others. I see that `binutils-is-llvm` does not provide either `ldd` or `ar`, although `binjutils` does provide them.

Possibly add those programs to `binutils-is-llvm` ? Otherwise, I must switch back and forth between the incompatible "binutils-is-llvm` and `binutils` depending on what I am trying to build.

I am not a programmer, so I do not know how to edit source code so that `ldd` and `ar` are eliminated.

### What steps will reproduce the bug?

Build source code. Makes a difference whether using termux-build system (requires `binutils-is-llvm`) or not (may requite `binutils` instead, due to `ldd` or `ar`). This has been the case ever since `binutils-is-llvm` was introduced.

### What is the expected behavior?

Should be able to use one package, probably `binutils-is-llvm`, always.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://plug-mirror.rcac.purdue.edu/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.29.2
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22626479 #1 SMP PREEMPT Fri Jul 22 16:53:55 +07 2022 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T510
```

**Comment by xtkoba** [comment]
`binutils-is-llvm` does contain `ar` as a symlink to `llvm-ar`. What is the error when calling `ar` command?

Note that `ldd` is not a part of GNU Binutils in the first place. It is contained in our `binutils` package just for convenience.

**Comment by rallg** [comment]
That is helpful. The problem with `ar` appears to be source code that is somehow not accepting the symlink. I cannot recall which code produces the problem. If I encounter it again, I can manually edit the source code so that will accept `llvm-ar` instead.

I only encountered `ldd` once. If I encounter it again, I will simply extract `ldd` from `binutils` and try it. Note that I do not necessarily use the latest git master (or release) for source code, if an older release has fewer dependencies (for example, recent code may require gtk4, instead of older gtk3).

Since other users have not noticed this issue, I must assume that it is specific to only some source code. Issue closed.

**Comment by xtkoba** [comment]
Ref: #12426 (PR for a fake `ldd` command).
