### ISSUE TITLE
rust linked to libllvm 14

### ISSUE THREAD

**Issue by franklaranja** [termux/termux-packages#12008]
after todays upgrade rust stopped working:
rustc -v
CANNOT LINK EXECUTABLE "rustc": library "libLLVM-14.so" not found

Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=25332
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
sources.list
deb https://termux.astra.in.ua/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.29.2
Android version:
9
Kernel build information:
Linux localhost 4.9.148 #1 SMP PREEMPT Tue Feb 22 17:24:32 CST 2022 aarch64 Android

**Comment by tmgast** [comment]
Same issue for me.

`libllvm` is now on `v15.0.0`
`rust` is on `1.63.0`

rust 1.65 adds compatibility with llvm-15 but isn't available yet.

**Comment by AndrielFR** [comment]
Same for me

**Comment by tgarrell** [comment]
Is there a lead time to the package getting uodated? I've tried reinstalling and updating my package since #12013 went in, but it still seems to be compiled against LLVM 14

**Comment by Grimler91** [comment]
@tgarrell rust takes ~2h to build and become available on main (packages.termux.dev) repo. After that it might take a few hours before all mirrors have mirrored it. If rust 1.63.0-1 is still not available you can try switching to another mirror with `termux-change-repo`

**Comment by AndrielFR** [comment]
Now it gives me
```bash
† rustc --version
CANNOT LINK EXECUTABLE "rustc": cannot locate symbol "LLVMConstExtractValue" referenced by "/data/data/com.termux/files/usr/lib/librustc_driver-1a7b7f67c04da79d.so"...
```

**Comment by mildcnvce001** [comment]
> Now it gives me
> 
> ```shell
> † rustc --version
> CANNOT LINK EXECUTABLE "rustc": cannot locate symbol "LLVMConstExtractValue" referenced by "/data/data/com.termux/files/usr/lib/librustc_driver-1a7b7f67c04da79d.so"...
> ```

Same for me now, 1.63.0 rev 1 update, after "xtkoba" #12013 commit

**Comment by lybekk** [comment]
For future visitors stumbling upon this issue. 
As of today, running `pkg upgrade` upgrading all packages resolved the issue.
