### ISSUE TITLE
ffnpeg missing a needed library

### ISSUE THREAD

**Issue by gappleto97** [termux/termux-packages#1201]
I'm trying to automate some video conversion, and I can't get ffmpeg to actually run on termux. The same command works on my desktop. The error it throws is:

```
ffmpeg -i storage/dcim/VID_20170727_185335Z.mp4 storage/dcim/VID_20170727_185335Z.webm
CANNOT LINK EXECUTABLE "ffmpeg": library "libc++_shared.so" not found
Aborted
```

**Comment by fornwall** [comment]
Can you run `apt update && apt upgrade` to ensure that you have the latest version of all packages and try again?

**Comment by gappleto97** [comment]
Gah. Sorry for my stupidity. I really should know better than this by now.
