### ISSUE TITLE
[Bug]: rustc-nightly is outdated and linked to libllvm 14

### ISSUE THREAD

**Issue by sk0kanik** [termux/termux-packages#12042]
### Problem description

rustc-nightly is outdated and linked to libllvm 14

### What steps will reproduce the bug?

~ $ apt install rustc-nightly
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
rustc-nightly is already the newest version (1.61.0-1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```
~ $ rustc
```
CANNOT LINK EXECUTABLE "rustc": library "libLLVM-14.so" not found: needed by /data/data/com.termux/files/usr/opt/rust-nightly/lib/librustc_driver-9c080be5f4455daa.so in namespace (default)
```

### What is the expected behavior?

fixing this broken package or moving to disable-packages to maintain stable rust only

### System information

Packages CPU architecture:
aarch64
Subscribed repositories:
deb https://packages.termux.dev/apt/termux-main stable main
Updatable packages:
libnghttp2/stable 1.50.0 aarch64 [upgradable from: 1.49.0]
termux-tools version:
1.29.2
Android version:
11
Kernel build information:
Linux localhost 4.19.127-ge275d78fd-dirty #1 SMP PREEMPT Tue Jun 7 20:09:08 CST 2022 aarch64 Android

**Comment by Grimler91** [comment]
Disabling sounds good to me, no one has touched the package since it was added
