### ISSUE TITLE
firebase-tools install error

### ISSUE THREAD

**Issue by godza-kauyani** [termux/termux-packages#1206]
firebase-tools can no longer be installed on nodejs  the following error

└── (empty)

npm ERR! Linux 3.10.72+
npm ERR! argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "install" "-g" "firebase-tools"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.3.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.3.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/data/com.termux/files/home/npm-debug.log
npm ERR! code 1

**Comment by accmail** [comment]
Hello i get same error i tried this https://stackoverflow.com/questions/37335259/trying-to-rollback-firebase-version-to-2-x but instead of version 2 i installed 3.9.1 and then updated to latest 3.9.2
maybe if you after "sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}"
try install 3.9.2 it would probably work

**Comment by OmarSharif** [comment]
Is there a solution to this issue? I am facing the same issue right now. Above answer did not work for me.

**Comment by GUILLALAB** [comment]
I exactly have the same problem, i updated node and npm but it didn't solve the problem.

**Comment by vishalbiswas** [comment]
Install `nodejs-current`. Then try installing it again.

**Comment by GUILLALAB** [comment]
My current node version is v8.2.1.
I tried to install nodes-current, but it say Not Found:
 sudo npm install nodejs-current
npm ERR! code E404
npm ERR! 404 Not Found: nodejs-current@latest

**Comment by vishalbiswas** [comment]
@GUILLALAB I meant `pkg install nodejs-current`

**Comment by GUILLALAB** [comment]
@vishalbiswas unfortunately i'm not on freeBSD, i don't have pkg command as i'am on a mac. 
But if try with npm, and i place a dot a the end of the command, it says :
ERR! Could not install from "" as it does not contain a package.json file.

**Comment by vishalbiswas** [comment]
@GUILLALAB `pkg` is a wrapper for `apt` in termux.

**Comment by GUILLALAB** [comment]
@vishalbiswas Thanks you, i'll try this. I'm not using termux currently but i have this problem.

**Comment by wschenk** [comment]
I have the same problem.  The issue seems to be the grpc node package that doesn't build.  Node-pre-gyp is used to download a prebuilt version of this, which it can't find. (gyp seems to think that the platform is android and the libc type is "unknown" which is why it can't find a binary for it.)  So it falls back to building grpc directly.

This fails because "clang-5.0: error: unknown argument: '-zdefs'"  So it's something wrong I think with node-gyp not setting the build settings correctly or identifying the platform correctly.

**Comment by fornwall** [comment]
Any help by someone who knows node well would be very appreciated!

**Comment by wschenk** [comment]
here's a work around: https://medium.com/@wschenk/getting-firebase-and-grpc-working-under-termux-115c25317ce3

**Comment by Adarshreddyash** [comment]
one  of firebase developers suggested me to use node 6 instead latest version. @wschenk may be this post may help

**Comment by Adarshreddyash** [comment]
Please downgrade your npm version to 6  then deploy it  works.. As firebase is well designed for 6 and getting better for 8.. @wschenk @fornwall @godza-kauyani

**Comment by Adarshreddyash** [comment]
Use npm install -g npm@6 to downgrade

**Comment by Adarshreddyash** [comment]
close  #1206

**Comment by xeffyr** [comment]
Can be installed with latest **nodejs-lts** package:
```
~ $ npm install -g firebase-tools
/data/data/com.termux/files/usr/bin/firebase -> /data/data/com.termux/files/usr/lib/node_modules/firebase-tools/lib/bin/firebase.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/firebase-tools/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"android","arch":"arm"})

+ firebase-tools@7.3.2
added 410 packages from 250 contributors in 34.779s
```

Closing issue as *outdated*.
