### ISSUE TITLE
[Bug]: cryptography won't install

### ISSUE THREAD

**Issue by guranu** [termux/termux-packages#12083]
### Problem description

Cryptography won't install even with CARGO_BUILD
the error is diffrent from the usual "can't install cryptography" issues 
![Screenshot_20220923-140103_1](https://user-images.githubusercontent.com/103632948/192013998-e5acbb20-8d9c-4930-8d19-aab906e79ea3.jpg)

### What steps will reproduce the bug?

[termux.txt](https://github.com/termux/termux-packages/files/9635666/termux.txt)

This is the only method for me to post the output of the command.

### What is the expected behavior?

For it work

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=29753
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.29.2
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Thu Jan 28 00:40:44 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
GM1900
```

**Comment by xtkoba** [comment]
Seems like due to migration to LLVM 15, maybe?

A quick workaround (meant for devs):

```diff
--- cryptography-38.0.1/src/rust/Cargo.toml.orig
+++ cryptography-38.0.1/src/rust/Cargo.toml
@@ -22,5 +22,5 @@
 crate-type = ["cdylib"]
 
 [profile.release]
-lto = "thin"
+#lto = "thin"
 overflow-checks = true
```

We may consider adding this (`python-cryptography`) as a Termux package, unless we can devise a non-trivial workaround.

**Comment by xtkoba** [comment]
But we should first bump Rust to 1.64.0. As I said in another place, the current Rust version (1.63.0) is only working by backporting some patches wrt LLVM 15 and is not officially guaranteed to work correctly.

**Comment by guranu** [comment]
So this is a rust issue then?

**Comment by guranu** [comment]
If so how do i downgrade it?

**Comment by xtkoba** [comment]
Now I have decided to add the `python-cryptography` package (PR #12084) which will become available in few hours. If you have any trouble installing and using that package, then please open another issue. I'm not going to handle the issue of on-device building through `pip` anymore. Thanks.

**Comment by xtkoba** [comment]
Turns out that the situation does not change with Rust 1.64.0.

Another workaround (which is far easier than the previous one):

```bash
export RUSTFLAGS+=" -C lto=no"
pip install cryptography
```
