### ISSUE TITLE
[Bug]: mesa build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#12086]
### Problem description

                ^
../src/src/gallium/auxiliary/gallivm/lp_bld_arit.c:1295:17: note: did you mean 'LLVMConstFDiv'?
../src/src/gallium/auxiliary/gallivm/lp_bld_arit.c:1293:17: note: 'LLVMConstFDiv' declared here
         return LLVMConstFDiv(a, b);
                ^
../src/src/gallium/auxiliary/gallivm/lp_bld_arit.c:1295:17: error: incompatible integer to pointer conversion returning 'int' from afunction with result type 'LLVMValueRef' (aka 'struct LLVMOpaqueValue *') [-Werror,-Wint-conversion]
         return LLVMConstSDiv(a, b);
                ^~~~~~~~~~~~~~~~~~~
../src/src/gallium/auxiliary/gallivm/lp_bld_arit.c:1297:17: error: implicit declaration of function 'LLVMConstUDiv' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
         return LLVMConstUDiv(a, b);
                ^
../src/src/gallium/auxiliary/gallivm/lp_bld_arit.c:1297:17: error: incompatible integer to pointer conversion returning 'int' from afunction with result type 'LLVMValueRef' (aka 'struct LLVMOpaqueValue *') [-Werror,-Wint-conversion]
         return LLVMConstUDiv(a, b);
                ^~~~~~~~~~~~~~~~~~~
../src/src/gallium/auxiliary/gallivm/lp_bld_arit.c:2649:14: error: implicit declaration of function 'LLVMConstFDiv' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      return LLVMConstFDiv(bld->one, a);
             ^
../src/src/gallium/auxiliary/gallivm/lp_bld_arit.c:2649:14: error: incompatible integer to pointer conversion returning 'int' from afunction with result type 'LLVMValueRef' (aka 'struct LLVMOpaqueValue *') [-Werror,-Wint-conversion]
      return LLVMConstFDiv(bld->one, a);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/src/gallium/auxiliary/gallivm/lp_bld_arit.c:3760:10: warning: 'LLVMBuildLoad' is deprecated: Use LLVMBuildLoad2 instead to support opaque pointers [-Wdeprecated-declarations]
         LLVMBuildLoad(builder, mxcsr_ptr, "mxcsr");
         ^
/data/data/com.termux/files/usr/include/llvm-c/Core.h:3926:1: note: 'LLVMBuildLoad' has been explicitly marked deprecated here
LLVM_ATTRIBUTE_C_DEPRECATED(
^
/data/data/com.termux/files/usr/include/llvm-c/Deprecated.h:26:23: note: expanded from macro 'LLVM_ATTRIBUTE_C_DEPRECATED'
  decl __attribute__((deprecated(message)))
                      ^
1 warning and 16 errors generated.
[833/978] Compiling C object src/gallium/auxiliary/libgallium.a.p/gallivm_lp_bld_assert.c.o
../src/src/gallium/auxiliary/gallivm/lp_bld_assert.c:91:4: warning: 'LLVMBuildCall' is deprecated: Use LLVMBuildCall2 instead to support opaque pointers [-Wdeprecated-declarations]
   LLVMBuildCall(builder, function, args, ARRAY_SIZE(args), "");
   ^
/data/data/com.termux/files/usr/include/llvm-c/Core.h:4029:1: note: 'LLVMBuildCall' has been explicitly marked deprecated here
LLVM_ATTRIBUTE_C_DEPRECATED(
^
/data/data/com.termux/files/usr/include/llvm-c/Deprecated.h:26:23: note: expanded from macro 'LLVM_ATTRIBUTE_C_DEPRECATED'
  decl __attribute__((deprecated(message)))
                      ^
1 warning generated.
[843/978] Compiling C++ object src/compiler/glsl/libglsl.a.p/builtin_functions.cpp.o
ninja: build stopped: subcommand failed.
builder@ab6a0afe2fbf:~/termux-packages$ ./build-package.sh -i mesa

[mesa.txt](https://github.com/termux/termux-packages/files/9637293/mesa.txt)

### What steps will reproduce the bug?

building

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Mesa 22.1.0 does not support LLVM 15. Build failure is pretty much expected. Bumping to Mesa 22.2.0 has its own issue: see #12054. It is not going to be fixed any time soon.
