### ISSUE TITLE
Web Application Penetration Testing Tools Package Request

### ISSUE THREAD

**Issue by cr4shcod3** [termux/termux-packages#1209]
@fornwall sir can you add some tools for this like w3af, vega, or skipfish? I will really appreciate if there is :)

**Comment by cr4shcod3** [comment]
Sir @Neo-Oli I have termux-fedora but i dont know what tools is in the packages

**Comment by sdrausty** [comment]
It looks like w3af, vega and skipfish are currently available in Termux through Arch Linux PRoot.  This script is designed to install Arch Linux in just a few keystrokes. Tapping this link https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh will transfer `setupTermuxArch.sh` to your device. Simply run `bash ~/storage/downloads/setupTermuxArch.sh` to install Arch Linux in Termux.  

![screenshot_20171203-090135](https://user-images.githubusercontent.com/27742457/33526057-ac91f818-d808-11e7-8a34-d90c64726a62.png)


To add Archstrike and Blackarch distributions that provide the tools follow these steps.  Use https://sdrausty.github.io/TermuxArch/ to install, update and configure Arch Linux on device first. 

Edit your /etc/pacman.conf by adding:

[archstrike] 
Server = https://mirror.archstrike.org/$arch/$repo

[blackarch] 
Server = http://blackarch.org/blackarch/$repo/os/$arch

Next run pacman -Syu to update your repository listing.  Then to install either distribution, run one of these commands:

pacman -S archstrike --needed
pacman -S blackarch --needed

:: There are 663 members in group archstrike: ~2G download (~6G on device)
:: There are 1602 members in group blackarch: ~5G download (~16G on device)

That's a lot of pentesting.  If you don't desire this much pentesting, don't install everything. 

## To search only for packages use `pacman -Ss {query}`.  To install use `pacman -S {package}`. 

Enjoy 😀
