### ISSUE TITLE
Add --with-http_sub_module to nginx build instructions

### ISSUE THREAD

**Issue by vstavrinov** [termux/termux-packages#12095]
### Problem description

The ngx_http_sub_module module is a filter that modifies a response by replacing one specified string by another.

My use case:

I am using acestream-service on my Android TV locally without nginx. But for remote access it requires rewrite host and port with proxying to local service. Here is where nginx with it's filter come in. 

Thank You for Your work.

**Comment by Pandip78** [comment]
Unable to create pakage and install

**Comment by vstavrinov** [comment]
@Pandip78 
> Unable to create pakage and install

What package?

**Comment by Pandip78** [comment]
All pakages

**Comment by vstavrinov** [comment]
@Pandip78 
What are talking about? How does it relate to this issue?

**Comment by Grimler91** [comment]
Added in https://github.com/termux/termux-packages/commit/3ad66e3caec1cb942114f8cbad211016437ef2d5
