### ISSUE TITLE
g++ missing libstdc++

### ISSUE THREAD

**Issue by plattfot** [termux/termux-packages#121]
Looks like when running "apt install g++" libstdc++ doesn't get installed. Unable to compile any c++ code that uses the standard library.

**Comment by fornwall** [comment]
The default Android `libstdc++` is a minimal one that doesn't support STL or std io. You need to explicitly link with `-lgnustl_shared` for a more fully featured C++ library - see http://developer.android.com/ndk/guides/cpp-support.html#system.

This will be documented at https://termux.com/help.html soon - there is the issue https://github.com/termux/termux-packages/issues/33 open for that!

**Comment by plattfot** [comment]
Didn't know that, thanks.
