### ISSUE TITLE
[Enhancement]: properties.sh: allow use of existing JAVA_HOME variable

### ISSUE THREAD

**Issue by lonxwolx** [termux/termux-packages#12104]
tried to run setup-android-sdk.sh get an error
```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-8-openjdk-amd64

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```
I use void so I tried setting JAVA_HOME to right one:
```
$ printenv JAVA_HOME
/usr/lib/jvm/java-1.8-openjdk
```
 but still got the same error
```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-8-openjdk-amd64

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

**Comment by xtkoba** [comment]
Not supposed to be used outside our Docker image, I would say. But PR is welcome if you can improve `properties.sh`.

**Comment by lonxwolx** [comment]
I was thinking of this:
`export JAVA_HOME=${JAVA_HOME:-/usr/lib/jvm/java-8-openjdk-amd64}`
or this, I haven't tried this on the docker image, but I think it would also work.
`export JAVA_HOME=$(dirname $(dirname $(realpath $(which java))))`

**Comment by tomty89** [comment]
Actually what you/we really want to have is that the script would use existing `JAVA_HOME` value only when `/usr/lib/jvm/java-8-openjdk-amd64` does not exist.

**Comment by charle426** [comment]
## Transcript

```
You can now launch Ubuntu with the ./start-ubuntu20.sh script form next time                                          proot warning: can't sanitize binding "/proc/self/fd/0": No such file or directory
Err:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.                               W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal/InRelease  Temporary failure resolving 'ports.ubuntu.com'                                                    W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-updates/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-backports/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-security/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package wget
~ $
```
##


## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##


## Device Info

### Software

**OS_VERSION**: `4.4.146+`  
**SDK_INT**: `28`  
**RELEASE**: `9`  
**ID**: `PPR1.180610.011`  
**DISPLAY**: `X604-H633H-P-191113V280`  
**INCREMENTAL**: `H-191113V280`  
**SECURITY_PATCH**: `2019-11-05`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `INFINIX MOBILITY LIMITED`  
**BRAND**: `Infinix`  
**MODEL**: `Infinix X604`  
**PRODUCT**: `H633`  
**BOARD**: `X604_H633`  
**HARDWARE**: `mt6763`  
**DEVICE**: `Infinix-X604_sprout`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##


## Termux APT Info


### Subscribed Repositories

#### sources.list
`deb https://packages.termux.dev/apt/termux-main stable main`
#### root-repo (sources.list.d/root.list)
`deb https://packages.termux.dev/apt/termux-root root stable`  
#### x11-repo (sources.list.d/x11.list)
`deb https://packages.termux.dev/apt/termux-x11 x11 main`  
##


### Updatable Packages

```
grep/stable 3.8 aarch64 [upgradable from: 3.7-2]
libjpeg-turbo/stable 2.1.4 aarch64 [upgradable from: 2.1.3]
speexdsp/stable 1.2.1 aarch64 [upgradable from: 1.2.0-2]
```
##



##

**Comment by charle426** [comment]
Am problem here connecting to vscode

**Comment by lonxwolx** [comment]
how about something like this:
```
if [ -d /usr/lib/jvm/java-8-openjdk-amd64 ]; then
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
fi
```
Is it fine to leave the `JAVA_HOME` variable unset if it's unset?

**Comment by truboxl** [comment]
We run `setup-ubuntu.sh` then `setup-android-sdk.sh`
Anything outside Ubuntu 22.04 is on your own

**Comment by charle426** [comment]
I can't open vscode
