### ISSUE TITLE
VNC for Termux

### ISSUE THREAD

**Issue by cr4shcod3** [termux/termux-packages#1210]
Is there a VNC for Termux???

**Comment by cr4shcod3** [comment]
Please close this. I forgot that I already have an open request

**Comment by sdrausty** [comment]
You should be able to close this issue yourself, since you opened it, by using the "Close Issue" button. @cr4shcod3

**Comment by cr4shcod3** [comment]
Thanks @sdrausty. Im just new in github :)

**Comment by sdrausty** [comment]
It appears that VNC is available. See https://wiki.termux.com/wiki/VNC
