### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by OceanWanderer4life** [termux/termux-packages#12144]
Can someone tell me the password for termux

**Comment by TomJo2000** [comment]
If you've never set one you'll want to use `passwd` to set one.
Termux sets no password by default, and it should only require one if you are trying to connect over SSH with password authentication.

**Comment by 2096779623** [comment]
Set your user password(not display)
```
pkg i termux-auth -y
passwd
```
Vnc password:
`vncpasswd`
