### ISSUE TITLE
[Bug]: `dbus` is still version `1.15.0`

### ISSUE THREAD

**Issue by babaric-dev** [termux/termux-packages#12162]
### Problem description

`dbus` should be updated to version `1.15.0_1` in #12140. But it is still not available on Termux repos.

Newest version of `dbus` is `1.15.0` [here](https://packages.termux.dev/apt/termux-main/pool/main/d/dbus/).

**Comment by xtkoba** [comment]
Weird. IIRC I saw ones in the main repo. <a href="https://grimler.se/termux-packages-24/pool/main/d/dbus/">grimler.se mirror</a> does have ones as of now.

**Comment by babaric-dev** [comment]
Then is it a bug for [packages.termux.dev](https://packages.termux.dev)?

**Comment by xtkoba** [comment]
Now populated in the main repo. For maintainers: if they disappear again, then please try revbumping.

Yeah, it could be some kind of server error. I'm not sure though.

**Comment by babaric-dev** [comment]
I can confirm `1.15.0-1` is available now. Closing as complete.
