### ISSUE TITLE
[Bug]: ssdb improper packaging

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#12205]
### Problem description

package `ssdb` does not symlink its binaries so commands like `ssdb-server` won't be available.

Then after manually `cd`ing into the directory:
```
/d/d/c/f/u/o/ssdb  ./ssdb-server ssdb.conf
ssdb-server 1.9.8
Copyright (c) 2012-2015 ssdb.io

'./var' is not a directory or not exists!
 ✘  /d/d/c/f/u/o/ssdb 
```
This is however quickly fixed with a `mkdir var` folder in there, which the Makefile also does.

### What steps will reproduce the bug?

```
$ pkg install ssdb
$ ssdb-server
```

### What is the expected behavior?

Binaries are available in PATH and the var directory exists to let the server start.

### System information

termux-info:

```
N/A
```

**Comment by 2096779623** [comment]
https://github.com/ideawu/ssdb/blob/3e556e4bf4cee96d2577e3c3002f00c540e4ba10/ssdb.conf#L5

>  absolute path, or relative to path of this file, directory must exists.

**Comment by ravener** [comment]
> https://github.com/ideawu/ssdb/blob/3e556e4bf4cee96d2577e3c3002f00c540e4ba10/ssdb.conf#L5
> 
> >  absolute path, or relative to path of this file, directory must exists.

And the problem is that the one packaged in Termux does not include that folder.

**Comment by Grimler91** [comment]
Default config path changed. As for adding symlinks, I'm not sure why @xtkoba put the package in $PREFIX/opt to begin with so not sure if it is safe to symlink to $PREFIX/bin (or install to $PREFIX instead)
