### ISSUE TITLE
[Bug]: libfm-qt build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#12209]
### Problem description

[libfm-qt.txt](https://github.com/termux/termux-packages/files/9677980/libfm-qt.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Thanks for reporting, should be fixed in 2432c02a907a1c6de779186d1a35d7b888fdbed5.
