### ISSUE TITLE
[Package]: opensubdiv

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#12200]
### Why do you want to add this package to Termux?

Required for blender 

### Home page URL

https://github.com/PixarAnimationStudios/OpenSubdiv

### Source code URL

https://github.com/PixarAnimationStudios/OpenSubdiv/archive/refs/tags/v3_5_0.tar.gz

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

It has some weird patches [here](https://github.com/archlinux/svntogit-community/blob/packages/opensubdiv/trunk/PKGBUILD)

Skeleton build.sh
```bash
TERMUX_PKG_HOMEPAGE=http://graphics.pixar.com/opensubdiv
TERMUX_PKG_DESCRIPTION="An Open-Source subdivision surface library"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=3.5.0
TERMUX_PKG_SRCURL=https://github.com/PixarAnimationStudios/OpenSubdiv/archive/refs/tags/v${TERMUX_PKG_VERSION//./_}.tar.gz
TERMUX_PKG_SHA256=8f5044f453b94162755131f77c08069004f25306fd6dc2192b6d49889efb8095
TERMUX_PKG_DEPENDS="ptex, libtbb, libxcursor, xorg-xrandr, libxinerama"
TERMUX_PKG_BUILD_DEPENDS="python, doxygen, glfw, glew, opencl-headers" #cuda missing?
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DNO_CUDA=1"

termux_step_pre_configure() {
        _PYTHON_VERSION=$(. $TERMUX_SCRIPTDIR/packages/python/build.sh; echo $_MAJOR_VERSION)
        termux_setup_python_crossenv
        pushd $TERMUX_PYTHON_CROSSENV_SRCDIR
        _CROSSENV_PREFIX=$TERMUX_PKG_BUILDDIR/python-crossenv-prefix
        python${_PYTHON_VERSION} -m crossenv \
                $TERMUX_PREFIX/bin/python${_PYTHON_VERSION} \
                ${_CROSSENV_PREFIX}
        popd
        . ${_CROSSENV_PREFIX}/bin/activate

        build-pip install pygments docutils
}
```
If cuda is added we can build it with it
But cuda...
```
Package Size:	1.3 GB
Installed Size:	3.8 GB
```

**Comment by T-Dynamos** [comment]
And what does this means

https://github.com/archlinux/svntogit-community/blob/9e0ada71ababba82cee4eec41e56230e7f583bec/trunk/PKGBUILD#L32-L35

**Comment by 2096779623** [comment]
> Instead of adding one-by-one each of Blender dependency, please add them in one pull request. Just to note that if Blender packaging will be failed, the standalone library packages will be mostly useless.
