### ISSUE TITLE
[Bug]:CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash"

### ISSUE THREAD

**Issue by markkco** [termux/termux-packages#12216]
### Problem description

After updating bash, binutils, termux-tools, termux-am-socket cannot get to shell. Termux displays:
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": cannot locate symbol "rl_trim_arg_from_keyseq" referenced by "/data/data/com.termux/files/usr/bin/bash"...
[Process completed (code 1) - Press Enter]

### Steps to reproduce the behavior.

pkg install bash binutils termux-tools termux-am-socket termux-keyring

### What is the expected behavior?

After updating bash termux should start in bash shell.

### System information

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: Xiaomi Poco X3 Pro

**Comment by markkco** [comment]
Thank you! Successfully updated!

**Comment by MrQueen** [comment]
Thank you guys,  solved my problem. @markkco @Grimler91

**Comment by amar-ke** [comment]
‏afaf_khellou55‏

**Comment by ququleader-stack** [comment]
import 'package:flutter/material.dart';
import 'dart:math';

void main() {
  runApp(TapmacaApp());
}

class TapmacaApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Tapmaca Oyunu',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: TapmacaPage(),
    );
  }
}

class TapmacaPage extends StatefulWidget {
  @override
  _TapmacaPageState createState() => _TapmacaPageState();
}

class _TapmacaPageState extends State<TapmacaPage> {
  final List<Map<String, dynamic>> questions = [
    {'question': '2 + 2 = ?', 'answers': ['3', '4', '5', '6'], 'correct': '4'},
    {'question': '5 - 3 = ?', 'answers': ['1', '2', '3', '4'], 'correct': '2'},
    {'question': '3 x 3 = ?', 'answers': ['6', '9', '8', '12'], 'correct': '9'},
    {'question': '10 ÷ 2 = ?', 'answers': ['2', '5', '10', '20'], 'correct': '5'},
  ];

  int score = 0;
  int currentIndex = 0;

  void checkAnswer(String answer) {
    if (answer == questions[currentIndex]['correct']) {
      setState(() {
        score++;
      });
      _showSnackBar('Düzgün cavab! 👍');
    } else {
      _showSnackBar('Səhv cavab! ❌');
    }
    _nextQuestion();
  }

  void _nextQuestion() {
    setState(() {
      currentIndex = (currentIndex + 1) % questions.length;
    });
  }

  void _showSnackBar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message), duration: Duration(seconds: 1)),
    );
  }

  @override
  Widget build(BuildContext context) {
    final currentQuestion = questions[currentIndex];
    return Scaffold(
      appBar: AppBar(
        title: Text('Tapmaca Oyunu'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              currentQuestion['question'],
              style: TextStyle(fontSize: 24),
            ),
            SizedBox(height: 20),
            ...currentQuestion['answers'].map<Widget>((answer) {
              return Padding(
                padding: const EdgeInsets.symmetric(vertical: 8.0),
                child: ElevatedButton(
                  onPressed: () => checkAnswer(answer),
                  child: Text(answer, style: TextStyle(fontSize: 20)),
                ),
              );
            }).toList(),
            SizedBox(height: 30),
            Text('Sənin xalın: $score', style: TextStyle(fontSize: 22)),
          ],
        ),
      ),
    );
  }
}
