### ISSUE TITLE
[Package]: python-pyqtwebengine

### ISSUE THREAD

**Issue by eliranwong** [termux/termux-packages#12211]
### Feature description

I want to run python-pyqt5-webengine on Termux

### Additional information

Right now I can "pkg install pyqt5" but that does not include QtWebEngineWidgets

Therefore, it failed to run "from PyQt5 import QtWebEngineWidgets" via python

### Home page URL

https://www.riverbankcomputing.com/software/pyqtwebengine/

### Source code URL

https://files.pythonhosted.org/packages/source/P/PyQtWebEngine/PyQtWebEngine-5.15.6.tar.gz

**Comment by xtkoba** [comment]
Does not either build nor run without `qt5-qtwebengine` (#10070). May build with stub libs, but it would not make much sense.

**Comment by xtkoba** [comment]
"Wontfix" until `qt5-qtwebengine` is packaged. Thanks.

**Comment by xtkoba** [comment]
Added "package request" label to prevent Stale Bot from interfering.

**Comment by Mame29** [comment]
has this problem been resolved ?

**Comment by Mame29** [comment]
if not solved, try this
```sh
sip-wheel --qmake-setting 'QMAKE_CXXFLAGS += -I/data/data/com.termux/files/usr/include/QtPrintSupport -I/data/data/com.termux/files/usr/include/QtWebChannel' --qmake-setting 'QMAKE_LFLAGS += -L/data/data/com.termux/files/usr/lib -lpython3.11 -lQt5WebEngineCore -lQt5Quick -lQt5Gui -lQt5QmlModels -lQt5Qml -lQt5Network -lQt5Core -lQt5WebEngine -lQt5WebEngineWidgets -lQt5Widgets'```

**Comment by Mame29** [comment]
my result

![Screenshot_20230115_114311](https://user-images.githubusercontent.com/72637907/212591701-2f4685a3-46aa-4e6c-adb8-6a13abc8eeee.jpg)
![Screenshot_20230115_115226](https://user-images.githubusercontent.com/72637907/212591749-e1f69f61-c77d-4df5-b63f-77ecb0ea15a8.jpg)
![Screenshot_20230115_115301](https://user-images.githubusercontent.com/72637907/212591822-69b080a3-2c71-45ee-abfc-232e849bd204.jpg)

**Comment by codemona** [comment]
@Mame29 
How did you install it? I have built the wheel but it is not installing.

![Screenshot_Termux](https://user-images.githubusercontent.com/122843517/212789144-6b3f1e17-a1cd-4034-ab64-30da4f89fd28.jpg)

**Comment by Mame29** [comment]
> 

I change file name to `PyQtWebEngine-5.15.6-cp311-abi3-linux_aarch64.whl`

**Comment by codemona** [comment]
It worked, Thanks

**Comment by eliranwong** [comment]
> ```shell
> sip-wheel
> ```

I want to try, but 'sip-wheel' command not found.  May I ask how can I install sip-wheel command on Termux?

**Comment by Mame29** [comment]
> > ```shell
> > sip-wheel
> > ```
> 
> I want to try, but 'sip-wheel' command not found. May I ask how can I install sip-wheel command on Termux?

now install with commad `pkg update -y && pkg install python-pyqtwebengine`

**Comment by codemona** [comment]
Can it build using python3.9?
