### ISSUE TITLE
[Bug]: iwyu build failure

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#12218]
### Problem description

[iwyu.txt](https://github.com/termux/termux-packages/files/9684254/iwyu.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by 2096779623** [comment]
What is your clang version?

https://github.com/include-what-you-use/include-what-you-use/issues/1073

**Comment by johndebia2022** [comment]
> What is your clang version?
> 
> [include-what-you-use/include-what-you-use#1073](https://github.com/include-what-you-use/include-what-you-use/issues/1073)

I am using pre-build termux docker image

**Comment by buttaface** [comment]
Known issue, #12003, will have to wait till they support LLVM 15.

**Comment by xtkoba** [comment]
Fixed by commit 32d15557ad0cb430ca8e42fb9049c2d009053280.
