### ISSUE TITLE
[Bug]: chezmoi fails to run scripts

### ISSUE THREAD

**Issue by VorpalBlade** [termux/termux-packages#12220]
### Problem description

chezmoi installed from the official termux repositories fail to execute scripts. This is specific to the termux environment, and works fine on normal desktop Linux.

Based on a bug report in chezmoi this is a termux bug: https://github.com/twpayne/chezmoi/issues/2345

The issue seems to be that termux uses LD_PRELOAD hacks that don't take effect on programs written in Go. An alternative solution to enable full functionality on Termux is needed (as the upstream developer does not consider this a bug in chezmoi).

### Steps to reproduce the behavior.

```console
$ pkg install chezmoi
$ chezmoi init
$ chezmoi cd
$ echo "#!/usr/bin/env bash" > run_test.sh
$ echo "echo Hi" >> run_test.sh
$ chezmoi apply
```

### What is the expected behavior?

The `run_` script should execute, and in this case print "Hi"

Instead you will get an output like the following:
```
chezmoi: fork/exec /data/data/com.termux/files/usr/tmp/1634744225.test.sh: no such file or directory
```

### System information

* Termux application version: Termux from F-Droid version 0.118.0
* Android OS version: Android 11
* Device model: OnePlus 6

**Comment by 2096779623** [comment]
https://github.com/twpayne/chezmoi/issues/2345#issuecomment-1241338143

**Comment by Grimler91** [comment]
Is it possible to use templates in scripts? If yes then something like 

```
$ cat run_test.sh.tmpl
{{- if eq .chezmoi.os "android" }}
#!/data/data/com.termux/files/usr/bin/env bash
{{ else }}
#!/usr/bin/env bash
{{ end }}
echo Hi
```

could work. 
For it to work without such a workaround we would have to patch our golang and add the same functionality as we have in libtermux-exec. 

We have an open feature request for adding support for golang's "shebangs" (like `//usr/bin/go run $0 $@ ; exit`) over at https://github.com/termux/termux-exec/issues/22.

**Comment by VorpalBlade** [comment]
Ah, yes, It is possible to be even more elegant:

```
#!{{ lookPath "bash" }}
[ ... ]
```

That solves my immediate problem. However, that is specific to chezmoi. I don't know if there are any other Go programs that need to execute scripts that lack the template functionality. None that I use that I know of.
