### ISSUE TITLE
calculator

### ISSUE THREAD

**Issue by ForgettenAccount** [termux/termux-packages#12238]
### Why do you want to add this package to Termux?

Just a basic interactive calculator 

### Home page URL

https://github.com/ForgettenAccount/calculator

### Source code URL

https://github.com/ForgettenAccount/calculator

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Requirements:
Python 3+

**Comment by 2096779623** [comment]
You can go to [tur](https://github.com/termux-user-repository/tur) and create an issue.

> Packages must be active, well-known projects
> Software available in major Linux distributions has more chances to be included into Termux repositories. We will not accept outdated, dead projects as well as projects which do not have active community.
