### ISSUE TITLE
[Bug]: gdb build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#12254]
### Problem description

/home/builder/.termux-build/gdb/src/gdb/completer.c:295:18: warning: variable 'found_quote' set but not used [-Wunused-but-set-variable]
  int scan, end, found_quote, delimiter, pass_next, isbrk;
                 ^
  CXX    cp-support.o
/home/builder/.termux-build/gdb/src/gdb/completer.c:2039:10: error: cannot initialize return object of type 'char *' with an lvalue of type 'const char *'
  return rl_completer_word_break_characters;
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make[2]: *** [Makefile:1618: completer.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/builder/.termux-build/gdb/build/gdb'
make[1]: *** [Makefile:10066: all-gdb] Error 2
make[1]: Leaving directory '/home/builder/.termux-build/gdb/build'
make: *** [Makefile:854: all] Error 2

[gdb.txt](https://github.com/termux/termux-packages/files/9701266/gdb.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Already fixed by commit 8d0a66c915a14e23f87e14f1b3363304ce824acd.
