### ISSUE TITLE
[Bug]: tigervnc build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#12263]
### Problem description

checking for aarch64-linux-android-cpp... /home/builder/.termux-build/_cache/android-r25b-api-24-v0/bin/aarch64-linux-android-cpp
checking if /home/builder/.termux-build/_cache/android-r25b-api-24-v0/bin/aarch64-linux-android-cpp requires -undef... clang-14: error: no input files
clang-14: error: no input files
clang-14: error: no input files
configure: error: /home/builder/.termux-build/_cache/android-r25b-api-24-v0/bin/aarch64-linux-android-cpp defines unix with or without -undef.  I don't know what to do.

[tigervnc.txt](https://github.com/termux/termux-packages/files/9708942/tigervnc.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Already fixed by commit 29e245750531823d334f555ff8870b428dde1967.
