### ISSUE TITLE
qemu-system-x86_64 fails with Illegal instruction

### ISSUE THREAD

**Issue by radumamy** [termux/termux-packages#12261]
### Problem description

`qemu-system-x86_64` fails to provision / start a VM. I've tried an Alpine image and I keep getting `SeaBIOS (version rel-1.16.0-0-gd239552ce722-prebuilt.qemu.orgIllegal instruction` no matter what I try. Can this please be investigated? Many thanks.

### What steps will reproduce the bug?

qemu-system-x86_64  -name "Alpine" -M q35 \
  -cpu qemu64 \
  -smp 2 -m 2048 \
  -drive file=hdd.img,if=virtio \
  -netdev user,id=n1,hostfwd=tcp::2222-:22 \
  -device virtio-net,netdev=n1 \
  -cdrom alpine-virt-3.16.2-x86_64.iso -boot d \
  -nographic

### What is the expected behavior?

VM to boot

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=25022
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.bardia.tech/termux/termux-main stabln
Updatable packages:
All packages up to date
termux-tools version:
1.29.3
Android version:
12
Kernel build information:
Linux localhost 5.10.81-android12-9-00001-g19c16239b619d
Device manufacturer:
Sony
Device model:
XQ-CT54
```

**Comment by JeyKul** [comment]
Hey, i wanted to say, that i experience the same.

either it happens after it creates vnc or if you use -nographic it happends after the seabios output.

`/sdcard $ qemu-system-x86_64 -m 2048 -cdrom de_windows_7_professional_with_sp1_x86_dvd_u_677093.iso -hda hdd.img -nographic
SeaBIOS (version rel-1.16.0-0-gd239552ce722-prebuilt.qemu.orgIllegal instruction`

`/sdcard $ qemu-system-x86_64 -m 2048 -cdrom de_windows_7_professional_with_sp1_x86_dvd_u_677093.iso -hda hdd.img
VNC server running on 127.0.0.1:5900
Illegal instruction`

I am using an S22 ultra exynos. 



termux-info:

`Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
aria2/stable 1.36.0-5 aarch64 [upgradable from: 1.36.0-4]
bash/stable 5.2.2-3 aarch64 [upgradable from: 5.1.16-1]
ca-certificates/stable 1:2022.10.11 all [upgradable from: 1:2022.03.29]
clang/stable 15.0.2 aarch64 [upgradable from: 14.0.3-1]
command-not-found/stable 2.1.0-1 aarch64 [upgradable from: 1.75]
coreutils/stable 9.1-2 aarch64 [upgradable from: 9.1]
cups/stable 2.3.3-10 aarch64 [upgradable from: 2.3.3-9]
curl/stable 7.85.0 aarch64 [upgradable from: 7.83.1]
dialog/stable 1.3-20220728-0 aarch64 [upgradable from: 1.3-20220117-0]
dos2unix/stable 7.4.3 aarch64 [upgradable from: 7.4.2]
dpkg/stable 1.21.9 aarch64 [upgradable from: 1.21.7]
ffmpeg/stable 5.1.2 aarch64 [upgradable from: 5.0.1-1]
findutils/stable 4.9.0-2 aarch64 [upgradable from: 4.9.0-1]
game-music-emu/stable 0.6.3-1 aarch64 [upgradable from: 0.6.3]
gdbm/stable 1.23 aarch64 [upgradable from: 1.22]
git/stable 2.38.0 aarch64 [upgradable from: 2.36.1]
gnupg/stable 2.3.7 aarch64 [upgradable from: 2.3.6]
gpgv/stable 2.3.7 aarch64 [upgradable from: 2.3.6]
grep/stable 3.8-1 aarch64 [upgradable from: 3.7-2]
gzip/stable 1.12-1 aarch64 [upgradable from: 1.12]
harfbuzz/stable 5.3.0 aarch64 [upgradable from: 4.3.0]
inetutils/stable 2.3-2 aarch64 [upgradable from: 1.9.4-13]
krb5/stable 1.20 aarch64 [upgradable from: 1.19.3]
ldns/stable 1.8.3 aarch64 [upgradable from: 1.8.1-1]
less/stable 608 aarch64 [upgradable from: 590]
libaom/stable 3.5.0 aarch64 [upgradable from: 3.3.0]
libc++/stable 25b aarch64 [upgradable from: 23b-3]
libcompiler-rt/stable 15.0.2 aarch64 [upgradable from: 14.0.3-1]
libcurl/stable 7.85.0 aarch64 [upgradable from: 7.83.1]
libdb/stable 18.1.40-4 aarch64 [upgradable from: 18.1.40-3]
libevent/stable 2.1.12-2 aarch64 [upgradable from: 2.1.12-1]
libexpat/stable 2.4.9 aarch64 [upgradable from: 2.4.8]
libffi/stable 3.4.3 aarch64 [upgradable from: 3.4.2]
libgcrypt/stable 1.10.1-1 aarch64 [upgradable from: 1.10.1]
libgmp/stable 6.2.1-2 aarch64 [upgradable from: 6.2.1-1]
libgnutls/stable 3.7.7-1 aarch64 [upgradable from: 3.7.5]
libgraphite/stable 1.3.14-2 aarch64 [upgradable from: 1.3.14-1]
libjpeg-turbo/stable 2.1.4 aarch64 [upgradable from: 2.1.3]
libksba/stable 1.6.1 aarch64 [upgradable from: 1.6.0]
libllvm/stable 15.0.2 aarch64 [upgradable from: 14.0.3-1]
liblz4/stable 1.9.4 aarch64 [upgradable from: 1.9.3]
liblzma/stable 5.2.7 aarch64 [upgradable from: 5.2.5-1]
libnettle/stable 3.8.1 aarch64 [upgradable from: 3.7.3]
libnghttp2/stable 1.50.0 aarch64 [upgradable from: 1.47.0]
libpng/stable 1.6.38 aarch64 [upgradable from: 1.6.37-3]
libresolv-wrapper/stable 1.1.7-3 aarch64 [upgradable from: 1.1.7-2]
libsqlite/stable 3.39.3 aarch64 [upgradable from: 3.38.5]
libtiff/stable 4.4.0 aarch64 [upgradable from: 4.3.0-2]
libtirpc/stable 1.3.3 aarch64 [upgradable from: 1.3.2-1]
libunistring/stable 1.0-1 aarch64 [upgradable from: 1.0]
libvpx/stable 1:1.12.0-1 aarch64 [upgradable from: 1.11.0]
libwebp/stable 1.2.4 aarch64 [upgradable from: 1.2.2]
libx11/stable 1.7.5 aarch64 [upgradable from: 1.7.2-1]
libx265/stable 3.5-4 aarch64 [upgradable from: 3.5-3]
libxau/stable 1.0.10 aarch64 [upgradable from: 1.0.9-9]
libxcursor/stable 1.2.1 aarch64 [upgradable from: 1.2.0-20]
libxfixes/stable 6.0.0-1 aarch64 [upgradable from: 5.0.3-25]
libxi/stable 1.8 aarch64 [upgradable from: 1.7.10-23]
libxml2/stable 2.10.2-1 aarch64 [upgradable from: 2.9.14]
libxtst/stable 1.2.4 aarch64 [upgradable from: 1.2.3-26]
lld/stable 15.0.2 aarch64 [upgradable from: 14.0.3-1]
llvm/stable 15.0.2 aarch64 [upgradable from: 14.0.3-1]
lsof/stable 4.96.3 aarch64 [upgradable from: 4.95.0-1]
ncurses-ui-libs/stable 6.3-4 aarch64 [upgradable from: 6.3-1]
ncurses/stable 6.3-4 aarch64 [upgradable from: 6.3-1]
ndk-sysroot/stable 25b aarch64 [upgradable from: 23b-7]
nmap-ncat/stable 7.92-3 aarch64 [upgradable from: 7.92-2]
nmap/stable 7.92-3 aarch64 [upgradable from: 7.92-2]
openjdk-17/stable 17.0-24 aarch64 [upgradable from: 17.0-22]
openssh-sftp-server/stable 9.1p1 aarch64 [upgradable from: 9.0p1-2]
openssh/stable 9.1p1 aarch64 [upgradable from: 9.0p1-2]
openssl-1.1/stable 1:1.1.1q aarch64 [upgradable from: 1.1.1o]
openssl/stable 1:3.0.5 aarch64 [upgradable from: 3.0.3]
perl/stable 5.36.0-1 aarch64 [upgradable from: 5.36.0]
pinentry/stable 1.2.1 aarch64 [upgradable from: 1.2.0]
pkg-config/stable 0.29.2-2 aarch64 [upgradable from: 0.29.2-1]
procps/stable 3.3.17-2 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.5-1 aarch64 [upgradable from: 23.4]
python/stable 3.10.8 aarch64 [upgradable from: 3.10.4]
readline/stable 8.2.1 aarch64 [upgradable from: 8.1.1]
rust/stable 1.64.0 aarch64 [upgradable from: 1.61.0]
sed/stable 4.8-4 aarch64 [upgradable from: 4.8-2]
tar/stable 1.34-1 aarch64 [upgradable from: 1.34]
termux-am-socket/stable 1.5.0 aarch64 [upgradable from: 1.3.0]
termux-keyring/stable 3.9 all [upgradable from: 3.4]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-2]
termux-tools/stable 1.30.2 all [upgradable from: 0.181]
unbound/stable 1.16.3 aarch64 [upgradable from: 1.15.0-1]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-7]
update-info-dir/stable 6.8-6-0 all [upgradable from: 6.8-4-0]
util-linux/stable 2.38.1 aarch64 [upgradable from: 2.38]
wget/stable 1.21.3-4 aarch64 [upgradable from: 1.21.3-2]
x11-repo/stable 8.3 all [upgradable from: 8.1]
xorgproto/stable 2022.2 all [upgradable from: 2020.1-1]
xz-utils/stable 5.2.7 aarch64 [upgradable from: 5.2.5-1]
zlib/stable 1.2.13 aarch64 [upgradable from: 1.2.12]
zstd/stable 1.5.2-2 aarch64 [upgradable from: 1.5.2-1]
termux-tools version:
0.181
Android version:
13
Kernel build information:
Linux localhost 5.10.66-android12-9-25250107-abS908BXXU2ZVJ2 #2 SMP PREEMPT Wed Oct 5 11:02:27 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S908B`

**Comment by xtkoba** [comment]
Not happening on my ASUS_X01AD (Snapdragon 632) aarch64 Android 8.1.0.

We need more information about that illegal instruction. Would you please share the relevant part of `logcat` output if any?

**Comment by Grimler91** [comment]
Running the command that fails under strace would also be useful, i.e. run something like 

```
strace -o qemu.log qemu-system-x86_64 -name "openSUSE" -M q35 -smp 2 -m 1024M -drive file=opensuse.img,if=virtio
```

and then share the qemu.log file.

> Hi @xtkoba. Thank you for your reply. Can you please advise how I would use logcat?

Enable usb debugging in your device settings ([guide](https://www.lifewire.com/enable-usb-debugging-android-4690927)), and then connect your device to a computer, run the `qemu` command that gives the error on the device, and then run `adb logcat` on the comupter

**Comment by radumamy** [comment]
> Running the command that fails under strace would also be useful, i.e. run something like
> 
> ```
> strace -o qemu.log qemu-system-x86_64 -name "openSUSE" -M q35 -smp 2 -m 1024M -drive file=opensuse.img,if=virtio
> ```
> 
> and then share the qemu.log file.
> 
> > Hi @xtkoba. Thank you for your reply. Can you please advise how I would use logcat?
> 
> Enable usb debugging in your device settings ([guide](https://www.lifewire.com/enable-usb-debugging-android-4690927)), and then connect your device to a computer, run the `qemu` command that gives the error on the device, and then run `adb logcat` on the comupter

@Grimler91 Thank you. As requested, please see attached. 
[qemu.log](https://github.com/termux/termux-packages/files/9800432/qemu.log)

**Comment by xtkoba** [comment]
The following is not related to the QEMU issue. Just showing an example use of `logcat`:

```
$ ./lse
Illegal instruction

$ logcat
[...]
10-18 17:21:33.439  8410  8410 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-18 17:21:33.439  8410  8410 F DEBUG   : Build fingerprint: 'asus/WW_X01AD/ASUS_X01A_1:8.1.0/OPM1/15.2016.1902.159-20190227:user/release-keys'
10-18 17:21:33.439  8410  8410 F DEBUG   : Revision: '0'
10-18 17:21:33.439  8410  8410 F DEBUG   : ABI: 'arm64'
10-18 17:21:33.439  8410  8410 F DEBUG   : pid: 8407, tid: 8407, name: lse  >>> ./lse <<<
10-18 17:21:33.439  8410  8410 F DEBUG   : signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x5c79261680
10-18 17:21:33.439  8410  8410 F DEBUG   :     x0   0000000000000001  x1   0000005c79263938  x2   0000007fc596fdc8  x3   0000007fc596fd88
10-18 17:21:33.439  8410  8410 F DEBUG   :     x4   0000000000000001  x5   0000007040595578  x6   61642f617461642f  x7   fffffffffffffff0
10-18 17:21:33.439  8410  8410 F DEBUG   :     x8   0000000000000000  x9   0000000000000002  x10  0000000000000001  x11  0000000000000000
10-18 17:21:33.439  8410  8410 F DEBUG   :     x12  0000000000000018  x13  0000000000000000  x14  0000007040512010  x15  00000000000000ac
10-18 17:21:33.439  8410  8410 F DEBUG   :     x16  0000000000000001  x17  000000704043d4f0  x18  0000007040595000  x19  0000005c79261638
10-18 17:21:33.439  8410  8410 F DEBUG   :     x20  0000007fc596fdb8  x21  0000000000000001  x22  0000007fc596fdc8  x23  0000000000000000
10-18 17:21:33.439  8410  8410 F DEBUG   :     x24  0000000000000000  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
10-18 17:21:33.439  8410  8410 F DEBUG   :     x28  0000000000000000  x29  0000007fc596fd40  x30  0000005c79261660
10-18 17:21:33.439  8410  8410 F DEBUG   :     sp   0000007fc596fd30  pc   0000005c79261680  pstate 0000000080000000
10-18 17:21:33.441  8410  8410 F DEBUG   :
10-18 17:21:33.441  8410  8410 F DEBUG   : backtrace:
10-18 17:21:33.441  8410  8410 F DEBUG   :     #00 pc 0000000000000680  /data/data/com.termux/files/home/lse
10-18 17:21:33.441  8410  8410 F DEBUG   :     #01 pc 000000000000065c  /data/data/com.termux/files/home/lse
```

You can also use `gdb` to investigate SIGILL issue:

```
$ gdb --quiet ./lse
Reading symbols from ./lse...
(No debugging symbols found in ./lse)
(gdb) run
Starting program: /data/data/com.termux/files/home/lse
warning: Unable to determine the number of hardware watchpoints available.
warning: Unable to determine the number of hardware breakpoints available.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/data/data/com.termux/files/usr/lib/libthread_db.so".

Program received signal SIGILL, Illegal instruction.
0x0000005555556680 in __aarch64_ldadd4_acq_rel ()
(gdb) disassemble
Dump of assembler code for function __aarch64_ldadd4_acq_rel:
   0x0000005555556670 <+0>:     bti     c
   0x0000005555556674 <+4>:     adrp    x16, 0x5555558000
   0x0000005555556678 <+8>:     ldrb    w16, [x16, #2344]
   0x000000555555667c <+12>:    cbz     w16, 0x5555556688 <__aarch64_ldadd4_acq_rel+24>
=> 0x0000005555556680 <+16>:    ldaddal w0, w0, [x1]
   0x0000005555556684 <+20>:    ret
   0x0000005555556688 <+24>:    mov     w16, w0
   0x000000555555668c <+28>:    ldaxr   w0, [x1]
   0x0000005555556690 <+32>:    add     w17, w0, w16
   0x0000005555556694 <+36>:    stlxr   w15, w17, [x1]
   0x0000005555556698 <+40>:    cbnz    w15, 0x555555668c <__aarch64_ldadd4_acq_rel+28>
   0x000000555555669c <+44>:    ret
End of assembler dump.
(gdb) bt
#0  0x0000005555556680 in __aarch64_ldadd4_acq_rel ()
#1  0x0000005555556660 in main ()
(gdb)
```

**Comment by truboxl** [comment]
I cant reproduce on Android 11 aarch64... Is this Android 12 issue? Providing a logcat will be a big help in this case...

**Comment by xtkoba** [comment]
Or maybe only on relatively new SoCs. XQ-CT54 (Sony Xperia 1 IV) has Qualcomm Snapdragon 8 Gen 1.

**Comment by xtkoba** [comment]
Or maybe only with relatively new SoCs. XQ-CT54 (Sony Xperia 1 IV) has Qualcomm Snapdragon 8 Gen 1.

**Comment by radumamy** [comment]
> Or maybe only on relatively new SoCs. XQ-CT54 (Sony Xperia 1 IV) has Qualcomm Snapdragon 8 Gen 1.

Hi @xtkoba. Pleases see attached. Thank you.
[logcat.txt](https://github.com/termux/termux-packages/files/9838592/logcat.txt)

**Comment by radumamy** [comment]
I've copied a qcow2 disk from a VM in Proxmox and it boots absolutely fine. As soon as I attach the cd-rom it fails. I hope this helps. Thank you.

**Comment by xtkoba** [comment]
@radumamy Please share the output of

```bash
llvm-objdump -d --disassemble-symbols=siglongjmp /apex/com.android.runtime/lib64/bionic/libc.so
```

(You may need to install `llvm` package.)

**Comment by radumamy** [comment]
> @radumamy Please share the output of
> 
> ```shell
> llvm-objdump -d --disassemble-symbols=siglongjmp /apex/com.android.runtime/lib64/bionic/libc.so
> ```
> 
> (You may need to install `llvm` package.)

[llvm.txt](https://github.com/termux/termux-packages/files/9839527/llvm.txt)
As requested, many thanks.

**Comment by xtkoba** [comment]
```
/apex/com.android.runtime/lib64/bionic/libc.so:	file format elf64-littleaarch64

Disassembly of section .text:

000000000004daa0 <siglongjmp>:
[...]
   4dc34: d50323bf     	autiasp # <= XXX
```

**Comment by truboxl** [comment]
This makes no sense. OEM shipping `libc.so` that their CPU can't run?
Possible to provide output of `lscpu` command?

**Comment by radumamy** [comment]
> This makes no sense. ~OEM shipping `libc.so` that their CPU can't run?~ looks like Android 12 security feature... Possible to provide output of `lscpu` command?

lscpu
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 8
  On-line CPU(s) list:  0-7
Vendor ID:              ARM
  Model name:           Cortex-510
    Model:              2
    Thread(s) per core: 1
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           r0p2
    CPU(s) scaling MHz: 76%
    CPU max MHz:        1785.6000
    CPU min MHz:        307.2000
    BogoMIPS:           38.40
    Flags:              fp asimd evtstrm aes pmull sha1
                        sha2 crc32 atomics fphp asimdhp
                        cpuid asimdrdm jscvt fcma lrcpc
                        dcpop sha3 sm3 sm4 asimddp sha51
                        2 asimdfhm dit uscat ilrcpc flag
                        m ssbs sb paca pacg dcpodp flagm
                        2 frint i8mm bf16 bti
  Model name:           Cortex-710
    Model:              0
    Thread(s) per core: 1
    Core(s) per socket: 3
    Socket(s):          1
    Stepping:           r2p0
    CPU(s) scaling MHz: 53%
    CPU max MHz:        2496.0000
    CPU min MHz:        633.6000
    BogoMIPS:           38.40
    Flags:              fp asimd evtstrm aes pmull sha1
                        sha2 crc32 atomics fphp asimdhp
                        cpuid asimdrdm jscvt fcma lrcpc
                        dcpop sha3 sm3 sm4 asimddp sha51
                        2 asimdfhm dit uscat ilrcpc flag
                        m ssbs sb paca pacg dcpodp flagm
                        2 frint i8mm bf16 bti
  Model name:           -
    Model:              0
    Thread(s) per core: 1
    Core(s) per socket: 1
    Socket(s):          1
    CPU(s) scaling MHz: 43%
    CPU max MHz:        2995.2000
    CPU min MHz:        806.4000
Vulnerabilities:
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Spec store bypass:    Mitigation; Speculative Store By
                        pass disabled via prctl
  Spectre v1:           Mitigation; __user pointer sanit
                        ization
  Spectre v2:           Vulnerable: Unprivileged eBPF en
                        abled
  Srbds:                Not affected
  Tsx async abort:      Not affected

**Comment by radumamy** [comment]
> Never had issues with QEMU on my device (Pixel 5), even on Android 13 with latest security patch.
> 
> Used these commands:
> 
> ```
> qemu-img create -f qcow2 hdd.img 1G
> 
> # From top post
> qemu-system-x86_64 -name "Alpine" -M q35 -cpu qemu64 -smp 2 -m 2048 -drive file=hdd.img,if=virtio -netdev user,id=n1,hostfwd=tcp::2222-:22 -device virtio-net,netdev=n1 -cdrom alpine-virt-3.16.2-x86_64.iso -boot d -nographic
> ```
> 
> Image boots successfully and is usable without crash.
> 
> I can't identify what can be an issue there because my CPU (Snapdragon 765G) has less features than in CPU described in comment above:
> 
> ```
> fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
> ```
> 
> All of these features are mentioned in [comment](https://github.com/termux/termux-packages/issues/12261#issuecomment-1287070034).

I've created a new qcow2 disk, removed the cd-rom and the VM boots. If the cd-rom is present in the launch comand it fails. I believe others have raised the issue on Reddit
![Screenshot_20221021-162032](https://user-images.githubusercontent.com/63680669/197231711-17aa57e4-2d61-43cf-bd89-885edd4e6474.png)
![Screenshot_20221021-162453](https://user-images.githubusercontent.com/63680669/197232025-e41e9ae5-3340-4138-97c4-130148d7ca7c.png)

**Comment by radumamy** [comment]
> As I said, for me it can boot image with no issues:
> 
> ![qemu](https://user-images.githubusercontent.com/107305601/197233636-03e84078-20a0-461b-8864-3bb4850f1653.png)
> 
> I have compiled older package version (7.0.0). Try it and tell whether it works for you or not. Zip contains qemu-system-x86-64-headless and qemu-common packages. You need to install both. Delete old QEMU before installing this one.
> 
> [qemu-7.0.0-termux.zip](https://github.com/termux/termux-packages/files/9840445/qemu-7.0.0-termux.zip)

Thank you, unfortunately same problem.

**Comment by truboxl** [comment]
OK. Can you please post the output of `cat /proc/cpuinfo`? This should be the last info we need.

**Comment by truboxl** [comment]
I need to confirm it's Armv8 or something else

**Comment by radumamy** [comment]
> OK. Can you please post the output of `cat /proc/cpuinfo`? This should be the last info we need.

processor       : 0
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd46
CPU revision    : 2

processor       : 1
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd46
CPU revision    : 2

processor       : 2
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd46
CPU revision    : 2

processor       : 3
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd46
CPU revision    : 2

processor       : 4
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x2
CPU part        : 0xd47
CPU revision    : 0

processor       : 5
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x2
CPU part        : 0xd47
CPU revision    : 0

processor       : 6
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x2
CPU part        : 0xd47
CPU revision    : 0

processor       : 7
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x2
CPU part        : 0xd48
CPU revision    : 0

**Comment by truboxl** [comment]
Great thanks! This confirms 2 things:
1. It still thinks it's armv8 when it should be armv9
2. Cortex X2 is not recognised by lscpu

I am wondering whether https://github.com/android/ndk/discussions/1706 is relevant or not

**Comment by truboxl** [comment]
Possible to test these? I have no armv9 but it seems to work fine on armv8 except a bit larger
1. https://github.com/termux/termux-packages/suites/8905802041/artifacts/407700701 (pac)
2. https://github.com/termux/termux-packages/suites/8905806300/artifacts/407702845 (pac+leaf)
3. https://github.com/termux/termux-packages/suites/8905812008/artifacts/407704334 (standard)

**Comment by radumamy** [comment]
> Possible to test these? I have no armv9 but it seems to work fine on armv8 except a bit larger
> 
> 1. https://github.com/termux/termux-packages/suites/8905802041/artifacts/407700701 (pac-ret)
> 2. https://github.com/termux/termux-packages/suites/8905806300/artifacts/407702845 (pac-ret+leaf)
> 3. https://github.com/termux/termux-packages/suites/8905812008/artifacts/407704334 (standard)

Hi @truboxl. I am not sure what these are. Can you please advise how I install them. Thanks.

**Comment by truboxl** [comment]
These are generated artifacts from the CI. They are zip files. Download them and open in Termux.
`unzip the-zip-file` to extract tar file
`tar xvf the-tar-file` to extract deb files
`cd debs`
`dpkg -i qemu-common*.deb qemu-system-x86-64-headless*.deb` to install

**Comment by radumamy** [comment]
> These are generated artifacts from the CI. They are zip files. Download them and open in Termux, tap open directory. `unzip the-zip-file` to extract out tar file `tar xvf the-tar-file` to extract out deb files `cd debs` `dpkg -i qemu-common*.deb qemu-system-x86-64-headless*.deb` to install
> 
> Can comment back which option 1, 2, or 3 works?

Thanks @truboxl. Unfortunately none of the options worked. ☹️

**Comment by truboxl** [comment]
Hi @radumamy
Can you help test with this command? You will need to install `qemu-user-aarch64`. I wonder all qemu x86_64 packages for aarch64 are affected or not...
```
qemu-user-aarch64 $PREFIX/bin/qemu-system-x86_64 ...
```

**Comment by radumamy** [comment]
> 

Installed it, but it doesn't work `qemu-user-aarch64: command not found`

**Comment by radumamy** [comment]
> Hi @radumamy Can you help test with this command? You will need to install `qemu-user-aarch64`. I wonder all qemu x86_64 packages for aarch64 are affected or not...
> 
> ```
> qemu-user-aarch64 $PREFIX/bin/qemu-system-x86_64 ...
> ```

I've used `qemu-aarch64` instead. The command is accepted but no output with -nographic. If I take out -nographic, it says vnc server has started but there is no vnc display when I connect to it. 😔

**Comment by subhashisbhowmik** [comment]
> > Hi @radumamy Can you help test with this command? You will need to install `qemu-user-aarch64`. I wonder all qemu x86_64 packages for aarch64 are affected or not...
> > ```
> > qemu-user-aarch64 $PREFIX/bin/qemu-system-x86_64 ...
> > ```
> 
> I've used `qemu-aarch64` instead. The command is accepted but no output with -nographic. If I take out -nographic, it says vnc server has started but there is no vnc display when I connect to it. 😔

Same here

**Comment by xtkoba** [comment]
A possible workaround would be to provide a library something like `libandroid-setjmp` that implements `sig{set,long}jmp` without security check and to link qemu against it (or preload it).

I still do not understand where the problem sits. It could be that the jump buffer were broken within the qemu code, or that the implementation of `{pac,aut}iasp` in the SoC had some kind of bugs.

**Comment by xtkoba** [comment]
The `libandroid-setjmp` package as mentioned above: https://github.com/termux/termux-packages/actions/runs/3403306015 (PR #12914.)

**Comment by xtkoba** [comment]
And qemu binaries linked against `libandroid-setjmp`: https://github.com/termux/termux-packages/actions/runs/3403773871.

**Comment by subhashisbhowmik** [comment]
@xtkoba Can you please explain how to do that?

**Comment by xtkoba** [comment]
Do what?

**Comment by subhashisbhowmik** [comment]
I tried assembling a very basic boot sector (used nasm):
~/ostest $ cat boot.asm
jmp $

times 510-($-$$) db 0
db 0x55, 0xaa
~/ostest $ hexdump boot.bin
0000000 feeb 0000 0000 0000 0000 0000 0000 0000
0000010 0000 0000 0000 0000 0000 0000 0000 0000
*
00001f0 0000 0000 0000 0000 0000 0000 0000 aa55
0000200

~/ostest $ qemu-system-x86_64 -nographic boot.bin
SeaBIOS (version rel-1.16.0-0-gd239552ce722-prebuilt.qemu.or)


iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+07F912600



Booting from Hard Disk..Illegal instruction

**Comment by xtkoba** [comment]
Please share the output of `termux-info` if you post a "me too" comment.

BTW, I meant android-12+ is a necessary condition. I am aware that it is not a sufficient condition.

**Comment by radumamy** [comment]
> And qemu binaries linked against `libandroid-setjmp`: https://github.com/termux/termux-packages/actions/runs/3403773871.

Thank you @xtkoba. It's working after I've installed the 2 new packages. 
![Screenshot_20221113-125557](https://user-images.githubusercontent.com/63680669/201522792-98727a66-841a-4446-907a-7505b8d055b5.png)

**Comment by subhashisbhowmik** [comment]
@xtkoba 
termux-info
Termux Variables: TERMUX_API_VERSION=0.50.1+9e72088 TERMUX_APK_RELEASE=GITHUB TERMUX_APP_PACKAGE_MANAGER=apt TERMUX_APP_PID=21520 TERMUX_IS_DEBUGGABLE_BUILD=1 TERMUX_MAIN_PACKAGE_FORMAT=debian TERMUX_VERSION=0.118.0 Packages CPU architecture: aarch64 Subscribed repositories: # sources.list deb https://packages-cf.termux.dev/apt/termux-main stable main Updatable packages: All packages up to date termux-tools version: 1.31.0 Android version: 13 Kernel build information: Linux localhost 5.10.81-android12-9-25281987-abS908EXXU2BVJA #1 SMP PREEMPT Thu Oct 13 11:45:42 UTC 2022 aarch64 Android Device manufacturer: samsung Device model: SM-S908E

**Comment by subhashisbhowmik** [comment]
> A possible workaround would be to provide a library something like `libandroid-setjmp` that implements `sig{set,long}jmp` without security check and to link qemu against it (or preload it).

I'm not sure how to do this @xtkoba Can you please help?

**Comment by xtkoba** [comment]
(Sorry for the spammy reference messages.)

Do we need to make further investigation for this issue? Personally I am curious to know the root cause, but as a workaround it is sufficient to override `setjmp/longjmp`.

**Comment by radumamy** [comment]
Happy to close. Thanks.
