### ISSUE TITLE
fdsan problems with vlc

### ISSUE THREAD

**Issue by tmakarios** [termux/termux-packages#12277]
VLC will often crash when switching tracks in a playlist.  Something like this will be in the output:
```
fdsan: attempted to close file descriptor 15, expected to be unowned, actually owned by FILE* 0xblahblah
```

I can reproduce this, but it doesn't happen every time it comes to the end of a track; I don't know what the trigger is, except that it only seems to happen at the end of a track.

In case it's relevant:  I'm running VLC's http interface (started by running `vlc -I http`, with configuration of just `http-password`, `http-host`, and `http-port` in `~/.config/vlc/vlcrc` (in an `[http]` section)).  I'm adding .m3u8 playlists, which point to other .m3u8 playlists and eventually to ftp-served media files that are only accessible within my LAN.  The crash can occur regardless of whether the playlist is playing in order or shuffled.

**Comment by licy183** [comment]
We have no way for `fdsan error` on Android 11+ currently except disable it.

**Comment by licy183** [comment]
Hello @tmakarios. Please test the deb files in https://github.com/termux/termux-packages/actions/runs/3196522864. It works fine on my Android 12 device (Xiaomi MIX4).

**Comment by tmakarios** [comment]
Thanks for responding so quickly, @licy183!  I've tested the plain vlc deb for aarch64, and I can confirm that it seems to work for me; my playlist has been going for several hours now without crashing.

Thank you!
