### ISSUE TITLE
How to install Capstone?

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-packages#1227]
When installing, Capstone appearad an error ( pip install Capstone )

http://prntscr.com/g5i3b8

How to fix?

**Comment by phcoder** [comment]
Prefix your command with:
SHELL=$PREFIX/bin/sh

**Comment by Deathlive** [comment]
@phcoder 
Wrote a command `SHELL=$PREFIX/bin/sh` , later` pip2 install Capstone` → Installation error.
Replaced `pip2` on  `pip install Capstone` Installation worked, but Produces the same error.

**Comment by phcoder** [comment]
It's a single line. Not 2 lines

**Comment by Deathlive** [comment]
@phcoder 
`SHELL=$PREFIX/bin/sh pip install Capstone` Does not work.

**Comment by Deathlive** [comment]
@phcoder 
Thanks for the answer, use `CONFIG-SHELL=$REFIX/bin/sh pip install Capstone` → Mission Complete.
