### ISSUE TITLE
How to install iptables?

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-packages#1228]
How to install iptables, Or is there a substitute for this program?

**Comment by phcoder** [comment]
iptables needs root access. If you have root access there are plenty of apps to configure iptables on play store

**Comment by Deathlive** [comment]
@phcoder 
Root there is, Iptable Necessary for sslstrip, For this Command.
`iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 8080`
You think the program with the play market can it this?
