### ISSUE TITLE
[Mirror]:  New mirror addition request for termux.3san.dev/termux

### ISSUE THREAD

**Issue by Exosunandnet** [termux/termux-packages#12296]
Repository | sources.list
-- | --
Main | deb https://termux.3san.dev/termux/termux-main stable main
Root | deb https://termux.3san.dev/termux/termux-root root main
X11 | deb https://termux.3san.dev/termux/termux-x11 x11 main

Relevant information:
 - 1Gb/s
 - Mirrors are updated every 6 hours.
 - Local server: Spain
 - IPv4 only

**Comment by Grimler91** [comment]
Thank you! Would it be possible to enable a rsync interface on the server? This would allow us to keep track of the mirror status (see https://mirror.termux.dev/?mirrorstats).

A working rsync config can look something like:

```
$ cat /etc/rsyncd.conf
[termux]
  path =  /srv/termux/aptly/public/
  read only = yes
  uid = 7205
  gid = 7205
  exclude = termux-ndk-r25
```

where 7205 is the user and group id of a dedicated `rsync` user, and exclude is folders in `path` that should not be shared.

You could also password protect it by adding something like

```
auth users = username
secrets file = /var/rsyncd.secrets
```

where `/var/rsyncd.secrets` contains plaintext `username:password`

**Comment by Exosunandnet** [comment]
Sorry for the inconvenience, the rsync interface has been activated on the server.

```rsync --list-only rsync://termux.3san.dev```
 - No password required.

**Comment by Grimler91** [comment]
Thanks! Added, and updated termux-tools released so should be accessible to users shortly.

**Comment by Exosunandnet** [comment]
Uptime Bot for Termux: 
https://kuma.3san.dev/status/termux

**Comment by Grimler91** [comment]
Hi @Exosunandnet, on https://kuma.3san.dev/status/termux it looks like status is good, but it seems like mirror hasn't been updated in two days. Maybe some rsync service is disabled on the server?

**Comment by Exosunandnet** [comment]
The configuration on firewall blocked the port used for rsync synchronization, but that seems to be fixed now.
Sorry for the inconvenience

**Comment by Exosunandnet** [comment]
> Uptime Bot for Termux: https://kuma.3san.dev/status/termux

New subdomain:
- https://status.3san.dev/status/termux

**Comment by Exosunandnet** [comment]
I have checked the website to see if the server is syncing properly with the mirror, and it seems that it hasn't synchronized for the past 8 days. I manually launched a check to see if it wasn't syncing properly, but it appears that it is. Could you please look into what's happening? Sorry for the inconvenience.

https://mirror.termux.dev/?mirrorstats
