### ISSUE TITLE
[Enhance];Moon buggy sound addon

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#12294]
src https://m.seehuhn.de/programs/moon-buggy-sound-1.0.51.tar.gz
this file contains a simple patch 
home_page https://www.seehuhn.de/pages/moon-buggy

Maybe a subpkg can be added

**Comment by xtkoba** [comment]
We are sorry but no one is willing to fix this. Thanks.

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last commit in upstrean was 7 years ago so I consider this project is dead/frozen.
