### ISSUE TITLE
Can't update or install any repos 

### ISSUE THREAD

**Issue by JamesSims91** [termux/termux-packages#12295]
I'm not able to update the app or install any repos on termix can anyone help me. I'm trying to get vc code remote to work as well as Ubuntu and python.

**Comment by rallg** [comment]
Until recently, `pkg up` did it all. Now, try `pkg update` followed by `pkg upgrade` then try `pkg install (package)` again.

That may or may not help. Worth trying.

**Comment by JamesSims91** [comment]
I tried that and I received these errors:

Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://grimler.se/termux-packages-24 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B
E: The repository 'https://grimler.se/termux-packages-24 stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?)

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/issues/6726

**Comment by Suban2810** [comment]
Same here new to this
