### ISSUE TITLE
[Bug]: ncmpcpp segfaults

### ISSUE THREAD

**Issue by jpalus** [termux/termux-packages#12309]
### Problem description

After one of recent upgrades (`boost`?) `ncmpcpp` started to segfault on startup. Tried to take backtrace with `gdb` but `gdb` aborts on startup. Possibly `ncmpcpp` rebuild could fix the issue.

### What steps will reproduce the bug?

Run ncmpcpp

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=10364
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.cdn.lumito.net/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.30.2
Android version:
11
Kernel build information:
Linux localhost 4.14.212-g718eb2fa3c24 #1 SMP PREEMPT Thu Apr 14 16:04:57 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 4a
```

**Comment by Grimler91** [comment]
Please check if it works with ncmpcpp 0.9.2-4

**Comment by jpalus** [comment]
@Grimler91 unfortunately not, but I've managed to figure it's actually due to `readline` upgrade combined with wrong locale on my side which first patchset for `readline 8.2` should fix: https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001 (as a workaround setting `LC_CTYPE=C` for `ncmpcpp` works fine).

**Comment by jpalus** [comment]
Side note: it's also the reason why `gdb` aborts.

**Comment by Grimler91** [comment]
What did you have LC_CTYPE set to before?

**Comment by jpalus** [comment]
`LC_CTYPE=pl_PL.UTF-8` that comes from my shell configuration shared between multiple environments, which by itself is valid locale, but I guess I don't have locale data installed in my `termux` setup.
