### ISSUE TITLE
Auto update failing for termux-gui-bash

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#12300]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the termux-gui-bash package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating termux-gui-bash [Current version: 0.1.0]
ERROR: No 'latest-release-tag' found (https://api.github.com/repos/tareksander/termux-gui-bash/releases/latest).
Try using 'newest-tag'.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2022-10-08 19:18:50 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/3211301571">3211301571</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by truboxl** [comment]
@tareksander 
Please use Releases or a new tag on upstream. Otherwise disable the auto update.
