### ISSUE TITLE
Termux-api 

### ISSUE THREAD

**Issue by seifubeach** [termux/termux-packages#12316]
I installed termux api but when I run the command pkg install termux-api it says: Package termux-api is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'termux-api' has no installation candidate

**Comment by seifubeach** [comment]
> Try running this:
> 
> ```
> pkg update
> yes | pkg upgrade
> pkg install termux-api
> ```

Didn't work

**Comment by VARUNSINCE2001** [comment]
E: Package 'termux-api' has no installation candidate
$

**Comment by vXtreniusX** [comment]
Can you try running `termux-info` and pasting the output here?

**Comment by alaCa21** [comment]
Tes
