### ISSUE TITLE
[Bug]: The Emacs package is different from the standard

### ISSUE THREAD

**Issue by drcxd** [termux/termux-packages#12327]
### Problem description

I installed Emacs package and found that my configuration code triggers some error with it. It turns out that the provided Emacs is different from a standard one to some extent. For example, the provided Emacs does not define function `set-fontset-font` which is a built-in function in Emacs' C code. There are also some other undefined variables.

Is this difference intentional or it is just a bug? I tried to build Emacs from source code but failed because it requires selinux.h which is not present in the system. I can't install selinux development library from apt. I browsed the wiki but find no instructions about how to build software on your own. Could you give me some pointers?

I also tried nix-on-droid which is based on termux. The Emacs provided by them is identical to standard ones, thus I think it is possible to bring Emacs untouched to termux as well. However, Emacs on nix-on-droid is really slow, but it runs fast on termux, so I prefer using it in termux.

### What steps will reproduce the bug?

1.  Install termux
2.  `apt install emacs`
3.  Launch emacs and `C-h f` to ask for help about functions
4.  type `set-fontset-font` and found no such function. However, this function is described in the emacs manual https://www.gnu.org/software/emacs/manual/html_node/emacs/Modifying-Fontsets.html

### What is the expected behavior?

The Emacs package provided should be identical to Emacs on other platforms.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5223
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# source.list
deb https://packages.termux.dev/apt/termux-main/ stablemain
Updatable packages:
readline/stable 8.2.1 aarch64 [upgradable from: 8.2.0]
termux-tools version:
1.30.2
Android version:
12
Kernel build information:
Linux localhost 5.10.66-android12-9-00001-g41ff3fa8fff9-ab8171928 #1 SMP PREEMPT Mon Feb 7 06:19:48 UTC 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
22041216C
```

**Comment by Grimler91** [comment]
There is no "standard" emacs package, emacs has something like 60 configure options so there's plenty of ways for distros to configure their package in different ways. [Termux/android is also different from Linux](https://wiki.termux.com/wiki/Differences_from_Linux) so it is impossible to make identical packages for termux and other linux distros.

That being said, it seems `set-fontset-font` require x11 or gtk, which our main emacs package are compiled without.  If you install emacs-x instead then `C-h f set-fontset-font` works (but I don't know if the function *actually* works, in the absence of a GUI).

> I tried to build Emacs from source code but failed because it requires selinux.h which is not present in the system. I can't install selinux development library from apt. I browsed the wiki but find no instructions about how to build software on your own. Could you give me some pointers?

See [Building-packages](https://github.com/termux/termux-packages/wiki/Building-packages) for how to build packages for termux. Our build recipe for emacs, with the config options we use, are in [packages/emacs/build.sh](https://github.com/termux/termux-packages/blob/master/packages/emacs/build.sh), and all the patches in [packages/emacs/](https://github.com/termux/termux-packages/blob/master/packages/emacs/).

---

You mentioned undefined variables as well, please provide more details if you think this is another bug.

**Comment by Grimler91** [comment]
`mouse-wheel-mode` behaviour miiight have to do with our custom [site-start.el](https://github.com/termux/termux-packages/blob/master/packages/emacs/site-start.el#L2-L4), which was added to [allow for scrolling on a touchscreen](https://github.com/termux/termux-packages/commit/0d25a03f1129c0949f0d7d3ab6dd98651d802b4a). Are you planning to use emacs with a hardware mouse instead of using the touch screen? In that case you might want to remove those site-start.el defintions

**Comment by drcxd** [comment]
I do not plan to use a hardware mouse, however, one package I used contains some code involving those variables.

I tried to comment out all the code in `usr/share/emacs/site-lisp/site-start.el` but it does not change the behavior.
