### ISSUE TITLE
[Bug]: [][03:35 AM] []EsGeeks@Termux:~ $ []

### ISSUE THREAD

**Issue by Retocraft141** [termux/termux-packages#12355]
### Problem description

I want to know how to fix the problem

### What steps will reproduce the bug?

r][03:45 AM] []EsGeeks@Termux:~ $ []nh -
┌──(root㉿localhost)-[~]
└─# kex
vncserver: No matching VNC server running for this user!
vncserver: No matching VNC server running for this user!

NetHunter KeX server sessions:

X DISPLAY #     RFB PORT #      RFB UNIX PATH   PROCESS ID #SERVER
2               5902                            26694       Xtigervnc
5               5905                            27991 (stale)Xtigervnc

You can use the KeX client to connect to any of these displays.

┌──(root㉿localhost)-[~]
└─#
[Process completed (signal 9) - press Enter

### System information

termux-info:

```

``
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=28800
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.30.2
Android version:
12
Kernel build information:
Linux localhost 4.14.190-23725627-abG975U1UEU6IVH1 #2 SMP PREEMPT Mon Aug 1 22:28:57 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G975U1

**Comment by Retocraft141** [comment]
What is the expected behavior?

**Comment by Grimler91** [comment]
See "NOTICE: Termux is broken on Android 12" section in [README](https://github.com/termux/termux-app/blob/master/README.md)
