### ISSUE TITLE
[Package]: e4defrag in  e2fsprogs

### ISSUE THREAD

**Issue by arch-user-france1** [termux/termux-packages#12361]
### Why do you want to add this package to Termux?

It does defragmentation

### Source code URL

not sure

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

It could be used to check fragmentation status of the device's storage.

**Comment by 2096779623** [comment]
`e2fsprogs` is already in our repository.
https://github.com/termux/termux-packages/blob/master/packages/e2fsprogs/build.sh

**Comment by arch-user-france1** [comment]
Would you enable it or can I just clone the repository and build it myself?

**Comment by arch-user-france1** [comment]
So it won't work on arm, do I understand that correct?

**Comment by arch-user-france1** [comment]
> Build issues on all architectures because NDK lacks certain definitions in compiler headers.

Is there a prebuilt version for Arm?

**Comment by arch-user-france1** [comment]
> I've literally said it can't be built for all architectures using NDK as of now: aarch64, **arm**, i686, x86_64.
> 
> Wait until someone patches e2fsprogs source to fix the issue.

I meant, is there an older version for arm prebuilt?
Ubuntu has e4defrag preinstalled, couldn't I copy some precompiled older version to /bin?

**Comment by arch-user-france1** [comment]
Alright, thanks. I understand that this package cannot be added because of broken code but I could use something like Andronix.

**Comment by arch-user-france1** [comment]
Alright, thanks. I understand that this package cannot be added because of broken code but I could use something like Andronix.
