### ISSUE TITLE
Brew-like versioning with @?

### ISSUE THREAD

**Issue by vaites** [termux/termux-packages#1239]
[Homebrew](https://brew.sh) uses @ to make different versions of the same package, instead naming it. An example could be _nodejs_ and _node-current_, marked as _nodejs@6_ and _nodejs_ respectively. 

Using this convention we can have node@4, node@6 and the latest stable without versioning. The same for PHP with php@5 and many others...

**Comment by fornwall** [comment]
I think it sounds like a good convention in general!

For the nodejs case I'm not so sure we should have fixed version numbers in the package names - the current plan is to have the `nodejs` being the stable/LTS version that most users want and have `nodejs-current` track the current version, regardless of version number.

**Comment by vaites** [comment]
Ok, is just an idea. There are many conventions (Debian appends version numbers) but this seems the lest confusing for the users.

**Comment by fornwall** [comment]
Right, let's do it in the future for packages with multiple versions (for example, something like python2/python3)!

**Comment by vaites** [comment]
Great, Thank you for always being open to suggestions.
