### ISSUE TITLE
Strange vibration issue with Emacs

### ISSUE THREAD

**Issue by nyuszika7h** [termux/termux-packages#124]
If I start Emacs in portait mode, my phone starts vibrating non-stop until I quit Termux, and I only see some dashes on the screen. This does not happuen in landscape mode, which makes me wonder if it has anything to do with the terminal size being too small.

Details that may be relevant:

* Device: Nexus 5
* OS: CyanogenMod 13.0 (hammerheadcaf) 2016-01-10
* Font: FiraCode

<small>(Note: I'm a vim user, I just wanted to try something ;)</small>

**Comment by fornwall** [comment]
Yes, emacs unfortunately seems to hang/crash with a less than 72 column wide terminal - tracked in issue https://github.com/termux/termux-packages/issues/11 (will ask for help by emacs developers).
