### ISSUE TITLE
[Bug]: postgresql 15

### ISSUE THREAD

**Issue by pi3c** [termux/termux-packages#12413]
### Problem description

Can't install postgresql 15.
`~ $ apt install postgresql
Reading package lists... Done
Building dependency tree... Done                           Reading state information... Done
The following additional packages will be installed:
  libandroid-shmem libicu
The following NEW packages will be installed:
  libandroid-shmem libicu postgresql
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/15.0 MB of archives.
After this operation, 68.3 MB of additional disk space will be used.                                                  Do you want to continue? [Y/n] y
Selecting previously unselected package libandroid-shmem.
(Reading database ... 21537 files and directories currently installed.)
Preparing to unpack .../libandroid-shmem_0.4_aarch64.deb ...
Unpacking libandroid-shmem (0.4) ...
Selecting previously unselected package libicu.
Preparing to unpack .../libicu_71.1-1_aarch64.deb ...
Unpacking libicu (71.1-1) ...
Selecting previously unselected package postgresql.
Preparing to unpack .../postgresql_15.0_aarch64.deb ...    Unpacking postgresql (15.0) ...
Setting up libandroid-shmem (0.4) ...
Setting up libicu (71.1-1) ...
Setting up postgresql (15.0) ...                           ~ $ mkdir -p $PREFIX/var/lib/postgresql//
~ $ initdb $PREFIX/var/lib/postgresql
The files belonging to this database system will be owned by user "u0_a293".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /data/data/com.termux/files/usr/var/lib/postgresql ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... sysv
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... W-SU
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start

~ $ pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start
waiting for server to start.... done
server started
~ $ createuser --superuser --pwprompt postgresql           Enter password for new role:
Enter it again:
createuser: error: connection to server on socket "/data/data/com.termux/files/usr/tmp/.s.PGSQL.5432" failed: FATAL:  could not map shared memory segment "1735480196": Invalid argument
~ $'

### What steps will reproduce the bug?

apt update&& apt upgrade
Before this posgresql(previous ver) works fine

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7748
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# root-repo (sources.list.d/root.list)                     deb https://packages.termux.dev/apt/termux-root root stableUpdatable packages:
All packages up to date
termux-tools version:
1.30.2
Android version:                                           12
Kernel build information:
Linux localhost 4.19.157-chime #1 SMP PREEMPT Wed Aug 17 08:45:07 CEST 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:                                              M2010J19SY
```

**Comment by qc477** [comment]
> In your `postgresql.conf` file change the value of `dynamic_shared_memory_type` from `sysv` to `mmap`

Thanks! Your advice helped solve this problem.
