### ISSUE TITLE
[Bug]: rsync version 3.2.6 throws error when using --files-from over ssh

### ISSUE THREAD

**Issue by txoof** [termux/termux-packages#12419]
### Problem description

Including `--files-from=files.foo` arg causes rsync to throw the following error:
```
ERROR: rejecting unrequested file-list name: Music/Rock/Avett Brothers
rsync error: protocol incompatibility (code 2) at flist.c(998) [Receiver=3.2.6]
```

This appears to be related to a [bug introduced recently](https://github.com/WayneD/rsync/issues/376). The latest version provided in the termux archive appears to include this bug. The latest version of rsync was last updated on 2022.09.09 at [rsync.samba.org](https://rsync.samba.org/ftp/rsync/src/) and includes the current issue.

Apologies if this is the wrong place to file this report. 

### What steps will reproduce the bug?

rsync files over an ssh connection using `--files-from=foo.txt`

```
rsync --files-from=./rsync.list --size-only --no-times -v -P -r --delete-excluded -e "ssh -p 22 -i ~/.ssh/id_rsa" user@host:/ ./music
```

rsync.list contains:
```
Music/Rock/Athenaeum/Athenaeum - Radiance - 01 - What I Didn't Know.mp3
Music/Rock/Athenaeum/Athenaeum - Radiance - 03 - On My Mind.mp3
Music/Rock/Avett Brothers/The Avett Brothers - Four Thieves Gone - The Robbinsville Sessions - 01 - Talk On Indolence.mp3
Music/Rock/Avett Brothers/The Avett Brothers - Four Thieves Gone - The Robbinsville Sessions - 04 - Distraction #74.mp3
```

result:
```
receiving file list ...
ERROR: rejecting unrequested file-list name: Music/Rock/Avett Brothers
rsync error: protocol incompatibility (code 2) at flist.c(998) [Receiver=3.2.6]
```

### What is the expected behavior?

rsync should sync the files with no error.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.cbrx.io/apt/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.30.2
Android version:
13
Kernel build information:
Linux localhost 5.10.107-android13-4-00004-g6522bf85d262-ab8935228 #1 SMP PREEMPT Thu Aug 11 01:17:17 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 7 Pro
```

**Comment by txoof** [comment]
@xtkoba , I'm genuinely surprised how quickly you all handled this bug report! It's pretty fantastic!

I'm curious to understand the process. What happens now? How does your back port make it into the repo mirrors? What happens when a newer official samba version emerges? Is there some trigger that helps you all remember to move back to the official release channel?

Thanks again!

**Comment by Grimler91** [comment]
And thanks for the bug report!

**Comment by txoof** [comment]
Thanks for the insight into the process. Cool to see that everything is happening within GitHub.

How long do the changes typically take to propagate out to the mirrors after the packages are built?

**Comment by Grimler91** [comment]
> How long do the changes typically take to propagate out to the mirrors after the packages are built?

Around 3 - 24 h, different mirrors sync with different intervals. Status of some (but not yet all) mirrors can be seen at:
https://mirror.termux.dev/?mirrorstats

**Comment by txoof** [comment]
@Grimler91 Thanks so much for all the information. I find this super fascinating. Thanks @xtkoba and the rest of the team for patching this bug so quickly. I thought my project was going to be hoopajup'd by this bug. I've got an updated rsync and I'm ready to get to fixing.
