### ISSUE TITLE
Kali Linux Chroot

### ISSUE THREAD

**Issue by cr4shcod3** [termux/termux-packages#1243]
Ive already tried and installed Fedora 25 and 26 and Ubuntu 17. I want to know if you can also provide us Kali Linux, Backbox, ParrotSec OS or any Distro that is for Pentesting. I want it so badly :'(. Maybe some of people hete too :).

**Comment by vishalbiswas** [comment]
chroot'd linux are not officially provided. They are created by community members. Termux aims to be a prefixed environment.
Most tools in Kali linux will require you to grant them superuser rights. In that case, Linux Deploy would be a better option.
Tools that don't require root will be scripts, mostly. These can be easily installed manually as termux already has all major interpreters available.
