### ISSUE TITLE
Kali Rolling aarch64 for termux please :)

### ISSUE THREAD

**Issue by cr4shcod3** [termux/termux-packages#1244]
![screenshot_20170810-132337](https://user-images.githubusercontent.com/26832583/29162480-29865606-7dec-11e7-950b-dbc2b1d0c7af.png)
![screenshot_20170810-151227](https://user-images.githubusercontent.com/26832583/29162492-33c60c6a-7dec-11e7-8fa6-f50cb9401fea.png)
![screenshot_20170810-133014](https://user-images.githubusercontent.com/26832583/29162498-3991fcf8-7dec-11e7-9756-310cdd6a8668.png)
I installed successfully the Kali Linux on my android without root. The problem is I only have the arm64 of the environment. My architecture is aarch64. Can someone help me to install this? I'm having an error in installing package in the Kali Linux environment. Error always occur. I think it is because of my architecture aarch64 while I installed the arm64

**Comment by shubhradas** [comment]
USE:-
./start.sh
