### ISSUE TITLE
busybox less segfaults on 32-bit arm

### ISSUE THREAD

**Issue by suryapoo** [termux/termux-packages#1245]
$ cd /sdcard
$ less hit.txt

[1]+  Stopped                 less hit.txt
$ ls
Alarms         Movies         Ringtones
Android        Music          WhatsApp
DCIM           Notifications  hit.txt
Download       Pictures
Foxit          Podcasts
[1]+  Segmentation fault      less hit.txt

I'm on a nexus 5..Android version ..6.0.1 ..

**Comment by vishalbiswas** [comment]
how big is hit.txt?

**Comment by sdrausty** [comment]
@suryapoo Did you `apt update & apt upgrade` to try to fix it?

**Comment by suryapoo** [comment]
@vishalbiswas ..it contains just one line of text..

**Comment by suryapoo** [comment]
@sdrausty ..yes I did..

**Comment by sdrausty** [comment]
@vishalbiswas 
```
$ l file
-rw------- 1 u0_a93 u0_a93 10485760 Aug  1 12:55 file
$ less file
```

**Comment by sdrausty** [comment]
@suryapoo What is your architecture? `uname -a`

**Comment by suryapoo** [comment]
Linux localhost 3.4.0-g7717f76 #1 SMP PREEMPT Wed Nov 4 21:42:24 UTC 2015 armv7l Android

**Comment by fornwall** [comment]
Seems to be busybox less on 32-bit arm that segfaults.

**Comment by fornwall** [comment]
@suryapoo Thanks for reporting! This has now been fixed, run `pkg update` to install the latest version of busybox which fixes this problem.

**Comment by suryapoo** [comment]
Thanks a lot ..@fornwall
