### ISSUE TITLE
[Bug]: cmake: Weird directory structure

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#12465]
### Problem description

Binary package of `cmake` contains directory `$PREFIX/doc` which I believe is unintentional:

```
$ ar x cmake_3.24.2_aarch64.deb data.tar.xz && tar tf data.tar.xz | grep '^\.'${PREFIX//./\\.}/doc
./data/data/com.termux/files/usr/doc/
./data/data/com.termux/files/usr/doc/cmake-3.24/
./data/data/com.termux/files/usr/doc/cmake-3.24/cmsys/
./data/data/com.termux/files/usr/doc/cmake-3.24/cmsys/Copyright.txt
./data/data/com.termux/files/usr/doc/cmake-3.24/Copyright.txt
```

### What steps will reproduce the bug?

```bash
pkg install cmake
```

and see the directory structure under `$PREFIX`.

### What is the expected behavior?

`$PREFIX/doc` should be replaced with `$PREFIX/share/doc`.

### System information

Irrelevant.

**Comment by thunder-coding** [comment]
I guess this directory structure is intentional by the CMake team. As you noted that most distributions have those files in `$PREFIX/share/doc`, so there's no harm in moving them there.
