### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DilkhushBhati** [termux/termux-packages#12462]
### Problem description

![Screenshot_20221018-185039](https://user-images.githubusercontent.com/54091092/197193241-d8f0d381-6c47-4261-bdfa-9fc9fd202104.png)
After installing maridb in my termux ,when I run cmd mysqld it shows that libssl.so.3 not found
You can see that in SS ,
 

### What steps will reproduce the bug?

![Screenshot_20221018-185039](https://user-images.githubusercontent.com/54091092/197193887-8bd76e75-0188-4a57-aef9-7d3be7e6e53d.png)

### System information

termux-info:

```
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #2 SMP PREEMPT Tue Jul 20 20:16:01 CST 2021 aarch64 Android
Device manufacturer:
motorola
Device model:
moto e(6s)
```

**Comment by DilkhushBhati** [comment]
I also try by reinstall termux again

**Comment by xtkoba** [comment]
Do `pkg up`.

**Comment by DilkhushBhati** [comment]
Noe it's shows that ,repository is under maintenance or down . See below
for details.

$ pkg upgrade
Checking availability of current mirror: ok
Hit:1 https://termux.mentality.rip/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  502 Bad Gateway
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  502 Bad Gateway
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games
Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong
sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24
science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong
sources.list URL?).
