### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Vixiii666** [termux/termux-packages#12486]
### Problem description

Having a error when installing jishaku

### What steps will reproduce the bug?

pip install jishaku

### What is the expected behavior?

Installs without any error 

### System information

termux-info:

```
V = 0.118.0
Yes, i installed it from f droid
Android 11

```
![IMG_20221022_133857](https://user-images.githubusercontent.com/116427832/197328640-1320ada9-3cc8-49e4-ae39-587a41d19794.jpg)

**Comment by Vixiii666** [comment]
Accidentally clicked on close...

**Comment by xtkoba** [comment]
Try:

```bash
pip install discord scikit-build
pip install --no-use-pep517 jishaku
```

**Comment by Vixiii666** [comment]
![Uploading Screenshot_20221024_014945.jpg…]()

**Comment by Vixiii666** [comment]
![IMG_20221024_015014](https://user-images.githubusercontent.com/116427832/197416458-eadf655b-2182-43fc-8a61-05b237791eb6.jpg)

**Comment by Vixiii666** [comment]
You're my last hope now

**Comment by xtkoba** [comment]
```bash
pip install Cython
```

**Comment by Vixiii666** [comment]
Nvm, i just installed the developmental version, and it works fine! Thanks anyways
