### ISSUE TITLE
Package Request: POCO

### ISSUE THREAD

**Issue by azaka** [termux/termux-packages#1249]
[https://pocoproject.org/](url)

**Comment by its-pointless** [comment]
yeah i added this #1408 . You could do some testing since i have this added this to my repo etc. Should be relatively fine.

**Comment by azaka** [comment]
Hi

I managed to install poco by merging the libpoco branch into my local repo and then building under Docker

$ dpkg -i libpoco_1.pre-cpp11-0_aarch64.deb                   
Selecting previously unselected package libpoco.           
 (Reading database ... 19236 files and directories currently installed.)                                                 Preparing to unpack libpoco_1.pre-cpp11-0_aarch64.deb ...   
Unpacking libpoco (1.pre-cpp11-0) ...                       
Setting up libpoco (1.pre-cpp11-0) ...                      
$ dpkg -l|grep poco                                         
ii  libpoco        1.pre-cpp11- aarch64      C++ Portable Components (POCO)

Thank you for making the port.
