### ISSUE TITLE
[Bug]: libusb error

### ISSUE THREAD

**Issue by youssefnone** [termux/termux-packages#12494]
### Problem description

i have problem on libusb
error: ERROR: Failed to initialise libusb. libusb error: -1

### What steps will reproduce the bug?

after using termux-usb 
i use the cmd termux-usb -e ./hi.sh /dev/bus/usb/001/011 then i got the problem
hi.sh contains: heimdall detect i try to flash recovery on samsung phone using heimdall + termux-usb over otg

### System information

termux-info:

```Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=16698
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.dev/apt/termux-root root stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
clang/stable 15.0.3 arm [upgradable from: 15.0.2]
cmake/stable 3.24.2-1 arm [upgradable from: 3.24.2]
libcompiler-rt/stable 15.0.3 arm [upgradable from: 15.0.2]
libllvm/stable 15.0.3 arm [upgradable from: 15.0.2]
lld/stable 15.0.3 arm [upgradable from: 15.0.2]
llvm/stable 15.0.3 arm [upgradable from: 15.0.2]
termux-tools/stable 1.31.0 all [upgradable from: 1.30.2]
termux-tools version:
1.30.2
Android version:
10
Kernel build information:
Linux localhost 3.18.140-21947068 #1 SMP PREEMPT Wed Jan 12 20:26:43 KST 2022 armv8l Android
Device manufacturer:
samsung
Device model:
SM-M105G


```

**Comment by Grimler91** [comment]
You haven't specified what heimdall you are trying to run, but I guess error is due to the fact that on android programs that use libusb need to set `LIBUSB_OPTION_NO_DEVICE_DISCOVERY`. Heimdall needs additional patches to work on android in any case, it uses `libusb_get_device_list` which gets devices by parsing `/sys`, which won't work on android without root. 

See also the heimdall package request: https://github.com/termux/termux-packages/issues/10437

**Comment by youssefnone** [comment]
> You haven't specified what heimdall you are trying to run, but I guess error is due to the fact that on android programs that use libusb need to set `LIBUSB_OPTION_NO_DEVICE_DISCOVERY`. Heimdall needs additional patches to work on android in any case, it uses `libusb_get_device_list` which gets devices by parsing `/sys`, which won't work on android without root.
> 
> See also the heimdall package request: #10437
i build and ran your heimdall 
then heimdall must runned on rooted device

**Comment by Grimler91** [comment]
Yes, termux-api/termux-usb doesn't provide any way to list devices yet, so only way is with root for now

**Comment by youssefnone** [comment]
> Yes, termux-api/termux-usb doesn't provide any way to list devices yet, so only way is with root for now

sad
