### ISSUE TITLE
How to add  sh script in bin/sh without $PREFIX/bin/sh.

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-packages#1250]
i want to install a `capstone`,

http://prntscr.com/g6wv66  → ERROR
http://prntscr.com/g6wvim  → ERROR

WHAT IS THE PROBLEM?
How to make pip know where to be `sh` script

**Comment by fornwall** [comment]
Try `CONFIG_SHELL=$PREFIX/bin/sh pip install Capstone` as mentioned in https://github.com/termux/termux-packages/issues/1227.
