### ISSUE TITLE
tmp-mksh: python: not found

### ISSUE THREAD

**Issue by thenickvendetta** [termux/termux-packages#1251]
cd set
$ python setup.py install
Are you root? Please execute as root
$ su
python setup.py install                           <
tmp-mksh: python: not found

**Comment by Neo-Oli** [comment]
What are you trying to install?
You shouldn't need root to install something with python.

**Comment by fornwall** [comment]
I would guess the message about root is from here: https://github.com/trustedsec/social-engineer-toolkit/blob/master/setup.py#L18

Closing this in favour of https://github.com/termux/termux-packages/issues/980 - see that issue @thenickvendetta.
