### ISSUE TITLE
[Package]: mp3cat combine mutliple mp3

### ISSUE THREAD

**Issue by OilSubjectLoss7** [termux/termux-packages#12527]
### Why do you want to add this package to Termux?

very useful

### Home page URL

https://github.com/dmulholl/mp3cat

### Source code URL

https://github.com/dmulholl/mp3cat

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by snooppr** [comment]
> [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Not serving duplicated functionality


Hello. You can merge audio files with ffmpeg:
```
cd storage/downloads/audio/
printf "file '%s'\n" *.mp3 > allname.txt
ffmpeg -f concat -safe 0 -i allname.txt -c copy all.mp3
```
You can replace .mp3 with .wav and it will work just as fast.
