### ISSUE TITLE
Garbage Onscreen in Weechat

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1252]
Garbage onscreen in weechat is very annoying making weechat close to useless, or probably even worse than useless - by misleading through garballing messages, and rearranging systemwide font size in every open session if trying to simply correct garbage onscreen through resorting to pinching the screen to refresh weechat. This was not the case a while ago. The screen looked beautiful, and did not flicker as much as it does now, too; Flickering away, refreshing over and over again before it finally settles down with garbage onscreen!

Termux-packages arch:
aarch64
Android version:
6.0.1

Simple bash then weechat:
![screenshot_20170811-104312](https://user-images.githubusercontent.com/27742457/29218191-f84cd470-7e81-11e7-952c-d2b06b6e3db5.png)
![screenshot_20170811-120806](https://user-images.githubusercontent.com/27742457/29221737-d7136402-7e8d-11e7-804d-d0c707b79046.png)

ssh localhost authentication, then weechat:
```
Welcome to Termux!

Online help:     https://termux.com/help
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ sshd -p 9999
$ ssh localhost -p 9999
Permission denied (publickey,keyboard-interactive).
$ ps aux |grep ssh
u0_a93   27899  0.0  0.0   5700   792 ?        Ss   13:01   0:00 sshd -p 9999
u0_a93   27937  0.0  0.0   3520   980 pts/3    S+   13:01   0:00 grep ssh
$ ssh
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-J [user@]host[:port]] [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port] [-Q query_option] [-R address]
           [-S ctl_path] [-W host:port] [-w local_tun[:remote_tun]]
           [user@]hostname [command]
$ ssh -p 9999 localhost
Permission denied (publickey,keyboard-interactive).
$ rf .ssh/
$ ssh -p 9999 localhost
The authenticity of host '[localhost]:9999 ([127.0.0.1]:9999)' can't be established.
ECDSA key fingerprint is SHA256:AjSeLNogkMIJITtocEY9au5KE3UQK/8y23wro5gMCxI.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[localhost]:9999' (ECDSA) to the list of known hosts.
Permission denied (publickey,keyboard-interactive).
$ weechat
```

![screenshot_20170811-121606](https://user-images.githubusercontent.com/27742457/29222049-e33be578-7e8e-11e7-9e7d-739623330a88.png)

Garbage onscreen in both scenarios, but with less flickering (fewer screen refreshes) in ssh.

**Comment by fornwall** [comment]
It seems that [the recent ncurses update for 2017-07-29](http://invisible-island.net/ncurses/NEWS.html#t20170729) starts to use the following escape sequence (from http://invisible-island.net/xterm/ctlseqs/ctlseqs.txt):

    CSI Ps b  Repeat the preceding graphic character Ps times (REP).

This is not currently handled in the Termux terminal emulator, but should be easy to add.

**Comment by fornwall** [comment]
Thanks for reporting! This is now fixed in version `6.0.20170812` of the ncurses package which is available as an update.

**Comment by sdrausty** [comment]
Thank you for the quick fix/update, much less flickering (screen refreshing) too🙂

**Comment by sdrausty** [comment]
@fornwall Can you reopen this issue please? This garbage came onscreen after swiping back to Extra Keys View from Text Input View in weechat on Termux. Also, at times, the number of screen refreshes (flickering) is excessive in weechat on Termux too. 

![screenshot_20170815-100718](https://user-images.githubusercontent.com/27742457/29319470-2c5295a2-81a2-11e7-923b-5799e0515d27.png)

**Comment by Neo-Oli** [comment]
Yeah. I also notice garbage in several other programs including ncmpcpp (visualizer) and mutt.

**Comment by fornwall** [comment]
@Neo-Oli Do you need to resize the screen to see that garbage (possibly by toggling keyboard visibility) or does it happen directly?

**Comment by Neo-Oli** [comment]
@fornwall No. It happens even without that. I tried it with a MinTTY terminal (via SSH and tmux) connected directly comparing the two outputs. The MinTTY one looked fine, but it became more and more garbaged on Device. I was testing ncmpcpp visualizer in this instance. It becomes garbaged the most consistently and fastest.

**Comment by fornwall** [comment]
@Neo-Oli The ncmpcpp visualizer should be a good test case!

Unfortunately I'm not able to see the problem directly following a guide at https://wiki.archlinux.org/index.php/ncmpcpp, with `~/.ncmpcpp/config` being:

```visualizer_fifo_path = "/data/data/com.termux/files/usr/tmp/mpd.fifo"
visualizer_output_name = "my_fifo"
visualizer_sync_interval = "30" 
visualizer_in_stereo = "yes"
visualizer_type = "spectrum"
visualizer_look = "+|"
```

Could you share necessary ncmpp configuration/setup? This is my first time using ncmpcpp, seems nice!

**Comment by sdrausty** [comment]
I have notice that if you press the power button on Android and then reactivate the screen, you do not have to resize the screen to alleviate it of screen garbage.

**Comment by Neo-Oli** [comment]
@fornwall Here's my mpd and ncmpcpp config: https://gist.github.com/Neo-Oli/3b6ef6c38c8ff032542888b08175ef70. You'll probably only need to edit `music_directory`.

By the way, you probably only needed to enable the visualizer output in `7` in ncmpcpp to make the visualizer in  `8` work. With my config it is enabled by default.

**Comment by fornwall** [comment]
@Neo-Oli @sdrausty Does this work better for you with the latest ncurses package (version 6.0.20170909)?

For me weechat works a lot better when resizing (but I haven't managed to reproduce the problem with the ncmpcpp visualizer).

**Comment by sdrausty** [comment]
@fornwal weechat works much better. Thank you!

Garbage seems gone. Is there anything that can be done about the refreshes weechat does, before settling down? Unlike weechat, emacs erc is steady as a rock.

**Comment by sdrausty** [comment]
Garbage is gone! Thank you! So this issue can be closed afaic☺

**Comment by sdrausty** [comment]
Weechat reboots Android 6 aarch64: 🌟 starts beautifully, logs in well...  Can tlk 2

`/nick` upsets it REBOOT stock

```
$ps aux |grep weechat
$kill weechatPID``` REBOOT WOW 😂

Needless to say:
https://sdrausty.github.io/pages/more
https://sdrausty.github.io/logs/ircFreenodeTermuxWeechatlog
Are not being updated at present because of this and other issues.

**Comment by Neo-Oli** [comment]
@sdrausty This is very likely the same issue as https://github.com/termux/termux-app/issues/129. Can you post it there. Also it would be interessting to know what model of phone you have.

**Comment by sdrausty** [comment]
The one that reboots is ZTE Z981

**Comment by sdrausty** [comment]
This is low level programming gone array.
