### ISSUE TITLE
[Bug]: Tmux horizontal split panel messed up when using Zsh

### ISSUE THREAD

**Issue by pseudoparenchymatous** [termux/termux-packages#12556]
### Problem description

Tmux is bugging with the colors
https://imgur.com/a/3JirVAx

### What steps will reproduce the bug?

Run tmux with certain colorschemes

### What is the expected behavior?

Display the shell/terminal color similar non-tmux

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=3914
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
11
Kernel build information:
Linux localhost 4.14.190-perf-gceaf914a4ae1-dirty #2 SMP PREEMPT Wed Feb 16 22:34:35 WIB 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8
```

**Comment by agnostic-apollo** [comment]
Check if https://github.com/termux/termux-app/issues/3036#issuecomment-1273430688 is the issue.

**Comment by pseudoparenchymatous** [comment]
> Check if [termux/termux-app#3036 (comment)](https://github.com/termux/termux-app/issues/3036#issuecomment-1273430688) is the issue.

I tried disabling the per app dark mode but it's still the same. Apparently this bug only happens if I make a pane to the right (horizontal split).

**Comment by pseudoparenchymatous** [comment]
> Looks like more a shell prompt formatting issue.
> 
> Can't reproduce the issue. ![Screenshot_20221026-224207](https://user-images.githubusercontent.com/107305601/198121382-ee54a180-c8fd-43d0-98f7-2c8cdaae68de.png)

How does yours look like if you do this (try light themes)?


https://user-images.githubusercontent.com/105337186/198132618-9933fe22-e534-4115-8914-eafadc76a632.mp4

**Comment by pseudoparenchymatous** [comment]
You're right, zsh is breaking this (even running `zsh - f`). Should I change this to zsh bug instead of tmux?

**Comment by xtkoba** [comment]
I don't really get the point of this issue. Couldn't it be that this is poking a bug of Termux app? In other words, is this reproducible with other terminals, e.g. `xfce4-terminal` in X11 environment, or any terminal in GNU/Linux environment which Termux is SSHed from?

**Comment by pseudoparenchymatous** [comment]
In the meantime, I stopped using Tmux and instead now using Zellij. Splits are too useful for me. Also,  `fish` shell can reproduce the bug for me when executing `clear` command in a vertical split.

**Comment by GR3YH4TT3R93** [comment]
Have you tried adding the following to your tmux config?

`set-option -ga terminal-overrides ",xterm-256color:Tc"`
