### ISSUE TITLE
I Installed Kali Rolling on Termux (Termux-Kali)

### ISSUE THREAD

**Issue by cr4shcod3** [termux/termux-packages#1255]
apt-get update && apt-get upgrade -y && apt-get install proot curl wget git

wget https://build.nethunter.com/kalifs/kalifs-latest/kalifs-arm64-full.tar.xz

proot --link2symlink tar -xf kalifs-arm64-full.tar.xz

cd kali-arm64 && echo "nameserver 8.8.8.8" > etc/resolv.conf

cd ../ && echo "proot --link2symlink -0 -r kali-arm64 -b /dev/ -b /sys/ -b /proc/ -b /data/data/com.termux/files/home -b /system -b /mnt  /usr/bin/env -i HOME=/root PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games TERM=$TERM  /bin/bash --login" > start.sh

chmod 777 start.sh && termux-fix-shebang start.sh && ./start.sh

Any suggestions? Or you can also help me to make this better

**Comment by Auxilus** [comment]
Nice @cr4shcod3 !

**Comment by fornwall** [comment]
Thanks!

I'm closing this issue, see https://wiki.termux.com/wiki/Main_Page, https://plus.google.com/communities/101692629528551299417 and https://groups.io/g/termux/ for additional places to discuss Termux!

**Comment by ogaskell** [comment]
I get a 404 from the URL in the 2nd command. where can i get this file now?

**Comment by Kaosxlinus** [comment]
@ogaskell what kind of device do are you trying to install this on?

**Comment by Kaosxlinus** [comment]
@ogaskell better yet, what kind of processor do you have? i386? amd64?

**Comment by Kaosxlinus** [comment]
@ogaskell if it's not either of those, look through this directory https://build.nethunter.com/kalifs/kalifs-latest/ and add the kalifs-"yourprocessor"-full.tar.xz to the end of that link, and use it with wget

**Comment by Hax4us** [comment]
@ogaskell if you are arm user ( either 64 bit or 32 bit) you can go here and install Nethunter with one click https://github.com/Hax4us/Nethunter-In-Termux
