### ISSUE TITLE
[Package]: termplay

### ISSUE THREAD

**Issue by rihaq** [termux/termux-packages#12570]
### Why do you want to add this package to Termux?

For playing videos in Termux

### Home page URL

https://gitlab.com/jD91mZM2/termplay

### Source code URL

https://github.com/jD91mZM2/termplay

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by rihaq** [comment]
@sylirre upload a proof showing mpv supports video

**Comment by rihaq** [comment]
@sylirre I'll close this issue if you 👆

**Comment by rihaq** [comment]
.....

**Comment by rihaq** [comment]
@sylirre timg doesn't support

**Comment by rihaq** [comment]
https://github.com/termux/termux-app/issues/3092

What is your command to play mp4?

**Comment by hzeller** [comment]
if you use `timg` with the character pixelation, things should work fine @sylirre 
I suspect @rihaq was using the `-pi` option to use the high-resolution iterm2 image rendering, in which `timg` needs more information.

**Comment by rihaq** [comment]
Yes I use iterm2, character pixelation is very bad quality
