### ISSUE TITLE
git-subtree is unavailable by default

### ISSUE THREAD

**Issue by a1batross** [termux/termux-packages#1257]
Default git package does not provide git subtree script. I installed it by hand, works perfectly.

**Comment by nstgc** [comment]
By this do you mean compiled it yourself?

**Comment by xeffyr** [comment]
Currently it is implemented as separate package in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install git-subtree
```
