### ISSUE TITLE
[Package]: minimodem

### ISSUE THREAD

**Issue by gbu117** [termux/termux-packages#12585]
### Why do you want to add this package to Termux?

Useful tool.

_Minimodem is a command-line program which decodes (or generates) audio modem tones at any specified baud rate, using various framing protocols. It acts a general-purpose software FSK modem, and includes support for various standard FSK protocols such as Bell103, Bell202, RTTY, TTY/TDD, NOAA SAME, and Caller-ID._

_Minimodem can play and capture audio modem tones in real-time via the system audio device, or in batched mode via audio files._

_Minimodem can be used to transfer data between nearby computers using an audio cable (or just via sound waves), or between remote computers using radio, telephone, or another audio communications medium._

### Home page URL

http://www.whence.com/minimodem/

### Source code URL

https://github.com/kamalmostafa/minimodem

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by nycki93** [comment]
How do you give this program access to the system microphone?
