### ISSUE TITLE
[Bug]: Could not locate Gemfile

### ISSUE THREAD

**Issue by Rekha070** [termux/termux-packages#12587]
### Problem description

I'm installing any tool it's sqlite3 is not able to install 
And when i do bundle install it's says "Could not locate Gemfile "

### What steps will reproduce the bug?

Could not locate Gemfile
Pip is there

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Bundle is a ruby command, unrelated to pip or sqlite3. Install sqlite3 through pkg (`pkg install sqlite`). Closing as unclear what you are trying to do.
