### ISSUE TITLE
lftp execl(/bin/sh) failed

### ISSUE THREAD

**Issue by sdalu** [termux/termux-packages#1259]
When connecting with ssh (sftp), it is not possible to run command, due to /bin/sh failed
~~~~
lftp sftp://xxx@yyyy
lftp xxx@yyyyyy:~> ls
`ls' at 0 [execl(/bin/sh) failed: No such file or directory]
~~~~

**Comment by fornwall** [comment]
Thanks to @its-pointless this should now be fixed in version `4.8.0-2` of the lftp package, to which you can update to with:

    pkg upgrade

Let us know if the problem remains!
