### ISSUE TITLE
apt update - Hash Sum Mismatch

### ISSUE THREAD

**Issue by AlanFlaherty** [termux/termux-packages#1260]
Unable to update package sources or install packages. 
```
$ apt update
Get:1 http://termux.net stable InRelease [1666 B]
Get:2 http://termux.net stable/main all Packages [4116 B]
Get:3 http://termux.net stable/main arm Packages [56.7 kB]
Err:3 http://termux.net stable/main arm Packages
  Hash Sum mismatch
Fetched 58.1 kB in 1s (34.9 kB/s)
Reading package list ... Done
E: Failed to fetch http://termux.net/dists/stable/main/binary-arm/Packages.xz Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Packages updated on the 11/08/2017, yesterday, seem to be causing the same issue when doing an ```apt install packagename```

**Comment by sdrausty** [comment]
```
$ apt update                                                                                                Hit:1 http://termux.net stable InRelease                                                                    Reading package lists... Done                                                                               Building dependency tree                                                                                    Reading state information... Done                                                                           All packages are up to date.
```
It is not getting any other Hits; Why?

**Comment by AlanFlaherty** [comment]
Had you already updated in the last day or so?

For arm 
The current InRelease lists the Hash of Packages.xy  as:

SHA 256
12eff6dfe3f1fccf78064b6fdc39e79e361bdff80b6b4787c7d164b443ee06f7

After Downloading and checking it looks like it should be:
C0AF3269E38D83951329514B4EC6AD78EBB8A9B8D74FFCFC0E696D7D6A901830

For aarch64 the listed hash of 91c37f56eca7fc4d3d12ae4001f0146da37289b53890480f9a985999e79fd650 matches the Packages.xy for that distribution

Alan

**Comment by fornwall** [comment]
This problem is due to caching issues with the cloudflare content distribution network which the termux apt repo uses. Normally it resolves itself after a short while.

@AlanFlaherty Does it work if you try now?

**Comment by AlanFlaherty** [comment]
Thanks,

All seems to be working again!
