### ISSUE TITLE
[Bug]: abootimg issue

### ISSUE THREAD

**Issue by AndVer2** [termux/termux-packages#12609]
### Problem description

after i request abootimg and giving source you mess something important:
abootimg-unpack/pack-initrd need to unpack and repack initrd.img (ramdisk) and that need gzip / cpio support i hope you add it

### What steps will reproduce the bug?

command not found

### System information

termux-info:

```

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=28193
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
10
Kernel build information:
Linux localhost 3.18.140-21947068 #1 SMP PREEMPT Wed Jan 12 20:26:43 KST 2022 armv8l Android
Device manufacturer:
samsung
Device model:
SM-M105G

**Comment by AndVer2** [comment]
@Grimler91 if you are busy sorry for pin

**Comment by agnostic-apollo** [comment]
`cpio` and `gzip` packages are already available, install them.

**Comment by Grimler91** [comment]
The helper scripts, which are just wrappers around cpio and gzip as @agnostic-apollo wrote, have been added in commit fa30c4d4cb9ef96fbff829220dc4781a7c741934

**Comment by AndVer2** [comment]
> `cpio` and `gzip` packages are already available, install them.

well as i know you didnt see abootimg repo. grimler add abootimg (its unpack and repack boot image) but he didnt add abootimg-unpack/pack-initrd which unpack and repack the initrd.img (ramdisk of boot.img) and abootimg to make sure repack ur boot.img he need: 
Image (kernel) + intrd.img (ramdisk) + something.cfg

**Comment by AndVer2** [comment]
> The helper scripts, which are just wrappers around cpio and gzip as @agnostic-apollo wrote, have been added in commit [fa30c4d](https://github.com/termux/termux-packages/commit/fa30c4d4cb9ef96fbff829220dc4781a7c741934)

thanks
