### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "gdalinfo": library "libwebp.so"

### ISSUE THREAD

**Issue by riveryeti** [termux/termux-packages#12611]
### Problem description

Installing gdal with pkg install gdal after pkg upgrade && pkg update I still get this error:

CANNOT LINK EXECUTABLE "gdalinfo": library "libwebp.so" not found: needed by /data/data/com.termux/files/usr/lib/libgdal.so in namespace (default)

### What steps will reproduce the bug?

pkg install gdal
gdalinfo --version

### What is the expected behavior?

Print gdalinfo version

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=696
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
12
Kernel build information:
Linux localhost 4.14.113-24706840 #1 SMP PREEMPT Fri Jul 29 15:12:47 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G975N
```

**Comment by 2096779623** [comment]
Adding `libwebp` to `TERMUX_PKG_DEPENDS` solved the problem, if updated to the latest version it would encounter build errors.

https://github.com/2096779623/termux-packages/actions/runs/3350673054/jobs/5551632892#step:6:1680

**Comment by riveryeti** [comment]
Thanks for the quick fix! Thanks to y'all I was able to build a VRT pointing to a remote cloud-optimized geotiff (COG) all from the comfort of my phone!
