### ISSUE TITLE
[Package]: dnote

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#12615]
### Why do you want to add this package to Termux?

A simple command line notebook for programmers

### Home page URL

https://www.getdnote.com

### Source code URL

https://github.com/dnote/dnote

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

There is a cli and a server, having the cli at least is good enough but having the server too would be nice, perhaps two packages `dnote` and `dnote-server`

It's written in Go so I hope packaging it will be as simple as the many Go packages we already have.

**Comment by 2096779623** [comment]
```bash
~/dnote-server-v2.0.1 $ VERSION=2.0.1 make
==> installing go dependencies
==> installing js dependencies
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-10-29T08_41_27_238Z-debug-0.log
make: *** [Makefile:24: install-js] Error 1

~/.../server/assets $ cat /data/data/com.termux/files/home/.npm/_logs/2022-10-29T08_44_14_206Z-debug-0.log
0 verbose cli /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/bin/npm
1 info using npm@8.19.2
2 info using node@v16.18.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 15ms
5 timing config:load:file:/data/data/com.termux/files/usr/lib/node_modules/npm/npmrc Completed in 6ms
6 timing config:load:builtin Completed in 7ms
7 timing config:load:cli Completed in 11ms
8 timing config:load:env Completed in 3ms
9 timing config:load:file:/data/data/com.termux/files/home/dnote-server-v2.0.1/pkg/server/assets/.npmrc Completed in 1ms
10 timing config:load:project Completed in 22ms
11 timing config:load:file:/data/data/com.termux/files/home/.npmrc Completed in 10ms
12 timing config:load:user Completed in 12ms
13 timing config:load:file:/data/data/com.termux/files/usr/etc/npmrc Completed in 2ms
14 timing config:load:global Completed in 4ms
15 timing config:load:validate Completed in 3ms
16 timing config:load:credentials Completed in 6ms
17 timing config:load:setEnvs Completed in 7ms
18 timing config:load Completed in 97ms
19 timing npm:load:configload Completed in 99ms
20 timing npm:load:mkdirpcache Completed in 7ms
21 timing npm:load:mkdirplogs Completed in 3ms
22 verbose title npm i
23 verbose argv "i"
24 timing npm:load:setTitle Completed in 12ms
25 timing config:load:flatten Completed in 28ms
26 timing npm:load:display Completed in 47ms
27 verbose logfile logs-max:10 dir:/data/data/com.termux/files/home/.npm/_logs
28 verbose logfile /data/data/com.termux/files/home/.npm/_logs/2022-10-29T08_44_14_206Z-debug-0.log
29 timing npm:load:logFile Completed in 61ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 243ms
33 timing arborist:ctor Completed in 9ms
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 374ms
36 warn old lockfile
36 warn old lockfile The package-lock.json file was created with an old version of npm,
36 warn old lockfile so supplemental metadata must be fetched from the registry.
36 warn old lockfile
36 warn old lockfile This is a one-time fix-up, please be patient...
36 warn old lockfile
37 timing npm Completed in 1474ms
38 verbose unfinished npm timer command:i 1667033055136
39 verbose unfinished npm timer reify 1667033055162
40 verbose unfinished npm timer reify:loadTrees 1667033055239
41 verbose unfinished npm timer idealTree 1667033055243
42 verbose unfinished npm timer idealTree:inflate 1667033055621
43 info ok
44 error Exit handler never called!
45 error This is an error with npm itself. Please report this error at:
46 error     <https://github.com/npm/cli/issues>
47 error A complete log of this run can be found in:
47 error     /data/data/com.termux/files/home/.npm/_logs/2022-10-29T08_44_14_206Z-debug-0.log
```

**Comment by ravener** [comment]
Re-opening this, to discuss some more packaging issues.

One issue is the version is shown as `2.0.1` which is the server's version, the cli version is currently at `0.12`

and the final binary built results in version being set to `master` instead of the actual version.
```
$ dnote version
dnote master
```
Instead of messing around with subpackages I just suggest these to be two different independent packages, fetching their own version from the github releases.

**Comment by ravener** [comment]
@2096779623 and the latest changes you made with the `unversioned` stuff, it did not solve anything, it still depends on the dnote parent package, just unversioned. Additionally you also ruined the `frp` package, it too now depends on each other and so everything is installed.

The `dnote-client` and `dnote-server` packages still remain empty (as they are just a few kbs in size) and everything is actually inside `dnote` package.

**Comment by ravener** [comment]
I'd suggest someone like @sylirre and others to take a look at what's going on here.

See also some of the comments in the linked PR.

**Comment by Grimler91** [comment]
> Re-opening this, to discuss some more packaging issues.

This should rather be tracked in a new issue, not in the original package request

> Additionally you also ruined the frp package, it too now depends on each other and so everything is installed.

I don't like this attitude. Open a bug report to report the issue, or a PR to fix the problem, instead of complaining about the work done by others.

> I'd suggest someone like @sylirre and others to take a look at what's going on here.
> 
> See also some of the comments in the linked PR.

You assigned yourself here, so are you planning to work on improving the package yourself or do you want someone else to do it?

**Comment by ravener** [comment]
@Grimler91
 
> I don't like this attitude. Open a bug report to report the issue, or a PR to fix the problem, instead of complaining about the work done by others.

I apologize, I did not mean to sound rude, I was just trying to point out an issue caused by a recent change.

> You assigned yourself here, so are you planning to work on improving the package yourself or do you want someone else to do it?
Yes I assigned myself to show that I care and will attempt to do what I can but I may or may not be able to do it, so I'll need help.

**Comment by ravener** [comment]
@2096779623 it looks hardcoded but it can be changed at build time, see https://github.com/dnote/dnote/blob/master/scripts/cli/build.sh#L60

**Comment by ravener** [comment]
Also I suggest we stop using subpackages like this.

As grimler mentioned, it's for packages that provide a subpackage (e.g a cli tool) that depends on the parent package.

In this case, these two packages (server and cli) can behave independently and are not a subpackage of any. Just have two packages `dnote` and a seperate package `dnote-server`

Even the CLI alone is fine, and even if you decide to just bundle both the server and cli in one package that'll also be fine, let's just get over this.
