### ISSUE TITLE
Cinnamon or MATE Desktop Environment Package Please

### ISSUE THREAD

**Issue by cr4shcod3** [termux/termux-packages#1262]
There are many programs or tools that needs to be run on GUI because some of them uses GTK. Like w3af and many more. I hope that you can build this. Goodluck

**Comment by xeffyr** [comment]
Cinnamon/MATE and dependencies for them require patching for working with Android's bionic libc, non standart prefix (/data/data/com.termux/files/usr) and etc. So there are a lot of work and chances that Cinnamon or other desktop environments will be available in Termux are very small.

**Comment by xeffyr** [comment]
If you want GUI apps, see this: https://github.com/vishalbiswas/termux-packages/tree/x11, this tree contains some xorg packages and VNC server.

**Comment by cr4shcod3** [comment]
Can you tell me how?

**Comment by xeffyr** [comment]
Install Linux distribution into VM (for example Ubuntu), install and setup docker, then follow guide for building packages in [termux-packages readme](https://github.com/termux/termux-packages#setting-up-a-build-environment-using-docker).

**Comment by xeffyr** [comment]
X11 packages are available here: https://github.com/xeffyr/termux-extra-packages. Availablility of large desktop environments like Cinnamon/Mate/Gnome/KDE is **unlikely**.
