### ISSUE TITLE
"termux-api" feature request: change android wallpaper from Termux

### ISSUE THREAD

**Issue by OpnSrcConstruction** [termux/termux-packages#1263]
in a recent post on G+ Termux community, a community member asked if it was possible to change the Android background from Termux; and I though the Termux-api package might be a great way to implement that feature. This could lend itself to really cool Termux scripts to change the Android backgrounds. I was just looking at a package for Linux recently, that changes the wallpaper based on the weather; and if this feature were to be implemented it could make things like that and so much more possible from Termux.

**Comment by fornwall** [comment]
This issue was moved to termux/termux-api#106

**Comment by Azhar-sayyed** [comment]
Sir please termux ke  background mai ham wallpaper kase pages iska tool banao

**Comment by kcubeterm** [comment]
@Azhar-sayyed , lol, no one can understand what you said,  This features is't available yet ,  I don't think it's essential features, why you want it.


> Sir please termux ke background mai ham wallpaper kase pages iska tool banao

English translation: Sir, make a tool that can add wallpaper in termux background.
