### ISSUE TITLE
dpkg hook scripts lacks shebangs so are executed with /system/bin/sh

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#1264]
This is bad as /system/bin/sh may not work as expected due to version differences or sharwd library clashes.

We should update the dpkg hook scripts to have shebang lines specifying `$TERMUX_PREFIX/bin/sh` or similar.

**Comment by sdrausty** [comment]
```
$ $TERMUX_PREFIX
$ $PREFIX
bash: /data/data/com.termux/files/usr: Is a directory
```

**Comment by fornwall** [comment]
Right, `$PREFIX` is what is available on device, while `$TERMUX_PREFIX` is used in most places when cross compiling.

**Comment by sdrausty** [comment]
@fornwall Thank you.
