### ISSUE TITLE
Requesting pypy

### ISSUE THREAD

**Issue by refacto** [termux/termux-packages#1265]
Pypy is an implementation of the python language focusing on speed, and I'd like to have it in termux.

This brings a couple of conflicts however, how would we deal with having different `pip`s around at the same time? Gentoo deals with this by using easily settable symlinks that can be set with the `eselect` utility. `python` could be just a symlink pointing to the currently chosen python implementation!

**Comment by veeshi** [comment]
Any update on this? Pypy will defo help speed up pure python scripts

**Comment by amir3code** [comment]
Hey guys! No update? We need pypy for speed up so we are not dependent upon CFFI. I hate C myself. pypy runs without issues related to python C interface (When running code on your pc vs running on termux there might be incompatibilities but with pypy there should be none!)

Please! I am begging you! Give us pypy on android!

**Comment by amir3code** [comment]
If somebody can get it compiled on termux please let us know, or if you have any issues post them here so People can help you get it compiled.

**Comment by aprilahijriyan** [comment]
hi @fornwall, i need this too! I hope this request is expedited. thanks!

**Comment by Nemo-Nowane** [comment]
I'll like to try pypy too.

**Comment by ccboxes** [comment]
Considering the low performance of mobile platforms, pypy is significant.

**Comment by Crystal-Lilith** [comment]
Heya, this still active? I think PyPy on mobile could significantly help alot of people, so I'd appreciate this alot

**Comment by Divyansh3027** [comment]
pyp a speed mirror of python, who don`t wan`t to use it.
If it got available on termux it may touch the peack speed of languages in android

**Comment by wenderccc** [comment]
You can easily install it by doing this:
```
pkg install proot-distro
proot-distro install ubuntu
proot-distro login ubuntu
apt update
apt upgrade
apt install pypy3
pypy3
```
The only problem is that every time you want to use it you should go into you Ubuntu distro. But it's the only way to use it

**Comment by licy183** [comment]
I tried to build pypy from source on the official website, but I failed to compile it. Following are my steps:
First, get source code from website.
```bash
pkg install wget unzip
wget https://downloads.python.org/pypy/pypy3.6-v7.3.2-src.zip
unzip pypy3.6-v7.3.2-src.zip
```
Second, install the dependencies.
```bash
pkg install cmake clang python2 python2-static \
        libffi libffi-static pkg-config \
        zlib zlib-static \
        libbz2 \
        libexpat libexpat-static \
        libsqlite libsqlite-static \
        openssl openssl-static \
        gdbm gdbm-static \
        liblzma liblzma-static
python2 -m pip install pycparser
```
Third, modify some files.
```
./rpython/rtyper/tool/rffi_platform.py line 556
[+] class NotWorks(CConfigSingleEntry):
[+]    def question(self, ask_gcc):
[+]        return False

./rpython/rlib/rtime.py line 32
[-]if not sys.platform.startswith("openbsd") and \
[-]       not sys.platform.startswith("freebsd"):
[-]        includes.append('sys/timeb.h')

./rpython/rlib/rtime.py line 46
[-]HAVE_FTIME = rffi_platform.Has(FTIME)
[+]HAVE_FTIME = rffi_platform.NotWorks()
```
Finally, build it.
```bash
cd ./pypy/goal
python2 ../../rpython/bin/rpython --opt=jit --cc=clang
``` 
But it will make Termux close without any message.

**Comment by xeffyr** [comment]
> But it will make Termux close without any message.

Because you don't have enough RAM. It is quite a heavy thing to build on device.

**Comment by licy183** [comment]
> > But it will make Termux close without any message.
> 
> Because you don't have enough RAM. It is quite a heavy thing to build on device.

So is it possible to build this kind of package on an Android device? I want to use pypy on the Termux environment rather than some other distros.

**Comment by AhmadNaruto** [comment]
never try it. but you can try this..
https://amp.reddit.com/r/termux/comments/mwt0c6/pypy_compiled_on_and_working_in_termux/

**Comment by licy183** [comment]
I successfully build pypy3 on aarch64, maybe helpful.

The general idea is to use sshfs to mount /data/data/com.termux/files from the phone to the computer, and then use docker to run the aarch64 version of termux-docker, and then mount the source code directory into the container (the source code is on the phone), use ssh (slower) or http to execute commands remotely so that the translation process is performed on the computer, and the compilation process is still performed on the mobile phone, and files can be synchronized.

I modified some files, as following.

<details>
  <summary>Hard code the platform</summary>

In fact, clang is still called on the mobile phone. This is a fake cross-compilation. Hard-coding the platform will make the compilation operation easier I think.

```
./rpython/jit/backend/detect_cpu.py line 106
def autodetect():
    return MODEL_ARM64

./rpython/jit/backend/detect_cpu.py line 113
def getcpuclassname(backend_name="auto"):
    return "rpython.jit.backend.aarch64.runner", "CPU_ARM64"

./rpython/jit/backend/detect_cpu.py line 141
def getcpufeatures(backend_name="auto"):
    return ['floats']
```

</details>

<details>
  <summary>Delete ftime support</summary>

As mentioned in the comment above, `timeb.h` has been deleted in Android.

```
./rpython/rtyper/tool/rffi_platform.py line 556
[+] class NotWorks(CConfigSingleEntry):
[+]    def question(self, ask_gcc):
[+]        return False

./rpython/rlib/rtime.py line 32
[-]if not sys.platform.startswith("openbsd") and \
[-]       not sys.platform.startswith("freebsd"):
[-]        includes.append('sys/timeb.h')

./rpython/rlib/rtime.py line 46
[-]HAVE_FTIME = rffi_platform.Has(FTIME)
[+]HAVE_FTIME = rffi_platform.NotWorks()
```
</details>

<details>
  <summary>Delete librt.so reference</summary>

On termux, librt.so is an ld script pointing to libc.so, which cannot be opened by python interpreter through dlopen, which will cause errors and compile failures.

```
./rpython/translator/platform/test/test_posix.py line 39
[-] if sys.platform.startswith('linux'):
[-]     assert '-lrt' in tmpdir.join("Makefile").read()

./rpython/translator/platform/linux.py line 14
[-] extra_libs = ('-lrt',)

./rpython/rlib/rtime.py line 54
[-] libraries = ['rt']
[+] libraries = ['c']

./rpython/rlib/rtime.py line 201
[-] eciclock = eciclock.merge(ExternalCompilationInfo(libraries=['rt']))
[+] eciclock = eciclock.merge(ExternalCompilationInfo(libraries=['c']))

./pypy/module/_multiprocessing/interp_semaphore.py line 43
[-] if sys.platform == 'darwin':
[-]    libraries = []
[-] else:
[-]    libraries = ['rt']
[+] libraries = []
```
</details>

<details>
  <summary>Add remote execution support</summary>

As explained above, we have to let clang execute remotely (on the phone) instead of locally (in the container). 

Rewrite ./python/translator/platform/arm.py.

```python
from rpython.translator.platform.linux import Linux
from rpython.translator.platform.posix import GnuMakefile
from rpython.translator.platform import ExecutionResult, log
from os import getenv
import requests
import json

REMOTE_IP = "192.168.1.90"
REMOTE_PORT = 8080
URL ="http://{0}:{1}/run".format(REMOTE_IP, REMOTE_PORT)

def run(executable, args=None, env=None, cwd=None):
    log.execute('http exec: '+ str(executable) + ' ' + ' '.join(args if args is not None else []))
    payload = {"executable": executable, "args": args, "env": env, "cwd": cwd}
    resp = requests.post(url=URL, json=payload)
    res = json.loads(resp.text)
    returncode, stdout, stderr = res['returncode'], res['stdout'], res['stderr']
    return returncode, bytes(stdout.decode('base64')), bytes(stderr.decode('base64'))

class ARM(Linux):
    name = "arm"
    shared_only = ('-fPIC',)

    available_librarydirs = ['/data/data/com.termux/files/usr/lib/']

    available_includedirs = ['/data/data/com.termux/files/usr/lib/']
    copied_cache = {}


    def _invent_new_name(self, basepath, base):
        pth = basepath.join(base)
        num = 0
        while pth.check():
            pth = basepath.join('%s_%d' % (base,num))
            num += 1
        return pth.ensure(dir=1)

    def _execute_c_compiler(self, cc, args, outname, cwd=None):
        # log.execute('http exec: '+ cc + ' ' + ' '.join(args))
        cclist = cc.split()
        cc = cclist[0]
        args = cclist[1:] + args
        returncode, stdout, stderr = run(cc, args, self.c_environ, cwd)
        self._handle_error(returncode, bytes(stdout), bytes(stderr), outname)

    def execute(self, executable, args=[], env=None):
        # log.execute('http exec: '+ str(executable) + ' ' + ' '.join(args))
        returncode, stdout, stderr = run(str(executable), args, env)
        return ExecutionResult(returncode, bytes(stdout), bytes(stderr))

    def include_dirs_for_libffi(self):
        return self.available_includedirs

    def library_dirs_for_libffi(self):
        return self.available_librarydirs

    def _preprocess_library_dirs(self, library_dirs):
        return list(library_dirs) + self.available_librarydirs

    def execute_makefile(self, path_to_makefile, extra_opts=[]):
        if isinstance(path_to_makefile, GnuMakefile):
            path = path_to_makefile.makefile_dir
        else:
            path = path_to_makefile
        log.execute('http exec: make %s in %s' % (" ".join(extra_opts), path))
        returncode, stdout, stderr = run('make', ['-C', str(path)] + extra_opts)
        self._handle_error(returncode, stdout, stderr, path.join('make'))
```

```python
# from rpython.tool.runsubprocess import run_subprocess as _run_subprocess
import requests
import json

REMOTE_IP = "192.168.1.90"
REMOTE_PORT = 8080
URL ="http://{0}:{1}/run".format(REMOTE_IP, REMOTE_PORT)

def _run_subprocess(executable, args=None, env=None, cwd=None):
    log.execute('http exec: '+ str(executable) + ' ' + ' '.join(args if args is not None else []))
    payload = {"executable": executable, "args": args, "env": env, "cwd": cwd}
    resp = requests.post(url=URL, json=payload)
    res = json.loads(resp.text)
    returncode, stdout, stderr = res['returncode'], res['stdout'], res['stderr']
    return returncode, bytes(stdout.decode('base64')), bytes(stderr.decode('base64'))
```

And then run a flask server on the phone

```python
from flask import Flask, render_template, url_for, request, json, jsonify, make_response
from subprocess import PIPE, Popen
import sys
import base64

app = Flask(__name__)

def _run_subprocess(executable, args=None, env=None, cwd=None):
    if isinstance(args, str):
        args = str(executable) + ' ' + args
        shell = True
    else:
        if args is None:
            args = [str(executable)]
        else:
            args = [str(executable)] + args
        shell = False
    print("http exec:", " ".join(args))
    pipe = Popen(args, stdout=PIPE, stderr=PIPE, shell=shell, env=env, cwd=cwd)
    stdout, stderr = pipe.communicate()
    return pipe.returncode, stdout, stderr

@app.route('/run', methods=['POST'])
def calc():
    req = json.loads(request.get_data(as_text=True))
    returncode, stdout, stderr = _run_subprocess(**req)
    return jsonify(returncode=returncode, stdout=base64.b64encode(stdout).decode(), stderr=base64.b64encode(stderr).decode())

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=True)
```

</details>

<details>
  <summary>Patch ctypes.util.find_library in the container</summary>
In python2, the default behavior of ctypes.util.find_library is to call `gcc`, `ldconfig` and other external commands to determine the name of the library, but `gcc` is an alias of `clang` in termux, `clang` cannot run in the docker, and Android does not allow users to call `/sbin/ldconfig`, so it is necessary to change this logic and let it return to libxxx.so directly.

```python
    return name if name.endswith(".so") else ("lib" + name + ".so")
```

</details>

**Comment by BlackCatDevel0per** [comment]
Big thanks licy183!
