### ISSUE TITLE
Program curl crashes with "CANNOT LINK EXECUTABLE..."

### ISSUE THREAD

**Issue by 4544fa8d** [termux/termux-packages#127]
Hello

After running this command: 
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

curl crashes with this message:
CANNOT LINK EXECUTABLE: cannot locate symbol "Curl_raw_nequal" referenced by "curl"...

**Comment by fornwall** [comment]
Hi, see [Common problems: CANNOT LINK EXECUTABLE ](https://termux.com/common-problems.html#cannot-link-executable-cannot-locate-symbol--referenced-by-)!

**Comment by michaelhou** [comment]
just try `apt-get upgrade`, it work fine for me.
