### ISSUE TITLE
[Bug]: polybar build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#12725]
### Problem description

--   No package 'xcb-proto' found
CMake Error at .../cmake-3.24/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
 ...FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  lib/xpp/CMakeLists.txt:10 (pkg_check_modules)

### What steps will reproduce the bug?

build packages

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
<a href="https://github.com/termux/termux-packages/actions/runs/3367993163">Not reproducing in CI</a>. Could you please share the full build log?
