### ISSUE TITLE
package request: flatpak

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#1277]
please add flatpak
https://github.com/flatpak/flatpak

**Comment by xeffyr** [comment]
Too much of relying on root.
Unprivileged mode will require *user namespaces* from kernel.

Also, I'm in doubt about dependencies like *dbus* and *polkit* if they will work at all in Termux.

**Comment by amsitlab** [comment]
Termux have proot just install it on linux chroot .

**Comment by xeffyr** [comment]
@amsitlab Anyway, those "hacks" make it unsuitable for packaging.

**Comment by amsitlab** [comment]
@xeffyr I not say ```root == proot``` .
