### ISSUE TITLE
can't install termux v0.18.1 from github

### ISSUE THREAD

**Issue by M7MAD77** [termux/termux-packages#12783]
### Problem description

Hi, I can't install termux on my phone from github and always when I try to install it, it gives me like that "app not installed" this is for the v 0.18.1 from github but when I install it from google play I didn't have any problem

### What steps will reproduce the bug?

installing termux v0.18.1 from github

### System information

termux-info:

```

```

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation
