### ISSUE TITLE
tcpdump: Can't open /sys/class/net: Permission denied

### ISSUE THREAD

**Issue by ironbamboo** [termux/termux-packages#1281]
tcpdump: Can't open /sys/class/net: Permission denied

Do you need root permission to run tcpdump?

**Comment by v00x** [comment]
Check this: [Add better support for root. #61](https://github.com/termux/termux-app/issues/61)

**Comment by Neo-Oli** [comment]
@fornwall Can we somehow mark all packages in the repository with *root required*, or something?

**Comment by fornwall** [comment]
@Neo-Oli perhaps we could have a separate apt repo for packages that requires root, which can be enabled by perhaps installing a `termux-root` package or similar?

This would enable adding some more experimental niche root-requiring packages which I have been hesitant to add to this main package repo, as most Termux users are non-root.

**Comment by Neo-Oli** [comment]
@fornwall That would be cool. `termux-root` is also where the `su` and perhaps a `sudo` package could go.

**Comment by Grimler91** [comment]
@fornwall Would you like someone else to host and be responsible for that repo?
(just asking)

**Comment by fornwall** [comment]
@Grimler91 Yes, that would be great, as I don't use any rooted device myself!

**Comment by Neo-Oli** [comment]
Does tcpdump actually require root or is this a bug?

**Comment by vishalbiswas** [comment]
are you on Android O Developer Preview?

**Comment by Neo-Oli** [comment]
@vishalbiswas I'm not. I'm on 7.1 and I get the same error.

**Comment by fornwall** [comment]
AFAIK tcpdump really requires root access (it's also possible with capabilities, https://askubuntu.com/questions/530920/tcpdump-permissions-problem, but on Android that implies root access).

**Comment by sdrausty** [comment]
@Neo-Oli @fornwall et. al. Package requests: su, sudo, termux-make-root and termux-make-unroot are potential spin-offs. https://github.com/termux/termux-packages/issues/1176#issuecomment-319508290

**Comment by xeffyr** [comment]
Closing as this is not really an issue if package requires root.

**Comment by SlimEmm** [comment]
> @fornwall Can we somehow mark all packages in the repository with _root required_, or something?

Sir as we wonder that there are 2 types of roots 
1 rooted device
2 termux-ubuntu
So as airmon-ng having problems when it is not rooted device
It still shows errors in termux-ubuntu

**Comment by xeffyr** [comment]
> Sir as we wonder that there are 2 types of roots

Only one type of root.

termux-ubuntu is proot and root access is here FAKE, i.e. it is just barely UID number with value "0". It doesn't give any permissions.

> So as airmon-ng having problems when it is not rooted device

Airmon-ng requires:
* rooted device, e.g. with Magisk or SuperSU
* kernel with injection patches and drivers for USB wifi stick

It won't work in termux-ubuntu.
