### ISSUE TITLE
[Bug]: crowbook build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#12824]
### Problem description

[crowbook.txt](https://github.com/termux/termux-packages/files/9926528/crowbook.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by licy183** [comment]
We should wait for upstream to bump a new version...

**Comment by xtkoba** [comment]
A workaround is to specify `TERMUX_RUST_VERSION` in `build.sh`: ca3740d5e47f1c329a79a58d5a1292d57065d4a2.

Another potential workaround is proposed in https://github.com/Rigellute/spotify-tui/issues/1027, though I have not investigated it.

**Comment by xtkoba** [comment]
Closing as build failure itself is resolved.
