### ISSUE TITLE
Python 3 doesn't start with libintl error

### ISSUE THREAD

**Issue by thurask** [termux/termux-packages#1283]
```
$python --version
CANNOT LINK EXECUTABLE "python": library "libintl.so" not found
Aborted
```

This is after packages upgrade, which upgraded libandroid-support to v22.

**Comment by its-pointless** [comment]
As a work around 
cd ~/../usr/lib
ln -s libandroid-support.so libintl.so

**Comment by Neo-Oli** [comment]
This doesn't only apply to python. The following packages have been found to be broken:
- python
    - ranger
    - profanity
- python2
- neovim
- ffmpeg
    - bs1770gain
    - mpv
    - mpd
- libgnutls
- emacs
- binutils

**Comment by fornwall** [comment]
Thanks for reporting! This has been fixed now, run `pkg up` to update all packages!
