### ISSUE TITLE
Python pkg needs libintl.so

### ISSUE THREAD

**Issue by djhenderson** [termux/termux-packages#1284]
After a fresh install of termux, installing python pkg fails with message `CANNOT LINK EXECUTABLE "python": library "libintl.so" not found`. 
Is there a package that will supply libintl.so?

**Comment by its-pointless** [comment]
As a work around
cd ~/../usr/lib
ln -s libandroid-support.so libintl.so

The functions needed in libintl.so which was a symlink to libandroid-support.so are now inlined in a header. Which means lots of stuff just broke. Its a fuck up... but we are trying to fix

**Comment by djhenderson** [comment]
Thanks. That worked (within the limits of my quick test). I wish you success with the fix. This is a 5 star app!

**Comment by fornwall** [comment]
Great!

The issue has been fixed (`libintl.so` has been removed from Termux and some packages needed to be rebuilt, which has happened now).
