### ISSUE TITLE
Segmentation Fault in `aapt` after Latest Update

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1287]
This segmentation fault breaks https://github.com/sdrausty/buildAPKs 🙁 Please fix this issue.
aapt/stable,now 7.0.0.14-3 aarch64 [installed]
Termux-packages arch:
aarch64
Android version:
6.0.1
```
Welcome to Termux!

Online help:     https://termux.com/help
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ cd buildAPKs/sources/apps/ActivityForResult/
$ buildAll.sh
aapt begun
Configurations:
 (default)
 ldpi-v4
 mdpi-v4
 hdpi-v4

Files:
  drawable/icon.png
    Src: (ldpi-v4) res/drawable-ldpi/icon.png
    Src: (mdpi-v4) res/drawable-mdpi/icon.png
    Src: (hdpi-v4) res/drawable-hdpi/icon.png
  layout/first.xml
    Src: () res/layout/first.xml
  layout/second.xml
    Src: () res/layout/second.xml
  values/strings.xml
    Src: () res/values/strings.xml
  AndroidManifest.xml
    Src: () ./AndroidManifest.xml

Resource Dirs:
  Type drawable
    drawable/icon.png
      Src: (ldpi-v4) res/drawable-ldpi/icon.png
      Src: (mdpi-v4) res/drawable-mdpi/icon.png
      Src: (hdpi-v4) res/drawable-hdpi/icon.png
  Type layout
    layout/first.xml
      Src: () res/layout/first.xml
    layout/second.xml
      Src: () res/layout/second.xml
  Type values
    values/strings.xml
      Src: () res/values/strings.xml
Including resources from package: /data/data/com.termux/files/usr/share/aapt/android.jar
Including resources from package: /data/data/com.termux/files/usr/share/java/android.jar
applyFileOverlay for drawable
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
    (new resource id icon from res/drawable-ldpi/icon.png)
    (new resource id icon from res/drawable-mdpi/icon.png)
    (new resource id icon from res/drawable-hdpi/icon.png)
    (new resource id first from res/layout/first.xml)
    (new resource id second from res/layout/second.xml)
Segmentation fault
$
```
![screenshot_20170817-105300](https://user-images.githubusercontent.com/27742457/29418526-8e4b9044-833a-11e7-9004-3f65f723714a.png)

**Comment by fornwall** [comment]
Writing down comment by me on gitter to remember it:

Hm, about termux/termux-packages#1287, I don't think I can reproduce the issue. does it happen when building any app or just some particular? have you run pkg up to ensure all latest package versions?

Anyone else who can see if aapt:s segfaults for them?

**Comment by sdrausty** [comment]
@fornwall This began today after today's `apt update && apt upgrade` which is what `au` is. `aapt` currently seg faults on almost all the sources in buildAPKs. You should be able to reproduce this by 🏃 running the following in Termux:

```
cd && pkg install aapt apksigner dx ecj git
git clone https://github.com/sdrausty/buildAPKs
./buildAPKs/scripts/build/buildAll.sh
```

BuildAPKs was build passing 💯% until today.

**Comment by sdrausty** [comment]
This issue is resolved. For anyone affected by this issue, please `apt update && apt upgrade` after http://termyx.net is updated tomorrow. 😀😁😃😊🙂🤔⛵🚤🚢👍

**Comment by fornwall** [comment]
This should now be solved by version `7.1.2.33` of `aapt`, which is available for installation!

**Comment by fornwall** [comment]
> Note: You might observe au as apt update && apt update and the corresponding output in posts by me

Note that `pkg up` is a command available out of the box which runs `apt update && apt update`.

**Comment by sdrausty** [comment]
@fornwall  Thank you! Works like a charm!

**Comment by Grimler91** [comment]
@flashish see #2066.
