### ISSUE TITLE
ffplay on termux

### ISSUE THREAD

**Issue by 5perseo** [termux/termux-packages#1288]
Unable to stream over udp port.
Command ffplay udp://10.5.5.9:8554 
Works on PC but get error on termux even after install pgk mmpeg ....is there another library to get??

**Comment by stephengroat** [comment]
@5perseo what the error that you're getting? do you think it could be a network-based issue?

**Comment by 5perseo** [comment]
no command 'ffplay' found
I've installed the package ffmpeg but my question is: 
Is there a command in termux able to show the streaming n udp port?
I can't find that command or package.
I can get stream with other method so i'm sure streaming is correctly send but i can't get by termux or python in order to call it on command running a script...

**Comment by fornwall** [comment]
The `ffplay` command is not currently available in Termux! You may ask for help at https://plus.google.com/communities/101692629528551299417 about other possible solutions!
