### ISSUE TITLE
emacs fails (on x86_64) with: library "libintl.so" not found

### ISSUE THREAD

**Issue by hanslub42** [termux/termux-packages#1289]
After upgrading `libandroid-support` to version 22  I get:

    [u0_a125@kermit] ~ > emacs           
    CANNOT LINK EXECUTABLE: library "libintl.so" not found

This is probably related to 0bb0e20a36ace: shouldn't `emacs` be rebuilt as well?

Edit: in view of sdrausty's comment below, I should  have mentioned:

    emacs/stable,now 25.2-1 x86_64 [installed]
    Termux-packages arch: x86_64
    Android version: 6.0.1

All `libandroid-*` packages are at their newest versions (as in the first comment below)

**Comment by sdrausty** [comment]
```
Welcome to Termux!

Online help:     https://termux.com/help
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ au
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ apt list | grep libandroid

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libandroid-glob/stable,now 0.4 aarch64 [installed]
libandroid-glob-dev/stable,now 0.4 aarch64 [installed]
libandroid-shmem/stable,now 0.2 aarch64 [installed]
libandroid-shmem-dev/stable,now 0.2 aarch64 [installed]
libandroid-support/stable,now 22 aarch64 [installed]
libandroid-support-dev/stable,now 22 aarch64 [installed]
$ emacs
$ find $PREFIX -name libintl.so
$
```
![screenshot_20170817-105300](https://user-images.githubusercontent.com/27742457/29433418-08dbfe0c-836d-11e7-8dac-03f37c84eedf.png)
![screenshot_20170817-165730](https://user-images.githubusercontent.com/27742457/29433472-40350b6e-836d-11e7-995a-ff0d4d075d63.png)

**Comment by hanslub42** [comment]
Issue has disappeared after `pkg up` even though `emacs` didn't get updated. Closing.

**Comment by pizzapanther** [comment]
This killed my python virtualenv. After removing it and rebuilding it, everything is good again.
