### ISSUE TITLE
Request for cleanup of stale `*-static` packages

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#12905]
To infra team,

The following `*-static` packages are not produced anymore for various reasons. Please remove them from bindist mirrors.

In main repo:
- [ ] assimp-static
- [ ] capnproto-static
- [ ] flang-static
- [ ] libcairo-static
- [ ] libid3tag-static
- [ ] liblz4-static
- [ ] libp8-platform-static
- [ ] libraqm-static
- [ ] librsvg-static
- [ ] libxlsxwriter-static
- [ ] psutils-static
- [ ] pulseaudio-static
- [ ] pystring-static
- [ ] quickjs-static
- [ ] tesseract-static

In root repo:
- [ ] aircrack-ng-static

(See also #12848.)

**Comment by Grimler91** [comment]
Thanks, removed, will be gone at the next repo update
