### ISSUE TITLE
Auto update failing for libjasper

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#12902]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the libjasper package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating libjasper [Current version: 3.0.6]
INFO: package being updated to 4.0.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 

libjasper: failed to calculate the new checksum
Already up to date.
ERROR: failed to update checksum.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2022-11-05 18:09:39 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/3401112793">3401112793</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by licy183** [comment]
Closes via https://github.com/termux/termux-packages/commit/8cd822c11928c89095748876271f6433cbcb95a5.
