### ISSUE TITLE
[Bug]: smbd cannot start after upgrade to version 4.15.11-1

### ISSUE THREAD

**Issue by henry-shadowjet** [termux/termux-packages#12909]
### Problem description

Unable to start samba (smbd) in Termux after upgrading to version 4.15.11-1 through "apt update" command.

Now, when started, the following error occurs:
`CANNOT LINK EXECUTABLE "smbd": library "libexecinfo.so" not found: needed by /data/data/com.termux/files/usr/lib/libsamba-util.so.0.0.1 in namespace (default)`

### What steps will reproduce the bug?

Issue "smbd" command in Termux

### What is the expected behavior?

Samba server starts with nothing returned in the prompt. 

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7779
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
12
Kernel build information:
Linux localhost 5.10.101-android12-9-00001-g1b6eff567cae-ab8943976 #1 SMP PREEMPT Sat Aug 13 08:16:31 UTC 2022 aarch64 Android
Device manufacturer:
asus
Device model:
ASUS_AI2201_D
```

**Comment by xtkoba** [comment]
Automagic dependency on `libandroid-execinfo` package. A workaround is to manually install this package.

**Comment by henry-shadowjet** [comment]
Issue is now fixed per latest update today. Thanks!!
