### ISSUE TITLE
Suspicious `qemu-system-*-headless` binary packages in x11 repo

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#12911]
As of now, the following binary packages are populated in x11 repo:

- [ ] qemu-system-aarch64-headless
- [ ] qemu-system-arm-headless
- [ ] qemu-system-i386-headless
- [ ] qemu-system-m68k-headless
- [ ] qemu-system-ppc-headless
- [ ] qemu-system-ppc64-headless
- [ ] qemu-system-riscv32-headless
- [ ] qemu-system-riscv64-headless

These are subpackages of `qemu-system-x86-64-headless` which exists in main repo. So they should be removed from x11 repo in bindist mirrors.

**Comment by Grimler91** [comment]
Thanks, removed, will be gone at the next repo update
