### ISSUE TITLE
Auto update failing for nala

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#12927]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the nala package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating nala [Current version: 0.11.1]
ERROR: Failed to get 'latest-release-tag' (https://gitlab.com/api/v4/projects/volian%2Fnala/releases).
HTTP code: 520
Response:</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2022-11-06 18:35:00 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/3405421294">3405421294</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by licy183** [comment]
Run manually in https://github.com/termux/termux-packages/actions/runs/3406723304
