### ISSUE TITLE
Package request:  APK Downloader for Google Play

### ISSUE THREAD

**Issue by T-vK** [termux/termux-packages#1294]
It would be great to have a utility that can download apk files from Google without the Play Store. 
[gplaycli](https://github.com/matlink/gplaycli) seems to be a pretty good one. It can search, download, update and even auto-update.

**Comment by Grimler91** [comment]
@T-vK have you tried installing it on device?

**Comment by T-vK** [comment]
@Grimler91 No, I haven't.

**Comment by Grimler91** [comment]
Actually, it's even installable through pip. Install with `pip install gplaycli`. 

So no need to create a package for it.

**Comment by fornwall** [comment]
If it's installable via pip we generally try to avoid creating a Termux package for it to avoid duplication, so I'm closing this!
