### ISSUE TITLE
In Termux When i Write a Content to file and try to print it On A Screen it Does not Printing it 

### ISSUE THREAD

**Issue by Titu302** [termux/termux-packages#12957]
I Have A Problem in gcc C language When i Write a Content to file and try to print it On A Screen it Does not Printing it 
My Code is This:
GNU nano 6.3            NEW.c
#include  <stdio.h>
#include <stdlib.h>
#include <string.h>
int main()
{
          FILE *in;
          in = fopen("An.txt","a");
          if(in == NULL)
          {
           printf("NO SUCH A FILE");
           exit(1);
          }

        fprintf(in,"Hello Titu");
        char str[45];

       fscanf(in,"%s",str);
        printf("%s",str);
        fclose(in);
}
  /*__END MAIN__*/

NO DOUBT TERMUX IS BEST BUT PLEASE LET ME HELP:
https://termux.dev/donate

**Comment by xtkoba** [comment]
This is not related to Termux at all. Just that your code is bad.

**Comment by Titu302** [comment]
Thank You So Much....
May be My Beginning But Thank You So Much ❤️

**Comment by Titu302** [comment]
> This is not related to Termux at all. Just that your code is bad.

💔🫂
