### ISSUE TITLE
[Bug]: Firefox has no sound in media.

### ISSUE THREAD

**Issue by Anonymous2716** [termux/termux-packages#12964]
### Problem description

Playing YouTube videos or any other type of media doesn't have any sound. It is Firefox specific because other media players plays just fine. And BTW the performance is way higher than running in any proot-distros.

### What steps will reproduce the bug?

Play media in Firefox web browser.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=UNKNOWN
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5539
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
9
Kernel build information:
Linux localhost 4.4.146 #2 SMP PREEMPT Wed Sep 9 18:47:45 CST 2020 aarch64 Android
```

**Comment by xtkoba** [comment]
This is because `firefox` is configured as such:

https://github.com/termux/termux-packages/blob/79f3818686dc7adba9d4a6b05ab03aaf5e7630dd/x11-packages/firefox/build.sh#L54

**Comment by Anonymous2716** [comment]
@Dendi777 it have to be compiled with that option removed. On device compilation is disabled for Firefox I think. And maybe there are issues related to this. Developers knows better.

**Comment by OrdinaryEnder** [comment]
why not use pulseaudio for this?

**Comment by xtkoba** [comment]
Now PulseAudio backend is enabled:

https://github.com/termux/termux-packages/blob/2e580fc4f32e4583124bc889f25c09bc7cd3ec9b/x11-packages/firefox/build.sh#L48

Can someone please report if sound output actually works?

**Comment by xu3s** [comment]
> Now PulseAudio backend is enabled:
> 
> https://github.com/termux/termux-packages/blob/2e580fc4f32e4583124bc889f25c09bc7cd3ec9b/x11-packages/firefox/build.sh#L48
> 
> Can someone please report if sound output actually works?

i don't know if i downloaded the right artifact but i downloaded it from latest build of firefox but it has no sound coming out.
![Screenshot_20221215_202448](https://user-images.githubusercontent.com/47383486/207870467-ba7bc73b-1d52-442e-a266-26655e83e8c7.jpg)

**Comment by xtkoba** [comment]
@Anonymous2716 The `--enable-audio-backends=pulseaudio` setting is already effective in our official binary packages. Just test e.g. `firefox` version `108.0.1`.

**Comment by 5A52** [comment]
@xtkoba Firefox 108.0.1
`[Child 28620, MediaDecoderStateMachine #1] WARNING: Decoder=7a04bee910 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - Error no decoder found for audio/mp4a-latm: file /home/builder/.termux-build/firefox/src/dom/media/MediaDecoderStateMachineBase.cpp:151`

**Comment by Dendi777** [comment]
Да firefox по прежнему остается без звука также  сопровождается  ошибками в логе

**Comment by Anonymous2716** [comment]
@xtkoba similar error

```
[Child 1459, MediaDecoderStateMachine #1] WARNING: 791f53fd40 Can't get cubeb context!: file /home/builder/.termux-build/firefox/src/dom/media/AudioStream.cpp:252
[Child 1459, MediaDecoderStateMachine #1] WARNING: Decoder=791f477d00 [OnMediaSinkAudioError]: file /home/builder/.termux-build/firefox/src/dom/media/MediaDecoderStateMachine.cpp:4475
```

**Comment by zairullahdev** [comment]
> You don't need to refer to me. I'm not familar with audio system for Termux. I don't even understand why Termux can play sound in the first place. 😦

termux uses openal to make sound output in mpv

**Comment by xtkoba** [comment]
Here is my current knowledge of Android audio.

To support audio devices we have to use directly or indirectly a native audio interface provided by Android. <a href="https://developer.android.com/ndk/guides/audio?hl=en">One is OpenSL ES which is older, and another is AAudio which is newer.</a> Our `pulseaudio` package provides modules for both, and `openal-soft` package supports OpenSL ES.

**Comment by enigma9o7** [comment]
Firefox 109 still has no sound.

Note sound works fine in epiphany, as well as vlc and audacious.

**Comment by Anonymous2716** [comment]
Currently my vlc and parole don't have sound but had before.

**Comment by xtkoba** [comment]
https://github.com/termux/termux-packages/issues/12964#issuecomment-1358902754:

> Error no decoder found for audio/mp4a-latm

This seems to be another issue (a matter of codec rather than audio device support) and is probably not fixed by #15110. Could you please open a new issue for that?

**Comment by xtkoba** [comment]
Should be fixed with `pulseaudio` version `16.1-4`.

Note that PulseAudio is sometimes flaky (in some environment?) and hence it is still possible that occasionally no audio output is made.

Aside from that there seems to be some codec issue, as noted above.

**Comment by xtkoba** [comment]
Turns out that the codec issue is due to `libavcodec.so` (from `ffmpeg`) missing SOVERSION suffix. Pretty much the same as the `pulseaudio` case.

**Comment by xtkoba** [comment]
Also currently `firefox` does not pull in `ffmpeg`. At least `ffmpeg` should be recommended.

**Comment by Anonymous2716** [comment]
@xtkoba as of now my packages are up to date . only MPV works by default and outputs sound but others need to start pulse audio before and now they have sound to . I started pulseaudio with :
```
pulseaudio --start --exit-idle-time=-1
```

**Comment by xtkoba** [comment]
Fix in `ffmpeg` version `5.1.2-5`. Currently manual installation of `ffmpeg` is needed unless it is already installed. Dependency fix for `firefox` will be made in version `110.0`. Thanks.

**Comment by xtkoba** [comment]
@Anonymous2716 Sorry but I'm not familiar with the behavior of PulseAudio. Thanks.

**Comment by xtkoba** [comment]
Please open a new issue if you still have any trouble with audio output after `firefox` version `110.0` is installed. Thanks.

**Comment by Anonymous2716** [comment]
@xtkoba without starting pulseaudio yes . but after starting sound works. So I should open a new one?

**Comment by enigma9o7** [comment]
Thanks, firefox sound working for me now after an update of version 109.

**Comment by Anonymous2716** [comment]
@enigma9o7 check if your pulseaudio is running in the background bcs I don't get any sound output (vlc parole firefox) without starting it manually. My all packages are up to date.

**Comment by enigma9o7** [comment]
I start pulseaudio in my bashrc, I think I did that to get sound in proot...   so yes it should be running in the background whenever  termux is.  Is there some problem with that?

**Comment by Anonymous2716** [comment]
@xtkoba now sound works for all of the mentioned packages thanks.

**Comment by xtkoba** [comment]
See also: #15395 (for future reference)
