### ISSUE TITLE
How to prefix in termux

### ISSUE THREAD

**Issue by Ayaaaaa18** [termux/termux-packages#12973]
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.

I'm having this problem on my termux when updating termux.

**Comment by agnostic-apollo** [comment]
Run `termux-change-repo` to switch to different repo like default and then run `apt update; apt install termux-tools`

Ideally also run `pkg upgrade` afterwards.
