### ISSUE TITLE
[Bug]: Unnecessary stubs for getgrgid_r() and getgrnam_r()

### ISSUE THREAD

**Issue by tavianator** [termux/termux-packages#12974]
### Problem description

getgrgid_r() and getgrnam_r() are stubbed out in `<grp.h>`: https://github.com/termux/termux-packages/blob/42eef081d71e93e49f9c4e4bd93ba4c8d4fb5cc3/ndk-patches/23c/grp.h.patch#L23-L24

This makes them act like no groups exist, leading to wrong/confusing behaviour of utilities that use them.

### What steps will reproduce the bug?

```console
~ $ git clone https://github.com/tavianator/bfs
...
~ $ cd bfs
~/bfs $ make -j$(nproc) EXTRA_CFLAGS="--target=aarch64-unknown-linux-android30"
...
~/bfs $ id -gn
u0_a358
~/bfs $ ./bin/bfs -group $(id -gn)
bfs: error: ./bin/bfs -group u0_a358
bfs: error:           ~~~~~~~~~~~~~~
bfs: error: No such group.
```

### What is the expected behavior?

The group should be found and `bfs` (for example) should list all the files.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
Updatable packages:
apt/stable 2.5.4 aarch64 [upgradable from: 2.5.0]
bash/stable 5.2.9 aarch64 [upgradable from: 5.1.16-1]
ca-certificates/stable 1:2022.10.11 all [upgradable from: 1:2022.03.29]
clang/stable 15.0.4 aarch64 [upgradable from: 15.0.2]
command-not-found/stable 2.1.0-2 aarch64 [upgradable from: 1.75]
coreutils/stable 9.1-2 aarch64 [upgradable from: 9.1]
curl/stable 7.86.0 aarch64 [upgradable from: 7.83.1]
dialog/stable 1.3-20220728-0 aarch64 [upgradable from: 1.3-20220117-0]
dos2unix/stable 7.4.3 aarch64 [upgradable from: 7.4.2]
dpkg/stable 1.21.9 aarch64 [upgradable from: 1.21.7]
findutils/stable 4.9.0-2 aarch64 [upgradable from: 4.9.0-1]
git/stable 2.38.1 aarch64 [upgradable from: 2.38.0]
gpgv/stable 2.3.8 aarch64 [upgradable from: 2.3.6]
grep/stable 3.8-1 aarch64 [upgradable from: 3.7-2]
gzip/stable 1.12-1 aarch64 [upgradable from: 1.12]
krb5/stable 1.20-1 aarch64 [upgradable from: 1.19.3]
ldns/stable 1.8.3-1 aarch64 [upgradable from: 1.8.1-1]
less/stable 608 aarch64 [upgradable from: 590]
libc++/stable 25b aarch64 [upgradable from: 23b-3]
libcompiler-rt/stable 15.0.4 aarch64 [upgradable from: 15.0.2]
libcurl/stable 7.86.0 aarch64 [upgradable from: 7.83.1]
libdb/stable 18.1.40-4 aarch64 [upgradable from: 18.1.40-3]
libevent/stable 2.1.12-2 aarch64 [upgradable from: 2.1.12-1]
libexpat/stable 2.5.0 aarch64 [upgradable from: 2.4.8]
libffi/stable 3.4.4 aarch64 [upgradable from: 3.4.3]
libgcrypt/stable 1.10.1-1 aarch64 [upgradable from: 1.10.1]
libgmp/stable 6.2.1-2 aarch64 [upgradable from: 6.2.1-1]
libgnutls/stable 3.7.8 aarch64 [upgradable from: 3.7.5]
libgpg-error/stable 1.46 aarch64 [upgradable from: 1.45]
libiconv/stable 1.17 aarch64 [upgradable from: 1.16-3]
libidn2/stable 2.3.4 aarch64 [upgradable from: 2.3.2]
libllvm/stable 15.0.4 aarch64 [upgradable from: 15.0.2]
liblz4/stable 1.9.4 aarch64 [upgradable from: 1.9.3]
liblzma/stable 5.2.7 aarch64 [upgradable from: 5.2.5-1]
libnettle/stable 3.8.1 aarch64 [upgradable from: 3.7.3]
libnghttp2/stable 1.50.0 aarch64 [upgradable from: 1.47.0]
libresolv-wrapper/stable 1.1.7-3 aarch64 [upgradable from: 1.1.7-2]
libtirpc/stable 1.3.3 aarch64 [upgradable from: 1.3.2-1]
libunistring/stable 1.1 aarch64 [upgradable from: 1.0]
lld/stable 15.0.4 aarch64 [upgradable from: 15.0.2]
llvm/stable 15.0.4 aarch64 [upgradable from: 15.0.2]
lsof/stable 4.96.4 aarch64 [upgradable from: 4.95.0-1]
make/stable 4.4 aarch64 [upgradable from: 4.3-2]
ncurses/stable 6.3-5 aarch64 [upgradable from: 6.3-1]
ndk-sysroot/stable 25b-1 aarch64 [upgradable from: 25b]
nmap-ncat/stable 7.93 aarch64 [upgradable from: 7.92-2]
nmap/stable 7.93 aarch64 [upgradable from: 7.92-2]
openssh-sftp-server/stable 9.1p1 aarch64 [upgradable from: 9.0p1-2]
openssh/stable 9.1p1 aarch64 [upgradable from: 9.0p1-2]
openssl-1.1/stable 1:1.1.1s aarch64 [upgradable from: 1.1.1o]
openssl-tool/stable 1:3.0.7 aarch64 [upgradable from: 3.0.5]
openssl/stable 1:3.0.7 aarch64 [upgradable from: 3.0.5]
procps/stable 3.3.17-2 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.5-1 aarch64 [upgradable from: 23.4]
readline/stable 8.2.1 aarch64 [upgradable from: 8.1.1]
rsync/stable 3.2.7 aarch64 [upgradable from: 3.2.6]
sed/stable 4.9 aarch64 [upgradable from: 4.8-2]
tar/stable 1.34-1 aarch64 [upgradable from: 1.34]
termux-am-socket/stable 1.5.0 aarch64 [upgradable from: 1.3.0]
termux-keyring/stable 3.10 all [upgradable from: 3.4]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-2]
termux-tools/stable 1.31.0 all [upgradable from: 0.180]
unbound/stable 1.16.3-1 aarch64 [upgradable from: 1.15.0-1]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-7]
util-linux/stable 2.38.1 aarch64 [upgradable from: 2.38]
xz-utils/stable 5.2.7 aarch64 [upgradable from: 5.2.5-1]
zlib/stable 1.2.13 aarch64 [upgradable from: 1.2.12]
termux-tools version:
0.180
Android version:
13
Kernel build information:
Linux localhost 5.10.107-android13-4-00004-gf0fe4f768061-ab8935229 #1 SMP PREEMPT Thu Aug 11 01:16:28 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 6 Pro
```

**Comment by Grimler91** [comment]
Good catch, that could have been removed when we dropped support for < api-level 24

**Comment by xtkoba** [comment]
This is introduced in commit 88695dba79f03301ed0ddf5d8d0ec4877c898e8c and is a legacy of era when Termux supported Android API 21 (Lollipop). As `getgrgid_r` and `getgrnam_r` have been introduced in API 24, these stubs should be removed.

**Comment by tavianator** [comment]
What's the current minimum API level supported?  I quickly looked through the rest of the patches and found these:

https://github.com/termux/termux-packages/blob/42eef081d71e93e49f9c4e4bd93ba4c8d4fb5cc3/ndk-patches/23c/langinfo.h.patch#L100-L103

https://github.com/termux/termux-packages/blob/42eef081d71e93e49f9c4e4bd93ba4c8d4fb5cc3/ndk-patches/23c/linux-fcntl.h.patch#L7-L8

https://github.com/termux/termux-packages/blob/42eef081d71e93e49f9c4e4bd93ba4c8d4fb5cc3/ndk-patches/23c/stdlib.h.patch#L14-L17

**Comment by xtkoba** [comment]
Current minimum supported API is 24. The `nl_langinfo` hack in `langinfo.h` is needed.

The `MB_CUR_MAX` hack in `stdlib.h` is needed for a bug of `setlocale()` in API 24, though this acts badly in some cases and the behavior is "reverted" in some packages (e.g. `grep` and `sed`).

Not sure for the `AT_EACCESS` hack.

**Comment by tavianator** [comment]
> > Not sure for the AT_EACCESS hack.
> 
> Related to comment in https://android.googlesource.com/platform/bionic.git/+/refs/tags/ndk-r23b/libc/bionic/faccessat.cpp#46

Yeah, I worked around that in bfs a while ago: https://github.com/tavianator/bfs/blob/main/src/bfstd.c#L403-L415

**Comment by tavianator** [comment]
> Current minimum supported API is 24. The `nl_langinfo` hack in `langinfo.h` is needed.

Why is it needed?  I assume termux packages are built with `__ANDROID_API__ == 24`, so the prototypes should be hidden anyway.  If I'm building something on my phone with `--target=aarch64-unknown-linux-android26` explicitly, those prototypes should be okay right?

However, it looks like this patch isn't even used, and https://github.com/termux/termux-packages/blob/master/ndk-patches/langinfo.h is used instead.

> The `MB_CUR_MAX` hack in `stdlib.h` is needed for a bug of `setlocale()` in API 24, though this acts badly in some cases and the behavior is "reverted" in some packages (e.g. `grep` and `sed`).

Well, 4 is correct for UTF-8 anyway so I don't mind :)

**Comment by xtkoba** [comment]
Yeah, the patch for `langinfo.h` is to make it an empty file. I wonder if it is really needed. Looks like redundant to me. Not harmful though I suppose.
