### ISSUE TITLE
[Packages support]Java-8-jdk for aarch64

### ISSUE THREAD

**Issue by 7sp0th** [termux/termux-packages#1298]
I ported a Java-8-jdk from Neoterm(@zt515). I will show you how to install it.

1. _wget http://ftp6196662.host601.zhujiwu.me/java-8-jdk.tgz_ 

2. _tar -xvzf java-8-jdk.tgz_

3. _cp  -rf usr $HOME/../_ 

4. _rm -rf usr_ 

Than,you can enjoy the java-8-jdk.

I am not good at English,please forgive me.     

@fornwall

**Comment by fornwall** [comment]
Hello! You can post this as a tip at https://plus.google.com/communities/101692629528551299417!

For inclusion as a Termux package we would need to have the build steps and patches available in order to build it ourselves.

**Comment by Harshiv-Patel** [comment]
Is there an ARM support?

**Comment by TheDiamondYT1** [comment]
Java 8 would be great! Java 9 breaks everything currently.

**Comment by TheDiamondYT1** [comment]
@fornwall This appears to be openjdk9, like we already have in Termux :(

**Comment by TheDiamondYT1** [comment]
Nevermind, already had openjdk9 installed in PATH somewhere else.

**Comment by sdrausty** [comment]
@TheDiamondYT1 "like we already have in Termux," cannot find openjdk* in the termux.net repo. Where is it?

**Comment by TheDiamondYT1** [comment]
@sdrausty Disabled packages.

**Comment by sdrausty** [comment]
@TheDiamondYT1 How to install from disabled packages?

**Comment by TheDiamondYT1** [comment]
@sdrausty No idea. I downloaded an outdated deb from a link in a PR.

**Comment by TheDiamondYT1** [comment]
@7sp0th NeoTerm doesn't have openjdk8, only 9. Also i can't get it to recognize the java binary is an executable, and it says it is not found.

**Comment by jxjhheric** [comment]
@7sp0th  资源被删除 能再共享下吗 谢谢

**Comment by sdrausty** [comment]
@7sp0th  Java is available through:
# [TermuxArch](https://github.com/sdrausty/TermuxArch)

Now you can install Arch Linux in Termux 📲 on your smartphone and tablet. More information at https://sdrausty.github.io/TermuxArch

Java is available through https://sdrausty.github.io/TermuxArch/ Just follow the easy install instructions at https://sdrausty.github.io/TermuxArch/docs/docs/install or simply run the following in you Termux window:

```
cd && git clone https://github.com/sdrausty/TermuxArch
./TermuxArch/setupTermuxArch.sh
```
Read more about the Arch Linux package manager at [duckduckgo arch+linux+install+java+pacman.](https://duckduckgo.com/?q=arch+linux+install+java+pacman&atb=v90-2__&t=cros&ia=qa)

To install java run `pacman -Syy; pacman -Su; pacman -S jdk8-openjdk`


![screenshot_20171109-220204](https://user-images.githubusercontent.com/27742457/32641053-cedfdcfe-c599-11e7-9c73-b185e70e9c6a.png)

**Comment by SeAL80s** [comment]
@7sp0th Can you post how you build jdk8 ? The link you provided is no longer accessible.Did you build from openjdk ? 能方便说下怎么做的jdk8.tgz吗？链接失效了，如果是国内的，发下网盘链接或者能发邮箱一份吗？SeAL80s@163.com（gmail一般不让发附件）
@fornwall Why the oracle JDK wouldn't work ? 'jdk-8u171-linux-arm64-vfp-hflt.tar.gz' and 'ejdk-8u171-linux-armv6-vfp-hflt.tar.gz' . $jdk1.8.0_171/bin/javac will show 'no such file or directory' even with the full path .

**Comment by P-A-I-N** [comment]
bad address 'ftp6196662.host601.zhujiwu.me'
