### ISSUE TITLE
Python's subprocess module defaults to /bin/sh

### ISSUE THREAD

**Issue by MatthewTurk** [termux/termux-packages#13]
The subprocess module in python2 defaults to using `/bin/sh`, which should be `/data/data/com.termux/files/usr/bin/sh`.  I'm prepping a PR to add a patch to the `subprocess.py` file once I can test it.

**Comment by fornwall** [comment]
Thanks a lot - I've added a patch for subprocess.py and pushed a fixed package (version 2.7.10-1) to the repo. See if you agree with the patch and check if it works for you!

Also, let me know if there is anything I can do to help getting locally built packages working!
