### ISSUE TITLE
[Bug]: Firefox homepage fails to load

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#13013]
### Problem description

Last two releases of Firefox have had the failure of the default homepage failing to load. I have done a clean reinstall, including the deletion of .cache, .config .mozilla files etc....  

### What steps will reproduce the bug?

Launch Firefox.
This is the result:-
![Screenshot_20221111-214550](https://user-images.githubusercontent.com/4559048/201365397-4d7a1e51-d8d5-4a7f-b7b0-766fc0b185be.jpg)

### What is the expected behavior?

Homepage is displayed.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=13006
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.utermux.dev/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.utermux.dev/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.utermux.dev/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Fri Nov 26 00:14:01 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003

```

**Comment by macerg** [comment]
To clarify, the 'default' Firefox homepage usually has a table of applet links to various common sites like Amazon, Wikipedia, YouTube etc...... You can tailor this for your own preferences.


Additionally, I have gone through a fresh install after an apt remove firefox --purge. I deleted anything to do with Firefox (.cache,. mozilla etc) before the reinstall. Still experiencing the same issue.

**Comment by T-Dynamos** [comment]
![Screenshot_2022-11-12-13-24-52-717_com realvnc viewer android](https://user-images.githubusercontent.com/68729523/201464699-5d19b98a-10cb-4a46-a5f0-b48d01787705.jpg)
This seems firefox issue

**Comment by macerg** [comment]
Indeed! "A Firefox issue". That's what I raised it as! I assume you mean a coding issue within the application?Regards,Richard Mace Can that be followed up with the developers?On 12 Nov 2022 14:58, Ansh Dadwal ***@***.***> wrote:

This seems firefox issue

**Comment by macerg** [comment]
I've downgraded to firefox_105.0.3_aarch64.deb which works fine!

**Comment by xtkoba** [comment]
I personally won't fix this because I have no idea how to debug this and IIUC this does not make `firefox` totally unusable. I do not recommend downgrading `firefox` solely for the purpose of working this around because a newer version almost always includes security fixes.

**Comment by macerg** [comment]
Ok, fair enough.
