### ISSUE TITLE
[Package]: websocketd: any command as websocket server, thus interactive app with html5

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-packages#13029]
### Why do you want to add this package to Termux?

websocketd makes any STDIN/STDOUT command a websocket server, thus make the console command an interactive web application with a little html5.

### Source code URL

https://github.com/joewalnes/websocketd

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Already packaged (145015b8fc433edae81e428a8ee4378ba1019695). Closing.
