### ISSUE TITLE
aapt is not working!

### ISSUE THREAD

**Issue by Droid-MAX** [termux/termux-packages#1304]
![s70823-011014](https://user-images.githubusercontent.com/12762435/29577938-fbfa5ade-8732-11e7-8544-3825e5f4c828.jpg)

**Comment by sdrausty** [comment]
@Droid-MAX Did you update before installing? What is your OS and arch?
![screenshot_20170822-132138](https://user-images.githubusercontent.com/27742457/29578317-da05ed94-873c-11e7-83f2-ee860752b2e9.png)

**Comment by fornwall** [comment]
@Droid-MAX Can you try updating with `pkg up` and see if the latest version fixes your problem?

Which Android version do you run?
