### ISSUE TITLE
AAPT fails after latest update.

### ISSUE THREAD

**Issue by Harshiv-Patel** [termux/termux-packages#1306]
`$ aapt`
gives:

CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "__android_log_error_write" referenced by "libandroid-ziparchive.so"...

error, I have tried apt update && apt upgrade.
Android version: Lollipop 5.1.1, I'm on ARM, cpuArch:armv7l

**Comment by fornwall** [comment]
@Harshiv-Patel Can you update to the latest version (7.1.2.33-1) of aapt (by running `pkg up`) and see if that fixes the problem?

I suspect that the problem is specific to Android 5.x.

**Comment by Harshiv-Patel** [comment]
Yes indeed! 
The latest update fixes this issue.
