### ISSUE TITLE
erroneous bash completions

### ISSUE THREAD

**Issue by brbsix** [termux/termux-packages#1308]
To illustrate the issue, enter the following:
`ping` + <kbd>Space</kbd> + <kbd>Tab</kbd>

Note that the results erroneously include the completions "No" and "Command". This arises from the `_known_hosts_real` helper function (used to provide host completions for commands like curl, dig, ftp, nc, nmap, nslookup, ssh, telnet, tracepath, traceroute, wget and many others) in the bash-completion package when it attempts to run the `ruptime` command which is obviously not available. I think on most systems (mine at least), running `ruptime 2>/dev/null` results in no output. On Termux however, it outputs the following:

> No command 'ruptime' found, did you mean:
>  Command 'uptime' from package 'procps'

I think this behavior is unexpected and will cause problems in other scripts as well. The quick and easy solution is to remove the following section from the `_known_hosts_real` function:

    # Add hosts reported by ruptime.
    COMPREPLY+=( $( compgen -W \
        "$( ruptime 2>/dev/null | awk '!/^ruptime:/ { print $1 }' )" \
        -- "$cur" ) )

So long as there are not some other side-effects, I assume the proper solution would be to ensure all output from `command-not-found` is redirected to stderr.

**Comment by fornwall** [comment]
> So long as there are not some other side-effects, I assume the proper solution would be to ensure all output from command-not-found is redirected to stderr.

Agreed, sounds reasonable and is what the command-not-found handler does on e.g. Debian. This is now implemented in version 1.25 of the `command-not-found` package, to which you can update to with `pkg up`. Does that fix the problem?

**Comment by brbsix** [comment]
That fixed it, thank you!
