### ISSUE TITLE
$ termux-chroot $ cd lm-sensors $ make Segmentation fault $

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1309]
```
$ termux-chroot
$ cd lm-sensors
$ make
Segmentation fault
$
```

To reproduce this segmentation fault, run the following:
```
termux-chroot
git clone https://github.com/groeck/lm-sensors
cd lm-sensors
make
```
Termux-packages arch:
aarch64
Android version:
6.0.1

![screenshot_20170824-231039](https://user-images.githubusercontent.com/27742457/29698197-c7df0a92-8921-11e7-89f4-600ccefc7bcd.png)

**Comment by fornwall** [comment]
@michalbednarski Do you want to have a look at this proot problem?

**Comment by michalbednarski** [comment]
Doesn't appear to reproduce on emulator (`make` works fine, however I found that `git` appears to have problems)

1. Make sure that you haven't nested `termux-chroot` (Can happen if you launch it from `.bashrc` and then start another shell)
2. What's your kernel version (`uname -a`)
3. Try using `PROOT_NO_SECCOMP=1 termux-chroot` and let me know if it works then
4. Check if just running `proot make` (without `termux-chroot`) from that directory is enough to cause segfault
5. If 4. still causes segfault please run following code and attach `proot-log.txt`
```
proot -v 9 make > proot-log.txt 2>&1
```

**Comment by sdrausty** [comment]
@michalbednarski 
```
$ uname -a
Linux localhost 3.10.84-perf-gcdba782-00725-g9a1b90d #1 SMP PREEMPT Wed Aug 2 13:48:17 CST 2017 aarch64 Android
$ PROOT_NO_SECCOMP=1 termux-chroot
$ cd lm-sensors/
$ make
Segmentation fault
$ exit
logout
$ proot make
proot info: vpid 1: terminated with signal 11
```
https://sdrausty.github.io/logs/proot-log.txt

However, simple with no chroot produces:
`make: *** No rule to make target 'langinfo.h', needed by 'prog/sensors/main.rd'.  Stop.`
![screenshot_20170825-234407](https://user-images.githubusercontent.com/27742457/29738391-5e60636c-89ef-11e7-901a-77ac0213907e.png)

**Comment by michalbednarski** [comment]
Looks like some assertion failed after first child process completed (after finished `wait4` for `uname -m` make connects to system log (`logcat`), `make` during my test on emulator here didn't use system log (haven't anything to log)).

In order to continue debugging I'd need you to

1. Try with following `Makefile` (put it in new empty directory)
```
MACHINE := $(shell uname -m)
```
(If this file was enough to reproduce segfault continue further steps using this directory,
If it says "`make: *** No targets.  Stop.`" return to `lm-sensors` `Makefile`)

2. Run `make` under `strace` under `proot` and send me result (whenever it works or not)
``` 
proot strace -vs50000 -fo proot-make-trace.txt make
```

3. In case of `make` working correctly in 2. also send system logs (If problem reproduced in 2. traces will already contain these logs)
```
logcat -c
make
logcat -d > proot-make-logcat.txt
```
(`logcat -c` clears log, `logcat -d` prints existing logs and exits without waiting for new ones to come)

**Comment by sdrausty** [comment]
@michalbednarski Thank you for your time and guidance.
```
$ mkdir new
$ cd new
$ vi Makefile
$ make
make: *** No targets.  Stop.
$
```
```
$ cd lm-sensors/
$ proot strace -vs50000 -fo proot-make-trace.txt make
proot info: vpid 1: terminated with signal 11
$ 
```
Output at https://sdrausty.github.io/logs/proot-make-trace.txt 🙂

**Comment by michalbednarski** [comment]
I think I've fixed this, please test:

[proot_5.1.106-2_aarch64.zip](https://github.com/termux/termux-packages/files/1254588/proot_5.1.106-2_aarch64.zip) (unzip and install with `dpkg -i`)

[Source on `vfork-exec-heap` branch (diff)](https://github.com/termux/proot/commit/6671bfed4ddcbd393d8ca7b2754d58e41ed9595b)

If everything is ok then this will be pushed to main repo

**Comment by sdrausty** [comment]
@michalbednarski Thank you for the update. 
```

$ unzip ../proot_5.1.106-2_aarch64.zip
Archive:  ../proot_5.1.106-2_aarch64.zip
  inflating: proot_5.1.106-2_aarch64.deb  
$ dpkg --install proot_5.1.106-2_aarch64.deb
(Reading database ... 91366 files and directories currently installed.)
Preparing to unpack proot_5.1.106-2_aarch64.deb ...
Unpacking proot (5.1.106-2) over (5.1.106-2) ...
Setting up proot (5.1.106-2) ...
Processing triggers for man (1.14.3) ...
$ cd lm-sensors/
$ make
/data/data/com.termux/files/usr/bin/sh: 1: /sbin/ldconfig: Permission denied
make: *** No rule to make target 'langinfo.h', needed by 'prog/sensors/main.rd'.  Stop.
$ proot strace -vs50000 -fo proot-make-trace.txt make
/data/data/com.termux/files/usr/bin/sh: 1: /sbin/ldconfig: not found
make: *** No rule to make target 'langinfo.h', needed by 'prog/sensors/main.rd'.  Stop.
$ termux-chroot
$ cd lm-sensors/
$ make
/data/data/com.termux/files/usr/bin/sh: 1: /sbin/ldconfig: not found
make: *** No rule to make target 'langinfo.h', needed by 'prog/sensors/main.rd'.  Stop.
$
```
Looks like this issue is resolved. Thank you 🙂
