### ISSUE TITLE
Weird problem when run "python -v" [Bug]

### ISSUE THREAD

**Issue by Agono0** [termux/termux-packages#13098]
### Problem description

![20221114_215001](https://user-images.githubusercontent.com/100796146/201752430-1e4d8e2b-4ce1-46de-be8c-3ed494fccdc0.jpg)

I just need to know is this normal or not 😅

### What steps will reproduce the bug?

Just try "python-v" or "exit()" from python interpreter

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=8285
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
9
Kernel build information:
Linux localhost 3.18.91-16526088 #1 SMP PREEMPT Fri May 28 23:13:01 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J730F
```

**Comment by MrAdityaAlok** [comment]
`python -v` means verbose mode, so it displays all the steps it took to start cli.
Use `python -V (capital)` if you want version.
