### ISSUE TITLE
[Package]: rust-std-wasm32-wasi

### ISSUE THREAD

**Issue by xJonathanLEI** [termux/termux-packages#13117]
### Why do you want to add this package to Termux?

Rust in Termux is not managed by `rustup`. Additional targets are added as `rust` subpackages like `rust-std-wasm32` for target `wasm32-unknown-unknown`. It would be nice to also support the increasingly popular `wasm32-wasi` target as well.

### Home page URL

https://www.rust-lang.org/

### Source code URL

https://github.com/rust-lang/rust

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by ebenali** [comment]
bump this

i will end up doing this if nobody else does
