### ISSUE TITLE
[Bug]: mailutils build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#13146]
### Problem description

[mailutils.txt](https://github.com/termux/termux-packages/files/10024218/mailutils.txt)

make[3]: Entering directory '/alsultan/.termux-build/mailutils/build/lib'
  CC       script.o
  CC       sieve.o
  CC       python.o
  CC       tcpwrap.o
  CC       mailcap.lo
  CC       manlock.lo
  CC       mdecode.lo
  CC       signal.lo
  CC       strexit.lo
  CC       mu_umaxtostr.lo
  CC       unistr_c.lo
In file included from /alsultan/.termux-build/mailutils/src/lib/python.c:20:
In file included from /usr/include/python3.10/Python.h:8:
/usr/include/python3.10/pyconfig.h:9:12: fatal error: 'aarch64-linux-gnu/python3.10/pyconfig.h' file not found
#  include <aarch64-linux-gnu/python3.10/pyconfig.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  AR       libmutcpwrap.a
1 error generated.
make[3]: *** [Makefile:1157: python.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/alsultan/.termux-build/mailutils/build/lib'
make[2]: *** [Makefile:1232: all-recursive] Error 1
make[2]: Leaving directory '/alsultan/.termux-build/mailutils/build/lib'
make[1]: *** [Makefile:1149: all-recursive] Error 1
make[1]: Leaving directory '/alsultan/.termux-build/mailutils/build'
make: *** [Makefile:1034: all] Error 2

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Not reproducible in CI. Simply adding `python` to `TERMUX_PKG_BUILD_DEPENDS` does not trigger this.

**Comment by xtkoba** [comment]
@johndebia2022 Please check if this still occurs with `mailutils` version `3.15-1`.

**Comment by johndebia2022** [comment]
> @johndebia2022 Please check if this still occurs with `mailutils` version `3.15-1`.

Thanks issue resolved now
