### ISSUE TITLE
[Bug]: binutils-is-llvm doesn's symlink as to llvm-as

### ISSUE THREAD

**Issue by OldWorldOrdr** [termux/termux-packages#13177]
### Problem description

binutils-is-llvm is supposed to provide symlinks to use llvm commands as replacements for binutils commands, for example making a symlink to `llvm-ar` named `ar`, however it doesn't symlink `as` to `llvm-as`

### What steps will reproduce the bug?

install binutils-is-llvm
attempt to run `as`
command not found :(

### What is the expected behavior?

the command to work

### System information

Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.31.1
Android version:
13
Kernel build information:
Linux localhost 4.19.239-g248fa42a73b2-ab9062766 #1 SMP PREEMPT Wed Sep 14 05:22:28 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 5

**Comment by xtkoba** [comment]
This is because `llvm-as` is pretty much different from GNU as.

**Comment by xtkoba** [comment]
If we symlink `bin/as` to `bin/llvm-as` then Clang's `-fno-integrated-as` will not work as expected.

`bin/as` is provided by `binutils-bin` which does not collide with `binutils-is-llvm`.
