### ISSUE TITLE
package request: rcs

### ISSUE THREAD

**Issue by dogear42** [termux/termux-packages#1320]
I know!  I'm so old school.

However, I have a use case where I have 1 file I need to revision control, and I would rather use a simple second text file as my revision control mechanism instead of the bloat that is git.  Also, cvs doesn't do it for me, as I don't want to use nested directories.

Thanks!

**Comment by fornwall** [comment]
Thanks to @its-pointless there is now a package available for installation: `pkg install rcs`.

**Comment by dogear42** [comment]
Thanks!  Fantastic!
