### ISSUE TITLE
`libc++` bundled with NDK is behind the latest upstream version

### ISSUE THREAD

**Issue by Sirox228** [termux/termux-packages#13247]
### Problem description

i need to use `numbers` header in my C++ program (this header was added in C++20), but whenever i try to include it, either with `-std=c++20` flag or without it, same `'numbers' file not found` error occurs, also `numbers` is not the only header that can't be found, there're lots of others, `ranges` for example have this issue too. (maybe problem is in sysroots?)

### What steps will reproduce the bug?

```
touch a.cpp
nano a.cpp
```
fill with:
```
#include <iostream>
#include <numbers>

int main(int argc, char** argv) {
  const long double pi = std::numbers::pi_v<long double>;
  std::cout << pi << std::endl;
}
```
compile it
```
clang++ a.cpp -std=c++20
```

### What is the expected behavior?

it should compile normally when `-std=c++20` flag is there and this program should output math PI

### System information

termux-info:

```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.49
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~lxE7n4SelLY6WFMQ4U9vGg==/com.termux-5oWNdFRwkWmKaQqM5RKyeA==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=2293
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c28,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c28,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10284
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+be66cff
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+be66cff
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.scau.edu.cn/termux/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device
Updatable packages:
All packages up to date
termux-tools version:
1.31.1
Android version:
11
Kernel build information:
Linux localhost 4.19.113-perf-ga8eb9aa #1 SMP PREEMPT Wed Jun 2 02:09:57 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
POCO F2 Pro
```

**Comment by ABDAH73** [comment]
- - ~~~~

**Comment by xtkoba** [comment]
I suppose this is partly because our `libc++` is bound to the latest stable NDK version. The source code for LLVM 15.0.6 seems to include these header files (which does not necessarily mean that they are actually installed and usable though.)

Sorry but we have no plan to improve the situation for now.

**Comment by xtkoba** [comment]
FYI, the list of C++ header files in LLVM 15.0.6 that are missing from Android NDK r25b:

* `<coroutine>`
* `<cuchar>`
* `<format>`
* `<numbers>`
* `<ranges>`

**Comment by Grimler91** [comment]
We use android-ndk's libc++ (and other system libs), and will probably continue to do so.  Consider opening an issue at github.com/android/ndk to see when full c++20 support is planned to be added.

**Comment by SainoNamkho** [comment]
> We use android-ndk's libc++ (and other system libs), and will probably continue to do so. Consider opening an issue at github.com/android/ndk to see when full c++20 support is planned to be added.

I found is has been updated from the ndk repo: https://github.com/android/ndk/wiki/Changelog-r26, does it mean we'll get newer version of libc++ recently?
Wishes.
