### ISSUE TITLE
PHP package doesn't build libunwind as a dependency yet linker script requires it causing dynamic linking error

### ISSUE THREAD

**Issue by ClosetMonkey** [termux/termux-packages#1328]
**Original title:** "libstdc++.so" is too small to be an ELF executable:

This is my first attempt to cross-compile using termux-packages. I cross-compiled PHP and once it was moved to device I got the error '"libstdc++.so" is too small to be an ELF executable:'. I assumed that it might have been a broken symbolic link but it wasn't, it was a text file that contained the text `INPUT(-lunwind -lc++_shared)` and nothing else. After searching the repository I came across this: https://github.com/termux/termux-packages/blob/0dc547ae70b82a97a0c4949ea1e1b4d38f642037/build-package.sh#L718 I'm clueless of what it is, but I guessed that it somehow copied libc++_shared.so to libstdc++.so so I deleted libstdc++.so and copied libc++_shared.so to libstdc++.so in /data/data/com.termux/files/usr/lib and it now works (at least, it is working without having yet used any form of executable that links to c++ (PHP is written in C and I changed the build.sh to disable all extensions) . Obviously this can't be the right fix

**Comment by fornwall** [comment]
The `libstdc++.so` file should only be used in the cross-compiling environment, and never end up in a package on a device!

[This line in build-package.sh](https://github.com/termux/termux-packages/blob/master/build-package.sh#L959) should exclude `libstdc++.so` from ending up in the built package. Do you have any idea why it wouldn't work for you?

**Comment by ClosetMonkey** [comment]
No idea per se, but I'm guessing that it might be that I copied the /data/data/com.termux folder from my host (Ubuntu 17) to my devices /data/data dir rather than using the generated .deb files (don't have dpkg or apt on my phone - figuring I'd do this one step at a time)

**Comment by ClosetMonkey** [comment]
I'm planing on deploying some termux packages within my own .apk. I've been using musl-libc when I cross-compile for Android which leaves me high and dry when it comes to Android specific APIs

**Comment by fornwall** [comment]
> No idea per se, but I'm guessing that it might be that I copied the /data/data/com.termux folder from my host (Ubuntu 17) to my device's /data/data dir rather than using the generated .deb files (don't have dpkg or apt on my device - figuring I'd do this one step at a time)

Ok, this seems to be the problem then! It's not safe to do that as shown by this issue - only the built package is safe to install on the device.

Let me know if there is anything I can do to help with cross compiling!

**Comment by ClosetMonkey** [comment]
I think I got it figured out. Thanks!

**Comment by ClosetMonkey** [comment]
I hope to port over a few different PHP extensions such as ptheads so you'll likely hear more from me.
