### ISSUE TITLE
apt-get update not updating

### ISSUE THREAD

**Issue by mklein994** [termux/termux-packages#133]
When I run apt-get update, it doesn't seem to update the package list. I've manually updated apt  from termux.net, reinstalled the app, and am still having the same problems. Sometimes it also complains that it can't find /data/data/com.termux/files/usr/lib/apt/methods/store. I can still install packages though. I've attached an strace of this.

[apt-get_strace_2016-02-01.txt](https://github.com/termux/termux-packages/files/113235/apt-get_strace_2016-02-01.txt)

**Comment by fornwall** [comment]
- What is the output from apt?
- Which device and Android version is this?
- Could you re-run strace with the -f option and make the trace available?

Thanks for the help!

**Comment by mklein994** [comment]
Sorry for the lack of detail. I'm running CyanogenMod 12.1 (Android 5.1.1) on a Samsung Galaxy SIII. I re-ran the strace, and cancelled when timed out:
[apt-get_strace.txt](https://github.com/termux/termux-packages/files/114350/apt-get_strace.txt)

Here's the output of apt-get update:

```
$ apt-get update
Get:1 http://termux.net stable InRelease [1875 B]
Get:2 http://termux.net stable/main all Packages [1532 B]
Get:3 http://termux.net stable/main arm Packages [37.5 kB]
93% [Working]^C
$
```

I cancelled because it was hanging at 93%. Just a note, I've tried to troubleshoot this by running `rm -rvf $PREFIX/var/lib/apt/lists/*`. Anything else I can do?

**Comment by fornwall** [comment]
@mklein994 Could you try to install the following experimental apt package:

    wget http://fornwall.net/apt_1.2.1_arm.deb
    dpkg -i apt_1.2.1_arm.deb

which adds the missing `methods/store` and then try to run `apt update` again after?

**Comment by mklein994** [comment]
It worked! Thanks so much!

**Comment by fornwall** [comment]
@mklein994 Great, thanks for your help in finding the problem, let me know if there are any more issues!

The updated apt package `1.2.1-1` has been pushed to the apt repo.
