### ISSUE TITLE
Package request: gpsd

### ISSUE THREAD

**Issue by robinpaulson** [termux/termux-packages#1330]
gpsd is licensed under BSD and from what I gather, it is incorporated into proprietary code when it is included in Android - at least for my Samsung Galaxy S3 anyway.

I use Replicant, a free software (proprietary blobs removed) derivative of Android, hence gpsd is not included. It would be great to get a vanilla version of gpsd added to termux so I and other Replicant users can use gps devices.

There are build instructions included for Android, it requires the NDK, scons and python to build:
https://git.savannah.gnu.org/cgit/gpsd.git/tree/build.txt#n431

**Comment by deviskra** [comment]
Hello! Have any body found a way to install gpsd on Android?

**Comment by herbsmn** [comment]
@deviskra maybe you could use the Guix package manager to install gpsbabel https://www.gnu.org/software/guix/blog/2018/guix-on-android/ https://redmine.replicant.us/issues/1479#note-6

**Comment by sunshinertoo** [comment]
I can get the GPS data live stream out of android into termux with the app BlueNMEA, and sent that stream over cellular connection to my PC at home, with netcat.

I still have to find out how to push that data into gpsd programs. I am new in GPS programs.

Also there is this termux command "termux-location", it gives a one-shot current location data, so the device node is accessible (don't know whether I am root or not).
