### ISSUE TITLE
erlang problem or rebar3 problem

### ISSUE THREAD

**Issue by zlfera** [termux/termux-packages#1331]
I can install erlang on Termux, and it works well. but when i install rebar3 in the Termux, the rebar3 did not run. this is the error message
"zsh: /data/data/com.termux/files/usr/bin/rebar3: bad interpreter: /usr/bin/env: no such file or directory".

**Comment by Grimler91** [comment]
This is because termux is a [prefixed environment](https://wiki.termux.com/wiki/Main_Page#Prefixed_System), you will need to change the shebang of the rebar3 file from `/usr/bin/env` to `/data/data/com.termux/files/usr/bin/env`. See the link for more information.
