### ISSUE TITLE
[Package]: yt-dlp

### ISSUE THREAD

**Issue by Toni500github** [termux/termux-packages#13361]
### Why do you want to add this package to Termux?

because since it's a fork of youtube-dl that fix bugs and add additional features, it's really great for downloading youtube videos and faster

### Source code URL

https://github.com/yt-dlp/yt-dlp

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Are there any issues installing it from pip?

**Comment by Toni500github** [comment]
> Are there any issues installing it from pip?

No problems I saw when installing on pip

**Comment by Grimler91** [comment]
Then please install through pip. See relevant section of [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy):

> ### Not installable through cpan, gem, npm, or pip
> 
> These packages should be installed through cpan, gem, npm, pip and so on.
