### ISSUE TITLE
Package request: hunspell-nl

### ISSUE THREAD

**Issue by bklaase** [termux/termux-packages#1336]
Should be using this source:
https://cgit.freedesktop.org/libreoffice/dictionaries/plain/nl_NL/

package could almost be a complete copy of:
https://github.com/termux/termux-packages/blob/master/packages/hunspell-ru/build.sh

**Comment by lezsakdomi** [comment]
Just commenting here that i'd appreciate the same in Hungarian (i.e. hunspell-hu)
