### ISSUE TITLE
[Package]: python-pip

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#13397]
### Why do you want to add this package to Termux?

Due to changes in the policy of adding packages to termux, I suggest adding python-pip as it is a core python module and cannot be installed via pip.

_PS: I draw your attention to the fact that to some extent this is a joke.  If you think it's unnecessary, then close it as a joke.  But if you think it's useful, then let's get started :)_

### Source code URL

https://github.com/pypa/pip

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by OrdinaryEnder** [comment]
It's just make life harder, just stick to the default python with pip included

**Comment by Maxython** [comment]
> It's just make life harder, just stick to the default python with pip included

In theory, no. Only the installation steps will change, namely a separate installation of pip (which is a kind of standard).

**Comment by OrdinaryEnder** [comment]
> In theory, no. Only the installation steps will change, namely a separate installation of pip (which is a kind of standard).

People always install python and have pip in default

**Comment by Maxython** [comment]
> > In theory, no. Only the installation steps will change, namely a separate installation of pip (which is a kind of standard).
> 
> People always install python and have pip in default

With the help of additional actions (that is, scripts in packages) after installing python (https://github.com/termux/termux-packages/blob/master/packages/python/build.sh#L90).
