### ISSUE TITLE
tinyscheme PIE error

### ISSUE THREAD

**Issue by smotti** [termux/termux-packages#134]
The tinyscheme package doesn't work. Starting the interpreter fails with:

```
error: only position independent executables (PIE) are supported
```

This seems to be easily fixable by adding the proper CFLAGS and LDFLAGS to the makefile:

```
CFLAGS = -fPIE
LDFLAGS = -fPIE -pie
```

I'm running Android 6.0.1, and it's the first package I encountered the issue.

**Comment by fornwall** [comment]
Thanks, fixed and pushed to the apt repo, install the update with `apt update && apt upgrade`!
