### ISSUE TITLE
[Bug]: gnunet build failure

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#13421]
### Problem description

[gnunet.txt](https://github.com/termux/termux-packages/files/10078078/gnunet.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Duplicate of #13420.

**Comment by xtkoba** [comment]
Oh I misread the title.

**Comment by xtkoba** [comment]
Use a newer Docker image after e0b888c4aba1aa283599ae4de101de5cbd8c892d.
