### ISSUE TITLE
[Bug]: gnuplot build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#13420]
### Problem description

[gnuplot.txt](https://github.com/termux/termux-packages/files/10078071/gnuplot.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Maybe due to parallel make?

**Comment by xtkoba** [comment]
Seems to be occurring in the host build step, where the number of jobs is not specified and the default should be 1.

Not occurring in GitHub Actions CI. Weird.

**Comment by xtkoba** [comment]
Example of successful build in GitHub Actions: https://github.com/termux/termux-packages/actions/runs/3533476293.

**Comment by xtkoba** [comment]
Lua is detected and used in the author's environment whereas not in GitHub Actions.

**Comment by johndebia2022** [comment]
Updating host_step
configure" **`--without-lua`**

works
