### ISSUE TITLE
error occurs when including unistd.h

### ISSUE THREAD

**Issue by breadbread1984** [termux/termux-packages#1344]
I found the specifier __sentinel__ which is not supported by clang compiler appears in unistd.h. Therefore, when including unistd.h the following error occurs.
``/data/data/com.termux/files/usr/include/unistd.h:108:20: error: expected ')'
    __attribute__((__sentinel__(1)));
``

**Comment by fornwall** [comment]
AFAIK `__sentinel__` is supported in clang and a simple hello world compiles for me:

```
$ cat test.c
#include <unistd.h>

int main() {
        return 0;
}
$ clang test.c
$
```

Could you give a small test case to reproduce the problem?

**Comment by fornwall** [comment]
Also, check that you are running with updated packages by running `pkg up`.

**Comment by stephengroat** [comment]
seeing the same error on #1640
