### ISSUE TITLE
[Package]: pkg install python3.7 as python not python3.7

### ISSUE THREAD

**Issue by a-gamer** [termux/termux-packages#13496]
### Why do you want to add this package to Termux?

kindly need your help after installed  python 3.7  it must be call python3.7 to work and python3.7 -m pip to use pip  
most of scripts not working  because of that can you help me please urgent 

### Source code URL

python 

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
```bash
pkg i tur-repo -y
pkg i python3.7 -y
```

https://github.com/termux/termux-packages/issues/9606#issuecomment-1080294159

**Comment by ravener** [comment]
You'll want the `python-is-python3.7` package to symlink python to python3.7
```sh
$ pkg install python-is-python3.7
```
