### ISSUE TITLE
[Bug]: weechat build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#13493]
### Problem description

[weechat error.txt](https://github.com/termux/termux-packages/files/10087683/weechat.error.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
@johndebia2022 Please test if #13494 fixes build. Thanks.

**Comment by johndebia2022** [comment]
> @johndebia2022 Please test if #13494 fixes build. Thanks.

It is building fine now
