### ISSUE TITLE
xargs: environment is too large for exec

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#135]
xargs from findutils fails with the above error. 
The one from busybox works fine.

**Comment by Neo-Oli** [comment]
This seems to have been resolved by version 0.32 of Termux. When it didn't occur on my main device anymore, I tested it on my alternate device, which was still on 0.31 just before and after updating and it failed before and worked after.
It also may have been resolved by another package update, and I just needed to restart my Tmux session, which was weeks old.

**Comment by Grimler91** [comment]
I encountered this today trying to run a program I have run many times before without problems, so something might have changed so that it happens again.
This is on arm (android 5.0), aarch64 (android 7.1) works fine.
