### ISSUE TITLE
Phone-Hacker Project

### ISSUE THREAD

**Issue by RafaelRfs** [termux/termux-packages#1350]
https://github.com/RafaelRfs/Phone-Hacker/

**Comment by fornwall** [comment]
Thanks! You can post this at https://termux.com/community if you want to share it with more people and get feedback!

**Comment by anderson058** [comment]
Do you need an excellent hacking experience? worry no more, as (cyberfiles.hacker@gmail.com) is the best, We are professionals in all kinds of hacking services including:

ACCESS TO EMAIL
ACCESS TO FACEBOOK
TOTAL PHONE HACK
WHATSAPP HACK

contact us today and get the best of hacking services.
