### ISSUE TITLE
[Bug]: error on starting

### ISSUE THREAD

**Issue by Cozmo007** [termux/termux-packages#13504]
### Problem description

![Screenshot_20221125-165533](https://user-images.githubusercontent.com/90281965/204050266-273e3138-cd33-4654-999c-9da5397cdc3c.png)

fix please

### What steps will reproduce the bug?

on installing

### What is the expected behavior?

on installing

### System information

termux-info:
```
Android 8.1
```

![Screenshot_20221125-165533](https://user-images.githubusercontent.com/90281965/204050312-546c3da9-a8fc-4768-9a2b-6f66ddef46dd.png)

**Comment by xtkoba** [comment]
The message

```
unused DT entry: type 0x1d arg 0x2cb
```

suggests that the dynamic linker does not support `DT_RUNPATH` which should be supported since Android 7.0 (API 24).

Also note that the symbol `strchrnul` is defined since Android 7.0. I doubt if your system is really Android 8.1. (I also use Android 8.1.0 but Termux works fine.)
