### ISSUE TITLE
[Bug]: neovim build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#13511]
### Problem description

[Uploading neovim.txt…]()

### What steps will reproduce the bug?

[neovim.txt](https://github.com/termux/termux-packages/files/10095209/neovim.txt)

### What is the expected behavior?

build

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
I won't anymore fix this type of failure on my own. Please submit a PR if you want to fix this. Thanks.

**Comment by xtkoba** [comment]
To clarify, I meant I won't fix build failures in Docker environment that do not reproduce in GitHub Actions CI. I will happily handle reproducible build failures.

**Comment by johndebia2022** [comment]
> > `no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lpeg.so'`
> 
> I would say this can't happen after commit [a4f4cb4](https://github.com/termux/termux-packages/commit/a4f4cb4e8bc044767df0b0fd9a55f7a28b9a8056), which installs [`lua-lpeg`](https://packages.ubuntu.com/jammy/amd64/lua-lpeg/filelist) in the Docker image.
> 
> What environment are you using in the first place?

Thank you @xtkoba after updating docker it worked
