### ISSUE TITLE
RCS package bin path error

### ISSUE THREAD

**Issue by dogear42** [termux/termux-packages#1352]
First, I'm really grateful for the RCS package!

However, I was running rcsdiff (which actually uses diff), and I got this error:

    RCS file: notes/data.org.txt,v                                                                                                                                                
    retrieving revision 1.32                                                                                                                                                      
    diff -r1.32 notes/data.org.txt                                                                                                                                                
    **/usr/bin/diff: not found**  

I'm guessing we missed something? diff is on the phone, but not at that location.

Thanks!

**Comment by Grimler91** [comment]
Which arch are you on? I uploaded debs for aarch64 and arm [here](https://github.com/Grimler91/Grimler91.github.io), could you try it and see if it fixes the problem? (I'm pretty sure it does but would like to make sure before opening a pull request).

**Comment by dogear42** [comment]
Arm. I tried it and got: 

[~/notes]
$ rcsdiff -r1.35 -r1.36 data.org.txt
===================================================================
RCS file: data.org.txt,v
retrieving revision 1.35
retrieving revision 1.36
diff -r1.35 -r1.36
/data/data/com.termux/files/usr/bin/diff: not found
[~/notes]
$ which diff
/data/data/com.termux/files/usr/bin/applets/diff

Do I need to install a different package to get diff to show up at that location?

BTW, I find it contrary to "the unix way" that the rcsdiff program is trying to force the path of the diff program.  Isn't that what the PATH variable is for? 

Thanks!

**Comment by Grimler91** [comment]
Ah, that because you don't have diffutils installed (`pkg install diffutils`), the one in the applets folder is a limited busybox version of diff. 

The configure script looks for the some utilities in the normal location (`/usr/bin/`) and finds them since they exist on the computer which we are cross compiling from. This is a bit weird, it should perhaps not assume this path since we are cross compiling. 

Maybe we should add diffutils as a dependency, or maybe it's possible to not hard code a path, I'll experiment a bit

**Comment by Grimler91** [comment]
@dogear42 should be fixed with #1353. Before that is merged, you can always just install diffutils manually and it should work with the version you installed manually earlier.

**Comment by dogear42** [comment]
Works great.  Thanks!
