### ISSUE TITLE
Auto update failing for miller

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#13534]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the miller package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating miller [Current version: 6.4.0]
INFO: package being updated to 6.5.0.
INFO: Trying to build package.
INFO: Package miller exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
Creating new container...
Unable to find image 'ghcr.io/termux/package-builder:latest' locally
latest: Pulling from termux/package-builder
e96e057aae67: Already exists
9fc79b698109: Pulling fs layer
457ebd0963c5: Pulling fs layer
9746bba775f9: Pulling fs layer
ba76cd3edfb3: Pulling fs layer
c2c0089cfd88: Pulling fs layer
ba76cd3edfb3: Waiting
c2c0089cfd88: Waiting
9fc79b698109: Download complete
9fc79b698109: Pull complete
457ebd0963c5: Verifying Checksum
457ebd0963c5: Pull complete
9746bba775f9: Download complete
9746bba775f9: Pull complete
c2c0089cfd88: Verifying Checksum
c2c0089cfd88: Download complete
ba76cd3edfb3: Verifying Checksum
ba76cd3edfb3: Download complete
ba76cd3edfb3: Pull complete
c2c0089cfd88: Pull complete
Digest: sha256:66f6b59583ae67a205dc7b949a31b775b3081e5defd4d712e24597702e9db075
Status: Downloaded newer image for ghcr.io/termux/package-builder:latest
98b016340ba430b8186b46cef90946297c578630c110e22d85f04319c6fbeb99
gpg: key B0076E490B71616B: 17 signatures not checked due to missing keys
gpg: key B0076E490B71616B: public key "Henrik Grimler <henrik@grimler.se>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no ultimately trusted keys found
gpg (GnuPG) 2.2.27; Copyright (C) 2021 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: key 5A897D96E57CF20C: public key "Termux Releases (Termux automatic builds) <contact@termux.dev>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   1  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-08-25
gpg (GnuPG) 2.2.27; Copyright (C) 2021 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

termux - building miller for arch aarch64...
Downloading https://github.com/termux/termux-elf-cleaner/releases/download/v2.1.1/termux-elf-cleaner
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

 21 63912   21 14051    0     0  29068      0  0:00:02 --:--:--  0:00:02 29068
100 63912  100 63912    0     0   123k      0 --:--:-- --:--:-- --:--:-- 2213k
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  50099      0 --:--:-- --:--:-- --:--:-- 50129
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   3973      0 --:--:-- --:--:-- --:--:--  3985
gpg: Signature made Sun 27 Nov 2022 02:45:48 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   2  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 2u
gpg: next trustdb check due at 2024-08-25
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 1454k    0  9037    0     0  23747      0  0:01:02 --:--:--  0:01:02 23719
100 1454k  100 1454k    0     0  2682k      0 --:--:-- --:--:-- --:--:-- 2678k
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  40504      0 --:--:-- --:--:-- --:--:-- 40609
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2784      0 --:--:-- --:--:-- --:--:--  2785
gpg: Signature made Sun 27 Nov 2022 09:54:40 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/stable/binary-aarch64/Packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 50295  100 50295    0     0   146k      0 --:--:-- --:--:-- --:--:--  146k
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  52686      0 --:--:-- --:--:-- --:--:-- 52903
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2664      0 --:--:-- --:--:-- --:--:--  2669
gpg: Signature made Sun 27 Nov 2022 02:49:26 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/main/binary-aarch64/Packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  360k  100  360k    0     0   820k      0 --:--:-- --:--:-- --:--:--  820k
Cloning into '/home/builder/.termux-build/miller/cache/tmp-checkout'...
warning: Could not find remote branch v6.5.0 to clone.
fatal: Remote branch v6.5.0 not found in upstream origin
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2022-11-27 18:13:00 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/3559358801">3559358801</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by licy183** [comment]
Closes via https://github.com/termux/termux-packages/commit/2fefe7bf95b1717378758123e197568373867ed3.
