### ISSUE TITLE
cyptsetup no longer works

### ISSUE THREAD

**Issue by misterhsp** [termux/termux-packages#13574]
### Problem description

cryptsetup no longer works for me since the last update of libdevmapper.

```
CANNOT LINK EXECUTABLE "cryptsetup": cannot find verneed/verdef for version index=32785 referenced by symbol "dm_bitset_parse_list" at "/data/data/com.termux/files/usr/lib/libdevmapper.so.1.02"
```

thanks

### What steps will reproduce the bug?

.

### What is the expected behavior?

.

### System information

termux-info:

cryptsetup (2.4.3-2)
libdevmapper_2.03.17

**Comment by xtkoba** [comment]
Something from build log (in my local cross-build environment) that may be related:

```
    [CC] ioctl/libdevmapper.so.1.02
aarch64-linux-android24-clang -shared -Wl,-soname,libdevmapper.so.1.02 \
        -Oz -fomit-frame-pointer -I/data/data/com.termux/files/usr/include -fPIC -Wl,--as-needed -Wl,-rpath=/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,--version-script,.export.sym -Wl,-z,relro datastruct/bitset.o datastruct/hash.o datastruct/list.o libdm-common.o libdm-config.o libdm-deptree.o libdm-file.o libdm-report.o libdm-stats.o libdm-string.o libdm-targets.o libdm-timestamp.o mm/dbg_malloc.o mm/pool.o regex/matcher.o regex/parse_rx.o regex/ttree.o ioctl/libdm-iface.o  -lpthread    -lm -o ioctl/libdevmapper.so.1.02
ld: warning: attempt to reassign symbol 'dm_bitset_parse_list' of version 'DM_1_02_129' to version 'DM_1_02_138'
```

**Comment by Grimler91** [comment]
> Something from build log (in my local cross-build environment) that may be related:
> 
> ```
>     [CC] ioctl/libdevmapper.so.1.02
> aarch64-linux-android24-clang -shared -Wl,-soname,libdevmapper.so.1.02 \
>         -Oz -fomit-frame-pointer -I/data/data/com.termux/files/usr/include -fPIC -Wl,--as-needed -Wl,-rpath=/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,--version-script,.export.sym -Wl,-z,relro datastruct/bitset.o datastruct/hash.o datastruct/list.o libdm-common.o libdm-config.o libdm-deptree.o libdm-file.o libdm-report.o libdm-stats.o libdm-string.o libdm-targets.o libdm-timestamp.o mm/dbg_malloc.o mm/pool.o regex/matcher.o regex/parse_rx.o regex/ttree.o ioctl/libdm-iface.o  -lpthread    -lm -o ioctl/libdevmapper.so.1.02
> ld: warning: attempt to reassign symbol 'dm_bitset_parse_list' of version 'DM_1_02_129' to version 'DM_1_02_138'
> ```

configuring with --with-symvers=no works (termux/termux-packages#13575), but that ld warning probably points to the real issue

**Comment by Grimler91** [comment]
dm_bitset_parse_list is in both [exported_symbols.DM_1_02_129](https://github.com/lvmteam/lvm2/blob/master/libdm/.exported_symbols.DM_1_02_129) and [exported_symbols.DM_1_02_138](https://github.com/lvmteam/lvm2/blob/master/libdm/.exported_symbols.DM_1_02_138). Removing it from exported_symbols.DM_1_02_138 also seem to fix the issue.

**Comment by Grimler91** [comment]
Neither the exported_symbols lists or libdm/datastruct/bitset.c have been touched between 2.03.16 and 2.03.17, so don't know why this issue occurs after the upgrade and not before

**Comment by Grimler91** [comment]
Merged the alternative fix so that we at least have a working package, thanks for reporting!

**Comment by misterhsp** [comment]
cryptsetup must also be rebuilt, right?

...

**Comment by Grimler91** [comment]
No, error comes from libdevmapper, so updating that package fixes it
