### ISSUE TITLE
[Package]: qt5-qtgraphicaleffects

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#13598]
### Why do you want to add this package to Termux?

Needed for cutefish-de

### Home page URL

https://github.com/archlinux/svntogit-packages/blob/packages/qt5-graphicaleffects/trunk/PKGBUILD

### Source code URL

https://github.com/archlinux/svntogit-packages/blob/packages/qt5-graphicaleffects/trunk/PKGBUILD

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Simeon Huang symeon@librehat.com 
@librehat

**Comment by 2096779623** [comment]
QtGraphicalEffects module is not available because it depends on OpenGL.

**Comment by T-Dynamos** [comment]
> QtGraphicalEffects module is not available because it depends on OpenGL.
I don't get it. Kivy also depends on OpenGL (mesa) but it works
