### ISSUE TITLE
[Bug]: Tageditor doesn't completely tag a audio file

### ISSUE THREAD

**Issue by GUUser91** [termux/termux-packages#13590]
### Problem description

Using tageditor to tag an audio file will only get the album and artist info tagged even if you include other info like title and track number.
I tried tageditor-cli on my pc and tagged the audio file with this exact same command below and it worked.

### What steps will reproduce the bug?

tageditor -s artist="Benge" title="[untitled]" album="Experimental Non-Vocal Electronic Pop" albumartist="Benge" disk="1" track="1"  genre="IDM" year=1999-06-00 comment="This is a comment" -f "01.m4a"

### What is the expected behavior?

tageditor get -f 01.m4a                      Tag information for "01.m4a":                                  - MP4/iTunes tag                                                 Title             [untitled]
    Album             Experimental Non-Vocal Electronic Pop
    Artist            Benge
    Genre             IDM
    Comment           This is a comment
    Track             1
    Disk              1
    Record date       1999-06-00
    Album artist      Benge

### System information

termux-info:

```
TERMUX_VERSION=0.118.0+a523911                                Packages CPU architecture:
aarch64                                                       Subscribed repositories:
# sources.list                                                deb https://packages-cf.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.32.0
Android version:
12
Kernel build information:
Linux localhost 5.4.147-moto-gae8639584c35 #1 SMP PREEMPT Thu Jun 2 05:25:58 CDT 2022 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g stylus 5G (2022)
```

**Comment by xtkoba** [comment]
A workaround seems to specify at most one field per command:

```bash
tageditor -s artist="Benge" -f "01.m4a"
tageditor -s title="[untitled]" -f "01.m4a"
tageditor -s album="Experimental Non-Vocal Electronic Pop" -f "01.m4a"
tageditor -s albumartist="Benge" -f "01.m4a"
tageditor -s disk="1" -f "01.m4a"
tageditor -s track="1" -f "01.m4a"
tageditor -s genre="IDM" -f "01.m4a"
tageditor -s year=1999-06-00 -f "01.m4a"
tageditor -s comment="This is a comment" -f "01.m4a"
```

Very inconvenient though.

**Comment by xtkoba** [comment]
Just an observation. With the modification

```diff
--- tageditor-3.7.6/cli/helper.cpp.orig
+++ tageditor-3.7.6/cli/helper.cpp
@@ -702,6 +702,7 @@
             std::exit(-1);
         }
     }
+    cerr << " parseFieldDenotations: fields.size(): " << fields.size() << endl;
     return fields;
 }
```

the example in the description results in

```
 parseFieldDenotations: fields.size(): 2
```

on Android (producing incorrect output), whereas

```
 parseFieldDenotations: fields.size(): 9
```

on GNU/Linux with correct output.

The test case (for completeness):

```bash
tageditor set artist="Benge" title="[untitled]" album="Experimental Non-Vocal Electronic Pop" albumartist="Benge" disk="1" track="1" genre="IDM" year=1999-06-00 comment="This is a comment" -f test.m4a
```

with `test.m4a` attached below.
[test.m4a.gz](https://github.com/termux/termux-packages/files/10204229/test.m4a.gz)

(or in Base64:)

```
AAAAHGZ0eXBNNEEgAAACAE00QSBpc29taXNvMgAAAAhmcmVlAAAACG1kYXQAAADWbW9vdgAAAGxt
dmhkAAAAAAAAAAAAAAAAAAAD6AAAAAAAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAB
AAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAGJ1ZHRhAAAA
Wm1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAALWlsc3QAAAAlqXRv
bwAAAB1kYXRhAAAAAQAAAABMYXZmNTguNzYuMTAw
```
