### ISSUE TITLE
Termux Python3.11 "inspect.getargspec"[Bug]: 

### ISSUE THREAD

**Issue by concu72** [termux/termux-packages#13632]
### Problem description

Since the "inspect.getargspec" command has been replaced with "inspect.getfullargspec" as of the Python3 version, the Python3.11 version downloaded from the Termux repo gives an error because this fix is ​​not made.
In Python3.11 downloaded from the Termux repo, the part with " inspect.getargspec " in Line 9: in /data/data/com.termux/files/usr/lib/python3.11/site-packages/parsimonius/expressions.py is inspect. getfullargspec " needs to be fixed. When I edited this file manually, the error went away.

### What steps will reproduce the bug?

In Python3.11 downloaded from the Termux repo, the part with " inspect.getargspec " in Line 9: in /data/data/com.termux/files/usr/lib/python3.11/site-packages/parsimonius/expressions.py is inspect. getfullargspec " needs to be fixed. When I edited this file manually, the error went away.

### System information

termux-info:

```

```

**Comment by MrAdityaAlok** [comment]
https://github.com/erikrose/parsimonious is a third-party python package. There's author should make that chage.

BTW they already have made that change. You just need to update.
