### ISSUE TITLE
 `fread` doesn't work. Return vode 14

### ISSUE THREAD

**Issue by RechieKho** [termux/termux-packages#13665]
### Problem description

I am programming in C and I need to load file using `fread`.  

Here is the [code](https://github.com/RechieKho/lake/blob/main/reader.c) that encounters error.
```c
// in reader.c
//...
int read(const char* p_filepath, read_handler_t p_handler) {
    int code = -1;
    long file_size = 0;
    char* content = NULL;
    FILE* file = fopen(p_filepath, "r");
    ASSERT_TRUE(file, quit);
    ASSERT_FALSE(fseek(file, 0L, SEEK_END), cleanup_file);
    ASSERT_POS(file_size = ftell(file), cleanup_file);
    ASSERT_FALSE(fseek(file, 0L, SEEK_SET), cleanup_file);
    ASSERT_TRUE(content = (char*) calloc(file_size + 1,sizeof(char)), cleanup_content);
    ASSERT_EQU(fread(content, sizeof(char), file_size, file), (size_t) file_size, cleanup_content);
    code = p_handler(content);
    return code;
cleanup_content:
    free(content);
cleanup_file:
    fclose(file);
quit:
    return code;
}
//...
```

All the `ASSERT_*` are [macros](https://github.com/RechieKho/lake/blob/main/macros.h) as defined,
```c
// In macros.h
//...
#define ASSERT_TRUE(mp_expression, mp_label) if(!(mp_expression)) goto mp_label
#define ASSERT_FALSE(mp_expression, mp_label) if((mp_expression)) goto mp_label
#define ASSERT_POS(mp_expression, mp_label) if((mp_expression) < 0) goto mp_label
#define ASSERT_EQU(mp_expression, mp_value, mp_label) if((mp_expression) != mp_value) goto mp_label
//...
```

And the `read` function will get called by `main` in [`main.c`](https://github.com/RechieKho/lake/blob/main/main.c),
```c
// In main.c
//...
static int read_handler(const char* p_content){
    //...
    return 0;
};

int main(int argc, const char* argv[]) {
    if(argc < 2) return 0;
    printf("Filepath: %s\n", argv[1]);
    int status = read(argv[1], read_handler);
    if(status < 0) fprintf(stderr, "Error: %d code.\n", errno);
    return status;
}
//...
```

I tried to run it on my laptop (Debian) and it works, but when I run it on termux, it always gives errno `14`.
The project is at [here](https://github.com/RechieKho/lake)

### What steps will reproduce the bug?

1. Clone the my project. `git clone https://github.com/RechieKho/lake.git`
2. `cd lake` and run `make`
3. Call `@bin/lake main.c`

### What is the expected behavior?

It should print out information of tokens about include directives (the project is for calculating the dependency of C file). If there is an error, it will print out the error code, in this case, it is probably error 14.

Here is the result on my termux.
```
~/.../c_projects/lake $ @bin/lake main.c
Filepath: main.c
Error: 14 code.
```

And here is the result on Debian.
```
rechie@debian:~/Documents/lake$ @bin/lake main.c
Filepath: main.c
Line 1 (indent 0, type 1):
	|#| (column 0, type 7)
	|include| (column 1, type 0)
	|"reader.h"| (column 10, type 0)
Line 2 (indent 0, type 1):
	|#| (column 0, type 7)
	|include| (column 1, type 0)
	|"token.h"| (column 10, type 0)
Line 3 (indent 0, type 1):
	|#| (column 0, type 7)
	|include| (column 1, type 0)
	|"errno.h"| (column 10, type 0)
```

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=28106
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.cbrx.io/apt/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.32.0
Android version:
11
Kernel build information:
Linux localhost 4.19.152-perf-23447145-abT500XXU3BVB4 #1 SMP PREEMPT Wed Mar 2 17:24:43 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T500
```

**Comment by Grimler91** [comment]
There already is a [function with the name `read` in bionic](https://android.googlesource.com/platform/bionic/+/refs/heads/master/libc/include/unistd.h#238), rename the function to something else

**Comment by RechieKho** [comment]
`fread` is a part of C standard while `read` is Unix specifix. I was hoping to write some platform independent code.

In #13663, the guy says that if `fread` does not work, half of the package won't work.

The issue got tagged as spam and greeted with unwelcome text, shouldn't have make the issue on phone under 5 minutes.
