### ISSUE TITLE
[New Mirror]: Add mirror.fcix.net as official mirror

### ISSUE THREAD

**Issue by PhirePhly** [termux/termux-packages#13673]
### Problem description

Wasn't quite clear if I should be using the bug template, but the alternative was a package request, so I'm making it work.

We have mirrored all of the repos and hosting them as the following:

```
http://mirror.fcix.net/termux/
https://mirror.fcix.net/termux/
rsync://mirror.fcix.net/termux/
```

10Gbps

Fremont, CA, US, NOAM

Hosting sponsor: Fremont Cabal Internet Exchange, https://fcix.net/

We have rsync ACLs, but if you tell us what IP addresses to allow for scanning we can allow them.

### What steps will reproduce the bug?

Um.

### What is the expected behavior?

Add FCIX as an official Termux mirror to be added to the rotation for users.

### System information

I've never used Termux myself, but users asked us to add you.

**Comment by Grimler91** [comment]
Thanks! 

Could you please add rsync access for 185.224.83.107 (ip of grimler.se repo) and 5.75.242.194 (ip of new vps which will be origin repo in a few days or weeks)?

**Comment by PhirePhly** [comment]
Done.

**Comment by 2096779623** [comment]
Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors/).

**Comment by Grimler91** [comment]
Added, thanks
