### ISSUE TITLE
curl error

### ISSUE THREAD

**Issue by irregularisnotrandom** [termux/termux-packages#137]
curl
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "SSLv2_client_method" referenced by "libcurl.so"...

**Comment by Neo-Oli** [comment]
does the output of `which curl` point to "/data/data/com.termux/files/usr/bin/curl"? Otherwise you don't have the termux version of curl installed and are using your roms version of curl. install curl with `apt install curl`.

**Comment by fornwall** [comment]
As @Neo-Oli says, you are probably trying to execute an older version of curl supplied with the system (in `/system/bin`), which clashes with the updated libraries in Termux, see https://termux.com/common-problems.html#cannot-link-executable-cannot-locate-symbol--referenced-by-.

**Comment by irregularisnotrandom** [comment]
You were damn right.

**Comment by alanjds** [comment]
Mine is on the right path, but still the same error.

**Comment by alanjds** [comment]
Can you please reopen?

**Comment by Grimler91** [comment]
@alanjds you shouldn't get any errors if all your packages are up to date. If you still get an error after `apt update && apt upgrade` then please open a new bug report and provide steps to reproduce it and the output of ` termux-info`.

**Comment by alanjds** [comment]
I just got it to work after installing `zlib`. I would expect `curl` package to have it as dependency and bump automatically. Strange.

But worked. Thanks anyway.

**Comment by Grimler91** [comment]
Curl depends on libcurl, which depends on zlib. You must have had an old version of libcurl installed, which didn't specify the dependency on zlib
