### ISSUE TITLE
[Bug]: On-device build: Buildling any C++ package implies building libc++ which fails

### ISSUE THREAD

**Issue by phhusson** [termux/termux-packages#13702]
### Problem description

Any packages requiring libc++ will force building libc++ (`build-package.sh -f --package debian packages/libc++` can be seen in `bash -x` call)
And building libc++ fails with:
```
+ termux_step_post_make_install
+ cp /data/data/com.termux/files/home/.termux-build/_cache/android-r25b-api-24-v2/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so /data/data/com.termux/files/usr/lib
cp: cannot stat '/data/data/com.termux/files/home/.termux-build/_cache/android-r25b-api-24-v2/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so': No such file or directory
```

It seems to me that libc++ shouldn't get rebuilt

Looking at history, it seems to me that https://github.com/termux/termux-packages/commit/b9b5987319e6df8a9de1a15cf3a0d2c22befcb27 is wrong:
- `scripts/build/termux_step_setup_variables.sh` will set TERMUX_FORCE_BUILD by default to "false"
- `${TERMUX_FORCE_BUILD+-f} ` will thus evaluate to `-f` no matter whether `-f` was passed originally or not

That being said, even removing that `-f` still makes build-package want to build libc++ even though it's already installed

### What steps will reproduce the bug?

Fresh install of Termux (on Android 13 on Pixel 6a if that's relevant)
```
pkg update
pkg install git build-essential
git clone https://github.com/termux/termux-packages
cd termux-packages
bash scripts/setup-termux.sh
bash build-package.sh par2
```

### What is the expected behavior?

I'm not exactly sure whether the expected behavior is for libc++ to build successfully on-device, or that it doesn't try installing libc++. But either way, it's expected that the build of `par2` (that's just an example) works on-device.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.32.0
Android version:
13
Kernel build information:
Linux localhost 5.10.107-android13-4-00004-gf0fe4f768061-ab8935229 #1 SMP PREEMPT Thu Aug 11 01:16:28 UTC 2022 aarch64 Android
Device manufacturer:
unknown
Device model:
Phh-Treble vanilla
```

```
$ dpkg -l libc++
[...]
ii  libc++         25b          aarch64      C++ Standard Library
```

**Comment by licy183** [comment]
`libc++` should not build on device, neither should `ndk-sysroot`. Maybe we should add on-device check in pre-configure step.

**Comment by licy183** [comment]
On-device build `bash build-package.sh -I par2` should run successfully.
