### ISSUE TITLE
htop showing really high load 

### ISSUE THREAD

**Issue by ioweb-gr** [termux/termux-packages#13716]
While the cpu cores are not utilized that much htop is always showing a very high load average

Usually it's over 30

![Screenshot_2022-12-04-11-24-54-10_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/20220341/205483438-842ac485-b069-4b5b-b273-03b249074eeb.jpg)

Any ideas what might be causing this?

**Comment by xtkoba** [comment]
On my environment (Android 8.1.0 asus/WW_X01AD/ASUS_X01A_1 with aarch64 userland, not quite Termux) `htop` shows `nan` as the load averages:

```
  Swp[||                              346M/1024M] Load average: nan nan nan
```

while `uptime` shows some sane ones:

```
$ uptime
 00:33:23 up 4 days, 18:43,  load average: 2.19, 2.27, 2.44
```

I suppose these two programs use different method for obtaining load average values from each other.

**Comment by ioweb-gr** [comment]
For me uptime shows the same as htop

**Comment by ioweb-gr** [comment]
Hi, here's the output 

![Screenshot_2022-12-06-22-42-43-67_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/20220341/206018877-70f44ccd-dcd4-43ba-a73a-f3b779cf80ab.jpg)

However I'm not sure how to make the device fully idle

**Comment by Anonymous2716** [comment]
@xtkoba in unrooted htop the cpu usage information removed? Bcs its always 0.

**Comment by Anonymous2716** [comment]
@sylirre I meant the %cpu column . in top it shows the usage percentage of a process. That's just 0 in htop.

**Comment by Anonymous2716** [comment]
@xtkoba I'm on non-rooted phone since top and htop can't access /proc/stat I'm guessing that top goes through each process id and reads their stat? And since htop cant it loads from this path faccessat"/data/data/com.termux/files/usr/var/htop/stat

```
(AT_FDCWD, "/proc/stat", R_OK) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "/data/data/com.termux/files/usr/var/htop/stat", O_RDONLY) = 3
```

top:
```
faccessat(AT_FDCWD, "/proc/stat", R_OK) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "/data/data/com.termux/files/usr/var/htop/stat", O_RDONLY) = 3
```

so its an htop specific issue?

**Comment by xtkoba** [comment]
@Anonymous2716 What?

**Comment by xtkoba** [comment]
Ah now I understand. <a href="https://github.com/termux/termux-packages/tree/master/packages/htop">`htop` in our repo</a> is heavily patched in terms of `/proc/stat`, including a hack to use a fake one as pointed out by @Anonymous2716.

But I doubt if that is relevant to CPU usage being always 0%, because the same happens for `top`.

**Comment by xtkoba** [comment]
Going too off-topic.

If `cat /proc/loadavg` shows as high values as `htop`, then it is just that the system reports that the load average is as high and `htop` is irrelevant there.

Closing as answered.
