### ISSUE TITLE
[Bug]: ass2bdnxml - not working

### ISSUE THREAD

**Issue by OilSubjectLoss7** [termux/termux-packages#13726]
### Problem description

i encountered a major error;

`Progress: 1000/1000 - Lines: 1 - Done
[1]    25590 segmentation fault  ass2bdnxml -c 1000 -o test.xml test.avs`

`fish: Job 1, 'ass2bdnxml -c 1000 -o test.xml 0…' terminated by signal SIGSEGV (Address boundary error)`

### What steps will reproduce the bug?

ass2bdnxml -f 23.976 -v 720p -o output.xml input.avs

### What is the expected behavior?

produce a working file i.e sup, xml

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Please share a .avs file that people can use to test the command

**Comment by OilSubjectLoss7** [comment]
@Grimler91 
[test.zip](https://github.com/termux/termux-packages/files/10154060/test.zip)

**Comment by T-Dynamos** [comment]
```
❯ ass2bdnxml -f 23.976 -v 720p test.avs -o ~/t.xml
Cannot determine absolute path for: /data/data/com.termux/files/home/t.xml
```
