### ISSUE TITLE
openssl (3.0): Cannot connect to https://mirror.rosalinux.ru due to "wrong signature type"

### ISSUE THREAD

**Issue by saber716rus** [termux/termux-packages#13723]
### Problem description

the problem is related to the curl package.

u0_a988@localhost ~> proot-distro install rosa
[*] Installing Rosa Linux...
[*] Downloading rootfs tarball...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:0A000172:SSL routines::wrong signature type
[!] Download failure, please check your network connection.
u0_a988@localhost ~ [1]> curl https://mirror.rosalinux.ru/rosa/rosa2021.1/iso/ROSA.FRESH.12/rootfs/rootfs-std-rosa2021.1_aarch64_2022-11-02.tar.xz
curl: (35) error:0A000172:SSL routines::wrong signature type
u0_a988@localhost ~ [35]>

u0_a988@localhost ~ [127]> pkg info curl
Package: curl
Version: 7.86.0
Essential: yes
Maintainer: @termux
Installed-Size: 348 kB
Depends: libcurl (= 7.86.0)
Homepage: https://curl.se/
Download-Size: 182 kB
APT-Manual-Installed: yes
APT-Sources: https://mirrors.scau.edu.cn/termux/apt/termux-main stable/main aarch64 Packages
Description: Command line tool for transferring data with URL syntax

u0_a988@localhost ~>

### What steps will reproduce the bug?

download file from curl https://mirror.rosalinux.ru/rosa/rosa2021.1/iso/ROSA.FRESH.12/rootfs/rootfs-std-rosa2021.1_aarch64_2022-11-02.tar.xz

### What is the expected behavior?

file upload.

### System information

u0_a988@localhost ~ [35]> termux-info
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=23562
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.scau.edu.cn/termux/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.32.0
Android version:
11
Kernel build information:
Linux localhost 4.14.186-g4e5507d5edae #1 SMP PREEMPT Wed Jul 13 20:33:06 WIB 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8 Pro
u0_a988@localhost ~>

**Comment by xtkoba** [comment]
The same goes for `wget`:

```
$ wget https://mirror.rosalinux.ru/rosa/rosa2021.1/iso/ROSA.FRESH.12/rootfs/rootfs-std-rosa2021.1_aarch64_2022-11-02.tar.xz
--2022-12-05 06:19:09--  https://mirror.rosalinux.ru/rosa/rosa2021.1/iso/ROSA.FRESH.12/rootfs/rootfs-std-rosa2021.1_aarch64_2022-11-02.tar.xz
Resolving mirror.rosalinux.ru... 195.19.76.246
Connecting to mirror.rosalinux.ru|195.19.76.246|:443... connected.
OpenSSL: error:0A000172:SSL routines::wrong signature type
Unable to establish SSL connection.
```

So it is OpenSSL that rejects the connection. Using `openssl s_client` command I get the following:

```
$ openssl s_client -servername mirror.rosalinux.ru -connect mirror.rosalinux.ru:443
CONNECTED(00000003)
depth=2 OU = GlobalSign Root CA - R3, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign RSA OV SSL CA 2018
verify return:1
depth=0 C = RU, ST = Moscow, L = Zelenograd, O = LLC NTC IT ROSA, CN = *.rosalinux.ru
verify return:1
A83929037B000000:error:0A000172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1572:
---
Certificate chain
 0 s:C = RU, ST = Moscow, L = Zelenograd, O = LLC NTC IT ROSA, CN = *.rosalinux.ru
   i:C = BE, O = GlobalSign nv-sa, CN = GlobalSign RSA OV SSL CA 2018
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jun 29 14:45:59 2022 GMT; NotAfter: Jul 31 14:45:58 2023 GMT
 1 s:C = BE, O = GlobalSign nv-sa, CN = GlobalSign RSA OV SSL CA 2018
   i:OU = GlobalSign Root CA - R3, O = GlobalSign, CN = GlobalSign
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Nov 21 00:00:00 2018 GMT; NotAfter: Nov 21 00:00:00 2028 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGkDCCBXigAwIBAgIMb1jFar6BhS34wDCZMA0GCSqGSIb3DQEBCwUAMFAxCzAJ
BgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMSYwJAYDVQQDEx1H
bG9iYWxTaWduIFJTQSBPViBTU0wgQ0EgMjAxODAeFw0yMjA2MjkxNDQ1NTlaFw0y
MzA3MzExNDQ1NThaMGYxCzAJBgNVBAYTAlJVMQ8wDQYDVQQIEwZNb3Njb3cxEzAR
BgNVBAcTClplbGVub2dyYWQxGDAWBgNVBAoTD0xMQyBOVEMgSVQgUk9TQTEXMBUG
A1UEAwwOKi5yb3NhbGludXgucnUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDeP6LwW98jvU7U90Neq+bfsPq2uZlj/OKTj6044VjqgVYJNera7iivKRLy
g3LT26idEuRbw0sDIxu5V21mgaKUHAIigwYwiD5YRfstEdWQ4ZqxVWdqg7YMX1YJ
LqzVa92m15+irYtetXe/QPhtdsj3Bn1eoY5zNzmYP4a5LqNT0PAlwhgcDSLX41Bx
ewmAo81lis13Mf0h5ubI9pj8chuqaxzs/WWpaY8SLGmDiFPmbRYbj3TSuKLRjW+s
kdHTFMkdmqojbtJo51Y397LM66mHzL5IFNbJ2v2JP2Ut9dsLeqgRmu8ytr//CBLF
vU9Ga/uDKCvYHigbI9jjAHZ7eu2pAgMBAAGjggNSMIIDTjAOBgNVHQ8BAf8EBAMC
BaAwgY4GCCsGAQUFBwEBBIGBMH8wRAYIKwYBBQUHMAKGOGh0dHA6Ly9zZWN1cmUu
Z2xvYmFsc2lnbi5jb20vY2FjZXJ0L2dzcnNhb3Zzc2xjYTIwMTguY3J0MDcGCCsG
AQUFBzABhitodHRwOi8vb2NzcC5nbG9iYWxzaWduLmNvbS9nc3JzYW92c3NsY2Ey
MDE4MFYGA1UdIARPME0wQQYJKwYBBAGgMgEUMDQwMgYIKwYBBQUHAgEWJmh0dHBz
Oi8vd3d3Lmdsb2JhbHNpZ24uY29tL3JlcG9zaXRvcnkvMAgGBmeBDAECAjAJBgNV
HRMEAjAAMD8GA1UdHwQ4MDYwNKAyoDCGLmh0dHA6Ly9jcmwuZ2xvYmFsc2lnbi5j
b20vZ3Nyc2FvdnNzbGNhMjAxOC5jcmwwJwYDVR0RBCAwHoIOKi5yb3NhbGludXgu
cnWCDHJvc2FsaW51eC5ydTAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
HwYDVR0jBBgwFoAU+O9/8s14Z6jeb48kjYjxhwMCs+swHQYDVR0OBBYEFDZT9sbx
gY5jmnLnLaDM9Gg7xU11MIIBfQYKKwYBBAHWeQIEAgSCAW0EggFpAWcAdwDoPtDa
PvUGNTLnVyi8iWvJA9PL0RFr7Otp4Xd9bQa9bgAAAYGv7RtFAAAEAwBIMEYCIQDF
jGIkKQNVnN9i20OXE9FykACXabfgNps0AhzZZtXVwgIhAMbpTqcWCnFlYLN+6Wfm
3iFr+YfDZEyhwu6Zfr6n2DHpAHUAb1N2rDHwMRnYmQCkURX/dxUcEdkCwQApBo2y
CJo32RMAAAGBr+0bOgAABAMARjBEAiB4ksHCP1x/vdOXP7QETeRL+nV0ZYdAVuWI
rDg6ZWvGigIgSAdMRpsPwF3/p/WqzYeasD736sPc3Lsywa4f9TV4nCUAdQCzc3cH
4YRQ+GOG1gWp3BEJSnktsWcMC4fc8AMOeTalmgAAAYGv7RtZAAAEAwBGMEQCICkM
o0PaCe8HRDchMd9InXzWkFfAX9KXBNx0f1lO5lDvAiB5+k+fH50ie+GzNkDYHSPg
bDi2Offg3Vrpf10e0aOfWTANBgkqhkiG9w0BAQsFAAOCAQEAeOfvjeIS+CS+OaXl
QXmdzKEAKBMnZ2PTvHA0ikBFr0zUFaCgXpRMh9qp7uUapoMSP2RSJ5SJjYZgtzxi
t7zHfl6GGLoLvtmaZhAVT5yYHYnSQrlc1M1Mt+QnMhpKrIb7lvc64uA2beayhyWx
Q2Mo7IPd60iEhlltST/UkmtLLU1wtCgQGeexGjFwEtgkh6saf5KDDKuRTyo3Ghsd
yTdg/UzlUblGJxWB/JI1+A6xdWoFOq0qciY94Y3MgciYrSBh+8tfy9ELeIdRMvmk
h1Bs9Xi3rlShev5fsrrxOEe+GMBVRJgV24tWmoiNesJtlupb+kDopcHTf4aV2+dL
LM96kw==
-----END CERTIFICATE-----
subject=C = RU, ST = Moscow, L = Zelenograd, O = LLC NTC IT ROSA, CN = *.rosalinux.ru
issuer=C = BE, O = GlobalSign nv-sa, CN = GlobalSign RSA OV SSL CA 2018
---
No client certificate CA names sent
Server Temp Key: ECDH, secp384r1, 384 bits
---
SSL handshake has read 3248 bytes and written 332 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    Start Time: 1670188623
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
$
```

**Comment by xtkoba** [comment]
@sylirre What is your OpenSSL version? On my GNU/Linux environment, the connection is accepted by OpenSSL 1.1.1s but is rejected by OpenSSL 3.0.5.

**Comment by saber716rus** [comment]
openssl/stable,now 1:3.0.7 aarch64 [installed]

**Comment by saber716rus** [comment]
installing version 1.1 does not help and you will not be able to remove version 3.

u0_a988@localhost ~> pkg install openssl-1.1
Checking availability of current mirror:
[*] https://mirrors.scau.edu.cn/termux/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  openssl-1.1
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1183 kB of archives.
After this operation, 4506 kB of additional disk space will be used.
Get:1 https://mirrors.scau.edu.cn/termux/apt/termux-main stable/main aarch64 openssl-1.1 aarch64 1:1.1.1s [1183 kB]
Fetched 1183 kB in 7s (168 kB/s)
Selecting previously unselected package openssl-1.1.
(Reading database ... 8113 files and directories currently installed.)
Preparing to unpack .../openssl-1.1_1%3a1.1.1s_aarch64.deb ...
Unpacking openssl-1.1 (1:1.1.1s) ...
Setting up openssl-1.1 (1:1.1.1s) ...
u0_a988@localhost ~> curl https://mirror.rosalinux.ru/rosa/rosa2021.1/iso/ROSA.FRESH.12/rootfs/rootfs-std-rosa2021.1_aarch64_2022-11-02.tar.xz
curl: (35) error:0A000172:SSL routines::wrong signature type
u0_a988@localhost ~ [35]> pkg remove openssl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apt : Depends: libgnutls but it is not going to be installed
 libcurl : Depends: libssh2 but it is not going to be installed
           Depends: openssl (>= 3.0.3) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
u0_a988@localhost ~ [100]>

**Comment by xtkoba** [comment]
@saber716rus Users cannot choose the version of OpenSSL to use. Our `curl` (or `wget`) is built against OpenSSL.

**Comment by xtkoba** [comment]
It seems that GnuTLS does not suffer from this issue. `epiphany` (which uses GnuTLS through GLib-Networking) can download that file.

**Comment by saber716rus** [comment]
> @saber716rus Users cannot choose the version of OpenSSL to use. Our `curl` (or `wget`) is built against OpenSSL [EDIT] 3.0.

I asked my distribution colleagues if there is a bug in openssl v3 or not.

**Comment by saber716rus** [comment]
> It seems that GnuTLS does not suffer from this issue. `epiphany` (which uses GnuTLS through GLib-Networking) can download that file.

I need to download and install this container in Proot-distro.

**Comment by xtkoba** [comment]
So may we close this? I have no good idea where this should be forwarded to. It may be just that the server is bad and that OpenSSL 3.0 is not guilty.

**Comment by xtkoba** [comment]
You may forward this to https://github.com/openssl/openssl/issues as a *question* (should not be labeled as bug at first.)

**Comment by saber716rus** [comment]
> So may we close this? I have no good idea where this should be forwarded to. It may be just that the server is bad and that OpenSSL 3.0 is not guilty.

this problem was raised by colleagues engaged in this service.

until I solve the problem, it's not worth closing it yet.

**Comment by xtkoba** [comment]
> until I solve the problem, it's not worth closing it yet.

But this is not a right place to hold this issue as it is not Termux-specific.
