### ISSUE TITLE
[Bug]: "pkg up" is broken. "termux-change-repo" is broken.

### ISSUE THREAD

**Issue by AmericaPacific42** [termux/termux-packages#13742]
### Problem description

"pkg up" is broken.
"termux-change-repo" is broken.

### What steps will reproduce the bug?

pkg up
termux-change-repo

### What is the expected behavior?

It shold be possible to use "pkg up" or to get Vim. Otherwise how could somebody use this to get employed?

### System information

[*] Official repositories selected
    Changing main repository
[*] Running apt update
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:2 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  SSL certificate problem: certificate has expired
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  SSL certificate problem: certificate has expired
Ign:3 https://termux.dev/packages stable InRelease
Err:6 https://termux.dev/packages stable Release                                                              404
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.                                                                                                         N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://termux.org/packages stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
13
Kernel build information:
Linux localhost 4.19.239-g248fa42a73b2-ab9062766 #1 SMP PREEMPT Wed Sep 14 05:22:28 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 5
$

**Comment by AmericaPacific42** [comment]
My job requires BASH, what should I replace Termux with?

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation

https://github.com/termux/termux-app#google-play-store-deprecated

**Comment by AmericaPacific42** [comment]
Solved with mv ../usr/etc/apt/sources.list.d/*.list ~/ && termux-change-repo #to termux.mentality.rip

BUT!! For SSL press "O" to keep the old file

https://mta.openssl.org/pipermail/openssl-commits/2020-February/027563.html “…unprotectedErrors may be set as workaround for broken server responses: accept missing or invalid protection of regular error messages, negative certificate responses (ip/cp/kup), revocation responses (rp), and PKIConf… int unprotectedErrors;”

Termux: “termux-change-repo

[*] A1batross's mirrors selected

Changing main repository

[*] Running apt update

Get:1 Index of /termux-packages-24/ (https://termux.mentality.rip/termux-packages-24) stable InRelease [14.0 kB]

Get:2 Index of /termux-packages-24/ (https://termux.mentality.rip/termux-packages-24) stable/main aarch64 Packages [481 kB]

$ pkg up

Checking availability of current mirror: ok

Hit:1 Index of /termux-packages-24/ (https://termux.mentality.rip/termux-packages-24) stable InRelease

The following packages will be REMOVED:

game-repo science-repo

The following NEW packages will be installed:

bash-completion libassuan libcap-ng libevent libexpat libgnutls libidn2 liblz4 libmd libnettle libnpth libunistring pcre2 termux-am-socket unbound xxhash

The following packages will be upgraded:

apt bash ca-certificates command-not-found coreutils curl dash debianutils dialog diffutils dos2unix dpkg ed findutils gawk gpgv grep gzip inetutils less libandroid-support libc++ libcrypt libcurl libgcrypt libgmp libgpg-error libiconv liblzma libmpfr libnghttp2 libssh2 libtirpc lsof nano ncurses net-tools openssl pcre procps psmisc readline sed tar termux-am termux-exec termux-keyring termux-licenses termux-tools unzip util-linux xz-utils zlib

53 upgraded, 16 newly installed, 2 to remove and 0 not upgraded.

Get:69 Index of /termux-packages-24/ (https://termux.mentality.rip/termux-packages-24) stable/main aarch64 unzip aarch64 6.0-9 [115 kB]

(Reading database ... 3684 files and directories currently installed.)

Preparing to unpack .../openssl_1%3a3.0.7_aarch64.deb ...

Unpacking openssl (1:3.0.7) over (1.1.1h) ...

Setting up openssl (1:3.0.7) ...

Configuration file '/data/data/com.termux/files/usr/etc/tls/openssl.cnf'

*** openssl.cnf (Y/I/N/O/D/Z) [default=N] ? D

--- /data/data/com.termux/files/usr/etc/tls/openssl.cnf 2022-12-05

02:17:37.243613177 -0800

+++ /data/data/com.termux/files/usr/etc/tls/openssl.cnf.dpkg-new 2022-11-01

08:59:04.000000000 -0700

@@ -1,7 +1,9 @@

+# Server authentication

+recipient = "/C=FI/O=Insta Demo/CN=Insta Demo CA" # or set srvcert or issuer

+ignore_keyusage = 1 # potentially needed quirk +unprotected_errors = 1 # potentially needed quirk
