### ISSUE TITLE
Package Request: poetry

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#13773]
### Description

Poetry: Python packaging and dependency management made easy

### Home page URL

https://python-poetry.org

### Source code URL

https://github.com/python-poetry/poetry

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

One of project that i want to try requires poetry to install it's dependencies.

But the requirement for installing this package via pip directly is too big to compile `cryptography` package which require `rust` to compile it (which also took 300 MB+ of storage). 

I do not want to waste 300 MB of space in my phone just to install rust package for compiling `cryptography` package for `poetry`.

**Comment by Grimler91** [comment]
Install cryptography through `pkg`: `pkg install python-cryptography`

If that is the only thing that prevents installation of poetry through pip then we can probably close this package request

**Comment by Yonle** [comment]
> Install cryptography through `pkg`: `pkg install python-cryptography`
> 
> If that is the only thing that prevents installation of poetry through pip then we can probably close this package request

That actually worked. Thanks for the answer.

Closing
