### ISSUE TITLE
[Package]: Pandas

### ISSUE THREAD

**Issue by Indranil012** [termux/termux-packages#13785]
### Why do you want to add this package to Termux?

Pandas need to compile from source on termux and it takes ages to update.
If you could add precompiled pandas package like numpy it would be great.

### Home page URL

https://pandas.pydata.org/

### Source code URL

https://github.com/pandas-dev/pandas

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Just taking some time to build does not fulfill our policy for packaging Python extensions.

**Comment by Indranil012** [comment]
> Just taking some time to build does not fulfill our policy for packaging Python extensions.

1. It's more than some time, like more than 10min.
2. Has some compiling issue needs some workaround.
3. It's so much popular.
If team doesn't want to add another package then ok. 
I requested because numpy is there why not pandas?

**Comment by xtkoba** [comment]
> 2. Has some compiling issue needs some workaround.

This can be a good reason for us to package this. Can you show us what happens when you try to install `pandas` through `pip`?

**Comment by Indranil012** [comment]
> > 2. Has some compiling issue needs some workaround.
> 
> This can be a good reason for us to package this. Can you show us what happens when you try to install `pandas` through `pip`?

Sorry for late reply, I just tried to upgrade pandas to show you the error on latest version. 
But I think they fixed on the latest version. on previous version the `MATHLIB="m"` arg was needed to compile, same as numpy.

**Comment by T-Dynamos** [comment]
Could be added to tur

**Comment by xtkoba** [comment]
Yeah, this is what third-party repos are for.

**Comment by xtkoba** [comment]
Not being buildable on Android 12 (due to phantom process killing) would become a good reason for us to package this. But I don't believe it requires some ridiculous amount of resources to build like Chromium which is not buildable even on GitHub Actions CI.

**Comment by xtkoba** [comment]
```bash
pkg install python-numpy
pip install Cython setuptools wheel
pip install --no-build-isolation pandas
```

What could be controversial is whether `--no-build-isolation` can be considered as trivial or not. I would say it would be trivial if ever well-documented, which unfortunately is not the case as of now (#15048).

Building in GitHub Actions CI is rather trivial. Keeping the package up to date is rather easy because the source code is hosted in GitHub and we can use the auto-update mechanism. Probably it is just a matter of disk space. I will try building it on CI and check the footprint.

BTW, isn't this added in TUR yet?

**Comment by xtkoba** [comment]
Just 10 to 11 MiB per arch. I think this is acceptable.

**Comment by xtkoba** [comment]
Added as a *disabled* package. Maintainers are free to re-enable this. Thanks.

**Comment by licy183** [comment]
Emmm... I'll add this to TUR.

**Comment by Jonaben1** [comment]
python-pandas from TUR package not working on termux. Any atempt to create a DataFrame results in a valueError: expected int_tpt got long long

This renders python-pandas useless in my termux app whereas python-numpy is working. Also, using pip to install doesn't work, not even with MATHLIB='m'

So, please how can I install pandas on termux?

**Comment by djd1226** [comment]
> 

me too,Ran into the same problem！
open csv file:
valueError: expected int_tpt got long long

**Comment by xtkoba** [comment]
TUR things should go to TUR community.

Note that if the package in TUR does not work, then neither does our "official" package if ever enabled.

**Comment by djd1226** [comment]
The problem has been solved，thanks!

**Comment by vbayda-kzn** [comment]
> The problem has been solved，thanks!

how?)

**Comment by Ystyphn** [comment]
> The problem has been solved，thanks!

Yah! How? I tried on using Pydroid 3 for but lots of ads. So how???
