### ISSUE TITLE
Info for maintainers: package uploads will be disabled temporarily 2022-12-10 9:00 am UTC+0

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#13804]
Fosshost will sooner or later [no longer be able to host termux](https://fosshost.org/). We are very grateful for their services over the years, they really were a life saver when we hade to migrate away from bintray. 

As part of migration from fosshost to new vps at Hetzner I will disable package uploads 2022-12-10 at 9:00 am UTC+0. Package downloads from packages.termux.dev will see some short interruptions as well (but other mirrors should work fine).

I imagine that setting everything up and verifying that it works will be done in 2 h.

**Comment by 2096779623** [comment]
Links we need to modify:

https://github.com/termux/termux-packages/wiki/Mirrors
https://github.com/termux/termux-tools/blob/master/mirrors/north_america/packages.termux.dev#L4
https://termux.dev/donate
https://termux.dev/privacy-policy

😢

**Comment by Grimler91** [comment]
@2096779623 thanks, I would have missed half of those

**Comment by Grimler91** [comment]
Accessing packages.termux.dev through apt or otherwise works, as well as uploads through aptly-api, so I'll go ahead and revert the previous commits

**Comment by Grimler91** [comment]
Done: https://github.com/termux/termux-packages/commit/ca931110340480e01e356f01aa0e09ec54d9806a

Now only editing of wiki pages etc remain
