### ISSUE TITLE
[Bug]:my termux is not responding to my commands, i'm using a virtual machine vmos pro, android version 7.1

### ISSUE THREAD

**Issue by ZetWorld258** [termux/termux-packages#13811]
### Problem description

[Bug]:my termux is not responding to my commands, i'm using a virtual machine vmos pro, android version 7.1

### What steps will reproduce the bug?

I dont know

### What is the expected behavior?

I think it would execute commands

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
It is known that Termux does not work well on VMOS environment (search GitHub Issues for "VMOS") which we do not / are not going to support.
