### ISSUE TITLE
Suggestion: Put texlive environment variables in ~/.bashrc. Works for me.

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#13828]
I regularly use TeXlive in Termux (32-bit Android, unrooted). From time to time, after I update using `tlmgr', the texlive configuration files are over-written. The new files no longer have the correct Termux paths, so `tlmgr' fails the next time it is used (sometimes, during the same operation). Termux provides `termux-patch-texlive' but sometimes it does not work as expected, and in any case the interruption is a nuisance.

My solution: Export the TeXlive environmental variables in ~/.bashrc (create it, if necessary). If `tlmgr' sees TEXMFROOT and related top-level variables defined there, then it will ignore whatever is written in texmf.cnf (both texlive/texmf.cnf and texlive/texmf-dist/web2c/texmf.cnf).

Apparently texmfcnf.lua does not have the problem, or it interacts with the set variables. I am not familiar with Lua programming.

Proof of the concept: If I export TEXTMFROOT and a few others from ~/.bashrc, then I can change those variables to nonsense values in texmf.cnf (both files) and TeXlive still works, after relaunch.

This technique is actually mentioned somewhere in TeX documentation (I forget where).

**Comment by xtkoba** [comment]
So how can we implement this in our package? IIRC I saw a package that adds / removes lines for some rc file in its `postinst` / `prerm`, but I cannot find it now. Some GNU/Linux seem to support `/etc/bash/bashrc.d` directory from which `bash` loads rc files, but I don't know if it is supported in the package for Termux.

**Comment by rallg** [comment]
Maybe in etc/profile.d ?

I described this as "suggestion" for users.

**Comment by xtkoba** [comment]
Ah I mistakenly regarded this as a request to devs. So this could be just a matter of documentation.
