### ISSUE TITLE
[Package]: dua

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#13839]
### Why do you want to add this package to Termux?

It can be useful if your storage is full, you can remove unwanted files easier than other tools

### Home page URL

https://github.com/Byron/dua-cli

### Source code URL

https://github.com/Byron/dua-cli

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by SunPodder** [comment]
This package requires a trash bin to work. I doubt we have something like that in termux. A freedesktop compliant trash bin implementation is needed. If it's available, that will require patching this files.
- [lib.rs](https://github.com/Byron/trash-rs/blob/master/src/lib.rs) : line 48 to include android platform
- [freedesktop.rs](https://github.com/Byron/trash-rs/blob/master/src/freedesktop.rs) : to match termux file system

I tried building the package and faced this issue. Leaving this comment for other devs

**Comment by flaribbit** [comment]
I want to add this package too. According to owner's instruction, `trash-move` feature can be disabled by `--no-default-features --features tui-crossplatform`. Other functions works perfect for me. https://github.com/Byron/dua-cli/issues/157

Maybe we can add this package without `trash-move` feature.
