### ISSUE TITLE
[Package]: swirc

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#13845]
### Why do you want to add this package to Termux?

Swirc is a BSD licensed, console based and lightweight ICB and IRC client written in C/C++, whose goals are to be portable and secure.

### What's the difference with the existing packages?
swirc tend to be easier to use & configure, And also has a different TUI than `irssi`, `weechat`, and `senpai`.

### Home page URL

https://www.nifty-networks.net/swirc/

### Source code URL

https://github.com/uhlin/swirc

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

When i finished compile the package, This error shows up after i execute `swirc`:

```
bindtextdomain: Invalid argument
```

**Comment by Yonle** [comment]
I could fix it with simple patch.

```
diff --git a/src/main.cpp b/src/main.cpp
index 8e7f578..188dc6b 100644                                         --- a/src/main.cpp
+++ b/src/main.cpp                                                    @@ -567,12 +567,7 @@ main(int argc, char *argv[])
        xsetlocale = setlocale;                                       
 #ifdef HAVE_LIBINTL_H                                                -#if defined(UNIX)
-       if (bindtextdomain("swirc", SWIRC_BTD_PATH) == NULL) {        -               err_ret("bindtextdomain");
-               return EXIT_FAILURE;
-       }
-#elif defined(WIN32)
+#if defined(WIN32)
        char    *pgm = NULL,
                *str = NULL;

@@ -587,18 +582,9 @@ main(int argc, char *argv[])
                while ((cp = strchr(str, SLASH_CHAR)) != NULL)
                        *cp = '/';
        }
-       if (bindtextdomain("swirc", (str ? str : "")) == NULL) {
-               err_ret("bindtextdomain");
-               return EXIT_FAILURE;
-       }
        free(str);
 #endif
        (void) bind_textdomain_codeset("swirc", "UTF-8");
-
-       if (textdomain("swirc") == NULL) {
-               err_ret("textdomain");
-               return EXIT_FAILURE;
-       }
 #endif

        if (!sighand_init()) {
```

**Comment by Yonle** [comment]
Closing because backspace won't work anymore.

**Comment by aicynide** [comment]
Haha this is the only irc client I've not requested here. Its useless
