### ISSUE TITLE
[Bug]: CI: Using stale bindist mirror for downloading

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#13853]
### Problem description

In GitHub Actions CI, `termux-tools` is built when building a package that depends on `bash`.

Example: https://github.com/termux/termux-packages/actions/runs/3670295387

### What steps will reproduce the bug?

Build a package that depends on `bash` in GitHub Actions CI.

### What is the expected behavior?

`termux-tools` should not be built but instead should be downloded from bindist mirror.

### System information

GitHub Actions.

**Comment by Damaj301damaj-lol** [comment]
I wonder, is this issue limited to Github Action or compiling locally will cause the same issue?

**Comment by Grimler91** [comment]
packages-cf.termux.dev still pointed towards Fosshost VPS instead of new one.

Should be fixed now after updating DNS settings (I mistakenly thought we had a redirect rule to handle packages-cf so did not touch it previously)
