### ISSUE TITLE
[Bug]:$ apt install wireshark-gtk CANNOT LINK EXECUTABLE "apt": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libapt-pkg.so"... Aborted

### ISSUE THREAD

**Issue by Isaac-hub-sudo** [termux/termux-packages#13862]
### Problem description

I need help every time i try to install wireshark-gtk the process is begging canceled i dont know why can you guys help me pls

### What steps will reproduce the bug?

A

### What is the expected behavior?

A

### System information

termux-info:

```

```
Aaa

**Comment by Grimler91** [comment]
Upgrade your packages, `pkg upgrade`
