### ISSUE TITLE
[Package]: libvgm

### ISSUE THREAD

**Issue by GUUser91** [termux/termux-packages#13888]
### Why do you want to add this package to Termux?

This is required for vgm2flac to work. I need vgm2flac to convert VGZ files to flac. ffmpeg can only convert the first 5 seconds of vgz files and vgmstream_cli can't convert vgz files even though vgmstream_cli is also a required dependency for vgm2flac to work.

### Home page URL

https://github.com/ValleyBell/libvgm

### Source code URL

https://github.com/ValleyBell/libvgm

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Looks like no license is specified to me. License specifications that can be found in the repository are only applied to submodules.

The author of this package request can communicate with upstream and ask them to provide license file(s) for the main module(s).

**Comment by GUUser91** [comment]
@xtkoba
So I have to open a new issue and ask upstream to provide license files for libvgm? Is that correct?

**Comment by Grimler91** [comment]
@guuser91 yes, an easy to find LICENSE or COPYING or similar in the repo root is most common way to specify what license(s) apply to the source code

**Comment by GUUser91** [comment]
I found a issue asking about adding a license file to the repo. It hasn't been updated in over a year though
https://github.com/ValleyBell/libvgm/issues/43#issue-574014042
