### ISSUE TITLE
[Bug]: pypy: Unable to (re)build

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#13913]
### Problem description

Package `pypy` fails to (re)build.

Example: https://github.com/termux/termux-packages/actions/runs/3693963421

Excerpt from build log:

```
 (Reading database ... 100%
 (Reading database ... 4146 files and directories currently installed.)
 Preparing to unpack .../coreutils_9.1-2_aarch64.deb ...
 Unpacking coreutils (9.1-2) over (9.1-2) ...
 Preparing to unpack .../dpkg_1.21.12_aarch64.deb ...
 Unpacking dpkg (1.21.12) over (1.21.12) ...
 dpkg: dependency problems prevent configuration of dpkg:
  dpkg depends on coreutils; however:
   Package coreutils is not configured yet.
 
 dpkg: error processing package dpkg (--configure):
  dependency problems - leaving unconfigured
 Errors were encountered while processing:
  dpkg
 E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
 ##[error]Process completed with exit code 100.
```

Failure seems to occur in

https://github.com/termux/termux-packages/blob/7c7674c03bf133f688a9a0d7bab1e2dc3e4ed30a/packages/pypy/build.sh#L182

I'm not familiar with `apt` command (or `dpkg` suite in general) and I cannot solve this on my own.

### What steps will reproduce the bug?

Rebuild `pypy` in GitHub Actions.

### What is the expected behavior?

Should build.

### System information

GitHub Actions.

**Comment by licy183** [comment]
`Unpacking dpkg (1.21.12) over (1.21.12)` is very unusual. I have no idea why this happens. AFAIK the only situation is `apt install --reinstall package`...

**Comment by Grimler91** [comment]
It is weird that it reinstalls packages (`(1.21.12) over (1.21.12)`), but I wonder if it could be solved by specifying `TERMUX_PKG_PRE_DEPENDS=coreutils` for dpkg. That should prevent apt to try to reinstall them at the same time, and might be a good idea in any case.

I'll try to test it locally

**Comment by Grimler91** [comment]
`apt install --reinstall dpkg coreutils` is not enough to trigger this issue, so not sure how apt ends up in this situation in the first place.

In any case, reverting commit https://github.com/termux/termux-packages/commit/75436ef46f1e08b139110435204a3426babaf57d, which was a fix/workaround for termux/termux-packages/issues/3762, seem to fix this. See PR termux/termux-packages#13915.

**Comment by toniistarks** [comment]
System information
