### ISSUE TITLE
[Bug]: we cant install cryptography whiout this:

### ISSUE THREAD

**Issue by mablue** [termux/termux-packages#13924]
### Problem description

https://github.com/termux/termux-packages/issues/9982#issuecomment-1283449362

### What steps will reproduce the bug?

pip install cryptography 

### What is the expected behavior?

installing cryptography whitout bug
on mi9t pro

### System information

termux-info:

```
export RUSTFLAGS=" -C lto=no" && export CARGO_BUILD_TARGET="$(rustc -vV | sed -n 's|host: ||p')" && pip install cryptography
```
please append it to termux `~/.bashrc` 👍

**Comment by xtkoba** [comment]
Use our package.

**Comment by xtkoba** [comment]
See also #12260.
