### ISSUE TITLE
[Package]: TPDNE-dl

### ISSUE THREAD

**Issue by patranger** [termux/termux-packages#13944]
### Why do you want to add this package to Termux?

I have working with cybersecurity for some time and I often have to use OPSEC tools, which is why I try to keep up to date with new tools. I saw that there is a new tool useful during OPSEC for downloading generated AI images. It is worth adding them to the repository because it is useful for the work of cybersecurity specialists.

### Source code URL

https://codeberg.org/nanoory/TPDNE-dl

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by TomJo2000** [comment]
This package may be better housed on the [Termux User Repository(TUR)](https://github.com/termux-user-repository/tur) as it has a very niche usecase,
and [does not meet point 1 of the general packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy:~:text=Packages%20must%20be%20active%2C%20well%2Dknown%20projects)

Quote:
> - Packages must be active, well-known projects
> Software available in major Linux distributions has more chances to be included into Termux repositories. We will not accept outdated, dead projects as well as projects which do not have active community.

**Comment by xtkoba** [comment]
Off-topic but I would say that the well-knownness requirement is kind of a dead letter. (See also #11974.)

**Comment by truboxl** [comment]
We can't afford to keep adding packages when said packages have little to no userbase. At first glance, this tool is nothing more than a single use, glorified image downloader...

**Comment by 2096779623** [comment]
https://github.com/termux-user-repository/tur/issues/187
