### ISSUE TITLE
[ERROR 404]: Not Found; When downloading rootfs

### ISSUE THREAD

**Issue by youknowWhO111** [termux/termux-packages#13946]
### Problem description

![Screenshot_20221216-220231_Termux](https://user-images.githubusercontent.com/120605738/208114981-7a42a0aa-6f8b-4f33-b50d-501d502d5d6f.jpg)

https://kali.download/nethunter-images/current/rootfs/kalifs-armhf-full.tar.xz
Resolving kali.download... 104.18.103.100, 104.18.102.100
Connecting to kali.download|104.18.103.100|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-16 21:56:29 ERROR 404: Not Found.

### What steps will reproduce the bug?

After the codes: ./install-nethunter-termux 
Its the time when I installed kali nethunter

### What is the expected behavior?

It stops and say the Error 404 Not found.

### System information

termux-info:

(```./install-nethunter-termux ```)

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking
