### ISSUE TITLE
Can't install mariadb database . error saying unable to locate pacakge mariadb [Bug]: 

### ISSUE THREAD

**Issue by bishalkar10** [termux/termux-packages#13973]
### Problem description

![Screenshot_2022-12-18-22-06-32-568_com termux](https://user-images.githubusercontent.com/112653391/208309227-93781a0b-b5ca-4c58-96a2-e7b8fcd6d31a.jpg)
That's the result.

### What steps will reproduce the bug?

pkg install mariadb 

The above line you reproduce the bug

### What is the expected behavior?

It will show something like mariadb is installed successfully...

### System information

termux-info:

```
pkg install mariadb
```

**Comment by xtkoba** [comment]
Please always share the output of `termux-info` when filing a bug. I guess your Termux app is just too old.

**Comment by bishalkar10** [comment]
I have installed the app 1 hours ago...
This is version info of the app

**Comment by xtkoba** [comment]
I cannot find the version info anywhere.

**Comment by bishalkar10** [comment]
Dear sir !
Version info is : 0.101
I have attached a screenshot in the previous mail..
Please check it out kindly ....
Or you can try to install mariadb yourself and check out fist hand..

**Comment by xtkoba** [comment]
> Version info is : 0.101

Yeah, that is too old. Maybe you installed it through Google Play? IIRC current latest released version is 0.118.0.

**Comment by bishalkar10** [comment]
So where should I install it...?

**Comment by xtkoba** [comment]
See https://termux.dev/.
