### ISSUE TITLE
Please remove disabled packages from bindist mirrors

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#13971]
To infra team,

The following packages are disabled and are not planned to be re-enabled. Please remove them from bindist mirrors. Thanks.

In main repo:
- [ ] kphp
- [ ] kphp-static
- [ ] kphp-timelib
- [ ] mosh-git
- [ ] php7
- [ ] php7-apache
- [ ] php7-fpm
- [ ] php7-pgsql
- [ ] python-torch
- [ ] python-torch-static
- [ ] python-torchvision
- [ ] rust-nightly-wasm32-unknown-unknown (NEW)
- [ ] rust-src-nightly (NEW)

In x11 repo:
- [ ] love10-static
- [ ] otter-browser

In root repo:
- [ ] aircrack-ng
- [ ] mdk4

**Comment by cobaineraser** [comment]
> To infra team,
> 
> The following packages are disabled and are not planned to be re-enabled. Please remove them from bindist mirrors. Thanks.
> 
> In main repo:
> 
> * [ ]  kphp
> * [ ]  kphp-static
> * [ ]  kphp-timelib
> * [ ]  mosh-git
> * [ ]  php7
> * [ ]  php7-apache
> * [ ]  php7-fpm
> * [ ]  php7-pgsql
> * [ ]  python-torch
> * [ ]  python-torch-static
> * [ ]  python-torchvision
> 
> In x11 repo:
> 
> * [ ]  love10-static
> * [ ]  otter-browser
> 
> In root repo:
> 
> * [ ]  aircrack-ng
> * [ ]  mdk4

**Comment by Grimler91** [comment]
Thanks, removed (or will be next time repo is re-published). Really should look at improving our scripts so this doesn't happen (or at least is easier to detect)
