### ISSUE TITLE
[Bug]: Emacs cannot find libgccjit library

### ISSUE THREAD

**Issue by c4dr01d** [termux/termux-packages#13981]
### Problem description

Hi, I just upgrade my emacs from emacs 27, after upgrading the open emacs, show up this:
```
Warning (initialization): An error occurred while loading ‘/data/data/com.termux/files/home/.emacs.d/init.el’:

Symbol's value as variable is void: comp-enable-subr-trampolines

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
```
Is not enable the Emacs native-compile feature fully?
Also I eval `(native-compile (expand-file-name "~/test.el"))` in ielm, report not found libgccjit

### What steps will reproduce the bug?

1. Clone a emacs config
2. Open emacs
test.el:
``` emacs-lisp
(defun hello (name)
  "Greeting to NAME."
  (message "Hello %s" name))
```

### What is the expected behavior?

Should open Emacs normally and plugins loaded

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=31104
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
Updatable packages:
All packages up to date
termux-tools version:
1.34.1
Android version:
12
Kernel build information:
Linux localhost 5.4.147-qgki-g8656e0196527 #1 SMP PREEMPT Tue Nov 1 03:31:38 CST 2022 aarch64 Android
Device manufacturer:
HONOR
Device model:
NTH-AN00
```

**Comment by xtkoba** [comment]
The jit feature of Emacs requires GCC, which is not available nor is planned to be in our *official* repo.

I suppose you were a user of `emacs` package from its-pointless repo, which provided some GCC-related functionality. You may want to ask other third-party repos (e.g. tur) to add packages with that functionality. We as the official repo are never going to add that. Thanks.
