### ISSUE TITLE
Some of the packages from termux.net don't work with termux-apt-repo

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1398]
Thanks. 

Stable / Testing / Experimental Termux 💪🙂 Distributions are the goals of this issue. Please assist in resolving them ASAP (As Soon As Possible).

g093 @Auxilus some of the packeges from termux.net don't work with terux-apt-repo
g093 subprocess.CalledProcessError: Command '['ar p storage/external-1/debs/termux.net/dists/stable/main/binary-arm/brogue-1.7.4_arm.deb control.tar.xz | tar --to-stdout -xJf - ./control']' returned non-zero exit status 2.
g093 any idea why?
g093 any¹?

IRC/Gitter bot Sep 07 23:59
g093 i wonder how debating GUI & Termux would look at a tech symposium?
![screenshot_20170908-000527](https://user-images.githubusercontent.com/27742457/30195735-72ea9976-9429-11e7-827d-47c12bcfd964.png)

Termux IRC Chat Log https://sdrausty.github.io/logs/ircFreenodeTermuxWeechatlog

https://github.com/termux/termux-apt-repo/issues/2

```
$ termux-apt-repo storage/external-1/debs/termux.net/dists/stable/main/binary-arm/ ty/
```
![screenshot_20170908-004405](https://user-images.githubusercontent.com/27742457/30196470-058778c6-942f-11e7-8f27-f229eea62d58.png)

**Comment by fornwall** [comment]
The problem is that termux-apt-repo assumes that the deb files contains a control.tar.xz.

Termux used a control.tar.gz before b96b5b147c52a7ecb19199431e13c3195823fe66 in january 2016, at which time the switch to .xz was made.

So: Old packages which haven't been rebuilt since january 2016 will have a control.tar.gz file and not work with termux-apt-repo. I think the best course of action is to rebuild them by revision bumping.

**Comment by sdrausty** [comment]
@fornwall thank you for your time and quick reply.

**Comment by fornwall** [comment]
@sdrausty All old packages containing a `control.tar.gz` have now had their revisions bumped and rebuilt - only `control.tar.xz` should now be used!

So termux-apt-repo should work for every current and future deb file - let me know if there are any problems!

**Comment by sdrausty** [comment]
All packages in the arm branch passed with flying colors. Thank you @fornwall

**Comment by sdrausty** [comment]
Arm packages are published at https://sdrausty.github.io/repoArm/ Hopefully this will grow into a backup *.deb for device resource. It is being run in Termux from a smartphone btw.

Please provide your input regarding this binary-arm repository for Termux. Did it work for you? Were you able to use it?

The intended purpose of this Termux repository is for archiving and retrieval of Termux *.deb files in the binary-arm branch from http://termux.net 😀

**Comment by sdrausty** [comment]
All packages in all branch pass with `termux-apt-repo` now. Thank you @fornwall

**Comment by sdrausty** [comment]
@fornwall termux-apt-repo fails in all five repositories https://sdrausty.github.io/logs/termux-apt-repo20171001.log

**Comment by sdrausty** [comment]
@fornwall termux-apt-repo fails on four/five repositories. Please see 👉https://sdrausty.github.io/logs/termux-apt-repo20171001.log

**Comment by sdrausty** [comment]
"/data/data/com.termux/files/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ar p termux.net/dists/stable/main/binary-i686/aapt_7.1.2.33-1_i686.deb control.tar.xz | tar --to-stdout -xJf - ./control']' returned non-zero exit status 2.
