### ISSUE TITLE
[Package]: moc

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#13993]
### Why do you want to add this package to Termux?

MOC (music on console) is a console audio player for LINUX/UNIX designed to be powerful and easy to use.

### Home page URL

http://moc.daper.net/

### Source code URL

http://moc.daper.net/download

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Tried to build this in mobile before, but seems require some unsupported component (like ALSA). Patch is likely possible.

**Comment by xtkoba** [comment]
Does this install `$PREFIX/bin/moc`? If so then this will conflict with `qt5-qtbase`. (Probably also related to #10854.)

**Comment by Yonle** [comment]
The binary that will installed is `mocp`. So hopefully it doesn't conflict with other packages

**Comment by j0hnd3v** [comment]
#1637
