### ISSUE TITLE
[Bug]: mpv: Dynamic linker error with `libgd_1:2.3.3-1`

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#13992]
### Problem description

This was first reported by @Neo-Oli in Gitter. I formally report it here along with a proposed solution.

With `libgd_1:2.3.3-1`, `mpv` aborts with the following message:

```
~ $ mpv
CANNOT LINK EXECUTABLE "mpv": cannot locate symbol "_Z17createHeifDecoderv" referenced by "/system/lib64/libskia.so"...
Aborted
```

`/system/lib64/libskia.so` has `libheif.so` as a `DT_NEEDED` entry, which is intended to refer to `/system/lib64/libheif.so`. On the other hand, `$PREFIX/lib/libgd.so`, which is needed by `mpv`, also has `libheif.so` as a `DT_NEEDED` entry, which refers to `$PREFIX/lib/libheif.so`. As these two `libheif.so`s have the same `DT_SONAME` `libheif.so`, one of them is overshadowed by the other.

Note that we had once a similar issue with `openssl`: #9174. A workaround for this is to set a different `DT_SONAME` to Termux one from system one.

### What steps will reproduce the bug?

Install `mpv` and launch it. Make sure that the version of `libgd` is `1:2.3.3-1`.

### What is the expected behavior?

`mpv` should run and exit normally.

I already have a proposed solution: #13991.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=22957
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.34.1
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.82-perf+ #1 SMP PREEMPT Wed Feb 27 13:05:28 CST 2019 aarch64 Android
Device manufacturer:
asus
Device model:
ASUS_X01AD
```

**Comment by Neo-Oli** [comment]
Oh wow, I guess this was a lot more complicated than a simple version bump this time :fearful:
