### ISSUE TITLE
Compiling on Atom processor doesn't quite work

### ISSUE THREAD

**Issue by MatthewTurk** [termux/termux-packages#14]
The spec file on my Dell Venue 8 was giving odd errors, just like @fornwall reported here: http://stackoverflow.com/questions/31815737/cross-compiled-gcc-fails-with-unrecognised-emulation-mode-dynamic-linker#

I was able to get around this (and so far all my python packages other than numpy work, with some modification to the `_sysconfigdata.py` file) by changing the spec file to be:

```
# Android 5 requires position-independent executables, so we use the
#   %{!S:X}     Substitutes X, if the -S switch is not given to GCC"
# construct (see https://gcc.gnu.org/onlinedocs/gcc/Spec-Files.html for full reference)
# to add -fPIE and -pie flags as appropriate.

*cc1_options:
+ %{!fpie: %{!fPIE: %{!fpic: %{!fPIC: %{!fno-pic:-fPIE}}}}}

*link_emulation:
elf_i386

*dynamic_linker:
%{mglibc:/lib/ld-linux.so.2;:%{muclibc:/lib/ld-uClibc.so.0;:/system/bin/linker}}

*link:
+ %{!nopie: %{!static: %{!shared: %{!nostdlib: %{!nostartfiles: %{!fno-PIE: %{!fno-pie: -pie}}}}}}} 
```

**Comment by MatthewTurk** [comment]
This has worked for me, and I've now been able to successfully compile most everything.

One issue I've run into is that numpy tries particularly hard to set its own environment; this resulted in incorrect linkages (which I believe were across toolkits) that included the `R_386_TLS_DTPMOD32` symbol.  Once I am able to set up an environment that allows me to build packages I will try to contribute a package for NumPy; it consists of setting `LDFLAGS="-L/system/lib -lm`, exporting `NPY_NO_SMP=1` and changing `numpy/core/setup_common.py` to have `OPTIONAL_VARIABLE_ATTRIBUTES = []` instead of its current value.  Once I am able to build packages I'll start a new issue and include a PR adding numpy.

**Comment by fornwall** [comment]
Great work on this @MatthewTurk! There is an updated gcc package (version `4.9.3-3`) available in the apt repo now, with the following change: 4d685cb66901d61e98e64edf9eb22a4194a38216.

For the dynamic linker It only has:

    *dynamic_linker:
    /system/bin/linker

Are the other entries that you mentioned necessary under some configuration here?

**Comment by MatthewTurk** [comment]
@fornwall I'm not sure yet -- I've run into a few issues with needing `-fno-gnu-unique` and needing to manually link against libraries in `/system/lib` but I'm not yet sure if they are specific to python packages or not.

**Comment by fornwall** [comment]
@MatthewTurk I'm closing this issue since compiling on i686 works now, great job finding the problem!

Let's open new issues if there are remaining general problems (or specific problems building python packages than can be fixed).
