### ISSUE TITLE
Package request: alpine

### ISSUE THREAD

**Issue by scateu** [termux/termux-packages#140]
Pine/Alpine is a mail client with a long history.

Some of alpine/pine users:
- Linus Torvalds
- Former CEO of Yahoo
- CERN

Homepage:

http://patches.freeiz.com/alpine/release/

**Comment by Neo-Oli** [comment]
Hi, I am re-opening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by scateu** [comment]
Hi, all

Any news on this?

--

**Comment by BryanLunduke** [comment]
Just would like to add in that this would be excellent.  Alpine in Termux would be incredibly handy.

**Comment by its-pointless** [comment]
for the sake of completeness this actually compiles and works from disabled. Its available in my repo.

**Comment by scateu** [comment]
Is there a tutorial to test the alpine from the `disabled-packages` directory?

**Comment by its-pointless** [comment]
Iv got it on my repo. Updated and fixed a few things. 

_Sent from my Htc HTC 2PS6200 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by reinob** [comment]
Thanks for providing alpine!

Would it be possible to ./conifgure it with "--with-passfile=.pine-passfile" so that it saves passwords? (otherwise it's a bit of pain on mobile..)

Thanks a lot.

**Comment by fornwall** [comment]
@its-pointless Would you like to submit a PR updating and enabling alpine?

**Comment by Auxilus** [comment]
@scateu Alpine is available by `pkg install alpine`
