### ISSUE TITLE
Creating Files/Folders in postinst

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#1401]
https://github.com/termux/termux-packages/blob/45a524ed4345a842b209d61e2966d8ce77d6f733/packages/moria/build.sh#L20-L21
This is a very minor thing. Moria creates this file in the postinst, so that scores don't get erased when the package updates. While this is a good thing, it leads to several undesirable consequences:
* If moria is removed, this file and folder remains. 
* If another program that creates $PREFIX/var/games, like emacs, gets uninstalled the following warning is printed:
`dpkg: warning: while removing emacs, directory '/data/data/com.termux/files/usr/var/games' not empty so not removed`

Is there perhaps a better way to achieve the goal that updates don't erase scores without the undesirable consequences?

**Comment by Grimler91** [comment]
python (with packages installed through pip) and texlive (with packages installed through tlmgr) have the same problem as point 1. 

There, we have these kind of `prerm` scripts:
```
echo "#!$TERMUX_PREFIX/bin/sh" > prerm:
echo 'if [ $1 != "remove" ]; then exit 0; fi' >> prerm
echo '{remove everything that apt don't know about}' >> prerm
```

If we uninstall the package then the files are removed, but if we upgrade they are left alone.

This doesn't solve point 2 though.
