### ISSUE TITLE
Auto update failing for leptonica

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#14022]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the leptonica package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating leptonica [Current version: 1.82.0]
INFO: package being updated to 1.83.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 8276k    0 8276k    0     0  8747k      0 --:--:-- --:--:-- --:--:-- 8747k
100 12.5M    0 12.5M    0     0  8959k      0 --:--:--  0:00:01 --:--:-- 9387k

You are about to commit these changes:

--------------------
diff --git a/packages/leptonica/build.sh b/packages/leptonica/build.sh
index 25fa10d40..92cfe6eca 100644
--- a/packages/leptonica/build.sh
+++ b/packages/leptonica/build.sh
@@ -3,10 +3,9 @@ TERMUX_PKG_DESCRIPTION="Library for image processing and image analysis"
 TERMUX_PKG_LICENSE="BSD 2-Clause"
 TERMUX_PKG_LICENSE_FILE="leptonica-license.txt"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION=1.82.0
-TERMUX_PKG_REVISION=2
+TERMUX_PKG_VERSION="1.83.0"
 TERMUX_PKG_SRCURL=https://github.com/DanBloomberg/leptonica/archive/${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=40fa9ac1e815b91e0fa73f0737e60c9eec433a95fa123f95f2573dd3127dd669
+TERMUX_PKG_SHA256=14cf531c2219a1414e8e3c51a3caa5cf021a52e782c4a6561bf64d0ef2119282
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_DEPENDS="giflib, libjpeg-turbo, libpng, libtiff, libwebp, openjpeg, zlib"
 TERMUX_PKG_BREAKS="leptonica-dev"
--------------------

bump(main/leptonica): 1.83.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package leptonica exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building leptonica for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  25089      0 --:--:-- --:--:-- --:--:-- 25064
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1427      0 --:--:-- --:--:-- --:--:--  1426
100   833  100   833    0     0   1427      0 --:--:-- --:--:-- --:--:--  1426
gpg: Signature made Tue 20 Dec 2022 07:33:48 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  21447      0 --:--:-- --:--:-- --:--:-- 21483
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1486      0 --:--:-- --:--:-- --:--:--  1484
100   833  100   833    0     0   1486      0 --:--:-- --:--:-- --:--:--  1484
gpg: Signature made Tue 20 Dec 2022 05:15:45 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  26683      0 --:--:-- --:--:-- --:--:-- 26720
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1560      0 --:--:-- --:--:-- --:--:--  1559
gpg: Signature made Tue 20 Dec 2022 05:22:09 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency giflib@5.2.1-2 if necessary...
Found giflib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/giflib/giflib_5.2.1-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16968  100 16968    0     0   119k      0 --:--:-- --:--:-- --:--:--  120k
extracting giflib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency giflib-utils@5.2.1-2 if necessary...
Found giflib-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/giflib-utils/giflib-utils_5.2.1-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 51642  100 51642    0     0  82980      0 --:--:-- --:--:-- --:--:-- 82892
extracting giflib-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libjpeg-turbo@2.1.4 if necessary...
Found libjpeg-turbo in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libj/libjpeg-turbo/libjpeg-turbo_2.1.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 10  276k   10 29553    0     0  55404      0  0:00:05 --:--:--  0:00:05 55342
100  276k  100  276k    0     0   494k      0 --:--:-- --:--:-- --:--:--  494k
extracting libjpeg-turbo to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libjpeg-turbo-progs@2.1.4 if necessary...
Found libjpeg-turbo-progs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libj/libjpeg-turbo-progs/libjpeg-turbo-progs_2.1.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 82248  100 82248    0     0   142k      0 --:--:-- --:--:-- --:--:--  142k
extracting libjpeg-turbo-progs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency zlib@1.2.13 if necessary...
Skipping already built dependency zlib@1.2.13
Downloading dependency libpng@1.6.39 if necessary...
Found libpng in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libp/libpng/libpng_1.6.39_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  191k  100  191k    0     0  1428k      0 --:--:-- --:--:-- --:--:-- 1425k
extracting libpng to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libc++@25b if necessary...
Found libc++ in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libc/libc++/libc++_25b_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  215k  100  215k    0     0  1350k      0 --:--:-- --:--:-- --:--:-- 1356k
extracting libc++ to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency liblzma@5.4.0 if necessary...
Found liblzma in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libl/liblzma/liblzma_5.4.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  172k  100  172k    0     0  1104k      0 --:--:-- --:--:-- --:--:-- 1106k
extracting liblzma to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xz-utils@5.4.0 if necessary...
Found xz-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xz-utils/xz-utils_5.4.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 63304  100 63304    0     0   406k      0 --:--:-- --:--:-- --:--:--  406k
extracting xz-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency zstd@1.5.2-2 if necessary...
Found zstd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/z/zstd/zstd_1.5.2-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  260k  100  260k    0     0  1299k      0 --:--:-- --:--:-- --:--:-- 1295k
extracting zstd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pzstd@1.5.2-2 if necessary...
Found pzstd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pzstd/pzstd_1.5.2-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  157k  100  157k    0     0   753k      0 --:--:-- --:--:-- --:--:--  755k
extracting pzstd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libtiff@4.5.0 if necessary...
Found libtiff in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libt/libtiff/libtiff_4.5.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  850k  100  850k    0     0  5210k      0 --:--:-- --:--:-- --:--:-- 5216k
extracting libtiff to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libtiff-utils@4.5.0 if necessary...
Found libtiff-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libt/libtiff-utils/libtiff-utils_4.5.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  245k  100  245k    0     0  1543k      0 --:--:-- --:--:-- --:--:-- 1542k
extracting libtiff-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libwebp@1.2.4-1 if necessary...
Found libwebp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libw/libwebp/libwebp_1.2.4-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  208k  100  208k    0     0   391k      0 --:--:-- --:--:-- --:--:--  392k
extracting libwebp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency littlecms@2.14-1 if necessary...
Found littlecms in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/littlecms/littlecms_2.14-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  131k  100  131k    0     0   252k      0 --:--:-- --:--:-- --:--:--  252k
extracting littlecms to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency littlecms-utils@2.14-1 if necessary...
Found littlecms-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/littlecms-utils/littlecms-utils_2.14-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 34668  100 34668    0     0   236k      0 --:--:-- --:--:-- --:--:--  236k
extracting littlecms-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openjpeg@2.5.0-1 if necessary...
Found openjpeg in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/o/openjpeg/openjpeg_2.5.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 10  141k   10 15880    0     0  30660      0  0:00:04 --:--:--  0:00:04 30656
100  141k  100  141k    0     0   263k      0 --:--:-- --:--:-- --:--:--  263k
extracting openjpeg to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openjpeg-tools@2.5.0-1 if necessary...
Found openjpeg-tools in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/o/openjpeg-tools/openjpeg-tools_2.5.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 61100  100 61100    0     0   502k      0 --:--:-- --:--:-- --:--:--  505k
extracting openjpeg-tools to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/DanBloomberg/leptonica/archive/1.83.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 1252k    0 1252k    0     0  2164k      0 --:--:-- --:--:-- --:--:-- 2164k
100 12.5M    0 12.5M    0     0  9142k      0 --:--:--  0:00:01 --:--:-- 13.7M
Applying patch: silence-tmpfile-warnings.patch
2 out of 2 hunks FAILED -- saving rejects to file src/boxbasic.c.rej
1 out of 1 hunk FAILED -- saving rejects to file src/colormap.c.rej
2 out of 2 hunks FAILED -- saving rejects to file src/dewarp1.c.rej
2 out of 2 hunks FAILED -- saving rejects to file src/fpix1.c.rej
1 out of 1 hunk FAILED -- saving rejects to file src/jp2kio.c.rej
1 out of 1 hunk FAILED -- saving rejects to file src/jpegio.c.rej
2 out of 2 hunks FAILED -- saving rejects to file src/numabasic.c.rej
2 out of 2 hunks FAILED -- saving rejects to file src/pixabasic.c.rej
1 out of 1 hunk FAILED -- saving rejects to file src/pixcomp.c.rej
2 out of 2 hunks FAILED -- saving rejects to file src/pnmio.c.rej
2 out of 2 hunks FAILED -- saving rejects to file src/ptabasic.c.rej
1 out of 1 hunk FAILED -- saving rejects to file src/sarray1.c.rej
1 out of 1 hunk FAILED -- saving rejects to file src/utils2.c.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2022-12-21 00:34:35 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/3745208321">3745208321</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by xtkoba** [comment]
This involves SOVERSION bump and should not be auto-updated.
