### ISSUE TITLE
[Package]: mat2 deleting file metadata

### ISSUE THREAD

**Issue by snooppr** [termux/termux-packages#14023]
### Why do you want to add this package to Termux?

A popular GNU utility for removing file metadata.  Unlike exiftool, it supports more formats, such as .aac/.mp3...
Algorithms not only clear tags, but also compress files to remove "bookmarks".

### Home page URL

https://0xacab.org/jvoisin/mat2

### Source code URL

https://0xacab.org/jvoisin/mat2

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

`$ pip install mat2` 
fails because  classical linux dependencies are required.

**Comment by xtkoba** [comment]
What do you mean by "classical linux dependencies"? For me `pip install mat2` succeeds. Note that mat2 depends on PyGObject and pycairo, for which we have packages on our own (`pygobject` and `pycairo` respectively.)

**Comment by snooppr** [comment]
Collecting mat2
  Using cached mat2-0.13.0-py3-none-any.whl (39 kB)
Collecting PyGObject
  Using cached PyGObject-3.42.2.tar.gz (719 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting mutagen
  Using cached mutagen-1.46.0-py3-none-any.whl (193 kB)
Collecting pycairo
  Using cached pycairo-1.23.0-cp310-cp310-linux_armv7l.whl
Building wheels for collected packages: PyGObject
  Building wheel for PyGObject (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for PyGObject (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-310
      creating build/lib.linux-armv7l-cpython-310/pygtkcompat
      copying pygtkcompat/__init__.py -> build/lib.linux-armv7l-cpython-310/pygtkcompat
      copying pygtkcompat/pygtkcompat.py -> build/lib.linux-armv7l-cpython-310/pygtkcompat
      copying pygtkcompat/generictreemodel.py -> build/lib.linux-armv7l-cpython-310/pygtkcompat
      creating build/lib.linux-armv7l-cpython-310/gi
      copying gi/__init__.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/module.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/docstring.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/pygtkcompat.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/importer.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/_gtktemplate.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/types.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/_propertyhelper.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/_signalhelper.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/_ossighelper.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/_option.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/_constants.py -> build/lib.linux-armv7l-cpython-310/gi
      copying gi/_error.py -> build/lib.linux-armv7l-cpython-310/gi
      creating build/lib.linux-armv7l-cpython-310/gi/repository
      copying gi/repository/__init__.py -> build/lib.linux-armv7l-cpython-310/gi/repository
      creating build/lib.linux-armv7l-cpython-310/gi/overrides
      copying gi/overrides/__init__.py -> build/lib.linux-armv7l-cpython-310/gi/overrides
      copying gi/overrides/Gtk.py -> build/lib.linux-armv7l-cpython-310/gi/overrides
      copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-armv7l-cpython-310/gi/overrides
      copying gi/overrides/keysyms.py -> build/lib.linux-armv7l-cpython-310/gi/overrides
      copying gi/overrides/GLib.py -> build/lib.linux-armv7l-cpython-310/gi/overrides
      copying gi/overrides/GdkPixbuf.py -> build/lib.linux-armv7l-cpython-310/gi/overrides
      copying gi/overrides/GObject.py -> build/lib.linux-armv7l-cpython-310/gi/overrides
      copying gi/overrides/Gdk.py -> build/lib.linux-armv7l-cpython-310/gi/overrides
      copying gi/overrides/Gio.py -> build/lib.linux-armv7l-cpython-310/gi/overrides
      copying gi/overrides/Pango.py -> build/lib.linux-armv7l-cpython-310/gi/overrides
      running build_ext
      Package 'gobject-introspection-1.0' requires 'glib-2.0 >= 2.74.0' but version of glib-2.0 is 2.72.1
      Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.56.0')' returned non-zero exit status 1.

      Try installing it with: 'sudo apt install libgirepository1.0-dev'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyGObject
Failed to build PyGObject
ERROR: Could not build wheels for PyGObject, which is required to install pyproject.toml-based projects

pygobject pycairo of course installed

**Comment by xtkoba** [comment]
> Using cached pycairo-1.23.0-cp310-cp310-linux_armv7l.whl

Are you using Python 3.10? Our official `python` is Python 3.11 and we do not support other versions.

**Comment by snooppr** [comment]
> > Using cached pycairo-1.23.0-cp310-cp310-linux_armv7l.whl
> 
> Are you using Python 3.10? Our official `python` is Python 3.11 and we do not support other versions.

yes...

**Comment by xtkoba** [comment]
Oh, no. You may want to upgrade asap. Note that if we ever packaged `mat2` it would be for Python 3.11 (or any one particular version we support at that time.)

**Comment by snooppr** [comment]
There are many things that don't work in python3.11 so I'm in no rush to update it.  
The meaning is clear, I will close the problem.

**Comment by snooppr** [comment]
There are many things that don't work in python3.11 so I'm in no rush to update it.  
The meaning is clear, I will close the problem.

**Comment by ticklemyIP** [comment]
Would anyone mind taking a look at this?

https://github.com/termux/termux-app/issues/3707
