### ISSUE TITLE
[Package]: xkbcomp/localegen

### ISSUE THREAD

**Issue by Zeioth** [termux/termux-packages#14031]
### Why do you want to add this package to Termux?

To choose my keyboad/DE language. It is critical for my case of use.

### Source code URL

https://archlinux.org/packages/extra/x86_64/xorg-xkbcomp/

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
We already have `xorg-xkbcomp` package.

**Comment by xtkoba** [comment]
We do not have `locale-gen` and it is not going to be packaged because Bionic libc does not have decent locale support (other than `C.UTF-8`.)

**Comment by Zeioth** [comment]
I saw xorg-xkbcomp but you cannot change your kb distribution w/ that right? It's only to generate keymaps.

**Comment by xtkoba** [comment]
I understand that `xkbcomp` is a command as such. If the behavior of the command is different from the one in GNU/Linux, then you may want to file a bug.

**Comment by Zeioth** [comment]
Ok I just realized the typo on my message. The necessary package to set your keymap is 'setxkbmap'.
