### ISSUE TITLE
[Package]: setxkbmap

### ISSUE THREAD

**Issue by Zeioth** [termux/termux-packages#14035]
### Why do you want to add this package to Termux?

To change my keyboard distribution to spanish/spain.

### Source code URL

https://archlinux.org/packages/extra/x86_64/xorg-setxkbmap/

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Zeioth** [comment]
cannot test it, do I need to add some testing repo?

**Comment by xtkoba** [comment]
Just download the artifact (zip file) from GitHub Actions and extract and install the DEB file in it.

**Comment by Zeioth** [comment]
Dependencies required: 

    The following packages have unmet dependencies:
    xorg-setxkbmap:arm : Depends: libx11:arm but it is not installable
                          Depends: libxkbfile:arm but it is not installable
                          Depends: libxrandr:arm but it is not installable


![Screenshot_20221222_160333_Termux.jpg](https://user-images.githubusercontent.com/3357792/209162919-fabf9fcd-f358-4254-9252-f8245114fc7b.jpg)

**Comment by xtkoba** [comment]
Could it be that you are on aarch64 environment? Also make sure to subscribe to x11-repo.

**Comment by Zeioth** [comment]
aarch64 installs correctly thank you. I'm gonna try to change my kb layout and confirm the case of use is solved.

**Comment by Zeioth** [comment]
Ok so here is my report:

* **I3**: Works as expected. Having the I3 setting xkb_layout "es" on the config file is enough.
* **XFCE4**: Seems to ignore changing kb distribution from xfce settings (researching why). Running "setxkbmap es" at startup works fine.

**Comment by Zeioth** [comment]
Opened a ticket on EXO. Will close if confirmed it's a termux xfce4-settings issue.
https://gitlab.xfce.org/xfce/exo/-/issues/95

**Comment by Zeioth** [comment]
I figure out how to fix xfce setting keyboard layout:

We need to provide the symbolic link:

    ln -s "/data/data/com.termux/files/usr/bin/xkbcomp" "/data/data/com.termux/files/usr/share/X11/xkb/xkbcomp"

That make "xfce setting keyboard layout" work fine. The reason can be tested with the command

    "xfsettingsd --replace"

This outputs that 'libxklavier' cannot execute 'xkbcomp' becaure It expects it to be in  '/share/X11/xkb/xkbcomp' but it actually is in '/bin/xkbcomp'.

**Comment by Zeioth** [comment]
Please submit said symbolic link through the package you consider optimal. After that, this can be closed.

**Comment by xtkoba** [comment]
Should instead fix the path to `xkbcomp`.

**Comment by Zeioth** [comment]
Linking the package here in case someone might need it:
https://github.com/termux/termux-packages/actions/runs/3764124625
