### ISSUE TITLE
Running Desktop Env from proot (and DeX)

### ISSUE THREAD

**Issue by rudolphpienaar** [termux/termux-packages#14039]
# Abstract 

Running a Desktop Env (DE) from within a `termux` `proot` in `termux-x11` is desirable for many reasons. A `proot` will often be a more complete and "standard" Linux experience offering many more X11 applications than currently available in stock `termux`. Currently, however, this is problematic, as in my anecdotal experience I can't seem to run any DE from the `proot`, with success only if the `termux` host runs the DE. While a closed older issue did address running a DE from a `proot`, the solution no longer seems to be working.

# Introduction

I've been trying (and failing) to successfully and reliably run a desktop env (DE) from within a `proot-login`.  The reasons for `proot-login` DE ability are of course obvious -- a `proot`, being a more "conventional" Linux installation, offers considerably more DE envs and X11 applications than the standard `termux` env which only seems to have `xfce4` and very few X11 apps (no `firefox` / `thunderbird` for example).

# Sources 

There are several documented solutions (none of which work for me as of late November 2022). Most relevant is the closed issue  [#138](https://github.com/termux/termux-x11/issues/138) but there are others --  [udroid](https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/quick-installation-and-usage/setting-up-gui/termux-x11) and various postings on reddit of varying utility [here](https://www.reddit.com/r/termux/comments/plvjsn/termuxx11_and_prootdistro_combination_not_working/), I thought to open an issue here as a central place to keep track.

# Environment

My setup is a Samsung Galaxy Z Fold 3, hooked up to an external monitor that triggers DeX. By default, any attempt at running `termux-x11` or even some `vnc` type solution will almost always die within a few minutes being killed by Android.  A _hack_ solution seems to be setting `max_phantom_processes` -- see [here](https://issuetracker.google.com/issues/205156966?pli=1) and a solution [here](https://github.com/termux/termux-app/issues/2366).

# Previously proposed solution (not fully  working for reasons unknown)

The core solution offered entails running/starting the `termux-x11` `Xwayland` server in `termux`, and then _sharing_ the relevant UNIX domain socket that is created in the `termux` `$XDG_RUNTIME_DIR` with the `proot` environment. In this manner, X11 apps in the `proot` can communicate with the `Xwayland` server instance. 

In summary, in `termux`:

```bash

# In termux, set some vars...
# First, enable PulseAudio over Network
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

# Prepare termux-x11 session
export XDG_RUNTIME_DIR=${TMPDIR}
termux-x11 :0 >/dev/null &

```

Now, enter the `proot`. Critically, note the `--shared-tmp` flag -- this is the _magic sauce_ that allows the `proot` to share the same `tmp` directory (`$XDG_RUNTIME_DIR`) between the host and `proot`):

```bash
proot-distro login archlinux --shared-tmp 
```

Obviously, in my above example, my `proot` is an Arch linux chroot. Now, in this `proot`, assuming I have installed `xfce4`, the concept is to simply run `xfce4-session` and it should connect to the `Xwayland` server running in the host `termux`:

```bash
# This is in the proot. Here, $TMPDIR is /tmp...
# Also, this doesn't work
export XDG_RUNTIME_DIR=${TMPDIR}
env DISPLAY=:0 xfce4-session
```

(Note that some documentation erroneously indicates to run `env DISPLAY=:0 startxfce4` -- however `startxfce4` is a wrapper that tries to start an X server. Since an Xserver is already running in the host, this will result in an `X server already running` error).

# Observed behaviour

I haven't been able to ever get the `xfce4` (or any other DE) started in the `proot` to connect to the host `Xwayland`. What _has_ worked for me is to run/start the DE in `termux`. Since `termux` only seems to offer `xfce4` this is the only environment possible:

```bash
# This works, but only when run in the termux host
export XDG_RUNTIME_DIR=${TMPDIR}
env DISPLAY=:0 xfce4-session
```

Now, in the `xfce4` DE, I can open a `terminal` and within that terminal I can `proot-distro login archlinux --shared-tmp`. At this point, I'm in a DE in the `termux`, but my terminal is now open onto the `proot`. I can then 

```bash
export DISPLAY=:0
firefox &
```

which runs the `firefox` from the `proot` and displays on the `termux` `Xwayland`.

# Oddities?

Any application in the `proot` that wants to communicate on `dbus` seems to fail. Luckily `firefox` doesn't use `dbus` but many other modern apps do (so `gnome-terminal` won't work, but `terminator` will). This limits the space of available applications considerably, but does hint at the fact that `dbus` communication might be the issue? 

I have tried many permutations, without success:

* setting my user `UID` in the `proot` to be the same `UID` as in the `termux` host. _Doesn't help_
* tried various `chmod  777 /tmp/dbus*` to see if I can speak to `dbus` from the `proot`. _Doesn't help_

# Other annoyances

* Often the `termux-x11` "window" opens full screen (without the DeX window decoration), but the colors seem "washed out". I can close the window and reopen it, and the colors seem fine, but the annoying Dex top window bar returns.
* The `termux-x11` always seems to have a very annoying button bar at the bottom with `Esc`, and what looks like cursor directions. I can't seem to get rid of this and it is very annoying.

**Comment by xtkoba** [comment]
So what did the author of this document ask us to do?

Closing as not worth keeping open. Discussions are welcome though. Thanks.

**Comment by rudolphpienaar** [comment]
This is amazing @ShapeShifter499 ! I should update my original posting to reflect this perhaps, but your guide essentially made my whole day/month/year.

Some notes/comments? I can't seem to reliably get `adb` shell access from within `termux`. I can pair. Sometimes it connects. It never seems though to work beyond that . For setting the `settings_enable_monitor_phantom_procs` I use the Play Store app, `LADB`.

Another fun "struggle"... getting any DE other than `xfce4` to work. Most of the usual suspects, `GNOME`, `KDE`, and derivativess complaing from the get go about `dbus` issues. I have tried a couple of stabs-in-the-dark -- setting my UID within `proot` to be the same as the host `termux` (didn't help).

Have you had success with any DE other than `xfce4`?

**Comment by ShapeShifter499** [comment]
> Some notes/comments? I can't seem to reliably get `adb` shell access from within `termux`. I can pair. Sometimes it connects. It never seems though to work beyond that . For setting the `settings_enable_monitor_phantom_procs` I use the Play Store app, `LADB`.

I had not heard of `LADB` so I'm glad that worked out for you. 

> Have you had success with any DE other than `xfce4`?

The only other desktop environment I've tried with so far was Gnome. I couldn't get it working and it is possible it might not work unmodified as it's starting to rely more and more on SystemD. SystemD unmodified can't run in proot as it wants to start as PID 1.  I've seen some efforts online to get Gnome working with SystemD but I've not tried those yet. 


But for the most part Gnome apps and others should work fine in XFCE as long as they don't rely on SystemD or dbus. For example I was using `gThumb` and `gscan2pdf` to help me compile documents I scanned or took photos of into pdf files earlier just fine. 

A cool thing to note.  If you have set up android file permissions for termux and run `termux-setup-storage`, `proot-distro` will by default bind the default android storage location to `/sdcard` inside the proot session allowing the proot distro to read-write files to your normal android storage location.  To add to that however, in my experience some applications could read files but not write for some reason. For example I couldn't write the compiled pdf with `gscan2pdf` outside the proot but I could use `thunar` to manually move the generated pdfs out of `/home` to the `/sdcard` directory and `gThumb` was able to view and delete the photos I pointed it to. I'm not actually sure why that was but something to keep in mind if you experience any read-write issues to the simulated `/sdcard` directory.  

That auto bind feature for the storage can be disabled by passing `--isolated` as mentioned at https://github.com/termux/proot-distro

**Comment by jsommr** [comment]
Have the same issue with running XFCE on a Surface Go 2/BlissOS with Debian proot. Can also render Firefox in termux-x11 (with poor performance), but when running `DISPLAY=:0 xfce4-session --display=:0`, termux-x11 is just a black screen and a cursor. There are no warnings and no errors, the command just hangs until SIGINT'ed.

**Comment by twaik** [comment]
Closing this as inactive.
