### ISSUE TITLE
Travis CI fails on new trusty images

### ISSUE THREAD

**Issue by stephengroat** [termux/termux-packages#1403]
Open an issues with travis-ci https://github.com/travis-ci/travis-ci/issues/8375

**Comment by Auxilus** [comment]
I think https://github.com/termux/termux-packages/pull/1361 is a big cause ( which I'm really feeling sorry for )

**Comment by Auxilus** [comment]
Also https://github.com/termux/termux-packages/pull/1400 ain't working cz its not even downloading the docker image..

**Comment by stephengroat** [comment]
no problem, the more builds the merrier. i trigger a bunch too

afaik, builds should be independent of each other (unless build artifacts are being maintained, which they're not). it might have something to do with the **huge** amount of logs that these builds are creating (which travis does keep), but i don't know

**Comment by stephengroat** [comment]
https://github.com/termux/termux-packages/pull/1399/commits/92b5d263d980261be6afa7c124e98f4436f99e05 seems to fix it, included in #1399

**Comment by Auxilus** [comment]
Is this was causing https://github.com/termux/termux-packages/pull/1400 to fail?

**Comment by stephengroat** [comment]
@Auxilus not sure, doesn't seem like that same problem but COULD be related

**Comment by Auxilus** [comment]
I think its related cz it doesn't even bothers to download the docker image!

**Comment by sdrausty** [comment]
To @whoeverfixxedthis 👉THANK YOU🚣🚢⛵

**Comment by sdrausty** [comment]
Do u trust travis?

**Comment by sdrausty** [comment]
How can u tell travis to build something on device in Termux?

android
?

**Comment by stephengroat** [comment]
@sdrausty travis is trustworthy, building thousands of open source projects every day. since travis is cross-compiling using the Android NDK, it can build for android

**Comment by sdrausty** [comment]
@stephengroat thanks for your answer. More specifically: How can I tell Travis to build like we are building in Termux on device?

I'd like to create a .travis.yml for https://github.com/sdrausty/buildAPKs which is designed to build on device in Termux. How can I tell Travis to do that?

**Comment by stephengroat** [comment]
@sdrausty right now there's no way to do that. that would require a full android emulation

it's possible, just not implemented yet. something you're interested in looking into? travis has some examples of emulating apps (https://docs.travis-ci.com/user/languages/android/#How-to-Create-and-Start-an-Emulator)

**Comment by sdrausty** [comment]
@stephengroat thanks for the link. I am definitely interested in this topic. Any idea what jdk: in .travis.yml for emulating Termux might be?

**Comment by stephengroat** [comment]
@sdrausty i'd just pick the latest

**Comment by sdrausty** [comment]
thanks :)

**Comment by stephengroat** [comment]
this *might* be solved, testing now

**Comment by stephengroat** [comment]
closing for now, travis _seems_ to have silently fixed the issue
