### ISSUE TITLE
[Bug]: libsoxr package not compiled correctly in pacman

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#14032]
### Problem description

The libsoxr package in pacman format does not contain some files that are associated with the library (eg `libsoxr.so.0`). The `lib` directory contains only the following files:
```
/data/data/com.termux/files/usr/lib/libsoxr-lsr.so
/data/data/com.termux/files/usr/lib/libsoxr.so
```

All additional information is located here https://github.com/termux-pacman/termux-packages/issues/4.

### What steps will reproduce the bug?

Compilation

### System information

All information here https://github.com/termux-pacman/termux-packages/issues/4.

**Comment by xtkoba** [comment]
Rather I wonder why our DEB package contains libraries with SOVERSION suffix. The build system for `libsoxr` is CMake, which for Android does not append SOVERSION suffix by default.

**Comment by xtkoba** [comment]
OK, rebuilding `libsoxr` (for DEB package) removes SOVERSION suffixes. Just that our DEB package was old.

**Comment by Maxython** [comment]
Thank
