### ISSUE TITLE
[Discussion]: Should we disable (remove, drop) `audacity` package (not supporting audio devices)?

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#14086]
As reported in #10412, our `audacity` package does not support any audio devices as of now, and from time to time we receive a question as to how to enable audio output of Audacity.

As the initial packager of `audacity`, I don't count this functionality as essential for Audacity. Many other people, however, seem to think Audacity is useless without it. If so, we should drop our `audacity` package.

How do you think?

### NOTICE
Discussions about adding audio device support is off-topic here. They should go to #10412.

**Comment by rallg** [comment]
Without sound, Audacity does provide a nice GUI for some transforms. Helpful, but not urgent. Suggestion: Existing package could be re-named `audacity-silent'. If there is a future ability to connect to audio, then the new package could be `audacity-sound'. Package installer might allow both, or only one of them.

**Comment by xtkoba** [comment]
Thanks. `audacity-silence` could be an option if an uncooperative third party repo ever provides a package with audio device support.

**Comment by rallg** [comment]
Why I respectfully suggest that my suggestion (above) is better than that of sylirre (above):

1. How many users actually read post-install messages? In any case, that would require to first install (expecting that audacity should have sound), then be disappointed (after reading the post-install script).

2. My suggestion would allow Termux audacity-silent to be installed along with a third-party (or user-built) version, just named audacity.

3. If Termux ever does get sound for audacity, then an update to audacity-silent could uninstall it, in favor of the real audacity. But the installer would need to first verify that the user did not have another audacity installed on $PREFIX/bin. Presumably no problem if another audacity is installed somewhere else.

**Comment by DLC01** [comment]
Well there may be one way to get audio output, since portaudio does have an alsa backend it would be possible to use the pulseaudio sink plugin provided by alsa-plugins and route the audio to pulseaudio, this would require packaging both alsa-lib and alsa-plugins

**Comment by xtkoba** [comment]
@DLC01 Adding audio device support to `audacity` is off-topic here; please go to #10412. I just don't want discussions to be scattered across issues. Thanks.

**Comment by xtkoba** [comment]
Conclusion has already been reached. I won't drop `audacity` for now. Thanks.
