### ISSUE TITLE
[Bug]: can't use the magick command from the imagemagick package

### ISSUE THREAD

**Issue by pandas-id** [termux/termux-packages#14096]
### Problem description

I'm trying to convert a photo from jpg to png extension using imagemagick
![Screenshot_20221225-091537_Termux](https://user-images.githubusercontent.com/60547606/209454457-9271529d-e3b9-4226-94d1-baccec1bed2d.jpg)

### What steps will reproduce the bug?

i tried this command

`magick Screenshot_20221108-110102_Termux.jpg ss1_termux.png`

### What is the expected behavior?

i want to change the photo extension from jpg to png, but i got that problem and i think it is a bug

### System information

termux-info: magick Screenshot_20221108-110102_Termux.jpg ss1_termux.png

```
CANNOT LINK EXECUTABLE "magick": library "libheif.so.1" not found: needed by /data/data/com.termux/files/usr/lib/libMagickCore-7.Q16HDRI.so in namespace (default)
```

**Comment by xtkoba** [comment]
Please always share your `termux-info` when reporting a bug.

`$PREFIX/lib/libheif.so.1` is available since `libheif` version `1.40.0-1`. I suppose you partially upgraded `imagemagick`. Please upgrade everything instead, with `apt-get upgrade` (or `pkg upgrade` if you are a user of `pkg` command.)
