### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Dendi777** [termux/termux-packages#14104]
Why does a bad system call occur with some actions, but when starting this action through sudo everything goes smoothly why did termux start requiring the root?

**Comment by Grimler91** [comment]
The description here, and in your other issue, are way too vague (what is "some actions"?). Use the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=untriaged%2Cbug+report&template=01-bug-report.yml&title=%5BBug%5D%3A+).

Sounds like you have messed up permissions in $PREFIX by using root in any case, so might help to reinstall the app.
