### ISSUE TITLE
[Package]: nodejs 19.3.0

### ISSUE THREAD

**Issue by pandas-id** [termux/termux-packages#14106]
### Why do you want to add this package to Termux?

i think newer version of nodejs will be better

### Home page URL

https://nodejs.org/en/download/current/

### Source code URL

https://nodejs.org/dist/v19.3.0/node-v19.3.0.tar.gz

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
See PR #13398 (which apparently is stalled due to the assignee being occupied.)
