### ISSUE TITLE
Bad system call

### ISSUE THREAD

**Issue by Dendi777** [termux/termux-packages#14103]
So I noticed that when installing any package, bad system call is written in my log, as well as when performing any action just launching something!

**Comment by xtkoba** [comment]
So, even `termux-info` is not working for you?

**Comment by Dendi777** [comment]
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=16744
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirror.surf/termux/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.surf/termux/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.34.1
Android version:
10
Kernel build information:
Linux localhost 4.9.193-perf-g743cb02 #1 SMP PREEMPT Mon Oct 25 17:15:39 CST 2021 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 8A

**Comment by Dendi777** [comment]
If you use everything as a superuser via sudo, then everything seems to work, but it's not reliable. Why did he start requiring root?

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app/issues/2080#issuecomment-846575028
