### ISSUE TITLE
[Bug]: apt fails to update

### ISSUE THREAD

**Issue by Aaroneisele55** [termux/termux-packages#14114]
### Problem description

apt fails to update:
`[*] Official repositories selected
    Changing main repository
[*] Running apt update
Ign:1 https://termux.dev/packages stable InRelease
Err:2 https://termux.dev/packages stable Release
  404
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/science-packages-24 science Release
  404  Not Found                                     Reading package lists... Done
E: The repository 'https://termux.org/packages stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.                                           N: Metadata integrity can't be verified, repository is disabled now.                                      N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).`

### What steps will reproduce the bug?

apt update

### What is the expected behavior?

It should update as normal

### System information

termux-info:

```
Packages CPU architecture:
aarch64                                              Subscribed repositories:
# sources.list                                       deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Mon Oct 17 22:01:30 CST 2022 aarch64 Android
Device manufacturer:
OnePlus
Device model:
AC2003
```

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation

https://github.com/termux/termux-app#google-play-store-deprecated

**Comment by giggls** [comment]
Why has this been closed? Bug exists using Version 0.118.0 from f-droid thus the posted links are not helpful.
```
 ~/ > termux-info 
find: ‘/data/data/com.termux/files/usr/etc/apt/sources.list.d’: No such file or directory
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
Updatable packages:
...
Android version:
11
Kernel build information:
Linux localhost 4.9.332-perf+ #1 SMP PREEMPT Wed Nov 23 17:13:15 CET 2022 aarch64 Android
Device manufacturer:
Fairphone
Device model:
FP3
 ~/ > apt update
Ign:1 https://termux.dev/packages stable InRelease
Err:2 https://termux.dev/packages stable Release
  404
Reading package lists... Done
E: The repository 'https://termux.org/packages stable Release' does no longer have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
```

**Comment by giggls** [comment]
I just did exactly this (without the Updatable packages list).

I get failed to fetch for any package I try to update or install.

Is my URL in sources.list still valid?

```
 ~/ > cat /data/data/com.termux/files/usr/etc/apt/sources.list 
# The main termux repository:
deb https://termux.org/packages/ stable main
```

**Comment by xtkoba** [comment]
FYI, the `$PREFIX/etc/apt/sources.list` with the latest `apt` package (version `2.5.4`) should read:

```
# The main termux repository, behind cloudflare cache:
# deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# The main termux repository:
deb https://packages.termux.dev/apt/termux-main/ stable main
```

I'm not sure if the one in Termux app version 0.118.0 is valid or not. I'm not familiar with the infrastructure.

**Comment by Grimler91** [comment]
> Why has this been closed? Bug exists using Version 0.118.0 from f-droid thus the posted links are not helpful.
> 
> ```
>  ~/ > termux-info 
> find: ‘/data/data/com.termux/files/usr/etc/apt/sources.list.d’: No such file or directory
> Packages CPU architecture:
> aarch64
> Subscribed repositories:
> # sources.list
> deb https://termux.org/packages/ stable main
> Updatable packages:
> ...
> Android version:
> 11
> Kernel build information:
> Linux localhost 4.9.332-perf+ #1 SMP PREEMPT Wed Nov 23 17:13:15 CET 2022 aarch64 Android
> Device manufacturer:
> Fairphone
> Device model:
> FP3
>  ~/ > apt update
> Ign:1 https://termux.dev/packages stable InRelease
> Err:2 https://termux.dev/packages stable Release
>   404
> Reading package lists... Done
> E: The repository 'https://termux.org/packages stable Release' does no longer have a Release file.
> N: Metadata integrity can't be verified, repository is disabled now.
> N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
> ```

This output is not from 0.118, 0.118 does not use `https://termux.org/packages` as repo, and does not print `termux-info` on that format.

Uninstall and install from fdroid instead.

**Comment by xtkoba** [comment]
I'm waiting for a reply from the author.

**Comment by giggls** [comment]
My package *has* been installed from f-droid. Re-Installation fixed this URL, so probably a release numbering issue on f-droid.

**Comment by xtkoba** [comment]
PLEASE SHARE THE OUTPUT OF `termux-info` COMMAND ANYWAYS.

**Comment by giggls** [comment]
Ähm I *did* share this output.

**Comment by xtkoba** [comment]
I'm still watching this. Please reply. Thanks.

**Comment by giggls** [comment]
As I already said. It works again using the Windows method (de-installation and re-installation). sources.list is correct now.

**Comment by Grimler91** [comment]
In theory it could be 0.118.0 if app was installed before 2021-06, then upgraded to 0.118.0 when that version was released in 2022-01, but `pkg upgrade` was never run (or not after 2021-06).

> PLEASE SHARE THE OUTPUT OF `termux-info` COMMAND ANYWAYS.

Output is in [earlier comment](https://github.com/termux/termux-packages/issues/14114#issuecomment-1372639048), app version is missing in output, app version was added to termux-info in 0.117

**Comment by xtkoba** [comment]
I suppose the case for @giggls has been resolved. Not yet the @Aaroneisele55 case though.

**Comment by giggls** [comment]
It might work to manually fix sources.list which I could no longer test as I already reinstalled termux from fdroid.

**Comment by xtkoba** [comment]
Maybe we do not recommend using `apt` command directly but instead using `pkg` command. IIRC the latter automatically (sometimes unwantedly) manipulates `$PREFIX/etc/apt/sources.list`.

**Comment by xtkoba** [comment]
OK, I misunderstood the conversation. I mistakenly assumed that the original author made an objection, which in fact is not the case.
