### ISSUE TITLE
[Package]: cups-pdf 

### ISSUE THREAD

**Issue by awYtechSystems** [termux/termux-packages#14119]
### Why do you want to add this package to Termux?

we are using CUPS to convert any tablet into a print server. we just need to add pdf virtual printer. Kindly provide the cups-pdf for the following linux version

### Home page URL

https://archlinux.pkgs.org/rolling/archlinux-extra-aarch64/cups-pdf-3.0.1-7-aarch64.pkg.tar.xz.html

### Source code URL

https://archlinux.pkgs.org/rolling/archlinux-extra-aarch64/cups-pdf-3.0.1-7-aarch64.pkg.tar.xz.html

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by awYtechSystems** [comment]
my request is for the CUPS-PDF. 
PDF virtual printer to work with CUPS

**Comment by xtkoba** [comment]
Yes, CUPS-PDF. If you encounter any problems using `cups-pdf`, then please open a new issue for that. Thanks.

**Comment by AdnanNovations** [comment]
> ### Why do you want to add this package to Termux?
> we are using CUPS to convert any tablet into a print server. we just need to add pdf virtual printer. Kindly provide the cups-pdf for the following linux version
> 
> ### Home page URL
> https://archlinux.pkgs.org/rolling/archlinux-extra-aarch64/cups-pdf-3.0.1-7-aarch64.pkg.tar.xz.html
> 
> ### Source code URL
> https://archlinux.pkgs.org/rolling/archlinux-extra-aarch64/cups-pdf-3.0.1-7-aarch64.pkg.tar.xz.html
> 
> ### Packaging policy acknowledgement
> * [x]  The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).
> 
> ### Additional information
> _No response_

Can you help me how to setup cups using termux properly? Mine just showing error unauthorized in Administration Page. No popup to input authentication, didn't know how to auth that. Thanks
