### ISSUE TITLE
hashcat package

### ISSUE THREAD

**Issue by Scaum** [termux/termux-packages#14121]
### Feature description

Please add the hashcat package in the repos. Readelf should also be available, strange not to have those...

Alternatively, people who have the package can link it. It makes no sense to try to restrict a package because HaCkiNg when we are talking about password-recovery... This is not even an active tool, running on your own device, there is definitely no hacking there, makes no sense at all...

### Additional information

/

**Comment by Grimler91** [comment]
Readelf is already available in the binutils package.

--

Hashcat did not work [back in the days](https://github.com/termux/termux-packages/issues/3629), but maybe situation is different after the opencl-vendor-driver package was added.

> It makes no sense to try to restrict a package because HaCkiNg when we are talking about password-recovery. This is not even an active tool, running on your own device, there is definitely no hacking there, makes no sense at all...

Password recovery of someone else's password sounds like hacking to me. I don't think we should add it to our repos. 

Feel free to compile it from source yourself

**Comment by Scaum** [comment]
Hashcat is a package for offline recovery. That "hacking" part Wis capturing the hash, not cracking it...

Will do next time I have access to my computer

**Comment by Grimler91** [comment]
> Hashcat is a package for offline recovery. That "hacking" part Wis capturing the hash, not cracking it...

Seems our definitions of hacking are different

> Will do next time I have access to my computer

Compilation of device seems to be quite straight forward based on linked issue
