### ISSUE TITLE
[Bug]: Linking error with clang: undefined symbol `futimes`

### ISSUE THREAD

**Issue by T-3B** [termux/termux-packages#14205]
### Problem description

When I try do compile myself a specific package (does not happen for other ones), I get an error at the link part saying I have no `futimes`.
I searched for Termux-packages, but apparently none provide that function.

Here is the full error message:
```
ld.lld: error: undefined symbol: futimes
>>> referenced by ld-temp.o
>>>               lto.tmp:(copy_file_times)
>>> did you mean: utimes
>>> defined in: /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/11.1.0/../../../../aarch64-linux-android/lib/libc.so
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
```

A link that could help: https://stackoverflow.com/questions/19374749/how-to-work-around-absence-of-futimes-in-android-ndk

I opened this issue because I found `futimes` is supported on all Linux OS.
Any solution to make the linking part working is welcome (even dirty one).
If that helps, I have rooted my device.

### Steps to reproduce the behavior.

Compile C code that have dependencies on `futimes`.

### What is the expected behavior?

Compilation without error.

### System information
```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21907
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.sahilister.in/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.sahilister.in/termux/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.35.0
Android version:
11
Kernel build information:
Linux localhost 4.14.237-AliKernel-V0.8.13-Stable termux/termux-app#2 SMP PREEMPT Mon Jun 21 22:25:42 CEST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Mi Note 10
```

**Comment by T-3B** [comment]
Quite strange…

Using your exact same `test.c` file (in `t.c`), I still get the same error:
```
$ clang t.c
t.c:3:3: warning: call to undeclared function 'futimes'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  futimes(0, NULL);
  ^
1 warning generated.
ld.lld: error: undefined symbol: futimes
>>> referenced by t.c
>>>               /data/data/com.termux/files/usr/tmp/t-95a35c.o:(main)
>>> did you mean: utimes
>>> defined in: /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/11.1.0/../../../../aarch64-linux-android/lib/libc.so
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

Tested with verbosity:
```
[…]
"/data/data/com.termux/files/usr/bin/ld.lld" --sysroot=/data/data/com.termux/files -pie -EL --fix-cortex-a53-843419 -z now -z relro -z max-page-size=4096 --hash-style=gnu --enable-new-dtags -rpath=/data/data/com.termux/files/usr/lib --eh-frame-hdr -m aarch64linux -dynamic-linker /system/bin/linker64 -o a.out /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/11.1.0/../../../../aarch64-linux-android/lib/crtbegin_dynamic.o -L/data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/11.1.0 -L/data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/11.1.0/../../../../aarch64-linux-android/lib -L/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr/aarch64-linux-android/lib -L/system/lib64 /data/data/com.termux/files/usr/tmp/t-9f1cfe.o /data/data/com.termux/files/usr/lib/clang/15.0.6/lib/linux/libclang_rt.builtins-aarch64-android.a -l:libunwind.a -ldl -lc /data/data/com.termux/files/usr/lib/clang/15.0.6/lib/linux/libclang_rt.builtins-aarch64-android.a -l:libunwind.a -ldl /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/11.1.0/../../../../aarch64-linux-android/lib/crtend_android.o
ld.lld: error: undefined symbol: futimes
>>> referenced by t.c
>>>               /data/data/com.termux/files/usr/tmp/t-9f1cfe.o:(main)
>>> did you mean: utimes
>>> defined in: /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/11.1.0/../../../../aarch64-linux-android/lib/libc.so
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

I don't remember "how I got that libc file", I just know it is located here: `/data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/11.1.0/../../../../aarch64-linux-android/lib/libc.so`.

I have both Clang-15 and GCC-11 installed, i don't know if it's a problem (I used `setupclang`).

**Comment by licy183** [comment]
It seems libc.so the clang tries to link against is from NDK and is targeted at Android 24. Anyway, I'm against the usage of `futimes` because the binaries from Termux repository are targeted at Android 24 (7.0), but `futimes` is introduced in bionic libc in Android 26 (8.0). You'd better replace its usage with some other functions, such as `utimensat`.

**Comment by T-3B** [comment]
I wish there was a way to use `futimes` (the code I'm trying tocompile is not mine and contains several calls to `futimes`.

And since the "translation" from `futimes` to `utimensat` is not immediate (not the same arguments nor same types), I don't want to do it.

Is there a way to have `futimes` in my libc.so ? How I could compile the bionic libc with target 26 (if it does not break termux) ?

**Comment by truboxl** [comment]
Please remove `ndk-multilib` on your device

**Comment by licy183** [comment]
I wonder whether we should provide a shared library that contains all the symbols from Android API 24 to the latest version of boinic. Actually, we've ported lots of libraries such as `libandroid-spawn`. But that may be hard to implement because the internal structs may differ from versions.

FYI, the following code are from Bionic libc.
```
#include <errno.h>
#include <time.h>
#include <sys/cdefs.h>

bool timespec_from_timeval(timespec& ts, const timeval& tv) {
  // Whole seconds can just be copied.
  ts.tv_sec = tv.tv_sec;

  // But we might overflow when converting microseconds to nanoseconds.
  if (tv.tv_usec >= 1000000 || tv.tv_usec < 0) {
    return false;
  }
  ts.tv_nsec = tv.tv_usec * 1000;
  return true;
}

int futimes(int fd, const timeval tv[2]) {
  timespec ts[2];
  if (tv && (!timespec_from_timeval(ts[0], tv[0]) || !timespec_from_timeval(ts[1], tv[1]))) {
    errno = EINVAL;
    return -1;
  }
  return futimens(fd, tv ? ts : nullptr);
}
```

**Comment by T-3B** [comment]
Removing `ndk-multilib` worked, thanks!

**Comment by AvnishGameDev** [comment]
I had to install`ndk-multilib` to make it work.

**Comment by T-3B** [comment]
It now appears that `ndk-multilib` supports `futimes()` !

So I can finally build a static program with `futimes()` !

**Comment by T-3B** [comment]
Thank you very much !

It appears that `ndk-multilib` is now supporting `futimes()` with a recent 
update, so I can finally compile my program statically.

Have a good day,
SMAGGHE Clément.
