### ISSUE TITLE
[BUG]: Lingker

### ISSUE THREAD

**Issue by BINTANGGAMING90** [termux/termux-packages#14206]
### Problem description

WARNING: linker: /data/data/com.termux/files/usr/bin/sh: unused DT entry: type 0x1d arg 0x2bf
CANNOT LINK EXECUTABLE: cannot locate symbol "strchrnul" referenced by "/data/data/com.termux/files/usr/bin/sh"...

### Steps to reproduce the behavior.

I install termix with app store not playstore in my phone 

### System information

* Termux application version: idk
* Android OS version: 6
* Device model: redmi 3x

**Comment by Grimler91** [comment]
From where did you install termux?

Did this happen right after bootstrap installation or after you ran some commands?

**Comment by xtkoba** [comment]
Isn't this invalid? IIRC Android 6 is not supported anymore.

(There seem to be activities to support Android 5-6 again though.)

**Comment by Grimler91** [comment]
> Isn't this invalid? IIRC Android 6 is not supported anymore.
> 
> (There seem to be activities to support Android 5-6 again though.)

Yeah, we don't work on package bugs for 5/6 anymore. The latest termux-app apks support 5&6, but all the packages have not been updated since 2019. 

I guess @sylirre is right and we can close this
