### ISSUE TITLE
Package request wine

### ISSUE THREAD

**Issue by ytrezq** [termux/termux-packages#1423]
Hello,
it would be nice to be able to run simple windows console programs like botvs.
However wine is difficult to compile and have many dependecies like mono. Of course, in order to make things simpler, building graphic support is not needed.

**Comment by Auxilus** [comment]
@ytrezq please refer https://github.com/termux/termux-packages/pull/332

**Comment by ytrezq** [comment]
Looks likes there are no pre built package.
Would it be poosible to create a disabled by default repository for such packages?

**Comment by iamahuman** [comment]
Reporting that Wine works well on Termux (+ Termux:X11) with a few patches :+1:
![Screenshot_20211105-212622_TermuxX11](https://user-images.githubusercontent.com/12353739/140510581-924e8431-8dc3-4786-b2ef-d71b81e3808b.png)

**Comment by WMCB-Tech** [comment]
> Reporting that Wine works well on Termux (+ Termux:X11) with a few patches 👍
> 
> ![Screenshot_20211105-212622_TermuxX11](https://user-images.githubusercontent.com/12353739/140510581-924e8431-8dc3-4786-b2ef-d71b81e3808b.png)

Did you compile it natively for Termux?

**Comment by iamahuman** [comment]
> > Reporting that Wine works well on Termux (+ Termux:X11) with a few patches 👍
> > ![Screenshot_20211105-212622_TermuxX11](https://user-images.githubusercontent.com/12353739/140510581-924e8431-8dc3-4786-b2ef-d71b81e3808b.png)
> 
> Did you compile it natively for Termux? just wondering

Yes.

**Comment by WMCB-Tech** [comment]
nice! although the problem is win32 apps support. which most windows apps targeted for intel and winrt apps have limited set of ports. not unless windows apps can be compiled for arm if source code and compiler is available.

it would still be nice if sharing the compilation steps and patches

**Comment by iamahuman** [comment]
> nice! although the problem is win32 apps support. which most windows apps targeted for intel and winrt apps have limited set of ports. not unless windows apps can be compiled for arm if source code and compiler is available.

Perhaps the WoW mechanism could be abused to juxtapose qemu-x86_64-user onto wine, but this is an upstream (wine) issue.

> 
> it would still be nice if sharing the compilation steps and patches

Ok, here's the whole (non-finalized, completely hacky) thing: https://gist.github.com/iamahuman/1d8db9637c314b9af47db7b7238f6ebc#file-wine-6-20-termux-patch-L23264

Note that you still need to

1. Ensure all dependencies are available. 
2. Get libunwind header files from LLVM (I was still unable to get libunwind to work right, so SEH is still clunky)
3. If you are on ARM64, symlink llvm-dlltool and llvm-windres to dlltool and windres respectively, and make them available on PATH. This is because binutils doesn't still support pei-arm64 target (as of 2021).
4. Install https://github.com/termux/termux-x11.

**Comment by truboxl** [comment]
Maybe look into packaging https://github.com/AndreRH/hangover and https://github.com/AndreRH/hangover/issues/113

**Comment by iamahuman** [comment]
> Maybe look into packaging https://github.com/AndreRH/hangover and [AndreRH/hangover#113](https://github.com/AndreRH/hangover/issues/113)

Please file a separate package request.

**Comment by iamahuman** [comment]
> > > nice! although the problem is win32 apps support. which most windows apps targeted for intel and winrt apps have limited set of ports. not unless windows apps can be compiled for arm if source code and compiler is available.
> > 
> > 
> > Perhaps the WoW mechanism could be abused to juxtapose qemu-x86_64-user onto wine, but this is an upstream (wine) issue.
> > > it would still be nice if sharing the compilation steps and patches
> > 
> > 
> > Ok, here's the whole (non-finalized, completely hacky) thing: https://gist.github.com/iamahuman/1d8db9637c314b9af47db7b7238f6ebc#file-wine-6-20-termux-patch-L23264
> > Note that you still need to
> > 
> > 1. Ensure all dependencies are available.
> > 2. Get libunwind header files from LLVM (I was still unable to get libunwind to work right, so SEH is still clunky)
> > 3. If you are on ARM64, symlink llvm-dlltool and llvm-windres to dlltool and windres respectively, and make them available on PATH. This is because binutils doesn't still support pei-aarch64 target (as of 2021).
> > 4. Install https://github.com/termux/termux-x11.
> 
> Do you still remember what was your configure parameters for building wine?

`../wine/configure --disable-win16 --without-pulse`
