### ISSUE TITLE
pass generates passwords from only 8 characters, always (aarch64, android 7.0)

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#1427]
Running `pass generate -c test/test` two times gives me:
`p[p[ahhhgg:[ahgh[ag:paa[p` and `gpa:r[:grgg[:]rra[[rargh]`

Turns out the same 8 chars are used all the time, the generated passwords aren't very secure so this is quite serious.

Here's a small script that generates 10 passwords and then counts the number of unique characters (it boats your pass git history, sry about that):

```
i=0
while (( i<10 )); do 
  echo y | pass generate -c test/test > /dev/null
  termux-clipboard-get >> passwords
  i=$((i+1))
done
more passwords | od -cvAnone -w1 | sort -bu | wc -l
```

For me on my phone it always return 9 (one char is \n), while running the test on my arm 5.0 tablet I get 87. 
Could someone on aarch64 please try it?

I'm using a custom ROM who's source code isn't available.

**Comment by Neo-Oli** [comment]
Because busybox's tr doesn't support the [:graph:] modifier, all passwords generated contain only the characters [:graph].

**Comment by Grimler91** [comment]
@Neo-Oli did you figure that out by noticing that the characters happen to make up `[:graph]`? 
Thanks, this solves it!

**Comment by Neo-Oli** [comment]
Something like that. pass used to require coreutils for pwgen, but after they started to use /dev/urandom directly instead of pwgen that requirement was dropped. I did test everything at the time, but I guess in some minor update they must have replaced the long list of characters with [:graph:].

**Comment by fornwall** [comment]
Thanks! The updated package is now available for installation.
