### ISSUE TITLE
wkhtmltopdf

### ISSUE THREAD

**Issue by yuanfang23** [termux/termux-packages#14313]
I tried to batch convert PDF files using wkhtmltopdf on termux, but I got: this version of wkhtmltopdf was compiled against the QT version without the wkhtmltopdf patch. Therefore, some features are missing, so if you need them, use the static version.

![Screenshot_2023-01-04-12-03-53-900_com termux-edit](https://user-images.githubusercontent.com/26624391/210482487-07ca0a66-0ca7-4b1b-a867-d5567788a72e.jpg)

https://github.com/termux/termux-app/issues/898

https://github.com/termux/x11-packages/issues/51

**Comment by Dragon1573** [comment]
## Additional information

- This package IS actually available in `x11-repo` and can run perfect in Termux. Maybe an `enhancement` label can be attached to this issue?
- This package needs Qt as one of the dependencies, maybe an `x11` label should be added to this issue?
- There're missing features of `wkhtmltopdf` (we needs them) and all of these features can only be enabled with a PATCHED version of Qt by wkhtmltopdf teams while compiling.
- Current package "metadata" of `wkhtmltopdf` is compiled with an official, UNPATCHED version of Qt. It's great, but some features are missing.

## Reduced Functionality

```text
  This version of wkhtmltopdf has been compiled against a version of QT without
  the wkhtmltopdf patches. Therefore some features are missing, if you need
  these features please use the static version.

  Currently the list of features only supported with patch QT includes:

 * Printing more than one HTML document into a PDF file.    (<-- This is what we needs)
 * Running without an X11 server.
 * Adding a document outline to the PDF file.
 * Adding headers and footers to the PDF file.
 * Generating a table of contents.
 * Adding links in the generated PDF file.
 * Printing using the screen media-type.
 * Disabling the smart shrink feature of WebKit.
```

**Comment by 2096779623** [comment]
@Yisus7u7

**Comment by xtkoba** [comment]
We are not going to apply patches to Qt for the sake of only one particular package. `wkhtmltopdf` depends on `qt5-qtwebkit` which is not well maintained and is potentially vulnerable. `wkhtmltopdf` itself could be a target of removal.

**Comment by xtkoba** [comment]
@Dragon1573 Basically `qmake && make`:

https://github.com/termux/termux-packages/blob/e77704842fc9ab71526539806743b811dbb48f61/x11-packages/wkhtmltopdf/build.sh

**Comment by Dragon1573** [comment]
Thank you, @xtkoba. But if we want to build this patched version of `wkhtmltopdf`, what should we do? Is there any methods that we can get the "patches" and apply it to Qt on Termux?

As previously mentioned, `wkhtmltopdf` has a special [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) repository to teach us about packaging a patched version. I cloned the repository to Ubuntu 22.10 Kinetic (amd64, inside WSL2) and checked all targets, only the following targets are available. There's no targets about `termux` ...

<details>
<summary>Outputs from <code>./build list-targets</code></summary>

```text
18:13:56 ~/D/packaging 1ms $ ./build list-targets                                                                                                   master
docker  almalinux8-aarch64
docker  almalinux8-ppc64le
docker  almalinux8-x86_64
docker  almalinux9-aarch64
docker  almalinux9-ppc64le
docker  almalinux9-x86_64
docker  amazonlinux2-aarch64
docker  amazonlinux2-x86_64
docker  amazonlinux2022-aarch64
docker  amazonlinux2022-x86_64
docker  amazonlinux2_lambda
docker  archlinux-amd64
docker  bionic-amd64
docker  bionic-arm64
docker  bionic-armhf
docker  bionic-i386
docker  bionic-ppc64el
docker  bullseye-amd64
docker  bullseye-arm64
docker  bullseye-armel
docker  bullseye-armhf
docker  bullseye-i386
docker  bullseye-ppc64el
docker  buster-amd64
docker  buster-arm64
docker  buster-armel
docker  buster-armhf
docker  buster-i386
docker  buster-ppc64el
docker  centos7-aarch64
docker  centos7-i686
docker  centos7-ppc64le
docker  centos7-x86_64
docker  fedora37-aarch64
docker  fedora37-ppc64le
docker  fedora37-x86_64
docker  focal-amd64
docker  focal-arm64
docker  focal-armhf
docker  focal-ppc64el
docker  jammy-amd64
docker  jammy-arm64
docker  jammy-armhf
docker  jammy-ppc64el
docker  mxe-cross-win32
docker  mxe-cross-win64
docker  opensuse.leap15-aarch64
docker  opensuse.leap15-ppc64le
docker  opensuse.leap15-x86_64
docker  raspberrypi.bullseye-armhf
docker  raspberrypi.buster-armhf
vagrant macos-cocoa
vagrant msvc2015-win32
vagrant msvc2015-win64
```

</details>

So this issue is "unsolvable" even if users try to build the patched version on their own?
