### ISSUE TITLE
Set `TERMUX_PKG_SRCURL` to a git repository is unreliable 

### ISSUE THREAD

**Issue by aadcg** [termux/termux-packages#14318]
The wiki pages mention that `TERMUX_PKG_SRCURL` can be set to a git url ending with `.git`.

So I wrote the following `build.sh` file:
 
```bash
TERMUX_PKG_HOMEPAGE=https://github.com/sionescu/libfixposix/
TERMUX_PKG_DESCRIPTION="Thin wrapper over POSIX syscalls "
TERMUX_PKG_LICENSE="BSL-1.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.5.1
TERMUX_PKG_GIT_BRANCH="master"
TERMUX_PKG_SRCURL=https://github.com/sionescu/libfixposix.git
TERMUX_PKG_SHA256=04d199878d0b81df2eaf93057e6be97e6c598896c36d4d487ebf366501d97884
```

However, I can't set SHA256 since it changes everytime the git sources are fetched.  Any ideas? Thanks.

```log
~/repos/termux-packages $ ./scripts/run-docker.sh ./build-package.sh libfixposix
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building libfixposix for arch aarch64...
]0;libfixposix...Downloading https://github.com/sionescu/libfixposix.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    412      0 --:--:-- --:--:-- --:--:--   414
100  193k    0  193k    0     0   111k      0 --:--:--  0:00:01 --:--:--  570k
Wrong checksum for https://github.com/sionescu/libfixposix.git:
Expected: 04d199878d0b81df2eaf93057e6be97e6c598896c36d4d487ebf366501d97884
Actual:   e23fef7888cb5a55ca82270a299515c65360fe9c94929263269d453c6b2d4152
```

**Comment by Grimler91** [comment]
Docs need to be updated, URL format was [changed recently](https://github.com/termux/termux-packages/commit/20bd0f0dc099aa390778f832f0201d50814b54ee), try `TERMUX_PKG_SRCURL=git+https://github.com/sionescu/libfixposix` instead

**Comment by TomJo2000** [comment]
The `TERMUX_PKG_SRCURL` should be set to the specified release dynamically.
i.e.
```bash
TERMUX_PKG_SRCURL=https://github.com/sionescu/libfixposix/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
```
For an [example build script](https://github.com/termux/termux-packages/blob/master/packages/bat/build.sh) see the build for the `bat` utility

The `TERMUX_PKG_SHA256` sum is the SHA256 hash of the file the Source URL is point at.
In this case the file is https://github.com/sionescu/libfixposix/archive/refs/tags/v0.5.1.tar.gz
We can find its SHA265 hash by downloading it and running `sha256sum` on it.
i.e
```bash
sha256sum ~/libfixposix-0.5.1.tar.gz
5d9d3d321d4c7302040389c43f966a70d180abb58d1d7df370f39e0d402d50d4  /home/tom/libfixposix-0.5.1.tar.gz
```
Which for this file should always result in a sum of:
`5d9d3d321d4c7302040389c43f966a70d180abb58d1d7df370f39e0d402d50d4`

Thus in the build script:
```bash
TERMUX_PKG_SHA256=5d9d3d321d4c7302040389c43f966a70d180abb58d1d7df370f39e0d402d50d4
```

Additionally see [Grimler's comment](https://github.com/termux/termux-packages/issues/14318#issuecomment-1370787773) if you intend to use the git version of this package instead.

**Comment by aadcg** [comment]
@Grimler91, thank you! That solves it for me.

@TomJo2000 thanks for your help, but I'm aware of that. In this particular case, I needed to get the sources from the master branch, and not from a tag/release.
