### ISSUE TITLE
I host new my mirror

### ISSUE THREAD

**Issue by Dev-Nergis** [termux/termux-packages#14326]
My mirror updated once per 6 hours.

- Hosted in Korea, Republic of
- 1Gb/s
- IPv4/IPv6
- No password required.

**[https://mirror.textcord.xyz/termux](https://mirror.textcord.xyz/termux)**
**[rsync://rsync.textcord.xyz/termux](rsync://rsync.textcord.xyz/termux)**

- [termux-main](https://mirror.textcord.xyz/termux/termux-main)
- [termux-main-21](https://mirror.textcord.xyz/termux/termux-main-21)
- [termux-root](https://mirror.textcord.xyz/termux/termux-root)
- [termux-x11](https://mirror.textcord.xyz/termux/termux-x11)

**Comment by 2096779623** [comment]
Thanks , added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors/126dace984a66e771e4d1c08c93d0c6021fe2d6f) .

**Comment by 2096779623** [comment]
Also see this: https://github.com/termux/termux-packages/issues/12296#issuecomment-1272264316

**Comment by Dev-Nergis** [comment]
rsync is already configured

[rsync://rsync.textcord.xyz/termux](rsync://rsync.textcord.xyz/termux)

- 1Gb/s
- IPv4 only
- No password required.

**Comment by 2096779623** [comment]
> IPv4 only
Since you used cloudflare cdn, it supports ipv6/ipv4.

**Comment by Dev-Nergis** [comment]
I had forgotten about that.

**Comment by Dev-Nergis** [comment]
https://imgur.com/vPpm74g
???????
My server is located in Seoul, Korea.

**Comment by Grimler91** [comment]
> My server is located in Seoul, Korea.

It's because the server is behind cloudflare, and cloudflare redirects to some local cache I guess. We can probably manually override the location and set Seoul instead.

This is a problem for other mirrors that use CDN's as well, mirrorbits doesn't play nicely with CDN's since it basically is suppose to do the same thing as a CDN

**Comment by Grimler91** [comment]
Position has been edited. 

Thanks @Dev-Nergis for setting up the mirror! Will be part of next termux-tools version

**Comment by Dev-Nergis** [comment]
Thank you!
