### ISSUE TITLE
Auto update failing for apkeep

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#14324]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the apkeep package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating apkeep [Current version: 0.14.1]
INFO: package being updated to 0.15.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13207    0 13207    0     0   9912      0 --:--:--  0:00:01 --:--:-- 13742
100 65455    0 65455    0     0  47784      0 --:--:--  0:00:01 --:--:-- 65586

You are about to commit these changes:

--------------------
diff --git a/packages/apkeep/build.sh b/packages/apkeep/build.sh
index 7442dff43..38ec667d1 100644
--- a/packages/apkeep/build.sh
+++ b/packages/apkeep/build.sh
@@ -2,9 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://github.com/EFForg/apkeep
 TERMUX_PKG_DESCRIPTION="A command-line tool for downloading APK files from various sources"
 TERMUX_PKG_LICENSE="MIT"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="0.14.1"
+TERMUX_PKG_VERSION="0.15.0"
 TERMUX_PKG_SRCURL=https://github.com/EFForg/apkeep/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=4992ac302d3779ba4d10980034b9cf25a1c61cebd51c789d32ec3836cc947964
+TERMUX_PKG_SHA256=439815cc2eb75df1235bb1106135548af2465e47486df6d1742cd47c0bd687dc
 TERMUX_PKG_DEPENDS="openssl (>= 3.0.3)"
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_BUILD_IN_SRC=true
--------------------

bump(main/apkeep): 0.15.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package apkeep exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
Creating new container...
Unable to find image 'ghcr.io/termux/package-builder:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/termux/package-builder/manifests/latest": Get "https://ghcr.io/token?scope=repository%3Atermux%2Fpackage-builder%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-01-05 00:37:53 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/3842687619">3842687619</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by xtkoba** [comment]
Assumed to be a temporary failure. Closing.
