### ISSUE TITLE
Auto update failing for aerc

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#14325]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the aerc package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating aerc [Current version: 0.13.0]
INFO: package being updated to 0.14.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 48911    0 48911    0     0  47370      0 --:--:--  0:00:01 --:--:-- 47348
100  324k    0  324k    0     0   274k      0 --:--:--  0:00:01 --:--:--  274k

You are about to commit these changes:

--------------------
diff --git a/packages/aerc/build.sh b/packages/aerc/build.sh
index 74a713d4d..7ceb704b4 100644
--- a/packages/aerc/build.sh
+++ b/packages/aerc/build.sh
@@ -2,9 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://aerc-mail.org/
 TERMUX_PKG_DESCRIPTION="A pretty good email client"
 TERMUX_PKG_LICENSE="MIT"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="0.13.0"
+TERMUX_PKG_VERSION="0.14.0"
 TERMUX_PKG_SRCURL=https://git.sr.ht/~rjarry/aerc/archive/${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=d8717ab2c259699b6e818a8f8db1e24033a2e09142e2e9b873fa5de6ee660bd8
+TERMUX_PKG_SHA256=60bfd15e5528a504dd11a03a33a11438ebbac7d5daca46e02d0bdc983adf9012
 TERMUX_PKG_BUILD_IN_SRC=true
 TERMUX_PKG_EXTRA_MAKE_ARGS="LDFLAGS="
 TERMUX_PKG_AUTO_UPDATE=true
--------------------

bump(main/aerc): 0.14.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package aerc exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
Creating new container...
Unable to find image 'ghcr.io/termux/package-builder:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/termux/package-builder/manifests/latest": Get "https://ghcr.io/token?scope=repository%3Atermux%2Fpackage-builder%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-01-05 00:37:55 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/3842687619">3842687619</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by xtkoba** [comment]
Assumed to be a temporary failure. Closing.
