### ISSUE TITLE
[Package]: hiptext

### ISSUE THREAD

**Issue by rihaq** [termux/termux-packages#14328]
### Why do you want to add this package to Termux?

For converting image into text

### Home page URL

https://github.com/jart/hiptext

### Source code URL

https://github.com/jart/hiptexthttps://github.com/jart/hiptext

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
`hiptext` is in disabled-packages due to not supporting FFmpeg 5.0.
