### ISSUE TITLE
[Bug]: Some Golang packages have CGO disabled

### ISSUE THREAD

**Issue by sylirre** [termux/termux-packages#14332]
### Problem description

It is required that CGO is enabled for all Golang packages compiled for Android. The CGO replaces certain functions implemented in pure Golang with equivalent from system libc, for example for DNS resolution. This is important for software compiled for Android OS as Golang contains implementations that are compatible with Linux, not with Android.

Example of issue with package `hcloud`. A maintainer specified `CGO_ENABLED=0`. As result, the package is broken completely. If user tries to run `hcloud server list`, an error will appear:
```
hcloud: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50&sort=id%3Aasc": dial tcp: lookup [api.hetzner.cloud](http://api.hetzner.cloud/) on [::1]:53: read udp [::1]:40487->[::1]:53: read: connection refused
```

This is because Go uses `/etc/resolv.conf` for Linux DNS resolver function implementation. If CGO will be enabled, it will be replaced with implementation from libc (works on Android).

### What steps will reproduce the bug?

So far I know only about DNS issues, they are 100% reproducible. Obviously can be done only by using a networking tool.

You can try to reproduce issue with hcloud (Hetzner cloud command line tool):
```
pkg install hcloud
hcloud context create mycontext
hcloud server list
```

### What is the expected behavior?

The tools should not attempt to read `/etc/resolv.conf` or try connect `[::1]:53`.

`build-package.sh` already sets `CGO_ENABLED=1` and there is no need to change this value. If package does not build with CGO and does not use networking, I think this can be a valid case where CGO can be disabled.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=29756
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
Updatable packages:
dpkg/stable 1.21.15 aarch64 [upgradable from: 1.21.14]
psmisc/stable 23.6-1 aarch64 [upgradable from: 23.6]
termux-keyring/stable 3.11 all [upgradable from: 3.10]
termux-tools version:
1.35.0
Android version:
13
Kernel build information:
Linux localhost 4.19.252-g1c485724b1e3-ab9145034 #1 SMP PREEMPT Thu Oct 6 02:17:04 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 5
```

**Comment by xtkoba** [comment]
I cannot reproduce this:

```
$ hcloud server list
hcloud: unable to authenticate (unauthorized)
```

Is 3c617f6222405cc51935bb13d557eb0b7b6fe95f not in effect? Or do we need any mor patches to Go stdlib?

No objection to refraining from disabling CGO unless absolutely necessary. (Once `btfs2` was broken due to CGO being disabled: 5c37c5644feeda3c45eedcdbcb5690d2323b4fda.)

**Comment by xtkoba** [comment]
Yeah, we often forget that `resolv-conf` is not an essential package. Please file a bug for each package that needs to depend on it.

**Comment by xtkoba** [comment]
Or a tracker issue (listing such packages) may be allowed in this case.
