### ISSUE TITLE
#Help

### ISSUE THREAD

**Issue by stainslav** [termux/termux-packages#1435]
I'm an unrooted user help me in creating app without root developers from beginning with every step please!
I request you all here please I have seen your commites on this issue so I'm posting my issue hope you don't mine!)
But please help:(

**Comment by Auxilus** [comment]
(Looks like you use translator)

You don't need root to install termux ( if that's what you meant by 'help me in creating app without root' )

**Comment by sdrausty** [comment]
@stainslav https://wiki.termux.com/wiki/Development_Environments outlines many ways to build apps on device in Termux 💪🙂
