### ISSUE TITLE
[Package]: C# softwares

### ISSUE THREAD

**Issue by rihaq** [termux/termux-packages#14366]
### Why do you want to add this package to Termux?

Hello please add C# application in repo

### Source code URL

Is it due to .Net?

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Discussions should go to #516. Thanks.
