### ISSUE TITLE
[Bug]: ./scripts/build-bootstraps.sh compiling every package

### ISSUE THREAD

**Issue by babaric-dev** [termux/termux-packages#14384]
### Problem description

I am trying to build Termux with a different packages name. However, it is building every single package when running `./scripts/build-bootstraps.sh` (including Python, etc.)

That bootstrap is just for testing. It is ok that the bootstrap can't update packages and stuff

### Steps to reproduce the behavior.

1.  Clone termux-packages repo
2. Run `./scripts/run-docker.sh ./script/build-bootstraps.sh -f`

It is building every package and im pretty sure packages like Python isnt needed.

### What is the expected behavior?

Only build a minimal bootstrap that works offline

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by xtkoba** [comment]
Ah, build dependency may not be relevant in this case. Subpackage may matter instead. I have found at least 2 paths to `python`:

```
apt -(dep)-> libgnutls -(dep)-> unbound -(subpkg)-> pyunbound -(dep)-> python
```

or

```
apt -(dep)-> dpkg -(subpkg)-> dpkg-perl -(dep)-> clang -(parent)-> libllvm -(subpkg)-> lldb -(dep)-> python
```

**Comment by xtkoba** [comment]
Aside from the second path, the first path does not seem to be evitable, as `pyunbound` requires a native `libpython` when building.
