### ISSUE TITLE
Package request: monero

### ISSUE THREAD

**Issue by hyc** [termux/termux-packages#1438]
This script successfully builds Monero for me, but it's full of hacks to get around CMake problems. Was there a cleaner way to do it?

[build.sh.txt](https://github.com/termux/termux-packages/files/1293542/build.sh.txt)

I overrode the configure_cmake() step because the line
`-DCMAKE_LINKER="$TERMUX_STANDALONE_TOOLCHAIN/bin/$LD $LDFLAGS"`
was breaking invocations of $CMAKE_LINKER. CMake was backslash-escaping the space in this var, so the shell was looking for a command named `...ld -L/...` instead of just invoking ld and passing -L/... as an argument.

The termux readline package doesn't install a package-config file, so our find_package() on it failed and so -DReadline_ROOT_DIR had to be specified explicitly.

Our bundled libunbound picks up a dependency on Android liblog, but it's bogus since we never actually use syslog(), so I've manually removed that from unbound/config.h.

The link commands generated by CMake for all of the executables are broken; CMake seems to think that -lreadline will just implicitly pick up the right library from /data/data/com.termux/files/usr/lib but it doesn't, so I've munged the relevant link.txt files to add the needed -L/... argument.

**Comment by fornwall** [comment]
> The termux readline package doesn't install a package-config file, so our find_package() on it failed and so -DReadline_ROOT_DIR had to be specified explicitly.

Thanks - this part has now been fixed. I've updated the readline build (version `7.0.3-1`) to now install the pkg-config file!
