### ISSUE TITLE
No Mirrors Accessible

### ISSUE THREAD

**Issue by SyafaHadyan** [termux/termux-packages#14408]
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Testing the available mirrors:
/data/data/com.termux/files/usr/bin/pkg: line 95: /data/data/com.termux/files/usr/etc/termux/mirrors/default: No such file or directory
/data/data/com.termux/files/usr/bin/pkg: line 96: MAIN: unbound variable
/data/data/com.termux/files/usr/bin/pkg: line 100: /data/data/com.termux/files/usr/etc/termux/mirrors/default: No such file or directory
/data/data/com.termux/files/usr/bin/pkg: line 101: WEIGHT: unbound variable
[*] () : bad
Error: None of the mirrors are accessible![Screenshot_20230109-105847_Termux.png](https://user-images.githubusercontent.com/107655102/211234695-11a0381a-1a49-4e78-92e1-3b29756f554c.png)![Screenshot_20230109-105945_Settings.png](https://user-images.githubusercontent.com/107655102/211234712-5c5e08ae-0740-4ba9-98af-0e8bf7c7b90e.png)

**Comment by SyafaHadyan** [comment]
Installed From F-Droid

**Comment by 2096779623** [comment]
Reinstall termux from F-Droid.

**Comment by xtkoba** [comment]
A bug report should be filed with specific format. It is probable that a bug only reproduces on some specific devices. Please share the output of `termux-info` command.

**Comment by SyafaHadyan** [comment]
> Reinstall termux from F-Droid.

I reinstalled Termux and it worked

**Comment by SyafaHadyan** [comment]
> A bug report should be filed with specific format. It is probable that a bug only reproduces on some specific devices. Please share the output of `termux-info` command.

Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
apt/stable 2.5.4 aarch64 [upgradable from: 2.3.13-3]
bash/stable 5.2.15 aarch64 [upgradable from: 5.1.12-2]
ca-certificates/stable 1:2022.10.11-1 all [upgradable from: 1:2021-10-26-0]
command-not-found/stable 2.1.0-3 aarch64 [upgradable from: 1.71]
coreutils/stable 9.1-2 aarch64 [upgradable from: 9.0]
curl/stable 7.87.0 aarch64 [upgradable from: 7.81.0]
dash/stable 0.5.12 aarch64 [upgradable from: 0.5.11.5]
debianutils/stable 5.7 aarch64 [upgradable from: 5.5]
dialog/stable 1.3-20221229-0 aarch64 [upgradable from: 1.3-20211214-0]
dos2unix/stable 7.4.3 aarch64 [upgradable from: 7.4.2]
dpkg/stable 1.21.17 aarch64 [upgradable from: 1.21.1]
ed/stable 1.18 aarch64 [upgradable from: 1.17-4]
findutils/stable 4.9.0-2 aarch64 [upgradable from: 4.8.0]
gawk/stable 5.2.1 aarch64 [upgradable from: 5.1.1]
gpgv/stable 2.4.0 aarch64 [upgradable from: 2.3.4]
grep/stable 3.8-1 aarch64 [upgradable from: 3.7-2]
gzip/stable 1.12-1 aarch64 [upgradable from: 1.11-3]
inetutils/stable 2.4 aarch64 [upgradable from: 1.9.4-12]
less/stable 608 aarch64 [upgradable from: 590]
libandroid-support/stable 28-3 aarch64 [upgradable from: 28-2]
libc++/stable 25b aarch64 [upgradable from: 23b-3]
libcap-ng/stable 2:0.8.3 aarch64 [upgradable from: 1:0.8.3-pre1-0]
libcrypt/stable 0.2-5 aarch64 [upgradable from: 0.2-3]
libcurl/stable 7.87.0 aarch64 [upgradable from: 7.81.0]
libevent/stable 2.1.12-2 aarch64 [upgradable from: 2.1.12]
libexpat/stable 2.5.0 aarch64 [upgradable from: 2.4.2]
libgcrypt/stable 1.10.1-1 aarch64 [upgradable from: 1.9.4]
libgmp/stable 6.2.1-2 aarch64 [upgradable from: 6.2.1]
libgnutls/stable 3.7.8 aarch64 [upgradable from: 3.6.16-1]
libgpg-error/stable 1.46 aarch64 [upgradable from: 1.43]
libiconv/stable 1.17 aarch64 [upgradable from: 1.16-3]
libidn2/stable 2.3.4 aarch64 [upgradable from: 2.3.2]
liblz4/stable 1.9.4 aarch64 [upgradable from: 1.9.3]
liblzma/stable 5.4.0 aarch64 [upgradable from: 5.2.5-1]
libmpfr/stable 4.2.0 aarch64 [upgradable from: 4.1.0]
libnettle/stable 3.8.1 aarch64 [upgradable from: 3.7.3]
libnghttp2/stable 1.51.0 aarch64 [upgradable from: 1.46.0]
libssh2/stable 1.10.0-2 aarch64 [upgradable from: 1.10.0]
libtirpc/stable 1.3.3 aarch64 [upgradable from: 1.3.2]
libunistring/stable 1.1 aarch64 [upgradable from: 0.9.10-5]
lsof/stable 4.96.5 aarch64 [upgradable from: 4.94.0-1]
nano/stable 7.1 aarch64 [upgradable from: 6.0]
openssl/stable 1:3.0.7 aarch64 [upgradable from: 1.1.1l]
pcre2/stable 10.42 aarch64 [upgradable from: 10.39-2]
procps/stable 3.3.17-2 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.6-1 aarch64 [upgradable from: 23.4]
readline/stable 8.2.1 aarch64 [upgradable from: 8.1.1]
sed/stable 4.9 aarch64 [upgradable from: 4.8-2]
tar/stable 1.34-1 aarch64 [upgradable from: 1.34]
termux-am-socket/stable 1.5.0 aarch64 [upgradable from: 1.02]
termux-exec/stable 1:1.0 aarch64 [upgradable from: 1:0.9]
termux-keyring/stable 3.11 all [upgradable from: 2.4]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-1]
termux-tools/stable 1.35.0 all [upgradable from: 0.155]
unbound/stable 1.17.0-1 aarch64 [upgradable from: 1.13.2-1]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-7]
util-linux/stable 2.38.1-1 aarch64 [upgradable from: 2.37.2-1]
xz-utils/stable 5.4.0 aarch64 [upgradable from: 5.2.5-1]
zlib/stable 1.2.13 aarch64 [upgradable from: 1.2.11-5]
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22825772 #1 SMP PREEMPT Thu Nov 3 10:58:52 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A307GN

**Comment by nuttingd** [comment]
I've hit this myself a few times (with the F-Droid and/or Github version).

I have been able to resolve it by using `apt` commands:

```sh
# pkg update fails here

apt update

# now pkg update works! (wtf?)
```

I don't know how pkg/apt are related in Termux, but this has fixed it for me more than once
