### ISSUE TITLE
[Bug]: Unable to Install Numpy

### ISSUE THREAD

**Issue by SyafaHadyan** [termux/termux-packages#14452]
### Problem description

Checking availability of current mirror: ok
Get:1 https://deb.kcubeterm.me/termux-main stable InRelease [512 B]
Err:1 https://deb.kcubeterm.me/termux-main stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.
![Screenshot_20230111-104022_Termux](https://user-images.githubusercontent.com/107655102/211705749-252bd006-27a8-45c6-9f77-70ed7f99cada.png)

### What steps will reproduce the bug?

pkg install numpy

### System information

termux-info:

```Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22825772 #1 SMP PREEMPT Thu Nov 3 10:58:52 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A307GN
```

**Comment by xtkoba** [comment]
The mirror "deb.kcubeterm.me" is broken. Select another one.

**Comment by SyafaHadyan** [comment]
How do I select mirror

**Comment by SyafaHadyan** [comment]
> ![Screenshot_20230111-105312_Termux.png](https://user-images.githubusercontent.com/107655102/211707087-e034082b-b797-4c5e-af7d-928c29eca74a.png)

I'm selected the 2nd mirror

**Comment by xtkoba** [comment]
You mean the selected mirror cannot be changed?

Another way is to manually modify the config: https://github.com/termux/termux-packages/issues/14114#issuecomment-1372657695.

As a last resort you can uninstall Termux app and then install it again.

**Comment by SyafaHadyan** [comment]
> You mean the selected mirror cannot be changed?
> 
> Another way is to manually modify the config: https://github.com/termux/termux-packages/issues/14114#issuecomment-1372657695.
> 
> As a last resort you can uninstall Termux app and then install it again.

I switched to default host with CloudFlare

**Comment by SyafaHadyan** [comment]
![Screenshot_20230111-142731_Termux.png](https://user-images.githubusercontent.com/107655102/211733581-328e3bba-a00c-462e-87bc-964dec319d89.png)

**Comment by SyafaHadyan** [comment]
> `pkg install numpy` will not work, it should be `pkg install python-numpy`
> 

It worked now

**Comment by SyafaHadyan** [comment]
Thanks for the help
