### ISSUE TITLE
Question: Audacity missing some Effects? Does not need sound.

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#14498]
Audacity has a "Change Pitch" Effect, but it is not in the Termux package. I see that the current Audacity source code (at their web site) does have the code, and it has recently been updated.

Is there a reason why that Effect is missing from the Termux build? A knowledgeable user (such as myself) can use it without the need for Audacity to play audio.

What it does: Changes pitch without changing tempo (speed). Why I use it: By artificially lowering pitch by a semitone or two, I can sing along with pop music from when I was young. I have used it on Windows many times before, but no longer have access to that.

**Comment by xtkoba** [comment]
Change Pitch depends on `libsoundtouch` which is not (yet) packaged, and it is explicitly turned off in `build.sh` of `audacity` to avoid automagic dependency:

https://github.com/termux/termux-packages/blob/41c87b89e7640bd87c87874df834e9eb8e396d8e/x11-packages/audacity/build.sh#L37

**Comment by rallg** [comment]
Thanks! Now I won't waste time looking for a hack (I am not a good hacker).
