### ISSUE TITLE
[Package]: php-cli-huy

### ISSUE THREAD

**Issue by u400822** [termux/termux-packages#14499]
### Why do you want to add this package to Termux?

I want build a php7

### Source code URL

https://github.com/Dichvucoder/dgbaopro/blob/main/php7_debug.zip

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Version : written on php 7.4.33
It is used as 1 tool to run the php file safely
Indicates that the sources are eval(avoid malicious code,viruses)

Please add the openssl-1.1 library

Please compile it as cli

**Comment by xtkoba** [comment]
PHP 7 is EOL upstream. We won't support it anymore on our own.

What is the ZIP file in the Source code URL? Isn't it just the souce tree of PHP 7.4.33? We cannot use such a suspicious source.

**Comment by u400822** [comment]
> PHP 7 is EOL upstream. We won't support it anymore on our own.
> 
> What is the ZIP file in the Source code URL? Isn't it just the souce tree of PHP 7.4.33? We cannot use such a suspicious source.

This source edited in Zend

**Comment by xtkoba** [comment]
We cannot use such an obscure source, unfortunately.
