### ISSUE TITLE
[Bug]: Unable to start Wireshark 

### ISSUE THREAD

**Issue by silverbullet-herr** [termux/termux-packages#14492]
### Problem description

i couldn't start wireshark or tshark packet capture due to this error 
![Screenshot_20230112-231403_Termux](https://user-images.githubusercontent.com/64875326/212192624-dbeaaf0c-51a9-45aa-99bb-fb9b460673ef.png)
it worked for me two months ago with no issues after reinstallation  it's not working 

### What steps will reproduce the bug?

sudo tshark 
sudo wireshark
sudo wireshark -w [different path] (same issue) 

### System information

termux-info:

```

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21394
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
tor/stable 0.4.7.13 aarch64 [upgradable from: 0.4.7.12-1]
termux-tools version:
1.35.0
Android version:
11
Kernel build information:
Linux localhost 4.4.177-g339a04eabab9 #1 SMP PREEMPT Sun Sep 4 02:24:27 UTC 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-M205F

**Comment by xtkoba** [comment]
Possibly a regression of https://github.com/termux/termux-root-packages/issues/220?

**Comment by silverbullet-herr** [comment]
> Possibly a regression of [termux/termux-root-packages#220](https://github.com/termux/termux-root-packages/issues/220)?

i think it's not a problem with  $TMPDIR path as i can change the file path with -w option 
![Screenshot_20230113-010834_Termux](https://user-images.githubusercontent.com/64875326/212207398-8c52e7bd-b9ea-49c9-b639-03c8fae4053d.png)

**Comment by 2096779623** [comment]
[termux-report_issue_from_transcript.log](https://github.com/termux/termux-packages/files/10407027/termux-report_issue_from_transcript.log)

Can reproduce on my device.

**Comment by 2096779623** [comment]
[termux-report_issue_from_transcript.log](https://github.com/termux/termux-packages/files/10407027/termux-report_issue_from_transcript.log)

Can reproduce on my device.

**Comment by xtkoba** [comment]
Does the `-w` option affect temporary files as well? I cannot find a screen capture when `-w` is specified.

Does `$TMPDIR` (`/data/data/com.termux/files/home/.suroot/.tmp`) exist?

Using `strace` command is suggested to see what is happening.

Error message transcribed:

```
tshark: The temporary file to which the capture would be saved could not be opened: Failed to create file "/data/data/com.termux/files/home/.suroot/.tmp/wireshark_rmnet0BY06Y1.pcapng": Permission denied.
```

**Comment by silverbullet-herr** [comment]
@xtkoba sorry for late reply i was asleep
yeah $TMPDIR exists and here's some screenshots 
![Screenshot_20230113-091836_Termux](https://user-images.githubusercontent.com/64875326/212273265-d8c9301a-7dee-45c3-b0be-3ad60028d5a0.png)

**Comment by silverbullet-herr** [comment]
strace output:
[example_trace.txt](https://github.com/termux/termux-packages/files/10409656/example_trace.txt)

**Comment by xtkoba** [comment]
@silverbullet-herr Would you please try `strace -f`? Error seems to be in some child process.

**Comment by silverbullet-herr** [comment]
@xtkoba 
[Uploading strace2.txt…]()

**Comment by xtkoba** [comment]
Seems to contain enough information to debug it. Thanks. Not sure but I already have some guesses.

**Comment by silverbullet-herr** [comment]
alright  good luck to you bro im sure you handle it 👍👍

**Comment by xtkoba** [comment]
Can you please test if artifact in https://github.com/termux/termux-packages/actions/runs/3923547479 works?

**Comment by silverbullet-herr** [comment]
> Can you please test if artifact in https://github.com/termux/termux-packages/actions/runs/3923547479 works?

i can confirm that  it's working perfectly thank you very much 👍👍

**Comment by przemo71J** [comment]
Please run "sudo chmod o+rw <folder_to_store_pcap_files>" and then save pcap files in this directory.
