### ISSUE TITLE
Installing weechat and weechat-python-plugin still won't let me run python scripts

### ISSUE THREAD

**Issue by geezuh** [termux/termux-packages#145]
I get the following when weechat starts:

`ERROR: unable to load plugin "/data/data/com.termux/files/user/lib/weechat/plugins/python.so": dlopen failed: cannot locate symbol "_Py_NoneStruct" referenced by "python.so"...`

**Comment by fornwall** [comment]
This should now be fixed - run `apt update && apt upgrade` to install the update.

Note that it's python3 that is used, so all python scripts may not be compatible (some are python2 only).
