### ISSUE TITLE
Change clang ld.lld link android lib path

### ISSUE THREAD

**Issue by StarkZhidian** [termux/termux-packages#14509]
### Discussed in https://github.com/termux/termux-packages/discussions/14508

<div type='discussions-op-text'>

<sup>Originally posted by **StarkZhidian** January 14, 2023</sup>
Hi, I want to integrate the clang package on an Android device, and I would like to ask if there is an environment variable parameter to specify the path where ld.lld loads files like libclang_rt.asan-arm-android.a

Here is my compile error log:

```
ld.lld: error: cannot open /data/data/com.clang.my_package/files/clang/lib/clang/13.0.1/lib/android/libclang_rt.builtins-aarch64-android.a: No such file or directory
ld.lld: error: cannot open /data/data/com.clang.my_package/files/clang/lib/clang/13.0.1/lib/android/libclang_rt.builtins-aarch64-android.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Thank u.</div>

**Comment by xtkoba** [comment]
Path to compiler-rt seems to be pretty much hardcoded. That is why we had to elaborate something like #10526.

You can get that path as follows:

```
$ clang -print-libgcc-file-name
/data/data/com.termux/files/usr/lib/clang/15.0.7/lib/linux/libclang_rt.builtins-aarch64-android.a
```

**Comment by xtkoba** [comment]
So in any way it cannot be changed dynamically.

Closing as answered.

**Comment by StarkZhidian** [comment]
@sylirre @xtkoba Ok, I got it. Thank u very much.
