### ISSUE TITLE
GNU sort and other GNU packages

### ISSUE THREAD

**Issue by lucabelmondo** [termux/termux-packages#1455]
Hi, I have scripts and configs that depend on GNU sort (as opposed to the BusyBox version), specifically to check versions strings.
Is there some way to install it natively in termux, or shold I do it from source?
In general, is there someway to install the GNU version of common packages in bulk?
Thank you!

**Comment by Neo-Oli** [comment]
yes. `pkg install coreutils`

**Comment by lucabelmondo** [comment]
Thank you! 😄
