### ISSUE TITLE
Error: unused DT entry

### ISSUE THREAD

**Issue by qwavfbb** [termux/termux-packages#14583]
### Problem description

An error occurred while running the compiled package "libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)"

### What steps will reproduce the bug?

runing

### What is the expected behavior?

libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)

### System information

null

**Comment by truboxl** [comment]
Is there any policy we should always closed as completed and not closed as invalid/wontfix/incomplete?

**Comment by xtkoba** [comment]
@truboxl No, nothing. It is just my way of moderation. You can do it as you like.

Largely this is just a matter of backward compatibility. "Closing as not planned" did not exist in the past and instead we used labels such as "wontfix", "not-bug" or "invalid" (or "obsolete" label which I created on my own). So my way is to close as completed when at least one of these labels are given.
