### ISSUE TITLE
gforth error when ran: image gforth.fi doesn't seem to be a Gforth (>=0.6) image.

### ISSUE THREAD

**Issue by smith901** [termux/termux-packages#14648]
# Steps to reproduce
pkg install gforth
gforth
_Error happens_

# Expected bahavior
gforth interpreter opens for coding

# What actually happens
Get an error message:  gforth: image gforth.fi doesn't seem to be a Gforth (>=0.6) image.

# Output from termux session:
```
~ $ pkg install gforth
Checking availability of current mirror:
[*] https://packages.termux.dev/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  googletest openssl-1.1
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  gforth
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 602 kB of archives.
After this operation, 3883 kB of additional disk space will be used.
Get:1 https://packages.termux.dev/apt/termux-main stable/main arm gforth arm 0.7.3 [602 kB]
Fetched 602 kB in 2s (377 kB/s)
Selecting previously unselected package gforth.
(Reading database ... 35629 files and directories currently installed.)
Preparing to unpack .../archives/gforth_0.7.3_arm.deb ...
Unpacking gforth (0.7.3) ...
Setting up gforth (0.7.3) ...
Processing triggers for update-info-dir (6.8-6-0) ...
~ $ gforth
gforth: image gforth.fi doesn't seem to be a Gforth (>=0.6) image.
~ $ termux-info
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12360
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.dev/apt/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.35.0
Android version:
13
Kernel build information:
Linux localhost 4.14.186-25433824 #1 SMP PREEMPT Thu Nov 24 17:21:05 KST 2022 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A136U
```

I'm not an Android dev and am just learning Forth so this is all the help I can do on this issue until I can get knowledgeable enough to fix it. If I manage to get it working by some miracle, a PR will be made.

### Edit  
Could be caused by Android13 update. I can compile with gcc but programs won't run at all. I used to be able to before the update. Not sure if this is helpful, but I'm adding it just incase its related to the problem. The 13 update, not gcc is what I'm talking about.

**Comment by xtkoba** [comment]
Somehow the magic ("Gforth3") is not aligned correctly (should be 8-byte aligned):

```
$ hexdump -C $PREFIX/lib/gforth/0.7.3/gforth.fi | head -n 5
00000000  23 21 2f 64 61 74 61 2f  64 61 74 61 2f 63 6f 6d  |#!/data/data/com|
00000010  2e 74 65 72 6d 75 78 2f  66 69 6c 65 73 2f 75 73  |.termux/files/us|
00000020  72 2f 62 69 6e 2f 67 66  6f 72 74 68 2d 30 2e 37  |r/bin/gforth-0.7|
00000030  2e 33 20 2d 2d 69 6d 61  67 65 2d 66 69 6c 65 0a  |.3 --image-file.|
00000040  20 20 47 66 6f 72 74 68  33 07 00 00 00 00 00 00  |  Gforth3.......|
```

**Comment by xtkoba** [comment]
Apparently due to shebang fix. The situation looks a bit different now though.

**Comment by smith901** [comment]
@xtkoba On the 1st line, shouldn't there be a space between `#!` and the path?
My laptop has it looking like this:`
00000000  23 21 20 2f 75 73 72 2f  62 69 6e 2f 67 66 6f 72  |#! /usr/bin/gfor|
00000010  74 68 2d 30 2e 37 2e 33  20 2d 2d 69 6d 61 67 65  |th-0.7.3 --image|
00000020  2d 66 69 6c 65 0a 20 20  47 66 6f 72 74 68 33 07  |-file.  Gforth3.|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  c0 71 05 00 00 00 00 00  00 00 80 00 00 00 00 00  |.q..............|`
