### ISSUE TITLE
[Package]: libglvnd

### ISSUE THREAD

**Issue by truboxl** [termux/termux-packages#14666]
### Why do you want to add this package to Termux?

Referring #13887

I agree that there's should be a standardised neutral way of loading OpenGL drivers and solve issues like:
1. sole dependency on mesa
2. no more LD_LIBRARY_PATH trickery to use alternative drivers, eg: gl4es
3. package management burden of adding new drivers to x11 packages while avoiding mesa conflicts

It should make way for entirely new driver other than mesa and gl4es which may be a better fit for Termux environment.

### Home page URL

https://gitlab.freedesktop.org/glvnd/libglvnd

### Source code URL

https://gitlab.freedesktop.org/glvnd/libglvnd.git

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
@licy183 X11 is not much relevant here. `mesa` package is now in main repo.
