### ISSUE TITLE
libuuid and libuuid-static are different

### ISSUE THREAD

**Issue by zorro** [termux/termux-packages#14676]
The `libuuid` package is from `util-linux` but the `libuuid-static` package is from sourceforge libuuid

**Comment by Grimler91** [comment]
Thanks for reporting! Libuuid-static should be removed

**Comment by xtkoba** [comment]
Can these also be removed:

- [ ] gtk3-static
- [ ] sdl-static
- [ ] avrdude-static

(I will file a new issue for that if need be.)

Reference: #12848.

**Comment by Grimler91** [comment]
I'm more or less locked out from the vps where I am currently at, but I'll fix it in a few days unless someone else beats me to it, no need for a separate issue

**Comment by Grimler91** [comment]
Fixed, thanks for reporting
