### ISSUE TITLE
thin gem is not getting installed.

### ISSUE THREAD

**Issue by suryapoo** [termux/termux-packages#1468]
$ gem install thin -- --use-system-libraries
Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing thin:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/ext
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20170912-9536-rr7j6t.rb extconf.rb --use-system-libraries
mkmf.rb can't find header files for ruby at /data/data/com.termux/files/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/eventmachine-1.2.5/gem_make.out
$

**Comment by Neo-Oli** [comment]
Try installing `ruby-dev`, as it contains the ruby header files.
`pkg install ruby-dev`

**Comment by suryapoo** [comment]
After installing ruby-dev:
Welcome to Termux!

Online help:     https://termux.com/help
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ pkg install ruby-dev
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
$ gem install thin -- --use-system-libraries
Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing thin:                       ERROR: Failed to build gem native extension.                                      
    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/ext
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20170912-14915-hrwkds.rb extconf.rb --use-system-libraries                       checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-cryptolib
        --without-cryptolib
/data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:542:in `try_link0'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:557:in `try_link'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:775:in `try_func'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:1002:in `block in have_library'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:997:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `each'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/eventmachine-1.2.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/eventmachine-1.2.5/gem_make.out
$

**Comment by suryapoo** [comment]
Hey...make was missing..after installing make, its working fine.!

**Comment by sdrausty** [comment]
@suryapoo that is good. Can u post your steps to successfully closing this issue please.

**Comment by suryapoo** [comment]
@sdrausty sûre..Man..it's

pkg install ruby-dev 
pkg install make

gem install thin  -- --use-system-libraries
