### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by byrpa2023** [termux/termux-packages#14713]
### Problem description

Hi all, I have installed Mysql server (MariaDB) on termux and everything without problems, but after a while, I have not detected why it happens, but when loading the mysql (MariaDB) gives an error "Missing FILE_CHECKPOINT" it has already happened to me several times and I had to lose data. I found that this error is when the INNODB system has not been able to find the checkpoint file, but I have not found how to avoid this error and if in case it happens how to recover the data at that time, since there are .FRM and .IBD files, but nothing can be done. Someone who can help on this issue, please. Best regards. 

Translated with www.DeepL.com/Translator (free version)

### What steps will reproduce the bug?

Hi all, I have installed Mysql server (MariaDB) on termux and everything without problems, but after a while, I have not detected why it happens, but when loading the mysql (MariaDB) gives an error "Missing FILE_CHECKPOINT" it has already happened to me several times and I had to lose data. I found that this error is when the INNODB system has not been able to find the checkpoint file, but I have not found how to avoid this error and if in case it happens how to recover the data at that time, since there are .FRM and .IBD files, but nothing can be done. Someone who can help on this issue, please. Best regards. 

Translated with www.DeepL.com/Translator (free version)

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Please provide the actual error message, steps to reproduce the issue, and output of termux-info (i.e. fill in the bug report template properly)

**Comment by xtkoba** [comment]
As pointed out in the comment above, this is not a valid bug report. An appropriate subject is required as well.

This reminds me of #9729. Unfortunately, it is common on Android that daemons are killed in a brutal manner, leaving DB in an inconsistent state.
