### ISSUE TITLE
[Package]: subfinder

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#14720]
### Why do you want to add this package to Termux?

Its not used for free internet hack, its just to get subdomains

### Home page URL

https://github.com/projectdiscovery/subfinder

### Source code URL

https://github.com/projectdiscovery/subfinder

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by SunPodder** [comment]
Better be added in [TUR](https://github.com/termux-user-repository/tur)

**Comment by 2096779623** [comment]
This is a "hacking" package like #14698 . Considering this, the place of `subfinder` is TUR.
