### ISSUE TITLE
[Package]: Split Language Source Code and .so files from Helix

### ISSUE THREAD

**Issue by giiutfff** [termux/termux-packages#14735]
### Why do you want to add this package to Termux?

Currently the Helix package is toooooooooooo big, 923MB after installed. Which is not great for mobile device.
After a lite investigation, the size mostly is took by language support, that no one will actually need every single one of them.
Please kindly consider split them into separate packages. And let users choose which to install on demand. 

### Source code URL

https://github.com/helix-editor/helix

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
The questionable source code is in `$PREFIX/share/helix/runtime/grammars/sources`. Is this used by end users in the first place? If so, this should be separated as a platform-independent subpackage (`helix-grammars-source`). And `$PREFIX/share/helix/runtime/grammars/*.so` can go to a (platform-dependent) subpackage (`helix-grammars`).

As shown above, ELF binaries are installed under `$PREFIX/share`. This is not standard. They should go under `$PREFIX/lib` or `$PREFIX/libexec`.

I can take this as it is rather trivial, but CC: @MrAdityaAlok in case if interested.

**Comment by MrAdityaAlok** [comment]
@xtkoba please leave it for me, I'll fix it. Also let that PR be open.

**Comment by MrAdityaAlok** [comment]
@xtkoba @giiutfff Seperating each grammar source to a different package won't be feasible (there's 123 currently). 

Instead users could install using `hx --grammar build` (though that would also build 123 grammars on device).

What's your opinion?
