### ISSUE TITLE
[Package]: apk-builder

### ISSUE THREAD

**Issue by mishpro-programm** [termux/termux-packages#14749]
### Why do you want to add this package to Termux?

This package should help people build apk in Termux

### Home page URL

https://github.com/mishpro-programm/apk-builder

### Source code URL

https://github.com/mishpro-programm/apk-builder

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
#14714
