### ISSUE TITLE
while setting up password lock ...

### ISSUE THREAD

**Issue by Lamuddxx** [termux/termux-packages#14778]
i goofed up on the 2nd password to verify what i had entered as my password but as soon as i went to re-enter the password i selected again i suddenly got a odd error similiar to what i get when trying to sign in :

Report issues at https://termux.dev/issues
Password:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/login.py", line 10, in <module>
    filepass = open("/data/data/com.termux/files/usr/share/login/.pass", "r")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/share/login/.pass'

**Comment by xtkoba** [comment]
Not an issue of our packages. Closing as invalid.

**Comment by Lamuddxx** [comment]
plsdirect meto the correct venue for help. thanks
