### ISSUE TITLE
[Package]: python-pandas

### ISSUE THREAD

**Issue by Mame29** [termux/termux-packages#14777]
### Why do you want to add this package to Termux?

pandas is a Python package that provides fast, flexible, and expressive data structures designed to make working with "relational" or "labeled" data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python. Additionally, it has the broader goal of becoming the most powerful and flexible open source data analysis / manipulation tool available in any language. 

### Home page URL

https://pandas.pydata.org/pandas-docs/stable

### Source code URL

https://github.com/pandas-dev/pandas

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Duplicate of #13785.
