### ISSUE TITLE
[Bug]: error: Uncaught exception, shutting down: Missing X extension: Composite

### ISSUE THREAD

**Issue by krypton-byte** [termux/termux-packages#14772]
### Problem description

when I run the polybar command, I get an error message like this "error: Uncaught exception, shutting down: Missing X extension: Composite"

### What steps will reproduce the bug?

polybar main -c "$HOME"/.config/polybar/beach/config.ini

### What is the expected behavior?

displays a polybar on the screen

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root/ root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.36.1
Android version:
9
Kernel build information:
Linux localhost 4.4.146 #1 SMP PREEMPT Sat Jun 29 19:01:39 CST 2019 aarch64 Android
Device manufacturer:
HOTWAV
Device model:
Pearl K2

```

**Comment by xtkoba** [comment]
Which X11 environment are you using? Not reproducing for me with `tigervnc`.

**Comment by krypton-byte** [comment]
i'm using xming and putty to remote x11

**Comment by xtkoba** [comment]
So this is an issue of Xming. Ask them how to enable Composite.
