### ISSUE TITLE
libuuid.so.1 not found

### ISSUE THREAD

**Issue by Code-Bytee** [termux/termux-packages#14799]
$ apachectl
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/httpd": library "libuuid.so.1" not found
![Uploading Screenshot_2023-01-29-14-34-58-719_com.termux.jpg …]()

**Comment by 2096779623** [comment]
Please send your `termux-info` output.

**Comment by xtkoba** [comment]
Yeah we need your `termux-info` output to triage this.

That said, I'm sure this is due to partial upgrading; only `libuuid` is upgraded and not `apache2`. I recommend upgrading everything, by `pkg upgrade` or `apt-get upgrade` or something.

**Comment by xtkoba** [comment]
For devs: revdep rebuild for `libuuid`, including `apache2`, is done in commit 11af5a371aa4a60c25480a44883e3d81b359b707. No extra work should be needed.

**Comment by xtkoba** [comment]
Closing as invalid.
