### ISSUE TITLE
libxtst-dev, libx11-dev packages

### ISSUE THREAD

**Issue by VRuzhentsov** [termux/termux-packages#1488]
Hi. Can  anyone explain, why there is no `libxtst-dev`, `libx11-dev` packages in termux/Android ?
I want to compile c++ file, which is using `#include <X11/Xutil.h>`

**Comment by vishalbiswas** [comment]
x11 or any kind of gui is not available in Termux. I previously compiled some of them for arm https://drive.google.com/folderview?id=0B8Q4yBRb9PSHLUQ4VHJkQkZvdDg

**Comment by AI-Pranto** [comment]
I have installed `libx11` from `x11-repo` repository. But there's some header file missing. 

```
./maketools all

warning: Can not find X11, which is required by some tools.
```
`X.h` header file missing in `include/X11/`. Any Idea how to fix this?

**Comment by Grimler91** [comment]
@AI-Pranto `$PREFIX/include/X11/X.h` is in xorgproto: https://www.google.com/search?q=x11+x.h

**Comment by AI-Pranto** [comment]
ls $PREFIX/include/X11/ 
```
CallbackI.h   Object.h      VendorP.h           Composite.h   ObjectP.h     XKBlib.h
CompositeP.h  PassivGraI.h  Xauth.h
ConstrainP.h  RectObj.h     Xcms.h
Constraint.h  RectObjP.h    Xdmcp.h
ConvertI.h    ResConfigP.h  Xlib-xcb.h
Core.h        ResourceI.h   Xlib.h
CoreP.h       SM            XlibConf.h
CreateI.h     SelectionI.h  Xlibint.h
EventI.h      Shell.h       Xlocale.h
HookObjI.h    ShellI.h      Xmu
ICE           ShellP.h      Xregion.h
ImUtil.h      StringDefs.h  Xresource.h
InitialI.h    ThreadsI.h    Xtos.h
Intrinsic.h   TranslateI.h  Xutil.h
IntrinsicI.h  VarargsI.h    cursorfont.h
IntrinsicP.h  Vendor.h      extensions
```

**Comment by AI-Pranto** [comment]
Should I create this file manually @Grimler91?

**Comment by Grimler91** [comment]
@AI-Pranto no, you should install xorgproto

**Comment by AI-Pranto** [comment]
Thanks @Grimler91
