### ISSUE TITLE
[Bug]: unar CANNOT LINK EXECUTABLE "unar": cannot locate symbol "Xzs_Construct" referenced by "/system/lib64/libunwindstack.so"...

### ISSUE THREAD

**Issue by zixijian** [termux/termux-packages#14881]
### Problem description

The unar package could not be used properly.
```
CANNOT LINK EXECUTABLE "unar": cannot locate symbol "Xzs_Construct" referenced by "/system/lib64/libunwindstack.so"...
```

### What steps will reproduce the bug?

Unzip the file using unar.

### What is the expected behavior?

The package could not be used properly.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1+2c6674f
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~dwYT_SXaloQTlWBMozX32g==/com.termux-GIzx1rkbZSiPp3suahT14Q==/base.apk
TERMUX_APP__APK_RELEASE=UNKNOWN
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-5
TERMUX_APP__PID=19083
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c244,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c244,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10244
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+8421173
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+8421173
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.36.1
Android version:
13
Kernel build information:
Linux 11tp 5.10.101-android12-9-00027-g1292f517889e-ab8602202 #1 SMP PREEMPT Mon May 16 11:18:04 UTC 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
22041216C

```

**Comment by xtkoba** [comment]
First of all please make sure that `LD_LIBRARY_PATH` env var is **NOT** set.

```bash
unset LD_LIBRARY_PATH
```

**Comment by zixijian** [comment]
> First of all please make sure that `LD_LIBRARY_PATH` env var is **NOT** set.
> 
> ```shell
> unset LD_LIBRARY_PATH
> ```

It worked,But I didn't specify the path myself.

**Comment by xtkoba** [comment]
Maybe due to:

> TERMUX_APP__PACKAGE_VARIANT=apt-android-5

`DT_RUNPATH` was not supported until Android 7 and `LD_LIBRARY_PATH` was used instead. I'm not sure (not familiar with Termux app in general) but that may be still the case with `apt-android-5` variant.

**Comment by agnostic-apollo** [comment]
> Maybe due to:
> 
> > TERMUX_APP__PACKAGE_VARIANT=apt-android-5
> 
> `DT_RUNPATH` was not supported until Android 7 and `LD_LIBRARY_PATH` was used instead. I'm not sure (not familiar with Termux app in general) but that may be still the case with `apt-android-5` variant.

Yeah, the `apt-android-5` variant exports it. It has a different bootstrap and repos too.

https://github.com/termux/termux-app/blob/c6dce125104620befd24b8f14e5a9f5871ed63a3/termux-shared/src/main/java/com/termux/shared/termux/shell/command/environment/TermuxShellEnvironment.java#L81

@zixijian you are using android 13, install `apt-android-7` variant.
