### ISSUE TITLE
Htop not working in android oreo

### ISSUE THREAD

**Issue by bitnetwork** [termux/termux-packages#1490]
Htop appears to break in Android Oero, as the system denied permission to non rooted user the process stat file.

    Cannoy open /proc/stat: Permission denied

Nexus 6P, Android 8.0 Oreo, OPR6.170623.019

**Comment by sdrausty** [comment]
@bitnetwork There quite a discussion going on about your issue at Android O: Permission denied on /proc entries for htop and top #299 https://github.com/termux/termux-app/issues/299
