### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by apple-corps** [termux/termux-packages#14926]
### Problem description

Problem description

I tried installing openssh on my phone and get CANNOT LINK EXECUTABLE "ssh=keygen": library "libcrypto.so.3" not found: needed by main executable https://imgur.com/a/CcybgQM
Steps to reproduce the behavior.

pkg install openssh
What is the expected behavior?

install package with no error message
System information

    Termux application version:v0.118.0
    Android OS version: android 12
    Device model: galaxy s22 ultra

__________

After looking at the termux-info, I ran apt-get upgrade and it seemed to resolve the issue. However it's unclear what version of configuration resources I'm supposed to select. Therefore I kept defaults

__________

https://wiki.termux.com/wiki/Package_Management https://wiki.termux.com/wiki/Package_Management

### What steps will reproduce the bug?

pkg install openssh

### What is the expected behavior?

openssh installs without error

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
Updatable packages:
apt/stable 2.5.5-1 aarch64 [upgradable from: 2.3.13-3]
bash/stable 5.2.15 aarch64 [upgradable from: 5.1.12-2]
ca-certificates/stable 1:2023.01.10 all [upgradable from: 1:2021-10-26-0]
command-not-found/stable 2.1.0-8 aarch64 [upgradable from: 1.71]
coreutils/stable 9.1-2 aarch64 [upgradable from: 9.0]
dash/stable 0.5.12 aarch64 [upgradable from: 0.5.11.5]
debianutils/stable 5.7 aarch64 [upgradable from: 5.5]
dialog/stable 1.3-20221229-0 aarch64 [upgradable from: 1.3-20211214-0]
diffutils/stable 3.9 aarch64 [upgradable from: 3.8]
dos2unix/stable 7.4.3 aarch64 [upgradable from: 7.4.2]
dpkg/stable 1.21.19 aarch64 [upgradable from: 1.21.1]
ed/stable 1.19 aarch64 [upgradable from: 1.17-4]
findutils/stable 4.9.0-2 aarch64 [upgradable from: 4.8.0]
gawk/stable 5.2.1 aarch64 [upgradable from: 5.1.1]
gpgv/stable 2.4.0-2 aarch64 [upgradable from: 2.3.4]
grep/stable 3.8-1 aarch64 [upgradable from: 3.7-2]
gzip/stable 1.12-1 aarch64 [upgradable from: 1.11-3]
inetutils/stable 2.4 aarch64 [upgradable from: 1.9.4-12]
less/stable 608 aarch64 [upgradable from: 590]
libandroid-support/stable 28-3 aarch64 [upgradable from: 28-2]
libc++/stable 25c aarch64 [upgradable from: 23b-3]
libcap-ng/stable 2:0.8.3 aarch64 [upgradable from: 1:0.8.3-pre1-0]
libcrypt/stable 0.2-5 aarch64 [upgradable from: 0.2-3]
libevent/stable 2.1.12-2 aarch64 [upgradable from: 2.1.12]
libexpat/stable 2.5.0 aarch64 [upgradable from: 2.4.2]
libgcrypt/stable 1.10.1-1 aarch64 [upgradable from: 1.9.4]
libgmp/stable 6.2.1-2 aarch64 [upgradable from: 6.2.1]
libgnutls/stable 3.7.8 aarch64 [upgradable from: 3.6.16-1]
libgpg-error/stable 1.46 aarch64 [upgradable from: 1.43]
libiconv/stable 1.17 aarch64 [upgradable from: 1.16-3]
libidn2/stable 2.3.4 aarch64 [upgradable from: 2.3.2]
liblz4/stable 1.9.4 aarch64 [upgradable from: 1.9.3]
liblzma/stable 5.4.1 aarch64 [upgradable from: 5.2.5-1]
libmpfr/stable 4.2.0 aarch64 [upgradable from: 4.1.0]
libnettle/stable 3.8.1 aarch64 [upgradable from: 3.7.3]
libnghttp2/stable 1.51.0 aarch64 [upgradable from: 1.46.0]
libssh2/stable 1.10.0-2 aarch64 [upgradable from: 1.10.0]
libtirpc/stable 1.3.3 aarch64 [upgradable from: 1.3.2]
libunistring/stable 1.1 aarch64 [upgradable from: 0.9.10-5]
lsof/stable 4.98.0 aarch64 [upgradable from: 4.94.0-1]
nano/stable 7.2 aarch64 [upgradable from: 6.0]
ncurses/stable 6.4-1 aarch64 [upgradable from: 6.2.20200725-6]
pcre2/stable 10.42 aarch64 [upgradable from: 10.39-2]
procps/stable 3.3.17-2 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.6-1 aarch64 [upgradable from: 23.4]
readline/stable 8.2.1 aarch64 [upgradable from: 8.1.1]
sed/stable 4.9 aarch64 [upgradable from: 4.8-2]
tar/stable 1.34-1 aarch64 [upgradable from: 1.34]
termux-am-socket/stable 1.5.0 aarch64 [upgradable from: 1.02]
termux-exec/stable 1:1.0 aarch64 [upgradable from: 1:0.9]
termux-keyring/stable 3.11 all [upgradable from: 2.4]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-1]
termux-tools/stable 1.36.1 all [upgradable from: 0.155]
unbound/stable 1.17.1 aarch64 [upgradable from: 1.13.2-1]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-7]
util-linux/stable 2.38.1-1 aarch64 [upgradable from: 2.37.2-1]
xz-utils/stable 5.4.1 aarch64 [upgradable from: 5.2.5-1]
zlib/stable 1.2.13 aarch64 [upgradable from: 1.2.11-5]
Android version:
13
Kernel build information:
Linux localhost 5.10.81-android12-9-25490797-abS908U1UES2BWA2 #1 SMP PREEMPT Fri Jan 6 23:29:56 UTC 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S908U1
~ $
```

**Comment by 2096779623** [comment]
`pkg upgr` first.

**Comment by xtkoba** [comment]
> I ran apt-get upgrade and it seemed to resolve the issue.

So this is already resolved.

**Comment by apple-corps** [comment]
> > I ran apt-get upgrade and it seemed to resolve the issue.
> 
> So this is already resolved.

I would think it's still a bug that leads to a poor UX. Install the latest version of termux then install openssh and have this issue.

Finally I'm confused by the configuration mess from `apt-get upgrade`. It seemed like there were multiple package configuration conflicts . 

What's the tactic for dealing with these conflicts in termux? I was forced to make an uniformed choice due to difficultes in viewing diffs on the phone screen. IIRC there were 3-4 conflicts. Why so many?

**Comment by xtkoba** [comment]
This is essentially an issue caused by partial upgrading. `apt-get install foo` does not upgrade dependencies of `foo` that are already installed. We do not support partial upgrading in our (probably unwritten?) maintenance policy.

You should do `apt-get update && apt-get upgrade` just before installing anything.

**Comment by xtkoba** [comment]
Debian-like distros provide `libcrypto1.1`, `libcrypto3` and have packages depend on (one of) them. But in our repo `openssh` just depends on `openssl`. In Termux app version 0.118.0 without any upgrading `openssl` provides "`libcrypto1.1`" but the latest `openssh` actually requires "`libcrypto3`", hence this issue.

To avoid catastrophe caused by this, some critical packages like `libcurl` explicitly specify "`libcrypto3`" (or later) as a dependency:

https://github.com/termux/termux-packages/blob/7749857860831a7674235a7701a1d84f526c4dec/packages/libcurl/build.sh#L10

But we do not do that for all packages, because we believe doing so increases maintenance costs. And we do not assume `openssh` to be a critical package.

We already have trouble with just specifying dependency (without version specifier) correctly. From time to time we receive bug reports of incorrect dependency. You cannot expect us to correctly specify dependency with version restriction added.

**Comment by xtkoba** [comment]
After all, it is far easier to just write

> Do `pkg upgrade` first.

and close issues immediately, than to add dependency version specifier to all packages and keep them up-to-date forever.

**Comment by apple-corps** [comment]
> Debian-like distros provide `libcrypto1.1`, `libcrypto3` and have packages depend on (one of) them. But in our repo `openssh` just depends on `openssl`. In Termux app version 0.118.0 without any upgrading `openssl` provides "`libcrypto1.1`" but the latest `openssh` actually requires "`libcrypto3`", hence this issue.
> 
> To avoid catastrophe caused by this, some critical packages like `libcurl` explicitly specify "`libcrypto3`" (or later) as a dependency:
> 
> https://github.com/termux/termux-packages/blob/7749857860831a7674235a7701a1d84f526c4dec/packages/libcurl/build.sh#L10
> 
> But we do not do that for all packages, because we believe doing so increases maintenance costs. And we do not assume `openssh` to be a critical package.
> 
> We already have trouble with just specifying dependency (without version specifier) correctly. From time to time we receive bug reports of incorrect dependency. You cannot expect us to correctly specify dependency with version restriction added.

Thanks for the detailed explanation.
