### ISSUE TITLE
[Package]: carbonyl

### ISSUE THREAD

**Issue by lostdusty** [termux/termux-packages#14938]
### Why do you want to add this package to Termux?

To run browser directly from termux, without X.

### Source code URL

https://github.com/fathyb/carbonyl

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

[Build instructions here.](https://github.com/fathyb/carbonyl#development)

Might actually rely on X11, see [this issue on carbonyl repo](https://github.com/fathyb/carbonyl/issues/21#issuecomment-1407774622).

Haven't tried building n my Moto G because it needs an arm64 processor, and I don't think its possible building on my Redmi 10 because of the Android version (12, MIUI 13)

**Comment by xtkoba** [comment]
Just that packages that depend on packages in x11 repo go to x11 repo.

I know a maintainer who is familiar with building Chromium from whom hopefully we can get some comment here.

**Comment by licy183** [comment]
It will cost about 1 day to build on GitHub Actions, so it is almost impossible to build...

**Comment by princessmortix** [comment]
No plans to use 3rd party CIs, like [refloat.ci](https://refloat.ci/home)?

**Comment by licy183** [comment]
> No plans to use 3rd party CIs, like [refloat.ci](https://refloat.ci/home)?

I'm afraid not. I think the official repository will not switch CI from GitHub Actions.

**Comment by princessmortix** [comment]
Understood, thanks!

**Comment by licy183** [comment]
Emmm... I tried to build it locally but it shows a blank screen. If you are interested in it, you can build it locally. The build script is at https://github.com/termux-user-repository/tur/commit/195af45696706ecbee60a6b22bc3d8d61beb5641.

**Comment by princessmortix** [comment]
> Emmm... I tried to build it locally but it shows a blank screen. If you are interested in it, you can build it locally. The build script is at [termux-user-repository/tur@195af45](https://github.com/termux-user-repository/tur/commit/195af45696706ecbee60a6b22bc3d8d61beb5641).

See [this issue](https://github.com/fathyb/carbonyl/issues/29) on the carbonyl repo. This happens when it can't determine terminal size.

**Comment by TomJo2000** [comment]
<sub>(Cleaning up old issues, feel free to ignore.)</sub>
Closed by termux-user-repository/tur#255
