### ISSUE TITLE
[Package]: rime-cli

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-packages#14960]
### Why do you want to add this package to Termux?

1. [coc-rime](https://github.com/tonyfettes/coc-rime) need it
2. A standard Go project which is very easy to transplanted to termux

### Home page URL

https://github.com/puddinging/rime-cli

### Source code URL

https://github.com/puddinging/rime-cli

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
I think this package should be added to [tur](https://github.com/termux-user-repository/tur) .
