### ISSUE TITLE
[Bug]: guile: guile-config looks for pkg-config in build machine specific location.

### ISSUE THREAD

**Issue by dragonmaus** [termux/termux-packages#15039]
### Problem description

The command `guile-config` includes a hard-coded path to the `pkg-config` binary, which was apparently derived from the temporary build path of the machine guile was built on. This prevents it from functioning correctly when given commands such as `guile-config info pkgdatadir`:

```
error: ("/home/builder/.termux-build/_cache/android-r25b-api-24-v3/bin/pkg-config" "--variable=pkgdatadir" "guile-3.0") exited with non-zero error code 127
```

I was able to temporarily fix the problem by editing the file `/data/data/com.termux/files/usr/bin/guile-config` and updating the `%pkg-config-program` binding on line 34.

### What steps will reproduce the bug?

```sh
guile-config info pkgdatadir
```

### What is the expected behavior?

The program runs successfully and prints:
```
/data/data/com.termux/files/usr/share/guile
```

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=31870
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.36.1
Android version:
13
Kernel build information:
Linux localhost 5.10.107-android13-4-00004-gf0fe4f768061-ab8935229 #1 SMP PREEMPT Thu Aug 11 01:16:28 UTC 2022 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 6a
```

**Comment by xtkoba** [comment]
Maybe I know how to work this around:

https://github.com/termux/termux-packages/blob/e30fdbf6f7fb15b8d0fd0470a1b3ed93700305df/packages/imagemagick/build.sh#L35-L36

Not yet looked in details though.
