### ISSUE TITLE
Neovim package lacks python (python3) support

### ISSUE THREAD

**Issue by BrainDamage** [termux/termux-packages#1504]
Neovim package lacks python (python3) support, try to launch a plugin which requires it and you'll get
'[deoplete] deoplete requires Neovim with Python3 support("+python3").'
unlike vim there seems to be no packages to provide the python plugins for neovim

**Comment by Neo-Oli** [comment]
It works a bit differently with Neovim. To enable python support you need to install the `neovim` package from pip. (Note: You need both the pip and apt package.)

`pip install neovim`

Note about deoplete: You should install the package before installing deoplete, as the installation already requires it. There is a [note ](https://github.com/Shougo/deoplete.nvim#note-python3-must-be-enabled-before-updating-remote-plugins) about it on the github page, but the command didn't work for me and I had to remove deoplete and install it again to make it work.

**Comment by akshgpt7** [comment]
Update: The `neovim` package has now changed to `pynvim`.
So, use `pip install pynvim` instead.
