### ISSUE TITLE
[Bug]: undefined symbol: frexp

### ISSUE THREAD

**Issue by guranu** [termux/termux-packages#15051]
### Problem description

Tried to compile this: https://github.com/iOrange/bcdec
However after cmaking `CMakeLists.txt` and typing `make` it gives the error `undefined symbol: frexp`

### What steps will reproduce the bug?

`cd bcdec
~/bcdec $ make
[ 50%] Linking C executable bcdec
ld.lld: error: undefined symbol: frexp
>>> referenced by stb_image_write.h:647
>>>               CMakeFiles/bcdec.dir/test.c.o:(stbi_write_hdr_core)
>>> referenced by stb_image_write.h:647
>>>               CMakeFiles/bcdec.dir/test.c.o:(stbi_write_hdr_core)
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/bcdec.dir/build.make:97: bcdec] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/bcdec.dir/all] Error 2
make: *** [Makefile:91: all] Error 2`

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=22720
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.36.1
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Thu Jan 28 00:40:44 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
GM1900
```

**Comment by xtkoba** [comment]
`frexp` is defined in `libm.so`. I would suggest something like

```bash
export LDFLAGS+=" -lm"
```

**Comment by guranu** [comment]
> 

Maybe i'm typing something wrong but it didn't do anything

```
export LDFLAGS+="frexp -lm"
~/bcdec $ make
[ 50%] Linking C executable bcdec
ld.lld: error: undefined symbol: frexp
>>> referenced by stb_image_write.h:647
>>>               CMakeFiles/bcdec.dir/test.c.o:(stbi_write_hdr_core)
>>> referenced by stb_image_write.h:647
>>>               CMakeFiles/bcdec.dir/test.c.o:(stbi_write_hdr_core)
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/bcdec.dir/build.make:97: bcdec] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/bcdec.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by xtkoba** [comment]
Not our issue anyway.

```
~ $ cat frexp.c
#include <math.h>
int main()
{
        return (int)frexp(0.0, (int *)0);
}
~ $ clang frexp.c
ld.lld: error: undefined symbol: frexp
>>> referenced by frexp.c
>>>               /data/data/com.termux/files/usr/tmp/frexp-3f8d43.o:(main)
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
~ $ clang frexp.c -lm
~ $
```

**Comment by truboxl** [comment]
Instead of exporting environment variable, just run `make LDFLAGS=-lm`.
You might want to check Makefile if it messes LDFLAGS internally...
