### ISSUE TITLE
[Bug]: Physfs segfault

### ISSUE THREAD

**Issue by maxsupermanhd** [termux/termux-packages#15069]
### Problem description

While trying to run physfs-powered application I am getting segfault in initialization phase

### What steps will reproduce the bug?

Install dependencies for Warzone 2100.

<spoiler>
apt
asciidoctor
bash
bzip2
ca-certificates
clang
cmake
command-not-found
coreutils
curl
dash
debianutils
dialog
diffutils
dos2unix
dpkg
ed
findutils
freetype-static
freetype
gawk
gdb
gettext
git
gpgv
grep
gzip
harfbuzz
htop
inetutils
less
libandroid-glob
libandroid-support
libassuan
libbz2
libc++
libcap-ng
libcrypt
libcurl
libevent
libexpat
libgcrypt
libgmp
libgnutls
libgpg-error
libiconv
libidn2
liblz4
liblzma
libmpfr
libnettle
libnghttp2
libnpth
libphysfs
libpng
libsodium
libsqlite
libssh2
libtheora
libtirpc
libunistring
lsof
nano
ncurses
net-tools
nmap
openal-soft
openssh
openssl
patch
pcre2
pcre
pkg-config
procps
psmisc
readline
sdl2
sed
strace
tar
termux-am-socket
termux-am
termux-exec
termux-keyring
termux-licenses
termux-tools
tigervnc
unbound
unzip
util-linux
wget
x11-repo
xfce4
xxhash
xz-utils
zip
zlib
</spoiler>

```
git clone https://github.com/warzone2100/warzone2100
cd warzone2100
git submodule update --init --recursive
mkdir build
cd build
cmake ..
cmake --build . -j
```

Successfully build executable warzone2100/build/src/warzone2100

(Xorg/display init is not reached so not really necessary to reproduce)

Run warzone2100

### What is the expected behavior?

Not a segfault

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=14810
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
xfce4-panel/x11 4.18.2 aarch64 [upgradable from: 4.18.1]
termux-tools version:
1.36.1
Android version:
11
Kernel build information:
Linux localhost 4.14.190-perf+ #1 SMP PREEMPT Fri Jun 17 12:17:41 CST 2022 aarch64 Android
Device manufacturer:
OnePlus
Device model:
GM1910
```

**Comment by maxsupermanhd** [comment]
![Screenshot_20230210-045137](https://user-images.githubusercontent.com/20772987/217982799-b5807d5a-5a27-4ff0-a8b5-34687e953b84.jpg)
![Screenshot_20230210-045725](https://user-images.githubusercontent.com/20772987/217982815-e82d3633-7e0c-4855-b2d4-ae88288c3aa5.jpg)
Looks like it crashes right after timezone read? (I am not in Africa but it is a matching timezone)

**Comment by xtkoba** [comment]
How about this: https://github.com/termux/termux-packages/actions/runs/4140247262

Time zone is not relevant here.

(The provided repro is somewhat elephantine and takes some time.)

**Comment by xtkoba** [comment]
Confirmed. And it is also confirmed that #15070 fixes this issue.
