### ISSUE TITLE
[Package]: tegaki-recognize

### ISSUE THREAD

**Issue by kawanakaiku** [termux/termux-packages#15072]
### Why do you want to add this package to Termux?

Chinese and Japanese Handwriting Recognition.
I'd like to input Chinese characters with x11.

### Home page URL

https://tegaki.github.io/

### Source code URL

https://github.com/tegaki/tegaki

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by kawanakaiku** [comment]
Seems to depend on pygtk.

**Comment by xtkoba** [comment]
Yeah. Projects that depend on `python2` at run-time won't be newly packaged.
