### ISSUE TITLE
[Repo Package]: dichvucoder-repo

### ISSUE THREAD

**Issue by Dichvucoder** [termux/termux-packages#15076]
### Why do you want to add this package to Termux?

I would like to have a separate repo to provide packages of my website (php,python extensions) and packages that are no longer supported by termux. Example: php-8.1,php7,php7-zts,php-8.1-zts,...
My repo was added to tur-repo, but I want to install it without going through tur-repo

### Home page URL

https://repo.dichvucoder.com

### Source code URL

https://github.com/Dichvucoder/dists

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

It has been built here
https://github.com/termux-user-repository/tur/tree/master/tur/dichvucoder-repo

**Comment by xtkoba** [comment]
This is not allowed. Thanks.

**Comment by xtkoba** [comment]
Adding unofficial `*-repo` packages (except for `tur-repo`) to our official repo is not allowed because TUR is:

https://github.com/termux/termux-packages/blob/f0ab4bf06c98c6224a06d52d4dd9560e1b5fce47/packages/tur-repo/build.sh#L2

**Comment by Grimler91** [comment]
@Dichvucoder Any particular reason for not adding your packages to the termux-user-repository instead?

Are your build recipes available somewhere? 
Publishing the build recipes allows users to verify that a published package is actually built from the recipe and sources that it claims to belong to, and to check so that malware is not inserted into a package for example

**Comment by Dichvucoder** [comment]
@Grimler91 It is located here : https://github.com/Dichvucoder/dvc-packages
Similar https://github.com/termux-user-repository/tur
But it is set to private mode
If necessary I can add you to the contributors section so you can check

**Comment by Dichvucoder** [comment]
I was assisted in creating by licy183 Uchiha Kakashi

**Comment by Dichvucoder** [comment]
> @Dichvucoder Any particular reason for not adding your packages to the termux-user-repository instead?

I don't want to disturb tur
And there are some packages I can't add to tur because I need to secure its source (extensions to run the encryption that protects the source of the php user).
I used to add it to tur but it was deleted and I got help creating a separate repo

**Comment by xtkoba** [comment]
Creating your own repo is OK. It is just that we won't authorize it.
