### ISSUE TITLE
How to detect android or termux in cmake?

### ISSUE THREAD

**Issue by huiyiqun** [termux/termux-packages#151]
Well, this is not a issue but a question.

I'm trying to compile YouCompleteMe in termux and nearly make it.

The problem is that librt is not available for android-ndk, which seems integrated into bionic. So I have to remove -lrt from ld when compile YCM on termux, but ˋCMAKE_SYSTEM_NAMEˋ is ˋlinuxˋ even under android. Is there any graceful method to detect termux or android in cmake?

I believe this problem is common for packager of termux.

**Comment by fornwall** [comment]
One possible solution could be to setup `librt.so` as a symlink to `libc.so´ in Termux, to avoid having to modify build systems. What do you think about that?

**Comment by fornwall** [comment]
@huiyiqun I looked around, and a better option than checking for Android is probably to check if `librt` exists, like in:

```cmake
CHECK_LIBRARY_EXISTS(rt clock_gettime "time.h" NEED_LIBRT)
IF(NEED_LIBRT)
    TARGET_LINK_LIBRARIES(${target} rt)
```

This is what e.g. [libgit2](https://github.com/libgit2/libgit2/blob/master/CMakeLists.txt#L155) does and it seems to work for them!

If you really want to detect Android, one possibility could be to execute `uname -o` and check if the output is `Android`.

**Comment by joakim-noah** [comment]
[The CMake docs suggest setting `CMAKE_SYSTEM_NAME` to `Android` when cross-compiling](https://cmake.org/cmake/help/v3.8/manual/cmake-toolchains.7.html#cross-compiling-for-android), would be nice if you could do the same when building CMake for Android, so that we could use that natively on Android itself.

**Comment by fornwall** [comment]
@joakim-noah Thanks, makes sense!

The [docs on CMAKE_SYSTEM_NAME](https://cmake.org/cmake/help/v3.0/variable/CMAKE_SYSTEM_NAME.html) says:

> This is the name of the operating system on which CMake is targeting. On systems that have the uname command, this variable is set to the output of uname -s. Linux, Windows, and Darwin for Mac OS X are the values found on the big three operating systems.

Currently `uname -s` in Termux outputs `Linux`, both for the uname supplied by Termux and the system `/system/bin/uname`.

So, if we are to change `CMAKE_SYSTEM_NAME` to Android, which makes sense, we could either:

1. Change `uname -s` to output `Android`, which will be picked up by cmake. Seems a bit risky in that it could break a lot of scripts not ready to handle that?

2. Patch `Modules/CMakeDetermineSystem.cmake` to default our cmake program in Termux to default set `CMAKE_SYSTEM_NAME=Android`.

I'm leaning towards (2), even if it would contradict the documentation. Any opinions?

**Comment by joakim-noah** [comment]
Yeah, (2) sounds good to me.

**Comment by joakim-noah** [comment]
Hmm, I tried setting `-DCMAKE_SYSTEM_NAME=Android` on the Termux command-line and CMake complains that it can't find the NDK or a standalone toolchain.  Looks like the Android support, which assumes cross-compilation, will need to be stripped out from the native CMake package, if we're going to do this.

**Comment by sgeto** [comment]
Hi
What's the status in this? I just checked and `Modules/CMakeDetermineSystem.cmake` has not been patches yet to return Android. Would be nice if that would come through.

He is how I am currently detecting TERMUX with cmake (some of these ideas are taken from your answers here. Thanks for that.)

```
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(OS_LINUX 1)
# check if we're building natively on Android (TERMUX)
    EXECUTE_PROCESS( COMMAND uname -o COMMAND tr -d '\n' OUTPUT_VARIABLE OPERATING_SYSTEM )
      if(${OPERATING_SYSTEM} MATCHES "Android")
        set(OS_ANDROID 1)
      endif(OPERATING_SYSTEM} MATCHES "Android")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Android")
# In case we're cross-compiling for Android and CMAKE_SYSTEM_NAME has been set manually (as suggest by cmake)
# https://cmake.org/cmake/help/v3.8/manual/cmake-toolchains.7.html#cross-compiling-for-android
    set(OS_ANDROID 1)
    set(OS_LINUX 1)
else()
    message(FATAL_ERROR "Operating system not supported")
endif()
```
This snippet is meant to set variable the variables OS_LINUX and/or OS_ANDROID (which can later be turned into preprocessor definitions). It's actually much longer and checks for other operating systems as well.
In case you're wondering, `tr` is used to cut off the trailing "Carriage Return"
Hope this is of use for someone.

**Comment by buttaface** [comment]
Can Termux finally patch CMake to set CMAKE_SYSTEM_NAME to Android? I've had to work around it with patches like [this](https://github.com/apple/swift/commit/796d6ad#diff-af3b638bc2a3e6c650974192a53c7291R606) or [this](https://gist.github.com/buttaface/8b4e9c5e0a034d00466b4ac3522ec3fa), as I'm sure pretty much anyone using CMake on Android has to. Since Android has been standardized for that CMake variable when cross-compiling, Termux should be using the same name natively, if not also submitting a pull for this to CMake upstream.
