### ISSUE TITLE
[Package]: transmission-4

### ISSUE THREAD

**Issue by urain39** [termux/termux-packages#15113]
### Why do you want to add this package to Termux?

Transmission has been updated to version 4.0.0, and a lot of code has been refactored in the new version.

### Home page URL

https://github.com/transmission/transmission

### Source code URL

https://github.com/transmission/transmission

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
PR #15114 is now ready to merge. It is recommended that you test the artifacts. It is probable that this results in some regression, because this is a major bump. Thanks.

**Comment by urain39** [comment]
It works. Thanks!
