### ISSUE TITLE
[Bug]: screen input a symbol exception under GBK

### ISSUE THREAD

**Issue by zixijian** [termux/termux-packages#15117]
### Problem description

Can not enter symbols such as `♡▲★☆` after specifying the default encoding for screen as GBK，it will show `????`.

But SSH to other environments in Termux or standalone linux environments  you can enter these characters using the same configuration.

The screen version number for Termux is 4.9, and the screen version in Ubuntu18 I tested was 4.6.2.

Since I couldn't successfully compile screen in Termux, I'm not sure if it's a configuration or patch problem in Termux for screen.

### What steps will reproduce the bug?

```
pkg in screen -y
echo defencoding GBK > ~/.screenrc
screen bash
```
Then Enter these characters.

### What is the expected behavior?

Can not enter these characters in gbk environment.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1+2c6674f
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~4hW-lcmLWmuqzUxujAHQ8A==/com.termux-5sqTRjHA5gl_hJoxRkQt1Q==/base.apk
TERMUX_APP__APK_RELEASE=UNKNOWN
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=21870
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c244,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c244,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10244
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+8421173
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+8421173
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
Updatable packages:
command-not-found/stable 2.1.0-10 aarch64 [upgradable from: 2.1.0-9]
ffmpeg/stable 5.1.2-5 aarch64 [upgradable from: 5.1.2-4]
less/stable 608-1 aarch64 [upgradable from: 608]
python/stable 3.11.2-2 aarch64 [upgradable from: 3.11.2-1]
termux-tools version:
1.36.1
Android version:
13
Kernel build information:
Linux 11tp 5.10.101-android12-9-00027-g1292f517889e-ab8602202 #1 SMP PREEMPT Mon May 16 11:18:04 UTC 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
22041216C
```

**Comment by xtkoba** [comment]
This is because Android does not support locales other than `C.UTF-8` (a.k.a. `en_US.UTF-8`). GBK cannot be used on Android.

**Comment by zixijian** [comment]
@xtkoba 

I don't know how screen makes this configuration work. 

Currently it can display most of the GBK characters correctly in termux. 

Any other solutions?

**Comment by xtkoba** [comment]
What do you mean by GBK characters? If these characters are in Unicode then it is natural if they are printed.

**Comment by zixijian** [comment]
@xtkoba 

If I connect to a gbk-encoded mud server using `screen tt++`, all the data I receive will be garbled. If I use `echo defencoding GBK > ~ / .screenrc` , the Chinese and some characters will be displayed correctly (include ☆★,But you can't enter)

**Comment by xtkoba** [comment]
Maybe "GBK" is handled differenly in different part of the code. I would say GBK locale is invalid in Android and should not be used. This is a restriction derived from Bionic libc and we cannot fix it on our own.

**Comment by xtkoba** [comment]
FWIW, once we had an issue where `lftp` is broken with `de_DE.UTF-8` locale. Our "solution" is to tell the OP not to use `de_DE.UTF-8`. Pretty much the same here.

**Comment by zixijian** [comment]
@xtkoba 

Isn't it strange that the data sent by the server can be displayed correctly, but it can't be entered?

**Comment by xtkoba** [comment]
Nothing strange, they can be "handled differenly in different part of the code" as I wrote.
