### ISSUE TITLE
Request for removal of disabled packages from bindist mirrors

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#15116]
To infra team,

please remove the following packages from bindist mirros. Thanks.

#### main repo

- [ ] libarrow-python
- [ ] libexecinfo
- [ ] mingw-w64
- [ ] mingw-w64-crt
- [ ] mingw-w64-gcc-libs

#### x11 repo

- [ ] libdrm (*)
- [ ] libxshmfence (*)
- [ ] libxshmfence-static (*)
- [ ] libxxf86vm (*)
- [ ] libxxf86vm-static (*)
- [ ] pypanel
- [ ] python2-six
- [ ] python2-xlib

Note that the packages marked as (*) have been moved to main repo. Please make sure that you do *not* remove these packages in main repo.

#### root repo

- [ ] bettercap

**Comment by Grimler91** [comment]
Done, packages will be gone next time repos are re-signed, thanks!

**Comment by zorro** [comment]
@Grimler91 `libexecinfo-static` is still in repository
