### ISSUE TITLE
[Bug]: Astra ISP should be removed from default mirror rotation

### ISSUE THREAD

**Issue by alexandervlpl** [termux/termux-packages#15197]
### Problem description

This Ukrainian mirror (termux.astra.in.ua) is blocking all connections from Russia. This may or may not be justified, but I think any mirror that deliberately restricts access like this has no place in the default rotation list. It breaks Termux for many users and the solution is not obvious.

I would also argue this is against the spirit of projects like Termux, open source, and the Internet as it should be. Happy to discuss in a more appropriate place.

_Edit: this domain/IP is currently not blocked in Russia if anyone is wondering._

### What steps will reproduce the bug?

Open https://termux.astra.in.ua/apt/termux-main in Russia.

### What is the expected behavior?

Mirrors in the default rotation list should be globally accessible.

### System information

not relevant

**Comment by Grimler91** [comment]
You can subscribe to the Russian mirror group with the `termux-change-repo` tool to avoid the issue (we [encourage users to select a mirror group](https://github.com/termux/termux-tools/blob/master/scripts/pkg.in#L140) if they have not done so).

You can also manually remove any mirror that is unsuitable: 

```
rm $PREFIX/etc/termux/mirrors/europe/termux.astra.in.ua
```

The astra mirror is useful for people in Ukraine and nearby European countries, so I don't think it is fair to remove it for all users. As @sylirre said the mirror is down every now and then though (because of blackouts?)

**Comment by alexandervlpl** [comment]
Thanks for taking a look at this. @sylirre here's the output, it does look like I'm completely blocked and the checks aren't working:
```
*   Trying 193.93.216.77:443...
*   Trying 2a10:2f40:1::20e:443...
* connect to 2a10:2f40:1::20e port 443 failed: Network is unreachable
* After 2248ms connect time, move on!
* connect to 193.93.216.77 port 443 failed: Connection timed out
* Failed to connect to termux.astra.in.ua port 443 after 2953 ms: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to termux.astra.in.ua port 443 after 2953 ms: Connection timed out
```
As of this moment this works just fine outside Russia, the server is online.

@Grimler91 I did run `termux-change-repo` after reading the wiki, but I really don't think something like that should be necessary to get Termux running (especially for a first time user). The default setup should be reasonably reliable.

If this mirror is often offline as you say, is that not an even better reason for excluding it from the default list? At the very least, these problems should be mentioned on the wiki page.

**Comment by alexandervlpl** [comment]
Where is this check mechanism? Maybe I can do some testing.

**Comment by agnostic-apollo** [comment]
>the question is how mirror checker function let it be marked as "good"

Fresh installation from F-Droid or Github would have old `termux-tools` version and it selects bad mirrors like `deb.kcubeterm.me`, that may be the reason.

**Comment by alexandervlpl** [comment]
After a full `pkg upgrade` I have the latest `termux-tools` and I can confirm that the check works now and this mirror is marked as bad. Also I see the prompt to run `termux-change-repo` which is helpful.

@agnostic-apollo yes, this is an F-Droid install and I've experienced these repo problems before now that you mention it.

Maybe it's time to make an F-Droid release? :smile:

**Comment by ChiefMikeK** [comment]
I would suggest it's about time for a minor f-droid point release as in `0.118.1` :neckbeard:

**Comment by agnostic-apollo** [comment]
> Maybe it's time to make an F-Droid release? 😄

Any day (, week, month, year) now! ;)
