### ISSUE TITLE
~/x11-packages $ ./build-package.sh
bash: ./build-package.sh: No such file or directory

### ISSUE THREAD

**Issue by Jazzsimavlabal** [termux/termux-packages#15192]

**Comment by Jazzsimavlabal** [comment]
~ $ cd ./x11-packages
./start-builder.sh
touch: cannot touch '/tmp/.termux-x11-builder.lck': No such file or directory
~/x11-packages $ cd ./x11-packages
bash: cd: ./x11-packages: No such file or directory
~/x11-packages $ ./start-builder.sh
touch: cannot touch '/tmp/.termux-x11-builder.lck': No such file or directory
~/x11-packages $ ./build-package.sh
bash: ./build-package.sh: No such file or directory
~/x11-packages $

**Comment by Jazzsimavlabal** [comment]
$ pkg install x11-repo
Testing the available mirrors:
[*] (10) https://packages-cf.termux.dev/apt/termux-main: ok
[*] (1) https://mirror.textcord.xyz/termux/termux-main: ok
[*] (1) https://mirror.nevacloud.com/applications/termux/termux-main: ok
[*] (1) https://linux.domainesia.com/applications/termux/termux-main: ok
[*] (1) https://mirror.albony.xyz/termux/termux-main: ok
[*] (1) https://mirrors.cbrx.io/apt/termux/termux-main: ok
[*] (1) https://packages.nscdn.top/termux-main: bad
[*] (1) https://mirror.bardia.tech/termux/termux-main: ok
[*] (1) https://mirrors.dgut.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.cqupt.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.aliyun.com/termux/termux-main: ok
[*] (1) https://mirror.iscas.ac.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.njupt.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.sdu.edu.cn/termux/termux-main: ok
[*] (1) https://mirror.nyist.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.sau.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.pku.edu.cn/termux/termux-main/: ok
[*] (1) https://mirrors.nju.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.bfsu.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.sustech.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.scau.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.hit.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.ustc.edu.cn/termux/apt/termux-main: ok
[*] (1) https://packages.termux.dev/apt/termux-main: ok
[*] (1) https://termux.astra.in.ua/apt/termux-main: ok
[*] (1) https://termux.mentality.rip/termux-main: ok
[*] (1) https://termux.librehat.com/apt/termux-main: ok
[*] (1) https://mirrors.sahilister.in/termux/termux-main: ok
[*] (4) https://grimler.se/termux/termux-main: ok
[*] (1) https://mirror.termux.dev/termux-main: ok
[*] (1) https://mirror.accum.se/mirror/termux.dev/termux-main: ok
[*] (1) https://termux.3san.dev/termux/termux-main: ok
[*] (1) https://mirror.mwt.me/termux/main: ok
[*] (1) https://termux.cdn.lumito.net/termux-main: ok
[*] (1) https://plug-mirror.rcac.purdue.edu/termux/termux-main: ok
[*] (1) https://mirrors.utermux.dev/termux/termux-main: ok
[*] (1) https://mirror.fcix.net/termux/termux-main: ok
[*] (1) https://mirror.vern.cc/termux/termux-main: ok
[*] (1) https://dl.kcubeterm.com/termux-main: ok

[*] (1) https://mirror.mwt.me/termux/main: ok
[*] (1) https://mirror.csclub.uwaterloo.ca/termux/termux-main: ok
[*] (1) http://mirror.mephi.ru/termux/termux-main: ok
[*] (1) https://mirror.surf/termux/termux-main/: ok
oPicking mirror: (49) /data/data/com.termux/files/usr/etc/termux/mirrors/north_america/mirror.csclub.uwaterloo.ca
Get:1 https://mirror.csclub.uwaterloo.ca/termux/termux-main stable InRelease [14.0 kB]
Get:2 https://mirror.csclub.uwaterloo.ca/termux/termux-root root InRelease [14.2 kB]
Get:3 https://mirror.csclub.uwaterloo.ca/termux/termux-main stable/main aarch64 Packages [488 kB]
Get:4 https://mirror.csclub.uwaterloo.ca/termux/termux-root root/stable aarch64 Packages [17.6 kB]
Fetched 534 kB in 6s (83.3 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  x11-repo
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1204 B of archives.
After this operation, 53.2 kB of additional disk space will be used.
Get:1 https://mirror.csclub.uwaterloo.ca/termux/termux-main stable/main aarch64 x11-repo all 8.4-1 [1204 B]
Fetched 1204 B in 1s (830 B/s)

okSelecting previously unselected package x11-repo.
(Reading database ... 7221 files and directories currently installed.)
Preparing to unpack .../x11-repo_8.4-1_all.deb ...
Unpacking x11-repo (8.4-1) ...
Setting up x11-repo (8.4-1) ...
Downloading updated package list ...
Get:1 https://packages-cf.termux.dev/apt/termux-x11 x11 InRelease [14.0 kB]
Hit:2 https://mirror.csclub.uwaterloo.ca/termux/termux-main stable InRelease
Hit:3 https://mirror.csclub.uwaterloo.ca/termux/termux-root root InRelease
Get:4 https://packages-cf.termux.dev/apt/termux-x11 x11/main aarch64 Packages [121 kB]
Fetched 135 kB in 3s (40.4 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
~ $ git clone https://github.com/termux/x11-packages
Cloning into 'x11-packages'...
remote: Enumerating objects: 23651, done.
remote: Counting objects: 100% (613/613), done.
remote: Compressing objects: 100% (386/386), done.
Receiving objects:   2% (474/23651), 148.01 KiB | 273.00 KiReceiving objects:   2% (507/23651), 148.01 KiB | 273.00 KiReceiving objects:   3% (710/23651), 316.01 KiB | 298.00 KiReceiving objects:   4% (947/23651), 484.01 KiB | 309.00 KiReceiving objects:   5% (1183/23651), 484.01 KiB | 309.00 KReceiving objects:   6% (1420/23651), 484.01 KiB | 309.00 KReceiving objects:   7% (1656/23651), 644.01 KiB | 312.00 KReceiving objects:   8% (1893/23651), 644.01 KiB | 312.00 KReceiving objects:   9% (2129/23651), 644.01 KiB | 312.00 KReceiving objects:  10% (2366/23651), 796.01 KiB | 310.00 KReceiving objects:  10% (2588/23651), 852.01 KiB | 276.00 KReceiving objects:  11% (2602/23651), 852.01 KiB | 276.00 KReceiving objects:  12% (2839/23651), 932.01 KiB | 259.00 KReceiving objects:  12% (3025/23651), 988.01 KiB | 181.00 KReceiving objects:  13% (3075/23651), 988.01 KiB | 181.00 KReceiving objects:  14% (3312/23651), 988.01 KiB | 181.00 KReceiving objects:  15% (3548/23651), 988.01 KiB | 181.00 KReceiving objects:  15% (3763/23651), 1.77 MiB | 281.00 KiBReceiving objects:  15% (3763/23651), 2.09 MiB | 280.00 KiBReceiving objects:  15% (3763/23651), 2.42 MiB | 282.00 KiBReceiving objects:  15% (3763/23651), 2.58 MiB | 301.00 KiBReceiving objects:  15% (3763/23651), 2.89 MiB | 427.00 KiBReceiving objects:  15% (3763/23651), 3.21 MiB | 318.00 KiBReceiving objects:  15% (3763/23651), 3.54 MiB | 320.00 KiBReceiving objects:  15% (3763/23651), 3.89 MiB | 326.00 KiBReceiving objects:  16% (3785/23651), 4.11 MiB | 339.00 KiBReceiving objects:  17% (4021/23651), 4.11 MiB | 339.00 KiBReceiving objects:  17% (4052/23651), 4.11 MiB | 339.00 KiBReceiving objects:  18% (4258/23651), 4.11 MiB | 339.00 KiBReceiving objects:  19% (4494/23651), 4.36 MiB | 357.00 KiBReceiving objects:  20% (4731/23651), 4.36 MiB | 357.00 KiBReceiving objects:  21% (4967/23651), 4.36 MiB | 357.00 KiBReceiving objects:  22% (5204/23651), 4.36 MiB | 357.00 KiBReceiving objects:  23% (5440/23651), 4.36 MiB | 357.00 KiBReceiving objects:  24% (5677/23651), 4.36 MiB | 357.00 KiBReceiving objects:  25% (5913/23651), 4.36 MiB | 357.00 KiBReceiving objects:  26% (6150/23651), 4.36 MiB | 357.00 KiBReceiving objects:  27% (6386/23651), 4.61 MiB | 383.00 KiBReceiving objects:  28% (6623/23651), 4.61 MiB | 383.00 KiBReceiving objects:  29% (6859/23651), 4.61 MiB | 383.00 KiBReceiving objects:  30% (7096/23651), 4.61 MiB | 383.00 KiBReceiving objects:  30% (7129/23651), 4.61 MiB | 383.00 KiBReceiving objects:  31% (7332/23651), 4.61 MiB | 383.00 KiBReceiving objects:  32% (7569/23651), 4.82 MiB | 393.00 KiBReceiving objects:  32% (7637/23651), 5.26 MiB | 420.00 KiBReceiving objects:  32% (7637/23651), 5.66 MiB | 439.00 KiBReceiving objects:  32% (7637/23651), 6.00 MiB | 411.00 KiBReceiving objects:  32% (7637/23651), 6.45 MiB | 351.00 KiBReceiving objects:  32% (7637/23651), 6.71 MiB | 359.00 KiBReceiving objects:  32% (7637/23651), 6.97 MiB | 365.00 KiBReceiving objects:  32% (7637/23651), 7.46 MiB | 384.00 KiBReceiving objects:  32% (7637/23651), 7.85 MiB | 410.00 KiBReceiving objects:  33% (7805/23651), 7.85 MiB | 410.00 KiBReceiving objects:  34% (8042/23651), 7.85 MiB | 410.00 KiBReceiving objects:  34% (8272/23651), 8.23 MiB | 382.00 KiBReceiving objects:  34% (8272/23651), 8.60 MiB | 420.00 KiBReceiving objects:  34% (8272/23651), 8.81 MiB | 355.00 KiBReceiving objects:  34% (8272/23651), 9.04 MiB | 309.00 KiBReceiving objects:  34% (8272/23651), 9.37 MiB | 301.00 KiBReceiving objects:  34% (8272/23651), 9.75 MiB | 290.00 KiBReceiving objects:  34% (8272/23651), 10.12 MiB | 319.00 KiReceiving objects:  34% (8272/23651), 10.48 MiB | 333.00 KiReceiving objects:  34% (8272/23651), 10.76 MiB | 362.00 KiReceiving objects:  34% (8272/23651), 11.04 MiB | 327.00 KiReceiving objects:  34% (8272/23651), 11.33 MiB | 306.00 KiReceiving objects:  35% (8278/23651), 11.33 MiB | 306.00 KiReceiving objects:  35% (8380/23651), 11.41 MiB | 280.00 KiReceiving objects:  35% (8380/23651), 11.69 MiB | 264.00 KiReceiving objects:  35% (8380/23651), 11.93 MiB | 251.00 KiReceiving objects:  35% (8380/23651), 12.13 MiB | 228.00 KiReceiving objects:  35% (8380/23651), 12.39 MiB | 225.00 KiReceiving objects:  35% (8380/23651), 12.49 MiB | 202.00 KiReceiving objects:  35% (8380/23651), 12.51 MiB | 165.00 KiReceiving objects:  35% (8380/23651), 12.67 MiB | 144.00 KiReceiving objects:  35% (8380/23651), 12.73 MiB | 129.00 KiReceiving objects:  35% (8380/23651), 12.86 MiB | 109.00 KiReceiving objects:  35% (8380/23651), 13.25 MiB | 161.00 KiReceiving objects:  35% (8380/23651), 13.61 MiB | 221.00 KiReceiving objects:  35% (8380/23651), 13.84 MiB | 217.00 KiReceiving objects:  35% (8436/23651), 14.49 MiB | 258.00 KiReceiving objects:  36% (8515/23651), 14.49 MiB | 258.00 KiReceiving objects:  37% (8751/23651), 14.49 MiB | 258.00 KiReceiving objects:  38% (8988/23651), 14.49 MiB | 258.00 KiReceiving objects:  39% (9224/23651), 14.49 MiB | 258.00 KiReceiving objects:  40% (9461/23651), 14.49 MiB | 258.00 KiReceiving objects:  41% (9697/23651), 14.49 MiB | 258.00 KiReceiving objects:  42% (9934/23651), 14.49 MiB | 258.00 KiReceiving objects:  43% (10170/23651), 14.49 MiB | 258.00 KReceiving objects:  44% (10407/23651), 14.49 MiB | 258.00 KReceiving objects:  45% (10643/23651), 14.49 MiB | 258.00 KReceiving objects:  46% (10880/23651), 14.49 MiB | 258.00 KReceiving objects:  47% (11116/23651), 14.49 MiB | 258.00 KReceiving objects:  48% (11353/23651), 14.49 MiB | 258.00 KReceiving objects:  49% (11589/23651), 14.49 MiB | 258.00 KReceiving objects:  50% (11826/23651), 14.49 MiB | 258.00 KReceiving objects:  51% (12063/23651), 14.49 MiB | 258.00 KReceiving objects:  52% (12299/23651), 14.49 MiB | 258.00 KReceiving objects:  53% (12536/23651), 14.49 MiB | 258.00 KReceiving objects:  54% (12772/23651), 14.49 MiB | 258.00 KReceiving objects:  55% (13009/23651), 14.49 MiB | 258.00 KReceiving objects:  56% (13245/23651), 14.49 MiB | 258.00 KReceiving objects:  57% (13482/23651), 14.49 MiB | 258.00 KReceiving objects:  58% (13718/23651), 14.49 MiB | 258.00 KReceiving objects:  59% (13955/23651), 14.49 MiB | 258.00 KReceiving objects:  60% (14191/23651), 14.49 MiB | 258.00 KReceiving objects:  61% (14428/23651), 14.49 MiB | 258.00 KReceiving objects:  62% (14664/23651), 14.49 MiB | 258.00 KReceiving objects:  63% (14901/23651), 14.49 MiB | 258.00 KReceiving objects:  64% (15137/23651), 14.49 MiB | 258.00 KReceiving objects:  65% (15374/23651), 14.49 MiB | 258.00 KReceiving objects:  66% (15610/23651), 14.49 MiB | 258.00 KReceiving objects:  67% (15847/23651), 14.49 MiB | 258.00 KReceiving objects:  68% (16083/23651), 14.49 MiB | 258.00 KReceiving objects:  69% (16320/23651), 14.49 MiB | 258.00 KReceiving objects:  70% (16556/23651), 14.49 MiB | 258.00 KReceiving objects:  71% (16793/23651), 14.49 MiB | 258.00 KReceiving objects:  71% (17019/23651), 14.49 MiB | 258.00 KReceiving objects:  72% (17029/23651), 14.49 MiB | 258.00 KReceiving objects:  73% (17266/23651), 14.49 MiB | 258.00 KReceiving objects:  74% (17502/23651), 15.16 MiB | 353.00 KReceiving objects:  75% (17739/23651), 15.16 MiB | 353.00 KReceiving objects:  76% (17975/23651), 15.16 MiB | 353.00 KReceiving objects:  77% (18212/23651), 15.16 MiB | 353.00 KReceiving objects:  78% (18448/23651), 15.16 MiB | 353.00 KReceiving objects:  79% (18685/23651), 15.16 MiB | 353.00 KReceiving objects:  80% (18921/23651), 15.16 MiB | 353.00 KReceiving objects:  81% (19158/23651), 15.16 MiB | 353.00 KReceiving objects:  82% (19394/23651), 15.16 MiB | 353.00 KReceiving objects:  83% (19631/23651), 15.16 MiB | 353.00 KReceiving objects:  84% (19867/23651), 15.39 MiB | 388.00 KReceiving objects:  85% (20104/23651), 15.39 MiB | 388.00 KReceiving objects:  86% (20340/23651), 15.39 MiB | 388.00 KReceiving objects:  87% (20577/23651), 15.39 MiB | 388.00 KReceiving objects:  88% (20813/23651), 15.39 MiB | 388.00 KReceiving objects:  89% (21050/23651), 15.39 MiB | 388.00 KReceiving objects:  89% (21181/23651), 15.61 MiB | 408.00 KReceiving objects:  89% (21190/23651), 15.93 MiB | 395.00 KReceiving objects:  89% (21215/23651), 16.25 MiB | 392.00 KReceiving objects:  90% (21286/23651), 16.25 MiB | 392.00 KReceiving objects:  91% (21523/23651), 16.51 MiB | 486.00 KReceiving objects:  92% (21759/23651), 16.51 MiB | 486.00 KReceiving objects:  93% (21996/23651), 16.51 MiB | 486.00 KReceiving objects:  94% (22232/23651), 16.51 MiB | 486.00 KReceiving objects:  95% (22469/23651), 16.51 MiB | 486.00 KReceiving objects:  96% (22705/23651), 16.51 MiB | 486.00 KReceiving objects:  97% (22942/23651), 16.51 MiB | 486.00 KReceiving objects:  97% (23060/23651), 16.51 MiB | 486.00 KReceiving objects:  98% (23178/23651), 16.51 MiB | 486.00 KReceiving objects:  99% (23415/23651), 16.51 MiB | 486.00 Kremote: Total 23651 (delta 222), reused 474 (delta 165), pack-reused 23038
Receiving objects: 100% (23651/23651), 16.86 MiB | 531.00 KReceiving objects: 100% (23651/23651), 16.91 MiB | 319.00 KiB/s, done.
Resolving deltas: 100% (13916/13916), done.
~ $ cd ./x11-packages
./start-builder.sh
touch: cannot touch '/tmp/.termux-x11-builder.lck': No such file or directory
~/x11-packages $ cd ./x11-packages
bash: cd: ./x11-packages: No such file or directory
~/x11-packages $ ./start-builder.sh
touch: cannot touch '/tmp/.termux-x11-builder.lck': No such file or directory
~/x11-packages $ ./build-package.sh
bash: ./build-package.sh: No such file or directory
~/x11-packages $

**Comment by xtkoba** [comment]
We have no such file as `start-builder.sh` in our repo. Maybe it derives from now archived `x11-packages` repo, but we do not support it anymore.
