### ISSUE TITLE
[Bug]: ls with -A option fails in sh

### ISSUE THREAD

**Issue by zongou** [termux/termux-packages#15196]
### Problem description

ls with -A option should ignore ./ and ../
however. when running in sh shell, this fails.

### What steps will reproduce the bug?

in home dir, run sh -c "ls -A .*"
current dir ./ and upper dir ../
is listed too.

### What is the expected behavior?

ignoring . and .., not to list upper dir

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=25481
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf-g90eb916 #1 SMP PREEMPT Thu May 7 23:04:42 CST 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
MI 8
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

```

**Comment by licy183** [comment]
IMO this is not a bug of Termux. `.*` has different values in bash and dash. For more information, run `bash -c 'echo .*'` and `sh -c 'echo .*'`.
