### ISSUE TITLE
cpanm Net::HTTP failed!

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1519]
```
$ cpanm Net::HTTP
--> Working on Net::HTTP
Fetching http://www.cpan.org/authors/id/O/OA/OALDERS/Net-HTTP-6.17.tar.gz ... OK
Configuring Net-HTTP-6.17 ... OK
Building and testing Net-HTTP-6.17 ... FAIL
! Installing Net::HTTP failed. See /data/data/com.termux/files/home/.cpanm/work/1505497559.26966/build.log for details. Retry with --force to force install it.
```
Build log at https://sdrausty.github.io/logs/150549755926966build.log
```
$ cpanm IO::Socket::INET6
--> Working on IO::Socket::INET6
Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/IO-Socket-INET6-2.72.tar.gz ... OK
Configuring IO-Socket-INET6-2.72 ... OK
Building and testing IO-Socket-INET6-2.72 ... FAIL
! Installing IO::Socket::INET6 failed. See /data/data/com.termux/files/home/.cpanm/work/1505499256.30175/build.log for details. Retry with --force to force install it.
```
Build log at https://sdrausty.github.io/logs/150549925630175build.log

These are prerequisite modules for other Perl modules. So they are probably very important for successful Perl builds like https://github.com/termux/termux-packages/issues/981 Building biber in Termux perl Dependency Install ERROR.

Android 6.0.1 aarch64

![screenshot_20170915-142238](https://user-images.githubusercontent.com/27742457/30497594-5f05b10e-9a21-11e7-995d-b72d37fbcc2a.png)

**Comment by sdrausty** [comment]
From `$ cpan Net::HTTP`:

```
#     Module             Want    Have
#     ----------------- ----- -------
#     IO::Socket          any    1.38
#     IO::Socket::INET6   any missing
```
From `$ cpan IO::Socket::INET6`:
```
IO::Socket::INET6: sock_info: Bad protocol 'tcp' at t/blocking.t line 34.
```
It bubbles down to successfully installing IO::Socket::INET6 on device. This should resolve numerous Perl troubles.

**Comment by stainslav** [comment]
Java 9 no root termux?

**Comment by sdrausty** [comment]
@stainslav standard by the book, out of box, install Termux 💪 That is it. 

Hmmm...
```
java
```
Did anyone mention anything about java on Android on device?
https://github.com/termux/termux-packages/issues?utf8=✓&q=java

**Comment by sdrausty** [comment]
It is possible to install both `Net::HTTP` and `IO::Socket::INET6` on device in Arch Linux in Termux.  See https://sdrausty.github.io/TermuxArch/  Use `pacman -S base-devel perl` before installing.  
![screenshot_20171124-231535](https://user-images.githubusercontent.com/27742457/33227271-6829aa6e-d16d-11e7-92ab-fd0808f2bad7.png)
