### ISSUE TITLE
Gpgme doesn't work correctly in mutt yet

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#152]
Because of my experimentation with pass I've dipped a bit into gpg and would now like to use gpg with mutt and I've read it should be very easy to configure with gpgme, but mutt states it's not built with gpgme support.

**Comment by fornwall** [comment]
Hi, I added `--enable-gpgme` to the mutt configure run and built an experimental deb. Can you try installing it with:

    wget http://fornwall.net/mutt-with-gpgme.deb
    apt install ./mutt-with-gpgme.deb

and check if it works ok?

**Comment by Neo-Oli** [comment]
When I try to send an email I get a `"error signing data: unsupported protocol"`message. mutt also prints the following to sterr:
```
    GPGME: OpenPGP protocol not available
    GPGME: CMS protocol not available
```
I couldn't really find any information about these errors. I haven't used gpgme and mutt on any other environment, so maybe I'm doing something wrong.

**Comment by its-pointless** [comment]
I fiddled around and got it to work. Uninstalled gnupg2 gpgsm doesn't seem to work. 
added "set crypt_use_gpgme = yes" and "set pgp_auto_decode = yes" to .muttrc.

**Comment by Neo-Oli** [comment]
@its-pointless Were you able to sign mails with your config? That's where my errors occur. I added `set crypt_autosign=yes` to my config, so mails would get signed during sending.

**Comment by its-pointless** [comment]
yes i can get it working. Just tested it then. Trying pressing p just before you send the mail. Should encrypt if it can't work out automatically to use what key.

**Comment by Neo-Oli** [comment]
After uninstalling gnupg2 I am getting a bad passphrase error. Am I right in assuming that after pressing p and choosing to sign I should get prompted to input my passphrase? Because that isn't happening.

**Comment by Neo-Oli** [comment]
I just tested it with traditional configuration without gpgme and that does work and ask me for a my passphrase.

**Comment by its-pointless** [comment]
If you are encrypting it there is no pass phrase required. You only need a that to decrypt

**Comment by Neo-Oli** [comment]
I've since used the traditional method of configuring Mutt with GnuPG and became familiar with it. I was right that I should get prompted for my passphrase when I try to sign a message. Unfortunately http://fornwall.net/mutt-with-gpgme.deb 404'd, so I can no longer test this.

**Comment by Neo-Oli** [comment]
Sorry for accidentally closing.

**Comment by fornwall** [comment]
@Neo-Oli Great, it applies now! Which dependencies should the package have, something more than `bash` and `coreutils`?

**Comment by fornwall** [comment]
@Neo-Oli @its-pointless I have [updated the mutt package](https://github.com/termux/termux-packages/commit/196cc8991b9e05256986c71858e19295a6767aff) to version `1.5.24-3` which contains the gpgme support, so you can install it as a normal update with `apt update && apt upgrade`.

Try it out and let me know how it works.

**Comment by Neo-Oli** [comment]
I  am still getting `Error: decryption/verification failed: Bad passphrase` error after not being prompted a passphrase. The only configutation I have is `set crypt_use_gpgme=yes`, which [this tutorial ](http://henrytodd.org/notes/2014/simpler-gnupg-mutt-config-with-gpgme/)claims would "just work". It also still prints `GPGME: CMS protocol not available`to sterr. @its-pointless If you do any action that requires entering a passphrase, like decrypting, does that work?

**Comment by its-pointless** [comment]
Yeah its not asking for password

**Comment by its-pointless** [comment]
okay i think the issue is that gnupg2 is required to get it to ask for password. But using that mutt doesn't detect available protocol gpg-agent. The difference in behavior is caused  because without gnugp2 mutt doesn't use gpgconf because its not there. gpgconf is not working as intended according to mutt.

**Comment by fornwall** [comment]
>  debian there is a lot of output from gpgconf that isn't there in termux

It seems that gpgconf fails to produce output due to the `es_*` family of functions from `libgpg-error` that it uses to output fails. A minimal test case is the following C program:

```C
#define GPGRT_ENABLE_ES_MACROS
#include <gpg-error.h>
int main() { es_putc('A', es_stdout); }
```

After installing the `gcc` and `libgpg-error-dev` packages, compiling and running (`gcc t.c -lgpg-error -o t && ./t`) should produce a single 'A', but gives not output. So the problem here seems to be with libgpg-error.

**Comment by fornwall** [comment]
@its-pointless @Neo-Oli There is now an updated version `2.1.11-2` of the `gnupg2` package where `gpgconf` should work. Can you try updating and see if that fixes mutt using gnupg2 or if any problem remains?

**Comment by its-pointless** [comment]
Its still not working correctly but mutt is detecting that gpgconf is available and loading the libraries etc... but as a test 
`gpgconf --list-options gpg`
gives 
`Option gpgconf-gpg.conf, needed by backend GnuPG, was not initialized`
`gpgconf: fatal error (exit status 1)`

**Comment by fornwall** [comment]
@its-pointless Thanks! I've updated gnupg2 yet again, now to version `2.1.11-3`, where `gpgconf --list-options gpg` should work, so try again :).

**Comment by its-pointless** [comment]
tried it again still not working...

**Comment by fornwall** [comment]
@its-pointless @Neo-Oli Ok, so I don't normally use `mutt` or `gpg` myself, so help me out here :)!

Is it correct that mutt can use gpg to sign mails using two different methods?

1. By a "traditional" setup where mutt invokes gnupg(2).
2. By using a built-in gpgme functionality in mutt.

And that (1) works in Termux, but (2) doesn't?

If so, is (1) good enough so that we can just remove the built-in gpgme support (`--enable-gpgme`), which has the additional advantage of reducing the dependencies of mutt (since not everyone mutt user uses the gpgme feature), or does (2) bring any advantages?

**Comment by its-pointless** [comment]
Yeah its okay to remove it. At some stage i will get the debian script setup so people won't have to fumble around to set it up.

**Comment by Neo-Oli** [comment]
Yeah, It's probably okay to remove it. 
(1) takes some 16 lines in .muttrc to setup
```
`set pgp_decode_command="gpg %?p?--passphrase-fd 0? --no-verbose --batch --output - %f"
set pgp_verify_command="gpg --no-verbose --batch --output - --verify %s %f"
set pgp_decrypt_command="gpg --passphrase-fd 0 --no-verbose --batch --output - %f"
set pgp_sign_command="gpg --no-verbose --batch --output - --passphrase-fd 0 --armor --detach-sign --
set pgp_clearsign_command="gpg --no-verbose --batch --output - --passphrase-fd 0 --armor --textmode
set pgp_encrypt_only_command="pgpewrap gpg --batch --quiet --no-verbose --output - --encrypt --textm
set pgp_encrypt_sign_command="pgpewrap gpg --passphrase-fd 0 --batch --quiet --no-verbose --textmode
set pgp_import_command="gpg --no-verbose --import -v %f"
set pgp_export_command="gpg --no-verbose --export --armor %r"
set pgp_verify_key_command="gpg --no-verbose --batch --fingerprint --check-sigs %r"
set pgp_list_pubring_command="gpg --no-verbose --batch --with-colons --list-keys %r"
set pgp_list_secring_command="gpg --no-verbose --batch --with-colons --list-secret-keys %r"
set pgp_autosign=no
set pgp_replyencrypt=yes
set pgp_timeout=1800
set pgp_good_sign="^gpg: Good signature from"
```
while (2) would only take 1 line to setup.
`set crypt_use_gpgme=yes

After either is set up, as far as I can tell, they work identically.

**Comment by fornwall** [comment]
@its-pointless What is the debian script setup?

**Comment by its-pointless** [comment]
Nothing really interesting. But it does make mutt look pretty.

**Comment by fornwall** [comment]
@Neo-Oli Aha! We could setup those lines in an example file just like other distributions do, so that we bring it back down to one line in .muttrc:

    source $PREFIX/share/examples/mutt/gpg.rc

The lines you wrote were cut off - if you paste the full contents I can add it to the package in the above mentioned file!

**Comment by Neo-Oli** [comment]
I have them from [here](https://dev.mutt.org/trac/wiki/MuttGuide/UseGPG). It mentions that there should already be a gpg.rc somewhere, but I couldn't find it in termux. I checked on an ubuntu and what is in there is already very close to what I have in my .muttrc

```
set pgp_decode_command="gpg %?p?--passphrase-fd 0? --no-verbose --batch --output - %f"
set pgp_verify_command="gpg --no-verbose --batch --output - --verify %s %f"
set pgp_decrypt_command="gpg --passphrase-fd 0 --no-verbose --batch --output - %f"
set pgp_sign_command="gpg --no-verbose --batch --output - --passphrase-fd 0 --armor --detach-sign --textmode %?a?-u %a? %f"
set pgp_clearsign_command="gpg --no-verbose --batch --output - --passphrase-fd 0 --armor --textmode --clearsign %?a?-u %a? %f"
set pgp_encrypt_only_command="pgpewrap gpg --batch --quiet --no-verbose --output - --encrypt --textmode --armor --always-trust --encrypt-to $pgp_sign_as -- -r %r -- %f"
set pgp_encrypt_sign_command="pgpewrap gpg --passphrase-fd 0 --batch --quiet --no-verbose --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust --encrypt-to $pgp_sign_as -- -r %r -- %f"
set pgp_import_command="gpg --no-verbose --import -v %f"
set pgp_export_command="gpg --no-verbose --export --armor %r"
set pgp_verify_key_command="gpg --no-verbose --batch --fingerprint --check-sigs %r"
set pgp_list_pubring_command="gpg --no-verbose --batch --with-colons --list-keys %r" 
set pgp_list_secring_command="gpg --no-verbose --batch --with-colons --list-secret-keys %r" 
```

**Comment by fornwall** [comment]
Thanks! I've added it to the mutt package (version `1.6.0.20160416-1`), so 

    source $PREFIX/share/examples/mutt/gpg.rc

should work there!

**Comment by Neo-Oli** [comment]
Thanks, I've tested it and it seems to work like that. Just for future reference:
You need to specify the key before you source the gpg.rc (gpg.rc has references to $pgp_sign_as
```
set pgp_sign_as = 063A4794
source $PREFIX/share/examples/mutt/gpg.rc
```

**Comment by nyetwurk** [comment]
I don't use any of it and I dont want the error. I had to add
`set crypt_use_gpgme=no`
to .muttrc to avoid the  "GPGME: CMS protocol not available" warning

**Comment by Neo-Oli** [comment]
@nyetwurk Do you by any chance have an outdated version of mutt? Can you try to run `apt update && apt upgrade`. 
gpgme support was briefly enabled in mutt (for this issue) but then removed again.

**Comment by nyetwurk** [comment]
@Neo-Oli 
$ apt-cache policy mutt
```
mutt:
  Installed: 1.7.0-6
  Candidate: 1.7.0-6
  Version table:
 *** 1.7.0-6 500
        500 http://http.us.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
$ sudo aptitude update; sudo aptitude install mutt
...
mutt is already installed at the requested version (1.7.0-6)
```

**Comment by fornwall** [comment]
@nyetwurk That is from a debian install and not the Termux package. Are you ssh:ing into another box?

**Comment by nyetwurk** [comment]
@fornwall
Sorry, this is about my own debian box, not about termux... google search pointed me here. Apologies for cluttering this bug report.
