### ISSUE TITLE
Ruby Error - Segmentation Fault on 32-bit arm

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-packages#1520]
After the last update, an error occurred → segmentation faul
https://prnt.sc/glrlec

**Comment by fornwall** [comment]
Looks to be specific to 32-bit arm. I'm make a build with debug symbols and will investigate.

**Comment by fornwall** [comment]
- Building with `-Oz` or `-O2`: Segmentation fault.
- Building with `-O0`: Working.

**Comment by fornwall** [comment]
Thanks for the report!

This problem, which affected 32-bit arm devices, is now fixed in the latest version `2.4.2-1` of the ruby package!

**Comment by Deathlive** [comment]
@fornwall 
Sorry, I updated but the problem it did not disappear.
Ruby does not open and gem = segmentation faul.
![screens](https://user-images.githubusercontent.com/29791715/30518357-da570062-9b8c-11e7-991c-c895b2cb295c.png)

**Comment by fornwall** [comment]
@Deathlive Hm, can you run `apt show ruby` and verify that it says `Version: 2.4.2-1` in the output of that command?

**Comment by Auxilus** [comment]
@fornwall is https://github.com/termux/termux-packages/issues/715#issuecomment-330032364 analogous to this issue?

**Comment by fornwall** [comment]
@Auxilus Probably, if it's 32-bit arm and both ruby and irb segfaults directly. For me `2.4.2-1` fixed that problem.

**Comment by rpil2** [comment]
I see the same - ruby 2.4.2-1 now works again. Gem segfaults as above

**Comment by fornwall** [comment]
@rpil2 Ah thanks - so version ´2.4.2-1` fixed the `ruby` and `irb` commands, but `gem` still segfaults.

**Comment by Auxilus** [comment]
@fornwall problem still persists https://github.com/termux/termux-packages/issues/715

**Comment by Deathlive** [comment]
Yes, probably a problem in gem.
![1](https://user-images.githubusercontent.com/29791715/30520217-53fc1060-9bba-11e7-8339-3484704b1f1e.png)

**Comment by benjaminoakes** [comment]
I'm having this same problem.  Is there a reasonable way to downgrade to Ruby 2.3 in the meantime?

**Comment by benjaminoakes** [comment]
In case it helps, this seems to happen on Rubygems 2.5.2 and 2.6.12 as well

**Comment by fornwall** [comment]
Update yet again with `pkg up` - this should install version `2.4.2-2` on 32-bit arm which hopefully fixes the issue.

Reports if the new version is working or not are very welcome!

**Comment by benjaminoakes** [comment]
@fornwall Thanks for the quick update!  I updated and it no longer segfaults.

**Comment by sdrausty** [comment]
Ruby gem is beautiful on aarch64 Android OS at present. However, when we glance at Gem::Ext::BuildError: ERROR: Failed to build gem native extension. #969 and sift through https://github.com/termux/termux-packages/issues?utf8=✓&q=ruby%20gem there might be a common denominator which appears to be system access to library and header files. Can https://github.com/termux/termux-exec assist in this role too?
> when installed allows #!/bin/sh, #!/usr/bin/env and likewise to work! after installation it won't affect the current session, but every future session should work without any setup
![screenshot_20170917-175730](https://user-images.githubusercontent.com/27742457/30525316-0afddd40-9bd2-11e7-9bc0-cb7b3293cdf3.png)

@fornwall awesome work! Congratulations ☺

**Comment by ivam3** [comment]
Ruby v 2.6.1 show Segmentation fault error once again, can u help with it please

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/3380
