### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by stainslav** [termux/termux-packages#1521]
How to install Java 9 or 8 in termux aarch64 no root?
@fronwall

**Comment by fornwall** [comment]
See https://github.com/termux/termux-packages/issues/45

**Comment by sdrausty** [comment]
@stainslav java is available through
https://sdrausty.github.io/TermuxArch/
https://duckduckgo.com/?q=arch+linux+install+java+pacman&atb=v90-2__&t=cros&ia=q
Then run # pacman -Syy; # pacman -Su; # pacman -S jdk8-openjdk

**Comment by SeAL80s** [comment]
@sdrausty too slow ! emacs need 120+s to start !

**Comment by sdrausty** [comment]
@SeAL80s timings? Sec?
>oo slow ! emacs need 120+s to start !

Can u present timing with source?

**Comment by SeAL80s** [comment]
@sdrausty First of All ,Thanks for your great work ! 

Hardware :Cortex A53 ,8 Core , 2Ghz ,3G RAM 
System:Android 7.0
Spacemacs start in pure termux takes up 9s, in TermuxArch 45.116s .

**Comment by bobby-kun** [comment]
Has anyone tried having compiling java on android and successfully running java8~? Need some help to run java on android
