### ISSUE TITLE
[Bug]: Can't install openjdk-19

### ISSUE THREAD

**Issue by RIC217** [termux/termux-packages#15212]
### Problem description

Error while installing openjdk-19 in Termux from https://github.com/termux/termux-packages/actions/runs/4163778931 :
![image](https://user-images.githubusercontent.com/68387948/219124083-f5f6d3bf-be0c-4c8f-8636-a0eb614a45d0.png)

### What steps will reproduce the bug?

Download openjdk-19 for aarch64 from https://github.com/termux/termux-packages/actions/runs/4163778931 and extract it. Finally do `dpkg -i openjdk-19*` in the extracted folder

### What is the expected behavior?

OpenJDK should install properly.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
webkit2gtk-4.1/x11 2.38.5 aarch64 [upgradable from: 2.38.4]
termux-tools version:
1.37.0
Android version:
11
Kernel build information:
Linux localhost 4.14.190-perf-gceaf914a4ae1-dirty #2 SMP PREEMPT Wed Feb 16 22:34:35 WIB 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by RIC217** [comment]
> 

Okay thanks I'll try :)

**Comment by RIC217** [comment]
@agnostic-apollo When I execute postinst, I get this error : ```
./postinst: 6: Syntax error: word unexpected (expecting "do")
```

**Comment by Grimler91** [comment]
Next build from https://github.com/termux/termux-packages/pull/15108 should™ have working postinst scripts, if you want to try it before you have to remove the script, for example following instructions in https://stackoverflow.com/a/47852901 (but without sudo)

This will also cause binaries to not be in PATH, so you would have to add `$PREFIX/lib/jvm/openjdk-19-java/bin` to PATH to find `java` and friends.

**Comment by RIC217** [comment]
Ok thanks I'll try that right now !

**Comment by RIC217** [comment]
It worked !

**Comment by Grimler91** [comment]
Great, please let us know if there are any issues with openjdk-19!

**Comment by AlirezaParsi** [comment]
i want openjdk19 too how i get it? if you have any link of that deb file please give me
