### ISSUE TITLE
[Bug]: ERROR 1698 (28000): Acess denied for user 'root'@'localhos' 

### ISSUE THREAD

**Issue by kingandrenz** [termux/termux-packages#15236]
### Problem description

am unable to create tables and carry task, in fact I am unable to use this package, this issue occurred when I tried setting password , I was denied access totally.

### What steps will reproduce the bug?

access denied to database 'mysql'

### System information

termux-info:

```
$ mysql -u root
ERROR 1698 (28000): Access denied for user 'root'@'localhost' to database 'mysql'

```

**Comment by xtkoba** [comment]
Perhaps related to #14004.

Please share your `termux-info` output anyways.

**Comment by kingandrenz** [comment]
I was able to solve the issue by uninstalling it and removed all files that was created when it was installed and reinstalled it again
