### ISSUE TITLE
[Bug]: What's happening???

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#15238]
### Problem description

It's hard to explain, you have to see it.

https://github.com/termux/termux-packages/actions/runs/4197619577/jobs/7280174849
https://github.com/termux-pacman/termux-packages/actions/runs/4197555977/jobs/7280073987
https://github.com/termux-pacman/tur/actions/runs/4197489595/jobs/7280030155

### What steps will reproduce the bug?

commits

### System information

GitHub actions

**Comment by Maxython** [comment]
There are suspicions that this is due to this commit (https://github.com/termux/termux-packages/commit/a09a471d4a8e249a6a034606df759373eeeb14f0).

**Comment by xtkoba** [comment]
Then 878774b13627f51a24f09107245e536143b08309 should be to blame, rather than the commit referenced in the previous comment. This commit has `python-xcbgen` depend on `python` in an awkward manner. I wouldn't be surprised if it resulted in cyclic dependencies in some situations.

**Comment by xtkoba** [comment]
Closing as fixed by commit 5bec5a66fff06e762c0879e6019396a9363bf7d3.

**Comment by Maxython** [comment]
Do I need to adjust buildorder.py so that the loop does not appear?

**Comment by xtkoba** [comment]
IMO it is not necessary. Just that `TERMUX_PKG_ANTI_BUILD_DEPENDS` should not be abused.
