### ISSUE TITLE
Some irrelevant patches are applied to packages.

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#15247]
xwayland: [1](https://github.com/termux/termux-packages/blob/master/x11-packages/xwayland/xorg-server-1.20.1_os_osinit.c.patch), [2](https://github.com/termux/termux-packages/blob/master/x11-packages/xwayland/xorg-server-1.20.1_os_connection.c.patch) (relevant to darwin).
xorg-server-xvfb: [1](https://github.com/termux/termux-packages/blob/master/x11-packages/xorg-server-xvfb/xorg-server-1.20.1_hw_xfree86_common_xf86Config.c.patch), [2](https://github.com/termux/termux-packages/blob/master/x11-packages/xorg-server-xvfb/xorg-server-1.20.1_hw_xfree86_os-support_linux_lnx_acpi.c.patch), [3](https://github.com/termux/termux-packages/blob/master/x11-packages/xorg-server-xvfb/xorg-server-1.20.1_hw_xfree86_os-support_linux_lnx_kmod.c.patch), [4](https://github.com/termux/termux-packages/blob/master/x11-packages/xorg-server-xvfb/xorg-server-1.20.1_hw_xfree86_parser_scan.c.patch), [5](https://github.com/termux/termux-packages/blob/master/x11-packages/xorg-server-xvfb/xorg-server-1.20.1_hw_xfree86_parser_write.c.patch), [6](https://github.com/termux/termux-packages/blob/master/x11-packages/xorg-server-xvfb/xorg-server-1.20.1_hw_xfree86_xorg-wrapper.c.patch), [7](https://github.com/termux/termux-packages/blob/master/x11-packages/xorg-server-xvfb/xorg-server-1.20.1_hw_xquartz_mach-startup_bundle-main.c.patch), [8](https://github.com/termux/termux-packages/blob/master/x11-packages/xorg-server-xvfb/xorg-server-1.20.1_hw_xwin_InitOutput.c.patch) (irrelevant to xvfb), [9](https://github.com/termux/termux-packages/blob/master/x11-packages/xorg-server-xvfb/xorg-server-1.20.1_os_osinit.c.patch) (relevant to darwin).

xorg-server: [1](https://github.com/termux/termux-packages/blob/master/x11-packages/xorg-server/xorg-server-1.20.1_os_osinit.c.patch) (relevant to darwin).

**Comment by xtkoba** [comment]
Maybe a result of substitution in bulk? No problem if they are not harmful.
