### ISSUE TITLE
[Bug]: Xdummy does not work

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#15240]
### Problem description

Xdummy does not work. It looks like it is not patched to work in termux. Also it looks like `xf86-video-dummy` is not present in x11-repo.
```
$ Xdummy
mkdir: cannot create directory ‘/tmp’: Read-only file system
chmod: cannot access '/tmp/Xdummy.u0_a257/17938': No such file or directory
touch: cannot touch '/tmp/Xdummy.u0_a257/17938/test.file': No such file or directory
warning: setting tmpdir to /tmp/Xdummy.17938.u0_a257 ...
mkdir: cannot create directory ‘/tmp’: Read-only file system
```

### What steps will reproduce the bug?

```
pkg in x11vnc
Xdummy
```

### What is the expected behavior?

Xdummy should start new X server...

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
12
Kernel build information:
Linux localhost 4.19.188-25223464-abA042FXXU1AVJ4 #1 SMP PREEMPT Thu Oct 20 15:35:01 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A042F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by 2096779623** [comment]
I can reproduce this bug.

**Comment by xtkoba** [comment]
Looks like just a matter of hard-coded paths.

I don't know how `xf86-video-dummy` is related to this issue.

**Comment by twaik** [comment]
Of cource it is related. Xdummy [starts](https://github.com/LibVNC/x11vnc/blob/f07df92816ef10b7382a542125955df7f4156a5c/misc/Xdummy.in#L945)  Xorg with dummy driver.

**Comment by xtkoba** [comment]
Oh, then should we remove `Xdummy` from the package?

**Comment by twaik** [comment]
I was hoping we will fix Xdummy 😄 . I am planning to get rid of wayland dependency in `termux-x11` and make it simple X11 client, but it will require some other X server with output to offscreen. Xvfb is slow (even on PC tested with x11vnc) so I was hoping Xdummy will do the work.

**Comment by twaik** [comment]
Does it mean we will not fix Xdummy?

**Comment by twaik** [comment]
@xtkoba ?

**Comment by xtkoba** [comment]
If `Xdummy` did not work in the first place, then this is not a regression. Just that a component should be removed that does not work. Just like some programs in `coreutils` package.

**Comment by xtkoba** [comment]
Of course a PR is welcome that adds `xf86-video-dummy`, and possibly enables `Xdummy` to work. Thanks.

**Comment by twaik** [comment]
Actually dummy was disabled from `x11-packages` a long time ago, I do not know why... https://github.com/termux/x11-packages/tree/master/disabled-packages/xf86-video-dummy .
