### ISSUE TITLE
[Package]: Subpackage eglinfo

### ISSUE THREAD

**Issue by truboxl** [termux/termux-packages#15275]
### Why do you want to add this package to Termux?

`eglinfo` from mesa-demos can be used independently without installing mesa. It only depends on `libEGL.so` and `libc.so` which should be present on all Android 7+ devices.

So we should subpackage eglinfo and decouple from mesa as a dependency.

### Source code URL

https://gitlab.freedesktop.org/mesa/demos

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Example `eglinfo` output of loading Android `libEGL.so`:
```
EGL client extensions string:
    EGL_EXT_client_extensions EGL_KHR_platform_android
    EGL_ANGLE_platform_angle EGL_ANDROID_GLES_layers

Default display:
EGL API version: 1.4
EGL vendor string: Android
EGL version string: 1.4 Android META-EGL
EGL client APIs: OpenGL_ES
EGL extensions string:
    EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time
    EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer
    EGL_ANDROID_front_buffer_auto_refresh
    EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata
    EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base
    EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace
    EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync
    EGL_KHR_create_context EGL_KHR_config_attribs
    EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness
    EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync
    EGL_ANDROID_recordable EGL_KHR_partial_update
    EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer
    EGL_IMG_context_priority EGL_KHR_no_config_context
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces
---------------------------------------------------------------------
0x1f 32  0  8  8  8  8  0  0  0 0 0x01TC      a     y  y     win,pb
0x20 32  0  8  8  8  8  0  0  0 0 0x01TC      a     y  y     win
0x01 32  0  8  8  8  8  0  0  0 0 0x01TC      a     y  y     win,pb
0x02 32  0  8  8  8  8 24  0  0 0 0x01TC      a     y  y     win,pb
0x03 32  0  8  8  8  8 24  8  0 0 0x01TC      a     y  y     win,pb
0x04 32  0  8  8  8  8 24  8  4 1 0x01TC      a     y  y     win,pb
0x05 16  0  5  6  5  0  0  0  0 0 0x04TC      y     y  y     win,pb
0x06 16  0  5  6  5  0 24  0  0 0 0x04TC      y     y  y     win,pb
0x07 16  0  5  6  5  0 24  8  0 0 0x04TC      y     y  y     win,pb
0x08 16  0  5  6  5  0 24  8  4 1 0x04TC      y     y  y     win,pb
0x09 24  0  8  8  8  0  0  0  0 0 0x02TC      y     y  y     win,pb
0x0a 24  0  8  8  8  0 24  8  0 0 0x02TC      y     y  y     win,pb
0x0b 24  0  8  8  8  0  0  0  4 1 0x02TC      y     y  y     win,pb
0x0c 24  0  8  8  8  0 24  8  4 1 0x02TC      y     y  y     win,pb
0x0d 16  0  5  5  5  1 24  8  0 0 0x00TC      a     y  y     pb
0x0e 16  0  5  5  5  1 24  8  4 1 0x00TC      a     y  y     pb
0x0f 16  0  4  4  4  4 24  8  0 0 0x00TC      a     y  y     pb
0x10 16  0  4  4  4  4 24  8  4 1 0x00TC      a     y  y     pb
0x11 32  0  8  8  8  8 24  8  8 1 0x01TC      a     y  y     win,pb
0x12 16  0  5  6  5  0 24  8  8 1 0x04TC      y     y  y     win,pb
0x13 24  0  8  8  8  0 24  8  8 1 0x02TC      y     y  y     win,pb
0x14 32  0  8  8  8  8 24  8 16 1 0x01TC      a     y  y     win,pb
0x15 16  0  5  6  5  0 24  8 16 1 0x04TC      y     y  y     win,pb
0x16 24  0  8  8  8  0 24  8 16 1 0x02TC      y     y  y     win,pb
0x19 32  0 10 10 10  2 24  8  0 0 0x2bTC      a     y  y     win,pb
```

**Comment by licy183** [comment]
Emmm... `libEGL.so` from `/system/lib64` isn't packaged, and IMO it should not be packaged because it cannot work for x11... So is it necessary to split `eglinfo` from `mesa-demos`?

**Comment by xtkoba** [comment]
I'm not in favor of separation of GL and EGL, as written before somewhere. IMO they should be handled as `opengl` in bulk in terms of dependency, because too fine-grained dependency is unmaintainable. As for independence from `mesa`, the `opengl` metapackage is provided for such purposes. Currently `opengl` depends on `mesa` because IIUC OpenGL does not work without it. When in future any other provider is added, then `opengl` can depend on `mesa` or (`|`) that package.

**Comment by xtkoba** [comment]
Another reason why `eglinfo` is difficult to be independent of `opengl` is because it has `DT_RUNPATH` set to `$PREFIX/lib`. When `libglvnd` is installed, then `eglinfo` references `libEGL.so` coming from that package, instead of the system one, regardless of the dependency specified in the metadata of the package.

There is even a plan to change the SONAME of `libEGL.so` to `libEGL.so.1`, to avoid future SONAME conflict. When this change is applied, then `eglinfo` cannot refer to the system `libEGL.so` at all.

**Comment by truboxl** [comment]
`vulkaninfo` now also added dependency on X11, and it doesn't stop linking with system `libvulkan.so` but can also link with our own `libvulkan.so`.

`eglinfo` from `mesa-demos` is the well maintained version of `eglinfo` and I dont see there's any other alternatives.

I really don't think EGL should be treated under `opengl`. And having `opengl` depends on `mesa` instead of `libglvnd` makes no sense.

**Comment by xtkoba** [comment]
Then please make `libglvnd` function without `mesa`, which is not the case as of now:

```
$ glxgears
Error: couldn't get an RGB, Double-buffered visual
```

**Comment by xtkoba** [comment]
It is possible that we package "`eglinfo` for system" under another name, say `eglinfo-system`, by `patchelf`ing the existing `eglinfo` executable, just like `php-apache-*` subpackages of `php`. Does that satisfy your needs?
