### ISSUE TITLE
ssh hangs forever when a command is specified

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#1529]
This concerns the SSH Server of Termux. The problem occurs both the ssh client of termux and debian
If I run `ssh localhost -p 8022 ls` It just hangs forever instead of running `ls`
Running `ssh localhost -p 8022 -t tmux` gives me a normal login shell instead of launching `tmux`

This has only started happening today, as I previously used commands like many times a day.

**Comment by fornwall** [comment]
Thanks! Can you updated and verify that `termux-tools` at version `0.46` fixes the problem?

**Comment by io7m** [comment]
I just ran into this problem today, and `0.46` does fix it for me here.

**Comment by Neo-Oli** [comment]
Yes the update does fix this for me as well.  Thanks
