### ISSUE TITLE
[Bug]: Cant install mariadb

### ISSUE THREAD

**Issue by Hurleyy456** [termux/termux-packages#15301]
### Problem description

I can't install mariadb on termux. I'm new to this, we just need it for our school. I always get this error.
`$ pkg install mariadb
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: bad
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Get:1 https://termux.mentality.rip/termux-packages-24 stable InRelease [14.0 kB]
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 Packages [488 kB]
Err:5 https://dl.bintray.com/grimler/game-packages-24 games Release
  404  Not Found
Err:6 https://dl.bintray.com/grimler/science-packages-24 science Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$ pkg install mariadb
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libedit liblz4 pcre2
The following NEW packages will be installed:
  libedit liblz4 mariadb pcre2
0 upgraded, 4 newly installed, 0 to remove and 53 not upgraded.
Need to get 13.5 MB of archives.
After this operation, 196 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libedit aarch64 20221030-3.1-0 [77.7 kB]
Get:2 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 liblz4 aarch64 1.9.4 [85.5 kB]
Get:3 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 pcre2 aarch64 10.42 [856 kB]
Get:4 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 mariadb aarch64 2:10.10.3 [12.5 MB]
Fetched 13.5 MB in 4s (3082 kB/s)
Selecting previously unselected package libedit.
(Reading database ... 3457 files and directories currently installed.)
Preparing to unpack .../libedit_20221030-3.1-0_aarch64.deb ...
Unpacking libedit (20221030-3.1-0) ...
Selecting previously unselected package liblz4.
Preparing to unpack .../liblz4_1.9.4_aarch64.deb ...
Unpacking liblz4 (1.9.4) ...
Selecting previously unselected package pcre2.
Preparing to unpack .../pcre2_10.42_aarch64.deb ...
Unpacking pcre2 (10.42) ...
Selecting previously unselected package mariadb.
Preparing to unpack .../mariadb_2%3a10.10.3_aarch64.deb ...
Unpacking mariadb (2:10.10.3) ...
Setting up libedit (20221030-3.1-0) ...
Setting up liblz4 (1.9.4) ...
Setting up pcre2 (10.42) ...
Setting up mariadb (2:10.10.3) ...
Initializing mysql data directory...
Installing MariaDB/MySQL system tables in '/data/data/com.termux/files/usr/var/lib/mysql' ...
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/mariadbd": library "libssl.so.3" not found: needed by main executable

Installation of system tables failed!  Examine the logs in
/data/data/com.termux/files/usr/var/lib/mysql for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /data/data/com.termux/files/usr/bin/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mariadbd daemon with:

    shell> /data/data/com.termux/files/usr/bin/mariadbd --skip-grant-tables --general-log &

and use the command line tool /data/data/com.termux/files/usr/bin/mariadb
to connect to the mysql database and look at the grant tables:

    shell> /data/data/com.termux/files/usr/bin/mariadb -u root mysql
    MariaDB> show tables;

Try '/data/data/com.termux/files/usr/bin/mariadbd --help' if you have problems with paths.  Using
--general-log gives you a log in /data/data/com.termux/files/usr/var/lib/mysql that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss

Please check all of the above before submitting a bug report
at https://mariadb.org/jira

$`

### What steps will reproduce the bug?

pkg install mariadb

### What is the expected behavior?

Success

### System information

termux-info:

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.186-01012-g1d2564ba3eeb-dirty #1 SMP PREEMPT Tue Jan 10 19:31:39 CST 2023 aarch64 Android
Device manufacturer:
INFINIX MOBILITY LIMITED
Device model:
Infinix X695
```

**Comment by xtkoba** [comment]
Do `pkg up` first.

**Comment by xtkoba** [comment]
Also I suspect you downloaded the Termux app from Google Play. It is not supported.
