### ISSUE TITLE
[Package]: wego

### ISSUE THREAD

**Issue by jere6a** [termux/termux-packages#15304]
### Why do you want to add this package to Termux?

wego is a weather app for the terminal.

### Source code URL

https://github.com/schachmat/wego

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
Why not use `curl https://wttr.in/` ?

**Comment by jere6a** [comment]
wttr.in is a good option when you are always in the same place. But not when you make a lot of trips you need to change some parameters to know how the weather will be at the destination.

**Comment by Grimler91** [comment]
It's pretty easy to change location with wittr as well:

```
curl wttr.in/Stockholm
curl wittr.in/Sydney
```

I don't mind having wego as a package though

**Comment by jere6a** [comment]
Good. So I think I'll make a shell script and name it wego.
