### ISSUE TITLE
[Package]: tdash

### ISSUE THREAD

**Issue by tuimania** [termux/termux-packages#15317]
### Why do you want to add this package to Termux?

A terminal dashboard with stats from Google Analytics, GitHub, Travis CI, and Jenkins. Very much built specific to me.
 

### Source code URL

https://github.com/jessfraz/tdash

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
> Packages must be active, well-known projects

Software available in major Linux distributions has more chances to be included into Termux repositories. We will not accept outdated, dead projects as well as projects which do not have active community.

It looks like it's in an unmaintained state, last updated in 2020
