### ISSUE TITLE
[Bug]: Bash-completion for PicoLisp

### ISSUE THREAD

**Issue by gerdolf** [termux/termux-packages#15331]
### Problem description

It would be nice to have Bash-completion for PicoLisp. For that, it is just necessary to add this line to the installation process:

sed "s/\/usr/\${PREFIX}/" $PREFIX/lib/picolisp/lib/bash_completion > $PREFIX/share/bash-completion/completions/pil

### What steps will reproduce the bug?

Pressing TAB in bash

### What is the expected behavior?

Expand TABs context-sensitively

### System information

termux-info:

```

```

**Comment by gerdolf** [comment]
Hi Uchiha-San,

> Closed #15331 as completed via #15352.

Thanks for taking care of the issue!

However, the fix is not correct, and does not work.

It creates a new *directory* named pil in share/bash-completion/completions,
containing a file bash_completion.

Correct would be a *file* named pil.

Cheers

☺/ A!ex
-- 
Sent from my Penti

   Alexander Burger
   Software Lab. / 7fach GmbH
   Bahnhofstr. 24a, D-86462 Langweid
   ***@***.***
   +49 179 6731887
   @abu:7fach.de

**Comment by licy183** [comment]
> Hi Uchiha-San,
> Closed #15331 as completed via #15352.
> Thanks for taking care of the issue! However, the fix is not correct, and does not work. It creates a new *directory* named pil in share/bash-completion/completions, containing a file bash_completion. Correct would be a *file* named pil. Cheers ☺/ A!ex -- Sent from my Penti Alexander Burger Software Lab. / 7fach GmbH Bahnhofstr. 24a, D-86462 Langweid ***@***.*** +49 179 6731887 @ABU:7fach.de

Thanks for your report! Should be fixed by https://github.com/termux/termux-packages/commit/491a2e72c52c565fbbda3185f0e6b2de2a637937.

**Comment by gerdolf** [comment]
On Sat, Feb 25, 2023 at 10:54:41PM -0800, Uchiha Kakashi wrote:
> Thanks for your report! Should be fixed by https://github.com/termux/termux-packages/commit/491a2e72c52c565fbbda3185f0e6b2de2a637937.

Yes. Very good, works perfectly! :)

Thank you very much!

☺/ A!ex
-- 
Sent from my Penti

   Alexander Burger
   Software Lab. / 7fach GmbH
   Bahnhofstr. 24a, D-86462 Langweid
   ***@***.***
   +49 179 6731887
   @abu:7fach.de
