### ISSUE TITLE
[Package]: cia-unix

### ISSUE THREAD

**Issue by X-ronin** [termux/termux-packages#15344]
### Why do you want to add this package to Termux?

Decrypt CIA/3DS roms in UNIX environments 

### Source code URL

https://github.com/shijimasoft/cia-unix

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
I do not allow this to be packaged in our official repo.
