### ISSUE TITLE
0% [working]: 

### ISSUE THREAD

**Issue by symbian1symbian1off** [termux/termux-packages#15357]
### Problem description

whenever I want to update my package or upgrade, trmux just show me **0% [Working]** i search about it and found some answer  ` termux-change-repo` make termux use another repository for the package but again I saw this error **0% [Working]** I tried every repository but none of them makes any different for me and for example, with grimler repository, I saw this

> Grimler's mirrors selected
>     Changing main repository                                   Changing game repository
>     Changing science repository
> [*] Running apt update
> CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found: >needed by /data/data/com.termux/files/usr/lib/libcurl.so in namespace (default)
> CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found: >needed by /data/data/com.termux/files/usr/lib/libcurl.so in namespace (default)
> 0% [Working]

but I search for it more and found some new answers this is a solution for the update package it doesn't work because. SSL is broken. so

you must download openssl debs "manually" through curl or browser from
 [https://packages.termux.dev/apt/termux-main/pool/main/a/apt/](https://www.stackoverflow.com/) and [https://packages.termux.dev/apt/termux-main/pool/main/o/openssl/](https://www.stackoverflow.com/), 
and install with `dpkg -i /path/to/downloaded/debs` **but ** you see this new error `dpkg`: error: cannot access archive '/path/to/downloaded/debs': No such file or directory and...

a friend do me a favour and help me in this way so I want to share my experience I start from the last command that we try `dpkg -i /path/to/downloaded/debs` adapt on friend's guide "**Well, the error message says it all. Replace /path/to/downloaded/debs with the paths to the debs you downloaded.**" so I do that. I change my path to /storage/emulated/0/Download/apt_2.5.6_arm.deb and here is the command `dpkg -i /storage/emulated/0/Download/apt_2.5.6_arm.deb` and I saw

> dpkg-split: error: failed to read archive '/storage/emulated/0/Download/apt_2.5.6_arm.deb': Permission denied dpkg: error >processing archive /storage/emulated/0/Download/apt_2.5.6_arm.deb (--install): subprocess dpkg-split returned error exit >status 2 Errors were encountered while processing: /storage/emulated/0/Download/apt_2.5.6_arm.deb

at first, I think my phone must be at root but after help from my friend I get the reason "Run `termux-setup-storage` to give termux access to shared storage." I must run `termux-setup-storage` so it makes this command work (`dpkg -i /storage/emulated/0/Download/apt_2.5.6_arm.deb`) also the problem is an error sayed me to use another file from the repository error sayed the file must be aarc64 no arm so I do it `dpkg -i /storage/emulated/0/Download/apt_2.5.6_aarch64.deb` and the new error is:))))

### What steps will reproduce the bug?

I think after installing openssl package may you faced the problem 

### What is the expected behavior?

I love Linux. especially in my phone "termux" and I'm happy to solve my problem and the others to improve using this app :)

### System information

termux-info:

```
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-packages-24 stable main
# game-repo (sources.list.d/game.list)
deb https://termux.mentality.rip/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://termux.mentality.rip/science-packages-24 science stable
Updatable packages:
apt/stable 2.5.6 aarch64 [upgradable from: 1.4.10-6]
bash/stable 5.2.15 aarch64 [upgradable from: 5.0.18-2]
ca-certificates/stable 1:2023.01.10 all [upgradable from: 20200722]
command-not-found/stable 2.1.0-11 aarch64 [upgradable from: 1.57]
coreutils/stable 9.1-2 aarch64 [upgradable from: 8.32-4]
curl/stable 7.88.1 aarch64 [upgradable from: 7.72.0]
dash/stable 0.5.12 aarch64 [upgradable from: 0.5.11.2-2]
debianutils/stable 5.7 aarch64 [upgradable from: 4.11.1]
dialog/stable 1.3-20230209-0 aarch64 [upgradable from: 1.3-20200327-0]
diffutils/stable 3.9 aarch64 [upgradable from: 3.7-3]
dos2unix/stable 7.4.4 aarch64 [upgradable from: 7.4.1-1]
dpkg/stable 1.21.20 aarch64 [upgradable from: 1.20.5-2]
ed/stable 1.19 aarch64 [upgradable from: 1.16-1]
findutils/stable 4.9.0-2 aarch64 [upgradable from: 4.7.0-2]
gawk/stable 5.2.1 aarch64 [upgradable from: 5.1.0-1]
gpgv/stable 2.4.0-2 aarch64 [upgradable from: 2.2.23]
grep/stable 3.8-1 aarch64 [upgradable from: 3.4-1]
gzip/stable 1.12-1 aarch64 [upgradable from: 1.10-4]
inetutils/stable 2.4 aarch64 [upgradable from: 1.9.4-10]
less/stable 608-1 aarch64 [upgradable from: 551-1]
libandroid-support/stable 28-3 aarch64 [upgradable from: 28]
libc++/stable 25c aarch64 [upgradable from: 21d-1]
libcrypt/stable 0.2-5 aarch64 [upgradable from: 0.2-3]
libcurl/stable 7.88.1 aarch64 [upgradable from: 7.72.0]
libgcrypt/stable 1.10.1-1 aarch64 [upgradable from: 1.8.6]
libgmp/stable 6.2.1-2 aarch64 [upgradable from: 6.2.0-1]
libgpg-error/stable 1.46 aarch64 [upgradable from: 1.39]
libiconv/stable 1.17 aarch64 [upgradable from: 1.16-3]
liblzma/stable 5.4.1 aarch64 [upgradable from: 5.2.5-1]
libmpfr/stable 4.2.0 aarch64 [upgradable from: 4.1.0]
libnghttp2/stable 1.52.0 aarch64 [upgradable from: 1.41.0-1]
libssh2/stable 1.10.0-2 aarch64 [upgradable from: 1.9.0-2]
libtirpc/stable 1.3.3 aarch64 [upgradable from: 1.2.6-1]
lsof/stable 4.98.0 aarch64 [upgradable from: 4.93.2]
nano/stable 7.2 aarch64 [upgradable from: 5.2]
ncurses/stable 6.4-1 aarch64 [upgradable from: 6.2.20200725]
net-tools/stable 2.10.0 aarch64 [upgradable from: 1.60.2017.02.21-3]
openssl/stable 1:3.0.8 aarch64 [upgradable from: 1.1.1h]
pcre/stable 8.45-1 aarch64 [upgradable from: 8.44-1]
procps/stable 3.3.17-2 aarch64 [upgradable from: 3.3.16-2]
psmisc/stable 23.6-1 aarch64 [upgradable from: 23.3-2]
readline/stable 8.2.1 aarch64 [upgradable from: 8.0.4-1]
sed/stable 4.9 aarch64 [upgradable from: 4.8-1]
tar/stable 1.34-1 aarch64 [upgradable from: 1.32-6]
termux-am/stable 0.4 all [upgradable from: 0.3]
termux-exec/stable 1:1.0 aarch64 [upgradable from: 0.5]
termux-keyring/stable 3.11 all [upgradable from: 1.4]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-1]
termux-tools/stable 1.37.0 all [upgradable from: 0.94]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-7]
util-linux/stable 2.38.1-1 aarch64 [upgradable from: 2.36]
xz-utils/stable 5.4.1 aarch64 [upgradable from: 5.2.5-1]
zlib/stable 1.2.13 aarch64 [upgradable from: 1.2.11-5]
Android version:
11
Kernel build information:
Linux localhost 4.19.152-perf+ #1 SMP PREEMPT Tue Feb 7 13:57:48 CST 2023 aarch64 Android
Device manufacturer:
OnePlus
Device model:
BE2013

```

**Comment by 2096779623** [comment]
Where did you download termux from?

**Comment by symbian1symbian1off** [comment]
from google store

**Comment by symbian1symbian1off** [comment]
> Where did you download termux from?

from google store

**Comment by 2096779623** [comment]
Download termux from f-droid or github, google play store has been deprecated.

https://github.com/termux/termux-app#installation

Clear termux app data then install termux on f-droid or github.

**Comment by symbian1symbian1off** [comment]
> Download termux from f-droid or github, google play store has been deprecated.
> 
> https://github.com/termux/termux-app#installation
> 
> Clear termux app data and remove old termux app, then install new termux on [github](https://github.com/termux/termux-app/releases) or [f-droid](https://f-droid.org/en/packages/com.termux/).

TNX

**Comment by symbian1symbian1off** [comment]
> I would say more:
> 
> 1. Install app from F-Droid or GitHub
> 2. **On the first run, before doing anything else, execute this: `yes | pkg upgrade`.**
> 
> Partial upgrades not supported. If user will upgrade a single package, especially dependency like through command `pkg install -y openssl` without upgrading everything else, the environment will become broken. Termux is rolling release distribution.



> I would say more:
> 
> 1. Install app from F-Droid or GitHub
> 2. **On the first run, before doing anything else, execute this: `yes | pkg upgrade`.**
> 
> Partial upgrades not supported. If user will upgrade a single package, especially dependency like through command `pkg install -y openssl` without upgrading everything else, the environment will become broken. Termux is rolling release distribution.

thank you
