### ISSUE TITLE
MultiViewer for F1

### ISSUE THREAD

**Issue by RichardBurghout** [termux/termux-packages#15366]
### Why do you want to add this package to Termux?

Hi, I'm new to GitHub and also new to Termux so I hope I'm doing this right.

I have a chromecast with google TV, with the Termux app installed. I would like to try to install "MultiViewer for F1". Multiviewer for F1 has a Linux version. But if I understand correctly, a normal .deb package can't be installed in Termux, those packages have to be modified first before it can be installed in Termux.

So my request is: Could someone create a Multiviewer for F1 package that can be installed in Termux?

### Source code URL

https://multiviewer.app/download

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Seems to be a closed source software, so we cannot package this or make it work in termux (could work under qemu and in a chroot, but we can't package it for termux)
