### ISSUE TITLE
Package request: tty-solitaire

### ISSUE THREAD

**Issue by shfrs** [termux/termux-packages#1536]
Ncurses based solitaire game,
https://github.com/mpereira/tty-solitaire/blob/master/README.md

**Comment by Auxilus** [comment]
@shfrs https://github.com/termux/termux-packages/pull/1559

**Comment by fornwall** [comment]
There is now a tty-solitaire package available - install with `pkg install tty-solitaire`!

**Comment by sdrausty** [comment]
After installing:
```
$ dpkg -S tty-solitaire
dpkg-query: no path found matching pattern *tty-solitaire*
```
Android 7.1.1 arm

**Comment by remo7777** [comment]
hmmm.. not working on  android 7.0 aarch64

**Comment by Auxilus** [comment]
Well.. Works on my device (6.0.2 aarch64)

**Comment by remo7777** [comment]
ok i ll try on aarch 64 (andro .6.0 **)👍👍

**Comment by remo7777** [comment]
😭😭😭😭 not working..

**Comment by sdrausty** [comment]
@Auxilus can you please send us a screenshot of tty-solitaire from your Android 6.0.2 aarch64 smartphone?

**Comment by fornwall** [comment]
@sdrausty Note that the binary name is `ttysolitaire`, while the name of the project is `tty-solitaire`.

@remo7777 Could you clarify what "not working" means (what do you see when you run the problem)?

**Comment by sdrausty** [comment]
@fornwall thanks for the clarification:
```
$ dpkg -L tty-solitaire
/.
/data
/data/data
/data/data/com.termux
/data/data/com.termux/files
/data/data/com.termux/files/usr
/data/data/com.termux/files/usr/bin
/data/data/com.termux/files/usr/bin/ttysolitaire
$ dpkg -S tty-solitaire
dpkg-query: no path found matching pattern *tty-solitaire*
$ dpkg -S ttysolitaire
tty-solitaire: /data/data/com.termux/files/usr/bin/ttysolitaire
$
```
I still cannot tell the suites apart from each other though. Please see attached screenshot. 

![screenshot_20170924-182831](https://user-images.githubusercontent.com/27742457/30787451-a5cc8f7c-a156-11e7-9a3c-fc8219835501.png)

**Comment by remo7777** [comment]
Message like.. 
Please increase your terminal size to at least 57x
28 or press q to quit.

**Comment by remo7777** [comment]
Oh... Working now..

**Comment by its-pointless** [comment]
Yeah zoom out pinch screen make text smaller it will load.

**Comment by remo7777** [comment]
But how to play this game?..😜😜 with touch

**Comment by remo7777** [comment]
Oh using spacebar..

**Comment by remo7777** [comment]
![screenshot_20170925-073809](https://user-images.githubusercontent.com/28594846/30789907-43097b14-a1c6-11e7-82be-9ade2f8074d7.jpeg)

**Comment by remo7777** [comment]
Rules
1. Set up your game.
2. Place the aces above the piles.
3. Keep stacking the cards until you cannot move anymore.
4. Each pile should be alternating in color and move in descending order.
5. Use the reserve deck if you run out of moves.
6. Place kings into empty slots.
![screenshot_20170925-081605](https://user-images.githubusercontent.com/28594846/30790529-0573ff32-a1ca-11e7-9439-3bbcc8ef929f.jpeg)
Rule no. 4 card color problem.

**Comment by sdrausty** [comment]
♠❤♦♣ the four card suites. Where are they in tty-solitaire?

**Comment by remo7777** [comment]
@sdrausty: :grinning: :kissing_heart:

**Comment by sdrausty** [comment]
@remo7777 Thank you ☺

**Comment by remo7777** [comment]
I found it from termux - help... Option
Thank you termux..
