### ISSUE TITLE
[Package]: pdf-tools

### ISSUE THREAD

**Issue by gbarnich** [termux/termux-packages#15378]
### Why do you want to add this package to Termux?

It would be great to have emacs pdf-tools working under termux. It can be used to view pdf files directly in emacs, spacemacs or doom-emacs, so no need to termux-open the pdf file generated by latex. 

The problem is that I cannot built the epdf-info server.

I tried alternatives like termux-ubuntu or nix-on-droid to get this working, but for me they are either too complicated or too slow. 

### Source code URL

https://github.com/vedang/pdf-tools

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

~/pdf-tools $ ./server/autobuild -d
Failed to recognize this system, trying to continue.
---------------------------
 Configuring and compiling
---------------------------
./configure -q  && make clean && make -s
configure: error: Package requirements (poppler-glib >= 0.16.0) were not met:

Package 'xproto', required by 'x11', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables poppler_glib_CFLAGS
and poppler_glib_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(
===========================

**Comment by xtkoba** [comment]
Dev note. It is common that `xorgproto` package is missing from build dependency (`TERMUX_PKG_BUILD_DEPENDS`) of some package. Unfortunately it is hard to detect because it does not matter on CI.

**Comment by gbarnich** [comment]
Thanks for providing the precise name for the package ! With this installed, the server builds and PDF tools is installed correctly. There is one remaining problem though. The pdf does not show correctly and the error message is now: 

Error while processing tq callback: PNG image supported not compiled into Emacs.

There is a solution for this problem for emacs ported to windows: 
https://emacs.stackexchange.com/questions/38946/png-image-support-and-pdftools
https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Image-support.html

Any suggestions on what to do for the termux version ?

**Comment by gbarnich** [comment]
Update: 

1) pdf-tools do work with emacs-x when using GUI with VNC viewer. The result is not very good though (on an eink device with android 11). 
2) results are in general much better using the standard emacs app in the terminal. The above problem "PNG image supported not compiled into Emacs." remains. The error message when trying to directly open a .png file in emacs is "error DISPLAY does not support images). 

Is there any way to compile emacs with png support directly in termux, without passing through X ?

**Comment by gbarnich** [comment]
With emacs-x, when setting the correct geometry and dpi in the vncserver and using emacs in fullscreen mode in the vncviewer, results are very good after all, both for standard emacs and spacemacs.
