### ISSUE TITLE
[Bug]: whois (version 5.5.16): Failing to build

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#15390]
### Problem description

`whois` has been bumped to version `5.5.16` in 64fe148b341a2de61f4dc763cfca0d7b62d1a7d1, which however fails to build in CI:

https://github.com/termux/termux-packages/actions/runs/4293666704

### What steps will reproduce the bug?

Trigger (re)build of `whois` package in GitHub Actions CI.

### What is the expected behavior?

Build should succeed.

### System information

GitHub Actions.

**Comment by xtkoba** [comment]
Consider reverting the bump if it is hard to fix. Thanks.

**Comment by landfillbaby** [comment]
oh oops i didn't notice! fixed in https://github.com/termux/termux-packages/commit/c4a4ce34209ad791442fad73ba6c5a2c062ba51c. although really it's an upstream problem that they didn't use `$(prefix)`
