### ISSUE TITLE
irssi does not load config

### ISSUE THREAD

**Issue by pressure679** [termux/termux-packages#1541]
even with the --config argument to irssi the config is not loaded.

**Comment by fornwall** [comment]
Could you give a short description of steps how to verify the problem (for one who have never used irssi myself)?

**Comment by pressure679** [comment]
Yeah.
My config has some bloat to it, but it is to use it in a terminal, the following extensions are:
color nick (nickcolor.pl from https://irssi.org/download/)
A config file to add ignoring of JOINS, PARTS and QUITS messages.
- A autojoin list of some channels.
- A logging of the channels.
I start the irssi program like so:
irssi -c irc.freenode.org -w 12345qwer -n pressure679

I tried adding the --config argument to specify where my irssi config file was/is ~/.irssi/config in termux, and in irssi a /server add irc.freenode.org command, but it did not solve the issue.

the error irssi writes while executed in termux is:
... Wait, the device, and termux, are rooted now, and irssi connects to the irc.freenode.org server. It still does not join the channels, but I will see if I can solve the issue.

**Comment by pressure679** [comment]
Aww, it was me, I simply wrote the wrong server domain name. - .org instead of .net

**Comment by fornwall** [comment]
Ok, thanks for the feedback!
