### ISSUE TITLE
[Package]: pthreads extension for php

### ISSUE THREAD

**Issue by u400822** [termux/termux-packages#15413]
### Why do you want to add this package to Termux?

null

### Home page URL

php.net

### Source code URL

null

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Maybe a duplicate of #892.
