### ISSUE TITLE
[Bug]: git send-email fails due to "out-of-date IO::Socket::SSL"

### ISSUE THREAD

**Issue by matheusmoreira** [termux/termux-packages#15424]
### Problem description

`git send-email` currently fails on my up to date Termux system. After attempting to send an email, I get the following message:

```
Not using SSL_VERIFY_PEER due to out-of-date IO::Socket::SSL.
To use SSL please install IO::Socket::SSL with version>=2.007 at /data/data/com.termux/files/usr/lib/perl5/5.36.0/Net/SMTP.pm line 268, <FIN> line 1.
```

Attempting to resolve that dependency by using `cpan` also failed.

```
cpan update
cpan IO::Socket::SSL
```

I get _numerous_ build errors when running the above commands, suggesting that building and/or intalling these modules is not supported on Termux.

I searched the package repositories for Perl SSL packages but didn't find any.

### What steps will reproduce the bug?

 - Installed git

       pkg install git

 - Configured git
 - Configured git send-email with my gmail account
 - Used format-patch to make a test patch

       git format-patch -1 HEAD

 - Attempted to send a test email to myself

       git send-email --to=$(git config user.email) *.patch

 - Got the reported error message and email was not sent

I also attempted to follow these [instructions on StackOverflow][link].

[link]: https://stackoverflow.com/a/68238913

### What is the expected behavior?

`git send-email` should send the email without errors.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=19454
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb http://mirror.mephi.ru/termux/termux-main stable main
Updatable packages:
parallel/stable 20230222 all [upgradable from: 20230122]
termux-tools version:
1.37.0
Android version:
10
Kernel build information:
Linux localhost 4.9.186-22986754 #1 SMP PREEMPT Thu Aug 4 00:22:03 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N9600
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
If the goal is to make the following Perl code work:

```perl
require IO::Socket::SSL;
IO::Socket::SSL->import(qw/SSL_VERIFY_PEER SSL_VERIFY_NONE/);
```

then

```bash
export LIBDIR=$PREFIX/lib
export OPENSSL_PREFIX=$PREFIX
cpan -fi Net::SSLeay

cpan -fi IO::Socket::SSL
```

works for me.

**Comment by matheusmoreira** [comment]
Setting those variables solved my issue. Thank you.

**Comment by Sertonix** [comment]
Isn't this still an issue? I think termux packages should fix the differences in the enviroment.
Maybe the env can also be set at compile time.
