### ISSUE TITLE
[Bug]: cloneit does not works

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#15466]
### Problem description

I tried to run `cloneit` but didn't worked 

Error :

```
❯ cloneit https://github.com/SubhamTyagi/Last-Launcher/tree/master/app/src/main/java/io/github/subhamtyagi
CANNOT LINK EXECUTABLE "cloneit": library "libssl.so.1.1" not found: needed by main executable
```

Libs :
```
❯ ls $PREFIX/lib/ | grep libssl
libssl.so
libssl.so.3
libssl3.so
```

### What steps will reproduce the bug?

```bash
apt install cloneit
cloneit https://github.com/SubhamTyagi/Last-Launcher/tree/master/app/src/main/java/io/github/subhamtyagi
```

### What is the expected behavior?

Should work

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Please share your `termux-info` output.

**Comment by xtkoba** [comment]
Ah, OK. Turns out that `openssl-1.1` is in `TERMUX_PKG_BUILD_DEPENDS`. This should be in `TERMUX_PKG_DEPENDS`.

**Comment by ThatMG393** [comment]
`pkg up && pkg in openssl`
