### ISSUE TITLE
tcsh autolock function not working.

### ISSUE THREAD

**Issue by tcshUser** [termux/termux-packages#15469]
In tcsh entered
set autologout = ( 300 30 )

After 30 - 60 seconds nothing happens.

Thanks

tcshUser

**Comment by xtkoba** [comment]
From `tcsh(1)` manpage:

> The first word is the number of *minutes* of inactivity before automatic logout.  The optional second word is the number of *minutes* of inactivity before automatic locking. 

(emphasis mine)
