### ISSUE TITLE
Accept user-trusted ca-certificates

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#1546]
_From @aetherfaerber on August 29, 2017 9:10_

Hi,

As the title already says: termux currently seems to ignore certificates imported via android system settings or e.g. cadroid. 

It would be nice if these could be used or other means were available inside termux to keep a repository of trusted certificates. Otherwise scripts can't connect to services on a server with a self-signed certificate using a secure connection.

_Copied from original issue: termux/termux-app#404_

**Comment by fornwall** [comment]
After updating packages, it's now possible to add trusted certificates using the `add-trusted-certificate` script as shown below:

```sh
$ curl https://self-signed.badssl.com
curl: (60) SSL certificate problem: self signed certificate
[...]

$ echo | openssl s_client -showcerts -connect self-signed.badssl.com:443 |  sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > self-signed.badssl.com.pem
[...]

$ add-trusted-certificate self-signed.badssl.com.pem
Copying self-signed.badssl.com.pem to /data/data/com.termux/files/usr/etc/tls/certs/
Doing /data/data/com.termux/files/usr/etc/tls/certs/
link self-signed.badssl.com.pem -> c275f070.0

$ curl https://self-signed.badssl.com
<!DOCTYPE html>
[...]
```

What `add-trusted-certificate` is copying the specified file to `$PREFIX/etc/tls/certs/` and runs [openssl rehash](https://www.openssl.org/docs/man1.1.1/man1/rehash.html) on it, so the file should be a .pem, .crt, .cer, or .crl one.

**Comment by unixandria-xda** [comment]
> After updating packages, it's now possible to add trusted certificates using the `add-trusted-certificate` script as shown below:
> 
> ```shell
> $ curl https://self-signed.badssl.com
> curl: (60) SSL certificate problem: self signed certificate
> [...]
> 
> $ echo | openssl s_client -showcerts -connect self-signed.badssl.com:443 |  sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > self-signed.badssl.com.pem
> [...]
> 
> $ add-trusted-certificate self-signed.badssl.com.pem
> Copying self-signed.badssl.com.pem to /data/data/com.termux/files/usr/etc/tls/certs/
> Doing /data/data/com.termux/files/usr/etc/tls/certs/
> link self-signed.badssl.com.pem -> c275f070.0
> 
> $ curl https://self-signed.badssl.com
> <!DOCTYPE html>
> [...]
> ```
> 
> What `add-trusted-certificate` does is copying the specified file to `$PREFIX/etc/tls/certs/` and runs [openssl rehash](https://www.openssl.org/docs/man1.1.1/man1/rehash.html) on it, so the file should be a .pem, .crt, .cer, or .crl one.

This doesn't work on the adguard cert

Says doesn't contain exactly one certificate

**Comment by xeffyr** [comment]
> This doesn't work on the adguard cert

Yes, because it has to be converted into PEM format. Adguard provides only DER.
