### ISSUE TITLE
New folder name algorithm breaks for certain tar files

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#1548]
I'm trying to build tsocks, but I am getting `rm: refusing to remove '.' or '..' directory: skipping '.'` from the builder. Investigating yields this line, which breaks for a small subset of tar files:
https://github.com/termux/termux-packages/blob/87566986d257f9c087e254fae3e7fbd8e87e1a31/build-package.sh#L478

```
$ tar tf tsocks-1.8beta5.tar.gz | head -1
./tsocks-1.8/
$⠁tar tf tsocks-1.8beta5.tar.gz | head -1 | sed -e 's/\/.*//'
.
```
I wonder if this last `sed` is even necessary? How would one create a tar file which lists the file in a folder first, but not the folder itself?

**Comment by fornwall** [comment]
> How would one create a tar file which lists the file in a folder first, but not the folder itself?

Hm, it seems to exist:

    $ tar tf ./binutils/cache/binutils-2.29.tar.gz | head -1
    binutils-2.29/config.guess

and

    $ tar tf ./attr/cache/attr-2.4.47.src.tar.gz | head -1
    attr-2.4.47/Makefile

What do you think about

    folder=`tar tf "$file" | head -1 | sed 's/^.\///' | sed -e 's/\/.*//'`

that is, inserting a `sed 's/^.\///'` step to clear away an initial `./` if it exists, like in your above`./tsocks-1.8/` example?

**Comment by Neo-Oli** [comment]
> that is, inserting a `sed 's/^.\///'` step to clear away an initial `./` if it exists, like in your above`./tsocks-1.8/` example?

That would fix this problem, I think. We'll just have to keep our eye out for any more weird tar files.

**Comment by fornwall** [comment]
Thanks, pushed!

> We'll just have to keep our eye out for any more weird tar files.

Right, if we encounter anything too strange we could always make it possible to manually specify the root folder name again.
