### ISSUE TITLE
nano: segmentation fault

### ISSUE THREAD

**Issue by roccomuso** [termux/termux-packages#1551]
I've installed `nano` but when I run it I get a "Segmentation fault" error on the terminal.

**Comment by its-pointless** [comment]
Which arch are you using?
`uname -m` command if you don't know.

**Comment by roccomuso** [comment]
`uname -m` returns: `armv71`.

I've tried `nano` on a different smartphone. Same error.

**Comment by Auxilus** [comment]
Works fine on aarch64

**Comment by fornwall** [comment]
@roccomuso Thanks for reporting!

1. Does running `apt show nano` indicate the latest version with `Version: 2.8.7`?
2. Which Android version (and possibly custom ROM) are you running?

**Comment by roccomuso** [comment]
1. nano version `2.8.7`.
2. Android `7.0` - ROM `Emui v5.0`.

**Comment by samtech09** [comment]
I also got same issue.
`uname -m` reports `aarch64`
`nano` version is `2.8.7`
Device is Samsung Note-5 with Android Nouget.

**Comment by fornwall** [comment]
@roccomuso @samtech09 Are you still having this problem with nano, even after updating to latest package versions by running `pkg up`?

**Comment by spiraldancing** [comment]
I hit the same issue.  Checked tried all of the above, did not resolve (what is `pkg up`?).

Ran `apt-get dist-upgrade` ... this resolved the issue for me.

**Comment by Quasic** [comment]
```pkg up``` is basically shorthand for ```apt update && apt upgrade```
The pkg script wraps apt.

**Comment by sdrausty** [comment]
Feedback requested forvhttps://sdrausty.github.io/au/ regarding 

> `pkg up` is basically shorthand for `apt update && apt upgrade`
The `pkg` script wraps `apt`:. 

```
[21:58 ~ ]$ which apt get
/data/data/com.termux/files/usr/bin/apt
[21:58 ~ ]$ file $(which atp get)
Usage: file [-bcEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding] [--mime-type]
            [-e testname] [-F separator] [-f namefile] [-m magicfiles] file ...
       file -C [-m magicfiles]
       file [--help]
[21:58 ~ ]$ file $(which apt get)
```:

**Comment by Quasic** [comment]
@sdrausty, is this what you were asking about?
`````
$ file "$(which apt)"
/data/data/com.termux/files/usr/bin/apt: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
`````

**Comment by sdrausty** [comment]
@Quasic yes, I was.  
> I think https://sdrausty.github.io/au/ should stick to using apt directly.

I agree, since we are only interested in rolling back deb files in case we received an incoherent push.

**Comment by sdrausty** [comment]
@Quasic yes, I was.  
> I think https://sdrausty.github.io/au/ should stick to using apt directly.

Agreed; we are only interested in rolling back deb files in case we received an upsetting push with `pkg up`.
