### ISSUE TITLE
[Package]: node 16.19.0

### ISSUE THREAD

**Issue by WindowHZT** [termux/termux-packages#15527]
### Why do you want to add this package to Termux?

Hello, how to build node 16.19.0 in docker, can you help me? I need this version of node, here's how I changed packages/nodejs/build.sh and compiled, without success

![image](https://user-images.githubusercontent.com/78307930/223713165-c4ea741c-5fb9-4bf4-8139-a234d5437a4a.png)

![image](https://user-images.githubusercontent.com/78307930/223711479-5af73a4f-1b70-4f90-82bb-44505c7cbe31.png)

### Source code URL

https://nodejs.org/dist/v16.19.0/

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I tried compiling it on my device，win11->wsl2->docker-destop

**Comment by xtkoba** [comment]
Go to TUR. Thanks.

**Comment by WindowHZT** [comment]
> 转到 TUR。谢谢。

Can you say a little more detailed？

**Comment by WindowHZT** [comment]
> > 转到 TUR。谢谢。
> 
> 你能说得更详细一点吗？
Sorry I didn't understand

**Comment by WindowHZT** [comment]
> Go to TUR. Thanks.

Sorry I didn't understand

**Comment by 2096779623** [comment]
> Sorry I didn't understand

https://github.com/termux-user-repository/tur/issues/new
Create a package request there.
