### ISSUE TITLE
ZSH install fails

### ISSUE THREAD

**Issue by dexofan23** [termux/termux-packages#1552]
chsh -s `which zsh`
/data/data/com.termux/files/usr/bin//data/data/com.termux/files/usr/bin/zsh is not an executable file!
Android 6.0.1

**Comment by yashamon** [comment]
I have the same problem. Although manually launching zsh works. On a side note why does bash even exist anymore?

**Comment by its-pointless** [comment]
no need for which command
just use chsh
then zsh

**Comment by dexofan23** [comment]
@its-pointless didn't work. ZSH work only if i type zsh in shell by my hands.

**Comment by its-pointless** [comment]
type chsh
a prompt comes up
type zsh
default shell is now zsh but you are still running bash
or you can simply ln -s $(which zsh) ~/.termux/shell

**Comment by dexofan23** [comment]
chsh didn't work.

**Comment by Grimler91** [comment]
@dexofan23 could you please provide more details as to why it doesn't work, i.e. what did you write and what error message did you get?

**Comment by dexofan23** [comment]
@Grimler91 i didn't had any output. Shell does not change with chsh command.

**Comment by Grimler91** [comment]
So did the prompt appear? 
How did you verify that the shell changed/didn't change?

**Comment by dexofan23** [comment]
@Grimler91 Yep, promt appears. To verify I use oh-my-zsh with default theme to see that shell changed. When I type ZSH by my hands shell changes to ZSH.

**Comment by Neo-Oli** [comment]
@dexofan23 chsh doesn't switch your current shell, only your default shell. You have to exit your current shell and start a new one. 

On a side note. You can use chsh as a oneliner:
`chsh -s zsh`
