### ISSUE TITLE
Fake su binary makes it hard to determine root status

### ISSUE THREAD

**Issue by mks-h** [termux/termux-packages#15538]
Termux does not supply tools for rooting, yet it does supply a script named 'su' that tells users that Termux does not supply tools for rooting.

The problem is, I expected to determine, from a script, whether root is present by running "which su". This way if I'm booted from a boot image patched with Magisk, I can use "su" in a script. But if I'm not, I can connect through root-enabled ADB and have root access that way.

But always having a "su" script makes it hard to determine whether it is actually available.

**Comment by twaik** [comment]
Why not to check if `/system/bin/su` is available or not? Anyway termux has only `/data/data/com.termux/files/usr/bin` in `PATH` so this check will fail in any other case.

**Comment by mks-h** [comment]
Fair enough, thanks for the suggestion
