### ISSUE TITLE
pip install neovim throws error

### ISSUE THREAD

**Issue by yashamon** [termux/termux-packages#1553]
pip install neovim throws the following error. This is on ChromeOs

llecting neovim
  Using cached neovim-0.1.13.tar.gz
Requirement already satisfied: msgpack-python>=0.4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from neovim)
Collecting greenlet (from neovim)
  Using cached greenlet-0.4.12.tar.gz
Installing collected packages: greenlet, neovim
  Running setup.py install for greenlet ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-u2p_0ila/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-44cq4vqh-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.linux-i686-3.6
    i686-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=i686 -msse3 -mstackrealign -mfpmath=sse -Oz -march=i686 -msse3 -mstackrealign -mfpmath=sse -Oz -fPIC -I/data/data/com.termux/files/usr/include/python3.6m -c greenlet.c -o build/temp.linux-i686-3.6/greenlet.o
    unable to execute 'i686-linux-android-clang': No such file or directory
    error: command 'i686-linux-android-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-u2p_0ila/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-44cq4vqh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-u2p_0ila/greenlet/

**Comment by Grimler91** [comment]
Have you installed clang? 
`pkg install clang`

**Comment by yashamon** [comment]
Yes clang is installed. Calling clang separately seems to work.

**Comment by fornwall** [comment]
@yashamon Does running `i686-linux-android-clang` directly work? It should come as part of the `clang` package.

Could you perhaps try updating all packages with `pkg up` and try again?

**Comment by yashamon** [comment]
ran pkg up, running i686-linux-android-clang directly works it just gives
error that there are no input files.
I think clang is working, the error in the compilation is this
one: ./greenlet.h:8:10: fatal error: 'Python.h' file not found

**Comment by fornwall** [comment]
@yashamon Great! Run `pkg install python-dev` to install Python.h - then it should work!

**Comment by yashamon** [comment]
that worked. But is there a reason this dependency could not be auto
fetched?

**Comment by Grimler91** [comment]
@yashamon pip doesn't know anything about apt and all packages available through it so it doesn't know where Python.h is. It's the same "problem" on many linux distros if you install through pip.
