### ISSUE TITLE
[Bug]:  required sse2neon patch

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#15585]
### Problem description

```
/data/data/com.termux/files/usr/include/sse2neon.h:6655:53: error: implicit conversion increases floating-point precision: 'float' to 'double' [-Werror,-Wdouble-promotion]
    _sse2neon_const __m128d mask = _mm_set_pd(1.0f, -1.0f);
                                   ~~~~~~~~~~       ^~~~~
```
Maybe it needs to be updated because this is on line 5811 in latest sse2neon https://github.com/DLTcollab/sse2neon/blob/0d28a356e2f06b50372a7c4d60a4649e225a0acd/sse2neon.h#L5811

### What steps will reproduce the bug?

Got this while compiling blender #blen

### What is the expected behavior?

Should compile successfully 

### System information

--

**Comment by xtkoba** [comment]
```bash
CFLAGS+=" -Wno-error=double-promotion"
CXXFLAGS+=" -Wno-error=double-promotion"
```

**Comment by xtkoba** [comment]
I see in the build log of Blender that the following options are specified:

```
-Werror=float-conversion
-Werror=double-promotion
```

The build system of Blender should be patched so that these options are not specified, instead of patching sse2neon.

**Comment by xtkoba** [comment]
Or you may want to report this upstream.

**Comment by T-Dynamos** [comment]
> I see in the build log of Blender that the following options are specified:
> 
> ```
> -Werror=float-conversion
> -Werror=double-promotion
> ```
> 
> The build system of Blender should be patched so that these options are not specified, instead of patching sse2neon.

Yes I did `x11-packages/blender/no-double_promotion-float_conversion.PATCH`
See : https://github.com/termux/termux-packages/pull/12103/files
But still not working 🫥

**Comment by xtkoba** [comment]
Because uppercase "PATCH" suffix is not recognized by our scripts.

**Comment by T-Dynamos** [comment]
Ahh, I can feel the pain.
