### ISSUE TITLE
Auto update failing for matterircd

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#15590]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the matterircd package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating matterircd [Current version: 0.26.1]
INFO: package being updated to 0.27.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 3136k    0 3136k    0     0  3082k      0 --:--:--  0:00:01 --:--:-- 3082k
100 5451k    0 5451k    0     0  3621k      0 --:--:--  0:00:01 --:--:-- 4744k

You are about to commit these changes:

--------------------
diff --git a/packages/matterircd/build.sh b/packages/matterircd/build.sh
index c257c167f..0642988ad 100644
--- a/packages/matterircd/build.sh
+++ b/packages/matterircd/build.sh
@@ -2,10 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://github.com/42wim/matterircd
 TERMUX_PKG_DESCRIPTION="Connect to your mattermost or slack using your IRC-client of choice"
 TERMUX_PKG_LICENSE="MIT"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="0.26.1"
-TERMUX_PKG_REVISION=1
+TERMUX_PKG_VERSION="0.27.0"
 TERMUX_PKG_SRCURL=https://github.com/42wim/matterircd/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=025d0dc7ef12902ad64e92c7e7a2a612a488310ef4154f712d835386eede5bf9
+TERMUX_PKG_SHA256=f1a4bc836473459bf97fde2abcdbc45dccbf51af619b4a051f4202ac9b15ebe7
 TERMUX_PKG_BUILD_IN_SRC=true
 TERMUX_PKG_AUTO_UPDATE=true
 
--------------------

bump(main/matterircd): 0.27.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package matterircd exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building matterircd for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0   109k      0 --:--:-- --:--:-- --:--:--  109k
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1519      0 --:--:-- --:--:-- --:--:--  1517
gpg: Signature made Sat 11 Mar 2023 12:29:15 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: BAD signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
ERROR: failed to verify gpg signature of /home/builder/.termux-build/_cache/packages-cf.termux.dev-apt-termux-main-stable-Release
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-03-11 00:32:37 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/4389533809">4389533809</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by xtkoba** [comment]
Temporary.
