### ISSUE TITLE
[Package]: authbind

### ISSUE THREAD

**Issue by Runner-coder** [termux/termux-packages#15599]
### Why do you want to add this package to Termux?

"Authbind" can be used to forward lower ports without having root access. I need this for a project that I'm working on where it requires to forward port 80 to port 8080 for a web server application. This would be really helpful since I don't have to root my device to do the job.

### Home page URL

http://www.chiark.greenend.org.uk/ucgi/~ian/git/authbind.git/

### Source code URL

http://www.chiark.greenend.org.uk/ucgi/~ian/git?p=authbind.git;a=snapshot;h=64b7841344fcc3cc5208a6ac8ec92c2db1a8802f;sf=tgz

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I tried to compile the package but it was very tedious and after some trials and errors I got it to work. (Sort of)

First I had to include the following in the source files.
`#include <netdb.h>`

Then I had to change the paths in the source files wherever contains usr as the following

`/data/data/com.termux/files/usr`

But I couldn't install it using "make install" command because it couldn't copy/modify some files and permissions due to the /usr directory has been mounted as read only. So I manually created the directories and moved the files.

After running the authbind in the source file location (./authbind) it will give some errors for missing files. You have to move those files in the correct place.

After doing all of these still the authbind wouldn't work even though it runs perfectly. It gives a operation not permitted error. But the whole point of this tool is not to use root access. So it could be a mistake that I made while compiling or editing the files. 

`authbind socat TCP4-LISTEN:90,fork,reuseaddr TCP4:TCP4:127.0.0.1:8080`

`2023/03/11 18:33:19 socat[14484] E bind(5, {AF=2 0.0.0.0:90}, 16): Operation not permitted
`
Either way if you could make this package available on official termux repo then it would be really helpful.

**Comment by xtkoba** [comment]
IIUC `authbind` itself needs root privilege; some helper program has to be setuid to root. Does this satisfy your needs?

**Comment by Runner-coder** [comment]
Thanks for your info. I thought that it doesn't require root privileges since it's designed bind lower ports without root privileges. All the examples I found online don't run the authbind as sudo. So I'm little bit confused. Could you explain this to me little bit more ? (I'm new to the Linux field)

**Comment by xtkoba** [comment]
Do you understand what `setuid(2)` is? `sudo(8)` is setuid to root (on my GNU/Linux system):

```
$ ls -l /usr/bin/sudo
-rws--x--x 1 root root 266808  3月  8 15:00 /usr/bin/sudo
```

**Comment by xtkoba** [comment]
See also "Authbind" article in Wikipedia: https://en.wikipedia.org/wiki/Authbind

**Comment by xtkoba** [comment]
And "Setuid" article: https://en.wikipedia.org/wiki/Setuid

**Comment by xtkoba** [comment]
When an executable is setuid, then it is executed in the privilege of the owner of the file. `sudo` command relies on this mechanism, so does authbind. This leads to that some executable in `authbind` package has to be owned by `root`, which is impossible without root access.

**Comment by Runner-coder** [comment]
Ok, now I understand it. So one way or the other I have to root my device to archive the task. Anyway thanks for your help. Do you think that I should close the issue ?

**Comment by xtkoba** [comment]
You can if you want. We do not prevent it.

**Comment by Runner-coder** [comment]
Um, I'm gonna keep this open for a while in case if someone find an alternative solution. Anyway thanks again for your help.

**Comment by Cima899** [comment]
##                   Hi 👋

##.                      Open Termux
                and run the following commands

pkg install termux-gui-pm/stable fakeroot/stable fakeroot-static/stable authbind broot proot-distro proot broot root-repo x-11 repo  python python3 python-pip/stable,now &&  proot -0  && cd $HOME 



##                  After 

termux-chroot 


## a me funziona come root qualsiasi cosa

## Greetings
