### ISSUE TITLE
Cannot link executable 

### ISSUE THREAD

**Issue by Desmond235** [termux/termux-packages#15592]
$ apt update
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found

![Screenshot_20230311-083200](https://user-images.githubusercontent.com/102704899/224474106-7e073a89-5fb5-4199-8411-fbfeee259415.png)

**Comment by xtkoba** [comment]
Your system is broken. Reset it and then do `pkg up` first of all.

Note also that the Termux app in Google Play is not supported.

**Comment by xtkoba** [comment]
I meant by "system" the ecosystem of Termux packages. Not that you have to reset your Android system.

BTW, for me this does not seem to be likely to happen. With my up-to-date system I get the following:

```
$ ldd $PREFIX/lib/apt/methods/https
	libandroid-glob.so => /data/data/com.termux/files/usr/lib/libandroid-glob.so
	libapt-pkg.so => /data/data/com.termux/files/usr/lib/libapt-pkg.so
	libgnutls.so => /data/data/com.termux/files/usr/lib/libgnutls.so
	libc++_shared.so => /data/data/com.termux/files/usr/lib/libc++_shared.so
	libm.so => /system/lib64/libm.so
	libdl.so => /system/lib64/libdl.so
	libc.so => /system/lib64/libc.so
	ld-android.so => /system/lib64/ld-android.so
	libz.so.1 => /data/data/com.termux/files/usr/lib/libz.so.1
	libbz2.so.1.0 => /data/data/com.termux/files/usr/lib/libbz2.so.1.0
	liblzma.so.5 => /data/data/com.termux/files/usr/lib/liblzma.so.5
	liblz4.so => /data/data/com.termux/files/usr/lib/liblz4.so
	libzstd.so.1 => /data/data/com.termux/files/usr/lib/libzstd.so.1
	libiconv.so => /data/data/com.termux/files/usr/lib/libiconv.so
	libgcrypt.so => /data/data/com.termux/files/usr/lib/libgcrypt.so
	libxxhash.so.0 => /data/data/com.termux/files/usr/lib/libxxhash.so.0
	libgpg-error.so => /data/data/com.termux/files/usr/lib/libgpg-error.so
	libidn2.so => /data/data/com.termux/files/usr/lib/libidn2.so
	libunistring.so => /data/data/com.termux/files/usr/lib/libunistring.so
	libnettle.so.8 => /data/data/com.termux/files/usr/lib/libnettle.so.8
	libhogweed.so.6 => /data/data/com.termux/files/usr/lib/libhogweed.so.6
	libgmp.so => /data/data/com.termux/files/usr/lib/libgmp.so
	libandroid-support.so => /data/data/com.termux/files/usr/lib/libandroid-support.so
```

This means OpenSSL libraries are not needed by this executable. In fact our `apt` package does not depend on `openssl` now, and not in the past either, due to licensing issue. How can this happen?

**Comment by xtkoba** [comment]
Do we need to specify some old version of `apt` in `TERMUX_PKG_BREAKS` of `openssl` package? I'm reluctant to do that if this type of issue happens only on Google Play version of Termux app.
