### ISSUE TITLE
[Bug]: df: Unknown option 'T' (see "df --help")

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#15615]
### Problem description

Need coreutils 9.1 `df`
Programs like flood needs it

### What steps will reproduce the bug?

Run  df

### System information

termux-info:

```

```

**Comment by 2096779623** [comment]
Try to use lowercase `t` .

**Comment by aicynide** [comment]
@2096779623 `df -T` is different

**Comment by aicynide** [comment]
-T, --print-type      print file system type

**Comment by 2096779623** [comment]
It looks like df is hardlinked to `/system/bin/df`.
```bash
~ $ apt-file search bin/df
termux-tools: /data/data/com.termux/files/usr/bin/df
```
https://github.com/termux/termux-tools/blob/10cdf6ea804bca4c3baece359b23fb5acde7bf84/scripts/Makefile.am#L83

**Comment by aicynide** [comment]
Can we use coreutils df?

**Comment by 2096779623** [comment]
> Can we use coreutils df?

https://github.com/termux/termux-packages/blob/47746fb1d47dacda97649ab7438297ac1c691bf6/packages/coreutils/build.sh#L15
