### ISSUE TITLE
[Bug]: Build rtorrent with xmrpc-c support 

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#15616]
### Problem description

For accessing rtorrent in web-ui

### What steps will reproduce the bug?

Not bug

### System information

termux-info:

```

```

**Comment by truboxl** [comment]
This needs `libxmlrpc` which haven't packaged yet. It also uses `svn` to get it's sources rather than download source tarballs. Those who want to help probably need to invest some time on this.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/8763838917
