### ISSUE TITLE
Split Docker into separate repo

### ISSUE THREAD

**Issue by stephengroat** [termux/termux-packages#1562]
As discussed with @fornwall, by creating the additional git repo `termux-build` and using `.gitmodules` to map it to the `scripts` dir, docker images could be built and deployed by travis-ci

[this site](http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/) shows an example of how to move a directory to another repo while maintaining history

```
- termux-packages
---> scripts (https://github.com/termux/termux-build.git)
-------> Dockerfile
-------> etc.
---> build-package.sh
---> etc.
```

**Comment by sdrausty** [comment]
Will this work on device?

**Comment by stephengroat** [comment]
@sdrausty as long as `git` has submodule support, which is pretty ubiquitous. it's not a `contrib` project or anything like that, it's pretty much considered core functionality

as an example, try cloning `hashcat`, which i know has submodules, and check for the `deps/OpenCL-Headers/CL` directory and make sure it has files in it (specifically headers)

```
git clone https://github.com/hashcat/hashcat.git
cd hashcat
git submodule update --init --recursive
```

**Comment by sdrausty** [comment]
Done.
```
$ git clone https://github.com/hashcat/hashcat.git
Cloning into 'hashcat'...
remote: Counting objects: 32748, done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 32748 (delta 80), reused 92 (delta 48), pack-reused 32603
Receiving objects: 100% (32748/32748), 26.08 MiB | 112.00 KiB/s, done.
Resolving deltas: 100% (27222/27222), done.
$ cd hashcat
$ git submodule update --init --recursive
Submodule 'deps/OpenCL-Headers/CL' (https://github.com/KhronosGroup/OpenCL-Headers.git) registered for path 'deps/OpenCL-Headers/CL'
Cloning into '/data/data/com.termux/files/home/hashcat/deps/OpenCL-Headers/CL'...
Submodule path 'deps/OpenCL-Headers/CL': checked out 'bf0f43b76f4556c3d5717f8ba8a01216b27f4af7'
$ ls  deps/OpenCL-Headers/CL
cl.h                             cl_ext_intel.h
cl_d3d10.h                       cl_gl.h
cl_d3d11.h                       cl_gl_ext.h
cl_dx9_media_sharing.h           cl_platform.h
cl_dx9_media_sharing_intel.h     cl_va_api_media_sharing_intel.h
cl_egl.h                         opencl.h
cl_ext.h
$
```
@stephengroat Thank you for your immediate reply. What steps should be taken next to build this on device in Termux?

**Comment by stephengroat** [comment]
don't worry, changes haven't occurred yet.

this change shouldn't change much of anything for `termux-packages`, just allow automated `termux-docker` builds

**Comment by sdrausty** [comment]
+stephengroat afaik docker isn't available on device in Termux.

**Comment by stephengroat** [comment]
@sdrausty on device builds currently aren't available because the android NDK (the basis of the termux build process) is currently a cross compiling framework and isn't built for android

**Comment by sdrausty** [comment]
+stephengroat 🌒 moon-buggy builds well on device; And I am interested in building on device for the specific system it's on, not cross compling for other device architectures. Kind of how https://sdrausty.github.io/buildAPKs builds APKs on device. Download source and build it on the device being used.

**Comment by stephengroat** [comment]
@sdrausty sorry, i was confused. when you said 

> Will this work on device?

I thought you were referring to clone the `termux-packages` repo. this proposed change has no effect on the ability to run the script on device

**Comment by sdrausty** [comment]
@stephangroat It is very tempting to 🔥 fire up my old computers, some of which are not that old. However, I made a decision last year to confine my computer activity to smartphones with Termux. This seems to be working better than expected at present. 

Sorry about not stating my initial question clearer, that I meant building packages on device in Termux. Any suggestions, including links about compling deb packages this way are very welcome.

**Comment by sdrausty** [comment]
https://wiki.termux.com/index.php?title=Installing_from_Source_on_Device

https://wiki.termux.com/wiki/Installation

**Comment by vladimiroltean** [comment]
@stephengroat what is the benefit of this split?

**Comment by stephengroat** [comment]
@vladimiroltean automatic docker builds and deployments

**Comment by stephengroat** [comment]
@fornwall i've made an example of the idea with https://github.com/stephengroat/termux-package-builder (git repo that maintains the `scripts` history) and https://github.com/stephengroat/termux-packages/tree/scripts-sub-ex (basically `git rm scripts && git submodule add termux-package-builder scripts/ && git commit`)

**Comment by stephengroat** [comment]
@fornwall any interest in this? could really help with #1169 and it's kind of a blocker

**Comment by xtkoba** [comment]
Completely outdated. Closing.
