### ISSUE TITLE
demoneditor python-gtk oserror

### ISSUE THREAD

**Issue by risky777** [termux/termux-packages#15626]
Hi

I managed to run app demoneditor (python-gtk, https://github.com/DYefremov/DemonEditor), but there was one issue. I got error

/storage/emulated/0/Download/demoneditor/app/ui/uicommons.py", line 85, in
locale.bindtextdomain(TEXT_DOMAIN, LANG_PATH)
OSError: [Errno 22] Invalid argument

I fixed that by commenting-out lines

#if UI_RESOURCES_PATH == BASE_PATH:
#locale.bindtextdomain(TEXT_DOMAIN, LANG_PATH)

Do you know what could cause that?

**Comment by xtkoba** [comment]
This is because Bionic (libc in Android) does not fully support locales.

The `gjots2` package in our repo has a similar workaround:

https://github.com/termux/termux-packages/blob/0ededf58b8d52f19f3a4e9e7b6ced02256d936d8/x11-packages/gjots2/bin-gjots2.patch#L1-L18

Closing as answered.
