### ISSUE TITLE
[Bug]: elfutils: zsh complains that `debuginfod.sh:9: no matches found: /data/data ... /etc/debuginfod/*.urls`

### ISSUE THREAD

**Issue by anzhi0708** [termux/termux-packages#15634]
### Problem description

Note the last line `"/data/data/com.termux/files/usr/etc/profile.d/debuginfod.sh:9: no matches found: /data/data/com.termux/files/usr/etc/debuginfod/*.urls"`

```
➜  ~ ssh -p 8022 u0_a202@192.168.43.169
Welcome to Termux!

Docs:       https://termux.dev/docs
Donate:     https://termux.dev/donate
Community:  https://termux.dev/community

Working with packages:

 - Search:  pkg search <query>
 - Install: pkg install <package>
 - Upgrade: pkg upgrade

Subscribing to additional repositories:

 - Root:    pkg install root-repo
 - X11:     pkg install x11-repo

For fixing any repository issues,
try 'termux-change-repo' command.

Report issues at https://termux.dev/issues
/data/data/com.termux/files/usr/etc/profile.d/debuginfod.sh:9: no matches found: /data/data/com.termux/files/usr/etc/debuginfod/*.urls
~ %
```

After rooting my Redmi Note 11 and reinstalling Termux, I did a full upgrade for Termux. It all went well at the beginning, then `debuginfod.sh:9: no matches found: /data/data ... /etc/debuginfod/*.urls` showed up when launching the app.

I'm 66.66% sure that this isn't a big deal; yet it tells me to report any issue here, so here I am.

### What steps will reproduce the bug?

Openning Termux app

### What is the expected behavior?

No error message showing

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12717
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://termux.mentality.rip/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
11
Kernel build information:
Linux localhost 4.14.186-perf-gd65dbc980d48 #1 SMP PREEMPT Fri Oct 28 22:22:47 CST 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
21091116AC
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
This happens if (1) `elfutils` package is installed, and (2) `zsh` is used as the login shell.

**Comment by hcartiaux** [comment]
You can also add `setopt NULL_GLOB` in your `~/.zshrc` before sourcing `/etc/profile`.
It will make zsh behaves more like bash when a file globbing pattern does not match anything.
