### ISSUE TITLE
Virgl android

### ISSUE THREAD

**Issue by RaWolFoX** [termux/termux-packages#15639]
Is it possible to use virgl in native termux environment with termux x11 app?.

**Comment by IntinteDAO** [comment]
@RaWolFoX Sorry, doesn't understand. Virglrenderer-android works on native termux environment by default (with Termux X11 also, but you can also use something else)

To execute this, you need to:
virgl_test_server_android &
This one will run virgl server in background

export GALLIUM_DRIVER=virpipe

To enable virgl client

then you execute termux-x11, for example:
termux-x11 :0 -ac &

If everything works, close issue, thanks

**Comment by DocMAX** [comment]
i try to run gnome with virgl, but it's crashing when opening windows

**Comment by crceck123** [comment]
I know it is an issue from 2024, but i have this problem when running virgl_test_server_android &: CANNOT LINK EXECUTABLE "virgl_test_server_android": cannot locate symbol "epoxy_set_library_path" referenced by "/data/data/com.termux/files/usr/bin/virgl_test_server_android"... Help me :( Android 12
