### ISSUE TITLE
![Screenshot_20230314-153402_Termux](https://user-images.githubusercontent.com/118419708/225117282-fc4c3e60-7915-4558-b2da-06c381b323fd.jpg)

### ISSUE THREAD

**Issue by ah-ha-admin** [termux/termux-packages#15644]
#15643         ![Screenshot_20230314-153402_Termux](https://user-images.githubusercontent.com/118419708/225117282-fc4c3e60-7915-4558-b2da-06c381b323fd.jpg)

_Originally posted by @ah-ha-admin in https://github.com/termux/termux-packages/discussions/15643_
      I dont know what to put in this files anyway making it wrong please help and maybe helpful commands i dont know much about termux

**Comment by xtkoba** [comment]
Do not multipost an issue. #15643 is enough. Thanks.
