### ISSUE TITLE
[BUG]: CANNOT LINK EXECUTABLE "apt": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libapt-pkg.so"...

### ISSUE THREAD

**Issue by engnilsonsp** [termux/termux-packages#15656]
I think after installing "unstable-repo", answering "y" to the question:
...
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** sources.list (Y/I/N/O/D/Z) [default=N] ? y
...
The problem occurs... in all the following calls do pkg install / apt install...
How to fix it? plz.

**Comment by xtkoba** [comment]
This can happen when you partially upgrade packages. Reset the Termux app and do `pkg up` first of all.

**Comment by xtkoba** [comment]
Also note that Google Play version of Termux app is not supported.
