### ISSUE TITLE
Package missing libnetfilter-queue-dev

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-packages#1565]
Is there a replacement for libnetfilter-queue-dev ?
Needed for installation https://github.com/kti/python-netfilterqueue

**Comment by fornwall** [comment]
Unfortunately no! I'm not sure that you can use `libnetfilter_queue` even on a rooted device. If you want to try it out your best bet is probably to build it yourself (if so, please add if it works as a comment here)!
