### ISSUE TITLE
mc can not be run

### ISSUE THREAD

**Issue by hqy6** [termux/termux-packages#15663]
CANNOT LINK EXECUTABLE "mc": cannot locate symbol "g_memdup2" referenced by "/data/data/com.termux/files/usr/bin/mc"...

**Comment by xtkoba** [comment]
Please share your `termux-info` output.

Not reproducible for me. `g_memdup2` is defined in `$PREFIX/lib/libglib-2.0.so` which is linked against from `$PREFIX/bin/mc`.

This can happen with partial upgrading of packages. Do `pkg up` (or equivalent) first and see if this persists.
