### ISSUE TITLE
[Bug]: mpd as a service ignores log

### ISSUE THREAD

**Issue by Lodger-test** [termux/termux-packages#15664]
### Problem description

mpd, started as a service, ignores log, configured in usr/etc/mpd.conf

### What steps will reproduce the bug?

1. In usr/etc/mpd.conf set log to ~/.mpd/log and set log level to "verbose"
`log_file    "~/.mpd/log"`
`log_level    "verbose"`
2. Start mpd as a service
`sv start mpd`
3. Check log `tail ~/.mpd/log`
4. The log will be empty

### What is the expected behavior?

All the same, as 1-3, but 
4. The log contains strings

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=32476
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.ustc.edu.cn/termux/apt/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
10
Kernel build information:
Linux localhost 4.9.193-perf-g743cb02 #1 SMP PREEMPT Mon Oct 25 19:19:32 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 8
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

```

**Comment by Lodger-test** [comment]
> Have you tried setting path differently, for example like below?
> 
> ```
> log_file "/data/data/com.termux/files/home/.mpd/log"
> ```

Yes, I have tried this with no result. Absolute address or relative both work fine if I start mpd manually.

**Comment by Grimler91** [comment]
It's because of the `--stdout` arg I assume. With termux-services the log output is in `$PREFIX/var/log/sv/mpd/current`. If you want to change that you can edit `$PREFIX/var/service/mpd/run` and remove the `--stdout` arg (changes will persist even if mpd package is upgraded as the file is marked as a conffile)

**Comment by Lodger-test** [comment]
Thank you, @Grimler91, that helped.
