### ISSUE TITLE
Ffmpeg can't convert flac to alac

### ISSUE THREAD

**Issue by guranu** [termux/termux-packages#15686]
### Problem description

Wanted to convert a flac audio file to an alac file (m4a) however i get this error: [ipod @ 0x7a5365e280] Could not find tag for codec h264 in stream #0, codec not currently supported in container
[out#0/ipod @ 0x7a5368b180] Could not write header (incorrect codec parameters ?): Invalid argument
[aost#0:1/alac @ 0x7a537ca300] Error initializing output stream:
Conversion failed! This is probably not the right repository to ask but i was wondering how to fix this error?

### What steps will reproduce the bug?
$ ffmpeg -i 01-enjoy-your-beverage.flac -c:a alac 01-enjoy-your-beverage.m4a
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Android (9352603, based on r450784d1) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
  configuration: --arch=aarch64 --as=aarch64-linux-android-clang --cc=aarch64-linux-android-clang --cxx=aarch64-linux-android-clang++ --nm=llvm-nm --pkg-config=/home/builder/.termux-build/_cache/android-r25c-api-24-v1/bin/pkg-config --strip=llvm-strip --cross-prefix=aarch64-linux-android- --disable-indevs --disable-outdevs --enable-indev=lavfi --disable-static --disable-symver --enable-cross-compile --enable-gnutls --enable-gpl --enable-lcms2 --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgme --enable-libmp3lame --enable-libopus --enable-librav1e --enable-libsoxr --enable-libssh --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-opencl --enable-shared --prefix=/data/data/com.termux/files/usr --target-os=android --extra-libs=-landroid-glob --disable-vulkan --enable-neon --disable-libfdk-aac
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, flac, from '01-enjoy-your-beverage.flac':
  Metadata:
    ALBUM           : Horde
    album_artist    : Fossil Aerosol Mining Project
    ARTIST          : Fossil Aerosol Mining Project
    DATE            : 2022
    ENCODER         : Lavf57.56.101
    TITLE           : Enjoy Your Beverage
    track           : 1/
  Duration: 00:04:12.52, start: 0.000000, bitrate: 793 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s32 (24 bit)
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1400x1400 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
Stream mapping:
  Stream #0:1 -> #0:0 (mjpeg (native) -> h264 (libx264))
  Stream #0:0 -> #0:1 (flac (native) -> alac (native))
Press [q] to stop, [?] for help
[vost#0:0/libx264 @ 0x7d5b7ca000] Frame rate very high for a muxer not efficiently supporting it.
Please consider specifying a lower framerate, a different muxer or setting vsync/fps_mode to vfr
[libx264 @ 0x7d5b656800] using SAR=1/1
[libx264 @ 0x7d5b656800] MB rate (696960000) > level limit (16711680)
[libx264 @ 0x7d5b656800] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x7d5b656800] profile High, level 6.2, 4:2:0, 8-bit
[libx264 @ 0x7d5b656800] 264 - core 164 - H.264/MPEG-4 AVC codec - Copyleft 2003-2022 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[alac @ 0x7d5b657000] encoding as 24 bits-per-sample
[ipod @ 0x7d5b65e280] Could not find tag for codec h264 in stream #0, codec not currently supported in container
[out#0/ipod @ 0x7d5b68b180] Could not write header (incorrect codec parameters ?): Invalid argument
[aost#0:1/alac @ 0x7d5b7ca300] Error initializing output stream:
Conversion failed!

### What is the expected behavior?

For it to convert it into an alac (m4a)

### System information

termux-info:

```
TERMUX_APK_RELEASE=F_DROID                              TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=19110                                    TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian                       TERMUX_VERSION=0.118.0
Packages CPU architecture:                              aarch64
Subscribed repositories:                                # sources.list
deb https://termux.cdn.lumito.net/termux-main stable main
# x11-repo (sources.list.d/x11.list)                    deb https://termux.cdn.lumito.net/termux-x11 x11 main
Updatable packages:                                     All packages up to date
termux-tools version:
1.37.0
Android version:                                        10
Kernel build information:                               Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Thu Jan 28 00:40:44 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
GM1900
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
I would suggest `-c:v copy`, as per https://stackoverflow.com/questions/55429909/.

Converting FLAC to ALAC itself is possible, if there is no video stream in the source.
