### ISSUE TITLE
packages missing :: libmoose-perl

### ISSUE THREAD

**Issue by remo7777** [termux/termux-packages#1569]
perl uniscan.pl
Can't locate Moose.pm in @INC (you may need to install the Moose module) (@INC contains: ./Uniscan /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.0 /data/data/com.termux/files/usr/lib/perl5/5.26.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.26.0 .) at Uniscan/Crawler.pm line 3.
BEGIN failed--compilation aborted at Uniscan/Crawler.pm line 3.
Compilation failed in require at uniscan.pl line 4.
BEGIN failed--compilation aborted at uniscan.pl line 4.

**Comment by remo7777** [comment]
OALDERS/libwww-perl-6.27.tar.gz                  one dependency not OK (Net::HTTP); additionally test harness failed                                     /data/data/com.termux/files/usr/bin/make test -- NOT OK                                             //hint// to see the cpan-testers results for installing this module, try:                               reports OALDERS/libwww-perl-6.27.tar.gz


**_need this package also 'libwww-perl' _**

**Comment by fornwall** [comment]
Generelly we try to avoid creating Termux packages for things that can be installed with language package managers (pip/cpan/npm/...).

**Comment by remo7777** [comment]
Nop. I m just checking..

**Comment by remo7777** [comment]
I want one help. Can we put our all termux data to another device...? If yes... How
