### ISSUE TITLE
Tutorial to port package to termux

### ISSUE THREAD

**Issue by huiyiqun** [termux/termux-packages#157]
Is there any tutorial to port package for termux?

I'd like to build some package(ydcv) for termux, is there some tutorial? I'm archlinux user and never package for debian or ubuntu.

Just a suggestion, apt maybe too complex for small project like termux. pacman instead more simple.

**Comment by fornwall** [comment]
There is not any documentation available except the README in this repository and looking at `build-package.sh` and the existing packages for inspiration.

Any documentation from someone who has managed to build packages would be most welcome! One step could be from the suggestion in #109: "Add a skeleton build.sh with all the possible functions/variables with descriptions".

**Comment by Auxilus** [comment]
@huiyiqun
This could help you 
https://wiki.termux.com/wiki/Package_Management#Compiling_packages_on_device

**Comment by xeffyr** [comment]
Recently we have added documentation: https://github.com/termux/termux-packages/tree/master/docs - may help to understand package creation and build process.

Regarding "package porting", take a look on https://github.com/termux/termux-packages/blob/master/docs/BUILD.md#common-porting-problems to understand common problems you may run into when trying to compile package for Termux. Nothing more can be suggested as it is not possible to have universal guide for package porting as programs written by different authors which results in different build systems, unique bugs and possible incompatibility with OSes using non-GNU libc.
