### ISSUE TITLE
termux wont sign repositories

### ISSUE THREAD

**Issue by yirod3721** [termux/termux-packages#15716]
### Problem description

i downloaded termux from f-droid and i immediately ran apt update and it updated fine then i ran apt upgrade and it asked to chsnge the ssl config so i told it yes then this happened:
W: GPG error: https://termux.cdn.lumito.net/termux-main stable InRelease: At lea
E: The repository 'https://termux.cdn.lumito.net/termux-main stable InRelease' i
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list
N: Please note that all hosting problems or other serious issues we announce on
N: Use termux-change-repo for switching to a mirror.
i saw an issue about it being from coreutils so i did what they asked and it didnt work 
and i also tried termux-change-repo on a wide range of repos and regions

### What steps will reproduce the bug?

i dont know why it did it i think it might be a cloack problem but im not sure

### What is the expected behavior?

it should t least be able to find a working repo and it isnt possible that all repos are down or unsigned

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.cdn.lumito.net/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf-g2211f76 #1 SMP PREEMPT Fri Nov 8 14:43:26 WIB 2019
Device manufacturer:
Xiaomi
Device model:
Redmi 5 Plus
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so


```

**Comment by yirod3721** [comment]
i meant clock problem

**Comment by xtkoba** [comment]
For readers: OP says this is different from #15706, which causes the same symptom as described here. Please first consult #15706 before commenting here. Please do not let discussions scatter across issues. Thanks.

**Comment by truboxl** [comment]
I am unconvinced. It was said OP need [arm deb](https://github.com/termux/termux-packages/issues/15706#issuecomment-1477568352) but the termux-info returns aarch64...

Please post `apt info coreutils`.

**Comment by yirod3721** [comment]
Package: coreutils
Version: 9.2-1
Status: install ok installed
Essential: yes
Maintainer: @termux
Installed-Size: 2609 kB
Depends: libandroid-support, libgmp, libiconv
Breaks: chroot, busybox (<< 1.30.1-4)
Replaces: chroot, busybox (<< 1.30.1-4)
Homepage: https://www.gnu.org/software/coreutils/
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /data/data/com.termux/files/usr/var/lib/dpkg/status
Description: Basic file, shell and text manipulation utilities from the GNU project

**Comment by xtkoba** [comment]
I wrote in https://github.com/termux/termux-packages/issues/15706#issuecomment-1477299616:

> Fixed for me with `coreutils` version `9.2-1`.
> 
> If you still see this type of failure, then please share the `strace -f` output of the failing command.

It is pretty much possible that `9.2-1` does not fix #15706 on some device, unfortunately.

**Comment by truboxl** [comment]
> ... please share the strace -f output of the failing command.

**Comment by yirod3721** [comment]
How do I do that and the command is any apt install or apt update command also pkg commands don't work

**Comment by alexfarseer** [comment]
@yirod3721 Are you sure both `mv` and `cp` are working? I ask because this is the exact same error I was getting with `apt update`. But that got fixed with the patched version.

**Comment by truboxl** [comment]
I have a feeling the old kernel version has something to do with it if what OP say is true...

**Comment by yirod3721** [comment]
This is the output of the CP command cp: failed to clone '/data/data/com.termux/files/home/test2.txt' from 'test.txt': Not a typewriter even though it worked a second ago

**Comment by alexfarseer** [comment]
@yirod3721 That means your issue is the same as https://github.com/termux/termux-packages/issues/15706. If the patched `coreutils` did not fix it just patch your `cp` with `busybox cp`. Like this script:

```
#!/bin/bash
busybox cp $@
```

**Comment by yirod3721** [comment]
@alexfarseer i dont know where and how to do what you jut said

**Comment by xtkoba** [comment]
OK I understand. `ENOTTY` is unexpected to the failure handling.

**Comment by yirod3721** [comment]
@xtkoba ?

**Comment by yirod3721** [comment]
so is there even a solution?

**Comment by alexfarseer** [comment]
@yirod3721 Make a directory in your `$HOME` called `bin`. And add this in your `.bashrc` file, `export PATH=~/bin:$PATH`. After that make a file in `~/bin/` called `cp`, and fill that with my script above. Execute `chmod +x cp` and that should fix `apt`.

FYI, this is how I fixed my problem before the patched `coreutils` got released.

**Comment by yirod3721** [comment]
how do i install the new coreutils

**Comment by yirod3721** [comment]
what do i do now?

**Comment by yirod3721** [comment]
@xtkoba can you please assist me as to what to do now?

**Comment by xtkoba** [comment]
Please migrate to #15706.
