### ISSUE TITLE
Package Request mpg123

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1572]
This is a console based decoder/player for mono/stereo mpeg audio files, probably more familiar as MP3 or MP2 files. https://github.com/dreamerc/mpg123 & http://mpg123.org

**Comment by its-pointless** [comment]
Issue is the player needs an android compatible output. So it needs opensles or openal output.  Mpg123 doesn't have that.

**Comment by sdrausty** [comment]
@its-pointless Thanks for your reply. Do you think https://packages.debian.org/source/jessie/aumix is portable to Termux?

**Comment by its-pointless** [comment]
no.
Audio is one of the hard bits of porting things to android. Unless it supports opensles or openal then its very likely not going to work. The only thing that could get stuff like this to work is if someone completed a pulseaudio android output. There was someone working on it but he has gone silent.

**Comment by sdrausty** [comment]
I will close this issue. Once we have a surplus of developers, it surely can be reopened.
