### ISSUE TITLE
need new pkg 

### ISSUE THREAD

**Issue by Mina20000** [termux/termux-packages#1576]
I need pkg driver for rtl8188cu wifi 802.11n I have the hardware I need the driver

**Comment by fornwall** [comment]
I'm sorry, but packaging kernel hardware drivers are outside the scope of Termux!

**Comment by vishalbiswas** [comment]
You have to compile drivers yourself. Drivers need to be built against your exact kernel signature. Providing drivers for each kernel configuration that runs android is practically impossible.
And insmod'ing requires superuser access.

**Comment by Mina20000** [comment]
I don't understand 
I have the Linux driver but I don't know how to install it this is the driver 
https://github.com/CalielOfSeptem/rtl8188cus

**Comment by Grimler91** [comment]
@Mina20000 Have you read the [readme.txt](https://github.com/CalielOfSeptem/rtl8188cus/blob/master/readme.txt)? There seem to be a document called [Quick_Start_Guide_for_Driver_Compilation_and_Installation.pdf](https://github.com/CalielOfSeptem/rtl8188cus/blob/master/document/Quick_Start_Guide_for_Driver_Compilation_and_Installation.pdf), I'm guessing that's a good start.
