### ISSUE TITLE
some WMs not working with virglrenderer-android

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-packages#15784]
It is great that chromium works perfectly with virglrenderer-android (of course, more smooth than using software renderer). 
I want to run a wm with effects(such as kwin and compiz) with virglrenderer, but kwin crashes and compiz also crashes.
Is is possible to make kwin or compiz work with virglrenderer-android?

**Comment by licy183** [comment]
I'm afraid that this is hard. Using virgl as mesa's OpenGL backend will use the device's GPU, and many GL extentions will not be available. Anyway, I'm working on running ANGLE over virgl these days, and hopefully it will have good performance.

**Comment by twaik** [comment]
I thought ANGLE is some sort of software rendering. Will it be faster using ANGLE instead of native GLES implementation in this case?

**Comment by licy183** [comment]
> I thought ANGLE is some sort of software rendering. Will it be faster using ANGLE instead of native GLES implementation in this case?

I don't think ANGLE will make it faster because ANGLE will do some software rendering, but using ANGLE will make it possible to have OpenGL libraries with higher version.

**Comment by anmol-undostres** [comment]
> virglrenderer

How did you run chromium with virgl?

**Comment by kde-yyds** [comment]
> > virglrenderer
> 
> @kde-yyds 
> 
> How did you run chromium with virgl?

chromium just runs with virglrenderer android
no need to do something else

**Comment by kde-yyds** [comment]
> @kde-yyds 
> is it same when running it from xfce?
> when I run it from xfce4 it doesn't show hardware rendering and youtube videos drop lot of frames
>  

on my device chromium's software renderer is even faster

**Comment by anmol-undostres** [comment]
> > @kde-yyds 
> > is it same when running it from xfce?
> > when I run it from xfce4 it doesn't show hardware rendering and youtube videos drop lot of frames
> >  
> 
> on my device chromium's software renderer is even faster

What is your device.. also can you tell me count of dropped frames on YouTube on a 1080p60fps vid?

**Comment by kde-yyds** [comment]
> > > @kde-yyds 
> > > is it same when running it from xfce?
> > > when I run it from xfce4 it doesn't show hardware rendering and youtube videos drop lot of frames
> > >  
> > 
> > on my device chromium's software renderer is even faster
> 
> What is your device.. also can you tell me count of dropped frames on YouTube on a 1080p60fps vid?

youtube is not available in my country
