### ISSUE TITLE
$ man ping man: No entry for ping in the manual.

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#1580]
$ man ping
man: No entry for ping in the manual. 🎁🎄

**Comment by xeffyr** [comment]
Termux uses a wrapper script which calls ping located in /system/bin, so it does not have manpages.

**Comment by sdrausty** [comment]
@xeffyr tnx Q write manpage A texinfo Q add manpage to pull request at?

**Comment by xeffyr** [comment]
Closing as
> Termux uses a wrapper script which calls ping located in /system/bin

and we cannot manage anything under /system/bin. Also no warranty that this command is same on different devices.

Information from `ping -h` should be enough for most cases.
