### ISSUE TITLE
[Package]: zellij

### ISSUE THREAD

**Issue by kyzsuukii** [termux/termux-packages#15822]
### Why do you want to add this package to Termux?

Zellij s a workspace aimed at developers, ops-oriented people and anyone who loves the terminal. Similar programs are sometimes called "Terminal Multiplexers".

### Home page URL

https://github.com/zellij-org/zellij

### Source code URL

https://github.com/zellij-org/zellij

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
`zellij` already in termux-packages.
https://github.com/termux/termux-packages/issues/11857
You can install it via `pkg install zellij` .

**Comment by kyzsuukii** [comment]
> `zellij` already in termux-packages.
> https://github.com/termux/termux-packages/issues/11857
> You can install it via `pkg install zellij` .

not found when installed
`E: Unable to locate package zellij`

**Comment by xtkoba** [comment]
Note that zellij is not available to 32-bit arches due to technical reasons. That message appears if you are using arm arch.
