### ISSUE TITLE
[Bug]: all the commands *-w64-mingw32-clang++ fail

### ISSUE THREAD

**Issue by Duilio12** [termux/termux-packages#15836]
### Problem description

Hello, today I use mingw-w64 to compile some files for Windows. It works for C, but when I use for c++, it fails. I   erased data from termux and reinstalled the package, but the results are same.
![Screenshot_20230326-163548_Termux](https://user-images.githubusercontent.com/78109034/227809095-a099f438-9332-451a-9546-8e67c11a0da1.jpg)

### What steps will reproduce the bug?

I installed the package using pkg

### System information

termux-info:

```

```

**Comment by licy183** [comment]
Yeah, this is a bug. I'll fix it.

**Comment by Duilio12** [comment]
All is working, bat I don't use my libraries such sfml, I use the command x86_64-w64-mingw32-c++ -print-search-dirs and this was the result:
programs: =/data/data/com.termux/files/usr/bin
libraries: =/data/data/com.termux/files/usr/lib/clang/16::/data/data/com.termux/files/usr/opt/llvm-mingw-w64/x86_64-w64-mingw32/lib:/data/data/com.termux/files/usr/opt/llvm-mingw-w64/x86_64-w64-mingw32/mingw/lib:/data/data/com.termux/files/usr/opt/llvm-mingw-w64/lib

But the problem is that my libraries are in /data/data/com.termux/files/usr/lib. Please help me to fix this
