### ISSUE TITLE
[Package]: gnu-which

### ISSUE THREAD

**Issue by joshcangit** [termux/termux-packages#15863]
### Why do you want to add this package to Termux?

The package `debianutils` has noted `which` as deprecated.
There's another package called `gnu-which` which can replace it.
Certain distros such as Arch and Fedora use the GNU variant of `which` by default.

Latest `tar.gz` release can be downloaded from the homepage.
Source code is in a `cvs` repository.

### Home page URL

https://carlowood.github.io/which/

### Source code URL

https://cvs.savannah.gnu.org/viewvc/which/

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I have made a repository to house the built deb packages to try out.
https://github.com/joshcangit/gnu-which-termux

However, I had to modify the `debianutils` package from Termux to use `update-alternatives`.
That is the same functionality as `debianutils` on Debian and Ubuntu.

**Comment by xtkoba** [comment]
We do not use `update-alternatives` here because it is not worth it. Note that `debianutils` is not an essential package. If a package not depending on `debianutils` relies on `which` command, then that is a bug in that package in the first place.

**Comment by joshcangit** [comment]
So that means no more `which` in the `debianutils` package.
Thought it was because the version which uses the Bash script can be replaced by another which is a binary executable.

No problem, any code that relied on `which` has to be rewritten.
Shouldn't be difficult to do so.
