### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zainali45** [termux/termux-packages#15878]
### Problem description

Signal 9 error termux automatically kill vncserver 

### What steps will reproduce the bug?

Phantom killing process in Android 

### What is the expected behavior?

vncserver run and kali is connected but after 5 to 20minutes it kills automatically and showing unexpectedly error

### System information

termux-info:

```
Kex vncserver
![Screenshot_20230331_165943_com offsec nethunter kex](https://user-images.githubusercontent.com/129515394/229119071-6a62eb09-310a-4c0b-80ff-7bf05a90cedf.jpg)

```

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking
