### ISSUE TITLE
Bug when I run apt update && apt upgrade

### ISSUE THREAD

**Issue by DexSpecial** [termux/termux-packages#15893]
### Problem description

When I run apt update && apt upgrade I get those error messages

Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Get:2 https://termux.mentality.rip/termux-packages-24 stable InRelease [14.0 kB]
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  404  Not Found
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  404  Not Found
Get:6 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 Packages [496 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

### What steps will reproduce the bug?

Run the commands; apt update && apt upgrade

### What is the expected behavior?

It should update and upgrade my app

### System information

termux-info:

```
Packages CPU architecture:
aarch64
Android version:
13
Kernel build information:
Linux localhost 4.14.190-25316417-abA715FXXU8DVK3 #1 SMP PREEMPT Thu Nov 17 23:59:26 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A715F
```

**Comment by xtkoba** [comment]
#6726.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation

https://github.com/termux/termux-app#google-play-store-deprecated
