### ISSUE TITLE
[Package]: zxtune

### ISSUE THREAD

**Issue by GUUser91** [termux/termux-packages#15902]
### Why do you want to add this package to Termux?

This is required for psf conversion to work on vgm2flac

### Home page URL

https://bitbucket.org/zxtune/zxtune/src

### Source code URL

https://bitbucket.org/zxtune/zxtune/src

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
This package has no license.
