### ISSUE TITLE
[Bug]: Error while installing greenlet package on Termux using pip

### ISSUE THREAD

**Issue by kyzsuukii** [termux/termux-packages#15911]
### Problem description

While trying to install the greenlet package using pip on Termux, the following error occurred:
```
src/greenlet/platform/switch_arm32_gcc.h:54:16: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
      __attribute__((optimize("no-omit-frame-pointer")))
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/greenlet/platform/switch_arm32_gcc.h:59:9: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
              register int *stackref, stsizediff;
              ^~~~~~~~~
      src/greenlet/platform/switch_arm32_gcc.h:59:9: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
              register int *stackref, stsizediff;
              ^~~~~~~~~
      1 warning and 2 errors generated.
      error: command '/data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1
      [end of output]
```
This error seems to originate from a subprocess and is likely not a problem with pip. The error message suggests that the ISO C++17 standard does not allow the 'register' storage class specifier used in the code.

I have previously installed this package and it worked fine. However, it is not working anymore. Please help me resolve this issue.

### What steps will reproduce the bug?

`pip install greenlet`

### What is the expected behavior?

greenlet is installed

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/com.termux-V-_tZ0GW7JiOVlhmWMkytw==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=24889
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c204,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c204,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10204
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirror.termux.dev/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
10
Kernel build information:
Linux localhost 4.9.200-DoraKernel_3.0+ #1 SMP PREEMPT Wed Jun 29 17:47:34 UTC 2022 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 6A
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
Use another standard such as

```bash
export CXXFLAGS+=" -std=c++14"
```

or omit the `register` keywords from source.

If C++17 is specified by upstream then this is an upstream bug. You may want to report upstream.

**Comment by kyzsuukii** [comment]
> Use another standard such as
> 
> ```shell
> export CXXFLAGS+=" -std=c++14"
> ```
> 
> or omit the `register` keywords from source.
> 
> If C++17 is specified by upstream then this is an upstream bug. You may want to report upstream.

![Screenshot_20230402-215620_Termux](https://user-images.githubusercontent.com/110718021/229357497-fe6f1e7d-891d-481b-8188-e2fb8e772bcc.png)

![Screenshot_20230402-215624_Termux](https://user-images.githubusercontent.com/110718021/229357513-4384d563-fa20-4abc-8e19-d6cfb744d4a8.png)

still same

**Comment by xtkoba** [comment]
`clang++-16` defaults to C++17. If the package does not accept custom flags, then there is no way to fix this other than using another C++ compiler. I don't know but maybe TUR archives older Clang/LLVM packages?

Please also report this upstream: https://github.com/python-greenlet/greenlet/issues. Thanks.

**Comment by xtkoba** [comment]
I would use a `CXX` wrapper though.

```sh
#!/bin/sh
exec clang++ -std=c++14 "$@"
```

**Comment by Biswa96** [comment]
> Please also report this upstream: https://github.com/python-greenlet/greenlet/issues. Thanks.

There is a pull request in upstream https://github.com/python-greenlet/greenlet/pull/347

**Comment by xtkoba** [comment]
Use our `python-greenlet` package if needed. Thanks.
