### ISSUE TITLE
gdrive (google drive) on termux

### ISSUE THREAD

**Issue by remo7777** [termux/termux-packages#1593]
if it is possible to upload "file" directly to our Google drive through termux then life will be easier for us..
building a package like that..😍😍
# Thank you..

**Comment by Grimler91** [comment]
A really quick google search found me the python package [PyDrive](https://pypi.python.org/pypi/PyDrive), try that. Install through pip.

**Comment by Neo-Oli** [comment]
The best tool for that is [rclone](http://github.com/ncw/rclone). I've been using it for quite some time now and it works great on Termux.
```
apt install golang git
go get github.com/ncw/rclone
```

**Comment by remo7777** [comment]
ok i ll try @Grimler91  thank you..

**Comment by remo7777** [comment]
rclone also i ll try.. thank you @Neo-Oli
