### ISSUE TITLE
[Package]: Add F-droid repomaker package

### ISSUE THREAD

**Issue by mesflit** [termux/termux-packages#15940]
### Why do you want to add this package to Termux?

Add f-droid repomaker package

### Source code URL

https://gitlab.com/fdroid/repomaker.git

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Seems like somehow necessary to resolve dependency manually. Other than that, repomaker is installable through pip:

```bash
pip install repomaker
```

Use our `python-libsass` package for libsass module which does not build without patching.
