### ISSUE TITLE
Package request: gmpy2 

### ISSUE THREAD

**Issue by sutharsha** [termux/termux-packages#1596]
pip install gmpy2 is throwing the following error

Collecting gmpy2
  Using cached gmpy2-2.0.8.zip
Installing collected packages: gmpy2
  Running setup.py install for gmpy2 ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-hiqg4vtj/gmpy2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-ofcl1ss4-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'gmpy2' extension
    creating build
    creating build/temp.linux-aarch64-3.6
    creating build/temp.linux-aarch64-3.6/src
    aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Oz -Oz -fPIC -DWITHMPFR -DWITHMPC -I/data/data/com.termux/files/usr/include/python3.6m -c src/gmpy2.c -o build/temp.linux-aarch64-3.6/src/gmpy2.o
    In file included from src/gmpy2.c:426:
    src/gmpy.h:106:12: fatal error: 'gmp.h' file not found
    #  include "gmp.h"
               ^~~~~~~
    1 error generated.
    error: command 'aarch64-linux-android-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-hiqg4vtj/gmpy2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-ofcl1ss4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-hiqg4vtj/gmpy2/

**Comment by sutharsha** [comment]
already installed libgmp btw

**Comment by Neo-Oli** [comment]
Try installing `libgmp-dev`. `-dev` packages usually contain the header files.

**Comment by sutharsha** [comment]
nice, thx @Neo-Oli also had to install libmpfr-dev and libmpc-dev tho.
