### ISSUE TITLE
[Package]: typst-lsp

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-packages#15975]
### Why do you want to add this package to Termux?

Language server for typst. Useful for every editor which support LSP.

### Source code URL

https://github.com/nvarner/typst-lsp

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Manik04IISER** [comment]
Is there any update?

**Comment by TomJo2000** [comment]
Huh, was this not packaged along with `typst` itself?
I'll give it a look, shouldn't be too bad to package.

**Comment by Manik04IISER** [comment]
Ig a typst app exists, but nvim is just better than that. But if you can, do so, it will really be helpful

**Comment by TomJo2000** [comment]
@Manik04IISER got it building, wasn't anything too difficult,
but I couldn't get it to build with `--features native-tls`
so we're just building with the default `rustls-tls` which is probably fine.

I'd like to request you to test this package once [the CI run](https://github.com/termux/termux-packages/actions/runs/7673676417?pr=19071) is finished, DEBs will be available from the artifacts section.

> [!TIP]
> To install a local DEB from a CI
> Use `pkg i /path/to/artifact.deb`
> i.e `pkg i ./typst-lsp.deb`

I unfortunately don't have the time or expertise to properly evaluate the functionality of the package.
But I'd like a cursory check before this is ready to be merged.

**Comment by Manik04IISER** [comment]
It's been fine for me

**Comment by TomJo2000** [comment]
I'll probably merge it tomorrow if there is no further objections.

**Comment by Manik04IISER** [comment]
Yup. And thanks !!!!
