### ISSUE TITLE
Error installing localtunnel using npm command

### ISSUE THREAD

**Issue by Mustafa5798** [termux/termux-packages#1597]
I tried to install localtunnel on termux using command npm for package nodejs but this problem arised 
`bash-4.4$ npm install -g localtunnel
Unhandled rejection Error: EACCES: permission denied, link '/data/data/com.termux/files/home/.npm/_cacache/tmp/f726f9d0' -> '/data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/a9/4a/a30c410a9f5442083cb369afc1ce2ab1abf4f4888ce02d3d1c14ff7aadbf275e75fdebb0fa393ebf09f7f846ea8eaf9f6ca2101b2368e38a61d75a92e39c'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2017-09-28T22_02_23_843Z-debug.log
bash-4.4$ 
`
How to handle such a problem !!!

**Comment by sdrausty** [comment]
https://github.com/npm/npm/issues/19239

**Comment by SamSanuch** [comment]
@sdrausty do you have admin rights in termux package?

**Comment by Quasic** [comment]
Also npm/npm#19170

**Comment by Quasic** [comment]
#1192 might be relevant
