### ISSUE TITLE
[Package]: jq-lsp

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-packages#15970]
### Why do you want to add this package to Termux?

jq language server provides many useful functions of jq language develop for every editor which support language server protocol. 

### Home page URL

https://github.com/wader/jq-lsp

### Source code URL

https://github.com/wader/jq-lsp

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
> Packages must be active, well-known projects
> Software available in major Linux distributions has more chances to be included into Termux repositories. We will not accept outdated, dead projects as well as projects which do not have active community.
I think it should be packaged into [TUR](https://github.com/termux-user-repository/tur) .
