### ISSUE TITLE
[Bug]: ettercap build failure

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#15986]
### Problem description

/home/builder/.termux-build/ettercap/src/plug-ins/sslstrip/sslstrip.c:57:2: error: libcurl 7.26.0 or up is needed
#error libcurl 7.26.0 or up is needed

[ettercap.zip](https://github.com/termux/termux-packages/files/11162800/ettercap.zip)

https://github.com/johndebia2022/termux-packages/actions/runs/4622503668/jobs/8175267011

### What steps will reproduce the bug?

build 

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
https://github.com/Ettercap/ettercap/commit/40534662043b7d831d1f6c70448afa9d374a9b63

**Comment by johndebia2022** [comment]
I would suggest that you increase the package revision after every update/patch/fix
