### ISSUE TITLE
Android app source code

### ISSUE THREAD

**Issue by valerio-bozzolan** [termux/termux-packages#16]
Sorry me, I have not found the source code of your Android app.

Is it released? Have you planned a release?

Your project can be really appreciated in [F-Droid](https://f-droid.org).

**Comment by fornwall** [comment]
I'm planning on releasing the app source code soon, but need to untangle the parts of the source code shared with other (non-android) projects and decide on a license first. I guess F-Droid is fine with most major open source licenses?

Will update this issue when there is something to show!

**Comment by valerio-bozzolan** [comment]
The [license compatibility](http://www.gnu.org/licenses/quick-guide-gplv3.en.html#new-compatible-licenses) section at GNU.org it's a good place to start when you have to choose the right license for your project and when you have to respect a lot of software license terms, from third-part software that you are using.

Personally I really love the *GNU General Public License* because I really don't want that someone may steal my code and sell it without sharing his modifications with me.

In any case F-Droid is fine with every Free software license. They are only really strict on don't have any uncompilable binary file in the source code. When all the source code has no hidden features it's pratically approved.

**Comment by fornwall** [comment]
Hi, the source code for the Termux app is now available at https://github.com/termux/termux-app under the GPLv3 license!

**Comment by valerio-bozzolan** [comment]
Thanks @fornwall, I'm very happy to hear that! :+1:

**Comment by mvdan** [comment]
Thanks for publishing the source, @fornwall! Working on adding it to F-Droid now.

**Comment by mvdan** [comment]
Added, should be available at https://f-droid.org/app/com.termux tomorrow.

@fornwall if you tag releases, updates will be picked up and built by F-Droid daily.

**Comment by fornwall** [comment]
@mvdan I created a tag for v0.17 (should be almost the same as the v0.16 one at the Play Store, but from the new github repo) at https://github.com/termux/termux-app/releases/tag/v0.17 - is that enough for F-Droid to pick it up?

**Comment by mvdan** [comment]
Yup, I'll set up auto updates with tags tomorrow once the 0.16 build succeeds :)

**Comment by fornwall** [comment]
@mvdan Great, let me know if there is anything I can do to help!
