### ISSUE TITLE
Need php-mysql package

### ISSUE THREAD

**Issue by kcfinished** [termux/termux-packages#1600]
I try to develop the LAMP stack and found that my php code which tried to access mysql (actually mariadb) throwed this "Call to undefined function mysqli_init()"

so I think I should install something like 'php-mysql' but cound not found on 'pkg list-all'

**Comment by Neo-Oli** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/630

**Comment by alo0oz** [comment]
No php-mysql package is aavailable now.
