### ISSUE TITLE
Flask gets stuck at debugging is active when debug = True

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#1601]
My code : 

ute('/')
def hello() -> str:
        return "Hello world"

                                                 @app.route('/search4', methods = ['POST'])

def do_search() -> str:
    phrase = request.form['phrase']
    letters = request.form['letters']
    return phrase,letters

@app.route('/entry')
def page() -> 'html':                                    return render_template('entry.html',the_title = 'Welcome !!!')

app.run(debug=True)

--Now in terminal

python web.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!

The page hangs in chrome without loading anything.

**Comment by wdscxsj** [comment]
This doesn't seem like a termux issue. Flask's built-in server by default serves requests one-by-one (http://flask.pocoo.org/docs/0.12/deploying/). You may want to try a container like gevent or something (http://flask.pocoo.org/docs/0.12/deploying/wsgi-standalone/).

**Comment by suryapoo** [comment]
It runs perfectly when I remove debug=True

**Comment by michalbednarski** [comment]
See comments on #279

Basically, workaround is:
```
rm /data/data/com.termux/files/usr/bin/ip
```

You can undo above command with:
```
pkg install --reinstall termux-tools
```

**Comment by suryapoo** [comment]
Cool..so should I close this ?

**Comment by gordol** [comment]
Isn't this fixed upstream now?

Do we need a new python package for termux?

https://bugs.python.org/issue27057

**Comment by michalbednarski** [comment]
That is different fix (for bug which prevented Flask from working altogether; I've said that *comments* on that pull request were relevant)

This isn't bug in python, this is problem with `ip` command built in Android

**Comment by gordol** [comment]
I am presently running a Flask app and it works just fine with debug enabled.

Chrome OS: Version 61.0.3163.110 (Official Build) beta (64-bit)

**Comment by gordol** [comment]
It's using Android 7.1.1 also, if that helps.

**Comment by Sid352** [comment]
> It runs perfectly when I remove debug=True
> 
> Tried on Chrome,opera, Firefox on a Nexus 5

I tried the same thing but it is still loading and I ain't getting any graph

**Comment by ch-monish** [comment]
if __name__=='__main__':
	app.run(debug=True)
if we add this code we can run in debug mode
