### ISSUE TITLE
Segmentation Fault Taskwarrior

### ISSUE THREAD

**Issue by fabsir06021982** [termux/termux-packages#1602]
Since today every time when i want to execute the command task from the taskwarrior package i get the message Segmentation fault.
What to do?

**Comment by fornwall** [comment]
1. Which arch is this one (what is the output of `uname -m`)?
2. Which Android version?
3. Does the problem remain if you update to latest version of all packages with `pkg up`?

**Comment by bumper314** [comment]
FYI, I thought this might be related to #1617, but `task` is working fine on my armv71 and aarch64 devices.

**Comment by sdrausty** [comment]
Task warrior works in Termux.  When users fail to reply to requests for information...

![screenshot_20171203-083345](https://user-images.githubusercontent.com/27742457/33525815-e1eb0ed6-d804-11e7-800c-d0997d5d93c2.png)

Android 6 stock
