### ISSUE TITLE
[Bug]: pyarrow.__version__ not defined

### ISSUE THREAD

**Issue by rockwalrus** [termux/termux-packages#16047]
### Problem description

`pyarrow`'s `__init__` script can't import the version number from `._generated_version` and so it sets the version to `None`.

I worked around this by manually setting the version number in `/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyarrow/__init__.py` line 59 to `"11.0.0"`.

### What steps will reproduce the bug?

```
~ $ pkg install python-pyarrow
~ $ pip install datasets
```
... _Fight epic battle to install dependencies_ ...
```
~ $ datasets-cli                                        
Traceback (most recent call last):                        
  File "/data/data/com.termux/files/usr/bin/datasets-cli", line 5, in <module>                                      
    from datasets.commands.datasets_cli import main     
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/datasets/__init__.py", line 33, in <module>
    if version.parse(pyarrow.__version__).major < 8: 
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^             
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^                           
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/packaging/version.py", line 195, in __init__                                                       
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
TypeError: expected string or bytes-like object, got 'NoneType'
```

### System information

termux-info:

```

```
Termux Variables:                                       TERMUX_APK_RELEASE=F_DROID                              TERMUX_APP_PACKAGE_MANAGER=apt                          TERMUX_APP_PID=6108                                     TERMUX_IS_DEBUGGABLE_BUILD=0                            TERMUX_MAIN_PACKAGE_FORMAT=debian                       TERMUX_VERSION=0.118.0                                  Packages CPU architecture:                              aarch64                                                 Subscribed repositories:                                # sources.list                                          deb https://dl.kcubeterm.com/termux-main stable main    Updatable packages:                                     All packages up to date                                 termux-tools version:                                   1.37.0                                                  Android version:                                        13                                                      Kernel build information:                               Linux localhost 5.10.107-android13-4-00020-g02b5dfab573c-ab9358130 #1 SMP PREEMPT Thu Dec 1 18:28:18 UTC 2022 aarch64 Android                                           Device manufacturer:                                    Google                                                  Device model:                                           Pixel 6                                                 LD Variables:                                           LD_LIBRARY_PATH=                                        LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by xtkoba** [comment]
Dev memo. Workaround when packaging:

```bash
echo "version = ${TERMUX_PKG_VERSION#*:}" \
> $TERMUX_PYTHON_HOME/site-packages/pyarrow/_generated_version.py
```

Seeking for proper fix.
