### ISSUE TITLE
Termux ffmpeg live stream not working 

### ISSUE THREAD

**Issue by mdsohag017** [termux/termux-packages#16045]
### Problem description

**Please Solution**

I don't know much about noob termux so I do everything from what I see online

Why can't you install ffmpeg on Termux app **without root** and connect server using rtmp url & key and go live?

**Command shows this problem again and again** 👇👇

Cannot read RTMP handshake response

And the videos on the **phone** with **Termux app** or
Is there any other good system to live from online video link?

**Nginx can be live with Termux app by installing rtmp**

 Is there any **system to live from video link for Termux app**
Which system can be **live using facebook and youtube rtmp url & key**

### What steps will reproduce the bug?

I want to know how to live video on Facebook and YouTube with ffmpeg through Termux app with non rooted phone

The live will be done with the video on the phone or video link from online for example like gosteam app like this 

And tell me if there is any other free system 

### System information

termux-info:

```
Letest Termux app 
```

**Comment by harieamjari** [comment]
What steps will reproduce the bug?

**Comment by xtkoba** [comment]
Output of `termux-info` command cannot be "Letest Termux app" though it may be irrelevant in this specific issue.

As a matter of fact, in our `ffmpeg` package librtmp support is not enabled. But I have no idea if that is the point, as no repro is provided.

As for RTMP protocol, `rtmpdump` command (from the package of the same name) can handle it and it may be worth trying it.
