### ISSUE TITLE
[Bug]: avahi ssh and sftp services use the wrong port

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#16057]
### Problem description

the default service files, ssh.service and sftp.service, contain the wrong port of 22:
`<port>22</port>`

### What steps will reproduce the bug?

pkg in avahi

### What is the expected behavior?

Termux's sshd runs on 8022 by default

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=4178
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
11
Kernel build information:
Linux localhost 4.4.223-g52750b8f2138-ab6846512 #1 SMP PREEMPT Fri Sep 18 09:49:34 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 2
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

```

**Comment by TomJo2000** [comment]
Android restricts Ports below 1024.
As such Termux's SSHD defaults to using Port 8022.
It is working as intended.

**Comment by sudomain** [comment]
Tangentially related: Does anyone have a working avahi/sshd setup working on Termux? I want just to be able to ssh into my phone from a machine on the same LAN. After correcting the port number and running avahi-daemon with default settings, I can't even connect to localhost using the following command and get the following error:

`$ ssh -p8022 linux.local
ssh: Could not resolve hostname linux.local: No address associated with hostname`

I haven't used avahi outside of Termux and I'm wondering if my address isn't formatted correctly. I thought it would be because avahi-daemon running in the foreground told me `Host name is linux.local`

**Comment by xtkoba** [comment]
@2096779623 "packaging" label is basically used for issues not affecting end users. Not suitable for this issue.
