### ISSUE TITLE
[Package]: Multi-platform Linux user space API headers

### ISSUE THREAD

**Issue by matheusmoreira** [termux/termux-packages#16069]
### Why do you want to add this package to Termux?

Linux UAPI headers are necessary for building software that interfaces directly with the Linux kernel. One example of such software is the standard C library.

The kernel headers for the Linux that Termux runs on top of are already provided in the following locations:

```
"${PREFIX}"/
    include/
        linux
        asm
        asm-generic
```

It would be nice to have Linux UAPI headers for other architectures as well, especially `x86_64`.

Termux already offers user mode `qemu` for numerous architectures as well as `clang` which has native cross compilation support. With these headers, I'd be able to cross compile and test my projects to any of those architectures without ever leaving Termux.

References:

 - [Exporting kernel headers for use by userspace][1]
 - [Arch Linux package][2]
 - [Debian package][3]

[1]: https://www.kernel.org/doc/html/latest/kbuild/headers_install.html

[2]: https://archlinux.org/packages/core/any/linux-api-headers/

[3]: https://packages.debian.org/sid/linux-headers-amd64

### Home page URL

https://www.kernel.org/

### Source code URL

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

The Arch Linux package is built with `make`:

```
make INSTALL_HDR_PATH="$pkgdir/usr" headers_install
```

**Comment by matheusmoreira** [comment]
@sylirre
> The headers provided in Termux are supplied by Android NDK.

That's true, I noted this in the issue. It appears Bionic libc provides those headers. I'm already using them.

The packaging request is for the Linux headers of other architectures. Those don't have to match the currently running kernel at all. It would make it a lot easier to cross compile software.

**Comment by xtkoba** [comment]
I cannot get the point. There already exist `$PREFIX/include/${triple}/asm`s in `ndk-sysroot` package (where `triple=x86_64-linux-android` for example.) It is true that `ndk-sysroot` package is platform-specific but I don't see any evidence of it excluding any non-native headers.

**Comment by xtkoba** [comment]
I'd like to mention that unlike in the description `$PREFIX/include/asm` does not exist in my Termux environment (where `ndk-sysroot` is already installed.)
