### ISSUE TITLE
QPython

### ISSUE THREAD

**Issue by AyeshaShafique** [termux/termux-packages#1607]
How to install Scipy package of python on android?
Could anyone help me? IT IS URGENT !

**Comment by Grimler91** [comment]
See https://wiki.termux.com/wiki/Installing_Scipy_The_Easy_Way.

**Comment by AyeshaShafique** [comment]
I couldn't install the scipy using pip in android ? Could you tell me what to do?

**Comment by Grimler91** [comment]
Scipy requires Fortran which so far isn't available with clang, so no, it not possible to install it with pip. Only way to get it is through its-pointless repo, see the instructions in the link I gave you.

This question has been raised a couple of times before, see for example https://github.com/termux/termux-packages/issues/471.

**Comment by Grimler91** [comment]
Also, please not that this repo is for the [linux terminal emulator termux](https://termux.com), for android. It has nothing to do with the android app qpython.

**Comment by Grimler91** [comment]
Looks like you've opened a duplicate issue at https://github.com/qpython-android/qpython.org/issues/178
