### ISSUE TITLE
Package request: vifm

### ISSUE THREAD

**Issue by shfrs** [termux/termux-packages#1608]
Vifm is an ncurses based file manager with vi like key bindings. It will be a good alternative of ranger.
https://github.com/vifm/vifm

**Comment by sdrausty** [comment]
👍

**Comment by its-pointless** [comment]
check it...
#1612

**Comment by sdrausty** [comment]
I'm trying to install docker in Termux. Any suggestions? I have found success https://wiki.termux.com/wiki/Proot 🔹 but not fruition.

**Comment by sdrausty** [comment]
Do I really need docker? What alternatives do we have in Termux?

**Comment by its-pointless** [comment]
none it requires features not found in normal android linux kernel.

**Comment by shfrs** [comment]
Just tested it on i686, I didn't notice any possible bug/errors. 👍

**Comment by fornwall** [comment]
Thanks to @its-pointless the package is now available for installation with `pkg install vifm`!
