### ISSUE TITLE
error about, ps, top, htop, on android ( 7.0 aarch64) 

### ISSUE THREAD

**Issue by remo7777** [termux/termux-packages#1611]
not showing system android background processes, help me plz...😭😭😭
![screenshot_20171003-185317](https://user-images.githubusercontent.com/28594846/31139932-af1bc2d2-a890-11e7-9e5a-48d10dba7363.jpeg)
![screenshot_20171003-230541](https://user-images.githubusercontent.com/28594846/31140019-dd7810a4-a890-11e7-98f8-82891e3f8c04.jpeg)

**Comment by remo7777** [comment]
working on my another phone android ( marshmallow  aarch64)...

**Comment by its-pointless** [comment]
Yes thats due to android 7 no longer allowing it. Nothing we can do.

**Comment by remo7777** [comment]
and for root user; can giv that permission on termux ??

**Comment by its-pointless** [comment]
there is a package called tsu
running that command should put you into root mode and able to use termux stuff
