### ISSUE TITLE
pforth segmentation fault

### ISSUE THREAD

**Issue by bumper314** [termux/termux-packages#1617]
pforth isn't behaving properly (confirmed on 3 devices):

- When run without arguments, pforth seg faults.
- When run with the -i argument, pfroth runs, but it's a highly stripped down (useless) environment.

I'm able to build the same commit of pforth on my Mac, and it works as expected.
Let me know if I can do more to help.

**Comment by stephengroat** [comment]
@bumper314 have you run `pkg up` to make sure that everything is up to date?

**Comment by its-pointless** [comment]
Well i don't know much about forth but did manage to compile gforth on device. If you could tell me the arch of your device (uname -m) i could use someone who does use forth for some testing?

**Comment by bumper314** [comment]
@stephengroat Yes, all up to date or freshly installed yesterday/today.

@its-pointless Just installed on a 4th device and pforth works, so here's the breakdown:

- **Worked**
  - LG VK815 (aarch64)
- **Failed**
  - Nexus 5 (armv71)
  - Nexus 6 (armv71)
  - Samsung Note Pro 12 (armv71)

Happy to test.  I wasn't able to get the Docker dev env setup for testing, but I can try suggestions on-device.

**Comment by its-pointless** [comment]
https://github.com/its-pointless/its-pointless.github.io/raw/master/files/dists/termux/extras/binary-arm/gforth_0.7.3_arm.deb

**Comment by its-pointless** [comment]
i can get pforth to work on arm by compiling pforth on device. So at the very least that should work.

**Comment by bumper314** [comment]
I'm able to build the pforth source on device and it runs correctly, so perhaps their's an issue with the [build script](https://github.com/termux/termux-packages/blob/master/packages/pforth/build.sh).

I'm unable to install the debs due to [unresolvable dependencies](https://gist.github.com/bumper314/d41e622100c12b8685212b6754795564), but those also appear to be [gforth](https://github.com/termux/termux-packages/issues/231) instead of pforth.

Any other thoughts as to why building natively works vs the package?  Perhaps a cross-compiler issue?

**Comment by its-pointless** [comment]
oh i messed that up i will fix that now

**Comment by its-pointless** [comment]
regarding why it works built on device and not cross compiled?

could be one of many different reasons.
the compilers are not quite the same is one answer.  The compilers we use on device are not ndk sources but upstream llvm. After looking at things cross compiling forth is a strange thing as well...

**Comment by its-pointless** [comment]
K solved this with pull request 1804

**Comment by fornwall** [comment]
The PR is now merged and the fixed package is available as an update - nice work!

**Comment by bumper314** [comment]
Confirmed fix on both 32 and 64-bit  devices.  Thanks!
