### ISSUE TITLE
[Package]: time

### ISSUE THREAD

**Issue by kawanakaiku** [termux/termux-packages#16216]
### Why do you want to add this package to Termux?

To measure CPU, memory resource usage of a program.

### Home page URL

https://www.gnu.org/software/time

### Source code URL

https://ftp.gnu.org/gnu/time/time-1.9.tar.gz

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by landfillbaby** [comment]
it does exist on termux as bash builtin, but not as separate executable. do you need it outside of bash?

**Comment by kawanakaiku** [comment]
builtin one is just for measuring time and cannot be used to measure CPU or memory usage.

**Comment by landfillbaby** [comment]
just checked and my /system/bin/time doesn't do cpu usage either

**Comment by kawanakaiku** [comment]
Add ```-v``` argument to see detailed information.

**Comment by landfillbaby** [comment]
```sh
$ ./bin/time -v echo

Real time (s): 0.014432
User time (s): 0.010570
System time (s): 0.003553
Max RSS (KiB): 3504
Major faults: 0
Minor faults: 381
File system inputs: 0
File system outputs: 0
Voluntary context switches: 0
Involuntary context switches: 1
```
working on a PR with full-featured `time` as i'd like this too :)

**Comment by TomJo2000** [comment]
Huh so by the looks of it this is a more capable version of `Bash` (or `Zsh`)'s `time` built-in?
This would definitely be useful to have on Termux.

**Comment by landfillbaby** [comment]
btw see also: [bash $TIMEFORMAT](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-TIMEFORMAT). you can do CPU percentage with that too, but not I/O and stuff like the command

**Comment by TomJo2000** [comment]
Zsh's [`$TIMEFMT`](https://linux.die.net/man/1/zshparam#:~:text=TIMEFMT) seems to largely cover the usecase for this package.
Although not 100% I believe, and the standalone package is still good to have.
