### ISSUE TITLE
[Bug]: texlive-installer points at nonexistent repo

### ISSUE THREAD

**Issue by davidpiano** [termux/termux-packages#16234]
### Problem description

The `texlive-installer` package provides `termux-install-tl`, which is a Termux-specific script that runs texlive's own `install-tl` while applying the modifications Termux needs to make everything run correctly.

By default, Texlive's `install-tl` downloads from whatever is the latest repo on the texlive servers. Texlive builds a brand new repo once per year, and puts the old one into the archives. Therefore, Termux's package `texlive-installer` is guaranteed to go out of date once per year, because the repo it points at will disappear.

### What steps will reproduce the bug?

1. Wait until the middle of April. :)
2. `pkg install texlive-installer`
3. `termux-install-tl`
4. Press `c` to run the install script.
5. See it complains about the mismatched repo.

### What is the expected behavior?

`termux-install-tl` should complete its tasks successfully.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=9851
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://plug-mirror.rcac.purdue.edu/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.36.1
Android version:
13
Kernel build information:
Linux localhost 4.19.125-25915284 #1 SMP PREEMPT Mon Feb 20 17:35:27 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A716U1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by rallg** [comment]
This is because TeXlive is now in edition 2023, and the repos are all 2023. But Termux remains with 2022, so its installer points to the 2022 repos (which are not lonline anymore).

Many have complained to TUG (the TeX folks) and CTAN about this, for years. Each year, there is an interval when year N installations cannot install or update packages, because the repos are at N+1. In some places, TeX is maintined over a newtork by a sysadmin, who may not make the change for months.

It does not help to get the 2023 installer directly from TUG, because it will attempt to install non-Termux binaries (if any), then complain when it cannot run them.

On a related note, when can we expect Termux to have the 2023 binaries and installer?

**Comment by davidpiano** [comment]
> This is because TeXlive is now in edition 2023, and the repos are all 2023. But Termux remains with 2022, so its installer points to the 2022 repos (which are not lonline anymore).
> ...
> On a related note, when can we expect Termux to have the 2023 binaries and installer?

I thought I had already said this, more or less. :)

**Comment by davidpiano** [comment]
Closed by finger slip, not intentionally

**Comment by rallg** [comment]
It is possible to use TeXlive 2023 packages with the Termux texlive-bin
2022 binaries. Do not do this unless you are an experienced TeX user who
can solve problems (I have not encountered any). This assumes you already
have Termux texlive-bin installed.

1. Your existing TeXlive packages are in Termux $PREFIX/share/texlive.
Re-name that directory to $PREFIX/share/texlive2022. Then, if something
goes wrong, you can restore it.

2. Get the TeXlive installer from tug.org. It is install-tl-unx.tar.gz.
Unpack it: tar-xzf install-tl-unx.tar.gz

3. Enter the install-tl-<date> directory.
Run the installer: perl ./install-tl

4. You will see the familiar TexLive installer menu. Its binaries are wrong
for Termux, but allow them to be installed (they do not go into
$PREFIX/bin, and can be discarded later). Select as many or as few
collections as you need. You must change the installation directories.
The main directory, where texmf-dist is installed, should be changed to
/data/data/com.termux/files/usr/share/texlive. That wil also change where
some other TeX directories are placed. If you wish, change the user directories.

5. Do not add symlinks to the usual locations.

6. Do not place the newly-installed binaries on PATH. Continue using the
Termux binaries. Indeed, you may discard the newly-installed binaries.

7. In your home directory, create a .bashrc file with these lines:
export TEXMFROOT="$PREFIX/share/texlive"
export TEXMFOS="$TEXMFROOT"
export TEXMFDIST="$TEXMFROOT/texmf-dist"
export TEXMFLOCAL="$TEXMFROOT/texmf-local"

8. Logout of Termux, login.

9. Run a test file, to see if all is OK. You may need to install more packages
using the tlmgr program.

10. It is possible that some recently-updated packages require 2023 binaries.
But I have tested with lualatex and fontspec, which are under continued
development. They work. If you are creating PDF with Accessibility enhancement,
that might be an area where you need the newer binaries.

11. I expect that when Termux upgrades texlive-bin to 2023, it will not be
necessary to do anything else. Hopefully.

**Comment by davidpiano** [comment]
Thanks - I no longer have those files that should still be existing, that's part of my problem.

**Comment by rallg** [comment]
You do not need any pre-existing files. Begin at the beginning (that's a very good place to start, as the song goes). Install `texlive-bin`. Do not use the Termux TeXlive installer. Get the installer from TUG, as described above. And away you go....

**Comment by YijunYuan** [comment]
Just curious, why texlive-installer is not designed to install the latest version of texlive from tlnet automatically? Is there a reason that we have to hard-coding the version number?

**Comment by Grimler91** [comment]
Ah, it's this time of year again, I'll look at it

**Comment by rallg** [comment]
As for the patches: That is why I export environmental variables in my `~.bashrc` file. According to TeXlive documentation, any variables defined there will add to places where `kpathsea` looks for things (maybe even over-rides the defaults). I did not need to patch vanilla TeXlive when I changed it.

**Comment by Grimler91** [comment]
> As for the patches: That is why I export environmental variables in my `~.bashrc` file. According to TeXlive documentation, any variables defined there will add to places where `kpathsea` looks for things (maybe even over-rides the defaults). I did not need to patch vanilla TeXlive when I changed it.

This is a good tip, thanks! I'll see if we can add TEXMFROOT and friends to the texlive.sh profile script and thereby prevent breakage every time texlive-infra is updated

**Comment by rallg** [comment]
If a user has previously hacked the combination of texlive-bin 2022, with TeXlive packages 2023 (as described above): When upgrading to texlive-bin 2023 (today), there may be an issue with formats. If a known-good `*tex` file now fails, with complaint about not finding the format, simply rebuild the formats:
```
fmtutil-sys --all
```

**Comment by davidpiano** [comment]
> > As for the patches: That is why I export environmental variables in my `~.bashrc` file. According to TeXlive documentation, any variables defined there will add to places where `kpathsea` looks for things (maybe even over-rides the defaults). I did not need to patch vanilla TeXlive when I changed it.
> 
> This is a good tip, thanks! I'll see if we can add TEXMFROOT and friends to the texlive.sh profile script and thereby prevent breakage every time kpathsea is updated

From the point of view of ConTeXt, it would be nice (but not vital) to set OSFONTDIR to include the usual font directories of both the system and the user (or just the system one, whatever is considered proper policy). (To be specific, this would not involve X console fonts, just where OTF fonts are normally installed.)

**Comment by rallg** [comment]
Including system in OSFONTDIR could mean Termux or Android system fonts, or both. I would be cautious about that. Android has many multilingual fonts that might clutter things (I have a low-end system with not a lot of free memory). And, as far as I can tell, many of them are available in TeX, or can be copied out of the Android system (no root needed) into the Termux or TeX font directory. Works with LuaLaTeX. Presumably this is well-known among users who need TeX on Android.

**Comment by davidpiano** [comment]
Oh! Not Android certainly, just within Termux.

I meant exactly two locations: "the usual fonts directory under Termux's /usr" and "the usual fonts directory under Termux's /home".
