### ISSUE TITLE
Package Request: urlview

### ISSUE THREAD

**Issue by atomi** [termux/termux-packages#1624]
https://github.com/sigpipe/urlview

Ubuntu repo https://packages.ubuntu.com/trusty/misc/urlview

**Comment by atomi** [comment]
I think if there is a way to open the termux urlviewer via command line that will work too.

**Comment by stephengroat** [comment]
requires `librx` https://github.com/zorgnax/librx

**Comment by atomi** [comment]
How about just the ability to run the ctrl+alt+u url list from the command line?

**Comment by Neo-Oli** [comment]
urlview seems to be abandoned. Have you tried `urlscan`? You can install it with `pip install urlscan`. It seems to be doing almost the same thing.

**Comment by atomi** [comment]
it's for rtv https://github.com/michael-lazar/rtv and urlscan doesnt seem to do anything when invoked fro rtv
