### ISSUE TITLE
termux-fix-shebang inside git

### ISSUE THREAD

**Issue by brysgo** [termux/termux-packages#1627]
Would it be possible to make a filter stream to rewrite shebangs the way auto_crlf works in git? (https://github.com/git/git/blob/238e487ea943f80734cc6dad665e7238b8cbc7ff/convert.h)

That way any scripts in a git repository would be automatically converted, and we don't need to worry about having uncommitted changes.

**Comment by Neo-Oli** [comment]
You might also be interested in [Termux-Exec](https://wiki.termux.com/wiki/Termux-exec), which allows you to run scripts with traditional shebang without calling termux-fix-shebang.

**Comment by brysgo** [comment]
woah, thanks. will try it

**Comment by brysgo** [comment]
tried briefly to get termux-exec working without success, will try again later

**Comment by Neo-Oli** [comment]
@brysgo be sure to restart your shell (or better all of termux) after installing termux-exec with `pkg install termux-exec`

**Comment by brysgo** [comment]
I did restart my shell, but maybe there are other things going on in the script. I'll have to learn how termux-exec works to try and figure out what is happening. Have you used JavaScript dev tools with termux-exec?

**Comment by xeffyr** [comment]
Closing since we have *termux-exec*. If it is not working, then **find**, **xargs** and **termux-fix-shebang** will help.
