### ISSUE TITLE
[Bug]: $PREFIX/bin/texlive no longer on PATH

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#16320]
### Problem description

I have been using texlive on Termux for a long time. Recently, perhaps after the recent update to 2022 texlive-bin, `$PREFIX/bin/texlive` is no longer on PATH. I looked in `$PREFIX/etc/profile.d` but did not find anything that would add texlive to PATH. Previously, if I remember correctly, there was a script in there, which added the PATH.

User error? Of does the `profile.d/texlive.sh` file need to be re-packaged?

Easy to fix with my `~/.bashrc` file.

### What steps will reproduce the bug?

command: `luahbtex --version` fails (not found in PATH).

### What is the expected behavior?

`luabhtex -vversion` should respond with some info.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://plug-mirror.rcac.purdue.edu/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-x11 x11 main
Updatable packages:
ffmpeg/stable 6.0-2 arm [upgradable from: 6.0-1]
firefox/x11 112.0.1 arm [upgradable from: 112.0-1]
libxpm/x11 3.5.16 arm [upgradable from: 3.5.15]
texstudio-data/x11 4.5.2 all [upgradable from: 4.5.1]
texstudio/x11 4.5.2 arm [upgradable from: 4.5.1]
tumbler/x11 4.18.1 arm [upgradable from: 4.18.0]
termux-tools version:
1.36.1
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22626479 #1 SMP PREEMPT Mon Jan 9 15:48:32 KST 2023 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T510
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
`$PREFIX/etc/profile.d/texlive.sh` is owned by `texlive-installer` package which is recommended by `texlive-bin` package and these two packages are installed together by default, unless specified otherwise explicitly e.g. by using `--no-install-recommends` option for `apt-get` command.

**Comment by davidpiano** [comment]
Did you just do a new install of Texlive, on a Termux that didn't have it yet, or where Texlive had been deleted? Maybe the problem is the same as [#16234](https://github.com/termux/termux-packages/issues/16234#issue-1671709688) , that you made a recent new install, and almost all the parts are missing from your system because the download repository was unavailable.

**Comment by rallg** [comment]
I could have done any of those naughty things. I use TeXlive every day (and have contributed a package to CTAN), so I may very well have altered something. Put it down to "user error". No big deal, since I fixed it myself.
