### ISSUE TITLE
[Packaging]: Multiple RUNPATH entries limitations

### ISSUE THREAD

**Issue by truboxl** [termux/termux-packages#16358]
### Problem description

I think there's a need for a tool, probably `patchelf` and some scripts, that fixes the order of having improper RUNPATH entries at post massage phase or post install phase during building. Goal is to sort the entries and always place `$PREFIX/lib` last.

Issues arise when binaries prefer Termux's `$PREFIX/lib` over package's `$ORIGIN/../lib` for example.

I do not believe the current order is something that can be fixed easily using our existing build scripts. LDFLAGS are set to have `$PREFIX/lib` at start then additional entries are appended later on during configure stage by the packages.

May need more effort to customise build.sh for each package to fix this behaviour if we don't have a shared tool.

It should also be opt-in per xtkoba's suggestion.

### What steps will reproduce the bug?

```
apt install binaryen emscripten-binaryen
cd $PREFIX/opt/emscripten-binaryen/bin
for bin in `ls`; do echo $bin; ./$bin --version; done
```
```
wasm-as
wasm-as version 112
wasm-ctor-eval
CANNOT LINK EXECUTABLE "./wasm-ctor-eval": cannot locate symbol "_ZNK4wasm7Literal11internalizeEv" referenced by "/data/data/com.termux/files/usr/opt/emscripten-binaryen/bin/wasm-ctor-eval"...
wasm-dis
wasm-dis version 112
wasm-emscripten-finalize
wasm-emscripten-finalize version 112
wasm-fuzz-types
CANNOT LINK EXECUTABLE "./wasm-fuzz-types": cannot locate symbol "_ZN4wasm10ReFinalize18visitArrayNewFixedEPNS_13ArrayNewFixedE" referenced by "/data/data/com.termux/files/usr/opt/emscripten-binaryen/bin/wasm-fuzz-types"...
wasm-metadce
wasm-metadce version 112
wasm-opt
CANNOT LINK EXECUTABLE "./wasm-opt": cannot locate symbol "_ZN4wasm10ReFinalize18visitArrayNewFixedEPNS_13ArrayNewFixedE" referenced by "/data/data/com.termux/files/usr/opt/emscripten-binaryen/bin/wasm-opt"...
wasm-reduce
CANNOT LINK EXECUTABLE "./wasm-reduce": cannot locate symbol "_ZNK4wasm4Type8isStringEv" referenced by "/data/data/com.termux/files/usr/opt/emscripten-binaryen/bin/wasm-reduce"...
wasm-shell
CANNOT LINK EXECUTABLE "./wasm-shell": cannot locate symbol "_ZNK4wasm7Literal11internalizeEv" referenced by "/data/data/com.termux/files/usr/opt/emscripten-binaryen/bin/wasm-shell"...
wasm-split
wasm-split version 112
wasm2js
CANNOT LINK EXECUTABLE "./wasm2js": cannot locate symbol "_ZN4wasm13ArrayNewFixed8finalizeEv" referenced by "/data/data/com.termux/files/usr/opt/emscripten-binaryen/bin/wasm2js"...
```

### What is the expected behavior?

```
wasm-as
wasm-as version 112
wasm-ctor-eval
wasm-ctor-eval version 112
wasm-dis
wasm-dis version 112
wasm-emscripten-finalize
wasm-emscripten-finalize version 112
wasm-fuzz-types
wasm-fuzz-types version 112
wasm-metadce
wasm-metadce version 112
wasm-opt
wasm-opt version 112
wasm-reduce
wasm-reduce version 112
wasm-shell
wasm-shell version 112
wasm-split
wasm-split version 112
wasm2js
wasm2js version 112
```

### System information

n/a

**Comment by buttaface** [comment]
Easily fixed, simply add patchelf as a dependency in our Docker, then patch away as needed. See [my recent Swift work for an example](https://github.com/buttaface/termux-packages/commit/6bcae3f4370be7a9317508c0e8a67ea8b6c9d473#diff-a3bcec5381cf1ae076d0c16e6be6792a91869d20be55c919085f0704fa11424cR163).

**Comment by xtkoba** [comment]
If the hack is applied in the *opt-in* basis (by using some flag like `TERMUX_PKG_FIX_RPATH=true` with `false` being the default) then it is welcome.

I'm against *unconditionally* applying the proposed hack to every package. In the past I tried to use `patchelf` in some package but couldn't because it broke some binaries. Note that we do not check whether binaries are broken in auto-updating packages and so the unconditional application may lead to silent breakage.

**Comment by buttaface** [comment]
You used `--add-rpath` there, I've not had a problem with `--set-rpath` on linux (others reported problems using it on macOS though), works well so far.

**Comment by licy183** [comment]
I think that these operations should be handled in post-massage step for particular packages, rather than adding a generic step in message step...

**Comment by xtkoba** [comment]
> I think that these operations should be handled in post-massage step for particular packages, rather than adding a generic step in message step...

IIRC files in subpackages cannot be post-massaged. Note that `emscripten-binaryen` is a subpackage of `emscripten`. A workaround is to use `termux_step_post_make_install` (e.g. `php`) but providing a hook for subpackages is also suggested.

**Comment by xtkoba** [comment]
`patchelf` is known to break some binaries when stripped afterwards: https://github.com/NixOS/patchelf/issues/145. (FWIW `eglinfo-system` is one of its victims now for which I have to elaborate some workaround: PR #16563.)

Not sure but maybe OK if the `patchelf` stage is placed after `strip` stage.

**Comment by truboxl** [comment]
I suppose we can add a `clang` and/or `ld` wrapper that intercepts `-Wl,-rpath=` arguments and modify the order as `patchelf` still has unknown bugs...
