### ISSUE TITLE
Termux error when installing package or PKG upgrade

### ISSUE THREAD

**Issue by Marcodoro** [termux/termux-packages#16374]
### Problem description

When I want to install something or type PKG upgrade this happens:$ pkg upgrade
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: bad
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: bad
Using fallback mirror: https://termux.org/packages
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libssh2.so in namespace (default)
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libssh2.so in namespace (default)
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libssh2.so in namespace (default)
0% [Working]. and it stays so forever

### What steps will reproduce the bug?

I don't think that this is possible

### What is the expected behavior?

Upgrading the pkg

### System information

termux-info:

```
...Command doesn't work
```

**Comment by xtkoba** [comment]
This can happen with partial upgrading. Also note that Google Play version of Termux is not supported anymore.

See also:

#6726

https://github.com/termux/termux-app#installation

https://github.com/termux/termux-app#google-play-store-deprecated
