### ISSUE TITLE
Add destab/vidstab to ffmpeg

### ISSUE THREAD

**Issue by dorneanu** [termux/termux-packages#1638]
Hi! Any chances of adding stabilization filters like destab/vidstab to ffmpeg? That would be great.

Thanks in advance.

**Comment by dorneanu** [comment]
The vidstab library can be found at: https://github.com/georgmartius/vid.stab

**Comment by Witiko** [comment]
Can we add --enable-libvidstab to the build script? I agree with @dorneanu and @uqs that this would be highly useful. Due to the missing `lib*-dev` packages, I haven't had much success with compiling ffmpeg with vidstab manually on the device.

**Comment by eathtespagheti** [comment]
Would be pretty sweet, I'm trying to do a `build.sh` for VidStab, I'll let you know

**Comment by its-pointless** [comment]
i can do this as i have done it before.

**Comment by eathtespagheti** [comment]
Hey @its-pointless, I've tried to do it but I've got stuck with the compiler complaining about an invalid variable conversion

```
error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
```

If you want to check my [build.sh](https://github.com/eathtespagheti/termux-packages/blob/db7047d393711a5cfae6287373dcac764352218d/packages/vid.stab/build.sh) I've [forked](https://github.com/eathtespagheti/termux-packages) the project and it's in the branch `packages/VidStab`

**Comment by uqs** [comment]
unstale ping

**Comment by xtkoba** [comment]
The current `ffmpeg` seems to be configured with `--enable-libvidstab` already.

Can't this be closed?

**Comment by thunder-coding** [comment]
Yeah @xtkoba, thanks!
