### ISSUE TITLE
Can QEMU use egl-headless display?

### ISSUE THREAD

**Issue by dontknowhy** [termux/termux-packages#16386]
### Problem description

~ # env LD_LIBRARY_PATH=/system/lib64 qemu-system-x86_64 -display vnc=:0 -display egl-headless
qemu-system-x86_64: egl: no drm render node available
qemu-system-x86_64: egl: render node init failed
 
You can see QEMU can't use Android's EGL library because QEMU uses gbm and Android doesn't have it

### What steps will reproduce the bug?

env LD_LIBRARY_PATH=/system/lib64 qemu-system-x86_64 -display vnc=:0 -display egl-headless

### System information

termux-info:

```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1+d2f2051
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~OLGgDWsRAEzyFKJZUszzSw==/com.termux--WLw_XX2By-5Fwrd8GvqFg==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=16847
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c215,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c215,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10471
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+93eafff
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+93eafff
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main/ stable main
deb https://mirrors.ustc.edu.cn/termux/apt/termux-x11/ x11 main
deb https://mirrors.ustc.edu.cn/termux-its-pointless/24 termux extras
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
12
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Mon Jan 16 04:17:11 CST 2023 aarch64 Android
Device manufacturer:
HONOR
Device model:
BRT-W09
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

```

**Comment by tareksander** [comment]
I recently looked at the Android EGL library and was annoyed that you need to create a surface to use GLES. I think headless mode is only supported with [this extension](https://registry.khronos.org/EGL/extensions/KHR/EGL_KHR_surfaceless_context.txt), and that is not required to be implemented for Android. EGL1.5 has this in the core specification, but the GLES implementation also needs to support surfaceless contexts. So I think this feature just isn't implemented on Android.

**Comment by dontknowhy** [comment]
> I recently looked at the Android EGL library and was annoyed that you need to create a surface to use GLES. I think headless mode is only supported with [this extension](https://registry.khronos.org/EGL/extensions/KHR/EGL_KHR_surfaceless_context.txt), and that is not required to be implemented for Android. EGL1.5 has this in the core specification, but the GLES implementation also needs to support surfaceless contexts. So I think this feature just isn't implemented on Android.

So...
It won't work anymore?
Even my device supported this EGL_KHR_surfaceless_context?

**Comment by tareksander** [comment]
I looked into it a bit more, QEMU only supports X11 and GBM rendering through Mesa, and Android EGL has support for neither. You can raise an issue over at the QEMU repo if you want.

**Comment by dontknowhy** [comment]
> I looked into it a bit more, QEMU only supports X11 and GBM rendering through Mesa, and Android EGL has support for neither. You can raise an issue over at the QEMU repo if you want.

Nothing works
