### ISSUE TITLE
[Package]:  python-tokenizers and python-tiktoken

### ISSUE THREAD

**Issue by nacho00112** [termux/termux-packages#16409]
### Why do you want to add this package to Termux?

[tokenizers](https://github.com/huggingface/tokenizers) is used by the huggingface machine learning library [transformers](https://github.com/huggingface/transformers), [tiktoken](https://github.com/openai/tiktoken) is not required by the [openai](https://github.com/openai/openai-python) library, but may be needed in some cases, the thing is that these libraries takes a lot of space and time to build, they use rust, i'm not sure if this should be in the [tur-repo](https://github.com/termux-user-repository/tur).
These packages are used with the OpenAI and Hugging Face Python API's.

### Home page URL

I provided the links to their github in the description

### Source code URL

I provided the links to their github in the description

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I compiled tiktoken after repeating the same command `pip install tiktoken` a lot of times it showed me different errors, it taked me some hours, i also am having problems compiling tokenizers, i actually dropped it since it are taking me further work than tiktoken

**Comment by nacho00112** [comment]
Issue number 404, it was funny for me
![IMG_20230423_202726](https://user-images.githubusercontent.com/71481304/233875485-94694661-5397-4b62-9bc2-14e6cf8480b8.jpg)

**Comment by nviet** [comment]
> I found the solution as following, `pkg install tur-repo && pip install tiktoken`

Great. I think we wait for OP to try this and if it works then the issue can be closed without having to add new packages.

**Comment by nacho00112** [comment]
They should be added at least in tur, should not?

**Comment by nacho00112** [comment]
> I found the solution as following, `pkg install tur-repo && pip install tiktoken`

As I said, repeating worked for me for some reason

**Comment by nacho00112** [comment]
> 

The thing is not that bro, they take much time and space in ~/.cargo

**Comment by nacho00112** [comment]
I will re-open this in tur
