### ISSUE TITLE
[Package]:  dhclient (isc-dhcp-client) dhcp client

### ISSUE THREAD

**Issue by gtxaspec** [termux/termux-packages#16415]
### Why do you want to add this package to Termux?

Add ability to establish network connections via DHCP (since android does not support DHCP)

Termux currently has no dhcp clients in it's repositories.

### Home page URL

https://www.isc.org/dhcp/

### Source code URL

https://gitlab.isc.org/isc-projects/dhcp

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by nviet** [comment]
This is a nice package. However since it already reached the end of life, it does not complies with the **Packaging policy** (under the clause _Packages must be active, well-known projects_).
