### ISSUE TITLE
[Package]: fcitx5-configtool, fcitx5-gtk, fcitx5-qt

### ISSUE THREAD

**Issue by amuramatsu** [termux/termux-packages#16425]
### Why do you want to add this package to Termux?

Fcitx5 already exists in termux-packages, but fcitx5 related tools that fcitx5-configtool and immodules for GUI toolkit does not yet. These tools are useful for text input with fcitx5 for CJK users.

* Fcitx5-configtools: https://github.com/fcitx/fcitx5-configtool
   Fcitx5 configuration tools with GUI
* Fcitx5-qt: https://github.com/fcitx/fcitx5-qt
  immodule for Qt toolkit and library for Qt application
* Fcitx5-gtk: https://github.com/fcitx/fcitx5-gtk
  immodule for GTK2,3,4 toolkit and library

### Source code URL

https://github.com/fcitx/fcitx5-configtool, https://github.com/fcitx/fcitx5-qt, https://github.com/fcitx/fcitx5-gtk

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by thiled** [comment]
+1
