### ISSUE TITLE
"curl": cannot locate symbol "curl_mime_free" 

### ISSUE THREAD

**Issue by tchollingsworth** [termux/termux-packages#1646]
```
$ curl --version                                 
CANNOT LINK EXECUTABLE "curl": cannot locate symbol "curl_mime_free" referenced by "/data/data/com.termux/files/usr/bin/curl"...
Aborted
$ which curl                                     
/data/data/com.termux/files/usr/bin/curl
$ apt-cache show curl
Package: curl                                    
Architecture: arm                                
Installed-Size: 328
Maintainer: Fredrik Fornwall @fornwall
Version: 7.56.0
Description: Command line tool for transferring data with URL syntax
Description-md5: c65d2add7ee87e0ba9e5a74f286ce55a
Homepage: https://curl.haxx.se/
Depends: libcurl
Filename: dists/stable/main/binary-arm/curl_7.56.0_arm.deb
Size: 137824
SHA256: 71618e46447a33156bf97daddd33fd97a18d7a03abb2a56ed756ed48b1c421d9
```

Unlike with some similar issues, I don't appear to have an Android system version of curl installed at all.

**Comment by tchollingsworth** [comment]
I do have `/system/lib/libcurl.so`, but you set things up so it shouldn't be using it?

```
$ echo $LD_LIBRARY_PATH
/data/data/com.termux/files/usr/lib
```

This is on a Moto G4 with Android 7.0 if that's helpful.

**Comment by tchollingsworth** [comment]
The symbol does seem to be genuinely missing:

```
$ nm -D /data/data/com.termux/files/usr/lib/libcurl.so | grep curl_mime_free
<no output>
```

**Comment by Grimler91** [comment]
I assume that you have made sure that everything is up to date? (apt update && apt upgrade)

curl_mime_free is included in libcurl.so on my arm device so something is very weird here. 

```
$ uname -a
Linux localhost 3.4.39-5941801 #1 SMP PREEMPT Mon Oct 5 17:34:20 KST 2015 armv7l Android
$ nm -D $PREFIX/lib/libcurl.so | grep curl_mime_free
00038b8c T curl_mime_free
```

Does `apt install libcurl --reinstall` change anything?

**Comment by tchollingsworth** [comment]
Good catch, updating `libcurl` resolves the issue. (I didn't think to run an `apt-get upgrade` because I just recently installed Termux and did that.)

**Comment by michaelhou** [comment]
> Good catch, updating `libcurl` resolves the issue. (I didn't think to run an `apt-get upgrade` because I just recently installed Termux and did that.)

I got error 

```
CANNOT LINK EXECUTABLE "curl": cannot locate symbol "curl_url" referenced by "/data/data/com.termux/files/usr/bin/curl"...
Aborted

```
After I run a  `apt-get upgrade`, it works like a charm...
