### ISSUE TITLE
[Bug]: missing sub package for buf 

### ISSUE THREAD

**Issue by Ludea** [termux/termux-packages#16491]
### Problem description

Buf package doesn't work correctly, it miss 2 sub packages :
protoc-gen-connect-es
protoc-gen-es

### What steps will reproduce the bug?

`apt install buf`
`buf generate /someprotofile`

### What is the expected behavior?

Run buf without issue

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~vVvzkyGImqVC0_dbWADmtA==/com.termux--JS1m2ChQfTEKObFaR46tQ==/base.apk
TERMUX_APP__APK_RELEASE=UNKNOWN
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=false
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=18779
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c0,c258,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c0,c258,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10512
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://md.mirrors.hacktegic.com/termux/termux-main stable main
Updatable packages:
command-not-found/stable 2.1.0-21 aarch64 [upgradable from: 2.1.0-20]
termux-tools version:
1.38.1
Android version:
12
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Fri Mar 17 16:09:10 CST 2023 aarch64 Android
Device manufacturer:
OnePlus
Device model:
AC2003
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by 2096779623** [comment]
Following the steps in [docs](https://buf.build/docs/tutorials/getting-started-with-buf-cli/), I can't reproduce this bug on my device.
Please describe the steps to reproduce in detail.

**Comment by Ludea** [comment]
I update my post with more détails on installation

**Comment by 2096779623** [comment]
> I update my post with more détails on installation

```bash
~/.../start/getting-started-with-buf-cli $ buf generate proto/pet/v1/pet.proto
~/.../start/getting-started-with-buf-cli $ cat buf.gen.yaml
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/bufbuild/buf-tour/gen
plugins:
  - plugin: buf.build/protocolbuffers/go
    out: gen
    opt: paths=source_relative
  - plugin: buf.build/bufbuild/connect-go
    out: gen
    opt: paths=source_relative
~/.../start/getting-started-with-buf-cli $
```

**Comment by Ludea** [comment]
![Uploading Screenshot_2023-04-30-15-57-49-87_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by Ludea** [comment]
![Screenshot_2023-04-30-15-57-49-87_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/2116692/235356965-9819bcde-fced-4169-99f4-4a8aee296071.jpg)

**Comment by 2096779623** [comment]
https://github.com/bufbuild/connect-es
This may require you to build and install into `$PREFIX/bin` yourself.

**Comment by Ludea** [comment]
It's better to provide it with buf package as sub packages ?

**Comment by 2096779623** [comment]
> It's better to provide it with buf package as sub packages ?

`npm i -g @bufbuild/protoc-gen-connect-es`
Then try again.

**Comment by Ludea** [comment]
Doesn't work, if I install `protoc-gen-connect-es `, it need `@bufbuild/protoc-gen-es`, if I install it, it need `protoc-gen-connect-es ` whereas it's already installed

**Comment by Ludea** [comment]
It was an incompatibily between buf package, and npm buf package.
I delete buf npm package, and it work
