### ISSUE TITLE
w3m aborts

### ISSUE THREAD

**Issue by csabahenk** [termux/termux-packages#1649]
I'm getting this:

```
> w3m -h
Wrong __data_start/_end pair
[1]    27261 abort      w3m -h
```

With:

```
> dpkg -s w3m libgc
Package: w3m
Status: install ok installed
Installed-Size: 1320
Maintainer: Fredrik Fornwall @fornwall
Architecture: arm
Version: 0.5.3.20170102-1
Depends: libgc, ncurses, openssl
Description: Text based Web browser and pager
Homepage: http://w3m.sourceforge.net/

Package: libgc
Status: install ok installed
Installed-Size: 156
Maintainer: Fredrik Fornwall @fornwall
Architecture: arm
Version: 7.6.0-1
Description: Library providing the Boehm-Demers-Weiser conservative garbage collector
Homepage: http://www.hboehm.info/gc/
```

Note I made a "rogue" build of w3m, ie. cloned this repo to the target device and without setting up a build environment I compiled it along the build instructions (installed the *-dev packages for the dependecies, manually applyed patches and set configure opts). The resulting w3m binary did not produce the abort (it 's still not usable, as it segfaults on any non-trivial page, but that's an other thing).

**Comment by its-pointless** [comment]
The issue is likely with libgc. I dealt with this on x86 trying to get guile to work on it. Its due to libgc assuming android uses ld.gold instead of the normal ld.  I didn't get an error on arm on guile so i thought it was fine.

**Comment by csabahenk** [comment]
@its-pointless I could work around the issue with using static libgc.

- I built libgc (current git checkout) with `--enable-static`
- Installed libgc and deleted the .so files to enforce static linking (is there a more gracious way? w3m does not support `--enable-static`)
- compiled w3m

It works!

Note: using my previous w3m build (that links dynamically to libgc) with the freshly built libgc produces the segfault. I don't know what to expect when building w3m against the fresh libgc, but dynamically linking to it.

**Comment by csabahenk** [comment]
OK. I checked dynamic linking against freshly built libgc.

It works.

So just rebuild libgc (I used current git) and w3m (according to termux-package) and it works.

**Comment by its-pointless** [comment]
The updated libgc should of fixed this?

**Comment by csabahenk** [comment]
Yes indeed, it does.

**Comment by fornwall** [comment]
Nice! Great work @its-pointless !
