### ISSUE TITLE
mcedit does not accept input

### ISSUE THREAD

**Issue by dvlasenk** [termux/termux-packages#165]
Freshly installed termux on a Samsung SM-T700 tablet. Android version 5.0.2.

I installed Midnight Commander: apt install mc
This installs mc-4.8.15

MC works okay apart from one problem: internal editor does not accept any text input:
- select and open a text file: F4 key. This opens internal MC text editor.
  Or run "mcedit FILE".
- try typing any text. Instead of typed letters, dots appear.
  (ordinary dot chars, 0x2E ascii: I checked by saving file and hexdumping it).
- space doesn't work (inputs dots too).
- but Tab works (inserts tab character).
- cursor keys, Fn keys, Esc all work.
- input in dialogs works: press F7 (text search) and there text input works.

**Comment by fornwall** [comment]
Thanks for a descriptive report! This has been fixed in version `4.8.16-2` of the mc package, which you can update to using

    apt update && apt upgrade

Let me know if any problem remains!
