### ISSUE TITLE
@Auxilus

### ISSUE THREAD

**Issue by stainslav** [termux/termux-packages#1651]
Can you Modify these scripts for termux it is very nicessary for me and there is .bin folder also in this zip please make it accessible from /data/data/com.termux/files/use/bin not .bin please edit these scripts and try to run because it shows me cannot execute binary file 
Link is here: https://mega.nz/#!KYwU1AwL!PSjuNh9BHKDmQrXE2ngQhO2tVilPFOAKcUMrCc0oJ-E

**Comment by Grimler91** [comment]
It's probably built for another architecture. Executing binaries built for another architecture won't work.

**Comment by Auxilus** [comment]
@stainslav as @Grimler91 said, you have to either use the binary executable which is supported by your architecture or compile the package locally to create one.

**Comment by sdrausty** [comment]
The key for success is architecture in systems working in Termux. 
https://wiki.termux.com/wiki/Proot

**Comment by vishalbiswas** [comment]
that zip file just contains bash scripts. You can just do `apt install termux-exec` then restart termux. be sure to read Instructions.md
