### ISSUE TITLE
[Bug]: libglvnd: SONAME conflict of `libEGL.so` with system one

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#16548]
### Problem description

`libEGL.so` from `libglvnd` package and `libOpenSLES.so` (under `/system/lib*`) cannot be loaded together. The dynamic linker complains that it cannot locate symbol "eglDestroySyncKHR" referenced by "/system/lib64/libgui.so".

PR #16547 (enabling SOVERSION suffix for shared libs in `libglvnd` package) solves this issue.

### What steps will reproduce the bug?

```bash
echo 'int main(int argc, char **argv){ return 0; }' | clang -x c - -o a.out -Wl,--no-as-needed -lOpenSLES -lEGL && ./a.out
```

produces the error

```
CANNOT LINK EXECUTABLE "./a.out": cannot locate symbol "eglDestroySyncKHR" referenced by "/system/lib64/libgui.so"...
```

### What is the expected behavior?

The program should exit successfully.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5210
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
12
Kernel build information:
Linux localhost 4.19.191-g234d1747e22a #1 SMP PREEMPT Sat Mar 25 18:12:54 CST 2023 aarch64 Android
Device manufacturer:
motorola
Device model:
moto e32(s)
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by tareksander** [comment]
I tried to compile a program that should use the system EGL while having libglvnd installed. The compiler automatically used libEGL.so.1 with `-lEGL`, so setting `LD_LIBRARY_PATH` to force the system EGL didn't work anymore. I had to uninstall libglvnd so the compiler picked up on the system EGL. Is there another way to compile for the system libraries? Would this also happen if libglvnd is installed in the build prefix in termux-packages?

**Comment by truboxl** [comment]
Pass `-L/system/lib64 -lEGL` when compiling
`LD_LIBRARY_PATH` is never used during compiling

**Comment by tareksander** [comment]
> `LD_LIBRARY_PATH` is never used during compiling

I used that when running the compiled program.



> Pass `-L/system/lib64 -lEGL` when compiling

That won't work when the program is build with termux-packages, right?

**Comment by truboxl** [comment]
> That won't work when the program is build with termux-packages, right?

There is no `/system/lib64/libEGL.so` in the builder docker image so no...

**Comment by EDLLT** [comment]
> Pass `-L/system/lib64 -lEGL` when compiling `LD_LIBRARY_PATH` is never used during compiling

I am facing the exact same error when trying to run RNote
``CANNOT LINK EXECUTABLE "./rnote": cannot locate symbol "eglDestroySyncKHR" referenced by "/system/lib64/libgui.so"...`` 
https://github.com/termux/termux-packages/issues/17655#issuecomment-2346604075
