### ISSUE TITLE
[Bug]: inkscape crash on file new or save.as

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#16572]
### Problem description

Installed inkscape today. All package up to date. Rebooted. Inkscape fails every time. Splash screen shows, but cannot open file browser (crash). If I use New File, I get the graphics window, but if I attempt to save anything, Inkscape crashes. If I right-click an existing svg file, open in Inkscape, it will open. But it will crash if I attempt save.

Command line says, after crash: " (org.inkscape.Inkscape:20604): GLib-GIO-ERROR **: 12:37:20.957: No GSettings schemas are installed on the system Trap"

I have tried re-compiling gschemas. I get a few warnings about deprecated system paths, but this is not new. Reboot, no joy.

### What steps will reproduce the bug?

Any attempt to open any file from within Inkscape. Any attempt o save a file.

### What is the expected behavior?

File browser should open.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://plug-mirror.rcac.purdue.edu/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22626479 #1 SMP PREEMPT Mon Jan 9 15:48:32 KST 2023 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T510
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
A quick workaround as per https://gitlab.com/inkscape/inkscape/-/issues/2495:

```bash
GSETTINGS_SCHEMA_DIR=$PREFIX/share/glib-2.0/schemas inkscape
```

I'm still seeking for a proper and permanent solution.

**Comment by rallg** [comment]
Today's update 1.2.2-6 seems to be OK.
