### ISSUE TITLE
Re: Relevant Inquiry w/ reference to 'Package request: groff #2056'

### ISSUE THREAD

**Issue by HrtfdJetpack06120** [termux/termux-packages#16574]
Greetings,

			I am looking to be able to output man page results to PDF format, to be saved for later reference and review. My inquiry into how to achieve this, led me to the package 'groff', from whence I came upon 'gropdf'. 
		I was looking for some clarification as to whether or not 'gropdf'  is a separate package, or if it is just a set of  extended commands made available by the 'groff' package. 
		I wanted to avoid the requesting 'gropdf' if its commands , its functions are/were an inherent part of the already successfully  requested, available 'groff' package, that I have just installed. 

			Thanks to all,

							Will

**Comment by xtkoba** [comment]
`gropdf` command is part of `groff` package.

Closing as answered.
