### ISSUE TITLE
how to ssha with multiple keys?

### ISSUE THREAD

**Issue by fiiim** [termux/termux-packages#1658]
I cant figure out how to use ssha with multiple keys and I find no info about it anywhere. Maybe multiple keys doesnt work with ssha?

**Comment by xeffyr** [comment]
By default ssha preloads to agent only keys with standard name, e.g. `id_rsa` or `id_ed25519`. It just behaviour of `ssh-add` without arguments.

From manpage:
> ssh-add  adds  private key identities to the authentication agent, ssh-agent(1).  When run without arguments, it adds the files ~/.ssh/id_rsa, ~/.ssh/id_dsa, ~/.ssh/id_ecdsa, and ~/.ssh/id_ed25519.
       After loading a private key, ssh-add will try to load corresponding certificate information from the filename obtained by appending -cert.pub to the name of the private key file.  Alternative  file
       names can be given on the command line.

So you cannot use additional keys which have non-standard names.
