### ISSUE TITLE
R: /data/data/com.termux/files/usr/bin/sed: not found

### ISSUE THREAD

**Issue by espectalll** [termux/termux-packages#1659]
Whenever I try to run a script with `Rscript`, I get the following error:

```
/data/data/com.termux/files/usr/lib/R/bin/R: 1: /data/data/com.termux/files/usr/lib/R/bin/R: /data/data/com.termux/files/usr/bin/sed: not found
/data/data/com.termux/files/usr/lib/R/bin/R: 1: /data/data/com.termux/files/usr/lib/R/bin/R: /data/data/com.termux/files/usr/bin/sed: not found
Fatal error: cannot open file '': No such file or directory
```

The same goes for `R CMD BATCH`:

```
/data/data/com.termux/files/usr/lib/R/bin/R: 1: /data/data/com.termux/files/usr/lib/R/bin/R: /data/data/com.termux/files/usr/bin/sed: not found
ERROR: option '-f' requires a filename argument
```

**Comment by its-pointless** [comment]
Install sed..
apt install sed

**Comment by espectalll** [comment]
Oh, so it specifically needs GNU sed. OK, then shouldn't it be added as a dependency to R?

**Comment by its-pointless** [comment]
R isn't specifically supported by termux ( i distribute it). But i will add it to the dependencies so next up date works...

**Comment by espectalll** [comment]
Oh, didn't notice that! I don't remember what I added your repo for, so I just installed R expecting it was from the main repo. Anyway, thanks, closing!
