### ISSUE TITLE
[Package]: llama-index

### ISSUE THREAD

**Issue by eliranwong** [termux/termux-packages#16598]
### Why do you want to add this package to Termux?

llama-index is a very helpful package to query over data via OpenAI GPT models. Unfortunately, I cannot install on Termux. 

### Source code URL

https://pypi.org/project/llama-index/

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
```bash
MATHLIB=m pip install llama-index
```

If you are on arm arch, then some workaround will be needed for greenlet (#15911). No objection to providing `python-greenlet` package on our own.

**Comment by eliranwong** [comment]
Tried "MATHLIB=m pip install llama-index" 

Tried installing from source. 

Still doesn't work, even after installing your python-greenlet package.

Getting errors:

Failed to build maturin
      ERROR: Could not build wheels for maturin, which is required to install pyproject.toml-based projects

I m using Termux on Microsoft Surface Duo. Can anyone help?
