### ISSUE TITLE
Add termux-open-url as default $BROWSER

### ISSUE THREAD

**Issue by Yajo** [termux/termux-packages#166]
As said in https://github.com/termux/termux-packages/issues/17#issuecomment-196466359.

cc @fornwall @coderstephen @Neo-Oli

**Comment by fornwall** [comment]
I'm closing this - those who want to may do a `export BROWSER=termux-open-url` to setup this (but not everyone wants this, some people wants to open an in-terminal browser).

**Comment by coderstephen** [comment]
Oops, sorry; I missed your ping.

It probably makes sense to leave it empty and just let the user configure it if they like.
