### ISSUE TITLE
Programs linked to libcrypto.so.1.0.0 can't be debugged with gdb on arm

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#1660]
I noticed this when looking into https://github.com/termux/termux-packages/issues/1657. 

Consider this "empty" C program: 
```
int main()
{
   return 0;
}
```

Compiling this with `gcc test.c -o test -lcrypto` gives a program that outputs the following in gdb:
```
bash-4.4$ gdb test
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-androideabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from hello...(no debugging symbols found)...done.
(gdb) run
Starting program: /data/data/com.termux/files/home/test/test

Program received signal SIGILL, Illegal instruction.
0xb6eaade8 in _armv7_tick () from /data/data/com.termux/files/usr/lib/libcrypto.so.1.0.0
```

There are no problems when doing the same on aarch64. Might be a issue upstream with libcrypto I guess.

`(gdb) disas 0xb6eaade8` gives 
```
Dump of assembler code for function _armv7_tick:
=> 0xb6eaade8 <+0>:     mrrc    15, 1, r0, r1, cr14
   0xb6eaadec <+4>:     bx      lr
End of assembler dump.
```

**Comment by Grimler91** [comment]
Actually, I get the same problem on my raspberry pi so this must be an upstream issue.

**Comment by fornwall** [comment]
Right - this is by design in openssl, from https://www.openssl.org/docs/faq.html#PROG15:

> OpenSSL adapts to processor it executes on and for this reason has to query its capabilities. Unfortunately on some processors the only way to achieve this for non-privileged code is to attempt instructions that can cause Illegal Instruction exceptions. The initialization procedure is coded to handle these exceptions to manipulate corresponding bits in capabilities vector. This normally appears transparent, except when you execute it under debugger, which stops prior delivering signal to handler. Simply resuming execution does the trick, but when debugging a lot it might feel counterproductive. Two options. Either set explicit capability environment variable in order to bypass the capability query (see corresponding crypto/*cap.c for details). Or configure debugger not to stop upon SIGILL exception, e.g. in gdb case add 'handle SIGILL nostop' to your .gdbinit.

**Comment by Grimler91** [comment]
Interesting, thanks!

**Comment by vishalbiswas** [comment]
on a sidenote, you can actually debug them.
