### ISSUE TITLE
[Bug]: libmp3lame invalid pkgconfig

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#16610]
### Problem description

.\data\data\com.termux\files\usr\lib\pkgconfig:\data\data\com.termux\files\usr\share\pkgconfig\lame.pc

the above path is the path 'lame.pc' file is installed on which is incorrect

the cause could be: 
https://github.com/termux/termux-packages/blob/d1bec93c64b1275f8d7b320c382ac535081ac711/scripts/build/termux_step_start_build.sh#L69

### What steps will reproduce the bug?

build package

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Thanks. Probably the same for `libmad` package.

**Comment by johndebia2022** [comment]
Great but why don't you increase the **revision** of the package ?
