### ISSUE TITLE
pkg install man fail!

### ISSUE THREAD

**Issue by mystorp** [termux/termux-packages#1662]
```text
$ pkg install man
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  man
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 206 kB of archives.
After this operation, 1012 kB of additional disk space will be used.
Err:1 http://211.161.151.132/files/4119000000C92EAE/neoterm.studio stable/main aarch64 man aarch64 1.14.3-1
  404  Not Found
E: Failed to fetch http://211.161.151.132/files/4119000000C92EAE/neoterm.studio/dists/stable/main/binary-aarch64/man_1.14.3-1_aarch64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by remo7777** [comment]
first typ command `apt-get update --fix-missing` then `apt-get upgrade -y` then `pkg install man`
😁

**Comment by mystorp** [comment]
thank u for reply@remo7777
but it seems not work for me
i have upgrade termux to `0.53`
and i can install other packages normally

**Comment by Grimler91** [comment]
Seems like you're subscribed to a neoterm repository, and that's what's failing. This is a neoterm issue and not a termux issue

**Comment by mystorp** [comment]
thank you for your reply.
Yes, i see.
but i don't know anything about neoterm, and i haven't done anything about it. how did it happen?

here is my `$PREFIX/usr/etc/apt/sources.list`:
(i have a little ubuntu expierence, i think this might help)
```list
$ cat ../usr/etc/apt/sources.list
# The main termux repository:
deb [arch=all,aarch64] http://termux.net stable main
```

**Comment by mystorp** [comment]
nothing.
```text
$ ls ../usr/etc/apt
apt.conf.d     sources.list
preferences.d  trusted.gpg
```

**Comment by Auxilus** [comment]
Im on aarch64, I got no errors while `pkg install man`

**Comment by Auxilus** [comment]
$  ~ pkg install man
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  man
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 206 kB of archives.
After this operation, 1012 kB of additional disk space will be used.
Get:1 http://termux.net stable/main aarch64 man aarch64 1.14.3-1 [206 kB]
Fetched 206 kB in 4s (44.8 kB/s)
Selecting previously unselected package man.
(Reading database ... 28900 files and directories currently installed.)
Preparing to unpack .../man_1.14.3-1_aarch64.deb ...
Unpacking man (1.14.3-1) ...
Setting up man (1.14.3-1) ...
$  ~

**Comment by mystorp** [comment]
Yes, i am too.@Auxilus 
```text
$ uname -a
Linux localhost 4.4.21-perf-g6a9ee37d-05963-g7b6ada9 #1 SMP PREEMPT Thu Sep 7 16:30:38 CST 2017 aarch64 Android
```

**Comment by Grimler91** [comment]
@mystorp Something is very weird, it is somehow configured to download from http://211.161.151.132/files/4119000000C92EAE/neoterm.studio, but that should mean that you have neoterm's repo specified in $PREFIX/etc/apt/sources, which you don't seem to have. 

From where did you install termux?

Can you do `grep -r neoterm $PREFIX` and see if that outputs something suspicious?

**Comment by mystorp** [comment]
I install termux from APKPure, a third party  android pkg downloader.
i have run `grep -r neoterm $PREFIX`, but it output nothing

**Comment by Grimler91** [comment]
Seems weird, but the apk from APKPure is identical with the one from [FDroid](https://f-droid.org/packages/com.termux/). 

Maybe someone else has a guess about what's going on.

**Comment by fornwall** [comment]
Strange. What does `ping termux.net` output?

If you have curl installed, what does `curl -D- http://termux.net -o /dev/null` output?

**Comment by mystorp** [comment]
```text
$ ping termux.net
PING termux.net (104.18.36.234) 56(84) bytes of data.
64 bytes from 104.18.36.234: icmp_seq=1 ttl=44 time=193 ms
^C64 bytes from 104.18.36.234: icmp_seq=2 ttl=44 time=212 ms

--- termux.net ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 10211ms
rtt min/avg/max/mdev = 193.100/202.622/212.145/9.533 ms

$ curl -D- http://termux.net -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Date: Sun, 15 Oct 2017 02:08:19 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=de0b039bf58549f579b06f26dc1a3974f1508033299; expires=Mon, 15-Oct-18 02:08:19 GMT; path=/; domain=.termux.net; HttpOnly
Last-Modified: Tue, 25 Jul 2017 22:32:57 GMT
ETag: W/"5977c719-125"
CF-Cache-Status: MISS
Expires: Sun, 15 Oct 2017 02:38:19 GMT
Cache-Control: public, max-age=1800
Server: cloudflare-nginx
CF-RAY: 3adf3adb152222a6-LAX

100   293    0   293    0     0    293      0 --:--:-- --:--:-- --:--:--   659
```
it's really strange, actually, I just installed curl

**Comment by mystorp** [comment]
i find it run success when i am trying to find somthing strange by use strace command a moment ago.I guess it's probably what God did.
