### ISSUE TITLE
[Bug]: vim rc .. cant disable

### ISSUE THREAD

**Issue by fxmbsw7** [termux/termux-packages#16621]
### Problem description

i code in vim
over the years , i stopped using syntax hight and tabbing auto ' features ' cause they are buggy and all wrong

i wished the same for vim s system vimrc i dunno what u did where
.. but i cant disable all these besides i dunno its vimnames ..
i do
~/.vimrc
set binary noeol ft=text mouse=

with or without that last of three opts
i usually got on debian

) no auto tab
) no auto syntax
) no eol ( ending \n excessive wrong-bte )

on termux vim package i cant disable your / the termux es vim defaults
at least the ( wrong ) autotabbing
noeol may work already im halfsure

### What steps will reproduce the bug?

.vimrc
set binary noeol ft=text mouse=

### What is the expected behavior?

somehow disable the termux opt sys vimrc , i couldnt manage
im looking for full off
no smth tabspace and shit

### System information

termux-info:

```
~ $ termux-info
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~e1HjUlA0jZ6hm2PRQnFC6w==/com.termux-G9A9bkEcrl-QZetCeoJ75w==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=20123
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c216,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c216,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10216
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+93eafff
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+93eafff
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.accum.se/mirror/termux.dev/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
13
Kernel build information:
Linux localhost 5.15.41-android13-8-00005-g779f29f1a22b-ab9196663 #1 SMP PREEMPT Wed Oct 19 23:38:42 UTC 2022 aarch64 Android
Device manufacturer:
nubia
Device model:
NX729J
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by ChiefMikeK** [comment]
🤔copy and edit the default to $HOME  
`cat /data/data/com.termux/files/usr/share/vim/vimrc` :shipit:

**Comment by fxmbsw7** [comment]
thank you , sorry for later reply ..

i mv ed this share file away as my changes ( commenting ) and my .vimrc started to work

thank you

**Comment by ChiefMikeK** [comment]
please close this if fixed 🧷

**Comment by fxmbsw7** [comment]
ah i did press wrong button
yes sorry , peace , greets
