### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Jdgdb1837** [termux/termux-packages#16632]
### Problem description

Я установил пароль на термикс через Termux- login, но при входе  появляется ошибка:Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/login.py", line 10, in <module>
    filepass = open("/data/data/com.termux/files/usr/share/login/.pass", "r")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/share/login/.pass' ПОМОГИТЕ ПОЖАЛУЙСТА!!!

### What steps will reproduce the bug?

Ввод пароля

### System information

termux-info:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/login.py", line 10, in <module>
    filepass = open("/data/data/com.termux/files/usr/share/login/.pass", "r")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/share/login/.pass'

**Comment by xtkoba** [comment]
Duplicate of #14778.
