### ISSUE TITLE
[Package]: browsh

### ISSUE THREAD

**Issue by xronin01** [termux/termux-packages#16661]
### Why do you want to add this package to Termux?

Browsh is a fully-modern text-based browser. It renders anything that a modern browser can; HTML5, CSS3, JS, video and even WebGL. Its main purpose is to be run on a remote server and accessed via SSH/Mosh or the in-browser HTML service in order to significantly reduce bandwidth and thus both increase browsing speeds and decrease bandwidth costs.

### Home page URL

https://www.brow.sh

### Source code URL

https://github.com/browsh-org/browsh

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Yonle** [comment]
It is installable via the static binary.

> NOTE: Not available in most distribution package managers
