### ISSUE TITLE
[Update request]: Please update Clangd server

### ISSUE THREAD

**Issue by Duilio12** [termux/termux-packages#16682]
Clangd server is a tool that allows autocomplete in C/C++. It is included in Clang package, wich includes other tools like clang compiler. I have a problem. When I use it to get autocopletion, it doesn't show the documentation of the standard library. It does that in any prooted-distro, so I guess is not updated. With other languages I have not problems. I use it in vim with coc.nvim and in code-server. Thanks for reading!

**Comment by xtkoba** [comment]
I'm not sure what "the documentation of the standard library" denotes. The standard library we use in Termux is coming from Android NDK (packaged as `ndk-sysroot`) that does not bundle documentation AFAIK. I don't believe upstream LLVM suite (not NDK) provides any. If you mean "the standard library" the libc++ by LLVM project (`clang++ -stdlib=libc++ ...`) then note that our libc++ is also coming through NDK, which is kind of wontfix (#13247).

I'd like to mention that the `clangd` itself in our package is the latest upstream release version:

```
$ clangd --version
clangd version 16.0.3
Features: linux
Platform: aarch64-unknown-linux-android24
```

**Comment by thunder-coding** [comment]
/

**Comment by thunder-coding** [comment]
> When I use it to get autocopletion, it doesn't show the documentation of the standard library.

Make sure you are having `compile_commands.json` enabled when building your project with CMake/whatever build system you use. CMake does have a `-DCMAKE_EXPORT_COMPILE_COMMANDS=On` option to do that. And in your clangd plugin for your editor just simply set your project's build directory/path to `compile_commands.json`. As far as I remember last time when I used it, it worked pretty well.

Also apologies for closing and reopening the issue (was accidental)

**Comment by DuilioPerez** [comment]
Hello everyone!

I've used clangd in termux for autocompletion, and I think this is a partial bug. Some functions, without a compile_commands.json, show its documentation. I think that it could be that there is a bug with this documentation. I post here a screenshot of my neovim with a pop up of documentation of malloc, printf and free. It only shows the correct documentation of malloc.
![C_documentation](https://github.com/termux/termux-packages/assets/135564120/ae743a5d-0027-4669-8469-77f5d77c0e11)
