### ISSUE TITLE
Today's upgrade of texlive-bin breaks XeLaTeX and pdfLaTeX

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#1668]
Two problems:

1. After the upgrade the links to executable binaries disappear, i.e. executing "xelatex" results in "command not found". This is fixed by running `texlinks` command, but it shouldn't be necessary.

2. After running `texlinks` nothing actually works, i.e. trying to compile anything fails _before_ it even has a chance to write to the log file, so I can't even see why it is failing. I'll have to strace it to see what's wrong.

So, at the moment TeX Live in Termux is unusable.

**Comment by tigran123** [comment]
Here is the error message (I have enabled the standard error output from pdflatex command):

```
Can't locate TeXLive/TLUtils.pm in @INC (you may need to install the TeXLive::TLUtils module) (@INC contains: /data/data/com.termux/files/usr/opt/texlive/2017/tlpkg /data/data/com.termux/files/usr/opt/texlive/2017/texmf-dist/scripts/texlive /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.1 /data/data/com.termux/files/usr/lib/perl5/5.26.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.26.1 .) at /data/data/com.termux/files/usr/opt/texlive/2017/bin/custom/mktexfmt line 46.
BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/opt/texlive/2017/bin/custom/mktexfmt line 46.
I can't find the format file `pdflatex.fmt'!
```

**Comment by Grimler91** [comment]
Try reinstalling texlive: `apt install texlive --reinstall`. That should recreate the missing files. 

That being said, I should look over the preinst/postinst scripts..

**Comment by tigran123** [comment]
Thank you, yes, that solved the problem. Both xelatex and pdflatex work fine.

**Comment by tigran123** [comment]
Good news: today's upgrade of texlive did _not_ break anything! Tested both xelatex and pdflatex.

Btw, it would be nice if there was a way to set the value of SHELL variable in the Makefile in a way that works both in Termux and in normal Linux environment. Currently I have to edit the Makefile manually to switch between the values:

```
SHELL = /bin/bash
```

and 

```
SHELL = /data/data/com.termux/files/usr/bin/bash
```
The above full path I enter by using a vi command `:r! which bash` of course.

The following naive attempt wouldn't work as `make(1)` complains about the recursive use of shell:

```
SHELL = $(shell which bash)
```

Any better suggestions?
