### ISSUE TITLE
Tcpdump permissions

### ISSUE THREAD

**Issue by Dragonbreak** [termux/termux-packages#1669]
Attempting to run tcpdump as standard user gives this error:
     tcpdump: Can't open netlink socket 13:Permission denied

Attempting to run as root (tsu) provides this error:
     CANNOT LINK EXECUTABLE: cannot locate symbol "OpenSSL_add_all_algorithms" referenced by 
      "tcpdump"...page record for 0xb6ef004c was not found (block_size=64)

Searching on google brought some information that it's a permissions issue. However, it seems that the internet permissions option that *may* fix the issue is missing. Is there a way to fix this, or some other pcap package that can be run within termux?

Phone specs:
     Android 6.0
     Galaxy S5
     ROOTED:True

**Comment by xeffyr** [comment]
After **tsu** try this commands:
```
# export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
# export PATH=/data/data/com.termux/files/usr/bin
# tcpdump
```
If this not work, check that **openssl** is installed.
