### ISSUE TITLE
Termux Biggest Missing Thing!

### ISSUE THREAD

**Issue by stainslav** [termux/termux-packages#1670]
GUI Support in termux till when it's coming 2 yearsnow there is no trace of it!
Please @fronwall what about progress on GUI Support to termux?

**Comment by Auxilus** [comment]
I don't think GUI is necessary for us right now.

**Comment by stainslav** [comment]
@Auxilus
wxpython and more libraries needs GUI but selinux is the biggest problem have you tried to build GUI Support?

**Comment by sdrausty** [comment]
@stainslav How are you going to use a GUI on a smartphone screen?  Try it before you reply, and not just to see if it works, but see if you can enjoy using it for a week or more.  Then when you have a firm opinion about this topic, post your user experience here.

**Comment by KedalionDaimon** [comment]
It has Midnight Commander. That should suffice. Rumour has it that Android itself might offer a so-called "GUI"... ;)

**Comment by Auxilus** [comment]
![screenshot_20171214-000114](https://user-images.githubusercontent.com/23075789/33955553-f093d1b0-e061-11e7-8006-f685dbea414d.png)

This ks currently what we have 
Take a look at
https://github.com/xeffyr/termux-x-repository

**Comment by xeffyr** [comment]
@Auxilus, stainslav already have GUI since he use https://github.com/xeffyr/termux-rootfs

**Comment by sdrausty** [comment]
How to use Xorg in TermuxArch?   https://github.com/sdrausty/TermuxArch/issues/27

**Comment by sdrausty** [comment]
@stainslav 
> [ getting X up and running](https://github.com/sdrausty/TermuxArch/issues/59#issuecomment-374852283)

There are a number of ways to accomplish this goal today, including Arch Linux in Termux PRoot.  Screenshots from Android smartphone:

[![screenshot_20180326-165002](https://user-images.githubusercontent.com/27742457/37932154-c4833304-3115-11e8-9821-9d9f144d648b.png)](https://github.com/sdrausty/TermuxArch/issues/59)


[![screenshot_20180413-172406](https://user-images.githubusercontent.com/27742457/38758637-ec0ff0dc-3f3f-11e8-802c-82bc511cde88.png)](https://sdrausty.github.io/TermuxArch/docs/install)

**Comment by Yisus7u7** [comment]
@stainslav 
It does not seem silly to me, x11 termux is also a good alternative for low-income cell phones, apart from the project has grown a lot in these 2 years ...
And I don't know if you knew, but you can create a proot container and install programs there, then run them in termux x11 using xhost, you can emulate firefox and other things


![Screenshot_20210626-220430](https://user-images.githubusercontent.com/64093255/123590788-bf61b680-d7b0-11eb-9974-082f5e88f688.png)

![Screenshot_20210627-014123](https://user-images.githubusercontent.com/64093255/123590786-be308980-d7b0-11eb-8ca0-c79efb47a72b.png)
[Screenshot_20210627-013815](https://user-images.githubusercontent.com/64093255/123590779-bb359900-d7b0-11eb-963f-9b0eba01decc.png)
![Screenshot_20210627-014015](https://user-images.githubusercontent.com/64093255/123590782-bc66c600-d7b0-11eb-9b6b-07c41d25043c.png)
