### ISSUE TITLE
[Bug]: neovim "Man" command is broken by termux patch

### ISSUE THREAD

**Issue by ajpaon** [termux/termux-packages#16720]
### Problem description

Neovim provides a plugin for viewing man pages in the editor. It's broken in termux, and I'll explain why. 

The plugin works by using the `man` command to find the path to the man file.

When neovim was updated to 0.9 on termux, a change was made to this patch: packages/neovim/runtime-lua-man.lua that causes the plugin to use `mandoc` to find the file path.

https://github.com/termux/termux-packages/commit/ebeb10fa03691ed000e3259edc83e7f9f229116f

So now, instead of running (for example)

```
$ man -w man
/data/data/com.termux/files/usr/share/man/man1/man.1.gz
/data/data/com.termux/files/usr/share/man/man7/man.7.gz
```

We do 

```
$ mandoc -w man
mandoc: man: BADARG: bad command line argument: No such file or directory
```

This error message is swallowed by the lua plugin - it really took some dedicated debugging to find the cause!

When I manually revert this change and use `man` instead of `mandoc`, the plugin works again.

It's not at all clear to me what the rationale for using `mandoc` here was. It's not mentioned in the commit and it's not explained in the comment change. I think it was probably an accident; AFAICT no version of `mandoc` supports the `-w` switch.

### What steps will reproduce the bug?

Running this command in neovim

```
:Man strace
```

Results in the error

```
man.lua: "no manual entry for strace"
```

This is reproducible starting from `nvim -u NORC`, which runs neovim without my custom config.

On the other hand, running `man strace` in bash works fine.

### What is the expected behavior?

The man page should open

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=9706
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
clang/stable 16.0.4 aarch64 [upgradable from: 16.0.3]
curl/stable 8.1.0 aarch64 [upgradable from: 8.0.1]
dos2unix/stable 7.5.0 aarch64 [upgradable from: 7.4.4]
dpkg/stable 1.21.22 aarch64 [upgradable from: 1.21.21]
fribidi/stable 1.0.13 aarch64 [upgradable from: 1.0.12]
golang/stable 3:1.20.4-1 aarch64 [upgradable from: 3:1.20.4]
libcompiler-rt/stable 16.0.4 aarch64 [upgradable from: 16.0.3]
libcurl/stable 8.1.0 aarch64 [upgradable from: 8.0.1]
libllvm/stable 16.0.4 aarch64 [upgradable from: 16.0.3]
libmpfr/stable 4.2.0-p9-0 aarch64 [upgradable from: 4.2.0-p7-0]
librav1e/stable 0.6.6 aarch64 [upgradable from: 0.6.5]
libsqlite/stable 3.42.0 aarch64 [upgradable from: 3.41.2]
libxml2/stable 2.11.4 aarch64 [upgradable from: 2.11.3]
lld/stable 16.0.4 aarch64 [upgradable from: 16.0.3]
llvm/stable 16.0.4 aarch64 [upgradable from: 16.0.3]
sqlite/stable 3.42.0 aarch64 [upgradable from: 3.41.2]
termux-tools version:
1.38.1
Android version:
13
Kernel build information:
Linux localhost 5.4.147-qgki-25884040-abT733XXU2CWC5 #1 SMP PREEMPT Thu Mar 30 20:32:41 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T733
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
The commit was "branched" from `neovim-nightly` package. The actual change was made in 7137f6dea116f50381cd2a5d9793fa8e3356aeba. Still no description though.

**Comment by ajpaon** [comment]
Thanks @xtkoba. I think it's a bug in both places :)

I just installed `neovim-nightly` and reproduced it there too

**Comment by ajpaon** [comment]
may I send a PR to fix this patch?

**Comment by Grimler91** [comment]
> may I send a PR to fix this patch?

Please go ahead
