### ISSUE TITLE
[Bug]: nvim broken by latest update

### ISSUE THREAD

**Issue by alexfarseer** [termux/termux-packages#16730]
### Problem description

So I updated today, and it was around 14 packages. I don't recall which packages exactly but `nvim` got broken after that.

### What steps will reproduce the bug?

Just open `nvim`. Here is the output:
```
$ nvim
Bad system call
```

Here is the strace log: https://gist.github.com/alexfarseer/138d067dbe36ae81824b62339eb44822

### What is the expected behavior?

`nvim` should work.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12420
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
13
Kernel build information:
Linux localhost 5.10.149-android13-4-00003-gebdbc9fbe2e2-ab9664856 #1 SMP PREEMPT Mon Feb 27 10:44:09 UTC 2023 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 6a
LD Variables:
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/opt/lib:
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by alexfarseer** [comment]
Found the problem, `libuv-1.45.0` is the source of the bug. I fixed it by downgrading to `1.44.2` with `apt install libuv=1.44.2`. So `nvim` is temporarily fixed.

**Comment by linusjf** [comment]
> 

This does not work for me.

```bash
apt install libuv=1.44.2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libuv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '1.44.2' for 'libuv' was not found
```

**Comment by alexfarseer** [comment]
@linusjf Looks like the mirrors have removed the old version. You can try different mirrors or wait for it to be resolved.

**Comment by xtkoba** [comment]
Mine. Already specified. Will be fixed in a few hours. Sorry for your inconvenience.

**Comment by linusjf** [comment]
> @linusjf Looks like the mirrors have removed the old version. You can try different mirrors or wait for it to be resolved.

How do you check which versions of packages are available in the repositories?
