### ISSUE TITLE
[Bug]: build failed  lua-language-server arm+i686

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#16751]
### Problem description

                                                   ^
3rd/bee.lua/bee/net/socket.cpp:545:77: error: cannot initialize a parameter of type 'socklen_t *' (aka 'int *') with an rvalue of type 'bee::net::socklen_t *' (aka 'unsigned int *')
        const int ok   = ::getsockopt(s, SOL_SOCKET, SO_ERROR, (char*)&err, &errl);
                                                                            ^~~~~
/home/builder/.termux-build/_cache/android-r25c-api-24-v2/bin/../sysroot/usr/include/sys/socket.h:315:92: note: passing argument to parameter '__value_length' here
__socketcall int getsockopt(int __fd, int __level, int __option, void* __value, socklen_t* __value_length);
                                                                                           ^
5 errors generated.
[5/85] Compile C++ build/obj/source_bee/filewatch_linux.obj
[6/85] Compile C++ build/obj/source_bee/format.obj
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.

[logs_31.zip](https://github.com/termux/termux-packages/files/11549532/logs_31.zip)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
This can happen because as of now our auto-updater only checks buildability of packages for aarch64 target.

CI: https://github.com/termux/termux-packages/actions/runs/5057186797

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/actions/runs/5266958109/jobs/9521585077

https://github.com/termux/termux-packages/commit/5b5c3b70dc5c2d0792de4184de19964cc59190ba
