### ISSUE TITLE
[Bug]:  neovim-nightly build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#16761]
### Problem description

Downloading https://github.com/neovim/neovim/archive/nightly.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 39609    0 39609    0     0  52621      0 --:--:-- --:--:-- --:--:-- 52621
100 5545k    0 5545k    0     0  3190k      0 --:--:--  0:00:01 --:--:-- 5584k
100 10.8M    0 10.8M    0     0  4044k      0 --:--:--  0:00:02 --:--:-- 5553k
100 11.1M    0 11.1M    0     0  4011k      0 --:--:--  0:00:02 --:--:-- 5441k
Wrong checksum for https://github.com/neovim/neovim/archive/nightly.tar.gz:
Expected: 783dfad368dc36e4f7fe26d39ba08ec0b346e7f34cb414f4e05450559d867f21
Actual:   2fc3db8831584794c1b9c16d2cfefa1d9967f0dd222b5e122ea3b8dafe240f82
Error: Process completed with exit code 1.

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Due to nondeterministic source. Pretty much expected.

**Comment by xtkoba** [comment]
See also #16366. `neovim-nightly` is not updated now.
