### ISSUE TITLE
GnuPG unable to send keys to keyserver

### ISSUE THREAD

**Issue by LissieTilbrook** [termux/termux-packages#1677]
This is not a duplicate of #852. Instead, I created a GPG key and need to send it to hkp://keyserver.ubuntu.com . The error I get is

gpg: no handler for keyserver scheme `hkp'

(I'm on mobile so I can't do markup)

I need to do this so I can help my partner submit her GPG key for her Launchpad, https://launchpad.net/~alexatilbrook and we don't have access to a computer at this moment.

**Comment by Grimler91** [comment]
Did you try installing `gnupg-curl`, as described in #852?

**Comment by Grimler91** [comment]
Closing due to lack of response.
