### ISSUE TITLE
Termux - Primeiros Comandos - PTBR

### ISSUE THREAD

**Issue by J0nathan-xyz** [termux/termux-packages#16781]
Termux - Comandos Iniciais

# Alguns comandos iniciais do Termux, para iniciantes:

$ apt update (utilize o -y se preferir) 
$ apt upgrade (utilize o - y se preferir) 

Ou experimente o comando:

$ apt update -y && apt upgrade -y

Que assim irá fazer os 2 comandos de uma só vez. 

Esses dois primeiros comandos são essenciais para atualizar o repositório atual. Utilizem todas as vezes que abrir o Termux, ou que abrir uma nova aba, para garantir que não ocorra erros. 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Agora vem os comandos essenciais para instalar qualquer pacote dentro do termux. 
(Não se preocupe se tem todos os comandos ou não, você sempre vai atualizar seu vocabulário, aprendendo novos comandos com o decorrer do uso do app e com alguns tutoriais no YouTube ou no GitHub). 

ATENÇÃO! Utilize o comando: 

$ termux-change-repo 

Caso algum pacote ou alguma ferramenta, não instale, utilize esse comando acima, para mudar o repositório. 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 

Principais comandos para a instalação da grande maioria dos pacotes:

$ apt update

$ apt upgrade

$ apt install python

$ apt install python2

$ apt install python3

$ apt install python-pip

$ apt install python3-pip

$ apt install ruby

$ apt install curl

$ apt install perl

$ apt install wget

$ apt install git

$ apt install hydra

$ apt install nmap

$ apt iinstall nano

$ apt install clang

$ apt install php

$ apt install tor

$ apt install pip

$ apt iinstall sqlmap

$ apt install gcc

Em todos os comandos, após executá-lo, se aparecer uma mensagem para confirmar, com: (Y/n), apenas dê enter, ou por precaução, digite Y e tecle enter para continuar. 

Os principais pacotes estão instalados no seu termux, agora é só vê alguns tutoriais no YouTube, de como executar cada um deles, e para que serve. 

Obrigado pela atenção.

**Comment by twaik** [comment]
Official language of Termux project is English...

**Comment by twaik** [comment]
Also there is [Getting started](https://wiki.termux.com/wiki/Getting_started) page and [wiki](https://wiki.termux.com/wiki/Main_Page) so there is no need in instructions like these.

**Comment by J0nathan-xyz** [comment]
> Also there is [Getting started](https://wiki.termux.com/wiki/Getting_started) page and [wiki](https://wiki.termux.com/wiki/Main_Page) so there is no need in instructions like these.

I was wanting to leave it private just for myself, or erase it, how do I do it?

**Comment by twaik** [comment]
> > Also there is [Getting started](https://wiki.termux.com/wiki/Getting_started) page and [wiki](https://wiki.termux.com/wiki/Main_Page) so there is no need in instructions like these.
> 
> I was wanting to leave it private just for myself, or erase it, how do I do it?

@agnostic-apollo  can you please help?

**Comment by agnostic-apollo** [comment]
I assume you want to delete the issue. Doing that now.
