### ISSUE TITLE
[Bug]: bash: cd: termux-login: No such file or directory termux not login 

### ISSUE THREAD

**Issue by Mahesh7776** [termux/termux-packages#16789]
### Problem description

![Screenshot_20230530_163852](https://github.com/termux/termux-packages/assets/96675595/908eaed1-ad30-44c3-b09d-ff1491e92b25)

### What steps will reproduce the bug?

Termux not loging 

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
Not an issue of our packages.
