### ISSUE TITLE
[Bug]: less: segfault with /!^

### ISSUE THREAD

**Issue by landfillbaby** [termux/termux-packages#16795]
### Problem description

running `less '+/!^X'` or typing `/!^X<enter>` in a `less` session, will for most input and `X`, cause a (possibly not immediate) segmentation fault.
i've checked on my PC and it seems this is probably Termux-specific.
i haven't figured out what's causing it so i've opened an issue instead of a pr :/

https://github.com/gwsw/less/issues/125 may be relevant?

edit: oh of course it's an issue with `/!...$` too...

### What steps will reproduce the bug?

here's a few example outcomes (assuming it isn't set to `--quit-if-one-screen`).

all i've tested are the same whether it's a command-line argument to less or run from within a session.

`less '+/!^'` with any non-empty input immediately segfaults.
`echo -e 'a\nb' | less '+/!^a'` segfaults if you try to scroll back up afterwards.
`echo a | less '+/!^a'` segfaults after the pattern not found error is cleared.
`echo a | less '+/!^b'` or `echo -e 'a\nb' | less '+/!^c'` don't segfault.

### What is the expected behavior?

no segfault!

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21539
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_PKG_NO_MIRROR_SELECT=1
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
13
Kernel build information:
Linux localhost 5.10.149-android13-4-00003-gebdbc9fbe2e2-ab9664856 #1 SMP PREEMPT Mon Feb 27 10:44:09 UTC 2023 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 6
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.styling versionCode:30
```

**Comment by xtkoba** [comment]
Maybe not Termux-specific? The following command causes `less` to segfault on my GNU/Linux (Gentoo) system as well as on Termux:

```bash
echo -e 'hi\nhello' | less '+/!^...$'
```

Version (both for GNU/Linux and Termux):

```
$ less --version
less 633 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by landfillbaby** [comment]
oh oops. i was working with an older version of less on my pc. 590 via ubuntu.
and i just went to check, it was fixed in https://github.com/gwsw/less/commit/8320d1a920a90599892b9aca2306822709dab8f7 earlier today

**Comment by landfillbaby** [comment]
https://github.com/termux/termux-packages/commit/615f387a2e20e664e49a351fbfab5ba187b3dba2
