### ISSUE TITLE
proot called from termux-chroot exits with signal 6

### ISSUE THREAD

**Issue by sp4rkie** [termux/termux-packages#1679]
I'm currently writing a script allowing an [automated install of debian 9 (stretch)](https://github.com/sp4rkie/debian-on-termux/) in a termux environment. The guest system is entered via proot. Sometimes during the installation process proot exits ungracefully with signal 6 like this:

```
./path/proc.c:52: Action readlink_proc(const Tracee *, char *, const char *, const char *, Comparison): assertion "comparison == compare_paths("/proc", base)" failed
proot warning: signal 6 received from process 13277
```
I experimented a little to find an easy way to reproduce the problem:
just call 
```
termux-chroot
```
and execute
```
ls -l /proc
```
==> signal 6 is hit instantly

any idea what is going on here?

**Comment by xeffyr** [comment]
Have you directory /proc/device-tree ? On my device (Samsung galaxy s7) proot fails when accesses this directory.
I have modified source code by commenting line 52 in src/path/proc.c:
```
assert(comparison == compare_paths("/proc", base));
```
This solution maybe invalid, but after that proot works fine.

**Comment by sp4rkie** [comment]
yeah, `/proc/device-tree` exists here too. Thanks for the tip. I will later try it and report the results.

**Comment by sp4rkie** [comment]
ok, encommenting the assertion 'solves' the problem for me too. At least I can't see any undesired side effects until now:-)

**Comment by sp4rkie** [comment]
I attached the patched proot package. 

```
--- proot/src/src/path/proc.c.1 2017-08-27 19:25:21.000000000 +0200
+++ proot/src/src/path/proc.c   2017-10-23 10:58:54.744586370 +0200
@@ -49,7 +49,7 @@
        int status;
        pid_t pid;
 
-       assert(comparison == compare_paths("/proc", base));
+//     assert(comparison == compare_paths("/proc", base));
 
        /* Remember: comparison = compare_paths("/proc", base)  */
        switch (comparison) {
```

[Uploading proot_5.1.106-3_arm.deb.gz…]()

**Comment by sp4rkie** [comment]
[Uploading proot_5.1.106-3_arm.deb.gz…]()

test
upload does not work

**Comment by maidenone** [comment]
I also have this issue on my S8, can you compile it for aarch64 as well? maybe make a pull request in the proot repo? I have also checked out the proot repo made the changes but have failed to figure out how to cross compile it...

**Comment by xeffyr** [comment]
@maidenone [proot_5.1.106-3_aarch64.deb.gz](https://github.com/termux/termux-packages/files/1482302/proot_5.1.106-3_aarch64.deb.gz)

**Comment by sp4rkie** [comment]
the package was published 5 days ago: https://github.com/termux/proot/issues/5#issuecomment-343724509

**Comment by maidenone** [comment]
I had proot 5.1.106-3 installed and it was the latest according to apt but it did not contain the patch above as i got the same proc.c:52 issue.
I checked the termux proot repo and did not see any related changes there.

**Comment by sp4rkie** [comment]
>  I checked the termux proot repo and did not see any related changes there.

committed 7 days ago

https://github.com/termux/proot/commit/16a6181f31d005044b5a04b49ab978780b7a0334

**Comment by maidenone** [comment]
But still: https://github.com/termux/proot/blob/master/src/path/proc.c
