### ISSUE TITLE
[Package]: dircord

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#16794]
### Why do you want to add this package to Termux?

Discord <--> IRC bridge

### Home page URL

https://karx.xyz/projects/dircord/

### Source code URL

https://git.karx.xyz/karx/dircord

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
> Packages must be active, well-known projects

> Software available in major Linux distributions has more chances to be included into Termux repositories. We will not accept outdated, dead projects as well as projects which do not have active community.

You can submit this package request in [tur](https://github.com/termux-user-repository/tur) .
