### ISSUE TITLE
eSpeak floating point exception

### ISSUE THREAD

**Issue by Quasic** [termux/termux-packages#1680]
I tried reinstalling, but no help. Can anyone reproduce? This happens in some form in every invocation I've tried, but the cleanest failure was the form:
espeak -f file.txt -w file.wav

I believe it updated a while ago, but this is the first time I've tried to use it since then.  It was working before.

**Comment by Quasic** [comment]
Sorry, I forgot to say it was running in Lollipop on arm.

**Comment by Grimler91** [comment]
I was able to reproduce the error on my arm device. 

The error disappeared when building with debug symbols, so it is most likely the -Oz flag that is causing this and a patch similar to the one in [texlive-bin](https://github.com/termux/termux-packages/blob/master/packages/texlive-bin/build.sh#L127) probably solves it. 
I can test it and open a pull request tomorrow unless you or someone else beats me to it 
(feel free to beat me to it).

**Comment by fornwall** [comment]
Thanks to @Grimler91 the updated 1.49.2-1 version of the espeak package should now be fixed - update to it with `pkg up`!

**Comment by Quasic** [comment]
Thank you! I confirmed it's working again!

**Comment by Quasic** [comment]
So do I. Android version doesn't seem to matter. (I tried on 5 and 7.) It could be the same problem come back, but it could be something new. Maybe we should start a new issue, since this one was resolved?

**Comment by Quasic** [comment]
@Grimler91, any insights? I'm currently not set up to try building.

**Comment by xeffyr** [comment]
@Quasic This can be a regression introduced after 32de55cecea124fcf38c86487d94ef28b0ea8e68.

**Comment by xeffyr** [comment]
I pushed https://github.com/termux/termux-packages/commit/c004c92cc459fa3b990029f3b74c501ce7587ff7, so updated android-7 package will be available soon.

**Comment by xeffyr** [comment]
@Quasic Could you try `espeak` 1.49.2-3 (android 7) ?

**Comment by pschwede** [comment]
With my new Android 9.0 it works without errors out of the box. However I cannot hear a thing.

**Comment by Quasic** [comment]
It works for me, too, thanks!

@pschwede, the ```espeak <<<hello``` command specifies no output. Try ```espeak --stdout <<<hello|play -``` (For some reason, I had to install cmus before that worked. I wonder if a dependency is missing from Sox.)
