### ISSUE TITLE
[Package]: zig (latest)

### ISSUE THREAD

**Issue by SunPodder** [termux/termux-packages#16806]
### Why is it worth to add this package?

Current zig in termux is `0.9.1`. Many breaking changes have been added since then and v0.9.1 is now incompatible with the latest zig (0.10.1).

### Source code URL

https://github.com/ziglang/zig

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

Latest release (0.10.1) uses `llvm-15` and current master branch uses `llvm-16`. Termux llvm version is also 16 if this is something to be considered.

Also using zig from `termux_setup_zig` to build the latest version won't work. It installs zig 0.9.1 which doesn't work with the latest codebase.

**Comment by thunder-coding** [comment]
There has been a failed attempt of trying to build zig 0.10.0 in #12720

**Comment by truboxl** [comment]
I think its better to use master branch. LLVM in Termux is already upgraded to 16.

If we must use zig 0.10.1, there will lots of backports to work with Termux's LLVM...

**Comment by SunPodder** [comment]
![Screenshot_20230803-230809_Termux](https://github.com/termux/termux-packages/assets/73415680/4b4a69e8-2c1c-4b9e-b547-5a576f782c4c)

[Zig](https://ziglang.org/builds/zig-linux-aarch64-0.11.0-dev.4410+76f7b40e1.tar.xz) from the official release working fine on Termux.
Maybe termux can distribute a shell script to download and install that if we are having trouble building it? I can install that manually, but I'm saying this cause the current version of zig in termux is obsolete anyway.
