### ISSUE TITLE
elinks segfaults at termux.com

### ISSUE THREAD

**Issue by Quasic** [termux/termux-packages#1682]
I'm writing this from elinks in termux. It works great, but for some reason, whenever I click a link to termux.com, it segfaults. If I use the command ```elinks http://termux.com```  it segfaults after displaying "SSL negotiation" Can anyone reproduce?

**Comment by vishalbiswas** [comment]
I can reproduce this on arm API 23.

"On Desktop, I get Unable to retrieve https://termux.com/: SSL Error"

**Comment by Quasic** [comment]
Sorry, I forgot to say it was running in Lollipop on arm.

**Comment by fornwall** [comment]
Generally, lynx is the only maintained terminal browser - elinks is abandoned, without fixes or support from upstream.

A possible way forward would be to setup at least `elinks` as a symlink to `lynx`, so that users running `elinks` out of habit gets a maintained browser instead. What do you say about that?

**Comment by Neo-Oli** [comment]
> lynx is the only maintained terminal browser

The w3m fork we're using is pretty well maintained. I've found it working the best of the three. Lynx has a lot of screen garbage when used within tmux. 

I am missing the gopher support in w3m (it's unclear if that is even possible, but Wikipedia lists w3m as a gopher client).

Just my 2 cents. Not really anything relevant to this issue.

**Comment by Quasic** [comment]
Since someone asked in the other thread, http://termux.com gives the same segfault during SSL negotiation, as I think it redirects to https.

I originally installed lynx, but like having a backup browser, so tried elinks. I found its interface intuitive and it seemed to work better with my setup, at the time, so lynx became my backup. I might switch back, but I'd probably like to keep elinks around...maybe note in the description that it's unmaintained, if you don't disable it.

**Comment by xeffyr** [comment]
Elinks closes socket before freeing the ssl structure (and this causes a crash):

src/network/ssl/socket.c:
```
int
ssl_close(struct socket *socket)
{
    ssl_do_close(socket);
    done_ssl_connection(socket);

    return 0;
}
```

src/network/ssl/ssl.c:
```
void
done_ssl_connection(struct socket *socket)
{
    ssl_t *ssl = socket->ssl;

    if (!ssl) return;
#ifdef CONFIG_OPENSSL
    SSL_free(ssl);
#elif defined(CONFIG_GNUTLS)
    gnutls_deinit(*ssl);
    mem_free(ssl);
#endif
    socket->ssl = NULL;
}
```

I can provide patch that fixes crash but elinks will show SSL error on https://termux.com. Other sites (google.com or such) will work.

**Comment by xeffyr** [comment]
I have rebuild elinks without any patches and it not crashes but shows SSL error.

**Comment by xeffyr** [comment]
Tried [git version](http://elinks.cz/elinks.git/) of elinks - everything works.

**Comment by fornwall** [comment]
The updated version is now available for installation (`pkg up`) - thanks @xeffyr !

**Comment by Quasic** [comment]
Sorry to post late, but I did confirm the problem no longer occurs after updating. Thank you!

In the meantime, I found I really do like w3m's use of screen space, though it gives warnings of memory leaks and things, so now I have 2 backups. ;-)
