### ISSUE TITLE
[Package]: r-base

### ISSUE THREAD

**Issue by i2z1** [termux/termux-packages#16820]
### Why is it worth to add this package?

R is a free software environment for statistical computing and graphics. Like Python and Julia, R is the one of core languages for data analysis and ML.

 R can be extended with various additional packages (most known is [CRAN](https://cran.r-project.org/mirrors.html) -- Comprehensive R Archive Network).

With additional packages it can be used for Tex generation and even web application development (thanks to [Shiny framework](https://shiny.posit.co/)) 

### Home page URL

https://www.r-project.org/

### Source code URL

https://github.com/wch/r-source

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by j0hnd3v** [comment]
#250
