### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by amitkumar0128** [termux/termux-packages#16830]
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libcurl.so in namespace (default) 
This is what it shows 
![Uploading Screenshot_20230603-134601.jpg…]()

**Comment by 2096779623** [comment]
Please provide `termux-info` output.

**Comment by xtkoba** [comment]
Could happen with partial upgrading which is not supported.
