### ISSUE TITLE
[Package]: kdenlive

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#16837]
### Why is it worth to add this package?

I want to use a video editor inside termux. In android, the most video editor needs a premium subscription. But kdenlive is free software. I think it could work in termux. I know that it is available only in ubuntu and arch, so I understand why is not in termux repositories.

### Home page URL

https://kdenlive.org

### Source code URL

https://github.com/KDE/kdenlive

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

This is the installation guide:
https://github.com/KDE/kdenlive/blob/master/dev-docs/build.md

**Comment by dontknowhy** [comment]
You may want to ask Kdenlive team to port their video editor to Android.
Because Krita has already did it🤔.
