### ISSUE TITLE
Can't install texlive?

### ISSUE THREAD

**Issue by TheWithz** [termux/termux-packages#1685]
termux on google pixel C android tablet non root Oreo 8.0.0

Googled how to install pdflatex because i need it for a project, came upon a bunch of resources that say to run `termux-install-tl` however, when I do it. I get a `command not found` error.

```u0_a111:@:localhost:[/data/.../files/home]:[15:32:57]> apt update
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
u0_a111:@:localhost:[/data/.../files/home]:[15:33:08]> apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
u0_a111:@:localhost:[/data/.../files/home]:[15:33:11]> termux-install-tl
termux-install-tl: command not found
u0_a111:@:localhost:[/data/.../files/home]:[15:33:26]>```

**Comment by tigran123** [comment]
did you try the command `pkg install texlive`?

**Comment by Grimler91** [comment]
termux-install-tl was the way to go up until a few months ago. Now days it is installable through apt/pkg as tigran said.

**Comment by TheWithz** [comment]
I installed through apt and it's working fine. Sorry for the confusion.
