### ISSUE TITLE
[Bug]: installing packages via pip is not working. 

### ISSUE THREAD

**Issue by Alixan77** [termux/termux-packages#16879]
### Problem description

while installing packages using pip is giving errors from yesterday.  I tried installing Telethon pyrogram licensing tgcrypto and other packages all of them are giving the same error. 
`~/a $ pip install telethon
Collecting telethon
  Downloading Telethon-1.28.5-py3-none-any.whl (600 kB)
     ━━━━━━━━━━━━━━ 600.9/600.9   119.9 kB/s eta 0:00:00
                    kB
Collecting pyaes (from telethon)                          Downloading pyaes-1.6.1.tar.gz (28 kB)
  Installing build dependencies ... done                  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: [('/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info/PKG-INFO', '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info.bkp/PKG-INFO', "[Errno 13] Permission denied: '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info.bkp/PKG-INFO'"), ('/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info/dependency_links.txt', '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info.bkp/dependency_links.txt', "[Errno 13] Permission denied: '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info.bkp/dependency_links.txt'"), ('/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info/top_level.txt', '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info.bkp/top_level.txt', "[Errno 13] Permission denied: '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info.bkp/top_level.txt'"), ('/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info/SOURCES.txt', '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info.bkp/SOURCES.txt', "[Errno 13] Permission denied: '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info.bkp/SOURCES.txt'"), ('/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info', '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info.bkp', "[Errno 13] Permission denied: '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-w3nrlymt/pyaes.egg-info.bkp'")]
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

### What steps will reproduce the bug?

![photo_2023-06-09_19-47-02](https://github.com/termux/termux-packages/assets/75313960/497a251c-1d78-4f9e-a9d1-c0fce15de0d2)

### What is the expected behavior?

I think problem on the new python release or metada

### System information

termux-info:

```
~/a $ termux-info
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=13540
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
13
Kernel build information:
Linux localhost 4.14.190-perf-g019d15b3d168 #1 SMP PREEMPT Thu Feb 23 13:10:28 UTC 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2101K6G
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
Most likely due to https://github.com/python/cpython/commit/2e457bc202179445cbf7b3a2a96c8450f1cda72f. I'm going to "revert" this.

**Comment by Alixan77** [comment]
> Most likely due to [python/cpython@2e457bc](https://github.com/python/cpython/commit/2e457bc202179445cbf7b3a2a96c8450f1cda72f). I'm going to "revert" this.

when problem will be solved

**Comment by Alixan77** [comment]
I checked now, problem is solved. thanks to developers
