### ISSUE TITLE
libfdk-acc library

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-packages#1688]
is it possible to have this on termux?

**Comment by Auxilus** [comment]
https://github.com/mstorsjo/fdk-aac  is this what you are talking about?

**Comment by kurokirasama** [comment]
if it's the same to what described here:[ https://trac.ffmpeg.org/wiki/Encode/AAC]( https://trac.ffmpeg.org/wiki/Encode/AAC), then yes

**Comment by fornwall** [comment]
Out of interest - why do you want to use fdk-aac over the native AAC Encoder in ffmpeg?

**Comment by kurokirasama** [comment]
a long time ago, i converted some mp3 to aac using  native AAC Encoder, but i didn't liked the quality. Knowing termux recently, i looked into it again i found out that supposedly fdk-aac library gives better results...

**Comment by kurokirasama** [comment]
I tried to compile using what is described [here](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu):
```
pkg install autoconf automake libtool
mkdir ~/ffmpeg_sources
cd ~/ffmpeg_sources
wget -O fdk-aac.tar.gz https://github.com/mstorsjo/fdk-aac/tarball/master
tar xzvf fdk-aac.tar.gz
cd mstorsjo-fdk-aac*
autoreconf -fiv
./configure --prefix="$HOME/ffmpeg_build" --disable-shared
make
make install
```
Everything went fine, except for 1 warning when running `make install`:
`/data/data/com.termux/files/home/ffmpeg_sources/mstorsjo-fdj-aac-cf697df/libtool: 1: eval: ldconfig: Permission denied`
And ffmpeg still doesn't recognize the library...

**Comment by fornwall** [comment]
@kurokirasama My understanding is that the native AAC encoder in ffmpeg has been improved a lot the last couple of years - see e.g. http://git.videolan.org/?p=ffmpeg.git;a=commit;h=d9791a8656b5580756d5b7ecc315057e8cd4255e. Can you check how it works for you?

**Comment by kurokirasama** [comment]
already done, i've no complains now :)

**Comment by fornwall** [comment]
@kurokirasama Nice! I'm closing this then, as I think we can manage without libfdk-acc.

**Comment by arbitrary-dev** [comment]
Had the same issue with:
```
ldconfig: Permission denied
```

Overcame it by manually copying built `lib` & `include` folders into `/data/data/com.termux/files/usr/`.

**Comment by linyf2008** [comment]
Same issue to ask if it's possible to add libfdk_aac to ffmpeg as it's the only encoder which support HE-AAC and HE-AACv2 encoding.
