### ISSUE TITLE
octave issue

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-packages#1689]
Hello,

i don't know if this question goes here, but if not, please tell me where should i do it.

i successfully installed octave on termux, as well as several octave packages. However, i can't install two:

* miscellaneous: i got the error:
```
configure: error: Unable to find ncurses library headers. 
sh: 0: Can't open ./config.status

pkg: error running the configure script for miscellaneous.
error: called from
configure_make at line 86 column 9
install at line 192 column 7
pkg at ine 394 column 9
```
I have have ncurses library installed

*parallel: i got the error:
```
configure: WARNING: TLS disabled since gnutls/gnutls.h not found or not compilable
configure: error: required system functions not found
sh: 0: Can't open ./config.status

pkg: error running the configure script for parallel.
error: called from
configure_make at line 86 column 9
install at line 192 column 7
pkg at ine 394 column 9
```
and i have gnutls library instaled...

**Comment by Grimler91** [comment]
Technically this question belong better at https://github.com/its-pointless/gcc-termux as you must have installed the octave from his repo, but it doesn't matter.

Try installing the *header* files for ncurses and gnutls, available from ncurses-dev and libgnutls-dev. If that doesn't work then it's most likely one of the [differences between Linux and termux](https://wiki.termux.com/wiki/Differences_from_Linux) causing the errors.

**Comment by kurokirasama** [comment]
i ran 
`pkg install ncurses-dev libgnutls-dev`
but nothing get installed and when trying to install octave packages i got the same error.
I have added the repositories that are on termux wiki page...

**Comment by kurokirasama** [comment]
Hello, I could install the packages, now the only error I got is:
`sh: 0: Can't open ./config.status`

**Comment by Quasic** [comment]
I was going to second trying the other repo, but then I saw you did in its-pointless/gcc_termux#14

**Comment by kurokirasama** [comment]
yep, already fixed. Thanks!

**Comment by Grimler91** [comment]
@kurokirasama I guess you can close this issue (and possibly share the solution you found) then.

**Comment by kurokirasama** [comment]
it was an octave issue, the dev fixed it in [here](https://github.com/its-pointless/gcc_termux/issues/16)
