### ISSUE TITLE
What's build Gradle Android projects?

### ISSUE THREAD

**Issue by TrashboxBobylev** [termux/termux-packages#1692]
I'm request gradle exeutable to terminal repository.

I'm working on the Shattered PD fork, which is collected with Gradle.

Okay, there the assembler's work is simply done (we move classes from the graphics library to the game part), however with large projects the heap of actions that Gradle performs is manually performed almost impossible or incredibly long.

How soon will Ant, at least Ant, or another Java project collector appear in Termux?

**Comment by its-pointless** [comment]
It is possible to have java. The package in disabled builds. Its very large and slow though and is prone to using 100% cpu forcing android to crash often on arm and slower phones.

**Comment by sdrausty** [comment]
@TrashboxBobylev java is available through
https://sdrausty.github.io/TermuxArch/
https://duckduckgo.com/?q=arch+linux+install+java+pacman&atb=v90-2__&t=cros&ia=q
Then run # pacman -Syy; # pacman -Su; # pacman -S jdk8-openjdk

**Comment by fornwall** [comment]
Closing this issue in favour of tracking https://github.com/termux/termux-packages/issues/45 for openjdk support (which will bring tools such as ant and gradle).

**Comment by sdrausty** [comment]
Gradle works on the fly for x86 and x86_64 architectures using Termux Arch in Termux PRoot.  Arm architures must wait, as it appears the gradle is x86 architecture specific.

**Comment by hyperpallium** [comment]
> @sdrausty Gradle works on the fly for x86 and x86_64 architectures using Termux Arch in Termux PRoot.

PRoot apparently includes the extraordinary feature of emulating other architectures:

> PRoot internally utilizes the qemu user-mode emulator to allow programs to be run inside the PRoot even when they are compiled for an architecture other than the host system's https://wiki.archlinux.org/index.php/PRoot

Maybe there's more to it, but shouldn't switching on this emulation make it possible to run Gradle on arm architectures?

**Comment by xeffyr** [comment]
> PRoot apparently includes the extraordinary feature of emulating other architectures:

> Maybe there's more to it, but shouldn't switching on this emulation make it possible to run Gradle on arm architectures?

QEMU is not embedded into proot. It uses external binary which is specified with `--qemu` option:
```
  -q *command*, --qemu=*command*
	Execute guest programs through QEMU as specified by *command*.

	Each time a guest program is going to be executed, PRoot inserts
	the QEMU user-mode command in front of the initial request.
	That way, guest programs actually run on a virtual guest CPU
	emulated by QEMU user-mode.  The native execution of host programs
	is still effective and the whole host rootfs is bound to
	/host-rootfs in the guest environment.
```
