### ISSUE TITLE
How to use custom PHP extensions?

### ISSUE THREAD

**Issue by lukeeey** [termux/termux-packages#1693]
I am in need of PHP build with the v8js extension and pthreads, but they are not included in the termux php package

**Comment by Hero9909** [comment]
Same as the php runkit extensions 

All of them are installable throught pear.

Ive tried to build an extebsion manual but fails after editing some vars of ./configure of autoconf with`cannot guess build type`

Is there any way you can mention?

**Comment by xtkoba** [comment]
This issue is marked as obsolete. Please open a new issue if you encounter a similar problem. Thanks.
