### ISSUE TITLE
termux-wifi-scaninfo gives no output 

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#1694]
termux-wifi-scaninfo gives no output even though wifi AP are in range.

**Comment by Auxilus** [comment]
Maybe increasing scan time would help?

**Comment by remo7777** [comment]
![screenshot_20171021-192714](https://user-images.githubusercontent.com/28594846/31852488-13e0a3d2-b696-11e7-9a12-f624ba2306fa.jpeg)
**hmmm not showing my wifi**

**Comment by sp4rkie** [comment]
I don't think it's a timeout issue. Something is missing to trigger a rescan at all.
The AP list appears to be frozen unless you toggle the Wi-Fi button or launch the `WiFiAnalyzer` app in between

**Comment by Auxilus** [comment]
I don't remember that `termux-wifi-scaninfo` ever worked on my device

**Comment by xeffyr** [comment]
@Auxilus same problem with termux-wifi-scaninfo. But it can be solved by enabling geolocation.

**Comment by Auxilus** [comment]
Should we implement enabling geolocation in api source?

**Comment by xeffyr** [comment]
Not sure if we can change Android settings from regular application without root. But it possible to show notice that geolocation should be enabled.

**Comment by Auxilus** [comment]
Im on it

**Comment by Auxilus** [comment]
take a look at https://github.com/termux/termux-api/pull/114

I guess this should fix the issue

**Comment by fornwall** [comment]
In version 0.22 of the `Termux:API` app termux-wifi-scaninfo now shows `Location needs to be enabled on the device` if called when Location is disabled on the device.

Location is needed due to https://issuetracker.google.com/issues/37060483, `"WifiManager#getScanResults() returns an empty array list if GPS is turned off`.
