### ISSUE TITLE
termux-open fails to open pdf files 

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#1696]
Issue appears when i use termux-open for pdfs stored in termux storage

**Comment by Grimler91** [comment]
It's working fine for me, do you have a functioning pdf reader on your device?

**Comment by Auxilus** [comment]
yes, google pdg reader

**Comment by chends888** [comment]
For some reason, termux-open fails to open pdf files on Google pdf reader, but if you try in another one like Adobe Reader it works as expected.

**Comment by hugosoftdev** [comment]
Just completing what @chends888  said, you can disable the google pdf reader and download another one that it will work, or just set this other as the default. If you dont have a reader nothing will happen.
