### ISSUE TITLE
Error import opencv 

### ISSUE THREAD

**Issue by autumnwater935** [termux/termux-packages#16979]
hello
I have installed python 3.11.4 & opencv-python 4.7.0-5
but when importing opencv error
`>>> import cv2
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
F0000 00:00:1686908925.146090  22510 common.cc:86
This program was compiled against version 3.0.0 of the Protocal Buffer runtime library, which is not compatible with the installted version (4.22.4). Contact the program author for an update. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "external/protobuf/src/google/protobuf/any.pb.cc".)
*** Check failure stack trace: ***
Aborted
`
But before I installed the old version python 3.11.3 & opencv-python 4.7.0-5, there was no error
Please help me

**Comment by 2096779623** [comment]
```bash
Setting up opencv (4.7.0-5) ...
Setting up opencv-python (4.7.0-5) ...
~ $ python
Python 3.11.4 (main, Jun  9 2023, 22:32:13) [Clang 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>>
```
I can't reproduce it on my device, please provide `termux-info` output.

## termux-info
```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1+2c6674f
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~L12z_fXciITR5obZMtOmrQ==/com.termux-cYiMcDCnjjsoz9UpB_x5Vw==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=21467
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c185,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c185,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10185
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.ustc.edu.cn/termux/apt/termux-root root stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.ustc.edu.cn/termux/apt/termux-x11 x11 main
Updatable packages:
krb5/stable 1.21 aarch64 [upgradable from: 1.20.1]
termux-tools version:
1.38.3
Android version:
13
Kernel build information:
Linux localhost 4.14.299-Perf #4 SMP PREEMPT Sun Dec 4 15:42:55 CST 2022 aarch64 Android
Device manufacturer:
LGE
Device model:
LM-G820N
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.styling versionCode:29
```

**Comment by autumnwater935** [comment]
@2096779623 
Thank you for your feedback
here is my termux-info
`
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=15049
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
deb http://deb.debian.org/debian buster main contrib non-free
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.91-19978747-QB54389539 #1 SMP PREEMPT Tue Jul 26 13:07:58 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G930L
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

`

**Comment by autumnwater935** [comment]
Can anyone help me to build a package python3.11.3 or fix the error above

**Comment by xtkoba** [comment]
Not confirmed but probably the same as https://github.com/termux/termux-packages/issues/14961, some clash of protobuf shared lib against system one under `/system/lib(64)`.

My guess is python is not relevant here but instead ffmpeg is, because some library in ffmpeg now links against `libandroid.so` (097206d50d34ab7fc0eb4c0ff20ae80ee73fd901).

Presumably we should use static protobuf lib everywhere.

**Comment by xtkoba** [comment]
@autumnwater935 Please test the artifact of PR #17081 in https://github.com/termux/termux-packages/actions/runs/5353603976. I will merge the PR if it works for you. Thanks.

**Comment by autumnwater935** [comment]
@xtkoba Tks for your help .
I tested and was able to import cv2 on android 8, android9.
Can you merge it into the main repo so I can directly install it via pkg command ?
