### ISSUE TITLE
The fish shell does not work correctly

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#17]
It prints strange output on startup mostly.

**Comment by fornwall** [comment]
It prints 

    fish:fish:fish:fish:fish:fish:fish:fish:fish:fish:...

endlessly. By doing `mkdir -p $HOME/.config/fish` it reaches a running state (still after printing `fish:fish:..` a lot of times.

**Comment by fornwall** [comment]
Fish uses wide character functions (wcsdup, wcstol, ..), could be due to Android lacking support of those.

**Comment by Yajo** [comment]
Is there any progress on this? I'd absolutely love to have fish in my tablet!

**Comment by fornwall** [comment]
@Yajo Unfortunately not at the moment, will hopefully be able to look at this soon! So `bash` and `zsh` are the current options :).

**Comment by coderstephen** [comment]
I get a similar output on my device, though I might have too little RAM for that result of finally working maybe? On my device it prints `fish:` repeatedly until it segfaults, presumably from using all of the RAM.

**Comment by coderstephen** [comment]
I finally got some sensible output out of `fish` with the following command:

```
$ fish -c ls > fish.log
fish: Wide character -1093271008 has no narrow representation
fish: Wide character -1227358080 has no narrow representation
fish: Wide character -1225900412 has no narrow representation
fish: Wide character -1093271044 has no narrow representation
fish: Wide character -1226671224 has no narrow representation
fish: Wide character -1093271044 has no narrow representation
fish: Wide character -1226671224 has no narrow representation
fish: Wide character -1093271000 has no narrow representation
fish: Wide character -1202449640 has no narrow representation
fish: Wide character -1202444640 has no narrow representation
test: Expected a combining operator like '-a' at index 1TT
```

I'm no expert, but I'm guessing `-1093271008` isn't a valid character code and shouldn't be negative. Perhaps this confirms the issue is related to lack of wide character support? If so, how glum does the future look for Fish on Termux? Fish is pretty integral to my terminal workflow...

**Comment by pl3w5y** [comment]
There are a few bugs in Fish itself with similar output

Eg, https://github.com/fish-shell/fish-shell/issues/1894

Given ridiculousfish's comment at the bottom, is there anything that we can try to make progress here?

**Comment by Yajo** [comment]
That one is supposed to be fixed.

**Comment by Yajo** [comment]
Maybe we could ping some Fish developer to see if they can provide more insight...

**Comment by fornwall** [comment]
Hi, I hope this have been fixed now! Update to latest versions of packages with

    apt update && apt upgrade

which should pull in recent updates to both the `libandroid-support` and the `fish` package, which leaves me with a more friendly startup message:

    Welcome to fish, the friendly interactive shell
    Type help for instructions on how to use fish
    u0_a260@localhost ~> 

Let me know if this does not work for you, or if you encounter any remaining issue with fish!

**Comment by Yajo** [comment]
Fixed, thanks!

**Comment by Yajo** [comment]
The only issue now is that typing `help` does not open a browser because it says it lacks a `$BROWSER` env variable, but maybe that's not Termux problem...

**Comment by Neo-Oli** [comment]
@Yajo You need to have a browser installed for that. `apt install w3m` or `apt install lynx`. 
It does however 404 for me when I try to open help.

**Comment by fornwall** [comment]
The problem with `help` seems to be that it tries to open

    http://fishshell.com/docs/unknown/index.htm

instead of

    http://fishshell.com/docs/current/index.html

This could be due to the way the fish shell is built from git master instead of a tagged release - I'll try to fix this!

**Comment by fornwall** [comment]
The `help` command has been fixed now to use a correct url (though you need a browser as @Neo-Oli said).

**Comment by coderstephen** [comment]
You can also use `termux-open-url`. :wink:

**Comment by fornwall** [comment]
@coderstephen Perhaps that is the best solution to default to (and let a user override it with BROWSER environment variable if desirrd)!
