### ISSUE TITLE
[feature request] virgl's Venus support

### ISSUE THREAD

**Issue by dontknowhy** [termux/termux-packages#17011]
I noticed that virglrenderer has supported Venus protocol and mesa has supported it too.
So I think It's time to add it to virglrenderer-android package.(Termux has already supported Vulkan anyway)

**Comment by twaik** [comment]
Most of Android devices do not meet Venus dependencies.

**Comment by DocMAX** [comment]
Still the same situation?

**Comment by dontknowhy** [comment]
> Still the same situation?

Too busy to test it...
And if you are brave enough to manually patch `virgl_test_server`,you can test it.
I'm sorry but I don't want to focus on this thing.
