### ISSUE TITLE
[Bug]: qt5-qtwebengine: Please revise dependency (on system libs)

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#17012]
### Problem description

@licy183

`qt5-qtwebengine` package (version `5.15.12-3`) does not link against `libxml2` or `libxslt`. Not confirmed but the build log should contain:

```
Checking for compatible libxml2 and libxslt... no
```

Please revise `TERMUX_PKG_DEPENDS` so that it does not contain *unnecessary* packages.

### What steps will reproduce the bug?

Check `DT_NEEDED` entries of shared objects in `qt5-qtwebengine` package for `libxml2.so`.

### What is the expected behavior?

`TERMUX_PKG_DEPENDS` should not contain `libxml2` if `libxml2.so` is unused.

### System information

Irrelevant as this is a packaging issue.

**Comment by xtkoba** [comment]
As for dependency on system libs, this package is blocking bump of `libre2` to `2023.06.02`. It does not build with this new version of `libre2`. <a href="https://github.com/termux/termux-packages/actions/runs/5296561841">When I tried adding some workaround, then it built but the system re2 became unused</a>:

```
Checking for re2... no
```

Not a bug currently but this is nice to be resolved as well.

**Comment by licy183** [comment]
I'll try to bump this package to 5.15.14 and solve this issue.

The qt building system in Termux is strange and it does not follow the standard cross-compile steps the qt team provides. It doesn't enable pkg-config but this is needed to configure qtwebengine. It seems that my tricks on forcing pkg-config enabled don't always work properly...
