### ISSUE TITLE
Did you try this?

### ISSUE THREAD

**Issue by TheKam** [termux/termux-packages#1702]
https://pastebin.com/FL6e9iKt

Go there nd just copy paste tht in termux to install metasploit msfvenom works it least but can't make bind file or apk any solution for that? To nake a bind apk with termux ....?

**Comment by Auxilus** [comment]
@TheKam I'd advise you to go with the official metasploit-framework installation script given at [wiki](wiki.termux.com/wiki/Metasploit_Framework) rather than using third-party scripts which are likely to have bugs

**Comment by Auxilus** [comment]
BTW yeah we've got metasploit for almost 4 months now

**Comment by TheKam** [comment]
@Auxilus yeah thanks does that wiki metasploit-framework can bind payload into apk in termux?

**Comment by Auxilus** [comment]
No

**Comment by TheKam** [comment]
Let me know if you find any solution for that thx again @Auxilus
