### ISSUE TITLE
[Feature]: Deep Learning for Java on Termux

### ISSUE THREAD

**Issue by LobsterMan123** [termux/termux-packages#17035]
### Feature description

Would you please tell me if you could make deep learning for Java available on Termux?  Since both Java and Maven are available through the official package manager, this would be awesome.  There's a library called DL4J that supposedly can run on arm processors but it isn't working on my device despite being walked through many different approaches by the folks at DL4J (I've thrown in the towel for now).  From discussions with them, it seems the problem has something to do with getting the native dependencies to work for me (apparently DL4J's heavy computational lifting is done by C).

Thanks and my apologies for mistakenly submitting this question originally through a pull request instead of a feature request.

### Additional information

I do not know if my requested feature is available on other app terminal emulators (likely not since any competing terminal emulators also run on mobile device processors which is where the challenge is for the requested feature).

**Comment by xtkoba** [comment]
A package request must be submitted using the specific template.
