### ISSUE TITLE
ncurses-dev and libgnutls-dev packages 

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-packages#1704]
Hello,

is it possible to have this packages on temux?

Regards,

**Comment by Auxilus** [comment]
@kurokirasama they are already added!
You can install them by 
```
pkg install ncurses-dev libgnutls-dev
```

**Comment by kurokirasama** [comment]
Odd.
They do not appear if i run `pkg list-installed`. And running `pkg install ncurses-dev libgnutls-dev` doesn't install anything. Here is the output:
[screenshoot1](https://yadi.sk/i/cg-Zah-w3P2GfB)
[screenshoot2](https://yadi.sk/i/R4Thd6rd3P2GjH)

**Comment by Auxilus** [comment]
There is an error with one of the repository you added to your sources.list

Remove all other repositories except the official one and try again

**Comment by kurokirasama** [comment]
ok, how do i remove them?

**Comment by Auxilus** [comment]
You gotta remove all the lines in `$PREFIX/etc/apt/sources.list`  using vim or nano except the one which says `deb [arch=all,aarch64] http://termux.net stable main`

**Comment by kurokirasama** [comment]
Thanks!, that worked.
