### ISSUE TITLE
QEMU: Could not init `pa` driver

### ISSUE THREAD

**Issue by zavocc** [termux/termux-packages#17040]
### Problem description

I'm trying to run a Windows XP-based VM (Server 2003) and I'm enabling audio with pulseaudio with `-audiodev pa,id=snd0 -device AC97,audiodev snd0` but it yields an error:
```console
❯ ls
server.qcow2  server.sh  win.iso
❯ sh server.sh
audio: Could not init `pa' audio driver
❯ cat server.sh
#!/bin/bash
ISO="win.iso"
DISK="server.qcow2"

qemu-system-x86_64 \
 -m 1024 -cpu max -accel tcg,tb-size=512,thread=multi \
 -drive file=$ISO,media=cdrom \
 -drive file=$DISK,if=ide,cache=unsafe \
 -vnc :1 \
 -device virtio-balloon \
 -netdev user,id=vmnic0 \
 -device rtl8139,netdev=vmnic0 \
 -usb -device usb-tablet \
 -audiodev pa,id=audio0 \
 -device AC97,audiodev=audio0 \
 -monitor stdio
❯ sh server.sh
audio: Could not init `pa' audio driver

╭─ ~/vms ──────────────────────── 1 ✘  06:18:43 PM ─╮
╰─                                                      ─╯
```

I also tried adding property`server=localhost` in `-audiodev pa` and started pulseaudio manually, and this time it yields a different error:
```console
❯ sh server.sh
pulseaudio: Wrong context state
pulseaudio: Reason: Connection refused
pulseaudio: Failed to initialize PA contextaudio: Could not init `pa' audio driver

╭─ ~/vms ──────────────────────── 1 ✘  06:20:21 PM ─╮
╰─                                                      ─╯
```

I tried this on a Linux distribution installation on my PC before which pulseaudio started and QEMU uses that audio driver without problems with `-audiodev pa,I'd=snd0` but I assume it should start and should utilize pulseaudio audiodev driver.

### What steps will reproduce the bug?

There are two different ways to exhibit this behavior which produces errors when using pulseaudio audiodev driver

First option without explicitly specifying `server` property in audiodev
1. Install qemu either headless or GUI variant which both have pulseaudio support as per build.sh
`pkg in qemu-system-x86-64` or `pkg in qemu-system-x86-64-headless`
2. Start QEMU with `pa` audiodev 
`qemu-system-x86_64 -audiodev pa,id=snd0 -device AC97,audiodev=snd0`

Should result in error: 
```audio: Could not init 'pa' audio driver```

---

And with explicitly specifying `server=localhost` property in audiodev with manually invoked pulseaudio command (`pulseaudio --start --exit-idle-time=-1`)
1. Start pulseaudio `pulseaudio --start --exit-idle-time=-1`
2. Start QEMU with `pa` audiodev with `server=localhost` property with: `qemu-system-x86_64 -audiodev pa,id=snd0,server=localhost -device AC97,audiodev=snd0`

Should also result in:
```
pulseaudio: Wrong context state
pulseaudio: Reason: Connection refused
pulseaudio: Failed to initialize PA contextaudio: Could not init `pa' audio driver
```

### What is the expected behavior?

Both methods should start, at least if pulseaudio can allow qemu to utilize audio without additional setup 

### System information

termux-info:

```
❯ termux-info
Termux Variables:                                          TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=25348
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:                                      1.38.3
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf+ #2 SMP PREEMPT Sat Sep 3 23:17:03 CST 2022 aarch64 Android
Device manufacturer:
OPPO                                                       Device model:
CPH1933
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.styling versionCode:30
```

### Additional information
Additional findings about these errors that might help finding the root cause of this problem 
https://www.reddit.com/r/linux_gaming/comments/5tidzc/a_solution_for_pulseaudio_pa_context_connect/
https://stackoverflow.com/questions/59988019/emulator-pulseaudio-access-denied
https://bbs.archlinux.org/viewtopic.php?id=201393

Thanks in advance!

**Comment by zavocc** [comment]
QEMU PulseAudio seems to work and initializes only if the pulseaudio server was explicitly started and enabled auth-anonymous in either unix or tcp mode

```console
~ $ pulseaudio --start --exit-idle-time=-1
~ $ pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
~ $ qemu-system-x86_64 -audiodev pa,id=snd0,server=localhost -device AC97,audiodev=snd0 -vnc :1
```
It throws a lot of invalid argument but it continues to work

Or using SDL audiodev `-audiodev sdl` to make it easier which also utilizes pulseaudio, GUI builds of qemu already uses this by default, but headless ones doesn't which pa audiodev driver is used.

---

However this one doesn't work as expected without explicitly adding`server` property:
```console
~ $ pulseaudio --start --exit-idle-time=-1
~ $ pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
~ $ env PULSE_SERVER=localhost qemu-system-x86_64 -audiodev pa,id=snd0 -device AC97,audiodev=snd0 -vnc :1
audio: Could not init `pa' audio driver
```

**Comment by zavocc** [comment]
Setting `XDG_RUNTIME_DIR` environment variable fixes it and QEMU pulseaudio driver works again properly as it should 

```console
~ $ export XDG_RUNTIME_DIR=$TMPDIR
~ $ pulseaudio --start --exit-idle-time=-1
~ $ qemu-system-x86_64 -audiodev pa,id=snd0 -device AC97,audiodev=snd0 -vnc :1
```
Without needing to run pacmd commands and manually explicitly setting `server=` audiodev property

**Comment by atasoglou** [comment]
@zavocc What is `$TMPDIR` in your case? Or what is it supposed to be? Thanks

**Comment by zavocc** [comment]
That's the Termux's temporary directory located at `$PREFIX/tmp`.

XDG_RUNTIME_DIR serves similar purpose to temporary directory but it is mostly managed for the specific user account, since Termux is a single user environment, pretty much you can set it to somewhere in appropriate non-persistent runtime directories where runtime files.

QEMU's case, since PulseAudio audiodev backend might need this variable for this to work correctly, the XDG variable is set for PulseAudio put those runtime files somewhere and QEMU to communicate with PulseAudio.
