### ISSUE TITLE
Updated proot version is not working in my phone & want old  

### ISSUE THREAD

**Issue by Hax4us** [termux/termux-packages#1705]
Architecture :- aarch64
Android :- 5.1.1
But one thing I want to say that....older version of proot was working properly .....so plz...@fornwall if u can give me old version so...plz give..

**Comment by Grimler91** [comment]
Please write a proper bug report and show us the actual error.

**Comment by Hax4us** [comment]
Can you guide me ...means..how can I know proper bug report....actually when I m trying to extract a file (with hard links ) with this command :- 
proot --link2symlink tar -xf file.tar.xz
Then error was that :-
Proot info : void 1: terminated with signal 7

**Comment by Hax4us** [comment]
Srry
It is not void ..it is vpid

**Comment by Grimler91** [comment]
Just copy the command you wrote and _all_ the output it generated here.

**Comment by Hax4us** [comment]
Bro I did already.. See above

**Comment by Hax4us** [comment]
Closed
