### ISSUE TITLE
Please add jdk 20 

### ISSUE THREAD

**Issue by AlirezaParsi** [termux/termux-packages#17063]
Before Minecraft 1.20.1 i used jdk17 but now it need above 17 and jdk 20 is perfect option and also i cant use oracle builds because it's for linux and i can't run it because libs and also i can't build jdk for termux.
Thanks.

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux-packages/pull/15108 for openjdk-19. Package requests need to follow termux-packages repo issue template.
