### ISSUE TITLE
Missing info page for gcal(1) command

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#1707]
The GNU Calendar program `gcal(1)` is the most sophisticated calendar software embodying all that is currently known about calendars on our planet. So, omitting the manual which describes all its intricate features is equivalent to downgrading it to the level of a mere Unix `cal(1)` command. Yes, I know about the brief summary of options available via `gcal -hh` invocation, but that is not enough for serious usage.

E.g. I need to display the calendar of some year B.C. and I still can't figure out how to do this :)

**Comment by Quasic** [comment]
Did you have the texinfo package installed when you installed gcal?

Regardless, you can download it from https://www.gnu.org/software/gcal/manual/

**Comment by tigran123** [comment]
I don't remember if I had texinfo package installed --- probably yes, as the firs thing after installing termux I always install hundreds of packages which I consider to be absolutely essential even for a minimalistic GNU system.

Regardless, if gcal package requires texinfo then it should be mentioned in the package as a dependency and this would cause texinfo to be automatically installed, if needed.

**Comment by sdrausty** [comment]
@tigran123 You might want to update the title to, "Missing info and man pages for gcal(1) command".

```
$ info gcal
info: No menu item 'gcal' in node '(dir)Top'
$ man gcal
man: No entry for gcal in the manual.
$ dpkg -L gcal
```
![screenshot_20171107-164209](https://user-images.githubusercontent.com/27742457/32519491-f4892b2e-c3da-11e7-9960-a03adae90018.png)

**Comment by Quasic** [comment]
It's not disabled in the package, that I can see. The info file is in gcal-4.1/doc/en/texinfo.tex, so perhaps ./configure's --infodir=... etc. are needed?

**Comment by Quasic** [comment]
Oh, by default they aren't put in termux packages. I could open a pull request, and we'll see what happens...

**Comment by fornwall** [comment]
Thanks to @Quasic there is now an updated `4.1-2` version of the gcal package available which includes the gcal info page!

**Comment by tigran123** [comment]
Thank you very much, yes, it is there!
