### ISSUE TITLE
Nmap Failed to open deice Wlan0

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-packages#1708]
I installed Proot Debian of this package [Debian on Termux](https://github.com/sp4rkie/debian-on-termux)
When running Nmap, from root, i get error.
![2](https://user-images.githubusercontent.com/29791715/31941959-bb7feb44-b8d4-11e7-86e1-a00faba1c5f2.png)
Why Debian → Root does not see a wifi device?
From a simple user, the nmap works, but some programs require ROOT.
How can fix this?

**Comment by sp4rkie** [comment]
for this to work you must  root your device. You then are allowed to drop a root shell with all the privileges you need: https://github.com/termux/termux-app/issues/164

**Comment by Deathlive** [comment]
@sp4rkie I have Root, but how to do it ?(how to drop a root shell)
What would I be able to start nmap from the root user.
If you talk about the https://github.com/st42/termux-sudo, it does not work in Termux Debian.

**Comment by sp4rkie** [comment]
sorry, I don't have a rooted device. I can't tell you much about it. What did you exactly do?
Have you tried to call `nmap` within `termux` (not debian) after issuing `tsu`? What was the result? 
Maybe  https://github.com/termux/termux-packages/issues/1669 helps.

**Comment by xeffyr** [comment]
@Deathlive you cannot call **su** under proot. If you want to run programs with root in debian, you need to setup a normal chroot environment (root needed) in EXT4 fs image (because on /data partition suid bit is disabled by Android's fstab).

**Comment by Deathlive** [comment]
@sp4rkie I used  `tsu` and everything turned out  after `enter_deb -0 -p` and everything turned out.
Probably `-0` does not give a full root of access as `tsu`.

**Comment by sp4rkie** [comment]
A possible solution to the question `how to run debian with true root permissions` is to first invoke `tsu` and after this call `proot` with proper arguments to enter the debian environment. 

I hope I understand @Deathlive correctly: https://github.com/sp4rkie/debian-on-termux/issues/2#issuecomment-339554603

**Comment by Deathlive** [comment]
@sp4rkie One more solution to the question, I tried https://github.com/st42/termux-sudo, like you said, changed the  `ROOT_HOME=$PRE/home/.suroot` on `ROOT_HOME=$PRE/home/` and the sudo launched debian.
If to run with `ROOT_HOME=$PRE/home/.suroot` there will be an error →
```
proot warning:can`t sznitize binding "/data/data/com.termux/files/home/.suroot/debian": No such file or directory
fatal error: see `proot --help`.
```

**Comment by sp4rkie** [comment]
you could try `sshfs` within your rooted debian. If that works you could post it there: https://github.com/termux/termux-packages/issues/276 :-)

**Comment by laoxiaodiao** [comment]
first you can make a file in HOME
"vim sud"
then insert the follow code 


#!/bin/bashexport PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:$PATH
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
echo "now,you can run as root" 


save and  quit 
now
type "su" at HOME
then type"source sud"
if it show "now,you can run as root"
you can startkali and then startnmap

my English is very poor, sorry
