### ISSUE TITLE
[Bug]: Failed to build Wheels for Pillow

### ISSUE THREAD

**Issue by Xediox-zex** [termux/termux-packages#17098]
### Problem description

~ $ pip install Pillow
Collecting Pillow
  Using cached Pillow-9.5.0.tar.gz (50.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: Pillow
  Building wheel for Pillow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for Pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [204 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv8l-cpython-311
      creating build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/FitsImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/Image.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/QoiImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/__init__.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/__main__.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/_binary.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/_deprecate.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/_util.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/_version.py -> build/lib.linux-armv8l-cpython-311/PIL
      copying src/PIL/features.py -> build/lib.linux-armv8l-cpython-311/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing requirements to src/Pillow.egg-info/requires.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files found matching 'renovate.json'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext

      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "<string>", line 993, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 809, in build_extensions
      RequiredDependencyException: jpeg

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-u2etj614/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 1010, in <module>
      RequiredDependencyException:

      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
Failed to build Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects

### What steps will reproduce the bug?

pip install Pillow

### What is the expected behavior?

  ERROR: Failed building wheel for Pillow
Failed to build Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=32724
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf #1 SMP PREEMPT Wed Feb 1 11:15:00 CST 2023 armv8l Android
Device manufacturer:
vivo
Device model:
vivo 1801
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by 2096779623** [comment]
`pkg i python-pillow`
