### ISSUE TITLE
Package request: texlive

### ISSUE THREAD

**Issue by RerumNovarum** [termux/termux-packages#171]
I believe some latex support is a must-have for termux
https://archlinuxarm.org/packages/any/texlive-core
https://archlinuxarm.org/packages/arm/texlive-bin

**Comment by fornwall** [comment]
Thanks, some kind of latex support would indeed be great for editing papers and thesis when in a need. I added this to the [package suggestion page](https://termux.com/package-suggestions.html).

**Comment by Neo-Oli** [comment]
Hi, I am re-opening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by alexj136** [comment]
Also agree that LaTeX support is a must-have.

**Comment by Holzhaus** [comment]
TexLive would be great. Probably we can even get [Pandoc](http://pandoc.org/) support?

**Comment by mklein994** [comment]
@Holzhaus maybe open that as a separate issue.

**Comment by pf4d** [comment]
First, great job with Termux.  I agree TexLive would be an excellent addition.

**Comment by bfortz** [comment]
You can try this: https://www.euro-online.org/termux-texlive/ 
Works fine for me, I'd be happy to get feedback. If I find time I might try to package it properly, but it seems far from trivial.

**Comment by fornwall** [comment]
The texlive package is now available for installation:

    packages install texlive

Thanks to @rnauber, @Grimler91 and all the others whose hard work made this possible!

**Comment by tukusejssirs** [comment]
Probably, I should open a new issue, however, this is connected with texlive. I cannot run `lualatex` because it cannot find *any* fonts. Could you add texlive-full? Or at least `texlive-fonts-extra`?
