### ISSUE TITLE
[Bug]: `CMAKE_SYSTEM_VERSION` value is kernel version, instead of Android API level.

### ISSUE THREAD

**Issue by funsafe-ptr** [termux/termux-packages#17104]
### Problem description

Since Termux default `CMAKE_SYSTEM_NAME` is `Android`, it's better to set `CMAKE_SYSTEM_VERSION` to 24 (Termux's current Android API level) instead of using `uname -r`, no? This can be used to check the availability of system functions and link to compatibility libraries like the `libandroid-spawn` package. I don't know the side effects, though.

https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-android-with-the-ndk
https://cmake.org/cmake/help/latest/variable/CMAKE_ANDROID_API.html

### What steps will reproduce the bug?

```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.0)

project(test)

message("CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
message("CMAKE_SYSTEM_VERSION: ${CMAKE_SYSTEM_VERSION}")
```

print
```ignore
CMAKE_SYSTEM_NAME: Android
CMAKE_SYSTEM_VERSION: 4.9.77+
```

### What is the expected behavior?

```ignore
CMAKE_SYSTEM_NAME: Android
CMAKE_SYSTEM_VERSION: 24
```

### System information

termux-info:

```ignore
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21515
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
clang/stable 16.0.6 aarch64 [upgradable from: 16.0.5]
command-not-found/stable 2.2.0-5 aarch64 [upgradable from: 2.2.0-3]
emscripten-binaryen/stable 3.1.42 aarch64 [upgradable from: 3.1.41-1]
emscripten-llvm/stable 3.1.42 aarch64 [upgradable from: 3.1.41-1]
emscripten/stable 3.1.42 all [upgradable from: 3.1.41-1]
gst-libav/stable 1.22.4 aarch64 [upgradable from: 1.22.3]
gst-plugins-bad/stable 1.22.4 aarch64 [upgradable from: 1.22.3]
gst-plugins-base/stable 1.22.4 aarch64 [upgradable from: 1.22.3]
gst-plugins-good/stable 1.22.4 aarch64 [upgradable from: 1.22.3]
gst-plugins-ugly/stable 1.22.4 aarch64 [upgradable from: 1.22.3]
gstreamer/stable 1.22.4 aarch64 [upgradable from: 1.22.3]
libcompiler-rt/stable 16.0.6 aarch64 [upgradable from: 16.0.5]
libflac/stable 1.4.3 aarch64 [upgradable from: 1.4.2]
libllvm/stable 16.0.6 aarch64 [upgradable from: 16.0.5]
lld/stable 16.0.6 aarch64 [upgradable from: 16.0.5]
lldb/stable 16.0.6 aarch64 [upgradable from: 16.0.5]
llvm/stable 16.0.6 aarch64 [upgradable from: 16.0.5]
vulkan-extension-layer/stable 1.3.255 aarch64 [upgradable from: 1.3.253]
vulkan-headers/stable 1.3.255 all [upgradable from: 1.3.253]
vulkan-loader-generic/stable 1.3.255 aarch64 [upgradable from: 1.3.253]
vulkan-tools/stable 1.3.255 aarch64 [upgradable from: 1.3.251]
termux-tools version:
1.38.3
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.77+ #2 SMP PREEMPT Fri Mar 19 20:17:40 CST 2021 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH1909
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.styling versionCode:30
com.termux.widget versionCode:13
com.termux.window versionCode:15
```

**Comment by xtkoba** [comment]
On-device building is different from cross building. There should be no problem as is.

It has long been discussed what API level should be used *by default* for on-device building. See #2469 for example. There may be an objection to set `CMAKE_SYSTEM_VERSION` to 24. Honestly I don't want to touch this anymore.

**Comment by xtkoba** [comment]
The use case provided by the author seems to be out of the point. `libandroid-spawn` is always needed when targeting API level 24.

The only official C compiler in our repo that is used for on-device packaging, `clang`, specifies the target API level. Which system functions are available can be checked by trying to compile test programs. That should be enough.

**Comment by xtkoba** [comment]
(Some legacy build system like Autotools occasionally misdetects the available system functions, when a test program declares its own prototype and links against system libs. But that is another story. I seldom hears that modern build systems like CMake or Meson do that.)

**Comment by funsafe-ptr** [comment]
I'm sorry, but isn't issue #2469 referring to the `__ANDROID_API__` definition, which correctly defined as `24`? The code 
```c++
static_assert(__ANDROID_API__ == 1);
``` 
prints 'static assertion failed due to requirement 24 == 1' which is correct. 
Isn't `CMAKE_SYSTEM_VERSION` only for CMake?
Sorry if I'm being annoying.

**Comment by xtkoba** [comment]
`__ANDROID_API__` should be always respected, whether on-device or cross.

Relying on `CMAKE_SYSTEM_VERSION` is dangerous, assuming it is set to the API level. Inconsistencies can happen very easily. It may be relied on for cross-building using NDK, but may not otherwise.

**Comment by truboxl** [comment]
No where in #2469 mentions CMAKE_SYSTEM_VERSION

The "CMAKE_SYSTEM_VERSION follows Android API level" behaviour is defined in https://android.googlesource.com/platform/ndk/+/master/build/cmake/android.toolchain.cmake#177
https://android.googlesource.com/platform/ndk/+/master/build/cmake/adjust_api_level.cmake

but we don't use NDK android.toolchain.cmake.

**Comment by funsafe-ptr** [comment]
I mean it makes CMake code for cross compile and buiding from Termux is the same, 
I just dont see the use case which `CMAKE_SYSTEM_VERSION` being the kernel version is useful? `CMAKE_SYSTEM_NAME` is Android anyway not Linux i think assuming `CMAKE_SYSTEM_VERSION` represents Android Api level is fine? since it is documented.

It's not a big deal though, I can just use `check_symbol_exists(posix_spawn "spawn.h" HAVE_POSIX_SPAWN)`.

**Comment by xtkoba** [comment]
This is not a bug. Just a nice-to-have enhancement at most. I can't bother to do that.

The biggest problem when doing this is whether we should set the default value of `CMAKE_SYSTEM_VERSION` to `24` or the value of `getprop ro.build.version.sdk`. I cannot determine that on my own, but my feeling is that the latter is more plausible. But it definitely contradicts the current value of `__ANDROID_API__` when using `clang`. So my opinion is `CMAKE_SYSTEM_VERSION` should not ever be relied on.

**Comment by xtkoba** [comment]
Documentation says `CMAKE_SYSTEM_VERSION` represents the target API level when cross-compiling for Android. Nothing is said about other cases for Android. So the current value of this variable has no problem at all. This is what I meant by "not a bug".

You may want to ask upstream (CMake developers) to do this instead. I don't think this is our business.

**Comment by funsafe-ptr** [comment]
Maybe a Termux-specific patch? Because there will be a mismatch with `getprop ro.build.version.sdk`. Anyway, no worries if this is too much to ask :)

```patch
--- /data/data/com.termux/files/usr/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake	Fri Jun 30 01:27:40 2023
+++ Untitled	Fri Jun 30 01:29:27 2023
@@ -47,6 +47,8 @@
       set(CMAKE_HOST_SYSTEM_VERSION "${_CMAKE_HOST_SYSTEM_MAJOR_VERSION}.${_CMAKE_HOST_SYSTEM_MINOR_VERSION}")
       unset(_CMAKE_HOST_SYSTEM_MAJOR_VERSION)
       unset(_CMAKE_HOST_SYSTEM_MINOR_VERSION)
+    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Android")
+      set(CMAKE_HOST_SYSTEM_VERSION 24) # TODO make 24 automatically sync with Termux.
     else()
       execute_process(COMMAND ${CMAKE_UNAME} -r
         OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_VERSION
```

**Comment by funsafe-ptr** [comment]
So, I made a little patch. Do you know how to get the current Termux target Android API?

```patch
--- /data/data/com.termux/files/usr/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake	Fri Jun 30 01:41:37 2023
+++ Untitled	Fri Jun 30 01:41:46 2023
@@ -47,6 +47,15 @@
       set(CMAKE_HOST_SYSTEM_VERSION "${_CMAKE_HOST_SYSTEM_MAJOR_VERSION}.${_CMAKE_HOST_SYSTEM_MINOR_VERSION}")
       unset(_CMAKE_HOST_SYSTEM_MAJOR_VERSION)
       unset(_CMAKE_HOST_SYSTEM_MINOR_VERSION)
+    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Android")
+      if(DEFINED ENV{TERMUX_VERSION})
+        set(CMAKE_HOST_SYSTEM_VERSION 24) # TODO make 24 automatically sync with Termux.
+      else()
+        execute_process(COMMAND getprop ro.build.version.sdk
+          OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_VERSION
+          OUTPUT_STRIP_TRAILING_WHITESPACE
+          ERROR_QUIET)
+      endif()
     else()
       execute_process(COMMAND ${CMAKE_UNAME} -r
         OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_VERSION
```
