### ISSUE TITLE
Package Request: Pianobar

### ISSUE THREAD

**Issue by vredesbyyrd** [termux/termux-packages#1712]
Pianobar, a console based Pandora player. It would be great to ditch the pandora app and use the awesome pianobar cli instead. I was going to try and compile for termux myself, but the more i dig the more i realize im probably in over my head.  

https://github.com/PromyLOPh/pianobar 
https://6xq.net/pianobar/

**Comment by sdrausty** [comment]
It looks like Pianobar is currently available in Termux through Arch Linux PRoot.  This script is designed to install Arch Linux in just a few keystrokes. Tapping this link https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh will transfer `setupTermuxArch.sh` to your device. Simply run `bash ~/storage/downloads/setupTermuxArch.sh` to install Arch Linux in Termux.  To install use `pacman -S pianobar` and this will install Pianobar on device.  

![screenshot_20171130-013043](https://user-images.githubusercontent.com/27742457/33417155-3eaa20e2-d56e-11e7-8961-46b4ea3cfb01.png)

**Comment by vredesbyyrd** [comment]
Quite fascinating. Arch on my android phone... arch is my daily driver so to learn of this is pretty cool. I was unaware you could install an entire environment like that, so thank you for enlightening me! When I am finished with work tonight i will definitely be looking into this. Thanks again for the tutorial and links.

**Comment by edward-p** [comment]
@iamlord [Pulseaudio](https://github.com/termux/termux-packages/issues/821) is now available on termux, I tried played audio from pianobar inside Termux Arch over Pulseaudio tcp. It works but low performance. The audio can't even be played at real time due to low performance. Maybe we need port it by using other audio playbacks.

**Comment by iamlord** [comment]
I am impressed you got that far. I had a similar issue with a debian vm where it played but it was, oh so, choppy. It would be nice to be able to convert the python to a native ver for android.

**Comment by tcaddy** [comment]
I tried to make pianobar from source.  Every development package is available except for libao.  When I try to compile libao, it won't make the plugin for pulse audio.

Pianobar will run, but it cannot output to an audio device.

More details here: https://github.com/PromyLOPh/pianobar/issues/664

**Comment by edward-p** [comment]
Done.
[Add packages: pianobar, libao #2641](https://github.com/termux/termux-packages/pull/2641)
The sound is much better than using `module-native-protocol-tcp`, which I did before, but still gets randomly choppy, I think it's a problem with pulseaudio.

**Comment by vredesbyyrd** [comment]
@edward-p 

Thanks for the info. I remember when I first posted about this I tired compiling libao but could not get it to build. Although It sounds like I will have to revisit this now :)  Cheers.

**Comment by edward-p** [comment]
@vredesbyyrd Both of `libao` and `pianobar` patched, I reopened a pull request [here](https://github.com/termux/termux-packages/pull/2744). Check if this fixed the choppy sound issues.

**Comment by iamlord** [comment]
Could we get a scratch brew recipe, or a termux pianobar package? I don't see libao.

**Comment by edward-p** [comment]
@iamlord
It will be available when my [pull request](https://github.com/termux/termux-packages/pull/2744) merged. You can build yourself if you can't wait.

**Comment by iamlord** [comment]
I've had issues installing from source. When running arch or ubuntu I can install it but it can't access my sound card. I can't use debian packages with dpkg because they do not have aarch64. I am going to ask them to create some. I think there may be a way to change the hardware ver in the source code.

**Comment by edward-p** [comment]
Since my pull request is still pending, I built these for you. (you can fix missing dependencies from the source)

[libao_pianobar_debs_aarch64.tar.gz](https://github.com/termux/termux-packages/files/2483523/libao_pianobar_debs_aarch64.tar.gz)

USE NON-OFFICIAL BUILT PACKAGES AT YOUR OWN RISK!

**Comment by iamlord** [comment]
Cool. I'm excited to try it out. I was looking at alien to convert some rpms but it won't let me do it on different hardware it seems.

**Comment by iamlord** [comment]
I just tried it out. Your amazing ed! This is really great work. Perhaps you could walk me through how you acomplished this. I have been trying for a while. Did you have to do some form of compiling or script editing? Also any chance at an English translation of your blog?

**Comment by edward-p** [comment]
Actually, my blog doesn't mention that. You can see all my changes for termux-packages [here](https://github.com/termux/termux-packages/pull/2744/files). I just added libao and pianobar by writing `build.sh` for them and do some patches to fix some issues in termux environment, which is already merged into upstream pianobar tree, you can track it [here](https://github.com/PromyLOPh/pianobar/pull/665) and [https://github.com/PromyLOPh/pianobar/issues/664](https://github.com/PromyLOPh/pianobar/issues/664)
To build termux-packages yourself, you need to see the [readme file](https://github.com/termux/termux-packages/blob/master/README.md) of this repository.

**Comment by iamlord** [comment]
Works pretty good. Sometimes it stops recognizing what sound device it is playing to and you have to force stop the APP. It does not recognize a received phone call and keeps playing on the phone and you have to pause it. Really great work!

**Comment by wokawoka** [comment]
Thanks for the 64bit pianobar debs.
Would it be possible for someone to share the 32bit ones? I've tried to compiled them but I don't have a suitable machine to do so at the moment. Many thanks

**Comment by edward-p** [comment]
Here you go:
[prebuild_debs_arm_20190214.zip](https://github.com/termux/termux-packages/files/2917727/prebuild_debs_arm_20190214.zip)

For aarch64:
[prebuild_debs_aarch64_20190214.zip](https://github.com/termux/termux-packages/files/2865957/prebuild_debs_aarch64_20190214.zip)

**Comment by wokawoka** [comment]
works supergreat! Many thanks!

**Comment by wokawoka** [comment]
@edward-p sorry for hijacking the thread but I have been happily listening to pianobar on my phone for 3 days but tonight I broke the magic.
I don't know if it's because I updated termux from f-droid or because I also made an apt-get update / upgrade, but unfortunately now pianobar can't play a single note anymore. It regularly connects and download the playlist, fetch the song and never start it.
At a certain point I've read the "Cannot open audio device" error of issue [#664](https://github.com/PromyLOPh/pianobar/issues/664). 
I've tried to remove/reinstall the packages that you provided with no luck. Any idea about how I could fix it?  It was too great

**Comment by edward-p** [comment]
@wokawoka
I think it's a pulseaudio issue.
Try `killall -9 pulseaudio` before running `pianobar`

**Comment by wokawoka** [comment]
thanks for replying back so quickly!
unfortunately killing pulseaudio is not solving the issue.
I even rebooted the phone, pianobar connects to pandora, receives the playlist and the first song title and lenght but never start playing it :((

**Comment by edward-p** [comment]
Can you run pulseaudio in another tag using `pulseaudio -vvv --daemonize=no &> ~/pulse.log` and upload the `pulse.log` ?

**Comment by edward-p** [comment]
think the link of between `pulseaudio` and `libao` is broken

**Comment by wokawoka** [comment]
@edward-p yes, something is wrong with pulseaudio. It's like termux is not running it by default in background anymore. 
As soon as I start logging with `pulseaudio -vvv --daemonize=no &> ~/pulse.log ` pianobar starts playing again.
Do you still need the log file? Any hint on how to make pulseaudio start by default again?
Thank you very much again!

**Comment by wokawoka** [comment]
or, if pulseadio should be invoked and started by pianobar, that doesn't happen anymore.
If I try to run pulseadio by itself without any parameter I get
$ pulseaudio
W: [pulseaudio] core.c: Failed to allocate shared posix-shm memory pool. Falling back to a normal memory pool.

**Comment by edward-p** [comment]
Pulseadio should be invoked and started by pianobar automatically. I found out that `cmus` also has the same issue. This should be a pulseaudio issue.

**Comment by wokawoka** [comment]
yes, I've read that afterwards, it seems that pianobar invoke pulseaudio because after launching pianobar I can see the pulseaudio process alive and I can kill it, but pianobar somehow can't start playing.
But if I run pianobar after having run `pulseaudio -vvv --daemonize=no` in a parallel termux session pianobar just works, whereas whenever I run just `pulseaudio` I receive the error
`W: [pulseaudio] pid.c: Stale PID file, overwriting.
W: [pulseaudio] core.c: Failed to allocate shared posix-shm memory pool. Falling back to a normal memory pool.`

**Comment by edward-p** [comment]
This is not an error, just a warning. It's safe to ignore it. There might be other issues that causes this.

**Comment by wokawoka** [comment]
ok, you are right. And I've just checked that if I just run `pulseaudio` in a session and then I start pianobar in another, it indeed starts playing the music.

What I can't understand is if pianobar is no more able to invoke pulseaudio, then why I can see the pulseaudio process spawning when I launch pianobar?
and, also, why it did work previously and now I need to launch pulseaudio manually. Was this problem triggered by updating termux from f-droid or by doing an apt-get upgrade/update?

Anyway, at least now I know how to avoid the problem by manually starting pulseaudio. Thank you again!

**Comment by edward-p** [comment]
Most likely by apt-get upgrade/update, `cmus` is also a victim of the new pulseaudio. This may be fixed in new pulseaudio builds.

**Comment by wokawoka** [comment]
alright, now everything is much more clear.
Thank you again!

**Comment by wokawoka** [comment]
As a follow up a new apt-get upgrade/update updated pulseaudio and fixed the problem. 
Thanks again for pointing me in the right ddirection

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/pull/2744 is merged now. Closing.
