### ISSUE TITLE
[Bug]: kid3 exit with error while open mp3

### ISSUE THREAD

**Issue by QkiZMR** [termux/termux-packages#17121]
### Problem description

When I'm trying to open mp3 file kid3 is throwing SIGSEGV error
```
Wrong JPEG library version: library is 62, caller expects 80
fish: Job 1, 'kid3-qt' terminated by signal SIGSEGV (Address boundary error)
```

### What steps will reproduce the bug?

1. Run kid3
2. Load mp3 file with cover
3. Kid3 will exit immediately 

### What is the expected behavior?

Load mp3 without problems to further edit

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=32356
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://termux.librehat.com/apt/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://termux.librehat.com/apt/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
12
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Mon Mar 6 05:24:34 CST 2023 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(100)
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:11
com.termux.styling versionCode:30
com.termux.tasker versionCode:6
```

**Comment by xtkoba** [comment]
Confirmed.

Not recommended but if this is urgent then a temporary workaround would be to

```bash
export LD_LIBRARY_PATH=$PREFIX/lib
```

before invoking Kid3. This may break other functionalities and known to actually break some other programs. So please use with care. I strongly recommend `unset`ting the `LD_LIBRARY_PATH` variable when you finish your work with Kid3.

I'm seeking for a proper solution.

**Comment by xtkoba** [comment]
Seems like a kind of SONAME conflict regarding `libjpeg.so`. Not sure but presumably introduced by recent change in `ffmpeg` package in which it was made to depend on `libandroid.so`.

Rebuilding `libjpeg-turbo` package with SOVERSION suffix added and then rebuilding revdeps may fix this. It may cause inconsistencies in bindist because `libjpeg-turbo` has quite a few revdeps and we cannot rebuild all of them in one run in GitHub Actions. I will post a new issue for notification.

**Comment by QkiZMR** [comment]
Thx, working fine now.
