### ISSUE TITLE
AUTO Complete Not Work in sqlcipher!!

### ISSUE THREAD

**Issue by Vanillma** [termux/termux-packages#17124]
Package is now available.

You can obtain it with these commands:
```
pkg install sqlcipher
```

_Originally posted by @ghost in https://github.com/termux/termux-packages/issues/5096#issuecomment-625472505_
            
Hello...I noticed that the autocomplete is not working!!...when I press the tab key, a tab appears!!...while in sqlite3 version it activates an autocomplete tab!!
This answer explains that the readline=yes option should be used during compilation!
https://superuser.com/a/622282
I haven't tried but I hope this bug will be fixed soon...thanks.

**Comment by truboxl** [comment]
Please download and test the artifacts whether the autocomplete works from https://github.com/termux/termux-packages/actions/runs/5622955693

**Comment by Vanillma** [comment]
> Please download and test the artifacts whether the autocomplete works from https://github.com/termux/termux-packages/actions/runs/5622955693

Did you fix it?😃
I would like to thank you very much😘❤️🧡💛💚💙💜🤎🤍♥️🖤
whatever I tried it didn't compile!!... did you compile it on Linux or Termux?!
