### ISSUE TITLE
[Package]: Dwarf Fortress

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#17125]
### Why is it worth to add this package?

It's quite a nice game that I'm interested in playing. I'm sure a lot of people like terminal games so it would make for a good addition to the Termux roster.

### Home page URL

http://www.bay12games.com/dwarves/

### Source code URL

http://www.bay12games.com/dwarves/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by 2096779623** [comment]
> Packages must be licensed under widely recognized open source license
Software should be licensed under Apache, BSD, GNU GPL, MIT or other well known open-source licenses. Software for which the source is available but distributed under non-free conditions is processed on an individual basis.
Software which is either closed-source, contain binary-only components or is distributed under End User License Agreement is not accepted.

It doesn't seem to be open source.
