### ISSUE TITLE
[Package]: ASCIIpOrtal

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#17127]
### Why is it worth to add this package?

Interesting game that could be added to termux's bunch of games

### Source code URL

https://github.com/cymonsgames/ASCIIpOrtal

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by 2096779623** [comment]
> Packages must be active, well-known projects

> Software available in major Linux distributions has more chances to be included into Termux repositories. We will not accept outdated, dead projects as well as projects which do not have active community.

You can submit this package request to [tur](https://github.com/termux-user-repository/tur).
