### ISSUE TITLE
Package request: redis

### ISSUE THREAD

**Issue by huiyiqun** [termux/termux-packages#172]

**Comment by fornwall** [comment]
Thanks, I've added this to [the package suggestion page](https://termux.com/package-suggestions.html).

**Comment by Neo-Oli** [comment]
Hi, I am re-opening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by RyanMontalbano** [comment]
I would really like to see this happen. Thanks for all the hard work. :)

**Comment by vishalbiswas** [comment]
Pull request open for redis https://github.com/termux/termux-packages/pull/813

**Comment by fornwall** [comment]
Thanks to @vaites there is now a redis package available for installation:

    packages install redis
