### ISSUE TITLE
Setup-storage PIxel C and Oreo

### ISSUE THREAD

**Issue by steve-j-wilcox** [termux/termux-packages#1721]
termux-setup-storage does not allow access to file system on Oreo (8.0), where previously on 7.X it worked as expected.

There are no errors reported.

termux-setup-storage
uname -a
Linux localhost 3.18.0-g3d6c7b39db3 #1 SMP PREEMPT Thu Aug 17 23:26:30 UTC 2017 aarch64 Android

**Comment by fornwall** [comment]
Thanks - this is indeed a problem when running under Android 8. Subscribe to the existing issue https://github.com/termux/termux-packages/issues/1578 to be notified about progress!
