### ISSUE TITLE
include symlinks in bootstrap*.zip

### ISSUE THREAD

**Issue by stephengroat** [termux/termux-packages#1723]
include symlinks in bootstrap zip files for #1169

**Comment by stephengroat** [comment]
@fornwall anyway you could share the scripts for making the bootstraps? i'll test out what including the symlinks does on android, but i can only do chrome-based and 8.0

**Comment by stephengroat** [comment]
@fornwall any interest in this? could really help with #1169 and it's kind of a blocker

**Comment by Grimler91** [comment]
Closing this since it is possible the bootstrap zip contain a symlink-list now (don't know when that was added).

**Comment by stephengroat** [comment]
@Grimler91 that symlink list doesn't really work for #1169 because it's very difficult to address the non-ASCII characters in that file in bash

**Comment by Grimler91** [comment]
@stephengroat you mean the arrow character? 

I've been looking a bit at continuing #1169 (but without using apt) and created the symlinks with:
```bash
while read link; do
    ln -sf ${link/←/ }
done<SYMLINKS.txt
```

**Comment by stephengroat** [comment]
@Grimler91 that exactly it, never worked for me previously! let me give it a try right now

**Comment by stephengroat** [comment]
@Grimler91 do you know what directory the `unzip` runs in normally? i need to know where to run the linking. i'm starting down the path of looking at the app, thought i'd ask first

**Comment by stephengroat** [comment]
@Grimler91 do you know what directory the `unzip` runs in normally? i need to know where to run the linking. i'm starting down the path of looking at the app, thought i'd ask first

**Comment by Grimler91** [comment]
@stephengroat from PREFIX, so after unzipping the bootstrap to PREFIX you can cd there, run the codde snippet and then rm SYMLINKS.txt

**Comment by stephengroat** [comment]
not 100% sure it's run in `PREFIX` since there's a ton of `libs` in there. Could it be run in `lib`?

the `..` before the `busybox` links also makes me think that's the same
