### ISSUE TITLE
#pip install pybluez libbluethooth

### ISSUE THREAD

**Issue by stainslav** [termux/termux-packages#1724]
Ez Colton:
----------------------------------------
  Failed building wheel for pybluez
  Running setup.py clean for pybluez
Failed to build pybluez
Installing collected packages: pybluez
  Running setup.py install for pybluez ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-warbvsp2/pybluez/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-01ho1vnc-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.6
    creating build/lib.linux-aarch64-3.6/bluetooth
    copying bluetooth/ble.py -> build/lib.linux-aarch64-3.6/bluetooth
    copying bluetooth/bluez.py -> build/lib.linux-aarch64-3.6/bluetooth
    copying bluetooth/btcommon.py -> build/lib.linux-aarch64-3.6/bluetooth
    copying bluetooth/msbt.py -> build/lib.linux-aarch64-3.6/bluetooth
    copying bluetooth/osx.py -> build/lib.linux-aarch64-3.6/bluetooth
    copying bluetooth/widcomm.py -> build/lib.linux-aarch64-3.6/bluetooth
    copying bluetooth/__init__.py -> build/lib.linux-aarch64-3.6/bluetooth
    running build_ext
    building 'bluetooth._bluetooth' extension
    creating build/temp.linux-aarch64-3.6
    creating build/temp.linux-aarch64-3.6/bluez
    aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Oz -Oz -fPIC -I./port3 -I/data/data/com.termux/files/usr/include/python3.6m -c bluez/btmodule.c -o build/temp.linux-aarch64-3.6/bluez/btmodule.o
    In file included from bluez/btmodule.c:20:
    bluez/btmodule.h:5:10: fatal error: 'bluetooth/bluetooth.h' file not found
    #include <bluetooth/bluetooth.h>
             ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'aarch64-linux-android-clang' failed wit

**Comment by fornwall** [comment]
Thanks for reporting! Unfortunately, this is a general limitation of Android that bluez (which provides `< bluetooth/bluetooth.h>`) is not supported - you will need to find another tool to access Android bluetooth functionality.
