### ISSUE TITLE
Error building Electric-Fence

### ISSUE THREAD

**Issue by stainslav** [termux/termux-packages#1725]
~/electric-fence ➤ make -j8
cc -g   -c -o page.o page.c
page.c: In function 'stringErrorReport':
page.c:48:28: error: 'sys_nerr' undeclared (first use in this function)              if ( errno > 0 && errno < sys_nerr )
                            ^~~~~~~~
page.c:48:28: note: each undeclared identifier is reported only once for each function it appears in
page.c:49:10: error: 'sys_errlist' undeclared (first use in this function)
   return sys_errlist[errno];
          ^~~~~~~~~~~
make: *** [<builtin>: page.o] Error 1
~/electric-fence ➤

**Comment by fornwall** [comment]
Thanks! The lack of `sys_errlist` is an Android limitation that must be worked around in the source code (which already much does does) - you can contact the Electric-Fence developers for that!
