### ISSUE TITLE
anybody tried to build mysql-server and mysql-client?

### ISSUE THREAD

**Issue by stainslav** [termux/termux-packages#1726]
I have tried but config.guess problem
May anybody fix this config.guess file for termux?

https://drive.google.com/file/d/0B-ZW5sShbL1IbHdNUjlsMjJsa0U/view?usp=drivesdk

**Comment by fornwall** [comment]
Thanks for the interest! Note that github issues is not the right forum for this, try any of the following channels instead:

- Google+ community: https://termux.com/community
- Mailing list: https://groups.io/g/termux/
- Gitter: https://gitter.im/termux/termux
- IRC: #termux on freendoe

**Comment by stainslav** [comment]
@fronwall please build mysql

**Comment by fornwall** [comment]
@stainslav Have you tried using mariadb?
