### ISSUE TITLE
Package Request: dlib

### ISSUE THREAD

**Issue by jxjhheric** [termux/termux-packages#1728]
When I install face_recognition: pip3 install face_recognition
Get this errors:
Running setup.py install for dlib ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-7i7w4dg5/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-tl28wd9m-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Detected Python architecture: 32bit
    Detected platform: linux
    Configuring cmake ...
    CANNOT LINK EXECUTABLE: cannot locate symbol "__gnu_ldivmod_helper" referenced by "/data/data/com.termux/files/usr/lib/libarchive.so"...
    page record for 0xb6cd004c was not found (block_size=64)
    error: cmake configuration failed!

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-7i7w4dg5/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-tl28wd9m-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-7i7w4dg5/dlib/

**Comment by Grimler91** [comment]
I looked at dlib briefly and it seems to require boost to be configured with `--with-libaries=python`, which could be added according to https://github.com/termux/termux-packages/pull/974.

**Comment by youerning** [comment]
you can try this LDFLAGS=" -llog -lpython3" python3 setup.py install --set 'DCMAKE_INSTALL_PREFIX=$PREFIX'.

**Comment by xeffyr** [comment]
Closing as package installable through `pip`. Termux has all its dependencies, just they need to be installed manually.

**Comment by AravindRajKarur** [comment]
try this
git clone https://github.com/davisking/dlib.git
cd dlib
mkdir build; cd build; cmake ..; cmake --build
cd ..
python3 setup.py install
