### ISSUE TITLE
zsh: $fpath[1] is outside of $PREFIX

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#1730]
In zsh the first value in `$fpath` is outside of `$PREFIX`.
```
$ echo $fpath
/usr/local/share/zsh/site-functions /data/data/com.termux/files/usr/share/zsh/site-functions /data/data/com.termux/files/usr/share/zsh/5.4.2/functions
```
While zsh normally just ignores that entry it does pose a problem in Makefiles
If a program wants to install a completion script it would normally run 
`$( unset FPATH; zsh -fc 'print -r -- $fpath[1]' )` to find the correct directory, which in this case fails.

This entry should be removed

**Comment by fornwall** [comment]
Thanks - this should be fixed in the updated `5.4.2-1` version of the zsh package which is now available as an update!
