### ISSUE TITLE
pypy{,3}: Dubious dependency on libxml2

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#17319]
Do `pypy{,3}` really depend on `libxml2`? AFAIK the shared library `libxml2.so` is not linked against.

@licy183

**Comment by licy183** [comment]
I'm not sure. IIRC these dependencies are copied from one website (maybe a Dockerfile that supports pypy cross translation)...

**Comment by landfillbaby** [comment]
there's no mention of libxml on https://doc.pypy.org/en/latest/build.html

**Comment by linusjf** [comment]
```
Checking Forecasting/installer.R for whitespace...                                              Traceback (most recent call last):                File "/data/data/com.termux/files/usr/bin/wscheck", line 5, in <module>                           from wscheck.__main__ import main             File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wscheck/__main__.py", line 10, in <module>                                     from wscheck.printer import ErrorPrinter      File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wscheck/printer.py", line 2, in <module>                                       from lxml import builder, etree               File "src/lxml/builder.py", line 44, in init lxml.builder                                     ImportError: dlopen failed: cannot find "libxml2.so" from verneed[1] in DT_NEEDED list for "/data/data/com.termux/files/usr/lib/python3.11/site-packages/lxml/etree.cpython-311.so"
```

Getting the above error while executing `wscheck` against files. Problems started with latest version of python. Worked fine earlier. Is it connected to above?

**Comment by xtkoba** [comment]
@linusjf No. `pypy{,3}` is different from `python`.

**Comment by xtkoba** [comment]
@licy183 So can you please reconsider the dependency?

Also consider updating `pypy{,3}` to version 7.3.12. According to <a href="https://bugs.gentoo.org/show_bug.cgi?id=908018">some 3rd party source</a> it contains several fixes for security vulnerabilities.

I will enforce these if not done until next Saturday. Thanks.

**Comment by licy183** [comment]
Thanks for your information. I will do it this weekend. I don't have a PC with me now.
