### ISSUE TITLE
[Bug]: can't install pycryptodome nor pycryptodomex using pip

### ISSUE THREAD

**Issue by nacho00112** [termux/termux-packages#17333]
### Problem description

I can't install pycryptodome nor pycryptodomex using pip.

### What steps will reproduce the bug?

For pycryptodome:
```bash
pip install pycryptodome
```
Outputs:

building 'Crypto.Cipher._raw_arc2' extension                       arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -DHAVE_STDINT_H -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=32 -DLTC_NO_ASM -DHAVE_POSIX_MEMALIGN -Isrc/ -I/data/data/com.termux/files/usr/include/python3.11 -c src/ARC2.c -o build/temp.linux-armv7l-cpython-311/src/ARC2.o                                                            arm-linux-androideabi-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r25c-api-24-v2/sysroot/usr/lib -march=armv7-a -Wl,--fix-cortex-a8 -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r25c-api-24-v2/sysroot/usr/lib build/temp.linux-armv7l-cpython-311/src/ARC2.o -L/data/data/com.termux/files/usr/lib -o build/lib.linux-armv7l-cpython-311/Crypto/Cipher/_raw_arc2.abi3.so                              ld.lld: error: section .note.android.ident at 0x134 of size 0xFFFFFFFFFFFFFECC exceeds available address space                        ld.lld: error: section .rodata at 0x23C of size 0xFFFFFFFFFFFFFDC4 exceeds available address space                                    ld.lld: error: section .data.rel.ro at 0x1090 of size 0xFFFFFFFFFFFFEF70 exceeds available address space                              ld.lld: error: section .dynsym file range overlaps with .plt       >>> .dynsym range is [0x0, 0x8F]                                   >>> .plt range is [0x0, 0x8F]                                                                                                         ld.lld: error: section .gnu.version file range overlaps with .data.rel.ro
      >>> .gnu.version range is [0x90, 0xA1]                             >>> .data.rel.ro range is [0x90, 0xFFFFFFFFFFFFEFFF]
                                                                         ld.lld: error: section .data.rel.ro file range overlaps with .gnu.version_r                                                           >>> .data.rel.ro range is [0x90, 0xFFFFFFFFFFFFEFFF]               >>> .gnu.version_r range is [0xA4, 0xC3]                                                                                              ld.lld: error: section .dynstr file range overlaps with .note.android.ident                                                           >>> .dynstr range is [0xDC, 0x1F3]                                 >>> .note.android.ident range is [0x134, 0xFFFFFFFFFFFFFFFF]                                                                          ld.lld: error: section .dynsym virtual address range overlaps with .plt                                                               >>> .dynsym range is [0x0, 0x8F]                                   >>> .plt range is [0x0, 0x8F]                                                                                                         ld.lld: error: section .plt virtual address range overlaps with .dynamic                                                              >>> .plt range is [0x0, 0x8F]                                      >>> .dynamic range is [0x0, 0xB7]                                                                                                     ld.lld: error: section .dynamic virtual address range overlaps with .gnu.version                                                      >>> .dynamic range is [0x0, 0xB7]                                  >>> .gnu.version range is [0x90, 0xA1]                                                                                                ld.lld: error: section .gnu.version_r virtual address range overlaps with .got                                                        >>> .gnu.version_r range is [0xA4, 0xC3]
      >>> .got range is [0xB8, 0xBF]                               
      ld.lld: error: section .got.plt virtual address range overlaps with .gnu.hash                                                         >>> .got.plt range is [0xC0, 0xE7]                                 >>> .gnu.hash range is [0xC4, 0xDB]
                                                                         ld.lld: error: section .dynstr virtual address range overlaps with .note.android.ident                                                >>> .dynstr range is [0xDC, 0x1F3]
      >>> .note.android.ident range is [0x134, 0xFFFFFFFFFFFFFFFF] 
      ld.lld: error: section .dynsym load address range overlaps with .plt
      >>> .dynsym range is [0x0, 0x8F]                                   >>> .plt range is [0x0, 0x8F]
                                                                         ld.lld: error: section .plt load address range overlaps with .dynamic                                                                 >>> .plt range is [0x0, 0x8F]
      >>> .dynamic range is [0x0, 0xB7]                            
      ld.lld: error: section .dynamic load address range overlaps with .gnu.version
      >>> .dynamic range is [0x0, 0xB7]                                  >>> .gnu.version range is [0x90, 0xA1]
                                                                         ld.lld: error: section .gnu.version_r load address range overlaps with .got                                                           >>> .gnu.version_r range is [0xA4, 0xC3]
      >>> .got range is [0xB8, 0xBF]                               
      ld.lld: error: section .got.plt load address range overlaps with .gnu.hash
      >>> .got.plt range is [0xC0, 0xE7]                                 >>> .gnu.hash range is [0xC4, 0xDB]
                                                                         ld.lld: error: section .dynstr load address range overlaps with .note.android.ident                                                   >>> .dynstr range is [0xDC, 0x1F3]
      >>> .note.android.ident range is [0x134, 0xFFFFFFFFFFFFFFFF]       clang-16: error: linker command failed with exit code 1 (use -v to see invocation)                                                    error: command '/data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1                              [end of output]
                                                                     note: This error originates from a subprocess, and is likely not a problem with pip.                                                  ERROR: Failed building wheel for pycryptodome
  Running setup.py clean for pycryptodome

For pycryptodomex:
```bash
pip install pycryptodomex
```
Outputs:
building 'Cryptodome.Cipher._raw_eksblowfish' extension            arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -DHAVE_STDINT_H -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=32 -DLTC_NO_ASM -DHAVE_POSIX_MEMALIGN -Isrc/ -I/data/data/com.termux/files/usr/include/python3.11 -c src/blowfish_eks.c -o build/temp.linux-armv7l-cpython-311/src/blowfish_eks.o                                            arm-linux-androideabi-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r25c-api-24-v2/sysroot/usr/lib -march=armv7-a -Wl,--fix-cortex-a8 -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r25c-api-24-v2/sysroot/usr/lib build/temp.linux-armv7l-cpython-311/src/blowfish_eks.o -L/data/data/com.termux/files/usr/lib -o build/lib.linux-armv7l-cpython-311/Cryptodome/Cipher/_raw_eksblowfish.abi3.so           ld.lld: error: section .note.android.ident at 0x134 of size 0xFFFFFFFFFFFFFECC exceeds available address space                        ld.lld: error: section .rodata at 0x240 of size 0xFFFFFFFFFFFFFDC0 exceeds available address space                                    ld.lld: error: section .data.rel.ro at 0x1090 of size 0xFFFFFFFFFFFFEF70 exceeds available address space                              ld.lld: error: section .dynsym file range overlaps with .plt       >>> .dynsym range is [0x0, 0x8F]                                   >>> .plt range is [0x0, 0x8F]                                                                                                         ld.lld: error: section .gnu.version file range overlaps with .data.rel.ro                                                             >>> .gnu.version range is [0x90, 0xA1]                             >>> .data.rel.ro range is [0x90, 0xFFFFFFFFFFFFEFFF]                                                                                  ld.lld: error: section .data.rel.ro file range overlaps with .gnu.version_r                                                           >>> .data.rel.ro range is [0x90, 0xFFFFFFFFFFFFEFFF]               >>> .gnu.version_r range is [0xA4, 0xC3]                                                                                              ld.lld: error: section .dynstr file range overlaps with .note.android.ident                                                           >>> .dynstr range is [0xDC, 0x1F3]                                 >>> .note.android.ident range is [0x134, 0xFFFFFFFFFFFFFFFF]                                                                          ld.lld: error: section .dynsym virtual address range overlaps with .plt                                                               >>> .dynsym range is [0x0, 0x8F]                                   >>> .plt range is [0x0, 0x8F]                                                                                                         ld.lld: error: section .plt virtual address range overlaps with .dynamic                                                              >>> .plt range is [0x0, 0x8F]                                      >>> .dynamic range is [0x0, 0xB7]                                                                                                     ld.lld: error: section .dynamic virtual address range overlaps with .gnu.version                                                      >>> .dynamic range is [0x0, 0xB7]                                  >>> .gnu.version range is [0x90, 0xA1]                                                                                                ld.lld: error: section .gnu.version_r virtual address range overlaps with .got                                                        >>> .gnu.version_r range is [0xA4, 0xC3]                           >>> .got range is [0xB8, 0xBF]                                                                                                        ld.lld: error: section .got.plt virtual address range overlaps with .gnu.hash                                                         >>> .got.plt range is [0xC0, 0xE7]                                 >>> .gnu.hash range is [0xC4, 0xDB]                                                                                                   ld.lld: error: section .dynstr virtual address range overlaps with .note.android.ident                                                >>> .dynstr range is [0xDC, 0x1F3]                                 >>> .note.android.ident range is [0x134, 0xFFFFFFFFFFFFFFFF]                                                                          ld.lld: error: section .dynsym load address range overlaps with .plt                                                                  >>> .dynsym range is [0x0, 0x8F]                                   >>> .plt range is [0x0, 0x8F]                                                                                                         ld.lld: error: section .plt load address range overlaps with .dynamic                                                                 >>> .plt range is [0x0, 0x8F]                                      >>> .dynamic range is [0x0, 0xB7]                                                                                                     ld.lld: error: section .dynamic load address range overlaps with .gnu.version                                                         >>> .dynamic range is [0x0, 0xB7]
      >>> .gnu.version range is [0x90, 0xA1]                                                                                                ld.lld: error: section .gnu.version_r load address range overlaps with .got                                                           >>> .gnu.version_r range is [0xA4, 0xC3]                           >>> .got range is [0xB8, 0xBF]                                                                                                        ld.lld: error: section .got.plt load address range overlaps with .gnu.hash                                                            >>> .got.plt range is [0xC0, 0xE7]                                 >>> .gnu.hash range is [0xC4, 0xDB]                                                                                                   ld.lld: error: section .dynstr load address range overlaps with .note.android.ident                                                   >>> .dynstr range is [0xDC, 0x1F3]                                 >>> .note.android.ident range is [0x134, 0xFFFFFFFFFFFFFFFF]       Invalid address 0xa5c0e000 passed to free: value not allocated                                                                        PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.                           clang-16: error: unable to execute command: Aborted                clang-16: error: linker command failed due to signal (use -v to see invocation)                                                       error: command '/data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1                              [end of output]                                                                                                                   note: This error originates from a subprocess, and is likely not a problem with pip.                                                  ERROR: Failed building wheel for pycryptodomex                     Running setup.py clean for pycryptodomex

### What is the expected behavior?

pycryptodome and pycryptodomex being installed correctly

### System information

termux-info:
Termux Variables:                                                  TERMUX_APK_RELEASE=F_DROID                                         TERMUX_APP_PACKAGE_MANAGER=apt                                     TERMUX_APP_PID=5785                                                TERMUX_IS_DEBUGGABLE_BUILD=0                                       TERMUX_MAIN_PACKAGE_FORMAT=debian                                  TERMUX_VERSION=0.118.0                                             Packages CPU architecture:                                         arm                                                                Subscribed repositories:                                           # sources.list                                                     deb https://dl.kcubeterm.com/termux-main stable main               # dichvucoder-repo (sources.list.d/dichvucoder.list)               deb https://repo.dichvucoder.com dvc-packages dvc                  # tur-repo (sources.list.d/tur.list)                               deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# root-repo (sources.list.d/root.list)                             deb https://dl.kcubeterm.com/termux-root root stable               # x11-repo (sources.list.d/x11.list)                               deb https://dl.kcubeterm.com/termux-x11 x11 main                   Updatable packages:                                                All packages up to date                                            termux-tools version:                                              1.38.3                                                             Android version:                                                   7.0                                                                Kernel build information:                                          Linux localhost 3.10.49-gf2f82e6-00003-g39ffe37 #1 SMP PREEMPT Sat Mar 17 15:13:00 CST 2018 armv7l Android                            Device manufacturer:                                               AlcatelOneTouch                                                    Device model:                                                      Alcatel_5044R                                                      LD Variables:
LD_LIBRARY_PATH=                                                   LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by xtkoba** [comment]
This issue needs to be narrowed down.

This does not occur on my Android 12 aach64 environment. (My `termux-info` output is attached at the end of this comment.)

The author's environment reads Android 7.0 arm (32-bit) and yes the issue could happen on it.

Can anyone else confirm this on arm (32-bit) arch?

<details>
<summary>My `termux-info` output</summary>

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5893
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
12
Kernel build information:
Linux localhost 4.19.191-g11f8accf2f25 #1 SMP PREEMPT Wed May 24 14:18:13 CST 2023 aarch64 Android
Device manufacturer:
motorola
Device model:
moto e32(s)
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

</details>

**Comment by xtkoba** [comment]
(Moderation memo: this could happen when compiling and linking any other stuff, not just `pycryptodome` or anything through `pip`.)

**Comment by xtkoba** [comment]
Not reproducing on my Android 8.1 aarch64 with 32-bit userland.

Unfortunately I do not have access to any Android 7.x enviroment and I am afraid I cannot confirm this on my own.

If this is specific to Android 7.x, then it is worth while trying `LD_PRELOAD`ing `libandroid-support.so` and seeing if anything changes:

```bash
export LD_PRELOAD=${LD_PRELOAD+$LD_PRELOAD:}$PREFIX/lib/libandroid-support.sow
```

<details>
<summary>My `termux-info` output (Android 8.1 aarch64 with 32-bit userland)</summary>

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=10074
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.82-perf+ #1 SMP PREEMPT Wed Feb 27 13:05:28 CST 2019 armv8l Android
Device manufacturer:
asus
Device model:
ASUS_X01AD
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

<details>

**Comment by xtkoba** [comment]
(Moderation memo: the labels "arch-arm" and "android-7.x" are just teasers as of now; they will be removed if they turn out to be irrelevant.)

**Comment by nacho00112** [comment]
This also might be some pycryptodome specific problem

**Comment by truboxl** [comment]
Not reproducible for aarch64 Android 7, will check arm later
```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5569
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.termux.dev/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
7.0
Kernel build information:
Linux localhost 3.18.35+ #1 SMP PREEMPT Fri Mar 22 16:46:06 CST 2019 aarch64 Android
Device manufacturer:
Sony
Device model:
F3116
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api
com.termux.boot
```
```
~ $ pip install pycryptodome
Collecting pycryptodome
  Downloading pycryptodome-3.18.0.tar.gz (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 575.9 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pycryptodome
  Building wheel for pycryptodome (pyproject.toml) ... done
  Created wheel for pycryptodome: filename=pycryptodome-3.18.0-cp35-abi3-linux_aarch64.whl size=1848575 sha256=704e90408eca073cf8bbb37b3166f3ff2cd2a52e170a7150cfb9800bd20fc947
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/96/39/70/aa399bdb7cad18abf13aac9338ea6ffc2db84a3de6ab7b38fa
Successfully built pycryptodome
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.18.0
```

**Comment by truboxl** [comment]
Not reproducible
```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirror.termux.dev/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
7.0
Kernel build information:
Linux localhost 3.18.35+ #1 SMP PREEMPT Fri Mar 22 16:46:06 CST 2019 armv8l Android
Device manufacturer:
Sony
Device model:
F3116
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api
com.termux.boot
```
```
~ $ pip install pycryptodome
Collecting pycryptodome
  Using cached pycryptodome-3.18.0.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pycryptodome
  Building wheel for pycryptodome (pyproject.toml) ... done
  Created wheel for pycryptodome: filename=pycryptodome-3.18.0-cp35-abi3-linux_armv8l.whl size=1893578 sha256=8237ea0623ceb388fcea435d9374796efb30e0dc1402ef3800a9a4b2b136ca69
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/96/39/70/aa399bdb7cad18abf13aac9338ea6ffc2db84a3de6ab7b38fa
Successfully built pycryptodome
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.18.0
```
```
~ $ pip install pycryptodomex
Collecting pycryptodomex
  Using cached pycryptodomex-3.18.0.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pycryptodomex
  Building wheel for pycryptodomex (pyproject.toml) ... done
  Created wheel for pycryptodomex: filename=pycryptodomex-3.18.0-cp35-abi3-linux_armv8l.whl size=1896806 sha256=a8e91978b230488cf2b5bb6c35ea4f3ff3b29b7dca861260ac7cb198d50329f0
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/41/93/e9/8943b9c82b7709374b57812402ff30b4ce416b638049c78ccb
Successfully built pycryptodomex
Installing collected packages: pycryptodomex
Successfully installed pycryptodomex-3.18.0
```

**Comment by nacho00112** [comment]
Fixed, making a backup of my files and deleting the termux data worked for me
