### ISSUE TITLE
hashdeep segfaults (failed assert) on Acer Chromebook R11

### ISSUE THREAD

**Issue by valmar** [termux/termux-packages#1733]
hashdeep segfaults on the Acer Chromebook R11 after last update:

$ hashdeep --help
/home/fornwall/.termux-build/hashdeep/src/src/main.cpp:1250: int main(int, char **): assertion "sizeof(off_t)==8" failed
Aborted (core dumped)

$ uname -m
i686

ChromeOS version:
61.0.3163.123 (Official Build) (64-bit)

Android version:
Nougat

**Comment by sdrausty** [comment]
@valmar can you please post `uname -mo` too? I wish I could be of more help, but I don't have a Chromebook. Your -o output will be of great help at https://raw.githubusercontent.com/sdrausty/TermuxArch/master/knownconfigurations.sh hopefully.

**Comment by valmar** [comment]
Sure!

Here it is:

$ uname -mo
i686 Android

**Comment by fornwall** [comment]
This should now be fixed in the latest 4.4-1 version of the hashdeep package - install with `pkg up`.

Unfortunately this updates requires Android 7.0 or later for 32-bit arches (arm and i686) to work correctly.
