### ISSUE TITLE
[Packaging]: mesa-vulkan-icd-freedreno is useless for x86 and x86_64 architectures

### ISSUE THREAD

**Issue by truboxl** [termux/termux-packages#17336]
### Problem description

https://packages-cf.termux.dev/apt/termux-main/pool/main/m/mesa-vulkan-icd-freedreno/

Observe that there are packages for i686 and x86_64. These will never be used in the real world given the hardware is ARM only.

### What steps will reproduce the bug?

n/a

### What is the expected behavior?

Should be disabled for x86 and x86_64 and repackaged under mesa-vulkan-drivers when we keep expanding our hardware support.

Fedora and Debian selectively disables build options for specific architectures. We should follow that.

https://packages.debian.org/sid/amd64/mesa-vulkan-drivers/filelist
https://packages.debian.org/sid/arm64/mesa-vulkan-drivers/filelist
https://src.fedoraproject.org/rpms/mesa/blob/rawhide/f/mesa.spec

### System information

n/a

**Comment by licy183** [comment]
Although the option in build.sh can be modified, our building system doesn't support `TERMUX_SUBPKG_BLACKLISTED_ARCHES`...

**Comment by xtkoba** [comment]
> Although the option in build.sh can be modified, our building system doesn't support `TERMUX_SUBPKG_BLACKLISTED_ARCHES`...

Let's implement it. Please open a new issue for it.

**Comment by xtkoba** [comment]
Now the following line should work for `*.subpackage.sh`.

```bash
TERMUX_SUBPKG_EXCLUDED_ARCHES="i686, x86_64"
```

I won't work on it on my own, because I have no idea what this subpackage is for. Please merge the change on your own. Thanks.
