### ISSUE TITLE
Is there any way to execute files from sdcard?

### ISSUE THREAD

**Issue by iocmet** [termux/termux-packages#17344]
I tried create symlink to /data/data/com.termux/files/usr to sdcard because i have low amount of free memory but i ran into permission denied because of noexec

**Comment by TomJo2000** [comment]
Android prohibits apps from running executables from outside their own directory.
(In Termux's case usually referred to as the `$PREFIX`)

As such any executables need to be located under the `/data/data/com.termux/files/` directory, or any its subdirectories.
*Not* on "adoptable" or "external" storage.

**Comment by Agono0** [comment]
@iocmet 
Actually you can (like execute python file or whatever Read/Write) in sdcard termux `prefix`
Like in my phone:
`/storage/7ADB-1AF9/Android/data/com.termux/`

`7ADB-1AF9` is my sdcard name.

**Comment by xtkoba** [comment]
Closing as answered.

FYI, Termux Wiki already has an article about this: https://wiki.termux.com/wiki/Internal_and_external_storage

**Comment by romanovj** [comment]
use adoptable storage with my "hack"
https://www.reddit.com/r/termux/comments/12hty88/comment/jfuv5mg/
