### ISSUE TITLE
[Bug]: Vulkan Generic vkEnumerateInstanceExtensionProperties points to the loader

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-packages#17343]
### Problem description

I don't know if I have all the necessary packages installed to run Vulkan (Generic) on Termux. Vulkan Android runs fine, however after installing the generic packages (swrast / freedreno) it throws this error (in vulkaninfo):

```
WARNING: [Loader Message] Code 0 : loader_scanned_icd_add: Using deprecated ICD interface of 'vkGetInstanceProcAddr' instead of 'vk_icdGetInstanceProcAddr' for ICD /data/data/com.termux/files/usr/lib/libvulkan.so
WARNING: [Loader Message] Code 0 : loader_scanned_icd_add: Driver /data/data/com.termux/files/usr/lib/libvulkan.so supports Vulkan 1.3, but only supports loader interface version 0. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
ERROR: [Loader Message] Code 0 : loader_add_instance_extensions: /data/data/com.termux/files/usr/lib/libvulkan.so's vkEnumerateInstanceExtensionProperties points to the loader, this would lead to infinite recursion.
ERROR: [Loader Message] Code 0 : loader_add_instance_extensions: /data/data/com.termux/files/usr/lib/libvulkan.so's vkEnumerateInstanceExtensionProperties points to the loader, this would lead to infinite recursion.
```

vkcube doesn't work either, but without any errors.

Maybe the problem is with kernel version. Lenovo and Motorola uses outdated version of kernels

### What steps will reproduce the bug?

^

### What is the expected behavior?

The best Vulkan experience in my life

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=1391
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://ftp.fau.de/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://ftp.fau.de/termux/termux-root root stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://ftp.fau.de/termux/termux-x11 x11 main
Updatable packages:
zstd/stable 1.5.5-1 aarch64 [upgradable from: 1.5.5]
termux-tools version:
1.38.3
Android version:
12
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Fri Oct 28 08:27:23 CDT 2022 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(100)
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:12

```

**Comment by truboxl** [comment]
It may help if you can compare mesa from the tur-repo and the main repo.

**Comment by licy183** [comment]
You can run `vulkaninfo` with `VK_LOADER_DEBUG=all` to see how vulkan-loader-generic loads the drivers.

**Comment by IntinteDAO** [comment]
> It may help if you can compare mesa from the tur-repo and the main repo.
@truboxl Doesn't work either with the same bug.

> You can run `vulkaninfo` with `VK_LOADER_DEBUG=all` to see how vulkan-loader-generic loads the drivers.
@licy183 

Mesa:
https://zerobin.thican.net/?a7811b64fd64bcc7#H3yDweUoRvy5Z26pgVUUNty4WKs4yi5ifHJRrGru6TRq

Mesa-zink:
https://zerobin.thican.net/?84f849698fe4bb37#ER5AFPcxyCNtraz9ran4bxu7Sj4SHRNJMMEPRJZUNz6y

**Comment by licy183** [comment]
Maybe the cause is the file `/data/data/com.termux/files/usr/share/vulkan/icd.d/vulkan.json`. If I guess correctly, it sets `library_path` to `libvulkan.so`.

**Comment by truboxl** [comment]
Confirmed circular loading caused the issue. Need to find out which package `/data/data/com.termux/files/usr/share/vulkan/icd.d/vulkan.json` falls under...

**Comment by licy183** [comment]
No such file have been found using apt-file...
```
~ $ apt-file search /data/data/com.termux/files/usr/share/vulkan/icd.d/
mesa-vulkan-icd-freedreno: /data/data/com.termux/files/usr/share/vulkan/icd.d/freedreno_icd.aarch64.json
mesa-vulkan-icd-swrast: /data/data/com.termux/files/usr/share/vulkan/icd.d/lvp_icd.aarch64.json
swiftshader: /data/data/com.termux/files/usr/share/vulkan/icd.d/vk_swiftshader_icd.json
~ $
```

**Comment by IntinteDAO** [comment]
@licy183 
It's possible it's some kind of residue, on Termux on my phone I often test if an app can be ported before I try to build it in docker.

On Freedreno, on the other hand, I get a message that I don't have support for DRI3 in vkcube. Is there a fix for this?

However, swrast works, so problem solved.

**Comment by licy183** [comment]
> On Freedreno, on the other hand, I get a message that I don't have support for DRI3 in vkcube. Is there a fix for this?

Set `MESA_VK_WSI_DEBUG=sw` to force mesa using software WSI

**Comment by IntinteDAO** [comment]
@licy183 
Works, thank you - closing
