### ISSUE TITLE
fish -c 'read x; read y' error

### ISSUE THREAD

**Issue by rubikitch** [termux/termux-packages#1735]
In termux on Android 5.1.1

    u0_a136@localhost ~> cd .config; mv fish fish0; fish -c 'read x; read y'; mv fish0 fish; cd ..
    read> 0
    0
    <E> fish: src/reader.cpp:1559: failed assertion: input_initialized
    <E> fish: Sorry, but your system does not support backtraces
    'fish -c 'read x; read y'' has stopped
    fish: Job 1, 'fish -c 'read x; read y'' terminated by signal SIGABRT (Abort)

In my Linux computer, it does not occur.
What's wrong?

**Comment by xeffyr** [comment]
Same error on Android 6.0.1.

**Comment by xeffyr** [comment]
This problem fixed in [2.7b1](https://github.com/fish-shell/fish-shell/releases/tag/2.7b1).

**Comment by fornwall** [comment]
@xeffyr Nice find. Seems to be this issue: https://github.com/fish-shell/fish-shell/issues/4206

**Comment by fornwall** [comment]
The updated version `2.6.0-3` of the fish package is now patched to contain the fix for this - update with `pkg up`.

**Comment by rubikitch** [comment]
The problem is fixed. Thank you very much.
