### ISSUE TITLE
Error with termux-exec

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#1736]
```
[14:16] ~ > apksigner --help
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
page record for 0xf72e000c was not found (block_size=64)
...... 
```

**Comment by xeffyr** [comment]
LD_PRELOAD should be disabled for every script/program which call **/system/bin/dalvik** or **/system/bin/app_process**.

**Comment by fornwall** [comment]
Hm, the `dalvikvm` script wrapper in `$PREFIX/bin/dalvikvm` already does `unset LD_LIBRARY_PATH`. Why is the dynamic linker still trying to use libtermux-exec.so?

**Comment by Neo-Oli** [comment]
@fornwall I think `dalvikvm` needs to `unset` both `$LD_LIBRARY_PATH` and `$LD_PRELOAD`

**Comment by fornwall** [comment]
@Neo-Oli Ah of course, I mixed them up in my head!

An updated version `0.48` of the termux-tools package is now available, update to it with `pkg up`. After that `apksigner` and other tools using `dalvikvm` should work!

**Comment by sdrausty** [comment]
Installing `termux-exec` breaks stuff. The fist screenshot is without `termux-exec` being active. The second one is in a new session after installing. 

![screenshot_20171101-132452](https://user-images.githubusercontent.com/27742457/32287749-1a82077e-bf08-11e7-9421-0ddb61e81539.png)

![screenshot_20171101-132559](https://user-images.githubusercontent.com/27742457/32287789-4330ae3c-bf08-11e7-9482-74347e235629.png)

PRoot and termux-exec don't seem to like one another yet 👷

**Comment by Neo-Oli** [comment]
@sdrausty You need to `unset LD_PRELOAD` in your arch script as well. Like here: https://github.com/Neo-Oli/termux-ubuntu/blob/9484af655f8ba28496cade18411a173a38015e1e/ubuntu.sh#L34

**Comment by sdrausty** [comment]
@Neo-Oli thank you for your answer, time and help in improving https://sdrausty.github.io/TermuxArch/ 

You contribution was added https://github.com/sdrausty/TermuxArch/commit/71f2b4fa72a45c51d812e7598856d1ab6a2d531b ⚒
