### ISSUE TITLE
pip install numpy not working

### ISSUE THREAD

**Issue by shashank-simha** [termux/termux-packages#1737]
I tried installing numpy using the command 
 pip install numpy
but its throwing these errors
`

$ pip install numpy
Collecting numpy
  Using cached numpy-1.13.3.zip
Installing collected packages: numpy
  Running setup.py install for numpy ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-gxs3xa6q-record/install-record.txt --single-version-externally-managed --compile:
    Running from numpy source directory.

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)

    blas_opt_info:
    blas_mkl_info:
      libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    /data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    blas_info:
      libraries blas not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    /data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/system_info.py:572: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    blas_src_info:
      NOT AVAILABLE

    /data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/system_info.py:572: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    /data/data/com.termux/files/usr/bin/sh: 1: svnversion: not found
    non-existing path in 'numpy/distutils': 'site.cfg'
    /data/data/com.termux/files/usr/bin/sh: 1: svnversion: not found
    F2PY Version 2
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in /data/data/com.termux/files/usr/lib
      libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries satlas,satlas not found in /data/data/com.termux/files/usr/lib
      libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in /data/data/com.termux/files/usr/lib
      libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries f77blas,cblas,atlas not found in /data/data/com.termux/files/usr/lib
      libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    /data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    /data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    /data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.linux-armv7l-3.6
    creating build/src.linux-armv7l-3.6/numpy
    creating build/src.linux-armv7l-3.6/numpy/distutils
    building library "npymath" sources
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize IntelFCompiler
    Could not locate executable ifort
    Could not locate executable ifc
    customize LaheyFCompiler
    Could not locate executable lf95
    customize PGroupFCompiler
    Could not locate executable pgfortran
    customize AbsoftFCompiler
    Could not locate executable f90
    Could not locate executable f77
    customize NAGFCompiler
    customize VastFCompiler
    customize CompaqFCompiler
    Could not locate executable fort
    customize IntelItaniumFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize IntelEM64TFCompiler
    customize GnuFCompiler
    Could not locate executable g77
    customize G95FCompiler
    Could not locate executable g95
    customize PathScaleFCompiler
    Could not locate executable pathf95
    don't know how to compile Fortran code on platform 'posix'
    C compiler: arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -fPIC

    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/data/data/com.termux/files/usr/include/python3.6m -c'
    arm-linux-androideabi-clang: _configtest.c

    failure.
    removing: _configtest.c _configtest.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/setup.py", line 392, in <module>
        setup_package()
      File "/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/setup.py", line 384, in setup_package
        setup(**metadata)
      File "/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/command/install.py", line 62, in run
        r = self.setuptools_run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/command/install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/command/build.py", line 47, in run
        old_build.run(self)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/command/build_src.py", line 148, in run
        self.build_sources()
      File "/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/command/build_src.py", line 159, in build_sources
        self.build_library_sources(*libname_info)
      File "/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/command/build_src.py", line 294, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 674, in get_mathlib_info
        raise RuntimeError("Broken toolchain: cannot link a simple C program")
    RuntimeError: Broken toolchain: cannot link a simple C program

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-gxs3xa6q-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-3uwksmiu/numpy/
$
`
the same thing is happening with pandas, scipy and jupyter also.
please reply.
thank you.

**Comment by remo7777** [comment]
i hv installed numpy on termux successfully..
first you need to install `wheel`
`pip install wheel`
_____________________
## see my pip list
![screenshot_20171101-184007](https://user-images.githubusercontent.com/28594846/32276424-22494d28-bf35-11e7-98a4-8d369dd82bbd.jpeg)

**Comment by shashank-simha** [comment]
@remo7777 I installed wheel but the same problem is continuing with numpy.

**Comment by Grimler91** [comment]
@shashank-simha you can install numpy and scipy from its-pointless repo as @tigran123 suggested to you [in the other thread](https://github.com/termux/termux-packages/issues/136). 

`pip install numpy` is possible with some special settings while `pip install scipy` won't work since clang can't compile fortran code. You are in either case much better of by installing from its-pointless repository.

**Comment by remo7777** [comment]
`apt install clang libc++`

`pip2 install numpy==1.9.1`
scipy not working for me 😂 @shashank-simha

**Comment by shashank-simha** [comment]
@Grimler91 I activated its-pointless repo, but it provides numpy and scipy for python-2 only and not for python-3

**Comment by shashank-simha** [comment]
@remo7777 its not working for me...

**Comment by its-pointless** [comment]
Install scipy for python3-scipy
install python2-scipy for python2

**Comment by remo7777** [comment]
how to install scipy for python3 guide us
@its-pointless

**Comment by remo7777** [comment]
## thank you
@its-pointless

**Comment by remo7777** [comment]
@its-pointless 
how to install urlparse

**Comment by shashank-simha** [comment]
It seems that cblas , gfortran, f77blas and other packages to install numpy. How can I install them all?

**Comment by shashank-simha** [comment]
@its-pointless can you please give me the commands to install and activate your repository.

**Comment by its-pointless** [comment]
curl -L https://its-pointless.github.io/setup-pointless-repo.sh | sh

**Comment by shashank-simha** [comment]
Thanks you very much @its-pointless

**Comment by zeus31831** [comment]
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-ml6448t3/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-gb4soiex/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-ml6448t3/numpy/      help

**Comment by Killer83339** [comment]
Command "/data/data/com.termux/files/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-Awbt62/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-EWO17d/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-Awbt62/numpy/ You are using pip version 18.1, however version 19.2.3 is available. You should consider upgrad.
