### ISSUE TITLE
[Bug]: Unable to update on fresh install (pkg/apt)

### ISSUE THREAD

**Issue by StringManolo** [termux/termux-packages#17381]
### Unable to update/install packages (pkg/apt)

$ pkg update
```
Testing the available mirrors:
[*] https://packages-cf.termux.org/apt/termux-main: ok
[*] https://deb.kcubeterm.me/termux-main: ok
[*] https://termux.mentality.rip/termux-main: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://termux.librehat.com/apt/termux-main: ok
Picking mirror: https://grimler.se/termux-packages-24
Get:1 https://grimler.se/termux-packages-24 stable InRelease [14.0 kB]
Err:1 https://grimler.se/termux-packages-24 stable InRelease
  Unknown error executing apt-key
Reading package lists... Done
W: GPG error: https://grimler.se/termux-packages-24 stable InRelease: Unknown error executing apt-key
E: The repository 'https://grimler.se/termux-packages-24 stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.
```

I have tested all the obvious stuff, changed repos, checking that repos were accessible using curl, checking that the files under ~/../usr/etc/apt are fine, etc. 

### What steps will reproduce the bug?

It's a fresh Termux install into vphonegaga virtual machine: https://gsxnj.cn/mobile/index/

Everything else works perfectly, it's just apt/pkg, just try to update.

### What is the expected behavior?

Being able to use apt/pkg.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 4.14.42-titan #34 SMP PREEMPT Sat Nov 9 17:05:30 CST 2019 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
ART-L29
```

**Comment by 2096779623** [comment]
> Remember that VMOS and F1VM environments are NOT SUPPORTED!
These "virtual" environments are not supported by Termux. They have a number of issues including broken apt-key.

https://github.com/termux/termux-packages/issues/6726

**Comment by xtkoba** [comment]
Don't label an issue both "not-bug" and "wontfix". "wontfix" is for an issue that can technically be fixed with some political decision and enough effort. We have no way to "fix" an issue that is not a bug.

**Comment by xtkoba** [comment]
The reason I label this "invalid" is because there is no evidence that the issue is not due to bugs in the emulation environment. As mentioned in the other comment, we do not actively support such an environment. The author should have provided the evidence.

**Comment by StringManolo** [comment]
It may have an easy workable fix. But i have absolutelly no idea how the apt/pkg software works internally. So i can't tell if there is a bug with the emulation software itself (everything works pretty much fine), if it's a minor compatibillity or what it's going on. 

I also have no idea why would be the reasson why package integrity verification would not work at VMOS and F1VM. I think all other commands work perfectly fine. 

Make it work would be very handy since you can have some root packages work on a non rooted device using this software, for example to programatically send tap events using input command to send events. (Already made scripts to create accounts, open apps, etc)
