### ISSUE TITLE
[Bug]: Biber fail to build after the last update

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#17385]
### Problem description

```
$ termux-install-biber
[*] Installing cpanm...
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/data/data/com.termux/files/home/.cpan/Metadata'
  Database was generated on Wed, 05 Jul 2023 09:41:02 GMT
App::cpanminus is up to date (1.7046).
[*] Downloading and patching troublesome dependencies...
File t/01-simple.t is read-only; trying to patch anyway
patching file t/01-simple.t
--> Working on .
==> Found dependencies: Module::Build
--> Working on Module::Build
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/Module-Build-0.4234.tar.gz ... OK
Configuring Module-Build-0.4234 ... OK
Building and testing Module-Build-0.4234 ... FAIL
! Installing Module::Build failed. See /data/data/com.termux/files/home/.cpanm/work/1688555170.10497/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Module::Build' is not installed
! Bailing out the installation for ExtUtils-LibBuilder-0.08.
```

```
$ biber --help
Can't locate Log/Log4perl.pm in @INC (you may need to install the Log::Log4perl module) (@INC entries checked: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.38.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.38.0 /data/data/com.termux/files/usr/lib/perl5/5.38.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.38.0) at /data/data/com.termux/files/usr/bin/biber line %.
BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/bin/biber line %.
```

### What steps will reproduce the bug?

I have built biber last week before the last update.

Why each time you release a new biber-installer version we have to rebuild biber? We have to spent half day to do this.. and often the build does not work. Why you do not release directly the binaries? This occurs on other systems on which the users have just to download the binaries.

You would save a lot of bug reports...

### What is the expected behavior?

I have flagged the issue [here](https://github.com/termux-user-repository/tur/issues/483) but there they need [help](https://github.com/termux-user-repository/tur/issues/483#issuecomment-1623490634)

### System information

termux-info:

```
$ termux-info
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=14606
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf-g2211f76 #1 SMP PREEMPT Fri Nov 8 14:43:26 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 5 Plus
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
Not our issue. Biber has been removed from our official repo (2b9a0f555e37e4fc44c3ea5d497f14a82f16a74b).

**Comment by xtkoba** [comment]
Seems like the author had posted the same issue to the TUR community before.

If you want the Termux official community to handle this anyway, then please describe a step that does not need any third-party packages, to make sure that the issue is not due to bugs in them. Thanks.

**Comment by angelog0** [comment]
Biber has been your package up to few week ago and people which should handle this does not know how to do (have you read what I wrote?) and without Biber functional I cannot build any document I wrote with YOUR texlive. I posted the issue to the right place but they asked help to @Grimler91 which usually works here..

**Comment by xtkoba** [comment]
You opened this issue in order to ping a member of our community? That is kind of overkill and is just a spam for other members.
