### ISSUE TITLE
Package Request: wireguard-tools

### ISSUE THREAD

**Issue by zx2c4** [termux/termux-packages#1739]
The kernel module needs to be installed by the actual ROM, of course, but the tools on their own are quite useful. They require libmnl, like most modern linux networking utilities. I build this all on my computer and ship it over manually using this hilarious script:

```bash
$ cat make-me-an-android-wg-command.sh 
#!/bin/bash

set -e

ARCH="arm64"
ANDROID_PLATFORM="24"
WIREGUARD_VERSION="0.0.20171101"
LIBMNL_VERSION="1.0.4"

case "$ARCH" in
        arm) ANDROID_MACHINE="arm-linux-androideabi"; ;;
        arm64) ANDROID_MACHINE="aarch64-linux-android"; ;;
        mips) ANDROID_MACHINE="mipsel-linux-android"; ;;
        mips64) ANDROID_MACHINE="mips64el-linux-android"; ;;
        x86) ANDROID_MACHINE="x86-linux-android"; ;;
        x86_64) ANDROID_MACHINE="x86_64-linux-android"; ;;
        *) echo "Error: unknown architecture" >&2; exit 1; ;;
esac

GCC_VERSION="4.9"
ANDROID_PLATFORM="/opt/android-ndk/platforms/android-$ANDROID_PLATFORM/arch-$ARCH/usr"
ANDROID_TOOLCHAIN="/opt/android-ndk/toolchains/$ANDROID_MACHINE-$GCC_VERSION/prebuilt/linux-$(uname -m)/bin"

export PATH="$ANDROID_TOOLCHAIN:$PATH"
export CC="$ANDROID_MACHINE-gcc --sysroot $ANDROID_PLATFORM"
export LD="$ANDROID_MACHINE-ld --sysroot $ANDROID_PLATFORM"
export CFLAGS="-O3 -fomit-frame-pointer -I$ANDROID_PLATFORM/include -fPIE"
export LDFLAGS="-pie"

trap 'cd /; rm -rf "$where"' EXIT
where="$(mktemp -d)"
here="$PWD"
cd "$where"

wget "http://ftp.netfilter.org/pub/libmnl/libmnl-$LIBMNL_VERSION.tar.bz2"
wget "https://git.zx2c4.com/WireGuard/snapshot/WireGuard-$WIREGUARD_VERSION.tar.xz"

tar xjf "libmnl-$LIBMNL_VERSION.tar.bz2"
tar xJf "WireGuard-$WIREGUARD_VERSION.tar.xz"

cd "libmnl-$LIBMNL_VERSION"
./configure --enable-static --disable-shared --host="$ANDROID_MACHINE"
make -j$(nproc)

cd ..

cd "WireGuard-$WIREGUARD_VERSION/src/tools"
export CFLAGS="$CFLAGS -I../../../libmnl-$LIBMNL_VERSION/include"
export LDFLAGS="$LDFLAGS -L../../../libmnl-$LIBMNL_VERSION/src/.libs"
make -j$(nproc)
"$ANDROID_MACHINE-strip" wg
mv wg "$here/wg"

echo
echo
echo ===============================================
echo Build complete:
ls -l "$here/wg"
echo ===============================================
```

It would, of course, be much nicer to have this properly packaged inside termux, where from the packaging script it should be enough to do:

```bash
make -C src/tools
make -C src/tools install \
		DESTDIR="${pkgdir}/" \
		WITH_BASHCOMPLETION=yes \
                WITH_WGQUICK=no \
                WITH_SYSTEMDUNITS=no
```

**Comment by Grimler91** [comment]
@zx2c4 have you tried creating a build.sh script? Should be very straight forward since you've already done all the work "manually".

**Comment by zx2c4** [comment]
No, I haven't. I was hoping somebody would be enthusiastic about doing this for me, but if nobody steps of, of course I'll just do the work myself.

**Comment by Grimler91** [comment]
Does it actually work? The problem with openvpn was that it starts and everything but nothing is actually routed through the vpn (neither in termux or in the rest of android). Some (a lot?) of android programming is needed before openvpn can work in termux.

Never the less, interesting work here!

**Comment by zx2c4** [comment]
It does!

https://twitter.com/EdgeSecurity/status/900441856819027968

**Comment by sdrausty** [comment]
It looks like wireguard-tools are currently available in Termux through Arch Linux PRoot.  This script is designed to install Arch Linux in just a few keystrokes. Tapping this link https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh will transfer `setupTermuxArch.sh` to your device. Simply run `bash setupTermuxArch.sh` to install Arch Linux in Termux.  To install use `pacman -S wireguard-tools` and this will install wireguard-tools on device.  

![screenshot_20171130-003917](https://user-images.githubusercontent.com/27742457/33415806-2428cfa4-d567-11e7-94e7-6f925ac3b4dc.png)

**Comment by fornwall** [comment]
The package is now available for installation!

**Comment by sudomain** [comment]
@zx2c4 does this work on nonroot devices?

**Comment by xeffyr** [comment]
@sudomain VPN interface management works only for **rooted** devices with **custom** kernel.

**Comment by zx2c4** [comment]
There is a use case for the wg(8) utility on phones that are not rooted, actually. It's useful to be able to script key generation activities from termux, and `wg genkey` and related commands are available to anybody.
