### ISSUE TITLE
[Bug]: mangal: connection refused

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#17395]
### Problem description

2023/07/09 11:32:15 Get "https://api.mangadex.org/manga?contentRating%5B%5D=safe&contentRating%5B%5D=suggestive&limit=100&order%5BfollowedCount%5D=desc&title=big+tits": dial tcp: lookup api.mangadex.org on [::1]:53: read udp [::1]:56854->[::1]:53: read: connection refused

### What steps will reproduce the bug?

1. Install Mangal
2. Run Mangal
3. Search any manga

### System information

termux-info:

```

```

**Comment by 2096779623** [comment]
```
~ $ mangal
~ $ ls $TMPDIR/mangal
'[0001]_Chapter_1_-_A_Dog_and_a_Chainsaw.pdf'
~ $
```
Open that link in your browser to check whether mangadex is blocked in your country and region, if not, I suggest you try a few more times.
