### ISSUE TITLE
[Bug]: Jupyter notebook won't install.

### ISSUE THREAD

**Issue by orphecus** [termux/termux-packages#17405]
### Problem description

Even if pip is the most recent version, the bug appears.

`~ $ LDFLAGS=" -lm -lcompiler_rt" pip3 install jupyter
Collecting jupyter                                         Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting notebook (from jupyter)
  Using cached notebook-6.5.4-py3-none-any.whl (529 kB)
Collecting qtconsole (from jupyter)                        Using cached qtconsole-5.4.3-py3-none-any.whl (121 kB)
Collecting jupyter-console (from jupyter)
  Using cached jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Collecting nbconvert (from jupyter)
  Using cached nbconvert-7.6.0-py3-none-any.whl (290 kB)
Collecting ipykernel (from jupyter)
  Using cached ipykernel-6.24.0-py3-none-any.whl (152 kB)
Collecting ipywidgets (from jupyter)
  Using cached ipywidgets-8.0.7-py3-none-any.whl (138 kB)
Collecting comm>=0.1.1 (from ipykernel->jupyter)           Using cached comm-0.1.3-py3-none-any.whl (6.6 kB)
Collecting debugpy>=1.6.5 (from ipykernel->jupyter)
  Using cached debugpy-1.6.7-py2.py3-none-any.whl (4.9 MB)
Collecting ipython>=7.23.1 (from ipykernel->jupyter)
  Using cached ipython-8.14.0-py3-none-any.whl (798 kB)
Collecting jupyter-client>=6.1.12 (from ipykernel->jupyter)                                                         Using cached jupyter_client-8.3.0-py3-none-any.whl (103 kB)
Collecting jupyter-core!=5.0.*,>=4.12 (from ipykernel->jupyter)
  Using cached jupyter_core-5.3.1-py3-none-any.whl (93 kB)
Collecting matplotlib-inline>=0.1 (from ipykernel->jupyter)
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting nest-asyncio (from ipykernel->jupyter)
  Using cached nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
Collecting packaging (from ipykernel->jupyter)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting psutil (from ipykernel->jupyter)
  Using cached psutil-5.9.5.tar.gz (493 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyzmq>=20 (from ipykernel->jupyter)
  Using cached pyzmq-25.1.0.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tornado>=6.1 (from ipykernel->jupyter)
  Using cached tornado-6.3.2.tar.gz (508 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting traitlets>=5.4.0 (from ipykernel->jupyter)
  Using cached traitlets-5.9.0-py3-none-any.whl (117 kB)
Collecting widgetsnbextension~=4.0.7 (from ipywidgets->jupyter)
  Using cached widgetsnbextension-4.0.8-py3-none-any.whl (2.3 MB)
Collecting jupyterlab-widgets~=3.0.7 (from ipywidgets->jupyter)
  Using cached jupyterlab_widgets-3.0.8-py3-none-any.whl (214 kB)
Collecting prompt-toolkit>=3.0.30 (from jupyter-console->jupyter)
  Using cached prompt_toolkit-3.0.39-py3-none-any.whl (385 kB)
Collecting pygments (from jupyter-console->jupyter)
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting beautifulsoup4 (from nbconvert->jupyter)
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting bleach!=5.0.0 (from nbconvert->jupyter)
  Using cached bleach-6.0.0-py3-none-any.whl (162 kB)
Collecting defusedxml (from nbconvert->jupyter)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting jinja2>=3.0 (from nbconvert->jupyter)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting jupyterlab-pygments (from nbconvert->jupyter)
  Using cached jupyterlab_pygments-0.2.2-py2.py3-none-any.whl (21 kB)
Collecting markupsafe>=2.0 (from nbconvert->jupyter)
  Using cached MarkupSafe-2.1.3.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting mistune<4,>=2.0.3 (from nbconvert->jupyter)
  Using cached mistune-3.0.1-py3-none-any.whl (47 kB)
Collecting nbclient>=0.5.0 (from nbconvert->jupyter)
  Using cached nbclient-0.8.0-py3-none-any.whl (73 kB)
Collecting nbformat>=5.7 (from nbconvert->jupyter)
  Using cached nbformat-5.9.1-py3-none-any.whl (77 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
  Using cached pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting tinycss2 (from nbconvert->jupyter)
  Using cached tinycss2-1.2.1-py3-none-any.whl (21 kB)
Collecting argon2-cffi (from notebook->jupyter)
  Using cached argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting ipython-genutils (from notebook->jupyter)
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting Send2Trash>=1.8.0 (from notebook->jupyter)
  Using cached Send2Trash-1.8.2-py3-none-any.whl (18 kB)
Collecting terminado>=0.8.3 (from notebook->jupyter)
  Using cached terminado-0.17.1-py3-none-any.whl (17 kB)
Collecting prometheus-client (from notebook->jupyter)
  Using cached prometheus_client-0.17.0-py3-none-any.whl (60 kB)
Collecting nbclassic>=0.4.7 (from notebook->jupyter)
  Using cached nbclassic-1.0.0-py3-none-any.whl (10.0 MB)
Collecting qtpy>=2.0.1 (from qtconsole->jupyter)
  Using cached QtPy-2.3.1-py3-none-any.whl (84 kB)
Collecting six>=1.9.0 (from bleach!=5.0.0->nbconvert->jupyter)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting webencodings (from bleach!=5.0.0->nbconvert->jupyter)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting backcall (from ipython>=7.23.1->ipykernel->jupyter)
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting decorator (from ipython>=7.23.1->ipykernel->jupyter)
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel->jupyter)
  Using cached jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
Collecting pickleshare (from ipython>=7.23.1->ipykernel->jupyter)
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting stack-data (from ipython>=7.23.1->ipykernel->jupyter)
  Using cached stack_data-0.6.2-py3-none-any.whl (24 kB)
Collecting pexpect>4.3 (from ipython>=7.23.1->ipykernel->jupyter)
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting python-dateutil>=2.8.2 (from jupyter-client>=6.1.12->ipykernel->jupyter)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting platformdirs>=2.5 (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter)
  Using cached platformdirs-3.8.1-py3-none-any.whl (16 kB)
Collecting jupyter-server>=1.8 (from nbclassic>=0.4.7->notebook->jupyter)
  Using cached jupyter_server-2.7.0-py3-none-any.whl (375 kB)
Collecting notebook-shim>=0.2.3 (from nbclassic>=0.4.7->notebook->jupyter)
  Using cached notebook_shim-0.2.3-py3-none-any.whl (13 kB)
Collecting fastjsonschema (from nbformat>=5.7->nbconvert->jupyter)
  Using cached fastjsonschema-2.17.1-py3-none-any.whl (23 kB)
Collecting jsonschema>=2.6 (from nbformat>=5.7->nbconvert->jupyter)
  Using cached jsonschema-4.18.0-py3-none-any.whl (81 kB)
Collecting wcwidth (from prompt-toolkit>=3.0.30->jupyter-console->jupyter)
  Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting ptyprocess (from terminado>=0.8.3->notebook->jupyter)
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting argon2-cffi-bindings (from argon2-cffi->notebook->jupyter)
  Using cached argon2-cffi-bindings-21.2.0.tar.gz (1.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting soupsieve>1.2 (from beautifulsoup4->nbconvert->jupyter)
  Using cached soupsieve-2.4.1-py3-none-any.whl (36 kB)
Collecting parso<0.9.0,>=0.8.0 (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter)
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat>=5.7->nbconvert->jupyter)
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat>=5.7->nbconvert->jupyter)
  Using cached jsonschema_specifications-2023.6.1-py3-none-any.whl (17 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat>=5.7->nbconvert->jupyter)
  Using cached referencing-0.29.1-py3-none-any.whl (25 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=2.6->nbformat>=5.7->nbconvert->jupyter)
  Using cached rpds_py-0.8.10.tar.gz (16 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Collecting maturin<2.0,>=1.0
        Using cached maturin-1.1.0.tar.gz (181 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: maturin
        Building wheel for maturin (pyproject.toml): started
        Building wheel for maturin (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for maturin (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [33 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-aarch64-cpython-311
            creating build/lib.linux-aarch64-cpython-311/maturin
            copying maturin/__init__.py -> build/lib.linux-aarch64-cpython-311/maturin
            copying maturin/__main__.py -> build/lib.linux-aarch64-cpython-311/maturin
            copying maturin/import_hook.py -> build/lib.linux-aarch64-cpython-311/maturin
            running egg_info
            creating maturin.egg-info
            writing maturin.egg-info/PKG-INFO
            writing dependency_links to maturin.egg-info/dependency_links.txt
            writing requirements to maturin.egg-info/requires.txt
            writing top-level names to maturin.egg-info/top_level.txt
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest template 'MANIFEST.in'
            warning: no files found matching '*.json' under directory 'src/python_interpreter'
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            running build_ext
            running build_rust
            error: can't find Rust compiler

            If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

            To update pip, run:

                pip install --upgrade pip

            and then retry package installation.

            If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for maturin
      Failed to build maturin
      ERROR: Could not build wheels for maturin, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

### What steps will reproduce the bug?

apt update
apt upgrade
pkg install python
pip install --upgrade pip
apt install clang python  fftw libzmq freetype libpng pkg-config
LDFLAGS=" -lm -lcompiler_/rt" pip install jupyter
or
 LDFLAGS=" -lm -lcompiler_rt" pip3 install jupyter

### System information

termux-info:

```

```
Termux Variables:                                        TERMUX_APK_RELEASE=GITHUB                                TERMUX_APP_PACKAGE_MANAGER=apt                           TERMUX_APP_PID=14425                                     TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64                                                  Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main                                                   Updatable packages:
All packages up to date
termux-tools version:
1.38.3                                                   Android version:
13
Kernel build information:
Linux localhost 5.4.210-qgki-25884040-abT733XXU4CWE7 #1 SMP PREEMPT Wed May 24 14:31:03 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T733                                                  LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by 2096779623** [comment]
```bash
plg i libzmq -y
LDFLAGS=" -lm -lcompiler_rt" pip3 install jupyter "prompt-toolkit == 3.0.38"
```

**Comment by xtkoba** [comment]
@2096779623 Wrong answer. You don't understand what is the point. Please reopen. Thanks.

**Comment by xtkoba** [comment]
Off topic but where does `-lcompiler_rt` come from? I recommend the following if you need to explicitly link in compiler builtins:

```bash
LDFLAGS+=" $(clang -print-libgcc-file-name)"
```

**Comment by orphecus** [comment]
> 주제에서 벗어나지만 어디 `-lcompiler_rt`에서 왔습니까? 컴파일러 내장에서 명시적으로 연결해야 하는 경우 다음을 권장합니다.
> 
> ```shell
> LDFLAGS+=" $(clang -print-libgcc-file-name)"
> ```

I tried all the commands you told me, but the jupyter installation command didn't run.

I didn't understand what -lcompiler meant.

**Comment by orphecus** [comment]
> 주제에서 벗어나지만 어디 `-lcompiler_rt`에서 왔습니까? 컴파일러 내장에서 명시적으로 연결해야 하는 경우 다음을 권장합니다.
> 
> ```shell
> LDFLAGS+=" $(clang -print-libgcc-file-name)"
> ```

In fact, the same error occurred when I installed jupyter with pip install jupyter, pip3 .

**Comment by 2096779623** [comment]
> Can anyone in this community wipe @2096779623's ass?

@xtkoba We can email instead of whining here.

**Comment by truboxl** [comment]
On a fresh install:
```
pkg upgrade
pkg install binutils libzmq python rust
pip install jupyter
```
