### ISSUE TITLE
[Package]:obabel

### ISSUE THREAD

**Issue by HusniMuhammad** [termux/termux-packages#17412]
### Why is it worth to add this package?

Open Babel is a chemical toolbox designed to support the many languages of chemical data. It’s an open, collaborative project allowing anyone to search, convert, analyze, or store data from molecular modeling, chemistry, solid-state materials, biochemistry, or related areas.

### Home page URL

https://openbabel.org

### Source code URL

http://sourceforge.net/projects/openbabel/files/openbabel/2.3.1/openbabel-2.3.1.tar.gz/download

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

Help needed

**Comment by Grimler91** [comment]
What is wrong with the [openbabel package we already have](https://github.com/termux/termux-packages/blob/master/packages/openbabel/build.sh)?

**Comment by HusniMuhammad** [comment]
I don't know it's already Available or  not.
Thanks for your quick reply... :)

**Comment by HusniMuhammad** [comment]
> What is wrong with the [openbabel package we already have](https://github.com/termux/termux-packages/blob/master/packages/openbabel/build.sh)?

How to install?
