### ISSUE TITLE
[Bug]: SDL1.2 doesn't support pkg config

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-packages#17417]
### Problem description

I may be wrong on the details, but in general here is the description.

Part of the application at configure checks if there are packages installed. It looks like pkg-config uses the *.pc files located in /data/data/com.termux/files/usr/lib/pkgconfig to do this.

However, there is no proper file for SDL1.2, so that when trying to sport the game "zaz" on TUR, configure does not detect the existence of the SDL1.2 package and throws an error.

I wrote my own version of this file based on the Debian package, but I don't know if it is correct. I'm just posting as a "curiosity".

I think solving this problem will solve some of the problems with building applications that use SDL1.2

```
prefix=/data/data/com.termux/files/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: sdl
Description: Simple DirectMedia Layer is a cross-platform multimedia library designed to provide low level access to audio, keyboard, mouse, joystick, 3D hardware via OpenGL, and 2D video framebuffer.
Version: 1.2.15
Requires:
Conflicts:
Libs: -L${libdir} -lSDL
Libs.private: -lSDL -lpthread -lm -ldl -lasound -lm -ldl -lpthread -lpulse-simple -pthread -lpulse -pthread -lX11 -lXext -lcaca -lpthread
Cflags: -I${includedir}/SDL -D_GNU_SOURCE=1 -D_REENTRANT
```

### What steps will reproduce the bug?

Try to compile zaz
http://sourceforge.net/projects/zaz/files/zaz-1.0.0.tar.bz2/download

It will return that SDL not found. But if you add my file as "/data/data/com.termux/files/usr/lib/pkgconfig/sdl.pc" it will move on

### System information

It's from docker build script

**Comment by truboxl** [comment]
You should modify the source to use sdl12_compat.pc from sdl package

**Comment by IntinteDAO** [comment]
Oh, ok. Thanks :P
(Temporary?) closing
