### ISSUE TITLE
[Package]: qdl (Qualcomm flashing tool)

### ISSUE THREAD

**Issue by RohitVerma882** [termux/termux-packages#17420]
### Why is it worth to add this package?

Qualcomm MSM based devices contain a special mode of operation, called Emergency Download Mode (EDL). In this mode, the device identifies itself as Qualcomm HS-USB 9008 through USB, and can communicate with a PC host. 

### Home page URL

https://www.96boards.org/documentation/consumer/guides/qdl.md.html

### Source code URL

https://git.codelinaro.org/linaro/qcomlt/qdl

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by RohitVerma882** [comment]
Any process?

**Comment by RohitVerma882** [comment]
.

**Comment by Benjie35** [comment]
How to BL vivo y19 using termux command root access

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last commit was 3 years ago so I consider this project is dead/frozen.
