### ISSUE TITLE
[Bug]: Tigervnc cannot startup

### ISSUE THREAD

**Issue by qiangz63** [termux/termux-packages#17443]
### Problem description

Tue Jul 18 14:10:51 2023
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
Sync Extension 3.1
lost connection to rendering server on 8 read -1 22
(EE)
Fatal server error:
(EE) Caught signal 6 (Aborted). Server aborting
(EE)
[1]    14210 abort      Xvnc :1

### What steps will reproduce the bug?

Xvnc :1

**Comment by twaik** [comment]
You are starting Xvnc with GALLIUM_DRIVER=virpipe but not starting virgl_test_server...
