### ISSUE TITLE
Imagemagick resize error

### ISSUE THREAD

**Issue by Emil-7** [termux/termux-packages#1744]
Imagemagick does not resize correctly. For example,

`convert rose: -resize 300% rose.png`

creates random artifacts, different at every run. This only happens on my Galaxy S5, not my S2 with Lineage OS. "-blur" is also affected:

`convert rose: -blur 0x8 rose.png`

I have reinstalled the app and factory reset the phone, but the error still persists.

Not sure if this is related to https://github.com/termux/termux-packages/issues/1314

Possible workaround:
`convert rose: -scale 300% rose.png`

**Comment by Grimler91** [comment]
Both devices are arm, so it's interesting that the behaviour differs. 
We're all packages up to date when you tested on both devices?

**Comment by Emil-7** [comment]
Yes, all packages were updated before testing. I tested both devices a few months ago simultaneously and now only the S5. I can repeat the S2 test if necessary.

**Comment by Emil-7** [comment]
Different than stated above, the S2 is not error free. Now I did some tests on my Galaxy S5 with stock Android and on my Galaxy S2 with Lineage OS, both with Termux 0.54 and all packages up to date. The following table shows the results (ok, a=artifacts, s=Segmentation fault and no output) for device / resize factor / output format:
S5 500% png : s
S2 500% png : a
S5 300% jpg : a
S2 300% jpg : ok
S5 300% png : a
S2 300% png : a
S5 300% gif : a
S2 300% gif : s
S5 150% png : a
S2 150% png : ok
S5 120% png : ok
S2 120% png : ok

**Comment by Grimler91** [comment]
@Emil-7 If you run the same command several times, does it generate the same erroneous output everytime or does it only happen sometimes (as in https://github.com/termux/termux-packages/issues/1314)?

**Comment by Emil-7** [comment]
The category correct output / artifacts / segfault is mostly stable. In the case of artifacts, the random distortions and black lines across the image are different for every run.

**Comment by cherryleafroad** [comment]
Related to #2214

**Comment by fornwall** [comment]
I'm closing this issue in favour of #2214.
