### ISSUE TITLE
error run awesome wm

### ISSUE THREAD

**Issue by Dendi777** [termux/termux-packages#17454]
I've been trying to run awesome wm for the whole day, I fixed a bunch of problems with dbus, but it seems that the problem is simply not working for termux awesome [2023-07-19 21:06:31 W: awesome: a_dbus_connect:618: Could not connect to D-Bus system bus: Failed to connect to socket /data/data/com.termux/files/usr/var/run/dbus/system_bus_socket: Connection refused
2023-07-19 21:06:31 E: awesome: signal_fatal:497: signal 11, dumping backtrace
Cannot get backtrace symbols.] by the way, I'm trying to run it using termux-x11 I haven't tried tigervnc because it's slow (but maybe it would have worked) but while awesome does not want to connect to termux-x11

**Comment by licy183** [comment]
Close in favour of #17461.
