### ISSUE TITLE
rustc fails when running on Chromebook.

### ISSUE THREAD

**Issue by adambuchbinder** [termux/termux-packages#1745]
I'm running Play Store apps on a Chromebook, including Termux. Because [rustup doesn't work](https://stackoverflow.com/a/46130238) here, I'm [using the its-pointless packages](https://wiki.termux.com/wiki/Package_Management#its-pointless_.28live_the_dream.29).

I set up the repo:

    pkg install curl
    curl -L https://its-pointless.github.io/setup-pointless-repo.sh | sh
    pkg install rustc cargo

Running `cargo init --bin hello` fails due to `$USER` being unset. That's solved with `export USER=$(id -un)`, but now I get `CANNOT LINK EXECUTABLE "rustc": library "libLLVM-4.0.so" not found`. *That*'s solved by running:

    pkg install libllvm-4so

At this point, `cargo run` builds and runs on my phone, but following these steps on my Chromebook, I get `Could not create LLVM TargetMachine for triple: i686-linux-android: Unable to find target for this triple (no targets are registered)`.

clang compiles and runs a test C program without complaint, and `uname -a` says I'm an i686 Android device. Is this a problem in Termux, in the `rustc` package, or what?

**Comment by its-pointless** [comment]
Its my package at fault.

**Comment by adambuchbinder** [comment]
Ah, thank you for figuring that out. Is there any more information I can provide, or anything I can help with?

**Comment by its-pointless** [comment]
No not really. This is on my todo list that i may get back to.

**Comment by adambuchbinder** [comment]
I see. I was hoping to be able to do some coding on a flight tomorrow. (Long story.) Can you point me to anything I can poke at?

**Comment by its-pointless** [comment]
i am compiling it now

**Comment by its-pointless** [comment]
compile failed sorry

**Comment by adambuchbinder** [comment]
No worries; I'll make do. Thanks for trying!

**Comment by its-pointless** [comment]
should work now ... sorry for being late

**Comment by Alfriadox** [comment]
This is broken again I think...

**Comment by Alfriadox** [comment]
This is the error I am getting.
```
$ cargo help
error: no default toolchain configured
```
(I am on a Lenovo chromebook 500e, so there is android store support, and the target triple should be i686-linux-android)
I tried to fix it using rustup (to install rust stable 1.25.0) and got this error.
```
$ rustup install stable
info: syncing channel updates for 'stable-i686-linux-android'
info: latest update on 2018-03-29, rust version 1.25.0 (84203cac6 2018-03-25)
error: target not found: 'i686-linux-android'
```

**Comment by Alfriadox** [comment]
@its-pointless Do you know what's causing this?

**Comment by its-pointless** [comment]
Rustup doesn't work in android. 
You are second person having this issue. I will try to fix it. Note though that it works for some people but not others this makes it hard for me to bugfix since i can't isolate the issue and the number of places where it could break is large. I am no rust expert at all. 
i will try though.

**Comment by dead10ck** [comment]
I'm experiencing this issue myself. After installing the `rust` package, any cargo commands just say

```
error: no override and no default toolchain set
```

**Comment by dead10ck** [comment]
Never mind; it turned out the issue was that I tried installing rustup from the bash script, which failed, before installing the rust termux package, and the bash script put a bunch of executables in my `$CARGO_HOME/bin`, which was on my path.

**Comment by stonecharioteer** [comment]
@dead10ck thanks for posting this. I had the same problem just now!
