### ISSUE TITLE
GLib developer tools not found

### ISSUE THREAD

**Issue by gergelypolonkai** [termux/termux-packages#1747]
The Automake macro `GOBJECT_INTROSPECTION_CHECK` and the `glib-mkenums` script can not be found. `glib-genmarshal` and `glib-compile-schemas` are provided by the `glib-bin` package as expected.

**Comment by Grimler91** [comment]
Try installing the development package glib-dev

**Comment by gergelypolonkai** [comment]
All 3 GLib packages are installed, hence the bug report.

**Comment by gergelypolonkai** [comment]
With the latest update, `glib-mkenums` is available; introspection is still missing though.

**Comment by xeffyr** [comment]
Closing as introspection actually separate package (https://gitlab.gnome.org/GNOME/gobject-introspection) which still not available for Termux and tracked in https://github.com/termux/x11-packages/issues/81.
