### ISSUE TITLE
[Bug]: I was trying to install kali linux for android. I have successfully installed it but when i was trying to set a password by giving command "nethunter kex passwd" it is showing that there is no such command. It is written above that to set password for the kex server enter that command. And same is happening with the "nethunter kex &" command. Please help me. If i am doing something wrong then please help me and if this is a bug then please fix it.

### ISSUE THREAD

**Issue by Enderman3** [termux/termux-packages#17475]
### Problem description

I was trying to install kali linux for android. I have successfully installed it but when i was trying to set a password by giving command "nethunter kex passwd" it is showing that there is no such command. It is written above that to set password for the kex server enter that command. And same is happening with the "nethunter kex &" command. Please help me. If i am doing something wrong then please help me and if this is a bug then please fix it.

### What steps will reproduce the bug?

I don't know

### What is the expected behavior?

It should let me to set a password and then say to confirm the password again
Next when starting the kex server it should show me the port of the server

### System information

termux-info:

```

```

**Comment by twaik** [comment]
https://wiki.termux.com/wiki/Hacking
