### ISSUE TITLE
I am having a problem.

### ISSUE THREAD

**Issue by sami2161** [termux/termux-packages#17483]
When I try to download a package or update it, it throws this error:
'Release file for https://termux.mentality.rip/termux-main/dists/stable/InRelease is not valid yet (invalid for another 1h 56min 23s). Updates for this repository will not be applied.'
What should I do?

**Comment by romanovj** [comment]
you have to set the correct local time

**Comment by 2096779623** [comment]
As above, make sure your phone is set to the correct time and date.
