### ISSUE TITLE
debs directory is root on new docker installation, 

### ISSUE THREAD

**Issue by cswl** [termux/termux-packages#1748]
I did a fresh clone and ran scripts in README and built libandroid-support.

Then I got this error.
`ar: /home/builder/termux-packages/debs/libandroid-support-dev_22_aarch64.deb: Permission denied`

Upon `ls -al` debs directory was owned by root. And the deb files were there which were owned by root.

I removed the debs directory via `sudo` . so the package could be built.

But perhaps the default docker install has those files owned by root.

**Comment by fornwall** [comment]
Did you run docker using `./scripts/run-docker.sh` as a non-root user?

**Comment by cswl** [comment]
Yes.. I am in docker group.. 
All other files in the home directory were from builder...
Expect the debs directory

**Comment by xeffyr** [comment]
In my container the permissions on **debs** directory seems to be fine:
```
drwxr-xr-x 1 builder builder  1888 Nov 12 20:13 debs/
```

**Comment by cswl** [comment]
I guess it was just some errror on mine side.

Closing
