### ISSUE TITLE
[Bug]: Users help for virglrenderer-android

### ISSUE THREAD

**Issue by xDoge26** [termux/termux-packages#17488]
### Problem description

It would be nice to have `--help` option or man page  for virglrenderer-android 

### What steps will reproduce the bug?

```
pkg install x11-repo
pkg install virglrenderer-android
```

### System information

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=6568
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
12
Kernel build information:
Linux localhost 4.19.157-perf-g836e7cd4cf74 #1 SMP PREEMPT Mon Apr 17 22:24:35 CST 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
2201117TG
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by zavocc** [comment]
Manpage for `virgl_test_server` itself is present in online Debian manpage https://manpages.debian.org/testing/virgl-server/virgl_test_server.29 but the `virgl_test_server_android` script yeah it doesn't have help argument yet

**Comment by licy183** [comment]
Adding the help of `virglrenderer` doesn't make sense, because on Android many options like `--use-glx` doesn't work anymore.
I'll add usage of `--angle-gl`, `--angle-vulkan` and `--angle-vulkan-null`.
