### ISSUE TITLE
[Bug]: i have a problem as when i write command pkg install root-repo i always face this error:  Ability to run this command as root has been disabled permanently for safety purposes. can u help me deal with this?  

### ISSUE THREAD

**Issue by mr-issoalolo** [termux/termux-packages#17481]
### Problem description

[Bug]: i have a problem as when i write command pkg install root-repo i always face this error:  Ability to run this command as root has been disabled permanently for safety purposes. can u help me deal with this?  

### What steps will reproduce the bug?

[Bug]: i have a problem as when i write command pkg install root-repo i always face this error:  Ability to run this command as root has been disabled permanently for safety purposes. can u help me deal with this?  

### System information

termux-info:

```

```

**Comment by romanovj** [comment]
you shoudn't run pkg/apt commands with root rights

**Comment by 2096779623** [comment]
As mentioned above, do not run pkg/apt/pacman with root privileges.
