### ISSUE TITLE
mc: "shell link" in left/right panel menu leads to Segfault

### ISSUE THREAD

**Issue by gwpl** [termux/termux-packages#175]
Application: `mc`

Occurrence: every time

To reproduce:
* F9
* Select "Left" or "Right" menu
* Shell Link
* Try to connect with some ssh host, e.g. user@192.168.1.16

Returns:
+ Stopped
Segfault

Expected:
Ability to browse, copy to/from remote destination.

**Comment by fornwall** [comment]
Thanks for reporting!

This [was a bug in mc 4.8.16](http://www.midnight-commander.org/ticket/3611) and has now been patched in the updated `4.8.16-4` version of the mc package in Termux, which can be installed with `apt update && apt upgrade`.

**Comment by gwpl** [comment]
Thank you! Now works beautifully ! :)
