### ISSUE TITLE
How to by login during git clone in termux 

### ISSUE THREAD

**Issue by robinsaraswat0** [termux/termux-packages#1751]
Whenever i tried to clone any script in my termux. It asks for username and password, i provide proper username and password but it said fatal:authentication failed
Plzz help me..

**Comment by xeffyr** [comment]
With which command you are trying to clone ?
Command should be like:
```
git clone https://github.com/termux/termux-packages
```

**Comment by robinsaraswat0** [comment]
Git  clone and then location of script frm of github

**Comment by robinsaraswat0** [comment]
But i m doing when my location is in sdcard it simply installed

**Comment by robinsaraswat0** [comment]
Sey cloned

**Comment by xeffyr** [comment]
You are trying to clone only part of repository (script) ? If so, then you are doing the git clone wrong - only whole repository can be cloned.

**Comment by sdrausty** [comment]
Don't clone to the sdcard. See https://wiki.termux.com/wiki/Internal_and_external_storage for an explanation.

**Comment by Syedaanis** [comment]
I'm also facing same problem

**Comment by xeffyr** [comment]
> I'm also facing same problem

I'm able to clone repos over git://, https:// and ssh to /sdcard without any problems (even on official Android 8). So, I guess that there is some problem with your ROM and not with git program.

**Comment by Syedaanis** [comment]
When I am providing Username and password, it says repository not found

**Comment by xeffyr** [comment]
@Syedaanis You do something wrong. Post command that you typed if you want help.

**Comment by Syedaanis** [comment]
git clone https://github.com/TechnicalMujeeb/tmvenom

**Comment by xeffyr** [comment]
![screenshot_20180523-220517_termux](https://user-images.githubusercontent.com/25881154/40445796-d843da5e-5ed5-11e8-9d3b-030a656a5076.jpg)

I have successfully cloned repo with your command. I don't have prompted for entering user/password for accessing repo.

As I said above, possible that you have something wrong with your ROM.

**Comment by Syedaanis** [comment]
So what can I do for that?

**Comment by Syedaanis** [comment]
[
![screenshot_20180524-133921](https://user-images.githubusercontent.com/39441287/40472885-540a26c0-5f58-11e8-9848-1b448e311108.jpg)
](url)

**Comment by Grimler91** [comment]
@Syedaanis you haven't spelled tmvenom correctly..

**Comment by Syedaanis** [comment]
No its correct, whenever I click enter last alphabet goes dissappear.

**Comment by sdrausty** [comment]
http://www.bing.com/search?q=ls%C2%A0pwd%C2%A0beginner%C2%A0site%3Atldp.org

**Comment by neFAST** [comment]
So how did you fixed it? I have the same issue in a fresh termyx install on my nexus5

**Comment by tomty89** [comment]
Just noticed that the keyboard was SwiftKey, which my phone also preloads and I can reproduce the problem with it. No problem with the Xperia Chinese keyboard.

**Comment by neFAST** [comment]
I Use Google keyboard and get` fatal: Authentication failed for 'https://ne....`.

**Comment by tomty89** [comment]
Is it a private repo? (where authentication is expected?)

It's probably hard to tell if it's the same problem (i.e. Enter becomes Backspace + Enter) when it's a password field. Try a few other keyboard apps maybe. If it still doesn't work you may consider opening another issue.

So far I have no problem doing `git push`, so I don't feel like it's a git problem.

**Comment by neFAST** [comment]
Correct, this is a private repo. I tried a different keyboard app without success.

**Comment by neFAST** [comment]
I tried to put login/pass in the url `git clone https://user:name@server.com/git/repo` and I still get authentication failed. The same command on my PC works fine

**Comment by leomzy** [comment]
How will I save my github

**Comment by Sudeepanddavid** [comment]
Same here

**Comment by charslan** [comment]
Same problem for this command
git clone https://github.com/LOoLzeC/DarkSploit

**Comment by dipayand** [comment]
This generally happens when you copy paste something. The last character gets truncated

**Comment by minkimac** [comment]
I was facing same issue with Swift keyboard but then after switching to Aosp keyboard, it didn't ask for any credentials and cloned the repo.

**Comment by henrywilliem** [comment]
Same with me git clone http://github 
 Ask for username and password  why

**Comment by maxx123321** [comment]
I have this issue: git clone username for 'https //github.com'. Please help me solve this.

**Comment by xeffyr** [comment]
* Check if URL is correct. It's common problem when you copy-pasting URLs on touch screen. Also, do not try to type whole URL by hand without understanding what its parts mean, URLs are very sensitive for typos and missing parts.

* Check if repository exist. There no guarantee that URL you got somewhere on the Internet is not outdated. *Internet is not permanent.*

* Check if you have access right to repository.
