### ISSUE TITLE
Zig missing libxml2.so 

### ISSUE THREAD

**Issue by codedsprit** [termux/termux-packages#17541]
Hi,
I'm trying to run and compile zig and it's `CANNOT find libxml2.so`. I viewed other issues related to this but can't get the solution. 

Here is the output when I run `zig`

```bash
~ $ zig
CANNOT LINK EXECUTABLE "zig": cannot find "libxml2.so" from verneed[0] in DT_NEEDED list for "/data/data/com.termux/files/usr/bin/zig"
~ $
```

**Comment by licy183** [comment]
`zig` has been disabled in commit e3c7fe93282b897805af46d797b0994951e13fa7. Upstream hasn't bumped a new version for llvm 16 yet.

**Comment by qiangz63** [comment]
@licy183 The lastest zig version up to v0.11.0 already download form official site, and run fine!!

**Comment by joshcangit** [comment]
Using Zig 0.11.0 works but there's this warning.
```
warning: Encountered error: FileNotFound, falling back to default ABI and dynamic linker.
```

Maybe building it from source could deal with that.
But no matter what, I can't build Zig in Termux.
