### ISSUE TITLE
[Package]: opencv with GUI support 

### ISSUE THREAD

**Issue by Coderx7** [termux/termux-packages#17542]
### Why is it worth to add this package?

Hey everyone. 
I'd like to suggest a package addition to the termux. but before that I'd also like to thank all of you for your time and effort in making all of this a reality. thank you all very much. 

now here's my suggestion if you don't mind: 

I noticed termux only offers a headless version of opencv that has no gui support for obvious reason. 

However I also found out there's termux-x11. now knowing that termux also offers supports GUI, it'd be a great idea imho, to also have the GUI version. it allows for complete support of opencv and lots and lots of computer vision related tasks. this allows you to work on the same codebase on the go right from your cell phone. this is not the case with the current headless version. 

I'd like to also ask for the contrib version which has a wealth of algorithms compared to the normal version. 

What do you think? 

### Source code URL

https://opencv.org/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

Apparently this is doable without much of a hassle and works flawlessly as well ( see ref [here](https://www.reddit.com/r/termux/comments/15drlwt/how_do_you_build_an_opencv_package_supporting/ju7qvf4/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button)  )

**Comment by Biswa96** [comment]
Could you provide any tests for those GUI mode and contrib algorithm?

**Comment by Coderx7** [comment]
@Biswa96
do you mean a simple example using some of those GUI functionalities and algorithms? because I'm not sure how Im supposed to write a test for a GUI component! I may be able to do what you want if you could kindly explain a bit more what it is that you like to have.

**Comment by Biswa96** [comment]
I was asking for any minimal procedure to test if opencv contrib and GUI functions are working properly.

**Comment by Coderx7** [comment]
@Biswa96 Is this what you are looking for? 

```python
import unittest
# for creating key press for waitKey
from unittest.mock import patch
import numpy as np
import cv2

class TestOpenCVGUI(unittest.TestCase):
    
    def test_imshow(self):
        # Create a simple black image
        image = 255 * np.ones((100, 100, 3), dtype=np.uint8)
        # Display the image in a window
        cv2.imshow('Test Window', image)
        # Check if the window was created
        self.assertEqual(cv2.getWindowProperty('Test Window', cv2.WND_PROP_VISIBLE), 1)
        # Close the window
        cv2.destroyAllWindows()

    # we use mock to simulate a key press so the test can go on
    # without any user interaction
    @patch('cv2.waitKey', return_value=ord('q'))
    def test_waitKey(self, mock_waitKey):
        # Call the cv2.waitKey() 
        key = cv2.waitKey(0)
        # Check if the key returned is the same as the mock
        self.assertEqual(key, ord('q'))

    def test_namedWindow(self):
        # Create a named window
        cv2.namedWindow('TestWindow')
        # Check if the window was created
        self.assertEqual(cv2.getWindowProperty('TestWindow', cv2.WND_PROP_VISIBLE), 1)
        # Optionally, set window properties (e.g., resizable)
        cv2.setWindowProperty('TestWindow', cv2.WND_PROP_AUTOSIZE, cv2.WINDOW_NORMAL)
        # Destroy the window
        cv2.destroyWindow('TestWindow')

    def test_sift_keypoints(self):
        # Draw a simple image to use with sift
        image = np.ones((200, 200), dtype=np.uint8)
        cv2.rectangle(image, (15, 30), (35, 40), 0, -1)
        cv2.rectangle(image, (20, 35), (50, 60), 255, -1)
        cv2.rectangle(image, (150, 35), (180, 60), 255, -1)
        cv2.rectangle(image, (50, 70), (150, 150), 255, -1)
        cv2.rectangle(image, (20, 160), (180, 190), 255, 2)
        # for versions>4.4 for lower versions we use cv2.xfeatures2d.SIFT_create )
        sift = cv2.SIFT_create()
        # Detect keypoints
        keypoints = sift.detect(image, None)
        # Check if keypoints are detected (there should be 36 keypoints!)
        self.assertTrue(len(keypoints) == 36)

if __name__ == '__main__':
    unittest.main()
```
This doesnt require any user interactions, and should complete successfully if the GUI components are working properly. in a headless version these obviously fail!

**Comment by Biswa96** [comment]
Thank you. Does it require the contrib algorithms also as you've mentioned that in original post?

**Comment by Coderx7** [comment]
@Biswa96 only the last test which is 
```python
    def test_sift_keypoints(self):
        # Create a checkerboard pattern
        image = np.kron([[1, 0] * 4, [0, 1] * 4] * 4, np.ones((50, 50))).astype(np.uint8) * 255
        # for versions>4.4 for lower versions we use cv2.xfeatures2d.SIFT_create )
        sift = cv2.SIFT_create()
        # Detect keypoints
        keypoints = sift.detect(image, None)
        # Check if keypoints are detected (there should be 330 keypoints!)
        self.assertTrue(len(keypoints) == 330)
```
uses `SIFT_create()` which exists in the contrib. the previous ones exist in the normal cv2 package. 
(note I just removed the few lines of code for the image generation with one here to simplify things further!)

**Comment by Coderx7** [comment]
@Biswa96 I added `daisy_descriptor` test for the contrib package as the previous test was moved from contrib to the main package.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/8666646408

All the above tests passed in my phone.

**Comment by Coderx7** [comment]
I installed it and ran couple of scripts perfectly, so I guess opencv wise it's working well.however the scripts that had matplotlib in them gave me this error: 
```
~/opencv-projects $ python basic_opencv_1_\(roi_splitting_merging_basics\).py
pixel values in a color image at (100,100): [197 122   0]
the blue channel pixel value at (100,100): 197
setting values at (100,100) to all white: [255 255 255]
item at (10,10,2): 1
item value at (10,10,2) after being set: 100
img shape: (1200, 1920, 3)
img pixel count: 6912000
img datatype: uint8
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/data/data/com.termux/files/usr/tmp/runtime-u0_a259'
Traceback (most recent call last):
  File "/storage/emulated/0/Documents/Opencv/OpenCVProjects/basic_opencv_1_(roi_splitting_merging_basics).py", line 116, in <module>
    plt.subplot(231),plt.imshow(img1,'gray'),plt.title('ORIGINAL')
    ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/pyplot.py", line 1437, in subplot
    fig = gcf()
          ^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/pyplot.py", line 1000, in gcf
    return figure()
           ^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/pyplot.py", line 934, in figure
    manager = new_figure_manager(
              ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/pyplot.py", line 464, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/pyplot.py", line 441, in _warn_if_gui_out_of_main_thread
    canvas_class = cast(type[FigureCanvasBase], _get_backend_mod().FigureCanvas)
                                                ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/pyplot.py", line 280, in _get_backend_mod
    switch_backend(rcParams._get("backend"))  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/pyplot.py", line 327, in switch_backend
    switch_backend(candidate)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/pyplot.py", line 342, in switch_backend
    module = importlib.import_module(cbook._backend_module_name(newbackend))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/backends/backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, QtCore, QtGui
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/backends/qt_compat.py", line 128, in <module>
    _setup()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/matplotlib/backends/qt_compat.py", line 90, in _setup_pyqt5plus
    from PyQt5 import QtCore, QtGui, QtWidgets
RuntimeError: the sip module implements API v12.0 to v12.12 but the PyQt5.QtCore module requires API v12.13
~/opencv-projects $
```
how should this be taken care of? seems like a conflict between my existing libs with the one bundled with this package am I right?

**Comment by Biswa96** [comment]
> seems like a conflict between my existing libs with the one bundled with this package am I right?

yeah, it looks like from pyqt-sip mismatch issue and not related to opencv. Did you install matplotlib and pyqt using pkg/apt ?

**Comment by Coderx7** [comment]
Yes if I remember correctly I installed them using pkg/apt

**Comment by Biswa96** [comment]
Could you create a separate issue for that pyqt issue? Also, provide the steps and minimal sample code to reproduce the issue. I hope the tests can be run with less memory ~in a potato~.

**Comment by Coderx7** [comment]
@Biswa96
I created the issue as you asked. 
concerning 

> I hope the tests can be run with less memory in a potato.
The tests that I provided should not be in anyway memory intensive, are you seeing something weird?
