### ISSUE TITLE
pkg search sudo

### ISSUE THREAD

**Issue by DrMasmm** [termux/termux-packages#17553]
### Why is it worth to add this package?

![Screenshot_20230804-024654_Termux](https://github.com/termux/termux-packages/assets/141459685/b01ba267-0a5b-4c97-876d-1927b43c3c1f)

### Home page URL

https://github.com/termux/termux-packages/assets/141459685/e95e5da5-3c06-4760-901c-83afca6406df

### Source code URL

https://github.com/termux/termux-packages/assets/141459685/e95e5da5-3c06-4760-901c-83afca6406df

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

┌──(root㉿localhost)-[~]
└─# sudo apt update
Ign:1 http://http.kali.org/kali kali-rolling InRelease
Ign:1 http://http.kali.org/kali kali-rolling InRelease
Ign:1 http://http.kali.org/kali kali-rolling InRelease
Err:1 http://http.kali.org/kali kali-rolling InRelease
  Temporary failure resolving 'http.kali.org'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease  Temporary failure resolving 'http.kali.org'
W: Some index files failed to download. They have been ignored, or old ones used instead. 

This is my problem .
![Screenshot_20230804-024654_Termux](https://github.com/termux/termux-packages/assets/141459685/e95e5da5-3c06-4760-901c-83afca6406df)

**Comment by twaik** [comment]
It is already available in the package `tsu`.

**Comment by twaik** [comment]
About kali: https://wiki.termux.com/wiki/Hacking
