### ISSUE TITLE
package request: distcc

### ISSUE THREAD

**Issue by shawnl** [termux/termux-packages#1755]
I compiled it on termux (which took a small patch https://github.com/distcc/distcc/pull/238 )

compile with

sh ./configure --without-libiberty --disable-Werror`

can only compile native unlless https://github.com/termux/termux-packages/pull/1218 is merged

download with ./configure already present: https://code.google.com/archive/p/distcc/downloads

**Comment by shawnl** [comment]
build with ./configure --without-libiberty

**Comment by xeffyr** [comment]
Package is now available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install distcc
```
