### ISSUE TITLE
[Package]: cutefish-session

### ISSUE THREAD

**Issue by djmanri3** [termux/termux-packages#17557]
### Why is it worth to add this package?

I would like for this package to be available in the Termux repositories, as it is a beautiful desktop environment. Additionally, I have been testing it on proot-based distributions and it works fantastic.

It is based on KDE, but the best part is that it is lighter.

### Home page URL

https://cutefish-ubuntu.github.io/

### Source code URL

https://github.com/cutefishos/core

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

Nothing more to object.

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/pull/13527

**Comment by djmanri3** [comment]
CuteFish development has been reactivated recently, they have released version 0.8 for debian 12
