### ISSUE TITLE
[Bug]: tkinter not working 

### ISSUE THREAD

**Issue by Tanzin01** [termux/termux-packages#17550]
### Problem description

did set up vnc and installed via pkg. However getting thr following missing ee
error

### What steps will reproduce the bug?

any simple tk example on android 13 results in error

### System information

termux-info:

```
python3 lab2.py https://browser.engineering/http.html
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/book/src/lab2.py", line 10, in <module>
    import tkinter
  File "/data/data/com.termux/files/usr/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ImportError: dlopen failed: library "libexpat.so.1" not found: needed by /data/data/com.termux/files/usr/lib/libfontconfig.so in namespace (default)
```

**Comment by romanovj** [comment]
pkg ins libexpat

**Comment by 2096779623** [comment]
```bash
~ $ python
Python 3.11.4 (main, Jul  2 2023, 11:17:00) [Clang 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> 
```
I can't reproduce it on my device.

**Comment by licy183** [comment]
Please share your `termux-info` output. It seems that you've done partial upgrading. SOVERSION suffix is enabled in commit 6404c523aadfd3118d2e23ba5d2f8f73cc5183db to solve symbol conflict issue with system provided libexpat, and it seems that your libexpat is not up to date. Termux is a rolling distribution, you should never do partial software upgrades.

**Comment by Tanzin01** [comment]
Here is the output

~ $ termux-info
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=22552
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
apt/stable 2.7.3 aarch64 [upgradable from: 2.7.1-1]
command-not-found/stable 2.2.0-10 aarch64 [upgradable from: 2.2.0-4]
curl/stable 8.2.1 aarch64 [upgradable from: 8.1.2]
debianutils/stable 5.8 aarch64 [upgradable from: 5.7-1]
gpgv/stable 2.4.3 aarch64 [upgradable from: 2.4.2]
libassuan/stable 2.5.6 aarch64 [upgradable from: 2.5.5]
libcurl/stable 8.2.1 aarch64 [upgradable from: 8.1.2]
libexpat/stable 2.5.0-1 aarch64 [upgradable from: 2.5.0]
liblzma/stable 5.4.4 aarch64 [upgradable from: 5.4.3]
libnghttp2/stable 1.55.1 aarch64 [upgradable from: 1.54.0]
libsmartcols/stable 2.39.1 aarch64 [upgradable from: 2.39]
libtalloc/stable 2.4.1 aarch64 [upgradable from: 2.4.0]
libunbound/stable 1.17.1-2 aarch64 [upgradable from: 1.17.1-1]
libuuid/stable 2.39.1 aarch64 [upgradable from: 2.39]
ncurses-ui-libs/stable 6.4.20230527 aarch64 [upgradable from: 6.4-2]
ncurses/stable 6.4.20230527 aarch64 [upgradable from: 6.4-2]
openssl/stable 1:3.1.2 aarch64 [upgradable from: 1:3.1.1]
python-pip/stable 23.2.1 all [upgradable from: 23.1.2]
tar/stable 1.35 aarch64 [upgradable from: 1.34-2]
unbound/stable 1.17.1-2 aarch64 [upgradable from: 1.17.1-1]
util-linux/stable 2.39.1 aarch64 [upgradable from: 2.39]
xxhash/stable 0.8.2 aarch64 [upgradable from: 0.8.1]
xz-utils/stable 5.4.4 aarch64 [upgradable from: 5.4.3]
zstd/stable 1.5.5-1 aarch64 [upgradable from: 1.5.5]
termux-tools version:
1.38.3
Android version:
13
Kernel build information:
Linux localhost 5.10.107-android13-4-25931408 #2 SMP PREEMPT Thu Jun 8 18:51:51 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A145F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
~ $

**Comment by licy183** [comment]
Please run `pkg up` to update all the packages.

**Comment by Tanzin01** [comment]
Oky

**Comment by Tanzin01** [comment]
Thanks, now its working.
