### ISSUE TITLE
[Package]: Inquire about improving virglrenderer performance

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#17579]
### Why is it worth to add this package?

GPU acceleration with in Termux-x11 via **virglrenderer-android**

You don't seem to get even about 10% performance of the host GPU native due to the overhead.

`GALLIUM_DRIVER=virpipe` When run the game with 
**- performance is slow**
**- 3d modeling is broken**
**- Character animation is not output**
**- The background effect is not displayed**

I have the same issues as above.
(ex :  SuperTuxKart)

OpenGL version 2.1 is the limit, so there are program compatibility issues. 
(ex :  blender, kdenlive)

In the mid- to long-term, not short-term 
Is there room for improved virpipe performance and compatibility?

p.s
When combined with an **angle-android**, it seems that there is a bigger compatibility problem.

### Source code URL

https://gitlab.freedesktop.org/virgl/virglrenderer

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
Pull requests are always welcome.

**Comment by hansm629** [comment]
> Pull requests are always welcome.

I am very interested in the various improvements you have reported to Mesa GitLab :)

Is there room for improved virpipe performance and compatibility?

**Comment by IntinteDAO** [comment]
> > Pull requests are always welcome.
> 
> I am very interested in the various improvements you have reported to Mesa GitLab :)
> 
> Is there room for improved virpipe performance and compatibility?

As I understand - yes, but need more devs.
But I hope Zink are now popular and it can be faster than virpipe and also it supports (but badly for me??) OpenGL4.6

But I think virglrenderer is too slow for some unknown reason. I try to investigate about it, but nothing. Ofc. it's much slower on Xfce4 than on i3 / openbox (based on glmark2 benchmark)

**Comment by hansm629** [comment]
> > > Pull requests are always welcome.
> > 
> > 
> > I am very interested in the various improvements you have reported to Mesa GitLab :)
> > Is there room for improved virpipe performance and compatibility?
> 
> As I understand - yes, but need more devs. But I hope Zink are now popular and it can be faster than virpipe and also it supports (but badly for me??) OpenGL4.6
> 
> But I think virglrenderer is too slow for some unknown reason. I try to investigate about it, but nothing. Ofc. it's much slower on Xfce4 than on i3 / openbox (based on glmark2 benchmark)

When using zink From the PRoot-Distro

Can I guarantee compatibility for **Mali, PowerVR, Xclipse(mRDAN2)** not Adreno GPU?


It's interesting that the virgl performance is slower on xfce4.

I remember that KDE is less usable because of its slow gui performance.

**Comment by twaik** [comment]
> Is there room for improved virpipe performance and compatibility?

No.

> I am very interested in the various improvements you have reported to Mesa GitLab :)

These are only suggestions.

**Comment by hansm629** [comment]
> > Is there room for improved virpipe performance and compatibility?
> 
> No.
> 
> > I am very interested in the various improvements you have reported to Mesa GitLab :)
> 
> These are only suggestions.

I'm not a developer
I don't have much knowledge about graphics.

Do you think zink could be a GPU acceleration solution to replace virpipe?

As far as I know, PRoot-Distro is
Other mobile GPUs are not guaranteed to use zink unless it is a **freedreno turnip**.


Still
I'm confused about the best GPU acceleration solution in PRoot-Distro. T_T

would have been best if the Android Vulkan driver supported WSI
It's a shame.

**Comment by IntinteDAO** [comment]
> > > Do you think zink could be a GPU acceleration solution to replace virpipe?
> > 
> > 
> > You can use Zink already in Termux. IMHO the Zink is too buggy to use it, but maybe it's releated with Android Vulkan. There are some other features that can by used as an alternative for OpenGL, but I think we don't have too many devs to implement it fast.
> > One year ago you don't even have virgl android, now you can use Zink and Virgl. The future is now :P
> 
> Currently using zink+turnip in PRoot-Distro Ubuntu. Can a mali GPU (e.g. Exynos2100) use zink on a PRoot-Distro?

Not sure. You can try to run Zink on Termux directly and confirm / reject before you try to do it on proot distro. In the future it can be possible thanks to Venus and Zink. But for now I'm not so sure, because you have freedreno support (only?)

First check if vulkan works good on your Termux

**Comment by hansm629** [comment]
> > > > Do you think zink could be a GPU acceleration solution to replace virpipe?
> > > 
> > > 
> > > You can use Zink already in Termux. IMHO the Zink is too buggy to use it, but maybe it's releated with Android Vulkan. There are some other features that can by used as an alternative for OpenGL, but I think we don't have too many devs to implement it fast.
> > > One year ago you don't even have virgl android, now you can use Zink and Virgl. The future is now :P
> > 
> > 
> > Currently using zink+turnip in PRoot-Distro Ubuntu. Can a mali GPU (e.g. Exynos2100) use zink on a PRoot-Distro?
> 
> Not sure. You can try to run Zink on Termux directly and confirm / reject before you try to do it on proot distro. In the future it can be possible thanks to Venus and Zink. But for now I'm not so sure, because you have freedreno support (only?)
> 
> First check if vulkan works good on your Termux

Yes...
My Galaxy S21 Ultra (Exynos2100 : Mali-G78MP14) is

After installing `mesa-zink` from the `tur-repo` on the `Termux`
In combination with `vulkan-loader-android`

The zink is working.

Is there a way to use this in the `proot-distro` as it is?

**Comment by IntinteDAO** [comment]
@hansm629 Well, I don't know. You can use Zink and Virglrenderer together. Zink will render graphics, virglrenderer will send it to your proot-distro. But vulkan-loader-android can be only handled (I think?) by Mesa 22.0.5.

https://ivonblog.com/en-us/posts/termux-virglrenderer/#42-in-chroot

**Comment by twaik** [comment]
Closing this because it is an upstream issue.
