### ISSUE TITLE
[Package]: Emacs 29.1

### ISSUE THREAD

**Issue by cabins** [termux/termux-packages#17581]
### Why is it worth to add this package?

Emacs 29.1 is out, but the version in the repo is 28.3-rc1, which is out. Pls update to the latest version. Thanks!

### Source code URL

https://ftp.gnu.org/gnu/emacs/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by licy183** [comment]
Resolved via https://github.com/termux/termux-packages/commit/2b912e3ed62aeda06146b9e1cc84c348e5657dac.
