### ISSUE TITLE
Package request: GNU Stow

### ISSUE THREAD

**Issue by mcchrish** [termux/termux-packages#176]
Useful for some that uses GNU Stow for dotfiles.

**Comment by fornwall** [comment]
Thanks, I've added this to [the package suggestion page](https://termux.com/package-suggestions.html).

**Comment by Neo-Oli** [comment]
Hi, I am re-opening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by rqcy** [comment]
I would like to use Stow for my config files too.

**Comment by jottr** [comment]
Any updates on this? Anything we can do to help?

**Comment by Neo-Oli** [comment]
@jottr there are quite a few package requests open at the moment, so it might take some time. If you're able to, you could try to package it yourself and submit it as a pull request.

**Comment by jottr** [comment]
@Neo-Oli will check it out. Just started reading the on-topic doc.

**Comment by jottr** [comment]
@Neo-Oli you can find my PR here: https://github.com/termux/termux-packages/pull/374

**Comment by fornwall** [comment]
PR merged and package has been added, closing this issue.
