### ISSUE TITLE
[Bug]: files not accesble by Nodejs in Termux shortcuts 

### ISSUE THREAD

**Issue by HusniMuhammad** [termux/termux-packages#17611]
### files not accesble by **Termux widget** using **Nodejs** package **javascript-obfuscator**

 ![Screenshot_20230812-224521](https://github.com/termux/termux-packages/assets/104101867/a602604c-c48f-4e54-9c37-f89d7f523331)

This `h.sh` file contains this following _code/command_

`javascript-obfuscator ~/example/body.js --output ~/output/body.js`

Note: 
- Directly running with this command (Not using **Termux widget**)  `javascript-obfuscator ~/example/body.js --output ~/output/body.js` _working fine_

- other packages like **ffmpeg** working fine  With **Termux widget**

- Directly running with this command (Not using **Termux widget**) this command
`bash .shortcuts/h.sh` _working fine_

### What steps will reproduce the bug?

opening a **sh** file using **Termux widget**

`com.termux.documents/home/.shortcuts/h.sh`

This `h.sh` file contains this following _code/command_

`javascript-obfuscator ~/example/body.js --output ~/output/body.js`

### What is the expected behavior?

![Screenshot_20230812-224600](https://github.com/termux/termux-packages/assets/104101867/ff52c2df-6916-445b-a5cb-60f69ea62347)

**Like this** 

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=30302
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.5
Android version:
11
Kernel build information:
Linux localhost 4.14.193+-ab441 #1 SMP PREEMPT Sat Jun 17 10:52:36 CST 2023 armv8l Android
Device manufacturer:
realme
Device model:
RMX3231
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.widget versionCode:13


```

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-widget#termux-environment

https://github.com/javascript-obfuscator/javascript-obfuscator/blob/c7d4f9cf26859ac3071bd11179516753883eda10/bin/javascript-obfuscator#L1

**Comment by HusniMuhammad** [comment]
I will try again Thanks

**Comment by HusniMuhammad** [comment]
**Not working**

![Screenshot_20230812-235802](https://github.com/termux/termux-packages/assets/104101867/a1447f45-3efa-494d-99ed-f83717b874f4)

**Comment by agnostic-apollo** [comment]
What did you do?

**Comment by HusniMuhammad** [comment]
![Uploading Screenshot_20230813-000154.png…]()

**Comment by HusniMuhammad** [comment]
![Screenshot_20230813-000154](https://github.com/termux/termux-packages/assets/104101867/071d7fcf-f515-4bd9-b6e5-37f56819fd80)

**Comment by agnostic-apollo** [comment]
No idea what you changed based on the picture. The `javascript-obfuscator` script needs to have the #!/data/data/com.termux/files/usr/bin/env node` shebang as the link posted mentioned. Or use `tudo` to run it.

**Comment by HusniMuhammad** [comment]
I added wrong shebang. I will try again. Thanks for your reply

**Comment by HusniMuhammad** [comment]
![Screenshot_20230813-001110](https://github.com/termux/termux-packages/assets/104101867/d201f264-d439-49b4-a2be-2111d7292ae7)

Working but with error😤

**Comment by agnostic-apollo** [comment]
Your `h.sh` script should be using `#!/data/data/com.termux/files/usr/bin/bash` as shebang since you are trying to run shell commands.

**Comment by HusniMuhammad** [comment]
![Screenshot_20230813-040559](https://github.com/termux/termux-packages/assets/104101867/502c8c0b-7f91-4d79-ada4-f6e7c5066520)

**Comment by agnostic-apollo** [comment]
https://unix.stackexchange.com/questions/721844/linux-bash-shell-script-error-cannot-execute-required-file-not-found

**Comment by HusniMuhammad** [comment]
**FFMPEG** working fine with the **Termux widget**
i.e **recognizing files in Termux widget** 

Not working with `javascript-obfuscator ~/example/body.js --output ~/output/body.js`


Here the code ffmpeg example `h.sh` file

```
#!/data/data/com.termux/files/usr/bin/bash

ffmpeg -i /storage/emulated/0/download/videoplayback.mp4 -c:a copy -c:v libx264 -vf ass=/storage/emulated/0/download/subtitle.ass /storage/emulated/0/download/output.mp4

```

**Comment by HusniMuhammad** [comment]
Also without the shebangs working fine 

`ffmpeg -i /storage/emulated/0/download/videoplayback.mp4 -c:a copy -c:v libx264 -vf ass=/storage/emulated/0/download/subtitle.ass /storage/emulated/0/download/output.mp4
`

**Comment by 2096779623** [comment]
Try changing `~` to `$HOME` .

**Comment by agnostic-apollo** [comment]
Fix your `javascript-obfuscator` with `dos2unix` and post its content in case still using some other wrong shebang.

**Comment by HusniMuhammad** [comment]
> 

Working :)

**Comment by HusniMuhammad** [comment]
> `termux-fix-shebang $PREFIX/bin/javascript-obfuscator`

Working big thanks

**Comment by HusniMuhammad** [comment]
![Screenshot_20230813-045458](https://github.com/termux/termux-packages/assets/104101867/d0c18e9e-886c-42b1-bdc3-92a07ab0ded0)

**Big thanks to all the participants**

Now I can run my `mywebsite_sync.sh` in **Android launcher**

**Comment by HusniMuhammad** [comment]
> Fix your `javascript-obfuscator` with `dos2unix` and post its content in case still using some other wrong shebang. Also set your text editor to use `LF` instead of `CRLF` for newlines.

Thanks 👍
![Screenshot_20230813-050246](https://github.com/termux/termux-packages/assets/104101867/7c4683c1-1725-41a6-afb2-2f7370660ac7)


Note:LF Text visible for   preview purpuses only

![Screenshot_20230813-050612](https://github.com/termux/termux-packages/assets/104101867/e2204524-5bdf-4535-8ab3-2da7982f43d3)
