### ISSUE TITLE
无法通过RealVNC连接Termux。  Unable to connect local RealVNC to Termux 

### ISSUE THREAD

**Issue by grade2** [termux/termux-packages#17642]
下图为通过TMOE提供的startvnc脚本于Termux端启动VNC的历程。

![S30815-11582235_com termux](https://github.com/termux/termux-packages/assets/78834791/2fc2727a-e053-4bdb-877a-3d32fa74ac64)

在此之后,我使用预先设定的端口"localhost:5902"来连接VNC,但最终我得到了“The port on which the computer is listening for a connection could not be contacted.”报错。
本人能力有限,目前尚未在网络中发现有类似错误的解决方法。请各位大神指点一二。

本人设备:魅族20                     Meizu 20
安卓版本:13                             Android 13
设备是否root：否                   No root
容器类型:proot                        container type is proot
安装发行版版本：debian12  OS:debian12
服务端VNC：TigerVNC          Tiger VNC server

**Comment by twaik** [comment]
Official language of all Termux repos is English.
