### ISSUE TITLE
[Package]: rtorrent xmlrpc

### ISSUE THREAD

**Issue by hon4** [termux/termux-packages#17648]
### Why is it worth to add this package?

rTorrent is a hard to use client and the rest of the users uses remote connection to control it such as ruTorrent frontend. This connection requires XMLRPC connection that is not supported.

### Source code URL

https://github.com/termux/termux-packages/issues/5206

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

I have tried to enable it but I receive this message.

`rtorrent: XMLRPC not supported.`

**Comment by 2096779623** [comment]
Duplate of https://github.com/termux/termux-packages/issues/15616 .
