### ISSUE TITLE
pycares: error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#17656]
### Problem description

~ $ pip install aioping
Collecting aioping
  Obtaining dependency information for aioping from https://files.pythonhosted.org/packages/93/26/afc25b1d88ded3e707960e7b2bae653add126cbf11ae3402d17ca5b79ee4/aioping-0.4.0-py3-none-any.whl.metadata
  Using cached aioping-0.4.0-py3-none-any.whl.metadata (923 bytes)
Collecting async-timeout (from aioping)
  Obtaining dependency information for async-timeout from https://files.pythonhosted.org/packages/a7/fa/e01228c2938de91d47b307831c62ab9e4001e747789d0b05baf779a6488c/async_timeout-4.0.3-py3-none-any.whl.metadata
  Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting aiodns (from aioping)
  Using cached aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Collecting pycares>=4.0.0 (from aiodns->aioping)
  Using cached pycares-4.3.0.tar.gz (821 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi>=1.5.0 (from pycares>=4.0.0->aiodns->aioping)
  Using cached cffi-1.15.1-cp311-cp311-linux_aarch64.whl
Collecting pycparser (from cffi>=1.5.0->pycares>=4.0.0->aiodns->aioping)
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Using cached aioping-0.4.0-py3-none-any.whl (12 kB)
Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Building wheels for collected packages: pycares
  Building wheel for pycares (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pycares (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/pycares
      copying src/pycares/__init__.py -> build/lib.linux-aarch64-cpython-311/pycares
      copying src/pycares/__main__.py -> build/lib.linux-aarch64-cpython-311/pycares
      copying src/pycares/_version.py -> build/lib.linux-aarch64-cpython-311/pycares
      copying src/pycares/errno.py -> build/lib.linux-aarch64-cpython-311/pycares
      copying src/pycares/utils.py -> build/lib.linux-aarch64-cpython-311/pycares
      running build_ext
      generating cffi module 'build/temp.linux-aarch64-cpython-311/_cares.c'
      creating build/temp.linux-aarch64-cpython-311
      building '_cares' extension
      creating build/temp.linux-aarch64-cpython-311/build
      creating build/temp.linux-aarch64-cpython-311/build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/deps
      creating build/temp.linux-aarch64-cpython-311/deps/c-ares
      creating build/temp.linux-aarch64-cpython-311/deps/c-ares/src
      creating build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c build/temp.linux-aarch64-cpython-311/_cares.c -o build/temp.linux-aarch64-cpython-311/build/temp.linux-aarch64-cpython-311/_cares.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares__addrinfo2hostent.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares__addrinfo2hostent.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares__addrinfo_localhost.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares__addrinfo_localhost.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares__close_sockets.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares__close_sockets.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares__get_hostent.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares__get_hostent.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares__parse_into_addrinfo.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares__parse_into_addrinfo.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares__read_line.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares__read_line.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares__readaddrinfo.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares__readaddrinfo.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares__sortaddrinfo.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares__sortaddrinfo.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares__timeval.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares__timeval.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_android.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_android.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_cancel.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_cancel.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_create_query.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_create_query.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_data.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_data.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_destroy.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_destroy.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_expand_name.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_expand_name.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_expand_string.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_expand_string.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_fds.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_fds.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_free_hostent.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_free_hostent.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_free_string.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_free_string.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_freeaddrinfo.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_freeaddrinfo.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_getaddrinfo.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_getaddrinfo.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_getenv.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_getenv.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_gethostbyaddr.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_gethostbyaddr.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_gethostbyname.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_gethostbyname.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_getnameinfo.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_getnameinfo.o
      deps/c-ares/src/lib/ares_getnameinfo.c:300:15: error: call to undeclared function 'getservbyport_r'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                if (getservbyport_r(port, proto, &se, (void *)tmpbuf,
                    ^
      deps/c-ares/src/lib/ares_getnameinfo.c:300:15: note: did you mean 'getservbyport'?
      /data/data/com.termux/files/usr/include/netdb.h:262:17: note: 'getservbyport' declared here
      struct servent* getservbyport(int __port_in_network_order, const char* __proto);
                      ^
      1 error generated.
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycares
Failed to build pycares
ERROR: Could not build wheels for pycares, which is required to install pyproject.toml-based projects

### What steps will reproduce the bug?

pip install aioping
pip install pycares
pip install pyproject.toml
pip install numpy
#and other libraries

### System information

termux-info:

```
Termux Variables:
unsupported
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.pku.edu.cn/termux/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.pku.edu.cn/termux/termux-root/ root stable
Updatable packages:
All packages up to date
termux-tools version:
1.38.5
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Sat Jul 24 15:17:21 WIB 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

```

**Comment by EvgeniySnezhkov** [comment]
pkg install clang

**Comment by truboxl** [comment]
https://github.com/saghul/pycares/issues?q=is%3Aissue+android+is%3Aclosed

Really need to report to upstream... Will take a look in detail...

**Comment by romanovj** [comment]
```
wget https://files.pythonhosted.org/packages/01/50/e3015e6e03a3cf64113f509e8b86b71af37169b59ccedfcb182f3d031329/pycares-4.3.0.tar.gz

tar -xf pycares-4.3.0.tar.gz

sed -i s/'#define HAVE_GETSERVBYPORT_R 1'//g ./pycares-4.3.0/deps/build-config/config_android/ares_config.h

pip install ./pycares-4.3.0
```

**Comment by truboxl** [comment]
Fixed in pycares master branch. Should be no more issue for pycares version newer than 4.4.0.
