### ISSUE TITLE
texlive "bus error" running xelatex

### ISSUE THREAD

**Issue by smallcreek** [termux/termux-packages#1765]
I would like to use xelatex which needs lm fonts.  After installing them, running xelatex results in a bus error.

Here's the steps to reproduce my problem, including a minimal working example of a tex file that produces the error.

```
$ # Get rid of old texmf tree just to make sure
$ apt-get purge texlive
[...]
$ apt-get --purge autoremove
[...]
$ # Reinstall from scratch; I want to use xelatex which needs lm fonts
$ # (I really need some more packages not included in the texlive termux
$ # package, but here I'm trying to reduce it to the minimal example
$ # that still errors out.)
$ apt-get install texlive
[...]
$ source /data/data/com.termux/files/usr/etc/profile.d/texlive.sh
$ tlmgr install lm
[...]
$ cat <<EOF >mwe.tex
> \documentclass[a4paper]{article}
>
> \begin{document}
> Test
> \end{document}
> EOF
$ xelatex mwe
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Termux) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./mwe.tex
LaTeX2e <2017-04-15>
Babel <3.10> and hyphenation patterns for 5 language(s) loaded.

(/data/data/com.termux/files/usr/opt/texlive/2017/texmf-dist/tex/latex/base/art
icle.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class

(/data/data/com.termux/files/usr/opt/texlive/2017/texmf-dist/tex/latex/base/siz
e10.clo))
No file mwe.aux.
[1
xdvipdfmx:fatal: File ended prematurely


Output file removed.
Bus error
$ # mwe.aux and mwe.log are created empty.
```

This particular file does not require any xelatex features and compiles flawlessly with latex.

Is there anything I'm doing wrong? Some Termux peculiarity I'm missing? And how would I go about debugging this further?

**Comment by Grimler91** [comment]
Hi, thanks for the detailed bug report 👍 

Which arch are you on (`uname -a`)? I can't seem to reproduce it on aarch64.

**Comment by smallcreek** [comment]
Thanks for your quick reply!

This is an armv7l device, a Samsung n5100 running Lineage Android 7.1.2.

**Comment by Grimler91** [comment]
I get the same error on arm. gdb gives some interesting output (`gdb --args xelatex mwe.tex` followed by run). 

I've tried building a debug version of texlive-bin before but it fails if xetex is included (probably due to order of flags if I remember correctly). I probably need to get that running before a deeper investigation is possible.

**Comment by Grimler91** [comment]
The error disappeared when running a debug build of xelatex, so it is probably possible to get rid of it by changing the level of optimization. I'll experiment with that and come up with a fix.
