### ISSUE TITLE
[Bug]: Pidgin / Finch - no protocols detected

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-packages#17668]
### Problem description

Pidgin and Finch are multicommunicators, so it can handle multiple protocols for communicate with other people - like Gadu Gadu, XMPP, IRC etc. You don't need to have (usually) different software to handle this.

But sadly in Termux, Finch and Pidgin doesn't have any protocols. 

According to build log

```
pidgin 2.14.12

Build GTK+ 2.x UI............. : yes
Build console UI.............. : yes
Build for X11................. : yes

Enable Gestures............... : yes
Protocols to build dynamically : gg irc jabber novell simple zephyr
Protocols to link statically.. :

```

Some protocols should work.

![obraz](https://github.com/termux/termux-packages/assets/56807194/bfaaaaed-6c4b-4db5-9d21-bada0b5b9f99)

No protocols are on pidgin (except Discord, but it doesn't work and it's 3rd party). I try to investigate how to fix it, but I've never found anything

### What steps will reproduce the bug?

1) Install Pidgin / Finch
2) Try to add new account
3) No protocols on the list

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=16477
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX_X11_DEBUG=1
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://ro.mirror.flokinet.net/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://ro.mirror.flokinet.net/termux/termux-root root stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://ro.mirror.flokinet.net/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.38.5
Android version:
12
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Fri Oct 28 08:27:23 CDT 2022 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(100)
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:14

```

**Comment by IntinteDAO** [comment]
Log from Pidgin:
fervi@Shinzan:~$ cat logs-pidgin.txt 
(22:01:59) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file : Failed to open file “”: No such file or directory
(22:02:01) g_log: purple_find_prpl: assertion 'id != NULL' failed
(22:02:11) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/musicmessaging.so
(22:02:11) plugins: /data/data/com.termux/files/usr/lib/pidgin/musicmessaging.so is not loadable: dlopen failed: cannot locate symbol "purple_conversation_get_im_data" referenced by "/data/data/com.termux/files/usr/lib/pidgin/musicmessaging.so"...
(22:02:11) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/sendbutton.so
(22:02:11) plugins: /data/data/com.termux/files/usr/lib/pidgin/sendbutton.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/pidgin/sendbutton.so"...
(22:02:11) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/themeedit.so
(22:02:11) plugins: /data/data/com.termux/files/usr/lib/pidgin/themeedit.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/pidgin/themeedit.so"...
(22:02:11) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/extplacement.so
(22:02:11) plugins: /data/data/com.termux/files/usr/lib/pidgin/extplacement.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/pidgin/extplacement.so"...
(22:02:11) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/markerline.so
(22:02:11) plugins: /data/data/com.termux/files/usr/lib/pidgin/markerline.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/pidgin/markerline.so"...
(22:02:11) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/convcolors.so
(22:02:11) plugins: /data/data/com.termux/files/usr/lib/pidgin/convcolors.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/pidgin/convcolors.so"...
(22:02:11) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/pidginrc.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/pidginrc.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/pidgin/pidginrc.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/timestamp_format.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/timestamp_format.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/pidgin/timestamp_format.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/timestamp.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/timestamp.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/pidgin/timestamp.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/relnot.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/relnot.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/pidgin/relnot.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/iconaway.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/iconaway.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/pidgin/iconaway.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/notify.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/notify.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/pidgin/notify.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/gestures.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/gestures.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/pidgin/gestures.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/gtkbuddynote.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/gtkbuddynote.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/pidgin/gtkbuddynote.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/transparency.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/transparency.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/pidgin/transparency.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/xmppdisco.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/xmppdisco.so is not loadable: dlopen failed: cannot locate symbol "purple_debug_misc" referenced by "/data/data/com.termux/files/usr/lib/pidgin/xmppdisco.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/ticker.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/ticker.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/pidgin/ticker.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/spellchk.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/spellchk.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/pidgin/spellchk.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/xmppconsole.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/xmppconsole.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/pidgin/xmppconsole.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/pidgin/history.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/pidgin/history.so is not loadable: dlopen failed: cannot locate symbol "purple_log_compare" referenced by "/data/data/com.termux/files/usr/lib/pidgin/history.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/newline.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/newline.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/purple-2/newline.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/libzephyr.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/libzephyr.so is not loadable: dlopen failed: cannot locate symbol "purple_strequal" referenced by "/data/data/com.termux/files/usr/lib/purple-2/libzephyr.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/dbus-example.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/dbus-example.so is not loadable: dlopen failed: cannot locate symbol "PURPLE_DBUS_TYPE_PurpleBuddy" referenced by "/data/data/com.termux/files/usr/lib/purple-2/dbus-example.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/offlinemsg.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/offlinemsg.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/purple-2/offlinemsg.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/autoaccept.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/autoaccept.so is not loadable: dlopen failed: cannot locate symbol "purple_user_dir" referenced by "/data/data/com.termux/files/usr/lib/purple-2/autoaccept.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/ssl.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/ssl.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/purple-2/ssl.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/libxmpp.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/libxmpp.so is not loadable: dlopen failed: library "libjabber.so" not found: needed by /data/data/com.termux/files/usr/lib/purple-2/libxmpp.so in namespace (default)
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/ssl-gnutls.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/ssl-gnutls.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/purple-2/ssl-gnutls.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/libnovell.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/libnovell.so is not loadable: dlopen failed: cannot locate symbol "purple_utf8_strcasecmp" referenced by "/data/data/com.termux/files/usr/lib/purple-2/libnovell.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/statenotify.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/statenotify.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/purple-2/statenotify.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/log_reader.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/log_reader.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/purple-2/log_reader.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/buddynote.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/buddynote.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/purple-2/buddynote.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/libgg.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/libgg.so is not loadable: dlopen failed: cannot locate symbol "deflateInit_" referenced by "/data/data/com.termux/files/usr/lib/purple-2/libgg.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/psychic.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/psychic.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/purple-2/psychic.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/tcl.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/tcl.so is not loadable: dlopen failed: library "libtk8.6.so" not found: needed by /data/data/com.termux/files/usr/lib/purple-2/tcl.so in namespace (default)
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/libsimple.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/libsimple.so is not loadable: dlopen failed: cannot locate symbol "purple_account_user_split_new" referenced by "/data/data/com.termux/files/usr/lib/purple-2/libsimple.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/libjabber.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/libjabber.so is not loadable: dlopen failed: cannot locate symbol "xmlnode_free" referenced by "/data/data/com.termux/files/usr/lib/purple-2/libjabber.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/joinpart.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/joinpart.so is not loadable: dlopen failed: cannot locate symbol "purple_prefs_add_none" referenced by "/data/data/com.termux/files/usr/lib/purple-2/joinpart.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/idle.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/idle.so is not loadable: dlopen failed: cannot locate symbol "purple_plugin_register" referenced by "/data/data/com.termux/files/usr/lib/purple-2/idle.so"...
(22:02:12) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/libirc.so
(22:02:12) plugins: /data/data/com.termux/files/usr/lib/purple-2/libirc.so is not loadable: dlopen failed: cannot locate symbol "purple_marshal_VOID__POINTER_POINTER" referenced by "/data/data/com.termux/files/usr/lib/purple-2/libirc.so"...

**Comment by truboxl** [comment]
Thanks. That narrows down the problem a lot. Likely a build issue.

**Comment by IntinteDAO** [comment]
@truboxl Ok, but I'm curious why this is happening. However, on pure Linux there are no such problems, is it some kind of problem with building libraries in Bionic or how to understand it?

**Comment by Almoshaks964** [comment]
I want Kali Linux commands
