### ISSUE TITLE
texlive error: can't find some font files?

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-packages#1767]
Hello, 

i'm trying to compile this tex file:
```
\documentclass[a4paper,12pt]{article}
\usepackage{listings}
\usepackage{graphicx}
\usepackage{color}
\usepackage[T1]{fontenc}
\definecolor{lightgray}{rgb}{0.9,0.9,0.9}
\lstset{
language = Octave,
basicstyle =\footnotesize,
numbers = left,
numberstyle = \footnotesize,
backgroundcolor=\color{lightgray},
frame=single,
tabsize=2,
breaklines=true}
\begin{document}
\section*{Source code: \texttt{C2IN0032C-201702.m}}
%\lstinputlisting{C2IN1032C-201702.m}
\section*{Execution results}
\lstset{
language = Octave,
basicstyle =\footnotesize,
numbers = none,
backgroundcolor=\color{white},
frame=none,
tabsize=2,
breaklines=true}
\begin{lstlisting}
octave>C2IN0032C-201702
input: [1 6 0]

L =

   7.07107  -0.98995   0.00000
   0.00000   2.00499   1.99502
   0.00000   0.00000   0.14107

x =

    43.000
   307.000
  -307.000

Se excedió el numero de iteraciones sin converger

xs =

   0.36315
   3.66928
  -3.66928

es =  649.30
ea =  649.30
ep =  98.828
C =  6113.2
\end{lstlisting}
\begin{center}
\end{center}
\end{document}
```
But i got several errors:
```
can't find file: 'ecbx1000'
can't find file: 'ecttt1728'
etc
```
googleing, it seems that there are fonts missing.  The solution seem to be, on other linux distros, to install:
```
texlive-latex-recommended
texlive-latex-extra
texlive-fonts-recommended
```
which are not available for termux.
Is there an alternative so i can compile this tex?

**Comment by Grimler91** [comment]
Hi, you can install them with texlive's package manager tlmgr. 
To find which package provides a specific file you can search with: ˋtlmgr search --global --file NAMEˋ. 
See https://wiki.termux.com/wiki/Texlive for more tips and information.

**Comment by Grimler91** [comment]
Hi, you can install them with texlive's package manager tlmgr. 
To find which package provides a specific file you can search with: ˋtlmgr search --global --file NAMEˋ. 
See https://wiki.termux.com/wiki/Texlive for more tips and information.

**Comment by kurokirasama** [comment]
according to a missedfont.log file that was generated, there are 57 fonts missing. Do I have to do that for everyone of them?

**Comment by kurokirasama** [comment]
I did the tlmgr search for one, there was a git, but when I try to install, it tells me that there is not such file.

**Comment by Grimler91** [comment]
What did you try to install then?

**Comment by kurokirasama** [comment]
It's now fixed after running
```
tlmgr install collections-fontsrecommended
```

**Comment by Grimler91** [comment]
Alright, this can be closed then.
