### ISSUE TITLE
[Package]: portal

### ISSUE THREAD

**Issue by kyzsuukii** [termux/termux-packages#17671]
### Why is it worth to add this package?

a command-line file transfer utility for sending files from any computer to another

### Source code URL

https://github.com/SpatiumPortae/portal

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

i ever try to build it and success but got issue on send and receive file
![Screenshot_20230820-104038_Termux.png](https://github.com/termux/termux-packages/assets/110718021/9c9ed98d-87bd-421d-86de-ec1f8494f92f)

**Comment by kyzsuukii** [comment]
ahh thanks i am also looking alternative

so i can transfer file from my vps to termux

**Comment by TomJo2000** [comment]
> ahh thanks i am also looking alternative
> 
> so i can transfer file from my vps to termux

Have a look at `rsync` or `scp`.
Both of which piggyback off SSH.
