### ISSUE TITLE
Please consider changing exa to eza.

### ISSUE THREAD

**Issue by RaWolFoX** [termux/termux-packages#17681]
### Why is it worth to add this package?

Exa is not releasing new versions and look like its dead. There is community maintained fork called [Eza](https://github.com/eza-community/eza) . please look into it.

### Source code URL

https://github.com/eza-community/eza

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by MartinFillon** [comment]
Do we have an ETA on this issue ?

**Comment by TomJo2000** [comment]
Alright, seems to be building.
Tested the resulting `.deb` and as far as I can tell its running perfectly.

**Comment by MartinFillon** [comment]
Super nice when you merged it please tell me we will add it to our next changelog

**Comment by TomJo2000** [comment]
> Super nice when you merged it please tell me we will add it to our next changelog

I'm currently cleaning up a couple things before opening the PR like cleaning up the build script a little, making sure `eza` is marked as replacing `exa`, and adding a replacement notice on install.
