### ISSUE TITLE
Confusing Usage

### ISSUE THREAD

**Issue by Manto321** [termux/termux-packages#17687]
So, when I used
```shell
scrypt enc example.mp3 example2.mp3,
``` 
I always get a massage saying:`usage: scrypt {enc | dec} [-f] [-M maxmem] [-m maxmemfrac]
              [-t maxtime] [-v] [-P] infile [outfile]
       scrypt --version`Why,?

**Comment by Manto321** [comment]
`cannot parse :test ` or smh idk that's my second issue

**Comment by TomJo2000** [comment]
From the [man page](https://man.archlinux.org/man/scrypt.1), it appears `scrypt` takes one (1) input files, and writes its results to one (1) output file.

You seem to be trying to apply `scrypt` to multiple existing files simultaneously.
