### ISSUE TITLE
[Bug]: go: RLock go.mod: function not implemented

### ISSUE THREAD

**Issue by zerofo** [termux/termux-packages#17691]
### Problem description

build https://github.com/alist-org/alist  source
```
go build . 
```
Get Error
```
go: RLock go.mod: function not implemented
```

### What steps will reproduce the bug?

```
apt install vim wget curl git golang clang
git clone --depth 1 https://github.com/alist-org/alist
cd alist
go build . 
```

### System information

termux-info:

```
Termux Variables:
unsupported
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.bfsu.edu.cn/termux/apt/termux-root root stable
Updatable packages:
Running as root. Cannot check package updates.
termux-tools version:
1.38.5
Android version:
13
Kernel build information:
Linux localhost 5.10.177-android12-9-gcbe815fadca1 #1 SMP PREEMPT Tue Jul 18 17:00:37 UTC 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
2203121C
LD Variables:
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
LD_PRELOAD=
Installed termux plugins:
com.termux.styling versionCode:29
```
test on xiaomi 12s Ultra and xiaomi 10 pro (cmi)

**Comment by zerofo** [comment]
@2096779623  hello, do you know how to fix it ?

**Comment by 2096779623** [comment]
You haven't done `go mod tidy` yet.
Please refer to the content in [build.sh](https://github.com/alist-org/alist/blob/main/build.sh) to build.

**Comment by 2096779623** [comment]
![image](https://github.com/termux/termux-packages/assets/57583560/a18d6e5d-9d2e-4871-938d-a16b87c238ef)
But I can build it now.

**Comment by zerofo** [comment]
> You haven't done yet. Please refer to the content in [build.sh](https://github.com/alist-org/alist/blob/main/build.sh) to build.`go mod tidy`

it work. thanks for your direction

**Comment by rios0rios0** [comment]
> > You haven't done yet. Please refer to the content in [build.sh](https://github.com/alist-org/alist/blob/main/build.sh) to build.`go mod tidy`
> 
> it work. thanks for your direction

I can't build anything. Even a code started from scratch with termux. `````` go mod tidy```  does the same error.

**Comment by bojale** [comment]
> > > You haven't done yet. Please refer to the content in [build.sh](https://github.com/alist-org/alist/blob/main/build.sh) to build.`go mod tidy`
> > 
> > 
> > it work. thanks for your direction
> 
> I can't build anything. Even a code started from scratch with termux. `````` go mod tidy``` does the same error.

This error occurs if you try to build code inside the storage (symlinked in Termux home to your ordinary user space that you see in Files apps on Android, like your Download folder or Document or users "/"). If you move the code into Termux home path (mv myCode ~/) and build there, it will work
