### ISSUE TITLE
64bit: git clone segmentation fault

### ISSUE THREAD

**Issue by vainikkaj** [termux/termux-packages#177]
This started happening after I upgraded my Nexus 9 into 64-bit Termux (using fresh install method).

```
$ git clone http://www.github.com/termux/termux-packages
Cloning into 'termux-packages'...
remote: Counting objects: 6516, done.
remote: Compressing objects: 100% (201/201), done.
remote: Total 6516 (delta 96), reused 0 (delta 0), pack-reused 6313
Receiving objects: 100% (6516/6516), 1.45 MiB | 326.00 KiB/s, done.
Resolving deltas: 100% (3538/3538), done.
Checking connectivity... done.
Segmentation fault
```

strace output is available at https://gist.github.com/vainikkaj/df9177a8afffdf270f42

**Comment by fornwall** [comment]
On nexus 9. I'm able to clone https and ssh repos on a nexus 6p.

**Comment by fornwall** [comment]
@vainikkaj Since I'm unable to reproduce the segfault, could you try to get a backtrace with gdb?

I built a git package with debug symbols at http://fornwall.net/DEBUG_git-2.7.4_aarch64.deb, so use something like the below:

    wget http://fornwall.net/DEBUG_git-2.7.4_aarch64.deb
    dpkg -i DEBUG_git-2.7.4_aarch64.deb
    apt install gdb
    gdb git
    # At the gdb prompt, run:
    run clone http://www.github.com/termux/termux-packages

then when hitting the segfault run

    backtrace

and see if you get a backtrace you can paste here?

**Comment by vainikkaj** [comment]
No need for gdb backtrack because your debug build worked. I noticed that you pushed 2.7.4 few hours ago and after brief testing it proved to be working also. Perhaps new build with aarch64 toolchain did the trick? Thanks for you help.

**Comment by fornwall** [comment]
@vainikkaj Great that it works now, let me know if you find out about anything more broken under aarch64!
