### ISSUE TITLE
Errors in post update steps for TeXLive using tlmgr

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#17722]
### Problem description

I did an update of TeXLive using tlmgr and after installing the packaged to be upgraded the post install steps shows errors mainly with `lua*` packages. I add this part of the upgrade log.
[error-tl-update.log.gz](https://github.com/termux/termux-packages/files/12474647/error-tl-update.log.gz)

Is there a workaround to fix those errors?

TIA,
 Angelo.

**Comment by Grimler91** [comment]
Thanks for reporting, fixed in texlive-bin 20230313-1!

**Comment by angelog0** [comment]
@Grimler91 , thanks but what about:

@angelog0 

> Is there a workaround to fix those errors?

after upgrading the binaries?
