### ISSUE TITLE
Is Termux switching to new NDK?

### ISSUE THREAD

**Issue by skycat2216** [termux/termux-packages#17734]
### Problem description

[#7338]([https://github.com/termux/termux-packages/issues/7338])
It's happening again,on my phone and WSA.
I checked issues and found no infomation of any new Header updates
Is Termux switching to new version of Headers?

### What steps will reproduce the bug?

"Write hello world with c++"
"use clang to compile it"
"ld.lld: error: undefined symbol: std::__ndk1::cout"
">>> referenced by test.cpp"
">>>               /data/data/com.termux/files/usr/tmp/test-9f87ee.o:(main)"

### What is the expected behavior?

compile passed 

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=30489
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
x86_64
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main stable main
# root-repo (sources.list.d/root.list)
deb https://mirror.mwt.me/termux/root root stable
Updatable packages:
apt/stable 2.7.3 x86_64 [upgradable from: 2.7.2]
ca-certificates/stable 1:2023.08.22 all [upgradable from: 1:2023.05.30]
command-not-found/stable 2.2.0-14 x86_64 [upgradable from: 2.2.0-8]
curl/stable 8.2.1 x86_64 [upgradable from: 8.2.0]
debianutils/stable 5.8 x86_64 [upgradable from: 5.7-1]
gzip/stable 1.13 x86_64 [upgradable from: 1.12-1]
libcurl/stable 8.2.1 x86_64 [upgradable from: 8.2.0]
liblzma/stable 5.4.4 x86_64 [upgradable from: 5.4.3]
libsmartcols/stable 2.39.2 x86_64 [upgradable from: 2.39.1]
openssl/stable 1:3.1.2 x86_64 [upgradable from: 1:3.1.1]
util-linux/stable 2.39.2 x86_64 [upgradable from: 2.39.1]
xz-utils/stable 5.4.4 x86_64 [upgradable from: 5.4.3]
zlib/stable 1.3 x86_64 [upgradable from: 1.2.13]
termux-tools version:
1.38.5
Android version:
13
Kernel build information:
Linux localhost 5.15.104-windows-subsystem-for-android-20230608+ #1 SMP PREEMPT Sat Jul 8 04:23:19 UTC 2023 x86_64 Android
Device manufacturer:
Google                                   //Why M$ Devs uses Pixel 5 as disguise? 
Device model:
Pixel 5
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

```
It also

**Comment by licy183** [comment]
I don't think this is related to #7338. You should not use `clang` to compile C++ sources. It will not link to `libc++` automatically.

**Comment by skycat2216** [comment]
> I don't think this is related to #7338. You should not use `clang` to compile C++ sources. It will not link to `libc++` automatically.

Already tried --stdlib=libc++ option.

**Comment by licy183** [comment]
You need use `clang++` to compile CXX files rather than `clang`.

```
clang++ main.cpp
```

**Comment by skycat2216** [comment]
> You need use `clang++` to compile CXX files rather than `clang`. If you really want to compile CXX files using `clang`, please use `-lc++_shared` option.
> 
> ```
> clang++ main.cpp
> clang main.cpp -lc++_shared
> ```

Thank you for solve problem.
