### ISSUE TITLE
[Package]: nethunter kex passwd

### ISSUE THREAD

**Issue by Chinnupatil** [termux/termux-packages#17748]
### Why is it worth to add this package?

Nethunter kex passwd problem 

### Home page URL

Termux

### Source code URL

Gitub

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by agnostic-apollo** [comment]
https://wiki.termux.com/wiki/Hacking
