### ISSUE TITLE
[Bug]: Multiple Tab opening problem 

### ISSUE THREAD

**Issue by sumanbera2002** [termux/termux-packages#17765]
### Problem description

When i swipe for open more 1 or 2 tab in termux app it not so easy.
Tab drawer open after swipe 3 or 4 time.
Tab drawer smoothly work in play Store termux version.

### What steps will reproduce the bug?

I don't know. 🙂🙂

### System information

~ $ termux-info
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=27066
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.39.0
Android version:
12
Kernel build information:
Linux localhost 4.14.190-perf-g19c1ecd3f0fa #1 SMP PREEMPT Mon Jun 19 11:00:05 CST 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
POCO M2 Pro
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by agnostic-apollo** [comment]
Try setting `terminal-margin-horizontal=0` or add `DRAWER` extra key.

https://wiki.termux.com/wiki/Terminal_Settings#Adjust_Terminal_Margin.2FPadding

https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row
