### ISSUE TITLE
bash: ./a.out: Permission denied (Android 6)

### ISSUE THREAD

**Issue by 134sofiane** [termux/termux-packages#1776]
Hi, 
I want to compile and execute a c program called hello.c ( it is on the directory /sdcard )
i wrote:
 cd /sdcard 
clang hello.c (it worked well)
But when I write :
./a.out 
I give the following message:

bash: ./a.out: Permission denied 

Please how  can I solver this problem ??

**Comment by Auxilus** [comment]
you cant execute files on `sdcard`, you have to move a.out to $HOME

**Comment by 134sofiane** [comment]
Ok thank you Auxilus .

**Comment by dextercva** [comment]
Yes, i figured this problem when i do clang name.c it compiled but the output file was a.out unable to open saying permission denied. So is there any specific reason for this...?

**Comment by xeffyr** [comment]
> So is there any specific reason for this...?

Reason is that you can't have executables on /sdcard because Android enforces noexec for all kinds of external storage.

**Comment by eldiapason** [comment]
Actually, I have the same problem, but I have no sd card installed, and all my files are on internal storage.
Any suggestions ?

**Comment by xeffyr** [comment]
There only one suggestion - move all executables & scripts to Termux home folder (`/data/data/com.termux/files/home`) by using command `mv`.
