### ISSUE TITLE
[Bug]: running qtcreator returns: Bad system call

### ISSUE THREAD

**Issue by talal12bfk** [termux/termux-packages#17780]
### Problem description

When I was trying to compile a qt project([QOwnNotes](https://www.qownnotes.org)) i tried to use qtcreator on the project file which failed giving me:
Bad system call
I tried to run it without any arguments which returned the same thing. I decided to build the project without qtcreator, it build successfully but running the executable results in the same problem.

Here is the `strace` log for qtcreator:
[qtcreator.log](https://github.com/termux/termux-packages/files/12564249/qtcreator.log)

Here is the `strace` log for QOwnNotes:
[QOwnNotes.log](https://github.com/termux/termux-packages/files/12564260/QOwnNotes.log)

### What steps will reproduce the bug?

1. `qtcreator`
2. `'QStandardPaths: XDG_RUNTIME_DIR not set, defaulting
to '/data/data/com.termux/files/usr/tmp/runtime-u0_a261'
Bad system call'`

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=25212
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.0
Android version:
10
Kernel build information:
Linux localhost 4.4.177-18310171 #1 SMP PREEMPT Wed Apr 8 21:53:40 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A205F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=
Installed termux plugins:
com.termux.x11 versionCode:14
```

**Comment by licy183** [comment]
`libandroid-sysv-semaphore` seems not working on Android 26+...

**Comment by talal12bfk** [comment]
> `libandroid-sysv-semaphore` seems not working on Android 26+...

is it fixable on my side?

**Comment by licy183** [comment]
I've submitted a fix for it. Please download the debs from the workflow and test whether it fixes this problem or not when it's convenient for you. Thanks!

**Comment by talal12bfk** [comment]
> I've submitted a fix for it. Please download the debs from the workflow and test whether it fixes this problem or not when it's convenient for you. Thanks!

That seems to have fixed the problem,
I'm Very very grateful for your help <3

here is a screenshot of qtcreator working!

![qtcreator](https://github.com/termux/termux-packages/assets/85613292/3363d8b3-0917-43c3-ba59-ff0e397e7a39)
