### ISSUE TITLE
Hope to add tls cert option to pure-ftpd.

### ISSUE THREAD

**Issue by Sak94664** [termux/termux-packages#1779]
I think it would be safer and faster transferring files.(for sftp is much slower than ftpes)
Thanks in advance!

**Comment by fornwall** [comment]
Thanks! Can you update with `pkg up` to the updated `1.0.47` version of the package, and see if tls works with that version (it was built with `--with-tls`)?

**Comment by Sak94664** [comment]
@fornwall 
It works,thanks!
