### ISSUE TITLE
Auto update failing for libsodium

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#17814]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the libsodium package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating libsodium [Current version: 1.0.18]
INFO: package being updated to 1.0.19.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 1856k    0 1856k    0     0  1946k      0 --:--:-- --:--:-- --:--:-- 1946k
100 2099k    0 2099k    0     0  2055k      0 --:--:--  0:00:01 --:--:-- 3578k

You are about to commit these changes:

--------------------
diff --git a/packages/libsodium/build.sh b/packages/libsodium/build.sh
index 1f4307ea0..b22ea484a 100644
--- a/packages/libsodium/build.sh
+++ b/packages/libsodium/build.sh
@@ -2,10 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://libsodium.org/
 TERMUX_PKG_DESCRIPTION="Network communication, cryptography and signaturing library"
 TERMUX_PKG_LICENSE="ISC"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION=1.0.18
-TERMUX_PKG_REVISION=3
+TERMUX_PKG_VERSION="1.0.19"
 TERMUX_PKG_SRCURL=https://github.com/jedisct1/libsodium/archive/${TERMUX_PKG_VERSION}-RELEASE.tar.gz
-TERMUX_PKG_SHA256=b7292dd1da67a049c8e78415cd498ec138d194cfdb302e716b08d26b80fecc10
+TERMUX_PKG_SHA256=980bd4c915c791c53a445ae8a193164a3f8c563ffb1055436b8601480e9fd5ce
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
 TERMUX_PKG_BREAKS="libsodium-dev"
--------------------

bump(main/libsodium): 1.0.19

Not committing to Git!

INFO: Trying to build package.
INFO: Package libsodium exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building libsodium for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  22072      0 --:--:-- --:--:-- --:--:-- 22073
100 13134  100 13134    0     0  22067      0 --:--:-- --:--:-- --:--:-- 22036
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1412      0 --:--:-- --:--:-- --:--:--  1414
gpg: Signature made Wed 13 Sep 2023 12:31:43 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13319  100 13319    0     0  22152      0 --:--:-- --:--:-- --:--:-- 22124
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1233      0 --:--:-- --:--:-- --:--:--  1232
100   833  100   833    0     0   1233      0 --:--:-- --:--:-- --:--:--  1232
gpg: Signature made Thu 07 Sep 2023 12:20:57 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  21869      0 --:--:-- --:--:-- --:--:-- 21903
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1430      0 --:--:-- --:--:-- --:--:--  1428
gpg: Signature made Tue 12 Sep 2023 05:17:30 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://github.com/jedisct1/libsodium/archive/1.0.19-RELEASE.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 2099k    0 2099k    0     0  2192k      0 --:--:-- --:--:-- --:--:-- 2192k
ERROR: SOVERSION guard check failed.
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-09-13 12:19:47 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/6172182861">6172182861</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by twaik** [comment]
Fixed by 6652093cf042a4a43d73169d6ba9c7d476538f1a
