### ISSUE TITLE
[Bug]: how to install pandas module in termux

### ISSUE THREAD

**Issue by dextercva** [termux/termux-packages#17819]
### Problem description

I installed Python in termux. When I install pandas module I'm getting the below following error in termux.

> SystemError: One of the required function to build numpy is not available (the list is ['sin', 'cos', 'tan', 'sinh', 'cosh', 'tanh', 'fabs', 'floor', 'ceil', 'sqrt', 'log10', 'log', 'exp', 'asin', 'acos', 'atan', 'fmod', 'modf', 'frexp', 'ldexp']).
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.

### What steps will reproduce the bug?

`pkg install python`
`pip install pandas`

### What is the expected behavior?

I want pandas module to be installed in Termux and import pandas and run code. 

### System information

termux-info:

```

```

**Comment by romanovj** [comment]
pkg i python-numpy tur-repo
pkg i python-pandas

**Comment by licy183** [comment]
`python-pandas` is available in TUR. If you really want to build it from source, try `MATHLIB=m pip install pandas`.
