### ISSUE TITLE
[Bug]: ERROR: Package contains hard links: ./bin/perlbug

### ISSUE THREAD

**Issue by hanxinhao000** [termux/termux-packages#17837]
### Problem description

  /data/data/com.termux/files/usr/share/man/man1/cpan.1
  /data/data/com.termux/files/usr/share/man/man1/corelist.1
  /data/data/com.termux/files/usr/share/man/man1/enc2xs.1
  /data/data/com.termux/files/usr/share/man/man1/encguess.1
  /data/data/com.termux/files/usr/share/man/man1/h2ph.1
  /data/data/com.termux/files/usr/share/man/man1/h2xs.1
  /data/data/com.termux/files/usr/share/man/man1/instmodsh.1
  /data/data/com.termux/files/usr/share/man/man1/json_pp.1
  /data/data/com.termux/files/usr/share/man/man1/libnetcfg.1
  /data/data/com.termux/files/usr/share/man/man1/perlbug.1
  /data/data/com.termux/files/usr/share/man/man1/perlthanks.1
  /data/data/com.termux/files/usr/share/man/man1/perlivp.1
  /data/data/com.termux/files/usr/share/man/man1/piconv.1
  /data/data/com.termux/files/usr/share/man/man1/pl2pm.1
  /data/data/com.termux/files/usr/share/man/man1/pod2html.1
  /data/data/com.termux/files/usr/share/man/man1/prove.1
  /data/data/com.termux/files/usr/share/man/man1/ptar.1
  /data/data/com.termux/files/usr/share/man/man1/ptardiff.1
  /data/data/com.termux/files/usr/share/man/man1/ptargrep.1
  /data/data/com.termux/files/usr/share/man/man1/shasum.1
  /data/data/com.termux/files/usr/share/man/man1/splain.1
  /data/data/com.termux/files/usr/share/man/man1/streamzip.1
  /data/data/com.termux/files/usr/share/man/man1/xsubpp.1
  /data/data/com.termux/files/usr/share/man/man1/zipdetails.1
make[1]: Leaving directory '/home/builder/.termux-build/perl/src'
termux-elf-cleaner: Replacing unsupported DF_1_* flags 134217729 with 1 in './bin/perl'
ERROR: Package contains hard links: ./bin/perlbug
./bin/perlthanks

### What steps will reproduce the bug?

./build-package.sh -i perl

### System information

termux-info:

```

```

**Comment by TechMasterfury** [comment]
Unsubcribe


♪⁠┌⁠|⁠∵⁠|⁠┘⁠♪ sent by Jeffrey @ okanogan tech

**Comment by twaik** [comment]
@TechMasterfury It does not work this way. You must click a button to unsubscribe.
<details>

![123123123](https://github.com/termux/termux-packages/assets/9674930/4bc30679-f91c-4141-80bc-fe78d03f2a51)
</details>
