### ISSUE TITLE
Can't Install NodeJS, corrupted filesystem tarfile?

### ISSUE THREAD

**Issue by ClickSimply** [termux/termux-packages#1784]
Not sure what to do here.

Brand new install of Termux on a rooted Android 5.1 device.  Downloaded Termux from the Google Play store, opened it up, typed `apt install nodejs` and got this result:
```
dpkg: error processing archive: /data/data/com.terumx/files/usr/var/cache/apt/archives/nodejs_8.9.0-1_arm.deb (--unpack):
corrupted filesystem tarfile - corrupted package archive
```

Doing `apt install nodejs-current` provides the same error, only with a different version number in the download.
- Restarting the device didn't help.
- Reinstalling termux didn't help.
- Other packages like Curl and Wget installed just fine.

Google search hasn't turned up anything useful for the error, not sure what to diagnose from here.

Thanks guys.

**Comment by xeffyr** [comment]
Try to do this:
```
apt-get clean
apt-get update
apt-get install nodejs
```

**Comment by ClickSimply** [comment]
Thanks for the response, ran the commands and still no dice....

I ran the commands on another Android device and had success, so there must be some configuration/app on my initial device that's causing the problem.

I'll keep looking into this and update if I find a resolution.  In any case I think it's safe to say Termux and the packages aren't to blame.

Thanks for the help.

**Comment by fornwall** [comment]
@ClickSimply Thanks - let us know if you find out what causes the problem, and I'll reopen the issue if it's something that can be improved on the side of Termux!

**Comment by gdevacc12** [comment]
I'm getting the same problem:

> Unpacking nodejs (8.9.3) ...
> dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/nodejs_8.9.3_arm.deb (--unpack):
> corrupted filesystem tarfile - corrupted package archive
>dpkg-deb (subprocess): decompressing archive member: lzma write error: Broken pipe
>dpkg-deb: error: <decompress> subprocess returned error exit status 2
>Errors were encountered while processing:
> /data/data/com.termux/files/usr/var/cache/apt/archives/nodejs_8.9.3_arm.deb
>E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

I tried the usual apt fixes: update upgrade autoclean autoremove

**Comment by peterstadie** [comment]
Same here, I am using Galaxy Note 4 with Android 6.0.1. It's not network related, I tried it on different networks. I was working a week before with Note 3, however, this one was not updated for quite a while...

**Comment by gdevacc12** [comment]
Same problem with 8.9.4. Strange that despite the error message pointing to the archive, it extracts ok:
`$pwd
/data/data/com.termux/files/usr/var/cache/apt/archives
$ dpkg -x ./nodejs_8.9.4_arm.deb /
$ node -v
v8.9.4`
but `dpkg -i ./nodejs_8.9.4_arm.deb` throws the error.

**Comment by gdevacc12** [comment]
I ran `dpkg --debug=3773 -i ./nodejs_8.9.4_arm.deb` and around the error got:

> D000100: secure_remove '/data/data/com.termux/files/usr/share/man/man1/node.1.dpkg-new' unlink OK
D000002: maintscript_new nonexistent postrm '/data/data/com.termux/files/usr/var/lib/dpkg/tmp.ci/postrm' 
dpkg-deb (subprocess): decompressing archive member: lzma write error: Broken pipe                                dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg-deb (subprocess): cannot copy archive member from './nodejs_8.9.4_arm.deb' to decompressor pipe: failed to write (Broken pipe)
D000010: path_remove_tree '/data/data/com.termux/files/usr/var/lib/dpkg/tmp.ci'                                   D000010: path_remove_tree running rm -rf '/data/data/com.termux/files/usr/var/lib/dpkg/tmp.ci'                    D000010: path_remove_tree '/data/data/com.termux/files/usr/var/lib/dpkg/reassemble.deb'                           Errors were encountered while processing:                                                                          ./nodejs_8.9.4_arm.deb

Could the 
> nonexistent postrm

be a problem?
