### ISSUE TITLE
[Bug]: some times kali linix is not executing.

### ISSUE THREAD

**Issue by FATALITYop** [termux/termux-packages#17842]
### Problem description

![Screenshot_20230917_175125_Termux](https://github.com/termux/termux-packages/assets/145267943/28e526aa-0a4f-4ecf-9064-84682cf732bb)

### What steps will reproduce the bug?

Please do something.

### What is the expected behavior?

Very good.

### System information

termux-info:

```

```

**Comment by twaik** [comment]
We are not helping with hacking tools. https://wiki.termux.com/wiki/Hacking
