### ISSUE TITLE
[Package]: ffplayout 

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#17847]
### Why is it worth to add this package?

Because its a unique package. There's not any single package with same functionality 

### Home page URL

https://ffplayout.github.io/

### Source code URL

https://github.com/ffplayout/ffplayout

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by TomJo2000** [comment]
(For documentation)
- https://github.com/termux-user-repository/tur/pull/668
