### ISSUE TITLE
[Bug]:  Problem with the CMake installation, build keeps aborting

### ISSUE THREAD

**Issue by Per1winkle** [termux/termux-packages#17850]
### Problem description

![Screenshot_20230918-113807](https://github.com/termux/termux-packages/assets/145385738/0ebc048d-b885-4247-a9ef-dfb65629d56e)

        Cannot build wheel for patchelf and cannot build ninja patchelf. Can't build wheels for ninja, patchelf, which is required to install pyproject.toml-based projects

### What steps will reproduce the bug?

When I try to install pip > cmake.

### What is the expected behavior?

ERROR: Could not build wheels for ninja, patchelf, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

### System information

termux-info:

```
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for patchelf
      Failed to build ninja patchelf
      ERROR: Could not build wheels for ninja, patchelf, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking
