### ISSUE TITLE
kalifs-arm64-nano.tar.xz kali.download" is not working...the page doesn't exist 

### ISSUE THREAD

**Issue by Tal-1959** [termux/termux-packages#17893]
### Why is it worth to add this package?

It's for my nethunter download 

### Source code URL

kalifs-arm64-nano.tar.xz kali.download

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

--2023-09-25 10:31:28--  https://kali.download/nethunter-images/current/rootfs/kalifs-arm64-nano.tar.xz
Resolving kali.download (kali.download)... 104.18.102.100, 104.18.103.100, 2606:4700::6812:6664, ...
Connecting to kali.download (kali.download)|104.18.102.100|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-09-25 10:31:30 ERROR 404: Not Found.

**Comment by Maxython** [comment]
No and never - https://wiki.termux.com/wiki/Hacking
