### ISSUE TITLE
Segfault in php when using bind_result in php-mysql

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#1790]
Copied from https://github.com/termux/termux-packages/pull/1025. It's still happening with @vishalbiswas php-mysql.

Since the mariadb update to 10.2.6, php sometimes Segfaults when connecting to large databases. I've seen this issue come up with Typo3 instances.

WARNING: [pool www] child 5574 exited on signal 11 (SIGSEGV - core dumped) after 1.226751 seconds from start

I'm not sure what could cause the problem

Stacktrace: 
```
Program received signal SIGSEGV, Segmentation fault.
0x0000007fb6f3f9f8 in zif_mysqli_stmt_bind_result ()
   from /data/data/com.termux/files/usr/lib/php/mysqli.so
(gdb) bt
#0  0x0000007fb6f3f9f8 in zif_mysqli_stmt_bind_result ()
   from /data/data/com.termux/files/usr/lib/php/mysqli.so
#1  0x00000030004095f4 in zend_call_function ()
#2  0x000000300034c124 in zif_call_user_func_array ()
#3  0x00000030004be040 in ?? ()
#4  0x0000003000a59000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

**Comment by vishalbiswas** [comment]
upstream php hasn't been updated for latest mariadb versions yet

**Comment by Neo-Oli** [comment]
Finally, after hours of debugging I found a short reproducible test case. It can be tested with one short file and 4 commands. There is no webserver or Typo3 instance required. This is very exciting as now anyone can test this segfault, without finding out how to install Typo3 or installing a Webserver. In fact it's completely unrelated to Typo3. 

Setup (works on a blank termux)
```
# installs php, mariadb and php-mysql
apt install php-mysql 
# sets up the default mysql tables
mysql_install_db 
# launch a mysql server
mysqld &
# run test script
php -dextension=mysqli.so test.php
```

test.php
```
<?php
$mysqli = new mysqli("localhost", "root", null, "mysql");
if (mysqli_connect_errno()) {
    printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
}
/* prepare statement */
if ($stmt = $mysqli->prepare("SELECT * from help_keyword")) {
    $stmt->execute();

    /* bind variables to prepared statement */
    $stmt->bind_result($col1, $col2);

    /* fetch values */
    while ($stmt->fetch()) {
        printf("%s %s\n", $col1, $col2);
    }

    /* close statement */
    $stmt->close();
}
/* close connection */
$mysqli->close();

?>
```
result:
```
2017-12-05 22:43:58 547879920720 [Warning] Aborted connection 8 to db: 'mysql' user: 'root' host: 'localhost' (Got an error reading communication packets)
Segmentation fault (core dumped)
```

The test script is taken straight from the php manual http://php.net/manual/en/mysqli-stmt.bind-result.php

**Comment by Neo-Oli** [comment]
Possible related bug in php bugtracker: https://bugs.php.net/bug.php?id=74046

**Comment by Neo-Oli** [comment]
Second seemingly related php bug: https://bugs.php.net/bug.php?id=66762
Both test scripts also segfault on Termux.

Is it unusual for php-mysql to be built against mariadb? Is there another distribution that has ditched mysql completely?

**Comment by Neo-Oli** [comment]
The problem doesn't seem to occur when php is build with mysqlnd instead of the mariadb library.
Does anybody know if there are any negative consequences to this?

```
diff --git a/packages/php/build.sh b/packages/php/build.sh
index d450d685..4c0480fe 100644
--- a/packages/php/build.sh
+++ b/packages/php/build.sh
@@ -35,7 +35,7 @@ ac_cv_func_res_nsearch=no
 --with-zlib
 --with-pgsql=shared,$TERMUX_PREFIX
 --with-pdo-pgsql=shared,$TERMUX_PREFIX
---with-mysqli=shared,$TERMUX_PREFIX/bin/mysql_config
+--with-mysqli=mysqlnd
 --with-pdo-mysql=shared,$TERMUX_PREFIX/bin/mysql
 --with-mysql-sock=$TERMUX_PREFIX/tmp/mysqld.sock
 --with-apxs2=$TERMUX_PREFIX/bin/apxs
```
