### ISSUE TITLE
Wireless-Tools Package(Iwconfig)

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-packages#1791]
Can you add a package [Wireless Tools](https://packages.debian.org/ru/jessie/wireless-tools)

**Comment by Auxilus** [comment]
pr for that is already open

**Comment by Auxilus** [comment]
you can compile it yourself ,  go through  https://github.com/termux/termux-root-packages/pull/4

**Comment by Deathlive** [comment]
@Auxilus It is possible in more detail.
How can I compile it and install it in the Termux?

**Comment by Deathlive** [comment]
@Auxilus If it is not difficult, can you give me a compiled deb package ?
