### ISSUE TITLE
Package request: Atomic Parsley

### ISSUE THREAD

**Issue by neelkamath** [termux/termux-packages#1792]
Using `pkg install atomicparsley` works on Ubuntu based distros with `apt-get install atomicparsley` but not on Termux.
It gives the error: `E: Unable to locate package atomicparsley`.

**Comment by Grimler91** [comment]
That means that no one has ported it for termux yet. You can try compiling it yourself on device, or cross compiling it by following the instructions in the readme. 

Another option is of course to convert this issue into a package request and see if someone else is up for the challenge to cross compile it.

**Comment by neelkamath** [comment]
Doing it myself is beyond me. How do I convert this issue into a package request?

**Comment by its-pointless** [comment]
pull request #1822
If you could test it that would be good.
https://github.com/its-pointless/its-pointless.github.io/blob/master/files/dists/termux/extras/binary-arm/atomicparsley_0.9.6_arm.deb

**Comment by neelkamath** [comment]
This is what happened when I installed the file you commented ([the arm version](https://github.com/its-pointless/its-pointless.github.io/blob/master/files/dists/termux/extras/binary-arm/atomicparsley_0.9.6_arm.deb)):

```shell
$ pkg install ./atomicparsley_0.9.6_arm.deb
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
7 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'atomicparsley:arm' instead of './atomicparsley_0.9.6_arm.deb'
The following NEW packages will be installed:
  atomicparsley:arm
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 0 B/94.0 kB of archives.
After this operation, 217 kB of additional disk space will be used.
Get:1 /storage/emulated/0/Download/atomicparsley_0.9.6_arm.deb atomicparsley arm 0.9.6 [94.0 kB]
dpkg: error processing archive /storage/emulated/0/Download/atomicparsley_0.9.6_arm.deb (--unpack):
 package architecture (arm) does not match system (aarch64)
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

So I installed the [the aarch64 version](https://github.com/its-pointless/its-pointless.github.io/blob/master/files/dists/termux/extras/binary-aarch64/atomicparsley_0.9.6_aarch64.deb) instead and it installed.

Here's the error I get when using it:

```shell
$ youtube-dl "https://m.youtube.com/watch?v=m1PDqdLQMv8" -x --audio-format m4a --embed-thumbnail
[youtube] m1PDqdLQMv8: Downloading webpage
[youtube] m1PDqdLQMv8: Downloading video info webpage
[youtube] m1PDqdLQMv8: Extracting video information
[youtube] m1PDqdLQMv8: Downloading MPD manifest
[youtube] m1PDqdLQMv8: Downloading thumbnail ...
[youtube] m1PDqdLQMv8: Writing thumbnail to: Miss World 2017 Top 5 Question and Answer-m1PDqdLQMv8.jpg
[download] Destination: Miss World 2017 Top 5 Question and Answer-m1PDqdLQMv8.webm
[download] 100% of 5.77MiB in 00:00
[ffmpeg] Destination: Miss World 2017 Top 5 Question and Answer-m1PDqdLQMv8.m4a
Deleting original file Miss World 2017 Top 5 Question and Answer-m1PDqdLQMv8.webm (pass -k to keep)
[atomicparsley] Adding thumbnail to "Miss World 2017 Top 5 Question and Answer-m1PDqdLQMv8.m4a"
ERROR: "AtomicParsley": error: only position independent executables (PIE) are supported.
```

Steps to get this error in Termux:
1. `pkg install python`
1. `pip install --upgrade youtube-dl`
1. `pkg install ffmpeg`
1. `youtube-dl "https://m.youtube.com/watch?v=m1PDqdLQMv8" -x --audio-format m4a --embed-thumbnail`

**Comment by Quasic** [comment]
arm version is also not PIE

**Comment by its-pointless** [comment]
Sorry bout that fix it in a bit

**Comment by sdrausty** [comment]
It looks like Atomic Parsley is currently available in Termux through Arch Linux PTRoot.  This script is designed to install Arch Linux in just a few keystrokes. Tapping this link https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh will transfer `setupTermuxArch.sh` to your device. Simply run `bash setupTermuxArch.sh` to install Arch Linux in Termux.  To install use `pacman -S atomicparsley` and this will install Atomic Parsley on device. 

![screenshot_20171130-003146](https://user-images.githubusercontent.com/27742457/33415663-f4d74c72-d565-11e7-9725-89a423e511b9.png)

**Comment by neelkamath** [comment]
You have to set the locale and stuff while setting up Arch after waiting for it to download a big file and decompress. For the simple script I have to download music from YouTube, this is overkill. However, I see the difficulties in making the package for Termux so I'm fine without `atomicparsley` if it's not possible atm. Feel free to close this I guess.

**Comment by sdrausty** [comment]
@neelkamath thank you for trying Arch Linux in Termux PProot. There is a small helper script `yt` in the `/root/bin` directory which installs and runs `youtube-dl` in Arch.  I haven't had a chance to take a closer look at `atomicparsley` itself in detail.  Can you tell us some about some of its' advantages?

**Comment by sdrausty** [comment]
@neelkamath "You have to set the locale and stuff" untrue. What you describe is automated into the setup script if you want English.  If you do want another language, you should specify it.

**Comment by neelkamath** [comment]
@sdrausty `atomicparsley` is required for the pip package `youtube-dl` to download the cover art while downloading YouTube videos. This is great for music.

As for the Arch Linux part, it's still overkill for my needs for `atomicparsley`. I'd rather just not use `atomicparsley` then.

**Comment by sdrausty** [comment]
@neelkamath thank you for describing atomicparsley.  Hopefully, someone will come along and port it to Termux.

**Comment by its-pointless** [comment]
Iv already ported it...
does it not work?

**Comment by neelkamath** [comment]
oh
I checked a day after and it wasn't updated so I thought you'd followup when you fixed it
as a note, i have recently lost interest in android and prefer iOS so i'm deleting my termux scripts
i have seen many ppl use `youtube-dl` on termux though so it'd still be useful

**Comment by fornwall** [comment]
Thanks to @its-pointless there is now an `atomicparsley` package available for installation!
