### ISSUE TITLE
zsh doesn't parse regular expression in x86 devices

### ISSUE THREAD

**Issue by aydjc** [termux/termux-packages#1795]
After change shell to zsh in **x86** device(such as Nokia N1 and XiaoMi Pad2), it doesn't recognize any regular expression such as `ls *.zsh`. Like below screen capture image shows:

![zsh](https://user-images.githubusercontent.com/722574/32822910-b70f4ff8-ca15-11e7-9c1f-8cbb261c9ddd.png)

**Comment by stephengroat** [comment]
@aydjc i tried this and couldn't replicate the situation. have you tried running `pkg up` to make sure everything's up to date?

**Comment by fornwall** [comment]
@aydjc I'm unable to reproduce it as well! As said above, try updating with `pkg up`, and if it still doesn't work note the output of running `zsh --version` here and we'll look at it!

**Comment by aydjc** [comment]
@stephengroat @fornwall  I've updated all packages, but zsh still **can't** works. The version of zsh is **5.4.2**, and my device is **Nokia N1, Android 5.1.1, Kernel 3.10.62-x86_64_moor, A5CNB19**  like below image shows:

![zsh2](https://user-images.githubusercontent.com/722574/33113882-3ce245e8-cf95-11e7-9f7a-dcdaeb4b0187.png)

**Comment by Grimler91** [comment]
@aydjc try reinstalling oh-my-zsh as well

**Comment by aydjc** [comment]
@Grimler91 It has nothing to do with `oh-my-zsh`, it is the bug of `zsh`. After uninstall `oh-my-zsh`, the bug still exist.
