### ISSUE TITLE
Without permission a+r Lambda development impossible

### ISSUE THREAD

**Issue by lucasgonze** [termux/termux-packages#1799]
It's not possible to set read permissions for other (or world) in termux, as far as I can tell. It's not possible to run javascript in Lambda file unless the file is world readable.

A Node app in Lambda needs to be packaged up in a zip file. AWS unzips on the server side. When it does that the 660 permissions in termux are restored. When node tries to read a Javascript file in the zip, it gets EACCESS.

Is there any workaround to the permissions issue? Is there a directory that is world-readable, where termux can support the permission bit? Is it possible to force the umask?

**Comment by vishalbiswas** [comment]
`chmod` doesn't work?

**Comment by lukeeey** [comment]
You can only run node in the internal storage. Android doesn't allow script execution in the sdcard.

**Comment by fornwall** [comment]
On internal storage (`$HOME`) world readable permission should work:

```sh
$ chmod a+r test.txt
$ ls -lha test.txt
-rwxr--r-- 1 u0_a269 u0_a269 16 Nov 21 05:01 test.txt
```

On shared storage Android does not allow world readable permission, and there is nothing Termux can do about it, unfortunately.

**Comment by lukeeey** [comment]
@fornwall Would this be possible with root or with a custom ROM?

**Comment by fornwall** [comment]
@lukeeey It's a limitiation with the file system - in theory a custom ROM could do something about that, but I don't know if anyone does unfortunately.

**Comment by lucasgonze** [comment]
What happens when you chmod a+r and it doesn't work? Better to fail fast
and make the issue transparent to developers.

In my case it was days of debugging to figure out why Lambda code packaged
in a zip file via the Serverless framework was failing. As it turns out
Serverless is creating a zip file which has no chance of ever working and
then failing silently.

**Comment by alexgalli** [comment]
Wow - stumbled on this thread after many hours of Googling, the first describing precisely what I was encountering.  In my case, it was running `aws cloudformation package` in termux on a Chromebook to upload a Node.js Lambda function to S3, but I imagine the same applies for serverless, etc.

This is indeed an issue with the default umask.  I did two things to fix this:

1) move my project directory into the termux home (previously had it in shared storage)
2) set `umask 022` before running `aws cloudformation package`

Problem solved.
