### ISSUE TITLE
cannot install netpbm : version number does not start with digit

### ISSUE THREAD

**Issue by cswl** [termux/termux-packages#18]
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/netpbm_r2592_arm.deb (--unpack):
 parsing file '/data/data/com.termux/files/usr/var/lib/dpkg/tmp.ci/control' near line 5 package 'netpbm':
 error in 'Version' field string 'r2592': version number does not start with digit
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/netpbm_r2592_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

due to this line..  maybe

https://github.com/termux/termux-packages/blob/master/packages/netpbm/build.sh
TERMUX_PKG_VERSION=r${_SVN_REVISION}

**Comment by fornwall** [comment]
Thanks, this has now been fixed and netpbm should be installable after an `apt update`!
