### ISSUE TITLE
[Bug]: libprotobuf, missing symbol, fixed in upstream 

### ISSUE THREAD

**Issue by romanovj** [termux/termux-packages#18002]
### Problem description

After building onnx

```
~/onnx $ python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/home/onnx/onnx/__init__.py", line 12, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: dlopen failed: cannot locate symbol "__emutls_v._ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E" referenced by "/data/data/com.termux/files/home/onnx/onnx/onnx_cpp2py_export.cpython-311.so"...
```
```
nm libprotobuf.so | grep thread_cache_
no symbols
```

Error is gone after fixing these files by applying upstream patch
```
src/google/protobuf/arena.cc
src/google/protobuf/thread_safe_arena.h 
```
Description https://github.com/protocolbuffers/protobuf/commit/4329fde9cf3fab7d1b3a9abe0fbeee1ad8a8b111

after rebuilding with fix
```
nm libprotobuf.so | grep thread_cache_
0000000000096440 R __emutls_t._ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E
0000000000272db8 D __emutls_v._ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E
```

### What steps will reproduce the bug?

Build and import onnx https://github.com/onnx/onnx

### What is the expected behavior?

Should import

### System information

termux-info:

```

```

**Comment by symmetricalbyte** [comment]
is there any guide to install onnx on termux

**Comment by romanovj** [comment]
@symmetricalbyte onnx, onnxruntime, onnxruntime-training?

**Comment by symmetricalbyte** [comment]
> @symmetricalbyte onnx, onnxruntime, onnxruntime-training?

the one in `pip install onnx`, to use with python scripts

**Comment by romanovj** [comment]
@symmetricalbyte this issue and https://github.com/termux/termux-packages/issues/18007 should be enough to install onnx

**Comment by romanovj** [comment]
fixed!
