### ISSUE TITLE
[Package]: `apt-build`

### ISSUE THREAD

**Issue by Rudxain** [termux/termux-packages#18008]
### Why is it worth to add this package?

> (Apologies in advance, if this is a dupe)

Since Android is usually installed on mobile devices (devs which strongly depend on battery power, and are usually slower than their bulkier non-portable counterparts), it's recommended that packs should be optimized for the specific CPU that the user owns. This is the main reason why A.R.T. does AOT+JIT.

Since all packs from the official source-repo are OSS, and most of them are compilable, this implies it's worth adding APTB, as the instances where APTB is no-op are rare

### Home page URL

https://packages.debian.org/sid/apt-build

### Source code URL

http://deb.debian.org/debian/pool/main/a/apt-build/apt-build_0.12.49.tar.xz

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

If I understood correctly, for this pack to work properly, an extra line must be added to `sources.list` which must start with "deb-src". For that to work, the official main repo must provide src files.

I also considered `apt-src`, but that's more targeted at developers than consumers (regular users)

**Comment by romanovj** [comment]
you can build all packages yourself
https://github.com/termux/termux-packages/wiki/Building-packages

**Comment by Rudxain** [comment]
> not compatible with Debian build system and there is no plan to make it compatible.

Thanks for the info. I was doing more research, and it seems like, in the _hypothetical_ case that it was supported, the server **storage-use would double,** which is a "big no-no" considering the low capacity.

> Termux was not meant to mimic Debian.

Thanks for clarifying, but I already know that. Termux is just a "relatively-minimal" Linux-like environment, not a distro.

> The `apt` was just original choice of a package manager.

I suggested `apt-build` mostly for the sake of consistency, as `apt` and `pkg` are the default P.M.s . The "core" (essentials) part of my request is to make it easier for users to locally optimize packs using `-march=native` (or similar flags).

> Termux build system was and will be distribution-agnostic.

And I appreciate that!

> you can build all packages yourself

Thanks for the link! I think that's a much better solution, as it doesn't add workload to maintainers, and doesn't require server storage. I haven't read the build scripts yet, so IDK if local builds are generic or host-tuned.

BTW, I've been reading [this](https://stackoverflow.com/questions/52653025/why-is-march-native-used-so-rarely), so now I'm convinced `apt-build` isn't worth the hassle
