### ISSUE TITLE
[Bug]: Docker run error http invalid host header

### ISSUE THREAD

**Issue by 2253856133** [termux/termux-packages#18017]
### Problem description

已经编译完内核 运行dockerd 不报错 但是run hello-world 报错
http invalid host header

### What steps will reproduce the bug?

运行 hello world

### System information

termux-info:

```

```

**Comment by 2096779623** [comment]
Official language of all Termux repos is English.

**Comment by 2096779623** [comment]
https://github.com/docker/cli/issues/4437

**Comment by romanovj** [comment]
fix:

edit /data/data/com.termux/files/usr/etc/docker/daemon.json

replace unix:.. with localhost

start containers with 
`sudo docker -H localhost:2375`

for example
`sudo docker -H localhost:2375 run -it debian`
