### ISSUE TITLE
[Bug]: gtkconfig.h is not found

### ISSUE THREAD

**Issue by boatsky** [termux/termux-packages#18012]
### Problem description

When I use include gtk.h,clangd error:In included file: 'glibconfig.h' file not found.I cd /usr/include/glib-xx.xx and it have not glibconfig.h .

### What steps will reproduce the bug?

```c
#include <gtk4.0/gtk/gtk.h>
```
or
ln -s gtk4.0/* . and use 
```c
#include <gtk/gtk.h>
```

### What is the expected behavior?

#include <glib-x.x/glibconfig.h>

### System information

termux-info:

```

```

**Comment by licy183** [comment]
`glibconfig.h` exists in `/data/data/com.termux/files/usr/lib/glib-2.0/include/glibconfig.h`.
