### ISSUE TITLE
Why xorg-twm is Never Use Xubuntu (Ubuntu Xfce4 Desktop + Ubuntu Look Like Xubuntu)

### ISSUE THREAD

**Issue by BBCByComcast** [termux/termux-packages#18065]
I Can't Install xorg-twm in Xubuntu Because When Using a VNC, It's Been Black/Blank Screen, However Without Proot Distro Can Install xorg-twm, Any Problem?

**Comment by twaik** [comment]
It is not a termux problem. Xubuntu is a third-party distro that we offer zero support for.

**Comment by BBCByComcast** [comment]
It's a True @twaik There a Xubuntu Termux in a Internet, Like a YouTube, Google, Snaptube, Facebook, Instagram, X And More, Will You Solve Me?

**Comment by twaik** [comment]
Xubuntu is not Termux product and we do not offer support for it.
