### ISSUE TITLE
How about add  --enable-delay-pools configure option to squid

### ISSUE THREAD

**Issue by Sak94664** [termux/termux-packages#1807]
If it is enabled,then i can decrease bandwidth occupation.(I'm using a public server to forward proxy port inside home network,but home network cannot forward inbound port)(to secure public wifi  connection)
Thanks!

**Comment by vishalbiswas** [comment]
Is there anything more you would like? Squid has quite a lot of options.

**Comment by Sak94664** [comment]
@vishalbiswas I configured squid with delay pools,but it doesn't work.I checked  "https://wiki.squid-cache.org/Features/DelayPools",it said that configure it with --enable-delay-pools to enable this feature,
Hope to add it.^_^

**Comment by vishalbiswas** [comment]
I have added it in #1809, I was asking whether do you require any other options, too?

**Comment by Sak94664** [comment]
@vishalbiswas  There's no need to add more features,thanks!

**Comment by fornwall** [comment]
The updated package is now available for installation!
