### ISSUE TITLE
Why `build-package` checks PM rather than `uname`?

### ISSUE THREAD

**Issue by Rudxain** [termux/termux-packages#18080]
I stumbled upon this:

https://github.com/termux/termux-packages/blob/81c0f6166a3fe1c60ed4f8e49f75d001d848f1fe/build-package.sh#L364C4-L368C4

And I was wondering why not simply do...?
```bash
export TERMUX_ARCH="$(uname -m)"
```

Is it because the script must be "perfectly aligned" to whatever architecture the PMs use?

**Comment by licy183** [comment]
`uname -m` doesn't show arch correctly on ARM devices.

```
$ uname -m
armv8l
```

**Comment by Rudxain** [comment]
> `uname -m` doesn't show arch correctly on ARM devices.
> 
> ```
> $ uname -m
> armv8l
> ```

I'm sorry. On my device it printed `aarch64`, so I assumed there was no problem.

It seems `uname` is more specific, while the PMs are coded to "just say if it's 32b or 64b, and whether it's arm or x86".

I think it would be nice to add a little source-comment explaining that (or link to existing docs)
