### ISSUE TITLE
[Package]: kitty-terminfo

### ISSUE THREAD

**Issue by glensc** [termux/termux-packages#18094]
### Why is it worth to add this package?

In debian kitty has terminfo subpackage:

```
Thu Feb 16 13:38:07 2023 kitty-terminfo_0.13.3-1+deb10u1_all
Thu Feb 16 13:38:08 2023 kitty_0.13.3-1+deb10u1+b4_armhf
Thu Feb 16 13:38:09 2023 kitty-doc_0.13.3-1+deb10u1_all
```

```
$ dpkg --listfiles kitty-terminfo
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/kitty-terminfo
/usr/share/doc/kitty-terminfo/changelog.Debian.gz
/usr/share/doc/kitty-terminfo/changelog.gz
/usr/share/doc/kitty-terminfo/copyright
/usr/share/terminfo
/usr/share/terminfo/x
/usr/share/terminfo/x/xterm-kitty
```

the purpose of that is to connect to the host with TERM=xterm-kitty, but without having to install kitty with x11 dependencies.

in termux project, it would require even enabling x11-packages repository.

### Source code URL

https://github.com/termux/termux-packages/blob/cab4e4ca3da987728f4dc391eceec480e2e4deaf/x11-packages/kitty/build.sh

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

I'm not sure does termux support subpackages (probably does), but does it support subpackages across repositories? probably not.

therefore it makes sense to create new kitty-terminfo package in main repository?

I'm willing to add the package myself, if it's to be accepted.

**Comment by glensc** [comment]
also, seems the existing kitty package in termux, doesn't even package kitty-terminfo file (it removes it?)
- https://github.com/termux/termux-packages/blob/cab4e4ca3da987728f4dc391eceec480e2e4deaf/x11-packages/kitty/build.sh#L18C18-L18C29

**Comment by TomJo2000** [comment]
We prune some rarely used legacy `terminfo` entries for space savings.
Kitty's should probably be included.

**Comment by glensc** [comment]
@TomJo2000 no, you do not understand, I do not want to install x11 packages, and installing kitty. I need only the terminfo.

**Comment by TomJo2000** [comment]
In that case it should be sufficient to copy it from your Debian system into Termux's terminfo directory.

**Comment by glensc** [comment]
@TomJo2000 this is package request not support forum. if i want to hack system manually, I wouldn't opened the issue!

**Comment by glensc** [comment]
however, seems kitty terminfo is installed in ncurses package:
- https://github.com/termux/termux-packages/blob/cab4e4ca3da987728f4dc391eceec480e2e4deaf/packages/ncurses/build.sh#L15

but the kitty version is outdated:
- https://github.com/termux/termux-packages/blob/cab4e4ca3da987728f4dc391eceec480e2e4deaf/packages/ncurses/build.sh#L9

current is 0.30.0:
- https://github.com/kovidgoyal/kitty/releases/tag/v0.30.0

so, need to bump version in ncurses package.

**Comment by glensc** [comment]
https://github.com/termux/termux-packages/pull/18095

**Comment by glensc** [comment]
> We do not offer hacking support.

it was you who insisted on hacking my system by copying files manually to $PREFIX/usr. I wanted to do this in pristine way, hence this issue requesting subpackage. 

this is no longer relevant, as I found the kitty termiinfo is packaged by ncurses package. it just was outdated.

**Comment by TomJo2000** [comment]
Expecting users to be comfortable to modify their terminfo database if they require a terminfo file not provided by default does not constitute "hacking".
It is just like tweaking any other system configuration file.

Please be aware that as mentioned `ncurses` is already in the process of being updated, and your proposed PR should be addressed already by that.
