### ISSUE TITLE
Termux /tmp involved in the openssh-server installation under chroot[Bug]: 

### ISSUE THREAD

**Issue by bJsH688** [termux/termux-packages#18108]
### Problem description

 chroot debian won't be installed properly with termux due to the bug caused by Termux when installing  openssh-server.. However, openssh-server can be installed properly with ConnectBot. Thus, it is confirmed that bug is Termux error. 
The debootstrap package may also generate errors because it stuck during first stage while installing Devuan.

### What steps will reproduce the bug?

1) root android 13 with Magisk;
2) install Termux then debootstrap;
3) mkdir and goto (chroot dir)
3) install rootfs with debootstrap --arch arm64 bookworm . ; (devuan stuck.)
4) chroot . /bin/su
5) export path
then,
 https://bogeskov.dk/DebianAndroid.html
https://ivonblog.com/en-us/posts/termux-chroot-ubuntu/
next install openssh-server dead here

### System information

termux-info:

```

```
cannot install openssh-server with termux error comes up!

**Comment by twaik** [comment]
Termux has `debootstrap` package, but it is not responsible for the way you are configuring your chroot environment. After chrooting to environment everything that happens there is on your responsibility.

**Comment by romanovj** [comment]
you should chroot with
`chroot . /bin/su -`
with "chroot . /bin/su" you are havin environet vars from termux and android
