### ISSUE TITLE
How to build a deb package?

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-packages#1812]
How can I convert a `debian deb` package for a `termux`?
Give detailed instructions, Let's say I want to install the [IPtables](https://packages.debian.org/ru/wheezy/iptables-persistent) package or [Netfilter-queue-dev](https://packages.debian.org/sid/libnetfilter-queue-dev) how can I install them for Termux ?

**Comment by Grimler91** [comment]
No, it's not possible, see https://wiki.termux.com/wiki/Package_Management#Installing_.deb_files. Packages in termux has to be cross compiled for its specific environment. Hence you would need to follow the instructions in the read me and properly package the packages.

See also https://github.com/termux/termux-packages/issues/714.

**Comment by Grimler91** [comment]
@Deathlive maybe you are asking about how to properly cross-compile and package a package into a deb for termux. 

For that, see the https://github.com/termux/termux-packages/blob/master/README.md on how to setup the build environment (on a system that supports docker, not on device) and then start looking at all the existing build.sh scripts to see how to write one for the package you want to cross-compile. 

Some packages are really easy to package (thanks to the excellent build-package.sh script), for example https://github.com/termux/termux-packages/blob/master/packages/libopus/build.sh, while others requires more work, see for example https://github.com/termux/termux-packages/blob/master/packages/python/build.sh.
