### ISSUE TITLE
[Bug]: sabnzbd=4.1.0 missing dependency python-sabyenc3=7.1.2

### ISSUE THREAD

**Issue by macearl** [termux/termux-packages#18165]
### Problem description

The newly released sabnzbd 4.1.0 package does not work as the python-sabyenc3 package was updated to 8.0.0 and not 7.1.2. 

Sabnzbd version bump: https://github.com/termux/termux-packages/commit/38e8ff9edaae04dc340140fbb42264c4d546aeeb

python-sabyenc3 version bump: https://github.com/termux/termux-packages/commit/e0e8fc062fd82855cd6d66d46f17759b09910622

The necessary python-sabyenc3 version was increased on September 29th in the upstream repository: https://github.com/sabnzbd/sabnzbd/commit/182a5412a571fb6a4e6ba3f793465a0386cb48d0

But version 4.1.0 was released 3 days prior to that: https://github.com/sabnzbd/sabnzbd/releases/tag/4.1.0

Error message
```
2023-10-06 22:12:46,806::INFO::[notifier:123] Sending notification: Error - SABCTools disabled: no correct version found! (Found v8.0.0, expecting v7.1.2) (type=error, job_cat=None)
2023-10-06 22:12:46,805::ERROR::[sabnzbd:427] SABCTools disabled: no correct version found! (Found v8.0.0, expecting v7.1.2)
```

The package should probably be downgraded again or both versions should be kept in the repository

### What steps will reproduce the bug?

Install sabnzbd and start it. 

### What is the expected behavior?

sabnzbd should start. 

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=29309
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.dev/apt/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.39.1
Android version:
13
Kernel build information:
Linux localhost 4.9.337-perf-g8a93d901b11c #1 SMP PREEMPT Mon Oct 2 15:09:10 UTC 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
POCO F1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by truboxl** [comment]
sabnzbd has been updated to 4.2.0 via #18890
