### ISSUE TITLE
Package request: Nim

### ISSUE THREAD

**Issue by shfrs** [termux/termux-packages#1816]
**Nim** is a systems and applications programming language. Statically typed and compiled, it provides unparalleled performance in an elegant package.
https://nim-lang.org

**Comment by sdrausty** [comment]
It looks like Nim is currently available in Termux through Arch Linux PRoot.  This script is designed to install Arch Linux in just a few keystrokes. Tapping this link https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh will transfer `setupTermuxArch.sh` to your device. Simply run `bash setupTermuxArch.sh` to install Arch Linux in Termux.  To install use `pacman -S nim` and this will install Nim on device.  

![screenshot_20171130-000520](https://user-images.githubusercontent.com/27742457/33415055-3bf620c8-d562-11e7-8c20-94498be1b29f.png)

**Comment by its-pointless** [comment]
Just for completeness i have a pull request for nim and its available on my repo. Its also possible to build this on device...

**Comment by xeffyr** [comment]
Nim is available for installation. `pkg install nim`.
