### ISSUE TITLE
[Bug]: Can't install rust; `pkg upgrade` tries to remove it if it's already installed (libllvm too new)

### ISSUE THREAD

**Issue by Rhys-T** [termux/termux-packages#18164]
### Problem description

I was trying to run `pkg upgrade`, and discovered that apt wanted to remove rust for some reason. I eventually figured out that libllvm was trying to upgrade to version 17.x, and rust was still 1.72.1 and wouldn't work with that. (See also #17751, #18027.) Since `pkg` uses `apt full-upgrade` rather than `apt upgrade`, it's willing to uninstall any package that gets in the way of upgrading other packages.

If I move `.../usr` aside and relaunch to get a fresh prefix, I can't install rust at all because of the version mismatch.

For now, I've used `apt-mark hold libllvm` to make it ignore that upgrade (and the matching clang, etc. upgrades) and go ahead with everything else. I'll run `apt-mark unhold libllvm` once the new version of rust is available.

(I wasn't sure whether to file this as a 'bug report', or a 'package request' for the new version of rust. I went with 'bug report' because of the effect it was having on upgrading, but feel free to change it if that wasn't right.)

### What steps will reproduce the bug?

With rust (and libllvm 16) already installed:
```console
$ pkg upgrade
```

Without rust installed (e.g. in fresh prefix):
```console
$ pkg install rust
```

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=19358
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.quantum5.ca/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.quantum5.ca/termux/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
clang/stable 17.0.2-1 aarch64 [upgradable from: 16.0.6-2]
libcompiler-rt/stable 17.0.2-1 aarch64 [upgradable from: 16.0.6-2]
libllvm/stable 17.0.2-1 aarch64 [upgradable from: 16.0.6-2]
libltdl/stable 2.4.7-1 aarch64 [upgradable from: 2.4.7]
libsmartcols/stable 2.39.2-1 aarch64 [upgradable from: 2.39.2]
libtool/stable 2.4.7-1 aarch64 [upgradable from: 2.4.7]
libuuid/stable 2.39.2-1 aarch64 [upgradable from: 2.39.2]
libx11/stable 1.8.7 aarch64 [upgradable from: 1.8.6]
libxpm/x11 3.5.17 aarch64 [upgradable from: 3.5.16]
lld/stable 17.0.2-1 aarch64 [upgradable from: 16.0.6-2]
llvm/stable 17.0.2-1 aarch64 [upgradable from: 16.0.6-2]
openssh-sftp-server/stable 9.5p1 aarch64 [upgradable from: 9.4p1-1]
openssh/stable 9.5p1 aarch64 [upgradable from: 9.4p1-1]
perl/stable 5.38.0-2 aarch64 [upgradable from: 5.38.0-1]
psmisc/stable 23.6-2 aarch64 [upgradable from: 23.6-1]
util-linux/stable 2.39.2-1 aarch64 [upgradable from: 2.39.2]
virglrenderer/x11 1.0.0 aarch64 [upgradable from: 0.10.4-2]
termux-tools version:
1.39.1
Android version:
13
Kernel build information:
Linux localhost 4.19.113-27114284 #1 SMP PREEMPT Fri Aug 11 10:06:51 +07 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T970
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.x11 versionCode:14
com.termux.api versionCode:51
com.termux.styling versionCode:30
```

**Comment by twaik** [comment]
We are updating packages, it will be fixed soon.

**Comment by Rhys-T** [comment]
Sounds good. Just wanted to check, and include the workaround I was using in case anyone else was having that problem.

**Comment by finagolfin** [comment]
As you found, the rust package needs to be updated, and probably will be in the next day.
