### ISSUE TITLE
[Package]: Update to BorgBackup to 1.2.6 (latest)

### ISSUE THREAD

**Issue by quickishfm** [termux/termux-packages#18162]
### Why is it worth to add this package?

The included version of BorgBackup is quite old and has some issues, which the new versions should fix.

### Source code URL

https://github.com/borgbackup/borg

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by quickishfm** [comment]
It turns out this can be upgraded outside of `pkg upgrade borgbackup` by issuing `pip install --upgrade borgbackup`. While it would be nice to have it officially upgraded in the Termux repo, this does the job.

**Comment by TomJo2000** [comment]
Termux mostly follows the [PEP-0668](https://peps.python.org/pep-0668/) proposal.
System packages should only be updated through `pkg` (or `apt`/`pacman`) directly.
