### ISSUE TITLE
[Package]: editor to remove voice (karaoke) from audio?

### ISSUE THREAD

**Issue by AmericaPacific42** [termux/termux-packages#18170]
### Why is it worth to add this package?

~21 years ago, Windows had an editor for everyone with Realtek motherboard audio that would allow to remove vocals from audio.
No network, local editor;
https://www.reddit.com/r/audio/comments/wpr8eu/realtek_hd_audio_manager_karaoke_option_setting/
Ubuntu has good editors to remove vocals from audio (not 21 years ago, as Windows. Just around 11 years ago):
https://askubuntu.com/questions/456021/remove-vocals-from-mp3-and-get-only-instrumentals
>Try out [Audacity](https://apps.ubuntu.com/cat/applications/audacity/). You can find it in the Ubuntu Repositories. To remove vocals

But for all of the programs on Goog's repo, you have to pay to upload your audio to a third-party AI server to remove voices from your audio.
Can you add a local 1 to Termux' repo?
Don't care what 1, just want to remove vocals from audio.
Don't have to support playback, can just pass audio through shared folders to Termux and back. VLC-Android supports all audio.

### Source code URL

https://sourceforge.net/projects/audacity/?s=editing&i=remove-vocals

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by AmericaPacific42** [comment]
>To have a live removal of vocals from a stereo recording we can add a [LADSPA filter](https://askubuntu.com/questions/43950/how-can-i-apply-a-ladspa-plugin-to-a-pulseaudio-stream) as a sound output to pulseaudio. There is a quite good karaoke plugin from the [Steve Harris' LADSPA](http://plugin.org.uk/ladspa-swh/docs/ladspa-swh.html#tth_sEc2.61)

**Comment by AmericaPacific42** [comment]
https://manpages.ubuntu.com/manpages/focal/en/man1/sox.1.html#oops
>has an option for karaoke:
    oops
    Out Of Phase Stereo effect. Mixes stereo to twin-mono where each mono channel contains the difference between the left and right stereo channels. This is sometimes known as the ‘karaoke’ effect as it often has the effect of removing most or all of the vocals from a recording.

So from command line this ...

sox song.wav music.wav oops

**Comment by AmericaPacific42** [comment]
All lyrics in all videos (whether music videos or education) is bad    for your mental health and you should remove it from audio.

**Comment by truboxl** [comment]
Sox is already packaged and can be installed with `pkg install sox`

Audacity doesn't  playback during editing so you need to export it to to verify, see #10412
