### ISSUE TITLE
Auto update failing for walk

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#18176]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the walk package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating walk [Current version: 1.6.2]
ERROR: No 'latest-release-tag' found (https://api.github.com/repos/antonmedv/walk/releases/latest).
Try using 'newest-tag'.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-10-07 12:18:14 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/6441018677">6441018677</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by landfillbaby** [comment]
seems the owner deleted or renamed their github account, same one as #18175

**Comment by AyushSinghRawat-hub** [comment]
try to Update the Package Manually

**Comment by landfillbaby** [comment]
we can't. we don't know where the source is anymore

**Comment by twaik** [comment]
Maybe we should remove both packages?
I checked alpine, archlinux and fedora are fetching upstream source from the same github account as we do. The same thing is relevant to `walk` and AUR/Homebrew.

**Comment by twaik** [comment]
As far as I understand termuxbot2 will open new issues with same topic.
