### ISSUE TITLE
[Bug]: Problems with procps (3.3.17-3)

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#18180]
### Problem description

There are issues with pgrep and pkill
since upgrade to procps (3.3.17-3) from procps (3.3.17-2)

### What steps will reproduce the bug?

It's not easy for me to come up with an example. 
Following are the extracts from the manual.

-f, --full
      The pattern is normally only matched against the
      process name.  When -f is set, the full command
      line is used.

-x, --exact
      Only match processes whose names (or command
      lines if -f is specified) exactly match the
      pattern.

When using both pgrep -x and pkill -x both of these commands are behaving as of the -f option was used.

### What is the expected behavior?

Both pgrep and pkill commands should behave as per manual.

They do not.
I have reverted to procps (3.3.17-2) and this has resolved the issues.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=10572
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.termux.dev/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirror.termux.dev/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://mirror.termux.dev/termux-x11 x11 main
Updatable packages:
procps/stable 3.3.17-3 aarch64 [upgradable from: 3.3.17-2]
termux-tools version:
1.39.1
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Fri Nov 26 00:14:01 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.boot versionCode:7
com.termux.styling versionCode:30
com.termux.widget versionCode:12
com.termux.window versionCode:15

```

**Comment by truboxl** [comment]
https://github.com/termux/termux-packages/commit/b470466432643683c7515da885575ecd035f3946

**Comment by macerg** [comment]
Ok, --full is the default but -x no longer works!

**Comment by fornwall** [comment]
@macerg Thanks for reporting this!

I reverted (https://github.com/termux/termux-packages/pull/18184) the changed behaviour, so `3.3.17-4` (available shortly once the build is done) will restore the original behaviour.

We need to change pgrep&pkill to avoid looking arg the executable file name (as that will always almost be `/system/bin/linker64` once https://github.com/termux/termux-exec/pull/24 lands), but that will be done in a future way, to only switch `executable filename` -> `argv0` - we shouldn't match on all command-line arguments by default.

**Comment by macerg** [comment]
Happy to help!
