### ISSUE TITLE
How can i start apache2 in termux

### ISSUE THREAD

**Issue by rajuhax** [termux/termux-packages#1818]
Tell me sir how can i do that

**Comment by rafinetiz** [comment]
Use command
`apachectl start`

**Comment by Grimler91** [comment]
Closing this due to lack of information.

**Comment by Cvar1984** [comment]
ar1984@localheart:~$ apachectl start
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
(20014)Internal error (specific information not available): AH00058: Error retrieving pid file var/run/apache2/httpd.pid
AH00059: Remove it before continuing if it is corrupted.

**Comment by rafinetiz** [comment]
rm $PREFIX/var/run/apache2/httpd.pid

and try again

**Comment by Cvar1984** [comment]
Address already in use: AH00072: make_sock: could not bind to address [::]:8080
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:8080
no listening sockets available, shutting down
AH00015: Unable to open logs

**Comment by coldmow** [comment]
If you run `apachectl -t -D DUMP_INCLUDES` , it will show you the patch to your httpd.conf 
I don't know how much that'll help, I havent figured out myself how to rum Apache2 in Termux either, but I hope people will come closer with this.

**Comment by emahuni** [comment]
has someone done this? I think this has something to do with the path. Most packages expect /var/.... but we don't have that.

**Comment by Hax4us** [comment]
Do `echo "ServerName localhost" >> /data/data/com.termux/files/usr/etc/apache2/httpd.conf`
Then
`apachectl start `

**Comment by HussainiMagaji** [comment]
I am having the problem too. I want to run python cgi scripts but its not working even with python3 http server

**Comment by AmiyKumar** [comment]
> I am having the problem too. I want to run python cgi scripts but its not working even with python3 http server

I am also having the same problem
It just opens python files.

**Comment by SigmaRS** [comment]
Not working.

**Comment by xeffyr** [comment]
@SigmaRS What is not working ? Which error did you get ?

**Comment by HussainiMagaji** [comment]
Apache server on termux.
Here's the error:

(20014)Internal error (specific information not available): AH00058: Error retrieving pid file var/run/apache2/httpd.pid
AH00059: Remove it before continuing if it is corrupted.

Also removing the above "httpd.pid" causes another error because it constains form set-ups for the server.
Thanks.

**Comment by 011235813213455** [comment]
I got it to work.... thx to Hax4us and OhNyZsh faje root 😅😎😍😍😍

**Comment by HussainiMagaji** [comment]
How do you manage that?

**Comment by 011235813213455** [comment]
@HussainiMagaji

Hax4us got me the reason to work... kill (pid) in my case it was 20307 and then i set the servername to localhost like Hax4us

**Comment by AHvibrator** [comment]
When i did like Hax4us,i get this error:

AH00534: httpd: Configuration error: No MPM loaded.

I use of termux in android

**Comment by 011235813213455** [comment]
https://httpd.apache.org/docs/current/de/mpm.html

Please read the instructions for MPM's

Greez n cheerz

Am Sa., 2. März 2019, 22:00 hat AHvibrator <notifications@github.com>
geschrieben:

**Comment by remo7777** [comment]
https://hindux.github.io/setup-apache-server-in-termux/
