### ISSUE TITLE
[Bug]: Clang updates to 17.0.2 without corresponding libc++, causing troubles.

### ISSUE THREAD

**Issue by SainoNamkho** [termux/termux-packages#18203]
### Problem description

I found #17863 is still in progress. But there's an update for clang 17.0.2.

Before this update, I wrote patches like (successfully built with `clang++ -std=c++2b`)
```c++
#include <type_traits>
#include <utility>

namespace std {
#ifndef __cpp_lib_forward_like
template<class T, class U>
[[nodiscard]] constexpr auto&& forward_like(U&& x) noexcept
{
    constexpr bool is_adding_const = std::is_const_v<std::remove_reference_t<T>>;
    if constexpr (std::is_lvalue_reference_v<T&&>) {
        if constexpr (is_adding_const) {
            return std::as_const(x);
        }
        else {
            return static_cast<U&>(x);
        }
    }
    else {
        if constexpr (is_adding_const) {
            return std::move(std::as_const(x));
        }
        else {
            return std::move(x);
        }
    }
}
#endif
}

int main()
{
    static_cast<void>(std::forward_like<int>(1));
}
```
to temporary make STL functions that should be implemented but not available in the old ndk libc++ in use, hoping that I can smoothly switch to the new clang when update is available.

But after the update, clang++ reports
```
test.cpp:32:27: error: function 'forward_like<int, int>' with deduced return type cannot be used before it is defined
   32 |   static_cast<void>(std::forward_like<int>(1));
      |                          ^
test.cpp:7:32: note: 'forward_like<int, int>' declared here
    7 | [[nodiscard]] constexpr auto&& forward_like(U&& x) noexcept
      |                                ^
1 error generated.
```

The old clang don't have these functions but allow me to add them, and the new clang still don't have them while don't allow adding them to the std namespace. Will this be fixed by the upcoming ndk update? Or should I roll back the clang version before the ndk update is availvable?

**Comment by licy183** [comment]
`forward_like` has been a builtin since clang-17. You can workaround it by passing `-fno-builtin-std-forward_like`. See https://github.com/llvm/llvm-project/issues/64029.

**Comment by SainoNamkho** [comment]
> `forward_like` has been a builtin since clang-17. You can workaround it by passing `-fno-builtin-std-forward_like`. See [llvm/llvm-project#64029](https://github.com/llvm/llvm-project/issues/64029).

Thanks a lot! So it seems there's not as many things broken as I imagined at first. I'm keeping this issue open for a another few days to see if it works stably.
