### ISSUE TITLE
php mysqli extension not working with apache2

### ISSUE THREAD

**Issue by rafinetiz** [termux/termux-packages#1820]
I tried running a web server using php + apache2 + php7 for apache module but unfortunately mysqli extension not include in this php,
so i installed php-mysql package and i already write
`extension=mysqli.so` to php.ini

When i tried running this script with `php` command
```
<?php
$mysqli = mysqli_init();
```
In terminal it's give me no error
But when i tried running in browser it's give me fatal error
```
Fatal error: Uncaught Error: Call to undefined function mysqli_init() in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/test.php:8 Stack trace: #0 {main} thrown in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/test.php on line 8
```

**Comment by vishalbiswas** [comment]
did you specify that php.ini file using `-c` flag to php?

**Comment by rafinetiz** [comment]
I am using default path of php.ini
`$PREFIX/lib/php.ini`

**Comment by vishalbiswas** [comment]
I don't think we have a default location for php.ini files.
You'll need to use other methods to manually specify your php.ini -> http://php.net/manual/en/configuration.file.php

**Comment by vishalbiswas** [comment]
Sorry, for false info.
I can confirm that php-mysql doesn't work with apache2.
nginx seems to be working.

Do you get any errors in log files?

**Comment by rafinetiz** [comment]
i'm sorry but i already remove apache2 packages from termux last night.
Ok, i'll try using nginx.

**Comment by vishalbiswas** [comment]
Please update to php-7.1.12-1 package. php-mysql is built into the php package now, so, you don't need to have an entry for it in your `php.ini`

**Comment by ckpakbar** [comment]
Tetew
