### ISSUE TITLE
Auto update failing for cronie

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#18237]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the cronie package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating cronie [Current version: 1.6.1]
INFO: package being updated to 1.7.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  265k  100  265k    0     0   499k      0 --:--:-- --:--:-- --:--:--  499k

You are about to commit these changes:

--------------------
diff --git a/packages/cronie/build.sh b/packages/cronie/build.sh
index 18c54c611..bddd943a9 100644
--- a/packages/cronie/build.sh
+++ b/packages/cronie/build.sh
@@ -3,10 +3,9 @@ TERMUX_PKG_DESCRIPTION="Daemon that runs specified programs at scheduled times a
 TERMUX_PKG_LICENSE="ISC, BSD 2-Clause, BSD 3-Clause, GPL-2.0, LGPL-2.1"
 TERMUX_PKG_LICENSE_FILE="COPYING, COPYING.obstack"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="1.6.1"
-TERMUX_PKG_REVISION=1
+TERMUX_PKG_VERSION="1.7.0"
 TERMUX_PKG_SRCURL=https://github.com/cronie-crond/cronie/releases/download/cronie-${TERMUX_PKG_VERSION}/cronie-${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=2cd0f0dd1680e6b9c39bf1e3a5e7ad6df76aa940de1ee90a453633aa59984e62
+TERMUX_PKG_SHA256=6827f5a47760cc64afeef0a60d3cb5376f52569109fc9a73957dd5e9fdae7619
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
 TERMUX_PKG_DEPENDS="dash"
--------------------

bump(main/cronie): 1.7.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package cronie exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building cronie for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  42945      0 --:--:-- --:--:-- --:--:-- 43062
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2600      0 --:--:-- --:--:-- --:--:--  2595
100   833  100   833    0     0   2599      0 --:--:-- --:--:-- --:--:--  2595
gpg: Signature made Fri 13 Oct 2023 08:22:59 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  23068      0 --:--:-- --:--:-- --:--:-- 23084
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2911      0 --:--:-- --:--:-- --:--:--  2912
100   833  100   833    0     0   2910      0 --:--:-- --:--:-- --:--:--  2912
gpg: Signature made Thu 12 Oct 2023 06:47:21 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  24837      0 --:--:-- --:--:-- --:--:-- 24848
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1554      0 --:--:-- --:--:-- --:--:--  1554
100   833  100   833    0     0   1553      0 --:--:-- --:--:-- --:--:--  1551
gpg: Signature made Thu 12 Oct 2023 07:45:42 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency dash@0.5.12 if necessary...
Found dash in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/d/dash/dash_0.5.12_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 65180  100 65180    0     0   349k      0 --:--:-- --:--:-- --:--:--  349k
extracting dash to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/cronie-crond/cronie/releases/download/cronie-1.7.0/cronie-1.7.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  265k  100  265k    0     0   622k      0 --:--:-- --:--:-- --:--:--  622k
Applying patch: fix-default-environment.patch
Applying patch: fix-hardcoded-paths.patch
1 out of 1 hunk FAILED -- saving rejects to file configure.rej
1 out of 1 hunk FAILED -- saving rejects to file src/pathnames.h.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-10-13 12:30:46 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/6507981875">6507981875</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by twaik** [comment]
Fixed by 902a6731aa133f9d87925bd1f4976bc630823399 .
