### ISSUE TITLE
Auto update failing for progress

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#18235]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the progress package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating progress [Current version: 0.16]
INFO: package being updated to 0.17.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 60357    0 60357    0     0  99368      0 --:--:-- --:--:-- --:--:-- 99368

You are about to commit these changes:

--------------------
diff --git a/packages/progress/build.sh b/packages/progress/build.sh
index 46fba0fca..0b759351c 100644
--- a/packages/progress/build.sh
+++ b/packages/progress/build.sh
@@ -2,10 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://github.com/Xfennec/progress
 TERMUX_PKG_DESCRIPTION="Linux tool to show progress for cp, mv, dd and more"
 TERMUX_PKG_LICENSE="GPL-3.0"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION=0.16
-TERMUX_PKG_REVISION=1
+TERMUX_PKG_VERSION="0.17"
 TERMUX_PKG_SRCURL=https://github.com/Xfennec/progress/archive/v$TERMUX_PKG_VERSION.tar.gz
-TERMUX_PKG_SHA256=59944ee35f8ae6d62ed4f9b643eee2ae6d03825da288d9779dc43de41164c834
+TERMUX_PKG_SHA256=ee9538fce98895dcf0d108087d3ee2e13f5c08ed94c983f0218a7a3d153b725d
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
 TERMUX_PKG_DEPENDS="libandroid-wordexp, ncurses"
--------------------

bump(main/progress): 0.17

Not committing to Git!

INFO: Trying to build package.
INFO: Package progress exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building progress for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  20278      0 --:--:-- --:--:-- --:--:-- 20268
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1519      0 --:--:-- --:--:-- --:--:--  1517
100   833  100   833    0     0   1519      0 --:--:-- --:--:-- --:--:--  1517
gpg: Signature made Fri 13 Oct 2023 12:23:07 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  4 1531k    4 63465    0     0  68778      0  0:00:22 --:--:--  0:00:22 68759
100 1531k  100 1531k    0     0  1163k      0  0:00:01  0:00:01 --:--:-- 1163k
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  23465      0 --:--:-- --:--:-- --:--:-- 23450
100 13320  100 13320    0     0  23427      0 --:--:-- --:--:-- --:--:-- 23409
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2973      0 --:--:-- --:--:-- --:--:--  2975
gpg: Signature made Thu 12 Oct 2023 06:47:21 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  23626      0 --:--:-- --:--:-- --:--:-- 23597
100 13120  100 13120    0     0  23622      0 --:--:-- --:--:-- --:--:-- 23597
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1573      0 --:--:-- --:--:-- --:--:--  1574
gpg: Signature made Thu 12 Oct 2023 07:45:42 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency libandroid-wordexp@0.1 if necessary...
Found libandroid-wordexp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-wordexp/libandroid-wordexp_0.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3566  100  3566    0     0   6430      0 --:--:-- --:--:-- --:--:--  6436
extracting libandroid-wordexp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses@6.4.20231001-1 if necessary...
Found ncurses in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-utils@6.4.20231001-1 if necessary...
Found ncurses-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs@6.4.20231001-1 if necessary...
Found ncurses-ui-libs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs-static@6.4.20231001-1 if necessary...
Found ncurses-ui-libs-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs-static to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/Xfennec/progress/archive/v0.17.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 60357    0 60357    0     0   142k      0 --:--:-- --:--:-- --:--:--  142k
Applying patch: Makefile.patch
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-10-13 12:30:43 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/6507981875">6507981875</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by twaik** [comment]
Fixed by c6572cd328f9c1979de1d9bfdb8cffc9e9367d54
