### ISSUE TITLE
Apache2 server's service not running!!!!

### ISSUE THREAD

**Issue by rajuhax** [termux/termux-packages#1824]
Sir I am getting his error message.....
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message

Please sir help me

**Comment by Grimler91** [comment]
Hi, 

That looks like a warning. Isn't the server working in spite of this message?

**Comment by Quasic** [comment]
I always get that message. I have more success ignoring it than trying to use a hostname.

**Comment by Quasic** [comment]
My comment was cut off. How do you know the server isn't running? Could it simply not be serving pages properly?

**Comment by fornwall** [comment]
@rajuhax Closing this issue - check if the server may be running in the background and let us know if not!

**Comment by Abdulwaqeel** [comment]
Background not running termux app
