### ISSUE TITLE
[Bug]: Clang-tidy dosent find headers properly

### ISSUE THREAD

**Issue by 32bitguy2c1** [termux/termux-packages#18240]
### Problem description

Hi, i have noticed that clang-tidy isnt working as it should because it errors out with it weirdly not finding headers while clang does that properly with no issue.
The error in question (in a simple c file, it varies depending on what you try to include) is: 

`
Error while processing /data/data/com.termux/files/home/test.c.
/data/data/com.termux/files/usr/include/sys/types.h:32:10: error: 'stddef.h' file not found [clang-diagnostic-error]
   32 | #include <stddef.h>
      |          ^~~~~~~~~~
`

### What steps will reproduce the bug?

just run clang-tidy, on a c++/c file, i tested it for example on a simple c file:
`
#include <stdio.h>
int main() {
  puts("Test");
  return 0;
}  ` 
It errored out while clang compiled it fine.

### What is the expected behavior?

For it to not exit because of weird header errors.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=11885
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.39.1
Android version:
9
Kernel build information:
Linux localhost 4.9<REDACTED> #1 SMP PREEMPT Tue Jun <REDACTED> armv8l Android
Device manufacturer:
<REDACTED>
Device model:
<REDACTED>
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
com.termux.window versionCode:15
```

**Comment by landfillbaby** [comment]
https://github.com/llvm/llvm-project/issues/63890 ?

**Comment by landfillbaby** [comment]
```sh
$clang-tidy --extra-arg=--print-resource-dir /dev/null
[...]
lib/clang/17
[...]
$clang --print-resource-dir
/data/data/com.termux/files/usr/lib/clang/17
```
somehow clang-tidy is stripping the $PREFIX?
