### ISSUE TITLE
'omp.h' file is still missed in clang

### ISSUE THREAD

**Issue by ashindin** [termux/termux-packages#1826]
It seems that in the last clang package there is libomp.a file but the header file (omp.h) is still missed.
I copy omp.h from clang-openmp sources (openmp-5.0.0.src/runtime/src/include/50/omp.h.var) and can build some openmp examples.

**Comment by its-pointless** [comment]
Yeah this is annoying, it can be simply copied from ndk.

**Comment by fornwall** [comment]
Thanks - this has been fixed in version `16-5` of the ndk-sysroot package which is installed automatically as a clang dependency - update to it by running `pkg up`!
