### ISSUE TITLE
[Package]: Terminal Radio (TERA)

### ISSUE THREAD

**Issue by catanadj** [termux/termux-packages#18273]
### Why is it worth to add this package?

Hi!

This package is an interactive music radio player that can play thousands of stations from around the planet, directly in the terminal.

Thank you

### Home page URL

https://tera.codewithshin.com/

### Source code URL

https://github.com/shinokada/tera

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by TomJo2000** [comment]
Yep, and all the dependencies (`bash`, `mpv`, `jq`, `fzf`, `gh` and `wget`) are already packaged as well.

You can just install this by cloning the source repo and running the `tera` script contained in its top level directory.
It doesn't seem to do its own dependency checks though.
Which is fair enough considering its a simple 160 line Bash script.

**Comment by catanadj** [comment]
Did try to clone the repo but getting the following error during the execution of the script. 
"/data/data/com.termux/files/home/tera-0.4.1/lib/lib.sh: line 128: /tmp/tera_error: No such file or directory
Something went wrong. Please see /tmp/tera_error"

I've assumed that it must have something to do with the Termux environment because on Linux there is no issue.

**Comment by TomJo2000** [comment]
> Did try to clone the repo but getting the following error during the execution of the script. "/data/data/com.termux/files/home/tera-0.4.1/lib/lib.sh: line 128: /tmp/tera_error: No such file or directory Something went wrong. Please see /tmp/tera_error"
> 
> I've assumed that it must have something to do with the Termux environment because on Linux there is no issue.

You should be able to replace `/tmp` with `${TMPDIR}` and then it should work.
Termux doesn't have access to the system tmp directory so it has its own at `/data/data/com.termux/files/usr/tmp` that directory string is available through the `TMPDIR` environment variable for brevity.
