### ISSUE TITLE
[Bug]: libgpgmepp missing (today's update). It is a poppler dependency.

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#18284]
### Problem description

After today's update, programs that use poppler may fail to launch correctly. Evince, Gimp, etc. Error message from Evince:
```
(evince:9335): EvinceDocument-WARNING **: 13:26:44.374: dlopen failed: library "libgpgmepp.so" not found: needed by /data/data/com.termux/files/usr/lib/libpoppler.so in namespace (default)
```

### What steps will reproduce the bug?

Any launch of a program that uses poppler.

### What is the expected behavior?

Previously launched without problem. Expected no problem.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://plug-mirror.rcac.purdue.edu/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.1
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22626479 #1 SMP PREEMPT Mon Jan 9 15:48:32 KST 2023 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T510
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:49
com.termux.styling versionCode:29
```

**Comment by truboxl** [comment]
Zzz somebody put the dependency wrongly and didn't test. There is a difference between `gpgme` and `gpgmepp`.

Please install `gpgmepp` as a temporary workaround

**Comment by twaik** [comment]
It is pretty weird, I thought I revbumped all the dependencied shown by `apt-cache rdepends poppler poppler-qt | sort | uniq`

**Comment by twaik** [comment]
Yeah, I see my mistake. It is pretty weird since poppler configuring script asked for gpgme, not gpgmepp.

**Comment by twaik** [comment]
The fix will be available soon.
