### ISSUE TITLE
[Package]: Add extension tablefunc to postgresql

### ISSUE THREAD

**Issue by Kuret** [termux/termux-packages#18292]
### Why is it worth to add this package?

We currently use the tablefunc extension in some of our databases. It is nornally part of postgresql/contrib.

I'm trying to see if I can create a portable dev machine using Samsung DeX, and can't proceed until I can run the database.

### Home page URL

https://www.postgresql.org/docs/current/tablefunc.html

### Source code URL

https://doxygen.postgresql.org/tablefunc_8c_source.html

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
Pull requests are always welcome.
