### ISSUE TITLE
[Bug]: espeak: shared memfd open() failed: Unknown error 22

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#18295]
### Problem description

Running espeak results in this error being given twice and no audio:
`shared memfd open() failed: Unknown error 22`

It does this regardless of the selected voice. My pulseaudio works with other apps.

### What steps will reproduce the bug?

```
~ $ espeak hi
shared memfd open() failed: Unknown error 22
shared memfd open() failed: Unknown error 22
```

### What is the expected behavior?

espeak speaks

### System information

Espeak version: 1.51-1

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=26172
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.1
Android version:
11
Kernel build information:
Linux localhost 4.4.223-g52750b8f2138-ab6846512 #1 SMP PREEMPT Fri Sep 18 09:49:34 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 2
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.boot versionCode:7
com.termux.widget versionCode:13
com.termux.window versionCode:15

```

**Comment by licy183** [comment]
Hello, please test the deb files in https://github.com/termux/termux-packages/actions/runs/6570731736. Thanks!

**Comment by sudomain** [comment]
Seems to work, thank you! So I installed those deb files manually using `apt install -f`. Will I still recieve upgrades to pulseaudio when I do `pkg up`?

**Comment by licy183** [comment]
> Will I still recieve upgrades to pulseaudio when I do `pkg up`?

Yes, packages will be uploaded to apt repository soon.
