### ISSUE TITLE
Unknown argument --licenses

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#1830]
On the latest master (b1e1a0b8), I get this error when running `./scripts/setup-android-sdk.sh`:
```
Error: Unknown argument --licenses
Usage: 
  sdkmanager [--uninstall] [<common args>] \
    [--package_file <package-file>] [<packages>...]
  sdkmanager --update [<common args>]
  sdkmanager --list [<common args>]

In its first form, installs, or uninstalls, or updates packages.
    <package> is a sdk-style path (e.g. "build-tools;23.0.0" or 
             "platforms;android-23").
    <package-file> is a text file where each line is a sdk-style path
                   of a package to install or uninstall.
    Multiple --package_file arguments may be specified in combination
     with explicit paths.
In its second form (with --update), currently installed packages are
    updated to the latest version.
In its third form, all installed and available packages are printed out.

Common Arguments:
    --sdk_root=<sdkRootPath>: Use the specified SDK root instead of the SDK containing this tool
    --channel=<channelId>: Include packages in channels up to <channelId>.
                           Common channels are:
                           0 (Stable), 1 (Beta), 2 (Dev), and 3 (Canary).

    --include_obsolete: With --list, show obsolete packages in the
                        package listing. With --update, update obsolete
                        packages as well as non-obsolete.
    --no_https: Force all connections to use http rather than https.
    --proxy=<http | socks>: Connect via a proxy of the given type.
    --proxy_host=<IP or DNS address>: IP or DNS address of the proxy to use.
    --proxy_port=<port #>: Proxy port to connect to.

* If the env var REPO_OS_OVERRIDE is set to "windows",
  "macosx", or "linux", packages will be downloaded for that OS.
```

**Comment by fornwall** [comment]
Could it be that you have an old sdk tools version in `$HOME/lib/android-sdk` where sdkmanager doesn't accept `--licenses`?

Could you try removing `$HOME/lib/android-sdk` and run `scripts/setup-android-sdk.sh` again and see if that fixes the problem?

**Comment by Rudloff** [comment]
I deleted and reinstalled the Android SDK Tools (25.2.5) and still get the same error.

**Comment by fornwall** [comment]
> I deleted and reinstalled the Android SDK Tools (25.2.5) and still get the same error.

Right, 25.2.5 is too old to accept `--licenses` - did you install it manually?

If you just delete `$HOME/lib/android-sdk` and run `setup-android-sdk.sh` directly after it should automatically install a 26.0.1 version. Does that work?

**Comment by Rudloff** [comment]
Deleting the whole folder worked.
I'm not sure why the `android` tool didn't update itself to 26...

**Comment by sdrausty** [comment]
@Rudloff great work.  Does not work.  Backup.  Delete.  Reinstall.  Perfect.

**Comment by sdrausty** [comment]
Unless we get something like `md5sum` for `setup-android-sdk.sh` @Rudloff error can repeat indefinitely.  How does one navigate https://dl.google.com/android/repository/ and similar directories at do? @fornwall  ?  This is a gamebraker, navigating dl.google.com.
