### ISSUE TITLE
[Package]: ffmpeg --enable-libopenmpt

### ISSUE THREAD

**Issue by vivimncer** [termux/termux-packages#18309]
### Why is it worth to add this package?

With the --enable-libopenmpt flag, ffmpeg can be used to play and convert various trackers files (.mod, xm, etc).

My personal (and hacky) use case is to use it together with mpd to decoding various tracker files on-the-fly.

### Home page URL

https://wiki.openmpt.org/Libopenmpt

### Source code URL

https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/libopenmpt.c

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by ngc6302h** [comment]
Wow! I was gonna make request just now but you've made it just 20 minutes earlier! What were the chances of something like this happening??

I subscribe to this request, please compile ffmpeg with libopenmpt!

**Comment by landfillbaby** [comment]
https://github.com/termux/termux-packages/commit/8f8bbced205bf852f9fcd288b360d85514165e63
done :)
