### ISSUE TITLE
[Bug]: edit default page

### ISSUE THREAD

**Issue by saeedadmin** [termux/termux-packages#18306]
### Problem description

How to edit default page termux for example instead this text : 
Welcome to Termux!

Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

Modify own text 

### What steps will reproduce the bug?

T

### System information

termux-info:

```

```
Android

**Comment by Grimler91** [comment]
You can edit $PREFIX/etc/motd

**Comment by saeedadmin** [comment]
> You can edit $PREFIX/etc/motd

How can i edit that?

**Comment by saeedadmin** [comment]
> You can edit $PREFIX/etc/motd

zsh: permission denied: /data/data/com.termux/files/usr/etc/motd
Error

**Comment by saeedadmin** [comment]
> You can edit $PREFIX/etc/motd

Thanks you i fixed it
