### ISSUE TITLE
Package request: qpdf

### ISSUE THREAD

**Issue by tomty89** [termux/termux-packages#1831]
http://qpdf.sourceforge.net

A very nice set of tool / library for pdf transformations / manipulations.  Good alternative / supplement to the poppler tools.

**Comment by JamesFinn** [comment]
Can you exact tell me which dependencies needed mingw?

**Comment by sdrausty** [comment]
It looks like qpdf is currently available in Termux through Arch Linux PRoot.  This script is designed to install Arch Linux in just a few keystrokes. Tapping this link https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh will transfer `setupTermuxArch.sh` to your device. Simply run `bash setupTermuxArch.sh` to install Arch Linux in Termux.  To install use `pacman -S qpdf` and this will install qpdf on device.  

![screenshot_20171130-000210](https://user-images.githubusercontent.com/27742457/33414957-c3d50a32-d561-11e7-997d-5ff04cbf3d7a.png)

**Comment by vishalbiswas** [comment]
Turns out it was quite easy to package this as I did in #1889 
If anybody wan't to try it out, tell me your arch and I'll provide a deb file.

**Comment by fornwall** [comment]
Thanks to @vishalbiswas the package is now available for installation: `pkg install qpdf`.

**Comment by Mark-Joy** [comment]
@fornwall 
Please update the package version.
Current available version: [10.3.2](https://github.com/qpdf/qpdf/releases/tag/release-qpdf-10.3.2) 
Package version on Termux: 10.0.1
There were some build errors during pikepdf installation which did not occur if latest version(10.3.2) is used.

**Comment by tomty89** [comment]
@Mark-Joy #7543 has been merged. Please see if it works for you, thanks!

**Comment by Mark-Joy** [comment]
@tomty89 Thanks a lot. It works alright!!
