### ISSUE TITLE
Get access to package manager(pkg) from adb

### ISSUE THREAD

**Issue by stasbar** [termux/termux-packages#1832]
Hello,
I'm wondering if there is some way to install package manager (pkg) to /system/xbin to be able to start it from other terminals and from adb ?
I tried to add _/data/data/com.termux/files/usr/bin/_ to _$PATH_ but it fails on 
```
angler:/ # pkg list-all
CANNOT LINK EXECUTABLE "apt": library "libapt-pkg.so.5.0" not found
Aborted
```

**Comment by Grimler91** [comment]
Hi, you need to set `LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib` as well, without it the shell only looks for libraries in the system location.

**Comment by notorand-it** [comment]
This is happening now with latest version.
Adding that variable setting doesn't help.
