### ISSUE TITLE
[Package]: postgresql 16.0

### ISSUE THREAD

**Issue by sans404-dev** [termux/termux-packages#18331]
### Why is it worth to add this package?

Add postgresql please

### Home page URL

https://www.postgresql.org/

### Source code URL

https://ftp.postgresql.org/pub/source/v16.0/postgresql-16.0.tar.bz2

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by TomJo2000** [comment]
Already packaged.
https://github.com/termux/termux-packages/blob/351d6cfebec0c6afaf9f206b71b993a495b5291d/packages/postgresql/build.sh#L1-L10
Though admittedly out of date.

**Comment by twaik** [comment]
Yeah, I failed to port patches. Need the review of package maintainers for newer version.
