### ISSUE TITLE
Cinnamon or MATE Desktop Environment Package Please (Unlocked)

### ISSUE THREAD

**Issue by BBCByComcast** [termux/termux-packages#18348]
There are many programs or tools that needs to be run on GUI because some of them uses GTK. Like w3af and many more. I hope that you can build this. Goodluck
(Termux-X11 Extra Package Repo Are Deleted, It's Now Transfer to That Repo)

**Comment by twaik** [comment]
What exactly are you talking about? GTK is available in `x11-repo` (`pkg i x11-repo` to install it), and there is `mate-desktop` package (in the same `x11-repo`).

Cinnamon is not available.
