### ISSUE TITLE
Auto update failing for upx

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#18350]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the upx package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating upx [Current version: 4.1.0]
INFO: package being updated to 4.2.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 1247k  100 1247k    0     0  2197k      0 --:--:-- --:--:-- --:--:-- 2197k

You are about to commit these changes:

--------------------
diff --git a/packages/upx/build.sh b/packages/upx/build.sh
index 12f05ddb0..a302df1cf 100644
--- a/packages/upx/build.sh
+++ b/packages/upx/build.sh
@@ -2,8 +2,8 @@ TERMUX_PKG_HOMEPAGE=https://upx.github.io/
 TERMUX_PKG_DESCRIPTION="the Ultimate Packer for eXecutables"
 TERMUX_PKG_LICENSE="GPL-2.0"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="4.1.0"
+TERMUX_PKG_VERSION="4.2.0"
 TERMUX_PKG_SRCURL=https://github.com/upx/upx/releases/download/v${TERMUX_PKG_VERSION}/upx-${TERMUX_PKG_VERSION}-src.tar.xz
-TERMUX_PKG_SHA256=0582f78b517ea87ba1caa6e8c111474f58edd167e5f01f074d7d9ca2f81d47d0
+TERMUX_PKG_SHA256=09b89fe127fbcb8222dc519badc8cc4da0b2f9f661f2d699d0b2a79e167161fa
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_DEPENDS="libc++"
--------------------

bump(main/upx): 4.2.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package upx exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building upx for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  43733      0 --:--:-- --:--:-- --:--:-- 43780
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1519      0 --:--:-- --:--:-- --:--:--  1517
100   833  100   833    0     0   1519      0 --:--:-- --:--:-- --:--:--  1517
gpg: Signature made Thu 26 Oct 2023 09:13:42 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  25353      0 --:--:-- --:--:-- --:--:-- 25371
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1605      0 --:--:-- --:--:-- --:--:--  1605
100   833  100   833    0     0   1604      0 --:--:-- --:--:-- --:--:--  1605
gpg: Signature made Mon 23 Oct 2023 08:41:27 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  23519      0 --:--:-- --:--:-- --:--:-- 23554
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1621      0 --:--:-- --:--:-- --:--:--  1620
gpg: Signature made Wed 25 Oct 2023 05:37:49 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency libc++@26b if necessary...
Found libc++ in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libc++ to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/upx/upx/releases/download/v4.2.0/upx-4.2.0-src.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 1247k  100 1247k    0     0  2186k      0 --:--:-- --:--:-- --:--:-- 2186k
Applying patch: src-util-snprintf.patch
1 out of 1 hunk FAILED -- saving rejects to file src/util/snprintf.h.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-10-26 12:36:02 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/6653800298">6653800298</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by twaik** [comment]
Closed by 06de3a5eac4be8e730efc3b1b368e56e693e80c0 .
