### ISSUE TITLE
[Bug]: glib-cross scripts can not be executed on host

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#18354]
### Problem description

`termux_step_massage` replaces shebangs in scripts so scripts in `glib-cross` can not be launched on PC.
```
aarch64-binfmt-P: Could not open '/system/bin/linker64': No such file or directory
```

### What steps will reproduce the bug?

Try to launch any of `gdbus-codegen glib-genmarshal glib-gettextize glib-mkenums gtester-report` in `${TERMUX_PREFIX}/opt/glib/cross/bin` on host.

### System information

.

**Comment by truboxl** [comment]
Can add enhancement to selectively exclude files from doing shebang fix

**Comment by twaik** [comment]
It will be perfect.
