### ISSUE TITLE
[upgpkg] Can not upgrade `mogan` to 1.1.6

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#18376]
Hi. I can nt upgrade mogan to `1.1.6` since it switched it's build system from `cmake` to `xmake`, not sure how to patch it to build it the right way. 
[APKBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mogan&id=49ebdf92e6721a9316521d8fed159a79065985a1) for reference of newer building way.

**Comment by Iey4iej3** [comment]
`1.2.0` is available now. I guess that it upgrades effortlessly.
