### ISSUE TITLE
[Mirror] Another termux mirror in Germany

### ISSUE THREAD

**Issue by SunRed** [termux/termux-packages#18398]
I have this mirror running for quite a while now and was recently reminded again to finally contribute my mirror to this project.
The server is running at Hetzner in Falkenstein/Vogtland, Germany with a 1Gb/s connection and support for both ipv4 and ipv6 and is available at https://mirror.sunred.org/termux/ with the following sources.list entries:
```
deb https://mirror.sunred.org/termux/termux-main stable main
deb https://mirror.sunred.org/termux/termux-root root stable
deb https://mirror.sunred.org/termux/termux-x11 x11 main
```

I check every two hours using `rsync` on the origin server.
Additionally there are 8 sync slots open for syncing with `rsync` and `rsync-ssl` using `rsync://sync.mirror.sunred.org/termux`. I may put the main domain behind a caching reverse proxy at some point, hence the use of a different domain for the sync endpoint.

Additionally I would like to know if it would be possible to provide a `lastupdate` file in the root of the mirror repo or in /termux-main/ where the `lastsync` file is located (or maybe move this one to the root as well) to indicate when one of the repos was actually last updated. This would make it possible to optionally sync a mirror more frequently but only when necessary. This is similar to how other linux distros like Arch Linux do it with a sync script like [here](https://gitlab.archlinux.org/archlinux/infrastructure/-/blob/master/roles/syncrepo/files/syncrepo-template.sh). With this I could e.g. check every 5-10 minutes more efficiently over http and only sync over rsync when packages were actually updated on the origin mirror.

**Comment by Grimler91** [comment]
Thanks! 

> Additionally I would like to know if it would be possible to provide a lastupdate file

Yeah, would be nice, it was suggested by some other mirror as well. Unfortunately I don't see a good way to implement it except for patching/hacking [aptly](https://github.com/aptly-dev/aptly) (which we use to control repo) to generate the file when publishing repo. Shouldn't be too hard I guess, but my golang skills are negligible

**Comment by Grimler91** [comment]
Opened a feature request: https://github.com/aptly-dev/aptly/issues/1229

**Comment by 2096779623** [comment]
Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-sunred) .

**Comment by Grimler91** [comment]
@SunRed there is now a lastupdate file at https://packages.termux.dev/apt/termux-main/lastupdate, it is generated by a cronjob that checks the date field in the Release file, every 5 minutes.

**Comment by SunRed** [comment]
Thanks for coming back to me about this. I adjusted my configuration and thus it should now check every 5 minutes and only do a full sync if necessary. :)
