### ISSUE TITLE
Auto update failing for clash

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#18403]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the clash package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating clash [Current version: 1.18.0]
ERROR: No 'latest-release-tag' found (https://api.github.com/repos/Dreamacro/clash/releases/latest).
Try using 'newest-tag'.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-11-03 06:26:50 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/6741843445">6741843445</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by 2096779623** [comment]
The author of clash no longer maintains it for some reasons and deletes this package.
