### ISSUE TITLE
Will you provide a symlink `apt` → `.` in your Rsync module?

### ISSUE THREAD

**Issue by iBug** [termux/termux-packages#18407]
We (University of Science and Technology of China) recently discovered the availability of Rsync from `packages.termux.dev` and switched our synching method to it. Our mirror service was previously serving from <https://mirrors.ustc.edu.cn/termux/apt/>, but the new directory layout no longer contains a layer of `apt` directory. With some Nginx trick, we're currently serving at both `/termux/` and `/termux/apt/`, while mirror sites at fellow universities are serving at either `/termux/` or `/termux/apt/` inconsistently (see [Mirrors](https://github.com/termux/termux-packages/wiki/Mirrors) wiki page).

We would therefore ask for a favor: Will you create a symlink at the root of your Rsync module, `apt -> .`, so that we don't have to rely on Nginx tricks (which is actually pretty reliable per se) while keeping both paths accessible?

To elaborate, here's the current layout of the top-level `termux` module:

```text
drwxr-xr-x  termux-main-21
drwxr-xr-x  termux-main
drwxr-xr-x  termux-root
drwxr-xr-x  termux-x11
```

And here's our desired layout:

```text
lrwxrwxrwx  apt -> .
drwxr-xr-x  termux-main-21
drwxr-xr-x  termux-main
drwxr-xr-x  termux-root
drwxr-xr-x  termux-x11
```

**Comment by Grimler91** [comment]
Hey, good suggestion, thanks for reaching out!

I have created the symlink, and verified that it is there when rsyncing. Please confirm that it works on your end

**Comment by iBug** [comment]
Thank you very much for your help. I can confirm we have the symlink on our receiving end and both paths are serving the files over HTTP.
