### ISSUE TITLE
[Bug]: charmbracelet gum doesn't work

### ISSUE THREAD

**Issue by eggbean** [termux/termux-packages#18420]
### Problem description

[Charmbracelet gum](https://github.com/charmbracelet/gum) doesn't work. I have been using it in a few of my scripts to suppress output and replace it with information on whether steps of the script and successful or not, but they are all failing on termux because the termux build of gum doesn't work. This is such a pain for me right now. I have not been using termux heavily since I started using `gum`, until now, so I don't know how long this has been happening.

### What steps will reproduce the bug?

Make a small script:

```
#!/bin/bash
sleep 7
echo foo
```

    $ gum spin --title "foo" -- ./foo.sh

This results in nothing happening and errorlevel 1.

    $ echo $?
    1

Do the same on a non-termux system and it will work.

### What is the expected behavior?

A little spinning character should appear for 7 seconds and then the word `foo`.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18951
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://md.mirrors.hacktegic.com/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://md.mirrors.hacktegic.com/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://md.mirrors.hacktegic.com/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.4
Android version:
13
Kernel build information:
Linux localhost 5.10.136-android12-9-27100597-abS901BXXS6CWI1 #1 SMP PREEMPT Wed Sep 13 11:05:29 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S901B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.tasker versionCode:6
com.termux.styling versionCode:29
```

**Comment by TomJo2000** [comment]
It would need to be compiled for Termux to work.
I can take a look at that after work, should be pretty straight forward.

**Comment by eggbean** [comment]
It would be great if you could have a look and see why it isn't working.

**Comment by eggbean** [comment]
A fix/workaround [was given to me here](https://github.com/termux/termux-packages/pull/11371#issuecomment-1794345462) and I have modified my scripts and they work now. They were working perfectly fine on non-termux systems all this time, so there is something different.
