### ISSUE TITLE
How to change Termux and Packages language ?

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-packages#1844]
Can I change the language of the Termux?

**Comment by Grimler91** [comment]
No, it is not currently possible. See for example https://github.com/termux/termux-app/pull/285.

**Comment by tik9** [comment]
Is it possible that one day this will work? Termux is my day to day tool!

**Comment by xeffyr** [comment]
@tik9 It is possible to do some localization for Termux app, but not for packages.
