### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "node": library "libicui18n.so.73" not found: needed by main executable

### ISSUE THREAD

**Issue by skaba04** [termux/termux-packages#18482]
### Problem description

This error showes up while installing nodejs

CANNOT LINK EXECUTABLE "node": library "libicui18n.so.73" not found: needed by main executable
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

### What steps will reproduce the bug?

pkg install nodejs

### System information

termux-info: Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=29224
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root/ root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.4
Android version:
13
Kernel build information:
Linux localhost 4.14.190-27200287-abA715FXXUADWH4 #1 SMP PREEMPT Mon Aug 21 20:01:41 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A715F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
~ $

**Comment by luisdavim** [comment]
same error here, tried uninstalling nodejs and installing again and that didn't help.

**Comment by licy183** [comment]
Should be fixed in commit 10f6aa880ba58406c709bcf3d7ac9b7247d4f481. Next I'll bump icu to 74 and revbump revdeps.

**Comment by GR3YH4TT3R93** [comment]
Still seems to be broken with same exact error as in original Issue

**Comment by twaik** [comment]
1. Pull request is not merged.
2. Mirror sync takes some time.

You should wait.

**Comment by skaba04** [comment]
I still do not know what to do.

**Comment by twaik** [comment]
1. Mirror sync takes some time.
2. `pkg up`.

**Comment by skaba04** [comment]
I will try that pkg upgrade tommorow. Hope it will be fixed.

**Comment by dnquinn** [comment]
Have the same problem, and pkg upgrade doesn't helps
