### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by hanlay** [termux/termux-packages#18494]
How can I solve this

`~ $ pkg update && pkg upgrade -y
Checking availability of current mirror:
[*] https://mirror.mwt.me/termux/main: ok
Hit:1 https://mirror.mwt.me/termux/main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Checking availability of current mirror:
[*] https://mirror.mwt.me/termux/main: ok
Hit:1 https://mirror.mwt.me/termux/main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
~ $ cd /storage/emulated/0/T                            .../0/T $ php bot.php
CANNOT LINK EXECUTABLE "php": library "libicuio.so.73" not found: needed by main executable
.../0/T $`

**Comment by hulaVUX** [comment]
Duplicated of #18482

**Comment by hanlay** [comment]
I found solution.

termux-change-repo

And then changing single.
Next update and upgrade.

**Comment by hulaVUX** [comment]
@hanlay, please read https://gist.github.com/hulaVUX/0c96bfe9ff179871c0d96f473a30efe7
