### ISSUE TITLE
[Bug]:  zenity / libicu 74 : CANNOT LINK EXECUTABLE "zenity": library "libicuuc.so.73" not found

### ISSUE THREAD

**Issue by domichbt** [termux/termux-packages#18524]
### Problem description

Running package zenity from termux-x11 or any program that calls on it produces the error:

`CANNOT LINK EXECUTABLE "zenity": library "libicuuc.so.73" not found: needed by /data/data/com.termux/files/usr/lib/libharfbuzz-icu.so in namespace (default)`

Package libicu 74.1 is installed and was recently bumped to 74 instead of 73. Seems similar to #18482 

### What steps will reproduce the bug?

Add termux-x11 repository:
`pkg install x11-repo`
Add zenity:
`pkg install zenity`
Run zenity:
`zenity`

### What is the expected behavior?

Console should answer `You must specify a dialog type. See 'zenity --help' for details` or similar message indicating zenity is working

### System information

termux-info:

```

Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7440
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.4
Android version:
13
Kernel build information:
Linux localhost 5.4.210-qgki-27114284-abT733XXU5CWI4 #1 SMP PREEMPT Mon Sep 25 18:02:15 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T733
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14

```

**Comment by truboxl** [comment]
The issue is harfbuzz-icu not rebuild, not zenity

**Comment by Asuka-pr8** [comment]
Is the problem fixed now?
Bcz I am still getting this error

**Comment by licy183** [comment]
> Is the problem fixed now? Because I am still getting this error

Please switch to the default mirror `packages-cf.termux.dev` and run `pkg up`.

**Comment by Asuka-pr8** [comment]
Thnx its working now

**Comment by Asuka-pr8** [comment]
Its back once again
However now its libicui18n.so.74 and libicu is 75.1

**Comment by Biswa96** [comment]
> Its back once again

It will be gone once again. Patience is all we need.
