### ISSUE TITLE
[Bug]: "svn diff --diff-cmd" + script using /usr/bin/env broken with Android 14

### ISSUE THREAD

**Issue by vinc17fr** [termux/termux-packages#18537]
### Problem description

With `svn diff`, I use the `--diff-cmd` option with my own diff utility, which is a script that runs an interpreter using `/usr/bin/env`. After the upgrade to Android 14, this is no longer working.

### What steps will reproduce the bug?

1. In `~/bin`, add a `mydiff` script that starts with `#!/usr/bin/env sh` (for this test, it doesn't need to do anything, i.e. it may contain just this line).
2. In a Subversion working copy, modify a file (in order to have an non-empty diff).
3. Run `svn diff --diff-cmd mydiff`.

### What is the expected behavior?

The `mydiff` script should be run. Instead, I get an error like
```
Index: perso/TODO
===================================================================
exec of 'mydiff' failed: No such file or directorysvn: E200012: 'mydiff' returned 255
```

Note that running `mydiff` from the shell does not give an error. The issue occurs only with `svn diff --diff-cmd mydiff`.

And if `mydiff` starts with `#!/bin/sh`, then `svn diff --diff-cmd mydiff` works fine.

Note about the use of `/usr/bin/env`: with the actual script, this is actually `#!/usr/bin/env zsh` with the goal of using the same script on various platforms (where `zsh` can be at various places).

### System information

termux-info:
```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=8143
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
Updatable packages:
command-not-found/stable 2.3.0-11 aarch64 [upgradable from: 2.3.0-10]
termux-tools version:
1.39.4
Android version:
14
Kernel build information:
Linux localhost 5.15.94-android13-8-27763874-abS918BXXU3BWJM #1 SMP PREEMPT Tue Oct 24 12:40:02 UTC 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S918B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by 2096779623** [comment]
It will work after executing `termux-fix-shebang ~/bin/mydiff` .
```bash
~/ntfs-3g-2022.10.3/ntfs-3g $ svn diff --diff-cmd $PREFIX/bin/mydiff                                            Index: tags/2022.10.3/mak                               ===================================================================                                             exec of '/data/data/com.termux/files/usr/bin/mydiff' failed: No such file or directorysvn: E200012: '/data/data/com.termux/files/usr/bin/mydiff' returned 255
~/ntfs-3g-2022.10.3/ntfs-3g $ vim $PREFIX/bin/mydiff
~/ntfs-3g-2022.10.3/ntfs-3g $ termux-fix-shebang $PREFIX/bin/mydiff
~/ntfs-3g-2022.10.3/ntfs-3g $ vim $PREFIX/bin/mydiff
~/ntfs-3g-2022.10.3/ntfs-3g $ svn diff --diff-cmd $PREFIX/bin/mydiff
Index: tags/2022.10.3/mak                               ===================================================================                                             a
```

**Comment by vinc17fr** [comment]
> It will work after executing `termux-fix-shebang $PREFIX/bin/mydiff` .

But this changes `/usr/bin/env` to `/data/data/com.termux/files/usr/bin/env`, thus will not work on other platforms (this is an issue when doing synchronization between platforms). A portable workaround (currently my choice) is to do:
```
#!/bin/sh
[ -n "$ZSH_VERSION" ] || exec zsh -f -- "$0" ${1+"$@"}
```

Anyway, the cause of the failure should be found, and this should be fixed if possible.

There are 2 things I'm wondering about:
1. What does `svn` do to cause the failure (which doesn't appear from a shell) with Android 14?
2. What changed between Android 13 and 14?

**Comment by 2096779623** [comment]
My device is currently on Android 14, so I don't know what broke it between Android 13 and 14 .

**Comment by vinc17fr** [comment]
> You can replace `/data/data/com.termux/files/usr/` with `$PREFIX` .

This doesn't work, neither under GNU/Linux nor in Termux.

**Comment by landfillbaby** [comment]
ok so we need to patch `apr_proc_create` to use `execve` instead of `fork` so that libtermux-exec fixes the shebang

**Comment by vinc17fr** [comment]
Wrapping other `exec` variants, `execvp` in particular, would be the right fix as `execvp` is commonly used. For instance, it is used by `mutt` too.

**Comment by agnostic-apollo** [comment]
Will be fixed when `termux-exec` pull is merged. Hopefully will be able to finish my changes today.

https://github.com/termux/termux-exec/pull/24/files#diff-64e599360efd9a8e1e30ff693edc041482fbffc75f9f9a3e9df363b956fcaade
