### ISSUE TITLE
Pkg install error

### ISSUE THREAD

**Issue by devilish-crow** [termux/termux-packages#18533]
### Problem description

I tried installing nodejs on a rooted Motorola edge 20 lite but I got:
"Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done                          The following additional packages will be installed:
  c-ares libicu resolv-conf
Suggested packages:
  clang make pkg-config python
The following NEW packages will be installed:
  c-ares libicu nodejs resolv-conf
0 upgraded, 4 newly installed, 0 to remove and 64 not upgraded.
Need to get 19.6 MB of archives.                           After this operation, 104 MB of additional disk space will be used.
Do you want to continue? [Y/n]                             Get:1 https://termux.mentality.rip/termux-main stable/main aarch64 resolv-conf aarch64 1.3 [976 B]
Get:2 https://termux.mentality.rip/termux-main stable/main aarch64 c-ares aarch64 1.22.0 [162 kB]
Get:3 https://termux.mentality.rip/termux-main stable/main aarch64 libicu aarch64 74.1+real74.1 [9720 kB]
Get:4 https://termux.mentality.rip/termux-main stable/main aarch64 nodejs aarch64 20.2.0-1 [9690 kB]
Fetched 19.6 MB in 58s (335 kB/s)
Selecting previously unselected package resolv-conf.
(Reading database ... 5795 files and directories currently installed.)
Preparing to unpack .../resolv-conf_1.3_aarch64.deb ...
Unpacking resolv-conf (1.3) ...
Selecting previously unselected package c-ares.
Preparing to unpack .../c-ares_1.22.0_aarch64.deb ...
Unpacking c-ares (1.22.0) ...
Selecting previously unselected package libicu.
Preparing to unpack .../libicu_74.1+real74.1_aarch64.deb ...
Unpacking libicu (74.1+real74.1) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_20.2.0-1_aarch64.deb ...
Unpacking nodejs (20.2.0-1) ...
Setting up resolv-conf (1.3) ...
Setting up libicu (74.1+real74.1) ...
Setting up c-ares (1.22.0) ...
Setting up nodejs (20.2.0-1) ...
**CANNOT LINK EXECUTABLE "node": library "libcrypto.so.3" not found: needed by main executable
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)**"

After I ran `dpkg --configure -a && install -m 755 /dev/null /usr/local/bin/udevadm` I got:
"Setting up nodejs (20.2.0-1) ...
**CANNOT LINK EXECUTABLE "node": library "libcrypto.so.3" not found: needed by main executable
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)**"

### What steps will reproduce the bug?

Try installing nodejs on a rooted device after giving storage permission. (with the tsu package installed)

### What is the expected behavior?

Installing nodejs normally.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
Updatable packages:
apt/stable 2.7.6 aarch64 [upgradable from: 2.3.13-3]
bash/stable 5.2.15-1 aarch64 [upgradable from: 5.1.12-2]
ca-certificates/stable 1:2023.08.22 all [upgradable from: 1:2021-10-26-0]
command-not-found/stable 2.3.0-10 aarch64 [upgradable from: 1.71]
coreutils/stable 9.4 aarch64 [upgradable from: 9.0]
curl/stable 8.4.0 aarch64 [upgradable from: 7.81.0]
dash/stable 0.5.12 aarch64 [upgradable from: 0.5.11.5]
debianutils/stable 5.14 aarch64 [upgradable from: 5.5]
dialog/stable 1.3-20230209-0 aarch64 [upgradable from: 1.3-20211214-0]
diffutils/stable 3.10 aarch64 [upgradable from: 3.8]
dos2unix/stable 7.5.1 aarch64 [upgradable from: 7.4.2]
dpkg/stable 1.22.1 aarch64 [upgradable from: 1.21.1]
ed/stable 1.19 aarch64 [upgradable from: 1.17-4]
findutils/stable 4.9.0-2 aarch64 [upgradable from: 4.8.0]
gawk/stable 5.3.0 aarch64 [upgradable from: 5.1.1]
gpgv/stable 2.4.3 aarch64 [upgradable from: 2.3.4]
grep/stable 3.11 aarch64 [upgradable from: 3.7-2]
gzip/stable 1.13 aarch64 [upgradable from: 1.11-3]
inetutils/stable 2.4-1 aarch64 [upgradable from: 1.9.4-12]
less/stable 633-1 aarch64 [upgradable from: 590]
libandroid-support/stable 28-3 aarch64 [upgradable from: 28-2]
libassuan/stable 2.5.6 aarch64 [upgradable from: 2.5.5]
libc++/stable 26b aarch64 [upgradable from: 23b-3]
libcap-ng/stable 2:0.8.3 aarch64 [upgradable from: 1:0.8.3-pre1-0]
libcrypt/stable 0.2-5 aarch64 [upgradable from: 0.2-3]
libcurl/stable 8.4.0 aarch64 [upgradable from: 7.81.0]
libevent/stable 2.1.12-2 aarch64 [upgradable from: 2.1.12]
libexpat/stable 2.5.0-1 aarch64 [upgradable from: 2.4.2]
libgcrypt/stable 1.10.2 aarch64 [upgradable from: 1.9.4]
libgmp/stable 6.3.0 aarch64 [upgradable from: 6.2.1]
libgnutls/stable 3.8.1 aarch64 [upgradable from: 3.6.16-1]
libgpg-error/stable 1.47 aarch64 [upgradable from: 1.43]
libiconv/stable 1.17 aarch64 [upgradable from: 1.16-3]
libidn2/stable 2.3.4 aarch64 [upgradable from: 2.3.2]
liblz4/stable 1.9.4 aarch64 [upgradable from: 1.9.3]
liblzma/stable 5.4.5 aarch64 [upgradable from: 5.2.5-1]
libmpfr/stable 4.2.1 aarch64 [upgradable from: 4.1.0]
libnettle/stable 3.9.1 aarch64 [upgradable from: 3.7.3]
libnghttp2/stable 1.58.0 aarch64 [upgradable from: 1.46.0]
libssh2/stable 1.11.0 aarch64 [upgradable from: 1.10.0]
libtirpc/stable 1.3.4 aarch64 [upgradable from: 1.3.2]
libunistring/stable 1.1 aarch64 [upgradable from: 0.9.10-5]
lsof/stable 4.99.0 aarch64 [upgradable from: 4.94.0-1]
nano/stable 7.2 aarch64 [upgradable from: 6.0]
ncurses/stable 6.4.20231001-2 aarch64 [upgradable from: 6.2.20200725-6]
openssl/stable 1:3.1.4 aarch64 [upgradable from: 1.1.1l]
pcre2/stable 10.42 aarch64 [upgradable from: 10.39-2]
procps/stable 3.3.17-5 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.6-2 aarch64 [upgradable from: 23.4]
readline/stable 8.2.1 aarch64 [upgradable from: 8.1.1]
sed/stable 4.9-1 aarch64 [upgradable from: 4.8-2]
tar/stable 1.35 aarch64 [upgradable from: 1.34]
termux-am-socket/stable 1.5.0 aarch64 [upgradable from: 1.02]
termux-am/stable 0.6.0 all [upgradable from: 0.4]
termux-exec/stable 1:1.0 aarch64 [upgradable from: 1:0.9]
termux-keyring/stable 3.11 all [upgradable from: 2.4]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-1]
termux-tools/stable 1.39.4 all [upgradable from: 0.155]
unbound/stable 1.19.0 aarch64 [upgradable from: 1.13.2-1]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-7]
util-linux/stable 2.39.2-1 aarch64 [upgradable from: 2.37.2-1]
xxhash/stable 0.8.2 aarch64 [upgradable from: 0.8.1]
xz-utils/stable 5.4.5 aarch64 [upgradable from: 5.2.5-1]
zlib/stable 1.3 aarch64 [upgradable from: 1.2.11-5]
Android version:
12
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Mon Jun 26 16:52:56 CDT 2023 aarch64 Android
Device manufacturer:
motorola
Device model:
motorola edge 20 lite
```

**Comment by romanovj** [comment]
`yes | pkg upgrade`

**Comment by devilish-crow** [comment]
> `yes | pkg upgrade`

Ok, I thought it was because my custom bootloader.

**Comment by devilish-crow** [comment]
It worked.

**Comment by devilish-crow** [comment]
Fixed
