### ISSUE TITLE
[Bug]: can't install ntfs-3g

### ISSUE THREAD

**Issue by Tochees** [termux/termux-packages#18538]
### Problem description

After I install ntfs-3g, it still notice me to install ntfs-3g.

### What steps will reproduce the bug?

mkfs.ntfs
pkg install ntfs-3g
![Screenshot_2023-11-19-14-00-35-134_com termux](https://github.com/termux/termux-packages/assets/99777243/5762a141-012d-48f4-8d30-c9eeb8711127)

### System information

termux-info:

```

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=6436
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://termux.librehat.com/apt/termux-root root stable
Updatable packages:
command-not-found/stable 2.3.0-11 aarch64 [upgradable from: 2.3.0-10]
termux-tools version:
1.39.4
Android version:
13
Kernel build information:
Linux localhost 4.14.186-perf-ge57d707f8a4b #1 SMP PREEMPT Wed May 31 13:05:20 UTC 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
21121119SC
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by romanovj** [comment]
broken symlink
/data/data/com.termux/files/usr/bin/mkfs.ntfs -> /bin/mkntfs

fix
`ln -sf $PREFIX/bin/mkntfs $PREFIX/bin/mkfs.ntfs`

**Comment by 2096779623** [comment]
BTW, Can it really mount an ntfs formatted USB flash drive on termux?
