### ISSUE TITLE
NPM ERR! Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by trusktr** [termux/termux-packages#1855]
https://github.com/npm/npm/issues/19265

Is this a Termux-specific issue maybe?

**Comment by trusktr** [comment]
It happens with both nodejs and nodeks-current on Pixel 2

**Comment by fornwall** [comment]
The comment at https://github.com/npm/npm/issues/19265#issuecomment-347997389 says that this has been fixed in the `worker-farm` dependency that npm uses, so it will be available after an npm update. So I'm closing this in favour of tracking the problem at https://github.com/npm/npm/issues/19265.

**Comment by trusktr** [comment]
Thanks @fornwall. How do I perform an "npm update". For example, if I run `npm i -g npm` it will fail because of this error, so I can not update npm. Do we need to update the nodejs termux package?

**Comment by fornwall** [comment]
@trusktr Right, we will have to wait for an updated nodejs version to bring in the npm fix.

**Comment by fornwall** [comment]
I guess the best workaround is to apply https://github.com/rvagg/node-worker-farm/commit/0b2349c6c7ed5c51e234e418fad226875313e773 locally by hand, if possible.

**Comment by Quasic** [comment]
You can alternatively set it to the number of virtual CPUs you have, (or the number of concurrent workers you want, if that's different.) This fix will effectively disable concurrent workers when receiving this error. If you like, you can try [WIP] https://github.com/Quasic/cpuinfo node package to find the number. I hope to turn this into a fix that will still use concurrent workers.

**Comment by MrClan** [comment]
@trusktr How did you solve this issue? I still get this same error on pixel2 for node 9.6.1 and npm 5.6.0

**Comment by MrClan** [comment]
@trusktr Perfect, thanks. Just as @fornwall  suggestd, hard coded the value 8, like this: *maxConcurrentWorkers: 8* in  _/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js_ and issue solved.

**Comment by lukechilds** [comment]
For anyone else that runs into this, just:

```shell
$ apt-get install yarn
$ yarn add global npm
```

Now `npm` will work.

**Comment by LEI** [comment]
Regarding the last command, the correct order to install globally is :

    yarn global add npm

**Comment by lukechilds** [comment]
Thanks @LEI I updated my comment with your typo fix.

It's unfortunate that it doesn't do the trick for everyone.

**Comment by KMayne** [comment]
Just do this
```
pkg install yarn
yarn global add npm
npm i -g npm
```

**Comment by nsdevaraj** [comment]
In termux node doesn't return the value properly for the os.cpus() that's why the error happens on the file 
/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js
Just edit the above mentioned file with maxConcurrentWorkers value set as 1

**Comment by Tymski** [comment]
None of this works for me

**Comment by EamonnMR** [comment]
If you grep the error log (`/data/data/com.termux/files/home/.npm/_logs/*debug.log`) for a line with `farm.js` you can find the right file to edit.

**Comment by hussainb** [comment]
I can see the changes `|| { length: 1 }` already present in farm.js but it still throws the error

**Comment by xeffyr** [comment]
@hussainb It has these lines by default:
``` .js
const DEFAULT_OPTIONS = {
           workerOptions               : {}
         , maxCallsPerWorker           : Infinity
        , maxConcurrentWorkers        : (require('os').cpus() || { length: 1 }).length
         , maxConcurrentCallsPerWorker : 10
         , maxConcurrentCalls          : Infinity
, maxCallTime : Infinity // exceed this and the whole worker is terminated
```

But `cpus()` will throw TypeError on latest Android versions. You need to replace entire `(require('os').cpus() || { length: 1 }).length` with 1.

***
Patch:
``` .diff
--- /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js.orig
+++ /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js
@@ -3,7 +3,7 @@
 const DEFAULT_OPTIONS = {
           workerOptions               : {}
         , maxCallsPerWorker           : Infinity
-        , maxConcurrentWorkers        : (require('os').cpus() || { length: 1 }).length
+        , maxConcurrentWorkers        : 1
         , maxConcurrentCallsPerWorker : 10
         , maxConcurrentCalls          : Infinity
, maxCallTime : Infinity // exceed this and the whole worker is terminated
```
