### ISSUE TITLE
[Package]: openjdk-21

### ISSUE THREAD

**Issue by MatteoBax** [termux/termux-packages#18572]
### Why is it worth to add this package?

openjdk-17 is already 2 years old

### Home page URL

https://openjdk.org/projects/jdk/

### Source code URL

https://github.com/openjdk/jdk

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by MatteoBax** [comment]
Ok

**Comment by twaik** [comment]
Duplicate of #17978
