### ISSUE TITLE
[Package]: gitea-act_runner

### ISSUE THREAD

**Issue by urain39** [termux/termux-packages#18583]
### Why is it worth to add this package?

gitea.com/gitea/act_runner:
> Act runner is a runner for Gitea based on Gitea fork of act.

github.com/nektos/act:
> Run your GitHub Actions locally!

### Source code URL

https://gitea.com/gitea/act_runner

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

Gitea Actions is still under development, so there may be some bugs and missing features. And breaking changes may be made before it's stable (v1.20 or later).

If the situation changes, we will update it [here](https://docs.gitea.com/usage/actions/overview). So please refer to the content here when you find outdated articles elsewhere.

**Comment by twaik** [comment]
Github Actions should not run on Android devices. Even in the case if user has root (for docker or lxc) most actions require x86_64 host so it will not be compatible.
