### ISSUE TITLE
[Package]: go-tuf

### ISSUE THREAD

**Issue by rc-chuah** [termux/termux-packages#18599]
### Why is it worth to add this package?

Go implementation of The Update Framework (TUF)

This is a Go implementation of The Update Framework (TUF), a framework for securing software update systems.

### Home page URL

https://theupdateframework.com

### Source code URL

https://github.com/theupdateframework/go-tuf

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by Jeffhaji6** [comment]
> ### Why is it worth to add this package?
> 
> Go implementation of The Update Framework (TUF)
> 
> This is a Go implementation of The Update Framework (TUF), a framework for securing software update systems.
> 
> ### Home page URL
> 
> https://theupdateframework.com
> 
> ### Source code URL
> 
> https://github.com/theupdateframework/go-tuf
> 
> ### Packaging policy acknowledgement
> 
> - [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.
> 
> ### Additional information
> 
> _No response_

- [ ]
