### ISSUE TITLE
[Bug]: Segmentation Fault in gh

### ISSUE THREAD

**Issue by mcagabe19** [termux/termux-packages#18619]
### Problem description

![Screenshot_20231202_192733_VPhoneGaGa](https://github.com/termux/termux-packages/assets/82843871/8ed415ce-a1bd-4145-be2f-24b573a10128)

### What steps will reproduce the bug?

using armv7 termux

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/com.termux-2/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=12304
TERMUX_APP__SE_FILE_CONTEXT=u:r:untrusted_app:s0:c512,c768
TERMUX_APP__SE_INFO=default
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app:s0:c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10035
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+3b5018b
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+3b5018b
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.5
Android version:
7.1.2
Kernel build information:
Linux localhost 4.14.42-titan #34 SMP PREEMPT Sat Nov 9 17:05:30 CST 2019 armv8l Android
Device manufacturer:
samsung
Device model:
SM-S918B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by truboxl** [comment]
`gdb` or `lldb` or `logcat` traces needed

**Comment by mcagabe19** [comment]
@truboxl here!!
![Screenshot_20231207_124221_VPhoneGaGa](https://github.com/termux/termux-packages/assets/82843871/7c7c75c0-5ddd-4b62-b64e-9f47a83d4a57)

**Comment by 2096779623** [comment]
Don't use a virtual machine to run termux.

**Comment by mcagabe19** [comment]
> Don't use a virtual machine to run termux.

well I was just install termux on VM due I can't multiple termux. I needed armv7 termux for compile the [box86](https://github.com/ptitSeb/box86) and I'm helping to ptitSeb to get box(86/64) working in termux so.. this issue can

**Comment by 2096779623** [comment]
> well I was just install termux on VPhoneGaGa due I can't multiple termux. I needed armv7 termux for compile the [box86](https://github.com/ptitSeb/box86) and I'm helping to @ptitSeb to get box(86/64) working in termux so.. this issue can be closed

You can use [termux-docker](https://github.com/termux/termux-docker) instead of Vphonegaga .
