### ISSUE TITLE
[Bug]: Nethack 3.6.7 and the curses interface

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#18615]
### Problem description

I started up nethack and immediately saw something wrong with the curses interface

Instead of describing, I'll drop a screenshot

![Screenshot_2023-12-02-12-50-24-51_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-packages/assets/46418295/fb3e6099-4716-4f88-ae7e-53682c29db95)

### What steps will reproduce the bug?

You need to open up nethack with some of the options set to curses, this can be done in the .nethackrc file

windowtype:curses
symset:curses

### What is the expected behavior?

I remember it looking more like this in the early versions

![curses-introduction](https://github.com/termux/termux-packages/assets/46418295/8e2f573d-c42c-4120-b07e-89aefbb46e30)

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=31151
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# dichvucoder-repo (sources.list.d/dichvucoder.list)
deb https://repo.dgbaodev.com dvc-packages dvc
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/termux/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.39.5
Android version:
12
Kernel build information:
Linux localhost 4.19.152-perf+ #1 SMP PREEMPT Mon Oct 9 22:39:47 CST 2023 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH2127
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.styling versionCode:30
com.termux.window versionCode:15
```

**Comment by Grimler91** [comment]
Try zooming out, looks similar to gpg pinentry issue if console is too small

**Comment by Grimler91** [comment]
Don't know, but closing then since issue is solved for you
