### ISSUE TITLE
[Package]: Asciiquarium

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#18625]
### Why is it worth to add this package?

Just something nice for the terminal screen

### Source code URL

https://github.com/cmatsuoka/asciiquarium

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by Biswa96** [comment]
It is just a perl script and can be used as is. No packaging is required.
