### ISSUE TITLE
[Bug]:  Installtion of matplotlib fails

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#18640]
### Problem description

Trying to install matplotlib package fails. First it fails with the missing `spawn.h` header error, but after installing the `libandroid-spawn` package it fails in a different way.

```
            [402/402] ElideMiddle.ElideInTheMiddle
            failed
            make[2]: *** [CMakeFiles/build_ninja.dir/build.make:120: build_ninja-prefix/src/build_ninja-stamp/build_ninja-run_ninja_test_suite] Error 1
            make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/build_ninja.dir/all] Error 2
            make: *** [Makefile:136: all] Error 2
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-6hfir09o/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 674, in s
etup
                cmkr.make(make_args, install_target=cmake_install_target, env=env)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-6hfir09o/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 697, in make
                self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-6hfir09o/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 742, in make_impl
                raise SKBuildError(msg)
      
            An error occurred while building with CMake.
              Command:
                /data/data/com.termux/files/usr/bin/cmake --build . --target install --config Release --
              Install target:
                install
              Source directory:
                /data/data/com.termux/files/usr/tmp/pip-install-y0ci9y9f/ninja_e38cf2eba55f4061a1ce2c884d3d10b9
              Working directory:
                /data/data/com.termux/files/usr/tmp/pip-install-y0ci9y9f/ninja_e38cf2eba55f4061a1ce2c884d3d10b9/_skbuild/linux-aarch64-3.11/cmake-build
            Please check the install target is valid and see CMake's output for more information.
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for ninja
      Failed to build patchelf ninja
      ERROR: Could not build wheels for patchelf, ninja, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
dpkg: error processing package matplotlib (--configure):
 installed matplotlib package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 matplotlib
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

```

### What steps will reproduce the bug?

`pkg install matplotlib`

### What is the expected behavior?

it should succeed.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=6845
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.39.5
Android version:
10
Kernel build information:
Linux localhost 4.9.118-23733710 #1 SMP PREEMPT Thu Jul 21 10:29:46 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G965F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.styling versionCode:31
```

**Comment by twaik** [comment]
Post the whole log please.

**Comment by tigran123** [comment]
[typescript.txt](https://github.com/termux/termux-packages/files/13599070/typescript.txt)

Here is the full typescript of `pkg install matplotlib`

**Comment by romanovj** [comment]
`pkg i ninja patchelf`

**Comment by tigran123** [comment]
Thank you, that worked. But presumably those two packages should be listed as dependencies and installed automatically?

**Comment by romanovj** [comment]
> And now `pip install gmpy` fails with `longinterp.h` header missing...

gmpy 1.17 - release Jul 28, **2013**

you can try your luck with 2.1.5 or switch to older python

pip install https://github.com/aleaxit/gmpy/archive/refs/tags/gmpy2-2.1.5.tar.gz

**Comment by romanovj** [comment]
@Suletta-Majo you can copy modules from
`/data/data/com.termux/files/usr/lib/python3.11/site-packages`
to `lib/python3.11/site-packages` inside your venv

**Comment by Suletta-Majo** [comment]
@romanovj
There were two directories, so I moved them with _**cp matplot* Matplotlib**_   
has appeared in pip list in env!  
 In the Python program for the graph image output test  
The import error is gone, but I get a new numpy error    
[errormsg.txt](https://github.com/termux/termux-packages/files/13720261/errormsg.txt)

**Comment by romanovj** [comment]
@Suletta-Majo 
`patchelf --add-needed libpython3.11.so  /data/data/com.termux/files/home/pyprog/env/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311.so`

**Comment by Suletta-Majo** [comment]
@romanovj 
thanks I tried it, but there error seems to be no change
[errormsg2.txt](https://github.com/termux/termux-packages/files/13720655/errormsg2.txt)

**Comment by romanovj** [comment]
@Suletta-Majo try

**Comment by Suletta-Majo** [comment]
@romanovj 
on my virtual-environment
<code>pip install matplotlib</code> is run completed!
but error is same

Let's run python and modules in a virtual environment on the site we learned because it was recommended and we just followed it.
I would like to move to programming in a direct environment that is easy and simple in terms of Termux😓
As it is happening now, it is not like I can deal with it as an advanced person.
thanks

**Comment by romanovj** [comment]
@Suletta-Majo did you replace numpy in venv with numpy from /data/data/com.termux/files/usr/lib/python3.11/site-packages ?

**Comment by Suletta-Majo** [comment]
@romanovj 
Because the machine translation displayed the copy source and destination as if it were reversed.   
I didn't do it because I didn't understand the purpose of this work, but I understood it with a new statement and carried  
it out Errors are now concise and short, and I feel like they can be solved  
somehow Is this a good way to uninstall some duplicate matplotlib?
<code>
(env) [165ms][~/pyprog]$ python3 mplottes.py
/data/data/com.termux/files/home/pyprog/env/lib/python3.11/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
</code>

**Comment by Suletta-Majo** [comment]
success! thankyou @romanovj   

i not copyed all required module  
so when copy start. i found mystery module named mpl_toolkit  
i copy this to venv module directory then plotprogram complete run and generate png graph!   
thx a lot and sorry my wrong action :D
<code>
[76ms][/data/data/com.termux/files/usr/lib/python3.11/site-packages]$ cp -rf matplot* ~/pyprog/env/lib/python3.11/site-packages
[0.899s][/data/data/com.termux/files/usr/lib/python3.11/site-packages]$ cp -rf pypar* ~/pyprog/env/lib/python3.11/site-packages
[154ms][/data/data/com.termux/files/usr/lib/python3.11/site-packages]$ cp -rf count* ~/pyprog/env/lib/python3.11/site-packages
cp: cannot stat 'count*': No such file or directory
[115ms][1][/data/data/com.termux/files/usr/lib/python3.11/site-packages]$ cp -rf conto* ~/pyprog/env/lib/python3.11/site-packages
[135ms][/data/data/com.termux/files/usr/lib/python3.11/site-packages]$ cp -rf cycl* ~/pyprog/env/lib/python3.11/site-packages
[96ms][/data/data/com.termux/files/usr/lib/python3.11/site-packages]$ cp -rf kiwi* ~/pyprog/env/lib/python3.11/site-packages
[154ms][/data/data/com.termux/files/usr/lib/python3.11/site-packages]$ cd mpl_toolkits                                /data/data/com.termux/files/usr/lib/python3.11/site-packages/mpl_toolkits
.  mplot3d  axis
<code>

**Comment by twaik** [comment]
As of now `pkg install matplotlib` works fine. I am closing this as fixed.
