### ISSUE TITLE
Package request: termux-arch

### ISSUE THREAD

**Issue by martmists** [termux/termux-packages#1864]
https://github.com/sdrausty/termux-arch

**Comment by fornwall** [comment]
Thanks for the suggestion! I think that repository works nice as it is - those who are interested in using are (hopefully?) able to use it from the repo, and installing from the repo instead of packaging it up allows it to evolve faster.

**Comment by martmists** [comment]
I would however be interested in seeing different Termux distros. The default is Debian-esque, but I'd love to see an Arch or Fedora-like Termux environment. Can we expect this anywhere in the near future?

**Comment by fornwall** [comment]
@martmists Raise an issue at https://github.com/sdrausty/termux-arch/issues and ask!

**Comment by sdrausty** [comment]
@martmists @fornwall Thank you for your time and suggestions. While I do agree it will be cool to see a Termux package, this is completely unnecessary afaict.  The script is designed to install a Linux in just a few keystrokes.  Tapping this link https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh will transfer the script to your device. Simply run `bash setupTermuxArch.sh` to install Arch Linux. 

@martmists if you are still interested in having a package created as you suggest in this issue, open an issue at the address @fornwall provided or at https://github.com/sdrausty/TermuxArch/issues and we will go from there.  A package can be created for this script, but I don't see the motivation for it. Can you say why you want it packaged?

**Comment by sdrausty** [comment]
@martmists `setupTermuxArch.sh` provides three Linux distributions at present. See https://plus.google.com/u/0/109614420080028230010/posts/bkRpMPiBZM2 for details.
