### ISSUE TITLE
[Bug]: socat UDP listen error, but netcat is fine

### ISSUE THREAD

**Issue by brianwoo** [termux/termux-packages#18645]
### Problem description

I have this problem where socat cannot listen on any UDP port for some reason. Netcat can listen fine on the same UDP port. The error was xioopen_ipdgram_listen(): unknown address family 0. I have tried this on 2 different Android phones and I am getting the same error.
![IMG_20231206_202157](https://github.com/termux/termux-packages/assets/2199825/079d2f5d-6d0f-4087-808a-7c3a7cbceedc)

### What steps will reproduce the bug?

From Termux, enter the following:

```bash
socat -dd udp-listen:1234,fork,reuseaddr,bind=127.0.0.1 -
```

The same UDP listen from netcat and worked:

```bash
nc -u -vv -l 1234
```

### What is the expected behavior?

socat should be able to listen on udp port 1234.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7034
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://plug-mirror.rcac.purdue.edu/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://plug-mirror.rcac.purdue.edu/termux/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.39.5
Android version:
14
Kernel build information:
Linux localhost 5.10.177-android13-4-00003-ga7208022a7ea-ab10815828 #1 SMP PREEMPT Fri Sep 15 16:40:54 UTC 2023 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 6
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

**Comment by licy183** [comment]
This is a bug of socat version 1.8.0.0. It is also reproducible on Alpine Linux 3.19 (with socat version 1.8.0.0), or even a newly built one.

![image](https://github.com/termux/termux-packages/assets/45286352/ed54b3e0-23ca-4382-a271-41e35ca3fd56)

![image](https://github.com/termux/termux-packages/assets/45286352/3e3899b7-ccfd-4a88-a0dc-a6f6898e95c0)

**Comment by brianwoo** [comment]
Thanks very much for testing it.  Really appreciate it.

**Comment by licy183** [comment]
I've submitted a temporary fix for it and have reported this issue upstream. I will not close this issue until upstream resolves it. Thanks for your report!

**Comment by ezekielnewren** [comment]
> This is a bug of socat version 1.8.0.0. It is also reproducible on Alpine Linux 3.19 (with socat version 1.8.0.0), or even a newly built one.
> 
> ![image](https://private-user-images.githubusercontent.com/45286352/289232162-ed54b3e0-23ca-4382-a271-41e35ca3fd56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTY5NjEsIm5iZiI6MTcwNDAxNjY2MSwicGF0aCI6Ii80NTI4NjM1Mi8yODkyMzIxNjItZWQ1NGIzZTAtMjNjYS00MzgyLWEyNzEtNDFlMzVjYTNmZDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA5NTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNDI2ODE5MmE0YmE1M2ExZjJhM2QyNDg0MjlmMjM5MmU2Mjc4ZjZjNGIyNmJjNDQwODMwMWE3NmU3MDlkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DNXBpmH_pGOoiWYVt1cO-Ql46Zm_CGPooTHkEMiCGow)
> 
> ![image](https://private-user-images.githubusercontent.com/45286352/289232095-3e3899b7-ccfd-4a88-a0dc-a6f6898e95c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTY5NjEsIm5iZiI6MTcwNDAxNjY2MSwicGF0aCI6Ii80NTI4NjM1Mi8yODkyMzIwOTUtM2UzODk5YjctY2NmZC00YTg4LWEwZGMtYTZmNjg5OGU5NWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA5NTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyOTNmZjcxNmRmNzQzNmYzOWJjOGZmZGFhYjU2NmRiMGRkZWVmNDQzMTMzMGFlMGZmNDNmMDRmZTZhMDc4ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ve3hRZnIcGNI9obHxW8j_G2gZ0IH_VgiibliXW2H2Kc)

I was trying to run 'socat UDP-LISTEN:5000,fork -' on Alpine Linux 3.19 and I got this error.

**Comment by licy183** [comment]
You need to report it to Alpine Linux or build socat from source with [this patch](https://github.com/termux/termux-packages/blob/fadc9bec5ae6c92fdb9a5f5f4cd16d375dcfb1cb/packages/socat/0004-udp-listen-bind4.patch).
