### ISSUE TITLE
[Bug]: Python AttributeError: module 'os' has no attribute 'link'. Did you mean: 'unlink'?

### ISSUE THREAD

**Issue by ShaoYuJun** [termux/termux-packages#18666]
### Problem description

pip tries to access os.link but errors out. Similar to #4557 but in a newer version of python.

### What steps will reproduce the bug?

Using the newest vertion of python in apt source (3.11.6).
``` bash
~ $ python
Python 3.11.6 (main, Month  date yyyy, hh:mm:ss) [Clang 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.link
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'link'. Did you mean: 'unlink'?
```

### What is the expected behavior?

from official [Python docs:](https://docs.python.org/3/library/os.html)
> ### os.link(src, dst, *, src_dir_fd=None, dst_dir_fd=None, follow_symlinks=True)
>
>    Create a hard link pointing to src named dst.
>    This function can support specifying src_dir_fd and/or dst_dir_fd to supply [paths relative to directory descriptors](https://docs.python.org/3/library/os.html#dir-fd), and [not following symlinks](https://docs.python.org/3/library/os.html#follow-symlinks).
>    Raises an [auditing event](https://docs.python.org/3/library/sys.html#auditing) os.link with arguments src, dst, src_dir_fd, dst_dir_fd.
>    [Availability](https://docs.python.org/3/library/intro.html#availability): Unix, Windows, not Emscripten.
>    Changed in version 3.2: Added Windows support.
>   New in version 3.3: Added the src_dir_fd, dst_dir_fd, and follow_symlinks arguments.
>    Changed in version 3.6: Accepts a [path-like object](https://docs.python.org/3/glossary.html#term-path-like-object) for src and dst.

It damages many python-based app like matrix-commander.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB                                                                                     TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=29242
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.pku.edu.cn/termux/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.pku.edu.cn/termux/termux-root/ root stable
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.pku.edu.cn/termux/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.5
Android version:
13
Kernel build information:
Linux localhost 5.10.136-android12-9-967691-abX700ZCU5BWH6 #1 SMP PREEMPT Fri Aug 11 08:38:22 UTC 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-X700
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by licy183** [comment]
Android has disabled hard link on Android 5+ in SELinux. `os.link` will not work on Android. So I think this will not be fixed in Termux.

**Comment by ShaoYuJun** [comment]
> Android has disabled hard link on Android 5+ in SELinux. `os.link` will not work on Android. So I think this will not be fixed in Termux.

ops...Sad to hear that.

**Comment by Benjamin-Loison** [comment]
I am absolutely not an expert but just wanted to have `matrix-commander` working to some extent and I achieved to do so by removing occurrences of `link` in [`$PREFIX/lib/python3.11/site-packages/aiofiles/os.py`](https://github.com/Tinche/aiofiles/blob/c35ef69768aed5a1a900164f80761a288836b015/src/aiofiles/os.py#L20).

**Comment by agowa** [comment]
Doesn't Android API 21 have os.link and API 26 Files.createLink and FileSystemProvider.createLink including the new LinkPermissions "hard", "symbolic" for hardlinks? As far as I'm aware of the former "blocking" of os.link on android mainly resulted from the choice for FAT32 on the external storage (which does no support it). Also it always worked with root permissions (development boards or embedded devices).

Is this enough to revisit the decision to fix this limitation @licy183?
