### ISSUE TITLE
g++ doing problems 

### ISSUE THREAD

**Issue by nivmish123** [termux/termux-packages#187]
hello.cpp file:
`#include <iostream>
using namespace std;

int main() {
   cout << "Hello World";
   return 0;
}`

I tried to compile it:
`g++ helli.cpp`

but I get thins:
`/data/data/com.termux/files/usr/tmp//ccY3dn83.o: In function `main':
hello.cpp:(.text+0x8c): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
hello.cpp:(.text+0xa4): undefined reference to `std::cout'
/data/data/com.termux/files/usr/tmp//ccY3dn83.o: In function `__static_initialization_and_destruction_0(int, int)':
hello.cpp:(.text+0xec): undefined reference to `std::ios_base::Init::Init()'
hello.cpp:(.text+0x130): undefined reference to `std::ios_base::Init::~Init()'
collect2: error: ld returned 1 exit status`

**Comment by fornwall** [comment]
The Android system libstdc++ does not contain full support for the C++ standard library: see http://developer.android.com/ndk/guides/cpp-support.html

For now you have to add `-lgnustl_shared` to link against the fully featured GNU STL library. In the future the g++ and clang++ packages in Termux may be modified to do thst by default.
