### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HLSV** [termux/termux-packages#18760]
### Problem description

~ $ apt update
Get:1 https://deb.kcubeterm.me/termux-main stable InRelease [512 B]
Err:1 https://deb.kcubeterm.me/termux-main stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.

### What steps will reproduce the bug?

~ $ apt update
Get:1 https://deb.kcubeterm.me/termux-main stable InRelease [512 B]
Err:1 https://deb.kcubeterm.me/termux-main stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.

### What is the expected behavior?

Baixar os novos pacotes e atualizar...

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.18.91-Nitrogen_Pie_V2.0+ #1 SMP PREEMPT Sun Mar 1 23:25:36 PST 2020 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J730F
```

**Comment by twaik** [comment]
After installing Termux and opening it, you should do the following:

1. `termux-change-repo` (to select a nearby mirror to get updates from):
- `SPACE` toggles highlighted options;
- `ENTER` moves to the next screen;
Choose the first/topmost option on each screen. _(If that one fails, try another.)_
2. `pkg update && pkg upgrade` (to update your package database, then upgrade all packages)
On each prompt, press `y` and `Enter` to install newest versions available
3. `exit` (to exit Termux, so you can restart it yourself, all updated!)
