### ISSUE TITLE
Termux session terminating automatically in vnc

### ISSUE THREAD

**Issue by HR-decode** [termux/termux-packages#18764]
I am facing an issue with termux related to vnc

I logged in at proot-distro debian and started vnc server using tigervnc.When i open realvnc viewer the connection closes automatically after a while and termux session also automatically terminates.i did this in 4gb ram phone.

**Comment by twaik** [comment]
Seems like out-of-memory issue. It can not be fixed.
Next time you are opening issue like this use `Bug report` format, not blank issue.
