### ISSUE TITLE
[Bug]: Audacity can not be rebuilt or upgraded.

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#18790]
### Problem description

Hi. Audacity can not be rebuilt, probably because of NDK verbump.
[Build log](https://github.com/termux/termux-packages/files/13752302/audacity-build.log).

Version upgrading is not possible too because of major changes in Audacity and patches incompatibility.

### What steps will reproduce the bug?

```
./build-package -I -f audacity
```

**Comment by twaik** [comment]
BTW did anyone try to port the latest version (3.5.1) xtkoba commented 3.0.0+ can not work with vanilla wxwidgets, but what exactly does that mean?

**Comment by TomJo2000** [comment]
There's also general packaging/licensing concerns with newer Audacity versions after they got acquired.

**Comment by twaik** [comment]
So we should not upgrade the version?

**Comment by TomJo2000** [comment]
I'm not actually sure what the deal with Audacity is.

**Comment by twaik** [comment]
It is still
```
Audacity is released under the GNU General Public License version 3 (GPLv3). 
Individual source files may be available under other licenses as specified 
in those files or an accompanying file. In particular, many source files are 
available under GPL version 2 (GPLv2) or (at your option) any later version, 
and this is the default license used where no other license is specified.
```
SO I think we can package new versions.

**Comment by TomJo2000** [comment]
I looked it up, when Audacity was acquired in 2021 they were talking about adding some telemetry to it, but due to backlash it looks like that never got implemented.
But the general stink of that incident has lingered over Audacity ever since.

It should be fine to update it.

**Comment by twaik** [comment]
Ok, I stucked with vst3sdk which seems to depend on "filesystem" C++ feature which for some reason is inaccessible to conan. Probably I am doing something wrong and conan should not be used here at all.

**Comment by twaik** [comment]
[audacity.tar.gz](https://github.com/termux/termux-packages/files/15486051/audacity.tar.gz)
If somebody wants to spend some time on this.

**Comment by Biswa96** [comment]
> Probably I am doing something wrong and conan should not be used here at all.

conan requirement could be disabled with `-Daudacity_conan_enabled=off` option.

> I stucked with vst3sdk which seems to depend on "filesystem" C++ feature which for some reason

If conan is disabled vst3sdk and other dependencies can be added as a packaged dependencies. Then issues with vst3sdk can be patched.
