### ISSUE TITLE
[Bug]: SponsorBlock extension says WebExtension storage is disabled in Firefox

### ISSUE THREAD

**Issue by twocomputed** [termux/termux-packages#18792]
### Problem description

After installing SponsorBlock in termux Firefox, the extension went up with an error saying that WebExtension storage is disabled despite having the ```webextensions.storage.sync.enabled``` preference set to ```true```.
Screenshot:
![Screenshot_2023-12-22_06-40-59](https://github.com/termux/termux-packages/assets/84579960/dbf219c9-d94a-4040-bdfc-bdf789b65100)
Log output (captured using ```firefox > ~/firefox.log 2&1```)
[firefox.log](https://github.com/termux/termux-packages/files/13752953/firefox.log)

### What steps will reproduce the bug?

Install Firefox from x11-repo
Start an X11 session with Firefox
Click the addons button and search for sponsorblock
Click on "SponsorBlock..."
Install the addon and follow onscreen instructions
The addon will open up the onboarding page with the aforementioned error message.

### What is the expected behavior?

SponsorBlock extension does not throw an error about WebExtension storage

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=23341
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.quantum5.ca/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.quantum5.ca/termux/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
libdrm/stable 2.4.119 aarch64 [upgradable from: 2.4.118]
termux-tools version:
1.39.6
Android version:
14
Kernel build information:
Linux localhost 5.15.94-android13-8-27763874-abS911U1UES2BWKA #1 SMP PREEMPT Fri Nov 24 07:03:52 UTC 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S911U1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
com.termux.api versionCode:51
com.termux.boot versionCode:7
com.termux.styling versionCode:31
```

**Comment by truboxl** [comment]
Issue seems to go away after set `webextensions.storage.sync.kinto` to `true`

**Comment by truboxl** [comment]
Firefox Desktop default for `webextensions.storage.sync.kinto` is `false`.
https://searchfox.org/mozilla-central/source/modules/libpref/init/all.js#3592

It seems Mozilla defaults Android version to `true`.
https://searchfox.org/mozilla-central/source/mobile/android/app/geckoview-prefs.js#419

We may want to set it to `true` to fix this issue for now until Kinto is removed...
