### ISSUE TITLE
[Bug]: Can't run java programs in LXQT

### ISSUE THREAD

**Issue by DuilioPerez** [termux/termux-packages#18801]
### Problem description

I can't run java programs in the LXQT desktop environment. I can run them into termux without a desktop environment, but when I use the java command, it fails with the error: 
"Error: Could not find or load main class 'name'
Caused by: java.lang.ClassNotFoundException: 'name'"
To run graphical java programs, I use the next command inside termux: "DISPLAY=:1 java 'className'. It's the only way to do it. I have only tested in LXQT, so it is possible to work in another desktop environment. I'm using Termux-x11 for graphics.

### What steps will reproduce the bug?

Run the command java in LXQT.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=24965
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.6
Android version:
11
Kernel build information:
Linux localhost 4.14.186-22735277 #1 SMP PREEMPT Sat Feb 19 02:14:57 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A225M
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:14
com.termux.styling versionCode:29

```

**Comment by twaik** [comment]
You did not specify classpath or bootclasspath so it should not even try to work.
