### ISSUE TITLE
Package request: PyNaCl

### ISSUE THREAD

**Issue by pippognetow** [termux/termux-packages#1881]
I got an error while try to install pynacl with pip. So it's possible to install it with pkg command?
Please help

**Comment by Deathlive** [comment]
pkg install -y coreutils clang libclang libtool libgrpc-dev

SODIUM_INSTALL=system pip2 install pynacl

**Comment by pippognetow** [comment]
@Deathlive same error :/

**Comment by Grimler91** [comment]
@pippognetow this has been requested before, see https://github.com/termux/termux-packages/issues/1628. 

Try the steps described there:
```
git clone https://github.com/pyca/pynacl && cd pynacl
# replace all occurences of /bin/sh with /data/data/com.termux/files/usr/bin/sh
find . -type f -exec sed 's%/bin/sh%/data/data/com.termux/files/usr/bin/sh%g' {} \;
#replace python with python2 for python2
python setup.py install
```

Closing this as it is a duplicate.

**Comment by pippognetow** [comment]
@Grimler91 I had try but when I do the second command the tablet start to vibrate and nothing happens

**Comment by Grimler91** [comment]
Oh yeah, there was a typo. ˋsed 's%..ˋ -> ˋsed -i 's%ˋ. Corrected now, please try again.
(That command will take some time as it goes through all the files in pynacl and replaces /bin/sh with /data/data/com.termux/files/usr/bin/sh)

**Comment by pippognetow** [comment]
It's normal that the device starts to vibrate?

**Comment by Grimler91** [comment]
Yeah, on an error. It's [the bell character](https://termux.com/configuration.html). I believe we have/used to have an issue open at https://github.com/termux/termux-app that wishes to prevent almost continuous vibrations.

The reason for the almost continuous vibration is that the faulty command is run a lot of times thanks to 
ˋfindˋ. Sorry for the typo.

**Comment by pippognetow** [comment]
No problem tomorrow I am going to test if it works...I hope. Thanks for your help @Grimler91

**Comment by emptix0** [comment]
@Grimler91 I got this error 
```
The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

```

**Comment by Grimler91** [comment]
@emptix0 what did you run?
