### ISSUE TITLE
mpc: music player daemon client 0.35 

### ISSUE THREAD

**Issue by roizcorp** [termux/termux-packages#18844]
### Why is it worth to add this package?

it is the latest mpc package and contains a substantials improvements

### Home page URL

https://www.musicpd.org/

### Source code URL

https://github.com/MusicPlayerDaemon/mpc

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
No need to ask for package updates. We see when new releases are coming.
Currently we package `v0.35` which is the latest release as of now.
