### ISSUE TITLE
[Package]: Maxima Compiled with SBCL & or Clozure CL

### ISSUE THREAD

**Issue by defencedog** [termux/termux-packages#18851]
### Why is it worth to add this package?

Maxima is a mathematical tool for physicists & engineers alike. Right now in the repos following is available:
`Maxima 5.47.0 https://maxima.sourceforge.io using Lisp ECL 23.9.9`
However this `LISP` impementation is not supported by  `jupyter` kernel as stated by [maxima-jupyter](https://github.com/robert-dodier/maxima-jupyter?tab=readme-ov-file#maxima-jupyter)

_Note also that ECL might theoretically work, since it is supported by Bordeaux Threads. However, nobody (neither Maxima-Jupyter developers nor users) has been able to get ECL to work, therefore you should assume ECL does not work with Maxima-Jupyter. SBCL and Clozure CL are known to work, try those instead._

### Source code URL

https://github.com/calyau/maxima

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last commit was 4 years ago so I consider this project is dead/frozen.
