### ISSUE TITLE
Why msfconsole is not working

### ISSUE THREAD

**Issue by eth4kr** [termux/termux-packages#1886]
I've msfconsole installed and is listing in the bin directory, but when I type command, 

> msfconsole

, it says not found, and meanwhile I checked for file and is present there. [WHAT THE HELL IS THIS]

![screenshot_2017-12-02-06-37-09](https://user-images.githubusercontent.com/31907722/33509876-8947b8ee-d72b-11e7-8f9f-ad181289a4e5.png)
[I'm in bin directory of Termux, i.e., `usr/bin`

**Comment by vishalbiswas** [comment]
Install `apt install termux-exec`. Then restart termux

**Comment by fornwall** [comment]
As @vishalbiswas says, it's probably due to the shebang being something like `#!/usr/bin/env ruby`, and `/usr/bin/env` does not exist on Android. Installing `termux-exec` and reinstalling works around that.

**Comment by shaheem007** [comment]
lzmore                          xzgrep
 m4                              xzless
 make                            xzmore
 md5sum                          yacc
 mdm_console                     yard
 mkdir                           yardoc
 mkfifo                          yat2m
 mknod                           yes
 mktemp                          yri
 mpicalc                         zip
 msfbinscan                      zipcloak
 msfconsole                      zipdetails
 msfd                            zipgrep
 msfelfscan                      zipinfo
 msfmachscan                     zipnote
 msfpescan                       zipsplit
 msfrop
# ./msfd
bash: ./msfd: No such file or directory
# msfconsole
msfconsole: command not found
# msfd

**Comment by shaheem007** [comment]
im in 
/data/data/com.termux/files/usr/bin

**Comment by shaheem007** [comment]
this start happen when type this command in
$termux-elf-cleaner

im using termux on custom pie rom
samsung s4 i9505
