### ISSUE TITLE
[Bug]: xdg-open does nothing

### ISSUE THREAD

**Issue by Forge36** [termux/termux-packages#18869]
### Problem description

xdg-open returns error code 255 when run.

I have read https://github.com/termux/termux-tasker#allow-external-apps-property-optional
And it is working (and my tasker integration is also working).

from (unrelated) issue https://github.com/termux/termux-packages/issues/8733

### What steps will reproduce the bug?

1. open termx
2. run `xdg-open https://termux.dev/issues || echo $?`

This prints 255

I have added `allow-external-apps = true` in `~/.termux/termux.properties`

### What is the expected behavior?

Chrome should launch the URL

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=24513
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.astra.in.ua/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.39.3
Android version:
14
Kernel build information:
Linux localhost 4.19.282-g4b749a433956-ab10893502 #1 SMP PREEMPT Fri Sep 22 09:02:07 UTC 2023 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 5a
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.tasker versionCode:6
```

**Comment by agnostic-apollo** [comment]
Update `termux-am` package to `v0.8.0`.

**Comment by Forge36** [comment]
Aha: I was using a mirror which had `termux-am` at `v0.6.0` and the package update was reporting everything was up to date. I switched repositories using `termux-change-repo` and re-ran `pkg upgrade`

**Comment by agnostic-apollo** [comment]
Yeah, need to add booting out mirrors that are out of date for long from `pkg` rotation.
