### ISSUE TITLE
Package Request: pngquant

### ISSUE THREAD

**Issue by AntumDeluge** [termux/termux-packages#1887]
## Description:
*(taken from pngquant.org)*

***pngquant*** is a command-line utility and a library for lossy compression of PNG images.

The conversion reduces file sizes significantly (often as much as 70%) and preserves full alpha transparency. Generated images are compatible with all web browsers and operating systems.

#### Features
- High-quality palette generation using a combination of vector quantization algorithms.
- Unique adaptive dithering algorithm that adds less noise to images than the standard Floyd-Steinberg.
- Easy to integrate with shell scripts, GUIs and server-side software.
- Fast mode for real-time processing/large numbers of images.

Homepage: https://pngquant.org/
GitHub: https://github.com/pornel/pngquant

## Notes:
*libimagequant* is the only dependency that I am aware of. I am not sure if it is included with *pngquant*'s source. I only recently started using it.

#### libimagequant links:
About page: https://pngquant.org/lib
GitHub: https://github.com/ImageOptim/libimagequant

I read over #1831 & saw that Arch for Termux was referenced. *pngquant* does not appear to be included with it (at least, I didn't find it), so I decided to make this package request.

If I felt that I would have the time soon, I would attempt compiling & create a pull request myself. But I honestly don't know when I would be able to get to it.

Also, there is a GUI Android app available called [Atomize](https://play.google.com/store/apps/details?id=com.wrmndfzzy.atomize), but I would still like to have the command line utility.

I would add the *Package Request* label, but I guess I can't.

**Edit:** I just found the [Termux Create Package](https://github.com/termux/termux-create-package) repo. I may check this out & see if I can create the package myself if it's not too difficult... if I get time to do so.

**Edit:** Made a mistake. *libpng* is required too. Should have known that.

**Comment by SamSanuch** [comment]
![screenshot_2017-12-02-08-46-43-576_com termux](https://user-images.githubusercontent.com/33522514/33511268-afd3daae-d70f-11e7-8ca9-8c5277243142.png)

**Comment by AntumDeluge** [comment]
I can't get it to compile.

![tmp_28396-screenshot_20171201-1954261785524163](https://user-images.githubusercontent.com/3631473/33511606-71469ab6-d6d2-11e7-80f5-a42237659a3d.png)

![tmp_28396-screenshot_20171201-19571675325236](https://user-images.githubusercontent.com/3631473/33511612-7d0c1bbe-d6d2-11e7-9d37-dcd6c0e03625.png)

**Comment by SamSanuch** [comment]
You can't compile,i can!

**Comment by AntumDeluge** [comment]
Ya. And how did you get your Android filesystem to support executables?

**Comment by SamSanuch** [comment]
https://mega.nz/#!UqJVDYAZ!SDqy6V7fCG-t4GRyOpW1fBqTnzL1L5A4PA9yvhbac7A
Check makefile and watch my mistakes and type them here !
I'm using GCC v7.2.0 but it's doesn't matter after I'll compile all the required libraries, please check everything in zip and tell my mistakes!

**Comment by vishalbiswas** [comment]
I have opened #1888.
Thanks for the detailed request, helped a lot.

**Comment by SamSanuch** [comment]
@vishalbiswas where is my credit?:weary:

**Comment by vishalbiswas** [comment]
@SamSanuch I didn't use gcc. Didn't see your Makefile. If you compared my pull request, there is nothing in common between our builds.

**Comment by AntumDeluge** [comment]
Thank you both very much!

@vishalbisws
```bash
uname -a
Linux localhost 3.10.49-MPI24.241-2.35-1-g84466aa #1 SMP PREEMPT Tue Jul 25 16:01:38 CEST 2017 armv7l Android
```

*armv7l* 32-bit is my Android architecture.

**Comment by vishalbiswas** [comment]
@AntumDeluge https://drive.google.com/open?id=162by1hU8BLkt0ZV9w6ZbxcEbzIYmLZj1
Please tell me if there are any regressions.

**Comment by AntumDeluge** [comment]
Thanks a bunch! I have installed it, but probably won't be able to test it thoroughly until tomorrow.

**Comment by AntumDeluge** [comment]
![tmp_13422-screenshot_20171201-220043365271193](https://user-images.githubusercontent.com/3631473/33512343-557b299e-d6e3-11e7-90f3-05dce93dce51.png)

**Comment by fornwall** [comment]
Thanks to @vishalbiswas the package is now available for installation: `pkg install pngquant`.

**Comment by AntumDeluge** [comment]
Thank you all so much (yes, you too @SamSanuch 😉). Now I am able to run my scripts on Android.

**Comment by SamSanuch** [comment]
@AntumDeluge thanks!
I'll suggest you something?
I think you'll probably love to use this rootfs this a collection of all new tools with extraordinary tools that Official repo not possess https://github.com/xeffyr/termux-rootfs

**Comment by AntumDeluge** [comment]
Thanks @SamSanuch, that does look interesting. It looks like it for 64-bit only though. If that's the case, I won't be able to try it out until I get a 64-bit Android OS. 😢
