### ISSUE TITLE
[Bug]: mesa-vulkan-icd-freedreno-dri3 have contains files unrelated to the project

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-packages#18875]
### Problem description

It seems to me that this package is poorly built or contains things that should not be in the final package. Well, this package contains binaries from bsdtar (bsdcat, bsdcpio, bsdtar) and libraries (libarchive.so and liblua.so). I'm almost sure that these files were mistakenly added to the package causing conflicts with existing packages.

Additionally, I guess the package (if a fix is added) closes the issue [#17567](https://github.com/termux/termux-packages/issues/17567)

Contributors: @xMeM @licy183 

### What steps will reproduce the bug?

Just install it :P

### System information

termux-info:

```

```

**Comment by twaik** [comment]
I can confirm this. 
```
~ $ apt-file show mesa-vulkan-icd-freedreno-dri3
mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/bin/bsdcat
mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/bin/bsdcpio
mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/bin/bsdtar
mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/lib/libarchive.so
mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/lib/liblua.so
mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/lib/libvulkan_freedreno.so
mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/share/doc/mesa-vulkan-icd-freedreno-dri3/license.rst
mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/share/vulkan/icd.d/freedreno_icd.aarch64.json
```

**Comment by xMeM** [comment]
> I can confirm this.
> 
> ```
> ~ $ apt-file show mesa-vulkan-icd-freedreno-dri3
> mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/bin/bsdcat
> mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/bin/bsdcpio
> mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/bin/bsdtar
> mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/lib/libarchive.so
> mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/lib/liblua.so
> mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/lib/libvulkan_freedreno.so
> mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/share/doc/mesa-vulkan-icd-freedreno-dri3/license.rst
> mesa-vulkan-icd-freedreno-dri3: /data/data/com.termux/files/usr/share/vulkan/icd.d/freedreno_icd.aarch64.json
> ```

These are not required at runtime. Would adding them as build dependencies fix it? Or is there any other way to exclude them?

**Comment by licy183** [comment]
Mesa seems include subprojects in its source file. Just delete them.

https://github.com/termux/termux-packages/blob/7e2af7650b333791c00bc0642048fb844e4e4e42/packages/mesa/build.sh#L36-L39
