### ISSUE TITLE
[Bug]: brotli-static Depends: brotli (= 1.0.9-1)

### ISSUE THREAD

**Issue by Vanillma** [termux/termux-packages#18897]
### Problem description

Hi, we have two packages in Termux called Brotli and Brotli-Static
![Screenshot_20240105-110236_Termux](https://github.com/termux/termux-packages/assets/95992420/1e94989f-f225-49fa-a309-d7a190c77a3e)

When I want to install the brotli-static package (which is brotli static libraries according to the description)
I am facing such problem (because brotli version in repository is 1.1.0 while it depends on brotli 1.0.9-1!)
![Screenshot_20240105-114356_Termux](https://github.com/termux/termux-packages/assets/95992420/e015d0fb-258b-4871-8086-1c56edf588fd)

Now my question is, is there a version lower than 1.1.0 of brotli in the termux repositories for me to install?

Is the brotli-static package no longer updated to version 1.1.0? (by the keepers of the termux package)
To be able to depend on version 1.1.0?

### What steps will reproduce the bug?

pkg i brotli-static :)

### What is the expected behavior?

Install brotli-static :)

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=17770
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirror.bardia.tech/termux/termux-main stable main
Updatable packages:
c-ares/stable 1.25.0 arm [upgradable from: 1.24.0]
debianutils/stable 5.16 arm [upgradable from: 5.15]
termux-tools version:
1.40.4
Android version:
9
Kernel build information:
Linux localhost 3.4.113 #1 SMP PREEMPT Tue Oct 25 18:29:07 UTC 2022 armv7l Android
Device manufacturer:
samsung
Device model:
SM-G7102
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Grimler91** [comment]
Hi, seems like they removed so static libraries are no longer built automatically with commit https://github.com/google/brotli/commit/641bec0e30bea648b3da1cd90fc6b44deb429f71, and the old brotli-static package remains in our repo and conflicts with now brotli package.

We can either just remove brotli-static, or fix the build recipe so that it builds static libraries again. Do you need brotli-static?

**Comment by Vanillma** [comment]
> Hi, seems like they changed so static libraries are no longer built automatically with commit [google/brotli@641bec0](https://github.com/google/brotli/commit/641bec0e30bea648b3da1cd90fc6b44deb429f71), and the old brotli-static package remains in our repo and conflicts with now brotli package.
> 
> We can either just remove brotli-static, or fix the build recipe so that it builds static libraries again. Do you need brotli-static?

No I just wondered why there was this conflict in the termux repository... that's why I reported it!

As for removing or updating, I'll leave the decision to the maintainers of the termux package repository... but in general if you don't want to update it, it's better to remove it... because in the repository it's useless... But if you want to keep it and update it...that's up to you

Thank you for your response to this issue :)
