### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "et": cannot locate symbol

### ISSUE THREAD

**Issue by jasttw** [termux/termux-packages#18893]
### Problem description

I assume this is similar to #11791 

I get the following when I use et:
`CANNOT LINK EXECUTABLE "et": cannot locate symbol "_ZN6google8protobuf8internal20VarintParseSlowArm32EPKcPjm" referenced by "/data/data/com.termux/files/usr/bin/et"...`

### What steps will reproduce the bug?

pkg upgrade
et

### What is the expected behavior?

Normal usage of application

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=19843
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.zju.edu.cn/termux/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.40.4
Android version:
14
Kernel build information:
Linux localhost 5.15.94-android13-8-27763874-abS918BXXS3BWKC #1 SMP PREEMPT Wed Nov 29 23:18:35 UTC 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S918B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.styling versionCode:31
com.termux.tasker versionCode:6
```

**Comment by jasttw** [comment]
Hello,

I started getting the issue again

`CANNOT LINK EXECUTABLE "et": cannot locate symbol "_ZN6google8protobuf8internal14ArenaStringPtr3SetEN4absl12lts_2023080211string_viewEPNS0_5ArenaE" referenced by "/data/data/com.termux/files/usr/bin/et"...`

**Comment by twaik** [comment]
First of all do `pkg up` and try again.
