### ISSUE TITLE
[Package]: bashrc and .bash_profile misses bashalias

### ISSUE THREAD

**Issue by grzchr15** [termux/termux-packages#18913]
### Why is it worth to add this package?

How to temmux

### Source code URL

termux

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

Please help

**Comment by TomJo2000** [comment]
It looks like you used the wrong issue template, what are you trying to do?
