### ISSUE TITLE
Zsh failing with unsetopt CASE_GLOB (case-insensitive glob matching)

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#1894]
_From @ericbn on December 3, 2017 12:2_

On a clean Termux installation:

```
$ pkg install -y zsh git
...
$ zsh
$ git clone --recursive https://github.com/Eriner/zim.git ~/.zim
...
$ ls ~/.zim/modules/prompt/functions/prompt_*_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_eriner_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_gitster_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_lean_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_liquidprompt_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_magicmace_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_minimal_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_pure_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_steeef_setup
$ unsetopt CASE_GLOB
$ ls ~/.zim/modules/prompt/functions/prompt_*_setup
zsh: no matches found: /data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_*_setup
$
```

Unseting `CASE_GLOB` means disabling case-sensitive matching in globs. According to the [docs](http://zsh.sourceforge.net/Doc/Release/Options.html#Expansion-and-Globbing):

>  If the option is unset, the presence of any character which is special to filename generation will cause case-insensitive matching. For example, `cvs(/)` can match the directory `CVS` owing to the presence of the globbing flag [...]

In the scenario above, it is expected that the second `ls` call would yield the same results as the first one.

_Copied from original issue: termux/termux-app#497_

**Comment by xeffyr** [comment]
Tried to reproduce this on two devices, and here is the result:
On AArch64 (with fresh PREFIX):
```
localhost% ls ~/.zim/modules/prompt/functions/prompt_*_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_eriner_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_gitster_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_lean_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_liquidprompt_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_magicmace_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_minimal_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_pure_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_steeef_setup
localhost% unsetopt CASE_GLOB
localhost% ls ~/.zim/modules/prompt/functions/prompt_*_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_eriner_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_gitster_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_lean_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_liquidprompt_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_magicmace_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_minimal_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_pure_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_steeef_setup
```

And on ARM device, I have received:
```
localhost% ls ~/.zim/modules/prompt/functions/prompt_*_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_eriner_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_gitster_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_lean_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_liquidprompt_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_magicmace_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_minimal_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_pure_setup
/data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_steeef_setup
localhost% unsetopt CASE_GLOB
localhost% ls ~/.zim/modules/prompt/functions/prompt_*_setup
zsh: no matches found: /data/data/com.termux/files/home/.zim/modules/prompt/functions/prompt_*_setup
```

So error only on ARM ?

**Comment by fornwall** [comment]
Hm, I can reproduce it on an AArch64 device running Android 7.0.

It seems that `~` doesn't work correctly after `unsetopt CASE_GLOB` on that one.

**Comment by SamSanuch** [comment]
@fronwall yes I'll done and got worked

**Comment by ericbn** [comment]
I should have mentioned when I reported this: I'm on a Nexus 4, zsh version is `zsh 5.4.2 (arm-unknown-linux-androideabi)`

**Comment by easyaspi314** [comment]
Is this a signed/unsigned char/wchar_t issue?

**Comment by WingofaGriffin** [comment]
Any updates on this? I'm able to install zim successfully and it works, but the built in zsh-syntax-highlighting plugin is unable to be loaded.

**Comment by xeffyr** [comment]
> Any updates on this? I'm able to install zim successfully and it works, but the built in zsh-syntax-highlighting plugin is unable to be loaded.

@WingofaGriffin How zsh-syntax-highlighting related to this issue ?

Plugin **zsh-syntax-highlighting** is not built-in so you can't just load it.
Clone https://github.com/zsh-users/zsh-syntax-highlighting and source file `zsh-syntax-highlighting.zsh` from it.

![screenshot_20181202-203122_termux](https://user-images.githubusercontent.com/25881154/49343414-87824900-f671-11e8-8d05-8d98f069f846.jpg)

**Comment by ericbn** [comment]
The issue is still related to unsetting `CASE_GLOB`, not related to zsh-syntax-highlighting.

Unsetting `CASE_GLOB` before sourcing zsh-syntax-highlighting is just another way of reproducing it.

![screenshot_20190104-192639_termux](https://user-images.githubusercontent.com/4120606/50718017-bff2b980-1059-11e9-99e5-c4fdcc960287.jpg)

**Comment by easyaspi314** [comment]
Found what the bug is.

A simple `strace` shows this:

```c
openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 EACCES (Permission denied)
```

Specifically, it is [this `opendir` call in `glob.c`](https://github.com/zsh-users/zsh/blob/ce0660b7ba283e3208db28a8763796816a587259/Src/glob.c#L584) which is called with NO_CASE_GLOB to recursively find all case combinations.

Since Android doesn't really like programs calling `opendir` on `/data/data`, it returns immediately.

**Comment by easyaspi314** [comment]
I submitted a patch to the mailing list which correctly handles unreadable parent directories. But I will make a PR to backport it until it gets upstream.

**Comment by easyaspi314** [comment]
![Screenshot_20210112-224415](https://user-images.githubusercontent.com/6258309/104404139-fce6c600-5527-11eb-8ac1-f3cb14b2e20e.png)
Behold
