### ISSUE TITLE
[Bug]: Error when adding certain folders to cmus' queue: fdsan: attempted to close file descriptor

### ISSUE THREAD

**Issue by terminatorbs** [termux/termux-packages#18954]
### Problem description

when adding certain folders to my cmus queue, cmus crashes. 

Full error:
fdsan: attempted to close file descriptor 14, expected to be unowned, actually owned by FILE* 0x7ac8a74c58
Aborted

i do not know why this happens on some folders and not on others. the folders look normal to me, nothing special in them just mp3 files and subdirectories. they work perfectly fine on my archlinux desktop.

i've searched for this error and seen reports of it in other termux packages, but i don't know enough about termux to understand what's going on.

### What steps will reproduce the bug?

open cmus in termux
switch to file browser (5)
browse to affected folder
add the folder to queue (e)

### What is the expected behavior?

the files get added to the queue and cmus doesn't crash

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=29786
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.40.5
Android version:
13
Kernel build information:
Linux localhost 5.4.219-qgki-g50c59753416a #1 SMP PREEMPT Thu Nov 30 19:05:41 CST 2023 aarch64 Android
Device manufacturer:
Fairphone
Device model:
FP5
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by licy183** [comment]
I cannot reproduce on my Android 13 device, but disabling fdsan for this package may fix the problem.

**Comment by licy183** [comment]
Please test the deb files in https://github.com/termux/termux-packages/actions/runs/7501973782/job/20423694499?pr=18955. Thanks!

**Comment by terminatorbs** [comment]
that works perfectly, thank you very much!

after reading up on what fdsan actually is for a second... does disabling it come with any downsides? if so, i'd be happy to help troubleshoot. but if you're okay with removing it in the package, i don't mind either way.

**Comment by licy183** [comment]
Emmm... Lots of packages have disabled fdsan, such as [git](https://github.com/termux/termux-packages/commit/22a60f72493b6cf3df81874a7904b1372ff43652), [zsh](https://github.com/termux/termux-packages/commit/42515f9c26a55c173e8cd5a914d3e5f88afc3201) and [renameutils](https://github.com/termux/termux-packages/commit/a0820247258675a620ea3d7de33d1f13eb72d41f), so I think it is acceptable to disable fdsan only.

Maybe a tracker should be created to record how many packages are affected by fdsan.

**Comment by pgaskin** [comment]
I think I've found a possible cause of the double-close, which would happen if an input file opened by ip/mad (mp2, mp3) ends at around the same time as a file is opened with fopen or fdopen (which is most likely ip/cue or an ip/opus).

@terminatorbs did the folder you added contain a combination of mp2/mp3/cue/opus files?

**Comment by terminatorbs** [comment]
> @terminatorbs did the folder you added contain a combination of mp2/mp3/cue/opus files?

sorry for the late reply, my cmus wasn't working for a while due to https://github.com/termux/termux-packages/issues/20773 .
i don't think i have the cmus version that had the issue around anymore, but if i remember the folder correctly, it does contain mp3, ogg and m4a files.
