### ISSUE TITLE
Command doesn't work 

### ISSUE THREAD

**Issue by Chauhanrs** [termux/termux-packages#18967]
pkg install root-repo
CANNOT LINK EXECUTABLE "apt": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libapt-pkg.so"...
$ pkg install unstable-repo
CANNOT LINK EXECUTABLE "apt": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libapt-pkg.so"...
$

**Comment by Grimler91** [comment]
Have you installed termux from google playstore? Uninstall and install from f-droid, see https://github.com/termux/termux-app#installation
