### ISSUE TITLE
[Bug]: wierd screen on termux x11 

### ISSUE THREAD

**Issue by Notmrbeast1508** [termux/termux-packages#18966]
### Problem description

![Screenshot_20240113_161413_TermuxX11](https://github.com/termux/termux-packages/assets/109910490/7e36f8d3-ff2a-4538-a549-b1d2665d08ca)
I was trying to open up mobox /wine and that's the screen I got I waited for 10 mins just incase it was normal 

### What steps will reproduce the bug?

Literally anything I can't start wine without that popping up

### What is the expected behavior?

Wierd screen sometimes its black

### System information

termux-info:

```

```
Samsung s22 ultra eyxnos

**Comment by IntinteDAO** [comment]
Is this works on other X11 server, like tigervncserver + aVNC? Maybe the problem is not releated with Termux X11

**Comment by Notmrbeast1508** [comment]
I don't know what that is I don't know anything about emulating I just want to install gta 4 on my phone

**Comment by twaik** [comment]
1. We do not offer support for wine or mobox.
2. `-legacy-drawing`. It is stated it `termux-x11`'s readme page.

**Comment by IntinteDAO** [comment]
> I don't know what that is I don't know anything about emulating I just want to install gta 4 on my phone

Maybe try to use other project like Winlator? It's Open Source and it's for running Windows apps on Android. If you don't need a mouse it can be best option
