### ISSUE TITLE
[Package]: u-boot

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#18962]
### Why is it worth to add this package?

U-Boot is a firmware for embedded boards based on PowerPC, ARM, MIPS and
several other processors, which can be installed in a boot ROM and used to
initialize and test the hardware or to download and run application code.

It could be useful for `qemu-system-arm` and `qemu-system-risc`.

### Home page URL

https://www.denx.de/wiki/U-Boot

### Source code URL

https://github.com/u-boot/u-boot

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
`qemu-system-*` packages already have instruments for booting ROMs. Also `u-boot` configuring is specific for both target hardware and ROM so there is no sense in packaging it.
