### ISSUE TITLE
[Bug]: tmux has issues displaying multibyte Unicode characters

### ISSUE THREAD

**Issue by stevenxxiu** [termux/termux-packages#18974]
### Problem description

Multibyte Unicode characters aren't displayed properly, or somethings not at all.

I'm not sure whether this is a *Neovim* bug, or an issue with the *Termux* app itself.

### What steps will reproduce the bug?

Create the file `foo.txt`:

```
⌨️A
```

Open this with a clean *Neovim* config:

    $ nvim --clean foo.txt

What we get looks like:

```
A 
```

### What is the expected behavior?

The file displays the multibyte Unicode character.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=pacman
TERMUX_APP_PID=11947
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=pacman
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Usage = All
Server = https://service.termux-pacman.dev/main/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/main/aarch64
[x11]
Usage = All
Server = https://service.termux-pacman.dev/x11/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/x11/aarch64
[root]
Usage = All
Server = https://service.termux-pacman.dev/root/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/root/aarch64
[tur]
Usage = All
Server = https://service.termux-pacman.dev/tur/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur/aarch64
[tur-continuous]
Usage = All
Server = https://service.termux-pacman.dev/tur-continuous/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur-continuous/aarch64
[tur-multilib]
Usage = All
Server = https://service.termux-pacman.dev/tur-multilib/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur-multilib/aarch64
[gpkg]
Usage = All
Server = https://service.termux-pacman.dev/gpkg/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/gpkg/aarch64
Updatable packages:
iproute2 6.6.0-0 -> 6.7.0-0
termux-tools version:
1.40.5
Android version:
14
Kernel build information:
Linux phone_pixel7_steven 5.10.177-android13-4-00003-ga7208022a7ea-ab10815828 #1 SMP PREEMPT Fri Sep 15 16:40:54 UTC 2023 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 7
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.boot versionCode:7
```

**Comment by TomJo2000** [comment]
Unable to reproduce.
This is most likely a font issue.

Please try replacing `~/.termux/font.ttf` with a (monospace) font you know to have Emoji support.
Recommendations would include any [NerdFont](https://www.nerdfonts.com/font-downloads), these are also available through [Termux:Styling](https://github.com/termux/termux-styling).

**Comment by stevenxxiu** [comment]
Ah this happens when run inside *Tmux*. It's fine indeed when running outside of it. So it must be a *Tmux* bug then.

I do have a custom font, I use *JetBrainsMono NF Regular*.

**Comment by TomJo2000** [comment]
> Ah this happens when run inside _Tmux_. It's fine indeed when running outside of it. So it must be a _Tmux_ package bug then.
> 
> I do have a custom font, I use _JetBrainsMono NF Regular_.
> 
> Could you see if you can reproduce it inside _Tmux_?

In that case tmux is setting a bad default value for `TERM`, this is known issue not exclusive to Termux and is very googleable.

**Comment by stevenxxiu** [comment]
I tried `set -g default-terminal "tmux-256color"` per the wiki. It makes no difference.

This works fine when I use `cat` on the file, with or without that setting.

It also works mostly fine inside *Tmux* when I SSH into a server and perform the same command. There I get extra spaces, but the character shows up. This is why I think there's a package bug.

Does it work for you inside *Tmux*?

**Comment by truboxl** [comment]
I think tmux itself is already problematic in handling emoji.
Outside tmux
```
echo "⌨A" > test.txt
cat test.txt
⌨A
```

Inside tmux (there seems to be a space after emoji)
```
echo "⌨A" > test.txt
cat test.txt
⌨ A
```

I will change the title to tmux

**Comment by stevenxxiu** [comment]
Yup I don't mind `cat` as having a space isn't too bad. It's *Neovim* inside *Tmux* that breaks and is my main concern.

**Comment by truboxl** [comment]
Its not just Neovim. Any program running inside tmux is having this issue.

**Comment by truboxl** [comment]
I wonder if this is similar to #224 and need #13943

**Comment by stevenxxiu** [comment]
The character shows up now on v0.119.0-beta.1.

It's slightly strange that when I press `:`, the character goes from having a width of 1 to 2. But that's no big deal.
