### ISSUE TITLE
[Bug]: Bootstrap archives failed.

### ISSUE THREAD

**Issue by ytest6709** [termux/termux-packages#18970]
### Problem description

The last Bootstrap archive was generated two weeks ago. After generating, it will not release for two weeks
Fails with:
```
Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

### What steps will reproduce the bug?

Generate a Bootstrap archive workflow

### What is the expected behavior?

Bootstrap archives generated successfully

### System information

termux-info:

```
GitHub Actions (Workflow)
```

**Comment by truboxl** [comment]
https://github.com/actions/upload-artifact/issues/478
