### ISSUE TITLE
installing lv2 builds lxml which causes device to crash

### ISSUE THREAD

**Issue by zavocc** [termux/termux-packages#18973]
### Problem description

Installing `lv2` or packages depends on it would build `lxml` but during the installation, it takes a lot of resources causing the device to crash in the background, leading to unfinished installs in any packages.

### What steps will reproduce the bug?

Install `lv2`

### What is the expected behavior?

I believe lxml should be packaged as it is impractical to build such dependency that would cause the device to crash

Additionally it also causes such build error halfway through the installation if the Termux app was in the foreground (which causes the device to lag and system ui crashes)
![Screenshot_2024-01-14-21-11-59-52_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-packages/assets/119603393/90a5a384-b6a5-4b5c-be48-6bff00a056d5)

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21712
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
cmus/stable 2.10.0-7 aarch64 [upgradable from: 2.10.0-6]
command-not-found/stable 2.4.0-7 aarch64 [upgradable from: 2.4.0-6]
libdrm/stable 2.4.120 aarch64 [upgradable from: 2.4.119]
libpsl/stable 0.21.5 aarch64 [upgradable from: 0.21.2]
termux-tools version:
1.40.5
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf+ #2 SMP PREEMPT Sat Sep 3 23:17:03 CST 2022 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH1933
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.styling versionCode:31
com.termux.widget versionCode:13

```

**Comment by licy183** [comment]
OK. It also crashed on my device. It seems that 6G RAM (~4.5GB free RAM) is not enough to compile lxml.

1) Add `python-lxml`. It will not take much space I suppose.
2) Remove `lv2` and `inkscape-extensions`. They depend on lxml and install it in `postinst`.

Ping @sylirre @truboxl @2096779623 Any ideas?

**Comment by licy183** [comment]
During the building, I found that the file generated by `etree.pyx` (`etree.c`) is about 12 MB, maybe this file is too large for some devices to compile...
