### ISSUE TITLE
"/data/data/com.termux/files/home/PhoneSploit-Pro/phonesploitpro.py", line 35, in <module>     import nmap[Bug]: 

### ISSUE THREAD

**Issue by Raagemanaxe** [termux/termux-packages#18995]
### Problem description

I can't use phonesploit-pro
Plz help plz

### What steps will reproduce the bug?

git clone https://github.com/AzeemIdrisi/PhoneSploit-Pro.git
Cd phonsploit-pro
Python3 phonesploitpro.py
And this problem = "/data/data/com.termux/files/home/PhoneSploit-Pro/phonesploitpro.py", line 35, in <module>
    import nmap

### System information

termux-info:

`TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=10101
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.40.5
Android version:
12
Kernel build information:
Linux localhost 4.19.132-24202344 #1 SMP PREEMPT Wed Sep 13 16:18:50 +07 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A217F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so``

```

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking
