### ISSUE TITLE
[Bug]: Sudo wasnt fixed for Magisk-delta

### ISSUE THREAD

**Issue by CanglanXYA** [termux/termux-packages#18990]
### Problem description

su has been repaired by newer package updates, but sudo is still asking me "No superuser binary detected.
Are you rooted?"

Due to the magisk-delta's change of root position

### What steps will reproduce the bug?

give root access to termux and invoke sudo

### What is the expected behavior?

sudo successfully run

### System information

termux-info:

```

Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=16444
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.sahilister.in/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.40.5
Android version:
13
Kernel build information:
Linux localhost 5.10.198-gki-g31ba608f47d0 #45 SMP PREEMPT Mon Jan 8 16:59:46 CET 2024 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
23013PC75G
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.tasker versionCode:6

```

**Comment by 2096779623** [comment]
Ping @HuskyDG  .

**Comment by Archargelod** [comment]
> Where is sudo coming from?

![IMG_20240130_013418](https://github.com/termux/termux-packages/assets/60652075/5211e9ed-3ff2-49c6-b3b3-c5d8bef0f629)

sudo is a symlink to tsu (Termux su wrapper)

**Comment by Agreous** [comment]
new megisk delta change mounting su location , and tsu don't know that . I've created a pull request to solve this problem cswl/tsu#104
