### ISSUE TITLE
[Package]: Visidata

### ISSUE THREAD

**Issue by rmc1961** [termux/termux-packages#19016]
### Why is it worth to add this package?

excellent terminal-based viewing/editing of tsv,csv

### Home page URL

https://github.com/saulpw/visidata

### Source code URL

https://github.com/saulpw/visidata.git

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by licy183** [comment]
I'm afraid this package will not be packaged. It is distributed as a pure-python wheel and is able to be installed via pip.

**Comment by rmc1961** [comment]
thanks so much - I will try that method


*ROGER CICORA*

*U.S. ARMY BAND, RET.*

*TENOR TROMBONE, BASS TROMBONE770.977.3616*
