### ISSUE TITLE
[Bug]: Scrcpy doesn't have android-tools as dependency

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-packages#19020]
### Problem description

It's simple proposal. Scrcpy needs adb, but our package doesn't have it in dependency. 

scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
exec: No such file or directory
ERROR: Command not found: [adb], [start-server]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
INFO: You may install 'adb' by "apt install adb"
ERROR: Could not execute "adb start-server"
ERROR: Could not start adb server
ERROR: Server connection failed

### What steps will reproduce the bug?

Run scrcpy without android-tools

### System information

termux-info:

```

```

**Comment by twaik** [comment]
Please, do not ping contributors randomly.

**Comment by IntinteDAO** [comment]
Ok, I through you develop this package

**Comment by twaik** [comment]
I was updating the package, not the same thing.
