### ISSUE TITLE
[Package]: Polars

### ISSUE THREAD

**Issue by Alexanderortizcuellar** [termux/termux-packages#19028]
### Why is it worth to add this package?

Excelent and fast data science library for python

### Home page URL

https://pola.rs/

### Source code URL

https://github.com/pola-rs/polars

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by Alexanderortizcuellar** [comment]
Already added on tur-repo

**Comment by TomJo2000** [comment]
Closed in:
- https://github.com/termux-user-repository/tur/pull/811
