### ISSUE TITLE
https://github.com/termux/termux-packages/issues/7834#issue-1034316075[Package]: 

### ISSUE THREAD

**Issue by Mehdimome** [termux/termux-packages#19049]
### Why is it worth to add this package?

https://github.com/termux/termux-packages/issues/7834#issue-1034316075

### Source code URL

Git

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by TomJo2000** [comment]
This is not a package.
If you want to comment on the discussion just comment there.
