### ISSUE TITLE
[Bug]: Bug in cmake 

### ISSUE THREAD

**Issue by defencedog** [termux/termux-packages#19058]
### Problem description

`cmake` is unusable

```
~ $ cmake --help                                        CANNOT LINK EXECUTABLE "cmake": cannot locate symbol "_ZN4Json5ValueC1ERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE" referenced by "/data/data/com.termux/files/usr/bin/cmake"...
```

### What steps will reproduce the bug?

Install `cmake` & it gives this error

### What is the expected behavior?

Cannot use cmake....

### System information

termux-info:

```
Termux Variables:                                       TERMUX_API_VERSION=0.50.1                               TERMUX_APK_RELEASE=F_DROID                              TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=10505                                    TERMUX_IS_DEBUGGABLE_BUILD=0                            TERMUX_MAIN_PACKAGE_FORMAT=debian                       TERMUX_VERSION=0.118.0                                  TERMUX__USER_ID=0                                       Packages CPU architecture:
arm                                                     Subscribed repositories:                                # sources.list                                          deb https://md.mirrors.hacktegic.com/termux/termux-main stable main                                             # tur-repo (sources.list.d/tur.list)                    deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:                                     All packages up to date                                 termux-tools version:                                   1.40.5                                                  Android version:                                        13                                                      Kernel build information:                               Linux localhost 4.19.191-25884040-abA137FXXS3CWL2 #1 SMP PREEMPT Fri Dec 8 18:11:03 KST 2023 armv8l Android     Device manufacturer:                                    samsung                                                 Device model:                                           SM-A137F                                                LD Variables:                                           LD_LIBRARY_PATH=/system/lib                             LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so                                                Installed termux plugins:                               com.termux.api versionCode:51
```

**Comment by truboxl** [comment]
Please do not set `LD_LIBRARY_PATH`

**Comment by defencedog** [comment]
@truboxl 
I added that because ffmpeg will not work
Your instructions work ... but now when I use ffmpeg

```
CANNOT LINK EXECUTABLE "ffmpeg": cannot locate symbol "_Z17createHeifDecoderv" referenced by "/system/lib/libhwui.so"...
```

**Comment by truboxl** [comment]
Please install `libandroid-stub` if it fixes your issue

**Comment by defencedog** [comment]
Thanks it works...

**Comment by Biswa96** [comment]
May I ask how libandroid-stub fixed the ffmpeg issue? Ther error output has createHeifDecoder function which is not related to libandroid library.

**Comment by agnostic-apollo** [comment]
The `_Z17createHeifDecoderv` symbol is provided by `/system/lib[64]/libheif.so`, which `/system/lib[64]/libhwui.so` depends on.

The termux `libheif` package also provides `$PREFIX/lib/libheif.so`.

Installing the `libandroid-stub` package shouldn't be required, my guess is that user has set `LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib` somewhere else, which causes `$PREFIX/lib/libheif.so` to be picked up instead of the system one.

This error was posted in https://www.reddit.com/r/termux/comments/17pxvw5/how_to_fix_this/ as well and unsetting `LD_LIBRARY_PATH` worked.

**Comment by defencedog** [comment]
@agnostic-apollo 
Problem has resurfaced. I had installed `libandroid-stub`
```
examples$ gtt                                           CANNOT LINK EXECUTABLE "gtt": cannot locate symbol "_Z17createHeifDecoderv" referenced by "/system/lib/libhwui.so"...
```

**Comment by truboxl** [comment]
Can you help try `rm $PREFIX/lib/libheif.so`?

**Comment by defencedog** [comment]
@truboxl will not `rm` be dangerous what about renaming via `mv`?

**Comment by truboxl** [comment]
Unless you use packages from `apt rdepends libheif` then maybe. You can always restore by `apt reinstall libheif`.

**Comment by agnostic-apollo** [comment]
Also post output of `echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH` after running it in the same shell in which error is triggered.

**Comment by defencedog** [comment]
> Also post output of `echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH` after running it in the same shell in which error is triggered.

`LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib:/data/data/com.termux/files/usr/local/lib`

**Comment by agnostic-apollo** [comment]
That is your problem, find out where it is being set and remove the command, it should be empty on Android `>= 7`, termux does not set it by default. Also uninstall `libandroid-stub` with `apt remove libandroid-stub` and restore your `$PREFIX/lib/libheif.so` file.
