### ISSUE TITLE
[Package]: bfm

### ISSUE THREAD

**Issue by codedsprit** [termux/termux-packages#19051]
### Why is it worth to add this package?

**Bfm** a dead simple terminal file manager written in bash which works with ***vim-keybindings***

### Source code URL

https://github.com/codedsprit/bfm

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by 2096779623** [comment]
> Packages must be active, well-known projects
Software available in major Linux distributions has more chances to be included into Termux repositories. We will not accept outdated, dead projects as well as projects which do not have active community.

It would be better to request it at https://github.com/termux-user-repository/tur.
