### ISSUE TITLE
[Bug]: firefox from x-11 repo crash when i open whatsapp web

### ISSUE THREAD

**Issue by dr1408** [termux/termux-packages#19050]
### Problem description

I installed firefox from x-11 repo and i have xfce4 for GUI environment

### What steps will reproduce the bug?

When i enter whatsapp web its normal but when i try to enter any conversation firefox crash imeddiatly 

### What is the expected behavior?

To browse conversations without crashes

### System information

termux-info:

```
Termux 0.118 armv8l samsung A13 sm137F
```

**Comment by dr1408** [comment]
So i tried running firefox from xfce java then i entered whatsapp web and same crash happens but i got alot of java errors when i opened firefox till it crash

firefox
console.error: ({})
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
console.error: "Translations: SIMD not supported" (new CompileError("at offset 15: bad type", "chrome://global/content/translations/simd-detect-worker.js", 14))
[1706036073525](tel:1706036073525) Sync.EngineManager ERROR Could not initialize engine : TypeError: Cc[aContract] is undefined(resource://gre/modules/XPCOMUtils.sys.mjs:137:9) JS Stack trace: defineLazyServiceGetter/<@XPCOMUtils.sys.mjs:137:9
ExtensionStorageEngineBridge@extension-storage.sys.mjs:72:3
register@engines.sys.mjs:706:20
registerAlternatives@engines.sys.mjs:633:16
_registerEngines@service.sys.mjs:477:36
[localhost] u0_a214@localhost:~ [20:55:24] 
0$ firefox 
console.error: ({})
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
console.error: "Translations: SIMD not supported" (new CompileError("at offset 15: bad type", "chrome://global/content/translations/simd-detect-worker.js", 14))
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
console.error: "SearchSuggestionController found an unexpected string value:" "HTTP request timeout"
JavaScript warning: https://web.whatsapp.com/main.97024843baa672b4f497.js, line 5: unreachable code after return statement
JavaScript warning: https://web.whatsapp.com/main.97024843baa672b4f497.js, line 5: unreachable code after return statement
[Child 14675, MediaDecoderStateMachine #1] WARNING: Decoder=b9e39c00 Decode error: NS_ERROR_DOM_MEDIA_DECODE_ERR (0x806e0004) - MediaResult mozilla::FFmpegAudioDecoder<60>::DecodeUsingFFmpeg(AVPacket *, bool &, MediaRawData *, DecodedData &, bool *): FFmpeg audio error: file /home/runner/.termux-build/firefox/src/dom/media/MediaDecoderStateMachineBase.cpp:166
JavaScript warning: https://web.whatsapp.com/app.26ed67124a887965b349.js, line 266: This error message will be blank when privacy.resistFingerprinting = true.  If it is really necessary, please add it to the whitelist in MediaError::GetMessage: NS_ERROR_DOM_MEDIA_DECODE_ERR (0x806e0004) - MediaResult mozilla::FFmpegAudioDecoder<60>::DecodeUsingFFmpeg(AVPacket *, bool &, MediaRawData *, DecodedData &, bool *): FFmpeg audio error
JavaScript warning: https://web.whatsapp.com/app.26ed67124a887965b349.js, line 266: This error message will be blank when privacy.resistFingerprinting = true.  If it is really necessary, please add it to the whitelist in MediaError::GetMessage: NS_ERROR_DOM_MEDIA_DECODE_ERR (0x806e0004) - MediaResult mozilla::FFmpegAudioDecoder<60>::DecodeUsingFFmpeg(AVPacket *, bool &, MediaRawData *, DecodedData &, bool *): FFmpeg audio error
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error
Bus error

**Comment by truboxl** [comment]
Please post output `apt info firefox`

**Comment by licy183** [comment]
I'm able to reproduce it with url https://get.webgl.org. This may be a issue related to WebGL in Firefox.

**Comment by licy183** [comment]
The backtrace with firefox debug build

<details>

```
0  0xf767d708 in strlen () from /system/lib/libc.so
#1  0xf259fe14 in nsTDependentString<char>::nsTDependentString (this=0xe2a70048, aData=0x0)
    at /home/builder/.termux-build/firefox/src/xpcom/string/nsTDependentString.h:75
#2  0xf2aa769a in mozilla::gl::MesaMemoryLeakWorkaround()::$_0::operator()(dl_phdr_info*, unsigned int, void*) const (
    info=<optimized out>, this=<optimized out>, size=<optimized out>, data=<optimized out>)
    at /home/builder/.termux-build/firefox/src/gfx/gl/GLContext.cpp:2622
#3  mozilla::gl::MesaMemoryLeakWorkaround()::$_0::__invoke(dl_phdr_info*, unsigned int, void*) (info=<optimized out>, 
    size=<optimized out>, data=0xe2a700a0) at /home/builder/.termux-build/firefox/src/gfx/gl/GLContext.cpp:2620
#4  0xf778da90 in __dl__Z18do_dl_iterate_phdrPFiP12dl_phdr_infojPvES1_ () from /system/bin/linker
#5  0xf778cdc0 in __dl_dl_iterate_phdr () from /system/bin/linker
#6  0xf2a9a43e in mozilla::gl::MesaMemoryLeakWorkaround () at /home/builder/.termux-build/firefox/src/gfx/gl/GLContext.cpp:2619
#7  0xf75ee698 in std::__ndk1::__call_once(unsigned long volatile&, void*, void (*)(void*)) ()
   from /data/data/com.termux/files/usr/lib/libc++_shared.so
#8  0xf2a9cad6 in std::__ndk1::call_once[abi:v170000]<void (&)()>(std::__ndk1::once_flag&, void (&)()) (__flag=..., 
    __func=<optimized out>) at /home/builder/.termux-build/_cache/android-r26b-api-24-v1/bin/../sysroot/usr/include/c++/v1/mutex:670
#9  0xf2a9c0b2 in mozilla::gl::EglDisplay::Create (lib=..., display=<optimized out>, isWarp=<optimized out>, aProofOfLock=...)
    at /home/builder/.termux-build/firefox/src/gfx/gl/GLLibraryEGL.cpp:807
#10 0xf2a9d3ce in mozilla::gl::GetAndInitDisplay (egl=..., displayType=<optimized out>, aProofOfLock=...)
    at /home/builder/.termux-build/firefox/src/gfx/gl/GLLibraryEGL.cpp:169
#11 0xf2a9d288 in mozilla::gl::GLLibraryEGL::CreateDisplayLocked (this=0xcc574dc0, forceAccel=<optimized out>, 
    out_failureId=0xe2a70314, aProofOfLock=...) at /home/builder/.termux-build/firefox/src/gfx/gl/GLLibraryEGL.cpp:958
#12 0xf2a9cd4e in mozilla::gl::GLLibraryEGL::DefaultDisplay (this=0xcc574dc0, out_failureId=0xe2a70314)
    at /home/builder/.termux-build/firefox/src/gfx/gl/GLLibraryEGL.cpp:871
#13 0xf2a9b1aa in mozilla::gl::DefaultEglDisplay (out_failureId=0xe2a70314)
    at /home/builder/.termux-build/firefox/src/gfx/gl/GLContextEGL.h:30
#14 0xf2a9bfc8 in mozilla::gl::GLContextProviderEGL::CreateHeadless (desc=..., out_failureId=0xe2a70314)
    at /home/builder/.termux-build/firefox/src/gfx/gl/GLContextProviderEGL.cpp:1240
#15 0xf330ad16 in mozilla::WebGLContext::CreateAndInitGL(bool, std::__ndk1::vector<mozilla::WebGLContext::FailureReason, std::__ndk1::allocator<mozilla::WebGLContext::FailureReason> >*)::$_1::operator()(already_AddRefed<mozilla::gl::GLContext> (*)(mozilla::gl::GLContextCreateDesc const&, nsTSubstring<char>*), char const*) const (this=0xe2a70364, pfnCreate=0xe2a700a0, info=0x0)
    at /home/builder/.termux-build/firefox/src/dom/canvas/WebGLContext.cpp:384
#16 0xf3304a20 in mozilla::WebGLContext::CreateAndInitGL(bool, std::__ndk1::vector<mozilla::WebGLContext::FailureReason, std::__ndk1::allocator<mozilla::WebGLContext::FailureReason> >*)::$_0::operator()() const (this=<optimized out>)
    at /home/builder/.termux-build/firefox/src/dom/canvas/WebGLContext.cpp:397
#17 mozilla::WebGLContext::CreateAndInitGL (this=0xd2c7f000, forceEnabled=false, out_failReasons=0xe2a703e4)
    at /home/builder/.termux-build/firefox/src/dom/canvas/WebGLContext.cpp:391
#18 0xf3304db2 in mozilla::WebGLContext::Create(mozilla::HostWebGLContext&, mozilla::webgl::InitContextDesc const&, mozilla::webgl::InitContextResult*)::$_0::operator()() const (this=<optimized out>)
    at /home/builder/.termux-build/firefox/src/dom/canvas/WebGLContext.cpp:549
#19 mozilla::WebGLContext::Create (host=..., desc=..., out=0xe2a70520)
    at /home/builder/.termux-build/firefox/src/dom/canvas/WebGLContext.cpp:523
#20 0xf32db0ee in mozilla::HostWebGLContext::Create (ownerData=..., desc=..., out=0x0)
    at /home/builder/.termux-build/firefox/src/dom/canvas/HostWebGLContext.cpp:58
#21 0xf331cdb6 in mozilla::dom::WebGLParent::RecvInitialize (this=0xceaf4b80, desc=..., out=0x0)
    at /home/builder/.termux-build/firefox/src/dom/canvas/WebGLParent.cpp:18
#22 0xf3348f6e in mozilla::dom::PWebGLParent::OnMessageReceived (this=0xceaf4b80, msg__=..., reply__=...)
    at /home/builder/.termux-build/firefox/src/obj-arm-unknown-linux-androideabi/ipc/ipdl/PWebGLParent.cpp:418
#23 0xf2bed0a6 in mozilla::gfx::PCanvasManagerParent::OnMessageReceived (this=<optimized out>, msg__=..., reply__=...)
    at /home/builder/.termux-build/firefox/src/obj-arm-unknown-linux-androideabi/ipc/ipdl/PCanvasManagerParent.cpp:495
#24 0xf28f7f36 in mozilla::ipc::MessageChannel::DispatchSyncMessage (this=0xcff88e4c, aProxy=0xcf9d4d50, aMsg=..., aReply=...)
    at /home/builder/.termux-build/firefox/src/ipc/glue/MessageChannel.cpp:1780
#25 0xf28f798e in mozilla::ipc::MessageChannel::DispatchMessage (this=0xcff88e4c, aProxy=0xcf9d4d50, aMsg=...)
    at /home/builder/.termux-build/firefox/src/ipc/glue/MessageChannel.cpp:1730
#26 0xf28f7b44 in mozilla::ipc::MessageChannel::RunMessage (this=0x0, aProxy=0xcf9d4d50, aTask=...)
    at /home/builder/.termux-build/firefox/src/ipc/glue/MessageChannel.cpp:1525
#27 0xf28f7d92 in mozilla::ipc::MessageChannel::MessageTask::Run (this=0xd0a2d6b0)
    at /home/builder/.termux-build/firefox/src/ipc/glue/MessageChannel.cpp:1623
#28 0xf2613a18 in nsThread::ProcessNextEvent (this=0xe5215a00, aMayWait=<optimized out>, aResult=0xe2a707db)
    at /home/builder/.termux-build/firefox/src/xpcom/threads/nsThread.cpp:1192
#29 0xf26156da in NS_ProcessNextEvent (aThread=0x0, aMayWait=false)
    at /home/builder/.termux-build/firefox/src/xpcom/threads/nsThreadUtils.cpp:480
#30 0xf28f9650 in mozilla::ipc::MessagePumpForNonMainThreads::Run (this=0xe4facac8, aDelegate=0xe2a7082c)
    at /home/builder/.termux-build/firefox/src/ipc/glue/MessagePump.cpp:300
#31 0xf28cff0a in MessageLoop::RunInternal (this=0x0)
    at /home/builder/.termux-build/firefox/src/ipc/chromium/src/base/message_loop.cc:370
#32 MessageLoop::RunHandler (this=0x0) at /home/builder/.termux-build/firefox/src/ipc/chromium/src/base/message_loop.cc:363
#33 MessageLoop::Run (this=0x0) at /home/builder/.termux-build/firefox/src/ipc/chromium/src/base/message_loop.cc:345
#34 0xf26126fe in nsThread::ThreadFunc (aArg=0xe507fa90) at /home/builder/.termux-build/firefox/src/xpcom/threads/nsThread.cpp:370
#35 0xf70c7b06 in ?? () from /data/data/com.termux/files/usr/lib/libnspr4.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

</details>
