### ISSUE TITLE
Changes to be made when updating to NDK r17

### ISSUE THREAD

**Issue by enh** [termux/termux-packages#1905]
an NDK r17 with https://android-review.googlesource.com/#/c/platform/bionic/+/555419/ didn't need your <sys/select.h> patch, so hopefully you should be able to get rid of that when r17 ships. just filing this bug as a future reminder for you :-)

**Comment by fornwall** [comment]
Let's generalize this to a tracking bug to prepare for NDK r17. So far we have:

- <sys/select.h> patch can be dropped (as stated above)
- <elf.h> can be dropped (as mentioned in #1907)

**Comment by Grimler91** [comment]
Considering the latest comments in https://github.com/android-ndk/ndk/issues/294 we might be able to build emacs and m4 with clang instead of with gcc in r17 as well.

**Comment by fornwall** [comment]
- `AArch64 now uses gold by default, matching the other architectures` - we can remove the lines in build-package.sh that sets up gold as the default linker.

**Comment by fornwall** [comment]
- The workaround in added to libgit2 in https://github.com/termux/termux-packages/pull/2316 for the issue at https://github.com/android-ndk/ndk/issues/642 can be removed.
