### ISSUE TITLE
Hi, I was setting up Linux for my friend but she had issues with it.

### ISSUE THREAD

**Issue by Basiron** [termux/termux-packages#19063]
Hi, I was setting up Linux for my friend but she had issues with it.

We figured that she had the doble-trouble Samsung with Android 12, so we couldn't use the `VNCviewer` & `vncserver` on Termux/Ubuntu for development because the background process would get killed instantly.

<details>
  <summary>`termux-info`</summary>
  
  Output:
```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=11165
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://cdn.lumito.net/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://cdn.lumito.net/termux/termux-x11 x11 main
Updatable packages:
coreutils/stable 9.1-1 aarch64 [upgradable from: 9.1]
libc++/stable 25b aarch64 [upgradable from: 25-2]
termux-tools version:
1.29.2
Android version:
12
Kernel build information:
Linux localhost 4.14.186-24355525 #1 SMP PREEMPT Mon Jun 6 07:42:25 +07 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A326B
```
</details>

When we tried disabling Phantom Process Monitoring with,
```
adb shell settings put global settings_enable_monitor_phantom_procs false
```
we had the following error:
```
daemon not running; starting now at tcp:5037
* daemon started successfully
* daemon still not running
adb: cannot connect to daemon at tcp:5037: Not a data message
```

I tried running `adb devices` to see what's going on but it spewed the following:
```
daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /data/data/com.termux/files/usr/tmp/adb.10051.log
Server had pid: 25280
--- adb starting (pid 25280) ---
adb I 09-14 18:47:35 25280 25280 main.cpp:63] Android Debug Bridge version 1.0.41
adb I 09-14 18:47:35 25280 25280 main.cpp:63] Version 31.0.3p1-android-tools
adb I 09-14 18:47:35 25280 25280 main.cpp:63] Installed as /data/data/com.termux/files/usr/bin/adb
adb I 09-14 18:47:35 25280 25280 main.cpp:63]
adb F 09-14 18:47:36 25280 25280 main.cpp:155] could not install smartsocket listener: Address already in use

* failed to start daemon
adb: failed to check server version: cannot connect to daemon
```

After googling the error with added context that it happened on Termux/Ubuntu, I stumbled upon the similar issue https://github.com/termux/termux-packages/issues/7946 where [this](https://github.com/termux/termux-packages/issues/7946#issuecomment-991620663) reply offered such approach
```
export ADB_SERVER_SOCKET=localfilesystem:$(pwd)/adb_socket
adb start-server
```
to use a file as a socket and thus circumvent false-positive `EADDRINUSE (Address already in use)` bug on Samsung phones, if I understand it correctly.

After that, I ran

```
adb shell settings put global settings_enable_monitor_phantom_procs false
```

but it said `adb: no devices/emulators found`.

What exactly did I do wrong? Warning, I'm a newbie with `adb`.

_Originally posted by @JohnScience in https://github.com/termux/termux-app/issues/2366#issuecomment-1247106786_

**Comment by twaik** [comment]
No need to repost messages of some other people with no additional context.
