### ISSUE TITLE
NDK r16 made various ndk patches obsolete

### ISSUE THREAD

**Issue by enh** [termux/termux-packages#1907]
based on your bug reports over time, i'd been meaning for a while to check to what extent you'd be able to build with a pristine NDK. i finally had time this week...

* ndk-patches/elf.h: i think only a few structures and constants are missing in NDK r16, and https://android-review.googlesource.com/#/c/platform/bionic/+/556720/ should ensure that the remaining ones are in NDK r17.
* ndk-patches/sys-user.h.patch: i see you've spotted and removed this one yourself while i was testing :-)
* ndk-patches/syscall.h.patch: <syscall.h> as a synonym for <sys/sycall.h> is in NDK r16.
* ndk-patches/sysexits.h: an almost identical <sysexits.h> from one of the other BSDs is in NDK r16.
* ndk-patches/termios.h.patch: i suspect this was in the wrong place to begin with; glibc doesn't define _POSIX_VDISABLE if you only include <termios.h> either. none of your current packages seem to need this.

note also that libuv seems to have moved to https only. i needed this patch to build it:
```
diff --git a/packages/libuv/build.sh b/packages/libuv/build.sh
index e3216b18..8369aff4 100644
--- a/packages/libuv/build.sh
+++ b/packages/libuv/build.sh
@@ -2,7 +2,7 @@ TERMUX_PKG_HOMEPAGE=http://libuv.org
 TERMUX_PKG_DESCRIPTION="Support library with a focus on asynchronous I/O"
 TERMUX_PKG_VERSION=1.18.0
 TERMUX_PKG_SHA256=54e4734da09172f19d5061dcfd7a536fe4c3a8dc12ed981a14a58ac17efdab88
-TERMUX_PKG_SRCURL=http://dist.libuv.org/dist/v${TERMUX_PKG_VERSION}/libuv-v${TERMUX_PKG_VERSION}.tar.gz
+TERMUX_PKG_SRCURL=https://dist.libuv.org/dist/v${TERMUX_PKG_VERSION}/libuv-v${TERMUX_PKG_VERSION}.tar.gz
 
 termux_step_pre_configure () {
        export PLATFORM=android
```

a few other projects' web sites (such as graphviz) seem to be down, so i've ignored them.

let me know if you find anything that's still broken that should be fixed in the NDK directly!

**Comment by fornwall** [comment]
The patches

- sys-user.h.patch
- syscall.h.patch
- sysexits.h
- termios.h.patch

have all been dropped now, and <elf.h> has been added to #1905 to be dropped when updating to NDK r17.

Also, libuv and graphviz download urls have been updated, and I'm performing a full rebuild of all packages to pick up if any other url have gone stale.

Thanks a lot!
