### ISSUE TITLE
[Package]: mediapipe

### ISSUE THREAD

**Issue by itisjoby** [termux/termux-packages#19094]
### Why is it worth to add this package?

Its the one of the fastest facerecognition project by google

### Home page URL

https://github.com/google/mediapipe

### Source code URL

https://github.com/google/mediapipe

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

No

**Comment by licy183** [comment]
Duplicated of #17761
