### ISSUE TITLE
Please solve this problem 

### ISSUE THREAD

**Issue by devanand09** [termux/termux-packages#19097]
Waiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is held by process 11695 (Waiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is held by process 11695 (apt) please solve this problem 
![Screenshot_2024-01-30-22-41-54-52_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-packages/assets/158203479/cd92df52-c51b-4374-900c-6beee347e7fb)
![Screenshot_2024-01-30-22-41-54-52_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-packages/assets/158203479/73dd26b9-9efd-4e7e-bd5a-fed1c6ae4946)

**Comment by twaik** [comment]
Force-stop termux and start again.
