### ISSUE TITLE
Package request: cowsay

### ISSUE THREAD

**Issue by cheezgi** [termux/termux-packages#191]
A timeless classic from the days of old, up there with sl, figlet, and fortune. The "one thing" missing from this excellent program. (along with fortune)

**Comment by Neo-Oli** [comment]
In the meantime, you can get a pretty good cowsay clone from PyPI. 
`pip install pysay`
It comes with the python snake as default cow. You need to download the other cows manually, perhabs from this github mirror:
`svn checkout https://github.com/piuccio/cowsay/trunk/cows $PREFIX/share/cows`
If you want to have it behave exactly like cowsay add the following to your `.bash_profile`/`.zshrc`
`alias cowsay="pysay -f default.cow"`
`cowsay` will then still take another `-f` parameter if you want to specify a different cowfile. 

There's also a pretty good python2 clone of fortune.
`pip2 install pyfortune`
(which can be called by `fortune`)

If you do all this `fortune | cowsay` will work.

**Comment by Neo-Oli** [comment]
There is also a pretty good nodejs version that just work, without the need to get the cowfiles or do the alias. 
`npm install -g cowsay`

**Comment by fornwall** [comment]
The classic cowsay is now just an `apt install cowsay` away :).

Note that `fortune` was also recently added.
