### ISSUE TITLE
[Package]: dateutils

### ISSUE THREAD

**Issue by JacksonChen666** [termux/termux-packages#19109]
### Why is it worth to add this package?

dateutils is a collection of command line tools for date related stuff. The dateutils tools could be used in shell scripts when dealing with dates, or just in general on the command line.

### Home page URL

https://www.fresse.org/dateutils/

### Source code URL

https://github.com/hroptatyr/dateutils

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by TomJo2000** [comment]
How exactly does this improve on the functionality of the standard `date` command from coreutils?

I don't foresee this being particularly complicated to package, but it seems like a crutch for not learning how to use the standard version of `date` properly.
Unless I'm missing something this doesn't add any functionality that date and maybe some basic control flow couldn't provide.

**Comment by TomJo2000** [comment]
Upon further contemplation, eh yeah this is actually widely packaged and provides some nice utilities.
I guess I can give compiling it a try.

**Comment by TomJo2000** [comment]
Right, I assigned myself the issue so I wouldn't forget about it.
Went on vacation.
And promptly forgot about it.

Sorry about that.
I'll see about getting it building.

**Comment by jarofromel** [comment]
Thanks a lot @TomJo2000 for your work!

**Comment by TomJo2000** [comment]
Biswa got it working.
