### ISSUE TITLE
gnupg2: trust-model tofu+pgp

### ISSUE THREAD

**Issue by rqcy** [termux/termux-packages#1911]
Please enable trust-model tofu+pgp in gpg2.

I have the following line in gpg.conf:

    trust-model tofu+pgp

and when I invoke gpg2, I get an error:

    $ gpg2
    gpg: unknown trust model 'tofu+pgp'

**Comment by fornwall** [comment]
Thanks - this should be supported in the updated gnupg2 package at version 2.2.3-1, to which you can update to with `pkg up` - let me know if there are any problems!

**Comment by rqcy** [comment]
> Thanks - this should be supported in the updated gnupg2 package at
> version 2.2.3-1, to which you can update to with `pkg up` - let me
> know if there are any problems!

There are no problems. ;-)

Thanks!
