### ISSUE TITLE
[Package]: ponysay

### ISSUE THREAD

**Issue by duanemoody** [termux/termux-packages#19112]
### Why is it worth to add this package?

It's funnier, more colorful and more configurable than cowsay. 

### Home page URL

https://github.com/erkin/ponysay?tab=readme-ov-file

### Source code URL

https://github.com/erkin/ponysay

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
https://github.com/termux/termux-packages/pull/20485#pullrequestreview-2108413232
