### ISSUE TITLE
[Package]: Update telegram-bot-api to 7.0

### ISSUE THREAD

**Issue by Sarisan** [termux/termux-packages#19127]
### Why is it worth to add this package?

Current version is 6.7.1 and it's really outdated

### Source code URL

https://github.com/tdlib/telegram-bot-api

### Packaging policy acknowledgement

- [x] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
No need to remind about updates. We see al of it as soon as packages become outdated. We have no enough human resource to do that.

**Comment by Biswa96** [comment]
@Sarisan Could you test the updated package from CI if I create a pull request?

**Comment by Sarisan** [comment]
> @Sarisan Could you test the updated package from CI if I create a pull request?

Sure
