### ISSUE TITLE
[Package]: rsgain

### ISSUE THREAD

**Issue by namesarebloat** [termux/termux-packages#19132]
### Why is it worth to add this package?

rsgain is an easy, yet powerful tool to add replaygain 2.0 to pretty much any audio file. There is, to my knowledge, no other way to do this on android. An inclusion in termux would mean that I don't have to copy music, that I get on my phone, over to my desktop first.

### Source code URL

https://github.com/complexlogic/rsgain

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

Edit: okay, I managed to build it myself. The dependencies are all already in the repo, just named differently than they would be on debian and in the resulting cmake_install.cmake file I just had to find and replace a few lines.

Here's the dependency list
taglib
fmt
libinih
libebur128
ffmpeg

I opened the cmake_install.cmake file with a text editor and used find and replace to erase every instance of "/local" and replace every instance of "/usr/bin" with "/data/data/com.termux/files/usr/bin" and every instance of "/usr/share" with "/data/data/com.termux/files/usr/share"

**Comment by ponzatron** [comment]
> ### Why is it worth to add this package?
> rsgain is an easy, yet powerful tool to add replaygain 2.0 to pretty much any audio file. There is, to my knowledge, no other way to do this on android. An inclusion in termux would mean that I don't have to copy music, that I get on my phone, over to my desktop first.
> 
> ### Home page URL
> _No response_
> 
> ### Source code URL
> https://github.com/complexlogic/rsgain
> 
> ### Packaging policy acknowledgement
> * [x]  I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.
> 
> ### Additional information
> Edit: okay, I managed to build it myself. The dependencies are all already in the repo, just named differently than they would be on debian and in the resulting cmake_install.cmake file I just had to find and replace a few lines.
> 
> Here's the dependency list taglib fmt libinih libebur128 ffmpeg
> 
> I opened the cmake_install.cmake file with a text editor and used find and replace to erase every instance of "/local" and replace every instance of "/usr/bin" with "/data/data/com.termux/files/data/data/com.termux/files/usr/bin" and every instance of "/usr/share" with "/data/data/com.termux/files/data/data/com.termux/files/usr/share"

Worked incredible thank you.

**Comment by TomJo2000** [comment]
PR is open, I wanna do some on-device testing before I merge it.

**Comment by TomJo2000** [comment]
Just merged, should be available on the repos within a couple hours.
