### ISSUE TITLE
[Bug]: python dependency not found 

### ISSUE THREAD

**Issue by RohitVerma882** [termux/termux-packages#19158]
### Problem description

Python dependency

shiboken6 >= 6.4.0.1
pyside6 >= 6.4.0.1

Not found 

### What steps will reproduce the bug?

Install requirements.txt

### What is the expected behavior?

Install requirements.txt

### System information

termux-info:

```

```

**Comment by Biswa96** [comment]
qt6 packages are absent in termux packages.

**Comment by Biswa96** [comment]
qt6 is now available. Those python dependencies can now be installed.
