### ISSUE TITLE
[Bug]: package-updates ci error

### ISSUE THREAD

**Issue by ytest6710** [termux/termux-packages#19163]
### Problem description

Package Updates CI got error while running:
```could not read Username for 'https://github.com/': terminal prompts disabled```

### What steps will reproduce the bug?

Schedule a package updates every 6 hours

### What is the expected behavior?

Package updates is working!

### System information

termux-info:

```
GitHub CI Actions
```

**Comment by agnostic-apollo** [comment]
termuxbot2 token got expired, it has already been updated by grimler, should work for next schedule.
