### ISSUE TITLE
most termux-* features don't work on Oreo

### ISSUE THREAD

**Issue by etherealmccoy** [termux/termux-packages#1918]

**Comment by etherealmccoy** [comment]
termux-location
cmd: Can't find service: activity

**Comment by tinydynamite00** [comment]
@etherealmccoy Are you having this problem with both the Termux-API add-on and the termux-api pkg from the main repository installed?

**Comment by etherealmccoy** [comment]
hi. termux and termux-api apps are installed from Play store. is that not
enough?

**Comment by etherealmccoy** [comment]
also pkg install termux-api says
termux-api is already the newest version (0.24).

**Comment by Grimler91** [comment]
Hi, this is a duplicate of https://github.com/termux/termux-api/issues/105. Subscribe to that issue for the latest development.
