### ISSUE TITLE
[Bug]: command-not-found giving misleading reply

### ISSUE THREAD

**Issue by learningBASh** [termux/termux-packages#19199]
### Problem description

[Bug]: command-not-found giving misleading reply 'cannot execute: a required file is missing' when running `which` you should expect command-not-found to reply with 'command not found' when which is not found. I have a discussion to reference to be linked [HERE](https://github.com/termux/termux-app/discussions/3830). https://github.com/termux/termux-app/discussions/3830

### What steps will reproduce the bug?

$ which

### What is the expected behavior?

You should expect command-not-found to reply with 'command not found' when a command is not found. Not a misleading 'cannot execute: a required file is missing' which reply may in language rightly be construed to mean the command was in place but missing some dependency such as a lib. 

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=3883
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main stable main
Updatable packages:
apt/stable 2.7.10 arm [upgradable from: 2.7.7]
bash/stable 5.2.26 arm [upgradable from: 5.2.15-1]
ca-certificates/stable 1:2023.12.12 all [upgradable from: 1:2023.08.22]
command-not-found/stable 2.4.0-11 arm [upgradable from: 2.4.0-5]
curl/stable 8.6.0 arm [upgradable from: 8.5.0]
debianutils/stable 5.16 arm [upgradable from: 5.15]
dos2unix/stable 7.5.2 arm [upgradable from: 7.5.1]
gh/stable 2.43.1 arm [upgradable from: 2.42.1]
git/stable 2.43.1 arm [upgradable from: 2.43.0]
glib/stable 2.78.4 arm [upgradable from: 2.78.3]
gnupg/stable 2.4.4 arm [upgradable from: 2.4.3]
gpgv/stable 2.4.4 arm [upgradable from: 2.4.3]
libcurl/stable 8.6.0 arm [upgradable from: 8.5.0]
libexpat/stable 2.6.0 arm [upgradable from: 2.5.0-1]
liblzma/stable 5.4.6 arm [upgradable from: 5.4.5]
libnghttp2/stable 1.59.0 arm [upgradable from: 1.58.0]
libnpth/stable 1.6-2 arm [upgradable from: 1.6-1]
openssl/stable 1:3.2.1 arm [upgradable from: 1:3.1.4]
termux-tools/stable 1.40.6 all [upgradable from: 1.40.1]
xz-utils/stable 5.4.6 arm [upgradable from: 5.4.5]
zlib/stable 1.3.1 arm [upgradable from: 1.3-3]
termux-tools version:
1.40.1
Android version:
10
Kernel build information:
Linux localhost 4.14.141+ #1 SMP PREEMPT Mon Oct 23 18:01:40 CST 2023 armv7l Android
Device manufacturer:
Hot Pepper Inc
Device model:
HPP-L55B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by landfillbaby** [comment]
have you tried updating? does that fix it?

**Comment by learningBASh** [comment]
> have you tried updating? does that fix it?

hi landfillbaby, no I opted to delete the entire system, looks like a fake error msg indicative of malware, if you care to you may join me in termux-rebuild using Wheeler DDC method

**Comment by learningBASh** [comment]
hi @landfillbaby landfillbaby, no I opted to delete the entire system, looks like a fake error msg indicative of malware, if you care to you may join me in termux-rebuild using Wheeler DDC method
Close with comment:
not planned
BUGGED: fake error message

**Comment by learningBASh** [comment]
BUGGED: fake error message
