### ISSUE TITLE
pkill behaves like pgrep

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#192]
I am using the arm arch. This only applies to the `procps` package. `busybox pkill` works as expected. `which pkill` points to `/data/data/com.termux/files/usr/bin/pkill`

![untitled](https://cloud.githubusercontent.com/assets/7983745/14199217/b9f5ba24-f7e2-11e5-899e-0f874c585481.png)

**Comment by fornwall** [comment]
Thanks - fixed in version `3.3.11-1` of the `procps` package!

**Comment by Neo-Oli** [comment]
That's great. The change in [src-password-store.sh.patch](https://github.com/termux/termux-packages/blob/master/packages/pass/src-password-store.sh.patch) from 
`pkill -f "^$sleep_argv0" 2>/dev/null && sleep 0.5`
 to 
`pgrep -f "^$sleep_argv0" | xargs kill 2>/dev/null && sleep 0.5`
could now be reversed. But I don't think that really matters anyway, so perhaps that line can just be omitted when the next version of pass gets released or some other bug gets fixed.
