### ISSUE TITLE
[Bug]: termux-gui-c absl linking error

### ISSUE THREAD

**Issue by tareksander** [termux/termux-packages#19214]
### Problem description

`termux-gui-c` doesn't seem to build correctly in the repo anymore, it works fine when compiled on device though.

````
CANNOT LINK EXECUTABLE "./es2gears": cannot locate symbol "_ZN4absl12lts_202301255MutexD1Ev" referenced by "/data/data/com.termux/files/usr/lib/libtermuxgui.so"...
````

The symbol seems to come from absl_synchronization, which I have included in the CMake file, and it worked previously, I don't know what exactly broke it.

### What steps will reproduce the bug?

`pkg i termux-gui-c` then try to compile and run the [es2gears demo](https://github.com/tareksander/termux-gui-c-bindings/blob/main/demos/es2gears.c) with `clang -ltermuxgui -lEGL -lGLESv2 -lm demos/es2gears.c -o es2gears && ./es2gears`.

### What is the expected behavior?

The program runs correctly.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/com.termux-S5IH5OkJxfpDZmsoLcL-3g==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=5786
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c136,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c136,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10136
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
i686
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.40.6
Android version:
10
Kernel build information:
Linux localhost 4.14.112+ #1 SMP PREEMPT Fri Sep 13 21:20:42 UTC 2019 i686 Android
Device manufacturer:
Google
Device model:
Android SDK built for x86
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.gui versionCode:8
com.termux.x11 versionCode:11

```

**Comment by Biswa96** [comment]
Did you try to rebuild the termuxgui library?

**Comment by tareksander** [comment]
In the emulator, yes. I don't know when a rebuild is triggered here in the repo, or how exactly to do that.

**Comment by TomJo2000** [comment]
> In the emulator, yes. I don't know when a rebuild is triggered here in the repo, or how exactly to do that.

Auto updates run every 6 hours for applicable packages.
Regular CI runs run on every push to the associated PR, though they need manual approval for first time contributors.

**Comment by tareksander** [comment]
I looked just now and auto-updates are enabled for the package. I just released a new version and can see if that also fixed this issue tomorrow.

**Comment by twaik** [comment]
I am not sure about this but you can try to update package version manually. Do you have write access to termux-packages repo?

**Comment by tareksander** [comment]
The last update got picked up by the auto-update, so I don't think that's needed.

**Comment by TomJo2000** [comment]
Repology happened to have an outage during the auto update run.


https://github.com/termux/termux-packages/issues/19217#issuecomment-1939011154

**Comment by tareksander** [comment]
Well, [the bot managed to update it](https://github.com/termux/termux-packages/commit/0f2d3a91fc73dc2cf9a557aa856081d6a31ca720), I tested the deb, and it works now. Will the update be include in the repo automatically or does the repology outage affect that?

**Comment by agnostic-apollo** [comment]
Repology is separate from repo upload.

https://packages.termux.dev/apt/termux-main/pool/main/t/termux-gui-c/

https://github.com/termux/termux-packages/blob/0f2d3a91fc73dc2cf9a557aa856081d6a31ca720/.github/workflows/packages.yml#L249

**Comment by tareksander** [comment]
OK, then this should be fixed, thanks.

**Comment by agnostic-apollo** [comment]
You are welcome.
