### ISSUE TITLE
Package request: libssl-dev

### ISSUE THREAD

**Issue by thomastse2000** [termux/termux-packages#1924]
Recently when I was trying to implement cpuminer-multi in Termux, I found out that libssl-dev wasn't included in the stock git repository, much to my disappointment
Here are the generated log files. 
`$ apt-get install libssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libssl-dev`
It would be nice if it could be added to the repository so that the program can be normally executed. Thanks :)

**Comment by its-pointless** [comment]
openssl-dev

**Comment by Grimler91** [comment]
Right, the name of the package is openssl-dev in termux, as it is on ubuntu (but it is named libssl-dev on debian).

**Comment by daflame76** [comment]
I hate to revive a dead thread, but this package no longer exists.

**Comment by xeffyr** [comment]
> but this package no longer exists

This issue is 3 year as closed, many things changed from that time. Now we have merged "dev" & "non-dev" packages, so you no longer need "libssl-dev" or "openssl-dev". Just ensure that "openssl" is installed and up to date.

**Comment by daflame76** [comment]
@xeffyr Thanks for the update.  I'm sure this will be useful for others landing here.
