### ISSUE TITLE
[Package]: Upgrade ghostscript to 10.02.1

### ISSUE THREAD

**Issue by Mark-Joy** [termux/termux-packages#19241]
### Why is it worth to add this package?

Please upgrade ghostscript to 10.02.1

### Source code URL

https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10021/ghostpdl-10.02.1.tar.gz

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
No need to ask for package updates. We see if there are new versions as soon as they are available, but have no enough human resource to process them.
