### ISSUE TITLE
> I will get some reward for telling it in brief

### ISSUE THREAD

**Issue by Kaliarmaan** [termux/termux-packages#19249]
> I will get some reward for telling it in brief

Do you think your post deserves any reward? Nope.

_Originally posted by @sylirre in https://github.com/termux/termux-packages/issues/19248#issuecomment-1945088863_
  Bro listen user like me who are reporting the bugs are making termux improve day by day and you can ask anyone website gives reward if we report bugs

**Comment by agnostic-apollo** [comment]
Since you are spamming our security advisory and issues with useless posts without any actual issue, congratz on a 1 day ban. We may give rewards for vulnerabilities, but not for bugs, especially bugs that aren't actually submitted.
