### ISSUE TITLE
[![Packages](https://github.com/termux/termux-packages/actions/workflows/packages.yml/badge.svg?branch=master)](https://github.com/termux/termux-packages/actions/workflows/packages.yml)

### ISSUE THREAD

**Issue by JefriReynaldi** [termux/termux-packages#19255]
[![Packages](https://github.com/termux/termux-packages/actions/workflows/packages.yml/badge.svg?branch=master)](https://github.com/termux/termux-packages/actions/workflows/packages.yml)

_Originally posted by @JefriReynaldi in https://github.com/termux/termux-packages/issues/19088#issuecomment-1946856341_

**Comment by twaik** [comment]
No.
