### ISSUE TITLE
Package request: grc

### ISSUE THREAD

**Issue by tasmo** [termux/termux-packages#1926]
Although the **Generic Colouriser** [`grc`](https://github.com/garabik/grc) is available through pip it cannot be installed easily with pip.

There is a native package for Debian as well.

**Comment by Grimler91** [comment]
Seems quite easy to install it from the sources:

```
# From suitable folder
git clone https://github.com/garabik/grc
cd grc
# Fix shebangs
find . -type f -exec termux-fix-shebang {} \;
# Install into $PREFIX
./install.sh $PREFIX $PREFIX
# done
```

**Comment by tasmo** [comment]
That is a nice first approach. One just get no necessary updates through a package manager.

**Comment by Grimler91** [comment]
True. But to update you can simply `git pull` and then redo the installation.

The sources hasn't been updated in 8 months so I don't think updates happen so often.

Closing as upstream patching is needed if the package is to be installable through pip, and it is fairly easy to install from sources.

**Comment by j16180339887** [comment]
I think you need to copy all grc conf files to `~/.grc`

Otherwise you won't get colored output.

see also https://github.com/garabik/grc/issues/102
