### ISSUE TITLE
[Bug]: graphviz -- remove_overlap: Graphviz not built with triangulation library

### ISSUE THREAD

**Issue by StevanWhite** [termux/termux-packages#19261]
### Problem description

This is in Termux 0.118.0 on an MT8183 tablet running Android 12, graphviz 10.0.1
with pydot 2.0.0, and the Python graphviz 0.20.1 package.
with the attached script "graphviz-problem.py" and dot file "K_5-cross.dot":

`python graphviz-problem.py`
`"dot" with args ['-Tsvg', '/data/data/com.termux/files/usr/tmp/tmpnt44uiqc'] returned code: 1`
(spits out the SVG code)
`Error: remove_overlap: Graphviz not built with triangulation library`

[problem_example.zip](https://github.com/termux/termux-packages/files/14314855/problem_example.zip)

On my Linux Mint desktop system, with pydot 1.4.2 from the distro installer, it runs and creates the SVG file. 
I also tried removing the distro pydot, and using pip to install pydot 2.0,0.  The example script still runs properly there.

This appears to be a problem with the dot binary on Android.

### What steps will reproduce the bug?

Run the script 
`python graphviz-problem.py`
It will produce output like this:

`"dot" with args ['-Tsvg', '/data/data/com.termux/files/usr/tmp/tmpnt44uiqc'] returned code: 1`
(spits out the SVG code)
`Error: remove_overlap: Graphviz not built with triangulation library`

### What is the expected behavior?

When the script is run, it converts the included `K_5-cross.dot` to `K_5-cross.svg`

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=22672
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
android-tools/stable 34.0.4-4 aarch64 [upgradable from: 34.0.4-3]
ghostscript/stable 10.02.1 aarch64 [upgradable from: 10.02.0]
git/stable 2.43.2 aarch64 [upgradable from: 2.43.1]
gst-plugins-bad/stable 1.22.10 aarch64 [upgradable from: 1.22.9]
gstreamer/stable 1.22.10 aarch64 [upgradable from: 1.22.9]
libprotobuf/stable 2:25.1 aarch64 [upgradable from: 2:22.4-2]
libunbound/stable 1.19.1 aarch64 [upgradable from: 1.19.0]
libusb/stable 1.0.27 aarch64 [upgradable from: 1.0.26-1]
pcre2/stable 10.43 aarch64 [upgradable from: 10.42]
unbound/stable 1.19.1 aarch64 [upgradable from: 1.19.0]
vlc/stable 3.0.20-4 aarch64 [upgradable from: 3.0.19]
vulkan-loader/stable 0.0.3 all [upgradable from: 0.0.2]
termux-tools version:
1.40.6
Android version:
12
Kernel build information:
Linux localhost 4.19.191 #1 SMP PREEMPT Fri Aug 25 12:07:06 CST 2023 aarch64 Android
Device manufacturer:
jumper
Device model:
EZpad M10 SE
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

**Comment by StevanWhite** [comment]
`pkg install graphviz`
`pip install pydot`
`pip install graphviz`

**Comment by Biswa96** [comment]
I have added libgts dependency with graphviz and it fixes the error. The following image shows the generated image file (converted to png for convenience).

![K_5-cross](https://github.com/termux/termux-packages/assets/31443074/07744e21-60d2-44ea-818c-8789e34188c9)

**Comment by StevanWhite** [comment]
Yes, Biswa96, the output should look something like that!

I just did an upgrade, but I didn't see any changes.  When can I expect that?
Or... should I do something special?

**Comment by Biswa96** [comment]
You could test the new packages from the linked PR's CI artifact or wait for the PR to be merged.

**Comment by StevanWhite** [comment]
works!  Thanks!!
