### ISSUE TITLE
Update Rust to 1.76

### ISSUE THREAD

**Issue by doonv** [termux/termux-packages#19277]
### Why is it worth to add this package?

The Bevy game engine requires Rust 1.76 in order to compile.

### Home page URL

https://rust-lang.org

### Source code URL

https://github.com/rust-lang/rust

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
No need to ask for package updates. We see all new versions as soon as they are available but have no enough people to update packages. Pull requests are always welcome.
