### ISSUE TITLE
Include `xvfb-run` in the xorg-server-xvfb package

### ISSUE THREAD

**Issue by knyipab** [termux/termux-packages#19288]
Could termux-packages consider to include the shell script `xvfb-run` in the xorg-server-xvfb package? Indeed, many distro repository distributes `xvfb-run` in their xvfb packages. I am currently writing a package `build.sh` that requires x server and uses `xvfb-run` (on-device build). 
* Debian version of `xvfb-run`: https://salsa.debian.org/xorg-team/xserver/xorg-server/-/blob/debian-unstable/debian/local/xvfb-run
* Archlinux version of `xvfb-run` (seems newer): https://gitlab.archlinux.org/archlinux/packaging/packages/xorg-server/-/blob/main/xvfb-run?ref_type=heads

If it is not suitable to add this into the main repository, I am happy to contribute another in TUR. However, it seems more resonable to  get `xvfb-run` through `pkg install xorg-server-xvfb` as other distros do so.

**Comment by twaik** [comment]
Fixed by 6e216884019f4662d4981c17f5704a95d34e2b2e .
