### ISSUE TITLE
[Package]: git with git-http-push support

### ISSUE THREAD

**Issue by kesiev** [termux/termux-packages#19290]
### Why is it worth to add this package?

Using Webdav to host a GIT repository is a way to use cheap hosting services with basic scripting support to serve a private repository for personal projects/small teams.

### Home page URL

https://git-scm.com/docs/git-http-push

### Source code URL

https://mirrors.kernel.org/pub/software/scm/git/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by thunder-coding** [comment]
Git needs to be built with libexpat for http-push to work

**Comment by TomJo2000** [comment]
`libexpat` is already packaged so that shouldn't be an issue.
