### ISSUE TITLE
New dalvikvm wrapper in termux-tools breaks jack

### ISSUE THREAD

**Issue by joakim-noah** [termux/termux-packages#193]
The jack compiler needs `/system/lib` in its `LD_LIBRARY_PATH`, but the new dalvikvm wrapper sets it to an empty string right before executing `/system/bin/dalvikvm`.  Removing that last empty `LD_LIBRARY_PATH` in the dalvikvm wrapper works around the issue for me.

**Comment by michalbednarski** [comment]
I think we should `unset LD_LIBRARY_PATH` there and remove whole LD_LIBRARY_PATH logic from `jack.sh`.

Previously Jack didn't work on my phone because it has `/system/lib64` (with one unused library) folder despite being 32-bit device

**Comment by fornwall** [comment]
This should now be fixed - reopen this issue if the problem remains after an `apt update && apt upgrade`.

@michalbednarski Interesting with the `/system/lib64` folder existing on a 32-bit device. I've switched to using `getprop ro.product.cpu.abilist64` to check if the device is a 32-bit one.
