### ISSUE TITLE
[Package]: kbd

### ISSUE THREAD

**Issue by natebragg** [termux/termux-packages#19315]
### Why is it worth to add this package?

I would like this package because I would like to be able to use `showkey` to track key presses from the command line.

### Home page URL

https://kbd-project.org/

### Source code URL

https://github.com/legionus/kbd/tree/master

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

I have not tried to compile it.  I am new to termux.

**Comment by TomJo2000** [comment]
I have previously sent in a PR to package it.
- https://github.com/termux/termux-packages/pull/17841
I'll probably do some minor reworking and resume work on it.

**Comment by TomJo2000** [comment]
If I recall correctly, the other parts of kbd aren't really applicable to Termux so we'll probably just wanna package `showkey`, I'll need to take another look at it.

**Comment by natebragg** [comment]
Any hope for progress on this?  I need showkey to help diagnose a different issue a different issue.

**Comment by TomJo2000** [comment]
Well I was gonna work on it.
And then I forgot about it and had a lovely vacation to London.

I have updated the branch linked to #17841, so [you can grab the .deb from the CI run](https://github.com/termux/termux-packages/actions/runs/8251949253?pr=17841) in the meantime, but I still need to fixup the build script so it only ends up packaging `showkey`, since the rest of `kbd` doesn't apply to Termux.

**Comment by natebragg** [comment]
You're my hero.  Hooray!  I hope you had a great vacay.

**Comment by natebragg** [comment]
Hi, just checking, can this issue be closed?  I don't see the package using pkg.

**Comment by TomJo2000** [comment]
Sorry I've had a lot to deal with personally.
I haven't gotten around to it.
When it gets merged this issue will be closed automatically.

**Comment by TomJo2000** [comment]
@natebragg package just got merged.
Should be available at your mirror of choice within a couple hours.

**Comment by natebragg** [comment]
Huzzah!  Thanks to you I could immediately diagnose the issue I was having. :^D

**Comment by eMPee584** [comment]
Uhm, doesn't work for me on a titan2 (android 15 with physical keyboard), neither as default termux user nor as root with `tsu`:

<img width="1436" height="1440" alt="Image" src="https://github.com/user-attachments/assets/51b1e7fb-c1be-45a6-8a53-517c24d03ac9" />

Does it still work for you? `strace showkey` output seen at the top shows the `KDGKBTYPE` ioctls fail with `ENOTTY` .. 🤔
