### ISSUE TITLE
[Package]: gcc

### ISSUE THREAD

**Issue by 1Q23LYC45** [termux/termux-packages#19310]
### Why is it worth to add this package?

Many C language programs require gcc compilation and cannot be compiled through clang. 
I always find that for the same software, gcc can compile normally, but there are compilation errors in clang.

### Home page URL

https://gcc.gnu.org

### Source code URL

https://gcc.gnu.org/git/gcc

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
Gcc was removed for a reason. https://github.com/termux/termux-packages/commit/768ce14ecc1048cdfc8fcf0d51baaba5c33a163b

**Comment by 1Q23LYC45** [comment]
> Gcc was removed for a reason. [768ce14](https://github.com/termux/termux-packages/commit/768ce14ecc1048cdfc8fcf0d51baaba5c33a163b)

Thank you very much.

**Comment by 1Q23LYC45** [comment]
> Available in https://github.com/termux-user-repository/tur.
> 
> > I always find that for the same software, gcc can compile normally, but there are compilation errors in clang
> 
> Are you sure? How did you tested this in Termux without GCC installed?
> 
> The main issue is not compiler, but Android libc and NDK headers which are far different from what is supplied by GNU libc. After changing the compiler you still need to apply patches to software when it errors.
> 
> Sources of all Termux compilation issues:
> 
> * https://wiki.termux.com/wiki/Differences_from_Linux
> * https://github.com/termux/termux-packages/wiki/Common-porting-problems (this one I suppose incomplete)
> 
> All of software provided in Termux is compiled using Clang - besides code (the code going to be compiled) compatibility with Android, there no issues.

OK, I'll try tur packages. Thank you.
