### ISSUE TITLE
Package request gst-python

### ISSUE THREAD

**Issue by araczkowski** [termux/termux-packages#1932]
Hi,
this is the part of gstremer 
https://gstreamer.freedesktop.org/src/gst-python/

having the gst-python package it should be possible to run mopidy on termux 

thx

**Comment by xeffyr** [comment]
Requires at least `python-gobject` as dependency but we do not package python modules.

**Comment by Grimler91** [comment]
Re-opening, I think we could make an exception for gst-python and python-gobject, but packaging them would be quite hard since cross-compilation with python is not really supported. If anyone gives it a try, let is know how it goes!

**Comment by xeffyr** [comment]
Before this `python-gobject` we need to get `gobject-introspection` to be available.

**Comment by xtkoba** [comment]
Now `gobject-introspection` is already packaged. But yeah, cross-building python modules is not at all trivial and needs some hacks, as we saw in #6970 with `gobject-introspection` itself.

**Comment by xtkoba** [comment]
Now that we have `termux_setup_python_crossenv`, it should not be difficult to cross-build Python modules.

The next hurdle is that gir is not trivial to cross build. See https://maxice8.github.io/8-cross-the-gir/ for example. The `meson.build` in GStreamer tarball explicitly disables building gir when cross building:

```python
build_gir = gir.found() and (not meson.is_cross_build() or get_option('introspection').enabled())
```

(The difficulty of cross-building gir also prevents https://github.com/termux/x11-packages/issues/583 from being  resolved, for reference.)
