### ISSUE TITLE
repository is under maintenance or down (wrong sources.list URL?).

### ISSUE THREAD

**Issue by n1k0byte** [termux/termux-packages#19320]
### Problem description

I was Trying To Install Python In Termux, But doesn't Work

`Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ cd
$ dir
$ ls
$ python
The program python is not installed. Install it by executing:
 pkg install python
$ pkg install python
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Get:1 https://termux.mentality.rip/termux-packages-24 stable InRelease [14.0 kB]
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  404  Not Found
Get:5 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 Packages [501 kB]
Err:6 https://dl.bintray.com/grimler/science-packages-24 science Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).`

### What steps will reproduce the bug?

pkg install python3

### What is the expected behavior?

install python3 

### System information

termux-info:

```
Packages CPU architecture:                              aarch64
Subscribed repositories:                                # sources.list
deb https://main.termux-mirror.ml/ stable main          # game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)            deb https://dl.bintray.com/grimler/science-packages-24 science stable                                           Updatable packages:
All packages up to date
Android version:
14                                                      Kernel build information:
Linux localhost 4.19.191-g2f3c0b869827 #1 SMP PREEMPT Thu Dec 14 11:45:30 CST 2023 aarch64 Android
Device manufacturer:                                    Xiaomi
Device model:                                           2303CRA44A
```

**Comment by licy183** [comment]
Duplicated #6726
