### ISSUE TITLE
[Package]: Add game music emu plugin to deadbeef

### ISSUE THREAD

**Issue by GUUser91** [termux/termux-packages#19331]
### Why is it worth to add this package?

The game music emu plugin is needed in order to play and convert video game format files like .VGZ and .VGM files in deadbeef.
License located here
https://github.com/DeaDBeeF-Player/deadbeef/blob/master/plugins/gme/game-music-emu-0.6pre/license.txt

### Home page URL

https://github.com/DeaDBeeF-Player/deadbeef/tree/master/plugins/gme

### Source code URL

https://github.com/DeaDBeeF-Player/deadbeef/tree/master/plugins/gme

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by TomJo2000** [comment]
Was a relatively simple 2 line patch to get it working, will be sending in a PR shortly.

**Comment by TomJo2000** [comment]
If you would like to test the plugin before the PR is merged, DEBs are available from the CI run artifacts.
https://github.com/termux/termux-packages/actions/runs/8017027468?pr=19332

Just can install it from the downloaded DEB using `pkg i /path/to/package.deb`

**Comment by GUUser91** [comment]
I'm not sure if I installed it correctly. I dragged and dropped the game music files to deadbeef and nothing happened.  Can you test these files out, just drag and drop the audio files to deadbeef
https://vgmrips.net/packs/pack/prop-cycle-namco-system-super-22
http://snesmusic.org/v2/profile.php?profile=set&selected=2506

**Comment by TomJo2000** [comment]
I completely forgot to bump the package revision.
Let me wait for the CI run and give it a try.

**Comment by TomJo2000** [comment]
Got sidetracked but I updated the PR.
Turns out I interpreted the change in the upstream function the wrong way around,
but the GME plugin is getting recognized by deadbeef now.

I unfortunately don't have audio set up on my Termux X11 session, so I can't test if this works right now, but its no longer throwing an immediate error.

**Comment by GUUser91** [comment]
@TomJo2000
It works. Thanks!
