### ISSUE TITLE
[Bug]: Problem Reinstalling Mobox 

### ISSUE THREAD

**Issue by ShinigamixKira** [termux/termux-packages#19345]
### Problem description

I reinstall Mobox like any other tutorial stuff download termux etc,copy code at github etc.after I done paste code and it complete downloading,when I run code "mobox" as supposed like usual,it create weird error I don't understand.Can anyone help me?

### What steps will reproduce the bug?

Reinstall Mobox and paste code,then run "Mobox"

### What is the expected behavior?

It shows error

### System information

termux-info:

```

```

**Comment by twaik** [comment]
Mobox is a 3rd party project we offer zero support for. Open issue at https://github.com/olegos2/mobox .
