### ISSUE TITLE
[Bug]: Neovim LSP server not attaching in Termux

### ISSUE THREAD

**Issue by HaroonSaifi17** [termux/termux-packages#19342]
### Problem description

The Neovim LSP server is not attaching even though it is configured correctly. Upon attempting to use the LSP features, such as code completion or diagnostics, they do not function as expected. Previous versions of Neovim worked fine, and this version is functioning correctly in other Linux distributions.

### What steps will reproduce the bug?

1.Open Neovim in Termux.
2.Ensure LSP server configuration is correctly set up.
3.Attempt to use LSP features, such as code completion or diagnostics.

### What is the expected behavior?

The Neovim LSP server should attach and provide expected functionality for LSP features like code completion and diagnostics.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=24780
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.quantum5.ca/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirror.quantum5.ca/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://mirror.quantum5.ca/termux/termux-x11 x11 main
Updatable packages:
bash-completion/stable 2.12.0 all [upgradable from: 2.11-2]
c-ares/stable 1.27.0 aarch64 [upgradable from: 1.26.0]
git/stable 2.44.0 aarch64 [upgradable from: 2.43.2]
libsmartcols/stable 2.39.3-4 aarch64 [upgradable from: 2.39.3-3]
libuuid/stable 2.39.3-4 aarch64 [upgradable from: 2.39.3-3]
nodejs-lts/stable 20.11.1-1 aarch64 [upgradable from: 18.16.1-2]
util-linux/stable 2.39.3-4 aarch64 [upgradable from: 2.39.3-3]
termux-tools version:
1.40.6
Android version:
14
Kernel build information:
Linux localhost 4.14.186-perf-gfe971f1c1fe2 #1 SMP PREEMPT Sat Oct 7 08:46:56 UTC 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
22087RA4DI
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by agnostic-apollo** [comment]
Possible duplicate of https://github.com/termux/termux-app/issues/3855

**Comment by agnostic-apollo** [comment]
Read the comments in linked issue and follow them.

**Comment by HaroonSaifi17** [comment]
Thanks, it works after installing the provided 'termux-exec'. Appreciate the assistance.
