### ISSUE TITLE
[Bug]: postgresql package isn't working 

### ISSUE THREAD

**Issue by mohamedxtestx** [termux/termux-packages#19351]
### Problem description

Whenever i try to Connect to a postgres database i get segmentation fault.
I was using "psycopg2" in python. So i thought the problem is with that driver but then i tried "psql" command and got the same error

### What steps will reproduce the bug?

Trying to connect to a postgres database in termux 

### System information

termux-info:

```
[1]    11467 segmentation fault  python p.py
```

**Comment by Biswa96** [comment]
Could you provide steps to reproduce the issue?

**Comment by mohamedxtestx** [comment]
pkg install postgresql

pip install psycopg2 

Then use psycopg2 in any python script
Like this for example. 
(This code is generated by chat gpt since i am using sqlalchemy in my actaul project and just wanted a sample code to test it.
But it gave the same error there too)
`
import psycopg2

def print_schema():
    # Establish a connection to the database
    conn = psycopg2.connect(
        dbname="your_database_name",
        user="your_username",
        password="your_password",
        host="your_host",
        port="your_port"
    )

    # Create a cursor object to execute SQL commands
    cur = conn.cursor()

    try:
        # Execute SQL query to retrieve the schema
        cur.execute("SELECT table_name, column_name, data_type FROM information_schema.columns WHERE table_schema = 'public'")

        # Fetch results
        rows = cur.fetchall()

        # Print schema
        for row in rows:
            table_name, column_name, data_type = row
            print(f"Table: {table_name}, Column: {column_name}, Data Type: {data_type}")
    except psycopg2.Error as e:
        print("Error fetching schema:", e)
    finally:
        # Close cursor and connection
        cur.close()
        conn.close()

# Call the function to print the schema
print_schema()
`

**Comment by mohamedxtestx** [comment]
pkg install postgresql

pip install psycopg2 

Then use psycopg2 in any python script
Like this for example. 
(This code is generated by chat gpt since i am using sqlalchemy in my actaul project and just wanted a sample code to test it.
But it gave the same error there too)
```
import psycopg2

def print_schema():
    conn = psycopg2.connect(
        dbname="your_database_name",
        user="your_username",
        password="your_password",
        host="your_host",
        port="your_port"
    )

    cur = conn.cursor()

    try:
        cur.execute("SELECT table_name, column_name, data_type FROM information_schema.columns WHERE table_schema = 'public'")

        rows = cur.fetchall()

        for row in rows:
            table_name, column_name, data_type = row
            print(f"Table: {table_name}, Column: {column_name}, Data Type: {data_type}")
    except psycopg2.Error as e:
        print("Error fetching schema:", e)
    finally:
        cur.close()
        conn.close()

print_schema()
```

**Comment by Biswa96** [comment]
I got the following error with your sample code.

```
~ $ python test.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test.py", line 28, in <module>
    print_schema()
  File "/data/data/com.termux/files/home/test.py", line 4, in print_schema
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: invalid integer value "your_port" for connection option "port"
```

**Comment by mohamedxtestx** [comment]
You have to use your own database credentials. There is just placeholders there.

**Comment by yubrajbhoi** [comment]
Yes, I noticed this a few days ago as well. If I start a PostgreSQL server on localhost it works as expected. But when I try to connect to a remote server this happens:

```
psql: error: connection to server at "32.45.243.107", port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet
connection to server at "32.45.243.107", port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet
Segmentation fault
```

**Comment by yubrajbhoi** [comment]
Good news, I managed to find a workaround. When I tried to debug it in GDB it shows the segfault coming from `libpq.so`. So I tried to compile it from source.

Postgresql `16.1` did not work, it gave the segfault as well. But version `16.2` somehow worked. The patches for `16.1` worked on `16.2` as well. Well except for `src-backend-utils-adt-xml.c.patch`, but it compiles without any error.

I also had to patch `fcntl.h` like this to enable the `sync_file_range` function:

```
--- fcntl.h.orig	2024-03-12 21:59:23.232570077 +0530
+++ fcntl.h	2024-03-12 21:59:42.116570086 +0530
@@ -254,10 +254,6 @@
  * Returns 0 on success and returns -1 and sets `errno` on failure.
  */
 
-#if __ANDROID_API__ >= 26
-int sync_file_range(int __fd, off64_t __offset, off64_t __length, unsigned int __flags) __INTRODUCED_IN(26);
-#endif /* __ANDROID_API__ >= 26 */
-
 
 #endif
 
```

Anyway, here is the compiled package if anyone wants to try it out:

[postgresql-16.2-aarch64.zip](https://github.com/termux/termux-packages/files/14575832/postgresql-16.2-aarch64.zip)

This is compiled on a Pixel 6a with `-D__ANDROID_API__=27`. I don't know if this will run on another phone without any bugs.

@truboxl @licy183 Can you guys look into this and bump `postgresql` to `16.2`?

**Comment by licy183** [comment]
I still want to know more about this. What is the version of your remote postgresql? I have tested and cannot reproduce with pgsql 15.1/16.1/16.2.

**Comment by yubrajbhoi** [comment]
@licy183 Remote postgresql is version `16.2` hosted on a normal GCP server. I have tried it with other versions as well, same segfault. Here is the output:

```
psql: error: connection to server at "65.24.254.243", port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet
connection to server at "65.24.254.243", port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet
Segmentation fault
```

Same thing happens if I try to connect in Python using `psycopg`:

```python
import psycopg

conn = psycopg.connect(host="65.24.254.243", user="testuser", dbname="test", password="ry56fhd7rf")
conn.close()
```

```bash
$ python connect.py
Segmentation fault
```

Connection using the local Unix socket works, but everything else causes the segfault.

Here is a GDB backtrace, IDK how useful it is:

```
psql: error: connection to server at "65.24.254.243", port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet
connection to server at "65.24.254.243", port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet

Program received signal SIGSEGV, Segmentation fault.
0x0000007ff3f069d8 in scudo::Allocator<scudo::AndroidNormalConfig, &scudo_malloc_postinit>::deallocate(void*, scudo::Chunk::Origin, unsigned long, unsigned long) ()
   from /apex/com.android.runtime/lib64/bionic/libc.so
(gdb) backtrace
#0  0x0000007ff3f069d8 in scudo::Allocator<scudo::AndroidNormalConfig, &scudo_malloc_postinit>::deallocate(void*, scudo::Chunk::Origin, unsigned long, unsigned long) ()
   from /apex/com.android.runtime/lib64/bionic/libc.so
#1  0x0000007ff1c62d8c in ?? ()
   from /data/data/com.termux/files/usr/lib/libpq.so.5.16
#2  0x00000055555cc6a8 in ?? ()
#3  0x0000007ff3f11e1c in __libc_init ()
   from /apex/com.android.runtime/lib64/bionic/libc.so
```

Here is `termux-info`:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1+5f1c08e
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=11982
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.41.1
Android version:
14
Kernel build information:
Linux localhost 5.10.189-android13-4-00012-g1217bb583cc5-ab11174560 #1 SMP PREEMPT Mon Dec 4 18:59:42 UTC 2023 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 6a
LD Variables:
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/opt/lib:/data/data/com.termux/files/usr/lib:
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.window versionCode:15
com.termux.api versionCode:51
```

Anyway, using the `libpq.so` from version `16.2` fixed it for me, even when using the default `psql-16.1` version.

**Comment by licy183** [comment]
I suppose this is an issue for Android 14 devices, so I asked @2096779623 to test, but he also did not succeed in reproducing the issue on his Android 14 device, so it doesn't seem to be an issue for Android 14 devices either.

Anyway, please download the deb files in https://github.com/termux/termux-packages/actions/runs/8284559286 and test. Thanks!

**Comment by yubrajbhoi** [comment]
@licy183 Thanks for your work. I tested the new deb and it works. It's weird you were not able to reproduce it, maybe it is a bug on Pixel phones.

**Comment by mohamedxtestx** [comment]
It also didn't work on my phone (xiaomi android 12).
But the new package did work.
Thanks.
