### ISSUE TITLE
[Package]: emojify

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-packages#19354]
### Why is it worth to add this package?

> emojify substitutes emoji aliases that many services (like GitHub) use for emoji raw characters.

A tool to replace emoji code like `:bug:` to :bug: in any text like the output of `git log`.

### Home page URL

https://github.com/mrowa44/emojify

### Source code URL

https://github.com/mrowa44/emojify

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by TomJo2000** [comment]
This is a pure bash script.
It doesn't need additional packaging, just download and run it.

**Comment by Freed-Wu** [comment]
No serious. I can package it to TUR. It should not be very hard :smile:

**Comment by TomJo2000** [comment]
It should not require packaging.
The installation one-liner from the upstream repo works with minimal adjustment.
```bash
curl https://raw.githubusercontent.com/mrowa44/emojify/master/emojify -o "./emojify" && chmod +x "./emojify"
```

**Comment by Freed-Wu** [comment]
> curl https://raw.githubusercontent.com/mrowa44/emojify/master/emojify -o "$PREFIX/bin/emojify" && chmod +x "$PREFIX/bin/emojify"

Thanks for your answer. I think `apt install` should be shorter for `curl XXX` :smile:

> Neofetch is a special case which is packaged by exceeding popular demand

emojify have 1.5k stars, which can prove it is popular, IMO.

https://github.com/termux-user-repository/tur/pull/853

**Comment by TomJo2000** [comment]
> emojify have 1.5k stars, which can prove it is popular, IMO.

This is the first and only mention of it anywhere in the entire Termux Org.
- https://github.com/search?q=org%3Atermux+emojify&type=issues

I understand you like the script, but it's not in need of packaging.

**Comment by Freed-Wu** [comment]
No serious. This problem is solved and All is OK.

> This is the first and only mention

I see. Thanks for explaining the popularity.
