### ISSUE TITLE
Help needed regarding scipy

### ISSUE THREAD

**Issue by Soft-Buddy** [termux/termux-packages#19360]
https://github.com/termux/termux-packages/blob/fede87cbd401a644fa5782fdf59a9790f6f98e12/packages/python-scipy/build.sh#L17

As we see here, `numpy-cross-file.txt` file is being used for cross compilation. I'm trying to manually cross compile scipy source (with some modifications). Where can I find that file so that I can manually compile scipy? 

Any guidance will be appreciated.

**Comment by Biswa96** [comment]
> Where can I find that file so that I can manually compile scipy?

Try to compile the python-scipy package with the procedure from here https://github.com/termux/termux-packages/wiki/Building-packages. The cross file can be found in /home/builder/.termux-build/python-scipy/tmp/numpy-cross-file.txt path in the termux-package-builder container.

**Comment by licy183** [comment]
This file is auto-generated by the building system. You can find the steps in [termux_setup_meson.sh](https://github.com/termux/termux-packages/blob/master/scripts/build/setup/termux_setup_meson.sh).

**Comment by Soft-Buddy** [comment]
Thank you all for your help. I appreciate that !
