### ISSUE TITLE
[Bug]: flang installation fails

### ISSUE THREAD

**Issue by StevanWhite** [termux/termux-packages#19362]
### Problem description

Package `flang` fails to install, resulting in a partial install.

Without it, I don't have a FORTRAN compiler that works under Termux.

Find attached the installer output.
[flang.err.gz](https://github.com/termux/termux-packages/files/14417370/flang.err.gz)

### What steps will reproduce the bug?

pkg install flang
...
error: Semantic errors in /data/data/com.termux/files/usr/opt/flang/module/__ppc_intrinsics.f90
/data/data/com.termux/files/usr/opt/flang/module/__ppc_intrinsics.f90:39:3: error: Vector type is only supported for PowerPC
    ELEM_FUNC_VIVI(1) ELEM_FUNC_VIVI(2) ELEM_FUNC_VIVI(4) ELEM_FUNC_VIVI(8)
... 

### What is the expected behavior?

the package should install normally

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=939
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
openjpeg/stable 2.5.1 aarch64 [upgradable from: 2.5.0-1]
termux-tools version:
1.40.6
Android version:
12
Kernel build information:
Linux localhost 4.19.191 #1 SMP PREEMPT Fri Aug 25 12:07:06 CST 2023 aarch64 Android
Device manufacturer:
jumper
Device model:
EZpad M10 SE
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51

```

**Comment by TomJo2000** [comment]
Can confirm the behavior.
We could probably disable the PPC module.
https://github.com/termux/termux-packages/blob/2f8860fd5f00006fd80104d6104554927b5e89ed/packages/flang/postinst.sh.in#L5-L18
I think it's safe to assume that not shipping IBM PowerPC support in 2024 wouldn't be a huge loss.

I'm unfortunately unfamiliar with Fortran though, so I'll ping @licy183 as the latest maintainer of the `flang` package.

**Comment by licy183** [comment]
Bumping flang to 17.0.6 should resolve this. Thanks for your report!

**Comment by StevanWhite** [comment]
Hey, it installs now!  Thanks!

However, it doesn't quite work as expected.  Filed a separate problem report:
https://github.com/termux/termux-packages/issues/19373
