### ISSUE TITLE
fatal: unable to access 'https://github.com/libcpr/cpr/': SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Toni500github** [termux/termux-packages#19377]
Everytime I try to `git pull` or `git clone` any **existing** repo, appears always this error on the title. 

The worst thing is that all the mirrors doesn't work, tried to change region but nothing, always the error "Error: None of the mirrors are accessible". So now I can't even update or install packages or use git. Please help

**Comment by Toni500github** [comment]
It works, backed up my ~ and then re-installed termux. I hope this issue doesn't happen again because I don't wanna loose my $PREFIX stuff again

**Comment by Alhajisunusi** [comment]
How to fixed this Unable to establish SSL connection.

**Comment by Toni500github** [comment]
Backup the necessary files and delete+re-install termux.

Look up above
