### ISSUE TITLE
[Bug]: flang: flang-new fails to find intrinsics libraries

### ISSUE THREAD

**Issue by StevanWhite** [termux/termux-packages#19373]
### Problem description

The FORTRAN compiler `flang-new` fails to find its libraries of intrinsic functions by default.
This appears to be a configuration issue.

### What steps will reproduce the bug?

With a FORTRAN input file, and without special flags, the `flang-new` compiler should link its output with the usual FORTRAN intrinsic functions.  

For example, with the simple attached FORTRAN file,
    `flang-new INTR.F`
should produce an executable, `a.out,` which can then be run, to produce reasonable output.

Instead, a linker error occurs:

`ld.lld: error: undefined symbol: dtime_`

Note:  This is a configuration problem.
The  `flang-new`  documentation mentions a flag
```
-fintrinsic-modules-path <dir>                              
                  Specify where to find the compiled intrinsic modules
```
but that should be used in exceptional cases where the path has been changed.

[INTR.F.gz](https://github.com/termux/termux-packages/files/14425676/INTR.F.gz)

### What is the expected behavior?

Running a.out, created as above, should produce reasonable output.

### System information

termux-info:

```
ermux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=939
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.40.6
Android version:
12
Kernel build information:
Linux localhost 4.19.191 #1 SMP PREEMPT Fri Aug 25 12:07:06 CST 2023 aarch64 Android
Device manufacturer:
jumper
Device model:
EZpad M10 SE
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

**Comment by licy183** [comment]
I can't reproduce it.

```
~ $ flang-new ./INTR.F
././INTR.F:5:12: portability: argument types do not match specific intrinsic 'dmax1' requirements; using 'max' generic instead and converting the result to REAL(8) if needed
         M = DMAX1( 1.0, 2.0 )
             ^^^^^^^^^^^^^^^^^
~ $ ./a.out
  Found max  2.
~ $
```

**Comment by StevanWhite** [comment]
HM.  Now it's working fine for me, too.
I had uninstalled it and re-installed it...
Best guess: something was left over from a previous installation.  There is an associated package `mlir`.

Closing.  Thanks!
