### ISSUE TITLE
[Package]: vulkan khronos validation layers

### ISSUE THREAD

**Issue by Sirox228** [termux/termux-packages#19381]
### Why is it worth to add this package?

provides debugging for vulkan code

### Home page URL

https://github.com/KhronosGroup/Vulkan-ValidationLayers

### Source code URL

https://github.com/KhronosGroup/Vulkan-ValidationLayers

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by truboxl** [comment]
Does it even work?

**Comment by Sirox228** [comment]
it's difenetely working. if you compile a vulkan program with the validation layer and don't see any info/debug/verbose messages when running it, that means that everything is fine. i can provide some test code if you wish. almost all distros have this validation layer packaged.

**Comment by Trass3r** [comment]
Has been done already: https://www.reddit.com/r/termux/comments/16s2kl8/native_android_vulkan_loader_validation_layer/
I guess that user is @xMeM.

**Comment by Trass3r** [comment]
I gave it a quick try but needs more setup to work.
https://github.com/termux/termux-packages/compare/master...Trass3r:termux-packages:master

**Comment by Sirox228** [comment]
i managed to get to the linking state by adding `#undef __ANDROID__` to vk_layer_config.cpp and layer_settings_manager.cpp file in vulkan-utility-library, commenting out `#error` in layers/utils/android_ndk_types.h that comes when android_surface_khr is not defined and commenting out lines in CMakeLists.txt that define the android_surface_khr (also enabling xlib surface) bur linking fails with the following 
```
ld.lld: error: version script assignment of 'global' to symbol 'vkEnumerateDeviceLayerProperties' failed: symbol not defined
ld.lld: error: version script assignment of 'global' to symbol 'vkEnumerate
```
