### ISSUE TITLE
dpkg:1.22.5,python-apt:2.7.6

### ISSUE THREAD

**Issue by codenamedpkt** [termux/termux-packages#19387]
### Why is it worth to add this package?

The `dpkg` and `python-apt` has updated to the above titled of version. And it has more active links there: https://salsa.debian.org/dpkg-team/dpkg/-/archive/1.22.5.tar.gz.
https://salsa.debian.org/apt-team/python-apt/-/archive/2.7.6.tar.gz

See https://salsa.debian.org/dpkg-team/dpkg/-/tags https://salsa.debian.org/apt-team/python-apt/-/tags for updates.

### Home page URL

https://salsa.debian.org/dpkg-team/dpkg
https://salsa.debian.org/apt-team/python-apt/

### Source code URL

https://salsa.debian.org/dpkg-team/dpkg/-/archive/1.22.5.tar.gz
https://salsa.debian.org/apt-team/python-apt/-/archive/2.7.6.tar.gz

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by truboxl** [comment]
dpkg updated in https://github.com/termux/termux-packages/commit/5198e3f296a893e2e441f7353793d82d595c786f
