### ISSUE TITLE
Emacs manual missing

### ISSUE THREAD

**Issue by mklein994** [termux/termux-packages#194]
As all `info(1)` pages are removed in the [build script](https://github.com/termux/termux-packages/blob/master/build-package.sh#L454), it seems that Emacs' builtin manual is deleted in the process (usually found under `/usr/share/info`, or similar). Would it be possible to create an exception for Emacs? I'm new to Emacs, so having a manual offline would be very helpful.

On a related note, besides disk space, is there a reason why info pages are removed in general? Perhaps as a solution the info pages could be compressed before packaging?

**Comment by lajapriv** [comment]
You can copy these files from TERMUX_PKG_SRCURL=ftp://alpha.gnu.org/gnu/emacs/pretest/emacs-${TERMUX_PKG_VERSION}.tar.xz

For example:
Add to emacs init file (if TERMUX_PKG_VERSION=25.0.92):
(setq Info-directory-list '("/data/data/com.termux/files/usr/share/emacs/25.0.92/info"))

**Comment by mklein994** [comment]
Thank-you @lajapriv. However, I wonder what could be preventing `info` from becoming a package?

**Comment by fornwall** [comment]
@mklein994 I've updated the emacs package in version `25.0.92-6` to keep the info pages, thanks for pointing this out!
