### ISSUE TITLE
yarn 1.x haven been frozen, now latest version is yarn-4.x

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-packages#19407]
See the discription of https://github.com/yarnpkg/yarn

> The 1.x line is frozen - features and bugfixes now happen on https://github.com/yarnpkg/berry

**Comment by truboxl** [comment]
yarn-berry 4.x is not meant to be packaged by distro and should be installed via npm. https://github.com/yarnpkg/berry/discussions/5629#discussioncomment-6593555

So what AUR doing with yarn-berry is wrong in the upstream views. https://aur.archlinux.org/packages/yarn-berry

I will update the yarn 1.22.x to close this issue.
