### ISSUE TITLE
[Package]: Dillo

### ISSUE THREAD

**Issue by Usinganame** [termux/termux-packages#19406]
### Why is it worth to add this package?

Dillo is a lightweight web browser, useful for low end systems or low storage systems where every megabyte counts

### Home page URL

https://dillo-browser.github.io/

### Source code URL

https://github.com/dillo-browser/dillo/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

It does compile, but onky with a few patches

* Clone the Github Repo
* Run `./autogen.sh`
* Run `./configure`
* Go to the `dpid/` directory
* Open `dpidc.c` in your favorite text editor
* Change line 82 from
   `bzero((char *) &serv_addr, sizeof(serv_addr));`
to
`memset(&serv_addr, 0, sizeof(serv_addr));`
* Change line 101 from
  `bzero(buffer,256);`
to
`memset(buffer, 0, 256);`
* Back to the top level directory
* Run `make`

**Comment by Biswa96** [comment]
This package has been added in TUR https://github.com/termux-user-repository/tur/commit/c9d85459f4dfd648b47c87626957106b0a3ec249
