### ISSUE TITLE
Ruby Libxml Upgrade Doesn't Work

### ISSUE THREAD

**Issue by nuhadev** [termux/termux-packages#1940]
Hi,
i want to upgrade my libxml-ruby but not work

Notice :
invalid option: --with-xml2-config
$ gem install libxml-ruby
Building native extensions.  This could take a while...
ERROR:  Error installing libxml-ruby:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/libxml-ruby-3.0.0/ext/libxml
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20171217-17173-qy3cyc.rb extconf.rb
/data/data/com.termux/files/usr/bin/ruby: warning: shebang line ends with \r may cause a problem
checking for libxml/xmlversion.h in /opt/include/libxml2,/opt/local/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --with-xml2-config
        --without-xml2-config
        --with-xml2-dir
        --without-xml2-dir
        --with-xml2-include
        --without-xml2-include=${xml2-dir}/include
        --with-xml2-lib
        --without-xml2-lib=${xml2-dir}/lib
 extconf failure: need libxml2.

    Install the library or try one of the following options to extconf.rb

--with-xml2-config=/path/to/xml2-config
      --with-xml2-dir=/path/to/libxml2
      --with-xml2-lib=/path/to/libxml2/lib
      --with-xml2-include=/path/to/libxml2/include

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/libxml-ruby-3.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/libxml-ruby-3.0.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/libxml-ruby-3.0.0/gem_make.out

**Comment by fornwall** [comment]
Could you attach (or link to) the content of /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/libxml-ruby-3.0.0/mkmf.log ?

**Comment by xeffyr** [comment]
>checking for libxml/xmlversion.h in /opt/include/libxml2,/opt/local/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... no

It just tries to look for libxml2 headers at standard paths which are not available in Termux. Use `termux-chroot` from proot package to install this gem.

```ShellSession
[~]:$ termux-chroot
[/home]:$ gem install libxml-ruby
Building native extensions. This could take a while...
Successfully installed libxml-ruby-3.1.0
```
