### ISSUE TITLE
[Bug]: every 5 seconds mobox freezes. 

### ISSUE THREAD

**Issue by Rynchguy64** [termux/termux-packages#19423]
### Problem description

Every 5 second mobox freezes and when i jump off and jump back in it unfreezes but freezes again!! 

### What steps will reproduce the bug?

5 seconds later. 

### What is the expected behavior?

It shouldn't freeze so it's useable. 

### System information

termux-info:

```

```

**Comment by twaik** [comment]
Mobox is a 3rd party product we offer zero support for.

**Comment by licy183** [comment]
Please report your bug to mobox. https://github.com/olegos2/mobox
