### ISSUE TITLE
Taskwarrior segfaults

### ISSUE THREAD

**Issue by matthiasbeyer** [termux/termux-packages#1942]
Taskwarrior segfaults in `task sync` (Ehen syncing with a taskserver).

**Comment by Grimler91** [comment]
Which arch are you on? (What's the output of `uname -a`?)

**Comment by Grimler91** [comment]
I am able to reproduce on arm. And it seems that simply rebuilding the package gets rid of the error, `task sync` then gives "Taskserver is not configured." instead of "Segmentation fault".

**Comment by matthiasbeyer** [comment]
I'm on armv7l Android running kernel 3.4.

How to force rebuild? I tried `apt remove taskwarrior && apt install taskwarrior` but that doesn't solve the problem.

**Comment by Grimler91** [comment]
@matthiasbeyer The version of the package needs to be increased and the package rebuilt using the build-package.sh script (see https://github.com/Grimler91/termux-packages/commit/25886b844af35250a2e152adc4026b2ad7e3e850).
Could you try this deb where I have done exactly that and see if it works as it should? 
https://github.com/Grimler91/Grimler91.github.io/blob/master/files/dists/testing/misc/binary-arm/taskwarrior_2.5.1-4_arm.deb
I'll open a pull request to the main repo if it seems to work.
