### ISSUE TITLE
tsu - error opening terminal: unknown

### ISSUE THREAD

**Issue by jdgregson** [termux/termux-packages#1946]
I recently acquired root by flashing Magisk (phh's SuperUser). I then installed termux, htop, tsu, and htop as root (via tsu). But I am unable to actually start htop as root. Here is what I am seeing on the console:

$ htop
[htop starts] (^c to exit)
$ tsu
bash-4.4#
bash-4.4# whoami
root
bash-4.4# which htop
/data/data/com.termux/files/usr/bin/htop
bash-4.4# htop
Error opening terminal: unknown.

Is there something I am missing? I would like to be able to run any termux executable as root but it doesn't seem possible. Please advise if there is a workaround.

**Comment by xeffyr** [comment]
try as root:
```
export TERM=xterm-256color
```

**Comment by jdgregson** [comment]
Ah, that does get it to work. Thanks! I'll have to try to get a bashrc setup somewhere for root.

Interesting thing, when I export TERM and then start htop or vim as root, they both only take up about half of the available terminal window (vertically). When I run the commands as my normal user they are full screen.

**Comment by sdrausty** [comment]
@jdgregson how did you root your device?  What app did you use to crack it?

**Comment by jdgregson** [comment]
I unlocked the bootloader and then flashed Magisk v7 via TWRP as described in the Edit section of this post: https://forum.xda-developers.com/yoga-book/how-to/root-yb1-x90l-how-to-t3534268. The device was a Yoga Book on Android 7.1.1.

It seems like Magisk is responsible for a few recent su-related issues, as I have this exact issue as well: https://github.com/termux/termux-app/issues/398.

**Comment by xeffyr** [comment]
> It seems like Magisk is responsible for a few recent su-related issues,

I guess that this is not a Magisk issue.
1. The `su` binaries may have a different command line interface.
2. The `su` binary can force set it's own environment.
