### ISSUE TITLE
[Package]: texlive-bin now 2024

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#19489]
### Why is it worth to add this package?

I regularly use TeXlive. The 2024 edition was released earlier this week.

### Source code URL

https://github.com/TeX-Live/texlive-source

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

As usual, the binaries need to be built, with the non-binaries separately installable.

**Comment by twaik** [comment]
No need to ask about package updates. We see all of them but have no resourses to write patches. It will be available as soon as it it possible.
