### ISSUE TITLE
[Bug]: installing or running gh fails with dbus error

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#19497]
### Problem description

`pkg install gh` fails during auto-completion generation in postinst script with the following:

```
Setting up gh (2.45.0) ...
failed to migrate config: cowardly refusing to continue with multi account migration: couldn't find oauth token for "users": The name org.freedesktop.secrets was not provided by any .service files
failed to migrate config: cowardly refusing to continue with multi account migration: couldn't find oauth token for "users": The name org.freedesktop.secrets was not provided by any .service files
failed to migrate config: cowardly refusing to continue with multi account migration: couldn't find oauth token for "users": The name org.freedesktop.secrets was not provided by any .service files
dpkg: error processing package gh (--configure):
 installed gh package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 gh
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

### What steps will reproduce the bug?

`pkg install gh` or `gh completion -s bash` or just `gh` in the half-installed state.

### What is the expected behavior?

gh installs without errors.

### System information

Reproduced on an arm tablet, but works fine on my aarch64 phone. 

I don't think this is an issue with gh, I guess something else is broken in my environment. Opening this bug report until I can figure out the real issue (and post solution here to help others).

termux-info:

```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~jEmUSByi-Byt7HMYxM_cKw==/com.termux-BuuSpk9yfzSB9DBd0Oj6jw==/base.apk
TERMUX_APP__APK_RELEASE=UNKNOWN
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=false
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=5093
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c146,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c146,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10146
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/termux/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.41.1
Android version:
11
Kernel build information:
Linux localhost 3.4.113-g2691a7a12f79 #3 SMP PREEMPT Sat Nov 18 20:03:48 CET 2023 armv7l Android
Device manufacturer:
samsung
Device model:
SM-T800
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.window versionCode:15

```

**Comment by Grimler91** [comment]
If I uninstall dbus on the arm device I instead get:

```
failed to migrate config: cowardly refusing to continue with multi account migration: couldn't find oauth token for "users": exec: "dbus-launch": executable file not found in $PATH
```

On my aarch64 gh works with or without dbus.

gh pulls in github.com/godbus/dbus, so I guess issue comes from there in some way, but don't know why this happens on arm but not aarch64.

**Comment by Biswa96** [comment]
Does this issue happen with gh only? I have added the same logic in a pull request to generate shell completions with git-delta. I am wondering if that would cause any issue in arm devices. aarch64 is working fine though.

**Comment by Grimler91** [comment]
@Biswa96 not really sure what real issue is, but I am guessing it is not really a gh issue (and definetly not a completion generation issue). I can trigger issue by just running `gh` also. 

What is the command for generating git-delta completion? I can try it out

**Comment by Biswa96** [comment]
> What is the command for generating git-delta completion?

For example, `delta --generate-completion bash` is for bash completion. The full change can be found in the recent pull request.

**Comment by Grimler91** [comment]
@Biswa96 tried it, and it works fine on arm as well!

**Comment by Grimler91** [comment]
Adding `version: "1"` to `~/.config/gh/config.yml` or removing `~/.config/gh/hosts.yml` fixes issue. Seems my config file was not compatible with this gh version. 
(We might want to add dbus to gh's dependencies since gh apparently tries to start dbus-launch under some conditions)

**Comment by Grimler91** [comment]
> Seems my config file was not compatible with this gh version.

Should probably have realised this sooner considering the message `failed to migrate config` :shrug:
