### ISSUE TITLE
[QUESTION]: extra-cmake-modules 6.0.0

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#19504]
extra-cmake-modules 6.0.0 is available, but should we update package to 6.0.0 or we should provide additional package for version 6 and keep older version for compatibility with KDE Frameworks 5.* based packages?

**Comment by Grimler91** [comment]
Which packages do we have that do not work with 6.0.0?

Generally we try to just have one version (latest), so unless the (hopefully few) packages that need 5.* are very popular or something I would say we should update to 6.0.0

**Comment by twaik** [comment]
Closed by 079f573676a92e3f656d0ef086f511a5f30b9045
