### ISSUE TITLE
Kali Linux install packages

### ISSUE THREAD

**Issue by abhusal** [termux/termux-packages#1954]
I tried to install a package and I get this errorapt-get install metagoofil --fix-missing
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  metagoofil
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 451 kB of archives.
After this operation, 2,448 kB of additional disk space will be used.
Get:1 http://http.kali.org/kali kali-rolling/main amd64 metagoofil all 2.2-1kali2 [451 kB]
Err:1 http://http.kali.org/kali kali-rolling/main amd64 metagoofil all 2.2-1kali2
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:a24ca216c74b33100236fc3be7a669898550eb72753ef5910439d5144f5316e1
   - SHA1:5da5cd88b9bf4fca76b44234ddd2a887fa3d4b49 [weak]
   - MD5Sum:69a5126ecb419d07e7a14ced9cc148fd [weak]
   - Filesize:450942 [weak]
  Hashes of received file:
   - SHA256:26713aac0e0e9cd7ed030d6e3de9f3450014509e9d5501f8a281435dbacc9ff2
   - SHA1:6fbddcc2f623fc76755ad56dc7ee8b949d2ea1fd [weak]
   - MD5Sum:41286c191f66469f4107ebf2af2a2f0d [weak]
   - Filesize:8894 [weak]
  Last modification reported: Wed, 20 Dec 2017 17:19:37 +0000
Fetched 8,894 B in 0s (56.6 kB/s)
E: Failed to fetch https://auth.impulse.com:8443/clientStatus.!^  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:a24ca216c74b33100236fc3be7a669898550eb72753ef5910439d5144f5316e1
    - SHA1:5da5cd88b9bf4fca76b44234ddd2a887fa3d4b49 [weak]
    - MD5Sum:69a5126ecb419d07e7a14ced9cc148fd [weak]
    - Filesize:450942 [weak]
   Hashes of received file:
    - SHA256:26713aac0e0e9cd7ed030d6e3de9f3450014509e9d5501f8a281435dbacc9ff2
    - SHA1:6fbddcc2f623fc76755ad56dc7ee8b949d2ea1fd [weak]
    - MD5Sum:41286c191f66469f4107ebf2af2a2f0d [weak]
    - Filesize:8894 [weak]
   Last modification reported: Wed, 20 Dec 2017 17:19:37 +0000
E: Internal Error, ordering was unable to handle the media swap

Any Help?

**Comment by abhusal** [comment]
I tried removing some applications and installing them again. It didn't work. None of the application from the repository are working

My source file is 
deb http://http.kali.org/kali kali-rolling main contrib non-free
# For source package access
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free
#deb-src http://http.kali.org/kali kali-rolling main contrib non-free

deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free

**Comment by abhusal** [comment]
I am trying to install metagoofil. I have kali linux GNU rolling

**Comment by Grimler91** [comment]
Doesnt look like the error has anything to do with termux. Have you `apt update`?

**Comment by abhusal** [comment]
I tried apt-update apt-upgrade and dist upgrade too but it says it couldn’t fetch dome packages.
