### ISSUE TITLE
Rails generate controller command giving error ...

### ISSUE THREAD

**Issue by staymetal** [termux/termux-packages#1956]
$ ls
Gemfile       config        public
Gemfile.lock  config.ru     test
README.md     db            tmp
Rakefile      lib           vendor
app           log
bin           package.json
$ rails g controller hello
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/run.rb:76:in `spawn': No such file or directory - /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/bin/spring (Errno::ENOENT)
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/run.rb:76:in `boot_server'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/run.rb:56:in `cold_run'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/run.rb:33:in `rescue in call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/run.rb:30:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:24:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /data/data/com.termux/files/home/myblog/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
$

**Comment by xtkoba** [comment]
This issue is marked as obsolete. Please open a new issue if you encounter a similar problem. Thanks.
