### ISSUE TITLE
Would a combination of Termux, termux-api, termux-usb, and the SPICE usbredir protocol allow QEMU read and write access to a USB device without root?

### ISSUE THREAD

**Issue by NoteAfterNote** [termux/termux-packages#19570]
* https://www.spice-space.org/usbredir.html

* https://gitlab.freedesktop.org/spice/usbredir/-/blob/main/docs/usb-redirection-protocol.md

* https://people.freedesktop.org/~teuf/spice-doc/html/ch02s06.html

* https://github.com/termux/termux-packages/issues/5249

**Comment by twaik** [comment]
1. Qemu does not have code needed to handle `termux-usb.
2. Even in the case someone writes it you will have no access to usb hubs, keyboards or mice, or any device with BOOT subclass. https://cs.android.com/android/platform/superproject/+/android-8.0.0_r1:frameworks/base/services/usb/java/com/android/server/usb/UsbHostManager.java;l=121-133 . It does not matter what software you use. We can not override Android security policies.

**Comment by mjuned47** [comment]
https://youtu.be/LayYgwC-55c?si=5zJoQSz-T_URFvbT

I think this will be helpful

**Comment by twaik** [comment]
No, it is not.

**Comment by twaik** [comment]
Closing this due to Android security restrictions.
