### ISSUE TITLE
Kali Linux Install Package Problem

### ISSUE THREAD

**Issue by abhusal** [termux/termux-packages#1957]
This issue was closed without getting solved. Please help. 

I tried to install a package and I get this errorapt-get install metagoofil --fix-missing
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
metagoofil
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 451 kB of archives.
After this operation, 2,448 kB of additional disk space will be used.
Get:1 http://http.kali.org/kali kali-rolling/main amd64 metagoofil all 2.2-1kali2 [451 kB]
Err:1 http://http.kali.org/kali kali-rolling/main amd64 metagoofil all 2.2-1kali2
Hash Sum mismatch
Hashes of expected file:

SHA256:a24ca216c74b33100236fc3be7a669898550eb72753ef5910439d5144f5316e1
SHA1:5da5cd88b9bf4fca76b44234ddd2a887fa3d4b49 [weak]
MD5Sum:69a5126ecb419d07e7a14ced9cc148fd [weak]
Filesize:450942 [weak]
Hashes of received file:
SHA256:26713aac0e0e9cd7ed030d6e3de9f3450014509e9d5501f8a281435dbacc9ff2
SHA1:6fbddcc2f623fc76755ad56dc7ee8b949d2ea1fd [weak]
MD5Sum:41286c191f66469f4107ebf2af2a2f0d [weak]
Filesize:8894 [weak]
Last modification reported: Wed, 20 Dec 2017 17:19:37 +0000
Fetched 8,894 B in 0s (56.6 kB/s)
E: Failed to fetch https://auth.impulse.com:8443/clientStatus.!^ Hash Sum mismatch
Hashes of expected file:
SHA256:a24ca216c74b33100236fc3be7a669898550eb72753ef5910439d5144f5316e1
SHA1:5da5cd88b9bf4fca76b44234ddd2a887fa3d4b49 [weak]
MD5Sum:69a5126ecb419d07e7a14ced9cc148fd [weak]
Filesize:450942 [weak]
Hashes of received file:
SHA256:26713aac0e0e9cd7ed030d6e3de9f3450014509e9d5501f8a281435dbacc9ff2
SHA1:6fbddcc2f623fc76755ad56dc7ee8b949d2ea1fd [weak]
MD5Sum:41286c191f66469f4107ebf2af2a2f0d [weak]
Filesize:8894 [weak]
Last modification reported: Wed, 20 Dec 2017 17:19:37 +0000
E: Internal Error, ordering was unable to handle the media swap
Any Help?
 @abhusal
     
abhusal commented 20 hours ago
I tried removing some applications and installing them again. It didn't work. None of the application from the repository are working

My source file is
deb http://http.kali.org/kali kali-rolling main contrib non-free

For source package access

deb-src http://http.kali.org/kali kali-rolling main contrib non-free

#deb-src http://http.kali.org/kali kali-rolling main contrib non-free

deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free
 @xeffyr
 Contributor
xeffyr commented 20 hours ago
What are you trying to do ? Kali linux possible only in chroot/proot or emulator. It won't work in Termux if you add deb http://http.kali.org/kali kali-rolling main contrib non-free to /data/data/com.termux/files/usr/etc/sources.list because of some reasons:

Kali linux (and other Linux distros) use gnu libc. Termux uses bionic from Android.
Termux uses prefixed environment. There no /bin, /usr/bin but $PREFIX/bin, etc... so package won't be installed correctly.
 @abhusal
     
abhusal commented 17 hours ago
I am trying to install metagoofil. I have kali linux GNU rolling
 @Grimler91
 Collaborator
Grimler91 commented 17 hours ago
Doesnt look like the error has anything to do with termux. Have you apt update?
 @fornwall fornwall closed this 11 hours ago
 @abhusal
     
abhusal commented 11 hours ago
I tried apt-update apt-upgrade and dist upgrade too but it says it couldn’t fetch dome packages.

**Comment by sdrausty** [comment]
@abhusal Are you using `debootstrap`?  What Termux commands are you using?  Where do you get
> Reading package lists... Done
and what follows from?  Telling us what Termux commands you used to get this output would be helpful; Wouldn't it?

**Comment by xeffyr** [comment]
@abhusal what path to your sources.list file ? And what your architecture ?

**Comment by abhusal** [comment]
@xeffyr That's my source file

deb http://http.kali.org/kali kali-rolling main contrib non-free

For source package access

deb-src http://http.kali.org/kali kali-rolling main contrib non-free

#deb-src http://http.kali.org/kali kali-rolling main contrib non-free

deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free

**Comment by abhusal** [comment]
@sdrausty I don't think I am using debootstrap.

**Comment by abhusal** [comment]
@sdrausty 
I was using apt-get install metagoofil to install a package.

**Comment by sdrausty** [comment]
@abhusal the packages apt uses must be compiled for Termux.  You cannot use other Linux distribution packages directly in Termux.  To use other Linux distributions in Termux, we have PRoot.  Is this https://github.com/Hax4us/Nethunter-In-Termux "This is a script by which you can install Kali nethunter (Kali Linux) in your termux application without rooted phone" what you are trying to do in Termux?

**Comment by xeffyr** [comment]
@abhusal if your sources list is located at /data/data/com.termux/files/usr/etc/apt/sources.list ($PREFIX/etc/apt/sources.list), then refer to comment from @sdrausty.

**Comment by abhusal** [comment]
I dont think it has anything to do with termux. I am using Kali linux GNU rolling in Virtualbox

**Comment by Neo-Oli** [comment]
@abhusal Then why are you asking it in the Termux repository?

**Comment by abhusal** [comment]
I didn't notice I was in termux repository. I am sorry about that.
