### ISSUE TITLE
Multiple Attempts to run mobox [Bug]: 

### ISSUE THREAD

**Issue by Rekkusu09** [termux/termux-packages#19599]
### Problem description

Often times, after pressing mobox. It does not respond. Still had To do multiple Attempts before it redirect. And i mean exiting the termux

### What steps will reproduce the bug?

Dont know im not a dev. 

### What is the expected behavior?

After entering an entry , it should respond on time . If not respond , should only be once . 

### System information

termux-info
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=10677
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://ro.mirror.flokinet.net/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://ro.mirror.flokinet.net/termux/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://ro.mirror.flokinet.net/termux/termux-root root stable
Updatable packages:
curl/stable 8.7.1 aarch64 [upgradable from: 8.6.0-1]
libcurl/stable 8.7.1 aarch64 [upgradable from: 8.6.0-1]
libffi/stable 3.4.6-1 aarch64 [upgradable from: 3.4.6]
zstd/stable 1.5.6 aarch64 [upgradable from: 1.5.5-1]
termux-tools version:
1.41.2
Android version:
12
Kernel build information:
Linux localhost 4.19.191-g97751e3c4ba3-dirty #1 SMP PREEMPT Fri Jan 26 21:13:00 CST 2024 aarch64 Android
Device manufacturer:
TECNO
Device model:
TECNO LG6n
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
~ $

**Comment by TomJo2000** [comment]
Mobox is a 3rd party application using Termux as a base.
We do not offer support or compatibility guarantees for it.
Please open an issue at: https://github.com/olegos2/mobox/issues/new
