### ISSUE TITLE
Upgrade `mogan` to v1.2.5.1 (and following LTS)

### ISSUE THREAD

**Issue by Iey4iej3** [termux/termux-packages#19608]
Now `mogan` has LTS releases https://github.com/XmacsLabs/mogan/issues/1622

I propose to only follow LTS releases (to reduce the effort of maintenance).

The latest LTS is v1.2.5.1, and I propose to upgrade to this version. Moreover, when another point update (e.g. v1.2.5.2) of v1.2.5 is released, I hope that point releases could be followed automatically (e.g. done by a bot), and human intervention is only necessary for major upgrades between different versions of LTS releases.

**Comment by Biswa96** [comment]
I have tired to compile that version but failed after some patching. I do not how to fix the following error.

```
error: "s7": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
libc: error: "s7": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
```

The new patches are attached here.

[xmake-packages-s7-port-xmake.lua.patch.txt](https://github.com/termux/termux-packages/files/14812625/xmake-packages-s7-port-xmake.lua.patch.txt)
[xmake-packages.lua.patch.txt](https://github.com/termux/termux-packages/files/14812626/xmake-packages.lua.patch.txt)

Remove src-Scheme-S7-s7.c.patch and xmake.lua.patch files and add libgit2 dependency in build.sh.

**Comment by TomJo2000** [comment]
Provided we get the new version to build properly we should also be able to enable auto updates for it.

Thus tracking the mainline releases would be no more work than tracking LTS.

**Comment by Iey4iej3** [comment]
LTS versions are supposed to be stable, and general users are recommended to use LTS versions for the time being, cf. https://github.com/XmacsLabs/mogan/issues/1622#issuecomment-1914626853 and https://github.com/XmacsLabs/mogan/issues/1622#issuecomment-1916262501

If you have suggestions which facilitate your maintenance, you could also leave messages there.

**Comment by Grimler91** [comment]
> I have tired to compile that version but failed after some patching. I do not how to fix the following error.
> 
> ```
> error: "s7": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
> libc: error: "s7": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
> ```

termux-elf-cleaner should fix such underalignment: https://github.com/termux/termux-elf-cleaner/blob/5af92859785f773f3d5f30c6d5a1a042844412ab/elf-cleaner.cpp#L108-L122
