### ISSUE TITLE
[Bug]: vlc defaults to opengl

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#19613]
### Problem description

Hello. It seems like vlc-qt (and possibly vlc too) defaults to use OpenGL video output, but its performance is very low in the case if only swrast/llvmpipe is installed. Can we make it fallback to X11 video output (XCB) in the case if llvmpipe is the only available driver? Vlc's performance will be much higher in that case.

### What steps will reproduce the bug?

Just install vlc-qt and open 1080p video.

### What is the expected behavior?

It should run faster like in the case of X11 video output.

### System information

termux-info:

```
Irrelevant
```

**Comment by twaik** [comment]
@Biswa96 I've seen the link to your videolan profile, so you should be familiar with VLC code. Can you please take a look at this?

**Comment by Biswa96** [comment]
Unfortunately, I have no idea about VLC internals. Although, I would be interested to know about this issue just from a tinkering POV.

**Comment by Biswa96** [comment]
Are you looking for something like this? VLC > Tools > Preferences > Video > Output > X11 video output (XCB)

I can not comprehend any visual performance change because opengl and x11 both looks same in termux-x11. Please let me know if there is any way to see the performance.

**Comment by twaik** [comment]
> Are you looking for something like this? VLC > Tools > Preferences > Video > Output > X11 video output (XCB)

Yes.

> I can not comprehend any visual performance change because opengl and x11 both looks same in termux-x11. Please let me know if there is any way to see the performance.

Probably your device is powerful enough to render it fast using llvmpipe, but there are lots of devices which can not.

**Comment by truboxl** [comment]
Somebody can tweak `set_capability()` values based on https://github.com/videolan/vlc/commit/077be967c1739bc2e52239697061c3173183a0df
