### ISSUE TITLE
Package Request: clang-format

### ISSUE THREAD

**Issue by DoktorStein** [termux/termux-packages#1961]
**clang-format** [https://clang.llvm.org/docs/ClangFormat.html] understand language constructs and is very customizable. Also it can be integrated with _vim_ and _emacs_, aside being production-ready.
Any chance of getting it for Termux?

**Comment by stephengroat** [comment]
@DoktorStein i'm seeing `clang-format`, along with the associated scripts, available in the `clang` package.

have you tried `pkg install clang`?

**Comment by joakim-noah** [comment]
Yep, it's in the clang package, install it and run `dpkg -L clang` to confirm.

**Comment by Grimler91** [comment]
I guess we can close this then.

**Comment by DoktorStein** [comment]
Yep, after running `clang-format` I noticed batteries included :)
Thanks.
