### ISSUE TITLE
[Bug]: minio auto update failed for arm, i686, x86_64

### ISSUE THREAD

**Issue by truboxl** [termux/termux-packages#19624]
### Problem description

https://github.com/termux/termux-packages/commits/master/packages/minio/build.sh

Its been a while but somebody need to take a look and fix the auto update. PRs are welcomed.

### What steps will reproduce the bug?

n/a

### What is the expected behavior?

n/a

### System information

n/a

**Comment by twaik** [comment]
I think I know what causes the problems.
The package has CGO disabled for build.
Probably we should enable it.
https://github.com/termux/termux-packages/commit/d98b83e04bc2adfb42d8d40fca8fc7ba78330376
https://github.com/termux/termux-packages/commit/04809d6cb0b0af7dc6b5fe7c387512639b5a6e92
https://github.com/termux/termux-packages/commit/44b9931f86c28c3db373063a274bd320850af6e1

**Comment by Grimler91** [comment]
Maybe we should test build for all arches before pushing auto-updates.. :/

**Comment by Biswa96** [comment]
> test build for all arches before pushing auto-updates..

And the logic should handle TERMUX_PKG_BLACKLISTED_ARCHES cases also.
