### ISSUE TITLE
librsync 2.0.0 fails with segmentation fault [-> 2.0.1?]

### ISSUE THREAD

**Issue by YtvwlD** [termux/termux-packages#1963]
The currently shipped version 2.0.0 of librsync has a bug which causes it to crash in some circumstances. (see https://github.com/librsync/librsync/issues/50)

v2.0.1 seems to have solved this problem, but I can't get it to build - it fails with

```
/home/builder/.termux-build/librsync/build/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:10: fatal error: 'mcheck.h' file not found
#include <mcheck.h>
         ^~~~~~~~~~
```

**Comment by xeffyr** [comment]
This should be fixed in https://github.com/librsync/librsync/commit/c2daedb5835f5301de50b44add166344e1ef6b02

Patch:
```
diff -uNr librsync-2.0.0/src/search.c librsync-2.0.0.mod/src/search.c
--- librsync-2.0.0/src/search.c	2015-11-29 22:43:12.000000000 +0200
+++ librsync-2.0.0.mod/src/search.c	2017-12-23 15:06:05.684445933 +0200
@@ -218,7 +218,7 @@
 	    r = m;
     }
 
-    if (l == r) {
+    if ((l == r) && (l <= bucket->r)) {
 	int i = sig->targets[l].i;
 	rs_block_sig_t *b = &(sig->block_sigs[i]);
 	if (weak_sum != b->weak_sum)
```

**Comment by YtvwlD** [comment]
Yeah, that should be fixed. But v2.0.1 has not yet landed in Termux, right?

**Comment by fornwall** [comment]
Thanks a lot! The package has been updated to v2.0.1 which should fix this (update with `pkg up`), let us know how it works!

**Comment by YtvwlD** [comment]
Thank you! It worked. :)
