### ISSUE TITLE
[Bug]: openjdk-17 can not run normally in Termux

### ISSUE THREAD

**Issue by Sandendaty** [termux/termux-packages#19645]
### Problem description

Just now I updated the packages using "pkg update" and "pkg upgrade". Then I happended to find that java (openjdk-17) can no longer run. After that, I reinstalled openjdk-17, but the problem still existed. Here is the error information:
![Screenshot_2024-04-02-20-36-20-55_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-packages/assets/39406572/da54fb6a-b40a-4c12-86f9-ccde399e7d40)

### What steps will reproduce the bug?

Install or reinstall openjdk-17. Then execute some commands related to java, such as "java", "javac", "java -version".

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21487
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.quantum5.ca/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.quantum5.ca/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.41.2
Android version:
14
Kernel build information:
Linux localhost 5.15.94-android13-8-o-00722-ge568e3a79803 #1 SMP PREEMPT Thu Jan 18 08:24:02 UTC 2024 aarch64 Android
Device manufacturer:
OnePlus
Device model:
PJE110
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
com.termux.api versionCode:51
```

**Comment by twaik** [comment]
First of all: try `pkg i libandroid-spawn` and please report if that is reproducible.

**Comment by Sandendaty** [comment]
> First of all: try `pkg i libandroid-spawn` and please report if that is reproducible.

OK, I have already tried the command you provided and find that java can now run properly. Thank you!

**Comment by twaik** [comment]
@Grimler91 can you please add libandroid-spawn to openjdk-17 dependencies?
