### ISSUE TITLE
Issue with language change not being applied in Termux XFCE desktop

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#19646]
### Problem description

I would like to inquire about changing the language to a Termux native XFCE session rather than a PRoot environment.

Changing the language (changing locale) in general Linux is easy because there are so many manuals, but it seems not to be easy in Termux.

```
pkg install locales
``` 
Through the above command, it appears that the locales package is not provided separately...

I tried a little trick.
```
nano ~/.profile
``` 
After entering the command
``` 
LD_PRELOAD=/system/lib64/libskcodec.so
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
export LANG=ko_KR.UTF-8
``` 

After adding `export LANG=ko_KR.UTF-8`, I ran XFCE.

But ko_KR.UTF-8 is not applied to XFCE...

I was disappointed, but! It wasn't completely unapplied!

The program list in `Properties -> Open With` is
`ko_KR.UTF-8` is applied and displayed in `Korean` language.

![KO_1](https://github.com/termux/termux-packages/assets/101167173/c501572c-c7fc-449c-b7bf-efee069c6ee3)

Chromium browser installed
`ko_KR.UTF-8` was applied and displayed in `Korean` language.
![KO_2](https://github.com/termux/termux-packages/assets/101167173/df8e73df-1f4f-4e6e-af5a-9ad1bf0cec61)

However, it still does not apply to many programs and the XFCE desktop.

``` 
nano ~/.profile
``` 
at
``` 
LC_CTYPE=ko_KR.UTF-8
LC_NUMERIC=ko_KR.UTF-8
LC_TIME=ko_KR.UTF-8
LC_COLLATE=ko_KR.UTF-8
LC_MONETARY=ko_KR.UTF-8
LC_MESSAGES=ko_KR.UTF-8
LC_PAPER=ko_KR.UTF-8
LC_NAME=ko_KR.UTF-8
LC_ADDRESS=ko_KR.UTF-8
LC_TELEPHONE=ko_KR.UTF-8
LC_MEASUREMENT=ko_KR.UTF-8
LC_IDENTIFICATION=ko_KR.UTF-8
LC_ALL=
``` 

I filled it out, but there was no significant income.

Ah...if I remove `export LANG=ko_KR.UTF-8`, it returns to `English` again.
![KO_3](https://github.com/termux/termux-packages/assets/101167173/d2fbe8aa-e25f-452f-80cc-00f05d8c3231)
![KO_4](https://github.com/termux/termux-packages/assets/101167173/8a4309f6-72fa-4ff5-8f00-0f0ac609fc0a)

XFCE sessions clearly support multiple languages.
Seeing that I saw some effect just by adding `export LANG=ko_KR.UTF-8` to `.profile`, I think there must be a way to change the language.

I wonder if there is a sure way.

### What steps will reproduce the bug?

When adding `export LANG=ko_KR.UTF-8` to `.profile,` the language is applied to only a small portion of `XFCE`.

### System information

termux-info:

![KO_5](https://github.com/termux/termux-packages/assets/101167173/5a2dcd84-23dd-42e3-904b-0b446815f160)

**Comment by TomJo2000** [comment]
Libbionic does not support the locales mechanism.
This is known and expected behavior.

**Comment by twaik** [comment]
Probably because it uses mechanism other than gnu locales.

**Comment by hansm629** [comment]
@twaik 
Ah...I just understood what you mean.

**Comment by hansm629** [comment]
@TomJo2000 
That's sad...
XFCE4 clearly supports multi-language, but I can't use it...

**Comment by twaik** [comment]
Closing this because bionic does not have locales mechanisms and they are not planned to be ported.
