### ISSUE TITLE
[Package]: slrn snapshot

### ISSUE THREAD

**Issue by r3k2** [termux/termux-packages#19647]
### Why is it worth to add this package?

a lot of people in our linux and security community is flocking back to the new usenet, with out google, binaries and only plain text, so we been using slrn snapshot under arch linux, will be amazing if someone could port slrn snapshot to termux so we can use it on our tablets etc. BTW Thanks for porting aerc.!!!!

### Home page URL

https://aur.archlinux.org/packages/slrn-snapshot

### Source code URL

https://aur.archlinux.org/packages/slrn-snapshot
https://jedsoft.org/snapshots/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

I have 0 knowladge of android/roms/arm

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last release was 9 years ago and upstream repos are unavailable so I consider the project is dead.
