### ISSUE TITLE
[Bug]: luarocks cannot install rocks modules

### ISSUE THREAD

**Issue by haidaroh9** [termux/termux-packages#19668]
### Problem description

luarocks install --global --verbose --force-lock nlua
-------------------------------------------------------------------------------
Current configuration:
-------------------------------------------------------------------------------
accept_unknown_fields = false
arch = "linux-aarch64"
cache = {}
cache_fail_timeout = 86400
cache_timeout = 60
check_certificates = false
cmake_generator = "Unix Makefiles"
config_files = {
   nearest = "/data/data/com.termux/files/usr/etc/luarocks/config-5.1.lua",
   system = {
      file = "/data/data/com.termux/files/usr/etc/luarocks/config-5.1.lua",
      found = true
   },
   user = {
      file = "/data/data/com.termux/files/usr/etc/luarocks/config-5.1.lua",
      found = true
   }
}
connection_timeout = 30
deps_mode = "one"
disabled_servers = {}
export_path_separator = ":"
external_deps_dirs = {
   "/data/data/com.termux/files/usr/local",
   "/data/data/com.termux/files/usr"
}
external_deps_patterns = {
   bin = {
      "?"
   },
   include = {
      "?.h"
   },
   lib = {
      "lib?.a",
      "lib?.so",
      "lib?.so.*"
   }
}
external_deps_subdirs = {
   bin = "bin",
   include = "include",
   lib = {
      "lib64",
      "lib"
   }
}
external_lib_extension = "so"
fs_use_modules = true
gcc_rpath = true
home = "/data/data/com.termux/files/home"
home_tree = "/data/data/com.termux/files/home/.luarocks"
hooks_enabled = true
lib_extension = "so"
lib_modules_path = "lib/lua/5.1"
link_lua_explicitly = false
local_by_default = false
local_cache = "/data/data/com.termux/files/home/.local/cache/luarocks"
lua_extension = "lua"
lua_found = true
lua_modules_path = "share/lua/5.1"
lua_version = "5.1"
no_manifest = false
obj_extension = "o"
processor = "aarch64"
program_version = "3.11.0"
rocks_servers = {
   {
      "https://luarocks.org",
      "https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/",
      "https://loadk.com/luarocks/"
   }
}
rocks_subdir = "lib/luarocks/rocks-5.1"
rocks_trees = {
   {
      name = "user",
      root = "$HOME/.local/luarocks"
   },
   {
      name = "system",
      root = "/data/data/com.termux/files/usr"
   }
}
runtime_external_deps_patterns = {
   bin = {
      "?"
   },
   include = {
      "?.h"
   },
   lib = {
      "lib?.so",
      "lib?.so.*"
   }
}
runtime_external_deps_subdirs = {
   bin = "bin",
   include = "include",
   lib = {
      "lib64",
      "lib"
   }
}
static_lib_extension = "a"
sysconfdir = "/data/data/com.termux/files/usr/etc/luarocks"
target_cpu = "aarch64"
upload = {
   api_version = "1",
   server = "https://luarocks.org",
   tool_version = "1.0.0"
}
user_agent = "LuaRocks/3.11.0 linux-aarch64"
variables = {
   AR = "ar",
   BUNZIP2 = "bunzip2",
   CC = "gcc",
   CFLAGS = "-O2 -fPIC",
   CHMOD = "chmod",
   CMAKE = "cmake",
   CP = "cp",
   CURL = "curl",
   CURLNOCERTFLAG = "-k",
   CVS = "cvs",
   FIND = "find",
   GIT = "git",
   GPG = "gpg",
   GUNZIP = "gunzip",
   HG = "hg",
   ICACLS = "icacls",
   LD = "gcc",
   LIBFLAG = "-shared",
   LIB_EXTENSION = "so",
   LN = "ln",
   LS = "ls",
   LUA = "/data/data/com.termux/files/usr/bin/lua5.1",
   LUA_BINDIR = "/data/data/com.termux/files/usr/bin",
   LUA_DIR = "/data/data/com.termux/files/usr",
   LUA_VERSION = "5.1",
   MAKE = "make",
   MD5 = "md5",
   MD5SUM = "md5sum",
   MKDIR = "mkdir",
   MKTEMP = "mktemp",
   OBJ_EXTENSION = "o",
   OPENSSL = "openssl",
   PWD = "pwd",
   RANLIB = "ranlib",
   RM = "rm",
   RMDIR = "rmdir",
   RSYNC = "rsync",
   RSYNCFLAGS = "--exclude=.git -Oavz",
   SCP = "scp",
   SEVENZ = "7z",
   SSCM = "sscm",
   SVN = "svn",
   TAR = "tar",
   TEST = "test",
   TOUCH = "touch",
   UNZIP = "unzip -n",
   WGET = "wget",
   WGETNOCERTFLAG = "--no-check-certificate",
   ZIP = "zip"
}
verbose = true
web_browser = "xdg-open"
wrapper_suffix = ""

-------------------------------------------------------------------------------
fs.quiet_stderr("pwd")

io.popen:       pwd 2> /dev/null
fs.is_superuser()
fs.current_user()

io.popen:       whoami  Mode:   r
fs.check_command_permissions(table: 0x70a38ae680)
fs.exists("/data/data/com.termux/files/usr/lib/luarocks/rocks-5.1")
fs.absolute_name("/data/data/com.termux/files/usr/lib/luarocks/rocks-5.1")
fs.root_of("/data/data/com.termux/files/usr/lib/luarocks/rocks-5.1")
fs.exists("/data/data/com.termux/files/usr/lib/luarocks")
fs.absolute_name("/data/data/com.termux/files/usr/lib/luarocks")
fs.exists("/data/data/com.termux/files/usr/lib")
fs.absolute_name("/data/data/com.termux/files/usr/lib")
fs.is_writable("/data/data/com.termux/files/usr/lib")
fs.is_dir("/data/data/com.termux/files/usr/lib")
fs.absolute_name("/data/data/com.termux/files/usr/lib")
fs.exists("/data/data/com.termux/files/usr/share/lua/5.1")
fs.absolute_name("/data/data/com.termux/files/usr/share/lua/5.1")
fs.is_writable("/data/data/com.termux/files/usr/share/lua/5.1")
fs.is_dir("/data/data/com.termux/files/usr/share/lua/5.1")
fs.absolute_name("/data/data/com.termux/files/usr/share/lua/5.1")
fs.exists("/data/data/com.termux/files/usr/bin")
fs.absolute_name("/data/data/com.termux/files/usr/bin")
fs.is_writable("/data/data/com.termux/files/usr/bin")
fs.is_dir("/data/data/com.termux/files/usr/bin")
fs.absolute_name("/data/data/com.termux/files/usr/bin")
fs.exists("/data/data/com.termux/files/usr/share/lua/5.1")
fs.absolute_name("/data/data/com.termux/files/usr/share/lua/5.1")
fs.is_writable("/data/data/com.termux/files/usr/share/lua/5.1")
fs.is_dir("/data/data/com.termux/files/usr/share/lua/5.1")
fs.absolute_name("/data/data/com.termux/files/usr/share/lua/5.1")
fs.lock_access("/data/data/com.termux/files/usr", true)
fs.make_dir("/data/data/com.termux/files/usr")
fs.execute("mkdir -p", "/data/data/com.termux/files/usr")
fs.quote_args("mkdir -p", "/data/data/com.termux/files/usr")
fs.Q("/data/data/com.termux/files/usr")
fs.execute_string("mkdir -p '/data/data/com.termux/files/usr'")

os.execute:     mkdir -p '/data/data/com.termux/files/usr'
..........: 0
fs.execute("ln -f", "/data/data/com.termux/files/usr/.lock.tmp.26460943", "/data/data/com.termux/files/usr/lockfile.lfs")
fs.quote_args("ln -f", "/data/data/com.termux/files/usr/.lock.tmp.26460943", "/data/data/com.termux/files/usr/lockfile.lfs")
fs.Q("/data/data/com.termux/files/usr/.lock.tmp.26460943")
fs.Q("/data/data/com.termux/files/usr/lockfile.lfs")
fs.execute_string("ln -f '/data/data/com.termux/files/usr/.lock.tmp.26460943' '/data/data/com.termux/files/usr/lockfile.lfs'")

os.execute:     ln -f '/data/data/com.termux/files/usr/.lock.tmp.26460943' '/data/data/com.termux/files/usr/lockfile.lfs'
ln: failed to create hard link '/data/data/com.termux/files/usr/lockfile.lfs' => '/data/data/com.termux/files/usr/.lock.tmp.26460943': Permission denied
##########: 256

Error: command 'install' requires exclusive write access to /data/data/com.termux/files/usr - failed to force the lock: File exists
fs.change_dir_to_root()
fs.is_dir("/data/data/com.termux/files/home")
fs.absolute_name("/data/data/com.termux/files/home")

### What steps will reproduce the bug?

maybe fixing build script 

### What is the expected behavior?

ability to install rocks normally 

### System information

termux-info:
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/com.termux-hoL113UHI6YY_uegVBlhkw==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=22033
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c211,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c211,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10467
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+d7bab73
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+d7bab73
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
ffmpeg/stable 6.1.1-3 aarch64 [upgradable from: 6.1.1-3]
libnghttp2/stable 1.61.0 aarch64 [upgradable from: 1.60.0]
termux-tools version:
1.41.2
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf+ #1 SMP PREEMPT Thu Apr 16 23:47:37 2020 aarch64 Android
Device manufacturer:
Sony
Device model:
SO-03K
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

```

```

**Comment by twaik** [comment]
AFAIK hardlinks are not supported in Android's fs used as a termux's home dir storage. Modify your code to use softlinks.

**Comment by haidaroh9** [comment]
on termux repository .default luarocks needs superuser to install rocks ,which is impossible on unrooted android.maybe some patches needed or move it to root packages

**Comment by licy183** [comment]
Please test whether the PR linked with this issue fixes it. Thanks!

**Comment by haidaroh9** [comment]
thanks it's work
luarocks install nlua
Installing https://luarocks.org/nlua-0.1.0-1.src.rock

nlua 0.1.0-1 depends on lua >= 5.1 (5.1-1 provided by VM: success)
Warning: /data/data/com.termux/files/usr/bin/nlua is not tracked by this installation of LuaRocks. Moving it to /data/data/com.termux/files/usr/bin/nlua~~
No existing manifest. Attempting to rebuild...
nlua 0.1.0-1 is now installed in /data/data/com.termux/files/usr (license: GPL-3.0)
