### ISSUE TITLE
[Question] How to use the host device microphone in Audacity

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#19679]
![Screenshot_2024-04-06_03-11-39](https://github.com/termux/termux-packages/assets/101167173/bd2d7451-7c61-4c4d-91d3-bf5addf8676b)

Can Audacity installed on Termux use the host device's microphone?

Since `termux-api` supports `termux-microphone-record`, I think there must be some way.

I wonder if it is possible.

**Comment by twaik** [comment]
AFAIK microphone might be recorded with regular SLES, no need to fall into termux-api. But currently there is no one who can fix it (Audacity).

**Comment by twaik** [comment]
1. Current version of portaudio (used in audacity as audio backend) does not support pulseaudio or sles. #21824 fixes it.
2. You must grant Termux:API microphone access to let apps running in termux record sound.

**Comment by hansm629** [comment]
@twaik 
Sorry for the late reply. I installed the package in the pull request, but I couldn't run audacity.

Did I miss something?
(termux-api's microphone permission has already been enabled.)



```
$ audacity
CANNOT LINK EXECUTABLE "audacity": cannot locate symbol "sqlite3_trace" referenced by "/system/lib64/libandroid_runtime.so"...

```

**Comment by twaik** [comment]
Probably you should do `LD_PRELOAD=/system/lib64/libsqlite.so audacity`.

**Comment by hansm629** [comment]
@twaik 
thank you!
It works perfectly, from microphone recording to mp3 saving!
![Screenshot_2024-10-18_01-55-49](https://github.com/user-attachments/assets/b37e8294-c1eb-47eb-a93d-6ce9c4206c19)

**Comment by twaik** [comment]
Good. It seems like I found a `sqlite3` problem source, trying to fix it.

**Comment by twaik** [comment]
Ok, I fixed a sqlite problem.
