### ISSUE TITLE
cant install scikit-learn and solution to it is missing [Fixed]

### ISSUE THREAD

**Issue by mahdoosh1** [termux/termux-packages#19681]
### Edit

EDIT: found the solution by myself, scroll down to last comment to find solution

### Issue

i have found out that solution is at #17552 but when i load that issue i see a message telling: 'failed to fetch issue 17552'

**Comment by Biswa96** [comment]
There are other similar issues with scikit-learn https://github.com/termux/termux-packages/issues?q=is%3Aissue+scikit-learn

**Comment by mahdoosh1** [comment]
> There are other similar issues with scikit-learn

i found the solution by myself

i downloaded scikit-learn.tar.gz from pypi using wget and then i ran `cd scikit-learn`
`python setup.py install`

this will build scikit learn without reinstalling scipy

and it might be working now.

**Comment by mahdoosh1** [comment]
ok install is complete but `pip list` is showing two scikit-learn packages for some reason

**Comment by mahdoosh1** [comment]
and `python -c 'import sklearn'`
is giving an error

**Comment by mahdoosh1** [comment]
> and `python -c 'import sklearn'`
> is giving an error

my bad, i wasnt in home directory

**Comment by mahdoosh1** [comment]
> my bad, i wasnt in home directory

IT IS WORKING NOW!!!!

**Comment by mahdoosh1** [comment]
here is all commands i have ran:
```bash
wget https://files.pythonhosted.org/packages/ef/e5/c09d20723bfd91315f6f4ddc77912b0dcc09588b4ca7ad2ffa204607ad7f/scikit-learn-1.4.2.tar.gz

tar xvzf scikit-learn-1.4.2.tar.gz

python scikit-learn-1.4.2/setup.py install

python -c 'import sklearn\nprint(sklearn.__version__)'

```

requirements:
wget (termux package)
setuptools (python package)
Cython (python package)
python-scipy (termux-package)
python-numpy (termux-package)
python (termux-package)

**Comment by Biswa96** [comment]
This issue seems to be fixed and can be closed.

**Comment by mahdoosh1** [comment]
> This issue seems to be fixed and can be closed.

sure!

**Comment by Duuckjing** [comment]
> here is all commands i have ran:
> ```bash
> wget https://files.pythonhosted.org/packages/ef/e5/c09d20723bfd91315f6f4ddc77912b0dcc09588b4ca7ad2ffa204607ad7f/scikit-learn-1.4.2.tar.gz
> 
> tar xvzf scikit-learn-1.4.2.tar.gz
> 
> python scikit-learn-1.4.2/setup.py install
> 
> python -c 'import sklearn;print(sklearn.__version__)'
> 
> ```
> 
> requirements:
> wget (termux package)
> setuptools (python package)
> Cython (python package)
> python-scipy (termux-package)
> python-numpy (termux-package)
> python (termux-package)

I'm also trying to install scikit-learn and I'm excited to find it was just discussed this month. But i got stuck at the third step: the error log still says that scipy is required to install scikit-learn. I've got python-scipy installed and used ```hash -r``` to update the package hash; My build is under a venv.

Here is the error log
```(phantom) ~/phantom $ python scikit-learn-1.4.2/setup.py install
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/phantom/scikit-learn-1.4.2/setup.py", line 34, in <module>
    with open("./README.rst") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './README.rst'                                                            (phantom) ~/phantom $ cd scikit-learn-1.4.2/
(phantom) ~/phantom/scikit-learn-1.4.2 $ ls                      COPYING      README.rst   pyproject.toml         sklearn
MANIFEST.in  doc          scikit_learn.egg-info
Makefile     examples     setup.cfg
PKG-INFO     meson.build  setup.py
(phantom) ~/phantom/scikit-learn-1.4.2 $ python setup.py install Partial import of sklearn during the build process.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/phantom/scikit-learn-1.4.2/setup.py", line 161, in check_package_status
    module = importlib.import_module(package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/phantom/scikit-learn-1.4.2/setup.py", line 639, in <module>
    setup_package()
  File "/data/data/com.termux/files/home/phantom/scikit-learn-1.4.2/setup.py", line 630, in setup_package
    check_package_status("scipy", min_deps.SCIPY_MIN_VERSION)
  File "/data/data/com.termux/files/home/phantom/scikit-learn-1.4.2/setup.py", line 188, in check_package_status
    raise ImportError(
ImportError: scipy is not installed.
scikit-learn requires scipy >= 1.6.0.
Installation instructions are available on the scikit-learn website: https://scikit-learn.org/stable/install.html```

**Comment by mahdoosh1** [comment]
> I don't know why there is the README file but it couldn't read... And after i changed the directory it continued but failed with scipy not installed.

because the package python-scipy is used to be installed in the user environment not in a virtual environment

if you want to install scipy to your venv you have to copy the installed scipy directory to your venv specific folder, i dont know how venvs work but here is the directory where your python packages are installed:

`~/  $   cd`
`~/  $   cd ../usr/lib/python-3.11/site-packages`

after these commands you will see all packages (including scipy) at here, you may need a toturial how to move a package from user to venv

**Comment by Duuckjing** [comment]
It is solved now, when creating a new venv after python-scipy is installed, the venv will have scipy package, and I just add a few arguments to install scikit-learn directly from pip rather than from source.

**Comment by mahdoosh1** [comment]
> and I just add a few arguments to install scikit-learn directly from pip rather than from source.

what are those arguments  please?

**Comment by Duuckjing** [comment]
> what are those arguments  please?
`--no-build-isolation`

**Comment by mahdoosh1** [comment]
> > what are those arguments  please?
> `--no-build-isolation`
> 

Oh, Very thanks
