### ISSUE TITLE
Segfault in Python in Termux

### ISSUE THREAD

**Issue by Cypher1** [termux/termux-packages#1969]
I'm having an issue with my Sony Xperia running Android Oreo.

Specifically, certain numbers cause segmentation faults when divided.

I've seen this with
    890/23.0
    890/3
    880/4

I'm not sure what other numbers are effected but can set up a script to test them if needed (I am about to get on a flight).

Python version is 3.6.1
Gcc is version 4.2.1

Can someone track this down or help me understand what to do to debug it (I'm hoping to avoid trying to install gdb on my phone).

**Comment by xeffyr** [comment]
In Termux repository current python version is 3.6.4 not 3.6.1, so you may want to update. I'm currently using python 3.6.3, and there is no segfault:
```
Python 3.6.3 (default, Oct  7 2017, 12:01:30) 
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 890/23.0
38.695652173913047
>>> 890/3
296.66666666666669
>>> 880/4
220.0
```

**Comment by its-pointless** [comment]
The gcc version is clang which is gcc 4,2 compatible(its far more complicated than that...) but yeah if you are using old versions of python its not much help. But that is an interesting bug you have there.

**Comment by fornwall** [comment]
@Cypher1 Can you try updating to the latest python version by running `pkg up` and see if the problem remains for you?

**Comment by Cypher1** [comment]
PKG update seems to have fixed the problem.
My code no longer segfaults (always a lovely feeling).

Thanks

Is there anything that needs to be done to make sure that this doesn't foul
up anyone else?

**Comment by fornwall** [comment]
Great that it works now!

> Is there anything that needs to be done to make sure that this doesn't foul up anyone else?

Not that I know of, we'll see if we ever hit a problem like this again!
