### ISSUE TITLE
[Bug]: every time i install a package an issue comes

### ISSUE THREAD

**Issue by vishal14102005** [termux/termux-packages#19698]
### Problem description

every time i install any pkg it says
"CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/git-core/git-remote-https": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libssh2.so in namespace (default)"

### What steps will reproduce the bug?

I don't know but you have to

### System information

termux-info:

```

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
apt/stable 2.7.10 aarch64 [upgradable from: 2.3.13-3]
bash/stable 5.2.26 aarch64 [upgradable from: 5.1.12-2]
ca-certificates/stable 1:2024.03.11-2 all [upgradable from: 1:2021-10-26-0]
command-not-found/stable 2.4.0-19 aarch64 [upgradable from: 1.71]
coreutils/stable 9.4 aarch64 [upgradable from: 9.0]
dash/stable 0.5.12 aarch64 [upgradable from: 0.5.11.5]
debianutils/stable 5.17 aarch64 [upgradable from: 5.5]
dialog/stable 1.3-20240307-0 aarch64 [upgradable from: 1.3-20211214-0]
diffutils/stable 3.10 aarch64 [upgradable from: 3.8]
dos2unix/stable 7.5.2 aarch64 [upgradable from: 7.4.2]
dpkg/stable 1.22.2 aarch64 [upgradable from: 1.21.1]
ed/stable 1.20.1 aarch64 [upgradable from: 1.17-4]
findutils/stable 4.9.0-2 aarch64 [upgradable from: 4.8.0]
gawk/stable 5.3.0 aarch64 [upgradable from: 5.1.1]
gpgv/stable 2.4.4 aarch64 [upgradable from: 2.3.4]
grep/stable 3.11 aarch64 [upgradable from: 3.7-2]
gzip/stable 1.13 aarch64 [upgradable from: 1.11-3]
inetutils/stable 2.4-1 aarch64 [upgradable from: 1.9.4-12]
less/stable 633-1 aarch64 [upgradable from: 590]
libandroid-support/stable 28-3 aarch64 [upgradable from: 28-2]
libassuan/stable 2.5.6 aarch64 [upgradable from: 2.5.5]
libc++/stable 26b aarch64 [upgradable from: 23b-3]
libcap-ng/stable 2:0.8.4 aarch64 [upgradable from: 1:0.8.3-pre1-0]
libcrypt/stable 0.2-5 aarch64 [upgradable from: 0.2-3]
libevent/stable 2.1.12-2 aarch64 [upgradable from: 2.1.12]
libexpat/stable 2.6.2 aarch64 [upgradable from: 2.4.2]
libgcrypt/stable 1.10.3 aarch64 [upgradable from: 1.9.4]
libgmp/stable 6.3.0 aarch64 [upgradable from: 6.2.1]
libgnutls/stable 3.8.3 aarch64 [upgradable from: 3.6.16-1]
libgpg-error/stable 1.48 aarch64 [upgradable from: 1.43]
libiconv/stable 1.17 aarch64 [upgradable from: 1.16-3]
libidn2/stable 2.3.4 aarch64 [upgradable from: 2.3.2]
liblz4/stable 1.9.4 aarch64 [upgradable from: 1.9.3]
liblzma/stable 5.6.1+really5.4.5 aarch64 [upgradable from: 5.2.5-1]
libmpfr/stable 4.2.1 aarch64 [upgradable from: 4.1.0]
libnettle/stable 3.9.1 aarch64 [upgradable from: 3.7.3]
libnghttp2/stable 1.61.0 aarch64 [upgradable from: 1.46.0]
libnpth/stable 1.6-2 aarch64 [upgradable from: 1.6-1]
libssh2/stable 1.11.0 aarch64 [upgradable from: 1.10.0]
libtirpc/stable 1.3.4 aarch64 [upgradable from: 1.3.2]
libunistring/stable 1.1 aarch64 [upgradable from: 0.9.10-5]
lsof/stable 4.99.3 aarch64 [upgradable from: 4.94.0-1]
nano/stable 7.2 aarch64 [upgradable from: 6.0]
ncurses/stable 6.4.20231001-3 aarch64 [upgradable from: 6.2.20200725-6]
pcre2/stable 10.43 aarch64 [upgradable from: 10.39-2]
procps/stable 3.3.17-5 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.6-2 aarch64 [upgradable from: 23.4]
readline/stable 8.2.1 aarch64 [upgradable from: 8.1.1]
sed/stable 4.9-1 aarch64 [upgradable from: 4.8-2]
tar/stable 1.35 aarch64 [upgradable from: 1.34]
termux-am-socket/stable 1.5.0 aarch64 [upgradable from: 1.02]
termux-am/stable 0.8.0 all [upgradable from: 0.4]
termux-exec/stable 1:1.0 aarch64 [upgradable from: 1:0.9]
termux-keyring/stable 3.11-1 all [upgradable from: 2.4]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-1]
termux-tools/stable 1.42.0 all [upgradable from: 0.155]
unbound/stable 1.19.3 aarch64 [upgradable from: 1.13.2-1]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-7]
util-linux/stable 2.39.3-4 aarch64 [upgradable from: 2.37.2-1]
xxhash/stable 0.8.2 aarch64 [upgradable from: 0.8.1]
xz-utils/stable 5.6.1+really5.4.5 aarch64 [upgradable from: 5.2.5-1]
zlib/stable 1.3.1 aarch64 [upgradable from: 1.2.11-5]
Android version:
13
Kernel build information:
Linux localhost 4.19.191+ #1 SMP PREEMPT Sun Feb 4 01:43:58 CST 2024 aarch64 Android
Device manufacturer:
INFINIX
Device model:
Infinix X6739
![Screenshot_20240407-211413](https://github.com/termux/termux-packages/assets/166349273/d1333c1d-8776-43a8-875e-78bbc07c995e)
![Screenshot_20240407-211413](https://github.com/termux/termux-packages/assets/166349273/56bb6e8e-bfb7-4ff4-946f-0ba5e558376b)

**Comment by harieamjari** [comment]
Try `pkg upgrade`.

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking
