### ISSUE TITLE
Auto update failing for libtiff

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#19703]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [libtiff](https://github.com/termux/termux-packages/blob/b24783e01db91af7a2d6f1a3fcc0eca2ed3d6007/packages/libtiff) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating libtiff [Current version: 4.6.0]
INFO: package being updated to 4.6.0t.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   153    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

libtiff: failed to calculate the new checksum
Already up to date.
ERROR: failed to update checksum.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-04-08 12:14:16 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/8599725923">8599725923</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by pranav10780** [comment]
The package is up to date and the error is caused by the incorrect versoin number ```4.6.0t```
