### ISSUE TITLE
[Package]: meson

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-packages#19723]
### Why is it worth to add this package?

Meson® is a project to create the best possible next-generation build system. 

### Home page URL

http://mesonbuild.com/

### Source code URL

https://github.com/mesonbuild/meson

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

I notice meson is written in python which make it doesn't respect https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy . However, meson depends on ninja in order to `meson compile`. The last python package `pynvim` depends on a cython package is ACKed. So I want to know can meson be ACKed. Thanks for discussion.

**Comment by TomJo2000** [comment]
> I notice meson is written in python which make it doesn't respect https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy . However, meson depends on ninja in order to `meson compile`. The last python package `pynvim` depends on a cython package is ACKed. So I want to know can meson be ACKed. Thanks for discussion.

That ACK was specifically for `pynvim`,
for the purposes of feature parity with `vim-python`,
meson was not included in that.
