### ISSUE TITLE
Could not find nokogiri-1.8.0 in any of the sources

### ISSUE THREAD

**Issue by PEREZLOMELI** [termux/termux-packages#1976]
No puedo encontrar la solucion

**Comment by xeffyr** [comment]
`gem install nokogiri -v '1.8.0' -- --use-system-libraries`, no ?

**Comment by shaheem007** [comment]
gem install nokogiri -v '1.8.0' -- --use-system-libraries
Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.8.0/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -I /data/data/com.termux/files/usr/lib/ruby/2.6.0 -r ./siteconf20190505-22644-11r6sro.rb extconf.rb --use-system-libraries
mkmf.rb can't find header files for ruby at /data/data/com.termux/files/usr/lib/ruby/include/ruby.hYou might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.8.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/arm-linux/2.6.0/nokogiri-1.8.0/gem_make.out

**Comment by xeffyr** [comment]
@shaheem007 Carefully read error and determine which dependencies are missing.

**ruby-dev**, **libxml2-dev**, **libxslt-dev**, **zlib-dev**... **clang**

**Comment by xeffyr** [comment]
It even suggests you: _You might have to install separate package for the ruby development environment, ruby-dev or ruby-devel for example._
