### ISSUE TITLE
[Node.js version - 21.7.3]: 

### ISSUE THREAD

**Issue by Web-Developer-is-here** [termux/termux-packages#19774]
### Why is it worth to add this package?

I, had observed the termux, and it is great. 
**Requirment:**
_The Node JS is updated time to time and new versions keep coming, still there is 21.6 version available in termux, but the new features for the 21.7.3 is not still available yet, various new features and technological advancements. _

**Improvement**
_This is gonna provide learners and devs a great facility for learning further and enhance the way of learning, as well as the one most bug is that we also **can't be able to download the mongodb directly in termux,** better fix it._

**Conclusion:**
_This package is or Node.js of new 21.7.3 version is very much essential for the developers to code on Back-end and Server side, as well as due to the **non-installment of mongodb directly** we are too facing with the issue of database creation as well as database managements, kindly **make the new Node.js version [21.7.3] available for termux,**, that when we run the command ```pkg i nodejs``` it should install the node of version 21.7.3 **not** of the current and older one that is 21.6 default set in termux. Kindly fix this two issues and for this I as well as great development teams would be obligized to you all,  termux development team, if want to contact then can contact on my specific link, thanks !_

### Home page URL

https://github.com/

### Source code URL

https://github.com/Web-Developer-is-here/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
No need to ask for package updates. We see all new versions as soon as they are available but have no enough people to update packages. Pull requests are always welcome.

**Comment by Biswa96** [comment]
Maybe this is the first time, does not this issue feel like generated with the help of LLM?

**Comment by twaik** [comment]
Probably. But anyway it is closed.
