### ISSUE TITLE
[Package]: fcitx5-hangul, fcitx5-mozc, fcitx5-chinese-addons packages request 

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#19788]
### Why is it worth to add this package?

For East Asian users, the keyboard language cannot be changed when using an external keyboard in a Termux XFCE desktop environment.

When using a Samsung flagship smartphone
DeX mode allows you to use your phone like a desktop PC
(The `Qualcomm Snapdragon 8 Gen3` has CPU performance close to the `Apple M1` on Geekbench 5.)

Through a Bluetooth or USB keyboard
I think it would be very cool if language conversion was possible.

Most packages related to `fcitx5` have already been ported to the `Termux main-repo`.

required for a specific language transition

`fcitx5-hangul` (Korean)
`fcitx5-mozc` (Japanese)
`fcitx5-chinese-addons` (Chinese)

The above packages are not ported, so they seem essential for fitting the fcitx5 package.

If you use a Bluetooth keyboard or a USB keyboard, you cannot change the language, so it is not possible to properly surf the web, so I think many East Asian users will like the above packages added.

[#19775](https://github.com/termux/termux-packages/issues/19775)
The above issue that I registered as a bug also appears to be a problem caused by the absence of `fcitx5-hangul`.

Even on `PRoot-Distro Debian`, when I only deleted `fcitx5-hangul`, the USB keyboard's language switching function did not work.

Please review it seriously.

### Source code URL

https://github.com/fcitx/fcitx5-hangul

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

https://github.com/fcitx/fcitx5-hangul
https://github.com/fcitx/mozc
https://github.com/fcitx/fcitx5-chinese-addons

**Comment by Biswa96** [comment]
Do you need all of those fcitx modules? I have compiled fcitx5-hangul successfully and can create a pull request to add that.

**Comment by hansm629** [comment]
@Biswa96 
Oh oh!
Please send us the deb package and we will test it right away!

**Comment by Biswa96** [comment]
I shall create a pull request to add those but I am waiting for another PR with a dependency. Could you please answer my previous question?

**Comment by hansm629** [comment]
@Biswa96
Are you porting the fcitx5 full module?

When are you expecting PR?

**Comment by Biswa96** [comment]
I am waiting for #19815

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/8766093116?pr=19858

**Comment by TomJo2000** [comment]
I did also leave detailed instructions for testing PRs in the https://github.com/termux/termux-packages/issues/19788#issuecomment-2061453198 above if needed.

**Comment by hansm629** [comment]
@Biswa96 

https://github.com/termux/termux-packages/actions/runs/8766093116


![Screenshot_2024-04-21_03-42-56](https://github.com/termux/termux-packages/assets/101167173/8e478d39-b44c-4549-94b4-74fbb8370435)



The Korean keyboard works well!

It's all thanks to you!
thank you! :)

**Comment by TomJo2000** [comment]
Merging #19858 then.

**Comment by Biswa96** [comment]
@hansm629 There are two other same language related issues. Are those fixed now?

**Comment by hansm629** [comment]
@Biswa96
Unfortunately
Japanese and Chinese keyboards do not work with `fcitx5-hangul`.

Japanese is `fcitx5-mozc`
https://github.com/fcitx/mozc

Chinese is `fcitx5-chinese-addons`
https://github.com/fcitx/fcitx5-chinese-addons



Korean keyboard works with `fcitx5-hangul`.
And it works very well. :)

**Comment by liuo2023** [comment]
[fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons)   it work！ However,The Chinese input method does not display candidate words and does not display the status bar。。maybe it need fcitx5-lua

**Comment by Biswa96** [comment]
[fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons) is not present in termux-packages. Could you test the package if it is added?

**Comment by liuo2023** [comment]
> [fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons) is not present in termux-packages. Could you test the package if it is added?

it work,but input method does not display candidate words and does not display the status bar.

**Comment by hansm629** [comment]
@Biswa96 
Could you please distribute the latest `fcitx5-hangul`?

Recently, a bug related to Korean input has been fixed.

https://github.com/fcitx/fcitx5-hangul/commit/169955806ae158895a947a4a0c3514e7db93ba56

**Comment by twaik** [comment]
The commit you referenced is not a part of release. It is in master branch. We prefer to package releases, not unstable/master branches.

**Comment by hansm629** [comment]
@twaik 
ah...
I understand what mean.
Please forget what I just asked for.

We will wait until it is reflected in the official release.

**Comment by Biswa96** [comment]
> Recently, a bug related to Korean input has been fixed.
> [fcitx/fcitx5-hangul@1699558](https://github.com/fcitx/fcitx5-hangul/commit/169955806ae158895a947a4a0c3514e7db93ba56)

That commit has been added in 5.1.4 release. Please update the package.

**Comment by hansm629** [comment]
@Biswa96
thank you!
Bug fixed! :)

**Comment by k10876** [comment]
Hi guys,

I'm recently testing out the [fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons) for Termux.

Unfortunately, it seems that it's impossible to get this addon working like a regular Chinese input method. Even really hard to make it work (i guess it's my problem lol).

Hope that more people are involved in developing the Chinese one and making it baseline usable. Should I open a issue?

---
Outputs:
```
╭─termux @ termux in /data/data/com.termux/files/usr 
╰─✗  fcitx5-configtool
fcitx5-config: IMPage changed
I2025-02-14 01:23:09.401687 addonmanager.cpp:205] Loaded addon punctuation
E2025-02-14 01:23:09.409511 addonloader.cpp:95] Failed to create addon: pinyin io fail: unspecified iostream_category error
I2025-02-14 01:23:09.409574 addonmanager.cpp:201] Could not load addon pinyin
fcitx5-config: QDBusError("org.freedesktop.DBus.Error.Failed", "Failed to get input method.")
```

**Comment by Biswa96** [comment]
There is an open issue about [fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons) package. The dictionary files are absent in the package and I did not find any proper way to add it.

**Comment by k10876** [comment]
@Biswa96 I'm actually struggling to get the Chinese add-on working. Is it (Pinyin, Shuangpin) working on your side?

I'm trying to let it work in a xfce4 GUI in Termux and it's impossible for me.

**Comment by Biswa96** [comment]
See #22121 where I provided an workaround but I have not tested that recently.

**Comment by k10876** [comment]
@Biswa96 Thanks for that! I've fixed the issue.

The reason for the candidate screen not showing up is due to the lack of [xdg_desktop_portal](https://github.com/flatpak/xdg-desktop-portal). It generates (probably) org.freedesktop.portal.Desktop.service, and it might be required for the UI to work.

The error message is:
```
[portalsettingmonitor.cpp:115] DBus call error: org.freedesktop.DBus.Error.ServiceUnknown The name org.freedesktop.portal.Desktop was not provided by any service files
```

Unlike hangul (where it might not be really necessary to fix the UI), Chinese Pinyin layout requires this package to work properly. Otherwise, one cannot select candidates, and it's quite a pain. 

I haven't figured out how to install this on termux yet, but i think it will require quite a lot of effort. 

Leaving this here for now.

**Comment by Biswa96** [comment]
fcitx5-chinese-addons 5.1.8-3 now works and loads dictionaries properly. Please update the packages.

**Comment by liuo2023** [comment]
nice！

**Comment by 2clouds** [comment]
Due to a similar cause, the candidate screen for Korean input (e.g., when selecting Hanja) also fails to appear.
