### ISSUE TITLE
[Bug]: APT failed to build

### ISSUE THREAD

**Issue by shadowprospero** [termux/termux-packages#19791]
### Problem description

The APT binary apt_2.7.10.tar.xz not found in the remote repository

Downloading https://deb.debian.org/debian/pool/main/a/apt/apt_2.7.10.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   260    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Failed to download https://deb.debian.org/debian/pool/main/a/apt/apt_2.7.10.tar.xz

### What steps will reproduce the bug?

1. Run ./scripts/run-docker.sh
2. In docker run ./scripts/build-bootstraps.sh --architectures aarch64

### System information

termux-info:

```

```

**Comment by twaik** [comment]
Apt origin site does not keep sources of old versions. Probably we should update the package.

**Comment by shadowprospero** [comment]
I tried with next version but no luck also

Downloading https://deb.debian.org/debian/pool/main/a/apt/apt_2.7.12.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2295k  100 2295k    0     0  3914k      0 --:--:-- --:--:-- --:--:-- 3910k
Applying patch: 0000-cmake-fix.patch
Applying patch: 0001-no-macro-redef.patch
Applying patch: 0002-no-locales.patch
1 out of 2 hunks FAILED -- saving rejects to file apt-pkg/deb/debrecords.cc.rej
[*] Building 'apt' exited with exit code 1

Probably something with patches, not familiar with this

**Comment by twaik** [comment]
Probably because it should be properly updated. You can not simply bump version in `build.sh` and expect it will work. You must port patches to newer version of sources.

**Comment by shadowprospero** [comment]
Agree. I'm not qualified enough for this. I'll wait for your fixes

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/8758711992
