### ISSUE TITLE
'who' command?

### ISSUE THREAD

**Issue by MinchinWeb** [termux/termux-packages#1981]
I'd like to install the *who* command, but I can't figure out which package would contain it. Suggestions? Thanks!

**Comment by Atavic** [comment]
[Bash](https://ss64.com/bash/who.html).

**Comment by MinchinWeb** [comment]
@Atavic , @Grimler91 I have *bash* installed, but am still missing the *who* commnad. Am I missing something basic here, or should I open a new ticket?

![2017-12-27 17 26 09](https://user-images.githubusercontent.com/1548809/34396734-3025fc0c-eb2c-11e7-84ef-4b1300d2d0fa.png)

**Comment by Quasic** [comment]
I thought I used to have who, but I don't, now. It's not listed in help, either.

**Comment by Grimler91** [comment]
@MinchinWeb you're right, it's missing. Sorry for closing.

**Comment by Atavic** [comment]
Wait, did you mean whoami? `whoami` has no spaces.

**Comment by MinchinWeb** [comment]
I'm trying to use [liquidprompt](https://github.com/nojhan/liquidprompt/blob/master/liquidprompt#L596), which relies on `who am i` (yes, with the spaces).

Google tells me `who` is actually part of coreutils but it is actually [disabled](https://github.com/termux/termux-packages/blob/master/packages/coreutils/build.sh#L9) without a ton of explanation.

[Another ticket](https://github.com/termux/termux-packages/issues/600) about `who` missing.

**Comment by sdrausty** [comment]
@MinchinWeb `who` is available in Arch Linux Termux PRoot on Android, Chromebook and Fire.  It doesn't work as expected, and this is due to app permissions.

```
[20:43 home ]$ who 
[20:56 home ]$ who -a
[20:56 home ]$ who --all
[20:57 home ]$ who --version
who (GNU coreutils) 8.28
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Joseph Arceneaux, David MacKenzie, and Michael Stone.
```

**Comment by xeffyr** [comment]
Termux is **single-user**, so commands like `who`, `users`, `last` will not work.

**Comment by sdrausty** [comment]
@xeffyr have you used `adduser` then `su - username` in Arch Linux in Termux PRoot?

**Comment by xeffyr** [comment]
@sdrausty, topic about using `who` in Termux, not in Arch Linux. I'll try su in Arch Linux, but I guess it will fail under PRoot.

**Comment by sdrausty** [comment]
@xeffyr Arch Linux in Termux PRoot is on topic for more than the next three reasons.  
a)  Arch Linux runs in Termux on device affording packages galore on device today.  
b)  Termux PRoot https://github.com/termux/proot is used to make this work.  
c)  It is a very important on device diagnostic tool.  See https://github.com/termux/termux-packages/issues/1798 for one of the results.  Does it work on device and how it works on device comparison is critical for expedient diagnosis.  
 
Using multiuser mode in Arch Linux in Termux PRoot is necessary to access some features that do not run as root user in Arch Linux in Termux PRoot.  Use `adduser`  then `su - username` to login as a user, not root.

**Comment by Atavic** [comment]
@MinchinWeb see: https://github.com/nojhan/liquidprompt/issues/532

**Comment by xeffyr** [comment]
Termux does not support utmp/wtmp/btmp files so command "who" is useless here because it will display nothing.

**Comment by sixiyizai** [comment]
maybe you can use this script

`
#!/usr/bin/env python
"""
summary:
    termux python script
    monitor tty login
python:
    python3.x
usage:
    python monitor_tty.py
"""
import os
import time
from collections import deque

g_cache_que = deque(maxlen=100)


def tty_wall(msg):
    cmd_msg = "\x1b[92m" + msg + "\033[0m"
    for i in range(1, 100):
        tty_fn = "/dev/pts/{}".format(i)
        if os.path.exists(tty_fn):
            cmds = "echo {msg} > {fn}".format(msg=cmd_msg, fn=tty_fn)
            os.system(cmds)


def monitor_tty():
    p = "/dev/pts/{}"
    for i in range(1, 100):
        tty_f = p.format(i)
        if os.path.exists(tty_f):
            tty_ctime = os.stat(tty_f).st_ctime
            if tty_ctime not in g_cache_que:
                g_cache_que.append(tty_ctime)
                tty_wall('someone login in other tty')


def main():
    while 1:
        monitor_tty()
        time.sleep(3)


if __name__ == '__main__':
    main()

`

**Comment by sixiyizai** [comment]
```
#!/usr/bin/env python
"""
summary:
    termux python script
    monitor tty login
python:
    python3.x
usage:
    python monitor_tty.py
"""
import os
import time
from collections import deque

g_cache_que = deque(maxlen=100)


def tty_wall(msg):
    cmd_msg = "\x1b[92m" + msg + "\033[0m"
    for i in range(1, 100):
        tty_fn = "/dev/pts/{}".format(i)
        if os.path.exists(tty_fn):
            cmds = "echo {msg} > {fn}".format(msg=cmd_msg, fn=tty_fn)
            os.system(cmds)


def monitor_tty():
    p = "/dev/pts/{}"
    for i in range(1, 100):
        tty_f = p.format(i)
        if os.path.exists(tty_f):
            tty_ctime = os.stat(tty_f).st_ctime
            if tty_ctime not in g_cache_que:
                g_cache_que.append(tty_ctime)
                tty_wall('someone login in other tty')


def main():
    while 1:
        monitor_tty()
        time.sleep(3)


if __name__ == '__main__':
    main()

```

**Comment by sixiyizai** [comment]
maybe you can use this script 
i use this script and invoke by sshd command  when open termux 

```
#!/usr/bin/env python
"""
summary:
    termux python script
    monitor tty login
python:
    python3.x
usage:
    python monitor_tty.py
"""
import os
import time
from collections import deque

g_cache_que = deque(maxlen=100)


def tty_wall(msg):
    cmd_msg = "\x1b[92m" + msg + "\033[0m"
    for i in range(1, 100):
        tty_fn = "/dev/pts/{}".format(i)
        if os.path.exists(tty_fn):
            cmds = "echo {msg} > {fn}".format(msg=cmd_msg, fn=tty_fn)
            os.system(cmds)


def monitor_tty():
    p = "/dev/pts/{}"
    for i in range(1, 100):
        tty_f = p.format(i)
        if os.path.exists(tty_f):
            tty_ctime = os.stat(tty_f).st_ctime
            if tty_ctime not in g_cache_que:
                g_cache_que.append(tty_ctime)
                tty_wall('someone login in other tty')


def main():
    while 1:
        monitor_tty()
        time.sleep(3)


if __name__ == '__main__':
    main()

```
