### ISSUE TITLE
[Package]: go-pd

### ISSUE THREAD

**Issue by GUUser91** [termux/termux-packages#19826]
### Why is it worth to add this package?

It's needed in order to upload to and download from pixeldrain in a commandline

### Home page URL

https://github.com/ManuelReschke/go-pd

### Source code URL

https://github.com/ManuelReschke/go-pd

### Packaging policy acknowledgement

- [ ] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
> # Packages must be active, well-known projects

> Software available in major Linux distributions has more chances to be included into Termux repositories. We will not accept outdated, dead projects as well as projects which do not have active community.

**Comment by TomJo2000** [comment]
Can probably be packaged in the TUR instead.
https://github.com/termux-user-repository/tur
