### ISSUE TITLE
[Package]: dnsmasq

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#19830]
### Why is it worth to add this package?

Because it is a very powerful firewall whose settings can be imported from any linux machine.

### Home page URL

https://thekelleys.org.uk/dnsmasq/doc.html

### Source code URL

https://thekelleys.org.uk/dnsmasq/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

I was recently informed that dnsmasq existed on termux. When I tried installing ig `pkg install dnsmasq` it failed. So I am creating this request.

**Comment by Biswa96** [comment]
dnsmasq is present in root repository https://github.com/termux/termux-packages/tree/master/root-packages/dnsmasq
