### ISSUE TITLE
Package request: dictd

### ISSUE THREAD

**Issue by srajasimman** [termux/termux-packages#1984]
Hi there,

I need the following package for termux.

https://sourceforge.net/projects/dict/files/dictd/dictd-1.12.1/

Thanks.

**Comment by sdrausty** [comment]
`dictd` is currently available through https://sdrausty.github.io/TermuxArch/ Arch Linux in Termux PRoot on Android, Chromebook and Fire.  Other dictionaries like `wtf` and `stardict` are available likewise.

**Comment by its-pointless** [comment]
Iv added dictd and its dependency libwaa. I hsve no idea how to use dictd properly but iv got binaries available  you can add my repo with instructions github.com/its-pointless/gcc_termux or download from https://github.com/its-pointless/its-pointless.github.io/tree/master/files/dists/termux/extras ...
Just need to know if it works :)

**Comment by ayatakesi** [comment]
Hi.
I build dictd on my tablets termux.
I posted procedure about this to [here](https://qiita.com/ayatakesi/items/4150c32ea26ac7f82e60).
This article is written in Japanese, but only terminal log and patch file, you can understand what is necessarily to build dictd on termux.
Also I will create pull-request to termux-packages about this.

**Comment by xeffyr** [comment]
Closing as package is already available via `pkg install`.
