### ISSUE TITLE
[pkg request] potrace

### ISSUE THREAD

**Issue by Wolfram-Wolf** [termux/termux-packages#1987]
http://potrace.sourceforge.net/

**Comment by sdrausty** [comment]
`potrace` is currently available through https://sdrausty.github.io/TermuxArch/ Arch Linux in Termux PRoot on Android, Chromebook and Fire.  See https://sdrausty.github.io/TermuxArch/ for more information how to use `potrace` on your device today.

**Comment by fornwall** [comment]
Thanks to @its-pointless there is now a potrace package available - install it with

    pkg install potrace
