### ISSUE TITLE
[PSA]: `libicu 74.2` is deprecated packages are being rebuilt against `libicu 75.1`.

### ISSUE THREAD

**Issue by RajDave-Dev** [termux/termux-packages#19879]
### Problem description

Upgrading the libicu to 75 breaks node js. Currently I got the error in nodejs-lts.
Here is the error I got for nodejs-lts
```
CANNOT LINK EXECUTABLE "node": library "libicui18n.so.74" not found: needed by main executable
```

### What steps will reproduce the bug?

To produce error for nodejs-lts
1. Upgrade libicu to 75
2. Run node or npm command
3. Error occurred 

### What is the expected behavior?

Should run.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=14036
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:
13
Kernel build information:
Linux localhost 4.19.191+ #1 SMP PREEMPT Sun Feb 18 12:08:07 CST 2024 aarch64 Android
Device manufacturer:
Ganium
Device model:
Ganium GT
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
```

I have made my own custom rom from the stock android and did some tweaks to meet my requirements.

**Comment by Biswa96** [comment]
Please wait for the CI to complete in 08353e19adc8b3875feaf63af7d12cb92dce76c1

**Comment by MrAimo** [comment]
PHP has a similar error
LOG：CANNOT LINK EXECUTABLE "php": library "libicuio.so.74" not found: needed by main executable

**Comment by Cube5x59999** [comment]
Same on nodejs-lts version.

**Comment by TomJo2000** [comment]
I have left a note in the comment above.
I like like to again reiterate that:
> [!WARNING]
>
> # ***`libicu 74.2` is deprecated and unsupported on Termux at this stage, and manually installing it will result in breaking packages that rely on it going forward***

**Comment by TomJo2000** [comment]
Looks like all packages are rebuilding successfully at this point, with just a couple stragglers left to push up to the repos.

NodeJS and PHP are already pushed out to the package repos and mirrors.
`gir` and a couple webkit related packages are the only remaining effected packages are are currently rebuilding.
At risk of jinxing it, I'd say we're through with the rebuilds for `libicu` and all updated packages should start filtering out to the package mirrors within a few hours depending on sync interval.

**Comment by awkiw** [comment]
ImportError: dlopen failed: library "libicui18n.so.74" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/site-packages/icu/_icu_.cpython-311.so in namespace (default)
The same problem with Slob.And how to cope this?

**Comment by Biswa96** [comment]
Update the package or rebuild the python wheel.

**Comment by awkiw** [comment]
This Termux doesn't let downgrade pyicu does.The last pyicu fails to install while 2.12 does easily from cache.Pyicu requires 74 exactly the problem is alive yet!
