### ISSUE TITLE
[Bug]:  bash failed to build

### ISSUE THREAD

**Issue by shadowprospero** [termux/termux-packages#19886]
### Problem description

The psmisc archive psmisc-23.6.tar.xz not found in the remote repository

Downloading https://fossies.org/linux/misc/psmisc-23.6.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 410
Failed to download https://fossies.org/linux/misc/psmisc-23.6.tar.xz

### What steps will reproduce the bug?

Run ./scripts/run-docker.sh
In docker run ./scripts/build-bootstraps.sh --architectures aarch64

### System information

termux-info:

```

```

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/8778333905

**Comment by shadowprospero** [comment]
It's fixed for me. Thank you @Biswa96 !
