### ISSUE TITLE
[Package]: openslide

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#19894]
### Why is it worth to add this package?

Open-source C library for slide

### Home page URL

https://openslide.org/

### Source code URL

https://github.com/openslide/openslide

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by TomJo2000** [comment]
We do not usually package standalone libraries without any package depending on them.

To quote from the packaging policy:
> [!NOTE]
> Important: standalone library packages are of interest mostly for developers and we will not package them unless required as dependency for another package. This is not a strong rule, but needed to ensure that repository is clean and provides content useful for average Termux user.
