### ISSUE TITLE
[Package]: ffmpegthumbnailer, libavcodec package request

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#19921]
### Why is it worth to add this package?

![Screenshot_2024-04-24_23-35-59](https://github.com/termux/termux-packages/assets/101167173/8e1b22f2-8d9b-44f7-9a91-0cc00c884192)

In Termux native XFCE4 desktop environment
For `mkv`, `wmv`, `avi` videos, thumbnails are not displayed.

I had the same symptom in the XFCE4 environment of `PRoot-Distro Debian Linux`.

`ffmpegthumbnailer`, `libavcodec*`
It was resolved after installing the above packages.

For a smooth multimedia environment and experience
I think it will be useful to many users if the `ffmpegthumbnailer` and `libavcodec*` packages are build into Termux.

### Source code URL

https://github.com/dirkvdb/ffmpegthumbnailer

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

https://github.com/dirkvdb/ffmpegthumbnailer
https://github.com/FFmpeg/FFmpeg/tree/master/libavcodec

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/8819631007

I have installed the package from CI artifact and it's working fine with thunar and xfce4. The following screenshot shows the generated thumbnails of sample media file in thunar.

![image](https://github.com/termux/termux-packages/assets/31443074/22acf291-b755-4546-a463-10facc35f3f2)

**Comment by hansm629** [comment]
@Biswa96 
It works very well!
Thank you for the quick builds as always!

![Screenshot_2024-04-25_01-20-00](https://github.com/termux/termux-packages/assets/101167173/3dd984f8-5e66-4af5-9bb1-010ac52fa97b)




@sylirre 
I think it was solved with just ffmpegthumbnailer.
Thank you for the additional comment.
