### ISSUE TITLE
[Package]: webp-pixbuf-loader package request

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#19932]
### Why is it worth to add this package?

![Screenshot_2024-04-26_00-36-23](https://github.com/termux/termux-packages/assets/101167173/f2a6a6e7-fdc6-429c-92cd-bdc331f4b594)
![Screenshot_2024-04-26_00-44-22](https://github.com/termux/termux-packages/assets/101167173/9f22927f-1d7a-47db-a94c-907e7ff1263e)

In Termux native XFCE4 environment
The `webp` image thumbnail is not displayed and it does not run through the `Ristretto image viewer`.

`PRoot-Distro Debian Linux `the same symptom occurs in the XFCE4 environment.
The symptom was resolved after installing the `webp-pixbuf-loader` package.

When `webp-pixbuf-loader` is ported to Termux
I think it will be very helpful in improving multimedia experience and usability.
:)

### Home page URL

https://github.com/aruiz/webp-pixbuf-loader

### Source code URL

https://github.com/aruiz/webp-pixbuf-loader

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by hansm629** [comment]
@Biswa96 
Could you please build the above package?
If only this package is ported, most of the multimedia aspects in Termux will be satisfied, except for the lack of hardware decoding!

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/8852177640

I have installed the package from CI artifact and it's working fine with thunar and xfce4. The following screenshot shows the generated thumbnails of sample image file in thunar.

![image](https://github.com/termux/termux-packages/assets/31443074/050e6632-17e6-49cf-b453-1bb243c0ed98)

**Comment by hansm629** [comment]
@Biswa96 
Works great!
thank you!

The Termux native XFCE4 desktop environment is becoming more complete! :)
