### ISSUE TITLE
[Package]: statsmodels

### ISSUE THREAD

**Issue by liuo2023** [termux/termux-packages#19960]
### Why is it worth to add this package?

Statsmodels are required for relevant statistical calculations and the use of Dtale

### Home page URL

https://github.com/statsmodels/statsmodels

### Source code URL

https://github.com/statsmodels/statsmodels

### Packaging policy acknowledgement

- [ ] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
Termux packaging policy violation: 
> **Not installable through cpan, gem, npm, or pip**
> 
> These packages should be installed through cpan, gem, npm, pip and so on.
> 
> Packaging modules for Perl, Ruby, Node.js, is problematic, especially when it comes to cross-compiling native extensions.

The package is installable with pip.

**Comment by Duuckjing** [comment]
> The package is installable with pip.

It seems to lack dependency from numpy?
I got this error log when installing statsmodels 
```
Building wheel for statsmodels (pyproject.toml) ... error        error: subprocess-exited-with-error                                                                                               × Building wheel for statsmodels (pyproject.toml) did not run successfully.                                                       │ exit code: 1                                                   ╰─> [18 lines of output]                                             running bdist_wheel                                              running build                                                    running build_py                                                 running build_ext                                                building 'statsmodels.tsa.stl._stl' extension                    aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_TRACE_NOGIL=0 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/core/include -I/data/data/com.termux/files/home/phantom/include -I/data/data/com.termux/files/usr/include/python3.11 -c statsmodels/tsa/stl/_stl.c -o build/temp.linux-aarch64-cpython-311/statsmodels/tsa/stl/_stl.o                                statsmodels/tsa/stl/_stl.c:21649:17: warning: using floating point absolute value function 'fabs' when argument is of integer type [-Wabsolute-value]                                               21649 |     __pyx_v_r = fabs(((__pyx_v_j + 1) - __pyx_v_xs));                                                                           |                 ^                                       statsmodels/tsa/stl/_stl.c:21649:17: note: use function 'labs' instead                                                             21649 |     __pyx_v_r = fabs(((__pyx_v_j + 1) - __pyx_v_xs));                                                                           |                 ^~~~                                           |                 labs                                    1 warning generated.                                             aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v1/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v1/sysroot/usr/lib -liconv build/temp.linux-aarch64-cpython-311/statsmodels/tsa/stl/_stl.o -L/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/core/include/../lib -L/data/data/com.termux/files/usr/lib -lnpymath -lpython3.11 -o build/lib.linux-aarch64-cpython-311/statsmodels/tsa/stl/_stl.cpython-311.so                                                     ld.lld: error: unable to find library -lnpymath                  aarch64-linux-android-clang: error: linker command failed with exit code 1 (use -v to see invocation)                             error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1                          [end of output]
```
Reference this: [Failed to install on android](https://github.com/statsmodels/statsmodels/issues/9236)

**Comment by twaik** [comment]
Seems like `statsmodels/tsa/stl/_stl.c` did not include `math.h` header.

**Comment by twaik** [comment]
Also yeah, you should install numpy.

**Comment by liuo2023** [comment]
This may not be the reason. I set some parameters and numpy can be installed through pip, but scipy cannot.
show error

../meson.build:138:12: ERROR: Command `/data/data/com.termux/files/usr/tmp/pip-build-env-25j4yhrz/overlay/bin/pythran --version` failed with status 1.

**Comment by Duuckjing** [comment]
> ../meson.build:138:12: ERROR: Command `/data/data/com.termux/files/usr/tmp/pip-build-env-25j4yhrz/overlay/bin/pythran --version` failed with status 1.

just use ```pkg install python-scipy``` to install scipy......
 While numpy 1.26.4 could be installed through pkg, numpy 2.0.0rc1 seems to encounter a typical error dlopen failed.
You can see the full error log here

```
(phantom) ~/phantom/statsmodels $ python                         Python 3.11.8 (main, Feb 11 2024, 13:05:24) [Clang 17.0.2 (https://android.googlesource.com/toolchain/llvm-project d9f89f4d1 on linux                                                              Type "help", "copyright", "credits" or "license" for more information.                                                            >>> import numpy as np                                           Traceback (most recent call last):                                 File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>          from . import multiarray                                       File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>        from . import overrides                                        File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>          from numpy._core._multiarray_umath import (                  ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...                                                                                                                            During handling of the above exception, another exception occurred:                                                                                                                                Traceback (most recent call last):                                 File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>               from numpy.__config__ import show as show_config               File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>               from numpy._core._multiarray_umath import (                    File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/__init__.py", line 49, in <module>          raise ImportError(msg)                                       ImportError:                                                                                                                      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!                                                                                                                                 Importing the numpy C-extensions failed. This error can happen for                                                                many reasons, often due to issues with your setup or how NumPy was                                                                installed.                                                                                                                        We have compiled some common reasons and troubleshooting tips at:                                                                     https://numpy.org/devdocs/user/troubleshooting-importerror.html                                                                                                                                Please note and check the following:                                                                                                * The Python version is: Python3.11 from "/data/data/com.termux/files/home/phantom/bin/python"                                    * The NumPy version is: "2.0.0rc1"                                                                                              and make sure that they are the versions you expect.             Please carefully study the documentation linked above for further help.                                                                                                                            Original error was: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...                                                                                                                                                                                      The above exception was the direct cause of the following exception:                                                                                                                               Traceback (most recent call last):                                 File "<stdin>", line 1, in <module>                              File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/__init__.py", line 119, in <module>               raise ImportError(msg) from e                                ImportError: Error importing numpy: you should not try to import numpy from                                                               its source directory; please exit the numpy source tree, and relaunch                                                             your python interpreter from there.
```

**Comment by liuo2023** [comment]
> > ../meson.build:138:12: ERROR: Command `/data/data/com.termux/files/usr/tmp/pip-build-env-25j4yhrz/overlay/bin/pythran --version` failed with status 1.
> 
> just use `pkg install python-scipy` to install scipy...... While numpy 1.26.4 could be installed through pkg, numpy 2.0.0rc1 seems to encounter a typical error dlopen failed. You can see the full error log here
> 
> ```
> (phantom) ~/phantom/statsmodels $ python                         Python 3.11.8 (main, Feb 11 2024, 13:05:24) [Clang 17.0.2 (https://android.googlesource.com/toolchain/llvm-project d9f89f4d1 on linux                                                              Type "help", "copyright", "credits" or "license" for more information.                                                            >>> import numpy as np                                           Traceback (most recent call last):                                 File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>          from . import multiarray                                       File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>        from . import overrides                                        File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>          from numpy._core._multiarray_umath import (                  ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...                                                                                                                            During handling of the above exception, another exception occurred:                                                                                                                                Traceback (most recent call last):                                 File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>               from numpy.__config__ import show as show_config               File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>               from numpy._core._multiarray_umath import (                    File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/__init__.py", line 49, in <module>          raise ImportError(msg)                                       ImportError:                                                                                                                      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!                                                                                                                                 Importing the numpy C-extensions failed. This error can happen for                                                                many reasons, often due to issues with your setup or how NumPy was                                                                installed.                                                                                                                        We have compiled some common reasons and troubleshooting tips at:                                                                     https://numpy.org/devdocs/user/troubleshooting-importerror.html                                                                                                                                Please note and check the following:                                                                                                * The Python version is: Python3.11 from "/data/data/com.termux/files/home/phantom/bin/python"                                    * The NumPy version is: "2.0.0rc1"                                                                                              and make sure that they are the versions you expect.             Please carefully study the documentation linked above for further help.                                                                                                                            Original error was: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...                                                                                                                                                                                      The above exception was the direct cause of the following exception:                                                                                                                               Traceback (most recent call last):                                 File "<stdin>", line 1, in <module>                              File "/data/data/com.termux/files/home/phantom/lib/python3.11/site-packages/numpy/__init__.py", line 119, in <module>               raise ImportError(msg) from e                                ImportError: Error importing numpy: you should not try to import numpy from                                                               its source directory; please exit the numpy source tree, and relaunch                                                             your python interpreter from there.
> ```

try     CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" pip3 install numpy==2.0.0rc1

**Comment by Duuckjing** [comment]
> try     CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" pip3 install numpy==2.0.0rc1     

Ah yes, numpy2.0.0rc1 can be installed through this, but now stuck on installing scipy... Since `pkg install python-scipy` will override numpy version

**Comment by Duuckjing** [comment]
> try `CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" pip3 install numpy==2.0.0rc1`

Ah yes, numpy2.0.0rc1 can be installed through this, but now stuck on installing scipy... Since `pkg install python-scipy` will override numpy version

**Comment by liuo2023** [comment]
you can install scipy first，then install numpy&nbsp;l override python-numpy version




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月28日(星期天) 上午10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [termux/termux-packages] [Package]: statsmodels (Issue #19960)














                                                                                                                                                                                            &gt; try     CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" pip3 install numpy==2.0.0rc1       
Ah yes, numpy2.0.0rc1 can be installed through this, but now stuck on installing scipy... Since pkg install python-scipy will override numpy version
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

**Comment by Duuckjing** [comment]
That's magic. Now that I have installed the dependencies, it still has some errors about 'cpow'
```
statsmodels/tsa/exponential_smoothing/_ets_smooth.c:3381:44: note: expanded from macro '__Pyx_c_pow_double'
       3381 |         #define __Pyx_c_pow_double(a, b)  (cpow(a, b))                                                                    |                                            ^
      statsmodels/tsa/exponential_smoothing/_ets_smooth.c:35442:316: note: include the header <complex.h> or explicitly provide a declaration for 'cpow'
      statsmodels/tsa/exponential_smoothing/_ets_smooth.c:3381:44: note: expanded from macro '__Pyx_c_pow_double'                  3381 |         #define __Pyx_c_pow_double(a, b)  (cpow(a, b))                                                                    |                                            ^
      2 errors generated.                                           error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
```

**Comment by Duuckjing** [comment]
> you can install scipy first，then install numpy&nbsp;l override python-numpy version

You are not using venv right? Inside an venv it's impossible to override the python-numpy package, so I deactivated it and then successfully installed numpy2.0.0rc1

**Comment by Duuckjing** [comment]
@twaik How did you installed statsmodels? I'm trying to do this because I want to finish my homework on it. After a few failed attempts, finally its been like this, though it is installed, the version is 0.0.0
```~/phantom/statsmodels $ CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" python -m pip install . --no-build-isolation                                                        Processing /data/data/com.termux/files/home/phantom/statsmodels        Preparing metadata (pyproject.toml) ... done                       Requirement already satisfied: numpy<3,>=1.22.3 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from statsmodels==0.0.0) (2.0.0rc1)                                                           Requirement already satisfied: scipy!=1.9.2,>=1.7.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from statsmodels==0.0.0) (1.13.0)                                                         Requirement already satisfied: pandas!=2.1.0,>=1.3.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from statsmodels==0.0.0) (2.2.2)                                                         Collecting patsy>=0.5.6 (from statsmodels==0.0.0)                      Using cached patsy-0.5.6-py2.py3-none-any.whl.metadata (3.5 kB)    Requirement already satisfied: packaging>=21.3 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from statsmodels==0.0.0) (24.0)                                                                Requirement already satisfied: python-dateutil>=2.8.2 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.3.0->statsmodels==0.0.0) (2.9.0.post0)                           Requirement already satisfied: pytz>=2020.1 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.3.0->statsmodels==0.0.0) (2024.1)                                          Requirement already satisfied: tzdata>=2022.7 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.3.0->statsmodels==0.0.0) (2024.1)                                        Requirement already satisfied: six in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from patsy>=0.5.6->statsmodels==0.0.0) (1.16.0)                                                            Using cached patsy-0.5.6-py2.py3-none-any.whl (233 kB)               Building wheels for collected packages: statsmodels                    Building wheel for statsmodels (pyproject.toml) ... |^done
  Created wheel for statsmodels: filename=statsmodels-0.0.0-cp311-cp311-linux_aarch64.whl size=19226310 sha256=79290983d9ad9acf7b6f0801e56724fd3c4bc0327c4d1c0b9552b632a6aa6b3f
  Stored in directory: /data/data/com.termux/files/usr/tmp/pip-ephem-wheel-cache-k0yvm_zt/wheels/01/7c/68/5a0a151f7e7b13e0814d2e1dcd0cf1f44c2674341f5b6bb24c
Successfully built statsmodels
Installing collected packages: patsy, statsmodels
Successfully installed patsy-0.5.6 statsmodels-0.0.0
~/phantom/statsmodels $ pip show statsmodels
Name: statsmodels
Version: 0.0.0
Summary: Statistical computations and models for Python
Home-page: https://www.statsmodels.org/
Author:
Author-email:
License: BSD License
Location: /data/data/com.termux/files/usr/lib/python3.11/site-packages
Requires: numpy, packaging, pandas, patsy, scipy
Required-by:```

**Comment by Duuckjing** [comment]
@twaik still worthwhile to add this package due to numpy dependency.
![Screenshot_2024-04-28-22-18-46-297_org.mozilla.firefox-edit.jpg](https://github.com/termux/termux-packages/assets/154486750/e7942063-3afd-407f-9242-e04f02f4304c)

**Comment by twaik** [comment]
Please avoid pinging maintainers.

**Comment by Duuckjing** [comment]
Sorry for that

**Comment by TomJo2000** [comment]
> still worthwhile to add this package due to numpy dependency.

We do not package Python modules except in rare circumstances.
If you still want a package of it, you might have more luck in the TUR, which has laxer packaging criteria.
https://github.com/termux-user-repository/tur

**Comment by Duuckjing** [comment]
After adding the _version.py, successfully installed statsmodels using `CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" python -m pip install . --no-build-isolation` in the [git clone statsmodels](https://github.com/statsmodels/statsmodels/) repository, and the _version.py was from windows. It is working now!
![Screenshot_2024-04-29-10-45-16-286_com.termux.jpg](https://github.com/termux/termux-packages/assets/154486750/5c247eac-51a7-4116-83b6-5a11af8f4c1d)

**Comment by liuo2023** [comment]
> After adding the _version.py, successfully installed statsmodels using `CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" python -m pip install . --no-build-isolation` in the [git clone statsmodels](https://github.com/statsmodels/statsmodels/) repository, and the _version.py was from windows. It is working now! ![Screenshot_2024-04-29-10-45-16-286_com.termux.jpg](https://private-user-images.githubusercontent.com/154486750/326319850-5c247eac-51a7-4116-83b6-5a11af8f4c1d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjA0MzIsIm5iZiI6MTcxNDM2MDEzMiwicGF0aCI6Ii8xNTQ0ODY3NTAvMzI2MzE5ODUwLTVjMjQ3ZWFjLTUxYTctNDExNi04M2I2LTVhMTFhZjhmNGMxZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwMzA4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTNiZjRlN2FjY2E2ZjNlMzM5NjVmNjY4NDZjMDBjODQ4NWFkZDY3ZTQ0ZWVmZTQxMDRiMTI3NWMzMzA4MDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JHCw7wrrDrs_zLplb1L0pcLKMcFzeT5hhJ4RwJ1U8mQ)


Maybe only use this method to compile and install.    
pip list show  
statsmodels                    0.0.0

but it work !!!

**Comment by HaHa131221** [comment]
> After adding the _version.py, successfully installed statsmodels using `CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" python -m pip install . --no-build-isolation` 

After the command is executed, an error is displayed:  Has it been solved?

```
WARNING: linker: Warning: "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so" unused DT entry: unknown processor-specific (type 0x70000005 arg 0x0) (ignoring)
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>
          from . import multiarray
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>
          from . import overrides
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>
          from numpy._core._multiarray_umath import (
      ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>
          from numpy.__config__ import show as show_config
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
          from numpy._core._multiarray_umath import (
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/__init__.py", line 49, in <module>
          raise ImportError(msg)
      ImportError:
      
      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
      
      Importing the numpy C-extensions failed. This error can happen for
      many reasons, often due to issues with your setup or how NumPy was
      installed.
```

**Comment by HaHa131221** [comment]
> After adding the _version.py, successfully installed statsmodels using `CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" python -m pip install . --no-build-isolation` in the [git clone statsmodels](https://github.com/statsmodels/statsmodels/) repository, and the _version.py was from windows. It is working now!
> ![Screenshot_2024-04-29-10-45-16-286_com.termux.jpg](https://github.com/termux/termux-packages/assets/154486750/5c247eac-51a7-4116-83b6-5a11af8f4c1d)
> 
>  

@Duuckjing Can you provide the specific installation process? Thanks!

**Comment by Duuckjing** [comment]
@HaHa131221 Have you installed numpy correctly? It is (discussed recently)[https://github.com/termux/termux-packages/discussions/19126]
If it fails, you can try to use the (`patchelf` command)[https://github.com/numpy/numpy/issues/24909].

**Comment by HaHa131221** [comment]
> @HaHa131221 Have you installed numpy correctly? It is [discussed recently](https://github.com/termux/termux-packages/discussions/19126)
> If it fails, you can try to use the [`patchelf` command](https://github.com/numpy/numpy/issues/24909).

Thanks for your reply! I reinstalled all dependencies, and then installed statmodels can be successful.🤗

**Comment by sheneeb** [comment]
> > After adding the _version.py, successfully installed statsmodels using `CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" python -m pip install . --no-build-isolation`
> 
> After the command is executed, an error is displayed: Has it been solved?
> 
> ```
> WARNING: linker: Warning: "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so" unused DT entry: unknown processor-specific (type 0x70000005 arg 0x0) (ignoring)
>       Traceback (most recent call last):
>         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>
>           from . import multiarray
>         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>
>           from . import overrides
>         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>
>           from numpy._core._multiarray_umath import (
>       ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...
>       
>       During handling of the above exception, another exception occurred:
>       
>       Traceback (most recent call last):
>         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>
>           from numpy.__config__ import show as show_config
>         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
>           from numpy._core._multiarray_umath import (
>         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/__init__.py", line 49, in <module>
>           raise ImportError(msg)
>       ImportError:
>       
>       IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
>       
>       Importing the numpy C-extensions failed. This error can happen for
>       many reasons, often due to issues with your setup or how NumPy was
>       installed.
> ```

How to add the 

> After adding the _version.py, successfully installed statsmodels using `CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" python -m pip install . --no-build-isolation` in the [git clone statsmodels](https://github.com/statsmodels/statsmodels/) repository, and the _version.py was from windows. It is working now! ![Screenshot_2024-04-29-10-45-16-286_com.termux.jpg](https://private-user-images.githubusercontent.com/154486750/326319850-5c247eac-51a7-4116-83b6-5a11af8f4c1d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzE2ODIsIm5iZiI6MTcxODEzMTM4MiwicGF0aCI6Ii8xNTQ0ODY3NTAvMzI2MzE5ODUwLTVjMjQ3ZWFjLTUxYTctNDExNi04M2I2LTVhMTFhZjhmNGMxZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxODQzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjAyNThkMGI1MTI5YjU5ZWQ3MTU4OTExMTc3ZDIzOGJjMDMwZmFhYzg2YTViZGYxZGQzY2Y4MzJiMDcxMTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AlxBhh3HBZEv630kVil-C4a0jk8g3seetPv_vF2jn1A)

How to get through version.py from windows 
I managed to Install.but now getting this error
>>> import statsmodels                                                        Traceback (most recent call last):                                              File "<stdin>", line 1, in <module>                                           File "/data/data/com.termux/files/home/statsmodels/statsmodels/__init__.py", line 3, in <module>                                                              from statsmodels._version import __version__, __version_tuple__           ModuleNotFoundError: No module named 'statsmodels._version'

**Comment by liuo2023** [comment]
> > > After adding the _version.py, successfully installed statsmodels using `CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" python -m pip install . --no-build-isolation`
> > 
> > 
> > After the command is executed, an error is displayed: Has it been solved?
> > ```
> > WARNING: linker: Warning: "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so" unused DT entry: unknown processor-specific (type 0x70000005 arg 0x0) (ignoring)
> >       Traceback (most recent call last):
> >         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>
> >           from . import multiarray
> >         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>
> >           from . import overrides
> >         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>
> >           from numpy._core._multiarray_umath import (
> >       ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...
> >       
> >       During handling of the above exception, another exception occurred:
> >       
> >       Traceback (most recent call last):
> >         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>
> >           from numpy.__config__ import show as show_config
> >         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
> >           from numpy._core._multiarray_umath import (
> >         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/__init__.py", line 49, in <module>
> >           raise ImportError(msg)
> >       ImportError:
> >       
> >       IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> >       
> >       Importing the numpy C-extensions failed. This error can happen for
> >       many reasons, often due to issues with your setup or how NumPy was
> >       installed.
> > ```
> 
> How to add the
> 
> > After adding the _version.py, successfully installed statsmodels using `CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" python -m pip install . --no-build-isolation` in the [git clone statsmodels](https://github.com/statsmodels/statsmodels/) repository, and the _version.py was from windows. It is working now! ![Screenshot_2024-04-29-10-45-16-286_com.termux.jpg](https://private-user-images.githubusercontent.com/154486750/326319850-5c247eac-51a7-4116-83b6-5a11af8f4c1d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzE2ODIsIm5iZiI6MTcxODEzMTM4MiwicGF0aCI6Ii8xNTQ0ODY3NTAvMzI2MzE5ODUwLTVjMjQ3ZWFjLTUxYTctNDExNi04M2I2LTVhMTFhZjhmNGMxZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxODQzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjAyNThkMGI1MTI5YjU5ZWQ3MTU4OTExMTc3ZDIzOGJjMDMwZmFhYzg2YTViZGYxZGQzY2Y4MzJiMDcxMTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AlxBhh3HBZEv630kVil-C4a0jk8g3seetPv_vF2jn1A)
> 
> How to get through version.py from windows I managed to Install.but now getting this error
> 
> > > > import statsmodels                                                        Traceback (most recent call last):                                              File "", line 1, in                                            File "/data/data/com.termux/files/home/statsmodels/statsmodels/**init**.py", line 3, in                                                               from statsmodels._version import **version**, **version_tuple**           ModuleNotFoundError: No module named 'statsmodels._version'
> 
> I got the version issue fixed, however unable to import statsmodels.api

CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m LDFLAGS="-lpython3.11" pip install numpy --force-reinstall
