### ISSUE TITLE
[Bug]: Lighttpd cannot disable HTTP/2.0

### ISSUE THREAD

**Issue by 123z45** [termux/termux-packages#19962]
### Problem description

server.feature-flags += ( "server.h2proto" => "diaable", "server.h2c" => "disable" )
It didn't work!
I tried to remove the mod_http2 module, but it didn't work, neither!
How to disable HTTP2?????

### What steps will reproduce the bug?

sudo lighttpd -f /sdcard/lighttpd/lighttpd.conf
Then curl -Ik https://127.0.0.1
Finally I got
```
HTTP/2 200
content-type: text/html;charset=UTF-8
accept-ranges: bytes
content-length: 6501
date: Sat, 27 Apr 2024 02:08:54 GMT
server: lighttpd/1.4.76
```

### What is the expected behavior?

HTTP/1.1 200
content-type: text/html;charset=UTF-8
accept-ranges: bytes
content-length: 6501
date: Sat, 27 Apr 2024 02:08:54 GMT
server: lighttpd/1.4.76

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=3641
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:
12
Kernel build information:
Linux localhost 4.14.141+ #1 SMP PREEMPT Thu Nov 30 17:24:16 CST 2023 aarch64 Android
Device manufacturer:
unknown
Device model:
Phh-Treble vanilla
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by tqfx** [comment]
typo 'diaable'.

**Comment by 123z45** [comment]
> typo 'diaable'.

Thank you. The configuration is now normal. However, it is recommended to follow the changes in lighttpd and change mod_h2 to a separate module, which will be introduced by default in the configuration file. Afterwards, simply comment out mod_h2 in modules.conf to disable HTTP 2.0.
