### ISSUE TITLE
[Question] How to mount USB storage in Termux

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#19965]
In Termux native XFCE4 desktop environment
I want to mount USB storage via USB OTG.

Even if you search on the Internet, there doesn't seem to be a clearly organized manual.

**1. Is it necessary to modify Termux permissions through ADB?**

**2. Is there anything I need to configure separately after installing `termux-api` and `termux-usb`?**

**3. What command or environment variable should I use to mount USB storage in the XFCE4 desktop environment?**

@sylirre 
Could you please help?

**Comment by twaik** [comment]
Mounting external drives to termux is possible only with root. ADB, termux-api or termux-usb will not help you with that.
