### ISSUE TITLE
[Bug]: Unable to locate package metasploit

### ISSUE THREAD

**Issue by Hero-brain** [termux/termux-packages#19983]
### Problem description

I am trying to get metasploit in termux but its not working 
![Screenshot_2024-04-28-06-32-59-125_com termux](https://github.com/termux/termux-packages/assets/168264892/0263f32f-f58b-4b8b-86bd-33d6605d56b2)

### What steps will reproduce the bug?

![Uploading Screenshot_2024-04-28-06-32-59-125_com.termux.jpg…]()

### What is the expected behavior?

We expecting behavior is 'the packages all are up to date'

### System information

termux-info:installed from f-droid

```

```

**Comment by Duuckjing** [comment]
Metasploit is not inside pkg, you can refer to this [Installing msfconsole](https://www.geeksforgeeks.org/how-to-install-metasploit-6-on-android-using-termux-no-root/)

**Comment by licy183** [comment]
metasploit is not packaged by Termux, and I'm afraid it will not be packaged in the future.

Please read: https://wiki.termux.com/wiki/hacking
