### ISSUE TITLE
[Package]: gedit and NEdit (nirvana text editor)

### ISSUE THREAD

**Issue by Coderx7** [termux/termux-packages#19985]
### Why is it worth to add this package?

NEdit(Nirvana text editor) is a great editor and it's especially great at loading huge files, it supports Unicode and lots of features and it's fast.
gedit is also a well-known text editor which is quite useful when you plan on using x11/ a desktop along with termux.
I checked and none of these text editors are available at the time of writing this request 

### Source code URL

https://sourceforge.net/projects/nedit/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

here's nedits project page : 
https://sourceforge.net/projects/nedit/

and here's gedit website: 
https://www.gedit.org/

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/9041647919

**Comment by Coderx7** [comment]
the last release came in 2021 version 5.7.3. 
NEdit is pretty fast and capable editor, not having it would be a shame imho. 
if for any reason we cant have nedit because its 3 years old, there's another fork called xnedit : https://github.com/unixwork/xnedit which is up to date (forked from 5.7) which can be used instead imho.
