### ISSUE TITLE
[Bug]: I donot install pip3 requirement.txt why 

### ISSUE THREAD

**Issue by bbek18** [termux/termux-packages#19993]
### Problem description

Python  3 error pip error no installation  canditate
![Screenshot_20240429-180450](https://github.com/termux/termux-packages/assets/141847705/711ca1f2-d1b7-43e5-8c66-3a6094b0a878)

### What steps will reproduce the bug?

।।।।।।

### What is the expected behavior?

।।।।

### System information

termux-info:

```

```
।।।

**Comment by landfillbaby** [comment]
`pkg install python-pip`
