### ISSUE TITLE
Could not find neither libtermcap.a, libncurses.a, or libcurses.

### ISSUE THREAD

**Issue by ZaxonXP** [termux/termux-packages#1999]
Hi,

Tried to install CPAN module using following command:

`cpan install Term::ReadLine::Gnu::XS`

and here is the error I am getting:

`Reading '/data/data/com.termux/files/home/.cpan/Metadata'
   Database was generated on Thu, 04 Jan 2018 08:29:03 GMT
 Running install for module 'Term::ReadLine::Gnu::XS'
 Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/H/HA/HAYASHI/Term-ReadLine-Gnu-1.35.tar.gz ok
 Configuring H/HA/HAYASHI/Term-ReadLine-Gnu-1.35.tar.gz with Makefile.PL
Could not find neither libtermcap.a, libncurses.a, or libcurses.
 Warning: No success on command[/data/data/com.termux/files/usr/bin/perl Makefile.PL]
   HAYASHI/Term-ReadLine-Gnu-1.35.tar.gz
   /data/data/com.termux/files/usr/bin/perl Makefile.PL -- NOT OK`

In which package I can find these missing libraries?

Regards,
Piotr

**Comment by its-pointless** [comment]
You won't we don't distribute static libs generally.

**Comment by ZaxonXP** [comment]
Does this mean that I need to recompile tchem from some source dev libraries? If yes, then which ones should I install?

**Comment by its-pointless** [comment]
You may need the headers from each library which is found in readline-dev ncurses-dev packages etc
