### ISSUE TITLE
termux-camera-photo not working.

### ISSUE THREAD

**Issue by thekindlyone** [termux/termux-packages#2]
On asus zenfone 2 .

    $ termux-camera-photo -h
    usage: /data/data/com.termux/files/usr/bin/termux-camera-photo [OPTIONS] <output-file>

    Take a photo and save it in a file. Valid options:
      -c, --camera <camera-id>    the id of the camera to use
    See the termux-camera-info for getting information about available cameras
    $ termux-camera-photo -c 0 pic.jpg
    Error type 3
    Error: Activity class {com.termux.extras/com.termux.extras.PhotoActivity} does not exist.
    $

**Comment by fornwall** [comment]
I forgot to update the termux-camera-photo script to use the correct internal parameters - if you do a `apt update && apt -y upgrade` you should get the fixed 0.6 version of the termux-api package. Thanks!
