### ISSUE TITLE
Package request: golang-doc

### ISSUE THREAD

**Issue by casept** [termux/termux-packages#2000]
The `godoc` tool currently doesn't work due to missing a documentation directory usually shipped with the go distribution.

Steps to reproduce:
```shell
go get -v golang.org/x/tools/cmd/godoc
godoc -http :8080
```
If you visit http://localhost:8080 in a webbrowser you get to see 
![image](https://user-images.githubusercontent.com/21053871/34568497-4ad4d2ea-f166-11e7-82d9-633286b9a167.png)
instead of the normal
![image](https://user-images.githubusercontent.com/21053871/34568529-60c449be-f166-11e7-8e3d-313489c05391.png)

Clicking the `Documents` link on the page results in an error.

I think it would be best to create a separate `golang-doc` package containing these assets so users who wish to use a working `godoc` can do so without wasting space for those who don't.

**Comment by Grimler91** [comment]
I changed this into a package request as that basically is what this is. Let me know if you disagree

**Comment by xqdoo00o** [comment]
the command `godoc` could use 2GB or more memory when add `-analysis` option.

**Comment by fornwall** [comment]
Thanks! A `golang-doc` subpackage can now be installed with `pkg in golang-doc`, after which `godoc -http :8080` looks as expected!
