### ISSUE TITLE
[Bug]: Undefined symbols error when building perl

### ISSUE THREAD

**Issue by gouravkhunger** [termux/termux-packages#20027]
### Problem description

Building the package `perl` produces the following error (This is on `arm`):

```
INFO: Found files with undefined symbols
INFO: Showing result
ERROR: ./lib/perl5/5.38.2/arm-android/auto/List/Util/Util.so contains undefined symbols:
    62: 00000000     0 NOTYPE  GLOBAL DEFAULT   UND floor
    63: 00000000     0 NOTYPE  GLOBAL DEFAULT   UND ceil
    96: 00000000     0 NOTYPE  GLOBAL DEFAULT   UND modf
ERROR: ./lib/perl5/5.38.2/arm-android/auto/re/re.so contains undefined symbols:
   179: 00000000     0 NOTYPE  GLOBAL DEFAULT   UND ceil
INFO: Done ... 9s
INFO: Found 2 files with undefined symbols after exclusion
ERROR: Refer above
Failed to build package 'perl' for arch 'arm'
[*] Building 'perl' exited with exit code 1
```

### What steps will reproduce the bug?

Run the bootstraps script using docker

```shell
./scripts/run-docker.sh ./clean.sh
./scripts/run-docker.sh ./scripts/build-bootstraps.sh
```

`PACKAGES` must include `perl`:

```shell
...
# Core utilities.
PACKAGES+=("perl")
...
```

### What is the expected behavior?

The package should build successfully. This issue might be in relation to `-no-undefined-version` being enabled by default in lld-17.

I tried passing `-Wl,--undefined-version` in the `LDFLAGS`

https://github.com/termux/termux-packages/blob/6ffa25fcbab87bd3ae2b1f2a7abbbb078a350a4e/packages/perl/build.sh#L57

```sh
CFLAGS=" -D__USE_BSD=1" LDFLAGS=" -Wl,--undefined-version -Wl,-rpath=$TERMUX_PREFIX/lib -L$TERMUX_PREFIX/lib -landroid-utimes" $TERMUX_PKG_SRCDIR/configure \ 
```

but the issue persists. Could someone please point me in the right direction so I can help contribute? Thanks!

### System information

N/A

**Comment by Grimler91** [comment]
Please try adding `-lm` to LDFLAGS (in the line you linked)

**Comment by gouravkhunger** [comment]
Thanks a lot @Grimler91, that did fix the issue! I've created a PR for the same.

**Comment by truboxl** [comment]
Only perl is affected?

**Comment by gouravkhunger** [comment]
@truboxl I was trying to [build `git`](https://github.com/jekyllex/ruby-android/actions/runs/8955804973) when I faced it. After the fix, it [built successfully](https://github.com/jekyllex/ruby-android/actions/runs/8958765467). Not sure if any other package has got similar bug.
