### ISSUE TITLE
[Package]: Csound

### ISSUE THREAD

**Issue by Maurus998** [termux/termux-packages#20023]
### Why is it worth to add this package?

It would be really cool to have this in Termux, it is an extremely powerful software for sound synthesis and instrument design. It doesn't need graphical interface, it is lightweight and doesn't have much dependencies.

### Home page URL

https://csound.com/

### Source code URL

https://github.com/csound/csound

### Packaging policy acknowledgement

- [ ] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment]
> Packages must be active, well-known projects

The repo you referenced was commited last time 2 years ago.
The project does not comply with packaging policy.

**Comment by TomJo2000** [comment]
Could still be packaged in the [TUR](https://github.com/termux-user-repository/tur/) probably.

**Comment by Maurus998** [comment]
> > Packages must be active, well-known projects
> 
> The repo you referenced was commited last time 2 years ago. The project does not comply with packaging policy.

Did you at least check the page I linked? They are going to have an international conference at VIENA in September 2024, It is not a dead project, lots of people use Csound in many areas.

Please reconsider your decision, I would really like to have this program in the repos, we don't have something like this in Termux.

**Comment by TomJo2000** [comment]
Has development been moved somewhere else then?
Because the latest commit on the GitHub repo is from 2 years ago.

**Comment by TomJo2000** [comment]
Well the latest commit is from 4 months ago...
Which is definitely not "dead".

**Comment by Maurus998** [comment]
> Has development been moved somewhere else then? Because the latest commit on the GitHub repo is from 2 years ago.

I don't know, honestly.

I'm going to follow your sugestion and request it on TUR, I didn't know TUR existed, thanks :D

**Comment by Maurus998** [comment]
> Well the latest commit is from 2 years ago...

So I should wait for a new update so I can post a package request again?

**Comment by TomJo2000** [comment]
> So I should wait for a new update so I can post a package request again?

It can definitely be packaged on the TUR, and TUR packages can and do move into the main repos.

**Comment by Maurus998** [comment]
> > So I should wait for a new update so I can post a package request again?
> 
> It can definitely be packaged on the TUR, and TUR packages can and do move into the main repos. If circumstances permit.

I posted a request in TUR.

Thank you very much!
