### ISSUE TITLE
[Enhancement]: applying speed limits to `termux_download`

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#20036]
Can we please make termux_download retry if speed falls to 0 for 30 seconds or longer? 
Sometimes connection stucks for 10 minutes or more so updater-script is simply waiting for new data.
According to `curl`'s man we should use `--speed-limit` and `--speed-time` options.
https://github.com/termux/termux-packages/blob/5cf7e74e6d88a8a029e9e06825c33c6b32cedd53/scripts/build/termux_download.sh#L21

**Comment by twaik** [comment]
To avoid this:
```
Downloading https://github.com/pypa/pip/archive/24.1b1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  160k    0  160k    0     0    266      0 --:--:--  0:10:13 --:--:--     0
curl: (56) OpenSSL SSL_read: Connection timed out, errno 110
Failed to download https://github.com/pypa/pip/archive/24.1b1.tar.gz
ERROR: failed to build.
```
It was waiting for 10 minutes only to say connection timed out.

**Comment by TomJo2000** [comment]
> To avoid this:
> 
> ```
> Downloading https://github.com/pypa/pip/archive/24.1b1.tar.gz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100  160k    0  160k    0     0    266      0 --:--:--  0:10:13 --:--:--     0
> curl: (56) OpenSSL SSL_read: Connection timed out, errno 110
> Failed to download https://github.com/pypa/pip/archive/24.1b1.tar.gz
> ERROR: failed to build.
> ```
> 
> It was waiting for 10 minutes only to say connection timed out.

Huh I was actually working on Pip right now, I found some other stuff I need to look into first, but I updated the regex for valid versions in #20050, could you please double check that I did that correctly if you have a minute?
