### ISSUE TITLE
[Python py project unable to build wheel]: 

### ISSUE THREAD

**Issue by LmTechyTEM** [termux/termux-packages#20039]
### Problem description

I've been having problems with installing python packages that are are py project toml based, regular packages work fine. Here's the error 
```
copying aiohttp/_helpers.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
      copying aiohttp/_http_parser.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
      copying aiohttp/_http_writer.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
      copying aiohttp/_websocket.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
      copying aiohttp/py.typed -> build/lib.linux-aarch64-cpython-311/aiohttp
      creating build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_cparser.pxd.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_find_header.pxd.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_helpers.pyi.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_helpers.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_http_parser.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_http_writer.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_websocket.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/hdrs.py.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      running build_ext
      building 'aiohttp._websocket' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/aiohttp
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.11 -c aiohttp/_websocket.c -o build/temp.linux-aarch64-cpython-311/aiohttp/_websocket.o
      aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib build/temp.linux-aarch64-cpython-311/aiohttp/_websocket.o -L/data/data/com.termux/files/usr/lib -lpython3.11 -o build/lib.linux-aarch64-cpython-311/aiohttp/_websocket.cpython-311.so
      aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build Pillow aiohttp
ERROR: Could not build wheels for Pillow, aiohttp, which is required to install pyproject.toml-based projects

 itsCyberToast  termux  ~ 
```

### What steps will reproduce the bug?

Install python 
Install any py project toml example: aiohttp, pillow 

### What is the expected behavior?

It's supposed to install normally but it does this.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=9174
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:
14
Kernel build information:
Linux localhost 4.19.191-27944104-abA146USQS6CXC2 #1 SMP PREEMPT Fri Mar 8 17:06:37 KST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A146U
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
com.termux.api versionCode:51
```

**Comment by Biswa96** [comment]
I can reproduce the same error with `pip install aiohttp` command. The clang 17.0.2 in NDK supports `-fopenmp-implicit-rpath` option but clang 18.1.5 in termux-packages does not support that.

**Comment by tqfx** [comment]
```
$ python -m sysconfig | grep fno-openmp-implicit-rpath
	BLDSHARED = "aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib"
	CONFIGURE_LDFLAGS = "-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib"
	CONFIG_ARGS = "'--disable-dependency-tracking' '--prefix=/data/data/com.termux/files/usr' '--libdir=/data/data/com.termux/files/usr/lib' '--sbindir=/data/data/com.termux/files/usr/bin' '--disable-rpath' '--disable-rpath-hack' '--host=aarch64-linux-android' 'ac_cv_file__dev_ptmx=yes' 'ac_cv_file__dev_ptc=no' 'ac_cv_func_wcsftime=no' 'ac_cv_func_ftime=no' 'ac_cv_func_faccessat=no' '--build=x86_64-pc-linux-gnu' '--with-system-ffi' '--with-system-expat' '--without-ensurepip' 'ac_cv_func_linkat=no' 'ac_cv_buggy_getaddrinfo=no' '--enable-loadable-sqlite-extensions' 'ac_cv_little_endian_double=yes' 'ac_cv_posix_semaphores_enabled=yes' 'ac_cv_func_sem_open=yes' 'ac_cv_func_sem_timedwait=yes' 'ac_cv_func_sem_getvalue=yes' 'ac_cv_func_sem_unlink=yes' 'ac_cv_func_shm_open=yes' 'ac_cv_func_shm_unlink=yes' '--with-build-python=python3.11' '--disable-nls' '--enable-shared' '--enable-static' '--libexecdir=/data/data/com.termux/files/usr/libexec' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=aarch64-linux-android' 'PKG_CONFIG=/home/builder/.termux-build/_cache/android-r26b-api-24-v3/bin/pkg-config' 'PKG_CONFIG_LIBDIR=/data/data/com.termux/files/usr/lib/pkgconfig:/data/data/com.termux/files/usr/share/pkgconfig' 'CC=aarch64-linux-android-clang' 'CFLAGS= -fstack-protector-strong -O3' 'LDFLAGS=-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib' 'CPPFLAGS= -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/include' 'CPP=aarch64-linux-android-cpp' 'LIBCRYPT_LIBS=-lcrypt'"
	LDFLAGS = "-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib"
	LDSHARED = "aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib"
	PY_CORE_LDFLAGS = "-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib"
	PY_LDFLAGS = "-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib"
	PY_LDFLAGS_NOLTO = "-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib"
```

**Comment by licy183** [comment]
This issue will be difficult to fix in the builder side until next NDK ships.

A possible way is modifying `$PREFIX/lib/python3.11/_sysconfigdata*.py` manually.

```bash
_file="$(find $TERMUX_PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
rm -rf $PREFIX/lib/python3.11/__pycache__
cp $_file "$_file".backup
sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
```

Related: https://github.com/termux/termux-packages/issues/19766

**Comment by davidtompul-tvlk** [comment]
> This issue will be difficult to fix in the builder side until next NDK ships.
> 
> A possible way is modifying `$PREFIX/lib/python3.11/_sysconfigdata*.py` manually.
> 
> ```bash
> _file="$(find $TERMUX_PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
> rm -rf $PREFIX/lib/python3.11/__pycache__
> cp $_file "$_file".backup
> sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
> ```
> 
> Related: https://github.com/termux/termux-packages/issues/19766
> 

 Hi i can not access the lib, any solution for this??

```
~ $ which python3
/data/data/com.termux/files/usr/bin/python3
~ $ _file="$(find $TERMUX_PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"find: ‘/data/data/com.termux/files/lib/python3.11’: No such file or directory
```

**Comment by Biswa96** [comment]
If you are in Android device or termux environment replace `TERMUX_PREFIX` with `PREFIX`.

`TERMUX_PREFIX` is used for build packages.

**Comment by davidtompul-tvlk** [comment]
> If you are in Android device or termux environment replace `TERMUX_PREFIX` with `PREFIX`.
> 
> `TERMUX_PREFIX` is used for build packages.

Yes, it works for me too. Thanks

**Comment by moodydeel900** [comment]
> ### Problem description
> 
> I've been having problems with installing python packages that are are py project toml based, regular packages work fine. Here's the error 
> ```
> copying aiohttp/_helpers.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
>       copying aiohttp/_http_parser.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
>       copying aiohttp/_http_writer.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
>       copying aiohttp/_websocket.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
>       copying aiohttp/py.typed -> build/lib.linux-aarch64-cpython-311/aiohttp
>       creating build/lib.linux-aarch64-cpython-311/aiohttp/.hash
>       copying aiohttp/.hash/_cparser.pxd.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
>       copying aiohttp/.hash/_find_header.pxd.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
>       copying aiohttp/.hash/_helpers.pyi.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
>       copying aiohttp/.hash/_helpers.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
>       copying aiohttp/.hash/_http_parser.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
>       copying aiohttp/.hash/_http_writer.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
>       copying aiohttp/.hash/_websocket.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
>       copying aiohttp/.hash/hdrs.py.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
>       running build_ext
>       building 'aiohttp._websocket' extension
>       creating build/temp.linux-aarch64-cpython-311
>       creating build/temp.linux-aarch64-cpython-311/aiohttp
>       aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.11 -c aiohttp/_websocket.c -o build/temp.linux-aarch64-cpython-311/aiohttp/_websocket.o
>       aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib build/temp.linux-aarch64-cpython-311/aiohttp/_websocket.o -L/data/data/com.termux/files/usr/lib -lpython3.11 -o build/lib.linux-aarch64-cpython-311/aiohttp/_websocket.cpython-311.so
>       aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
>       aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
>       error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for aiohttp
> Failed to build Pillow aiohttp
> ERROR: Could not build wheels for Pillow, aiohttp, which is required to install pyproject.toml-based projects
> 
>  itsCyberToast  termux  ~ 
> ```
> 
> ### What steps will reproduce the bug?
> 
> Install python 
> Install any py project toml example: aiohttp, pillow 
> 
> ### What is the expected behavior?
> 
> It's supposed to install normally but it does this.
> 
> ### System information
> 
> termux-info:
> 
> ```
> Termux Variables:
> TERMUX_API_VERSION=0.50.1
> TERMUX_APK_RELEASE=GITHUB
> TERMUX_APP_PACKAGE_MANAGER=apt
> TERMUX_APP_PID=9174
> TERMUX_IS_DEBUGGABLE_BUILD=1
> TERMUX_MAIN_PACKAGE_FORMAT=debian
> TERMUX_VERSION=0.118.0
> TERMUX__USER_ID=0
> Packages CPU architecture:
> aarch64
> Subscribed repositories:
> # sources.list
> deb https://packages.termux.org/apt/termux-main stable main
> # tur-repo (sources.list.d/tur.list)
> deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
> # x11-repo (sources.list.d/x11.list)
> deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
> Updatable packages:
> All packages up to date
> termux-tools version:
> 1.42.0
> Android version:
> 14
> Kernel build information:
> Linux localhost 4.19.191-27944104-abA146USQS6CXC2 #1 SMP PREEMPT Fri Mar 8 17:06:37 KST 2024 aarch64 Android
> Device manufacturer:
> samsung
> Device model:
> SM-A146U
> LD Variables:
> LD_LIBRARY_PATH=
> LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
> Installed termux plugins:
> com.termux.x11 versionCode:14
> com.termux.api versionCode:51
> ```
> 
https://www.facebook.com/profile.php?id=100005989952465&mibextid=ZbWKwL

**Comment by ECHO-64** [comment]
> This issue will be difficult to fix in the builder side until next NDK ships.
> 
> A possible way is modifying `$PREFIX/lib/python3.11/_sysconfigdata*.py` manually.
> 
> ```shell
> _file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
> rm -rf $PREFIX/lib/python3.11/__pycache__
> cp $_file "$_file".backup
> sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
> ```
> 
> Related: #19766
> 
> Edit: [1] Replace `TERMUX_PREFIX` with `PREFIX`.

it works for me too. thanks bro

**Comment by Duuckjing** [comment]
Thanks a lot, and it also works for clang++.

**Comment by okineadev** [comment]
> This issue will be difficult to fix in the builder side until next NDK ships.
> 
> A possible way is modifying `$PREFIX/lib/python3.11/_sysconfigdata*.py` manually.
> 
> ```bash
> _file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
> rm -rf $PREFIX/lib/python3.11/__pycache__
> cp $_file "$_file".backup
> sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
> ```
> 
> Related: https://github.com/termux/termux-packages/issues/19766
> 
> Edit:
> [1] Replace `TERMUX_PREFIX` with `PREFIX`.

I have been awake for several nights looking for a solution to this problem, now I have found it, thank you, now everything works!

**Comment by Khalid0909** [comment]
> This issue will be difficult to fix in the builder side until next NDK ships.
> 
> A possible way is modifying `$PREFIX/lib/python3.11/_sysconfigdata*.py` manually.
> 
> ```shell
> _file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
> rm -rf $PREFIX/lib/python3.11/__pycache__
> cp $_file "$_file".backup
> sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
> ```
> 
> Related: #19766
> 
> Edit: [1] Replace `TERMUX_PREFIX` with `PREFIX`.

THANK YOU

**Comment by uzi98f** [comment]
Hi new in termux, how I install manually that? can someone give step by step please

_file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
rm -rf $PREFIX/lib/python3.11/__pycache__
cp $_file "$_file".backup
sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"

**Comment by okineadev** [comment]
> Hi new in termux, how I install manually that? can someone give step by step please
> 
> _file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
> rm -rf $PREFIX/lib/python3.11/__pycache__
> cp $_file "$_file".backup
> sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
> 
> 

google.com

Please do not ask such questions here.

**Comment by uzi98f** [comment]
Please do not write if you will not help

**Comment by uzi98f** [comment]
> > Hi new in termux, how I install manually that? can someone give step by step please
> > _file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
> > rm -rf $PREFIX/lib/python3.11/**pycache**
> > cp $_file "$_file".backup
> > sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
> 
> https://google.com
> 
> Please do not ask such questions here.

Please do not write if you will not help

**Comment by SamLukeYes** [comment]
I found a simpler workaround for this issue:

1. install `clang-16` from `tur-repo`
2. set environment variable `CC=clang-16`

**Comment by Nekoplex** [comment]
> > Hi new in termux, how I install manually that? can someone give step by step please
> > _file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
> > rm -rf $PREFIX/lib/python3.11/**pycache**
> > cp $_file "$_file".backup
> > sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
> 
> https://google.com
> 
> Please do not ask such questions here.

github is public platform. You are not owner of It. You can't force us to do so

**Comment by Nekoplex** [comment]
> > Hi new in termux, how I install manually that? can someone give step by step please
> > _file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
> > rm -rf $PREFIX/lib/python3.11/**pycache**
> > cp $_file "$_file".backup
> > sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
> 
> https://google.com
> 
> Please do not ask such questions here.

I apologize for being off-topic, but I will answer this person.
If you don’t understand this and if you don’t have any problems like this, this doesn’t mean that you can afford to write something like that and just leave a link to Google.
Is Google the solution to all your problems?
This does not mean that Google will find a solution to all problems. It would be smarter to leave a link to the solution to the problem or not embarrass yourself and not write anything here at all!

**Comment by okineadev** [comment]
> > > Hi new in termux, how I install manually that? can someone give step by step please
> > > _file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
> > > rm -rf $PREFIX/lib/python3.11/**pycache**
> > > cp $_file "$_file".backup
> > > sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
> > 
> > 
> > [google.com](https://google.com)
> > Please do not ask such questions here.
> 
> I apologize for being off-topic, but I will answer this person. If you don’t understand this and if you don’t have any problems like this, this doesn’t mean that you can afford to write something like that and just leave a link to Google. Is Google the solution to all your problems? This does not mean that Google will find a solution to all problems. It would be smarter to leave a link to the solution to the problem or not embarrass yourself and not write anything here at all!

He didn't even say what to install

**Comment by okineadev** [comment]
> > > Hi new in termux, how I install manually that? can someone give step by step please
> > > _file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
> > > rm -rf $PREFIX/lib/python3.11/**pycache**
> > > cp $_file "$_file".backup
> > > sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
> > 
> > 
> > [google.com](https://google.com)
> > Please do not ask such questions here.
> 
> I apologize for being off-topic, but I will answer this person. If you don’t understand this and if you don’t have any problems like this, this doesn’t mean that you can afford to write something like that and just leave a link to Google. Is Google the solution to all your problems? This does not mean that Google will find a solution to all problems. It would be smarter to leave a link to the solution to the problem or not embarrass yourself and not write anything here at all!

He didn't even really explain anything, how do I know that he can't install it?
