### ISSUE TITLE
[Package]: dotload

### ISSUE THREAD

**Issue by okineadev** [termux/termux-packages#20048]
### Why is it worth to add this package?

I am actively developing this project and adding new download methods, currently the following methods are available: with **apt (PPA)**, with **install.sh** and **from sources** (see "[**Installation**](https://github.com/okineadev/dotload#%EF%B8%8F-installation)"), the tool works completely in **Termux**

And now I plan to add it to the **Termux** repo so that it can be easily installed with the `pkg install dotload` command

I want my package to be automatically updated, the package source archives are attached to releases (see https://github.com/okineadev/dotload/releases/latest)

![image](https://github.com/termux/termux-packages/assets/81070564/bf7d4af4-0e1e-46b1-aaa1-8f5a628f8bf7)

### Home page URL

https://github.com/okineadev/dotload

### Source code URL

https://github.com/okineadev/dotload

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

Package dependencies:
- git

**Comment by TomJo2000** [comment]
Being written mostly in shell script, this package does not meet the requirements set out in our packaging policy, as it should be able to run just fine without specifically needing to be packaged.

If you would still like to get it packaged for Termux you should be able to get packaged in the [TUR](https://github.com/termux-user-repository/tur).

**Comment by okineadev** [comment]
OK, I'll try
