### ISSUE TITLE
[Bug]: Unable to run "pm" command on latest KSU

### ISSUE THREAD

**Issue by privacyguy123** [termux/termux-packages#20049]
### Problem description

Getting "Failure calling service package" error, I have seen the post about it. I wonder is it possible to have these 2 things coexist without the SELinux patch on said post?

Here is the relevant commit:
https://github.com/tiann/KernelSU/commit/935dc18faace4dfdda79d3f00bf1ed2632a94628

### What steps will reproduce the bug?

Install latest KSU CI build and try to run ```pm``` command.

### What is the expected behavior?

It should/could work?

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB                                         TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21860
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:                                                  13
Kernel build information:
Linux localhost 4.19.113-27223811 #52 SMP PREEMPT Tue May 7 18:47:53 BST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G781B
LD Variables:                                                     LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by 2096779623** [comment]
You can replace `pm` with `pm </dev/null 2>&1 | cat` .

https://github.com/termux/termux-packages/discussions/8292
