### ISSUE TITLE
[Bug]: "mesa-vulkan-icd-freedreno-dri3 patch" patch error in mesa-main.

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#20056]
### Problem description

Supports `Adreno 750`
`mesa-main`(https://gitlab.freedesktop.org/mesa/mesa)
`a750-hw-binning-ban-gs`(https://gitlab.freedesktop.org/Danil/mesa/-/tree/turnip/fix/a750-hw-binning-ban-gs)

From the two branches above

`wsi-termux-x11.patch`
`tu_kgsl_export_dmabuf.patch`

The patch fails with an error.

Could you please provide a patch that works on `mesa-main` and `a750-hw-binning-ban-gs`?

### What steps will reproduce the bug?

`wsi-termux-x11.patch`
```
Checking patch src/vulkan/wsi/wsi_common.c...
error: while searching for:
      assert(!has_signal_dma_buf);
#endif

      if (wsi->sw)
	      wsi->WaitForFences(device, 1, &swapchain->fences[image_index],
				 true, ~0ull);


error: patch failed: src/vulkan/wsi/wsi_common.c:1466
error: src/vulkan/wsi/wsi_common.c: patch does not apply
Checking patch src/vulkan/wsi/wsi_common_drm.c...
Hunk #1 succeeded at 45 (offset 2 lines).
Hunk #2 succeeded at 71 (offset 2 lines).
Hunk #3 succeeded at 101 (offset 2 lines).
Checking patch src/vulkan/wsi/wsi_common_x11.c...
Hunk #1 succeeded at 447 (offset 8 lines).
error: while searching for:
   for (uint32_t i = 0; i < chain->base.image_count; i++) {
      if (!chain->images[i].busy) {
         /* We found a non-busy image */
         xshmfence_await(chain->images[i].shm_fence);
         *image_index = i;
         chain->images[i].busy = true;
         chain->present_poll_acquire_count++;

error: patch failed: src/vulkan/wsi/wsi_common_x11.c:1417
error: src/vulkan/wsi/wsi_common_x11.c: patch does not apply

``` 

`tu_kgsl_export_dmabuf.patch`
```
Checking patch src/freedreno/vulkan/tu_device.cc...
Hunk #1 succeeded at 2790 (offset 166 lines).
Checking patch src/freedreno/vulkan/tu_knl.h...
error: while searching for:
   TU_BO_ALLOC_ALLOW_DUMP = 1 << 0,
   TU_BO_ALLOC_GPU_READ_ONLY = 1 << 1,
   TU_BO_ALLOC_REPLAYABLE = 1 << 2,
};

/* Define tu_timeline_sync type based on drm syncobj for a point type

error: patch failed: src/freedreno/vulkan/tu_knl.h:21
error: src/freedreno/vulkan/tu_knl.h: patch does not apply
Checking patch src/freedreno/vulkan/tu_knl_kgsl.cc...
Hunk #3 succeeded at 70 (offset 1 line).
Hunk #4 succeeded at 132 (offset 1 line).
Hunk #5 succeeded at 182 (offset 1 line).
Hunk #6 succeeded at 238 (offset 7 lines).
Hunk #7 succeeded at 249 (offset 7 lines).
error: while searching for:
   if (bo->map)
      return VK_SUCCESS;

   uint64_t offset = bo->gem_handle << 12;
   void *map = mmap(0, bo->size, PROT_READ | PROT_WRITE, MAP_SHARED,
                    dev->physical_device->local_fd, offset);

error: patch failed: src/freedreno/vulkan/tu_knl_kgsl.cc:183
error: src/freedreno/vulkan/tu_knl_kgsl.cc: patch does not apply
``` 

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5853
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.1
Android version:
14
Kernel build information:
Linux localhost 6.1.43-android14-11-abS926NKSU1AXCA #1 SMP PREEMPT Sun Mar 17 10:24:49 UTC 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S928N
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.x11 versionCode:14
com.termux.api versionCode:51

```

**Comment by twaik** [comment]
Patches in `termux-packages` supposed to work with packages available in `termux-packages`. It is not guaranteed to work on random 3rd party repositories you find all over the Internet. 
If you need these patches to work with 3rd party repos you can rebase them on your own.

**Comment by twaik** [comment]
And no, these patches are not universal and should not work on all versions/commits of project repo (even master branch) even if we are packaging it. We rebase patches on demand.

**Comment by chaitan3** [comment]
Latest mesa main branch has support for https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/28928

This allows 32-bit x86 vulkan apps to work with hangover-wine. Would it possible to create a mesa-git package for termux that has an up to date mesa? Maybe it should be in the termux user repository?

**Comment by twaik** [comment]
> Latest mesa main branch has support for

Has support for what exactly and how is it related `mesa-vulkan-icd-freedreno-dri3` patch?

**Comment by chaitan3** [comment]
From the MR description on mesa gitlab:
VK_EXT_map_memory_placed is required by [winevulkan WoW64](https://gitlab.winehq.org/wine/wine/-/commit/1999e4f3f51c805a96e93fdf62bec0b200912229) for mapping all Vulkan allocations in the 32-bit address space. This MR implements the extension for all Turnip KMDs but it has only been tested on msm.

It could allow turnip driver (which you get by installing mesa-vulkan-icd-freedreno-dri3 package) to run 32-bit vulkan or directx (via dxvk) games in termux via wine.
