### ISSUE TITLE
[Enhancement]: making `libsqlite-tcl` a subpackage of `libsqlite`

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#20058]
Hello. 
I think it is possible to make `libsqlite-tcl` a subpackage of `libsqlite`, in this case we will be able to allow it automatic updates.
I think we can make in the way similar to 50fd60f7a76e4c0a3115e35d3b5f00f64a9e6c4f . So the source will be built in `post_make_install` step. 
Nobody minds?

**Comment by RABITillum159** [comment]
Yeah but we can ..!

**Comment by TomJo2000** [comment]
I don't see why not.
