### ISSUE TITLE
[Bug]: firefox spits out an error "XPCOMGlueLoad error for file /data/data/com.termux/files/usr/lib/firefox/libxul.so:"

### ISSUE THREAD

**Issue by yeetssite** [termux/termux-packages#20066]
### Problem description
*Edit: I forgot to mention that this error prevents firefox from opening at all  
The error reads like this:

    XPCOMGlueLoad error for file /data/data/com.termux/files/usr/lib/firefox/libxul.so:
    dlopen failed: library "libicui18n.so.75" not found: needed by /data/data/com.termux/files/usr/lib/firefox/libxul.so in namespace (default)
    Couldn't load XPCOM.

I've tried researching this problem and it seems to be an error with the package of some sort.

### What steps will reproduce the bug?

Well, I don't know if my device or install is bugging, but simply installing firefox and running it in xfce4 does nothing. Trying to open firefox using the terminal gives me the error mentioned in the description:

    XPCOMGlueLoad error for file /data/data/com.termux/files/usr/lib/firefox/libxul.so:
    dlopen failed: library "libicui18n.so.75" not found: needed by /data/data/com.termux/files/usr/lib/firefox/libxul.so in namespace (default)
    Couldn't load XPCOM.

I use Termux:x11 with a xfce4 desktop on an arm64/aarch64 device

### What is the expected behavior?

Firefox opens with no issue (or, firefox opens at all)

### System information

termux-info:

```
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=26438
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.nguyenhoang.cloud/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:
14
Kernel build information:
Linux localhost 4.14.199-28028797-abX200XXS3DXD5 #2 SMP PREEMPT Mon Apr 15 14:41:44 +07 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-X200
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:14
com.termux.styling versionCode:32
```

**Comment by licy183** [comment]
Please use `termux-change-repo`, select the default mirror (`packages-cf.termux.dev`) and run `pkg upgrade`.

The mirror you selected has outdated libicu.
