### ISSUE TITLE
[Bug]: Building package `glib` fails

### ISSUE THREAD

**Issue by gouravkhunger** [termux/termux-packages#20070]
### Problem description

The build for package `glib` [fails](https://github.com/jekyllex/ruby-android/actions/runs/9013101741) with the error:

```
...
Installing /home/builder/.termux-build/glib/src/m4macros/gsettings.m4 to /data/data/com.termux/files/usr/opt/glib/cross/share/aclocal
Applying patch: gio-gdbusprivate.c.patch
Applying patch: gio-gkeyfilesettingsbackend.c.patch
Applying patch: gio-gnetworking.h.in.patch
Applying patch: gio-gunixmounts.c.patch
Applying patch: gio-xdgmime-xdgmime.c.patch
Applying patch: glib-gcharset.c.patch
Applying patch: glib-gspawn.c.patch
Applying patch: glib-gthread-posix.c.patch
Applying patch: glib-gthreadprivate.h.patch
Applying patch: glib-gtimezone.patch
Applying patch: glib-gtypes.h.patch
Applying patch: glib-gutils.c.patch
Applying patch: glib-tests-meson.build.patch
Applying patch: meson.build.patch
sed: can't read /data/data/com.termux/files/usr/lib/pkgconfig/gobject-introspection-1.0.pc: No such file or directory
Error: Process completed with exit code 2.
```

This seems to be introduced since 4ccbae1cec294cdf0c2dff25fc3a0227d493f456 in line:

https://github.com/termux/termux-packages/blob/4ccbae1cec294cdf0c2dff25fc3a0227d493f456/packages/glib/build.sh#L73-L74

On inspection, I found that the build system didn't download `gobject-introspection` for building even if it is defined in the `TERMUX_PKG_BUILD_DEPENDS` for `glib`:

https://github.com/termux/termux-packages/blob/bb4bdf2294cc22c4eb88ae1913421b8901def97d/packages/glib/build.sh#L10

Thus the file is missing.

### What steps will reproduce the bug?

Build the package `glib` on `master` with command:

```
./scripts/run-docker.sh ./clean.sh
./scripts/run-docker.sh ./build-package.sh glib
```

Because `gobject-introspection` was not downloaded, I tried building it right before `glib`. But that resulted in an [infinite pause](https://github.com/jekyllex/ruby-android/actions/runs/8969546157):

```
./scripts/run-docker.sh ./build-package.sh gobject-introspection glib
```

But well, `gobject-introspection` depends on `glib` so maybe that caused the loop:

https://github.com/termux/termux-packages/blob/e6edae346502fb933dd3940ee78345afb6a2147e/packages/gobject-introspection/build.sh#L8

### What is the expected behavior?

I am unable to replicate the successful builds as in [termux workflow builds](https://github.com/termux/termux-packages/actions/runs/9010395870).

### System information

N/A

**Comment by Biswa96** [comment]
You have to follow some steps to bootstrap glib and gojbect-introspection (GI). See https://gitlab.gnome.org/GNOME/glib/-/blob/2.80.0/docs/reference/glib/building.md?ref_type=tags

1. Build glib using `-Dintrospection=disabled` option.
2. Build GI using glib from step1.
3. Build glib with `-Dintrospection=enabled` using GI from step2.

I can try to add a bootstrap flag in glib or GI build script but I do not know how to check if glib is being bootstrapped. Otherwise, user has to pass the bootstrap flag manually.

**Comment by Biswa96** [comment]
I have no idea what `TERMUX_FORCE_BUILD_DEPENDENCIES` does and even if that works.

**Comment by Biswa96** [comment]
I am not sure if `TERMUX_FORCE_BUILD_DEPENDENCIES` variable should be used. It is not documented and not used in any other build script. That variable is true when `-F` option is passed to build-package.sh. I would follow simple steps from Alpine Linux to replace the cyclic dependency https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/glib/APKBUILD (if feasible).

**Comment by robertkirkman** [comment]
> You have to follow some steps to bootstrap glib and gojbect-introspection (GI). See https://gitlab.gnome.org/GNOME/glib/-/blob/2.80.0/docs/reference/glib/building.md?ref_type=tags
> 
>     1. Build glib using `-Dintrospection=disabled` option.
> 
>     2. Build GI using glib from step1.
> 
>     3. Build glib with `-Dintrospection=enabled` using GI from step2.
> 
> 
> I can try to add a bootstrap flag in glib or GI build script but I do not know how to check if glib is being bootstrapped. Otherwise, user has to pass the bootstrap flag manually.

Before I saw this issue I independently created my own automated workaround that I now see is different from the open PR. My workaround is specifically intended for the **use case of those adding a package to the list in `scripts/build-bootstraps.sh`  that depends on `glib` or `gobject-introspection`**  and is not tested from other entry points, and it might be very messy in its current form, but I will post it so that others can see if they are looking for options.

```diff

--- a/packages/glib/build.sh
+++ b/packages/glib/build.sh
@@ -12,7 +12,6 @@ TERMUX_PKG_BREAKS="glib-dev"
 TERMUX_PKG_REPLACES="glib-dev"
 TERMUX_PKG_DISABLE_GIR=false
 TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
--Dintrospection=enabled
 -Druntime_dir=$TERMUX_PREFIX/var/run
 -Dlibmount=disabled
 -Dman-pages=enabled
@@ -69,8 +68,12 @@ termux_step_pre_configure() {
 
 	TERMUX_PKG_VERSION=. termux_setup_gir
 
-	# Workaround: Remove cyclic dependency between gir and glib
-	sed -i "/Requires:/d" "${TERMUX_PREFIX}/lib/pkgconfig/gobject-introspection-1.0.pc"
+	# Workaround: cyclic dependency between gir and glib
+	if [ -f "${TERMUX_PREFIX}/lib/pkgconfig/gobject-introspection-1.0.pc" ]; then
+		sed -i "/Requires:/d" "${TERMUX_PREFIX}/lib/pkgconfig/gobject-introspection-1.0.pc"
+	else
+		TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" -Dintrospection=disabled"
+	fi
 }
 
 termux_step_post_make_install() {
--- a/scripts/build/termux_step_get_dependencies.sh
+++ b/scripts/build/termux_step_get_dependencies.sh
@@ -19,6 +19,27 @@ termux_step_get_dependencies() {
 			fi
 		fi
 
+		# glib <-> gobject-introspection cyclic dependency that the above condition ^ as-is isn't fixing
+		# fix in termux_step_pre_configure() of packages/glib/build.sh will
+		# make sure that first glib is built with -Dintrospection=disabled, then gobject-introspection is built,
+		# then glib is built again and this time the installed gobject-introspection will be detected and 
+		# glib will be recompiled and reinstalled with introspection support enabled.
+		# POTENTIAL FAILURE CASE: when "glib" itself is passed as an argument to build_package() in build-bootstraps.sh
+		# first in the list before any other package that depends on glib - that might not be handled and result in a glib
+		# without introspection support that could cause a build failure later.
+		GLIB_PKG="glib"
+		GIR_PKG="gobject-introspection"
+		if [ "$PKG" = "$GLIB_PKG" ] && [ ! -f "$TERMUX_BUILT_PACKAGES_DIRECTORY/$GLIB_PKG-$GIR_PKG-cycle-begun" ]; then
+			touch "$TERMUX_BUILT_PACKAGES_DIRECTORY/$GLIB_PKG-$GIR_PKG-cycle-begun"
+			termux_run_build-package # first glib compilation
+			PKG_DIR="$GIR_PKG"
+			termux_run_build-package # gobject-introspection compilation
+			# remove conflicting files to allow outer build of gobject-introspection to also complete
+			rm -r "$TERMUX_TOPDIR/$GIR_PKG/massage/"*
+			rm "$TERMUX_BUILT_PACKAGES_DIRECTORY/$GLIB_PKG" # remove build marker
+			PKG_DIR="$GLIB_PKG" # second glib compilation happens below
+		fi
+
 		if [ "$TERMUX_INSTALL_DEPS" = true ] || [ "$cyclic_dependence" = true ]; then
 			if [ -z $PKG ]; then
 				continue
```
