### ISSUE TITLE
Package request: gitter-cli or gitterCLI

### ISSUE THREAD

**Issue by Symbian9** [termux/termux-packages#2007]
- https://github.com/RodrigoEspinosa/gitter-cli

or

- https://github.com/meetmangukiya/gitterCLI

or any better Gitter client with CLI.

**Comment by xeffyr** [comment]
`npm install -g gitter-cli` is not working ?

**Comment by fornwall** [comment]
As https://github.com/RodrigoEspinosa/gitter-cli lists installation through npm as the first installation instruction (and likewise with `go get` for https://github.com/meetmangukiya/gitterCLI), I think we can avoid packaging these ourselves.
