### ISSUE TITLE
It works, but there are things that do not work in this root, such as pkg. When I type pkg install... it says it does not exist. I tried it a lot, but there is no solution.

### ISSUE THREAD

**Issue by kali-tor** [termux/termux-packages#20075]
that repo works!!!
that help me fixed error above

Update termux: apt-get update && apt-get upgrade -y
Install wget: apt-get install wget -y
Install proot: apt-get install proot -y
Install git: apt-get install git -y
Go to HOME folder: cd ~
Download script: git clone https://github.com/MFDGaming/ubuntu-in-termux.git
Go to script folder: cd ubuntu-in-termux
Give execution permission: chmod +x ubuntu.sh
Run the script: ./ubuntu.sh -y
Now just start ubuntu: ./startubuntu.sh

_Originally posted by @Antracot in https://github.com/termux/termux-app/issues/381#issuecomment-629725043_
        
![Screenshot_20240509-213427_Termux](https://user-images.githubusercontent.com/167249316/329350840-7f34f249-1075-4a67-b97d-0e9783d1e26f.jpg)
    It works, but there are things that do not work in this root, such as pkg. When I type pkg install... it says it does not exist. I tried it a lot, but there is no solution.

**Comment by twaik** [comment]
1. This is termux space. We are not responsible for every single 3rd party solution built on top of termux you find in Internet.
2. There is proot-distro which allows you to use ubuntu without root on your device.
