### ISSUE TITLE
#201 Update pkg: apt v1.2.9 throws weak crypto warning

### ISSUE THREAD

**Issue by tinydynamite00** [termux/termux-packages#201]
@fornwall 
#201
*Update to latest apt package throws a weak hash warning.
- - - - - - - - - - - - - — - - - — - - - - - - — - - - - - - - - - - - --- -- - - 
*Termux' output*:
     Sun Apr 03-21:46:52 u0_a80@localhost ~$apt update
     Hit:1 http://termux.net stable InRelease
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     All packages are up to date.
     __W: http://termux.net/dists/stable/InRelease: Signature by key              2218893D3F679BEFC421FD976700B77E6D8D0AE7 uses    weak digest algorithm (SHA1)__

     Sun Apr 03-22:11:34 u0_a80@localhost ~$apt --version
     apt 1.2.9 (arm)
_ _ _ _ _ _ ___ _ _ _ _ __ _  _ __ _ _ _ _ __ _ _ __ __ _ _ _
- *Expected behaviour*: Run 'apt update' + all pkg handlers/installers without weak crypto warning to STDOUT. 

Users need a more reliable method of retrieving/updating main source.list key(s) from keyserver. Ability to confirm whether maintainer's key is up to date, disabled, revoked via 'apt-key --net-update' *_also_* for importing into local gpg keyring/trust.db.

**Comment by fornwall** [comment]
Thanks, the repo has now been updated to use SHA-256!

Will look into adding the key to a keyserver soon!

**Comment by tinydynamite00** [comment]
Thank you! Apt started behaving not long after issuing the report, which I near forgot. I just now saw the Github email notification or I would have been by earlier to thank you. (=
