### ISSUE TITLE
[Package]: convmv

### ISSUE THREAD

**Issue by ah-dagdelen** [termux/termux-packages#20101]
### Why is it worth to add this package?

This is a filename encoding conversion tool. It can convert a filename to a different encoding.

### Home page URL

https://www.j3e.de/linux/convmv/man/

### Source code URL

https://packages.debian.org/source/sid/convmv

### Packaging policy acknowledgement

- [ ] The project is actively developed.
- [x] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
I fail to see how this package is applicable to Android/Termux, seeing as there is no filesystem in userspace support on Android.

**Comment by ah-dagdelen** [comment]
I encountered this sort of problem when I tried to unzip a folder with its contents which was created and zipped under Microsoft Windows 10. Folder and file names were screwed up under Termux.

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last commit was 7 years ago (2018-03-26 22:37) so I consider this project is dead/frozen. Also convmv is a perl script so it does not require compilation and can be used as is.
