### ISSUE TITLE
[Package]: Origami Kernel Manager

### ISSUE THREAD

**Issue by Rem01Gaming** [termux/termux-packages#20119]
### Why is it worth to add this package?

set of utilities for power users to tune, adjust, and manage the kernel parameters through the command line interface (CLI), specifically on termux. It aims to deliver a comprehensive solution for enhancing device performance and customization by providing various settings for kernel fine-tuning.

### Source code URL

https://github.com/Rem01Gaming/origami_kernel_manager

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [ ] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

This package need a root permission and some features may be not available on some combination of device/kernel.

**Comment by TomJo2000** [comment]
Would that even work on Android?
Even assuming root access, you can't just plop in a generic desktop Linux Kernel.

**Comment by TomJo2000** [comment]
After looking at the source repo I'm even more confused.
This is written for Termux, in ***Bash*** and I'm unable to discern how or what exactly it's even meant to do.

Regardless of that, there are two more immediate issues.
- 1.) It's written in Bash, it doesn't need packaging to work.
- 2.) We don't package personal "pet projects" in the main repository.

I'd suggest trying [the TUR](https://github.com/termux-user-repository/tur), but honestly this is the most baffling package requests I've ever seen, and I don't foresee you getting a different answer there.

**Comment by Rem01Gaming** [comment]
It's designed specifically for Android devices, even can't work with other Linux based OS.
Have same functionality like other Kernel Like [Franco Kernel Manager](https://play.google.com/store/apps/details?id=com.franco.kernel) and [Smartpack kernel](https://github.com/SmartPack/SmartPack-Kernel-Manager/releases)

**Comment by TomJo2000** [comment]
What exactly is a "Kernel Manager", for any of us not familiar with XDA forum slang?
Because those look like system monitoring apps to me.

**Comment by Rem01Gaming** [comment]
> What exactly is a "Kernel Manager", for any of us not familiar with XDA forum slang?

A "Kernel Manager" is a utility designed to give users control over various aspects of their device's kernel configuration. These aspects can include CPU and GPU frequencies and [governors](https://wiki.archlinux.org/title/CPU_frequency_scaling#Scaling_governors), networking and memory parameters, and I/O schedulers among others.

It provides users with an approachable interface to manage and optimize common kernel parameters. These features can help augment user experience significantly by allowing customization at such a granular level.

With kernel manager, you can do several things like Optimize battery life by lowering Maximum frequencies of CPU and GPU or set governor to powersave, Max out performance by locking frequencies to highest, optimize network latency for games and more.

Kernel Manager is also equipped with some utility for changing SOC and OEM (including kernel patches from developers) specific features/components like vibration strength, display color calibration, changing performance limitations, [Adreno idler](https://xdaforums.com/t/adreno-idler-an-idling-algorithm-for-devfreq-based-adreno-devices.3134872/) and so on.

> Because those look like system monitoring apps to me.

Well the main idea of a Kernel Manager is changing kernel parameters, monitoring is not really needed but nice to have feature.
