### ISSUE TITLE
[Package]: qemu

### ISSUE THREAD

**Issue by psiphon-pro19** [termux/termux-packages#20110]
### Why is it worth to add this package?

request package qemu in android 5 or 6

### Home page URL

https://qemu.org

### Source code URL

https://download.qemu.org/qemu-8.0.2.tar.xz

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

qemu

**Comment by twaik** [comment]
Android 5 and 6 repos are unmaintained. They are kept for history but we do not port packages there.
