### ISSUE TITLE
[Bug]: libosmpbf can not be rebuilt or upgraded

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#20124]
### Problem description

I failed to rebuild or upgrade libosmpbf.

### What steps will reproduce the bug?

`./build-package.sh -I -f libosmpbf` gives me this log:
[log.txt](https://github.com/termux/termux-packages/files/15290541/log.txt)
It seems like it is not compatible with abseil-cpp source but I am not so sure about it.

After updating libosmpbf to 1.5.1 with SHA256=edd98ba252c81372113747a131466f5ba45e0cff97b597e863a26e83943ba84f I am getting different log:
[log2.txt](https://github.com/termux/termux-packages/files/15290556/log2.txt)
It seems like it fails to find protobuf generator binary.

### What is the expected behavior?

N/A

### System information

N/A

**Comment by licy183** [comment]
`abseil-cpp` headers need at least c++ 17 to compile, but `libosmpbf` uses `-std=gnu++14`.

**Comment by twaik** [comment]
What about the protobuf issue?

**Comment by licy183** [comment]
> What about the protobuf issue?

I don't have a computer with me so I can't test it. I'll test it when I get back tonight.

**Comment by twaik** [comment]
It seems like removing `protobuf_MODULE_COMPATIBLE` and `CMAKE_FIND_PACKAGE_PREFER_CONFIG` from CMakeLists.txt fixes it. Thank you.
