### ISSUE TITLE
python-torch pkg error 

### ISSUE THREAD

**Issue by shaheen-coder** [termux/termux-packages#20129]
### Problem description

i try to install python (3.11.8) pytorch on termux and i see there is 'python-torch' pkg on mirror after installed, torch doesnt work 

![Screenshot_2024-05-13-21-02-33-593_com termux](https://github.com/termux/termux-packages/assets/116414366/f6b3dd8a-b78d-46e9-938f-d26e58009d65)
![Screenshot_2024-05-13-21-02-13-461_com termux](https://github.com/termux/termux-packages/assets/116414366/5548bd78-7e7e-4d5e-8d9e-66de4afd9933)

error : 
``
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen failed: cannot locate symbol "_ZN4absl12lts_2023080213hash_internal15MixingHashState5kSeedE" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/lib/libtorch_python.so"...
``

### What steps will reproduce the bug?

idk !

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21992
TERMUX_IS_DEBUGGABLE_BUILD=0                                                                 TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:                                                                   aarch64                                                                                      Subscribed repositories:
# sources.list
deb https://mirrors.qvq.net.cn/termux/termux-main stable main
Updatable packages:
libnghttp2/stable 1.62.0 aarch64 [upgradable from: 1.61.0]
termux-tools version:
1.42.1
Android version:
12
Kernel build information:
Linux localhost 4.19.191-perf-01022-gec293e668c0c #1 SMP PREEMPT Fri Mar 10 18:54:33 CST 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
22120RN86G
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by shaheen-coder** [comment]
Hey ? Did you debug it ? If I reinstall, it should work well ?

**Comment by shaheen-coder** [comment]
i still got that error 

``
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/35.2 MB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 61324 files and directories currently installed.)
Preparing to unpack .../python-torch_2.1.2-1_aarch64.deb ...
Unpacking python-torch (2.1.2-1) over (2.1.2-1) ...
Setting up python-torch (2.1.2-1) ...
Installing dependencies for python-torch...
Requirement already satisfied: filelock in /data/data/com.termux/files/usr/lib/python3.11/site-packages (3.14.0)
Requirement already satisfied: jinja2 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (3.1.4)
Requirement already satisfied: networkx in /data/data/com.termux/files/usr/lib/python3.11/site-packages (3.3)
Requirement already satisfied: sympy in /data/data/com.termux/files/usr/lib/python3.11/site-packages (1.12)
Requirement already satisfied: typing_extensions in /data/data/com.termux/files/usr/lib/python3.11/site-packages (4.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from jinja2) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from sympy) (1.3.0)
``
``
~ $ python -m torch --version
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen failed: cannot locate symbol "_ZN4absl12lts_2023080213hash_internal15MixingHashState5kSeedE" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/lib/libtorch_python.so"...
``
repo:
``
deb https://packages-cf.termux.dev/apt/termux-main stable main
``

**Comment by licy183** [comment]
Install x11-repo and retry. python-torch has been moved to the x11 repository.

**Comment by shaheen-coder** [comment]
i still got that error 

``
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/35.2 MB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 61324 files and directories currently installed.)
Preparing to unpack .../python-torch_2.1.2-1_aarch64.deb ...
Unpacking python-torch (2.1.2-1) over (2.1.2-1) ...
Setting up python-torch (2.1.2-1) ...
Installing dependencies for python-torch...
Requirement already satisfied: filelock in /data/data/com.termux/files/usr/lib/python3.11/site-packages (3.14.0)
Requirement already satisfied: jinja2 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (3.1.4)
Requirement already satisfied: networkx in /data/data/com.termux/files/usr/lib/python3.11/site-packages (3.3)
Requirement already satisfied: sympy in /data/data/com.termux/files/usr/lib/python3.11/site-packages (1.12)
Requirement already satisfied: typing_extensions in /data/data/com.termux/files/usr/lib/python3.11/site-packages (4.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from jinja2) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from sympy) (1.3.0)
``
``
~ $ python -m torch --version
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen failed: cannot locate symbol "_ZN4absl12lts_2023080213hash_internal15MixingHashState5kSeedE" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/torch/lib/libtorch_python.so"...
``
repo:
``
deb https://packages-cf.termux.dev/apt/termux-main stable main
``

**Comment by shaheen-coder** [comment]
Thank you, now its working good
