### ISSUE TITLE
[Bug]: cairo-dock

### ISSUE THREAD

**Issue by babaric-dev** [termux/termux-packages#20131]
### Problem description

It tries to download to tmp when switching themes:
```
warning :  (/home/builder/.termux-build/cairo-dock-core/src/src/gldit/cairo-dock-packages.c:gchar *cairo_dock_download_file_in_tmp(const gchar *):210)
Couldn't create temporary file '/tmp/cairo-dock-net-file.X7mfoV' - check permissions in /tmp
```

### What steps will reproduce the bug?

Go to the "themes" tab in cairo dock settings and switch to another theme

### What is the expected behavior?

It should download successfully.

**Comment by twaik** [comment]
`System information` field is relevant. Do not ignore it please.
