### ISSUE TITLE
Package request: lilypond

### ISSUE THREAD

**Issue by arathron** [termux/termux-packages#2013]
It would be nice to create sheet music and midi files directly on android.

**Comment by its-pointless** [comment]
Issue is last time i checked it required guile 1.8 ?
It might be doable though...

**Comment by fennecdjay** [comment]
Any updates on this issue?

**Comment by tilleule** [comment]
Has anybody managed to have lilypond running in Termux?

**Comment by bilrou** [comment]
### Package description                               
 LilyPond is a music engraving program, devoted to producing the highest-quality sheet music possible. It brings the aesthetics of traditionally engraved music to computer printouts. LilyPond is free software and part of the GNU Project.
### Home page URL                                     
https://lilypond.org/                                 
### Source code URL

https://git.savannah.gnu.org/git/lilypond.git/

**Comment by martineausimon** [comment]
There's an aarch64 in Fedora repos : https://rpmfind.net/linux/RPM/fedora/devel/rawhide/aarch64/l/lilypond-2.23.6-1.fc36.aarch64.html
Maybe it's possible to create a .deb for Termux ?

**Comment by martineausimon** [comment]
Woooooow !! Thank you !!

**Comment by arathron** [comment]
Thank you! It works perfect! 👍

**Comment by mtarenskeen** [comment]
I am extremely grateful to see LilyPond has been added to the termux packages! I already was writing LilyPond scores on my Android tablet while traveling. But to compile the scores I always needed access to my Linux or Windows laptop.

I installled Lilypond on termux now but unfortunately when I try to compile a very simple example lilypond score it crashes with the following message:

`GNU LilyPond 2.23.13 (running Guile 3.0)
Pre-boot error; key: out-of-range, args: (#f "Value out of range -S to< -S" (0 -1 1) (1)Aborted`

Anyone else having this issue? Maybe older lilypond version, using guile1.8 instead of Guile3.0 does not have my issue? What could be the problem here?

**Comment by fennecdjay** [comment]
that's amazing news.
Thanks

**Comment by mtarenskeen** [comment]
> I am extremely grateful to see LilyPond has been added to the termux packages! I already was writing LilyPond scores on my Android tablet while traveling. But to compile the scores I always needed access to my Linux or Windows laptop.
> 
> I installled Lilypond on termux now but unfortunately when I try to compile a very simple example lilypond score it crashes with the following message:
> 
> `GNU LilyPond 2.23.13 (running Guile 3.0) Pre-boot error; key: out-of-range, args: (#f "Value out of range -S to< -S" (0 -1 1) (1)Aborted`
> 
> Anyone else having this issue? Maybe older lilypond version, using guile1.8 instead of Guile3.0 does not have my issue? What could be the problem here?

Narrowing down my problem:
LilyPond seems to run fine in Termux on my Huawei P10lite phone (aarch64 Android, Linux 4.4.23+ kernel)

But it fails with the formentioned message on my Samsung Galaxy Tab A (2016) tablet (armv8l Android, Linux 3.18.14-15260192 kernel)

Maybe I should get myself a newer tablet, but it would be cool to see this fixed (if possible) anyway.

**Comment by mtarenskeen** [comment]
Fixed here:


https://github.com/termux/termux-packages/pull/14659

**Comment by nagymusic** [comment]
Hello! 

I successfully installed Lilypond using Termux on my Android (version 12) tablet, but I can't view the PDF after compiling the file. Here's the error message I received:

```
~ $ lilypond [myfile.ly](http://myfile.ly/)
GNU LilyPond 2.24.4 (running Guile 3.0)
Processing `[myfile.ly](http://myfile.ly/)'
Parsing...
Interpreting music...
Preprocessing graphical objects...
Finding the ideal number of pages...
Fitting music on 1 page...
Drawing systems...
/data/data/com.termux/files/usr/share/lilypond/2.24.4/ly/init.ly:65:2: error: Guile signaled an error for the expression beginning here
#
 (let ((book-handler (if (defined? 'default-toplevel-book-handler)
In procedure open_iconv_descriptors: invalid or unknown character encoding LATIN1
```

Would you have any suggestions on how to fix this issue? Thanks so much!
