### ISSUE TITLE
Delete hping3 and ettercap

### ISSUE THREAD

**Issue by 123z45** [termux/termux-packages#20157]
Hping3 is clearly a ddos tool, and everyone knows that it violates the rules but is not taken down.
The same goes for the ARP hijacking tool Ettercap.

**Comment by 123z45** [comment]
You are unequal and racist. I think talking to you people is meaningless.

**Comment by agnostic-apollo** [comment]
`ettercap` will be removed as it violates are current policy, `hping3` does not. I suggest you read https://github.com/termux/termux-community/blob/site/site/pages/en/rules/index.md#4-no-toxic-behavior-trolling-or-spamming and its consequences before commenting abusive or disrespectful stuff again. You will get banned on next offense.
