### ISSUE TITLE
[Package]: dsniff

### ISSUE THREAD

**Issue by 123z45** [termux/termux-packages#20156]
### Why is it worth to add this package?

Dsniff is an excellent packet capture software and network security auditing tool. The tcpkill and tcpnice tools here are very useful, especially when using Apache. 

If you believe that this software package violates policies, please remove tools other than dsniff, tcpkill, dnsspoof, and tcpnice from it.

### Home page URL

https://monkey.org/~dugsong/dsniff/

### Source code URL

https://ftp.debian.org/debian/pool/main/d/dsniff/dsniff_2.4b1+debian-31.debian.tar.xz

### Packaging policy acknowledgement

- [ ] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [x] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [ ] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

Root requied. Support Android 7.1.2 and later only.

**Comment by twaik** [comment]
We do not package hacking tools.
https://wiki.termux.com/wiki/Hacking
This package violates packaging policy.
![image](https://github.com/termux/termux-packages/assets/9674930/7a4b9776-4d2c-45a1-907a-cbed81ed6521)

**Comment by 123z45** [comment]
Why don't you delete the DDOS tool? Hping3 is the most well-known transport layer DDOS tool, and it is still being maintained there. Moreover, the illegal and criminal software v2ray is still there.

**Comment by twaik** [comment]
The topic is dsniff, not other tools.

**Comment by twaik** [comment]
> Hping3 is the most well-known transport layer DDOS tool

"Can be used for something" does not mean "created for this purpose". You can hurt someone with hammer or rope, but they were created for different purpose and that is the reason they are allowed.

> Moreover, the illegal and criminal software v2ray is still there.

Not everywhere. Probably it is illegal in your country, but it is legal on other places.

**Comment by agnostic-apollo** [comment]
I suggest you read https://github.com/termux/termux-community/blob/site/site/pages/en/rules/hacking.md

>Termux maintainers make case-by-case decisions about whether to accept packages based on the balance of their usefulness. For example, we package `nmap`, which can be used unethically but is a core tool for network diagnostics, but don't package `metasploit`, which is accurately characterized as an engine for breaking into other people's computers.

The primary purpose of `hping3` is not DDOS attacks, even if you may be able to use it for that. However, the primary purpose of `dsniff` is sniffing passwords and that is not allowed by our packaging or community rules.

**Comment by 123z45** [comment]
You are unequal and racist. I think talking to you people is meaningless.
