### ISSUE TITLE
Error  Cant open file "setup.py" no such file or directory in termux

### ISSUE THREAD

**Issue by ILLUMINATI6662** [termux/termux-packages#2015]
My termux dont open Setup.py! heelp xD
One error its runned ;-;
python: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by its-pointless** [comment]
Its most likely because /usr/bin/python doesn't exist
Either install termux-exec which cause /usr/bin/python execute the right python binary or use "python setup.py" command
