### ISSUE TITLE
Package request: TextTop

### ISSUE THREAD

**Issue by Symbian9** [termux/termux-packages#2016]
*TextTop* (`texttop`) - fully interactive X Linux desktop rendered in TTY and streamable over SSH

- https://github.com/tombh/texttop

**Comment by Atavic** [comment]
That's a huge docker package with alpine linux and firefox, see: https://github.com/tombh/texttop/issues/12

**Comment by Atavic** [comment]
Wait, you can install it on a home or cloud server and then SSH in it from your phone.
