### ISSUE TITLE
Package request: libglu1-mesa-dev

### ISSUE THREAD

**Issue by modulesio** [termux/termux-packages#2019]
Mesa OpenGL utility library -- development files

https://packages.ubuntu.com/trusty/libglu1-mesa-dev

---

This provides OpenGL headers for building stuff.

**Comment by modulesio** [comment]
It could also be `libgl-dev`.

**Comment by Grimler91** [comment]
Requires X if I'm not mistaken, so I believe this package request belongs at https://github.com/xeffyr/termux-x-repository.

**Comment by sdrausty** [comment]
@modulesio   `glu` is currently available via https://sdrausty.github.io/TermuxArch/ Arch Linux in [Termux PRoot](https://github.com/termux/proot).  Use `pacman -S glu` to install `glu` on device once [Arch Linux](https://www.archlinux.org/) is installed in Termux.  **Use `pacman -Ss mesa` to search for  *mesa packages available today* on your smartphone and tablet for Android, Chromebook and Fire OS.**  

![Screenshot of Arch On Termux](https://sdrausty.github.io/TermuxArch/docs/imgs/IMG_20171019_190414.jpg)

**Comment by leo60228** [comment]
@sdrausty Not sure where to put this; will this support hardware acceleration on an x86 Chromebook, or just software rendering? And if software rendering, will it support `llvmpipe` or just `softpipe`?

**Comment by sdrausty** [comment]
@leo60228 good questions.  All I know is that it is available on device…

**Comment by xeffyr** [comment]
I added this package to [termux/x11-packages](https://github.com/termux/x11-packages). Soon it will be available as `pkg install libglu libglu-dev`.

@Grimler91 This issue can be closed.
