### ISSUE TITLE
Package request: povray

### ISSUE THREAD

**Issue by koppi** [termux/termux-packages#202]
Why not run POV-Ray on your Android? – The Persistence of Vision Raytracer is a high-quality, Free Software tool for creating stunning three-dimensional graphics.

Website: http://www.povray.org/

I'm stuck, see: http://news.povray.org/povray.unix/thread/%3Cweb.5703a674be33e802db8f4ad50%40news.povray.org%3E/

**Comment by koppi** [comment]
update: I fixed the compilation issues with povray31, here's some screenshots: http://imgur.com/a/p8Ali

It would be nice to have povray37. But I was not able to compile the libboost libraries, a requirement for povray37. If you know howto compile libboost on termux, please let me know.

**Comment by buribu** [comment]
Renderer for mobile system? really? You're going to do this? Even with all computational cost of rendering. You will probably overheat your device and spend your battery very fast.

**Comment by sdrausty** [comment]
From http://hof.povray.org POV-Ray Hall of Fame
![4b](https://user-images.githubusercontent.com/27742457/30513514-90237db4-9ad2-11e7-9a59-fd7c97c1c522.jpg)

**Comment by sdrausty** [comment]
@buribu Really! It's already happened, just not in Termux 💪🙂 Sweet yet. Afaik smartphones consume far less power than their bigger cousins, e.g. desktops, laptops, etc... And when you leave a smartphone or tablet plugged into a powered physical port, the batteries never ever die...

**Comment by sdrausty** [comment]
Povray works on Ubuntu chroot in Termux 😀😍 on a smartphone.

**Comment by sdrausty** [comment]
Made on a smartphone in Termux proot from Povray source http://www.oyonale.com/downloads/scifi_demo.zip today. 

![scifi_demo](https://user-images.githubusercontent.com/27742457/31354926-371c5e52-ad06-11e7-8dc6-543bc417e5ba.jpg)

![screenshot_2017-10-09-14-40-39](https://user-images.githubusercontent.com/27742457/31354946-4e060352-ad06-11e7-85fe-ab35ad22edce.png)

Dependencies for Povray in Debian and Ubuntu are similar:
```
root@localhost:~# apt-cache depends povray
povray
  Depends: libboost-system1.62.0
  Depends: libboost-thread1.62.0
  Depends: libc6
  Depends: libgcc1
  Depends: libilmbase12
  Depends: libjpeg8
  Depends: libopenexr22
  Depends: libpng16-16
  Depends: libsdl1.2debian
  Depends: libstdc++6
  Depends: libtiff5
  Depends: zlib1g
```

**Comment by sdrausty** [comment]
https://sdrausty.github.io/TermuxPovray/ is now updated and online with made in Termux on device examples.  https://github.com/POV-Ray/povray/issues/291 is still seeking resolution at present.

**Comment by sdrausty** [comment]
https://plus.google.com/109614420080028230010/posts/SbT5hjNhMrs Hopefully you find Arch Linux in Termux PRoot and Termux on device insiping. This is a new website regarding Arch Linux in Termux PRoot and is being built around https://github.com/termux/termux-packages/issues/202 Package Request: Povray. More information at https://sdrausty.github.io/TermuxPovray/. The files are amazing.

**Comment by sdrausty** [comment]
Do you find [Arch Linux](https://sdrausty.github.io/TermuxArch/) in [Termux PRoot](https://github.com/termux/proot) and [Termux](https://termux.com) on device insiping?  These images were raytraced on a smartphone in Termux in Android, January 2018.  They were created with [Povray in Arch Linux Termux PRoot](https://sdrausty.github.io/TermuxArch/). This website is about [Povray](https://github.com/POV-Ray) in [Arch Linux](https://sdrausty.github.io/TermuxArch/) in [Termux PRoot](https://github.com/termux/proot) and is being built around [Package Request: Povray](https://github.com/termux/termux-packages/issues/202) and [Povray Termux Package Request](https://github.com/POV-Ray/povray/issues/291).  More information at [https://sdrausty.github.io/TermuxPovray/docs](https://sdrausty.github.io/docsTermuxPovray/).  The files are amazing. Thank you for keeping [this project](https://github.com/termux/termux-packages) up to date.  

![scifi_demo512](https://sdrausty.github.io/filesTermuxPovray/scifi_demo/scifi_demo512.png) 

![julia512](https://sdrausty.github.io/filesTermuxPovray/julia/julia512.png)

![field512](https://sdrausty.github.io/filesTermuxPovray/field/field512.png)

![1ag9512](https://sdrausty.github.io/filesTermuxPovray/nih/1ag9512.png)

![1asy512](https://sdrausty.github.io/filesTermuxPovray/nih/1asy512.png)

![tulips512](https://sdrausty.github.io/filesTermuxPovray/tulips/tulips512.png)

![pebbles512](https://sdrausty.github.io/filesTermuxPovray/pebbles/pebbles512.png)

**Comment by SDRausty** [comment]
Pardon me for asking; After contributing to Termux for more than five years, why have my comments been mimimized here in this topic, and all across the board at Termux Github repositories?

**Comment by SDRausty** [comment]
I would like to know why Termux is asking for help, then bashes its' helpers by banning, deleting and minimizing contributor's work that Termux user's are seeking to use on their palmheld devices.  How will Termux users find what they are seeking for when work contributed to Termux is gone?

**Comment by agnostic-apollo** [comment]
Even comments of termux members including my own comments sometimes get hidden if they are off-topic to the the issue at hand. No need to get emotional about it. The hidden button exists for exactly this reason.

You were commenting about package usage through proot, while request was for native package, and no useful info about solving the issue, so someone would have hidden your comment. Nothing unexpected or cancel-culture about it.

**Comment by SDRausty** [comment]
>No need to get emotional about it. 

I am not emotional about it. I am searching for any logical reasoning why Termux is deleting its' work that lead to a milestone in this topic right here, boost library integration.

>You were commenting about package usage through proot, while request was for native package, and no useful info about solving the issue, so someone would have hidden your comments. 

If it works in PRoot, it should equally well, if not better the native Termux enviromnment.

>Nothing unexpected or cancel-culture about it.

Five years of my Termux contributions minimmized and gone that helped groom native Termux into a much more robust program, I beg to dissagree.  Why?  It really works in Termux PRoot, but still does not work in native Termux is a much better result thsn no one knows it even works in Termux all!

**Comment by SDRausty** [comment]
>No need to get emotional about it. 

I am not emotional about it. I am searching for any logical reasoning why Termux is deleting its' work that lead to a milestone in this topic right here, boost library integration.

>You were commenting about package usage through proot, while request was for native package, and no useful info about solving the issue, so someone would have hidden your comments. 

If it works in PRoot, it should work equally well, if not better the native Termux environment.

>Nothing unexpected or cancel-culture about it.

Five years of my Termux contributions minimized and gone that helped groom native Termux into a much more robust program, I choose to disagree.  Why?

If it really does work in Termux PRoot, but still does not work in native Termux is a much much better result than no one knows it even works in Termux all!

**Comment by SDRausty** [comment]
>Renderer for mobile system? really? You're going to do this? Even with all computational cost of rendering. You will probably overheat your device and spend your battery very fast.

How did this quoted comment contribute to `povrsy` on handheld Termux Android development?

**Comment by Grimler91** [comment]
> If it works in PRoot, it should work equally well, if not better in the native Termux environment.

No, a package that works with glibc in proot does not mean that it works with termux/android.

> If it really does work in Termux PRoot very well, but still does not work in native Termux is a much better result than no one knows it even works in Termux all!  Do you agree?

Pointing out that a package works in proot is off-topic in a package request issue like this one, so I disagree.

Back in the day you were commenting on a lot of package requests to notify that the package in question was available from archlinux, which was frankly annoying and seemed mostly like self-advertisement for your arch project

**Comment by SDRausty** [comment]
>Why not run POV-Ray on your Android?

My first comment in this issue answers op's request, and it is minimized now.  It seems that running `povray` was not possible on Android handheld until @koppi's request was answered by me.  Granted, the answer is a nonnative Termux answer, but I still cannot phantom why answering op's question is considered off topic spam now, but not in 2017.  This logic is mad:

It did not work = It works = SPAM = off topic

I felt that this topic is important enough to let upstream know too at https://github.com/POV-Ray/povray/issues/291, and it seems that upstream is not as eager to delete/minimize my hard effort/work with contributions as Termux are recently now.  

The SDRausty account is now banned for years at Gitter.  I still di not know why;  Can you please unban the SDRausty account at Gitter please?

>No, a package that works with glib in troop does not mean that it works with Termux/android.

The reason Termux Arch exists is because of Termux user requests.  Much of the work at Termux Arch is modifying the scripts without cracking/rooting Android.

>Pointing out that a package works in troop is off-topic in a package request issue like this one, so I disagree.

Does this answer imply that granting op's request via Termux Arch should NOT have been announced to the Termux community.  Please keep in mind that finding a working `povray` in Termux P Root took much time for it did NOT work in almost all P Roots.  More so, finding a working Termux P Root solution is NOT effortless either.  Finding a solution that works consistently and reliably requires very much effort and time.  Rooting Android devices to use Termux seems to make absolutely no sense at all as privileged apps can run Android!  Do you not agree @Grimmer?

>that the package in question was available from archlinux, which was frankly annoying 

I do not find the topic that it did not work, but now it works annoying at all.  Especially when it grants Termux user requests that seem.to he met with aplause except for Termux's aplause and thanks, as in this topic here.

**Comment by SDRausty** [comment]
It is great that `povray` is finally available in native Termux.  Contributing to this issue, and at https://github.com/POV-Ray/povray/issues/291 took much time.  Finding a working `povray` solution took more time and effort.  A thank you was not expected. Neither was a ban.

>Pointing out that a package works in proot is off-topic

Trivializing precious hard work given to Termux is shamefull and finding my hard work that eventually led to povray's native integration minimized and deleted and more of this same behaviour at https://github.com/termux by Termux's curators while supurfulous topics are displayed up front, and in plain sight consuming time and detracting from the main topic, "does it work well on handheld?" only speaks of our team's integraty.  Do you agree?

**Comment by SDRausty** [comment]
@Grimler91 you want them to root Android!

I want us to use Android as best as we can; Can you please assit us in this goal?

**Comment by agnostic-apollo** [comment]
A lot of things are possible in proot, but they would still be off-topic for an issue for native package request. If you were the one who first got it running in proot, then great, but you are welcome to create your own repos and blogs to document such stuff and just post a link in the comment instead of posting all the off-topic stuff here. Long and multiple comments can be clutter and can be hidden if doesn't really relate to actual issue. And devices heating and battery running out is obviously an issue when one uses such stuff, specially on devices from 2016, and its just a single comment. 

And your [five years of contributions](https://github.com/termux/termux-packages/commits?author=SDRausty) are not gone, in this issue only your comments were hidden, and not even deleted.

I don't know why you got banned, could be because you were throwing tantrums or excessively spamming/self-promoting there too.

**Comment by SDRausty** [comment]
>could be because you were throwing tantrums or excessively spamming/self-promoting there too.

Examples please, or is this selfjustification?

**Comment by Grimler91** [comment]
> The SDRausty account is now banned for years at Gitter. I still do not know why; Can you please unban the SDRausty account at Gitter please?

Really? You don't know why? You were spamming termux's channel with gibberish and arguing with various contributors, like you are doing here right now. See for example [messages here](https://gitter.im/termux/termux?at=5adce5ca62316e0505ea3c29). You were repeatedly told to stop spamming: [[1]](https://gitter.im/termux/termux?at=59c339c6bc464729745bc29a), [[2]](https://gitter.im/termux/termux?at=5aec0d8e59a0578004a3894b), [[3]](https://gitter.im/termux/termux?at=5e4468b1340a8019bbbb4275).

You were also spamming us moderators in private. 
<details>
<summary>Here's an example of what the gitter logs look like between you and I</summary>

![sdrausty1](https://user-images.githubusercontent.com/18900601/159114430-1798cd97-9c27-4040-8dfd-156717634991.png)
![sdrausty2](https://user-images.githubusercontent.com/18900601/159114440-17915f0f-b39f-4961-af05-2e43a9e540df.png)
![sdrausty3](https://user-images.githubusercontent.com/18900601/159114441-a55d7448-f5b1-446b-a51c-ef3c7d7c9927.png)

</details>

If you don't know why you were banned from gitter then it seems kinda futile to try to explain why your comments on this issue for example are considered off-topic/spam. 

These discussions have taken too much time and energy from everyone involved already, and you've now (necro-)posted in ~10 different issues/package requests asking the same thing, so I'll go ahead and save us all some headache by blocking you from the termux organization

**Comment by Mwm110** [comment]
https://user-images.githubusercontent.com/39448746/209030191-0f5bbcf6-4e93-4bde- [ ] # -8cef-694d1ed3b845.mp4~~[]()
~~
