### ISSUE TITLE
Cloudfoundry - Gem::Ext::BuildError: ERROR: Failed to build gem native extension 

### ISSUE THREAD

**Issue by Deekshit51** [termux/termux-packages#2021]
Started installing CPI
  Compiling package 'ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042'... Finished (00:00:00)
  Compiling package 'bosh_aws_cpi/c2563067cbc20e3406ea36ca2984df2f0eaebcb0'... Failed (00:00:03)
Failed installing CPI (00:00:03)

Installing CPI:
  Compiling job package dependencies for installation:
    Compiling job package dependencies:
      Compiling package:
        Running command: 'bash -x packaging', stdout: 'Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Installing json 1.8.3 with native extensions
Installing mini_portile2 2.1.0
Installing pkg-config 1.1.7
Installing little-plugger 1.1.4
Installing multi_json 1.12.1
Installing semi_semantic 1.2.0
Installing membrane 1.1.0
Installing httpclient 2.7.1
Using bundler 1.11.2
Installing nokogiri 1.6.8 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/ext/nokogiri
/home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/bin/ruby -r ./siteconf20180111-2906-r4yh2y.rb extconf.rb
Using pkg-config version 1.1.7
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
/home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- openssl (LoadError)
        from /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/lib/ruby/2.2.0/net/https.rb:22:in `<top (required)>'
        from /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:3:in `<top (required)>'
        from /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/mini_portile2-2.1.0/lib/mini_portile2.rb:2:in `<top (required)>'
        from /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from extconf.rb:468:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/nokogiri-1.6.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8 for inspection.
Results logged to /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/nokogiri-1.6.8/gem_make.out
Installing logging 1.8.2
An error occurred while installing nokogiri (1.6.8), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.
', stderr: '+ set -e -x
+ BOSH_PACKAGES_DIR=/home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages
+ cp -a bosh_aws_cpi/Gemfile bosh_aws_cpi/Gemfile.lock bosh_aws_cpi/bin bosh_aws_cpi/lib bosh_aws_cpi/vendor /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/bosh_aws_cpi
+ export BUNDLE_CACHE_PATH=vendor/package
+ BUNDLE_CACHE_PATH=vendor/package
+ export BUNDLE_WITHOUT=development:test
+ BUNDLE_WITHOUT=development:test
+ bundle_cmd=/home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/bin/bundle
+ cd /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/bosh_aws_cpi
+ /home/ec2-user/.bosh/installations/f0a51651-8013-4822-73ac-e17f624a3949/packages/ruby_aws_cpi/bin/bundle install --local --no-prune --deployment
':
          exit status 5

Exit code 1

**Comment by Deekshit51** [comment]
Can any one help me on this ?

**Comment by Atavic** [comment]
Ruby version in this repository is 2.4.0 
Maybe ask [here](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release)?

**Comment by sdrausty** [comment]
Try `gem install nokogiri -- --use-system-libraries`.

**Comment by chemostafa** [comment]
Try that it works with me

apt install ruby-dev libxml2-dev libxslt-dev pkg-config make clang

**Comment by Deekshit51** [comment]
That is also not working for me :-1:  ... just let me know if there is any other way to do this

**Comment by Grimler91** [comment]
This doesn't seem to be related to termux, as @Atavic hinted, and paths like `/home/ec2-user/.bosh/.../ruby/2.2.0/extensions/x86_64-linux`

Closing.
