### ISSUE TITLE
Package request: dstat

### ISSUE THREAD

**Issue by kaefert** [termux/termux-packages#2022]
I found this pull request, but it's not in the termux included pkg repository i think..
https://github.com/termux/termux-packages/pull/688

Is there some other way to get dstat on my Android device based on this CPU: `Realtek RTD1295 ARM`?

**Comment by sdrausty** [comment]
@kaefert `dstat` is currently available via https://sdrausty.github.io/TermuxArch/ Arch Linux in [Termux PRoot](https://github.com/termux/proot).  Use `pacman -S dstat` to install `dstat` on device once [Arch Linux](https://www.archlinux.org/) is installed in Termux.  Use `pacman -Ss statistics` to search for a plethora of statistics packages available today on your smartphone and tablet for Android, Chromebook and Fire OS.

**Comment by its-pointless** [comment]
yes 
wget https://github.com/dagwieers/dstat/archive/0.7.3.tar.gz
extract and patch the makefile with 
https://github.com/its-pointless/gcc_termux/raw/master/dstat.patch

termux-fix-shebang dstat
make install

**Comment by kaefert** [comment]
Thanks for both your replies!

I first looked at TermuxArch and read in the install guide 1GB free storage is required - which I thought maybe is quite a lot just for this little tool (dstat).

So I look at the method to compile it myself, which worked like a charm, but also required nearly 250mb of storage for all those build tools. But that's okey and if I wanted I can remove them now after dstat is built :)

Huge thanks to my saviors and also to the developers of Termux (and all the free software it's based on)!
(I still think dstat would be a very valueable addition to the default packages repository available through tmux `pkg install x`)

**Comment by kaefert** [comment]
okey, so it's actually MUCH easier than what I did before. No build tools required. Just download the raw python script, and adapt the first line to match Termux Paths!
```
cd /data/data/com.termux/files/usr/bin
wget https://raw.githubusercontent.com/dagwieers/dstat/master/dstat
sed -i "1s/#!/#!\/data\/data\/com.termux\/files/" dstat
chmod +x dstat

#to be able to run dstat you have to have a python 2 runtime installed (anyway)
pkg install python2
dstat -taflmsC total
```

**Comment by sdrausty** [comment]
> No build tools required  

Perfect! Python is your build tool btw.  

> `pkg install python2`

>> No problems with python2...

*From https://github.com/sdrausty/TermuxArch/issues/30 Python's "pip install" fails with "permission denied".*

@kaefert It is great news that it can be installed with python2.  Is there a particular reason for choosing python2?

**Comment by kaefert** [comment]
just the hint from the first line of the dstat python script which in the original version reads:
`#!/usr/bin/env python2`

**Comment by sdrausty** [comment]
Permission denied #create-react-app https://github.com/termux/termux-packages/issues/1899 This might be another python3 issue too.

**Comment by kaefert** [comment]
I just tried to run dstat using the python3 runtime, which gives this error:
```
  File "/data/data/com.termux/files/usr/bin/dstat", line 122
    except getopt.error, exc:
                       ^
```

**Comment by twaik** [comment]
Does not comply with [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last change was 4 years ago and it is indicating development has been terminated.
