### ISSUE TITLE
Update ffmpeg

### ISSUE THREAD

**Issue by mishpro-programm** [termux/termux-packages#20220]
In new version, ffmpeg needs to be compiled with libharfbuzz in order to drawtext filter work. Please recompile ffmpeg binary with libharfbuzz
(Sorry for my english)

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/9117497565

I have tested ffmpeg with the following command.

```
ffmpeg -i input.mp4 -vf "drawtext=text='Hello, World':fontfile=$PREFIX/share/fonts/TTF/DejaVuSans.ttf:fontsize=24:fontcolor=white:x=10:y=10" output.mp4
```

It produces the output.mp4 file which has "Hello, World" text in the upper left corner.

**Comment by mishpro-programm** [comment]
It works, tysm!
