### ISSUE TITLE
[Bug]: upgrade failure for libltdl / libtool

### ISSUE THREAD

**Issue by vinc17fr** [termux/termux-packages#20230]
### Problem description

The upgrade of libltdl / libtool fails with a "trying to overwrite" error message.

### What steps will reproduce the bug?

```
$ pkg upgrade
The following packages will be upgraded:
  gdk-pixbuf libltdl libtool
[...]
Preparing to unpack .../gdk-pixbuf_2.42.12_aarch64.deb ...
Unpacking gdk-pixbuf (2.42.12) over (2.42.11) ...
Preparing to unpack .../libltdl_2.4.7-2_aarch64.deb ...
Unpacking libltdl (2.4.7-2) over (2.4.7-1) ...
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/libltdl_2.4.7-2_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/include/ltdl.h', which is also in package libtool 2.4.7-1
Preparing to unpack .../libtool_2.4.7-2_aarch64.deb ...
Unpacking libtool (2.4.7-2) over (2.4.7-1) ...
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/libltdl_2.4.7-2_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

### What is the expected behavior?

The upgrade shouldn't try to overwrite a file from another package (at least, not yet upgraded).

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12141
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
Updatable packages:
libltdl/stable 2.4.7-2 aarch64 [upgradable from: 2.4.7-1]
termux-tools version:
1.42.1
Android version:
11
Kernel build information:
Linux localhost 4.14.186 #1 SMP PREEMPT Wed May 24 18:56:15 BST 2023 aarch64 Android
Device manufacturer:
Planet_Computers
Device model:
Astro_Slide_5G_Transformer
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Biswa96** [comment]
It could be fixed by adding TERMUX_SUBPKG_REPLACES but I am not sure enough. In the meantime, I workaround the issue by reinstalling those packages `apt reinstall libtool libltdl`

**Comment by Grimler91** [comment]
Fixed, thanks for the report!

**Comment by vinc17fr** [comment]
I hope that the `Breaks` is sufficient. https://www.debian.org/doc/debian-policy/ch-relationships.html#packages-which-break-other-packages-breaks says "If the breaking package also overwrites some files from the older package, it should use `Replaces` to ensure this goes smoothly. See [Overwriting files and replacing packages - Replaces](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-replaces) for a full discussion of taking over files from other packages, including how to use `Breaks` in those cases." And this other webpage says "Normally, `Breaks` should be used in conjunction with `Replaces`."

**Comment by Grimler91** [comment]
I tested it and upgrade worked fine. But yeah, you are right, reading up on the [footnote there](https://www.debian.org/doc/debian-policy/ch-relationships.html#id9) it seems ltdl.h risks being lost if REPLACES is not added as well. 

I've added Replaces as well in https://github.com/termux/termux-packages/commit/cdfa380f3235f7abac5543826b191144f8c59e4a, thanks!
