### ISSUE TITLE
Parallel /bin/sh not found

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-packages#2024]
Hello, I'm getting this error when trying to run parallel: `parallel: Error: Shell '/bin/sh' not found.`
I made an upgrade but still...

**Comment by Grimler91** [comment]
Yeah we should patch that. The script checks for SHELL first though so you can fix it temporarily with `export SHELL=$PREFIX/bin/sh`.

**Comment by kurokirasama** [comment]
Running `termux-chroot` again also worked...
