### ISSUE TITLE
Bug how to fix this

### ISSUE THREAD

**Issue by Sparta101091** [termux/termux-packages#20251]
### Problem description

![Screenshot_2024-05-17-19-25-45-590_com termux](https://github.com/termux/termux-packages/assets/169583514/52b9192a-fd71-461a-9302-58e34c93249d)
How to fix this acc

### What steps will reproduce the bug?

When ido python

### What is the expected behavior?

.

### System information

```shell
When ido python
```

**Comment by tqfx** [comment]
Please provide more information about this issue, such as `python -c 'import requests;print(requests.__version__)'`.

**Comment by licy183** [comment]
Please reinstall `requests` using pip. `pip install requests --force-reinstall --no-cache-dir`

**Comment by thunder-coding** [comment]
Closed as no input from author

**Comment by thunder-coding** [comment]
Closed as no input from author
