### ISSUE TITLE
[Bug]: Can't install jupyterlab on termux (python version 3.11.9)

### ISSUE THREAD

**Issue by JahidCodeVoyage** [termux/termux-packages#20271]
### Problem description

~ $ pip install jupyterlab                            Collecting jupyterlab                                   Using cached jupyterlab-4.2.0-py3-none-any.whl.metadata (16 kB)                                           Collecting async-lru>=1.0.0 (from jupyterlab)
  Using cached async_lru-2.0.4-py3-none-any.whl.metadata (4.5 kB)
Collecting httpx>=0.25.0 (from jupyterlab)              Using cached httpx-0.27.0-py3-none-any.whl.metadata (7.2 kB)
Collecting ipykernel>=6.5.0 (from jupyterlab)
  Using cached ipykernel-6.29.4-py3-none-any.whl.metadata (6.3 kB)                                          Collecting jinja2>=3.0.3 (from jupyterlab)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting jupyter-core (from jupyterlab)               Using cached jupyter_core-5.7.2-py3-none-any.whl.metadata (3.4 kB)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab)
  Using cached jupyter_lsp-2.2.5-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.4.0 (from jupyterlab)
  Using cached jupyter_server-2.14.0-py3-none-any.whl.metadata (8.4 kB)                                     Collecting jupyterlab-server<3,>=2.27.1 (from jupyterlab)
  Using cached jupyterlab_server-2.27.1-py3-none-any.whl.metadata (5.9 kB)
Collecting notebook-shim>=0.2 (from jupyterlab)         Using cached notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting packaging (from jupyterlab)
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting tornado>=6.2.0 (from jupyterlab)
  Using cached tornado-6.4.tar.gz (498 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting traitlets (from jupyterlab)
  Using cached traitlets-5.14.3-py3-none-any.whl.metadata (10 kB)
Collecting anyio (from httpx>=0.25.0->jupyterlab)
  Using cached anyio-4.3.0-py3-none-any.whl.metadata (4.6 kB)
Collecting certifi (from httpx>=0.25.0->jupyterlab)
  Using cached certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting httpcore==1.* (from httpx>=0.25.0->jupyterlab)
  Using cached httpcore-1.0.5-py3-none-any.whl.metadata (20 kB)
Collecting idna (from httpx>=0.25.0->jupyterlab)
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting sniffio (from httpx>=0.25.0->jupyterlab)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx>=0.25.0->jupyterlab)
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting comm>=0.1.1 (from ipykernel>=6.5.0->jupyterlab)
  Using cached comm-0.2.2-py3-none-any.whl.metadata (3.7 kB)
Collecting debugpy>=1.6.5 (from ipykernel>=6.5.0->jupyterlab)
  Using cached debugpy-1.8.1-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting ipython>=7.23.1 (from ipykernel>=6.5.0->jupyterlab)
  Using cached ipython-8.24.0-py3-none-any.whl.metadata (4.9 kB)
Collecting jupyter-client>=6.1.12 (from ipykernel>=6.5.0->jupyterlab)
  Using cached jupyter_client-8.6.1-py3-none-any.whl.metadata (8.3 kB)
Collecting matplotlib-inline>=0.1 (from ipykernel>=6.5.0->jupyterlab)
  Using cached matplotlib_inline-0.1.7-py3-none-any.whl.metadata (3.9 kB)
Collecting nest-asyncio (from ipykernel>=6.5.0->jupyterlab)
  Using cached nest_asyncio-1.6.0-py3-none-any.whl.metadata (2.8 kB)
Collecting psutil (from ipykernel>=6.5.0->jupyterlab)
  Using cached psutil-5.9.8.tar.gz (503 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyzmq>=24 (from ipykernel>=6.5.0->jupyterlab)
  Using cached pyzmq-26.0.3.tar.gz (267 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting MarkupSafe>=2.0 (from jinja2>=3.0.3->jupyterlab)
  Using cached MarkupSafe-2.1.5.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting platformdirs>=2.5 (from jupyter-core->jupyterlab)
  Using cached platformdirs-4.2.2-py3-none-any.whl.metadata (11 kB)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached argon2_cffi-23.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting jupyter-events>=0.9.0 (from jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached jupyter_events-0.10.0-py3-none-any.whl.metadata (5.9 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached jupyter_server_terminals-0.5.3-py3-none-any.whl.metadata (5.6 kB)
Collecting nbconvert>=6.4.4 (from jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached nbconvert-7.16.4-py3-none-any.whl.metadata (8.5 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting overrides>=5.0 (from jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached prometheus_client-0.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached Send2Trash-1.8.3-py3-none-any.whl.metadata (4.0 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.27.1->jupyterlab)
  Using cached Babel-2.15.0-py3-none-any.whl.metadata (1.5 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.27.1->jupyterlab)
  Using cached json5-0.9.25-py3-none-any.whl.metadata (30 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.27.1->jupyterlab)
  Using cached jsonschema-4.22.0-py3-none-any.whl.metadata (8.2 kB)
Collecting requests>=2.31 (from jupyterlab-server<3,>=2.27.1->jupyterlab)
  Using cached requests-2.32.0-py3-none-any.whl.metadata (4.6 kB)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached argon2-cffi-bindings-21.2.0.tar.gz (1.8 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      Collecting setuptools>=45
        Using cached setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-8.1.0-py3-none-any.whl.metadata (6.6 kB)
      Collecting wheel
        Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting cffi>=1.0.1
        Using cached cffi-1.16.0.tar.gz (512 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting packaging>=20 (from setuptools_scm>=6.2)
        Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
      Collecting pycparser (from cffi>=1.0.1)
        Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
      Using cached setuptools-69.5.1-py3-none-any.whl (894 kB)
      Using cached setuptools_scm-8.1.0-py3-none-any.whl (43 kB)
      Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
      Using cached packaging-24.0-py3-none-any.whl (53 kB)
      Using cached pycparser-2.22-py3-none-any.whl (117 kB)
      Building wheels for collected packages: cffi
        Building wheel for cffi (pyproject.toml): started
        Building wheel for cffi (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for cffi (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [38 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-aarch64-cpython-311
            creating build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/__init__.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/_imp_emulation.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/_shimmed_dist_utils.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/api.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/backend_ctypes.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/cffi_opcode.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/commontypes.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/cparser.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/error.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/ffiplatform.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/lock.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/model.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/pkgconfig.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/recompiler.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/setuptools_ext.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/vengine_cpy.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/vengine_gen.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/verifier.py -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/_cffi_include.h -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/parse_c_type.h -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/_embedding.h -> build/lib.linux-aarch64-cpython-311/cffi
            copying src/cffi/_cffi_errors.h -> build/lib.linux-aarch64-cpython-311/cffi
            running build_ext
            building '_cffi_backend' extension
            creating build/temp.linux-aarch64-cpython-311
            creating build/temp.linux-aarch64-cpython-311/src
            creating build/temp.linux-aarch64-cpython-311/src/c
            aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/python3.11 -c src/c/_cffi_backend.c -o build/temp.linux-aarch64-cpython-311/src/c/_cffi_backend.o
            aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib build/temp.linux-aarch64-cpython-311/src/c/_cffi_backend.o -L/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr/lib -lffi -lpython3.11 -o build/lib.linux-aarch64-cpython-311/_cffi_backend.cpython-311.so
            aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
            aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
            error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      Failed to build cffi
      ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
~ $

### What steps will reproduce the bug?

pip install jupyterlab.
In python version 3.11.8 , jupyterlab was  installed without any problem. But in python version 3.11.9 fails to install lab in termux.

Experts, please help to solve this issue.

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=22846
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.sjtu.edu.cn/termux/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.42.1
Android version:
11
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Mon Apr 25 15:49:22 CST 2022 aarch64 Android
Device manufacturer:
realme
Device model:
RMX3195
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by twaik** [comment]
I think you should follow the advices from https://github.com/termux/termux-packages/issues/20039.

**Comment by JahidCodeVoyage** [comment]
> I think you should follow the advices from #20039.

Thanks man

**Comment by Karthi02116K** [comment]
I aslo face this problem, but I find out the solution 

Try this
```
pip install pydantic==1.10.2
```
```
pip install anyio distro httpx sniffio tqdm typing-extensions
```
```
pip install openai --no-deps
```
