### ISSUE TITLE
Package request : masscan

### ISSUE THREAD

**Issue by doggukan** [termux/termux-packages#2028]
i have tried to compile it but so many fatal errors .i started issue on masscan repo but if you add it as a package it will be awesome.This is what i get when i make

^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/usr/lib/clang/5.0.1/include/mmintrin.h:518:12: error:
      invalid conversion between vector type '__m64' (vector of 1 'long long' value)
      and integer type 'int' of different size
    return (__m64)__builtin_ia32_psubb((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/usr/lib/clang/5.0.1/include/mmintrin.h:539:12: error:
      invalid conversion between vector type '__m64' (vector of 1 'long long' value)
      and integer type 'int' of different size
    return (__m64)__builtin_ia32_psubw((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Makefile:87: tmp/smack1.o] Error 1
$

**Comment by Grimler91** [comment]
Which arch are you on? 
Could you add a reference to the masscan repo issue you opened?

I ran into this when (cross)-compiling [aircrack-ng for aarch64](https://github.com/termux/termux-root-packages/pull/3#issuecomment-357049587) yesterday but have not been able to find a solution.

**Comment by doggukan** [comment]
aarch64  https://github.com/robertdavidgraham/masscan

**Comment by sdrausty** [comment]
@doggukan `masscan` is currently available via https://sdrausty.github.io/TermuxArch/ Arch Linux in [Termux PRoot](https://github.com/termux/proot).  Use `pacman -S masscan` to install `masscan` on device once [Arch Linux](https://www.archlinux.org/) is installed in Termux.  
```
pacman -Ss masscan
community/masscan 1.0.4-1
    TCP port scanner, spews SYN packets asynchronously, scanning entire Internet in under 5 minutes
```

![Screenshot of Arch On Termux](https://sdrausty.github.io/TermuxArch/docs/imgs/IMG_20171019_190414.jpg)

**Comment by Atavic** [comment]
But OP asked about Masscan, not Arch Linux.

**Comment by sdrausty** [comment]
@Atavic @doggukan 
> asked about Masscan

`masscan` was provided.  Can you provide another option today?  If you can, submit a [pull request here](https://github.com/termux/termux-packages/pulls).

**Comment by sdrausty** [comment]
>  if urgent you can install 

I will consider this.  Thank you.

**Comment by doggukan** [comment]
Installed arch but it takes so much disk space for just masscan.

**Comment by doggukan** [comment]
So is there any way to just use arch with termux

**Comment by doggukan** [comment]
Cant run masscan because of the interface issues ? any fix? device is rooted

**Comment by sdrausty** [comment]
> it takes so much disk space for just masscan.

https://sdrausty.github.io/TermuxArch/ in not just for `masscan` https://github.com/termux/termux-packages/issues?utf8=%E2%9C%93&q=is%3Aissue+termuxarch+

> it takes so much disk space 

Some projects consume amazing amounts of disk space.  See https://sdrausty.github.io/TermuxPovray/ concerning  https://github.com/termux/termux-packages/issues/202 "Package request: Povray" for one such example.

**Comment by sdrausty** [comment]
@doggukan 
> Cant run masscan because of the interface issues ? any fix? device is rooted

If this is in Arch Linux Termux PRoot open an issue https://github.com/sdrausty/TermuxArch/issues here.  Provide `setupTermuxArch.sh --sysinfo` output along with your input and output.  Include screenshots if you think they will help in resolving.

**Comment by Atavic** [comment]
[python-masscan](https://github.com/MyKings/python-masscan) needs python2 package and `pip` Package Management.

**Comment by doggukan** [comment]
issue is accesing the interface .so cant be fixed i think.i was able to run but no open ports.even tried with root

thanks i will have a look at the python-masscan.

**Comment by Grimler91** [comment]
@doggukan did you only try in arch or did you try the python package as well?

**Comment by ExtremeNerd** [comment]
You can get an alpine Linux PRoot working with just one command, since they already provide you with a minimal rootfs tarball.

`proot -S [PATH_TO_UNPACKED_ROOTFS] -b /storage -b $HOME`

Of course, you can store the required alpine package in SD Card, as well as all direct / indirect dependencies [Which are of course less in case of extra lightweight Alpine Linux], then run `apk add` on all them with `allow untrusted` and dependency ignorance flags. If it won't work, rename to something.tar.gz and unpack in proot root directory, for getting simple packages to work..

If you can find a binary package in Arch ARM Repo with less complicated config files, you can have a 30 minute (somewhat) workaround to unpack its contents to respective directories of termux prefix. [API Level 23+ maybe required for some .so files]


P.S: I am having issues with network inside a PRooted alpine Linux Rootfs.. If you get `apk add` working in straightforward manner, lemme know.... 😎
