### ISSUE TITLE
[Bug]: Building package 'apt' fails

### ISSUE THREAD

**Issue by shadowprospero** [termux/termux-packages#20288]
### Problem description

The APT binary apt_2.7.12.tar.xz not found in the remote repository

```
Downloading https://deb.debian.org/debian/pool/main/a/apt/apt_2.7.12.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   260    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Failed to download https://deb.debian.org/debian/pool/main/a/apt/apt_2.7.12.tar.xz
[*] Building 'apt' exited with exit code 1
Failed to build package 'apt' for arch 'aarch64'

```

### What steps will reproduce the bug?

Run ./scripts/run-docker.sh
In docker run ./scripts/build-bootstraps.sh --architectures aarch64

### System information

```shell
macos
```

**Comment by TomJo2000** [comment]
It looks like your docker container does not have a working internet connection or domain name resolution.
I am unable to reproduce the issue locally with
`./scripts/run-docker.sh ./scripts/build-bootstraps.sh --architectures aarch64`

**Comment by shadowprospero** [comment]
Just try to open this link
https://deb.debian.org/debian/pool/main/a/apt/apt_2.7.12.tar.xz

**Comment by TomJo2000** [comment]
We do not control the web servers for Debian.
If they are having an outage, that is an upstream issue (and highly unusual).

**Comment by TomJo2000** [comment]
Ah figured it out, there is no `apt_2.7.12.tar.xz` file on the upstream FTP server, in which case that does become our bug because we'll need to get APT's source code from somewhere else then.
Very odd that it would be suddenly removed though.

**Comment by shadowprospero** [comment]
This archive is not available on FTP
<img width="476" alt="Screenshot 2024-05-22 at 15 47 45" src="https://github.com/termux/termux-packages/assets/124584269/e9105386-09ad-4688-8e24-4f8b70e49dcb">

**Comment by shadowprospero** [comment]
Quite strange behaviour. Why do they delete old sources from FTP

**Comment by Biswa96** [comment]
There is a pending pull request to update apt package. It may solve this issue.

**Comment by shadowprospero** [comment]
https://github.com/termux/termux-packages/issues/19791 done for old version. It's closed

**Comment by Biswa96** [comment]
> Unless there is another one I'm not aware of Biswa.

Now there is :slightly_smiling_face:
