### ISSUE TITLE
[Bug]: openai installation in termux 

### ISSUE THREAD

**Issue by Karthi02116K** [termux/termux-packages#20295]
### Problem description

I try to install openai in termux, but it's not installed properly, it showing Error problem with subprocess 

But I find the Error also solution for error

### What steps will reproduce the bug?

pip install pydantic==1.10.2
pip install anyio distro httpx sniffio tqdm typing-extensions
pip install --upgrade pip
pip install openai --no-deps

Try this to solve this error in termux

### System information

```shell
u0_a331@localhost
-----------------
OS: Android 11 aarch64
Host: realme RMX3201
Kernel: 4.19.127+
Uptime: 7 hours, 16 mins
Packages: 195 (dpkg), 1 (pkg)
Shell: bash 5.2.26
CPU: MT6765G (8) @ 2.301GHz
Memory: 1662MiB / 2802MiB
```

**Comment by Biswa96** [comment]
What is the error?

**Comment by Karthi02116K** [comment]
Error solved....👍🏻
