### ISSUE TITLE
Package request : at

### ISSUE THREAD

**Issue by LaChirla** [termux/termux-packages#2031]
**at** is a small, but highly efficient package.
It does: 
Delayed job execution and batch processing
Runs a  job at a specified time.

Thank you

**Comment by sdrausty** [comment]
@LaChirla  `at` is currently available via https://sdrausty.github.io/TermuxArch/ Arch Linux in [Termux PRoot](https://github.com/termux/proot).  Use `pacman -S at` to install `at` on device once [Arch Linux](https://www.archlinux.org/) is installed in Termux.  

![Screenshot of Arch On Termux](https://sdrausty.github.io/TermuxArch/docs/imgs/IMG_20171019_190414.jpg)

**Comment by Atavic** [comment]
But OP asked for *at*, not *Arch*.

**Comment by sdrausty** [comment]
@Atavic @LaChirla 
> asked for *at*

`at` was provided.  Can you provide another option today?  If you can, submit a [pull request here](https://github.com/termux/termux-packages/pulls).  Also can you explain how your comment is supposed to be constructive, not destructive?

**Comment by Atavic** [comment]
Look at the mirror on the wall. You send every single request to Archtermux.

**Comment by sdrausty** [comment]
> Look at the mirror on the wall. You send every single request to Archtermux.

Can you explain how your comment is supposed to be constructive, not destructive? What constructive characteristics does your comment have?  **Can you provide a roadmap to *your* contributions to this project?**

**Comment by Atavic** [comment]
I have zero contributions.

**Comment by sdrausty** [comment]
> Look at the mirror on the wall. You send every single request to Archtermux

If we were to follow your reasoning, we would be making projects, **but tell no one of their existence**.  Even to people who are seeking a published solution.  This would be similar to
>zero contributions.  

Is your intent to have zero information published about Termux?

**Comment by sdrausty** [comment]
> zero information published about Termux

We have this at present at https://en.wikipedia.org/wiki/Termux 
"Please share your thoughts on the matter ..." as the notice requests https://github.com/termux/termux-packages/issues/1930

**Comment by Atavic** [comment]
:+1: 

Wikipedia page is under the hands of Neo-Oli:
https://en.wikipedia.org/wiki/User:Glow_oli/Termux

**Comment by Quasic** [comment]
It's hard to search for something like "at" without knowing where to ask. Took me forever to find the source: http://ftp.debian.org/debian/pool/main/a/at/at_3.1.16.orig.tar.gz

**Comment by sdrausty** [comment]
@Quasic thanks for sharing the source.

**Comment by Quasic** [comment]
Tried building on device: requires bison, use ```./configure --prefix=$PREFIX```

Doesn't make, yet. I'll work with it a bit when I have time and post progress later...

**Comment by msdos** [comment]
@Quasic any news on this? I couldn't compile it Termux, even using Bison. I'm not familiar with this kind of compilation, I get:

```
clang-8: error: no such file or directory: 'lex.yy.c'
clang-8: error: no input files
clang-8: error: no input files
make: *** [Makefile:93: lex.yy.o] Error 1
```

`at` package is _really_ useful. It makes bash scripting much easier in some situations.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install at
```
