### ISSUE TITLE
[Package]: "mesa-vulkan-icd-freedreno-dri3-24.1.0" Package request

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#20320]
### Why is it worth to add this package?

![6456981b885be7c24c6581c72b54e5e3](https://github.com/termux/termux-packages/assets/101167173/1ac73ead-f9a7-478b-8c86-d141cbff5416)
https://docs.mesa3d.org/relnotes/24.1.0.html

Recently `mesa 24.1.0` was released and
Added native support for `Adreno 750` in turnip.

Distributed from termux main-repo 
`mesa-vulkan-icd-freedreno-dri3` does not work on `Adreno 750` of `Snapdragon 8 Gen3`.

If `mesa-vulkan-icd-freedreno-dri3-24.1.0` is added
It appears that` Adreno 750` can be used in the `Termux native XFCE4 environment`.

### Home page URL

https://www.mesa3d.org/

### Source code URL

https://gitlab.freedesktop.org/mesa/mesa/-/tree/mesa-24.1.0?ref_type=tags

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by twaik** [comment]
No need to ask about package updates. We update packages as soon as we can.

**Comment by hansm629** [comment]
@twaik 
I know that mesa is responding to updates quickly. Currently, it is almost the latest version, `24.0.8`....

but
`mesa-vulkan-icd-freedreno-dri3` is stopped in version `24.0.4`.
That's why I asked for an update.

I tried buildit myself for termux, but
In the `mesa 24.1.0` src, the DRI3 patch used in the 24.0.4 build was not applied and an error occurred.
