### ISSUE TITLE
Hydra Segmentation Fault

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#2033]
_From @Wnns on January 10, 2018 10:34_

Hello. 

When I try to use Hydra I am getting Segmentation Fault. Just this text and nothing more. I am using Motorola G2, uname -m returns armv7l.

_Copied from original issue: termux/termux-app#534_

**Comment by fornwall** [comment]
@Wnns Could you give steps to reproduce (exact commands that you are running to get the segmentation fault)?

**Comment by Wnns** [comment]
`hydra -l test@xxxx.xx -P test smtp://xxxxx.xx`

However I can put anything here. Different protocols, addresses, logins and passwords configurations still return same result:
```
Hydra v8.6 (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2018-01-14 21:20:13
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
Segmentation fault
$
```

**Comment by fornwall** [comment]
Thanks!

I packaged the latest git master of hydra into version `8.6.20180104` of the package - can you try updating to it by running `pkg up` and see if that fixes the problem for you?

**Comment by Wnns** [comment]
Segmentation error is not present now. Hydra performs attacks correctly, it is usable, however there is one issue, various numbers in program are not correct. Here are examples: 
```
[ATTEMPT] target 192.168.0.1 - login "admin" - pass "asddd" - 0 of 122 [child 0] (22254/0)
[ATTEMPT] target 192.168.0.1 - login "admin" - pass "asdddf" - 0 of 123 [child 0] (22254/0)
[ATTEMPT] target 192.168.0.1 - login "admin" - pass "asdddff" - 0 of 124 [child 0] (22254/0)
[ATTEMPT] target 192.168.0.1 - login "admin" - pass "asdddffg" - 0 of 125 [child 0] (22254/0)

```
Here attempt counter is showing wrong values and children have wrong numbers
```
[80][http-get] host: 192.168.0.1   login: admin   password: admin
[STATUS] attack finished for 192.168.0.1 (waiting for children to complete tests)
1 of 1 target successfully completed, 200000 valid password found
```
Result should be: 1 valid password found.

But like I said, attacks are working correctly so no big deal.

**Comment by Grimler91** [comment]
Closing since hydra is no longer a package in the repos
