### ISSUE TITLE
[Bug]: Failed to compile binutils-libs

### ISSUE THREAD

**Issue by mucute** [termux/termux-packages#20349]
### Problem description

Failed to compile binutils-libs
![image](https://github.com/termux/termux-packages/assets/43491106/eafaa065-3943-4988-b1a1-6b816122a9ce)

### What steps will reproduce the bug?

./build-package.sh -a aarch64 binutils-libs

### System information

```shell
docker
```

**Comment by twaik** [comment]
Probably you should share more details. 
Words "failed to compile" and "Leaving directory" are not enough to debug it.
First of all you should post **the whole log**. Not screenshot.

**Comment by TomJo2000** [comment]
@mucute would you mind providing some follow up?
What did fix your issue?

**Comment by mucute** [comment]
@TomJo2000 I pulled the latest image without making any changes to the binutils-libs

**Comment by TomJo2000** [comment]
> @TomJo2000 I pulled the latest image without making any changes to the binutils-libs

And that solved the build issue?

**Comment by mucute** [comment]
[log.txt](https://github.com/termux/termux-packages/files/15484228/log.txt)
Here's the detailed log

**Comment by mucute** [comment]
@TomJo2000 Sorry, the problem hasn't been solved yet

**Comment by Biswa96** [comment]
I can not reproduce the issue. I have built binutils-libs in termux-package-builder container successfully. Please try to remove the container `docker rm -f termux-package-builder` and rebuild it.

**Comment by mucute** [comment]
@Biswa96 Ok, thank you very much for your help

**Comment by TomJo2000** [comment]
Okay so you aren't specifically building `binutils-libs`, but instead `apt` without pre-built  dependencies.

I can't replicate the build failure using the command you used from your log file.

**Comment by TomJo2000** [comment]
Biswa already got around to suggesting making a fresh build container.
I'd also like to ask if you could try the following reproduction steps:
```bash
./scripts/docker-run.sh ./clean.sh
./scripts/run-docker.sh ./build-package.sh -f -I apt
```
- `-f` forces a rebuild if the target package was already built
- `-I` will download the dependencies from the official repositories instead of compiling them locally, resulting in much faster builds.
(It took down a clean build of `apt` from 41 minutes to 3 minutes 30 seconds)

**Comment by TomJo2000** [comment]
I'm gonna assume this can be closed?
