### ISSUE TITLE
[Package]: 7-Zip 24.06

### ISSUE THREAD

**Issue by Cyberavater** [termux/termux-packages#20342]
### Why is it worth to add this package?

An update for the 7zip src code is already available.

### Home page URL

https://www.7-zip.org/download.html

### Source code URL

https://www.7-zip.org/a/7z2406-src.tar.xz

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by twaik** [comment]
No need to ask for package updates. We are aware of all new versions available for all packages (thanks to repology). But we do not need enough human resource to perform package updates and test them.
Pull requests are always welcome.
