### ISSUE TITLE
[Bug]: Qt6 `QProcess` fails to create process for Linux kernel >= 5

### ISSUE THREAD

**Issue by knyipab** [termux/termux-packages#20354]
Most things in this PR `shocut` app works well, except that the export job does not work.,, stuck at finite time "--:--:--". You may try the builds in the PR  #20353 or this action: https://github.com/knyipab/termux-packages/actions/runs/9290613878

After use the program to export file, the only useful log from terminal is below. 
```
[Debug  ] <MeltJob::start> "/data/data/com.termux/files/usr/bin/melt-7 -verbose -progress2 -abort xml:%2Fdata%2Fdata%2Fcom.termux%2Ffiles%2Fusr%2Ftmp%2Fshotcut-jnXVRh.mlt" 
```

Indeed, if I run that command `/data/data/com.termux/files/usr/bin/melt-7 -verbose -progress2 -abort xml:%2Fdata%2Fdata%2Fcom.termux%2Ffiles%2Fusr%2Ftmp%2Fshotcut-jnXVRh.mlt`, it works well and output the intended video. 

That line of log corresponds to [this line of code in `MeltJob::start()`](https://github.com/mltframework/shotcut/blob/407a34a973771fd5a721f9629bbf82b35d55d4be/src/jobs/meltjob.cpp#L123). That method should ultimately call [`QProcess::start()` at this line](https://github.com/mltframework/shotcut/blob/407a34a973771fd5a721f9629bbf82b35d55d4be/src/jobs/abstractjob.cpp#L135). So I suspect that QProcess does not function. I have no proof and nothing more in the log is helpful.

**Comment by Biswa96** [comment]
Does `strace` provide any hint?

**Comment by knyipab** [comment]
it seems to fail to create child process. Don't have experience with `strace` but it seems to fail to create child process. 
```
clone(child_stack=0x7ffdb65530, flags=CLONE_VM|CLONE_PIDFD|CLONE_VFORK|SIGCHLD, parent_tid=NULL) = -1 EFAULT (Bad address)
```

`strace` log: [shortcut_excerpt.log](https://github.com/termux/termux-packages/files/15499017/shortcut_excerpt.log)

**Comment by knyipab** [comment]
A simple Qt6 example (generated by ChatGPT) fails to execute command with `QProcess`. `strace` show similar error in `clone` syscall. 

```bash
g++ -o qprocess qprocess.cpp -lQt6Core -I"$PREFIX"/include/qt6 -I"$PREFIX"/include/qt6/QtCore
```

### qprocess.cpp
```cpp
#include <QCoreApplication>
#include <QProcess>

int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);

    QProcess process;
    process.start("ls", QStringList() << "-l");

    if (process.waitForStarted() && process.waitForFinished()) {
        QByteArray output = process.readAllStandardOutput();
        qDebug() << output;
    } else {
        qDebug() << "Failed to start or execute command.";
    }

    return app.exec();
}
```

**Comment by Biswa96** [comment]
That example program worked in my PC (x86_64) and in my phone (aarch64) without any error.

```
execve("/data/data/com.termux/files/usr/bin/test", ["test"], 0x7fd1e78830 /* 54 vars */) = 0
```

**Comment by Biswa96** [comment]
> When it is without `strace`, does that example program print something similar to `ls -l` on your device?

Yes.

**Comment by knyipab** [comment]
It seems to be `system_vforkfd` introduced in Qt6.4 ([this commit](https://github.com/qt/qtbase/commit/e1a787a76ed462e4ed49db78a40c6d7e272182d7)). I think for us, we should patch it to use the old `system_forkfd` instead. 

FYI, this problem seems to occur in runtime depending on the kernel version: 

| Device | Arch | Android | Linux | Build | `strace` `clone` flags | success? |
| - | - | - | - | - | - | - |
| Emulated | x86_64 | 14 | 6.1.23 | Qt6 | `CLONE_VM\|CLONE_PIDFD\|CLONE_VFORK\|SIGCHLD` | no |
| Emulated | x86_64 | 14 | 6.1.23 | Qt5 | `CLONE_PIDFD\|SIGCHLD` | yes |
| Emulated | x86_64 | 13 | 5.15.41 | Qt6 | `CLONE_VM\|CLONE_PIDFD\|CLONE_VFORK\|SIGCHLD` | no |
| Emulated | x86_64 | 13 | 5.15.41 | Qt5 | `CLONE_PIDFD\|SIGCHLD` | yes |
| Samsung Fold5 | x86_64 | 13 | 5.15.41 | Qt6 | `CLONE_VM\|CLONE_PIDFD\|CLONE_VFORK\|SIGCHLD` | no |
| Samsung Fold5 | x86_64 | 13 | 5.15.41 | Qt5 | `CLONE_PIDFD\|SIGCHLD` | yes |
| Emulated | x86 | 11 | 5.4.61 | Qt6 | `CLONE_VM\|CLONE_PIDFD\|CLONE_VFORK\|SIGCHLD` | no |
| Emulated | x86 | 11 | 5.4.61 | Qt5 | `CLONE_PIDFD\|SIGCHLD` | yes |
| Pixel 4a | aarch | 13 | 4.14.302 | Qt6 | `CLONE_CHILD_CLEARTID\|CLONE_CHILD_SETTID\|SIGCHLD` | yes |
| Pixel 4a | aarch | 13 | 4.14.302 | Qt5 | `CLONE_CHILD_CLEARTID\|CLONE_CHILD_SETTID\|SIGCHLD` | yes |
| Emulated | aarch | 9 | 4.4.124 | Qt6 | `CLONE_CHILD_CLEARTID\|CLONE_CHILD_SETTID\|SIGCHLD` | yes |
| Emulated | aarch | 9 | 4.4.124 | Qt5 | `CLONE_CHILD_CLEARTID\|CLONE_CHILD_SETTID\|SIGCHLD` | yes |
