### ISSUE TITLE
[Help] Cross compile `movit` (`shotcut` & `mlt` GPU deps), which can build on-device

### ISSUE THREAD

**Issue by knyipab** [termux/termux-packages#20351]
`movit`, which enables the GPU mode of `shotcut`, seems to require on device compilation (successful on device build shown in [this TUR PR](https://github.com/termux-user-repository/tur/pull/1054)). When building the package, it executes a compiled binary to generate .cpp file (see [the error log of this cross compile attempt](https://github.com/knyipab/tur/actions/runs/9288905494)). However, there does not seem to be on device build feature in this`termux-packages` repo, right? 

If `termux-packages` does not accpet on-device built package, there seems to be only four options: 
1. Someone figure out how to cross-compile movit 
2. Workaround to bring ondevice built packages to `termux-packages`
3. Give up and disable the `movit` GPU mode for `shotcut` and any `mlt`-dependent pacakges
4. Put `movit`, `shotcut` (and possibly `mlt`) to TUR

May I seek advice from the community? Thanks.

**Comment by Biswa96** [comment]
Yes, it may be possible to build with host program.

**Comment by TomJo2000** [comment]
1. Is definitely the preferred option.

2. I'm very reluctant to consider.
Building packages on-device is a last resort, and generally only acceptable for "simple" packages

3. If 1 doesn't work out I think this would be the preferred (interim) solution

4. That is always an option if the standard build infrastructure doesn't fit for shotcut.

**Comment by knyipab** [comment]
If someone want to try option 1, may continue the work at PR #20352. 

I will do option 3 for now. But fyi, there are still some issues regarding the `shotcut` package and I will open issue later.

**Comment by TomJo2000** [comment]
Bingo, found the issue.
The `make_bundled_shaders` helper binary is of course compiled for the target architecture.
Thus it can't be run during the build, but the build tries to run it.
Now if I can just find where it builds it...

**Comment by TomJo2000** [comment]
So, in theory yes.
In practice I've not sure how to get it to build `make_bundled_shaders` such that it can be run by the build system as a native executable (as opposed to the cross compilation target of the rest of the package)

**Comment by Biswa96** [comment]
For building `make_bundled_shaders` program, the host environment need eigen package.

**Comment by TomJo2000** [comment]
Hmm
