### ISSUE TITLE
cant apt update now

### ISSUE THREAD

**Issue by breadbread1984** [termux/termux-packages#2038]
apt update yields errors

> error:100be07e:SSL routines:ssl3_get_server_certificate:CERTIFICATE_VERIFY_FAILED

how to get rid of the error and update from repository again?

**Comment by Grimler91** [comment]
What's the content of $PREFIX/etc/apt/sources.list?

Do you have `apt-transport-https` installed?

**Comment by LaChirla** [comment]
Maybe OT, but I also cannot update - upgrade any more. 

--> apt update
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received a segmentation fault.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.

Thank you.

**Comment by Grimler91** [comment]
@LaChirla Try editing the url in $PREFIX/etc/apt/sources.list to use http instead of https. 
Hopefully you can then upgrade and hopefully https will work afterwards.

**Comment by breadbread1984** [comment]
@Grimler91 thx, mine is solved.
