### ISSUE TITLE
[Bug]: error when open terminal in ssh

### ISSUE THREAD

**Issue by chieonol** [termux/termux-packages#20391]
### Problem description

Report issues at https://termux.dev/issues
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.termux.termuxam.CrossVersionReflectedMethod.invoke(C
rossVersionReflectedMethod.java:175)
        at com.termux.termuxam.IActivityManager.startService(IActiv
ityManager.java:210)
        at com.termux.termuxam.Am.runStartService(Am.java:524)
        at com.termux.termuxam.Am.onRun(Am.java:355)
        at com.termux.termuxam.BaseCommand.run(BaseCommand.java:46)
        at com.termux.termuxam.Am.main(Am.java:74)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Nat
ive Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.jav
a:411)
Caused by: java.lang.NullPointerException
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3029
)
        at android.os.Parcel.createException(Parcel.java:3007)
        at android.os.Parcel.readException(Parcel.java:2990)
        at android.os.Parcel.readException(Parcel.java:2932)
        at com.android.internal.app.IAppOpsService$Stub$Proxy.repor
tRuntimeAppOpAccessMessageAndGetConfig(IAppOpsService.java:1488)
        at android.app.AppOpsManager$1.reportStackTraceIfNeeded(App
OpsManager.java:291)
        at android.app.AppOpsManager$1.onNoted(AppOpsManager.java:2
66)
        at android.app.AppOpsManager.readAndLogNotedAppops(AppOpsMa
nager.java:9831)
        at android.os.Parcel.readExceptionCode(Parcel.java:2954)
        at android.os.Parcel.readException(Parcel.java:2929)
        at android.app.IActivityManager$Stub$Proxy.startService(IAc
tivityManager.java:6214)
        ... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.internal.util.AnnotationValidations.validate
(AnnotationValidations.java:129)
        at android.app.SyncNotedAppOp.<init>(SyncNotedAppOp.java:24
6)
        at android.app.SyncNotedAppOp$1.createFromParcel(SyncNotedA
ppOp.java:262)
        at android.app.SyncNotedAppOp$1.createFromParcel(SyncNotedA
ppOp.java:254)
        at android.os.Parcel.readTypedObject(Parcel.java:3959)
![Screenshot_20240601-153025](https://github.com/termux/termux-packages/assets/93561822/fd3f271d-5b86-43cc-acc7-dd657e264e9e)

### What steps will reproduce the bug?

Just connect via ssh

### What is the expected behavior?

No message

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=16117
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
apt/stable 2.7.12-2 aarch64 [upgradable from: 2.7.2]
bash-completion/stable 2.14.0 all [upgradable from: 2.11-2]
bash/stable 5.2.26-1 aarch64 [upgradable from: 5.2.15-1]
ca-certificates/stable 1:2024.03.11-2 all [upgradable from: 1:2023.
05.30]
command-not-found/stable 2.4.0-26 aarch64 [upgradable from: 2.2.0-9
]
coreutils/stable 9.5 aarch64 [upgradable from: 9.3]
curl/stable 8.8.0 aarch64 [upgradable from: 8.2.0]
debianutils/stable 5.17 aarch64 [upgradable from: 5.7-1]
dialog/stable 1.3-20240307-0 aarch64 [upgradable from: 1.3-20230209
-0]
dos2unix/stable 7.5.2 aarch64 [upgradable from: 7.5.0]
dpkg/stable 1.22.6 aarch64 [upgradable from: 1.21.22]
ed/stable 1.20.2 aarch64 [upgradable from: 1.19]
gawk/stable 5.3.0 aarch64 [upgradable from: 5.2.2]
gpgv/stable 2.4.5-1 aarch64 [upgradable from: 2.4.3]
gzip/stable 1.13 aarch64 [upgradable from: 1.12-1]
iperf3/stable 3.17.1 aarch64 [upgradable from: 3.13]
krb5/stable 1.21.2 aarch64 [upgradable from: 1.21]
libassuan/stable 2.5.7 aarch64 [upgradable from: 2.5.6]
libc++/stable 26b aarch64 [upgradable from: 25c]
libcap-ng/stable 2:0.8.5 aarch64 [upgradable from: 2:0.8.3]
libcurl/stable 8.8.0 aarch64 [upgradable from: 8.2.0]
libedit/stable 20240517-3.1-0 aarch64 [upgradable from: 20221030-3.
1-0]
libexpat/stable 2.6.2 aarch64 [upgradable from: 2.5.0-1]
libgcrypt/stable 1.10.3 aarch64 [upgradable from: 1.10.2]
libgmp/stable 6.3.0 aarch64 [upgradable from: 6.2.1-2]
libgnutls/stable 3.8.5 aarch64 [upgradable from: 3.8.0-1]
libgpg-error/stable 1.49 aarch64 [upgradable from: 1.47]
libidn2/stable 2.3.7 aarch64 [upgradable from: 2.3.4]
liblzma/stable 5.6.1+really5.4.5 aarch64 [upgradable from: 5.4.3]
libmpfr/stable 4.2.1 aarch64 [upgradable from: 4.2.0-p9-0]
libnghttp2/stable 1.62.1 aarch64 [upgradable from: 1.55.1]
libnpth/stable 1.6-2 aarch64 [upgradable from: 1.6-1]
libsmartcols/stable 2.39.3-4 aarch64 [upgradable from: 2.39.1]
libtirpc/stable 1.3.4-1 aarch64 [upgradable from: 1.3.3]
libunbound/stable 1.20.0 aarch64 [upgradable from: 1.17.1-2]
libuuid/stable 2.39.3-4 aarch64 [upgradable from: 2.39.1]
lsof/stable 4.99.3 aarch64 [upgradable from: 4.98.0]
nano/stable 8.0 aarch64 [upgradable from: 7.2]
ncurses-utils/stable 6.4.20231001-3 aarch64 [upgradable from: 6.4.2
0230527]
ncurses/stable 6.4.20231001-3 aarch64 [upgradable from: 6.4.2023052
7]
openssh-sftp-server/stable 9.7p1 aarch64 [upgradable from: 9.3p2]
openssh/stable 9.7p1 aarch64 [upgradable from: 9.3p2]
openssl/stable 1:3.2.1-1 aarch64 [upgradable from: 1:3.1.1]
pcre2/stable 10.43 aarch64 [upgradable from: 10.42]
procps/stable 3.3.17-5 aarch64 [upgradable from: 3.3.17-2]
proot-distro/stable 4.13.0-1 all [upgradable from: 3.17.0]
proot/stable 5.1.107-64 aarch64 [upgradable from: 5.1.107-60]
psmisc/stable 23.7 aarch64 [upgradable from: 23.6-1]
readline/stable 8.2.10 aarch64 [upgradable from: 8.2.1]
screen/stable 4.9.1 aarch64 [upgradable from: 4.9.0]
termux-am/stable 0.8.0 all [upgradable from: 0.4]
termux-keyring/stable 3.12 all [upgradable from: 3.11]
termux-tools/stable 1.42.2 all [upgradable from: 1.38.3]
unbound/stable 1.20.0 aarch64 [upgradable from: 1.17.1-2]
util-linux/stable 2.39.3-4 aarch64 [upgradable from: 2.39.1]
wget/stable 1.24.5 aarch64 [upgradable from: 1.21.4-1]
xz-utils/stable 5.6.1+really5.4.5 aarch64 [upgradable from: 5.4.3]
zlib/stable 1.3.1 aarch64 [upgradable from: 1.2.13]
zstd/stable 1.5.6 aarch64 [upgradable from: 1.5.5-1]
termux-tools version:
1.38.3
Android version:
13
Kernel build information:
Linux localhost 4.19.113-27166950 #1 SMP PREEMPT Tue May 14 14:41:1
1 KST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G981N
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.boot versionCode:7
com.termux.tasker versionCode:6
~ $
```

**Comment by agnostic-apollo** [comment]
You do not appear to be using official termux app and so we do not provide support.

However, update run `apt update; apt install termux-am termux-tools` to update required packages, which may fix your issue.

**Comment by chieonol** [comment]
Then, f-droid version app is not official?

> You do not appear to be using official termux app and so we do not provide support.
> 
> However, update run `apt update; apt install termux-am termux-tools` to update required packages, which may fix your issue.

Then f-droid version is not official? Should I need to re-install?

**Comment by agnostic-apollo** [comment]
Where did you install?

**Comment by agnostic-apollo** [comment]
Or is that image from some text editor?

**Comment by chieonol** [comment]
F droid. 
Screenshot is my ssh client named connectbot

**Comment by agnostic-apollo** [comment]
Ah, sorry, missed the title. Fdroid is fine.

**Comment by chieonol** [comment]
Problem is only once occurred.
So not critical.

**Comment by agnostic-apollo** [comment]
Update the packages as suggested.

**Comment by chieonol** [comment]
Ok ty
