### ISSUE TITLE
Package Request: Cap'n Proto

### ISSUE THREAD

**Issue by stschwar** [termux/termux-packages#2039]
Hey everyone.

I am pretty new to Termux and love it! For a personal project I would need assistance to build Cap'n Proto (C++) for the Termux shell: https://capnproto.org/

From the docs the build process seems pretty straightforward, but I have problems running the `./configure` step:

```
curl -O https://capnproto.org/capnproto-c++-0.6.1.tar.gz
tar zxf capnproto-c++-0.6.1.tar.gz
cd capnproto-c++-0.6.1
./configure
make -j6 check
sudo make install
```

Any help is appreciated!

**Comment by Grimler91** [comment]
@stschwar if you provide more information about how it failed when you configured it, we might be able to help.

**Comment by h4waii** [comment]
@stschwar

All this needs is `TMPDIR=./` to get passed that error. You have other issues to deal with afterwards though

`debug.c++:250:23: error: no viable overloaded '='`

**Comment by sdrausty** [comment]
>  pretty new to Termux and love it! 

Reverberating echo, printf yes.

**Comment by sdrausty** [comment]
Wadz Androidm

**Comment by xeffyr** [comment]
```
pkg install capnproto
```
