### ISSUE TITLE
[Bug]: postgresql: initdb: library "libicui18n.so.74" not found

### ISSUE THREAD

**Issue by rvalyi** [termux/termux-packages#20414]
### Problem description

I did a fresh termux installation,
Then pkg install postgresql
Then tried the initdb command and got:
CANNOT LINK EXECUTABLE "initdb": library "libicui18n.so.74" not found: needed by main executable

This is with the postgresql 16.2 package. Strangely pkg says it's the latest version available while I had the 16.3 version installed previously on another device and where initdb works...

Probably related to https://github.com/termux/termux-packages/issues/19879

### What steps will reproduce the bug?

>pkg install postgresql
>initdb
CANNOT LINK EXECUTABLE "initdb": library "libicui18n.so.74" not found: needed by main executable

### What is the expected behavior?

initdb should work and print the help message

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=8044
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.nguyenhoang.cloud/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.nguyenhoang.cloud/termux/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# root-repo (sources.list.d/root.list)
deb https://mirrors.nguyenhoang.cloud/termux/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.42.2
Android version:
14
Kernel build information:
Linux localhost 5.15.123-NinjaSU #1 SMP PREEMPT Wed May 29 23:10:03 UTC 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-X910
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
```

**Comment by TomJo2000** [comment]
https://github.com/termux/termux-packages/blob/7df74c2ed96e7271c03f24398af505ad90e63a75/packages/postgresql/build.sh#L1-L6
Your `postgresql` package is out of date.

Please update *all* of your packages using `pkg up`.
`termux-info` should have pointed this out, I am unsure why it did not.
It it quite possible the primary repository mirror you are using has not been synced.

**Comment by rvalyi** [comment]
Hello, thanks for the quick response.  In I just figured it out as well: I used termux-change-repo, selected all mirrors instead of south America previously and suddenly postgresql 16.3 was available. And yes it works as expected.
