### ISSUE TITLE
msf > db_status [*] postgresql selected, no connection

### ISSUE THREAD

**Issue by chemostafa** [termux/termux-packages#2042]
I search hard and I found a video in YouTube sya that solve the problem by this command

Commands for fixing error 
open termux first and use the following command 
1.mkdir -p $PREFIX/var/lib/postgresql
2.initdb $PREFIX/var/lib/postgresql
3.pg_ctl -D $PREFIX/var/lib/postgresql start
after that change your directory to metasploit-framework 
4.cd metasploit-framework 
./msfconsole 
............
So I do it and and get that :::;;
$ mkdir -p $PREFIX/var/lib/postgresql
$ initdb $PREFIX/var/lib/postgresql
The files belonging to this database system will be owned by user "u0_a166".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /data/data/com.termux/files/usr/var/lib/postgresql ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... sysv
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start

$pg_ctl -D $PREFIX/var/lib/postgresql start
waiting for server to start....2018-01-16 23:47:15.200 EET [11117] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2018-01-16 23:47:15.207 EET [11117] LOG:  listening on Unix socket "/data/data/com.termux/files/usr/tmp/.s.PGSQL.5432"
2018-01-16 23:47:15.271 EET [11121] LOG:  database system was shut down at 2018-01-16 23:44:00 EET
2018-01-16 23:47:15.391 EET [11117] LOG:  database system is ready to accept connections
 done
server started

…......and I run it ruby
$ ruby msfconsole

So I tray to do 
msf > db_status
[*] postgresql selected, no connection

😁😁😁 not solvedfiat I want know what I did ? Is this command I found in the YouTube is mean that person hack my cellphone or what 👀

**Comment by Atavic** [comment]
Look at [Connect to Database](https://wiki.termux.com/wiki/Metasploit_Framework) and the many issues referenced therein.

**Comment by chemostafa** [comment]
OK I did all this 
cd $HOME/metasploit-framework/config
curl -LO https://Auxilus.github.io/database.yml
mkdir -p $PREFIX/var/lib/postgresql
initdb $PREFIX/var/lib/postgresql
pg_ctl -D $PREFIX/var/lib/postgresql start
createuser msf
createdb msf_database

And I go to msf
msf > db_status
[*] postgresql connected to msf_database
Great all don't but how that happened?
My problem in this ( $path_to_db )
Whence I do 
msf > db_connect $path_to_db 
How i replaced $path_to_db  by my real path in the first case and that us was by
$ initdb ~/pg
$ pg_ctl -D ~/pg start
How I find the db real path in /pg ? Or in your Cass  /postgresql ?

**Comment by Atavic** [comment]
`/data/data/com.termux/files/usr/var/lib/postgresql` https://github.com/termux/termux-packages/issues/715#issuecomment-354640927

Also see: https://github.com/gushmazuko/metasploit_in_termux/blob/master/metasploit.sh

**Comment by chemostafa** [comment]
OK I do that
$ initdb ~/pg
$ pg_ctl -D ~/pg start
$ createuser msfpg
$ createdb msfpg_database
And I open msf 
msf > 
msf > db_connect /data/data/com.termux/files/home/pg
[*] Rebuilding the module cache in the background...
msf > db_status
[*] postgresql connected to data
Why it connect to name (data) ? Not pg or msfpg or msfpg_database ? 
Plz tell me I really want learn 😕

**Comment by Atavic** [comment]
I don't have it on my phone, sorry. Try asking [here](https://github.com/Hax4us/Metasploit_termux/)

**Comment by chemostafa** [comment]
OK thanks man 👍

**Comment by Atavic** [comment]
Welcome on Github!

**Comment by demokratlinux** [comment]
`msf > db_status`
[*] postgresql selected, no connection

`root@kali:~# msfdb reinit`
[i] Database already started
psql: could not connect to server: No such file or directory`enter code here`
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

`root@kali:~# nano /etc/postgresql/10/main/postgresql.conf`
listen_addresses = '*'
port = 5432   (I tried 5433)
and
`root@kali:~# cd /usr/share/metasploit-framework/config/` (tried 5433)

`root@kali:~# nano /etc/postgresql/10/main/pg_hba.conf`
local   all             all                                     peer
host    all             all             0.0.0.0/0            md5
host    all             all             all                  md5
host    all             all             ::1/128                 md5
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
host    all             all             all                     md5

root@kali:~# msfconsole
[-] Failed to connect to the database: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

What else can I do? thanks for the help

**Comment by saggyballs** [comment]
Same damn problem i dont know how to edit the server i want to connect to or how to dump the directory

**Comment by elogada** [comment]
Have you guys tried connecting the database first? Metasploit tries its best to be manually operated a lot (which is why they have support for custom scripts).

Try
`````
$ msfconsole
msf> db_connect msf_database
`````
I suggest you read up on the docs of how to use msf before using it on your phone. It's not native to Android, more of for Debian. You can expect a lot to fail (especially port problems, unless you're root). Iirc Android doesn't have the capacity to edit TCP packets, for example (whether available when jailbroken idk).

**Comment by reksores** [comment]
$ postgres -D nameofdatabase

**Comment by work-2020** [comment]
try `msfdb reinit`
I'm OK

**Comment by infraredracoon1** [comment]
https://github.com/infraredracoon1/m-wiz
To install 
1. mkdir -p $PREFIX/var/lib/postgresql
2. initdb $PREFIX/var/lib/postgresql
3. pg_ctl -D $PREFIX/var/lib/postgresql start
4. msfconsole
5. db_connect msf_database
I suggest u look up how to create a workspace 
 https://www.offensive-security.com/metasploit-unleashed/using-databases/
