### ISSUE TITLE
VPN server 

### ISSUE THREAD

**Issue by Blackhat4hacker1** [termux/termux-packages#20434]
### Problem description

Warning: localhost:1 is taken because of /data/data/com.termux/files/usr/tmp/.X1-lock
Remove this file if there is no X server localhost:1

New 'localhost:4 ()' desktop is localhost:4

Starting applications specified in /data/data/com.termux/files/home/.vnc/xstartup
Log file is /data/data/com.termux/files/home/.vnc/localhost:4.log

### What steps will reproduce the bug?

Warning: localhost:1 is taken because of /data/data/com.termux/files/usr/tmp/.X1-lock
Remove this file if there is no X server localhost:1

New 'localhost:4 ()' desktop is localhost:4

Starting applications specified in /data/data/com.termux/files/home/.vnc/xstartup
Log file is /data/data/com.termux/files/home/.vnc/localhost:4.log

### What is the expected behavior?

Warning: localhost:1 is taken because of /data/data/com.termux/files/usr/tmp/.X1-lock
Remove this file if there is no X server localhost:1

New 'localhost:4 ()' desktop is localhost:4

Starting applications specified in /data/data/com.termux/files/home/.vnc/xstartup
Log file is /data/data/com.termux/files/home/.vnc/localhost:4.log

### System information

```shell
Warning: localhost:1 is taken because of /data/data/com.termux/files/usr/tmp/.X1-lock
Remove this file if there is no X server localhost:1

New 'localhost:4 ()' desktop is localhost:4

Starting applications specified in /data/data/com.termux/files/home/.vnc/xstartup
Log file is /data/data/com.termux/files/home/.vnc/localhost:4.log
```

**Comment by TomJo2000** [comment]
A VNC Server is not a VPN, what is the issue you are actually having?
If there is a leftover lockfile at `/data/data/com.termux/files/usr/tmp/.X1-lock` but that X server is not running anymore,
I'd say you should follow the suggestion of the warning and delete the leftover lockfile.

You just put in the same truncated error message 4 times, what do you expect us to do with that?
