### ISSUE TITLE
[Bug]: Darktable fails to open, "libicui18n.so.74" not found

### ISSUE THREAD

**Issue by wakearray** [termux/termux-packages#20438]
### Problem description

Darktable fails to open.

When launching Darktable in xfce4 running in the native Termux environment, the following error occurs:
```bash
CANNOT LINK EXECUTABLE "darktable": library "libicui18n.so.74" not found: needed by /data/data/com.termux/files/usr/lib/darktable/libdarktable.so in namespace (default)
```

### What steps will reproduce the bug?

Run the following commands in shell:
1. `pkg update`
1. `pkg install darktable`
1. `darktable`

### What is the expected behavior?

That Darktable will open.

### System information

```shell
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~qvAdMuM6dswQnChJdE1pRQ==/com.termux-AKiMe3BxNyS7nzBo-BXU6w==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=9589
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c141,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c141,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10397
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
# glibc-repo (sources.list.d/glibc.list)
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
Updatable packages:
All packages up to date
termux-tools version:
1.42.2
Android version:
14
Kernel build information:
Linux localhost 6.1.25-android14-11-28243294-abS928USQS2AXD3 #1 SMP PREEMPT Tue Apr 30 09:46:32 UTC 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S928U1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.x11 versionCode:14
com.termux.api versionCode:51
com.termux.boot versionCode:7
com.termux.styling versionCode:30
```

**Comment by TomJo2000** [comment]
Hi, thanks for the bug report.
`darktable` is packaged in the Termux User Repository, not the main repo.
Thus it wasn't caught for rebuilding against `libicu 75.1`.

I'll kick off a rebuild of it on the TUR, but this issue is unrelated to the main repository besides the Libicu update necessitating a rebuild of the `darktable` package in the TUR.

**Comment by wakearray** [comment]
Ah, sorry, I forgot that the TUR is unrelated to the main packages repo. Thanks for taking care of it!

**Comment by TomJo2000** [comment]
I can't actually tell how `darktable` is depending on `libicu`.
Neither it, nor any depdency of it seems to depend on libicu.

**Comment by wakearray** [comment]
I don't know if this needs further investigation. Should I open this as an issue on the TUR GitHub page?

**Comment by TomJo2000** [comment]
I'm rebuilding the package locally right now, I'll open a pull request on the TUR shortly

**Comment by wakearray** [comment]
> `libicu` was pulled in as a dependency for the build, but I'm still unsure by what.

Looks like Darktable uses it in [their SQLite](https://github.com/darktable-org/darktable/blob/2347e678b3990e89b817703aa1b86813ae27087f/src/common/sqliteicu.c#L507) build to enable some regex and case matching functions.

**Comment by TomJo2000** [comment]
Should be closed by:
- termux-user-repository/tur#1066
