### ISSUE TITLE
[Bug]:  ./build-package.sh glib  or ./build-package.sh gobject-introspection  or ./build-package.sh python-pip

### ISSUE THREAD

**Issue by CloudControlPro** [termux/termux-packages#20447]
### Problem description

Unable to build Python-pip

![Snipaste_2024-06-08_00-59-26](https://github.com/termux/termux-packages/assets/154424640/46fa3fa7-68e9-4622-8a85-e7fa2e31e409)

### What steps will reproduce the bug?

./build-package.sh python-pip
./build-package.sh glib 
./build-package.sh gobject-introspection

### What is the expected behavior?

Can successfully build Python-pip

### System information

```shell
termux - building glib for arch aarch64...
Applying patch: *.patch.beforehostbuild
Applying patch: gio-gdbusprivate.c.patch
Applying patch: gio-gkeyfilesettingsbackend.c.patch
Applying patch: gio-gnetworking.h.in.patch
Applying patch: gio-gunixmounts.c.patch
Applying patch: gio-xdgmime-xdgmime.c.patch
Applying patch: glib-gcharset.c.patch
Applying patch: glib-gspawn.c.patch
Applying patch: glib-gthread-posix.c.patch
Applying patch: glib-gthreadprivate.h.patch
Applying patch: glib-gtimezone.patch
Applying patch: glib-gtypes.h.patch
Applying patch: glib-gutils.c.patch
Applying patch: glib-tests-meson.build.patch
Applying patch: meson.build.patch
sed: can't read /data/data/cn.mucute.merinal/files/usr/lib/pkgconfig/gobject-introspection-1.0.pc: No such file or directory
```

**Comment by TomJo2000** [comment]
Builds fine from the latest commit on the master branch.
We can't help with issues related to forks of the Termux app.

**Comment by Biswa96** [comment]
There are two similar issues. I have added that line in glib build script. There is a circular dependency between glib and gobject-introspection. It could be fixed by building gobject-introspection in glib as similas as Alpine Linux did https://git.alpinelinux.org/aports/tree/main/glib/APKBUILD. That would increase build time. I could try to solve that if increased build time is allowed.

**Comment by TomJo2000** [comment]
> There are two similar issues. I have added that line in glib build script. There is a circular dependency between glib and gobject-introspection. It could be fixed by building gobject-introspection in glib as similas as Alpine Linux did https://git.alpinelinux.org/aports/tree/main/glib/APKBUILD. That would increase build time. I could try to solve that if increased build time is allowed.

`glib` is well below the CI runner limit, by all means go for it.

**Comment by CloudControlPro** [comment]
Who can give me specific steps to solve it?

**Comment by Biswa96** [comment]
Duplicate of #20070

If glib and gobject-introspection are in your repository add with `-I` option with build-packages.sh command to prevent recompiling dependencies.

If glib and gobject-introspection does not present in your repository you have to follow some steps to bootstrap glib and gojbect-introspection (GI). See https://gitlab.gnome.org/GNOME/glib/-/blob/2.80.0/docs/reference/glib/building.md?ref_type=tags

1. Build glib using `-Dintrospection=disabled` option.
2. Build GI using glib from step1.
3. Build glib with `-Dintrospection=enabled` using GI from step2.

**Comment by truboxl** [comment]
Since they are building for a custom prefix `cn.mucute.merinal`, `-I` option will not work.
