### ISSUE TITLE
gcc/clang compatibility with AndroidStudio 

### ISSUE THREAD

**Issue by darkoverlordofdata** [termux/termux-packages#2045]
When I compile a library made in c/cpp using Android Studio 3  and ndk-build, and then download that library to android, and link against it in termux using gcc, I get this error:

> /system/lib64/libbcinfo.so: undefined reference to `vtable for llvm::VAArgInst' 

It appears that gcc in termux is really a link to clang, so I'm not sure why this is happening.

**Comment by xeffyr** [comment]
Yes, in termux gcc is link to clang.
