### ISSUE TITLE
hacked/selinux or something else?

### ISSUE THREAD

**Issue by MidnightRaven907** [termux/termux-packages#20456]
/data/data/com.termux/files/usr/bin/termux-setup-storage: line 31: 32029 Aborted                 am broadcast --user "$TERMUX__USER_ID" --es com.termux.app.reload_style storage -a com.termux.app.reload_style com.termux > /dev/null

**Comment by 2096779623** [comment]
apt upgrade termux-am

**Comment by 2096779623** [comment]
Duplicate of https://github.com/termux/termux-app/issues/3647 .
