### ISSUE TITLE
tsu permission denied when executing command

### ISSUE THREAD

**Issue by rafinetiz** [termux/termux-packages#2047]
I already granted  supersu permission..

![screenshot_2018-01-18-15-27-10](https://user-images.githubusercontent.com/14245406/35088104-1e33e3ca-fc65-11e7-9062-20bac3118258.png)

As you can see in images.
Only a few commands can be run.

Termux ver. : 0.59
Android ver. : 5.1.1
Root type: Systemless root

**Comment by xeffyr** [comment]
If commands not working under superuser, then this may be a SELinux issue.

**Comment by rafinetiz** [comment]
So, how to fix this?

**Comment by Grimler91** [comment]
I've experienced this on several devices/ROMs. I use this script on my tablet instead of tsu:
```
$ more ~/bin/SU
export PATH=/system/bin/:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
/system/xbin/su --preserve-environment -c "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
```
Replace /system/xbin/su with the path to your su binary obviously. 

Haven't investigated further.

@xeffyr:
```
$ /system/bin/getenforce
Enforcing
```
(as root: `bash: /system/bin/getenforce: Permission denied`)

**Comment by xeffyr** [comment]
> $ /system/bin/getenforce
> Enforcing

This may be the source of 'permission denied' error. It is possible to restrict permissions of root user with selinux policy.

**Comment by Atavic** [comment]
If Grimler91 solution works, that's a :+1:

Sometimes Custom ROM devs tell people to change SELinux options to Permissive Mode and that's really a bad idea.

**Comment by Grimler91** [comment]
@Atavic I don't think it's the proper way to solve the problem though. I've revised the script a bit, no need to export vars before (and LD_LIBRARY_PATH wasn't preserved for some reason).

**Comment by Grimler91** [comment]
I believe it would better to move this issue to https://github.com/cswl/tsu

**Comment by Harshiv-Patel** [comment]
I face a "permission denied"  issue as well:

`$ tsu
$ ls
bash: /data/data/com.termux/files/usr/bin/ls: Permission denied         
$ env
bash: /data/data/com.termux/files/usr/bin/env: Permission denied

The Shell prompt is ( possibly other environment variables too)  preserved, with color.
Rooted with Magisk v16.
Running Android Lollipop 5.1.1
CPU arch : armv7l.

**Comment by rafinetiz** [comment]
@Harshiv-Patel show the output of `/system/bin/getenforce`

**Comment by helmut72** [comment]
Me too:

> $ /system/bin/getenforce
> CANNOT LINK EXECUTABLE "/system/bin/getenforce": cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib64/libselinux.so"...

**Comment by xeffyr** [comment]
@helmut72 Use `LD_LIBRARY_PATH=  /system/bin/getenforce`

![screenshot_20180818-124700_termux](https://user-images.githubusercontent.com/25881154/44298075-42feb780-a2e5-11e8-980b-9e3a82941b79.jpg)

**Comment by helmut72** [comment]
Thanks, getenforce shows now a proper output. But tsu still doesn't work.

> $ LD_LIBRARY_PATH= /system/bin/getenforce
> Enforcing
> $ tsu
> /data/data/com.termux/files/usr/bin/tsu: 139: exec: : Permission denied

**Comment by Grimler91** [comment]
@helmut72 update your magisk, if you are using magisk

**Comment by Harshiv-Patel** [comment]
@rafinetiz , the output of `getenforce` is "enforcing" only. : 
![screenshot_2018-08-20-08-12-25-1](https://user-images.githubusercontent.com/25936599/44317924-3a2af480-a451-11e8-8bda-fe368e86356c.png)

I am running on stock ROM of Samsung SM-E700H device (arm) if that could help.
Rooted with Magisk v16

**Comment by Grimler91** [comment]
@Harshiv-Patel Magisk v16.0 was released in February. Update your magisk.

**Comment by Harshiv-Patel** [comment]
AFAIK v1600 is latest stable version of Magisk.

**Comment by Grimler91** [comment]
Weird, there are newer releases available at the [github page](https://github.com/topjohnwu/Magisk/releases) at least.

**Comment by Harshiv-Patel** [comment]
Updated Magisk to beta v16.71 through Magisk Manager (which I didn't really expect to fix the issue). No change is observed. Issue persists.

**Comment by Grimler91** [comment]
@Harshiv-Patel alright, thanks for checking!

**Comment by rafinetiz** [comment]
> @xeffyr 
This may be the source of 'permission denied' error. It is possible to restrict permissions of root user with selinux policy.

He's right, you all need to change the current state of Enforcing status to Permissive Mode.
And now tsu is work perfectly in my device after changing Enforcing status to Permissive Mode.
Of course i'm using a custom rom to enabled this feature.

**Comment by haxersworld** [comment]
I'm thinking this could be a kernel issue on our phones Sammy S7 here 8.0 with noway to setenforce to permissive might try a new rom and kernel. I really don't want to however this is my last resort in  trying to correct the error 32/64 bit to unset LD_PRELOAD works = permission Denied....

**Comment by Austcool-Walker** [comment]
I also have this problem on a Samsung Galaxy Tab A 8.0 (2017) with the tsu package and I need tsu to work so I can gain temp root over the device so I can use termux bash as root on my tablet so archlinux trizen can execute with sudo support. so so example ```tsu bash startarch``` then in side proot ```trizen -S mcpelauncher-linux``` then it will prompt for sudo and it will work.

**Comment by Austcool-Walker** [comment]
also we need to find a work around this worked fine before the Oreo update (`8.1.1`). I read an portal post on XDA developers it said that Samsung was trying to patch spector and meltdown and downgrading is not possable I have tried

**Comment by Grimler91** [comment]
@austcool-walker use `tsu -a`, that preserves the environment variables and should fix the permission denied error

**Comment by Austcool-Walker** [comment]
My issue is the program gets killed by something

**Comment by Austcool-Walker** [comment]
It gets killed on the SM-T380 I'm rooted with magisk

**Comment by Austcool-Walker** [comment]
For me the problem is solved my issues were because of Samsung Defex security in the kernel going to https://opensource.samsung.com and requesting the kernel source code and building with the Defex disabled in defconfig fixed my problems

**Comment by tanujtyagi104** [comment]
Tsu permission decline
![Screenshot_2020-04-09-03-24-15-170_com termux](https://user-images.githubusercontent.com/57852233/78837471-c799ce80-7a11-11ea-8dcd-7b1709fdb986.jpg)

**Comment by WonderKruger** [comment]
> su tsu

Solved this problem for me
