### ISSUE TITLE
[Bug]: transmission-daemon segfault

### ISSUE THREAD

**Issue by Daniel6372** [termux/termux-packages#20490]
### Problem description

```
~ $ transmission-daemon -f --log-level=error
connect: Connection timed out
Segmentation fault
~ $
```

### What steps will reproduce the bug?

Install the transmission package and run transmission-daemon.
The segfault occurs within a few seconds.

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=26989
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://md.mirrors.hacktegic.com/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.42.4
Android version:
13
Kernel build information:
Linux localhost 4.4.302-PixelExperience-g7e5857d26436 #1 SMP PREEMPT Fri Jan 26 08:02:45 UTC 2024 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 7
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Daniel6372** [comment]
Running transmission-daemon with no internet makes the segfault not occur, and after reconnecting to internet it keeps working fine. Even downloading a torrent was successful.
So, for some reason, it runs fine as long as it doesn't have internet access immediately.

**Comment by Daniel6372** [comment]
Looks like this happens when `port-forwarding-enabled` is set to `true` in `~/.config/transmission-daemon/settings.json`.
If it's set to false, it runs as usual.

Transmission tries to open the port using UPnP, and then segfaults.

I tested this on Fedora as well, where Transmission prints the same `connect: Connection timed out` message, but doesn't segfault and everything appears normal.
It also successfully opened the port, so I'm not sure what the previous message really means.

**Comment by licy183** [comment]
I can't reproduce it.

**Comment by Daniel6372** [comment]
If you edit the config while the daemon is running, the changes get overwritten by the daemon on exit.

To make sure you're running with the correct settings, try: `transmission-daemon -f -m`.
Also make sure you have an active network connection. I only tested with Wi-Fi.

I tested with a second phone (Android 8), same result.

**Comment by fornwall** [comment]
@Daniel6372 Can you verify if version `4.0.6-1` of the `transmission` package (where #20788 was applied) fixes the problem for you?

**Comment by Daniel6372** [comment]
Yes, the issue is fixed. Thanks!
