### ISSUE TITLE
[Package]: Update epiphany to 46.1

### ISSUE THREAD

**Issue by kairusds** [termux/termux-packages#20509]
### Why is it worth to add this package?

There is a new stable update for the package.

### Source code URL

https://github.com/GNOME/epiphany/tree/46.1

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by twaik** [comment]
No need to ask about package update. We see all new versions of projects as soon as they are available. But we do not have enough people to package and distribute them. Pull requests are always welcome.
