### ISSUE TITLE
`sed` not support UTF-8?

### ISSUE THREAD

**Issue by agguser** [termux/termux-packages#2050]
`echo 'abc' | sed -r 's/.(.)./\1/'` returns `b`,
but `echo '一二三' | sed -r 's/.(.)./\1/'` returns `一二三`
(while in normal Linux, returns `二`)!

**Comment by its-pointless** [comment]
are you using the busybox default or the proper full version of sed? 
apt install sed

**Comment by agguser** [comment]
full `sed` (`which sed` returns `/data/data/com.termux/files/usr/bin/sed`)

**Comment by fornwall** [comment]
@agguser Can you try updating (`pkg up`) and see if the latest sed package version `4.4-1` fixes the problem?

I made no other change then rebuilding the package, but it seems to fix the problem for me.

**Comment by agguser** [comment]
It works! Thanks.
