### ISSUE TITLE
[Bug]: Expected absolute path for `SOURCE_DATE_EPOCH`

### ISSUE THREAD

**Issue by gouravkhunger** [termux/termux-packages#20559]
### Problem description

I am not sure if this is caused by `ruby`'s [`v3.3.2` bump](https://github.com/termux/termux-packages/commit/6c82e3d14b618e7dc37b32ff600cd13c228ecf10) or [`SOURCE_DATE_EPOCH` change](https://github.com/termux/termux-packages/commit/e2035b690aae0a5a4b337d87a9f53cac7efbab1d) in the build scripts.

I had a custom prefixed bootstrap with `ruby` `v3.2.2`. I used to be able to install and run gems, though it required [some patches](https://github.com/jekyllex/ruby-android/tree/ruby-test/patches) to make things work on the android 10 bootstrap.

But since upgrading the bootstrap to ruby `v3.3.2`, I get this error when trying to install gems that have native `C`/`C++` code:

```
...
/data/data/sh.gourav.jekyllex/files/usr/bin/ruby extconf.rb
error: expected absolute path: "{SOURCE_DATE_EPOCH="

extconf failed, exit code 1
...
```

For example, `gem install ffi` produces this output:

```
:/data/data/sh.gourav.jekyllex/files/home $ gem install ffi
Building native extensions. This could take a while...
ERROR:  Error installing ffi: ERROR: Failed to build gem native extension.                                                        
    current directory: /data/data/sh.gourav.jekyllex/files/usr/lib/ruby/gems/3.3.0/gems/ffi-1.17.0/ext/ffi_c/data/data/sh.gourav.jekyllex/files/usr/bin/ruby extconf.rb
error: expected absolute path: "{SOURCE_DATE_EPOCH="

extconf failed, exit code 1

Gem files will remain installed in /data/data/sh.gourav.jekyllex/files/usr/lib/ruby/gems/3.3.0/gems/ffi-1.17.0 for inspection.
Results logged to /data/data/sh.gourav.jekyllex/files/usr/lib/ruby/gems/3.3.0/extensions/aarch64-linux-android/3.3.0/ffi-1.17.0/gem_make.out
1|:/data/data/sh.gourav.jekyllex/files/home $
```

So does `nokogiri` `eventmachine`, `json` and other native gems.

Logs are not really helpful. Not sure if this is caused by the commits mentioned. I tried looking around through sources but haven't been able to find out the reason behind this.

### What steps will reproduce the bug?

I have these `PACKAGES` in my bootstrap:

```shell
PACKAGES+=("git")
PACKAGES+=("tar")
PACKAGES+=("dash")
PACKAGES+=("make")
PACKAGES+=("ruby")
PACKAGES+=("libxslt")
PACKAGES+=("libllvm")
PACKAGES+=("coreutils")
PACKAGES+=("pkg-config")
PACKAGES+=("binutils-libs")
```

The development tools are required to build native extensions for gems like `nokogiri`, `ffi`, `eventmachine`, etc., on device.

The bootstrap was built using:

```
./scripts/run-docker.sh ./clean.sh
./scripts/run-docker.sh ./scripts/build-bootstraps.sh --android10
```

### System information

```shell
:/data/data/sh.gourav.jekyllex/files/home $ ruby -v
ruby 3.3.2 (2024-05-30 revision e5a195edf6) [aarch64-linux-android]
:/data/data/sh.gourav.jekyllex/files/home $ gem -v
3.5.9
:/data/data/sh.gourav.jekyllex/files/home $ make -v
make: TMPDIR value /data/data/sh.gourav.jekyllex/files/usr/tmp: No such file or directory
make: using default temporary directory '/data/data/sh.gourav.jekyllex/files/usr/tmp/'
GNU Make 4.4.1
Built for aarch64-unknown-linux-android
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
:/data/data/sh.gourav.jekyllex/files/home $ clang -v
clang version 18.1.7
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/sh.gourav.jekyllex/files/usr/bin
```

**Comment by Biswa96** [comment]
`SOURCE_DATE_EPOCH` is an environment variable. From the error message, it seems that somehow `SOURCE_DATE_EPOCH` is added to a path or a command which is not correct.

**Comment by gouravkhunger** [comment]
Thanks for the insight @Biswa96. I was able to debug it and it turns out the issue was in a patch I created myself.
