### ISSUE TITLE
[Bug]: Android play market auto update fails

### ISSUE THREAD

**Issue by aegelsky** [termux/termux-packages#20561]
### Problem description

It's for week or more and still unable to install update for termux from android play market, it shows no error details except yellow triangle (!) and "update failed".

### What steps will reproduce the bug?

View updates available, try to update termux

### What is the expected behavior?

updated like all other apps

### System information

```shell
Xiaomi mi9tpro, miui 12.5.xx (latest available), android 11 (also latest available for it).
```

**Comment by twaik** [comment]
https://github.com/termux/termux-app/discussions/4000
