### ISSUE TITLE
[Package]: "xfce4-cpugraph-plugin" Package request

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#20571]
### Why is it worth to add this package?

`xfce4-cpugraph-plugin` is
You can monitor by CPU core in an XFCE4 session.

When build for Termux native
that XFCE4 desktop usability will be greatly improved.

Please review. 

:)

### Home page URL

https://docs.xfce.org/panel-plugins/xfce4-cpugraph-plugin/start

### Source code URL

https://github.com/frivoal/xfce4-cpugraph-plugin

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by twaik** [comment]
Closed by 5d1f392eb97f3b3cc5e828ff7da1223881caddaf
