### ISSUE TITLE
[Package]: "About xfce" System Add Update

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#20574]
### Why is it worth to add this package?

![Screenshot_2024-06-17_22-50-21](https://github.com/termux/termux-packages/assets/101167173/4625f857-ebcf-4ac7-b3b1-2617ab6ad79c)

When I run `About xfce` in `Termux XFCE4`, the `System` tab menu is not visible.

Could a `System` tab menu be added?

If you load system information with `neofetch` and `glxinfo -B` information values,
I think it will be a much more similar environment to a PC desktop.

![Debian1102](https://github.com/termux/termux-packages/assets/101167173/acf98988-f179-4b9a-bc82-0c2d52ac0412)

### Home page URL

https://github.com/xfce-mirror/

### Source code URL

https://github.com/xfce-mirror/xfce4-session

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by Biswa96** [comment]
I have added a pull request to add the feature. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/9623135281. Please install both libgtop and libxfce4ui packages from that artifact.

Here is the screenshot in my phone after installing those new packages.

![about-xfce](https://github.com/termux/termux-packages/assets/31443074/5152fa89-89b3-425a-a9e0-ce304ff8face)

**Comment by hansm629** [comment]
@Biswa96 

Thanks for the quick build! :)

Galaxy S23 Ultra (Snapdragon 8 Gen2 for Galaxy)
Galaxy Tab S9 Ultra (Snapdragon 8 Gen2 for Galaxy)
Galaxy S24+ (Exynos 2400)
Galaxy S24 Ultra (Snapdragon 8 Gen3 for Galaxy)

Tested on 4 models.

Most of the information was displayed well, but

All CPU entries are displayed as blank.

Could you please fix it?

![Screenshot_2024-06-23_01-20-36](https://github.com/termux/termux-packages/assets/101167173/f899531f-e1fd-4daa-ae67-638e4f72bf80)

**Comment by Biswa96** [comment]
CPU info is not shown in your neofetch output either. I'm not sure what the underlying issue in your case.

**Comment by hansm629** [comment]
@Biswa96
It seems to be the same thing happening to all SoCs released after `Snapdragon 888`. 
😢


Equipped with `Snapdragon 865`
Galaxy S20, Galaxy S22 Ultra
CPU information is displayed fine in `xfce4 about` and `neofetch`.


Is there a way to display at least the number of `CPU cores` like `neofetch`?

**Comment by hansm629** [comment]
@knyipab
Sir, hello.
I have a question for you.

Debian/Ubuntu Linux distribution 
For two packages: "xfce4-cpugraph-plugin" and "Task Manager"

- Snapdragon 8 Gen1
- Snapdragon 8 Gen2
- Snapdragon 8 Gen3
- Exynos 2200
- Exynos 2400

I couldn't load CPU information of the latest SoCs as above at all.
Thanks to this, it wasn't even monitored.

But the sir build it exclusively for Termux
CPU monitoring was successful for "`xfce4-cpugraph-plugin`" and "`Task Manager`".

Did you make a separate patch?

I think it's related to not being able to load CPU information on `xfce4 about`.

**Comment by knyipab** [comment]
I don't think your reported issue has nothing to do with that two mentioned packages. 

There does not seem to be any good way to detect CPU name on Android to patch it. Perhaps closest is using
```sh
getprop ro.hardware
getprop ro.board.platform
getprop ro.product.board
```
But that is not the common soc name, at least for my 8 gen 2, it is "qcom" "kalama".

**Comment by Biswa96** [comment]
libgtop is using /proc/cpuinfo which is readable in termux environment. I am not sure why it is not working in OP's system.

**Comment by knyipab** [comment]
Haven't tried your package, but that soc name feature seems unlikely work for my Samsung z fold 5 (8 gen 2), cuz `cat /proc/cpuinfo` print this (unlike Linux, no cpu name info shown, not sure vendor-specific or Android version specific): 
```
processor	: 0
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd46
CPU revision	: 1

processor	: 1
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd46
CPU revision	: 1

processor	: 2
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd46
CPU revision	: 1

processor	: 3
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd4d
CPU revision	: 0

processor	: 4
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd4d
CPU revision	: 0

processor	: 5
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x2
CPU part	: 0xd47
CPU revision	: 0

processor	: 6
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x2
CPU part	: 0xd47
CPU revision	: 0

processor	: 7
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint i8mm bf16 bti
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd4e
CPU revision	: 0
```

**Comment by hansm629** [comment]
@knyipab 
The result of entering the command is as follows.

![Screenshot_2024-06-23_03-44-21](https://github.com/termux/termux-packages/assets/101167173/e1304db0-f07c-440e-8add-9d142a35a753)


```
getprop ro.hardware
``` 
The above command doesn't seem to produce any special results.


Results of additional testing on the Galaxy S20 and Galaxy S20 Ultra equipped with Snapdragon 865, which I own.

The CPU information was displayed perfectly.

Hmm...what's the problem....

**Comment by knyipab** [comment]
@hansm629 you did not spell hardware correctly

**Comment by hansm629** [comment]
@Biswa96 
![Screenshot_2024-06-23_03-50-48](https://github.com/termux/termux-packages/assets/101167173/ca1ac089-ce08-4d1a-83e0-ea13b08665b7)

oh! Now that I typed it in correctly, it displays fine.
Even the SoC manufacturer name is clearly visible.


I also checked the CPU information using the cat /proc/cpuinfo command.
Starting with Snapdragon 8 Gen1, the CPU name is not displayed.
![Screenshot_2024-06-23_03-54-45](https://github.com/termux/termux-packages/assets/101167173/6788b899-72bd-4453-a0b5-d2482f128dcf)



but
Snapdragon 865 displayed well.

**Comment by Biswa96** [comment]
The following string is shown in CPU info in xfce-about in my phone.

```
$ head -n 1 /proc/cpuinfo
Processor       : AArch64 Processor rev 4 (aarch64)
```

**Comment by hansm629** [comment]
@Biswa96 @knyipab 

I tested it with the devices below that I currently own.

Galaxy S22 Ultra (Snapdragon 8 Gen1)
Galaxy Tab S9 Ultra (Snapdragon 8 Gen2 for Galaxy)
Galaxy S24+ (Exynos 2400)
Galaxy S24 Ultra (Snapdragon 8 Gen3 for Galaxy)

It seems that CPU information is not displayed at all.

![Screenshot_2024-06-23_04-01-55](https://github.com/termux/termux-packages/assets/101167173/1e50f2ac-fd4b-4991-971a-536b0ed3707f)



but
Interestingly, the Galaxy S20 and Galaxy S20 Ultra equipped with Snapdragon 865 are displayed well as shown below.

![Screenshot_20240623_040012_Termux](https://github.com/termux/termux-packages/assets/101167173/eda202bd-5521-4e22-82d9-79d0ffd08f72)

**Comment by licy183** [comment]
On some chips, `Hardware` section can be found in `/proc/cpuinfo`. If this section doesn't exist, reading chip model from `ro.hardware`/`ro.product.platform`/`ro.product.board` can also be used as a fallback option. If neither of them are available, it is also possible to get a dummy one from macros like `__aarch64__` .

I could implement it tomorrow. Feel free to do it if you want to. ~~I have to go to bed now, even though I haven't found the bug in my code yet.~~

**Comment by licy183** [comment]
Please test the debs in https://github.com/termux/termux-packages/actions/runs/9631439310. Thanks!

**Comment by Biswa96** [comment]
I have tested the artifact from that CI job. xfce-about shows same info as before.

**Comment by hansm629** [comment]
@licy183 @Biswa96 

- Galaxy Tab S9 Ultra (Snapdragon 8 Gen2 for Galaxy)
- Galaxy S24+ (Exynos 2400)

Tested on the two devices above.

The CPU entry now displays properly instead of being blank!

![Screenshot_2024-06-23_19-41-00](https://github.com/termux/termux-packages/assets/101167173/5031bed2-1160-48c3-b961-93b1a623e48a)
![Screenshot_2024-06-23_19-54-28](https://github.com/termux/termux-packages/assets/101167173/571bbe8c-a823-464c-b82f-730d36364bf4)






Is it possible to display the number of CPU cores as well?

`Qcom Kalama (8 core)`
`S5e9945 Erd9945 (10 core)`

Is it possible to implement it as shown above?

**Comment by licy183** [comment]
Please test the deb files in https://github.com/termux/termux-packages/actions/runs/9633235697. Thanks!

**Comment by hansm629** [comment]
@licy183 
![Screenshot_2024-06-23_21-11-28](https://github.com/termux/termux-packages/assets/101167173/93b2b029-3834-439b-b78b-f9e3cbffdb4e)
![Screenshot_2024-06-23_21-15-41](https://github.com/termux/termux-packages/assets/101167173/d0ab92f7-3013-4ad9-9134-6be010cffb8f)


The number of CPU cores is also displayed well!

It's perfect!
thank you!
