### ISSUE TITLE
sftp does not work under dropbear

### ISSUE THREAD

**Issue by Glushiator** [termux/termux-packages#2059]
I guess patching this:

#define SFTPSERVER_PATH "/usr/libexec/sftp-server"

to something like:

#define SFTPSERVER_PATH "@TERMUX_PREFIX@/usr/libexec/sftp-server"

should fix this... I would like to try sftp with dropbear.
Sftp with openssh does not work very well, openssh crashes frequently.

**Comment by fornwall** [comment]
Could you update to version `2017.75-2` of the dropbear package which has the `SFTPSERVER_PATH` patch and try it out?

**Comment by Glushiator** [comment]
Forgive me my ignorance, but how do I install a specific version?
pkg upgrade says that there is nothing to upgrade.

**Comment by Glushiator** [comment]
Ok, so I found how to, but no success:





*$ apt install dropbear=2017.75-2Reading package lists... DoneBuilding
dependency tree       Reading state information... DoneE: Version
'2017.75-2' for 'dropbear' was not found*











*$ pkg install dropbear=2017.75-2Hit:1 https://termux.net
<https://termux.net> stable InReleaseReading package lists... DoneBuilding
dependency tree       Reading state information... DoneAll packages are up
to date.Reading package lists... DoneBuilding dependency tree       Reading
state information... DoneE: Version '2017.75-2' for 'dropbear' was not
found*

On Wed, Jan 24, 2018 at 9:35 AM, Jaroslaw Marcin Iwanski <jmarcini@gmail.com
> wrote:

> Forgive me my ignorance, but how do I install a specific version?
> pkg upgrade says that there is nothing to upgrade.
>
> On Wed, Jan 24, 2018 at 9:27 AM, Fredrik Fornwall <

**Comment by Grimler91** [comment]
@Glushiator it was updated last hour or so, so `apt update && apt upgrade` should install it.

**Comment by Glushiator** [comment]
Thanks folks, installed the package.
SFTP works.
Will keep using to see if there are any stability issues.
