### ISSUE TITLE
[Package]: opendylan

### ISSUE THREAD

**Issue by cattokomo** [termux/termux-packages#20597]
### Why is it worth to add this package?

Dylan is an advanced, object-oriented, dynamic language which supports rapid program development.

### Home page URL

https://opendylan.org/

### Source code URL

https://github.com/dylan-lang/opendylan/

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [ ] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

The size of the compiler is about >100MB due to standard libraries,

**Comment by TomJo2000** [comment]
That's gonna be a [NACK](https://en.wikipedia.org/wiki/Acknowledgement_(data_networks)) from me.
- There's 2 packages.
One on the AUR and an outdated one on Nixpkgs
- The language basically does not exist outside of the `dylan-lang` org.
https://github.com/search?q=lang%3ADylan
- Excessive package size
