### ISSUE TITLE
[Bug]: xsltproc must be upgraded

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-packages#20607]
### Problem description

It looks like xsltproc is a libxslt subpackage. However it's still in old version (1.1.39) and requires that version of libxslt, but this package is in 1.1.40 version

Maybe it's some kind of Termux Build System bug, because not sure why xsltproc was not upgraded when libxslt was upgraded.

### What steps will reproduce the bug?

...

### System information

```shell
...
```

**Comment by Biswa96** [comment]
> However it's still in old version (1.1.39)

xsltproc is 1.1.40 version, see https://packages.termux.dev/apt/termux-main/pool/main/x/xsltproc/

**Comment by IntinteDAO** [comment]
@Biswa96 
Ok, it looks like termux.3san.dev repo is outdated
