### ISSUE TITLE
pip fails to upgrade packages

### ISSUE THREAD

**Issue by moises-santillan** [termux/termux-packages#2061]
I have termux on x86_64 and when I try to upgrade packages like pyzmq and matplotlib with pip, it fails with the following error:

CANNOT LINK EXECUTABLE "x86_64-linux-android-clang": library "libgcc_s.so.1" not found                                                                                    error: command 'x86_64-linux-android-clang' terminated by signal 6

Any help would be appreciated

**Comment by its-pointless** [comment]
Looks like you might be using my repo but haven't upgraded

**Comment by sdrausty** [comment]
@moises-santillan
 > Any help would be appreciated

Have you tried 
> packages like pyzmq and matplotlib with pip

in [Arch Linux Termux PRoot](https://sdrausty.github.io/TermuxArch/)?

**Comment by fornwall** [comment]
@moises-santillan Does updating packages to the latest versions with `pkg up` make a difference?

**Comment by xeffyr** [comment]
Seems fixed.
