### ISSUE TITLE
[Package]: Python v3.12.4

### ISSUE THREAD

**Issue by codenamedpkt** [termux/termux-packages#20654]
### Why is it worth to add this package?

We would like to update the package which make our workflow smoothly.

### Home page URL

https://python.org

### Source code URL

https://github.com/python/cpython/archive/v3.12.tar.gz

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by twaik** [comment]
No need to ask for package updates. We see all available newest versions as soon as they are published. But we do not have enough human resource to process them. Pull requests are always welcome.

**Comment by TomJo2000** [comment]
Already in progress
- #18078
