### ISSUE TITLE
Neovim fails to invoke TypeScript

### ISSUE THREAD

**Issue by mindbound** [termux/termux-packages#2067]
I have installed all of the following:

- Latest neovim with Python 2, Python 3, Ruby, and npm extensions;
- The [nvim-typescript](https://github.com/mhartington/nvim-typescript) plugin;
- TypeScript via `npm install -g typescript`;
- termux-exec.

When trying to open a .ts file, neovim throws the following error:
```
Error caught in async handler '/data/data/com.termux/files/home/.config/nvim/.cache/init.vim/.dein/rplugin/python3/nvim_typescript:function:TSOnBufEnter [[]]'
Traceback (most recent call last):
File "/data/data/com.termux/files/home/.config/nvim/.cache/init.vim/.dein/rplugin/python3/nvim_typescript/__init__.py", line 688, in on_bufenter
self.tsstart()
File "/data/data/com.termux/files/home/.config/nvim/.cache/init.vim/.dein/rplugin/python3/nvim_typescript/__init__.py", line 99, in tsstart
self._client.setTsConfig()
File "/data/data/com.termux/files/home/.config/nvim/.cache/init.vim/.dein/rplugin/python3/nvim_typescript/client.py", line 53, in setTsConfig
[command + ' --version'], shell=True)
File "/data/data/com.termux/files/usr/lib/python3.6/subprocess.py", line 336, in check_output
**kwargs).stdout
File "/data/data/com.termux/files/usr/lib/python3.6/subprocess.py", line 418, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['tsc --version']' returned non-zero exit status 127.
```

The `:CheckHealth` report has also the following:
```
ERROR: Command error (job=17): /data/data/com.termux/files/usr/bin/neovim-node-host --version
Output: sh: 1: /data/data/com.termux/files/usr/bin/neovim-node-host: not found
ERROR: Failed to run: /data/data/com.termux/files/usr/bin/neovim-node-host --version
```

Both `tsc --version` and `neovim-node-host --version` return correctly when called directly from command line.

I'm using latest Termux from F-Droid on Android 6.0.1, Galaxy Tab A SM-T550, ARM Cortex-A53 quad-core, ARMv8-A architecture. Please advise.

**Comment by Atavic** [comment]
Value 127 is returned because the given command is not found within your PATH
Maybe issue is that PATH isn't read by Python?

**Comment by mindbound** [comment]
How should I test for that and, if it turns out to be the case, what (if any) should I do to fix it?

**Comment by Atavic** [comment]
Hope this helps: https://github.com/termux/termux-packages/issues/1991

**Comment by mindbound** [comment]
I managed to solve the problem on my own. Turns out I had to manually add libtermux-exec.so to `LD_PRELOAD`.
