### ISSUE TITLE
[Bug]: zphisher dont give the url

### ISSUE THREAD

**Issue by NaofumiIwatan1** [termux/termux-packages#20676]
### Problem description

Hi, me and my friend cant do nothing with zphisher, the tool just give the second url and the second url is not working, hiw to fix it?
![Screenshot_20240625-194637_Termux](https://github.com/termux/termux-packages/assets/173866427/1fc2feb6-f7da-404c-9f89-b0ff5c675acb)

### What steps will reproduce the bug?

I dont know

### What is the expected behavior?

I need the 2 url

### System information

```shell
pkg install tur-repo
pkg install zphisher
zphisher
```

**Comment by twaik** [comment]
https://wiki.termux.com/wiki/Hacking
