### ISSUE TITLE
[Bug]: vlc H265/HEVC Performance

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#20671]
### Problem description

When playing `4K@30fps H265/HEVC video` using `vlc-qt`, the video screen is broken.

With the performance of the latest flagship SoC's CPU (`Snapdragon 8 Gen2`, `Exynos 2400`, `Snapdragon 8 Gen3`), playback would be sufficient without hardware decoding, but strangely, symptoms of screen crash are occurring separately from frame drops.

![Screenshot_2024-06-25_23-24-05](https://github.com/termux/termux-packages/assets/101167173/ef817284-6e67-4dc3-90a8-1275bcb18523)

Is it possible to fix the screen crash and performance above?

### What steps will reproduce the bug?

[4K@30fps H265/HEVC Sample](https://drive.google.com/file/d/1xsd4C7ZWpCncsYU5IZs5w0WMaU59SKvB/view?usp=sharing)

video sample above

On `Snapdragon 8 Gen2`, `Exynos 2400`, `Snapdragon 8 Gen3` host devices
Symptoms occur when playing through `vlc-qt`

`zink`, `virpipe`, `llvmpipe` are all the same

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18475
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.sjtu.edu.cn/termux/termux-main/ stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://mirror.sjtu.edu.cn/termux/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.4
Android version:
14
Kernel build information:
Linux localhost 6.1.43-android14-11-abS926NKSU2AXE4 #1 SMP PREEMPT Tue May 28 05:26:39 UTC 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S926N
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.x11 versionCode:14
com.termux.api versionCode:51
```

**Comment by DuilioPerez** [comment]
I've experienced using vlc-qt in termux and it's performance is very poor. Even without hardware acceleration firefox and mpv can play a video in a high framerate. I don't know why vlc-qt is slow in termux, but maybe is related to Qt, because firefox uses GTK and mpv uses SDL

**Comment by twaik** [comment]
Disable OpenGL rendering, enable X11/XCB rendering.

**Comment by twaik** [comment]
No need to compare. Just use this.
![image](https://github.com/termux/termux-packages/assets/9674930/da4dd256-0ea2-4132-ae3e-2ca3691b37fd)

**Comment by DuilioPerez** [comment]
> No need to compare. Just use this. ![image](https://private-user-images.githubusercontent.com/9674930/345890242-da4dd256-0ea2-4132-ae3e-2ca3691b37fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDkwNDUsIm5iZiI6MTcyMDEwODc0NSwicGF0aCI6Ii85Njc0OTMwLzM0NTg5MDI0Mi1kYTRkZDI1Ni0wZWEyLTQxMzItYWUzZS0yY2EzNjkxYjM3ZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMTU1OTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNlZWU3ZjFhZWE4ZjA2OTE0YzU4ODY1ZGQ5MjVlZDM5ZTZiNTk4MDk3YThlMTM3ZWFkMjUwY2VjMTdlMDAwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rY-lJAqM09tQy0-gpH-Mzmcjr7auBFeMTo89FoBklDE)

It worked, thanks. But why isn't this the default option?

**Comment by hansm629** [comment]
@twaik 
![Screenshot_2024-07-05_01-00-50](https://github.com/termux/termux-packages/assets/101167173/a5348710-1682-415d-bc14-cb4a8b25cebd)
![Screenshot_2024-07-05_01-01-20](https://github.com/termux/termux-packages/assets/101167173/a52aaf66-06eb-458c-bc0c-d6cf64078b85)


When set to `XVideo output (XCB)`
No video is displayed.




![Screenshot_2024-07-05_01-02-12](https://github.com/termux/termux-packages/assets/101167173/a0780350-7ab9-40e1-93b0-754b9ff559c0)
![Screenshot_2024-07-05_01-03-02](https://github.com/termux/termux-packages/assets/101167173/ad20faa1-5bf4-44a2-be52-10c213860a7c)

When set to `X11 Video output (XCB)`
Video is displayed, but the screen is still broken and performance is slow.



This is a `Snapdragon 8 Gen3` host device. (Galaxy S24 Ultra)

**Comment by twaik** [comment]
Try the X11 backend.

**Comment by hansm629** [comment]
@twaik 
![Screenshot_2024-07-05_01-03-02](https://github.com/termux/termux-packages/assets/101167173/df43c4d7-fb3a-4c35-ae09-59afd3bb1b22)


When set to `X11 Video output (XCB)`
Video is displayed, but the screen is still broken and performance is slow.

This is a `Snapdragon 8 Gen3` host device. (Galaxy S24 Ultra)

**Comment by hansm629** [comment]
@twaik 
![Screenshot_2024-07-05_01-15-36](https://github.com/termux/termux-packages/assets/101167173/9f09ea73-c06c-4ed6-a7a4-a694c7f5e6a2)
I tested it further

When playing via mpv
There doesn't seem to be any signs of screen cracking.

However, the performance was very slow.

When playing video in vlc-qt

`4K@60fps H.264/AVC1`
`4K@60fps VP9`

Everything plays well

Only `H265/HEVC` codec
`1080p@30fps` and `4K@30fps` are both very slow
Symptoms of screen cracking appear.

**Comment by IntinteDAO** [comment]
Well, 4K@30fps works slow even on my Ryzen CPU

Sadly Termux doesn't have Video Acceleration (vaapi)
