### ISSUE TITLE
Issues after upgrading to 119-beta.1 [openjdk?]

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#20683]
### Problem description

Starting Termux after the upgrading prints /data/.../profile.d/java.sh is a directory. Indeed java.sh is a symlink to a folder: $PREFIX/etc/alternatives/java-profile

I upgraded from FDROID, exactly from this package: https://f-droid.org/repo/com.termux_1020.apk.

All this on a tablet with android-11 os.

On a phone with android 8, the same apk does not produce issues!

NB. I already flagged this [here](https://github.com/termux/termux-app/issues/4033#issue-2373813539)

**Comment by angelog0** [comment]
On android 8 the symlink is something like this:

```
java.sh -> [...]/alternatives/java-profile
```

**Comment by angelog0** [comment]
On android 11 `[...]/alternatives/java-profile` is a symlink to `[...]/java-17-openjdk` directory and not to `[...]/java-17-openjdk/etc/profile.d/java.sh` file!

**Comment by Grimler91** [comment]
Seems to be typo/copy paste error in https://github.com/termux/termux-packages/commit/d539737ff5a304e86cd04188ba34517d51d19621 that I missed when reviewing
