### ISSUE TITLE
[Bug]: edit crontab

### ISSUE THREAD

**Issue by jd1900** [termux/termux-packages#20682]
### Problem description

First crontab install and edit is fine.

But trying to edit I get this error:
```
~ $ crontab -e
crontab: installing new crontab
/data/data/com.termux/files/home/.cache/crontab: mkdir: No such file or directory
```

### What steps will reproduce the bug?

Install crontab.
crontab -e
Edit again 

### What is the expected behavior?

Edit and work. 

### System information

```shell
Latest Android on Pixel 8 pro.
```

**Comment by tqfx** [comment]
```
mkdir ~/.cache
```

**Comment by jd1900** [comment]
Thank you. It works, but it shouldn't be the default behavior.

**Comment by tqfx** [comment]
See cronie-crond/cronie#173
