### ISSUE TITLE
add Java

### ISSUE THREAD

**Issue by magician333** [termux/termux-packages#207]
I hope termux could install Java

**Comment by fornwall** [comment]
Thanks for the suggestion - openjdk noted as a suggested package at https://termux.com/package-suggestions.html and will hopefully come in the future!

For now I'm closing this issue to avoid having open issues for all package suggestions.

**Comment by sdrausty** [comment]
@magician333     Java, javac and jar available through:
# [TermuxArch](https://github.com/sdrausty/TermuxArch)

Now you can install Arch Linux in Termux 📲 on your smartphone and tablet. More information at https://sdrausty.github.io/TermuxArch

Java is available through https://sdrausty.github.io/TermuxArch/ Just follow the easy install instructions at https://sdrausty.github.io/TermuxArch/docs/docs/install or simply copy and paste the following into your Termux window:

```
cd && git clone https://github.com/sdrausty/TermuxArch
./TermuxArch/setupTermuxArch.sh
```
Read more about the Arch Linux package manager at [duckduckgo arch+linux+install+java+pacman.](https://duckduckgo.com/?q=arch+linux+install+java+pacman&atb=v90-2__&t=cros&ia=qa)

To install java run `pacman -Syy; pacman -Su; pacman -S jdk8-openjdk`


![screenshot_20171109-220204](https://user-images.githubusercontent.com/27742457/32641053-cedfdcfe-c599-11e7-9c73-b185e70e9c6a.png)
![screenshot_20171109-222326](https://user-images.githubusercontent.com/27742457/32641590-d5541d4a-c59c-11e7-8855-e151bc217acc.png)
