### ISSUE TITLE
[Error when install library python]: 

### ISSUE THREAD

**Issue by kimyugiixyz** [termux/termux-packages#20714]
### Problem description

[termux-report_issue_from_transcript.log](https://github.com/termux/termux-app/files/15288150/termux-report_issue_from_transcript.log)

### Steps to reproduce the behavior.

pkg install python-cryptography
pkg install pycryptodome
pip install pillow

### System information

* Termux application version: 118
* Android OS version: 4.19.127+ / 11
* Device model: RMX3201

**Comment by Grimler91** [comment]
OP had issues with `pip install pillow`. It should work to install the packaged pillow instead: `pkg in python-pillow`
