### ISSUE TITLE
Devkitpro cross compilers and libraries

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-packages#20727]
### Why is it worth to add this package?

It would make developing for homebrew software for consoles easier its installer uses pacman manager and alias dkp-pacman. However I don't view this is an urgent package

### Home page URL

http://devkitpro.org/

### Source code URL

https://github.com/devkitPro/buildscripts

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

No root required may need a libc wrapper though, and cross prefixes

**Comment by Biswa96** [comment]
Those are just shell scripts and can be used as is.
