### ISSUE TITLE
[Package]: OCRMyPDF

### ISSUE THREAD

**Issue by khemarato** [termux/termux-packages#20726]
### Why is it worth to add this package?

It's a convenient utility for OCRing PDFs  Many times I'm reading a PDF on my phone and only realize it hasn't been OCRed when I go to copy and paste a quote from it. Being able to fix that on the fly would be convenient.

### Source code URL

https://github.com/ocrmypdf/OCRmyPDF

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [ ] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

Seeing as the underlying tesseract package already exists, it should hopefully not be too hard to add this wrapper! :fing

**Comment by khemarato** [comment]
I tried:

```
pkg install unpaper pngquant jbig2enc jbig2enc-static ghostscript tesseract
pip install ocrmypdf
```

And that worked to install it, but then it didn't run successfully (lots of errors and a garbage PDF on the other side)

**Comment by eelalzep** [comment]
`Building wheel for pi-heif (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pi-heif (pyproject.toml) did not run successfully.`

Any known solutions for this??
