### ISSUE TITLE
[Bug]: Password authentication in OpenSSH no longer works

### ISSUE THREAD

**Issue by sylirre** [termux/termux-packages#20758]
### Problem description

After last upgrade of `openssh` package, the password authentication appears to not working anymore.

I checked my `sshd_config` to be sure that it is enabled and it is.

I also compared `sshd` behavior from my backup and old version of OpenSSH worked fine with the same configuration. Below is the comparison.

Old version:

![Screenshot_20240701-173513_Termux](https://github.com/termux/termux-packages/assets/107305601/295b77f8-3106-4dcd-b427-f5669535c354)

After `apt update; apt full-upgrade; killall -9 sshd; sshd;`:

![Screenshot_20240701-173649_Termux](https://github.com/termux/termux-packages/assets/107305601/bf04e306-cc50-4881-9adc-3dff83729e9d)

### What steps will reproduce the bug?

1. Ensure PasswordAuthentication in `sshd_config` set to yes
2. Set new password: `passwd`, can enter something simple like `123` for testing.
3. Ensure that SSH server started with new configuration: `killall -9 sshd; sshd;`
4. Try connecting: `ssh -p 8022 localhost`, type your password into the prompt.

### What is the expected behavior?

When password is correct, `ssh` must display shell prompt.

If password not correct, a `permission denied` or something like should be displayed.

### System information

```shell
-
```

**Comment by tqfx** [comment]
`publickey` will work. You can use `publickey` instead of `password` for now.
