### ISSUE TITLE
[Bug]: cmus error opening audio device

### ISSUE THREAD

**Issue by terminatorbs** [termux/termux-packages#20773]
### Problem description

trying to start playback in cmus gives an error:

error: opening audio device: internal error

and no audio starts playing.

### What steps will reproduce the bug?

i havent changed anything in my termux and it used to work (has been broken for over a week at least though)
so i assume the issue will occur when simply installing cmus nornally. if not, please help me troubleshoot, i'm stuck.

### What is the expected behavior?

no error and music starts playing

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=19192
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/termux/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.42.4
Android version:
13
Kernel build information:
Linux localhost 5.4.219-qgki-g95eb98a8c435 #1 SMP PREEMPT Wed Apr 17 12:31:37 CST 2024 aarch64 Android
Device manufacturer:
Fairphone
Device model:
FP5
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Biswa96** [comment]
@pgaskin can this issue be closed now?

**Comment by pgaskin** [comment]
Possibly.

If @terminatorbs's error was due to pulseaudio failing to start, then yes, since we now have AAudio.

If pulseaudio started correctly, this is unusual, since pulseaudio always has at least a null sink even if there aren't any working real sinks.
