### ISSUE TITLE
ncurses url is giving 404 not found

### ISSUE THREAD

**Issue by mklein994** [termux/termux-packages#2077]
~~The `ncurses` package is using a url that is not stable; it's tracking `/current/`. This should be locked in at a specific version.
https://github.com/termux/termux-packages/blob/26bee40fbfd0cccf6803f83c7e40fec8afb68973/packages/ncurses/build.sh#L5~~

**Comment by mklein994** [comment]
Actually, it seems that http://invisible-mirror.net doesn't keep packages for very long; the version this one is referring to has disappeared.

cc @fornwall

**Comment by fornwall** [comment]
@mklein994 Thanks! I've switched to a mirror (https://bintray.com/termux/upstream) that keeps packages around for as long as Termux needs them.
