### ISSUE TITLE
squid -z

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#2078]
`squid -z` produces: 
```
squid -z
2018/01/31 00:41:28 kid1| Set Current Directory to /data/data/com.termux/files/usr/var/cache/squid
2018/01/31 00:41:28 kid1| Creating missing swap directories
2018/01/31 00:41:28 kid1| No cache_dir stores are configured.
```

`squid.conf` has the following defined:
```
cache_dir ufs /data/data/com.termux/files/usr/var/cache/squid 100 16 256
```

The output is a little bit different in [Arch Linux](https://sdrausty.github.io/TermuxArch/) in [Termux PRoot](https://github.com/termux/proot):
```
squid -z
FATAL: Ipc::Mem::Segment::create failed to shm_open(/squid-cf__metadata.shm): (13) Permission denied
```

Suggestions how to use a caching proxy, not necessarily Squid, in Termux are welcome.

**Comment by xeffyr** [comment]
Disk-based cache is unsupported since requires XSI message queue support in libc/kernel. Option `cache_dir` will not work.
