### ISSUE TITLE
Patch to add "zip" to setup-ubuntu.sh in support of openjdk-9-jre-headless

### ISSUE THREAD

**Issue by PaulAtBanno** [termux/termux-packages#2080]
[0001-Add-zip-to-setup-ubuntu.sh-in-support-of-openjdk-9-j.patch.zip](https://github.com/termux/termux-packages/files/1682573/0001-Add-zip-to-setup-ubuntu.sh-in-support-of-openjdk-9-j.patch.zip)

As of yesterday on the master branch, at least, this allows:

`./scripts/run-docker.sh ./build-package.sh -a i686 -D openjdk-9-jre-headless`

to succeed, given a rebuild of the `termux/package-builder:latest` image in Docker.

I would suggest doing tests of builds of all of the platforms for the OpenJDK package and, if they're successful, promoting the package from `disabled-packages`. There doesn't appear to be a good reason to leave it there, since 1) JDK 9 is in formal release, and 2) successfully building it appears to be trivial.

**Comment by its-pointless** [comment]
Issue is its still very buggy once installed.

**Comment by xeffyr** [comment]
Packages are easily installable via `apt` in the build environment. Also we trying to keep bare minimum used for packages from https://github.com/termux/termux-packages/tree/master/packages, so dependencies for disabled packages are ignored.

Closing.
