### ISSUE TITLE
Supertuxkart

### ISSUE THREAD

**Issue by EDLLT** [termux/termux-packages#20801]
### Why is it worth to add this package?

Biswa96 claims to have already compiled it and I'm opening this issue at his request to discuss over some things. 

STK would be a nice addition to the list of available termux packages.

### Home page URL

https://supertuxkart.net/Main_Page

### Source code URL

https://github.com/supertuxkart/stk-code/

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
We have the template for a reason.
Please fill out the info accurately.

**Comment by TomJo2000** [comment]
I've updated the project homepage and source repository in the template.

**Comment by Biswa96** [comment]
I have compiled the package in my system. The package size is 617 MB. It could be added in this main repository if the package is split into binary and data files - user can download data files from supertuxkart git repository. Or, would it be possible to add the package in TUR? I am not familiar with the packaging rules in TUR.

**Comment by TomJo2000** [comment]
It wouldn't be the largest package we have.
(I think that distinction goes to `helix`)
But it would probably need signoff from the infrastructure team.

**Comment by EDLLT** [comment]
> I've updated the project homepage and source repository in the template.

Apologies, sleep deprivation had hindered my thought process while making this

**Comment by IntinteDAO** [comment]
Well, supertux also works.

However I think the games should be in TUR repository
