### ISSUE TITLE
[Bug]: Build gdb

### ISSUE THREAD

**Issue by CloudControlPro** [termux/termux-packages#20817]
### Problem description

local void bi_windup(s)
           ^
20 warnings generated.
  CC       libz_a-uncompr.o
/home/builder/.termux-build/gdb/src/zlib/uncompr.c:27:13: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
int ZEXPORT uncompress2 (dest, destLen, source, sourceLen)
            ^
/home/builder/.termux-build/gdb/src/zlib/uncompr.c:86:13: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
int ZEXPORT uncompress (dest, destLen, source, sourceLen)
            ^
2 warnings generated.
  CC       libz_a-zutil.o
/home/builder/.termux-build/gdb/src/zlib/zutil.c:133:22: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
const char * ZEXPORT zError(err)
                     ^
/home/builder/.termux-build/gdb/src/zlib/zutil.c:305:22: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
voidpf ZLIB_INTERNAL zcalloc (opaque, items, size)
                     ^
/home/builder/.termux-build/gdb/src/zlib/zutil.c:315:20: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
void ZLIB_INTERNAL zcfree (opaque, ptr)
                   ^
3 warnings generated.
22 warnings generated.
true "AR_FLAGS=rc" "CC_FOR_BUILD=gcc" "CFLAGS=-fstack-protector-strong -Oz    " "CXXFLAGS=-fstack-protector-strong -Oz    " "CFLAGS_FOR_BUILD=" "CFLAGS_FOR_TARGET=-g -O2  -fstack-protector-strong -Oz" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "LDFLAGS=-L/data/data/com.Cloudcontrol.script/files/usr/lib -Wl,-rpath=/data/data/com.Cloudcontrol.script/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now /home/builder/.termux-build/_cache/android-r26b-api-24-v4/lib/clang/17/lib/linux/libclang_rt.builtins-aarch64-android.a" "LIBCFLAGS=-fstack-protector-strong -Oz  " "LIBCFLAGS_FOR_TARGET=-g -O2  -fstack-protector-strong -Oz" "MAKE=make" "MAKEINFO=makeinfo --split-size=5000000 --split-size=5000000 " "PICFLAG=" "PICFLAG_FOR_TARGET=" "SHELL=/bin/bash" "EXPECT=expect" "RUNTEST=runtest" "RUNTESTFLAGS=" "exec_prefix=/data/data/com.Cloudcontrol.script/files/usr" "infodir=/data/data/com.Cloudcontrol.script/files/usr/share/info" "libdir=/data/data/com.Cloudcontrol.script/files/usr/lib" "prefix=/data/data/com.Cloudcontrol.script/files/usr" "tooldir=/data/data/com.Cloudcontrol.script/files/usr/aarch64-linux-android" "AR=llvm-ar " "AS=aarch64-linux-android-clang" "CC=aarch64-linux-android-clang" "CXX=aarch64-linux-android-clang++" "LD=ld.lld" "LIBCFLAGS=-fstack-protector-strong -Oz  " "NM=llvm-nm" "PICFLAG=" "RANLIB=llvm-ranlib " "DESTDIR=" DO=all multi-do # make
  AR       libz.a
make[2]: Leaving directory '/home/builder/.termux-build/gdb/build/zlib'
make[1]: Leaving directory '/home/builder/.termux-build/gdb/build'
make: *** [Makefile:1021: all] Error 2
builder@efc9cd9cc059:~/termux-packages$ 

### What steps will reproduce the bug?

./build-package.sh -a aarch64 gdb

### System information

```shell
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 57 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Platinum 8350C CPU @ 2.60GHz
    CPU family:          6
    Model:               106
    Thread(s) per core:  2
    Core(s) per socket:  1
    Socket(s):           1
    Stepping:            6
    BogoMIPS:            5187.81
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid tsc_know
                         n_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb st
                         ibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512vb
                         mi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid md_clear arch_capabilities
Virtualization features: 
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):     
  L1d:                   48 KiB (1 instance)
  L1i:                   32 KiB (1 instance)
  L2:                    1.3 MiB (1 instance)
  L3:                    48 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0,1
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Vulnerable
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by Biswa96** [comment]
The issue can not be reproduced. Same as previous one #20816
