### ISSUE TITLE
[Bug]: Build qemu system x86-64-headless

### ISSUE THREAD

**Issue by CloudControlPro** [termux/termux-packages#20816]
### Problem description

checking whether the x86_64-linux-android-clang linker (ld.lld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for doxygen... false
configure: WARNING: *** doxygen not found, API documentation will not be built
checking for pdflatex... yes
checking for bibtex... yes
checking for fig2dev... yes
configure: WARNING: *** Format Specification will not built.
checking for ld used by x86_64-linux-android-clang... (cached) ld.lld
checking if the linker (ld.lld) is GNU ld... (cached) yes
checking how to control symbol export... --version-script
checking for pkg-config... yes
checking pkg-config is at least version 0.9.0... yes
checking for OGG... yes
checking for VORBIS... yes
checking for sdl-config... no
checking for SDL - version >= 0.11.0... no
*** The sdl-config script installed by SDL could not be found
*** If SDL was installed in PREFIX, make sure PREFIX/bin is in
*** your path, or set the SDL_CONFIG environment variable to the
*** full path to sdl-config.
configure: WARNING: *** Unable to find SDL -- Not compiling example players ***
/home/builder/.termux-build/libtheora/src/configure: line 13310: /data/data/com.Cloudcontrol.script/files/usr/bin/rm: No such file or directory
/home/builder/.termux-build/libtheora/src/configure: line 13319: /data/data/com.Cloudcontrol.script/files/usr/bin/sed: No such file or directory
/home/builder/.termux-build/libtheora/src/configure: line 13320: ${+set}: bad substitution
/home/builder/.termux-build/libtheora/src/configure: line 6: /data/data/com.Cloudcontrol.script/files/usr/bin/cat: No such file or directory
/home/builder/.termux-build/libtheora/src/configure: line 14: /data/data/com.Cloudcontrol.script/files/usr/bin/sed: No such file or directory
/home/builder/.termux-build/libtheora/src/configure: line 40: /data/data/com.Cloudcontrol.script/files/usr/bin/sort: No such file or directory
/home/builder/.termux-build/libtheora/src/configure: line 37: /data/data/com.Cloudcontrol.script/files/usr/bin/sed: No such file or directory
/home/builder/.termux-build/libtheora/src/configure: line 44: /data/data/com.Cloudcontrol.script/files/usr/bin/cat: No such file or directory
/home/builder/.termux-build/libtheora/src/configure: line 57: /data/data/com.Cloudcontrol.script/files/usr/bin/sort: No such file or directory
/home/builder/.termux-build/libtheora/src/configure: line 79: /data/data/com.Cloudcontrol.script/files/usr/bin/cat: No such file or directory
/home/builder/.termux-build/libtheora/src/configure: line 85: /data/data/com.Cloudcontrol.script/files/usr/bin/cat: No such file or directory
/home/builder/.termux-build/libtheora/src/configure: line 92: /data/data/com.Cloudcontrol.script/files/usr/bin/rm: No such file or directory

### What steps will reproduce the bug?

./build-package.sh -a x86_64 qemu-system-x86-64-headless

### System information

```shell
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 57 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Platinum 8350C CPU @ 2.60GHz
    CPU family:          6
    Model:               106
    Thread(s) per core:  2
    Core(s) per socket:  1
    Socket(s):           1
    Stepping:            6
    BogoMIPS:            5187.81
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid tsc_know
                         n_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb st
                         ibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512vb
                         mi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid md_clear arch_capabilities
Virtualization features: 
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):     
  L1d:                   48 KiB (1 instance)
  L1i:                   32 KiB (1 instance)
  L2:                    1.3 MiB (1 instance)
  L3:                    48 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0,1
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Vulnerable
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by Biswa96** [comment]
Add `-I` option use prebuilt dependencies.

**Comment by TomJo2000** [comment]
> Add `-I` option use prebuilt dependencies.

That's not gonna work, they seem to have a different prefix.

**Comment by Biswa96** [comment]
From that log, It seems that libtheora failed to build. But it can be built fine in termux-package-builder container with `./build-package.sh -I -q -a x86_64 libtheora` command.

**Comment by TomJo2000** [comment]
Note the different application prefix.
`com.Cloudcontrol.script`

All our packages are built against `com.termux`.
So the `-I` "fast build" option wouldn't be available,
since this user doesn't use the same application prefix.

**Comment by Biswa96** [comment]
Can you see any error in provided log?

**Comment by TomJo2000** [comment]
This looks like an improperly set up build environment to me.
Check: https://github.com/termux/termux-packages/wiki/Build-environment#setting-up
