### ISSUE TITLE
Golang :: WARNING: linker: /data/data/com.termux/files/usr/tmp/go-build538679723/command-line-arguments/_obj/exe/hash: unused DT entry: type 0x6ffffef5 arg 0x410

### ISSUE THREAD

**Issue by po7a7o** [termux/termux-packages#2082]
The latest update of Golang returns this warning in every execution of program.

```txt
WARNING: linker: /data/data/com.termux/files/usr/tmp/go-build538679723/command-line-arguments/_obj/exe/hash: unused DT entry: type 0x6ffffef5 arg 0x410
```

> $ termux-info 

```txt
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.65-1247614 #2 SMP PREEMPT Mon Nov 13 22:36:29 KST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
5.1.1
Device manufacturer:
samsung
Device model:
SM-J200H
```

> **go version go1.9.3 android/arm**

**Comment by Grimler91** [comment]
I'm not too familiar with go, but `/data/data/com.termux/files/usr/tmp/go-build538679723/command-line-arguments/_obj/exe/hash` looks like something you've installed/downloaded/compiled yourself?

The [termux-packages readme](https://github.com/termux/termux-packages/blob/master/README.md#android-dynamic-linker) explains that running `termux-elf-cleaner` on the binary gets rid of the warning, so in your case run `termux-elf-cleaner $PREFIX/tmp/go-build538679723/command-line-arguments/_obj/exe/hash`.

**Comment by fornwall** [comment]
0x6ffffef5 seems to be DT_GNU_HASH.

@po7a7o Do you have a small test case? Building and running a simple hello world go program does not cause the warning for me.

**Comment by Droid-MAX** [comment]
@po7a7o [termux-elf-cleaner#5](https://github.com/termux/termux-elf-cleaner/issues/5)

**Comment by Droid-MAX** [comment]
@po7a7o https://github.com/Droid-MAX/termux-elf-cleaner
I solved this problem, but this feature is only support Android 5.x device, and this issue can be closed.

**Comment by po7a7o** [comment]
@Droid-MAX  it worked for me! Thanks

**Comment by bhagwandassony1** [comment]
![Screenshot_20200805-054516](https://user-images.githubusercontent.com/69147279/89358771-c3c24400-d6b3-11ea-883b-ae6661e8e977.png)

**Comment by xeffyr** [comment]
@bhagwandassony1 Stop spamming with your screenshots! You seems installed packages compiled for Android 7.0, that's why you have linker issues.
