### ISSUE TITLE
rsync-3.1.3 update failing with: [sender] write error: Broken pipe

### ISSUE THREAD

**Issue by skymoo** [termux/termux-packages#2083]
Since updating to rsync-3.1.3 yesterday several of my scripts, which use `rsync`, have started failing with errors of the form:

```
rsync: [sender] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at /home/builder/.termux-build/rsync.src/io.c(820) [sender=3.1.3]
```

Is the previous package version still available?

**Comment by skymoo** [comment]
Just built `rsync-3.1.2-1` and installed the resulting package and my scripts are working again so this is definitely a regression in this new version.

**Comment by fornwall** [comment]
Thanks for reporting! 

I just tried some basic rsync examples, and it works for me. Does every basic usage of rsync fail for you, or only certain commands? What arch do you run (what is the output of running `uname -m`) and which Android version?

**Comment by skymoo** [comment]
I have a script that backs up the contents of my sdcard to my desktop machine, the exact `rsync` command that my script uses is:

```
rsync \
  -vHrltD \
  --chmod=Du+rwx,go-rwx,Fu+rw,go-rw \
  --no-perms \
  --delete-after \
  -e "ssh -y -p 22 -i ${KEY}" \
  /sdcard/ \
  ${USER}@${HOSTNAME}:${DESTINATION}
```

I'm using a Pixel 2 running Android-8.1.0 (5 January 2018 security patch level) with architecture `aarch64`.

I'll try and run some basic `rsync` commands and see what happens, it'll probably be tomorrow before I can get to that now.

**Comment by skymoo** [comment]
Sorry for the delay, it seems that on device `rsync` commands work but when I'm encountering the problem when `ssh` is involved and I'm syncing from, or to, another host.

**Comment by skymoo** [comment]
Actually I've just had the issue with `rsync-3.1.2-1` so this isn't specific to 3.1.3, it just seems to happen more often with 3.1.3.

**Comment by xeffyr** [comment]
> rsync: [sender] write error: Broken pipe (32)

> -e "ssh -y -p 22 -i ${KEY}"

Seems that this is related to SSH and not `rsync`.

**Comment by xtkoba** [comment]
This issue is marked as obsolete. Please open a new issue if you encounter a similar problem. Thanks.
