### ISSUE TITLE
[Bug]: serious proplem

### ISSUE THREAD

**Issue by User2736473** [termux/termux-packages#20849]
### Problem description

When i try to move the mouse it moves little bit than stops the only way to fix tgisbus to delete app from background but its really annoying proplem i hope you fix mouse stopping move soon and thx

### What steps will reproduce the bug?

Only delete it from background

### What is the expected behavior?

Bad

### System information

```shell
termux-info
I dunno
```

**Comment by Hammadicko** [comment]
Good evening how are you

Le sam. 13 juil. 2024 à 11:59, User2736473 ***@***.***> a
écrit :
