### ISSUE TITLE
[Package]: RmlUI

### ISSUE THREAD

**Issue by DuilioPerez** [termux/termux-packages#20859]
### Why is it worth to add this package?

RmlUI is a library to implement GUI components easly on games based on some libraries, as SDL, glfw, SFML and some renderes, as Open GL (ES) 2 or 3, SDL_Renderer, etc. It uses rml and rcss to make the development of GUI apps easy. rml files are like XHTML 1 and rcss are like css 2.

### Home page URL

https://github.com/mikke89/RmlUi

### Source code URL

https://github.com/mikke89/RmlUi

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

It takes about 15 minutes to compile. I've compiled amd tested locally on my device. Here I add a compilated package for aarch64. This zip file contains a script to compile (buildRmlUI.sh) and a file (buildRmlUI.txt) with some observations.
[RmlUI.zip](https://github.com/user-attachments/files/16229663/RmlUI.zip)

**Comment by DuilioPerez** [comment]
If I didn't mentioned in buildRmlUI.txt, xorgproto is only used for the headers to compile the demos

**Comment by TomJo2000** [comment]
We don't package standalone libraries without any programs that depend on them.
I thought that was mentioned in the checklist, but apparently not.
