### ISSUE TITLE
Auto update failing for wasm-component-ld

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#20878]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [wasm-component-ld](https://github.com/termux/termux-packages/blob/0cb5312e02da650e0cc42f4345fffc889c3feee8/packages/wasm-component-ld) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating wasm-component-ld [Current version: 0.5.4]
INFO: package being updated to 0.5.5.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 75942    0 75942    0     0   199k      0 --:--:-- --:--:-- --:--:--  199k

You are about to commit these changes:

--------------------
diff --git a/packages/wasm-component-ld/build.sh b/packages/wasm-component-ld/build.sh
index 967c2964e..8fb62a337 100644
--- a/packages/wasm-component-ld/build.sh
+++ b/packages/wasm-component-ld/build.sh
@@ -3,9 +3,9 @@ TERMUX_PKG_DESCRIPTION="Command line linker for creating WebAssembly components"
 TERMUX_PKG_LICENSE="Apache-2.0, MIT"
 TERMUX_PKG_LICENSE_FILE="LICENSE-APACHE, LICENSE-Apache-2.0_WITH_LLVM-exception, LICENSE-MIT"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="0.5.4"
+TERMUX_PKG_VERSION="0.5.5"
 TERMUX_PKG_SRCURL=https://github.com/bytecodealliance/wasm-component-ld/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=78483e8bf35aabe0ccdedd2a2fe61a382038bb883b3389c1686fedac3f32a5db
+TERMUX_PKG_SHA256=e604fd428e039c44f47735892c6a22c1e7f5dea98d31ea77cd1ab36a42cc87f9
 TERMUX_PKG_BUILD_IN_SRC=true
 TERMUX_PKG_AUTO_UPDATE=true
 
--------------------

bump(main/wasm-component-ld): 0.5.5

Not committing to Git!

INFO: Trying to build package.
INFO: Package wasm-component-ld exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building wasm-component-ld for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  30875      0 --:--:-- --:--:-- --:--:-- 30903
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1972      0 --:--:-- --:--:-- --:--:--  1973
gpg: Signature made Tue 16 Jul 2024 04:08:44 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  30125      0 --:--:-- --:--:-- --:--:-- 30135
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2003      0 --:--:-- --:--:-- --:--:--  2007
gpg: Signature made Sun 14 Jul 2024 02:55:10 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  30703      0 --:--:-- --:--:-- --:--:-- 30654
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1971      0 --:--:-- --:--:-- --:--:--  1973
gpg: Signature made Tue 16 Jul 2024 01:29:52 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://github.com/bytecodealliance/wasm-component-ld/archive/refs/tags/v0.5.5.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 75942    0 75942    0     0   314k      0 --:--:-- --:--:-- --:--:--  314k
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for '1.79.0-x86_64-unknown-linux-gnu'
info: default toolchain set to '1.79.0-x86_64-unknown-linux-gnu'

  1.79.0-x86_64-unknown-linux-gnu unchanged - rustc 1.79.0 (129f3b996 2024-06-10)

Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, you need to source
the corresponding env file under $HOME/.cargo.

This is usually done by running one of the following (note the leading DOT):
. "$HOME/.cargo/env"            # For sh/bash/zsh/ash/dash/pdksh
source "$HOME/.cargo/env.fish"  # For fish
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
    Updating crates.io index
 Downloading crates ...
  Downloaded ahash v0.8.11
  Downloaded semver v1.0.23
  Downloaded wasm-metadata v0.214.0
  Downloaded unicode-xid v0.2.4
  Downloaded lexopt v0.3.0
  Downloaded wit-component v0.214.0
  Downloaded wat v1.214.0
  Downloaded zerocopy v0.7.35
  Downloaded wasmparser v0.214.0
  Downloaded wit-parser v0.214.0
  Downloaded spdx v0.10.6
  Downloaded syn v2.0.71
  Downloaded wasm-encoder v0.214.0
  Downloaded clap_builder v4.5.9
  Downloaded wast v214.0.0
  Downloaded serde_derive v1.0.204
  Downloaded serde v1.0.204
  Downloaded bumpalo v3.16.0
  Downloaded leb128 v0.2.5
  Downloaded clap v4.5.9
   Compiling serde v1.0.204
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.19.0
   Compiling zerocopy v0.7.35
   Compiling proc-macro2 v1.0.86
   Compiling ahash v0.8.11
   Compiling bitflags v2.6.0
   Compiling unicode-ident v1.0.12
   Compiling semver v1.0.23
   Compiling equivalent v1.0.1
   Compiling anyhow v1.0.86
   Compiling leb128 v0.2.5
   Compiling serde_json v1.0.120
   Compiling quote v1.0.36
   Compiling syn v2.0.71
   Compiling libc v0.2.155
   Compiling utf8parse v0.2.2
   Compiling ryu v1.0.18
   Compiling itoa v1.0.11
   Compiling anstyle-parse v0.2.4
   Compiling rustix v0.38.34
   Compiling smallvec v1.13.2
   Compiling colorchoice v1.0.1
   Compiling is_terminal_polyfill v1.70.0
   Compiling anstyle v1.0.7
   Compiling anstyle-query v1.1.0
   Compiling spdx v0.10.6
   Compiling hashbrown v0.14.5
   Compiling indexmap v2.2.6
   Compiling anstream v0.6.14
   Compiling wasmparser v0.214.0
   Compiling errno v0.3.9
   Compiling strsim v0.11.1
   Compiling serde_derive v1.0.204
   Compiling log v0.4.22
   Compiling unicode-width v0.1.13
   Compiling memchr v2.7.4
   Compiling clap_lex v0.7.1
   Compiling heck v0.5.0
   Compiling bumpalo v3.16.0
   Compiling unicode-xid v0.2.4
   Compiling linux-raw-sys v0.4.14
   Compiling id-arena v2.2.1
   Compiling clap_derive v4.5.8
   Compiling clap_builder v4.5.9
   Compiling fastrand v2.1.0
   Compiling tempfile v3.10.1
   Compiling wasm-encoder v0.214.0
   Compiling wit-parser v0.214.0
   Compiling wasm-metadata v0.214.0
   Compiling wast v214.0.0
   Compiling wit-component v0.214.0
   Compiling wat v1.214.0
   Compiling clap v4.5.9
   Compiling lexopt v0.3.0
   Compiling wasm-component-ld v0.5.5 (/home/builder/.termux-build/wasm-component-ld/src)
    Finished `release` profile [optimized] target(s) in 49.87s
ERROR: No LICENSE file was installed for wasm-component-ld
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-07-16 18:21:38 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/9961868387">9961868387</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by TomJo2000** [comment]
closed by https://github.com/termux/termux-packages/commit/e275b54f24ba270ba230b2657755c42d409e980a
