### ISSUE TITLE
leanify

### ISSUE THREAD

**Issue by TPS** [termux/termux-packages#20885]
### Why is it worth to add this package?

Very good recursive minifier/optimizer for a wide variety of compressed archives, documents, & files

### Home page URL

https://github.com/JayXon/Leanify

### Source code URL

https://github.com/JayXon/Leanify

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

_N.B.:  Project no longer has standard releases, but has more of rolling releases._

**Comment by TomJo2000** [comment]
That packaging list is looking pretty slim.
https://repology.org/project/leanify/versions

and the commits are looking pretty sporadic.
https://github.com/JayXon/Leanify/commits/master/

I'm not opposed to this package,
but I think it would be a better fit for the [TUR](https://github.com/termux-user-repository/tur).

**Comment by TPS** [comment]
@TomJo2000 Would you be willing to move the request there? 🙇🏾‍♂️

**Comment by TomJo2000** [comment]
I can do that later.
I have it very close to building fine locally.

The Makefile just doesn't have a `install` target, so I need to overwrite that step of the build process.
Other than that, was pretty simple to get it to compile.
Just had to add 
```bash
TERMUX_PKG_DEPENDS='libiconv_open'
# and
termux_step_post_configure() {
	CFLAGS+=' -Wno-error=unused-but-set-variable'
	LDFLAGS+=' -liconv'
}
```
to the standard build script template after filling in the package details.

**Comment by TomJo2000** [comment]
Got it building.
I'll tidy it up, do some testing and send a pull request to the TUR after I get back from running some errands.

**Comment by TomJo2000** [comment]
Closed by termux-user-repository/tur#1123

**Comment by TPS** [comment]
@TomJo2000 If you don't mind, some advice, please:

I'd like to request to publish [`oxipng`](https://github.com/oxipng/oxipng), a successor to `optipng` (already in this main repo).  Should I request that here, or in the TUR?

**Comment by TomJo2000** [comment]
> [@TomJo2000](https://github.com/TomJo2000) If you don't mind, some advice, please:
> 
> I'd like to request to publish [`oxipng`](https://github.com/oxipng/oxipng), a successor to `optipng` (already in this main repo). Should I request that here, or in the TUR?

- If it's a continuation project (along the lines of #17828), then `oxipng` can just replace `optipng` in the main repo.

**Comment by TPS** [comment]
> - If it's a continuation project (along the lines of #17828), then `oxipng` can just replace `optipng` in the main repo.

Its neither a fork nor a continuation, but, a few years ago, while `optipng` mantenance had stopped for a while, `oxipng` was started inspired by it, but designed to be multithreaded from the outset.  Since then, each is still being developed, & have diverged in their features.

Where do you think I should request?

**Comment by TomJo2000** [comment]
> > * If it's a continuation project (along the lines of [replace(exa -> eza): replace with maintained fork #17828](https://github.com/termux/termux-packages/pull/17828)), then `oxipng` can just replace `optipng` in the main repo.
> 
> Its neither a fork nor a continuation, but, a few years ago, while `optipng` mantenance had stopped for a while, `oxipng` was started inspired by it, but designed to be multithreaded from the outset. Since then, each is still being developed, & have diverged in their features.

So it's a continuation fork with a revived original project.

> Where do you think I should request?

Considering both projects are widely[^1] packaged.
Main repo sounds fine.

[^1]:![Image](https://github.com/user-attachments/assets/142e483a-1639-4eb9-8e5e-66268572e426)![Image](https://github.com/user-attachments/assets/130cc6e4-ce57-4350-b92d-7a256399ead4)

**Comment by TPS** [comment]
Finally remembered to RFP [jpegli](https://github.com/termux-user-repository/tur/issues/1448) ~~& [oxipng](https://github.com/termux-user-repository/tur/issues/2099)~~ _([packaged!](https://github.com/termux-user-repository/tur/pull/2134))_.

**Comment by TPS** [comment]
@TomJo2000 Does the recent merging of https://github.com/JayXon/Leanify/pull/98 make `leanify` simpler/possible to *(auto)*-update here?

**Comment by robertkirkman** [comment]
> [@TomJo2000](https://github.com/TomJo2000) Does the recent merging of [JayXon/Leanify#98](https://github.com/JayXon/Leanify/pull/98) make `leanify` simpler/possible to _(auto)_-update here?

unfortunately not quite, there are still no recent tags in the leanify repository, so that is calculated by Termux as meaning that there is no new release.

**Comment by TomJo2000** [comment]
> [@TomJo2000](https://github.com/TomJo2000) Does the recent merging of [JayXon/Leanify#98](https://github.com/JayXon/Leanify/pull/98) make `leanify` simpler/possible to _(auto)_-update here?

Eh, no not really.
You can submit a PR to update it to the latest commit and remove the `termux_step_make_install` override.
But there isn't really any way for us to auto-update the package in a conventional way since it doesn't release tagged versions.

`libluajit` is in a similar situation and in that case we use the Arch Linux packaging Gitlab as a release proxy.
https://github.com/termux/termux-packages/blob/e6c703f92311e012de7f7fb7b9e7c4bc986fed24/packages/libluajit/build.sh#L15-L27
But I don't think the same thing would be applicable for `leanify`.
This only works for LuaJIT because it is a widely used project with a fairly unique versioning scheme (or lack thereof).

**Comment by TPS** [comment]
Thanks for taking a look 🙇🏾‍♂️
