### ISSUE TITLE
Key error essid [Bug]: 

### ISSUE THREAD

**Issue by Gilbert020994** [termux/termux-packages#20887]
### Problem description

![Screenshot_2024-07-18-14-05-17-732_com termux](https://github.com/user-attachments/assets/44cb9ce3-74c0-47b0-ba80-7f39a9f989b3)

### What steps will reproduce the bug?

..

### What is the expected behavior?

...

### System information

```shell
...
```

**Comment by TomJo2000** [comment]
What do you expect us to do with that?
You didn't provide any information.

**Comment by twaik** [comment]
https://wiki.termux.com/wiki/Hacking
