### ISSUE TITLE
No existing LLVM 17 related packages after version 18 bump

### ISSUE THREAD

**Issue by cattokomo** [termux/termux-packages#20891]
Currently, there's no packages for LLVM 17 for `llvm`, `clang`, `lld`, `mlir` and many others. Is this an unintended mistake when bumping to version 18?

**Comment by TomJo2000** [comment]
That is expected behavior for the main repo.
Though there not being a `libllvm17` package in the TUR is a TUR issue.
And should be filed as such.

**Comment by TomJo2000** [comment]
Please feel free to take the last LLVM 17 commit's state.
And add it to the TUR.
https://github.com/termux/termux-packages/tree/5c69b909a360f3025a032e353c0d0de3c0419625/packages/libllvm
