### ISSUE TITLE
[Bug]: ncurses version mismatch 

### ISSUE THREAD

**Issue by redaHBZ0** [termux/termux-packages#20899]
### Problem description

the ncurses package does not have the same version as ncurses-utils or ncurses-ui-libs.
This triggers a version mismatch error when trying to install either packages.
![Screenshot_20240719-144409_Termux](https://github.com/user-attachments/assets/c48bb957-56a2-4742-859d-9d9cbc230682)
![Screenshot_20240719-144424_Termux](https://github.com/user-attachments/assets/9ca4ac12-4683-46fd-a5b7-e57680d002bd)

### What steps will reproduce the bug?

`pkg install ncurses-utils` or install similar packages

### What is the expected behavior?

Install packages correctly

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=17952
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.astra.in.ua/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://termux.astra.in.ua/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.4
Android version:
11
Kernel build information:
Linux localhost 4.19.127-22945975 #1 SMP PREEMPT Mon Apr 24 13:16:03 KST 2023 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A107F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

**Comment by redaHBZ0** [comment]
Note that these packages are required to install python.

**Comment by Biswa96** [comment]
Please update the packages. Here are the latest version of the ncurses packages.

```
$ apt search ncurses | grep 'ncurses.*stable'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ncurses/stable,now 6.4.20231001-4 x86_64 [installed]
ncurses-static/stable 6.4.20231001-4 x86_64
ncurses-ui-libs/stable,now 6.4.20231001-4 x86_64 [installed,automatic]
ncurses-ui-libs-static/stable 6.4.20231001-4 x86_64
ncurses-utils/stable 6.4.20231001-4 x86_64
```

 Also, try to switch mirror because that mirror may have older versions.
