### ISSUE TITLE
Music touches people's hearts. I need CMUS.

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#209]
And I'm not completely satisfied with play-audio.
 **Cmus** seems to be a better solution for **termux**.
I would love to listen to music with cmus. : /
But still I do not know what is needed to build **cmus** to **termux**  ...
Why **cmus** not part of the package list yet?

**https://cmus.github.io/**

**Comment by fornwall** [comment]
Thanks! You will need to open a feature request against cmus, since it would need to add support for the audio framework used on Android (OpenSL ES) before the package can be added to Termux!

**Comment by Neo-Oli** [comment]
I went ahead and opened an issue at the cmus repo. https://github.com/cmus/cmus/issues/437

**Comment by Neo-Oli** [comment]
I posted a small bounty on the inclusion of OpenSL ES in cmus on [bountysource](https://www.bountysource.com/issues/33102790-support-for-the-audio-framework-used-on-android-opensl-es). Maybe it will entice someone capable to do the required work (Especially if a couple more people pitched in).

**Comment by ackalker** [comment]
I would like to request re-opening this issue, which is about *packaging* CMUS for Termux, not about its built-in support for a particular audio backend. CMUS supports both ALSA and Pulseaudio among others, so . it can be used with the ongoing work in issue #821. I see no particular problems with creating a build script for CMUS with either of those (or both) as dependencies.

**Comment by ackalker** [comment]
@Neo-Oli Thanks! Now that I've got `libpulseaudio` done, I'll have a go at packaging `cmus`. @buribu Stay tuned 😃

**Comment by ackalker** [comment]
It's here!
![CMUS on Termux](https://i.imgur.com/ytEkqLm.png)

Still very young, lots of dependencies still to package, but... it *sings* :heart:

**Comment by ackalker** [comment]
`cmus' will be ready for merging soon! More file formats are now supported and tested.

! [CMUS playlist](https://m.imgur.com/gallery/Stgoz)

**Comment by buribu** [comment]
Thank you so much @ackalker ! I get very happy when someone takes a need from me
And dedicates so much time and effort to supply it.
As if this necessity were the reason for his own existence. LOL
 
I read and applied everything that was written on #821 .
I was really impressed. I did not think it would take so much work. The need for Xserver XSDL surprised me a little.
I imagine the termux as a Swiss Army Knife. With lightweight and powerful applications expanding the possibilities of android use.

It's really cool to have cmus \o/.
I wonder how amazing it will be when all features are supported.
