### ISSUE TITLE
Auto update failing for grafana

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#20904]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [grafana](https://github.com/termux/termux-packages/blob/38987a94712c384ece3ad9530f788c0be6195ff6/packages/grafana) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating grafana [Current version: 1:11.1.0]
INFO: package being updated to 11.1.999.
INFO: Trying to build package.
INFO: Package grafana exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
Creating new container...
Unable to find image 'ghcr.io/termux/package-builder:latest' locally
latest: Pulling from termux/package-builder
9b857f539cb1: Pulling fs layer
7b3a5b9cdd29: Pulling fs layer
d1e6ce8fa13d: Pulling fs layer
ba4ad9062242: Pulling fs layer
afb47b1887be: Pulling fs layer
2431bfbdc468: Pulling fs layer
2431bfbdc468: Waiting
ba4ad9062242: Waiting
afb47b1887be: Waiting
7b3a5b9cdd29: Download complete
d1e6ce8fa13d: Verifying Checksum
d1e6ce8fa13d: Download complete
9b857f539cb1: Download complete
ba4ad9062242: Verifying Checksum
ba4ad9062242: Download complete
2431bfbdc468: Download complete
9b857f539cb1: Pull complete
7b3a5b9cdd29: Pull complete
d1e6ce8fa13d: Pull complete
ba4ad9062242: Pull complete
afb47b1887be: Verifying Checksum
afb47b1887be: Download complete
afb47b1887be: Pull complete
2431bfbdc468: Pull complete
Digest: sha256:d45f95d4dd7b84380c416ff9e3938a2aef7f016c20c80805c8effbb2ebaedcba
Status: Downloaded newer image for ghcr.io/termux/package-builder:latest
acf8082025e581847813fee3721052ae6c5b34b0906e0e63c3e3feffcfacb5c0
gpg: key B0076E490B71616B: 18 signatures not checked due to missing keys
gpg: key B0076E490B71616B: public key "Henrik Grimler <henrik@grimler.se>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no ultimately trusted keys found
gpg (GnuPG) 2.2.27; Copyright (C) 2021 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: key 5A897D96E57CF20C: public key "Termux Releases (Termux automatic builds) <contact@termux.dev>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   1  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2026-05-06
gpg (GnuPG) 2.2.27; Copyright (C) 2021 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: key 389CEED64573DFCA: public key "termux-pacman (security signature) <pacman@termux.dev>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg (GnuPG) 2.2.27; Copyright (C) 2021 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

termux - building grafana for arch aarch64...
Downloading https://github.com/termux/termux-elf-cleaner/releases/download/v2.2.1/termux-elf-cleaner
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  471k  100  471k    0     0  2095k      0 --:--:-- --:--:-- --:--:-- 2095k
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0   128k      0 --:--:-- --:--:-- --:--:--  129k
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1877      0 --:--:-- --:--:-- --:--:--  1880
gpg: Signature made Fri 19 Jul 2024 09:37:53 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   3  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 3u
gpg: next trustdb check due at 2026-05-06
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1 1604k    1 30651    0     0  55833      0  0:00:29 --:--:--  0:00:29 55830
100 1604k  100 1604k    0     0  1753k      0 --:--:-- --:--:-- --:--:-- 1753k
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  34455      0 --:--:-- --:--:-- --:--:-- 34418
100 13320  100 13320    0     0  34443      0 --:--:-- --:--:-- --:--:-- 34418
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1955      0 --:--:-- --:--:-- --:--:--  1955
gpg: Signature made Fri 19 Jul 2024 06:26:22 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/stable/binary-aarch64/Packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 57358  100 57358    0     0   143k      0 --:--:-- --:--:-- --:--:--  143k
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  30536      0 --:--:-- --:--:-- --:--:-- 30511
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2374      0 --:--:-- --:--:-- --:--:--  2380
gpg: Signature made Fri 19 Jul 2024 06:45:23 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/main/binary-aarch64/Packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  469k  100  469k    0     0  1075k      0 --:--:-- --:--:-- --:--:-- 1074k
Downloading dependency yarn@1.22.22 if necessary...
Found yarn in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/y/yarn/yarn_1.22.22_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  874k  100  874k    0     0  6233k      0 --:--:-- --:--:-- --:--:-- 6247k
extracting yarn to /home/builder/.termux-build/_cache-all...
Cloning into '/home/builder/.termux-build/grafana/cache/tmp-checkout'...
warning: Could not find remote branch v11.1.999 to clone.
fatal: Remote branch v11.1.999 not found in upstream origin
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-07-20 00:24:59 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/10015922871">10015922871</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by TomJo2000** [comment]
We should probably also set `TERMUX_PKG_UPDATE_TAG_TYPE=latest-release-tag`
