### ISSUE TITLE
[Bug]: no template named 'auto_ptr' in namespace 'std' in libxml++-2.6

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-packages#20903]
### Problem description

My goal is to (theoretically) port the GnuCash application to Termux. It requires a lot of small libraries that seem to be easy to port. For now, however, I'm stuck with the libofx library.

I want to build the project itself in Termux Build Environment (that's why I don't add termux-info). The problem also occurs when building on a smartphone, so it's probably a problem with the libxml++-2.6 header files. I'm no expert, but I suspect that the version of libxml that is distributed (its header files) are not compatible with new versions of the C++ language. However, I don't know if it works that way ;)

https://p.vinci-concessions.com/?4cef332360f9a023#CHSFXmyTwwwLSEgdqJBZiNoMpnUur4nLzBWV2s5z4ySH

PKGs:
[pkgs.tar.gz](https://github.com/user-attachments/files/16317065/pkgs.tar.gz)

### What steps will reproduce the bug?

Just build using Termux Build Env

### System information

```shell
-
```

**Comment by Biswa96** [comment]
Please provide the steps to reproduce the issue and link to actual git repository. I am not eager to download random files in the Internet.

**Comment by licy183** [comment]
`std::auto_ptr` has been deprecated since C++11 and removed since C++17. From clang-17, c++17 is enabled by default. You can append `-std=c++11` in `CXXFLAGS`.

**Comment by IntinteDAO** [comment]
@licy183 Works great, thx
