### ISSUE TITLE
[Package]: lshw

### ISSUE THREAD

**Issue by maaaaz** [termux/termux-packages#20912]
### Why is it worth to add this package?

A small tool to provide detailed information on the hardware
configuration of the machine. It can report exact memory
configuration, firmware version, mainboard configuration, CPU version
and speed, cache configuration, bus speed, etc. on DMI-capable x86
systems, on some PowerPC machines (PowerMac G4 is known to work) and AMD64.
Information can be output in plain text, HTML or XML.

### Source code URL

https://github.com/lyonel/lshw

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
As stated in:
- #20910

This will likely require root permissions.
If the necessary APIs exist on Android at all.

**Comment by TomJo2000** [comment]
combining into above mentioned issue

**Comment by robertkirkman** [comment]
In

- https://github.com/termux/termux-packages/pull/25278

I have added `hdparm` and `smartmontools`, and not any of these others.

I can attempt to add others if re-requested.
