### ISSUE TITLE
[Package]: keepassxc

### ISSUE THREAD

**Issue by maaaaz** [termux/termux-packages#20917]
### Why is it worth to add this package?

KeePassXC is a free/open-source password manager or safe which helps you
to manage your passwords in a secure way. You can put all your
passwords in one database, which is locked with one master key or a
key-disk. So you only have to remember one single master password or
insert the key-disk to unlock the whole database. The databases are
encrypted using the algorithms AES or Twofish.
In contrast to KeePassX (package keepassx), KeePassXC is actively developed
and has more features, e.g., connectivity to a Web Browser plugin (package
webext-keepassxc-browser).

### Source code URL

https://keepassxc.org/download/#code

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
Already packaged:
- #10044

Please lay off with the package requests for the time being.
Anything "system monitor" related can get lumped into #20910 for the time being.
