### ISSUE TITLE
[Package]: lm-sensors

### ISSUE THREAD

**Issue by maaaaz** [termux/termux-packages#20914]
### Why is it worth to add this package?

lm-sensors is a hardware health monitoring package for Linux. It allows you
to access information from temperature, voltage, and fan speed sensors. It
works with most newer systems.
This package contains programs to help you set up and read data from
lm-sensors.

### Source code URL

https://hwmon.wiki.kernel.org/lm_sensors

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
As stated in:
- #20910

This will likely require root permissions.
If the necessary APIs exist on Android at all.

**Comment by TomJo2000** [comment]
Combing into above mentioned issue.

**Comment by robertkirkman** [comment]
In

- https://github.com/termux/termux-packages/pull/25278

I have added `hdparm` and `smartmontools`, and not any of these others.

I can attempt to add others if re-requested.
