### ISSUE TITLE
[Package]: dislocker

### ISSUE THREAD

**Issue by maaaaz** [termux/termux-packages#20919]
### Why is it worth to add this package?

Dislocker has been designed to read BitLocker encrypted partitions under
a Linux system. The driver used to read volumes encrypted in Windows system
versions of the Vista to 10 and BitLocker-To-Go encrypted partitions, that's
USB/FAT32 partitions.
The software works with driver composed of a library, with multiple binaries
using this library. Decrypting the partition, you have to give it a mount
point where, once keys are decrypted, a file named dislocker-file appears.
This file is a virtual NTFS partition, so you can mount it as any NTFS
partition and then read from or write to it. Writing to the NTFS virtual
file will change the underlying BitLocker partition content. To use
dislocker-find Ruby is required.
This tool is useful in cryptography managing and forensics investigations.

### Source code URL

https://github.com/Aorimn/dislocker

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
Alright, that's enough.
You can stop opening new package requests.

Consider this part of #20910.

**Comment by robertkirkman** [comment]
In

- https://github.com/termux/termux-packages/pull/25278

I have added `hdparm` and `smartmontools`, and not any of these others.

I can attempt to add others if re-requested.
