### ISSUE TITLE
LTS NDK 27 was just released

### ISSUE THREAD

**Issue by finagolfin** [termux/termux-packages#20927]
[We should update to use it](https://developer.android.com/ndk/downloads). We can finally get rid of `-fno-openmp-implicit-rpath`, and I'm sure other issues too.

**Comment by Biswa96** [comment]
`clang-scan-deps` is now included[^1]. The workaround in vulkan-headers can be removed.
https://github.com/termux/termux-packages/blob/9bfc82c43cc9856647be8436e3a0a093db0d919d/packages/vulkan-headers/build.sh#L12


[^1]: https://github.com/android/ndk/wiki/Changelog-r27

**Comment by TomJo2000** [comment]
> `clang-scan-deps` is now included

Does this also apply for `emscripten`?
https://github.com/termux/termux-packages/blob/9bfc82c43cc9856647be8436e3a0a093db0d919d/packages/emscripten/build.sh#L39

**Comment by Biswa96** [comment]
> Does this also apply for `emscripten`?

It is probably not related to NDK update or that clang-scan-deps addition. Those file is emscripten were removed to match upstream released binaries and probably making the package smaller. Though the emsdk-3.1.63/upstream/bin directory has clang-scan-deps executable.
