### ISSUE TITLE
Ncurses Update causes errors in Neovim

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#2092]
Controlling Neovim with the mouse doesn't work anymore after upgrading to ncurses 6.1
Error:
`E349: No identifier under cursor`

This happens when clicking anywhere in a file (to move the cursor).

Downgrading to ncurses 6.0 fixes the issues.

Perhaps Neovim just needs to be rebuilt against ncurses 6.1?

**Comment by Atavic** [comment]
>The issue about neovim is a bug in libtermkey (neovim's terminal handling library).

https://github.com/lxde/qtermwidget/issues/164#issuecomment-361280624

**Comment by Neo-Oli** [comment]
Since it's fixed in neovim's git->master we could bump the commit of our neovim package.

**Comment by fornwall** [comment]
The neovim package has been updated to latest git master (this commit: https://github.com/neovim/neovim/commit/0851057a8deaa1197bd0af22babb62c1146d836c) which should fix the problem!
