### ISSUE TITLE
segmentation fault after running pkg up

### ISSUE THREAD

**Issue by juanspeed** [termux/termux-packages#2093]
Hello after running pkg up I can not use any command in another session. ls, apt, etc. It generates a message that says "segmentation fault". How can I solve that? Thank you

**Comment by xeffyr** [comment]
Try `unset LD_PRELOAD`. Related issue: https://github.com/termux/termux-packages/issues/2066

**Comment by juanspeed** [comment]
@xeffyr   I tried but it does not work.

**Comment by Grimler91** [comment]
Closing in favour of #2066.
