### ISSUE TITLE
[Error]: "Compressed file ended before the end-of-stream marker was reached"

### ISSUE THREAD

**Issue by VT-V1PER** [termux/termux-packages#20936]
### Problem description

![Screenshot_2024-07-22-20-45-33-801_com termux](https://github.com/user-attachments/assets/36152f2b-9db3-45a6-83dd-c84de0e825c2)

### What steps will reproduce the bug?

I was downloading files for system

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18052
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# glibc-repo (sources.list.d/glibc.list)
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
liblz4/stable 1.10.0 aarch64 [upgradable from: 1.9.4-1]
termux-tools version:
1.43.1
Android version:
14
Kernel build information:
Linux localhost 6.1.57-android14-11-g42825d7bf0cd-ab11468031 #1 SMP PREEMPT Mon Feb 19 08:37:13 UTC 2024 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
2311DRK48G
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
```

**Comment by Biswa96** [comment]
How to reproduce the issue?

**Comment by VT-V1PER** [comment]
> How to reproduce the issue?
I was downloadind main files for dark os (I don't know how to explain it, there is some screen shots) 
![Screenshot_2024-07-22-21-40-55-974_com termux](https://github.com/user-attachments/assets/a165d77a-0d60-473b-bbdb-65e2d44db1d0)
![Screenshot_2024-07-22-21-40-49-725_com termux](https://github.com/user-attachments/assets/fa53e86c-b8b3-497f-9f2d-2f4f66a9037b)

**Comment by truboxl** [comment]
We dont provide support for 3rd party scripts. Please go seek help from the original author of the script.

**Comment by VT-V1PER** [comment]
It is original, lol, the command was

curl -o install https://raw.githubusercontent.com/ahmad1abbadi/darkos/main/installOS.sh && chmod +x install && ./install

**Comment by truboxl** [comment]
Then submit your issue to https://github.com/ahmad1abbadi/darkos/issues
