### ISSUE TITLE
[Package]: frankenphp

### ISSUE THREAD

**Issue by kyzsuukii** [termux/termux-packages#20943]
### Why is it worth to add this package?

FrankenPHP is a modern application server for PHP built on top of the [Caddy](https://caddyserver.com/) web server.

FrankenPHP gives superpowers to your PHP apps thanks to its stunning features: [Early Hints](https://frankenphp.dev/docs/early-hints/), [worker mode](https://frankenphp.dev/docs/worker/), [real-time capabilities](https://frankenphp.dev/docs/mercure/), automatic HTTPS, HTTP/2, and HTTP/3 support...

FrankenPHP works with any PHP app and makes your Laravel and Symfony projects faster than ever thanks to their official integrations with the worker mode.

### Home page URL

https://frankenphp.dev/

### Source code URL

https://github.com/dunglas/frankenphp

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [ ] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

![image](https://github.com/user-attachments/assets/08fd8ba0-8576-4407-b8a9-df1601102cab)

its have prebuild binary and i try to run on termux its work

**Comment by TomJo2000** [comment]
I think your fill out of the checklist pretty much sums up why this isn't a good candidate for the main repository.
- It doesn't have existing packages to use as reference
(or even show interest in the package, though that is secondary)
- It's a very large package
the official release archives of the latest version are 43.7 MB for x86_64
and **124 MB** for Aarch64.
- It's duplicating a lot of functionality.

Maybe the [TUR](https://github.com/termux-user-repository/tur) would be interested in packaging it.
But if the pre-built binaries run on Termux I doubt that would be useful.
Unfortunately server space, bandwidth and maintainer time are neither free nor unlimited.
