### ISSUE TITLE
termux elf cleaner not working

### ISSUE THREAD

**Issue by Hax4us** [termux/termux-packages#2094]
WARNING: linker: libgarcon-1.so.0: unused DT entry: type 0x6ffffef5 arg 0x1080

I m trying to clean above dt entry by :- termux-elf-cleaner libgarcon-1.so.0 
But nothing happened 
Any help will be appreciated :)

**Comment by Grimler91** [comment]
Related/same issue: #2082.
From where did you get libgarcon-1.so.0?

**Comment by Hax4us** [comment]
@grimler i compiled garcon

**Comment by fornwall** [comment]
@Hax4us Is this on an Android 5.0 device? Support for the DT_GNU_HASH (0x6ffffef5) DT entry was added to the linker in Androdi 6.0, so I'm a bit hesitant to remove the entry.

**Comment by Hax4us** [comment]
Yes Android 5.x device @fornwall

**Comment by Hax4us** [comment]
Can u add this entry into termux elf cleaner ? @fornwall

**Comment by Quasic** [comment]
Could it detect the Android version and only remove the entries unsupported on that version?

**Comment by Droid-MAX** [comment]
Me too, I got the same problem at my Meizu mini m2 Android 5.1

**Comment by Droid-MAX** [comment]
@fornwall Can you build a standard termux-elf-cleaner deb files for Android 5.0 devices? Include arm & aarch64 platform, thanks!

**Comment by Droid-MAX** [comment]
@Hax4us [termux-elf-cleaner#5](https://github.com/termux/termux-elf-cleaner/issues/5)

**Comment by Droid-MAX** [comment]
@Hax4us I solve this problem, you can see my forked repo
https://github.com/Droid-MAX/termux-elf-cleaner

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Meizu m2 发送_

**Comment by Droid-MAX** [comment]
@Hax4us This issue can be closed.

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Meizu m2 发送_

**Comment by Hax4us** [comment]
Nice work @Droid-MAX ....and give a PR

**Comment by Droid-MAX** [comment]
@Hax4us I need to ask fornwall's advice.

**Comment by Droid-MAX** [comment]
@fornwall Will my modified merged into your repo?

**Comment by Droid-MAX** [comment]
@Hax4us https://github.com/termux/termux-elf-cleaner/pull/6

**Comment by Deathlive** [comment]
@Droid-MAX
How to install this ?
https://github.com/Droid-MAX/termux-elf-cleaner
