### ISSUE TITLE
Unable to install python module better_proxy

### ISSUE THREAD

**Issue by AkshiTChauhan-max** [termux/termux-packages#20940]
### Problem description

note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for maturin
      Failed to build maturin
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (maturin)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
.../download/MemeFiV2 $

### What steps will reproduce the bug?

Pip install better_proxy

### System information

```shell
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for maturin
      Failed to build maturin
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (maturin)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
.../download/MemeFiV2 $
```

**Comment by 2096779623** [comment]
```bash
pkg i binutils-is-llvm rust
CARGO_BUILD_TARGET="$(uname -m)-linux-android" pip3 install better-proxy
```

**Comment by twaik** [comment]
Is it still relevant?

**Comment by truboxl** [comment]
@2096779623's command works
