### ISSUE TITLE
[Bug]: created bootstrap-aarch64.zip successfully. but can't work successfully in the termux-play-store/termux-apps project

### ISSUE THREAD

**Issue by RainPlayer** [termux/termux-packages#20946]
### Problem description

hello, i have clone the termux-play-store/termux-apps source code from github, and run it in my android studio successfully. then i clone the termux-play-store/termux-packages sources code too, i want to build the bootstrap-aarch64.zip with the code, the steps are:
1、./scripts/run-docker.sh
2、 ./scripts/run-generate-bootstraps.sh --architectures aarch64

finally, it created bootstrap-aarch64.zip successfully. but when i put it into the termux-play-store/termux-apps project(replace the bootstrap-aarch64.zip download from the online, i have delete the download bootstrap-aarch64.zip code in the build.gradle.kts file), it can not run the termux-app normally. the error i will show in the picture.

I have noticed the difference bettwen the two bootstrap-aarch64.zip. the one download from the online was just 23.2MB, but the one i created was 27.4MB.
actually, i don't care the size difference very much, but the bootstrap-aarch64.zip i created can't work normally. that's a big problem and i don't know why it happened.

PS: I don't change any code from the termux-play-store/termux-apps or termux-play-store/termux-packages.
I hope receive your reply, thank you.

Steps to reproduce the behavior.
1、./scripts/run-docker.sh
2、 ./scripts/run-generate-bootstraps.sh --architectures aarch64
3、delete the download bootstrap-aarch64.zip code in the build.gradle.kts file)
4、replace the bootstrap-aarch64.zip with the one i created.
![Screenshot_20240723_153428](https://github.com/user-attachments/assets/1baa019e-85fd-41a1-9b7a-5c5cb5242b3e)

### What steps will reproduce the bug?

1、./scripts/run-docker.sh
2、 ./scripts/run-generate-bootstraps.sh --architectures aarch64
3、delete the download bootstrap-aarch64.zip code in the build.gradle.kts file)
4、replace the bootstrap-aarch64.zip with the one i created.

### What is the expected behavior?

termux-play-store/termux-apps run normally and can excute linux command successfully.

### System information

```shell
Termux application version: the termux-play-store/termux-apps versionname is googleplay.2024.07.07
Android OS version: Android 12, sumsung
```

**Comment by fornwall** [comment]
@RainPlayer See https://github.com/termux-play-store/termux-apps/issues/32, and use that issue for any eventual follow up issues.
