### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sadsouler** [termux/termux-packages#2095]
[gem_make.out.zip](https://github.com/termux/termux-packages/files/1692492/gem_make.out.zip)
I can not install jekyll using ruby.
Error
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20180204-4805-1e2s5hd.rb extconf.rb
mkmf.rb can't find header files for ruby at /data/data/com.termux/files/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/http_parser.rb-0.6.0/gem_make.out

**Comment by fornwall** [comment]
I think this is the answer (as provided by @Auxilus):

ruby.h is missing, install it by apt install ruby-dev

**Comment by sdrausty** [comment]
@fornwall can we add something similar like:
```
pacman -S base
pacman -S base-devel
```
in [Arch Linux in Termux PRoot](https://github.com/sdrausty/TermuxArch) to `pkg`?  For example:
```
pkg install base
pkg install base-devel
```
The first option would install `coreutils` `findutils` and similar.  Ditto for option two plus developers packages.
