### ISSUE TITLE
[Bug]: megacmd package doesn't work with icu 75

### ISSUE THREAD

**Issue by andruska** [termux/termux-packages#20952]
### Problem description

CANNOT LINK EXECUTABLE "mega-cmd-server": library "libicudata.so.75" not found

### What steps will reproduce the bug?

$ mega-cmd-server

### What is the expected behavior?

Too late to regret. Updated working Termux and now some packages seems to not have recompiled yet. How to solve this ?

### System information

```shell
Termux version 0.118.0
CPU aarch64
Android 10
```

**Comment by TomJo2000** [comment]
`megacmd` was rebuilt as part of the `libicu` update in https://github.com/termux/termux-packages/commit/78a58fdddb380fa6c4f2c06364fda28ff0ec08dc.

Please make sure you are running version `1.7.0-1`.
If your mirror is not serving that version, it is stale 
and you should select a new mirror using `termux-change-repo`

**Comment by andruska** [comment]
This issue is already related to megacmd 1.7.0-1. What else can be wrong here ?

```
$ pkg show megacmd
Package: megacmd
Version: 1.7.0-1
Maintainer: @termux
Installed-Size: 12.4 MB
Depends: c-ares, cryptopp, dbus, ffmpeg, freeimage, libandroid-glob, libc++, libcurl, libsodium, libsqlite, libuv, mediainfo, openssl, pcre, readline, zlib
Homepage: https://mega.io/
Download-Size: 2936 kB
APT-Manual-Installed: yes
APT-Sources: https://mirrors.sau.edu.cn/termux/apt/termux-main stable/main aarch64 Packages
Description: Provides non UI access to MEGA services
```

**Comment by TomJo2000** [comment]
Hmm I can't reproduce the issue locally.
You can try reinstall the `megacmd` package.

Other than that I'm not sure why it would have any issues provided all your packages are up to date.

**Comment by Biswa96** [comment]
What is the output of `apt list | grep libicu` command in termux?

**Comment by andruska** [comment]
`/data/data/com.termux/files/usr/lib/libicudata.*` is missing in my Termux system. It seems to be a dependency problem. All those who have `libicudata.so.75` on their system have got it another way.

```
$ pkg update
Checking availability of current mirror:
[*] https://mirror.vern.cc/termux/termux-main: ok
Hit:1 https://mirror.vern.cc/termux/termux-main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
 $ pkg reinstall megacmd
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/2936 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 24509 files and directories currently installed.)
Preparing to unpack .../megacmd_1.7.0-1_aarch64.deb ...
Unpacking megacmd (1.7.0-1) over (1.7.0-1) ...
Setting up megacmd (1.7.0-1) ...
 $ mega-cmd-server
CANNOT LINK EXECUTABLE "mega-cmd-server": library "libicudata.so.75" not found
```

**Comment by Biswa96** [comment]
Could you try re-installing libicu package with `apt reinstall libicu` command?

**Comment by andruska** [comment]
Thanks !! `apt install libicu` solved this.
