### ISSUE TITLE
Package request: kpcli

### ISSUE THREAD

**Issue by ennoweichert** [termux/termux-packages#2096]
Kpcli is a cli client for KeePass 1.x and 2.x databases.

http://kpcli.sourceforge.net

It would be very useful for admins.

**Comment by xeffyr** [comment]
KeePass client is available as `keepassxc` package in `x11-repo`. It provides tool variants for both X11 and command line. Though as they are linked to Qt5, I do not split package.

Install:
```
pkg install x11-repo
pkg install keepassxc
```

Usage for command line variant:
```
keepassxc-cli <arguments>
```
