### ISSUE TITLE
[Package]: qt6ct

### ISSUE THREAD

**Issue by BHlmaoMSD** [termux/termux-packages#21001]
### Why is it worth to add this package?

> Qt6ct is just like qt5ct - a standalone qt configuration tool.

> We can configure qt6 applications systemwide without depending on lxqt so it would be a lightweight qt6 configuration tool.

### Source code URL

https://github.com/trialuser02/qt6ct

### Packaging policy acknowledgement

- [x] The project is actively developed.
- [x] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [x] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

This might take sometime due to the qt6 transition is not finished yet.

**Comment by Biswa96** [comment]
I have added the package and it's working fine in xfce4 in termux. See the following screenshot.

![qt6ct](https://github.com/user-attachments/assets/3b9257ab-7ddb-41f1-bd7a-277c72c13a63)
