### ISSUE TITLE
[Bug]: gpgme host down

### ISSUE THREAD

**Issue by xoureldeen** [termux/termux-packages#21015]
### Problem description

When i build pacman for my termux fork with custom package name i got thats

Building dependency gpgme if necessary...
termux - building gpgme for arch aarch64...
Downloading ftp://ftp.gnupg.org/gcrypt/gpgme/gpgme-1.23.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- -  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to ftp.gnupg.org port 21 after 237 ms: Connection refused
Warning: Problem : connection refused. Will retry in 30 seconds. 20 retries
Warning: left.

### What steps will reproduce the bug?

./build-package.sh -a aarch64 pacman

### System information

```shell
Ubuntu 22.04 server
16gb ram + swap 32 gb
500gb nvme
I9 13k (kvm server)
```

**Comment by truboxl** [comment]
Fixed by https://github.com/termux/termux-packages/pull/20976
