### ISSUE TITLE
termux-api doesn't pull termux-am

### ISSUE THREAD

**Issue by tomty89** [termux/termux-packages#2101]
Now `$PREFIX/usr/bin/am` is no longer provided by termux-tools but termux-am, which termux-api should hence pull.

**Comment by Emil-7** [comment]
Thank you for this! Since today's update, termux-api methods break with error:

`execv("/data/data/com.termux/files/usr/bin/am"): No such file or directory`

This can be remedied by

`apt install termux-am`

**Comment by fornwall** [comment]
Thanks! As of now the essential `termux-tools` package which every Termux user has installed depends on `termux-am`, which will mean that everyone will get that package pulled in!
