### ISSUE TITLE
Auto update failing for gtkwave

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#21028]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [gtkwave](https://github.com/termux/termux-packages/blob/e2feb95d9ddfe388f0cb425f53e571352241909c/x11-packages/gtkwave) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating gtkwave [Current version: 1:3.3.116]
ERROR: No 'latest-release-tag' found (https://api.github.com/repos/gtkwave/gtkwave/releases/latest).
Try using 'newest-tag'.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-08-02 18:44:19 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/10220035804">10220035804</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by TomJo2000** [comment]
@agnostic-apollo got you that prod breakage you wanted.
(Or at least a minor auto-update oversight)

**Comment by agnostic-apollo** [comment]
lolz, thanks for not disappointing :p

**Comment by TomJo2000** [comment]
Should be a simple matter of adding a `TERMUX_PKG_UPDATE_VERSION_REGEXP`
