### ISSUE TITLE
cryptsetup Package Update Request: From cryptsetup-2.6.1 To cryptsetup-2.7.4

### ISSUE THREAD

**Issue by NoteAfterNote** [termux/termux-packages#21045]
**Source Code:** https://gitlab.com/cryptsetup/cryptsetup

**Termux Package:** https://github.com/termux/termux-packages/tree/master/root-packages/libcryptsetup

**Why:**

1. https://www.kernel.org/pub/linux/utils/cryptsetup/v2.6/v2.6.1-ReleaseNotes

2. https://www.kernel.org/pub/linux/utils/cryptsetup/v2.7/v2.7.1-ReleaseNotes

3. https://www.kernel.org/pub/linux/utils/cryptsetup/v2.7/v2.7.2-ReleaseNotes

4. https://www.kernel.org/pub/linux/utils/cryptsetup/v2.7/v2.7.3-ReleaseNotes

5. https://www.kernel.org/pub/linux/utils/cryptsetup/v2.7/v2.7.4-ReleaseNotes

**Comment by twaik** [comment]
Please don’t request package updates. We’re aware of new releases as soon as they become available.
However, we have a small team and can’t always update every package immediately.
Pull requests are always welcome!
