### ISSUE TITLE
[Bug]: build failed (matplotlib) + (python-scipy)

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#21059]
### Problem description

ERROR: Could not find a version that satisfies the requirement numpy==1.26.5

[job-logs.txt](https://github.com/user-attachments/files/16504869/job-logs.txt)

### What steps will reproduce the bug?

build

### System information

```shell
none
```

**Comment by licy183** [comment]
`numpy==1.26.5` doesn't exist on pypi.

By the way, numpy may be upgraded to 2.0 soon.
