### ISSUE TITLE
[Package]: yazi → `ya` shell utility is missing

### ISSUE THREAD

**Issue by Zeioth** [termux/termux-packages#21054]
### Why is it worth to add this package?

The utility `ya`, (which should be included  when you install yazi), is necessary for programs that integrate yazi, such as neovim through [yazi.nivm](https://github.com/mikavilpas/yazi.nvim).

### Home page URL

https://github.com/sxyazi/yazi

### Source code URL

https://yazi-rs.github.io/

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

Termux package originally submitted [here](https://github.com/termux/termux-packages/tree/8f2046b1fb5e7e721822344ee55a17c3e2b1a491/packages/yazi) by @Biswa96.

**Comment by Zeioth** [comment]
Example of using yazi.nvin on termux.
![Screenshot_20240805_184056_Termux.jpg](https://github.com/user-attachments/assets/0f949fb8-d15c-4f32-b494-d503ce0ae893)

ya is indeed not there
![Screenshot_20240805_184218_Termux.jpg](https://github.com/user-attachments/assets/27aeb0eb-fafa-4065-bacc-7387e3cd24a1)

**Comment by TomJo2000** [comment]
This is a bug report regarding our existing `yazi` package, not a package request for `yazi`/`ya`

**Comment by TomJo2000** [comment]
Had a look around the `yazi` source repo and it seems like we are missing the `ya` executable, and the Nushell and Elvish completions.
I have added both `ya` and the missing completions to be included by the `termux_step_make_install()` function of the yazi build script and will be pushing those changes as a PR shortly.

**Comment by TomJo2000** [comment]
- Should be fixed by #21057, as soon as its merged.

**Comment by Zeioth** [comment]
That was truly fast thank you!! Yazi.nvim work fine now.
![Screenshot_20240805_200752_Termux.jpg](https://github.com/user-attachments/assets/4fa79558-e7ac-401d-9733-97a76316386e)

**Comment by kenis1108** [comment]
> Example of using yazi.nvin on termux. ![Screenshot_20240805_184056_Termux.jpg](https://github.com/user-attachments/assets/0f949fb8-d15c-4f32-b494-d503ce0ae893)
> 
> ya is indeed not there ![Screenshot_20240805_184218_Termux.jpg](https://github.com/user-attachments/assets/27aeb0eb-fafa-4065-bacc-7387e3cd24a1)

Hey!  Cool keyboard. May I ask what input method software you're using? It looks super unique and I'm really interested in trying it out.
