### ISSUE TITLE
It always not downloading when I'm downloading it[Package]: 

### ISSUE THREAD

**Issue by Noahnijel** [termux/termux-packages#21061]
### Why is it worth to add this package?

Pls help

### Home page URL

noahnojel.com

### Source code URL

Iah

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

It always freeze

**Comment by twaik** [comment]
1. Not a valid package request.
2. Url is not accessible.
3. No logs posted.
4. `it always freeze` is not a valid bug report.
