### ISSUE TITLE
[Bug]: swift build failure

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#21060]
### Problem description

ERROR: Wrong NDK version - we need 26b
Error: Process completed with exit code 1.

[job-logs.txt](https://github.com/user-attachments/files/16505291/job-logs.txt)

### What steps will reproduce the bug?

build

### System information

```shell
none
```

**Comment by johndebia2022** [comment]
On NDK17

FAILED: lib/Basic/CMakeFiles/swiftBasic.dir/BasicSourceInfo.cpp.o 
/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang++ -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -DNDEBUG -DSWIFT_THREADING_PTHREADS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/runner/.termux-build/swift/build/swift-android-aarch64/lib/Basic -I/home/runner/.termux-build/swift/src/swift/lib/Basic -I/home/runner/.termux-build/swift/src/swift/stdlib/public/SwiftShims -I/home/runner/.termux-build/swift/build/swift-android-aarch64/include -I/home/runner/.termux-build/swift/src/swift/include -I/home/runner/.termux-build/swift/src/llvm-project/llvm/include -I/home/runner/.termux-build/swift/build/llvm-android-aarch64/include -I/home/runner/.termux-build/swift/src/llvm-project/clang/include -I/home/runner/.termux-build/swift/build/llvm-android-aarch64/tools/clang/include -I/home/runner/.termux-build/swift/src/cmark/src/include -I/home/runner/.termux-build/swift/build/cmark-android-aarch64/src -I/data/data/com.termux/files/usr/include -Wno-unknown-warning-option -Werror=un
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang++ -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -DNDEBUG -DSWIFT_THREADING_PTHREADS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/runner/.termux-build/swift/build/swift-android-aarch64/lib/Basic -I/home/runner/.termux-build/swift/src/swift/lib/Basic -I/home/runner/.termux-build/swift/src/swift/stdlib/public/SwiftShims -I/home/runner/.termux-build/swift/build/swift-android-aarch64/include -I/home/runner/.termux-build/swift/src/swift/include -I/home/runner/.termux-build/swift/src/llvm-project/llvm/include -I/home/runner/.termux-build/swift/build/llvm-android-aarch64/include -I/home/runner/.termux-build/swift/src/llvm-project/clang/include -I/home/runner/.termux-build/swift/build/llvm-android-aarch64/tools/clang/include -I/home/runner/.termux-build/swift/src/cmark/src/include -I/home/runner/.termux-build/swift/build/cmark-android-aarch64/src -I/data/data/com.termux/files/usr/include -Wno-unknown-war
1.	<eof> parser at end of file
2.	/home/runner/.termux-build/swift/src/llvm-project/clang/include/clang/AST/Redeclarable.h:189:14: instantiating function definition 'clang::Redeclarable<clang::TranslationUnitDecl>::getNextRedeclaration'
3.	/home/runner/.termux-build/swift/src/llvm-project/clang/include/clang/AST/Redeclarable.h:122:16: instantiating function definition 'clang::Redeclarable<clang::TranslationUnitDecl>::DeclLink::getPrevious'
4.	/home/runner/.termux-build/swift/src/llvm-project/clang/include/clang/AST/ExternalASTSource.h:410:12: instantiating function definition 'clang::LazyGenerationalUpdatePtr<const clang::Decl *, clang::Decl *, &clang::ExternalASTSource::CompleteRedeclChain>::LazyGenerationalUpdatePtr'
5.	/home/runner/.termux-build/swift/src/llvm-project/clang/include/clang/AST/ASTContext.h:3508:57: instantiating function definition 'clang::LazyGenerationalUpdatePtr<const clang::Decl *, clang::Decl *, &clang::ExternalASTSource::CompleteRedeclChain>::makeValue'
 #0 0x000055d10122e862 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x442e862)
 #1 0x000055d10122d760 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x442d760)
 #2 0x000055d10120074e (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x440074e)
 #3 0x000055d101200876 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x4400876)
 #4 0x00007f0ab2242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x000055d10320350f (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x640350f)
 #6 0x000055d1021da634 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x53da634)
 #7 0x000055d100a0ab53 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x3c0ab53)
 #8 0x000055d102c132c1 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x5e132c1)
 #9 0x000055d102d71c8d (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x5f71c8d)
#10 0x000055d102c21c9e (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x5e21c9e)
#11 0x000055d102d71fde (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x5f71fde)
#12 0x000055d102c21c9e (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x5e21c9e)
#13 0x000055d102d71fde (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x5f71fde)
#14 0x000055d102c21c9e (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x5e21c9e)
#15 0x000055d102d71fde (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x5f71fde)
#16 0x000055d102c21c9e (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x5e21c9e)
#17 0x000055d10312a17f (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x632a17f)
#18 0x000055d103c5ba97 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x6e5ba97)
#19 0x000055d102f7b769 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x617b769)
#20 0x000055d10373f7ba (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x693f7ba)
#21 0x000055d10373f070 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x693f070)
#22 0x000055d10373edb4 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x693edb4)
#23 0x000055d10373e8d0 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x693e8d0)
#24 0x000055d10306acc7 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x626acc7)
#25 0x000055d103069b79 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x6269b79)
#26 0x000055d103069a29 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x6269a29)
#27 0x000055d1030699fe (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x62699fe)
#28 0x000055d10392e356 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x6b2e356)
#29 0x000055d103a07ece (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x6c07ece)
#30 0x000055d103a7c695 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x6c7c695)
#31 0x000055d103bacf37 (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x6dacf37)
#32 0x000055d103bac25e (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x6dac25e)
#33 0x00007f0ab2229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#34 0x00007f0ab2229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#35 0x000055d10350397f (/home/runner/.termux-build/_cache/android-r27-api-24-v0/bin/clang+++0x670397f)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Android (12027248, +pgo, +bolt, +lto, +mlgo, based on r522817) clang version 18.0.1 (https://android.googlesource.com/toolchain/llvm-project d8003a456d14a3deb8054cdaa529ffbf02d9b262)
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /home/runner/.termux-build/_cache/android-r27-api-24-v0/bin
clang++: note: diagnostic msg: 
********************
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/BasicSourceInfo-5fbb2c.cpp
clang++: note: diagnostic msg: /tmp/BasicSourceInfo-5fbb2c.sh
clang++: note: diagnostic msg: 
********************

**Comment by finagolfin** [comment]
This was a bug in the NDK clang that now appears to be fixed.
