### ISSUE TITLE
[Bug]:  NOT WRITING POCO MOBILE KEYBOARD IN TERMUX APP 

### ISSUE THREAD

**Issue by Mafarjulm** [termux/termux-packages#21076]
### Problem description

IF I TYPE SOMETIHNG ELSE IN MY KEYBOARD ITS NOT ADDING IN APP SURFACE 

### What steps will reproduce the bug?

IF I TYPE SOMETIHNG ELSE IN MY KEYBOARD ITS NOT ADDING IN APP SURFACE 

### System information

```shell
ITS BY XIAOMI POCO X5 . ANDROID 14
```

**Comment by twaik** [comment]
Not a valid bug report.
1. That is not termux-app repo.
2. System information field has command you should run in its description.
