### ISSUE TITLE
Adding GLES/EGL support to Termux apps

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#2107]
Hello there. As I mentioned [here](https://github.com/termux/termux-packages/issues/821#issuecomment-363336443) I found a way to share Android Native Window between processes. The library is [here](https://github.com/twaik/libcw). 
Some details of the implementation (the most important):

- Android Native Window is a queue of some `ANativeWindowBuffer`s with a set of some methods manipulating them. 
- ANativeWindowBuffer is a wrapper over gralloc buffer. 
- gralloc buffer can be shared over Binder IPC or UNIX-socket.
- ANativeWindowBuffer can be binded to EGL/GLES texture and drawn on Surface usin shaders. Also the ANativeWindowBufffer can be attached to Surface and queued like a usual GraphicBuffer. That should improve perfomance but I didn't test this option.

**About integration:** for now the output program uses libgui to draw image to Surfaceflinger directly. It draws the shared window on top of other windows. That is a problem. The integration into Termux apk is necessary. I think the app should scan some folder for new UNIX-sockets and open windows the termux apps can bind to (like the button "New session" and bash).

**Comment by sajin01** [comment]
Hello S20

**Comment by twaik** [comment]
@sajin01 What?

**Comment by dianaxxyyzz** [comment]
"Termux apps " are Linux apps that run inside a chroot ,right ? This library will enable  firefox for linux that run inside chroot to have 3d acceleration?

**Comment by twaik** [comment]
Termux apps are apps built for Termux, like cmus or termux-wake-lock. Firefox is X11 app, it means it is hardware acceleration-enabled if running Xorg supports GLX. Termux have no Xorg support yet but I will write xorg-video-android driver when libcw(*1) will be tested and improved. I have already ported Xorg(*2) to android, but it is unusable without video output library. libgui supports video output but it is sdk-dependent and can not be used in non-Java userspace apps without hacks or AOSP-prebuilt binary blobs.   So I will just improve libcw, then I will write xorg driver. And this Xorg will be usable inside chroot with DISPLAY=:0 environment variable. It will behave like XServer XSDL but it will be much faster. And only then I will add GLX support to that server. Something like this. 
(*1) libcw is just the lib which shares drawing surface to another process which is able to draw it to the screen because Android does not support drawing without libgui. libgui is android-version dependent and it is can be built only with AOSP. Dalvik/ART are linked to libgui and that's why only Android apps (apks) can draw images to the screen. That's why I need Termux to support this lib. 
(*2) Xorg built with my built script segfaults on some devices, that's why I want to port it to Termux first.

**Comment by twaik** [comment]
@fornwall I need you to implement window listener in Java side. I can create JNI-bindings to make this lib openable by Java or you can write something like JNI-dlopener for the app..

**Comment by dianaxxyyzz** [comment]
Great explanation  , thank you .
------
"And only then I will add GLX support to that server" . And "Xorg built with my built script segfaults on some devices"
-----
As X11 server  runs great inside chroot or lxc with a dummy driver , can we just modify a component of X11 so  X11 to communicate with a Android app ?
So X11 to command that android app to make some 3d work ,and the android app to give back to X11 the resulted image?
If X11 can just put a android app at work (that app being 3d capable) ,and X11 to receive the result back ...

**Comment by twaik** [comment]
X11 server is Xorg. Xorg running in chroot or LXC uses glibc and it can not use Android libraries such as Android libEGL.so or Android libGLESv2.so. 
> an we just modify a component of X11 so X11 to communicate with a Android app ?

Look at [sparkle driver](https://gitlab.com/mogryph/sparkle) It renders image to the tmpfs and Android app draws it to the screen. It can not draw to the screen without Android app and can not use hardware acceleration. My solution will use the hardware acceleration without any bindings. 

> If X11 can just put a android app at work (that app being 3d capable) ,and X11 to receive the result back

It would be much slower than software acceleration.

> We used long time ago a android app to play sound from Debian that runs inside lxc

And than I found a way to not use Android app...

**Comment by dianaxxyyzz** [comment]
Maybe just try to compile wayland for android cause it support egl , and compile it linked to the  android egl libraries ...

**Comment by twaik** [comment]
It needs libGLESv2 and libEGL in chroot or LXC container too. Tha same problem as with Xorg,

**Comment by twaik** [comment]
I have updated the lib git. 
@fornwall I added GLSurfaceBased activity example. Maybe you can say something to improve it. Or you can just say what to do with lib to be integrated into Termux codebase.

**Comment by twaik** [comment]
@fornwall I think it is ready to be integrated. I need only the activity/GLSurfaceView to be integrated into Termux code and I will be able to improve it. For now the only things needed to be adapted are JNI functio names to match JNI expectations (Java_com_example_SanAngeles_DemoRenderer_onSurfaceCreated -> Java_com_termux_libcwRenderer(?)_onSurfaceCreated)

**Comment by thebestnom** [comment]
any news on this?

**Comment by seisdr** [comment]
What about libhybris

**Comment by twaik** [comment]
No news. Libhybris is just android libc + library loader + some android library wrappers. We do not need to use external bionic and loader because termux uses device's bionic implementation. The only things we can use are wrappers but without universal API for hardware buffers or native windows they are completely useless. So we can not use GLES for rendering separate windows, only the whole screen. That is the reason we can not use EGL/GLES for X11/Wayland apps.

**Comment by RalfWerner** [comment]
Moin @twaik
I am satisfied with your _X11-termux app_ together with Xwayland, except a few restrictions in "direct mode". It is definitely better than Xvnc. Most recently, I worked with proot/ubuntu to avoid the ELF restrictions of Q10-termux - you had [read/detect](https://gitter.im/termux/dev?at=5e65346f85f81e18a8f29a05). Unfortunately I could not yet use _**your app**_ there. Have _**you checked**_ this once and can you give me a [tip](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-594033201) _**what is missing?**_

**Comment by twaik** [comment]
@RalfWernerthe app should be signed with the same key as Termux::App is.

**Comment by RalfWerner** [comment]
> the app should be _**signed**_ with the same key as Termux::App is

@twaik I think _**signing**_ is not the problem, because otherwise I would not be able to install the app, but it worked in the real _**and**_ emulated device in the _termux_ environment. Only in _ubuntu **not!**_
The process PID3 (Xwayland - is different in termux/ubuntu) follows PID2 (x11 is the same for both OS). So PID3 must be stopped in termux before it is started again in _ubuntu._ Three shots from the Q10-emulator session to explain:
![grafik](https://user-images.githubusercontent.com/45426380/76422264-33eac900-63a5-11ea-96bd-84aaa20e2789.png)
Shot 3 is made with nedit (PC-Xserver) from _ubuntu_ and shows the PID3 logs (at the bottom the kill from shot2). I then added: `apt-get install libegl1` in _ubuntu_, and tried again.:
```
X=Xwayland; px=`pgrep -o $X`; x11=com.termux.x11/.MainActivity
export XDG_RUNTIME_DIR=u/tmp; [ -z $px ]&& am start -n $x11; [ -z $px ]&& $X :0>TMP/TX 2>&1 &
```
Then `am` is not found in _ubuntu_ (PID2 - service should still exist, but cannot be recognized with` ps` and
`ln -s /home/u/bin/am u/bin/am` doesn't help) and when I start PID3 I get:
`could not connect to wayland server (EE) Fatal server error: (EE) Couldn't add screen`
Can you _understand/repeat_ that and _**do you still have a solution?**_

**Comment by twaik** [comment]
@RalfWerner how did you install Ubuntu? Using proot? The server creates server socket only in Termux's environment, not Ubuntu's

**Comment by RalfWerner** [comment]
> how did you install Ubuntu? Using proot?

**yes!** What would be an alternative? Are you interested in _install_ script?

**Comment by twaik** [comment]
@RalfWerner even if it will be available to be used from Ubuntu you still wont be able to use Ubuntu's EGL/GLES implementation. Android has different graphical subsystem structure.

**Comment by twaik** [comment]
But if you start Xwayland in Termux you will be able to use it from Ubuntu. Using "export DISPLAY=..."

**Comment by RalfWerner** [comment]
```
[~]$ u uu
a=arm, c= p=proot -b /storage -b /system -b /data -b /dev -b /proc -b /data/data/com.termux/files/home:/home --link2symlink -0 -r ../uu -w /root /usr/bin/env -i   HOME=/root PATH=.:/bin:/sbin:/system/bin RT=uu NL= TERM=xterm LANG=C.UTF-8
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 20116
groups: cannot find name for group ID 50116
uu[~]# pp
  PID  PPID COMM                            ELAPSED
 2102     1 bash                              01:31
 2104  2102 aterm                             01:31
 2140 30128 proot                             00:04
 2144  2140 bash                              00:04
 2158  2144 toybox                            00:00
 8013  7979 bash                         6-04:01:40
 8045     1 sshd                         6-04:01:39
30126  8045 sshd                           03:22:36
30127  8045 sshd                           03:22:35
30128 30126 bash                           03:22:34
30608     1 bash                           03:01:38
30609 30608 Xwayland                       03:01:38
uu[~]# xterm -display :0
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
xterm: DISPLAY is not set
```

**Comment by xeffyr** [comment]
I don't see where `/tmp` was mounted in your command:
```
a=arm, c= p=proot -b /storage -b /system -b /data -b /dev -b /proc -b /data/data/com.termux/files/home:/home --link2symlink -0 -r ../uu -w /root /usr/bin/env -i   HOME=/root PATH=.:/bin:/sbin:/system/bin RT=uu NL= TERM=xterm LANG=C.UTF-8
```

Make `-b $PREFIX/tmp:/tmp`.

**Comment by RalfWerner** [comment]
**aterm** is the XClient from termux. It won't get any better if I finish it. **env** is in _ubuntu_ the same as [above](https://github.com/termux/termux-packages/issues/2107#issuecomment-597648552). I try `export XDG_RUNTIME_DIR=$PREFIX/tmp` with the same effect!
```
uu[~]# export XDG_RUNTIME_DIR=$PREFIX/tmp
uu[~]# ll $PREFIX/tmp
total 11
drwx------.  3 root root 3488 Mar 11 13:12 .
drwx------. 20 root root 3488 Mar 11 16:15 ..
drwxrwxrwt.  2 root root 3488 Mar 11 13:12 .X11-unix
uu[~]# xterm -display :0
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
uu[~]#
```

**Comment by twaik** [comment]
@RalfWerner you did not export DISPLAY

**Comment by RalfWerner** [comment]
XClients from termux _**and**_ ubuntu can be seen here - that's more than I expected and _Xvnc_ can.
everything is fine - _**thanks again!**_ Can you understand/repeat the _"direct mode crash problem"_ and possibly _**solve it?**_
![grafik](https://user-images.githubusercontent.com/45426380/76444995-09106d00-63c5-11ea-8f27-ed690945a7e1.png)

**Comment by twaik** [comment]
For now I am spending all the time at work and don't have a time for development. In a month I am joining IDF, so I won't have a free time.

**Comment by seisdr** [comment]
Someone will be supported by Israel defense force embassy to spoil termux haha

**Comment by Grimler91** [comment]
@seisdr let's be respectful

**Comment by RalfWerner** [comment]
> In a month I am joining IDF, so I won't have a free time

@twaik Good for Israel but bad for termux - how sad! I read 3 years are common. I wish you success as well as God's support and protection for the time. You are apparently still young and very busy, while I'm old and have too much time - deal with A-Studio :)
For _termux-x11:_ I successfully created `*x11.apk` last year with a build process in my debian VB emulation, but _not_ edited it. With _my signing_ I was able to use this plugin on all devices and emulators.
Studio uses a _signes_ so I tried to install [termux-x11](https://github.com/termux/termux-x11/) in **R11** where this is also for _termux-app_ did and got:
![grafik](https://user-images.githubusercontent.com/45426380/76681574-b61cfc80-65f4-11ea-9d91-8e518a5541ff.png)

Can _you_ or @xeffyr give me a _**tip on how to fix this?**_

**Comment by xeffyr** [comment]
> tip on how to fix this?

Uninstall **all** addons & previous Termux app before installing a new one. You are using a different signature key.

**Comment by RalfWerner** [comment]
How can it be? I've installed both APKs one after the other with Studio today and previously uninstalled all termux APKs from the _R11 emulation  - **should I repeat?**_

**Comment by xeffyr** [comment]
termux-x11 does not use our *shared development key*. As result, termux-x11 will have a key different from which is used by termux-app and other addons.

See https://github.com/termux/termux-app/blob/master/app/build.gradle#L34 for more information.

**Comment by RalfWerner** [comment]
Thanks @xeffyr for the tip. Both apps use targetSdkVersion 28 (see shot above) In addition to _x11_, I also use the plugins _Widget_ - already contained the `*keystore*` and _api_ - I copied them from _app_ as with _x11_. This enabled me to create/install three `*.apk` (list) on both emulators - long _wait_ and 65Gb now.

```
WSL[AS]$ ll `find x/wd/ -name "*keystore*"`
-rwxrwxrwx 1 th80wr th80wr 2097 Mar  6 16:10 x/wd/termux-api/app/dev_keystore.jks
-rwxrwxrwx 1 th80wr th80wr 2097 Mar  6 16:10 x/wd/termux-app/app/dev_keystore.jks
-rwxrwxrwx 1 th80wr th80wr 2097 Mar  4 17:23 x/wd/termux-widget/app/dev_keystore.jks
-rwxrwxrwx 1 th80wr th80wr 2097 Mar  6 16:10 x/wd/termux-x11/app/dev_keystore.jks
WSL[AS]$ ll `find x/wd/ -name "*.apk"`
-rwxrwxrwx 1 th80wr th80wr 17486369 Mar 14 11:36 x/wd/termux-app/app/build/outputs/apk/debug/app-debug.apk
-rwxrwxrwx 1 th80wr th80wr    53777 Mar 14 15:05 x/wd/termux-widget/app/build/outputs/apk/debug/app-debug.apk
-rwxrwxrwx 1 th80wr th80wr  2848568 Mar 14 16:52 x/wd/termux-x11/app/build/outputs/apk/debug/app-debug.apk

[~]$ t # start favorite check
Starting: Intent { cmp=com.termux.x11/.MainActivity } Warning: Activity not started, its current task has been brought to the front
IP:10.0.2.16, X:Xwayland/ p=*.xpm *.c bashrc :162034.1 make: /data/data/com.termux/files/home/TMP/check.exe is up to date.
E=> Display not opened! STOP # log: could not connect to wayland server (EE) Fatal server error: (EE) Couldn't add screen

[~]$ pp # process check
PID   PPID  COMMAND          ELAPSED
 8635  1740 com.termux.x11    7h38
 9195  1740 com.termux        7h30
 9274     1 sshd              7h30
10703     1 Xvnc              7h25
16731  9195 bash              1h32
16950 16731 proot             1h24
16960 16950 bash              1h23
17005 16960 nedit             1h19
19083  9195 bash              5:23

[~]$ env # check (partial) with "ln -s ../usr/ u" in $HOME
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so:/data/data/com.termux/files/usr/lib//libandroid-shmem.so
LD_LIBRARY_PATH=/data/data/com.termux/files/home/u/lib
XDG_RUNTIME_DIR=/data/data/com.termux/files/home/u/tmp
```
Compared to my previous checks with `*t32.apk` (shot below shot 1-3).
I could _not_ start **PID3** (Xwayland) so far, but here (app-debug) PID1+2 (9195+8635) is visible. Processes and env are visible in the log above.
Shot 1,2 are from setup, startscreen of my gigaset device (with crash in x11-direct mode). Shot 3 startscreen of Q10 emulator. Shot 4 Studio with _widget_ and _api._
![grafik](https://user-images.githubusercontent.com/45426380/76704143-34ea6600-66d7-11ea-814a-44cd058fcbee.png)
The fourth plugin _**api**_ obviously lacks the _Default Activity_ or is incorrect. _**Questions:**_
- What could be the error in _**PID3**_ (with `*t32.apk` it was still possible yesterday)?
- Where do I've to enter the **API** _Default Activity_ to get this `*.apk`?
- Would _**one**_ `C:\Users\th80wr\.android\dev_keystore.jks` suffice?

**Comment by xeffyr** [comment]
> What could be the error in PID3 (with *t32.apk it was still possible yesterday)?

Crash log is needed. `adb logcat`

> Where do I've to enter the API Default Activity to get this *.apk?

Termux:API is not normal app and don't have default activity.

> Would one C:\Users\th80wr\.android\dev_keystore.jks suffice?

I have added keystore and config recently, so do `git pull origin master` for termux-x11 and do debug build again. It should be signed with correct key.

**Comment by RalfWerner** [comment]
> Crash log is needed. adb logcat

As described in _**Addendum to the PID3 start**_ X11 in api28 works satisfactorily for a _Studio_ emulation. I would repeat that if `targetSdkVersion 29` is possible - thanks so far!
> Termux:API is **not** normal app and don't have default activity.

As described above, I test real devices (shot1: Termux:API 5.18 MB =api28) and emulations in _**Studio**_ (>=api29). Because of **Error** in shot4 I can not do this here - _**what to do?**_
> I have added keystore and config recently, ... for termux-x11 and do debug build again.

Your [patch](https://github.com/termux/termux-x11/commit/d13faa8924afbb2c6c223b1b8af84cd0a4754bbb) I've done in same way. My question was whether _**only one**_ instead of _**four**_ `keystore` files are necessary if **all** plugins use the same file _**is it?**_

**Comment by xeffyr** [comment]
You need to install Termux:API but not run it. Its a plug-in package and not app.

Regarding key - it is one for all APKs. Just added in per-repository mode.
