### ISSUE TITLE
 Problem With Virglrendrer 

### ISSUE THREAD

**Issue by Karimiprogramer** [termux/termux-packages#21089]
I have problem with virglrendrer.
I want to execute glxgears on termux . but in x11 server shows nothing.
terminal output :

https://pastebin.com/74PAsJsN

**Comment by licy183** [comment]
Are you using mesa from Termux repos? `ZINK: warning, this is cpu-based conditional rendering, say bye-bye to fps` is an error message from old mesa.

**Comment by Karimiprogramer** [comment]
Yes . I download all of the packages from official termux repositories and all of them are  latest version.

**Comment by licy183** [comment]
That's strange. Please post your `termux-info` output and `apt list | grep mesa`.

**Comment by Karimiprogramer** [comment]
termux-info :
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=13560
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://repository.su/termux/termux-main/ stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://repository.su/termux/termux-x11/ x11 main
Updatable packages:
command-not-found/stable 2.4.0-37 aarch64 [upgradable from: 2.4.0-36]
termux-tools version:
1.43.2
Android version:
14
Kernel build information:
Linux localhost 5.15.123-android13-3-28444519 #1 SMP PREEMPT Tue Jul 16 14:04:55 +07 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A356E
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.x11 versionCode:15
com.termux.styling versionCode:1000

**Comment by Karimiprogramer** [comment]
apt list | grep mesa :
```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

mesa-demos/x11 9.0.0-4 aarch64
mesa-dev/stable 24.0.8 all
mesa-vulkan-icd-freedreno-dri3/stable 24.0.4 aarch64
mesa-vulkan-icd-freedreno/stable 24.0.8 aarch64
mesa-vulkan-icd-swrast/stable 24.0.8 aarch64
mesa-zink-dev/tur-packages 22.0.5-5 all
mesa-zink-vulkan-icd-freedreno/tur-packages 22.0.5-5 aarch64
mesa-zink-vulkan-icd-swrast/tur-packages 22.0.5-5 aarch64
mesa-zink/tur-packages,now 22.0.5-5 aarch64 [installed]
mesa/stable 24.0.8 aarch64
osmesa-demos/x11 9.0.0-4 aarch64
osmesa-zink/tur-packages 22.0.5-5 aarch64
osmesa/stable 24.0.8 aarch64
virglrenderer-mesa-zink/tur-packages,now 20220627 aarch64 [installed]
```

**Comment by licy183** [comment]
You're using `mesa-zink` from TUR, not `mesa` from Termux main repo. `mesa-zink` doesn't work on many devices.

**Comment by Karimiprogramer** [comment]
thanks for your help. It works very good on native termux but it crashes on proot-distro. Can I describe the problem on proot-distro on this issue or describe it on another issue?

**Comment by licy183** [comment]
The crash may come from the version mismatch from virglrenderer and mesa. You can try to compile mesa from source in your proot-distro.

**Comment by Karimiprogramer** [comment]
Thanks for your help.
