### ISSUE TITLE
[Package Update]: QEMU v9.0.2

### ISSUE THREAD

**Issue by codenamedpkt** [termux/termux-packages#21097]
### Why is it worth to add this package?

See [changelog](https://wiki.qemu.org/ChangeLog/9.0) for details.

### Home page URL

https://qemu.org

### Source code URL

https://gitlab.com/qemu-project/qemu/-/archive/v9.0.2/qemu-v9.0.2.tar.gz

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by twaik** [comment]
No need to ask for package updates. We aware about all package version updates but do not have enough people to process them and update repository.

**Comment by codenamedpkt** [comment]
We would asked you stick on QEMU v9 but not v9.1.0 as current now in release candidate. QEMU v8 will deprecated in few years later.

**Comment by TomJo2000** [comment]
- See also: https://github.com/termux/termux-packages/pull/20516#issue-2349026510

**Comment by codenamedpkt** [comment]
For QEMU v9.1.x, I provide [this guy](https://gitlab.com/qemu-project/qemu/-/archive/v9.1.0-rc1/qemu-v9.1.0-rc1.tar.gz) to try it first.

**Comment by codenamedpkt** [comment]
However they are release candidate, has little unstable. Do not used on daily production.

**Comment by codenamedpkt** [comment]
[This guy](https://gitlab.com/qemu-project/qemu/-/archive/master/qemu-master.tar.gz) is master branch, now in v9.0.91.

**Comment by TomJo2000** [comment]
I can see that.

**Comment by lqvsyi** [comment]
The older version 8.0.2 that can be installed has network issues.
