### ISSUE TITLE
Package request: mu

### ISSUE THREAD

**Issue by ayatakesi** [termux/termux-packages#2109]
Hi.
I build mu-1.0 on my tablet's termux environment and use with isync and emacs.
I want to create pull-request about mu-1.0.
Mu-1.0 depends on existing termux-packages except libgmime-2.6>2.6.7.
Termux-packages' libgmime version is 3.2 and library functions were changed drastic from gmime2.x to gmime3.x so I build gmime-2.6.23 myself.
But I found there is gmime2.6.23 build in termux-packages [here](https://github.com/termux/termux-packages/commit/1ff1b15d1aebf3a27c21dcd062b1da1ad53d5049#diff-f70d2f4fbd00437af57f55bf43bdd7af).
So, is this possible to separate this gmime2.6.23 build from gmime3.2 repository.
Thanks!

**Comment by fornwall** [comment]
http://www.djcbsoftware.nl/code/mu/

**Comment by ayatakesi** [comment]
???
