### ISSUE TITLE
[Package]: uv

### ISSUE THREAD

**Issue by indrastorms** [termux/termux-packages#21096]
### Why is it worth to add this package?

Can't install the package normally.

```bash
curl -LsSf https://astral.sh/uv/install.sh | sh
sh: 1034: ldd: not found
System glibc version (`') is too old; using musl
ERROR: there isn't a package for aarch64-linux-android
```

### Home page URL

https://github.com/astral-sh/uv

### Source code URL

https://github.com/astral-sh/uv

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
This package ***explicitly*** duplicates the functionality provided by `pip` or `pipx`.
So what, besides unproven claims of "more speed" differentiates `uv` from the already provided `python-pip`.

**Comment by indrastorms** [comment]
I don't think they are bluffing about speed they claimed similar with ruff and it's a genuine claim.

As a package manager is hasn't any other significant difentiatives compared to pip

**Comment by TomJo2000** [comment]
I tend to be rather skeptical of any first party benchmarks.
But regardless.

I think this package is *probably* better suited for inclusion in the [TUR](https://github.com/termux-user-repository/tur), since it's essentially `pip` but faster.

---

I can't quite get it building, but it doesn't seem like it would be anything too complicated, just exceeds my knowledge of Rust.

<details><summary>Here's the error I'm getting when it's trying to build the <code>sys-info</code> crate.</summary>
<p>

```styl
error: failed to run custom build command for `sys-info v0.9.1`

Caused by:
  process didn't exit successfully: `/home/builder/.termux-build/python-uv/src/target/release/build/sys-info-42568d11475dc351/build-script-build` (exit status: 1)
  --- stdout
  OUT_DIR = Some(/home/builder/.termux-build/python-uv/src/target/aarch64-linux-android/release/build/sys-info-9532cbfe449f5e48/out)
  TARGET = Some(aarch64-linux-android)
  OPT_LEVEL = Some(3)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CC_aarch64-linux-android
  CC_aarch64-linux-android = None
  cargo:rerun-if-env-changed=CC_aarch64_linux_android
  CC_aarch64_linux_android = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some(aarch64-linux-android-clang)
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  cargo:rerun-if-env-changed=CFLAGS_aarch64-linux-android
  CFLAGS_aarch64-linux-android = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_linux_android
  CFLAGS_aarch64_linux_android = Some( -I/data/data/com.termux/files/usr/include)
  cargo:warning=c/linux.c:96:11: error: call to undeclared library function 'index' with type 'char *(const char *, int)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  cargo:warning=   96 |                 mount = index(procline, ' ');
  cargo:warning=      |                         ^
  cargo:warning=c/linux.c:96:11: note: include the header <strings.h> or explicitly provide a declaration for 'index'
  cargo:warning=1 error generated.

  --- stderr


  error occurred: Command "aarch64-linux-android-clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I/data/data/com.termux/files/usr/include" "-o" "/home/builder/.termux-build/python-uv/src/target/aarch64-linux-android/release/build/sys-info-9532cbfe449f5e48/out/db3b6bfb95261072-linux.o" "-c" "c/linux.c" with args aarch64-linux-android-clang did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
```

</p>
</details> 

And here's the build script.
```bash
# file: tur/python-uv/build.sh
TERMUX_PKG_HOMEPAGE=https://github.com/astral-sh/uv
TERMUX_PKG_DESCRIPTION="An extremely fast Python package installer and resolver, written in Rust."
TERMUX_PKG_LICENSE="Apache-2.0, MIT"
TERMUX_PKG_LICENSE_FILE="LICENSE-APACHE, LICENSE-MIT"
TERMUX_PKG_MAINTAINER="@termux-user-repository"
TERMUX_PKG_VERSION=0.2.35
TERMUX_PKG_SRCURL=https://github.com/astral-sh/uv/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=75233b4fe20715ac2da9e14e35379ed67f025e267fbe63abcb5d607033572c41
TERMUX_PKG_BUILD_DEPENDS='libandroid-support, libbz2, zlib'
TERMUX_PKG_DEPENDS="python"
TERMUX_PKG_PYTHON_COMMON_DEPS="'setuptools>=65.0.0', wheel"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE=latest-release-tag

termux_step_pre_configure() {
	termux_setup_cmake
	termux_setup_rust

	# borrowed from https://github.com/termux/termux-packages/blob/55254de403f139b508cd9fb392c2082b72928a8b/packages/fselect/build.sh#L15-L21
	# Dummy CMake toolchain file to workaround build error:
	# error: failed to run custom build command for `libz-ng-sys v1.1.15`
	# ...
	# CMake Error at /home/builder/.termux-build/_cache/cmake-3.28.3/share/cmake-3.28/Modules/Platform/Android-Determine.cmake:217 (message):
	# Android: Neither the NDK or a standalone toolchain was found.
	export TARGET_CMAKE_TOOLCHAIN_FILE="${TERMUX_PKG_BUILDDIR}/android.toolchain.cmake"
	touch "${TERMUX_PKG_BUILDDIR}/android.toolchain.cmake"
}

termux_step_make() {
	cargo build --jobs $TERMUX_PKG_MAKE_PROCESSES --target $CARGO_TARGET_NAME --release
}

termux_step_make_install() {
	install -Dm755 -t $TERMUX_PREFIX/bin target/${CARGO_TARGET_NAME}/release/uv
}
```

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/10523643838

**Comment by indrastorms** [comment]
Sorry how to fix this?
```
$ uv lock
     error: No interpreter found in managed installations or system path
$ uv python install 3.11
     Searching for Python versions matching: Python 3.11 error: No download found for request: cpython-3.11-linux-aarch64-none
```

**Comment by indrastorms** [comment]
> Are you trying to install Python with `uv`? That would not work as sideloaded software has to be compiled for Termux: https://wiki.termux.com/wiki/Differences_from_Linux
> 
> This applies for all environment management tools such as rustup or nvm.

Then how to fix "no interpreter found" issue?

**Comment by Biswa96** [comment]
The issue is in the uv-python crate. I'll try to come up with a fix or workaround.

```
>>> import sys
>>> sys.path = ["/data/data/com.termux/files/home/uv-0.3.2/crates/uv-python/"] + sys.path
>>> from python.get_interpreter_info import main
>>> main()
{"result": "error", "kind": "libc_not_found"}
```

**Comment by kuyu132** [comment]
@TomJo2000 in Termux application, where the path should I put the buildscript on my phone?

**Comment by TomJo2000** [comment]
I have not touched anything Python related in about 2 years, I am not familiar with `uv`.

Is there any particular reason the `uv` package from the repos isn't gonna work for you?
