### ISSUE TITLE
mutt trash patch

### ISSUE THREAD

**Issue by erji44** [termux/termux-packages#211]
How can I compile and install mutt in termux so it recognizes trash.
At the moment latest mutt on termux complaints about unknown variable set trash= which means mutt has been compiled without trash support patch.

**Comment by its-pointless** [comment]
yeah get patches from here https://github.com/neomutt/neomutt since he is using 1.6 version. The trash patch applies and compiles but i can't bug test your specific use case but for me it is deleteing to trash dir.

**Comment by erji44** [comment]
Thanks for the reply.
I use the same muttrc file on linux and on termux.
Somehow mutt version of termux complains about unrecognized variable trash
set trash="+Trashbin"
This is imap mail setup.
For simplicity i've created Trashbin folder so when i delete a mail goes in Trashbin rather than Trash.
This makes me think mutt version of termux is not compiled with trash patch support.

**Comment by its-pointless** [comment]
Sorry i wasn't clear the termux version does not support trash. I just compiled my own version with trash enabled .

**Comment by fornwall** [comment]
Thanks! I've pushed an updated mutt package (version `1.6.0-1`) which includes the neomutt patches, including the trash patch. Let me know if there is any problem with it!

**Comment by erji44** [comment]
Thank you, works fine now.
Much obliged.
