### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Superstupid-UX** [termux/termux-packages#21103]
### Problem description

mesa-24.0.8 cannot use patch tu_kgsl_export_dmabuf.patch

### What steps will reproduce the bug?

patch -p1 -i tu_kgsl_export_dmabuf.patch

### System information

```shell
patching file src/freedreno/vulkan/tu_device.ccHunk #1 succeeded at 2758 (offset 134 lines).  patching file src/freedreno/vulkan/tu_knl.h    Hunk #1 FAILED at 21.                          1 out of 2 hunks FAILED -- saving rejects to file src/freedreno/vulkan/tu_knl.h.rej           patching file src/freedreno/vulkan/tu_knl_kgsl.cc
```

**Comment by twaik** [comment]
Termux packages' patches are supposed to be used with specific versions of software. Versions of software are specified in `build.sh` files.
