### ISSUE TITLE
bison-3.0.4-1 abort  with -t option

### ISSUE THREAD

**Issue by ayatakesi** [termux/termux-packages#2110]
Hi.

When I use bison on my tablet, it dies only say message 'Aborted'.

```shell
$ cat hello.y
%{
#include <stdio.h>
#include <stdlib.h>

int yylex(void);
int yyerror(const char *s);
 %}

%token HI BYE

%%

program:
        hi bye
        ;

hi:
        HI { printf("Hello World\n"); }
        ;

bye:
        BYE { printf("Bye World\n"); exit(0); }
        ;

$ pkg search bison
Hit:1 https://termux.net stable InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Sorting... Done
Full Text Search... Done
bison/stable,now 3.0.4-1 aarch64 [installed]
  General-purpose parser generator

$ bison -y -t hello.y
Aborted
```

Strange to say, if I downloads same source code and build same configure option M4=m4 as [here](https://github.com/termux/termux-packages/blob/master/packages/bison/build.sh) and useit, I could not reproduce this error.

Can anyone reproduce this?
I have 2 android phone and using termux-0.60 and both signals same error with same message.

**Comment by fornwall** [comment]
@ayatakesi Thanks for reporting!

Can you try updating to the latest `3.0.4-2` version of bison by running `pkg up` and see if that fixes the problem?

**Comment by ayatakesi** [comment]
I tried bison-3.0.4-2 and this release fix this problem. Thanks!
