### ISSUE TITLE
No more touch control for Midnight Commander after last updates

### ISSUE THREAD

**Issue by pest4711** [termux/termux-packages#2112]
Until recently I could control Midnight Commander via touchscreen (change directories, select menu items, etc). After the last apt update / apt upgrade I get weird characters in mc's command line (e.g. ;40M;40M1;10M2 etc). 
I Know how to use mc via keys only, but using the touch screen was a lot easier...

**Comment by fornwall** [comment]
I'm able to reproduce the problem, a guess would be that the ncurses 6.1 update causes it.

**Comment by fornwall** [comment]
Thanks for reporting! This is now fixed in the latest version (4.8.20-1) of the mc package - update by running `pkg up`!
