### ISSUE TITLE
[Package]: offpunk -- An offline-first browser for the small internet

### ISSUE THREAD

**Issue by mglh** [termux/termux-packages#21125]
### Why is it worth to add this package?

**From its Homepage:**

> _Offpunk_ is a command-line and offline-first smolnet browser/feed reader for Gemini, Gopher, Spartan and Web.
> The goal of _Offpunk_ is to be able to synchronise your content once (a day, a week, a month) and then browse/organise it while staying disconnected.

I'm visiting several (mainly text-based) sites / pages frequently, and I would like to have their content available _offline_. The way _Offpunk_ provides access to web content seems to be unique in this regard.

I don't use Gemini, Gopher and Spartan myself. However, I assume that other users might be interested in having those protocols available, with the possibility of storing the content locally for later (offline) access.

**Note:**

_Offpunk_ itself _**is**_ available via pip. But (for me, on my device) it seems to be impossible to get it running because of missing or uncompilable dependencies. (For me) it would be desirable to have all dependencies and all recommendations available as packages in Termux, beside _Offpunk_ itself.

### Home page URL

https://sr.ht/~lioploum/offpunk/

### Source code URL

https://git.sr.ht/~lioploum/offpunk

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by Biswa96** [comment]
Have you tried to install it using `pip install offpunk` command? It installed fine in my system.

```
$ pip install offpunk
Collecting offpunk
  Downloading offpunk-2.2-py3-none-any.whl.metadata (51 kB)
Downloading offpunk-2.2-py3-none-any.whl (84 kB)
Installing collected packages: offpunk
Successfully installed offpunk-2.2
```

**Comment by Biswa96** [comment]
So far no reply from OP. Closing this issue because the program can be installed with pip.
