### ISSUE TITLE
Zphisher problem

### ISSUE THREAD

**Issue by nuclearamen** [termux/termux-packages#21141]
### Problem description

 why I can't make a zphisher link for other devices and other network , far ones I didn't find anyone to explain for me please help .

### What steps will reproduce the bug?

opening zphisher to make a link for instagram

### What is the expected behavior?

Help me or make a tutorial of making a link in zphisher for others devices and networks.

### System information

```shell
Forgot it
```

**Comment by licy183** [comment]
`zphisher` is a hacking tool. Termux's official channels will not offer help to hacking tools. See https://wiki.termux.com/wiki/Hacking.
