### ISSUE TITLE
[Bug]: Missing packages when building termux-tools packages

### ISSUE THREAD

**Issue by DevAnDroidCoder** [termux/termux-packages#21176]
### Problem description

I am tried to update termux tools for my app but I got error of missing dependency.

### What steps will reproduce the bug?

Build termux-tools package without argument `-I`

### System information

```shell
Run declare -a packages
  declare -a packages
  for repo_path in $(jq --raw-output 'del(.pkg_format) | keys | .[]' repo.json); do
    repo=$(jq --raw-output '.["'${repo_path}'"].name' repo.json)
    if [ -f ./built_${repo}_packages.txt ]; then
      packages="$packages $(cat ./built_${repo}_packages.txt | tr '\n' ' ')"
    fi
  done
  
  if [ true == 'false' ]; then
    NDK=$ANDROID_NDK ANDROID_HOME=$ANDROID_SDK_ROOT ./build-package.sh -a arm $packages
  elif [ -n "$packages" ]; then
    ./scripts/run-docker.sh ./build-package.sh -a arm $packages
  fi
  shell: /usr/bin/bash -e {0}
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
Creating new container...
Unable to find image 'ghcr.io/termux/package-builder:latest' locally
latest: Pulling from termux/package-builder
9b857f539cb1: Pulling fs layer
d24da82b95f3: Pulling fs layer
2c4c2fc3faee: Pulling fs layer
de5c9067ef5f: Pulling fs layer
74dee1923210: Pulling fs layer
b7c9d133a0f7: Pulling fs layer
de5c9067ef5f: Waiting
74dee1923210: Waiting
b7c9d133a0f7: Waiting
d24da82b95f3: Verifying Checksum
d24da82b95f3: Download complete
2c4c2fc3faee: Download complete
de5c9067ef5f: Download complete
9b857f539cb1: Verifying Checksum
9b857f539cb1: Download complete
b7c9d133a0f7: Verifying Checksum
b7c9d133a0f7: Download complete
9b857f539cb1: Pull complete
d24da82b95f3: Pull complete
2c4c2fc3faee: Pull complete
de5c9067ef5f: Pull complete
74dee1923210: Verifying Checksum
74dee1923210: Download complete
74dee1923210: Pull complete
b7c9d133a0f7: Pull complete
Digest: sha256:c6ad5a9da424b11a9b5d25837daf73fac6b66d7824909b1420d49b54951c831d
Status: Downloaded newer image for ghcr.io/termux/package-builder:latest
861706f17f687957ffc39cab697ba94de3a2f694636dacced7cb5b9a2c0e1b59
termux - building termux-tools for arch arm...
Downloading https://github.com/termux/termux-elf-cleaner/releases/download/v2.2.1/termux-elf-cleaner
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  471k  100  471k    0     0  2241k      0 --:--:-- --:--:-- --:--:-- 2241k
ERROR: Package libimobiledevice depends on non-existing package "usbmuxd"
ERROR: Obtaining buildorder failed
Error: Process completed with exit code 1.
```

**Comment by Biswa96** [comment]
I have moved usbmuxd to root-packages directory in 6b81c67da15e3bad8ca15c3842e27952650c0501 commit because it requires root permission as discussed in #20827. Should usbmuxd be moved to main packages directory? Or, should all the reverse dependencies of usbmuxd be moved to root-packages directory?

**Comment by DevAnDroidCoder** [comment]
> I have moved usbmuxd to root-packages directory in [6b81c67](https://github.com/termux/termux-packages/commit/6b81c67da15e3bad8ca15c3842e27952650c0501) commit because it requires root permission as discussed in #20827. Should usbmuxd be moved to main packages directory? Or, should all the reverse dependencies of usbmuxd be moved to root-packages directory?

What if I revert that commit for myself?
Will it work?

**Comment by Biswa96** [comment]
> What if I revert that commit for myself?
> Will it work?

Probably. My question is for other maintainers.

**Comment by twaik** [comment]
@Grimler91 did some changes to make libusb work without root, but I do not know if there any progress.

**Comment by agnostic-apollo** [comment]
The `build-order.py` is already passed all package directories, so OP likely has removed `root-packages` directory from `repo.json` and/or from `termux-packages` git repo.

https://github.com/termux/termux-packages/blob/488d5d16540a87f663755773048d02dafdfd9331/scripts/build/termux_step_get_dependencies.sh#L113

There might be other `main` repo packages that depend on packages from `root`/`x11` repo as well. It still could be good policy for core/bootstrap packages to only depend on packages from `main` repo.

**Comment by twaik** [comment]
Should we keep this issue opened or we should close it in prior to #21130?
