### ISSUE TITLE
[Bug]: go raises `SIGSYS: bad system call`

### ISSUE THREAD

**Issue by absolutelynotmonika** [termux/termux-packages#21180]
### Problem description

go raises 
```
SIGSYS: bad system call
PC=0x64ccefc700 m=5 sigcode=1
```
when trying to compile a project/file

### What steps will reproduce the bug?

```
go build
go run
```
or any other project/file-building command

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5260
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
termux-tools version:
1.43.3
Android version:
10
Kernel build information:
Linux localhost 4.9.190+ #1 SMP PREEMPT Wed Mar 8 11:04:15 CST 2023 aarch64 Android
```

**Comment by Biswa96** [comment]
Could you provide the project link to reproduce the issue?

**Comment by absolutelynotmonika** [comment]
it's actually about any file/project, ive tried it on a simple hello world program too and a project made before the latest update (and worked)

**Comment by absolutelynotmonika** [comment]
my bad I closed the issue

**Comment by absolutelynotmonika** [comment]
my bad I closed the issue 
actually its any project and file, even a hello wold

**Comment by absolutelynotmonika** [comment]
_man I really forgot to not close the issue on commenting _

**Comment by Biswa96** [comment]
I can not reproduce the issue with a simple hello world program.

```
$ go run main.go
hello world

$ go version
go version go1.23.0 android/arm64
```

**Comment by absolutelynotmonika** [comment]
yeah im slr

**Comment by absolutelynotmonika** [comment]
it seems to come from the garbage collector from what im reading, the stack trace is really long and I don't if I could or should send all my it

**Comment by absolutelynotmonika** [comment]
i don't really get what I should do, to be honest, i havent opened that many issues before this one.
