### ISSUE TITLE
Swift broken

### ISSUE THREAD

**Issue by naurelius** [termux/termux-packages#21187]
I just updated nodejs to version 22. This required libicu 75 which I also updated.
Well turns out that this broke Swift. I in turn updated Swift, but that did not fix it. is there a way I can have both libicu74 and libicu75?

**Comment by truboxl** [comment]
Please post `termux-info` output

**Comment by naurelius** [comment]
That's exactly what I did. I updated swift from version 5.10.1 to 5.10.1-1 but the issue is still the same. This is the exact output
`CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/swift-driver": library "libicuuc.so.74" not found`.

**Comment by licy183** [comment]
Please use `termux-change-repo` and select the main repository manually (packages-cf.termux.dev), then update all your packages and try again.

**Comment by naurelius** [comment]
Problem fixed. Turns out I only update Swift but did not update the sdk and runtime package. Thanks for all the help.
