### ISSUE TITLE
[Bug]: add pgroonga extension in postgresql

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#21190]
### Problem description

pgroonga is missing

### What steps will reproduce the bug?

Try to use any app that needs pgroonga for searching

### System information

```shell
`termux-info`
```

**Comment by Biswa96** [comment]
Could you provide any real use cases like any command or some procedure? I could try to add the package. This requires groonga package also.

**Comment by TomJo2000** [comment]
Is there a reason this issue isn't a package request for `teldrive`?

**Comment by TomJo2000** [comment]
This sounds like a problem you, and probably only you, are having.

**Comment by TomJo2000** [comment]
I meant no offence.
I like to take a "good cop, bad cop" approach to package requests.
That can come across as somewhat mean, I apologize for that.

For what it's worth I wouldn't have any issue with adding pgroonga as a package.
But I'm not personally interested or currently available to write a build script for it.

**Comment by TomJo2000** [comment]
> [groonga.zip](https://github.com/user-attachments/files/16727389/groonga.zip)
> 

We can't do anything with that.

**Comment by TomJo2000** [comment]
We're gonna need a `build.sh` script.
We can't do anything useful with precompiled binaries, even if they were built for Termux.

We can't reproduce them, we can't update them, we can't ensure they haven't been corrupted or tampered with, and we can't publish them on the repos.

**Comment by Biswa96** [comment]
I have compiled groonga and discussing some issues with pgroonga in upstream.

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/termux/termux-packages/actions/runs/10546238478
