### ISSUE TITLE
[Package]: barrier and / or some of its dependencies (like avahi-compat-libdns_sd)

### ISSUE THREAD

**Issue by Marietto2008** [termux/termux-packages#21209]
### Why is it worth to add this package?

Because it is very comfortable to be able to share mouse and keyboad between systems : on the left for example FreeBSD or Linux or Windows or MacOS (infact barrier can be used in all these OSes) ; and on the other side,termux-x11 installed on Termux on Android. I tried to compile barrier from source like this :

```
# pkg install build-essential git
# git clone https://github.com/debauchee/barrier
# cd barrier
# ./clean_build.sh
```
in this case,unfortunately,it can’t be compiled from source because I can’t install this package : avahi-compat-libdns_sd because it is not present on the repos.

The following packages are missing on the F-Droid repos but necessary for barrier :

```
xorg-dev
g++
libcurl4-openssl-dev
libavahi-compat-libdnssd-dev
libssl-dev
libx11-dev
libqt4-dev
qtbase5-dev
```

### Home page URL

https://github.com/debauchee/barrier

### Source code URL

https://github.com/debauchee/barrier

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by Marietto2008** [comment]
The following packages are missing on the F-Droid repos but necessary for barrier :

```
xorg-dev
g++
libcurl4-openssl-dev
libavahi-compat-libdnssd-dev
libssl-dev
libx11-dev
libqt4-dev
qtbase5-dev
```

**Comment by Biswa96** [comment]
The https://github.com/debauchee/barrier project is not maintained now and the last commit was 2 years ago. You can use scrcpy https://github.com/Genymobile/scrcpy to share mouse and screen between PC and Android phone.

**Comment by Imissmiya962019** [comment]
Okay question what if I'm not trying to link my phone to a computer as in I
don't own a computer so setting up mouse and keyboard would be kind of
useless and I don't own a computer and would only make me more vulnerable
to somebody who does have one and I'm only trying to gain root access orbit
says I have root but nothing else registers that I do I got the Jason foul
I think I'm kind of starting to figure out what I did wrong I need some keys

**Comment by Imissmiya962019** [comment]
Still lost but I'll try aguring those files I don't understand fully how to
write with termux I also have she'll command I'll send ss

**Comment by Marietto2008** [comment]
> The https://github.com/debauchee/barrier project is not maintained now and the last commit was 2 years ago. You can use scrcpy https://github.com/Genymobile/scrcpy to share mouse and screen between PC and Android phone.

scrcpy uses a different technology. It mirrors the Android screen on the PC. Barrier creates a client-server model between the PCs. The second kind of technology is less resource consuming.

**Comment by Marietto2008** [comment]
Hello.

I've copied all the libraries needed by barrier. I see that some libraries aren't detected even if they are on the right place :
```

# ldd barrier

libQt5Widgets.so.5
libQt5Network.so.5
libcrypto.so.3
libdns_sd.so.1
libX11.so.6
libQt5Gui.so.5
libQt5Core.so.5
libstdc++.so.6
libgcc_s.so.1
libc.so.6
ld-linux-aarch64.so.1
```

is there a special command to register them with the system ? something like sudo ldconfig,but this command does not work on termux.

**Comment by Marietto2008** [comment]
Ok. So,I will restore the backupped lib directory and I stop to work on this project,since it is out of my abilities. Its up to you the decision to include it or not.
