### ISSUE TITLE
[Bug]: permission denied on many command executions

### ISSUE THREAD

**Issue by alpha4041** [termux/termux-packages#21219]
### Problem description

I am not sure whether I am missing something but I searched everywhere on the internet and couldn't fix this problem.

My current working directory is `/data/data/com.termux/files/home/aur`, there is an executable which has the execution permission but when I try to run it, I get `bash: ./aur: Permission denied`.

- [x] I installed termux:API from GitHub
- [x] I installed the `termux-api` package
- [x] I ran the `termux-setup-storage` command
- [x] I tried running it as root

This is an example, but I got `ar: permission denied` in other situations, or even the `termux-setup-storage` command gives `libc: Access denied finding property ...` as output.

### What steps will reproduce the bug?

`cd ~`
`git clone https://github.com/kodeaqua/aur`
`cd aur`
`chmod +x aur`
`./aur`

### What is the expected behavior?

The aur executable should run without errors.

### System information

```shell
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1+c553bc2
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~0sfa2xkIbRmqEenDjwtguA==/com.termux-B3d3ypQKAhqulYDeKWYFsw==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=9620
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c132,c258,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c132,c258,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10644
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+661c375
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+661c375
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.bouwhuis.network/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.43.3
Android version:
14
Kernel build information:
Linux localhost 5.4.268-perf-g73afc966421d #1 SMP PREEMPT Sat Aug 10 12:31:46 UTC 2024 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
2109119DG
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

**Comment by freebrowser1** [comment]
Did you use a root shell and is your deviced rooted ?
That can be done by prepending the command with `sudo`. In that case Magisk (or whatever Android root manager you have) will prompt that Termux requests root access.
Whe you consent, the command will be executed as root.

**Comment by truboxl** [comment]
We don't really provide support for 3rd party user scripts. You should seek help from the authors instead. Looking at the script it has mix usage of pkg and other commands. pkg can't be run with root. So you might want to run the script without root for pkg part and with root for the unpack part.

**Comment by damyr4444** [comment]
I'm not rooted and I have same problem

**Comment by freebrowser1** [comment]
Weird.
On my phone it does work and I am not using a root shell (I am rooted, but not for Termux).
```
------------------------------------------------
-                                              -
-   A N D R O I D  U N P A C K  R E P A C K    -
-                                              -
------------------------------------------------
| WELCOME TO AUR SETUP WIZARD!                 |
------------------------------------------------
I: Preparing setup...
I: Update and Installing package(s)
^C
Nothing 2a:~/aur$ ls -al
total 67
drwx------.  3 u0_a229 u0_a229  3452 Mar  8 08:36 .
drwx------. 26 u0_a229 u0_a229  3452 Mar  8 08:36 ..
drwx------.  7 u0_a229 u0_a229  3452 Mar  8 08:36 .git
-rw-------.  1 u0_a229 u0_a229 35149 Mar  8 08:36 LICENSE
-rw-------.  1 u0_a229 u0_a229  1775 Mar  8 08:36 README.md
-rwx------.  1 u0_a229 u0_a229 15433 Mar  8 08:36 aur
Nothing 2a:~/aur$ 
```

**Comment by TomJo2000** [comment]
We do not have a package for this project, nor do we offer official support for it.
I would recommend contacting the author, however it appears they have archived the repository.
So it is safe to assume this is an unmaintained, unsupported, third party tool.
