### ISSUE TITLE
mc not opening subshell

### ISSUE THREAD

**Issue by LaChirla** [termux/termux-packages#2122]
If I press < CTRL - o > in mc I see a shell background, but no subshell is opening.
Normally mc looks at the $SHELL var, then in /etc/password.

Thank you.

**Comment by Quasic** [comment]
Ctrl+o by default only shows console output. It doesn't allow commands to be entered or show something if the previous command cleared the screen (such as running ```clear``` from the command line in the mc display.) It's working for me this way on arm Lollipop.

**Comment by LaChirla** [comment]
On my other linux machines ctrl-o opens a subshell.
The manpage tells.:

       C-o    when the program is being run in the Linux or FreeBSD console or
              under an xterm, it will show you the output of the previous
              command.  When ran on the Linux console, Midnight Commander uses
              an external program (cons.saver) to handle saving and restoring
              of information on the screen.

       When the subshell support is compiled in, you can type C-o at any time
       and you will be taken back to Midnight Commander's main screen, to
       return to your application just type C-o.  If you have an application
       suspended by using this trick, you won't be able to execute other
       programs from Midnight Commander until you terminate the suspended
       application.

In Termux: 
mc -V says, it is build with subshell support.

The mc.edit CTRL-o is pointing to:
usr/bin/open | x /usr/local/bin/open & x /bin/sh
o       Open next a free console
but open does not exists.

Thank you very much!

**Comment by LaChirla** [comment]
Jump in a subshell with CTRL-o works  like expected, if I start mc with:
**SHELL='/data/data/com.termux/files/usr/bin/bash' && mc**
or the shell I want to work with.
Thank you, this issue is closed for me now.
