### ISSUE TITLE
plutolang: transfer as sub-package and prefer php scripts

### ISSUE THREAD

**Issue by cattokomo** [termux/termux-packages#21255]
- Transfer `plutolang` as sub-package of `libpluto`, this follows the convention of `liblua*` and `lua*` package.
- Prefer using PHP scripts found in `scripts/` directory over Makefile as it's much stable and no patches required to build shared and static library.

**Comment by Biswa96** [comment]
What would be the benefit of this change or why is this required?

**Comment by TomJo2000** [comment]
Plutolang being a lua-like would loosely benefit from following the established struction of the `liblua{51,52,53,54,jit}` packages.

Needing PHP as the build system would be a minor pain in the ass.
Nut if Komo feels like making those conformance changes I'm happy to merge them.

**Comment by cattokomo** [comment]
@TomJo2000 I feel like writing Makefile patch is much more pain in the ass than having to write a setup script for PHP :P

**Comment by Biswa96** [comment]
> I feel like writing Makefile patch is much more pain in the ass than having to write a setup script for PHP :P

That would be same as comparing screwdriver with hammer. Use the right tool for the right job.

**Comment by cattokomo** [comment]
> > I feel like writing Makefile patch is much more pain in the ass than having to write a setup script for PHP :P
> 
> That would be same as comparing screwdriver with hammer. Use the right tool for the right job.

IMO writing patches are more of a "Hey, apply this tape until it loosened", once the package got bumped, the patches may or may not work.

**Comment by TomJo2000** [comment]
And patching the PHP build scripts fixes this problem how exactly?
I mean if it's what upstream recommends that's a good enough reason to use them, you don't have to come up with additional reasons.

**Comment by cattokomo** [comment]
> And patching the PHP build scripts fixes this problem how exactly?

The PHP build scripts already added the thing you wanted, like building static and shared library. Unlike the Makefile approach where you need to patch the Makefile to also build a shared library and also use the Termux Builder's `C{,XX,PP}FLAGS`

> I mean if it's what upstream recommends that's a good enough reason to use them, you don't have to come up with additional reasons.

They did recommend to use the PHP build scripts over the modified Makefile from Lua source.
