### ISSUE TITLE
Not find nokogiri-1.12.5

### ISSUE THREAD

**Issue by alisaleh17ali** [termux/termux-packages#21270]
Could` not find nokogiri-1.12.5 in any of the sources
Run `bundle install` to install missing gems.

**Comment by TomJo2000** [comment]
That appears to be a XML/HTML library for Ruby.
https://rubygems.org/gems/nokogiri

You should be able to install it through `gem install nokogiri`.
If you need specifically 1.12.5 use `gem install nokogiri -v 1.12.5`.

I suspect the error message was telling you to do just that, but it appears it didn't paste correctly.

If you're having some other issue with it, providing more details on what you are doing would be immensely helpful.

**Comment by truboxl** [comment]
Closing as resolved until further inquiry from issue author
