### ISSUE TITLE
Can't not update

### ISSUE THREAD

**Issue by mrhidden13** [termux/termux-packages#2128]
apt-get update
Hit:1 https://termux.net stable InRelease
Reading package lists... Error!
W: Problem unlinking the file /data/data/com.termux/files/usr/var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /data/data/com.termux/files/usr/var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
E: Problem renaming the file /data/data/com.termux/files/usr/var/cache/apt/srcpkgcache.bin.k1hfXN to /data/data/com.termux/files/usr/var/cache/apt/srcpkgcache.bin - rename (13: Permission denied)
E: Problem renaming the file /data/data/com.termux/files/usr/var/cache/apt/pkgcache.bin.mbSilO to /data/data/com.termux/files/usr/var/cache/apt/pkgcache.bin - rename (13: Permission denied)
W: You may want to run apt-get update to correct these problems
E: The package cache file is corrupted![](https://i.imgur.com/ktQ7aZA.png)

_Dikirim dari MI 5C menggunakan [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Quasic** [comment]
Have you run the command as root? Try ls -l on those paths. Here's mine:
`````sh
~$ ls -l /data/data/com.termux/files/usr/var/cache/apt
total 1544
drwx------    3 u0_a115  u0_a115       4096 Feb  9 01:39 archives
-rw-r--r--    1 u0_a115  u0_a115     783869 Feb  9 16:43 pkgcache.bin
-rw-r--r--    1 u0_a115  u0_a115     783659 Feb  9 16:43 srcpkgcache.bin
`````

**Comment by easyaspi314** [comment]
I have just encountered that same error.
```
ls -l
total 4                                                        
drwx------ 3 u0_a94 u0_a94 4096 Feb  9 12:11 archives
$
```
Running it as su doesn't help:
```
# apt update
Hit:1 https://termux.net stable InRelease
Err:1 https://termux.net stable InRelease
Splitting up /data/data/com.termux/files/usr/var/lib/apt/lists/termux.net_dists_stable_InRelease into data and signature failed
Reading package lists... Error!
W: No sandbox user '_apt' on the system, can not drop privileges
W: An error occurred during the signature verification.
The repository is not updated and the previous index files will be used. 
GPG error: https://termux.net stable InRelease: Splitting up /data/data/com.termux/files/usr/var/lib/apt/lists/termux.net_dists_stable_InRelease into data and signature failed
W: Failed to fetch https://termux.net/dists/stable/InRelease
Splitting up /data/data/com.termux/files/usr/var/lib/apt/lists/termux.net_dists_stable_InRelease into data and signature failed
W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Unable to parse package file /data/data/com.termux/files/usr/var/lib/apt/lists/termux.net_dists_stable_InRelease (1)
E: The package lists or status file could not be parsed or opened.
```

**Comment by Grimler91** [comment]
See #2066.

**Comment by hishtas** [comment]
apt update
Hit:1 https://termux.net stable InRelease
Hit:2 https://grimler.se root InRelease
Err:3 https://termux.xeffyr.ml extra InRelease
  Failed to connect to termux.xeffyr.ml port 443: Connection timed out
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://termux.xeffyr.ml/dists/extra/InRelease  Failed to connect to termux.xeffyr.ml port 443: Connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by xeffyr** [comment]
> https://termux.xeffyr.ml

@hishtas Who forced you to use non-existent repository address ?
