### ISSUE TITLE
Tor

### ISSUE THREAD

**Issue by nizagotov** [termux/termux-packages#2130]
How to route Termux through tor.

**Comment by Auxilus** [comment]
There is a package called proxychains, @kuburan compiled it for termux, you can install his repo with https://kuburan.guthub.io/kuburan-repo.sh

**Comment by Atavic** [comment]
Typo above: https:///kuburan.github.io/blob/master/kuburan-repo.sh

**Comment by Atavic** [comment]
Typo, corrected:
https:///kuburan.github.io/blob/master/kuburan-repo.sh

**Comment by Atavic** [comment]
Typo, corrected:
https://kuburan.github.io/blob/master/kuburan-repo.sh

**Comment by Atavic** [comment]
Typo, corrected:
https://kuburan.github.io/kuburan-repo.sh

**Comment by nizagotov** [comment]
So no Tor?

**Comment by fornwall** [comment]
Have a look at torsocks (http://web.sas.upenn.edu/clayw/2017/04/02/torifying-lynx-with-torsocks/) which is available as a Termux package. That's the best (although very limited) solution I know of at the moment.
