### ISSUE TITLE
[Question]: Problems when running Brogue

### ISSUE THREAD

**Issue by ErickN13** [termux/termux-packages#21313]
Hey, I'm having problems running the 'Brogue' package, when I go to open the package a screen appears telling me to have a [1] screen, but I don't know what that is, can someone help me?

**Comment by ErickN13** [comment]
`Brogue needs a terminal window that is at least [1
If your terminal can be resized, resize it now.
Press ctrl-c at any time to quit.
Width:  50/100
Height: 40/34




Colors (pairs): 256 (65536)`

**Comment by twaik** [comment]
Checked it now. You must resize (pinch) terminal and it starts working.

**Comment by ErickN13** [comment]
Thanks for the help but I already solved this a few months ago. I'm sorry I didn't close the issue. Thanks!

**Comment by ErickN13** [comment]
Thanks for the help but I already solved this a few months ago. I'm sorry I didn't close the issue. Thanks!
