### ISSUE TITLE
Please help out am facing this

### ISSUE THREAD

**Issue by IamdeiAm** [termux/termux-packages#21314]
Please help out am facing this 
On my Termux on my android phone 

error: "/data/data/com.termux/files/usr/lib/node_modules/node-gyp/bin/node-gyp.js" has bad ELF magic: 23212f75
npm error code 1
npm error path /data/data/com.termux/files/usr/lib/node_modules/truffle/node_modules/bufferutil
npm error command failed
npm error command sh -c node-gyp-build

npm error A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-08-31T16_01_42_647Z-debug-0.log
~ $
~ $

_Originally posted by @IamdeiAm in https://github.com/termux/termux-packages/issues/13293#issuecomment-2322949659_

**Comment by afrhan-repo** [comment]
Can I show the log file?

**Comment by twaik** [comment]
Is this still reproducible?

**Comment by twaik** [comment]
Closing this as not reproducible.
