### ISSUE TITLE
[Bug]: isync: FORTIFY: %n not allowed on Android

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#21323]
### Problem description

There's a problem with the latest update of isync (1.5.0). `mbsync` will fail all commands with
```
~ $ mbsync
FORTIFY: %n not allowed on Android
Aborted
```

This is possibly related to #5595 and #4381. Perhaps a similar solution would work?

### What steps will reproduce the bug?

- Install isync
- run `mbsync`
Arguments or config files don't seem to matter.

### What is the expected behavior?

It used to work fine up until this latest version. Never had that issue.

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.49
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=4217
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb file:///data/data/com.termux/files/home/drive/aptly/public/main/latest main_latest main
deb file:///data/data/com.termux/files/home/drive/aptly/public/main/today main_today main
deb file:///data/data/com.termux/files/home/drive/aptly/public/main/1_days main_1_days main
deb file:///data/data/com.termux/files/home/drive/aptly/public/main/3_days main_3_days main
deb file:///data/data/com.termux/files/home/drive/aptly/public/main/7_days main_7_days main
deb file:///data/data/com.termux/files/home/drive/aptly/public/main/30_days main_30_days main
deb file:///data/data/com.termux/files/home/drive/aptly/public/root/latest root_latest stable
deb file:///data/data/com.termux/files/home/drive/aptly/public/root/today root_today stable
deb file:///data/data/com.termux/files/home/drive/aptly/public/root/1_days root_1_days stable
deb file:///data/data/com.termux/files/home/drive/aptly/public/root/3_days root_3_days stable
deb file:///data/data/com.termux/files/home/drive/aptly/public/root/7_days root_7_days stable
deb file:///data/data/com.termux/files/home/drive/aptly/public/root/30_days root_30_days stable
deb file:///data/data/com.termux/files/home/drive/aptly/public/x11/latest x11_latest main
deb file:///data/data/com.termux/files/home/drive/aptly/public/x11/today x11_today main
deb file:///data/data/com.termux/files/home/drive/aptly/public/x11/1_days x11_1_days main
deb file:///data/data/com.termux/files/home/drive/aptly/public/x11/3_days x11_3_days main
deb file:///data/data/com.termux/files/home/drive/aptly/public/x11/7_days x11_7_days main
deb file:///data/data/com.termux/files/home/drive/aptly/public/x11/30_days x11_30_days main
Updatable packages:
isync/main_latest 1.5.0 aarch64 [upgradable from: 1.4.4]
termux-tools version:
1.43.4
Android version:
14
Kernel build information:
Linux localhost 5.4.280-qgki-g004cf7a2803b #1 SMP PREEMPT Tue Aug 27 04:38:40 UTC 2024 aarch64 Android
Device manufacturer:
Fairphone
Device model:
FP5
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.window versionCode:15
com.termux.api versionCode:49
com.termux.styling versionCode:1000
com.termux.widget versionCode:13
com.termux.boot versionCode:1000
```

**Comment by TobiasEgg** [comment]
The issue (and the same fix) also affects OpenBSD 7.6. mbsync crashes. 

In your fix @licy183 __OpenBSD__ should trigger the same __ANDROID__ 


For the sake of completness the relevant compiler warnings:
config.c:451:41: warning: '%n' format specifier support is deactivated and will call abort(3)
                        nfsnprintf( path, sizeof(path), "%s/%nisyncrc", config_home, &path_len );
                                                            ~^
config.c:453:49: warning: '%n' format specifier support is deactivated and will call abort(3)
                        nfsnprintf( path, sizeof(path), "%s/.config/%nisyncrc", Home, &path_len );
                                                                    ~^
config.c:454:42: warning: '%n' format specifier support is deactivated and will call abort(3)
                nfsnprintf( path2, sizeof(path2), "%s/%n.mbsyncrc", Home, &path_len2 );
                                                      ~^
config.c:483:40: warning: '%n' format specifier support is deactivated and will call abort(3)
                        nfsnprintf( path, sizeof(path), "./%n%s", &cfile.path_len, where );
                                                           ~^


And the crash:
$ mbsync example
Abort trap (core dumped)
