### ISSUE TITLE
[Bug]: white borders around `firefox` right click and sidebar menus

### ISSUE THREAD

**Issue by 813ethan** [termux/termux-packages#21321]
### Problem description

On `firefox` (termux native), a white edge showed up around the right click context menus and the sidebar menu

this problem occurred for multiple versions of firefox , but never got reported

tried adding different options for launching termux-x11 (force-bgra, legacy-drawing...) but none fixed this issue

setting `widget.gtk.native-context-menus` to true in firefox `about:config` changes the right click context menus to native GTK style (which doesn't have white edges), but white edges still not removed in the sidebar menu

sidebar menu
![Screenshot_20240901-210328_Termux_X11](https://github.com/user-attachments/assets/ac93bf84-47b7-488b-8b38-c0c5038e0fe8)

right click context menu
![Screenshot_20240901-210428_Termux_X11](https://github.com/user-attachments/assets/b1bc29a0-1321-4257-883a-9bb760facc4e)

with `widget.gtk.native-context-menus` set
![Screenshot_20240901-210552_Termux_X11](https://github.com/user-attachments/assets/aee6132f-cfab-4b2f-940b-88bd6b4cc8b9)

### What steps will reproduce the bug?

install `firefox` and `termux-x11-nightly`
launch `firefox` on `Termux:x11` (or in any desktop environment)

### What is the expected behavior?

the white edges shouldn't exist (or only a few px wide) and are more rounded

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__APK_FILE=/data/app/~~dllTk59tz_Tal1whq4SopQ==/com.termux-MzPNcKvS4lgZpKrmn3xq4g==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__APP_VERSION_CODE=1020
TERMUX_APP__APP_VERSION_NAME=0.119.0-b1+monet36
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PID=31638
TERMUX_APP__TARGET_SDK=28
TERMUX_VERSION=0.119.0-b1+monet36
TERMUX__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c77,c257,c512,c768
TERMUX__SE_INFO=default:targetSdkVersion=28:complete
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c77,c257,c512,c768
TERMUX__UID=10333
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.43.4
Android version:
14
Kernel build information:
Linux localhost 5.10.218-android12-9-04296-g686e8cd4df17-ab12127007 #1 SMP PREEMPT Tue Jul 23 14:06:11 UTC 2024 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
23049RAD8C
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.window versionCode:15
com.termux.styling versionCode:1000
com.termux.api versionCode:51
com.termux.widget versionCode:13
com.termux.boot versionCode:1000
com.termux.x11 versionCode:15
```

**Comment by IntinteDAO** [comment]
Isn't this caused by the compositor being disabled in Xfce4?

**Comment by 813ethan** [comment]
didn't help even if compositor closed or launched solely by termux-x11

**Comment by 813ethan** [comment]
`termux-x11 :1 -xstartup "firefox"`
without any xfce4 component 
![Uploading Screenshot_20240902-073906_Termux_X11.png…]()

**Comment by 813ethan** [comment]
`termux-x11 :1 -xstartup "firefox"`
without any xfce4 component 
![Screenshot_20240902-073906_Termux_X11](https://github.com/user-attachments/assets/7ac60d36-4e29-4713-b3b1-5d51f25c90d1)

**Comment by IntinteDAO** [comment]
> didn't help even if compositor enabled or firefox launched solely by termux-x11 (instead of using xfce4)

Yep, you need a compositor to have transparencies. It's not releated with Xfce4.

If you want to enable compositor

In "Xfce4 Settings" go to "Window Manager Tweaks", next "Compositor" and Enable them. Otherwise you can install other compositor software like picom

**Comment by 813ethan** [comment]
note that the compositor is **ALWAYS** enabled for me since i reported this issue

enabling the shadows under popup windows checkmark still didnt work for me and the white edge still showed up

**Comment by 813ethan** [comment]
if you dont have this issue in native termux-x11 (NOT proot-distro) firefox, can you please send a screenshot of that? would be appreciated

**Comment by funsafe-ptr** [comment]
Me too! I'm using the `xcompmgr` compositor. Transparency works.

But I don't really mind it. I didn't even notice it until now.
![Screenshot_2024-12-10-20-55-49-88](https://github.com/user-attachments/assets/71016f1c-30e8-4654-9fdf-f435b3d250ca)

**Comment by 813ethan** [comment]
@funsafe-ptr see if the pr works

**Comment by funsafe-ptr** [comment]
Yes, thank you! It works when the compositor is running. Now, instead of white borders, it draws a little shadow. 🌟

![img](https://github.com/user-attachments/assets/e9ce1e93-e614-448b-914f-ab61c46ebd20)

**Comment by 813ethan** [comment]
nice guess it works then :) no more eyesore
