### ISSUE TITLE
Package request: keybase

### ISSUE THREAD

**Issue by justinkelly** [termux/termux-packages#2133]
Hi Termux - would be awesome if keybase could be packaged for termux

I believe there used to be some issues between the termux version of go and the one keybase needs 
- not sure if that is still an issue

related issues
* https://github.com/keybase/client/issues/9152
* https://github.com/keybase/kbfs/issues/1231

Thanks!!! termux on chromeos has been amazing

Justin

**Comment by sdrausty** [comment]
@justinkelly thanks for sharing your thoughts.  Termux is inspiring; Do you?  

```
$ pacman -S keybase
resolving dependencies...
looking for conflicting packages...

Packages (1) keybase-1.0.40-1

Total Download Size:    6.93 MiB
Total Installed Size:  35.39 MiB

:: Proceed with installation? [Y/n]
```

Available today; Out-of-box via https://sdrausty.github.io/TermuxArch/

**Comment by justinkelly** [comment]
@sdrausty can i install arch in termux on an sd card in chromeOS?

**Comment by sdrausty** [comment]
@justinkelly not in Android 5 or 6 afaik.  It might be possible in 7 and beyond.  Do you have execute and symlink permissions on the external card?  It's a no go if you do not have these permissions.

**Comment by tomty89** [comment]
I think it's a matter of whether you format and use the sdcard as internal storage (where the real internal storage will no longer be used or accessible AFAIK). It is an Android 6 feature.

**Comment by tomty89** [comment]
Hmm. What about `/data`? Wouldn't the SD card be used for that? Coz I heard that the real internal storage would not be used anymore.

**Comment by tomty89** [comment]
`/storage/emulated` would probably never be mounted without `noexec` and/or allow symlinks, since they want the behavior to be consistent with the FAT fs family?

**Comment by sdrausty** [comment]
When it's external in Android 6 it's rwxrwxrwx.  As internal it's rw-rw-rw-.  No exec; No symlink on both.

**Comment by arswb** [comment]
now keybase client work in termux. 
![screenshot_20180624-233050](https://user-images.githubusercontent.com/6703134/41821168-c62fc69e-7806-11e8-8a8f-3faf9bd91a64.png)

**Comment by arswb** [comment]
kbfsfuse is also successfully installed. but need root access to mount, my device is not root yet.

![screenshot_20180625-010435](https://user-images.githubusercontent.com/6703134/41822076-5ba9f764-7814-11e8-9805-974d075f6b23.png)

**Comment by philips** [comment]
Put up an initial PR https://github.com/termux/termux-packages/pull/2804

**Comment by philips** [comment]
This needs to merge to get the git stuff working: https://github.com/termux/termux-packages/pull/2811

**Comment by heronhaye** [comment]
Hi, I'm from the Keybase team. About a month ago we moved the KBFS repo to the client repo at https://github.com/keybase/client/tree/master/go/kbfs, so the code in https://github.com/keybase/kbfs/ is out of date and likely will stop working/fail to build in the future. Please update your build scripts. The latest version is 3.0.0. Sorry about the confusion.

**Comment by Eeems** [comment]
@heronhaye it would probably be best to open a new issue and probably @ mention @philips since he did the initial work.
