### ISSUE TITLE
[Package]: Onnxruntime python package 

### ISSUE THREAD

**Issue by afrhan-repo** [termux/termux-packages#21342]
### Why is it worth to add this package?

ONNX Runtime is worth using because it offers cross-platform support, optimized performance, and interoperability for deploying machine learning models. It supports multiple frameworks, accelerates inference, and is highly customizable, making it ideal for production environments in android environment.

I need this because Chromadb (vector database) has dependency of Onnxruntime 

### Home page URL

https://onnxruntime.ai/

### Source code URL

https://github.com/microsoft/onnxruntime

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

It doesn't require any special access.

**Comment by licy183** [comment]
Please test the debs in https://github.com/termux/termux-packages/actions/runs/10723964688. Thanks!

**Comment by afrhan-repo** [comment]
It works perfectly fine with chromadb

> Please test the debs in https://github.com/termux/termux-packages/actions/runs/10723964688. Thanks!

It works perfectly fine with chromadb.

**Comment by gety9** [comment]
@afrhan-repo @licy183 guys, could you please tell how to install it?

when i do 

> pkg install python-onnxruntime

it results in 

```
Installing dependencies through pip...
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
dpkg: error processing package python-onnxruntime (--configure):
 installed python-onnxruntime package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 python-onnxruntime
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

also will installing python-onnxruntime also will install onnx?
cause i need onnx to install https://github.com/Byaidu/PDFMathTranslate
but it results in error
```
Collecting onnx (from pdf2zh)
  Using cached onnx-1.17.0.tar.gz (12.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [227 lines of output]
```

**Comment by licy183** [comment]
I can't reproduce the error when `pkg install python-onnxruntime`.
