### ISSUE TITLE
[Bug]: Crash at startup on Android 6.0.1

### ISSUE THREAD

**Issue by asciibene** [termux/termux-packages#21363]
### Problem description

permissions have been granted already as needed

### What steps will reproduce the bug?

starting app

### What is the expected behavior?

app should start and not crash

### System information

```shell
## Report Info


**User Action**: `plugin execution command`  
**Sender**: `RunCommandService`  
**Report Timestamp**: `2024-09-05 00:52:51.838 UTC`  
##

## RUN_COMMAND Execution Intent Command

**Previous State**: `Pre-Execution`  
**Current State**: `Failed`  
**Executable**: `/system/bin/nc`  
**Arguments:**
**Arg 1**:

-l
```

**Arg 2**:
```
-s
```

**Arg 3**:
```
127.0.0.1
```

**Arg 4**:
```
-p
```

**Arg 5**:
```
48455
```

**Arg 6**:
```
clangd
```

**Arg 7**:
```
--header-insertion-decorators=0
```

**Arg 8**:
```
--completion-style=bundled
```

**Working Directory**: `/storage/emulated/0`  
**Runner**: `app-shell`  
**isFailsafe**: `false`  
**Session Action**: `0`  
**Shell Name**: -  
**Shell Create Mode**: -  
**Set Shell Command Shell Environment**: `false`  
**isPluginExecutionCommand**: `true`  

**Result PendingIntent Creator:** -  

**Stdout**: -  
**Stderr**: -  
**Exit Code**: -  

**Error Code**: `150`  
**Error Message (FileUtils Error)**:
```
The executable regular file not found at path "/system/bin/nc".
```

### Plugin API Help

Visit https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent for more info on RUN_COMMAND Intent usage.
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0+661c375`  
**VERSION_CODE**: `118`  
**UID**: `10116`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app:s0:c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c512,c768`  
**SE_INFO**: `default`  
**TERMUX_APP_PACKAGE_MANAGER**: `APT`  
**TERMUX_APP_PACKAGE_VARIANT**: `APT_ANDROID_5`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0+661c375`  
**VERSION_CODE**: `118`  
**UID**: `10116`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app:s0:c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c512,c768`  
**SE_INFO**: `default`  
##

### Software

**OS_VERSION**: `3.18.20-g8a718a8`  
**SDK_INT**: `23`  
**RELEASE**: `6.0.1`  
**ID**: `MXB48T`  
**DISPLAY**: `MXB48T`  
**INCREMENTAL**: `170201425625b`  
**SECURITY_PATCH**: `2017-01-01`  
**IS_DEBUGGABLE**: `0`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `LGE`  
**BRAND**: `lge`  
**MODEL**: `LG-K557`  
**PRODUCT**: `ph2n_global_ca`  
**BOARD**: `QC_Reference_Phone`  
**HARDWARE**: `ph2n`  
**DEVICE**: `ph2n`  
**SUPPORTED_ABIS**: `armeabi-v7a, armeabi`  
##
```

**Comment by agnostic-apollo** [comment]
Termux does not run `RUN_COMMAND` intents itself by default, you have installed something yourself that is running it. Check your shell rc files like `~/.bashrc`, etc. Moreover, app wouldn't be crashing on `RUN_COMMAND` intent errors, its just showing a notification for failures.
