### ISSUE TITLE
[Bug]: numba does not install via pip

### ISSUE THREAD

**Issue by han5enar** [termux/termux-packages#21377]
### Problem description

numba fails to install properly when using pip. I managed to get llvmlite working, but numba seems to be the final roadblock here. I tried looking for a pkg for numba, but it appears that doesn't exist.

I'm quite new to termux and such but I made sure to look at any and every source about this issue that I could find online and I've been blocked at every turn it seems, so I just don't know what else to do than to submit a bug report and hope that goes somewhere.

Error log:
`Collecting numba                                       Using cached numba-0.60.0.tar.gz (2.7 MB)            Installing build dependencies ... done               Getting requirements to build wheel ... done         Installing backend dependencies ... done             Preparing metadata (pyproject.toml) ... done       Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from numba) (0.43.0)                Requirement already satisfied: numpy<2.1,>=1.22 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from numba) (1.26.5)                          Building wheels for collected packages: numba          Building wheel for numba (pyproject.toml) ... error  error: subprocess-exited-with-error                                                                       × Building wheel for numba (pyproject.toml) did not run successfully.                                     │ exit code: 1                                       ╰─> [68 lines of output]                                 Traceback (most recent call last):                     File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/normal/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>              from . import multiarray                           File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/normal/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>            from . import overrides                            File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/normal/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>              from numpy._core._multiarray_umath import (      ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/normal/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...                                                                                            During handling of the above exception, another exception occurred:                                                                                            Traceback (most recent call last):                     File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/normal/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>                   from numpy.__config__ import show as show_config                                                        File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/normal/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>                   from numpy._core._multiarray_umath import (        File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/normal/lib/python3.11/site-packages/numpy/_core/__init__.py", line 49, in <module>              raise ImportError(msg)                           ImportError:                                                                                              IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!                                                                                             Importing the numpy C-extensions failed. This error can happen for                                        many reasons, often due to issues with your setup or how NumPy was                                        installed.                                                                                                We have compiled some common reasons and troubleshooting tips at:                                                                                                  https://numpy.org/devdocs/user/troubleshooting-importerror.html                                                                                            Please note and check the following:                                                                        * The Python version is: Python3.11 from "/data/data/com.termux/files/usr/bin/python3.11"                 * The NumPy version is: "2.0.2"                                                                         and make sure that they are the versions you expect.                                                      Please carefully study the documentation linked above for further help.                                                                                        Original error was: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/normal/lib/python3.11/site-packages/numpy/_core/_multiarray_umath.cpython-311.so"...                                                                                                                                          The above exception was the direct cause of the following exception:                                                                                           Traceback (most recent call last):                     File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>                main()                                             File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main                    json_out['return_val'] = hook(**hook_input['kwargs'])                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                   File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel             return _build_backend().build_wheel(wheel_directory, config_settings,                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                   File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 421, in build_wheel                                                             return self._build_with_temp_dir(                           ^^^^^^^^^^^^^^^^^^^^^^^^^^                  File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir                                                    self.run_setup()                                   File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 503, in run_setup          super().run_setup(setup_script=setup_script)                                                            File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup          exec(code, locals())                               File "<string>", line 423, in <module>               File "<string>", line 138, in get_ext_modules        File "/data/data/com.termux/files/usr/tmp/pip-build-env-qhsl3q7w/normal/lib/python3.11/site-packages/numpy/__init__.py", line 119, in <module>                   raise ImportError(msg) from e                    ImportError: Error importing numpy: you should not try to import numpy from                                       its source directory; please exit the numpy source tree, and relaunch                                     your python interpreter from there.          [end of output]                                                                                       note: This error originates from a subprocess, and is likely not a problem with pip.                      ERROR: Failed building wheel for numba             Failed to build numba                                ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (numba)`

### What steps will reproduce the bug?

`pip install numba`

### What is the expected behavior?

It installs perfectly fine with no issues and imports fine

### System information

```shell
`Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=10065
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.43.4
Android version:
14
Kernel build information:
Linux localhost 4.19.191-28714460-abA146U1UES8DXG1 #1 SMP PREEMPT Mon Jul 1 23:42:13 KST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A146U1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so`
```

**Comment by licy183** [comment]
`export LDFLAGS="-lpython3.11"`, `export MATHLIB=m` and try again.

**Comment by han5enar** [comment]
Yeah, same issue. It's saying that it can't import numpy, even though I already installed the python-numpy package.

**Comment by han5enar** [comment]
I did see that there are 2 different numpy's, there's the one in termux and the one that comes with numba... so i need to specify which one to use?

**Comment by licy183** [comment]
Do not use the pip build cache.
```
export LDFLAGS="-lpython3.11"
export MATHLIB=m
pip install numba --no-cache-dir
```

**Comment by han5enar** [comment]
Still the same error, but I managed to get it properly installed on debian with proot and everything works perfectly fine on there, so I guess its just a problem with the python environment on termux.

**Comment by licy183** [comment]
I have no idea, but it should not be error like `cannot locate symbol "PyExc_ValueError"`. `--no-cache-dir` will force `pip` not to use the prebuilt `numpy` (maybe bugly as `LDFLAGS="-lpython3.11"` isn't set) and use the fresh-built numpy. If `LDFLAGS="-lpython3.11"` is set, error above should not occur.

Anyway, `numba` will not install properly, as it depends on `llvmlite` and `llvmlite` will require LLVM 14 but Termux has LLVM 18.

**Comment by han5enar** [comment]
Ah oh well then, at least I got it working in debian. Thanks for giving me some things to try out.
