### ISSUE TITLE
Cyclic Dependence

### ISSUE THREAD

**Issue by RajDave-Dev** [termux/termux-packages#21370]
### Problem description

Sorry to post this here. 
I need help in building cgt (glibc) but cgt requires glibc package and glibc itself required cgt. And glibc Pacman community seems pretty inactive. 
How to build the CGT without building glibc, linux-api-headers? 
OR
How to build glibc and linux-api-headers without building CGT, CBT?

I have tried manually building cgt etc but no luck. 
I have tried building glibc, linux-api-headers, cgt but all are dependent on other.
Can I use termux's glibc for building the CGT and then build glibc with that cgt?

Sorry once again 

### What steps will reproduce the bug?

Build Glibc with custom prefix.

### System information

```shell
Ubuntu focal
Amd64
```

**Comment by Maxython** [comment]
> I need help in building cgt (glibc) but cgt requires glibc package and glibc itself required cgt.

If you want to build `cgt` and `cbt` (i.e. `cgct` packages) for your application, you don't need to do this. The ready `cgct` has the ability to change the path (i.e. prefix) to the glibc environment of the application. To do this, you need to configure the same prefix in the `CGCT_APP_PREFIX` variable. For better understanding, here is an example:
```
export CGCT_APP_PREFIX="/data/data/example/glibc"
```

> And glibc Pacman community seems pretty inactive.

If you mean the community on social networks, then this is the first time I hear this (where is it?). If by this community you mean the organization @termux-pacman, then I will be offended...

**Comment by RajDave-Dev** [comment]
So does this means that the cgct that termux provides that can build the Glibc for a custom prefix?

**Comment by RajDave-Dev** [comment]
No, I don't mean the whole community nor the @termux-pacman but still sorry I should not say that

**Comment by RajDave-Dev** [comment]
> > I need help in building cgt (glibc) but cgt requires glibc package and glibc itself required cgt.
> 
> If you want to build `cgt` and `cbt` (i.e. `cgct` packages) for your application, you don't need to do this. The ready `cgct` has the ability to change the path (i.e. prefix) to the glibc environment of the application. To do this, you need to configure the same prefix in the `CGCT_APP_PREFIX` variable. For better understanding, here is an example:
> 
> ```
> export CGCT_APP_PREFIX="/data/data/example/glibc"
> ```
> 
> > And glibc Pacman community seems pretty inactive.
> 
> If you mean the community on social networks, then this is the first time I hear this (where is it?). If by this community you mean the organization @termux-pacman, then I will be offended...

Help..... Again... 😅
When I try to build linux-api-headers I got this error
`ERROR: glibc dynamic linker was not found ('/data/data/com.andio/files/usr/lib/ld-linux-aarch64.so.1')`
And Glibc depends on Linux api headers

**Comment by Biswa96** [comment]
A link to documentation may help OP.

**Comment by Maxython** [comment]
> When I try to build linux-api-headers I got this error

The instruction on how to fix this can be found [here](https://github.com/termux-pacman/glibc-packages/issues/286#issuecomment-2333983973).
