### ISSUE TITLE
Unable to start mpd

### ISSUE THREAD

**Issue by pawelkat** [termux/termux-packages#2137]
Hi,
I get 
```
starting mpd the music player daemon
Segmentation fault
```
when I start mpd.
Here is my strace output:
[https://pastebin.com/4Gx76ypz](https://pastebin.com/4Gx76ypz)
All packages are freshly pulled.

**Comment by fornwall** [comment]
Is this the same problem as https://github.com/termux/termux-packages/issues/2142 (that is, does removing the mpd database as described there cause mpd not to crash on the next startup)?

**Comment by pawelkat** [comment]
No, the database file is not created at all.

**Comment by fornwall** [comment]
@pawelkat Thanks! Could you paste the output of running `termux-info` here?

**Comment by pawelkat** [comment]
Updatable packages:
bash/stable 4.4.19 arm [upgradable from: 4.4.18]
ffmpeg/stable 3.4.2 arm [upgradable from: 3.4.1-1]
libmpdclient/stable 2.14 arm [upgradable from: 2.13]
libx264/stable 20180211 arm [upgradable from: 20170714]
libx265/stable 2.6 arm [upgradable from: 2.5]
mpc/stable 0.29 arm [upgradable from: 0.28-1]
mpv/stable 0.27.2 arm [upgradable from: 0.27.0-1]
ncurses/stable 6.1.20180203 arm [upgradable from: 6.1.20180129]
tsu/stable 1.2 all [upgradable from: 1.1]
System information:
Linux localhost 3.10.40-10100220 #1 SMP PREEMPT Thu Oct 12 15:52:52 KST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
6.0.1
Device manufacturer:
samsung
Device model:
SM-N910F

**Comment by fornwall** [comment]
@pawelkat Thanks! Just to make sure, can you update to latest version of all packages by running `pkg up` and check if the problem remains?

**Comment by pawelkat** [comment]
problem still remains after pkg up

**Comment by Neo-Oli** [comment]
This just got a whole lot worse in the latest update. 
```
 terminating with uncaught exception of type std::__ndk1::system_error: Failed to open /storage/6A3DF11A581D3E00/Android/data/com.termux/files/drive/Music/.mpdignore: No such file or directory
```
MPD now searches for an `.mpdignore` file in every directory in the music library and crashes if there isn't one in **every** subfolder.

**Comment by qi777xj** [comment]
I have same issue with SM-N916K.
The MPD in Google play store doesn't work, either.
Then, is it the issue of MPD itself?

**Comment by Xarchuser** [comment]
Hi, mpd doesn't work here either

my  termux-info : 

```
Updatable packages:
dnsutils/stable 9.13.6-1 arm [upgradable from: 9.13.4]
System information:
Linux localhost 3.10.73-perf-g94fc9a6 #1 SMP PREEMPT Tue Oct 25 19:17:12 CST 2016 aarch64 Android
Termux-packages arch:
arm
Android version:
5.1.1
Device manufacturer:
Xiaomi
Device model:
Redmi Note 3
```

logs

[strace.log](https://gist.githubusercontent.com/Xarchuser/4c7b67cdc1c70785dab5cbe2d6225389/raw/7b5f987950d7be63748666d30d5592248eb7c0c2/gistfile1.txt)

[tracefile.log](https://pastebin.com/4DMypVTy)

**Comment by xeffyr** [comment]
Seems related to https://github.com/termux/termux-packages/issues/3441 which is solved.
