### ISSUE TITLE
[Bug]: pdfplumber install error

### ISSUE THREAD

**Issue by DesiSpymaster** [termux/termux-packages#21399]
### Problem description

Trying to install pdfplumber aborts at "Getting requirements to build wheel" step. See errors. I'm also attaching an 
[err_pdfplumber.txt](https://github.com/user-attachments/files/16923141/err_pdfplumber.txt)
in case the errors pasted here become too unreadable like last time with PyMuPDF.

`
Collecting pdfplumber                             Downloading pdfplumber-0.11.4-py3-none-any.whl.metadata (41 kB)                               Requirement already satisfied: pdfminer.six==20231228 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from pdfplumber) (20231228)                                              Requirement already satisfied: Pillow>=9.1 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from pdfplumber) (10.4.0)           Collecting pypdfium2>=4.18.0 (from pdfplumber)    Downloading pypdfium2-4.30.0.tar.gz (140 kB)    Installing build dependencies ... done          Getting requirements to build wheel ... error   error: subprocess-exited-with-error                                                             × Getting requirements to build wheel did not run successfully.                                 │ exit code: 1                                  ╰─> [178 lines of output]                           ['git', 'ls-remote', 'https://github.com/bblanchon/pdfium-binaries.git'] (cwd=None)             Downloading binary 6693 ...                     Fetching chromium refs ...                      ['git', 'ls-remote', '--sort', '-version:refname', '--tags', 'https://chromium.googlesource.com/chromium/src', '*.*.*.0'] (cwd=None)            Resolved 6693 -> PdfiumVer(major=130, minor=0, build=6693, patch=0)                             Downloading headers...                          Building bindings ...                           INFO: Preprocessing /data/data/com.termux/files/usr/tmp/tmprip46zug.h                           INFO: gcc -E /data/data/com.termux/files/usr/tmp/tmprip46zug.h -dD -D __extension__= -D '__asm__(x)=' -D '__asm(x)=' -D __const=const -D CTYPESGEN=1 -U __GNUC__                                INFO: Parsing /data/data/com.termux/files/usr/tmp/tmprip46zug.h                                 ERROR: /data/data/com.termux/files/usr/include/bits/get_device_api_level_inlines.h:38: Syntax error at '__name'                                 ERROR: /data/data/com.termux/files/usr/include/bits/get_device_api_level_inlines.h:38: Syntax error at '__value'                                ERROR: /data/data/com.termux/files/usr/include/bits/get_device_api_level_inlines.h:39: Syntax error at '__s'                                    ERROR: /data/data/com.termux/files/usr/include/bits/get_device_api_level_inlines.h:39: Syntax error at ';'                                      ERROR: /data/data/com.termux/files/usr/include/bits/get_device_api_level_inlines.h:44: Syntax error at 'int'                                    ERROR: /data/data/com.termux/files/usr/include/asm-generic/int-ll64.h:13: Syntax error at 'short'                                               ERROR: /data/data/com.termux/files/usr/include/asm-generic/int-ll64.h:21: Syntax error at 'long'                                                ERROR: /data/data/com.termux/files/usr/include/linux/types.h:13: Syntax error at '__int128'                                                     ERROR: /data/data/com.termux/files/usr/include/linux/types.h:13: Syntax error at ';'            ERROR: /data/data/com.termux/files/usr/include/linux/types.h:14: Syntax error at '__u128'       ERROR: /data/data/com.termux/files/usr/include/linux/types.h:14: Syntax error at ';'            ERROR: /data/data/com.termux/files/usr/include/linux/time_types.h:24: Syntax error at '__s64'                                                   ERROR: /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/13.2.0/../../../../aarch64-linux-android/include/asm/sigcontext.h:28: Syntax error at '__uint128_t'                        ERROR: /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/13.2.0/../../../../aarch64-linux-android/include/asm/sigcontext.h:28: Syntax error at ';'                                  ERROR: /data/data/com.termux/files/usr/include/sys/user.h:229: Syntax error at '__uint128_t'                                                    ERROR: /data/data/com.termux/files/usr/include/sys/user.h:229: Syntax error at ';'              ERROR: /data/data/com.termux/files/usr/include/sys/user.h:232: Syntax error at '}'              ERROR: /data/data/com.termux/files/usr/include/signal.h:58: Syntax error at 'const'             ERROR: /data/data/com.termux/files/usr/include/signal.h:58: Syntax error at ';'                 ERROR: /data/data/com.termux/files/usr/include/signal.h:62: Syntax error at '__new_action'      ERROR: /data/data/com.termux/files/usr/include/signal.h:62: Syntax error at '__old_action'      ERROR: /data/data/com.termux/files/usr/include/signal.h:71: Syntax error at 'signal'            ERROR: /data/data/com.termux/files/usr/include/signal.h:72: Syntax error at '__set'             ERROR: /data/data/com.termux/files/usr/include/signal.h:78: Syntax error at '__set'
      ERROR: /data/data/com.termux/files/usr/include/signal.h:84: Syntax error at '__set'             ERROR: /data/data/com.termux/files/usr/include/signal.h:90: Syntax error at '__set'             ERROR: /data/data/com.termux/files/usr/include/signal.h:96: Syntax error at '__set'             ERROR: /data/data/com.termux/files/usr/include/signal.h:103: Syntax error at '__set'            ERROR: /data/data/com.termux/files/usr/include/signal.h:109: Syntax error at '__new_set'
      ERROR: /data/data/com.termux/files/usr/include/signal.h:109: Syntax error at '__old_set'        ERROR: /data/data/com.termux/files/usr/include/signal.h:115: Syntax error at '__mask'           ERROR: /data/data/com.termux/files/usr/include/signal.h:121: Syntax error at '__set'            ERROR: /data/data/com.termux/files/usr/include/signal.h:121: Syntax error at '__signal'         ERROR: /data/data/com.termux/files/usr/include/signal.h:150: Syntax error at '__new_signal_stack'                                               ERROR: /data/data/com.termux/files/usr/include/signal.h:150: Syntax error at '__old_signal_stack'                                               ERROR: /data/data/com.termux/files/usr/include/signal.h:152: Syntax error at '__info'
      ERROR: /data/data/com.termux/files/usr/include/signal.h:152: Syntax error at '__msg'            ERROR: /data/data/com.termux/files/usr/include/signal.h:153: Syntax error at '__msg'            ERROR: /data/data/com.termux/files/usr/include/signal.h:164: Syntax error at '__new_set'        ERROR: /data/data/com.termux/files/usr/include/signal.h:164: Syntax error at '__old_set'        ERROR: /data/data/com.termux/files/usr/include/signal.h:174: Syntax error at '__set'            ERROR: /data/data/com.termux/files/usr/include/signal.h:174: Syntax error at '__info'           ERROR: /data/data/com.termux/files/usr/include/signal.h:174: Syntax error at '__timeout'        ERROR: /data/data/com.termux/files/usr/include/signal.h:174: Syntax error at ';'                ERROR: /data/data/com.termux/files/usr/include/signal.h:184: Syntax error at '__set'            ERROR: /data/data/com.termux/files/usr/include/signal.h:184: Syntax error at '__info'           ERROR: /data/data/com.termux/files/usr/include/signal.h:184: Syntax error at ';'                ERROR: /data/data/com.termux/files/usr/include/sys/select.h:98: Syntax error at '__read_fds'                                                    ERROR: /data/data/com.termux/files/usr/include/sys/select.h:98: Syntax error at '__write_fds'                                                   ERROR: /data/data/com.termux/files/usr/include/sys/select.h:98: Syntax error at '__exception_fds'                                               ERROR: /data/data/com.termux/files/usr/include/sys/select.h:98: Syntax error at '__timeout'                                                     ERROR: /data/data/com.termux/files/usr/include/sys/select.h:109: Syntax error at '__read_fds'                                                   ERROR: /data/data/com.termux/files/usr/include/sys/select.h:109: Syntax error at '__write_fds'                                                  ERROR: /data/data/com.termux/files/usr/include/sys/select.h:109: Syntax error at '__exception_fds'                                              ERROR: /data/data/com.termux/files/usr/include/sys/select.h:109: Syntax error at '__timeout'                                                    ERROR: /data/data/com.termux/files/usr/include/sys/select.h:109: Syntax error at '__mask'       ERROR: /data/data/com.termux/files/usr/include/sys/time.h:41: Syntax error at '__tv'            ERROR: /data/data/com.termux/files/usr/include/sys/time.h:41: Syntax error at '__tz'            ERROR: /data/data/com.termux/files/usr/include/sys/time.h:42: Syntax error at '__tv'            ERROR: /data/data/com.termux/files/usr/include/sys/time.h:42: Syntax error at '__tz'            ERROR: /data/data/com.termux/files/usr/include/sys/time.h:44: Syntax error at '__current_value'                                                 ERROR: /data/data/com.termux/files/usr/include/sys/time.h:45: Syntax error at '__new_value'                                                     ERROR: /data/data/com.termux/files/usr/include/sys/time.h:45: Syntax error at '__old_value'                                                     ERROR: /data/data/com.termux/files/usr/include/sys/time.h:47: Syntax error at '__path'          ERROR: /data/data/com.termux/files/usr/include/sys/time.h:47: Syntax error at '2'               ERROR: /data/data/com.termux/files/usr/include/time.h:63: Syntax error at 'tzname'              ERROR: /data/data/com.termux/files/usr/include/time.h:98: Syntax error at 'tm_zone'             ERROR: /data/data/com.termux/files/usr/include/time.h:110: Syntax error at '__t'                ERROR: /data/data/com.termux/files/usr/include/time.h:120: Syntax error at '__duration'         ERROR: /data/data/com.termux/files/usr/include/time.h:120: Syntax error at '__remainder'        ERROR: /data/data/com.termux/files/usr/include/time.h:132: Syntax error at 'asctime'            ERROR: /data/data/com.termux/files/usr/include/time.h:132: Syntax error at '__tm'               ERROR: /data/data/com.termux/files/usr/include/time.h:142: Syntax error at 'asctime_r'          ERROR: /data/data/com.termux/files/usr/include/time.h:142: Syntax error at '__tm'               ERROR: /data/data/com.termux/files/usr/include/time.h:142: Syntax error at '__buf'              ERROR: /data/data/com.termux/files/usr/include/time.h:161: Syntax error at '__tm'               ERROR: /data/data/com.termux/files/usr/include/time.h:186: Syntax error at 'localtime'          ERROR: /data/data/com.termux/files/usr/include/time.h:186: Syntax error at '__t'                ERROR: /data/data/com.termux/files/usr/include/time.h:198: Syntax error at 'localtime_r'        ERROR: /data/data/com.termux/files/usr/include/time.h:198: Syntax error at '__t'                ERROR: /data/data/com.termux/files/usr/include/time.h:198: Syntax error at '__tm'               ERROR: /data/data/com.termux/files/usr/include/time.h:218: Syntax error at '__tm'               ERROR: /data/data/com.termux/files/usr/include/time.h:229: Syntax error at 'gmtime'             ERROR: /data/data/com.termux/files/usr/include/time.h:229: Syntax error at '__t'                ERROR: /data/data/com.termux/files/usr/include/time.h:240: Syntax error at 'gmtime_r'           ERROR: /data/data/com.termux/files/usr/include/time.h:240: Syntax error at '__t'                ERROR: /data/data/com.termux/files/usr/include/time.h:240: Syntax error at '__tm'               ERROR: /data/data/com.termux/files/usr/include/time.h:245: Syntax error at '__tm'               ERROR: /data/data/com.termux/files/usr/include/time.h:253: Syntax error at 'strptime'           ERROR: /data/data/com.termux/files/usr/include/time.h:253: Syntax error at '__s'                ERROR: /data/data/com.termux/files/usr/include/time.h:253: Syntax error at '__fmt'              ERROR: /data/data/com.termux/files/usr/include/time.h:253: Syntax error at '__tm'               ERROR: /data/data/com.termux/files/usr/include/time.h:253: Syntax error at ';'                  ERROR: /data/data/com.termux/files/usr/include/time.h:270: Syntax error at '__buf'              ERROR: /data/data/com.termux/files/usr/include/time.h:270: Syntax error at 'const'              ERROR: /data/data/com.termux/files/usr/include/time.h:270: Syntax error at '__fmt'              ERROR: /data/data/com.termux/files/usr/include/time.h:270: Syntax error at '__tm'               ERROR: /data/data/com.termux/files/usr/include/time.h:270: Syntax error at ';'                  ERROR: /data/data/com.termux/files/usr/include/time.h:275: Syntax error at '__buf'              ERROR: /data/data/com.termux/files/usr/include/time.h:275: Syntax error at 'const'              ERROR: /data/data/com.termux/files/usr/include/time.h:275: Syntax error at '__fmt'              ERROR: /data/data/com.termux/files/usr/include/time.h:275: Syntax error at '__tm'               ERROR: /data/data/com.termux/files/usr/include/time.h:275: Syntax error at ';'                  ERROR: /data/data/com.termux/files/usr/include/time.h:287: Syntax error at 'ctime'              ERROR: /data/data/com.termux/files/usr/include/time.h:287: Syntax error at '__t'                ERROR: /data/data/com.termux/files/usr/include/time.h:297: Syntax error at 'ctime_r'            ERROR: /data/data/com.termux/files/usr/include/time.h:297: Syntax error at '__t'                ERROR: /data/data/com.termux/files/usr/include/time.h:297: Syntax error at '__buf'              ERROR: /data/data/com.termux/files/usr/include/time.h:368: Syntax error at '__clock'            ERROR: /data/data/com.termux/files/usr/include/time.h:368: Syntax error at ';'                  ERROR: /data/data/com.termux/files/usr/include/time.h:378: Syntax error at '__resolution'       ERROR: /data/data/com.termux/files/usr/include/time.h:386: Syntax error at '__ts'               ERROR: /data/data/com.termux/files/usr/include/time.h:397: Syntax error at '__time'             ERROR: /data/data/com.termux/files/usr/include/time.h:397: Syntax error at '__remainder'        ERROR: /data/data/com.termux/files/usr/include/time.h:405: Syntax error at '__ts'               ERROR: /data/data/com.termux/files/usr/include/time.h:413: Syntax error at '__event'            ERROR: /data/data/com.termux/files/usr/include/time.h:421: Syntax error at '__timer'            ERROR: /data/data/com.termux/files/usr/include/time.h:429: Syntax error at '__timer'            ERROR: /data/data/com.termux/files/usr/include/time.h:429: Syntax error at 'const'              ERROR: /data/data/com.termux/files/usr/include/time.h:429: Syntax error at '__new_value'        ERROR: /data/data/com.termux/files/usr/include/time.h:429: Syntax error at '__old_value'        ERROR: /data/data/com.termux/files/usr/include/time.h:437: Syntax error at '_timer'             ERROR: /data/data/com.termux/files/usr/include/time.h:437: Syntax error at '__ts'               ERROR: /data/data/com.termux/files/usr/include/time.h:446: Syntax error at '__timer'            INFO: Processing description list.              INFO: Looking for conflicting names...          'https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F6693/pdfium-linux-arm64.tgz' -> '/data/data/com.termux/files/usr/tmp/pip-install-ohxkr98z/pypdfium2_d4f9fe1f52e14eb28b23fa6b07d81be9/data/linux_arm64/pdfium-linux-arm64.tgz'                                        Traceback (most recent call last):                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>                                                 main()                                        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main                                                     json_out['return_val'] = hook(**hook_input['kwargs'])                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel                             return hook(config_settings)                           ^^^^^^^^^^^^^^^^^^^^^                  File "/data/data/com.termux/files/usr/tmp/pip-build-env-rg1y8wkk/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel                        return self._get_build_requires(config_settings, requirements=[])                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                             File "/data/data/com.termux/files/usr/tmp/pip-build-env-rg1y8wkk/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires                                 self.run_setup()                              File "/data/data/com.termux/files/usr/tmp/pip-build-env-rg1y8wkk/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup                                           exec(code, locals())                          File "<string>", line 161, in <module>          File "<string>", line 156, in main              File "/data/data/com.termux/files/usr/tmp/pip-install-ohxkr98z/pypdfium2_d4f9fe1f52e14eb28b23fa6b07d81be9/setupsrc/pypdfium2_setup/emplace.py", line 70, in prepare_setup                         _get_pdfium_with_cache(pl_name, pdfium_ver, flags, use_v8)                                    File "/data/data/com.termux/files/usr/tmp/pip-install-ohxkr98z/pypdfium2_d4f9fe1f52e14eb28b23fa6b07d81be9/setupsrc/pypdfium2_setup/emplace.py", line 45, in _get_pdfium_with_cache                build_pdfium_bindings(req_ver, flags=req_flags, compile_lds=compile_lds)                      File "/data/data/com.termux/files/usr/tmp/pip-install-ohxkr98z/pypdfium2_d4f9fe1f52e14eb28b23fa6b07d81be9/setupsrc/pypdfium2_setup/packaging_base.py", line 532, in build_pdfium_bindings                                                         run_ctypesgen(DataDir_Bindings, headers_dir, **kwargs)                                        File "/data/data/com.termux/files/usr/tmp/pip-install-ohxkr98z/pypdfium2_d4f9fe1f52e14eb28b23fa6b07d81be9/setupsrc/pypdfium2_setup/packaging_base.py", line 472, in run_ctypesgen                 ctypesgen.__main__.main([str(a) for a in args])                                               File "/data/data/com.termux/files/usr/tmp/pip-build-env-rg1y8wkk/overlay/lib/python3.11/site-packages/ctypesgen/__main__.py", line 33, in main                                                    main_impl(args, cmd_str)                      File "/data/data/com.termux/files/usr/tmp/pip-build-env-rg1y8wkk/overlay/lib/python3.11/site-packages/ctypesgen/__main__.py", line 110, in main_impl                                              processor.process(raw_data, args)             File "/data/data/com.termux/files/usr/tmp/pip-build-env-rg1y8wkk/overlay/lib/python3.11/site-packages/ctypesgen/processor/pipeline.py", line 65, in process                                       check_symbols(data, options)                  File "/data/data/com.termux/files/usr/tmp/pip-build-env-rg1y8wkk/overlay/lib/python3.11/site-packages/ctypesgen/processor/operations.py", line 184, in check_symbols                              libraryloader._register_library(              File "/data/data/com.termux/files/usr/tmp/pip-build-env-rg1y8wkk/overlay/lib/python3.11/site-packages/ctypesgen/libraryloader.py", line 35, in _register_library                                  _libs[name] = dllclass(libpath)                               ^^^^^^^^^^^^^^^^^               File "/data/data/com.termux/files/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__                                                   self._handle = _dlopen(self._name, mode)                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^                                                    OSError: dlopen failed: library "libpthread.so.0" not found: needed by /data/data/com.termux/files/usr/tmp/pip-install-ohxkr98z/pypdfium2_d4f9fe1f52e14eb28b23fa6b07d81be9/data/linux_arm64/libpdfium.so in namespace (default)                 [end of output]                                                                             note: This error originates from a subprocess, and is likely not a problem with pip.          error: subprocess-exited-with-error                                                             × Getting requirements to build wheel did not run successfully.                                 │ exit code: 1                                  ╰─> See above for output.                                                                       note: This error originates from a subprocess, and is likely not a problem with pip.
`

### What steps will reproduce the bug?

`pip install pdfplumber`

### What is the expected behavior?

pdfplumber should be installed without errors.

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=30731
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.zju.edu.cn/termux/apt/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.zju.edu.cn/termux/apt/termux-x11 x11 main
Updatable packages:
termux-x11-nightly/x11 1.03.00-7 all [upgradable from: 1.03.00-0]
termux-tools version:
1.43.4
Android version:
13
Kernel build information:
Linux localhost 4.19.113-27223811 #1 SMP PREEMPT Fri Aug 2 16:38:04 KST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G781B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
com.termux.api versionCode:51
com.termux.tasker versionCode:6
```

**Comment by licy183** [comment]
This is not a bug of Termux.

`pdfplumber` depends on `pypdfium2`, and `pypdfium2` downloads the prebuilt glibc-based arm64 `libpdfium.so`. It cannot be used with Termux.

**Comment by DesiSpymaster** [comment]
> This is not a bug of Termux.
> 
> `pdfplumber` depends on `pypdfium2`, and `pypdfium2` downloads the prebuilt glibc-based arm64 `libpdfium.so`. It cannot be used with Termux.

Ah, okay. Thanks for clarifying. So there's no way to use pdfplumber on Termux? What about compiling from source (Pypdfium2 and then pdfplumber). Would that work?

**Comment by Maxython** [comment]
> So there's no way to use pdfplumber on Termux?

You can use the `python-glibc` package for this, which can work with glibc-based python modules. Here are the commands to set it all up:
```bash
pkg ins glibc-repo
pkg ins python-pip-glibc glibc-runner

# After this command, a shell will be launched that will give access to this python
grun -s
pip install pdfplumber
```

**Comment by DesiSpymaster** [comment]
> > So there's no way to use pdfplumber on Termux?
> 
> You can use the `python-glibc` package for this, which can work with glibc-based python modules. Here are the commands to set it all up:
> 
> ```shell
> pkg ins glibc-repo
> pkg ins python-pip-glibc glibc-runner
> 
> # After this command, a shell will be launched that will give access to this python
> grun -s
> pip install pdfplumber
> ```

Okay, so that did work out, contrary to my usual luck!

`Collecting pdfplumber
  Using cached pdfplumber-0.11.4-py3-none-any.whl.metadata (41 kB)
Collecting pdfminer.six==20231228 (from pdfplumber)
  Downloading pdfminer.six-20231228-py3-none-any.whl.metadata (4.2 kB)
Collecting Pillow>=9.1 (from pdfplumber)
  Downloading pillow-10.4.0-cp311-cp311-manylinux_2_28_aarch64.whl.metadata (9.2 kB)            Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.0-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (48 kB)
Collecting charset-normalizer>=2.0.0 (from pdfminer.six==20231228->pdfplumber)
  Downloading charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (33 kB)                            Collecting cryptography>=36.0.0 (from pdfminer.six==20231228->pdfplumber)                         Downloading cryptography-43.0.1-cp39-abi3-manylinux_2_28_aarch64.whl.metadata (5.4 kB)        Collecting cffi>=1.12 (from cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber)             Downloading cffi-1.17.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber)
  Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Downloading pdfplumber-0.11.4-py3-none-any.whl (59 kB)
Downloading pdfminer.six-20231228-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━ 5.6/5.6 MB 4.0 MB/s eta 0:00:00Downloading pillow-10.4.0-cp311-cp311-manylinux_2_28_aarch64.whl (4.4 MB)                          ━━━━━━━━━━━━━ 4.4/4.4 MB 4.1 MB/s eta 0:00:00
Downloading pypdfium2-4.30.0-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.8 MB)
   ━━━━━━━━━━━━━ 2.8/2.8 MB 4.6 MB/s eta 0:00:00Downloading charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (136 kB)
Downloading cryptography-43.0.1-cp39-abi3-manylinux_2_28_aarch64.whl (3.8 MB)
   ━━━━━━━━━━━━━ 3.8/3.8 MB 4.1 MB/s eta 0:00:00Downloading cffi-1.17.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (469 kB)   Downloading pycparser-2.22-py3-none-any.whl (117 kB)                                            Installing collected packages: pypdfium2, pycparser, Pillow, charset-normalizer, cffi, cryptography, pdfminer.six, pdfplumber
Successfully installed Pillow-10.4.0 cffi-1.17.1 charset-normalizer-3.3.2 cryptography-43.0.1 pdfminer.six-20231228 pdfplumber-0.11.4 pycparser-2.22 pypdfium2-4.30.0`

Many thanks🙏🙏

**Comment by DesiSpymaster** [comment]
> > So there's no way to use pdfplumber on Termux?
> 
> You can use the `python-glibc` package for this, which can work with glibc-based python modules. Here are the commands to set it all up:
> 
> ```shell
> pkg ins glibc-repo
> pkg ins python-pip-glibc glibc-runner
> 
> # After this command, a shell will be launched that will give access to this python
> grun -s
> pip install pdfplumber
> ```

This also managed to install PyMuPdf!
By a simple 
`pip install pymupdf`

I've been struggling with that for ages!

**Comment by mara004** [comment]
Related: https://github.com/pypdfium2-team/pypdfium2/issues/332
We are planning to improve the android/termux support.

There are ways to install pypdfium2 with a native android binary, although slightly obscure. See https://github.com/pypdfium2-team/pypdfium2/issues/332#issuecomment-2546357309 for a recipe.

> and pypdfium2 downloads the prebuilt glibc-based arm64 libpdfium.so

Correct. Because the `platform` module on python3.12 makes the android system appear like a regular linux. Only checking `platform.libc_ver()` reveals that it's actually android. This might change once python3.13 (PEP 738) lands in termux-packages.

**Comment by mara004** [comment]
I think we've implemented experimental android handling in pypdfium2's devel branch, which will be merged soon.
The main credits actually go to Benoît Blanchon for providing the pdfium-binaries on a large variety of platforms, including android (thanks!). pypdfium2 could not exist in this form without the pdfium-binaries project.

For the record, [`sys.getandroidapilevel()`](https://docs.python.org/3/library/sys.html#sys.getandroidapilevel) is probably a more reliable way to detect android prior to PEP 738 than `platform.libc_ver()`.
