### ISSUE TITLE
package request: OpenMP

### ISSUE THREAD

**Issue by tomty89** [termux/termux-packages#2139]
May I ask why we don't have openmp built and shipped as a package like this?
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/openmp
https://www.archlinux.org/packages/extra/x86_64/openmp/files/

These commits make no sense to me:
https://github.com/termux/termux-packages/commit/382e583cbf42e0382d542b232d4b8ac76706fa00
https://github.com/termux/termux-packages/commit/3516aa96ecd915bdf8e2ca5e9e228231459c2691

**Comment by joakim-noah** [comment]
Why do they make no sense to you? We're taking the working OpenMP support in the NDK and simply enabling it in the clang package.

**Comment by tomty89** [comment]
Because there's no reason not to build it from the same version of source as we does for llvm/clang?

**Comment by joakim-noah** [comment]
Oh, that was just done for our convenience, much easier to copy over the pre-built libraries from the NDK than investigate building from source. If you patch it to build from source instead, I'm sure @fornwall will consider it.

**Comment by its-pointless** [comment]
openmp is relatively straight forward. libcompiler_rt is something that is best avoided for now according to the ndk guys.
