### ISSUE TITLE
[Bug]: The description of the python-lxml package is incorrect.

### ISSUE THREAD

**Issue by liuxspro** [termux/termux-packages#21404]
### Problem description

The package `python-lxml` has wrong description

![image](https://github.com/user-attachments/assets/bb21330c-f995-4b70-82a8-beb4506bcef7)

https://github.com/termux/termux-packages/blob/9965665f9864163e134de1342572308b6cf0eae1/packages/python-lxml/build.sh#L2

same as `python-libsass`
https://github.com/termux/termux-packages/blob/9965665f9864163e134de1342572308b6cf0eae1/packages/python-libsass/build.sh#L2

### What steps will reproduce the bug?

```bash
apt show python-lxml
```

### What is the expected behavior?

Short description from https://github.com/lxml/lxml
`The lxml XML toolkit for Python`

### System information

```shell
=
```

**Comment by Biswa96** [comment]
Fixed in 1b1d1fe4b00da9d64fc611f4f024711cbf66bccd
