### ISSUE TITLE
[Package]: filelight

### ISSUE THREAD

**Issue by EngineerDragon** [termux/termux-packages#21401]
### Why is it worth to add this package?

The requested package is required for me in order to clean up my unwanted extra files from my termux workspace. This package provides me proper visualisation for my big files.

### Home page URL

https://apps.kde.org/filelight/

### Source code URL

https://github.com/KDE/filelight

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [x] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [x] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

I managed to build the package. Unfortunately I have encountered an error while building kirigami due to an ambigous error. When I ran it It told me it is unable to find the required qml modules provided by kconfig even though kf6-kconfig package is installed.

Error occured during builing kirigami
```
/data/data/com.termux/files/home/kirigami/src/kirigamiplugin.cpp:73:50: error: use of undeclared identifier 'baseUrl'
   73 |    Kirigami::Platform::StyleSelector::setBaseUrl(baseUrl());
      |                                                  ^
``` If this gets fixed I assume filelight will not give error and work properly

**Comment by Biswa96** [comment]
KDE apps require many dependencies which will flood the termux-packages repository. I am not sure if maintainers would accept that.

**Comment by twaik** [comment]
Most of these dependencies are reusable so probably yes. We should ask @sylirre, @truboxl and @licy183 about that.

**Comment by licy183** [comment]
Adding KDE-related packages is OK for me. Actually, Termux already has lots of them. It would be better to add them in one PR, and use `squash and merge`.

**Comment by Biswa96** [comment]
I like to do it in "tier" basis, like upstream does https://invent.kde.org/packaging/craft-blueprints-kde/-/tree/master/kde/frameworks?ref_type=heads. There could be too many packages.
