### ISSUE TITLE
[Bug]: Nethunter: Downloading rootfs errors to 404

### ISSUE THREAD

**Issue by OdiofO** [termux/termux-packages#21472]
### Problem description

After choosing nethunter package to install it errors, 404: Not Found

##################################################
####  ############# NetHunter ####################

[*] Checking device architecture ...

[1] NetHunter ARM64 (full)
[2] NetHunter ARM64 (minimal)
[3] NetHunter ARM64 (nano)
Enter the image you want to install: 1

[*] Checking package dependencies...
  proot is OK
  tar is OK
  axel is OK
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[*] Downloading rootfs...

--2024-09-13 17:41:09--  https://kali.download/nethunter-images/current/rootfs/kalifs-arm64-full.tar.xz
Resolving kali.download (kali.download)... 2606:4700::6811:feef, 2606:4700::6811:fdef, 104.17.254.239, ...
Connecting to kali.download (kali.download)|2606:4700::6811:feef|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-09-13 17:41:09 ERROR 404: Not Found.
![Screenshot_20240913-174116](https://github.com/user-attachments/assets/ee3be1a0-2c05-4cef-890a-e3349bffafdb)

### What steps will reproduce the bug?

Choosing any of the three nethunter options. 

### What is the expected behavior?

Nethunter install. 

### System information

```shell
~ $ termux-info
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=30683
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.43.4
Android version:
14
Kernel build information:
Linux localhost 5.10.189-android13-4-00012-g1217bb583cc5-ab11174560 #1 SMP PREEMPT Mon Dec 4 18:59:42 UTC 2023 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 7 Pro
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
~ $
```

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-community/blob/site/site/pages/en/rules/hacking.md
