### ISSUE TITLE
[Package]: qrmu-kvm

### ISSUE THREAD

**Issue by lqvsyi** [termux/termux-packages#21492]
### Why is it worth to add this package?

run Windows ARM64 in CPU host mode using qemu-system-aarch64, qemu-kvm is required, But there's no such Package.

### Home page URL

https://qemu.org/

### Source code URL

https://gitlab.com/qemu/qemu

### Packaging policy acknowledgement

- [ ] The project is actively developed.
- [ ] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

Seems to require root access

**Comment by Biswa96** [comment]
For that package, you need KVM support in Linux kernel in your Android OS. KVM is disabled in most of the Android devices.
