### ISSUE TITLE
[Package]: bsdiff

### ISSUE THREAD

**Issue by SergioFLS** [termux/termux-packages#21507]
### Why is it worth to add this package?

Yet another binary diff and patch format. https://github.com/mattcurrie/gb-save-states/ seems to utilise it.
* https://repology.org/project/bsdiff/versions
* http://fileformats.archiveteam.org/wiki/Bsdiff

### Home page URL

https://www.daemonology.net/bsdiff/

### Source code URL

http://deb.debian.org/debian/pool/main/b/bsdiff/bsdiff_4.3.orig.tar.gz

### Packaging policy acknowledgement

- [ ] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

Seems to depend on `bzip2`. Binaries compile with a simple `make` after commenting out lines 13-15 in the `Makefile`.

**Comment by TomJo2000** [comment]
This project does not seem to have seen active development in at least 14 years.
It also largely duplicates the functionality of the standard [GNU `patch`](https://github.com/termux/termux-packages/blob/master/packages/patch/build.sh) utility's [`--binary`](https://man7.org/linux/man-pages/man1/patch.1.html#OPTIONS:~:text=patch/util.c.-,%2D%2Dbinary,-Write%20all%20files) flag.

Unless you can come up with a program that we already package that uses as a major part of its operation there really is not much sense in packaging bsdiff.
