### ISSUE TITLE
package request: tizonia

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#2152]
Cloud music player for the Linux console with support for Spotify, Google Play Music, YouTube, SoundCloud, Dirble and Chromecast. - http://www.tizonia.org
https://github.com/tizonia/tizonia-openmax-il

![tizonia-usage-screencast2](https://user-images.githubusercontent.com/782908/36308796-3a4006ce-1309-11e8-9c7e-27234565606a.gif)

**Comment by tathastu871** [comment]
Dependencies:
```
meson ninja mpg123 mpg123-static boost boost-static python libsqlite libsqlite-static sqlite dbus dbus-static libev libmad liboggz liboggz-static libopus libopus-static opusfile opusfile-static libuuid libuuid-static
```
Missing dependencies:
```
log4c 
```
Installing missing dependencies:
```
wget http://prdownloads.sourceforge.net/log4c/log4c-1.2.4.tar.gz && tar xvf log4c-1.2.4.tar.gz && rm log4c-1.2.4.tar.gz && cd log4c-1.2.4 && ./configure --prefix=$PREFIX && make -j8 && make install

```
Steps:
```
wget https://github.com/tizonia/tizonia-openmax-il/archive/refs/tags/v0.22.0.tar.gz
tar xvf v0.22.0.tar.gz && rm v0.22.0.tar.gz
cd tizonia-openmax-il-0.22.0
meson build
```
Errors:
```
meson.build:90:0: ERROR: Invalid version of dependency, need 'uuid' ['>=2.19.0'] found '1.0.3'.
```

**Comment by xtkoba** [comment]
The build system seems to assume that `uuid` comes from `util-linux`, whereas on Termux it is not. (Note that `util-linux` is configured with `--disable-libuuid`.) I expect that it works by omitting the version check.
