### ISSUE TITLE
[Package]: easyrsa

### ISSUE THREAD

**Issue by marek22k** [termux/termux-packages#21530]
### Why is it worth to add this package?

EasyRSA contains tools for the simple management of certificates (CA, certificate requests, certificate issuance). Although it was originally developed for OpenVPN, it can also be extended for other domains (e.g. website certificates, e-mail certificates and code signing certificates). Furthermore, openvpn is available in the root packages - which is another reason this tool would be a nice addition.

### Source code URL

https://github.com/OpenVPN/easy-rsa/

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by Biswa96** [comment]
The repository does not require packaging. It is just some shell scripts and can be installed as explained here https://github.com/OpenVPN/easy-rsa/blob/master/README.quickstart.md

**Comment by marek22k** [comment]
The manual download works, but I would still prefer it as a package. This is also the case in Arch Linux, for example. I think that would be more user-friendly. Furthermore, there is already a deactivated EasyRSA package in Termux.
