### ISSUE TITLE
[Package]: why has deno been moved into disabled-packages?

### ISSUE THREAD

**Issue by stellarweb008** [termux/termux-packages#21577]
### Why is it worth to add this package?

_(its my first time filing such a report, so please kindly forgive if any mistakes are made or any informations are skipped)_
Deno is the modern javascript backend framework. But when I tried to install it in my phone it doesn't work. I saw a man trying to install it but failing due to disabled architecture ([like here](https://www.reddit.com/r/termux/comments/sh7txc/how_do_you_install_the_deno_package_in_termux/)). My device doesn't fall in that category. But I still can't install it. On further investigation I realised that it's just moved into disabled-packages. Why? Are there any plans to "un-disable" it? 

### Source code URL

https://github.com/termux/termux-packages/tree/master/disabled-packages/deno

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [x] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
The deno package was disabled in commit https://github.com/termux/termux-packages/commit/40efdad80188f0a7a170a1a363274227f44ce181 because it did not function.
- https://github.com/termux/termux-packages/issues/8689

If anybody wants to take the time to fix it up and get it working, PRs are welcome.
