### ISSUE TITLE
[Package]: DropPoint

### ISSUE THREAD

**Issue by icebreaker2005** [termux/termux-packages#21583]
### Why is it worth to add this package?

DropPoint is very siimple to drag and copy paste the files. And collect all files at once and add them on attachment to e-mail or copy to any directory. It makes all fast. Thank you in advance.

### Home page URL

https://droppoint.netlify.app/

### Source code URL

https://github.com/GameGodS3/DropPoint

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [ ] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

DropPoint is very siimple to drag and copy paste the files. And collect all files at once and add them on attachment to e-mail or copy to any directory. It makes all fast. Thank you in advance.

**Comment by TomJo2000** [comment]
This package probably isn't a good fit for Termux as it's a pure JavaScript application and doesn't seem to have any existing packages.

**Comment by TomJo2000** [comment]
Actually it looks like this is an Electron application.
That's not going to work at all, as we currently do not have an Electron or Chromium package in the main repository.

It might be possible to package this on the [TUR](https://github.com/termux-user-repository/tur), however it still looks like a "toy project" without active development or existing packages.
