### ISSUE TITLE
[Bug]: x265 update?

### ISSUE THREAD

**Issue by Randrianasulu** [termux/termux-packages#21584]
### Problem description

not really problem, I tried to update x265

```
TERMUX_PKG_HOMEPAGE=http://x265.org/
TERMUX_PKG_DESCRIPTION="H.265/HEVC video stream encoder library"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
_COMMIT=6318f223684118a2c71f67f3f4633a9e35046b00
_COMMIT_DATE=20240913
TERMUX_PKG_VERSION=4.0-p${_COMMIT_DATE}
#TERMUX_PKG_SRCURL=https://bitbucket.org/multicoreware/x265_git/downloads/x265_$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SRCURL=git+https://bitbucket.org/multicoreware/x265_git
TERMUX_PKG_SHA256=1f08b3e623a9e262bbf4031cae5b4ca3b77ed0252183a0031e95b7fe4d9a5b46
TERMUX_PKG_GIT_BRANCH=master
TERMUX_PKG_DEPENDS="libandroid-posix-semaphore, libc++"
TERMUX_PKG_BREAKS="libx265-dev"
TERMUX_PKG_REPLACES="libx265-dev"
```

it builds (without two source patches), but updating ffmpeg/libheif fails to create packages (oom?)

### What steps will reproduce the bug?

x265 currently at 3.5+git, version 4.0 was released

https://bitbucket.org/multicoreware/x265_git/commits/6318f223684118a2c71f67f3f4633a9e35046b00

### What is the expected behavior?

new x265 version 4.0 for new aarch64 acceleration

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=16989
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://repository.su/termux/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://repository.su/termux/termux-x11/ x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.43.5
Android version:
11
Kernel build information:
Linux localhost 4.14.193 #1 SMP PREEMPT Thu Jul 8 13:58:00 CST 2021 aarch64 Android
Device manufacturer:
DEXP
Device model:
K38
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

**Comment by Randrianasulu** [comment]
for ffmpeg 6.1.2 may be this patch will be needed

http://git.ffmpeg.org/gitweb/ffmpeg.git/commit/f749aaf108696fcfc2be6a9f6c1059415474caf3

**Comment by TomJo2000** [comment]
Would you mind providing your full modifications to the `libx265/build.sh` script?
Either as a diff or the full file.

**Comment by Randrianasulu** [comment]
> Would you mind providing your full modifications to the `libx265/build.sh` script? Either as a diff or the full file.

[libx265_update_aarch64.txt](https://github.com/user-attachments/files/17155175/libx265_update_aarch64.txt)

**Comment by Randrianasulu** [comment]
[ffmpeg_libx265_update.patch](https://github.com/user-attachments/files/17155187/ffmpeg_libx265_update.patch)

and this is ffmpeg 6.1.2 patch. (without it x265 encoding fails)
I am not sure about removed x265 patches, at least first was failed, may be they need  careful re-apply for arm7 ?

**Comment by Randrianasulu** [comment]
for libheif you need this patch:

https://github.com/strukturag/libheif/commit/4d9d27e0b2580de23f7c620aeed5553554e19f95.diff

**Comment by Randrianasulu** [comment]
now I see 4.1 in tree, upgraded as ffmpeg dep. Thanks
