### ISSUE TITLE
[Bug]: "cp -a" fails on symbolic links

### ISSUE THREAD

**Issue by gerdolf** [termux/termux-packages#21597]
### Problem description

'cp' with "-a" on a symbolic link gives:
cp: failed to restore the default file creation context: Permission denied

### What steps will reproduce the bug?
<sup>Maintainer note: example edited for clarity</sup>
```bash
ln -s foo foo.ln
cp -a foo.ln foo.copy
# cp: failed to restore the default file creation context: Permission denied
```

### What is the expected behavior?

Should succeed

### System information

```shell
coreutils/stable,now 9.5-2 aarch64
(Android 14 on Pixel Fold)
```

**Comment by agnostic-apollo** [comment]
And it begins :p

**Comment by TomJo2000** [comment]
I've done a little bit of digging and found the following.

```styl
// system cp
ldd /bin/cp
        libcrypto.so => /system/lib64/libcrypto.so
        libz.so => /system/lib64/libz.so
        liblog.so => /system/lib64/liblog.so
        libprocessgroup.so => /system/lib64/libprocessgroup.so
        libselinux.so => /system/lib64/libselinux.so
        libc.so => /system/lib64/libc.so
        libm.so => /system/lib64/libm.so
        libdl.so => /system/lib64/libdl.so
        ld-android.so => /system/lib64/ld-android.so
        libc++.so => /system/lib64/libc++.so
        libbase.so => /system/lib64/libbase.so
        libcgrouprc.so => /system/lib64/libcgrouprc.so
        libpcre2.so => /system/lib64/libpcre2.so
        libpackagelistparser.so => /system/lib64/libpackagelistparser.so

// Termux cp
ldd $PREFIX/bin/cp
        libandroid-support.so => /data/data/com.termux/files/usr/lib/libandroid-support.so
        libandroid-selinux.so => /data/data/com.termux/files/usr/lib/libandroid-selinux.so
        libgmp.so => /data/data/com.termux/files/usr/lib/libgmp.so
        libiconv.so => /data/data/com.termux/files/usr/lib/libiconv.so
        libc.so => /system/lib64/libc.so
        ld-android.so => /system/lib64/ld-android.so
        libdl.so => /system/lib64/libdl.so
        libpcre2-8.so => /data/data/com.termux/files/usr/lib/libpcre2-8.so
        liblog.so => /system/lib64/liblog.so
        libc++.so => /system/lib64/libc++.so
        libm.so => /system/lib64/libm.so
```

And here's `cp` from Arch as a comparison.
```styl
ldd /bin/cp
        linux-vdso.so.1 (0x00007de8daaed000)
        libacl.so.1 => /usr/lib/libacl.so.1 (0x00007de8daa90000)
        libattr.so.1 => /usr/lib/libattr.so.1 (0x00007de8daa88000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007de8da897000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007de8daaef000)
```
I'm not sure if we can draw any conclusions from this.
However: `/bin/cp -a` gives the same warning when used in place of Termux's `cp`,
and with either version of `cp` the file copy is successful despite the warning.

My best educated guess is this is an issue with Android's SELinux restrictions meaning Termux is not allowed to "properly" copy/set the security context of files causing `cp` to emit a warning.

**Comment by kyufie** [comment]
When SELinux support is present, cp enforces context preservation when used with -a for symlinks and possibly hard links.

According to the code comment, "-a" is basically "-dR --preserve=all with reduced failure diagnostics". According to the man page, "-d" is the same as " --no-dereference --preserve=links" and "--preserve=links" is "for hard links".
Android has no hard links so I suppose we can ignore that part, making it behaves like "-R --preserve=all with failure diagnostics", removing the enforcement policy.

**Comment by truboxl** [comment]
Toybox `/system/bin/cp -a` does not preserve security context.
https://github.com/landley/toybox/blob/master/toys/posix/cp.c#L31

Any fixes are going to change the behavior and can't be compared to Desktop Linux.

**Comment by kyufie** [comment]
I think that's a good point.

I almost unable to think of any reason why would anyone use it.
Perhaps we can disable it for `cp`?
