### ISSUE TITLE
[Package]: deface-jso

### ISSUE THREAD

**Issue by satu-persen** [termux/termux-packages#21601]
### Why is it worth to add this package?

hehe

### Home page URL

https://github.com/satu-persen/deface-jso

### Source code URL

https://github.com/satu-persen/deface-jso

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [ ] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [ ] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

no

**Comment by Biswa96** [comment]
Nice malware you have written.

**Comment by TomJo2000** [comment]
This project is a blatant violation of our policy against malignant packages.
