### ISSUE TITLE
[Bug]: mv command error 

### ISSUE THREAD

**Issue by YasinAtLinux** [termux/termux-packages#21616]
### Problem description

I have given storage permission to termux. But when I move file from my internal storage, it gives me an error and delete the file from storage. Copy works very well. 
cp command work well. 
**ERROR :** mv: failed to set default file creation context to ‘u:object_r:sdcardfs:s0’: Permission denied
![Screenshot_2024-09-30-21-35-43-959_com termux](https://github.com/user-attachments/assets/15886e32-1821-41ca-b89e-5b5a81e4eea6)

### Steps to reproduce the behavior.

mv storage/shared/Download/TheLinux.md
Whenever I move things from my internal storage to termux environment. 

### System information

* Termux application version: 0.118.1
* Android OS version: 8.1.0
* Device model: Xiaomi Redmi 5

**Comment by YasinAtLinux** [comment]
Sorry. I reinstall Termux and it works.

**Comment by fornwall** [comment]
> Sorry. I reinstall Termux and it work

That is probably because you have older package versions after reinstalling. Once you updated (`pkg up`) the same problem will likely come back.

**Comment by fornwall** [comment]
@kyufie Will this be fixed by #21599?

**Comment by kyufie** [comment]
That should fix it, yes.
I apologize for the mess that I've caused.

**Comment by TomJo2000** [comment]
> That should fix it, yes.
I apologize for the mess that I've caused.

You make an omelette you're gonna crack a few eggs.
Nothing we can't clean up.

**Comment by YasinAtLinux** [comment]
> > Sorry. I reinstall Termux and it work
> 
> That is probably because you have older package versions after reinstalling. Once you updated (`pkg up`) the same problem will likely come back.

Exactly happened same. once I updated packages I got same error again m

**Comment by TomJo2000** [comment]
Yep, we're still working out the teething issues with SELinux support.
Should be fixed shortly.

**Comment by YasinAtLinux** [comment]
> Yep, we're still working out the teething issues with SELinux support. Should be fixed shortly.

Thank you! 😊

**Comment by fornwall** [comment]
https://github.com/termux/termux-packages/pull/21599 has been merged, so closing this (run `pkg up` to upgrade).
