### ISSUE TITLE
[Bug]: resolv.conf is not available in curl and libcurl

### ISSUE THREAD

**Issue by 1q23lyc45** [termux/termux-packages#21630]
### Problem description

I changed resolv.conf, but it only works in dig and nslookup, not in curl.
Let's look directly at the following:
```
u0_a198@localhost:~$ cat ../usr/etc/resolv.conf
nameserver 185.222.222.222
nameserver 45.11.45.11
u0_a198@localhost:~$ curl -v 1q23l.us.kg
* Host 1q23l.us.kg:80 was resolved.
* IPv6: ::
* IPv4: 124.236.16.201
*   Trying [::]:80...
* Connected to 1q23l.us.kg (::) port 80
* using HTTP/1.x
> GET / HTTP/1.1
> Host: 1q23l.us.kg
> User-Agent: curl/8.10.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.27.1
< Date: Wed, 02 Oct 2024 11:13:52 GMT
< Content-Type: text/html
< Content-Length: 169
< Connection: keep-alive
< Location: http://127.0.0.1:8080
<
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.27.1</center>
</body>
</html>
* Connection #0 to host 1q23l.us.kg left intact
u0_a198@localhost:~$ dig 1q23l.us.kg

; <<>> DiG 9.16.41 <<>> 1q23l.us.kg
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61118
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;1q23l.us.kg.                   IN      A

;; ANSWER SECTION:
1q23l.us.kg.            300     IN      A       104.21.37.233
1q23l.us.kg.            300     IN      A       172.67.214.176

;; Query time: 184 msec
;; SERVER: 185.222.222.222#53(185.222.222.222)
;; WHEN: Wed Oct 02 19:14:05 CST 2024
;; MSG SIZE  rcvd: 72

u0_a198@localhost:~$
```

### What steps will reproduce the bug?

Just curl any domain name.

### What is the expected behavior?

The DNS modified in resolv.conf must be applied to curl

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=4355
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous tur-hacking
Updatable packages:
busybox/stable 1.36.1-2 aarch64 [upgradable from: 1.36.1-1]
liblzma/stable 5.6.3 aarch64 [upgradable from: 5.6.2]
xz-utils/stable 5.6.3 aarch64 [upgradable from: 5.6.2]
termux-tools version:
1.43.5
Android version:
10
Kernel build information:
Linux localhost 4.14.141+ #1 SMP PREEMPT Sun Mar 11 23:50:42 WEST 2020 aarch64 Android
Device manufacturer:
unknown
Device model:
Phh-Treble vanilla
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by 1q23lyc45** [comment]
Maybe you can't reproduce it there, but this problem does exist. You can rename resolv.conf to resolv.conf.bak and you will find that curl can still resolve domain names, and the resolution is not 8.8.8.8 but [the carrier DNS.](https://www.bilibili.com/read/mobile?id=21633154)

**Comment by licy183** [comment]
`curl` in Termux is built without cares support, so `etc/resolv.conf` will have no effect on `curl`.

**Comment by 1q23lyc45** [comment]
I can't even open my website.
But what can we do?
Is this resolv.conf a scam?

**Comment by 1q23lyc45** [comment]
> > Is this resolv.conf a scam?
> 
> Not a scam (depending on view point), but is a stub for _certain_ programs.
> 
> Neither `$PREFIX/etc/resolv.conf` nor `$PREFIX/etc/hosts` will have effect on curl and on the most of other packages. This is not a bug.
> 
> `curl` uses Android OS DNS resolver.

So how can this bug be solved? 
Is it only can resolve by forwarding udp and tcp port 53 through routers and Iptables? I don't have a router management password!

**Comment by 1q23lyc45** [comment]
Is this targeting my domain name? Or is it for the entire us.kg domain? Why intentionally block?

**Comment by licy183** [comment]
不是哥们，你开关issue干啥呢，这玩意修不了啊。curl用了Android系统提供的DNS解析函数怎么修。我建议是你买个软路由连上你家宽带然后DoH。

**Comment by 1q23lyc45** [comment]
gnu/linux 它的curl 的dns用的应该就是resolv.conf 
另外resolv.conf本来就应该是管理dns解析相关的(https://metaso.cn/s/38G4zUk )，既然用不了那么放着干嘛呢，不如删了得了，，，

**Comment by licy183** [comment]
你也说了那是GNU/Linux，libc是glibc，glibc有自己的DNS解析管理方式，Termux直接用了Android提供的bionic libc，那它的DNS server就是安卓提供的netd。

curl本身可以通过开启cares支持来指定DNS服务器，但就算curl支持了设置DNS服务器，ISP仍然可以通过DNS抢先应答等方式来污染DNS，建议是买个软路由开DoH，不然DNS污染很难防止。

我把这个tag成enhancement，看看其他维护者谁有空搞一下。

**Comment by 1q23lyc45** [comment]
> 你也说了那是GNU/Linux，libc是glibc，glibc有自己的DNS解析管理方式，Termux直接用了Android提供的bionic libc，那它的DNS server就是安卓提供的netd。
> 
> curl本身可以通过开启cares支持来指定DNS服务器，但就算curl支持了设置DNS服务器，ISP仍然可以通过DNS抢先应答等方式来污染DNS，建议是买个软路由开DoH，不然DNS污染很难防止。
> 
> 我把这个tag成enhancement，看看其他维护者谁有空搞一下。

关键我这里根本没污染，改个114dns就搞定的事非要doh不麻烦吗，就用这个库解析，把它改成curl强制依赖就不行吗，就占用1mb也没别的依赖
```
u0_a198@localhost:~/curl$ apt info c-ares
Package: c-ares                                      Version: 1.33.1
Maintainer: @termux                                  Installed-Size: 1061 kB                              Depends: resolv-conf                                 Breaks: c-ares-dev
Replaces: c-ares-dev                                 Homepage: https://c-ares.haxx.se                     Download-Size: 173 kB                                APT-Manual-Installed: no
APT-Sources: https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable/main aarch64 Packages
Description: Library for asynchronous DNS requests (including name resolves)

u0_a198@localhost:~/curl$ cat ./docs/cmdline-opts/dns-servers.md                                          ---
c: Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
SPDX-License-Identifier: curl                        Long: dns-servers
Arg: <addresses>                                     Help: DNS server addrs to use
Protocols: DNS                                       Requires: c-ares
Added: 7.33.0                                        Category: dns
Multi: single                                        See-also:
  - dns-interface                                      - dns-ipv4-addr                                    Example:                                               - --dns-servers 192.168.0.1,192.168.0.2 $URL
  - --dns-servers 10.0.0.1:53 $URL                   ---
                                                     # `--dns-servers`
                                                     Set the list of DNS servers to be used instead of the system default. The list                            of IP addresses should be separated with commas. Port numbers may also                                    optionally be given, appended to the IP address separated with a colon.
```

**Comment by licy183** [comment]
那等我晚上回去搞吧，现在在外面玩

**Comment by 1q23lyc45** [comment]
> 那等我晚上回去搞吧，现在在外面玩

谢谢

**Comment by licy183** [comment]
Note: This has been reverted in https://github.com/termux/termux-packages/commit/e599c70709b4844944021525c1fc17eb79332cbf as it breaks many users usage.

**Comment by 1q23lyc45** [comment]
😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠

**Comment by TomJo2000** [comment]
> 😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠

This is not a constructive addition to the discussion.
If you think the issue needs further discussion please write out your thoughts instead of just grumbling about it.

**Comment by 1q23lyc45** [comment]
> > 😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠
> 
> This is not a constructive addition to the discussion. If you think the issue needs further discussion please write out your thoughts instead of just grumbling about it.

If the ISP resolves all the software sources of Termux to 127.0.0.1 through their own DNS, do you want Termux to die?

**Comment by TomJo2000** [comment]
> Your commit is tantamount to letting all users, as long as the dns is hijacked by the ISP, can't use Termux!

You're gonna need to qualify that assertion.
Users are free to use whatever DNS servers they want, including the ISP provided ones.
And cURL should work out of the box for users without having to mess with DNS resolution.
This does mean a malicious ISP can mess with DNS resolution provided by its own DNS Servers,
but Termux is no more at fault or at risk because of that decision made by a users ISP than any other application.
I do not understand what is giving you the impression that we are maliciously disabling features.

**Comment by 1q23lyc45** [comment]
```
~ $ pkg update
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Testing the available mirrors:
[*] (10) https://packages-cf.termux.dev/apt/termux-main: bad
[*] (1) https://mirror.textcord.xyz/termux/termux-main: bad
[*] (1) https://mirror.nevacloud.com/applications/termux/termux-main: bad
[*] (1) https://mirrors.nguyenhoang.cloud/termux/termux-main: bad
[*] (1) https://mirror.twds.com.tw/termux/termux-main: bad
[*] (1) https://linux.domainesia.com/applications/termux/termux-main: bad
[*] (1) https://tmx.xvx.my.id/apt/termux-main: bad
[*] (1) https://mirror.freedif.org/termux/termux-main: bad
[*] (1) https://mirrors.cbrx.io/apt/termux/termux-main: bad
[*] (1) https://mirrors.in.sahilister.net/termux/termux-main/: bad
[*] (1) https://mirror.albony.in/termux/termux-main: bad
[*] (1) https://mirror.bardia.tech/termux/termux-main: bad
[*] (1) https://mirrors.ravidwivedi.in/termux/termux-main: bad
[*] (1) https://mirrors.saswata.cc/termux/termux-main: bad
[*] (1) https://termux.niranjan.co/termux-main: bad
[*] (1) https://mirror.jeonnam.school/termux/termux-main: bad
[*] (1) https://mirrors.sdu.edu.cn/termux/termux-main: bad
[*] (1) https://mirrors.sau.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.nju.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.sustech.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.pku.edu.cn/termux/termux-main/: bad
[*] (1) https://mirror.sjtu.edu.cn/termux/termux-main/: bad
[*] (1) https://mirror.iscas.ac.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.ustc.edu.cn/termux/termux-main: bad
[*] (1) https://mirrors.aliyun.com/termux/termux-main: bad
[*] (1) https://mirrors.qvq.net.cn/termux/termux-main: bad
[*] (1) https://mirrors.cqupt.edu.cn/termux/termux-main: bad
[*] (1) https://mirrors.zju.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.hust.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.bfsu.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirror.nyist.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main: bad
[*] (1) https://ftp.agdsn.de/termux/termux-main: bad
[*] (4) https://grimler.se/termux/termux-main: bad
[*] (1) https://ro.mirror.flokinet.net/termux/termux-main: bad
[*] (1) https://mirrors.cfe.re/termux/termux-main: bad
[*] (1) https://mirror.termux.dev/termux-main: bad
[*] (1) https://termux.3san.dev/termux/termux-main: bad
[*] (1) https://mirror.bouwhuis.network/termux/termux-main: bad
[*] (1) https://mirror.accum.se/mirror/termux.dev/termux-main: bad
[*] (1) https://termux.mentality.rip/termux-main: bad
[*] (1) https://is.mirror.flokinet.net/termux/termux-main: bad
[*] (1) https://md.mirrors.hacktegic.com/termux/termux-main: bad
[*] (1) https://mirror.mwt.me/termux/main: bad
[*] (1) https://mirrors.medzik.dev/termux/termux-main: bad
[*] (1) https://packages.termux.dev/apt/termux-main: bad
[*] (1) https://mirror.sunred.org/termux/termux-main: bad
[*] (1) https://mirrors.de.sahilister.net/termux/termux-main: bad
[*] (1) https://mirror.leitecastro.com/termux/termux-main: bad
[*] (1) https://termux.cdn.lumito.net/termux-main: bad
[*] (1) https://nl.mirror.flokinet.net/termux/termux-main: bad
[*] (1) https://ftp.fau.de/termux/termux-main: bad
[*] (1) https://termux.librehat.com/apt/termux-main: bad
[*] (1) https://mirror.autkin.net/termux/termux-main: bad
[*] (1) https://mirror.polido.pt/termux/termux-main: bad
[*] (1) https://dl.kcubeterm.com/termux-main: bad
[*] (1) https://termux.danyael.xyz/termux/termux-main: bad
[*] (1) https://mirror.mwt.me/termux/main: bad
[*] (1) https://mirrors.utermux.dev/termux/termux-main: bad
[*] (1) https://mirror.vern.cc/termux/termux-main: bad
[*] (1) https://plug-mirror.rcac.purdue.edu/termux/termux-main: bad
[*] (1) https://mirror.quantum5.ca/termux/termux-main: bad
[*] (1) https://mirror.fcix.net/termux/termux-main: bad
[*] (1) https://mirror.csclub.uwaterloo.ca/termux/termux-main: bad
[*] (1) https://gnlug.org/pub/termux/termux-main: bad
[*] (1) https://mirrors.middlendian.com/termux/termux-main: bad
[*] (1) https://repository.su/termux/termux-main/: bad
[*] (1) http://mirror.mephi.ru/termux/termux-main: bad
Error: None of the mirrors are accessible
```

**Comment by 1q23lyc45** [comment]
You also said that users should have the freedom to modify DNS!This includes the use of resolv through modification.conf The freedom to modify DNS freely!

**Comment by agnostic-apollo** [comment]
You can change DNS in Android wifi settings if your ISP is malicious, in which case you shouldn't even be using that ISP anyways.

If enabling ares for curl breaks random users ability to use curl, then it does not make sense to enable it as we need to prioritize stability. I don't know how ares works internally, but if it can be dynamically enabled at runtime with an environment variable/config file, that can be looked into. Otherwise the decision stays. You have the freedom to compile curl yourself with ares enabled, no one took that freedom from you.

**Comment by 1q23lyc45** [comment]
> You can change DNS in Android wifi settings if your ISP is malicious, in which case you shouldn't even be using that ISP anyways.
> 
> If enabling ares for curl breaks random users ability to use curl, then it does not make sense to enable it as we need to prioritize stability. I don't know how ares works internally, but if it can be dynamically enabled at runtime with an environment variable/config file, that can be looked into. Otherwise the decision stays. You have the freedom to compile curl yourself with ares enabled, no one took that freedom from you.

The Android Wifi settings have a DNS option, but it doesn't work at all!
Maybe that's a feature only for your custom OS. Changing it on my LineageOS 18 has no effect at all!

**Comment by agnostic-apollo** [comment]
Android AOSP wouldn't have the feature if it didn't work, and it has existed since very old android versions. If its not working for LineageOS, report to them, we are not responsible for custom ROM/device vendor bugs.

**Comment by 1q23lyc45** [comment]
> Android AOSP wouldn't have the feature if it didn't work, and it has existed since very old android versions. If its not working for LineageOS, report to them, we are not responsible for custom ROM/device vendor bugs.

No!
Harmony OS 3.0 and Flyme OS 8 doesn't work either!

**Comment by 1q23lyc45** [comment]
I urge you to change the Issue back to Not Planned. because the issue itself it not solved at all!

**Comment by 1q23lyc45** [comment]
> Note: This has been reverted in [e599c70](https://github.com/termux/termux-packages/commit/e599c70709b4844944021525c1fc17eb79332cbf) as it breaks many users' usage.

https://github.com/termux/termux-packages/commit/e599c70709b4844944021525c1fc17eb79332cbf
This commit, as much as anything, makes Termux unavailable to many users!

**Comment by twaik** [comment]
C-ares support was disabled because it created more problems than it solved so we reverted it back. End of story. 
In the case if it is important to use c-ares you always can compile it for yourself.
