### ISSUE TITLE
[Package]: "mesa-vulkan-icd-freedreno-dri3" New Version Package request

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#21640]
### Why is it worth to add this package?

Currently, the `mesa-vulkan-icd-freedreno-dri3` package distributed on Termux does not support the latest `Adreno 750` GPU, as it is based on `mesa-24.0.4 (released: 2024-03-27)`.

I would like to request the `mesa-vulkan-icd-freedreno-dri3` package to be updated to the latest version, `mesa-24.2.3 (released: 2024-09-18)`.

### Home page URL

https://docs.mesa3d.org/relnotes/24.2.3.html

### Source code URL

https://gitlab.freedesktop.org/mesa/mesa/-/tree/mesa-24.2.3

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by twaik** [comment]
No need to ask about package updates. We are aware about new versions of software. But there is no people to process all of them.
