### ISSUE TITLE
[Bug]: Termux-x11 xfce4 wrong resolution.

### ISSUE THREAD

**Issue by sfantu** [termux/termux-packages#21644]
### Problem description

![2024-10-03-152538_3440x1440_scrot](https://github.com/user-attachments/assets/b57c09d9-8c85-4210-b010-39e090bae639)

Recently the resolution won't get set to what it's supposed to be.

You can see from the screenshot that in display settings the monitor is reported as 3440x1440 yet the dialog at the bottom is reporting 1720x 720.

It all worked GREAT before .

### What steps will reproduce the bug?

start xfce4 and resolution is messed up.

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=25395
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.de.sahilister.net/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.de.sahilister.net/termux/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
clang/stable 19.1.1 aarch64 [upgradable from: 18.1.8]
libcompiler-rt/stable 19.1.1 aarch64 [upgradable from: 18.1.8]
libllvm/stable 19.1.1 aarch64 [upgradable from: 18.1.8]
lld/stable 19.1.1 aarch64 [upgradable from: 18.1.8]
llvm/stable 19.1.1 aarch64 [upgradable from: 18.1.8]
ncurses-ui-libs/stable 6.5.20240831-1 aarch64 [upgradable from: 6.5.20240831]
ncurses-utils/stable 6.5.20240831-1 aarch64 [upgradable from: 6.5.20240831]
ncurses/stable 6.5.20240831-1 aarch64 [upgradable from: 6.5.20240831]
termux-tools/stable 1.43.6 aarch64 [upgradable from: 1.43.5]
termux-tools version:
1.43.5
Android version:
14
Kernel build information:
Linux localhost 5.10.198-android12-9-29544049-abS901BXXUBEXH7 #1 SMP PREEMPT Mon Aug 19 14:24:07 KST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S901B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.x11 versionCode:15
com.termux.api versionCode:51
```

**Comment by IntinteDAO** [comment]
Strange, however you can set your resolution manually in Termux X11 Preferences

**Comment by sfantu** [comment]
Yes i can ... but the result is still the same .

**Comment by IntinteDAO** [comment]
> Yes i can ... but the result is still the same .

Interesting. But what
> xrandr

says?

**Comment by sfantu** [comment]
~ $ xrandr
Screen 0: minimum 1 x 1, current 2256 x 481, maximum 32767 x 32767
Builtin Display connected 2256x481+0+0 0mm x 0mm
   2256x481      59.89* 

This is without being connected to the external display. 

It gives the corect resolution. But still the actual resolution is exactly half .

**Comment by IntinteDAO** [comment]
I can't help you. If you think it's a Termux X11 bug, you can report it here
https://github.com/termux/termux-x11

However I don't think it's a Termux X11 bug, but maybe Xfce4 bug and you maybe should report it on xfce4.org

**Comment by sfantu** [comment]
I think it's more of a drivers problem.

**Comment by sfantu** [comment]
Reinstalled and now it's fixed. I have no idea what messed up the resolution.
