### ISSUE TITLE
[Bug]: Neovim doesn't start after update

### ISSUE THREAD

**Issue by Serega124** [termux/termux-packages#21659]
### Problem description

After updating neovim to `0.10.2` and tree-sitter to `0.24.1` nvim command throws an error `CANNOT LINK EXECUTABLE "nvim": library "libtree-sitter.so.0.23" not found: needed by main executable`

### What steps will reproduce the bug?

Install or update `neovim` package

### What is the expected behavior?

nvim command should run neovim

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__APK_FILE=/data/app/~~ynjO0bSuvSaVA5jEDGjBxQ==/com.termux--qpk1IKBLLD2CEezr16upg==/base.apk
TERMUX_APP__APK_RELEASE=F_DROID
TERMUX_APP__APP_VERSION_CODE=1020
TERMUX_APP__APP_VERSION_NAME=0.119.0-beta.1
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__IS_DEBUGGABLE_BUILD=false
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PID=5402
TERMUX_APP__TARGET_SDK=28
TERMUX_VERSION=0.119.0-beta.1
TERMUX__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c77,c257,c512,c768
TERMUX__SE_INFO=default:targetSdkVersion=28:complete
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c77,c257,c512,c768
TERMUX__UID=10333
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
Updatable packages:
coreutils/stable 9.5-3 aarch64 [upgradable from: 9.5-1]
proot-distro/stable 4.17.1 all [upgradable from: 4.16.0]
termux-tools version:
1.43.6
Android version:
13
Kernel build information:
Linux localhost 4.14.180-perf-g2c687cdb9430 #1 SMP PREEMPT Sun May 7 15:20:47 UTC 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2102J20SG
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.styling versionCode:1000
com.termux.api versionCode:51
```

**Comment by Biswa96** [comment]
Actually, the issue happened due to tree-sitter update in b4ddcb4f56a1ba5cf39f283b54bd8212b8663ef2 commit. Rebuilding neovim will fix the issue but I think the soversion check in tree-sitter should be fixed first.

**Comment by TomJo2000** [comment]
> Actually, the issue happened due to tree-sitter update in b4ddcb4f56a1ba5cf39f283b54bd8212b8663ef2 commit. Rebuilding neovim will fix the issue but I think the soversion check in tree-sitter should be fixed first.

I'll look into that once I'm back from the grocery store.
Did you have anything specific in mind for how we'd need to adjust the SO guard?

**Comment by fornwall** [comment]
> Did you have anything specific in mind for how we'd need to adjust the SO guard?

The version check is currently just asserting that we stay on the same major version number (`0` here):

```bash
termux_step_pre_get_source() {
	# Do not forget to bump revision of reverse dependencies and rebuild them
	# after SOVERSION is changed.
	local _SOVERSION=0

	# New SO version is the major version of the package
	if [[ $TERMUX_PKG_VERSION != $_SOVERSION.* ]]; then
		termux_error_exit "SOVERSION guard check failed."
	fi
}
```

Changing to `local _SOVERSION=0.24` is what we want, right, as we don't want auto updating to update across breaking minor `0.x` versions (until we have taught the auto updater to revbump revdeps)?
