### ISSUE TITLE
Numpy - unmet dependency - openblas

### ISSUE THREAD

**Issue by halldrine** [termux/termux-packages#2165]
Following the steps here:

https://wklchris.github.io/Jupyter-Installation-on-Android.html

I get this:
pkg install numpy
Hit:1 https://termux.net stable InRelease
Hit:2 https://its-pointless.github.io/files termux InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 numpy : Depends: openblas but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Apologies in advance if this is the wrong place...

thanks

**Comment by its-pointless** [comment]
what arch you using and pkg install openblas won't install?
Also this isssue is probably better at github.com/its-pointless/gcc_termux/issues

**Comment by its-pointless** [comment]
anyway im fixing this thanks for reporting it. i can see whats wrong now
