### ISSUE TITLE
[Bug]: LXQT and llvm-mingw are broken

### ISSUE THREAD

**Issue by DuilioPerez** [termux/termux-packages#21663]
### Problem description

LXQT can't run because Qt 6.7.2 and Qt 6.7.3 are incompatible, and llvm-mingw-w64 have dependencies issue, llvm was upgraded to major 19, but llvm-mingw-w64 is still in version 18.

### What steps will reproduce the bug?

1. Upgrade packages and try to use lxqt.
2. Try to install or upgrade llvm-mingw-w64

### What is the expected behavior?

1. Run LXQT
2. Be able to install llvm-mingw-w64

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__APK_FILE=/data/app/~~LQzey9mCzS7FzKtqTYRMfw==/com.termux-GhIV57Ap-eqr_cw6kSgV0Q==/base.apk
TERMUX_APP__APK_RELEASE=F_DROID
TERMUX_APP__APP_VERSION_CODE=1020
TERMUX_APP__APP_VERSION_NAME=0.119.0-beta.1
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__IS_DEBUGGABLE_BUILD=false
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PID=14345
TERMUX_APP__TARGET_SDK=28
TERMUX_VERSION=0.119.0-beta.1
TERMUX__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c33,c257,c512,c768
TERMUX__SE_INFO=default:targetSdkVersion=28:complete
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c33,c257,c512,c768
TERMUX__UID=10289
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.danyael.xyz/termux/termux-main stable main
# glibc-repo (sources.list.d/glibc.list)
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://termux.danyael.xyz/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.43.6
Android version:
11
Kernel build information:
Linux localhost 4.14.186-22735277 #1 SMP PREEMPT Sat Feb 19 02:14:57 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A225M
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:15
com.termux.styling versionCode:32
```

**Comment by Biswa96** [comment]
> LXQT can't run because Qt 6.7.2 and Qt 6.7.3 are incompatible

I am updating qt6 packages one by one because auto-update can't do that for some reason. I'll test lxqt later after all qt6 update.

**Comment by Biswa96** [comment]
All qt6 packages are updated now. Could you please check with lxqt?

**Comment by DuilioPerez** [comment]
You need to update LXQT too. It's weird that a change in the tweak version component of a library can broke a binary.
![Screenshot_20241004-124642_Termux](https://github.com/user-attachments/assets/dfc851c0-94a1-4423-8bc2-c96f5fea03f8)

Panel, Application launcher and Desktop were affected.
![Screenshot_20241004-125006_TermuxX11](https://github.com/user-attachments/assets/177a0e06-86a3-4a47-ac99-b1ae98cd159a)

**Comment by Biswa96** [comment]
I can not reproduce the issue in my phone and can run lxqt without any issue. Could you see any qt 6.7.2 in the output of `apt search qt6` ? No need to provide the full output.

**Comment by DuilioPerez** [comment]
Yes, there are some packages

**Comment by Biswa96** [comment]
Please wait. The mirrors need some time to update.

**Comment by DuilioPerez** [comment]
Well, there are just two packages with that version, qt6-qt5compact{-cross-tools} and qt6-qtwayland{-cross-tools}

**Comment by Biswa96** [comment]
All packages should be up-to-date now.

**Comment by sm8ps** [comment]
I can confirm that LXQT does startup normally again and without complaining about incompatible QT-versions anymore. Thanks for your quick reaction, @Biswa96 !

**Comment by DuilioPerez** [comment]
Yes, all it is working now. Thanks!

**Comment by DuilioPerez** [comment]
But now Desktop and Panel don't handle clicks correctly. In Panel, menu launcher, calendary and notifications don't work, direct access to applications opens to windows t the same time. In desktop, it open directories with one click. It seem they receive clicks duplicated

**Comment by sm8ps** [comment]
@DuilioPerez : I do not fully understand what you mean, sorry.
Here, I can launch applications by tapping them in the launcher. I have no calendar or notifications to test. Though, I do not experience anything like duplicate clicks.
Could it be due to the pointer settings of Termux-X11? I have mine set to Direct touch and I do not use a mouse.

**Comment by DuilioPerez** [comment]
This new issue is after solving the previous issue (LXQT couldn't run because of Qt version error). Maybe a video can explain:

https://github.com/user-attachments/assets/4938e5a7-959b-4472-a918-24a0b08b80fc

It's not Termux-x11 error or configuration because xfce4 works very well.

**Comment by sm8ps** [comment]
I see. (Un-)Fortunately I do not see any such effects. I am sorry that I cannot be of much further help.

**Comment by DuilioPerez** [comment]
I've used xfce4 today, and I've see the double click issue is in all qt apps. Maybe related to qt6-qtwayland?

**Comment by DuilioPerez** [comment]
I've used xfce4 here. It works well, but not with shotcut, which is a qt app. You can see click because the clicked option becomes blue, that's why I think qt after the last update have issue with clicks, it receive a click as a double click.

https://github.com/user-attachments/assets/643fac32-2f20-48ba-a30c-0fcbba4fa049
