### ISSUE TITLE
[Bug]: resolv.conf is invalid

### ISSUE THREAD

**Issue by b1c4ef5** [termux/termux-packages#21674]
### Problem description

The DNS configured in resolv.conf does not take effect in curl.

### What steps will reproduce the bug?

1. Set the DNS on your router to our local ISP (China Mobile, Hebei) DNS 111.11.1.141
2. Reconnect WiFi
3. Ensure that the DNS in /data/data/com. termux/files/usr/etc/resolv.conf is not 111.11.1.141
4. run this command in termux
```
curl -v abcd.us.kg
```
5. You will see this:
```
* Host abcd.us.kg:80 was resolved.                  * IPv6: ::
* IPv4: 124.236.16.201                               *   Trying [::]:80...
* connect to :: port 80 from ::1 port 48798 failed: Connection refused
*   Trying 124.236.16.201:80...
```
6. `dig wvvw.us.kg`
7. `dig wvvw.us.kg @111.11.1.141`
8. Compare the two obtained IPs

### What is the expected behavior?

The configuration in resolv.conf must be effective in all programs in Termux!

### System information

```shell
any
```

**Comment by licy183** [comment]
Duplicated of #21630
