### ISSUE TITLE
ERROR: No files in package

### ISSUE THREAD

**Issue by h4waii** [termux/termux-packages#2167]
I'm having an issue building a package, specifically `proxmark3`. My build.sh is correct, I have a Makefile patch to remove a single line, which I can see is being is applied correctly (by browsing to the ~/.termux-packages src directory), but the package building fails before it starts compiling with `ERROR: No files in package`. 

Some how this is related to the massaging process, where the data is targzipped up? I just can't figure out why it's failing in this process.

Any help would be appreciated.

**Comment by Grimler91** [comment]
The message means that no files were installed to `/data/data/com.termux/files/usr/..`, and therefore no files were moved to the massage folder. 

Since you say that it fails before it starts compiling (you have no files in `~/.termux-build/proxmark3/build`?) then the configuration, make and/or make install step probably fails (maybe you need to autogen a configuration file?).

**Comment by h4waii** [comment]
There are no files in `~/.termux-build/proxmark3/build` for it, but I can drop to `src ` directory, issue `make`, and everything builds correctly.

There is no configure/autogen/autoconf script, just a Makefile. I'm guessing there might **have** to be an install: portion of the Makefile in order to place the binary accordingly? Is this true?

**Comment by Grimler91** [comment]
Could you upload the branch or share the build.sh? 

Only a Makefile should work in theory, but it needs a `install:`-target (and the install location can't be hardcoded to be `/usr/local` or similar).

**Comment by h4waii** [comment]
Okay, if it needs an `install:` portion, I will patch it in and see.

Thanks for responding and providing the info, much appreciated.

[build.sh](https://github.com/termux/termux-packages/files/1737480/build.txt)

**Comment by Grimler91** [comment]
You'll probably need to set TERMUX_PKG_BUILD_IN_SRC=yes also, proxmark3 doesn't seem to support building from another directory.
