### ISSUE TITLE
`apt update` fails on some devices

### ISSUE THREAD

**Issue by ChillarAnand** [termux/termux-packages#2168]
In some of the devices, it is throwing this error

```
100|athene_f:/sdcard # apt update                                                                                                                    
Get:1 https://termux.net stable InRelease [1687 B]
Err:1 https://termux.net stable InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: No sandbox user '_apt' on the system, can not drop privileges
W: GPG error: https://termux.net stable InRelease: At least one invalid signature was encountered.
E: The repository 'https://termux.net stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by Muhaiminkp** [comment]
Ya me also. What to do!?

**Comment by lkdevil** [comment]
@ChillarAnand your phone is rooted and ever used tsu or sudo in termux ?

**Comment by Muhaiminkp** [comment]
Yes my device is rooted and I use sudo for setoolkit one time

**Comment by Muhaiminkp** [comment]
@lkdevil Yes my device is rooted and I use sudo

**Comment by Grimler91** [comment]
`100|athene_f:/sdcard # apt update` indicates that you were running as root. 

You shouldn't use apt or other stuff that install/download/changes termux as root. 
Best course of action in your case is to uninstall termux and then reinstalling it. 

You could also try running `chown -R YOUR_ID:YOUR_ID /data/data/com.termux/files/usr` as root (replace YOUR_ID with the id you get from `whoami` as non-root), might work.

**Comment by sdrausty** [comment]
Root should be reserved for system maintenance.  This can be confusing without understanding the concepts of [system administration](https://duckduckgo.com/?q=system+administration+site%3Atldp.org), [selinux](https://duckduckgo.com/?q=selinux+site%3Atldp.org) and [chroot permissions](https://duckduckgo.com/?q=chroot+permission+site%3Atldp.org).  When the Termux user is give privileges to administrate every aspect of the device, it's sort of like saying, "Here are the car keys to the Ferrari, bring it back whole."  Odds are no one is coming back in one piece at all.
