### ISSUE TITLE
[Bug]: iconv only outputs ascii

### ISSUE THREAD

**Issue by freedom-foundation** [termux/termux-packages#21682]
### Problem description

iconv only outputs ascii no matter what output is specified. I suspect this has to do with some UTF or ASCII constraint within the overall termux design. 

### What steps will reproduce the bug?

iconv -f ASCII -t KOI8-R asciifile.txt > testfile.txt
file testfile.txt shows ASCII filetype
md5sum testfile.txt compare same as asciifile.txt
The output is unchanged.

### What is the expected behavior?

I expected when using KOI8-R for the output to be garbled thus showing that the output was indeed converted however it was not and remained the exact same ASCII

### System information

```shell
packages/libiconv/iconv.subpackage.sh
```

**Comment by fornwall** [comment]
Could you paste the output from running `which iconv` and `iconv --version`? Just want to make sure that you run the `iconv` binary from the `iconv` Termux package, and not the `/system/bin/iconv` toybox binary.

**Comment by freedom-foundation** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

iconv --version
iconv (GNU libiconv 1.17)
Copyright (C) 2000-2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Bruno Haible.
-----BEGIN PGP SIGNATURE-----
Version: ProtonMail

wnUEARYKACcFgmcDERUJkKkWZTlQrvKZFiEEZlQIBcAycZ2lO9z2qRZlOVCu
8pkAABaVAQCsHVZQsXhf7Y9XKIHUdp9E8C6A4x32XeSWoh0JZplp8gEAiA2O
0Gzh1tPq+hhUEMDcLQ7YFC4P0SMjNKA0VIRy8gc=
=iTFg
-----END PGP SIGNATURE-----

**Comment by freedom-foundation** [comment]
Where does iconv get locale in linux? I need to verify it. I keep getting people saying ascii generally but there are 5 or so releases of ascii, (ascii is 7bit but various 8bit "padding" may be in use) landfillbaby being the latest claiming KOI8-R is a superset of ascii; This actually sounds like somebody parted out UTF-8 to rewrite history on the locales so you just have Unicode and then parts of it relabled as a locale and an UNKNOWN ascii subset. It seems they are touchy on this because they want to keep pushing various ascii to flux the code ( a crooks manuever ) by pushing Unicode updates upstream ( actually changing the codepage ) . landfillbaby good to test but to close my bug under these auspices you would only test my example yet you would need the locales from my machine unless any of those you tested are included in iconv. Part of the bug is that iconv relies on stdout and depending on the pipe mechanism I have a concern that the final result will be including yet another locale ( do to iconv only using stdout ) as such: from locale to locale then locale of piped display. In this example I need to verify ALL THREE locale sources ( codepages ).  Without reguard to the piped data I will anyhow need to reference the THIRD locale because these eyes will be verifying the output displayed even if it were not used in writing the file.
Where does iconv, and terminal display of stdio, get locale in linux?

**Comment by landfillbaby** [comment]
What are you trying to say here? The locale encoding of Android is always UTF-8. It hasn't been around that long. You're talking about standards from over 50 tears ago.

**Comment by freedom-foundation** [comment]
ASCII 1969 was standardized by IETF in 2015 and since 69 there are 5 or so revisions. You can buy a standards paper of ASCII rev. 2022 from ANSI for $60. I am talking about: Where does iconv, and terminal display of stdio, get locale in linux? Where is the locale codepage stored?

**Comment by freedom-foundation** [comment]
Though this bug is closed this needs to be moved to a question related to iconv, android, and linux kernel. Is there a better place to post this. Do the upstream repos of the termux-packages subpackages have a GH presence to post questions to: iconv. And then AOSP and Linux kernel.

**Comment by freedom-foundation** [comment]
@landfillbaby according to @TomJo2000 termux cannot make use of any locales. See here https://github.com/termux/termux-packages/discussions/21765#discussioncomment-10909309

@landfillbaby because in your tests you are piping with a redirect from stdio no matter what locale you specify it is likely run through bionic and get the same output for any encoding. So you mayaswell reopen this or it is to be reissued as a more serious bug. Keeping closing unresolved bugs only makes it harder to track troubleshooting history. 

As such termux-packages  needs to code a version of iconv compatible to the environment from within it does run: that is termux app using bionicC stdio on android. This is a serious bug. 

The coder needs a primer about the android environment here https://en.wikipedia.org/wiki/Bionic_(software).
