### ISSUE TITLE
[Package]: sftpgo

### ISSUE THREAD

**Issue by maaaaz** [termux/termux-packages#21687]
### Why is it worth to add this package?

A full-featured and highly configurable SFTP, HTTP/S, FTP/S and WebDAV server - S3, Google Cloud Storage, Azure Blob.
It is really efficient and easy to configure.

### Home page URL

https://sftpgo.com/

### Source code URL

https://github.com/drakkan/sftpgo

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

Here you can find **some directions to compile it**:
https://github.com/drakkan/sftpgo/issues/1755

Here you can find some tricks to reduce a GO binary size: 
https://words.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

**Comment by TomJo2000** [comment]
What in particular differentiates this project from for example:
`curl` or `sftp` (provided by `openssh`)?

**Comment by maaaaz** [comment]
sftpgo provides server-side capabilities: SFTP server, WebDAV server, FTP server.

All in one simple and robust tool.

**Comment by maaaaz** [comment]
Thank you !
Have you managed to shrink the size of binaries ?
