### ISSUE TITLE
ssh logon fails keycheck. on entry in known_hosts

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#2169]
ssh-keyscan [192.168.1.10]:8022
getaddrinfo [192.168.1.10]:8022: No address associated with hostname
getaddrinfo [192.168.1.10]:8022: No address associated with hostname
getaddrinfo [192.168.1.10]:8022: No address associated with hostname
u0_a134@localhost:~$ ssh -p 8022 192.168.1.10      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:7201eyCLf6C+Zi2RNQDafYjsesmq8ciq7q3h29oJkgg.
Please contact your system administrator.
Add correct host key in /data/data/com.termux/files/home/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /data/data/com.termux/files/home/.ssh/known_hosts:56
ECDSA host key for [192.168.1.10]:8022 has changed and you have requested strict checking.
Host key verification failed.

**Comment by macerg** [comment]
.....no entry in .ssh/known_hosts for this address:port but fails security.

**Comment by macerg** [comment]
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.19+ #1 SMP PREEMPT Sat Dec 10 21:57:17 CST 2016 aarch64 Android
Termux-packages arch:
aarch64
Android version:
6.0
Device manufacturer:
DOOGEE
Device model:
T5

**Comment by gagaltotal** [comment]
example : 
- ssh-keygen -R (IP server)
- ssh-keygen -R 123.23.323.12
