### ISSUE TITLE
[Package Update]: apt

### ISSUE THREAD

**Issue by 1q23lyc45** [termux/termux-packages#21725]
### Why is it worth to add this package?

APT 2.9.8 has been released, but currently termux is still 2.8.1. It's time to update now.

### Home page URL

https://packages.debian.org/apt

### Source code URL

https://deb.debian.org/debian/pool/main/a/apt/apt_2.9.8.tar.xz

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by twaik** [comment]
No need to ask about package updates. We are aware about new versions of software. But there is no staff to process all of them.

**Comment by Biswa96** [comment]
> APT 2.9.8 has been released, but currently termux is still 2.8.1. It's time to update now.

APT is a core package. It is updated to stable versions or when needed. apt version 2.8.1 was released two months ago https://salsa.debian.org/apt-team/apt/-/commit/f9f65657ec84ac930c9d9af183913a5ae063bf0f

**Comment by 1q23lyc45** [comment]
> > APT 2.9.8 has been released, but currently termux is still 2.8.1. It's time to update now.
> 
> APT is a core package. It is updated to stable versions or when needed. apt version 2.8.1 was released two months ago https://salsa.debian.org/apt-team/apt/-/commit/f9f65657ec84ac930c9d9af183913a5ae063bf0f

![screenshot](https://github.com/user-attachments/assets/87acf011-27f8-4932-a586-6755a1500fa5)
This software release is somewhat......
However, it seems that version 2.9 has been released for a long time. Additionally, 2.9.7 is earlier than 2.8.1. Why not update 2.9? The experience of version 2.9 is great.
A long time ago, Kali Linux and Debian 12 have been updated to version 2.9 of apt. It has been a long time since then.

**Comment by TomJo2000** [comment]
The 2.9.x releases are experimental releases leading up to 3.0.0

We are not going to package them.
If you do want to use them you can use the build artifacts from:
- #20029 
(Which should more accurately be called apt 2.9.x testing)

**Comment by 1q23lyc45** [comment]
OK. Thanks.
