### ISSUE TITLE
PHP with intl extension

### ISSUE THREAD

**Issue by shaqman** [termux/termux-packages#2173]
I am not sure if this used in many places or not, but I don't see why we can't have a php built with flag  `--enable-intl` on.

**Comment by Wetitpig** [comment]
I can't find out where it is. Can you point it out?

**Comment by shaqman** [comment]
http://php.net/manual/en/intl.installation.php

There is also alternative packages, that could be built seperately.
Eg: In ubuntu: apt install php-intl

**Comment by Wetitpig** [comment]
Maybe can you send all of us a log of build here and see what happens?

**Comment by shaqman** [comment]
Will do later this afternoon. Need to setup the environment first.

**Comment by shaqman** [comment]
@Wetitpig 

I'm sorry for the noob question, but which log of build do you meant? The one that goes from the terminal is quite long, but it ends completed as done.

Should I just do a PR?

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/1f66857dce7086b6460e3c99d437692050daf1a9.
