### ISSUE TITLE
[Package]: neofetch New Package request (Hamonikr)

### ISSUE THREAD

**Issue by hansm629** [termux/termux-packages#21732]
### Why is it worth to add this package?

The `neofetch` in `Hamonikr`, unlike the `standard neofetch`, provides a lot of information about mobile SoCs.

After installing `version 7.3.1` of `Hamonikr neofetch`, which is distributed for `ARM64 Linux`, in `PRoot-Distro Debian`, details such as the number of cores per cluster and clock speeds of the SoC are displayed (for some SoCs, the CPU architecture is also shown), as well as GPU information.

If the neofetch distributed in Termux is replaced with Hamonikr's neofetch, I believe it will display more detailed specifications.

**Snapdragon8 Gen2 for Galaxy (Galaxy Tab S9 Ultra 5G)**
![Screenshot_2024-10-07_18-22-15](https://github.com/user-attachments/assets/cb1fe57c-ac88-4670-ad12-2168270cd365)

**Exynos 2400 (Galaxy S24+)**
![Screenshot_2024-10-08_00-13-25](https://github.com/user-attachments/assets/6bb95a60-b770-4023-9365-7617b490f446)

**Snapdragon8 Gen3 for Galaxy (Galaxy S24 Ultra)**
![Screenshot_2024-10-08_01-34-21_1](https://github.com/user-attachments/assets/586f9cb6-4153-4a5b-b79c-71e0916f6298)

### Source code URL

https://github.com/hamonikr/neofetch/tree/master

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
We already package the original version of Neofetch by Dylan Araps.
Which is as of April this year officially archived.

We do not intend to ship any fork of the original in its place as the original Neofetch still works perfectly fine.

More to the point, our `neofetch` package was created before the current packaging policy was in place and would not be eligible for packaging under the current packaging policy as it is an ordinary Bash script not requiring any changes to work on Termux.

As such if you want to use any maintained fork of Neofetch on your device please download it from its Git repository.

Or alternatively use one of the several alternatives packaged in our repositories such as:
- `fastfetch`
- `macchina`
- `onefetch`
- `rxfetch`
or
- `screenfetch`
