### ISSUE TITLE
[Bug]: qt6-qtdeclarative 6.8.0 fails to build for non-aarch64 architectures

### ISSUE THREAD

**Issue by Biswa96** [termux/termux-packages#21733]
### Problem description

qt6-qtdeclarative 6.8.0 fails to build for non-aarch64 architectures. Here is the linker error.

```
ld.lld: error: undefined symbol: __tls_get_addr
>>> referenced by tasktree.cpp
>>>               lto.tmp:(Tasking::ExecutionContextActivator::activateTaskTree(Tasking::RuntimeContainer*))
>>> referenced by tasktree.cpp
>>>               lto.tmp:(Tasking::ExecutionContextActivator::activateTaskTree(Tasking::RuntimeContainer*))
>>> referenced by tasktree.cpp
>>>               lto.tmp:(Tasking::ExecutionContextActivator::activateTaskTree(Tasking::RuntimeContainer*))
>>> referenced 20 more times
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Full log can be found in https://github.com/termux/termux-packages/actions/runs/11242534272

### What steps will reproduce the bug?

build it.

### What is the expected behavior?

should build.

### System information

```shell
n/a
```

**Comment by fornwall** [comment]
Possibly related: https://github.com/android/ndk/issues/2069

**Comment by twaik** [comment]
Adding `-femulated-tls` to build and link flags did not work, having the same error.

**Comment by twaik** [comment]
`tasktree.cpp` is a part of `$PREFIX/lib/libQt6ExamplesAssetDownloader.a` which is a part of `qt6-qtbase`. Probably it should be rebuilt with `-femulated-tls` but I am not so sure about this. I am even not sure if `femulated-tls` should be applied to CFLAGS/CXXFLAGS, LDFLAGS or both.

**Comment by truboxl** [comment]
I feel that somewhere injected `-flto`. Try add `-flto` in LDFLAGS.

**Comment by twaik** [comment]
Seems like injecting flto to ldflags works locally, but I tried only x86_64 build

**Comment by fornwall** [comment]
> I am even not sure if femulated-tls should be applied to CFLAGS/CXXFLAGS, LDFLAGS or both.

Agreed, I don't think `femulated-tls` should be used. My current understanding is that NDK should take care of using emulated TLS when targeting API level 28 or lower, https://android.googlesource.com/platform/bionic/+/HEAD/android-changes-for-ndk-developers.md#elf-tls-available-for-api-level-29:

> Android supports [ELF TLS](https://android.googlesource.com/platform/bionic/+/HEAD/docs/elf-tls.md) starting at API level 29. Since NDK r26, clang will automatically enable ELF TLS for minSdkVersion 29 or higher. Otherwise, the existing emutls implementation (which uses pthread_key_create() behind the scenes) will continue to be used. This means that convenient C/C++ thread-local syntax is available at any API level; at worst it will perform similarly to “roll your own” thread locals using pthread_key_create() but at best you'll get the performance benefit of ELF TLS, and the NDK will take care of the details.

And indeed, as indicated above, the issue might be that `flto` needs to be used both when compiling and linking for the above to work (having it only for compilation was the issue in https://github.com/android/ndk/issues/2069, and might be the issue here as well).

**Comment by fornwall** [comment]
> Seems like injecting flto to ldflags works locally, but I tried only x86_64 build

Verified a 32-bit arm build as well locally. Created the #21739 PR with it, let's see a complete CI run.
