### ISSUE TITLE
[Bug]: python-dev not installed

### ISSUE THREAD

**Issue by Kivypls** [termux/termux-packages#21775]
### Problem description

When installing python-dev, the error "package ' python-dev' has no installation candidate" appears

### What steps will reproduce the bug?

I am writing pkg install python-dev

### What is the expected behavior?

For some reason it doesn't install

### System information

```shell
Samsung Galaxy A10
```

**Comment by Biswa96** [comment]
> I am writing pkg install python-dev

There is no such package in termux.
