### ISSUE TITLE
Recursion in `termux_setup_wayland_cross_pkg_config_wrapper` function

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#21777]
https://github.com/termux/termux-packages/blob/52bd744bcb9ea9901ccb68e10de181dc18e4e3ef/scripts/build/setup/termux_setup_pkg_config_wrapper.sh#L20

**Comment by TomJo2000** [comment]
Both of you are gonna need to elaborate.
What's the issue here?

**Comment by Biswa96** [comment]
The `termux_setup_wayland_cross_pkg_config_wrapper` function seems to call itself in the shell script.

**Comment by Biswa96** [comment]
We both changed the title at same time :slightly_smiling_face:

**Comment by TomJo2000** [comment]
Jinx

**Comment by truboxl** [comment]
Don't be Push trigger happy

**Comment by twaik** [comment]
Currently I can not fix it. Can someone please switch lines between these 2 and commit? https://github.com/termux/termux-packages/blob/a338cd8a4f366a0eb4090ac3db915ef6d170527d/packages/vulkan-tools/build.sh#L25 and https://github.com/termux/termux-packages/blob/52bd744bcb9ea9901ccb68e10de181dc18e4e3ef/scripts/build/setup/termux_setup_pkg_config_wrapper.sh#L20

**Comment by twaik** [comment]
Seems like geany switched tab after replacing all occurrences of `termux_setup_pkg_config_wrapper "${TERMUX_PREFIX}/opt/libwayland/cross/lib/x86_64-linux-gnu/pkgconfig` with `termux_setup_wayland_cross_pkg_config_wrapper` and I replaced it back in wrong place.

**Comment by TomJo2000** [comment]
> Seems like geany switched tab after replacing all occurrences of `termux_setup_pkg_config_wrapper "${TERMUX_PREFIX}/opt/libwayland/cross/lib/x86_64-linux-gnu/pkgconfig` with `termux_setup_wayland_cross_pkg_config_wrapper` and I replaced it back in wrong place.

It happens.
A PR and review would have caught this before it ends up on `master`, but we'll just fix it now.

**Comment by TomJo2000** [comment]
> Currently I can not fix it. Can someone please switch lines between these 2 and commit?
> 
> https://github.com/termux/termux-packages/blob/a338cd8a4f366a0eb4090ac3db915ef6d170527d/packages/vulkan-tools/build.sh#L25

This one is also missing an ending `"`.
