### ISSUE TITLE
[Bug]: I can't install pygame on the Termux app

### ISSUE THREAD

**Issue by Kivypls** [termux/termux-packages#21795]
### Problem description

I write the command pip install pygame, but an error comes out (You can see in the screenshot)
I set the default mirror to Termux, update and upgrade also did, it does not help
![5215537250807441169](https://github.com/user-attachments/assets/a3babffe-aae5-454f-8f47-85a1463b3dd2)
![5215537250807441170](https://github.com/user-attachments/assets/15705b35-30d8-45b8-8541-6327d9ce8c07)
![5215537250807441171](https://github.com/user-attachments/assets/9e199d1f-b69d-4fb6-8ef2-bf9ebbcfab78)

### What steps will reproduce the bug?

I set the default mirror to Termux, update and upgrade also did, it does not help

### What is the expected behavior?

Tried everything, reinstalled Termux, installed another version, does not help

### System information

```shell
Samsung Galaxy A10 I don't know what to write here, let it be my phone
```

**Comment by Biswa96** [comment]
You can install pygame from TUR https://github.com/termux-user-repository/tur/tree/master/tur/python-pygame

**Comment by Kivypls** [comment]
Thank you

**Comment by fladd** [comment]
> You can install pygame from TUR https://github.com/termux-user-repository/tur/tree/master/tur/python-pygame
> 
> ```
> $ pkg install tur-repo
> $ pkg install python-pygame
> ```

This unfortunately does not work. It will complain about unsatisfied dependencies. Python-pygame depends on sdl2, but it is not installable.

**Comment by fladd** [comment]
> > You can install pygame from TUR https://github.com/termux-user-repository/tur/tree/master/tur/python-pygame
> > ```
> > $ pkg install tur-repo
> > $ pkg install python-pygame
> > ```
> 
> This unfortunately does not work. It will complain about unsatisfied dependencies. Python-pygame depends on sdl2, but it is not installable.

Apparently you also need the x11-repo.

But still, even when it installs, it gives an error on importing pygame:

```
Python 3.12.11 (main, Jun 10 2025, 09:01:37) [Clang 18.0.3 (https://android.googlesource.com/toolchain/llvm-project d8003a456 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pygame/__init__.py", line 92, in <module>
    from pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen failed: library "libandroid-support.so" not found: needed by /data/data/com.termux/files/usr/lib/python3.12/site-packages/pygame/base.cpython-312.so in namespace (default)

```
