### ISSUE TITLE
Building with docker issue

### ISSUE THREAD

**Issue by shaqman** [termux/termux-packages#2179]
Hi, 
I am under the impression that building using docker doesn't needs any configuration. However, after configuring docker and executing:

PS D:\bS\projects\termux-packages> .\scripts\run-docker.ps1
Running container termux-package-builder from image termux/package-builder...
Creating new container...
Unable to find image 'termux/package-builder:latest' locally
latest: Pulling from termux/package-builder
0bd639347642: Pull complete
15f827925d02: Pull complete
8d4e9883d6b5: Pull complete
c754e879539b: Pull complete
85f5abd03ce7: Pull complete
715bddf0a668: Pull complete
7f01d0b672f6: Pull complete
78bcbd64f974: Pull complete
2a0987a6d45f: Pull complete
Digest: sha256:c3ad9b3bb0f37e9d579f105005752d9b8f0ba8e9bfe38b6d76a00f8759130f62
Status: Downloaded newer image for termux/package-builder:latest
23cec6044ac59674ab7a0c8def041f1979332706a97a2ea2d4bf73bf8c453957

I found the following issues:

builder@23cec6044ac5:~/termux-packages$ ./build-all.sh
/usr/bin/env: ‘python3\r’: No such file or directory

builder@23cec6044ac5:~/termux-packages$ ./build-package.sh libandroid-support
: not founder/termux-packages/scripts/config.guess: 4: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 6: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 33: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 34: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 36: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 48: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 57: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 60: /home/builder/termux-packages/scripts/config.guess:
/home/builder/termux-packages/scripts/config.guess: 63: /home/builder/termux-packages/scripts/config.guess: Syntax error: word unexpected (expecting "in")

Is there something else I need to configure?

Using Docker version 17.12.0-ce, build c97c6d6 under Windows 10 64 bit (10.0, build 16299)

**Comment by Wetitpig** [comment]
Maybe you can build the docker yourself

**Comment by shaqman** [comment]
I'm not sure what the issue really is, but compiling docker by myself did not help.

What finally did work was changing the line endings. Some *.sh and *.py files had windows style line endings which caused it to assume there were invalid commands (characters)

**Comment by Grimler91** [comment]
@shaqman Thanks for reporting. So you solved it by converting all line endings to windows style? Or by converting all line endings to linux style?

**Comment by shaqman** [comment]
@grimler91

All line endings to Linux style.
There are some other files that have Windows style endings, but so far the build works with the file changes I mention above.

**Comment by Pigpog** [comment]
Thank you, this is still a thing btw
