### ISSUE TITLE
rng-tools could this be added

### ISSUE THREAD

**Issue by wulvyrn** [termux/termux-packages#2180]
there isn't enough entropy on a x86_64 system to install arch linux from rusty's script.

**Comment by sdrausty** [comment]
@wulvyrn thanks for sharing your solution.

> added with https://github.com/sdrausty/TermuxArch/commit/16517a8f6e4421e469c9475be5421219e4df137c this commit; Thank you for this solution  🎼🏄🐬💦

This is a small package:
```
Packages (1) rng-tools-5-4

Total Installed Size:  0.08 MiB
```
It might be possible to package easily too +1

**Comment by wulvyrn** [comment]
rng-tools doesn't work 
```
unable to adjust write_wakeup_threshold: Permission denied
```

i was able to get the script to work with pacman-key --init, but not with --populate archlinux as there isn't enough entropy in the system.  without rng-tools, a psuedo way would be to have something in a loop on another terminal or just a process running in background.

**Comment by sdrausty** [comment]
@wulvyrn thank you for diving into this matter and sharing.  

> rng-tools doesn't work

Do you think this is because `rng` is accessing dev files that might not be working correctly?  

> was able to get the script to work with pacman-key --init, but not with --populate archlinux 

Ditto.  There was much enthusiasm at `pacman-key --init`: OK, initially...  

> enough entropy

Can you expand this to a couple of short paragraphs?  What are we trying to achieve; and how should this be done?  Are you suggesting a simple script generating entropy (random integers) to resolve this?  

> just a process running in background.

This sounds way simple.

**Comment by wulvyrn** [comment]
rng-tools seem to be an issue in vm containers as they don't have the same rights as a native client.  the error also show up in a few vm hosting areas.  there was no fix for this as far as i researched.

for pseudo entropy, some guys run some commands in a loop on another terminal.  i have not tried this.  it is on my todo list as i'd like to see this working.

another option is to not require signing.  my security hat cringes at this.  it would be one step to get it up and install the keys vice doing pacman-key.  again, not my preferred method.

objective:  install the packages as desired and have a working arch linux install system to play with from there.

i can test this idea on my pixel c and my pixelbook - tomorrow be another day.

**Comment by sdrausty** [comment]
> i'd like to see this working.

Ditto 😂

**Comment by xeffyr** [comment]
Problem with running out of entropy is not relevant for most Android devices. Some of them even have a hardware RNG.

Package `rng-tools` may require root.

Proot makes things slow and entropy won't help here.
