### ISSUE TITLE
[Bug]: I can't create a buildozer.spec

### ISSUE THREAD

**Issue by Kivypls** [termux/termux-packages#21819]
### Problem description

bulldozer is not working for me and I want to add it to the executable using setx path %PATH%;C:\Users\Bulldozer (I wrote an example, based on which it will be necessary to insert the path where the buildozer is located) I do this on a PC in cmd

### What steps will reproduce the bug?

After that, I want to convert my kivy code to an apk file and when I create a bulldozer.spec file using the buildozer init command, the following error appears (buildozer is installed) This is Visual Studio Code on a PC and I will do everything on a computer
![Снимок экрана 2024-10-14 190744 translated](https://github.com/user-attachments/assets/5105b363-5088-4695-9780-e44a30b37e9f)

### System information

```shell
VS code / PC / This is not a Termux / TERMUNAL in VS code
```

**Comment by Kivypls** [comment]
I wanted to write under the old error, but I couldn't:(

**Comment by Biswa96** [comment]
Why are you creating issues about other projects here? Also, you are not even using termux in this case.

**Comment by Kivypls** [comment]
And where is it necessary?

**Comment by Biswa96** [comment]
Figure it out yourself. This is not a search engine.

**Comment by Biswa96** [comment]
You can find the buildozer documentation here https://buildozer.readthedocs.io/en/latest/
