### ISSUE TITLE
usr/bin/ld: skipping incompatible 

### ISSUE THREAD

**Issue by Hax4us** [termux/termux-packages#2182]
first of all thnx guys .....for anything..

can anybody tell me that what is prob in build script or any other issue...

In short the error is :- 
/usr/bin/ld: skipping incompatible /data/data/com.termux/files/usr/lib/libandroid-shmem.so when searching for -landroid-shmem

Here is log

https://api.travis-ci.org/v3/job/344652250/log.txt

**Comment by Grimler91** [comment]
It shouldn't be using /usr/bin/ld, it should use ARCH-linux-androideabi-ld so you need to patch the Makefile to use $(LD) (which is set to the correct linker) instead.

**Comment by Hax4us** [comment]
@Grimler91 thnx fixed
