### ISSUE TITLE
[Bug]: Will I be able to install zlib1g-dev

### ISSUE THREAD

**Issue by Kivypls** [termux/termux-packages#21820]
### Problem description

Will I be able to install zlib1g-dev using the sudo apt-get install zlib1g-dev command on a phone with Root, if they ask me 'Are you rooted' on a phone without Root and if I write 'yes' a lot of letters 'y' will come out

### What steps will reproduce the bug?

It can be seen in the screenshot
![5215537250807441396](https://github.com/user-attachments/assets/eca6273b-c42f-4bfe-bbb6-bd8966685bac)

### What is the expected behavior?

I 've been trying for 8 days now, what kind of behavior can there be here

### System information

```shell
Termux / Samsung Galaxy A10
```

**Comment by twaik** [comment]
Termux is not Ubuntu. Use `pkg install zlib zlib-static`.

**Comment by twaik** [comment]
You already got your answer about "are you rooted" and "yes behaviour". https://github.com/termux/termux-packages/issues/21800#issuecomment-2409063037
