### ISSUE TITLE
Auto update failing for lxmenu-data

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#21831]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [lxmenu-data](https://github.com/termux/termux-packages/blob/5eb156452195b820046cd4095ab63b1528c41a7e/x11-packages/lxmenu-data) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating lxmenu-data [Current version: 0.1.6]
ERROR: No 'latest-release-tag' found (https://api.github.com/repos/lxde/lxmenu-data/releases/latest).
Try using 'newest-tag'.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-10-16 12:19:43 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/11365293436">11365293436</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by Biswa96** [comment]
Fixed in 4c8dead8b477b7b93e3a785a48eeba896cacac81 commit.
