### ISSUE TITLE
Make some Hacking tools package

### ISSUE THREAD

**Issue by Cyb3rD3m0n** [termux/termux-packages#2185]
Hi i want some hacking tools repo for termux.
Im making my own tool for termux ,the name of
tool is InfoSploit😂😂😂, ok lets back to my problem i cant use perfectly termux because of
Root problem and hacking tools problem ,termux will be a famous app for android if you create some penetration testing tools repo and for the root please add sudo ...etc root tools because termux is a linux terminal , all linux terminal need sudo and termux will be better if you add some fake root but fake root will have a activation command and fix some bugs in termux...........

If you create your own hacking repo like kali term,blackarch term,parrotsec term.......termux 1million + downloads will go up and up and up and up like a 100 millions of pentester and hacker will use termux app and use some hacking repo

**Comment by Neo-Oli** [comment]
>  ...........
Try putting your periods at the end of each sentence instead of all at the same place

**Comment by Atavic** [comment]
*tsu* is available as a termux package: tsu allows to gain root shell on Termux.

*proot* is [an implementation like chroot](https://github.com/termux/proot), also available as package.

Inside proot folder there's *termux-chroot* script to setup a chroot to mimic a normal Linux file system.

**Comment by sdrausty** [comment]
@Cyb3rD3m0n for two different types of hacking use:
> [bloom] Create local copy of TermuxArch in TermuxArchBloom.  Useful for hacking and modifying TermuxArch.  

*From https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh*

or

> To add Archstrike and Blackarch distributions follow these steps. Use https://sdrausty.github.io/TermuxArch/ to install, update and configure Arch Linux on device first.

*From https://sdrausty.github.io/TermuxArch/docs/install*
