### ISSUE TITLE
[BUG] Octave-x not working 

### ISSUE THREAD

**Issue by milen-prg** [termux/termux-packages#21868]
### Problem description

The installed Octave is visible in start menu, but returns can't find files.

octave --gui. Do not start.

### What steps will reproduce the bug?

Install octave-x from tur repo and try to start WITH GUI 

### System information

```shell
Android, Termux
```

**Comment by twaik** [comment]
You did not provide correct system information data. The field has clear explanation what you should post there.
![image](https://github.com/user-attachments/assets/7aadb0d0-35ea-4123-9268-e4b395ff65e3)

**Comment by twaik** [comment]
This should be reported to https://github.com/termux-user-repository/tur.
![image](https://github.com/user-attachments/assets/bf25293b-70be-47e8-a857-1d3857f263da)
