### ISSUE TITLE
Auto update failing for libwebp

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#21866]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [libwebp](https://github.com/termux/termux-packages/blob/fdf8283447ecd08f0301e16a80f4d3056899dc59/packages/libwebp) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating libwebp [Current version: 1.4.0-rc1]
dpkg: warning: version 'webp-rfc9649' has bad syntax: version number does not start with digit
INFO: package being updated to webp-rfc9649.
Downloading https://github.com/webmproject/libwebp/archive/vwebp-rfc9649.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

libwebp: failed to calculate the new checksum
Already up to date.
ERROR: failed to update checksum.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-10-18 18:21:21 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/11408702056">11408702056</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by Biswa96** [comment]
libwebp 1.5.0 version has been released.
