### ISSUE TITLE
rar package

### ISSUE THREAD

**Issue by isrgish** [termux/termux-packages#2190]
I would like to have a package for rar to be able to compress on termux.

**Comment by Hax4us** [comment]
apt install p7zip

**Comment by Wetitpig** [comment]
RAR is patented actually... You need to pay for it.

**Comment by Wetitpig** [comment]
@isrgish Check here:
https://en.wikipedia.org/wiki/RAR_(file_format)

> RAR files can be created only with **commercial software WinRAR (Windows)**, **command-line RAR (Windows, MS-DOS, macOS, Linux, Android, and FreeBSD)**, and other software that has written permission from Alexander Roshal or shares copyrighted code under license from Alexander Roshal. Only WinRAR for Windows and Rar for Linux are available as native 64-bit applications. The software license agreements forbid reverse engineering.

**Comment by tomty89** [comment]
The binaries on the official site *might* work on an x86 device. Try it yourself.

**Comment by isrgish** [comment]
I did try using the rar from the linux command line but it doesn't work. Or maybe it needs to be installed and I don't know anything about how to go about it.

Does p7zip do rar?

**Comment by sdrausty** [comment]
@isrgish from `man 7za`:
```
7-Zip is a file archiver with the highest compression ratio. The
       program supports 7z (that implements LZMA compression algorithm), ZIP,
       CAB, ARJ, GZIP, BZIP2, TAR, CPIO, RPM and DEB formats. Compression
       ratio in the new 7z format is 30-50% better than ratio in ZIP format.
.
.
.
-t{Type}
              Type of archive (7z, zip, gzip, bzip2 or tar. 7z format is
              default)
```

> Does p7zip do rar?

Doesn't look like it does.

**Comment by its-pointless** [comment]
there is rar for android. But it doesn't have a command line tool in the apk. So this is not possible afaik.

**Comment by Wetitpig** [comment]
@isrgish there are only tools for unraring

**Comment by isrgish** [comment]
Is there anyway of making the Linux command line tool from the website work on Android termux?

**Comment by Wetitpig** [comment]
@isrgish there is no source code

**Comment by Grimler91** [comment]
Closing this as we can't port it as @Wetitpig has said.
