### ISSUE TITLE
[CI] Require pull request to have packages with newer version or revision

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#21906]
It is known problem that `upload` workflow fails in the case if aptly tries to upload version already present in repos. But there it does not fail for PRs because `upload` workflow is being skipped (for non-master branches).
I think we should enable it and make it check if version is present on `packages.termux.org` instead of actually uploading it in the case if runner works on non-master branch.
Thank you.
Ping @Grimler91 @agnostic-apollo @2096779623.

**Comment by TomJo2000** [comment]
As part of the Linter step we could check the diff for the commit(s) to check that it contains either of these two lines.
```diff
+TERMUX_PKG_VERSION
+TERMUX_PKG_REVISION
```
Indicating the version or revision was changed.

**Comment by twaik** [comment]
But probably linter can use curl to get current package version from URL like `https://github.com/termux/termux-packages/blob/master/packages/$PACKAGE/build.sh`. No need for invoking git for checking history or clone current repo.

**Comment by TomJo2000** [comment]
> But probably linter can use curl to get current package version from URL like `https://github.com/termux/termux-packages/blob/master/packages/$PACKAGE/build.sh`. No need for invoking git for checking history or clone current repo.

I was trying not to tie it too closely to the specific repo so forks wouldn't have to do extra work.
But something like that should be easy enough to do.

**Comment by twaik** [comment]
We can take URL from `properties.sh`, should not be a problem.

**Comment by TomJo2000** [comment]
That isn't currently in the `properties.sh` I don't think.

**Comment by twaik** [comment]
There is another viable option. `git config --get remote.origin.url` gives you url of the place you cloned termux-packages from. But I think we should transform it to url in the case if it was cloned with ssh or github cli.
