### ISSUE TITLE
[Bug]: `wine-stable` fails to be built in docker

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#21926]
### Problem description

Wine fails to be built in docker for arch `x86_64`.
Fresh docker instance did not help.
The problem is our toolchain, it can not work with `-mabi`.

```
echo | ~/.termux-build/_cache/android-r27b-api-24-v1/bin/x86_64-linux-android-clang -x c - -mabi=ms
clang: error: unsupported option '-mabi=' for target 'x86_64-unknown-linux-android24'
```

Last time package was updated at 22/Jan/24 and was not updated since.
But we updated our toolchain 3 times (26b, 27, 27b) so probably `-mabi` support was dropped in some of these releases.

### What steps will reproduce the bug?

```
./scripts/run-docker.sh ./build-package.sh -I -f -a x86_64 wine-stable
...
x86_64-linux-android-clang -m64 -c -o dlls/dinput/data_formats.o /home/builder/.termux-build/wine-stable/src/dlls/dinput/data_formats.c -Idlls/dinput \
  -I/home/builder/.termux-build/wine-stable/src/dlls/dinput -Iinclude \
  -I/home/builder/.termux-build/wine-stable/src/include \
  -I/home/builder/.termux-build/wine-stable/src/include/msvcrt -D_UCRT -D__WINESRC__ \
  -DDIRECTINPUT_VERSION=0x0700 -Wall -pipe -fcf-protection=none -fvisibility=hidden \
  -fno-stack-protector -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Winit-self -Wno-pragma-pack -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -fPIC \
  -fasynchronous-unwind-tables -D_WIN32 -fno-builtin -fshort-wchar -Wno-format -mabi=ms \
  -I/data/data/com.termux/files/usr/include 
clang: error: unsupported option '-mabi=' for target 'x86_64-unknown-linux-android24'
```
The error I mentioned happens with first invocation of `-mabi`, there are no other invocations mentioned in the log.
[wine-log.txt](https://github.com/user-attachments/files/17468851/wine-log.txt)

**Comment by twaik** [comment]
Ping @fornwall @Maxython @truboxl @licy183 @finagolfin @Grimler91 because you commited to toolchains directory. Sorry for ping.

**Comment by twaik** [comment]
Update:
Clang on Ubuntu host gives similar results:
```
twaik@twaikpc:~/termux-packages$ echo | clang -x c - -mabi=ms
clang: error: unsupported option '-mabi=' for target 'x86_64-pc-linux-gnu'
```
And on termux
```
~ $ echo | clang -x c - -mabi=ms
error: unknown target ABI 'ms'
```

**Comment by licy183** [comment]
`-mabi=ms` is ignored by by `clang<=16` and becomes an error since `clang>=17`.

Ignoring this flag when building for target `x86_64-linux-android` should be safe, because
1. `dlls/*/*.o` are dev libs in unix format. They just be installed as `dev` files. `wine` needs the `dlls` to run successfully. Ignoring this flag will not break the functionality of wine.
2.  `-mabi=ms` is ignored in previous clang. If this flag is important enough, all the libraries compiled before have already been broken.

**Comment by twaik** [comment]
Wow. I just checked another solution.
I just remembered I used regular ubuntu's as compiler to build pixman for termux-x11 because ndk's as was incompatible and tried this
```
	if [ "$TERMUX_ARCH" = "x86_64" ]; then
		mkdir -p "$TERMUX_PKG_TMPDIR/bin"
		cat <<- EOF > "$TERMUX_PKG_TMPDIR/bin/x86_64-linux-android-clang"
			#!/bin/bash
			if [[ " \$@ " == *" -mabi="* && " \$@ " == *" -o "* ]]; then
				exec gcc "\$@"
			else
				exec $TERMUX_STANDALONE_TOOLCHAIN/bin/x86_64-linux-android-clang "\$@"
			fi
		EOF
		chmod +x "$TERMUX_PKG_TMPDIR/bin/x86_64-linux-android-clang"
		export PATH="$TERMUX_PKG_TMPDIR/bin:$PATH"
	fi
```
Shocking. It worked fine.
But it is not a right solution so I'll just add a patch removing `-mabi=ms` from CFLAGS.
Thank you.

**Comment by twaik** [comment]
I mean it worked when I installed it to device. And it is shocking me twice.

**Comment by licy183** [comment]
Creating a wrapper for `x86_64-linux-android-clang` should be a good choice. Removing `-mabi=ms` from `MSVCRTFLAGS` by patching `configure{,.ac}` is not correct, because this should be necessary when building the dlls.
