### ISSUE TITLE
Package request: upx

### ISSUE THREAD

**Issue by xqdoo00o** [termux/termux-packages#2192]
The compiled binary of Golang is too big,  `UPX` would help a lot. [upx](https://github.com/upx/upx)

**Comment by sdrausty** [comment]
@xqdoo00o `upx` is available in Termux via https://sdrausty.github.io/TermuxArch/.  Use https://sdrausty.github.io/TermuxArch/ to setup Arch Linux in Termux PRoot if desired.
```
$ pacman -Ss upx
community/upx 3.94-1
    Ultimate executable compressor.
```

**Comment by xqdoo00o** [comment]
@sdrausty Thanks !!! waiting for upx 3.95 which fixed  `aarch` with option  `'--best'` error.

**Comment by frink** [comment]
upx should be included in base termux.
