### ISSUE TITLE
[Bug]: main/fte's hostbuild-step fails to complete successfully due to the presence of glibc 2.39 in the package builder after the update to Ubuntu 24.04

### ISSUE THREAD

**Issue by robertkirkman** [termux/termux-packages#21960]
### Problem description

Since the docker builder image was updated to Ubuntu 24.04 which comes with glibc 2.39 https://github.com/termux/termux-packages/commit/ce35b3a1265b8e2eaab5ff686e0e8817be2c0b21, the hostbuild-step of the `termux-packages` `fte` package now fails to complete successfully due to the presence of glibc >= 2.38 in the build environment:

https://github.com/termux/termux-packages/blob/3bf8927ead6130cd5aab0a9075d5ae00c6b5821a/packages/fte/build.sh#L28-L32

Result:
```
g++ -c s_string.cpp   -Wall -Wpointer-arith -Wconversion -Wwrite-strings -Winline -g    -I/usr/include/qt3 -I/usr/lib64/qt-3.3/include  -I/usr/include/slang -DUNIX -DLINUX
In file included from s_string.cpp:3:
/usr/include/string.h:506:15: error: conflicting declaration of ‘size_t strlcpy(char*, const char*, size_t)’ with ‘C’ linkage
  506 | extern size_t strlcpy (char *__restrict __dest,
      |               ^~~~~~~
In file included from s_string.cpp:1:
s_string.h:10:8: note: previous declaration with ‘C++’ linkage
   10 | size_t strlcpy(char *dst, const char *src, size_t size);
      |        ^~~~~~~
/usr/include/string.h:506:15: error: declaration of ‘size_t strlcpy(char*, const char*, size_t) noexcept’ has a different exception specifier
  506 | extern size_t strlcpy (char *__restrict __dest,
      |               ^~~~~~~
s_string.h:10:8: note: from previous declaration ‘size_t strlcpy(char*, const char*, size_t)’
   10 | size_t strlcpy(char *dst, const char *src, size_t size);
      |        ^~~~~~~
/usr/include/string.h:512:15: error: conflicting declaration of ‘size_t strlcat(char*, const char*, size_t)’ with ‘C’ linkage
  512 | extern size_t strlcat (char *__restrict __dest,
      |               ^~~~~~~
s_string.h:14:8: note: previous declaration with ‘C++’ linkage
   14 | size_t strlcat(char *dst, const char *src, size_t size);
      |        ^~~~~~~
/usr/include/string.h:512:15: error: declaration of ‘size_t strlcat(char*, const char*, size_t) noexcept’ has a different exception specifier
  512 | extern size_t strlcat (char *__restrict __dest,
      |               ^~~~~~~
s_string.h:14:8: note: from previous declaration ‘size_t strlcat(char*, const char*, size_t)’
   14 | size_t strlcat(char *dst, const char *src, size_t size);
      |        ^~~~~~~
make[2]: *** [fte-unix.mak:159: s_string.o] Error 1
```

Very fortunately, there is actually an existing package for `fte` in the Ubuntu 24.04 official repository, so because the toolchain and build environment that termux-packages hostbuild-steps use is uncannily similar to the build environment that Ubuntu 24.04 official packages use, I can see the exact solution they have used for the same error by looking at the source code created by Ubuntu or Debian for the `fte` packaged in Ubuntu 24.04 and newer.
https://git.launchpad.net/ubuntu/+source/fte/tree/debian/patches/strlcpy.patch

### What steps will reproduce the bug?
```bash
docker container stop termux-package-builder 
docker container rm termux-package-builder
docker image rm ghcr.io/termux/package-builder
scripts/run-docker.sh ./build-package.sh fte
```

### What is the expected behavior?

Successfully use `scripts/run-docker.sh ./build-package.sh fte`

### System information

```shell
N/A
```

**Comment by Biswa96** [comment]
Is that ancient package is actually required? The last update was in 2012-12-12 https://sourceforge.net/projects/fte/

**Comment by TomJo2000** [comment]
Xtkoba has taken a hiatus since the middle of last year.
I wouldn't count on him to be available for comment.

**Comment by truboxl** [comment]
> Is that ancient package is actually required? The last update was in 2012-12-12 https://sourceforge.net/projects/fte/

Yet another candidate for rmpkg

**Comment by twaik** [comment]
I created a merge that removes this package, waiting for @sylirre's approve.

**Comment by Archenoth** [comment]
ahah, I was wondering why this failed to download!

I'm not saying this should come back or anything, don't worry! I'm just amused at how bad my timing is

Basically, I got curious about this editor when I saw it was icculus' [editor of choice](https://youtu.be/i3yVqWYFbCE) two days ago, and noticed `apt search` had it!

But that was before I updated my cache

**Comment by robertkirkman** [comment]
@Archenoth if you like it, you can install it manually from the disabled-packages folder still, but it is just a bit inconvenient. 
there was also a fork of it called "efte" but that is also pretty old and seemed at least at my glance to diverge into two development branches after 2009, a [Debian/Ubuntu branch](https://salsa.debian.org/debian/efte) and a [GitHub branch](https://github.com/lanurmi/efte), with no official releases for 15 years, so it's not clear which exact version of fte would be best to possibly re-package in termux without more users of fte appearing and giving input.

**Comment by Archenoth** [comment]
Oh yeah! I stumbled on `efte` in my initial confusion actually! It seems to require a graphical environment rather than just a terminal though

I was just planning on building it myself, but using disabled-packages is a much better idea! Thanks for the suggestion..! ^^
