### ISSUE TITLE
[Enhancement] rename the pypy to pypy2

### ISSUE THREAD

**Issue by 1q23lyc45** [termux/termux-packages#21975]
Python 2 is outdated and no longer supported.
I think using pypy2 as the default pypy can easily mislead beginners. In the latest versions of many Linux distributions, the default value of Python has been changed to Python 3. I think Pypy needs to follow up.
So I suggest changing the original pypy to pypy2 and creating a new pypy as a meta package pointing to pypy3.
I hope you will consider this suggestion.

**Comment by licy183** [comment]
As the maintainer of `pypy` and `pypy3`, I'm afraid that I'll not change this. In most of distros, `pypy` stands for `pypy2` and `pypy3` stands for `pypy3`. Besides, the source code of pypy is written in RPython, which is based on Python 2, so pypy and pypy3 must use python2 to translate the source code to C.

**Comment by 1q23lyc45** [comment]
> As the maintainer of `pypy` and `pypy3`, I'm afraid that I'll not change this. In most of distros, `pypy` stands for `pypy2` and `pypy3` stands for `pypy3`. Besides, the source code of pypy is written in RPython, which is based on Python 2, so pypy and pypy3 must use python2 to translate the source code to C.

Perhaps we can rename pypy to pypy2, which would be better.

**Comment by 1q23lyc45** [comment]
I just want this:
```
apt -s install pypy
NOTE: This is only a simulation!
      apt needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'pypy2' for 'pypy'
Suggested packages:
  pypy2-tkinter
Recommended packages:
  clang make pkg-config
The following NEW packages will be installed:
  pypy2
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst pypy2 (7.3.17 termux-main stable:stable [aarch64])
Conf pypy2 (7.3.17 termux-main stable:stable [aarch64])
```
Otherwise, now (see below), there is no prompt for not directly installing pypy2, it's too misleading!
```
apt -s install pypy
NOTE: This is only a simulation!
      apt needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  pypy-tkinter
Recommended packages:
  clang make pkg-config
The following NEW packages will be installed:
  pypy
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst pypy (7.3.17 termux-main stable:stable [aarch64])
Conf pypy (7.3.17 termux-main stable:stable [aarch64])
```
The latter one is too misleading!

**Comment by 1q23lyc45** [comment]
https://repology.org/project/pypy/versions
Starting from debian 12, 13, SID, and Ubuntu 23.04, 23.10, and 24, pypy(2) has been removed completely and pypy3 has been used.
