### ISSUE TITLE
Package request:  minicom

### ISSUE THREAD

**Issue by brad112358** [termux/termux-packages#220]
With USB OTG and a usb serial adapter, minicom would be a handy tool for server console access and embedded device development.  I currently run a full chroot environment with vnc to get this function on my phone (the android serial terminal emulators I've tried can't keep up with reasonable baud rates).

**Comment by its-pointless** [comment]
I have minicom kind of working on my termux-packages fork. i have no way to test it though. Some functionality doesn't work like file transfer selecting a file causes segfault but i doubbt you need that.

**Comment by its-pointless** [comment]
welp updated tool chain so it all works as well as lrzsz

**Comment by fornwall** [comment]
@brad112358 Can you try out the appropriate build for your arch from the following list (download with `wget <url>` and install with `dpkg -i <file>`):

http://fornwall.net/tmp/minicom_2.7_arm.deb
http://fornwall.net/tmp/minicom_2.7_i686.deb
http://fornwall.net/tmp/minicom_2.7_aarch64.deb

They are built from the pull request by @its-pointless - I just want to check if it's possible to use this on Android or not with an usb serial adapter, so that it makes sense having such a package!

**Comment by its-pointless** [comment]
http://antipastohw.pbworks.com/w/page/54179823/Working%20with%20USB%20serial%20adapters%20in%20Android

Its possible but frankly if someone uses it I would be surprised.

**Comment by brad112358** [comment]
Sorry for the delay in testing.  I hadn't noticed the responses here.  I downloaded the arm package (wget crashes for me most of the time so I downloaded it from the browser).  The package installed fine and it works!
I used a pl2303 serial adapter via a USB OTG cable on my rooted SG Note 4.
I had to change the mode or ownership of the device (/dev/ttyUSB1 in my case) using su after plugging in the serial adapter, but otherwise it just worked once I properly set the default tty device, baud, flow control, etc as normal via "minicom -s".

I use USB serial devices on android often for debugging various embedded boards.  I usually use a full linux chroot environment since the native Android serial applications are invariably too slow to keep up with typical baud rates.  The kernel drivers for the (couple different chipsets) USB serial adapters I own has been available with no problem on all of the (2 Samsung, Asus, and Nook running CM) android devices I have owned over the years.

You might still be correct about not many other people using it, but I will!

Thanks for the package!

**Comment by brad112358** [comment]
BTW,  The first thing I tried when I got permission denied opening /dev/ttyUSB1 was running minicom under su but this resulted in "CANNOT LINK EXECUTABLE DEPENDENCIES: library "libandroid-support.so" not found".  Is this expected?  Does running things as root not work as normal under termux?

**Comment by its-pointless** [comment]
Yes that is normal since invoking su doesn't maintain the LD_LIBRARY_PATH environment setting. There are plans to fix that.

**Comment by drtrigon** [comment]
What is the recommended way of using this? wget from termux? Or is there an other way? Will that package be integrated into termux in future?

**Comment by its-pointless** [comment]
wget the deb files then dpkg -i minicom_2.7_aarch64.deb. It requires root to use which is why it probably won't be  added.  That and very few would even use this.

**Comment by fornwall** [comment]
As there has been some interest, and the packages are small, I've added the minicom and lrzsz packages now thanks to @its-pointless!

They are available for installation as normal packages after running `apt update`.

**Comment by therealjayvi90** [comment]
OMG THANK YOU

**Comment by drtrigon** [comment]
Thanks! Useful for in the field debugging.

**Comment by chriscarver** [comment]
Having trouble getting minicom to work

Have tried:
sudo minicom
env TERM=vt100 sudo minicom

Always get No cursor motion capability (cm)
