### ISSUE TITLE
Auto update failing for ol

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#22020]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [ol](https://github.com/termux/termux-packages/blob/cdc4ea8188f3d89043f88eb7dd874c570855f43f/packages/ol) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating ol [Current version: 2.5.1]
INFO: package being updated to 2.6.
Downloading https://github.com/yuriy-chumak/ol/archive/2.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 2281k    0 2281k    0     0  4314k      0 --:--:-- --:--:-- --:--:-- 4314k

You are about to commit these changes:

--------------------
diff --git a/packages/ol/build.sh b/packages/ol/build.sh
index c7be41d084..a4fd969c70 100644
--- a/packages/ol/build.sh
+++ b/packages/ol/build.sh
@@ -3,10 +3,9 @@ TERMUX_PKG_DESCRIPTION="Purely functional dialect of Lisp"
 TERMUX_PKG_LICENSE="LGPL-3.0, MIT"
 TERMUX_PKG_LICENSE_FILE="COPYING.LESSER, LICENSE"
 TERMUX_PKG_MAINTAINER="Yuriy Chumak <yuriy.chumak@mail.com>"
-TERMUX_PKG_VERSION="2.5.1"
-TERMUX_PKG_REVISION=1
+TERMUX_PKG_VERSION="2.6"
 TERMUX_PKG_SRCURL=https://github.com/yuriy-chumak/ol/archive/${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=d9fe66bd15cf9c9c30bf45b97e5825c2101b518fc27c671c08a95798eec3c510
+TERMUX_PKG_SHA256=c5506de4005a63039dc96962322ae94bf6c33eeaf63dcc03b07b1e8cc3a4d8f3
 TERMUX_PKG_AUTO_UPDATE=true
 # needs xxd
 TERMUX_PKG_BUILD_DEPENDS="vim"
--------------------

bump(main/ol): 2.6

Not committing to Git!

INFO: Trying to build package.
INFO: Package ol exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building ol for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0   286k      0 --:--:-- --:--:-- --:--:--  291k
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   6201      0 --:--:-- --:--:-- --:--:--  6216
gpg: Signature made Tue 29 Oct 2024 07:38:58 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0   280k      0 --:--:-- --:--:-- --:--:--  282k
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0  23240      0 --:--:-- --:--:-- --:--:-- 23800
gpg: Signature made Tue 29 Oct 2024 06:42:00 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0   229k      0 --:--:-- --:--:-- --:--:--  232k
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0  16041      0 --:--:-- --:--:-- --:--:-- 16333
gpg: Signature made Tue 29 Oct 2024 03:42:33 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency libiconv@1.17 if necessary...
Found libiconv in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libi/libiconv/libiconv_1.17_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  543k  100  543k    0     0  6571k      0 --:--:-- --:--:-- --:--:-- 6626k
extracting libiconv to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency iconv@1.17 if necessary...
Found iconv in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/i/iconv/iconv_1.17_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8988  100  8988    0     0   219k      0 --:--:-- --:--:-- --:--:--  225k
extracting iconv to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses@6.5.20240831-2 if necessary...
Found ncurses in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-utils@6.5.20240831-2 if necessary...
Found ncurses-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs@6.5.20240831-2 if necessary...
Found ncurses-ui-libs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs-static@6.5.20240831-2 if necessary...
Found ncurses-ui-libs-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs-static to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency vim@9.1.0800 if necessary...
Found vim in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/v/vim/vim_9.1.0800_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1158k  100 1158k    0     0  17.7M      0 --:--:-- --:--:-- --:--:-- 17.9M
extracting vim to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency vim-runtime@9.1.0800 if necessary...
Found vim-runtime in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/v/vim-runtime/vim-runtime_9.1.0800_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4851k  100 4851k    0     0  65.4M      0 --:--:-- --:--:-- --:--:-- 65.8M
extracting vim-runtime to /home/builder/.termux-build/_cache-all...
Downloading https://github.com/yuriy-chumak/ol/archive/2.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 2281k    0 2281k    0     0  6336k      0 --:--:-- --:--:-- --:--:-- 6336k
GNUmakefile:44: Submodules not loaded. Run 'git submodule update --init --recursive' once.
sed -e '/\/\/ /d' src/olvm.c >includes/ol/vm.h
aarch64-linux-android-clang src/olvm.c -o vm \
   extensions/ffi.c -Iincludes \
    -fstack-protector-strong -Oz -std=gnu99 -fno-exceptions -DHAVE_SOCKETS=1 -DHAVE_DLOPEN=1 -DHAVE_SECCOMP=1 -DHAVE_MEMFD_CREATE=0 -lm -D_FILE_OFFSET_BITS=64  -O2 -DNDEBUG -Wno-unused-result -g0 -DPREFIX=\"/data/data/com.termux/files/usr\"  -ldl -Xlinker --export-dynamic
Ok.
cp vm olvm
strip olvm
strip: Unable to recognise the format of the input file `olvm'
make: *** [GNUmakefile:260: olvm] Error 1
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-10-30 01:07:57 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/11584619597">11584619597</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by Biswa96** [comment]
Fixed in 471e5a7b5aee68c0c20227372c7ad4df1a3eae5b commit.
