### ISSUE TITLE
[scripts]: dump-repology-metadata fails

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#22023]
### Problem description

1. `https://repology.org/api/v1/projects/?inrepo=termux&outdated=1&families_newest=2-` without `User-Agent` replies with error 403.
2. `https://repology.org/api/v1/projects/taglib?inrepo=termux&outdated=1&families_newest=2-` replies with error 404.
3. `https://repology.org/api/v1/project/taglib?inrepo=termux&outdated=1&families_newest=2-` (no 's' in 'projects') replies valid json, but python throws exception
```
Traceback (most recent call last):
  File "/home/twaik/termux-packages/scripts/updates/api/dump-repology-data", line 114, in <module>
    json.dump(get_outdated_packages(project), f)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/twaik/termux-packages/scripts/updates/api/dump-repology-data", line 57, in get_outdated_packages
    last_project = sorted(repology_data.keys())[
                          ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'keys'
```
Probably repology's API was changed, I did not dive deep into the script.
CC @truboxl @MrAdityaAlok because you commited to `dump-repology-metadata`

### What steps will reproduce the bug?

```
python3 ./scripts/updates/api/dump-repology-data /tmp/repology
```

### What is the expected behavior?

N/A.

### System information

```shell
Irrelevant.
```

**Comment by Biswa96** [comment]
The following change show some output but I do not know the expected result.

```diff
 def get_repology_data(last_project, project):
     url = f"https://repology.org/api/v1"
     if project != "":
-        url = f"{url}/projects/{project}?inrepo=termux&outdated=1"
+        url = f"{url}/projects/?search={project}&inrepo=termux&outdated=1"
     else:
-        url = f"{url}/projects/{last_project}?inrepo=termux&outdated=1&families_newest=2-"
+        url = f"{url}/projects/?search={last_project}&inrepo=termux&outdated=1&families_newest=2-"
```

**Comment by twaik** [comment]
@AMDmi3 can you please tell us if API was changed?

**Comment by AMDmi3** [comment]
API hasn't changed, but I've blocked more clients which do not properly identify themselves.

> 1. `https://repology.org/api/v1/projects/?inrepo=termux&outdated=1&families_newest=2-` without `User-Agent` replies with error 403.
> 
> 2. `https://repology.org/api/v1/projects/taglib?inrepo=termux&outdated=1&families_newest=2-` replies with error 404.
> 
> 3. `https://repology.org/api/v1/project/taglib?inrepo=termux&outdated=1&families_newest=2-` (no 's' in 'projects') replies valid json, but python throws exception

Depends on what you need, 1 and 2 are for projects listing, but 2 is malformed, should have slash after `taglib` (it's pagination, `projects/` is the first page, `projects/foo/` is projects starting with `foo`) and 3 is for individual project. In either case, you must set unique user agent which identifies your script.

**Comment by truboxl** [comment]
I believe we already done setting user agent
https://github.com/termux/termux-packages/commit/d318b1c460dd7a25715885018e68230cbacd7ca5

Probably need to fix the rest of the issue

**Comment by twaik** [comment]
Yeah, but that is not a `dump-repology-metadata` script.

**Comment by AMDmi3** [comment]
Yes, `check-auto-update` is getting 200's. The fix for `dump-repology-metadata` looks good.
