### ISSUE TITLE
[Bug]: Can't compile libgd on my device

### ISSUE THREAD

**Issue by Cigydd** [termux/termux-packages#22038]
### Problem description

Trying to build the rhythmbox player lead me to a libgd compilation problem.
Shrunk to a libgd compilation issue.

[build.log](https://github.com/user-attachments/files/17582416/build.log)

### What steps will reproduce the bug?

1. Clone the termux packages repository
2. Run the `./build-package.sh libgd` script on your mobile device
3. Watch the output

### What is the expected behavior?

`libgd` should compile

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=1035
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://nl.mirror.flokinet.net/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://nl.mirror.flokinet.net/termux/termux-x11 x11 main
Updatable packages:
mesa/stable 24.2.5 aarch64 [upgradable from: 24.0.8-1]
svt-av1/stable 2.3.0 aarch64 [upgradable from: 2.2.1]
termux-tools version:
1.44.2
Android version:
14
Kernel build information:
Linux localhost 4.14.190-perf-28693687-abA525FXXU8FXH1 #1 SMP PREEMPT Tue Aug 6 16:11:25 +07 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A525F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.window versionCode:15
com.termux.widget versionCode:13
com.termux.api versionCode:51
com.termux.tasker versionCode:6
com.termux.styling versionCode:31
```

**Comment by Biswa96** [comment]
Could you try adding the following function in libgd/build.sh file?

```sh
termux_step_pre_configure() {
        autoreconf -fi
}
```

**Comment by Cigydd** [comment]
Well, we got a bit further...
[build.log](https://github.com/user-attachments/files/17594263/build.log)

**Comment by Cigydd** [comment]
> git checkout fba6c5e7b12bf8d943fe9de4af1f199d2635325e         
> ./build-package.sh -f libgd 2>&1 | tee ~/storage/downloads/build.log
[build.log](https://github.com/user-attachments/files/17594838/build.log)
... Success!

**Comment by Biswa96** [comment]
I can not reproduce the issue in termux package builder container. On device builds are not done for most of the cases.

**Comment by Cigydd** [comment]
OK, if on device builds aren’t something important and my bug has manifested itself on device only then I think it’s the time to close this bug. Whoever runs into something similar, feel free to reopen.

My goal was to build rhythmbox and I have since then achieved that goal by simply installing the packages that don’t compile from the regular binary package repository 😁
