### ISSUE TITLE
Unable to show travis logs

### ISSUE THREAD

**Issue by Hax4us** [termux/termux-packages#2204]
i am facing very strange problem . 
Here is my PR
https://github.com/termux/termux-packages/pull/2203

Actually I can't see the logs of exiv2 build process I don't know why?
Thnx in advance :)

**Comment by shaqman** [comment]
AFAIK, build-package.sh only build packages under packages folder. I see you commited exiv2 outside of packages folder. That is why the build succeeded with message: 
`termux - build of 'autoconf-archive' done`

since autoconf-archive was the only package that was changed udner packages folder.

**Comment by Hax4us** [comment]
Lol I did not checked this ...btw thnx man
