### ISSUE TITLE
package request: mdp

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#2205]
mdp - A command-line based markdown presentation tool.

https://github.com/visit1985/mdp
![797c494c-a043-11e4-9dbd-959cab4055fa 1](https://user-images.githubusercontent.com/782908/36726551-e7b40ae8-1b98-11e8-9349-66b8288847bd.gif)

**Comment by Hax4us** [comment]
made a pull request for it  https://github.com/termux/termux-packages/pull/2206

**Comment by fornwall** [comment]
The package is now available for installation!
