### ISSUE TITLE
Auto update failing for enchant

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#22055]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [enchant](https://github.com/termux/termux-packages/blob/fba6c5e7b12bf8d943fe9de4af1f199d2635325e/packages/enchant) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating enchant [Current version: 2.8.2]
ERROR: No 'latest-release-tag' found (https://api.github.com/repos/AbiWord/enchant/releases/latest).
Try using 'newest-tag'.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-10-31 18:30:11 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/11617403347">11617403347</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by Biswa96** [comment]
The upstream enchant repository is being moved from https://github.com/AbiWord/enchant to https://github.com/rrthomas/enchant. Probably, it would take some time to add the releases in new repository.
