### ISSUE TITLE
[Bug]: compilation error when install python readline via pip

### ISSUE THREAD

**Issue by to-mg** [termux/termux-packages#22068]
### Problem description

When installing python package readline via "pip install readline", compilation step aborts with following error:

Modules/3.x/readline.c:1179:34: error: incompatible function pointer types assigning to 'char *(*)(FILE *, FILE *, const char 
*)' (aka 'char *(*)(struct __sFILE *, struct __sFILE *, const char *)') from 'char *(FILE *, FILE *, char *)' (aka 'char *(struct __
sFILE *, struct __sFILE *, char *)') [-Wincompatible-function-pointer-types]
       1179 |     PyOS_ReadlineFunctionPointer = call_readline;
            |                                  ^ ~~~~~~~~~~~~~
[error.readline.txt](https://github.com/user-attachments/files/17600793/error.readline.txt)

### What steps will reproduce the bug?

pkg install python
pip install readline

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18553
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.accum.se/mirror/termux.dev/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.44.3
Android version:
12
Kernel build information:
Linux localhost 5.4.161 #1 SMP PREEMPT Sat Feb 18 17:35:13 CST 2023 aarch64 Android
Device manufacturer:
incar
Device model:
Npad-Pro
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Biswa96** [comment]
You can workaround the compiler error with `CFLAGS="-Wno-error=incompatible-function-pointer-types"` environment variable.

The issue is not related to termux specifically. clang is just stricter now with the rules.
