### ISSUE TITLE
[Bug]: new pkgconf cannot find the pkgconfig folders during hostbuild-steps yet

### ISSUE THREAD

**Issue by robertkirkman** [termux/termux-packages#22060]
### Problem description

As reported by @Biswa96 [here](https://github.com/termux/termux-packages/pull/22027#issuecomment-2450483465), the new `pkgconf`  2.3.0 build in the Dockerfile seems to be not quite ready yet but I went ahead and tried to see if I can help fix it. It was not able to find Ubuntu host's `libpng`  Cflags for a hostbuild-step.

https://github.com/termux/termux-packages/blob/524d5a80f35aa6c548f2e53a0af1a4b779b97369/scripts/setup-ubuntu.sh#L343-L355

### What steps will reproduce the bug?

```bash
scripts/run-docker.sh pkgconf -cflags libpng
```
- Result
```
Package libpng was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpng.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpng' not found
```

### What is the expected behavior?

```
-I/usr/include/libpng16
```

### System information

```shell
N/A
```

**Comment by jhays1818** [comment]
/

![Image](https://github.com/user-attachments/assets/84f0079c-3e99-4e1c-ab07-536accd8d27e)
