### ISSUE TITLE
node/node-current lack ICU support

### ISSUE THREAD

**Issue by vsemozhetbyt** [termux/termux-packages#2210]
Is there a reason that `node`/`node-current` are built with `--without-intl` flag?

This limits JavaScript and Node.js API functionality significantly: https://nodejs.org/api/intl.html#intl_options_for_building_node_js

Moreover, without `small-icu` support a user cannot add more ICU locales (up to `full-icu` npm module) at runtime: https://nodejs.org/api/intl.html#intl_providing_icu_data_at_runtime

Can `node`/`node-current` be built with `--with-intl=small-icu` flag?

**Comment by vsemozhetbyt** [comment]
Also, one of the new RegExp features is not supported without ICU: https://github.com/nodejs/node/pull/19052

**Comment by fornwall** [comment]
The updated `10.10.0-1` now uses the libicu package. Let me know if anything is broken!

**Comment by vsemozhetbyt** [comment]
Thank you a lot!

**Comment by vsemozhetbyt** [comment]
I've checked some things from the table in https://nodejs.org/api/intl.html#intl_options_for_building_node_js and they are OK. Thank you again.
