### ISSUE TITLE
Termux Fedora Proot issue?

### ISSUE THREAD

**Issue by Root-voidX** [termux/termux-packages#2212]
Hey guys, so I was trying to run Fedora on my Galaxy S7 Edge (and possibly my Galaxy S9+ when I get it in 2 weeks). I have used Proot in Gnuroot Debian before, I am trying to get a full fedora distro on arm to run some scientific packages and visualization packages like blender and paraview. Anyway I used nmilosev script to install Fedora. I am running the latest proot (Version 5.1.107-5) and when I type in

`startfedora`

I get an error code:

`proot info: vpid:1 terminated with signal 1`

What is my issue? Is this due to Selinux? Do I need to be rooted?

**Comment by Hax4us** [comment]
Maybe the main problem was arised while extracting fedora tar file ...
you should manually follow script steps

**Comment by sdrausty** [comment]
> proot info: vpid:1 terminated with signal 1

This might be incorrect system image for device architecture.  See whether the Fedora system image matches your device architecture.  No, you do not need root to run PRoot.  These are two separate concepts.

**Comment by Root-voidX** [comment]
@sdrausty, It doesn't matter if install the armhf version (f26_arm or f27_arm) it still gives me the same error. I may reinstall termux and try to manually type in the comments in nmilosev script like @Hax4us suggested.

**Comment by Root-voidX** [comment]
Okay update,

After doing it manually I get this error:

'$ startfedora
proot error: '/bin/env' not found (root = /data/data/com.termux/files/home/fedora, cwd = /data/data/com.termux/files/home, $PATH=(null))
fatal error: see `proot --help`.'

**Comment by sdrausty** [comment]
@Root-voidX find `env`.  It should be in `$HOME/fedora/bin/env` and adjust `startfedora` accordingly.  Have you tried https://sdrausty.github.io/TermuxArch/ which installs Arch Linux in Termux?  It's created because I was having difficulties with Termux chroots like you are having now, including Fedora.

**Comment by Root-voidX** [comment]
@sdrausty I looked at that directory and it doesn't exist. I am confused??? I will looking into your code. So its basically an Arch Linux container like gnuroot debian right? I am trying/playing with the idea of a mini pc for running code,simulation, visualization. So I assume I can install lxde and use  xsdl to export a gui and programs directly from Termux?

**Comment by Hax4us** [comment]
u checked in /bin now check in /usr/bin/

**Comment by Root-voidX** [comment]
This is my / directory:
'
cd /
$ ls
acct                           init.usb.rc
bugreports                     init.wifi.rc
cache                          init.zygote32.rc
config                         init.zygote64_32.rc
cpefs                          knox_data
d                              lib
data                           mnt
default.prop                   oem
dev                            persdata
efs                            postrecovery.do
etc                            preload
factory                        proc
file_contexts.bin              property_contexts
fstab.goldfish                 publiccert.pem
fstab.ranchu                   root
fstab.samsungexynos8890        sbin
fstab.samsungexynos8890.fwup   sdcard
init                           seapp_contexts
init.baseband.rc               sepolicy
init.container.rc              sepolicy_version
init.environ.rc                service_contexts
init.goldfish.rc               storage
init.gps.rc                    sys
init.ranchu.rc                 system
init.rc                        ueventd.goldfish.rc
init.rilchip.rc                ueventd.ranchu.rc
init.rilepdg.rc                ueventd.rc
init.samsungexynos8890.rc      ueventd.samsungexynos8890.rc
init.samsungexynos8890.usb.rc  vendor
init.usb.configfs.rc
'

**Comment by Hax4us** [comment]
Wrong directory bro...i said check in fedora folder just paste this `cd $HOME/fedora/usr/bin`
And check env is exist or not

**Comment by Root-voidX** [comment]
Yeah bro it doesn't exist:

'$ cd $HOME/fedora/usr/bin'
'bash: cd:' '/data/data/com.termux/files/home/fedora/usr/bin: No such file or directory'

**Comment by Hax4us** [comment]
Check fedora folder is exist or not

**Comment by Root-voidX** [comment]
It exist but its empty.

**Comment by Hax4us** [comment]
So how can you run empty fedora ? First extract fedora properly 
Delete old 
`rm -rf fedora`
Then
`apt install bsdtar`
then
`proot --link2symlink -0 bsdtar -xpf your_fedora_tarfile_name`

And check fedora is extracted or not

**Comment by sdrausty** [comment]
This https://github.com/termux/proot/issues/9 "New proot causes problems for Fedora under termux on all Android machines I own," should be of interest for Fedora users.

**Comment by Hax4us** [comment]
@sdrausty check gitter man :)

**Comment by Root-voidX** [comment]
I was able to boot into fedora 27 after installing bsdtar. The issue is I tried to run dnf update, and now couple of packages failed, now trying to run dnf update results in 

`bash: /bin/dnf: /usr/bin/python3: bad interpreter: Permission denied`

**Comment by Hax4us** [comment]
Bro dont mind but now this issue must be move to fedora project bcz your issue is not related to termux and you can use Arch linux in termux instead of Fedora to avoid issues or errors ...

**Comment by Root-voidX** [comment]
Bro, its most probably proot implementation on termux since Arch and debian have the same issue with python 3. Gnuroot debian doesn't but its based on terminal emulator not termux. Could be SELinux :/

**Comment by tomty89** [comment]
What exactly do you get when you just start python?

**Comment by Root-voidX** [comment]
@tomty89

It fails to update to python 3 and causes dnf to brick. I believe it might a f27 issue. I'll revert to f26, and if it persists then idk.

**Comment by Root-voidX** [comment]
F26 fixed my issue boys!! 

Thanks for the help (y)

**Comment by sdrausty** [comment]
@Root-voidX perseverance pays.  Congratulations!

**Comment by Root-voidX** [comment]
@sdrausty Thanks for your help.
