### ISSUE TITLE
Bad Mirrors

### ISSUE THREAD

**Issue by idunknown00** [termux/termux-packages#22137]
![Screenshot 2024-11-06 002101](https://github.com/user-attachments/assets/426ddc64-73f5-450a-90a6-243a07aff863)
 I keep getting bad mirrors i have tried everything...help im lost!!!

**Comment by agnostic-apollo** [comment]
Are you running Termux in some kind of VM?

**Comment by twaik** [comment]
Also it may be related to VPN or something.

**Comment by twaik** [comment]
We do not support any VM configurations except AVD.

**Comment by idunknown00** [comment]
It's Fdroid I got the links off Github

**Comment by idunknown00** [comment]
It was working just fine. I'm not exactly sure what you mean by avd so if
you could explain that a little bit and please don't don't make fun of me
cuz I don't know a whole lot

**Comment by idunknown00** [comment]
Okay so if I download the wsa off of for Windows and it was running just
fine and then I was just stopped running what could cause that because it
was I've been running an app for like 2 weeks with no problem and then all
of a sudden I got a problem
