### ISSUE TITLE
please remove dependency between fzf and tmux, I use zellij

### ISSUE THREAD

**Issue by xronin01** [termux/termux-packages#22136]
### Problem description

![Screenshot_20241105-210420_Termux_1](https://github.com/user-attachments/assets/f10f383a-164f-436b-b1e6-ba62786d5a76)

### What steps will reproduce the bug?

.

### System information

```shell
.
```

**Comment by Juhan280** [comment]
fzf is getting removed because it wasn't explicitly installed rather as the dependency of tmux.
You can install it explicitly using `apt install fzf`

**Comment by licy183** [comment]
Not a bug. As comments above, mark `fnf` as manually-installed package using  `apt install fnf` should solve this.

**Comment by truboxl** [comment]
fzf-tmux needs tmux

What was the problem again?

**Comment by licy183** [comment]
`fzf-tmux` is just a script. Arch Linux also doesn't add `tmux` to dependencies of `fzf` but also provide `fzf-tmux` with it.
