### ISSUE TITLE
Imagemagick graphics corruption for png

### ISSUE THREAD

**Issue by cherryleafroad** [termux/termux-packages#2214]
Imagemagick Version 7.0.7-22 aarch64

image.png
![](https://image.ibb.co/mR372c/bitmoji2003792811.png)

Commands
```
$ magick image.png -transparent white tmp.png
$ magick tmp.png -alpha extract tmp2.png
$ magick tmp2.png \
> -define connected-components:mean-color=true \
> -define connected-components:area-threshold=30 \
> -connected-components 4 \
> tmp3.png
$ magick tmp3.png -morphology Dilate Octagon output.png
```

output.png
![](https://image.ibb.co/cJuTsc/outp.png)

Corruptions like this are very common. No matter what commands I use with imagemagick, the corruptions happen. Sometimes it's fine, but usually the corruptions happen.

This problem probably happens with any kind of image, not only png. Sometimes the program will segfault, other times it says it ran out of memory. It is very sporadic.

**Comment by cherryleafroad** [comment]
Using a separate build of imagemagick works perfectly (it's not related to termux, but I can get it to work by copying the binary and libs over, and `unset LD_PRELOAD`

**Comment by fornwall** [comment]
Could you check if the latest version of the imagemagick package (version `7.0.7.38`) fixes this problem?

If not, does running `export OMP_NUM_THREADS=1` before invoking `magick` help?

**Comment by fornwall** [comment]
I'm closing this issue in favour of #1314.
