### ISSUE TITLE
Firefox crashes every time you wanna use it

### ISSUE THREAD

**Issue by GlineYT** [termux/termux-packages#22154]
![Screenshot_2024-11-07-19-10-22-403.jpg](https://github.com/user-attachments/assets/8e169ccc-fbd4-4d8d-9d49-d5eb33f3817d)

![Screenshot_2024-11-07-19-10-16-991.jpg](https://github.com/user-attachments/assets/41048dba-deb0-4288-8aa2-a2db4f84e7a6)

And it also brings the entire X11 session down with it.

Why does this happen?
And why does it take the entire xfce4 session with it aswell?.

STEPS TO REPRODUCE:
STEP 1:
Install firefox the regular package manager way: pkg install firefox
STEP 2:
just use it as you would any other web broswer. Click links, change settings, whatever. It sometimes crashes after startup, sometimes when you click on a webiste and try and read it, or just by itself.

**Comment by GlineYT** [comment]
Also the panel isn't happy either, but that doesn't crash the xfce4 session

**Comment by twaik** [comment]
https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#how-to-disable-the-phantom-processes-killing
