### ISSUE TITLE
missing mosquittopp

### ISSUE THREAD

**Issue by sruetzler** [termux/termux-packages#2219]
Hello,
I'm needing the cpp wrapper for mosquitto.
Why is it removed from the package?
TERMUX_PKG_RM_AFTER_INSTALL="include/mosquittopp.h lib/libmosquittopp.so"
Regards Simon

**Comment by fornwall** [comment]
Thanks for reporting! The mosquitto version has been updated to version 1.4.15 and no longer removes mosquittopp.
