### ISSUE TITLE
elinks: should be removed from repository due to nasty security issue.

### ISSUE THREAD

**Issue by alive4ever** [termux/termux-packages#2221]
elinks doesn't verify TLS certificate when connecting to https servers.

This is a nasty security issue.

The issue has been reported since 2017[1] and still no action taken to fix this serious security issue.

OpenBSD has removed elinks from their ports repository due to this issue[2].

For a better alternative that works with certificate verification, links2 is available as elinks replacement[3].

[1] http://lists.linuxfromscratch.org/pipermail/elinks-dev/2017-March/002119.html
[2] https://github.com/openbsd/ports/commit/e1e17bc3804d21942b5f89fc81d703af2d5902db
[3] http://links.twibright.com

**Comment by xeffyr** [comment]
Just tested SSL with elinks - looks like some verification checks it does. Seems that this feature was added via this commit: https://github.com/xeffyr/elinks/commit/f43f5714e8815e7c3b2c1f18cd2ca8c311ce5706

![screenshot_20180305-005355](https://user-images.githubusercontent.com/25881154/36951761-c8dfbb46-200f-11e8-8b5e-6b433d54bb4b.png)

**Comment by alive4ever** [comment]
There is no [such commit](http://repo.or.cz/elinks.git/commit/commit/f43f5714e8815e7c3b2c1f18cd2ca8c311ce5706).

If you think that you've fixed the ssl verification issue, you should upstream the patch.

**Comment by xeffyr** [comment]
Termux already [uses](https://github.com/termux/termux-packages/blob/master/packages/elinks/build.sh) latest git version of elinks.
And this commit is present in official git repo: http://elinks.cz/elinks.git/

**Comment by xeffyr** [comment]
@fornwall, @Grimler91, I guess this could be closed for now since git version of elinks do verification of certificates, at least it shows warning when cert is self-signed.
