### ISSUE TITLE
[Package]: Love2d for lua 

### ISSUE THREAD

**Issue by justlimeguy** [termux/termux-packages#22219]
### Why is it worth to add this package?

It would help compile love2d projects from terminal itself, instead going "zip all - rename to love - open love loader - find archive - run"
similar to how it works on arch.

### Home page URL

https://love2d.org/

### Source code URL

https://github.com/love2d/love

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [ ] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by twaik** [comment]
Project is already present. https://github.com/termux/termux-packages/blob/2ad4e335af43a2cbb7329d3e997d73afeb94aa48/x11-packages/love/build.sh

**Comment by justlimeguy** [comment]
how do I install it?
it does not show up in list and says package not found.

**Comment by Biswa96** [comment]
> how do I install it?

`apt install x11-repo; apt update; apt install love`
