### ISSUE TITLE
[Bug]: curl .netrc parser error

### ISSUE THREAD

**Issue by Vanillma** [termux/termux-packages#22243]
### Problem description

Hello, there is a problem in parsing the .netrc file in the new curl update! 
[curl/issues/15496](https://github.com/curl/curl/issues/15496)

A patch for it has been committed in the master branch.
Do you update it in the termux repository as well?
![Screenshot_20241113-085331_Termux](https://github.com/user-attachments/assets/953ed5e8-4a24-4843-8ff4-c0d7c20a5d67)

### What steps will reproduce the bug?

pkg update && pkg upgrade -y
git clone <repository>

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=29635
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.44.3
Android version:
9
Kernel build information:
Linux localhost 3.4.113 #1 SMP PREEMPT Tue Oct 25 18:29:07 UTC 2022 armv7l Android
Device manufacturer:
samsung
Device model:
SM-G7102
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

**Comment by Grimler91** [comment]
Hi, 

Seems like there are at least two patches fixing related issues there, https://github.com/curl/curl/commit/f5c616930b5cf148b1b2632da4f5963ff48bdf88 and https://github.com/curl/curl/commit/0cdde0fdfbeb8c35420f6d03fa4b77ed73497694 and I guess you want both?

Best would be to get them through a curl release rather than backporting (especially since curl is such a fundamental package), maybe there will be a minor release to fix the issue..

**Comment by Vanillma** [comment]
> Hi,
> 
> Seems like there are at least two patches fixing related issues there, [curl/curl@f5c6169](https://github.com/curl/curl/commit/f5c616930b5cf148b1b2632da4f5963ff48bdf88) and [curl/curl@0cdde0f](https://github.com/curl/curl/commit/0cdde0fdfbeb8c35420f6d03fa4b77ed73497694) and I guess you want both?
> 
> Best would be to get them through a curl release rather than backporting (especially since curl is such a fundamental package), maybe there will be a minor release to fix the issue..

I don't know the exact differences between those two patches.

But yes, I agree that a new minor release would be the best approach, and that was my goal in reporting this bug.

Especially since the Termux repository only maintains the latest package versions, there's no way to install older ones!

**Thank you for your quick response :)**
