### ISSUE TITLE
[Bug]: subprocess-exited-with-error

### ISSUE THREAD

**Issue by vinayakpawar94** [termux/termux-packages#22259]
### Problem description

I am reaching out to seek assistance regarding an issue I’ve been facing with installing Python libraries on Termux. Every attempt to install packages via pip ends in a subprocess-exited-with-error message. Despite trying several troubleshooting methods, including installing essential build dependencies (cmake, clang, make, etc.), updating Termux, and adjusting pip installation flags, the error persists.

Here is a summary of my setup and the methods I have tried:
Error Message: subprocess-exited-with-error (occurs with various libraries like numpy and others)

### What steps will reproduce the bug?

roubleshooting Steps Tried:
Updated all Termux packages (pkg update && pkg upgrade)
Installed build-essential, cmake, clang, and other necessary build tools
Tried pip installation with --no-binary :all: and --no-build-isolation flags

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=17192
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root/ root stable
Updatable packages:
All packages up to date
termux-tools version:
1.44.3
Android version:
10
Kernel build information:
Linux localhost 4.9.118-2434300 #1 SMP PREEMPT Thu Jul 21 11:05:27 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N960F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Biswa96** [comment]
Could you provide the full command and error output?

**Comment by vinayakpawar94** [comment]
[TermuxError.txt](https://github.com/user-attachments/files/17787047/TermuxError.txt)

Please find the full transcript

Thanks for the replying

**Comment by vinayakpawar94** [comment]
Yes, I install python by using pkg command.

**Comment by twaik** [comment]
@vinayakpawar94 not python. python-numpy.

**Comment by vinayakpawar94** [comment]
No I will try, Just a moment please

**Comment by vinayakpawar94** [comment]
I feel embarrassed when I notice small, silly mistakes.
Thank you, Thank you so much @twaik @Biswa96

I have a small request for both of you, Please help me whenever I get stuck in coding or in the Termux environment.
Your assistance would be greatly appreciated and beneficial for my future. 😊

**Comment by twaik** [comment]
You can ask for help in #coding channel of our discord.

**Comment by vinayakpawar94** [comment]
Sure, I will definitely join. Thank you man
