### ISSUE TITLE
[Bug]: bootstraps build fails

### ISSUE THREAD

**Issue by YitianDevelop** [termux/termux-packages#22268]
### Problem description

after changing scripts/properties.sh , I run the command ./scripts/build-bootstraps.sh in docker. It seems that the fontconfig build failed.(i update some packages which be downloaded fails.

### What steps will reproduce the bug?

Following the build instructions, I just run the command ./scripts/build-bootstraps.sh in docker

**The build fail log** 
```
checking for struct statfs.f_fstypename... no
checking for struct dirent.d_type... yes
checking The type of len parameter of gperf hash/lookup function... size_t
checking for FREETYPE... no
configure: error: Package requirements (freetype2 >= 21.0.15) were not met:

Package 'freetype2' not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FREETYPE_CFLAGS
and FREETYPE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
[*] Building 'apt' exited with exit code 1
Failed to build package 'apt' for arch 'aarch64' in format 'debian'

```

**My modifications to the project are as follows**

![2024-11-15_16-19](https://github.com/user-attachments/assets/abbfa0f7-7383-4b42-b318-e91c53aae304)
![2024-11-15_16-19_1](https://github.com/user-attachments/assets/ced7ba57-dfc9-4d8c-8478-9e98f5a87296)
![2024-11-15_16-20](https://github.com/user-attachments/assets/5c74aa37-cd7c-40d6-9309-4ce40a261e07)

[whole_log.txt](https://github.com/user-attachments/files/17771746/whole_log.txt)

### What is the expected behavior?

the bootstraps-aarch64.zip should be generated. 

### System information

```shell
I just build it on docker.
```

**Comment by Biswa96** [comment]
I can not reproduce the issue in termux-packages. freetype is being detected by fontconfig correctly.

```
checking for FREETYPE... yes
checking for FT_Get_BDF_Property... yes
checking for FT_Get_PS_Font_Info... yes
checking for FT_Has_PS_Glyph_Names... yes
checking for FT_Get_X11_Font_Format... yes
checking for FT_Done_MM_Var... yes
```

**Comment by YitianDevelop** [comment]
> I can not reproduce the issue in termux-packages. freetype is being detected by fontconfig correctly.
> 
> ```
> checking for FREETYPE... yes
> checking for FT_Get_BDF_Property... yes
> checking for FT_Get_PS_Font_Info... yes
> checking for FT_Has_PS_Glyph_Names... yes
> checking for FT_Get_X11_Font_Format... yes
> checking for FT_Done_MM_Var... yes
> ```

what branch you work on ?

**Comment by Biswa96** [comment]
master branch of https://github.com/termux/termux-packages repository.

**Comment by YitianDevelop** [comment]
Thanks for the reply, apt build successfully after pulling the latest update. Unfortunately ,there is new problem occurs,that is package bzip2 build fails. I check the directory position where bzip2 should be,and I really not found bzip2 in packages directory.

**Comment by TomJo2000** [comment]
`bzip2` is a subpackage of `libbz2`.
https://github.com/termux/termux-packages/blob/master/packages/libbz2/bzip2.subpackage.sh

I assume the dependency resolution is not taking subpackages into account, causing it to not be found.
I'll have to do some local testing on that.

**Comment by YitianDevelop** [comment]
> `bzip2` is a subpackage of `libbz2`. https://github.com/termux/termux-packages/blob/master/packages/libbz2/bzip2.subpackage.sh
> 
> I assume the dependency resolution is not taking subpackages into account, causing it to not be found. I'll have to do some local testing on that.

I removed this bzip2 for now and I seem to have found a new issue with the build-bootstraps.sh script.
![2024-11-15_20-34](https://github.com/user-attachments/assets/f0b7b6bb-804a-4e22-a2d2-5e8c9fa24fb0)

**Comment by TomJo2000** [comment]
Please try again with the latest commits from the master branch applied.
apollo just pushed some fixes potentially related to this issue.
https://github.com/termux/termux-packages/compare/c090dc6a0cab...6fc9e1345855
