### ISSUE TITLE
How to export LXDE to Xserver XSDL using termux-fedora?

### ISSUE THREAD

**Issue by Root-voidX** [termux/termux-packages#2226]
I tried to type in 
`export Display=:0 startlxde &`
but lxde doesnt start up?

**Comment by tomty89** [comment]
`DISPLAY` but not `Display`?
Also it's either `export DISPLAY=:0; startlxde` or `DISPLAY=:0 startlxde`.

**Comment by Root-voidX** [comment]
@tomty89 yes thank you, display is all capital. But still sometimes the command works and other time it doesn't. Anyway are there other x11 apps that offer hardware acceleration? Glxgears wont run on xsdl.

**Comment by sdrausty** [comment]
@Root-voidX @abicorios had a similar https://github.com/sdrausty/TermuxArch/issues/27 issue with X.  How to use Xorg in TermuxArch? *Hopefully you will find this information useful.*

**Comment by Root-voidX** [comment]
Anyone know how I can enable RGB? Glxgears fail in xsdl. I have installed all the xorg files and mesa files
