### ISSUE TITLE
[Bug]: Building fontconfig fails (whether building bootstrap or building fontconfig separately

### ISSUE THREAD

**Issue by YitianDevelop** [termux/termux-packages#22267]
### Problem description

Following the build instructions,I want to integrate termux into my application.

**This is the build output**

0b060d5037ab% ./scripts/build-bootstraps.sh             

[*] Building 'apt'...
termux - building apt for arch aarch64...
Building dependency libandroid-support if necessary...
libandroid-support@28-3 built - skipping (rm /data/data/.built-packages/libandroid-support to force rebuild)
Building dependency libc++ if necessary...
libc++@25b built - skipping (rm /data/data/.built-packages/libc++ to force rebuild)
Building dependency libgmp if necessary...
libgmp@6.2.1-2 built - skipping (rm /data/data/.built-packages/libgmp to force rebuild)
Building dependency libiconv if necessary...
libiconv@1.17 built - skipping (rm /data/data/.built-packages/libiconv to force rebuild)
Building dependency coreutils if necessary...
coreutils@9.1-2 built - skipping (rm /data/data/.built-packages/coreutils to force rebuild)
Building dependency liblzma if necessary...
liblzma@5.4.1 built - skipping (rm /data/data/.built-packages/liblzma to force rebuild)
Building dependency zlib if necessary...
zlib@1.3.1 built - skipping (rm /data/data/.built-packages/zlib to force rebuild)
Building dependency libxml2 if necessary...
libxml2@2.10.3 built - skipping (rm /data/data/.built-packages/libxml2 to force rebuild)
Building dependency docbook-xml if necessary...
docbook-xml@4.5-4 built - skipping (rm /data/data/.built-packages/docbook-xml to force rebuild)
Building dependency zstd if necessary...
zstd@1.5.2-2 built - skipping (rm /data/data/.built-packages/zstd to force rebuild)
Building dependency binutils-libs if necessary...
binutils-libs@2.40 built - skipping (rm /data/data/.built-packages/binutils-libs to force rebuild)
Building dependency libgpg-error if necessary...
libgpg-error@1.46 built - skipping (rm /data/data/.built-packages/libgpg-error to force rebuild)
Building dependency libgcrypt if necessary...
libgcrypt@1.10.1-1 built - skipping (rm /data/data/.built-packages/libgcrypt to force rebuild)
Building dependency libxslt if necessary...
libxslt@1.1.37 built - skipping (rm /data/data/.built-packages/libxslt to force rebuild)
Building dependency docbook-xsl if necessary...
docbook-xsl@1.79.2-1 built - skipping (rm /data/data/.built-packages/docbook-xsl to force rebuild)
Building dependency libbz2 if necessary...
libbz2@1.0.8-6 built - skipping (rm /data/data/.built-packages/libbz2 to force rebuild)
Building dependency ncurses if necessary...
ncurses@6.4-1 built - skipping (rm /data/data/.built-packages/ncurses to force rebuild)
Building dependency libedit if necessary...
libedit@20221030-3.1-0 built - skipping (rm /data/data/.built-packages/libedit to force rebuild)
Building dependency libffi if necessary...
libffi@3.4.4 built - skipping (rm /data/data/.built-packages/libffi to force rebuild)
Building dependency ndk-sysroot if necessary...
ndk-sysroot@25b-3 built - skipping (rm /data/data/.built-packages/ndk-sysroot to force rebuild)
Building dependency readline if necessary...
readline@8.2.1 built - skipping (rm /data/data/.built-packages/readline to force rebuild)
Building dependency gdbm if necessary...
gdbm@1.23 built - skipping (rm /data/data/.built-packages/gdbm to force rebuild)
Building dependency libandroid-posix-semaphore if necessary...
libandroid-posix-semaphore@0.1-3 built - skipping (rm /data/data/.built-packages/libandroid-posix-semaphore to force rebuild)
Building dependency ca-certificates if necessary...
ca-certificates@1:2023.01.10 built - skipping (rm /data/data/.built-packages/ca-certificates to force rebuild)
Building dependency openssl if necessary...
openssl@1:3.0.7 built - skipping (rm /data/data/.built-packages/openssl to force rebuild)
Building dependency libcrypt if necessary...
libcrypt@0.2-5 built - skipping (rm /data/data/.built-packages/libcrypt to force rebuild)
Building dependency libexpat if necessary...
libexpat@2.5.0 built - skipping (rm /data/data/.built-packages/libexpat to force rebuild)
Building dependency libsqlite if necessary...
libsqlite@3.40.1 built - skipping (rm /data/data/.built-packages/libsqlite to force rebuild)
Building dependency libpng if necessary...
libpng@1.6.39 built - skipping (rm /data/data/.built-packages/libpng to force rebuild)
Building dependency freetype if necessary...
freetype@2.12.1 built - skipping (rm /data/data/.built-packages/freetype to force rebuild)
Building dependency libcap-ng if necessary...
libcap-ng@2:0.8.3 built - skipping (rm /data/data/.built-packages/libcap-ng to force rebuild)
Building dependency util-linux if necessary...
util-linux@2.38.1-1 built - skipping (rm /data/data/.built-packages/util-linux to force rebuild)
Building dependency ttf-dejavu if necessary...
ttf-dejavu@2.37-8 built - skipping (rm /data/data/.built-packages/ttf-dejavu to force rebuild)
Building dependency fontconfig if necessary...
termux - building fontconfig for arch aarch64...
Applying patch: fcatomic.c.patch
configure: WARNING: unrecognized options: --disable-rpath-hack
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for aarch64-linux-android-strip... llvm-strip
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for aarch64-linux-android-gcc... aarch64-linux-android-clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether aarch64-linux-android-clang accepts -g... yes
checking for aarch64-linux-android-clang option to enable C11 features... none needed
checking whether aarch64-linux-android-clang understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of aarch64-linux-android-clang... none
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking for sys/param.h... yes
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking pkg-config is at least version 0.9.0... yes
checking for a Python interpreter with version >= 3... python
checking for python... /usr/bin/python
checking for python version... 3.12
checking for python platform... linux
checking for GNU default python prefix... ${prefix}
checking for GNU default python exec_prefix... ${exec_prefix}
checking for python script directory (pythondir)... ${PYTHON_PREFIX}/local/lib/python3.12/dist-packages
checking for python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/local/lib/python3.12/dist-packages
checking for RM macro... rm -f
checking build system type... x86_64-pc-linux-gnu
checking host system type... aarch64-unknown-linux-android
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by aarch64-linux-android-clang... ld.lld
checking if the linker (ld.lld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... llvm-nm
checking the name lister (llvm-nm) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to aarch64-unknown-linux-android format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for ld.lld option to reload object files... -r
checking for aarch64-linux-android-file... no
checking for file... file
configure: WARNING: using cross tools not prefixed with host triplet
checking for aarch64-linux-android-objdump... llvm-objdump
checking how to recognize dependent libraries... pass_all
checking for aarch64-linux-android-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for aarch64-linux-android-ar... llvm-ar
checking for archiver @FILE support... @
checking for aarch64-linux-android-strip... (cached) llvm-strip
checking for aarch64-linux-android-ranlib... llvm-ranlib
checking command to parse llvm-nm output from aarch64-linux-android-clang object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for aarch64-linux-android-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if aarch64-linux-android-clang supports -fno-rtti -fno-exceptions... yes
checking for aarch64-linux-android-clang option to produce PIC... -fPIC -DPIC
checking if aarch64-linux-android-clang PIC flag -fPIC -DPIC works... yes
checking if aarch64-linux-android-clang static flag -static works... yes
checking if aarch64-linux-android-clang supports -c -o file.o... yes
checking if aarch64-linux-android-clang supports -c -o file.o... (cached) yes
checking whether the aarch64-linux-android-clang linker (ld.lld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... Android linker
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether NLS is requested... no
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by aarch64-linux-android-clang... ld.lld
checking if the linker (ld.lld) is GNU ld... yes
checking for shared library run path origin... done
checking how to run the C preprocessor... aarch64-linux-android-cpp
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking whether to use NLS... no
checking for aarch64-linux-android-clang options needed to detect all undeclared functions... -fno-builtin
checking whether __SUNPRO_C is declared... no
checking for build system executable suffix... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for egrep... (cached) /usr/bin/grep -E
checking for dirent.h... yes
checking for fcntl.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/statvfs.h... yes
checking for sys/vfs.h... yes
checking for sys/statfs.h... yes
checking for sys/param.h... (cached) yes
checking for sys/mount.h... yes
checking for stdint types... stdint.h (shortcircuit)
make use of stdint.h in src/fcstdint.h (assuming C99 compatible system)
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for flexible array members... yes
checking for pid_t... yes
checking for vprintf... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for link... yes
checking for mkstemp... yes
checking for mkostemp... yes
checking for _mktemp_s... no
checking for mkdtemp... yes
checking for getopt... yes
checking for getopt_long... yes
checking for getprogname... yes
checking for getexecname... no
checking for rand... yes
checking for random... yes
checking for lrand48... yes
checking for random_r... no
checking for rand_r... yes
checking for readlink... yes
checking for fstatvfs... yes
checking for fstatfs... yes
checking for lstat... yes
checking for strerror... yes
checking for strerror_r... yes
checking for posix_fadvise in fcntl.h... fcntl.h
checking for struct stat.st_mtim... yes
checking for struct statvfs.f_basetype... no
checking for struct statvfs.f_fstypename... no
checking for struct statfs.f_flags... yes
checking for struct statfs.f_fstypename... no
checking for struct dirent.d_type... yes
checking The type of len parameter of gperf hash/lookup function... size_t
checking for FREETYPE... no
configure: error: Package requirements (freetype2 >= 21.0.15) were not met:

Package 'freetype2' not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FREETYPE_CFLAGS
and FREETYPE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
[*] Building 'apt' exited with exit code 1
Failed to build package 'apt' for arch 'aarch64' in format 'debian'

### What steps will reproduce the bug?

**after changing scripts/properties.sh , I run the command ./scripts/build-bootstraps.sh in docker. It seems that the fontconfig build failed.(i update some packages which be downloaded fails.**

**My modifications to the project are as follows(git diff)**

diff --git a/packages/ncurses/build.sh b/packages/ncurses/build.sh
index 03fc7f41ec..509aaf72e2 100644
--- a/packages/ncurses/build.sh
+++ b/packages/ncurses/build.sh
@@ -3,7 +3,7 @@ TERMUX_PKG_DESCRIPTION="Library for text-based user interfaces in a terminal-ind
 TERMUX_PKG_LICENSE="MIT"
 TERMUX_PKG_MAINTAINER="@termux"
 TERMUX_PKG_VERSION=(6.4
-		    9.30
+		    9.31
 		    15
 		    0.26.5
 		    0.9.0)
@@ -14,7 +14,7 @@ TERMUX_PKG_SRCURL=(https://ftp.gnu.org/gnu/ncurses/ncurses-${TERMUX_PKG_VERSION[
 		   https://github.com/kovidgoyal/kitty/archive/v${TERMUX_PKG_VERSION[3]}.tar.gz
 		   https://github.com/alacritty/alacritty/archive/refs/tags/v${TERMUX_PKG_VERSION[4]}.tar.gz)
 TERMUX_PKG_SHA256=(6931283d9ac87c5073f30b6290c4c75f21632bb4fc3603ac8100812bed248159
-		   fe1c93d12f385876457a989fc3ae05c0915d2692efc59289d0f70fabe5b44d2d
+		   aaa13fcbc149fe0f3f391f933279580f74a96fd312d6ed06b8ff03c2d46672e8
 		   3ae9ebef28aad081c6c11351f086776e2fd9547563b2f900732b41c376bec05a
 		   7a1b444f1cc10e16ee0f20a804c0f80b52417eeabf60d9f25e37ef192503ba26
 		   6d3aaac9e0477f903563b6fb26e089118407cdbfe952a1e2ffbf4e971b7062b3)
diff --git a/packages/zlib/build.sh b/packages/zlib/build.sh
index 38d5ab23bb..687f05e1c8 100644
--- a/packages/zlib/build.sh
+++ b/packages/zlib/build.sh
@@ -2,9 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://www.zlib.net/
 TERMUX_PKG_DESCRIPTION="Compression library implementing the deflate compression method found in gzip and PKZIP"
 TERMUX_PKG_LICENSE="ZLIB"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION=1.2.13
+TERMUX_PKG_VERSION=1.3.1
 TERMUX_PKG_SRCURL=https://www.zlib.net/zlib-$TERMUX_PKG_VERSION.tar.xz
-TERMUX_PKG_SHA256=d14c38e313afc35a9a8760dadf26042f51ea0f5d154b0630a31da0540107fb98
+TERMUX_PKG_SHA256=38ef96b8dfe510d42707d9c781877914792541133e1870841463bfa73f883e32
 TERMUX_PKG_BREAKS="ndk-sysroot (<< 19b-3), zlib-dev"
 TERMUX_PKG_REPLACES="ndk-sysroot (<< 19b-3), zlib-dev"
 
diff --git a/scripts/properties.sh b/scripts/properties.sh
index 20417256eb..cb6fa673bc 100644
--- a/scripts/properties.sh
+++ b/scripts/properties.sh
@@ -30,7 +30,7 @@ else
 fi
 
 # Termux packages configuration.
-TERMUX_APP_PACKAGE="com.termux"
+TERMUX_APP_PACKAGE="me.yan.termux"
 TERMUX_BASE_DIR="/data/data/${TERMUX_APP_PACKAGE}/files"
 TERMUX_CACHE_DIR="/data/data/${TERMUX_APP_PACKAGE}/cache"
 TERMUX_ANDROID_HOME="${TERMUX_BASE_DIR}/home"
@@ -40,7 +40,7 @@ TERMUX_PREFIX="${TERMUX_BASE_DIR}/usr"
 # Package name for the packages hosted on the repo.
 # This must only equal TERMUX_APP_PACKAGE if using custom repo that
 # has packages that were built with same package name.
-TERMUX_REPO_PACKAGE="com.termux"
+TERMUX_REPO_PACKAGE="me.yan.termux"
 
 # Termux repo urls.
 TERMUX_REPO_URL=(

### What is the expected behavior?

the bootstraps-*.zip should be generated.

### System information

```shell
i build it on docker.
```

**Comment by TomJo2000** [comment]
Based on the `git diff` of the `ncurses` build script, your fork of termux-packages seems to be at least 3 weeks out of date.

The `ncurses` build script was last modified in [`26b3cca`](https://github.com/termux/termux-packages/blob/26b3cca10ad11eabcc95e2a54c96af5a2fa7bde0/packages/ncurses/build.sh).

Aside from that I cannot replicate your build error with `fontconfig` at all.

**Comment by YitianDevelop** [comment]
> Based on the `git diff` of the `ncurses` build script, your fork of termux-packages seems to be at least 3 weeks out of date.
> 
> The `ncurses` build script was last modified in [`26b3cca`](https://github.com/termux/termux-packages/blob/26b3cca10ad11eabcc95e2a54c96af5a2fa7bde0/packages/ncurses/build.sh).
> 
> Aside from that I cannot replicate your build error with `fontconfig` at all.

Thanks for the reply, the build is complete after pulling the latest update.
