### ISSUE TITLE
Termux Fedora Proot and package failure 

### ISSUE THREAD

**Issue by Root-voidX** [termux/termux-packages#2228]
Sorry if I have been a bothersome but this seems to be the only git page which has been active and helpfull to me. I dont know if this is termux, proot or a fedora only problem, but most of my packages fail to install. Like for example libstdc++ throws this error, its the same for other packages too. 

```
Error unpacking rpm package libstdc++-7.3.1-2.fc26.aarch64
Error unpacking rpm package libstdc++-7.3.1-2.fc26.aarch64
error: unpacking of archive failed on file /usr/share/gcc-7/python/libstdcxx/__init__.pyo;5a9f79a9: cpio: open
libstdc++-7.3.1-2.fc26.aarch64 was supposed to be installed but is not!
```

Is this a proot issue?

**Comment by Atavic** [comment]
By looking around, a common answer is:

Seems like Fedora Core RPM Db has been corrupted.

Then [here](https://ask.fedoraproject.org/en/question/105642/f25-chkconfig-upgrade-fails/?answer=108593#post-id-108593) a similar problem, due to local init scripts in /etc/init.d, has been solved.

Hope it helps.

**Comment by duncenbn** [comment]
`fix `

**Comment by Root-voidX** [comment]
I updates proot and it hasnt fixed the issue @fornwall. 

Example when installing libstdc++ 

```
dnf install libstdc++
Last metadata expiration check: 0:00:23 ago on Sun 11 Mar 2018 05:26:52 AM UTC.
Dependencies resolved.
========================================================================
 Package         Arch          Version              Repository     Size
========================================================================
Installing:
 libstdc++       aarch64       7.3.1-2.fc26         updates       454 k

Transaction Summary
========================================================================
Install  1 Package

Total download size: 454 k
Installed size: 1.9 M
Is this ok [y/N]: y
Downloading Packages:
libstdc++-7.3.1-2.fc26.aarch64.rpm      580 kB/s | 454 kB     00:00
------------------------------------------------------------------------
Total                                   256 kB/s | 454 kB     00:01
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                1/1
  Installing       : libstdc++-7.3.1-2.fc26.aarch64                 1/1
Error unpacking rpm package libstdc++-7.3.1-2.fc26.aarch64
Error unpacking rpm package libstdc++-7.3.1-2.fc26.aarch64
```

**Comment by duncenbn** [comment]
`git clone` and `fix usage`

**Comment by Root-voidX** [comment]
@duncenbn

Git fails install,

**Comment by duncenbn** [comment]
Hi! You have to try this Wirex app, it's the best crypto payment centre
with zero fees! Use this link to get cards for free. Thank me later 😉
https://links.wirexapp.com/MpmB/4bTIQcutbK?action=affiliate-register&code=8HOzTgx2R0uPRVHP4J4hmg

**Comment by Root-voidX** [comment]
@fornwall The issue is not fixed, why did you close it?

**Comment by Grimler91** [comment]
@Root-voidX This repo is for packages available for termux. Termux-fedora isn't available from the official repo so this issue is rather off-topic. You might have more luck if you open the issue at the termux-fedora github page.
