### ISSUE TITLE
packages git  curl  wget

### ISSUE THREAD

**Issue by alaradm2025** [termux/termux-packages#22294]
### Why is it worth to add this package?

نظام إدارة إصدارات موزع مفتوح المصدر يُستخدم لتتبع التغييرات في التعليمات البرمجية ومشاركة المشاريع بين المطورين.

### Home page URL

https://packages.termux.dev/apt/termux-main/dists/stable/main/

### Source code URL

Git: https://github.com/git/git  Curl: https://github.com/curl/curl  Wget: https://git.savannah.gnu.org/cgit/wget.git

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

لقد قمت بتثبيت بعض الادوات ومن بعد هذا التثبيت يطلب مني المفتاح وبشكل عام ان بعض الحزم ادخلت من غير قبلي لتلاعب الاطفال بحهازي مما اداء الى الخلل

**Comment by TomJo2000** [comment]
All three of those are already packaged and available on the repos.
