### ISSUE TITLE
Bash doesn't work on N developer preview

### ISSUE THREAD

**Issue by michalbednarski** [termux/termux-packages#223]
When running `bash` in N developer preview it fails to link and start.

```
$ bash
CANNOT LINK EXECUTABLE "bash": cannot locate symbol "__moddi3" referenced by "bash"...
Aborted
$
```

(Above transcript was obtained after changing shell to `dash` through failsafe mode, normally this happens immediately after starting Termux and no prompt is available)

This appears to be caused by change described under [NDK Apps Linking to Platform Libraries](https://developer.android.com/preview/behavior-changes.html#ndk)

(Originally I mentioned this issue in #222)

**Comment by fornwall** [comment]
I think this will be fixed by rebuilding bash using the upcoming r12 release of the Android NDK.

**Comment by fornwall** [comment]
I rebuilt both `bash` and `openssh` (which suffered from the same `__moddi3` problem with [the ndk r12 beta 1](https://github.com/android-ndk/ndk/wiki#user-content-current-beta-release) and verified that it fixes the problem. The packages are pushed to the apt repo so exploring the Android N preview under the emulator should now work better.

I'm holding off with a more massive rebuild until a stable NDK r12 release, so there may be more similar problems with packages that will have to wait.
