### ISSUE TITLE
[Bug]: subprocess-exited-with-error

### ISSUE THREAD

**Issue by vinayakpawar94** [termux/termux-packages#22340]
### Problem description

I'm getting "subprocess-exited-with-error" while installing the pandas library. Using pip install pandas command
and also I'm getting an "Unable to locate package python-pandas" error while using pkg install python-pandas

### What steps will reproduce the bug?

I do all updates such as pip, python, cake, ninja...

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=17192
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root/ root stable
Updatable packages:
All packages up to date
termux-tools version:
1.44.3
Android version:
10
Kernel build information:
Linux localhost 4.9.118-2434300 #1 SMP PREEMPT Thu Jul 21 11:05:27 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N960F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by twaik** [comment]
Post the full log please. `subprocess-exited-with-error` is not informative enough to fix it.

**Comment by vinayakpawar94** [comment]
$ pip install pandas
Collecting pandas
  Using cached pandas-2.2.3.tar.gz (4.4 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
 
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [98 lines of output]
      Collecting meson-python==0.13.1                         Using cached meson_python-0.13.1-py3-none-any.whl.metadata (4.1 kB)
      Collecting meson==1.2.1
        Using cached meson-1.2.1-py3-none-any.whl.metadata (1.7 kB)
      Collecting wheel
        Using cached wheel-0.45.0-py3-none-any.whl.metadata (2.3 kB)
      Collecting Cython~=3.0.5                                Using cached Cython-3.0.11-py2.py3-none-any.whl.metadata (3.2 kB)
      Collecting numpy>=2.0
        Using cached numpy-2.1.3.tar.gz (20.2 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'error'
        error: subprocess-exited-with-error
 
        × pip subprocess to install backend dependencies did not run successfully.
        │ exit code: 1
        ╰─> [67 lines of output]
            Collecting ninja>=1.8.2
Using cached ninja-[1.11.1.1](http://1.11.1.1/).tar.gz (132 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting patchelf>=0.11.0
              Using cached patchelf-0.17.2.1.tar.gz (167 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Building wheels for collected packages: ninja, patchelf
              Building wheel for ninja (pyproject.toml): started
              Building wheel for ninja (pyproject.toml): finished with status 'error'
              error: subprocess-exited-with-error
 
              × Building wheel for ninja (pyproject.toml) did not run successfully.
              │ exit code: 1
              ╰─> [15 lines of output]
/data/data/com.termux/files/usr/tmp/pip-build-env-q7bbp1jb/overlay/lib/python3.12/site-packages/setuptools_scm/[git.py:312](http://git.py:312/): UserWarning: git archive did not support describe output
                    warnings.warn("git archive did not support describe output")
/data/data/com.termux/files/usr/tmp/pip-build-env-q7bbp1jb/overlay/lib/python3.12/site-packages/setuptools_scm/[git.py:331](http://git.py:331/): UserWarning: unprocessed git archival found (no export subst applied)
                    warnings.warn("unprocessed git archival found (no export subst applied)")
                  Traceback (most recent call last):
File "/data/data/com.termux/files/usr/tmp/pip-build-env-q7bbp1jb/overlay/lib/python3.12/site-packages/skbuild/[setuptools_wrap.py](http://setuptools_wrap.py/)", line 639, in setup
                      cmkr = cmaker.CMaker(cmake_executable)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/data/com.termux/files/usr/tmp/pip-build-env-q7bbp1jb/overlay/lib/python3.12/site-packages/skbuild/[cmaker.py](http://cmaker.py/)", line 145, in __init__
                      self.cmake_version = get_cmake_version(self.cmake_executable)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/data/com.termux/files/usr/tmp/pip-build-env-q7bbp1jb/overlay/lib/python3.12/site-packages/skbuild/[cmaker.py](http://cmaker.py/)", line 102, in get_cmake_version
                      raise SKBuildError(msg) from err
 
                  Problem with the CMake installation, aborting build. CMake executable is cmake
                  [end of output]
 
              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed building wheel for ninja
              Building wheel for patchelf (pyproject.toml): started
              Building wheel for patchelf (pyproject.toml): finished with status 'error'
              error: subprocess-exited-with-error
 
              × Building wheel for patchelf (pyproject.toml) did not run successfully.
              │ exit code: 1
              ╰─> [11 lines of output]
                  Traceback (most recent call last):
File "/data/data/com.termux/files/usr/tmp/pip-build-env-nk6qwdto/overlay/lib/python3.12/site-packages/skbuild/[setuptools_wrap.py](http://setuptools_wrap.py/)", line 639, in setup
                      cmkr = cmaker.CMaker(cmake_executable)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/data/com.termux/files/usr/tmp/pip-build-env-nk6qwdto/overlay/lib/python3.12/site-packages/skbuild/[cmaker.py](http://cmaker.py/)", line 145, in __init__
                      self.cmake_version = get_cmake_version(self.cmake_executable)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/data/com.termux/files/usr/tmp/pip-build-env-nk6qwdto/overlay/lib/python3.12/site-packages/skbuild/[cmaker.py](http://cmaker.py/)", line 102, in get_cmake_version
                      raise SKBuildError(msg) from err
 
                  Problem with the CMake installation, aborting build. CMake executable is cmake
                  [end of output]
 
              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed building wheel for patchelf
            Failed to build ninja patchelf
            ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ninja, patchelf)
            [end of output]
 
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
 
      × pip subprocess to install backend dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
 
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
 
× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
 
note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by twaik** [comment]
Use `pkg install python-pandas`.

**Comment by vinayakpawar94** [comment]
$ pkg install python-pandas
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Checking availability of current mirror:
[*] https://packages-cf.termux.dev/apt/termux-main/: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python-pandas

**Comment by vinayakpawar94** [comment]
I did the same termux-change-repo and update. but still same error shows 
~ $ pkg install python-pandas
Checking availability of current mirror:
[*] https://mirrors.medzik.dev/termux/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python-pandas

**Comment by twaik** [comment]
Oh, the package was disabled two years ago because it can be installed with pip w/ some trivial workaround. https://github.com/termux/termux-packages/issues/13785

**Comment by twaik** [comment]
`pkg i tur-repo; pkg up; pkg i python-pandas`.

**Comment by vinayakpawar94** [comment]
Thanks for the help @twaik 
I'd started a new journey in data science. 
I want to install every library Numpy, Pandas, matplotlib, seaborn, SciPy, Scikit-learn, TensorFlow, PyTorch, Jupyter Notebook, Beautiful Soup, XGBoost... etc.

But when I'm trying to install a specific library will get "subprocess-exited-with-error" and "Unable to locate package python-<Package_name>". Every time I don't want to raise the issue here. 
Please suggest what to do. 
Which documents I prefer, Where I get information regarding error.

**Comment by Biswa96** [comment]
> I'd started a new journey in data science.

Android phone is not appropriate for that.
