### ISSUE TITLE
hostname is missing from net-tools why ?

### ISSUE THREAD

**Issue by lkdevil** [termux/termux-packages#2240]
Why we have not hostname binary in net-tools package ? Actually i am not happy with busybox hostname binary bcz it has very few options.

**Comment by sdrausty** [comment]
@lkdevil are you looking for:
```
$ pkg list-all |grep net

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

inetutils/stable 1.9.4-5 arm
libnettle/stable 3.4 arm
libnettle-dev/stable 3.4 arm
net-tools/stable 1.60.2017.02.21-1 arm
netcat/stable 7.60 arm
netpbm/stable 3094 arm
netpbm-dev/stable 3094 arm
nettle/stable 3.4 arm
```
If you are use `pkg install net-tools`.

**Comment by xeffyr** [comment]
@sdrausty, are you understand question ?

Utility 'hostname' is not found in package `net-tools`:
```
bash-4.4$ dpkg -L net-tools | grep usr/bin
/data/data/com.termux/files/usr/bin
/data/data/com.termux/files/usr/bin/ipmaddr
/data/data/com.termux/files/usr/bin/rarp
/data/data/com.termux/files/usr/bin/route
/data/data/com.termux/files/usr/bin/nameif
/data/data/com.termux/files/usr/bin/iptunnel
/data/data/com.termux/files/usr/bin/ifconfig
/data/data/com.termux/files/usr/bin/plipconfig
/data/data/com.termux/files/usr/bin/slattach
/data/data/com.termux/files/usr/bin/arp
/data/data/com.termux/files/usr/bin/mii-tool
/data/data/com.termux/files/usr/bin/netstat
```

Seems that this tool is disabled in [build.sh](https://github.com/termux/termux-packages/blob/master/packages/net-tools/build.sh#L12):
```
TERMUX_PKG_EXTRA_MAKE_ARGS="BINDIR=$TERMUX_PREFIX/bin SBINDIR=$TERMUX_PREFIX/bin HAVE_HOSTNAME_TOOLS=0"
```

**Comment by lkdevil** [comment]
But why @xeffyr
is hostname affecting termux ?

**Comment by Atavic** [comment]
[/* sethostname() is not available on Android pre android-23 and not allowed anyway. */](https://github.com/termux/termux-packages/blob/d7d48bac73af77638957cfa91795b13c0b1b59b6/packages/busybox/networking-hostname.c.patch)

**Comment by xeffyr** [comment]
Closing as package can't be available with API less than 23.
