### ISSUE TITLE
unable to stat './data/data/com.termux' (which was about to be installed): Permission denied

### ISSUE THREAD

**Issue by Shoukaku07** [termux/termux-packages#22426]
![Screenshot_2024-11-30-12-20-15-71_d5a2645eee30d6db0d7a90f94d524f9a.jpg](https://github.com/user-attachments/assets/f3adecc2-1735-49da-9b49-faeb5b279cdd)

Anyone? can I fix this error?😞
Previously I had changed the package in the termux application and built bootstraps, I found that there were several files in the bootstrap that still used "com.termux" and I changed it to the another package, but when I run it I get this error? how can I fix this?

**Comment by Biswa96** [comment]
You are using fork of termux or termux-packages. Please report the issue to that repository. You can not mix packages with different PREFIX path.

**Comment by Shoukaku07** [comment]
> You are using fork of termux or termux-packages. Please report the issue to that repository. You can not mix packages with different PREFIX path.

Ok thx
