### ISSUE TITLE
[Package]: moar

### ISSUE THREAD

**Issue by mbekkomo** [termux/termux-packages#22424]
### Why is it worth to add this package?

Moar is a pager that supports syntax highlighting, ANSI color codes, incremental search etc.

### Source code URL

https://github.com/walles/moar?tab=readme-ov-file

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
Do we really need another pager?
We have at least 5 available.

- `less`
- `more`
- `most`
- `w3m`
- `lazyread`
- arguably duplicates functionality easily achieved with `vim`, `neovim`, `emacs`, etc.

So what sets `moar` apart?

**Comment by Biswa96** [comment]
> So what sets `moar` apart?

The features are listed in README file https://github.com/walles/moar?tab=readme-ov-file

It sounds like similar as fd vs. find or cat vs. bat.

**Comment by tathastu871** [comment]
less covers all features, for syntax highlighting
https://www.vim.org/scripts/script.php?script_id=1723
less+vim

**Comment by mbekkomo** [comment]
> less covers all features, for syntax highlighting https://www.vim.org/scripts/script.php?script_id=1723 less+vim

That will require user to install `vim`? Which in terms of installation size is much bigger than `more`.

**Comment by TomJo2000** [comment]
It's also Vim.
Which is a very take it or leave it proposition.

I think the comparison to `fd` or `bat` is probably a fair assessment.
A lower friction alternative that is easier to get something nice out of, but limited in some other ways.

**Comment by mbekkomo** [comment]
> Do we really need another pager? We have at least 5 available.
> 
> * `less`
> * `more`
> * `most`
> * `w3m`
> * `lazyread`
> * arguably duplicates functionality easily achieved with `vim`, `neovim`, `emacs`, etc.
> 
> So what sets `moar` apart?

It's pretty much an enhanced `less`, it supports syntax highlighting, you can display ANSI escape code including the terminal hyperlinks, UTF-8 supports.

Although syntax highlighting can be achieved using `vim`, `neovim`, `emacs`, etc. That would require the user to install the runtimes which arguably bigger, while `moar` itself embeds syntax highlighting into it's binary, and Chroma syntax highlighting file is small, so it doesn't take up many spaces.

**Comment by TomJo2000** [comment]
Less supports everything you rattled off, though not all of it by itself.
I've already given this package request my approval.
It's got at least as much merit as `fd`, `bat` and `eza`.
