### ISSUE TITLE
I can't delete a directory... 

### ISSUE THREAD

**Issue by dAtiuy** [termux/termux-packages#2243]
I can't delete a directory. I got this "error"
rm -r Breacher
rm: remove write-protected regular file 'Breacher/.git/objects/9e/5b940e08afab1503b85d0a3c5d0de883413cd2'?
rm: remove write-protected regular file 'Breacher/.git/objects/9e/3bcd0d0c58d2a09573dbee93d8586f679da5c6'?
rm: cannot remove 'Breacher/.git/objects/9e': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/61/dd0fa0e666f6b7b2312af07e109edf4b750369'?
rm: cannot remove 'Breacher/.git/objects/61': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/fb/ec4c0bc7187f110f99184afadd8b4608c53112'?
rm: remove write-protected regular file 'Breacher/.git/objects/fb/9f6a2d6825fb119b49c6631adbb13a2cc209be'?
rm: cannot remove 'Breacher/.git/objects/fb': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/db/3c5a2d7f7aad8774a53153e15b9e93dc2c4cc5'?
rm: remove write-protected regular file 'Breacher/.git/objects/db/858724ac8169655c91312d22009c95fb275186'?
rm: remove write-protected regular file 'Breacher/.git/objects/db/eeb1c750e1c735b8a17411272af7b262cf42fb'?
rm: cannot remove 'Breacher/.git/objects/db': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/1e/7e63fdb4835c868175c6f6b367764bbb429a1e'?
rm: cannot remove 'Breacher/.git/objects/1e': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/af/e001f71d300c4ad3c140f1a80cab04fa84afa5'?
rm: cannot remove 'Breacher/.git/objects/af': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/ba/8b44425f385eaba40e370f7a47d8f83e117dbe'?
rm: cannot remove 'Breacher/.git/objects/ba': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/4c/ce2c1dce82329e812b04640dea9ebddbcb789e'?
rm: cannot remove 'Breacher/.git/objects/4c': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/cd/891102af44469cca136a9c18c82d2f3ee184f9'?
rm: cannot remove 'Breacher/.git/objects/cd': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/d0/c9f7d54c27be606ee2c2ffc6becea1d24b2902'?
rm: cannot remove 'Breacher/.git/objects/d0': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/09/f7287be00a50a4adbdc46403edbc6438fe4888'?
rm: cannot remove 'Breacher/.git/objects/09': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/9c/c0ba55ee12fd8a39add97cc13264c86961af0a'?
rm: cannot remove 'Breacher/.git/objects/9c': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/93/eca85f1d45c989fb4fa8966d4723bb7897bff7'?
rm: cannot remove 'Breacher/.git/objects/93': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/cb/bc9bf02bd4953b94b7bfd37d734f1780041e56'?
rm: cannot remove 'Breacher/.git/objects/cb': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/a4/9f034402b1b913c984afa891860b6625a5215c'?
rm: cannot remove 'Breacher/.git/objects/a4': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/81/53dcbe77fd45d24e46ef319af7f9d6ad429658'?
rm: cannot remove 'Breacher/.git/objects/81': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/68/530941bc6352c78a481290fe0d1ee485ced32c'?
rm: cannot remove 'Breacher/.git/objects/68': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/5b/ff928b23c6879320009eb19adadca2b91910bd'?
rm: cannot remove 'Breacher/.git/objects/5b': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/70/0030174dec7f9945ae887427e30b0566d5afa8'?
rm: cannot remove 'Breacher/.git/objects/70': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/b8/bcb57fc34c890c79307961876d5e4bb26c389e'?
rm: cannot remove 'Breacher/.git/objects/b8': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/e7/f645ee09dc111c20972c8f29d717ec215e6a27'?
rm: cannot remove 'Breacher/.git/objects/e7': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/b9/55b49a4b3457f5d06128b40f9f91d9920332f6'?
rm: cannot remove 'Breacher/.git/objects/b9': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/31/af9b1d960d60efde16978102e5d99e02350e14'?
rm: remove write-protected regular file 'Breacher/.git/objects/31/418470f37fdc84bed1f148187d020e7b13fd2d'?
rm: cannot remove 'Breacher/.git/objects/31': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/30/a8fbebe987ab70047b23c9aa416d9493954382'?
rm: cannot remove 'Breacher/.git/objects/30': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/a3/ba1ab0f2d80d45675454b961f8e64f364a892e'?
rm: cannot remove 'Breacher/.git/objects/a3': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/2b/16c89bd4d57cd113bce2f3a37cfffeafceaa7f'?
rm: cannot remove 'Breacher/.git/objects/2b': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/4a/10236da99ed0827a4ea504f9a33f41821cdf7a'?
rm: cannot remove 'Breacher/.git/objects/4a': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/c6/c626799f7fe3e90ac1358e6357c98701958da6'?
rm: cannot remove 'Breacher/.git/objects/c6': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/c4/74b5afd86b3f4b62bae997ec136a76bdd7fb69'?
rm: cannot remove 'Breacher/.git/objects/c4': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/9b/f621af3293db366f09e8ec60c77d48b4f2e454'?
rm: cannot remove 'Breacher/.git/objects/9b': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/6a/d85d1e21d21a80bffe6e8a98d2b02f717a63f0'?
rm: cannot remove 'Breacher/.git/objects/6a': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/c9/de2adf2e6762ff6a285f5e9510d08860a09418'?
rm: cannot remove 'Breacher/.git/objects/c9': Directory not empty
rm: remove write-protected regular file 'Breacher/.git/objects/6c/4d95b5d171b3dc6d0b4f8ccfa9076aa

**Comment by Grimler91** [comment]
Use `rm -rf`.

**Comment by dAtiuy** [comment]
Thanks

**Comment by FaniHacker** [comment]
😡

**Comment by tranduclinh197** [comment]
thank ^^

**Comment by Leah1802** [comment]
rm: refusing to remove '.' or '..' directory: skipping '.'

**Comment by kcubeterm** [comment]
rm doesn't remove parents directory, that's features of rm , it's not issue, if you want to delete parent directory, then go to there and then remove it, rm  skip . and .. directory

**Comment by Leah1802** [comment]
thanks

**Comment by LuCiFaR-MaXxX** [comment]
![Screenshot_20200602-024832](https://user-images.githubusercontent.com/65081649/83453186-dafa7080-a47b-11ea-8f81-c668ba123076.png)

**Comment by LuCiFaR-MaXxX** [comment]
![Screenshot_20200602-025158](https://user-images.githubusercontent.com/65081649/83453337-21e86600-a47c-11ea-8e0f-429caaf1cdbd.png)

**Comment by LuCiFaR-MaXxX** [comment]
I want to remove TBomb.
but, it's a directory.
so, I can't remove it.
plz, help.

**Comment by xeffyr** [comment]
If "permission denied" is shown for your directory, then you need to delete it using root.
```
tsu
rm -rf ./path/to/your/directory
```

**Comment by xeffyr** [comment]
I'm locking that issue as enough solutions is shown here.
