### ISSUE TITLE
[Bug]: The "imagemagick" package is broken.

### ISSUE THREAD

**Issue by snooppr** [termux/termux-packages#22445]
### Problem description

Updated The "imagemagick v7.1.1.41" package to the latest version and it stopped working.

### What steps will reproduce the bug?

$ pkg install imagemagick
$ convert

>CANNOT LINK EXECUTABLE "convert": library "libOpenEXR-3_2.so" not found

### System information

```shell
Termux: 0.119.0-beta.1 F-Droid, armeabi-v7a
```

**Comment by snooppr** [comment]
imagemagick version is specified in the post. openexr version was 3.1.9 updated it to 3.2.4. Also reinstalled imagemagick

$ convert
>CANNOT LINK EXECUTABLE "convert": cannot locate symbol "heif_image_handle_get_context" referenced by "/data/data/com.termux/files/usr/lib/libMagickCore-7.Q16HDRI.so"...

**Comment by Biswa96** [comment]
I can not reproduce the issue. Please make sure all packages are updated.

**Comment by licy183** [comment]
Please fill `System information` with the output of `termux-info`. This is necessary for maintainers to find the cause of issues. It shows your system version, the mirror you're subscribing, the packages which are needed to be updated and so on.

**Comment by snooppr** [comment]
Upgrading all environments solved the problem.

**Comment by ghetto-philosoper** [comment]
Pls let me procced
