### ISSUE TITLE
[Bug]: "libssl.so.3" not found after updating rust-1.83.0-1

### ISSUE THREAD

**Issue by dilongx** [termux/termux-packages#22468]
### Problem description

`CANNOT LINK EXECUTABLE "cargo": library "libssl.so.3" not found: needed by main executable`

### What steps will reproduce the bug?

Run cargo or rustc after updating the rust-1.83.0-1 installation.

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=pacman
TERMUX_APP_PID=10684
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=pacman
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Usage = All
Server = https://service.termux-pacman.dev/main/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/main/aarch64
[x11]
Usage = All
Server = https://service.termux-pacman.dev/x11/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/x11/aarch64
[root]
Usage = All
Server = https://service.termux-pacman.dev/root/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/root/aarch64
[tur]
Usage = All
Server = https://service.termux-pacman.dev/tur/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur/aarch64
[tur-continuous]
Usage = All
Server = https://service.termux-pacman.dev/tur-continuous/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur-continuous/aarch64
[tur-multilib]
Usage = All
Server = https://service.termux-pacman.dev/tur-multilib/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur-multilib/aarch64
[gpkg]
Usage = All
Server = https://service.termux-pacman.dev/gpkg/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/gpkg/aarch64
Updatable packages:
All packages up to date
termux-tools version:
1.44.1
Android version:
13
Kernel build information:
Linux localhost 5.10.198-android12-9-g82f21bd5762e-dirty #1 SMP PREEMPT Wed Jun 26 08:45:25 UTC 2024 aarch64 Android
Device manufacturer:
vivo
Device model:
V2279A
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

**Comment by dilongx** [comment]
I'm sorry. I seem to have sent it to the wrong repository.

[termux-packages/issues/104](https://github.com/termux-pacman/termux-packages/issues/104)

**Comment by TomJo2000** [comment]
This is the still the right repository.
`libssl.so.3` is part of the `openssl` package.
Which is a dependency for the `rust` package.
So it should be installed automatically.
https://github.com/termux/termux-packages/blob/0cefc7065d010f47223917d3bb2a794d277b51fb/packages/rust/build.sh#L12

It's also crucial for both `apt` and `pacman` to be able to operate.
So please make sure you have it installed.

**Comment by dilongx** [comment]
> This is the still the right repository. `libssl.so.3` is part of the `openssl` package. Which is a dependency for the `rust` package. So it should be installed automatically.
> 
> https://github.com/termux/termux-packages/blob/0cefc7065d010f47223917d3bb2a794d277b51fb/packages/rust/build.sh#L12
> 
> It's also crucial for both `apt` and `pacman` to be able to operate. So please make sure you have it installed.


openssl and other dependencies are installed, also tried to reinstall rust, openssl, can not solve the problem
![Screenshot_20241207_074039](https://github.com/user-attachments/assets/bb04873a-b05f-4879-b8f8-c2db148f5d89)

**Comment by TomJo2000** [comment]
I can also replicate this issue on `apt`.

**Comment by TomJo2000** [comment]
CC: @truboxl

**Comment by truboxl** [comment]
Set `LD_LIBRARY_PATH=$PREFIX/lib` for the time being
