### ISSUE TITLE
[Bug]: LXQT via vncserver

### ISSUE THREAD

**Issue by hanzelpeter** [termux/termux-packages#22466]
### Problem description

I have installed termux and LXQT succesfully on my new mobile. Now I want to access desktop via real vncviewer.
I have installed tigervnc server and modified vnc xstartup to startlxqt. I can connect succesfully but Window manager is not started and shows dbus error to connect.

### What steps will reproduce the bug?

Install LXQT.
Install tigervnc server
Modify vnc xstartup to startlxqt
Connect to server via real vnc mobile application.

### What is the expected behavior?

LXQT should be started and working.
Dbus error from xorg log is:
lxqt-session: dbus-updatee-activation-environment failed: dbus-update-activation-environment: error: unable to connect to D-Bus: Failed to connect to socket /data/data/com.termux/files/usr/tmp/dbus-JOvjHWosQd: No such file or directory

### System information

```shell
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=googleplay.2024.10.30
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# x11-repo (sources.list.d/x11.list)
deb https://x11-packages.termux.net/ x11 main
Updatable packages:
command-not-found/stable 2.4.0-53 aarch64 [upgradable from: 2.4.0-48]
curl/stable 8.11.0-1 aarch64 [upgradable from: 8.10.1-2]
debianutils/stable 5.21 aarch64 [upgradable from: 5.20]
inetutils/stable 2.5 aarch64 [upgradable from: 2.4-2]
libc++/stable 27c aarch64 [upgradable from: 27b]
libcurl/stable 8.11.0-1 aarch64 [upgradable from: 8.10.1-2]
libsmartcols/stable 2.40.2-2 aarch64 [upgradable from: 2.40.2-1]
util-linux/stable 2.40.2-2 aarch64 [upgradable from: 2.40.2-1]
termux-tools version:
3.0.8
Android version:
14
Kernel build information:
Linux localhost 5.10.205-android12-9-00029-g3f12df86bfdb-ab11799032 #1 SMP PREEMPT Fri Apr 19 02:29:04 UTC 2024 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g54 5G
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Biswa96** [comment]
Have you tried to use lxqt with termux-x11? Could you provide the full output after running startlxqt? Please update all the packages.

**Comment by hanzelpeter** [comment]
I have not tried termux-x11. All [packages] update.
I have attached localhost:1.log.
If any other log file should be attached please write me.
[1.log](https://github.com/user-attachments/files/18041241/1.log)

**Comment by funsafe-ptr** [comment]
What about xfce? If that fails too, maybe it's because you're using the Play Store version?
https://github.com/termux-play-store#current-status-for-users

**Comment by hanzelpeter** [comment]
Hello. Yes I use Play store version.
I can start LXQT when I modify .vnc/xstartup to start qterminal. Then from qterminal I start dbus-launch and then startlxqt. Then LXQT is started. So maybe it has some problems with dbus launch order.
