### ISSUE TITLE
CANNOT LINK EXECUTABLE "php": library "libicuio.so.76" not found: needed by main executable

### ISSUE THREAD

**Issue by Jobians** [termux/termux-packages#22465]

**Comment by Biswa96** [comment]
Pleas fill up the issue template.

**Comment by Jobians** [comment]
@Biswa96 I fixed it.

If anyone else run over same issue please run
```
pkg install libicu
```

**Comment by Biswa96** [comment]
libicu is already a dependency of php https://github.com/termux/termux-packages/blob/master/packages/php/build.sh. So apt should install libicu with php automatically.

**Comment by Jobians** [comment]
Yes it installed already but when PHP is updated it doesn't update libicu

**Comment by yes141** [comment]
same proplem it dose not work with php 4 or more

**Comment by Biswa96** [comment]
There is no php 4 in termux packages.
