### ISSUE TITLE
Terminal transcript

### ISSUE THREAD

**Issue by Acnfv12** [termux/termux-packages#22478]
Welcome to Termux

Docs:       https://doc.termux.com
Community:  https://community.termux.com

Working with packages:
 - Search:  pkg search <query>
 - Install: pkg install <package>
 - Upgrade: pkg upgrade

Report issues at https://bugs.termux.com
~/downloads $ instahack
No command instahack found, did you mean:
 Command nethack in package nethack
~/downloads $ usnane :sre138753
No command usnane found, did you mean:
 Command snake in package bsd-games
 Command uname in package coreutils
 Command nsnake in package nsnake
 Command snake in package snake
 Command uuname in package uucp
~/downloads $ iamge
No command iamge found, did you mean:
 Command age in package age
 Command lame in package lame
 Command rage in package rage
 Command page in package tcllib
~/downloads $ Is
No command Is found, did you mean:
 Command as in package binutils-bin
 Command ls in package coreutils
 Command gs in package ghostscript
 Command ss in package iproute2
 Command ts in package moreutils
 Command ps in package procps
 Command ts in package task-spooler
~/downloads $ pkg ubstall coreutils
Unknown command: 'ubstall' (run 'pkg help' for u
sage information)
~/downloads $ pkg instll bsd-games
Ign:1 https://tur.kcubeterm.com tur-packages InR
elease
Hit:2 https://termux.net stable InRelease
Hit:3 https://x11-packages.termux.net x11 InRele
ase
Ign:1 https://turdl.kcubeterm.com tur-packages I
nRelease
Hit:1 https://turdl.kcubeterm.com tur-packages I
nRelease
9 packages can be upgraded. Run 'apt list --upgr
adable' to see them.
Installing:
  bsd-games

Summary:
  Upgrading: 0, Installing: 1, Removing: 0, Not 
Upgrading: 9
  Download size: 205 kB
  Space needed: 893 kB

Get:1 https://termux.net stable/main aarch64 bsd
-games aarch64 3.3 [205 kB]
Fetched 205 kB in 1s (171 kB/s)
dpkg: unrecoverable fatal error, aborting:
 unable to create '/data/data/com.termux/files/u
sr/var/lib/dpkg/updates/tmp.i': Permission denie
d
Error: Sub-process /data/data/com.termux/files/u
sr/bin/dpkg returned an error code (2)
~/downloads $ pkg install nsnake
Installing:
  nsnake

Summary:
  Upgrading: 0, Installing: 1, Removing: 0, Not 
Upgrading: 9
  Download size: 83.9 kB
  Space needed: 487 kB

Get:1 https://termux.net stable/main aarch64 nsn
ake aarch64 3.0.1-6 [83.9 kB]
Fetched 83.9 kB in 1s (105 kB/s)
dpkg: unrecoverable fatal error, aborting:
 unable to create '/data/data/com.termux/files/u
sr/var/lib/dpkg/updates/tmp.i': Permission denie
d
Error: Sub-process /data/data/com.termux/files/u
sr/bin/dpkg returned an error code (2)
~/downloads $ pkg install snake
Installing:
  snake

Summary:
  Upgrading: 0, Installing: 1, Removing: 0, Not 
Upgrading: 9
  Download size: 16.8 kB
  Space needed: 90.1 kB

Get:1 https://termux.net stable/main aarch64 sna
ke aarch64 2022.11.07 [16.8 kB]
Fetched 16.8 kB in 1s (18.9 kB/s)
dpkg: unrecoverable fatal error, aborting:
 unable to create '/data/data/com.termux/files/u
sr/var/lib/dpkg/updates/tmp.i': Permission denie
d
Error: Sub-process /data/data/com.termux/files/u
sr/bin/dpkg returned an error code (2)
~/downloads $ pkg instalk tcllib
Installing:
  tcllib

Installing dependencies:
  tcl

Summary:
  Upgrading: 0, Installing: 2, Removing: 0, Not 
Upgrading: 9
  Download size: 5894 kB
  Space needed: 23.5 MB

Continue? [Y/n] Y
Get:1 https://termux.net stable/main aarch64 tcl
 aarch64 8.6.14 [2263 kB]
Get:2 https://termux.net stable/main aarch64 tcl
lib all 2.0 [3631 kB]
Fetched 5894 kB in 2s (3192 kB/s)
dpkg: unrecoverable fatal error, aborting:
 unable to create '/data/data/com.termux/files/u
sr/var/lib/dpkg/updates/tmp.i': Permission denie
d
Error: Sub-process /data/data/com.termux/files/u
sr/bin/dpkg returned an error code (2)
~/downloads $ pkg
Usage: pkg command [arguments]

A tool for managing apt packages.

Commands:

  autoclean            - Remove all outdated pac
kages from apt cache.

  clean                - Remove all packages fro
m apt cache.
                         Using 799M now.

  files <packages>     - Show all files installe
d by packages.

  install <packages>   - Install specified packa
ges.

  list-all             - List all packages avail
able in repositories.

  list-installed       - List installed packages
.

  reinstall <packages> - Reinstall specified ins
talled packages at the
                         latest version.

  search <query>       - Search package by query
, for example by name or
                         description part.

  show <packages>      - Show basic metadata, su
ch as dependencies.

  uninstall <packages> - Uninstall specified pac
kages. Configuration files
                         will be left intact.

  upgrade              - Upgrade all installed p
ackages to the latest
                         version.

  update               - Update apt databases fr
om configured
                         repositories.

~/downloads $ pkg updet
Hit:1 https://termux.net stable InRelease
Ign:2 https://tur.kcubeterm.com tur-packages InR
elease
Hit:2 https://turdl.kcubeterm.com tur-packages I
nRelease
Hit:3 https://x11-packages.termux.net x11 InRele
ase
9 packages can be upgraded. Run 'apt list --upgr
adable' to see them.
~/downloads $ paswoord accont usname insta @sare
138753
No command paswoord found, did you mean:
 Command parecord in package pulseaudio
~/downloads $ pkg install pulseaudio
pulseaudio is already the newest version (17.0-2
).
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not 
Upgrading: 9
~/downloads $ paswoord accont usname insta @sare
138753
No command paswoord found, did you mean:
 Command parecord in package pulseaudio
~/downloads $ cd hackinsta
bash: cd: hackinsta: No such file or directory
~/downloads $ is
No command is found, did you mean:
 Command as in package binutils-bin
 Command id in package coreutils
 Command gs in package ghostscript
 Command ip in package iproute2
 Command ts in package moreutils
 Command ps in package procps
 Command ils in package sleuthkit
 Command ts in package task-spooler
 Command vis in package vis
~/downloads $ pkg install vis
vis is already the newest version (0.9-3).
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not 
Upgrading: 9
~/downloads $ pkg install task-spooler
task-spooler is already the newest version (1.0.
3).
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not 
Upgrading: 9
~/downloads $ taxtol
No command taxtol found, did you mean:
 Command atool in package atool
 Command axel in package axel
 Command factor in package coreutils
 Command hxtoc in package html-xml-utils
 Command atob in package nss-utils
 Command pastel in package pastel
 Command pactl in package pulseaudio
 Command taplo in package taplo
 Command tdbtool in package tdb-tools
 Command texdoc in package texlive-bin
 Command tsxml in package tsduck-tools
~/downloads $ proxy.txt
proxy.txt: command not found
~/downloads $ pip hack
ERROR: unknown command "hack" - maybe you meant 
"check"
~/downloads $ instahack
No command instahack found, did you mean:
 Command nethack in package nethack
~/downloads $ ld sara138753
The program ld is not installed. Install it by e
xecuting:
 pkg install binutils
or
 pkg install binutils-is-llvm
~/downloads $ pkg install binutils-is-llvm
Installing:
  binutils-is-llvm

Summary:
  Upgrading: 0, Installing: 1, Removing: 0, Not 
Upgrading: 9
  Download size: 0 B / 1824 B
  Space needed: 49.2 kB

dpkg: unrecoverable fatal error, aborting:
 unable to create '/data/data/com.termux/files/u
sr/var/lib/dpkg/updates/tmp.i': Permission denie
d
Error: Sub-process /data/data/com.termux/files/u
sr/bin/dpkg returned an error code (2)
~/downloads $ permission
permission: command not found
~/downloads $ found
No command found found, did you mean:
 Command fold in package coreutils
 Command find in package findutils
 Command count in package llvm-tools
 Command mount in package mount-utils
 Command ffind in package sleuthkit
~/downloads $ pkg install sleuthkit
sleuthkit is already the newest version (4.12.1-
1).
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not 
Upgrading: 9
~/downloads $ cdinstahack
cdinstahack: command not found
~/downloads $ pkg instshsck
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not 
Upgrading: 9
~/downloads $ @sare138753
@sare138753: command not found
~/downloads $ @sare138753
@sare138753: command not found
~/downloads $ https://aparat.com/V/InyhL
bash: https://aparat.com/V/InyhL: Permission den
ied
~/downloads $
~/downloads $
~/downloads $
~/downloads $ ♈️«pkg uninstall <package_name
bash: package_name: No such file or directory
~/downloads $
♈️«pkg uninstall <package_nam
bash: package_nam: No such file or directory
~/downloads $ cd <directory
bash: directory: No such file or directory
~/downloads $ mv <source> <destination          
bash: syntax error near unexpected token `<'
~/downloads $ webcam_snap -i 1 -p storage/downlo
ads/X-Stealth-Snapshot-R.jpg
webcam_snap: command not found
~/downloads $ dump_contacts -o storage/downloads
/X-Contacts.txt
dump_contacts: command not found
~/downloads $ pkg found
dpkg-query: error: --listfiles needs at least on
e package name argument

Use --help for help about querying packages.
~/downloads $
~/downloads $ dump_sms -o storage/downloads/X-SM
S.txt
No command dump_sms found, did you mean:
 Command dcmpsmk in package dcmtk
 Command dumpe2fs in package e2fsprogs
~/downloads $
~/downloads $ git clone https://github.com/remo7
777/T-Header.git
Cloning into 'T-Header'...
remote: Enumerating objects: 220, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (24/24), done
remote: Total 220 (delta 100), reused 91 (delta 
88), pack-reused 108 (from 1)
Receiving objects:  18% (40/220), 444.00 KiB | 8
Receiving objects:  19% (42/220), 444.00 KiB | 8
Receiving objects:  20% (44/220), 444.00 KiB | 8
Receiving objects:  21% (47/220), 444.00 KiB | 8
Receiving objects:  22% (49/220), 444.00 KiB | 8
Receiving objects:  23% (51/220), 444.00 KiB | 8
Receiving objects:  24% (53/220), 444.00 KiB | 8
Receiving objects:  25% (55/220), 444.00 KiB | 8
Receiving objects:  26% (58/220), 444.00 KiB | 8
Receiving objects:  27% (60/220), 444.00 KiB | 8
Receiving objects:  28% (62/220), 444.00 KiB | 8
Receiving objects:  29% (64/220), 444.00 KiB | 8
Receiving objects:  30% (66/220), 444.00 KiB | 8
Receiving objects:  31% (69/220), 444.00 KiB | 8
Receiving objects:  32% (71/220), 444.00 KiB | 8
Receiving objects:  33% (73/220), 444.00 KiB | 8
Receiving objects:  34% (75/220), 444.00 KiB | 8
Receiving objects:  35% (77/220), 444.00 KiB | 8
Receiving objects:  36% (80/220), 444.00 KiB | 8
Receiving objects:  37% (82/220), 444.00 KiB | 8
Receiving objects:  38% (84/220), 444.00 KiB | 8
Receiving objects:  39% (86/220), 444.00 KiB | 8
Receiving objects:  40% (88/220), 444.00 KiB | 8
Receiving objects:  41% (91/220), 444.00 KiB | 8
Receiving objects:  42% (93/220), 444.00 KiB | 8
Receiving objects:  43% (95/220), 444.00 KiB | 8
Receiving objects:  44% (97/220), 444.00 KiB | 8
Receiving objects:  45% (99/220), 444.00 KiB | 8
Receiving objects:  46% (102/220), 444.00 KiB | 
Receiving objects:  47% (104/220), 444.00 KiB | 
Receiving objects:  48% (106/220), 444.00 KiB | 
Receiving objects:  49% (108/220), 444.00 KiB | 
Receiving objects:  50% (110/220), 444.00 KiB | 
Receiving objects:  51% (113/220), 444.00 KiB | 
Receiving objects:  52% (115/220), 444.00 KiB | 
Receiving objects:  53% (117/220), 444.00 KiB | 
Receiving objects:  54% (119/220), 444.00 KiB | 
Receiving objects:  55% (121/220), 444.00 KiB | 
Receiving objects:  56% (124/220), 444.00 KiB | 
Receiving objects:  57% (126/220), 444.00 KiB | 
Receiving objects:  58% (128/220), 444.00 KiB | 
Receiving objects:  59% (130/220), 444.00 KiB | 
Receiving objects:  60% (132/220), 444.00 KiB | 
Receiving objects:  61% (135/220), 444.00 KiB | 
Receiving objects:  62% (137/220), 444.00 KiB | 
Receiving objects:  63% (139/220), 444.00 KiB | 
Receiving objects:  64% (141/220), 444.00 KiB | 
Receiving objects:  65% (143/220), 444.00 KiB | 
Receiving objects:  66% (146/220), 444.00 KiB | 
Receiving objects:  67% (148/220), 444.00 KiB | 
Receiving objects:  68% (150/220), 444.00 KiB | 
Receiving objects:  69% (152/220), 444.00 KiB | 
Receiving objects:  70% (154/220), 444.00 KiB | 
Receiving objects:  71% (157/220), 444.00 KiB | 
Receiving objects:  72% (159/220), 444.00 KiB | 
Receiving objects:  73% (161/220), 444.00 KiB | 
Receiving objects:  74% (163/220), 444.00 KiB | 
Receiving objects:  75% (165/220), 444.00 KiB | 
Receiving objects:  76% (168/220), 444.00 KiB | 
Receiving objects:  77% (170/220), 444.00 KiB | 
Receiving objects:  78% (172/220), 444.00 KiB | 
Receiving objects:  79% (174/220), 444.00 KiB | 
Receiving objects:  80% (176/220), 444.00 KiB | 
Receiving objects:  81% (179/220), 444.00 KiB | 
Receiving objects:  82% (181/220), 444.00 KiB | 
Receiving objects:  83% (183/220), 444.00 KiB | 
Receiving objects:  84% (185/220), 444.00 KiB | 
Receiving objects:  85% (187/220), 444.00 KiB | 
Receiving objects:  86% (190/220), 444.00 KiB | 
Receiving objects:  87% (192/220), 444.00 KiB | 
Receiving objects:  88% (194/220), 444.00 KiB | 
Receiving objects:  89% (196/220), 444.00 KiB | 
Receiving objects:  90% (198/220), 444.00 KiB | 
Receiving objects:  91% (201/220), 444.00 KiB | 
Receiving objects:  92% (203/220), 444.00 KiB | 
Receiving objects:  93% (205/220), 444.00 KiB | 
Receiving objects:  94% (207/220), 444.00 KiB | 
Receiving objects:  95% (209/220), 444.00 KiB | 
Receiving objects:  96% (212/220), 444.00 KiB | 
Receiving objects:  97% (214/220), 444.00 KiB | 
Receiving objects:  98% (216/220), 444.00 KiB | 
Receiving objects:  99% (218/220), 444.00 KiB | 
Receiving objects: 100% (220/220), 444.00 KiB | 
Receiving objects: 100% (220/220), 695.19 KiB | 
1.12 MiB/s, done.
Resolving deltas: 100% (117/117), done.
~/downloads $
~/downloads $ cd -Header
bash: cd: -H: invalid option
cd: usage: cd [-L|[-P [-e]] [-@]] [dir]
~/downloads $
~/downloads $ bash t-header.sh
/data/data/com.termux/files/usr/bin/bash: t-head
er.sh: No such file or directory
~/downloads $ hackinsta
hackinsta: command not found
~/downloads $ zare
No command zare found, did you mean:
 Command age in package age
 Command arj in package arj
 Command ar in package binutils
 Command ar in package binutils-is-llvm
 Command bore in package bore
 Command date in package coreutils
 Command dar in package dar
 Command dart in package dart
 Command zgrep in package gzip
 Command lame in package lame
 Command mark in package mailutils
 Command make in package make
 Command make in package make-guile
 Command arp in package net-tools
 Command mark in package nmh
 Command jar in package openjdk-21
 Command par2 in package par2
 Command parec in package pulseaudio
 Command rage in package rage
 Command rake in package ruby
 Command tar in package tar
 Command page in package tcllib
 Command tere in package tere
 Command more in package util-linux
 Command vale in package vale
 Command yara in package yara
 Command yarn in package yarn
~/downloads $ cd instagram
bash: cd: instagram: No such file or directory
~/downloads $ usname sare138753
No command usname found, did you mean:
 Command uname in package coreutils
 Command uuname in package uucp
~/downloads $ pkg install uucp
Installing:
  uucp

Summary:
  Upgrading: 0, Installing: 1, Removing: 0, Not 
Upgrading: 9
  Download size: 0 B / 316 kB
  Space needed: 1569 kB

dpkg: unrecoverable fatal error, aborting:
 unable to create '/data/data/com.termux/files/u
sr/var/lib/dpkg/updates/tmp.i': Permission denie
d
Error: Sub-process /data/data/com.termux/files/u
sr/bin/dpkg returned an error code (2)
~/downloads $

**Comment by twaik** [comment]
We do not help with it.

**Comment by Acnfv12** [comment]
~/downloads $ ~/downloads $ usnane :sre138753
/data/data/com.termux/files/home/downloads: /data/data/com.termux/files/home/downloads: Is a directory
