### ISSUE TITLE
How to avoid build time dependecies 

### ISSUE THREAD

**Issue by lkdevil** [termux/termux-packages#2247]
i am new to termux and my question is that if i want to create `build.sh` for a package and `dep-1` & `dep-2` are two dependencies for my package but `dep-1` is only required while build time not run time so I don't want to include `dep-1` in `TERMUX_PKG_DEPENDS` so what is the solution ?

**Comment by Grimler91** [comment]
You can use `TERMUX_PKG_BUILD_DEPENDS` for `dep-1`, as done for example in [pinentry/build.sh](https://github.com/termux/termux-packages/blob/master/packages/pinentry/build.sh).

**Comment by lkdevil** [comment]
Thnx @Grimler91

**Comment by sdrausty** [comment]
@Grimler91 do you know of any step by step instructions for Termux packaging?  Should this question be a new issue?

**Comment by Grimler91** [comment]
@sdrausty, no but the build-package.sh script has quite self-explainatory variables.

I've been thinking about writing a walkthrough for some simple package for a year or so though..

For now best way to get started is to read the readme and mimic existing build.sh scripts.
