### ISSUE TITLE
[Bug]: termux-microphone-record records silence

### ISSUE THREAD

**Issue by jankratochvil** [termux/termux-packages#22486]
### Problem description

`termux-microphone-record` was recoding files fine in August 2024. But recently all the files contain just silence now - already since October 1st. I do not have files from September so it probably had stopped working that time. I have latest `termux-tools` and I run on Pixel 8 with updated LineageOS (so it could be also a LineageOS regression).
Could someone test it is working? A regular PlayStore recording app is still working fine for me.

### What steps will reproduce the bug?

I was using `termux-microphone-record -f filename.mp4 -e amr_wb -r 16000 -b 23850 -c 1 -l 0` but even all other/removed removed parameters do not work. `termux-volume` shows all the volumes at max.

### What is the expected behavior?

Recorded sound

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=4232
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.44.5
Android version:
14
Kernel build information:
Linux localhost 5.15.137-android14-11-gbc062a78e195-ab12057991 #1 SMP PREEMPT Mon Jul 8 12:34:46 UTC 2024 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 8
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.boot versionCode:1000
```

**Comment by funsafe-ptr** [comment]
I think you need to report this to the repo.
https://github.com/termux/termux-api/issues, 

Also records fine on my device. Make sure you grant the Termux:API app the `android.permission.RECORD_AUDIO` permission.

**Comment by jankratochvil** [comment]
Thanks, I did disable and reenable the Microphone permission and it worked now, I will check it more.
