### ISSUE TITLE
Upgraded matplotlib makes python kernel crash

### ISSUE THREAD

**Issue by moises-santillan** [termux/termux-packages#2249]
After upgrading matplotlib to latest version, it makes python kernel crash. There is no problem to import matplotlib, but when trying to plot with `plt.plot()` the python kernel crashes returning `illegal instruction`.

**Comment by xeffyr** [comment]
@moises-santillan, what do you mean by 'python kernel' ? IPython, Jupyter kernels are not supported officially...
I guess you have a crash in one of the native extensions of installed modules, so you should try to reinstall deps (from sources) of matplotlib and then matplotlib.

**Comment by tomty89** [comment]
He means the whole python crashes and got core dumped, instead bumping into an error *in python*.

**Comment by xeffyr** [comment]
@tomty89, I never had crashes with matplotlib/numpy/scipy/pillow in Termux.
When native module (shared lib) crashes with `segmentation fault` or `illegal instruction`, it will look like a crash of `python` executable.

**Comment by Grimler91** [comment]
Closing since we don't really have any information about the error.
