### ISSUE TITLE
Auto update failing for moreutils

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#22507]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [moreutils](https://github.com/termux/termux-packages/blob/187b1de5bc32613574bf43ca22102ab4014c512e/packages/moreutils) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating moreutils [Current version: 0.69]
INFO: package being updated to 0.70.
Downloading http://ftp.debian.org/debian/pool/main/m/moreutils/moreutils_0.70.orig.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   260    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

moreutils: failed to calculate the new checksum
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-12-11 00:34:27 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/12267151130">12267151130</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by TomJo2000** [comment]
Looks like Debian is lagging behind upstream here.
It'd probably be better to change the srcurl to `git://git.joeyh.name/moreutils`
