### ISSUE TITLE
Package Request: Any tips on the best Linux proot running on aarch64 that also works with Oreo?

### ISSUE THREAD

**Issue by Root-voidX** [termux/termux-packages#2251]
Hey guys this is more of a package request/looking for suggestions. I am looking for a linux distro that works fully via termux-proot. I am experienced with gnuroot debian and Linux deploy but one doesn't work in 8.0 and another needs root. I tried termux-fedora but the core files dont load properly so using any application doesn't work. Any ideas?

**Comment by sdrausty** [comment]
@Root-voidX have you heard of Arch Linux through https://sdrausty.github.io/TermuxArch/ in Termux PRoot?

**Comment by Hax4us** [comment]
@Root-voidX Archlinux will be r8 choice for you :)

**Comment by tomty89** [comment]
I think it's barely relevant. If something in oreo is blocking you, it will probably blocks you in every distro. The bottom line is, none of them will *fully* work anyway.

And prooting is really just a single command line. (Or two, if you count the one for extraction). It can hardly be distro-specific.

**Comment by Neo-Oli** [comment]
Try https://plus.google.com/ for suggestions/support.
