### ISSUE TITLE
Python import fails due to inability to map segment

### ISSUE THREAD

**Issue by crypto-jeronimo** [termux/termux-packages#2253]
I've got a locally compiled (i.e, on the Android device itself) shared `.so` library. I've tested the same mechanism (via a [setup.py](https://docs.python.org/2/distutils/setupscript.html) script) it on other ARM-based devices and it works without any problems.

However, when I try to import the library into Python 2.7, I keep getting the following error:
```
$ pwd
/data/data/com.termux/files/home/storage/<path_to_file>

$ python2
>>> import <shared_lib>
ImportError: dlopen failed: couldn't map "/storage/emulated/0/<path_to_file>/<shared_lib>.so" segment 0: Permission denied
```

I've seen some suggestions online about creating a temporary directory and assigning it to either `TMP` or `TMPDIR` environment variables, but neither worked.

**Comment by Grimler91** [comment]
Move everything to some folder in $HOME instead and try again. The shared storage comes with limitations for security reasons.

**Comment by crypto-jeronimo** [comment]
Worked like a charm, thanks!

**Comment by jaydamani** [comment]
Is there any way without having to move it out of shared storage?

**Comment by xeffyr** [comment]
@jaydamani No, this is not possible.

Android applies a reasonable restriction (W^X, to reduce possibility of injecting code by unauthorized apps) to prevent loading of .so files from shared storage. Also, shared storage doesn't support symlinks and Unix file permissions. So it is a good idea to *move your Python modules and related files to Termux home directory*.

Locking issue as solution is already provided and there nothing more to discuss.
