### ISSUE TITLE
VLC no sound output since updating.

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#22550]
### Problem description

Since upgrading to VLC media player 3.0.21 Vetinari (revision 3.0.21-0-gdd8bfdbabe8) VLC does not produce any sound output from either file or stream input. 

### What steps will reproduce the bug?

Start VLC with a file or stream as input.

### What is the expected behavior?

VLC should provide sound output to local audio devices.

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=10723
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.danyael.xyz/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://termux.danyael.xyz/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://termux.danyael.xyz/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.44.5
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Fri Nov 26 00:14:01 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.boot versionCode:1000
com.termux.styling versionCode:1000
com.termux.widget versionCode:12
com.termux.window versionCode:15
```

**Comment by funsafe-ptr** [comment]
Me too, sometimes VLC starts without sound.
You need to manually kill `pulseaudio` and restart VLC. In my case, the audio started working again.
```sh
killall -KILL pulseaudio
```
Must use `SIGKILL`, `SIGTERM` won't work.

**Comment by TomJo2000** [comment]
This should hopefully be resolved by #22551

**Comment by macerg** [comment]
I probably shouldn't double up here but I'll give it a try for my convenience.
The qt interface no longer works.
--intf qt in x11

**Comment by funsafe-ptr** [comment]
What do you mean?

![ss](https://github.com/user-attachments/assets/f3e5475f-06e4-42ee-8faa-a197c6919682)

**Comment by macerg** [comment]
Ok, it works for you. Used to work for me but no longer.

**Comment by funsafe-ptr** [comment]
Maybe because of this?
 
```fish
❯ apt search vlc
Sorting... Done
Full Text Search... Done
vlc/stable 3.0.21-3 aarch64
  A popular libre and open source media player and multimedia engine

vlc-qt/x11,now 3.0.21-4 aarch64 [installed]
  A popular libre and open source media player and multimedia engine
```

**Comment by macerg** [comment]
Yes that fixed that thanks. Was installed before as a package with VLC iirc. Can't explain whst happened to it.

**Comment by macerg** [comment]
I think that this has been closed in error. The original 'no sound' has not been resolved as
https://github.com/termux/termux-packages/pull/22551 has not been completed. Perhaps this my fault for piggybacking another issue? Sorry for that.

**Comment by TomJo2000** [comment]
> Yes that fixed that thanks. Was installed before as a package with VLC iirc. Can't explain whst happened to it.

Sorry I interpreted this as "issue resolved"

**Comment by macerg** [comment]
> > Yes that fixed that thanks. Was installed before as a package with VLC iirc. Can't explain whst happened to it.
> 
> Sorry I interpreted this as "issue resolved"

No worries, thanks for re-opening.

**Comment by funsafe-ptr** [comment]
Did you try the one with killing the `pulseaudio` server?

**Comment by macerg** [comment]
> Did you try the one with killing the `pulseaudio` server?

Yes, tried a number of times but it doesn't work for me.

**Comment by macerg** [comment]
On an x11 session I get something like '.mp4a codec not supported. Can play .ogg ok though.

**Comment by twaik** [comment]
Probably related to recent ffmpeg update?

**Comment by funsafe-ptr** [comment]
You're right. After upgrading to `ffmpeg 7.1-1`, the audio stopped working with error
```
Codec not supported:
VLC could not decode the format "mp4a" (MPEG AAC Audio)
```

**Comment by twaik** [comment]
@Biswa96 related to #22518

**Comment by Biswa96** [comment]
New PR is pending as Tom mentioned above.

**Comment by twaik** [comment]
Also ffplay does not work due to 
```
CANNOT LINK EXECUTABLE "ffplay": library "libavfilter.so.9" not found: needed by main executable
```
Because it is linked against `libavfilter.so.9` instead of `libavfilter.so.10` present in current ffmpeg version.

**Comment by twaik** [comment]
Oh, ok.

**Comment by macerg** [comment]
> You're right. After upgrading to `ffmpeg 7.1-1`, the audio stopped working with error
> 
> ```
> Codec not supported:
> VLC could not decode the format "mp4a" (MPEG AAC Audio)
> ```

Interestingly, I regressed to 1 and then 2 earlier versions. Still didn't work.

**Comment by funsafe-ptr** [comment]
Do you mean downgrading? How do you do that?

**Comment by macerg** [comment]
> Do you mean downgrading? How do you do that?

dpkg -i (backup_file)from /data/data/com.termux/cache/apt/archives

**Comment by funsafe-ptr** [comment]
I regularly clean the cache to free up space :( 
The last working version of ffmpeg is 6, 
As Termux does not officially support downgrading, I think I'll wait for the fix.
