### ISSUE TITLE
Auto update failing for hugo

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#22563]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [hugo](https://github.com/termux/termux-packages/blob/f4767e3b326266a552a0c607c76dc564742f0a89/packages/hugo) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating hugo [Current version: 0.139.4]
INFO: package being updated to 0.139.5.
Downloading https://github.com/gohugoio/hugo/archive/v0.139.5.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 1600k    0 1600k    0     0  3884k      0 --:--:-- --:--:-- --:--:-- 3884k
100 20.2M    0 20.2M    0     0  14.8M      0 --:--:--  0:00:01 --:--:-- 19.6M

You are about to commit these changes:

--------------------
diff --git a/packages/hugo/build.sh b/packages/hugo/build.sh
index b79181d96b..f2e31abe47 100644
--- a/packages/hugo/build.sh
+++ b/packages/hugo/build.sh
@@ -2,9 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://gohugo.io/
 TERMUX_PKG_DESCRIPTION="A fast and flexible static site generator"
 TERMUX_PKG_LICENSE="Apache-2.0"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="0.139.4"
+TERMUX_PKG_VERSION="0.139.5"
 TERMUX_PKG_SRCURL=https://github.com/gohugoio/hugo/archive/v$TERMUX_PKG_VERSION.tar.gz
-TERMUX_PKG_SHA256=8c89c968ace21086528a164cd9a1019809c0064f0ea2ef8a82b035c2d079d19b
+TERMUX_PKG_SHA256=ed3e3e8887285c71b5d8ae9f9be956c5313c16f31c8501602d52eae7a002f53d
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_DEPENDS="libc++"
 
--------------------

bump(main/hugo): 0.139.5

Not committing to Git!

INFO: Trying to build package.
INFO: Package hugo exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building hugo for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  62688      0 --:--:-- --:--:-- --:--:-- 62542
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2023      0 --:--:-- --:--:-- --:--:--  2026
gpg: Signature made Sat 14 Dec 2024 01:58:16 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  36031      0 --:--:-- --:--:-- --:--:-- 36000
100 13320  100 13320    0     0  36021      0 --:--:-- --:--:-- --:--:-- 36000
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2300      0 --:--:-- --:--:-- --:--:--  2301
gpg: Signature made Sat 14 Dec 2024 09:53:53 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  38544      0 --:--:-- --:--:-- --:--:-- 38588
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2243      0 --:--:-- --:--:-- --:--:--  2239
gpg: Signature made Sat 14 Dec 2024 03:18:59 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency libc++@27c if necessary...
Found libc++ in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libc/libc++/libc++_27c_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  291k  100  291k    0     0  2536k      0 --:--:-- --:--:-- --:--:-- 2556k
extracting libc++ to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/gohugoio/hugo/archive/v0.139.5.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 16.2M    0 16.2M    0     0  15.7M      0 --:--:--  0:00:01 --:--:-- 15.7M
100 20.2M    0 20.2M    0     0  16.8M      0 --:--:--  0:00:01 --:--:-- 23.6M
go: downloading github.com/alecthomas/chroma/v2 v2.14.0
go: downloading github.com/bep/clocks v0.5.0
go: downloading github.com/bep/debounce v1.2.0
go: downloading github.com/bep/lazycache v0.7.0
go: downloading github.com/bep/logg v0.4.0
go: downloading github.com/bep/overlayfs v0.9.2
go: downloading github.com/bep/mclib v1.20400.20402
go: downloading github.com/bep/simplecobra v0.4.0
go: downloading github.com/fsnotify/fsnotify v1.8.0
go: downloading github.com/pkg/browser v0.0.0-20240102092130-5ac0b6a4141c
go: downloading github.com/spf13/afero v1.11.0
go: downloading github.com/spf13/cobra v1.8.1
go: downloading github.com/spf13/fsync v0.10.1
go: downloading github.com/spf13/pflag v1.0.5
go: downloading go.uber.org/automaxprocs v1.5.3
go: downloading golang.org/x/sync v0.9.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/dlclark/regexp2 v1.11.0
go: downloading github.com/bep/godartsass/v2 v2.3.2
go: downloading github.com/bep/golibsass v1.2.0
go: downloading github.com/pelletier/go-toml/v2 v2.2.3
go: downloading github.com/tdewolff/parse/v2 v2.7.15
go: downloading github.com/gohugoio/locales v0.14.0
go: downloading github.com/spf13/cast v1.7.0
go: downloading github.com/fatih/color v1.18.0
go: downloading github.com/gobwas/glob v0.2.3
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading github.com/mitchellh/mapstructure v1.5.1-0.20231216201459-8508981c8b6c
go: downloading github.com/pbnjay/memory v0.0.0-20210728143218-7b4eea64cf58
go: downloading golang.org/x/exp v0.0.0-20221031165847-c99f073a8326
go: downloading github.com/jdkato/prose v1.2.1
go: downloading github.com/kyokomi/emoji/v2 v2.2.13
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/armon/go-radix v1.0.1-0.20221118154546-54df44f2176c
go: downloading github.com/cespare/xxhash/v2 v2.3.0
go: downloading golang.org/x/text v0.20.0
go: downloading github.com/bep/gitmap v1.6.0
go: downloading github.com/frankban/quicktest v1.14.6
go: downloading github.com/gobuffalo/flect v1.0.3
go: downloading github.com/hairyhenderson/go-codeowners v0.6.1
go: downloading golang.org/x/tools v0.27.0
go: downloading github.com/rogpeppe/go-internal v1.13.1
go: downloading github.com/gorilla/websocket v1.5.3
go: downloading golang.org/x/mod v0.22.0
go: downloading github.com/clbanning/mxj/v2 v2.7.0
go: downloading github.com/niklasfasching/go-org v1.7.0
go: downloading golang.org/x/sys v0.27.0
go: downloading github.com/yuin/goldmark v1.7.8
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.4
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/net v0.31.0
go: downloading software.sslmate.com/src/go-pkcs12 v0.2.0
go: downloading github.com/hashicorp/golang-lru/v2 v2.0.7
go: downloading github.com/cli/safeexec v1.0.1
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/gohugoio/hashstructure v0.1.0
go: downloading github.com/gohugoio/localescompressed v1.0.1
go: downloading github.com/BurntSushi/locker v0.0.0-20171006230638-a6e239ea1c69
go: downloading github.com/gohugoio/httpcache v0.7.0
go: downloading github.com/tdewolff/minify/v2 v2.20.37
go: downloading github.com/bep/gowebp v0.3.0
go: downloading github.com/disintegration/gift v1.2.1
go: downloading github.com/bep/imagemeta v0.8.3
go: downloading github.com/makeworld-the-better-one/dither/v2 v2.4.0
go: downloading github.com/muesli/smartcrop v0.3.0
go: downloading golang.org/x/image v0.22.0
go: downloading github.com/tetratelabs/wazero v1.8.2
go: downloading google.golang.org/protobuf v1.35.2
go: downloading github.com/marekm4/color-extractor v1.2.1
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading github.com/google/go-cmp v0.6.0
go: downloading github.com/kr/pretty v0.3.1
go: downloading github.com/gohugoio/go-i18n/v2 v2.1.3-0.20230805085216-e63c13218d0e
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading golang.org/x/crypto v0.29.0
go: downloading github.com/bep/tmc v0.5.1
go: downloading github.com/gohugoio/hugo-goldmark-extensions/extras v0.2.0
go: downloading github.com/yuin/goldmark-emoji v1.0.4
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/bep/goat v0.5.0
go: downloading github.com/getkin/kin-openapi v0.123.0
go: downloading github.com/ghodss/yaml v1.0.0
go: downloading github.com/gohugoio/hugo-goldmark-extensions/passthrough v0.3.0
go: downloading github.com/evanw/esbuild v0.24.0
go: downloading github.com/perimeterx/marshmallow v1.1.5
go: downloading github.com/invopop/yaml v0.2.0
go: downloading github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826
go: downloading github.com/go-openapi/jsonpointer v0.20.2
go: downloading github.com/go-openapi/swag v0.22.8
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/alecthomas/chroma/v2 v2.14.0
go: downloading github.com/bep/clocks v0.5.0
go: downloading github.com/bep/debounce v1.2.0
go: downloading github.com/bep/lazycache v0.7.0
go: downloading github.com/bep/logg v0.4.0
go: downloading github.com/bep/mclib v1.20400.20402
go: downloading github.com/bep/simplecobra v0.4.0
go: downloading github.com/bep/overlayfs v0.9.2
go: downloading github.com/fsnotify/fsnotify v1.8.0
go: downloading github.com/pkg/browser v0.0.0-20240102092130-5ac0b6a4141c
go: downloading github.com/spf13/afero v1.11.0
go: downloading github.com/spf13/cobra v1.8.1
go: downloading github.com/spf13/fsync v0.10.1
go: downloading github.com/spf13/pflag v1.0.5
go: downloading go.uber.org/automaxprocs v1.5.3
go: downloading golang.org/x/sync v0.9.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/hashicorp/golang-lru/v2 v2.0.7
go: downloading github.com/dlclark/regexp2 v1.11.0
go: downloading github.com/bep/godartsass/v2 v2.3.2
go: downloading github.com/bep/golibsass v1.2.0
go: downloading github.com/pelletier/go-toml/v2 v2.2.3
go: downloading github.com/tdewolff/parse/v2 v2.7.15
go: downloading github.com/gohugoio/locales v0.14.0
go: downloading github.com/spf13/cast v1.7.0
go: downloading github.com/fatih/color v1.18.0
go: downloading github.com/gobwas/glob v0.2.3
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading github.com/mitchellh/mapstructure v1.5.1-0.20231216201459-8508981c8b6c
go: downloading golang.org/x/exp v0.0.0-20221031165847-c99f073a8326
go: downloading github.com/pbnjay/memory v0.0.0-20210728143218-7b4eea64cf58
go: downloading github.com/jdkato/prose v1.2.1
go: downloading github.com/kyokomi/emoji/v2 v2.2.13
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/armon/go-radix v1.0.1-0.20221118154546-54df44f2176c
go: downloading github.com/cespare/xxhash/v2 v2.3.0
go: downloading golang.org/x/text v0.20.0
go: downloading github.com/rogpeppe/go-internal v1.13.1
go: downloading github.com/gorilla/websocket v1.5.3
go: downloading golang.org/x/mod v0.22.0
go: downloading github.com/bep/gitmap v1.6.0
go: downloading github.com/frankban/quicktest v1.14.6
go: downloading github.com/gobuffalo/flect v1.0.3
go: downloading github.com/hairyhenderson/go-codeowners v0.6.1
go: downloading golang.org/x/tools v0.27.0
go: downloading github.com/clbanning/mxj/v2 v2.7.0
go: downloading github.com/niklasfasching/go-org v1.7.0
go: downloading github.com/yuin/goldmark v1.7.8
go: downloading golang.org/x/sys v0.27.0
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.4
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/cli/safeexec v1.0.1
go: downloading google.golang.org/protobuf v1.35.2
go: downloading golang.org/x/net v0.31.0
go: downloading software.sslmate.com/src/go-pkcs12 v0.2.0
go: downloading github.com/gohugoio/hashstructure v0.1.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/BurntSushi/locker v0.0.0-20171006230638-a6e239ea1c69
go: downloading github.com/gohugoio/httpcache v0.7.0
go: downloading github.com/gohugoio/localescompressed v1.0.1
go: downloading github.com/tdewolff/minify/v2 v2.20.37
go: downloading github.com/bep/gowebp v0.3.0
go: downloading github.com/disintegration/gift v1.2.1
go: downloading github.com/makeworld-the-better-one/dither/v2 v2.4.0
go: downloading github.com/bep/imagemeta v0.8.3
go: downloading github.com/muesli/smartcrop v0.3.0
go: downloading golang.org/x/image v0.22.0
go: downloading github.com/tetratelabs/wazero v1.8.2
go: downloading github.com/marekm4/color-extractor v1.2.1
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading github.com/google/go-cmp v0.6.0
go: downloading github.com/kr/pretty v0.3.1
go: downloading github.com/gohugoio/go-i18n/v2 v2.1.3-0.20230805085216-e63c13218d0e
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading golang.org/x/crypto v0.29.0
go: downloading github.com/bep/tmc v0.5.1
go: downloading github.com/gohugoio/hugo-goldmark-extensions/extras v0.2.0
go: downloading github.com/yuin/goldmark-emoji v1.0.4
go: downloading github.com/bep/goat v0.5.0
go: downloading github.com/getkin/kin-openapi v0.123.0
go: downloading github.com/ghodss/yaml v1.0.0
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/gohugoio/hugo-goldmark-extensions/passthrough v0.3.0
go: downloading github.com/evanw/esbuild v0.24.0
go: downloading github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826
go: downloading github.com/go-openapi/jsonpointer v0.20.2
go: downloading github.com/invopop/yaml v0.2.0
go: downloading github.com/perimeterx/marshmallow v1.1.5
go: downloading github.com/go-openapi/swag v0.22.8
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/josharian/intern v1.0.0
Generating Hugo man pages in /data/data/com.termux/files/usr/share/man/man1/ ...
Done.
termux-elf-cleaner: Replacing unsupported DF_1_* flags 134217729 with 1 in './bin/hugo'
INFO: READELF=llvm-readelf ... /home/builder/.termux-build/_cache/android-r27c-api-24-v1/bin/llvm-readelf
INFO: Generating undefined symbols regex to /tmp/tmp.h0ItVBFx7L
INFO: Done ... 0s
INFO: Total symbols 2365
INFO: Generating OpenMP symbols regex to /tmp/tmp.bxhhANKdMP
INFO: Done ... 0s
INFO: Total OpenMP symbols 2505
INFO: Identifying files with nproc=4
INFO: Done ... 0s
INFO: Found 1 / 47 files
INFO: Running symbol checks on 1 files with nproc=4
INFO: Done ... 1s
termux - build of 'hugo' done
INFO: Committing package.
INFO: Pushing package.
ERROR: git push failed. See below for details.
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
fatal: could not read Username for 'https://github.com': No such device or address</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-12-15 00:34:58 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/12334250117">12334250117</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by Biswa96** [comment]
Fixed in 24df4b1ed381bd311f44ea755172f9172f58a5c1 commit.
