### ISSUE TITLE
[Bug]: Command Not Found, Generates bootstrap archives and Package updates failed on GitHub Actions

### ISSUE THREAD

**Issue by wtest5555** [termux/termux-packages#22574]
### Problem description

The command-not-rebuild, generate bootstrap archives failed with
`fatal: could not read Username for 'https://github.com/': No such device or address` since Saturday

Package updates failed with:
```
ERROR: git push failed. See below for details.
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
fatal: could not read Username for 'https://github.com/': No such device or address
```

### What steps will reproduce the bug?

Schedule actions every 6 hrs

### System information

```shell
GitHub Actions
```

**Comment by truboxl** [comment]
Fixed by https://github.com/termux/termux-packages/commit/3e971ba3781f7f5920285d85523aad3570130077
