### ISSUE TITLE
gmpxx.h not found

### ISSUE THREAD

**Issue by FaArIsH** [termux/termux-packages#2261]
fte/rank_unrank.h:21:10: fatal error: 'gmpxx.h' file not found
    #include <gmpxx.h>
             ^~~~~~~~~
    1 error generated.
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

I have installed libgmp-dev but there is no gmpxx.h so I pasted it to include folder but still I get that error

**Comment by tomty89** [comment]
Yeah the current libgmp isn't built with `--enable-cxx` so the C++ library and header file are missing. Somehow the info files are not there either.

**Comment by its-pointless** [comment]
Yeah we didn't enable a lot of c++ in libraries because at the time a lot of it didn't work since the gnustl was so old. i will go though a bit enabling alot of it tommorow.

**Comment by vmonkey** [comment]
Is there any progress in this issue? I tried to compile gmp manually at termux but failed. Working gmp with cxx support would be great.

**Comment by xeffyr** [comment]
Done in https://github.com/termux/termux-packages/commit/dc14276be8edf156afc228c3bee6c21c20e54cd5.
