### ISSUE TITLE
can't open octave

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-packages#2263]
Hello,

I recently changed my phone. I installed termux and next octave, together with:

```
pkg install octave octave-dev python make clang gnuplot gnutls ncurses ncurses-dev libgnutls-dev units pkg-config libgfortran
pip install sympy requests slugify
```
But when running `octave-cli` i got the following error:
```
CANNOT LINK EXECUTABLE "octave-cli": cannot locate symbol "__powisf2" referenced by "/usr/lib/octave/4.2.1/liboctave.so"...
Aborted
```
Please help!
My phone, Huawei P9 Lite 2017, Android 7.0

**Comment by tomty89** [comment]
Octave isn't provided / supported in Termux yet, whose repo did you get it from?

Also `/usr/lib/...`...

**Comment by kurokirasama** [comment]
ok, i get it from here:
https://github.com/its-pointless/gcc_termux
regards,

**Comment by Grimler91** [comment]
Open a issue at its-pointless repo instead.

**Comment by sdrausty** [comment]
```
$ pacman -Ss octave
extra/cauchy 0.9.0-1
    A library for transforming Matlab/Octave files to C++ (with Eigen) and Matlab
extra/texmacs 1.99.6-1
    Free scientific text editor, inspired by TeX and GNU Emacs. WYSIWYG editor TeX-fonts and
    CAS-interface (Giac, GTybalt, Macaulay 2, Maxima, Octave, Pari, Qcl, R and Yacas) in one.
community/octave 4.2.2-1
    A high-level language, primarily intended for numerical computations.
```
*From Arch Linux in Termux PRoot*

These three and more than 6K complementary packages are available today thanks to Termux, [Termux PRoot](https://github.com/termux/proot) and [TermuxArch](https://sdrausty.github.io/TermuxArch/).
