### ISSUE TITLE
[Bug]: qemu-img & qemu-system-x86-64 packages maybe broken? 

### ISSUE THREAD

**Issue by col83** [termux/termux-packages#22642]
### Problem description

A couple of days ago I used the packages:

qemu-system-x86-64-headless and qemu-utils.

Everything worked fine, but since yesterday after reinstalling termux and/or installing two types of bootstrap, in any case after installing these packages none of them work.

I noticed that libnfs was updated yesterday - https://github.com/termux/termux-packages/commit/5c68c27170593c88eb3bdc1f5e02c3cf72eb8786

And I'm not sure but maybe this is the reason for the errors:

CANNOT LINK EXECUTABLE "qemu-img": cannot locate symbol "nfs_pagecache_invalidate" referenced by "/data/data/com.termux/files/usr/bin/qemu-img"... when using qemu-img

And also -

CANNOT LINK EXECUTABLE "qemu-system-x86_64": cannot locate symbol "nfs_pagecache_invalidate" referenced by "/data/data/com.termux/files/usr/bin/qemu-system-x86_64"... when using qemu-system-x86_64 respectively.

### What steps will reproduce the bug?

qemu-img, qemu-system-x86-64-headless

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~ltsenksYnSr4xw9z8xIbtQ==/com.termux-R4pwVztaXzdSOvOloq0y8A==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=4662
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=0:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_25:s0:c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10043
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+21bf4e0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+21bf4e0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.44.6
Android version:
13
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Fri Aug 2 12:42:32 CST 2024 aarch64 Android
Device manufacturer:
HONOR
Device model:
TFY-LX1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by truboxl** [comment]
Should kick off rebuild after #22619

**Comment by truboxl** [comment]
Bruh
https://lists.nongnu.org/archive/html/qemu-block/2024-12/msg00151.html

**Comment by truboxl** [comment]
I will turn off libnfs support until upstream fixes it or a patch is provided

**Comment by TomJo2000** [comment]
> I will turn off libnfs support until upstream fixes it or a patch is provided

Hold on, it's currently rebuilding.
https://github.com/termux/termux-packages/commit/f436747cd4e5af84fe831126b537f3c686cac274 https://github.com/termux/termux-packages/commit/3e1559a47840dcd9da6cab55b11cb77c3ec85a71
