### ISSUE TITLE
curl is installed with wrong libcurl, by default

### ISSUE THREAD

**Issue by bukzor** [termux/termux-packages#2266]
`apt upgrade` solves it, but this is a pretty subtle issues for users to figure out themselves.

Upon a fresh install of termux, curl is at a different, newer version than libcurl:
```
$ curl -V
curl 7.59.0 (i686-pc-linux-android) libcurl/7.58.0 OpenSSL/1.0.2n zlib/1.2.8 nghttp2/1.30.0
```

Trying to use curl in this state results in an error: `curl: (48) An unknown option was passed in to libcurl`

**Comment by fornwall** [comment]
Thanks - the bootstrap packages (those that are installed on a fresh Termux installation) has been updated to the latest versions now!

**Comment by NeKp0T** [comment]
Just now I've had the same problem. On freshly installed termux 0.66 libcurl was outdated and curl didn't work.
~~~~
curl is already the newest version (7.64.1).
Calculating upgrade... Done
The following NEW packages will be installed:
  game-repo science-repo termux-keyring
The following packages will be upgraded:
  apt bash busybox ca-certificates dpkg gpgv
  libbz2 libc++ libcurl libgpg-error
  libnghttp2 ncurses openssl readline
  termux-tools
15 upgraded, 3 newly installed, 0 to remove and 0 not upgraded
~~~~

**Comment by xeffyr** [comment]
> On freshly installed termux 0.66 libcurl was outdated and curl didn't work.

You haven't installed updates.

> The following packages will be upgraded:
  apt bash busybox ca-certificates dpkg gpgv
  libbz2 libc++ libcurl libgpg-error
  libnghttp2 ncurses openssl readline
  termux-tools

`pkg upgrade`

**Comment by xeffyr** [comment]
Bootstrap packages may not have up-to-date versions, so you need to do `pkg upgrade` after installing Termux.
