### ISSUE TITLE
[Package]: discordo update

### ISSUE THREAD

**Issue by col83** [termux/termux-packages#22670]
### Why is it worth to add this package?

package already exist in repo

### Home page URL

https://github.com/ayn2op/discordo

### Source code URL

https://github.com/ayn2op/discordo.git

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

I saw that the discordo package is actively maintained by its developer.

I got curious and looked at our build.sh
I don't understand much about the process of building packages in general, but judging by the structure, I need to update the commit variable, and also calculate a new SHA256. The problem is that I don't know how to calculate it

Further (as I understand it) github actions will build it with the golang dependency?

I ask you (if you have time and opportunity) to update the package and if it's not difficult, write a couple of lines here about where and how you get the hash?

**Comment by twaik** [comment]
Please don’t request package updates. We’re aware of new releases as soon as they become available.
However, we have a small team and can’t always update every package immediately.
Pull requests are always welcome!
