### ISSUE TITLE
Glib.h missing 

### ISSUE THREAD

**Issue by Vm900** [termux/termux-packages#2269]
Hi
I installed glib-dev but each time I try to compile I get glib.h not found. I have checked where it was installed and glib.h is not there. Only found glibconfig.h.
And another thing I want to install libgtk. How do I go about it?
Thanks in advance.

**Comment by tomty89** [comment]
```
$ dpkg -S glib.h
glib-dev: /data/data/com.termux/files/usr/include/glib-2.0/glib.h
$
```

**Comment by Vm900** [comment]
Still throws the same error @tomty89

**Comment by Vm900** [comment]
Is there a specific order the other deps like should be installed?(pango)I have managed to install gtk but pango not found in your pkg-config path.You should add directory containing pango.pc to the PKG_CONFIG_PATH environment variable
package pango required by gdk-3.0
When i nstall pango libgtk is removed.So confused now @Hax4us

**Comment by fornwall** [comment]
(Closing this as glib.h is in glib-dev)
