### ISSUE TITLE
git cannot clone a repo to shared storage

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#227]
When trying to clone a repo to shared storage the operation errors out due to chmod not being allowed on shared storage (a file created on shared storage is now owned by the Termux user, it's owned by root):

    chmod on /storage/emulated/0/termux-packages/.git/config.lock failed: Operation not permitted

The relevant commit to the git project was https://github.com/git/git/commit/daa22c6f8da466bd7a438f1bc27375fd737ffcf3:

    Users may already store sensitive data such as imap.pass in
    .git/config; making the file world-readable when "git config"
    is called to edit means their password would be compromised
    on a shared system.

What happens is that git creates `.git/config.log` in a project and as a last step tries to remove `.git/config` and rename() the lock file to it. So the chmod on the lock file is to retain permission of the config file.

The reason that git preserves permission of the config file in the project is that (as noted above) a user may store sensitive information in it.

One possible solution to this is to allow a git repo to be cloned to shared storage by warning once and then proceed, like with the following patch:

```diff
diff -u -r ../git-2.8.1/config.c ./config.c
--- ../git-2.8.1/config.c	2016-04-03 15:07:18.000000000 -0400
+++ ./config.c	2016-04-21 18:37:26.707906688 -0400
@@ -49,6 +49,27 @@
  */
 static struct config_set the_config_set;
 
+/*
+ * Protecting the project-specific git configuration file (.git/config) is
+ * not possible on a shared file system on Android, which on an unpatched
+ * git causes operations such as clone to fail with an error message.
+ *
+ * For the Termux git package we introduce a warning about the configuration
+ * file being unprotected, but proceed in order to allow git repositories
+ * to be cloned to shared storage accessible to other apps.
+ */
+static void termux_warn_once_about_lockfile()
+{
+	static int already_warned;
+	if (!already_warned) {
+		if (!already_warned) {
+			warning("Cannot protect .git/config on this file system"
+					" - do not store sensitive information here.");
+			already_warned = 1;
+		}
+	}
+}
+
 static int config_file_fgetc(struct config_source *conf)
 {
 	return getc_unlocked(conf->u.file);
@@ -2125,10 +2147,14 @@
 		in_fd = -1;
 
 		if (chmod(get_lock_file_path(lock), st.st_mode & 07777) < 0) {
+#ifdef __ANDROID__
+			termux_warn_once_about_lockfile();
+#else
 			error("chmod on %s failed: %s",
 			      get_lock_file_path(lock), strerror(errno));
 			ret = CONFIG_NO_WRITE;
 			goto out_free;
+#endif
 		}
 
 		if (store.seen == 0)
@@ -2330,9 +2356,13 @@
 	fstat(fileno(config_file), &st);
 
 	if (chmod(get_lock_file_path(lock), st.st_mode & 07777) < 0) {
+#ifdef __ANDROID__
+		termux_warn_once_about_lockfile();
+#else
 		ret = error("chmod on %s failed: %s",
 			    get_lock_file_path(lock), strerror(errno));
 		goto out;
+#endif
 	}
 
 	while (fgets(buf, sizeof(buf), config_file)) {
```

**Comment by johnmellor** [comment]
Seems a reasonable solution, and patch looks good (though I noticed you repeated `if (!already_warned) {` twice).

It's possible that something that forks multiple git processes might warn multiple times, but it seems this only happens if .git/config is modified, so that should be rare.

**Comment by fornwall** [comment]
@johnmellor Thanks, removed the double if clause!

Let's try this out - I've pushed the git package at version `2.8.1-2` to the apt repo containing this patch - let me know how it works.

**Comment by johnmellor** [comment]
Wonderful! I can confirm that git clone, commit, pull, push, status, rebase and diff all seem to work fine (at least for simple cases) in /sdcard :+1: 

(which in my case using Android N preview on Nexus 6P seems to be mounted as:
```/dev/fuse on /storage/emulated type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other)```
)
