### ISSUE TITLE
Please update `qalc` to the latest version (2.2.1)

### ISSUE THREAD

**Issue by agguser** [termux/termux-packages#2270]
https://qalculate.github.io/news.html

**Comment by Hax4us** [comment]
https://github.com/termux/termux-packages/pull/2272 here is PR for this :)

**Comment by fornwall** [comment]
The updated package is now available for installation - nice work!

**Comment by agguser** [comment]
It is still 2.1.0!

**Comment by Hax4us** [comment]
Yes I can aslo see .. Version is still 2.1.0 I checked termux.net repository and found qalc is still 2.1.0  @fornwall

**Comment by agguser** [comment]
Still 2.1.0, what's wrong? Please check.

BTW, 2.3 is now released.

**Comment by agguser** [comment]
2.3.0 now, thanks.
