### ISSUE TITLE
[Package]: base91

### ISSUE THREAD

**Issue by IzumiSenaSora** [termux/termux-packages#22702]
### Why is it worth to add this package?

An advanced method for encoding binary data to ASCII text

### Home page URL

http://base91.sourceforge.net/

### Source code URL

http://downloads.sourceforge.net/base91/base91-0.6.0.tar.gz

### Packaging policy acknowledgement

- [ ] The project is actively developed.
- [ ] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by twaik** [comment]
Last update was in 2006, it is unmaintained.
