### ISSUE TITLE
[Package]: autoconf 2.69

### ISSUE THREAD

**Issue by SamB** [termux/termux-packages#22713]
### Why is it worth to add this package?

Upstream binutils and gdb insist on autoconf 2.69 precisely, so it's tricky to hack their configure scripts on my phone without it.

### Home page URL

https://www.gnu.org/software/autoconf/autoconf.html

### Source code URL

https://git.savannah.gnu.org/cgit/autoconf.git

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

No, I didn't try it yet. It could be as simple as starting with the [autoconf](https://github.com/termux/termux-packages/tree/master/packages/autoconf) package, switching the source version and name, and adapting this line from autoconf213:

```
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--program-suffix=-2.13"
```

**Comment by twaik** [comment]
Please don’t request package updates. We’re aware of new releases as soon as they become available.
However, we have a small team and can’t always update every package immediately.
Pull requests are always welcome!

**Comment by Biswa96** [comment]
twaik, actually this issue is asking for a older release :)

Samuel, ArchLinux [uses](https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/blob/main/PKGBUILD) autoconf 2.72 to build gcc and binutils without any issue. Are you trying to build any older release?

**Comment by SamB** [comment]
@Biswa96 do they use a special flag for that, then? Perhaps the assertion was meant for maintainers, to prevent unnecessary charn and arbitrary fluctuations in flakiness.

**Comment by Biswa96** [comment]
> do they use a special flag for that, then?

All the configure options are mentioned in that PKGBUILD file. Could you share the error?

**Comment by SamB** [comment]
Oh, it looks like they don't actually run autoconf (to generate **/configure from **/configure.ac) during the build on arch. At least, I didn't spot any code for that in the PKGBUILD for binutils or gdb.

That's fine until you want to modify the configure scripts. For example, I wss trying to add checks for some stuff that isn't in Termux's thread_db.h to gdb's configure.ac that I think are only used for consistency checks anyway and then skip those checks when the fields aren't there...

But when I do (basically[^1]):
```bash
git clone https://sourceware.org/git/binutils-gdb.git
cd binutils/gdb
autoconf
```

I get the error:

```
configure.ac:21: error: Please use exactly Autoconf 2.69 instead of 2.72.
../config/override.m4:12: _GCC_AUTOCONF_VERSION_CHECK is expanded from...
configure.ac:21: the top level
autom4te: error: /data/data/com.termux/files/usr/bin/m4 failed with exit status: 1
```

But I suppose, since the macros wouldn't get defined on Termux anyway, I can (and should) just test that part of my changes on a computer later (to make sure I spelled the macro names correctly in my `#if`s).

It would be nice to be able to check the code now, though, and I definitely can't properly address that thing where getrandom() gets detected as existing (because it exists in libc) but then can't actually be used (because it's not declared at API level 24).

Anyway, I guess it'd be easy enough to just package it myself: the trickiest part might be bikeshedding the name of the package.

**Comment by Grimler91** [comment]
@samb please try `autoreconf -vfi` instead, see for example https://stackoverflow.com/questions/27285052/difference-between-autoconf-and-autoreconf for difference between autoconf and autoreconf
