### ISSUE TITLE
git deadlocks when pushing large packs

### ISSUE THREAD

**Issue by bukzor** [termux/termux-packages#2271]
Small patches seem to work fine, but when moving something as large as Homebrew around, git deadlocks, even if it's between two localhost repositories, not using ssh. 

Demo:

```
bash-4.4$ git clone https://github.com/Linuxbrew/brew.git
Cloning into 'brew'...
remote: Counting objects: 107255, done.
remote: Compressing objects: 100% (220/220), done.
remote: Total 107255 (delta 260), reused 261 (delta 189), pack-reused 106841
Receiving objects: 100% (107255/107255), 24.37 MiB | 2.51 MiB/s, done.
Resolving deltas: 100% (78156/78156), done.

bash-4.4$ GIT_TRACE=2 GIT_SSH=/not/executable git push ../demo
16:24:34.454758 git.c:344               trace: built-in: git 'push' '../demo'
16:24:34.457110 run-command.c:631       trace: run_command: 'git-receive-pack '\''../demo'\'''
16:24:34.467498 git.c:344               trace: built-in: git 'receive-pack' '../demo'
16:24:34.469045 run-command.c:631       trace: run_command: 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
16:24:34.478012 git.c:344               trace: built-in: git 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
Counting objects: 107017, done.
```

It never progresses past that point. I did some debugging, and I don't understand the git-pack protocol at all, but it seems like `git pack-objects` is waiting too long to send its data, or else `git receive-objects` is waiting too long to close the pipe. Also, the pipe seems to have more than two open references so that could be the cause:

```
$ ps -o pid,ppid,args | egrep '(29076|29077|29080)'
29076  4140 git push ../demo
29077 29076 git-receive-pack ../demo
29080 29076 /data/data/com.termux/files/usr/libexec/git-core/git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress

bash-4.4$ lsof | egrep '(29076|29077|29080)' | grep 796531
29076	/data/data/com.termux/files/usr/libexec/git-core/git	pipe:[796531]
29076	/data/data/com.termux/files/usr/libexec/git-core/git	pipe:[796531]
29080	/data/data/com.termux/files/usr/libexec/git-core/git	pipe:[796531]

bash-4.4$ lsof | egrep '(29076|29077|29080)' | grep 457394
29076	/data/data/com.termux/files/usr/libexec/git-core/git	pipe:[457394]
29077	/data/data/com.termux/files/usr/libexec/git-core/git	pipe:[457394]
29080	/data/data/com.termux/files/usr/libexec/git-core/git	pipe:[457394]
```

**Comment by bukzor** [comment]
The same happens if I *pull* large packs served by termux git:

```
bash-4.4$ GIT_TRACE=2 GIT_SSH=/not/executable git pull ../brew
16:31:31.401360 git.c:344               trace: built-in: git 'pull' '../brew'
16:31:31.402027 run-command.c:631       trace: run_command: 'fetch' '--update-head-ok' '../brew'
16:31:31.411048 git.c:344               trace: built-in: git 'fetch' '--update-head-ok' '../brew'
16:31:31.411613 run-command.c:631       trace: run_command: 'git-upload-pack '\''../brew'\'''
16:31:31.427713 run-command.c:631       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
16:31:31.436060 run-command.c:631       trace: run_command: 'pack-objects' '--revs' '--thin' '--stdout' '--progress' '--delta-base-offset'
remote: 16:31:31.442525 git.c:344               trace: built-in: git 'pack-objects' '--revs' '--thin' '--stdout' '--progress' '--delta-base-offset'
remote: Counting objects: 107017, done.
```

This never proceeds.

**Comment by sdrausty** [comment]
@bukzor what is happening is called ['git bloat'](https://duckduckgo.com/?q=%22git+bloat%22) afaik.  This is a serious problem for maturing projects all across GitHub and beyond that use `git` for collaborative projects.

**Comment by bukzor** [comment]
Thanks for the vocabulary, but are you making an argument that this isn't a termux-packages bug?

**Comment by sdrausty** [comment]
@bukzor You are welcome, but please don't give me credit for this term.  I just passed on what I learned.
> are you making an argument that this isn't a termux-packages bug?

 On slow connections when git repositories are larger, `git` does not work at all.  It tries to do something, be it clone, pull or push, but does not succeed.  When the connection is good, git repository size is irrelevant.

**Comment by bergie** [comment]
I'm seeing this same issue, and not only with `git push`, but also with commands like `git gc`. They all get stuck in _Counting objects... done_

**Comment by bukzor** [comment]
>> are you making an argument that this isn't a termux-packages bug?

> On slow connections when git repositories are larger, git does not work at all. It tries to do something, be it clone, pull or push, but does not succeed. When the connection is good, git repository size is irrelevant.

I can't tell if this means "yes" or "no".

**Comment by bukzor** [comment]
@bergie: I suspect that may be a separate issue. Let's discuss on a fresh ticket.

**Comment by bergie** [comment]
@bukzor in my case the repository is also pretty large (https://github.com/noflo/noflo-ui). And I'm seeing the exact same behavior as you when I try to push. Just wanted to note that this is definitely not network-related since it happens also with `git gc` and not only with `git push`. But the symptoms seem to match yours.

**Comment by sdrausty** [comment]
@bukzor 
>> I can't tell if this means "yes" or "no".

>> On slow connections when git repositories are larger, git does not work at all. 

>> what is happening is called ['git bloat'](https://duckduckgo.com/?q=%22git+bloat%22) afaik.  This is a serious problem for maturing projects all across GitHub and beyond that use `git` for collaborative projects.

This is a `git` issue.  It is called [git bloat](https://duckduckgo.com/?&q=%22git+bloat%22+repository+size), and it should be https://github.com/git here somewhere.  On fast connections there are no errors, and ` git` works as expected.

**Comment by sdrausty** [comment]
> On slow connections when git repositories are larger, git does not work at all.

It consumes developer's bandwidth, resources and time on slow connections when the repository is big, and does not work as intended.  This issue has been around for some time, a resolution is still pending.

**Comment by sdrausty** [comment]
I am trying to reproduce this issue on a fast network connection by using bandwidth shaper `trickle` to throttle the bandwidth to 8kps.  **Unfortunately, this issue is not reproducible on a fast network with bandwidth throttling.**  This is probably due to network throughput overhead.  Even when throttling bandwidth on a fast network, there is a lot of network overhead.  On a slow network, there is no overhead since the bandwidth is completely utilized.  This is probably why a throttled connection works for `git`, but a slow unthrottled connection does not work with `git` on large git repositories.

**Comment by bukzor** [comment]
@sdrausty I don't see why you've assumed this has something to do with network speeds. I showed the problem reproduce on localhost, with networking 100% disabled: `GIT_TRACE=2 GIT_SSH=/not/executable git push ../demo`

**Comment by sdrausty** [comment]
@bukzor quite possibly, we are discussing two different git issues.  Here is the info requested:
```
$ git clone https://github.com/Linuxbrew/brew.git
Cloning into 'brew'...
remote: Counting objects: 108028, done.
remote: Total 108028 (delta 0), reused 0 (delta 0), pack-reused 108027
Receiving objects: 100% (108028/108028), 24.38 MiB | 3.15 MiB/s, done.
Resolving deltas: 100% (78864/78864), done.
$ cd brew
$ GIT_TRACE=2 GIT_SSH=/not/executable git push ../brew-clone
11:43:05.101561 git.c:344               trace: built-in: git 'push' '../brew-clone'
11:43:05.107386 run-command.c:631       trace: run_command: 'git-receive-pack '\''../brew-clone'\'''
11:43:05.165185 git.c:344               trace: built-in: git 'receive-pack' '../brew-clone'
fatal: '../brew-clone' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ pwd
/data/data/com.termux/files/home/tmp/brew
$ ls
CHANGELOG.md        LICENSE.txt         bin                 manpages
CODE_OF_CONDUCT.md  Library             completions
CONTRIBUTING.md     README.md           docker.test.yml
Dockerfile          _config.yml         docs
$ git pull
Already up to date.
```
Android 6 aarch64

**Comment by sdrausty** [comment]
@bukzor works as intended in Termux:
```
$ rm -rf brew/
$ git clone https://github.com/Linuxbrew/brew.git
Cloning into 'brew'...
remote: Counting objects: 108253, done.
remote: Compressing objects: 100% (153/153), done.
remote: Total 108253 (delta 120), reused 112 (delta 69), pack-reused 108028
Receiving objects: 100% (108253/108253), 24.57 MiB | 1.57 MiB/s, done.
Resolving deltas: 100% (78984/78984), done.
$ git init --bare brew-clone
Initialized empty Git repository in /data/data/com.termux/files/home/tmp/brew-clone/
$ cd brew
$ GIT_TRACE=2 GIT_SSH=/not/executable git push ../brew-clone
13:37:03.523252 git.c:344               trace: built-in: git 'push' '../brew-clone'
13:37:03.529179 run-command.c:631       trace: run_command: 'git-receive-pack '\''../brew-clone'\'''
13:37:03.584364 git.c:344               trace: built-in: git 'receive-pack' '../brew-clone'
13:37:03.588456 run-command.c:631       trace: run_command: 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
13:37:03.616910 git.c:344               trace: built-in: git 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
Counting objects: 108015, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (26496/26496), done.
13:37:07.261490 run-command.c:631       trace: run_command: 'index-pack' '--stdin' '--pack_header=2,108015' '--keep=receive-pack 20110 on localhost' '--show-resolving-progress' '--report-end-of-input' '--fix-thin'
remote: 13:37:07.297763 git.c:344               trace: built-in: git 'index-pack' '--stdin' '--pack_header=2,108015' '--keep=receive-pack 20110 on localhost' '--show-resolving-progress' '--report-end-of-input' '--fix-thin'
Writing objects: 100% (108015/108015), 24.42 MiB | 6.46 MiB/s, done.
Total 108015 (delta 78863), reused 108015 (delta 78863)
remote: Resolving deltas: 100% (78863/78863), done.
13:37:17.531662 run-command.c:631       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet' '--progress=Checking connectivity'
remote: 13:37:17.571020 git.c:344               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet' '--progress=Checking connectivity'
remote: Checking connectivity: 108015, done.
13:37:19.643970 run-command.c:631       trace: run_command: 'gc' '--auto' '--quiet'
remote: 13:37:19.680481 git.c:344               trace: built-in: git 'gc' '--auto' '--quiet'
To ../brew-clone
 * [new branch]          master -> master
$
```
Termux-packages arch:
aarch64
Android version:
7.1.1

**Comment by mikolajpp** [comment]
@sdrausty is almost certainly correct. 

@bukzor, to makr sure, you should not test it using github, which has bandwidth limits. 

The proper way to test and see that is not or is termux issue is to host the git repository on your own server.

**Comment by bergie** [comment]
@mikolajpp as [noted earlier](https://github.com/termux/termux-packages/issues/2271#issuecomment-376601601), the same problem can be triggered via `git gc`, so doesn't sound like this is a network issue

**Comment by mikolajpp** [comment]
@bergie I was talking specifically about ruling out git push malfunction. 

The `git gc`, `git push` could be the same issue, or not. 
So to perhaps rule out `git push` we should try to test it off github.

**Comment by bukzor** [comment]
`git push ../myclone` is already off github.

**Comment by timnolte** [comment]
I am also experiencing this same thing. In one case completely blowing away my fork and reapplying the changes ended up working. Now 9 just recently forked a repo and had created a branch. After a few days I need to sync my fork to continue development. After having merged the upstream changes my push has also gotten stuck. I've been struggling with this, and reaching out to GitHub for support. Now it seems as though this has been an ongoing issue.
