### ISSUE TITLE
tex live - Can't remove packages with tlmgr

### ISSUE THREAD

**Issue by yeahnope** [termux/termux-packages#2277]
It seems like removing packages with tlmgr is not possible:

```
~$ tlmgr remove scheme-full
mkdir: can't create directory '/tmp/cg-23786': No such file or directory
config.guess: cannot create a temporary directory in /tmp
/data/data/com.termux/files/usr/bin/tlmgr.ln: could not run /data/data/com.termux/files/usr/share/texlive/tlpkg/installer/config.guess, cannot proceed, sorry at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 246.
```

Is there any way to redirect tlmgr to use a different directory than /tmp ?
The file reported by "kpsewhich -var-value=TEXMFSYSCONFIG" does not exist. Is this normal?

**Comment by Grimler91** [comment]
Are you in a ssh shell or in a normal terminal?
Try `export TMPDIR=$PREFIX/tmp` and then remove it again.

It seems that TMPDIR isn't set, or at least that tlmgr isn't using it (and if it isn't using it we should patch it).

**Comment by yeahnope** [comment]
Thanks! I was using ssh. And yes, you are right, that was the problem, I wasn't aware that this made a difference for the variables that are set.

**Comment by Grimler91** [comment]
Not sure if it is a bug or a feature, but there has been some discussion about this before at https://github.com/termux/termux-packages/issues/1644.
