### ISSUE TITLE
apt error on termux

### ISSUE THREAD

**Issue by Muhaiminkp** [termux/termux-packages#2278]
ANONYMOUS:
# apt update
Hit:1 https://termux.net stable InRelease
Ign:2 https://hax4us.github.io/termux-tools termux InRelease
Hit:3 https://xeffyr.github.io/termux-x-repository termux InRelease
Get:4 https://hax4us.github.io/termux-tools termux Release [753 B]
Ign:5 https://hax4us.github.io/termux-tools termux Release.gpg
Fetched 753 B in 5s (143 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: No sandbox user '_apt' on the system, can not drop privileges

iam useing termux and itis runnuig ing sudo su becuse of permission problem in normal please help

**Comment by Hax4us** [comment]
You should not use `apt` as a superuser otherwise you will get different errors regarding permissions

**Comment by Hax4us** [comment]
Well it is just a warning ( Don't affect your termux experience) Don't Worry

**Comment by Grimler91** [comment]
Don't run apt as root. You are not suppose to, if you have permission errors then you should solve those instead.
See https://github.com/termux/termux-app/issues/542.

**Comment by Muhaiminkp** [comment]
@Hax4us can restore only my apt with out any missing of lib's and gem's 
my problem is 
W: No sandbox user '_apt' on the system, can not drop privileges

i think it want take from root permission if me correct!?
