### ISSUE TITLE
Libcurses missing from ncurses package

### ISSUE THREAD

**Issue by Hax4us** [termux/termux-packages#2279]
there is no any libcurses.so file in ncurses package why ?

**Comment by tomty89** [comment]
It's a symlink that has to been made manually downstream:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/ncurses#n49
And it has not been done in the Termux package.

**Comment by Hax4us** [comment]
So should I not create symlink also in termux ? It will be useful while compiling some packages

**Comment by tomty89** [comment]
You can make a PR for that if you find it important. It's a trivial task to do on demand though.

**Comment by fornwall** [comment]
As of version `6.1.20180331` of the ncurses package there is now a `libcurses.so -> libncurses.so` symlink setup for compatibility.
