### ISSUE TITLE
Can't install any pakages

### ISSUE THREAD

**Issue by Enigma817** [termux/termux-packages#2280]
apt install nano
Reading package lists... Done
Building dependency tree
Reading state information... Done
nano is already the newest version (2.9.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up wireshark (2.2.1) ...
ln: failed to create symbolic link '/data/data/com.termux/files/usr/lib/libGL.so.1': File exists
dpkg: error processing package wireshark (--configure):
 installed wireshark package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 wireshark
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by Enigma817** [comment]
I tried to install wireshark in it but it gave me error after that I can't install any packages in termux

**Comment by Hax4us** [comment]
@Enigma817 `apt remove wireshark` is working or not ?

**Comment by Enigma817** [comment]
It worked thank you
