### ISSUE TITLE
php shell_exec link error

### ISSUE THREAD

**Issue by lukeeey** [termux/termux-packages#2281]
I get this error when using `shell_exec` in php.

```
CANNOT LINK EXECUTABLE DEPENDENCIES: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit
```

**PHP**: 7.2.3
**Termux**: 0.60
**Android**: FireOS 5.6.0.1

**Comment by tomty89** [comment]
What exactly are you exexuting though? Seems like some 64-bit binary (while the CPU, or at least the installed Termux environment, is 32-bit)?

Or did it actually say `is 64-bit instead of 32-bit`?

**Comment by lukeeey** [comment]
I copied and pasted the error so no. My device is 64 bit and i executed the `nm` binary. It runs fine when executing from the terminal and it used to work fine.

**Comment by lukeeey** [comment]
if the termux env is 32 bit then idk how to fix it

**Comment by tomty89** [comment]
In any case, you can try `shell_exec('unset LD_PRELOAD; nm ... )`.

**Comment by vaguerant** [comment]
I see similar behavior on what I assume is the same platform (Fire HD 10 2017).

Attempted to `pip install pycrypto` and got the following:

```
    running build_ext
    running build_configure
    CANNOT LINK EXECUTABLE DEPENDENCIES: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-build-2_hv4cwh/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-2_hv4cwh/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-2_hv4cwh/pycrypto/setup.py", line 273, in run
        raise RuntimeError("chmod error")
    RuntimeError: chmod error

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-2_hv4cwh/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-lgcpyvlo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-2_hv4cwh/pycrypto/
```

Super lay user here, I have no idea whatsoever what I might do to resolve this.

**Comment by tomty89** [comment]
Does ` apt` and `file` tell you that termux-exec is aarch64 / 64 bit respectively?
```
$ apt show termux-exec
Package: termux-exec
Version: 0.3
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 36.9 kB
Homepage: https://github.com/termux/termux-exec
Download-Size: 2324 B
APT-Manual-Installed: yes
APT-Sources: https://termux.net stable/main aarch64 Packages
Description: An execve() wrapper to make /bin and /usr/bin shebangs work

$ file $PREFIX/lib/libtermux-exec.so
/data/data/com.termux/files/usr/lib/libtermux-exec.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
$
```

**Comment by lukeeey** [comment]
Its an arm package 32 bit and uname -a shows armv8l

`lscpu` displays AArch64 Processor rev 3 (aarch64)

Guess this is a termux bootstrap error

**Comment by vaguerant** [comment]
I think the issue here might be that the 2017 Fire HD 10 has a 64-bit processor but is only running 32-bit Android. I ran AnTuTu Benchmark which lists the Android version as 5.1.1 (32-bit).

**Comment by Grimler91** [comment]
We've had this issue a couple of times before. As @vaguerant put it, the situation is complicated. 

Easiest way to get rid of the error is to remove `$PREFIX/lib/libtermux-exec.so` and then open a new shell (it is restored if the package termux-exec is reinstalled), but the downside is that other, non-problematic, processes won't benefit from libtermux-exec.so. 
What the library does is to replace calls to /usr/bin/sh, /usr/bin/python and similar with /data/data/com.termux/files/usr/bin/sh, /data/data/com.termux/files/usr/bin/python, ...
See https://wiki.termux.com/wiki/Termux-exec and the [source code](https://github.com/termux/termux-exec/blob/master/termux-exec.c).

**Comment by lukeeey** [comment]
Cant we make the Termux app install 64 bit binary on the Fire? I know i can run 64 bit binaries and i once had a custom PHP build which was specifically for a PHP application that *only* supported 64 bit architectures (because of the mathmatical operations it did).

**Comment by luismene** [comment]
> I get this error when using `shell_exec` in php.
> 
> ```
> CANNOT LINK EXECUTABLE DEPENDENCIES: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit
> ```
> 
> **PHP**: 7.2.3
> **Termux**: 0.60
> **Android**: FireOS 5.6.0.1
