### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by fazha991** [termux/termux-packages#2285]
npm ERR! Cannot read property 'length' of undefine

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2018-03-26T10_39_41_391Z-debug.log

**Comment by Grimler91** [comment]
You will need to provide more information than that if anyone is suppose to be able to help. 
I'll re-open if you edit so that the post actually reports an issue or asks a question.

**Comment by Quasic** [comment]
@fazha991, is this related to #1798?
