### ISSUE TITLE
Python package installation error.

### ISSUE THREAD

**Issue by Jezwin** [termux/termux-packages#2286]
pkg install python
$ pkg install python
Hit:1 https://termux.net stable InRelease
Err:2 https://Auxilus.github.io termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A02DAB86B7A6E4BE
Reading package lists... Done
W: GPG error: https://Auxilus.github.io termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A02DAB86B7A6E4BE
E: The repository 'https://Auxilus.github.io termux InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (extras/binary-arm/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:3 and /data/data/com.termux/files/usr/etc/apt/sources.list:4
W: Target Packages (extras/binary-all/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:3 and /data/data/com.termux/files/usr/etc/apt/sources.list:4

**Comment by Grimler91** [comment]
As the error message says, you need to re-import Auxilus gpg key. 

See the wiki on how to do that: https://wiki.termux.com/wiki/Package_Management#Auxilus.
