### ISSUE TITLE
Metasploit-Package installation error.

### ISSUE THREAD

**Issue by Jezwin** [termux/termux-packages#2287]
dpkg: error processing package metasploit-framework (--configure):
 installed metasploit-framework package post-installation script subprocess returned error exit status 1
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by Auxilus** [comment]
@Jezwin sorry for inconvenience, but you're gonna have to stick with script installation untill I fix the repo

**Comment by Jezwin** [comment]
How's that? Could you provide a some link.

**Comment by vishnu14111** [comment]
dpkg: error processing package metasploit (--configure): installed metasploit package post-installation script subprocess returned error exit status 18                 
Errors were encountered while processing:
 metasploit                                            
 E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by prakashjivpm** [comment]
dpkg: error processing package metasploit-framework (--configure):
installed metasploit-framework package post-installation script subprocess returned error exit status 1
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by prakashjivpm** [comment]
dpkg: error processing package metasploit  (--configure):
installed metasploit package post-installation script subprocess returned error exit status 56
Errors were encountered while processing: metasploit
