### ISSUE TITLE
Error while installing eventmachine gem

### ISSUE THREAD

**Issue by lkdevil** [termux/termux-packages#2292]
after doing `gem install eventmachine` I am getting this error 
![img-20180328-wa0022](https://user-images.githubusercontent.com/20367238/38070481-cc5ea736-3339-11e8-8b5e-780362156acd.jpg)
![img-20180328-wa0021](https://user-images.githubusercontent.com/20367238/38070502-e8111342-3339-11e8-9029-89ef091d203a.jpg)
![img-20180328-wa0020](https://user-images.githubusercontent.com/20367238/38070539-126d03a8-333a-11e8-9af1-d16fbdef03cc.jpg)
![img-20180328-wa0019](https://user-images.githubusercontent.com/20367238/38070547-1e2d301e-333a-11e8-82a6-c298173362c6.jpg)
![img-20180328-wa0018](https://user-images.githubusercontent.com/20367238/38070577-4aa26dbc-333a-11e8-84b0-dd5df4f44378.jpg)

**Comment by Auxilus** [comment]
try building it locally :  
```
gem unpack eventmachine -v '1.0.9.1'
cd eventmachine-1.0.9.1
wget https://github.com/eventmachine/eventmachine/raw/master/eventmachine.gemspec
gem build eventmachine.gemspec
gem install eventmachine-1.0.9.1.gem
```

**Comment by drterminus** [comment]
thx @Auxilus this worked for me
i had the same error while installing eventmachine-1.2.5

**Comment by DATNIGGADEBO** [comment]
@Auxilus thanks bro

**Comment by lesid** [comment]
@Auxilus  that works whith me , thank you

**Comment by abduldully** [comment]
Hi..am trying to run ..bundle install ..and it tell me this..
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 4.2.10
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.3.0
Fetching nokogiri 1.8.2
Installing nokogiri 1.8.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native
extension.

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.2/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -r
./siteconf20180420-17561-ebwn9x.rb extconf.rb
--use-system-libraries
mkmf.rb can't find header files for ruby at
/data/data/com.termux/files/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.2
for inspection.
Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/nokogiri-1.8.2/gem_make.out

An error occurred while installing nokogiri
(1.8.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.8.2'`
succeeds before bundling.

In Gemfile:
factory_bot_rails was resolved to 4.8.2, which depends
on
    railties was resolved to 4.2.10, which depends on
actionpack was resolved to 4.2.10, which depends
on
actionview was resolved to 4.2.10, which depends
on
rails-dom-testing was resolved to 1.0.9, which
depends on
Nokogiri

**Comment by TommyPujol06** [comment]
@Auxilus it worked for me !!! 

> try building it locally :
> 
> ```
> gem unpack eventmachine -v '1.0.9.1'
> cd eventmachine-1.0.9.1
> wget https://github.com/eventmachine/eventmachine/raw/master/eventmachine.gemspec
> gem build eventmachine.gemspec
> gem install eventmachine-1.0.9.1.gem
> ```

**Comment by MnxCool** [comment]
@Auxilus it worked for me !!!
