### ISSUE TITLE
Metasploit-Package installation error.

### ISSUE THREAD

**Issue by Jezwin** [termux/termux-packages#2293]
pkg upgrade
pkg update
pkg install wget
wget https://Auxlius.github.io/metasploit.sh
bash metasploit.sh
cd metasploit-framework
bundle config build.nokogiri --use-system-libraries
bundle install
ls
./msfconsole
Working with this code comes up with infinite 'y's proceeding with 'Yes'.

**Comment by Auxilus** [comment]
A screenshot would help a lot :)

**Comment by Auxilus** [comment]
BTW msfconsole takes time to boot up for the first time...

**Comment by Jezwin** [comment]
It's not about the code I guess. Whenever I type 'yes' and enter it shows
up like this.

**Comment by Auxilus** [comment]
You mean something like this! 
![28660147-8b0dcc9c-72cf-11e7-8555-9b27e4a0e0f5](https://user-images.githubusercontent.com/23075789/38097971-68896d26-3394-11e8-8ba8-ea669a342fad.jpg)

**Comment by Jezwin** [comment]
Nope. It asks for a confirmation during the installation. When I type yes
it goes like that(My last screenshot).

**Comment by Jezwin** [comment]
It's the same whenever I type yes in Termux.

**Comment by Auxilus** [comment]
You didn't post screenshot..

**Comment by Jezwin** [comment]
![screenshot_20180329-211131](https://user-images.githubusercontent.com/16209021/38098539-f3ec6fde-3395-11e8-9b70-aba454573562.png)

**Comment by Auxilus** [comment]
Try reinstalling...

**Comment by Jezwin** [comment]
Hope you got that.

**Comment by Jezwin** [comment]
I've done already. The issue persists.

**Comment by sdrausty** [comment]
@Jezwin typing `man yes` gives:
```
YES(1)                           User Commands                          YES(1)

NAME
       yes - output a string repeatedly until killed

SYNOPSIS
       yes [STRING]...
       yes OPTION

DESCRIPTION
       Repeatedly output a line with all specified STRING(s), or 'y'.

       --help display this help and exit

       --version
              output version information and exit

AUTHOR
       Written by David MacKenzie.

REPORTING BUGS
       GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
       Report yes translation bugs to <https://translationproject.org/team/>

COPYRIGHT
       Copyright (C) 2017 Free Software Foundation, Inc.  License GPLv3+: GNU
       GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
       This is free software: you are free to change and redistribute it.
       There is NO WARRANTY, to the extent permitted by law.

SEE ALSO
       Full documentation at: <https://www.gnu.org/software/coreutils/yes>
       or available locally via: info '(coreutils) yes invocation'

GNU coreutils 8.29               December 2017                          YES(1)
```
Ditto for `info yes`.  It says the same thing.  Try some other commands too.  Like `info ls`, `man df` and similar.  If you run out of commands to try, try TAB TAB.  Tap the TAB key twice to see all your commands.

**Comment by Jezwin** [comment]
![screenshot_20180329-212659](https://user-images.githubusercontent.com/16209021/38099343-fcc90430-3397-11e8-80dd-609518ecb440.png)

**Comment by sdrausty** [comment]
@Jezwin `pkg install coreutils`

**Comment by Jezwin** [comment]
That works. But the problem persist with the y thing.

**Comment by Jezwin** [comment]
Is there another way to install metasploit?

**Comment by Jezwin** [comment]
Okay that works. How to install metasploit btw?

**Comment by Auxilus** [comment]
wiki.termux.com/wiki/Metasploit_Framework

**Comment by Grimler91** [comment]
Report the error at the repo where the script is from instead (i.e. https://github.com/Auxilus/Auxilus.github.io). And see #715.
