### ISSUE TITLE
Repository not signed error.

### ISSUE THREAD

**Issue by Jezwin** [termux/termux-packages#2295]
![screenshot_20180329-215358](https://user-images.githubusercontent.com/16209021/38100775-ef7d7d0c-339b-11e8-8451-7ee657797aa0.png)

**Comment by Auxilus** [comment]
As @Grimler91 said, issues regarding my repo should be on github.com/Auxilus/Auxilus.github.io

**Comment by Auxilus** [comment]
Also don't use the repo method.. It's broken..
