### ISSUE TITLE
Error message when starting htop

### ISSUE THREAD

**Issue by quincunx** [termux/termux-packages#2297]
The tool "htop" used to work fine on my mobile phone (Nokia 6 with Android 8) until it got updated to version 2.1 recently.

It does not start at all - just the error message "Cannot open /proc/stat: Permission denied" is shown. Reinstalling the package did not help to solve the problem.

**Comment by its-pointless** [comment]
Its an android limitation nothing we can do...

**Comment by quincunx** [comment]
But it worked with htop version 2.0.2 - why not keeping it at this version, then?
