### ISSUE TITLE
Import module Crypt is broken in Python 3.5 #230

### ISSUE THREAD

**Issue by tinydynamite00** [termux/termux-packages#230]
#245

The crypt module in Python 
- Python 3.5.1 (default, Feb 29 2016, 01:52:42)
[GCC 4.9 20140827 (prerelease)] on linux

throws the following error:

>help> crypt
problem in crypt - ImportError: dlopen failed: cannot locate symbol "crypt" referenced by "/data/data/com.termux/files/usr/lib/python3.5/lib-dynload/_crypt.cpython-35m-arm-linux-gnueabi.so"...<

Similar failure importing crypt module from the py interpreter:
> ->crypt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'crypt' is not defined

Contrary to calling other modules and functions at the Python prompt, e.g.
> -> hash
_built-in function hash_

Is there any way upstream Salt is ready for porting to arm?

**Comment by fornwall** [comment]
Thanks, this has been fixed in version `3.5.1-4` which you can update to by running

    apt update && apt upgrade
