### ISSUE TITLE
Operation not permitted in prooted environment

### ISSUE THREAD

**Issue by lkdevil** [termux/termux-packages#2307]
Recently I installed Kali nethunter like as Arch Linux in termux using proot 
But after `apt-get upgrade` I am getting this error 
```
Unpacking perl (5.26.1-5) over (5.26.0-8) ...
dpkg: error processing archive /tmp/apt-dpkg-install-7cd3oB/0-perl_5.26.1-5_arm64.deb (--unpack):
 unable to securely remove '/usr/bin/corelist.dpkg-tmp': Operation not permitted
Preparing to unpack .../1-perl-modules-5.26_5.26.1-5_all.deb ...
```
And above error is coming each time whenever any package is trying to upgrade itself it means that if any package i.e, perl is already installed but I am trying to upgrade perl .

**Above error is only happening in aarch64 devices not in armhf devices**

Any workaround suggestions ?

**Comment by Grimler91** [comment]
Are you in a ssh-shell? Try `export TMPDIR=/data/data/com.termux/files/usr/tmp`.

**Comment by lkdevil** [comment]
Yes

**Comment by lkdevil** [comment]
I found that `apt` was trying to remove `corelist.dpkg-tmp` from `/usr/bin` while upgrading perl and it is root cause because I tried to remove manually but can't remove 
```
rm /usr/bin/corelist.dpkg-tmp
rm: cannot remove '/usr/bin/corelist.dpkg-tmp': Operation not permitted
```
And I got very strange output of `ls -l` in `/usr/bin`
```
l?????????? ? ?    ?          ?            ? corelist.dpkg-tmp
```
all files have correct permissions with user (root ) and group (root) but idk why above file has no any user I'd and group I'd ?

**Comment by xeffyr** [comment]
This is due to proot's problems with link2symlink enabled.
