### ISSUE TITLE
Add rust

### ISSUE THREAD

**Issue by freetnt5852** [termux/termux-packages#2309]
Can you guys add Rust programming language I've been trying to follow their website but for some reason curl doesn't work the same the thing i was running is `curl https://sh.rustup.rs -sSf | sh` if you add rust in the packages that would simplify the installing like it did for nodejs python and ruby for me, Thanks.

**Comment by Grimler91** [comment]
I believe it's available from @its-pointless repo. See instructions on how to add it here: https://wiki.termux.com/wiki/Package_Management#its-pointless_.28live_the_dream.29

**Comment by Grimler91** [comment]
See also https://github.com/termux/termux-packages/issues/261.
