### ISSUE TITLE
Package request: GNU Forth

### ISSUE THREAD

**Issue by gwenhael-le-moine** [termux/termux-packages#231]
https://www.gnu.org/software/gforth/

**Comment by Grimler91** [comment]
It's been a while since this has been updated, but gforth is now available from [its-pointless community repository](https://github.com/its-pointless/its-pointless.github.io). See https://wiki.termux.com/wiki/Package_Management#its-pointless_.28live_the_dream.29 for instructions on how to subscripe to the repo.

**Comment by Atavic** [comment]
:+1: Asking to close this issue.

**Comment by sdrausty** [comment]
@Grimler91 This package must be built from `aur` to work in Arch Linux Termux PRoot.  https://en.wikipedia.org/wiki/Gforth is on Wikipedia.  Termux is not https://github.com/termux/termux-packages/issues/1930 "Please share your thoughts on the matter ..." as the notice requests.

**Comment by Grimler91** [comment]
Reopening this with the goal of adding gforth to the main repo.

**Comment by sdrausty** [comment]
GNU rocks!  @Grimler91 Are you familiar with https://www.gnu.org/distros/free-distros.en.html  Especially:
> If you maintain a distribution that follows the [Free System Distribution ](https://www.gnu.org/distros/free-system-distribution-guidelines.html) and would like to be listed here, please write to <webmasters@gnu.org> with an introduction and a link to the project Web site.

**Comment by its-pointless** [comment]
If anyone is attempting to get this working as a cross compiled its probably better of to use the development version seeing as it has some android support already. It also needs gcc as in not clang as far as i can tell.

**Comment by farvardin** [comment]
It's not working, i got this error:

```
$ gforth 
gforth: image gforth.fi doesn't seem to be a Gforth (>=0.6) image.
```

0.7.3 is also an outdated version.
The 0.7.9 developer version has android support, but as this one is using opengl it's less easy to use in comparison to a termux version (no copy/paste)

**Comment by xtkoba** [comment]
@farvardin Please file a new issue for that. Do not reuse a closed one.
