### ISSUE TITLE
htop tree view not working for root

### ISSUE THREAD

**Issue by jdgregson** [termux/termux-packages#2313]
When I run htop as the default user I am able to press `t` to see processes in tree view as intended. When I run htop as root, pressing `t` causes the list of processes to disappear completely until I press `t` again.

I have confirmed that the termux app and all packages are up to date. The issue also occurs in Termux-Float.

It may be important to note that I am using st42's [termux-sudo](https://github.com/st42/termux-sudo) to run htop as root.

Details --
Phone: Nexus 6
Android: 7.1.2
Root: SuperSU
Rom: PureNexus
Kernel: B14ckB1rd

**Comment by xeffyr** [comment]
@jdgregson Do you still have the same problem with running as non-root ?

On htop v2.2.0 tree view is working:
![screenshot_20180421-142449](https://user-images.githubusercontent.com/25881154/39083639-2afeec40-4570-11e8-92c8-94f0187314be.png)

I'm running htop as regular user as I no longer use/have root.

**Comment by sdrausty** [comment]
![screenshot_2018-04-21-11-56-48](https://user-images.githubusercontent.com/27742457/39086145-5f458bf4-455b-11e8-88f9-23d39879cfc9.png)

`htop` t mode test results : OK (Android 5-7 armv7-armv8)

@jdgregson you are most probably experiencing initial side effects of rooting an Android device.

**Comment by xeffyr** [comment]
@sdrausty He probably use version 2.1.0. I have the same problem on it, but after update everything ok.

**Comment by sdrausty** [comment]
No idea regarding kernel version @xeffyr 

@jdgregson run `termux-info` and post the output;  Is the kernel on your device version 2.1.0?

**Comment by sdrausty** [comment]
No idea regarding kernel version @jdgregson has.
> The root account is reserved for system administration

Is it necessary to run `htop` as system administrator @xeffyr ?

@jdgregson run `termux-info` and post the output;  Is the kernel on your device version 2.1.0?

**Comment by sdrausty** [comment]
@xeffyr I am not sure why you edited your comment; Can you explain why you edited it?

I edited my previous comment too.  Why did you not simply post a subsequent comment to maintain continuity of this issue?  Do not force me to edit my comments to maintain thread continuity because you edited the comment that I answered from you.  Maintaining issue continuity is important for our users and Termux @xeffyr You should know this.  After all, you are a contributor.

**Comment by xeffyr** [comment]
@sdrausty 
1. I have a right to edit my comments.
2. I just added a line 'I guess this issue could be closed.'

As I see, you are like to criticize users last time...

**Comment by sdrausty** [comment]
> As I have asked you in another thread, your answers to questions are welcome.  Would you care to share an answer regarding development?  Your opinions of me are your personal viewpoint, and your are welcome to share those too.

*From https://github.com/termux/termux-packages/pull/2306#issuecomment-382207955


> If it works in Termux PRoot, shouldn't it work easily in just Termux too?

From that thread, question unanswered still.

> Is it necessary to run htop as system administrator?

From this thread, question unanswered, too.

>> Your opinions of me are your personal viewpoint, and your are welcome to share those too.

Please stop your aggressive commenting towards me asap.  They are unproductive for development.

**Comment by sdrausty** [comment]
Was the reasoning behind editing SE flaming @xeffyr ?  imo yes

**Comment by sdrausty** [comment]
Was the reasoning behind editing SE flaming @xeffyr ?  imo yes

@xeffyr You use the same technique SE tactic that @tomty89 uses.

**Edit other users comments into foot-in-mouth disease by reediting comments.**

This is unproductive for rapid prototyping.  Do you agree?

**Comment by sdrausty** [comment]
> As I have asked you in another thread, your answers to questions are welcome.  Would you care to share an answer regarding development?  Your opinions of me are your personal viewpoint, and your are welcome to share those too.

*From https://github.com/termux/termux-packages/pull/2306#issuecomment-382207955


> If it works in Termux PRoot, shouldn't it work easily in just Termux too?

From that thread, question unanswered still.

> Is it necessary to run htop as system administrator?

From this thread, question unanswered, too.

>> Your opinions of me are your personal viewpoint, and your are welcome to share those too.

Please stop your aggressive commenting towards me.

Was the reasoning behind editing SE flaming? imo yes

@xeffyr You use the same technique SE tactic that @tomty89 uses.

**Edit other users comments into foot-in-mouth disease by reediting comments.**

This is unproductive for rapid prototyping.  Do you agree?

**Comment by sdrausty** [comment]
@xeffyr You use the same technique SE tactic that @tomty89 uses.

Edit other users comments into foot-in-mouth disease by reediting comments.

This is unproductive for rapid prototyping. Do you agree?

**Comment by jdgregson** [comment]
@xeffyr, No, when running as the default non-root user I was able to use tree view as expected. However, since I am using Android 7.1.2, that user is only able to see termux processes, so there is little reason to use it for htop.

**Comment by xeffyr** [comment]
@jdgregson did you run ```pkg upgrade``` ? I have same problem on version 2.1.0 but on 2.2.0 everything is ok.  I'm on android 7.0.

**Comment by jdgregson** [comment]
@xeffyr Yes, I ran `pkg updrage` and also confirmed that all Termux apps were up to date in the play store. The issue persisted.

I had to revert my phone to factory settings a couple weeks back and have yet to re-root. I will root again soon and see if the issue is still occurring.

**Comment by RSCipher001** [comment]
It is working for me on rooted phone. I am using `tsu` to become root.

**Comment by sdrausty** [comment]
Posted https://duckduckgo.com/?q=linux+permissions for reference.

**Comment by sdrausty** [comment]
> probably experiencing initial side effects of rooting an Android device along with the abuse of admin privileges. The root account is reserved for system administration. There is no valid reason to run htop as admin; 

Posted https://duckduckgo.com/?q=linux+permissions for reference.

**Comment by xeffyr** [comment]
In recent versions of `htop` the issue seems to be either solved or doesn't happen anymore. 

Tested as `tsu`, st42's termux-sudo and regular shell:
[![asciicast](https://asciinema.org/a/PNnmVcrORP0WFFYUEiGBrzenT.svg)](https://asciinema.org/a/PNnmVcrORP0WFFYUEiGBrzenT)
