### ISSUE TITLE
How to get back pkg

### ISSUE THREAD

**Issue by freetnt5852** [termux/termux-packages#2319]
Hi i installed something that its executable is also pkg, i was dumb and forgot this is also called pkg and stopped working, i uninstalled that but pkg is still broken, is there a way to fix it or reinstall? Don't feel like reinstalling termux and re doing everything.

**Comment by xeffyr** [comment]
Try to do `apt install --reinstall termux-tools`.

**Comment by freetnt5852** [comment]
Thanks that fixed it.
