### ISSUE TITLE
Package request: mitmproxy and build-essentials

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#232]
In order for us to migrate package suggestions to labeled issues I'm opening this here. 
This package was originally requested here: https://github.com/termux/termux-app/issues/34

**Comment by jamesharrington** [comment]
Hey was there ever any progress on this??

**Comment by Mouradif** [comment]
I wonder as well, for now I am stuck at 

`
build/temp.linux-armv7l-3.6/_openssl.c:434:10: fatal error: 'openssl/opensslv.h' file not found
    #include <openssl/opensslv.h>
             ^~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'arm-linux-androideabi-clang' failed with exit status 1
`

**Comment by Grimler91** [comment]
@Mouradif opensslv.h is provided by the package openssl-dev so do `pkg install openssl-dev`

**Comment by xeffyr** [comment]
Package is now available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install build-essential
```
