### ISSUE TITLE
zsh: missing pcre module

### ISSUE THREAD

**Issue by msva** [termux/termux-packages#2321]
Hi there!
I've found that zsh package misses it's modules.
This results in things like that:
```
_zsh_highlight_main_highlighter_highlight_argument:51: failed to load module: zsh/pcre
_zsh_highlight_main_highlighter_highlight_argument:51: -pcre-match not available for regex
```
And even:
```
$  zsh -f
$ setopt rematchpcre
$ [[ 'foo→bar' =~ .([^[:ascii:]]). ]]; print $MATCH
zsh: failed to load module: zsh/pcre
zsh: -pcre-match not available for regex
```

Actually, I faced similar issue when I tried to build zsh as static binary (with compiled-in modules), and the problem was in the fact that libpcre used jit feature, which required `pthread` library (and zsh's buildsystem doesn't link zsh binary against it).

But I performed some checks over zsh in termux and it looks like it is not the issue, but modules are really missing.

So, can you fix the package, please?

**Comment by fornwall** [comment]
Thanks to @tomty89 pcre is now enabled in the latest version `5.5-1` of the zsh package, to which you can update by running `pkg up`.
