### ISSUE TITLE
package request: ccons

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#2328]
The goal of ccons is to provide an interactive console for the C programming
language.

The project builds on top of clang and llvm.

https://github.com/asvitkine/ccons

**Comment by vishalbiswas** [comment]
That repository hasn't been updated since 2015 and is heavily out of sync with latest llvm. So, this looks like undoable unless upstream gets updated.

**Comment by xeffyr** [comment]
Closing as [ccons](https://github.com/asvitkine/ccons) is outdated.
