### ISSUE TITLE
tmux will not run

### ISSUE THREAD

**Issue by matt812** [termux/termux-packages#2334]
I have installed tmux on termux.

When I run tmux, it does not open and gives me the error: "open terminal failed: not a terminal".

Any idea what I might be doing wrong?

**Comment by Neo-Oli** [comment]
For some reason you are in a non-interactive shell. That normally shouldn't happen. Did you put anything weird in your .bashrc or set a weird alternative shell or something? Try restarting termux and see if it helps.

**Comment by matt812** [comment]
My .bashrc is frankenstein's monster.  

I'll try emptying it and adding lines back one at a time until I can figure out what is causing this.

Also, in Termux:
When I open the program for the first time, which shell scripts run in that terminal?
And, when I open a new session, which shells scripts run?
And, when I connect over ssh, which shell scripts run?
And, when I run tmux, which shell scripts run inside of it?

Maybe some things are running that I did not expect to run.  (I migrated my scripts from a mac.)

I guess I can find this out using some creating investigation, too.

**Comment by matt812** [comment]
Okay, so I did some research regarding which scripts get run where.  
Here is what I found (and note that the ONLY one that is consistent between the OSes is screen!).

```
|----------------------------------------+----------+---------+---------------|                      
| Command                                | OS       | .bashrc | .bash_profile |                      
|----------------------------------------+----------+---------+---------------|                      
| ssh without command (ssh machine) into | Termux(1)| X       | X             |                      
|                                        | Macos(2) |         | X             |                      
|----------------------------------------+----------+---------+---------------|                      
| ssh with command (ssh machine ls) into | Termux   |         | X             |                      
|                                        | Macos    | X       |               |                      
|----------------------------------------+----------+---------+---------------|                      
| tmux within                            | Termux(3)| X       | X             |                      
|                                        | Macos    | X       |               |                      
|----------------------------------------+----------+---------+---------------|                      
| screen within                          | Termux   | X       |               |                      
|                                        | Macos    | X       |               |                      
|----------------------------------------+----------+---------+---------------|                      
| scp into                               | Termux   |         | X             |                      
|                                        | Macos    | X       |               |                      
|----------------------------------------+----------+---------+---------------|                      
| new session from within                | Termux(4)| X       | X             |                      
|                                        | Macos    |         | X             |                      
|----------------------------------------+----------+---------+---------------|                      
1. GNU bash, version 4.4.19(1)-release (arm-unknown-linux-androideabi)
2. GNU bash, version 4.4.18(1)-release (x86_64-apple-darwin17.3.0)
3. where I get "open terminal failed: not a terminal", which I do NOT get with 1 & 4, which also run both scripts)
```

When both scripts are run, .bashrc is always run first.  At least that is consitent. ;)

So, I don't know what is deciding when to run these scripts, but they are definitely different for the different OSes!

I have only 1 of each script, which I use on all of my machines (which I keep synced), and there are very few lines that differ between the OSes, so I use a small if/else block to test the OS to see which half to run for Macos vs Termux.

I imagine that there is something in either the .bashrc or .bash_profile that tmux doesn't like, but how to remedy it is difficult to say when the different bashes behave so differently.

**Comment by matt812** [comment]
Okay, so I think this issue goes beyond tmux and my configuration.

If I completely remove .bashrc and .bash_profile, then I run this:
```
ssh -p 8022 termuxdeviceip 'nano somefile.txt'
Error opening terminal: unknown.
```

I don't have this issue on any other OS.

So, doesn't this seem like some sort of default OS/shell configuration issue?
