### ISSUE TITLE
Bionic and threads

### ISSUE THREAD

**Issue by vaites** [termux/termux-packages#234]
Hi

I'm working on some packages that need a complete POSIX implementation of threads, and Bionic library lacks some functions (like pthread_cancel). There are some workarounds (using pthread_kill instead of pthread_cancel) but didn't worked for me (app hangs). Searching for a solution I found [this repository](https://github.com/tux-mind/libbthread/). I think that adding this to toolchain (as tmpfile fix) would make many packages work without modification. My proposal is reasonable or is there a better alternative?.

Thanks!

**Comment by truboxl** [comment]
Closing.
I believe maintainers now know better in patching their packages by replacing the calls or better yet remove the calls altogether.
There are also reports of unreliability: https://github.com/termux/termux-packages/issues/4378#issuecomment-538683862
There is no need to introduce another library as a dependency.
