### ISSUE TITLE
exa segmentation fault

### ISSUE THREAD

**Issue by Ublimjo** [termux/termux-packages#2351]
$ exa  
Segmentation fault

**Comment by Grimler91** [comment]
Please open an issue at the repository you installed exa from instead.

**Comment by Ublimjo** [comment]
electrum/termux 3.0.5 all.    
elfutils/stable 0.170 i686.      
elfutils-dev/stable 0.170 i686    
elinks/stable,now 0.13.GIT-1 i686.    
emacs/stable 25.3-2 i686.   
erlang/stable 20.3.2 i686.   
espeak/stable 1.49.2-1 i686.     
espeak-dev/stable 1.49.2-1 i686.    
**exa/termux,now 0.8.0 i686 [installed]**.                                             
expect/stable 5.45.3 i686                                                            
expect-dev/stable 5.45.3 i686                                                        
fdupes/stable 1.6.1 i686                                                             
feh/termux,now 2.25.1 i686 [installed,automatic]                                     
ffmpeg/stable,now 3.4.2 i686 [installed]                                             
ffmpeg-dev/stable 3.4.2 i686                                                         
fftw/stable,now 3.3.7 i686 [installed,automatic]

**Comment by its-pointless** [comment]
This belongs in my gcc

**Comment by Grimler91** [comment]
Yeah, running `apt show exa` gives
```
Package: exa
Version: 0.8.0
Maintainer: @its-pointless
Installed-Size: 1012 kB
Depends: tzdata
Homepage: https://the.exa.website/
Download-Size: 438 kB
APT-Sources: https://its-pointless.github.io/files termux/extras arm Packages
Description: exa is a modern replacement for ls
```
