### ISSUE TITLE
spawn.h, libsigsegv missing

### ISSUE THREAD

**Issue by mikolajpp** [termux/termux-packages#2355]
Hello, first of, thanks for this amazing project.

Second, is there a reason why sigsegv library and headers, as well as spawn.h libc header are missing?

I am trying to build some program which requires those. How can this be fixed?

**Comment by Grimler91** [comment]
The most general answer to why a package is missing is that no one had bothered or had the time to port it yet. 
However, in this particular case you can get libsigsegv from [its-pointless repo](https://wiki.termux.com/wiki/Package_Management#its-pointless_.28live_the_dream.29). Building it was trivial, I have an old build.sh script [here](https://github.com/Grimler91/termux-packages/tree/xindy/packages/libsigsegv).

There is a comment in the [build-package.sh](https://github.com/termux/termux-packages/blob/2043cdec2ccf27a0fd309a9300bd09a7da498e50/build-package.sh#L684) script indicating that spawn.h is only available for android 8.1 and later, but I don't know the details here.

**Comment by tomty89** [comment]
https://android.googlesource.com/platform/bionic/+/HEAD/docs/status.md

Only bionic libc on Android P (which is still in preview) would support functions exposed in spawn.h.

**Comment by mikolajpp** [comment]
@Grimler91 it seems the libsigsegv from its-pointless repo is missing? I have added the repo, but pkg does not turn any package with that name...

**Comment by Grimler91** [comment]
@mikolajpp I can see the package for all arches in [the file structure](https://github.com/its-pointless/its-pointless.github.io/tree/master/files/dists/termux/extras) so it should be available if you've added the repo and run apt update.

**Comment by its-pointless** [comment]
not quite
https://github.com/termux/termux-packages/blob/master/packages/ninja/src-posix_spawn.c.patch
 This implementation of posix_spawn is only suitable for the needs of dhcpcd but it could easily be extended to other applications. */
it implements a less than perfect implementation. Its not just the header.
