### ISSUE TITLE
Package request: apt-transport-tor

### ISSUE THREAD

**Issue by monoidic** [termux/termux-packages#2359]
In direct response to [this](https://github.com/termux/termux-packages/issues/2358):
Plus, Tor for the sake of Tor. It exists upstream already as well.

**Comment by xeffyr** [comment]
I have this package in my repository: [termux-extra-packages/apt-transport-tor](https://github.com/xeffyr/termux-extra-packages/blob/master/packages/apt-transport-tor/build.sh). Maybe this should be available here instead ?

**Comment by monoidic** [comment]
Oh, cool, thanks, that seems to work.

**Comment by fornwall** [comment]
Thanks to @xeffyr there is now a package available - install it with `pkg install apt-transport-tor`!
