### ISSUE TITLE
failed to add code"printk"  in kernel 

### ISSUE THREAD

**Issue by shuigang100** [termux/termux-packages#236]
I'm trying to debug my kernel source code ,but I can't find the output of "my own printk"  except for the origional  ones , what do I missed?   I‘m sure my log level is higher than the console ,and I read the log in file "proc/kmsg",  beg for some help pls

**Comment by fornwall** [comment]
Sorry, this is nothing Termux-specific, you are probably better off asking at a forum for Linux kernel development.
