### ISSUE TITLE
how can I install hashcat in termux?

### ISSUE THREAD

**Issue by huitc** [termux/termux-packages#2361]
I hope anyone can provide a detailed installation tutorial

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by xeffyr** [comment]
Get this: https://github.com/termux/termux-packages/files/1461226/hashcat_debs.zip
Downloaded zip file will contain deb files for AArch64.

**Comment by huitc** [comment]
$ hashcat -b
hashcat (v4.0.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

clGetPlatformIDs(): CL_INVALID_VALUE

Started: Wed Apr 25 19:03:46 2018
Stopped: Wed Apr 25 19:03:46 2018

**Comment by xeffyr** [comment]
> clGetPlatformIDs(): CL_INVALID_VALUE

hashcat is incompatible with your device.

**Comment by vida1j** [comment]
How to fix it?
hashcat v.4.0.0
device = aarch64
![hashcat_termux](https://user-images.githubusercontent.com/39262574/40908646-5b6b4882-680d-11e8-8b7d-7ab7a933296d.png)

**Comment by xeffyr** [comment]
@vida1j No idea. On some devices it works on others not, it even depends on Android version. OpenCL version of hashcat is totally unsupported in Termux.

**Comment by XSecr3t** [comment]
Just try install another tools like CMSmap for good hashing..

**Comment by remo7777** [comment]
![Screenshot_20190703-152051](https://user-images.githubusercontent.com/28594846/60582434-6a982a80-9da6-11e9-9791-41820fed06ee.jpeg)

**Comment by xeffyr** [comment]
I don't know which version you are trying to use but:
* Upgrade your packages. `pkg upgrade`.
* Make sure that hashcat is installed from `unstable-repo`.
* Hashcat is not working on Android 5/6.

**Comment by acdc12** [comment]
Is there any way to fix the error:
![Screenshot_20200616_164540](https://user-images.githubusercontent.com/61262953/84753064-1dca5580-aff1-11ea-8045-616b24986eac.jpg)

**Comment by Mascaraneous** [comment]
Type
Pkg install unstable-repo

After that 
Pkg install hashcat
![Screenshot_20200929-170914](https://user-images.githubusercontent.com/72079565/94554141-43fdc380-0277-11eb-9a9b-b866e40b7ed7.jpg)

**Comment by LAVINIA000** [comment]
I have unable locate to package hashcat error

**Comment by kcubeterm** [comment]
Hashcat has removed because it is related to hacking. 
https://github.com/termux/unstable-packages/commit/ae1f6f2acf81978d25cb895f958459f75e6737e9

Package policy has changed now

**Comment by xeffyr** [comment]
> I have unable locate to package hashcat error

Related to \-\-\> https://wiki.termux.com/wiki/FAQ#Where_are_Metasploit_and_Hydra_packages
