### ISSUE TITLE
mc points mistakenly to /usr/bin/unzip 

### ISSUE THREAD

**Issue by konijn** [termux/termux-packages#2362]
Greetings,

when trying to view the contents of a zip file in mc,
I get an error that /usr/bin/unzip is not found.
This makes sense, unzip is not there.

I assume mc needs to be patched to have it point to the Termux location of unzip.

**Comment by fornwall** [comment]
Thanks for reporting!

This is now available in version 4.8.20-2 of the mc package, to which you can update to by running `pkg up`.

**Comment by konijn** [comment]
Thanks, this works. For future visitors: also install unzip with `pkg install unzip`
