### ISSUE TITLE
When I command or use chmod for new app I get this :" No such file or directory found" can anyone please help I'm a beginner?

### ISSUE THREAD

**Issue by alithemanwhosoldtheworld** [termux/termux-packages#2365]

**Comment by xeffyr** [comment]
> chmod for new app

@alithemanwhosoldtheworld Copy and paste your command here as I can't figure out what you are trying to chmod.

**Comment by alithemanwhosoldtheworld** [comment]
Chmod +x toolss.py
Cd instahack
Cd fbbrute
all of these will face the same bash

**Comment by xeffyr** [comment]
Files 'toolss.py', 'instahack' 'fbbrute' exists ?
Check with ```ls -ld 'toolss.py', 'instahack' 'fbbrute'```

**Comment by alithemanwhosoldtheworld** [comment]
Well doesn't this website provide you woth instahack git clone?

**Comment by alithemanwhosoldtheworld** [comment]
@Grimler91 thanks a lot.
I also realised that I can install almost none of Python's Modules such as pycares or cffi or proxybroker...you got anything for that?

**Comment by Grimler91** [comment]
@alithemanwhosoldtheworld can't tell without knowing which error you run into. 

You either lack dependencies (indicated by errors saying something about missing headers (i.e. files with .h extension)) or the package require some patches to work in termux. 

Many python packages have already been discussed in previous issues so it's a good idea to search the github issues if you run into problems. 
Here's one issue for cffi: https://github.com/termux/termux-packages/issues/1208.

**Comment by alithemanwhosoldtheworld** [comment]
Thanks

**Comment by Mumtaz22** [comment]
When I command or use chmod for new app I get this :" No such file or directory found" can anyone please help

**Comment by Mumtaz22** [comment]
When I command or use chmod for new app I get this :" No such file or directory found .
Help me
