### ISSUE TITLE
how to rename files in kernel

### ISSUE THREAD

**Issue by shuigang100** [termux/termux-packages#237]
I want to rename several  file in kernel , I know file's location ,but I don't know how ,  are there any functions to use in kernel lib?    can I use "vfs_rename" in  "fs/namei.c"?

**Comment by fornwall** [comment]
Sorry, this is nothing Termux-specific, you are probably better off asking at a forum for Linux kernel development.

**Comment by shuigang100** [comment]
ok thank you

**Comment by shuigang100** [comment]
any advices about forum of linux kernel development?

**Comment by fornwall** [comment]
Perhaps http://forum.kernelnewbies.org/?

**Comment by shuigang100** [comment]
thanks
