### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by R00TD4nZ** [termux/termux-packages#2378]
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.1/arm-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.1 /data/data/com.termux/files/usr/lib/perl5/5.26.1/arm-android /data/data/com.termux/files/usr/lib/perl5/5.26.1 .) at rev.pl line 11.
BEGIN failed--compilation aborted at rev.pl line 11.

**Comment by xeffyr** [comment]
> you may need to install the LWP::UserAgent module

The perl suggests you to install LWP::UserAgent module to fix this error.

**Comment by onlurking** [comment]
@R00TD4nZ, can you try those commands?
```bash
perl -MCPAN -e 'install Bundle::LWP'
perl -MCPAN -e 'install LWP::UserAgent'
```

You should check [this site too](http://lwp.interglacial.com/ch01_03.htm).

**Comment by putkijam** [comment]
Can't locate LWP/UserAgent.pm in @inc (you may need to install the LWP::UserAgent module) (@inc contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.1/arm-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.1 /data/data/com.termux/files/usr/lib/perl5/5.26.1/arm-android /data/data/com.termux/files/usr/lib/perl5/5.26.1 .) at rev.pl line 11.
BEGIN failed--compilation aborted at rev.pl line 11.
