### ISSUE TITLE
package request #libportaudio-dev

### ISSUE THREAD

**Issue by Adarshreddyash** [termux/termux-packages#2385]
Need **libportaudio-dev** for termux

**Comment by its-pointless** [comment]
iv looked into this before. The android support for libportaudio uses the java to use it its a tad more involved than just compiling.
On the other hand there is a pulseaudio out for portaudio that isnt in the stable release branch. Unfortunately i can't get it to work in termux.

**Comment by Adarshreddyash** [comment]
Iam on a project to create personal assistant for mobile.. can i get alternative for libportaudio

**Comment by twaik** [comment]
Closed by 3308c31bb4b65f4a43d688f2abb692b456e656d2
