### ISSUE TITLE
"pass -c" hangs

### ISSUE THREAD

**Issue by DoktorStein** [termux/termux-packages#2388]
I was able to successfuly setup a `pass` password store and insert/retrieve pwds but when I tried to run `pass -c <some_password_entry>` to copy a password to clipboard directly, **pass** hangs and clipboard's buffer remains **inaltered**.

Thanks in advance.

**Comment by Neo-Oli** [comment]
In order for clipboard functionality to work you must set up [Termux:API](https://wiki.termux.com/wiki/Termux:API#Installation).
