### ISSUE TITLE
Syncthing failed to start in non-chroot environment

### ISSUE THREAD

**Issue by darkgeek** [termux/termux-packages#2391]
Hi, all:

I have an OnePlus One phone with Android Extended ROM v5.4 (say, it's Android `8.1.0`) flashed. Then I install `syncthing` from repo, and try to run it. However, it complains with many errors and exits abnormally. On the other hand, if I run `termux-chroot` before running `syncthing`, say, run it in chroot mode, `syncthing` works without any issues.

I upload the transcript of the session output here:
[typescript2.txt](https://github.com/termux/termux-packages/files/1961679/typescript2.txt)

And this is the environment of my Android:

```shell
u0_a105@localhost:~$ uname -a
Linux localhost 3.4.113-bacon-g487bcfba375 #1 SMP PREEMPT Wed Apr 11 09:51:18 IST 2018 armv7l Android
u0_a105@localhost:~$ dpkg --print-architecture
arm
```

Feel free to tell me if more information is needed. Thanks.

**Comment by Grimler91** [comment]
I've never used syncthing. 

Just starting syncthing on my arm device doesn't give any errors though. 
Are you doing anything more to get the errors?

**Comment by darkgeek** [comment]
@Grimler91 No, I just run `syncthing`  command without any parameters only, nothing more.

**Comment by Grimler91** [comment]
Ah, seems to be the same/similar issue as in https://github.com/termux/termux-packages/issues/420. Newer android versions have stricter security and doesn't allow some instructions.

Not sure if there is anything we can do, either than workaround as in the termux-chroot case.

**Comment by xeffyr** [comment]
This is because of sys_ioprio_set() syscall. Setting of the IO priority shouldn't be critical and I guess it can be disabled allowing to run syncthing on Android 8.

**Comment by xeffyr** [comment]
Version 0.14.47 works fine on Android 8 (i686 AVD image).
@darkgeek you may want to run `pkg upgrade` to update packages to latest versions.

@Grimler91, @fornwall  I guess that this issue was solved.
