### ISSUE TITLE
Compile kernel with libllvm

### ISSUE THREAD

**Issue by Nsikak1** [termux/termux-packages#2396]
Is it possible to compile the Linux kernel with llvm or is the ndk in termux now Thanks.

**Comment by its-pointless** [comment]
the ndk is termux by default...
If the kernel is able to be compiled by clang it should work. But i don't think most available kernels for most phones compile with clang. But i do have gcc-7 at my repo and people have compiled kernels on that before.

**Comment by its-pointless** [comment]
Unless you are doing kernel dev stuff very specifically you don't want to compile kernel on device though.

**Comment by Nsikak1** [comment]
Hi "its-pointless" I actually thought the title was its pointless but what if I want to run make (the make command) when I want to compile how will I do that also how can I add the your GCC in termux Thanks.

**Comment by Grimler91** [comment]
Closing this as I believe this is out of our scope. 

Best course of action would be to first learn how to compile a kernel on a desktop (and there's plenty of guides for that) and then just do the same on device and then fix (if possible) android specific errors that occur.

**Comment by Nsikak1** [comment]
Not easy as it seems but will update you on my progress
