### ISSUE TITLE
Add support libass to ffmpeg

### ISSUE THREAD

**Issue by rafinetiz** [termux/termux-packages#2399]
I am trying to convert softcoded subtitles to hardcoded subtitles video but subtitles filter is not available in current ffmpeg version.

`ffmpeg -i "/sdcard/Tanaka.mkv" -vcodec libx264 -acodec aac -vf subtitles=/sdcard/Tanaka.mkv /sdcard/Rafi/Tanaka.mkv`

It give me error:

> [AVFilterGraph @ 0xb4891200] No such filter: 'subtitles'2:22.77 bitrate=  -0.0kbits/s speed=N/A
> Error reinitializing filters!
> Failed to inject frame into filter network: Invalid argument

https://github.com/libass/libass
https://ffmpeg.org/ffmpeg-filters.html#subtitles-1

**Comment by seisdr** [comment]
Yea

**Comment by xeffyr** [comment]
Done in https://github.com/termux/termux-packages/commit/0724ec2c23920a9c36366a7f373f40f9b443cd88.
