### ISSUE TITLE
using aria2 with webui in browser

### ISSUE THREAD

**Issue by fplust** [termux/termux-packages#240]
run:
 aria2 --enable-rpc --rpc-listen-all
it runs no error
but when I open http://ziahamza.github.io/webui-aria2/ in the browser, it can not connect to the aria2 rpc server.

**Comment by fornwall** [comment]
It works for me when I try. Can you ensure that you run the latest package versions by running

    apt update && apt -y upgrade

and then try again? If the problem remains, can you paste the output of running

    aria2 --enable-rpc --rpc-listen-all

Also, which web browser are you using? Chrome on the Android device?

**Comment by fplust** [comment]
I retried on Chrome and it connected successfully, so it is my browser's problem. thank you for your reply.
