### ISSUE TITLE
Package request: atom.io

### ISSUE THREAD

**Issue by fancsali** [termux/termux-packages#2401]
I am not sure, whether it's feasible, but it would be awesome if we could have the popular atom.io editor on our Chromebooks using Termux.

**Comment by claytonaalves** [comment]
Atom editor depends on a Webview engine like chrome, not on a terminal like termux.

**Comment by fancsali** [comment]
You are absolutely right. But Chromebooks do not run arbitrary code by default, so Termux would essentially be a sandbox, to host it. Maybe the whole idea is a bit of a hack, and as such out of the scope of Termux, I do agree with that...

**Comment by onlurking** [comment]
To run Electron(which is Atom's base) you will need a bunch of dependencies, namely:
```
gtk+-2.0 dbus-1 x11 x11-xcb xcb xi xcursor xdamage 
xrandr xcomposite xext xfixes xrender xtst xscrnsaver 
gconf-2.0 gmodule-2.0 nss
```
Actually, you can get `xorg` running with Termux with some [black magic](https://github.com/xeffyr/termux-x-repository), but really, I think there is no way Termux will distribute Atom as a package, Termux is meant to be only a "Terminal Emulator" top on Android, have a Linux userland and run `cli` apps.

**Comment by Serkan-devel** [comment]
Does anyone know if electron is being ported to Android?

**Comment by ExtremeNerd** [comment]
I think the app named GNURoot Debian could do it in somewhat complicated manner. Whatever, webview stuff will more likely be a memory hog on a smartphone. There are alternatives to that..

**Comment by fornwall** [comment]
X11 gui programs are currently out of scope for Termux.
