### ISSUE TITLE
libclang_rt.asan-aarch64-android.so is missing.

### ISSUE THREAD

**Issue by sebras** [termux/termux-packages#2403]
I'm trying to compile something inside termux that uses clang's AddressSanitizer.

This is how to reproduce my issue (there might be shorter ways, but this works):
> echo -e '#include <stdio.h>\nint main() { printf("hello\\n"); }' > testing.c
> clang -g -fsanitize=address -o testing testing.c`

When linking it fails with:
> /data/data/com.termux/files/usr/bin/ld: cannot find /data/data/com.termux/files/usr/lib/clang/6.0.0/lib/linux/libclang_rt.asan-aarch64-android.so: No such file or directory

It would be nice to have this ASAN library because the resulting binaries catch many of the same errors as valgrind does, but the program consumes less resources when run (because all instructions are not emulated, it is just a subset that are instrumented). Besides running the same program in valgrind like this, results in *lots* of irrelevant warnings:
> echo -e '#include <stdio.h>\nint main() { printf("hello\\n"); }' > testing.c
> clang -g -o testing testing.c`
> valgrind ./testing

I'm open to testing a pre-release version of a compiled version of this library if it helps you in any way. Oh, and thanks for putting effort into termux, I just started using it. :)

**Comment by its-pointless** [comment]
You can compile libcompiler_rt on device which should give you the needed library.

**Comment by pd0wm** [comment]
I ran into the same problem too, and added theses lines to the libllvm build script. If this is something you guys want to upstream I can make a pull request.

```
diff --git a/packages/libllvm/build.sh b/packages/libllvm/build.sh
index fd494ad4..e76a935a 100644
--- a/packages/libllvm/build.sh
+++ b/packages/libllvm/build.sh
@@ -56,6 +56,15 @@ termux_step_post_extract_package () {
        tar -xf $TERMUX_PKG_CACHEDIR/$CLANG_SRC_TAR -C tools
        mv tools/cfe-${TERMUX_PKG_VERSION}.src tools/clang

+       local COMPILER_RT_SRC_TAR=compiler-rt-${TERMUX_PKG_VERSION}.src.tar.xz
+       termux_download \
+                 https://releases.llvm.org/${TERMUX_PKG_VERSION}/$COMPILER_RT_SRC_TAR \
+                 $TERMUX_PKG_CACHEDIR/$COMPILER_RT_SRC_TAR \
+                 d0cc1342cf57e9a8d52f5498da47a3b28d24ac0d39cbc92308781b3ee0cea79a
+
+       tar -xf $TERMUX_PKG_CACHEDIR/$COMPILER_RT_SRC_TAR -C projects
+       mv projects/compiler-rt-${TERMUX_PKG_VERSION}.src projects/compiler-rt
+
        local LLD_SRC_TAR=lld-${TERMUX_PKG_VERSION}.src.tar.xz
        termux_download \
                https://llvm.org/releases/${TERMUX_PKG_VERSION}/$LLD_SRC_TAR \
```

**Comment by sebras** [comment]
@pd0wm assuming that `compile-rt-*.src.tar.xz` contains the source for the asan-library it looks alright to me. Does everything compile successfully with this patch? I assume it does, but better to ask. If so I'd like for this to be a PR that hopefully is included. :)

**Comment by its-pointless** [comment]
I already have a build script for it as a separate package.  I made the lib available on my repo if anyone wants to test etc...

**Comment by pmatos** [comment]
> I already have a build script for it as a separate package. I made the lib available on my repo if anyone wants to test etc...

Which repo are you talking about? Does this include the undefined behaviour sanitizer?

**Comment by harieamjari** [comment]
> You can compile libcompiler_rt on device which should give you the needed library.

I've tried compiling `compiler-rt-9.0.0.src` for my clang 9.0.0, and of course! it did gave me an error:

```
/data/data/com.termux/files/home/compiler-rt-9.0.0.src/lib/builtins/arm/sync_fetch_and_add_4.S:19:160: error: instruction requires: data-barriers
.p2align 2; .thumb; .syntax unified; .arm ; ; .globl __sync_fetch_and_add_4 ; .type __sync_fetch_and_add_4,%function ; ; .thumb_func ; __sync_fetch_and_add_4: dmb; mov r12, r0; .L_tryatomic_add_4 : ldrex r0, [r12]; add r2, r0, r1; strex r3, r2, [r12]; cmp r3, #0; bne .L_tryatomic_add_4; dmb; bx lr


                           ^
```

Note: I'm using a legacy Termux environment.
