### ISSUE TITLE
bad interpreter: Permission denied

### ISSUE THREAD

**Issue by abhi2k18** [termux/termux-packages#2407]
As i update using dnf update some error arrived some failed and after it Failed:                                              glibc.aarch64 2.26-27.fc27                glibc-langpack-en.aarch64 2.26-27.fc27                      libstdc++.aarch64 7.3.1-5.fc27            python3.aarch64 3.6.5-1.fc27                                python3-dnf.noarch 2.7.5-2.fc27           python3-gpg.aarch64 1.10.0-4.fc27.1                         python3-hawkey.aarch64 0.11.1-1.fc27      python3-libs.aarch64 3.6.5-1.fc27                           python3-pip.noarch 9.0.3-1.fc27           python3-rpm.aarch64 4.14.1-1.fc27                           python3-setuptools.noarch 37.0.0-1.fc27   tzdata.noarch 2018d-1.fc27
Error: Transaction failed                          [termux@fedora home]$ yum install java-1.0.8-openjdk                                                  bash: /bin/yum: /usr/bin/python3: bad interpreter: Permission denied                                  [termux@fedora home]$ dnf update
bash: /bin/dnf: /usr/bin/python3: bad interpreter: Permission denied
[termux@fedora home]$                              [termux@fedora home]$ yum install fish
bash: /bin/yum: /usr/bin/python3: bad interpreter: Permission denied

**Comment by onlurking** [comment]
This is a [termux fedora proot](https://github.com/nmilosev/termux-fedora) issue, not a termux one, can you [post there](https://github.com/nmilosev/termux-fedora/issues) and close this issue? 

I will try to reproduce this bug in my phone and help you.

**Comment by abhi2k18** [comment]
Thanks
