### ISSUE TITLE
Unison inside Arch proot freezes on file change

### ISSUE THREAD

**Issue by alexozer** [termux/termux-packages#2412]
I've tried Unison in Arch, but when using `-repeat watch` to sync instantly on local file changes, after a while of running it seems to stop syncing changes on the phone eventually.

At some point I'll modify a file, and unison will print "Looking for changes" and then just freeze until restarted, when it will then sync the change.

**Comment by vovcacik** [comment]
Things you can try in no particular order:
- ssh into your phone and watch `top` output - if you run unison with `-repeat watch` there should be `unison-fsmonitor` running 
- your phone may kill wifi after few minutes to save battery (and use mobile data instead)
- try to disable SELinux temporarily:
  - `su bash`
  - `getenforce`
  - `setenforce 0`
  - `getenforce` to check the change
- let termux acquire wake lock:
  - there should be button on termux notification
  - or you can run `termux-wake-lock` from shell
- there should be `~/unison.log` file, or specify your own location with `log` and `logfile` options (see docs)

**Comment by vovcacik** [comment]
- make sure you run same unison version on both ends: `unison -version`
  - the version of OCaml that were used to build unison may play a role (but I don't think you can find out this info)
- try my binaries: https://github.com/vovcacik/unison-build-scripts/tree/master/binaries/2.48.4/linux-armv7

**Comment by alexozer** [comment]
Thanks a lot for the suggestions! Although I'm currently not using Termux, so I won't have much info to provide, so maybe this should be closed until somebody else reports the issue.

I can say though that I did check and all Unison ocaml versions were the same.

**Comment by vovcacik** [comment]
The error seems to be tightly connected to change discovery, `unison-fsmonitor` is using `inotify` on linux. It might be worth to play with it little bit:
- `cat /proc/sys/fs/inotify/max_user_watches` to get your default
- `sudo su -c 'echo 262144 > /proc/sys/fs/inotify/max_user_watches'` to increase it
- `sudo su -c 'echo 1024 > /proc/sys/fs/inotify/max_user_watches'` to decrease it
