### ISSUE TITLE
Package request: calc

### ISSUE THREAD

**Issue by GRMrGecko** [termux/termux-packages#2417]
http://www.isthe.com/chongo/tech/comp/calc/

This is my favorite calculator for Linux. Uses readline for input.

**Comment by ExtremeNerd** [comment]
If that is available for Alpine, for right now, you can install a minimal Alpine Linux rootfs as provided by them using `proot`, and install it there..
If you can't get Network working right inside that rootfs, download all direct and indirect dependencies yourself & add using `--allow-untrusted` flag.
By the way, you may download the Alpine Linux APK file + all direct / indirect dependencies then unpack into termux prefix directory. By renaming `calc*.apk` to `calc.tar.gz`... Don't know if it works properly...

**Comment by 3442** [comment]
#4875

**Comment by kcubeterm** [comment]
This issue should be close
