### ISSUE TITLE
man apt

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#2419]
Can we package the man page for apt?

**Comment by kaeptmblaubaer1000** [comment]
No actions since many months... please do something!

**Comment by xeffyr** [comment]
> No actions since many months... please do something!

Because manpage cannot be built for unknown reason. I tried to install necessary tools but no success.

**Comment by kaeptmblaubaer1000** [comment]
I think I've seen something in the build.sh of apt, but I don't remember anymore

**Comment by kaeptmblaubaer1000** [comment]
![screenshot_20190223-134222](https://user-images.githubusercontent.com/18211838/53286566-f226ba80-3770-11e9-91ab-bed0f1d0e70d.png)

**Comment by xeffyr** [comment]
This is done intentionally to prevent build error.

**Comment by kaeptmblaubaer1000** [comment]
Which error? Got any log?

**Comment by xeffyr** [comment]
```
CMake Error at CMake/Documentation.cmake:44 (message):
  Could not find docbook xsl
Call Stack (most recent call first):
  doc/CMakeLists.txt:1 (include)
```
This error happens even if docbook and docbook-xsl are installed.

**Comment by kaeptmblaubaer1000** [comment]
:thinking: hmmm...
Is it possible to build apt on-device? I might try to find a solution

**Comment by xeffyr** [comment]
> I might try to find a solution

Other solution is to just **copy** manpage from somewhere.
Intresting, that I can't find anything about problems with docbook in CMakeOutput.log or CMakeError.log.

**Comment by xeffyr** [comment]
Now I know why it fails:
```
find_path(DOCBOOK_XSL manpages/docbook.xsl
         # Debian
         /usr/share/xml/docbook/stylesheet/docbook-xsl
         /usr/share/xml/docbook/stylesheet/nwalsh
         # OpenSUSE
         /usr/share/xml/docbook/stylesheet/nwalsh/current
         # Arch
          /usr/share/xml/docbook/xsl-stylesheets
         # Fedora
         /usr/share/sgml/docbook/xsl-stylesheets
         # Fink
         ${CMAKE_INSTALL_PREFIX}/share/xml/xsl/docbook-xsl
         # FreeBSD
         ${CMAKE_INSTALL_PREFIX}/share/xsl/docbook/
         NO_DEFAULT_PATH)

if(NOT DOCBOOK_XSL)
    message(FATAL_ERROR "Could not find docbook xsl")
endif()
```

Some of these paths are outdated and no longer valid.

**Comment by kaeptmblaubaer1000** [comment]
I'd probably have found it too if I had enough time...
But great that I asked about it so that you could find it ;-)
