### ISSUE TITLE
Ruby cannot locate endpwent

### ISSUE THREAD

**Issue by CRamsan** [termux/termux-packages#242]
I am trying to run ruby on my Pixel C on the Android N preview but I am encountering a similar issue to #212.

Would the fix be similar, rebuilding with the function patched away?

**Comment by fornwall** [comment]
This have been fixed as a side effect of updating to ruby `2.3.1` and rebuilding - run `apt update && apt upgrade` and let me know if the problem remains!

**Comment by CRamsan** [comment]
Thanks, that did fix the issue
