### ISSUE TITLE
wget missing HTTPS support

### ISSUE THREAD

**Issue by tidux** [termux/termux-packages#2423]
```
$ wget https://github.com/fletcher/MultiMarkdown-6/archive/6.3.2.tar.gz
wget: not an http or ftp url: https://github.com/fletcher/MultiMarkdown-6/archive/6.3.2.tar.gz
```

**Comment by Grimler91** [comment]
You are using the busybox version. Install wget with `pkg in wget` and open a new terminal.

**Comment by pre1ude** [comment]
@tidux after `pkg install wget`, restart the terminal will find wget support https now!!!

**Comment by Souravgoswami** [comment]
Same goes for me. Upgrading the package doesn't work.

## Solution for Me 💡
Who cares, I have got ruby 💎
```
require 'net/http'
File.write 'cowspeak', Net::HTTP.get(URI('https://raw.githubusercontent.com/Souravgoswami/cowspeak/master/cowspeak'))
```

So basically, it's just a tricky way. It will work in an emergency!

**Comment by xeffyr** [comment]
> Upgrading the package doesn't work.

Works. You just doing something wrong or just not restarted session (or did `hash -r`).

1. Installing normal version of wget:
```
pkg install wget
hash -r
```

2. Calling wget on some HTTPS site:
```
Setting up libuuid (1.0.3-2) ...
Setting up wget (1.20.3-2) ...
$ wget https://google.com
--2019-05-17 00:01:28--  https://google.com/
Resolving google.com... 216.58.215.110
Connecting to google.com|216.58.215.110|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.google.com/ [following]
--2019-05-17 00:01:28--  https://www.google.com/
Resolving www.google.com... 172.217.20.164
Connecting to www.google.com|172.217.20.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.1’

index.html.1       13.82K  --.-KB/s    in 0.004s  

2019-05-17 00:01:29 (3.52 MB/s) - ‘index.html.1’ saved [14156]
```
\- works...

**Comment by xeffyr** [comment]
So, if you are installing utility that replaces one from busybox, you have to restart the session or just execute `hash -r`. This is required because bash does program path caching.
