### ISSUE TITLE
termux-api package for arm is a few versions behind the latest one (0.25 vs 0.28)

### ISSUE THREAD

**Issue by wendelscardua** [termux/termux-packages#2426]
I've noticed that some new termux-api scripts weren't available on my phone, although both package and app were updated... Then, checking the repos themselves, while https://termux.net/dists/stable/main/binary-aarch64/ lists `termux-api_0.28` from 2018-04-09, https://termux.net/dists/stable/main/binary-arm/ still has only `termux-api_0.25`, from 2018-02-05.

**Comment by fornwall** [comment]
Thanks for reporting! This has now been fixed.
