### ISSUE TITLE
ipcs: command not found (util-linux)

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#2427]
```
[23:47 test ]$ ipcs

------ Message Queues --------
key        msqid      owner      perms      used-bytes   messages

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status

------ Semaphore Arrays --------
key        semid      owner      perms      nsems

[23:47 test ]$ ./cleanup-shared-memory.sh
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
[23:48 test ]$ e
[23:48 test ]$ ipcs
No command 'ipcs' found, did you mean:
 Command 'apxs' from package 'apache2'
 Command 'ocs' from package 'cscope'
 Command 'pphs' from package 'ghostscript'
 Command 'mpc' from package 'mpc'
 Command 'ps' from package 'procps'
 Command 'rcs' from package 'rcs'
 Command 'ip' from package 'termux-tools'
[23:48 test ]$ ./cleanup-shared-memory.sh
./cleanup-shared-memory.sh: line 4: ipcs: command not found
BusyBox v1.28.3 (2018-04-08 23:41:12 UTC) multi-call binary.

Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...
```
```
$ pacman -Qo ipcs
/usr/bin/ipcs is owned by util-linux 2.32-3
```

References:
1) https://github.com/termux/libandroid-shmem/issues/3
>Shared memory appears to be important in many issues:
> 1) https://github.com/sdrausty/termux-archlinux/issues/4
> 2) https://github.com/sdrausty/TermuxArch/issues/38
> 3) https://github.com/sdrausty/TermuxArch/issues/55
> 4)  https://github.com/sdrausty/TermuxArch/issues/55https://github.com/sdrausty/TermuxArch/issues/59#issuecomment-381380567
> 4) https://github.com/sdrausty/TermuxArch/issues/68

**Comment by vishalbiswas** [comment]
Its not possible.
The functions to implement **Message Queues** and **Semaphore Arrays** are not available before Nougat. So, this is not possible yet.
Maybe, when we make the minimum API Level 24.

**Comment by sdrausty** [comment]
@vishalbiswas thank you for looking into this issue.  Is it possible to fork Termux development into API 21, 23 and 24+ branches?  The reason that I am asking is, would this make Termux development easier for developers and users alike?  This development scenario would probably use getprop to install the correct Termux version on device and wrappers can handle exec, errors and warnings for Termux packages...

**Comment by sdrausty** [comment]
Accessing libandroid-shmem support is now possibly in TermuxArch, use **[`setupTermuxArch.sh r`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh)** for quick system refresh; libandroid-shmem support is added with this https://github.com/sdrausty/TermuxArch/commit/a25067274c341b73d1fc79b85eabbbbdf33680eb commit.  The current version of [TermuxArch](https://sdrausty.github.io/TermuxArch/) also sets locales from Android on the fly for Arch Linux in Termux PRoot to be in the language you wish.

**Comment by xeffyr** [comment]
@sdrausty **Why you reopened this ?**

> Its not possible.
> The functions to implement **Message Queues** and **Semaphore Arrays** are not available before Nougat. So, this is not possible yet.
> Maybe, when we make the minimum API Level 24.

**Comment by sdrausty** [comment]
Because we are working on this https://github.com/sdrausty/libandroid-shmem issue here @xeffyr.  If we can get libandroid-shmem to work correctly, then this issue should be closed.  

Futhermore, probably because it is so far off in the sidelines, this https://github.com/termux/libandroid-shmem/issues/3 issue has received no comments.  

Moreover, these shmem issues have also been reopened at https://github.com/sdrausty/TermuxArch/issues hete.  There are a few lingering at https://github.com/sdrausty/Termux-Archlinux/issues also.  A total of five open related issues at present.

Do you think a new issue concerning shmem should be opened, instead of reopening this one? The demand for a functional shmem is very high among Termux users even though many don't know that a functional shmem is what they want.

**Comment by xeffyr** [comment]
@sdrausty 

1. 'ipcs: command not found': ipcs command is not part libandroid-shmem.
2. libandroid-support is functional in standard Termux installation. So **if it not working somewhere else - this is irrelevant**.

> If we can get libandroid-shmem to work correctly
> The demand for a functional shmem is very high among Termux users even though many don't know that a functional shmem is what they want.

Termux users **!=** TermuxArch users as they use different environments.
Termux users already got fully functional `libandroid-shmem`.

So, since `libandroid-shmem` works, issue can be closed, otherwise it will be **force closed** or even **locked**.

**Comment by sdrausty** [comment]
@xeffy can you show me how to test this?

> Termux users already got fully functional libandroid-shmem.

> So, since libandroid-shmem works, issue can be closed

I don't see it working.  Can you outline some examples where it works please?

**Comment by xeffyr** [comment]
> I don't see it working. Can you outline some examples where it works please?

1. [postgresql](https://github.com/termux/termux-packages/tree/master/packages/postgresql)
2. [x11/feh](https://github.com/termux/x11-packages/tree/master/packages/feh)
3. [x11/mpv-x](https://github.com/termux/x11-packages/tree/master/packages/mpv-x)
4. [x11/pypanel](https://github.com/termux/x11-packages/tree/master/packages/pypanel)
5. [x11/wireshark-gtk](https://github.com/termux/x11-packages/tree/master/packages/wireshark-gtk)
6. other packages (from [termux-packages](https://github.com/termux/termux-packages) or [x11-packages](https://github.com/termux/x11-packages)) that are not mentioned in this list.

**Comment by sdrausty** [comment]
> Termux users != TermuxArch users 

I cannot phantom this logic @xeffyr; You must be a Termux user first in order to become a TermuxArch user, as far as I can tell.  How can you use TermuxArch without Termux?  

It is not either one or the other.  It is one or both of them.  Shouldn't libshmem work equally well in Termux and Termux PRoot? 

> can you show me how to test this?

You have been kind enough to list packages where libshmem works with Termux.  Possibly it was being installed incorrectly in TermuxArch?
