### ISSUE TITLE
I broke `pkg`!

### ISSUE THREAD

**Issue by JacobTDC** [termux/termux-packages#2432]
I used `npm install pkg` not realizing it replaces the default package manager command. I have uninstalled npm pkg, and it removed pkg altogether. How do I fix it?! :(
Please help, I'm really worried that I'm going to have to lose all of my data to reinstall Termux.

**Comment by Grimler91** [comment]
`pkg` is just a wrapper around `apt` so you can use `apt` instead.

`pkg` runs `apt update` before trying to install something. If you use `apt` you have to manually run `apt update` every now and then or before you try to install something.

If you get into similar problems you can also run `rm -rf $PREFIX` and restart termux. This will re-download termux' bootstrap, you will lose all installed packages but all your data in $HOME will be safe.

**Comment by Grimler91** [comment]
Oh, and `pkg` is provided by the package termux-tools, so if you want pkg back (but break the npm package) you can do `apt update && apt install --reinstall termux-tools`.

**Comment by vagEYE8** [comment]
I somehow managed to break C++... Any ideas?
