### ISSUE TITLE
mutt smtp issue

### ISSUE THREAD

**Issue by Xohwie1i** [termux/termux-packages#2434]
Since a few days ago, mutt cannot send emails using the embedded smtp. I get a "No authenticators available" error. Maybe this is related to [here](https://github.com/termux/termux-packages/issues/1582)?

**Comment by Grimler91** [comment]
I tested mailing from three of my accounts and I have the same issue with one of them (smtp-mail.outlook.com). I'm not entirely sure if it worked before though so can't rule outmy settings.

**Comment by ZerooCool** [comment]
SASL est apparemment requis pour que mutt s'authentifie à l'aide de smtps.
Installer le paquet suivant résout le problème : sudo apt install libsasl2-modules
Apt a répertorié ce paquet comme "recommandé", ce qui n'est pas un bogue, car vous n'en avez pas besoin pour exécuter mutt.

```
# SENDING MAIL
set smtp_url = "smtps://sow.eclipse@smtp.gmail.com:465/"
set smtp_pass = "PASSWORD"
set from = "sow.eclipse@gmail.com"
set realname = "Je suis l'utilisateur du VPS"

# RECEIVING MAIL
set imap_user = "sow.eclipse@gmail.com"
set imap_pass = "PASSWORD"
set folder = "imaps://imap.gmail.com:993"
set spoolfile="+INBOX"
set postponed="+[Gmail]/Drafts"
set record="imaps://imap.gmail.com/Sent"
set header_cache=~/.mutt/cache/headers
set certificate_file=~/.mutt/certificates
set message_cachedir=~/.mutt/cache/bodies
set move = no
```

**Comment by Xohwie1i** [comment]
I'm not sure I understand your suggestion, plus, I already have 'libsasl' installed...so I'm not sure this is the issue.

**Comment by renaldiap** [comment]
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"...

Hel me

**Comment by erji44** [comment]
I had exactly the same problem.
Use msmtp works fine to send emails and change the config of mutt to use msmtp instead of it's own smtp service.

**Comment by Grimler91** [comment]
This should have been fixed in https://github.com/termux/termux-packages/commit/95f60426cb8283fc0e5aec16f9b0f181cb69baad
