### ISSUE TITLE
git Fails in Folder on SD Card

### ISSUE THREAD

**Issue by kloppen** [termux/termux-packages#2441]
I'm currently unable to interact with git repos located on an SD card. This was previously possible (a few months ago), but no longer works. I'm not sure if this is related to an Android update, an update to Termux or an update to git running on Termux.

I am able to create/commit/push/pull with git repos on the device internal memory. For example, in the home directory, the following succeeds:

```bash
git init test-repo
```

However, if the same command is run in a folder on the (removable) SD card of my device, I get the following error:

```
error: could not write config file /storage/5385-1A04/Android/data/com.termux/files/test-repo/.git/config: Permission denied
fatal: could not set 'core.filemode' to 'false'
```

In the same folder on the SD Card where the creation of a git repo fails, I can create and modify files. I am able to create an empty file with `touch` and am able to edit existing files with `vim`

Any insight into this issue would be appreciated.

## Software and Device Details
Asus Zenpad
Android 7.0
Termux version 0.60
git version 2.17.0

**Comment by onlurking** [comment]
Can you try this command?
```
git config core.fileMode false
```

**Comment by kloppen** [comment]
I've tried setting core.fileMode false globally (as @onlurking suggested) and still get the same results. 

The SD card has an exFAT filesystem, but I've tried with a FAT file system too with exactly the same results.

When I run `ls -all` while in a directory on the SD card (inside the termux data directory), the permissions are all `rwxr-x---`, the owner of all the files is the user that termux is running under (u0_a111 in my case) and the group is "everybody". This would suggest that both my user should be able to run files in this folder. However, this doesn't actually work. If I create a simple bash script in this folder and run it as ./mybashscript.sh, I get a permission error (running as bash mybashscript.sh does work). This supports @onlurking's comment about permissions (despite what `ls` reports).

The strange thing is that I was able to create, clone, push and pull git repos stored on the same SD card until recently (a few months ago), so something has changed with either Android, Termux or git.

**Comment by tomty89** [comment]
I bet there was an Android upgrade?

You may want to run the `git init` command with `strace` to see exactly which system call on `.git/config` failed (probably with `EACCES` or `EPERM`).

Also do you have the Storage permission enabled? It appears that you can access `Android/data/com.termux` either way, but I wonder if there could be subtle differences between them on some Android builds.

Btw will you bump into the same problem if you work in the `Android/data/com.termux` under the *emulated* SD card (i.e. `/storage/emulated/0`) instead?

P.S. The executable case is probably irrelevant, since that's just because all SD cards (emulated or real) are mounted with `noexec`.

**Comment by kloppen** [comment]
As you've suggested, @tomty89 , I've run the following commands and the `mv`'s both succeed (note that I'm running this in the `com.termux/files` folder on the SD card, as I don't have write permissions in the root of the SD card.

```
cd /storage/5385-1A04/Android/data/com.termux/files
touch test-a
mv test-a test-b  # This succeeds
mv /storage/5385-1A04/Android/data/com.termux/files/test-b /storage/5385-1A04/Android/data/com.termux/files/test-c  # This also succeeds.
```

I've also run `strace` on one of the `mv`'s above. The `renameat` line in the `strace` output is:

```
renameat(AT_FDCWD, "test-a", AT_FDCWD, "test-b") = 0
```

So, it seems that `mv` is doing the same thing as `git init` is trying to do, but `mv` succeeds for whatever reason.

Maybe it is either a bug in the Android build on my ZenPad, or something broken with my Termux installation. I just tried the same thing on another device (Samsung S7, also running Android 7.0), and `git init` in a folder on the SD card inserted into that device (a different card) works fine.

**Comment by tomty89** [comment]
Hmm, does `mv` fail if the "b" file already exists? Like:
```
touch a b
mv a b
```

**Comment by kloppen** [comment]
Yes. If both `a` and `b` exist and are on the SD card, then `mv a b` fails with "Permission denied." If I run `strace` on this, then it shows:

```
renameat(AT_FDCWD, "a", "AT_FDCWD, "b") = -1 EACCESS (Permission denied)
```

However, if I try the same thing on the internal storage, then `mv a b` succeeds.

**Comment by vishalbiswas** [comment]
@kloppen go into app settings for termux and remove the granted permissions for read/write external. Then run `termux-setup-storage` again.

**Comment by kloppen** [comment]
@vishalbiswas Thanks for the suggestion. I've done that (and tapped "allow" when asked to grant Termux storage permissions), and `git init` still fails when run from a folder on the SD card.

**Comment by vishalbiswas** [comment]
@kloppen instead of accessing from /storage, try to access it from ~/storage

**Comment by kloppen** [comment]
Same result when accessing from /storage and ~/storage. Both fail.

**Comment by tomty89** [comment]
@kloppen I think it's pretty obvious that your Android build blocks the `renameat` syscall under certain circumstances (namely when the target already exists on a real SD card, that is). Not sure if it's intentional or just some regression. It's silly to me though and it's inconsistent to the behaviour of the emulated SD card, so I would say it's a more likely a regression.

There's not much you can do, except from reporting to the vendor.

**Comment by kloppen** [comment]
I've closed this issue, as it doesn't seem to be a problem with termux-packages.

Thanks for your help, @tomty89, @vishalbiswas and @onlurking

**Comment by vishalbiswas** [comment]
Until then we could have something like
```
if (exists(config_file)) {
    unlink(config_file);
}
```
before the move operation.

**Comment by vishalbiswas** [comment]
I've applied the following patch to git:
```patch
--- ./tempfile.c        2018-05-23 09:29:49.418310413 +0530
+++ ./tempfile.c        2018-05-23 09:29:43.204911421 +0530
@@ -295,7 +295,7 @@
                return -1;
        }

-       if (rename(tempfile->filename.buf, path)) {
+       if ((access(path, W_OK) || unlink(path)) || rename(tempfile->filename.buf, path)) {
                int save_errno = errno;
                delete_tempfile(tempfile_p);
                errno = save_errno;
```
You can try these changes by installing this deb file -> https://drive.google.com/open?id=1V9h-K0_H5GHO4oUlWENnBA9LPy8kjaWc
