### ISSUE TITLE
Intall package with specific version

### ISSUE THREAD

**Issue by fajarekapr** [termux/termux-packages#2443]
sorry about my english...

Hei guys, i was install python v3.x
but now I need python v2.6.x
How I can get it.

thanks.

**Comment by tomty89** [comment]
Currently Termux provides only python 2.7.x, known as `python2`.

**Comment by fajarekapr** [comment]
how to install it?

**Comment by fajarekapr** [comment]
oh so python2 it is python 2.7.x ??

**Comment by fajarekapr** [comment]
Ok, thank you guys.
I'm sorry if I'm a newbie.
