### ISSUE TITLE
Cannot install LUA HTTP [pls help]

### ISSUE THREAD

**Issue by bensh4** [termux/termux-packages#2447]
![](https://i.imgur.com/QoPT2qT.png)

I want to install LUA HTTP via LUAROCKS.I installed openssl. But when trying to install,it is showing this

```
luarocks install http

```

```
Error: Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/include
  No file openssl/ssl.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
```
LOOK SCREENSHOT!

I already have openssl/ssl.h. :disappointed:

![](https://i.imgur.com/sjMhYOr.png)

**Comment by Hax4us** [comment]
Try this command `luarocks install luasec OPENSSL_DIR=$PREFIX/include`

**Comment by bensh4** [comment]
![](https://i.imgur.com/dxdW1AJ.png) Getting the same error again :disappointed:.

**Comment by Hax4us** [comment]
You typed `luarocks install luasec`
But I said `luarocks install luasec OPENSSL_DIR=$PREFIX/include`

**Comment by bensh4** [comment]
should i replace ```OPENSSL_DIR``` ,  with ```/data/data/com.termux/files/usr/include/ssl.h``` ?

**Comment by Grimler91** [comment]
@bensh4 given the information you get from the error message, and what @hax4us wrote, what do you think you should do?

**Comment by bensh4** [comment]
I'm in ```usr/bin``` When I do ```ls``` 
I can see openssl is there 

![](https://i.imgur.com/kNGUX7d.png

But when running ```luarocks install luasec usr/bin/openssh $PREFIX/include``` I'm still facing this error.

![](https://i.imgur.com/jAc2wGr.png)

There's is an other openssl installed on ```usr/include/openssl/openssl.h``` which also gives me error. @Grimler91 @Hax4us

**Comment by Grimler91** [comment]
Right, lets go through this.

First of all you are not in `/usr/bin`, you are in `/data/data/com.termux/files/usr/bin`. See [this wiki entry](https://wiki.termux.com/wiki/Differences_from_Linux#Prefixed_System) on why that is important. 

Second of all, the openssl in `/data/data/com.termux/files/usr/bin` (I'll here after write $PREFIX instead of `/data/data/com.termux/files/usr/`) is an executable file (and therefore resides in `$PREFIX/bin`) while the files in the foldwr

**Comment by bensh4** [comment]
Firstly,we need to navigate into /system/usr/lib where the ssl lib are saved. From there run ```luarocks install luasec OPENSSL_DIR=$PREFIX``` Then it will be installed. But not sure where the Luasec is installed 🙄 ![](https://i.imgur.com/yKAFRbq.png)

**Comment by bensh4** [comment]
@Grimler91 ,You told that i should be in the ```usr/bin``` i hope you meant ```/system/usr/bin```  right?

**Comment by bensh4** [comment]
I'm still wondering how the LUASEC is installed. But let me tell you,the problem isn't solved. For lua HTTP, we need to install ```luaossl``` too. Anyway,i'm again falling back to old problem

**Comment by Grimler91** [comment]
Read the error message and use what you learned before. 
OPENSSL_DIR has nothing to do with your current error. 

Again, it doesn't matter which folder you run the command from.

**Comment by bensh4** [comment]
@Grimler91 , you are cool man 😎
I
Look what I got! ! Still got some warnings! 
 
![](https://i.imgur.com/JQNcKLE.png)

And

![](https://i.imgur.com/pO86eIG.png)

**Comment by BhanuPrakash531** [comment]
apt-get install libssl-dev will do the trick
