### ISSUE TITLE
Clang dont load librarys

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#245]
How to resolve? O.o

bash-4.3$ clang
CANNOT LINK EXECUTABLE: could not load library "libLLVMARMCodeGen.so" needed by "clang"; caused by could not load library "libLLVMARMAsmPrinter.so" needed by "libLLVMARMCodeGen.so"; caused by could not load library "libLLVMMC.so" needed by "libLLVMARMAsmPrinter.so"; caused by could not load library "libLLVMSupport.so" needed by "libLLVMMC.so"; caused by cannot locate symbol "_ZNSt13__future_base12_Result_baseD2Ev" referenced by "libLLVMSupport.so"...

**Comment by fornwall** [comment]
This should now be fixed - run

    apt update && apt upgrade

and let me know if the problem remains after that!
