### ISSUE TITLE
Cannot install Luadns [Please help]

### ISSUE THREAD

**Issue by bensh4** [termux/termux-packages#2451]
I installed luahttp, thanks @Grimler91 
But now when trying to install ```luadns``` using luarocks,I'm getting this error

![](https://i.imgur.com/MILgAGp.png)

Do we need to port this to termux for working without this error?
Also tried my showing openssl directory. But didn't worked either.  :disappointed:

![](https://i.imgur.com/3qRQBxL.png)     

@fornwall , @nekoas , @mawatech

**Comment by Atavic** [comment]
CFLAGS appear on other issues, started mainly because scripts assume */bin/sh* exists:

> *-use-system-libraries*

https://github.com/termux/termux-packages/issues/397#issuecomment-271558353

> avoid defining PREFIX path hardcoded in favour of @TERMUX_PREFIX@

https://github.com/termux/termux-packages/pull/77#issuecomment-162313941

**Comment by bensh4** [comment]
@Atavic ,Could you please tell me where to make changes in the command

**Comment by bensh4** [comment]
@Atavic , when I added ```-use-system-libraries``` , I got this error! 

![](https://i.imgur.com/GYxacxO.png)
