### ISSUE TITLE
Flex is not building 

### ISSUE THREAD

**Issue by Hax4us** [termux/termux-packages#2454]
https://api.travis-ci.org/v3/job/383776557/log.txt

Flex is not building after Automake 1.15 update 
https://github.com/lede-project/source/commit/91e262c6b35a748c743607da2d3ead4764e05038 

Autoreconf (regenerating configure) in build.sh should solve this issue and I tried but then autoreconf complaining for `autopoint` which is part of gettext

**Comment by Hax4us** [comment]
This issue is invisible ?

**Comment by fornwall** [comment]
Is this still a problem? I'm unable to reproduce it when building using a clean docker image.
