### ISSUE TITLE
Streamlink on Termux  - pip2 install fails!

### ISSUE THREAD

**Issue by markosjal** [termux/termux-packages#2456]
I am trying to install Streamlink on Termux 

I execute  
pip2 install streamlink 

installation  fails

WIll post the installer log file as soon as I can but it will be a little work to get it here from there

I sure hope there is a fix for this!

**Comment by markosjal** [comment]
log attached

[streamlinkfail.log](https://github.com/termux/termux-packages/files/2042191/streamlinkfail.log)

**Comment by tomty89** [comment]
Install clang

**Comment by markosjal** [comment]
Must apt install clang . It does not work with pip install .

**Comment by Grimler91** [comment]
Yes, clang is available through apt. You can't install it through pip.
