### ISSUE TITLE
pcaprub installation fails 

### ISSUE THREAD

**Issue by KnightRider066** [termux/termux-packages#2457]
Fetching pcaprub 0.12.4
Installing pcaprub 0.12.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/pcaprub-0.12.4/ext/pcaprub_c
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20180527-27045-122aftz.rb extconf.rb

[*] Running checks for pcaprub_c code...
platform is aarch64-linux-android
checking for ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl()... yes
checking for pcap_open_live() in -lpcap... no
checking for pcap_setnonblock() in -lpcap... no
creating Makefile

current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/pcaprub-0.12.4/ext/pcaprub_c
make "DESTDIR=" clean

current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/pcaprub-0.12.4/ext/pcaprub_c
make "DESTDIR="
compiling pcaprub.c
pcaprub.c:11:10: fatal error: 'pcap.h' file not found
#include <pcap.h>
         ^~~~~~~~
1 error generated.
make: *** [Makefile:242: pcaprub.o] Error 1

make failed, exit code 2

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/pcaprub-0.12.4 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/pcaprub-0.12.4/gem_make.out

An error occurred while installing pcaprub (0.12.4), and Bundler cannot continue.
Make sure that `gem install pcaprub -v '0.12.4' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  metasploit-framework was resolved to 4.16.4, which depends on
    packetfu was resolved to 1.1.13, which depends on
      pcaprub

**Comment by Grimler91** [comment]
It says `pcaprub.c:11:10: fatal error: 'pcap.h' file not found` so install libpcap-dev.

**Comment by bensh4** [comment]
@Grimler91 , https://github.com/termux/termux-packages/issues/2451

**Comment by Grimler91** [comment]
@bensh4 don't spam unrelated comments in other threads. I'm sure someone will advice you sooner or later, if they can.
