### ISSUE TITLE
CFLAGS while installing luadns

### ISSUE THREAD

**Issue by bensh4** [termux/termux-packages#2458]
The problem got more simplified when I run it in the verbose mode. ```luarocks install Luadns --verbose``` produced these outputs.
![](https://i.imgur.com/nfWUUp0.png)

![](https://i.imgur.com/UFovVqD.png)

![](https://i.imgur.com/Gtj264D.png)

![](https://i.imgur.com/Hquf8H2.png)

Any fix ? When I added ```-use-system-libraries``` I got this error

![](https://i.imgur.com/VXmTVtd.png)

**Comment by bensh4** [comment]
you mean ```luarocks install luadns --use-system-libraries ``` right?

**Comment by bensh4** [comment]
![](https://i.imgur.com/2xTKL6U.png)

**Comment by vishalbiswas** [comment]
do you have dev files for lua?

**Comment by Grimler91** [comment]
You probably need to patch the source code, try downloading it and look into the code.
Luadns doesn't seem to have been [updated in 4 years](https://luarocks.org/modules/luarocks/luadns) so it is perhaps not very surprising that it doesn't build.

**Comment by bensh4** [comment]
@Grimler91 As far as concerned,this is the problem with Lua. I need to deal with networking and servers. Then which would be the best language which also have better support of all libraries in termux ? Thanks @Grimler91

**Comment by Grimler91** [comment]
@bensh4 I don't work with networking or servers so I don't really know.

Python is generally good..

**Comment by vishalbiswas** [comment]
@bensh4 the problem is not really with Lua. The source code uses `luaL_reg` but newer Lua versions have `luaL_Reg`.
You'll have to manually patch the source code to install it.
Unfortunately, the buildspec for LuaDNS doesn't use CFLAGS neither, so you cannot fix this without manually editing source code.

**Comment by bensh4** [comment]
Does termux supports all python libraries?

**Comment by bensh4** [comment]
@vishalbiswas Any other way to run Luadns either in termux or any way? Thanks!

**Comment by vishalbiswas** [comment]
add this definition in `$PREFIX/include/lauxlib.h`
```c
#define luaL_reg luaL_Reg
```
on line 35

If you have a 64-bit phone (aarch64 or x86_64) run `ln -s /system/lib64/libc.so $PREFIX/lib/libresolv.so`
else if you have a 32-bit phone (arm, x86) run `ln -sf /system/lib/libc.so $PREFIX/lib/libresolv.so`

Then you will be able to install it.

**Comment by bensh4** [comment]
@vishalbiswas , Mine is arm but i didn't add ```in -sf``` line. After your fix in line35, i ran ```luarocks install luadns``` And successfully installed. 

``` luadns 1.0.0-1 is now installed in /data/data/com.termux/files/usr (license: MIT/X11) ``` 

Thanks @vishalbiswas
