### ISSUE TITLE
Package request: rsnapshot

### ISSUE THREAD

**Issue by Ezwen** [termux/termux-packages#2463]
rsnapshot would be fantastic to have on termux, as it would make it almost possible to use an unused android phone as an efficient autonomous incremental backup server.

This would need to be combined with a possibility to easily use cron or other kind of task scheduler (see https://github.com/termux/termux-packages/issues/358).

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install rsnapshot
```
