### ISSUE TITLE
Nokogiri fails to install on latest ruby

### ISSUE THREAD

**Issue by rhanekom** [termux/termux-packages#247]
Firstly, thanks for the awesomeness that is Termux!

I've installed the latest packages and using --use--system-libraries as per similiar previous issues logged. However, the make file for Nokogiri contains direct references to /home/fornwall/..

Building the native extension fails with:

make: /home/fornwall/lib/prefix/bin/mkdir: Command not found

I'm assuming this is a package patch issue - let me know if you need more detail.

**Comment by fornwall** [comment]
Thanks - this was indeed a packaging mistake in the version of the ruby package!

This has now been fixed in version `2.3.1-1` which is available as an update through

    apt update && apt upgrade

now.

**Comment by rhanekom** [comment]
Installed perfectly now, thanks!
