### ISSUE TITLE
errors while compiling xfe

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#2474]
![screenshot_20180530-083739](https://user-images.githubusercontent.com/23075789/40696781-db3b870c-63e4-11e8-9710-4c3719f892e5.png)
![screenshot_20180530-083747](https://user-images.githubusercontent.com/23075789/40696787-e2d228e0-63e4-11e8-9e5d-aa88e3f5f52d.png)

**Comment by Hax4us** [comment]
@Auxilus I am not getting these errors can you tell which version of xfe and fox toolkit u have

**Comment by Hax4us** [comment]
![intex aqua trend_2018-05-30-11-46-45](https://user-images.githubusercontent.com/30441647/40702476-9bbb7d6a-63ff-11e8-8cb9-8bab04167ac0.png)

**Comment by KorraCatBerlin** [comment]
Do you have FOX on termux ? Please give me the files.
