### ISSUE TITLE
neovim segfault / erratic

### ISSUE THREAD

**Issue by zelhar** [termux/termux-packages#248]
Greetings

It seems that since the last version of neovim for termux it stopped working on my Nexus 9 LTE. About 1 in 7 times it might actually start normally, the rest of the time it either segfaults or prints a scroll of error messages on the screen and finally starts without properly loading init.vim (and what not else?).

**Comment by Neo-Oli** [comment]
Can you post some of these error messages?

**Comment by zelhar** [comment]
Yes of course:

: No such group or event: *.shada,*.shada.tmp.[a-z] :if !empty(v:cmdarg)|throw '++opt not supported'|endif |call writefile(shada#get_binstrings(getline(min([line("'["), line("']")]),max([line("'["), line("']")]))),expand('<afile>'),'b')
line   36:
E216: No such group or event: *.shada,*.shada.tmp.[a-z] :if !empty(v:cmdarg)|throw '++opt not supported'|endif |call writefile(shada#get_binstrings(getline(min([line("'["), line("']")]),max([line("'["), line("']")]))),expand('<afile>'),'ab')
line   38:
E216: No such group or event: *.shada,*.shada.tmp.[a-z] :execute 'rshada' fnameescape(expand('<afile>'))
Error detected while processing /data/data/com.termux/files/usr/share/nvim/runtime/plugin/spellfile.vim:
line    8:
E216: No such group or event: * call spellfile#LoadFile(expand('<amatch>'))
Error detected while processing /data/data/com.termux/files/usr/share/nvim/runtime/plugin/tarPlugin.vim:
line   28:
E216: No such group or event: tarfile::*^Icall tar#Write(expand("<amatch>"))
line   34:
E216: No such group or event: tarfile::*/*^Icall tar#Write(expand("<amatch>"))
Error detected while processing /data/data/com.termux/files/usr/share/nvim/runtime/plugin/vimballPlugin.vim:
line   30:
E216: No such group or event: *.vba.gz,*.vba.bz2,*.vba.zip,*.vba.xz^I^I^Iif expand("%")!=expand("<afile>") | exe "1sp" fnameescape(expand("<afile>"))|endif|call vimball#Decompress(expand("<amatch>"))|so %|if expand("%")!=expand("<afile>")|close|endif
line   31:
E216: No such group or event: *.vba^I^I^I^I^I^I^I^I^I^I^Iif expand("%")!=expand("<afile>") | exe "1sp" fnameescape(expand("<afile>"))|call vimball#Vimball(1)|close|else|call vimball#Vimball(1)|endif
line   33:
E216: No such group or event: *.vmb.gz,*.vmb.bz2,*.vmb.zip,*.vmb.xz^I^I^Iif expand("%")!=expand("<afile>") | exe "1sp" fnameescape(expand("<afile>"))|endif|call vimball#Decompress(expand("<amatch>"))|so %|if expand("%")!=expand("<afile>")|close|endif
line   34:
E216: No such group or event: *.vmb^I^I^I^I^I^I^I^I^I^I^Iif expand("%")!=expand("<afile>") | exe "1sp" fnameescape(expand("<afile>"))|call vimball#Vimball(1)|close|else|call vimball#Vimball(1)|endif
Error detected while processing /data/data/com.termux/files/usr/share/nvim/runtime/plugin/zipPlugin.vim:
line   40:
E216: No such group or event: zipfile:*^Icall zip#Write(expand("<amatch>"))
line   46:
E216: No such group or event: zipfile:*/*^Icall zip#Write(expand("<amatch>"))
line   49:
E216: No such group or event: *.zip,*.jar,*.xpi,*.ja,*.war,*.ear,*.celzip,*.oxt,*.kmz,*.wsz,*.xap,*.docx,*.docm,*.dotx,*.dotm,*.potx,*.potm,*.ppsx,*.ppsm,*.pptx,*.pptm,*.ppam,*.sldx,*.thmx,*.xlam,*.xlsx,*.xlsm,*.xlsb,*.xltx,*.xltm,*.xlam,*.crtx,*.vdw,*.glox,*.gcsx,*.gqsx call zip#Browse(expand("<amatch>"))
Press ENTER or type command to continue

**Comment by fornwall** [comment]
Hm, I don't really know how to debug that (I can't reproduce the problem myself)...

I just rebuilt the `neovim` package, can you update to the latest version (`apt update && apt -y upgrade`) and see if it's fixed there?

If the problem remains after updating, can you reproduce the problem when running

    nvim -u NONE

?

**Comment by zelhar** [comment]
When I start with `nvim -u NONE` neovim starts without errors. However typing from within nvim 
`:syntax on` reproduces the error. I have that command in my init.vim file too. I removed `filetype.vim` and the `.config/nvim/syntax` folder but the error persists.

**Comment by zelhar** [comment]
Has anybody else reproduced this error? This is the result after I start wit ˋnvim -u NONEˋ and then type ˋ:filetype plugin indent onˋ :

`rror detected while processing /data/data/com.termux/files/usr/share/nvim/runtime/filetype.vim:
line  972:
E216: No such group or event: *.4gl,*.4gh,*.m4gl^Isetf fgl
line  975:
E216: No such group or event: *.ini^I^I^Isetf dosini
line  978:
E216: No such group or event: inittab^I^I^Isetf inittab
line  981:
E216: No such group or event: *.iss^I^I^Isetf iss
line  984:
E216: No such group or event: *.ijs^I^I^Isetf j
line  987:
E216: No such group or event: *.jal,*.JAL^I^Isetf jal
line  990:
E216: No such group or event: *.jpl,*.jpr^I^Isetf jam
line  993:
E216: No such group or event: *.java,*.jav^I^Isetf java
line  996:
E216: No such group or event: *.jj,*.jjt^I^Isetf javacc
line  999:
E216: No such group or event: *.js,*.javascript,*.es,*.jsx   setf javascript
line 1002:
E216: No such group or event: *.jsp^I^I^Isetf jsp
line 1005:
E216: No such group or event: *.properties,*.properties_??,*.properties_??_??^Isetf jproperties
line 1006:
E216: No such group or event: *.properties_??_??_*^Icall s:StarSetf('jproperties')
line 1009:
E216: No such group or event: *.clp^I^I^Isetf jess
line 1012:
E216: No such group or event: *.jgr^I^I^Isetf jgraph
line 1015:
E216: No such group or event: *.jov,*.j73,*.jovial^Isetf jovial
line 1018:
E216: No such group or event: *.json,*.jsonp^I^Isetf json
line 1021:
E216: No such group or event: *.kix^I^I^Isetf kix
line 1024:
E216: No such group or event: *.k^I^I^Isetf kwt
line 1027:
E216: No such group or`

**Comment by vainikkaj** [comment]
I'm also experiencing this on my Nexus 9.

**Comment by Neo-Oli** [comment]
I tested it on my xperia z and z3c, but can not reproduce

**Comment by zelhar** [comment]
UPDATE: The latest 0.2 seems to work without major bugs.

**Comment by fornwall** [comment]
@zelhar Great, thanks for the update!
