### ISSUE TITLE
Provide machine readable metadata

### ISSUE THREAD

**Issue by philippgille** [termux/termux-packages#2485]
[Repology](https://repology.org/) is a useful service for app developers that monitors packages in many package repositories, so instead of having to check each package repositories on your own, you just have to check repology. I'm not affiliated with it in any way, I just found it useful.

I added an issue to the [Repology GitHub repository](https://github.com/repology/repology) to add support for Termux packages, but according to an answer by the maintainer this is currently not possible because of missing machine readable metadata. See repology/repology#628

Is there a way to change this? Or are there already ways that should make this possible?

**Comment by fornwall** [comment]
Which kind of metadata is needed? The packages are provided in an apt repository (e.g. http://termux.net/dists/stable/main/binary-aarch64/Packages for aarch64) - is that enough or is more metadata needed?

**Comment by fornwall** [comment]
I'm closing this issue as the discussion here is taking place in https://github.com/repology/repology/issues/628
