### ISSUE TITLE
Stop using $TERMUX_NDK_VERSION in packages (libc++, ndk-*)?

### ISSUE THREAD

**Issue by tomty89** [termux/termux-packages#2486]
It seems like a bad idea to me since it doesn't really help ease things up. Recently ndk-* got rebuilt / upgraded against NDK 17 but because of the "convenient" `TERMUX_PKG_VERSION=$TERMUX_NDK_VERSION`, `TERMUX_PKG_REVISION` didn't get reset. Wouldn't it have been way better if we simply had a proper commit for a bump like that?

Even more so for the not yet done libc++ rebuild / upgrade, since we would need to bump `TERMUX_PKG_REVISION` in packages that has linkage to it to trigger a rebuild anyway, it would be way less silly if the commit includes an actual bump for `TERMUX_PKG_VERSION` in libc++ from `16` to `17`, instead of relying on this pointless automation.

**Comment by xtkoba** [comment]
Already resolved.
