### ISSUE TITLE
Youtube-dl in Termux

### ISSUE THREAD

**Issue by CATASTR0PHE420** [termux/termux-packages#2494]
So I've tried to use youtube-dl in termux, so far it's working and all I've did was apt install , apt update, apt upgrade, apt install python, apt install ffmpeg, pip install youtube-dl. Whenever I try to convert any video, it successfully converts but the problem is I can't see the path location where it saves all my downloads, I'm new to this type of stuff so please help me. Thank you.

**Comment by xeffyr** [comment]
Did you check your home dir ($HOME or ~/) ? I suggest you to use parameter `--output` for youtube-dl to specify where to save downloaded files.

**Comment by CATASTR0PHE420** [comment]
Thank you for your answer, data/data/com.termux/files/home can only be accessed if your phone is rooted :/

**Comment by vishalbiswas** [comment]
use `termux-share` or download to /sdcard/ using `--output` flag
