### ISSUE TITLE
Package request: squashfuse

### ISSUE THREAD

**Issue by lars18th** [termux/termux-packages#2496]
https://github.com/vasi/squashfuse

The idea is to have the binaries inside the Termux, and with "su" (root) support, mount using native FUSE support an SquashFS image. This will provide _readonly_ mounts of, for example, images inside the SDCard.

The package has native Android support, so I feel it well be easy to incorporate to the Termux Packages repository.

I hope you agree.

**Comment by Quasic** [comment]
Maybe this should go in the root package repo?

**Comment by lars18th** [comment]
> Maybe this should go in the root package repo?

First the package needs to be compiled and checked. Right?

**Comment by lars18th** [comment]
Hi @Quasic ,

If you say that this request needs to go in the "root package repo" (http://github.com/termux/termux-root-packages), then the answer is: _perhaps_.

The idea is not only "compile" the package. And in this case, for sure it needs to be included in the "root package repo" instead of the "regular termux packages repo". However, the idea goes further!

Let me to explain it:

- If the package really works, that's it compiles and run inside Termux, and using root access you can mount in your device any squashfs image using the FUSE layer... Then you can do a "spplit" of Termux filesystem. And you can generate some read-only images of part of the Termux "filesystem" structure. This will save a lot of space (Squash is a high-compression filesystem), and you can store the images in the SD-CARD (transparently). However, you need to "mount/umount" the images after start/close Termux sessions. And this will include to manage or modify the regular Termux App.

I hope the developers can see the advantage of this mode, and try to add support for this module.

But in any case, the first step is to compile/test/include this module.
Regards.

**Comment by Quasic** [comment]
Ok, sounds interesting.

**Comment by Grimler91** [comment]
I guess this should go into termux-root-packages, we do compilation/testing there as well. I can move it later. 

It sounds interesting with the possibility to compress and store part of the filesystem elsewhere but not all users are rooted and not everyone can therefore benefit from this/use this.

**Comment by lars18th** [comment]
Hi @Grimler91 ,

> It sounds interesting with the possibility to compress and store part of the filesystem elsewhere but not all users are rooted and not everyone can therefore benefit from this/use this.

I agree with that! However, I feel it's best to have working the option to store some part of the filesystem compressed in the SD card, and after that explore the options for expand it to non-rooted users. The kernel FUSE support permits a lot of flexibility.

**Comment by Grimler91** [comment]
This issue was moved to termux/termux-root-packages#30
