### ISSUE TITLE
mdp doesn't support non-ascii characters

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#2497]
I just tried the new mdp package for termux. It doesn't display non-ascii characters like "äöü" or other unicode characters, even though according to the [demo](https://cloud.githubusercontent.com/assets/2237222/5810237/797c494c-a043-11e4-9dbd-959cab4055fa.gif) at the mdp repository it should work.

**Comment by Grimler91** [comment]
äöü works in the sample.md for me. What does it look like for you?
Could you share an example.md?


![screenshot_20180608-222044_termux](https://user-images.githubusercontent.com/18900601/41179255-651d0bd0-6b6a-11e8-8c3f-0b97286645eb.jpg)

**Comment by Neo-Oli** [comment]
Not working for me, Even with the default sample.md. 
I wonder what the difference in our environment is. I also tried it in a blank termux chroot with no dotfiles or other programs installed whatsoever.
![screenshot_20180608-224545](https://user-images.githubusercontent.com/7983745/41180278-fdfa248e-6b6d-11e8-9c8e-4640225c0106.png)

**Comment by Grimler91** [comment]
Are you using some none-standard font?

Which android version and arch is it on?
Interesting that Φ works but not äöü.

**Comment by Grimler91** [comment]
I can reproduce the problem on my arm device, android 7.

**Comment by Neo-Oli** [comment]
hmm.. I am on aarch64, but also on Android 7.

**Comment by onlurking** [comment]
This is probably an font issue, which font you are using?
Can you download [this font](https://github.com/onlurking/termux/raw/master/.termux/font.ttf) to `$HOME/.termux/font.ttf` to see if it works?

**Comment by Neo-Oli** [comment]
@onlurking But why would it be a font issue? It normally displays äüö without a problem.

**Comment by onlurking** [comment]
Yep, not a font issue, the same error is happening here too.

![](https://user-images.githubusercontent.com/10618352/41184203-23530b60-6b55-11e8-9c02-baa3101dd1c3.jpeg)

Android 6.0.1, armv7l

**Comment by Grimler91** [comment]
It's perhaps the same issue as in ttysolitaire, mentioned in https://github.com/termux/termux-packages/issues/1536. Looks very similar atleast.

**Comment by buribu** [comment]
This issue is old, but there may be some link ...
https://github.com/visit1985/mdp/issues/19

**Comment by xeffyr** [comment]
Doesn't happen on Android 8.

Since the issue doesn't happen on my device regardless of used repository (tried both for API 21 and API 24), I guess here is something libc-related.

![Screenshot_20190630-151101_Termux](https://user-images.githubusercontent.com/25881154/60396412-155fdd00-9b4a-11e9-8c41-e3186440d48e.jpg)

![Screenshot_20190630-151144_Termux](https://user-images.githubusercontent.com/25881154/60396413-1a249100-9b4a-11e9-82d0-5d8e5c950a6a.jpg)

On Android 5 device everything looks like in https://github.com/termux/termux-packages/issues/2497#issuecomment-395888733.

**Comment by buribu** [comment]
This may be the reason...

https://stackoverflow.com/questions/23820769/cross-compiled-ncurses-for-utf-8-displays-incorrectly

**Comment by xeffyr** [comment]
@buribu That's unlikely. Issue is not reproducible on Android **8**.0 and higher.

**Comment by xtkoba** [comment]
Let's just keep this open.

**Comment by xtkoba** [comment]
#5124 smells similar, and indeed `LD_PRELOAD`ing `libandroid-support.so` seems to work this around.

**Comment by Quasic** [comment]
Confirming mdp works on my Android 7 device, now. Good work!
