### ISSUE TITLE
Virtual keyboard is put in word mode with some input methods

### ISSUE THREAD

**Issue by xiaq** [termux/termux-packages#25]
With some input methods that support both a "word mode" and a "letter mode", the virtual keyboard is put in the word mode. For instance, when I write "apt" with Google Pinyin, the screen looks like:

![screenshot_2015-10-12-14-06-14](https://cloud.githubusercontent.com/assets/582021/10427514/9e9bfa2e-70ea-11e5-8dda-23476a90fcf4.png)

This is not a limitation of the input method, since in quite some circumstances like the location bar of Firefox and Chrome, the virtual keyboard is correctly put in the letter mode. I believe the behavior is influenced by some property of the text field, which termux is not setting correctly.

**Comment by fornwall** [comment]
> This is not a limitation of the input method, since in quite some circumstances like the location bar of Firefox and Chrome, the virtual keyboard is correctly put in the letter mode.

Are you sure? When I try Google Pinyin with the location bar in the latest version of both Firefox and Chrome, I get the same behaviour as in Termux with the word being visible above the keyboard - see attached screenshot when e.g. typing `google`:

![pinyin-google](https://cloud.githubusercontent.com/assets/277251/10467163/8b00a2c6-71f8-11e5-9f61-dbe8bd1f8ea1.png)

**Comment by xiaq** [comment]
@fornwall First put Google Pinyin in English mode. Use the globe button or the "En" tab button. In Chinese mode Google Pinyin will always show Chinese candidates like you showed.

**Comment by fornwall** [comment]
@xiaq Thanks, did not know that (first time using Google Pinyin)! Pushing the globe seems to toggle to the normal Google keyboard, which for me has the correct "letter mode".

However, I notice that I do not have the same layout as you (I do not have e.g. the '+' beneath 'd' which you have), could that be relevant? Do you know how to configure the normal Google Keyboard to display these (or do you use another keyboard variant)?

![eng-keyboard](https://cloud.githubusercontent.com/assets/277251/10469417/4ec4c884-7205-11e5-98e5-7c7d92b9ade8.png)

**Comment by xiaq** [comment]
@fornwall Oops, the globe button took you to Google Keyboard, not the English keyboard of Google Pinyin, which seems to have become disabled by default. If you go to the settings of Google Pinyin (accessible from Language & input in Settings) and then go to Keyboard, there is a "Show English keyboard" option. Use the English keyboard of Google Pinyin, not Google Keyboard, to reproduce my problem.

**Comment by fornwall** [comment]
Thanks! With "Show English keyboard" I'm able to reproduce the issue by using the "En" tab - will examine how to fix it.

**Comment by fornwall** [comment]
@xiaq This has now been fixed in the 0.14 update of Termux, which should be available in the Play Store as an update in a couple of hours.

Thanks for all the help finding the issue, let me know if there is any remaining problem!
