### ISSUE TITLE
Package request: keychain

### ISSUE THREAD

**Issue by jean** [termux/termux-packages#2500]
Keychain helps you to manage SSH and GPG keys in a convenient and secure manner. 
https://www.funtoo.org/Keychain

**Comment by kfiz** [comment]
+ 1. This would be so useful. I'm really surprised that we don't have this package yet. Is it problematic to get this onto android?

**Comment by GAZ082** [comment]
+1

**Comment by oxr463** [comment]
# Manual Installation

```sh
git clone https://github.com/funtoo/keychain.git
cd keychain
git checkout tags/2.8.5
mkdir -p ~/bin
cp keychain ~/bin/
export PATH="${PATH}:~/bin"
```

**Comment by kcubeterm** [comment]
Should be close
