### ISSUE TITLE
Package Request: python-tk

### ISSUE THREAD

**Issue by MS-Jahan** [termux/termux-packages#2503]
Please add the tkinter module for python. Termux now supports a few gui things so it would be interesting to test tk gui projects in termux.

**Comment by tomty89** [comment]
The thing is we don't even have tk in our repo. It's easy to include back the .py files but to build the library we need tk (so there's probably little point to include them back).

Perhaps it can be done with tk on the build host, but AFAIK, nothing GUI is in the official scope of Termux.

**Comment by segalion** [comment]
Could be great talk with [androwish](https://www.androwish.org/home/home) people to join efforts to get tcl/tk version in termux, and then python tkinter.

Python people are really lost in android world with kivy, p4a, and other projects around...

TCL/TK people are more centered (as usually) in a direct android integration, as you can see in androwish project. See i.e [borg](https://www.androwish.org/home/wiki?name=Android+facilities) where termux-api could get some great ideas...

**Comment by PySimpleGUI** [comment]
I'm trying to determine the state of tkinter using Termux.  I'm able to use tkinter using PyDroid3.  Is it available yet on Termux?  

Was this issue closed because it is out of the scope of Termux's charter or it's been completed?

**Comment by xeffyr** [comment]
> Was this issue closed because it is out of the scope of Termux's charter or it's been completed?

The state can be easily determined by `pkg search tkinter`.

```
~ $ pkg search tkinter
Sorting... Done
Full Text Search... Done
python-tkinter/stable 3.8.1-4 aarch64
  Tkinter support for Python 3

~ $
```
