### ISSUE TITLE
SSH with out SSH-KEY

### ISSUE THREAD

**Issue by DovaMerith** [termux/termux-packages#2508]
I Am a student and I cant ssh into termux becuase of how its SSHD works, Im using a NaCL plugin that lets me ssh, but it only supports the command
>ssh user@ip:port
and i cant use a SSH-KEY with it due to this, how do i enable password logins? I am rooted and have full control of my system, running Resurection Remix 5.x, Android AOSP 7.1.2 Lineage OS based, how would i go about this?

**Comment by Grimler91** [comment]
There is an [open PR to add password support](https://github.com/termux/termux-packages/pull/2198), you could sign up to my test repo and update openssh to test it:
ˋˋˋ
pkg install dirmngr
apt-key adv --keyserver pgp.mit.edu --recv A46BE53C 
mkdir -p $PREFIX/etc/apt/sources.list.d  
echo "deb https://grimler.se testing misc" > $PREFIX/etc/apt/sources.list.d/grimler-test.list 
apt update
ˋˋˋ

**Comment by DovaMerith** [comment]
Alright, I set up the password and all that stuff, and restarted the phone, Now my tool simply says that the connection was refused,

and when i try it as root (Have to reinstall the app afterwards) It gives me the same error.

I am forced to reinstall Termux due to file permissions breaking when i run them as TSU

**Comment by Grimler91** [comment]
Yeah you shouldn't run stuff as root if you don't really know what you are doing, that breaks stuff.

I can't know why your tool says connection was refused.
Have you started sshd after rebooting the phone?

**Comment by DovaMerith** [comment]
Yes,
