### ISSUE TITLE
Package Request: Softether Client

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#2509]
SoftEther VPN ("SoftEther" means "Software Ethernet") is one of the world's most powerful and easy-to-use multi-protocol VPN software.

**Comment by xeffyr** [comment]
For tun/tap root is needed. So if `Softether Client` uses tun/tap, then probably it belongs to [termux-root-packages](https://github.com/termux/termux-root-packages).

**Comment by DRSDavidSoft** [comment]
@xeffyr I'm not sure if the client package necessarily requires tun/tap to work, so it might still be eligible for the non-root repo here.

However, shouldn't using `su -c package` suffice to run packages as root?

Also, can you have a look at #2883? The **server** package I'm sure doesn't _require_ tun/tap.

The SoftEther team has made it really easy to cross compile their software for most platforms.
