### ISSUE TITLE
Package request: traceroute

### ISSUE THREAD

**Issue by GIJack** [termux/termux-packages#2510]
Requesting tcpdump package. Eponymous TCP/IP debugging tool - http://www.tcpdump.org/

http://traceroute.sourceforge.net/ - is by far the most powerful traceroute implementation in existence with support for arbitrary protocols and ports.

**Comment by Auxilus** [comment]
@GIJack  tcpdump is already available in github.com/termux/termux-root-packages

traceroute is available in package tracepath
`pkg install tracepath`

**Comment by GIJack** [comment]
tracepath is **NOT** linux traceroute

**Comment by Auxilus** [comment]
oO didn't know that :p

**Comment by GIJack** [comment]
"linux traceroute" specifically has support fo TCP, UDP and ICMP, and allows you to specify and arbitrary port verrry useful

**Comment by benlavender** [comment]
We absolutely should have these available.
