### ISSUE TITLE
package request: GCC

### ISSUE THREAD

**Issue by GIJack** [termux/termux-packages#2511]
Requesting GCC and deps be available.

**Comment by xeffyr** [comment]
@its-pointless provides GCC. Check his pages: https://github.com/its-pointless/gcc_termux, https://github.com/its-pointless/its-pointless.github.io.

**Comment by GIJack** [comment]
Still would like first party support, as well as a buildessentials

**Comment by xeffyr** [comment]
@GIJack GCC was removed from official repositories: https://github.com/termux/termux-packages/issues/407

Now only from @its-pointless repository

**Comment by Grimler91** [comment]
I think we are unlikely to re-add it, since it is available from third-party source and we have clang/llvm.
