### ISSUE TITLE
package request: mat (cli version)

### ISSUE THREAD

**Issue by GIJack** [termux/termux-packages#2513]
https://mat.boum.org - Metadata Anonymization tool.

I would like to see the CLI version on termux

**Comment by Grimler91** [comment]
Seems to be installable from pip under the name "metadata"?
Have you tried `pip install metadata`?

**Comment by GIJack** [comment]
ain't got time for that language specific package. need a system package

**Comment by xeffyr** [comment]
This is not going to be packaged as relies on external python modules.
Install package with `pip` instead.
