### ISSUE TITLE
TERMUX_PKG_DEPENDS="nodejs || nodejs-current"

### ISSUE THREAD

**Issue by laem** [termux/termux-packages#2518]
Is there a way to do that ?
I'd like to use yarn with the current version of nodejs, not the LTS version.

**Comment by laem** [comment]
In case someone has the same need, you can also just install yarn with : 
`curl -o- -L https://yarnpkg.com/install.sh | bash`

**Comment by Grimler91** [comment]
The syntax is "nodejs | nodejs-current" (see https://www.debian.org/doc/debian-policy/#syntax-of-relationship-fields), I guess this would be possible.

**Comment by laem** [comment]
Thanks for your help. A simple PR edit of [yarn/build.sh](https://github.com/termux/termux-packages/blob/master/packages/yarn/build.sh)  with that new line 
```
TERMUX_PKG_DEPENDS="nodejs | nodejs-current"
```
should suffice then ?

**Comment by Grimler91** [comment]
Yes, I believe so. Feel free to open a PR (and remember to bump the package, i.e. set TERMUX_PKG_REVISION=1) :)
