### ISSUE TITLE
vimdiff E97 cannot create diffs with busybox diff, just diff from diffutils

### ISSUE THREAD

**Issue by Quasic** [termux/termux-packages#2528]
I am investigating what causes E97 cannot create diffs in vimdiff. I am not sure it's a termux issue, but vim seems to be operating normally... Can anyone else reproduce? ```vimdiff filea fileb```
For me, it displays the above error message before opening the files. The log (using the -V9 switch) shows it is using tmp:
diff -a /data/data/com.termux/files/usr/tmp/vc69YWW/0 /data/data/com.termux/files/usr/tmp/vc69YWW/1 >/data/data/com.termux/files/usr/tmp/vc69YWW/2
(I accidentally deleted the redirection at the end, but I think it was just for stderr.)
It tries again without -a before giving up.

Tested on 2 devices after PKG up:
Android 5:
`````
$ uname -a
Linux localhost 3.10.49-gecffe94 #1 SMP PREEMPT Thu Jan 14 10:06:48 KST 2016 armv7l Android
`````
Android 7:
`````
$ uname -a
Linux localhost 3.18.35 #1 SMP PREEMPT Tue Nov 21 13:15:24 KST 2017 armv7l Android
`````

I am hoping to find a way to trace the problem down further...
I'm also thinking of trying to use a MyDiff function.

I thought I had seen this before, so feel free to mark this duplicate; I just couldn't find it.

**Comment by xeffyr** [comment]
@Quasic Try `pkg install diffutils`. After this it works.

**Comment by Quasic** [comment]
```pkg in diffutils``` fixes it, but I'm still curious...
Probably an incompatibility with BusyBox, though.

**Comment by Grimler91** [comment]
Thanks for finding the other issue @Quasic! 
I would suggest adding vimdiff as SUGGESTS or RECOMMENDS, but not as DEPENDS as it imho isn't really a necessary dependency for the main functionalities of vim.
