### ISSUE TITLE
error while installing python-levenshtein

### ISSUE THREAD

**Issue by T4P4N** [termux/termux-packages#2529]
![screenshot_2018-06-18-21-55-21-557_com termux](https://user-images.githubusercontent.com/32695903/41549301-02c8b55c-7343-11e8-9cb2-abcc43ee8b74.png)
Any Solutions?

**Comment by Hax4us** [comment]
`apt install libcrypt-dev`

**Comment by T4P4N** [comment]
@Hax4us Thank You Very Brother!

**Comment by TheZnuf** [comment]
Same error here ?

`ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-qyn2n3ds/python-Levenshtein/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-qyn2n3ds/python-Levenshtein/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-296wj426/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.`

If i try to install libcrypt-dev :
```
Package libcrypt-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libcrypt

E: Package 'libcrypt-dev' has no installation candidate
```
libcrypt is well installed

**Comment by xeffyr** [comment]
>If i try to install libcrypt-dev :

Dev packages are now merged with regular packages and not available separately.
There even suggestion in your error message:
```
However the following packages replace it:
  libcrypt
```

**Comment by TheZnuf** [comment]
Thank you, 
but libcrypt is already installed and had this error.

**Comment by xeffyr** [comment]
Then make sure that `clang` is installed.
To install python-levenshtein, you need only 2 packages: `python` and `clang`. That's all.

**Comment by TheZnuf** [comment]
It was my problem. Thanks a lot !
