### ISSUE TITLE
termux-location script isn't working

### ISSUE THREAD

**Issue by ginabythebay** [termux/termux-packages#253]
It appears that I was copied from termux-notifcation and only the help was changed, mostly.

. running termux-location -h results  in help that talks about termux-notification
. the help says there is -p option but when I try to set it, the script says that is an illegal option

**Comment by Neo-Oli** [comment]
The `-p` option requires an argument. `termux-location -p network` for example.

**Comment by ginabythebay** [comment]
Yes.  That is what I tried to set it to but it still gave me an error message saying that -p was an illegal option,

**Comment by fornwall** [comment]
I've fixed the typo in the help output of `termux-location` that incorrectly said termux-notification, run

    apt update && apt upgrade

to get the update.
