### ISSUE TITLE
How to setup cava&stag on termux

### ISSUE THREAD

**Issue by T4P4N** [termux/termux-packages#2530]
I Want to Setup cava and stag in termux
is there any proper article or wiki for configuring cava & stag
Suggestions & solutions are Highly Appreciated :)

**Comment by T4P4N** [comment]
@Neo-Oli How to configure cava in termux

**Comment by Neo-Oli** [comment]
You need to call `mpc outputs` to list all outputs and then call `mpc enable <NUMBER>` for the ncmpcpp visualizer. As for stag, try `man stag`

**Comment by T4P4N** [comment]
Ok,Thanks
