### ISSUE TITLE
error while installing gem

### ISSUE THREAD

**Issue by T4P4N** [termux/termux-packages#2533]
![screenshot_2018-06-19-11-33-11-817_com termux](https://user-images.githubusercontent.com/32695903/41579448-a3e39a80-73b4-11e8-895c-b7d7fd51865d.png)
Any Solutions!

**Comment by xeffyr** [comment]
Package `ruby-dev` installed ?

**Comment by T4P4N** [comment]
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ apt install ruby-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  ruby-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 48.7 kB of archives.
After this operation, 373 kB of additional disk space will be used.
Get:1 https://termux.net stable/main aarch64 ruby-dev aarch64 2.5.1 [48.7 kB]
Fetched 48.7 kB in 1s (34.8 kB/s)
Selecting previously unselected package ruby-dev.
(Reading database ... 15920 files and directories currently installed.)
Preparing to unpack .../ruby-dev_2.5.1_aarch64.deb ...
Unpacking ruby-dev (2.5.1) ...
Setting up ruby-dev (2.5.1) ...
$ gem install ruby_terminal_games
Building native extensions. This could take a while...
ERROR:  Error installing ruby_terminal_games:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/curses-1.2.4/ext/curses
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20180619-29093-1xb8a14.rb extconf.rb
checking for tgetent() in -ltinfo... no
checking for tgetent() in -ltermcap... no
checking for ncursesw/curses.h... no
checking for ncurses.h... no
checking for ncurses/curses.h... no
checking for curses_colr/curses.h... no
checking for curses.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --with-curses-dir
        --without-curses-dir
        --with-curses-include
        --without-curses-include=${curses-dir}/include
        --with-curses-lib
        --without-curses-lib=${curses-dir}/lib
        --with-ncurses-dir
        --without-ncurses-dir
        --with-ncurses-include
        --without-ncurses-include=${ncurses-dir}/include
        --with-ncurses-lib
        --without-ncurses-lib=${ncurses-dir}/lib
        --with-termcap-dir
        --without-termcap-dir
        --with-termcap-include
        --without-termcap-include=${termcap-dir}/include
        --with-termcap-lib
        --without-termcap-lib=${termcap-dir}/lib
        --with-tinfolib
        --without-tinfolib
        --with-termcaplib
        --without-termcaplib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/curses-1.2.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/curses-1.2.4 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/curses-1.2.4/gem_make.out
$

**Comment by T4P4N** [comment]
Still Throwing error!

**Comment by Grimler91** [comment]
@T4P4N Read the error message and install the missing headers. Headers are found in the -dev packages.

**Comment by T4P4N** [comment]
@remo7777 Thanks bro!
