### ISSUE TITLE
Package request: nginx

### ISSUE THREAD

**Issue by zejji** [termux/termux-packages#255]
I realise this is a significant request, but adding nginx to termux would be very helpful in allowing Android to be used as a feasible web development platform (especially since emacs is already available). For a usable LEMP platform, this would also require a number of additional php-related packages to be installed, namely:

php5-cli
php5-intl
php5-cgi
php5-fpm
php5-sqlite
php5-mysqlnd
php5-mcrypt
php5-gd
php5-xdebug
phpmyadmin
mariadb-server *
mariadb-client *

(*) I notice there is already a request for mariadb (https://github.com/termux/termux-packages/issues/216).

**Comment by sebfindling** [comment]
They don't really care about us

**Comment by fornwall** [comment]
Thanks to @vishalbiswas there is now a nginx package available! Install with:

    packages install nginx

**Comment by TheDiamondYT1** [comment]
@fornwall wtf is the packages command? I use apt

**Comment by Rudloff** [comment]
It is a wrapper for apt. You can use the one you prefer.
