### ISSUE TITLE
How to take screenshot?

### ISSUE THREAD

**Issue by TonyStark** [termux/termux-packages#2556]
Is there any screencap command available for termux??

**Comment by Hax4us** [comment]
@TonyStark if your phone is rooted then you can take screenshot from this command
`/system/bin/screencap -p /sdcard/screenshot.png`

**Comment by TonyStark** [comment]
I think that is not working
```
$ /system/bin/screencap -p screenshot.png
CANNOT LINK EXECUTABLE "/system/bin/screencap": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib64/libunwind.so"...
Aborted
$
```

**Comment by Hax4us** [comment]
Install __tsu__ package `apt install tsu`
Then grant root permission `tsu -p`
Now execute the command `screencap -p /sdcard/screenshot.png`

**Comment by tomty89** [comment]
`(unset LD_LIBRARY_PATH; /system/bin/screencap -p screenshot.png)`

**Comment by Hax4us** [comment]
@tomty89 without root ?

**Comment by tomty89** [comment]
@Hax4us no assuming root. apparently without root it captures/outputs nothing (empty file created).

**Comment by TonyStark** [comment]
Okay tsu things got work.
Thank you
