### ISSUE TITLE
Package request encryption

### ISSUE THREAD

**Issue by erji44** [termux/termux-packages#256]
Termux is next best thing having a proper linux system on a phone.
Given android is not linux, Termux just completes android.
I'm trying to compile cryptsetup/LUKS for termux but how do I go about doing it?
There is no tool that does encryption in android(at least not linux way), would be appreciated if someone could point in the right direction on how to compile cryptsetup on termux.
With cryptsetup you could create an encrypted container and mount it locally after creating a file with dd.
So, dd to create file > cryptsetup to encrypt container > format desired file system in it > mount on local folder, and this way you have a protected file system under android.
Once I find out how to compile cryptsetup, I will post a step by step tutorial on how to do the above. 
Home page is: https://gitlab.com/cryptsetup/cryptsetup

**Comment by joelyoungblom** [comment]
👍

**Comment by pawamoy** [comment]
Any news on this @erji44 ?

**Comment by xeffyr** [comment]
@pawamoy We already have cryptsetup in https://github.com/termux/termux-root-packages. It looks like someone forget to close this issue.

```
pkg install root-repo
pkg install cryptsetup
```

Don't forget that `cryptsetup` requires root permissions.

***

@Grimler91 this can be closed.
