### ISSUE TITLE
Package Request: Ampache

### ISSUE THREAD

**Issue by T4P4N** [termux/termux-packages#2565]
Ampache is a web based audio/video streaming application and file manager allowing you to access your music & videos from anywhere, using almost any internet enabled device.
https://github.com/ampache/ampache/

**Comment by remo7777** [comment]
gui

**Comment by T4P4N** [comment]
web ui

**Comment by remo7777** [comment]
Android app present on playstore

https://github.com/ampache/ampache/wiki/Clients

**Comment by T4P4N** [comment]
it's a client app, I need server package.

**Comment by remo7777** [comment]
what about caddy ??

**Comment by remo7777** [comment]
`curl https://getcaddy.com | bash`

**Comment by T4P4N** [comment]
caddy is a web sever not a media server app.

**Comment by remo7777** [comment]
https://github.com/termux/termux-packages/issues/92

**Comment by T4P4N** [comment]
i don't need this shit anymore. Mpd rocks!!!
