### ISSUE TITLE
Error: Port request not allowed

### ISSUE THREAD

**Issue by Cimmanuel** [termux/termux-packages#2567]
I just started using Termux. Why? I want to start building websites on my phone. Whenever I start my django server and copy the url `http://127.0.0.1:8000` on my browser, I get `Error: Port request not allowed`. What's wrong?

**Comment by okiedokie78** [comment]
Check your setting in the browses might need configured

**Comment by Cimmanuel** [comment]
If what you mean is to try ports lower than 8000, I have tried and it's still the same

**Comment by vishalbiswas** [comment]
Is the port already being used by some other application?

**Comment by okiedokie78** [comment]
what server are you using

**Comment by xeffyr** [comment]
@Cimmanuel I just created new project and it works:
```
$ django-admin startproject testproj
$ cd testproj
$ python manage.py runserver 
Performing system checks...

System check identified no issues (0 silenced).

You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

June 22, 2018 - 10:27:22
Django version 1.11.12, using settings 'testproj.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

![screenshot_20180622-102856_samsung internet](https://user-images.githubusercontent.com/25881154/41763581-40900388-7607-11e8-8460-2609d9d17a60.jpg)

Which version of Django you have ? For me, v1.11.12 works ok.

**Comment by xeffyr** [comment]
@Cimmanuel Check your settings.py, maybe you have something like that: `ALLOWED_HOSTS = ['127.0.0.1:8000']`. Try to remove port numbers from ALLOWED_HOSTS.

**Comment by Cimmanuel** [comment]
@xeffyr ALLOWED_HOSTS is an empty list

**Comment by Cimmanuel** [comment]
@xeffyr I'm using Django2.0

**Comment by Cimmanuel** [comment]
@okiedokie78 The built-in development server Django provides

**Comment by Cimmanuel** [comment]
@vishalbiswas I don't think so, but if that's what's happening, I have changed my port severally and still getting the same error

**Comment by Cimmanuel** [comment]
![](https://i.imgur.com/37I59Wt.png)

This is my server running

**Comment by Cimmanuel** [comment]
![](https://i.imgur.com/ty998Qy.png)

This is what my browser says

**Comment by Cimmanuel** [comment]
@tomty89 Sorry, what's that?

**Comment by Cimmanuel** [comment]
@xeffyr How do I go about this?

**Comment by xeffyr** [comment]
I don't know. Maybe something with your device or network.
Try to enable 'Airplane mode' on your device and check if you can access `http://127.0.0.1:8000` when django server is running.

**Comment by Cimmanuel** [comment]
@xeffyr It still doesn't work.

**Comment by Cimmanuel** [comment]
@xeffyr Could it be because my device isn't rooted?

**Comment by tomty89** [comment]
More like its ROM is built with some malware? Couldn't really find anything about this iProxy-WISP on the Internet myself.

Have you checked whether you see this page *without* the django server running?

**Comment by Grimler91** [comment]
@cimmanuel what device are you using?

**Comment by okiedokie78** [comment]
Uninstall your browser and install it back on without logging in

**Comment by vishalbiswas** [comment]
are you inside a vpn?

**Comment by Cimmanuel** [comment]
@Grimler91 Samsung Galaxy S6 Edge

**Comment by Cimmanuel** [comment]
@okiedokie78 Will do

**Comment by Cimmanuel** [comment]
@vishalbiswas No, I'm not

**Comment by Cimmanuel** [comment]
@tomty89 What do you mean?

**Comment by Cimmanuel** [comment]
It finally works. I just had to run on port 1024. Thanks everyone!

**Comment by fornwall** [comment]
I'm sorry, but I don't think there is anything that can be done from the side of Termux here, unfortunately.
