### ISSUE TITLE
Too many symlinks for a file

### ISSUE THREAD

**Issue by bensh4** [termux/termux-packages#2571]
![](https://i.imgur.com/S8kFJpJ.png)

Once I Symlinked ```nikto.pl``` to ```$PREFIX/bin``` and later I removed it. When I tried to Symlink again; it is saying "Too many symlinks"
Then i removed again  and tried. But same error. Is there any way to unlink this? Will unlinking fix this? Screenshot provided!

![](https://i.imgur.com/dLOMZyR.png)

**Comment by bensh4** [comment]
Linked with ```ln -s nikto/program/nikto.pl $PREFIX/bin```

**Comment by bensh4** [comment]
Bro. As you above said , using ``` ln -s /nikto/program/nikto.pl $PREFIX/bin ```  it will Symlink. But while trying to execute,it is saying too many symlinks exist. I think there's something with permission? It's in a red color after Symlink.
![](https://i.imgur.com/uR9CWDE.png)

**Comment by tomty89** [comment]
Where exactly is this nikto.pl? (I mean the original file, not the symlink you create)

And what does `realpath` return for the original file?

Does executing the original file with its full path returns the same error?

**Comment by Hax4us** [comment]
@bensh4 you are creating link in wrong way as I said __always use full path__ .
I am assuming your nikto folder is in home directory of termux so use __$HOME__  as prefix with your path in command i.e, `ln -s $HOME/nikto/program/nikto.pl $PREFIX/bin/`

**Comment by bensh4** [comment]
Nikto.pl is a python script. While we clone from GitHub, it would be in ```$HOME/nikto/program/nikto.pl```
It is a very tedious task to go into /nikto/program/ and execute nikto.pl.
So I Symlinked nikto.pl with $PREFIX/bin and it worked fine for me. 
After a bit I unlinked(removed)the file from /bin and tried linked to link nikto.pl again.
Then it's showing too many symlinks.
I also tried linking by changing the script name. But it didn't work either.
![](https://i.imgur.com/JSuLj38.png)

**Comment by Hax4us** [comment]
Copy paste my command (given above)

**Comment by bensh4** [comment]
@Hax4us Thanks. I just added $HOME   before /nikto. But I'm wondering why.? Because, /nikto.pl is already in $HOME  so I didn't add $HOME

**Comment by Hax4us** [comment]
You were giving relative path instead of absolute path which will not work if you are not using `-r` option of `ln`.
`-r` option allow __relative path__ 
Google will help you to find more about __absolute and relative path__

**Comment by tomty89** [comment]
It would have worked as well if he used the *right* relative path:
```
$ ln -s ../../home/nikto/program/nikto.pl $PREFIX/bin
$ readlink $PREFIX/bin/nikto.pl
../../home/nikto/program/nikto.pl
$ readlink -f $PREFIX/bin/nikto.pl
/data/data/com.termux/files/home/nikto/program/nikto.pl
$ nikto.pl
Hello World
$
```

**Comment by tomty89** [comment]
This is what `-r` really for:
```
$ ln -sf $HOME/nikto/program/nikto.pl $PREFIX/bin
$ readlink $PREFIX/bin/nikto.pl
/data/data/com.termux/files/home/nikto/program/nikto.pl
$ ln -sfr $HOME/nikto/program/nikto.pl $PREFIX/bin
$ readlink $PREFIX/bin/nikto.pl
../../home/nikto/program/nikto.pl
$
```
