### ISSUE TITLE
updatedb does not default to /

### ISSUE THREAD

**Issue by felagund** [termux/termux-packages#2572]
When installing mlocate and running `updatedb`, it scans just some subdirectory (I suspect only something that "belongs" to termux"). However, running `updatedb --help` says that `updatedb -U` defaults to `/` which is not the case. Running `updatedb -U /` indexes all of android filesystem (with the caveat that I am not sure it sees all the files when run as non-root, when run as root, locate cannot be used by non-root user without fixing permissions of the database).

There are two solutions:
1) Fix the output of the help command to point to the default directory to search
2) Make the default `/` (which is what I would prefer, but I am not sure about others).

**Comment by felagund** [comment]
Hm. On the second try (and reinstalling Termux from FDroid instead of Google Play), I cannot get locate to work under non-root user. It always complains:
`locate: can not open `/data/data/com.termux/files/usr/var/mlocate/mlocate.db': Permission denied`

Even when I change back ownership of the file to non-root user:

    ls -al /data/data/com.termux/files/usr/var/mlocate
    total 20592
    drwx------    2 u0_a119  u0_a119       4096 Jun 23 18:41 .
    drwx------    9 u0_a119  u0_a119       4096 Jun 23 18:11 ..
    -rw-------    1 u0_a119  u0_a119   21074202 Jun 23 18:41 mlocate.db

I might have forget to exit the root session when I claimed to make it work for non-root as well, I am not sure. Any ideas?

**Comment by xeffyr** [comment]
@felagund Android also sets SELinux labels so after root you will have to do `/system/bin/restorecon -R /data/data/com.termux/files/usr`

**Comment by felagund** [comment]
Thanks. Worked like a charm. The original report still stands though.

**Comment by xeffyr** [comment]
As on recent Android versions rootfs is not readable by regular applications, making the `/` as default search directory will just make `updatedb` without specifying additional arguments useless for non-rooted users.

`updatedb` will search `/data/data/com.termux/files` by default as was before. Those who need full search and have root can use `updatedb -U /`.
