### ISSUE TITLE
Option to turn off persistent notification

### ISSUE THREAD

**Issue by felagund** [termux/termux-packages#2573]
It seems that when I run Termux, it puts a persistent notification informing me on the number of sessions I have opened. Could this be optionally turned off?

**Comment by Quasic** [comment]
It also used to give a wake lock control and a way to terminate the app, but it seems to be missing in the one I am using on Android 7. I expect to update soon, and I'll see if it comes back.

**Comment by felagund** [comment]
Ok, I blocked it. But I still think this should be configurable from within - this way if in the future Termux starts using notifications for something useful, I will never know.
I am on 7.1 too.

**Comment by xeffyr** [comment]
@felagund Notification needed to keep Termux service running. Without notification there high chance that it will be killed by Android.

**Comment by Quasic** [comment]
You can also access the notification settings in settings - apps - Termux

**Comment by fornwall** [comment]
As @xeffyr says, the notification is needed to keep the Termux service running.

**Comment by Quasic** [comment]
The phone I am on kills it anyway, but I still prefer the notification.

**Comment by ljcucc** [comment]
I have the same problem on Android 9.

**Comment by xeffyr** [comment]
@ljcucc Refer to https://github.com/termux/termux-packages/issues/2573#issuecomment-399700868, https://github.com/termux/termux-packages/issues/2573#issuecomment-402150492. Notification won't be removed from Termux.
