### ISSUE TITLE
Unable to run ctags on Amazon Fire HD 10 tablet

### ISSUE THREAD

**Issue by kholia** [termux/termux-packages#2575]
System details,

```
$ uname -a
Linux localhost 3.18.19+ #1 SMP PREEMPT Thu Mar 22 21:49:02 UTC 2018 armv8l Android
```

The device is a Amazon Fire HD 10 tablet.

Termux and all packages are current as of today (22-June-2018).

```
$ ctags -R
CANNOT LINK EXECUTABLE DEPENDENCIES: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit
ctags: cannot sort tag file : Success
```

I have seen a similar error mesage in some others packages as well.

I wonder if the tablet is running a 32-bit OS or a 64-bit one.

**Comment by kholia** [comment]
The `unset LD_PRELOAD` trick works fine. Thanks!

Output of `termux-info`,

```
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.19+ #1 SMP PREEMPT Thu Mar 22 21:49:02 UTC 2018 armv8l Android
Termux-packages arch:
arm
Android version:
5.1.1
Device manufacturer:
Amazon
Device model:
KFSUWI
```

**Comment by xeffyr** [comment]
> System information:
Linux localhost 3.18.19+ #1 SMP PREEMPT Thu Mar 22 21:49:02 UTC 2018 armv8l Android
Termux-packages arch:
arm

Something strange. You have AArch64 (armv8) CPU but packages arch is ARM.

**Comment by Grimler91** [comment]
It's probably one of those devices that is 64 bit but installs android as 32 bit. I don't understand why ctags is/wants to be 64 bits though, unless it loads some lib in /system/lib(64).

**Comment by kholia** [comment]
Here is the output,

```
$ env -i /system/bin/getprop | grep abi
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
```

This seems to be problematic to me.

The `/system/bin/logcat` file is 64-bit on this system.

**Comment by xeffyr** [comment]
@kholia Your device specifies only 32bit ARM in abi list and this is a source of problem.

**Comment by kholia** [comment]
What can I do about this? Can I somehow force usage of a 64-bit ARM ABI in Termux despite what `getprop` says? Is such a thing (64-bit ARM ABI) actually supported by my device?

**Comment by joakim-noah** [comment]
Huh, that's strange: I guess Amazon is using a 64-bit kernel and userland but runs all apps in 32-bit mode, which is somehow confusing Termux?

**Comment by fornwall** [comment]
Termux does this to determine which arch to install (from [TermuxInstaller.java](https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/TermuxInstaller.java#L192)):

```java
        // Note that we cannot use System.getProperty("os.arch") since that may give e.g. "aarch64"
        // while a 64-bit runtime may not be installed (like on the Samsung Galaxy S5 Neo).
        // Instead we search through the supported abi:s on the device, see:
        // http://developer.android.com/ndk/guides/abis.html
        // Note that we search for abi:s in preferred order (the ordering of the
        // Build.SUPPORTED_ABIS list) to avoid e.g. installing arm on an x86 system where arm
        // emulation is available.
        for (String androidArch : Build.SUPPORTED_ABIS) {
            switch (androidArch) {
                case "arm64-v8a": return "aarch64";
                case "armeabi-v7a": return "arm";
                case "x86_64": return "x86_64";
                case "x86": return "i686";
            }
        }
```

Here `Build.SUPPORTED_ABIS` is defined as:

```java
    /**
     * An ordered list of ABIs supported by this device. The most preferred ABI is the first
     * element in the list.
     *
     * See {@link #SUPPORTED_32_BIT_ABIS} and {@link #SUPPORTED_64_BIT_ABIS}.
     */
    public static final String[] SUPPORTED_ABIS = getStringList("ro.product.cpu.abilist", ",");
```

I would say that the output provided by @kholia above,

```sh
$ env -i /system/bin/getprop | grep abi
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
```

is a bug by the device manufacturer, as `ro.product.cpu.abilist` does not include 64-bit arm at all.

**Comment by tomty89** [comment]
Since `arm64-v8a` is found and only found in `ro.product.cpu.abi` on such devices, perhaps we can compare `ro.product.cpu.abilist[0]` against it before the switch:
https://android.googlesource.com/platform/frameworks/base/+/eff258c3050e260b67399432357c7d79baec7916
*If* we can do the `getString` or equivalent in our app.

Btw wonder if `LD_LIBRARY_PATH=$PREFIX/lib:/system/lib` could be a good workaround for this...

**Comment by tomty89** [comment]
The OP's ROM is probably more off than that though. I managed to set up an arm prefix manually on my aarch64 phone, and running ctags without a target works fine with termux-exec:
```
$ ls -l ..
total 12
drwx------ 16 u0_a312 u0_a312 4096 Jul  3 23:16 home
lrwxrwxrwx  1 u0_a312 u0_a312    5 Jul  3 23:03 usr -> usr32
drwx------ 10 u0_a312 u0_a312 4096 Jul  3 22:22 usr32
drwx------ 12 u0_a312 u0_a312 4096 Jul  3 22:21 usr64
$ ctags
ctags: No files specified. Try "ctags --help".
$ ../usr64/bin/ctags
CANNOT LINK EXECUTABLE "../usr64/bin/ctags": "/data/data/com.termux/files/usr32/lib/libtermux-exec.so" is 32-bit instead of 64-bit
Aborted
$ file ../usr/bin/ctags
../usr/bin/ctags: ELF 32-bit LSB pie executable ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
$ file /system/bin/linker
/system/bin/linker: ELF 32-bit LSB pie executable ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[md5/uuid]=c491b67856cbe8005971ba52a37e3268, not stripped
$ file ../usr64/bin/ctags
../usr64/bin/ctags: ELF 64-bit LSB pie executable ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped
$ file /system/bin/linker64
/system/bin/linker64: ELF 64-bit LSB pie executable ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[md5/uuid]=3234339c246c3a427ac353fb1cc2eeeb, not stripped
$
```
As you can see, only running 64-bit ctags errors out (and it would continue to error out expectedly against other libraries in the prefix when `LD_PRELOAD` is unset).

Though the 32-bit `ctags` would error out if a target is specified, as somehow it tries to run `/system/bin/sh` then:
```
$ printenv PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
$ touch test
$ ctags test
CANNOT LINK EXECUTABLE "sh": "/data/data/com.termux/files/usr32/lib/libtermux-exec.so" is 32-bit instead of 64-bit
ctags: cannot sort tag file : No such file or directory
$ termux-chroot ctags test
proot error: '/system/bin/sh' is a 64-bit program whereas this version of proot handles 32-bit programs only
ctags: cannot sort tag file : No such file or directory
proot error: trying to remove a directory outside of '/data/data/com.termux/files/usr/tmp/', please report this error.

$ /system/bin/sh -c "echo -n"
CANNOT LINK EXECUTABLE "/system/bin/sh": "/data/data/com.termux/files/usr32/lib/libtermux-exec.so" is 32-bit instead of 64-bit
Aborted
$ sh -c "echo -n"
$ unset LD_PRELOAD
$ /system/bin/sh -c "echo -n"
$ ctags test
$
```
