### ISSUE TITLE
proot: termux-chroot does not work on Nexus 9 

### ISSUE THREAD

**Issue by vainikkaj** [termux/termux-packages#258]
Installing latest version of *proot* and running `termux-chroot`gives following error:
```
proot warning: can't set the syscall number: Invalid argument
proot warning: can't set the syscall number: Invalid argument
proot warning: can't set the syscall number: Invalid argument
proot warning: can't set the syscall number: Invalid argument
proot warning: can't set the syscall number: Invalid argument
proot warning: can't set the syscall number: Invalid argument
proot info: vpid 1: terminated with signal 11
```
Full strace available at https://gist.github.com/vainikkaj/122b795b286ad3849e1e9be74e450522

**Comment by fornwall** [comment]
Can you attach the output of running

    uname -a

Perhaps it's something with the kernel version or configuration on the Nexus 9.

**Comment by vainikkaj** [comment]
```
$ uname -a
Linux localhost 3.10.40-gcc76e44 #1 SMP PREEMPT Fri Mar 25 15:18:18 UTC 2016 aarch64 Android
```

**Comment by fornwall** [comment]
Can you test if setting

    export PROOT_NO_SECCOMP=1

before running termux-chroot makes a difference?

**Comment by vainikkaj** [comment]
Unfortunately, still broken even with exported variable. Output is exactly the same as before.

**Comment by michalbednarski** [comment]
This strace is for `termux-chroot` wrapper script which prepares arguments and launches `proot`, could You check if just simple `proot ls` works and provide strace for it if it's enough to cause error (otherwise we'll have to try adding other arguments that were provided by `termux-chroot` script)

**Comment by vainikkaj** [comment]
Running `proot ls`also fails.
```
$ proot ls
proot warning: can't set the syscall number: Invalid argument
proot warning: can't set the syscall number: Invalid argument
proot info: vpid 1: terminated with signal 11
```
[strace output](https://gist.github.com/vainikkaj/0f004bc104d83f50b869e74b11e27770)

**Comment by michalbednarski** [comment]
I've noticed that ARM64 build of proot shouldn't have code path with this message, which suggests that ARM64 build of PRoot in Termux was compiled without `ARCH_ARM64` defined.

https://github.com/proot-me/PRoot/blob/f393b4daf9bfd6d034cf2c8dd56d44f135b08e93/src/tracee/reg.c#L300-L321

**Comment by fornwall** [comment]
@michalbednarski We're building from the next branch, so there is `can't set the syscall number` path also for ARM64:

https://github.com/proot-me/PRoot/blob/next/src/tracee/reg.c#L302

**Comment by michalbednarski** [comment]
Ah, that way, I was a bit lost about different `ptrace()` in source and strace.

```
ptrace(PTRACE_SETREGSET, 19457, 0x404 /* NT_??? */, [{0x7fedb85df8, 8}]) = -1 EINVAL (Invalid argument)
```

It looks like kernel did't recognize `NT_ARM_SYSTEM_CALL` so not much we can do here

For reference
[PRoot commit](https://github.com/proot-me/PRoot/commit/b06b8d0ede8e147646345c281054936e24a86403)
[Linux kernel commit (which apparently wasn't applied on this device)](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=766a85d7bc5d7f1ddd6de28bdb844eae45ec63b0)

**Comment by fornwall** [comment]
Closing this since there is not much to do if the kernel lacks support (the Nexus 9 kernel seems to rather odd in how it's configured compared to other devices).

**Comment by 9990242854** [comment]
When i use that export PROOT_NO_SECCOMP=1 , it will work but when i update then its show BUS ERROR
Please fix that.

**Comment by xeffyr** [comment]
> then its show BUS ERROR
> Please fix that.

@9990242854 I suggest you to open issue at https://github.com/termux/proot/issues - more probability that it will be fixed.
