### ISSUE TITLE
libc++ upgrade breaks libLLVM (and in turn clang)

### ISSUE THREAD

**Issue by tomty89** [termux/termux-packages#2580]
```
$ clang
CANNOT LINK EXECUTABLE "clang": cannot locate symbol "__register_frame" referenced by "/data/data/com.termux/files/usr/lib/libLLVM-6.0.so"...
Aborted
$ LD_PRELOAD=/system/lib64/libc++.so clang
clang-6.0: error: no input files
$
```

Maybe it just needs a rebuild? Can't really test here.

**Comment by its-pointless** [comment]
Rebuild would do it...

**Comment by joakim-noah** [comment]
Just ran into this with CMake too after upgrading to libc++ 17 on Android/AArch64 8.0,
```
bash-4.4$ cmake --version
CANNOT LINK EXECUTABLE "cmake": cannot locate symbol "_Unwind_Resume" referenced by "/data/data/com.termux/files/usr/bin/cmake"...
Aborted
bash-4.4$ LD_PRELOAD=/system/lib64/libc++.so cmake --version
cmake version 3.11.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by tomty89** [comment]
I wonder if the upgrade was just an "accident", as @fornwall has been holding it back and mentioned a script of finding all the packages that need to be rebuild...

**Comment by fornwall** [comment]
@tomty89 Right, it was a mistake. I'm bumping revisions and rebuilding c++-using packages at the moment.

**Comment by fornwall** [comment]
Thanks - this has now been fixed by rebuilding to 6.0.0-3!

**Comment by fornwall** [comment]
(cmake has also been fixed, version 3.11.4-2 there).

**Comment by joakim-noah** [comment]
Clang and CMake now both work after updating, thanks.

**Comment by joakim-noah** [comment]
lldb still broken, guessing there are others.

**Comment by fornwall** [comment]
@joakim-noah Thanks, the updated lldb package at version 6.0.0-2 fixes this!

Most other C++ using packages should already be rebuilt, I'm checking them now.

**Comment by joakim-noah** [comment]
Updated lldb, works now. :smile:
