### ISSUE TITLE
Error while installing jupyter & When running ncmcpp

### ISSUE THREAD

**Issue by T4P4N** [termux/termux-packages#2585]
![screenshot_2018-06-27-00-26-00-357_com termux](https://user-images.githubusercontent.com/32695903/41933222-e228fc8a-79a0-11e8-900b-c7b44d68c9af.png)
![screenshot_2018-06-27-00-24-11-944_com termux](https://user-images.githubusercontent.com/32695903/41933289-0a887f84-79a1-11e8-8093-fc54ec85cbd3.png)
this is all started after running this while trying to install jupyter
```bash
LDFLAGS=" -lm -lcompiler_rt" pip install jupyter
```

**Comment by T4P4N** [comment]
#2260

**Comment by Grimler91** [comment]
Same issue as https://github.com/termux/termux-packages/issues/2580. Should be fixed, update all your packages with `apt update && apt upgrade` and try again.

**Comment by T4P4N** [comment]
thanks mate!
