### ISSUE TITLE
apt quit working after update

### ISSUE THREAD

**Issue by ejaquay** [termux/termux-packages#2586]
$ apt
CANNOT LINK EXECUTABLE "apt": cannot locate symbol "_Unwind_Resume" referenced by "/data/data/com.termux/files/usr/bin/apt"...
Aborted

$ termux-info
Aborted <-----------!
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.71-13527040 #1 SMP PREEMPT Wed May 16 17:00:07 KST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SAMSUNG-SM-G930A
Ph$

Now what?

**Comment by ejaquay** [comment]
Maybe the issue was that I screwed it up by doing apt package upgrades one at a time (using apt install).  Fixed it by renaming ../usr to ../usrold and restarting termux.   Then I ran 'apt update' and 'apt upgrade' and all seems okay now.   Renaming the usr directory is a nice trick for recovering from screwed up binaries without loosing data, so that at least is worth mentioning.

**Comment by Grimler91** [comment]
Closing this then, good that you figured it out.
