### ISSUE TITLE
Taskwarrior doesn't work anymore

### ISSUE THREAD

**Issue by regagain** [termux/termux-packages#2589]
_Taskwarrior_ was working fine until today. Now I am getting this:
```
$ task                                                                                                                                                                    
CANNOT LINK EXECUTABLE "task": cannot locate symbol "_Unwind_Resume" referenced by "/data/data/com.termux/files/usr/bin/task"...
[1]    6642 abort      task
```
Nexus 6P / Android 8.1.0 / CopperheadOS

Does anyone else have the same issue?

**Comment by fornwall** [comment]
Thanks a lot for reporting! This has been fixed in the latest `2.5.1-5` version of the taskwarrior package - update to it by running `pkg up`.
