### ISSUE TITLE
Weechat seems not working

### ISSUE THREAD

**Issue by huiyiqun** [termux/termux-packages#26]
![img_20151013_161416](https://cloud.githubusercontent.com/assets/3468160/10449323/7ccb09e0-71c5-11e5-91ff-4e7e7ec1844d.jpg)

**Comment by fornwall** [comment]
Hi, which device and Android version is this (the problem does not occur on the devices I test on)?

**Comment by huiyiqun** [comment]
Device: Nexus 7 2013 wifi(flo)
Android version: official Android 6.0 from Google

**Comment by fornwall** [comment]
Thanks - I'm able to reproduce the problem om Android 6, will look into it!

**Comment by fornwall** [comment]
@huiyiqun: This should now be fixed, do an `apt update && apt upgrade` to install the fixed packages.

Thanks for reporting the issue!
