### ISSUE TITLE
Package Request: `php-cli` and `php-readline`

### ISSUE THREAD

**Issue by ElvenSpellmaker** [termux/termux-packages#260]
Without the `cli` and `readline` package `php -a` switches to a crippled mode that basically isn't a REPL any more which makes it hard to run quick PHP tasks on the command line.

**Comment by fornwall** [comment]
Readline support has been enabled in the `5.6.21-1` version of the php package, to which you can update with:

    apt update && apt upgrade

**Comment by ElvenSpellmaker** [comment]
Thanks! Nice and quick! :+1:
