### ISSUE TITLE
Cant commit even after setting username and password

### ISSUE THREAD

**Issue by Sheriff0** [termux/termux-packages#2602]
I'm getting this error!!!!

git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'u0_a138@localhost.(none)')

Where is "u0_a138@localhost.(none)" coming from so i can change is manually?

**Comment by tomty89** [comment]
Do it?

**Comment by Sheriff0** [comment]
I have done it severally... same thing.. NB: My device is rooted

**Comment by Grimler91** [comment]
How did you set the username and email? Show what you ran and the output.

**Comment by Sheriff0** [comment]
git config --global user.mail "s.esseson@yahoo.com" 
git config --global user.name "sheriff0"
I even ran "git config" passing the "--system" option.

**Comment by Sheriff0** [comment]
. I have been doing it all wrong.  it's "user.email" and not "user.mail". thanks guys.. keep up the good work
