### ISSUE TITLE
Installing dialog creates a symlink for whiptail, but not equivalent

### ISSUE THREAD

**Issue by Ketrel** [termux/termux-packages#2623]
Not all functions of dialog are present in whiptail and syntax differs between the two slightly.

My script does the following:

1. checks for whiptail and uses if found
2. if whiptail not found, checks for dialog and uses if found

Problem is, by creating the whiptail -> dialog symlink, the script fails because it calls the dialog binary, but uses whiptail syntax.

Basically the dialog package should NOT create that symlink.

**Comment by Ketrel** [comment]
Quick question, I just noticed this is tagged as enhancement, but I'm trying to say it's a bug.

Whiptail and Dialog have slightly different syntax on certain items, so symlinking one to the other breaks scripts.

**Comment by its-pointless** [comment]
Adding whiptail would be the solution.

**Comment by OwElko** [comment]
whiptail is a must hope it will be added soon

**Comment by Ketrel** [comment]
https://i.imgur.com/zIMAA10.png

This is still the case.

The dialog package installs a symlink to whiptail which breaks scripts that depend on whiptail due to it not being a drop in replacement for dialog because the command line arguments are different.

**Comment by xtkoba** [comment]
The symlink seems to have been added to fix #291. @gwpl @vaites Any objections to removing the symlink?

**Comment by Ketrel** [comment]
If they don't answer, for what it's worth, I'm pretty sure the example scripts mentioned like raspi-config would fail horribly with the symlink. My script that caused me to open this bug uses whiptail the same ways they do.

**Comment by Ketrel** [comment]
Also, just wanted to add a specific example of the non-equivalence of the two.

Whiptail has a switch for a few options called --noitem

Dialog has the same function, but it's --no-items

**Comment by vaites** [comment]
Sorry for the delay @xtkoba. No objections here...
