### ISSUE TITLE
Question about NDK

### ISSUE THREAD

**Issue by Hax4us** [termux/termux-packages#2628]
It may be a dumb question lol 
I were googling today and I found an interesting project __CrystaX NDK__ well I didn't know that there is one more ndk exist and I read description it is more portable and have more functions which does not support Google's NDK 
So my question is that , can CrystaX replace Googles NDK for termux ?
What you think guys :)

For more information https://www.crystax.net/en

**Comment by fornwall** [comment]
The latest CrystaX NDK release is from 2016, and a lot has happened in the Android NDK since then. So it does not seem to be a viable alternative.
