### ISSUE TITLE
go install fails.  Cannot find aarch64-linux-android-gcc

### ISSUE THREAD

**Issue by ginabythebay** [termux/termux-packages#263]
I'm trying to build with go.  When I run `go install`, it failes because it cannot find `aarch64-linux-android-gcc`:

```
u0_a76@localhost` ~/g/s/g/g/ledger-tools> apt update
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
u0_a76@localhost ~/g/s/g/g/ledger-tools> apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
u0_a76@localhost ~/g/s/g/g/ledger-tools> go install
# github.com/ginabythebay/ledger-tools
/data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64/link: running aarch64-linux-android-gcc failed: exec: "aarch64-linux-android-gcc": executable file not found in $PATH
```

**Comment by ginabythebay** [comment]
looks like it works if I do `apt install gcc`, so it is probably just a dependency that needs updating

**Comment by fornwall** [comment]
Hm, should go depend on gcc then, or do many use go without using cgo?

**Comment by ginabythebay** [comment]
Well, it is my understanding that go moved to using a self hosted compiler in the last year or so and that they are keeping gcc around for a while.  So I was surprised to need gcc as part of the tool chain, but thought it was an intentional choice related to the constrained environment.

My experience using the package was that I couldn't find much of anything go-related that I could do until I installed gcc.

**Comment by fornwall** [comment]
The `golang` package now requires `clang` (which is now used as a C compiler in Termux), so closing this issue.
