### ISSUE TITLE
Package request: GNU Screen

### ISSUE THREAD

**Issue by jbrikman1** [termux/termux-packages#264]
GNU Screen is not just a terminal multiplexer but also a great environment to run multiple tabs in using a full keyboard setup on a tablet and avoiding touch screen use.  Moreover, screen can detach and allow for temporary daemons.

**Comment by Neo-Oli** [comment]
For the moment, check out tmux. It does almost exactly the same stuff as screen. 
There is also byobu and abducto+dvtm

**Comment by gardner** [comment]
tmux has screen-style bindings as well. I'm agnostic about the two but I am used to ctrl-a being the command key. They do the same thing, tmux seems newer and shinnier.

**Comment by timoc** [comment]
Should mention Mosh (mobile shell) here. its on Termux. A remote terminal application that allows roaming, supports intermittent connectivity, and provides intelligent local echo and line editing of user keystrokes.

it does not replace screen etc, but might fit your screen use case.

**Comment by gwpl** [comment]
+100  for screen. I have !any scripts that run stuff in named screen sessions so later they can be attached for view if needed. Also I would love to use my comfigs I use on desktop/laptop making customized workspaces

**Comment by gwpl** [comment]
I've tried to download and compile gnu screen without luck:

```
$ wget 'http://www.nic.funet.fi/pub/gnu/ftp.gnu.org/pub/gnu/screen/screen-4.4.0.tar.gz'
$ gunzip screen-4.4.0.tar.gz
$ tar xvf screen-4.4.0.tar
$ cd screen-4.4.0
$ termux-fix-shebang *.sh
$ termux-fix-shebang configure 
$ ./configure

(...)

configure: checking select...
configure: checking fifos...
- your fifos are not usable
configure: checking sockets...
- your sockets are not usable
configure: error: you have neither usable sockets nor usable pipes -> no screen
$
```

**Comment by mirrornoir** [comment]
I hope it's not bad form bumping this request but having screen would be extremely useful. I use screen extensively in the terminal and I'd love to have the same environment/work flow in termux. Thanks and props to an amazing app and package selection!

**Comment by addisaden** [comment]
I would also love to have screen available. It's an awesome tool in combination with socat!

btw i use also tmux, but screen is more usable for scripts

**Comment by fornwall** [comment]
There is now a screen package available in Termux - install with:

    packages install screen

It's only lightly tested so report issues encountered.

**Comment by gwpl** [comment]
Thank you!

**Comment by addisaden** [comment]
Thank you! This is awesome. Termux is a lovely project

Am 26.04.2017 1:00 vorm. schrieb "Grzegorz Wierzowiecki" <
notifications@github.com>:

**Comment by vanous** [comment]
Hi, thanks for gnu screen in termux!

After splitting screen (Ctrl-a S), the newly created window has no prompt, no response. One can move into it (Ctrl-a Tab) but it visually takes no keystrokes. Closing it (Ctrl-a X iirc) closes it correctly. The same issue on vertical/horizontal split.

Anyone experiences the same issue?

**Comment by vanous** [comment]
Oh, i didn't realize that new screen must be now created in the new window via Ctrl-a. Perhaps this helps to someone.
