### ISSUE TITLE
pinentry does not build if /usr/bin/fltk-config is available

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#2643]
fltk-config sets -fno-plt as one of CFLAGS and clang answers ` error: unknown argument: '-fno-plt'`

**Comment by xeffyr** [comment]
@twaik You got FLTK from my repository ([termux-extra-packages/fltk](https://github.com/xeffyr/termux-extra-packages/tree/master/packages-x11/fltk)) ?

**Comment by twaik** [comment]
No. Configure looka for /usr/bin/fltk-config and gets CFLAGS from that.

**Comment by fornwall** [comment]
Thanks for reporting! 48ae1723a54eb95d7b7ec4cec93771e8d4053c0f adds `--disable-pinentry-fltk`to configure when building, does that fix the problem for you?

**Comment by twaik** [comment]
Yes, thanks. It fixes the problem. Also I think that PKG_CONFIG_PATH=$TERMUX_PREFIX/lib/pkgconfig should be exported in termux_step_setup_variables().

**Comment by fornwall** [comment]
@twaik Thanks!

About setting `PKG_CONFIG_PATH`: We already set `PKG_CONFIG_LIBDIR`, and according to [this page](https://www.freedesktop.org/wiki/Software/pkg-config/CrossCompileProposal/):

> Note that when specifying PKG_CONFIG_LIBDIR, pkg-config will completely ignore the content in PKG_CONFIG_PATH, even if the documentation states different things.
