### ISSUE TITLE
How to host your own APT Repository?

### ISSUE THREAD

**Issue by moliata** [termux/termux-packages#2646]
Hello everyone,
I'm new here and I'm sorry if this question looks dumb. I have built all the packages using ./build-all.sh and I am interested into hosting these packages as a separate APT repository, but I have no idea how to do so. As far as I know, someone said it's possible to host them on GitHub Pages or any other static web hosting service, but what specifically I would need to upload and is there any kind of configuration for that. Or that would straight away process? Thanks.
Best regards,
moliata.

**Comment by xeffyr** [comment]
> I have built all the packages using ./build-all.sh
it's possible to host them on GitHub Pages

It is not recommended to have git repositories with size more than 1-2 GB.

> is there any kind of configuration for that.

You need a script, like this: https://github.com/termux/termux-apt-repo/blob/master/termux-apt-repo

**Comment by moliata** [comment]
Thanks @xeffyr, I will take a look right now.
