### ISSUE TITLE
Package request: nlopt

### ISSUE THREAD

**Issue by santiagoalonso** [termux/termux-packages#2647]
#143

**Comment by natalienaught** [comment]
Thank you for requesting this, I just wanted to +1 nlopt!

Now that R is so readily available in Termux ( many thanks to @its-pointless ), there are several useful packages that *I believe* are lacking only this dependency (e.g. lme4 & car).

**Comment by mlangiu** [comment]
I was also interested in this package and gave installation a shot, except for a linking issue everything seems to work, here's what I tried:

```shell
curl -LO https://its-pointless.github.io/setup-pointless-repo.sh
bash setup-pointless-repo.sh
pkg install numpy scipy
pkg install cmake
pkg install swig
pip install --upgrade pip
pip install wheel
pip install nlopt
```
For me this completed installation without errors, now running python
```python
Python 3.9.5 (default, May  5 2021, 12:32:19)
[Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nlopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/nlopt/__init__.py", line 20, in <module>
        from . import _nlopt
        ImportError: dlopen failed: cannot locate symbol "PyObject_GenericGetAttr" referenced by "/data/data/com.termux/files/usr/lib/python3.9/site-packages/nlopt/_nlopt.so"...
```

`PyObject_GenericGetAttr` is part of the [Python object protocol](https://docs.python.org/3/c-api/object.html), suggesting that for some reason the Python library isn't loaded properly.
We can fix this by preloading it explicitly through:
```shell
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libpython3.9.so.1.0
```
after which the import works fine:
```python
Python 3.9.5 (default, May  5 2021, 12:32:19)
[Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nlopt
>>>
```
To make this persistant, just export `LD_PRELOAD` in `~/.bashrc` or `~/.bash_profile`.
Hope this helps someone ;)
