### ISSUE TITLE
Apksigner Error (Aborted)

### ISSUE THREAD

**Issue by Hax4us** [termux/termux-packages#2652]
![42722215-e95136ea-8750-11e8-837b-fd8e78ff30a4 1](https://user-images.githubusercontent.com/30441647/42722577-ef53757e-876b-11e8-99c1-c88a4cffff6e.png)
![42721858-79305c5c-874a-11e8-810f-e910dc2e4964](https://user-images.githubusercontent.com/30441647/42722590-1787d9fe-876c-11e8-9a3e-9c4275441989.png)

**Comment by Hax4us** [comment]
strace log 
[log.txt](https://github.com/termux/termux-packages/files/2194784/log.txt)

**Comment by xeffyr** [comment]
I have similar error with apksigner (and dx or ecj). The solution is to provide `BOOTCLASSPATH` environment variable which is set by Android. PR for this: https://github.com/termux/termux-app/pull/811

**Comment by xeffyr** [comment]
Should be fixed in https://github.com/termux/termux-app/commit/5fa4f2647b72eb4ed1bb468171e5763d11abbcf3.
