### ISSUE TITLE
strings command doesnt list all strings

### ISSUE THREAD

**Issue by lukeeey** [termux/termux-packages#2654]
The `strings` command on termux and the same command on Ubuntu 16.04 are different. The termux version cant find the strings i was searching for on ubuntu.

**Comment by its-pointless** [comment]
there are 2 versions of strings one is installed by default as its part of busybox the other is in binutils. Which one are you using?

**Comment by lukeeey** [comment]
I have binutils Installed because I have the nm command

**Comment by its-pointless** [comment]
Could be because binutils is built without iconv support currently.

**Comment by lukeeey** [comment]
@fornwall I am using the libminecraftpe.so library found in Minecraft on Android. It's also the x86 version because the ARM version didn't seem to display much (i forgot why)

http://play.funo.host/libminecraftpe.so

**Comment by matthewsalmon** [comment]
I don't seem to have the strings command, but bintils is installed.

> strings
strings-GNU: command not found

**Comment by xeffyr** [comment]
`strings-GNU` - I'm not surprised that such command is not found.
Perhaps you should execute it in way like `$PREFIX/bin/strings` ? I don't know which things you messed up but it seems something replaces `strings` with `strings-GNU`, aliases maybe ?

**Comment by matthewsalmon** [comment]
@xeffyr Thanks, it must have been an alias from a past linux.

**Comment by xeffyr** [comment]
Closing since `busybox` is no longer provide `strings` applet - busybox being replaced by normal packages and in this case utility `strings` is located in binutils.
