### ISSUE TITLE
Package request: Deluge

### ISSUE THREAD

**Issue by newmania** [termux/termux-packages#2658]
https://deluge-torrent.org/

transmission-daemon and aria2c work great but I'm in need of a torrent client with socks5 proxy support. Deluge is a very popular option for headless installs.

Please and thank you!

**Comment by tomty89** [comment]
We probably won't package any python package as we expect users to get them with pip.

We can probably ship libtorrent-rasterbar though.

**Comment by newmania** [comment]
Thanks, that would be very helpful.

From the docs it looks like deluge isn't on pypi, though (almost) all of its dependencies are.

**Comment by newmania** [comment]
I've opened #3327 for libtorrent-rasterbar, since deluge itself is written in Python and can be installed by other means.
