### ISSUE TITLE
Bash info page missing

### ISSUE THREAD

**Issue by feklee** [termux/termux-packages#2662]
Browsing Bash documentation without table of contents and without index, aka the man page, is a nightmare on a small screen device. *Would it be possible to add the Bash info page?*

(A separate package would be fine, although I think info being the primary documentation for GNU tools, the man pages should be in a separate package.)

Size comparison, from another installation:

    $ ls -lh /usr/share/man/man1/bash.1.gz
    -rw-r--r-- 1 root root 78K Aug 30  2017 /usr/share/man/man1/bash.1.gz
    $ ls -lh /usr/share/info/bash.info.gz
    -rw-r--r-- 1 root root 121K Aug 30  2017 /usr/share/info/bash.info.gz

**Comment by tomty89** [comment]
> Would it be possible to add the Bash info page?

Of course it's possible. All you need to do is to add `TERMUX_PKG_KEEP_INFOPAGES=yes` to its `build.sh`

The real question should be what's the policy on info pages here. The current situation is somewhat irrational/silly:

https://github.com/termux/termux-packages/search?q=TERMUX_PKG_KEEP_INFOPAGES

It might be worth mentioning that the man pages in Termux are not compressed.

**Comment by feklee** [comment]
> All you need to do is to add TERMUX_PKG_KEEP_INFOPAGES=yes to its build.sh

Yes, I've seen that, but I prefer to have the info pages available in the original installation, either included or as a separate package (weird, but better than nothing).

*What can I do to make that happen?*

**Comment by Quasic** [comment]
I requested the gcal info page for someone. I could do the same here, but it might be better in a separate package, and I haven't done package splitting.

**Comment by feklee** [comment]
Maybe it's a good idea to update [build-package.sh][1] so that if there is an info page, it gets kept and the corresponding man page is deleted. This saves space and at the same time keeps documentation at the highest possible level.

[1]: https://github.com/termux/termux-packages/blob/aa3e6f78b8a48f9d0725ffa6f11f68d1139f8307/build-package.sh

**Comment by fornwall** [comment]
Perhaps we should just keep info pages by default and remove `TERMUX_PKG_KEEP_INFOPAGES`? I guess it wouldn't affect package sizes that much?

**Comment by kaeptmblaubaer1000** [comment]
I agree with that, there is no proper make documentation in the man pages and they only refer to `info` while info pages are missing. This happens in many other cases too.

**Comment by xeffyr** [comment]
Will be fixed after https://github.com/termux/termux-packages/pull/4005.

**Comment by fornwall** [comment]
Fixed in version `5.0.7-2` of the bash package.
