### ISSUE TITLE
Visible bell?

### ISSUE THREAD

**Issue by feklee** [termux/termux-packages#2664]
*Is it possible to get a visible bell?*

In Bash, I tried to no avail:

    set bell-style visible
    set prefer-visible-bell

It still vibrates (`bell-character=vibrate` in `termux.properties`). I'd like to have the terminal flash, e.g. invert, on bell.

**Comment by xeffyr** [comment]
Such feature was removed a long time ago: https://github.com/termux/termux-app/commit/7c0ae4cb54cb98441d797348538e19eb315cfb21

**Comment by feklee** [comment]
That’s sad. Simply inverting the display as supported by some terminal emulators would be sufficient.

**Comment by fornwall** [comment]
This issue was moved to termux/termux-app#820
