### ISSUE TITLE
Package request: cscope

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-packages#267]
$ pacman -Si cscope
Repository      : extra
Name            : cscope
Version         : 15.8.a-3
Description     : A developers tool for browsing program code
Architecture    : x86_64
URL             : http://cscope.sourceforge.net/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : ncurses  sh
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 142.20 KiB

**Comment by fornwall** [comment]
Thanks to @yumaokao there is now a cscope package available - install it with:

    packages install cscope
