### ISSUE TITLE
tsu exec command failed

### ISSUE THREAD

**Issue by Cvar1984** [termux/termux-packages#2675]
unknown option -- preserve-environment
Usage: su [options] [args...]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -cn, --context CONTEXT        switch to SELinux CONTEXT before invoking
  -d, -ad, --daemon, --auto-daemon
                                start the su daemon
  -i, --install                 check and repair su files
  -h, --help                    display this help message and exit
  -v, -V, --version             display version number and exit

Usage#2: su uid COMMAND...
u0_a89@localhost:~$ su 0 id
u0_a89@localhost:~$ uid=0(root) gid=0(root) context=u:r:init:s0
u0_a89@localhost:~$ su 0 apt
u0_a89@localhost:~$ [-] Execute command failed
u0_a89@localhost:~$ env
u0_a89@localhost:~$ LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
LANG=en_US.UTF-8
PREFIX=/data/data/com.termux/files/usr
PWD=/data/data/com.termux/files/home
HOME=/data/data/com.termux/files/home
TMPDIR=/data/data/com.termux/files/usr/tmp
TERM=xterm-256color
SHLVL=1
ANDROID_ROOT=/system
ANDROID_DATA=/data
EXTERNAL_STORAGE=/storage/emulated/0
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
_=/data/data/com.termux/files/usr/bin/env
u0_a89@localhost:~$

**Comment by Cvar1984** [comment]
What are you fucking about?

**Comment by Grimler91** [comment]
You've given the error message but not what you ran to get it.

I would guess that your particular su binary doesn't support "preserve-environment", if that is the case then there isn't much tsu can do about it. I would then recommend that you un-root and then re-root with another su variant.
