### ISSUE TITLE
Package request: shellcheck

### ISSUE THREAD

**Issue by notevenodd** [termux/termux-packages#2678]
https://github.com/koalaman/shellcheck
https://www.shellcheck.net/

shellcheck is a must-have application to remove or prevent bugs from shell scripts. It would be extremely useful to have this tool available in termux.

**Comment by sdrausty** [comment]
For the impatient, shellcheck is already available in Termux PRoot via https://sdrausty.github.io/TermuxArch/.

```
[11:04 home ]$ pacman -S shellcheck
resolving dependencies...
looking for conflicting packages...

Packages (23) ghc-libs-8.4.3-1  haskell-aeson-1.3.1.1-25
              haskell-attoparsec-0.13.2.2-25  haskell-base-compat-0.10.4-1
              haskell-dlist-0.8.0.4-5  haskell-hashable-1.2.7.0-3
              haskell-integer-logarithms-1.0.2.1-3  haskell-primitive-0.6.4.0-1
              haskell-quickcheck-2.11.3-4  haskell-random-1.1-12
              haskell-regex-base-0.93.2-33  haskell-regex-tdfa-1.2.3.1-1
              haskell-scientific-0.3.6.2-6  haskell-tagged-0.8.6-1
              haskell-tf-random-0.5-19  haskell-th-abstraction-0.2.8.0-1
              haskell-time-locale-compat-0.1.1.4-3
              haskell-unordered-containers-0.2.9.0-8
              haskell-uuid-types-1.0.3-15  haskell-vector-0.12.0.1-10
              llvm50-5.0.2-2  llvm50-libs-5.0.2-2  shellcheck-0.5.0-65

Total Download Size:    73.96 MiB
Total Installed Size:  538.60 MiB

:: Proceed with installation? [Y/n]
```

Since shellcheck is written in Haskell maybe this link will be useful https://github.com/termux/termux-packages/issues?q=is%3Aissue+haskell.

**Comment by xeffyr** [comment]
Termux does not still have haskell compiler available so package `shellcheck` can't be built.

I have opened PR (https://github.com/termux/termux-packages/pull/2794) for [shellharden](https://github.com/anordal/shellharden), which may be an alternative. It seems not same accurate in linting as shellcheck but better than nothing.

**Comment by xeffyr** [comment]
It requested at least 2 times. It even exist in disabled packages: https://github.com/termux/termux-packages/blob/master/disabled-packages/ghc

**Comment by sdrausty** [comment]
>  requested at least 2 times. It even exist in disabled packages: 

Any idea what is disabling it?  It is just a compiler.  My guess is Haskell might even work in DOS 💾

**Comment by TJProgrammer** [comment]
> Termux does not still have haskell compiler available so package `shellcheck` can't be built.
> 
> I have opened PR (#2794) for [shellharden](https://github.com/anordal/shellharden), which may be an alternative. It seems not same accurate in linting as shellcheck but better than nothing.

Hello! So if the way is to use shellharden, it was good to inform the user about that like:

```
pkg install Shellcheck
Error: use instead shellharden
```
What do you think?

**Comment by xeffyr** [comment]
shellharden != shellcheck. They can't replace each other.

**Comment by TJProgrammer** [comment]
Ok. Thanks for the explanation @xeffyr!

**Comment by brbsix** [comment]
I've wanted shellcheck on Termux so badly for a while now. I resorted to some less-than ideal solutions.

    # Here's a Bash function that pipes a local script into the shellcheck installed on my server
    shellcheck(){
        ssh MYSERVER /usr/bin/shellcheck -C "${@:1:$(($#-1))}" -- - < "${@: -1}"
    }

    # Here's one that uploads a local script onto the live demo at shellcheck.net
    shellcheck.net ()
    {
        curl --data-urlencode "script@$1" -sS 'https://www.shellcheck.net/shellcheck.php' | jq .
    }

Well, enough is enough, so I wrote a script to install the latest x86_64 binary locally and run it with QEMU. It looks like the `pandoc` package does something similar, so it should be straightforward to make a proper package.

Note that I've installed it in `~/.local/bin` but you will want to change that if it's not on your PATH.

https://gist.github.com/brbsix/999c3d4a4a881400f6c8ee5417a66a15

**Comment by notevenodd** [comment]
Hello @brbsix, why not just simply use the statically-linked ARM binary made available from shellcheck's github release page?
https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.armv6hf.tar.xz

**Comment by brbsix** [comment]
@notevenodd Does that run in Termux for you? I'm on an aarch64 processor. None of shellcheck's published binary releases run natively on my device. Neither aarch64 nor armv6hf. I already had qemu-user-x86_64 installed as a dependency of pandoc so I decided to use it with shellcheck's x86_64 release.

**Comment by notevenodd** [comment]
@brbsix yes, the armv6hf binary works for me... anyway, it's great you've found and shared a workaround :+1:

**Comment by Aptrug** [comment]
Same as @brbsix but my device is rooted and I found out that ShellCheck can be run like this: `su -c '/path/to/binary/shellheck'`. Tested using the *aarch64* binary: https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.linux.aarch64.tar.xz

**Comment by GrpeApple** [comment]
Hmm, perhaps the system call is different from Termux?

**Comment by SDRausty** [comment]
> shellcheck is a must-have application to remove or prevent bugs from shell scripts. It would be extremely useful to have this tool available in termux.

Termux Proot can be used to have 'shellcheck' available on smartphone today. It works as expected on both arm architectures. 

I have only tried these with QEMU; and it appears to work as expected in all available architectures as well.

**Comment by tathastu871** [comment]
```
cd $HOME
wget https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.aarch64.tar.xz
tar xvf shellcheck-stable.linux.aarch64.tar.xz
rm shellcheck-stable.linux.aarch64.tar.xz
cd shellcheck-stable
cp shellcheck $PREFIX/bin
echo 'alias shellcheck="proot -0 shellcheck"' >> $PREFIX/etc/bash.bashrc
```

**Comment by tathastu871** [comment]
> ```
> cd $HOME
> wget https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.aarch64.tar.xz
> tar xvf shellcheck-stable.linux.aarch64.tar.xz
> rm shellcheck-stable.linux.aarch64.tar.xz
> cd shellcheck-stable
> cp shellcheck $PREFIX/bin
> echo 'alias shellcheck="proot -0 shellcheck"' >> $PREFIX/etc/bash.bashrc
> rm -rf $HOME/shellcheck-stable
> ```

Above command worked for me. However i was unable to integrate shelcheck with vim.
I tried syntastic, ale. But none of them work.
For syntastic, default linters are 1)sh, 2) shellcheck 
i tried setting,
``` let g:syntastic_sh_checkers = ["shellcheck"] ```
in ~/.vimrc.

But still syntastic uses sh as linter instead of shellcheck.

Can anyone help with it?

**Comment by SDRausty** [comment]
Porting of newly published code package request.

> would be extremely useful to have this tool available in termux.

Shellcheck source code from [AUR](https://aur.archlinux.org/packages/shellcheck-bin/) builds like a magic charm in [TermuxArch](https://github.com/TermuxArch/TermuxArch):

![Screenshot_20220126](https://user-images.githubusercontent.com/27742457/151151101-1dbc1a36-d39f-4fca-816b-067b3241eba7.gif)

It works like a magic charm too!  Thank you 🎼  
```
user05:58~$ d .cache/yay/shellcheck-bin/
6.0M    .cache/yay/shellcheck-bin/
```

It appears upstream might be listening to our some of our requests here in Termux.

**Comment by leapofazzam123** [comment]
Thanks to @xtkoba, Haskell is now working on Termux again. So, we should be able to build shellcheck.
