### ISSUE TITLE
svn  sqlite version error

### ISSUE THREAD

**Issue by QGB** [termux/termux-packages#2683]
svn: E200029: Couldn't perform atomic initialization
svn: E200030: SQLite compiled for 3.23.1, but running with 3.22.0
$
$apt  install libsqlite
Reading package lists... Done
Building dependency tree
Reading state information... Done
libsqlite is already the newest version (3.24.0-1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
$

**Comment by QGB** [comment]
u0_a133@HS8917QC:/ $ su
root@HS8917QC:/ # find / -iname libsqli

^C
130|root@HS8917QC:/ # find / -iname libsqli*

/system/lib/libsqlite.so
/system/lib/libsqlite_jni.so
/system/lib64/libsqlite.so
/system/lib64/libsqlite_jni.so

**Comment by QGB** [comment]
when i try to build svn

/bin/sh "/data/data/com.termux/files/home/subversion-1.10.2/libtool" --tag=CC --silent --mode=compile gcc -std=c90  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -Werror=unknown-warning-option -g -O2     -I./subversion/include -I./subversion -I/data/data/com.termux/files/usr/include/apr-1   -I/data/data/com.termux/files/usr/include/apr-1   -o subversion/libsvn_subr/cache-inprocess.lo -c subversion/libsvn_subr/cache-inprocess.c
/bin/sh "/data/data/com.termux/files/home/subversion-1.10.2/libtool" --tag=CC --silent --mode=compile gcc -std=c90  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -Werror=unknown-warning-option -g -O2     -I./subversion/include -I./subversion -I/data/data/com.termux/files/usr/include/apr-1   -I/data/data/com.termux/files/usr/include/apr-1   -o subversion/libsvn_subr/cache-membuffer.lo -c subversion/libsvn_subr/cache-membuffer.c
/bin/sh "/data/data/com.termux/files/home/subversion-1.10.2/libtool" --tag=CC --silent --mode=compile gcc -std=c90  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -Werror=unknown-warning-option -g -O2     -I./subversion/include -I./subversion -I/data/data/com.termux/files/usr/include/apr-1   -I/data/data/com.termux/files/usr/include/apr-1   -o subversion/libsvn_subr/cache-memcache.lo -c subversion/libsvn_subr/cache-memcache.c
In file included from subversion/libsvn_subr/cache-memcache.c:38:
In file included from /data/data/com.termux/files/usr/include/apr-1/apr_memcache.h:32:
In file included from /data/data/com.termux/files/usr/include/apr-1/apr_network_io.h:32:
In file included from /data/data/com.termux/files/usr/include/netinet/in.h:37:
In file included from /data/data/com.termux/files/usr/include/linux/in.h:217:
In file included from /data/data/com.termux/files/usr/include/asm/byteorder.h:24:
In file included from /data/data/com.termux/files/usr/include/linux/byteorder/little_endian.h:28:
/data/data/com.termux/files/usr/include/linux/swab.h:39:8: error:
      unknown type name 'inline'
static inline __attribute__((__const__)) __u32 __fswahw32(__u32 val) {
       ^
/data/data/com.termux/files/usr/include/linux/swab.h:39:15: error:
      expected identifier or '('
static inline __attribute__((__const__)) __u32 __fswahw32(__u32 val) {
              ^
/data/data/com.termux/files/usr/include/linux/swab.h:46:8: error:
      unknown type name 'inline'
static inline __attribute__((__const__)) __u32 __fswahb32(__u32 val) {
       ^
/data/data/com.termux/files/usr/include/linux/swab.h:46:15: error:
      expected identifier or '('                                        static inline __attribute__((__const__)) __u32 __fswahb32(__u32 val) {                ^
/data/data/com.termux/files/usr/include/linux/swab.h:79:8: error:
      unknown type name 'inline'
static inline __u32 __swahw32p(const __u32 * p) {
       ^                                                                /data/data/com.termux/files/usr/include/linux/swab.h:79:20: error:
      expected ';' after top level declarator
static inline __u32 __swahw32p(const __u32 * p) {
                   ^
6 errors generated.
make: *** [Makefile:789: subversion/libsvn_subr/cache-memcache.lo] Error 1

**Comment by QGB** [comment]
sed -i 's/-std=c90 $CFLAGS/$CFLAGS/' configure
(cd subversion/bindings/swig/perl/libsvn_swig_perl/; ln -s ../../proxy/swig_perl_external_runtime.swg)
CPPFLAGS=" -I$PREFIX/lib/perl5/5.26.2/aarch64-android/CORE" ./configure --prefix=$PREFIX/local --disable-static

solved

**Comment by fornwall** [comment]
This should be fixed in the latest 1.10.2 version of the subversion package - run `pkg up` to update!
