### ISSUE TITLE
Package request: pari-gp (calculator and computer algebra system)

### ISSUE THREAD

**Issue by rybasd** [termux/termux-packages#2694]
Despite there is a port of PARI/GP calculator to android named PariDroid, it has some flows.

Is it possible to add pari-gp package to termux? 

Source code: https://pari.math.u-bordeaux.fr/download.html
Version control: https://pari.math.u-bordeaux.fr/cgi-bin/gitweb.cgi?p=pari.git;a=summary

**Comment by Grimler91** [comment]
Seems straightforward to compile on device, no patching needed, so before it has been added to the repo you can always compile it yourself on device and test it.

This should work to compile and install it:
```
# from suitable directory
wget https://pari.math.u-bordeaux.fr/pub/pari/unix/pari-2.11.0.tar.gz
tar -xf pari-2.11.0.tar.gz
cd pari-2.11.0
./Configure --prefix=$PREFIX
make all
make install
```

**Comment by rybasd** [comment]
**Grimler91**, it installs but with no readline support:

```
###
### Readline library does not seem to work. Maybe install libncurses?
###
### Building without GNU readline support
```
Which is very inconvinient :(

**Comment by xeffyr** [comment]
`pkg install readline-dev ncurses-dev`

**Comment by rybasd** [comment]
**xeffyr** and what next?

**Comment by Grimler91** [comment]
@rybasd re-run `./Configure --prefix=$PREFIX`, `make all` and `make install` after installing the dependencies.

**Comment by rybasd** [comment]
@Grimler91 
After

```
./Configure --prefix=$PREFIX
make all
make install
```
readline still does not work. 
after pressing up arrow key it prints ^[[A, down prints ^[[B right prints ^[[C left prints ^[[D

**Comment by Grimler91** [comment]
What did the ./Configure print about readline then?

**Comment by rybasd** [comment]
@Grimler91 
It says
`Using GNU readline, version 7.0`

**Comment by rybasd** [comment]
@Grimler91 after `make clean` and re-run configure+make readline works!
Thank you!

**Comment by rybasd** [comment]
Now another annoyance: Ctrl-V does not paste (yet long tap invokes termux's "copy paste more..." menu and paste works).

**Comment by Grimler91** [comment]
Does ctrl + v usually work in pari-gp (does it have its own clipboard?)? It isn't really standard gnu/linux syntax. For most programs in termux long-pressing is the only way to copy paste.

**Comment by rybasd** [comment]
@Grimler91 I don't know if ctrl+v does work in pari-gp in linuxes as the only linux cli I have is termux :) Can check in macos, though I'm o'k with long tap.

**Comment by X-m7** [comment]
It doesn't have a clipboard of its own, and ctrl-v doesn't do anything, just tried it with the version Arch Linux has.

**Comment by rybasd** [comment]
Is there any chance the pari-gp package to be added?
