### ISSUE TITLE
package upgrade command not working properly and gnupg-curl package is missing from package list

### ISSUE THREAD

**Issue by remo7777** [termux/termux-packages#2696]
## * What happened package upgrade command is not working properly on my device
<img src="https://user-images.githubusercontent.com/28594846/43488916-d8bab27a-9538-11e8-8c3c-76eb19b48659.png" width="300" hight="220">

## * And gnupg-curl is not present in package list

<img src="https://user-images.githubusercontent.com/28594846/43489392-82f47b9e-953a-11e8-89a6-2680b773db8c.png" width="300" hight="220">

<img src="https://user-images.githubusercontent.com/28594846/43489891-2022f930-953c-11e8-8e7c-02cf3fe215c2.png" width="300" hight="220">

**Comment by Grimler91** [comment]
We removed gnupg and renamed gnupg2 to gnupg. To fix this you need to run `apt install gnupg`, after that all programs can be upgraded normally.

**Comment by remo7777** [comment]
ok but what about package upgrade ??

**Comment by xeffyr** [comment]
@remo7777 Did you tried `apt dist-upgrade` ?

**Comment by remo7777** [comment]
thanks bro..
