### ISSUE TITLE
Package request:NFC, Bluetooth, Proximity Sensors

### ISSUE THREAD

**Issue by Kaosxlinus** [termux/termux-packages#2697]
I'm not sure if this is the right way to go about this, but are there any packages/repositories that would allow me to interact with the NFC, Bluetooth, and proximity sensor interfaces? I'd assume these are going to be different tools, but any help would be greatly appreciated here. I have a Galaxy S8, not rooted.

**Comment by Grimler91** [comment]
The proximity sensor can be accessed through the app&package termux-api, see https://github.com/termux/termux-api/pull/147.

NFC and bluetooth aren't implemented yet, see https://github.com/termux/termux-api/issues/86 and https://github.com/termux/termux-api/issues/88. 

Closing in favour of the other issues.
