### ISSUE TITLE
Vim: no visual mode and cannot use 'word wrap' mode

### ISSUE THREAD

**Issue by wean-irdeh** [termux/termux-packages#2709]
Using Android 8.0 in Xiaomi Mi A1 Android One device, I can't use visual mode as it says 'not implemented', setting up word wrap mode doesn't change anything too, please help!

**Comment by fornwall** [comment]
You are probably running `vi` and is getting a lightweight vi implementation from busybox. To get the normal fully-featured vim run:

    pkg in vim
