### ISSUE TITLE
ssh-agent throws "Bad system call" on Android Pie

### ISSUE THREAD

**Issue by infernix** [termux/termux-packages#2714]
I've upgraded my Pixel 2XL to Pie, upgraded all termux packages but with openssh/stable,now 7.7p1-3 strarting ssh-agent just returns "Bad system call".

I'd provide more detail, but:

``` 
$ strace -f ssh-agent
strace: Unexpected wait status 0x1f
```

gdb:
```
(gdb) run
Starting program: /data/data/com.termux/files/usr/bin/ssh-agent 
warning: .dynamic section for "/data/data/com.termux/files/usr/bin/ssh-agent" is not at the expected address (wrong library or version mismatch?)

Program received signal SIGSYS, Bad system call.
0x0000007fb7971420 in setresgid () from /system/lib64/libc.so
(gdb) bt
#0  0x0000007fb7971420 in setresgid () from /system/lib64/libc.so
#1  0x000000555555b80c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by tmzullinger** [comment]
It looks like `setresgid` is one of the syscalls which are now filtered by Android Pie.  Perhaps the attached logcat output is useful.

[ssh-agent-logcat.log](https://github.com/termux/termux-packages/files/2269001/ssh-agent-logcat.log)

Looking briefly at the openssh source, it looks like it checks for setregid at build time, so maybe a rebuild with Android Pie will fix this issue.  (The openssh configure script defines `BROKEN_SETRESGID` if setresgid doesn't work properly.)

**Comment by tmzullinger** [comment]
I'm not sure whether a rebuild will pick up the changes to `setresgid` automatically.  It may be simpler to define it in the build script, e.g.:

```diff
diff --git i/packages/openssh/build.sh w/packages/openssh/build.sh
index 9029a9da..b836cbb1 100755
--- i/packages/openssh/build.sh
+++ w/packages/openssh/build.sh
@@ -47,7 +47,7 @@ termux_step_pre_configure() {
     ## prefixed path to program 'passwd'
     export PATH_PASSWD_PROG="${TERMUX_PREFIX}/bin/passwd"
 
-	CPPFLAGS+=" -DHAVE_ATTRIBUTE__SENTINEL__=1"
+	CPPFLAGS+=" -DHAVE_ATTRIBUTE__SENTINEL__=1 -DBROKEN_SETRESGID"
 	LD=$CC # Needed to link the binaries
 	LDFLAGS+=" -llog" # liblog for android logging in syslog hack
 }
```

I haven't built termux packages previously, but I'll try to do this in the next few days if no one beats me to it.

**Comment by infernix** [comment]
Well, I built it with -DBROKEN_SETRESGID but now gdb throws:

```
Program received signal SIGSYS, Bad system call.
0x0000007fb78b3360 in setgid () from /system/lib64/libc.so
```

logcat:
```
08-08 13:12:10.412 25292 25292 F DEBUG   : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
08-08 13:12:10.413 25292 25292 F DEBUG   : Cause: seccomp prevented call to disallowed arm64 system call 144
```

Not sure how to deal with this one.

**Comment by infernix** [comment]
I've built it and seems to work for me, can download at https://dx.infernix.net/openssh_7.7p1-3_aarch64.deb

**Comment by Grimler91** [comment]
Nice work!

@infernix How much/how have you tested it? Grepping for setgid shows that it is used in a couple of more places as well (openbsd-compat/bsd-setres_id.c, scp.c, session.c, uidswap.c). 

Could you try sending a file back and forth with scp for example?

**Comment by infernix** [comment]
I saw those, but I don't think they get called in normal operation; at least not in any test cases I ran. sshd works, scp works etc.

**Comment by tmzullinger** [comment]
Nicely done @infernix!  Thanks for saving me the trouble of building with only `BROKEN_SETRESGID` and running into `setgid` and `setegid` failures.

I tested this a bit as well and haven't found any problems so far.  Ideally something along these lines will make it upstream to openssh-portable as well.

**Comment by fornwall** [comment]
Nice! The https://github.com/termux/termux-packages/pull/2716 PR has now been merged and the updated openssh package is available for installation.
