### ISSUE TITLE
PREFIX env var autocompletes in bash, not in zsh

### ISSUE THREAD

**Issue by aiisuika** [termux/termux-packages#2715]
bash:
```bash
$ $PR + TAB -> $PREFIX

$ $PRE + TAB -> $PREFIX

$ $PREF + TAB -> $PREFIX

$ $PREFI + TAB -> $PREFIX

$ $PREFIX + TAB -> $PREFIX/
```
zsh:
```bash
$ $PR + TAB ->
PROMPT             PROMPT3            precmd_functions   prompt
PROMPT2            PROMPT4            preexec_functions

$ $PRE + TAB -> $pre

$ $PREF + TAB -> $TMPPREFIX

$ $PREFI + TAB -> $TMPPREFIX

$ $PREFIX + TAB -> $ZSH_THEME_GIT_PROMPT_PREFIX
```
Even after `export PREFIX=$PREFIX` or `export PREFIX="$PREFIX"` zsh doesn't detect the existence of `$PREFIX`
But it exists when used?!?
```bash
$ echo $PREFIX
/data/data/com.termux/files/usr
```

**Comment by Neo-Oli** [comment]
Looking through the sources of zsh it seems zsh does this on purpose (for reasons unrelated to termux). It seems like this can be disabled either by setting the prefix-hidden or keep-prefix zstyle setting, but I haven't found out how.

**Comment by aiisuika** [comment]
Seems so, perhaps PREFIX in zsh's sources could be renamed...
I'll try rebuilding it

**Comment by aiisuika** [comment]
Can't work out a fix atm
