### ISSUE TITLE
Fish can't find ssh; breaks tab completion for some commands.

### ISSUE THREAD

**Issue by supbish** [termux/termux-packages#2721]
To reproduce, run `fish` and then type `telnet <tab>`.

Fish looks for ssh in `/etc/ssh`, but should look in `~/../user/etc/ssh`.

```
telnet cd: The directory '/etc/ssh' does not exist
Standard input (line 21):
            builtin cd $relative_path
            ^
in function '_recursive'
        called on standard input

in function '_ssh_include'
        called on line 2 of file /data/data/com.termux/files/usr/share/fish/functions/__fish_print_hostnames.fish
        with parameter list '/etc/ssh/ssh_config'

in command substitution
        called on line 0 of file /data/data/com.termux/files/usr/share/fish/functions/__fish_print_hostnames.fish

in function '__fish_print_hostnames'
        called on standard input

in command substitution
        called on standard input
```

**Comment by supbish** [comment]
Cross-posted here: https://github.com/fish-shell/fish-shell/issues/5138

**Comment by supbish** [comment]
Alright, looks like we can just replace the path in a few places in `__fish.print.hostname.fish`.

Going to leave this open because parameterizing it could still be useful; feel free to close if not desired.

**Comment by supbish** [comment]
This appears to be fixed in fish for some time, with explicit support for Termux paths. Updating to a more recent version should fix it.

**Comment by xeffyr** [comment]
Fixed in recent fish versions.
