### ISSUE TITLE
Xapian unable to generate UUID

### ISSUE THREAD

**Issue by wtomed** [termux/termux-packages#2730]
When building a new database with the command 'notmuch new' xapian fails with the error:

A Xapian exception occurred opening database: Opening UUID generator failed

**Comment by its-pointless** [comment]
Tries to acsess /proc/sys/kernel/random/uuid and fails.

**Comment by fornwall** [comment]
Thanks for reporting! And nice description of the problem @its-pointless.

This should now be fixed in version 1.4.7-1 of libxapian (by using libuuid instead of trying to read `/proc/sys/kernel/random/uuid`, which is not allowed on newer android versions) - run `pkg up` to update.
