### ISSUE TITLE
[gdb 8.1.1] gdb fails to attach to non-termux processes with assertion error

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#2733]
gdb fails to attach to non-termux processes with assertion error. This happens right after typing `attach <pid>`:

```
linux-nat.c:1093: internal error: int linux_nat_post_attach_wait(ptid_t, *int *): Assertion `pid == new pid' failed.
```

This is of a simple test app I built with python-for-android, it's not a system app or anything and runs a single process. (I ran gdb inside `tsu -e` because otherwise, I don't appear to have the permissions to attach to a non-termux process at all)

gdb version is 8.1.1 installed through termux's `apt`

**Comment by JonasT** [comment]
I can try more stuff, if you can think of something that might help provide some information for this. Just let me know. Maybe it's some weirdness with the specific `serranoltexx` image of LineageOS? This is the system I'm running: https://download.lineageos.org/serranoltexx (lineageos 14.1)

**Comment by Grimler91** [comment]
The same error message occurs in some other, older, issues: 
http://gdb-patches.sourceware.narkive.com/sgK4mb8b/fix-for-internal-error-linux-nat-post-attach-wait-assertion-pid-new-pid-wifstopped-status-failed
https://bugzilla.redhat.com/show_bug.cgi?id=1162264

I don't get the error on aarch64 (android 8). might be something only happening on arm.

**Comment by JonasT** [comment]
Hm. I wonder if gdb packaged for `aarch64` is a newer version by any chance?

**Comment by Grimler91** [comment]
Both are 8.1.1: http://termux.net/dists/stable/main/binary-aarch64/, http://termux.net/dists/stable/main/binary-arm/. 

The issues I linked are 9 and 4 years old, those issues are closed since long so it seems likely that there is some other issue here (but the error message happen to be the same)

**Comment by Grimler91** [comment]
I tried it on arm, lineageos 14.1 and couldn't reproduce the error. Does it happen for all processes you try to attach to or just this python program?

**Comment by twaik** [comment]
Closing this because topic-starter's account was deleted.
