### ISSUE TITLE
matplotlib.pyplot not working on jupyter for android

### ISSUE THREAD

**Issue by ObasiGodstime** [termux/termux-packages#2745]
import matplotlib.pyplot as plt
---------------------------------------------------
ModuleNotFoundErrorTraceback (most recent call last)
<ipython-input-7-3765d9b4ab39> in <module>()
----> 2 import matplotlib.py

ModuleNotFoundError: No module named 'matplotlib.py'

**Comment by Grimler91** [comment]
Doesn't seem to be any issue related to termux here. 

I guess you haven't installed matplotlib, or that you're using the wrong syntax (import matplotlib instead of matplotlib.py).
