### ISSUE TITLE
Failed to build from tip

### ISSUE THREAD

**Issue by ginabythebay** [termux/termux-packages#275]
I thought I would try my hand at contributing and am having trouble building by following the instructions.  My local repo is at 74e2f470045fd9658b68086bf681645cb7d84bd3.

I am doing this on mac, using docker.

I did:

    docker build --rm=true -t termux .
    docker run --rm=true -ti termux /bin/bash
    cd root/termux-packages/
    time ./build-all.sh

It proceeded until I got an error building coreutils.  Looking at coreutils.err, I see:

```
+ termux_step_host_build
+ /root/termux/coreutils/src/configure ac_cv_func_mkfifo=yes gl_cv_host_operating_system=Android --without-gmp --enable-single-binary=symlinks ac_cv_func_endpwent=no --enable-no-install-program=pinky,realpath,df,chroot,env
configure: error: in `/root/termux/coreutils/host-build':
configure: error: you should not run configure as root (set FORCE_UNSAFE_CONFIGURE=1 in environment to bypass this check)
```

Is there some other step I should be doing before running `build-all.sh`?

**Comment by its-pointless** [comment]
If you started docker as root and you are root in the container or something like that. I am making the docker image right now so i will check back here shortly. but don't run docker as user root add user to docker group.

**Comment by fornwall** [comment]
Is the problem that running the Dockerfile per instructions sets you up as root, but at least one configure script refuses to run as root?

Perhaps the easiest solution is to have the Dockerfile setup `FORCE_UNSAFE_CONFIGURE=1`?

**Comment by its-pointless** [comment]
Yeah it does set you up as root.

**Comment by ginabythebay** [comment]
Yes it set me up as root.  Getting it to not do that in my mac environment is not obvious to me.  if using FORCE_UNSAFE_CONFIGURE will do the job, then I think that may be the way to go here.

**Comment by fornwall** [comment]
This and some other docker issues are now fixed - thanks!
