### ISSUE TITLE
vim: E484: Can't open file /data/data/com.termux/files/usr/share/vim/syntax/syntax.vim

### ISSUE THREAD

**Issue by msdos** [termux/termux-packages#2754]
When trying to run vim, I get:

```
bash-4.4$ vim
Error detected while processing /data/data/com.termux/files/usr/share/vim/vimrc:
line   19:
E484: Can't open file /data/data/com.termux/files/usr/share/vim/syntax/syntax.vim
Press ENTER or type command to continue
```

`/data/data/com.termux/files/usr/share/vim/syntax/syntax.vim` doesn't exist. The correct path is `/data/data/com.termux/files/usr/share/vim/vim80/syntax/syntax.vim`. An workaround is to create a symbolic link:

```
mkdir -p /data/data/com.termux/files/usr/share/vim/syntax/
ln -s /data/data/com.termux/files/usr/share/vim/vim80/syntax/syntax.vim /data/data/com.termux/files/usr/share/vim/syntax/syntax.vim
```
More information:

```
bash-4.4$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug  8 2018 09:44:06)
Included patches: 1-250
Compiled by builder@f2e7b9a360c4
```

**Comment by fornwall** [comment]
I'm unable to reproduce.

Can you run `pkg up` to update to the latest package versions and see if that fixes the problem? Could it be that your `vim-runtime` is out of date?

**Comment by msdos** [comment]
You're right. Latest `vim-runtime` is pointing to `/data/data/com.termux/files/usr/share/vim/vim81/syntax/syntax.vim` and the error is gone. 

Sorry about that. I'm closing this issue and keeping in mind running `pkg up` before opening new issues. AFAIK, github has a feature of adding issue templates, maybe a reminder of running `pkg up` before opening an issue would be a nice one.
