### ISSUE TITLE
Read-only file system @ dir_s_mkdir - /tmp (Errno::EROFS)

### ISSUE THREAD

**Issue by 821938089** [termux/termux-packages#2760]
I follow the tutorial to install brew:https://github.com/Linuxbrew/brew/wiki/Android

An error occurred while running brew

$ brew
Traceback (most recent call last):
13: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/brew.rb:15:in <main>' 12: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/brew.rb:15:inrequire_relative'
11: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/global.rb:15:in <top (required)>' 10: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:inrequire'
9: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in require' 8: from /data/data/com.termux/files/home/prefix/brew/Library/Homebrew/config.rb:47:in<top (required)>'
7: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/pathname.rb:578:in mkpath' 6: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:193:inmkdir_p'
5: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:193:in each' 4: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:208:inblock in mkdir_p'
3: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:208:in reverse_each' 2: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:210:inblock (2 levels) in mkdir_p'
1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:in fu_mkdir' /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:inmkdir': Read-only file system @ dir_s_mkdir - /tmp (Errno::EROFS)

**Comment by Grimler91** [comment]
Closing as brew isn't a command/package provided by termux. 

@821938089 From the error message it looks like you might need to install gdbm{,-dev}.

**Comment by txdgidraph** [comment]
> > 1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:in fu_mkdir' /data/data/com.termux/files/usr/lib/ruby/2.5.0/fileutils.rb:232:inmkdir': Read-only file system @ dir_s_mkdir - /tmp (Errno::EROFS)
> 
> @821938089
> 
>     1. Android don't have directory **/tmp**
> 
>     2. The rootfs (i.e. `/`) is read-only + owned by root, so you can't just `mkdir /tmp`.
> 
> 
> As workaround, you can install proot (`pkg install proot`) and then try to run `brew` under `termux-chroot`:
> 
> ```
> termux-chroot
> brew
> ```
Worked for me
