### ISSUE TITLE
Metasploit is not anymore going to be installed on Termux

### ISSUE THREAD

**Issue by nasirxo** [termux/termux-packages#2773]
Hey u tried to installl meatsploit on termux but it have Some error with nokogiri seems likes not going to be installed plz fix this issue

**Comment by Hax4us** [comment]
What's your issue / error ? Any screenshot ?

**Comment by Hax4us** [comment]
See CEO 😂
![intex aqua trend_2018-08-25-11-58-50](https://user-images.githubusercontent.com/30441647/44615711-7ea5fe00-a85e-11e8-9a0b-2fe58f9e5754.png)

**Comment by Grimler91** [comment]
Metasploit isn't a termux-packages package so closing this. It would be more appropriate to open an issue where you got the install script, or to ask in any of the other [community channels](https://wiki.termux.com/wiki/Community).

**Comment by nasirxo** [comment]
Nokogiri version required for metasploit is not installing try to re install metasploit on termux

**Comment by Ivartb99** [comment]
Why it dose not work now
