### ISSUE TITLE
How to Downgrade PHP to version 7.1.8  ?

### ISSUE THREAD

**Issue by irfaanprogrammer** [termux/termux-packages#2781]
my script running normal when using this php version, if i using the new version my script not running and error, please tell me how to downgrade version on php to 7.1.8

**Comment by xeffyr** [comment]
> please tell me how to downgrade version on php to 7.1.8

Since Termux has `rolling release`, older versions are not provided.

**Comment by fornwall** [comment]
@irfaanprogrammer Is your script incompatible with php 7.2 in general, or could it be a problem with the packaging of php in Termux that needs to be improved? Could you share the relevant part of your script?
