### ISSUE TITLE
redis-cli cannot connect to server

### ISSUE THREAD

**Issue by bestvow** [termux/termux-packages#2783]
redis-cli cannot connect to server.

**Comment by fornwall** [comment]
A preliminary check: Have you run `pkg up` to ensure latest package versions?

Could you give more information about the error (what output do you get)? Also, could you paste the output from running `termux-info`?

**Comment by bestvow** [comment]
Sorry for my recklessness.
Please see the gif.
Android 8.0 system with the latest version termux & redis.
![333](https://user-images.githubusercontent.com/24888709/44729788-1ed77d80-ab12-11e8-9909-de18087b2822.gif)

**Comment by xeffyr** [comment]
@fornwall I did a fix for this issue in https://github.com/termux/termux-packages/pull/2786.

**Comment by xeffyr** [comment]
@bestvow This should be fixed now. Just update and do `redis-cli` again.

**Comment by fornwall** [comment]
Thanks to @xeffyr this is fixed in version `4.0.11-1` of the redis package!

Run `pkg up` to update and let us know if any problem remain.

**Comment by sicaboy** [comment]
A fresh install today and this issue happened. Googled and found this issue.

**Comment by JosiasAurel** [comment]
Hey, I tried installing redis and it didn't work for me. I had this error :
```shell
$ redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected>
```

**Comment by xeffyr** [comment]
> Hey, I tried installing redis and it didn't work for me.

It doesn't work for *you* because server is not started.

Start server (`redis-server`) and it will work.

![Screenshot_20200704-202056_Termux](https://user-images.githubusercontent.com/25881154/86517800-5ca33c80-be34-11ea-9f0e-dcd85aaa5ae1.jpg)

**Comment by JosiasAurel** [comment]
Thanks alot 🙏. I am new to redis that's why 😋
