### ISSUE TITLE
Pakage request: lxde

### ISSUE THREAD

**Issue by zaoqi** [termux/termux-packages#2792]

**Comment by xeffyr** [comment]
X11 packages are out of scope and won't be officially available for Termux.

***

Some X11 packages may be found in my repository here https://github.com/xeffyr/termux-extra-packages, but I don't provide major DEs such as LXDE/GNOME/KDE etc...

**Comment by sdrausty** [comment]
@zaoqi https://github.com/sdrausty/TermuxArch/issues/73 Xorg : How to Run Xserver might have what you are seeking.
