### ISSUE TITLE
Pakage request: GNU libc

### ISSUE THREAD

**Issue by zaoqi** [termux/termux-packages#2798]

**Comment by xeffyr** [comment]
@zaoqi It is very unlikely that we will switch Termux to use GNU libc instead of Bionic.

If you really need GNU libc, I suggest you to try this: https://github.com/Neo-Oli/termux-ubuntu, or any other way installing linux distribution into chroot (or proot) environment.

**Comment by aiisuika** [comment]
Or even install a linux distro into chroot/proot and bind termux's dir, then manually build glibc into termux
It'd be best to install into a directory that isn't `$PREFIX` alot will break :p

**Comment by sdrausty** [comment]
@zaoqi it is also available in https://sdrausty.github.io/TermuxArch/.

```
root08:32home$ pcss glibc
core/glibc 2.28-4 (base) [instalado]
    GNU C Library
```

**Comment by lukechilds** [comment]
>It is very unlikely that we will switch Termux to use GNU libc instead of Bionic.

@xeffyr why is this? I'm not arguing it should be, just interested in what the reasoning is.

Wouldn't using glibc enable most existing pre-built aarch64 binaries to work in Termux? What's the downside?

**Comment by lukechilds** [comment]
I found this:

>To have best compatibility with Android OS and remove the need of maintaining custom toolchains we compile all our packages with Android NDK. Resulting binaries are linked against Bionic libc (files libc.so, libm.so, libdl.so from /system/lib or /system/lib64).

https://wiki.termux.com/wiki/Differences_from_Linux

What makes maintaining an apt repo with patched binaries for Bionic easier than a custom toolchain?

**Comment by RossComputerGuy** [comment]
Bionic has differences in system calls, it's designed specifically for Android. Running Glibc linked programs won't work because of the system calls that Android has.

**Comment by lukechilds** [comment]
@RossComputerGuy so how are glibc linked binaries able to work in a prooted environment?

**Comment by RossComputerGuy** [comment]
Because proot is able to intercept the system calls. https://wiki.termux.com/wiki/PRoot

**Comment by lukechilds** [comment]
Ah, got it.

Thanks!

**Comment by Maxython** [comment]
Note: the glibc package and packages that are based on the glibc library are already available in Termux, read more - https://www.reddit.com/r/termux/s/BKOnayd3kB
