### ISSUE TITLE
Package Request: Ruby-dev 

### ISSUE THREAD

**Issue by CRamsan** [termux/termux-packages#281]
I am looking for a solution to run some Ruby apps in Android(currently working with Jekyll) and ruby is available but not the development headers needed to build some of the modules. Having this package would be awesome :)

Thanks guy,
Keep up the good work

**Comment by Neo-Oli** [comment]
Is the `ruby-dev` package that is available not the one you're looking for?
```
$ apt show ruby-dev
Package: ruby-dev
Version: 2.3.1-3
Maintainer: Fredrik Fornwall <fredrik@fornwall.net>
Installed-Size: 344 kB
Depends: ruby
Homepage: https://www.ruby-lang.org/
Download-Size: 44.5 kB
APT-Manual-Installed: yes
APT-Sources: http://termux.net stable/main arm Packages
Description: Development files for ruby
```
