### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-sntlp83_/mechanize/

### ISSUE THREAD

**Issue by Rehyans** [termux/termux-packages#2810]
While trying to install 
Pip install mechanize this error showed up please help me to solve this problem

**Comment by Grimler91** [comment]
Try following the generic instructions at https://wiki.termux.com/wiki/Instructions_for_installing_python_packages to install from aource

**Comment by Rehyans** [comment]
Nothing helped me

**Comment by xeffyr** [comment]
@Rehyans ```pip2 install mechanize``` works for me without error.

Make sure that you use **pip2** instead of **pip**.

**Comment by Grimler91** [comment]
Closing since we lack information about the problem.

**Comment by xeffyr** [comment]
@Grimler91 I posted a solution to problem (see previous post).

**Comment by Grimler91** [comment]
@xeffyr pip2 instead of pip3? Good to know that python2 is necessary. 
Feels like the problem might just as well have been missing headers though, but maybe you're right!

**Comment by Sam7798** [comment]
Collecting setup.py
  ERROR: Could not find a version that satisfies the requirement setup.py (from versions: none)
ERROR: No matching distribution found for setup.py

**Comment by xeffyr** [comment]
> Collecting setup.py

There no such python package as `setup.py` - it is just a script usually distributed with python package sources.
