### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by Egrak** [termux/termux-packages#2818]
What is the solution to this error(
Error updating)
pkg update
Ign:1 https://hax4us.github.io/termux-tools termux InRelease
Hit:2 https://termux.net stable InRelease
Ign:4 https://hax4us.github.io/termux-tools termux Release
Ign:5 https://hax4us.github.io/termux-tools termux/extras arm Packages
Get:3 https://ipfs.io/ipns/xeffyr.ml/termux extra InRelease [10.5 kB]
Ign:6 https://hax4us.github.io/termux-tools termux/extras all Packages
Ign:5 https://hax4us.github.io/termux-tools termux/extras arm Packages
Ign:6 https://hax4us.github.io/termux-tools termux/extras all Packages
Ign:5 https://hax4us.github.io/termux-tools termux/extras arm Packages
Ign:6 https://hax4us.github.io/termux-tools termux/extras all Packages
Err:5 https://hax4us.github.io/termux-tools termux/extras arm Packages
  404  Not Found
Ign:6 https://hax4us.github.io/termux-tools termux/extras all Packages
Fetched 10.5 kB in 4s (2218 B/s)
Reading package lists... Done
E: Failed to fetch https://hax4us.github.io/termux-tools/dists/termux/extras/binary-arm/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead

**Comment by xeffyr** [comment]
> Err:5 https://hax4us.github.io/termux-tools termux/extras arm Packages
404 Not Found

Remove `https://hax4us.github.io/termux-tools` from your sources.list

**Comment by Egrak** [comment]
How can I login to a file( sources.list)

**Comment by xeffyr** [comment]
@Egrak Remove this line:
```
deb [trusted=yes arch=all,arm] https://hax4us.github.io/termux-tools termux extras
```

**Comment by Egrak** [comment]
This does not result in any problems
In the update?

**Comment by Egrak** [comment]
Thank you so much😊😊😊😊

**Comment by yoyosourav** [comment]
Help me I am not able to install any pkg
Ever time show this:-
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by xeffyr** [comment]
> Sub-process https received signal 4.

Likely you have a VFP-only device. If so, you cannot use Termux.

**Comment by cipher015** [comment]
Can someone help this?pkg install ruby
Ign:1 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:2 https://dl.bintray.com/grimler/termux-root-packages-21 root InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Ign:4 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable InRelease
Ign:5 https://dl.bintray.com/xeffyr/x11-packages-21 x11 InRelease
Get:6 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-21 games Release
Get:8 https://dl.bintray.com/grimler/termux-root-packages-21 root Release [5342 B]
Hit:8 https://dl.bintray.com/grimler/termux-root-packages-21 root Release
Get:10 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:10 https://dl.bintray.com/grimler/science-packages-21 science Release
Get:12 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release [6065 B]
Hit:12 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release
Get:14 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release [6055 B]
Hit:14 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release
Err:16 https://termux.net stable InRelease
  Operation timed out after 120001 milliseconds with 0 out of 0 bytes rec
When i tried to pkg install for another package,the message is same like this,Sorry for my bad english

**Comment by ZeeMahn** [comment]
I'm experiencing the same here.. how can I find my source list and edit on my android phone ..

**Comment by cipher015** [comment]
But,now it has fixed.I think it because the internet are slow down when you
trying to install it pkg.
