### ISSUE TITLE
Package request: brute forcers + update

### ISSUE THREAD

**Issue by elogada** [termux/termux-packages#2819]
I'm pentesting via local, would make my job easier if I got brute forcers like _dirb_ , _sublist3r_ and _sqlmap_ natively. They run on GET and HEAD requests, so running them from root is not a problem.

Traceroute isn't updated. It needs TCP/UDP options. ICMP doesn't do the job these days anymore.

**Comment by Grimler91** [comment]
It would probably be better to open one package request for each package. 

sqlmap can be installed through pip, do you encounter any problems with it?

**Comment by elogada** [comment]
SQLmap looks mint! I'll open another thread for networking tools, thanks.

Closing.
