### ISSUE TITLE
clang update may have broken something to do with atomic

### ISSUE THREAD

**Issue by joakim-noah** [termux/termux-packages#282]
I'm compiling the exact same codebase that I was before with clang 3.8.0-2, but it doesn't link anymore when using `-std=c++11`, because most object files are now missing `__atomic_fetch_add_4`.  Looking at prior C++ builds, none of the object files had that symbol anywhere and I'm not sure where it's coming from now.  I think this is a regression in the latest clang, or possibly libandroid-support-dev, which is the only other package containing headers that was updated.  I last updated four days ago, so it's something recent that's broken.

__Update:__ Another example is that I was able to build llvm locally before, but it now fails with this message when building with clang:

```
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Failed
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - not found
CMake Error at cmake/modules/CheckAtomic.cmake:36 (message):
  Host compiler appears to require libatomic, but cannot find it.
```

That first atomics test passes with g++ 6.1.0, so I tried building llvm with g++, but it barfs on the first file in llvm with many errors.

__Update 2:__ by adding `-target armv7-linux-android` to my `CFLAGS` and `CXXFLAGS`, llvm passes the atomic check and is compiling again.  Funny what a big difference that subtle change makes. :)

**Comment by fornwall** [comment]
Thanks! Fixed in the `3.8.0-5` version of the clang package now.
