### ISSUE TITLE
Package request: networking pentesting tools

### ISSUE THREAD

**Issue by elogada** [termux/termux-packages#2820]
Stuff like _traceroute_, _ping_, _nslookup_, _shodan_, _nettools_, basically anything that touches the internet protocol.

Nevermind IPV6 for now.

**Comment by elogada** [comment]
EDIT: _net-tools_ with a dash.

Also, _nmap_ updates.

**Comment by xeffyr** [comment]
> ping

@elogada What's wrong with Android's ping command ?

> nslookup

You can find nslookup in dnsutils package.

**Comment by elogada** [comment]
Awesome, looks like nslookup is covered.

Anyway perhaps ping could be updated as per Linux standards? Idk the real difference, but I'm sure at some point there would be a more "effective" fork for Linux distros out there.

Anyway yeah close pls

**Comment by elogada** [comment]
Btw _nslookup_ is broken. _libirs.so_ is bugged. Fix pls?

**Comment by xeffyr** [comment]
> Btw nslookup is broken. libirs.so is bugged. Fix pls?

What is broken? Post examples please, because without this information nothing can be fixed.

**Comment by elogada** [comment]
_nslookup_ returns
```
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "cfg_type_dnsconf" referenced by "libirs.so"...
```

Any references on how to make that file?

As a hotfix I'm using Shodan's CLI as a glorified _WHOIS_ and _nslookup_ combined. The problem is that it needs a personal API key and is not native to Termux, perhaps for security's sake you can just patch up _dnsutils_.

Also for the rest I basically just added arch amd64 via dpkg and started downloading from the Kali repo. And btw is that legal?

**Comment by sdrausty** [comment]
> And btw is that legal?

It's like having a car; Depends on what you do with it.

**Comment by xeffyr** [comment]
> CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "cfg_type_dnsconf" referenced by "libirs.so"...

For me **nslookup** is working without issues. What's your architecture (`uname -m`) ?

**Comment by elogada** [comment]
My arch is armv71

This is my pentest phone, it's a Samsung J120H, no unofficial repos like the afformentioned Kali. I posted my ```apt list``` here
```
https://github.com/elogada/GET-Things/blob/master/apt.list
```

And yeah pls don't mind the src, thanks

**Comment by elogada** [comment]
Meh. *hugs his shodan API key*

Close thread? Close thread.

**Comment by Atavic** [comment]
You are the author, so close it.

**Comment by seffparker** [comment]
Why the issues is closed without a proper fix or ack? I still having issues on my aarch64 for all bins from dnsutils package.
```$ host
CANNOT LINK EXECUTABLE: could not load library "libirs.so" needed by "host"; caused by cannot locate symbol "isc_assertion_failed" referenced by "libirs.so"...
$ dig
CANNOT LINK EXECUTABLE: could not load library "libirs.so" needed by "dig"; caused by cannot locate symbol "isc_assertion_failed" referenced by "libirs.so"...
$ nslookup
CANNOT LINK EXECUTABLE: could not load library "libirs.so" needed by "nslookup"; caused by cannot locate symbol "isc_assertion_failed" referenced by "libirs.so"...```

All packages are up-to-date

**Comment by elogada** [comment]
@seffparker I fixed mine by downloading from the Kali Linux repository. This was done by adding amd64 architecture to my `dpkg`, then using `apt --allow-unauthenticated update`. since then I would use `apt --allow-unauthenticated install` for other means. It has seemed to work so far.

**Comment by xeffyr** [comment]
@seffparker Can't reproduce this on aarch64. Your packages are really `up-to-date` ? Do `pkg upgrade`, just in case.

Record with testing latest dnsutils, no linking errors found:
[![asciicast](https://asciinema.org/a/sbCPkYmrg15o1mogjdplXuX6p.png)](https://asciinema.org/a/sbCPkYmrg15o1mogjdplXuX6p)

@elogada Why this gets reopened ?

**Comment by elogada** [comment]
I was actually waiting on someone like you @xeffyr to give feedback on how this works in other machines/archs so that @seffparker can have input on a fix.

re-closing nao

**Comment by Grimler91** [comment]
Might be one of those cases when some device manufacturer does weird stuff. Might be solvable with `LD_PRELOAD=/system/lib/libirs.so`. I can't test it since it works fine on my device as well.

**Comment by ShowerShell** [comment]
Similar as @seffparker writes in https://github.com/termux/termux-packages/issues/2820#issuecomment-431631189 I get these error messages:
```
u0_a377@localhost~> dig
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "cfg_type_dnsconf" referenced by "libirs.so"...
u0_a377@localhost ~> nslookup
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "cfg_type_dnsconf" referenced by "libirs.so"...
```
@Grimler91 writes in https://github.com/termux/termux-packages/issues/2820#issuecomment-431665271
> Might be one of those cases when some device manufacturer does weird stuff. Might be solvable with `LD_PRELOAD=/system/lib/libirs.so`. I can't test it since it works fine on my device as well.

Most likely it has to do with a _missing_ libirs.so! 
```
u0_a377@localhost ~> find / -type f -iname "*libirs*" ^/dev/null
u0_a377@localhost ~> find / -iname "*libirs*" ^/dev/null
u0_a377@localhost ~>
```
_plz don't mind the_ ˋ^/dev/nullˋ _in_ ˋfishˋ _as it is equivalent to_ ˋ2>/dev/nullˋ _in_ ˋbashˋ

advice?

_My device is a Sony Xperia Tablet Z SGP321 (from the SGP3xx series) with Stock Android 5.1.1 (yeah, I know I should get officially supported LOS...)_
```
u0_a377@localhost ~> uname -m
armv7l
u0_a377@localhost ~> uname -a
Linux localhost 3.4.0-perf-gbccb33a #1 SMP PREEMPT Fri Jul 10 09:23:01 2015 armv7l Android
```

**Comment by xeffyr** [comment]
> Most likely it has to do with a missing libirs.so!
u0_a377@localhost ~> find / -type f -iname "*libirs*" ^/dev/null
u0_a377@localhost ~> find / -iname "*libirs*" ^/dev/null

@ShowerShell It's not missing. Fix your command and try again. Termux have everything in $PREFIX but /data is not searchable.
```
$ find $PREFIX -type f -iname "*libirs*"
/data/data/com.termux/files/usr/lib/libirs.so
```

> u0_a377@localhost ~> uname -m
armv7l
u0_a377@localhost ~> uname -a
Linux localhost 3.4.0-perf-gbccb33a #1 SMP PREEMPT Fri Jul 10 09:23:01 2015 armv7l Android

My device is ARMv7 too:
```
$ uname -a
Linux localhost 3.4.113-g955ea3f #1 SMP PREEMPT Sat Jun 30 09:25:00 UTC 2018 armv7l Android
```

But command `dig` is working:
```
$ dig google.com

; <<>> DiG 9.13.4 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3858
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		299	IN	A	216.58.215.78

;; Query time: 52 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Dec 10 22:38:53 EET 2018
;; MSG SIZE  rcvd: 55
```

This is a manufacturer issue.

**Comment by ShowerShell** [comment]
> @ShowerShell It's not missing. Fix your command and try again. Termux have everything in $PREFIX but /data is not searchable.

you're right, I noticed late and edited after your reply 

> ```
> $ find $PREFIX -type f -iname "*libirs*"
> /data/data/com.termux/files/usr/lib/libirs.so
> ```
> 
> > u0_a377@localhost ~> uname -m
> > armv7l
> > u0_a377@localhost ~> uname -a
> > Linux localhost 3.4.0-perf-gbccb33a #1 SMP PREEMPT Fri Jul 10 09:23:01 2015 armv7l Android
> 
> My device is ARMv7 too:
> 
> ```
> $ uname -a
> Linux localhost 3.4.113-g955ea3f #1 SMP PREEMPT Sat Jun 30 09:25:00 UTC 2018 armv7l Android
> ```
> 
> But command `dig` is working:
> 
> This is a manufacturer ROM issue.

ok, thanks!

so what @Grimler91 wrote in https://github.com/termux/termux-packages/issues/2820#issuecomment-431665271 is not relevant in my case? The setting of LD_PRELOAD is:
```
$ echo $LD_PRELOAD
/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xeffyr** [comment]
> so what @Grimler91 wrote in #2820 (comment) is not relevant in my case?

LD_PRELOAD'ing *might* solve...

Better solution is to use static libs in dnsutils. The dependency `libirs.so` will be dropped for commands as it will get compiled-in and errors will likely disappear.

**Comment by Xarchuser** [comment]
Thank it worked! xeffyr
