### ISSUE TITLE
Zsh module: fails to load zsh/stat

### ISSUE THREAD

**Issue by xPMo** [termux/termux-packages#2829]
This is a (new?) dependency of zplugin [(via zui)](https://github.com/zdharma/zui/blob/8978ae38be33f3e585ec46f41bf6a730ea1c8911/zui.plugin.zsh#L53).

Similar to previous issues like #672.

**Comment by fornwall** [comment]
Thanks! In the updated 5.6.2 version of the zsh package that is now available the zsh/stat module is now available.
