### ISSUE TITLE
Php driver installation

### ISSUE THREAD

**Issue by swashvirus** [termux/termux-packages#2830]
Whenever i install php-pgrsql pdo drivers on my device i it keeps failing in 
The cli when i run php --ini pointing it  my php.ini i get errors 

$ php --ini
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_pgsql.so' (tried: /data/data/com.termux/files/usr/lib/php/php_pgsql.so (dlopen failed: library "/data/data/com.termux/files/usr/lib/php/php_pgsql.so" not found), /data/data/com.termux/files/usr/lib/php/php_pgsql.so.so (dlopen failed: library "/data/data/com.termux/files/usr/lib/php/php_pgsql.so.so" not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'php_pgsql.so' (tried: /data/data/com.termux/files/usr/lib/php/php_pgsql.so (dlopen failed: library "/data/data/com.termux/files/usr/lib/php/php_pgsql.so" not found), /data/data/com.termux/files/usr/lib/php/php_pgsql.so.so (dlopen failed: library "/data/data/com.termux/files/usr/lib/php/php_pgsql.so.so" not found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_pdo_pgsql.so' (tried: /data/data/com.termux/files/usr/lib/php/php_pdo_pgsql.so (dlopen failed: library "/data/data/com.termux/files/usr/lib/php/php_pdo_pgsql.so" not found), /data/data/com.....

**Comment by swashvirus** [comment]
Solved boss actually it worked but   just needed a deep reboot 👏

**Comment by kusmantopratama** [comment]
> Solved boss actually it worked but just needed a deep reboot

@swashvirus can you guide me how to enable php pgsql on termux ?

**Comment by swashvirus** [comment]
It's been two years (I no longer program in php)

You haven't described what your problem is yet so here's a general advice
# install PostgreSQL server
`apt install postgresql`
# install PHP interpreter and psql drivers
`apt install php php-psql`

John Swana

**Comment by swashvirus** [comment]
It's been two years (I no longer program in php)

You haven't described what your problem is yet so here's a general advice
- install PostgreSQL server
`apt install postgresql`
- install PHP interpreter and psql drivers
`apt install php php-psql`

John Swana
