### ISSUE TITLE
python 3.5.1-6 i686: no `_sqlite3.so`

### ISSUE THREAD

**Issue by kazuoteramoto** [termux/termux-packages#284]
Hi!

After the update to python 3.5.1-6 i686 I can't import sqlite
```sh
$ python -c 'import sqlite3'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/data/data/com.termux/files/usr/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
```
I don't have `_sqlite3.so` in `lib-dynload/`. Looking at debs from http://termux.net/dists/stable/main/ seens that only `i686` is missing the `_sqlite3.so`, `arm` and `aarch64` python have a `_sqlite3.so` file.

Thanks!

PS. Is this the right place to report packaging bugs?
PPS. I did not find the old `.deb` on my system, are they saved somewhere so I can downgrade when some problem happen?

**Comment by fornwall** [comment]
Thanks! This has now been fixed in the `3.5.1-7` version of the python package.

> PS. Is this the right place to report packaging bugs?

Yes it it!

> PPS. I did not find the old .deb on my system, are they saved somewhere so I can downgrade when some problem happen?

They are not saved away at the moment. I have them in an offline backup, so I will look at exposing them online somewhere!
