### ISSUE TITLE
CANNOT LINK EXECUTABLE "lftp": library "libssl.so.1.1" not found

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#2843]
```
$ ./setupTermuxArch.sh l

Setting `lftp` as download manager.

 🕛 > 🕛 TermuxArch v1.6.id1684 shall attempt to install Linux in /data/data/com.termux/files/home/arch.  Arch Linux in Termux PRoot shall be available upon successful completion.  To run this BASH script again, use `!!`.  Ensure background data is not restricted.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

Using lftp to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

CANNOT LINK EXECUTABLE "lftp": library "libssl.so.1.1" not found
./setupTermuxArch.sh: line 154:  8386 Aborted                 lftpget -c "${FILE[sha]}" "${FILE[tar]}"

 TermuxArch WARNING:  Generated script signal 134 near or at line number 581 by `trap`!

setupTermuxArch.sh l v1.6.id1684: (Exit Signal 201) DONE 🏁
```
```
$ lftpget -v
Usage: /data/data/com.termux/files/usr/bin/lftpget URL [URL...]
$ lftpget -h
CANNOT LINK EXECUTABLE "lftp": library "libssl.so.1.1" not found
Aborted
```
```
$ lftpget https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh
CANNOT LINK EXECUTABLE "lftp": library "libssl.so.1.1" not found
Aborted
```
[LFTP](https://github.com/lavv17/lftp) works like a charm on Android 7, output is from Android 8 smartphone.  Furthermore, I was considering how lftp might perform as default DM, and ran into this issue on Android 8.

**Comment by sdrausty** [comment]
$ pkg list-installed |f lftp

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

lftp/stable,now 4.8.4-1 arm [installed]

> For me, lftp working fine...

@xeffyr 
> LFTP works like a charm on Android 7
> I was considering how lftp might perform as default DM, and ran into this issue on Android 8.

**Comment by xeffyr** [comment]
@sdrausty Okay, your device is ARM ? I can do check on ARM device (Android 6.0.1).

**Comment by sdrausty** [comment]
I AM SUPRISED that I missed `pkg up` before posting:
```
Setting `lftp` as download manager.

 🕛 > 🕛 TermuxArch v1.6.id1684 shall attempt to install Linux in /data/data/com.termux/files/home/arch.  Arch Linux in Termux PRoot shall be available upon successful completion.  To run this BASH script again, use `!!`.  Ensure background data is not restricted.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

Using lftp to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…


 🕛 > 🕐 TermuxArch download: OK

 🕛 > 🕜 TermuxArch v1.6.id1684 integrity: OK

Setting locales to: Language >> en_US << Region
```
Thank you @xeffyr🛀🛌

**Comment by sdrausty** [comment]
One of the reasons that I invested considerable time and energy enabling this new feature (if any of these aria2, axel, curl, lftp, and/or wget are on device, use one of them) is user satisfaction coupled with bandwidth economy!  Are there any more Termux https capable download managers that I may have missed @xeffyr?  As far as I know we have five of them packaged as Termux packages currently.

**Comment by xeffyr** [comment]
> axel
> bandwidth economy

@sdrausty Axel + bandwidth economy is something new for me.

While it is supposed to be used as download accelerator by creating connections to **multiple** mirrors for downloading one file, there are users that abuse it by opening 1000+ connections to one server thinking that file will be downloaded faster. Side effect of such abuse is DoS if server is not configured for big amount of connections/traffic. I really don't like this tool...

> Are there any more Termux https capable download managers that I may have missed

I don't think that there is something better than **curl** or **wget** for just downloading files. I prefer to use **curl** in scripts and **wget** in interactive shell.

**Comment by sdrausty** [comment]
> Axel + bandwidth economy is something new for me.

@xeffyr you brought up an interesting point about usage.  The bandwidth economy I was referencing is if a user has already downloaded on or more of these tools, they will not be asked to download one more.
