### ISSUE TITLE
Remove Support For 5.1 Lollipop Android Version 

### ISSUE THREAD

**Issue by V3rB0se** [termux/termux-packages#2850]
Stop supporting Lollipop if it cant support termux 
after update termux apt-get update 
it gives me an error every time i run the command apt-get install 'ex' Warning Linker Unsupported Flags_1=0x8.?!
Neither Metasploit Is Working 
Gives me an error ./msfconsole

Segmentation Fault.

**Comment by Grimler91** [comment]
The linker message is a warning, not an error (you can get rid of it with `termux-elf-cleaner`).
Metasploit isn't a termux package so report it to the correct maintainer instead.

See also https://github.com/termux/termux-packages/issues/2846

**Comment by Harshiv-Patel** [comment]
See this: WARNING: linker: Unsupported flags DT_FLAGS_1=0x8 on Android 5.1 #2846 for the warnings.
