### ISSUE TITLE
Package request: libtga

### ISSUE THREAD

**Issue by Ranjan-Bagri** [termux/termux-packages#2853]
I noticed libtga is unavailable in termux while working on pov-ray. Then I tried to compile it from source as guided [here](https://wiki.termux.com/wiki/Package_Management#Community_Repositories). But it threw bunch of errors. Is it possible to package it for aarch64? 

Some additional links about <kbd>libtga</kbd>

[http://tgalib.sourceforge.net](http://tgalib.sourceforge.net)

[https://github.com/madebr/libtga](https://github.com/madebr/libtga)

**Comment by xeffyr** [comment]
> Then I tried to compile it from source as guided here.

You didn't follow [guide](https://wiki.termux.com/wiki/Package_Management#Compiling_packages_on_device). At least you missed one step.

Your lib compiled with guide from Wiki:
[libtga.tar.gz](https://github.com/termux/termux-packages/files/2389559/libtga.tar.gz)

**Comment by Ranjan-Bagri** [comment]
@xeffyr Thanks for your quick response. Can you please tell me how to install  the compiled version?

**Comment by xeffyr** [comment]
@Ranjan-Bagri Since this is a tar archive, unpack it in this way (package `tar` needed):
```
tar xf libtga.tar.gz --strip-component=1 -C /
```

**Comment by Ranjan-Bagri** [comment]
Unfortunately I'm still getting error.
```sh
tar: data/data: Cannot utime: Permission denied
tar: data/data: Cannot change mode to rwx------: Permission denied
tar: data: Cannot utime: Permission denied
tar: data: Cannot change mode to rwx------: Permission denied
tar: Exiting with failure status due to previous errors
```

**Comment by xeffyr** [comment]
Use *.deb files then (don't forget to gunzip before installing with dpkg):
[libtga_1.0.1_aarch64.deb.gz](https://github.com/termux/termux-packages/files/2390016/libtga_1.0.1_aarch64.deb.gz)
[libtga-dev_1.0.1_aarch64.deb.gz](https://github.com/termux/termux-packages/files/2390017/libtga-dev_1.0.1_aarch64.deb.gz)

**Comment by Ranjan-Bagri** [comment]
Thanks again. That works.

**Comment by xeffyr** [comment]
Since this package is small and **rarely** used (I can't find it in debian and archlinux official repos) so it probably won't be added to the Termux unless here will be a package that requires it.
