### ISSUE TITLE
Why is Termux emacs 10x slower while loading?

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#2856]
Why is Termux emacs 10x slower while loading when compared with TermuxArch?

**Comment by rien333** [comment]
@fornwall What was the reason for closing this? Probably something to do with the (restricted) andriod environment, but it would be still nice to know why/if this is impossible.

**Comment by xeffyr** [comment]
Most likely due to https://github.com/termux/termux-packages/blob/master/packages/emacs/build.sh#L65.

**Comment by rien333** [comment]
if somebody stumbles upon this: `emacs --daemon` works pretty okay! :smile:
