### ISSUE TITLE
Package request: EncFS

### ISSUE THREAD

**Issue by AnderRasoVazquez** [termux/termux-packages#286]
From the Arch Wiki:

> [**EncFS**](https://wiki.archlinux.org/index.php/EncFS) is a userspace stackable cryptographic file-system similar to eCryptfs, and **aims to secure data with the minimum hassle**. It uses FUSE to mount an encrypted directory onto another directory specified by the user. It does not use a loopback system like some other comparable systems such as TrueCrypt and dm-crypt.
> 
> EncFS is definitely the simplest software if you want to try disk encryption on Linux.
> 
> This has a number of advantages and disadvantages compared to these systems. Firstly, **it does not require any root privileges to implement**; any user can create a repository of encrypted files. Secondly, one does not need to create a single file and create a file-system within that; it works on existing file-system without modifications.
> 
> This does create a few disadvantages, though; because the encrypted files are not stored in their own file, someone who obtains access to the system can still see the underlying directory structure, the number of files, their sizes and when they were modified. They cannot see the contents, however.
> 
> This particular method of securing data is obviously not perfect, but there are situations in which it is useful.

**Comment by timoc** [comment]
+1

**Comment by bharat226g** [comment]
+1 
I think most of the present day android device have kernel fuse support.
And there are apps in play store, that implemented encfs without requiring any root permissions. 
One such good app is [https://github.com/neurodroid/cryptonite](url)

**Comment by ackalker** [comment]
From: http://stackoverflow.com/a/9292958

> Edit: And even if many devices would have fuse support buildin chances are high they wouldn't let you mount it as a user, **you would need root access** as your app wouldn't have the privileges to mount fuse filesystems.

Emphasis mine.

**Comment by bharat226g** [comment]
encfs root access is needed only when mounting to sdcard path or some other path that the app wont normally have access to. I think root access is not needed when mounting to the apps own private directory (termux home path). Im happy to mount an encfs folder to termux home and copy the files from sdcard to it over command line.

Cryptonite works both on rooted and non-rooted devices. On rooted devices, it mounts encfs to sdcard folder. While on non-rooted devices, it doesnt mount to the sdcard, maybe it mounts to the apps private space, and provides a builtin minimalistic file manager to transfer files to and from it.

**Comment by BlueMax** [comment]
There is a collection of static binaries for Android that includes encfs binaries:
https://forum.xda-developers.com/android/software/utils-data-recovery-tools-testdisk-t3709380

**Comment by Grimler91** [comment]
I've added encfs (and libfuse) to the root repo: https://github.com/termux/termux-root-packages

It's basically un-tested so if anyone could try it out then that would be great.

**Comment by phorward** [comment]
Hi there!

Running the command `encfs ~/.home ~/home` runs well until after the password is prompted.

Then, I'm getting:
```
fuse: failed to open /dev/fuse: Permission denied
fuse failed.  Common problems:
 - fuse kernel module not installed (modprobe fuse)
 - invalid options -- see usage message
```
`modprobe` is not available in termux. Any idea?

**Comment by xeffyr** [comment]
> fuse: failed to open /dev/fuse: Permission denied
my device is not rooted or anything. Is this necessary?
modprobe is not available in termux.

Of course it require root. Android prohibits access to /dev/fuse for all regular Android applications (even for system ones).
The same goes for `modprobe`.

***

> This has a number of advantages and disadvantages compared to these systems. Firstly, it does not require any root privileges to implement; any user can create a repository of encrypted files. - from https://github.com/termux/termux-packages/issues/286#issue-157094406

Remember: all fuse-based software **require** (!) root if permission for /dev/fuse is restricted. On Android it is:
```
$ ls -l /dev/fuse
ls: cannot access '/dev/fuse': Permission denied
$ uname -a
Linux localhost 3.18.91-13895453-QB19588892 #1 SMP PREEMPT Fri Aug 31 14:19:51 KST 2018 aarch64 Android
```

On desktop Linux distribution it is:
```
xeffyr@archlinux-pc-xeffyr:~:$ ls -l /dev/fuse
crw-rw-rw- 1 root root 10, 229 ноя 21 13:08 /dev/fuse
xeffyr@archlinux-pc-xeffyr:~:$ uname -a
Linux archlinux-pc-xeffyr 4.19.2-arch1-1-ARCH #1 SMP PREEMPT Tue Nov 13 21:16:19 UTC 2018 x86_64 GNU/Linux
```

**Comment by xeffyr** [comment]
Package is available in https://github.com/termux/termux-root-packages.
If you experience any problems with package, you can open issue in https://github.com/termux/termux-root-packages/issues.

**Comment by c0dd3vi11** [comment]
Can't understand. Is it possible to install disabled package?

https://github.com/termux/termux-root-packages/blob/5c216e6ef82db1ec662bca1937e334287cd7fbae/disabled-packages/packages/encfs/build.sh

**Comment by xeffyr** [comment]
> Is it possible to install disabled package?

Disabled means **removed**, i.e. non-installable.
libfuse is broken in Termux and segfaults.

**Comment by FreddieOliveira** [comment]
# EncFS building instructions

## Intro

This package request is better suited at termux-root-packages, since it requires libfuse2 and can oly be used by root.

Here's the Ubuntu package page for reference:
https://packages.ubuntu.com/focal/encfs

## Building

### Dependencies

These are the libs it depends upon:

```
libfuse.so.2
libssl.so.1.1
libcrypto.so.1.1
libc.so
libc++_shared.so
libdl.so
```

### Steps

All the steps above were executed from within termux using the git master branch, since the latest stable release dates back from 2018 and contains some bugs which would require patches to be able to compile it.

```
$ git clone https://github.com/vgough/encfs.git
$ mkdir encfs/build && cd encfs/build
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr ..
$ make -j8
$ make install/strip
```

### Testing

EncFS comes with a test suite. This is good, because libfuse2 doesn't come with any tests, so we can use the EncFS ones to check if libfuse2 is working correctly. To run the tests, first complete the steps above to build the project and then run `sudo make integration` to build and run them. On my phone they succeeded.

## Aditional info

So far, everything seems to be working as expected. This is the list of files added to the system when installed:

```
files
└── usr
    ├── bin
    │   ├── encfs
    │   ├── encfsctl
    │   └── encfssh
    └── share
        ├── locale
        │   ├── ar
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── be
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── bg
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── bs
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── ca
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── cs
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── da
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── de
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── de_AT
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── de_CH
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── de_DE
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── el
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── eo
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── es
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── es_ES
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── es_PE
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── et
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── fi
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── fr
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── fr_FR
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── gl
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── he
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── hr
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── hu
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── id
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── it
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── ja
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── ko
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── lv
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── nb
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── nds
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── nl
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── nn
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── oc
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── pl
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── pt
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── pt_BR
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── pt_PT
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── ro
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── ru
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── sk
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── sr
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── sv
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── ta
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── tr
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── uk
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── vi
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── zh_CN
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   ├── zh_HK
        │   │   └── LC_MESSAGES
        │   │       └── encfs.mo
        │   └── zh_TW
        │       └── LC_MESSAGES
        │           └── encfs.mo
        └── man
            └── man1
                ├── encfs.1
                ├── encfsctl.1
                └── encfssh.1

106 directories, 56 files
```

I'm not a CryFS evangelizer, but I recommend reading this comparison between it and EncFS: https://www.cryfs.org/comparison/
