### ISSUE TITLE
A recent upgrade broke autossh

### ISSUE THREAD

**Issue by mayureshw** [termux/termux-packages#2863]
For a long time I was using autossh - dropbear combination without any problems. It used to maintain an active ssh connection in event of network changes etc.

Recently I did a pkg upgrade. Firstly it broke the autossh - dropbear compatibility and forced to replace dropbear with openssh. Since then the connection is not being reliably retained. autossh gets killed intermittently.

**Comment by fornwall** [comment]
As of the latest `1.4f-1` version of the autossh package it now lists either openssh or dropbear as a dependency, so you can go back to using dropbear.

About autossh being killed: Does using it with dropbear make a difference? Can you make sure that you are running with a wake lock (https://wiki.termux.com/wiki/Termux-wake-lock) perhaps and see if that makes a difference?

**Comment by mayureshw** [comment]
Thanks. I have switched back to autossh-dropbear combination which worked for me for long - yes with wake lock enabled.

Whether the problem was with autossh-openssh combination or whether autossh has developed some problem - will come to know. Will need to observe for a day or two as it was a random issue.

**Comment by mayureshw** [comment]
Have been observing for a while now. autossh is unable to retain connection. In earlier versions it used to retain the connection quite reliably. autossh is just seen exiting and exact scenario is not known. Shall I try any specific CLI options to make autossh retry instead of quit?

**Comment by mayureshw** [comment]
I had reported this to upstream and understand 1.4g should have fixed this. I have upgraded it and is under observation. So far no recurrence of the issue.

**Comment by fornwall** [comment]
@mayureshw Great, thanks for letting us know! I'm closing the issue, let us know if you find out anything that needs to be done!
