### ISSUE TITLE
OpenSSH updates overwrite sshd_config

### ISSUE THREAD

**Issue by Hackerpcs** [termux/termux-packages#2866]
As title says, when OpenSSH is updated it overwrites my sshd_config in ~/../usr/etc/ssh, having to copy a backup of it on every update.

**Comment by fornwall** [comment]
Thanks for reporting! This should be now be fixed in version 7.8p1-2 of the openssh package, run `pkg up` to update!

**Comment by Hackerpcs** [comment]
Thanks. Besides that, is it possible to not generate the kinds of public keys for the server not used? E.g. I use only RSA and ED25519 but the update generated DSA and ECDSA keys.

**Comment by xeffyr** [comment]
@Hackerpcs Why not to modify sshd_config to use only specific host keys then ? It will use only specified keys and ignore other.

**Comment by Hackerpcs** [comment]
I already do. On Ubuntu e.g. it doesn't generate the additional keys after updates
