### ISSUE TITLE
Help plzzzzzz 

### ISSUE THREAD

**Issue by nauat** [termux/termux-packages#2870]
When i Write. /msfconsole i get 

WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: nokogiri.so: unused DT entry: type 0x6ffffef5 arg 0xb18
WARNING: linker: pcaprub_c.so: unused DT entry: type 0x6ffffef5 arg 0x36c
WARNING: linker: bcrypt_ext.so: unused DT entry: type 0x6ffffef5 arg 0x25c
WARNING: linker: msgpack.so: unused DT entry: type 0x6ffffef5 arg 0x60c
WARNING: linker: redcarpet.so: unused DT entry: type 0x6ffffef5 arg 0x2b4
WARNING: linker: pg_array_parser.so: unused DT entry: type 0x6ffffef5 arg 0x1b4
WARNING: linker: pg_ext.so: unused DT entry: type 0x1d arg 0x1682
WARNING: linker: pg_ext.so: unused DT entry: type 0x6ffffef5 arg 0xb4c
Segmentation faultetasPloit Framework console...-
$

Why?

**Comment by AnikHasibul** [comment]
Check https://github.com/anikhasibul/wsh

**Comment by Grimler91** [comment]
Metasploit isn't a termux package so this "issue" isn't relevant here. Try asking in the other [community channels](https://wiki.termux.com/wiki/Community).
