### ISSUE TITLE
pulseaudio throws "Bad system call" on Android Pie

### ISSUE THREAD

**Issue by edward-p** [termux/termux-packages#2887]
Similar to [https://github.com/termux/termux-packages/issues/2714](https://github.com/termux/termux-packages/issues/2714) :

```
gdb /data/data/com.termux/files/usr/libexec/pulseaudio
...
(gdb) run
Starting program: /data/data/com.termux/files/usr/libexec/pulseaudio 
warning: .dynamic section for "/data/data/com.termux/files/usr/libexec/pulseaudio" is not at the expected address (wrong library or version mismatch?)

Program received signal SIGSYS, Bad system call.
0x0000007fb74f1224 in setresgid () from /system/lib64/libc.so
...
```

**Comment by xeffyr** [comment]
@edward-p It is better to attach strace log, it at least helps to identify which syscall was blocked by seccomp.

**Comment by edward-p** [comment]
> @edward-p It is better to attach strace log, it at least helps to identify which syscall was blocked by seccomp.
> 
> Strace is not working for me in Android Pie AVD. But logcat says that this is caused by x86 system call 203 (which is sys_setreuid()).
> 
> I guess we can just remove calls like this:
> 
> ```
> #if defined(HAVE_SETRESUID)
>     r = setresuid(pw->pw_uid, pw->pw_uid, pw->pw_uid);
> ```
> - they don't needed in Termux anyway.

Works!

However, it seems that all packages which have calls like this need fixing.
