### ISSUE TITLE
Package request: GStreamer

### ISSUE THREAD

**Issue by mklein994** [termux/termux-packages#289]
I found out that [GStreamer](https://gstreamer.freedesktop.org/) has Android support:

> Binaries for GStreamer on Android that integrate into the Android NDK can be found [here](https://gstreamer.freedesktop.org/data/pkg/android/). They are provided and maintained by the GStreamer project.

source: https://gstreamer.freedesktop.org/data/pkg/android/

Is there any way this can be included in Termux? It seems that there is a lot of overlap between the projects as far as dependencies, but these are compiled as static libraries, and without the Termux-specific prefix of course. Let me know what you think.

My main goal is to build [mopidy](https://www.mopidy.com/).

**Comment by tristan-k** [comment]
Any news on this matter? I'm also trying to run mopidy.

**Comment by Grimler91** [comment]
@tristan-k it is already available in the repo, see https://github.com/termux/termux-packages/commit/1c0e18621626085d77d7d46d9ace819debb9de19
(I guess we can close this package request).

**Comment by tristan-k** [comment]
Great! Thanks for notifying me.
