### ISSUE TITLE
[git] Can't type password in git push

### ISSUE THREAD

**Issue by CreatorVilius** [termux/termux-packages#2891]
So basically, everything with git is fine, except push.

Whenever i push, i can type username, but not password. 

This makes me unable to git push in Termux.

**Comment by xeffyr** [comment]
> So basically, everything with git is fine, except push.

@CreatorVilius Git push via https and ssh works fine. Just tested.

> Whenever i push, i can type username, but not password.

Passwords are **invisible**, i.e not echoed to console which is a default behaviour for most Linux command line programs with password prompt.
Just make sure that you typed password correctly or use a password manager for copying/pasting password when needed.

**Comment by Sujitbabu** [comment]
I can't input my password within termux
