### ISSUE TITLE
Add openssl as dependency of dnsutils

### ISSUE THREAD

**Issue by crass** [termux/termux-packages#2898]
Installing `dnsutils` does not automatically install `openssl`.  However, `dig` links against `libcrypto.so.1.1` from the `openssl` package, and thus will not run without `openssl` being installed.

**Comment by xeffyr** [comment]
> Add openssl as dependency of dnsutils

@crass OpenSSL really isn't dependency of dnsutils ? See this: https://github.com/termux/termux-packages/blob/master/packages/dnsutils/build.sh#L7

My output of `apt show dnsutils` also show that openssl is a dependency:
```
$ apt show dnsutils
Package: dnsutils
Version: 9.12.2-P1-1
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 2765 kB
Depends: openssl, readline, resolv-conf
Homepage: https://www.isc.org/downloads/bind/
Download-Size: 741 kB
APT-Sources: https://termux.net stable/main aarch64 Packages
Description: Clients provided with BIND
```

**Comment by fornwall** [comment]
`pkg up` should solve the problem!

**Comment by crass** [comment]
I have no `pkg` binary.  Yes this is a fairly old install.  Is `pkg up` equivalent to `apt update`?

**Comment by Grimler91** [comment]
@crass it's equivalent of ˋapt update && apt upgradeˋ
