### ISSUE TITLE
Node stopped working, cannot find a library

### ISSUE THREAD

**Issue by freetnt5852** [termux/termux-packages#2903]
I've been using nodejs 9+ for ages and it was fine until today it throws `CANNOT LINK EXECUTABLE DEPENDENCIES: library "libcrypto.so.1.0.0" not found` some stuff happened today when i tried to install nginx, `pkg show libcrypto` gives no results so i have no idea what's going on, lemme know if you need anymore info

**Comment by fornwall** [comment]
First: run `pkg up` to update all installed packages. Does that solve your problem?

**Comment by freetnt5852** [comment]
@fornwall i don't want to update all packages at the moment I'm kinda low on storage, but in update list nothing about libcrypto is listed and i took a look at `$PREFIX/lib` and see `libcrypto.so
libcrypto.so.1.1` but it looks like node is trying to use an older version 1.0.0

**Comment by xeffyr** [comment]
@freetnt5852 We don't providing older versions of packages (rolling-release).

**Comment by freetnt5852** [comment]
@xeffyr there isn't any newer nodejs-current releases in termux repo, do i just try reinstalling it?

**Comment by xeffyr** [comment]
Choose a one of `nodejs` and `nodejs-lts`.

**Comment by freetnt5852** [comment]
Oh thanks, nice didn't know termux had node 10 that fixed it but another problem is now i get `$ node
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8` everytime i use node

**Comment by freetnt5852** [comment]
Ok found an issue about that warning: #2846 closing this now.
