### ISSUE TITLE
Mongo: library "libboost_program_options.so.1.67.0" not found

### ISSUE THREAD

**Issue by naveedpash** [termux/termux-packages#2904]
I've installed the mongodb package but when I run the mongo command, it gives the error in the title. I've installed packages boost and boost-dev and confirm that my $PREFIX/usr/lib folder has "libboost_program_options.so.1.68.0".

Can y'all fix the mongodb package to use the new one (68) instead of the old one (67)? (Unless there's a way I can jimmy that on my own, in which case I'm a n00b)

**Comment by xeffyr** [comment]
> I've installed the mongodb package

@naveedpash We have a mongodb package ? I don't see it in [available packages](https://github.com/termux/termux-packages/tree/master/packages).

> Can y'all fix the mongodb package to use the new one (68) instead of the old one (67)?

No, we can't as you installed a **third-party** package. You should open issue about `mongodb` where you get it.

**Comment by naveedpash** [comment]
![image](https://user-images.githubusercontent.com/879490/46142213-acbc9a80-c26f-11e8-994f-8ea61496c9d8.png)
Whoops, it's actually from the its-pointless repo. My bad...

(Btw impressive response time
Respect +1
Love +1
Paragon +1
LVL UP)
