### ISSUE TITLE
openssh uses hard link copy to update host keys

### ISSUE THREAD

**Issue by Quasic** [termux/termux-packages#2909]
I thought issues like this would be common, but I'm having trouble finding them. I don't mind submitting a PR, but I'd like to review similar fixes, first. It works fine in Android 5, but permission denied in Android 7. I'm sure I saw someone fix this in a termux package, before...

hostfile_replace_entries: link /data/data/com.termux/files/home/.ssh/known_hosts to /data/data/com.termux/files/home/.ssh/known_hosts.old: Permission denied
update_known_hosts: hostfile_replace_entries failed: Permission denied

**Comment by fornwall** [comment]
OpenSSH uses a link to take a backup while replacing the file:

1. link `known_hosts` to `known_hosts.old`
2. move new file to `known_hosts` (overwriting the link there)

I guess we can patch it to instead rename the file:

1. rename `known_hosts` to `known_hosts.old`
2. move new file to `known_hosts`

This leaves a window between (1) and (2) where there is no `known_hosts`. But the operation is quick and (2) should rarely fail, so this is probably acceptable (at least compared to the current broken state).

**Comment by fornwall** [comment]
This has now been patched in version `7.8p1-3` of the openssh package - install it with `pkg up` and let me know how it works.

Thanks a lot for reporting!

**Comment by Quasic** [comment]
Thanks for the quick response! I think that was the same solution used in the other case I seem to remember, but can't find...

**Comment by Quasic** [comment]
I confirmed that it works. Thanks again!
