### ISSUE TITLE
Package Request: whiptail

### ISSUE THREAD

**Issue by gwpl** [termux/termux-packages#291]
[whiptail](https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail) is alternative to [dialog](http://linux.die.net/man/1/dialog).
It's used by some scripts - even `raspi-config` canonical Raspberry Pi configuration tool uses it.
Therefore, I would vote for providing `whiptail` package, as it's quite often a hidden dependency, that allows running great variety of available scripts and code snippets laying around the web.
(It's simple tool, similar to already available `dialog` so I hope it won't be much overhead to add it as package)

**Comment by vaites** [comment]
I worked on S-Lang+Newt days ago and I just made the pull request. By now, to enable colors you must export $COLORTERM variable.

**Comment by fornwall** [comment]
If `$PREFIX/bin/whiptail` would be a symlink to `$PREFIX/bin/dialog`, would that work? In that dialog is compatible with most whiptail options (it seems to be an explicit goal of dialog)?

This symlink is setup now in the latest dialog package, so try it out!

**Comment by gwpl** [comment]
I am not aware about impact of differences between tools. So if they might be compatible in most cases, then why not.

**Comment by fornwall** [comment]
There is now a `whiptail` program provided by the `dialog` package. If one tries to run `whiptail` without that package, the following message is shown:

    The program 'whiptail' is not installed. Install it by executing:
      apt install dialog

Report if you encounter any incompatibilities with whiptail and dialog, in which case we can reconsider adding whiptail proper instead of it being provided by dialog.
