### ISSUE TITLE
Termux u0_a267

### ISSUE THREAD

**Issue by Y-afes** [termux/termux-packages#2911]
Friends termux login screen "u0_a267 @ localhost [~]" how can we remove this and what is it

**Comment by ExtremeNerd** [comment]
That is not to be asked here btw. Use termux@groups.io or irc for these kind of issues.

That is actually shell command prompt, referred to as PS1 environment variable, indicating you enter command in front of it.

PS1 is like any environment variable. For example you can change it to single dollar sign for neatness `PS1="$ ", upon login, or adding to profile script.
