### ISSUE TITLE
How does one cross compile on Clang?

### ISSUE THREAD

**Issue by Archangel45** [termux/termux-packages#2912]
You see, the only surefire way I could cross compile is

```
$ cp $PREFIX/arm-linux-androideabi/lib/* $PREFIX/lib
$ clang -m32 -L/system/lib -Wl,-rpath=/system/lib test.c
$ file a.out
a.out: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, not stripped
$ ./a.out
$
```

But you see it's takes a bit long to do that! How would you cross compile on Clang?

I looked at the issues that cross compile is possible but how is it done in command line? It's just hard to use it on Termux...

**Comment by projectextremum** [comment]
Can you specify the issue little more specifically? Are you trying compile binaries for termux on a desktop linux system or compiling binaries on termux itself? Where are those binaries expected to run?
Hint: `proot` will be useful in these cases, perhaps.

**Comment by Archangel45** [comment]
Well, in the app itself. I'm trying to compile scheme on termux, but it complains that it cannot find a configuration file.
