### ISSUE TITLE
Support for on device builds using QEMU:

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#2914]
I know it would be rather slower. However, what about providing an on-device build toolchain, using binfmt functionality provided by PRoot & qemu-user?

**Comment by xeffyr** [comment]
> Support for on device builds using QEMU:
> qemu-user

@ExtremeNerd We don't have QEMU ? It is provided here: https://github.com/termux/x11-packages/tree/master/packages/qemu-system-x86_64 - both system emulation (with SDL support) and user emulation. So why not to just unpack Ubuntu's amd64 archive and configure it for using with termux-package ?

**Comment by xeffyr** [comment]
Is someone still need this (`an on-device build toolchain, using binfmt functionality provided by PRoot & qemu-user`) ?

I can create something like [Neo-Oli/termux-ubuntu](https://github.com/Neo-Oli/termux-ubuntu), unpacked docker image used  by termux-packages & script to launch it with proot and qemu-user.
