### ISSUE TITLE
Discussion: containers;

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#2916]
May be little stupid idea. Still I think it is worth discussing.

User Namespaces support is added in newer kernels (>3.8 perhaps), and some containers are reportedly able to run without root on these.

One interesting thing is singularity, which does not need root rights and never even mentioned user namespaces feature. I think it may not even need that because many clusters are still running LTS versions of Linux kernel (singularity is mainly intended for hpc clusters).

runc seems interesting but needs user namespaces for rootless.

* Are android phones capable of seemlessly running containers for smaller applications?
* Is it practical, at least on rooted phones?

There will be few advantages like isolation and ability to use images on external storage.

**Comment by xeffyr** [comment]
> User Namespaces support is added in newer kernels (>3.8 perhaps),

My device has 3.18 kernel. It supports user namespaces but they are **permanently disabled** via kernel (stock) configuration at compilation time.

> runc seems interesting but needs user namespaces for rootless.

Runc can be easily built on device. I tried it but it requires cgroups and optionally user namepace - so custom kernel is needed anyway.

**Comment by miniBill** [comment]
Uses user ns https://www.sylabs.io/guides/3.0/admin-guide/security.html#can-i-install-singularity-as-a-user

**Comment by projectextremum** [comment]
@miniBill what about singularity on a rooted device?
