### ISSUE TITLE
nodejs: Exception thrown during bootstrapping Segmentation Fault

### ISSUE THREAD

**Issue by gardner** [termux/termux-packages#292]
Termux is pretty great. We ran into this issue on two different devices Samsung J2 and a Nexus 5. There was no more information logged in `adb logcat`.

**Steps to reproduce:**
1. Install Termux from Play Store
2. `apt-get update`
3. `apt-get install nodejs`
4. Attempt to run the repl via `node`

**Observed Behavior:**
```
Exception thrown during bootstrapping
Segmentation Fault
```

![screenshot_20160531-122105](https://cloud.githubusercontent.com/assets/787026/15661491/3665ed28-272b-11e6-9fda-9a1eadc7e4b3.png)
![screenshot_20160531-122059](https://cloud.githubusercontent.com/assets/787026/15661490/36653d88-272b-11e6-9275-676bbbd25245.png)

Thanks for reading.

**Comment by Jelenadria** [comment]
I'm facing the same issue in first installation but now has working fine since I try to `Apt-get Upgrade`

**Comment by fornwall** [comment]
@gardner Do you still have this problem after updating with `apt update && apt upgrade` on the affected devices?

**Comment by gardner** [comment]
Unable to reproduce this issue now.
I executed (out of order)
```
apt-get upgrade # this actually upgraded 7 packages
apt-get update
apt-get upgrade nodejs # nothing to upgrade here
node
```
And I got dropped into the node interactive REPL.

**Comment by gardner** [comment]
thanks for whatever change was made! please close this issue. :)

**Comment by fornwall** [comment]
@gardner Great! Closing the issue.
