### ISSUE TITLE
suggestion: termux's own package manager?

### ISSUE THREAD

**Issue by Bakaika** [termux/termux-packages#2920]
> Termux is an Android terminal emulator and Linux environment app that works directly with no rooting or setup required. A minimal base system is installed automatically - additional packages are available using the APT package manager.

It's true we can use APT, and the `pkg` command uses APT... however `pkg` is noticeably used more than `apt install ...` or `apt-get install ...`. What if termux was to have a `pkg` command, without an APT/dpkg backend? It'd be more efficient (`pkg install` is 1 function and 2 commands `add|i*) assert_not_root; apt update; apt install $@;;`) and save a few kB's.

I suppose having APT does make it easier for those who use Debian/Ubuntu to start using Termux, however Termux isn't Debian, nor Ubuntu. Termux is basically it's own linux distro.

**Comment by Grimler91** [comment]
Apt is great, well tested and can handle pretty much all imaginable complex dependency cases.

Trying to invite an alternative feels like a waste of time to me (and it would probably result in something that is slower and has more bugs than apt).

Switching to another package manager (yum, linuxbrew, ...) could be discussed but might be a bit complex so there should be some pretty great advantages

**Comment by xeffyr** [comment]
> It's true we can use APT, and the pkg command uses APT... however pkg is noticeably used more than apt install ... or apt-get install .... What if termux was to have a pkg command, without an APT/dpkg backend? It'd be more efficient (pkg install is 1 function and 2 commands add|i*) assert_not_root; apt update; apt install $@;;) and save a few kB's.

And have Nth amount of bugs and security related problems. **Why not to use already existing tools that are mature and considered to be stable ?**

Switching package manager is not easy task...

> however pkg is noticeably used more than apt install ...

We advertising `pkg` to make life easier for `newbies`. Others can use APT.

**Comment by Bakaika** [comment]
I agree APT is a great package manager.
It would be awesome to have others like yum, dnf, and pacman too.

Maybe busybox of package managers could be released, symlink whatever flavour you enjoy? lol.

**Comment by xeffyr** [comment]
> It would be awesome to have others like yum, dnf, and pacman too.
Maybe busybox of package managers could be released, symlink whatever flavour you enjoy? lol.

And how you will share package database between these PMs ?

They use a different format of storing package metadata (e.g. file & dep lists). It also not possible to make them using a unified format of metadata (generally possible but no one wants to rewrite a half of package manager).

**Comment by Bakaika** [comment]
:thinking: didn't think that far...
would be interesting to somehow unify them...

**Comment by xeffyr** [comment]
> would be interesting to somehow unify them...

Unifying will require to **completely rewrite** parts that acutally handle package metadata parsing and storing on FS. This actually suffers from same problems as creation of own package manager.

**Comment by Bakaika** [comment]
Maybe convert them to a preexisting system?

**Comment by fornwall** [comment]
It's unlikely that we would implement a custom package manager. I have been looking a bit at [apkt, the package manager from Alpine Linux](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management) due to its simplicity, small size and speed, but it's just on the experimental phase.

Anyway, we do not need a specific issue for the general discussion until we have a concrete proposal for an eventual change.
