### ISSUE TITLE
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "r_mem_memzero" referenced by "libr_hash.so"

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#2923]
_From @Cvar1984 on October 2, 2018 6:48_

$ export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
But return same error.

$ env
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
LANG=en_US.UTF-8
PREFIX=/data/data/com.termux/files/usr                                  PWD=/data/data/com.termux/files/home
HOME=/data/data/com.termux/files/home
TMPDIR=/data/data/com.termux/files/usr/tmp
SHELL=/data/data/com.termux/files/usr/bin/bash
TERM=xterm-256color
SHLVL=1                                                                 ANDROID_ROOT=/system
ANDROID_DATA=/data
EXTERNAL_STORAGE=/storage/emulated/0
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
_=/data/data/com.termux/files/usr/bin/env
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.49-g987e9cc #1 SMP PREEMPT Tue Oct 27 18:35:37 IST 2015 armv7l Android
Termux-packages arch:                                                   arm                                                                     Android version:
5.1.1                                                                   Device manufacturer:
HUAWEI
Device model:
HUAWEI SCL-U31

_Copied from original issue: termux/termux-app#856_

**Comment by fornwall** [comment]
_From @Grimler91 on October 2, 2018 7:54_

What are you running to get this error? I guess it's related to R from its-pointless repo so you should probably open an issue there instead

**Comment by fornwall** [comment]
_From @its-pointless on October 2, 2018 8:13_

That symbol is in libr_util.so.2.9.0 which is part of radare2.

**Comment by fornwall** [comment]
_From @Grimler91 on October 2, 2018 8:16_

Ah, right, thanks

**Comment by fornwall** [comment]
@Cvar1984 So, do you get this issue when trying to run the `r2` program direclty, or how do you trigger it?

**Comment by fornwall** [comment]
Can it be the dlopen() issue fixed in Android 6? https://github.com/android-ndk/ndk/issues/201

**Comment by Cvar1984** [comment]
> @Cvar1984 So, do you get this issue when trying to run the `r2` program direclty, or how do you trigger it?

yes, i try run radare2

**Comment by its-pointless** [comment]
fornwall yeah thats the issue.

**Comment by its-pointless** [comment]
I have pr ready that fixes this

**Comment by xeffyr** [comment]
Seems like fixed by https://github.com/termux/termux-packages/pull/3492.
