### ISSUE TITLE
Termux-extras getting 404

### ISSUE THREAD

**Issue by Aerex** [termux/termux-packages#2927]
So i tried to install a package this morning and got this error

```
[INS~] pkg install termux-api                                                     :|
Hit:1 https://its-pointless.github.io/files termux InRelease
Hit:2 https://termux.net stable InRelease
Hit:3 https://grimler.se root InRelease
Ign:4 https://xeffyr.ml/termux extra InRelease
Err:5 https://xeffyr.ml/termux extra Release
  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xeffyr.ml:443
Reading package lists... Done
E: The repository 'https://xeffyr.ml/termux extra Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
[INS][~]
```

I checked the [github repository](https://github.com/xeffyr/termux-extra-packages) and I received 404. Is anyone getting this issue ?

**Comment by xeffyr** [comment]
> Termux-extras getting 404

Usually, 404 means `page not found`. So remove lines that are not working.

***

If you seeking for x11 packages - do `pkg install x11-repo` and everything will be okay.

**Comment by Aerex** [comment]
Thanks. I was wondering why the repository disappeared. Was it moved ?

**Comment by xeffyr** [comment]
> Was it moved ?

X11 packages was splitted out and moved here: https://github.com/termux/x11-packages - they are now official. Repository can be enabled by doing `pkg install x11-repo`.

Everything else was either moved or will be to `https://github.com/termux/termux-packages` via PRs or to source-based repo `https://github.com/xeffyr/termux-makepkg` (currently in dev. state).
