### ISSUE TITLE
beautifulsoup

### ISSUE THREAD

**Issue by empt1xo** [termux/termux-packages#2933]
hey, 

so I tried to install "beautifulsoup" witch is a Python package for parsing HTML and XML documents, and i got this error 

```
pip install beautifulsoup
Collecting beautifulsoup
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):                                             File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-gtdbrmlr/beautifulsoup/setup.py", line 22
        print "Unit tests have failed!"                                                                            ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?

    ----------------------------------------                                 Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-gtdbrmlr/beautifulsoup/
$
```
here's some information about the Android device im running,

  android-5d244b67d601f5a8
  OS: Android 7.1.2
  Device: SHV-E300S (jalteskt)
  ROM: lineage_jalteskt-userdebug 7.1.2
  Kernel: armv7l Linux 3.4.67-g9d55dec
  CPU: ARMv7 Processor rev 2 (v7l)

so is there any other way to get beautifulsoup ?

**Comment by xeffyr** [comment]
@empt1xo I suggest you to learn difference between python 2 & 3 versions and then read error message again.

You are installing beautifulsoup for **python2** with pip from python v3 package.

So do either:
```
pip2 install beautifulsoup
```
or
```
pip3 install beautifulsoup4
```

See documentation for more info: https://www.crummy.com/software/BeautifulSoup/

**Comment by empt1xo** [comment]
lol I'm drunk
