### ISSUE TITLE
node not working (5.1 lollipop)

### ISSUE THREAD

**Issue by hyperpallium** [termux/termux-packages#2934]
It installs OK, version 10.11.0
```
$ apt install nodejs
```
But nothing works, even `node -v` gives no output.

```
$ node -v
$
```

**Comment by hyperpallium** [comment]
I'm not seeing a `nodejs-stable` in the repository (there are 4 variants, all marked "stable", but not in their name e.g. `nodejs/stable 10.11.0 arm` is the one I tried)

```
$ apt search nodejs
Sorting... Done
Full Text Search... Done
nodejs/stable 10.11.0 arm
  Platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications

nodejs-dev/stable 10.11.0 arm
  Development files for nodejs

nodejs-lts/stable 8.12.0 arm
  Platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications

nodejs-lts-dev/stable 8.12.0 arm
  Development files for nodejs-lts

```



uh... maybe `lts` stands for `long term support`? I just tried `node-lts`, but also not working, in the same way.

**Comment by Grimler91** [comment]
Ah yes, I meant the -lts, sorry. Alright,  and you're on arm
