### ISSUE TITLE
dpkg error: not a regular file

### ISSUE THREAD

**Issue by b3nsh4** [termux/termux-packages#2939]
Because we have a 'no-engine' configuration in *openssl* , I used the openssl files given by @xeffyr . But while trying to install, it says "not regular file".
Files: https://github.com/termux/termux-packages/issues/2847#issuecomment-423773291

![](https://i.imgur.com/CoBn89g.jpg)

**Comment by Grimler91** [comment]
What's the output of `termux-info`?

**Comment by bensh4** [comment]
@Grimler91 2 outputs are producing at the time i checked *termux-info*
1- Termux-api has stopped

![](https://i.imgur.com/2Nn1YhH.jpg)

2- 
```
@localhost ➜ ~  termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.67 #1 SMP PREEMPT Sat Dec 13 20:28:37 CST 2014 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.2
```
![](https://i.imgur.com/v6KuQtI.jpg)

**Comment by Grimler91** [comment]
Try re-downloading the .deb and see if it's still the same problem

**Comment by bensh4** [comment]
@Grimler91 This time i downloaded the files again and installed within $HOME and it's installed :-D
Still the *Termux-api* problem persists.

![](https://i.imgur.com/kMpJSQ1.png)
