### ISSUE TITLE
failing to build in docker on os x with msg about mmap

### ISSUE THREAD

**Issue by ginabythebay** [termux/termux-packages#294]
I'm at commit  eb5ac24 (current head of master).  I get a failure building libandroid-support, using docker in os x.  I didn't see this problem previously.

```
$ ./scripts/run-docker.sh
Running container from image 'termux/package-builder'...
root@c6fd33ea3d84:~/termux-packages# ./clean-rebuild-all.sh
rm: cannot remove '/root/termux': Device or resource busy
+ set -e -u -o pipefail
++ dirname build-all.sh
+ BUILDSCRIPT=./build-package.sh
+ BUILDORDER_FILE=/root/termux/_buildall/buildorder.txt
+ BUILDSTATUS_FILE=/root/termux/_buildall/buildstatus.txt
+ '[' -e /root/termux/_buildall/buildorder.txt ']'
+ rm -Rf '/root/termux/*' /data/data /root/termux/_buildall
+ mkdir -p /root/termux/_buildall
+ ./scripts/buildorder.py
+ '[' -e /root/termux/_buildall/buildstatus.txt ']'
+ exec
++ tee -a /root/termux/_buildall/ALL.out
+ exec
++ tee -a /root/termux/_buildall/ALL.err
Building libandroid-support... + trap 'echo failure; echo See: $HOME/termux/_buildall/${package}.err' ERR
++ cat /root/termux/_buildall/buildorder.txt
+ for package in '`cat $BUILDORDER_FILE`'
+ '[' -e /root/termux/_buildall/buildstatus.txt ']'
+ echo -n 'Building libandroid-support... '
++ date +%s
+ BUILD_START=1464716277
+ bash -x ./build-package.sh libandroid-support
++ echo failure
++ echo See: /root/termux/_buildall/libandroid-support.err
failure
See: /root/termux/_buildall/libandroid-support.err
root@c6fd33ea3d84:~/termux-packages# tail -20 /root/termux/_buildall/libandroid-support.err
+ grep -q -E -v '^#\! ?\/system'
+ grep -E '^#\!.*\/bin\/.*'
+ head -c 100 ./include/libintl.h
+ for file in '`find -L . -type f`'
+ grep -q -E -v '^#\! ?\/system'
+ grep -E '^#\!.*\/bin\/.*'
+ head -c 100 ./lib/libandroid-support.so
+ for file in '`find -L . -type f`'
+ grep -q -E -v '^#\! ?\/system'
+ grep -E '^#\!.*\/bin\/.*'
+ head -c 100 ./lib/libiconv.so
+ for file in '`find -L . -type f`'
+ grep -q -E -v '^#\! ?\/system'
+ grep -E '^#\!.*\/bin\/.*'
+ head -c 100 ./lib/libintl.so
+ set -e -o pipefail
+ '[' '' = '' ']'
+ xargs -0 /root/termux/_cache/termux-elf-cleaner
+ find . -type f -print0
mmap(): Invalid argument
```

**Comment by fornwall** [comment]
Hm, it seems that docker running on OS X does not support `mmap` on a mounted host directory - see https://www.virtualbox.org/ticket/819 and https://issues.apache.org/jira/browse/CASSANDRA-9635.

I wonder if this is fixed by the Mac beta of OS X?

**Comment by ginabythebay** [comment]
I am starting to think that contributing to termux on a mac isn't the right way forward currently.

I may be getting a linux desktop which would let me work on this.

**Comment by fornwall** [comment]
@ginabythebay I've updated the build scripts and docker setup a bit, and this issue should be fixed now.

- The output folder of built .deb files is now `debs/` by default, so that folder is shared by the host and the container.
- The build folder (now changed to `$HOME/.termux-build/`, from the previous `$HOME/termux/`) is no longer mounted by the container, which fixes this issue.
- `scripts/run-docker.sh` now re-use a single docker container instead of creating new ones.
- `scripts/run-docker.sh` can now take a command to execute directly, so e.g. `./scripts/run-docker.sh ./build-package.sh -a i686 dash` will build
