### ISSUE TITLE
python command should be python 2 (see PEP 394)

### ISSUE THREAD

**Issue by funkyHat** [termux/termux-packages#295]
According to https://www.python.org/dev/peps/pep-0394/ the python command should not refer to python3.

I realise this may be slightly awkward for new users as python2 is not installed. Perhaps as a compromise could be to use update-alternatives if you're not happy with a wholesale switch?

**Comment by divinites** [comment]
Actually it depends on distributions. e.g. in the recent Archlinux, python refers to python3, while python2 refers to python2.

**Comment by funkyHat** [comment]
@divinites that's correct, but official policy from the Python project is that `python` should refer to Python 2 only. If you read the opening paragraphs of the PEP I linked above you'll see they explicitly mention Arch linux there.

**Comment by yamsu** [comment]
Hi, I agree with funkyHut. A lot of python applications still need to be updated for python3. Termux should attempt to resemble a general configuration that is prevalent on desktop linux distros.

**Comment by fornwall** [comment]
I'm siding with the Arch Linux approach here.

Several of Termux users are new to Linux and the command line, and as a general rule we want to avoid having them care about historical baggage. If someone starts using `python` and then gradually learn more, it's simply the best for them to be using the latest version by default.

Hopefully PEP 394 can be superseded soon - in all cases this will be less of a problem over time, as python3 adoptions speeds up.

**Comment by funkyHat** [comment]
*if* PEP 394 is superseded, it won't be until at least 2020.
By 2020 there's a good chance we'll have Python 4, which I think makes it even less likely that PEP 394 will be changed (I expect it will be extended to cover `python4` executables being called `python4` instead).

It's a shame that you've decided to go with the approach which caused PEP 394 to be written in the first place, as it was written for a reason.
I'm also (given the above) not sold on the argument that some of Termux's users are new to Linux & command line: python 2 still has 4 years of official support, so it's not "historical baggage" and if those same users start using Debian, Ubuntu, Fedora, Gentoo, er... pretty much !(Arch) desktop distro, they are going to get hit by this then, instead of learning it from the start :)

I fully agree that new python users should be using Python 3, but given that you're providing python 3 in the default install & not python 2, I can only see a very slight annoyance the *first* time a new python user tries to run `python` and gets told "command not found" (probably with a note that maybe they meant `python3`).

Finally (and apologies for the wall of text), this has the potential to cause problems for people wanting to run python scripts they've obtained from elsewhere, which by-and-large will be following the PEP. Of course for you or I just fixing the hashbang is trivial, but we're talking about beginner users here :)

**Comment by divinites** [comment]
I do not think that this will cause serious problems to run python scripts for beginners. 

A python scripts is just a plain text file which can be interpreted by python2 or python3 (or both!). You can always run python2 script.py for python2-compatible scripts and python3 script.py for python3-compatible scripts. The shebang will be overrided anyway.
