### ISSUE TITLE
I am unable to run apache2 in termux due to some errors which I am unable to fix

### ISSUE THREAD

**Issue by HussainiMagaji** [termux/termux-packages#2953]

**Comment by Grimler91** [comment]
We can't possibly know which error you're running into or how to fix it if you don't provide any information..

**Comment by xeffyr** [comment]
@jusdepatate Port 80 is unusable without root, 8080 can be changed to something different. It is easy to edit configuration file, isn't it ?

> Most of android phone blocks port 80 and 8080

Hmm, in Android source code I never seen iptables configuration that blocks port 80 or 8080. I also own some Android devices from different brands but no one of them has block for 80, 8080 or any other ports. There just no reason to block it, however some vendors may think differently...

**Comment by jusdepatate** [comment]
> Hmm, in Android source code I never seen iptables configuration that blocks port 80 or 8080. I also own some Android devices from different brands but no one of them has block for 80, 8080 or any other ports. There just no reason to block it, however some vendors may think differently...


Oh ?
I have 2 android devices and both block port 80 when i try to open an http server 🤔 
(One Asus tablet and one Huawei phone, both are not rooted, i cant root them :/)

**Comment by xeffyr** [comment]
Ports less than 1024 (e.g. 80 or 443) are privileged and you can't use them without root even on desktop Linux distribution.

**Comment by RishabhRyber** [comment]
Even I was facing same problem my ports 80 and 8080 were not accessible.
So I changed it from httpd.conf file:
Listen 0.0.0.0:12345
0.0.0.0 to make it accessible from any IP address
and it's working now
