### ISSUE TITLE
Package Request: vim-plug

### ISSUE THREAD

**Issue by nstgc** [termux/termux-packages#2956]
Rather than ask for specific plugins (notably the vim-latexsuite and vim-julia) I'd appreciate it if someone could package vim-plug, or some other vim plugin manager.

**Comment by Bakaika** [comment]
to instsall vim-plug you can simply do the standard unix installation in their readme, `curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`
i use vim-plug myself.
