### ISSUE TITLE
error: command 'arm-linux-androideabi-clang' failed with exit status 1

### ISSUE THREAD

**Issue by dklk7** [termux/termux-packages#2959]
I'm trying to install mechanicalsoup but I can not because every time I try it I get that error ...
![screenshot_20181015-232630](https://user-images.githubusercontent.com/44187030/46992851-d11ed080-d0d1-11e8-9bf3-d854292db0cc.png)
(url)

**Comment by its-pointless** [comment]
install libxml2-dev
