### ISSUE TITLE
Can't remove and recreate a socket created by a package.

### ISSUE THREAD

**Issue by nstgc** [termux/termux-packages#2961]
One of the packages I installed created a socket, which all well and good. The problems is that I later decided to move my home directory to my SD card. I then tried uninstalling the package (keybase) and installing it again, but this didn't work. I have also asked this question on Stack Exchange: https://android.stackexchange.com/questions/202771/move-a-socket-installed-in-termux

**Comment by xeffyr** [comment]
@nstgc Usually, it should be possible to remove socket in this way:
```
chmod 700 /dir
chmod 600 /dir/socket_file
rm -f /dir/socket_file
```
\- just fixing permissions for file & dir and then deleting it in usual way.

> The problems is that I later decided to move my home directory to my SD card.

Before doing this, you should know this: **symlinks, sockets, pipes and other special files can't be created on /sdcard - this is a limitation of filesystem**. Binary executables can't be executed on /sdcard too.
So, think twice before doing something that may have side effects.

**Comment by nstgc** [comment]
> > The problems is that I later decided to move my home directory to my SD card.
> 
> Before doing this, you should know this: **symlinks, sockets, pipes and other special files can't be created on /sdcard - this is a limitation of filesystem**. Binary executables can't be executed on /sdcard too.
> So, think twice before doing something that may have side effects.

Ah! I didn't know about that limitation (nor any others). To verify, you are saying what I am trying to do is not possible due to technical limitations of the storage medium's file system, correct? Furthermore, I will need to undo the changes that I made (fortunately I know better than to delete anything).

**Comment by xeffyr** [comment]
@nstgc You can store only **regular files** on /sdcard. So, your home directory should be located in standard place while some files (e.g. text, images, archives) can be stored on /sdcard.
