### ISSUE TITLE
install pyaudio returns error code 1

### ISSUE THREAD

**Issue by IMpIUVNvBk** [termux/termux-packages#2962]
Hi,
my android is 8.1

`$ pip3 install pyaudio
Collecting pyaudio
  Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Building wheels for collected packages: pyaudio
  Running setup.py bdist_wheel for pyaudio ... error
  Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-5s_xs9y6/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /data/data/com.termux/files/usr/tmp/pip-wheel-obtv_zyg --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv8l-3.6
  copying src/pyaudio.py -> build/lib.linux-armv8l-3.6
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-armv8l-3.6
  creating build/temp.linux-armv8l-3.6/src
  arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -I/data/data/com.termux/files/usr/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-armv8l-3.6/src/_portaudiomodule.o
  src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found
  #include "portaudio.h"
           ^~~~~~~~~~~~~
  1 error generated.
  error: command 'arm-linux-androideabi-clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio
  Running setup.py install for pyaudio ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-5s_xs9y6/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-5bw8i90a/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv8l-3.6
    copying src/pyaudio.py -> build/lib.linux-armv8l-3.6
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-armv8l-3.6
    creating build/temp.linux-armv8l-3.6/src
    arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -I/data/data/com.termux/files/usr/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-armv8l-3.6/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found
    #include "portaudio.h"
             ^~~~~~~~~~~~~
    1 error generated.
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-5s_xs9y6/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-5bw8i90a/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-5s_xs9y6/pyaudio/`

**Comment by its-pointless** [comment]
Port audio is not available in main repo. It is available in mine.

**Comment by IMpIUVNvBk** [comment]
> Port audio is not available in main repo. It is available in mine.

can u tell me how should i install this ?

**Comment by its-pointless** [comment]
https://wiki.termux.com/wiki/Package_Management

**Comment by IMpIUVNvBk** [comment]
> https://wiki.termux.com/wiki/Package_Management

sry , i don't know anything about this.
can u give me commands ?

**Comment by xeffyr** [comment]
> sry , i don't know anything about this.

You can't read ? On page https://wiki.termux.com/wiki/Package_Management everything that you need:
```
pkg install wget
$PREFIX/bin/wget https://its-pointless.github.io/setup-pointless-repo.sh
bash setup-pointless-repo.sh
```

**Comment by xeffyr** [comment]
`pkg install portaudio portaudio-dev`

**Comment by IMpIUVNvBk** [comment]
sorry, 1 more question
how can i give microphone Permission to termux ?

**Comment by Grimler91** [comment]
> sorry, 1 more question
> how can i give microphone Permission to termux ?

You can record stuff through termux-api.
Search github for `microphone` and you'll find older PRs/issues discussing this.

**Comment by IMpIUVNvBk** [comment]
i installed termux-api. and i gave permission to termux-api.
Why is my output so?
`>>> import speech_recognition as sr
>>> sr.Microphone.list_microphone_names()
['OpenSL ES Output', 'Monitor of OpenSL ES Output']`

**Comment by IMpIUVNvBk** [comment]
@Grimler91 could u please reopen this issue?

**Comment by paradoxnafi** [comment]
I had to install cmake and python-dev 
`pkg install cmake python-dev wget`
`wget https://its-pointless.github.io/setup-pointless-repo.sh`
`bash setup-pointless-repo.sh`
`pkg install portaudio portaudio-dev`
`pip3 install pyaudio`

This is the whole process

**Comment by vinay2007** [comment]
pkg install cmake python-dev wget
wget https://its-pointless.github.io/setup-pointless-repo.sh
bash setup-pointless-repo.sh
pkg install portaudio portaudio-dev
pip3 install pyaudio
 It's not working for me
Installing collected packages: pyaudio                      Running setup.py install for pyaudio ... error          ERROR: Command errored out with exit status 1:           command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-7oe5lx19/pyaudio_b88410b32c954dc8842a3b8f42b1e841/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-7oe5lx19/pyaudio_b88410b32c954dc8842a3b8f42b1e841/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-5mbewfnl/install-record.txt --single-version-externally-managed --compile --install-headers /data/data/com.termux/files/usr/include/python3.9/pyaudio                                                              cwd: /data/data/com.termux/files/usr/tmp/pip-install-7oe5lx19/pyaudio_b88410b32c954dc8842a3b8f42b1e841/    Complete output (16 lines):                             running install                                         running build                                           running build_py                                        creating build                                          creating build/lib.linux-aarch64-3.9                    copying src/pyaudio.py -> build/lib.linux-aarch64-3.9                                                           running build_ext                                       building '_portaudio' extension                         creating build/temp.linux-aarch64-3.9                   creating build/temp.linux-aarch64-3.9/src               aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.9 -c src/_portaudiomodule.c -o build/temp.linux-aarch64-3.9/src/_portaudiomodule.o                             src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found                                         #include "portaudio.h"                                           ^~~~~~~~~~~~~                                  1 error generated.                                      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1        ----------------------------------------            ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-7oe5lx19/pyaudio_b88410b32c954dc8842a3b8f42b1e841/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-7oe5lx19/pyaudio_b88410b32c954dc8842a3b8f42b1e841/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-5mbewfnl/install-record.txt --single-version-externally-managed --compile --install-headers /data/data/com.termux/files/usr/include/python3.9/pyaudio Check the logs for full command output.

**Comment by vinay2007** [comment]
Not working

**Comment by mAHeR-c** [comment]
Hi
