### ISSUE TITLE
Problemas com salvamento de pacotes/ferramentas 

### ISSUE THREAD

**Issue by Anomnubis** [termux/termux-packages#2963]
Eu usava muito o termux so que desinstalei e dps eu voltei a usalo so que estou com um problema toda vez que eu vou baixar uma ferramenta/pacote aparece a seguinte palavra depois da instalação: "Unable to locate package" ai o pacote so funciona naquela sessão e em outras tenho que reinstalalo por favor me ajudem :(

**Comment by Grimler91** [comment]
Google translate tells me you can't install some package that you could install before. Might be because you were subscribe to some community repo before: https://wiki.termux.com/wiki/Package_Management#Community_repositories

Closing since Spanish isn't the language we use here
