### ISSUE TITLE
termux-api dependency on bash

### ISSUE THREAD

**Issue by gafusss** [termux/termux-packages#2967]
See termux/termux-api-package#34, termux/termux-api-package#35

Some script in termux-api are bash scripts (e.g. termux-dialog). termux-api package does not depend on bash package, therefore apt allows to safely remove the bash pacakge, however that makes those bash scripts unsusable.

Could you please either mark termux-api package as dependent on bash, or merge the PR mentioned above?

P.S. Had to put this issue here since this repository is much more active than termux-api-package

**Comment by xeffyr** [comment]
PR is opened.

Interesting, why someone would uninstall bash ?

**Comment by gafusss** [comment]
I actually don't even know why it is in the bootstrap, since it is not "essential", and there is (essential) dash already.

I stumbled upon this issue because I was using custom built packages, having only "essential" and the ones I actually needed.

**Comment by gafusss** [comment]
@xeffyr Could you please look into termux/termux-api-package#35, and either close or merge it?

**Comment by xeffyr** [comment]
@gafusss No, I can't merge/close PRs here.
