### ISSUE TITLE
not able to run .deb file

### ISSUE THREAD

**Issue by pubsubhubbusb** [termux/termux-packages#2970]
Unsupported file ./settoolkit_7.7.4_all.deb given on commandline

**Comment by xeffyr** [comment]
*.deb files are archives, they are not runnable or executable. I even don't know where you get this settoolkit, we don't have it in repository so this actually not Termux's issue.

**Comment by pubsubhubbusb** [comment]
first time I installed it in my termux with  apt install ./ ./settoolkit_7.7.4_all.deb

but when am trying install to this in my another device it showing this error 
Unsupported file ./settoolkit_7.7.4_all.deb given on command line

**Comment by xeffyr** [comment]
You can't do ` apt install ./settoolkit_7.7.4_all.deb`. Instead do this: `dpkg -i settoolkit_7.7.4_all.deb`.

More information here: https://wiki.termux.com/wiki/Package_Management#Working_with_packages
