### ISSUE TITLE
termux:API microphone input problem

### ISSUE THREAD

**Issue by IMpIUVNvBk** [termux/termux-packages#2976]
hi,
i installed termux-api. and i gave permission to termux-api.
Why is my output so?

import speech_recognition as sr

sr.Microphone.list_microphone_names()

['OpenSL ES Output', 'Monitor of OpenSL ES Output']

**Comment by xeffyr** [comment]
> i installed termux-api. and i gave permission to termux-api.

> import speech_recognition as sr

@IMpIUVNvBk You gave permission to termux-api, then use termux-api. Termux:API does not have any relation to this python module `import speech_recognition as sr`.

**Comment by IMpIUVNvBk** [comment]
> Termux:API does not have any relation to this python module `import speech_recognition as sr`.

so what is related to this module?
how can i use microphone in python ?

**Comment by Epictek** [comment]
You would have to record the audio to a file and then process it or use the speech recognition input
