### ISSUE TITLE
Does redline (java smallttalk) work in Oreo?

### ISSUE THREAD

**Issue by hyperpallium** [termux/termux-packages#2977]
As a potential package. Sorry if it's not appropriate to ask here...
I saw it here https://news.ycombinator.com/item?id=18270524

The [getting started instructions](http://www.redline.st/discover/getting-started.html)
 need a `dex` step, and `dalvikvm` imstead of `java`:

```
>wget https://github.com/redline-smalltalk/redline-smalltalk.github.com/raw/master/assets/redline-deploy.zip
>unzip redline-deploy.zip -d redline
>cd redline
>java -jar redline-0.6-SNAPSHOT.jar st.redline.script.HelloWorld
```
The needed `dex`:
```
$ dx --dex --output=redline.dex redline-0.6-SNAPSHOT.jar
Uncaught translation error: dx.dx.cf.code.SimException: ERROR in st.redline.core.PrimObject.throwingAnswer:(Ljava/lang/Object;Ljava/lang/String;)Lst/redline/core/LambdaBlock;: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
1 error; aborting
```
If anyone is interested in smalltalk, I wonder if this will work in Oreo?  Orea has the right api level (with `invokedynamic`), but there might be other problems..

**Comment by xeffyr** [comment]
DX needs option `--min-sdk-version=26` set.

**Comment by hyperpallium** [comment]
@xeffyr thanks for trying this! (BTW my post disappeared yesterday, I guess b/c the github outage)

```Bad method handle type 7 ```

Seems to be for `invokedynamic`, so it might just not be fully supported in Oreo yet...? Or, might dalvikvm/art needs an explicit flag, to expect java 8?

From https://stackoverflow.com/a/50268951/4930344

```kInvokeDirect      = 0x0007,  // an invoker for a direct (special) method.```

And a comment on the other answer there says a fix was to specify java 1.8

**Comment by xeffyr** [comment]
> Or, might dalvikvm/art needs an explicit flag, to expect java 8?

No, dalvikvm doesn't have flags to specify java version.

> and we need android 9

I can try to launch it on Android Pie AVD.

**Comment by hyperpallium** [comment]
@xeffyr thanks again for testing! It does sound like a problem with the dex, as you said.

**Comment by hyperpallium** [comment]
@xeffyr did you see my edit? The missing "class" turned out to be in smalltalk.

**Comment by TheBrokenRail** [comment]
Try dexing with D8.

**Comment by xeffyr** [comment]
Hope gnu smalltalk will be enough. How to get it via `apt` is in https://github.com/termux/unstable-packages/issues/29#issuecomment-459133403.
