### ISSUE TITLE
Do not mark `bash` as essential.

### ISSUE THREAD

**Issue by pthfdr-42** [termux/termux-packages#2981]
Firstly, it was not forced in the previous versions.
Secondly, there is already `dash`, and Android has `mksh` as a default shell.
Why do you force a bloated shell onto every Termux user?

**Comment by xeffyr** [comment]
Many things are relying on bash. Bash also is small package ~1.5 mb.

If you don't like bash, use `chsh` to set default shell.

**Comment by pthfdr-42** [comment]
There is another solution: Make everything POSIX-compilant, so you can use any shell.

**Comment by xeffyr** [comment]
What should be POSIX compliant ? You mean that we have to review and patch if needed any package to force use $PREFIX/bin/sh ?

That what you are requesting called `customization` and shouldn't be done widely.

Bash is a shell no. 1 in all major Linux distributions. In Debian it marked as essential for obvious reasons same as in Termux.

Solutions for you:
1. If you afraid bash - then you can throw it away with `dpkg --purge --force-all bash`.

2. You always can replace it without uninstalling package:
```
ln -sf /system/bin/mksh $PREFIX/bin/bash
```

**Comment by xeffyr** [comment]
If you need a posix compliant shell, then do `chsh -s dash`.

***

Seems that topic should be called `Holy war between POSIX and non-POSIX shells` actually.

**Comment by gafusss** [comment]
<sup>You could also make packages that require bash "depend" on it (which they should). No holy war here, just a thought :)</sup>

**Comment by tomty89** [comment]
That's how it's done in Arch AFAIK

**Comment by fornwall** [comment]
While I understand the desire to avoid bash, I think the benefits of always having bash available in Termux (for e.g. online tutorials, or helping users with support issues) outweighs the drawback.
