### ISSUE TITLE
After Upgrading to Python 3.7.1 All python modules & libs are deleted

### ISSUE THREAD

**Issue by T4P4N** [termux/termux-packages#2986]
Before Upgrade:
Package            Version
------------------ ---------
backcall           0.1.0
beautifulsoup4     4.6.0
bleach             2.1.3
certifi            2018.4.16
chardet            3.0.4
cheat              2.2.3
decorator          4.3.0
Django             2.1.1
docopt             0.6.2
elpy               1.22.0
entrypoints        0.2.3
flake8             3.5.0
fuzzywuzzy         0.17.0
html5lib           1.0.1
idna               2.7
ipykernel          4.8.2
ipython            6.4.0
ipython-genutils   0.2.0
ipywidgets         7.2.1
jedi               0.12.1
Jinja2             2.10
jsonschema         2.6.0
jupyter            1.0.0
jupyter-client     5.2.3
jupyter-console    5.2.0
jupyter-core       4.4.0
MarkupSafe         1.0
mccabe             0.6.1
mistune            0.8.3
nbconvert          5.3.1
nbformat           4.4.0
notebook           5.5.0
pandocfilters      1.4.2
parso              0.3.0
pexpect            4.6.0
pickleshare        0.7.4
pip                18.0
pluginbase         0.7
prettytable        0.7.2
prompt-toolkit     1.0.15
ptyprocess         0.6.0
pycodestyle        2.3.1
pyflakes           1.6.0
Pygments           2.2.0
python-dateutil    2.7.3
python-Levenshtein 0.12.0
pytz               2018.5
pyzmq              17.0.0
qtconsole          4.3.1
requests           2.19.1
rope               0.10.7
Send2Trash         1.5.0
setuptools         39.0.1
simplegeneric      0.8.1
six                1.11.0
terminado          0.8.1
testpath           0.3.1
tld                0.9.1
tornado            5.1
traitlets          4.3.2
urllib3            1.23
wcwidth            0.1.7
webencodings       0.5.1
widgetsnbextension 3.2.1
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
After Upgrade :
Only setup-tools is there.
Is this a Bug in pip or in python itself?

**Comment by Grimler91** [comment]
Upgrading from which version? 

Upgrading from 3.6 to 3.7 means that you need to reinstall the modules. I'm pretty sure it's the same on normal desktop linux, installed modules are installed to `/usr/lib/python#.#/site-packages`, so with python 3.6 you have `/usr/lib/python3.6/site-packages` while 3.7 installs to `/usr/lib/python3.7/site-packages`

**Comment by T4P4N** [comment]
Thanks, Yes, i'm upgrading from python 3.6..
:)
