### ISSUE TITLE
Package Request: ddclient

### ISSUE THREAD

**Issue by sajaysurya** [termux/termux-packages#2987]
Please include ddclient package to update dynamic dns entries.

**Comment by xeffyr** [comment]
ddclient requires `Data/Validate/IP.pm` but we don't packaging perl modules.

**Comment by bmvaghera** [comment]
Plz solv this 
$ sh build-package.sh
build-package.sh: 4: set: Illegal option -o pipefail
$

**Comment by edaubert** [comment]
https://wiki.termux.com/wiki/Perl

**Comment by edaubert** [comment]
Ok I have almost an available package but I do not find the way to test it on my phone.

I am pretty sure I am missing the link I need so could you point me to the right direction ?
I guess I need to create a repository and then add it on my phone. Then by including my ddclient package on it I will be able to install it.

Sorry if the question is really dumb though...

By the way, my `build.sh` looks like this:
```
TERMUX_PKG_HOMEPAGE=https://sourceforge.net/projects/ddclient/
TERMUX_PKG_DESCRIPTION="A Perl client to manage Dynamic DNS Network Services"
TERMUX_PKG_LICENSE="GPLv2"
TERMUX_PKG_VERSION=3.9.0
TERMUX_PKG_SRCURL=https://freefr.dl.sourceforge.net/project/ddclient/ddclient/ddclient-${TERMUX_PKG_VERSION}/ddclient-${TERMUX_PKG_VERSION}.zip
TERMUX_PKG_SHA256=b4bc907eaadb1f30ccef8a11d92a30080ee21338cde89bf76b7d3d20a4499830
TERMUX_PKG_DEPENDS="make, perl"

termux_step_post_make_install () {
  export PERL_MM_USE_DEFAULT=1
  cpan Data::Validate::IP
}
```

**Comment by xeffyr** [comment]
>```
>termux_step_post_make_install () {
>  export PERL_MM_USE_DEFAULT=1
>  cpan Data::Validate::IP
>}
>```

And where `Data::Validate::IP` will be installed ?
We don't have support for perl modules. Also, packaging multiple things into one package is **bad**.

**Comment by edaubert** [comment]
Ok my bad.

**Comment by xeffyr** [comment]
Can be installed with: 
```ShellSession
curl -o $PREFIX/bin/ddclient https://raw.githubusercontent.com/ddclient/ddclient/master/ddclient
sed -i "s@/etc/ddclient/@$PREFIX/etc/ddclient/@g" $PREFIX/bin/ddclient
sed -i "s@/var/cache/ddclient/@/@g" $PREFIX/bin/ddclient
sed -i "s@/tmp/@$PREFIX/tmp/@g" $PREFIX/bin/ddclient
mkdir -p $PREFIX/var/cache/ddclient
mkdir -p $PREFIX/etc/ddclient
cpan Data::Validate::IP
```

Then just create configuration file in `$PREFIX/etc/ddclient` and it should work.
