### ISSUE TITLE
Restore Packages from list file

### ISSUE THREAD

**Issue by isrgish** [termux/termux-packages#2988]
In the wiki there is instructions how to restore packages from a list file.

When I try to do this it stops with an error that some of the packages  it cant locate.

How can I get it to ignore those packages and install the ones it can locate.

Thank You

**Comment by xeffyr** [comment]
@isrgish Do you used this:
```
# generate installed package list
dpkg --get-selections | cut -f1 > mypackages.txt

# install packages
xargs -0 apt install -y < <(tr \\n \\0 < mypackages.txt)
```
Right ?

**Comment by isrgish** [comment]
Yes

**Comment by bmvaghera** [comment]
I have new issue plz solv this help plz

Illegal option -o pipefail

**Comment by Grimler91** [comment]
Can't be more than ~5 packages that are un-locateable, easiest would be to just delete those packages from mypackages.txt (one after one). Just make sure you have the same repos added to sources.list as before (like its-pointless' community repo)

**Comment by isrgish** [comment]
@Grimler91  I guess I can do that but I was hoping for a better option.

**Comment by Grimler91** [comment]
You could write a small bash script that first checks if the package is available (by grepping the output of `apt list`) before trying to install it

**Comment by isrgish** [comment]
That is still above my level of expertise.

I still am learning how to write scripts. I guess I will have to wait until I grasp that.

Thank You,
