### ISSUE TITLE
#ln -sf $ $PREFIX/lib/libandroid-support.so bash: /data/data/com.termux/files/usr/lib/libandroid-support.so: Permission denied $

### ISSUE THREAD

**Issue by bmvaghera** [termux/termux-packages#2991]
$ #ln -sf
$ PREFIX/lib/libandroid-support.so
bash: PREFIX/lib/libandroid-support.so: No such file or directory
$ #ln -sf
$ $PREFIX/lib/libandroid-support.so
bash: /data/data/com.termux/files/usr/lib/libandroid-support.so: Permission denied
$

**Comment by Grimler91** [comment]
I don't understand what you want to do. 
You get that error since you try to execute a .so file anyways. 

Read this guide to learn the basics https://www.tldp.org/LDP/Bash-Beginners-Guide/html/
