### ISSUE TITLE
"ld" search path issue (two lib with same name conflict)

### ISSUE THREAD

**Issue by alienabhishek** [termux/termux-packages#2992]
`ld -lssl --verbose`  shows that `ld` searches for the `libssl.so` in directory `/system/lib64` first then in directory `$prefix/lib`. as my system also contain library with same name as in $prefix/lib. it causes problem with symbol export. the write way in which ld searches for the directory must be order
`$prefix/lib64/:$prefix/lib:/system/lib64`.

in privious version it works fine but in lastest this is a problem.

**Comment by xeffyr** [comment]
Search dir list for ld:
```
SEARCH_DIR("/data/data/com.termux/files/usr/aarch64-linux-android/lib64"); 
SEARCH_DIR("/data/data/com.termux/files/usr/lib64"); 
SEARCH_DIR("/system/lib64"); 
SEARCH_DIR("/data/data/com.termux/files/usr/aarch64-linux-android/lib"); 
SEARCH_DIR("/data/data/com.termux/files/usr/lib");
```

Directory `/system/lib64` should be at the end.

**Comment by xeffyr** [comment]
@alienabhishek I have opened a PR which forces a termux-specific lib search path.
