### ISSUE TITLE
Termux Update

### ISSUE THREAD

**Issue by Wjsfj51najdk** [termux/termux-packages#2997]
Got this error
apt update
Hit:1 https://termux.net stable InRelease
Hit:2 https://grimler.se root InRelease
Get:3 https://termux-x11.ml x11 InRelease [2296 B]
Hit:3 https://termux-x11.ml x11 InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://termux.net stable InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'https://grimler.se root InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://termux-x11.ml x11 InRelease' doesn't support architecture 'i386'
How can I fix this?help!?

**Comment by xeffyr** [comment]
@Wjsfj51najdk Why you have configured i386 architecture ?

**Comment by Wjsfj51najdk** [comment]
I have no idea.I just install Tool-X.

**Comment by xeffyr** [comment]
> I just install Tool-X.

Then why you are opening issue here ?
**We are not reponsible about third party tools and nasty things that they can do!**

@Grimler91 This can be closed.

**Comment by Wjsfj51najdk** [comment]
@xeffyr Isn't there any way back to normal situation

**Comment by xeffyr** [comment]
@Wjsfj51najdk Go to `$PREFIX/etc/apt` and remove line containing i386 from all sources lists.

**Comment by Wjsfj51najdk** [comment]
![screenshot_2018-10-31-01-18-57-190_com termux](https://user-images.githubusercontent.com/43841067/47742433-03702680-dcab-11e8-80c9-e31575dac68b.png)
@xeffyr There is no such line in the sources.list.It is clean

**Comment by Wjsfj51najdk** [comment]
![screenshot_2018-10-31-01-22-08-229_com termux](https://user-images.githubusercontent.com/43841067/47742675-898c6d00-dcab-11e8-91c0-e90bddf2bc82.png)

@xeffyr There is no such line in the sources.list file

**Comment by Grimler91** [comment]
What's the output of termux-info and which device is this?

**Comment by xeffyr** [comment]
@Grimler91 Seems he executed `dpkg --add-architecture i386` when run this `Tool-X`.

**Comment by Wjsfj51najdk** [comment]
This is aarch64 device .Sure, it absolutely work before this

**Comment by xeffyr** [comment]
Execute `dpkg --remove-architecture i386`.

**Comment by Grimler91** [comment]
> @Grimler91 Seems he executed dpkg --add-architecture i386 when run this Tool-X.

Aha, yeah, maybe that explains it. I was thinking if it was a weird device for which we needed to change the arch detection

**Comment by xeffyr** [comment]
@Grimler91 Anyway, we have i686 instead of i386.

**Comment by Wjsfj51najdk** [comment]
Solved. I executed dpkg --remove-architecture i386
Got this:
$ apt update
Hit:1 https://termux.net stable InRelease
Hit:2 https://grimler.se root InRelease
Get:3 https://termux-x11.ml x11 InRelease [2296 B]
Hit:3 https://termux-x11.ml x11 InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
