### ISSUE TITLE
Tmux Command not found

### ISSUE THREAD

**Issue by Secr3ts** [termux/termux-packages#2999]
Hi, I found an issue.
I installed Tmux via
$ pkg install tmux
and i wrote this on my ~/.bashrc
echo "tmux" ~/.bashrc
Normally it's supposed to do the same thing as when i type tmux, but on the launch.
Here's the problem:
When I launch, I got
"tmux" command not found

This is frustrating!
I tried restarting, unistalling and  reinstalling
but this persist..

Thanks for help

**Comment by xeffyr** [comment]
@Secr3ts Can't reproduce:

Command `tmux` was put to ~/.bashrc, nothing more, but only `tmux`:
![screenshot_20181031-142615_termux](https://user-images.githubusercontent.com/25881154/47788100-6a2c2900-dd19-11e8-88a5-a895b425e157.jpg)

Started a new Termux session:
![screenshot_20181031-142843_termux](https://user-images.githubusercontent.com/25881154/47788165-95af1380-dd19-11e8-9ccc-720b4fa61bfc.jpg)

\- `tmux` was started automatically without yours error `"tmux" command not found`.

***

> I tried restarting, unistalling and reinstalling
but this persist..

Best solution is to reinstall Termux - to make sure that you don't have messed up with another settings.

And if you really want to automatically start tmux, it is better to do it in this way:
```
test -z "$TMUX" && tmux
```
\- just to avoid warning about nested session.

**Comment by Secr3ts** [comment]
Thanks I'll test that.
I can't write commands in code because I'm  on mobile

**Comment by Secr3ts** [comment]
(I accidentally found the answer)
By searching on ~/.bashrc
I found one line  :
"tmux"
I deleted the quotes and it works! thanks
aniways  @xeffyr
