### ISSUE TITLE
gcc - ld:  unrecognised emulation mode: -dynamic-linker

### ISSUE THREAD

**Issue by robertvalik** [termux/termux-packages#3]
Hello, I tried to compile simple hello world in c, but gcc failed with this:

$ gcc -Wall hello.c -o hello
/data/data/com.termux/files/usr/bin/ld: unrecognised emulation mode: -dynamic-linker
Supported emulations: elf_i386 i386linux elf32_x86_64
collect2: error: ld returned 1 exit status

Can you, please, help me with working around this?

Thanks.

**Comment by fornwall** [comment]
It seems to be a problem with the x86 gcc package (the x86 packages are not tested as much as the arm ones). I've posted the error and asked for help at:

- http://stackoverflow.com/questions/31815737/cross-compiled-gcc-fails-with-unrecognised-emulation-mode-dynamic-linker

- https://gcc.gnu.org/ml/gcc-help/2015-08/msg00024.html

Let's hope that someone can give a pointer in one of the above threads!

**Comment by MatthewTurk** [comment]
I didn't see this when I opened #14 where I have a specs file that works for me.  I still have a few issues, particularly with numpy (which reports `dlopen failed: unknown reloc type 35 @ 0xf708f344 (2890)` ) but otherwise seems to work.

**Comment by fornwall** [comment]
Thanks a lot - I'm closing this issue in favor of #14 which has a working spec file. Will try it out and hopefully update the gcc package with it shortly!

**Comment by fornwall** [comment]
@robertvalik Just a heads up - this issue (gcc compiling on intel cpu:s did not work) should now be fixed in the latest gcc package version, available with `apt update && apt upgrade`.

**Comment by robertvalik** [comment]
It is working. Thank you!
