### ISSUE TITLE
Add task package

### ISSUE THREAD

**Issue by AnderRasoVazquez** [termux/termux-packages#30]
Taskwarrior is a command line task editor with a lot of features, including syncing task with a server. Would be great to use this wonderful program on a smartphone.
https://taskwarrior.org/

Keep up the good work! =D

**Comment by fornwall** [comment]
Thanks for the suggestion, never heard of taskwarrior before, seems like a nice tool!

I've added the package, it should be installable by `apt update && apt install taskwarrior`.

**Comment by AnderRasoVazquez** [comment]
Thanks, there's a lot of people that want to run taskwarrior on Android. I'm going to tell them on irc freenode #taskwarrior that now we can! =)
