### ISSUE TITLE
Package Request: speedtest-cli

### ISSUE THREAD

**Issue by janisaarelainen** [termux/termux-packages#3001]
Command line interface for testing internet bandwidth using speedtest.net.

https://packages.debian.org/stretch/speedtest-cli

**Comment by xeffyr** [comment]
We don't packaging things that can be installed with `pip` or similar. Use `pip install speedtest-cli` to install it.

**Comment by janisaarelainen** [comment]
I should have thought of that. Thanks for your help! Much appreciated.
