### ISSUE TITLE
Python pip install permission denied

### ISSUE THREAD

**Issue by Wjsfj51najdk** [termux/termux-packages#3003]
I accidentally install pip install passlib as root user.I tried pip install main 
pip install main
Collecting main
  Using cached https://files.pythonhosted.org/packages/1c/f4/445fbd86d9ebd133a03a263482f72dd539ccc90a0c29693222903e5e145e/main-0.1.tar.gz
Installing collected packages: main
  Running setup.py install for main ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-x0rpcnvy/main/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-qf8g_2ih/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_scripts
    creating build
    creating build/scripts-3.7
    error: file '/data/data/com.termux/files/usr/tmp/pip-install-x0rpcnvy/main/main' does not exist

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-x0rpcnvy/main/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-qf8g_2ih/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-x0rpcnvy/main/

Now can't able able to install any python module normally.Reinstalled python and tried to install modules but I got this bash: /data/data/com.termux/files/usr/bin/pip: No such file or directory.Any help

**Comment by Grimler91** [comment]
Easiest fix would be to `rm -rf $PREFIX` and restart termux, but you would then have to reinstall all installed packages ($HOME is left alone though). 

Otherwise you need to find the files owned by root and chown them to your normal user (and possible move then to /sdcard/ and back to make selinux happy)

**Comment by Wjsfj51najdk** [comment]
I reinstalled termux and pip install main
Downloading https://files.pythonhosted.org/packages/1c/f4/445fbd86d9ebd133a03a263482f72dd539ccc90a0c29693222903e5e145e/main-0.1.tar.gz
Installing collected packages: main
  Running setup.py install for main ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-zrUFdj/main/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-fOd5m4-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_scripts
    creating build
    creating build/scripts-2.7
    error: file '/data/data/com.termux/files/usr/tmp/pip-build-zrUFdj/main/main' does not exist

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-zrUFdj/main/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-fOd5m4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-zrUFdj/main/
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command
Why not module installable

**Comment by xeffyr** [comment]
> Why not main module installable

**Because this module not installable.**

See information on PyPI: https://pypi.org/project/main/
