### ISSUE TITLE
CMake freezes at checking cc

### ISSUE THREAD

**Issue by KMe0w** [termux/termux-packages#3006]

**Comment by Grimler91** [comment]
Should be fixed in https://github.com/termux/termux-packages/commit/e47952a1b50927d3ff78bb1d0cf3533cc99f6066, update make and try again

**Comment by KMe0w** [comment]
It's not make It's CMake

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/2983.

**Comment by KMe0w** [comment]
![img_20181101_150147](https://user-images.githubusercontent.com/30691126/47856302-26075a00-dde7-11e8-9b61-ce74200358a8.jpg)
Screenshot

**Comment by KMe0w** [comment]
I get stuck at this line

**Comment by Grimler91** [comment]
Closing as duplicate of #2983

**Comment by KMe0w** [comment]
Thanks
