### ISSUE TITLE
Getting Clang error 

### ISSUE THREAD

**Issue by Adarshreddyash** [termux/termux-packages#3008]
![screenshot_2018-11-01-22-39-37-406_com termux](https://user-images.githubusercontent.com/28985009/47867268-0bed6c00-de27-11e8-8bd6-b5bf29ee73e7.png)

**Comment by xeffyr** [comment]
1. Post commands that you used for compilation (not make, but clang/clang++/ld ones). Your screenshot don't provide information about error's source.

2. This is a C++ code. You have to use `clang++` command instead of `clang`.

**Comment by Grimler91** [comment]
Closing as not termux related
