### ISSUE TITLE
Changing LC_ALL gives "No such file or directory" error

### ISSUE THREAD

**Issue by vovcacik** [termux/termux-packages#3009]
Hi,
I am trying to set LC_ALL to match my locale, but bash returns error.

```
-bash-4.4$ LC_ALL=cs_CZ.UTF-8
-bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8): No such file or directory
```

I also tried to install extended locale support for Bionic, but the error message is the same (even after restart):

```
# after "pkg install libandroid-support"
-bash-4.4$ touch åäö && find . -name åäö
./åäö

-bash-4.4$ LC_ALL=cs_CZ.UTF-8
-bash: warning: setlocale: LC_ALL: cannot change locale (cs_CZ.UTF-8): No such file or directory
```

Should I generate my locale alá `locale-gen`?

**Comment by vovcacik** [comment]
The reasoning behind installing `libandroid-support` is that I found similar problem someone had on Slackware and he solved it by installing `glibc` and `glibc-i18n` packages. My understanding is that Bionic and `libandroid-support` package are comparable to his solution.

[I got warning setlocale LC_CTYPE when I ssh connect to vagrant centos 6](https://stackoverflow.com/a/38813358/2587343)

**Comment by xeffyr** [comment]
>-bash-4.4$ LC_ALL=cs_CZ.UTF-8

We don't have locale support.

>locale-gen

We don't have GNU libc and never will have.

**Comment by xeffyr** [comment]
Little more information about libandroid-support:

>The purpose of libandroid-support in Termux is to add functionality missing the system libc to **ease building packages**.

\- so it doesn't add locale support.

**Comment by vovcacik** [comment]
The package description claims it does add locale support though

```
pkg search locale
(...)
libandroid-support/stable,now 22 arm [installed]
  Library extending the Android C library (Bionic) for additional multibyte, locale and math support
```

Also it helped to solve locale problem in #2487.

**Comment by xeffyr** [comment]
It provides only functions. Locales are **disabled by default**, that's why LANG is not working: see https://github.com/termux/termux-packages/blob/master/build-package.sh#L816

**Comment by xeffyr** [comment]
And I'm suggesting to read this: https://github.com/termux/termux-packages/issues/2796#issuecomment-424589888

**Comment by vovcacik** [comment]
Thanks, that explains it.
