### ISSUE TITLE
Pip Install Pandas 0.23.4 on Python 3.7

### ISSUE THREAD

**Issue by falloutphil** [termux/termux-packages#3012]
Hi,

Build tools installed as termux packages.

I got around issues building numpy by installing the package from it's pointless.

The other prerequisites seem to install OK by pip.

But Pandas itself fails to build.

I can see from Google that previous versions have installed OK, but can't find any confirmation of anyone having success with the latest versions (0.23.4 on 3.7).

Any ideas or pointers.

I've tried this - no luck:
`LD_FLAGS=" -lm" pip3 install -vvv pandas`

The other prerequisites seems to install ok 

copying pandas/_libs/tslibs/__init__.py -> build/lib.linux-armv7l-3.7/pandas/_libs/tslibs
creating build/lib.linux-armv7l-3.7/pandas/api/types
copying pandas/api/types/__init__.py -> build/lib.linux-armv7l-3.7/pandas/api/types
creating build/lib.linux-armv7l-3.7/pandas/api/extensions
copying pandas/api/extensions/__init__.py -> build/lib.linux-armv7l-3.7/pandas/api/extensions
creating build/lib.linux-armv7l-3.7/pandas/io/formats/templatescopying pandas/io/formats/templates/html.tpl -> build/lib.linux-armv7l-3.7/pandas/io/formats/templates
UPDATING build/lib.linux-armv7l-3.7/pandas/_version.py set build/lib.linux-armv7l-3.7/pandas/_version.py to '0.23.4'
running build_extbuilding 'pandas._libs.algos' extension creating build/temp.linux-armv7l-3.7

creating build/temp.linux-armv7l-3.7/pandas  creating build/temp.linux-armv7l-3.7/pandas/_libs arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -Ipandas/_libs/src/klib -Ipandas/_libs/src -I/data/data/com.termux/files/usr/lib/python3.7/site-packages/numpy-1.15.2-py3.7-linux-armv8l.egg/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.7m -c pandas/_libs/algos.c -o build/temp.linux-armv7l-3.7/pandas/_libs/algos.o -Wno-unused-function

In file included from pandas/_libs/algos.c:567:   In file included from /data/data/com.termux/files/usr/lib/python3.7/site-packages/numpy-1.15.2-py3.7-linux-armv8l.egg/numpy/core/include/numpy/arrayobject.h:4:   In file included from /data/data/com.termux/files/usr/lib/python3.7/site-packages/numpy-1.15.2-py3.7-linux-armv8l.egg/numpy/core/include/numpy/ndarrayobject.h:18:In file included from /data/data/com.termux/files/usr/lib/python3.7/site-packages/numpy-1.15.2-py3.7-linux-armv8l.egg/numpy/core/include/numpy/ndarraytypes.h:1821:
/data/data/com.termux/files/usr/lib/python3.7/site-packages/numpy-1.15.2-py3.7-linux-armv8l.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2:
warning: "Using deprecated NumPy API, disable it by ""#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings] #warning "Using deprecated NumPy API, disable it by " \ ^
clang-7: error: unable to execute command: Segmentation fault  clang-7:
error: clang frontend command failed due to signal (use -v to see invocation)
clang version 7.0.0 (tags/RELEASE_700/final) Target: arm--linux-android    Thread model: posix   InstalledDir: /data/data/com.termux/files/usr/bin clang-7: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-7: note: diagnostic msg:********************    PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:   Preprocessed source(s) and associated run script(s) are located at:
clang-7: note: diagnostic msg: /data/data/com.termux/files/usr/tmp/algos-493413.c
clang-7: note: diagnostic msg: /data/data/com.termux/files/usr/tmp/algos-493413.sh
clang-7: note: diagnostic msg:    ********************  error: command 'arm-linux-androideabi-clang' failed with exit status 254  error  Cleaning up...Removing source in /data/data/com.termux/files/usr/tmp/pip-install-ff8ecrsd/pandas

**Comment by xeffyr** [comment]
> clang-7: error: unable to execute command: Segmentation fault
clang-7: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 7.0.0 (tags/RELEASE_700/final) Target: arm--linux-android

Looks like the first bug report about segfault in clang (ARM)...

**Comment by falloutphil** [comment]
@xeffyr thanks... I can't create a new account (disabled for now) for reporting the bug, I've emailed it to llvm bug admin instead.

**Comment by falloutphil** [comment]
In the meantime anyone know of a workaround or binary package for Pandas?

**Comment by xeffyr** [comment]
> I've emailed it to llvm bug admin instead.

@falloutphil Bug may be Termux-specific, segfault is very common for ARM. Clang in Termux is **not supported** by LLVM developers.

**Comment by Grimler91** [comment]
Possibly related to https://github.com/termux/termux-packages/issues/3005, but that issue was on aarch64. 

@falloutphil You can install gcc (and then run setup-gcc#) from its-pointless repo as well, as a workaround, and then install pandas.
I tried installing pandas on my arm device, with all packages up to date, and it finished without any segfault or problems

**Comment by Grimler91** [comment]
@xeffyr Yeah, might be totally unrelated

**Comment by xeffyr** [comment]
@Grimler91 I have successfully installed pandas on AArch64;

![pandas_termux](https://user-images.githubusercontent.com/25881154/47964475-5f3c0600-e043-11e8-9928-de081437af99.jpg)

Just did `pip install pandas`, only official packages are installed. As you can see, there no errors or warnings.

**Comment by falloutphil** [comment]
@Grimler91 thanks to confirm apt installing gcc-7 worked as suggested.  It took forever to install, but worked eventually.

**Comment by xeffyr** [comment]
@Grimler91 Reason why it fails: https://github.com/termux/termux-packages/issues/3005#issuecomment-436664431

**Comment by ycathi** [comment]
> @Grimler91 Reason why it fails: [#3005 (comment)](https://github.com/termux/termux-packages/issues/3005#issuecomment-436664431)

Have you ever tested it? Is it effective?

**Comment by tathastu871** [comment]
> Possibly related to #3005, but that issue was on aarch64.
> 
> @falloutphil You can install gcc (and then run setup-gcc#) from its-pointless repo as well, as a workaround, and then install pandas.
> I tried installing pandas on my arm device, with all packages up to date, and it finished without any segfault or problems

arm is not a problem. All issues are mainly related to aarch64.
