### ISSUE TITLE
[ Error While Install Nokogiri 1.8.0 Version ] 

### ISSUE THREAD

**Issue by XSecr3t** [termux/termux-packages#3014]
[ Error While Instalaling Nokogiri 1.8.0 ]

Excuse Me
Hello sir greetings

I have some problem can anybody help me?

I want install Nokogiri 1.8.0 but cant cause have error like this

> To see why this extension failed to compile, please check the mkmf.log which can be found here:
>/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/nokogiri-1.8.0/mkmf.log
> extconf failed, exit code 1
> Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/nokogiri-1.8.0/gem_make.out

I have already run any command that i see like

> gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]
Or
> bundle config build.nokogiri --use-system-libraries
    bundle install

But the result still same, exit  ode 1

So what should i do?
I already uninstalled and installed again my termux 10times since 2 day ago
And Rebuild Package but the result still same,error code 1
It sucks for me can anyone help me sir?

It would be pleasure if somebody help me for guide me how to fix this problems.
First time i use termux looks good and everything is fine,but after 3 or 4 month everything has change,i already update every second every files and package but the result still same.

Somebody please help me🙁🙁

Because this problem i cannot run my metasploit again.

> here more error : http://i67.tinypic.com/343maoh.png
http://i67.tinypic.com/2ahz9f9.png
http://i66.tinypic.com/23w08yr.png
http://i67.tinypic.com/4uyk1y.png
http://i65.tinypic.com/2w7ph12.png
http://i68.tinypic.com/2vjph6r.png
http://i67.tinypic.com/20shis5.png

I think someone can help me for solve this,i dont know what i want to do again,,,
I'll do everything but still same

i try to used following command

> LDFLAGS=" -lglob" gem install nokogiri -- --use-system-libraries.

But the result said i installed nokogiri 1.8.5 not 1.8.0 versions,my metasploit needs nokogiri 1.8.0 not 1.8.5

> result :
LDFLAGS=" -lglob" gem install nokogiri -- --use-system-libraries
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Building native extensions with: '--use-system-libraries'
This could take a while...
Successfully installed nokogiri-1.8.5
Parsing documentation for nokogiri-1.8.5
Done installing documentation for nokogiri after 10 seconds
1 gem installed
root@Mr.XSecr3t:#

When i run msfconsole result said

> root@Mr.XSecr3t:#msfconsole
Could not find nokogiri-1.8.0 in any of the sources
Run bundle install to install missing gems.
root@Mr.XSecr3t:#

And when i run bundle install the result said

> root@Mr.XSecr3t:#bundle install
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Could not locate Gemfile
root@Mr.XSecr3t:#

so can anybody help me fix this problems? i dont know what i want to do,i cant run my metasploit again. 🙁🙁

thanks for helping me and reply my issued!

**Comment by Herzogs** [comment]
If you want install nokogiri 1.8.0, you should put this gem install nokogiri -v 1.8.0

**Comment by Grimler91** [comment]
Use the `-v` flag to choose version. Check `gem --help` for more information.

**Comment by XSecr3t** [comment]
@Grimler

Already done sir
Succes installed nokogiri 1.8.0 and run bundle install
Seems works bundle install and successfully fetch 12 gem files
But when i run msfconsole this error show up 
This time much error i dont know what  is it

> root@Mr.XSecr3t:~#msfconsole                       WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych.so: unused DT entry: type 0x6ffffef5 arg 0x4d0           WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0/lib/nokogiri/nokogiri.so: unused DT entry: type 0x6ffffef5 arg 0xba0
WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/pcaprub-0.12.4/lib/pcaprub_c.so: unused DT entry: type 0x6ffffef5 arg 0x3e0
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/versions.rb:4: warning: already initialized constant Psych::VERSION
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/versions.rb:4: warning: previous definition of VERSION was here
/data/data/com.termux/files/usr/lib/ruby/2
h64-linux-android/psych.so: warning: already initialized constant Psych::Parser::ANY
/data/data/com.termux/files/usr/lib/ruby/2.5.0/aarch64-linux-android/psych.so: warning: already initialized constant Psych::Parser::UTF8
/data/data/com.termux/files/usr/lib/ruby/2.5.0/aarch64-linux-android/psych.so: warning: already initialized constant Psych::Parser::UTF16LE
/data/data/com.termux/files/usr/lib/ruby/2.5.0/aarch64-linux-android/psych.so: warning: already initialized constant Psych::Parser::UTF16BE
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:7: warning: already initialized constant Psych::ClassLoader::BIG_DECIMAL
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:7: warning: previous definition of BIG_DECIMAL was here   /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:8: warning: already initialized constant Psych::ClassLoader::COMPLEX
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:8: warning: previous definition of COMPLEX was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:9: warning: already initialized constant Psych::ClassLoader::DATE
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:9: warning: previous definition of DATE was here          /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:10: warning: already initialized constant Psych::ClassLoader::DATE_TIME
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:10: warning: previous definition of DATE_TIME was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:11: warning: already initialized constant Psych::ClassLoader::EXCEPTION
0/gems/psych-3.0.3/lib/psych/class_loader.rb:11: warning: previous definition of EXCEPTION was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:12: warning: already initialized constant Psych::ClassLoader::OBJECT                /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:12: warning: previous definition of OBJECT was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:13: warning: already initialized constant Psych::ClassLoader::PSYCH_OMAP            /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:13: warning: previous definition of PSYCH_OMAP was here   /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:14: warning: already initialized constant Psych::ClassLoader::PSYCH_SET             /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:14: warning: previous definition of PSYCH_SET was here    /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:15: warning: already initialized constant Psych::ClassLoader::RANGE                 /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:15: warning: previous definition of RANGE was here        /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:16: warning: already initialized constant Psych::ClassLoader::RATIONAL              /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:16: warning: previous definition of RATIONAL was here     /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:17: warning: already initialized constant Psych::ClassLoader::REGEXP
0/gems/psych-3.0.3/lib/psych/class_loader.rb:17: warning: previous definition of REGEXP was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:18: warning: already initialized constant Psych::ClassLoader::STRUCT                /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:18: warning: previous definition of STRUCT was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:19: warning: already initialized constant Psych::ClassLoader::SYMBOL                /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:19: warning: previous definition of SYMBOL was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/class_loader.rb:65: warning: already initialized constant Psych::ClassLoader::CACHE                 /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/class_loader.rb:65: warning: previous definition of CACHE was here        /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/scalar_scanner.rb:9: warning: already initialized constant Psych::ScalarScanner::TIME               /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/scalar_scanner.rb:9: warning: previous definition of TIME was here        /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/scalar_scanner.rb:12: warning: already initialized constant Psych::ScalarScanner::FLOAT             /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/scalar_scanner.rb:12: warning: previous definition of FLOAT was here      /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/scalar_scanner.rb:17: warning: already initialized constant Psych::ScalarScanner::INTEGER
0/gems/psych-3.0.3/lib/psych/scalar_scanner.rb:17: warning: previous definition of INTEGER was here    /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:13: warning: already initialized constant Psych::Nodes::Stream::ANY                 /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/stream.rb:13: warning: previous definition of ANY was here          /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:16: warning: already initialized constant Psych::Nodes::Stream::UTF8                /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/stream.rb:16: warning: previous definition of UTF8 was here         /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:19: warning: already initialized constant Psych::Nodes::Stream::UTF16LE             /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/stream.rb:19: warning: previous definition of UTF16LE was here      /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:22: warning: already initialized constant Psych::Nodes::Stream::UTF16BE             /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/stream.rb:22: warning: previous definition of UTF16BE was here      /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/sequence.rb:43: warning: already initialized constant Psych::Nodes::Sequence::ANY             /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/sequence.rb:43: warning: previous definition of ANY was here        /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/sequence.rb:46: warning: already initialized constant Psych::Nodes::Sequence::BLOCK
0/gems/psych-3.0.3/lib/psych/nodes/sequence.rb:46: warning: previous definition of BLOCK was here      /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/sequence.rb:49: warning: already initialized constant Psych::Nodes::Sequence::FLOW
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/sequence.rb:49: warning: previous definition of FLOW was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:10: warning: already initialized constant Psych::Nodes::Scalar::ANY
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:10: warning: previous definition of ANY was here          /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:13: warning: already initialized constant Psych::Nodes::Scalar::PLAIN
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:13: warning: previous definition of PLAIN was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:16: warning: already initialized constant Psych::Nodes::Scalar::SINGLE_QUOTED       /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:16: warning: previous definition of SINGLE_QUOTED was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:19: warning: already initialized constant Psych::Nodes::Scalar::DOUBLE_QUOTED
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:19: warning: previous definition of DOUBLE_QUOTED was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:22: warning: already initialized constant Psych::Nodes::Scalar::LITERAL
0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:22: warning: previous definition of LITERAL was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:25: warning: already initialized constant Psych::Nodes::Scalar::FOLDED
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/scalar.rb:25: warning: previous definition of FOLDED was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/mapping.rb:17: warning: already initialized constant Psych::Nodes::Mapping::ANY               /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/mapping.rb:17: warning: previous definition of ANY was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/mapping.rb:20: warning: already initialized constant Psych::Nodes::Mapping::BLOCK
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/mapping.rb:20: warning: previous definition of BLOCK was here       /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/nodes/mapping.rb:23: warning: already initialized constant Psych::Nodes::Mapping::FLOW
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/nodes/mapping.rb:23: warning: previous definition of FLOW was here        /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/visitors/visitor.rb:11: warning: already initialized constant Psych::Visitors::Visitor::DISPATCH    /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/visitors/visitor.rb:11: warning: previous definition of DISPATCH was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:334: warning: already initialized constant Psych::Visitors::ToRuby::SHOVEL
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/handler.rb:27: warning: already initialized constant Psych::Handler::OPTIONS                        /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/handler.rb:27: warning: previous definition of OPTIONS was here
/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/handler.rb:30: warning: already initialized constant Psych::Handler::EVENTS
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/psych-3.0.3/lib/psych/handler.rb:30: warning: previous definition of EVENTS was here
Traceback (most recent call last):
        37: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `<main>'
        36: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `require'
        35: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        34: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        33: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        32: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        31: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
30: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
        29: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
        28: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
        27: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
        26: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:64:in `<class:Framework>'
        25: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        24: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        23: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
22: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
        21: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
        20: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/cert_provider.rb:2:in `<top (required)>'
        19: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        18: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/faker-1.8.7/lib/faker.rb:5:in `<top (required)>'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'                 9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'                                8: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych.rb:19:in `<top (required)>'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'                                                           5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
         4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
2: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/parser.rb:2:in `<top (required)>'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/parser.rb:33:in `<module:Psych>'/data/data/com.termux/files/usr/lib/ruby/2.5.0/psych/parser.rb:34:in `<class:Parser>': superclass mismatch for class Mark (TypeError)

I dont know what is it
