### ISSUE TITLE
Some scripts in /scripts fail because /bin/sh is linked to dash, not the needed bash

### ISSUE THREAD

**Issue by crass** [termux/termux-packages#3017]
Specifically `scripts/setup-android-sdk.sh` sources `scripts/properties.sh` which in turn uses the bashism `source` to source `.termuxrc`.  The problem is that on my Ubuntu 16.10 system `/bin/sh` is a symlink to `/bin/dash` which does not recognize the `source` command. There may be other scripts with bashisms, I haven't looked thoroughly.

So I'd suggest either changing `source` in `scripts/properties.sh` to `.` or make sure that anything executing `scripts/properties.sh` is running bash.

**Comment by fornwall** [comment]
Thanks a lot for reporting! This has now been fixed by @Grimler91 in https://github.com/termux/termux-packages/pull/3023
