### ISSUE TITLE
Building libexpat on system without xml capable docbook2man fails

### ISSUE THREAD

**Issue by crass** [termux/termux-packages#3018]
On my Ubuntu system I have a `docbook2man` that is sgml but not xml capable. So when i run `./build-package.sh -a arm -d packages/libexpat` the failure message is:

```
configure: error: Your local docbook2man was found to work with SGML rather
  than XML. Please install docbook2X and use variable DOCBOOK_TO_MAN to point
  configure to command docbook2x-man of docbook2X.
  Or use DOCBOOK_TO_MAN="xmlto man --skip-validation" if you have xmlto around.
  You can also configure using --without-docbook if you can do without a man
  page for xmlwf.
```

I've added `--without-docbook` to `TERMUX_PKG_EXTRA_CONFIGURE_ARGS` in `packages/libexpat/build.sh` and the build works.  Since `libexpat` doesn't install manpages disabling docbook shouldn't matter.  Also, this fixes and builds which require `libexpat` on affected systems.

**Comment by fornwall** [comment]
Thanks for reporting! This has now been fixed by @Grimler91 in https://github.com/termux/termux-packages/pull/3022
