### ISSUE TITLE
SELinux support for coreutils

### ISSUE THREAD

**Issue by isrgish** [termux/termux-packages#3020]
I was trying to use `ls` from `coreutils` to get the SELinux  codes. It doesn't seem to work. If I run `/system/bin/ls` it runs fine. Is there any way of fixing this?

Thank You,

**Comment by xeffyr** [comment]
> Is there any way of fixing this?

See this answer: https://github.com/termux/termux-packages/issues/544#issuecomment-436998591

To have working SELinux support in coreutils, we have to link it against system libselinux.so (/system/lib/libselinux.so). This library is a bit different from one used on desktop Linux distributions, also it is not a part of Android NDK.

**Comment by truboxl** [comment]
Fixed by #21495
