### ISSUE TITLE
Preserve command history between runs

### ISSUE THREAD

**Issue by rafis** [termux/termux-packages#303]
I've lost long commands I've typed for 3-5 mins in previous run of Termux. How to preserve all commands I type like .bash_history?

**Comment by tinydynamite00** [comment]
You can extend the <i>-n</i> value for the Bash environment variables, <code>HISTFILESIZE</code> & <code>HISTSIZE</code> in <code>${PREFIX}/etc/bash.bashrc</code> or <code>~/.bash_profile</code> - more a matter of personal preference in the case of Termux, as it sets up a single user, however extensible, environment by default. Otherwise, <code>bash.bashrc</code> houses global, system wide variables while <code>.bash_profile</code> - created in the user's <code>$HOME</code> directory - houses the shell variables for each user account, independent of <code>$SHELL</code>'s globally set functions & variables.

**Comment by fornwall** [comment]
Nice explanation @tinydynamite00! Closing this issue.

**Comment by rafis** [comment]
$ echo "$SHELL"
    /data/data/com.termux/files/usr/bin/bash
    $ printenv | grep HIST
    $ set | grep HIST
    HISTFILE=/data/data/com.termux/files/home/.bash_history
    HISTFILESIZE=500
    HISTSIZE=500

Commands are written to history only if I type `exit`. Please catch Android event of application closing and call `exit` in terminal - if that possible.

**Comment by tinydynamite00** [comment]
Several <code>shopt</code> settings are off by default, primarily for privacy reasons. Run <code>shopt</code> at a prompt (w/o options or arguments). Is the shell option <code>histappend</code> turned on for your shell? Without this option on, <code>history</code> is overwritten when a new shell is spawned. Also, <code>set</code> will inform you how <code>history</code> is being managed with the value of the shell variable <code>HISTCONTROL</code>.

This, from the _GNU Bash Reference Manual_ may be of interest to you:

>HISTCONTROL
A colon-separated list of values controlling how commands are saved on the history list. If the list of values includes ‘ignorespace’, lines which begin with a space character are not saved in the history list. A value of ‘ignoredups’ causes lines which match the previous history entry to not be saved. A value of ‘ignoreboth’ is shorthand for ‘ignorespace’ and ‘ignoredups’. A value of ‘erasedups’ causes all previous lines matching the current line to be removed from the history list before that line is saved. Any value not in the above list is ignored. If HISTCONTROL is unset, or does not include a valid value, all lines read by the shell parser are saved on the history list, subject to the value of HISTIGNORE. The second and subsequent lines of a multi-line compound command are not tested, and are added to the history regardless of the value of HISTCONTROL.
- SOURCE: https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html

**Comment by max0x7ba** [comment]
> I've lost long commands I've typed for 3-5 mins in previous run of Termux. How to preserve all commands I type like .bash_history?

Do `echo "shopt -s histappend" >> ~/.bash_profile`. And then use `exit` to save the history on exit from the shell.
