### ISSUE TITLE
Package request: iproute2

### ISSUE THREAD

**Issue by kees-closed** [termux/termux-packages#3043]
The `ip` command is available, but `ss` is not. The iproute2 package isn't available. Could you please add all utilities of the iproute2 suite?

[More info](https://wiki.linuxfoundation.org/networking/iproute2).

**Comment by Atavic** [comment]
Actual repository: https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/about/

**Comment by libnux** [comment]
+1 for ss command

**Comment by jaimet** [comment]
[(`netstat` was considered deprecated in 2011!)](https://dougvitale.wordpress.com/2011/12/21/deprecated-linux-networking-commands-and-their-replacements/)

**Comment by darkblaze69** [comment]
why there's no ss in termux?

**Comment by dewijones92** [comment]
yes please

**Comment by kevinzu007** [comment]
+1 for ss command

**Comment by rojenzaman** [comment]
+1 to ss command

**Comment by ChiefMikeK** [comment]
Maybe you should try this?   

- http://ftp.debian.org/debian/pool/main/s/sockstat/
- [sockstat(1) \[freebsd man page\]](https://www.unix.com/man-page/FreeBSD/1/sockstat/ )

**Comment by superjamie** [comment]
> Maybe you should try this?
> 
>     * http://ftp.debian.org/debian/pool/main/s/sockstat/
> 
>     * [sockstat(1) [freebsd man page]](https://www.unix.com/man-page/FreeBSD/1/sockstat/)

`sockstat` reads from procfs like `netstat` does. That is the old way of doing things. The files in procfs are only guaranteed atomic per-line, the contents can change during the runtime of a particularly large read.

The iproute tools use netlink sockets to communicate with the kernel. This is the new way of doing things. These tools work in units of one atomic block of information which is guaranteed correct at that point in time. The information will not change over the runtime of the command even for large data.

`ss` offers superior filtering methods over both `netstat` and `sockstat`. It can also display a lot more about internal kernel information.

So, this suggestion isn't a replacement or even a close equivalent of what `ss` provides and can do.

**Comment by frainz-de** [comment]
I would still like the ss command in termux.
