### ISSUE TITLE
pip install bluepy : Failed to compile bluepy-helper

### ISSUE THREAD

**Issue by ycathi** [termux/termux-packages#3044]
`pip install bluepy`

Collecting bluepy
  Using cached https://files.pythonhosted.org/packages/1f/5d/fb28bf7d95669b6909cc39dbc1c631f16fc61184f4bb5a3188f1662ca59c/bluepy-1.2.0.tar.gz
Installing collected packages: bluepy
  Running setup.py install for bluepy: started
    Running setup.py install for bluepy: finished with status 'error'
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-b3b94it2/bluepy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-1acdczca/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    Working dir is /data/data/com.termux/files/usr/tmp/pip-install-b3b94it2/bluepy
    execute make -C ./bluepy clean
    execute make -C bluepy -j1
    Failed to compile bluepy-helper. Exiting install.
    Command was 'make -C bluepy -j1' in /data/data/com.termux/files/usr/tmp/pip-install-b3b94it2/bluepy
    Return code was 2
    Output was:
    b"make: Entering directory '/data/data/com.termux/files/usr/tmp/pip-install-b3b94it2/bluepy/bluepy'\ntar xzf bluez-src.tgz\ntouch ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c\ncc -L. -Os -g -Wall  -DHAVE_CONFIG_H -I./bluez-5.47/attrib -I./bluez-5.47 -I./bluez-5.47/lib -I./bluez-5.47/src -I./bluez-5.47/gdbus -I./bluez-5.47/btio -I./bluez-5.47/sys -I/data/data/com.termux/files/usr/include/glib-2.0 -I/data/data/com.termux/files/usr/lib/glib-2.0/include -I/data/data/com.termux/files/usr/include -o bluepy-helper bluepy-helper.c ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c -L/data/data/com.termux/files/usr/lib -lglib-2.0\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/tmp/sdp-912f57.o: in function `android_polyfill_vsyslog':\n/data/data/com.termux/files/usr/include/syslog.h:119: undefined reference to `__android_log_print'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:116: undefined reference to `__android_log_vprint'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/tmp/log-8c2b31.o: in function `android_polyfill_vsyslog':\n/data/data/com.termux/files/usr/include/syslog.h:119: undefined reference to `__android_log_print'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:116: undefined reference to `__android_log_vprint'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:119: undefined reference to `__android_log_print'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:116: undefined reference to `__android_log_vprint'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:119: undefined reference to `__android_log_print'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:116: undefined reference to `__android_log_vprint'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:119: undefined reference to `__android_log_print'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:116: undefined reference to `__android_log_vprint'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:119: undefined reference to `__android_log_print'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:116: undefined reference to `__android_log_vprint'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:119: undefined reference to `__android_log_print'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:116: undefined reference to `__android_log_vprint'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:119: undefined reference to `__android_log_print'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:116: undefined reference to `__android_log_vprint'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:119: undefined reference to `__android_log_print'\n/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/include/syslog.h:116: undefined reference to `__android_log_vprint'\nclang-7: error: linker command failed with exit code 1 (use -v to see invocation)\nmake: *** [Makefile:28: bluepy-helper] Error 1\nmake: Leaving directory '/data/data/com.termux/files/usr/tmp/pip-install-b3b94it2/bluepy/bluepy'\n"
    
    ----------------------------------------

**Comment by ycathi** [comment]
`termux-info` output

Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.84-perf-g7f0277a #1 SMP PREEMPT Thu Nov 8 00:40:04 CST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
6.0.1
Device manufacturer:
Xiaomi
Device model:
Redmi Note 3

**Comment by Grimler91** [comment]
Bluepy will not work since we don't have Bluetooth support. 
This particular error can be fixed by linking against liblog.so though, so `LDFLAGS=" -llog" pip install bluepy` solves it
