### ISSUE TITLE
Package request lrzip

### ISSUE THREAD

**Issue by ashutoshmaurya1122** [termux/termux-packages#3045]
Could you compile lrzip for termux.I heard it has best compression ratio.

**Comment by Wetitpig** [comment]
Source here: https://github.com/ckolivas/lrzip

**Comment by ashutoshmaurya1122** [comment]
It requires linlzo2-dev which is not available in termux.

**Comment by xeffyr** [comment]
@ashutoshmaurya1122 `pkg install liblzo-dev`. Some packages have different name.

**Comment by ashutoshmaurya1122** [comment]
I am getting error like this
Making install in lzma
make[1]: Entering directory '/data/data/com.termux/files/home/lrzip/lzma'
Making install in C
make[2]: Entering directory '/data/data/com.termux/files/home/lrzip/lzma/C'
make[3]: Entering directory '/data/data/com.termux/files/home/lrzip/lzma/C'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/data/data/com.termux/files/home/lrzip/lzma/C'
make[2]: Leaving directory '/data/data/com.termux/files/home/lrzip/lzma/C'
make[2]: Entering directory '/data/data/com.termux/files/home/lrzip/lzma'
make[3]: Entering directory '/data/data/com.termux/files/home/lrzip/lzma'
make[3]: Nothing to be done for 'install-exec-am'.
 /data/data/com.termux/files/usr/bin/mkdir -p '/usr/local/share/doc/lrzip/lzma'
/data/data/com.termux/files/usr/bin/mkdir: cannot create directory '/usr': Read-only file system
make[3]: *** [Makefile:399: install-lzmadocDATA] Error 1
make[3]: Leaving directory '/data/data/com.termux/files/home/lrzip/lzma'
make[2]: *** [Makefile:590: install-am] Error 2
make[2]: Leaving directory '/data/data/com.termux/files/home/lrzip/lzma'
make[1]: *** [Makefile:426: install-recursive] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/lrzip/lzma'
make: *** [Makefile:954: install-recursive] Error 1

**Comment by ashutoshmaurya1122** [comment]
Can you help me to fix this 
warning generated.
  CC       aes.lo
  CC       sha4.lo
  CXX      libzpaq/libzpaq.lo
  CXXLD    libtmplrzip.la
  CXXLD    lrzip
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ./.libs/libtmplrzip.a(rzip.o): in function `lesser_bitness':
/data/data/com.termux/files/home/lrzip/rzip.c:317: undefined reference to `ffsll'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/home/lrzip/rzip.c:317: undefined reference to `ffsll'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:735: lrzip] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/lrzip'
make: *** [Makefile:954: install-recursive] Error 1

**Comment by Wetitpig** [comment]
Add something like this?:

https://github.com/lattera/glibc/blob/master/string/ffsll.c
https://github.com/lattera/glibc/blob/master/string/ffs.c

**Comment by xeffyr** [comment]
@Wetitpig Thanks, I will try it. Maybe even open a PR for lrzip.

**Comment by danieldjewell** [comment]
Hi All, 

I believe I found the issue and have submitted a PR to @ckolivas -- https://github.com/ckolivas/lrzip/pull/114

It seems to have come down to 4 underscores in lrzip_private.h not detecting Android -- https://github.com/danieldjewell/lrzip contains the fix and I have just compiled it within Termux (on device) using clang-8. I have not yet tried a cross-compile (the definition that I fixed in lrzip_private.h might need to be modified for cross compilation...)

Standard compile from github on Termux rules apply:
```bash
git clone https://github.com/danieldjewell/lrzip.git
cd lrzip
autoreconf -fi 
./configure --prefix=$PREFIX
make 
#or make -j4 or -j8 
make install 
```

**Comment by danieldjewell** [comment]
Wow, looks like my PR was merged in-between the time I made the PR and was writing my last comment. the master lrzip repo should now build on android :) - at least, on-device
