### ISSUE TITLE
metaflac needs --no-utf8-convert to work properly while it shouldn't

### ISSUE THREAD

**Issue by tomty89** [termux/termux-packages#3047]
I built flac in Termux with and without `/data/data/com.termux/files/usr/include/langinfo.h -> libandroid-support/langinfo.h` and confirmed that it is the source of the problem.

@fornwall I had PRs that fixes it in different manners but they were never accepted (for whatever reason, maybe it was only because you were busy and missed them). Would you mind fix *libandroid-support-dev* (and rebuild flac) in whichever way you find best (e.g. add the missing symlink or even just put the headers directly under `include/`)? https://github.com/termux/termux-packages/blob/master/build-package.sh#L628 can probably go afterwards either way.

**Comment by fornwall** [comment]
@tomty89 Sorry, I've been a lot busy. Could you create a new PR (or link to an existing one) for this?
