### ISSUE TITLE
How to unmount (and remount) External SD

### ISSUE THREAD

**Issue by isrgish** [termux/termux-packages#3048]
I'm looking to be able to unmount and then later mount the external sd card. I found something about using `sm` but I get the following error:

sm list-volumes
CANNOT LINK EXECUTABLE "app_process": cannot locate symbol "u_charMirror_56" referenced by "/system/lib64/libandroid_runtime.so"...

[1]+  Stopped                 sm list-volumes

Can anyone help me understand this error? Or help me with finding another way of doing this.

Thank You,

**Comment by xeffyr** [comment]
@isrgish You need to unset `LD_*` variables:
```
bash
unset LD_LIBRARY_PATH LD_PRELOAD
/system/bin/sm list-volumes
```

When you finish with `sm`, type `exit` to return to previous shell with correct LD_LIBRARY_PATH and LD_PRELOAD.

**Comment by isrgish** [comment]
Thank You @xeffyr 

Another option is to use `tsu -p` What this does is it prepends the system libs and system bin.
