### ISSUE TITLE
Can termux increase swap size?

### ISSUE THREAD

**Issue by ycathi** [termux/termux-packages#3052]
If you can, please tell me how to do it.
Thanks.

**Comment by xeffyr** [comment]
> increase swap size

Do you think that your device will be faster ? After similar experiments I realized that stock is the best.

> how to do it.

```
cd /data
dd if=/dev/zero of=swapfile.img bs=1M count=1024
mkswap swapfile.img
swapon swapfile.img
```

Termux is doesn't provide swapon/swapoff so you will have to use ones located in /system/bin or /system/xbin. Utility `mkswap` you can find in package `util-linux`.

Everything else like swap parameters or answers to how/why, you can find on Internet. If you need ZRam-based swap, see https://android.googlesource.com/kernel/msm/+/android-msm-bullhead-3.10-marshmallow-dr/Documentation/blockdev/zram.txt, but note that on Android, many things are different from ones on classical Linux-based OSes.

**Comment by ycathi** [comment]
Aha, when I compiled a package, I was reminded that swap memory was not enough.
I am root account in termuxarch, but hint that I do not have enough permissions.
Thanks.

I should promote the root permissions of termux first.
