### ISSUE TITLE
Android ndk 17 and 18 headers no longer support gcc

### ISSUE THREAD

**Issue by RoadOFF** [termux/termux-packages#3055]
I have some problems with clang (strange linker error, but clang++ works fine, as i knew later), so i tried to install gcc from pointless repo, but gcc package uses ndk-sysroot, please add version with old headers.

**Comment by xeffyr** [comment]
Closing since related to GCC from https://github.com/its-pointless/its-pointless.github.io.

**Comment by Wetitpig** [comment]
Is termux going to leave fortran or R for @its-pointless for developement? Thanks!
