### ISSUE TITLE
Hex format in printf broken for certain input on Android/x64?

### ISSUE THREAD

**Issue by joakim-noah** [termux/termux-packages#3058]
In trying to get the ldc package working on Android/x64 by testing it in Termux in the [Anbox container on linux/x64](https://anbox.io) (`termux-info` says its Android 7.1.1), I've run into this strange issue where `sprintf`/`printf` segfaults for certain `long double` input when trying to get it hex formatted.

Here's a two-line C file that reliably reproduces the issue for me:
```
#include <stdio.h>
int main() { printf("The square root of 2 is %LA\n", 1.414L);}
```
If I change the format to `%Lg`, it works, same if I change the number to 1.415 with the hex format. This isn't the only number that fails though, I had a couple other segfaults with other numbers. It works fine on Android/AArch64 (well, it doesn't segfault, the output string is wrong though) and even when compiled for 32-bit Android/x86 in the same Anbox container, though `long double` is half the size there.

What I'm looking for is someone to reproduce this on actual Android/x64 hardware, presumably a Chromebook, to see if this is just some Anbox incompatibility or reproducible there too.

To confirm, save the two lines to a source file `test.c`, install the clang package, compile, and run:
```
clang test.c -o test
./test
```
I get `Segmentation fault (core dumped)`, gdb shows it failed within `__hldtoa` from the Bionic libc.

**Comment by xeffyr** [comment]
On different OSes/libc's I'm getting different results:

1. Android/Termux, Bionic, AArch64:
```
$ cat /sdcard/test.c
#include <stdio.h>
int main() { printf("The square root of 2 is %LA\n", 1.414L);}
$ clang /sdcard/test.c -o test
$ ./test
The square root of 2 is 0X�.000000000000E76C8B43DD2F1AAP+0
$ uname -m
aarch64
```

2. Alpine Linux, Musl libc, x86_64:
```
[xeffyr]:~:$ gcc test.c -o test
[xeffyr]:~:$ ./test
The square root of 2 is 0X1.69FBE76C8B439582P+0
[xeffyr]:~:$ uname -m
x86_64
```

3. Arch Linux, GNU libc, x86_64:
```
xeffyr@archlinux-pc-xeffyr:~:$ cat test.c
#include <stdio.h>
int main() { printf("The square root of 2 is %LA\n", 1.414L);}
xeffyr@archlinux-pc-xeffyr:~:$ gcc test.c -o test
xeffyr@archlinux-pc-xeffyr:~:$ uname -m
x86_64
xeffyr@archlinux-pc-xeffyr:~:$ ./test
The square root of 2 is 0XB.4FDF3B645A1CAC1P-3
```

**Comment by joakim-noah** [comment]
BTW, how do you guys test command-line Termux packages on x86 and x64, actual hardware? It would be nice if there were a `qemu-user-bionic-x64` package that let me run command-line test binaries for Android/x64 on Android/AArch64, just as some run tests for Linux/glibc/AArch64 on Linux/glibc/x64 today using Qemu. Obviously I'd have to install any non-system libraries I need on my own, but it'd be much more convenient than having to spin up a linux/x64 VPS and Anbox when I need to test.

**Comment by xeffyr** [comment]
> BTW, how do you guys test command-line Termux packages on x86 and x64, actual hardware?

>  It would be nice if there were a qemu-user-bionic-x64

We use android emulator provided by SDK. For x86/x64, it has hardware acceleration so it's fast.

**Comment by gmkbenjamin** [comment]
Hi @xeffyr,
All your qemu package links are down. Is it still being maintained?

**Comment by xeffyr** [comment]
> All your qemu package links are down.

```
pkg install unstable-repo
pkg install qemu-system-x86_64-headless
```

**Comment by joakim-noah** [comment]
Closing, since not a Termux issue.
