### ISSUE TITLE
What about this static binary generator?

### ISSUE THREAD

**Issue by projectextremum** [termux/termux-packages#3063]
While static bins aren't going to work on android pie or newer, it will be still useful on systems up to android 8.

http://statifier.sourceforge.net/statifier

This is a beta version yet, though it is said to pack dynamic binaries to pseudo static ones, if I am not wrong. Also listed in FSF directory.

**Comment by xeffyr** [comment]
> While static bins aren't going to work on android pie or newer,

Static bins working and will work on Android **always** - it is not possible to enforce dynamic linking without having static for ELF executables. Binaries statically linked with GNU libc will work only if executed with proot.

> it will be still useful on systems up to android 8.
> pack dynamic binaries to pseudo static ones

What you are expecting from generating 'pseudo static' binaries ? If just for distributing them, don't forget that everything in Termux has binding to 'prefix' (/data/data/com.termux/files/usr) and regardless of static binary or not, it may not work properly.

While `statifier` can be added to Termux, I don't think that it will be useful for something other, than creating bundles for reusing Termux's packages in different applications, but even this purpose suffer from potential issues that can't be solved.

**Comment by projectextremum** [comment]
The description in the page creates the impression that it will be possible to copy an executable with all its dependencies and create a static standalone executable which then can be placed anywhere & executed. If it was possible, then one can simply repack a user app from a fedora / debian box and run it as static executable on android box.

In fact, I am sorry that I hadn't read that the project had support for x86, x86_64 only. Same issues with ul-exec rewrite I found)

**Comment by xeffyr** [comment]
> The description in the page creates the impression that it will be possible to copy an executable with all its dependencies and create a static standalone executable which then can be placed anywhere & executed.

Yes, it merges binary and it's libraries in special way. It works only with x86/x86_64. Though, it doesn't work properly. Just installed it on my PC and tested it on /bin/ls:
```
xeffyr@archlinux-pc-xeffyr:~/st_test:$ /bin/ls --version
ls (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard M. Stallman and David MacKenzie.
xeffyr@archlinux-pc-xeffyr:~/st_test:$ statifier --help
Usage: /usr/lib/statifier/statifier.sh [option]... <orig_exe> <new_exe>
Options:
   -h, --help                   display this help and exit
   -k, --keep-work-dir          do not remove working directory.
                                working dir will be .statifier instead of
                                $TMPDIR/statifier.tmpdir.$$
   -s, --set=Variable=Value     set environment variable 'Variable' to Value
   -u, --unset=Variable         unset environment variable 'Variable'
   -v, --verbose                verbose output
   -V, --version                output version and exit
xeffyr@archlinux-pc-xeffyr:~/st_test:$ statifier /bin/ls ls.static
/usr/lib/statifier/64/non_pt_load: warning: can't find segment with v_addr=0x0
/usr/lib/statifier/64/non_pt_load: warning: can't find segment with v_addr=0x4000
/usr/lib/statifier/64/non_pt_load: warning: can't find segment with v_addr=0x17000
/usr/lib/statifier/64/non_pt_load: warning: can't find segment with v_addr=0x21000
xeffyr@archlinux-pc-xeffyr:~/st_test:$ file /bin/ls
/bin/ls: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=0dd69c924e36ce85c93964d2364e645509dc82ea, stripped
xeffyr@archlinux-pc-xeffyr:~/st_test:$ file ls.static
ls.static: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, stripped
xeffyr@archlinux-pc-xeffyr:~/st_test:$ ./ls.static --version
Segmentation fault (core dumped)
```

As you can see, produced binary just not working. Seems because that modern systems has stack / vdso randomization.
