### ISSUE TITLE
Update to ubuntu 18.10 as officially supported build environment

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#3065]
aclocal-1.15 package is not installed after running setup-ubuntu.sh
Ubuntu cosmic(18.10).
```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/twaik/.termux-build/gtk3/src/build-aux/missing aclocal-1.15 -I m4 
/home/twaik/.termux-build/gtk3/src/build-aux/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:651: aclocal.m4] Error 127

```

**Comment by twaik** [comment]
Looks like 
sudo ln -s /usr/bin/aclocal-1.16 /usr/bin/aclocal-1.15
sudo ln -s /usr/bin/automake-1.16 /usr/bin/automake-1.15
fixed the problem.

**Comment by twaik** [comment]
This code inside build.sh fixed the problem. I think it should be added to termux_step_configure_autotools. 

    # fixing automake version mismatch
    cd ${TERMUX_PKG_SRCDIR}
    files=`find . -name configure -o -name config.status -o -name Makefile.in`
    for file in $files; do rm $file; done
    unset files

**Comment by fornwall** [comment]
Note that currently only Ubuntu 18.04 is officially supported (all packages available in the main package repo is built using the Docker image created by `scripts/Dockerfile`, which is using 18.04).

We should update, I'm updating the issue here to be about updating to use 18.10 as the reference build environment.

**Comment by fornwall** [comment]
The update to ubuntu 18.10 in the Docker image used as the official build environment is now done, and all packages build inside it. Run `scripts/update-docker.sh` to update a local setup.

If you encounter `'aclocal-1.15' is missing on your system` when building a custom package, running something like `./bootstrap.sh` or `./autogen.sh` should normally fix it.
