### ISSUE TITLE
Package Request: tvheadend

### ISSUE THREAD

**Issue by chapas** [termux/termux-packages#3066]
(or 'How can i compile it from source?')

**Comment by MCTyler** [comment]
Any update on this?

**Comment by MCTyler** [comment]
New Shield TV just released ...This would be SWEET!

**Comment by MCTyler** [comment]
![image](https://user-images.githubusercontent.com/6390898/67907186-2abf3500-fb45-11e9-9d47-3999bddbfe7c.png)

**Comment by leoncoolmoon** [comment]
any update?

**Comment by wsnake65** [comment]
Please add packege [tvheadend](https://github.com/tvheadend/tvheadend)
