### ISSUE TITLE
Suggestion: additional package directory for ./build-package.sh

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#3068]
To add external packages source, i.e x11-packages.

**Comment by fornwall** [comment]
Hello!

You may already build out of tree packages, as in like `./build-package.sh path/to/x11-packages/a-package`. So packages definitions can be maintained out of tree and still built using build-package.sh.

**Comment by twaik** [comment]
I guess you understood me wrong. I meant that it would be cool if you could add additional packages tree from $HOME/.termuxrc or using ./build-package.sh optargs. For now x11-packages repo copies all packages to termux-packages directory.
