### ISSUE TITLE
Suggestion: initial system for Termux

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#3071]
It will be needed to start HTTP/SSH/Pulseaudio server without typing comands in terminal, in auto mode.

**Comment by Grimler91** [comment]
What do you mean with "auto-mode" and "initial system" This sort of sounds like what you get when putting commands in ~/.profile, ~/.bashrc or when using a termux-boot script

**Comment by twaik** [comment]
I mean something like init.d. The init will be loaded during program start and start another programs listed somewhere in $TERMUX_PREFIX/etc/init.d. Program startup will be available to be modified from termux-app (settings or something simillar).

**Comment by cswl** [comment]
init.d has been long gone in desktop..  with systemd replacing it  

But I belive.. what you are asking is a daemon manager..  which is called "Services" now in systemctl
It handles starting stopping, restarting and dependencies..

While a full blown "Services" port from systemd  would be overwhelming

A minimal one to start, stop, restart, would be nice... bonus if we can add dependency

**Comment by twaik** [comment]
Looks like you understood me ) Init.d can start and stop services and that is the exact what is needed. With that feature you wont need to start sshd or apache on every reboot, they will be executed automatically. GUI for that feature is optional.

**Comment by cswl** [comment]
I havent used it but there is Termux Boot `https://wiki.termux.com/wiki/Termux:Boot` 
Which runs your scripts in ` ~/.termux/boot/ `

So its not hard to start thing as boot.. 

An Shortcut in Home Screen to start/stop and provide Toast notifs however.. (which I belive require Intents)

And we lack a proper system to "start" and "stop" these services.. which could very well be bash scripts..  
Call it init.d or systemctl or upstart

**Comment by xeffyr** [comment]
Implemented in https://github.com/termux/termux-packages/pull/3460 via RunSV.
