### ISSUE TITLE
Ping not working!

### ISSUE THREAD

**Issue by T4P4N** [termux/termux-packages#3074]
```bash
> ping -c 5 www.google.com
PING www.google.com (172.217.166.68) 56(84) bytes of data.

--- www.google.com ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4023ms

> a
Welcome to Arch Linux in Termux!
Install a package: pacman -S package
More  information: pacman -[D|F|Q|R|S|T|U]h
Search   packages: pacman -Ss query
Upgrade  packages: pacman -Syu

Chat: https://webchat.freenode.net/ #termux
Help: info query and man query
IRC:  wiki.archlinux.org/index.php/IRC_channel

[21:41 home ]$ ping -c 5 www.google.com
PING www.google.com(bom05s11-in-x04.1e100.net (2404:6800:4009:809::2004)) 56 data bytes
64 bytes from bom05s11-in-x04.1e100.net (2404:6800:4009:809::2004): icmp_seq=1 ttl=55 time=69.3 ms
64 bytes from bom05s11-in-x04.1e100.net (2404:6800:4009:809::2004): icmp_seq=2 ttl=55 time=218 ms
64 bytes from bom05s11-in-x04.1e100.net (2404:6800:4009:809::2004): icmp_seq=3 ttl=55 time=87.0 ms
64 bytes from bom05s11-in-x04.1e100.net (2404:6800:4009:809::2004): icmp_seq=4 ttl=55 time=77.1 ms
64 bytes from bom05s11-in-x04.1e100.net (2404:6800:4009:809::2004): icmp_seq=5 ttl=55 time=79.2 ms

--- www.google.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 16ms
rtt min/avg/max/mdev = 69.324/106.217/218.482/56.415 ms
[21:41 home ]$
```
however, it is working fine termux arch, as we can see above^

**Comment by T4P4N** [comment]
ping6 is working

**Comment by xeffyr** [comment]
> Ping not working

Blame your device vendor (or ROM developer) then. We use a /system/bin/ping and can't do anything with it.

**Comment by fornwall** [comment]
@T4P4N Could you provide the output from running `termux-info`?

Also, could you check if running `env -i /system/bin/ping www.google.com` makes a difference?

**Comment by T4P4N** [comment]
```
> env -i /system/bin/ping www.google.com
PING www.google.com (172.217.163.100) 56(84) bytes of data.
^C
--- www.google.com ping statistics ---
63 packets transmitted, 0 received, 100% packet loss, time 62057ms

> termux-info
Updatable packages:
ffmpeg/stable 4.1 aarch64 [upgradable from: 4.0.2-1]
git/stable 2.19.2 aarch64 [upgradable from: 2.19.1-1]
mpd/stable 0.20.23-1 aarch64 [upgradable from: 0.20.23]
ncurses/stable 6.1.20181117 aarch64 [upgradable from: 6.1.20180707]
ncurses-dev/stable 6.1.20181117 aarch64 [upgradable from: 6.1.20180707]
ncurses-ui-libs/stable 6.1.20181117 aarch64 [upgradable from: 6.1.20180707]
ncurses-utils/stable 6.1.20181117 aarch64 [upgradable from: 6.1.20180707]
nnn/stable 2.0-1 aarch64 [upgradable from: 2.0]
openssh/stable 7.9p1-1 aarch64 [upgradable from: 7.9p1]
openssl/stable 1.1.1a aarch64 [upgradable from: 1.1.1-3]
openssl-dev/stable 1.1.1a aarch64 [upgradable from: 1.1.1-3]
openssl-tool/stable 1.1.1a aarch64 [upgradable from: 1.1.1-3]
System information:
Linux localhost 3.18.31-perf-g9f3facd #1 SMP PREEMPT Tue Aug 28 13:33:11 WIB 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.1.2
Device manufacturer:
Xiaomi
Device model:
Redmi 4A
>
```

**Comment by T4P4N** [comment]
@xeffyr yes, $PREFIX/bin/ping points to system one, and system one is broken i think!

**Comment by T4P4N** [comment]
I reported the bug to developers
hope they will fix it

**Comment by darkquake93** [comment]
Sorry I know this is old, but I got it working on the system ping. You have to specify a Packet size of 32 for it to work (I noticed the difference compared to a standard ping from my Windows machine) :)
![Screenshot_20200419-153310_Termux](https://user-images.githubusercontent.com/8112825/79690679-914f2100-8253-11ea-854c-eae1a9e38222.jpg)

**Comment by ErSoul** [comment]
Exactly same problem on my device. Pitty that it is a vendor problem...

My _termux-info_ output:

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
tmux/stable 3.1b-2 aarch64 [upgradable from: 3.1b-1]
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf #1 SMP PREEMPT Fri Jun 2 15:23:03 CST 2017 aarch64 Android
Device manufacturer:
ZTE
Device model:
ZTE BLADE V8 MINI
```

**Comment by alexmercer13578** [comment]
And the same with me.
I can't ping to www.baidu.com, just as you ping to www.google.com
and there's my termux-info
`Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
busybox/stable 1.32.0-2 aarch64 [upgradable from: 1.32.0-1]
libandroid-support/stable 28 aarch64 [upgradable from: 26]
Android version:
9
Kernel build information:
Linux localhost 4.9.148 #1 SMP PREEMPT Sat Oct 19 10:20:47 CST 2019 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
BND-AL10
`

**Comment by alexmercer13578** [comment]
and the same with me.
I can't ping to www.baidu.com, just as you ping to www.google.com
there's my termux-info:
> Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
busybox/stable 1.32.0-2 aarch64 [upgradable from: 1.32.0-1]
libandroid-support/stable 28 aarch64 [upgradable from: 26]
Android version:
9
Kernel build information:
Linux localhost 4.9.148 #1 SMP PREEMPT Sat Oct 19 10:20:47 CST 2019 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
BND-AL10

**Comment by alexmercer13578** [comment]
And the same problem with me.
I can't ping to www.baidu.com, just as you ping to www.google.com
there's my termux-info:

> Packages CPU architecture:
aarch64
Subscribed repositories:
\# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
\# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
\# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
busybox/stable 1.32.0-2 aarch64 [upgradable from: 1.32.0-1]
libandroid-support/stable 28 aarch64 [upgradable from: 26]
Android version:
9
Kernel build information:
Linux localhost 4.9.148 #1 SMP PREEMPT Sat Oct 19 10:20:47 CST 2019 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
BND-AL10
