### ISSUE TITLE
Suggesiton: rename some libs after compiling to prevent collisions while executing system soft.

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#3078]
For example we can rename liblzma after make and modify lzma.pc file. That should not affect Termux apps but it will let us execute some system soft from Termux.

**Comment by mittorn** [comment]
For example, running any system executable linked with libunwind results in this error:
```
CANNOT LINK EXECUTABLE "/system/bin/dumpsys": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
Aborted
```

**Comment by xeffyr** [comment]
There no problems with renaming libraries, but this will have an impact on building programs from source that don't use pkg-config.

On Android 7 or higher it may be solved with `DT_RUNPATH`.

**Comment by twaik** [comment]
> but this will have an impact on building programs from source that don't use pkg-config.

termux-packages can patch programs like these to link to libraries with modified names.

**Comment by xeffyr** [comment]
@twaik I'm about if user will build program in Termux (on-device). Not in termux-packages.

**Comment by tomty89** [comment]
@mittorn 
```
$ /system/bin/dumpsys
CANNOT LINK EXECUTABLE "/system/bin/dumpsys": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib64/libunwind.so"...
Aborted
$ LD_PRELOAD=/system/lib64/liblzma.so /system/bin/dumpsys |& head
Currently running services:
  SurfaceFlinger
  accessibility
  account
  activity
  alarm
  android.security.keystore
  android.service.gatekeeper.IGateKeeperService
  appops
  appwidget
$
```

Actually, building versioned liblzma might be a less aggressive alternative. Most programs/libraries (if not all) should then have a versioned linkage. Not only this allows at least indirect linkage to both liblzma (e.g. mpv to libarchive *and* libOpenSLES), the unversioned symlink should be removable for most of the time. We might be able to have it in the `-dev` package then.

**Comment by xeffyr** [comment]
Fixed by android-7 package repository. Specifically, by `DT_RUNPATH` and versioned symbols.
