### ISSUE TITLE
package request - android-libcutils-dev

### ISSUE THREAD

**Issue by brubakerjeff** [termux/termux-packages#3086]

**Comment by xeffyr** [comment]
See https://github.com/termux/termux-packages/issues/3087#issuecomment-441425469.

**Comment by xtkoba** [comment]
The shared library `libandroid-cutils.so` is included in `aapt` package. Public headers are not packaged for some reason, but they are available at <a href="https://android.googlesource.com/platform/system/core/+archive/refs/tags/android-12.0.0_r27/libcutils/include.tar.gz">android.googlesource.com</a> (to avoid API mismatch align the tag with the one used in `aapt` package).

**Comment by twaik** [comment]
We prefer to not package library-only packages if not programs demand them. In the case if you need program that uses `libandroid-cutils` you should post package request for this program, not for the library.
