### ISSUE TITLE
Nodejs has 2 active lts, can you make it in termux please.

### ISSUE THREAD

**Issue by GwNih** [termux/termux-packages#3089]
according to [Nodejs Release Plan](https://github.com/nodejs/Release#release-schedule), thereis 2 active LTS version (actualy v8 and v10). But in termux, you only provide latest LTS version (v8).

Can you provide Nodejs v10 (latest active LTS) to termux please. May be you can add new package as nodejs-current-lts or something else.

**Comment by tomty89** [comment]
Maybe we should just upgrade our `nodejs-lts` to v10...

**Comment by GwNih** [comment]
I think some people still use v8, so its better if we have 2 LTS version

**Comment by fornwall** [comment]
The `nodejs-lts` package has been updated to v10. I don't think there is much value in supported v8 as well as a third nodejs package (but anyone interested is welcome to maintain it as a third-party repo)!
