### ISSUE TITLE
travis ci ruby gem results in segmentation fault when running

### ISSUE THREAD

**Issue by samos123** [termux/termux-packages#309]
Steps to reproduce:
1. apt install ruby ruby-dev gcc make
2. gem install travis -v 1.8.2 --no-rdoc --no-ri

Current result:
Running travis ci results in a segmentation fault. See strace log in attachment.
[log.txt](https://github.com/termux/termux-packages/files/307056/log.txt)

$ travis version
[1]    30611 segmentation fault  travis version

**Comment by fornwall** [comment]
There was an issue with ELF files being stripped incorrectly, which caused errors when linking to them.

This has now been fixed, update with:

    apt update && apt upgrade

After updating packages, one also needs to rebuild all gems with native extensions. Easiest is to uninstall all gems (`gem uninstall -aIx`)  and then install again (`gem install travis -v 1.8.2 --no-rdoc --no-ri`).

Let me know if the problem persists after updating packages and rebuilding gems.
