### ISSUE TITLE
Apt and ssh:// not working due to the way apt is being patched

### ISSUE THREAD

**Issue by rpil2** [termux/termux-packages#3093]
Using apt with ssh:// sources doesnt work - I think the patch at https://github.com/termux/termux-packages/blob/master/packages/apt/methods-rsh.cc.patch should be removed. I think the patch is telling apt to yry and execute 

/data/data/com.termux/files/usr/bin/sh 

on the ssh server. 

That is unlikely to work unless the remote server happens to be runnning termux..?

When i try and use a ssh:// line in sources.list i get

sh: 1: /data/data/com.termux/files/usr/bin/sh not found
Killed by signal 2.

**Comment by fornwall** [comment]
Thanks, sounds reasonable!

Should be fixed in version `1.4.8-7` of the apt package - update to it with `pkg up` and let me know if there are any problems!
