### ISSUE TITLE
Is this Termux Error

### ISSUE THREAD

**Issue by Wjsfj51najdk** [termux/termux-packages#3094]
I tried to install kalinethunter in termux

**Comment by Wjsfj51najdk** [comment]
![screenshot_2018-11-28-00-59-17-788_com termux](https://user-images.githubusercontent.com/43841067/49103093-dbbfae80-f2a8-11e8-8036-c38fc292da49.png)

**Comment by xeffyr** [comment]
It's just NetHunter's admin forgot that Let's Encrypt certificates expire after 90 days.

**Close this issue as it is not Termux-related.**

![2018-11-27 20-30-51](https://user-images.githubusercontent.com/25881154/49103264-845b1780-f283-11e8-9b1a-317dc1735c57.png)

![2018-11-27 20-36-47](https://user-images.githubusercontent.com/25881154/49103547-4d393600-f284-11e8-8086-16d0b3756995.png)
