### ISSUE TITLE
Pyrhon import cv2 gives error:

### ISSUE THREAD

**Issue by nitanmarcel** [termux/termux-packages#3097]
I installed opencv on termux but when I try to import cv2 (not opencv - this works fine) I get this error:

ImportError: dlopen failed: cannot locate symbol "PyFloat_Type" referenced by "/data/data/com.termux/files/usr/lib/python3.7/site-packages/cv2.cpython-37m.so"...

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/1992

**Comment by nitanmarcel** [comment]
@Grimler91 I didn't understand much.. Is boost the problem? Because I already have it installed

**Comment by Grimler91** [comment]
@nitanmarcel No, the problem is that android's linker is different from the standard gnu/linux linker. You need to compile it and link against libpython3.so with something like 
```
LDFLAGS=" -llog -lpython3" cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_opencv_python3=on -DBUILD_opencv_python2=off -DWITH_QT=OFF -DWITH_GTK=OFF ..
```

**Comment by nitanmarcel** [comment]
Oh, ok.. Thanks

**Comment by YEDrekt** [comment]
I use Python 3.7.5 and installed opencv from its-useless' repo with `pkg install opencv`.

When I try to import opencv with `import cv2`, I get this error: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/cv2/__init__.py", line 89, in <module>
    bootstrap()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/cv2/__init__.py", line 79, in bootstrap
    import cv2
ImportError: dlopen failed: cannot locate symbol "_ZN6google8protobuf8internal14AddDescriptorsEPNS1_15DescriptorTableEPKPFvvEi" referenced by "/data/data/com.termux/files/usr/lib/libopencv_dnn`

Any idea about how to fix that?
