### ISSUE TITLE
dlib: file cannot create directory: /usr/local/lib64.  Maybe need administrative   privileges

### ISSUE THREAD

**Issue by nitanmarcel** [termux/termux-packages#3099]
Hi, I'm trying to install dlib on termux but I get this error during compiling:

file cannot create directory: /usr/local/lib64.  Maybe need administrative
  privileges

These are the commands I used to install it:

LDFLAGS=" -llog -lpython3" cmake ..
make install

**Comment by nitanmarcel** [comment]
Problem solved.. I had to use the termux root location and not / which is the phone root location if I'm not wrong.
All I had to do is to add CMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr to cmake

**Comment by nitanmarcel** [comment]
@xeffyr Oh, you replied when I closed it.. thanks it worked ^^

**Comment by nitanmarcel** [comment]
@xeffyr tho, this doesn't install the python version.. I've tried to install it but it says it can't find Python.Boost even if I installed for like 20 times with the zip from boost.org

Thanks

**Comment by Grimler91** [comment]
@nitanmarcel why are you using a zip from boost.org instead of our boost and boost-dev package?
