### ISSUE TITLE
how do i fix this 

### ISSUE THREAD

**Issue by gidget4gadget** [termux/termux-packages#3108]
Need to get 707 kB of archives.
After this operation, 2441 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Abort.
$

**Comment by Grimler91** [comment]
Does lower case "y" work?

**Comment by xeffyr** [comment]
@Grimler91 Both uppercase and lowercase are working and should work.

**Comment by xeffyr** [comment]
@Grimler91 This can be either invisible character (null ?) or invalid encoding.

I have reproduced this by inserting russian "У" then backspace and "Y". Seems that `apt` can't handle multibyte characters properly.

**Comment by xeffyr** [comment]
> the base for ths app is 10 GB

?
