### ISSUE TITLE
Handle cpan modules in build-package.sh

### ISSUE THREAD

**Issue by edanaher** [termux/termux-packages#311]
nix (#59) needs a couple Perl modules; for the moment I'm just doing `yes | cpan [modules] || true` in , but it would be nice to have a TERMUX_PACKAGE_CPAN or similar that installs a set of perl modules before configure.

**Comment by twaik** [comment]
Closing this because `cpan` is mentioned only in `dpkg`, `sendxmpp`, `intltool` and `xdg-utils` packages. Not enough to add special case in build system.
