### ISSUE TITLE
Json and `npm audit fix` 

### ISSUE THREAD

**Issue by gidget4gadget** [termux/termux-packages#3110]
npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2018-12-03T07_14_59_593Z-debug.log

**Comment by Grimler91** [comment]
Can't say anything about this without more information, like 

* what did you run?
* what's the full output?
* what's the output of `termux-info`?
* what's the content of the log mentioned in the error message?

Please edit to add more information.
