### ISSUE TITLE
SWI-Prolog officially announced

### ISSUE THREAD

**Issue by erlanger** [termux/termux-packages#3111]
**Update** : Official announcement here: http://www.swi-prolog.org/build/Termux.html

SWI-Prolog
---------------
Hi,

   Hot off the press: release 7.7.23 of SWI-Prolog is now working under termux with all tests passing. 

  We have been [working](https://github.com/SWI-Prolog/swipl-devel/issues/358) to get to this point for the past month or so. The [termux-packages fork](https://github.com/erlanger/termux-packages/) contains the `ossp-uuid` and the `swi-prolog` termux packages (`ossp-uuid` is required by SWI-Prolog).

Right now we are distributing the pre-built `.deb` files from another github repository, but would like to see SWI-Prolog included in the official termux package repository.

What is the proper way to submit SWI-Prolog to be included in the official termux repositories?

Thanks!

P.S. [Here](https://github.com/erlanger/swipl-termux) and [here](https://github.com/SWI-Prolog/swipl-devel/issues/358) for more information about the SWI-Prolog port to termux.

**Comment by Grimler91** [comment]
Hi, 

Cool, you can probably open a PR containing the build.sh and patches for SWI-Prolog and ossp-uuid against this repo, and use your [release-build.sh](https://github.com/erlanger/termux-packages/blob/swi-prolog/packages/swi-prolog/release-build.sh) as build.sh for SWI-Prolog. 

I have some minor comments/questions that can wait until a PR review :+1:

**Comment by Grimler91** [comment]
Great to hear that you've already tested the compilation for several arches already as well.

You can open a PR now and add that commit as a patch, with a note that it can be removed when 7.7.24 is available.

**Comment by erlanger** [comment]
Done! See PR #3129

**Comment by esad** [comment]
@erlanger Thanks for your effort to bring SWI-Prolog to Android! I just noticed that the termux package doesn't include documentation (also both help/1 and apropos/1 predicates are not defined in the top level). I guess the package was built with -DINSTALL_DOCUMENTATION=OFF. Maybe we could include documentation in future builds? Or maybe put it into a second packagelike `swi-prolog-docs`?

**Comment by erlanger** [comment]
Hi @esad,

   Yes, the decision was made because we want as small a package as possible, and you can  access the docs from a browser. I am not sure the termux maintainers would be open to having another package named `swi-prolog-docs`. 

However, you can easily rebuild it with the docs using the termux-package docker image.  It is very easy:
```sh                                                    
docker pull termux/package-builder 
git clone https://github.com/termux/termux-packages
cd termux-packages
# change -DINSTALL_DOCUMENTATION
./scripts/run-docker.sh ./build-package.sh -a <arch> -f swi-prolog
```
Where \<arch\> is your architecture (probably aarch64 or arm).

**Comment by erlanger** [comment]
@esad, 

   Good news, we have now included the docs in the termux version. As soon as the 8.1.14 files get built you should be able to use them. 
Enjoy!
