### ISSUE TITLE
npm install - cannot read property length of undefined

### ISSUE THREAD

**Issue by roccomuso** [termux/termux-packages#3114]
I had to use switch to `yarn`.

npm keeps returning `Cannot read property "length" of undefined` during a simple `npm install`.

**Comment by Grimler91** [comment]
See for example https://github.com/termux/termux-packages/issues/1798, you need to edit `$PREFIX/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js` and set maxConcurrentWorkers to the number of cpu cores (or 1)
