### ISSUE TITLE
tsudo cp --attributes-only --preserve=all -v test1/1 test2/1 not working

### ISSUE THREAD

**Issue by shyvalley** [termux/termux-packages#3119]
`tsudo cp --attributes-only --preserve=all -v test1/1 test2/1`
not working

i want to only change attibutes of files, but this command is not working on my android phone(HTC U11).
`tsudo cp --version`
show "cp (GNU coreutils) 8.30".

**Comment by Grimler91** [comment]
Where are you trying to do this?

**Comment by shyvalley** [comment]
> Where are you trying to do this?

hi，the copy source is in the internal storage, the dest is in the external storage(exfat format filesystem tf card).

**Comment by shyvalley** [comment]
I test again just now, it runs ok when the copy source and dest both in the internal storage, failed when
dest is in the external storage(exfat format).

**Comment by shyvalley** [comment]
just nonsupport to change attributs of files in the exfat file system or not implement yet?

**Comment by shyvalley** [comment]
> I guess android doesn't allow those file attributes in the external sdcard, so the same reason we can't have executable files in shared&external storage. Nothing we can do about this

thanks for your reply, i'll close this issue.
