### ISSUE TITLE
ssh through Tor: Network is down

### ISSUE THREAD

**Issue by Sweenu** [termux/termux-packages#3120]
Hello!
I followed [the wiki](https://wiki.termux.com/wiki/Remote_Access#Tor) on using ssh through Tor and have configured termux exactly the same way. I also have installed the `tor` and `torsocks` package through brew on mac.

I can ssh without tor without any problem but when I lanuch tor on both machines and try to:
`torsocks ssh my.onion` it results in `ssh: connect to host my.onion port22: Network is down`.

Running `torsocks telnet my.onion 22` gives me the following:
```
Trying 127.42.42.0...
Connected to my.onion.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.9
```

Do you happen to have any clue on why this could be happening?

**Comment by Sweenu** [comment]
SSH gives: `Network is down` though and does not work though 
I already disabled System Integrity Protection for another application I use so that cannot be the problem

**Comment by xeffyr** [comment]
I wrote this tutorial and tested it on both Termux & Arch Linux (PC).

With telnet you got output `SSH-2.0-OpenSSH_7.9` which means that connection over tor is estabilished and working. So on Termux side (server) everything is okay. Only client side left.

Also, what's point of using ssh over tor for LAN connection ?

**Comment by Sweenu** [comment]
Do you have any special configuration for the client side? or do you just run `tor`? 
I don't plan to use it for a LAN connection ^^

**Comment by xeffyr** [comment]
No, default tor's configuration fine. The only question here is why `torsocks` works for telnet but not for ssh.

**Comment by Sweenu** [comment]
I know right, this is very weird, I don't really know what Network is down means and -vvv does not help...

**Comment by xeffyr** [comment]
> I don't really know what Network is down means

I don't know too. Torsocks seems intercepted connection, otherwise you will see `Name or service not known` instead of `Network is down`.

If you decide to try via openbsd netcat, you can use this command (from Tor wiki):
```
ssh -o "ProxyCommand nc -X 5 -x 127.0.0.1:9050 %h %p" <target_host>
```

**Comment by Sweenu** [comment]
So the avbove command gives me:
```
We tried for 15 seconds to connect to '[scrubbed]' using exit $B84F248233FEA90CAD439F292556A3139F6E1B82~tollana at 85.248.227.164. Retrying on a new circuit.
```
in the logs of the tor client (the macbook) and tries with other circuits without succeeding.

I tried the original command from another network and now I got something else.
The output is:
```
$ torsocks telnet my.onion 22 
ERROR torsocks[62169]: General SOCKS server failure (in socks5_recv_connect_reply() at socks5.c:533)
telnet: connect to address 127.42.42.0: Connection refused
telnet: Unable to connect to remote host
```
And in the logs of the tor client:
```
[warn] Fetching v2 rendezvous descriptor failed. Retrying at another directory.
[warn] Fetching v2 rendezvous descriptor failed. Retrying at another directory.
[notice] Closing stream for '[scrubbed].onion': hidden service is unavailable (try again later).
```

**Comment by daweedkob** [comment]
The same problem does someone found the solution to?

**Comment by xeffyr** [comment]
@daweedkob Use proxychains-ng instead of torsocks.
