### ISSUE TITLE
Segmentfault

### ISSUE THREAD

**Issue by myfreess** [termux/termux-packages#3121]
apk
CANNOT LINK EXECUTABLE "apk": cannot locate symbol "ENGINE_load_builtin_engines" referenced by "/data/data/com.termux/files/usr/bin/apk"...
Aborted

**Comment by Grimler91** [comment]
From where did you install "apk"? 
It isn't available in the termux-packages repo AFAIK

**Comment by fornwall** [comment]
@Grimler91 It's actually available in the `apk-tools` package added recently, to experiment with using that package format.

@myfreess Run `pkg up`  to update all your packages (it seems you have an outdated openssl package).

**Comment by vladkras** [comment]
I had to clear all cache, data and reinstall app to fix it
