### ISSUE TITLE
Package Request: Nightly Rust

### ISSUE THREAD

**Issue by pycadelic** [termux/termux-packages#3122]
I'm stuck trying to install vim-racer, which needs racer, which needs nightly.

With the termux package of rust (pkg install rust), cargo +nightly install racer claims that there is no such subcommand.

I'm new to rust and from looking around rustup would be the next step, it seems, but the termux package doesn't install it.

Would it be possible, then, to provide a build of nightly rust ?

**Comment by its-pointless** [comment]
I provide a nightly build. You just have to ad my apt repo from [Here](https://wiki.termux.com/wiki/Package_Management#By_its-pointless_.28live_the_dream.29)

**Comment by pycadelic** [comment]
Got it. Thanks!

**Comment by shnorbluk** [comment]
Hi! I have the same request. I would like to get code completion in vim. Could you please provide a package for rust-racer? Because even after installing rustc-nightly from its-pointless repository, the command "cargo +nightly install racer" does not work.
I must install an older version with "cargo install --version 2.0.13 racer" and then "export PATH=$PATH:~/.cargo/bin/"

**Comment by its-pointless** [comment]
easiest solution would be for me to use a more recent nightly. Right now that is a bit tricky for a couple of reasons 1st of which is suddenly nightly std libs are now 2x the size so packaging it for distribution is a bit of an issue and then  llvm 8.0.1 will be released soonish which would mean reupping a new version again ... 
so i am going to have to think about how i approach this.

**Comment by shnorbluk** [comment]
Thank you but I haven't understand everything actually ;-) You prefer waiting llvm 8.0.1.
In the meanwhile, I managed to use the older version in vim by adding to my ~/.vimrc: `let g:racer_cmd = "/data/data/com.termux/files/home/.cargo/bin/racer"
let $RUST_SRC_PATH = "/data/data/com.termux/files/usr/lib/rustlib/src/rust/src"`
