### ISSUE TITLE
libdl.so.2 request

### ISSUE THREAD

**Issue by teamclouday** [termux/termux-packages#3123]
I recently tried to install YouCompleteMe plugin in Vim.
But the ycmd server stopped because `libdl.so.2` is not found
How can I get libdl.so.2 installed?

**Comment by Grimler91** [comment]
Your android rom provides libdl.so in /system/lib so might work if you just tell vim to look there.
I don't use vim though so I don't know how to accomplish this (might mean compiling the plugin from source and changing a compiler flag)

**Comment by xeffyr** [comment]
Yes, libdl.so is in /system/lib (lib64).
But `libdl.so.2` is part of glibc which can't be available for Termux.

**Comment by teamclouday** [comment]
Thanks for your reply, I will try to configure it!

**Comment by hnmn** [comment]
@teamclouday any progress

**Comment by xeffyr** [comment]
> any progress

@hnmn No progress as **wontfix**. See https://github.com/termux/termux-packages/issues/3123#issuecomment-445055883.
