### ISSUE TITLE
'git clone ...' unable to fork

### ISSUE THREAD

**Issue by bbtdev** [termux/termux-packages#3134]
Hi,
I'm lost with this issue.
So basically, I want to clone a public repo:

```
$ git clone git@github.com:Shougo/dein.vim.git
Cloning into 'dein.vim'...
fatal: unable to fork
```
This happens with any repo.

**Comment by Grimler91** [comment]
Do you have openssh installed?

`git@` uses the ssh so you need to have openssh installed.

**Comment by bbtdev** [comment]
@Grimler91 damn, it did not cross my mind to check :(
Works now, thank ypu

**Comment by LeiYangGH** [comment]
doesn't git installation automatically embed/require openssh?
