### ISSUE TITLE
Debian's AptPkg

### ISSUE THREAD

**Issue by alxpettit** [termux/termux-packages#3135]
This Perl module is not already in CPAN, and probably won't ever be added. (It's part of the Debian project.) Prerequisite for #319

**Comment by Grimler91** [comment]
I have something that almost work over at https://github.com/Grimler91/termux-packages/tree/command-not-found, it fails if building for several arches without rebuilding perl in between. 

Cross-compiling perl modules is annoying, we probably want to add a `termux_setup_perl` function to build-package.sh.

**Comment by landfillbaby** [comment]
just added `libapt-pkg-perl` and `apt-file` :)
