### ISSUE TITLE
Package request: qrencode

### ISSUE THREAD

**Issue by woodnt** [termux/termux-packages#3137]

**Comment by woodnt** [comment]
We have the libraries for qrencode but not qrencode itself. Trying a pip install results in:

unable to execute 'arm-linux-androideabi-clang': No such file or directory
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-bzqwadjw/qrencode/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-7_ox0_5c/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-bzqwadjw/qrencode/

Even with clang installed.

**Comment by Grimler91** [comment]
Have you installed the header files in libqrencode-dev?

**Comment by xeffyr** [comment]
> We have the libraries for qrencode but not qrencode itself.

We have the libraries and utility for qrencode.
```
$ dpkg -L libqrencode | grep /bin/
/data/data/com.termux/files/usr/bin/qrencode
```
