### ISSUE TITLE
 Package request: ncmpcpp

### ISSUE THREAD

**Issue by soredake** [termux/termux-packages#314]

**Comment by mklein994** [comment]
Note that this requires the [boost](https://www.boost.org) library, which isn't yet available for Termux. @soredake you should really add a description for this.

**Comment by fornwall** [comment]
Link: https://rybczak.net/ncmpcpp/
Description: featureful ncurses based MPD client inspired by ncmpc

I guess MPD (https://www.musicpd.org/) needs to be added first.

**Comment by mklein994** [comment]
Not necessarily; **M**usic **P**layer **D**aemon is the server, ncmpcpp is just a client. Let's say I have MPD running on a computer whose IP address is 192.168.0.2, I could just run `ncmpcpp -h 192.168.0.2` to control the music on that computer.

**Comment by fornwall** [comment]
@mklein994 Ah, true!

**Comment by Neo-Oli** [comment]
Both Ncmpcpp and mpd are available now.

**Comment by atomi** [comment]
ncmpc is a lot more stable ime.
