### ISSUE TITLE
Emacs: Hunspell 1.7 needs a patch to work

### ISSUE THREAD

**Issue by Bridouz** [termux/termux-packages#3140]
Hi,

`hunspell` 1.7 introduced a bug in `ispell` use for now (patched upstream but not for `26.1`).

Is it possible to add this patch in termux emacs, thanks.

Patch is available [here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=33493)

**Comment by Grimler91** [comment]
Hi, adding a patch should be no problem. Could you update the (forgotten?) link to the patch?

**Comment by Grimler91** [comment]
Closing now that #3141 has been merged

**Comment by fornwall** [comment]
This is now available in version `26.1-2` of the emacs package, which is available for installation.
