### ISSUE TITLE
parsing termux-dialog return values

### ISSUE THREAD

**Issue by millermj1** [termux/termux-packages#3142]
Termux-dialog returns values in what appears to be json format, e.g.
`{
   "code": "-1",
   "text": "red",
   "index": "0"
}
 `
What's the best way to parse this in Termux: bash/grep, jq, or something else?

More generally, is there a collection of sample scripts that use termux-dialog?  I'd be happy to contribute to such a collection, as having samples would make coding easier for new users.

Thanks!

**Comment by xeffyr** [comment]
> What's the best way to parse

Best way to parse JSON in bash is **jq**.
Python has a json module in it's stdlib.

> is there a collection of sample scripts that use termux-dialog

Perhaps no. But you can always create one.
