### ISSUE TITLE
Please help me, Backup file

### ISSUE THREAD

**Issue by foodmaher** [termux/termux-packages#3144]
I want work backup of termux all files from path /data/data/com.termux/files/home/* .... 

without copying file storage >> sdcard external

How he did it ? ... please answer me 😟😟

**Comment by Atavic** [comment]
Seems like he wants to copy the content from path into internal file storage.

**Comment by xeffyr** [comment]
>I want work backup of termux all files from path /data/data/com.termux/files/home/* ....

> Seems like he wants to copy the content from path into internal file storage.

That should be easy.
```
tar -cvf /sdcard/home.tar $HOME
```

**Comment by foodmaher** [comment]
@xeffyr @Atavic 
# Thank you ....
       
      I made a dialog box showing the progress of the tar tool. Will it work with it when backing up the home folder?
