### ISSUE TITLE
Termux does not have a shadow file and related header files?

### ISSUE THREAD

**Issue by Droid-MAX** [termux/termux-packages#3146]
When I compiled the rtty client under termux, I got this error.

![s81216-21230328](https://user-images.githubusercontent.com/12762435/50077453-6a2bae00-021f-11e9-8135-91fdfbf2eccc.jpg)

**Comment by xeffyr** [comment]
Termux is Android. There no "shadow.h".

**Comment by Droid-MAX** [comment]
How can I fix this error?

**Comment by xeffyr** [comment]
You can't. As termux/android doesn't support such features. As workaround, you will have to remove all shadow-related stuff.

**Comment by Droid-MAX** [comment]
Ok, let it go
