### ISSUE TITLE
Add special keys above keyboard

### ISSUE THREAD

**Issue by colbycdev** [termux/termux-packages#3149]
Add keys such as Ctrl, alt, esc, etc above standard virtual keyboard.

**Comment by xeffyr** [comment]
Already added.
https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by colbycdev** [comment]
Let me rephrase: make it easily accessible

**Comment by Grimler91** [comment]
Closing as we already have an extra keys row
