### ISSUE TITLE
Ssh server

### ISSUE THREAD

**Issue by danielmeneses** [termux/termux-packages#315]
Hi,
After following the steps for installing ssh when i try to ssh into termux it requests me a password. Dont have no idea what's the problem any help will be welcome.. thanks

**Comment by Neo-Oli** [comment]
Termux doesn't support password authentication. You need to log in with a private/public keypair.
Read the "Adding your private key" section of this tutorial:
https://oliverse.ch/tech/2015/11/06/run-an-ssh-server-on-your-android-with-termux.html

If you've done this and it still asks you for a passwort it means something is still wrong. There's a "If it still doesn’t work" section in the tutorial as well that shows you how to debug this.

**Comment by fornwall** [comment]
I've now updated the `$PREFIX/etc/ssh/sshd_config` configuration file to disable password authentication completely (`PasswordAuthentication no`), to avoid showing the password prompt if a key is not available.

**Comment by danielmeneses** [comment]
Nice @fornwall. I've done the same on my $PREFIX/etc/ssh/sshd_config and also created the key pair and everything works fine.
thanks again!

**Comment by githubluv** [comment]
https://oliverse.ch/tech/2015/11/06/run-an-ssh-server-on-your-android-with-termux.html
is dead.   Should be
https://glow.li/technology/2015/11/06/run-an-ssh-server-on-your-android-with-termux/

**Comment by Neo-Oli** [comment]
@githubluv Thanks I updated my comment to avoid confusion. (Sorry I broke permalinks when switching website builder
