### ISSUE TITLE
Busybox's netcat can't use -e on xconnect

### ISSUE THREAD

**Issue by architek** [termux/termux-packages#3153]
Hello,

The following command doesn't work on busybox:
nc 192.168.1.1 4242 -e /bin/sh
It simply shows usage of the busybox nc command.

But this command should be correct.
For information, it does work on other busybox (linux or android and even older ones)
Arch is aarch64 and this is termux uptodate from google play.

The bug report was initially wrongly raised in termux/termux-app#953 (now closed)
Thank you

**Comment by xeffyr** [comment]
Considering as a bug since busybox with same config works on PC as expected.

**Comment by mahesh-hegde** [comment]
showing usage means the option wasn't interpreted, perhaps.

**Comment by xeffyr** [comment]
@mahesh-hegde Question was about difference SAME busybox versions with SAME config. This normally shouldn't happen and point on hidden compilation bug (like in https://github.com/termux/termux-packages/issues/3216).

**Comment by fornwall** [comment]
The updated package is now available for installation - update by running `pkg up`!

**Comment by architek** [comment]
Thanks a lot!
Confirm it works as expected.
