### ISSUE TITLE
screen throws "Bad system call" on Android Pie

### ISSUE THREAD

**Issue by feklee** [termux/termux-packages#3156]
Just updated my Xiaomi Mi A2 to Pie. Now when I call `screen` with a config file, it fails:

    $ echo >.screenrc
    $ screen
    [...]
    Bad system call

Output of `logcat`: [logcat.txt](https://github.com/termux/termux-packages/files/2698342/logcat.txt)

I understand that similar issues have been reported with other tools and related to Pie. Let me know how I can help to get this resolved.

**Comment by unidevel** [comment]
Same issue on my MI MAX3 with android P

**Comment by fornwall** [comment]
This should now be fixed in version `4.6.2-1` of the screen package - run `pkg up` to update.

Thanks for reporting!

**Comment by VRuzhentsov** [comment]
@fornwall Cant use nodejs `npm` package
![image](https://user-images.githubusercontent.com/4579833/55409690-227d2800-556b-11e9-949b-155d244dbf94.png)

**Comment by mityok** [comment]
Getting the same "Bad system call" error on fresh install on Pixel XL2 Android 9

**Comment by Grimler91** [comment]
@mityok @VRuzhentsov see https://github.com/termux/termux-packages/issues/3608
