### ISSUE TITLE
ecj Aborted

### ISSUE THREAD

**Issue by fajarnurp** [termux/termux-packages#3157]
i try to compile java to get the "Test.class" file but the process is aborted
```
$ ecj Test.java
Aborted
$
```
how to fix them.?

**Comment by Grimler91** [comment]
What's the output of `termux-info` and which ecj package are you using, ecj or ecj4.6?

**Comment by fajarnurp** [comment]
@Grimler91 
```
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.65-7296443 #2 SMP PREEMPT Fri Feb 19 19:53:54 KST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.1.1
Device manufacturer:
samsung
Device model:
SM-J320M
$
```
 im using ecj

**Comment by Grimler91** [comment]
@fajarnurp Try with ecj4.6 instead, it is compatible with android 5 and 6 (and that package is provided for that reason) while ecj is for newer android versions

**Comment by fajarnurp** [comment]
I tried it but the results are the same.
```
$ ls
Test.java  storage
$ cat Test.java
public class Test {
    public static void main(String[] args) {
        System.out.println("Gua Gans");
    }
}
$ ecj Test.java
Aborted
$
```

**Comment by xeffyr** [comment]
Can be related to https://github.com/termux/termux-packages/issues/2652. On some devices with Android 5.x/6.x it is necessary to have exported variable `BOOTCLASSPATH`, otherwise java-related things are not working.

Try:
```
for lib in $(find /system/framework -type f -iname \*.jar); do
    BOOTCLASSPATH=${lib}:${BOOTCLASSPATH};
done
BOOTCLASSPATH=${BOOTCLASSPATH%%:}
export BOOTCLASSPATH
```

But without logcat output it's impossible to say exactly why `ecj` errored.

**Comment by lugslab** [comment]
Thanks, this worked for me :+1:

**Comment by xeffyr** [comment]
Should be fixed by https://github.com/termux/termux-app/commit/5fa4f2647b72eb4ed1bb468171e5763d11abbcf3.

**Comment by rien333** [comment]
I'm on Android 10, and for some reason I also see this. Any call to `ecj` just outputs "aborted". termux and my termux installed pkgs are up-to-date.  

Updating the `BOOTCLASSPATH` manually doesn't seem to work (for some reason, it is empty for me initially):
```bash
for lib in $(find /system/framework -type f -iname \*.jar); do
    BOOTCLASSPATH=${lib}:${BOOTCLASSPATH};
done
BOOTCLASSPATH=${BOOTCLASSPATH%%:}
export BOOTCLASSPATH
```

```console
$ echo $BOOTCLASSPATH
/system/framework/org.lineageos.platform.jar:/system/framework/ethernet-service.jar:/system/framework/hid.jar:/system/framework/input.jar:/system/framework/locksettings.jar:/system/framework/wifi-service.jar:/system/framework/com.google.android.media.effects.jar:/system/framework/com.google.android.dialer.support.jar:/system/framework/com.android.location.provider.jar:/system/framework/ext.jar:/system/framework/monkey.jar:/system/framework/android.hidl.manager-V1.0-java.jar:/system/framework/bu.jar:/system/framework/bmgr.jar:/system/framework/voip-common.jar:/system/framework/uiautomator.jar:/system/framework/am.jar:/system/framework/ims-common.jar:/system/framework/content.jar:/system/framework/org.apache.http.legacy.jar:/system/framework/sm.jar:/system/framework/telecom.jar:/system/framework/media.jar:/system/framework/appwidget.jar:/system/framework/com.android.future.usb.accessory.jar:/system/framework/android.test.mock.jar:/system/framework/dpm.jar:/system/framework/services.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/telephony-ext.jar:/system/framework/vr.jar:/system/framework/android.test.base.jar:/system/framework/requestsync.jar:/system/framework/com.android.mediadrm.signer.jar:/system/framework/javax.obex.jar:/system/framework/tcmclient.jar:/system/framework/com.google.android.maps.jar:/system/framework/svc.jar:/system/framework/com.android.media.remotedisplay.jar:/system/framework/ims-ext-common_system.jar:/system/framework/android.test.runner.jar:/system/framework/telephony-common.jar:/system/framework/framework.jar
$ ejc -h
Aborted
```

**Comment by xeffyr** [comment]
> termux and my termux installed pkgs are up-to-date.
> for some reason, it is empty for me initially

Are you sure that your Termux app is up to date ? All recent versions set BOOTCLASSPATH by default.

What app version you have and what's your output of `env` (make sure that nothing is altered by bashrc or similar scripts) ?

It also better to post output of `logcat` obtained immediately after `ecj` crash.

**Comment by rien333** [comment]
> Are you sure that your Termux app is up to date ? 

In the settings app, termux is listed as being version 0.84 (I installed it from the play store). I only got this device a few days ago, anyway.

> All recent versions set BOOTCLASSPATH by default.

Yeah, weird. I'm using fish shell as my default shell if that matters. 

My `env` (from bash, I haven't messed with bashrc as I don't use bash):
```console
$ env
SHELL=/data/data/com.termux/files/usr/bin/fish
PREFIX=/data/data/com.termux/files/usr
PWD=/data/data/com.termux/files/home
LOGNAME=u0_a147
EXTERNAL_STORAGE=/sdcard
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
HOME=/data/data/com.termux/files/home
LANG=en_US.UTF-8
TMPDIR=/data/data/com.termux/files/usr/tmp
SSH_CONNECTION=192.168.2.69 53232 192.168.2.101 8022
ANDROID_DATA=/data
TERM=xterm-kitty
USER=u0_a147
SHLVL=2
ANDROID_ROOT=/system
SSH_CLIENT=192.168.2.69 53232 8022
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
SSH_TTY=/dev/pts/1
_=/data/data/com.termux/files/usr/bin/env
```

> It also better to post output of logcat obtained immediately after ecj crash.

Will do that in a bit.

**Comment by xeffyr** [comment]
Just noticed that missing BOOTCLASSPATH is app bug.

**Comment by rien333** [comment]
> Log is needed anyway because on most devices ecj works without that variable.

`abd logcat` after running `ecj -h`:

https://0x0.st/znED.txt

Although I have no other noticeable problems after extensively using my device, I am running an unofficial LineageOS nightly, so it might be something unfixable on termux's end.

**Comment by xeffyr** [comment]
> https://0x0.st/znED.txt
01-05 11:39:08.869  6311  6311 E ICU     : ANDROID_TZDATA_ROOT environment variable not set  01-05 11:39:08.869  6311  6311 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6311 (main), pid 6311 (main)

@rien333 Your error happens due to another environment variable missing - `ANDROID_TZDATA_ROOT`.

Try
```
export ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
```
ANDROID_RUNTIME_ROOT may be required too:
```
export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
```

**Comment by rien333** [comment]
@xeffyr All right, setting both `ANDROID_TZDATA_ROOT` and `ANDROID_RUNTIME_ROOT` made it work, thanks!
