### ISSUE TITLE
groff - CANNOT LINK EXECUTABLE "groff": cannot locate symbol "_Unwind_Resume"

### ISSUE THREAD

**Issue by rendiix** [termux/termux-packages#3163]
![screenshot_2018-12-22-18-29-54-387_com termux](https://user-images.githubusercontent.com/16639978/50373952-beb49c00-0618-11e9-938c-fc68557b6ddd.png)

how to fix them?

**Comment by yuvrajx** [comment]
First, 
Groff is conflicting with some packages like man etc.
