### ISSUE TITLE
Can't remove python3.6

### ISSUE THREAD

**Issue by abrikos110** [termux/termux-packages#3171]
I have python3.7 and python2.7 installed. python3.6 is not shown in list of installed packages but i have big 'python3.6' folder in termux's 'usr/lib'. How can i remove this python3.6?
![screenshot_2018-12-25-19-26-02-631_com termux](https://user-images.githubusercontent.com/37002281/50424840-4ea65000-087c-11e9-86c7-7bce645f4be6.png)

**Comment by xeffyr** [comment]
Trouble with running `rm -rf` ?

We don't cleaning up modules installed with pip, so you have python3.6 uninstalled but modues no. It's safe to just delete this folder.
