### ISSUE TITLE
Package request: FPC

### ISSUE THREAD

**Issue by jackokring** [termux/termux-packages#3177]
**Package description**
Free Pascal Compiler. Old but very portable term based fp dev.

**Link to home page and sources**
1. Freepascal.org svn.
2. ...

**Additional information**
No. New to termux. Use linux often.

**Comment by its-pointless** [comment]
I have fpc available on my apt repo

**Comment by jackokring** [comment]
Yes, the units and fp ide command seem to not be there, as per a debian install of fpc.

**Comment by SDRausty** [comment]
@its-pointless it is very good that fpc is at your repo.  Do you know why it is not in the main repo?

references:
> Lets allow Pascal users to create Pascal applications directly on Android devices 

a) https://github.com/SDRausty/buildAPKs/issues/23

b) https://github.com/termux/termux-packages/issues?q=pascal

c) search string:
`pascal compiler history of computer science site.edu`

> History of Computer Science. Blaise Pascal (approx . 1650) built a machine with 8 gears called the. Pascaline to assist French government in compiling tax ...
