### ISSUE TITLE
`ledger print` with date format produces garbage dates

### ISSUE THREAD

**Issue by kanreki** [termux/termux-packages#3184]
Running the `ledger print` command while specifying a date format produces output with non-printable, non-ASCII "garbage" for the dates. (The rest of the output is fine.)

For comparison, running the same example on Raspbian or Ubuntu works fine. Note also that other ledger subcommands (such as `register`) also work fine, even on Termux. It seems to be only the `print` subcommand. 

The command to reproduce the problem is as follows:

    ledger -f sample_input -y '%Y/%m/%d' print

(The sample_input is attached. Also attached is a copy of the output in the form of an `od` dump.)

You may argue that specifying a custom date format with the `print` subcommand makes no sense. And that is true. However, the problem is that I have the custom date format ensconced in my ~/.ledgerrc file, so it is always in effect automatically.

[sample_input.txt](https://github.com/termux/termux-packages/files/2725707/sample_input.txt)
[hex_dump.txt](https://github.com/termux/termux-packages/files/2725708/hex_dump.txt)

Expected behavior is of course that the dates appear properly formatted, with printable ASCII characters.

**Additional information**
Output of `termux-info`:
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.0-18720-g7b8c1dc67cda #1 SMP PREEMPT Mon Dec 10 23:56:44 PST 2018 i686 Android
Termux-packages arch:
i686
Android version:
7.1.1
Device manufacturer:
google
Device model:
HP Chromebook 13 G1

**Comment by tomty89** [comment]
https://github.com/ledger/ledger/commit/850a2cec794ef0d98dbaaf83e5ddce4ecb819e27

**Comment by fornwall** [comment]
Fixed in version `3.1.1-7` of the ledger package.
