### ISSUE TITLE
Privoxy fails to start

### ISSUE THREAD

**Issue by denialplando** [termux/termux-packages#3185]
Trying to run privoxy I get the following error:
_Info: Program name: privoxy
bionic/libc/upstream-netbsd/lib/libc/regex/regfree.c:110: regfree: assertion "preg->re_magic == MAGIC1" failed_

**Comment by denialplando** [comment]
Sorry,  this is on armv7l linux 3.18.19.

**Comment by xeffyr** [comment]
>bionic/libc/upstream-netbsd/lib/libc/regex/regfree.c:110: regfree: assertion "preg->re_magic == MAGIC1" 

Same issue as in https://github.com/termux/termux-packages/issues/1829.
**There no fix for this** as error comes from Android system library.

> linux 3.18.19.

Android version much more useful than kernel's.

**Comment by denialplando** [comment]
My android version is 6.0 .Privoxy worked well for me before the last update.

**Comment by xeffyr** [comment]
> worked well for me before the last update

And what ? This error happens randomly on devices with Android 5 or 6. There no guarantee that it will work correctly on downgrade, on certain settings it will fail.

Google fixed libc's regex problem in Android 7: https://android.googlesource.com/platform/bionic/+/8739a1a513b3d5c3043d764d2719b6a5e66ad21d%5E1..8739a1a513b3d5c3043d764d2719b6a5e66ad21d/
