### ISSUE TITLE
ledger: init-file specifying --file causes duplicate data

### ISSUE THREAD

**Issue by kanreki** [termux/termux-packages#3187]
Specifying a non-default `--init-file` containing a specification of the data file (`--file`) results in duplicate data.

The following works fine:

    ledger -f sample.txt reg food

But the following produces double output:

    ledger --init-file x.txt reg food

[x.txt](https://github.com/termux/termux-packages/files/2729092/x.txt)
[sample.txt](https://github.com/termux/termux-packages/files/2729093/sample.txt)
[bad_output.txt](https://github.com/termux/termux-packages/files/2729094/bad_output.txt)

Could it be that we need to pull [this bug fix](https://github.com/ledger/ledger/pull/493/commits/dab0039680cde39bd50404d1466f3ad50e012b68)?

**Comment by tomty89** [comment]
If we want to fix such non-platform-specific issue, perhaps we should just build from their `next` and update regularly. Does ledger still have release cycle anyway?

**Comment by kanreki** [comment]
(WIth  #3184 fixed, this one is now less vexing for me: I was using --init-file as part of workaround.)

**Comment by fornwall** [comment]
@kanreki Can you update with `pkg up` and see if the latest `3.3.1-8` version of the ledger package fixes this problem?

I added https://github.com/ledger/ledger/pull/493/commits/dab0039680cde39bd50404d1466f3ad50e012b68. Hopefully ledger will have a new release soon.
