### ISSUE TITLE
Package request: apt-file

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#319]
It would be quite useful to find which package is needed in order to get a specific binary.

**Comment by kennethho** [comment]
+1

**Comment by Neo-Oli** [comment]
I've done some work on this [here](https://github.com/Neo-Oli/termux-packages/tree/apt-file/packages/apt-file). The building works fine, but it's still missing several dependencies.

**Comment by TheDiamondYT1** [comment]
Unfortunatly ncurses requires alot of libs which arent in termux

**Comment by Rudloff** [comment]
@TheDiamondYT1 What do you mean? apt-file does not seem to require ncurses (and ncurses is already available in Termux).

**Comment by TheDiamondYT1** [comment]
Shhh i didnt see that

**Comment by TheDiamondYT1** [comment]
@Rudloff Look on the debian repository for apt-file

**Comment by Rudloff** [comment]
I don't see ncurses in the dependency tree (on Debian 8.6): https://gist.github.com/Rudloff/aec2ab938ff0c8a82793eab67ca0f620

**Comment by TheDiamondYT1** [comment]
Nvm im thinking of wrong pkg

**Comment by Rudloff** [comment]
It depends on the AptPkg Perl module which does no seem to be available from CPAN. Should we create a package for it?

**Comment by alxpettit** [comment]
I think we should.

**Comment by Grimler91** [comment]
Apt-file also needs Contents-$ARCH files to search in, so the main repository's build script has to be updated to generate this as well

**Comment by vstavrinov** [comment]
As soon as Contents files will be available we can use them before apt-file release. I hope it takes less time.

**Comment by landfillbaby** [comment]
just added `libapt-pkg-perl` and `apt-file` :)
