### ISSUE TITLE
metasploit gem bug

### ISSUE THREAD

**Issue by jakoma1** [termux/termux-packages#3191]
cant run metasploit always this error
1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
$

i have tried many times to fix it 
and install many bundle but no thing happend

i use unroot device

**Comment by Grimler91** [comment]
Metasploit isn't a package in termux-packages so I'm closing this. 

Searching the world-wide-web returns lots of results so I suggest you look there. My first result: https://stackoverflow.com/questions/47026174/find-spec-for-exe-cant-find-gem-bundler-0-a-gemgemnotfoundexception

**Comment by jakoma1** [comment]
help me
