### ISSUE TITLE
How to install opencv-contrib?

### ISSUE THREAD

**Issue by YEDrekt** [termux/termux-packages#3193]
I installed OpenCV with the help of this tutorial: `https://wiki.termux.com/wiki/Instructions_for_installing_python_packages`

But it was giving me an error so I replaced the

 `LDFLAGS=" -llog" cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_opencv_python3=on -DBUILD_opencv_python2=off -DWITH_QT=OFF -DWITH_GTK=OFF ..`

part with

`LDFLAGS=" -llog -lpython3" cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_opencv_python3=on -DBUILD_opencv_python2=off -DWITH_QT=OFF -DWITH_GTK=OFF ..`.

Now it works fine but I realized it doesn't include the contrib functions like SIFT.

Can someone explain how can I install opencv-contrib?

**Comment by Grimler91** [comment]
Thanks, I updated the wiki to include `-lpython3` as well. 

The opencv-contrib [README](https://github.com/opencv/opencv_contrib) looks pretty nice so have a look at that. Basically it should be enough to clone/download the opencv-contrib repo and then add 
```-DOPENCV_EXTRA_MODULES_PATH=<path_to_opencv_contrib_folder>/modules```
to your cmake flags in the command you wrote. 

I haven't tried it so let me know if you get any errors.

**Comment by YEDrekt** [comment]
@Grimler91 It worked, thanks! But OpenCV doesn't let you use contrib modules and wants you to set OPENCV_ENABLE_NONFREE CMake option. But all you need to do is adding 
`-DOPENCV_ENABLE_NONFREE:BOOL=ON `
to your CMake flags and you are good to go.

**Comment by spectereye** [comment]
Hi thanks and i just done `make install` for opencv-contrib following guide above without error pop up, but `pip list | grep opencv` can't find it ... another package `airtest` depend on this then installed failed, any guide? thanks!
