### ISSUE TITLE
Tor pkg

### ISSUE THREAD

**Issue by chemostafa** [termux/termux-packages#3198]
How I use bridge in tor pkg ?
Tor is blocked in my country and didn't work without bridge also I need to know how I use vbn for app by for pkg 
The bridge its some thing like that 
https://bridges.torproject.org/bridges

173.44.42.231:443 4A2AEC67397891009E44953891041B3A43C7ADBC

31.18.76.58:9001 0C2AA985FE56495D6367F8CE2B3EBBE3D3E58A37

94.75.219.26:8443 EF252311CDDCD8D3E67EE45E617A31E62465D1CA
I use it in orbit tour app but II want use ist in tor pkg termux

**Comment by Atavic** [comment]
Edit your .torrc config: https://asciinema.org/a/28492

**Comment by Atavic** [comment]
To know if it worked fine, check logs.
See: https://www.torservers.net/wiki/setup/bridge

**Comment by Atavic** [comment]
Also see: https://github.com/Yawning/torspec/blob/master/attic/bridges-spec.txt#L115

**Comment by chemostafa** [comment]
Thanks but I have one problem now , how I write the bridge in 
nano $PREFIX/etc/tor/torrc ??
I tirde to write it 
$ tor
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Jan 12 02:02:50.187 [notice] Tor 0.3.5.7 running on Linux with Libevent 2.1.8-beta, OpenSSL 1.1.1a, Zlib 1.2.8, Liblzma 5.2.4, and Libzstd N/A.
Jan 12 02:02:50.187 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jan 12 02:02:50.188 [notice] Read configuration file "/data/data/com.termux/files/usr/etc/tor/torrc".
Jan 12 02:02:50.198 [warn] Linelist option 'Bridge' has no value. Skipping.
Jan 12 02:02:50.199 [warn] Failed to parse/validate config: If you set UseBridges, you must specify at least one bridge.
Jan 12 02:02:50.199 [err] Reading config failed--see warnings above.

**Comment by xeffyr** [comment]
@chemostafa Put this to torrc:
```
UseBridges 1
Bridge 192.241.149.207:8443 69E9704E7061819879B0D2814B4F0908D922BE76
Bridge 45.23.19.129:9001 598E477CD637A07DF3F6987BC73C4905BEAE84AE
Bridge 178.63.28.14:443 88CB40E536DD6F6775626E6A3BCC5D9C0B7BAFEA
Bridge 119.9.89.184:8443 D9BA0A4ED65CCB10A1D86A9091C629FACE6D84F5
Bridge 31.185.27.204:443 2620ECB36C504BB1FD1AA75E73F3BA068514E842
Bridge 31.171.155.6:29378 410C02F95F7C3DAD2741BE7CD8F31685488856C7
```

Of course, you can set your bridges here. Example torrc shown above uses *plain bridges*, i.e. no pluggable transport as Termux doesn't provide obfs4proxy or similar.

**Comment by chemostafa** [comment]
Same problem

And also I do
pip install obfsproxy

Then 

nano $PREFIX/etc/tor/torrc

And I copy and past what you write to me and I got same problem ,, if you have Twitter or any mail I can sent you photo that's well be good coz I can't sent photo here

**Comment by xeffyr** [comment]
@chemostafa My example doesn't use obfsproxy or any other pluggable transport.

***

> pip install obfsproxy

Wrong command. In Termux, `pip` used by python v3 but obfsproxy requires python 2. Do this instead:
```
pkg install python2
pip2 install obfsproxy
```

Put this to your torrc:
```
UseBridges 1
ClientTransportPlugin obfs3 exec /data/data/com.termux/files/usr/bin/obfsproxy managed

Bridge obfs3 104.236.168.125:37494 E58F54184935689AC7BFD983FB887AFE2D443B4D
Bridge obfs3 83.28.233.173:39665 5BE6B6F203D8B5207B14FF618064F7A488F23053
```

If tor is not working:

* Check that obfsproxy is available at `/data/data/com.termux/files/usr/bin/obfsproxy`. Execute this file, you should get some information about it's usage. If it crashed - **reinstall obfsproxy** with pip2.

* Check that pluggable transport is enabled and it is obfs3.

* Check your bridges. They should be capable of *obfs3* protocol, otherwise get new bridges. Some bridges may not work.

* Check your torrc config for any possible conflicts.

* Finally, read the tor log to figure out why it is not working.

**Comment by chemostafa** [comment]
I get this error when I do 
pip2 install obfsproxy
Command "/data/data/com.termux/files/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-UeRSPU/PyCrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-wc7Oop-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-UeRSPU/PyCrypto/
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

So I'd o this
pip install --upgrade pip
And finished good 
Then I do 

pip2 install obfsproxy
Same error 😁
Look for real I new in all.of this , sorry 😕

**Comment by xeffyr** [comment]
@chemostafa Is obfsproxy is working for you in Termux at all ?

What output of `$PREFIX/bin/obfsproxy --help` ?

**Comment by xeffyr** [comment]
> do you have Twitter or any social mida app ?

Github already has support for pictures. If github doesn't allow you to upload pics, use https://imgbb.com/.

> pip2 install obfsproxy
I get that error

It seems that more packages needed. Do
```
pkg install clang python2-dev libgmp-dev
```
And then try `pip2 install obfsproxy` again.

**Comment by xeffyr** [comment]
> https://ibb.co/JvP815z

By default, nano performs "hard wrap" of long lines. As a result, you got a corrupted configuration file.
Use `nano --nowrap` when editing.

**Comment by chemostafa** [comment]
I thing the problem in 'data/data/com.termux/files/usr/bin/obfsproxy. Failing.
tor
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Jan 12 18:17:16.056 [notice] Tor 0.3.5.7 running on Linux with Libevent 2.1.8-beta, OpenSSL 1.1.1a, Zlib 1.2.8, Liblzma 5.2.4, and Libzstd N/A.
Jan 12 18:17:16.056 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jan 12 18:17:16.057 [notice] Read configuration file "/data/data/com.termux/files/usr/etc/tor/torrc".
Jan 12 18:17:16.067 [warn] Failed to parse/validate config: Unknown option 'data/data/com.termux/files/usr/bin/obfsproxy'.  Failing.
Jan 12 18:17:16.067 [err] Reading config failed--see warnings above.

**Comment by chemostafa** [comment]
OK I do 

nano --nowrap $PREFIX/etc/tor/torrc

Then I get new bridge from 
https://bridges.torproject.org/bridges
It give me new 3 bridge and I do this 

95.46.45.116:80 95E8FB7A8CFCBCB1361205DCCDF77E611B6583AD
192.40.56.22:443 F8E7693233E2A47F3F72FF7980A71FFF12565D77
83.28.233.173:9123 5BE6B6F203D8B5207B14FF618064F7A488F23053

So I write in torcc like that 

UseBridges 1 ClientTransportPlugin obfs3 exec /data/data/com.termux/files/usr/bin/obfsproxy managed
Bridge obfs3 95.46.45.116:80 95E8FB7A8CFCBCB1361205DCCDF77E611B6583AD
Bridge obfs3 192.40.56.22:443 F8E7693233E2A47F3F72FF7980A71FFF12565D77
Bridge obfs3 83.28.233.173:9123 5BE6B6F203D8B5207B14FF618064F7A488F23053
And is worked 😂😂 man your are genus you the best thank you very thank you 😘😘😘

https://ibb.co/BNmdp56

Now how I use it like vbn ,, like i f I want open whatsup or Twitter or any by tor it 😁

**Comment by xeffyr** [comment]
> And is worked

If worked, please close issue.

**Comment by chemostafa** [comment]
It worked but how use it on app like WhatsApp or any 👀 and II close it sure thank u at all 👍

**Comment by xeffyr** [comment]
> how use it on app like WhatsApp

Thats going too far as Termux has nothing do to with it. If WhatsApp does not support socks5 proxy, then no way to do it through Termux.

**Comment by chemostafa** [comment]
How about any app telgram or any even Firefox for sites ? I mean it worked so what is used for ?

**Comment by xeffyr** [comment]
> telgram

In Telegram setting set 127.0.0.1 for proxy host and 9050 for port.

**Comment by chemostafa** [comment]
That's very nice thanks now
1- I do that in telegram
2- then i start termux and start tor ,
= then telgrame only open by tor ? 👀

**Comment by xeffyr** [comment]
> then telgrame only open by tor

It should send/receive data over tor.

**Comment by chemostafa** [comment]
Thanks man for evey thing thank you 💖💖 I well close issue now thank you

**Comment by xeffyr** [comment]
In firefox open `about:config`, then change options like here:

![screenshot_20190112-191256_firefox](https://user-images.githubusercontent.com/25881154/51076262-ef7b7480-169e-11e9-8b0f-7596af51f5df.jpg)

and here:
![screenshot_20190112-191743_firefox](https://user-images.githubusercontent.com/25881154/51076263-f30efb80-169e-11e9-9eec-e650dd8c1f0a.jpg)

**Comment by chemostafa** [comment]
I know that I closed issue but can I asks why it never finished handshake 10% ? Is that coz slow net speed or what ?
Stuck at 10%: Finishing handshake with directory server. (DONE; DONE; count 17; recommendation warn; host 1F696E223A4CC260A7F8D89D424C56A5ED00ECB9 at 45.76.31.93:8443)
Jan 13 22:14:16.000 [warn] 38 connections have failed:
Jan 13 22:14:16.000 [warn]  21 connections died in state handshaking (proxy) with SSL state (No SSL object)
Jan 13 22:14:16.000 [warn]  17 connections died in state handshaking (TLS) with SSL state SSLv3/TLS write client hello in HANDSHAKE
Jan 13 22:14:16.000 [warn] Proxy Client: unable to connect to 78.218.45.83:41605 ("TTL expired")

**Comment by Siddharth0328** [comment]
After I install tor package and run it ,it gets stuck when it reaches 100% . Im not able to enter any other command after that

**Comment by Grimler91** [comment]
> After I install tor package and run it ,it gets stuck when it reaches 100%

That is how tor is suppose to work. Open another terminal session, or run tor with some service manager (for example [termux-services](https://wiki.termux.com/wiki/Termux-services))
