### ISSUE TITLE
Run the i386 environment on the aarch64

### ISSUE THREAD

**Issue by foodmaher** [termux/termux-packages#3199]
My problem is that I want to run an i386 or x86 environment on the aarch64 environment. Is this possible? Especially as there are programs that do this, for example [**ExaGear Windows Emulator**][e], which provides an i386 environment on [**raspberry pi 2 & 3**][rpi] that works with ARM64 processor ...

**Required:** What I want is to install [**wine**][w] on a 32-bit environment ...

Thanks ...

[e]: https://eltechs.com/product/exagear-desktop/
[w]: https://www.winehq.org
[rpi]: https://www.raspberrypi.org

**Comment by xeffyr** [comment]
ExaGear is not Wine.
Wine is not x86 emulator. You can't run x86 programs on Wine ARM or AArch64.

Read the Wine [wiki](https://wiki.winehq.org/ARM):

> Windows apps are mostly compiled for x86 and they won't run on ARM with bare Wine, likewise ARM applications won't run on x86(_64) with bare Wine, so this is not our motivation.

***

What you are requesting is simply not possible...

**Comment by foodmaher** [comment]
> My problem is that I want to run an i386 or x86 environment on the aarch64 environment. Is this possible? Especially as there are programs that do this, for example [**ExaGear Windows Emulator**](https://eltechs.com/product/exagear-desktop/), which provides an i386 environment on [**raspberry pi 2 & 3**](https://www.raspberrypi.org) that works with ARM64 processor ...
> 
> **Required:** What I want is to install [**wine**](https://www.winehq.org) on a 32-bit environment ...
> 
> Thanks ...

**Note:** I know that wine is not an emulator but it is a layers to run Windows programs on the host system, but I'm talking about the Exagear windows emulator application that emulates the i386 environment on the aarch64 to install wine x86 it

**Comment by xeffyr** [comment]
> how Exagear developers fill the i386 environment on the android ?

Likely the similar way as QEMU does this.
ExaGear is a **closed-source** proprietary stuff so it definetly won't be in Termux repos.

**Tell me what you exactly want.** Which package ? What it should do ?

**Comment by foodmaher** [comment]
Or install Windows 10 ARM on the qemu emulator through the android because I have done it in the past but crash the system when prompted me to press any key to complete the system installation

**Comment by xeffyr** [comment]
Closing because:

* We have QEMU (both user and system mode). How to setup minimal rootfs and chroot into it with proot and qemu-user is *searchable* on the Internet.

* ExaGear is a proprietary thing.

**Comment by ulist** [comment]
yes you can use exagear as emulator and ran wine and it works perfectly I use it everyday check this https://youtu.be/8nWo4kluyG0
but you don't really need to use proot launch exagear directly on termux

**Comment by Artoria2e5** [comment]
For those who still don't get the QEMU reply: you are supposed to run a 32-bit wine in QEMU for this. QEMU emulates the x86 environment for you to run wine. See https://www.qemu.org/docs/master/user/main.html#wine-launch for how to do that.
