### ISSUE TITLE
CANNOT LINK EXECUTABLE when running vifm

### ISSUE THREAD

**Issue by lsvy97** [termux/termux-packages#3201]
Vifm on launch gives this error:

```
$ vifm
CANNOT LINK EXECUTABLE: cannot locate symbol "pthread_spin_lock" referenced by "vifm"...
page record for 0x7f8b1e0010 was not found (block_size=16)
$
```
Android 6.0.1, LeEco Le X527

**Comment by xeffyr** [comment]
Same problem on ARM/Android6 but on Android 8 everything okay.
Perhaps `pthread_spin_lock()` is not implemented in Android 6 (or lower) libc.

**Comment by Grimler91** [comment]
@lsvy97 did it use to work for you (i.e. did it stop working on an update) or did you just try vifm for the first time?

Tagging #2874 since we might want to remove the package from (future) android 5&6 repos then

**Comment by tomty89** [comment]
https://github.com/termux/termux-packages/blob/master/packages/vifm/build.sh#L3

**Comment by fornwall** [comment]
It would be really nice if we could set the information about required version as a header value in the built .deb package, and then make apt or dpkg error out with something like "Cannot install package: Requires Android 7 while this device uses Android 5".

**Comment by fornwall** [comment]
@lsvy97 To clarify: You would need a device running at least Android 7 for the current vifm package to work.

**Comment by lsvy97** [comment]
> @lsvy97 did it use to work for you (i.e. did it stop working on an update) or did you just try vifm for the first time?
> 
> Tagging #2874 since we might want to remove the package from (future) android 5&6 repos then

Well, i tried it for the first time. Didn't know that packages are android version dependent. Do they require some linux kernel features missing in Android 6?

**Comment by tomty89** [comment]
A newer version of bionic libc that implements pthread_spin_*

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/commit/4133a77c80fe0b8d6d980b7c11312a002159b321
