### ISSUE TITLE
Package request: Kivy

### ISSUE THREAD

**Issue by Unviray** [termux/termux-packages#3209]
Kivy support android

**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page: https://kivy.org
2. Source code: https://github.com/kivy/kivy

**Additional information**
Complete output from command python setup.py egg_info:
    Using distutils

    Cython is missing, it's required for compiling kivy !

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-22pn0b8i/kivy/setup.py", line 232, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-22pn0b8i/kivy/

**Comment by seisdr** [comment]
Try on unbuntu

**Comment by xeffyr** [comment]
Kivy currently is not supported in Termux.

**Comment by seisdr** [comment]
Ukraine pidor

**Comment by Unviray** [comment]
Ok
