### ISSUE TITLE
Segmentation fault with `busybox httpd`

### ISSUE THREAD

**Issue by laomaiweng** [termux/termux-packages#3216]
I get the following when trying to use Busybox's httpd:

```
$ busybox httpd -fvv -p 8888
Segmentation fault
$ busybox httpd -h
Segmentation fault
```

It was working fine a week ago. I can't quite remember but I think the sigsegvs started after upgrading Busybox. Other Busybox utilities that I tested work fine.

Here's my `termux-info`:

```
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.86-g7b77e01 #2 SMP PREEMPT Thu Jun 16 07:06:21 CST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
6.0
Device manufacturer:
HUAWEI
Device model:
H60-L04
```

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/2a7d9007f235ee7b0e2f7d416f863735f2d04eac.
