### ISSUE TITLE
caddy ignoring /etc/host

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#3219]
On Window/Linux I can set i.e "localhost.io" in Caddyfile.
On termux I get this:

Offline:
Activating privacy features...2017/07/04 09:24:20 get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: dial tcp: lookup acme-v01.api.letsencrypt.org on 8.8.8.8:53: dial udp 8.8.8.8:53: connect: network is unreachable

On wifi:

Activating privacy features...2017/07/04 09:29:42 [homecloud] failed to get certificate: acme: Error 400 - urn:acme:error:malformed - Error creating new authz :: DNS name does not have enough labels

**Comment by xeffyr** [comment]
Caddy should be built for "android" GOOS target instead of "linux". Otherwise it will fail to resolve domains.
