### ISSUE TITLE
Issue starting emacs 

### ISSUE THREAD

**Issue by kirillrdy** [termux/termux-packages#322]
On galaxy tab s2
`
emacs
Warning: arch-dependent data dir '/data/data/com.termux/files/usr/libexec/emacs/25.0.95/arm-linux-androideabi/': Invalid argument
Warning: arch-independent data dir '/data/data/com.termux/files/usr/share/emacs/25.0.95/etc/': Invalid argument
Warning: Lisp directory '/data/data/com.termux/files/usr/share/emacs/25.0.95/lisp': Invalid argument
Error: charsets directory not found:
/data/data/com.termux/files/usr/share/emacs/25.0.95/etc/charsets
Emacs will not function correctly without the character map files.
Please check your installation!
$
`

Sorry for lack of details.
Please suggest what other details i should include

**Comment by fornwall** [comment]
Thanks - this should now be fixed in the `25.0.95-1` version of the emacs package - run `apt update && apt upgrade` to install the updated version.
