### ISSUE TITLE
Problem: vim is not working in su and on sdcard

### ISSUE THREAD

**Issue by AravK** [termux/termux-packages#323]
When I use SuperUser (su) and type in vim, I get an error: CANNOT LINK EXECUTABLE: library "libncursesw.so.6" not found. In sdcard, I get Permission denied.

**Comment by fornwall** [comment]
See https://github.com/cswl/tsu for a method of becoming root in Termux, which keeps the `LD_LIBRARY_PATH` variable needed for shared libraries to work.

As for the sdcard, see https://termux.com/storage.html.
