### ISSUE TITLE
Build package hugo with extended flag

### ISSUE THREAD

**Issue by holehan** [termux/termux-packages#3236]
@xeffyr Thanks for adding hugo to the main termux repository in commit https://github.com/termux/termux-packages/commit/d862c528541517d13de60ccbfa6ad58f8e587d20 . However the current build is dearly missing a decisive feature: the extended version with **Hugo Pipes** which add support for PostCSS, SASS and the like. I have been building and using the extended version of hugo on Termux successfully myself for quite some while now. Unfortunately I never came around to open a pull request for the official termux repository. Have a look at my build script at https://github.com/holehan/termux-packages/blob/master/packages/hugo/build.sh to see how to build with the `extended` tag and enable hugo Pipes.

**Comment by xeffyr** [comment]
Thanks, I'll look on it. Manpages and bash completion should be added too.

**Comment by holehan** [comment]
Thank you very much for bringing hugo extended with man pages and bash completion into the mainline termux-packages!
