### ISSUE TITLE
[Package Request] : gnucap

### ISSUE THREAD

**Issue by gribja** [termux/termux-packages#3237]
**Description :**
Gnucap is a general purpose circuit simulator. It performs nonlinear dc and transient analyses, fourier analysis, and ac analysis. 

**Additional links :**

* [https://www.gnu.org/software/gnucap/gnucap.html](https://www.gnu.org/software/gnucap/gnucap.html)

* [http://gnucap.org/dokuwiki/doku.php?id=gnucap:start](http://gnucap.org/dokuwiki/doku.php?id=gnucap:start)

* [https://mulder-patrick.gitbook.io/gnucap](https://mulder-patrick.gitbook.io/gnucap)

**Comment by Grimler91** [comment]
I had a look and it will require some work it seems, it doesn't support cross-compilation at all and lots of stuff is hard-coded. 

Or, actually, it seems older versions did support cross-compilation more nicely.
Latest code are at savannah and gitlab.

**Comment by gribja** [comment]
@Grimler91 There's a guide for different installation process I found [here](https://www.gnu.org/software/gnucap/gnucap-man-html/gnucap-man100.html). Have a look at this.

**Comment by Grimler91** [comment]
I almost have it working. It compiles but gives a linker error when gnucap is run on device (LD_PRELOAD-ing libgnucap.so solves it but we wanr a more proper solution).Sources are here for now: https://github.com/Grimler91/science-packages/tree/master/packages/gnucap

**Comment by Grimler91** [comment]
@gribja Alright, it's working. You can download the debs from here for now: https://grimler.se/dists/science/stable/binary-aarch64/gnucap_20171003-1_aarch64.deb (replace aarch64 with another arch if you are on another arch), it would be great if you could test it (I only tried running gnucap) and see if there are additional problems

**Comment by gribja** [comment]
@Grimler91 Many thanks for the deb package. Although there's more to test, but till now it's working pretty well.
