### ISSUE TITLE
Add cc alias

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#325]
Hello,

Some scripts look for a `cc` command but Termux does not seem to have one.
Would it be possible to add an alias that points to gcc ? (Debian seems to do that too.)

**Comment by fornwall** [comment]
If you `apt install clang` you get a `cc` command as an alias for `clang`.

As google has deprecated gcc support for Android in favour of clang, this is probably the way forward (in the future, depending on how hard it is to support gcc on Android, perhaps even `gcc` could be setup as an alias for `clang`).
