### ISSUE TITLE
Request: imgur.sh

### ISSUE THREAD

**Issue by Symbian9** [termux/termux-packages#3252]
**Package description**

Imgur CLI uploader (upload image to imgur)

**Link to home page and sources**

1. Home page:
2. Source code: https://github.com/tremby/imgur.sh

**Comment by xeffyr** [comment]
Did you looked at the script source ? There are several problems:

1. API key. Right now it is specified as "c9a6efb3d7932fd" which belongs to unknown person.

2. Usage of unavailable commands:
  * pbcopy - can be replaced with "termux-clipboard-set"
  * xsel - X11-related
  * xclip - X11-related

And last question, why we should package these small scripts ? It's easy to copy it, e.g. to $PREFIX/bin.

**Comment by Symbian9** [comment]
Okey, I found that I could use it via: `$ bash ./imgur.sh ./image.png`
