### ISSUE TITLE
Heimdall

### ISSUE THREAD

**Issue by lastweakness** [termux/termux-packages#3259]
If Heimdall is ported, it could be possible to flash Samsung firmware via OTG.

**Comment by xeffyr** [comment]
Should be possible, if device running heimdall has root.
Also, we are not going to port it unless there is a proof that it is working in Termux.

**Comment by ahirearyan2** [comment]
> Should be possible, if device running heimdall has root.
> Also, we are not going to port it unless there is a proof that it is working in Termux.

But how to install it? Can you tell me? Please it's urgent.

**Comment by ahirearyan2** [comment]
> If Heimdall is ported, it could be possible to flash Samsung firmware via OTG.

How to install it can you please tell me??
