### ISSUE TITLE
Arrow Keys (left and right) were removed

### ISSUE THREAD

**Issue by neo-expert** [termux/termux-packages#3261]
There were two rows with very useful additional keys (like "home", "end" and most importantly all the arrow keys)
I tried many software-keyboards, but no one have convinient solution for this.
These two additional rows were the best solution. And now after update (Playstore) there is only one row. Can we have it again?

Volume-Key up solution, is also not very convenient: my Volume Up key is broken now, because of using it so often with termux.

Edit:

Sorry, I posted this in the wrong repository

Here is the solution:

https://github.com/termux/termux-app/issues/749#issuecomment-456814311

**Comment by xeffyr** [comment]
> Arrow Keys (left and right) were removed

> Here is the solution:

We all know this.
