### ISSUE TITLE
Relationship between its-pointless gcc 

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#3263]
With reference to #3055,is termux going to leave fortran or R for @its-pointless for developement? If this is the case, shall we include the repository in the termux-packages list? Thanks!

**Comment by Wetitpig** [comment]
Thanks for telling me. I am just thinking of building Flang for termux...

**Comment by its-pointless** [comment]
Flang will likely never work for 32 bit (its possible only on aarch64 as of right now). Also you can't cross compile R anway.
