### ISSUE TITLE
[Package Request] Scat, a CLI Chat based on Scuttlebutt

### ISSUE THREAD

**Issue by Atavic** [termux/termux-packages#3267]
**Package description**
Scat is tiny chat-like cli built on Scuttlebutt

**Link to home page and sources**
https://www.scuttlebutt.nz/applications#scat
https://github.com/stripedpajamas/scat

**Additional information**
Scuttlebutt is a distributed and secure peer to peer social network:
https://www.scuttlebutt.nz/
About Scuttlebutt protocol:
https://ssbc.github.io/scuttlebutt-protocol-guide/

I haven't compiled Scat on device.

**Comment by Grimler91** [comment]
Can be installed through npm according to `https://github.com/stripedpajamas/scat#install--run`, have you tried that?

**Comment by Atavic** [comment]
Not yet, sorry.
