### ISSUE TITLE
xpdf3.04

### ISSUE THREAD

**Issue by yxiongnjnu** [termux/termux-packages#3271]
**Package description**
Describe what this package do and why it should be available.
light pdf reader.
**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
This shouldn't go to main repository. Especially old (3.04) version.
