### ISSUE TITLE
Build failed for unzip

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#3272]
**Problem description**
Build for unzip failed.

**Steps to reproduce**
https://cirrus-ci.com/build/5737301503115264 performed on https://github.com/Wetitpig/termux-packages/tree/cirrus-ci

**Comment by Wetitpig** [comment]
It may be due to the recent commits of `langinfo.h`

**Comment by Wetitpig** [comment]
A check in 
https://github.com/LuaDist/unzip/blob/master/unzip.c
shows that the file is included in the main function, and hence function declaration is not allowed.

Maybe the functions should be again, stored in a separate C file.

**Comment by Wetitpig** [comment]
Just made a patch and now I am trying to build it.

**Comment by Wetitpig** [comment]
radare2 also reports a problem with the build, maybe also due to the `langinfo.h` patch.

**Comment by fornwall** [comment]
Should be fixed by 927d89eacfaa7dadaea29ef9ba3b8176be3363bf.
