### ISSUE TITLE
Haraka error install

### ISSUE THREAD

**Issue by Sysetup** [termux/termux-packages#3279]
Is Haraka possible to be installed in Termux?
I'm having this issue now installing it. Can you give me some suggestions to install Haraka properly?

npm install -g Haraka
/data/data/com.termux/files/usr/bin/haraka_grep -> /data/data/com.termux/files/usr/lib/node_modules/Haraka/bin/haraka_grep
/data/data/com.termux/files/usr/bin/haraka -> /data/data/com.termux/files/usr/lib/node_modules/Haraka/bin/haraka
/data/data/com.termux/files/usr/bin/spf -> /data/data/com.termux/files/usr/lib/node_modules/Haraka/bin/spf
/data/data/com.termux/files/usr/bin/dkimverify -> /data/data/com.termux/files/usr/lib/node_modules/Haraka/bin/dkimverify

dtrace-provider@0.8.7 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/dtrace-provider
node-gyp rebuild || node suppress-error.js

modern-syslog@1.1.4 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/modern-syslog
node-gyp rebuild

sqlite3@4.0.6 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/sqlite3
node-pre-gyp install --fallback-to-build

iconv@2.3.2 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/iconv
node-gyp rebuild

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.7 (node_modules/Haraka/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.7 install: `node-gyp rebuild || node suppress-error.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn sh EACCES
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 (node_modules/Haraka/node_modules/modern-syslog):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn sh EACCES
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.0.6 (node_modules/Haraka/node_modules/sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn sh EACCES

npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno EACCES
npm ERR! syscall spawn sh
npm ERR! iconv@2.3.2 install: `node-gyp rebuild`
npm ERR! spawn sh EACCES
npm ERR!
npm ERR! Failed at the iconv@2.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2019-01-26T22_27_09_769Z-debug.log

**Comment by Sysetup** [comment]
If `--unsafe-perm` is used, this error is reported:

npm install --unsafe-perm -g Haraka

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /data/data/com.termux/files/usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Linux 3.18.70-Lineage-g54b61ef
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/dtrace-provider
gyp ERR! node -v v11.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

 modern-syslog@1.1.4 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/modern-syslog
 node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /data/data/com.termux/files/usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Linux 3.18.70-Lineage-g54b61ef
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/modern-syslog
gyp ERR! node -v v11.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
[            ......] \ install:safe-buffer: info lifecycle saf
 sqlite3@4.0.6 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/sqlite3
 node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: not found

 iconv@2.3.2 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/iconv
 node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /data/data/com.termux/files/usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Linux 3.18.70-Lineage-g54b61ef
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/iconv
gyp ERR! node -v v11.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
[            ......] | install: info lifecycle iconv@2.3.2~ins[            ......] | install: info lifecycle iconv@2.3.2~ins[            ......] | install: info lifecycle iconv@2.3.2~ins[            ......] | install: info lifecycle iconv@2.3.2~ins[            ......] | install: info lifecycle iconv@2.3.2~ins[            ......] | install: info lifecycle iconv@2.3.2~ins[            ......] | install: info lifecycle =iconv@2.3.2~ins[            ......] | install: info lifecycle iconv@2.3.2~ins[            ......] | install: info lifecycle iconv@2.3.2~ins[            ......] | install: info lifecycle iconv@2.3.2~ins[            ......] | install: info lifecycle iconv@2.3.2~ins[            ......] | install: info lifecycle iconv@2.3.2~insnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 (node_modules/Haraka/node_modules/modern-syslog):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.0.6 (node_modules/Haraka/node_modules/sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

npm ERR! code ELIFECYCLE
npm ERR! errno 10mnpm ERR! iconv@2.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2019-01-26T22_39_13_792Z-debug.log

**Note:** Python is correctly installed.

**Comment by Grimler91** [comment]
Can you run the failed command manually? 
`/data/data/com.termux/files/usr/bin/python -c 'import sys; print "%s.%s.%s" % sys.version_info[:3]'`

What do you get when you do that? You might need to install python2

**Comment by Sysetup** [comment]
Right, Installing python2 too and running `python -V` the system reports: Python 3.7.2

Running this command to set Python 2 to npm environment: `npm config set python python2.7` 

The system reports these errors running with tsu:

 dtrace-provider@0.8.7 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/dtrace-provider
 node-gyp rebuild || node suppress-error.js

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:159:21)
gyp ERR! System Linux 3.10.49-g8a8b553
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/dtrace-provider
gyp ERR! node -v v11.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

 modern-syslog@1.1.4 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/modern-syslog
 node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:159:21)
gyp ERR! System Linux 3.10.49-g8a8b553
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/modern-syslog
gyp ERR! node -v v11.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

sqlite3@4.0.6 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/sqlite3
node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: not found

 iconv@2.3.2 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/iconv
 node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:159:21)
gyp ERR! System Linux 3.10.49-g8a8b553
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/iconv
gyp ERR! node -v v11.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 (node_modules/Haraka/node_modules/modern-syslog):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.0.6 (node_modules/Haraka/node_modules/sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2019-01-30T22_54_01_821Z-debug.log

When is executed your suggested command:
`/data/data/com.termux/files/usr/bin/python -c 'import sys; print "%s.%s.%s" % sys.version_info[:3]'`

The system reports:

File "<string>", line 1
    import sys; print "%s.%s.%s" % sys.version_info[:3]
                               ^
SyntaxError: invalid syntax

**Comment by Sysetup** [comment]
Right, Installing python2 too and running `python -V` the system reports: Python 3.7.2

Running this command to set Python 2 to npm environment: `npm config set python python2.7` 

The system reports these errors running with tsu:

 dtrace-provider@0.8.7 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/dtrace-provider
 node-gyp rebuild || node suppress-error.js

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:159:21)
gyp ERR! System Linux 3.10.49-g8a8b553
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/dtrace-provider
gyp ERR! node -v v11.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

 modern-syslog@1.1.4 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/modern-syslog
 node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:159:21)
gyp ERR! System Linux 3.10.49-g8a8b553
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/modern-syslog
gyp ERR! node -v v11.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

sqlite3@4.0.6 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/sqlite3
node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: not found

 iconv@2.3.2 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/iconv
 node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:159:21)
gyp ERR! System Linux 3.10.49-g8a8b553
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/iconv
gyp ERR! node -v v11.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 (node_modules/Haraka/node_modules/modern-syslog):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.0.6 (node_modules/Haraka/node_modules/sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2019-01-30T22_54_01_821Z-debug.log

When is executed your suggested command:
`/data/data/com.termux/files/usr/bin/python -c 'import sys; print "%s.%s.%s" % sys.version_info[:3]'`

The system reports:

File "<string>", line 1
    import sys; print "%s.%s.%s" % sys.version_info[:3]
                               ^
SyntaxError: invalid syntax

**Comment by Grimler91** [comment]
> gyp ERR! stack Error: not found: make

So you need to install make

**Comment by Sysetup** [comment]
Now that make and g++ have been installed the system reports this error:

npm install --unsafe-perm -g Haraka                     

/data/data/com.termux/files/usr/bin/haraka -> /data/data/com.termux/files/usr/lib/node_modules/Haraka/bin/haraka                  /data/data/com.termux/files/usr/bin/spf -> /data/data/com.termux/files/usr/lib/node_modules/Haraka/bin/spf                        /data/data/com.termux/files/usr/bin/dkimverify -> /data/data/com.termux/files/usr/lib/node_modules/Haraka/bin/dkimverify          /data/data/com.termux/files/usr/bin/haraka_grep -> /data/data/com.termux/files/usr/lib/node_modules/Haraka/bin/haraka_grep                                                                          sqlite3@4.0.6 install /data/data/com.termux/files/usr/lib/node_modules/Haraka/node_modules/sqlite3                              
node-pre-gyp install --fallback-to-build                                                                                        sh: 1: node-pre-gyp: not found                                   
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.0.6 (node_modules/Haraka/node_modules/sqlite3):                         npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`                 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT                                                                      + Haraka@2.8.23                                                  
updated 1 package in 27.988s                                     

Haraka is not installed properly.

When the command `haraka -v` is executed Termux reports that it is not installed:

bash: /data/data/com.termux/files/usr/bin/haraka: /usr/bin/env: bad interpreter: No such file or directory

These commands have been executed:

npm install -g node-pre-gyp
npm install -g node-gyp

But the errors persist.

**Comment by Grimler91** [comment]
`bash: /data/data/com.termux/files/usr/bin/haraka: /usr/bin/env: bad interpreter: No such file or directory` means that haraka is installed but that it has a shebang that doesn't work in termux. You need to edit `/data/data/com.termux/files/usr/bin/haraka` and change the first line from 
`#!/usr/bin/env`
to
`#!/data/data/com.termux/files/usr/bin/env`.

You can also do this by running `termux-fix-shebang` on the script you need to fix.

See https://wiki.termux.com/wiki/Differences_from_Linux

**Comment by Sysetup** [comment]
Thank you. Now works until here. Regards.
