### ISSUE TITLE
pkg upgrade fails (27 January 2019)

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#3282]
**Problem description**
Executing the command `pkg upgrade` fails with some error messages about lzma failing to decompess ndk-sysroot_18-9_aarch64.deb.

**Steps to reproduce**
Run the command `pkg upgrade`

**Additional information**
Post output of command `termux-info`. I can't even login to the mobile running Termux anymore, because I get this from sshd:

```
CANNOT LINK EXECUTABLE: cannot locate symbol "nl_langinfo" referenced by "/data/data/com.termux/files/usr/lib/libreadline.so.7.0"...
page record for 0x7facca8050 was not found (block_size=64)
```

**Comment by xeffyr** [comment]
That's weird.

Recent [update](https://github.com/termux/libandroid-support/commit/43e88c7936789275e37eaf47bc8a50c6fb9e5f50) of libandroid-support changes ABI. Such changes require rebuilding of most (if not all) packages, but that was not done.

**Comment by tigran123** [comment]
Could it be that I also need to upgrade the Termux binary as well? I don't use Google infrastructure and upgrade Termux binary about once in a few years (I assume nothing changes in computing on the timescale of a decade or so).

**Comment by steffenl82** [comment]
I encounter the same problem. I already opened an issue here: https://github.com/termux/libandroid-support/issues/4

Once you log out after apt upgrade, you won't be able to login again

**Comment by graxlop** [comment]
Same problem here.

$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.0-g2c2be66 #1 SMP PREEMPT Sat Jan 26 14:40:26 UTC 2019 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.2
Device manufacturer:
LGE
Device model:
Nexus 5

**Comment by xeffyr** [comment]
> Hm, I don't understand why not all devices are affected, that is a bit weird.

@Grimler91 Android 8 provides nl_langinfo() functions by itself which *may (or may not)* prevent linking failure.

From NDK:
```
langinfo.h
97:char* nl_langinfo(nl_item __item) __INTRODUCED_IN(26);
98:char* nl_langinfo_l(nl_item __item, locale_t __l) __INTRODUCED_IN(26);
```

**Comment by xeffyr** [comment]
I just got same problem on my Android 6 device. But one with Android 8 is not affected.

**Comment by xeffyr** [comment]
Closing in favor of https://github.com/termux/termux-packages/issues/3283 as issue is not with "pkg" or "apt" but related to libandroid-support and affects all packages that use nl_langinfo().

**Comment by Grimler91** [comment]
@xeffyr Ah, that explains it. 

So probably rebuilding all packages that depend on libandroid-support, i.e. 60 pkgs:
```
abook
apache2
bash
calcurse
cboard
cmus
dos2unix
findutils
fish
gawk
gegl
ghostscript
glib
gnuplot
grep
gtypist
hfsutils
htop
httping
indent
krb5
libcairo
libedit
libelf
libidn2
libqrencode
libunistring
mariadb
mc
megatools
mlocate
mosh
mtools
mutt
nano
ncdc
ncdu
ne
neovim
newsboat
openssh
pinentry
profanity
python2
python
readline
ruby
sharutils
stfl
tig
tmate
tmux
tree
units
unrar
weechat
wget
xorriso
zip
zsh
```

Temporary downgrade instructions are available in the other thread: https://github.com/termux/termux-packages/issues/3283

**Comment by Harshiv-Patel** [comment]
latest update to htop fixes the issue mentioned above on Android 5.1.1

**Comment by Harshiv-Patel** [comment]
GhostScript version 9.26 remains broken due to same "nl_langinfo" error as on 01/02/2019 on arm/Android Lollipop, hereby requesting a rebuild!

**Comment by cilantro13** [comment]
$ pkg upgrade -y
Hit:1 https://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
why still so bad in OS 5.1
