### ISSUE TITLE
can't upgrade ndk-sysroot

### ISSUE THREAD

**Issue by hotaru2k3** [termux/termux-packages#3285]
when running `pkg upgrade` in termux, I get the following errors:

    Unpacking ndk-sysroot (18-9) over (18-8) ...
    dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/ndk-sysroot_18-9_aarch64.deb (--unpack):
     trying to overwrite '/data/data/com.termux/files/usr/include/iconv.h', which is also in package libandroid-support-dev 22
    dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
    Errors were encountered while processing:
     /data/data/com.termux/files/usr/var/cache/apt/archives/ndk-sysroot_18-9_aarch64.deb
    E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by isrgish** [comment]
Same here.

**Comment by Grimler91** [comment]
Thanks for reporting! There is a pending PR to fix it: https://github.com/termux/termux-packages/pull/3284

**Comment by jmmaranan** [comment]
Occuring in Pixel 2 as well

**Comment by landfillbaby** [comment]
this is probably happening for everyone then

**Comment by Wetitpig** [comment]
@Grimler91 @xeffyr As members of the termux organisation can you directly commit? It is urgent.

**Comment by xeffyr** [comment]
> As members of the termux organisation can you directly commit?

Commit != rebuild. I can bump necessary packages, but this will be useless until @fornwall rebuild them.

**Comment by Grimler91** [comment]
@Wetitpig we can't upload debs to the repo so commiting won't help. 

I've uploaded ndk-sysroot (and fixes for some of the broken packages in #3283) to the root repo (temporarily) so running `apt install root-repo` and `apt update` should fix this for now

**Comment by Wetitpig** [comment]
Thanks

**Comment by fornwall** [comment]
This should now be fixed.

**Comment by jmmaranan** [comment]
@fornwall @Grimler91 - works on both Pixel 2s
