### ISSUE TITLE
CANNOT LINK EXECUTABLE "mc"

### ISSUE THREAD

**Issue by XSecr3t** [termux/termux-packages#3292]
It is very disgusting i've just want start and use any tools but this error show up

Can anyone solve this problem please?  Cause this is first time since i updated termux .
I try to tell to my friend and everyone say that they are got this problem too

May you can help me and i can help my friens for solved this
Thank you,

**Comment by XSecr3t** [comment]
@Grimler91  well thank you about that , closed post

**Comment by nitroxnoob** [comment]
Not solved even after using apt update && apt upgrade

**Comment by nitroxnoob** [comment]
What to do???
