### ISSUE TITLE
newsboat can't locate "nl_langinfo"

### ISSUE THREAD

**Issue by saisubham** [termux/termux-packages#3298]
```
$newsboat
CANNOT LINK EXECUTABLE "newsboat": cannot locate symbol "nl_langinfo" referenced by "/data/data/com.termux/files/usr/bin/newsboat"...
Aborted 
```

**Comment by fornwall** [comment]
Could you update with `pkg up` now and see if that fixes your problem?

**Comment by Herzogs** [comment]
Hi i update and when execute newsboat say this

> $ newsboat 
>CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atfork" referenced by >"newsboat"...

**Comment by retraut** [comment]
have the same issue with htop

**Comment by xeffyr** [comment]
> same issue with htop

Not only htop: cmus, tig, tree - these broken too.

**Comment by fornwall** [comment]
htop, cmus, tig, tree have all been revision-bumped and rebuilt - install fixed packages with `pkg up`.

> $ newsboat
CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atfork" referenced by "newsboat"...

Newsboat currently requires Android 7.0 or later.

**Comment by saisubham** [comment]
> htop, cmus, tig, tree have all been revision-bumped and rebuilt - install fixed packages with `pkg up`.
> 
> > $ newsboat
> > CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atfork" referenced by "newsboat"...
> 
> Newsboat currently requires Android 7.0 or later.
![screenshot_2019-01-30-15-17-02-502_com termux](https://user-images.githubusercontent.com/24736807/51973010-c16da100-24a2-11e9-8365-ad62260dce03.png)
![screenshot_2019-01-30-15-15-18-656_com termux](https://user-images.githubusercontent.com/24736807/51973013-c2063780-24a2-11e9-8fb6-d01670299481.png)



Thanks for the help. It worked for newsboat but I'm having trouble with cmus. #
