### ISSUE TITLE
websockets mosquitto

### ISSUE THREAD

**Issue by ajherrador** [termux/termux-packages#3301]
Hello good afternoon.
I need to enable the websockets protocol in mosquitto. I have tried several ways and I do not get it.
Is there any way to do it?
Greetings and thank you

**Comment by xeffyr** [comment]
Currently, mosquitto is not compiled with libwebsockets dependency, so there no way to enable this protocol.

**Comment by ajherrador** [comment]
Leonid good again.

I have seen that you have started another thread where it leads to a modification of the mosquitto configuration file.

How could I do to install mosquitto with this modification if it works?

A greeting and thank you very much.

**Comment by ajherrador** [comment]
I would have to do that compilation? if that is how I would have to do to install libwevsockect.
if not who would have to do it to be able to use it.

Thank you so much for everything.
