### ISSUE TITLE
apt install g++ installs many irrelevant packages

### ISSUE THREAD

**Issue by thatcadguy** [termux/termux-packages#3302]
**Problem description**
I was using node.js and needed to install g++ for node-gyp to build some packages, so I executed apt install g++ and was surprised to see everything that was included with it, e.g. php-pgsql, libpulseaudio, weechat, clang, gnuchess, nginx, unrar, etc.

**Steps to reproduce**
apt install g++

**Expected behavior**
Only packages needed and related to g++ to be installed.

**Additional information**
Post output of command `termux-info`.
Updatable packages:
All packages are up to date
System information:
Linux localhost 3.18.71-14274519 #1 SMP PREEMPT Tue Nov 27 11:42:58 KST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-G930V

**Comment by Herzogs** [comment]
Is this a bug? apt almost always recommends packages to install but if you want to ignore those recommendations there are two ways:
1) `pkg install --no-install-recommends g++`
2) in /usr/etc/apt.conf.d/apt.conf
 `APT::Install-Suggests "0";`
`APT::Install-Recommends "false";`

**Comment by xeffyr** [comment]
> Is this a bug?

No. When package is not found, **apt** will retry to find a package by converting your query to *regular expression*.

Just try the following:
* `apt install a++` - will trigger regex package search and fail
* `apt install tintin++` - will install package successfully

**Comment by david56048** [comment]
Just try the following:
`pkg install build-essential `
This command install g++
