### ISSUE TITLE
Package functional conflict between tsudo  and zsh

### ISSUE THREAD

**Issue by CaesarW** [termux/termux-packages#3304]
Android version: 8.1.0 Oreo Lineage OS.  
Termux latest version.

# Issue
I've installed `tsudo` and `zsh` from termux official repository. The issue occurs when I try to exit with CTRL + D, and zsh reports the error "zsh: failed to write history file /data/data/com.termux/files/home/.zsh_history: permission denied".
# Workarounds
I've checked the ownership and permission status of `.zsh_history` and it's all fine on both user and root (screenshots below).
![Screenshot](https://i.imgur.com/q2Uus4O.png)

I've also tried manually set 777 for `.zsh_history` and didn't work.  
Is it the incompatibility between `tsudo` and `zsh` that caused the problem?

Thanks.

**Comment by Grimler91** [comment]
Could you try applying this patch to the tsu script?
```diff
diff --git a/tsu b/tsu
index 650b903..eca1d5b 100644
--- a/tsu
+++ b/tsu
@@ -140,7 +140,7 @@ fi
 if [ -z "$USER_COMMAND" ]; then
   exec "$SU_BINARY" --preserve-environment -c "HISTFILE=$HOME/.$(basename $ROOT_SHELL)_history_root LD_LIBRARY_PATH=$OLD_LIBRARY_PATH PATH=$PATH $ROOT_SHELL"
 else
-  exec "$SU_BINARY" --preserve-environment -c "LD_LIBRARY_PATH=$OLD_LIBRARY_PATH PATH=$PATH $USER_COMMAND"
+  exec "$SU_BINARY" --preserve-environment -c "HISTFILE=$HOME/.$(basename $ROOT_SHELL)_history_root LD_LIBRARY_PATH=$OLD_LIBRARY_PATH PATH=$PATH $USER_COMMAND"
 
 fi
 
```
It's the same as commit https://github.com/cswl/tsu/commit/fc6d077490ac095d9db38958274e861bb99d821f in the tsu repo, but for the tsudo case.

**Comment by CaesarW** [comment]
Yup it worked!
Permission sets looks fine. But when applying the patch, `vim` highlighted the _**$(** _ basename..._**)** _ two brackets in red. A bit syntax error maybe?
Happy to see new update pushed.

**Comment by xeffyr** [comment]
> A bit syntax error maybe?

Command substitution is a *syntax error* ??

Little visualization how it works:
![2019-01-31 12-59-15](https://user-images.githubusercontent.com/25881154/52050113-32bb5b80-2558-11e9-8b95-12accb163048.png)

**Comment by xeffyr** [comment]
It just parentheses highlighting.

**Comment by Neo-Oli** [comment]
@CaesarW You probably don't have a Shebang set in your .zshrc. Therefore vim will think it's supposed to be a POSIX-compliant /bin/sh script. Parentheses expansion is not POSIX compliant but is available in bash and zsh. If you set the shebang and reload the file vim will stop highligthing them red.

**Comment by 532910** [comment]
`restorecon` should be used for repair .zsh_history, not `chmod`
