### ISSUE TITLE
Package request: Can we get the emacs-el noarch package?

### ISSUE THREAD

**Issue by KalmanReti** [termux/termux-packages#331]
Currently m-x org-agenda gets an error while requiring org-w3m;finding and/or fixing this requires the elisp source.

Thanks for your consideration (and for termux!).

**Comment by KalmanReti** [comment]
Actually, this may be a mistake. In my last emacs session several functions didn't show up with source files attached to the help documentation.  However, after restarting emacs, they now do.
Apologies for the noise.

**Comment by fornwall** [comment]
No problem! Let me know if anything else needs fixing!
