### ISSUE TITLE
ssh-agent dies on Andriod Pie without errors

### ISSUE THREAD

**Issue by arndtc** [termux/termux-packages#3311]
**Problem description**
Using Android Pie I am trying to run ssh-agent, but it keeps dying immediately though I didn't notice any errors.  I tied to connect to the agent and when it failed, I ran ps and there was no ssh-agent process running.  I don't get any errors, it just dies.  I can run ssh-agent on termux on my Chromebook without problems.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.
```
ssh-agent
ps
```

**Expected behavior**
I expected ssh-agent to run in the background.  This is what I see when running on my Chromebook.

**Additional information**
Post output of command `termux-info`.
```
Updatable packages:
All packages up to date
System information:
Linux localhost 4.9.146-perf-ge2a8febb9823 #1 SMP PREEMPT Fri Jan 11 12:44:06 IST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
Poco F1
```

I've also attached the output of strace.
[2019-02-02_-_strace-ssh-agent.log](https://github.com/termux/termux-packages/files/2824704/2019-02-02_-_strace-ssh-agent.log)

Let me know if you need anymore information.

**Comment by arndtc** [comment]
I tried `eval "$(ssh-agent -s)"` and still no luck.

**Comment by Quasic** [comment]
It was a long shot. Sorry. I am able to reproduce, though, on an Android 7 device. I had a problem, before, but just used .ssh/config to do what I needed before I realized it was a bug. strace looks very similar. armv7l

**Comment by Quasic** [comment]
Here's a log from working armv7l running Android 5.

**Comment by TheInfected** [comment]
> **Problem description**
> Using Android Pie I am trying to run ssh-agent, but it keeps dying immediately though I didn't notice any errors. I tied to connect to the agent and when it failed, I ran ps and there was no ssh-agent process running. I don't get any errors, it just dies. I can run ssh-agent on termux on my Chromebook without problems.
> 
> **Steps to reproduce**
> Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.
> 
> ```
> ssh-agent
> ps
> ```
> **Expected behavior**
> I expected ssh-agent to run in the background. This is what I see when running on my Chromebook.
> 
> **Additional information**
> Post output of command `termux-info`.
> 
> ```
> Updatable packages:
> All packages up to date
> System information:
> Linux localhost 4.9.146-perf-ge2a8febb9823 #1 SMP PREEMPT Fri Jan 11 12:44:06 IST 2019 aarch64 Android
> Termux-packages arch:
> aarch64
> Android version:
> 9
> Device manufacturer:
> Xiaomi
> Device model:
> Poco F1
> ```
> I've also attached the output of strace.
> [2019-02-02_-_strace-ssh-agent.log](https://github.com/termux/termux-packages/files/2824704/2019-02-02_-_strace-ssh-agent.log)
> 
> Let me know if you need anymore information.

I'm on Android Pie also there's no such problem for me

**Comment by arndtc** [comment]
@Quasic Thanks for confirming that you could reproduce the issue.  I tried doing a clean install and I also tried using both the Play Store and the Fdriod installs, and all of these produced the same results.  ssh-agent just dies immediately with not errors.

**Comment by Quasic** [comment]
@arndtc try ```ltrace ssh-agent```
[ltrace-ssh-agent-Nougat-armv7l.log](https://github.com/termux/termux-packages/files/2892591/ltrace-ssh-agent-Nougat-armv7l.log)
I think it may be a forking problem...

**Comment by xeffyr** [comment]
Yes, ssh-agent is not exist in task list. But **it is working**.

Little demonstration that it is really works, but it's pid is not visible:

1. Starting `ssh-agent`:
```
[~]:$ ssh-agent
SSH_AUTH_SOCK=/data/data/com.termux/files/usr/tmp/ssh-Dyr77a8PLzos/agent.4401; export SSH_AUTH_SOCK;
SSH_AGENT_PID=4402; export SSH_AGENT_PID;
echo Agent pid 4402;
```

2. Checking running tasks:
```
[~]:$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
u0_a502   4116  0.0  0.1  10596  4336 pts/0    S<s+  1970   0:00 /data/data/com.termux/files/usr/bin/bash -l
u0_a502   4344  0.0  0.0  15228  3008 ?        S<s   1970   0:00 sshd
u0_a502   4391  0.0  0.1  15228  5904 ?        R<s   1970   0:00 /data/data/com.termux/files/usr/bin/sshd -R
u0_a502   4392  0.0  0.1  10596  4444 pts/1    S<s   1970   0:00 /data/data/com.termux/files/usr/bin/bash -l
u0_a502   4404  0.0  0.0   9356  2736 pts/1    R<+   1970   0:00 ps aux
```
`ssh-agent` is not found in the output of `ps`.

3. `pidof` cannot find it too:
```
[~]:$ pidof ssh-agent
[~]:$
```

4. But kill command working fine:
```
[~]:$ kill -9 4402
[~]:$
```

5. One more time:
```
[~]:$ kill -9 4402
bash: kill: (4402) - No such process
```
Now it failed because process was killed in step 4.

**Comment by xeffyr** [comment]
Hidden PIDs are not a bug in the recent Android versions. Proc filesystem is highly restricted and you may not see some PIDs under certain conditions. Currently I don't know steps how to make PID invisible, but only that it is related to daemonizing.

Problem about hidden PIDs affects `tor` when it is running in daemon mode.

**There no workaround or fix without breaking program functionality.**

**Comment by Quasic** [comment]
@xeffyr, Thanks for the information! My problem I solved with the config file was related to using ssh via git. To use ssha with git, I'm going to try these config options:
`````shell
git config --global core.sshCommand ssha
git config --global ssh.variant ssh
`````
I'll see how it goes... working so far...

**Comment by xeffyr** [comment]
@Quasic Another variant is having `export SSH_AUTH_SOCK="$PREFIX/tmp/ssh-agent"` in bashrc. So you can avoid setting `core.sshCommand`. That what I have and it working fine. To initialize ssh-agent I need to use `ssha` (or any other compatible way to initialize ssh-agent) only one time and then just `ssh`.

It should be possible to enable initialization of ssh-agent with just bashrc so you will have to enter passwords only on Termux "cold" start.

**Comment by Quasic** [comment]
`. source-ssh-agent` in . bashrc seems to do the job for me, so far.
