### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by brianwoo** [termux/termux-packages#3312]
**Problem description**
Execute certain commands in Termux resulting "Illegal Instruction"

I also need to mention that the tablet is a non-Neon tablet.  However, after manually installing the 
base-pkgs-vfp.tar.gz package (mentioned in https://github.com/termux/termux-app/issues/916), the shell worked ok.  The problem happened when executing commands from newly installed packages (e.g. openssh / nano, etc.).

**Steps to reproduce**
type ssh at the prompt will result in "Illegal instruction"
or 
type nano at the prompt will result in "Illegal instruction"

**Expected behavior**
Expecting these programs will execute normally.

**Additional information**
Post output of command `termux-info`.

termux-info
Illegal instruction
Updatable packages:
All packages up to date
System information:
Linux localhost 3.1.10+ #1 SMP PREEMPT Sat Sep 30 17:46:27 EDT 2017 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.2
Device manufacturer:
Samsung
Device model:
GT-P7510

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
logcat -d "*:W"
--------- beginning of main
--------- beginning of crash
02-02 14:30:04.173 2013 2013 F libc : Fatal signal 4 (SIGILL), code 1, fault addr 0x2a00c06a in tid 2013 (ssh)
02-02 14:31:00.216 2629 2629 F libc : Fatal signal 4 (SIGILL), code 1, fault addr 0x2a01124c in tid 2629 (nano)
02-02 14:31:59.763 1363 1363 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
02-02 14:31:59.767 1363 1363 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
02-02 14:31:59.846 1363 1363 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
02-02 14:31:59.934 1363 1363 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
02-02 14:31:59.955 1363 1363 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
02-02 14:32:00.024 1363 1363 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
02-02 14:32:00.026 1363 1363 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
02-02 14:32:00.027 1363 1363 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
02-02 14:32:00.029 1363 1363 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
02-02 14:32:00.030 1363 1363 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
02-02 14:32:00.030 1363 1363 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
02-02 14:32:00.031 1363 1363 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
02-02 14:32:00.031 1363 1363 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
02-02 14:32:00.032 1363 1363 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
02-02 14:32:02.037 1363 1363 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
02-02 14:32:12.510 2715 2715 F libc : Fatal signal 4 (SIGILL), code 1, fault addr 0xb6c8253e in tid 2715 (apt)
02-02 14:32:12.765 2718 2718 F libc : Fatal signal 4 (SIGILL), code 1, fault addr 0xb6c8a53e in tid 2718 (apt)
02-02 14:32:40.791 1363 1363 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because ViewDragHelper did not receive all the events in the event stream.
02-02 14:32:40.791 1363 1363 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because ViewDragHelper did not receive all the events in the event stream.
02-02 14:32:40.791 1363 1363 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because ViewDragHelper did not receive all the events in the event stream.
02-02 14:32:40.791 1363 1363 E ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because ViewDragHelper did not receive all the events in the event stream.
02-02 14:32:56.538 1363 1363 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
02-02 14:32:56.539 1363 1363 W IInputConnectionWrapper: finishComposingText on inactive InputConnection

2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
strace -fv -s 2048 -o strace.log ssh
Illegal instruction

3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
We are not going to setup non-neon (vfp) repository. Sorry.

**Comment by FazeelSajid** [comment]
I also have this issue someone help me please

**Comment by xeffyr** [comment]
> I also have this issue someone help me please

See https://github.com/termux/termux-packages/issues/3312#issuecomment-460011270.
