### ISSUE TITLE
gnuplot doesn't work

### ISSUE THREAD

**Issue by nfuhriman2** [termux/termux-packages#3323]
When I run "gnuplot" command it immediately returns with "Bad system call". When I do an strace I see that it is killed by SIGSYS.
I'm on a OnePlus 5T with the latest firmware installed.
I've run "pkg upgrade" and there are no new packages to install.

**Comment by its-pointless** [comment]
fixed... in #3325.

**Comment by fornwall** [comment]
Thanks for reporting @nfuhriman2 !

The updated package version `5.2.6-1` by @its-pointless should fix the problem - install the update with `pkg up`.

**Comment by nfuhriman2** [comment]
That did it Thanks!
