### ISSUE TITLE
Volume Issue With CMUS on Termux

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#3334]
Hello,

I have been trying to utilize cmus as my daily music driver via Termux. However, the default keybindings for volume do not work.

Does this have anything to do with android media volume?

I have tried [ and ] as well as :vol vol +10% but no dice.

Thanks for reading my issue!

Sincerely,

Sam

**Comment by xeffyr** [comment]
Have you tried to increase **device/android** volume ?

**Comment by SBanya** [comment]
Is this done via a cmus bash command? Like, :vol device/android +10%?

**Comment by xeffyr** [comment]
Via `termux-volume` from Termux:API if installed. But primarily done via Android interface.
`cmus` as other cli programs doesn't know how to set volume in Android.

**Comment by SBanya** [comment]
Ok I'll try that. Yeah for some reason the volume button doesn't actually work in termux but I think that's obviously due to the shortcuts provided to work around the limited keyboard.

**Comment by tomty89** [comment]
The +/- keys work fine here (as well as []/{}) as expected. It manipulates the pulse sink-input volume so has nothing to do with Android.

**Comment by SBanya** [comment]
Hey tomty89, can you tell me how you were able to do this?

I tried this while a song is playing but nothing happened volume wise.

**Comment by tomty89** [comment]
Just press the keys on the keyboard? Maybe it's the keyboard app you uses that are problematic?

**Comment by SBanya** [comment]
Hello,

The only thing that's weird is that I'm just using the basic keyboard from Samsung S6 keyboard that came with my phone.

Is there a console command way to do this action in CMUS since I might have to rebind volume up and volume down in cmus?

**Comment by tomty89** [comment]
`:vol +/- 10%` work fine here

**Comment by Quasic** [comment]
```:vol +10%``` without spaces works for me, but the mixer seems to stop if I do it too fast, probably related to #3364
