### ISSUE TITLE
Package request:KeePass2

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#3339]
an unique password manager

**Package description**
Today you need to remember many passwords. You need a password for the Windows network logon, your e-mail account, your website's FTP password, online passwords (like website member account), etc. etc. etc. The list is endless. Also, you should use different passwords for each account. Because if you use only one password everywhere and someone gets this password you have a problem... A serious problem. He would have access to your e-mail account, website, etc. Unimaginable.
**Link to home page and sources**
1. Home page:https://keepass.info/
2. Source code:https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.41/KeePass-2.41-Source.zip/download

I need KeeAgent plugin for daily IT management

**Comment by Neo-Oli** [comment]
Is KeePass2 not primarily a Windows application? Can you not use one of the many alternative programs that are available for the Keepass2 key format? I think there are also some that work cli only

**Comment by Grimler91** [comment]
`kpcli` is one of those cli programs I guess, it was requested in https://github.com/termux/termux-packages/issues/2096

**Comment by xeffyr** [comment]
I looked at sources which are on the specified [SourceForge](https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.41/KeePass-2.41-Source.zip/download) link and it seems written entirely in C#.
It also requires GUI which makes it completely unsuitable for main Termux repository.

**Comment by Neo-Oli** [comment]
@xeffyr It is technically available for Linux with Mono, and I tried to use it under Linux before, it barely works.

**Comment by xeffyr** [comment]
@Neo-Oli Problem is that `mono` is not packaged.

**Comment by xeffyr** [comment]
Added KeePassXC to x11-repo.
```
pkg install x11-repo
pkg install keepassxc
```
Requires X11 environment either via VNC or XSDL of course, but package has a CLI variant as well.
