### ISSUE TITLE
offlineimap

### ISSUE THREAD

**Issue by Whishay** [termux/termux-packages#3345]
**Package description**
Describe what this package do and why it should be available.
an email client work with mainstream imap/pop mail servers.

**Link to home page and sources**
1. Home page:
http://www.offlineimap.org/

2. Source code:
https://github.com/OfflineIMAP/offlineimap/archive/v7.2.2.zip

**Additional information**
Have you compiled or tried to compile the package on device?
Have not tried it, any link on how to? I would like to give it a shot, thanks a lot.

**Comment by Wetitpig** [comment]
Check this #3336

**Comment by Whishay** [comment]
> @Whishay Check [this](#3336) for build instructions.

The link takes me back to this issue, is it the guide the one to build it in termux? or I need to do cross-compile? 

My question is that if I can do it within termux? this should have been supported since gcc is already available, right?

**Comment by Wetitpig** [comment]
> > @Whishay Check [this](#3336) for build instructions.
> 
> The link takes me back to this issue, is it the guide the one to build it in termux? or I need to do cross-compile?
> 
> My question is that if I can do it within termux? this should have been supported since gcc is already available, right?

Sorry. The PR has been closed and the link should work now.

By the way, building within termux is not supported because GCC is not formally provided by Android or Termux. It is only provided by third-party repositories. An independent toolchain in Ubuntu is expected.

**Comment by xeffyr** [comment]
What problem with using **clang** instead of GCC ?  With clang it is possible to compile many (if not most) of available open source programs.

**Comment by xeffyr** [comment]
It's a python2 package, so just installed it via `pip2`.

1. Offlineimap has dependency "six" but it not getting installed for some reason. Doing manually:
```
pip2 install six
```

2. Installing offlineimap:
```
pip2 install offlineimap
```

***

Closing since we do not package python modules (though, unless it is a high priority thing).
