### ISSUE TITLE
dpkg Error

### ISSUE THREAD

**Issue by KANG-NEWBIE** [termux/termux-packages#3348]
dpkg: error processing package bash (--configure):
 unable to change ownership of target file '/data/data/com.termux/files/usr/etc/bash.bashrc.dpkg-new': Operation not permitted
Errors were encountered while processing:
 bash
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

Help me please

**Comment by Grimler91** [comment]
Have you run apt/dpkg as root? Easiest fix is to reinstall termux/delete $PREFIX and avoid root in the future

**Comment by xeffyr** [comment]
@Grimler91 Maybe we need to patch apt/dpkg to completely prevent it's usage as root ?

**Comment by Grimler91** [comment]
@xeffyr yeah, that would be good, as we do for `pkg`
