### ISSUE TITLE
vim-python error: after upgrade to version 8.1.0900

### ISSUE THREAD

**Issue by amsitlab** [termux/termux-packages#3357]
vim-pyhon error , after saving file with `:wq` hotkeys.
```Vim: Caught deadly signal ABRT
Vim: Finished.```

**Comment by xeffyr** [comment]
> after saving file with `:wq` hotkeys.

`:wq` stands here for **write** and **quit**. So if vim gets closed, it is okay.
I have no problem with vim or vim-python.
