### ISSUE TITLE
Request: vimtutor

### ISSUE THREAD

**Issue by reggi** [termux/termux-packages#336]
I'd love to get access to the `vimtutor` within termux. I know it's just a file. 

Ideas?

**Comment by fornwall** [comment]
If you install vim with `apt install vim` you should be able to run `vimtutor`, as it is part of the vim package. Does that work for you?

**Comment by reggi** [comment]
@fornwall  Thanks for the response!

Seems I've already installed vim and when I tun vimtutor I get a blank file.

**Comment by fornwall** [comment]
Can you press the enter key to continue from the blank file and get to the vimtutor contents? If not, is the screen totally blank, or is some text displayed?

**Comment by reggi** [comment]
These two screens flash, hope this helps.

![media-20160620-1](https://cloud.githubusercontent.com/assets/296798/16180815/17d045b0-365e-11e6-82a0-e5045764f171.png)
![media-20160620](https://cloud.githubusercontent.com/assets/296798/16180817/192d35f8-365e-11e6-8a6f-377bc68286e1.png)

**Comment by fornwall** [comment]
Is your vim package up to date (can you run `apt update && apt upgrade` and try again)?

**Comment by z3ntu** [comment]
`vimtutor` works for me
