### ISSUE TITLE
How to run old version package?

### ISSUE THREAD

**Issue by fast0490f** [termux/termux-packages#3363]
Hi, I won't run nodejs 8.5.0 is it possible to do it somehow?

**Comment by Wetitpig** [comment]
I am not sure if the old packages are archived... maybe they have been deleted already.

**Comment by Grimler91** [comment]
Yes, only way to obtain another version of nodejs is to build it yourself. You could also open a package request in https://github.com/termux/unstable-packages, if people want the package then we can add it.

Archiving old packages doesn't make much sense as one would then have to install the old package and old versions of all dependencies, which would brake other newer packages
