### ISSUE TITLE
libpulseaudio/cmus problem?

### ISSUE THREAD

**Issue by Quasic** [termux/termux-packages#3364]
What is going on here? I don't know much about pulseaudio...
Logcat:
`````
02-19 22:21:37.716 20909 20909 W syslog  : /data/data/com.termux/files/usr/libexec/pulseaudio - [pulseaudio] core.c: Failed to allocate shared posix-shm memory pool. Falling back to a normal memory pool.
02-19 22:21:37.717 20909 20909 E syslog  : /data/data/com.termux/files/usr/libexec/pulseaudio - [pulseaudio] main.c: Daemon startup without any loaded modules, refusing to work.
02-19 22:21:37.718 20906 20906 E syslog  : /data/data/com.termux/files/usr/libexec/pulseaudio - [pulseaudio] main.c: Daemon startup failed.
`````
Android 7, was trying cmus, which said only Internal Error

**Comment by Quasic** [comment]
After pkg in pulseaudio
`````
$ pulseaudio
W: [pulseaudio] core.c: Failed to allocate shared posix-shm memory pool. Falling back to a normal memory pool.
W: [pulseaudio] authkey.c: Failed to open cookie file '/data/data/com.termux/files/home/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/data/data/com.termux/files/home/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/data/data/com.termux/files/home/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/data/data/com.termux/files/home/.pulse-cookie': No such file or directory
`````

**Comment by Quasic** [comment]
After uninstalling pulseaudio, it doesn't work again.

**Comment by Grimler91** [comment]
I think I ran into this long ago, several times. Rebooting device solved it. I'm guessing something is running in the background and causing problems when running pulseaudio

**Comment by Quasic** [comment]
Restarting has made it work without running `pulseaudio` after that error happened twice, so that's probably it. Thanks, @Grimler91!

Only one thing... I tried uninstalling pulseaudio again, and it seems to break something. I guess I'll leave it for now, but maybe I'll try reinstalling libpulseaudio afterwards, sometime.

**Comment by tomty89** [comment]
Not sure I get what's happening here. So you rely on autospawn to start pulse, but changing volume in cmus sometimes crashes pulse, and autospawn stopped working until you reboot?

First of all recently the sink modules for Android have been revamped (#3391), crashes related to sink input changes should have been fixed (but the prebuilt packages are not up yet).

I am not sure what the installing/uninstalling of `pulseaudio` package is about here. While cmus depends only on `libpulseaudio`, `pulseaudio` is required for it to actually work (as cmus doesn't have native opensles output driver like mpv or mpd does). Pragmatically speaking, we may want to make cmus depend on `pulseaudio`.

As for the rebooting / autospawn stopped working part, I have no idea about it. If you want to find out more about it, you may want to add `-vvv` when you run `pulseaudio` (and/or add it to `extra-arguments` in $PREFIX/etc/pulse/client.conf for autospawn).

**Comment by Quasic** [comment]
@tomty89, thanks for the information! I gather autospawn means starting pulseaudio on demand. I didn't know this was a requirement of cmus. My main problem, then, is that pulseaudio wasn't installed when I installed cmus. The other problems were either from me playing with stuff or unrelated to this problem, and should probably be in a separate issue, if necessary after the upcoming package update. Thanks again. I'll submit a pull request adding pulseaudio as a dependency.

**Comment by Quasic** [comment]
#3439 has been merged, so I am closing this.

**Comment by fornwall** [comment]
cmus 2.8.0 is now available, run `pkg up` to update!

**Comment by Quasic** [comment]
cmus 2.8.0 seems to be working great! Thanks again, everyone!
