### ISSUE TITLE
Https for apache2 server

### ISSUE THREAD

**Issue by Marcus0086** [termux/termux-packages#3367]
I've configured the whole server for port 8080 and it just works fine but it is still http but i need https for some experiments and when i look into extra folder there was httpd-ssl.conf file and I've also configured it. I've also configured it to use ssl certificate and key and also loaded all the mentioned modules (mod_ssl) but when i run it on port 8443 it starts and by doing nmap my network there is a opened port 8843 followed by https-alt but when i open it in browser it always gives ssl error that this site sends an invalid response and there is no way to bind through port 443 without root access. Can somebody plss help me.

**Comment by xeffyr** [comment]
> gives ssl

Self signed SSL certificate will always give error.

**Comment by Marcus0086** [comment]
Okk so can i use burpsuite certificate and key

**Comment by xeffyr** [comment]
To use a self-signed certificate, install it to Android (as I know it is Settings => Security => Certificates => User certificates).

> burpsuite certificate

It is self-signed anyway.
Trusted SSL certificates can be obtained only from the certificate authority such as [Let's encrypt](https://letsencrypt.org/) (free) or any other (paid).
