### ISSUE TITLE
Request Package: D8/R8

### ISSUE THREAD

**Issue by amsitlab** [termux/termux-packages#3371]
Android have new dextools D8/R8.
D8/R8 will helpfull to buiding apks on termux.

**Comment by xeffyr** [comment]
It is in disabled-packages: https://github.com/termux/termux-packages/tree/master/disabled-packages/d8

**Comment by amsitlab** [comment]
Can I install it? How?

**Comment by fornwall** [comment]
Closing this in favour of #4927.
