### ISSUE TITLE
Squid  

### ISSUE THREAD

**Issue by ulist** [termux/termux-packages#3372]
```python
$ squid
Aborted
$ squid -z
2019/02/22 16:13:41| FATAL: Squid is already running: Found fresh instance PID file (/data/data/com.termux/files/usr/var/run/squid.pid) with PID 24435
    exception location: src/Instance.cc(121) ThrowIfAlreadyRunningWith

Aborted
```
what about use Android application 🤔

**Comment by xeffyr** [comment]
> `Squid is already running: Found fresh instance PID file (/data/data/com.termux/files/usr/var/run/squid.pid) with PID 24435`

Looks like you have already running instance of `squid`.
Before starting new, try to stop it with `killall -9 squid`.
