### ISSUE TITLE
help me please ....????

### ISSUE THREAD

**Issue by yasidhanie** [termux/termux-packages#3375]
Exec ("/data/data/com.termux/files/usr/bin/login") permission denied

**Comment by xeffyr** [comment]
Maybe you finish with posting duplicates ? (https://github.com/termux/termux-exec/issues/15)

> Exec ("/data/data/com.termux/files/usr/bin/login") permission denied

provides for us ZERO information about the problem.
Probably best way for you will be to **re-install Termux**.
