### ISSUE TITLE
Segmentation fault new Ruby Interpreter v. 2.6.1

### ISSUE THREAD

**Issue by skrmnz** [termux/termux-packages#3380]
Every action with the new Ruby Version 2.6.1 gives back a segmentation fault, just that nothing more. Reinstallation of the package or app does not help.

**Comment by xeffyr** [comment]
Confirming that it segfaults on ARM.

**Comment by skrmnz** [comment]
Full Text Search... Done
ruby/stable,now 2.6.1 arm [installed]
  Dynamic programming language with a focus on simplicity and productivity

ruby-dev/stable 2.6.1 arm
  Development files for ruby

ruby-ri/stable 2.6.1 all
  Ruby documentation index

weechat-ruby-plugin/stable 2.4 arm
  WeeChat Ruby Plugin

$ ruby
Segmentation fault
$

**Comment by skrmnz** [comment]
yes, on ARM

**Comment by xeffyr** [comment]
Looks like it can be fixed by changing optimization level. As I know we had similar issues in the past.
```
@@ -23,6 +24,7 @@ termux_step_pre_configure() {
        if [ "$TERMUX_ARCH_BITS" = 32 ]; then
                # process.c:function timetick2integer: error: undefined reference to '__mulodi4'
                TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" rb_cv_builtin___builtin_mul_overflow=no"
+               CFLAGS="${CFLAGS/-Os/-Oz}"
        fi
 }
```

I'll upload fixed packages to the [unstable-repo](https://github.com/termux/unstable-repo) so fix will be available before it will get merged to the main repository.

**Comment by xeffyr** [comment]
Try to do now
```ShellSession
pkg install unstable-repo
pkg upgrade
```

**Comment by skrmnz** [comment]
wow thank you :)

**Comment by aniketstark** [comment]
Nope is unstable
I tried its sucks again

**Comment by skrmnz** [comment]
so you have tried:
pkg install unstable-repo
pkg upgrade
But it still doesn't work?
it worked for me this way

**Comment by xeffyr** [comment]
@skrmnz He likely get different issue (with metasploit ?).

**Comment by aniketstark** [comment]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

**Comment by handsomebeast** [comment]
When I gave unstable-repo command then my metasploit showing metasploit-credential not in bundle

**Comment by xerofMo** [comment]
I had msfconsole on my nonrooted j5 running well until i needed impacket so i installed it
Ever since rubygems are printing segmentation fault.

 Unstable repo fixed the issue.

Thank you

**Comment by IFab967** [comment]
In try use that commands in my termux, but when all are installed show a error in metasploit, and msfvenom. I have Android Oreo, With 32 bits. Exist another form to fix this?, Before of the update, my metasploit was worked good

**Comment by fornwall** [comment]
The updated version 2.6.1-2 of the ruby package is now available for installation - run `pkg up` to update.

Let us know if the problem remains after that update.

**Comment by skrmnz** [comment]
ruby/stable,now 2.6.1-2 arm [installed]
  Dynamic programming language with a focus on simplicity and productivity
$ ruby -e "puts(RUBY_VERSION)"
2.6.1

seems everything works fine :)

**Comment by fornwall** [comment]
@skrmnz Great, thanks!

**Comment by IFab967** [comment]
I still have the same problem, error text: 
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager

and in msfvenom: /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so (LoadError)

And when I use gem install rubygems-update 
I have to stop, and execute the script again to install these gems.

My system operative is of 32 bits, Android 8.0 

I hope it can be solved, and I appreciate the help ;)

**Comment by Grimler91** [comment]
@xtkoba interesting, emacs also crashes with setjmp: https://github.com/termux/termux-packages/issues/2599, on arm and i686, unless configured with `emacs_cv_func__setjmp=no emacs_cv_func_sigsetjmp=no`
