### ISSUE TITLE
MariaDB Issues

### ISSUE THREAD

**Issue by spectrumcomputing** [termux/termux-packages#3387]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.
Errors when trying to install MariaDB (I'm using Android App downloaded from Play Store (Update 20 Jan 2019)

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.
pkg install mariadb

**Expected behavior**
Installation of mariadb

**Additional information**
Post output of command `termux-info`.
`Initializing mysql data directory...
/data/data/com.termux/files/usr/bin/my_print_defaults: Can't read dir of '/data/data/com.termux/files/usr/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted
Installing MariaDB/MySQL system tables in '/data/data/com.termux/files/usr/var/lib/mysql' ...
/data/data/com.termux/files/usr/bin/mysqld: Can't read dir of '/data/data/com.termux/files/usr/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted

Installation of system tables failed!  Examine the logs in
/data/data/com.termux/files/usr/var/lib/mysql for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /data/data/com.termux/files/usr/bin/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /data/data/com.termux/files/usr/bin/mysqld --skip-grant-tables --general-log &

and use the command line tool /data/data/com.termux/files/usr/bin/mysql
to connect to the mysql database and look at the grant tables:

    shell> /data/data/com.termux/files/usr/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /data/data/com.termux/files/usr/var/lib/mysql that may be helpful.`

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
If you won't fill template as it should, I'll close this issue.

**Comment by xeffyr** [comment]
@spectrumcomputing If you won't fill template as it should, I'll close this issue.

**Comment by spectrumcomputing** [comment]
Problem Description
Errors when trying to install MariaDB (I'm using Android App downloaded from Play Store (Update 20 Jan 2019)

Steps to reproduce
pkg install mariadb

Expected behavior
Installation of mariadb

Additional Information
`Initializing mysql data directory...
/data/data/com.termux/files/usr/bin/my_print_defaults: Can't read dir of '/data/data/com.termux/files/usr/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted
Installing MariaDB/MySQL system tables in '/data/data/com.termux/files/usr/var/lib/mysql' ...
/data/data/com.termux/files/usr/bin/mysqld: Can't read dir of '/data/data/com.termux/files/usr/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted

Installation of system tables failed!  Examine the logs in
/data/data/com.termux/files/usr/var/lib/mysql for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /data/data/com.termux/files/usr/bin/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /data/data/com.termux/files/usr/bin/mysqld --skip-grant-tables --general-log &

and use the command line tool /data/data/com.termux/files/usr/bin/mysql
to connect to the mysql database and look at the grant tables:

    shell> /data/data/com.termux/files/usr/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /data/data/com.termux/files/usr/var/lib/mysql that may be helpful.`

**Comment by spectrumcomputing** [comment]
> @spectrumcomputing If you won't fill template as it should, I'll close this issue.

Sorry, I was gathering all the information.

**Comment by xeffyr** [comment]
Try to
```
mkdir -p /data/data/com.termux/files/usr/etc/my.cnf.d
```
and then reinstall mariadb.

**Comment by spectrumcomputing** [comment]
$ termux-info
Updatable packages:
apt/stable 1.4.9 arm [upgradable from: 1.4.8-9]
bash/stable 4.4.23-4 arm [upgradable from: 4.4.23-3]
busybox/stable 1.30.1 arm [upgradable from: 1.29.3-1]
dpkg/stable 1.19.4 arm [upgradable from: 1.19.2]
gpgv/stable 2.2.13 arm [upgradable from: 2.2.12]
libcurl/stable 7.64.0 arm [upgradable from: 7.63.0]
libgpg-error/stable 1.35 arm [upgradable from: 1.34]
System information:
Linux localhost 3.18.71-perf-g08fffa4 #1 SMP PREEMPT Fri Jan 11 04:53:30 CST 2019 armv7l Android
Termux-packages arch:
arm
Android version:
8.0.0
Device manufacturer:
motorola
Device model:
moto g(6)
$

**Comment by spectrumcomputing** [comment]
> Try to
> 
> ```
> mkdir -p /data/data/com.termux/files/usr/etc/my.cnf.d
> ```
> and then reinstall mariadb.

OK, just trying now.

**Comment by spectrumcomputing** [comment]
Sorry, how do I run as sudo? I get permission denied?

**Comment by spectrumcomputing** [comment]
$ mkdir -p /data/data/com.termax/files/usr/etc/my.cnf.d
mkdir: can't create directory '/data/data/com.termax/': Permission denied

**Comment by xeffyr** [comment]
You have typo: com.termax should be com.termux.
Or try:
```
mkdir -p $PREFIX/etc/my.cnf.d
```

**Comment by spectrumcomputing** [comment]
Thanks!  Apologies.  OK, than ran now I have:

$ mkdir -p /data/data/com.termux/files/usr/etc/m$ mysql -u root
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/data/data/com.termux/files/usr/tmp/mysqld.sock' (2)

**Comment by spectrumcomputing** [comment]
Seems to be something from 2017 here which I just found:

https://hackermindsite.wordpress.com/2017/09/26/first-blog-post/

**Comment by xeffyr** [comment]
Seems to be fixed.

**Comment by Sasmitadn** [comment]
Error 2002

Try 
mysqld

And open new window

mariadb

Done
