### ISSUE TITLE
Metasploit no longer runs!!!

### ISSUE THREAD

**Issue by voldemort1912** [termux/termux-packages#3394]
**Problem description**
A week before today...metasploit framework used to run fine on my device SM-N9208 running Android 8.0 Oreo but recently...it started giving me errors and fails to run

**Steps to reproduce**
follow the wiki to install metasploit using the automatic script

**Expected behavior**
Metasploit runs successfully

**Additional information**
Post output of command `termux-info`.
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.61-Helios_Kernel-V1.0-N920C-20181224 #9 SMP PREEMPT Mon Dec 24 14:20:45 UTC 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-N935F
D
![screenshot_20190227-015416_termux](https://user-images.githubusercontent.com/47709143/53453271-a1051800-3a49-11e9-81cf-e9d13ab1fddf.jpg)
epending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by voldemort1912** [comment]
I believe this is caused due to the recent ruby update?

**Comment by xeffyr** [comment]
Metasploit is not official package for Termux.

**Comment by 21MRunknown12** [comment]
what's the fix for that ?
