### ISSUE TITLE
Right and left arrow buttons needed

### ISSUE THREAD

**Issue by canklot** [termux/termux-packages#3398]
New version of termux have up and down arrow buttons. And also ctrl alt etc. 
But there is no left and right button and it would be very helpful with editing documents with nano

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by xeffyr** [comment]
After implementing extra keys configuration, you have to enable necessary keys manually.

**Comment by hichemkanon** [comment]
https://github.com/htr-tech/termux-key
