### ISSUE TITLE
g++ won't compile hello word

### ISSUE THREAD

**Issue by Ralayax** [termux/termux-packages#34]
Hello,
First of all, well done your software is awesome !
I encounter a problem with g++

main.cpp :
#include <iostream>

int main(int argc, char** argv){
        std::cout << "bigboy" << std::endl;
}

$ g++ main.cpp -o main
/data/data/com.termux/files/usr/tmp//ccLwzPUy.o: In function `main':
main.cpp:(.text+0x34): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
main.cpp:(.text+0x4c): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
main.cpp:(.text+0x64): undefined reference to `std::cout'
main.cpp:(.text+0x6c): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
/data/data/com.termux/files/usr/tmp//ccLwzPUy.o: In function `__static_initialization_and_destruction_0(int, int)':
main.cpp:(.text+0xb4): undefined reference to `std::ios_base::Init::Init()'
main.cpp:(.text+0xf4): undefined reference to `std::ios_base::Init::~Init()'
collect2: error: ld returned 1 exit status

Everything seems like the std lib isn't installed.
The thing is I can't find any matching package.

**Comment by Ralayax** [comment]
Of course I've already fucked up my report, I meant #include <iostream>

**Comment by fornwall** [comment]
The Android system C++ library is basic, without support for STL - see http://developer.android.com/ndk/guides/cpp-support.html.

To use e.g. std::cout you need to compile against libgnustl_shared.so (install by running `apt install libgnustl`), so your complete command would be `g++ main.cpp -lgnustl_shared -o main`. Does that resolve the problem for you?

There has been a wish for making that clearer already in https://github.com/termux/termux-packages/issues/33, I will probably setup a wiki of some sort for this kind of information.

**Comment by Ralayax** [comment]
Works perfectly ! Thank you very much !
Yes it might be a good idea to do so.
