### ISSUE TITLE
Ruby Downgrade

### ISSUE THREAD

**Issue by RootSh311** [termux/termux-packages#3402]
Help Needed
Ruby Is Not Working. Tried Unstabble Version Of Ruby Is There Any Way To Downgrade Ruby. I Really Need This Fix
![screenshot_20190228-001223](https://user-images.githubusercontent.com/47913604/53512936-30640700-3aee-11e9-9a7e-7693f1ed048a.png)
![screenshot_20190228-001203](https://user-images.githubusercontent.com/47913604/53512984-47a2f480-3aee-11e9-8d1d-b738ef065cae.png)
![screenshot_20190228-001128](https://user-images.githubusercontent.com/47913604/53512997-4d98d580-3aee-11e9-9ab3-a14d9a0acb7e.png)

**Comment by xeffyr** [comment]
No, downgrade is impossible unless you compile ruby package on your own.

**Comment by RootSh311** [comment]
can you make a downgraded ruby compiled file
