### ISSUE TITLE
Tmux-bunch error 

### ISSUE THREAD

**Issue by handsomebeast** [termux/termux-packages#3407]
Same error like metasploit 
[*] Please wait while binding.......🕜

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Traceback (most recent call last):
        29: from ./msfvenom:445:in `<main>'
        28: from ./msfvenom:55:in `framework'
        27: from ./msfvenom:36:in `init_framework'
        26: from ./msfvenom:18:in `require_deps'
        25: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        24: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        23: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:18:in `<top (required)>'
        22: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:18:in `require'
        21: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'
        20: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        19: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `<top (required)>'
        18: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails.rb:11:in `<top (required)>'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails.rb:11:in `require'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/application.rb:7:in `<top (required)>'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/application.rb:7:in `require'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/engine.rb:1:in `<top (required)>'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/engine.rb:1:in `require'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/railtie.rb:2:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/railtie.rb:2:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/configuration.rb:2:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-4.2.11/lib/rails/configuration.rb:2:in `require'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object.rb:12:in `<top (required)>'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object.rb:12:in `require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/json.rb:4:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/json.rb:4:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `<top (required)>'
         2: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `require'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
/data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `require': dlopen failed: invalid ELF file "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so" load segment[8]: p_offset (0x2000) + p_filesz (0x270) ( = 0x2270) past end of file (0x2270) - /data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so (LoadError)
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
java.io.FileNotFoundException: /data/data/com.termux/files/home/Tmux-Bunch/unsign/Acmarket.apk (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.jar.JarFile.<init>(JarFile.java:154)
        at java.util.jar.JarFile.<init>(JarFile.java:133)
        at com.android.signapk.SignApk.main(SignApk.java:949)
rm: cannot remove '/data/data/com.termux/files/home/Tmux-Bunch/unsign/Acmarket.apk': No such file or directory

 We will met again :D , have a payload day..! 📢

 press ENTER for main menu

**Comment by xeffyr** [comment]
We don't have tmux-bunch.
Ask in https://github.com/Hax4us/Tmux-Bunch.

**Comment by handsomebeast** [comment]
Ohhk but solve my bigdecimal gem prblm

**Comment by lolodude** [comment]
i havve this problm too
