### ISSUE TITLE
rsync error: syntax or usage error (code 1)

### ISSUE THREAD

**Issue by Sysetup** [termux/termux-packages#3408]
When this command is used from Termux (device 1) to other Termux (device 2) rsync works fine:

`rsync -avzh u0_a93@domain.com:/data/data/com.termux/files/home/Documents .`

But when is used the same command from other OS like Debian 9 or macOS Mojave to Termux, it reports: 

```
rsync error: syntax or usage error (code 1) at /home/fornwall/.termux-build/rsync/src/main.c(1578) [server=3.1.3]
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.3]
```

rsync has been updated on Debian from 3.1.2 to 3.1.3 but the error persists.

**Comment by xeffyr** [comment]
I use rsync on Termux so far and never seen issue like this. No matter if I use it like termux <==> termux or  termux <==> PC (Arch Linux).

Are you running rsync daemon on the remote end ? Or just rsync over SSH ?

**Comment by Sysetup** [comment]
Yes, I'm getting this error from Debian and Mac. I have not set rsync as daemon, I have only installed it in Termux which is working as server now. 

If the option -e ssh is set with rsync command, after the password is typed the same error is printed:

```
rsync: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
rsync error: syntax or usage error (code 1) at /home/fornwall/.termux-build/rsync/src/main.c(1578) [server=3.1.3]
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.3]
```


`rsync -avzhe ssh u0_a93@domain.com:/data/data/com.termux/files/home/Documents .`

When a conventional ssh command is run to Termux I can connect normally.

`ssh domain.com` Works!

**Comment by xeffyr** [comment]
> This rsync lacks old-style --compress due to its external zlib.

Can you try without compression ?

**Comment by Sysetup** [comment]
Yeah man, without compression works, maybe do you know why?

**Comment by xeffyr** [comment]
> maybe do you know why?

Termux uses Android's zlib which is not same on different devices and likely this is a problem. There previously were zlib-related problems like https://github.com/termux/termux-packages/issues/2922.

**Comment by Sysetup** [comment]
Thank you @xeffyr for your assistance. Have a successful day.

**Comment by xeffyr** [comment]
Today had catched similar error and it looks like solution was provided in the error message.
> This rsync lacks old-style --compress due to its external zlib.  Try -zz.

So just pass `-zz` instead of `-z`.
