### ISSUE TITLE
Request Package: intltool

### ISSUE THREAD

**Issue by duzhaokun123** [termux/termux-packages#3409]
**Package description**
intltool is a set of tools to centralize translation of many different file formats using GNU gettext-compatible PO files.

The intltool collection can be used to do these things:

Extract translatable strings from various source files (.xml.in, glade, .desktop.in, .server.in, .oaf.in).
Collect the extracted strings together with messages from traditional source files (.c, .h) in po/$(PACKAGE).pot.
Merge back the translations from .po files into .xml, .desktop and oaf files. This merge step will happen at build resp. installation time.

**Link to home page and sources**
1. Home page:[https://freedesktop.org/wiki/Software/intltool/](https://freedesktop.org/wiki/Software/intltool/)
2. Source code:[https://launchpad.net/intltool/+download](https://launchpad.net/intltool/+download)

**Comment by tomty89** [comment]
The problem is intltool requires the XML::Parser perl module, for which our policy is not to package any but expect user to just get/build with `cpan`. (The module and its dependencies take much longer build than intltool itself anyway.)

**Comment by Grimler91** [comment]
See also https://github.com/termux/termux-packages/issues/776
