### ISSUE TITLE
sshd ignores TERM

### ISSUE THREAD

**Issue by rqcy** [termux/termux-packages#341]
It seems that TERM is always set to `xterm-256color' when logging in with ssh, e.g.,

    $ TERM=dumb ssh android_phone.local
    $ echo $TERM
    xterm-256color

Shouldn't TERM be set to `dumb'?

**Comment by fornwall** [comment]
Thanks - this should now work in the latest 7.2p2-5 version of the openssh package. Update to it with apt update && apt upgrade and make sure to kill any old sshd server process with killall -9 sshd before starting sshd again after updating.

Let me know if there are any remaining problem!

**Comment by rqcy** [comment]
Thanks the quick fix -- it works now! :)
