### ISSUE TITLE
error in project

### ISSUE THREAD

**Issue by tylershi** [termux/termux-packages#3410]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by tylershi** [comment]
LDAPException(resultCode=21 (invalid attribute syntax), diagnosticMessage='description: value #0 invalid per syntax', ldapSDKVersion=4.0.9, revision=29290)

how to solve this problem

**Comment by Grimler91** [comment]
We need more information than this. What are you running? How are you encountering the error?

You posted the issue template, it has lots of tips for what to include in a good bug report, like output of `termux-info`.

A quick google search shows this stackexchange thread with the same error: https://stackoverflow.com/questions/44500052/ldap-exception-invalid-value-0-per-syntax
