### ISSUE TITLE
Octave update 4.4.1-5 broken

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#3413]
octave: no graphical display found
octave: disabling GUI features
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-4.4.1": library "libreadline.so.8" not found
Aborted

**Comment by xeffyr** [comment]
Octave is a third-party package. If you installed it from https://github.com/its-pointless/its-pointless.github.io, ask @its-pointless to rebuild it.
