### ISSUE TITLE
Readline version 8 required for Octave. 

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#3415]
octave
octave: no graphical display found
octave: disabling GUI features
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-4.4.1": library "libreadline.so.8" not found

**Comment by xeffyr** [comment]
Ask @fornwall about it.
It has been released for AArch64 yesterday. For other architectures it will be released later.
