### ISSUE TITLE
ruby 2.6.1 segfaults

### ISSUE THREAD

**Issue by csabahenk** [termux/termux-packages#3417]
I just upgraded ruby to 2.6.1 (along all other packages with a `pkg up`) and it segfaults immediately and unconditionally:

```
ruby -e 'puts "hello world"'
[1]    31332 segmentation fault  ruby -e 'puts "hello world"'
```

**Comment by Grimler91** [comment]
I'm guessing you are on arm. We merged a fix for seg fault for arm recently: https://github.com/termux/termux-packages/issues/3380, updated package should be available within a day of so

**Comment by xeffyr** [comment]
Fix also available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg upgrade
```

That is if you can't wait until ruby gets updated in main repository.

**Comment by csabahenk** [comment]
Thank you, I got the update, now it works.
