### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by nasirxo** [termux/termux-packages#3418]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by Grimler91** [comment]
You can install heroku through npm. See also https://github.com/termux/termux-packages/issues/853.
