### ISSUE TITLE
fcgiwrap

### ISSUE THREAD

**Issue by vstavrinov** [termux/termux-packages#3422]
fcgiwrap is a simple server for running CGI applications over FastCGI.
 Its goal is to provide clean CGI support to the nginx webserver, although
 can be used with others.
 .
 fcgiwrap is lightweight and has no configuration, making it possible to
 use the same pool to run different sites.

Homepage: 

https://github.com/gnosek/fcgiwrap

I am using it for number of tasks: testing, development, site scraping etc. It is actually debian package working for me for a years:

https://packages.debian.org/search?keywords=fcgiwrap&searchon=names&suite=all&section=all

**Comment by xeffyr** [comment]
Added in https://github.com/termux/termux-packages/commit/83db0c11995bb920fe151da62f968a394fc4aaeb. `pkg install fcgiwrap`.

For installations using android-5 branch will be available after merging https://github.com/termux/termux-packages/pull/4015.
