### ISSUE TITLE
Can't start msfconsole

### ISSUE THREAD

**Issue by akiraaranii** [termux/termux-packages#3425]
msfconsole

[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `grpc.gemspec`: cannot load such file -- grpc/version
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/grpc.gemspec:4
 #  -------------------------------------------
 #  $LOAD_PATH.push File.expand_path('../src/ruby/lib', __FILE__)
 >  require 'grpc/version'
 #
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/Gemfile:4
 #  -------------------------------------------
 #  #   spec.add_runtime_dependency '<name>', [<version requirements>]
 >  gemspec name: 'metasploit-framework'
 #
 #  -------------------------------------------

**Comment by Grimler91** [comment]
Have you installed metasploit from [unstable-packages](github.com/termux/unstable-packages)? I guess not. Do that and try again (see wiki for instructions: https://wiki.termux.com/wiki/Metasploit_Framework)
