### ISSUE TITLE
Problem in Metasploit installing

### ISSUE THREAD

**Issue by Sam3ghost** [termux/termux-packages#3430]
Please help me, I'm having this problem :"
An error occurred while installing sqlite3 (1.3.13), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.3.13' --source 'https://rubygems.org/'` succeeds
before bundling.

**Comment by xeffyr** [comment]
Do not install metasploit manually if you don't know how to install it's deps.
Use
```
pkg install unstable-repo
pkg install metasploit
```

Since metasploit was packaged for Termux, all other installation methods getting obsolete in near future.

**Comment by Sam3ghost** [comment]
I have a problem with the package 
    "pkg install unstable-repo"
Error: Unable to locate package unstanle-repo

**Comment by xeffyr** [comment]
> Unable to locate package unstanle-repo

Typo ???
