### ISSUE TITLE
metasploit-credential not in the bundle

### ISSUE THREAD

**Issue by IFab967** [termux/termux-packages#3437]
I have this problem when I try to use my msfconsole, after install the last version of Ruby, I don't know why this is happening, the error text is:
`metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager`

`undefined method without for #<Bundler::Settings:0xb3690ac0> (NoMethodError)`

I have a system of 32 bits, and Android 8.0

Help please.

**Comment by xeffyr** [comment]
Completely, with all dependencies reinstall metasploit with one of methods described on https://wiki.termux.com/wiki/Metasploit_Framework.
