### ISSUE TITLE
uwsgi installation

### ISSUE THREAD

**Issue by vstavrinov** [termux/termux-packages#3438]
While compilation I've got:

./uwsgi.h:365:10: fatal error: 'glob.h' file not found

Does any package contain this header?

**Comment by tomty89** [comment]
```
$ dpkg -L libandroid-glob-dev
/.
/data
/data/data
/data/data/com.termux
/data/data/com.termux/files
/data/data/com.termux/files/usr
/data/data/com.termux/files/usr/include
/data/data/com.termux/files/usr/include/glob.h
$
```

**Comment by vstavrinov** [comment]
> ```
> $ dpkg -L libandroid-glob-dev
> ```

Thank You. But after fixing this now there is next error:

./uwsgi.h:2016:2: error: unknown type name 'cap_value_t'

**Comment by tomty89** [comment]
Well, we don't provide libcap. You may try to build it on device.

**Comment by xeffyr** [comment]
> we don't provide libcap.

Provide, but in different place: https://github.com/termux/unstable-packages/tree/master/packages/libcap
```ShellSession
pkg install unstable-repo
pkg install libcap-dev
```

**Comment by vstavrinov** [comment]
Next iteration:

gcc_version_components = gcc_version.split('.')
    AttributeError: 'NoneType' object has no attribute 'split'

Installing gcc doesn't help. Also there is conflict  between libcap-dev and ndk-sysroot providing the same file:

/data/data/com.termux/files/usr/include/sys/capability.h
