### ISSUE TITLE
Package : dnsutils error

### ISSUE THREAD

**Issue by kenneth-Q** [termux/termux-packages#3440]
A problem has been found
Command is: **host**
From package: _dnsutils_
`
CANNOT LINK EXECUTABLE: could not load library "libirs.so" needed by "host"; caused by cannot locate symbol "isc_assertion_failed" referenced by "libirs.so"...
`

**Another information:**
Termux-info output
Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.0-7532458 #1 SMP PREEMPT Wed Mar 16 12:53:31 KST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.0
Device manufacturer:
samsung
Device model:
SM-N9007

**Comment by kenneth-Q** [comment]
Oops
Found the same issue. #2820
Shall we close it？ Or change dnsutils to static build and keep this open？

**Comment by Bacte** [comment]
Any command in the dnsutils package throws the same error:

CANNOT LINK EXECUTABLE: could not load library "libirs.so" needed by "xxxxxx"; caused by cannot locate symbol "isc_assertion_failed" referenced by "libirs.so"...

Android Version: 5.0.2
Arch: x86

**Comment by Grimler91** [comment]
There is a fix pending in https://github.com/termux/termux-packages/pull/4007

**Comment by kenneth-Q** [comment]
Problem were fixed.
If you have any problem, you can create another issue.
