### ISSUE TITLE
Add Ruby 2.4

### ISSUE THREAD

**Issue by Xi4u7** [termux/termux-packages#3443]
Hii Sir Please Add Ruby 2.4, I Run beef in ruby 2.6 fail sir

**Comment by Grimler91** [comment]
Hi, we generally do not package older versions of packages (exceptions being nodejs), if you need an older versions then you can always build ruby yourself, either on device or by cross compiling it following the instructions in the docs: https://github.com/termux/termux-packages/blob/master/docs/BUILD.md

**Comment by raquelhortab** [comment]
the link is dead, could someone explain how to install or build an older version of ruby? It's quite normal for a developer to need older versions of packages like ruby... thanks
