### ISSUE TITLE
rsync link_stat regression

### ISSUE THREAD

**Issue by Dmole** [termux/termux-packages#3446]
**Problem description**
rsync stopped recognizing Shell GLOB patterns with quotes

**Steps to reproduce**
```
rsync -vhP --no-p -t -e "ssh -i $PK" "/storage/emulated/0/DCIM/Camera/"IMG_*.jpg $USER@$IP:"$FOLDER/"
```
**Expected behavior**
Files are synchronized

**Additional information**
```
rsync: link_stat "/storage/emulated/0/DCIM/Camera/IMG_*.jpg" failed: No such file or directory (2)

sent 16 bytes received 12 bytes 18.67 bytes/sec
total size is 0 speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at /home/fornwall/.termux-build/rsync/src/main.c(1189) [sender=3.1.3]
```
using /storage/emulated/0/DCIM/Camera/IMG_*.jpg (without quotes) works but this issue was in a script where some of the paths passed to rsync contain spaces, and not all files in the folder are to be synchronized.
Because this is from a script I can be sure it was working before the regression for at least the past 3 months.

**Comment by xeffyr** [comment]
This related to https://github.com/termux/termux-packages/issues/3420 and **not** to link_stat.

**Comment by Dmole** [comment]
Thanks xeffyr.
