### ISSUE TITLE
[package request] bup

### ISSUE THREAD

**Issue by talentlessguy** [termux/termux-packages#3451]
Very efficient backup system based on the git packfile format, providing fast incremental saves and global deduplication 

Github repo: https://github.com/bup/bup

**Comment by kenneth-Q** [comment]
Will you have a try?😉

**Comment by xeffyr** [comment]
Requires python modules:
```
pylibacl
python2-fuse
python2-pyxattr
python2-tornado (optional) - for bup web
```

**Comment by kenneth-Q** [comment]
Also, I can not found the package:acl .

**Comment by doak** [comment]
I am currently trying to get `bup` working on a Android 6 device (Replicant 6). I have installed a lot of stuff manually and built `bup` locally on the device: It at least runs (use case is to backup to a remote device over SSH), and "does something". But I haven't verified the result yet.

There are at least issues with big files (e.g. thumbnail cache). `bup`'s documentation tells about issues with 32 bit architectures and `mmap()` which seems to explain that behaviour.

Let's see how far I get.

**Comment by doak** [comment]
Looks quite good. I stored approx. 5.6 GB of data from the internal sdcard and compared the md5 hashes of files on device against restored files: they are the same.

That means packaging `bup` for Termux should be possible. At least for some subset of functionality.
