### ISSUE TITLE
Problem with gem install rubygems-update

### ISSUE THREAD

**Issue by IFab967** [termux/termux-packages#3454]
When I use `gem install rubygems-update`, the installation stops, and I have to abort, and execute `gem install rubygems-update`, to can install the gem, after of this, the gems don't have any error, but for a automatic installation with this command, the script stops, please help :/. I have arm 32 
Android 8.0

**Comment by Grimler91** [comment]
Why does it stop/why do you have to abort?

**Comment by xeffyr** [comment]
> but for a automatic installation with this command, the script stops

What is "automatic installation" and "the script" ?

**Comment by IFab967** [comment]
the installation stops, and to be able to resume it I have to interrupt it with **CONTROL + C**, after that I have to re-execute the command `gem install rubygems-update
Successfully installed rubygems-update-3.0.3
Parsing documentation for rubygems-update-3.0.3
Done installing documentation for rubygems-update after 1 seconds
1 gem installed` and now it is installed. with automatic installation I mean that if I make a script, that it takes that command `gem install rubygems-update` when I get to that part the script stops, and I have to interrupt. I think that would be it, I appreciate your help :)

**Comment by xeffyr** [comment]
> Installing ri documentation for rubygems-update-3.0.3

Installing ri documentation may take LONG TIME and you may see that installation hangs. It is not possible to fix that as depends on speed of your device's storage.

**Comment by IFab967** [comment]
Do not wait 10 minutes and it did not work. but I found another solution, when executing `gem install -N rubygems-update`, it does not install the documentation, since it is in that part where the script stops, and there it installs without problems, thanks for the help :D

**Comment by xeffyr** [comment]
FYI, how much it takes to install with docs:
![screenshot_20190305-162223](https://user-images.githubusercontent.com/25881154/53811996-31b88800-3f63-11e9-91b7-a694f576e922.png)

**Comment by IFab967** [comment]
Oh, I'll try again, I appreciate the information, I'm new to this, thank you very much for helping me, good day!! :)

**Comment by harsh2000shah** [comment]
Plz help me out of this...
It pops every time... I even tried formatiing my phone and uninstalling termux and metasploit.

**Comment by xeffyr** [comment]
> I even tried formatiing my phone and uninstalling termux and metasploit

Do not try to seek problem inside Termux or your device unless you checked that everything is okay with your network.

Package managers are very sensitive to broken Internet connections. In your case connection just timed out for whatever reason, e.g. because of high packet loss rate (very common on poor mobile signal) or your ISP tampers/intercepts traffic.

**Comment by harsh2000shah** [comment]
Thank you for your response.

**Comment by harsh2000shah** [comment]
Sir, can u fix this??

**Comment by xeffyr** [comment]
No. I can only suggest you to try manual downloading of `rubygems-update` gem package:
```
wget http://rubygems.org/gems/rubygems-update-3.0.3.gem
gem install ./rubygems-update-3.0.3.gem
```

**Comment by selva4458** [comment]
Have bundle install

**Comment by vrlmv** [comment]
One of solution may be using VPN. Because in some countries gem is banned, ind cannot fetch any data.
I have a same problem, but fixed it using VPN.
