### ISSUE TITLE
Package Request: TinyCC

### ISSUE THREAD

**Issue by TheBrokenRail** [termux/termux-packages#3459]
**Package description**
This is a small C compiler, this would be ice for device that don't have much stirage space, or for other reasons, don't want to download a 100MB package.

**Link to home page and sources**
1. Home page: https://savannah.nongnu.org/projects/tinycc
2. Source code: https://repo.or.cz/w/tinycc.git

**Additional information**
I have compiled the package on a linux laptop, here is a GitHub gist showing the steps for NDK r19. The outputted files do not run as they are not PIE, but they do wok when running as a script with ```tcc -run```. Some of the script has been based off code in the https://github.com/thioshp/termux-extra-packages repo.

https://gist.github.com/TheBrokenRail/eaf0548c890cb43f39931c0be050944b

**Comment by xeffyr** [comment]
TCC is completely unsuitable to have it officially packaged.

* No PIE.
* No support for NDK headers.
* Potential unknown bugs (there no compiler devs so bugs unlikely to be fixed)

Yes, it can run programs directly from C code by using `tcc -run` but this makes it useless as compiler. For simple one-file progs it ok (maybe). btw, TCC can't be for anything serious.

And should I mention that TinyCC project is no longer maintained ? Probably no.

**Comment by TheBrokenRail** [comment]
It actually is maintained, its last commit was only 30 hours ago.

**Comment by xeffyr** [comment]
Yes, there some activity on git. By going through git log it seems there mostly bugfixes.
https://github.com/termux/unstable-packages/commit/bac546acf33a3a816b50e3ba215b26c84b93e34b
