### ISSUE TITLE
fc-cache fails (fontconfig)

### ISSUE THREAD

**Issue by Breta01** [termux/termux-packages#346]
Hi,
I was following this guide how to install font for powerline https://powerline.readthedocs.io/en/latest/installation/linux.html#fontconfig
But it always fails:
![screenshot_20160701-215625 1](https://cloud.githubusercontent.com/assets/10288864/16533689/e4e0bb68-3fda-11e6-9298-a6c5bddd9651.png)

**Comment by fornwall** [comment]
Termux uses the Android system font renderer, which does not use fontconfig so the linked instructions will not work. The easiest solution is probably to install Termux:Styling and use one of the fonts provided by that app - is that possible for you?

**Comment by Breta01** [comment]
Thanks,
that makes sense. But is there any real use for fontconfig then?
