### ISSUE TITLE
Package request: nodejs 8.x.x

### ISSUE THREAD

**Issue by sezoid** [termux/termux-packages#3461]
Hi. I cant find older version of nodejs. I need it, because Google Firebase support only nodejs v6.x.x-8.x.x

Thanks.

**Comment by kenneth-Q** [comment]
Here is a old version of termux-packages. It include nodejs v8.4.0. I am no sure that is working, but you can try.
Download: [here](https://github.com/termux/termux-packages/archive/e51647f17b38c608bd8b20e9604661ac230ebbcb.zip)
Download and extract it. Then start building.

**Comment by felix12340** [comment]
> Here is an old version of termux-packages. It include nodejs v8.4.0. I am no sure that is working, but you can try. The package call nodejs-current.
> Download: [here](https://github.com/termux/termux-packages/archive/e51647f17b38c608bd8b20e9604661ac230ebbcb.zip)
> Download and extract it.
> Warning: We don't recommend it, please do not report if you get any issue.

I have the same problem. Can this solve the problem? 
If this can solve the problem, can you tell me how to replace the current package after downloading the old version.

**Comment by xeffyr** [comment]
> Can this solve the problem?

No.
You have to compile olld package version manually and install it.

**Comment by felix12340** [comment]
> > Can this solve the problem?
> 
> No.
> You have to compile old package version manually and install it.

How to compile the old package version on termux?

**Comment by felix12340** [comment]
> > Can this solve the problem?
> 
> No.
> You have to compile olld package version manually and install it.



> > Can this solve the problem?
> 
> No.
> You have to compile olld package version manually and install it.

can you explain the details?

**Comment by xeffyr** [comment]
Everything about how to build package is in https://github.com/termux/termux-packages/tree/master/docs. Information about how to work with git you can find on the Internet.

**We won't do this specially for you.**
