### ISSUE TITLE
uwsgi

### ISSUE THREAD

**Issue by vstavrinov** [termux/termux-packages#3465]
fast, self-healing application container server
 uWSGI presents a complete stack for networked/clustered web applications,
 implementing message/object passing, caching, RPC and process management.
 It uses the uwsgi protocol for all the networking/interprocess communications.
 .
 uWSGI can be run in preforking, threaded, asynchronous/evented modes and
 supports various forms of green threads/coroutines (such as uGreen, Greenlet,
 Fiber). uWSGI provides several methods of configuration: via command line,
 via environment variables, via XML, INI, YAML configuration files, via LDAP
 and more.
 .
 On top of all this, it is designed to be fully modular. This means that
 different plugins can be used in order to add compatibility with tons of
 different technology on top of the same core.
 .
 This package depends on uWSGI core binary and installs:
  * init.d script for running uWSGI daemon(s) with options defined in custom
    user-created configuration files
  * infrastructure for running daemons (like common locations of communication
    sockets, logs)

Homepage: http://projects.unbit.it/uwsgi/

There are some  compilation problems described in termux/termux-packages#3438

**Comment by xtkoba** [comment]
PR #8148. At least it builds: https://github.com/termux/termux-packages/actions/runs/1539672939.

Note that C standard library functions `futimes`, `semctl`, `semget` and `semop` referenced from `bin/uwsgi` are unavailable before API level 26. We have to fix this before releasing. Any ideas?

**Comment by Grimler91** [comment]
Easiest way would be to set TERMUX_PKG_API_LEVEL to 26 for uwsgi, and perhaps have a warning in postinst or package description that it doesn't work on lower android versions. We did that for some packages before the android 5&6 - android >= 7 split

**Comment by xtkoba** [comment]
After all I decided to backport those functions from <a href="https://android.googlesource.com/platform/bionic/+/master/libc">newer bionic codebase</a> because it was fairly trivial to do.
