### ISSUE TITLE
Add supporting packages for fish shell

### ISSUE THREAD

**Issue by efi** [termux/termux-packages#347]
In order to make the fish shell working error-free, there have to be some supporting packages available:

`man-db` (for the `apropos` command)
`util-linux` (for the `column` command)

_(I will list more when I come across them - `bc` seems to have been added recently.)_

Could those be easily added?

**Comment by fornwall** [comment]
Thanks, the apropos command is now available in the man package (which fish now depends on). Note that for apropos to give any results you have to run makewhatis command.

Which functionality of fish needs the `column` command?

**Comment by efi** [comment]
Thanks a lot! I tried to recall where that `column` requirement came from, but so far couldn't find the place. The only only thing I found that it was used in https://github.com/oh-my-fish/oh-my-fish which is of course no core part of fish (nevertheless `omf` support would be great).

But `apropos` was the larger issue here...

**Comment by fornwall** [comment]
Ok, I'm closing this issue - you may re-open the issue if you encounter the part in `omf` which requires `column` (with steps how to reproduce it)!

The latest version of the `man` package now also updates the db automatically each time a man page is added, removed or updated, so it's no longer necessary to run `makewhatis` manually.

**Comment by efi** [comment]
*reopen* :D

To find `column` in omf was not hard at all. Did it literally on the first try.
```
$ fish
x> ~ omf list
...
No command column found, did you mean: 
...
```

see here: https://github.com/oh-my-fish/oh-my-fish/blob/master/pkg/omf/functions/cli/omf.cli.list.fish#L10

Thanks for the `man` tweak, too! :-)

**Comment by Dietr1ch** [comment]
I also stumped on this while setting up oh-my-fish

**Comment by fornwall** [comment]
@efi @Dietr1ch Thanks - the fish package has been updated to bundle a `column` utility, update to it with `apt update && apt upgrade`!

**Comment by efi** [comment]
Works like a charm. Thank you!

**Comment by Dietr1ch** [comment]
@fornwall Now it works, thanks (:

**Comment by mjrael89** [comment]
x> ~ omf list
