### ISSUE TITLE
emacs system-type does not indicate emacs/termux

### ISSUE THREAD

**Issue by timoc** [termux/termux-packages#348]
Hi, 

I'm trying to deduce that emacs is running under termux. the usual mechanism is the system-type variable set in the build system. It is currently "gnu/linux", can you set it to something to indicate android?

**Comment by fornwall** [comment]
Hm, perhaps `android/linux`?

**Comment by timoc** [comment]
No, I'm cancelling the request,

After more digging, i came across the Emacs NEWS.19 release notes, which state i should be using the ```system-configuration``` variable. After digging into this it is probably the better approach, so no change needed. In fact keeping it closer to linux standard might be the better call.

For those wanting to use ```system-configuration``` here is the settings you might need
Linux PC has  ```x86_64-pc-linux-gnu``` whereas Termux has ```arm-unknown-linux-androidabi```

Looking through the environmental variables exported from the shell at the moment,
