### ISSUE TITLE
CANNOT LINK EXECUTABLE "php": library "libreadline.so.8" not found Aborted

### ISSUE THREAD

**Issue by Allistar101** [termux/termux-packages#3480]
This is the error I receive when I try and use php: I typed just (  php   )
CANNOT LINK EXECUTABLE "php": library "libreadline.so.8" not found Aborted

When I try and host a php server it reads: 
Aborted                    php -S 127.0.0.1:$port > /dev/null 2>&1

I think it may be an issue with either libreadline 8 not being found or something with version 7

I looked in my /data/data/com.termux/files/home/usr/lib and so some files I think my be related
I saw libreadline.so, libreadline.so.8 and libreadline.so.8.0
libreadline.so and libreadline.so.8 both displayed in blue text. libreadline.so.8.0 was in green text. 

So I ran this command: apt show headline -a
It displayed the following:
Package: readline
Version: 8.0
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 373 kB
Depends: libandroid-support, ncurses
Breaks: bash (<< 5.0)
Homepage: https://tiswww.case.edu/php/chet/readline/rltop.html
Download-Size: 88.3 kB
APT-Sources: https://termux.net stable/main aarch64 Packages
Description: Library that allow users to edit command lines as they are typed in

Package: readline
Version: 7.0.5-2
Status: install ok installed
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 352 kB
Depends: libandroid-support, ncurses
Homepage: https://tiswww.case.edu/php/chet/readline/rltop.html
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /data/data/com.termux/files/usr/var/lib/dpkg/status
Description: Library that allow users to edit command lines as they are typed in

**Steps to reproduce**
The error displays whenever I type php or any php command

**Expected behavior**
With the php server I expected to host a website from local host via serveo with the locator tool by @thelinuxchoice, But know php won't run either.

**Additional information**
Here is the output of 'termux-info'
$'termux-info'
Updatable packages:
apt/stable 1.4.9-1 aarch64 [upgradable from: 1.4.8-9]
bash/stable 5.0.2 aarch64 [upgradable from: 4.4.23-3]
busybox/stable 1.30.1-1 aarch64 [upgradable from: 1.29.3-1]
ca-certificates/stable 20190124 all [upgradable from: 20181205]
dpkg/stable 1.19.4 aarch64 [upgradable from: 1.19.2]
gpgv/stable 2.2.13-1 aarch64 [upgradable from: 2.2.12]
libbz2/stable 1.0.6-2 aarch64 [upgradable from: 1.0.6-1]
libc++/stable 19b aarch64 [upgradable from: 18]
libcurl/stable 7.64.0 aarch64 [upgradable from: 7.63.0]
libgpg-error/stable 1.35 aarch64 [upgradable from: 1.34]
ncurses/stable 6.1.20181117-1 aarch64 [upgradable from: 6.1.20181117]
openssl/stable 1.1.1b-1 aarch64 [upgradable from: 1.1.1a]
readline/stable 8.0 aarch64 [upgradable from: 7.0.5-2]
System information:
Linux localhost 3.18.71-13660022 #1 SMP PREEMPT Wed Oct 10 19:58:47 KST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-G930VL

I added photos below to show my errors, I really need to fix this urgently and would gladly accept any help that can be provided. If you need more info that I didn't include here just let me know.
![Screenshot_20190308-205236_Termux](https://user-images.githubusercontent.com/34456246/54064662-8b7bb500-41e4-11e9-91c2-ce9d4f553b66.jpg)
![Screenshot_20190308-205314_Termux](https://user-images.githubusercontent.com/34456246/54064664-91719600-41e4-11e9-85b9-2bcd6fc0c6d9.jpg)
![Screenshot_20190308-205257_Termux](https://user-images.githubusercontent.com/34456246/54064666-959db380-41e4-11e9-9097-ba60ec6efb8b.jpg)
![Screenshot_20190308-205409_Termux](https://user-images.githubusercontent.com/34456246/54064671-99313a80-41e4-11e9-98ab-9ca7cf59cc82.jpg)

![Screenshot_20190308-205211_Termux](https://user-images.githubusercontent.com/34456246/54064694-ea412e80-41e4-11e9-920d-9befdeb38200.jpg)
![Screenshot_20190308-205217_Termux](https://user-images.githubusercontent.com/34456246/54064696-ed3c1f00-41e4-11e9-8ef8-c03e2f868e9b.jpg)

**Comment by vishalbiswas** [comment]
You have readline 7 installed. `php` is asking for `libreadline.so.8`. Here `.8` stands for version 8.
Update your readline package. (on a sidenote: it is always advised to not selectively update packages in termux since the dependency data in packages includes no version information)

**Comment by Allistar101** [comment]
Libreadline8 and 7 are both installed

**Comment by Rafaelxp** [comment]
I was with this problem, but I installed the readline and this resolved it

**Comment by syntaxseed** [comment]
To update readline do:

pkg install readline

==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version.
    ...etc

(Choose first (Y) option if you get this message.)
