### ISSUE TITLE
Termux upgrade error

### ISSUE THREAD

**Issue by Kaan8910** [termux/termux-packages#3484]
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ apt-get update
Hit:1 https://termux.net stable InRelease
Reading package lists... Done
$ apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  apt bash busybox dpkg gpgv libcurl
  libgpg-error
7 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 1458 kB/1868 kB of archives.
After this operation, 299 kB disk space will be freed.
Do you want to continue? [Y/n] Y
Err:1 https://termux.net stable/main arm busybox arm 1.30.1
  404
Err:2 https://termux.net stable/main arm gpgv arm 2.2.13
  404
Err:3 https://termux.net stable/main arm apt arm 1.4.9
  404
Err:4 https://termux.net stable/main arm bash arm 4.4.23-4
  404
E: Failed to fetch https://termux.net/dists/stable/main/binary-arm/busybox_1.30.1_arm.deb  404
E: Failed to fetch https://termux.net/dists/stable/main/binary-arm/gpgv_2.2.13_arm.deb  404
E: Failed to fetch https://termux.net/dists/stable/main/binary-arm/apt_1.4.9_arm.deb  404
E: Failed to fetch https://termux.net/dists/stable/main/binary-arm/bash_4.4.23-4_arm.deb  404
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

How to fix?

**Comment by xeffyr** [comment]
Things to do:

* Verify that your Termux installation is sane. If you are not sure about this, just reinstall Termux.
* Use `pkg upgrade` to upgrade packages. **Always !!!**

**Comment by Kaan8910** [comment]
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ pkg upgrade
Hit:1 https://termux.net stable InRelease
Reading package lists... Done
Building dependency tree... Done
7 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
The following packages will be upgraded:
  apt bash busybox dpkg gpgv libcurl
  libgpg-error
7 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 1458 kB/1868 kB of archives.
After this operation, 299 kB disk space will be freed.
Do you want to continue? [Y/n] Y
Err:1 https://termux.net stable/main arm busybox arm 1.30.1
  404
Err:2 https://termux.net stable/main arm gpgv arm 2.2.13
  404
Err:3 https://termux.net stable/main arm apt arm 1.4.9
  404
Err:4 https://termux.net stable/main arm bash arm 4.4.23-4
  404
E: Failed to fetch https://termux.net/dists/stable/main/binary-arm/busybox_1.30.1_arm.deb  404
E: Failed to fetch https://termux.net/dists/stable/main/binary-arm/gpgv_2.2.13_arm.deb  404
E: Failed to fetch https://termux.net/dists/stable/main/binary-arm/apt_1.4.9_arm.deb  404
E: Failed to fetch https://termux.net/dists/stable/main/binary-arm/bash_4.4.23-4_arm.deb  404
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
$

**Comment by xeffyr** [comment]
> Verify that your Termux installation is sane. If you are not sure about this, just reinstall Termux.

You didn't reinstalled termux...

**Comment by cilantro13** [comment]
allways whay

**Comment by anupamkrsinha** [comment]
![Screenshot_20191001-130603](https://user-images.githubusercontent.com/56025312/65954669-1c0d3180-e464-11e9-9a4c-53fdb7446c9c.jpeg)
Error occurred while upgrading 
Command:-
pkg upgrade
