### ISSUE TITLE
nping unable to link dependency lib

### ISSUE THREAD

**Issue by ishantvivek** [termux/termux-packages#349]
Whenever i run nping with -tcp/-udp(for e.g "nping --tcp -c 20 --delay 50ms -p- google.com --mtu 1400 --data-length 1400")  which requires root ,i get error :
CANNOT LINK EXECUTABLE DEPENDENCIES: library "libssl.so.1.0.0" not found.

**Comment by ishantvivek** [comment]
Edit: Running without "su" , have error :
"Mode tcp requires root permission"

**Comment by fornwall** [comment]
Look at https://github.com/cswl/tsu for a method to run Termux packages under root without the `CANNOT LINK EXECUTABLE DEPENDENCIES` error.

The problem (that the above linked `tsu` script) works around is that Termux packages need the `LD_LIBRARY_PATH` environment variable setup in order for shared libraries to be found by the system linker, but `su` normally removes that environment variable.

**Comment by ishantvivek** [comment]
Thanks it worked :D ,BTW any plan of integrating "tsu" in termux?

**Comment by fornwall** [comment]
@ishantvivek Yes, `tsu` is now available as an apt package!
