### ISSUE TITLE
Packages with missing DT_RUNPATH

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#3490]
~~Let's keep this list updated and comment as we solve them.~~

To check if an ELF file has DT_RUNPATH set, run:

    objdump -x path-to-elf-file | grep RUNPATH

That should output:

    RUNPATH              /data/data/com.termux/files/usr/lib

**Comment by fornwall** [comment]
f6249e36fef454aebec486680312522c53452e1c - fortune was easy :), removing it from the list.

**Comment by xeffyr** [comment]
What about Go-based programs that link to additional shared libs ? `hugo` for example can't find libc++_shared.so.

**Comment by fornwall** [comment]
> What about Go-based programs that link to additional shared libs ? hugo for example can't find libc++_shared.so.

d03cd2f0db35e64a3e7fc7f0d098fb0fd9c42d2f should fix that by adding `export CGO_LDFLAGS="$LDFLAGS"`. I've bumped hugo after that change, it should now work.

> And perhaps clang should use -Wl,-rpath=$TERMUX_PREFIX/lib -Wl,--enable-new-dtags at linking time by default ?

Yes, definitely!

**Comment by xeffyr** [comment]
DT_RUNPATH is not needed for libc++_shared.so. Also, we can't do nothing here as this library is precompiled.

**Comment by xeffyr** [comment]
It also not needed for proot's loader.

**Comment by xeffyr** [comment]
Packages gbt, ipfs, keybase, kbfs and boost seems to be fixed now.

**Comment by monoidic** [comment]
From what hasn't been named so far:
bzip2
curl
ffmpeg
fribidi
gawk
gettext
htop
libidn2
libllvm
libseccomp
lld
ltrace
openssl-tool
patchelf
proot
sqlite
termux-auth
tracepath
(based on what's in my bin dir, minus busybox, which appears to not need DT_RUNPATH since it's not linked against anything in PREFIX)
> It also not needed for proot's loader.

It says it can't find libtalloc.so.2 here.

**Comment by xeffyr** [comment]
@monoidic Sometimes `pkg upgrade` is not enough to replace packages. You have to **reinstall everything**.

**Comment by xeffyr** [comment]
> It says it can't find libtalloc.so.2 here.

loader cannot say anything. It does not have dependencies.

**Comment by xeffyr** [comment]
Script for detecting missing runpath:
```bash
#!/data/data/com.termux/files/usr/bin/bash
##
##  Check binaries if they have DT_RUNPATH set and report
##  ones that do not have DT_RUNPATH.
##
##  Dependencies: bash, coreutils, file, findutils, patchelf
##

#set -e

: "${PREFIX:=/data/data/com.termux/files/usr}"

while read binary; do
    if [ "$(dd if="$binary" bs=1 skip=1 count=3 status=none)" = "ELF" ]; then
        runpath=$(patchelf --print-rpath "$binary" 2>/dev/null)
        if [ -z "$runpath" ]; then
            pkg=$(dpkg -S "$binary" 2>/dev/null | cut -d: -f1)
            if [ ! -z "$pkg" ]; then
                echo "$pkg: $binary"
            fi
        fi
    fi
done <<< $({ find "$PREFIX"/bin "$PREFIX"/libexec -type f; find "$PREFIX"/lib -type f -iname \*.so\*; } | sort)
```

**Comment by monoidic** [comment]
Ah, thanks. I guess I assumed all packages on bintray had bumped version numbers or something and I didn't really know how to reinstall all packages with apt.

**Comment by xeffyr** [comment]
Excluding valgrind because of static binaries - they should not have DT_RUNPATH.

**Comment by xeffyr** [comment]
Looks like now solved, though I will need to recheck everything again to be sure that everything is okay.
Closing.

**Comment by bhagwandassony1** [comment]
![Screenshot_20200805-054516](https://user-images.githubusercontent.com/69147279/89360501-2ddce800-d6b8-11ea-8d70-19bbc2624e90.png)
