### ISSUE TITLE
graphicsmagick: missing configuration script

### ISSUE THREAD

**Issue by kenneth-Q** [termux/termux-packages#3496]
For building a pavkage: [timg](url) 
GraphicsMagick++-config: Command not found
But I found this:
From: packages/graphicsmagick/build.sh
> TERMUX_PKG_RM_AFTER_INSTALL="bin/*-config share/man/man1/*-config.1"

Emmm...
For what purpose? Is there any problems to avoid?
Thank you.

**Comment by xeffyr** [comment]
Ask @fornwall about https://github.com/termux/termux-packages/commit/8f41da160caef7e92952615be496b2e16459ce51#diff-eafd5e6184e31e1394f2d3d1dd7a1a15/

**Comment by xeffyr** [comment]
Fixed in 299fefe154c6073925a16c56e2ad10b38d666c03.
