### ISSUE TITLE
Package Request: Surfraw

### ISSUE THREAD

**Issue by Aryailia** [termux/termux-packages#3498]
**Package description**
Surfraw is a bash-script-turned package that functions essentially the same as having several search bars in GUI web browsers except that it is a CLI tool. It also has a search for bookmarks through a local bookmark file feature. It then feeds to the link to $BROWSER (or a browser specified in its command-line argument). You can also make your custom searches (called "elvi" 's).

It's really nice for more streamlining terminal browsing or one could even use termux-open-url. Termux itself out of the box is a terminal-only environment so this would be a pretty good fit. 

**Link to home page and sources**
1. Home page: https://gitlab.com/surfraw/Surfraw/
2. Source code: https://gitlab.com/surfraw/Surfraw/

**Additional information**
I have complied it successfully, with autoconf installed:
```shell
$ git clone https://gitlab.com/surfraw/Surfraw.git
$ cd Surfraw
$ ./prebuild
$ ./configure --prefix="$PREFIX"
$ make install
```
This basically works for me, but not bash auto-completions do not work, and I'm not familiar enough with either bash autocompletions or autoconf to fix it.

**Comment by mithaku** [comment]
How to fix no such file directory when access sdcard?
Help me https://www.mithakuyunda.com

**Comment by xeffyr** [comment]
Package is available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install surfraw
```

**Comment by maxigaz** [comment]
@xeffyr I have unstable-packages enabled through `pkg install unstable-repo`, but I still can't find `surfraw` with `pkg search surfraw` or `pkg install surfraw`.

```
$ pkg install surfraw
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:4 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable InRelease
Get:5 https://dl.bintray.com/termux/termux-packages-24 stable Release [6061 B]
Hit:5 https://dl.bintray.com/termux/termux-packages-24 stable Release
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:7 https://dl.bintray.com/grimler/science-packages-24 science Release
Get:8 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release [6065 B]
Hit:8 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release
Reading package lists... Done                         
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package surfraw
```

On the other hand, I can find and install other packages from the same repo, listed [here](https://github.com/termux/unstable-packages/tree/master/packages), such as `fasd`, `sdcv`, and `gflags`.

Am I missing something?

**Comment by xeffyr** [comment]
@maxigaz Should be available now.

**Comment by maxigaz** [comment]
Excellent! Thank you very much!
