### ISSUE TITLE
Suggestion: gdbm as backend for apropos?

### ISSUE THREAD

**Issue by cydhaselton** [termux/termux-packages#350]
I came across [this thread](https://github.com/termux/termux-packages/issues/169) while searching for an error thrown in termux when searching with man -k.

The size concerns in the thread are valid so I did some digging for information on the back-end database. I found [man-db](http://man7.org/linux/man-pages/man8/mandb.8.html), an alternative to man, which supports a number of different database types…including gdbm, which is a supported, small footprint termux package.

Which got me thinking: Would it be possible to compile man with apropos using a gdbm database instead of sqlite?

**Comment by cydhaselton** [comment]
FYI I may be able to work on this if there are instructions on how to contribute builds done *within* the Termux environment

**Comment by fornwall** [comment]
Thanks, the apropos command is now available in the `man` package (which fish now depends on).

Note that for apropos to give any results you have to run `makewhatis`  command.
