### ISSUE TITLE
Time zone in program does not correspond to local time

### ISSUE THREAD

**Issue by garlapann** [termux/termux-packages#3501]
Hi, I use sniffer "bettercap". When I run this program on a PC (Ubuntu or Kali) everything is fine, but in termux this program display the wrong time of events. My time zone is UTC+3 but this program display Greenwich mean time in termux. The console itself displays the time correctly. Also, calling 'date' is OK.
`export TZ=Europe/Minsk && sudo bettercap` OR `export TZ=$(getprop persist.sys.timezone) && sudo bettercap` also does not help, although TZ is installed correctly.

P. S: I compiled bettercap locally in termux. Here are my commands:
`pkg install git golang libpcap-dev libusb-dev pkg-config`
`export PKG_CONFIG=$PREFIX/bin/pkg-config && go get github.com/bettercap/bettercap`
`cd ~/go/bin && mv bettercap $PREFIX/bin && chmod 0700 $PREFIX/bin/bettercap`

**Comment by xeffyr** [comment]
Related to https://github.com/termux/termux-packages/issues/2622.

**Comment by garlapann** [comment]
I use go1.12 and the problem is still not solved?

**Comment by xeffyr** [comment]
https://github.com/golang/go/issues/20455 still open, so it is not solved.

**Comment by garlapann** [comment]
That's too bad....
