### ISSUE TITLE
Can't run pkg update && pkg upgrade

### ISSUE THREAD

**Issue by lexus55** [termux/termux-packages#3502]
pkg update && pkg upgrade
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by xeffyr** [comment]
> Sub-process https received signal 4.

Likely same as https://github.com/termux/termux-app/issues/916.
VFP-only devices are not supported as will require 2x more repositories setup. We are not going to do this.
