### ISSUE TITLE
Package golang has a wrong hardcoded pkg-config path

### ISSUE THREAD

**Issue by evilsocket** [termux/termux-packages#3505]
**Problem description**

Hi, as a dependency to a project of mine, I am building a go package (https://github.com/google/gousb) that relies on `pkg-config` in order to find `libusb-dev`'s headers. When built it complains about a path which doesn't exist:

```
/home/builder/.termux-build/_cache/19b-aarch64-21-v1/bin/aarch64-linux-android-pkg-config --cflags -- libusb-1.0
/home/builder/.termux-build/_cache/19b-aarch64-21-v1/bin/aarch64-linux-android-pkg-config: fork/exec /home/builder/.termux-build/_cache/19b-aarch64-21-v1/bin/aarch64-linux-android-pkg-config: no such file or directory
```

**Steps to reproduce**

```
pkg install root-repo
pkg install golang git libpcap-dev libusb-dev
go get -u github.com/bettercap/bettercap
```

**Expected behavior**

It compiles.

**Additional information**

The ugly fix so far, that requires a rooted device, is remounting / as `rw`, creating the folder and symlinking the actual `pkg-config` to it:

```sh
sudo su
mount -o rw,remount /
mkdir -p /home/builder/.termux-build/_cache/18-arm-21-v2/bin/
ln -s `which pkg-config` /home/builder/.termux-build/_cache/18-arm-21-v2/bin/arm-linux-androideabi-pkg-config
```

Once this is done, the compilation completes with no other issues.

**Comment by fornwall** [comment]
This should now be fixed in version `1.12-1` of the golang package - update with `pkg up` and verify that it works. Thanks @its-pointless !
