### ISSUE TITLE
Cannot install Text::Iconv via cpan

### ISSUE THREAD

**Issue by mciancia** [termux/termux-packages#351]
I have installed both perl and iconv package via apt, but running cpan Text::Iconv fails, telling me
 `Can't load '/data/.cpan/build/Text-Iconv-1.7-WDJwyw/blib/arch/auto/Text/Iconv/Iconv.so' for module Text::Iconv: dlopen failed: cannot locate symbol "iconv_close" referenced by "Iconv.so"... at /data/data/com.termux/files/usr/lib/perl5/5.24.0/arm-linux/DynaLoader.pm line 196.`

Can someone confirm this and/or have solution?

**Comment by Grimler91** [comment]
dlopen issues are most often solved by first making sure the library providing the symbol is installed (in this case I'm guessing libandroid-support Is needed), and then running the installation with LDFLAGS set to point to the library that wasn't found. In this case something like `LDFLAGS=" -landroid-support" cpan Text::Iconv`
