### ISSUE TITLE
Required Android studio

### ISSUE THREAD

**Issue by foodmaher** [termux/termux-packages#3514]
**Package description**
With Android studio we can develop applications so we need to develop or learn to develop applications without the need for a computer

**Link to home page and sources**
1. [Android studio](https://developer.android.com/studio)
2. I Don't know (Code-source)

**Additional information**
Have you compiled or tried to compile the package on device?
I downloaded the program and got to the main interface but it showed a lot of errors and did not recognize the libraries android even could not open the layout and display design so I decided to scan because it needs to be compatible with the application

**Note:** It is installed within the Debian environment installed on Termux

**WARRING:** It is possible that the speech is incorrect due to the use of a language translator

**Comment by xeffyr** [comment]
1. Android Studio is not supported on Termux.
2. We don't have JDK.
3. Android SDK is required too. But no one will port it for known reasons.
