### ISSUE TITLE
How to install php extension

### ISSUE THREAD

**Issue by sohaha** [termux/termux-packages#3516]
I need some php extensions to get the job done.
 Such as php-msgpack, swoole,
 Make failed, is there any other way to do it?
 
 Anyway, thank you for providing such a good tool to let me finish some work on the bus.

**Comment by sohaha** [comment]
Pear has been used.
 It is estimated that the extension itself does not support Android environment

**Comment by xtkoba** [comment]
In general, problems for building extensions of PHP (or Python or Ruby or any other scripting languages you like) should be treated on a case-by-case basis. It may be that some dependencies are missing, or that some porting is needed (in the wild we have quite a few softwares that do not consider non-x86 arches). It does not seem to be the case here that the package (extension) manager itself does not work.

But I cannot guess any other thing until I see what you invoked and what were output as error logs.

**Comment by xtkoba** [comment]
This issue is marked as obsolete. Please open a new issue if you encounter a similar problem. Thanks.
