### ISSUE TITLE
pip geoip error

### ISSUE THREAD

**Issue by RootSh311** [termux/termux-packages#3519]
How Can I Fix This I Am Using Its-pointless gcc-8
![Screenshot_20190315-201345](https://user-images.githubusercontent.com/47913604/54437519-fdad4600-475e-11e9-8f14-4e7ea35fa11b.png)

**Comment by xeffyr** [comment]
I don't know what you did, but for me it is installed successfully:
```ShellSession
[~]:$ pip2 install geoip
Collecting geoip
  Downloading https://files.pythonhosted.org/packages/f2/7b/a463b7c3df8ef4b9c92906da29ddc9e464d4045f00c475ad31cdb9a97aae/GeoIP-1.3.2.tar.gz
Installing collected packages: geoip
  Running setup.py install for geoip ... done
Successfully installed geoip-1.3.2
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by xeffyr** [comment]
> I Am Using Its-pointless gcc-8

Ah, now I see why you have error. Switch back to **clang** and use it only. It just because python was compiled with some options that understands only clang.

**Comment by RootSh311** [comment]
I Don't Have libgeoip compiled

**Comment by RootSh311** [comment]
Can You Guide Me @xeffyr
