### ISSUE TITLE
HOSTNAME enviromental variable is localhost not system name

### ISSUE THREAD

**Issue by timoc** [termux/termux-packages#352]
This should be the system hostname, or the phones name. This name is the one usually registered  in the local dns when connected to a wifi network. having the hostname in the PS1 will make it easier for people to set up ssh connections as all they should need is 

```
ssh -p 8022 termux@<phonename>
```

and/or can add this to their ssh config (assuming the phone is called myphone)

```
Host myphone
    HostName myphone
    User termux
    Port 8022 
    ForwardX11 yes
    ForwardX11Trusted yes
    IdentitiesOnly yes
    IdentityFile ~/.ssh/termux.key
```

which allow people to just

```
ssh myphone
```

which works with emacs tramp for editing files on the phone filesystem

**Comment by fornwall** [comment]
I don't think Android (as of 5.0 or later) allows setting a system hostname. At least not without root - do you have a root setup where you can test this?

**Comment by timoc** [comment]
I guess hostname The hostname issue I have looked into, but i cannot find the detail. Usually there is a device ID that is used for the hostname, and this is part of the android platform. If you can publish this, then that would be a good substitute.

The above process also works by using IP address.
```
HostName 172.1.1.1
```
And can be added to the documentation

**Comment by Exaeta** [comment]
Hello! Android does have hostnames. Hostnames are required of all network devices... normally it is something like "android38793629130". Not being able to use a custom hostname without root is not the same as not having a hostname at all!

**Comment by Exaeta** [comment]
Add the following to `~/.bash_profile`:
```
GREEN="\[$(tput setaf 2)\]"
RESET="\[$(tput sgr0)\]"

export PS1="${GREEN}\$(id -n -u)@\$(getprop net.hostname):\$(pwd)${RESET}\$ "
```

**Comment by metimocyn** [comment]
Maybe this can be added to the sshd script, or another termux script that will tell you about your local network environs?

**Comment by xeffyr** [comment]
Android has 2 hostnames:

1. DHCP hostname, usually it something like android38793629130.
2. System hostname (sysctl kernel.hostname). Which is hardcoded at system-level to be localhost - typical Android devices doesn't meant to be used as servers or something similar.

Variable "HOSTNAME" is set by bash, value obtained from libc function gethostname() which obviously will return "*localhost*".

Obtaining DHCP hostname is something related to Termux:API...

**Comment by danintel** [comment]
On Linux hostname is set and stored in /etc/hostname
For example.. .

$ cat /etc/hostname
glacier
