### ISSUE TITLE
issue for cross compile

### ISSUE THREAD

**Issue by ze00** [termux/termux-packages#3525]
Hey guys, I want build a binary for arm on aarch64, I'm had Install the 'ndk-multilib' package, and I run the below command:

```
clang++ Test.cc -o Test --target=arm-linux-androideabi -nodefaultlibs -L/system/lib -lc -ldl
```
The error message of clang++:
```
/data/data/com.termux/files/usr/bin/ld: warning: ld-android.so, needed by /system/lib/libdl.so, not found (try using -rpath or -rpath-link)                         /data/data/com.termux/files/usr/bin/ld: aarch64 architecture of input file `/data/data/com.termux/files/usr/lib/crtbegin_dynamic.o' is incompatible with arm output /data/data/com.termux/files/usr/bin/ld: aarch64 architecture of input file `/data/data/com.termux/files/usr/lib/crtend_android.o' is incompatible with armv4t output/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/Test-b4778a.o:(.ARM.extab+0x0): undefined reference to `__gxx_personality_v0'
......
```
This is my simple code:
```
#include <stdio.h>
#include <vector>
int main() {
  std::vector<int> vec;
  vec.push_back(0);
  return 0;
}
```
and I run the finnaly command below:
```
clang++ Test.cc -o Test --target=arm-linux-androideabi -nodefaultlibs -L/system/lib -lc -ldl -Wl,-rpath=/system/lib -nostartfiles $PREFIX/arm-linux-androideabi/lib/{crtbegin_dynamic.o,crtend_android.o} -lc++
```
It's can build successfuly, but it's like a lot of shit, Any proper solutions?

**Comment by ze00** [comment]
sorry for my bad english and this fucking format.

**Comment by xeffyr** [comment]
> but it's like a lot of shit

What did you expect ? This cannot be simplified.

You have:

* Specify compiler target.
* Specify library paths.

\- that's at least.

For cross-compilation arm(aarch64) ==> i686(x86_64) things are much more complicated as custom sysroot is required.

Generally, cross-compilation in Termux is for so called "advanced users".

**Comment by its-pointless** [comment]
it can be simplified im patching clang so it is very simplied.
`clang --target=arm-linux-androideabi example.c ` 
will work.

**Comment by ze00** [comment]
@xeffyr but at least, don't let us to specify the crt files....I think this problem is can be fix now.

**Comment by ze00** [comment]
@its-pointless thank for your hard work, but I finnaly decide use the Android Ndk to compile my program.
