### ISSUE TITLE
Is possible to add sshfs package?

### ISSUE THREAD

**Issue by alvfig** [termux/termux-packages#3532]
The `sshfs` package provides a way to mount remote filesystems via SSH. No root is needed. It could be used to backup and/or share files directly from the terminal.

**Package description**
SSHFS allows you to mount a remote filesystem using SFTP. Most SSH servers support and enable this SFTP access by default, so SSHFS is very simple to use - there's nothing to do on the server-side.

**Link to home page and sources**
https://github.com/libfuse/sshfs

**Additional information**
I have not tried to compile it yet.

**Comment by xeffyr** [comment]
> No root is needed.

On Android root is needed to use FUSE.

**Comment by xeffyr** [comment]
Seems that sshfs already requested: https://github.com/termux/termux-root-packages/issues/45. Closing to prevent duplicates.

**Comment by alvfig** [comment]
Sorry, I didn't find that another request. Thank You by your attention.
