### ISSUE TITLE
[Package request] Dart

### ISSUE THREAD

**Issue by BlueSlimee** [termux/termux-packages#3539]
Packages: `dart, pub, dartanalyzer, dartdoc, dartfmt`

Would be cool have dart on the repository. There's a dart version for ARM (v7 and v8), but it doesn't work. This is the error: 
```bash
bash: /data/data/com.termux/files/usr/bin/dart: No such file or directory
```

Maybe a hard coded path? And I really don't want install arch or something just to run dart. Thanks!

**Comment by xeffyr** [comment]
Package is now available for installation on Android 7+ devices (aarch64 and arm for now).

You can obtain it with these commands:
```
pkg install dart
```

**Comment by BlueSlimee** [comment]
Hmm, I'm running Android 9 and I can't install it. :think:

**Comment by Grimler91** [comment]
@blueslimee you are probably subscribed to the android 5&6 repo, see for example instructions here for switching: https://github.com/termux/termux-packages/issues/3333#issuecomment-487553039

**Comment by xeffyr** [comment]
@BlueSlimee Also note that is has a problem: https://github.com/termux/termux-packages/issues/3729. But for simple scripts it works fine.
