### ISSUE TITLE
PHP 7.3 is missing default extension iconv from PHP 7.2

### ISSUE THREAD

**Issue by HarisHashim** [termux/termux-packages#3541]
why this package is needed: I have a script that run with PHP 7.2 but did not run with the latest PHP package installed in Termux.

The missing extension is iconv.

An instruction how to install iconv in the new PHP installation will also help alot.

Best Regards
Haris

**Comment by HarisHashim** [comment]
At least now I know where the source for package that have PHP 7.2 version.

https://github.com/termux/termux-packages/blob/78b944ba05b835203cd0f3f9bfb6266401ee506a/packages/php/build.sh

But I have no idea what to do with this knowledge :D

**Comment by HarisHashim** [comment]
Maybe I can build a pkg file or something? And then I can manually execute this file in Termux?

**Comment by filisko** [comment]
I'm with the same little problem, a lot of libraries reuire iconv, I think the PHP package should enable all the extensions by default

**Comment by its-pointless** [comment]
I have attempted a fix php iconv #3560

**Comment by filisko** [comment]
Great! Let's see when they merge it :+1:

**Comment by HarisHashim** [comment]
Thanks! Eagerly waiting to test it.

**Comment by its-pointless** [comment]
> Thanks! Eagerly waiting to test it.

https://github.com/its-pointless/gcc_termux/tree/master/php-iconv for aarch64 binaries

**Comment by filisko** [comment]
@its-pointless will they merge it in the termux main repository?
