### ISSUE TITLE
File system and code editing + compilation

### ISSUE THREAD

**Issue by hydroper** [termux/termux-packages#3543]
**Problem description**

I need to open Termux files at text editor apps, like QuickEdit at Play Store.
This isn't possible because root `/data` files are hidden.

Alternatively I wanna use `/sdcard` (`/storage/emulated/shared/0`) and compile
Rust there.

**Steps to reproduce**

```sh
$ cd /sdcard/Hydroper
$ cargo new hello-world
$ cd hello-world0
$ cargo rustc --target armv7-linux-androideabi
```

**Expected behavior**

Successful compilation of Rust's 'Hello, World'.

**Additional information**
```
$ termux-info

Updatable packages:
apt/stable 1.4.9-1 arm [upgradable from: 1.4.8-9]
bash/stable 5.0.2 arm [upgradable from: 4.4.23-3]
busybox/stable 1.30.1-1 arm [upgradable from: 1.29.3-1]
ca-certificates/stable 20190124 all [upgradable from: 20181205]
dpkg/stable 1.19.4 arm [upgradable from: 1.19.2]
git/stable 2.21.0 arm [upgradable from: 2.20.1-1]
gpgv/stable 2.2.13-1 arm [upgradable from: 2.2.12]
libbz2/stable 1.0.6-2 arm [upgradable from: 1.0.6-1]
libc++/stable 19b arm [upgradable from: 18]
libcurl/stable 7.64.0 arm [upgradable from: 7.63.0]
libgpg-error/stable 1.35 arm [upgradable from: 1.34]
libicu/stable 63.1-1 arm [upgradable from: 63.1]
libnghttp2/stable 1.37.0 arm [upgradable from: 1.36.0]
ncurses/stable 6.1.20181117-1 arm [upgradable from: 6.1.20181117]
nodejs/stable 11.12.0 arm [upgradable from: 11.10.0]
openssl/stable 1.1.1b-2 arm [upgradable from: 1.1.1a]
readline/stable 8.0 arm [upgradable from: 7.0.5-2]
System information:
Linux localhost 3.10.49-843898 #1 SMP PREEMPT Thu Oct 8 06:01:02 KST 2015 armv7l Android
Termux-packages arch:
arm
Android version:
5.1.1
Device manufacturer:
samsung
Device model:
SM-J500M
```

* **Rooted:** true.

**Comment by Grimler91** [comment]
Same issue as https://github.com/termux/termux-packages/issues/3542? Closing as duplicate.

**Comment by hydroper** [comment]
@Grimler91 I meant this one; please delete the old one.

**Comment by Grimler91** [comment]
@hydroper well I'm planning on closing both of them anyways.

Android doesn't allow executable files in shared storage, and it isn't possible to make /data/data/com.termux readable to other apps. 

We can't do anything about this since it's part of android's security model. 

You can always copy the file you want to edit to /sdcard/, edit it, copy it back and then compile it. 

For the record, we probably have at least 20 variants of this "issue" already in the github repo

**Comment by hydroper** [comment]
@Grimler91 Since it's a 'build' issue, a command like `cargo build --target-dir ~/target` will do!

I also think dependencies won't get a `target` folder automatically.
