### ISSUE TITLE
[Package request] shairport-sync

### ISSUE THREAD

**Issue by wokawoka** [termux/termux-packages#3552]
Being able to install shairport-sync would allow to use the device on which termux is running as an airplay receiver IN SYNC with other airplay receivers (very useful for multiroom audio)

the project is very actively developed here: https://github.com/mikebrady/shairport-sync

**Comment by xtkoba** [comment]
The code for `shairport-sync` heavily relies on `pthread_cancel()` and friends that are not (and will never be) implemented in Bionic libc. And it does not seem to be trivial to apply a generalization of <a href="https://github.com/termux/termux-packages/tree/fd63b7d1cf03263ca2c34e1185b9d0bd69dd2941/packages/calcurse/threading.patch">the approach taken in the `calcurse` package</a>.
