### ISSUE TITLE
EU Copyright Directive

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#3554]
For those who may not know, the EU copyright directive is likely to be approved. Will termux be affected by article 11, which state that snippets of text may be copyrighted as seen in the introduction of different packages? Also is it possible to prevent any copyright infringements which may incur liabilities for termux according to article 13?
Although it takes time for further legislation I think we should be discussing this topic now...

**Comment by xeffyr** [comment]
> snippets of text may be copyrighted as seen in the introduction of different packages

With such way someone may say that description of Termux app is copyrighted. 

Or for example, Termux Wiki uses instructions that include copyrighted content.

**Comment by xeffyr** [comment]
Most of packages, including GPL-based ones are copyrighted (look for "copyright" notes in source code). This means that Termux can't exist at all ? I don't think so, unless we are violating licenses.

Package descriptions usually obtained from readme files, manpages, program help information (usually argument `-h` or `--help`) which means they have same license as package unless explicitly specified something different.

**Comment by xeffyr** [comment]
Maybe worth to read: https://github.blog/2019-02-13-the-eu-copyright-directive-what-happens-from-here/
