### ISSUE TITLE
please help me，i don't know what's wrong with install

### ISSUE THREAD

**Issue by linganzhizhu** [termux/termux-packages#3555]
anything can't be install even the "tree" 

this is the error:

`pkg install tree` 

Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/xeffyr/x11-packages-21 x11 InRelease
Err:3 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release
  502  Bad Gateway
Reading package lists... Done
E: The repository 'https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Grimler91** [comment]
Try again, this can happen when bintray re-signs the repo after a package has been updated. It looks like it should be alright now.

**Comment by kenneth-Q** [comment]
I thought there was something wrong with my network. :)

**Comment by xeffyr** [comment]
No updates were done yesterday. See when metadata was last modified:
```
Content-Disposition: attachment; filename="Release.gpg"
Last-Modified: Tue, 19 Mar 2019 00:15:26 GMT
```

It is likely CDN didn't have updated file but I cannot do anything with this.
