### ISSUE TITLE
[ARM] GDB segmentation fault on invalid command

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-packages#3556]
**Problem description**
On ARM devices GDB may crash if you type invalid command. This means if you accidentally make a typo in command, you will have to restart whole debugging session because GDB was crashed with "segmentation fault".

![Screenshot_20190322-165812](https://user-images.githubusercontent.com/25881154/54832210-67c86c80-4cc4-11e9-8b77-c872e12902e8.png)

**Steps to reproduce**
1. Launch GDB.
2. Type invalid command, e.g. "abcdef".

**Expected behavior**
GDB should print error and wait for the next command.

**Additional information**
```
Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.113-g955ea3f #1 SMP PREEMPT Sat Jun 30 09:25:00 UTC 2018 armv7l Android
Termux-packages arch:
arm
Android version:
6.0.1
Device manufacturer:
Asus
Device model:
Nexus 7
```

**Comment by its-pointless** [comment]
I already fixed this with arm exceptions branch

**Comment by its-pointless** [comment]
#3452 
Fixes this as well
