### ISSUE TITLE
Termux Openvpn build error - lzoutil.h not found

### ISSUE THREAD

**Issue by srampv** [termux/termux-packages#3557]
I am trying to compile openvpn-2..4.7 binary , getting below error 
lzoutil.h not found , I have installed lzo package 
![Screenshot_20190322-133445_Termux](https://user-images.githubusercontent.com/6702943/54851731-1ad69d00-4ca8-11e9-9816-044d90549bd0.jpg)

**Comment by xeffyr** [comment]
>  I have installed lzo package

Have you checked \*-dev packages ? Development files are stored in a separate packages which end on \*-dev.

**Comment by xeffyr** [comment]
What you need is `liblzo-dev`.

**Comment by srampv** [comment]
ok thanks for the quick response
