### ISSUE TITLE
Unable to install octave on termux 

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#3559]
pkg install octave
Hit:1 https://its-pointless.github.io/files termux InRelease
Hit:2 https://termux.net stable InRelease
Ign:3 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable InRelease
Get:4 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release [6065 B]
Hit:4 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 octave : Depends: libhdf5 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by its-pointless** [comment]
Install science-packages
