### ISSUE TITLE
After ssh exit, every thing stucked

### ISSUE THREAD

**Issue by cheetosysst** [termux/termux-packages#3565]
http://imgur.com/a/ZYY0nW0

Not sure how I triggered it, well... It happened
Tried executing ls but as you see, it stuck on the same line and wouldn't move on to the next line

**Comment by kenneth-Q** [comment]
Are you using proot?

**Comment by cheetosysst** [comment]
No, I still have problem using those on mine. I wasn't using those at the time so I think it's not the reason.

I tried to trigger it again but no success, maybe you can close it because it might be my problem and can be fix by click to the home page and reopen the session.

**Comment by xeffyr** [comment]
Thats just messing with terminal capabilities.
Typical behaviour when writing binary content to stdout. Invalid encodings may also cause this, Termux is UTF-8 capable but may have problems with UTF-16 or higher. Or just some ncurses-based programs do not reinitialize terminal with correct settings on exit with ctrl-c.
