### ISSUE TITLE
Php no longer working

### ISSUE THREAD

**Issue by Allistar101** [termux/termux-packages#3566]
php -help
CANNOT LINK EXECUTABLE "php": library "libreadline.so.8" not found
Aborted
Their is an issue with libreadline8 and php 7
It also won't run php servers

**Comment by xeffyr** [comment]
> CANNOT LINK EXECUTABLE "php": library "libreadline.so.8" not found

Upgrade was not done. So do `pkg upgrade` before installing something. We switched to libreadline v8.0.
