### ISSUE TITLE
Cannot SCP from mac to android

### ISSUE THREAD

**Issue by m147** [termux/termux-packages#3567]
I've tried 
`scp -P 8022 ~/Pictures/fu-bar.jpg <androidusername>@<local.i.p.address>:~/Download`

it returns:

`Welcome to Termux!`
but does not copy the file.

What is the problem, what am I doing wrong?  Please help.  
Thank you.

**Comment by buttaface** [comment]
I don't have a mac, but running almost the same command to scp a file from Termux in one Android device to another doesn't reproduce the issue for me, ie it works and copies the file.

**Comment by xeffyr** [comment]
> doesn't reproduce the issue for me

This issue has nothing to do with packages `openssh` or `dropbear`.

He wrote:
```
I've tried
scp -P 8022 ~/Pictures/fu-bar.jpg <androidusername>@<local.i.p.address>:~/Download

it returns:

Welcome to Termux!
but does not copy the file.
```

and it seems that scp launches **login shell**.

***

Currently, I'm not able to break `scp` with bashrc or profile in Termux. Though, easily did this on PC.
