### ISSUE TITLE
logcat hangs on API 24

### ISSUE THREAD

**Issue by xdegaye** [termux/termux-packages#3568]
[Using SSH](https://termux.com/ssh.html) suggests to use ``logcat`` to view the log output from ``sshd`` but on API 24 ``logcat`` hangs. ``adb logcat`` works just fine though.

Running [termux-setup-storage](https://wiki.termux.com/wiki/Termux-setup-storage) has the nice side-effect of making ``logcat`` work again. I do not know if this is expected. Maybe the [Using SSH](https://termux.com/ssh.html) wiki could be updated to suggest to also run ``termux-setup-storage``. I may be missing something though.

**Comment by xeffyr** [comment]
* Not enough information about issue.

* Our `logcat` is just a wrapper around system utility `/system/bin/logcat`.

* Utility `logcat` works on most devices. No matter, API 23, 24 or 26 - it just works. I guess there ROM-specific problem.
