### ISSUE TITLE
Error with bintray-upload-deb

### ISSUE THREAD

**Issue by citrusui** [termux/termux-packages#357]
I have exported my Bintray username, API Key, and organization, but `bintray-upload-deb` still doesn't work quite right.

``` sh
scripts/bintray-upload-deb debs/coreutils*.deb -r deb

Does this look correct?
- Name: coreutils
- Version: 8.25-4
- Architecture: aarch64
- Distribution: stable
- Component: main
- BinTray Repo: citrusui/deb

(Please enter y/n): y
Submitting package...
Traceback (most recent call last):
  File "scripts/bintray-upload-deb", line 81, in <module>
    main()
  File "scripts/bintray-upload-deb", line 76, in main
    raise Exception("Failed to submit package: {0}\n{1}".format(response.status_code, response.text))
Exception: Failed to submit package: 400
{"message":"Failed to resolve package name"}
```

Specifying `-n` doesn't resolve this issue. Please help!

**Comment by fornwall** [comment]
I've removed the `bintray-upload-deb` script now.

If you want to use bintray you need either to use the web interface or a third-party script.

There is also the [termux-apt-repo](https://github.com/termux/termux-apt-repo) tool available for creating a Termux apt repository.
