### ISSUE TITLE
can't launch some apps with Magisk startup script

### ISSUE THREAD

**Issue by rodibin-at-placemaildotonline** [termux/termux-packages#3573]
**Problem description**
I have a [magisk startup script](https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md) that loads some things and not others (see below).` rclone mount `works just fine but `sshd` need to be launched manually inside of termux. Does anyone know why?

```
#!/system/bin/sh
PATH=$PATH:/data/data/com.termux/files/usr/bin/

sleep 15
rclone mount test: /data/media/0/test \

sleep 5

transmission-daemon --log-info -g '/storage/tools/transmission/'
```

**Steps to reproduce**
Copy script into /sbin/.magisk/img/.core/service.d/script.sh

**Expected behavior**
sshd should launch and allow access it, but it does not work

**Additional information**
Linux localhost 4.9.109-tegra-g4fa2f5b #1 SMP PREEMPT Sun Mar 3 15:08:57 PST 2019 armv8l Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
NVIDIA
Device model:
SHIELD Android TV

**Comment by xeffyr** [comment]
> Does anyone know why?

https://wiki.termux.com/wiki/Differences_from_Linux.

Setting `PATH` is not enough. Android's linker does not know anything about where Termux's libraries located.

You need
```
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
```

and also never set `PATH` in way like you did (`PATH=$PATH:/data/data/com.termux/files/usr/bin/`), do
```
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:$PATH
```
to make sure that search for binaries is done for Termux binaries firstly and only then fallback to default. Just because LD_LIBRARY_PATH set above may cause issues with the system ones.

**Comment by rodibin-at-placemaildotonline** [comment]
Thanks so much, so put this in the script? 

```
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:$PATH
export path 
```

why is it ok to export LD_LIBRARY_PATH like above but then PATH variable needs to be set directly and then exported?

**Comment by xeffyr** [comment]
```
export PREFIX=/data/data/com.termux/files/usr
export HOME=/data/data/com.termux/files/home
export PATH=${PREFIX}/bin:${PREFIX}/bin/applets:$PATH
export LD_LIBRARY_PATH=${PREFIX}/lib:$LD_LIBRARY_PATH
```
