### ISSUE TITLE
dos2unix needs to be rebuilt due to the infamous nl_langinfo error

### ISSUE THREAD

**Issue by valpogus** [termux/termux-packages#3577]
**Problem description**
Executables dos2unix, unix2dos... from package dos2unix throw a CANNOT LINK EXECUTABLE error.

**Steps to reproduce**
dos2unix --help

**Expected behavior**
Help message printed.

**Actual behavior**
CANNOT LINK EXECUTABLE "dos2unix": cannot locate symbol "nl_langinfo" referenced by "/data/data/com.termux/files/usr/bin/dos2unix"...
Aborted (core dumped)

**Additional information**
Rebuilding the package solves the problem.

**Comment by fornwall** [comment]
@valpogus Thanks for reporting!

This has been fixed in version `7.4.0-1` of the dos2unix package, update by running `pkg up`.
