### ISSUE TITLE
Metasploit framework unstable-repo

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#3578]
the latest upgrade froze the application.
Nothing appears after this splash

[*] StartiNg the Metasploit Framework console...-

**Comment by dipayand** [comment]
how do I rollback to previous version

**Comment by Grimler91** [comment]
The repo keeps older versions for a month so you can run `pkg in metasploit=4.17.37` in this particular case

**Comment by Auxilus** [comment]
@dipayand msf5 seems to be working on my device (aarch64), If you are using it for the first time it may take a few more seconds to build up the modules cache.

**Comment by dipayand** [comment]
4.17.37 not found...

**Comment by dipayand** [comment]
mine is armv7l... are you sure it will work

**Comment by xeffyr** [comment]
> Nothing appears after this splash

Just wait a bit.

**Comment by dipayand** [comment]
sorry to say... it is stuck since last 30 minutes
