### ISSUE TITLE
Is it possible to run an hourly cron from termux

### ISSUE THREAD

**Issue by Mannshoch** [termux/termux-packages#358]
I Installed Perl on Termux and need an hourly cron (if network is available).

**Comment by fornwall** [comment]
Have you tried running `crontab -e` to edit the crontab, and then start `crond`?

Note that if you want this to be run always (not only when using your device) you will probably want to make Termux prevent the device from sleeping - pinch expand the Termux notification and press the `WAKE` button.

**Comment by Mannshoch** [comment]
Thats the big Question is this a energie save solution is Termux created to use it this way or has Termux an other Solution build in. How could I add AFWall+ rule for such a self created service?

**Comment by stephengroat** [comment]
Just an idea, the termux api could also add support for the `JobScheduler` api to allow something like this without having to run `crond` in the background

**Comment by Grimler91** [comment]
I guess termux:boot and the tasked plugin could be helpful for this

**Comment by benmoran** [comment]
I implemented @stephengroat's suggestion - https://github.com/termux/termux-api/pull/235.
