### ISSUE TITLE
transmission: calling torrent completion script does not work

### ISSUE THREAD

**Issue by rodibin-at-placemaildotonline** [termux/termux-packages#3586]
**Problem description**
I have a special torrent script called on torrent completion (script-torrent-done-filename) that is not working (it works fine when I call it as root). 

**Steps to reproduce**
Edit script-torrent-done-filename in settings.json to a .sh script that is placed in /data/data/com.termux/files/usr/share/transmission/test.sh and chmod +x test.sh.

Even a simple "hello world" script does not execute on torrent completion, even though the log says the script is called.

**Expected behavior**
I expected the script to run. There is no info in 'logcat -s transmission' to help debug

**Additional information**
# termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 4.9.109-tegra-g4fa2f5b #1 SMP PREEMPT Sun Mar 3 15:08:57 PST 2019 armv8l Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
NVIDIA
Device model:
SHIELD Android TV

Depending on problem, additional information may be requested:
@fornwall I think is the maintainer for this package?

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
* How you launch "transmission" ?
* Have you tried a simple script that does not involve Termux environment ?
   ```Shell
   #!/system/bin/sh
   echo "foo" > /sdcard/bar.txt
   ```
   (here file /sdcard/bar.txt should appear if script was called)

**Comment by rodibin-at-placemaildotonline** [comment]
- I launch transmission from ssh under `tsu`. Ultimately I'm trying to launch it from a Magisk boot script since Termux-boot isn't available on my platform but I want to make sure this works first.

- I tried your script and no file appears in /sdcard/ 
:(

**Comment by rodibin-at-placemaildotonline** [comment]
Also, do you know where the default directory is for the transmission settings? I can't find it anywhere.

**Comment by xeffyr** [comment]
>know where the default directory is for the transmission settings in termux

`$HOME/.config/transmission-daemon`
