### ISSUE TITLE
sshd: permission denied when attempting to connect as root

### ISSUE THREAD

**Issue by rodibin-at-placemaildotonline** [termux/termux-packages#3589]
**Problem description**
I need to login to termux via sshd from a root user (I'm using a startup script from Magisk)

**Steps to reproduce**
in [termux](https://wiki.termux.com/wiki/Remote_Access): 
```
tsu
passwd (set password)
sshd
```
in remote system:

`
ssh -p 8022 ip.of.android.box
`

**Expected behavior**
I expected to login, instead I get a permission denied error: 
user@ip.of.android.box: Permission denied (publickey,password,keyboard-interactive).

**Additional information**
```
Updatable packages:
All packages up to date
System information:
Linux localhost 4.9.109-tegra-g4fa2f5b #1 SMP PREEMPT Sun Mar 3 15:08:57 PST 2019 armv8l Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
NVIDIA
Device model:
SHIELD Android TV
```

**Comment by Grimler91** [comment]
Start sshd with the `-D` option and check what it outputs when you try to connect.

I'm guessing sshd doesn't know where to find config files and other stuff as you don't preserve environmental variables when changing to the root shell (try `tsu -a` instead).

**Comment by rodibin-at-placemaildotonline** [comment]
@Grimler91 hmm, I tried `tsu -a` and then `sshd -D -dd`

from connecting computer
'ssh -p 8022 root@192.168.1.123'

```
debug 1: userauth-request for user root service ssh-connection method none
debug 1: attempt 0 failures 0
debut 2: input_userauth_request: try method none
Failed none for root from 192.168.1.254 port 49999 ssh2
debug 1: userauth-request for user root service ssh-connection method keyboard-interactive

... snip

Failed keyboard-interactive for root from 192.168.1.254 port 49999 ssh2
debug 1: userauth-request for user root service ssh-connection method password
debug 1: attempt 2 failures 1
debug 2: input_userauth_request: try method password
NET LOGIN REFUSED FROM 192.168.1.254 port 49999
Failed password for root from 192.168.1.172 port 49999 ssh2
```

**Comment by xeffyr** [comment]
I suggest you to try to edit file `$PREFIX/etc/ssh/sshd_config` and set this:
```
PermitRootLogin yes
```

If you read appropriate manpages, you will see that SSH disallows password logins for root by default.

**Comment by rodibin-at-placemaildotonline** [comment]
Thanks, that fixed it

any chance this can be included in the default configuration for termux? there is nothing stopping someone from connecting via ssh, running tsu, and then connecting via root.

**Comment by xeffyr** [comment]
`PermitRootLogin yes` will not be included by default. This is reasonable standard behaviour of OpenSSH.
