### ISSUE TITLE
Postgres prblm

### ISSUE THREAD

**Issue by ab2ou** [termux/termux-packages#3591]
How i can fix this ! Any one pls
postgresql
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2019-03-28 08:17:01.856 EET [26427] FATAL:  database files are incompatible with server
2019-03-28 08:17:01.856 EET [26427] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 11.2.
 stopped waiting
pg_ctl: could not start server
Examine the log output.

**Comment by Grimler91** [comment]
The error message says it all really, see https://stackoverflow.com/questions/17822974/postgres-fatal-database-files-are-incompatible-with-server or https://stackoverflow.com/questions/19076980/postgres-versions-are-not-compatible

**Comment by postsql** [comment]
you need to upgrade your data directory

see https://www.postgresql.org/docs/11/pgupgrade.html

but I am not sure termux keeps the old version of postgresql around, which is neede for successful pg_upgrade run
