### ISSUE TITLE
Cant install nokogiri gem. Please advice

### ISSUE THREAD

**Issue by acidphuck** [termux/termux-packages#3592]
After i updated to Ruby 2.6, everything has gone wrong. I have been trying to install nokogiri but still unable to do so. If anyone has occured the same problem and able to install nokogiri v 1.10.1 or v 1.10.2 on Ruby 2.6.2 please advice.

**Comment by Grimler91** [comment]
You are probably missing some dependency. Read the log to figure out which one.

**Comment by Grimler91** [comment]
You can also have a look at all the previous issues: https://github.com/termux/termux-packages/search?q=nokogiri&type=Issues

**Comment by acidphuck** [comment]
I really hope so that i ve missed a dependencies. Have you ever tried install metasploit on Ruby 2.6.0 inside Termux? Each time Ruby update to a new version, most of the Ruby code in termux especially Metasploit and wpscan will get Segfault but for me, this is the worst but maybe its not termux..most probably because i m using a fuck up phone. Lol.

**Comment by xeffyr** [comment]
> Have you ever tried install metasploit on Ruby 2.6.0 inside Termux?

Dude, metasploit already available via package.

> Lol.

Of course, not reading Wiki and seeking for ways that will potentially fail thats what is called lol...

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/Metasploit_Framework
