### ISSUE TITLE
package request: insmod, kmod, depmod

### ISSUE THREAD

**Issue by huitc** [termux/termux-packages#3595]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
Duplicate of:

* https://github.com/termux/termux-packages/issues/2520

* https://github.com/termux/termux-root-packages/issues/29
