### ISSUE TITLE
Unicode input in bash shell not working over SSH

### ISSUE THREAD

**Issue by magiruuvelvet** [termux/termux-packages#3598]
**Problem description**
Unicode input via SSH is rejected / doesn't work with the `openssh` server with the `bash` shell. I configured the termux environment to be owned by root and wrote an `init.d` script to autostart `sshd` on boot on my Android device (SuperSU root). Everything is working fine and I can use SSH without problems, but there is this major annoyance that Unicode input, in my case Japanese, is rejected in the bash shell. I can write Japanese in `nano` just fine without problems, but in the shell it doesn't work. My terminal on the Linux box is KDE/Konsole from where I ssh into the device. I locked the termux app because it is no longer owned by the termux user, so I can't test there. I prefer my Linux terminal anyway over OSD keyboard nightmares and small screens.

**Steps to reproduce**
- root required
- chown -R root:root /data/data/com.termux/files
- start `sshd` on port 22 as root user with UTF-8 encoding (`$LANG` environment variable) - does this work on Android??
- ssh into the device and try to write Unicode with fcitx for example
- bash rejects it, nano accepts it

`/system/su.d/sshd.sh` autostart script (works):
```sh
#!/system/bin/sh

# setup termux environment
export PATH="/data/data/com.termux/files/usr/bin:/su/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/su/xbin:/system/xbin"
export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib"
export HOME="/data/data/com.termux/files/home"

export LANG=ja_JP.UTF-8

# start ssh daemon in background
sshd || true
```

bash profile and bashrc (is loaded by bash)
```sh
# setup termux environment
export PATH="/data/data/com.termux/files/usr/bin:/su/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/su/xbin:/system/xbin"
export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib"
export HOME="/data/data/com.termux/files/home"

export LANG=ja_JP.UTF-8

...
```

**Expected behavior**
Unicode characters in `bash` are working, but they don't.

Nano screenshot running on Android:
![スクリーンショット_20190331_115333](https://user-images.githubusercontent.com/13280758/55287626-ac7e9280-53ab-11e9-9b73-df256e5a3325.png)

In bash the buffer is lost somewhere and never appears on screen. `ls` works though.
![スクリーンショット_20190331_115433](https://user-images.githubusercontent.com/13280758/55287629-c4561680-53ab-11e9-84f4-e3aa69d584b6.png)

**Additional information**
Post output of command `termux-info`.
```plain
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.84-perf-ga8bab08 #1 SMP PREEMPT Tue Feb 28 23:25:51 CST 2017 aarch64 Android
Termux-packages arch:
aarch64
Android version:
6.0.1
Device manufacturer:
LENOVO
Device model:
Lenovo PB2-690M
```

printenv output:
```plain
SHELL=/system/bin/sh
PWD=/data/data/com.termux/files/home
LOGNAME=root
EXTERNAL_STORAGE=/sdcard
HOME=/data/data/com.termux/files/home
LANG=ja_JP.UTF-8
SSH_CONNECTION=[redacted]
ANDROID_DATA=/data
TERM=screen-256color
USER=root
SHLVL=1
ANDROID_ROOT=/system
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
PS1=[\u] \w $ 
SSH_CLIENT=[redacted]
PATH=/data/data/com.termux/files/usr/bin:/su/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/su/xbin:/system/xbin
SSH_TTY=/dev/pts/0
```

If you need any more information, please let me know. My guess is that this is some kind of bug in the bash shell, rather than ssh, since it works fine in nano.

---

EDIT: Something I want you to know: fcitx input generally works in SSH on my machine. I have other remote servers with actual Linux and set the global encoding to UTF-8 and input works fine with `bash` and other shells. So I blame the bash build on termux to do some weird things.

**Comment by xeffyr** [comment]
> export LANG=ja_JP.UTF-8

Locales are unsupported.

**Comment by xeffyr** [comment]
> My guess is that this is some kind of bug in the bash shell, rather than ssh, since it works fine in nano.

No.
Nano just resets terminal settings on exit. Actually same is doable with `stty` or `reset`.

**Comment by xeffyr** [comment]
@magiruuvelvet Can you post here example input that causes problem ?

**Comment by magiruuvelvet** [comment]
Simple writing something with fcitx in Japanese like `こんにちは` and than pressing enter is enough. fcitx than sends the UTF-8 encoded buffer to the terminal application. But the buffer seems to be lost somewhere.

I don't guess root is required, but I never tried it with the default termux setup before setting the ownership to root and lock the app. You could try pasting the string above and see if it works.

**Comment by xeffyr** [comment]
Thanks, I will check what happens.

**Comment by xeffyr** [comment]
I was not able to reproduce the problem with default Termux settings/environment.
<img src="https://user-images.githubusercontent.com/25881154/55288075-f327b900-53ba-11e9-95a9-31b45e651639.jpg" width="500px" alt="bash working properly screenshot"/>

Actually, error was caused by setting `export LANG=ja_JP.UTF-8` but I wrote before that **locales are not supported**. You have to remove all overrides for this variable in your bashrc files and bash will work properly (see screenshot above).

**Comment by magiruuvelvet** [comment]
It didn't work unfortunately, I need to debug this further myself what is going on. Thanks for the help anyways.
