### ISSUE TITLE
MPD Segmentation fault

### ISSUE THREAD

**Issue by Xarchuser** [termux/termux-packages#3599]
**Problem description**

```
starting mpd the music player daemon
Segmentation fault
```

**Steps to reproduce**

`mpd`

**Expected behavior**

`no errors `

**Additional information**

termux-info:

```
Updatable packages:
dnsutils/stable 9.13.6-1 arm [upgradable from: 9.13.4]
System information:
Linux localhost 3.10.73-perf-g94fc9a6 #1 SMP PREEMPT Tue Oct 25 19:17:12 CST 2016 aarch64 Android
Termux-packages arch:
arm
Android version:
5.1.1
Device manufacturer:
Xiaomi
Device model:
Redmi Note 3
```

Additional information:

Tracefile logs:

[Tracefile](https://pastebin.com/4DMypVTy)

strace log:

[Strace](https://gist.githubusercontent.com/Xarchuser/4c7b67cdc1c70785dab5cbe2d6225389/raw/7b5f987950d7be63748666d30d5592248eb7c0c2/gistfile1.txt)

Found a similar issue as #2137 but no solutions so far...

**Comment by xeffyr** [comment]
You just duplicated https://github.com/termux/termux-packages/issues/2137 which is in "open" state.

**Comment by Xarchuser** [comment]
sorry. so Im closing this one, I'll move it to #2137
