### ISSUE TITLE
Cant install expo-cli

### ISSUE THREAD

**Issue by GalacticRogue** [termux/termux-packages#3607]
**Problem description**
I have installed nodejs via `pkg install nodejs` and its installed successfully but , I am unable to install the expo-cli via npm  I have used `npm install -g expo-cli` but it is giving me some weird errors.

Here's the screenshot of the errors [Errorimage](https://drive.google.com/file/d/1tDy-5e8cigrAIiKoqJQP6jICcNfnMQrp/view?usp=drivesdk)

**Steps to reproduce**
```
pkg install nodejs 
npm install -g expo-cli
```
**Expected behavior**
It should install the expo-cli without errors

**Comment by GalacticRogue** [comment]
I have installed clang and other dependencies  now using   ```
pkg upgrade && pkg install autoconf automake bison bzip2 clang cmake \
coreutils diffutils flex gawk git grep gzip libtool make patch perl  \
sed silversearcher-ag tar wget pkg-config
``` but still getting errors [ErrorImage](https://drive.google.com/file/d/17tg3HAQVlboPYud9KSoha2ab-1K4FffX/view?usp=drivesdk)

**Comment by GalacticRogue** [comment]
The problem occured cause of python2 , as I have installed it again , expo-cli tends to install , thanks for the response btw.

**Comment by raph-son** [comment]
@TheGlitchh can you please help look into [#3970](https://github.com/termux/termux-packages/issues/3970)
