### ISSUE TITLE
Can't run npm

### ISSUE THREAD

**Issue by dzx-dzx** [termux/termux-packages#3608]
Trying to run "npm" always results in the following error message:
> Bad system call

It occurred on both of my phones,one is Android 8.0,rooted,and the other is Android 9.0, not rooted.Tried reinstall.

**Comment by Grimler91** [comment]
What's the output of `termux-info`? 
Are you using nodejs or nodejs-lts?

**Comment by dzx-dzx** [comment]
>Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 4.9.97 #1 SMP PREEMPT Fri Feb 15 17:53:12 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
HUAWEI
Device model:
BKL-AL20

**Comment by Grimler91** [comment]
I've pushed an update to the master branch and opened a PR for the android-5 branch with a fix. 

If you feel adventurous and don't want to wait then you could switch to the new repo by editing `$PREFIX/etc/apt/sources.list` and replace
```deb https://termux.net stable main```
with 
```deb https://dl.bintray.com/termux/termux-packages-24 stable main```
(See https://wiki.termux.com/wiki/Bintray_package_hosting for more information)

This will subscribe you to the new android-7 repo which is currently being tested. The switch to this new repo will happen within a few weeks anyways.

Closing this as it is fixed (on the master branch).

**Comment by houd1ni** [comment]
> 
> 
> I've pushed an update to the master branch and opened a PR for the android-5 branch with a fix.
> 
> If you feel adventurous and don't want to wait then you could switch to the new repo by editing `$PREFIX/etc/apt/sources.list` and replace
> `deb https://termux.net stable main`
> with
> `deb https://dl.bintray.com/termux/termux-packages-24 stable main`
> (See https://wiki.termux.com/wiki/Bintray_package_hosting for more information)
> 
> This will subscribe you to the new android 7 (and newer) repo which is currently being tested. The switch to this new repo will happen within a few weeks anyways.
> **But note that it is for devices with android 7 and newer only**
> 
> Closing this as it is fixed (on the master branch).

Changed the list, a lot of everething, including npm have upgraded while `apt upgrade`.

`npm -v` is OK
`npm i` is `Bad system call` during installation.

**Comment by ourarash** [comment]
This gives me `bad system call`:

`npm install https://github.com/ourarash/get-cursor-position.git`
