### ISSUE TITLE
Can't link against jni with clang

### ISSUE THREAD

**Issue by cppdev-123** [termux/termux-packages#3616]
I want to use the jni functions inside c++ source code
But the linker can't resolve any reference to any jni function
I tried to add -ljvm flag to the linker but it can't find the library

Is the library missing from Android or the name is wrong?

Android oreo 8.1

**Comment by xeffyr** [comment]
> the name is wrong?

Yes, wrong.
In most cases you don't have to specify additional libraries at all in Android.
