### ISSUE TITLE
"PasswordAuthentication no" in "sshd_config" is not honored

### ISSUE THREAD

**Issue by steffenl82** [termux/termux-packages#3617]
sshd does not honor "PasswordAuthentication" set to "no" in sshd_config, i.e. a password login is still possible.

I'm using openssh 7.9p1-4 with latest termux on an arm64 device

**Comment by xeffyr** [comment]
> sshd does not honor "PasswordAuthentication" set to "no" in sshd_confi

Honors. I just verified that. Just make sure that:

- **sshd** was restarted.
- no duplicated lines in sshd_config.

**Comment by steffenl82** [comment]
You are right. I dont know where the problem was. But the setting now seems to be honored.
