### ISSUE TITLE
ssh always launches a login shell

### ISSUE THREAD

**Issue by Keith-S-Thompson** [termux/termux-packages#3620]
**Problem description**
Running a remote command via ssh, for example

    ssh -p 8022 android_deviceecho hello

launches `bash` as a login shell, causing it to source `$HOME/.bash_profile`. This causes problems, particularly if `.profile` produces output.

See this discussion on reddit:
https://www.reddit.com/r/termux/comments/b95j19/noninteractive_shell_via_ssh_invoking_bash_profile/

**Steps to reproduce**
On the device, add this line to `$HOME/.profile` :

    echo This is .profile

and run

    sshd

On another system:

    ssh -p 8022 echo hello

**Expected behavior**
Expected:

    hello

Actual:

    This is .profile
    hello

**Additional information**
Post output of command `termux-info`.
```
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.71-perf-ge30d5c4 #1 SMP PREEMPT Tue Feb 5 04:51:33 CST 2019 armv7l Android
Termux-packages arch:
arm
Android version:
8.1.0
Device manufacturer:
motorola
Device model:
Moto G (5) Plus
```

Proposed patch:
```
diff --git packages/termux-tools/login packages/termux-tools/login
index 9652d67a..76e65921 100755
--- packages/termux-tools/login
+++ packages/termux-tools/login
@@ -20,4 +20,8 @@ if [ -f $PREFIX/lib/libtermux-exec.so ]; then
        $SHELL -c "busybox true" > /dev/null 2>&1 || unset LD_PRELOAD
 fi
 
-exec "$SHELL" -l "$@"
+if [ "$TERM" ] ; then
+       exec "$SHELL" -l "$@"
+else
+       exec "$SHELL" "$@"
+fi
```

**Comment by xeffyr** [comment]
Should be fixed in https://github.com/termux/termux-packages/commit/9ba4d9fdd32c4282a73a29036dc40f8c51c971ca and https://github.com/termux/termux-packages/commit/3832f16c0fd092aa443ec293c37315e143283d5b.

**Comment by fornwall** [comment]
@Keith-S-Thompson Thanks!
