### ISSUE TITLE
Not found library 

### ISSUE THREAD

**Issue by myfreess** [termux/termux-packages#3623]
readline/stable,now 8.0 arm [installed]

when run gawk
```
CANNOT LINK EXECUTABLE: library "libreadline.so.7" not found page record for 0xb6e8d02c was not found (block_size=16)
```
it was fixed by create symbol link:D

**Comment by xeffyr** [comment]
Which git command you executed ?

**Comment by myfreess** [comment]
Sorry, break package is gawk：|
@xeffyr
