### ISSUE TITLE
Nodejs 6

### ISSUE THREAD

**Issue by LavrenkovNV** [termux/termux-packages#3624]
Hi, i want helt to install nodejs 6 help me please
Sorry for English

**Comment by fornwall** [comment]
Hello! Version 6 of node.js is not available anymore, only version 10 (in package `nodejs-lts`) and 11 (in package `nodejs`). You could try to work with node.js 10 perhaps?

**Comment by eine** [comment]
@fornwall is Node.js 10 still expected to be available? I can find `node` (13.0.0) and `nodejs-lts` (12.14.1), but no other.

I'm trying to build and run Theia (eclipse-theia/theia#7166), which requires Node.js 10.15.3: https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites
