### ISSUE TITLE
gRPC_cli 

### ISSUE THREAD

**Issue by Ludea** [termux/termux-packages#3625]
**Package description**
Grpc_cli is a command line tool with gRPC

**Link to home page and sources**
1. Home page: https://grpc.io/
2. Source code: https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md

**Additional information**
I think i could be interestinb, we have already a gRPC package

**Comment by xtkoba** [comment]
As mentioned in https://github.com/grpc/grpc/issues/10273#issuecomment-608554503, `grpcurl` should be used instead.

Please open another issue to request packaging `grpcurl` if you wish.
