### ISSUE TITLE
clGetPlatformIDs() returns CL_INVALID_VALUE in OpenCL program.

### ISSUE THREAD

**Issue by zhyfzy** [termux/termux-packages#3629]
**Problem description**
Hi, I tried to launch some OpenCL programs on my devices. I have confirmed that my devices support OpenCL and I have launched them successfully through adb shell. 

However, in Termux, OpenCL programs always return CL_INVALID_VALUE when clGetPlatformIDs() called. I have tried them on Samsung s8, OnePlus 3 and OnePlus 5. They all throw this error, and run well if I using adb shell to launch them. It seems this problem is not related to device.

**Steps to reproduce**
Take this simple progrem for test :

```
#include<CL/cl.h>
#include <stdio.h>

int main(){
    cl_int err;
    cl_uint num_platform;
    err = clGetPlatformIDs(0, NULL, &num_platform);
    if (err != CL_SUCCESS){
        printf("Error code: %d\n", err);
        return -1;
    }
    printf("Platform number: %u\n", num_platform);
    return 0;
}
```
	
compile it using gcc in Termux:
```
gcc test.c -o test -lOpenCL -L/system/vendor/lib64 -I./opencl-header
```
	
execute it
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/system/vendor/lib64:/system/lib64
./test
```

**Expected behavior**
in termux, I get the following result, where error code -30 means CL_INVALID_VALUE in OpenCL
```
Error code: -30
```

however, once I switch to adb shell, everything works well:
```
Platform number: 1
```

**Additional information**
Post output of command `termux-info`.
```
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.66-perf+ #1 SMP PREEMPT Thu Jun 21 18:54:00 CST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
OnePlus
Device model:
ONEPLUS A3000
```

**Comment by xeffyr** [comment]
This is not a bug. Just incompatibility with Termux environment. I had to solve exactly same issue to get hashcat working in Termux (https://github.com/termux/unstable-packages/tree/master/packages/hashcat).

To make your code working, I had to do this on my device:
```Shell
[~]:$ gcc test.c -o test -L/system/vendor/lib64 -lOpenCL /system/vendor/lib64/egl/libGLES_mali.so /system/lib64/liblzma.so
[~]:$ export LD_LIBRARY_PATH=/system/vendor/lib64:/system/vendor/lib64/egl:/system/lib64
[~]:$ ./test
Platform number: 1
```

**Comment by xeffyr** [comment]
I'm suggesting you to override Termux's LD_LIBRARY_PATH:

Instead of doing:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/system/vendor/lib64:/system/lib64
```

execute following command:
```
export LD_LIBRARY_PATH=/system/vendor/lib64:/system/lib64
```

This should completely prevent conflicts with libraries located under $PREFIX/lib.

**Comment by zhyfzy** [comment]
thank you so much, it works
@xeffyr

**Comment by aswinkumar1999** [comment]
Thanks @zhyfzy and @xeffyr , Found the above to be helpful.

Though overriding the LD_LIBRARY_PATH works in the current shell , it breaks all other functionalities like `cd`  , `ls` as they require the 32 bit libraries to work.

I got the following outputs : 
```bash
$ ls
CANNOT LINK EXECUTABLE "ls": library "libandroid-support.so" not found
$ cs
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/termux/command-not-found": library "libc++_shared.so" not found
```


But Instead of doing 

```bash
export LD_LIBRARY_PATH=/system/vendor/lib64:/system/lib64
```

Doing helped me overcome this : 

```bash
export LD_LIBRARY_PATH=/system/vendor/lib64:/system/lib64:$LD_LIBRARY_PATH
```

And These are the commands that worked for me : 

```bash
gcc test.c -o test " -L/system/vendor/lib64 -lOpenCL

export LD_LIBRARY_PATH=/system/vendor/lib64:/system/lib64:$LD_LIBRARY_PATH

./test
```

Post output command of `termux-info`

```
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.179-perf+ #1 SMP PREEMPT Sat Dec 14 20:49:05 CST 2019 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6010
```

**Comment by aswinkumar1999** [comment]
@xeffyr 

I tried running `hashcat` and ended up with the following :

```
Cannot find an OpenCL ICD loader library.
```

I modified the binary and replaced the line from : 
```bash
unset LD_LIBRARY_PATH
```
to 

```bash
export LD_LIBRARY_PATH=/system/vendor/lib64:/system/lib64:$LD_LIBRARY_PATH
```

and the benchmark started working.

I'm not sure if this works in every device , but this helped for me.
My Device details are the same as in the above comment.
