### ISSUE TITLE
Help me to install nodejs package sqlite3 plz

### ISSUE THREAD

**Issue by rafis** [termux/termux-packages#363]
CPU: aarch64
Anroid: 5.0.2

While linking nodejs package `sqlite3` I'm getting undefined reference to v8 and libuv, details in attached file.

[npm-debug2.log.txt](https://github.com/termux/termux-packages/files/374266/npm-debug2.log.txt)

I have installed `apt install libuv-dev nodejs-dev`, but cannot find `libv8-dev`, and anyway seems it doesn't helps.

**Comment by clausreinke** [comment]
Could be the same as #307.

**Comment by rafis** [comment]
Thank you, @clausreinke . Yes, it has `-shared -rdynamic` and removing `-pie` from `common.gypi` helped.

**Comment by fornwall** [comment]
Closing this in favour of tracking the problem in #307.

**Comment by rafis** [comment]
But after I've created simple JavaScript script to test:

    var sqlite = require('sqlite3');

And it throws an error:

```
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen failed: cannot locate symbol "uv_close" referenced by "/data/data/com.termux/files/home/project/node_modules/sqlite3/lib/binding/node-v48-android-arm64/node_sqlite3.node"...
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/data/com.termux/files/home/project/www/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

**Comment by fornwall** [comment]
@rafis Thanks! This problem with `process.dlopen` has now been fixed in the 6.6.0-1 update of the nodejs package, to which one can update with

    apt update && apt upgrade

**Comment by gorrioncillo** [comment]
sorry but i can't install sqlite3 for nodejs, i already remove -pie
command: npm install sqlite3 -g
i have node 6.9.1
sorry i know that this thread is close but i need help
thanks

**Comment by fornwall** [comment]
@gorrioncillo What error do you get? Have you installed what you need for building (I guess something like `apt install clang make nodejs-dev libuv-dev`)?

**Comment by gorrioncillo** [comment]
yes, i have those libs. 
node-pre-gyp install --fallback-to-build
i guess thats the problem, even prove this:
https://github.com/mapbox/node-sqlite3/issues/612

**Comment by p4cm4n** [comment]
It's still the same problem happening? is there any ideas?
