### ISSUE TITLE
node/npm - Bad system call since Pie update

### ISSUE THREAD

**Issue by francispeixoto** [termux/termux-packages#3635]
I can't get node or NPM to work since my device (Samsung s8+ Snapdragon) was updated to Android 8. Calling each command returns Bad System Call. 

I reinstalled termux but the issue is still there.

**Comment by Grimler91** [comment]
Thanks for reporting! This was fixed in https://github.com/termux/termux-packages/commit/a75b2c7638378952378bb37ebfbfe628d4788ba3
