### ISSUE TITLE
After installing metasploit with this commandspkg install unstable-repo  pkg install metasploit : !!! When i do ./msfconsole !this comes , what should i do ?! Plz help 

### ISSUE THREAD

**Issue by ghezzall** [termux/termux-packages#3637]
$ cd metasploit-framework
$ ./msfconsole
Could not find nokogiri-1.10.1 in any of the sources
Run `bundle install` to install missing gems.
$ bundle install
Fetching gem metadata from https://rubygems.org/..............
Installing nokogiri 1.10.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.1/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -I
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0 -r
./siteconf20190406-534-4vi6es.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
Static linking is disabled.
checking for gzdopen() in -lz... yes
checking for iconv... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.9
with the following patches applied:
        - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.9.tar.gz into tmp/aarch64-linux-android/ports/libxml2/2.9.9... OK
Running git apply with
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.1/patches/libxml2/0001-Revert-Do-not-URI-escape-in-server-side-includes.patch...
OK
Running 'configure' for libxml2 2.9.9... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:380:in
`spawn': No such file or directory - ./configure (Errno::ENOENT)
from
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:380:in
`block in execute'
from
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in
`chdir'
from
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in
`execute'
from
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:110:in
`configure'
from
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:153:in
`cook'
from extconf.rb:365:in `block (2 levels) in process_recipe'
        from extconf.rb:257:in `block in chdir_for_build'
        from extconf.rb:256:in `chdir'
        from extconf.rb:256:in `chdir_for_build'
        from extconf.rb:364:in `block in process_recipe'
        from extconf.rb:262:in `tap'
        from extconf.rb:262:in `process_recipe'
        from extconf.rb:557:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be
found here:

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/aarch64-linux/2.6.0/nokogiri-1.10.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.1 for inspection.
Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/aarch64-linux/2.6.0/nokogiri-1.10.1/gem_make.out

An error occurred while installing nokogiri (1.10.1), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.10.1' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  factory_girl_rails was resolved to 4.9.0, which depends on
    railties was resolved to 4.2.11, which depends on
      actionpack was resolved to 4.2.11, which depends on
        actionview was resolved to 4.2.11, which depends on
          rails-dom-testing was resolved to 1.0.9, which depends on
            nokogiri
$

**Comment by xeffyr** [comment]
Metasploit Is No Longer Installable Via Your Method.
**Read the Wiki please !**

P.S. Nokogiri is not needed for recent metasploit versions...

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/Metasploit_Framework
