### ISSUE TITLE
Python3 : approximate division

### ISSUE THREAD

**Issue by Almtesh** [termux/termux-packages#364]
I had this with python3 :
<code>>>> 316/10

31.600000000000001</code>
I only have on my phone, is that normal?

**Comment by fornwall** [comment]
Yes, that is a consequence of floating point numbers and is not Termux specific!

See https://docs.python.org/3/tutorial/floatingpoint.html or google for `floating point rounding error` for more information!

**Comment by Almtesh** [comment]
Would it be hardware dependant? I see that the `termux-battery-info` gives a temperature of 30.299999237060547. Python and the termux api only gives the values as represented by the hardware.
