### ISSUE TITLE
clBuildProgram() returns CL_OUT_OF_HOST_MEMORY  in OpenCL program.

### ISSUE THREAD

**Issue by xiatengxi** [termux/termux-packages#3642]
**Problem description**
Hi, I tried to launch some OpenCL programs on my mobile devices. I have confirmed that my devices support OpenCL .

However, in Termux, OpenCL programs always return CL_OUT_OF_HOST_MEMORY when clBuildProgram() called. I have tried them on Samsung s7 Edge, OnePlus 3. They all throw this error when using root user, and run well if I using adb shell to launch them. It seems this problem is not related to device.

**Steps to reproduce**
This is sample program for test
https://github.com/xiatengxi/OpenCLError-Test/tree/master

**Expected behavior**
in termux, I get the following result, where error code -6 means CL_OUT_OF_HOST_MEMORT in OpenCL
Error code: -6

**Additional information**
Post output of command `termux-info`.
termux-info
Updatable packages:
apt/stable 1.4.9-2 aarch64 [upgradable from: 1.4.8-6]
bash/stable 5.0.3 aarch64 [upgradable from: 4.4.23-3]
binutils/stable 2.32-1 aarch64 [upgradable from: 2.31.1-3]
busybox/stable 1.30.1-1 aarch64 [upgradable from: 1.29.3]
ca-certificates/stable 20190124 all [upgradable from: 20181017]
clang/stable 7.0.1-1 aarch64 [upgradable from: 7.0.0]
cmake/stable 3.13.4-1 aarch64 [upgradable from: 3.12.4]
command-not-found/stable 1.36 aarch64 [upgradable from: 1.35]
dpkg/stable 1.19.4 aarch64 [upgradable from: 1.19.0.5]
gpgv/stable 2.2.15 aarch64 [upgradable from: 2.2.10]
jsoncpp/stable 1.8.4-2 aarch64 [upgradable from: 1.8.4-1]
libandroid-support/stable 24 aarch64 [upgradable from: 22]
libbz2/stable 1.0.6-2 aarch64 [upgradable from: 1.0.6-1]
libc++/stable 19b aarch64 [upgradable from: 18]
libcurl/stable 7.64.1 aarch64 [upgradable from: 7.61.1-1]
libedit/stable 20181209-3.1-0 aarch64 [upgradable from: 20180525-3.1-0]
libgpg-error/stable 1.36 aarch64 [upgradable from: 1.32]
libllvm/stable 7.0.1-1 aarch64 [upgradable from: 7.0.0]
libnghttp2/stable 1.37.0 aarch64 [upgradable from: 1.34.0]
libsqlite/stable 3.27.2 aarch64 [upgradable from: 3.25.2]
libutil/stable 0.4 aarch64 [upgradable from: 0.3]
libuv/stable 1.27.0-1 aarch64 [upgradable from: 1.23.2]
libxml2/stable 2.9.9 aarch64 [upgradable from: 2.9.8]
ncurses/stable 6.1.20181117-1 aarch64 [upgradable from: 6.1.20180707]
ncurses-ui-libs/stable 6.1.20181117-1 aarch64 [upgradable from: 6.1.20180707]
ndk-sysroot/stable 19b-1 aarch64 [upgradable from: 18-8]
openssh/stable 7.9p1-4 aarch64 [upgradable from: 7.9p1]
openssl/stable 1.1.1b-2 aarch64 [upgradable from: 1.1.1-2]
python2/stable 2.7.16 aarch64 [upgradable from: 2.7.15-4]
readline/stable 8.0 aarch64 [upgradable from: 7.0.5-1]
rhash/stable 1.3.8 aarch64 [upgradable from: 1.3.6-4]
termux-tools/stable 0.61 all [upgradable from: 0.56]
util-linux/stable 2.33.1-1 aarch64 [upgradable from: 2.33.1]
vim/stable 8.1.1100 aarch64 [upgradable from: 8.1.1000]
vim-runtime/stable 8.1.1100 all [upgradable from: 8.1.1000]
System information:
Linux localhost 3.18.71-14176914 #1 SMP PREEMPT Tue Sep 18 16:14:18 KST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-G9350

**Comment by xeffyr** [comment]
See https://github.com/termux/termux-packages/issues/3629.

You cannot freely to use OpenCL library in Termux because of dependency incompatibility. We cannot fix that because we have no control over system components (/system), especially ones that are proprietary vendor implementation (/system/vendor).

You can try tricks described in https://github.com/termux/termux-packages/issues/3629.

**Comment by xiatengxi** [comment]
Thank you  very much
