### ISSUE TITLE
Unable to install python3 module mechanicalsoup

### ISSUE THREAD

**Issue by InformaTutos-geek** [termux/termux-packages#3644]
![56520113_387795962043445_2478992171915542528_n](https://user-images.githubusercontent.com/38510587/55674819-795b6800-58b1-11e9-96df-0b25e2584ce7.png)
Need help !
it's been several times that i'm experiencing this problem it's not just me but everyone in my class we have to install the mechanicalsoup module of python for a project but every time we have the same installation problem shown on the picture !
So I rest my complaint
did you help us?

**Comment by xeffyr** [comment]
> did you help us?

90 % of help is in the error message. **Is libxml2 installed ?**
Install libxml2 means that you have to install all parts (we have splitted it) of libxml2 package: library, devel headers, utilities.

`pkg install libxml2 libxml2-dev libxml2-utils`

Also you have to install some additional things (again, missing parts can be determined from error message):
```
pkg install python-dev libxslt-dev
```

And of course make sure that clang is installed: `pkg install clang`

Finally, do `pip install mechanicalsoup`.
