### ISSUE TITLE
Package request: etherwake 

### ISSUE THREAD

**Issue by gottogitgoing** [termux/termux-packages#3655]
From the man page "etherwake - A tool to send a Wake-On-LAN "Magic Packet""

Description
etherwake  is  a  program that generates and transmits a Wake-On-LAN (WOL) "Magic Packet", used for restarting machines that have been soft-powered-down (ACPI D3-warm state). It generates the standard AMD Magic  Packet  format,  optionally with a password included.  The single required parameter is a station (MAC) address or a host ID that can be translated to a MAC address by an ethers(5) database specified in nsswitch.conf(5)

Personally I use etherwake to update ledger files and do apt updates for all the nix machines on my lan. Without it I have to walk around turning them all on. It would be great to have this functionality for android and seems like a natural package to be included with termux.

thanks in advance

Peter

**Comment by Grimler91** [comment]
Are there any particular features that you are after that etherwake has and [wake-on-lan](https://github.com/termux/termux-packages/tree/master/packages/wol) doesn't have?

**Comment by gottogitgoing** [comment]
Thank you for the prompt reply. There are no particular features, I had read something earlier about wol but for whatever reason missed it completely searching through the package repo. I now have it installed and will try it out. Thank you once again.
