### ISSUE TITLE
libcurl segmentfault



### ISSUE THREAD

**Issue by myfreess** [termux/termux-packages#3661]
```
curl http://bing.com
curl: (48) An unknown option was passed in to libcurl

```
When I update the libcurl, this problem solved. but when I reinstall Termux, problem alive……

**Comment by Grimler91** [comment]
> when I reinstall Termux, problem alive……

That's because the bootstraps aren't updated daily. They might contain an older version/revision of a package. Running `pkg up` is recommended in a fresh installation
