### ISSUE TITLE
Wrong metadata version in rust-std-wasm32

### ISSUE THREAD

**Issue by fneddy** [termux/termux-packages#3670]
**Problem description**
The std library from the package 'rust-std-wasm32' is not linkable due to metadata version conflict. 

    = note: rust-lld: error: /data/data/com.termux/files/usr/lib/rustlib/wasm32-unknown-unknown/lib/libstd-a63dc4494413ca11.rlib
    (std-a63dc4494413ca11.std.b7xu582k-cgu.0.rcgu.o): Unexpected meta$ata version: 1 (Expected: 2)

This error das already reported in  #3646. But it was closed without any solution or comment. 

**Steps to reproduce**

    pkg install rust
    pkg install rust-std-wasm32
    cargo new test
    cd test
    cargo build --target wasm32-unknown-unknown

**Expected behavior**
'cargo build' should give no error. 

**Additional information**

termux-info

    Updatable packages:
    All packages up to date
    Subscribed repositories:
    https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
    https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
    https://dl.bintray.com/grimler/science-packages-21 science/stable
    https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
    https://dl.bintray.com/grimler/game-packages-21 games/stable
    https://termux.net stable/main
    https://termux.net stable/main
    System information:
    Linux localhost 4.4.15+ #1 SMP PREEMPT Mon Dec 11 16:54:20 CST 2017 aarch64 Android
    Termux-packages arch:
    aarch64
    Android version:
    7.0
    Device manufacturer:
    MAZE
    Device model:
    Alpha_X

pkg show rust 
                                
    Package: rust                                   
    Version: 1.33.0                                  
    Maintainer: Kevin Cotugno @kcotugno             
    Installed-Size: 227 MB                          
    Depends: clang, openssl, lld                    
    Homepage: https://www.rust-lang.org/            
    Download-Size: 65.7 MB                          
    APT-Manual-Installed: yes                       
    APT-Sources: https://termux.net stable/main aarch64 Packages                                    
    Description: Systems programming language focused on safety, speed and concurrency

pkg show rust-std-wasm32       
               
    Package: rust-std-wasm32                       
    Version: 1.33.0                                 
    Maintainer: Kevin Cotugno @kcotugno             
    Installed-Size: 49.0 MB                         
    Depends: rust                                   
    Homepage: https://www.rust-lang.org/            
    Download-Size: 15.7 MB                          
    APT-Manual-Installed: yes                       
    APT-Sources: https://termux.net stable/main all Packages                                        
    Description: rust std for wasm32-unknown-unknown target

**Comment by fneddy** [comment]
Adding @its-pointless here. Maybe you have an idea?

**Comment by its-pointless** [comment]
https://github.com/termux/termux-packages/pull/3705 likely fixes it

**Comment by its-pointless** [comment]
sigh https://reviews.llvm.org/D56762

**Comment by its-pointless** [comment]
looks to be we are going to have to build the rust lld for rust instead of a symlink to llvm lld.

**Comment by its-pointless** [comment]
or i could be completely wrong

**Comment by its-pointless** [comment]
Whats happening is that since rust on device uses llvm-8 it has metadata version 2 for wasm objects. So the wasm32-unknown-unknown std library available is built using a rust with llvm-7 which uses metadata v1. So we need a wasm32 std built with llvm-8
