### ISSUE TITLE
Can't run any program with root on pie using tsu?

### ISSUE THREAD

**Issue by bakaika** [termux/termux-packages#3672]
**Problem description**
```bash
$ tsu
# ls
bash: /data/data/com.termux/files/usr/bin/ls: Permission denied
#
```

**Steps to reproduce**
Install tsu
Run tsu
All programs say permission denied?

**Expected behavior**
Programs should run as usual

**Additional information**
```bash
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/termux-root-packages-24 root/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.111-15529922 #1 SMP PREEMPT Wed Mar 13 15:22:15 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-A530F
```

I'm using Magisk v18.1.

It appears even `/system/bin` programs fail

```bash
# /system/bin/sh
bash: /system/bin/sh: Permission denied
#
```

Running plain `su` works fine, however?

**Comment by xeffyr** [comment]
Try `setenforce 0`.

**Comment by bakaika** [comment]
Apparently I can't change enforcing mode?

```
:/data/data/com.termux/files/home # setenforce 0
:/data/data/com.termux/files/home # getenforce
Enforcing
:/data/data/com.termux/files/home # setenforce 0
:/data/data/com.termux/files/home # getenforce
Enforcing
:/data/data/com.termux/files/home #
```

No difference with unsetting either `LD_PRELOAD` nor `LD_LIBRARY_PATH`.

**Comment by xeffyr** [comment]
Can you check output of `dmesg` ? Is there any `avc denied` errors when you trying to execute command after tsu ?

**Comment by bakaika** [comment]
Uh, there's

```
[25756.007243] Restricted making process. PID = 20241(bash) PPID = 19368(bash)
```

Running plain `ls`

**Comment by xeffyr** [comment]
> [25756.007243] Restricted making process. PID = 20241(bash) PPID = 19368(bash)

This one is interesting. Perhaps samsung-specific thing.

**Comment by bakaika** [comment]
Yeah. Maybe I'll go back to oreo, lol.

Reboot doesn't change enforing mode.

**Comment by xeffyr** [comment]
Are you able to run commands from $PREFIX/bin when executed **su** ? You are using android-7 repo so you can avoid setting vars like LD_LIBRARY_PATH.

**Comment by bakaika** [comment]
Ah looks like I am able to, but those programs can't execute anything. Interpreted executable scripts fail too.

```bash
:/data/data/com.termux/files/home # $PREFIX/bin/bash
# ls
bash: /system/bin/ls: Permission denied
# exit
```

```bash
:/data/data/com.termux/files/home # $PREFIX/bin/neofetch
env: can't execute 'bash': Permission denied
126|:/data/data/com.termux/files/home #
```

**Comment by bakaika** [comment]
Had a look at `/proc/config.gz`, found:

```bash
#
# Samsung Rooting Restriction Feature
#
CONFIG_SEC_RESTRICT_ROOTING=y
CONFIG_SEC_RESTRICT_SETUID=y
CONFIG_SEC_RESTRICT_FORK=y
CONFIG_SEC_RESTRICT_ROOTING_LOG=y
# CONFIG_CORESIGHT is not set
```

HmMmMmM...

**Comment by xeffyr** [comment]
Seems like CONFIG_SEC_RESTRICT_FORK was greatly improved on latest ROMs.
On my old device it does not restrict execution from /data.

**Comment by bakaika** [comment]
Yeah haha. Man I wish they'd let us root ROMs more easily. Such a shame.
