### ISSUE TITLE
Python Pygame

### ISSUE THREAD

**Issue by Mishqutin** [termux/termux-packages#3675]
When trying to install Pygame I get an error about missing dependecies that I have no idea where to get from. Since Termux has X11 package it would be very nice if we could also mess around with Pygame.

Here's the error:
```
WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...

    /data/data/com.termux/files/usr/bin/sh: 1: pkg-config: not found
    /data/data/com.termux/files/usr/bin/sh: 1: pkg-config: not found
    /data/data/com.termux/files/usr/bin/sh: 1: pkg-config: not found

    Hunting dependencies...
    WARNING: "pkg-config freetype2" failed!
    SDL     : found 1.2.15
    FONT    : not found
    IMAGE   : not found
    MIXER   : not found
    PNG     : not found
    JPEG    : not found
    SCRAP   : found
    PORTMIDI: not found
    PORTTIME: not found
    FREETYPE: found 2.10.0
    Missing dependencies

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-rbkjy4rs/pygame/
```

**Comment by Grimler91** [comment]
Installing pkg-config would be a good start. You then also perhaps want to install the dependencies in that list (both the libraries and the -dev package, so for example `pkg install libpng libpng-dev`). 
We don't have portmidi, porttime, scrap, mixer in the main repo though and I'm not sure what software "font" and "image" refers to. These depedencies are hopefully optional.

**Comment by s33wagz** [comment]
anyway to get portmidi, porttime, scrap, mixer installed?

**Comment by SultanEryque** [comment]
you have you install the dependencies separately and focus with the sdl2 library...
