### ISSUE TITLE
libxvid

### ISSUE THREAD

**Issue by ulist** [termux/termux-packages#3676]
I'm trying to build ffmpeg with the flowing options
``
--enable-libass                 --enable-cross-compile                 --enable-gnutls                 --enable-gpl                 --enable-libmp3lame                 --enable-libfreetype                 --enable-libvorbis                 --enable-libopus                 --enable-libx264                 --enable-libx265                 --enable-libxvid                 --enable-libvpx                 --enable-shared                 --enable-libsoxr                 --enable-neon --disable-lzma
``
I get error
``ERROR: libxvid not found`` 
Where to install it?

**Comment by tomty89** [comment]
Make sure you have `xvidcore-dev`

**Comment by ulist** [comment]
Another error gnutls not found using pkg-config but it's exist
``pkg-config --exists --print-errors gnutls ``
Returned nothing and guntls.pc exist

**Comment by xeffyr** [comment]
> Returned nothing and guntls.pc exist

It should print nothing if gnutls exists.

**Comment by ulist** [comment]
Same
`` $ pkg-config --libs gnutls
-L/data/data/com.termux/files/usr/lib -lgnutls ``

**Comment by ulist** [comment]
When I tried only with --enable-gnutls it works probably other options effect?

**Comment by ulist** [comment]
Fixed  it was require ``nettle`` package
