### ISSUE TITLE
Username became bash-5.0$ ??

### ISSUE THREAD

**Issue by Satyrcore** [termux/termux-packages#3678]
bash-5.0$ whoami
u0_a377
bash-5.0$

This happened after i did this to bash.bashrc::

command_not_found_handle() {
/data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"
}
                 
eval $(thef*ck --alias f*ck)

alias install='apt install'
alias upup='apt update && apt upgrade'

Not a big deal just curious about a fix

**Comment by tomty89** [comment]
Just add this back:
https://github.com/termux/termux-packages/blob/9fd6e5b5f48d9b9e69c707bfd53a1f15a7cc02af/packages/bash/etc-bash.bashrc#L5
As you obviously deleted the line.

**Comment by Satyrcore** [comment]
thank you

Feel silly now

**Comment by sayan258** [comment]
Really thanks

**Comment by irfhan727** [comment]
But after I exit. Termux than it show again so help me please I use rootme after showing this I uninstall rootme but it showing continually
