### ISSUE TITLE
ESC button no response with an OTG keyboard

### ISSUE THREAD

**Issue by t123yh** [termux/termux-packages#368]
I'm using vim with a physical keyboard. However, the ESC button is not responding. Is that implemented? How can I debug or help to debug?

**Comment by fornwall** [comment]
This issue was moved to termux/termux-app#120

**Comment by fornwall** [comment]
@t123yh I've moved the issue to https://github.com/termux/termux-app/issues/120 (there is a separate repo for the app itself), so please answer there!

Could you use the app https://play.google.com/store/apps/details?id=com.sonelli.keywatcher and press Escape and attach the output?
