### ISSUE TITLE
Unable to install metasploit 

### ISSUE THREAD

**Issue by r4jesh** [termux/termux-packages#3685]
An error occurred while installing nokogiri
(1.10.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.1'
--source 'https://rubygems.org/'` succeeds before
bundling.

**Comment by xeffyr** [comment]
Now the only way to get metasploit is:
```
pkg install unstable-repo
pkg install metasploit
```

Other variants will not work. Even if you fix nokogiri, the last problem will be with ruby's bigdecimal.

**Comment by r4jesh** [comment]
How to fix nokogiri? Please help

**Comment by estridge2011** [comment]
pkg install zlib-dev
bundle install

**Comment by r4jesh** [comment]
Thanks a lot..
