### ISSUE TITLE
32-bit Clang defaults to ARMv4t. 

### ISSUE THREAD

**Issue by easyaspi314** [termux/termux-packages#3686]
Clang for 32-bit defaults to targeting armv4t-linux-android, which doesn't exist (Android needs at least ARMv7 without neon).

If I am not mistaken, doesn't Termux also require ARMv7 + NEON? I notice a lot of NEON code in the binaries, and multiple patches which disable the CPU feature check.

Another issue is that a recent update turned off NEON support with -march=armv7-a, and -mfpu=neon-vfpv4 seems to be required now.

Shouldn't building for the base requirement be the default?

**Comment by its-pointless** [comment]
if i remember correctly the issue here is caused because clang tries to get the native cpu via linux /proc/cpuinfo or something similar so its not the same for everyone. You are right neon is needed. It probably makes sense to use -mfpu=neon  by default and use the same as python etc uses. Since we can assume it works with that.

**Comment by easyaspi314** [comment]
Also make sure it targets `armv7a-linux-androideabi`. Clang assumes `arm` by itself is ARMv4t, which I think is the issue.

**Comment by fornwall** [comment]
This change in an upcoming clang version should probably help here, right? https://reviews.llvm.org/D58153

Perhaps we can backport it while waiting for llvm 9 to be released?

**Comment by its-pointless** [comment]
Making the default target armv7-linux-androideabi is enough. No need to back port.

**Comment by xeffyr** [comment]
I have reverted commit because it introduces https://github.com/termux/termux-packages/issues/4327.

**Comment by xeffyr** [comment]
You can try the https://github.com/termux/termux-packages/pull/4323 yourself by installing clang of specific version (still in apt repository):
```
apt install clang=8.0.1-3 libllvm=8.0.1-3
```

**Comment by Grimler91** [comment]
I am guessing this was fixed in https://github.com/termux/termux-packages/commit/9288ab211fbe276c7d8353bc87ac8c09db9803d6 (or even earlier). Please shout if it is still a problem
