### ISSUE TITLE
g++: exceptions don't work

### ISSUE THREAD

**Issue by espes** [termux/termux-packages#369]
-bash-4.3$ uname -a
    Linux localhost 3.18.20-perf+ #1 SMP PREEMPT Sun Jun 12 22:48:17 CST 2016 aarch64 Android
    -bash-4.3$ apt install g++
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following NEW packages will be installed:
      g++
    0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
    Need to get 504 kB of archives.
    After this operation, 2154 kB of additional disk space will be used.
    Get:1 http://termux.net stable/main aarch64 g++ aarch64 6.1.0-2 [504 kB]
    Fetched 504 kB in 1s (313 kB/s)              
    Selecting previously unselected package g++.
    (Reading database ... 6188 files and directories currently installed.)
    Preparing to unpack .../g++_6.1.0-2_aarch64.deb ...
    Unpacking g++ (6.1.0-2) ...
    Setting up g++ (6.1.0-2) ...
    -bash-4.3$ cat > tst.cpp
    #include <cstdio>
    int main() {
        try {
            throw 1;
        } catch (...) {
            printf("caught\n");
        }
        return 0;    
    }
    -bash-4.3$ g++ tst.cpp 
    -bash-4.3$ ./a.out 
    terminate called after throwing an instance of 'int'
    Aborted

Works as expected with `clang++`

**Comment by fornwall** [comment]
@espes The `gcc` and `g++` packages have been removed and replaced by `clang`, which has official Android support by Google. The `clang` package now sets up `gcc` and `g++` as symlinks to `clang`.

Run

    apt update && apt install clang

to install the clang package (which will replace gcc), or

    apt update && apt dist-upgrade

if you already have both clang and gcc installed (`dist-upgrade` is needed when one package replaces another, which is an unusual event).
