### ISSUE TITLE
Unable to install tigervnc

### ISSUE THREAD

**Issue by Kry9toN** [termux/termux-packages#3690]
after I scan x11-repo and try to install it
```pkg install tigervnc```

Termux replied
```E: Unable to locate package tigervnc```

**Comment by xeffyr** [comment]
As specified in X11-packages [README](https://github.com/termux/x11-packages/blob/master/README.md):
> Important: for now, some packages like tigervnc are unavailable in API-24 repository.

tigervnc is not available for Android 7 (API-24) currently.

**Comment by Chudy66** [comment]
So which VNC can I install in my Android phone since tiger is not available?
