### ISSUE TITLE
upgrade stopped

### ISSUE THREAD

**Issue by imed23001** [termux/termux-packages#3692]
i'am begginer on termux
after  dowloading it
i made: apt update
it worked for me
but when i tried to upgrade termux
"apt upgrade"
the process stopped at progress[94%]
i tried severel time delete and reinstall the app but it gives the same problem.

please help me.

**Comment by xeffyr** [comment]
> the process stopped at progress[94%]

No way to read the message it prints ?
It can only stop if prompts you to confirm whether to install or not newer version of config files.

**Comment by imed23001** [comment]
![Screenshot_2019-04-20-10-31-20-99](https://user-images.githubusercontent.com/49808936/56468638-13312200-6427-11e9-992b-c556351e5bc5.png)

**Comment by xeffyr** [comment]
Okay, seems that you typed "y" at prompt as should be. Now you have purely network problem which is unsolvable on Termux side.

**Comment by blackheat78** [comment]
is there another way to update because I can't update the termux. please help me update only until 94%

**Comment by swarz-dre** [comment]
apt -get update && upgrade not working please help
![Screenshot_20200802-224909](https://user-images.githubusercontent.com/69081079/89133271-85d9ea00-d512-11ea-9dac-3a4d06d38ed1.jpg)

**Comment by xeffyr** [comment]
@swarz-dre What you did so it stopped work? `rm -rf`'ed the $PREFIX/tmp ?
