### ISSUE TITLE
Pkg are not there and cannot install.

### ISSUE THREAD

**Issue by 9990242854** [termux/termux-packages#3694]
when i installing x11-repo pakeges such as "aterm , pypanel ,xterm ,openbox,dosbox,fluxbox they all are not there.
How i connect termux with xsrrver xsdl...

**Comment by xeffyr** [comment]
As mentioned in https://github.com/termux/x11-packages/blob/master/README.md:
> Important: for now, some packages like tigervnc are unavailable in API-24 repository.

Some packages currently are not available for Termux running on Android-7 (or higher).

**Comment by ulist** [comment]
Why ? What the difference

**Comment by xeffyr** [comment]
> What the difference

NDK headers difference.
