### ISSUE TITLE
pip install theano fails 

### ISSUE THREAD

**Issue by nileshpatra** [termux/termux-packages#3699]
**Problem description**
I run into errors when I try to install theano and keras via pip

Log for theano:
![Screenshot_20190422-150805](https://user-images.githubusercontent.com/37436956/56494698-c295f380-6510-11e9-9c9d-36cdbdd71061.jpg)

Log for keras : 
![Screenshot_20190422-151213](https://user-images.githubusercontent.com/37436956/56494786-19033200-6511-11e9-86bd-9ac17b01d024.jpg)

**Steps to reproduce**
Commands : ```pip install theano```  and ```pip install keras```
           
**Expected behavior**
Ideally , should be installed easily

**Comment by Grimler91** [comment]
Looks like the related to bumpy rather than keras/theano. Numpy can't be installed from pip, install it from [its-pointless repo](https://wiki.termux.com/wiki/Installing_Scipy_The_Easy_Way) instead

**Comment by Grimler91** [comment]
You also need to make sure you have clang and python-dev installed, see https://wiki.termux.com/wiki/Instructions_for_installing_python_packages

**Comment by xeffyr** [comment]
> Numpy can't be installed from pip

Installable:
```
[~]:$ pip install numpy
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/93/48/956b9dcdddfcedb1705839280e02cbfeb2861ed5d7f59241210530867d5b/numpy-1.16.3.zip (5.1MB)
    100% |████████████████████████████████| 5.1MB 3.4MB/s 
Installing collected packages: numpy
  Running setup.py install for numpy ... done
Successfully installed numpy-1.16.3
```

And even usable (only few tests failed).

**Comment by xeffyr** [comment]
But scipy will likely to be a problem and it should be installed like described on https://wiki.termux.com/wiki/Installing_Scipy_The_Easy_Way.

**Comment by nileshpatra** [comment]
I installed numpy and scipy and then I could install theano . The keras install however , still throws up error as : 

```
types.h:1822:                                                  /data/data/com.termux/files/usr/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^                                                         In file included from /data/data/com.termux/files/usr/tmp/pip-install-oml3vr28/h5py/h5py/defs.c:637:                  ./h5py/api_compat.h:27:10: fatal error: 'hdf5.h' file not found                                                       #include "hdf5.h"
             ^~~~~~~~                                          1 warning and 1 error generated.                           error: command 'aarch64-linux-android-clang' failed with exit status 1                                                                                                           ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-oml3vr28/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-8b8o60dh/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-oml3vr28/h5py/
```

**Comment by Grimler91** [comment]
@nileshpatra it says "error: file hdf5.h not found". Header files are found on the -dev packages so install libhdf5-dev.

**Comment by nileshpatra** [comment]
Installed , Thanks for your help guys :)
