### ISSUE TITLE
changing default login shell to ZSH fails

### ISSUE THREAD

**Issue by vainikkaj** [termux/termux-packages#37]
Steps to reproduce:
```
chsh -s zsh
/data/data/com.termux/files/usr/bin/zsh is not an executable file!
```

Used version:
```
$ zsh --version
zsh 5.1.1 (arm-unknown-linux-androideabi)
```

**Comment by fornwall** [comment]
Hi, thanks for reporting the issue!

This is probably a problem with the dash shell running on Android 6.0 (the dash shell is used by `chsh`).

Update to the latest dash version `0.5.8-2` with `apt update && apt upgrade` and let me know if it works now or not!

**Comment by vainikkaj** [comment]
Thank you for a quick fix. Works after installing latest dash.

**Comment by LooNeyTKp** [comment]
i'm having this same problem, the above solution doesn't work for me

**Comment by Neo-Oli** [comment]
@looneytkp What error messages do you get?

**Comment by looneytkp** [comment]
```
$ echo $SHELL
/data/data/com.termux/files/usr/bin/bash
$ chsh
Changing the login shell
Enter the new value, or press ENTER for the default
        Login Shell [bash]: zsh
$
```


this is after changing to zsh, so i logout and login to termux

```
$ echo $SHELL

$
```


i get no output after echo $shell, it's still bash. i ignored and tried installing oh-my-zsh but i get this error

```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
grep: /etc/shells: No such file or directory
Zsh is not installed! Please install zsh first!
$
```
apparently i don't have shells file in /etc/shells, i ls the /etc directory and indeed i don't have it
```
$ ls /etc
DxHDCP.cfg
NOTICE.html.gz
acdbdata
apns-conf.xml
audio_platform_info.xml
audio_policy.conf
bluetooth
clatd.conf
compiled-classes
default-permissions
event-log-tags
firmware
flp.conf
fonts.xml
g.prop
gps.conf
hosts
init
init.d
libnfc-brcm-20791b05.conf
libnfc-brcm.conf
media_codecs.xml
media_codecs_google_audio.xml
media_codecs_google_telephony.xml
media_codecs_google_video.xml
media_codecs_performance.xml
media_profiles.xml
mixer_paths.xml
mkshrc
permissions
ppp
preferred-apps
preloaded-classes
public.libraries.txt
qcril.db
sec_config
seccomp_policy
security
selective-spn-conf.xml
sensor_def_hh.conf
spn-conf.xml
sysconfig
thermal-engine-8974.conf
wifi
$
```

**Comment by Neo-Oli** [comment]
Oh-my-zsh can not be installed with the default installation script. See: https://wiki.termux.com/wiki/Shells#Oh-My-ZSH for instructions on how to do it.

**Comment by looneytkp** [comment]
thank you

**Comment by ipod825** [comment]
+1
The SHELL variable is empty after `chsh -s zsh`. The shell did changed, but the environment variable is not set. It maks things that depends on $SHELL (like ranger) fall back to sh.

**Comment by mrbrianhinton** [comment]
Is there a way to fix this issue?

**Comment by Quasic** [comment]
I imagine you could set it in ~/.zshrc

**Comment by sdrausty** [comment]
Have fun https://duckduckgo.com/?q=shell+zsh+site%3Awww.tldp.org and enjoy!

**Comment by im-o** [comment]
simple just use ```chsh -s zsh```

**Comment by clouu27** [comment]
Since no one mentions this, you need to ensure you've allowed Termux "storage access" on settings , since mine didn't pops up this, I had to do it manually on settings > apps > Termux > permissions, then try chsh -s zsh again, works for me.

**Comment by ouzmno** [comment]
> simple just use `chsh -s zsh`
> close and open again.

yes, just like you did
