### ISSUE TITLE
Ngrok not connectig

### ISSUE THREAD

**Issue by Urfander** [termux/termux-packages#3700]
I install ngrok in my termux and i connect to my account with authtoken but when i start in session status a appear "reconnecting (dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:376" and not connect.Someone can tell me what i have to do for ngrok work?Thanks

**Comment by Grimler91** [comment]
Ngrok isn't a termux package so this is off-topic here. You might have more luck in the community channels: https://wiki.termux.com/wiki/Community

**Comment by Jayprakashgiri** [comment]
![Screenshot_2019-12-09-13-50-16-436_com termux](https://user-images.githubusercontent.com/58571828/70420166-16981d00-1a8d-11ea-9c6e-b1e7ae9699e6.jpg)
Not working please help
