### ISSUE TITLE
Privoxy can't start

### ISSUE THREAD

**Issue by phucnx-itsol** [termux/termux-packages#3706]
**Problem description**
After install privoxy with command: apt install privoxy,  
I can't start privoxy via command : `privoxy --no-daemon $PREFIX/etc/privoxy/config`
it's show error :
`2019-04-24 16:34:53.903 7771c44548 Info: Privoxy version 3.0.28`
`2019-04-24 16:34:53.904 7771c44548 Info: Program name: privoxy`
`2019-04-24 16:34:53.970 7771c44548 Fatal error: can't load actions file '/data/data/com.termux/files/usr/etc/privoxy/default.action': line 693: cannot create URL or TAG pattern from: /.*(count|track|compteur|(?<!relo)adframe|adse?rve?|banner)(er|run)?(\?|\.(pl|cgi|exe|dll|asp|php|cpt))`
Check folder /etc/lib/ , can't find libpcreposix.so

**Additional information**
- Termux-info
`Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.120-gd46a6fb #1 SMP PREEMPT Mon Apr 15 06:42:39 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
MI 5s`

- apt show privoxy
`Package: privoxy
Version: 3.0.28-1
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 2171 kB
Depends: pcre, zlib
Homepage: https://www.privoxy.org
Download-Size: 431 kB
APT-Manual-Installed: yes
APT-Sources: https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 Packages
Description: Non-caching web proxy with advanced filtering capabilities`

**Comment by Grimler91** [comment]
Should be fixed in privoxy 3.0.28-2 which is now available, thanks for reporting!
