### ISSUE TITLE
Package request: Aircrack-ng 

### ISSUE THREAD

**Issue by mksincara** [termux/termux-packages#371]
Hi,please add aircrack-ng package for termux! Ita bery great! Thanks 🙏 🙏 🙏

**Comment by Zhu-Zhi-Hao** [comment]
Most Android phone wifi chips don't support wireless monitor mode,  airmon-ng start wlan0 return no thing so it doesn't work ！it means you can't not use Android capture wireless package...

So porting aircrack-ng doesn't make any sense....

**Comment by icebal** [comment]
Unless using a usb OTG cable and a dongle that supports it. But those that need this can always use the kali phone image, or just install the apps it does use.

**Comment by Anty0** [comment]
And what about handshake cracking support ("aircrack-ng" command)? (I have raspberry pi 3 with Kali Linux and on raspberry takes cracking of captured handshake using aircrack and filtered rockyou dictionary ~20 hours. I believe, that on phone it should be faster...)

**Comment by JxM-92** [comment]
But you could make termux to recognise an USB wireless device through OTG and that way use aircrack with that USB device...

**Comment by Ihexon** [comment]
By default Android Kernel configured no support mac80211 drivers，so RTL8192CU or others drivers support mac80211 does'not contain in Android stock kernel，so OTG way use usb devices may also does not well. 

you need recompile and reconfigure kernel，see the wiki on port nethunter...

[Modify the kernel](https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel)
