### ISSUE TITLE
lolcat

### ISSUE THREAD

**Issue by IrfanAhmad91** [termux/termux-packages#3710]
I want to try to make my thermux look cooler but why do I want to save the word "No command 'lolcat' found, did you mean: Command 'logcat' from package 'termux-tools'
  Command 'logcat' from package 'termux-tools'
 No command 'lolcat' found, did you mean:
  Command 'logcat' from package 'termux-tools'
  Command 'logcat' from package 'termux-tools' please fix this bug I once used lolcat but why did it come up? "

**Comment by xeffyr** [comment]
Installable with `gem` from ruby package.

**Comment by IrfanAhmad91** [comment]
please teach me how to install it

**Comment by Satyrcore** [comment]
$ gem install lolcat

Ruby is needed prior to command

**Comment by IrfanAhmad91** [comment]
Thanks sir it's working 👍
