### ISSUE TITLE
MariaDB : Error initializing mysql data directory

### ISSUE THREAD

**Issue by hugorosario** [termux/termux-packages#3713]
**Problem description**
The postinstall of MariaDB fails at "Initializing mysql data directory..." with the following error :

> Initializing mysql data directory...
> chown: unknown user xeffyr
> Cannot change ownership of the database directories to the 'xeffyr'
> user.  Check that you have the necessary permissions and try again.

If I run mysql_install_db without any arguments, the script is executed successfully and the data directory is initialized correctly.

**Steps to reproduce**
Just install the package using pkg :

> $ pkg install mariadb

(Please note that if MariaDB was previously installed, you should remove the folder  **$PREFIX/var/lib/mysql** before installing again)

**Expected behavior**
I think the package should install with the current user returned by the **whoami** command, which in my case is '**u0_a336**', but for some reason it is trying to use "xeffyr".

**Additional information**
Here is the full transcript:

> $ pkg install mariadb
> Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
> Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
> Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
> Get:4 https://dl.bintray.com/termux/termux-packages-24 stable Release [6061 B]
> Hit:4 https://dl.bintray.com/termux/termux-packages-24 stable Release
> Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
> Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
> Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
> Hit:7 https://dl.bintray.com/grimler/science-packages-24 science Release
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> 1 package can be upgraded. Run 'apt list --upgradable' to see it.
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following NEW packages will be installed:
>   mariadb
> 0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
> Need to get 14.9 MB of archives.
> After this operation, 167 MB of additional disk space will be used.
> Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 mariadb aarch64 10.3.14-1 [14.9 MB]
> Fetched 14.9 MB in 1s (9511 kB/s)
> Selecting previously unselected package mariadb.
> (Reading database ... 2455 files and directories currently installed.)
> Preparing to unpack .../mariadb_10.3.14-1_aarch64.deb ...
> Unpacking mariadb (10.3.14-1) ...
> Setting up mariadb (10.3.14-1) ...
> Initializing mysql data directory...
> chown: unknown user xeffyr
> Cannot change ownership of the database directories to the 'xeffyr'
> user.  Check that you have the necessary permissions and try again.

**Comment by xeffyr** [comment]
> chown: unknown user xeffyr
Cannot change ownership of the database directories to the 'xeffyr'

?

**Comment by hugorosario** [comment]
Thank you very much and congratulations on what you are all doing here.
Termux is an amazing project.

**Comment by hugorosario** [comment]
Just tested version 10.3.14-2 of the package and it is now installing properly.
Thank you.
