### ISSUE TITLE
antiword

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-packages#3716]
convert microsoft word file to html/text.

Name            : antiword
Version         : 0.37-7
Description     : A free MS Word reader for Linux and RISC OS
URL             : http://www.winfield.demon.nl/

**Comment by xeffyr** [comment]
Duplicate of https://github.com/termux/unstable-packages/issues/58

**Comment by xeffyr** [comment]
```
pkg install unstable-repo
pkg install antiword
```
