### ISSUE TITLE
Tsu package error

### ISSUE THREAD

**Issue by rendiix** [termux/termux-packages#3717]
![Screenshot_2019-04-26-13-03-43-346_com termux](https://user-images.githubusercontent.com/16639978/56786881-afdb3180-6824-11e9-82f3-aa8ba3a25b2e.png)

**Comment by xeffyr** [comment]
Likely because `tsu` uses bashisms but shebang points to dash.

Information from shellcheck:
```
In tsu line 128:
      if (( "16400" <= "$MAG32"  && "$MAG32" < "18200" )); then
         ^-- SC2039: In POSIX sh, standalone ((..)) is undefined.
```
@cswl

**Comment by cswl** [comment]
Yeah arithmetic test is bashim.. will fix
