### ISSUE TITLE
apt upgrade (or pkg upgrade)

### ISSUE THREAD

**Issue by Exaltat1on** [termux/termux-packages#3724]
After apt upgrade, progress stop at 94%, after reboot termux, apt and other not working

Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ apt update && apt upgrade
Hit:1 https://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
15 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  game-repo science-repo termux-keyring
The following packages will be upgraded:
  apt bash busybox ca-certificates dpkg gpgv
  libbz2 libc++ libcurl libgpg-error libnghttp2
  ncurses openssl readline termux-tools
15 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 3362 kB of archives.
After this operation, 225 kB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 https://termux.net stable/main all ca-certificates all 20190124 [120 kB]
Get:2 https://termux.net stable/main aarch64 openssl aarch64 1.1.1b-3 [907 kB]
Get:3 https://termux.net stable/main aarch64 libnghttp2 aarch64 1.38.0 [41.7 kB]
Get:4 https://termux.net stable/main aarch64 libcurl aarch64 7.64.1-1 [153 kB]
Get:5 https://termux.net stable/main aarch64 busybox aarch64 1.30.1-1 [277 kB]
Get:6 https://termux.net stable/main aarch64 dpkg aarch64 1.19.4-1 [186 kB]
Get:7 https://termux.net stable/main aarch64 libbz2 aarch64 1.0.6-2 [23.4 kB]
Get:8 https://termux.net stable/main aarch64 libgpg-error aarch64 1.36 [62.6 kB]
Get:9 https://termux.net stable/main aarch64 gpgv aarch64 2.2.15-1 [137 kB]
Get:10 https://termux.net stable/main aarch64 libc++ aarch64 19b [195 kB]
Get:11 https://termux.net stable/main aarch64 apt aarch64 1.4.9-3 [653 kB]
Get:12 https://termux.net stable/main aarch64 ncurses aarch64 6.1.20181117-1 [111 kB]
Get:13 https://termux.net stable/main aarch64 readline aarch64 8.0 [88.3 kB]
Get:14 https://termux.net stable/main aarch64 bash aarch64 5.0.7 [376 kB]
Get:15 https://termux.net stable/main all termux-tools all 0.65 [4382 B]
Get:16 https://termux.net stable/main all termux-keyring all 1.1 [24.2 kB]
Get:17 https://termux.net stable/main all game-repo all 1.0 [958 B]
Get:18 https://termux.net stable/main all science-repo all 1.0 [968 B]
Fetched 3362 kB in 1s (3089 kB/s)
(Reading database ... 4955 files and directories currently installed.)
Preparing to unpack .../ca-certificates_20190124_all.deb ...
Unpacking ca-certificates (20190124) over (20181205) ...
Setting up ca-certificates (20190124) ...
(Reading database ... 4955 files and directories currently installed.)
Preparing to unpack .../openssl_1.1.1b-3_aarch64.deb ...
Unpacking openssl (1.1.1b-3) over (1.1.1a) ...
Setting up openssl (1.1.1b-3) ...
(Reading database ... 4956 files and directories currently installed.)
Preparing to unpack .../libnghttp2_1.38.0_aarch64.deb ...
Unpacking libnghttp2 (1.38.0) over (1.36.0) ...
Setting up libnghttp2 (1.38.0) ...
(Reading database ... 4956 files and directories currently installed.)
Preparing to unpack .../libcurl_7.64.1-1_aarch64.deb ...
Unpacking libcurl (7.64.1-1) over (7.63.0) ...
Setting up libcurl (7.64.1-1) ...
(Reading database ... 4957 files and directories currently installed.)
Preparing to unpack .../busybox_1.30.1-1_aarch64.deb ...
Unpacking busybox (1.30.1-1) over (1.29.3-1) ...
Setting up busybox (1.30.1-1) ...
(Reading database ... 4957 files and directories currently installed.)
Preparing to unpack .../dpkg_1.19.4-1_aarch64.deb ...
Unpacking dpkg (1.19.4-1) over (1.19.2) ...
Setting up dpkg (1.19.4-1) ...
(Reading database ... 4957 files and directories currently installed.)
Preparing to unpack .../libbz2_1.0.6-2_aarch64.deb ...
Unpacking libbz2 (1.0.6-2) over (1.0.6-1) ...
Setting up libbz2 (1.0.6-2) ...
(Reading database ... 4957 files and directories currently installed.)
Preparing to unpack .../libgpg-error_1.36_aarch64.deb ...
Unpacking libgpg-error (1.36) over (1.34) ...
Setting up libgpg-error (1.36) ...
(Reading database ... 4957 files and directories currently installed.)
Preparing to unpack .../gpgv_2.2.15-1_aarch64.deb ...
Unpacking gpgv (2.2.15-1) over (2.2.12) ...
Setting up gpgv (2.2.15-1) ...
(Reading database ... 4957 files and directories currently installed.)
Preparing to unpack .../libc++_19b_aarch64.deb ...
Unpacking libc++ (19b) over (18) ...
Setting up libc++ (19b) ...
(Reading database ... 4957 files and directories currently installed.)
Preparing to unpack .../apt_1.4.9-3_aarch64.deb ...
Unpacking apt (1.4.9-3) over (1.4.8-9) ...
Setting up apt (1.4.9-3) ...
(Reading database ... 4957 files and directories currently installed.)
Preparing to unpack .../ncurses_6.1.20181117-1_aarch64.deb ...
Unpacking ncurses (6.1.20181117-1) over (6.1.20181117) ...
Setting up ncurses (6.1.20181117-1) ...
(Reading database ... 4949 files and directories currently installed.)
Preparing to unpack .../bash_5.0.7_aarch64.deb ...
Unpacking bash (5.0.7) over (4.4.23-3) ...
Preparing to unpack .../readline_8.0_aarch64.deb ...
Unpacking readline (8.0) over (7.0.5-2) ...
Setting up readline (8.0) ...
(Reading database ... 4952 files and directories currently installed.)
Preparing to unpack .../termux-tools_0.65_all.deb ...
Unpacking termux-tools (0.65) over (0.60) ...
Setting up termux-tools (0.65) ...

Configuration file '/data/data/com.termux/files/usr/etc/motd'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** motd (Y/I/N/O/D/Z) [default=N] ? y
y
Installing new version of config file /data/data/com.termux/files/usr/etc/motd ...
Selecting previously unselected package termux-keyring.
(Reading database ... 4952 files and directories currently installed.)
Preparing to unpack .../termux-keyring_1.1_all.deb ...
Unpacking termux-keyring (1.1) ...
Selecting previously unselected package game-repo.
Preparing to unpack .../archives/game-repo_1.0_all.deb ...
Unpacking game-repo (1.0) ...
Selecting previously unselected package science-repo.
Preparing to unpack .../science-repo_1.0_all.deb ...
Unpacking science-repo (1.0) ...
Setting up termux-keyring (1.1) ...
Setting up bash (5.0.7) ...
Setting up science-repo (1.0) ...
Downloading updated package list ...
0% [Working]
Progress: [ 94%] [##########################..]

**Comment by xeffyr** [comment]
Seems like it stuck on retrieving package lists from additional repositories. You have purely networking problem and this cannot be solved from Termux's side.

You can try VPN as workaround.

**Comment by Exaltat1on** [comment]
VPN don't helping, also i try mobile internet(not wi-fi) and have this problem

**Comment by xeffyr** [comment]
Last thing you can try is to force IPv4 connections for APT:

Create file `$PREFIX/etc/apt/apt.conf.d/00-force-ipv4` and put following content:
```
Acquire::ForceIPv4 "true";
```

**Comment by Exaltat1on** [comment]
apt update
E: Opening configuration file /data/data/com.termux/files/usr/etc/apt/apt.conf.d/00-force-ipv4 - ifstream::ifstream (13: Permission denied)

**Comment by xeffyr** [comment]
Do not use root explorer to edit files because you will mess up permissions and SElinux labels.
There many other ways how to insert line into such file without root.

**Comment by Exaltat1on** [comment]
I fix permission, but apt upgrade stay at 94%.

**Comment by rhyzq** [comment]
I have same problem, but when i upgrade using apt-get with forcing Ipv4 it run well
But it stuck when i use pkg command

**Comment by xeffyr** [comment]
> illegal instructions

@rhyzq If CPU of your device doesn't support NEON instructions, you can't use Termux.

**Comment by remo7777** [comment]
unpacking problem

**Comment by ipongmonarchy** [comment]
![Screenshot_2019-06-23-17-50-31-72](https://user-images.githubusercontent.com/51818923/59975206-a29db180-95df-11e9-9f95-d02fd8e5feef.png)
![Screenshot_2019-06-23-17-50-31-72](https://user-images.githubusercontent.com/51818923/59975208-b0533700-95df-11e9-8c8b-79e4657701c3.png)
why is this not working and still 0 working Can anyone help me

**Comment by raprocks** [comment]
Same problem with me it suddenly did that was working fine yesterday

**Comment by inderjeet68g** [comment]
Not installing in my rooted mi note 8 pro
