### ISSUE TITLE
Still can't use C++ stdlib

### ISSUE THREAD

**Issue by Waces** [termux/termux-packages#3726]
I've searched many Issues, tried a lot of things from the replies and still don't get how to use std stuff in C++

as trying to compile
```
#include <iostream>
int main(){
    std::cout << "anything" << '\n';
}
```
will result in
```
test.cpp:1:10: fatal error: 'iostream' file not found
```
tried clang++ and g++ with and without the libc++ option

if there is a thread that actually solved it I unfortunately couldn't find it :P

**Comment by xeffyr** [comment]
No idea what should be done to make Clang non-working.
```
$ nano test.cpp
$ clang++ test.cpp
$ ./a.out
anything
```

**Comment by Waces** [comment]
this response literally had no intellectual value somehow

**Comment by xeffyr** [comment]
> this response literally had no intellectual value somehow

Much less intellectually is to not provide *steps to reproduce*...

**Comment by Waces** [comment]
The steps are right there, just make a .cpp file that has ```#include <iostream>``` and try to compile it with clang++ or g++, any of these will give ```FILENAME.cpp:1:10: fatal error: 'iostream' file not found```

**Comment by xeffyr** [comment]
**Not reproducible.**

```
$ nano test.cpp
$ clang++ test.cpp
$ ./a.out
anything
```
```
$ cat test.cpp
#include <iostream>
int main(){
    std::cout << "anything" << '\n';
}
```

**Comment by Grimler91** [comment]
iostream is in the ndk-sysroot package. Clang depends on libllvm which depends on ndk-sysroot so it shouldn't be possible to have clang++ but not the iostream header. 

Have you searched for the file in $PREFIX? 
Which architecture are you on? 
What's the output of `termux-info`?
Have you tried to reinstall ndk-sysroot?

**Comment by xeffyr** [comment]
@Grimler91 It seems either like messing with $PREFIX or passing some additional flags to compiler. But as I wrote above, on normal installation everything okay, at least on AArch64 and ARM.

> Have you tried to reinstall ndk-sysroot?

`clang` probably should be reinstalled too.

**Comment by Grimler91** [comment]
Just want to make sure that i686, x86_64 or the android-5 pkgs aren't broken somehow
