### ISSUE TITLE
irssi on termux

### ISSUE THREAD

**Issue by coderandy** [termux/termux-packages#3732]
CANNOT LINK EXECUTABLE "irssi": library "libutf8proc.so.2" not found
Aborted

**Comment by coderandy** [comment]
![Screenshot_2019-04-29-22-09-13](https://user-images.githubusercontent.com/1799040/56902168-42e9c500-6acc-11e9-9345-b257c2499be3.jpg)

**Comment by Grimler91** [comment]
`pkg install utf8proc` fixes it. I'll add it to irssi's dependencies
