### ISSUE TITLE
[Package Request] PyGame

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [termux/termux-packages#3736]
**Package description**
I'm able to run PyGame programs in a browser window thanks to PySimpleGUIWeb, which runs on Termux.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?

When I try to install on Android using Termux, I get errors that a development version of SDL is required.

**Comment by Atavic** [comment]
Link to GH page: https://github.com/pygame/pygame

**Comment by MikeTheWatchGuy** [comment]
I would be happy to leave an issue with them.

Is there something in particular I should ask them for?  

I'm able to run Remi and PySimpleGUIWeb on Termux now, which is pretty exciting to see.

I was able to do this using termux and PySimpleGUIWeb:
![PSG On Android](https://user-images.githubusercontent.com/13696193/56870573-8fa3a200-69df-11e9-8013-5cd353b4c0a2.gif)

It's a start.

**Comment by xeffyr** [comment]
Unfortunately, we do not package python modules.

> I get errors that a development version of SDL is required.

Such version of SDL exists in [x11-packages](https://github.com/termux/x11-packages) repository.

**Comment by MikeTheWatchGuy** [comment]
Oh..... I see now (I think).  Package Request means something different in this case.  It's not a Python Package you're talking about.

Not sure if I need OpenGL since I'm outputting the PyGame output to a web page, accessible through a browser.

**Comment by AbdullahBinJahed** [comment]
uhhh ... pygame works though ? here's a screenshot ...
![Screenshot_2021-09-07-00-18-45-322_com realvnc viewer android](https://user-images.githubusercontent.com/39275638/132252064-21700c6a-a411-4152-a8f5-8b8323f5cf0a.jpg)
