### ISSUE TITLE
Android SDK does not install

### ISSUE THREAD

**Issue by ciaranodc** [termux/termux-packages#3739]
When I run the setup-android-sdk.sh script it prints the following and stops:

```
$ ./setup-android-sdk.sh 
Downloading android sdk...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  147M  100  147M    0     0  1542k      0  0:01:37  0:01:37 --:--:-- 1466k
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
```
The checksum in the script (92ffee5a1d98d856634e8b71132e8a95d96c83a63fde1099be3d86df3106def9) does seem to match the one on the website here:
https://developer.android.com/studio

Not sure what the issue is. Can anyone help or suggest a workaround?

**Comment by Grimler91** [comment]
It works fine for me, and the checksum on https://developer.android.com/studio#downloads is 92ffee5a1d98d856634e8b71132e8a95d96c83a63fde1099be3d86df3106def9 for sdk-tools-linux-433796.zip. 

Have you tried it a second time?

**Comment by jaredtlove** [comment]
I
Have a newer version of studio I'm updating microsoft stuff on laptop right now and then I'll check it out. 
Sent from Yahoo Mail on Android 
 
  On Tue, Apr 30, 2019 at 9:26 AM, Henrik Grimler<notifications@github.com> wrote:   
It works fine for me, and the checksum on https://developer.android.com/studio#downloads is 92ffee5a1d98d856634e8b71132e8a95d96c83a63fde1099be3d86df3106def9 for sdk-tools-linux-433796.zip.

Have you tried it a second time?

**Comment by xeffyr** [comment]
```
Downloading android sdk...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  147M  100  147M    0     0  25.6M      0  0:00:05  0:00:05 --:--:-- 30.7M
tools.zip: OK
Downloading android ndk...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  785M  100  785M    0     0  27.2M      0  0:00:28  0:00:28 --:--:-- 28.5M
ndk.zip: OK
Warning: File /home/xeffyr/.android/repositories.cfg could not be loaded.       
5 of 5 SDK package licenses not accepted. 100% Computing updates...             
Review licenses that have not been accepted (y/N)
```

Everything fine with downloading, if you didn't changed anything in setup scripts.
