### ISSUE TITLE
PHP cannot locate symbol pcre2_code_free_8 when opcache is enabled

### ISSUE THREAD

**Issue by Kleinschmidts** [termux/termux-packages#3741]
There has been already some issues regarding this #2232, #2234, but still i get the following error:
`php -n -dzend_extension=opcache.so
PHP Warning:  Failed loading Zend extension 'opcache.so'
(tried: /data/data/com.termux/files/usr/lib/php/opcache.so
(dlopen failed: cannot locate symbol "pcre2_code_free_8" referenced by
"/data/data/com.termux/files/usr/lib/php/opcache.so"...), /data/data/com.termux/files/usr/lib/php/opcache.so.so (dlopen failed: library "/data/data/com.termux/files/usr/lib/php/opcache.so.so" not found)) in Unknown on line 0`

Is this expected to work?
I use the packages
`php/stable,now 7.3.4-2 arm [installed]
php-apache/stable,now 7.3.4-2 arm [installed]
php-dev/stable,now 7.3.4-2 arm [installed]
php-fpm/stable,now 7.3.4-2 arm [installed]
pcre/stable,now 8.43 arm [installed,automatic]
pcre-dev/stable 8.43 arm
pcre2/stable,now 10.33 arm [installed,automatic]
pcre2-dev/stable,now 10.33 arm [installed]
`

**Comment by Grimler91** [comment]
What's your output of `termux-info`?

**Comment by Kleinschmidts** [comment]
sorry for bad format (don't get newline to work with "insert code")
u0_a65@localhost:/data/data/com.termux/files/usr/etc/apache2$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.4.112-Lineage-ge8d93e0 #1 SMP PREEMPT Sat Jan 12 14:54:25 UTC 2019 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.2
Device manufacturer:
samsung
Device model:
GT-I9505

**Comment by fornwall** [comment]
@Kleinschmidts Thanks for reporting - this should be fixed in version `7.3.6-1` of the php package, update to it with `pkg up`!

**Comment by Kleinschmidts** [comment]
Thank you very much, it works and i think i see a quite noticeable performance improvement.
