### ISSUE TITLE
E: Unable to locate package ...

### ISSUE THREAD

**Issue by Mohammad-GIV** [termux/termux-packages#3742]
Cannot install packages such as pip, rsa and many more.
When i want to install a new package i recive an error with this text:
E: Unable to locate package (package name)
Im tried with/without vpn with 4 different ISPs and nothing happened.
Im using termux on LG G2 running on android 5.0.2
Also reinstalling/rebooting/clear data not worked.
Please help.

**Comment by xeffyr** [comment]
> Please help.

No steps to reproduce (you didn't specified which package tried to install) => no help.

**Comment by xeffyr** [comment]
> Cannot install packages such as pip, rsa and many more.

btw, pip is part of `python`.

**Comment by Mohammad-GIV** [comment]
It worked.
But other packages continued receiving given error.
For example i need rsa, paes and... 
What should i do?

**Comment by xeffyr** [comment]
>  i need rsa, paes

1. rsa
```
pip install rsa
```

2. paes. I don't know if paes exists, but p**y**aes can be installed with:
```
pip install pyaes
```

> What should i do?

In short - read the instructions for such packages and try to install them in way their authors suggest. Or at least determine package type and install it with appropriate package manager, in your case **pip** and not 'pkg' or 'apt'.

**Comment by 1111drt** [comment]
How to exicuit metasploit frame work when itry to insall it shows apt-get install metasploit-framewor
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package metasploit-framewor
root@localhost:~# apt-get install metasmetasploit-framework
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package metasmetasploit-framework

**Comment by remo7777** [comment]
just check 
apt-get update
apt-get search metasploit

if it is present that package, then you can install

**Comment by 1111drt** [comment]
It sayes this apt-get search metasploit
E: Invalid operation search
$
