### ISSUE TITLE
SSH restarts on screen off/on

### ISSUE THREAD

**Issue by AravK** [termux/termux-packages#375]
I'm using ssh to connect to my Raspberry Pi.
I'm playing music (omxplayer), but if I switch my screen off with omxplayer running, after 2 seconds(ish) the music stops & I get:
Read from remote host <port>: Connection refused
Connection to <port> closed.
I then have to ssh in again.
Why is this happening? I think ssh switches off when I switch the screen off. Please fix this.

**Comment by Neo-Oli** [comment]
Does this also happen when you put Termux in Wakelock mode?
To do this: Two finger swipe the notification and press "WAKE".
Or perhaps your Phone cuts out your Wifi connection (for power saving reasons) -> Advanced Wifi Settings->Keep Wi-Fi on during sleep.
There is also the Wifi lock which could help in this case.

**Comment by AravK** [comment]
Thanks a lot!!!
