### ISSUE TITLE
MariaDB [MySQL]: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/data/data/com.termux/files/usr/tmp/mysqld.sock' (2)

### ISSUE THREAD

**Issue by bobby-kun** [termux/termux-packages#3750]
Everytime I execute mysql this error always pop up (
Errror 2002 (HY000): Can't connect to local MySQL server through socket '/data/data/com.termux/files/usr/tmp/mysqld.sock' (2))
I tried using the recommended solution from a github user by creating my.cnf.d directory and executing mysqld_safe_install and mysqld_safe -u root & but still the problem will repeat repeat once I close the terminal. Any work arounds?

**Comment by xeffyr** [comment]
You haven't started mysql server. Execute something like
```
mysqld_safe
```
and only then try `mysql`.

**Comment by rawagent09** [comment]
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/data/data/com.termux/files/usr/tmp/mysqld.sock' (2)

**Comment by xeffyr** [comment]
@rawagent09 Ensure that server is running before trying to connect ;)

**Comment by tan86** [comment]
> You haven't started mysql server. Execute something like
> 
> ```
> mysqld_safe
> ```
> 
> and only then try `mysql`.

In New Session mysqld_safe
Then try in first session mysql

**Comment by Adarsh-achu** [comment]
> You haven't started mysql server. Execute something like
> 
> ```
> mysqld_safe
> ```
> 
> and only then try `mysql`.

but do we need to execute each time

**Comment by Adarsh-achu** [comment]
iam on remux

**Comment by xeffyr** [comment]
> but do we need to execute each time

Before using client, you need to ensure that server is running, right? If mysqld_safe is not running, you need to start it.

**Comment by Pebrianz** [comment]
if mysqld_safe cannot be run.  try with mysqld

**Comment by SharakPL** [comment]
@xeffyr how? I do everything by the book and it still doesn't work ☹️ Worked once right after installation of mariadb, but after termux restarts it suddenly doesn't work anymore. I run `mysqld_safe -u root &`, looks ok but then `mysql` returns 
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/data/data/com.termux/files/usr/tmp/mysqld.sock' (2)

Would you please create some tutorial on using mysql in Termux and maybe how to manage services since `service` is not available? Pleaseeee 🙏🙏🙏

I haven't used Termux for over a year and I could swear it was easier before.

**Comment by xeffyr** [comment]
> I do everything by the book

I don't think there are right books about Termux exist somewhere. The only valid "book" is Termux Wiki.

Regarding MariaDB, read this article: https://wiki.termux.com/wiki/MariaDB. Carefully. And remember that Termux is not a normal Linux distribution. In fact, it neither a Linux distribution nor clean Android OS userspace. Commands copy-pasted from books will not work here.

**Comment by Adarsh-achu** [comment]
> @xeffyr how? I do everything by the book and it still doesn't work ☹️ Worked once right after installation of mariadb, but after termux restarts it suddenly doesn't work anymore. I run `mysqld_safe -u root &`, looks ok but then `mysql` returns 
> > ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/data/data/com.termux/files/usr/tmp/mysqld.sock' (2)
> 
> Would you please create some tutorial on using mysql in Termux and maybe how to manage services since `service` is not available? Pleeeease 🙏🙏🙏
> 
> I haven't used Termux for over a year and I could swear it was easier before. 

**Bro what do you need
**

**Comment by SharakPL** [comment]
@Adarsh-achu never mind ;) I think I've figured out sane way to manage mysql: 
1. `pkg install mariadb`
2.  added couple aliases to **.zshrc**:
```
alias sqlstart="mysqld_safe -u root &"
alias sqlstop="mysqladmin shutdown"
```
3. `sqlstart` to start the server, `mysql` to use it, `sqlstop` to stop it

Sometimes, for no apparent reason, I get this _Can't connect..._ error on running `mysql`, but `sqlstop` and `sqlstart` helps (life is so much easier when you actually know what to do 😂)

I've also managed to configure my server properly for utf8mb4 support:
1. `pkg install mlocate` and then `updatedb` for faster search
2. `locate my.cnf` and changed this one .../files/usr/etc/my.cnf
2.

**Comment by SharakPL** [comment]
@Adarsh-achu never mind ;) I think I've figured out sane way to manage mysql: 
1. `pkg install mariadb`
2.  added couple aliases to **.zshrc**:
```
alias sqlstart="mysqld_safe -u root &"
alias sqlstop="mysqladmin shutdown"
```
3. `sqlstart` to start the server, `mysql` to use it, `sqlstop` to stop it

Sometimes, for no apparent reason, I get this _Can't connect..._ error on running `mysql`, but `sqlstop` and `sqlstart` helps (life is so much easier when you actually know what to do 😂)

I've also managed to configure my server properly for utf8mb4 support:
1. `pkg install mlocate` and then `updatedb` for faster search
2. `locate 'my.cnf'` and changed this one **.../files/usr/etc/my.cnf** so it now looks like this:

```
#
# This group is read both by the client and the server
# use it for options that affect everything
#

[client]
default-character-set=utf8mb4

[mysql]
default-character-set=utf8mb4

[mysqld]
collation-server = utf8mb4_unicode_ci
init-connect='SET NAMES utf8mb4'
character-set-server = utf8mb4

#
# include *.cnf from the config directory
#
!includedir /data/data/com.termux/files/usr/etc/my.cnf.d
```

**Comment by Kuduxaaa** [comment]
First you kill mysqld process to re run mysqld
```
$ pkill mysqld
$ mysqld
```
