### ISSUE TITLE
Package Request for exiv2

### ISSUE THREAD

**Issue by DottieUnderwood** [termux/termux-packages#3752]
**Package description**
Exiv2 is a Cross-platform C++ library and a command line utility to manage image metadata. It provides fast and easy read and write access to the Exif, IPTC and XMP metadata and the ICC Profile embedded within digital images in various formats. Exiv2 is available as free software and is used in many projects including KDE and Gnome Desktops as well as many applications including GIMP, darktable, shotwell, GwenView and Luminance HDR. 

**Link to home page and sources**
1. Home page: https://www.exiv2.org/
2. Source code: https://www.exiv2.org/download.html

**Additional information**
The Exiv2 command line utility will be very usefull to process the metadata of the images created with the smartphone camera.

**Comment by xeffyr** [comment]
```
pkg install unstable-repo
pkg install exiv2
```
