### ISSUE TITLE
About termux unsafe

### ISSUE THREAD

**Issue by Sourabhjhaji** [termux/termux-packages#3755]
After installing termux in my device it shown me two icon first is termux and second is termux(unsafe). So I am quite worried about it that why it is seen me unsafe. So can you please solve this problem. My android version is 7.0 and please guide me how can I remove second termux unsafe icon.

**Comment by Grimler91** [comment]
It says "failsafe", not "unsafe". That icon is there to allow you to restore a broke environment (which can for example happen If you mess with your ~/.bashrc file, for example by putting `exit 0` in it). You can't remove the second icon. It was added in 0.67: https://github.com/termux/termux-app/releases/tag/v0.67
