### ISSUE TITLE
valgrind does not working on Android Pie

### ISSUE THREAD

**Issue by landfillbaby** [termux/termux-packages#3756]
**Problem description**
(i'm not sure where the fault is here: could be valgrind, termux, google, or samsung)
valgrind gives a cascade of warnings about `/system/bin/linker64`, then finally an `unsupported clone() flags` error, no matter what program is run. this wasn't a problem before i updated my phone to android 9 pie.

**Steps to reproduce**
`valgrind ls`

**Expected behavior**
a report of `ls`'s memory deallocation

**Additional information**
example valgrind output: [valgrind.txt](https://github.com/termux/termux-packages/files/3145408/valgrind.txt)
see also https://github.com/termux/termux-packages/issues/3221#issuecomment-485350347 (?)

<details><summary>termux-info</summary>

    Updatable packages:
    All packages up to date
    Subscribed repositories:
    https://dl.bintray.com/termux/termux-packages-24 stable/main
    System information:
    Linux localhost 4.4.111-15529922 #1 SMP PREEMPT Wed Mar 13 15:22:15 KST 2019 aarch64 
    Android
    Termux-packages arch:
    aarch64
    Android version:
    9
    Device manufacturer:
    samsung
    Device model:
    SM-A530F
</details>

**Comment by xeffyr** [comment]
Most likely SELinux problem and not valgrind's.

**Comment by landfillbaby** [comment]
related? https://bugs.kde.org/show_bug.cgi?id=386427

**Comment by its-pointless** [comment]
> related? https://bugs.kde.org/show_bug.cgi?id=386427

yes 
its still not working though. it just hangs instead of crashes

**Comment by Hax4us** [comment]
Same issue on my pie

**Comment by landfillbaby** [comment]
hey it's fixed!!

**Comment by landfillbaby** [comment]
not sure but maybe those other 2 issues can be closed too?
