### ISSUE TITLE
'-y' and '-n' switches on 'pkg' command

### ISSUE THREAD

**Issue by metaspook** [termux/termux-packages#3758]
**Problem description**
Please add '-y' and '-n' switches like apt-get in 'pkg' command it will be helpful to process installation, upgrade etc without asking... I hope you'll understand what I'm trying to pointing out here. Please add this to 'pkg' command.

**Comment by xeffyr** [comment]
Since *pkg* is alias for *apt*, it accepts same arguments as *apt*.
For example: `pkg install -y package_name` will work in same way as `apt update && apt install -y package_name`.

**Comment by metaspook** [comment]
> Since _pkg_ is alias for _apt_, it accepts same arguments as _apt_.
> For example: `pkg install -y package_name` will work in same way as `apt update && apt install -y package_name`.

What is this then? 
[![Screenshot-20190507-020629-01.jpg](https://i.postimg.cc/zXK3tXcs/Screenshot-20190507-020629-01.jpg)](https://postimg.cc/jLqsCKKc)

**Comment by metaspook** [comment]
@xeffyr 
And see '-y' switche working for 'apt' not for 'pkg' but u saying 'pkg' is aliase of 'apt' and you closed my issue without judging..
[![Screenshot-20190507-021426-01.jpg](https://i.postimg.cc/bwRx5R5f/Screenshot-20190507-021426-01.jpg)](https://postimg.cc/75fJGSDK)

**Comment by xeffyr** [comment]
Only `pkg upgrade` was affected and it should be fixed now.
