### ISSUE TITLE
Termux: installation of matplotlib failed

### ISSUE THREAD

**Issue by Sirdpol** [termux/termux-packages#3761]
I tried to install "matplotlib" for python 3 using termux after running
 > pip install matplotlib 
but returned the error
 "ERROR: Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-mLXJ0T/pandas"

Please help out

**Comment by Grimler91** [comment]
You are probably missing some dependency. Impossible to know which one without seeing the full error message. Read the error and install the header files (-dev packages) for missing dependencies.
See also https://wiki.termux.com/wiki/Instructions_for_installing_python_packages

**Comment by akhilporandla21041998** [comment]
ERROR: Complete output from command /data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-0dzbyt44/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-ss2fox39/install-record.txt --single-version-externally-managed --compile:
    ERROR: ================================================================================
    Edit setup.cfg to change the build options                  
    BUILDING MATPLOTLIB                                               matplotlib: yes [3.1.0]
          python: yes [3.7.3 (default, Jun 28 2019, 18:43:05)  [Clang 8.0.7
                      (https://android.googlesource.com/toolchain/clang
                      b55f2d4ebfd35bf6]                                 platform: yes [linux]
                                                                    OPTIONAL SUBPACKAGES
     sample_data: yes [installing]                                         tests: no  [skipping due to configuration]
                                                                    OPTIONAL BACKEND EXTENSIONS
             agg: yes [installing]                                         tkagg: yes [installing; run-time loading from Python Tcl/Tk]                                                                   macosx: no  [Mac OS-X only]
                                                                    OPTIONAL PACKAGE DATA
            dlls: no  [skipping due to configuration]



/lib.linux-aarch64-3.7/matplotlib/mpl-data/images
    copying lib/matplotlib/mpl-data/images/forward_large.gif -> build/lib.linux-aarch64-3.7/matplotlib/mpl-data/images              UPDATING build/lib.linux-aarch64-3.7/matplotlib/_version.py
    set build/lib.linux-aarch64-3.7/matplotlib/_version.py to '3.1.0'                                                               running build_ext                                               building 'matplotlib.ft2font' extension
    creating build/temp.linux-aarch64-3.7                           creating build/temp.linux-aarch64-3.7/src
    aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Oz -Oz -fPIC -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -Iextern/agg24-svn/include -I/data/data/com.termux/files/usr/lib/python3.7/site-packages/numpy-1.16.3-py3.7-linux-aarch64.egg/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.7m -c src/checkdep_freetype2.c -o build/temp.linux-aarch64-3.7/src/checkdep_freetype2.o
    src/checkdep_freetype2.c:1:10: fatal error: 'ft2build.h' file not found                                                         #include <ft2build.h>                                                    ^~~~~~~~~~~~
    1 error generated.                                              error: command 'aarch64-linux-android-clang' failed with exit status 1
    ----------------------------------------                    ERROR: Command "/data/data/com.termux/files/usr/bin/python -u

ERROR: Command "/data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-0dzbyt44/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-ss2fox39/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-0dzbyt44/matplotlib/

**Comment by akhilporandla21041998** [comment]
ERROR: Complete output from command /data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-0dzbyt44/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-ss2fox39/install-record.txt --single-version-externally-managed --compile:
    ERROR: ================================================================================
    Edit setup.cfg to change the build options                  
    BUILDING MATPLOTLIB                                               matplotlib: yes [3.1.0]
          python: yes [3.7.3 (default, Jun 28 2019, 18:43:05)  [Clang 8.0.7
                      (https://android.googlesource.com/toolchain/clang
                      b55f2d4ebfd35bf6]                                 platform: yes [linux]
                                                                    OPTIONAL SUBPACKAGES
     sample_data: yes [installing]                                         tests: no  [skipping due to configuration]
                                                                    OPTIONAL BACKEND EXTENSIONS
             agg: yes [installing]                                         tkagg: yes [installing; run-time loading from Python Tcl/Tk]                                                                   macosx: no  [Mac OS-X only]
                                                                    OPTIONAL PACKAGE DATA
            dlls: no  [skipping due to configuration]



/lib.linux-aarch64-3.7/matplotlib/mpl-data/images
    copying lib/matplotlib/mpl-data/images/forward_large.gif -> build/lib.linux-aarch64-3.7/matplotlib/mpl-data/images              UPDATING build/lib.linux-aarch64-3.7/matplotlib/_version.py
    set build/lib.linux-aarch64-3.7/matplotlib/_version.py to '3.1.0'                                                               running build_ext                                               building 'matplotlib.ft2font' extension
    creating build/temp.linux-aarch64-3.7                           creating build/temp.linux-aarch64-3.7/src
    aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Oz -Oz -fPIC -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -Iextern/agg24-svn/include -I/data/data/com.termux/files/usr/lib/python3.7/site-packages/numpy-1.16.3-py3.7-linux-aarch64.egg/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.7m -c src/checkdep_freetype2.c -o build/temp.linux-aarch64-3.7/src/checkdep_freetype2.o
    src/checkdep_freetype2.c:1:10: fatal error: 'ft2build.h' file not found                                                         #include <ft2build.h>                                                    ^~~~~~~~~~~~
    1 error generated.                                              error: command 'aarch64-linux-android-clang' failed with exit status 1
    ----------------------------------------                    ERROR: Command "/data/data/com.termux/files/usr/bin/python -u

ERROR: Command "/data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-0dzbyt44/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-ss2fox39/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-0dzbyt44/matplotlib/

**Comment by akhilporandla21041998** [comment]
Iam getting the above code as error message while installing matplotlib iny termux so please try to solve this issue and help me in this regard

**Comment by ortylp** [comment]
steps to reproduce:

install/clean termux

apt update
apt install clang python python-dev fftw libzmq libzmq-dev freetype freetype-dev libpng libpng-dev pkg-config
LDFLAGS=" -lm -lcompiler_rt" pip install numpy matplotlib pandas jupyter
