### ISSUE TITLE
conflict between libiconv-dev and linux-man-pages

### ISSUE THREAD

**Issue by valpogus** [termux/termux-packages#3764]
**Problem description**
There is a conflict in the files provided by the packages libiconv-dev and linux-man-pages

**Steps to reproduce**
apt update
apt -y upgrade
apt -y install libiconv-dev
apt -y install linux-man-pages

**Expected behavior**
linux-man-pages installed

**Actual behavior**
... 
Preparing to unpack .../linux-man-pages_4.16_all.deb ...
Unpacking linux-man-pages (4.16) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/linux-man-pages_4.16_all.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/share/man/man3/iconv_open.3.gz', which is also in package libiconv-dev 1.15-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/linux-man-pages_4.16_all.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by xeffyr** [comment]
Fixed in `linux-man-pages` v4.16-2.
