### ISSUE TITLE
Package request: Mumble Server

### ISSUE THREAD

**Issue by Serkan-devel** [termux/termux-packages#3766]
**Package description**
Mumble is a FOSS voicechat platform which one can self-host

**Link to home page and sources**
1. Home page: https://www.mumble.com/
2. Source code: https://github.com/mumble-voip/mumble

**Additional information**
I haven't tried to compile it yet but someone asked about it at https://github.com/mumble-voip/mumble/issues/3668

**Comment by JackalZhao** [comment]
+1

**Comment by xtkoba** [comment]
`mumble-server` (a.k.a. `murmur`) depends on Qt5, even without the client build. So the package has to go to the `x11` repo.
