### ISSUE TITLE
mutt email view html on firefox browser

### ISSUE THREAD

**Issue by erji44** [termux/termux-packages#3767]
I'm trying to open the html mails on mutt with termux-open-url but so far to no avail.
On linux I do the following:
.mailcap file content:
text/html; firefox '%s' >/dev/null 2>&1; test=test -n "$DISPLAY"; needsterminal

Then when viewing an email on mutt, pressing v will bring up the html part and when selected it will open the url with firefox.
Any ideas on how to get termux-open-url call firefox and open html emails.

Thank you

**Comment by xeffyr** [comment]
Firefox isn't available for Termux.

**Comment by xeffyr** [comment]
Is `termux-open-url` working at all for you ?

**Comment by xeffyr** [comment]
`termux-open-url` doesn't work for local (file://) urls.

**Comment by erji44** [comment]
OK, thanks for the answer.
termux-open-url work fine to open urls, it calls firefox(or other default browser) and opens the url.
Is there a way round this?
I'd like to be able to open html file attachments on mutt from local browser installed on android.
I can get them to open with elinks but it's not good enough.

**Comment by xeffyr** [comment]
You should use `termux-open` instead of `termux-open-url`.
Example command:
```
termux-open --content-type 'text/html' /path/to/file.html
```

**Comment by erji44** [comment]
I've been trying all possible options with this, it starts the browser but then browser says:
content://com.termux.files/path/to/file.html
Address was not understood.
Any suggestions?
Thanks

**Comment by xeffyr** [comment]
Html files opened through `termux-open` displayed correctly in Firefox:

1. `termux-open` command:
<img src="https://user-images.githubusercontent.com/25881154/57250518-493deb00-7050-11e9-9153-abf7f3fa0f88.jpg" width="400px">

2. Firefox:
<img src="https://user-images.githubusercontent.com/25881154/57250752-da14c680-7050-11e9-94b5-97745d8c3c89.jpg" width="400px">

**Comment by Limero** [comment]
How do I make mutt open html automatically with `termux-open` from the `v` menu?

**Comment by kontsevoy** [comment]
@Limero while in the `v` menu, select the HTML MIME part and hit `m`.
