### ISSUE TITLE
bug report - std::sto*  in g++

### ISSUE THREAD

**Issue by jaiselrahman** [termux/termux-packages#377]
First of all, Thank you for this great app 
It is helps me greatly for learning programmings

I found that when compiling this c++ code using g++

``` c++
    #include<iostream>
    #include<string>
    using namespace std;
    int main()                                     
    {                    
        string s="566";                       
        int i;
        i=stol(s); 
        cout<<i;                             
        cout<<'\n'<<stod("937");
        cout<<'\n'<<to_string(239.399);
        return 0;
  } 
```

the compiler throws error

> stoi.cpp: In function 'int main()':
> stoi.cpp:10:11: error: 'stol' was not declared in this scope
> i=stol(s);
>              ^
> stoi.cpp:12:25: error: 'stod' was not declared in this scope
> cout<<'\n'<<stod("937");
>                         ^
> stoi.cpp:13:32: error: 'to_string' was not declared in this scope
> cout<<'\n'<<to_string(239.399);
>                              ^

my compiler version is 6.1.0

**Comment by fornwall** [comment]
This is a bug in the Android NDK (which Termux is based on): https://github.com/android-ndk/ndk/issues/82

It is scheduled to be resolved in the next release (r13) of the NDK, at which time the fix will propagate to Termux as a package update!

**Comment by jaiselrahman** [comment]
thanks

i found that adding these to above headers fixes the problem (temporarily)

```c++
    #define _GLIBCXX_HAVE_WCSTOF 1
    #define _GLIBCXX_USE_C99 1
```
Again thanks for this awesome app

**Comment by fornwall** [comment]
Unfortunately the progress on the NDK side has been slower than expected. However, according to [the NDK roadmap](https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md), the next release (r15) states:

    With this project finished, libc++ will be safe to use

If it works ok, the plan is to switch to libc++ in Termux when r15 of the NDK is available. This will bring us a modern C++ library fixing these and other issues.

[The NDK release schedule](https://github.com/android-ndk/ndk/wiki) currently has r15 marked for release during `Late May/Early June 2017`.

**Comment by Exaeta** [comment]
@fornwall Can we get the beta version? This is stopping me from compiling software I want to try to use on android...

**Comment by fornwall** [comment]
Termux has just switched to libc++, so after updating packages things such as `std::to_string`, `std::stod` and friends should start working!

Note that C++ programs and libraries should be rebuilt completely, as Termux now links against libc++ by default, and you don't want to mix STL implementations in the same program.
