### ISSUE TITLE
confused between normal user and root user mode.

### ISSUE THREAD

**Issue by shownb** [termux/termux-packages#3783]
**Problem description**
what i want to do is ssh to android device via usb in rndis mode.
i connected the android device to pc with usb,and choosed the rndis mode.
so i tried in my linux pc:
```
ifconfig usb0 10.42.0.1 netmask 255.255.255.0
```
in my android device Termux terminal
```
tsudo ifconfig rndis0 10.42.0.2 netmask 255.255.255.0
```
now i can ping each other.it works good. it worked fine only in the root stituation.(tsu su tsudo)
when i used the u0_a91 user,it said: 
connect:Network is unreachable.
it seems like that there are two worlds between u0_a91 and root.

in root mode i run the sshd,and from pc ,i can ssh to android,but not matter how to chanage the u0_a91's password,i cannot login in. 

the termux is newest
**Additional information**
apt update
apt upgrade

thanks.

**Comment by Grimler91** [comment]
Perhaps not really an answer to your question (I'm clueless about rndis) but have a look at this guide for how to ssh over usb if you haven't seen it already: https://glow.li/technology/2016/9/20/access-termux-via-usb/

**Comment by xeffyr** [comment]
> i connected the android device to pc with usb,and choosed the rndis mode.

RNDIS mode is actually *USB tethering*. Just open Android settings => Connections => Mobile hotspot and Tethering and check "USB tethering".

Everything will be configured manually. There also will be DHCP running on device's side.

> it seems like that there are two worlds between u0_a91 and root.

Android's network subsystem is complicated:

* Android has pre-configured iptables.

* Only users with `inet` group can access the Internet.

**Comment by shownb** [comment]
@xeffyr your method worked.thank you very much.
@Grimler91 i think your method also can work.thank you all the same.
