### ISSUE TITLE
vim / vim-runtime circular dependency, can't install vim-python (bintray)

### ISSUE THREAD

**Issue by landfillbaby** [termux/termux-packages#3784]
**Problem description**
using the bintray repo (aarch64), can't update vim-python, and trying to instead uninstalls it, due to vim-runtime depending on vim since the most recent update?

**Steps to reproduce**
`pkg install vim-python`
`apt depends 'vim*'`

**Comment by xeffyr** [comment]
Should be fixed in vim-runtime >=8.1.1300-2.
