### ISSUE TITLE
Apt list error

### ISSUE THREAD

**Issue by kkrishna7638** [termux/termux-packages#3790]
u0_a195@localhost ~> apt list
CANNOT LINK EXECUTABLE "apt": "/data/data/com.termux/files/usr/lib/libz.so.1.2.11" is 64-bit instead of 32-bit
fish: 'apt list' terminated by signal SIGABRT (Abort)

I can't update and upgrade any package 
same issue in mpd command also .

**Comment by Grimler91** [comment]
How did you manage this? Did you restore a 64 bit installation to a 32 bit device?

Try reinstalling the app.

**Comment by ulist** [comment]
K

**Comment by kkrishna7638** [comment]
I tried but when I restore our old backup with tar.i face same issue

**Comment by kkrishna7638** [comment]
Finally I solved it by reinstalling the termux and this time, I did not take backup.and install all important packages .I have to lost our old packages and files or some settings,

**Comment by shubham5912** [comment]
CANNOT LINK EXECUTABLE "./ettercap": "/data/data/com.termux/files/usr/lib/libz.so.1.2.11" is 64-bit instead of 32-bit                                                   #


How to solve thes help

**Comment by kcubeterm** [comment]
In my case , my old phone has 32 bit processor and i just backuped all termux data with tar, and extract it in 64 bit new phone, you know 32 bit library and executable can't run on 64 bit without helping any emulator.thats why error occurred.
