### ISSUE TITLE
Discord bot making package (Termux should also have it's own discord)

### ISSUE THREAD

**Issue by GreatZardasht** [termux/termux-packages#3796]
This package should be needed because Thier are lots of people who are discord and want to make a robot so termux should make a package to make a discord bot and I think termux should have it's own discord it will be useful to report bugs and all that

**Comment by xeffyr** [comment]
> I think termux should have it's own discord it will be useful to report bugs

The only useful thing to report/track bugs is Github Issues.

**Comment by pollen5** [comment]
what do you exactly mean by a discord bot making package, Discord has a websocket and rest api that is being wrapped with libraries for various languages, it isn't a single package, you install the programming language you wanna use in termux and the libraries for it. A Termux discord server would be cool, not for bug reports but for general chatting.
