### ISSUE TITLE
vim dose not have python support

### ISSUE THREAD

**Issue by iamcco** [termux/termux-packages#38]
```
:echo has('python')   " result 0
```
many plugin need vim compiled with +python/python3

**Comment by fornwall** [comment]
Hi, there is a separate package named `vim-python` for vim compiled with python3 support. Does it work for you?

**Comment by iamcco** [comment]
@fornwall it works well !! cool

**Comment by sae13** [comment]
@fornwall Hi I am noob, how I can activate vim-python in vim ?

**Comment by xeffyr** [comment]
@sae13, `pkg install vim-python`
