### ISSUE TITLE
Cross-Compiling with Clang to other android archs?

### ISSUE THREAD

**Issue by pollen5** [termux/termux-packages#3804]
Now that it is possible to build Android apps on Termux itself (with tools like ecj, dx, aapt etc) but its just plain java there, i could write C/C++ code but it would be only for the current host, not portable, is it anyhow possible to have clang toolchain for other android archs? (i.e running aarch64-linux-android-clang on an ARM device)

**Comment by xeffyr** [comment]
> anyhow possible to have clang toolchain for other android archs?

Clang is cross-compiler out-of-box.
You just need sysroot for the needed architecture only.

**Comment by pollen5** [comment]
where do i get that? I tried running
```sh
clang main.c -target aarch64-linux-android
```
and got
```
/data/data/com.termux/files/usr/bin/ld: unrecognised emulation mode: aarch64linux
Supported emulations: armelf_linux_eabi armelfb_linux_eabi
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by xeffyr** [comment]
You have to use linker provided by LLVM. See package `lld`.

**Comment by pollen5** [comment]
I installed lld and ran clang with `-fuse-ld=lld` and got
```
$ clang main.c -fuse-ld=lld -target aarch64-linux-android
ld.lld: error: unable to find library -ldl
ld.lld: error: unable to find library -ldl
ld.lld: error: unable to find library -lc
ld.lld: error: unable to find library -ldl
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```
My guess is that i need those libraries compiled for the target, but do you have any ideas where i could find them?

**Comment by tomty89** [comment]
The Android NDK.

**Comment by TheBrokenRail** [comment]
The NDK does not run on Android, or even ARM for that matter.

**Comment by xeffyr** [comment]
> The NDK does not run on Android, or even ARM for that matter.

Runs, https://github.com/android-ide/aide_ndk/releases/download/v20160121/android-ndk-aide-linux-arm-20160121.tar.bz2.

But NDK is not need, only sysroot to obtain libs for specific architecture.

**Comment by pollen5** [comment]
A'ight @xeffyr let's get this issue closed asap, final question is where do i get the sysroot for other archs?

**Comment by tomty89** [comment]
As I said, the Android NDK. We have ndk-multilib but it's kind of outdated and incomplete anyway.

**Comment by tomty89** [comment]
Take a look at these files, they might help:
https://github.com/termux/termux-packages/blob/master/packages/ndk-sysroot/build.sh
https://github.com/termux/termux-packages/blob/master/packages/ndk-multilib/build.sh

**Comment by tomty89** [comment]
FWIW, ndk-multilib is particularly incomplete when you are cross-compiling for aarch64 on arm. As unlike on aarch64, you don't get both /system/lib64 and /system/lib.

Also you probably need to replace the crt*.o files in $PREFIX/lib anyway (instead of just having ndk-multilib installed). I don't know if things have changed though.

**Comment by xeffyr** [comment]
In case if cross-compiling from AArch64 to ARM, no need to have complete sysroot or copy crt files somewhere. Just `clang`, `ndk-multilib` and `lld`.
```
~ $ clang -fuse-ld=lld main.c
~ $ file a.out
a.out: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, not stripped
~ $ clang --target=armv7-linux-androideabi -fuse-ld=lld main.c
~ $ file a.out
a.out: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, not stripped
```

To compile from ARM/AArch64 to i686 you really need sysroot. Particulary you need the lib directory as Termux clang won't be handle NDK sysroot anyway.

I have replaced the ndk-multilib's `$PREFIX/i686-linux-android/lib`
```
~ $ ls $HOME/sysroot/usr/lib/i686-linux-android/24
crtbegin_dynamic.o  crtend_android.o  libGLESv1_CM.so  libOpenMAXAL.so  libc++.a   libc.so                  libdl.a            liblog.so  libmediandk.so  libvulkan.so
crtbegin_so.o       crtend_so.o       libGLESv2.so     libOpenSLES.so   libc++.so  libcamera2ndk.so         libdl.so           libm.a     libstdc++.a     libz.a
crtbegin_static.o   libEGL.so         libGLESv3.so     libandroid.so    libc.a     libcompiler_rt-extras.a  libjnigraphics.so  libm.so    libstdc++.so    libz.so
~ $ ls -ld $PREFIX/i686-linux-android/lib
lrwxrwxrwx 1 u0_a86 u0_a86 70 Sep  9 19:53 /data/data/com.termux/files/usr/i686-linux-android/lib -> /data/data/com.termux/files/home/sysroot/usr/lib/i686-linux-android/24
```
and now can compile from AArch64 to i686:
```
~ $ clang --target=i686-linux-android -fuse-ld=lld main.c
~ $ file a.out
a.out: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, not stripped
```

**Comment by pollen5** [comment]
@xeffyr aight thanks, also why not package the bare minimum libs needed in ndk-multilib (libc and libdl)?

**Comment by xeffyr** [comment]
Done in https://github.com/termux/termux-packages/commit/fbc8e9e397dcfcb0fe23279d2b92a23edc7eae2e.

**Comment by pollen5** [comment]
@xeffyr didn't work for me
```
pollen@localhost ~/c> gcc main.c -target aarch64-linux-android -fuse-ld=lld
ld.lld: error: unable to find library -ldl
ld.lld: error: unable to find library -ldl
ld.lld: error: unable to find library -lc
ld.lld: error: unable to find library -ldl
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
pollen@localhost ~/c> ls $PREFIX/aarch64-linux-android/lib
crtbegin_dynamic.o  libatomic.a        libc.a     liblog.so*
crtbegin_so.o       libc++_shared.a    libc.so*   libm.a
crtbegin_static.o   libc++_shared.so*  libdl.a    libm.so*
crtend_android.o    libc++_static.a    libdl.so*
crtend_so.o         libc++abi.a        libgcc.a
pollen@localhost ~/c>
```

**Comment by xeffyr** [comment]
> -target aarch64-linux-android

Target can't be used in this way.

**Comment by pollen5** [comment]
@xeffyr Im on Android 9 ARM, and `--target=aarch64-linux-android` gave same results.

**Comment by xeffyr** [comment]
**Latest** NDK multilib installed ?

**Comment by pollen5** [comment]
Yep just installed it a few minutes ago

**Comment by xeffyr** [comment]
What is your `termux-info` ?

**Comment by pollen5** [comment]
```
System information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Fri Apr 19 13:20:06 CST 2019 armv8l Android
Termux-packages arch:
arm
Android version:
9
Device manufacturer:
HUAWEI
Device model:
AMN-LX9
```

**Comment by xeffyr** [comment]
Why repository info truncated from top ?

**Comment by pollen5** [comment]
You mean this? 
```
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
```
removed top parts cause of the not updated packages, thought you only needed the system info.

**Comment by xeffyr** [comment]
> cause of the not updated packages,

Not updated packages leading to various issues including not working clang cross compilation.

**Comment by pollen5** [comment]
@xeffyr well, that was the issue, updated clang, llvm and lld and it works like a charm now
