### ISSUE TITLE
msfconsole error on termux

### ISSUE THREAD

**Issue by shaheem007** [termux/termux-packages#3814]
[*] Please Wait While Binding ...

/data/data/com.termux/files/home/hackapk/hackapk: line 319: cd: /data/data/com.termux/files/home/metasploit-framework: Not a directory
/data/data/com.termux/files/home/hackapk/hackapk: line 320: ./msfvenom: No such file or directory

[*] Signing Payloaded Apk ...
mv: cannot stat '/data/data/com.termux/files/home/hackapk/unsigned/output.apk': No such file or directory
java.io.FileNotFoundException: /data/data/com.termux/files/home/hackapk/unsigned/tubemate.apk (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.jar.JarFile.<init>(JarFile.java:154)
        at java.util.jar.JarFile.<init>(JarFile.java:133)
        at com.android.signapk.SignApk.main(SignApk.java:949)
rm: cannot remove '/data/data/com.termux/files/home/hackapk/unsigned/tubemate.apk': No such file or directory
rm: cannot remove '/data/data/com.termux/files/home/metasploit-framework/tubemate-3-3-2-5.apk': Not a directory

[*] Successfully Generated Payload In The Apk.

[*] Payloaded Apk Stored In 'final' Directory.

**Comment by shaheem007** [comment]
i use this to install to metasploit 
pkg install unstable-repo
pkg install metasploit

**Comment by 0xXA** [comment]
Purge and try reinstalling

**Comment by Grimler91** [comment]
This doesn't seem to be termux specific (seems you are trying to use outdated scripts), and this isn't a metasploit repo so closing as off topic

**Comment by xeffyr** [comment]
> /data/data/com.termux/files/home/hackapk/hackapk: line 319: cd: /data/data/com.termux/files/home/metasploit-framework: Not a directory

hackapk script requires a lot of fixing...
Metasploit is no longer installed to $HOME but into `$PREFIX/opt`.
