### ISSUE TITLE
how to bind apk on termux 

### ISSUE THREAD

**Issue by shaheem007** [termux/termux-packages#3815]
im using  pkg install unstable-repo
pkg install metasploit

i cant find a tool to bind apk

**Comment by shaheem007** [comment]
most of the tools say cant find metasploit framework

**Comment by shaheem007** [comment]
dont get angry becuz im a noob

**Comment by xeffyr** [comment]
> most of the tools say cant find metasploit framework

Because:

* You didn't use them properly.

* Tools are adapted specially for their author.

* Tools are poorly written or not portable.

**Comment by xeffyr** [comment]
Ask about these tools on relevant repositories and not there.
