### ISSUE TITLE
libjpeg-dev package

### ISSUE THREAD

**Issue by Arxk** [termux/termux-packages#382]
If I try to install Pillow, an image manipulation application with the command:

LDFLAGS="-L/system/lib/" pip2 install Pillow

I get the following error:

"... ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting"

I think it is because the package libjpeg-dev is missing and it can be installed from the repo.

**Comment by fornwall** [comment]
Could you try installing `libjpeg-turbo-dev` and see if that works?

**Comment by Arxk** [comment]
It works now. Thank you

**Comment by S4QL4IN** [comment]
android@localhost :~ pkg install libjpeg-turbo-dev
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libjpeg-turbo-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libjpeg-turbo

E: Package 'libjpeg-turbo-dev' has no installation candidate
