### ISSUE TITLE
Question: SQLite3 static binary with readline support

### ISSUE THREAD

**Issue by tcmaps** [termux/termux-packages#3828]
Hi,

Could someone here guide me to recompile the sqlite3 package as static binary? I need it outside of the termux context and this seems to be the only version sucessfully including readline support.

Thx!

**Comment by xeffyr** [comment]
1. You need to setup a build environment like described on https://github.com/termux/termux-packages/blob/master/docs/DOCKER.md. *On-device termux-packages builds are not supported !*

2. Apply the following patch on local clone of repository 'termux-packages': [0001-sqlite3-static-build.patch.txt](https://github.com/termux/termux-packages/files/3195116/0001-sqlite3-static-build.patch.txt)
    ```ShellSession
    wget https://github.com/termux/termux-packages/files/3195116/0001-sqlite3-static-build.patch.txt
    git apply 0001-sqlite3-static-build.patch.txt
    ```

3. Build package "libsqlite":
    ```ShellSession
    ./scripts/run-docker.sh
    ./build-package.sh -a ${your_architecture} libsqlite
    ```
    Replace `${your_architecture}` with appropriate value from: `aarch64`, `arm`, `i686`, `x86_64`.

4. Get your binary at path `/data/data/com.termux/files/usr/bin/sqlite3` or from deb package in `./debs`.
