### ISSUE TITLE
Ls command in termux is not wirking

### ISSUE THREAD

**Issue by dantheguyd** [termux/termux-packages#3829]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by dantheguyd** [comment]
i had no description to put so i didnt touch the  describtion

**Comment by xeffyr** [comment]
> Ls command in termux is not wirking

Any description about **how it is not working** ?

**Comment by dantheguyd** [comment]
And by wirking i mean working

**Comment by xeffyr** [comment]
`ls` from both coreutils and busybox working.
