### ISSUE TITLE
mktexfmt problem: can't find file dehypht-x-2019-04-04.tex

### ISSUE THREAD

**Issue by smaslovski** [termux/termux-packages#3831]
**Problem description**

After installing texlive-latexrecommended with all the dependences I tried compiling a simple latex source file (see below). The compilation fails due to a failure of mktexfmt when creating the latex format file. Here is what I got:

$ latex test.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Termux) (preloaded format=latex)
 restricted \write18 enabled.

kpathsea: Running mktexfmt latex.fmt
mktexfmt: mktexfmt is using the following fmtutil.cnf files (in precedence order):
mktexfmt:   /data/data/com.termux/files/usr/share/texlive/texmf-dist/web2c/fmtutil.cnf
mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
mktexfmt:   /data/data/com.termux/files/home/.texlive2019/texmf-config/web2c/fmtutil.cnf
mktexfmt [INFO]: writing formats under /data/data/com.termux/files/home/.texlive2019/texmf-var/web2c
mktexfmt [INFO]: --- remaking latex with pdftex
mktexfmt: running `pdftex -ini   -jobname=latex -progname=latex -translate-file=cp227.tcx *latex.ini'
.....
.....
.....

===========================================
Local configuration file hyphen.cfg used
===========================================

(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/generic/babel/hyp
hen.cfg
(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/generic/babel/swi
tch.def)
(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/generic/hyphen/hy
phen.tex)
(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/generic/hyphen/du
myhyph.tex)
(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/generic/hyphen/ze
rohyph.tex)
! I can't find file `dehypht-x-2019-04-04.tex'.
<to be read again>
                   \relax
l.172   \repeat

(Press Enter to retry, or Control-D to exit)
Please type another input file name:
! Emergency stop.
<to be read again>
                   \relax
l.172   \repeat

No pages of output.
Transcript written on latex.log.
mktexfmt [ERROR]: running `pdftex -ini   -jobname=latex -progname=latex -translate-file=cp227.tcx *latex.ini >&2 </dev/null' return status 1
mktexfmt [ERROR]: return error due to options --strict
mktexfmt [INFO]: Disabled formats: 7
mktexfmt [INFO]: Not selected formats: 43
mktexfmt [INFO]: Failed to build: 1 (pdftex/latex)
mktexfmt [INFO]: Total formats: 51
mktexfmt [INFO]: exiting with status 1
I can't find the format file `latex.fmt'!

*Steps to reproduce**

1. On a fresh installation of Termux install texlive-latexrecommended.
2. Try compiling the following latex source (or any other)

\documentclass{article}

\title{Check latex}

\author{First Second}

\begin{document}

\maketitle

Here I try to type a few sentences in \LaTeX.

$$ x^2+y^2 = z^2$$

The end.

\end{document}

**Expected behavior**

Latex format generated OK; latex source compiled OK.

**Additional information**
Post output of command `termux-info`.

$ termux-info
Updatable packages:
ncurses/stable 6.1.20190511-1 aarch64 [upgradable from: 6.1.20181117-5]
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/termux-root-packages-24 root/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.71-15759240 #1 SMP PREEMPT Thu Apr 4 14:01:51 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-T820

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by Grimler91** [comment]
Why are you opening duplicate issues? #3830

**Comment by smaslovski** [comment]
Sorry, my mistake! I reported this initially by mistake to the x11 repo, but then I realized that, and reported here now. However, I did not notice that you already closed the bug.

**Comment by smaslovski** [comment]
By the way, it seems you closed it without fixing.
