### ISSUE TITLE
When i install openssl and done, my termux dont be used. If, i install a package always stuck 0% 

### ISSUE THREAD

**Issue by MrWhoopy** [termux/termux-packages#3834]
First i try to install git and done
![Screenshot_2019-05-20-05-36-21-88](https://user-images.githubusercontent.com/50809885/57989353-baa38200-7ac3-11e9-90bb-88f91378fe25.png)
 

Next i try to install openssl and done 
![Screenshot_2019-05-20-05-36-43-34](https://user-images.githubusercontent.com/50809885/57989358-d9a21400-7ac3-11e9-9f99-4cd051696018.png)

But, next them i try to install package always eror 
![Screenshot_2019-05-20-05-37-05-20](https://user-images.githubusercontent.com/50809885/57989370-0bb37600-7ac4-11e9-8595-c2eb9f0e2d72.png)

 I need help. 
Thanks

**Comment by xeffyr** [comment]
Post output of `cat /proc/cpuinfo`.

**Comment by xeffyr** [comment]
In any case, if your device's CPU doesn't support NEON instructions you won't be able to use Termux.
There no workarounds.
