### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-g894Rt/pandas/

### ISSUE THREAD

**Issue by yasins20** [termux/termux-packages#3836]
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-g894Rt/pandas/ how to fix pls help :/
![Screenshot_20190520-184242~2](https://user-images.githubusercontent.com/50838989/58034992-7b5f4a80-7b30-11e9-9ebb-e5b383404571.png)

**Comment by Grimler91** [comment]
Impossible to know what's wrong without seeing the full error message

**Comment by yasins20** [comment]
@grimler91 how can I show all the

**Comment by Grimler91** [comment]
As I said, it is impossible for us to know if you don't show the full error message. You are missing some dependency.
