### ISSUE TITLE
Odd- Termux rejects one key character..

### ISSUE THREAD

**Issue by fieldlab** [termux/termux-packages#3837]
Very weird. I've only had Termux installed a few weeks and it's worked flawlessly. Android 6.0 on HTC one M9 with plenty of memory. I ran ffprobe a couple of times and now the lower case 'a' is rejected. I just get a long buzz like a standard error. 

Keyboard type doesn't matter. Didn't happen in other apps. Still happens after restarting phone. Long pressing the key, or shift, ctrl, etc. work fine. Plain lower case 'a'? Rejected.

Get this- pasting a lower case a from the clipboard is also rejected! Weird.

Now, if I swipe a word with an 'a' in it, the word appears except for the 'a's which are simply missing. Same thing happens when pasting a word or text with 'a's.

Looks like I'll have to try reinstalling Termux next.

**Comment by xeffyr** [comment]
> I've only had Termux installed a few weeks and it's worked flawlessly.
I ran ffprobe a couple of times and now the lower case 'a' is rejected.

So problem started to happen only after executing `ffprobe` ?

**Comment by Ariswandi255** [comment]
sit report lol I'm Bingung

**Comment by fieldlab** [comment]
I had run ffprobe before so I think it was coincidence.

**Comment by fieldlab** [comment]
I tried deleting the small cache in the app manager. No effect. Now the larger data store should go, around 700 mb. Backed up my configs first.

**Comment by fieldlab** [comment]
That fixed it, but was equivalent to a reinstall. It warned all files and data would be deleted. When restarting the Termux app, a brief "installing" notification appeared.

**Comment by Ariswandi255** [comment]
your lock I'm Scren Shot Scrip Not Work.
text file download I Don't understand Command Scrip first I'm Done
Reinstall &Handpone Restart

Pada tanggal Sel, 21 Mei 2019 22.57, fieldlab <notifications@github.com>
menulis:

**Comment by xeffyr** [comment]
I have no problems with `ffprobe`, at least it doesn't cause effect you described here. Also, I'm suggesting to try click on button "reset" in context menu - terminal state can be messed up if received some binary output or certain escape sequences and should be reset by user in these cases.
