### ISSUE TITLE
Php error cannot locate iconv

### ISSUE THREAD

**Issue by oskcrisz** [termux/termux-packages#3838]
![Screenshot_2019-05-21-08-53-16](https://user-images.githubusercontent.com/50778287/58066158-c58d0e00-7bba-11e9-9f1b-4560376fd93a.png)

**Comment by oskcrisz** [comment]
What the problem of this?

**Comment by tomty89** [comment]
Probably because php on the binary repo is not up-to-date.

**Comment by oskcrisz** [comment]
How can i update?

**Comment by tomty89** [comment]
I think the question is when will @fornwall be free to build it.

**Comment by oskcrisz** [comment]
@fornwall may i know what is the problem or there is some code?

**Comment by Dsya** [comment]
We have same issues with php..???

**Comment by Zulf135** [comment]
I have same issue just like that here ...
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"...
page record for 0xb643502c was not found (block_size=16)

**Comment by its-pointless** [comment]
php just needs to be recompiled

**Comment by Zulf135** [comment]
If you are right, its-pointless.
Then, How to do that?
Previously it works normally without do nothing, all you have to do just install and boom.

**Comment by Jamsa** [comment]
CANNOT LINK EXECUTABLE "mysql": cannot locate symbol "iconv_open" referenced by "/data/data/com.termux/files/usr/bin/mysql"...

**Comment by renaldiap** [comment]
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"...

Help me please

**Comment by AntoniusVip** [comment]
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"...
page record for 0x7fb08ab010 was not found (block_size=16)

**Comment by fornwall** [comment]
This has now been fixed - run `pkg up` to update.

Thanks for reporting!

**Comment by renaldiap** [comment]
@fornwall thank you very much ... I can run my php again

**Comment by Zulf135** [comment]
Thank You Mr. Fredrick 😁
Since PHP is my language i very need it in Termux to study
