### ISSUE TITLE
er

### ISSUE THREAD

**Issue by Ariswandi255** [termux/termux-packages#3839]
![Screenshot_2019-05-21-15-57-03-27](https://user-images.githubusercontent.com/48797472/58095390-1d4c6900-7bfd-11e9-9b8c-94f47940ef21.png)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
> er

I don't see any "er" on your screenshot.
