### ISSUE TITLE
"Method https has died unexpectedly!" In asus Z00LD

### ISSUE THREAD

**Issue by chezzEnt** [termux/termux-packages#3840]
After i run pkg install pip there is a line called " The default action is to keep the current version" then i press Y then the endless 0%[working] started everytime i install through pkg i got stuck here also when doing a apt update, so I tried to uninstall then install the termux and this always happens...
Example:
$ apt update
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
$

**Comment by xeffyr** [comment]
If device's CPU doesn't support NEON instructions, then no way to use Termux.
