### ISSUE TITLE
I try download termux and cant be used, i try to solve issues, but i cant solve it, i need help please

### ISSUE THREAD

**Issue by MrWhoopy** [termux/termux-packages#3841]
Frist i apt upgrade
BOOM error all 
![Screenshot_2019-05-21-21-41-27-66](https://user-images.githubusercontent.com/50809885/58107514-37de0c80-7c14-11e9-8c32-209f257e9084.png)

**Comment by xeffyr** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/3834.
Also **wontfix**.

**Comment by xeffyr** [comment]
If device doesn't support NEON instructions, then **no way to use Termux** !!!
