### ISSUE TITLE
Install error in device oppo a37f

### ISSUE THREAD

**Issue by max140218** [termux/termux-packages#3843]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

This is why the error when you want to install Python or something else must be written below:
pkg install python
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by xeffyr** [comment]
Post output of `cat /proc/cpuinfo` here.

**Comment by xeffyr** [comment]
Same as for https://github.com/termux/termux-packages/issues/3841 - Termux requires that ARM/AArch64 CPUs have support for NEON instructions.
