### ISSUE TITLE
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"... page record for 0x7f94f00010 was not found (block_size=16)

### ISSUE THREAD

**Issue by irfaanDJ** [termux/termux-packages#3844]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/3838.

**Comment by irfaanDJ** [comment]
close nya di mana?

Pada tanggal Rab, 22 Mei 2019 04.30, Leonid Plyushch <
notifications@github.com> menulis:

**Comment by Garrixer** [comment]
I have the same problem :( I have to do it to be normal again

**Comment by fornwall** [comment]
@Garrixer Run `pkg up?` to update packages!
