### ISSUE TITLE
Error Termux: CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"

### ISSUE THREAD

**Issue by yogiema** [termux/termux-packages#3847]
![Screenshot_2019-05-22-04-47-37-236_com termux](https://user-images.githubusercontent.com/43556633/58132989-3ad7fd80-7c12-11e9-9944-7f239f80317d.png)

**Comment by yogiema** [comment]
@fornwall pleae help me!

**Comment by yogiema** [comment]
@fornwall please help me!

**Comment by xeffyr** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/3838.
