### ISSUE TITLE
My php cannot link executeable

### ISSUE THREAD

**Issue by Dsya** [termux/termux-packages#3848]
pkg update php
Hit:1 https://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ php
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"...
$

**Comment by InfoSecRavindra** [comment]
Same issue here

**Comment by Dsya** [comment]
Something wrong with the server..

**Comment by xeffyr** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/3838.
