### ISSUE TITLE
Package request: Mercurial

### ISSUE THREAD

**Issue by thurask** [termux/termux-packages#385]
https://www.mercurial-scm.org/

Termux already has Git and Subversion, might as well include the other major version control system.

**Comment by Neo-Oli** [comment]
Hi, Mercurial can already be installed from the python package Index

```
apt install python2
pip2 install mercurial
hg --version
Mercurial Distributed SCM (version 3.9)
```

**Comment by thurask** [comment]
Ah, forgot about pip2.

Guess I'll close this, then.

**Comment by tamsky** [comment]
https://github.com/termux/termux-packages/issues/987#issuecomment-391512988

mentions that the instructions above are no longer sufficient to `pkg install mercurial`.

you may first need to `pkg install python2 python2-dev clang crypt-dev`
