### ISSUE TITLE
Problem Downloading Package

### ISSUE THREAD

**Issue by Sam3ghost** [termux/termux-packages#3853]
When I write an order 
$ pkg install metasploit
Error :dpkg: error processing package metasploit (--configure):                                             installed metasploit package post-installation script subprocess returned error exit status 5      Errors were encountered while processing:          metasploit                                       E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by xeffyr** [comment]
Your error message is truncated and it is impossible to know what is wrong.
