### ISSUE TITLE
Packages cannot locate symbol "iconv_open" (or "libiconv_open")

### ISSUE THREAD

**Issue by wissenswandler** [termux/termux-packages#3855]
**Problem description**

While working a in a Termux session I kept receiving CANNOT LINK [...] errors for most commands or depending libs.

I remember that I installed _parallel_ before the errors started. There was another error or warning message in stdout of the _parallel_  installation, which I did not inspect (or log or remember) in detail.

After exiting the session I am getting following error immediately upon start of a new Termux session:

```
CANNOT LINK EXECUTABLE "cat": cannot locate symbol "iconv_open" referenced by "/data/data/com.termux/files/usr/bin/coreutils"...
Aborted
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": cannot locate symbol "iconv_close" referenced by "/data/data/com.termux/files/usr/bin/bash"...

[Process completed (signal 6) - press Enter]

```

**Steps to reproduce**

Now every time when I try to start Termux, it immediately throws this error at me and stops. Nothing I could do in that Termux session except closing it.

**Additional information**

am using a Lenovo YB1-X90L with Android 7.1.1. (not rootet) and a pretty recent Termux.

**Comment by st7105** [comment]
+ OnePlus 3 (Android 9.0.2)

**Comment by fornwall** [comment]
You need to update packages.

Normally this is done by running `pkg up`, but if your Termux environment is so broken so that cannot be run the easiest way is to uninstall the Termux app completely and then reinstall it.

Note that you will loose the content of your $HOME directory when uninstalling. If this is a problem you need to look into failsafe sessions (long press on the Termux icon to get the Failsafe shortcut).

**Comment by samoht0** [comment]
Something looks fishy for me.
Android 5 branch packages are up to date here, including
https://github.com/termux/termux-packages/commit/ce9473fdca11bcaa11adc6340118768e969d8792
For mc (no other broken stuff noticed) I'm getting:
CANNOT LINK EXECUTABLE: cannot locate symbol "libiconv_open" referenced by "/data/data/com.termux/files/usr/lib/libglib-2.0.so"...
page record for 0xb6e5e02c was not found (block_size=16)
Something broken (just) here? Another issue (opening sparete bug needed)?

**Comment by xeffyr** [comment]
Commit https://github.com/termux/termux-packages/commit/ce9473fdca11bcaa11adc6340118768e969d8792 has no relation to the issue.

Do `export LD_PRELOAD=libiconv.so` for temporary workaround until glib will be fixed.

**Comment by john-x** [comment]
Getting a similar error when attempting to run *mpv:* 

```
CANNOT LINK EXECUTABLE: cannot locate symbol "libiconv_open" referenced by "/data/data/com.termux/files/usr/libexec/mpv"…
```

Error message remains the same after attempting @xeffyr 's workaround. It has had no effect.

**Comment by xeffyr** [comment]
>  It has had no effect.

It may not have effect for whatever reason:

* You don't have upgraded packages.
* You doing it wrong.
* Workaround was proposed to fix `mc` but not `mpv`. Though it should work for `mpv` too.

**Comment by samoht0** [comment]
> Do `export LD_PRELOAD=$PREFIX/lib/libiconv.so` for temporary workaround until glib will be fixed.
Works.
Now mc seems fine with latest glib update.

**Comment by matthewsalmon** [comment]
I am getting this error on Android 5.1.1, packages are updated:

/data/data/com.termux/files/home > xclock
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "xclock"...

**Comment by john-x** [comment]
>You don't have upgraded packages.
Ran *pkg up* all throughout yesterday and today and reset Termux to a fresh install. No change.

>You doing it wrong. 
You mean other than copying and pasting into a terminal? *You* right… instructions not clear; dick got stuck in github trying to execute it. 

>Workaround was proposed to fix mc but not mpv. Though it should work for mpv too.
That much I already understood. 

>This workaround works only per session, it is not persistent.
I'm not a well-seasoned coder by any means, but I know how environment variables work, neighbor. 

>Also, if your packages are up to date, mpv will work fine without any workaround
Gads. This is the equivalent of "try turning it off and on." *mpv --version* won't pull up anything – because of the same error message I've already mentioned – but here this is what *pkg* shows:
```
$pkg show mpv
Package: mpv
Version: 0.29.1-3
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 1294 kB
Depends: libiconv, ffmpeg, openal-soft, libandroid-support, libandroid-glob, liblua52, libpulseaudio
Homepage: https://mpv.io/
Download-Size: 612 kB
APT-Manual-Installed: yes
APT-Sources: https://termux.net stable/main arm Packages
Description: Command-line media player
```

**Comment by john-x** [comment]
>You don't have upgraded packages.

Ran pkg up all throughout yesterday and today and reset Termux to a fresh install. No change.

>You doing it wrong.

You mean other than copying and pasting into a terminal? *You* right… instructions not clear; dick got stuck in github trying to execute it.

>Workaround was proposed to fix mc but not mpv. Though it should work for mpv too.

That much I already understood.

>This workaround works only per session, it is not persistent.

I'm not a well-seasoned coder by any means, but I know how environment variables work, neighbor.

>Also, if your packages are up to date, mpv will work fine without any workaround

Gads. This is the equivalent of "try turning it off and on." *mpv --version* won't pull up anything – because of the same error message I've already mentioned – but here this is what pkg shows:
```
$pkg show mpv
Package: mpv
Version: 0.29.1-3
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 1294 kB
Depends: libiconv, ffmpeg, openal-soft, libandroid-support, libandroid-glob, liblua52, libpulseaudio
Homepage: https://mpv.io/
Download-Size: 612 kB
APT-Manual-Installed: yes
APT-Sources: https://termux.net stable/main arm Packages
Description: Command-line media player
```

**Comment by Grimler91** [comment]
@john-x what's your output of `termux-info`?

**Comment by john-x** [comment]
```
$termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.49-ge7aac37 #1 SMP PREEMPT Wed Feb 3 16:37:37 CST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.1
Device manufacturer:
motorola
Device model:
XT1526
```

**Comment by john-x** [comment]
Here is my `printenv' output too: 
```
$printenv
SHELL=/data/data/com.termux/files/usr/bin/bash
PREFIX=/data/data/com.termux/files/usr
PWD=/data/data/com.termux/files/home
EXTERNAL_STORAGE=/storage/emulated/legacy
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libiconv.so
HOME=/data/data/com.termux/files/home
LANG=en_US.UTF-8
TMPDIR=/data/data/com.termux/files/usr/tmp
ANDROID_DATA=/data
TERM=xterm-256color
SHLVL=1
ANDROID_ROOT=/system
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/data/data/com.termux/files/usr/local/bin
_=/data/data/com.termux/files/usr/bin/applets/printenv
```

**Comment by xeffyr** [comment]
What is output of `strings /data/data/com.termux/files/usr/lib/libiconv.so | grep iconv_open` ?
Just really strange that ld_preload'ing libiconv is not working for you.

**Comment by john-x** [comment]
```
libiconv_open
libiconv_open_into
```

**Comment by xeffyr** [comment]
Downgraded my tablet from Android 6 to 5.1, now I have same issue with `mpv`...

**Comment by samoht0** [comment]
> And it seems that it works on Android 6 because of a bit different linker.

Looks like. No problems with mpv on Android 6 here.

**Comment by john-x** [comment]
That fixed it! Thank you! 
Also, I think I owe you an apology, @xeffyr. I'm sorry for being short tempered. I was having a bad day and it was driving me crazy trying to troubleshoot the problem on my own. Thank you for taking time out of your day to maintain these packages and for your help. God bless.

**Comment by matthewsalmon** [comment]
I have binutils installed but no 'strings' command ...

> strings /data/data/com.termux/files/usr/lib/libiconv.so | grep iconv_open
strings-GNU: command not found

**Comment by xeffyr** [comment]
> I have binutils installed but no 'strings' command ...

* Why you are executing this ?

* By looking on your output (`strings-GNU: command not found`) I can only say that you have something wrong with your installation. There no command `strings-GNU` available but only `strings`. Messing with aliases ?

**Comment by xeffyr** [comment]
And this issue should be solved as not so many packages were affected and they were fixed yesterday.

**Comment by matthewsalmon** [comment]
./startfluxbox.sh
/data/data/com.termux/files/home > CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "fluxbox"...

**Comment by xeffyr** [comment]
X11 packages will be fixed later since they are not part of main package set.

**Comment by yudi1999** [comment]
Why is the thermux connection slowing down if I want to install the Perl
tool in the termux?

Pada tanggal Sab, 25 Mei 2019 19.56, Leonid Plyushch <
notifications@github.com> menulis:
