### ISSUE TITLE
Unable to get root privilages.su, tsu, termux-sudo wont work

### ISSUE THREAD

**Issue by mrjosephschmoe888** [termux/termux-packages#3856]
When i type su or tsu or sudo. I lose $ shell and termux hangs. I can type but no Acton's to commands.
Have to restart termux to get $ back

**Comment by Grimler91** [comment]
Are you rooted?

Have you given termux root permissions in your superSU app or similar?

**Comment by mrjosephschmoe888** [comment]
I am rooted. Termux did not request root permissions from SuperSU. Don't know another way to do it

**Comment by Grimler91** [comment]
Can you get root access from a adb shell or another app?

**Comment by mrjosephschmoe888** [comment]
Yes from su root command app. But cannot access installed softwares i require root access for

**Comment by mrjosephschmoe888** [comment]
I reinstalled supersu. And upgraded again, now i can type su without dropping out, but now all commands are permission denied until exit. No installed python works

**Comment by Grimler91** [comment]
That's because needed environmental variables aren't set. 
run `tsu -a` or `tsu -p` instead.
