### ISSUE TITLE
I have removed my package manager ,how can I recover except reinstalling Termux?

### ISSUE THREAD

**Issue by cherryblow** [termux/termux-packages#3859]
There is some problems with dpkg,then I run 'pkg remove dpkg',and then I type 'Yes, do as I say!' to remove dpkg.But when I tried to run 'pkg install dpkg',I found that dpkg and apt are both disappear and it says 'pkg install dpkg /data/data/com.termux/files/usr/bin/pkg: 36: /data/data/com.termux/files/usr/bin/pkg: apt: not found '.Whatever I run with 'pkg' it shows that.
I tried to install apt ,dpkg and pkg ,but I can only find deb pakages,which I can not install without dpkg.I found source codes of apt and dpkg on github but it cannot be used,run build.sh is no use.I downloaded apt-1.8.1.tar.xz on debian ,the link is from build.sh of github apt packages  ,also no use.How can i install apt and dpkg ,please give me a solution ,Thank Termux and you!

**Comment by xeffyr** [comment]
> There is some problems with dpkg,then I run 'pkg remove dpkg'

Radical way of solving package problems...

> and then I type 'Yes, do as I say!' to remove dpkg.

There is just one problem - you are not reading messages printed to console.

> How can i install apt and dpkg ,please give me a solution

In short - you can't. Termux uses \*.deb file format to distribute packages. Such files can be installed with `dpkg` (note that apt only downloads them and not installs !!!).

So, you have no variant other than re-installing Termux.
