### ISSUE TITLE
Termux failsafe went missing

### ISSUE THREAD

**Issue by AdhilJamal** [termux/termux-packages#3869]
I had an issue concerning termux.
I had a tool-x repository installed in it and downloaded about 250 tools. After that, i tried to install nethunter in it. It said i needed root permissions. Then when i granted it, it did'nt workout well, so when i tried to exit the su, it suddenly showed some error message saying CANNOT LINK EXECUTABLE: cat libandroid not found. I googled the issue and decided to open failsafe. But the problem was, the failsafe was nowhere to be found! I uninstalled termux and installed it again as there was no choice, my whole work with termux and my files were deleted. I am so sad i lost it and i request to fix this error from ever happening again..

**Comment by xeffyr** [comment]
50 % of people said before failsafe icon is annoying...
Another 50 % complains that failsafe icon gone...

No comments...

**Comment by xeffyr** [comment]
Failsafe icon was removed and won't be added back.

**Comment by Grimler91** [comment]
A failsafe session can be opened by long-pressing termux icon and clicking 'failsafe" though (on recent android versions), or by long pressing the "new session" button the the left drawer
