### ISSUE TITLE
Package request: GNU Octave

### ISSUE THREAD

**Issue by franciscod** [termux/termux-packages#387]
There are a few Octave "distros" for Android so maybe it's simple to bring Octave into Termux too. I might give it a shot in a few weeks (but don't let that stop you, feel free to try anyway :))

**Comment by Goodgithuber** [comment]
I like using android to plot graph on the fly, the GNUroot debian Octave eats like 650MB of diskspace, I lik Termux better.

**Comment by its-pointless** [comment]
done it myself..

**Comment by kurokirasama** [comment]
so it is possible to have octave on termux?

**Comment by Atavic** [comment]
Can be closed as solved [here](https://github.com/its-pointless/gcc_termux/issues/16).

**Comment by sdrausty** [comment]
@franciscod  `octave` is currently available via https://sdrausty.github.io/TermuxArch/ Arch Linux in [Termux PRoot](https://github.com/termux/proot).  Use `pacman -S octave` to install `octave` on device once [Arch Linux](https://www.archlinux.org/) is installed in Termux.  

![Screenshot of Arch On Termux](https://sdrausty.github.io/TermuxArch/docs/imgs/IMG_20171019_190414.jpg)

@Atavic https://en.wikipedia.org/wiki/GNU_Octave is on Wikipedia.  Termux is not https://github.com/termux/termux-packages/issues/1930 "Please share your thoughts on the matter ..." as the notice requests.

**Comment by Grimler91** [comment]
@Atavic Thanks!

**Comment by Grimler91** [comment]
Reopening this, goal is to have octave available in the main repo.
Low priority I suppose though since it is available from ita-pointless repo.

**Comment by sdrausty** [comment]
GNU rocks!  @Grimler91 Thank you for reopening this issue.  Are you familiar with https://www.gnu.org/distros/free-distros.en.html  Especially:
> If you maintain a distribution that follows the [Free System Distribution ](https://www.gnu.org/distros/free-system-distribution-guidelines.html) and would like to be listed here, please write to <webmasters@gnu.org> with an introduction and a link to the project Web site.

**Comment by apandada1** [comment]
The octave in its-pointless repo has gui disabled (tried with fluxbox and xfce). So it might be a good idea to keep this feature enabled in the official repository.

**Comment by xeffyr** [comment]
> in the official repository.

There is a reason why octave is available only in its-pointless repository.

**Comment by tathastu871** [comment]
https://play.google.com/store/apps/details?id=tech.ula.octave

**Comment by tathastu871** [comment]
Tried installing from itspointless repo throws below error
CANNOT LINK EXECUTABLE "octave": library "libandroid-support.so" not found

**Comment by apandada1** [comment]
> https://play.google.com/store/apps/details?id=tech.ula.octave

This is a paid download. Please don't spam the thread.

**Comment by Grimler91** [comment]
> Tried installing from itspointless repo throws below error CANNOT LINK EXECUTABLE "octave": library "libandroid-support.so" not found

Works fine here. Most likely you have installed octave from the android-5/6 repository on an android >= 7 device. Use the android >= 7 repo: `deb https://its-pointless.github.io/files/24 termux extras`

**Comment by tathastu871** [comment]
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-6.1.0": library "libmetis.so" not found

**Comment by tathastu871** [comment]
> > Tried installing from itspointless repo throws below error CANNOT LINK EXECUTABLE "octave": library "libandroid-support.so" not found
> 
> Works fine here. Most likely you have installed octave from the android-5/6 repository on an android >= 7 device. Use the android >= 7 repo: `deb https://its-pointless.github.io/files/24 termux extras`

Tried that
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-6.1.0": library "libmetis.so" not found

To solve above error installed openfoam as it provides libmetis. 

Then same libandroid again

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-6.1.0": library "libandroid-support.so" not found

**Comment by Grimler91** [comment]
> Tried that CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-6.1.0": library "libmetis.so" not found
> 
> To solve above error installed openfoam as it provides libmetis.

libmetis.so is provided by `suitesparse`, and octave already depends on it so the library should already be installed.

> Then same libandroid again
> 
> CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-6.1.0": library "libandroid-support.so" not found

I still can't produce any issue, so best guess is that your environment is broken for some reason.

**Comment by yjb152-yjb** [comment]
/sdcard $ octave
octave: no graphical display found
octave: disabling GUI features
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-7.3.0": library "libGLU.so" not found

**Comment by Jrsimonetti2** [comment]
Amanhã a polícia resolve essa bagaceira que estão pondo no meu cel

Em sex., 26 de mai. de 2023 01:29, yjb152-yjb ***@***.***>
escreveu:

**Comment by zoomlogo** [comment]
> > > Tried installing from itspointless repo throws below error CANNOT LINK EXECUTABLE "octave": library "libandroid-support.so" not found
> > 
> > 
> > Works fine here. Most likely you have installed octave from the android-5/6 repository on an android >= 7 device. Use the android >= 7 repo: `deb https://its-pointless.github.io/files/24 termux extras`
> 
> Tried that CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-6.1.0": library "libmetis.so" not found
> 
> To solve above error installed openfoam as it provides libmetis.
> 
> Then same libandroid again
> 
> CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-6.1.0": library "libandroid-support.so" not found

Adding this to my `.zshrc` seemed to solve the issue for me.
```
export PREFIX=/data/data/com.termux/files/usr
export LD_LIBRARY_PATH=$PREFIX/lib
export PATH=$PREFIX/bin
```

**Comment by raviraj-47** [comment]
I have installed the octave on termux how to run it please tell

**Comment by archisman-panigrahi** [comment]
Run the command `octave`

**Comment by raviraj-47** [comment]
It wasn't not working earlier with the same octave command but it worked now
Thanks bro
