### ISSUE TITLE
Pygtk

### ISSUE THREAD

**Issue by vpervenditti** [termux/termux-packages#3870]
**Package description**
PyGTK is a set of Python wrappers for the GTK+ GUI library. It offers a comprehensive set of graphical elements and other useful programming facilities for creating desktop applications. It is a part of the GNOME project. PyGTK is free software and licensed under the LGPL.

**Link to home page and sources**
1. Home page: https://pygobject.readthedocs.io/en/latest/
2. Source code: 

**Additional information**
I didnt try to compile it

**Comment by xeffyr** [comment]
Python modules are not accepted as package requests.

**Comment by Yisus7u7** [comment]
Dude, I'd like you to add pygtk or any other element for x11 app development, I'm excited about termux, and to a that's a little dead x11, I'd like to make apps for it, and scripts with graphical interface, but termux doesn't have those simple dependencies, I'd like the developers to think a little bit about us, and give us a hand with that
