### ISSUE TITLE
[MSM8916 devices] illegal instruction when using openssl-dependent utilities

### ISSUE THREAD

**Issue by SoumyadeepChatterjee96** [termux/termux-packages#3872]
I had a phone lying around and suddenly i planned to install Termux and use this one as a dedicated Node-red server as its pretty handy to run it on something like this.
I installed Termux and then went ahead to install Openssh and could install it but when I try to start the server it returned with 'Illegal Instruction' and out of frustration I uninstalled Termux.
When I reinstalled Termux I couldn't install anything from the repo as all gave me the output as

'Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.'

Help me solve this PLEASE! Newbie for the environment.

**Comment by afifah32** [comment]
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.😢😢😭

**Comment by SoumyadeepChatterjee96** [comment]
@afifah32 you having the same issue? which android version are you on and what's your processor?

**Comment by KU5UM4CYB3R** [comment]
Help me I

**Comment by afifah32** [comment]
@soumyadeepchatterje96  OPPO A37😪😪

**Comment by SoumyadeepChatterjee96** [comment]
@afifah32 I have the same SOC. But there's this Galaxy j5 that have the same thing and it never returned with the issue.

**Comment by ngucyt** [comment]
it doesn't run
pkg upgrade
0% [Working]

**Comment by roy232** [comment]
Masalahnya sama persis

**Comment by afifah32** [comment]
Aku sudah bagus, caranya adalah download termux di up to down versi 0.27
Selamat mencoba😁😁😎

Pada tanggal Sab, 25 Mei 2019 22.50 SoumyadeepChatterjee96 <
notifications@github.com menulis:

**Comment by fornwall** [comment]
Hello! Could those of you affected by this issues try out this:

    wget http://termux.net/issue_3872_openssl_1.1.1c_aarch64.deb
    dpkg -i issue_3872_openssl_1.1.1c_aarch64.deb

and see if that solves the issue? That version of the package was built with https://android.googlesource.com/platform/external/openssl/+/7a0cd2ac47950d221483b9dfef214e85c916d586 applied.

**Comment by Grimler91** [comment]
@SoumyadeepChatterjee96 @afifah32 does the openssl version fornwall shared above fix the issue?

**Comment by deoryus** [comment]
not for me

**Comment by xeffyr** [comment]
@deoryus seems like your downloaded file is corrupted.

Its SHA-256 should be:
```
9074190a06d27ecf03d8cd3ac8252dcf04cad4fd7c1399ddc25f1ecf6454353c  issue_3872_openssl_1.1.1c_aarch64.deb
```

And if file is okay, it will be installed correctly:
```
[~]:$ wget http://termux.net/issue_3872_openssl_1.1.1c_aarch64.deb
Connecting to termux.net (104.18.36.234:80)
issue_3872_openssl_1 100% |********************************|  887k  0:00:00 ETA
[~]:$ dpkg -i issue_3872_openssl_1.1.1c_aarch64.deb 
(Reading database ... 488 files and directories currently installed.)
Preparing to unpack issue_3872_openssl_1.1.1c_aarch64.deb ...
Unpacking openssl (1.1.1c) over (1.1.1c) ...
Setting up openssl (1.1.1c) ...
[~]:$
```

**Comment by deoryus** [comment]
@xeffyr it installed successfully but issue remain still.

openssl still return illegal instruction

**Comment by fdciabdul** [comment]
still 0% working :')

**Comment by miniact** [comment]
What's the solution then?

**Comment by xeffyr** [comment]
@miniact There no solution as this is ROM bug.

**Comment by miniact** [comment]
😢😢😥😭

**Comment by fornwall** [comment]
@miniact @fdciabdul @deoryus @SoumyadeepChatterjee96 (or any else affected):

Can you test the latest openssl update and see if that fixes the problem? Run the following commands:

```sh
busybox wget http://termux.net/dists/stable/main/binary-aarch64/openssl_1.1.1c-1_aarch64.deb
dpkg -i openssl_1.1.1c-1_aarch64.deb
```

and then try e.g. `pkg up` to see if it works.

**Comment by fdciabdul** [comment]
Yap it's working again now , thankyou

**Comment by fornwall** [comment]
@fdciabdul Great, thanks a lot for the help!

**Comment by daling** [comment]
> @miniact @fdciabdul @deoryus @SoumyadeepChatterjee96 (or any else affected):
> 
> Can you test the latest openssl update and see if that fixes the problem? Run the following commands:
> 
> ```shell
> busybox wget http://termux.net/dists/stable/main/binary-aarch64/openssl_1.1.1c-1_aarch64.deb
> dpkg -i openssl_1.1.1c-1_aarch64.deb
> ```
> 
> and then try e.g. `pkg up` to see if it works.

It worked for me, but please note that the link to the .deb file can change. Look for the current correct filename on http://termux.net/dists/stable/main/binary-aarch64/ and change your command accordingly.

**Comment by darthwalsh** [comment]
@fornwall Should this issue stay open until the workaround isn't needed? I installed Termux on my chromebook today and ran into the same problem. (Or, maybe the fix hasn't been released yet? I am on verision 0.86.)

BTW, if anybody is looking for the workaround and you get an error like:

    $ dpkg -i openssl_1.1.1d-2_aarch64.deb
    dpkg: error processing archive openssl_1.1.1d-2_aarch64.deb (--install):
     package architecture (aarch64) does not match system (i686)

Then like it says you should change the installation URL to [http://termux.net/dists/stable/main/binary-**i686**/openssl_1.1.1d-2_**i686**.deb](http://termux.net/dists/stable/main/binary-i686/openssl_1.1.1d-2_i686.deb)

**Comment by Grimler91** [comment]
@darthwalsh [this issue has been fixed](https://github.com/termux/termux-packages/commit/340fcae409869bcda830afc4b2546f8257376674) so you are probably encountering some other similar issue. Please open a new issue here at github and provide the information in the [bug report template](https://github.com/termux/termux-packages/issues/new?template=bug_report.md).

**Comment by xeffyr** [comment]
@Grimler91 Fix available only for ARM as we didn't know that it happens for i686 too (openssl in i686 virtual device works fine without problems like in this issue).

**Comment by rakesh-rgb** [comment]
@fornwall I am unable to install busybox, it says (Reading package failed lists...Error!) 
E: flAbsPath on /data/data/com.termux/files/usr/var/lib/dpkg/status failed- realpath
E: could not open file -open 
E:  problem opening
E: The package lists or status file could not be parsed or opened.
                      what should I do?

**Comment by xeffyr** [comment]
@rakesh-rgb Perhaps you need to reinstall Termux as package database could be broken.
