### ISSUE TITLE
X11 Packages problem

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-packages#3877]
X11 packages seem to not work for some reason. I hope that you can help me.
I have tried: aterm, mtpaint.

aterm: can't open display :0

mtpaint: CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "mtpaint"...

**Comment by Grimler91** [comment]
Duplicate of https://github.com/termux/x11-packages/issues/96
