### ISSUE TITLE
Torsocks SSH error

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-packages#3878]
When I try to ssh through tor, I receive this error:

1558769194 PERROR torsocks[32096]: socks5 libc connect: Connection refused (in socks5_connect() at /home/builder/.termux-build/torsocks/src/src/common/socks5.c:202)
ssh: connect to host mmgqi7uql42kgltfnagetfpd6lsrjwuvjjxosw6mkpum7x76u332weid.onion port 22: Connection refused

I did EXACTLY what the Termux Wiki told me to. What am I missing.

**Comment by Grimler91** [comment]
The error message says that hte host you are trying to connect to doesn't allow connections on port 22, so you probably want to use another port or make sure ssh is listening on that port. 

Sidenote, maybe it's not a good idea to show your onion address to everyone here at github?

This doesn't really seem to be a termux specific problem.

**Comment by HoangPhantom** [comment]
I used another port and it displays the same message

1558778251 PERROR torsocks[11687]: socks5 libc connect: Connection refused (in socks5_connect() at /home/builder/.termux-build/torsocks/src/src/common/socks5.c:202)
ssh: connect to host 6hhhhtfg.onion port 8022: Connection refused

**Comment by Grimler91** [comment]
You haven't shared any details about your setup/configuration so we can't really know what you've done wrong...
Try without torsocks and make sure sshd is running.

**Comment by HoangPhantom** [comment]
I will try. Thank you very much

**Comment by HoangPhantom** [comment]
It says

ssh: Could not resolve hostname ugyjbgyhgfg.onion: No address associated with hostname

Here is my torrc file.
[torrc.txt](https://github.com/termux/termux-packages/files/3219285/torrc.txt)

**Comment by xeffyr** [comment]
Try `proxychains-ng` instead of `torsocks`.

**Comment by xeffyr** [comment]
And make sure that **tor** is running.

It is possible to get error
```
1558780678 PERROR torsocks[19745]: socks5 libc connect: Connection refused (in socks5_connect() at /home/builder/.termux-build/torsocks/src/src/common/socks5.c:202)
```
only when no Tor SOCKS proxy running. You perhaps missed some step from Wiki.

**Comment by HoangPhantom** [comment]
I will try

**Comment by HoangPhantom** [comment]
It worked. Thank you very much
