### ISSUE TITLE
termux-tools: ping6 and ip command issues

### ISSUE THREAD

**Issue by lark** [termux/termux-packages#3879]
**Problem description**
ipv6 is working in my phone, but `ping6` and `ip` command is not working as expected.
```
$ ping6 ::1
PING ::1(::1) 56 data bytes
Bad system call
```

```
$ ip -6 route
```
No ipv6 route is output

`ip -6 addr sh` works as expected.

**Additional information**

termux-tools 0.65

strace log shows that setuid() triggers SIGSYS.

**Comment by xeffyr** [comment]
Termux uses `ping` and `ping6` commands provided by Android. For example, `$PREFIX/bin/ping6` in Termux is actually a wrapper script:
```
#!/data/data/com.termux/files/usr/bin/sh
unset LD_LIBRARY_PATH LD_PRELOAD
PATH=$PATH:/system/bin exec /system/bin/ping6 "$@"
```

If `/system/bin/ping6` is broken, it cannot be fixed.

***

Command `ip` is wrapper script too:
```
#!/data/data/com.termux/files/usr/bin/sh
unset LD_LIBRARY_PATH LD_PRELOAD
PATH=$PATH:/system/bin exec /system/bin/ip "$@"
```

**Comment by lark** [comment]
Just FYI, I forgot that android uses routing policies heavily.
Actually, `ip -6 route show table all` works as expected.
