### ISSUE TITLE
Failed create symbolic link

### ISSUE THREAD

**Issue by apolbox** [termux/termux-packages#3882]
Why does this always fail to make symbolic links?

formCheckSymbolic()
{
        TARGET=${1}
        LINK_NAME=${2}
        # Cek symbolic jika sudah ada
        if [ -h "${LINK_NAME}/www" ]; then
                echo -e "\e[31;mSymbolic link sudah ada.\e[0m"
                lamppScriptQuestion
        else
                if [ $(ln -s $TARGET $LINK_NAME) ]; then
                        echo -e "\e[32;mBerhasil membuat symbolic link.\e[0m"
                        lamppScriptQuestion
                else
                        echo "Failed"
                fi
        fi
}

Thanks.

**Comment by xeffyr** [comment]
Why this shouldn't fail ?

> if [ $(ln -s $TARGET $LINK_NAME) ]; then

Invalid conditional. Think why.

**Comment by xeffyr** [comment]
```Shell
if ln -s $TARGET $LINK_NAME; then
    echo ok
else
    echo fail
fi
```

**Comment by xeffyr** [comment]
Btw, you cannot create symlinks on sdcard due to filesystem limitations.
