### ISSUE TITLE
gnuplot no longer exports to png/jpeg

### ISSUE THREAD

**Issue by dsvilko** [termux/termux-packages#389]
After the last update of the gnuplot package my script can no longer export the plot to pngcairo (0 byte output) or jpeg (segfault). Is it possible to install an older version of the package?

**Comment by fornwall** [comment]
Could you try `apt update && apt upgrade` and see if it works after updating (I just updated and rebuilt several related packages)?

If the problem remains, can you write the output of `dpkg --print-architecture` here, as well as giving a simple script to reproduce the problem (this would be very helpful)!

**Comment by dsvilko** [comment]
Thank you! It's now, once again, working perfectly. 

On 13 August 2016 05:00:50 CEST, Fredrik Fornwall <notifications@github.com> wrote:
>Could you try `apt update && apt upgrade` and see if it works after
>updating (I just updated and rebuilt several related packages)?
>
>If the problem remains, can you write the output of `dpkg
>--print-architecture` here, as well as giving a simple script to
>reproduce the problem (this would be very helpful)!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/termux/termux-packages/issues/389#issuecomment-239598251

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
