### ISSUE TITLE
postgresql problem

### ISSUE THREAD

**Issue by Sam3ghost** [termux/termux-packages#3891]
when I put command 
$pg_upgrade -d oldCluster/data -D newCluster/data -b oldCluster/bin -B newCluster/bin
The error is :check for "oldCluster/bin" failed: No such file or directory

Failure, exiting
Some help please

**Comment by xeffyr** [comment]
> $pg_upgrade -d oldCluster/data -D newCluster/data -b oldCluster/bin -B newCluster/bin
check for "oldCluster/bin" failed: No such file or directory

Are you sure that all files specified on command line exist ?

**Comment by Sam3ghost** [comment]
yes I follow commands in this website :https://www.postgresql.org/docs/11/pgupgrade.html

**Comment by xeffyr** [comment]
What output of command
```
ls oldCluster/data newCluster/data oldCluster/bin newCluster/bin
```
?

**Comment by Sam3ghost** [comment]
output is :No such file or directory
but I download $ pkg install postgresql

**Comment by xeffyr** [comment]
> No such file or directory

Then you really don't have files at required locations...
