### ISSUE TITLE
Can't do pkg update && pkg upgrade after update version 0.72

### ISSUE THREAD

**Issue by saisubham** [termux/termux-packages#3894]
After running command `pkg update && pkg upgrade` the following output was produced:

`CANNOT LINK EXECUTABLE "dpkg-deb": library "liblzma.so.5" not found
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/libandroid-support_25_aarch64.deb (--unpack):
 dpkg-deb --control subprocess was killed by signal (Aborted)
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/libandroid-support_25_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)`

Logcat output:
[logcat1.txt](https://github.com/termux/termux-packages/files/3225060/logcat1.txt)

**Comment by xeffyr** [comment]
Likely your environment was in partial-upgrade step, i.e. dpkg was updated but liblzma is not.

Easiest way to solve will be to remove `$PREFIX`: `rm -rf $PREFIX` and re-install packages again.

**Comment by saisubham** [comment]
That'll most probably nuke and pave my chroot environment. Isn't there another way to do this? I have many custom binary executables and scripts in my bin which are important.

**Comment by MansLegend** [comment]
Likely your environment was at partial-upgrade stage, i.e. dpkg was updated but liblzma not.

Easiest way to solve will be to remove $PREFIX: rm -rf $PREFIX and re-install packages again.
this is good ' but it's delete some tools like python ....
