### ISSUE TITLE
Android: lack of GUI option to disable vibration makes users suffer

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [termux/termux-packages#3895]
**Problem description**
I thought I had all vibration disabled on my phone. Yet, Termux seems to vibrate when any command exits with an error code. The vibration makes me feel ill. Disabling it was no easy matter - see next section.

**Steps to reproduce**
In order to disable the vibration, I had to:
1. Find a webpage telling me how to do use a config file to disable the vibration (I found [this page](https://www.reddit.com/r/termux/comments/bei0jw/how_can_i_disable_vibration_in_termux/)).
2. Find out what Android considers `$HOME` (for that variable/location was referenced by the aforementioned webpage).
3. Create the required config file.
4. Download a paid app in order to edit a file as root.
5. Edit the config file.
6. Restart Termux.

And all this on a rather small screen with no proper keyboard.

Actually, though, I never got beyond step 4 because the editor I used, namely Root Explorer, fails to recognise my device as rooted for some reason.

**Expected behavior**
A GUI option, or some simple terminal command, to permanently disable vibration - and/or Termux should respect system settings whereby vibration is disabled (although admittedly the latter might be hard because disabling vibration completely is impossible/hacky on Android, at least on Android Lollipop).

**Additional information**
Post output of command `termux-info`.
Output on my device was: none. I have the latest Play Store (or was it FDroid?) version.

Android Lollipop. (The device - a phone - cannot be upgraded to a newer OS without de-rooting.)

**Comment by xeffyr** [comment]
> A GUI option

For now, all settings are done through `~/.termux/termux.properties` text file.

**Comment by xeffyr** [comment]
> Actually, though, I never got beyond step 4 because the editor I used, namely Root Explorer, fails to recognise my device as rooted for some reason.

Also, editing `~/.termux/termux.properties` NEVER required root. Termux has plenty of text editors inside it and it quite easy to modify files in your `$HOME`.

**Comment by LinuxOnTheDesktop** [comment]
Please supply a command - complete with path to the config file - which will allow me to edit that file.

**Comment by xeffyr** [comment]
```
pkg install nano
mkdir -p ~/.termux
nano ~/.termux/termux.properties
```

Instead of `nano` you can use something else, for example `vim` or `micro`.
If you need to just add one line to file, you can try `echo` or `cat`...

**Comment by Neo-Oli** [comment]
```
mkdir -p ~/.termux
echo "bell-character=ignore" >> ~/.termux/termux.properties
termux-reload-settings
```
This will disable vibration without any editors. 

There is also a wiki page (accessible from inside Termux by opening Help) describing this config file
https://wiki.termux.com/wiki/Terminal_Settings
