### ISSUE TITLE
install postgresql.tar.gz

### ISSUE THREAD

**Issue by Sam3ghost** [termux/termux-packages#3901]
How I can install tar.gz files like:
postgresql-10.8-1-linux-binaries.tar.gz
in termux and create db please help me I lost I'm trying from 2 weeks

**Comment by Sam3ghost** [comment]
I have a problem when I input :
$ tar xf postgresql-10.8-1-linux-binaries.tar
the output is: 
tar: can't create symlink 'pgsql/include/ncurses/ncurses.h' to 'curses.h': Operation not permitted

**Comment by xeffyr** [comment]
Why not just `pkg install postgresql` ???

**Comment by Grimler91** [comment]
I'm guessing 10.8 is needed to recover some database from the old postresql version. Unfortunately we don't keep old package versions though, and a postresql compiled for "linux" will unfortunately not work in termux.
