### ISSUE TITLE
Tor bug

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-packages#3902]
I was trying to establish a tor connection and it gave me this error. Please help.

CANNOT LINK EXECUTABLE: cannot locate symbol "evutil_secure_rng_add_bytes" referenced by "tor"...

**Comment by alcott1331** [comment]
another bug about  tor :

tor
CANNOT LINK EXECUTABLE "tor": cannot locate symbol "evutil_secure_rng_add_bytes" referenced by "/data/data/com.termux/files/usr/bin/tor"...
Aborted
$

**Comment by mrzarvan** [comment]
after upgrading i encountered this problem too!

**Comment by Grimler91** [comment]
That symbol seem to be part of libevent, so please check if `LD_PRELOAD=$PREFIX/lib/libevent.so tor` works as a workaround

**Comment by HoangPhantom** [comment]
Ok how do I check

**Comment by HoangPhantom** [comment]
When I enter that in, it still display the same error message

**Comment by TheT3ngu** [comment]
Having the same problem with tor 0.4.0.5 for aarch64.
`LD_PRELOAD=$PREFIX/lib/libevent.so tor` results also in `CANNOT LINK EXECUTABLE "tor": cannot locate symbol "evutil_secure_rng_add_bytes" referenced by "/data/data/com.termux/files/usr/bin/tor"...`

**Comment by HoangPhantom** [comment]
The lib file is not blue nor green. Is that the reason why?

**Comment by xeffyr** [comment]
> The lib file is not blue

Shared library is not a directory.

> nor green. 

Executable bit is useless for shared libraries.

**Comment by HoangPhantom** [comment]
When I try to go in the file and see, I can not see the "evutil_secure_rng_add_bytes" thing in the lib file. Can you double check?

**Comment by HoangPhantom** [comment]
When I search for the text of course

**Comment by xeffyr** [comment]
> When I try to go in the file and see, I can not see the "evutil_secure_rng_add_bytes" thing in the lib file. 
When I search for the text of course

You shouldn't search for text in such files. Use
```
objdump -T /path/to/file | grep symbol_name
```

Updated version of libevent doesn't contain this symbol:
```
[~]:$ objdump -T $PREFIX/lib/libevent.so | grep evutil_secure_rng
000000000001fdb8 g    DF .text  0000000000000004  Base        evutil_secure_rng_get_bytes
000000000001fd98 g    DF .text  0000000000000018  Base        evutil_secure_rng_init
000000000001fd90 g    DF .text  0000000000000008  Base        evutil_secure_rng_set_urandom_device_file
```
and `tor` should be recompiled. Trick with `LD_PRELOAD` will not help for obvious reasons.

**Comment by xeffyr** [comment]
Tor is fixed for for android-7/bintray repository and android-5/termux.net is [in progress](https://github.com/termux/termux-packages/pull/3908).

**Comment by HoangPhantom** [comment]
Thank you very much

**Comment by huitc** [comment]
+1

```
CANNOT LINK EXECUTABLE "tor": cannot locate symbol "evutil_secure_rng_add_bytes" referenced by "/data/data/com.termux/files/usr/bin/tor"...
```

**Comment by huitc** [comment]
termux 72
termux api 33

**Comment by fornwall** [comment]
The updated tor package (at version `0.4.0.5-1`) is now available everywhere - run `pkg up` to update!
