### ISSUE TITLE
Package (command) request： getent 

### ISSUE THREAD

**Issue by Justsoos** [termux/termux-packages#3909]
I found command 'getent' actually existed ever in termux, like: https://github.com/termux/termux-packages/blob/master/packages/zsh/compaudit.patch

and as the system resolve tool, now we have to use 'ping' to get the IP of hostname by some crazy cut or sed progress-afterwards and waiting for ping-pong even timeout, but 'getent ahosts' is the best for that way.

BTW, dig or nslookup are not alternatives, they are DNS resolve tools.

**Comment by xeffyr** [comment]
Executable `getent` is part of GNU libc. It also relies on glibc-specific stuff like nsswitch.conf etc...
