### ISSUE TITLE
Error in package: tinc

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-packages#3912]
When I try tinc, it doesn't contain the configuration file. Can you update it so that it contains all the needed files for the procedure. Thank you very much.

**Comment by xeffyr** [comment]
Official tinc distribution doesn't contain config file.
Want config file - supply the one working on Android by opening pull request.

**Comment by xeffyr** [comment]
I can add sample files, though tinc.conf will not be installed to `$PREFIX/etc`.

**Comment by HoangPhantom** [comment]
Ok, thank you very much
