### ISSUE TITLE
nodejs-lts: bad system call (statx)

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-packages#3915]
**Problem description**
The latest version (10.16.0) of package `nodejs-lts` fails with "bad system call".

**Steps to reproduce**
Transcript:
```
[~]:$ node -v
v10.16.0
[~]:$ node
> Bad system call
```

**Expected behavior**
Package should avoid use of `statx()` system call and therefore no crash in Termux.

**Additional information**
Strace:
```
23947 statx(21, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL,  <unfinished ...>
23947 --- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7371bf4b30, si_syscall=__NR_statx, si_arch=AUDIT_ARCH_AARCH64} ---
```
NodeJs current (v12.3.1) works fine without any crashes.

**Comment by Grimler91** [comment]
Perhaps same patch as we had [for nodejs](https://github.com/termux/termux-packages/commit/a75b2c7638378952378bb37ebfbfe628d4788ba3#diff-362ecac133389e07e9c4e17545bd98b7) needed?

**Comment by xeffyr** [comment]
Yes, it is.
