### ISSUE TITLE
Package request: Elixir

### ISSUE THREAD

**Issue by alanmaciel** [termux/termux-packages#392]
Elixir is a dynamic, functional language designed for building scalable and maintainable applications.

Elixir leverages the Erlang VM, known for running low-latency, distributed and fault-tolerant systems, while also being successfully used in web development and the embedded software domain.

[http://elixir-lang.org](http://elixir-lang.org)

**Comment by aurerua** [comment]
+1 With the growing attention that Elixir and Phoenix are getting, this would be awesome!

**Comment by bugQ** [comment]
+1 originally found termux wanting a way to do http://exercism.io problems on the go and learn new languages

**Comment by janfrs** [comment]
+1

**Comment by cdarne** [comment]
I've been able to run an Elixir project by building the erlang package from that PR https://github.com/termux/termux-packages/pull/439 and by downloading the latest precompiled Elixir package.

**Comment by gnagno** [comment]
+1

**Comment by charlenopires** [comment]
+1

**Comment by fornwall** [comment]
Thanks to @remvee an erlang package is now available. Install with:

    apt update && apt install erlang

**Comment by magoun** [comment]
@alanmaciel Were you able to get exercism running on Termux? I've gotten it installed (along with elixir, using the precompiled method mentioned in a previous comment), but I cannot fetch exercises - I keep getting a connection refused error. Based on some research, it looks like this may be a problem with installing exercism outside of the package manager inside Termux... not sure. Curious if you were able to get it running!

**Comment by onlurking** [comment]
I've manage to get Elixir up and running some time ago using the Precompiled:

```bash
mkdir "$HOME/.elixir" && cd "$HOME/.elixir"
curl -L https://github.com/elixir-lang/elixir/releases/download/v1.6.2/Precompiled.zip 2>/dev/null >Precompiled.zip
unzip -qq Precompiled.zip 1>/dev/null && rm Precompiled.zip && cd bin
termux-fix-shebang elixir elixirc iex mix
echo 'export PATH="$PATH:$HOME/.elixir/bin"' >>"$HOME/.profile"
cd "$HOME"
```

I even made a [installer with my dotfiles](https://github.com/onlurking/termux), for a straightforward installation: 
`curl -fsSL https://git.io/termux | bash -s -- --zsh --elixir`

**Comment by sdrausty** [comment]
Elixir is available today on device through Arch Linux in Termux PRoot:
```
$ pacman -Ss Erlang
community/ejabberd 18.01-1
    Jabber server written in Erlang
community/elixir 1.6.2-1
    a functional meta-programming aware language built on top of the Erlang VM
community/erlang 20.2-1
    General-purpose concurrent functional programming language developed by Ericsson
community/erlang-cl 1.2.1-4
    OpenCL binding for Erlang
community/erlang-docs 20.2-1
    HTML and PDF documentation for Erlang
community/erlang-nox 20.2-1
    General-purpose concurrent functional programming language developed by Ericsson
    (headless version)
community/erlang-sdl 1.3.1-2
    SDL and OpenGL bindings for Erlang
community/erlang-unixodbc 20.2-1
    Unixodbc support for Erlang
community/rabbitmq 3.7.3-2
    Highly reliable and performant enterprise messaging implementation of AMQP written in
    Erlang/OTP
community/rebar 1:2.6.4-1
    A sophisticated build-tool for Erlang projects that follows OTP principles.
community/yaws 2.0.4-3
    Web server/framework written in Erlang
```
*More information at https://sdrausty.github.io/TermuxArch/ 🎼🎶👷🐚🎺📯

**Comment by onlurking** [comment]
@sdrausty, sorry, but could you stop flooding all termux issues with your project?

**Comment by sdrausty** [comment]
@onlurking thanks for the input.  The goal is simple, from obscurity into the spotlight.  "Oh, I didn't know," nevermore!
1. Screenshot promotional was discontinued for Arch Linux in Termux PRoot - user input; on slow connections, it's easy to see.  

Synopsis, your comments are taken into account.

>  your project

One of our numerous Termux projects, join this small group of https://sdrausty.github.io/TermuxArch/CONTRIBUTORS if you like.  The huge textwall really hits home with:
```
$ pacman -Ss |wc -l                                                         
16838
```
How many packages is this?  How many programs?  How many package managers?
```
pacman -Ss |grep manager|grep package|wc -l                               
9
```

On an important side note for Termux packages that already run on device: Some of these Arch Linux packages work better than their Termux counterparts.  Why?

At times, there are a couple of Arch Linux in Termux PRoots running on only one device debugging TermuxArch.  Running Termux and Arch Linux in Termux PRoot in parallel seems like a very simple method to find out why programs like `imagemagik`, `perl`,  `python` and similar misbehave in Termux while behaving well in Termux PRoot.  This should be a priority.  I hope Elixir and Erlang users **do** enjoy the textwall you mentioned.

**Comment by LichP** [comment]
I got up and running quite nicely using the erlang packages and then installing precompiled elixir. One snag I did run into was with installing dependencies with mix - some of the erlang deps built with rebar would refuse to compile, which I managed to trace back to a hard-coded use of /tmp when rebar calls into erlang's insecure_mkdtemp function. Proot can be used to work round this problem:

`proot -b $TMPDIR:/tmp /data/data/com.termux/files/usr/bin/bash`

This gives you a shell with /tmp effectively bind mounted to Termux's tmp dir, and `mix deps.compile` should then work (solved it for me installing httpoison in the issues project from the Programming Elixir book)

**Comment by Serkan-devel** [comment]
Any progress on elixir support

**Comment by xeffyr** [comment]
Package is now available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install elixir
```

Based on prebuilt binaries from https://github.com/elixir-lang/elixir/releases.
