### ISSUE TITLE
cannot find package: libglib2.0-dev though it is available in scripts

### ISSUE THREAD

**Issue by arushijain45** [termux/termux-packages#3922]
While installing for `libglib2.0-dev`, getting error: `package not found` but I found that it is written in the [script](https://github.com/termux/termux-packages/blob/master/scripts/setup-ubuntu.sh).

**Comment by Grimler91** [comment]
It's called [glib](https://github.com/termux/termux-packages/tree/master/packages/glib). The script you linked is the script for setting up a cross-compilation environment in ubuntu, not in termux.
