### ISSUE TITLE
gdb segfault when breakpoints are set

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#3925]
**Problem description**
gdb segfaults when a program is run with breakpoints set at addresses other than *main.
It give following warning before crashing :

```
warning: Unable to determine the number of hardware watchpoints available.
warning: Unable to determine the number of hardware breakpoints available.
```

**Steps to reproduce**
1 load program in gdb `gdb prog`
2 set breakpoint somewhere in prog address (other than *main)
3 run 

**Expected behavior**
gdb should hit breakpoint

**Additional information**
System information:
Linux localhost 3.10.84-perf+ #1 SMP PREEMPT Tue Oct 24 01:07:25 CST 2017 aarch64 Android
Termux-packages arch:
aarch64
Android version:
6.0.1

**Comment by xeffyr** [comment]
Android 5 (ARM):
```
Reading symbols from ./a.out...
(gdb) b *0x51c
Breakpoint 1 at 0x51c: file test.c, line 11.
(gdb) run
Starting program: /data/data/com.termux/files/home/a.out 

[1]+  Stopped                 gdb ./a.out
```

Android 8 (ARM):
```
Reading symbols from ./a.out...
(gdb) b *0x51c
Breakpoint 1 at 0x51c: file test.c, line 11.
(gdb) run
Starting program: /data/data/com.termux/files/home/a.out 
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x51c
```

It crashes on Android 5 but not on Android 8.

***

Note about "cannot access memory" - it likely not relevant to GDB's crash since printed on PC as well.

**Comment by Auxilus** [comment]
Hi, "cannot insert breakpoint" and "cannot access memory" happen every time on all binaries, it doesn't crash gdb but it doesn't insert breakpoint either so somewhat voids the purpose of debugging... any workarounds on that?

System information:
Linux localhost 4.14.62-16641116 #1 SMP PREEMPT Fri Sep 20 10:32:09 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung

**Comment by Auxilus** [comment]
ptrace(PTRACE_PEEKTEXT, 31989, 0x698, 0x7fe4089710) = -1 EIO (I/O error)    ptrace(PTRACE_PEEKTEXT, 31989, 0x698, 0x7fe40898c0) = -1 EIO (I/O error)

while using strace it has this followed by 
`ioctl(1, TCSBRK, 1)                     = -1 EACCES (Permission denied)` right before throwing tge warnings above

**Comment by Auxilus** [comment]
Hi, it looks to me the addresses are mapped after I run the thing, so any breakpoints set beforehand just cause warning and automatic break, I again disassemble to get new addresses and set breakpoint where I want to with that, delete old breakpoint and rerun the program. it seems to work with this procedure, but my question is why does it have to switch addresses after I run the thing? it didn't happen to me on ubuntu..

**Comment by Auxilus** [comment]
Seens to me that running the program once without any breakpoints "corrects" the addresses, and if I do `disassemble` it shows correct addresses, and after that breakpoints work just fine

**Comment by xeffyr** [comment]
`ioctl(1, TCSBRK, 1) = -1 EACCES (Permission denied) right before throwing tge warnings above` - SELinux.
