### ISSUE TITLE
I can't install packegas matespapt-get install metasploit-framewor Reading package lists... Done Building dependency tree Reading state information... Done E: Unable to locate package metasploit-framewor root@localhost:~# apt-get install metasmetasploit-framework Reading package lists... Done Building dependency tree Reading state information... Done E: Unable to locate package metasmetasploit-framework 

### ISSUE THREAD

**Issue by 1111drt** [termux/termux-packages#3926]
And also can't do git clone
$ git clone https://github.com/Rajkumrdusad/Tool-
Cloning into 'Tool-'...
Username for 'https://github.com': 1111drt
Password for 'https://1111drt@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/Rajkumrdusad/Tool-/' not found
$

**Comment by Grimler91** [comment]
You are trying to clone a non-existent repo

**Comment by Grimler91** [comment]
See https://wiki.termux.com/wiki/Metasploit_Framework for how to install metasploit
