### ISSUE TITLE
Can't install Packages

### ISSUE THREAD

**Issue by xXSudipXx** [termux/termux-packages#3927]
Hi I recently installed termux and when I tried the command "pkg install php" it was just stuck in 0% working.  Please help me with this. My internet was switched on and my internet is LTE with 3mbps speed so why is this happening?

**Comment by Grimler91** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/3872

**Comment by SoumyadeepChatterjee96** [comment]
The issue isn't resolved yet and the thread is being closed continuously. Why? Even mine was.

**Comment by xXSudipXx** [comment]
I know how to solve now just open a new session and then try again

**Comment by xeffyr** [comment]
> The issue isn't resolved yet 

Device-specific issues can't be resolved.

**Comment by xeffyr** [comment]
I will also close other issues related to OpenSSL problem with MSM8916-based devices.

***

Try different ROMs and kernels... there no other way. Because fixing broken OS components goes too far from Termux scope.
