### ISSUE TITLE
Net not working 

### ISSUE THREAD

**Issue by harshyosoni** [termux/termux-packages#3932]
**Problem description**
 i have a problem with the termux app that when i start termux it dont use or consume any net,also i cant be able to download any packages in the termux i unistall and then install it many times but the problem is remain same. 

**Steps to reproduce**
Everything which i want to download or which needs net not working 
Pkg install git 
It stuck on 0% and moving further
Ping also not working 

**Expected behavior**
It have to download and net is suppose to work with termux, 

**Additional information**
Command `termux-info`.

Depending on problem, additional information may be requested:

1. When i try to install nmap
$ pkg install nmap
Reading package lists... Done
E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again)
E: Unable to lock directory /data/data/com.termux/files/usr/var/lib/apt/lists/
![Screenshot_2019-06-09-14-15-19-56](https://user-images.githubusercontent.com/36041841/59157005-89fea900-8ac1-11e9-99f3-3d370bf246f2.png)
![Screenshot_2019-06-09-14-15-07-71](https://user-images.githubusercontent.com/36041841/59157007-89fea900-8ac1-11e9-8084-eb259e60825e.png)
![Screenshot_2019-06-09-14-13-18-39](https://user-images.githubusercontent.com/36041841/59157008-8a973f80-8ac1-11e9-84d6-8db4967edf42.png)
![Screenshot_2019-06-09-14-12-58-00](https://user-images.githubusercontent.com/36041841/59157009-8a973f80-8ac1-11e9-9fa5-6ab761bb799d.png)
![Screenshot_2019-06-09-14-12-53-18](https://user-images.githubusercontent.com/36041841/59157010-8b2fd600-8ac1-11e9-84da-f54d36b72490.png)
![Screenshot_2019-06-09-13-56-38-28](https://user-images.githubusercontent.com/36041841/59157011-8b2fd600-8ac1-11e9-875a-a6228db68229.png)

**Comment by xeffyr** [comment]
What is your device model ?

**Comment by harshyosoni** [comment]
Oppo a37f, but i use termux since 2017 that problem i never face but this
month when i install it the problem occur

**Comment by xeffyr** [comment]
Hmm, it is based on `Qualcomm MSM8916 Snapdragon 410`, so... you are out of luck.

Related issues:
* https://github.com/termux/termux-packages/issues/3903
* https://github.com/termux/termux-packages/issues/3872

Most of devices based on MSM8916 have strange problem with OpenSSL.

**There no solution for the issue from Termux side.**

**Comment by xeffyr** [comment]
> i use termux since 2017 that problem i never face

Likely OpenSSL update. But since it happens only on MSM8916, likely there some conflict with ROM or kernel.

Since OpenSSL is critical, it will not be downgraded.
