### ISSUE TITLE
Issues regarding pkg managers

### ISSUE THREAD

**Issue by deoryus** [termux/termux-packages#3940]
apt and pkg commands both stuck at working [0%] as shown in ss.
update, install, search, download provide same result.
![Screenshot_2019-06-10-14-30-53-84](https://user-images.githubusercontent.com/43287620/59186836-56895080-8b8d-11e9-8dd4-0f1955d97973.png)

**Comment by Grimler91** [comment]
See #3872

**Comment by SoumyadeepChatterjee96** [comment]
Can you tell me the device name?

**Comment by deoryus** [comment]
oppo a37
