### ISSUE TITLE
sshd_config PrintMotd yes doubles output, no still gives it once

### ISSUE THREAD

**Issue by kaefert** [termux/termux-packages#3941]
**Problem description**
It seems the default config file used when starting `sshd` on termux is `/data/data/com.termux/files/usr/etc/ssh/sshd_config`
This contains `PrintMotd no` by default and still print's a lot of info on an interactive ssh login. Changing this to `PrintMotd yes` will make it print the whole info block twice instead.

**Steps to reproduce**
* check to see if `/data/data/com.termux/files/usr/etc/ssh/sshd_config` cotains `PrintMotd yes` or `PrintMotd no`.
* Start sshd and perform a login.
* Observe the described behavior for the currently configured value.
* Toggle the `PrintMotd` option in sshd_config, restart sshd and observe the other behavior.

**Expected behavior**
The `PrintMotd` option should control if that info block is displayed zero ore one time. not one or two times.

**Additional information**
```
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.14.29 #14 SMP PREEMPT Fri Jan 20 09:53:59 CST 2017 armv8l Android
Termux-packages arch:
arm
Android version:
6.0.1
Device manufacturer:
Amlogic
Device model:
MBOX
```

**Comment by xeffyr** [comment]
It's not SSH issue.
https://github.com/termux/termux-packages/blob/master/packages/termux-tools/login#L4

**Comment by xeffyr** [comment]
Do `touch ~/.hushlogin` to disable motd if you don't need it.

**Comment by kaefert** [comment]
Yes, I understand there are way's to get around it. I just think it would be nice to be as close to "default behaviour" as possible.
Why is there an "our login program" that shows login info already, instead of using the default way with the PrintMotd sshd config option?

**Comment by xeffyr** [comment]
Because login script is the only way to execute some stuff at pre-login step, for now we need:

1. Select login shell chosen by user with `chsh`.
2. Check whether termux-exec hook is working.

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/7e88992f9d468681812f8b1b98f14b8c489ebe6d.

Now `PrintMotd no` should disable printing of motd completely. Though, the `PrintMotd` will be `yes` by default.
