### ISSUE TITLE
mandb not found

### ISSUE THREAD

**Issue by apolbox** [termux/termux-packages#3945]
![Screenshot_2019-06-12-12-50-51-912_com termux](https://user-images.githubusercontent.com/15851262/59326476-ddb30180-8d10-11e9-84ed-7075d0d4faa6.png)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
In Termux `mandb` is replaced with `mandoc` from package `man`.

btw, answer was in your screenshot:
![59326476-ddb30180-8d10-11e9-84ed-7075d0d4faa6](https://user-images.githubusercontent.com/25881154/59338178-90339600-8d0a-11e9-8ee6-f7083172c324.png)
