### ISSUE TITLE
pip not installed with python

### ISSUE THREAD

**Issue by deoryus** [termux/termux-packages#3946]
When I manually install python2 via dpkg, It's installed and working fine but not pip.
As seen in ss, pip2 return "illegal instruction" while setting up. What could go wrong.?
And I can't use apt-get either since there's bug regarding MSM8916 chipset so manually installing is my only option.

Device is Oppo a37.
![Screenshot_2019-06-12-15-29-43-28](https://user-images.githubusercontent.com/43287620/59344723-14e0dd00-8d28-11e9-8b51-b0a7cc75c223.png)

**Comment by xeffyr** [comment]
Try workaround from https://github.com/termux/termux-packages/issues/3872#issuecomment-500235125.

***

And since OpenSSL is not working on your device, you can't make https connections and therefore `pip` cannot be installed.
