### ISSUE TITLE
Package Request: proxychains-ng

### ISSUE THREAD

**Issue by BrainDamage** [termux/termux-packages#395]
https://github.com/rofl0r/proxychains-ng is a program that lets you create chains of proxies and wrap api calls of another to enforce a proxy usage for a program that doesn't

**Comment by Neo-Oli** [comment]
This package was already requested at https://github.com/termux/termux-packages/issues/330

**Comment by wolfwar22** [comment]
Hi masters.. how to add proxy pass.txt on termux??
Please learning me
