### ISSUE TITLE
sftp logging to file

### ISSUE THREAD

**Issue by kaefert** [termux/termux-packages#3950]
Hi there!

I managed to customize my sshd logging using this line:
`sshd -De 2>&1 | while read line; do log "$line"; done &`

I would like to also get sftp logging into my own logging function or my own logfile.

I found this config line in sshd_config:
`Subsystem sftp /data/data/com.termux/files/usr/libexec/sftp-server -f USER -l INFO`
I've tried the -f log_facility options DAEMON, USER & leaving it at default (AUTH) - But all just make the log entries go through syslog into the Android logcat system.

Can I somehow manipulate this?

**Comment by xeffyr** [comment]
`sshd` can print logs to file or stderr but seems there no way to capture output from `sftp-server`.
