### ISSUE TITLE
pkg and apt install not work , always stuck in 0% Working

### ISSUE THREAD

**Issue by fdciabdul** [termux/termux-packages#3956]
How to fix it ? 
![Screenshot_20190616_214245](https://user-images.githubusercontent.com/31664438/59565707-e2fdac80-9080-11e9-9f31-26968e9ddfcd.png)
i tried pkg install or apt install still not working 
always show 0% working

when i write logcat -d
 that's showing

--------- beginning of main
W/InputMethodManager( 3147): startInputInner : InputBindResult == null
W/IInputConnectionWrapper( 3147): showStatusIcon on inactive InputConnection
W/IInputConnectionWrapper( 3147): showStatusIcon on inactive InputConnection
D/yuan    ( 3147): onVisibilityChanged----android.widget.ListView{c237e83 VFED.VCL ......ID 0,0-360,395 #7f050010 app:id/left_drawer_list}
D/yuan    ( 3147): onVisibilityChanged----android.widget.ListView{c237e83 VFED.VCL ......ID 0,0-360,395 #7f050010 app:id/left_drawer_list}
$

i don't understand that

**Comment by xeffyr** [comment]
Duplicateof https://github.com/termux/termux-packages/issues/3872.
