### ISSUE TITLE
Build packages with large files support, please (BusyBox, p7zip, unzip)

### ISSUE THREAD

**Issue by Efreak** [termux/termux-packages#3959]
I've got a >2gb zip file I need to work with, and neither `unzip` nor `p7zip` are working with it. The zip file contains a large number of smaller files (approximately 1500), mostly in zip format, and has compression set to 'store'. It can easily be viewed and extracted using other apps, however that doesn't help when I need to work with them using the terminal (I'd like to remove them, modify them, then update the archive; I've got a script that automates much of this already)

```
$ 7z x CalC.zip

7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=off,32 bits,4 CPUs LE)

Scanning the drive for archives:
1 file, 2188421612 bytes (2088 MiB)

Extracting archive: CalC.zip
ERROR: CalC.zip
Can not open the file as archive

E_FAIL

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
$ unzip CalC.zip
Trying to read large file (> 2 GiB) without large file support
$ busybox unzip CalC.zip
Archive:  CalC.zip
unzip: short read
$
```

**Comment by Efreak** [comment]
I can bypass issues using root and stericson's BusyBox installer, however this isn't very useful on unrooted devices, and will break as soon as my next Android update removes BusyBox.

**Comment by xeffyr** [comment]
> I can bypass issues using root and stericson's BusyBox installer

Stericson's busybox is different and linked against different libc,, don't know exactly which is, but definetly non Bionic. We link all our packages with Bionic libc which applies limits on 32-bit packages.

Issue well described at https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md

**Comment by basilgello** [comment]
Possibly the same issue with latest p7zip: 
[1.txt](https://github.com/termux/termux-packages/files/3843802/1.txt)

Archive with 19 or 20 random files * 1048576 bytes eachbis created just fine but compressing 21 files produces broken archive.

The same behavior is reproduced also on LineageOS-bundled 7-zip 15.06 (LineageOS 14.1 on Samsung Galaxy Tab S (chagalllte, armv7l])

**Comment by Efreak** [comment]
I haven't fixed my issue, I simply worked around it for the time being by using multiple smaller archives.

I'm currently in the middle of building several crosstools-ng configs targeted at my tablet (Nvidia shield k1; mtune cortex15, mfpu neon-vfp4 iirc, at least one is gnueabihf. I really have no idea what I'm doing or if this will work). I wish there was a script I could run on the target device to configure crosstools... Mostly I just want to build a bunch of stuff that has no arm binaries available, without abusing my tablet.

If you're interested, ping me in a few days; in the meantime, I'll try statically building 7zip if one of the builds actually finishes (the last two had issues with building ncurses and libssl). My laptop's a bit slow, and I'm quite lazy though, so don't expect a quick turnaround.

**Comment by basilgello** [comment]
@Efreak Since LineageOS is built from source and prebuilt clang-2690xxxx from 14.1 supports `__FILE_OFFSET_BITS=64`, I just made the following change https://review.lineageos.org/q/topic:"p7zip-hugefiles" and rebuilt 7zip in Lineage. Now I do have working 7zip.

As for NDK build ised in Termux, I might add an NDK patch or package patch but I want to double check which API the build targets.
