### ISSUE TITLE
Crackling audio on pulseaudio when screen off and pulseaudio started locally

### ISSUE THREAD

**Issue by S-trace** [termux/termux-packages#3963]
**Problem description**
I'm using PulseAudio with module-native-protocol-tcp to stream audio from PC to Android device.

When i'm starting pulseaudio using Termux application locally, when screen is on - audio quality is good, but when screen is off audio quality is bad, with lots of audio glitches, outages and crackling.

But when i'm starting pulseaudio on the Android device using SSH into Termux session - audio quality with screen off is still good, just like when screen is on, even if i put pulseaudio to background using pulseaudio and then ^Z + bg&disown and pkill sshd.

The same problem sometimes happens when starting pulseaudio&disown command using SSH. But not always.
Using "Acquire wakelock"  in Termux notification does not help (the wakelock is already held by audio output).

**Steps to reproduce**
On Android (192.168.0.3):
1. pkg install pulseaudio
2. pulseaudio&
3. pacmd load-module auth-ip-acl=192.168.0.2

On PC (192.168.0.2):
1. pacmd load-module module-tunnel-sink-new server=192.168.0.3
2. Play audio using tunnel sink to the Android
3. Listen audio on Android

**Expected behavior**
A clear sound regardless of way pulseaudio was started.

**Additional information**
```
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.148-perf+ #1 SMP PREEMPT Tue Feb 19 13:43:00 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Sony
Device model:
G8441
```

**Comment by xeffyr** [comment]
Wifi connection isn't stable when screen is off, there a lot of packet loss due force-enabled powersaving at kernel level. Issue causes problems not only with streaming. For example I have lags when SSH'ing into Termux when device screen is off.

Seems like wifi wakelock enabled at https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/TermuxService.java#L112 useless or does its work in a different way.

I'm running following command in a separate session as workaround `ping -i 0.3 -s 0 192.168.1.1`, solution isn't good but works for me.

**Comment by tomty89** [comment]
Cannot reproduce here. Can't really make sense out of the case anyway. Maybe it has something to do with the power saving feature of your ROM. Maybe you can add Termux as an exception and see if it helps.

If you want to investigate, you can start pulseaudio with `--log-level=debug` and `--log-target=newfile:PATH` and report back with the logs in different cases.

Also you don't need `&` or `disown`or so. There's `-D`.

P.S. I'm assuming the wifi problem @xeffyr mentioned isn't the cause. I experienced lags when ssh into my phone but I am not experiencing your problem.
