### ISSUE TITLE
Package Request: tzdata

### ISSUE THREAD

**Issue by grantbow** [termux/termux-packages#3971]
**Package description**
standard local time data

**Link to home page and sources**
1. Home page: https://packages.debian.org/tzdata
2. Source code: https://packages.debian.org/source/sid/tzdata

**Comment by xeffyr** [comment]
Will not be implemented as Termux based on libc from Android. Used tzdata is located at `/system/usr/share/tzdata`.

If you want to change timezone, do this either via Android settings or set environment variable `TZ`.

**Comment by grantbow** [comment]
Thank you very much for the fast and clear explanation. The Android "[bionic](https://en.wikipedia.org/wiki/Bionic_(software))" libc handles this differently than glibc. The real issue I encountered was [golang/go#20455](https://github.com/golang/go/issues/20455) which hard codes UTC in golang on Android/Chrome OS even when TZ is set. In case anyone else is interested I worked around this by setting `export TZ="$(getprop persist.sys.timezone)"` in my bashrc and in my golang program (edited a bit for brevity) `tz := os.Getenv("TZ")` then `loc, _ = time.LoadLocation(tz)` and finally ...time.Time`.In(loc)`...

**Comment by markbaas** [comment]
I would like to reopen this issue. The zoneinfo I got on emui 8 was very limited. The R package readr was unable to detect any timezones. Recompiling the package directly from https://www.iana.org/time-zones fixes the problem.

The right approach would hereby be to at least offer the packages, and when installed set the TZDIR to the appropiate folder.

**Comment by xeffyr** [comment]
@markbaas Please note that "normal" tzdata package is not compatible with Bionic libc. Switching it would be difficult and I won't bother to maintain time-zone patches for all packages relying on time info.

Timezones in R is another issue and I also should point that `R` is not official Termux package.
