### ISSUE TITLE
Can not install gritty (nodejs package)

### ISSUE THREAD

**Issue by maytinhdibo** [termux/termux-packages#3972]
Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:195:16: warning: 'BooleanValue' is
      deprecated: BooleanValue can never throw. Use
      Isolate version. [-Wdeprecated-declarations]
  if (info[8]->BooleanValue(Nan::GetCurrentCo...
               ^
/data/data/com.termux/files/home/.node-gyp/12.4.0/include/node/v8.h:2561:3: note:
      'BooleanValue' has been explicitly marked
      deprecated here
  V8_DEPRECATED("BooleanValue can never throw...
  ^
/data/data/com.termux/files/home/.node-gyp/12.4.0/include/node/v8config.h:307:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/unix/pty.cc:495:21: warning: 'Call' is
      deprecated [-Wdeprecated-declarations]
  Nan::Callback(cb).Call(Nan::GetCurrentConte...
                    ^
../../nan/nan.h:1651:3: note: 'Call' has been
      explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro
      'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings generated.
  SOLINK_MODULE(target) Release/obj.target/pty.node
clang-8: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: cannot find -lutil
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [pty.target.mk:135: Release/obj.target/pty.node] Error 1
make: Leaving directory '/data/data/com.termux/files/home/MDE/node_modules/node-pty/build'

**Comment by huitc** [comment]
how can I install wpscan?😅😅
https://github.com/wpscanteam/wpscan

**Comment by tomty89** [comment]
https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_setup_toolchain.sh#L158-L163

We should probably include the linker script in ndk-sysroot (and switch to the same approach for `-lpthread` and `-lrt`.

**Comment by tomty89** [comment]
I don't understand why they are not changed into linker scripts.
