### ISSUE TITLE
opencv on my android cellphone, clang-8: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by michaeldengxyz** [termux/termux-packages#3974]
I followed up this instruction to install opencv on my android cellphone
Android 5.0.1
Linux version 3.4.0-4745659 
-------------------------------------
1. Install python3 and dev
     pkg install python python-dev
2. Install tools and libs
     pkg install libjpeg-turbo-dev libpng-dev cmake pkg-config
3. Clone opencv from git
    git clone https://github.com/opencv/opencv && cd opencv
4. Create build directory
     mkdir build && cd build
5. Configure
    LDFLAGS=" -llog -lpython3" cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_opencv_python3=on -DBUILD_opencv_python2=off -DWITH_QT=OFF -DWITH_GTK=OFF -DBUILD_TESTS=OFF ..

    Don't missing the double dot at the end of command, It means start from the parent folder. 
    After success, execute the following command:
        make
        make install
        Please be noted that make will take a long time.
6. After installed, test it in python
     python
     >>> import cv2
     >>>cv2.__version__
    If no error it will print the version
-------------------------------------
**but when i did make in the step#5, then got:**
$ make
[  4%] Built target libtiff
[ 15%] Built target libwebp
[ 19%] Built target libjasper
[ 29%] Built target IlmImf
[ 36%] Built target libprotobuf
[ 36%] Built target quirc
[ 41%] Built target carotene_objs
[ 42%] Built target tegra_hal
[ 43%] Built target ade
[ 43%] Built target opencv_videoio_plugins
[ 51%] Built target opencv_core
[ 57%] Built target opencv_imgproc
[ 59%] Built target opencv_imgcodecs
[ 60%] Built target opencv_videoio
[ 60%] Built target opencv_highgui
[ 61%] Built target opencv_ts
[ 61%] Linking CXX executable ../../bin/opencv_perf_core
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_ts.a(ts_perf.cpp.o): in function `cv::operator<<(std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >&, cv::Mat const&)':
ts_perf.cpp:(.text._ZN2cvlsERNSt6__ndk113basic_ostreamIcNS0_11char_traitsIcEEEERKNS_3MatE+0xb8): undefined reference to `__atomic_fetch_add_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ts_perf.cpp:(.text._ZN2cvlsERNSt6__ndk113basic_ostreamIcNS0_11char_traitsIcEEEERKNS_3MatE+0xdc): undefined reference to `__atomic_fetch_add_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ts_perf.cpp:(.text._ZN2cvlsERNSt6__ndk113basic_ostreamIcNS0_11char_traitsIcEEEERKNS_3MatE+0x198): undefined reference to `__atomic_fetch_add_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ts_perf.cpp:(.text._ZN2cvlsERNSt6__ndk113basic_ostreamIcNS0_11char_traitsIcEEEERKNS_3MatE+0x1d8): undefined reference to `__atomic_fetch_add_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `__atomic_fetch_sub_8'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_imgcodecs.so.4.1.0: undefined reference to `__atomic_fetch_sub_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `__atomic_store_8'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_imgcodecs.so.4.1.0: undefined reference to `__atomic_load_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `__atomic_load_8'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `__atomic_store_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_imgcodecs.so.4.1.0: undefined reference to `__atomic_compare_exchange_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `__atomic_compare_exchange_8'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `__atomic_load_1'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `__atomic_store_1'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../lib/libopencv_core.so.4.1.0: undefined reference to `__atomic_fetch_add_8'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld generated: undefined reference to `__atomic_fetch_add_4'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [modules/core/CMakeFiles/opencv_perf_core.dir/build.make:542: bin/opencv_perf_core] Error 1
make[1]: *** [CMakeFiles/Makefile2:1382: modules/core/CMakeFiles/opencv_perf_core.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**If you help me out, i'm really appreciated!**

**Comment by its-pointless** [comment]
Need to add "-latomic" to ldflags
