### ISSUE TITLE
: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again) E: Unable to lock directory /d

### ISSUE THREAD

**Issue by miniact** [termux/termux-packages#3976]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
Just don't run multiple instances of package manager at same time.

Also try
```
rm -rf $PREFIX/var/lib/apt/lists/lock
```

**Comment by miniact** [comment]
When ever I try to install package
It only shows working and no installation done

**Comment by xeffyr** [comment]
> It only shows working and no installation done

https://github.com/termux/termux-packages/issues/3872

**Comment by viperr8000** [comment]
> > It only shows working and no installation done
> 
> #3872

Goto youtube
Press share/forward
Select Termux
It will download

**Comment by Shohag80** [comment]
E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again)
How ho solved this problem..
