### ISSUE TITLE
Package Request: Phoenix framework

### ISSUE THREAD

**Issue by alanmaciel** [termux/termux-packages#398]
Phoenix is a web development framework written in Elixir which implements the server-side MVC pattern. Many of its components and concepts will seem familiar to those of us with experience in other web frameworks like Ruby on Rails or Python's Django.

[http://www.phoenixframework.org/](http://www.phoenixframework.org/)

**Comment by Serkan-devel** [comment]
Would be great to do web development everywhere. Elixir is also more memory efficient than Ruby
