### ISSUE TITLE
php xsl

### ISSUE THREAD

**Issue by johnss** [termux/termux-packages#3983]
**Problem description**
i need to install composer packages that require xsl but failed because xsl disabled

**Steps to reproduce**
im trying to install theseer/phpdox by using `php path/to/composer.phar require theseer/phpdox` but failed

**Expected behavior**
should succesfully install without any problem

**Comment by merbst** [comment]
I too am missing a few php extensions in their absence!
My top priorities would be:
"ext-gmp": ">=7.3",
"ext-pdo_mysql": ">=7.3",
"ext-pdo_pgsql": ">=7.3",
"ext-pdo_sqlite": ">=7.3",
"ext-pgsql": ">=7.3"
And of course ext-xsl to brighten John's day!

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/5fbcf1c857786fc33fce9720b7b2094f726987d3.
