### ISSUE TITLE
slabtop missing from procps package

### ISSUE THREAD

**Issue by kerneltoast** [termux/termux-packages#3984]
Extracting `procps_3.3.15-2_aarch64.deb` shows that slabtop, which is a part of procps, is missing.

**Comment by xeffyr** [comment]
`slabtop` is removed from package, see https://github.com/termux/termux-packages/blob/master/packages/procps/build.sh#L26.

It just doesn't work.
```
[~]:$ slabtop
fopen /proc/slabinfo: No such file or directory
```

**Comment by kerneltoast** [comment]
It just requires kernel support in order to work. I was planning on using it with a modified kernel that has slabinfo exposed.
