### ISSUE TITLE
Unable to run Dnscrypt-proxy in Termux on a not-rooted Android: Permission denied

### ISSUE THREAD

**Issue by majiayeah** [termux/termux-packages#3986]
Hi,

I was trying to run Dnscrypt-proxy in Termux on a not-rooted Android, but failed.

Termux output: Permission denied

Dnscrypt-proxy is a tool from: https://github.com/jedisct1/dnscrypt-proxy
and it is reported that this tool runs fine on Termux. (see https://github.com/jedisct1/dnscrypt-proxy/issues/41)

My steps are:
1. download and upzip the Dnscrypt-proxy binary in the release page, with the correct platform.
2. put the binary in ./storage/downloads/dnscrypt-proxy/
3. modify the configuration file of dnscrypt-proxy to listen to 127.0.0.1:5353
4. go into the folder, and run ./dnscrypt-proxy

output: 
bash: ./dnscrypt-proxy: Permission denied.

Could anyone know how to successfully run dnscrypt-proxy in Termux on a not-rooted Android?

**Comment by xeffyr** [comment]
You can't execute binaries from sdcard (shared storage).
Download the binary to $HOME, run `chmod +x` on it and it should work.
