### ISSUE TITLE
Auto upgrade(if any) - how to disable.

### ISSUE THREAD

**Issue by gridmeister** [termux/termux-packages#3989]
I have a experimental distributed network of android devices (very cheap Chinese boxes)  that I control using termux ssh. During half a year of experimentation I notice errors with installations  such as "CANNOT LINK EXECUTABLE ... cannot locate symbol xxxx" (like #3855 , #3283). It may be just my imagination but it begins after I start using crond from termux.

Does termux have some kind of auto-upgrade system? If so - how to disable it? If not - please advice, I have some kind of disk/ssd problems on devices?

**Comment by xeffyr** [comment]
Termux never has and never will have **automatic package upgrade**.
