### ISSUE TITLE
Fisher

### ISSUE THREAD

**Issue by 77XAH77** [termux/termux-packages#3992]
Нефига не работает выдает ошибку 
Время подключения истекло и всё точнее, пишем всё как надо 
Cd fisher 
Chmod 777 install.sh
Sh install.sh
И после этой команды(sh install.sh)
Выходит опрос фиг поймёшь что там
После всего 
Этого 
Fish
Run 
Создаём второе окно 
Пишем 
apt install openssh
Ssh -R 80:localhost:8080 
ssh.install.run
И нефига не работает, выдает ошибку время подключения истеклр

**Comment by xeffyr** [comment]
Скорее всего, у вас была ошибка при установке/запуске fisher.
Обращайтесь к автору программы, т. к. здесь нет поддержки по сторонним скриптам вроде "fisher".
