### ISSUE TITLE
java, javac interface for dalvikvm and ecj

### ISSUE THREAD

**Issue by zaoqi** [termux/termux-packages#3993]

**Comment by Harshiv-Patel** [comment]
for javac and/or ecj, either you can directly use `ecj` instead of `javac` or make a symlink of `ecj` named `javac` in `$PREFIX/bin` .

**Comment by HemanthJabalpuri** [comment]
@zaoqi

I made it here.
https://github.com/HemanthJabalpuri/run_java

**Comment by zaoqi** [comment]
@HemanthJabalpuri  `javac` generates `*.class`, not `*.dex`

**Comment by HemanthJabalpuri** [comment]
> @HemanthJabalpuri `javac` generates `*.class`, not `*.dex`

My script created .dex only not .class

**Comment by xeffyr** [comment]
java/javac is available through package `openjdk-17`.
