### ISSUE TITLE
Bash exits due to signal 14

### ISSUE THREAD

**Issue by bbqz007** [termux/termux-packages#3997]
the session closes itself at 3 or 5 seconds after i create it. it shows me the message that the process completed because of 
signal 14. 
![Screenshot_20190630-054141](https://user-images.githubusercontent.com/19798738/60389756-0f421000-9afa-11e9-92b8-d875cd56a66c.jpeg)

now i can not use it at all.
i do not know why. the version of my termux is 64. i installed it one year ago, and used it to work for at least 6 months. then i never used it. now i am going to use it, but it can not work normally.

**Comment by xeffyr** [comment]
@bbqz007 By looking on motd message, your installation appears to be old. The recent one shows:

![Screenshot_2019-06-30-01-14-41](https://user-images.githubusercontent.com/25881154/60389962-c166e100-9ad4-11e9-841d-f3eb8cd245f6.png)

I'm suggesting to erase Termux application data and see if the issue gone.

**Comment by DaBoss5** [comment]
Oh, Thanks. I'll remember that for future use.

**Comment by bbqz007** [comment]
thanks! good. the problem is temporarily solved.
