### ISSUE TITLE
wget not included in last version of busybox

### ISSUE THREAD

**Issue by rafaeln** [termux/termux-packages#4]
~~~
$ busybox | head -1
BusyBox v1.23.2 (2015-08-03 18:05:04 EDT) multi-call binary.
$ busybox wget
wget: applet not found
~~~

**Comment by fornwall** [comment]
The busybox wget applet was removed in favour of the full GNU wget program (having the busybox one initially confused a number of people).

Is installing the full wget with `apt install wget` an acceptable solution?

**Comment by rafaeln** [comment]
Oh, now I see that you actually purposefully excluded `wget` from `busybox` in commit 8e928b79be7024f825ad1754709662651e3d001c. And I think the reasons why you did so, which you gave in the commit message, are good and sound. But I also think the same reasons would apply for many other applets provided by `busybox`. They are all trimmed-down and slightly buggy versions of the real ones. Personally, I was satisfied with `busybox`'s `wget`, since I was only using it to download files via http through sketchy internet connections (--tries 100). I ended up doing `apt install wget` anyways, but since my device is running out of internal memory and I can't install on the SD card (for reasons beyond our control), I would have preferred to have the option of keeping `busybox`'s `wget`. It is your project, though, and if you think this is the best thing to do, then this is the best thing to do. You'll always be breaking someone's workflow:

![workflow](http://explainxkcd.com/wiki/images/b/b5/workflow.png "Xkcd comic")

**Comment by fornwall** [comment]
Yes, it's a balance as you say :). Perhaps an option is to not install wget (and similar busybox applets) as a symlink to busybox by default, but still have it availabe in busybox? This means:

- This will avoid confusing newcomers, since `wget` (and similar applets) won't be in their PATH before installing the full featured version.

- Advanced users who wants to save space can use `busybox wget` directly without installing the fully featured variants.

What do you think about that variant?

**Comment by rafaeln** [comment]
I hadn't thought about this variant solution. It would greatly satisfy me and the likes of me. I would only also suggest you create a default alias for `wget` that issues an error message along the lines of "use `apt install wget` to install wget or create an alias for `busybox wget` in `.profile`"

**Comment by fornwall** [comment]
Thanks for the discussion - I will look at this during the weekend and write here when I made a change!

**Comment by fornwall** [comment]
So, after thinking about it a bit more I've re-enabled wget in the busybox package `apt update && apt upgrade` should install the updated version 1.23.2-6 with wget included.

I will just have to be clear in the documentation that the base tools are busybox ones, and if more fully featured alternatives (wget, coreutils, psmisc, ..) they need to be installed manually!

**Comment by rafaeln** [comment]
Thanks. I'm pretty satisfied with the level of fuctionality provided by the busybox utils, and I agree that being more clear in the documentation is a better solution than removing every busybox util that isn't fully featured (probably all of them).
