### ISSUE TITLE
Package request: mono

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#40]
_From @archanox on November 2, 2015 16:7_

It would be fantastic if mono support was included in termux to at least run cli applications.

_Copied from original issue: termux/termux-app#9_

**Comment by fornwall** [comment]
Thanks for the suggestion! Will look into trying a cross compile soon, for future reference when looking into this:

- [Mono on ARM information](http://www.mono-project.com/docs/about-mono/supported-platforms/arm/)
- [Stackoverflow post about cross compiling to Android ARM](http://stackoverflow.com/questions/17941856/compile-mono-for-android-arm7)
- [Stackoverflow post about cross compiling to Android x86](http://stackoverflow.com/questions/27438837/how-to-cross-compile-mono-for-x86-android)

**Comment by fornwall** [comment]
I started a [wiki page to keep track of package suggestions](https://github.com/termux/termux-packages/wiki/Package-suggestions) and have added Julia there!

**Comment by Neo-Oli** [comment]
Hi, I am reopening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by 0xFireball** [comment]
What is the status of Mono?

**Comment by GabrielTK** [comment]
+1. Any progress in mono???

**Comment by GabrielTK** [comment]
Take a look at [this!!](https://github.com/cydhaselton/mono-android)

**Comment by gattila** [comment]
Is there any way to provide deb packages to the repository for this ?

**Comment by sdrausty** [comment]
Mono is available in Termux through PRoot Arch Linux. Tapping this link https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh will transfer the script to your device. Simply run `bash setupTermuxArch.sh` to install Arch Linux.  Then run `pacman -S mono`.  Enjoy 🎼

![screenshot_20171129-221559](https://user-images.githubusercontent.com/27742457/33411376-545dcf8a-d553-11e7-9743-db9ab6e67cd8.png)

**Comment by pollen5** [comment]
any updates to this? It's been years.

**Comment by IanusInferus** [comment]
Hey guys, I have compiled Mono for Termux without proot. Check out [termux-mono](https://github.com/IanusInferus/termux-mono).

**Comment by beginor** [comment]
@IanusInferus Can you create package for Termux? I think there will be others want to try it!

**Comment by IanusInferus** [comment]
@beginor It's a good idea, but there are a few difficulties. First, the class libraries can not be compiled on Android as they need a working mono to bootstrap, so it's copied from a Linux build. Second, a libc.so.6 symbol link is needed as many class libraries assume it.
Currently,  you can download the prebuilt files from my repo and add the symbol link to use, if you don't want to build by yourself.

**Comment by Mhowser** [comment]
Any updates to this?

**Comment by Mhowser** [comment]
@cydhaselton Any chance you can update your mono fork?

**Comment by SFM61319** [comment]
Any updates on this? Like `apt install mono` isn't a thing yet. It's been 5 years...

**Comment by ravener** [comment]
@SFM61319 https://github.com/IanusInferus/termux-mono works great in the meantime.

**Comment by masterjavaofficial** [comment]
Any update till now? ☹️
