### ISSUE TITLE
Package Request: Spacemacs

### ISSUE THREAD

**Issue by alanmaciel** [termux/termux-packages#400]
A community-driven Emacs distribution - The best editor is neither Emacs nor Vim, it's Emacs *and* Vim!

[http://spacemacs.org](http://spacemacs.org)

**Comment by kirillrdy** [comment]
spacemacs can already installed, its just a configuration for emacs.

**Comment by alanmaciel** [comment]
oh!  I'll try to install emacs and configure spacemacs tonight! Thanks

**Comment by kirillrdy** [comment]
https://github.com/syl20bnr/spacemacs
quick install
```
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

**Comment by alanmaciel** [comment]
Great!
