### ISSUE TITLE
/system/bin/mount doesn't work

### ISSUE THREAD

**Issue by Avevad** [termux/termux-packages#4002]
Attempt to execute /system/sbin/mount results in getting error:
`CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "OPENSSL_add_all_algorithms_noconf" referenced by "libselinux.so"...`
Expected to show all mounts

This executable worked before updating Termux to 0.72.

```
System information:
Linux localhost 3.10.9-9398224 #1 SMP PREEMPT Mon Nov 12 21:17:11 KST 2018 armv7l Android
Termux-packages arch:
arm
Android version:
5.1.1
Device manufacturer:
samsung
Device model:
SM-J120F
```

**Comment by fornwall** [comment]
Should be fixed by version 0.68 of termux-tools, run `pkg up` to update.

Thanks for reporting!
