### ISSUE TITLE
tunctl cannot locate /dev/net/tun

### ISSUE THREAD

**Issue by readyblue** [termux/termux-packages#4006]
**Problem description**
when user root tries to create virtual interface like this:
`# tunctl -t tun1`
it gets error:
`tunctl: /dev/net/tun: No such file or directory`

**Expected behavior**
Created interface if it does not exists already

**Comment by xeffyr** [comment]
1. Which package provide the command `tunctl` ?

2. The correct path of tun device on Android is `/dev/tun`.

**Comment by readyblue** [comment]
1. It seems, it is busybox, not sure. On Linux it is uml-utilities. (it is listed in #3594 )
2. Thanks

**Comment by xeffyr** [comment]
It is listed for different busybox, a system one located under /system/xbin. Our busybox does not provide `tunctl`:
```
[~]:$ busybox tunctl
tunctl: applet not found
```

Closing since issue is not related to our packages.
