### ISSUE TITLE
Radare2 issue

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-packages#4008]
Hello, when I type in radare2 filename or r2 filename in Termux, it just gives me back my shell. It doesn't output anything or give me the radare2 shell. I tried using radare2 --help and it doesn't even output a help message. I tried restarting Termux but the issue is still there. I hope you can fix it. Thank you.
![20190702_141601](https://user-images.githubusercontent.com/46418295/60491933-13c22080-9cd4-11e9-9936-b426e0f8b10d.png)

**Comment by xeffyr** [comment]
What is your output of `termux-info` ?

**Comment by HoangPhantom** [comment]
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.72 #1 SMP PREEMPT Tue Feb 16 18:23:49 CST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.1
Device manufacturer:
Lenovo
Device model:
Lenovo TB3-710I

**Comment by xeffyr** [comment]
>Termux-packages arch:
arm
Android version:
5.1
Device 

There happens linking error:
```
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "r_sys_truncate" referenced by "libr_hash.so"...
```

**Comment by HoangPhantom** [comment]
Can you fix it?

**Comment by its-pointless** [comment]
yep

**Comment by xeffyr** [comment]
Should be fixed by https://github.com/termux/termux-packages/pull/4013.
