### ISSUE TITLE
segmentation fault on scrapy

### ISSUE THREAD

**Issue by ccssrryy** [termux/termux-packages#401]
I installed `scrapy` by pip.when running `scrapy`,the error occurs,`segmentation fault`, without any extra messages.

**Comment by fornwall** [comment]
There was an issue with ELF files being stripped incorrectly, which caused errors when linking to them.

This has now been fixed, update with:

    apt update && apt upgrade

After updating packages, one also needs to rebuild all packages with native extensions. Easiest is to uninstall all packages (`pip freeze | xargs pip uninstall -y`)  and then install again.

Let me know if the problem persists after updating apt packages and rebuilding pip ones.

**Comment by smallfaruk** [comment]
termux Show me segmentation fault

**Comment by Grimler91** [comment]
@smallfaruk @PhyoWanna see #2066.
