### ISSUE TITLE
How to male this code work

### ISSUE THREAD

**Issue by giuseppe345** [termux/termux-packages#4018]
git clone https://github.com/liveOverflow/liveoverflow_youtube.git
But It doesnt work i tried everything
Saying to me to insert username and password but i cant

**Comment by xeffyr** [comment]
> But It doesnt work

Really ? I just copied your command btw:

![Screenshot_20190706-020455_Termux](https://user-images.githubusercontent.com/25881154/60748070-d6d78180-9f92-11e9-89ba-bb44ac88e7a1.jpg)
