### ISSUE TITLE
cmake CANNOT LINK EXECUTABLE "cmake": cannot locate symbol "_ZN4Json5ValueaSES0_" 

### ISSUE THREAD

**Issue by changloong** [termux/termux-packages#4026]
**Problem description**
try use cmake get this:
 cmake
CANNOT LINK EXECUTABLE "cmake": cannot locate symbol "_ZN4Json5ValueaSES0_" referenced by "/data/data/com.termux/files/usr/bin/cmake"...
 
**Additional information**

on arm32 , not test aarch64 yet.

**Comment by Grimler91** [comment]
Thanks, should be fixed in a few minutes when the CI-build finishes: https://cirrus-ci.com/build/5119774932074496 !

**Comment by Grimler91** [comment]
Or rather, it should be fixed in cmake 3.14.5-2 which is available shortly
