### ISSUE TITLE
mc - link error after recent update (glib_2.60.4?)

### ISSUE THREAD

**Issue by samoht0** [termux/termux-packages#4027]
Android-5 branch: mc_4.8.23_arm.deb 
After installing lasted updates, when running "mc", I get:
CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_d2ulz" referenced by "mc"
Maybe related to glib_2.60.4_arm.deb update (?).

**Comment by tomty89** [comment]
Most likely because glib or another of its dependencies was fixed by the unwind symbols hiding and hence it needs a rebuild as well.

**Comment by xeffyr** [comment]
@samoht0 Try this one: https://dl.bintray.com/xeffyr/termux-dev/arm/mc_4.8.23_arm.deb

**Comment by samoht0** [comment]
> @samoht0 Try this one: https://dl.bintray.com/xeffyr/termux-dev/arm/mc_4.8.23_arm.deb

Alright. Build works fine.

**Comment by fornwall** [comment]
Fixed - run `pkg up` to update!
