### ISSUE TITLE
'pip install lmxl' does not work since '-lrt' is used

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#403]
Taken from comment by @slgray at https://github.com/termux/termux-packages/issues/139:

I try to install python lxml wiith pip install lmxl.
And got this error:

    /data/data/com.termux/files/usr/bin/ld: cannot find -lrt
    clang-3.8: error linker command failed with exit code 1(use -v to see invocation)
    error: cammand 'gcc' failed with exit status 1

The `-lrt` flag is not needed (and does not work) on Android. Where does that flag come fro (pip/clang/lxml/...)?

**Comment by fornwall** [comment]
@slgray This has now been fixed in version `12-4` of the `ndk-sysroot` package - run

    apt update && apt upgrade

and try again! Thanks for reporting the issue!

**Comment by slgray** [comment]
It works now, thank your for your great work!
