### ISSUE TITLE
Gentoo

### ISSUE THREAD

**Issue by ulist** [termux/termux-packages#4031]
How could I run gentoo on termux I have installed the system files and it require to be on /data/ folder

**Comment by xeffyr** [comment]
> and it require to be on /data/ folder

It doesn't require unless you use gentoo-prefix. Gentoo-prefix is **broken** (suffers from hardcoded paths, like Termux in past) and should not be used.

Just download stage3 archive for your architecture, for example aarch64 one: http://distfiles.gentoo.org/experimental/arm64/stage3-arm64-20190613.tar.bz2 and use it with proot. How ? - answers in https://github.com/Neo-Oli/termux-ubuntu/blob/master/ubuntu.sh. Ways are same, just different rootfs.

**Comment by xeffyr** [comment]
Using Gentoo under proot is bad idea. Many things should be compiled from source, but proot makes builds a lot slower.

**Comment by ulist** [comment]
So I Have problem I can't execute emerge it asked for `/dev/urandom` which is in my system and gentoo is dev `gentoo/dev/fd` file what do I do now

**Comment by xeffyr** [comment]
Bind-mount them of course. Hint: use option `-b` of proot, e.g. `-b /dev:/dev -b /proc/self/fd:/dev/fd`.
