### ISSUE TITLE
Ncurses package missing terminfo for simple terminal (st)

### ISSUE THREAD

**Issue by a-vrma** [termux/termux-packages#4034]
**Problem description**
`st  st-256color  st-meta  st-meta-256color` are missing from the ncurses package. Without these, sshing from my linux laptop that uses [st](https://st.suckless.org/) doesn't work well.

**Steps to reproduce**
1. Install st
2. SSH into termux
3. Type some characters
4. Press backspace

The character are not deleted.

**Expected behavior**

I would expect the characters to be deleted.

**Solution**

Upstream ncurses does in fact distribute st terminfos, however it seems that you are not packaging them. The solution would be to package them.

**Comment by xeffyr** [comment]
`st st-256color st-meta st-meta-256color` terminfo is available in `st` package from `x11-repo`.

**Comment by xeffyr** [comment]
These files can be moved to ncurses though as installing `st` will download additional dependencies.

**Comment by a-vrma** [comment]
Yeah, the ncurses package on my Arch machine includes all the `st` stuff.
I assume https://github.com/termux/termux-packages/blob/294a19be90105d827ce657f15b0f5eef271ae4e2/packages/ncurses/build.sh#L77 has something to do with it.

**Comment by Shourai** [comment]
> These files can be moved to ncurses though as installing `st` will download additional dependencies.

I experience the same thing as  @a-vrma does when using st to ssh to termux.
Though installing `st` from the x11-repo does work, it is as you said also installing additional dependencies.

Though a workaround without installing anything is just setting the TERM variable to something else as mentioned in https://github.com/termux/termux-packages/issues/1061#issuecomment-334784572.
 `TERM=vt100`
Works for me, but not an ideal solution.

**Comment by xeffyr** [comment]
Done in https://github.com/termux/termux-packages/commit/53a671ff8d383beb97ba934a587e6a3d84cf6942.
