### ISSUE TITLE
ecl issue with libffi

### ISSUE THREAD

**Issue by rsawrecht** [termux/termux-packages#4035]
**Problem description**
I have been running ECL from the commandline and emacs without issue until having completed a 'pkg update' last week.

When running from the commandline or in emacs via SLIME, ECL now produces the following error and aborts: "CANNOT LINK EXECUTABLE "ecl": library "libffi.so.6" not found"

When I  look for libffi in the file system:
$ locate libffi.so
/data/data/com.termux/files/usr/lib/libffi.so
/data/data/com.termux/files/usr/lib/libffi.so.6
/data/data/com.termux/files/usr/lib/libffi.so.6.0.4

But when i move into the directory and list, only libffi.so exists:
$ cd ../usr/lib && ls -al | grep libffi
-rwx------  1 u0_a3 u0_a3    14264 Jul  8 04:14 libffi.so

**Steps to reproduce**
commandline: $ ecl
emacs: M-x slime

**Expected behavior**
Both from the commanline and emacs after running the above commands a LISP REPL should present and accept input.

**Additional information**
===================================
1. Android warning/error log: logcat -d "*:W"
===================================
--------- beginning of crash
15:50:43.477  6721  6721 F libc    : CANNOT LINK EXECUTABLE "ecl": library "libffi.so.6" not found
15:50:43.477  6721  6721 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 6721 (ecl)                   

============================================
2. Output of strace: strace -fv -s 2048 -o strace.log ecl  
============================================
CANNOT LINK EXECUTABLE "ecl": library "libffi.so.6" not found
 Aborted

================================ ====================
3. If program write it's own log files, you may need to attach them.
From within EMACS:
=====================================================
(progn (load "/data/data/com.termux/files/home/quicklisp/dists/quicklisp/software/slime-v2.23/swank-loader.lisp" :    verbose t) (funcall (read-from-string "swank-loader:init") :from-emacs t) (funcall (read-from-string "swank:start-    server") "\/data/data/com.termux/files/usr/tmp/slime.22324"))

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/ecl": library "libffi.so.6" not found
Process inferior-lisp aborted

**Comment by its-pointless** [comment]
yeah looks like i didn't update ecl binaries in android-5 repo. quick solution is to make a symblink with libffi.so.6 pointing at libff.so 
either way i will fix it in a bit... btw ecl is not officallly supported so this doesn't belong here.
