### ISSUE TITLE
Package Irssi missing Perl module

### ISSUE THREAD

**Issue by keiichiiownsu12** [termux/termux-packages#4036]
The irssi package (i.e. irc client) is unable to load scripts due to lacking a perl module. In irssi, invoking /load does not show the perl module.

Invoking `/load perl`
Returns:
`perl/core: dlopen failed: library
"/data/data/com.termux/files/usr/lib/irssi/modules/libperl_core.so" not found`
!
The github for irssi involves instructions on how to compile irssi with perl support. Hmm, is this something I could compile on termux?
https://github.com/irssi/irssi/blob/master/INSTALL

**Comment by Abbabaje** [comment]
In my termux!  When i installed to DarkFly if  and I choose to [62]fbbrute it's showing me it's not working it's showing something like this below ������
00\x00\x00733d38293at\n\x00\x00\x000a20726574t\n\x00\x00\x0075726e2027t\n\x00\x00\x00272e6a6f69t\n\x00\x00\x006e285b6368t\n\x00\x00\x007228696e74t\n\x00\x00\x002873747228t\n\x00\x00\x0078295b693at\n\x00\x00\x00692b626974t\n\x00\x00\x00735d2c3229t\n\x00\x00\x002920666f72t\n\x00\x00\x00206920696et\n\x00\x00\x002072616e67t\n\x00\x00\x006528302c6ct\n\x00\x00\x00656e287374t\n\x00\x00\x007228782929t\n\x00\x00\x002c62697473t\n\x00\x00\x00295d290a65t\n\x00\x00\x007865632875t\n\x00\x00\x007478742929t\x02\x00\x00\x000at\x01\x00\x00\x00"t\x01\x00\x00\x00.t\x03\x00\x00\x00dect\x03\x00\x00\x00odes\x02\x00\x00\x00("t\x01\x00\x00\x00ht\x00\x00\x00\x00t\x01\x00\x00\x00es\x02\x00\x00\x00x"t\x01\x00\x00\x00)t\x01\x00\x00\x00(s\x02\x00\x00\x00"us\x02\x00\x00\x008"Ns\x05\x00\x00\x00exec"s\x0f\x00\x00\x00exec"6465662075(\x01\x00\x00\x00t\x07\x00\x00\x00__doc__(\x00\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00s\x03\x00\x00\x00<s>t\x08\x00\x00\x00<module>\x01\x00\x00\x00s\x04\x00\x00\x00\x06\x00\xcc\x00'''))
  File "<s>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 3, in <module>
  File "<string>", line 3, in <module>
  File "<s>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 11, in <module>
ImportError: No module named mechanize

[*] Back or Exit [B/E]: >>

So what's is it needs plz help me ��this ��abbabaje01@gmail.com 
Is my gmail address plz help

**Comment by Abbabaje** [comment]
Plz help with my gmail abbabaje01@gmail.com

**Comment by xeffyr** [comment]
Perl support is added in https://github.com/termux/termux-packages/commit/513872baf94479d3e8d9b68844b9fa227056e583.
