### ISSUE TITLE
Metasploit socket access denied

### ISSUE THREAD

**Issue by BBhacku** [termux/termux-packages#4037]
After following the instructions given at : https://wiki.termux.com/wiki/Metasploit_Framework
I successfully installed the Metasploit.

$ msfconsole
$ use auxiliary/scanner/discovery/arp_sweep
$ set RHOSTS 192.168.0.0/24
$ run
Error :192.168.0.0-192.168.0.255 : socket: Permission denied

At first instance it looked like that root permission wasn't granted to termux. So I did the following :

$ su
(Granted access in supersu)
root@a7lte:/data/data/com.termux/files/home # cd msfconsole
sush :msfconsole :not found
 
root@a7lte:/data/data/com.termux/files/home # cd ..

root@a7lte:/data/data/com.termux/files# cd usr
root@a7lte:/data/data/com.termux/files/usr# cd opt
root@a7lte:/data/data/com.termux/files/usr/opt#cd metasploit-framework
root@a7lte:/data/data/com.termux/files/usr/opt/metasploit-framework#./msfconsole
env :can't execute 'ruby' : Permission denied

I think I am not able to correctly install or run metsploit with right permission , any help will be highly appreciated.

**Comment by xeffyr** [comment]
Use `tsu` in order to use Termux utilities as root.
