### ISSUE TITLE
dart 2.4 dart2js not in .deb file

### ISSUE THREAD

**Issue by davidsands** [termux/termux-packages#4039]
**Problem description**
After installing dart, the dart to javascript compiler, dart2js was not installed. I downloaded the .deb file, and found the program was not in the deb.

**Steps to reproduce**
1. Install dart (current version 2.4)
2. Run dart2js
3. file not found error will occur

**Expected behavior**
dart2js should be with the other dart binaries in .../dart-sdk/bin

**Additional information**
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.10.84-perf-g4344a50-00007-ge630c83 #1 SMP PREEMPT Wed Jan 10 17:02:22 CST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.0
Device manufacturer:
asus
Device model:
P008

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by TheBrokenRail** [comment]
dart2js does not compile correctly on Android, so the only way to build Dart is to exclude it from the SDK. While this happens by default on ARM, it is also required on x86, so it is excluded there too.
