### ISSUE TITLE
CANNOT LINK EXECUTABLE MC

### ISSUE THREAD

**Issue by justteen** [termux/termux-packages#4040]
Help me. I got issue. Already delete all data, reinstall. But, not have a change. I don't know how to fix this.

CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_d2ulz" referenced by "mc"...
page record for 0xb6f5402c was not found (block_size=16)

![Screenshot_20190712_043437](https://user-images.githubusercontent.com/48372964/61086938-60d58d80-a45e-11e9-994f-fbc4af431b24.jpg)

Help me

**Comment by RossComputerGuy** [comment]
It ran for me, what device do you have?

**Comment by justteen** [comment]
Vivo 1603

**Comment by xeffyr** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/4027.
