### ISSUE TITLE
Anyone cant help me in my python script?

### ISSUE THREAD

**Issue by yogiema** [termux/termux-packages#4042]
![Screenshot_2019-07-12-11-44-10-525_com termux](https://user-images.githubusercontent.com/43556633/61103041-076e5e00-a460-11e9-94d1-860e1b44ed62.png)

**Comment by xeffyr** [comment]
Seems like problem with script. However you may try to install script to `~/` (`/data/data/com.termux/files/home`) and see if it will work.

Closing as off-topic as script is not part of Termux distribution.
