### ISSUE TITLE
How to install libssl1.0.0

### ISSUE THREAD

**Issue by IamPARANOID** [termux/termux-packages#4054]
openssl/openssl-dev1.0.0 is seemingly required for building phantomjs as noted in https://github.com/termux/termux-packages/issues/908

Is it possible to install an old version of the package?

**Comment by Grimler91** [comment]
It is not possible to install it from the repositories. Installing openssl 1.0.0 (and replacing openssl 1.1.1) would break all the termux-packages since they are linked against openssl 1.1.1.

You need to compile it yourself (either cross compile or on device) and install it to for example $PREFIX/local. Note that you need to override [$TERMUX_PREFIX](https://github.com/termux/termux-packages/blob/2876ccb8035589dd7df5fae97dde9339066d56fd/scripts/build/termux_step_setup_variables.sh#L7) to for example $PREFIX/local, and rename openssl to for example openssl-1.0 for the crosscompilation approach to work.

**Comment by IamPARANOID** [comment]
@Grimler91 Thanks for the response.
Not cross compiling, doing it on device.
How do I/what is the best way to convince the compilation process to use /usr/local not /usr/?
Tried changing/exporting $PREFIX to ``/data/data/com.termux/files/usr/local`` for zero avail.
I'm guessing ``proot`` or something similar is necessary?

**Comment by IamPARANOID** [comment]
Ended up just (cross-)compiling on a different computer, "installing" it there, then transferring it over using ``scp``, moving it to ``/usr/local``, then using ``sed`` to change where it was erroneously including files from.

**Comment by IamPARANOID** [comment]
Ended up actually compiling it as x86_64 the first time for some reason, which passed the early compile stage of phantomjs, but ran into errors later.

Here's a command dump on how to cross compile libssl1.0.0s on Linux for Termux:

```
./Configure linux-generic32 shared -DL_ENDIAN --prefix=/usr/local --openssldir=/usr/local -no-ssl3 -no-comp -no-hw -no-engine 
make CC=arm-linux-androideabi-gcc RANLIB=arm-linux-androideabi-ranlib LD=arm-linux-androideabi-ld MAKEDEPPROG=arm-linux-androideabi-gcc PROCESSOR=ARM 
LDFLAGS=-L/opt/android-ndk/platforms/android-9/arch-arm/usr/lib/


export PATH="/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/:$PATH"
export SYS_ROOT="/opt/android-ndk/platforms/android-9/arch-arm/"
export CC="arm-linux-androideabi-gcc --sysroot=$SYS_ROOT"
export LD="arm-linux-androideabi-ld"
export AR="arm-linux-androideabi-ar"
export C_INCLUDE_PATH=/opt/android-ndk/platforms/android-9/arch-arm/usr/include/
export CFLAGS=-I$C_INCLUDE_PATH

./Configure linux-generic32 shared -DL_ENDIAN --prefix=/usr/local/openssl1.0.0s --openssldir=/usr/local/openssl1.0.0s
make depend RANLIB=arm-linux-androideabi-ranlib MAKEDEPPROG=arm-linux-androideabi-gcc PROCESSOR=ARM
make all RANLIB=arm-linux-androideabi-ranlib MAKEDEPPROG=arm-linux-androideabi-gcc PROCESSOR=ARM
sudo -E make install RANLIB=arm-linux-androideabi-ranlib MAKEDEPPROG=arm-linux-androideabi-gcc PROCESSOR=ARM

sed -i 's#<openssl/#</data/data/com.termux/files/usr/local/openssl1.0.0s/include/openssl/#g' *.h


export LD_LIBRARY_PATH=$PREFIX/local/openssl1.0.0s/lib/:$LD_LIBRARY_PATH
```

Most of that is gleaned from these 3 helpful StackOverFlow questions:
https://stackoverflow.com/questions/23098521/do-openssl-1-0-1g-has-android-platform-support
https://stackoverflow.com/questions/15539062/cross-compiling-of-openssl-for-linux-arm-v5te-linux-gnueabi-toolchain
https://stackoverflow.com/questions/34209320/cross-compiling-using-android-toolchains

This of course requires the Android NDK, which can be installed from the AUR like so:
``yay -S android-ndk-11c``
