### ISSUE TITLE
Termux broken after git install

### ISSUE THREAD

**Issue by loic35** [termux/termux-packages#4055]
**Problem description**
After install of git ot works just after, but restarting leads to this message:
CANNOT LINK EXECUTABLE: could not load library "libreadline.so.7" needed by "/data/data/com.termux/files/usr/bin/bash"; caused by cannot locate symbol "nl_langinfo" referenced by "libreadline.so.7"...
[Process completed (code 1) - press Enter]

**Steps to reproduce**
Install latest git with pkg
Termux is uptodate

**Expected behavior**
Either refuse to install a package that will break Termux, or not problem with git.

**Additional information**
Not rooted phone. Unable to launch any command in Termux.

**Comment by Grimler91** [comment]
Seems like you haven't used termux in a while and installed a new program which unfortunately broke bash. It is good practice to run `pkg upgrade` (i.e. `apt update && apt upgrade`) if you haven't done so in a while before doing other stuff.

Easiest fix would be to run `rm -rf $PREFIX` from a [failsafe session](https://wiki.termux.com/wiki/Recover_a_broken_environment) and then restart the app, this will remove all installed packages and give a fresh installation ($HOME is left intact though). You could also try to manually extract and install the broken packages from the failsafe session, but this will probably be a bit tedious (bash, libreadline, libiconv and possibly others need to be upgraded).

Partial upgrades will (sometimes) break termux, there's not really any feasible way to prevent that.

**Comment by loic35** [comment]
Seems Ok after complete re-install.
Don't remember previously installed packages (at least Python).
