### ISSUE TITLE
PHP link executable issue

### ISSUE THREAD

**Issue by wuffeljunior90** [termux/termux-packages#4056]
Hello guys, I have a problem with php command in termux. 
I have a galaxy J3 2017 duos and running Android 8.0
In the following screenshot you can see that there is a link executable error. A few days ago the function was fine. But after update and upgrade today this issue shows up. 
I have tried some things to solve it but nothing worked for me. I have googled so much and now I can't php anymore. Can anyone tell me what's the problem or is it easy to solve? 
Thank you in advance. :) 
![Screenshot_20190715-104545_Termux](https://user-images.githubusercontent.com/51043135/61204636-08b4ba80-a6ee-11e9-8b9e-2104d76f1b8d.jpg)

**Comment by Grimler91** [comment]
What's the output of `termux-info`?

**Comment by wuffeljunior90** [comment]
Sorry I forgot to attach it. 

![Screenshot_20190715-105534_Termux](https://user-images.githubusercontent.com/51043135/61205706-1cadeb80-a6f1-11e9-9a78-98450256bf36.jpg)

**Comment by Grimler91** [comment]
`libgd` hasn't been upgraded in two months so it's weird that this happens now...

**Comment by xeffyr** [comment]
> libgd hasn't been upgraded in two months

php was upgraded. And NDK.

**Comment by xeffyr** [comment]
Fixed in libgd v2.2.5-4. Updated package will be available soon.
