### ISSUE TITLE
pkg cannot locate symbol "__gnu_ldivmod_helper"

### ISSUE THREAD

**Issue by btimofeev** [termux/termux-packages#4057]
pkg program has stopped working for me.  Previously, everything was fine, but today I run command termux-upgrade-repo. And after that pkg command gives an error and hangs. Clearing application data and reinstalling does not help.
Termux 0.72, Android 9, Nexus5 

``` 
>pkg upgrade
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": cannot locate symbol "__gnu_ldivmod_helper" referenced by "/data/data/com.termux/files/usr/lib/libcurl.so"...
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": cannot locate symbol "__gnu_ldivmod_helper" referenced by "/data/data/com.termux/files/usr/lib/libcurl.so"...
0% [Working]^C
```

**Comment by Grimler91** [comment]
Have you re-started termux and run `./termux-reinstall.sh`? 

What's the output of `termux-info`?

This issue seem have pretty much the same error: https://github.com/termux/termux-packages/issues/4056

**Comment by xeffyr** [comment]
On Pie/Aarch64 everything working fine.

**Comment by xeffyr** [comment]
> This issue seem have pretty much the same error: #4056

Maybe related but isn't same. While I have fully working `apt` (pkg), the php has exactly same error as in https://github.com/termux/termux-packages/issues/4056.

I will rebuild package and see if error is gone.

**Comment by btimofeev** [comment]
termux-reinstall.sh produced an error.  Now I can’t see which one, since I reinstalled the application and these commands no longer exist. But it seems that the error was the same as I wrote above.

termux-info does not display any messages, just hangs.

**Comment by xeffyr** [comment]
I have updated bootstrap packages. Try to clear application data and check if `pkg` is working.

**Comment by btimofeev** [comment]
Thanks, now it works for me
