### ISSUE TITLE
the termux cant reinstall all my missing package

### ISSUE THREAD

**Issue by t4n6a1ka** [termux/termux-packages#4060]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by Grimler91** [comment]
We can't help you if you don't provide any information or at least a screenshot of the error.
