### ISSUE TITLE
how to install wpscan?

### ISSUE THREAD

**Issue by huitc** [termux/termux-packages#4061]
I followed the way what they said, but i... can't...

**Comment by huitc** [comment]
I'm a nb pls tell me!

**Comment by Grimler91** [comment]
Try asking in on of the other social channels, for example https://www.reddit.com/r/termux/.

Closing as this is off topic in this repo.

**Comment by huitc** [comment]
how about a package named wpscan or sqlmap but only install the `Suggested packages` and `following additional packages` (google translated ^^''

**Comment by huitc** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Dependencies
...

like `pip install` `apt install` `gem install`...
