### ISSUE TITLE
Unable to connect to Termux

### ISSUE THREAD

**Issue by MademoiselleVictoire** [termux/termux-packages#4064]
Hey there! Unable to connect to Termux; keep getting same response: 
E: Malformed entry 4 in list file /data/data/com.termux/files/usr/etc/apt/sources.list (absolute Suite Component) E: The list of sources could not be read. 
Please --h

**Comment by xeffyr** [comment]
Fix sources.list file with:
```
echo "deb https://termux.net stable main" > $PREFIX/etc/apt/sources.list
```

I'm suggesting to avoid touching things under `/data/data/com.termux/files/usr` ($PREFIX).

**Comment by MademoiselleVictoire** [comment]
> Fix sources.list file with:
> 
> ```
> echo "deb https://termux.net stable main" > $PREFIX/etc/apt/sources.list
> ```
> 
> I'm suggesting to avoid touching things under `/data/data/com.termux/files/usr` ($PREFIX).

Thank you so much! It worked like a charm.
