### ISSUE TITLE
i cant type my github password .. i even did reinstalling but its not working

### ISSUE THREAD

**Issue by Nithishprajin** [termux/termux-packages#4068]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by Nithishprajin** [comment]
Im unable to type github password ...Sort out my  query as soon as possible

**Comment by xeffyr** [comment]
> Im unable to type github password

1. Typed passwords are **invisible**. A common behaviour on Linux distributions and that's normal and won't be changed.

2. You are doing mistakes when typing password.

3. You are trying to clone a nonexistent or private repo of someone else.
