### ISSUE TITLE
I cant enter enter github password

### ISSUE THREAD

**Issue by hacker7498** [termux/termux-packages#4069]
![IMG-20190719-WA0070](https://user-images.githubusercontent.com/49986607/61524463-1fcc1300-aa34-11e9-82fe-5a9c5686aa24.jpg)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/4068#issuecomment-513167302

**Comment by xeffyr** [comment]
Repository you are cloning does not exist:

![Screenshot_2019-07-19_12-48-50](https://user-images.githubusercontent.com/25881154/61526718-a88e8300-aa23-11e9-8170-a3f3eaf34e4d.png)
