### ISSUE TITLE
i keep getting this...Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by Technology54** [termux/termux-packages#4072]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
> i keep getting this...Sub-process /usr/bin/dpkg returned an error code (1)

**This** doesn't describe the problem and how you ran into it.
Template tells you which information you should provide.

***

FYI, if you got such problem with package manager after messing with stuff under $PREFIX (/data/data/com.termux/files/usr) or using packages or scripts from third-party, the better solution will be to re-install.

Following article on Wiki shows how to do so:
https://wiki.termux.com/wiki/Recover_a_broken_environment#If_the_problem_is_not_with_the_dotfiles
