### ISSUE TITLE
Env cant execute ruby

### ISSUE THREAD

**Issue by Uddhavshrimali** [termux/termux-packages#4077]
![Screenshot_20190720-212058](https://user-images.githubusercontent.com/41739097/61580928-37d78b80-ab35-11e9-8565-77325e5400d7.png)

**Comment by RossComputerGuy** [comment]
the hashbang probably is set to /usr/bin/ruby which does not exist. Change it to the termuc prefix + bin/ruby.

**Comment by Grimler91** [comment]
I guess you haven't installed ruby, which probably means that you haven't installed msf by following the wiki: https://wiki.termux.com/wiki/Metasploit_Framework
