### ISSUE TITLE
Bad system call encountered running "go get"

### ISSUE THREAD

**Issue by xxuejie** [termux/termux-packages#4079]
**Problem description**
The following command generates `Bad system call` behavior:

```
go get -u github.com/mjibson/esc
```

**Steps to reproduce**

* Install golang package
* Run `go get -u github.com/mjibson/esc`

**Expected behavior**

Go get should work.

**Additional information**

```
$ go get -u github.com/mjibson/esc
Bad system call
```

Not sure if it helps but I ran into this on a Chromebook using Android apps, a native Android device won't run into this issue.

Also allow me to say: awesome project! I know fixing complicated software like golang might be infeasible, but just want to check if this is a low-hanging fruit that can be resolved easily.

**Comment by Grimler91** [comment]
What do you mean with 
> a native Android device won't run into this issue

?
What's the output of `termux-info` on the device you have the problem?

Could you install strace and run `strace -o go.log go get -u github.com/mjibson/esc` and post the last ~20 lines of go.log here?

**Comment by xxuejie** [comment]
Allow me to explain.

I have an Android phone which works without problems. That's what I mean by a native Android device. The `termux-info` for this phone is as follows:

```
System information:
Linux localhost 4.9.106-perf+ #1 SMP PREEMPT Sat Jun 15 00:31:40 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6000
```

I also have a Chromebook which can run Android apps, `termux-info` for this device is as follows:

```
System information:
Linux localhost 4.4.178-16505-g1c7029432a2d #1 SMP PREEMPT Thu Jul 4 00:34:10 PDT 2019 x86_64 Android
Termux-packages arch:
x86_64
Android version:
9
Device manufacturer:
Google
Device model:
HP Chromebook x2
```

On this device, `go get` would signal the `bad syscall error`, and the last 20 lines of `go.log` file looks like this:

```
fcntl(6, F_GETFL)                       = 0x1 (flags O_WRONLY)
fcntl(6, F_SETFL, O_WRONLY|O_NONBLOCK)  = 0
pipe2([7, 8], O_CLOEXEC)                = 0
epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=4284817344, u64=138452555603904}}) = 0
fcntl(7, F_GETFL)                       = 0 (flags O_RDONLY)
fcntl(7, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
epoll_ctl(4, EPOLL_CTL_ADD, 8, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=4284817136, u64=138452555603696}}) = 0
fcntl(8, F_GETFL)                       = 0x1 (flags O_WRONLY)
fcntl(8, F_SETFL, O_WRONLY|O_NONBLOCK)  = 0
newfstatat(AT_FDCWD, ".", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
fcntl(6, F_GETFL)                       = 0x801 (flags O_WRONLY|O_NONBLOCK)
fcntl(6, F_SETFL, O_WRONLY)             = 0
fcntl(8, F_GETFL)                       = 0x801 (flags O_WRONLY|O_NONBLOCK)
fcntl(8, F_SETFL, O_WRONLY)             = 0
pipe2([9, 10], O_CLOEXEC)               = 0
getpid()                                = 2874
rt_sigprocmask(SIG_SETMASK, NULL, [], 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[], NULL, 8) = 0
clone(child_stack=NULL, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = ?
+++ killed by SIGSYS +++
```

Let me know if you have more questions.

**Comment by xeffyr** [comment]
>  and the last 20 lines of

20 lines from just strace output is not enough... unfortunately

Better to do:
```
strace -fv -o go.log go get -u github.com/mjibson/esc
```
and post lines of 
```
grep SIGSYS go.log
```

**Comment by xxuejie** [comment]
Here's the result:

```
$ grep SIGSYS go.log
1733  rt_sigaction(SIGSYS, {sa_handler=0x7e96ca1b7d44, sa_mask=~[RTMIN RT_1 RT_2 RT_3], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x7e96ca26df40}, NULL, 8) = 0
1733  rt_sigaction(SIGSYS, NULL, {sa_handler=0x7e96ca1b7d44, sa_mask=~[KILL STOP RTMIN RT_1 RT_2 RT_3], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x7e96ca26df40}, 8) = 0
1733  rt_sigaction(SIGSYS, {sa_handler=0x5c5b7efa27d0, sa_mask=~[RTMIN RT_1 RT_2 RT_3], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x7e96c9f69a10}, NULL, 8) = 0
1743  rt_sigaction(SIGSYS, {sa_handler=SIG_DFL, sa_mask=~[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x5c5b7efa2890}, NULL, 8) = 0
1743  --- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x5c5b7efeb49b, si_syscall=__NR_dup2, si_arch=AUDIT_ARCH_X86_64} ---
1742  +++ killed by SIGSYS +++
1741  +++ killed by SIGSYS +++
1740  +++ killed by SIGSYS +++
1739  +++ killed by SIGSYS +++
1738  +++ killed by SIGSYS +++
1737  +++ killed by SIGSYS +++
1736  +++ killed by SIGSYS +++
1735  +++ killed by SIGSYS +++
1733  +++ killed by SIGSYS +++
1743  +++ killed by SIGSYS (core dumped) +++
```

**Comment by xeffyr** [comment]
So, on your device it looks like `__NR_dup2` is blocked. This is not normal because such system call is essential and **not** blacklisted in https://github.com/aosp-mirror/platform_bionic/blob/master/libc/SECCOMP_BLACKLIST_APP.TXT.

**Comment by xxuejie** [comment]
Thanks! I think this should be a Chromebook issue, already relayed to the Chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=986119

**Comment by fornwall** [comment]
@xxuejie Thanks a lot! I'm closing this since there doesn't seem to be anything more to be done from the Termux side, just open a new issue if there is!
