### ISSUE TITLE
`git add --patch` does not work

### ISSUE THREAD

**Issue by Exaeta** [termux/termux-packages#408]
```
/data/data/com.termux/files/home/rbtree$ git add --patch rbtree.hh
fatal: 'add--interactive' appears to be a git command, but we were not
able to execute it. Maybe git-add--interactive is broken?
/data/data/com.termux/files/home/rbtree$
```

**Comment by michalbednarski** [comment]
You'll need to `apt install perl` in order to use `git add -i` and similar commands. Since `perl` is one of largest packages and many people use `git` without it it is not included by default, though message should be probably made clearer here.

**Comment by Exaeta** [comment]
Ah, okay. maybe add a package, "git-interactive" that would depend on perl and git? When it didn't work, I searched for git packages, something like this might help people like me that didn't know it uses perl.

**Comment by michalbednarski** [comment]
Actually, I don't think new package is needed, I was thinking about changing message at https://github.com/git/git/blob/2632c897f74b1cc9b5533f467da459b9ec725538/help.c#L308-L310 to instruct to install perl, since missing perl most likely cause for this error.

**Comment by Neo-Oli** [comment]
@michalbednarski Would you change that with a patch in termux or were you thinking of changing this in git proper?

**Comment by michalbednarski** [comment]
In Termux, desktops system usually have perl installed out of the box so this wouldn't be as likely to be cause for this error.

**Comment by fornwall** [comment]
Nice idea! Does the following patch look good?

```
Some git commands requires perl to be installed. But as perl
is a relatively large package, and many people don't need
these commands, the git package does not specify perl as a
dependency. Instead we inform about installing perl when
necessary with this patch.

diff -u -r ../git-2.9.3/help.c ./help.c
--- ../git-2.9.3/help.c	2016-08-12 15:38:45.000000000 -0400
+++ ./help.c	2016-08-23 05:54:46.533592159 -0400
@@ -307,7 +307,7 @@
 
 static const char bad_interpreter_advice[] =
 	N_("'%s' appears to be a git command, but we were not\n"
-	"able to execute it. Maybe git-%s is broken?");
+	"able to execute it. Maybe you need to 'apt install perl'?");
 
 const char *help_unknown_cmd(const char *cmd)
 {
```

**Comment by michalbednarski** [comment]
Looks okay, just drop extraneous die(...bad_interpreter_advice...) argument
as one %s was removed

**Comment by fornwall** [comment]
@michalbednarski Thanks! The `Maybe you need to 'apt install perl'? ` message will be in the `2.9.3-1` version of the git package and onwards.
