### ISSUE TITLE
Package request: assimp

### ISSUE THREAD

**Issue by pollen5** [termux/termux-packages#4080]
The Open-Asset-Importer-Lib

GitHub: https://github.com/assimp/assimp

It's known to work on Android

**Comment by xeffyr** [comment]
Isn't already added: https://github.com/termux/unstable-packages/issues/103 ?

**Comment by xeffyr** [comment]
I can move it to main repo today.

**Comment by pollen5** [comment]
o i forgot i opened the issue on unstable repo, i was searching and didn't find it so i remade one sorry

**Comment by xeffyr** [comment]
> o i forgot i opened the issue on unstable repo

I just transferred it here.
It also can be easily found by using *search*: https://github.com/search?q=org%3Atermux+assimp&type=Issues
