### ISSUE TITLE
Running an x86_64 binary on ARM

### ISSUE THREAD

**Issue by pollen5** [termux/termux-packages#4089]
I wanna use a program so badly but unfortunately it depends on a library that does not work on ARM and is closed-source, is there anyway to emulate the binary to run on ARM, i heard people talk about qemu but i have no idea about it, even if its gonna be slow I'm fine with it.

**Comment by xeffyr** [comment]
Is binary static ?

**Comment by pollen5** [comment]
no, it depends on some shared libraries, they are in termux repos though, except for that closed source one but i can download that.

**Comment by xeffyr** [comment]
> they are in termux repos though

QEMU doesn't support connecting x86 binary with ARM libraries. Also, there most likely differences in libc, glibc vs bionic.

You will need to setup whole x86 rootfs and use `proot` with `-q` option.

**Comment by pollen5** [comment]
Yes i know arm libraries won't be compatible with x86 binary, from another tutorial i saw he was adding the apt repo for the different arch to pull out those dependencies such as libc, but i just remembered termux uses the system libc so um that's gonna be difficult, for your answer how do you exactly do that, i don't know what's "rootfs" and is that possible in a way without destroying my current environment

**Comment by xeffyr** [comment]
Ubuntu rootfs:

amd64: https://partner-images.canonical.com/core/disco/current/ubuntu-disco-core-cloudimg-amd64-root.tar.gz

i386: https://partner-images.canonical.com/core/disco/current/ubuntu-disco-core-cloudimg-i386-root.tar.gz

**Comment by pollen5** [comment]
Ok i just downloaded the amd64 rootfs and extracted it with tar, however at the end i got a `tar: can't create hardlink 'usr/bin/bzcat' to 'usr/bin/bunzip2'` do i have to worry about that? If not then what's next now.

**Comment by xeffyr** [comment]
You may execute tar under proot with `--link2symlink`. But if you need rootfs just to run binary, I think you can ignore errors.

**Comment by pollen5** [comment]
How do i exactly call the proot command, i tried
```
pollen@localhost ~> proot --rootfs=ubuntu -q fbx-bin/fbx-conv-lin64
proot warning: can't chdir("/data/data/com.termux/files/home/./.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: execve("/usr/bin/sh"): Function not implemented
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot --help`.
proot error: can't chmod '/data/data/com.termux/files/usr/tmp/proot-13405-uycTtl': Function not implemented
proot error: can't chdir to '/': Function not implemented
```
Ran it from home directory where ubuntu/ is the rootfs extracted and fbx-bin/fbx-conv-lin64 is the binary i want to run.

**Comment by xeffyr** [comment]
> proot --rootfs=ubuntu -q fbx-bin/fbx-conv-lin64

`-q /path/to/qemu-x86_64`

**Comment by pollen5** [comment]
Oh so i need to install qemu, thought -q was for running a single command using qemu, which one do i install, qemu-system-x86_64-headless or qemu-user-x86_64

**Comment by xeffyr** [comment]
qemu-user-x86_64

**Comment by pollen5** [comment]
Got same issue
```
pollen@localhost ~> proot --rootfs=ubuntu -q /data/data/com.termux/files/usr/bin/qemu-x86_64
proot warning: can't chdir("/data/data/com.termux/files/home/./.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: execve("/usr/bin/sh"): Function not implemented
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot --help`.
proot error: can't chmod '/data/data/com.termux/files/usr/tmp/proot-18556-EKPiOb': Function not implemented
proot error: can't chdir to '/': Function not implemented
pollen@localhost ~>
```

**Comment by pollen5** [comment]
After looking at Neo-Oli's termux-ubuntu script i saw him unsetting LD_PRELOAD after doing that I'm getting a different error now
```
pollen@localhost ~> proot --rootfs=ubuntu -q /data/data/com.termux/files/usr/bin/qemu-x86_64
proot warning: can't chdir("/data/data/com.termux/files/home/./.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/data/data/com.termux/files/home/ubuntu/usr/bin/dash' is a 64-bit program whereas this version of proot handles 32-bit programs only
proot info: vpid 1: terminated with signal 11
```

**Comment by xeffyr** [comment]
Proot can handle programs only of same bitness as your device.

**Comment by pollen5** [comment]
@xeffyr would it work if proot is compiled for aarch64? my phone can execute aarch64 instructions just that it defaulted to arm on termux

**Comment by pollen5** [comment]
You're right i just did `file /system/lib/libc.so` and it is 32 bits, what if you include a copy of an aarch64 libc would that work or is that a lot of mess

**Comment by pollen5** [comment]
Or maybe a static build of proot?

**Comment by xeffyr** [comment]
> i just did file /system/lib/libc.so

Check existence of `/system/lib64` as `/system/lib` is always 32 bit.

**Comment by pollen5** [comment]
/system/lib64 doesn't exist :(

**Comment by pollen5** [comment]
@xeffyr ok I'm gonna ask again, what about a static build of proot for aarch64?, i found a static build for arm64 somewhere, it ran but gave a lot of syscall errors i suppose the termux version is patched? If so can i get a static build of proot for aarch64 if you have time, or atleast instructions for building i don't have access to a pc but i have access to an Ubuntu vps

**Comment by xeffyr** [comment]
Static proot:

android-7: [proot_5.1.107-21_aarch64.deb.gz](https://github.com/termux/termux-packages/files/3509697/proot_5.1.107-21_aarch64.deb.gz)

android-5: [proot_5.1.107-21_aarch64.deb.gz](https://github.com/termux/termux-packages/files/3509700/proot_5.1.107-21_aarch64.deb.gz)

**Comment by pollen5** [comment]
Strangely exits with a signal 11, but well i guess its time to stop trying.
