### ISSUE TITLE
Package request: rdiff-backup

### ISSUE THREAD

**Issue by legolegs** [termux/termux-packages#4091]
**Package description**
rdiff-backup is a well-known and proven remote incremental backup tool.

**Link to home page and sources**
1. Home page: http://www.nongnu.org/rdiff-backup/
2. Source code: https://github.com/sol1/rdiff-backup
3. Raspbian (armhf) build for reference: http://archive.raspbian.org/raspbian/pool/main/r/rdiff-backup/

**Additional information**
In pip (and pip2) I found a package "rdiff-backup (0.1.1)     - Documentation for rdiff-backup" - if thats a documentation then where the program itself? Anyway it cannot be installed via pip:
```
pip install  rdiff-backup 
Collecting rdiff-backup
  ERROR: Could not find a version that satisfies the requirement rdiff-backup (from versions: none)
ERROR: No matching distribution found for rdiff-backup
```

**Comment by KevWal** [comment]
A plus 1 from me, I use rdiff-backup on all my servers, it would be great for the phone too.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install rdiff-backup
```

**Comment by KevWal** [comment]
Brilliant,  thank you very much, will test it soon.

**Comment by legolegs** [comment]
Thank you!
I had to manually install rdiff-backup on Android 6 (by downloading built package from https://dl.bintray.com/termux/termux-packages-24/aarch64/:rdiff-backup_1.9.1~b0_aarch64.deb and doing `pkg install ./rdiff-backup_1.9.1~b0_aarch64.deb`) and it works.

It complains about "unused DT entry" but as far as I know it can be safely ignored.
