### ISSUE TITLE
Termux bootstrap

### ISSUE THREAD

**Issue by abrala** [termux/termux-packages#4092]
**Problem description**
My device has restrictions for allowed applications to install, I successfully  changed it to allowed one and opening it says "Termux was unable to install the bootstrap packages", there is a way to include it in build?

**Steps to reproduce**
Change "applicationId="*"" in /app/build-gradle to allowed one

**Comment by xeffyr** [comment]
> Change "applicationId="*"" in /app/build-gradle to allowed one

Something that we really should avoid...

**Comment by xeffyr** [comment]
> I successfully changed it to allowed one and opening it says "Termux was unable to install the bootstrap packages", there is a way to include it in build?

Termux bootstrap has nothing to do with "build", btw.

Things to check for you:

* Internet connection.
* Application has to be installed on internal storage.
* Application shouldn't be modified (e.g. in order to bypass restrictions on your device) - Termux is very sensitive to this.
