### ISSUE TITLE
Compiling Java 8 with ecj

### ISSUE THREAD

**Issue by pollen5** [termux/termux-packages#4099]
I use ecj to compile java code and use dalvik to execute it, i hear newer Android versions support java 8 features and I'm on Android 9

How do make use of Java 8 features, first thing i did was edit $PREFIX/bin/ecj to replace the -7 flag to -8 for Java 8 then i try to compile a sample program that uses Java 8 lambdas and then i get this error ```
The type java.lang.invoke.LambdaMetafactory cannot be resolved. It is indirectly referenced from required .class files
```

**Comment by xeffyr** [comment]
> i hear newer Android versions support java 8 features

Yes, but support is **partial**.

**Comment by pollen5** [comment]
Isn't the one in $PREFIX/share/java/android.jar for latest api level?

**Comment by xeffyr** [comment]
Yes, it is. But as I wrote above, java 8 support is partial.
```
$ ls java/lang/invoke/
 CallSite.class           LambdaConversionException.class   MethodHandleInfo.class        MethodHandles.class   MutableCallSite.class    WrongMethodTypeException.class
 ConstantCallSite.class   MethodHandle.class               'MethodHandles$Lookup.class'   MethodType.class      VolatileCallSite.class
```

As you can see, there no `LambdaMetafactory`.

**Comment by pollen5** [comment]
well rip, thanks for the help though.
