### ISSUE TITLE
Tar tries to execute /bin/sh

### ISSUE THREAD

**Issue by sfzhi** [termux/termux-packages#410]
Attempting to run `tar -cvJf foo.tar.xz foo` results in "_tar (child): xz: Cannot exec: No such file or directory_". Running the command under strace reveals that tar tries to execute `xz` via `/bin/sh`, which does not exist on Android.

**Comment by fornwall** [comment]
Thanks - this has been fixed in a `1.29-1` update of the tar package, to which you can update with

    apt update && apt upgrade
