### ISSUE TITLE
curl 7.65.3 is available

### ISSUE THREAD

**Issue by samoht0** [termux/termux-packages#4102]
Released on 2019-07-19 (7.65.2 had a broken progress meter):
https://curl.haxx.se/changes.html
Requesting package update for both branches. Thanks.

**Comment by xeffyr** [comment]
curl already 7.65.3: https://github.com/termux/termux-packages/blob/ee7fe4f054686d741d396eac8b3345b67e65da69/packages/libcurl/build.sh#L4

**Comment by xeffyr** [comment]
android-5 branch is updated once a week.
