### ISSUE TITLE
Using su in a pipe may break terminal characteristics

### ISSUE THREAD

**Issue by joaormatos** [termux/termux-packages#4109]
**Problem description**
When piping `su` into another command, the terminal characteristics are undesirably altered.
The change occurs when `su` is executed and persists afterwards, requiring a "blind" `reset` to get the terminal back to normal.

This doesn't happen when `su` is being piped into from another command or when piping both in and out. That is, it only happens when `stdin` is a terminal and `stdout` isn't.

**Steps to reproduce**
`su -c "echo hello; echo world" | cat`
The terminal now reads:
```su -c "echo hello; echo world" | cat 
hello
     world
          $ 
```
And now you can't see the characters you're typing (you can recover by running `reset`).
You can see what this looks like by running `stty -echo -onlcr`.
Or, more accurately (see below): `stty -icrnl -ixon -opost -isig -icanon -echo -echoe -echok`

**Expected behavior**
The terminal characteristics remain unaltered, unless an application explicitly changes them.

**Additional information**
System: LineageOS 15.1
su: LineageOS's own `su`, probably [this one right here.](https://github.com/LineageOS/android_system_extras_su/tree/lineage-15.1)
The fault may very well lie upstream, but I'm not sure at this point.

Output of `stty -g ; stty -a` before:
```
6506:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0
speed 38400 baud; rows 28; columns 62; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
```
Output of `stty -g ; stty -a` after:
```
6006:4:bf:8a00:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0
speed 38400 baud; rows 28; columns 62; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff
-iuclc -ixany imaxbel iutf8
-opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig -icanon iexten -echo -echoe -echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
```
Summary:
The following options were disabled: icrnl ixon opost isig icanon echo echoe echok

**Possible workaround**

Since the problem only seems to happen when stdin is a terminal and stdout isn't, maybe the wrapper could detect this case and replace stdin with a dummy pipe.

Something like:
```
if [[ -t 0 && ! -t 1 ]] ; then
  cat | su "$@"
else
  su "$@"
fi
```
(For the time being I'll be using that as a workaround wrapper around termux-tools's `su`.)

**termux-info output**
```
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
[redacted]
Termux-packages arch:
arm
Android version:
8.1.0
Device manufacturer:
OnePlus
Device model:
A0001
```

**Comment by xeffyr** [comment]
That's issue of `su` in Lineage OS. Happens `adb shell` too:
```
[xeffyr]:~:$ adb shell
herolte:/ $ su -c "echo hello; echo world" | cat
hello
     world
          herolte:/ $
```
