### ISSUE TITLE
Package Request: Timewarrior

### ISSUE THREAD

**Issue by linuxcaffe** [termux/termux-packages#411]
The taskwarrior team has been developing a companion app; timewarrior, and it has just released v1.0.0 (http://taskwarrior.org/news/news.20160821.html) Termux already packages taskwarrior (thank you, thank you) and it would be great to have the new time-tracking capabilities on our mobile devices.

thanks (again)

**Comment by fornwall** [comment]
Thanks for the suggestion!

I tried building timewarrior and encountered a problem described by the following note:

    In src/libshared/src/FS.cpp the <glob.h> file is included
    which is not provided by the Android platform. In Termux
    we have it in $TERMUX_PREFIX/include, which sould be found
    by DCMAKE_FIND_ROOT_PATH=$TERMUX_PREFIX? Works in
    taskwarrior for the src/FS.cpp file there.

Are you involved with the project and can look at this build problem (or could ask the right people)? I'm not that used to cmake, so it may be me missing something.

**Comment by linuxcaffe** [comment]
cloning and building timewarrior is slightly different from taskwarrior in
that "git clone --recursive bla bla" is required.. could that be it?

**Comment by linuxcaffe** [comment]
I let the taskwarrior/ timewarrior lead developer know about this stumbling block, and he opened an issue for it at https://bug.tasktools.org/browse/TW-1846. I also put out the call for assistance on freenode #taskwarrior, so maybe, just maybe, we can figure this thing out. Thanks for giving it some of your valuable attention, Mr fornwall, sir ;-)

**Comment by fornwall** [comment]
@linuxcaffe A timewarrior package is now available, install with `apt update && apt install timewarrior`!

**Comment by linuxcaffe** [comment]
and it works just fine, thanks!

**Comment by dbwest** [comment]
Does anybody have the timewarrior on-modify hook working with taskwarrior. Soooo important

**Comment by davidschnermann** [comment]
First thank you all for this great tools. I like it so much.
But I have the same question as dbwest just a few years later, so I hope someone has a solution.?

Does anybody have the timewarrior on-modify hook working with taskwarrior in termux?

**Comment by davidschnermann** [comment]
I got it. Just installed python3 and then it worked.
