### ISSUE TITLE
WiringPi package

### ISSUE THREAD

**Issue by KostasHelsinki** [termux/termux-packages#4111]
Hi all, 

Termux can be combined perfectly with a single board computer running Android. I have a NanoPi M4 from friendlyelec and I love runing Termux on it. I can have a simple and efficient operating system such as Android and at the same time have Mosquitto and Home Assistant running on it.  Now, my only problem is that I have troubles accessing and coding the GPIOs of my single board computer. WiringPi (wiringpi.com) is the ideal package for accessing GPIOs in single board computers. It would be perfect if we could have it as a package in Termux. Can someone help?

The closest I got was to follow this link: http://wiki.friendlyarm.com/wiki/index.php/WiringPi-Python_for_RK3399

but for this to work one needs : apt install git python-dev python-setuptools python3-dev python3-setuptools swig

and I couldn't install python-setuptools

Thanks in advance!

**Comment by xeffyr** [comment]
> and I couldn't install python-setuptools

`setuptools` as well as `pip` are already installed with python package.

You only need:
```
pkg install build-essential python-dev swig
pip install wiringpi
```

**Comment by xeffyr** [comment]
Termux does not package python modules, especially ones with native extensions.
