### ISSUE TITLE
pastebinit showing warnings

### ISSUE THREAD

**Issue by remo7777** [termux/termux-packages#4112]
![Screenshot_20190727-005755](https://user-images.githubusercontent.com/28594846/61977118-2d246700-b00b-11e9-90c2-58e4f4d70573.jpeg)
working good but warning is irritating...

**Comment by xeffyr** [comment]
It uses deprecated methods in python.
I have same warning on PC where python's version is 3.7.3.

**Comment by xeffyr** [comment]
Will be fixed in pastebinit `1.5-1`.
