### ISSUE TITLE
Stow 2.3.0: Can't locate Clone/Choose.pm (perl package)

### ISSUE THREAD

**Issue by OverkillGuy** [termux/termux-packages#4114]
**Problem description**
Stow 2.3.0 is broken on Termux, as it depends on Perl library "Clone/Choose" which isn't installed.
This dependency was removed in (as yet unreleased) 2.3.1, as the [Stow NEWS file](https://git.savannah.gnu.org/cgit/stow.git/tree/NEWS) says:

> ## Changes in version 2.3.1
> 
> ### Remove dependencies on Hash::Merge and Clone::Choose
> 
>    stow 2.3.0 added external runtime dependencies on Hash::Merge and Clone::Choose. Historically stow hasn't had runtime dependencies other than Perl itself, which is a useful property if you're managing the installation of Perl using stow; the bootstrapping instructions in stow's manual would need updating to describe how to install these two modules (and any dependencies they have now or in the future) as well.

```bash
$ pkg show stow
Package: stow
Version: 2.3.0
```

**Steps to reproduce**
Run `stow` with any argument.
```bash
$ stow --version
Can't locate Clone/Choose.pm in @INC (you may need to install the Clone::Choose module) (@INC contains: /data/data/com.termux/files/usr/share/perl/5.28.1 /data/data/com.termux/files/usr/lib/perl5/site_perl/5.28.2/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.28.2 /data/data/com.termux/files/usr/lib/perl5/5.28.2/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.28.2 .) at /data/data/com.termux/files/usr/bin/stow line 467, <DATA> line 22.
BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/bin/stow line 467, <DATA> line 22.
```

**Expected behavior**
```bash
$ stow --version
stow (GNU Stow) version 2.3.0
```

**Additional information**
```
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.73-g65a266a #1 SMP PREEMPT Sun Jul 7 16:09:51 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.1.0
Device manufacturer:
LGE
Device model:
Nexus 5X
```

**Comment by OverkillGuy** [comment]
Installing package via `cpan` didn't work (but then again I gave up when `cpan install XXX` gets mad and the problem isn't trivial to fix for a perl noob.

I guess we need to wait for 2.3.1 to be tagged to depend on it (bump package version+hash)?

**Comment by OverkillGuy** [comment]
I poked (referenced PR) for a release, will send email on mailing list if I don't hear back. 

In the interim, am attempting to backport the patch of GNU Stow that fixes this into termux-package.

**Comment by aspiers** [comment]
No need for the mail 😉 I'll try to make a release shortly. BTW very cool to hear people are using Stow on termux! I had no idea, and I'm a termux user myself.

**Comment by aspiers** [comment]
2.3.1 is now released.

**Comment by OverkillGuy** [comment]
> 2.3.1 is now released.

Thank you so much! I've created a quick PR to bump the package, this built fine on the docker container (but I didn't play around much with it after that)
