### ISSUE TITLE
CI resources

### ISSUE THREAD

**Issue by fkorotkov** [termux/termux-packages#4116]
Hey @xeffyr, our internal fraud detection mechanism at Cirrus CI started triggering for this repo since it's using quite a lot of resources of the community cluster. I checked and saw that you are using the maximum available configuration but in reality your builds don't use all 8 CPUs. Here is a screenshot of container activity for https://cirrus-ci.com/task/4999218794594304

<img width="742" alt="Screen Shot 2019-07-28 at 6 36 37 PM" src="https://user-images.githubusercontent.com/989066/62013865-2d397980-b167-11e9-9314-18587e18c7c6.png">

So the question is, do you really need that much CPU or you just set it to maximum?

**Comment by xeffyr** [comment]
I have set to 8 for faster builds. But if that causes issues, I can make it lower.
@fkorotkov 4 will be okay ?

**Comment by xeffyr** [comment]
Ended with following settings:
```
cpu: 4
memory: 8
```
Further reducing of `cpu` amount will have significant effect on build time.

**Comment by fkorotkov** [comment]
@xeffyr thanks! I just wanted to make sure that settings were expected. We have this mechanism just to prevent people from mining coins and activity in this repo was similar. 😅Thanks again!
