### ISSUE TITLE
apt-upgrade removes some -dev packages

### ISSUE THREAD

**Issue by stuart-little** [termux/termux-packages#4118]
I'm on Android 9, aarch64, running termux v0.72.

After the latest `apt full-upgrade` (Jul 29 2019, 4:32 GMT as I type this) some `-dev` packages were removed:

```
ibdb-dev libiconv-dev libxml2-dev openssl-dev
```
A repo search reveals this is because they're one version behind the main accompanying non-dev packages. For instance:

```
$ apt search libxml
Sorting... Done
Full Text Search... Done
libxml2/stable,now 2.9.9-6 aarch64 [installed]
  Library for parsing XML documents

libxml2-dev/stable 2.9.9-5 aarch64
  Development files for libxml2

libxml2-static/stable,now 2.9.9-6 aarch64 [installed]
  Static libraries for libxml2

libxml2-utils/stable 2.9.9-6 aarch64
  XML utilities
```

Is this temporary? Are the `-dev` packages currently being rebuilt?

**Comment by Grimler91** [comment]
This is intended behaviour, the files in the -dev packages (mostly the headers) are now included in the main package instead. See https://wiki.termux.com/wiki/No_more_-dev_packages

**Comment by stuart-little** [comment]
@Grimler91: understood, thanks!
