### ISSUE TITLE
Apt

### ISSUE THREAD

**Issue by AndreyTheHacker** [termux/termux-packages#4119]
after "apt update && apt upgrade" the following happens :

grep : not found ,
find not found : pkg install busybox or pkg install findutils,
(busybox already installed)

apt repository has error

**Comment by Grimler91** [comment]
You need to install grep and findutils to get `grep` and `find`, or use the busybox versions through `busybox grep` and `busybox find`. The symlinks `grep -> busybox grep` and `find -> busybox find` have been removed in a recent update.

**Comment by Emil-7** [comment]
Can I restore the symlinks?


`pkg upgrade` gives the following output:

`/data/data/com.termux/files/usr/bin/pkg: 22: /data/data/com.termux/files/usr/bin/pkg: id: not found
/data/data/com.termux/files/usr/bin/pkg: 22: [: -eq: unexpected operator
Ign:1 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:2 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:3 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:3 https://dl.bintray.com/grimler/game-packages-21 games Release
Hit:4 https://termux.net stable InRelease
Get:5 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:5 https://dl.bintray.com/grimler/science-packages-21 science Release
Err:6 https://dl.bintray.com/grimler/game-packages-21 games Release.gpg
  Unknown error executing apt-key
Err:4 https://termux.net stable InRelease
  Unknown error executing apt-key
Err:7 https://dl.bintray.com/grimler/science-packages-21 science Release.gpg
  Unknown error executing apt-key
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.bintray.com/grimler/game-packages-21 games Release: Unknown error executing apt-key
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://termux.net stable InRelease: Unknown error executing apt-key

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.bintray.com/grimler/science-packages-21 science Release: Unknown error executing apt-key
W: Failed to fetch https://termux.net/dists/stable/InRelease  Unknown error executing apt-key
W: Failed to fetch https://dl.bintray.com/grimler/game-packages-21/dists/games/Release.gpg  Unknown error executing apt-key
W: Failed to fetch https://dl.bintray.com/grimler/science-packages-21/dists/science/Release.gpg  Unknown error executing apt-key
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by Emil-7** [comment]
I consider this an open issue since the apt/pkg error has not been dealt with.

**Comment by xeffyr** [comment]
>  since the apt/pkg error has not been dealt with.

That's a completely different issue. And why it happened described at https://github.com/termux/termux-app/issues/1189#issuecomment-516133375.
