### ISSUE TITLE
CANNOT LINK EXECUTABLE "emacs": library "libdbus-1.so" not found

### ISSUE THREAD

**Issue by wordyallen** [termux/termux-packages#4120]
**Problem description**
Cannot run emacs

**Steps to reproduce**
Running a fresh install on x86_64. I run 
```
pkg install emacs
emacs
CANNOT LINK EXECUTABLE "emacs": library "libdbus-1.so" not found
```
**Expected behavior**
emacs should boot

**Additional information**
```
termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.178-16505-g1c7029432a2d #1 SMP PREEMPT Sun Jul 14 00:10:01 PDT 2019 x86_64 Android
Termux-packages arch:
x86_64
Android version:
9
Device manufacturer:
Google
Device model:
Google Pixelbook
```
Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by Grimler91** [comment]
Install `dbus` to make it work again. Seems latest emacs update linked against libdbus

**Comment by tomty89** [comment]
Should we build with `--without-bus` or list libdbus as dependency though?

**Comment by xeffyr** [comment]
For now I think better `--without-bus`, unless dbus provides useful functionality.

**Comment by xeffyr** [comment]
Should be fixed in https://github.com/termux/termux-packages/commit/89588b254d248d3eaa42b969205e65ecad4ff279.
