### ISSUE TITLE
Today's "pkg upgrade" broke some python modules (matplotlib and scipy)

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#4121]
**Problem description**
After today's "pkg upgrade" I can no longer use matplotlib and scipy (possibly for different reasons).

**Steps to reproduce**
```
$ ipython
Python 3.7.4 (default, Jul 28 2019, 22:33:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot as plt                                                                                                                                                                              
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a0d2faabd9e9> in <module>
----> 1 import matplotlib.pyplot as plt

/data/data/com.termux/files/usr/lib/python3.7/site-packages/matplotlib/pyplot.py in <module>
   2353     dict.__setitem__(rcParams, "backend", rcsetup._auto_backend_sentinel)
   2354 # Set up the backend.
-> 2355 switch_backend(rcParams["backend"])
   2356 
   2357 # Just to be safe.  Interactive mode can be turned on without

/data/data/com.termux/files/usr/lib/python3.7/site-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    219         else "matplotlib.backends.backend_{}".format(newbackend.lower()))
    220 
--> 221     backend_mod = importlib.import_module(backend_name)
    222     Backend = type(
    223         "Backend", (matplotlib.backends._Backend,), vars(backend_mod))

/data/data/com.termux/files/usr/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/data/data/com.termux/files/usr/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in <module>
     43 
     44 if _has_pil:
---> 45     from PIL import Image
     46 
     47 backend_version = 'v2.2'

/data/data/com.termux/files/usr/lib/python3.7/site-packages/PIL/Image.py in <module>
     93     # Also note that Image.core is not a publicly documented interface,
     94     # and should be considered private and subject to change.
---> 95     from . import _imaging as core
     96 
     97     if __version__ != getattr(core, "PILLOW_VERSION", None):

ImportError: dlopen failed: cannot locate symbol "jpeg_resync_to_restart" referenced by "/data/data/com.termux/files/usr/lib/python3.7/site-packages/PIL/_imaging.cpython-37m.so"...
```
As for "scipy" it used to come from @its-pointless 's repository, but today numpy and scipy were removed by "pkg upgrade". After that I tried "pkg install numpy" which failed because of depending on "python-dev" which seems to have been merged into "python". However, manually installing numpy via "pip install numpy" worked just fine (and I tested it together with PyFFTW --- all seems to work). However, doing the same for scipy failed "pip install scipy". And "pkg install scipy" fails as well, because it depends on the package "numpy" (not python package, but Debian package) which is non-existent, even though the python module "numpy" exists.

**Expected behavior**
importing matplotlib.pyplot (with backend set to "Agg") should produce no errors.

**Additional information**
Post output of command `termux-info`.
```
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.153-16123450 #2 SMP PREEMPT Wed Jun 12 13:21:47 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-T830
```

**Comment by xeffyr** [comment]
> ImportError: dlopen failed: cannot locate symbol "jpeg_resync_to_restart" referenced by "/data/data/com.termux/files/usr/lib/python3.7/site-packages/PIL/_imaging.cpython-37m.so"...

That's not todays upgrade.
libjpeg-turbo was rebuilt with `-DWITH_JPEG8=1` which changes ABI. Therefore all dependent things should be rebuilt in order to work.

Reinstalling `pillow` (pip may require `--no-cache-dir`) should fix the problem.

**Comment by tigran123** [comment]
@xeffyr Thank you, you are absolutely correct! So, the matplotlib problem is gone (tested now, it produces correct images which are then assembled via ffmpeg into movie, exactly as expected).

So, now it is only scipy that is problematic.

**Comment by Auxilus** [comment]
numpy installation is broken
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 numpy : Depends: python-dev but it is not installable
         Depends: libcrypt-dev but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by tigran123** [comment]
The numpy breakage is easily fixable by installing it manually via `pip install numpy` as I mentioned above.

**Comment by Auxilus** [comment]
Yes, I'm just reporting the broken dependency in the repo package

**Comment by xeffyr** [comment]
If @its-pointless can't rebuild/fix numpy/scipy, I can just repack deb files with fixed dependencies and post them here.

**Comment by xeffyr** [comment]
Fixed numpy for android 7+:

[numpy_1.16.3-1_aarch64.deb.gz](https://github.com/termux/termux-packages/files/3452318/numpy_1.16.3-1_aarch64.deb.gz)
[numpy_1.16.3-1_arm.deb.gz](https://github.com/termux/termux-packages/files/3452319/numpy_1.16.3-1_arm.deb.gz)
[numpy_1.16.3-1_i686.deb.gz](https://github.com/termux/termux-packages/files/3452320/numpy_1.16.3-1_i686.deb.gz)
[numpy_1.16.3-1_x86_64.deb.gz](https://github.com/termux/termux-packages/files/3452321/numpy_1.16.3-1_x86_64.deb.gz)

[debs are gzipped due to Github file type restriction]

**Comment by Auxilus** [comment]
Thanks!

**Comment by its-pointless** [comment]
i will fix this up today or tommorow don't worry

**Comment by xeffyr** [comment]
Closing as numpy package was updated on https://github.com/its-pointless/its-pointless.github.io.

**Comment by tigran123** [comment]
Thank you, yes, I confirm that it works fine.

**Comment by tigran123** [comment]
Well, that was on Samsung Galaxy Tab S4 (all fine), but on LG G4 I still get the following error:

```
$ pkg install numpy
Get:1 https://its-pointless.github.io/files termux InRelease [9176 B]
Hit:2 https://termux.net stable InRelease
Ign:3 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:4 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:5 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-21 games Release
Get:6 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:6 https://dl.bintray.com/grimler/science-packages-21 science Release
Fetched 9176 B in 2s (3146 B/s)                       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 numpy : Depends: python-dev but it is not installable
         Depends: libcrypt-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
$ apt show numpy
Package: numpy
Version: 1.16.3
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 16.3 MB
Depends: openblas, python-dev, libcrypt-dev
Homepage: http://www.numpy.org/
Download-Size: 2375 kB
APT-Sources: https://its-pointless.github.io/files termux/extras aarch64 Packages
Description: NumPy is the fundamental package for scientific computing with Python.


```

**Comment by tigran123** [comment]
Both devices are running the latest Termux 0.73.

**Comment by xeffyr** [comment]
@its-pointless haven't fixed packages for android-5.

**Comment by tigran123** [comment]
@xeffyr I am not using Android 5. This is on Android 6.

**Comment by xeffyr** [comment]
There 2 repositories:

1. One that used for Android 5 and 6.

2. One that used for Android 7 and higher.

**Comment by tigran123** [comment]
@xeffyr Thank you, now I understand. Well, it would be very nice if @its-pointless updates it for Android 6 as well, as LG G4 is very useful for "experimenting with numpy" while on the bus :)
