### ISSUE TITLE
Today's upgrade breaks shell scripts, rejects portable shebang

### ISSUE THREAD

**Issue by Fernal73** [termux/termux-packages#4123]
**Problem description**
Today's upgrade breaks scripts that use the following shebang : 
#! /usr/bin/env bash

The scripts worked earlier. 

Replacing the offending shebang with:
#!/bin/bash
resolves the issue. 

The message displayed is:
```
bash: {shellscriptname} /usr/bin/env: bad interpreter: No such file or directory
```

**Steps to reproduce**
Create a shell script with the offending shebang. 

**Expected behavior**
Shell script must execute without errors. 

**Additional information**
Post output of command `termux-info`.
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://its-pointless.github.io/files termux/extras
https://its-pointless.github.io/files termux/extras
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.31-perf-ge8c6508 #1 SMP PREEMPT Fri Jan 18 23:42:34 WIB 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.1.2

**Comment by xeffyr** [comment]
Install coreutils.

**Comment by Fernal73** [comment]
I have coreutils 8.31-2.

**Comment by xeffyr** [comment]
> I have coreutils 8.31-2

Should be `8.31-3`.

**Comment by Fernal73** [comment]
Install doesn't allow me that version. Terms it the latest version.

**Comment by xeffyr** [comment]
Reopening since coreutils `8.31-3` isn't available in termux.net. Waiting until @fornwall will build it.

**Comment by Fernal73** [comment]
Thank you very much!

**Comment by fornwall** [comment]
Sorry for the issue, there was a delay in deploying the packages in termux.net - now resolved.

Run `pkg up` to update!

**Comment by Fernal73** [comment]
Great! Thanks! One more for the Regression tests? I'm surprised that I'm the only one to complain!
