### ISSUE TITLE
Social-Engineering Toolkit (termux)

### ISSUE THREAD

**Issue by jsrtoday** [termux/termux-packages#4124]
1) Social-Engineering Attacks
2) Website Attack Vectors
8) HTA Attack Method

[!] Something went wrong, printing the error: [Errno 2] No such file or directory: '/etc/setoolkit/set.config'

**Comment by xeffyr** [comment]
Original setoolkit is unsupported by Termux. You have to apply a patch like https://github.com/termux/unstable-packages/blob/master/packages/setoolkit/fix-hardcoded-paths.patch.
