### ISSUE TITLE
Ngrok refused to provide me a ohising link please can i know why??

### ISSUE THREAD

**Issue by kezicodes** [termux/termux-packages#4127]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by kezicodes** [comment]
![Screenshot_2019-07-30-13-10-47](https://user-images.githubusercontent.com/52898343/62128157-bcf83880-b2cb-11e9-839b-9946233d3729.png)

**Comment by kezicodes** [comment]
Sowhat do i do

**Comment by xeffyr** [comment]
Wow, phishers again trying abuse ngrok & serveo....

https://twitter.com/trevordixon/status/1042714325666996225
