### ISSUE TITLE
it is possible to have nginx or similar to proxy control?

### ISSUE THREAD

**Issue by josinaldobarbosa** [termux/termux-packages#413]

**Comment by vaites** [comment]
I added Privoxy, but you need to build it yourself: https://github.com/termux/termux-packages/pull/406

**Comment by vishalbiswas** [comment]
Privoxy is merged into main repo now.
nginx is not gonna happen so easily. Very bad cross compile support on that one. Will need to write a cross compile mechanism from scratch.

**Comment by fornwall** [comment]
Ok, closing this as privoxy is available, and one can track https://github.com/termux/termux-packages/issues/255 for nginx!
