### ISSUE TITLE
Beanshell commands are not available

### ISSUE THREAD

**Issue by HemanthJabalpuri** [termux/termux-packages#4136]
@fornwall
Beanshell jar file may be not correctly dexed.
I have dexed bsh.jar from official one and it worked.
```bash
$ bsh
BeanShell 2.0b6 - by Pat Niemeyer (pat@pat.net)
bsh % print("hi");
// Error: EvalError: Command not found: print( java.lang.String ) : at Line: 1 : in file: <unknown file> : print ( "hi" )

bsh %
```

**Comment by HemanthJabalpuri** [comment]
@xeffyr
I have a small question that is not about above issue...

If I installed X pkg and it automatically installs pkg Y, then how can I know pkg Y is automatically installed from which pkg through command...?

**Comment by xeffyr** [comment]
>how can I know pkg Y is automatically installed from which pkg through command...?

`apt list` will show these packages as `[installed,automatic]`.

**Comment by HemanthJabalpuri** [comment]
@xeffyr 
But how we can know the **automatic** refers to which pkg....

i.e., how we can know pkgs that depends on specific package...

**Comment by xeffyr** [comment]
> But how we can know the automatic refers to which pkg....

Listing all automatic packages:
```
$ apt list | grep automatic

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

attr/stable,now 2.4.48-1 aarch64 [installed,automatic]
capstone/stable,now 4.0.1-3 aarch64 [installed,automatic]
glib/stable,now 2.60.6-1 aarch64 [installed,automatic]
libandroid-shmem/stable,now 0.2.1 aarch64 [installed,automatic]
libcap/stable,now 2.27-1 aarch64 [installed,automatic]
libffi/stable,now 3.2.1-4 aarch64 [installed,automatic]
libgnutls/stable,now 3.6.9-1 aarch64 [installed,automatic]
libidn2/stable,now 2.2.0-1 aarch64 [installed,automatic]
liblzo/stable,now 2.10-1 aarch64 [installed,automatic]
libnettle/stable,now 3.5.1-2 aarch64 [installed,automatic]
libnfs/stable,now 4.0.0-2 aarch64 [installed,automatic]
libpixman/stable,now 0.38.4-2 aarch64 [installed,automatic]
libssh2/stable,now 1.9.0-1 aarch64 [installed,automatic]
libunistring/stable,now 0.9.10-3 aarch64 [installed,automatic]
libxml2/stable,now 2.9.9-6 aarch64 [installed,automatic]
qemu-common/unstable,now 4.0.0-3 aarch64 [installed,automatic]
```

Checking specific packages - variant 1:
```
$ apt list | grep libxml2

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libxml2/stable,now 2.9.9-6 aarch64 [installed,automatic]
libxml2-static/stable 2.9.9-6 aarch64
libxml2-utils/stable 2.9.9-6 aarch64
```

Checking specific packages - variant 2:
```
$ apt show libxml2 2>/dev/null | grep APT-Manual-Installed
APT-Manual-Installed: no
```

> how we can know pkgs that depends on specific package...

Use `apt rdepends` (or `apt-cache rdepends`). Example for `libxml2`:
```
$ apt rdepends libxml2
libxml2
Reverse Depends:
  Depends: libxml2-static (= 2.9.9-6)
  Depends: qemu-utils
  Depends: qemu-system-x86_64-headless
  Depends: qemu-system-riscv64-headless
  Depends: qemu-system-riscv32-headless
  Depends: qemu-system-i386-headless
  Depends: qemu-system-arm-headless
  Depends: qemu-system-aarch64-headless
  Depends: metasploit
  Depends: lastpass-cli
  Depends: clamav
  Depends: openbabel
..............
```

**Comment by HemanthJabalpuri** [comment]
@xeffyr
Can you please dex this jar. In my mobile I am getting out of memory error.

https://repo1.maven.org/maven2/org/python/jython-standalone/2.5.3/jython-standalone-2.5.3.jar

Thanks

**Comment by avci21** [comment]
No command bahs found, did you mean:
 Command bash in package bash
 Command bat in package bat
 Command bsh in package beanshell
 Command as in package binutils
 Command bochs in package bochs from the x11-repo repository
 Command btfs in package btfs
 Command pphs in package ghostscript
 Command tabs in package ncurses-utils
 Command pass in package pass
![Screenshot_2021-09-13-09-07-36-645_com termux](https://user-images.githubusercontent.com/90591274/133032087-e39d5e0f-c5f2-44bc-84dc-9827514c51dd.jpg)k

**Comment by avci21** [comment]
No command bahs found, did you mean:
 Command bash in package bash
 Command bat in package bat
 Command bsh in package beanshell
 Command as in package binutils
 Command bochs in package bochs from the x11-repo repository
 Command btfs in package btfs
 Command pphs in package ghostscript
 Command tabs in package ncurses-utils
 Command pass in package pass
