### ISSUE TITLE
Alternatives mechanism

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#4137]
Looks like termux-packages lacks alternatives mechanism, see https://github.com/termux/termux-packages/issues/295#issue-157992271 , https://github.com/termux/termux-packages/issues/125#issuecomment-171376235 . I recommend to add update-alternative command (in Ubuntu it is contained in dpkg package) and make some packages with same functions use it to make it's implementation default (e.g. python and python2, coreutils and busybox, openbox and fluxbox, Xorg and Xwayland). Also $TERMUX_PREFIX/etc/alternatives dir can be added to $PATH before $PREFIX/bin and $PREFIX/applets to allow dpkg setup default (e.g.) ps (procps or busybox), ls (coreutils or busybox) or X (Xorg or Xwayland)  implementation.

**Link to home page and sources**
1. Home page: https://wiki.debian.org/Teams/Dpkg
2. Source code: https://git.dpkg.org/cgit/dpkg/dpkg.git/tree/utils/update-alternatives.c

**Additional information**
Dpkg is already available, but update-alternatives is not. Also packages do not support making itelf implementations default.

**Comment by xeffyr** [comment]
Got alternatives working:
```
$ update-alternatives --install $PREFIX/bin/editor editor $PREFIX/bin/micro 10
update-alternatives: using /data/data/com.termux/files/usr/bin/micro to provide /data/data/com.termux/files/usr/bin/editor (editor) in auto mode
$ update-alternatives --install $PREFIX/bin/editor editor $PREFIX/bin/nano 20
update-alternatives: using /data/data/com.termux/files/usr/bin/nano to provide /data/data/com.termux/files/usr/bin/editor (editor) in auto mode
$ update-alternatives --config editor
There are 2 choices for the alternative editor (providing /data/data/com.termux/files/usr/bin/editor).

  Selection    Path                                       Priority   Status
------------------------------------------------------------
* 0            /data/data/com.termux/files/usr/bin/nano    20        auto mode
  1            /data/data/com.termux/files/usr/bin/micro   10        manual mode
  2            /data/data/com.termux/files/usr/bin/nano    20        manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
update-alternatives: using /data/data/com.termux/files/usr/bin/micro to provide /data/data/com.termux/files/usr/bin/editor (editor) in manual mode
```

**Comment by xeffyr** [comment]
Closing since alternatives are implemented.
On android-5 will be available soon.
