### ISSUE TITLE
openmp support for clang

### ISSUE THREAD

**Issue by saeedSarpas** [termux/termux-packages#414]
Since you've changed the clang version to 3.8, do you have any plan to enable [openmp](http://llvm.org/releases/3.8.0/tools/clang/docs/ReleaseNotes.html#openmp-support-in-clang)?

**Comment by fornwall** [comment]
Clang is at version 4.0 now - but openmp support is not yet available (https://github.com/android-ndk/ndk/issues/9 may be relevant).

**Comment by joakim-noah** [comment]
Looks like its in the latest NDK r15, I can confirm it works when cross-compiling.  When using clang in Termux with the `-fopenmp` flag, it compiles fine but then complains that it can't find the library for `-lomp`.  All that's needed is to package up the pre-built OpenMP library from the NDK, or alternatively, build it from scratch.

**Comment by fornwall** [comment]
Thanks to @joakim-noah openmp is now enabled in version `clang_4.0.1-2` of the clang package which is available as an update!
