### ISSUE TITLE
Package Request:elvish

### ISSUE THREAD

**Issue by myfreess** [termux/termux-packages#4140]
Elvish is a friendly interactive shell and an expressive programming language. It runs on Linux, BSDs, macOS and Windows. Despite its pre-1.0 status, it is already suitable for most daily interactive use.

 https://github.com/elves/elvish

**Comment by Balint66** [comment]
## [Building elvish](https://github.com/elves/elvish#building-elvish)

use the above guide to build it with go.

## my implemantation in bash

```bash
##install elvish on termux
pkg install golang
pkg install make
go get github.com/elves/elvish
export GO111MODULE="on"
make get -C "$(go env GOPATH)/src/github.com/elves/elvish
export GO111MODULE="auto"
PATH="$PATH:$(go env GOPATH)/bin"
```
~~sorry i do not know how to make a package for this, but i think this bash script is more simple and faster.~~

**Comment by myfreess** [comment]
@Balint66

The only problem，cloning repo is so slow for me. I'm Chinese:V

@xeffyr elvish is well tested，add it to repo is easily ^_^

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install elvish
```
