### ISSUE TITLE
package `nim`: `nimble` and `koch` abort with `CANNOT LINK EXECUTABLE`

### ISSUE THREAD

**Issue by sschwarzer** [termux/termux-packages#4144]
Thank you for Termux! :-)

**Problem description**
With the `nim` package version 0.20.2, invoking `nimble` or `koch` on the command line fails with:
```bash
$ nimble --version
CANNOT LINK EXECUTABLE "nimble": library "libandroid-glob.so" not found
Aborted

$ koch --version
CANNOT LINK EXECUTABLE "koch": library "libandroid-glob.so" not found
Aborted
```

**Steps to reproduce**
See "Problem description"

**Expected behavior**
`nimble` and `koch` should print their respective versions.

**Additional information**
- The problem was already present before the `nim` 0.20.2 package, but I don't remember the version.
- The `nim` command is _not_ affected.
- A workaround for the described problem is setting
  ```
  export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
  ```
  After this, `nimble --version` and `koch --version` print their expected output.
- Post output of command `termux-info`.
  ```
  Updatable packages:
  All packages up to date
  Subscribed repositories:
  https://dl.bintray.com/grimler/science-packages-24 science/stable
  https://dl.bintray.com/grimler/game-packages-24 games/stable
  https://dl.bintray.com/termux/termux-packages-24 stable/main
  System information:
  Linux localhost 3.4.113-Deathly-1.0 #1 SMP PREEMPT Sat Jun 29 01:38:18 CDT 2019 armv7l Android
  Termux-packages arch:
  arm
  Android version:
  7.1.2
  Device manufacturer:
  samsung
  Device model:
  SM-T800
  ```

-----

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
Thanks, this is now fixed with https://github.com/termux/termux-packages/commit/771cd8f636a2392c0b294dcbdedacc576d1b7069.
