### ISSUE TITLE
sleep takes longer with screen off

### ISSUE THREAD

**Issue by deftdawg** [termux/termux-packages#4145]
**Problem description**

When the phone's screen shuts off commands that depend on time take much longer to execute... This effects 'sleep' and 'read -t' and perhaps other things.

```bash
# phone screen off
date; sleep 3; date 
Mon Aug  5 02:49:59 EDT 2019
Mon Aug  5 02:50:19 EDT 2019

# phone screen on
date; sleep 3; date 
Mon Aug  5 02:50:54 EDT 2019
Mon Aug  5 02:50:57 EDT 2019

# phone screen off
$ date
Mon Aug  5 02:52:51 EDT 2019
$ date
Mon Aug  5 02:52:52 EDT 2019
$ date
Mon Aug  5 02:52:53 EDT 2019
$ date
Mon Aug  5 02:52:54 EDT 2019
$ date
Mon Aug  5 02:52:54 EDT 2019
```

**Steps to reproduce**

* Login to phone via SSH
* Wait for screen to shut off
* run a ``date; sleep 5; date`` and see how long it takes

**Expected behavior**
The second date of 
``date; sleep 5; date`` 

should be 5 seconds after the first.

**Additional information**
Post output of command `termux-info`.

```
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Mon Jun 24 14:37:31 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
OnePlus
Device model:
ONEPLUS A5010
```

**Comment by xeffyr** [comment]
Not only `sleep` but everything will be executed longer. Android tries to put device's CPU into sleep mode and you have to either keep screen on or use wakelock and disable battery optimizations for Termux.
