### ISSUE TITLE
Suggestion: build python both with and without --enable-shared

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#4146]
I noticed that python is built with `--enable-shared` configure option:

```
$ ldd $PREFIX/bin/python3.7m
libandroid-support.so
libpython3.7m.so.1.0
libcrypt.so
libdl.so
libm.so
libc.so
```

This makes python about 20% slower (at least on x86_64 architecture, not sure about arm), which is why distributions usually build python twice, i.e. first with and then without `--enable-shared` option. The first build would produce the shared library (for those components that actually need it) and the second build would produce the fastest interpreter, i.e. built without `--enable-shared`. Why don't we do the same in Termux? I suppose before doing this (and thus making the build twice as long) one ought to verify whether on arm architecture there will be a significant performance improvement resulting from it.

**Comment by xtkoba** [comment]
At most a TUR matter, if ever.
