### ISSUE TITLE
Compiling with termcap linking failed

### ISSUE THREAD

**Issue by ViRb3** [termux/termux-packages#4147]
Trying to compile a program that uses termcap results in the following error:

```
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: cannot find -ltermcap
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

I can confirm that I am using `ncurses` revision `6` (latest, with termcap).

Related bit of `Makefile`:
```
LDLIBS +=  -ltermcap -lncurses
```

**Comment by fornwall** [comment]
Could you run `pkg up` and retry again?

**Comment by ViRb3** [comment]
Works perfectly, thank you!
