### ISSUE TITLE
Package Request: moreutils

### ISSUE THREAD

**Issue by mdomlop** [termux/termux-packages#4148]
**Package description**

`moreutils` is a growing collection of the unix tools that nobody thought to write long ago when unix was young.

So far, it includes the following utilities:

 - chronic: runs a command quietly unless it fails
 - combine: combine the lines in two files using boolean operations
 - errno: look up errno names and descriptions
 - ifdata: get network interface info without parsing ifconfig output
 - ifne: run a program if the standard input is not empty
 - isutf8: check if a file or standard input is utf-8
 - lckdo: execute a program with a lock held
 - mispipe: pipe two commands, returning the exit status of the first
 - parallel: run multiple jobs at once
 - pee: tee standard input to pipes
 - sponge: soak up standard input and write to a file
 - ts: timestamp standard input
 - vidir: edit a directory in your text editor
 - vipe: insert a text editor into a pipe
 - zrun: automatically uncompress arguments to command

Since termux is primarily a text-only environment, this set of small utilities is quite convenient to make users' lives easier on certain occasions.

**Link to home page and sources**
1. Home page: https://joeyh.name/code/moreutils/
2. Source code: http://deb.debian.org/debian/pool/main/m/moreutils/moreutils_0.63.orig.tar.xz

**Additional information**

Because it is a small set of simple utilities and is already packaged for Debian, I don't think it's complicated to include it in termux.

**Comment by kenneth-Q** [comment]
Due to getloadavg(use by parallel.c), it could build on android 9 API level 29.
I have no device running on android 9.
Sorry.

**Comment by xeffyr** [comment]
> it could build on android 9 API level 29

API 29 is Android Q.

It should be possible to obtain loadavg value from `sysinfo()`.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install moreutils
```

* Utility `parallel` is disabled currently (due to getloadavg()).
* Utility `chronic` is disabled due to external perl modules.
