### ISSUE TITLE
clang3.8 missing headers?

### ISSUE THREAD

**Issue by cydhaselton** [termux/termux-packages#415]
Hello,
When attempting to compile a program on termux that uses size_t in a typedef, I get the following error:
error: unknown type name '__size_t'

The code throwing the error:
typedef __size_t        size_t;

Grepping the usr/include folder for size_t does not turn up any headers.
I did some googling and from what I read, the necessary headers defining size_t (stddef.h) are compiler specific, which means that they're missing in the clang built for termux or they're in a location that clang cannot find them.

**Comment by fornwall** [comment]
Is `__size_t` supposed to be defined, or is it a thing of the past that should not be used? What are you trying to compile?

**Comment by cydhaselton** [comment]
I'm attempting to port [coreclr] as part of porting dotnet.  The build process looks for glob.h, which has the __size_t typedef.  

The glob.h header is not native to android, but there's a port for it…which is what I downloaded. Reference thread for glob.h port is [here](https://groups.google.com/forum/m/#!topic/android-ndk/vSH6MWPD0Vk)
(https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md)

**Comment by fornwall** [comment]
Ok, the glob.h file you've used seems to be FreeBSD-specific in the usage __size_t, which doesn't seem to be something portable or standardized, so I'm closing the issue.

You could either patch the file (replace __size_t with size_t), or specify something like `-D__size_t=size` when building it.

Another solution is to `apt install libandroid-glob-dev`, which provides the glob implementation used in Termux packages. This brings you `<glob.h>` which can be used as normal (and it doesn't use __size_t), and you need to link the the shared library providing the implementation: `-landroid-glob` .
