### ISSUE TITLE
influxDB

### ISSUE THREAD

**Issue by ingoiot** [termux/termux-packages#4152]
Database for use with node-red and mosquito

great addition to the already existing packages.
**Link to home page and sources**
1. Home page: https://www.influxdata.com/
2. Source code:https://github.com/influxdata/influxdb

**Comment by rpi-esp32** [comment]
thanks for this great pkg, working smooth except that the influxdb.conf file is not found in the default (/etc) directory and there is no way to find this file.  Amy idea where to find this file (without it one could not activate some services or adjust some settings).   
many thanks!
