### ISSUE TITLE
Speech recognition not working in python

### ISSUE THREAD

**Issue by Pavan-kalyan-thota** [termux/termux-packages#4154]
**Package description** 
I'm trying to make a speech recognition using python in termux my code is
![IMG_20190808_190321](https://user-images.githubusercontent.com/45842100/62707633-554e9580-ba0f-11e9-86b0-b7d7958caf8c.jpg)
![IMG_20190808_190346](https://user-images.githubusercontent.com/45842100/62707652-5ed7fd80-ba0f-11e9-8b21-16cf3834622f.jpg)
While running this iam struck at 
![IMG_20190808_190606](https://user-images.githubusercontent.com/45842100/62707775-a1013f00-ba0f-11e9-86f2-848ad5bcb095.jpg)
Can someone help me with this and suggest packages for future

**Comment by xeffyr** [comment]
I'm in doubt that pyaudio microphone input will work out-of-box.

**Comment by Pavan-kalyan-thota** [comment]
then which package supports microphone input

**Comment by its-pointless** [comment]
There is a pulseaudio mic input available i made (may have to edit pulseaudio configs to load module) and from there i have portaudio that relies on pulseaudio. From there pyaudio could work. Need to have  my apt repo added.

**Comment by its-pointless** [comment]
So yeah the pulseaudio mic input is distributed already via normal apt. Just not enabled by default.

**Comment by fahadali32** [comment]
i have also same problem

**Comment by creboy** [comment]
> There is a pulseaudio mic input available i made (may have to edit pulseaudio configs to load module) and from there i have portaudio that relies on pulseaudio. From there pyaudio could work. Need to have my apt repo added.

could you give more detail?
