### ISSUE TITLE
Octave documentation missing on Android 9 but present on Android 6

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#4155]
**Problem description**
When I run "octave" followed by "doc" it shows the documentation on LG G4 running Android 6 (though it is badly formatted, i.e. with some character codes like \344 etc) but says this on Samsung Galaxy Tab S4 running Android 9:

```
octave:1> doc
error: doc: unable to find the Octave info manual, Octave installation is incomplete
```

Octave was installed with `pkg install octave` on both devices. Both run the latest Termux 0.73.

**Comment by xeffyr** [comment]
Octave package is managed by @its-pointless.

**Comment by tigran123** [comment]
Ok, then the explanation is the same (only in reverse) as on the numpy/scipy, i.e. @its-pointless included documentation in the Android 5/6 built, but not in the Android 9 build.

**Comment by xeffyr** [comment]
Yes, there is a difference:
```
[xeffyr]:~:$ diff -rq octave/21/data octave/24/data
Only in octave/21/data/data/com.termux/files/usr: bin
Only in octave/24/data/data/com.termux/files/usr: include
Only in octave/21/data/data/com.termux/files/usr/lib: liboctave.so
Only in octave/21/data/data/com.termux/files/usr/lib: liboctinterp.so
Only in octave/21/data/data/com.termux/files/usr/lib: octave
Only in octave/24/data/data/com.termux/files/usr/lib: pkgconfig
Only in octave/21/data/data/com.termux/files/usr: share
```

**Comment by tigran123** [comment]
The good news is that "help command" works fine in both Android 6 and 9, so this issue can be closed. Also, I was pleasantly surprised that even plotting commands work using plain ASCII characters. For 3D plots it is not really useable, but for ordinary 2D plots it is OK. I wish there was a similar text terminal output driver as a matplotlib backend as well.
