### ISSUE TITLE
Report problems with the new support for on-device builds

### ISSUE THREAD

**Issue by buttaface** [termux/termux-packages#4157]
I've been trying it out in a fresh Termux, so I'll start. I'll note that there's at least three tiers of dependencies, with the bottom tier made up of some of the packages that are installed in [the new setup script for Termux](https://github.com/termux/termux-packages/blob/master/scripts/setup-termux.sh), which I purposely didn't run, let's call it Tier 1. Tier 1 is required to even run scripts/build/ from this repo. Tier 2 would be common build packages that are needed by many packages, but not by scripts/build/. Tier 3 would be the rest.

Here's my experience starting from scratch, my attempt to map part of the dependency tree by starting from the bottom:

I first tried to build ninja, but python was needed for buildorder.py in this repo and then clang to compile termux-elf-cleaner. After those two Tier 1 pre-built packages were installed, ninja wouldn't build, as its build script currently requires a pre-built ninja to build it. I'll patch that and submit a pull.

Next, I tried building kakoune, my editor of choice. That package provides a Makefile, so I had to build make, but these scripts require a pre-built make to build it, so I installed it. Kakoune would then build but fail when linking, missing several symbols from ncurses. So I tried building those ncurses packages, even though a couple are installed by default, by forcing a build.

ncurses requires the file package to build, but the file source wouldn't download, so I installed the package. Once the ncurses packages were all built, kakoune still wouldn't link, then I noticed a call to pkg-config in the build output that was failing, so I tried to build pkg-config.

pkg-config needs glib, which requires perl and meson to build. There's no package yet for meson though, and I figured perl would be too much work, so I installed those two packages. Finally, pkg-config requires itself to build, so I just ended up installing it.

At last, I got kakoune to build! :fireworks: Turns out the ncurses build wasn't necessary, the only problem was missing pkg-config.

I tried git next, which appears to build but then failed when installing the docs, as it requires asciidoc, for which I see no Termux package.

Finally, I tried to build the CMake package. It requires jsoncpp, which is built by CMake, and libarchive, which won't build because it expects posix_spawn. So I installed those two packages, and then the libuv dependency wouldn't build, because it requires automake.

Automake wouldn't build initially because it requires m4, which wouldn't build because it also wanted posix_spawn, so I installed the m4 pre-built package and Automake built. libuv then also needed libtoolize from the libtool package, so I built that one and finally got to CMake itself.

CMake depends on itself, but I saw a configure script in its source, so I turned off the TERMUX_PKG_FORCE_CMAKE flag for it and tried to build it that way. At first it seemed to build if I removed the --disable-dependency-tracking flag for the autotools script, but finally failed with another flag there. After that, it always gave strange errors in that final autotools invocation about flags missing, so I gave up and just installed the pre-built package for CMake.

I'll add some of these notes to the setup script for Termux, so people can see where the dependencies come from and work to remove them if they want.

Try out the new on-device build support for yourself and report similar dependencies like this here, so we can get more packages built on-device. I've tried out mostly Tier 1 and 2 packages, but build info for all packages is welcome.

**Comment by xeffyr** [comment]
> so I had to build make, but these scripts require a pre-built make to build it, so I installed it

You can't build make without `make`. Unless you are ready to type compilation commands manually.

> fail when linking, missing several symbols from ncurses. So I tried building those ncurses packages, even though a couple are installed by default

Probably because just `ncurses` isn't a complete package. It is splitted into `ncurses-ui-libs`.

> ncurses requires the file package to build

`./build-package.sh` requires file package too since it is used in `termux_step_massage()`.

> which wouldn't build because it also wanted posix_spawn

As I wrote in https://github.com/termux/termux-packages/issues/1756, environments & compiler aren't same.

Comparison of on-device config.h and cross-compiled: https://gist.github.com/xeffyr/e752f3ef4a040ea4c68279e47e2973ec

`posix_spawn` is enabled for on-device and disabled when using NDK somehow...

**Comment by xeffyr** [comment]
Glib has environment-specific issue too, just like `m4`:
```
[633/776] Compiling C object 'gio/6ae6c9e@@gio-2.0@sha/gunixmounts.c.o'.
FAILED: gio/6ae6c9e@@gio-2.0@sha/gunixmounts.c.o 
aarch64-linux-android-clang -Igio/6ae6c9e@@gio-2.0@sha -Igio -I../src/gio -I. -I../src/ -Iglib -I../src/glib -Igobject -I../src/gobject -Igmodule -I../src/gmodule -I/data/data/com.termux/files/usr/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu89 -Os -g -D_GNU_SOURCE -fno-strict-aliasing -Wall -Wimplicit-fallthrough -Wstrict-prototypes -Wunused -Wno-bad-function-cast -Wno-pedantic -Werror=declaration-after-statement -Werror=implicit-function-declaration -Werror=init-self -Werror=missing-include-dirs -Werror=missing-prototypes -Werror=pointer-arith -fstack-protector-strong -Oz -D__BIONIC__=1 -fPIC -pthread '-DG_LOG_DOMAIN="GLib-GIO"' -DGIO_COMPILATION '-DGIO_MODULE_DIR="/data/data/com.termux/files/usr/lib/gio/modules"' -fvisibility=hidden -MD -MQ 'gio/6ae6c9e@@gio-2.0@sha/gunixmounts.c.o' -MF 'gio/6ae6c9e@@gio-2.0@sha/gunixmounts.c.o.d' -o 'gio/6ae6c9e@@gio-2.0@sha/gunixmounts.c.o' -c ../src/gio/gunixmounts.c
../src/gio/gunixmounts.c:616:11: error: implicit declaration of function 'hasmntopt' [-Werror,-Wimplicit-function-declaration]
      if (hasmntopt (mntent, MNTOPT_RO) != NULL)
          ^
../src/gio/gunixmounts.c:616:11: warning: this function declaration is not a prototype [-Wstrict-prototypes]
../src/gio/gunixmounts.c:616:41: warning: comparison between pointer and integer ('int' and 'void *') [-Wpointer-integer-compare]
      if (hasmntopt (mntent, MNTOPT_RO) != NULL)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
../src/gio/gunixmounts.c:1115:11: error: implicit declaration of function 'hasmntopt' [-Werror,-Wimplicit-function-declaration]
      if (hasmntopt (mntent, "bind"))
```

**Comment by xeffyr** [comment]
Libarchive:
```
  CC       libarchive/filter_fork_posix.lo
/data/data/com.termux/files/home/.termux-build/libarchive/src/libarchive/filter_fork_posix.c:81:2: error: use of undeclared identifier 'posix_spawn_file_actions_t'
        posix_spawn_file_actions_t actions;
```

**Comment by buttaface** [comment]
Submitted a pull with some of this info and to make ninja build on-device, #4161.

**Comment by xeffyr** [comment]
It seems that make can be built without itself. It has script in its sources:
```
$ head -n2 build.sh.in 
#!/bin/sh
# Shell script to build GNU Make in the absence of any 'make' program.
```

**Comment by xeffyr** [comment]
Continuing my attempt of building on device as much as possible.
Many packages have common errors which means their fixes probably will be same.

libduktape:
```
/data/data/com.termux/files/usr/bin/python2 tools/configure.py --output-directory ./prep/nondebug --source-directory src-input --config-metadata config --option-file util/makeduk_base.yaml --line-directives
Traceback (most recent call last):
  File "tools/configure.py", line 29, in <module>
    import yaml
ImportError: No module named yaml
make: *** [Makefile:321: prep/nondebug] Error 1
```

**Comment by xeffyr** [comment]
Mpc:
```
[23/23] Linking target mpc.
FAILED: mpc 
aarch64-linux-android-clang  -o mpc 'mpc@exe/src_main.c.o' 'mpc@exe/src_list.c.o' 'mpc@exe/src_password.c.o' 'mpc@exe/src_status.c.o' 'mpc@exe/src_args.c.o' 'mpc@exe/src_format.c.o' 'mpc@exe/src_song_format.c.o' 'mpc@exe/src_tags.c.o' 'mpc@exe/src_util.c.o' 'mpc@exe/src_command.c.o' 'mpc@exe/src_queue.c.o' 'mpc@exe/src_output.c.o' 'mpc@exe/src_sticker.c.o' 'mpc@exe/src_tab.c.o' 'mpc@exe/src_idle.c.o' 'mpc@exe/src_message.c.o' 'mpc@exe/src_mount.c.o' 'mpc@exe/src_neighbors.c.o' 'mpc@exe/src_search.c.o' 'mpc@exe/src_options.c.o' 'mpc@exe/src_path.c.o' 'mpc@exe/src_charset.c.o' -L/data/data/com.termux/files/usr/lib -Wl,--no-undefined -Wl,--as-needed -pie -Wl,--gc-sections -Wl,-rpath=/data/data/com.termux/files/usr/lib,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--start-group /data/data/com.termux/files/usr/lib/libmpdclient.so -Wl,--end-group 
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: mpc@exe/src_charset.c.o: in function `charset_close':
/data/data/com.termux/files/home/.termux-build/mpc/build/../src/src/charset.c:164: undefined reference to `libiconv_close'
```

**Comment by buttaface** [comment]
Looking into having CMake set CMAKE_SYSTEM_NAME and CMAKE_HOST_SYSTEM_NAME to Android by default on device and avoid the NDK support, got it to work with a small CMake project, cmark, but I think I'll need to look into the Android/Linux platform Modules more for a more robust patch. I should have a CMake pull later this week.

**Comment by xeffyr** [comment]
Serf:
```
/data/data/com.termux/files/home/termux-packages/packages/serf/build.sh: line 14: scons: command not found
```

**Comment by xeffyr** [comment]
Weechat (gettext errored):
```
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/xgettext": cannot locate symbol "__unordtf2" referenced by "/data/data/com.termux/files/usr/lib/libgettextlib.so"...
[9/229] Building C object src/plugins/CMakeFiles/weechat_plugins_scripts.dir/plugin-script.c.o
ninja: build stopped: subcommand failed.
```

**Comment by xeffyr** [comment]
Finished my on-device "build session". Stats:

* Got 553 deb files. List: https://pastebin.com/PqGL9rvg
* Build directory took 13 GB of space in $HOME.
* Device's arch is aarch64.
* Device 2 times rebooted due to kernel oops (null pointer dereference).

Packages that are disabled for building on device are omitted. The same goes to packages which take long time to compile and few golang-based packages.

**Comment by buttaface** [comment]
Great to see so many packages building fine, that's 70% of [the 788 aarch64 deb packages](http://termux.net/dists/stable/main/binary-aarch64/). Why skip a few Go packages?

**Comment by xeffyr** [comment]
Because I will run out of space. Their build directories expand too much at the build time process and after building other packages I had only 2.6 GB on internal storage left.

```
$ du -hs *
32K	_cache
282M	gitea
135M	golang
31M	gotty
44M	hub
404M	hugo
632M	ipfs
795M	keybase
251M	micro
23M	obfs4proxy
163M	rclone
130M	restic
163M	syncthing
90M	tweego
```

I just built most of them. Golang & fzf are disabled for on-device builds. Gitea fails at:
```
go generate code.gitea.io/gitea code.gitea.io/gitea/cmd code.gitea.io/gitea/contrib/pr code.gitea.io/gitea/models code.gitea.io/gitea/models/migrations code.gitea.io/gitea/modules/auth code.gitea.io/gitea/modules/auth/ldap code.gitea.io/gitea/modules/auth/oauth2 code.gitea.io/gitea/modules/auth/openid code.gitea.io/gitea/modules/auth/pam code.gitea.io/gitea/modules/avatar code.gitea.io/gitea/modules/base code.gitea.io/gitea/modules/cache code.gitea.io/gitea/modules/context code.gitea.io/gitea/modules/cron code.gitea.io/gitea/modules/generate code.gitea.io/gitea/modules/gzip code.gitea.io/gitea/modules/highlight code.gitea.io/gitea/modules/httplib code.gitea.io/gitea/modules/indexer code.gitea.io/gitea/modules/indexer/issues code.gitea.io/gitea/modules/lfs code.gitea.io/gitea/modules/log code.gitea.io/gitea/modules/mailer code.gitea.io/gitea/modules/markup code.gitea.io/gitea/modules/markup/csv code.gitea.io/gitea/modules/markup/external code.gitea.io/gitea/modules/markup/markdown code.gitea.io/gitea/modules/markup/orgmode code.gitea.io/gitea/modules/metrics code.gitea.io/gitea/modules/minwinsvc code.gitea.io/gitea/modules/notification code.gitea.io/gitea/modules/notification/base code.gitea.io/gitea/modules/notification/indexer code.gitea.io/gitea/modules/notification/mail code.gitea.io/gitea/modules/notification/ui code.gitea.io/gitea/modules/options code.gitea.io/gitea/modules/pprof code.gitea.io/gitea/modules/private code.gitea.io/gitea/modules/process code.gitea.io/gitea/modules/public code.gitea.io/gitea/modules/recaptcha code.gitea.io/gitea/modules/search code.gitea.io/gitea/modules/secret code.gitea.io/gitea/modules/session code.gitea.io/gitea/modules/setting code.gitea.io/gitea/modules/ssh code.gitea.io/gitea/modules/structs code.gitea.io/gitea/modules/sync code.gitea.io/gitea/modules/templates code.gitea.io/gitea/modules/test code.gitea.io/gitea/modules/uploader code.gitea.io/gitea/modules/user code.gitea.io/gitea/modules/util code.gitea.io/gitea/modules/validation code.gitea.io/gitea/routers code.gitea.io/gitea/routers/admin code.gitea.io/gitea/routers/api/v1 code.gitea.io/gitea/routers/api/v1/admin code.gitea.io/gitea/routers/api/v1/convert code.gitea.io/gitea/routers/api/v1/misc code.gitea.io/gitea/routers/api/v1/org code.gitea.io/gitea/routers/api/v1/repo code.gitea.io/gitea/routers/api/v1/swagger code.gitea.io/gitea/routers/api/v1/user code.gitea.io/gitea/routers/api/v1/utils code.gitea.io/gitea/routers/dev code.gitea.io/gitea/routers/org code.gitea.io/gitea/routers/private code.gitea.io/gitea/routers/repo code.gitea.io/gitea/routers/routes code.gitea.io/gitea/routers/user code.gitea.io/gitea/routers/user/setting code.gitea.io/gitea/routers/utils
bindata.go
sed: Unknown option .bak (see "sed --help")
modules/options/options.go:9: running "sed": exit status 1
bindata.go
sed: Unknown option .bak (see "sed --help")
modules/public/public.go:22: running "sed": exit status 1
bindata.go
sed: Unknown option .bak (see "sed --help")
modules/templates/templates.go:9: running "sed": exit status 1
make: *** [Makefile:103: generate] Error 1
```

**Comment by xeffyr** [comment]
`posix_spawn` problem is fixed repository-wide.

**Comment by muhdali00001** [comment]
FB-NEW why it's not cracking the password if it's have been not nearly in wordlist why it's not cracking? Pls text to my this address https://www.facebook.com/abba.baje.10

**Comment by Grimler91** [comment]
I was hoping that using 
`test ! -z "$TERMUX_PKG_BUILD_DEPENDS" && echo "Build-Depends: $TERMUX_PKG_BUILD_DEPENDS" >> DEBIAN/control` 
would make it possible to install build-dependencies with `apt build-dep {PKG}`, but that wasn't how Build-Depends works unfortunately.

I suppose that creating a script `setup-termux.sh` that installs build dependencies like `setup-ubuntu.sh` does is the best way to make sure necessary tools for building packages

**Comment by xeffyr** [comment]
asciidoc is now available for installation (at time of writing for android-7 only). Problems with packages requiring asciidoc are now solved & packages building on device fine.

**Comment by buttaface** [comment]
Is there a regression with CMake where it no longer detects CMAKE_HOST_SYSTEM_PROCESSOR and CMAKE_SYSTEM_PROCESSOR, returning "Process failed because: No such file or directory" instead? I've been making the aforementioned modifications to set CMAKE_SYSTEM_NAME to Android in Termux, then I started hitting strange errors for CMake projects that check the host processor, which I hadn't seen before. I checked with stock CMake 3.15.2 on another device using the Android-5 package repo and I see the problem there too, which makes me think this might be tied to all the recent busybox/coreutils changes, not CMake?

To be precise, [this is the invocation of uname -m that breaks now](https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/CMakeDetermineSystem.cmake#L47). Just check that variable in a CMake project by adding this line, `message(STATUS "What is the host proc? ${CMAKE_HOST_SYSTEM_PROCESSOR")` and you will likely see that error, which I'm pretty sure is a recent regression.

**Comment by dirapratama** [comment]
https://github.com/4L13199/LITESPAM .

**Comment by happysmash27** [comment]
So has anyone figured out which package provides intltool, if it even exists?

**Comment by Grimler91** [comment]
@happysmash27 intltool provides `intltool`. We haven't packaged it though since it requires perl modules, see https://github.com/termux/termux-packages/issues/3409 and https://github.com/termux/termux-packages/issues/776.
