### ISSUE TITLE
libiconv header file conflict during apt upgrade

### ISSUE THREAD

**Issue by Harshiv-Patel** [termux/termux-packages#4158]
After downloading all the packages:

`reparing to unpack .../libiconv_1.16-3_arm.deb ...
Unpacking libiconv (1.16-3) over (1.16-2) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/libiconv_1.16-3_arm.deb (--unpack):
trying to overwrite '/data/data/com.termux/files/usr/include/iconv.h', which is also in package libandroid-support-dev 22-1
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/libiconv_1.16-3_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)`

**Problem description**
As in the log above, there is "$PREFIX/include/iconv.h" file conflict as file exists for both libiconv and libandroid-support-dev during apt upgrade.

**Steps to reproduce**
do `apt upgrade`

**Expected behavior**
Upgrade should be completed w/o any issue

**Additional information**

**Comment by xeffyr** [comment]
`pkg rm libiconv-dev libandroid-support-dev`.

**Comment by Harshiv-Patel** [comment]
and reinstall afterwards ?

**Comment by xeffyr** [comment]
Dev packages are no longer provided. They are replaced by "main":

libiconv-dev => libiconv.
