### ISSUE TITLE
LLVM static libraries missing

### ISSUE THREAD

**Issue by kb-1000** [termux/termux-packages#4159]
**Problem description**
I got a problem with my LLVM-based code, and wanted to debug it. Until recently, I could link in the libLLVM*.a files, which at least provided some debug info. Now, they're gone. It's impossible to debug this way, so what about dropping `gdb` and `lldb` too if you like that?

**Steps to reproduce**
1. `pkg install libllvm`
2. Try linking in all LLVM components statically using llvm-config

**Expected behavior**
It should produce an executable where gdb can at least map addresses to function names, but it produces nothing at all.

**Additional information**
```
Updatable packages:
qemu-common/x11 1:3.1.0-2 aarch64 [upgradable from: 4.0.0-4]
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.71-perf-g5d9b58b #1 SMP PREEMPT Thu Jun 20 14:37:26 CEST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.1.0
Device manufacturer:
bq
Device model:
Aquaris X Pro
```

**Comment by xeffyr** [comment]
**Static libraries are in a separate package !**
