### ISSUE TITLE
BLX, error: instruction requires: armv5t

### ISSUE THREAD

**Issue by IamPARANOID** [termux/termux-packages#4176]
I am attempting to compile qtwebkit within qtbase within phantomjs, however I run into the issue of it making calls that do not apparently exist for ARMv7l (my CPU).

Read elsewhere that this could be a gcc/libc issue, generating the wrong assembly code, or it's qmake or some such jargon falsely identifying the system/architecture, however I find this further confusing since Termux does not support GCC, and uses Clang.

Another thing I read, suggested the solution was to write what BLX does elsewhere in regular ARM assembly and call that code.

The file in question is "JITStubs.cpp".
I'm a bit out of my depth on this issue, any insight or suggestions on what to do would be helpful.

```
<inline asm>:9:1: error: instruction requires: armv5t
blx r0
^
```

**Comment by xeffyr** [comment]
Isn't related to https://github.com/termux/termux-packages/issues/3686 ?

**Comment by IamPARANOID** [comment]
@xeffyr Probably is related, not sure why that issue didn't come up in my searching.
So then, I need to somehow tell it to specifically target arm7l?

**Comment by xeffyr** [comment]
You can specify target by passing argument like ` --target=armv7a-linux-androideabi` to clang

**Comment by IamPARANOID** [comment]
> You can specify target by passing argument like ` --target=armv7a-linux-androideabi` to clang.

This 'fixed' my very specific issue/error, thanks.
Don't know if I should close this or not, I defer.

**Comment by xeffyr** [comment]
Then continuing in https://github.com/termux/termux-packages/issues/3686.
