### ISSUE TITLE
CMUS status display over bluetooth

### ISSUE THREAD

**Issue by doggydoggywoofwoof** [termux/termux-packages#4181]
I play music using cmus on termux. When connecting to the car over bluetooth no track, album, artist or album art information is transmitted. Is there a way to do this? Do I need a specific status display program?

It would also be nice to have status display in an android notification about the current song, with album art displayed, and that might be part of what I need anyway.

**Comment by xeffyr** [comment]
> Is there a way to do this?

No. Since cmus does sound output through PulseAudio, Android has no idea what is played.

> It would also be nice to have status display in an android notification about the current song

This more related to Termux:API, since only it can display Android notifications. But it is standalone and shouln't be used internally by console applications (which we keep "vanilla" as much as possible).

**Comment by doggydoggywoofwoof** [comment]
You can configure cmus to not use pulse audio.

Just because you think I shouldn't do something doesn't mean it shouldn't be done.

You shouldn't just close the issue.

**Comment by doggydoggywoofwoof** [comment]
Why not just leave it for someone else to look at if you don't want to? You clearly don't understand cmus anyway.

**Comment by xeffyr** [comment]
> Why not just leave it for someone else to look at

If issue closed it doesn't mean that it is disappeared.

> if you don't want to

As I wrote above, cli packages are keep "vanilla" as much as possible.

Cutting off pulseaudio (which is **base** requirement) will require to rewrite [cmus](https://github.com/cmus/cmus), at least audio part.

It also interesting which alternative you suggest to replace PulseAudio.

2 things that I'm against:

1. Modifying package in way that makes it not same as original.

2. Enforcing usage of Android API (in such case notifications, additional info for bluetooth, etc...) in **cli** program.

> You clearly don't understand cmus anyway.

You perhaps clearly understand everything. Then submit a PR implementing your requests.

**Comment by doggydoggywoofwoof** [comment]
Surely you wouldn't need to modify existing packages to do this? I don't see why you would think you would need to. This isn't about rewriting cmus or forcing it to use android API. 

You are exaggerating what I've said because you don't understand, it in no way mean I understand everything.

**Comment by Grimler91** [comment]
To obtain something like this we would probably need to enhance termux-api to be able to handle play/pause/now playing stuff, and then write a program that gets information from cmus and passes it on to the new termux-api addon.

An enhancement to termux-api to handle play/pause/now playing would be nice, we could convert this issue into a feature request in the termux-api repo.
