### ISSUE TITLE
ldc (ldc2) is not working since last update.

### ISSUE THREAD

**Issue by EmTee70** [termux/termux-packages#4185]
when calling it I just get a "Segementation fault"

There was an minor upgrade to 1.13.0-3 which has this issue.

My system is: aarch64 Android 7.0 Blackview BV6000

**Comment by xeffyr** [comment]
How you are calling it ?

I'm able not only just call it, but compile sample with the latest `ldc2` version:
```
$ cat > main.d
import std.stdio;
void main() 
{ 
 writefln("Hello World!");
}
$ ldc2 main.d
$ ./main
Hello World!
```

**Comment by xeffyr** [comment]
Post output of `termux-info`. Just `aarch64 Android 7.0 Blackview BV6000` isn't enough.
It matters which repository (api 21 or 24) you are using.

**Comment by EmTee70** [comment]
Hmm: This is my output:

```
termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.35 #6 SMP PREEMPT Sat Jul 8 13:49:32 CST 2017 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.0
Device manufacturer:
Blackview
Device model:
BV6000
```
And even `ldc2 --version` gives the segmentation fault

**Comment by xeffyr** [comment]
![Screenshot_1565884165](https://user-images.githubusercontent.com/25881154/63107402-9144a600-bf8d-11e9-9bc7-6ce16e6d005a.png)

So these segfaults actually same as in https://github.com/termux/termux-packages/issues/3990.

libc++ is broken on https://termux.net

**Comment by xeffyr** [comment]
Will be fixed with https://github.com/termux/termux-packages/issues/3990 in https://github.com/termux/termux-packages/pull/4191.

**Comment by EmTee70** [comment]
Just got the updated libc++ (20-1), but now I have to wait on an updated ldc2? Is that right?

**Comment by EmTee70** [comment]
LDC ins now updated, too! Error is gone!

**Comment by sr-tream** [comment]
after update ldc to 1.17 it crashed now

**Comment by xeffyr** [comment]
1.17 is outdated -https://github.com/termux/termux-packages/blob/android-5/packages/ldc/build.sh#L7.
