### ISSUE TITLE
Software semaphores

### ISSUE THREAD

**Issue by he77789** [termux/termux-packages#4186]
**Package description**
Currently, there is no working sem-open on android. Can we intercept the calls on Termux level and provide a software replacement for it?

**Additional information**
Have you compiled or tried to compile the package on device?
For example, trying to use the python multiprocessing package only works with multiprocessing.Process , and multiprocessing.Pool won't work. This causes large slowdown in multithreaded processes because of GIL. Also, quite a bit of packages depend on this function, but when this pops up, it is usually a warning so people just say "just ignore it" and not much is done for this.

**Comment by xeffyr** [comment]
Something that most likely won't be implemented. We don't have people who will work on this.
