### ISSUE TITLE
phpmyadmin

### ISSUE THREAD

**Issue by GRajin** [termux/termux-packages#4190]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page: https://www.phpmyadmin.net/
2. Source code: https://github.com/phpmyadmin/phpmyadmin

**Additional information**
Have you compiled or tried to compile the package on device? No
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
So, what prevents you from obtaining its zipfile and extracting it into server's webroot ?
`php` and `apache2` are available.

**Comment by GRajin** [comment]
I want this package to run the graphical window of mysql[Mariadb] in chrome.
