### ISSUE TITLE
strip .comment section from crt{begin,end}*.o so -fno-ident works

### ISSUE THREAD

**Issue by landfillbaby** [termux/termux-packages#4192]
**Problem description**
when compiling an executable with `clang -fno-ident`, a `.comment` section is still present in the output, due to being copied from `crtbegin_dynamic.o`, and has to be manually stripped with `strip -R.comment`
**Steps to reproduce**

    $ echo 'int main(){}'|clang -fno-ident -s -xc - -o ./nullprogram
    $ readelf -x.comment ./nullprogram
    Hex dump of section '.comment':
      0x00000000 416e6472 6f696420 28353232 30303432 Android (5220042
      0x00000010 20626173 6564206f 6e207233 34363338  based on r34638
      0x00000020 39632920 636c616e 67207665 7273696f 9c) clang versio
      0x00000030 6e20382e 302e3720 28687474 70733a2f n 8.0.7 (https:/
    (...)
**Expected behavior**

    readelf: Warning: Section '.comment' was not dumped because it does not exist!

**Additional information**
<details><summary>termux-info</summary>

    Updatable packages:
    All packages up to date
    Subscribed repositories:
    https://dl.bintray.com/termux/termux-packages-24 stable/main
    System information:
    Linux localhost 4.4.111-16371805 #1 SMP PREEMPT Tue Jul 9 20:19:03 KST 2019 aarch64 Android
    Termux-packages arch:
    aarch64
    Android version:
    9
    Device manufacturer:
    samsung
    Device model:
    SM-A530F
</details>

**Comment by xeffyr** [comment]
Android NDK doesn't strip it as well. I'm not sure that this is Termux-specific issue.
Does comment section cause problems ?

**Comment by landfillbaby** [comment]
it's just a waste of space really, it doesn't do anything

**Comment by xeffyr** [comment]
Option `-fno-ident` responsible for deleting `.ident` section, but not `.comment`.

```
$ echo "int main(){}" > test.c
$ clang -S test.c
$ cat test.s
	.text
	.file	"test.c"
	.globl	main                    // -- Begin function main
	.p2align	2
	.type	main,@function
main:                                   // @main
// %bb.0:
	mov	w0, #0
	ret
.Lfunc_end0:
	.size	main, .Lfunc_end0-main
                                        // -- End function

	.ident	"clang version 8.0.0 (tags/RELEASE_800/final)"
	.section	".note.GNU-stack","",@progbits
```

```
$ clang -S -fno-ident test.c
$ cat test.s
	.text
	.file	"test.c"
	.globl	main                    // -- Begin function main
	.p2align	2
	.type	main,@function
main:                                   // @main
// %bb.0:
	mov	w0, #0
	ret
.Lfunc_end0:
	.size	main, .Lfunc_end0-main
                                        // -- End function

	.section	".note.GNU-stack","",@progbits
```

**Comment by landfillbaby** [comment]
https://sourceware.org/binutils/docs/as/Ident.html
"When using ELF, comments are emitted to the .comment section."
