### ISSUE TITLE
Problem While installing pkg

### ISSUE THREAD

**Issue by abhipujari23** [termux/termux-packages#4193]
I have updated termux to the latest version available.
When I am installing a package using code :
pkg install php

It asks If I want to continue and If I select 'n' even the  it starts downloading..
Below is the exact copy of the whole situation.

$ pkg install php
Skipped some part as it is reading the packages
Reading package lists... Done
Building dependency tree
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  fontconfig freetype libgd libjpeg-turbo libpng libtiff
  libwebp libxml2
The following NEW packages will be installed:
  fontconfig freetype libgd libjpeg-turbo libpng libtiff
  libwebp libxml2 php
0 upgraded, 9 newly installed, 0 to remove and 4 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 53.0 MB of additional disk space will be used.

Do you want to continue? [Y/n] n  //Here I have given input n but downloading starts

Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main arm libpng arm 1.6.37-2 [190 kB]
Get:2 https://dl.bintray.com/termux/termux-package

**Comment by xeffyr** [comment]
Can't reproduce issue.

![Screenshot_20190817-130619_Termux](https://user-images.githubusercontent.com/25881154/63209935-0cbe6880-c0f0-11e9-8dea-ee6945c214d4.png)

**Comment by xeffyr** [comment]
Since nothing input-related was changed in `apt` and issue was reported only by you now. I guess the problem lying somewhere in your keyboard (some of them may append additional bytes) or OS.
