### ISSUE TITLE
Package request: gumbo-parser

### ISSUE THREAD

**Issue by andermirik** [termux/termux-packages#4194]
Its need to compile my vk bot on Termux

**Comment by RossComputerGuy** [comment]
Can't you use gumbolib-static?

**Comment by andermirik** [comment]
gumbolib-static? What shall i do to install it?

**Comment by RossComputerGuy** [comment]
`pkg install gumbolib-static`

**Comment by andermirik** [comment]
$pkg install gumbolib-static
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable Release [6061 B]
Hit:4 https://dl.bintray.com/termux/termux-packages-24 stable Release
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:6 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:6 https://dl.bintray.com/grimler/science-packages-24 science Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
11 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gumbolib-static

**Comment by RossComputerGuy** [comment]
Looks like gumbolib is not in the repository, how did you install gumbolib?

**Comment by andermirik** [comment]
I didn't installed it. I am just porting my cpp bot from linux to termux xd

**Comment by RossComputerGuy** [comment]
Oh, then install it from source

**Comment by xeffyr** [comment]
What is gumbolib ?
Is it https://github.com/google/gumbo-parser ?

**Comment by andermirik** [comment]
Yes. it is gumbo-parser from google.

**Comment by xeffyr** [comment]
Added in https://github.com/termux/termux-packages/commit/98a3f2132d3f4bb706e366ae2d039d076d07e2ef

```
pkg install gumbo-parser
```

**Comment by andermirik** [comment]
thx you <3
