### ISSUE TITLE
[Android]Segmentation fault on sync

### ISSUE THREAD

**Issue by Broky** [termux/termux-packages#4196]
Syncing on my Android tablet results in Segmentation fault. The server was just set up as on my PC where it worked fine.

It only applies to 
`task sync` and `task sync init`
The rest of the program works fine as expected.

Given similar reports, the output of `uname -a`:
`Linux localhost 3.18.14-15260192 #1 SMP PREEMPT Thu Jan 24 11:55:50 KST 2019 armv81 Android`
Output of `apt show taskwarrior`:
`Package: taskwarrior
Version: 2.5.1-7`

**Comment by RossComputerGuy** [comment]
Can you use strace on the command and paste the last lines?

**Comment by Broky** [comment]
Nevermind, the problem was a bad cert file on my end. My apologies.
