### ISSUE TITLE
qemu-user ignores the -L parameter

### ISSUE THREAD

**Issue by FTC55** [termux/termux-packages#4198]
**Problem description**
When trying to run a dynamically linked executable in qemu usermode (specifically i386 and x86-64 but possibly on all of them) even when the path to the loader is specified with the parameter "-L", the output is similar to the following: 
``` /lib64/ld-linux-x86-64.so.2: No such file or directory ```
which is a clearly invalid path that completely disregards the one provided.
**Steps to reproduce**
### qemu-x86_64
I mostly followed the guide [here](https://wiki.debian.org/QemuUserEmulation) under the section "Running dynamically linked executables" except I downloaded the libc6 package [here](https://packages.debian.org/buster/libc6-amd64) and manually extracted it in a folder with 
```dpkg -x```
and used its path as the qemu -L argument as specified in the guide.
**Expected behavior**
I expected the executable to get correctly linked and executed.
**Additional information** 
Updatable packages: 
apache2/stable 2.4.41 aarch64 [upgradable from: 2.4.39-2] 
bash/stable 5.0.9 aarch64 [upgradable from: 5.0.7-5]
dash/stable 0.5.10.2-2 aarch64 [upgradable from: 0.5.10.2-1
]
gawk/stable 5.0.1-4 aarch64 [upgradable from: 5.0.1-3] 
git/stable 2.22.1 aarch64 [upgradable from: 2.22.0] 
libc++/stable 20-1 aarch64 [upgradable from: 20] 
libopus/stable 1.3.1-3 aarch64 [upgradable from: 1.3.1-2]
libtalloc/stable 2.1.14-3 aarch64 [upgradable from: 2.1.14-
2]
termux-elf-cleaner/stable 1.7 aarch64 [upgradable from: 1.6
-1]
unzip/stable 6.0-5 aarch64 [upgradable from: 6.0-4] 
wireless-tools/root 30pre9-2 aarch64 [upgradable from: 30pr
e9-1] 
Subscribed repositories:
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable
/main
https://dl.bintray.com/grimler/termux-root-packages-21 root
/stable
https://Auxilus.github.io termux/extras
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 4.4.111-16290088 #1 SMP PREEMPT Wed Jun 26 
16:57:13 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-G950F

**Comment by xeffyr** [comment]
> and used its path as the qemu -L argument as specified in the guide.

You followed guide or specified command according to file system layout in Termux ?

Post exact command you executed as things from guide like `-L /usr/arm-linux-gnueabihf` may not work.

**Comment by xeffyr** [comment]
I figured out what happens. You are running into https://stackoverflow.com/questions/47625104/overriding-the-dynamic-linker-path?noredirect=1&lq=1.

QEMU uses hardcoded path to the interpreter. And if you are **carefully** read the [guide](https://wiki.debian.org/QemuUserEmulation) you provided, you will found that on Debian the  libc is installed with
```
sudo dpkg --add-architecture armhf
sudo apt-get update
sudo apt-get install libc6:armhf
```
into **system**, so linker is available in `/lib` (`/lib64`) and not in LD_PREFIX.

`QEMU_LD_PREFIX` is used for different purposes.

**Comment by xeffyr** [comment]
Use
```
~ $ dpkg-deb -x libc6-amd64_2.28-10_i386.deb LIBC_PREFIX
~ $ qemu-x86_64 -L ./LIBC_PREFIX ./your/command
```

In this case it doesn't throw `/lib64/ld-linux-x86-64.so.2: No such file or directory`.

**Comment by FTC55** [comment]
First time i tried yes, i had used the command according to the termux filesystem layout. The only difference from what you told me to use is that i was using dpkg instead of dpkg-deb. Anyways i tried it and if i set it to the root of LIBC_PREFIX it just hangs and i have to Ctrl + C. If i set it to the lib64 subfolder it just gives the same error about the linker not being found.

**Comment by xeffyr** [comment]
> it just hangs

qemu hangs for me as well.
No fix for that currently.

**Comment by FTC55** [comment]
I was hoping to get it working, but thanks anyways, at least now i know what i was doing wrong. Should I open a different issue about qemu hanging?

**Comment by xeffyr** [comment]
Not needed.
I will try to downgrade it to 3.1.0 today, which should work.

**Comment by xeffyr** [comment]
QEMU is now downgraded to 3.1.0 and works. Tried simple x86_64 program:
```
~ $ file x64_test 
x64_test: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0bef85fc0cff16d70b7db0d26c437d26ccd8dc50, for GNU/Linux 3.2.0, not stripped
~ $
~ $ qemu-x86_64 -L LIBC_PREFIX ./x64_test 
qemu-x86_64 works
~ $
```

**Comment by ShashaankHari** [comment]
> 
> 
> Use
> 
> ```
> ~ $ dpkg-deb -x libc6-amd64_2.28-10_i386.deb LIBC_PREFIX
> ~ $ qemu-x86_64 -L ./LIBC_PREFIX ./your/command
> ```
> 
> In this case it doesn't throw `/lib64/ld-linux-x86-64.so.2: No such file or directory`.

i followed your step but i still get the same error, also i extracted it to $PREFIX usr folder of termux
my commands were 
dpkg-deb -x libc6-amd64_2.28-10.deb $PREFIX (usr in files termux)
qemu-x86_64 -L ./$PREFIX keepass.Appimage

**Comment by xeffyr** [comment]
Instead of `./$PREFIX`, use `$PREFIX` or other absolute path to where your files were extracted. However I do not guarantee that you will be able to run appimage. On Android, it requires either root or word-accessible `/dev/fuse` - that's at least, as some appimages have more dependencies than just libc.

**Comment by ShashaankHari** [comment]
> 
> 
> Instead of `./$PREFIX`, use `$PREFIX` or other absolute path to where your files were extracted. However I do not guarantee that you will be able to run appimage. On Android, it requires either root or word-accessible `/dev/fuse` - that's at least, as some appimages have more dependencies than just libc.

i ran the whole thing under root(I am rooted)
