### ISSUE TITLE
Package request: racket

### ISSUE THREAD

**Issue by goodmind** [termux/termux-packages#42]

**Comment by goodmind** [comment]
https://packages.debian.org/sid/lisp/racket
https://packages.debian.org/sid/racket-common

**Comment by fornwall** [comment]
Thanks for the suggestion! I started a [wiki page to keep track of package suggestions](https://github.com/termux/termux-packages/wiki/Package-suggestions) and have added Racket there!

**Comment by Neo-Oli** [comment]
Hi, I am re-opening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by goodmind** [comment]
👍

**Comment by justinfay** [comment]
:+1:

**Comment by goodmind** [comment]
Any updates on this?

**Comment by goodmind** [comment]
#463

**Comment by y2kbugger** [comment]
+1

**Comment by brandon-atkinson** [comment]
:+1:

**Comment by its-pointless** [comment]
Iv got it kind of working on arm and i686 packages on my repo.... 
I have no idea how to go from here though.

**Comment by xeffyr** [comment]
Package is now available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install racket
```

I didn't tested it well, but seems working...
