### ISSUE TITLE
I am having trouble to start parrot os in termux  when i write start parrot.sh it says like this " proot warning: can't sanitize binding "debian-fs/root": No such file or directory   proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directoryproot info: default working directory is now "/"                                    proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/debian-fs, cwd = /, $PATH=(null))              fatal error: see `proot --help`" 

### ISSUE THREAD

**Issue by blackshadow101** [termux/termux-packages#4200]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by blackshadow101** [comment]
Hey man I have totourial for it and I have did what is expected from me but
it doesn't work

**Comment by blackshadow101** [comment]
You can see it now clearly plz help me

On Aug 19, 2019 1:15 PM, "shadow last" <zahirseid101@gmail.com> wrote:

Hey man I have totourial for it and I have did what is expected from me but
it doesn't work

**Comment by xeffyr** [comment]
We are not debugging third-party scripts.
