### ISSUE TITLE
Path allocation in su should use directories

### ISSUE THREAD

**Issue by gossbill** [termux/termux-packages#4208]
**Problem description**
The su script (/data/data/com.termux/files/usr/bin/su) allocates a program (/sbin/su) in the PATH variable instead of a directory (/sbin). This means that other Magisk su related programs, such as resetprop, can't be found.
Note: I'm using Magisk 19.3

Suggested Solution: Change the PATH allocation from: PATH=/sbin/su:/su/bin:/su/xbin:/system/bin:/system/xbin
To: PATH=/sbin:/su/bin:/su/xbin:/system/bin:/system/xbin

**Steps to reproduce**
$ su
:/data/data/com.termux/files/home # resetprop -h
/system/bin/sh: resetprop: not found
127|:/data/data/com.termux/files/home #

**Expected behavior**
The resetprop program should have displayed it's help information.

**Additional information**
Updatable packages:
bash/stable 5.0.9 aarch64 [upgradable from: 5.0.7-5]
dash/stable 0.5.10.2-2 aarch64 [upgradable from: 0.5.10.2-1]
gawk/stable 5.0.1-4 aarch64 [upgradable from: 5.0.1-3]
libiconv/stable 1.16-3 aarch64 [upgradable from: 1.16-2]
libnghttp2/stable 1.39.2 aarch64 [upgradable from: 1.39.1-1]
readline/stable 8.0.1 aarch64 [upgradable from: 8.0-3]
unzip/stable 6.0-5 aarch64 [upgradable from: 6.0-4]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.120-lineageos-g66e7aed #1 SMP PREEMPT Sun Aug 11 15:25:31 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
OnePlus
Device model:
ONEPLUS A3010

**Comment by xeffyr** [comment]
Use utility `tsu`.
```
pkg install tsu
tsu
```
