### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by oOkem** [termux/termux-packages#4209]
An error occurred while git clone and running python
![IMG_20190822_143706](https://user-images.githubusercontent.com/44183336/63495958-1d555100-c4eb-11e9-9934-dcf4edc5b846.jpg)

**Comment by Grimler91** [comment]
Can't see any error here.

**Comment by oOkem** [comment]
i can't run python and git

**Comment by oOkem** [comment]
![Screenshot_2019-08-22-22-51-24-66](https://user-images.githubusercontent.com/44183336/63529782-819a0400-c52f-11e9-9a85-1794d5392887.png)
you see now? since there is remote writing when git clone everything becomes an error when installing the script and running python
