### ISSUE TITLE
ninja failes to compile gobject-introspection

### ISSUE THREAD

**Issue by RossComputerPerson** [termux/termux-packages#4213]
**Problem description**
I'm compiling gobject-introspection so I can make GTK themes using Oomox on my phone and ran into an error that I don't know how to handle.

**Steps to reproduce**
After compiling and installing meson, and setting up gobject-introspect with the meson command run ninja. This error should show up:
```
ImportError: dlopen failed: cannot locate symbol "PyExc_RuntimeError" referenced by "/data/data/com.termux/files/home/gobject-introspection/build/giscanner/_giscanner.cpython-37m.so"...
[71/140] Compiling C o...-1.0@sha/regress.c.o'.
ninja: build stopped: subcommand failed.
```

**Expected behavior**
gobject-introspection should compile

**Additional information**
```
Updatable packages:
cmake/stable 3.15.2-1 aarch64 [upgradable from: 3.15.2]
Subscribed repositories:
ttps://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.153-15480849 #2 SMP PREEMPT Thu Jul 4 21:10:33 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-G950U
```

**Comment by xeffyr** [comment]
`build/giscanner/_giscanner.cpython-37m.so` has to be linked with python lib.
You are running into https://github.com/android-ndk/ndk/issues/201.

**Comment by RossComputerGuy** [comment]
I didn't see a way to fix this, what's the solution to fixing this?

**Comment by RossComputerGuy** [comment]
Nevermind, adding $PREFIX/lib/libpython3.7m.so to LD_PRELOAD fixed it

**Comment by RossComputerGuy** [comment]
Installing mako from pip produces an error saying its not found, running `sed -i "s|python3|python2|g" build/**/*.ninja`. Then python headers are needed so `python-static` is needed.

**Comment by Ludea** [comment]
Maybe specify python static path with with option https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/master/meson_options.txt#L21 ?

**Comment by nikey02** [comment]
i just barrow from this issue comment 
https://github.com/termux/termux-packages/issues/4213#issuecomment-524483167

which get rid of `cannot locate symbol` error
