### ISSUE TITLE
'mv' command doesn't work on text files starting with 'LG' on LG brand devices

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#4217]
**Problem description**
If a text file starts with the string 'LG' (can be followed by anything), the 'file' command identifies that file as some kind of archive format. Trying to 'mv' that file anywhere (or just renaming the file) results in this error:

`mv: cannot move 'testfile' to a subdirectory of itself, 'testfile2' `

This seems to be isolated to devices of the brand 'LG' as I was able to reproduce it on 2 LG devices but not on a non-LG Device.

screenshot:
![gltermux-error](https://user-images.githubusercontent.com/30786326/63644240-7ae7ca00-c6b2-11e9-98b1-658e99ae0977.png)

**Steps to reproduce**
(on a LG brand device)
1. create a file whose contents start with the string 'LG'
$ echo 'LG' > testfile
2. try to determine its filetype
$ file testfile
3. try to rename this file using mv
$ mv testfile testfile2

I originally found this strange behavior by grep-ing the output of termux-info to find the device model and storing the result in a file:
$ termux-info | grep --after-context=1 'Device model:' | grep --invert-match 'Device model:' > ~/.device-model

**Expected behavior**
file and mv commands to act the same in Termux regardless of the manufacturer of the device

**Additional information**
Post output of command `termux-info`.
termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.49-gaa82e61-00004-g68c3884 #1 SMP PREEMPT Fri Jan 30 17:02:24 KST 2015 armv7l Android
Termux-packages arch:
arm
Android version:
5.0.1
Device manufacturer:
LGE
Device model:
LGL33L

**Comment by RossComputerGuy** [comment]
I think this is something SELinux is doing. I don't know of any reason why this is occuring.

**Comment by ng1nX4O4** [comment]
try this instead

```mv testfile testfile2/.


This Is Causing Because You Already Have A Folder Called `testfile2`

**Comment by xeffyr** [comment]
> the 'file' command identifies that file as some kind of archive format.

The `file` command determines the file type by looking for common signatures.

For this "archive data" signature defined in the following way
```
# Arhangel
0	string	LG Arhangel archive data
```
so `file` works absolutely correctly.

***

Issue with `mv` is really strange.
If libc on your ROM executes some hooks when file-related functions are called, nothing will help.

**Comment by sudomain** [comment]
> # Arhangel

> 0	string	LG Arhangel archive data

Is this from the magic.msc file that is mentioned by the file man page? If so, how do I get a human-readable version of that file?

> If libc on your ROM executes some hooks when file-related functions are called, nothing will help.

Does the termux python package also rely on the version of libc provided by the ROM? I only ask because I tested the following code which worked:

`import os`
`os.rename('testfile', 'testfile2')`

**Comment by xeffyr** [comment]
> If so, how do I get a human-readable version of that file?

From source code: https://github.com/file/file/blob/master/magic/Magdir/archive

> Does the termux python package also rely on the version of libc provided by the ROM?

Yes because everything is NDK-based.

Note that `mv` doesn't execute just `rename()`, so most likely problem isn't here.

**Comment by xeffyr** [comment]
There also different issue for `mv` (again, unreproducible on AOSP devices): https://github.com/termux/termux-packages/issues/2869.

**Comment by 5p0ng3b0b** [comment]
There is potentially more than one version of mv on your device. mv is normally a symlink.
```
ls -l  $(which mv)
lrwxrwxrwx 1 u0_a101 u0_a101 9 Oct  3 11:19 /data/data/com.termux/files/usr/bin/mv -> coreutils
```
Can the problem be replicated using the toybox or busybox versions instead of coreutils?
eg /system/bin/mv or busybox mv
