### ISSUE TITLE
need ssh on termux

### ISSUE THREAD

**Issue by ebrammagdy123** [termux/termux-packages#4218]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by ebrammagdy123** [comment]
i need ssh for saycheese

**Comment by RossComputerGuy** [comment]
The wiki has a page on that I think

**Comment by Grimler91** [comment]
Install dropbear or openssh.
