### ISSUE TITLE
What happened to sdl-dev?

### ISSUE THREAD

**Issue by IntyLab** [termux/termux-packages#4224]
One day, there was an upgrade for sdl, but I couldn't install it until I uninstalled it first.  When I uninstalled sdl, sdl-dev was automatically uninstalled as well.  Now it doesn't seem to be in the usual repositories.  I was able to reinstall sdl, and the programs I have that use it seem to be running fine.

**Comment by Hax4us** [comment]
Don't worry , now there is no any Dev package splitting hence all Header files are now available without `*-dev` packages.

**Comment by Grimler91** [comment]
Yepp, here's a wiki page about it: https://wiki.termux.com/wiki/No_more_-dev_packages
