### ISSUE TITLE
Use termux chroot by default?

### ISSUE THREAD

**Issue by Merith-TK** [termux/termux-packages#4226]
I was wondering if it was possible at all to use termux-choot by defaut? So that i wont have to worry about file paths being broken when im trying to script a program for a real system

**Comment by xeffyr** [comment]
Put this to END of your `~/.bashrc`:

``` .bash
if [ -z "$CHROOTED" ]; then
    export CHROOTED=1
    exec termux-chroot
fi
```

**Comment by PePoDev** [comment]
@xeffyr  How about .zshrc ?

**Comment by xeffyr** [comment]
@PePoDev I have provided the idea how this can be done [comment above](https://github.com/termux/termux-packages/issues/4226#issuecomment-525480876). Just translate it into Zsh, maybe you even won't need to make any changes to this script.

**Comment by PePoDev** [comment]
@xeffyr Thanks for answering.

I have tried your comment in .zshrc then I create new sessions and it show

> [Process completed (signal 35) - press Enter]

After press Enter it exit !

I don't know much about shell.
Can you guide me what's wrong ?
