### ISSUE TITLE
emacsclient can not find server socket

### ISSUE THREAD

**Issue by bokuno** [termux/termux-packages#4230]
After a update to 
"emacs/stable,now 26.2-4 aarch64 [installed]',
I found emacsclient can not find socket by "emacsclient -t" command which is just fine before.
Then I found the emacs server socket's path has been changed to 
"(network server on /data/data/com.termux/files/usr/var/run/emacs10118/server)",
which "emacsclient -t -s /data/data/com.termux/files/usr/var/run/emacs10118/server" could connect to.
So, seems not a real bug but....something should be fixed as well?
Thanks in advance.

**Comment by Grimler91** [comment]
Yeah, should be fixed, thanks for reporting!

**Comment by OverkillGuy** [comment]
I'm running emacs 26.3-1, which thus should contain the fix of #4237, and the socket dir change to `$PREFIX/var/run/`, but the socket still seems to pop in `$TMPDIR`, despite no customization of my socket-dir. 

```shell
$ pkg show emacs
Package: emacs
Version: 26.3-1
$ emacs --daemon  # launch a daemon to connect to
# [...]
$ ls $PREFIX/var/run/  # folder where socket should be
README.openssh	sshd.pid
#  No emacs socket or folder!
$ ls $TMPDIR/emacs$(id -u)/  # but still in old place
server
$ emacsclient .
emacsclient: cant find socket; have you started the server?
$ emacsclient -s $TMPDIR/emacs$(id -u)/server  .
# this client connects fine!
```
Effectively I have all the symptoms of the bug, despite having emacs version with the commit supposed to fix the issue. Am I missing something?

---

Further digging: the `server-socket-dir` variable in my emacs was not customized by me, but the variable is defined as `$TMPDIR/emacs$(id -u)` as per my emacs' `server.el`, which contains the following

```elisp
(defvar server-socket-dir                                                                                           
  (and (featurep 'make-network-process '(:family local))                                                            
       (format "%s/emacs%d" (or (getenv "TMPDIR") "/data/data/com.termux/files/usr/var/run") (user-uid)))
```
Which looks exactly like the code BEFORE patch https://github.com/termux/termux-packages/blob/7658b5261f8207cc36452347f050d1a207f70db0/packages/emacs/lisp-server.el.patch.beforehostbuild#L9 is applied. Of course, [latest emacs26.3-1.deb](https://bintray.com/termux/termux-packages-24/emacs#files/aarch64) has the proper version, but somehow mine doesn't despite being created/managed by emacs pkg (`dpkg -S  dpkg -S /data/data/com.termux/files/usr/share/emacs/26.3/lisp/server.el.gz` says `emacs`!)

Summary: Despite having latest 26.3-1 (= include patch for socket creation/use in `$PREFIX/var/run`), my server.el gets an incorrect value, and I don't know where from.

Sorry for digging up dead threads, this seemed too closely related to current ticket to warrant creating a new one.

**Comment by xeffyr** [comment]
> (getenv "TMPDIR") "/data/data/com.termux/files/usr/var/run")

TMPDIR != `$PREFIX/var/run`.

**Comment by danielsz** [comment]
Everything @OverkillGuy described is true for me as well.
