### ISSUE TITLE
Slow Package Downloading

### ISSUE THREAD

**Issue by ng1nX4O4** [termux/termux-packages#4231]
Download Speed Is Slow. Downloading 70 MB Of Package From The Server And It's Been 1 hour. But haven't finish the download.

I Have 4g
And My Reguler Speed Is 3mb

My Device Is Aarch64

**Comment by ng1nX4O4** [comment]
It's Because I Am From Asia And I Think That The Server Is On USA. It Would Be Very Kind If Termux Has An Mirror Repo

**Comment by ItsTheAvro** [comment]
Use any free vpn
I prefer 'Thunder VPN'

**Comment by ng1nX4O4** [comment]
@ItsTheAvro Thanks. It Actually Worked.

**Comment by akhilsuny143** [comment]
Yes, vpn works

**Comment by Krypno** [comment]
Go to etc directory and if there is a file named reslov.conf edit it using :
nano resolv.conf
Then check if there is an entry as:
nameserver 8.8.8.8
if it is there then you are good to go. Else type this in amnd then save the file.
if there is no file named resolv.conf then create one and follow above steps.
etc directory lies relative to home as:
../usr/etc
in termux.

**Comment by xeffyr** [comment]
@Krypno `resolv.conf` is not being read by package manager. It is present for certain packages like `dnsutils` which have own DNS resolver.
