### ISSUE TITLE
Crontab is running a task multiple times at once

### ISSUE THREAD

**Issue by ItsTHEAvro** [termux/termux-packages#4232]
I created a python script to send **One message** to a person in Facebook. When I run it with 'python file.py' it sends only one message. Used crontab to schedule a task to run the script at a particular time. It runs successfully. But instead of **one** message, it sends **14** messages at once!

Crontab command -

0 11 * * * cd ~/ && /data/data/com.termux/files/usr/bin/python file.py

What am I doing wrong here?

**Comment by xeffyr** [comment]
Never observed that.
Make sure that you don't have multiple instances of crond running.

**Comment by ItsTHEAvro** [comment]
I don't

**Comment by xeffyr** [comment]
Really ? If you are starting crond via Termux:Boot then most likely you have multiple crond instances since Termux:Boot has a bug.

**Comment by ItsTHEAvro** [comment]
I am not using Termux:Boot
i just run the command "crond" and then "Acquire Wakelock" and minimize
Termux
 At the time mentioned in the crontab, it runs exactly 14 times
