### ISSUE TITLE
FFmpeg 4.2 update missing on andoid-5 branch

### ISSUE THREAD

**Issue by samoht0** [termux/termux-packages#4233]
android-7 is already on FFmpeg 4.2, but I couldn't find a commit on andoid-5. Was this intended or just missed?

**Comment by Grimler91** [comment]
The branches are updated independent of eachother so it's probably just that @fornwall hasn't updated and built it. If you open a PR against the android-5 branch then that probably speeds the process up

**Comment by Grimler91** [comment]
It is now available for all arches.
