### ISSUE TITLE
tor: raw assertion failed (crash)

### ISSUE THREAD

**Issue by foremtehan** [termux/termux-packages#4235]
After i execute ```termux-setup-storage``` in my device (Huawei P7 Android version 5) nothing happend but some of my packages functionality has been broked (tor) :
![63872210-a7615600-c9d2-11e9-8944-b18e7bd130a1](https://user-images.githubusercontent.com/53290883/63887020-1352b700-c9f1-11e9-8fe8-1ae405f65df2.jpg)

Even i would delete completely termux from my phone and reinstall it, tor wouldn't work and same error will show up and seem like termux restore it self from some hidden file in my sdcard...

How to Completely remove termux (cache,accesse, etc) from my phone ? (delete cache from setting wouldn't work)

**Comment by xeffyr** [comment]
> (delete cache from setting wouldn't work)

Erasing application data **will work**.

**Comment by foremtehan** [comment]
> Erasing application data will work.

1. I deleted google play data to make sure there no caching
2. first I deleted termux data in setting , and removed it from apps
3. I've restart my phone
4. then i install termux again
5. i executed ```pkg install tor -y```
and tor show the same error above,Note that i have termux and tor on my another hone and it work proply something wrong here,

I realized every time i run ```tor```, termux would create a ```core.``` file what is it ?

![Capture](https://user-images.githubusercontent.com/53290883/63877778-7e928e00-c9dd-11e9-9899-ee771df4caf5.PNG)

**Comment by xeffyr** [comment]
> Note that i have termux and tor on my another phone and it work properly , something wrong here,

1. `tor` just crashes and you can't do anything here (except using different device).

2. Post output of `termux-info` from both devices.

> I realized every time i run tor, termux would create a core. file what is it ?

It is a [core dump](https://wiki.archlinux.org/index.php/Core_dump).

**Comment by xeffyr** [comment]
> I couldnt see the detail of this file with nano

There no such file in Termux.
This is a reference to source code directory in build environment.

**Comment by foremtehan** [comment]
> Post output of termux-info from both devices.

Coudnt find a way to copy text from the console so here's the screenshots:

![1](https://user-images.githubusercontent.com/53290883/63886804-8d367080-c9f0-11e9-9e1f-f3c7fb65208f.jpg)

![2](https://user-images.githubusercontent.com/53290883/63886817-93c4e800-c9f0-11e9-96ee-0bcaf16bdf64.jpg)

(I'll send you screenshot from another phone if necessary but i cant for now)

**Comment by foremtehan** [comment]
@xeffyr does termux have access to ```/sdcard``` and ```/storage``` by default ? i'm able to see the directories by fresh termux install i bet this crash related to ```termux-setup-storage``` command, wish there is a command that able to restore or remove all termux access .

**Comment by xeffyr** [comment]
Android 5 allows to see /sdcard without storage permission since here it is given by default. Starting from Android 6, you have to explicitly give the necessary permission.

**Comment by xeffyr** [comment]
Seems to be fixed with update to 0.4.1.6.
