### ISSUE TITLE
Package Request: RCM (dotfiles management)

### ISSUE THREAD

**Issue by dgrabla** [termux/termux-packages#4236]
RCM is a management suite for dotfiles. It is very useful to keep track of the configuration of macos and linux. It would be great to have Termux support.
 
https://github.com/thoughtbot/rcm

**Comment by Shadow53** [comment]
Second this. I use RCM with Syncthing to synchronize my dotfiles between machines, including my phone, and it would be nice to get my configs available in Termux

**Comment by ckrailo** [comment]
I just switched over to `rcm` so yes please! (Either way, I love Termux and have happily purchased the upgrades to support the project... thank you!)

**Comment by ckrailo** [comment]
If it helps anybody... I've installed `rcm` via the following method:

(slightly adapted from the ["Elsewhere" installation instructions](https://github.com/thoughtbot/rcm/blob/master/README.md) and the prefix flag mentioned in the [INSTALL file](https://github.com/thoughtbot/rcm/blob/master/INSTALL)...)

```
mkdir -p ~/releases
cd ~/releases
curl -LO https://thoughtbot.github.io/rcm/dist/rcm-1.3.3.tar.gz &&
sha=$(sha256sum rcm-1.3.3.tar.gz | cut -f1 -d' ') &&
[ "$sha" = "935524456f2291afa36ef815e68f1ab4a37a4ed6f0f144b7de7fb270733e13af" ] &&
tar -xvf rcm-1.3.3.tar.gz &&
cd rcm-1.3.3 &&
./configure --prefix=$PREFIX &&
make &&
make install
```

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install rcm
```
