### ISSUE TITLE
need libutil

### ISSUE THREAD

**Issue by ng1nX4O4** [termux/termux-packages#4244]
can you port libutil for termux

**Comment by xeffyr** [comment]
Definetly wontfix. It was deleted inbtentionally from master branch as process of android-5 android-7 splitting. **It is no longer needed**. Patch your things to not link with libutil.

**Comment by xtkoba** [comment]
For future reference: <a href="https://github.com/termux/termux-packages/tree/android-5/packages/libutil">`libutil`</a> is a package of library that defines functions `openpty(3)`, `login_tty(3)` and `forkpty(3)` not available until Android 6.0.
