### ISSUE TITLE
Package request: k2pdfopt

### ISSUE THREAD

**Issue by VR-25** [termux/termux-packages#4254]
K2pdfopt optimizes PDF/DJVU files for mobile e-readers (e.g. the Kindle) and smartphones. It works well on multi-column PDF/DJVU files and can re-flow text even on scanned PDF files. It can also be used as a general PDF copying/ cropping/re-sizing/OCR-ing manipulation tool. It can generate native or bitmapped PDF output, with an optional OCR layer.

Homepage: https://www.willus.com/k2pdfopt/

Source: https://www.willus.com/k2pdfopt/src/

Source (alternate link): https://packages.debian.org/source/sid/k2pdfopt/

**Comment by dickyharper** [comment]
+1
Absolutely I agree.  It would be great. ☺☺

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install k2pdfopt
```

**Comment by dickyharper** [comment]
I can't download because I use Android 5.  That was sad.  I was expecting this package.01.01.2020, 23:24, "Leonid Plyushch" <notifications@github.com>:Closed #4254.

**Comment by VR-25** [comment]
Thank you!

**Important Info**

k2pdfopt CLI (all archs) won't detect all pages from certain PDFs.
Either something is missing or these PDFs are somewhat broken.

I couldn't find any public issue tracker to report this to the original developer.

Anyway, a good solution I found is rebuilding the PDFs first. I've been doing that on Android with [this app](https://play.google.com/store/apps/details?id=de.mdev.pdfutilities). Just add a blank page after the first - and you're done.

**Comment by Harshiv-Patel** [comment]
@dickyharper support for Android 5-6 is deprecated, we'll need to build the package ourselves.
