### ISSUE TITLE
pkg install sl not installing

### ISSUE THREAD

**Issue by ASHISHs21** [termux/termux-packages#4255]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
There really something wrong on your side...
Issue unreproducible.
