### ISSUE TITLE
pass autocompletion does not work

### ISSUE THREAD

**Issue by dwrz** [termux/termux-packages#4256]
**Problem description**
`bash` autocompletion for `pass` does not work.

**Steps to reproduce**
With `pass` set up, attempt to autocomplete with tab.

**Expected behavior**
Autocompletion of a password.

**Additional information**
Post output of command `termux-info`.
```
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.169-g09a041b17c60 #1 SMP PREEMPT Wed Jun 5 22:23:19 
UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Google
Device model:
Pixel 2
```

**Comment by buttaface** [comment]
Works for me.

**Comment by arno01** [comment]
I think it used to work for me in the past.
But now, it definitely does not.

``$ dpkg -L pass | grep completion``   does not return anything.

All what's currently packaged is the ``pass`` binary itself and the ``pass.1.gz`` (manpage).


The following completion files should be included to the package so that the completion is working:

```
$ wget -c https://git.zx2c4.com/password-store/snapshot/password-store-1.7.3.tar.xz
$ tar tvf password-store-1.7.3.tar.xz  |grep completion
drwxrwxr-x root/root         0 2018-08-03 05:32 password-store-1.7.3/src/completion/
-rw-rw-r-- root/root      4119 2018-08-03 05:32 password-store-1.7.3/src/completion/pass.bash-completion
-rw-rw-r-- root/root      6098 2018-08-03 05:32 password-store-1.7.3/src/completion/pass.fish-completion
-rw-rw-r-- root/root      4024 2018-08-03 05:32 password-store-1.7.3/src/completion/pass.zsh-completion
```

**Comment by xeffyr** [comment]
> $ dpkg -L pass | grep completion does not return anything.

```
~ $ dpkg -L pass | grep completion
/data/data/com.termux/files/usr/share/fish/vendor_completions.d
/data/data/com.termux/files/usr/share/fish/vendor_completions.d/pass.fish
/data/data/com.termux/files/usr/share/bash-completion
/data/data/com.termux/files/usr/share/bash-completion/completions
/data/data/com.termux/files/usr/share/bash-completion/completions/pass
```

**Comment by dwrz** [comment]
I also appear to have completion files:
```
u0_a132@localhost ~ $ dpkg -L pass | grep completion
/data/data/com.termux/files/usr/share/fish/vendor_completions.d
/data/data/com.termux/files/usr/share/fish/vendor_completions.d/pass.fish
/data/data/com.termux/files/usr/share/bash-completion
/data/data/com.termux/files/usr/share/bash-completion/completions
/data/data/com.termux/files/usr/share/bash-completion/completions/pass
```

But autocompletion still does not work for me. 

I've also noticed `pass ls` does not work on any machine for -- it just prints garbled text. I'm not sure if my store is corrupted in some way, or if there's a bug in `pass`. 

I do get autocompletion on my personal and work laptops, though, and not in `termux`.

**Comment by xeffyr** [comment]
@dwrz Is `bash-completion` package installed ?

**Comment by dwrz** [comment]
@xeffyr -- thank you -- that was it. I switched back to `bash` from `fish` and forgot to install completion.
