### ISSUE TITLE
Busybox deprecation causes breaking of backward compatibility with termux-arch

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#4259]
see:
https://github.com/SDRausty/termux-archlinux/issues/35#issuecomment-516931435

**Problem description**
A busybox deprecation (symlinking no longer supported) causes failure of new installs of termux-arch, the most starred termux proot environtment

**Steps to reproduce**
attempt to install termux-arch
fails due to symlinks not found and backward compatilbility being broken

**Expected behavior**
backward compatibility with scripts that require busybox

**Additional information**
Post output of command `termux-info`.
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.31-perf-g606096e-dirty #1 SMP PREEMPT Tue Jan 17 18:10:20 KST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
7.0
Device manufacturer:
LGE
Device model:
LGL84VL
$
Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
Why TermuxArch author sticked to busybox ? Does he know that coreutils as well as some other utilities now available by default and are **essential packages** ? There just no point in using utilities from busybox (specifically `sha256sum` or what is needed for installation).

If TermuxArch's author has some frustration about busybox, he can make symlinks on his own.

Wontfix.

**Comment by xeffyr** [comment]
Also, paths like `$PREFIX/bin/applets` are not standard and are not meant to be backwards compatible. Rely on `$PREFIX/bin` instead.

**Comment by xeffyr** [comment]
So in conclusion, let @sdrausty will use utilities from $PATH and not hardcoded something else. After that everything will work.
