### ISSUE TITLE
Distribution method for termux-built packages? 

### ISSUE THREAD

**Issue by cydhaselton** [termux/termux-packages#426]
I'm currently building dotnet and in doing so I've built several dependencies (libunwind, libicu) that may be helpful to someone else.

Is there a way to contribute termux-built packages to the termux repo?

**Comment by its-pointless** [comment]
pull request ... chat to fornwall. He is on irc as well as here.

**Comment by vaites** [comment]
Make a branch for each package (to send updates later if needed) and make a pull request...

**Comment by cydhaselton** [comment]
Thanks. Will chat w/fornwall about preferred method and refresh my memory on git process
