### ISSUE TITLE
Signal 11 - Completed error

### ISSUE THREAD

**Issue by Nikhil-John21** [termux/termux-packages#4262]
Hai Guys 
Today i installed Termux in my android.
When i opened it says installing and then it stopped and shows me a msg dialog.
[Process Completed (signal 11) - Press Enter

then i press enter it crashed. Tried multiple times , rerinstalled nothing helped.
[https://imgur.com/fQi92uy](url)

this is what i got!

**Comment by xeffyr** [comment]
1. Post output of `termux-info`.

2. Your error seems too strange. Seems device-specific problem.

**Comment by Nikhil-John21** [comment]
I m using VMOS which acts as virtual machine with buildin root access.
Its Android version 5.1.1
CPU Architecture ARMv7-A

**Comment by xeffyr** [comment]
Ah, then it is a bug of VMOS. I got same.
