### ISSUE TITLE
PyAudio

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#4263]
When trying to run Anki (a flashcard program) from source, the only python module that fails to install is PyAudio. Error log of the install pasted below. Afaict, it's only used to record audio, so with tweaks to my project's (a CLI version of Anki) source code, I'll be able to use termux-microphone-record if it's available. Thought I'd raise the issue anyway incase someone else needs this module in the future or if there's a quickfix available

**Additional information**
* If it didn't work then please provide the error you ran into

$ pip3 install pyaudio
Collecting pyaudio
  Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Installing collected packages: pyaudio
  Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-alinucup/pyaudio/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-alinucup/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-a34qdl9y/install-record.txt --single-version-externally-managed --compile
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-alinucup/pyaudio/
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.7
    copying src/pyaudio.py -> build/lib.linux-armv7l-3.7
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-armv7l-3.7
    creating build/temp.linux-armv7l-3.7/src
    arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -fPIC -I/data/data/com.termux/files/usr/include/python3.7m -c src/_portaudiomodule.c -o build/temp.linux-armv7l-3.7/src/_portaudiomodule.o
    unable to execute 'arm-linux-androideabi-clang': No such file or directory
    error: command 'arm-linux-androideabi-clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-alinucup/pyaudio/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-alinucup/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-a34qdl9y/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
> unable to execute 'arm-linux-androideabi-clang': No such file or directory

`pkg install clang`

**Comment by interstellarcodegit** [comment]
didnt work😭😭

**Comment by dzhemshit** [comment]
че
