### ISSUE TITLE
lld can't find libc by default

### ISSUE THREAD

**Issue by kettes-leulhetsz** [termux/termux-packages#4264]
`lld` should be a drop-in replacement for the system linker.

```
~/tmp> pkg install lld 2>/dev/null | grep lld
lld is already the newest version (8.0.1).

~/tmp> cat main.c
#include <stdio.h>

int main(int argc, char* argv[]) { return 0; }

~/tmp> clang -fuse-ld=lld main.c
ld.lld: error: unable to find library -ldl
ld.lld: error: unable to find library -lc
ld.lld: error: unable to find library -ldl
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by buttaface** [comment]
[Discussed before](https://github.com/termux/termux-packages/pull/3553#pullrequestreview-218137496) and a pull that would fix it sitting in limbo for months, #3531.

**Comment by buttaface** [comment]
Can confirm that it works now that Leonid merged that pull, including when cross-compiling and running 32-bit ARM on AArch64. :smile:

**Comment by kettes-leulhetsz** [comment]
Confirmed, fixed.
