### ISSUE TITLE
Can't compile codes on different directory. I'm a beginner, I want to know why is this happenning???

### ISSUE THREAD

**Issue by RohanKaran** [termux/termux-packages#4268]
![Screenshot_2019-09-07-02-30-08-14_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/38720754/64460450-08e29c80-d118-11e9-954f-29b9d5dd163e.png)

**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
Don't compile stuff under /storage/emulated/0 or /sdcard. Android doesn't allow executable permissions here.

**Comment by RohanKaran** [comment]
Ohh...okk...thsnks
