### ISSUE TITLE
will packages support android 4 in the future?

### ISSUE THREAD

**Issue by yurenhen** [termux/termux-packages#427]
termux is a great project.
I noticed termux need android version >=5 ,
but I try to download the package to my android 4.4.2,
and this error occur:

```bash
ls lib
libandroid-support.so  libiconv.so            libintl.so

LD_LIBRARY_PATH=$PWD/lib tree                                                                                                           
CANNOT LINK EXECUTABLE: could not load library "libandroid-support.so" needed by "tree"; 
caused by cannot locate symbol "wctomb" referenced by "libandroid-support.so"...
```
seems some system lib not export `wctomb`.

will you add android 4 support later ?

thank you!

**Comment by fornwall** [comment]
Android support for versions lower than 5.0 is unfortunately not going to happen - it's just too much work supporting older versions with good quality for this kind of porting.

You can try out [TerminalIDE](https://play.google.com/store/apps/details?id=com.spartacusrex.spartacuside) for older Android versions.

**Comment by yurenhen** [comment]
@fornwall 
thanks for your reply, i'll try it~
