### ISSUE TITLE
Liblua-dev no candidate and no cmake 

### ISSUE THREAD

**Issue by davemackintosh** [termux/termux-packages#4270]
**Problem description**
`liblua-dev` replaced by `liblua` but `liblua` and other Lua packages don't provide the lua library or symbols. I've installed And uninstalled each package to make sure there are no conflicts but cmake fails to find Lua libraries. I've also tried reinstalling Termux from scratch.

![Screenshot_20190907-084027_Termux](https://user-images.githubusercontent.com/1430657/64471792-ac01d900-d14d-11e9-983d-cafafe5a69e1.jpg)

**Steps to reproduce**
1. Install `liblua` 
2. Configure Cmake to require `Lua` or any specific version I.E `Lua53` 
3. Run `cmake`

**Expected behavior**
`cmake` should find lua and its libraries and configure correctly.

**Additional information**
N/A

**Comment by xeffyr** [comment]
1. It found Lua, see entry on screenshot `found version "5.3.5". There something else went wrong.

2. liblua package contains everything needed (interpreter excluded though):
   ```
   /data/data/com.termux/files/usr/include
   /data/data/com.termux/files/usr/include/lualib.h
   /data/data/com.termux/files/usr/include/lua.hpp
   /data/data/com.termux/files/usr/include/lua.h
   /data/data/com.termux/files/usr/include/lauxlib.h
   /data/data/com.termux/files/usr/include/luaconf.h
   /data/data/com.termux/files/usr/lib
   /data/data/com.termux/files/usr/lib/liblua.so.5.3.5
   /data/data/com.termux/files/usr/lib/pkgconfig
   /data/data/com.termux/files/usr/lib/pkgconfig/lua.pc
   /data/data/com.termux/files/usr/share
   /data/data/com.termux/files/usr/share/doc
   /data/data/com.termux/files/usr/share/doc/liblua
   /data/data/com.termux/files/usr/lib/liblua.so
   /data/data/com.termux/files/usr/lib/liblua.so.5.3
   /data/data/com.termux/files/usr/share/doc/liblua/LICENSE
   ```

**Comment by xeffyr** [comment]
It "can't" find lua due to:
```
/data/data/com.termux/files/usr32/share/cmake-3.15/Modules/FindLua.cmake(214):  set(LUA_LIBRARIES /data/data/com.termux/files/usr32/lib/liblua.so;LUA_MATH_LIBRARY-NOTFOUND )
```

Passing `-DLUA_MATH_LIBRARY="/system/lib/libm.so"` fixes the issue.

**Comment by davemackintosh** [comment]
That fixes the not finding issue but then I get an error about libm.so being the wrong format.

``` 
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /system/lib/libm.so: error adding symbols: file in wrong format
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by xeffyr** [comment]
I wrote above: `or which your system path to libm.so`.
64 bit installations should use `-DLUA_MATH_LIBRARY="/system/lib64/libm.so"`.

**Comment by davemackintosh** [comment]
Perfect, thanks for your time! I'm just learning C++ 

Thanks again.
