### ISSUE TITLE
Mosquitto[v1.6.4-1]: Doesnt work with websockets anymore

### ISSUE THREAD

**Issue by Nic2012** [termux/termux-packages#4276]
Hi,
not sure, but it seems beginning with Mosquitto 1.6.4 websockets are not supported anymore:
```
mosquitto -c /data/data/com.termux/files/usr/etc/mosquitto/websocket.conf
1567965007: mosquitto version 1.6.4 starting
1567965007: Config loaded from /data/data/com.termux/files/usr/etc/mosquitto/websocket.conf.
1567965007: Opening ipv6 listen socket on port 1883.
1567965007: Opening ipv4 listen socket on port 1883.
1567965007: Opening websockets listen socket on port 1884.
Segmentation fault
```
websocket.conf:
```
listener 1883
listener 1884
protocol websockets

```
Mosquittos stops immediately.
First time ever that I see "Segmentation fault" according to Mosq.

Best regards,
Nic

**Comment by xeffyr** [comment]
Post `termux-info` output.

**Comment by Nic2012** [comment]
To be more precise: without declaring additional websocket listener, mosquitto works fine with mqtt protocol.

**Comment by fornwall** [comment]
@Nic2012 Thanks for reporting! This should be fixed now - does it work after running `pkg up` to update packages?

**Comment by Nic2012** [comment]
Thanks for your response, but I'm afraid it's not working yet. Startup Mosq.(-v) without any issues:
```
mosquitto -v -c /data/data/com.termux/files/usr/etc/mosquitto/websocket.conf
1568064919: mosquitto version 1.6.4 starting
1568064919: Config loaded from /data/data/com.termux/files/usr/etc/mosquitto/websocket.conf.
1568064919: Opening ipv6 listen socket on port 1883.
1568064919: Opening ipv4 listen socket on port 1883.
1568064919: Opening websockets listen socket on port 1884.
```
But no stable connection by websockets possible, no further error logging in Mosq., but I can see (in browser console) websockets connection established from webpage (js framework: https://github.com/mqttjs/MQTT.js) are reconnecting and closing immediately.

No websockets possible also on a Android app Iot MQTT Panel (https://play.google.com/store/apps/details?id=snr.lab.iotmqttpanel.prod&hl=en) running locally on same smartphone as Termux.

Tested also with MqttBox (http://workswithweb.com/html/mqttbox/getstarted.html) on remote Ubuntu 19.04. Same here fine with tcp (1883) but no connection with websockets (1884).

**Comment by Nic2012** [comment]
There exists an nodejs package mosca (https://github.com/mcollina/mosca/wiki/Mosca-as-a-standalone-service) as a standalone cli tool. I have tested it with same configuration as mentioned above:
`mosca -v --port 1883 --http-port 1884` (http-port opens additional websocket port on 1884)

With "Iot MQTT Panel" I can connect by the websocket to mosca broker without any problems.

**Comment by fornwall** [comment]
@Nic2012 Could you run `pkg up` and see if it works after updating to mosquitto 1.6.5 and latest libwebsockets?

**Comment by Nic2012** [comment]
1.6.5 works fine now, no problems anymore. Same in browser via websockets!
Thank you for your support.
