### ISSUE TITLE
problems with mongodb

### ISSUE THREAD

**Issue by MathiasHabel** [termux/termux-packages#4277]
Hi all,

I installed mongodb. This was sucessfull in the end, but now have some difficulties running it:

1.) at first the dependency 'pcrecpp' could not be installed, as the package 'pcre' contains the library 'libpcrecpp.so' too, so I had to force-overwrite it. I made a copy of the old lib and moved it back it to 'libpcrecpp.so' after installation of pcrecpp to have the library version of Package 'pcre' active.

2.) calling 'mongo' gives at first gave some errors of missing libraries 'libboost_<…>.so.1.69.0', so i linked the corresponding 'libboost_<…>.so.1.70.0' to  'libboost_<…>.so.1.69.0'.

3.) now i get the error 'CANNOT LINK EXECUTABLE "mongo": cannot locate symbol "usprep_close_63" referenced by "/data/data/com.termux/files/usr/bin/mongo"...', which i was not able to resolve as of yet.

Can someone point me in the right direction?

Thanks,

Mathias

**Comment by its-pointless** [comment]
Mongodb is not directly supported by termux. Its from my apt repo. I will make an attempt at fixing it tommorow.
