### ISSUE TITLE
No command 'godoc' found

### ISSUE THREAD

**Issue by ItsTHEAvro** [termux/termux-packages#4278]
Install golang-doc using

> pkg install golang-doc

It says  
`golang-doc is already the newest version (2:1.13).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
But when I type 
> godoc -http :8080

It says
`No command 'godoc' found, did you mean:
 Command 'pydoc' from package 'python'
 Command 'rdoc' from package 'ruby'`

![Screenshot_Termux_20190910-132242](https://user-images.githubusercontent.com/42869374/64593232-8a178900-d3cf-11e9-8af7-98d670372c9e.png)

What to do now?

**Comment by ItsTHEAvro** [comment]
How do I run "godoc" then?

**Comment by ItsTHEAvro** [comment]
Followed this tutorial

![Screenshot_Chrome_20190910-205003](https://user-images.githubusercontent.com/42869374/64624573-b3a2d580-d40c-11e9-8361-9684868e214b.png)

**Comment by ItsTHEAvro** [comment]
Didn't solve the issue
![Screenshot_Termux_20190910-210518](https://user-images.githubusercontent.com/42869374/64625846-b6062f00-d40e-11e9-807f-f6ba804f1977.png)

**Comment by xeffyr** [comment]
Because godoc is installed to `$GOPATH/bin/...`
