### ISSUE TITLE
Add __TERMUX__ compiler definition to know when app is being built for Termux/Android

### ISSUE THREAD

**Issue by a1batross** [termux/termux-packages#4283]
The problem: clang compiler distributed within Termux define both `__ANDROID__` and `ANDROID` that I and probably everyone using to distinguish GNU/Linux and Android targets. So, when my project is being built with Android NDK compilers, it will include Android-specific code(using code from libandroid, liblog, libEGL and so on).

Though, this isn't correct case for Termux, as Termux is more GNU/Linux-ish environment where you usually don't build Android apps. 

Well, this is an abstract explanation. To be more precise, I'm a developer of a game engine that does support Android natively. Though, some users want to build a dedicated server in a Termux and run it from their Android devices. At this time, just building it will give an undefined references to `android_log_print`. 

The solution: I'm asking to add `__TERMUX__` or something like that, so I can configure my project to not include Android specific code and still don't enable glibc-specific code when it's built in Termux environment.

**Comment by buttaface** [comment]
> Termux is more GNU/Linux-ish environment where you usually don't build Android apps.

What makes you think this? Termux is merely an Android environment with a ton more libraries ported to also work on Android.

> just building it will give an undefined references to android_log_print

Should be pretty simple to fix: just add `-llog` to your linker flags, so it will link against liblog.so from the Android system directory /system/lib[64].

It may still make sense to add a `__TERMUX__` but I don't think you've made a good enough case, `__ANDROID__` is good enough atm because Termux is much closer to an Android NDK build than it is to "glibc-specific code."

**Comment by xeffyr** [comment]
While `__TERMUX__` can be added. But removing `__ANDROID__` will add another layer of incompatibility (certain libs/programs natively support Android through existence of `__ANDROID__`).

**Comment by a1batross** [comment]
>What makes you think this? Termux is merely an Android environment with a ton more libraries ported to also work on Android.

@buttaface 

Maybe I'm explained it wrong... As I suppose, Termux isn't supposed to run compiled binaries as Android applications. You can't just do that until you're taken Android NDK sysroot, java compiler, `dx`, `aapt` and build an APK and install it.
For average user who is familiar with GNU/Linux, especially Ubuntu/Debian, Termux is an environment when they can run just Linux applications. It's in a description of this repository, isn't it?

>Should be pretty simple to fix: just add `-llog` to your linker flags, so it will link against liblog.so from the Android system directory /system/lib[64].

If it was so easy. Just defined `__ANDROID__`  macro enables the code which meant to be run as Android app. It's not only log utilities, it's also `libandroid`, some JNI code and maybe even more in the future.
And on my particular devices, you can't link to libandroid.so, as libunwind.so(which is dependency of libandroid) depends on libxz, which is just doesn't exist in shared form on my device. Yes, I can compile it and link, but it is completely breaking the logic of building and not topic of my issue. 

>It may still make sense to add a `__TERMUX__` but I don't think you've made a good enough case, `__ANDROID__` is good enough atm because Termux is much closer to an Android NDK build than it is to "glibc-specific code."

Quoting myself: "so I can configure my project to not include Android specific code and still don't enable glibc-specific code".

>`__TERMUX__` can be added. But removing `__ANDROID__` will add another layer of incompatibility (certain libs/programs natively support Android through specified definition `__ANDROID__`).

@xeffyr I do not suggest removing `__ANDROID__`. I agree, it's complete madness to remove it.
I do suggest adding a new macro which literally means "We're running on Android environment but not as typical Android application so we don't need JNI glue code or Android native APIs".

**Comment by buttaface** [comment]
> Termux is an environment when they can run just Linux applications. It's in a description of this repository, isn't it?

Yes and no, Android is just a linux kernel with a new libc, Bionic, and Java VM, Dalvik/ART, plus a bunch of user sandboxing beyond what most linux distros do. Termux runs in that environment, exactly like an Android application, as the Termux app is itself an Android application. As such, all the same porting work that would need to be done to a native C/C++ library to make it work with Bionic in an Android APK would need to be done to make it work in Termux too.

> It's not only log utilities, it's also libandroid, some JNI code and maybe even more in the future.

I think all of those should be available in Termux too, after all it's just an Android app.

> And on my particular devices, you can't link to libandroid.so, as libunwind.so(which is dependency of libandroid) depends on libxz, which is just doesn't exist in shared form on my device.

I see no direct dependency on libunwind.so from the system libandroid.so on two of my devices I just checked. If you have problems with your libandroid.so, your device is pretty screwed up and that's a separate problem.

> Quoting myself: "so I can configure my project to not include Android specific code and still don't enable glibc-specific code".

Right, my point is that Termux is pretty much just Android, just like if you used the official NDK, with [only a few tweaks](https://github.com/termux/termux-packages/tree/master/ndk-patches).

Given that it's not just a stock NDK though, it might make sense to add a `__TERMUX__`, but only if those linked tweaks are affecting someone, which you so far have not demonstrated. If you need __android_log_print, just link against it: it's available from the system liblog.so so it should always be there.

**Comment by a1batross** [comment]
Sorry for long answer, I was quite busy and forgot about this issue. :)

@buttaface 
thanks on giving a link on NDK patches, for now, I can use some of "new" or changed defines, like this
```
#if defined(__ANDROID__) && TCSAFLUSH == 0
#define __TERMUX__
#endif 
```
Not reliable though. 

Anyway, I have a better idea now, that will work even outside Termux environment.

**Comment by buttaface** [comment]
Looks like you got your wish,  b9d83f9.

**Comment by fornwall** [comment]
Yes, thanks for the suggestion @a1batross !
