### ISSUE TITLE
ImageMagick with RSVG conversion errors

### ISSUE THREAD

**Issue by Insalien** [termux/termux-packages#4284]
**Problem description**
Issue related to imagemagick or precisely with rsvg-convert 
```
$ convert test.svg test.png
bionic/libc/upstream-netbsd/lib/libc/stdlib/bsearch.c:70: bsearch: assertion "key != NULL" failed
Aborted
$ rsvg-convert /sdcard/test.svg -o test.png
bionic/libc/upstream-netbsd/lib/libc/stdlib/bsearch.c:70: bsearch: assertion "key != NULL" failed
Aborted
```

**Steps to reproduce**
I can't upload svg file but the testing content is pretty small
```
<svg xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="640" height="1000" pagecolor="#ffffff" viewBox="0 0 744.09449 1052.3622" id="svg2" version="1.1">
  <g id="group_data">
    <text>Test</text>
  </g>
</svg>
```

**Expected behavior**
Conversion is done

**Additional information**
Post output of command `termux-info`.
```
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.19 #2 SMP PREEMPT Tue Jun 4 11:50:10 UTC 2019 armv7l Android
Termux-packages arch:
arm
Android version:
6.0
Device manufacturer:
FAMOCO
Device model:
FX200i,3
```

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
I'm unsure that issue is related to imagemagick with librsvg.

The line
```
bionic/libc/upstream-netbsd/lib/libc/stdlib/bsearch.c:70: bsearch: assertion "key != NULL" failed
```
clearly states that issue is in your ROMs libc.

**Comment by Insalien** [comment]
@xeffyr hey thank you for your quick response. I have several devices in both arm and aarch64 arch and only this one in arm having this issue. Let's say there's some incompatibility between termux libsrvg(arm) and the libC in our ROM. I'll try to dig into it further.

There is still one tiny problem that I didn't mention earlier because it's not related to the original question but after installing **imagemagick** and depending on the svg, the conversion might not work because of
```
(process:32277): GdkPixbuf-WARNING **: 19:01:39.235: Cannot open pixbuf loader module file '/data/data/com.termux/files/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /data/data/com.termux/files/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
```
Everything is fine when I followed the suggestion.
You might want to add a **gdk-pixbuf.postinst** in this case.

**Comment by tondy67** [comment]
After latest upgrade (20 Sep 2019) everythink X11 stop working :(
termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.4.39 #6 SMP PREEMPT Sat Sep 3 03:30:24 UTC 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.1.1
Device manufacturer:
DARK GLEE 10.1
Device model:
DARK GLEE 10.1 1.1
$ grep bionic /data/data/com.termux/files/home/.vnc/localhost:1.log
bionic/libc/upstream-netbsd/lib/libc/stdlib/bsearch.c:70: bsearch: assertion "key != NULL" failed

**Comment by Insalien** [comment]
Thanks @xeffyr,  the fix that you did on pango package is working for me. The ticket can be closed unless @tondy67 want to add anything.

**Comment by tondy67** [comment]
Hi, my X11 (openbox,geany,pcmanfm) is still broken.
I installed Termux from scratch - no luck
I installed all libandroid-*-static - no luck
I installed fluxbox, it works, at least I can start aterm
I use nano && mc to continue my work but it's not the same as geany && pcmanfm
Maybe is x32 related, my tablet is old...
