### ISSUE TITLE
-masm=intel doesn't work in clang

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#4288]
gcc -masm=intel -S input.c

clang-8: warning: argument unused during compilation: '-masm=intel' [-Wunused-command-line-argument]

**Comment by xeffyr** [comment]
Clang isn't completely gcc-compatible.

**Comment by Grimler91** [comment]
Support for `-masm=intel` seem to have been added in clang 3.5: https://bugs.llvm.org/show_bug.cgi?id=17465#c3, I guess we're disabling it (or not enabling it) during the compilation

**Comment by xeffyr** [comment]
Or it works only for x86.

**Comment by Grimler91** [comment]
@xeffyr good point!

**Comment by xeffyr** [comment]
Just verified, the intel assembly syntax supported only for i686 and x86_64. So to use `-masm=intel`, you need to call clang in cross-compiler mode:

* `clang --target=i686-linux-android -masm=intel`

* `clang --target=x86_64-linux-android -masm=intel`
