### ISSUE TITLE
Termux auto restart 

### ISSUE THREAD

**Issue by raja100** [termux/termux-packages#4289]
Termux auto restart within 10 minutes in vivo y51l.    5.5.1
Facing problems in vnc server

**Comment by xeffyr** [comment]
> Termux auto restart within 10 minutes

How it restarts ? What you do that it restarts ?

> Facing problems in vnc server

Which problems ? Do you have screenshot or logs with errors displayed ?
I'm very unsure that "problems in vnc server" related to "Termux auto restart".

**Comment by raja100** [comment]
I installed Kali Linux in Termux.
And run it with vnc server.
After 10 minutes Termux will restart and
vnc will disconnect.

**Comment by xeffyr** [comment]
Then perhaps something to do with https://github.com/termux/proot.
