### ISSUE TITLE
Security related updates available (FFmpeg, curl)

### ISSUE THREAD

**Issue by samoht0** [termux/termux-packages#4293]
FFmpeg 4.2.1 is available (fixing multiple overflow flaws, as always).
https://git.ffmpeg.org/gitweb/ffmpeg.git/shortlog/n4.2.1
Curl 7.66.0 is available (fixing two CVE).
https://curl.haxx.se/changes.html
Requesting update for both branches. Thanks.

**Comment by Grimler91** [comment]
The updated packages are now available for both branches
