### ISSUE TITLE
Tmux error on start

### ISSUE THREAD

**Issue by imShara** [termux/termux-packages#4296]
**Problem description**
Tmux not starts

**Steps to reproduce**
1. Fresh install termux
2. pkg install tmux
3. tmux

**Expected behavior**
Should start

**Additional information**
error creating /data/data/com.termux/files/usr/var/run/tmux-10158 (no suck file or directory)

**Solve**
mkdir -p  /data/data/com.termux/files/usr/var/run/

**Comment by Grimler91** [comment]
Thanks, a new postinst script should make sure it exists
