### ISSUE TITLE
Update Neovim to version 4.2

### ISSUE THREAD

**Issue by StephanBeer** [termux/termux-packages#4298]
Any chance for updating the Neovim pkg which is currently on v3.8 to version 4.2?

**Comment by Grimler91** [comment]
Newer version of neovim depends on [libluv](https://github.com/luvit/luv) which we currently don't have

**Comment by fornwall** [comment]
I've added a luv package: https://github.com/termux/termux-packages/commit/105680a6793ce001ff5a234b59d09d542b4ea3ec

But neovim doesn't build without further changes, complains about not finding lpeg.

**Comment by fornwall** [comment]
Neovim has now been updated to 0.4.2, run `pkg up` to update.
