### ISSUE TITLE
clang and libatomic: another issue

### ISSUE THREAD

**Issue by ASMfreaK** [termux/termux-packages#430]
I'm trying to build rust on my phone (x86 based). So when I configure it, it fails to configure llvm like #282 :
```
Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Failed
-- Looking for __atomic_load_8 in atomic
-- Looking for __atomic_load_8 in atomic - not found
CMake Error at cmake/modules/CheckAtomic.cmake:74 (message):
  Host compiler appears to require libatomic, but cannot find it.
Call Stack (most recent call first):
  cmake/config-ix.cmake:317 (include)
  CMakeLists.txt:460 (include)
```
I upgraded all packages just before build. (I'm using default repo from Google Play) I'm configuring rust like this (using solution from #282 ) and the problem persists:
```
CFLAGS='-target i686-linux-android' CXXFLAGS='-target i686-linux-android' ./configure --prefix=/data/data/com.termux/files/usr
```
Any help?

**Comment by fornwall** [comment]
@ASMfreaK Thanks for reporting! This should be fixed by version `12-5` of the `ndk-sysroot` package which bundles `libatomic.a`.

Update as normal with `apt update && apt -y upgrade`.

**Comment by ASMfreaK** [comment]
I confirm. That nasty error is fixed. Thank you :)
