### ISSUE TITLE
faild to install metasploit

### ISSUE THREAD

**Issue by shivam888** [termux/termux-packages#4302]
Fetching nokogiri 1.10.3                                  Installing nokogiri 1.10.3 with native extensions
Building native extensions with: '--use-system-libraries' This could take a while...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.3/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -I               /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0 -r ./siteconf20190918-26227-l4ddf.rb                       extconf.rb --use-system-libraries
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:                                   --with-opt-dir
        --without-opt-dir                                         --with-opt-include
        --without-opt-include=${opt-dir}/include                  --with-opt-lib
        --without-opt-lib=${opt-dir}/lib                          --with-make-prog
        --without-make-prog                                       --srcdir=.
        --curdir                                                  --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)                                                        --help
--clean                                           /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to                      generate an executable file. (RuntimeError)
You have to install development tools first.                      from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'                           from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:532:in `with_werror'                                    from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'                                    from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'              from /data/data/com.termux/files/usr/lib/ruby/2.6.0/mkmf.rb:643:in `with_cflags'                                    from extconf.rb:161:in `add_cflags'
        from extconf.rb:416:in `<main>'
To see why this extension failed to compile, please check the mkmf.log which can be found here:

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/arm-linux/2.6.0/nokogiri-1.10.3/mkmf.log
extconf failed, exit code 1
Gem files will remain installed in                        /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.3 for inspection.                            Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/arm-linux/2.6.0/nokogiri-1.10.3/gem_make.out
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:99:in `run'                      /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:47:in                     `block in build'
  /data/data/com.termux/files/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in
`build'                                                   /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:185:in `block
in build_extension'                                         /data/data/com.termux/files/usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:181:in                             `build_extension'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:229:in `block                      in build_extensions'
  /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:226:in `each'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:226:in
`build_extensions'                                        /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/installer.rb:830:in                               `build_extensions'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/rubygems_gem_installer.rb:30:in
`build_extensions'                                          /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/installer.rb:320:in `install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/source/rubygems.rb:155:in                          `block in install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/rubygems_integration.rb:221:in                     `preserve_paths'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/source/rubygems.rb:144:in
`install'                                                 /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/gem_installer.rb:63:in
`install'                                                 /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/gem_installer.rb:68:in                   `block in install_with_settings'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/rubygems_integration.rb:800:in
`install_with_build_args'                                 /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/gem_installer.rb:68:in                   `install_with_settings'                                   /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/gem_installer.rb:16:in                   `install_from_spec'                                       /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/parallel_installer.rb:164:in             `do_install'                                              /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/parallel_installer.rb:148:in             `install_serially'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/parallel_installer.rb:103:in             `call'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/parallel_installer.rb:78:in
`call'                                                    /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:289:in                                `install_in_parallel'                                       /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:197:in `install'                    /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:92:in `block in                       run'                                                      /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:12:in `block                       in lock'
  /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:9:in `open'
  /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:9:in `lock'
  /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:73:in `run'
  /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:25:in `install'
  /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli/install.rb:65:in `run'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:235:in `block in                            install'
  /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/settings.rb:143:in `temporary'                     
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:234:in `install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/settings.rb:143:in `temporary'                     /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:234:in `install'                          /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in
`run'                                                     /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in
`invoke_command'                                          /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in
`dispatch'                                                  /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in
`start'                                                     /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:18:in `start'                               /data/data/com.termux/files/usr/bin/bundle:30:in `block in <main>'                                                /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:124:in                          `with_friendly_errors'                                      /data/data/com.termux/files/usr/bin/bundle:22:in `<main>'
An error occurred while installing nokogiri (1.10.3), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.3' --source 'https://rubygems.org/'` succeeds
before bundling.
In Gemfile:
  factory_bot_rails was resolved to 5.0.2, which depends on                                                             railties was resolved to 4.2.11.1, which depends on
      actionpack was resolved to 4.2.11.1, which depends on                                                                 actionview was resolved to 4.2.11.1, which depends on                                                                 rails-dom-testing was resolved to 1.0.9, which depends on
            nokogiri                                      dpkg: error processing package metasploit (--configure):
 installed metasploit package post-installation script subprocess returned error exit status 5
Errors were encountered while processing:

**Comment by xeffyr** [comment]
Doesn't happen with **latest** version.
