### ISSUE TITLE
Package request: irc2-irc

### ISSUE THREAD

**Issue by VikTech92** [termux/termux-packages#4306]
**Package description**
This is the oldest and probably the most reliable IRC daemons that have ever been made. It would be cool if you can start an IRC server on your mobile device.

**Link to home page and sources**
1. Home page: http://www.irc.org
2. Source code: http://www.irc.org/ftp/irc/server/irc2.11.2p3/
3. You can also refer to the Debian package information page which also as well contains the source code for the irc daemon: http://deb.debian.org/debian/pool/main/i/ircd-irc2/ircd-irc2_2.11.2p3~dfsg.orig.tar.gz . This also includes what libraries the debian package is dependent upon.

**Additional information**
Have you compiled or tried to compile the package on device?
* Not yet, might give it a shoot soon if I find the time to try a compile.

**Comment by zorro** [comment]
@xeffyr I was able to build ircd on device.

**Comment by zorro** [comment]
@xeffyr I have successfully compiled ```ircd-irc2``` on device
