### ISSUE TITLE
Why did libunwind get removed?

### ISSUE THREAD

**Issue by pollen5** [termux/termux-packages#4307]
Just curious why did libunwind get removed, i wanted to try it and today it doesn't exist, i see there is a `/system/lib/libunwind.so` which might explain it but why did it exist in the repo in first place if that's the case.

**Comment by xeffyr** [comment]
2 main reasons:

* It conflicts with NDK.

* It is not used by any our package.

If you really need it, you can compile it yourself.

**Comment by pollen5** [comment]
@xeffyr does the ndk one work as good as the packaged one so then maybe i won't need to compile it

**Comment by xeffyr** [comment]
NDK one equivalent to one packaged in Termux. They are different btw.

**Comment by pollen5** [comment]
I mean is the `/system/lib/libunwind.so` would work same as one termux had.
