### ISSUE TITLE
Bug report: different about $COLUMNS, buffer lines.

### ISSUE THREAD

**Issue by gMan1990** [termux/termux-packages#4312]
**Problem description**

Mosh: buffer lines is ?

**Steps to reproduce**

- use ssh: has lines with my terminal setting.
    ```text
    $ echo "$COLUMNS"
    80
    $ cat long.txt
    ```

- use mosh: only the last "$COLUMNS" lines, the oldest lines has gone.

    ```text
    $ echo "$COLUMNS"
    82
    $ cat long.txt
    ```

**Expected behavior**

Same as ssh.

**Additional information**

Termux on Android Phone

> Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
Mosh uses fixed screen.
