### ISSUE TITLE
Problem with 'ruby-dev'.

### ISSUE THREAD

**Issue by Timur13240** [termux/termux-packages#4316]
Why I can't install the package 'ruby-dev'?

Android 5.1, arm

`pkg install ruby-dev`

_OUTPUT:_
Package ruby-dev is not available, but is referred to by another package.

This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ruby

E: Package 'ruby-dev' has no installation candidate

**Comment by xeffyr** [comment]
Read https://wiki.termux.com/wiki/No_more_-dev_packages **carefully**.
