### ISSUE TITLE
 Dpkg error, to upgrade packages

### ISSUE THREAD

**Issue by Alaint0594** [termux/termux-packages#4317]
Hi, I'm new to Termux, I'm having problems installing packages by applying the pkg upgrade command.

when I apply the command it gives the following error

dpkg:error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/procps_3.3.15-6i686.deb (--unpack):
unable to reate ´/data/data/com.termux/files/usr/include/proc/version.h.dpkh-new` (while processing `./data/data/com.termux/filesusr/include/proc/version.h`): File exists
Errors were encountered while processing:
/data/data/com.termux/files/usr/var/cache/apt/archives/procps_3.3.15-6_i686.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an errir code (1)

**Comment by RossComputerPerson** [comment]
It looks like it failed because `/data/data/com.termux/filesusr/include/proc/version.h` already exists, could removing it (or renaming it to something else) work if you try again?

**Comment by xeffyr** [comment]
@RossComputerPerson He may have `procps-dev` installed.

**Comment by xeffyr** [comment]
Ok, so `procps-dev` should be uninstalled if exists, if not - remove conflicting headers manually. Then procps should be upgraded correctly.

**Comment by Alaint0594** [comment]
look for the address of the file that is supposedly created (proc) at the following address / data / data / com.termux / filesusr / include / proc / version.h`) but that address does not exist (proc and version.h) are directories that do not exist in the "include" folder

**Comment by Alaint0594** [comment]
TERMUX_PKG_BREAKS="procps-dev"
TERMUX_PKG_REPLACES="procps-dev"


I didn't find the location of those files if you can specify the path please to try

**Comment by xeffyr** [comment]
> TERMUX_PKG_BREAKS="procps-dev"
TERMUX_PKG_REPLACES="procps-dev"

is from https://github.com/termux/termux-packages/blob/master/packages/procps/build.sh#L9, something that you don't need to change.

You should remove **/data/data/com.termux/files/usr/include/proc/version.h** if it exists.

**Comment by Alaint0594** [comment]
> /v You should remove /data/data/com.termux/files/usr/include/proc/version.h if it exists.

the file doesn't exist, it's the weird thing

**Comment by xeffyr** [comment]
Then don't remove if it exists.... obviously.

**Comment by Alaint0594** [comment]
I will completely erase termux and clear the cache and start from scratch to test if the error persists.

If the error persists, could you help me with a local host or teamviewer?

**Comment by Alaint0594** [comment]
and try everything included check folder by folder locate the error try even delete the entire folder
