### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by CodeWithLinc** [termux/termux-packages#4318]
What could be the problem
My mobile phone keeps giving me this error

$ ls
kali-binds  kali-fs  kali.sh  start-kali.sh
$ ./start-kali.sh
/usr/bin/env: '/bin/bash': No such file or directory
$

![Screenshot_20190922-081719](https://user-images.githubusercontent.com/55532988/65383228-7561bc00-dd12-11e9-9177-1a1fa46aee57.png)

**Comment by RossComputerPerson** [comment]
/bin/bash doesn't exist because Termux doesn't follow the normal GNU design, change /bin/bash to `$PREFIX/bin/bash`.

**Comment by TitanHero** [comment]
This is very easy of manage using the environment var `$HOME`  or `~` with this you have the security that any that could be the path you always gonna have the right path...

**Comment by Grimler91** [comment]
As @RossComputerPerson was saying, looks like you need to fix the shebang of the script

**Comment by CodeWithLinc** [comment]
Alright and thanks for the reply.....

**Comment by bhagwandassony1** [comment]
![Screenshot_20200804-092016](https://user-images.githubusercontent.com/69147279/89251117-c49c9c80-d605-11ea-91fe-cb1b27b40495.png)

**Comment by landfillbaby** [comment]
that's an 8 at the end, not a B. that's your issue
