### ISSUE TITLE
MariaDB server not starting after update to 10.4.8

### ISSUE THREAD

**Issue by Shubhamvis98** [termux/termux-packages#4319]
The mariadb server is not starting after update to **mariadb Ver 15.1** Distrib 10.4.8-MariaDB
I tried to reinstall my termux app but the problem is still same
**Scrshot:**
![Screenshot_20190922-132239_Termux](https://user-images.githubusercontent.com/43336210/65384135-229cfa00-dd3c-11e9-8bb1-eb1eba89d0d8.png)
Every command like mysql_install_db mysqld_safe etc not working

**Comment by RossComputerPerson** [comment]
I believe this issue was reported before, check the closed issues and trying the solution that matches your problem.

**Comment by xeffyr** [comment]
![65384135-229cfa00-dd3c-11e9-8bb1-eb1eba89d0d8](https://user-images.githubusercontent.com/25881154/65386296-83c7cc00-dd42-11e9-9550-4bd05096d727.png)

Perhaps your database corrupted ?

I can't reproduce the issue.
![Screenshot_20190922-140711_Termux](https://user-images.githubusercontent.com/25881154/65386299-93471500-dd42-11e9-99e0-935cb64fcbe6.png)

**Comment by Shubhamvis98** [comment]
> ![65384135-229cfa00-dd3c-11e9-8bb1-eb1eba89d0d8](https://user-images.githubusercontent.com/25881154/65386296-83c7cc00-dd42-11e9-9550-4bd05096d727.png)
> 
> Perhaps your database corrupted ?
> 
> I can't reproduce the issue.
> ![Screenshot_20190922-140711_Termux](https://user-images.githubusercontent.com/25881154/65386299-93471500-dd42-11e9-99e0-935cb64fcbe6.png)

I freshly installed it so how it get corrupted?
And how to fix if the data is corrupted?

**Comment by xeffyr** [comment]
> I freshly installed it so how it get corrupted?

Either something gone wrong during installation (database is initialized when installing package) or something device-specific.

Try to do a **fresh** installation and post here console log. Additionally post your `termux-info` here.

**Comment by Shubhamvis98** [comment]
**Error during installation**

![s](https://user-images.githubusercontent.com/43336210/65398745-95f34a00-ddd6-11e9-89ec-66f7ab3d9392.png)

`$ termux-info`
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.4.113-lineageos-ga54b3e28ce4 #1 SMP PREEMPT Thu Aug 22 11:56:47 JST 2019 armv7l Android
Termux-packages arch:
arm
Android version:
9
Device manufacturer:
samsung
Device model:
GT-I9506

**Comment by xeffyr** [comment]
![65398745-95f34a00-ddd6-11e9-89ec-66f7ab3d9392](https://user-images.githubusercontent.com/25881154/65406951-aeb92b00-dde9-11e9-8c30-f9dc4d94dd19.png)

So that's the cause and issue is device-specific.
Could you post output of `cat /proc/cpuinfo` ?

**Comment by Shubhamvis98** [comment]
![Screenshot_20190923-125903_Termux](https://user-images.githubusercontent.com/43336210/65408090-f946a180-de01-11e9-80c1-effe1f751e38.png)

**Comment by SPAstef** [comment]
I have this exact same problem. Device:
Oneplus 3 with latest official OxygenOS (Android 9 Pie), rooted,  latest Termux.

**Comment by indrakaw** [comment]
Same here. It's seem there are corrupted files or the Inno engine doesn't work correctly.

**Comment by DarthZedd** [comment]
Same here.
Samsung Note10+
Android 9
Fresh installation of Termux
Fresh installation of MariaDb

Initializing mysql data directory...
Installing MariaDB/MySQL system tables in '/data/data/com.termux/files/usr/var/lib/mysql' ...
Illegal instruction

**Comment by Shubhamvis98** [comment]
After downgrade from 10.4.8 to 10.4.6, the problem is still same

![Screenshot_20190925-130822_Termux](https://user-images.githubusercontent.com/43336210/65579583-a69dee80-df95-11e9-80c2-855cf45f7679.png)

![Screenshot_20190925-130530_Termux](https://user-images.githubusercontent.com/43336210/65579447-60e12600-df95-11e9-98fa-838a37169a96.png)

**Comment by SPAstef** [comment]
With the downgrade it was fixed.
@Shubhamvis98 it's not enough to reinstall/update. You have to manually delete the folder with the DB data:

rm $PREFIX/var/lib/mysql/*

Then reinstall and run mysql_install_db, then start mysqld_safe service.

**Comment by Shubhamvis98** [comment]
> With the downgrade it was fixed.
> @Shubhamvis98 it's not enough to reinstall/update. You have to manually delete the folder with the DB data:
> 
> rm $PREFIX/var/lib/mysql/*
> 
> Then reinstall and run mysql_install_db, then start mysqld_safe service.

**Solved**

**Comment by indrakaw** [comment]
How do I do to downgrade the version?

**Comment by SPAstef** [comment]
It's a downgrade masked as an update. Just do the usual "pkg up" and it will downgrade it

**Comment by xeffyr** [comment]
**v10.4.6** is not available currently for devices using `termux.net` repository. Maybe to the end of week.

**Comment by indrakaw** [comment]
I don't like waiting until the end of the week. I want it now.

**Comment by xeffyr** [comment]
Wait until @fornwall will rebuild it.
Btw, all changes on android-5 branch won't be immediate. Do not expect things to "happen now", especially when legacy Android versions are no longer our priority.

**Comment by SPAstef** [comment]
Wow man you get to have all this fantastic stuff for free, FREE! And still you complain because you won't get something very specific fixed in less than 3 days, while in an industry level products you could have to wait weeks. Come on :-)

**Comment by indrakaw** [comment]
I thought there is a way to get the older version via .deb file package or something. Because, noone disallow you to ask.

**Comment by SPAstef** [comment]
Maybe you just said it the wrong way, then. Don't worry it can happen!
