### ISSUE TITLE
Again with nokogiri installation failure 

### ISSUE THREAD

**Issue by ye7iaserag** [termux/termux-packages#4326]
I'll keep it short:

gem install nokogiri fails with "checking if the C compiler accepts ... ***
extconf.rb failed ***"

All dependencies are installed all "-dev" dependencies are not found
tried everything found under closed issues here including the use --use-system-libraries

It seems the issue is related to a new change or the disappearing "-dev" header files since dependencies might not be met

**Comment by xeffyr** [comment]
Dev packages aren't needed, we don't store headers in a separate package anymore.
