### ISSUE TITLE
Instaloader

### ISSUE THREAD

**Issue by yazdan28** [termux/termux-packages#4328]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by RossComputerPerson** [comment]
Can you please fill in the information your missing?

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages#new-packages
**Packages installable via pip is not accepted**. Especially if require additional python modules as dependency.

**Comment by xeffyr** [comment]
```
pkg install python
pip install instaloader
```
