### ISSUE TITLE
Unable located packages on termux

### ISSUE THREAD

**Issue by hderajat1** [termux/termux-packages#4332]
PIP is one packages with python but command PIP not found on directory in termux, and than install any tools like PIP pyaes, rsa, bs4, asyncio, async_generator etc always have notice "E: unable located packages pyaes, etc", so am i reinstalled and restart device when install termux from playstore and again install them but always failure. Now only PHP can run on my termux and the other cannot.

**Comment by RossComputerPerson** [comment]
Did you run `pkg update` first? Did you check that you used the right package names?

**Comment by Grimler91** [comment]
Sounds like you tried to install python packages through apt. You have to use pip for python packages
