### ISSUE TITLE
pmbootstrap

### ISSUE THREAD

**Issue by OffifialMITX** [termux/termux-packages#4333]
Would it be possible to use [pmbootstrap](https://wiki.postmarketos.org/wiki/Installing_pmbootstrap) in Termux? I've tried both the pip and git installation methods, but both don't really work, with it not accepting symlinks and reporting things like sudo:sudo not being a directory. I suspect it's just due to Termux' non-linux nature, but have no leads from here on.

(I'm still a noob and am trying to learn stuff)

**Comment by xeffyr** [comment]
There more question is in **usability of pmbootstrap under Termux**.
If you are going to install PostmarketOS on Termux host from Termux itself, then it most likely will result in OS breakage.

> I suspect it's just due to Termux' non-linux nature,

Yes, pmbootstrap requires Linux distribution-based host. So using it in Termux will not end in anything good.

**Comment by OffifialMITX** [comment]
No, of course I wouldn't want to install pmos from within on it's own host, more like imstalling it on an external device without requiring a desktop computer.

**Comment by xeffyr** [comment]
In order to run under Termux, `pmbootstrap` should be heavily patched. If you really need it, better to run it under LinuxDeploy or similar.
