### ISSUE TITLE
Newsboat stack corruption when opening article containing emojis

### ISSUE THREAD

**Issue by Nitroretro** [termux/termux-packages#4334]
**Problem description**
Newsboat crashes with the message "stack corruption detected" when opening an article containing emojis.
Video: https://i.imgur.com/1fehXWJ.mp4

**Steps to reproduce**
Open an article in Newsboat containing emojis. (Note: I am not sure if the title of the article matters, in this case both the title and the content contain emojis.)

Feed used in example: `https://www.twitrss.me/mobile_twitter_to_rss/?user=nitrome`

**Expected behavior**
It should open the article like it does on my Arch Linux PC. Keep in mind as of writing Arch's Newsboat package version is version 2.17, while on Termux it's 2.16.1.

*(Note: I am connected via ssh in the video, but the same issue occurs in Termux)*

**Additional information**
```shell
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.10.49-14895767 #1 SMP PREEMPT Tue Jun 11 20:25:44 KST 2019 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.1
Device manufacturer:
samsung
Device model:
SM-A5100
```

**Comment by xeffyr** [comment]
> Keep in mind as of writing Arch's Newsboat package version is version 2.15,

Perhaps [2.17](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/newsboat&id=26fc2a5ed5b7d8a4b3b9685cf58adc3ac269dc42), isn't it ?

**Comment by Nitroretro** [comment]
Yeah, updated recently I see. It's been out of date for some time :P

I still can't reproduce the issue on Arch with 2.17, so going to quickly edit that.

**Comment by xeffyr** [comment]
I have added a fix - https://github.com/termux/termux-packages/commit/bc9082eae83df9afd8025d650f40fb126741fc4d. Error seems Termux-specific and happens on ARM devices only.

**Comment by xeffyr** [comment]
Try `pkg upgrade` and check if error is gone.

**Comment by Nitroretro** [comment]
It works! Good job on fixing it.
