### ISSUE TITLE
Pls help me I got dis error You can now start vncserver by running vncserver-start

### ISSUE THREAD

**Issue by gunshut20** [termux/termux-packages#4335]
You can now start vncserver by running vncserver-start

It will ask you to enter a password when first time starting it.

The VNC Server will be started at 127.0.0.1:5901

You can connect to this address with a VNC Viewer you prefer

Connect to this address will open a window with Xfce4 Desktop Environment

Running vncserver-start

To Kill VNC Server just run vncserver-stop

/etc/profile: line 4: [: : integer expression expected
de-apt-xfce4.sh: line 44: /usr/local/bin/vncserver-start: Function not implemented

**Comment by xeffyr** [comment]
Probably related to https://github.com/termux/proot/issues/68.
