### ISSUE TITLE
Golang: Can't cross-compile for Android targets

### ISSUE THREAD

**Issue by pollen5** [termux/termux-packages#4338]
Just updated golang, it didn't work before but the error is different now.

Here's a terminal log
```
pollen@localhost ~/gostuff> cat test.go
package main

import "fmt"

func main() {
  fmt.Println("Hello, World!")
}
pollen@localhost ~/gostuff>
env GOARCH=arm64 GOOS=android go build test.go
# command-line-arguments
/data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm/link: running arm-linux-androideabi-clang failed: exit status 1
/data/data/com.termux/files/usr/tmp/go-link-173409349/go.o: file not recognized: file format not recognized
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)

pollen@localhost ~/gostuff>
env GOARCH=arm64 GOOS=linux go build test.go
pollen@localhost ~/gostuff> ./test
Hello, World!
pollen@localhost ~/gostuff>
env GOARCH=amd64 GOOS=windows go build test.go
pollen@localhost ~/gostuff> file test.exe
test.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
pollen@localhost ~/gostuff>
```
Building for arm64 android fails with linker errors (previously failed with a go related error i guess)

Building for arm64 again but targetting OS linux builds successfully, since my CPU is actually ARMv8l it can run 64 bit output successfully (however no 64 bit system libs but go outputs does not depend on libc or anything)

Building for windows even works fine, how can it build for every OS and arch except for Android targets, how does it link on other platforms but fail on Android.

Output of `termux-info`
```
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Fri Apr 19 13:20:06 CST 2019 armv8l Android
Termux-packages arch:
arm
Android version:
9
Device manufacturer:
HUAWEI
Device model:
AMN-LX9
```
I'm not 100% sure if this is go related or termux related but once i asked a friend to reproduce this on a real PC and he can cross compile to arm64 android with no issues so that leads me to trying to ask here.

**Comment by xeffyr** [comment]
Seems like golang relying on binutils, but we use lld for cross-compiling.

**Comment by xeffyr** [comment]
Maybe CGO should be disabled when cross-compiling.

**Comment by xeffyr** [comment]
```
~/test2 $ cat main.go 
package main

import "fmt"

func main() {
  fmt.Println("Hello, World!")
}
~/test2 $ CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o test
~/test2 $ file test
test: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=ELcQaDuK5utHjO3QJLCb/nUH4x-Bts-NVGoyA2tBO/qFJWaZrcQ-MtfkLjBNsQ/UyHX5JoVjIsGmMDmEV1b, not stripped
```

**Comment by xeffyr** [comment]
To have CGO enabled while cross-compiling, we will need a *complete* cross toolchain (C compiler + binutils) compiled for specific target. I'm in doubt that this will happen at some point.

**Comment by pollen5** [comment]
@xeffyr you got the wrong command, i showed that GOOS=linux is working fine, GOOS=android is the issue, CGO_ENABLED=0 didn't solve the issue

**Comment by xeffyr** [comment]
CGO can't be disabled for Android.

**Comment by pollen5** [comment]
oh okay, thanks
