### ISSUE TITLE
New npm packages

### ISSUE THREAD

**Issue by Kashkun** [termux/termux-packages#4340]
Getting an error everytime I try to install npm packages 
![Screenshot_20190924-165021_Termux](https://user-images.githubusercontent.com/37904263/65606325-ab07de80-df78-11e9-85b9-09fb726e03d1.jpg)

**Comment by xeffyr** [comment]
```
pkg install clang make python2
npm config set python $PREFIX/bin/python2
npm install -g sqlite
```
