### ISSUE TITLE
Cant Install PyX

### ISSUE THREAD

**Issue by ng1nX4O4** [termux/termux-packages#4342]
I Had Run `pip2 install pyx` here is the output screenshot
![Screenshot_20190926-091314](https://user-images.githubusercontent.com/47913604/65655389-e3252500-e03d-11e9-998b-6a4dd1dceb7c.png)

Here Is Termux Info
![Screenshot_20190926-091149](https://user-images.githubusercontent.com/47913604/65655405-ee785080-e03d-11e9-96bd-003a0880f836.png)

**Comment by RossComputerPerson** [comment]
Maybe try `pip` instead of `pip2`

**Comment by xeffyr** [comment]
Closing as problem related to third-party package.
