### ISSUE TITLE
A number of -dev packages are stuck with their old versions preventing proper updates

### ISSUE THREAD

**Issue by mike248** [termux/termux-packages#4343]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

The following packages (all of which are dependencies for building native extensions of certain ruby gems I have):

graphicsmagick-dev, libffi-dev, libgmp-dev, libiconv-dev, libnettle-dev, libsqlite-dev, libxml2-dev, libxslt-dev, ncurses-dev, openssl-dev, ruby-dev (and perhaps some other dev-packages I don't use)

still don't get updates and are older than their non-dev counterparts (I have them installed) which continue to get updates. 'pkg update' offers to REMOVE these outdated dev-packages, but this will render the native extensions in those ruby gems unable to compile normally and therefore the gems will stop get updated.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

//store the list of all packages to a file
pkg list-all > pkgs.txt
//open it in your text editor
micro pkgs.txt
//search for lines with "-dev" and compare them with adjacent packages with the same name but without "-dev"
# You'll see that all the packages mentioned in "Problem description" section are older than those without "-dev" in their names.
(For example, ruby and ruby-ri are 2.6.4 at the time of writing, but ruby-dev is still 2.6.3-4)

**Expected behavior**

All these dev-packages are expected to get updates along with their non-dev analogs.

**Additional information**
Post output of command `termux-info`.

termux-info
Updatable packages:
graphicsmagick/stable 1.3.33-1 arm [upgradable from: 1.3.33]
libffi/stable 3.2.1-4 arm [upgradable from: 3.2.1-3]
libgmp/stable 6.1.2-4 arm [upgradable from: 6.1.2-3]
libiconv/stable 1.16-3 arm [upgradable from: 1.16-2]
libnettle/stable 3.5.1-2 arm [upgradable from: 3.5.1-1]
libsqlite/stable 3.29.0-1 arm [upgradable from: 3.29.0]
libxml2/stable 2.9.9-4 arm [upgradable from: 2.9.9-3]
libxslt/stable 1.1.33-2 arm [upgradable from: 1.1.33-1]
ncurses/stable 6.1.20190511-7 arm [upgradable from: 6.1.20190511-5]
ncurses-ui-libs/stable 6.1.20190511-7 arm [upgradable from: 6.1.20190511-5]
ncurses-utils/stable 6.1.20190511-7 arm [upgradable from: 6.1.20190511-5]
openssl/stable 1.1.1d arm [upgradable from: 1.1.1c-1]
ruby/stable 2.6.4 arm [upgradable from: 2.6.3-4]
ruby-ri/stable 2.6.4 all [upgradable from: 2.6.3-4]
sqlite/stable 3.29.0-1 arm [upgradable from: 3.29.0]
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.35+ #2 SMP PREEMPT Thu Dec 7 15:20:09 CST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
7.0
Device manufacturer:
DEXP
Device model:
Ixion ML245
$

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by fornwall** [comment]
Packages are no longer split up in -dev packages - header files and similar are now available in the man package.

So just run `pkg up` and accept the proposal to delete the outdated -dev packages.

**Comment by mike248** [comment]
That's an interesting solution (esp for newbies maybe). Looked into *.deb for ruby and nurses - they're full of header files now!
