### ISSUE TITLE
Add sbin to su PATH

### ISSUE THREAD

**Issue by RichyHBM** [termux/termux-packages#4345]
As per the title, the su script adds /sbin/su to the path but not /sbin/, this means that a number of tools, mainly magisk related, are not in the path when using su

**Comment by RossComputerPerson** [comment]
I believe there's a valid reason why the devs added /sbin/su to the path and not /sbin/, probably has to do with what Termux aims to do.

**Comment by fornwall** [comment]
Thanks for reporting - the su script has now been updated to add /sbin/ to the path.

**Comment by xeffyr** [comment]
@fornwall The search path now looks
```
PATH=/sbin:/sbin/su:/su/bin:/su/xbin:/system/bin:/system/xbin
```
Isn't this will trigger an error in case `su` binary is located under `/sbin/su/` ?
