### ISSUE TITLE
Debootstrap is too slow

### ISSUE THREAD

**Issue by mahesh-hegde** [termux/termux-packages#4346]
**Problem description**
A `debootstrap` command in termux package `debootstrap` spends too much time in following stages:
`Resolving dependencies of required packages`
`Resolving dependencies of base packages`

**Steps to reproduce**
run debootstrap with appropriate options to bootstrap to an empty dir or download required debs. Dependency checking should not be disabled.
**Expected behavior**
Resolving of dependencies should take less time than it is now. How about including a cache text file in the package?

Also, if few downloads fail, debootstrap should ideally retry downloading them or at least prompt so.

**Additional information**
```
main
System information:
Linux localhost 3.10.64 #2 SMP PREEMPT Mon Nov 21 15:03:02 CST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.0
```

**Comment by RossComputerPerson** [comment]
Probably is just the speed of your device. `debootstrap` is a script so running bash programs take awhile.

**Comment by xeffyr** [comment]
Everything under `proot` is slow, especially thing based on scripts.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/blob/master/packages/debootstrap/debootstrap.patch#L67
