### ISSUE TITLE
chsh doesn't work without util-linux

### ISSUE THREAD

**Issue by mandeep** [termux/termux-packages#4347]
When running chsh or any other package that relies on getopt, the user receives an error without much detail: `getopt: not found`.

Turns out the user needs to `pkg install util-linux` to use getopt which the user is told when they type `getopt` into terminal. However, here getopt is trying to be used by chsh and no warning or info prompt is shown to the user.

**Comment by xeffyr** [comment]
`util-linux` as well as few other utilities was removed from bootstraps temporarily.
