### ISSUE TITLE
Add Python 2 support to Ledger

### ISSUE THREAD

**Issue by Shadow53** [termux/termux-packages#4348]
Ledger optionally (at compile-time) supports embedding Python into ledger files, e.g. to define functions that can be called elsewhere in the file, such as for complex queries.

I have a file with embedded Python in it. Running it with Ledger in Termux generates an error because Ledger was compiled without Python support. Can this be added?

As of this posting, Ledger seems only to support Python 2, not Python 3, though there is an open issue for adding support for v3. I've been working on (non-merged) edits to the FreeBSD port of ledger to add Python support, and it looks like it also has a dependency on Boost Python libraries, which in turn depend on NumPY. If that helps at all.

**Comment by fornwall** [comment]
I think we should avoid adding more Python 2 things at this stage, and rather move towards dropping Python 2 support.

**Comment by fornwall** [comment]
We have come to the decision to not add any new python 2-using packages. Let's revisit this once ledger adds python 3 support.
