### ISSUE TITLE
Proot error #usr/bin/bad no directory found! 

### ISSUE THREAD

**Issue by ayan231** [termux/termux-packages#4349]
I am getting this error on starting kali linux on my samsung device in termux armv8l. Please help me to fix that issue
![Screenshot_20190926-093557_Termux](https://user-images.githubusercontent.com/52261372/65813233-08599500-e1f0-11e9-9620-f6c820c252fe.jpg)

**Comment by xeffyr** [comment]
Closing as related to https://github.com/termux/proot/issues/76.
