### ISSUE TITLE
video output for mpv

### ISSUE THREAD

**Issue by treakiandroid** [termux/termux-packages#435]
Hi,

its greate that i can now run mpv (best mediaplayer ever) on android through termux. But it would be much better if there would be a working video output instead just an audio output. 

```
-bash-4.3$ mpv --vo=help
Available video outputs:
  null           : Null video output
  image          : Write video frames to image files

-bash-4.3$ mpv --ao=help
Available audio outputs:
  openal         : OpenAL audio output
  opensles       : OpenSL ES audio output
  null           : Null audio output
  pcm            : RAW PCM/WAVE file writer audio output

-bash-4.3$ 
```

I would be very happy if you could implement one, maybe also using opengl es. There is may some usable code in the vlc app.

thanks a lot in advance

**Comment by xeffyr** [comment]
Video output is subject of [x11-packages](https://github.com/termux/x11-packages).
```
pkg install x11-repo
pkg install mpv-x
```
