### ISSUE TITLE
package request: okc agent

### ISSUE THREAD

**Issue by doronbehar** [termux/termux-packages#4352]
Thank you so much @DDoSolitary for creating the open key chain projects which closed https://github.com/termux/termux-api/issues/230 . Could you package please https://github.com/DDoSolitary/okc-agents ? I won't mind working on that but you didn't publish any releases so I thought you might want to publish a release and then do it.

**Comment by DDoSolitary** [comment]
Unfortunately building this repo currently requires Nightly Rust, which isn't available as a Termux package so far so it would be quite hard to write a build.sh.

**Comment by doronbehar** [comment]
When Rust 1.39 will be released, would it be possible to package it then?

**Comment by auscompgeek** [comment]
Looks like okc-agents itself doesn't depend on unstable features, so the only things it needs are Rust 1.39, and I guess preferably also a stable tokio release that supports the async syntax.

**Comment by DDoSolitary** [comment]
Yes, all of the features(futures & async/await) okc-agents depend on have already been stabilized and can be used once Rust Stable 1.39 gets released. I know nothing about Rust's release strategy but according to the previous release dates it seems that they bump minor version number every 5 to 6 weeks: https://github.com/rust-lang/rust/blob/master/RELEASES.md

**Comment by Luflosi** [comment]
Rust 1.39 is now available in Termux: #4561.

**Comment by xeffyr** [comment]
We have now Rust 1.40 and okc-agents fails with a lot errors like
```
error[E0432]: unresolved import `tokio::net::TcpListener`
 --> src/bin/okc-ssh-agent.rs:9:5
  |
9 | use tokio::net::TcpListener;
  |     ^^^^^^^^^^^^^^^^^^^^^^^ no `TcpListener` in `net`

error[E0433]: failed to resolve: could not find `main` in `tokio`
  --> src/bin/okc-ssh-agent.rs:44:10
   |
44 | #[tokio::main]
   |          ^^^^ could not find `main` in `tokio`

error[E0433]: failed to resolve: could not find `UnixListener` in `net`
  --> src/bin/okc-ssh-agent.rs:51:29
   |
51 |     let listener = tokio::net::UnixListener::bind(&path)?;
   |                                ^^^^^^^^^^^^ could not find `UnixListener` in `net`
```

**Comment by DDoSolitary** [comment]
It seems that tokio has changed its API in the stable releases. I'll try to fix them when I have some spare time.

**Comment by DDoSolitary** [comment]
Sorry for the delay. The compilation errors has been fixed.

**Comment by xeffyr** [comment]
Package has been [added](https://github.com/termux/termux-packages/commit/672e395d3022e189c44305ed3dfb01891844b539).

You can obtain it with these commands:
```
pkg install okc-agents
```
*Note: if using non-Bintray repository, package may appear in 1 - 24 hours.*
