### ISSUE TITLE
ngrok

### ISSUE THREAD

**Issue by fancsali** [termux/termux-packages#4354]
**Package description**
I feel many of us use Termux as a quick and dirty dev environment, that's always in your pocket, should things with your server/project/work go south. A tool to be able to expose local services to the internet temporarily would aid testing and collaboration.

**Link to home page and sources**
1. Home page: https://ngrok.com
2. Source code: https://ngrok.com/downloads

**Additional information**
* I believe there's no source available, so I am bit unsure about the policy for packaging pre-compiled binaries, but I reckon it might be worth having a think about...

**Comment by Grimler91** [comment]
Pre-compiled binaries for termux (I.e. compiled against android's libc and with /data/data/com.termux/files/usr as prefix) doesn't exist afaik so packaging ngrok isn't possible, and we can't compile it as source isn't available as you said

**Comment by xeffyr** [comment]
@Grimler91 Ngrok works under Termux. Though, we don't package any kind of **paid, commercial, closed-source** stuff.

**Comment by xeffyr** [comment]
There really no valid reason to package stuff that is already built & working.

**Comment by fancsali** [comment]
Sure, you can `wget` it, it's just much nicer to say `pkg install ngrok`. ;)
