### ISSUE TITLE
Problem with Install

### ISSUE THREAD

**Issue by Timur13240** [termux/termux-packages#4355]
**Problem description**
Can't install Metasploit, because no -dev packages
![Screenshot_2019-09-30-18-27-17](https://user-images.githubusercontent.com/46261539/65879110-26222800-e3b1-11e9-8443-2041d4c0deff.png)

### **after 3 minutes...**

![Screenshot_2019-09-30-18-36-59](https://user-images.githubusercontent.com/46261539/65879519-c5471f80-e3b1-11e9-91ae-955ff6311182.png)

**Steps to reproduce**
pkg install unstable-repo
pkg install metasploit

**Expected behavior**
I was expecting the installation of metasploit-framework.

**Additional information**
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.65 #1 SMP PREEMPT Wed Mar 1 10:13:13 CST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
5.1
Device manufacturer:
DEXP
Device model:
Ixion MS450

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
Did you noticed that they are **recommended** ? I intentionally put them here to satisfy requirements for **old installations**.

**Dev packages are not needed !** They are merged with normal packages.

**Comment by xeffyr** [comment]
Error happens due to unknown compiler error. Maybe related to https://github.com/termux/termux-packages/issues/4287.
