### ISSUE TITLE
Init system

### ISSUE THREAD

**Issue by Merith-TK** [termux/termux-packages#4357]
**Package description**
LITTERALLY ANY INIT SYSTEM
Primary reason is its handy for services such as sshd, webservers, and the like. I was thinking sysv-init as its small and simple ish from my experience

**Comment by xeffyr** [comment]
1. https://wiki.termux.com/wiki/Termux-services

2. Termux is a **terminal application** and not **OS**.

**Comment by Merith-TK** [comment]
Well i know its not a OS, but a decent init system that runs along side termux for services would be nice. and the resources on that look nice
thanks for the link, my main thing for asking is it would make some of my programs easier to run, such as sshd and a webserver, 

Is there a way i can use termux-chroot to keep it using a more tradition unix filepathing? (so i dont have to use `/data/data/com.termux/files/usr`

**Comment by xeffyr** [comment]
> Is there a way i can use termux-chroot to keep it using a more tradition unix filepathing?

Add to bashrc following lines:
```
if [ -z "$TERMUX_CHROOT_USED" ]; then
    export TERMUX_CHROOT_USED=1
    exec termux-chroot
```
There just no other ways. You can't just symlink `termux-chroot` to `$HOME/.termux/shell` (like chsh does) because that will end in loop.

**Comment by Merith-TK** [comment]
I tried that to the bashrc, does nothing
https://hatebin.com/uwskvjcqan
