### ISSUE TITLE
[Major outage] Quota limit for termux-packages is reached

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-packages#4358]
## What happened ?

We received more download requests than expected and hit our quota limit. Repository `https://dl.bintray.com/termux/termux-packages-24` was suspended.

*Current status: appears to be resolved*

## What to do ?

Either wait or try repo snapshot on [IPFS](https://ipfs.io/) (expect high latency or download timeout, it's p2p and seeded from my PC):

Gateway 0:
```
deb https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main
```
Gateway 1:
```
deb https://cloudflare-ipfs.com/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main
```
Gateway 2:
```
deb https://ipfs.eternum.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main
```
Gateway 3:
```
deb https://hardbin.com/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main
```
Don't forget to temporarily comment out the bintray link in your sources.list before using mirror. Note that links above will no longer be valid after fixing the issue.

### Script for automatic mirror switching:
```
curl -o add-mirror.sh https://linx.li/add-mirror.sh
sh add-mirror.sh 0
```
it will comment out the termux-packages repository and put the selected mirror (0-3) to alternate sources.list config.

To remove changes applied with `add-mirror.sh`, do:
```
curl -o remove-mirror.sh https://linx.li/remove-mirror.sh
sh remove-mirror.sh
```

**Comment by Merith-TK** [comment]
approximately how long do we need to wait?
because I just reinstalled termux (storage issues) and I don't have a single text editor installed

**Comment by xeffyr** [comment]
> approximately how long do we need to wait?

One day, maybe less.

**Comment by goodevilgenius** [comment]
Any way to increases the timeout when using ipfs? I keep getting:

> Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds

**Comment by millersultani** [comment]
Sryy if I am being rude but WTFFFF.
I reseted my phone data.Erased the momery cuz I thought something is wrong with my phone and this is the problem. Argggggggg

**Comment by landfillbaby** [comment]
would deleting older versions of packages from the repo help?

**Comment by RossComputerPerson** [comment]
@landfillbaby It's too many requests causing the quota to cap out

**Comment by millersultani** [comment]
Guys I would recommend that you download UserLand. It's a Linux distribution and you can use Linux distros like kali in it . LINK = 
[]https://www.google.com/url?sa=t&source=web&rct=j&url=https://play.google.com/store/apps/details%3Fid%3Dtech.ula%26hl%3Den%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Duserland%26pcampaignid%3DAPPU_1_gtOSXaiHLeHWz7sP8O6Q2A8&ved=2ahUKEwio0JafmvrkAhVh63MBHXA3BPsQ5IQBMAh6BAgKEAM&usg=AOvVaw1e0mdCO3OrMTVWXkZkTd6y
-

**Comment by millersultani** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://play.google.com/store/apps/details%3Fid%3Dtech.ula%26hl%3Den%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Duserland%26pcampaignid%3DAPPU_1_gtOSXaiHLeHWz7sP8O6Q2A8&ved=2ahUKEwio0JafmvrkAhVh63MBHXA3BPsQ5IQBMAh6BAgKEAM&usg=AOvVaw1e0mdCO3OrMTVWXkZkTd6y

**Comment by Merith-TK** [comment]
@millersultani Please delete, it is not relevant at all

**Comment by millersultani** [comment]
> @millersultani Please delete, it is not relevant at all

How come. UserLand works thooo

**Comment by Merith-TK** [comment]
it is not relevant to Termux, it is a separate app that happens to utilize termux-app, not the packages. Please delete. Don't be a child and just delete this. If you're going to shitpost, do it somewhere where one expects there to be shit posting. (and yes, I do decree this as a form of shitposting)

**Comment by millersultani** [comment]
> it is not relevant to Termux, it is a separate app that happens to utilize termux-app, not the packages. Please delete. Don't be a child and just delete this. If you're going to shitpost, do it somewhere where one expects there to be shit posting. (and yes, I do decree this as a form of shitposting)

Mate, all I am trying to do is give people a solution or an option to their problem because I was facing this problem today with termux and I reseted my phone. It still didn't work so I did some research and found out that this was the problem. However i downlaoded UserLand and it works perfectly fine. Thanks

**Comment by RossComputerPerson** [comment]
@millersultani The only reason why Termux is not working right now is because a quota with the repositories have been reached, UserLand which is similar to Termux and has different repos won't be affected by this quota cap.

**Comment by millersultani** [comment]
> @millersultani The only reason why Termux is not working right now is because a quota with the repositories have been reached, UserLand which is similar to Termux and has different repos won't be affected by this quota cap.

Ik

**Comment by RossComputerPerson** [comment]
Then don't post about UserLand because it's not the same as Termux

**Comment by ParaDoxX08** [comment]
$ deb https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main
No command 'deb' found, did you mean:
 Command 'derb' from package 'icu-devtools'
 Command 'dub' from package 'ldc'
$

**Comment by RossComputerPerson** [comment]
@ParaDoxX08 It's not a command, that is a line to add into the apt sources file

**Comment by landfillbaby** [comment]
mkdir -p $PREFIX/etc/apt/sources.list.d
    echo 'deb https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main' > temp_outage.list
is what i've done personally

**Comment by karjok** [comment]
I have this error. I will try to fixing it.

**Comment by karjok** [comment]
Yeah, 
deb https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main
Work fine for me !

**Comment by MRxr00t** [comment]
please 

pkg install nano                                      Hit:1 https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr stable InRelease
Ign:2 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:3 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:4 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:5 https://dl.bintray.com/termux/termux-packages-24 stable Release
  403  Forbidden
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:8 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:8 https://dl.bintray.com/grimler/science-packages-24 science Release
Reading package lists... Done
E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by ikhsanh** [comment]
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Hit:2 https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr stable InRelease
Ign:3 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:4 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:5 https://dl.bintray.com/termux/termux-packages-24 stable Release
  403  Forbidden
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:8 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:8 https://dl.bintray.com/grimler/science-packages-24 science Release
Reading package lists... Done
E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$

How to fix this? I have been add deb https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main in termux/termux but not working. Plz help me

**Comment by yubrajbhoi** [comment]
@ikhsanh Try doing it like described in @landfillbaby comment. It worked for me.

**Comment by ikhsanh** [comment]
@yubrajbhoi
 I tried it, but it doesn't work

**Comment by dragonmaus** [comment]
I get the following:
```
$ mkdir -p $PREFIX/etc/apt/sources.list.d
$ echo deb https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main > $PREFIX/etc/apt/sources.list.d/temp_outage.list
$ pkg update
Hit:1 https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr stable InRelease
Ign:2 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Err:3 https://dl.bintray.com/termux/termux-packages-24 stable Release
  403  Forbidden
Reading package lists... Done
E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by xeffyr** [comment]
Comment out the line containing `https://dl.bintray.com/termux/termux-packages-24` in `$PREFIX/etc/apt/sources.list`.

**Comment by xeffyr** [comment]
You don't have problem with ipfs link
> Hit:1 https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr stable InRelease

**Comment by xeffyr** [comment]
Or you can just ignore that error without commenting anything. Index will be fetched anyway.

**Comment by amida141** [comment]
Idk how to add it to apt file ??? Howwww?

**Comment by xeffyr** [comment]
See comment https://github.com/termux/termux-packages/issues/4358#issuecomment-536875603.

**Comment by amida141** [comment]
I get the following
$ mkdir -p $PREFIX/etc/apt/sources.list.d
$ echo deb https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main > $PREFIX/etc/apt/sources.list.d/temp_outage.list
$ pkg install figlet
Hit:1 https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr stable InRelease
Ign:2 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:3 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:4 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:5 https://dl.bintray.com/termux/termux-packages-24 stable Release
  403  Forbidden
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:8 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:8 https://dl.bintray.com/grimler/science-packages-24 science Release
Reading package lists... Done
E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Anything like this can't upgrade and can't update

**Comment by xeffyr** [comment]
@amida141 Since you now have `Hit:1 https://ipfs.io/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr stable InRelease` - it works. You can ignore error about termux-packages.

**Comment by yubrajbhoi** [comment]
@amida141 Your IPFS link seems to be working so just comment out the line containing `https://dl.bintray.com/termux/termux-packages-24` in `$PREFIX/etc/apt/sources.list`.

**Comment by dragonmaus** [comment]
@xeffyr
The error prevents apt/pkg from continuing. @yubrajbhoi has the solution.

**Comment by xeffyr** [comment]
It may prevent pkg from continuing but with just `apt update` then `apt install <some packages>` works.

I added script for automating this:
```
curl https://linx.li/add-mirror.sh > add-mirror.sh
sh add-mirror.sh 0
```
run without arguments to see available mirror shortcuts.

**Comment by frankenzteinbeck** [comment]
pkg install xeffy
Hit:1 post-singularity inter-dimensional tech-support
Reading fire Is everywhere oh god my internet is burning down... Done
Building life raft to sail the fiery wasteland of godless broken hell
Reading ah fuck yeah my internets is back to themselves now its sandwich time... Done
All packages are up to date.

**Comment by xeffyr** [comment]
Seems `termux-packages` is now restored and working.
Mirror link can be removed. Those who used script/commands from https://github.com/termux/termux-packages/issues/4358#issuecomment-536875603 or https://github.com/termux/termux-packages/issues/4358#issuecomment-537015509 can use 
```
curl -o remove-mirror.sh https://linx.li/remove-mirror.sh
sh remove-mirror.sh
```
