### ISSUE TITLE
add cron

### ISSUE THREAD

**Issue by treakiandroid** [termux/termux-packages#436]
cron with autostart (and autorestart if android kills it) would be very nice. please implement it.

thanks

**Comment by paradigm** [comment]
FWIW, termux's busybox provides crond.  For me it's at `/data/data/com.termux/files/usr/bin/applets/crond`.  I don't know if it lacks any features that GNU's cron has, but the basics which I expected are all there.  Works fine for me.

As for auto-starting, that sounds like [issue 14 in termux-app](https://github.com/termux/termux-app/issues/14).  I want that as well.

As for auto-restarting if Android kills it, I found Android kills it (and other services) if left in the background, but so long as you have a Termux terminal open in the foreground (so when you swipe down from the bar at the top it shows a termux terminal is running) it seems to keep it open.  That is, until it updates Termux at which point it restarts it.  I have Android set not to auto-update termux; I do it manually when it indicates there's an update then restart crond et al myself.

**Comment by xeffyr** [comment]
Utilities `crond` and `crontab` available via busybox package (preinstalled). I don't think that there will be some benefits with "full" cron.

Those, who looking for *autostart* feature may want to use [Termux:Boot](https://wiki.termux.com/wiki/Termux:Boot) addon.
