### ISSUE TITLE
The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does no longer have a Release file.

### ISSUE THREAD

**Issue by ivitan** [termux/termux-packages#4360]
## Android 10
> The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does no longer have a Release file.
how to solve this problem?

**Comment by edubrazilswit** [comment]
Having same problem. Can't install any tool.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/4358
