### ISSUE TITLE
Can't update or install new packages 

### ISSUE THREAD

**Issue by millersultani** [termux/termux-packages#4361]
I just installed termux and I am facing this error while trying to update and install packages.

E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I have no idea how to fix it. PLEASE HELP THANKS

**Comment by dipayand** [comment]
Same here

**Comment by RossComputerPerson** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/4358
