### ISSUE TITLE
 Uploading packages: creating entry for version '5.0.11'... forbidden

### ISSUE THREAD

**Issue by sohutek** [termux/termux-packages#4362]
**Problem description**
"./scripts/package_uploader.sh bash" command made me get this alert 
[@] Uploading packages:

    * bash: creating entry for version '5.0.11'... forbidden

I must be missing something or what i did wrong?

**Comment by RossComputerPerson** [comment]
Maybe the quota cap mentioned in https://github.com/termux/termux-packages/issues/4358 is affecting this script

**Comment by landfillbaby** [comment]
i think it's unrelated to that, you just can't upload to bintray because you aren't registered there as a contributor to termux

**Comment by sohutek** [comment]
Thanks you guys so much

**Comment by xeffyr** [comment]
> I must be missing something or what i did wrong?

We are not allowing uploads by arbitrary people.
**Create OWN repository.**

**Comment by sohutek** [comment]
@xeffyr Where can i edit it? Pardon me. I'm new and maybe i have some stupid questions.

**Comment by xeffyr** [comment]
> Where can i edit it?

Can you at least open the script (I'm about ./scripts/package_uploader.sh) with text editor and review it ?
https://github.com/termux/termux-packages/blob/master/scripts/package_uploader.sh#L73
