### ISSUE TITLE
Repository can not done securely

### ISSUE THREAD

**Issue by arifjahan88** [termux/termux-packages#4366]
E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

This is showing when i install any package

**Comment by woofwoof** [comment]
Just been getting the same error report attempting to install Python. Tried updating and upgrading but still get the error. Could anybody please help?

Thanks. WW.

**Comment by arifjahan88** [comment]
Not solve...
