### ISSUE TITLE
Forbidden (#403)

### ISSUE THREAD

**Issue by dsvenky** [termux/termux-packages#4368]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by dsvenky** [comment]
Solve me this issue in termux  I was tried in different ways but I'm getting it again

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/4358
