### ISSUE TITLE
termux-chroot does not setup the enviroment correctly

### ISSUE THREAD

**Issue by Merith-TK** [termux/termux-packages#4374]
**Problem description**
Termux-Chroot does not properly handle file paths, still treats the file paths as if it didnt exist, but certain enviroment variables that are supposed to change, do change, but not the pathing

AKA, `/data/data/com.termux/files/usr` does not become `/` and `/data/data/com.termux/files/home/` does not become `/home` from what i can see

**Steps to reproduce**
Android 9, fresh install of proot (for termux-chroot command)
I do have termux-setup-storage setup
**Expected behavior**
a simple chroot

**Additional information**
```
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.111-16159346 #1 SMP PREEMPT Tue Aug 6 16:41:43 KST 2019 armv8l Android
Termux-packages arch: arm
Android version: 9
Device manufacturer: samsung
Device model: SM-J337R4
```

**Comment by xeffyr** [comment]
$PREFIX will always be /data/data/com.termux/files/usr. All packages are compiled against that and it won't be changed. Even under `termux-chroot`.

`termux-chroot` is just compatibility layer and it works as intended.

Regarding last comments in https://github.com/termux/termux-packages/issues/4357:
[![asciicast](https://asciinema.org/a/DgUuX9tSK67srnSETPb0a4Rkz.svg)](https://asciinema.org/a/DgUuX9tSK67srnSETPb0a4Rkz)

**Comment by Merith-TK** [comment]
```
$ termux-chroot
$ ls /
ls: cannot open directory '/': Permission denied
```

the chroot does not work

**Comment by xeffyr** [comment]
You really have something wrong. Try to reinstall. If still not working, then issue probably to proot's repository.

**Comment by xeffyr** [comment]
Is proot works for you at all ?

**Comment by Merith-TK** [comment]
Dont know, i litterally just uninstalled to reinstall, give me a second

**Comment by Merith-TK** [comment]
on a COMPLETELY FRESH INSTALL

(uninstall app, reinstall, 
`pkg install nano proot termux-auth wget curl openssh` has the same issue.

When i get home i think i can hook up the app to Android Studio debugger,

**Comment by Merith-TK** [comment]
@xeffyr i can give you ssh to poke around if you like

**Comment by Merith-TK** [comment]
Okay proot works normally,
```sh
#!/data/data/com.termux/files/usr/bin/bash
cd $(dirname $0)
## unset LD_PRELOAD in case termux-exec is installed
unset LD_PRELOAD
command="proot"
command+=" --link2symlink"
command+=" -0"
command+=" -r alpine-fs"
if [ -n "$(ls -A alpine-binds)" ]; then
    for f in alpine-binds/* ;do
      . $f
    done
fi
command+=" -b /dev"
command+=" -b /proc"
command+=" -b alpine-fs/root:/dev/shm"
## uncomment the following line to have access to the home directory of termux
#command+=" -b /data/data/com.termux/files/home:/root"
## uncomment the following line to mount /sdcard directly to /
#command+=" -b /sdcard"
command+=" -w /root"
command+=" /usr/bin/env -i"
command+=" HOME=/root"
command+=" PATH=PATH=/bin:/usr/bin:/sbin:/usr/sbin"
command+=" TERM=$TERM"
command+=" LANG=C.UTF-8"
command+=" /bin/sh --login"
com="$@"
if [ -z "$1" ];then
    exec $command
else
    $command -c "$com"
fi
```

I used anlinux script for alpine.
