### ISSUE TITLE
dnsutils is broken

### ISSUE THREAD

**Issue by 610th** [termux/termux-packages#4377]
**Problem description**
The tracepath and dig command does not work due to linking error.

bash-4.4$ nslookup telia.se
CANNOT LINK EXECUTABLE "nslookup": library "libreadline.so.8" not found

bash-4.4$ dig telia.se
CANNOT LINK EXECUTABLE "dig": library "libcrypto.so.1.1" not found

**Steps to reproduce**
Run `dig` and `nslookup`.

**Expected behavior**
A nice stdout output as expected.

**Additional information**
Termux version:
<=0.48
Installed Termux apps:
Updatable packages:
apt/stable 1.4.9-7 aarch64 [upgradable from: 1.2.12-3]
bash/stable 5.0.11 aarch64 [upgradable from: 4.4.12]
busybox/stable 1.30.1-6 aarch64 [upgradable from: 1.27.2]
ca-certificates/stable 20190828 all [upgradable from: 20170920]
command-not-found/stable 1.37 aarch64 [upgradable from: 1.26]
dash/stable 0.5.10.2-2 aarch64 [upgradable from: 0.5.9.1]
dpkg/stable 1.19.7-4 aarch64 [upgradable from: 1.18.24]
gpgv/stable 2.2.17 aarch64 [upgradable from: 1.4.22]
ldns/stable 1.7.1-1 aarch64 [upgradable from: 1.7.0-4]
libandroid-support/stable 24-5 aarch64 [upgradable from: 22]
libc++/stable 20-1 aarch64 [upgradable from: 15.2]
libedit/stable 20190324-3.1-1 aarch64 [upgradable from: 20170329-3.1-0]
liblzma/stable 5.2.4-2 aarch64 [upgradable from: 5.2.3]
libutil/stable 0.4 aarch64 [upgradable from: 0.3]
ncurses/stable 6.1.20190511-7 aarch64 [upgradable from: 6.0.20170909-1]
openssh/stable 8.0p1-5 aarch64 [upgradable from: 7.6p1]
openssl/stable 1.1.1d-1 aarch64 [upgradable from: 1.0.2l-1]
readline/stable 8.0.1 aarch64 [upgradable from: 7.0.3-1]
termux-tools/stable 0.70 all [upgradable from: 0.46]
System information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Wed Jul 31 18:37:40 HKT 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
OnePlus
Device model:
ONEPLUS A5000

**Comment by xeffyr** [comment]
Your packages aren't up-to-date. This is not a bug.
https://github.com/termux/termux-packages/#bug-reports

**Comment by xeffyr** [comment]
```
pkg upgrade
```
if package manager isn't broken, otherwise reinstall.
