### ISSUE TITLE
calcurse: visual glitches when editing a note

### ISSUE THREAD

**Issue by Nitroretro** [termux/termux-packages#4378]
**Problem description**
When editing a note in calcurse by pressing `n` on a todo item or appointment, it opens up your text editor of choice, but it has a lot of visual glitches. You can see calcurse updating the clock while it's opened. This makes the note-taking feature really hard to use on Termux.

**Steps to reproduce**
```shell
$ calcurse
# Add a todo item and press `n` to edit a note
```

Video: [calcurse-issue-videos.zip](https://github.com/termux/termux-packages/files/3681109/calcurse-issue-videos.zip) (GitHub doesn't let you upload .mp4)

**Expected behavior**
It shouldn't have any visual glitches and work like on Arch. Additional videos showcasing the issue are attached in [calcurse-issue-videos.zip](https://github.com/termux/termux-packages/files/3681109/calcurse-issue-videos.zip). In the Termux video, I'm connected via ssh. This happens with the Termux app itself as well, so it seems like it's a problem with the package.

**Additional information**
```shell
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.10.49-14895767 #1 SMP PREEMPT Tue Jun 11 20:25:44 KST 2019 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.1
Device manufacturer:
samsung
Device model:
SM-A5100
```

**Comment by Grimler91** [comment]
I can reproduce it on aarch64, android 9, as well, or well something very similar

**Comment by fornwall** [comment]
Could it be caused by our calcurse patches replacing pthread_cancel)) and pthread_join() with pthread_kill()?

**Comment by xeffyr** [comment]
> replacing pthread_cancel

More like due to removed `pthread_join()`. I can build calcurse with Termux patches for desktop and check if issue will happen.

**Comment by xeffyr** [comment]
Yes, with our patches the issue reproducible on desktop.

**Comment by xeffyr** [comment]
We need to use something like https://github.com/tux-mind/libbthread/blob/master/pt-cancel.c.

**Comment by fornwall** [comment]
I tried out a build with libbthread, but it did not work (hangs).

It may be due to libbthread having [an old copy of the pthread_internal_t definition in bionic](https://github.com/tux-mind/libbthread/blob/master/pt-internal.h#L33), which is no longer what bionic has: https://android.googlesource.com/platform/bionic/+/master/libc/bionic/pthread_internal.h#65.

Having it work well across android versions and vendors by relying on an internal struct in bionic is probably difficult. Is there another alternative?
