### ISSUE TITLE
m4: FORTIFY: %n not allowed on Android

### ISSUE THREAD

**Issue by easyaspi314** [termux/termux-packages#4381]
**Problem description**
Any call to m4 results in FORTIFY blocking %n == abort

**Steps to reproduce**

```
$ m4
FORTIFY: %n not allowed on Android
Aborted
```

**Expected behavior**
It actually works

**Additional information**
```

Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.177-g83bee1dc48e8 #1 SMP PREEMPT Mon Jul 22 20:12:03 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
10
Device manufacturer:
Google
Device model:
Pixel 2 XL
```

The crash seems to be caused by a vsnprintf call, although `strings $(which m4) | grep %n` comes clean.

**Comment by xeffyr** [comment]
> The crash seems to be caused by a vsnprintf call

If so, then perhaps we need to use own implementation of some libc functions for Android 10.

**Comment by easyaspi314** [comment]
Got it. They are using an ***__ANCIENT__*** version of Gnulib. We need to update it, or at least patch vasnprintf.c:4861 to also exclude __ANDROID__ like newer releases

**Comment by fornwall** [comment]
@easyaspi314 Thanks for the information - patch has been applied to the latest `1.4.18-3` version of the package.

**Comment by Strahinja** [comment]
I'm still getting this error on a fresh install of Termux with the its-pointless' gcc_termux installed. Is there anything else that needs to be done besides `apt upgrade` to have this fix propagated?

**Comment by xeffyr** [comment]
@Strahinja Each package has to be fixed individually. `groff` is not official Termux package, so please report the issue where you get it (to its-pointless repo).
