### ISSUE TITLE
Gatling - high performance http, ftp and smb server

### ISSUE THREAD

**Issue by Zuccace** [termux/termux-packages#4386]
I'd like to propose addition of [Gatling](http://www.fefe.de/gatling/) into termux repositories.

Gatling is ideal to those who need a simple solution to share files (and local web pages) via termux. It is also marketed as "high performance" which could indicate it being able to run on low power devices without much computation load.
Also, please _do_ read the feature list from Gatling website. Quite a feature set for such a small program, I think.

**Comment by xeffyr** [comment]
Will require `libowfat`.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install gatling
```

**Comment by Zuccace** [comment]
Excellent. Thank you very much. :)
