### ISSUE TITLE
Package Request: mtd-utils

### ISSUE THREAD

**Issue by 5p0ng3b0b** [termux/termux-packages#4387]
**Package description**
Various tools for processing filesystems and firmwares for flash devices.
Required in order to use binwalk effectively.

The ability to extract firmwares and modify them on the actual device makes sense.

**Link to home page and sources**
Home page: http://www.linux-mtd.infradead.org/
Source code: ftp://ftp.infradead.org/pub/mtd-utils/mtd-utils-2.1.1.tar.bz2

**Additional information**
Tried to compile myself but get error:

CCLD     mkfs.jffs2
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: jffsX-utils/mkfs_jffs2-mkfs.jffs2.o: in function `write_dirent':
/data/data/com.termux/files/home/mtd-utils-2.1.1/jffsX-utils/mkfs.jffs2.c:713: undefined reference to `IFTODT'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:2298: mkfs.jffs2] Error 1

**Comment by RossComputerPerson** [comment]
Probably requires root access so this issue needs to be moved to the https://github.com/termux/termux-root-packages, I cannot access the website as Firefox is saying it's insecure from its SSL certificate.

**Comment by xeffyr** [comment]
> Required in order to use binwalk effectively.

It required for supporting JFFS2 file system. You don't need `mtd-utils` unless you are working with JFFS2 images.

**Comment by xeffyr** [comment]
> Probably requires root access

@RossComputerPerson There number of utilities, but not all of them require root.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/commit/54873ae802ff73858c39d6d2064246d00562b19e
