### ISSUE TITLE
unpack tar file some hard link problem

### ISSUE THREAD

**Issue by remo7777** [termux/termux-packages#4389]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.
## architecture armv7l (arm)

`screenshot of installation kali-fs proot`
![Screenshot_20191005-141143](https://user-images.githubusercontent.com/28594846/66252613-3ce2c900-e77b-11e9-9197-3476b0948231.jpeg)

**Comment by xeffyr** [comment]
https://github.com/termux/proot/issues/75
