### ISSUE TITLE
NPM Permission denied

### ISSUE THREAD

**Issue by sohutek** [termux/termux-packages#4398]
**Problem description**
I build my own packages with custom prefix. I added NodeJS, and finally got bootstraps.zip files. I use this file for my app. But i've caught this problem every times i run "npm ***". All other packages've just worked fine. 
`bash: /data/data/com.myapp/files/usr/bin/npm: Permission denied`
What was i missing?

**Comment by xeffyr** [comment]
Make sure you understand the following piece of bootstrap installer:
https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/TermuxInstaller.java#L115

**Comment by xeffyr** [comment]
Please note that all discussions about Termux forks & derivatives are **offtopic** on all repositories belonging to @termux.

If you decided to create own Termux-based application make sure that:

* You well understand command line & bash syntax.  -- this is on what all our scripts and build system based.

* At least basic understanding of Java & Android app structure.  -- without this you won't be able to customize fork for your needs.

* Understanding build process of package. -- needed if you want to add custom packages.

**We are not teaching center. Moreover, we are not going to debug forks.**
