### ISSUE TITLE
Package request: tin-summer a replacement for du

### ISSUE THREAD

**Issue by gMan1990** [termux/termux-packages#4406]
**Package description**
Describe what this package do and why it should be available.

`du` not have option `--exclude`

**Link to home page and sources**
1. Home page:
2. Source code: https://github.com/vmchale/tin-summer
3. Binary release: https://github.com/vmchale/tin-summer/releases

**Comment by chellakutti** [comment]
Reading package lists... Error!
W: chmod 0600 of file /data/data/com.termux/files/usr/var/lib/apt/lists/dl.bintray.com_termux_termux-packages-24_dists_stable_Release failed - Item::QueueURI (1: Operation not permitted)
W: chmod 0644 of file /data/data/com.termux/files/usr/var/lib/apt/lists/dl.bintray.com_termux_termux-packages-24_dists_stable_Release failed - 201::URIDone (1: Operation not permitted)
W: chmod 0600 of file /data/data/com.termux/files/usr/var/lib/apt/lists/dl.bintray.com_grimler_game-packages-24_dists_games_Release failed - Item::QueueURI (1: Operation not permitted)
W: chmod 0644 of file /data/data/com.termux/files/usr/var/lib/apt/lists/dl.bintray.com_grimler_game-packages-24_dists_games_Release failed - 201::URIDone (1: Operation not permitted)
W: chmod 0600 of file /data/data/com.termux/files/usr/var/lib/apt/lists/dl.bintray.com_grimler_science-packages-24_dists_science_Release failed - Item::QueueURI (1: Operation not permitted)
W: chmod 0644 of file /data/data/com.termux/files/usr/var/lib/apt/lists/dl.bintray.com_grimler_science-packages-24_dists_science_Release failed - 201::URIDone (1: Operation not permitted)
W: chmod 0600 of file /data/data/com.termux/files/usr/var/lib/apt/lists/dl.bintray.com_xeffyr_unstable-packages-24_dists_unstable_Release failed - Item::QueueURI (1: Operation not permitted)
W: chmod 0644 of file /data/data/com.termux/files/usr/var/lib/apt/lists/dl.bintray.com_xeffyr_unstable-packages-24_dists_unstable_Release failed - 201::URIDone (1: Operation not permitted)
W: Problem unlinking the file /data/data/com.termux/files/usr/var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /data/data/com.termux/files/usr/var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
E: Problem renaming the file /data/data/com.termux/files/usr/var/cache/apt/srcpkgcache.bin.NW9tqn to /data/data/com.termux/files/usr/var/cache/apt/srcpkgcache.bin - rename (13: Permission denied)
E: Could not open file /data/data/com.termux/files/usr/var/lib/dpkg/status - open (13: Permission denied)
E: Problem opening /data/data/com.termux/files/usr/var/lib/dpkg/status
E: The package lists or status file could not be parsed or opened.
+--root@localhost~: +?#https://github.com/termux/termux-packages.wiki.git
bash: https://github.com/termux/termux-packages.wiki.git: No such file or directory

**Comment by qwerty12** [comment]
This builds - and runs fine - if you `sed -i 's/linux/android/g' src/utils.rs` before building.

**Comment by xeffyr** [comment]
@qwerty12 Thanks, will look at packaging it.

**Comment by gMan1990** [comment]
I find a similar command `ncdu`.
```text
ncdu <options> <directory>
  --exclude PATTERN          Exclude files that match PATTERN
```

**Comment by xeffyr** [comment]
Closing as package was added in https://github.com/termux/termux-packages/commit/f6bce3428205e4c1d569d12fb53f54383aab8ca7.

`pkg install tin-summer`
