### ISSUE TITLE
CANNOT LINK EXECUTABLE "sh"

### ISSUE THREAD

**Issue by hisimon** [termux/termux-packages#4408]
CANNOT LINK EXECUTABLE "sh": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit
dpkg: error processing package mariadb (--configure):
 installed mariadb package post-installation script subprocess was killed by signal (Aborted)
Errors were encountered while processing:
 mariadb

**Comment by Grimler91** [comment]
Have you restored an installation from another device?

Try to run `unset LD_PRELOAD` as a temporary fix
