### ISSUE TITLE
Can't able to access installed packages with ls command

### ISSUE THREAD

**Issue by MahendraMk** [termux/termux-packages#4409]
![Screenshot_20191009_202452](https://user-images.githubusercontent.com/56356996/66493493-cb38b100-ead3-11e9-8ddb-489328ea347d.jpg)

ls command not listout installed pkg its only shows storage

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
I don't see any problem on your screenshot since everything is accessible.
