### ISSUE TITLE
ls -l "error initializing month strings"

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#441]
If you type `ls -l` you will get the message `ls: error initializing month strings`. I suspect it is related to the recent commit to coreutils https://github.com/termux/termux-packages/commit/ec64262da3aab5c2fbf8f4451cb9b8dffda43f07

**Comment by fornwall** [comment]
@tigran123 Thanks, too much of the patch was removed by mistake! Fix in `8.25-6`, run `apt update && apt upgrade -y`.

**Comment by tigran123** [comment]
Yes, I confirm that build 8.25-6 fixed it, thanks.
