### ISSUE TITLE
NODEJS

### ISSUE THREAD

**Issue by ZOOENZZ** [termux/termux-packages#4410]
**Problem description**
when i type "node index.js" Notting happen, but two days ago it was working

**Steps to reproduce**
Node command

**Additional information**
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Wed May 22 13:55:45 WIB 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
Redmi Note 5

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
> when i type "node index.js" Notting happen, but two days ago it was working

Revert your index.js to version available two days ago and most likely it will work.

**Comment by xeffyr** [comment]
NodeJS works fine on all devices.
