### ISSUE TITLE
Package request : ccls

### ISSUE THREAD

**Issue by StephanBeer** [termux/termux-packages#4417]
C/C++ language server for Neovim (via CoC floating window) or Emacs/Spacemacs (via lsp-mode). Besides Clangd language server (which is not available in Termux through the LLVM  pkg with clangd and clang-tidy linter?) the best way for getting autocompletion, headers etc when programming c/c++ in nvim.

Source code and homepage https://github.com/MaskRay/ccls

CoC ...language server c/c++ section https://github.com/neoclide/coc.nvim/blob/master/Readme.md
    
Absent in repositories...Termux 😔😉
https://repology.org/project/ccls/versions  

ccls, which originates from cquery, is a C/C++/Objective-C language server.

code completion (with both signature help and snippets)

definition/references, and other cross references

cross reference extensions: $ccls/call $ccls/inheritance $ccls/member $ccls/vars ...

formatting

hierarchies: call (caller/callee) hierarchy, inheritance (base/derived) hierarchy, member hierarchy

symbol rename

document symbols and approximate search of workspace symbol

hover information

diagnostics and code actions (clang FixIts)

semantic highlighting and preprocessor skipped regions

semantic navigation: $ccls/navigate

**Comment by its-pointless** [comment]
Its available on unstable packages
