### ISSUE TITLE
android6 error help..

### ISSUE THREAD

**Issue by poptong** [termux/termux-packages#4419]
/libandroid-support.so: unused DT entry: type 0x1d arg 0x244
CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced by "/libandroid-support.so"...

**Comment by xeffyr** [comment]
Please post **complete console log** including executed command.

**Comment by poptong** [comment]
#!/bin/bash
export TERMUX_ARCH=arm
export TERMUX_PREFIX=/data/android/usr
export TERMUX_ANDROID_HOME=/data/home
./build-package.sh python

**Comment by xeffyr** [comment]
On-device builds doesn't support different prefix/home paths, so
```
export TERMUX_PREFIX=/data/android/usr
export TERMUX_ANDROID_HOME=/data/home
```
will not work.

This - `export TERMUX_ARCH=arm` will not work too. On device builds are done only for host arch.

And finally, make sure you read the https://github.com/termux/termux-packages/wiki/Build-environment#termux.

***

Regarding error in https://github.com/termux/termux-packages/issues/4419#issue-506325123, you probably messed up your environment (this is a side effect of on-device builds, btw).
