### ISSUE TITLE
Package request: ledger-cli

### ISSUE THREAD

**Issue by linuxcaffe** [termux/termux-packages#442]
(from ledger-cli.org)
Ledger is a powerful, double-entry accounting system that is accessed from the UNIX command-line.

(from http://ledger-cli.org/3.0/doc/ledger3.html#Building-the-program)
Ledger is written in ANSI C++, and should compile on any unix platform. The easiest way to build and install ledger is to use the prepared acprep script, that does a lot of the footwork:

**Comment by paradigm** [comment]
Looks like it's a disabled package, waiting on boost: https://github.com/termux/termux-packages/blob/master/disabled-packages/ledger/build.sh

**Comment by bergie** [comment]
Potentially related to this Boost PR? #974

**Comment by its-pointless** [comment]
Yes directly related.

**Comment by paradigm** [comment]
Give that boost is now in, looks like a pull request was made for this package: https://github.com/termux/termux-packages/pull/976

**Comment by fornwall** [comment]
Thanks to @its-pointless a `ledger` package is now available for installation:

    packages install ledger
