### ISSUE TITLE
Aria2c receives SIGILL when downloading torrent link

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#4420]
**Problem description**

```
Program received signal SIGILL, Illegal instruction.
#0  0xb69af346 in ?? () from /data/data/com.termux/files/usr/lib/libcrypto.so.1.1
#1  0xb69af24c in ?? () from /data/data/com.termux/files/usr/lib/libcrypto.so.1.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Steps to reproduce**
`aria2c "https://cdimage.debian.org/debian-cd/current/i386/bt-cd/debian-10.1.0-i386-netinst.iso.torrent"`

**Expected behavior**
Everything works up until version 1.34.0-8 of aria2

**Additional information**
```
Updatable packages:
All packages up to date
Subscribed repositories:
http://localhost:8111 unstable/main
http://localhost:8111 x11/main
http://localhost:8111 science/stable
http://localhost:8111 games/stable
http://localhost:8111 root/stable
http://localhost:8111 main/main
System information:
Linux localhost 3.4.0-perf-ge616a4e4391 #1 SMP PREEMPT Wed May 8 01:56:49 UTC 2019 armv7l Android
Termux-packages arch:
arm
Android version:
8.1.0
Device manufacturer:
Fairphone
Device model:
FP2
```

[strace.log](https://github.com/termux/termux-packages/files/3721916/strace.log)

**Comment by xeffyr** [comment]
@Neo-Oli It isn't failing due to illegal instruction. If you trying to run an OpenSSL-based program under GDB, you need to do
```
handle SIGILL nostop
```

I'm doing a debug build to check what happens.

**Comment by Neo-Oli** [comment]
> @Neo-Oli It isn't failing due to illegal instruction. If you trying to run an OpenSSL-based program under GDB, you need to do

Ah yes. I remember doing this excact same mistake a while ago :S

**Comment by xeffyr** [comment]
Building `aria2` with -Os fixes the problem.
