### ISSUE TITLE
nodejs runs toooooo slow

### ISSUE THREAD

**Issue by yunfan** [termux/termux-packages#4422]
**Problem description**
the nodejs installed by pkg runs too slow, it will take minutes before i saw the console

**Steps to reproduce**
no need special steps, i think it might caused by the specific version or my android enviroment

**Expected behavior**
fix it , make it runs normally

**Additional information**
```
$ termux-info
Updatable packages:
command-not-found/stable 1.42 aarch64 [upgradable from: 1.39]
curl/stable 7.66.0-1 aarch64 [upgradable from: 7.66.0]
dos2unix/stable 7.4.1 aarch64 [upgradable from: 7.4.0-1]
libcurl/stable 7.66.0-1 aarch64 [upgradable from: 7.66.0]
openssh/stable 8.1p1 aarch64 [upgradable from: 8.0p1-6]
openssl/stable 1.1.1d-1 aarch64 [upgradable from: 1.1.1d]
termux-tools/stable 0.72 all [upgradable from: 0.71]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.78-perf+ #1 SMP PREEMPT Wed May 15 11:13:29 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.1.0
Device manufacturer:
Xiaomi
Device model:
MI PAD 4

```

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
Just tried it - started within 5 seconds. Completely normal.

**Comment by xeffyr** [comment]
I also should note that slowdown is caused by way how Bionic libc handles memory. There a lot of `madvise()` calls but this can't be fixed because managed by system component.

**Comment by yunfan** [comment]
@xeffyr so this were caused by the system optimization?

**Comment by yunfan** [comment]
also python shell works very well

**Comment by xeffyr** [comment]
> so this were caused by the system optimization?

This isn't related to optimization. Just how OS components are working. Android isn't Linux, even though it is running Linux kernel.

Issue may also point on hardware issues...

**Comment by yunfan** [comment]
@xeffyr  but since there were no others report this issue, i was wondering if that might caused by OS for save batterylife purpose. since we chinese android echosystem has too many apps that will runs on background and drain the battery

but also need to notify that in the same time, python console works well . that's quite strange. why nodejs invoked so many madvise?

**Comment by xeffyr** [comment]
> i was wondering if that might caused by OS for save batterylife purpose.

Nothing to do here with battery optimizations.

> notify that in the same time, python console works well

Do not compare python and nodejs. Their implementation is different - interpreter vs jit compiler.

> why nodejs invoked so many madvise?

To instruct kernel about expected usage of allocated memory regions.

**Comment by xeffyr** [comment]
I'm permanently closing this issue as there nothing can be done on Termux side.
