### ISSUE TITLE
Setoolkit not starting in termux

### ISSUE THREAD

**Issue by kterm** [termux/termux-packages#4425]
Setoolkit not starting it just give following output
```$ setoolkit
[-] New set.config.py file generated on: 2019-10-15 10:02:29.031590
[-] Verifying configuration update...
[*] Update verified, config timestamp is: 2019-10-15 10:02:29.031590
[*] SET is using the new config, no need to restart

 The Social-Engineer Toolkit (SET) - by David Kennedy (ReL1K)

 Not running as root.

Exiting the Social-Engineer Toolkit (SET).



 Thank you for shopping with the Social-Engineer Toolkit.

 Hack the Gibso```

**Comment by Grimler91** [comment]
Probably exited because you are not running as root. 

Closing as setoolkit isn't a termux package, and I can't see any error that seem to be termux specific in your output

**Comment by xeffyr** [comment]
@Grimler91 Setoolkit is in unstable-repo, but getting it even 50% working in Termux isn't possible. Just no portability. That however problem of most programs for related topic.

**Comment by kterm** [comment]
O ' it means , I am not lucky.
