### ISSUE TITLE
GNU Parallel not working

### ISSUE THREAD

**Issue by forresthopkinsa** [termux/termux-packages#4429]
**Problem description**
GNU Parallel doesn't seem to work at all. I can't say if it used to or not, this is my first attempt.

**Steps to reproduce**
```
$ ls
a  b  c
$ parallel echo {} ::: *
Can't use string ("1") as a HASH ref while "strict refs" in use at /data/data/com.termux/files/usr/bin/parallel line 7210.
```

**Expected behavior**
```
$ ls
a  b  c
$ parallel echo {} ::: *
a
b
c
```

**Additional information**
```
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.14.83-perf+ #1 SMP PREEMPT Wed Aug 28 17:21:39 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
OnePlus
Device model:
GM1917
```

```
$ parallel --version
GNU parallel 20190922
Copyright (C) 2007-2019 Ole Tange and Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: http://www.gnu.org/software/parallel

When using programs that use GNU Parallel to process data for publication
please cite as described in 'parallel --citation'.
```

**Comment by Fernal73** [comment]
Same issue:

I tried to run the following command as per the parallel tutorial at 
https://zenodo.org/record/1146014#.Xaqmnx5X40M:

seq 5 | parallel seq {} '>' example.{}

and receive the following message:

Can't use string ("1") as a HASH ref while "strict refs" in use at /data/data/com.termux/files/usr/bin/parallel line 7210.

**Comment by Grimler91** [comment]
Related: https://stackoverflow.com/questions/22517768/parallel-reading-of-input-file-with-parallelloops-module

**Comment by Fernal73** [comment]
@Grimler91 I haven't gone through your link as yet thoroughly but the above tutorial works as expected for Arch Linux on Termux.

**Comment by xeffyr** [comment]
@Fernal73 Version 2019**09**22 works fine on Arch. Problem is Termux specific and probably lives somewhere in perl package.

**Comment by Fernal73** [comment]
I'm unable to verify that version on Arch Linux. Do you know the mirror on
which that version is available?

**Comment by xeffyr** [comment]
I built it myself. Just `./configure --prefix=/tmp/parallel && make && make install` then running it from `/tmp/parallel/bin/`.

**Comment by Fernal73** [comment]
Ah. That's not something I want to do. Thanks for the update.

**Comment by Fernal73** [comment]
I do use gnu parallel but not your package on Termyx. It's used on Arch
Linux on Termux which has a different installation of Perl and Gnu Parallel.
I used it to run my build, static analysis and test scripts faster on my
phone.

https://github.com/Fernal73/LearnJava?files=1

Check the build scripts ending with 'all'.

Thanks for your help.

**Comment by ole-tange** [comment]
I tested the workaround on my phone: It works.

So disable the 'use strict;' in line 32 and everything should work.

**Comment by Fernal73** [comment]
What line 32 are you referring to?
In the Perl installation on Termux?
I'm inclined to wait for the next minor version than alter anything on my
installation.

**Comment by ole-tange** [comment]
'use strict;' is used to punish me if I write bad code style.

It is rarely updated when a new Perl version comes out, but it looks as if it as been updated in 5.30 for Termux. And right now I cannot see what the bad style is in line 7210, so that is why I need to be able to reproduce the error on a non-android system.

If you prefer waiting, it is up to you. But at least you now know a simple workaround.

**Comment by ole-tange** [comment]
Oh, the line 32 is 'use strict;' in the file: /data/data/com.termux/files/usr/bin/parallel

**Comment by Fernal73** [comment]
Thanks. That worked. I'm not familiar with Perl.

**Comment by forresthopkinsa** [comment]
> And now that I have your attention: I am really curious what you are using GNU Parallel for in Termux. So far I have seen it as "we have GNU Parallel in Termux just because we can", but I have the feeling you actually _use_ it for something. Will you be willing to tell us, what you use it for?

I have a Oneplus 7 Pro, which is capable of recording drop-dead-gorgeous 4k/60fps video, which I've gotten into the habit of using for everything.

Problem is, 4k60fps video takes a *lot of space*, which maxes out my Google Photos storage pretty much instantly.

I'm trying to use Tasker+Termux to:

1. Watch for new files in the Camera folder
2. Use ffprobe to see if they're 4k
3. Move 4k videos to a non-backed-up directory
4. Use ffmpeg to make a downscaled (1080p/24fps) copy
5. Put the 1080p version in the backed-up Camera folder
6. Once on wifi, upload the 4k file to private server

Weird use case, I know. But I'm pretty used to using Parallel for scripting, and it's particularly useful when running operations on a ton of files at once.

**Comment by ole-tange** [comment]
Found the problem.
```
sub sct_android($) {
    # Returns:                                                                                                        
    #   { 'sockets' => #sockets                                                                                       
    #     'cores' => #cores                                                                                           
    #     'threads' => #threads                                                                                       
    #     'active' => #taskset_threads }                                                                              
    # Use GNU/Linux                                                                                                   
    return sct_gnu_linux(@_);
}
```
Should be:
```
sub sct_android($) {
    # Returns:                                                                                                        
    #   { 'sockets' => #sockets                                                                                       
    #     'cores' => #cores                                                                                           
    #     'threads' => #threads                                                                                       
    #     'active' => #taskset_threads }                                                                              
    # Use GNU/Linux                                                                                                   
    return sct_gnu_linux($_[0]);
}
```

It will be part of version 20191122.

Thanks for finding the bug.

**Comment by Fernal73** [comment]
Great. Thanks, Ole! Now we can all sleep well knowing that all is well with GNU Parallel!

**Comment by Fernal73** [comment]
@ole-tange @Grimler91 @xeffyr

Are you aware that the semaphore and mutex examples from the tutorial don't work on Termux?

**Comment by Fernal73** [comment]
https://www.npmjs.com/package/parallelshell

There's also this nodejs command line version of gnu parallel which is not as advanced.

**Comment by ole-tange** [comment]
> @ole-tange @Grimler91 @xeffyr
> 
> Are you aware that the semaphore and mutex examples from the tutorial don't work on Termux?

https://savannah.gnu.org/bugs/?57160
