### ISSUE TITLE
gst-plugins-bad: compiled without OpenSL ES support

### ISSUE THREAD

**Issue by isjerryxiao** [termux/termux-packages#4430]
**Problem description**
Unable to use `openslessink` to play audio on Android devices.  
The sink is missing bacause `--disable-android_media` flag is added while configuring gst-plugins-bad.

**Steps to reproduce**
Install gstreamer and gst-plugins-bad.  
Run `gst-inspect-1.0`.  

**Expected behavior**
`openslessink` should be present.  
I did a rebuild for gst-plugins-bad with `--disable-android_media` removed, and `openslessink` is functional again.

**Comment by isjerryxiao** [comment]
It seems that `gstandroidmedia` plugin is not working properly.
```0:00:00.382832657 20078   0x709202f200 ERROR                default gstjniutils.c:564:load_java_module: Could not find 'JNI_CreateJavaVM' in '(NULL)': 'JNI_Cr
eateJavaVM': undefined symbol: JNI_CreateJavaVM
0:00:00.382879896 20078   0x709202f200 ERROR                default gstjniutils.c:583:load_java_module: Failed to locate required JNI symbols in '(NULL)': 'JN
I_GetCreatedJavaVMs': undefined symbol: JNI_GetCreatedJavaVMs
0:00:00.383165990 20078   0x709202f200 ERROR                default gstjniutils.c:577:load_java_module: Failed to load Java module 'libdvm': dlopen failed: li
brary "libdvm.so" not found
0:00:00.383188125 20078   0x709202f200 WARN      GST_PLUGIN_LOADING gstplugin.c:528:GstPlugin *gst_plugin_register_func(GstPlugin *, const GstPluginDesc *, gpointer): plugin "/data/data/com.termux/files/usr/lib/gstreamer-1.0/libgstandroidmedia.so" failed to initialise
```
Maybe `--disable-android_media` and `--enable-opensles` is better.

**Comment by xeffyr** [comment]
> gstandroidmedia plugin is not working properly.

It doesn't work properly because is designed to be used via JNI inside Android application and not via Termux environment. That also a reason why it was disabled.
