### ISSUE TITLE
Polipo

### ISSUE THREAD

**Issue by debian44** [termux/termux-packages#4431]
**Package description**
"Polipo is a small and fast caching web proxy" its discontinued but still works better than Privoxy and etc.

**Link to home page and sources**
1. Home page: https://www.irif.fr/~jch/software/polipo/
2. Source code: https://github.com/jech/polipo

**Additional information**
Have you compiled or tried to compile the package on device?
Too lazy for this

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install polipo
```
