### ISSUE TITLE
I start apachectl on Termux and it said Address already in use: AH00072 (but i not do anything!) How can i fix this?

### ISSUE THREAD

**Issue by ReDCeNTipeDe** [termux/termux-packages#4437]
![Screenshot_20191018_172739](https://user-images.githubusercontent.com/43487032/67087185-9c55c580-f1cc-11e9-89ef-f3ba70788232.png)

**Comment by xeffyr** [comment]
Check open ports with `netstat -tulpn`, then kill existing **httpd** instance.
If httpd is not running but port still in use, then... just configure apache to use a different port.
