### ISSUE TITLE
Busybox issue

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#4438]
Busybox is clearly installed but when I try to execute 'telnetd', it says:

The program 'telnetd' is not installed. Install it by executing:
 pkg install busybox

**Comment by xeffyr** [comment]
busybox is no longer provides applets separately except very few ones that don't have alternative in other packages.

Use `busybox telnetd` if you really need it. Note that it will enable *unauthorized* access to your device's shell for everyone on your network.
