### ISSUE TITLE
Telnetd issue

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#4439]
Whenever I try and use:
$ busybox telnetd

Htop says that the command is ran. But Nmap and the Telnet client says otherwise. The telnet port was never open.
Am I doing something wrong or is this a bug?

**Comment by xeffyr** [comment]
It uses port `8023`.

**Comment by IRISnoir** [comment]
$ busybox telnetd -p 8023

Doesn't work aswell

**Comment by IRISnoir** [comment]
Wait
Nevermind

**Comment by IRISnoir** [comment]
Nmap -p1-65535

Reveals it
