### ISSUE TITLE
Package Request:gifski

### ISSUE THREAD

**Issue by Gokou-Ruri** [termux/termux-packages#4442]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:https://gif.ski/
2. Source code:https://github.com/ImageOptim/gifski

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install gifski
```
