### ISSUE TITLE
Package Request:cwebp/dwebp/webpmux/gif2webp

### ISSUE THREAD

**Issue by Gokou-Ruri** [termux/termux-packages#4443]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:https://developers.google.com/speed/webp/download
2. Source code:https://chromium.googlesource.com/webm/libwebp/
https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
Available as part of libwebp version 1.0.3-2 and higher.
