### ISSUE TITLE
Package Request:scrub

### ISSUE THREAD

**Issue by searler** [termux/termux-packages#4444]
**Package description**
Scrub iteratively writes patterns on files or disk devices to make retrieving the data more difficult. 

Combined with openssl, this provides a simple mechanism to store confidential data in termux

**Link to home page and sources**
1. Home page: http://manpages.ubuntu.com/manpages/bionic/man1/scrub.1.html
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
No

**Comment by moneer** [comment]
Additional info
Product info
answer_id
3463947
bc_url
https://support.google.com/chrome/answer/3463947
environment_hostname
https://support.google.com
external_name
chrome
hc
chrome
hostname
support.google.com
internal_ip
false
experiments
10800170,10800177,10800236,10800243,10800244,10800247,10800112
page_type
1
user_logged_in
false
environment
PROD
client
helpcenter
Browser info
appCodeName
Mozilla
appName
Netscape
appVersion
5.0 (X11; U; U; Linux x86_64; ar-sa) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36 Puffin/7.8.0.40457AP
cookieEnabled
true
onLine
true
platform
Linux x86_64
userAgent
Mozilla/5.0 (X11; U; U; Linux x86_64; ar-sa) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36 Puffin/7.8.0.40457AP
javaEnabled
false
pluginNames
Shockwave Flash
Page info
URL
https://support.google.com/chrome/answer/3463947#lock
Page structure
<HTML class="hcfe"> <HEAD> </HEAD> <BODY class="mobile"> <DIV class="content-background"> </DIV> <DIV class="hcfe"> <HEADER> <DIV class="gaiabar material-bar"> <HEADER id="gb" class="gb_ja gb_Oa gb_me gb_ld gb_cc gb_md"> <DIV class="gb_Ed"> <DIV class="gb_7b gb_5b gb_cc"> </DIV> </DIV> <DIV class="gb_kd gb_Ad"> <DIV class="gb_qc gb_wc gb_xc"> <DIV class="gb_Zb"> <svg> <path> </path> </svg> </DIV> <DIV class="gb_Zb gb_2b gb_va"> </DIV> <DIV class="gb_Zb gb_3b gb_va"> </DIV> <DIV class="gb_Sb gb_va"> </DIV> <DIV class="gb_qc gb_va gb_uc gb_vc"> </DIV> </DIV> <DIV class="gb_qc gb_vd gb_je gb_de gb_ge"> <DIV class="gb_Wd gb_Vd"> <DIV id="material-bar-custom-product-name" class="gb_2d gb_1d"> <A> </A> </DIV> </DIV> <DIV class="gb_be"> <FORM id="search-form" class="gb_ne"> <BUTTON class="gb_Te"> </BUTTON> <DIV class="gb_Ze"> <INPUT class="gb_Ie"> </INPUT> </DIV> <BUTTON class="gb_Ue"> </BUTTON> <BUTTON class="gb_Re"> <svg> <path> </path> <path> </path> </svg> </BUTTON> </FORM> </DIV> <DIV class="gb_Xd gb_Vd"> </DIV> </DIV> <DIV class="gb_rc gb_Ia gb_qc"> <DIV class="gb_sc"> <DIV class="gb_ic one-bar-widgets-container"> <DIV id="gbwa" class="gb_w gb_Lc gb_f gb_ef"> <DIV class="gb_df"> <A class="gb_x"> <svg class="gb_pe"> <path> </path> </svg> </A> <DIV class="gb_Ra"> </DIV> <DIV class="gb_Qa"> </DIV> </DIV> </DIV> </DIV> <A class="gb_1 gb_2 gb_Hd gb_jb"> </A> </DIV> <DIV> </DIV> </DIV> </DIV> <DIV class="gb_td gb_Ad"> </DIV> </HEADER> <DIV class="gb_nd"> </DIV> </DIV> <SCRIPT> </SCRIPT> <DIV> <DIV class="gb_id"> </DIV> </DIV> <SCRIPT> </SCRIPT> <DIV class="feedback-dialog material-dialog"> </DIV> <DIV> <DIV class="appbar-container"> <DIV class="appbar"> <DIV class="appbar-internal"> <DIV class="appbar-helpcenter-sections"> <A class="appbar-helpcenter-sections__link appbar-helpcenter-sections--helpcenter appbar-helpcenter-sections--active"> </A> <A class="appbar-helpcenter-sections__link appbar-helpcenter-sections--community"> </A> <A class="appbar-helpcenter-sections__link appbar-helpcenter-sections--announcements"> </A> </DIV> <DIV class="appbar-links"> <SPAN class="appbar-icon appbar-link-container"> <A class="product-icon"> <SPAN> </SPAN> <svg> <path> </path> </svg> </A> </SPAN> </DIV> </DIV> </DIV> </DIV> </DIV> </HEADER> <DIV class="hcfe-content"> <SECTION class="primary-container"> <DIV class="page-width-container"> <DIV class="main-content"> <ARTICLE class="page"> <SECTION class="article-container"> <H1> </H1> <DIV class="cc"> <P> </P> <P> </P> <P> </P> <UL> <LI> </LI> <LI> </LI> <LI> </LI> <LI> </LI> <LI> </LI> </UL> <P> <A> </A> </P> <H2> </H2> <OL> <LI> </LI> <LI> </LI> <LI> <IMG> </IMG> </LI> <LI> <IMG> </IMG> </LI> <LI> <IMG> </IMG> <IMG> </IMG> </LI> </OL> <H2> </H2> <P> </P> <DIV class="zippy-wrapper"> <DIV class="zippy-container"> <A class="zippy index1 goog-zippy-expanded"> </A> </DIV> <DIV class="zippy-overflow"> <DIV class="zippy-content"> <OL> <LI> <IMG> </IMG> </LI> <LI> <STRONG> </STRONG> </LI> <LI> <IMG> </IMG> </LI> </OL> </DIV> </DIV> </DIV> <DIV class="zippy-wrapper"> <DIV class="zippy-container zippy-last"> <A class="zippy index2 goog-zippy-expanded"> </A> </DIV> <DIV class="zippy-overflow"> <DIV class="zippy-content"> <P> </P> <OL> <LI> </LI> <LI> </LI> <LI> <STRONG> </STRONG> </LI> </OL> <P> </P> <P> </P> </DIV> </DIV> </DIV> </DIV> </SECTION> <DIV class="sub-article-container shaded"> <DIV class="article-survey-container"> <DIV class="as"> <DIV class="title"> </DIV> <DIV class="how-improve"> </DIV> <DIV class="button-group"> <BUTTON class="as-button"> </BUTTON> <BUTTON class="as-button"> </BUTTON> </DIV> <FORM> </FORM> </DIV> </DIV> </DIV> </ARTICLE> </DIV> <SCRIPT> </SCRIPT> <DIV class="side-container"> <DIV> </DIV> <DIV class="fixed-sidebar-container"> <DIV class="primary-nav"> <NAV> </NAV> </DIV> <DIV class="promotion-container"> <DIV id="promotion-yt_promo" class="promotion"> <DIV class="promotion-image"> <A> <IMG> </IMG> </A> </DIV> <DIV class="promotion-body"> <A class="promotion-title"> </A> <P class="promotion-text"> <A> </A> </P> </DIV> </DIV> </DIV> </DIV> </DIV> </DIV> </SECTION> <FOOTER> <DIV class="footer-links"> <DIV> <UL> <LI> </LI> <LI> <A> </A> </LI> <LI> <A> </A> </LI> </UL> <FORM class="language-selector"> <SELECT class="language-selector-select"> </SELECT> <DIV class="language-selector-select sc-select"> <SPAN> </SPAN> <svg> <path> </path> </svg> <OL> </OL> </DIV> </FORM> </DIV> <DIV class="footer-links-right-container"> <BUTTON class="dark-mode-toggle"> <svg class="dark-mode-toggle-icon"> <path> </path> <path> </path> </svg> </BUTTON> <A class="user-feedback-link"> <svg class="user-feedback-link__svg-container"> <path> </path> <path> </path> </svg> </A> </DIV> </DIV> </FOOTER> </DIV> </DIV> <TEXTAREA class="csi"> </TEXTAREA> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <DIV> </DIV> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <DIV class="navigation-drawer-backdrop"> <DIV class="navigation-drawer"> </DIV> </DIV> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <DIV> </DIV> <DIV> </DIV> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <DIV class="gstl_50 sbdd_a"> </DIV> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <DIV class="material-dialog-backdrop"> </DIV> <DIV class="material-menu-backdrop"> </DIV> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <DIV id="chat-support-roster"> </DIV> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <SCRIPT> </SCRIPT> <DIV class="gb_Ne"> </DIV> <DIV class="gb_Pe"> </DIV> <DIV class="gb_Oe"> </DIV> <DIV class="gb_1b"> </DIV> <IFRAME id="apiproxy5421c1048d0204eb5594655b2fc37c99c68136fe0.3728939575"> </IFRAME> <IFRAME id="oauth2relay725277565"> </IFRAME> <SCRIPT> </SCRIPT> </BODY> </HTML>

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install scrub
```
