### ISSUE TITLE
emacs 26.3 won't load

### ISSUE THREAD

**Issue by jimerickson** [termux/termux-packages#4445]
i am using emacs 26.3 on twm in termux. when i attempt to start emacs from the menu i get nothing, but checking top shows it is running. when called from the command line it loads a lot of stuff but hangs forever at :

Loading /data/data/com.termux/files/usr/share/emacs/26.3/lisp/emacs-lisp/site-init.el (source)...done

what exactly am i doing wrong?  i am happy to submit any requested logs. thanks for all your work on this app!!

**Comment by xeffyr** [comment]
It was already reported in https://github.com/termux/x11-packages/issues/153.
No solution currently.
