### ISSUE TITLE
Request: Update Zeronet to Python3

### ISSUE THREAD

**Issue by japzone1** [termux/termux-packages#4447]
**Package description**
Can the zeronet package in the unstable repo be updated to the new python3 version(0.7.x), or at least have a separate python3 package added? The python2 version is legacy software now and doesn't get new feature updates.

**Link to home page and sources**
1. Home page: https://zeronet.io/
2. Source code: https://github.com/HelloZeroNet/ZeroNet/tree/py3

**Additional information**
I've verified that the python3 version does run in Termux, though I used a tweaked version of [this script](https://github.com/Merith-TK/Termux-ZeroNet/blob/master/zn.sh) and ended up in dependency hell.

**Comment by xeffyr** [comment]
Answered in https://github.com/termux/unstable-packages/issues/134#issuecomment-544555911.

**Comment by xeffyr** [comment]
ZeroNet is now updated to 0.7.1.
