### ISSUE TITLE
curl is not working 

### ISSUE THREAD

**Issue by nichu8** [termux/termux-packages#4449]
when i am trying to install apk mod, i got an error, @Hax4us they told it because curl is not working
[error ](https://github.com/Hax4us/Apkmod/issues/14#issuecomment-544799347)

**Comment by Hax4us** [comment]
give some details to investigate it 
1. output of `termux-info`
2. Try to download any file with curl and give output here , for instance you can just paste this command `curl  --trace-ascii dump.txt -LO http://dl-cdn.alpinelinux.org/alpine/v3.10/releases/aarch64/alpine-minirootfs-3.10.3-aarch64.tar.gz`
3. `cat dump.txt | grep Info`
Screenshots would be better.

**Comment by nichu8** [comment]
termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.9.148 #1 SMP PREEMPT Thu Jul 25 15:05:56 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
HUAWEI
Device model:
INE-LX1
$ curl --trace-ascii dump.txt -LO http://dl-cdn.alpinelinux.org/alpine/v3.10/releases/aarch64/alpine-minirootfs-3.10.3-aarch64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:-  0     0    0     0    0     0      0      0 --:--:-- --:-  1 2563k    1 37324    0     0  31207      0  0:01:24  0:0 12 2563k   12  332k    0     0   150k      0  0:00:16  0:0 29 2563k   29  763k    0     0   238k      0  0:00:10  0:0 39 2563k   39 1002k    0     0   217k      0  0:00:11  0:0 47 2563k   47 1219k    0     0   234k      0  0:00:10  0:0 61 2563k   61 1569k    0     0   253k      0  0:00:10  0:0 75 2563k   75 1930k    0     0   268k      0  0:00:09  0:0 88 2563k   88 2274k    0     0   277k      0  0:00:09  0:0100 2563k  100 2563k    0     0   278k      0  0:00:09  0:0100 2563k  100 2563k    0     0   278k      0  0:00:09  0:00:09 --:--:--  335k
$ cat dump.txt | grep Info
== Info:   Trying 151.101.8.249:80...
== Info: TCP_NODELAY set
== Info: Connected to dl-cdn.alpinelinux.org (151.101.8.249) port 80 (#0)
== Info: Mark bundle as not supporting multiuse
== Info: Connection #0 to host dl-cdn.alpinelinux.org left intact
$

**Comment by nichu8** [comment]
@Hax4us


termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.9.148 #1 SMP PREEMPT Thu Jul 25 15:05:56 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
HUAWEI
Device model:
INE-LX1
$ curl --trace-ascii dump.txt -LO http://dl-cdn.alpinelinux.org/alpine/v3.10/releases/aarch64/alpine-minirootfs-3.10.3-aarch64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:-  0     0    0     0    0     0      0      0 --:--:-- --:-  1 2563k    1 37324    0     0  31207      0  0:01:24  0:0 12 2563k   12  332k    0     0   150k      0  0:00:16  0:0 29 2563k   29  763k    0     0   238k      0  0:00:10  0:0 39 2563k   39 1002k    0     0   217k      0  0:00:11  0:0 47 2563k   47 1219k    0     0   234k      0  0:00:10  0:0 61 2563k   61 1569k    0     0   253k      0  0:00:10  0:0 75 2563k   75 1930k    0     0   268k      0  0:00:09  0:0 88 2563k   88 2274k    0     0   277k      0  0:00:09  0:0100 2563k  100 2563k    0     0   278k      0  0:00:09  0:0100 2563k  100 2563k    0     0   278k      0  0:00:09  0:00:09 --:--:--  335k
$ cat dump.txt | grep Info
== Info:   Trying 151.101.8.249:80...
== Info: TCP_NODELAY set
== Info: Connected to dl-cdn.alpinelinux.org (151.101.8.249) port 80 (#0)
== Info: Mark bundle as not supporting multiuse
== Info: Connection #0 to host dl-cdn.alpinelinux.org left intact
$

**Comment by Hax4us** [comment]
It's working and maybe your problem was the network issue , can be closed now
