### ISSUE TITLE
Package Request: dwarves

### ISSUE THREAD

**Issue by gappleto97** [termux/termux-packages#4451]
**Package description**
This package lets you analyze ELF binaries, which could assist in debugging programs for Termux. In particular, pahole lets you look at the packing of C structs and C++ classes.

**Link to home page and sources**
1. Home page: Unknown
2. Source code: https://git.kernel.org/pub/scm/devel/pahole/pahole.git/

**Additional information**
Have you compiled or tried to compile the package on device?

Yes. It didn't work because it was missing some dwarf libraries. Specifically it could not find:

* the `dwarf` include dir
* the `libdw` include dir
* the `libebl` library
* the `libdw` library

**Comment by kamalaraja38** [comment]
PKg update plaz

**Comment by xtkoba** [comment]
They are provided by the `libdw` package. Other dependencies seem to be `argp`, `zlib` and <a href="https://github.com/termux/termux-packages/tree/master/packages/libelf/obstack.h">`obstack`</a>.
