### ISSUE TITLE
Error while installing R packages like testthat 

### ISSUE THREAD

**Issue by Shyamniper** [termux/termux-packages#4453]
**Problem description**
I am encountering error while installing package like 'testthat', 'ggplot2' 

byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/jsonlite/libs/jsonlite.so':
  dlopen failed: library "libicuuc.so.64" not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘gh’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/gh’
**Steps to reproduce**
I have tried uninstalling and reinstalling R along with the packages error occurred for few packages not all. 

**Additional information**
~ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://its-pointless.github.io/files termux/extras
https://its-pointless.github.io/files termux/extras
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.31-perf-g9e0bf5d #1 SMP PREEMPT Thu Jun 13 21:08:04 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.1.1
Device manufacturer:
Xiaomi
Device model:

Let me know if you want me to provide more information I will be happy to do that.

**Comment by its-pointless** [comment]
This issue belongs on https://github.com/its-pointless/gcc_termux
