### ISSUE TITLE
Tshark problem

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#4458]
After upgrading Tshark, I immediately activate it. And unfortunately it says this:

Fri Oct 25-22:28:01@localhost-u0_a201~:$tsudo tshark --color -VPxgWn2 -d tcp.port==1:65535,http -w sniff
Running as user "root" and group "root". This could be dangerous.
Capturing on 'wlan0'
tshark: The file to which the capture would be saved ("sniff") could not be opened: Permission denied.

0 packets captured

Here is my termux-info:
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.72 #1 SMP PREEMPT Tue Feb 16 18:23:49 CST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.1
Device manufacturer:
Lenovo
Device model:
Lenovo TB3-710I

**Comment by xeffyr** [comment]
1. Make sure tshark is executed as **root**.

2. Make sure that your SELinux is set to permissive.

**Comment by IRISnoir** [comment]
I have execited tshark as root

But how do I check SELinux

**Comment by IRISnoir** [comment]
I fulfilled those conditions, yet Tshark refuses to start for whatever reason...

Sat Oct 26-06:15:02@localhost-u0_a201~:$su
root@TB3-710I:/data/data/com.termux/files/home # getenforce
Enforcing
root@TB3-710I:/data/data/com.termux/files/home # setenforce 0
root@TB3-710I:/data/data/com.termux/files/home # getenforce
Permissive

Sat Oct 26-06:18:51@localhost-u0_a201~:$tsudo tshark --color -VPxgWn2 -d tcp.port==1:65535,http -w sniff
Running as user "root" and group "root". This could be dangerous.
Capturing on 'wlan0'
tshark: The file to which the capture would be saved ("sniff") could not be opened: Permission denied.

0 packets captured

**Comment by xeffyr** [comment]
You didn't executed it as root.... okay.
Re-read the post at https://github.com/termux/termux-packages/issues/4458#issuecomment-546418447 and try until it will work.

**Comment by xeffyr** [comment]
Either try another file name or save file on /sdcard.
Error quite strange though...

**Comment by IRISnoir** [comment]
Still to no avail:

Sat Oct 26-10:27:30@localhost-u0_a201~:$tsudo tshark --color -VPxgWn2 -d tcp.port==1:65535,http -w nose
Running as user "root" and group "root". This could be dangerous.
Capturing on 'wlan0'
tshark: The file to which the capture would be saved ("nose") could not be opened: Permission denied.

0 packets captured

Sat Oct 26-10:37:22@localhost-u0_a201~:$tsudo tshark --color -VPxgWn2 -d tcp.port==1:65535,http -w /sdcard/nose
Running as user "root" and group "root". This could be dangerous.
Capturing on 'wlan0'
tshark: The file to which the capture would be saved ("/sdcard/nose") could not be opened: Permission denied.

0 packets captured

**Comment by IRISnoir** [comment]
Usually, the system would let tsudo off the hook with the permission denied error, but this is not the case.

**Comment by IRISnoir** [comment]
Hello? Is this error being fixed?

**Comment by Grimler91** [comment]
@IRISnoir No, seems to be specific to your device so I am not sure what to fix, try installing another ROM
