### ISSUE TITLE
Mpv cannot running after update

### ISSUE THREAD

**Issue by kcubeterm** [termux/termux-packages#4461]
It gives following output:

$ mpv
CANNOT LINK EXECUTABLE "mpv": cannot locate symbol "ucnv_open_60" referenced by "/system/lib64/libmedia.so"...

###Device info #####
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
Redmi 6 Pro

**Comment by xeffyr** [comment]
Your "device info" is not complete. You should include **everything** that is printed by `termux-info`.

**Comment by rendiix** [comment]
Confirmed
```console
┌─[rendiix@termux]─[●]─[✔]                                 [05:54 WIB]
├─[~]
│
└─[$]─● mpv
CANNOT LINK EXECUTABLE "mpv": cannot locate symbol "ucnv_open_58" refe
renced by "/system/lib64/libmedia.so"...
Aborted                                                               
┌─[rendiix@termux]─[●]─[✘]                                 [05:54 WIB]
├─[~]
│
└─[$]─● termux-info                                                   
Updatable packages:
All packages up to date
Subscribed repositories:                                              
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://rendiix.github.io android-tools/termux
https://rendiix.github.io android-tools/termux
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://termux.org/packages stable/main
System information:
Linux localhost 3.18.71-perf-ga01336f #1 SMP PREEMPT Thu Oct 10 00:31:
05 CST 2019 aarch64 Android                                           
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
Xiaomi
Device model:
MI 5s
```

**Comment by its-pointless** [comment]
Way to solve this might be to build ffmpeg with --target-os=gnu instead of --target-os=android then rebuild mpv. That makes mpv link with libavutil.so.56 instead of libavutil.so. This would make it far less likely to get library name collisions in certain android systems.

**Comment by its-pointless** [comment]
try:
 `unset LD_LIBRARY_PATH`
then execute mpv

**Comment by kcubeterm** [comment]
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://termux.org/packages stable/main
System information:
Linux localhost 3.18.120-perf-gba834ca #1 SMP PREEMPT Thu Oct 10 18:25:27 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
Redmi 6 Pro
$

**Comment by kcubeterm** [comment]
After trying 

`unset LD_LIBRARY_PATH`
It's worked
Thanks  **its-pointless and xeffry**
