### ISSUE TITLE
End of android-5/6 support on 2020-01-01

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#4467]
Hi, 

Following discussion in the latest [development meeting](https://wiki.termux.com/wiki/Dev:Development_Session_42) it has been decided to drop android-5 support from 2020-01-01. 
From that date there will no longer be any updates to the package repositories' android-5 branches.
An android-5 branch has also been created for termux-app, and the latest tagged version of the app (0.76) requires android 7. 

Supporting the android-5 branches takes some time and effort from the maintainers. This time and effort would, arguably, be better spent making termux ready for android Q (and later). Some big changes are required to make termux usable for the latest android versions, as discussed in https://github.com/termux/termux-app/issues/1072. 

If you are using android 5 or android 6 on your device then the only way to continue to get updates after 2020-01-01 would be to upgrade to android 7 or newer (if possible).

See also the discussion in https://github.com/termux/termux-packages/issues/2874 from when we first separated the repos into an android-5 branch and a master branch.

**Comment by xeffyr** [comment]
I also should note that [unstable](https://github.com/termux/unstable-packages) and [x11](https://github.com/termux/x11-packages) will be disabled at this point and packages will not be downloadable for Android 5.

**Comment by xeffyr** [comment]
A to-do list of things that highly advisable to do before dropping Android 5 support completely:

- [ ] Fix https://github.com/termux/termux-packages/issues/4287
- [ ] Fix https://github.com/termux/termux-packages/issues/4189

**Comment by dickyharper** [comment]
Will I still be able to use youtube-dl and ffmpeg after 1.1.2020?  If no, is there any other way you recommend? Thanks. Best Wishes. 😶

**Comment by xeffyr** [comment]
> Will I still be able to use youtube-dl and ffmpeg after 1.1.2020? 

Will be able as soon as you have backup of `$PREFIX` with necessary things installed or `termux.net` is not down.

**Comment by dickyharper** [comment]
How do I get the backup myself?  Some course videos can only download with youtube-dl. 😓

**Comment by xeffyr** [comment]
```
cd $PREFIX/../
tar zcvf /sdcard/termux-prefix.tar.gz usr
```

**Comment by zorro** [comment]
What will happen to the android-5 branch? Will it be archived or completely removed?

**Comment by xeffyr** [comment]
Branch will be available but packages may not.

**Comment by samoht0** [comment]
Wound be fine to remove those bintray.com/grimler/ repos from android-5 official repo list before EOS. They aren't used anyway.

Why isn't there a **stable option** to continue providing bootstrap and android-5 **main** repo? Maybe on bintray, if hosting using termux.net is an issue?

**Comment by xeffyr** [comment]
> if hosting using termux.net is an issue?

Nowhere was mentioned that hosting of `termux.net` is an issue. But support apparently it is.
Android 5 is old and I don't want to keep device on this OS version *just for testing packages*.

**Comment by xeffyr** [comment]
> Consistent statement considering the two others?

Statement is consistent enough.

X11 and unstable repositories are not related to `termux.net` even though they provide packages for legacy Android. Removing them does not affect `termux.net` and they are not necessary for main Termux functionality. 

These packages are hosted on **my** (non Termux org) account in order to make all resources available to main repo which is essential. Removing the X11 & unstable for legacy Android will be necessary to have stable hosting of these ones for Android 7+ and have room for some new packages.

For those who disagree with that, I will provide APT repository archives via https://archive.org/.

Sources will not disappear and will be available. Those who want to continue support Android 5 can use them and keep up to date. Though, last 3000 commits tell that not so many people interested in supporting Android 5:

<details>
<summary>android-5 last 3000 commits stats (click to expand)</summary>
<pre>
1490	fredrik@fornwall.net
889	leonid.plyushch@gmail.com
248	henrik@grimler.se
93	tom.ty89@gmail.com
59	bored@goat.si
34	winsto003@hotmail.com
30	Henrik@Grimler.se
16	stephengroat@users.noreply.github.com
13	oli@glow.li
12	kevin@kevincotugno.com
11	bednarski.michal2@gmail.com
7	git@joakim.fea.st
6	alex@digriz.org.uk
6	henka20@hotmail.com
4	info@bitcoinprivacy.net
4	raghavsphadke@gmail.com
3	brandon.philips@coreos.com
3	cswl1337@gmail.com
3	j@ovvvo.co
3	kieran@coldron.com
3	repo@butta.fastem.com
3	sudosurootdev81@gmail.com
3	tom.ty89@outlook.com
2	17478432+TheBrokenRail@users.noreply.github.com
2	edward@edward-p.xyz
2	gdrbyko1@protonmail.com
2	github.snth@xoxy.net
2	hgrimler@kth.se
2	infectedx27@gmail.com
2	koro@kzxiv.net
2	laurent@spkdev.net
2	rafael@rafaelmartins.eng.br
2	stefan@sblbs.de
2	stephengroat@Stephens-MacBook-Pro.local
1	11911577+kenneth-Q@users.noreply.github.com
1	51031215+CarsonThompson@users.noreply.github.com
1	andy@onthewings.net
1	araczkowski@gmail.com
1	bigras.bruno@gmail.com
1	boundary.effect@gmail.com
1	connor24nolan@live.com
1	daniel.dob.obrien@gmail.com
1	davide@depau.eu
1	dextor@civ.zcu.cz
1	erlanger@please_use_issues
1	gary@garykim.dev
1	guillerobles1995@gmail.com
1	ImgBotHelp@gmail.com
1	infernix@gmail.com
1	its-pointless@users.noreply.github.com
1	Jason@zx2c4.com
1	jiri.tyr@gmail.com
1	karol@baraniecki.eu
1	karol@karcom.pl
1	kinke@users.noreply.github.com
1	landfillbaby@users.noreply.github.com
1	lkpandey950@gmail.com
1	lotheac@iki.fi
1	me@duncm.com
1	me@serl.it
1	mklein994@gmail.com
1	nonedisponibile@gmail.com
1	qbasic010@aim.com
1	ross@bluelightos.ddns.net
1	spaceboyross@yandex.com
1	surya@keyba.se
1	vbauer@yandex-team.ru
1	ysaxenax@gmail.com
1	zaomir@outlook.com
</pre>
</details>

> The second statement is related to, what?

It is an answer to https://github.com/termux/termux-packages/issues/4467#issuecomment-547782244.

> A clarification by Fredrik would help here greatly, I guess.

Yes, `termux.net` is hosted by @fornwall so clarification will be nice on this topic.

**Comment by alireza5830** [comment]
please release for android 5

**Comment by Leif-W** [comment]
A 5 year old OS has support dropped without notice, leaving Termux in a broken state of install/uninstall.  Really crappy decision and handling.  If Termux can't support users then I can't support Termux.  Time to get this garbage off my phone.

**Comment by xeffyr** [comment]
Last git versions for Termux and addons available for Android 5/6 devices:

* Termux app: https://api.cirrus-ci.com/v1/artifact/task/5594972685860864/output/app/build/outputs/apk/debug/app-debug.apk

* Termux api: https://api.cirrus-ci.com/v1/artifact/github/termux/termux-api/debug-build/output/app/build/outputs/apk/debug/app-debug.apk

* Termux styling: https://api.cirrus-ci.com/v1/artifact/github/termux/termux-styling/debug-build/output/app/build/outputs/apk/debug/app-debug.apk

**Comment by dickyharper** [comment]
> Last git versions for Termux and addons available for Android 5/6 devices:
> 
> Termux app: [termux-app.apk.gz](https://github.com/termux/termux-packages/files/3992561/termux-app.apk.gz)
> 
> API: [termux-api.apk.gz](https://github.com/termux/termux-packages/files/3992560/termux-api.apk.gz)
> 
> Boot: [termux-boot.apk.gz](https://github.com/termux/termux-packages/files/3992562/termux-boot.apk.gz)
> 
> Styling: [termux-styling.apk.gz](https://github.com/termux/termux-packages/files/3992563/termux-styling.apk.gz)
> 
> Task: [termux-task.apk.gz](https://github.com/termux/termux-packages/files/3992564/termux-task.apk.gz)
> 
> Widget: [termux-widget.apk.gz](https://github.com/termux/termux-packages/files/3992565/termux-widget.apk.gz)
> 
> `gunzip` downloaded APKs before installation.

Thank you.  I appreciate it.

**Comment by wbsch** [comment]
I got the "You are using legacy termux environment. Packages are unmaintained and will not receive any updates." message on an Android 8 phone with a Termux installation that goes a long way back and spans several older devices; that might influence the state it was in.

IMHO it would be helpful to add a note that running `termux-upgrade-repo` will fix this situation, or linking to a website with more info. I arrived here by searching for the text, then reading a Reddit thread that linked to this ticket. That process could certainly be improved :)

**Comment by xeffyr** [comment]
Since no further changes expected, I have created snapshot from the available repositories compatible with Android 5.x-6.x and uploaded to Internet Archive:
https://archive.org/details/termux-repositories-legacy

What is available:
* All latest git versions of Termux application and add-ons (debug builds): both apks and their sources.
* Archive of `termux.net` and supplementary repositories like `root-repo`, `x11-repo`, etc. Contains apt repositoriy dumps (ready to be deployed as mirror), build scripts and package source cache.
* Latest bootstrap archives.

Unlike `termux.net`, `x11` & `unstable` repos will not continue to be available and their packages can be obtained only from https://archive.org/download/termux-repositories-legacy/termux-repositories-legacy-24.12.2019.tar.

**Comment by hy-l** [comment]
Wait, `termux-upgrade-repo` will remove **everything**, won't it? If so, why can't I just clear all data and reopen the app/re-bootstrap? But I'd like to keep my data, is there a way please?

**Comment by xeffyr** [comment]
> why can't I just clear all data and reopen the app/re-bootstrap?

Because `termux-upgrade-repo` will clear only `$PREFIX` (where packages installed), i.e. data in $HOME will not be touched and will create reinstallation script.

**Comment by hy-l** [comment]
> > why can't I just clear all data and reopen the app/re-bootstrap?
> 
> Because `termux-upgrade-repo` will clear only `$PREFIX` (where packages installed), i.e. data in $HOME will not be touched and will create reinstallation script.

Oh, thank you! Actually I saw the `$PREFIX` variable in the script but mistakenly thought that HOME is in PREFIX (home in usr... lol), my bad...

**Comment by karstengit** [comment]
It's nice that the repos have been archived by xeffyr (https://github.com/termux/termux-packages/issues/4467#issuecomment-569526418)
but how can they be used now for Android 6.0 ???

**Comment by karstengit** [comment]
It is understandable and acceptable that "**Termux on devices with old Android OS without any updates and bugfixes.**" but **please let this older versions be installable and usable** !

**Comment by xeffyr** [comment]
> So this is unusable and Termux is dead for Android < 7.0

It works, error likely on your side. Make sure that your Android OS is not trying to install application on external storage and you didn't messed anything with root.

**Comment by xeffyr** [comment]
> but how can they be used now for Android 6.0 ???

To use repo archives you need to download (~7 GB) and extract them to directory where web server is running or you can install packages with `dpkg` manually.

**Comment by karstengit** [comment]
> It works, error likely on your side. Make sure that your Android OS is not trying to install application on external storage and you didn't messed anything with root.

The Termux-App has (only) 613 KB and the new one about 26 MB.
So i think that the bootstrap packages maybe included in the actual version but not in the last version for Android 6.

How can i manually install the bootstrap packages?

**Comment by karstengit** [comment]
> To use repo archives you need to download (~7 GB) and extract them to directory where web server is running or you can install packages with `dpkg` manually.

Sorry - that will not work!
After installing the Basic App and starting it there comes the message:
"Unable to install

Termux was unable to install the bootstrap packages.

Check your network connection and try again.

Abort        Try Again"

There is no chance to continue !?

**Comment by xeffyr** [comment]
> The Termux-App has (only) 613 KB and the new one about 63 MB.

Embedded bootstraps are not supported on Android 5. It downloads them from https://termux.net/bootstraps/new instead.

> There is no chance to continue !?

Depends on your device, network/isp, etc...

**Comment by karstengit** [comment]
> Depends on your device, network/isp, etc...

404 Not Found
nginx/1.14.0 (Ubuntu)

> > The Termux-App has (only) 613 KB and the new one about 63 MB.
> 
> Embedded bootstraps are not supported on Android 5. It downloads them from http://termux.net/bootstrap/new/ instead.
> 
> > There is no chance to continue !?
> 
> Depends on your device, network/isp, etc...

No - sorry - the sources are not existant any more:

**404 Not Found**
**nginx/1.14.0 (Ubuntu)**

**Comment by xeffyr** [comment]
Really ?
Are you sure that URL is https://termux.net/bootstrap/new/ ?

**Comment by karstengit** [comment]
> Really ?
> Are you sure that URL is https://termux.net/bootstrap/new/ ? I just checked, everything here.
...bootstrap exists but bootstrap**s** not ;-)

So what is the reason that the download fails?
I can only say that the internet connections works for every other app.

**Comment by xeffyr** [comment]
> So what is the reason that the download fails?

If you think your internet is ok (& not tampered), then only:

* Android forces app to be installed on external storage on some devices (known issue btw).
* You messed up permissions in /data/data/* and Android failed to recover them.

**Comment by xeffyr** [comment]
App uses correct URL, https://github.com/termux/termux-app/blob/android-5/app/src/main/java/com/termux/app/TermuxInstaller.java#L173. Last git versions for Android 5 (posted in https://github.com/termux/termux-packages/issues/4467#issuecomment-568266958) are tested and work well.

**Comment by karstengit** [comment]
I believe that the code is well and correct.

Hmm - can i extract the archive manually to the correct place?
The mobile is rooted.
/data/data/com.termux has only folders that are empty.

On the SD there seems no directorx for termux in /storage/.../Android/data

**Comment by xeffyr** [comment]
First go to android settings and check if application is installed to **internal storage**.

**Comment by karstengit** [comment]
> First go to android settings and check if application is installed to **internal storage**.
> 
> I.e. ensure that you are not running into:
> 
>     * [termux/termux-app#1023](https://github.com/termux/termux-app/issues/1023)
> 
>     * [termux/termux-app#761](https://github.com/termux/termux-app/issues/761)

It is installed internal with 4.71 MB.
I give manually access to the memory without success.

**Comment by xeffyr** [comment]
Last thing you can try is Termux app v0.79 with embedded bootstraps (git debug version).
https://linx.li/termux-v079-offline-bootstraps.apk

**Comment by karstengit** [comment]
O.K.
I deinstalled the App, downloaded and installed this one with offline bootstraps.
This one works!
Thank you for your time and help!

Google has really done everything to make the usage of Linux nearly unpossible in Android.

**Comment by karstengit** [comment]
I am trying to install https://github.com/EXALAB/AnLinux-App

Now i get the Error
E: The repository 'https://termux.net stable Release' does not have a Release file.

**Comment by xeffyr** [comment]
Something tampers your internet connection. For same reason it have failed to download bootstraps before.

Can you try to execute
```
curl -L http://termux.net/dists/stable/Release
```
\-  it should print text starting with
```
Codename: stable
Version: 1
Architectures: all arm i686 aarch64 x86_64
Description: Main repository
Suite: stable
Date: Mon, 23 Dec 2019 22:46:08 UTC
```

**Comment by karstengit** [comment]
Yes that works. Download works complete.

But there was an additional line after the Error message:
N: 'Updating from such a repository can't be done securely, and is therefore disabled by default.

This is the reason in this case!

**Comment by xeffyr** [comment]
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.

This is not a reason, `apt` just failed to download release file and verify it.

Few more things you can try:

* Edit `$PREFIX/etc/sources.list` and change `https` to `http`.
* Try VPN.

**Comment by karstengit** [comment]
I have edited /data/data/com.termux/files/usr/etc/apt/sources.list to http
Yes - that works! Thanks a lot!

The AnLinux install process could be started too.
But at least Termux seems to be all i need. 
Is there maybe an alternate way to get this direct running with root privileges?
I think i must have a closer look at https://github.com/termux/termux-root-packages
and https://proot-me.github.io/

Is it possible to connect over WLAN with an Linux-PC to an Termux-Shell?
When i use SSHelper i get remote an shell, but not within the Termux environment.

Besides - this is the Android running:
https://forum.xda-developers.com/galaxy-s5/development/rom-ane4-kitkat-4-4-2-multi-csc-t2813628
Maybe you have an idea what have been modified that causes the problems.
I can only say that this ROM is working good for all other cases of normal use with the S5.

**Comment by xeffyr** [comment]
> Is it possible to connect over WLAN with an Linux-PC to an Termux-Shell?

SSH or Telnet, pick what is the best for you.

**Comment by karstengit** [comment]
> > Is it possible to connect over WLAN with an Linux-PC to an Termux-Shell?
> 
> SSH or Telnet, pick what is the best for you.

So i have to install and configure an SSH-Server under Termux?

Where can i find some basic concepts ?
For example the use of X11 is not really clear.

**Comment by xeffyr** [comment]
> So i have to install and configure an SSH-Server under Termux?
Where can i find some basic concepts ?
For example the use of X11 is not really clear.

Why not to check Termux Wiki ?

> Unpack to an own Webserver and edit the path in sources.list to it. Correct?
But the bootstrap-archives cannot be used, because the URL in the APP is fix. Correct?

Both are correct.

**Comment by karstengit** [comment]
> > For example the use of X11 is not really clear.
> 
> Why not to check Termux Wiki ?

Found it now: https://wiki.termux.com/wiki/Graphical_Environment

**Comment by karstengit** [comment]
> > For example the use of X11 is not really clear.
> 
> Why not to check Termux Wiki ?

Found it now:
- https://wiki.termux.com/wiki/Graphical_Environment
- https://wiki.termux.com/wiki/Remote_Access#Using_the_SSH_server

It seems that the Wiki is not editable. So i can't add something.

**Comment by karstengit** [comment]
With the current installation "pkg install x11-repo" does not work.
How can this be added manually?
(I could get X11 running within Debian in AnLinux, but this cost really many internal Flash).

Can you tell me which script/executable is called by the main app to launch the Termux environment?

**Comment by Grimler91** [comment]
> It seems that the Wiki is not editable. So i can't add something.

You need to make an account first, we've had problems with spam.

> With the current installation "pkg install x11-repo" does not work.
> How can this be added manually?

Have a look at the previous x11-repo script and mimic what it did: https://github.com/termux/termux-packages/blob/f6e6addf36bd995e98d13733b8bc83ac9615b801/packages/x11-repo/build.sh#L12

> Can you tell me which script / executable is called by the main App to launch the Termux shell / environment ?

Not sure what you mean? `bash` is launched for a bash shell. 

> And a really wicked question: Is there an old version of Termux for Android 4 ?

No. Packages for android 4 is incompatible with android >= 5 (search the github issues for more information as this has been asked/requested many times)

**Comment by xeffyr** [comment]
> With the current installation "pkg install x11-repo" does not work.
How can this be added manually?

x11-repo is no longer available for Android 5/6. I provide only packages compiled for "current" Android API level, i.e. 24 or Android 7.0.

If want packages working on Android 5, get them from https://archive.org/download/termux-repositories-legacy/termux-repositories-legacy-24.12.2019.tar.

**Comment by karstengit** [comment]
> > Can you tell me which script / executable is called by the main App to launch the Termux shell / environment ?
> 
> Not sure what you mean? `bash` is launched for a bash shell.

Yes - the idea is that the Termux-App is (of course) calling the bash.
But how it is called that the environment of Termux can be used in the shell?
I am asking because this call can be done within an other bash.

> No. Packages for android 4 is incompatible with android >= 5 (search the github issues for more information as this has been asked/requested many times)

I didn't know if there is an backup of Termux for Android 4.0 too ?
That was the idea behind this question.

**Comment by xeffyr** [comment]
> I didn't know if there is an backup of Termux for Android 4.0 too ?

Termux packages never were compiled for Android 4.0. There a **much** more patches needed than for Android 5.

**Comment by karstengit** [comment]
> Linux has a system call `execve` which allows to execute binaries :)
> Termux is only calls it and then just redirects stdin/stdout/stderr. Basically how all terminal emulators work.

Yes - and what is called with what kind of parameters?


> Termux packages never were compiled for Android 4.0. There a **much** more patches needed than for Android 5.

O.K. Thanks for the info.

**Comment by xeffyr** [comment]
> how the bash is called with what kind of parameters?

Why not to just check the source code...

* https://github.com/termux/termux-packages/blob/3eeb70674681e484b207933e8a466bbedae67165/packages/termux-tools/login
* https://github.com/termux/termux-app/blob/90e6260d5e05211ec3e6dfeb9e6e631b56062281/app/src/main/java/com/termux/app/TermuxService.java#L282
* https://github.com/termux/termux-app/blob/90e6260d5e05211ec3e6dfeb9e6e631b56062281/app/src/main/java/com/termux/app/BackgroundJob.java#L134
* https://github.com/termux/termux-app/blob/90e6260d5e05211ec3e6dfeb9e6e631b56062281/terminal-emulator/src/main/java/com/termux/terminal/TerminalSession.java#L180
* https://github.com/termux/termux-app/blob/90e6260d5e05211ec3e6dfeb9e6e631b56062281/terminal-emulator/src/main/jni/termux.c#L25

And finally - http://man7.org/linux/man-pages/man2/execve.2.html.

**Comment by xeffyr** [comment]
I'm locking this issue due to much offtopic.
