### ISSUE TITLE
rc shell

### ISSUE THREAD

**Issue by v217** [termux/termux-packages#4469]
**Package description**
rc — A Shell for Plan 9 and UNIX Systems

**Link to home page and sources**
1. Home page:
https://packages.ubuntu.com/eoan/rc
http://manpages.ubuntu.com/manpages/eoan/en/man1/rc.1.html
http://static.tobold.org/rc/rc-duff.html
2. Source code:
https://github.com/rakitzis/rc

**Additional information**
I tried to install it with dpkg -i and did get an aarch64 arm64 mismatch error. I am not sure whether it's statically compiled with readline support.
Still the most usable shell in my opinion.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install rcshell
```
