### ISSUE TITLE
Can't include glib: 'glibconfig.h' file not found

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#447]
I am trying to test a glib function, because I suspect an error with the timezone function used by profanity.
In trying to test a simple test case I ran into issues with glib. 

I am trying to compile the following code with
```
clang test.c `pkg-config --cflags --libs glib-2.0`
```
test.c:
```
#include<stdio.h>
#include <glib.h>
main(){
        printf("Hello, World");
        /*the function I actually want to test:*/
        /*printf(g_time_zone_new_local());*/
}
```
But I am getting the following error:

```
In file included from test.c:3:
In file included from /data/data/com.termux/files/usr/include/glib-2.0/glib.h:30:
In file included from /data/data/com.termux/files/usr/include/glib-2.0/glib/galloca.h:32:
/data/data/com.termux/files/usr/include/glib-2.0/glib/gtypes.h:32:10: fatal error: 'glibconfig.h' file not found
#include <glibconfig.h>
         ^
1 error generated.
```
Searching for glibconfig.h, which normally should be there, yields no results.

**Comment by fornwall** [comment]
Thanks! Fixed in `2.48.2-1` of the `glib-dev` package, to which one can now update with `apt update && apt upgrade`.
