### ISSUE TITLE
No file in directory

### ISSUE THREAD

**Issue by irman1989** [termux/termux-packages#4472]
What heaven this
Command : termux-setup-storage
$  cd/sdcard/emulated/0
bash: cd/sdcard/emulated/0: No such file or directory
This info termux
1.
![Screenshot_2019-10-28-21-57-53-831_com termux](https://user-images.githubusercontent.com/57041244/67691088-96cc5c80-f9d0-11e9-9a58-5614714cf886.png)
2.
![Screenshot_2019-10-28-21-59-59-733_com termux](https://user-images.githubusercontent.com/57041244/67691183-bd8a9300-f9d0-11e9-804a-452a5263d09b.png)
3.
![Screenshot_2019-10-28-22-03-10-696_com termux](https://user-images.githubusercontent.com/57041244/67691348-02aec500-f9d1-11e9-954b-4476234ee45b.png)
![Screenshot_2019-10-28-22-03-36-773_com termux](https://user-images.githubusercontent.com/57041244/67691371-0d695a00-f9d1-11e9-97e2-19eac6b4e11c.png)
![Screenshot_2019-10-28-22-03-52-373_com termux](https://user-images.githubusercontent.com/57041244/67691387-135f3b00-f9d1-11e9-82b9-0564be362b4e.png)
![Screenshot_2019-10-28-22-04-12-315_com termux](https://user-images.githubusercontent.com/57041244/67691410-1f4afd00-f9d1-11e9-83ee-06223866d7d1.png)
Please help..what heaven in my termux...?

**Comment by xeffyr** [comment]
Why reposting https://github.com/termux/termux-packages/issues/4471 ???

Or you just can't see a difference between your command and one in https://github.com/termux/termux-packages/issues/4471#issuecomment-546991604 ?
