### ISSUE TITLE
/bin/hostname is executable but not executable

### ISSUE THREAD

**Issue by Keith-S-Thompson** [termux/termux-packages#4475]
**Problem description**
The test `[ -x /bin/hostname ]` indicates that it's executable, but executing it produces a `No such file or directory` error.

`hostname` isn't the only command affected, just the first one I ran into.

This problem occurs with Android 9, but not with Android 8.1.0 and earlier.

**Steps to reproduce**
Execute this script:
```
#!/bin/sh

ls -ld /bin
ls -l /bin/hostname
ls -l /bin/toybox

if [ -x /bin/hostname ] ; then
    echo '/bin/hostname is executable'
    echo 'executing /bin/hostname'
    /bin/hostname
    if [ $? -eq 0 ] ; then
        echo ok
    else
        echo FAILED
    fi
fi
```

**Expected behavior**
Either `/bin/hostname` is not executable or executing it is successful.

**Output of script**
```
lrw-r--r-- 1 root root 11 Dec 31  2008 /bin -> /system/bin
lrwxr-xr-x 1 root shell 6 Dec 31  2008 /bin/hostname -> toybox
-rwxr-xr-x 1 root shell 473848 Dec 31  2008 /bin/toybox
/bin/hostname is executable
executing /bin/hostname
./termux-bin-bug: 10: ./termux-bin-bug: /bin/hostname: not found
FAILED
```

**Additional information**
Post output of command `termux-info`.
```
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://termux.org/packages stable/main
System information:
Linux localhost 4.9.112-perf-16284547 #1 SMP PREEMPT Mon Aug 12 20:43:18 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-T290
```

**Comment by Grimler91** [comment]
This is an unfortunate side-effect of the preloaded library [termux-exec](https://wiki.termux.com/wiki/Termux-exec). 

To unload the library you can run `unset LD_PRELOAD; bash` and then `/bin/hostname` will work. 

A better solution would be to use the full path `system/bin/hostname` when executing it, or to create a symlink from `$PREFIX/bin/hostname` to `/system/bin/hostname` by running `ln -s /system/bin/hostname $PREFIX/bin/hostname`.
