### ISSUE TITLE
Npm uninstall error (electron)

### ISSUE THREAD

**Issue by H4ck3r404** [termux/termux-packages#4479]
I've tried installing Orca (which needs electron) on my terminal. Package was not installed as I expected. Problems starter when I've tried uninstalling it. `npm uninstall orca` shows me the same message as with `npm install`:

> electron@7.0.0 postinstall /data/data/com.termux/files/home/Orca/desktop/node_modules/electron
> node install.js

/data/data/com.termux/files/home/Orca/desktop/node_modules/electron/install.js:66
      throw new Error('Electron builds are not available on platform: ' + platform)
      ^

Error: Electron builds are not available on platform: android
    at getPlatformPath (/data/data/com.termux/files/home/Orca/desktop/node_modules/electron/install.js:66:13)
    at Object.<anonymous> (/data/data/com.termux/files/home/Orca/desktop/node_modules/electron/install.js:22:22)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1046:10)
    at internal/main/run_main_module.js:17:11
npm WARN Orca@0.1.0 No description
npm WARN Orca@0.1.0 No repository field.
npm WARN Orca@0.1.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@7.0.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@7.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2019-10-30T02_07_26_828Z-debug.log

I desperately need to free space on my phone and clearing all termux data it's not an option for me. :( Please help.

**Comment by xeffyr** [comment]
Answer is
```
Error: Electron builds are not available on platform: android
```
And Termux is `android`, so....

**Comment by H4ck3r404** [comment]
I know. The problem is that after executing npm install I've lost 70mb of memory. Can I somehow get it back?

**Comment by H4ck3r404** [comment]
(npm uninstall does not work.)

**Comment by Grimler91** [comment]
@H4ck3r404 you can remove files with the `rm` command, and folders with ` rm -r`.

**Comment by H4ck3r404** [comment]
Problem is that Orca folder contains only 10mb. Does that mean npm installed it in another location? (Tag -g was not used during instalation.)

**Comment by xeffyr** [comment]
Check dirs like `.cache`, `.local` in $HOME.

**Comment by xeffyr** [comment]
And check if any `node_modules` directories found:
```
find $HOME -type d -name node_modules
```

**Comment by H4ck3r404** [comment]
Command:

find $HOME -type d -name node_modules

gives me null output. I'm not sure about $HOME dir.
(.cache contains 4mb and .npm 17mb)
File explorer (with root) says it contains 87mb but <do> command shows me:

101M       .

 at the end of an output. I don't know what to do now.

**Comment by xeffyr** [comment]
If you use file explorer, you can probably turn on showing hidden files (starting with dot) and determine what you need to delete.

$PREFIX will always be big since stores all installed package data.

Another thing that is useful to get space usage by directories in $HOME:
```
cd $HOME
du -h --max-depth 1 | sort -k1hr
```

**Comment by xeffyr** [comment]
Yes, everything in $HOME may be deleted.
