### ISSUE TITLE
android sdkmanager failed connection to host

### ISSUE THREAD

**Issue by PlayLight** [termux/termux-packages#4481]
It's been over a year since i last used the android sdk within termux so maybe i've missed something here, but after installing OpenJava 8 and Android SDK i am unable to run any sdkmanager commands out of the gate.

sdkmanager commands are no longer working, due to a failed connection to the host (dl.google.com) while trying to retrieve addons_list<#>.xml.

```
Warning: Failed to connect to host: https://dl.google.com/android/repository/addons_list-3.xml
Warning: Failed to connect to host: https://dl.google.com/android/repository/addons_list-2.xml
Warning: Failed to connect to host: https://dl.google.com/android/repository/addons_list-1.xml
Warning: Failed to download any source lists!
```

**Steps to reproduce**
this can be reproduced simply by running the [setup-android-sdk.sh](https://github.com/termux/termux-packages/blob/master/scripts/setup-android-sdk.sh) script from the official [termux-packages](https://github.com/termux/termux-packages), as it also affects this package whenever sdkmanager commands are executed.

**Additional information**
I'm happy to provide any further information.
I'm hoping i've just been away for too long and simply missed some major changes to Termux :)
![Screenshot_20191030-212952](https://user-images.githubusercontent.com/7711708/67855757-c610d400-fb5e-11e9-8db7-16be0d1c5f02.png)

**Comment by xeffyr** [comment]
Emmm.... I didn't know when SDK was working in Termux...

**Comment by xeffyr** [comment]
If you got JDK from https://github.com/MasterDevX/Termux-Java, then know that DNS resolution is not working here.
