### ISSUE TITLE
Iostream missing from ndk-sysroot

### ISSUE THREAD

**Issue by H4ck3r404** [termux/termux-packages#4491]
When compiling program in c++ with #include <iostream> compiler shows that iostream is missing:

file.c:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.

#3726 references to this problem. Even so reinstalling clang neither ndk-sysroot helped me. Is there other way to fix this?

**Comment by H4ck3r404** [comment]
Update: phone is rooted.

**Comment by xeffyr** [comment]
It is not missing.

> file.c:1:10: fatal error: 'iostream' file not found
#include
^~~~~~~~~~
1 error generated.

Make sure that `#include ` is actually `#include <iostream>`.

Also:
* Make sure you are calling `clang++` to compile the C++ code.
* Make sure C++ file extension is `.cpp` - yours `file.c` is wrong.
