### ISSUE TITLE
Can't use the python package voice_assistant

### ISSUE THREAD

**Issue by Daniel-Brum** [termux/termux-packages#4493]
I downloaded the voice_assistant package using `pip` (with many difficulties, but I could do it, thankfully), but whenever I try to use it apart from importing it (in a .py file or in the interactive compiler) my Termux session freezes. Nothing works after that (the input is still shown, though), and I need to close the session and open another one.

**Comment by RossComputerGuy** [comment]
Sounds like an issue I remember from months ago where the Termux session was using too much RAM.

**Comment by Daniel-Brum** [comment]
Oh, I see. Is there any solution for this? My phone has 4GB of RAM.
