### ISSUE TITLE
dpkg: warning: 'busybox' not found in PATH or not executable

### ISSUE THREAD

**Issue by skycat2216** [termux/termux-packages#4494]
$ apt full-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  dos2unix ed findutils gawk gnupg grep inetutils
  libassuan libgmp libksba libmpfr libnpth net-tools
  patch pinentry procps psmisc sed unzip util-linux
The following packages will be upgraded:
  apt gpgv termux-tools
3 upgraded, 20 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/4993 kB of archives.
After this operation, 18.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg: warning: 'busybox' not found in PATH or not executable
dpkg: error: 1 expected program not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (2)

i'm using android 5.0.2 with mt6752
how to fix it?

**Comment by xeffyr** [comment]
Check the https://github.com/termux/termux-app/issues/1307#issuecomment-543996765.
