### ISSUE TITLE
.c .h files automatically gets execute permission when copied from Mobile device to PC

### ISSUE THREAD

**Issue by Next-93** [termux/termux-packages#4496]
The issue is when I move any .c and .h files from Termux to external storage then to PC all the .c and .h files are shown in green color in Ubuntu 18.04 i.e those are given execute permission automatically. Why ?

**Comment by its-pointless** [comment]
external sdcard has no execute permissions.

**Comment by Next-93** [comment]
I am not executing in external storage.

I will explain in detail.
All my .c and .h files are in Termux /home/C first I will execute those files. When everything is ok then I copy them to external storage
`cp -r ~/C ~/storage/shared/MyDir`
Then I copy them to PC. When copied from Mobile to PC .c and .h files are shown in green color. Why?

**Comment by its-pointless** [comment]
when saved on sdcard no execute bit is saved since no ececute is allowed. So all files are saved  with no execite permissions. Since its impossible to set it as having execute bit set sometimes this is interpreted by programs as all files having execite prrmissions set.

**Comment by Next-93** [comment]
Ok got it thanks
