### ISSUE TITLE
Package yasm is broken

### ISSUE THREAD

**Issue by aristarh2704** [termux/termux-packages#4497]
**Problem description**
Package yasm in the repository is broken, it doesn't work properly.

**Steps to reproduce**
Install ya from repository. Try compile by yasm this code:
```
bits 32
push ebx
```

**Expected behavior**
Yasm must emit `pushl` opcode, but emits `pushw`

**Additional information**
Post output of command `termux-info`.
```
Updatable packages:                            apt/stable 1.4.9-19 arm [upgradable from: 1.4.9-16]                                           ca-certificates/stable 20191016 all [upgradable from: 20190828]                               command-not-found/stable 1.42 arm [upgradable from: 1.39]                                     curl/stable 7.66.0-1 arm [upgradable from: 7.66.0]                                            dos2unix/stable 7.4.1 arm [upgradable from: 7.4.0-1]                                          libcurl/stable 7.66.0-1 arm [upgradable from: 7.66.0]                                         libedit/stable 20191025-3.1-0 arm [upgradable from: 20190324-3.1-1]                           openssh/stable 8.1p1-1 arm [upgradable from: 8.1p1]                                           openssl/stable 1.1.1d-1 arm [upgradable from: 1.1.1d]                                         termux-tools/stable 0.72 all [upgradable from: 0.71]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.83+ #1 SMP PREEMPT Wed Apr 17 15:37:32 CST 2019 armv7l Android
Termux-packages arch:
arm
Android version:
8.1.0
Device manufacturer:
ITEL MOBILE LIMITED
Device model:
itel A16 Plus RU
```

If I compile this package from sources or by using termux-packages on-host-build, it works properly.
Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
> Yasm must emit pushl opcode, but emits pushw

On PC it emits `push`, not `pushl` or `pushw`.

```
[xeffyr]:~:$ cat > test.asm
bits 32
push ebx
[xeffyr]:~:$ yasm -f elf -o test.elf test.asm
[xeffyr]:~:$ objdump -d test.elf

test.elf:     file format elf32-i386


Disassembly of section .text:

00000000 <.text>:
   0:	53                   	push   %ebx
```

On Termux behaviour is **same**. Used radare2 to check generated binary because arm/aarch64 `objdump` doesn't work with x86 binaries:
```
$ cat > test.asm
bits 32
push ebx
$ yasm -f elf test.asm -o test
$ radare2 test
Warning: run r2 with -e io.cache=true to fix relocations in disassembly
 -- Enable asm.trace to see the tracing information inside the disassembly
[0x08000040]> pd 1
            ;-- entry0:
            ;-- section..text:
            ;-- .text:
            ;-- eip:
            0x08000040      53             push ebx                    ; [04] -r-x section size 1 named .text
[0x08000040]>
```

**Comment by aristarh2704** [comment]
On pc it's work properly, on termux yasm from repository emit "push bx" (checked by pc binutils), but must emit "push ebx"

**Comment by aristarh2704** [comment]
Yasm on cygwin, on prooted Ubuntu, and official binary from site emit properly code, but your package doesn't.

**Comment by xeffyr** [comment]
```
$ yasm -f elf test.asm -o test
$ llvm-objdump -d test

test:	file format ELF32-i386


Disassembly of section .text:

00000000 .text:
       0: 53                           	pushl	%ebx
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/termux-root-packages-24 root/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://termux.org/packages stable/main
System information:
Linux localhost 3.18.91-15877854-QB25123770 #1 SMP PREEMPT Mon Jul 29 11:47:47 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-G930F
```

**Comment by aristarh2704** [comment]
My host is arm

**Comment by aristarh2704** [comment]
Oh, it doesn’t work even now, after the update. I tried run tests for yasm, 31 tests out of 44 failed. Yasm builded from source passes all tests.

**Comment by xeffyr** [comment]
Have checked the generated `config.h` and some `\*.c` files. The only difference I found is that yasm built on device is compiled with `libiconv` support. However changing `build.sh` to cross-compile it with libiconv doesn't fix the problem with invalid instructions generated. Compiler flags also don't matter. Don't know what is happening here.

Only ARM package is affected, others working fine.

***

Will add libiconv dependency, just in case.

**Comment by aristarh2704** [comment]
May be termux-packages in docker image are differ from repository?

**Comment by aristarh2704** [comment]
I found that files in massage dir not changed after rebuild.

**Comment by aristarh2704** [comment]
I find it's need to fully clean docker image.

**Comment by xeffyr** [comment]
> May be termux-packages in docker image are differs from repository?

?
CI/CD uses the latest docker image for building packages. Local repository also points on latest commit.

> I find it's need to fully clear docker image.

Packages for each push are built in freshly created container, so this is not an issue.

Maybe `./build-package.sh -I yasm` and `./build-package.sh yasm` produce different result somehow. I need to check this...

**Comment by xeffyr** [comment]
> Maybe ./build-package.sh -I -a arm yasm and ./build-package.sh -a arm yasm produce different result somehow. I need to check this...

Result of both commands is same as it should be, though yasm is broken in both cases.

**Comment by aristarh2704** [comment]
I may upload builded debs somethere.

**Comment by aristarh2704** [comment]
I found in cirrus log that some files doesn't generated, but on my host they are generated.

**Comment by xeffyr** [comment]
Which exactly ?
The file generation part -
```
./genperf /home/builder/.termux-build/yasm/src/x86insn_nasm.gperf x86insn_nasm.c
./genperf /home/builder/.termux-build/yasm/src/x86insn_gas.gperf x86insn_gas.c
./genmacro nasm-macros.c nasm_standard_mac /home/builder/.termux-build/yasm/src/modules/parsers/nasm/nasm-std.mac
./genmacro win64-nasm.c win64_nasm_stdmac /home/builder/.termux-build/yasm/src/modules/objfmts/coff/win64-nasm.mac
./genmacro win64-gas.c win64_gas_stdmac /home/builder/.termux-build/yasm/src/modules/objfmts/coff/win64-gas.mac
./genversion version.mac
./genmacro nasm-version.c nasm_version_mac version.mac
./genstring license_msg license.c /home/builder/.termux-build/yasm/src/COPYING
cc -o re2c  re2c-main.o re2c-code.o re2c-dfa.o re2c-parser.o re2c-actions.o re2c-scanner.o re2c-mbo_getopt.o re2c-substr.o re2c-translate.o 
./re2c -b -o gas-token.c /home/builder/.termux-build/yasm/src/modules/parsers/gas/gas-token.re
./re2c -b -o nasm-token.c /home/builder/.termux-build/yasm/src/modules/parsers/nasm/nasm-token.re
```
is same as in on-device build.

**Comment by aristarh2704** [comment]
I don't know how solve this issue.

**Comment by xtkoba** [comment]
Still actual.

**Comment by xtkoba** [comment]
This seems to be fixed by rebuilding with current NDK.
