### ISSUE TITLE
Package request: Openjdk

### ISSUE THREAD

**Issue by AliShahrivarian** [termux/termux-packages#45]
Hi

This app is awesome and it will be very interesting if there be openjdk.

thank you.

**Comment by fornwall** [comment]
Thanks for the suggestion! I started a [wiki page to keep track of package suggestions](https://github.com/termux/termux-packages/wiki/Package-suggestions) and have added Julia there!

**Comment by Neo-Oli** [comment]
Hi, I am re-opening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by TheDiamondYT1** [comment]
I hope somebody can try and compile Java 8, since Java 9 support doesn't work very well with lombok and other things.

By downloading the pre-built package in #1298, you can run Java 8 in Termux fairly easily. I tried to recreate this by downloading the official tarball, and failed.

I edited the script and used the gnulib provided by #1298, but no luck. They must have edited the source.
```bash
$ sh java
/data/data/com.termux/files/home/usr/jdk1.8.0_144/bin/__real_java: 1: /data/data/com.termux/files/home/usr/jdk1.8.0_144/bin/__real_java: Syntax error: end of file unexpected (expecting ")")
$ cat java
#!/data/data/com.termux/files/usr/bin/bash

export BASE_DIR="/data/data/com.termux/files/usr"
export JAVA_HOME="/data/data/com.termux/files/home/usr/jdk1.8.0_144"

export GNU_LIB_DIR="$BASE_DIR/share/gnulib"
export LD_LIBRARY_PATH="$GNU_LIB_DIR"

exec $JAVA_HOME/bin/__real_$(basename $0) "$@"
```

**Comment by sdrausty** [comment]
@AliShahrivarian   Java is available through:
# [TermuxArch](https://github.com/sdrausty/TermuxArch)

Now you can install Arch Linux in Termux 📲 on your smartphone and tablet. More information at https://sdrausty.github.io/TermuxArch

Java is available through https://sdrausty.github.io/TermuxArch/ Just follow the easy install instructions at https://sdrausty.github.io/TermuxArch/docs/docs/install or simply copy and paste the following into your Termux window:

```
cd && git clone https://github.com/sdrausty/TermuxArch
./TermuxArch/setupTermuxArch.sh
```
Read more about the Arch Linux package manager at [duckduckgo arch+linux+install+java+pacman.](https://duckduckgo.com/?q=arch+linux+install+java+pacman&atb=v90-2__&t=cros&ia=qa)

To install java run `pacman -Syy; pacman -Su; pacman -S jdk8-openjdk`


![screenshot_20171109-220204](https://user-images.githubusercontent.com/27742457/32641053-cedfdcfe-c599-11e7-9c73-b185e70e9c6a.png)

**Comment by cswl** [comment]
Whats blocking this? It'd be nice to have an JRE runtime at least.. If not for javac.. and JDK ..
without resorting to a full blown Arch Linux install

**Comment by sdrausty** [comment]
> Whats blocking this? 

I was asking similar questions a year ago.  We don't have enough people power who are active developers.  This is one of the reasons I got involved with this awesome project.  Consider contributing.  There are many ways to contribute.  Two important ways to contribue are documentation and promotion.  

Many people still do not know Termux and Termux Packages even exist!  If more developers knew about Termux @cswl, we would have a better Termux experience in the palm of our hand.

**Comment by Neo-Oli** [comment]
@gzmask Something like that. It is a user-space implementation of [chroot](https://en.wikipedia.org/wiki/Chroot).  Because it needs to emulate this functionality without using the root-only system calls programs tend to be much slower than a regular chroot, especially for programs which access file systems.

**Comment by sdrausty** [comment]
@gzmask we are working on timings at this https://github.com/termux/termux-app/issues/603 issue, "Terminal output speed issues". 

> Faster than vanilla Termux? Yes, faster by ~0.5s! See 0m8.320s above. Termux PRoot is about 6% faster than Termux. This is statistically significant. How is this possible?

@Neo-Oli PRoot is an amazing possibility in Termux that I just heard about a few months ago; Any documentation links that might help us understand what it is, what it does and how it accomplishes this are requested.

https://github.com/sdrausty/TermuxArch/blob/master/scripts/frags/stdoutbench.sh provides Termux screen output benchmarks; Share them with us along with a little system information.

**Comment by ashish0304** [comment]
Anyone please guide me to compile openjdk 8 for termux.
I've installed build environment with docker.

**Comment by xeffyr** [comment]
Issue continued in https://github.com/termux/termux-packages/issues/324.

**Comment by fajarnurprasetyo** [comment]
i not understand where the example for installing java 8 or 9
