### ISSUE TITLE
Package Request: samba (smbd) and cifs-utils

### ISSUE THREAD

**Issue by DRSDavidSoft** [termux/termux-packages#4501]
**Package description**
- Samba is a "SMB/CIFS file, print, and login server for Unix", which means it can provide Windows share functionality.
- The CIFS filesystem allows "SMB/CIFS shares to be mounted on Linux".

More on both: https://www.howtogeek.com/176471/how-to-share-files-between-windows-and-linux/

**Link to home page and sources**
1. Home page: https://www.samba.org//
2. Source code: 
   - Git: https://git.samba.org/
   - Tar package: https://download.samba.org/pub/samba/stable/samba-4.11.2.tar.gz

**Additional information**
I haven't personally tried to compile Samba on my devices, but many apps exist in the store that provide a pre-built Samba binary.

- [Servers Ultimate](https://play.google.com/store/apps/details?id=com.icecoldapps.serversultimate)
- [LAN drive - SAMBA Server & Client](https://play.google.com/store/apps/details?id=fr.webrox.landrive)

These apps are not directly useful, but it shows that Samba would work as intended when compiled for the device.

**Comment by nodefive** [comment]
Yeah would be nice some v2 v3 support.

Tried https://forum.xda-developers.com/showpost.php?p=8239139&postcount=128
But it is v1, cannot connect from my Mac.

Tried https://forum.xda-developers.com/showpost.php?p=8239139&postcount=128
Could not build, after configure errors out with a server.o with no rule to make.

I want to start all the daemons from a script within termux, so my workaround was to install apache2 and the php7 module for it, and using a php file manager gained access to the entire fs from a browser.

**Comment by gxbhgcb** [comment]
1. Get samba-3.5.9.tar.gz :
curl 'https://download.samba.org/pub/samba/stable/samba-3.5.9.tar.gz' --location --output ./samba-3.5.9.tar.gz
tar zxf samba-3.5.9.tar.gz
cd samba-3.5.9/source3/

2. Change file:
vi ./lib/system.c

/**************************************************************************
 Wrappers for getpwnam(), getpwuid(), getgrnam(), getgrgid()
****************************************************************************/
// gcb add
static struct passwd rootpw = {
     "root",
     "root",
     0,
     0,
     "root",
     "/root"
     "/data/data/com.termux/files/usr/bin/sh",
};
static char *rootmem[] = {
     "root"
};
static struct group rootgr = {
     "root",
     "root",
     0,
     rootmem,
};
//gcb add end


struct passwd *sys_getpwnam(const char *name)
{
        //return getpwnam(name); //gcb comment
        return &rootpw; // gcb add
}

struct passwd *sys_getpwuid(uid_t uid)
{
        //return getpwuid(uid); //gcb comment
        return &rootpw;
}

struct group *sys_getgrnam(const char *name)
{
        //return getgrnam(name); //gcb comment
       return &rootgr;
}

struct group *sys_getgrgid(gid_t gid)
{
        //return getgrgid(gid); //gcb comment
        return &rootgr;
}

3. Add config shell script:
vi ./my_android_config.sh 

CROSS_COMPILE=/home/drteam/gcb/Pie/prebuilts/gcc/linux-arm/Sourcery_G++_Lite/bin/arm-none-linux-gnueabi-
RUNTIME_DIR=/data/data/com.termux/files/usr
./configure \
CC="$CROSS_COMPILE"gcc \
AR="$CROSS_COMPILE"ar \
LD="$CROSS_COMPILE"ld \
RANLIB="$CROSS_COMPILE"ranlib \
--without-krb5 --without-ldap --without-ads --enable-static=yes --disable-shared \
--disable-cups --enable-swat=no --with-winbind=no \
--target=arm-linux-gnueabi --host=arm-linux-gnueabi \
--disable-cups \
--disable-iprint \
--prefix=$RUNTIME_DIR \
--exec-prefix=$RUNTIME_DIR \
--with-logfilebase=$RUNTIME_DIR/var/log \
--with-swatdir=$RUNTIME_DIR/usr/local/swat \
--with-rootsbindir=$RUNTIME_DIR/sbin \
--with-lockdir=$RUNTIME_DIR/var/lock \
--with-piddir=$RUNTIME_DIR/var/lock \
--with-privatedir=$RUNTIME_DIR/etc/samba \
--with-configdir=$RUNTIME_DIR/etc/samba \
--cache-file=armsel-linux.cache \
--with-static-modules=vfs_fake_perms \
samba_cv_CC_NEGATIVE_ENUM_VALUES=yes \
libreplace_cv_HAVE_GETADDRINFO=no \
ac_cv_file__proc_sys_kernel_core_pattern=yes 

4. Compile:

chmod +x ./my_android_config.sh
./my_android_config.sh
make -j48 LDFLAGS="-all-static -static"

5. Push smbd to your termux system:
scp -P 8022  ./bin/{smbd,nmbd,smbpasswd} root@192.168.1.111:/data/data/com.termux/files/usr/bin/
ssh -p 8022 root@192.168.1.111 "chmod +x ~/../usr/bin/*"
ssh -p 8022 root@192.168.1.111 "mkdir ~/../usr/etc/samba/ ; mkdir ~/../usr/var/{lock,tmp,log}"

6. Add your samba config:

vi ./smb.conf

[global]
interfaces = wlan0 eth0 lo
workgroup = WORKGROUP
server string = Samba on Android
netbios name = ANDROID
remote announce = 255.255.255.255
encrypt passwords = yes
security = user
restrict anonymous = 1
load printers = no
printcap name = /dev/null
disable spoolss = yes
deadtime = 5
delete readonly = yes
nt acl support = no
inherit permissions = yes
socket options = SO_SNDBUF=16384 SO_RCVBUF=16384

[sdcard]
vfs objects = fake_perms
comment = Android /mnt/sdcard
path = /mnt/sdcard
force user = root
read only = no
writable = yes
guest ok = no

7. Push the config file to your termux system:
scp -P 8022  ./smb.conf root@192.168.1.111:/data/data/com.termux/files/usr/etc/samba/

8. Start your SMB server on your Android device:

ssh -p 8022 root@192.168.1.111
pkg install proot
proot -0 smbpasswd  -a gcb
proot -0 smdb -p 1445 -D &
proot -0 nmbd -D &

9. Connect your Android device SMB server with file explorer app

**Comment by xeffyr** [comment]
@gxbhgcb https://github.com/termux/unstable-packages/tree/master/packages/samba

***

Closing as samba is already added to unstable repo.
```
pkg install unstable-repo
pkg install samba
```

**Comment by gxbhgcb** [comment]
Thanks!

**Comment by DRSDavidSoft** [comment]
@gxbhgcb Thanks for sharing your method, and I also appreciate @xeffyr adding the Samba package. Looking forward to seeing it in the stable ones.

**Comment by kellytrinh** [comment]
```
pkg install unstable-repo
pkg install samba
```

I did the two steps above and there is some samba related folders in `../usr/var/ but nothing in `../usr/etc`.  where should I put the `smb.conf` ?

**Comment by Stivencannor** [comment]
This package not work for me

**Comment by forever8938** [comment]
> @gxbhgcb https://github.com/termux/unstable-packages/tree/master/packages/samba
> 
> Closing as samba is already added to unstable repo.
> 
> ```
> pkg install unstable-repo
> pkg install samba
> ```

Not working at all. Where is smb.conf?

**Comment by Grimler91** [comment]
@forever8938 cp `$PREFIX/share/doc/samba/smb.conf.example` to `$PREFIX/etc/smb.conf` and modify it with your settings
