### ISSUE TITLE
cannot locate symbol "x265_api_get_176"

### ISSUE THREAD

**Issue by stuart-little** [termux/termux-packages#4502]
**Problem description**

Having updated the `x265` package today on `aarch64` in `v.0.77` on Android 9 I get the error

```
CANNOT LINK EXECUTABLE "ffmpeg": cannot locate symbol "x265_api_get_176" referenced by "/data/data/com.termux/files/usr/lib/libavcodec.so"...
```
when attempting to convert mp4 video to m4a audio with

```
ffmpeg -i <mp4 file> -vn -c:a copy <m4a file>
```
**Steps to reproduce**

Run the above command on an `mp4` file.

**Expected behavior**

A resulting `m4a` file containing just the audio track of the original `mp4` file.

**Additional information**

Updatable packages:
All packages up to date
Subscribed repositories:
https://termux.org/packages stable/main
System information:
Linux localhost 4.9.106-perf+ #1 SMP PREEMPT Wed Sep 11 23:50:26 HKT 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6013

**EDIT**

Actually, forget all that: just simply run `ffmpeg` in a terminal. The same error

```
CANNOT LINK EXECUTABLE "ffmpeg": cannot locate symbol "x265_api_get_176" referenced by "/data/data/com.termux/files/usr/lib/libavcodec.so"...
```
occurs.

**Comment by xeffyr** [comment]
Perhaps due to update of libx265 - https://github.com/termux/termux-packages/commit/ead8b4e9ab11e2022abdbeeff7b218a2b834eff5.

**Comment by xeffyr** [comment]
Does it work after `pkg uprgade` (ffmpeg 4.2.1-2) ?

**Comment by stuart-little** [comment]
I haven't tried the actual conversion, but running plain `ffmpeg` no longer returns the error. So I think this fixed it.
