### ISSUE TITLE
Cannot list root directory

### ISSUE THREAD

**Issue by canusmajor** [termux/termux-packages#4504]
Hi, termux updated during the course of last week and since then I have been unable to run an ls -l on the root directory.

![Screenshot_20191107-155716_Termux](https://user-images.githubusercontent.com/57492574/68396748-ba369a80-017a-11ea-94f3-e04788d702a7.jpg)

**Comment by kcubeterm** [comment]
1.Your phone is not rooted , so this error occur
2 try `termux-setup-storage` and then try




And can you provide the output of `termux-info`

**Comment by Grimler91** [comment]
As @kcubeterm said, you need root to see stuff in /

**Comment by canusmajor** [comment]
Hi Krishna,
I have tried the termux-setup-storage as suggested, it did not help.

With respect to Henrik, my phone has not been rooted and I would prefer not
to do so. Prior to the update, I was able to do a listing on / without any
issues.

Attached is a screenshot of the info requested.

Regards Ken.
