### ISSUE TITLE
How to install spiderfoot? (m2crypto)

### ISSUE THREAD

**Issue by H4ck3r404** [termux/termux-packages#4505]
I'm having a problem with spiderfoot. It needs to have m2crypto installed. Is there any way to install m2crypto without breaking apt enviroment?

**Comment by xeffyr** [comment]
> Is there any way to install m2crypto without breaking apt enviroment?

`pip install M2Crypto` ?
You have no other choice with python packages.

**Comment by H4ck3r404** [comment]
But it doesn't work. On output I have Command errored out exit with statut 1. There was a closed issue saying that it could be fixed by installing no_engine openssl build. After that was a comment from dev saying that it was patched. What should I do?
My arch is aarch64.

**Comment by H4ck3r404** [comment]
Note: error output is much longer than what I written.

**Comment by xeffyr** [comment]
Then you don't have `swig` installed.
`pkg install swig`

M2Crypto installing for me without **any** error.

**Comment by H4ck3r404** [comment]
Thanks. :)
