### ISSUE TITLE
Unstable termux tools

### ISSUE THREAD

**Issue by Amityaduvanshi** [termux/termux-packages#4507]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by Amityaduvanshi** [comment]
Tools are automatically deleted when I try to run them

**Comment by kcubeterm** [comment]
What do you mean by unstable termux-tools.
You should provide some more info about it.
Termux tools have some tools which doesn't work in termux like `pm` etc and `su` will work only when your device have superuser program installed.
