### ISSUE TITLE
Error while installing pypi package Unicorn

### ISSUE THREAD

**Issue by 0xEscxtt** [termux/termux-packages#4509]
`Building wheel for unicorn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-s05smeqb/unicorn/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-s05smeqb/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /data/data/com.termux/files/usr/tmp/pip-wheel-tk1khx0w --python-tag cp37
       cwd: /data/data/com.termux/files/usr/tmp/pip-install-s05smeqb/unicorn/
  Complete output (12 lines):
  running bdist_wheel
  running build
  Building C extensions
  cd qemu && \
  ./configure --cc="cc" --extra-cflags="-DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARMEB -DUNICORN_HAS_M68K -DUNICORN_HAS_ARM64 -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -fPIC -fvisibility=hidden" --target-list="x86_64-softmmu, arm-softmmu, armeb-softmmu, m68k-softmmu, aarch64-softmmu, mips-softmmu, mipsel-softmmu, mips64-softmmu, mips64el-softmmu, sparc-softmmu,sparc64-softmmu,"

  ERROR: Cannot use 'python', Python 2.4 or later is required.
         Note that Python 3 or later is not yet supported.
         Use --python=/path/to/python to specify a supported Python.

  make: *** [Makefile:214: qemu/config-host.h-timestamp] Error 1
  error: [Errno 2] No such file or directory: 'libunicorn.so'
  ----------------------------------------
  ERROR: Failed building wheel for unicorn
  Running setup.py clean for unicorn
Successfully built pwntools
Failed to build unicorn
Installing collected packages: unicorn, pwntools
  Running setup.py install for unicorn ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-s05smeqb/unicorn/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-s05smeqb/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-0q84nzqq/install-record.txt --single-version-externally-managed --compile
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-s05smeqb/unicorn/
    Complete output (12 lines):
    running install
    running build
    Building C extensions
    cd qemu && \
    ./configure --cc="cc" --extra-cflags="-DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARMEB -DUNICORN_HAS_M68K -DUNICORN_HAS_ARM64 -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -fPIC -fvisibility=hidden" --target-list="x86_64-softmmu, arm-softmmu, armeb-softmmu, m68k-softmmu, aarch64-softmmu, mips-softmmu, mipsel-softmmu, mips64-softmmu, mips64el-softmmu, sparc-softmmu,sparc64-softmmu,"

    ERROR: Cannot use 'python', Python 2.4 or later is required.
           Note that Python 3 or later is not yet supported.
           Use --python=/path/to/python to specify a supported Python.

    make: *** [Makefile:214: qemu/config-host.h-timestamp] Error 1
    error: [Errno 2] No such file or directory: 'libunicorn.so'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-s05smeqb/unicorn/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-s05smeqb/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-0q84nzqq/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.`

**Comment by Escxtt23** [comment]
Hi can you tell me how can i fix this Error while installing 

> pip3 install unicorn

**Comment by Grimler91** [comment]
Do you have python2 installed?

**Comment by xeffyr** [comment]
@Grimler91 python2 will not help there. Sources should be patched because it calls `python` instead of `python2`.

**Comment by xeffyr** [comment]
Can be fixed by executing
```
export UNICORN_QEMU_FLAGS="--python=$PREFIX/bin/python2"
```
before `pip install`. Package `python2` should be installed before doing this.

```
$ export UNICORN_QEMU_FLAGS="--python=$PREFIX/bin/python2"
$ pip install unicorn
Collecting unicorn
  Using cached https://files.pythonhosted.org/packages/7d/7f/47fe864fe967e91de2d57677618cffc91bee3918f0a3cdbaa6500b36855e/unicorn-1.0.1.tar.gz
Installing collected packages: unicorn
  Running setup.py install for unicorn ... done
Successfully installed unicorn-1.0.1
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$
```
