### ISSUE TITLE
include taskwarrior extra files 

### ISSUE THREAD

**Issue by linuxcaffe** [termux/termux-packages#451]
In a standard taskwarrior install, extra files (themes, holiday files, supporting scripts and sample hooks) are installed in /usr/local/share/doc/task/ 

In a termux install of taskwarrior, the .taskrc file (automatically created on first run) refers to theme files in /data/data/com.termux/files/usr/share/doc/task/, but no such files or path exists. 

This request, if possible, is to have those extra files made available in a termux install of task, in /data/data/com.termux/files/usr/share/doc/task/

thanks

**Comment by fornwall** [comment]
@linuxcaffe Thanks - this has been fixed in version `2.5.1-1` of the taskwarrior package, to which you can update with:

    apt update && apt upgrade
