### ISSUE TITLE
Tshark displaying nothing

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#4510]
Hello, when Tshark is upgraded to version 3.0.6, it stops working. It doesn't display anything when I attempt to capture. Can this bug be fixed?

**Comment by Grimler91** [comment]
Duplicate of https://github.com/termux/termux-root-packages/issues/108 and https://github.com/termux/termux-root-packages/issues/111. It seems like you are the only one who experiences this problem, so might be device specific. Closing as I can't reproduce the problem
