### ISSUE TITLE
Radare2 segfault

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#4511]
When I try to analyze a program with radare2, it's gives me the shell normally. But when I try to do something with the r2 shell, it gives me a segfault. Please help me.

**Comment by Harshiv-Patel** [comment]
@IRISnoir any solution for the segfault so far ?

**Comment by Harshiv-Patel** [comment]
For anyone using Android 5.x/6.x that might encounter the segfault same as I did, the solution is to upgrade to a recent version of radar2, say v4.4.0 or newer. This seems to have solved the issue for me on Android-5.
