### ISSUE TITLE
Streamripper

### ISSUE THREAD

**Issue by lchongv** [termux/termux-packages#4512]
I wish to use streamripper in order to record an stream of audio of various radios from Chile, using a low-consume android tv cheap set

**Package description**
Takes a stream of audio from the internet and saves it to a file of audio

**Link to home page and sources**
1. Home page: http://streamripper.sourceforge.net/
2. Source code: https://sourceforge.net/projects/streamripper/files/streamripper%20%28current%29/1.64.6/

**Additional information**
Have you compiled or tried to compile the package on device? No

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install streamripper
```
