### ISSUE TITLE
NodeJS, CANNOT LINK EXECUTABLE: library "libicui18n.so.65"

### ISSUE THREAD

**Issue by Aybee5** [termux/termux-packages#4513]
I just installed nodejs, but whenever I try running `node`, `npm` it throws this error 

> CANNOT LINK EXECUTABLE: library "libicui18n.so.65" not found
page record for 0xb57ad02c was not found (block_size=16)

**Comment by xeffyr** [comment]
Post output of `termux-info`.

**Comment by Aybee5** [comment]
> termux-info
Updatable packages:
apt/stable 1.4.9-7 arm [upgradable from: 1.4.9-5]
bash/stable 5.0.11 arm [upgradable from: 5.0.7-1]
busybox/stable 1.30.1-6 arm [upgradable from: 1.30.1-2]
ca-certificates/stable 20191016 all [upgradable from: 20190515]
dash/stable 0.5.10.2-2 arm [upgradable from: 0.5.10.2-1]
dpkg/stable 1.19.7-4 arm [upgradable from: 1.19.7]
gpgv/stable 2.2.17 arm [upgradable from: 2.2.16]
libandroid-support/stable 24-5 arm [upgradable from: 24-3]
libbz2/stable 1.0.8-2 arm [upgradable from: 1.0.6-3]
libc++/stable 20-2 arm [upgradable from: 20]
libcurl/stable 7.67.0 arm [upgradable from: 7.65.1]
libgcrypt/stable 1.8.5 arm [upgradable from: 1.8.4]
libgpg-error/stable 1.36-1 arm [upgradable from: 1.36]
libiconv/stable 1.16-3 arm [upgradable from: 1.16-2]
libicu/stable 65.1 arm [upgradable from: 64.2-2]
liblzma/stable 5.2.4-2 arm [upgradable from: 5.2.4]
libnghttp2/stable 1.39.2 arm [upgradable from: 1.38.0]
ncurses/stable 6.1.20190511-7 arm [upgradable from: 6.1.20190511-1]
openssl/stable 1.1.1d-1 arm [upgradable from: 1.1.1c-1]
readline/stable 8.0.1 arm [upgradable from: 8.0-1]
termux-am/stable 0.3 all [upgradable from: 0.2]
termux-exec/stable 0.4-1 arm [upgradable from: 0.3]
termux-tools/stable 0.71 all [upgradable from: 0.67]
zlib/stable 1.2.11-1 arm [upgradable from: 1.2.11]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/griml

I've run `apt get update` before installing node

>

**Comment by xeffyr** [comment]
> I've run apt get update before installing node
> libicu/stable 65.1 arm [upgradable from: 64.2-2]

**Upgrade your packages !** Use `pkg upgrade` instead of `apt-get update`.

Check general requirements for submitting bug reports - https://github.com/termux/termux-packages#bug-reports.

**Comment by xeffyr** [comment]
* `apt-get update`, `apt update` - update package lists
* `apt-get upgrade`, `apt upgrade` - upgrade installed packages

**Comment by pollen5** [comment]
This is simply due to outdated packages. A simple `pkg install libicu` fixes it.
