### ISSUE TITLE
Rails new not working

### ISSUE THREAD

**Issue by Surya-risingsun** [termux/termux-packages#4516]
Rails new command gives an error at sacss installation

`  $ rails new blog
      create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /data/data/com.te
rmux/files/home/ror/blog/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.
rb
      create  app/channels/application_cable/connecti
on.rb
      create  app/controllers/application_controller.
rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_control
ler_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers
.rb
      create  config/initializers/content_security_po
licy.rb
      create  config/initializers/cookies_serializer.
rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_lo
gging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defau
lts_6_0.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connect
ion_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defau
lts_6_0.rb
         run  bundle install
The dependency tzinfo-data (>= 0) will be unused by a
ny of the platforms Bundler is installing for. Bundle
r is installing for ruby but the dependency is only f
or x86-mingw32, x86-mswin32, x64-mingw32, java. To ad
d those platforms to the bundle, run `bundle lock --a
dd-platform x86-mingw32 x86-mswin32 x64-mingw32 java`
.
Fetching gem metadata from https://rubygems.org/.....
.......
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.........
Using rake 13.0.0
Using concurrent-ruby 1.1.5
Using i18n 1.7.0
Using minitest 5.13.0
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using zeitwerk 2.2.1
Using activesupport 6.0.1
Using builder 3.2.3
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.5
Using rails-dom-testing 2.0.3
Using crass 1.0.5
Using loofah 2.3.1
Using rails-html-sanitizer 1.3.0
Using actionview 6.0.1
Using rack 2.0.7
Using rack-test 1.1.0
Using actionpack 6.0.1
Using nio4r 2.5.2
Using websocket-extensions 0.1.4
Using websocket-driver 0.7.1
Using actioncable 6.0.1
Using globalid 0.4.2
Using activejob 6.0.1
Using activemodel 6.0.1
Using activerecord 6.0.1
Using mimemagic 0.3.3
Using marcel 0.3.3
Using activestorage 6.0.1
Using mini_mime 1.0.2
Using mail 2.7.1
Using actionmailbox 6.0.1
Using actionmailer 6.0.1
Using actiontext 6.0.1
Using public_suffix 4.0.1
Using addressable 2.7.0
Using bindex 0.8.1
Using msgpack 1.3.1
Using bootsnap 1.4.5
Using bundler 1.17.3
Using byebug 11.0.1
Using regexp_parser 1.6.0
Using xpath 3.2.0
Using capybara 3.29.0
Using childprocess 3.0.0
Using ffi 1.11.1
Using jbuilder 2.9.1
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using ruby_dep 1.5.0
Using listen 3.1.5
Using method_source 0.9.2
Using puma 4.3.0
Using rack-proxy 0.6.5
Using thor 0.20.3
Using railties 6.0.1
Using sprockets 4.0.0
Using sprockets-rails 3.2.1
Using rails 6.0.1
Using rubyzip 2.0.0
Fetching sassc 2.2.1
Installing sassc 2.2.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem
native extension.

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/g
ems/sassc-2.2.1/ext
/data/data/com.termux/files/usr/bin/ruby -I
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.
6.0
-r ./siteconf20191109-8123-9rdik.rb extconf.rb
creating Makefile

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/g
ems/sassc-2.2.1/ext
make "DESTDIR=" clean

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/g
ems/sassc-2.2.1/ext
make "DESTDIR="
compiling ./libsass/src/ast.cpp
clang-8: error: the clang compiler does not support
'-march=native'
make: *** [Makefile:237: ast.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/g
ems/sassc-2.2.1
for inspection.
Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/e
xtensions/aarch64-linux/2.6.0/sassc-2.2.1/gem_make.ou
t

An error occurred while installing sassc
(2.2.1), and Bundler cannot continue.
Make sure that `gem install sassc -v '2.2.1' --source
'https://rubygems.org/'` succeeds before
bundling.

In Gemfile:
  sass-rails was resolved to 6.0.0, which depends on
sassc-rails was resolved to 2.1.2, which depends
on
      sassc
         run  bundle binstubs bundler
Could not find gem 'sass-rails (>= 6)' in any of the
gem sources listed in your Gemfile.
         run  bundle exec spring binstub --all
bundler: command not found: spring
Install missing gem executables with `bundle install`
       rails  webpacker:install
Could not find gem 'sass-rails (>= 6)' in any of the 
gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
$      `

**Comment by Surya-risingsun** [comment]
When I tried installing sass gem 

`     gem install sassc -v '2.2.1'
Building native extensions. This could take a while...
ERROR:  Error installing sassc:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/ext
/data/data/com.termux/files/usr/bin/ruby -I /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0 -r ./siteconf20191109-10909-1qjrl9c.rb extconf.rb
creating Makefile

current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/ext
make "DESTDIR=" clean

current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/ext
make "DESTDIR="
compiling ./libsass/src/ast.cpp
clang-8: error: the clang compiler does not support '-march=native'
make: *** [Makefile:237: ast.o] Error 1

make failed, exit code 2

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/sassc-2.2.1 for inspection.    `

**Comment by xeffyr** [comment]
It just uses unsupported compiler flag for native extensions.
`-march=native` is not supported by clang for AArch64 or ARM. Nothing can be done from Termux side to fix that error.

You may try to install `sassc` from source, with removing occurrences of `-march=native` in build files.
