### ISSUE TITLE
smbclient package

### ISSUE THREAD

**Issue by WhiteExponent** [termux/termux-packages#4517]
**Package description**
From Debian: 
```
Samba is an implementation of the SMB/CIFS protocol for Unix systems, providing support for cross-platform file and printer sharing with Microsoft Windows, OS X, and other Unix systems.

This package contains command-line utilities for accessing Microsoft Windows and Samba servers, including smbclient, smbtar, and smbspool. Utilities for mounting shares locally are found in the package cifs-utils.
```

**Link to home page and sources**
1. Home page:http://www.samba.org/
2. Source code: 
 - https://packages.debian.org/source/buster/samba
 - https://git.samba.org/

**Additional information**
> Have you compiled or tried to compile the package on device?

No.

**Reason to add package**
It allows for easy copying of files from Windows or Linux shares without attaching USB cables. It also allows you to browse samba shares from the terminal.

**Comment by Efreak** [comment]
This would be appreciated. If love to have smbc/smb commander for browsing network shares directly within termux.

**Comment by its-pointless** [comment]
smbc is not likely. i can provide a (really bad) substitute using libsmb2. Browsing is the part that is tricky though.

**Comment by Efreak** [comment]
Samba also includes a program called smbclient that works like ftp/sftp. It requires python, though.

<details>
<summary>apt-cache and file output</summary>

```
Package: smbclient
Architecture: amd64
Version: 2:4.7.6+dfsg~ubuntu-0ubuntu2.13
Priority: optional
Section: net
Source: samba
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Samba Maintainers <pkg-samba-maint@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1731
Provides: samba-client
Pre-Depends: dpkg (>= 1.15.6~)
Depends: samba-common (= 2:4.7.6+dfsg~ubuntu-0ubuntu2.13), samba-libs (= 2:4.7.6+dfsg~ubuntu-0ubuntu2.13), libarchive13 (>= 3.0.4), libbsd0 (>= 0.0), libc6 (>= 2.14), libpopt0 (>= 1.14), libreadline7 (>= 6.0), libsmbclient (>= 2:4.0.3+dfsg1), libtalloc2 (>= 2.0.4~git20101213), libtevent0 (>= 0.9.9)
Suggests: cifs-utils, heimdal-clients
Filename: pool/main/s/samba/smbclient_4.7.6+dfsg~ubuntu-0ubuntu2.13_amd64.deb
Size: 351388
MD5sum: 98a3880d822922d4399ddf39824b6dc9
SHA1: 1ca5827e8e5ab99db46696a9dc524a4bf0309813
SHA256: 44477eff06f2ccce36ab88ddc2dd5aa2db76d0880a55f3800bacfaba466bed4a
Homepage: http://www.samba.org
Description-en: command-line SMB/CIFS clients for Unix
 Samba is an implementation of the SMB/CIFS protocol for Unix systems,
 providing support for cross-platform file and printer sharing with
 Microsoft Windows, OS X, and other Unix systems.
 .
 This package contains command-line utilities for accessing Microsoft
 Windows and Samba servers, including smbclient, smbtar, and smbspool.
 Utilities for mounting shares locally are found in the package
 cifs-utils.
Description-md5: 476018eed30b7f1e76b02afe22aaf008
Task: samba-server, ubuntu-mate-core, ubuntu-mate-desktop
Supported: 5y

efreak@Lenovo:~$ file /usr/bin/smbclient
/usr/bin/smbclient: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=fec7af066f7a84a7d6f68b440e7822bfc2e0cd38, stripped
```

</details>

**Comment by its-pointless** [comment]
i actually have half written a front end for libsmb2 around. I need to fix it up properly. But i can upload and download files and directory and sub directories etc.
Using commands like smbls to as ls current directory in share.

**Comment by its-pointless** [comment]
Havent had time to work on it but try this https://github.com/its-pointless/gcc_termux/raw/master/smb2box_0.1_aarch64.deb 
libsmb2 is available on my apt repo

**Comment by Cubuss** [comment]
> 
> 
> Havent had time to work on it but try this https://github.com/its-pointless/gcc_termux/raw/master/smb2box_0.1_aarch64.deb
> libsmb2 is available on my apt repo
> https://github.com/its-pointless/its-pointless.github.io/raw/master/files/24/dists/termux/extras/binary-aarch64/libsmb2_3.0.0-1_aarch64.deb

Will this allow for mounting to?
Like mount the network drive to android fs?

**Comment by xeffyr** [comment]
> Will this allow for mounting to?

No.

**Comment by am11** [comment]
Is it possible to port a part of Samba repo as a package? e.g. one of a prerequisites of [`gssntlmssp`](https://pagure.io/gssntlmssp) is `libwbclient` from Samba: https://github.com/samba-team/samba/tree/master/nsswitch/libwbclient.

**Comment by QGB** [comment]
termux python smb client access file

**Comment by xtkoba** [comment]
Now that `smbclient` command belongs to `samba` package, can this be closed as fixed?
