### ISSUE TITLE
Gdb-python

### ISSUE THREAD

**Issue by delmarocks** [termux/termux-packages#4518]
Is there any way to run gef on termux as gdb-termux never supports python on its compiled state![](https://i.imgur.com/NNzsepE.png)

**Comment by Auxilus** [comment]
You'll have to compile gdb with python support, https://github.com/termux/termux-packages/issues/993#issuecomment-446621997

**Comment by delmarocks** [comment]
@Auxilus i tried that but it fails to compile in my device. My arch is armv7l actually.

**Comment by xeffyr** [comment]
GDB now has Python 3 support starting from version `8.3.1-1`.
