### ISSUE TITLE
MPV doesn't stop until some combination done

### ISSUE THREAD

**Issue by Abrifq** [termux/termux-packages#4522]
**Problem description**
I don't know if this happens on other apps but when using mpv, ending all sessions won't kill mpv.

**Steps to reproduce**
Start listening to any music with mpv. Kill all sessions through the notification. Should continue to playing the music. 
Creating a new session and trying `ps -x` will show pid of mpv. Killing it with `kill <PID>` will stop it.

To kill mpv without opening another session, you need to delete Termux from Recents **after killing it through the notification.**

**Expected behavior**
Killing the session should stop mpv.

**Additional information**
```sh
$ termux-info
Updatable packages:
termux-tools/stable 0.73 all [upgradable from: 0.72]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://termux.org/packages stable/main
System information:
Linux localhost 3.18.91-16437666 #1 SMP PREEMPT Tue Jul 23 17:05:45 KST 2019 armv8l Android
Termux-packages arch:
arm
Android version:
9
Device manufacturer:
samsung
Device model:
SM-J330F
```
<details>
  <summary>Strace for full moon geeks</summary>

https://s.amsu.ng/qatz40Lo8DGN
  
</details>

**Comment by xeffyr** [comment]
> Kill all sessions through the notification. Should continue to playing the music.

It shouldn't.

**Comment by fbarda** [comment]
> > Kill all sessions through the notification. Should continue to playing the music.
> 
> It shouldn't.

That is the symptom.

**Comment by xeffyr** [comment]
Actually, when all Termux sessions are killed, there happens the following:

1. After application being closed, it isn't closed completely by Android OS. It is being in cached state which can be checked by task manager.

2. Foreground processes are being killed since shell is no longer exist.

3. Daemonized processes still running until application is not unloaded from memory completely (i.e. killed).

**Comment by xeffyr** [comment]
While it is possible to make application killing all processes when sessions are closed, such behaviour is not acceptable for all users.

**Comment by fbarda** [comment]
Interesting, it still downloads the stream after closing the sessions until I close the app from recents. Is it normal for a cached app to have access to internet? I will try enabling **optimizing the app**.

**Comment by fbarda** [comment]
Tried optimizing and limiting background battery usage, still same.

**Comment by xeffyr** [comment]
> Is it normal for a cached app to have access to internet?

Command line programs are running outside of Android runtime. Though they still are bound to Android application which still exists in memory.

**Comment by fbarda** [comment]
> While it is possible to make application killing all processes when sessions are closed, such behaviour is not acceptable for all users (e.g. those who use Termux in headless mode via sshd).

Then, what is the point of having a wakelock? When I was in Oreo, it closed sshd when disabled "acquire wakelock" and killed the sessions. It wouldn't otherwise.

**Comment by xeffyr** [comment]
Point of wakelock is to prevent CPU going to sleep mode.

**Comment by xeffyr** [comment]
Regarding mpv, it is being stopped immediately when closing all sessions (Samsung Galaxy S7, stock Oreo).

**Comment by fbarda** [comment]
Oh, well then reference and close this thread. I don't know how to.

**Comment by kalmari246** [comment]
I'm on Pie, mpv stops when termux is closed from recents and wakelock is off, otherwise it keeps playing.

**Comment by zabeiua** [comment]
If  mpv  is running in tmux, "tmux kill-session -t 0" will kill it

**Comment by Abrifq** [comment]
> mpv is running in tmux
that was an extra step I didn't want to take. I just went "`mpv <link>` makes my internet radio go brr"

**Comment by Abrifq** [comment]
While I appreciate an issue being re-opened, I don't think there is a clean fix for this. Let's keep it closed.
