### ISSUE TITLE
Nokogiri

### ISSUE THREAD

**Issue by vaibhavbhakuni** [termux/termux-packages#4532]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by vaibhavbhakuni** [comment]
Gyes please help me metasploit has not install nokogiri (1.10.4), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.4'  --source 'https://rubygems.org/'` succeeds before bundling. This isse

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/4308 and https://github.com/termux/termux-packages/issues/4302

**Comment by vaibhavbhakuni** [comment]
Ten me what to do
I don't understand

**Comment by Grimler91** [comment]
Alright, read and follow the instructions in the wiki and metasploit should work: https://wiki.termux.com/wiki/Metasploit_Framework

**Comment by vaibhavbhakuni** [comment]
I already done
Pkg install unstable-repo
And pkg install metaploit
70 mb file download but other 333 mb file not download
