### ISSUE TITLE
Termux pwntools segmentation fault

### ISSUE THREAD

**Issue by delmarocks** [termux/termux-packages#4534]
Whenever i tried to load the binary on my environment using ELF it crashes and i got segmentation fault. What's the reason behind this?

![](https://i.imgur.com/sOyy14Y.png)

**Comment by xeffyr** [comment]
Your device has ARM CPU ?
Post `uname -m` output.

**Comment by xeffyr** [comment]
Pwntools that just printed that cannot run on 32bit (ARM) python.

**Comment by delmarocks** [comment]
![](https://i.imgur.com/ywOlC5X.png)


This is the output

**Comment by delmarocks** [comment]
Is there any way to make this work on 32 bit arch?

**Comment by xeffyr** [comment]
Ask package's developer.
As I see, it just doesn't support it.
