### ISSUE TITLE
The repository 'https://termux.org/packages stable Release' is no longer signed

### ISSUE THREAD

**Issue by stuart-little** [termux/termux-packages#4537]
**Problem description**

After the latest `apt` update I am getting the error in the title upon issuing `apt update` or `pkg update`:

```
The repository 'https://termux.org/packages stable Release' is no longer signed

```

**Steps to reproduce**

Run `apt update` with the only `apt` source being 

```
$PREFIX/etc/apt/sources.list:

# The main termux repository:
deb https://termux.org/packages/ stable main
```

**Expected behavior**

Normal package repo sync.

**Additional information**

Packages CPU architecture:
aarch64
Subscribed repositories:
\# sources.list
deb https://termux.org/packages/ stable main
\# sources.list.d/science.list.bak
deb https://dl.bintray.com/grimler/science-packages-24 science stable
\# sources.list.d/game.list.bak                       
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:                                  
All packages up to date                              
Android version:
9                                                    
Kernel build information:
Linux localhost 4.9.106-perf+ #1 SMP PREEMPT Wed Sep 11 23:50:26 HKT 2019 aarch64 Android
Device manufacturer:
OnePlus                                              
Device model:
ONEPLUS A6013

**Comment by xeffyr** [comment]
It is normal now.
