### ISSUE TITLE
Termus install pandas issue

### ISSUE THREAD

**Issue by wabbyy** [termux/termux-packages#4538]
The following step is dead for more than 30 minutes, why?
"Running setup.py install for pandas ... /"

----------------------
$ pip install pandas
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/b7/93/b544dd08092b457d88e10fc1e0989d9397fd32ca936fdfcbb2584178dd2b/pandas-0.25.3.tar.gz
Requirement already satisfied: python-dateutil>=2.6.1 in /data/data/com.termux/files/usr/lib/python3.7/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /data/data/com.termux/files/usr/lib/python3.7/site-packages (from pandas) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in /data/data/com.termux/files/usr/lib/python3.7/site-packages (from pandas) (1.17.4)
Requirement already satisfied: six>=1.5 in /data/data/com.termux/files/usr/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas) (1.13.0)
Installing collected packages: pandas
    Running setup.py install for pandas ... /

**Comment by xeffyr** [comment]
A lot of native extensions is being compiled, that is why it takes long time for installation.

**Comment by wabbyy** [comment]
I waited for 1.5 hours, but not still dead,

> A lot of native extensions is being compiled, that is why it takes long time for installation.

**Comment by wabbyy** [comment]
Now I have to "CTRL+C" to stop it,  anyone can help?

**Comment by Grimler91** [comment]
Install it with `pip install -vvv pandas` if you want more output.

**Comment by abhi5794** [comment]
Hi, I am facing the below error when installing pandas 
`
error: command 'aarch64-linux-android-clang' failed with exit status 1                                          ----------------------------------------                ERROR: Failed building wheel for pandas               Failed to build pandas                                  ERROR: Could not build wheels for pandas which use PEP 517 and cannot be installed directly
`

**Comment by shyamsantoki** [comment]
How did you solve it?

**Comment by abhi5794** [comment]
Hey check the issue #5648, it has the details, you need to install it by setting up gcc-9 , from its-pointless repo, then do a pip install, it'll work, if you get somewhere, then drop a comment

**Comment by shyamsantoki** [comment]
That's entirely different issue. By the way, my issue has been resolved by installing pandas 1.0.5 instead of latest version.
________________________________

**Comment by chrisamow** [comment]
Building wheel for pandas hang here
No luck with 1.0.5 either
