### ISSUE TITLE
Package request: Most (pager)

### ISSUE THREAD

**Issue by Efreak** [termux/termux-packages#4539]
> MOST is a powerful paging program for Unix, VMS, MSDOS, and win32 systems. Unlike other well-known paging programs most supports multiple windows and can scroll left and right.

In terms of functionality, I'd say that most sits somewhere between bat and less (though bat ultimately relies on less for the actual paging, while most does not). The biggest drawback is incomplete support for colors (try `exa -l|most`, for example, and every line will show at least one escape code), as it tries to filter out escape sequences.
The advantage, however, is being able to scroll horizontally--you can now open up a file with long lines without having to wrap/truncate. When not doing anything fancy with colors, most is superior to less. 

**Link to home page and sources**
1. Home page: https://www.jedsoft.org/most
2. Source code: https://www.jedsoft.org/releases/most
 
**Additional information**
I have successfully compiled most on my tablet. This requires having s-lang installed, however, and s-lang did not want to install nicely. Unfortunately, I no longer have the source code for it, as I didn't intend to request it. I will attempt it on my phone in the next couple of days to see if I can figure it out again.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install most
```
