### ISSUE TITLE
Unable to compile ncurses c code 

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#4546]
#include <ncurses.h>                                         
 int main()                                                  
 {        
                                                         
initscr();                                                    
printw("Hello, world!");                                     
refresh();                                                    
getch();                                                      
endwin();                                                     
return 0;

}
Give me the following compilation error:

/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/tmp/ncurses-3ca37c.o: in function `main':
ncurses.c:(.text+0x18): undefined reference to `stdscr'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ncurses.c:(.text+0x1c): undefined reference to `stdscr'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ncurses.c:(.text+0x30): undefined reference to `initscr'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ncurses.c:(.text+0x3c): undefined reference to `printw'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ncurses.c:(.text+0x4c): undefined reference to `wrefresh'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ncurses.c:(.text+0x5c): undefined reference to `wgetch'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ncurses.c:(.text+0x60): undefined reference to `endwin'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Grimler91** [comment]
You need to link against libcurses.so with ` -lcurses`.

**Comment by dipayand** [comment]
Thank you so much
