### ISSUE TITLE
Rust 1.39

### ISSUE THREAD

**Issue by jonathandturner** [termux/termux-packages#4549]
**Package description**
You have Rust 1.38 available, and Rust 1.39 is a significant improvement by being the first to allow powerful features like async/await.

**Link to home page and sources**
1. Home page: https://blog.rust-lang.org/2019/11/07/Rust-1.39.0.html
2. Source code: https://github.com/rust-lang/rust

**Comment by Luflosi** [comment]
#4561 was merged, so this can probably be closed.
