### ISSUE TITLE
Can't install python

### ISSUE THREAD

**Issue by keyduq** [termux/termux-packages#455]
Everytime that I try to install python with `apt install python`, always says:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python' has no installation candidate
```
And I already run `apt install update` and `apt install upgrade` several times

**Comment by fornwall** [comment]
You should run `apt update` to download the package index! This is needed once initially, and then you should run it regularly to get updates.

**Comment by keyduq** [comment]
I already try running `apt update` and `apt upgrade` several times and nothing...
![photo_2016-09-15_15-25-52](https://cloud.githubusercontent.com/assets/4933682/18564322/ff77cf66-7b58-11e6-83be-61ff317b6f73.jpg)

**Comment by fornwall** [comment]
Ok, two things to try out!

1. Can you run `apt clean` once, and see if `apt update && apt install python` works after that?

2. I see that you are using a mirror - could you try if reverting to using `deb http://termux.net stable main` in `$PREFIX/etc/apt/sources.list` makes it work?

**Comment by keyduq** [comment]
Yeah was the mirror, I run this script https://github.com/4679/oh-my-termux/blob/master/install.sh to get oh-my-zsh on termux and that has modified my sources.list. Thanks!

**Comment by fornwall** [comment]
Great, thanks for the information!
