### ISSUE TITLE
Bash problem

### ISSUE THREAD

**Issue by BEACHEADVN** [termux/termux-packages#4550]
I write a few commands:
#!/bin/sh
a=/sdcard/Download
b=/ext
c=/temp
d=/system
e=/vendor

cd $a
ls *.zip >> a
x=`wc -l < a`
#echo "$x"

for (( c=1; c<=$x; c++ ))
do
	zipinfo -1 `sed -n "$c"p a` >> $c
	if grep -Fxq "system.new.dat.br" $c
then
    sed -n "$c"p a >> rom
else
    echo ""
fi
rm -rf $c
done
rm -rf a
cat rom
rm -rf rom

* Problem:
when I enter commands directly into termux they work but when I copy them into the t file and I run it, it doesn't work.
* Error information:
$tsu
bash /sdcard/t
/sdcard/t: line 7: $'\r': command not found
/sdcard/t: line 8: cd: $'/sdcard/Download\r\r': No such file or directory
ls: cannot access '*.zip': No such file or directory
/sdcard/t: line 10: a: No such file or directory
/sdcard/t: line 12: $'\r': command not found
/sdcard/t: line 13: syntax error near unexpected token `$'\r''
'sdcard/t: line 13: `for (( c=1; c<=$x; c++ ))

Thank you!

**Comment by Grimler91** [comment]
Looks like a line ending problem. `\r` is the line ending using on mac (windows uses `\r\n` and unix `\n`). Try making sure the script uses standard unix line endings, the programs `dos2unix` and `mac2unix` from the package `dos2unix` can be used to convert to unix line endings.

**Comment by xeffyr** [comment]
Yes, it fails due to line edings (bash expects only `\n` at the line end).
Easily reproducible on PC:
```
[xeffyr]:~:$ cat foo.sh 
#!/bin/bash

set -e

echo this script contains a lot errors
[xeffyr]:~:$ unix2dos foo.sh 
unix2dos: converting file foo.sh to DOS format...
[xeffyr]:~:$ bash foo.sh 
foo.sh: line 2: $'\r': command not found
: invalid optionset: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
foo.sh: line 4: $'\r': command not found
this script contains a lot errors
```
