### ISSUE TITLE
Package request:  ffsend 

### ISSUE THREAD

**Issue by selvodka** [termux/termux-packages#4551]
Package description
Easily and securely share files from the command line. A fully featured Firefox Send client

Source code: https://gitlab.com/timvisee/ffsend

**Comment by timvisee** [comment]
Developer of `ffsend` here. If any change or help in/from `ffsend` is required to pull this off, let me know.

**Comment by xeffyr** [comment]
@timvisee Do you know why compilation of 0.2.55 fails at
```
   Compiling ffsend-api v0.4.1
error[E0463]: can't find crate for `which`
 --> src/util.rs:9:1
  |
9 | extern crate which;
  | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: failed to compile `ffsend v0.2.55 (/home/builder/.termux-build/ffsend/src)`, intermediate artifacts can be found at `/home/builder/.termux-build/ffsend/src/target`

Caused by:
  could not compile `ffsend`.

To learn more, run the command again with --verbose.
```
?

**Comment by timvisee** [comment]
@xeffyr I do not, but I'll take a look into it. Looks like weird Rust `cargo` behavior, because the `which` package is [available](https://crates.io/crates/which).

**Comment by timvisee** [comment]
Conditionals are used for this missing `which` crate. It is only [included](https://github.com/timvisee/ffsend/blob/801b946abd94d9f0893fd93e19a6f02f5e8c1434/Cargo.toml#L131-L132) on non-Windows & non-macOS, and uses a compile time [`build.rs`](https://github.com/timvisee/ffsend/blob/801b946abd94d9f0893fd93e19a6f02f5e8c1434/build.rs#L2-L36) to select the `clipboard-bin` feature which uses this crate.

Could you provide the `cargo` command that is used to compile this crate, as I can't really find it in the build logs of b5a8650f9cc9eba6dea3918a73e7dd6e6c5d27b9? Some defaults might be disabled in using flags. The daily `ffsend` [builds](https://gitlab.com/timvisee/ffsend/pipelines) in CI don't suffer from this problem, and I have not seen it before.

**Comment by xeffyr** [comment]
```
cargo install --jobs 2 --path . --force --target aarch64-linux-android --root /data/data/com.termux/files/usr
```

**Comment by xeffyr** [comment]
Disabled clipboard feature and now build finishes without error.

**Comment by timvisee** [comment]
@xeffyr Good to hear. I don't think it to be properly supported on Android anyway.
