### ISSUE TITLE
termux.org is blocking tor

### ISSUE THREAD

**Issue by infinity0** [termux/termux-packages#4555]
Hi, termux.org is blocking tor when I use `pkg`. It works when I use a non-tor VPN. I'm not sure if this is your CDN's fault but the major linux distros do not block Tor, I don't see why Termux should be blocking it.

**Comment by xeffyr** [comment]
Will look on that.

**Comment by xeffyr** [comment]
Tor is now whitelisted for `termux.org`.

**Comment by infinity0** [comment]
Thanks for taking a look, but it seems it's still blocked:

~~~~
$ torsocks wget https://termux.org/packages
--2019-11-17 21:57:22--  https://termux.org/packages
Resolving termux.org (termux.org)... 104.31.90.132
Connecting to termux.org (termux.org)|104.31.90.132|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-11-17 21:57:23 ERROR 403: Forbidden.

exit code 8
~~~~

`pkg install nano` on my termux also reports 403.

**Comment by xeffyr** [comment]
If access to URLs like
```
https://dl.bintray.com/termux/termux-packages-24/aarch64/tor_0.4.1.6_aarch64.deb
```
is blocked, then nothing can be done. We cannot modify access policy of [Bintray's](https://bintray.com) servers.

**Comment by infinity0** [comment]
dl.bintray.com is fine, it is termux.org that is giving back the 403. You can see in the wget output above it gives 403 back before redirecting to dl.bintray.com. If I `torsocks wget` the bintray address directly, it works fine. But `pkg` goes through `termux.org`.

**Comment by xeffyr** [comment]
Try now.

**Comment by infinity0** [comment]
Works great now, thanks!
