### ISSUE TITLE
python pip: module 'os' has no attribute 'link'

### ISSUE THREAD

**Issue by landfillbaby** [termux/termux-packages#4557]
**Problem description**
pip tries to access os.link but errors out

**Steps to reproduce**
pip list

**Expected behavior**
list of installed python packages

**Additional information**

    Packages CPU architecture:
    aarch64
    Subscribed repositories:
    # sources.list
    deb https://termux.org/packages/ stable main
    Updatable packages:
    All packages up to date
    Android version:
    9
    Kernel build information:
    Linux localhost 4.4.111-16572992 #1 SMP PREEMPT Tue Oct 8 17:53:01 KST 2019 aarch64 Android
    Device manufacturer:
    samsung
    Device model:
    SM-A530F

**Comment by landfillbaby** [comment]
ok so, more specifically it's actually pathlib

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/ce4e1b56c35988a51bcbdcf96acb1e6056066fca.
