### ISSUE TITLE
python: can no longer install numpy via pip

### ISSUE THREAD

**Issue by landfillbaby** [termux/termux-packages#4562]
**Problem description**
`pip install numpy` fails due to #570
also applies to several other previously installable pypi packages, but notably not Pillow, which compiles fine
**Additional information**

    Packages CPU architecture:
    aarch64
    Subscribed repositories:
    # sources.list
    deb https://termux.org/packages/ stable main
    Updatable packages:
    All packages up to date
    Android version:
    9
    Kernel build information:
    Linux localhost 4.4.111-16572992 #1 SMP PREEMPT Tue Oct 8 17:53:01 KST 2019 aarch64 Android
    Device manufacturer:
    samsung
    Device model:
    SM-A530F

**Comment by Grimler91** [comment]
Thanks for the information. Numpy (and scipy) are installable from [its-pointless repo](https://wiki.termux.com/wiki/Package_Management#By_its-pointless_.28live_the_dream.29:) (though the packages there are probably not updated for python3.8 yet), if numpy needs to be patched then such a patch will be included in the package from that repo.

**Comment by its-pointless** [comment]
What is occuring is a change in how python deals with build threads. It detects 4 cpu so uses 4 threads so 4 different processes of clang compiling.  In 3.8 its now using multiprocessing module for that. Multiprocessing in python needs semaphore which aren't available in android libc. So can only use 1 thread when compiling python modules.

**Comment by stonegz** [comment]
is it possible to downgrade python to 3.7 or 3.6?

thanks
stone

**Comment by its-pointless** [comment]
Editing /data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py so its only ever one thread should do the trick. Make processes always equal one. i will get a patch or something working.

**Comment by its-pointless** [comment]
#4567 should fix this but needs to be tested

**Comment by yubrajbhoi** [comment]
Here is a workaround: unzip Numpy source code and build using this command: `python setup.py build -j 1 install`. This will only use one core so it's slow. But it works.

**Comment by T4Tea** [comment]
> Here is a workaround: unzip Numpy source code and build using this command: `python setup.py build -j 1 install`. This will only use one core so it's slow. But it works.

It works for me. Thanks!

**Comment by xeffyr** [comment]
Closing as https://github.com/termux/termux-packages/commit/e54d8445f8788cef4858638bcf7046d27b2d3b8c fixes building modules (verified with `pip install numpy`) - generally it is equivalent to `... build -j 1 install`.

**Comment by KnowingNothing** [comment]
The newest termux only provides python 3.9.0, but `pkg install numpy` only install numpy for python 3.8. Is there any way to get numpy for python 3.9 or downgrade python to 3.8 (no additional build from source)?

**Comment by xeffyr** [comment]
> Is there any way to get numpy for python 3.9

https://github.com/its-pointless/its-pointless.github.io is a third-party repo. You need to wait until @its-pointless will recompile it for recent python.

> downgrade python to 3.8 (no additional build from source)

We do not provide older versions of packages. You have only one way to get it - build from source.

**Comment by KnowingNothing** [comment]
Thanks.
