### ISSUE TITLE
vim-python 8.1.2200 does not actually have python support

### ISSUE THREAD

**Issue by Viqsi** [termux/termux-packages#4563]
Both the 'vim' and 'vim-python' packages, as of 8.1.2200 (possibly earlier versions, although I am not in a position to test these), provide a `vim` binary that lacks compiled-in support for python scripts. This is entirely expected for the 'vim' package, but the 'vim-python' package advertises having said support built in.

**Steps to reproduce**
`apt install vim-python`
`vim`
enter the vim command `:version`

Alternatively, one may run `vim` (after installing vim-python) and attempt to run any vim script that incorporates python.

**Expected behavior**
A long list of included features that includes one or both of "+python" or "+python3" (as opposed to both "-python" and "-python3", indicating that these features are not present)

(Alternatively, one may expect any vim script that incorporates python to execute, instead of exiting with errors complaining that Vim has not been compiled with python support.)

**Additional information**
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
8.0.0
Kernel build information:
Linux localhost 4.4.111-13688770-QB21336176 #1 SMP PREEMPT Wed Jan 2 12:10:53 KST 2019 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N950F
```

**Comment by Viqsi** [comment]
Some versioning clarification and additional information - the affected version is 8.1.2200-1. I didn't notice at first that there was a separate 8.1.2200 with no package version suffix (I'm used to Debian's habit of always having that suffix). 8.1.2200 was evidently compiled against Python 3.7 as opposed to 3.8; attempting to install and run that older version fails because the Python 3.7 libraries are not present on my phone (nor can I install them). This suggests to me that the problem is in the changeover from Python 3.7 to 3.8.

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/6a8a7fe8661a6c6bf4e159c6d161ef9662f2038d.
