### ISSUE TITLE
php date() prints time in UTC

### ISSUE THREAD

**Issue by erig123** [termux/termux-packages#4565]
**Problem description**
the output of date() is one hour late

**Steps to reproduce**
echo '<?php $d=date("G.i"); echo "$d\n"; ?>' | php

**Expected behavior**
print the local time

**Additional information**
php/stable,now 7.3.10 arm

localhost: termux-info
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.4.113-lineageos-g31d25d7 #1 SMP PREEMPT Fri May 18 14:39:45 CEST 2018 armv7l Android
Device manufacturer:
samsung
Device model:
SM-G900F

**Comment by xeffyr** [comment]
It seems prints date in UTC:
![Screenshot_20191208-210825_Termux](https://user-images.githubusercontent.com/25881154/70394579-16514080-19ff-11ea-89e3-010d0eb0c9be.jpg)

**Comment by xtkoba** [comment]
Just that `date` in PHP does not respect OS timezone settings. You should explicitly set `date.timezone` to the desired value in `php.ini`.

**Comment by xtkoba** [comment]
The same on GNU/Linux (with PHP 8.2.3 (cli)). Not our issue.
