### ISSUE TITLE
Update RGBDS to 0.3.9

### ISSUE THREAD

**Issue by sonic65101** [termux/termux-packages#4573]
The current available version in Termux is 0.3.8-2. The most recent version is 0.3.9 .
**Package description**
Game Boy development system. Older version already available in Termux.
**Link to home page and sources**
1. Home page:
https://rednex.github.io/rgbds/
2. Source code:
https://github.com/rednex/rgbds

**Additional information**
Have you compiled or tried to compile the package on device? 
Yes.
* If it didn't work then please provide the error you ran into:
Compiled executable was in ELF format, not Debian. dpkg couldn't install it.

**Comment by fornwall** [comment]
Hello and thanks for reporting the issue!

The package has now been updated - run `pkg up` to update!
