### ISSUE TITLE
Termux ubuntu not working on android

### ISSUE THREAD

**Issue by smrutiranjanbihari** [termux/termux-packages#4575]
Ubuntu installed successfully but not starting

Commands below:

cd termux-ubuntu
$ ls
README.md  start-ubuntu.sh  ubuntu.sh
binds      ubuntu-fs        ubuntu.tar.gz
$ start-ubuntu.sh
start-ubuntu.sh: command not found
$ ./start-ubuntu.sh
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 20229
groups: cannot find name for group ID 50229
root@localhost:~#

**Comment by xeffyr** [comment]
I see no issues here.
```
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 20229
groups: cannot find name for group ID 50229
```
Is expected behaviour.
