### ISSUE TITLE
Problem on Creating MTPROTO proxy

### ISSUE THREAD

**Issue by AliGarshasbi** [termux/termux-packages#4578]
![Screenshot_20191122-132626_Termux](https://user-images.githubusercontent.com/58054640/69486638-124feb00-0e63-11ea-9d31-b1f314f4ef40.jpg)

Anyone knows what's the problem and why This Error happens ?
Please help me😭😭

**Comment by xeffyr** [comment]
>  why This Error happens ?

It happens because someone who wrote mtproto stuff assumed that code will be execute on Intel Core2 CPU (weird from portability side btw).

This is not a Termux issue as source code should be fixed instead.
