### ISSUE TITLE
geckodriver

### ISSUE THREAD

**Issue by kyawgyi27** [termux/termux-packages#4579]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
Can you explain for what you use geckodriver in Termux ?
Its quite useless without `firefox` package and I have deleted it recently.

**Comment by xeffyr** [comment]
If you need it just because "some script requires it", I will close this issue without adding the package.
