### ISSUE TITLE
Package request: isync mbsync

### ISSUE THREAD

**Issue by gvrajesh** [termux/termux-packages#458]
It will be great if "isync" package is added. Thanks.

**Comment by ayatakesi** [comment]
Hi. I have just installed isync-1.3.0 from source tarball on Termux. Is there a way to make my work useful for creating packages?

**Comment by Grimler91** [comment]
@ayatakesi If you have access to a linux workstation, then you could follow the steps in the [termux-packages readme](https://github.com/termux/termux-packages/blob/master/README.md) and setup a cross-compilation environment and then create a build.sh for isync and then open a pull request to the repo. See for example [subversion/build.sh](https://github.com/termux/termux-packages/blob/master/packages/subversion/build.sh) for a simple build.sh script.

If you had to patch the source in anyway then those patches would be useful for anyone else trying to create a build.sh for isync.

**Comment by xeffyr** [comment]
Package "isync" is already available.
```
pkg install isync
```
