### ISSUE TITLE
X11 Missing fonts after installing aterm.

### ISSUE THREAD

**Issue by Mishqutin** [termux/termux-packages#4593]
![pic](https://user-images.githubusercontent.com/25058705/69666685-ed3ec080-108c-11ea-9a0b-bb742218728d.png)
This is my Openbox right click menu after installing aterm package.
This is what aterm package also installs:
`fontconfig-utils xorg-font-util
  xorg-fonts-75dpi xorg-fonts-alias
  xorg-fonts-encodings
  xorg-mkfontscale`
When I remove aterm and do `apt autoremove` which removes above packages fonts come back to normal.

**Comment by xeffyr** [comment]
```
pkg install ttf-dejavu
```

**Comment by Mishqutin** [comment]
Thanks
