### ISSUE TITLE
make/asciidoc/rsync breaking when running make?

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#4595]
**Problem description**
When trying to run make in order to build documentation, I get the following error:

`$ make

asciidoc knownissues20.txt
asciidoc manual.pl.txt
asciidoc knownissues21.txt
asciidoc AnkiMobile.txt
asciidoc addons20.txt
asciidoc addons.txt
asciidoc changes.txt
asciidoc manual20.txt
asciidoc help.txt
asciidoc manual.es.txt
asciidoc beta.txt
asciidoc am-manual.txt
asciidoc manual.id.txt
asciidoc manual.fr.txt
asciidoc manual.txt
asciidoc am-upgrade.txt
building mako
rsync: link_stat "/data/data/com.termux/files/home/ankidocs/*.html" failed: No such file or directory (2)
rsync: mkdir "/docs" failed: Read-only file system (30)
rsync error: error in file IO (code 11) at /home/builder/.termux-build/rsync/src/main.c(664) [Receiver=3.1.3]
make: *** [Makefile:22: build] Error 11
`
It looks like it's trying to make a directory in the root of the android filesystem, which is readonly

**Steps to reproduce**
1. git clone this repo https://github.com/dae/ankidocs
2. cd into the repo
3. run make (make and asciidoc need to be installed) 

**Expected behavior**
the docs should be built / asciidoc should convert the txt files to html

**Additional information**

Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g606096e-dirty #1 SMP PREEMPT Tue Jan 17 18:10:20 KST 2017 armv7l Android
Device manufacturer:
LGE
Device model:
LGL84VL

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
This is not the Termux issue.
Problem comes from https://github.com/dae/ankidocs/blob/master/Makefile#L11:
```
rsync -a img $(WEB)/docs/
```

Variable `$(WEB)` expands to nothing due to `${appsweb}` being not set (see Makefile's beginning).
