### ISSUE TITLE
HUAWEI Mate 10 lite, Ubuntu from termux and sound support from Ubuntu

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-packages#4598]
Dear specialists,
I have tested Pulseaudio from Termux by using MPV player. When I have used it from Termux, sound have been excellent. I could play even with screen turned off for A long time without issues.
But When I have installed Ubuntu to termux by using Ubuntu for Termux script
https://github.com/MFDGaming/ubuntu-in-termux
I can not listen to The Espeak speech output when Pulseaudio running in Termux listen TCP packets from Ubuntu, which also run from Termux by using Proot module.
I have used The following command to initiate Pulseaudio listening on The site of Termux.
apt install pulseaudio
apt install sox

pulseaudio --start --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1auth-anonymous=1
And Ubuntu had The following variable exported.
echo "export PULSE_SERVER=\"127.0.0.1\"" >> ~/.bashrc
I have logged out and I have login again to get changes.
I have also simply exported without using bash script.
But simply, Espeak do not produce speech.
HUAWEI Mate 10 lite uses Android version 7.0.
I Am using Termux stable.
So from termux, Pulseaudio work perfectly when mpv player is being used.
But sound do not work from Ubuntu.
Really, implementation of Pulseaudio for Termux is still The best approach. Sound is clear and soft. But I Am afraid, that included kernel modified by Huavei contain some protection which denie TCP communication between apps. Or may be, that it is real time kernel protection, I do not know, what could it be.

**Comment by xeffyr** [comment]
It works, I have just tried it.
Double check your commands for typos as you have a missed space typo in your `pacmd` command.

Nothing to do with kernel & Android restrictions.

**Comment by JanuszChmiel** [comment]
Please, would you be so kind and would you write The correct line for Me?
I do not know, where I have forgotten The space. Please! ANd I Am very very sorry for my redundand post.
I was afraid, that it is problem with Kernel, because Userland can not successfully extract file system, Termux Debian script can not load crucial shared library with .so extension and it work with my Lenovo tablet with Android 6.0. So I have been afraid, that it is some hydden kernel problem.

**Comment by xeffyr** [comment]
In Termux:
```
pulseaudio --start --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
```

In Ubuntu:
```
echo "export PULSE_SERVER=127.0.0.1" >> ~/.bashrc
```
Then `source ~/.bashrc`.
