### ISSUE TITLE
Package request: PHP

### ISSUE THREAD

**Issue by aspyct** [termux/termux-packages#46]
Hi,

Awesome work you did with termux, I really love it! I'm gonna go away for three months, and an android tablet is all I take with me (and a bt keyboard!). I'm pretty sure in 3 months time I'll want to program, so hey, termux really is perfect for me :)

One thing I'd love is to see PHP arrive, including binding to SQLite 3 (php pdo sqlite) and the built-in webserver (available since PHP 5.4 I believe). I tried to build it on the tablet, but I ran into problems with shebang and stuff...

**Comment by fornwall** [comment]
Thanks for the suggestion, I've added a php package now (install with `apt update && apt install php`)!

It's not heavily tested, but I verified that the built-in webserver and sqlite access worked. Let me know how it works for you!

**Comment by aspyct** [comment]
Holy cow, that was quick!

I'll have a look at it today :) Thanks!

**Comment by aspyct** [comment]
Works like a charm! Thanks a zillion!

**Comment by Rajib311** [comment]
Thank you.. Working triks

**Comment by Rockkingston** [comment]
can some one explain me please how i can install php pkg in termux i did try all over world 
but cant able to install pkg php in termux

**Comment by MrAdityaAlok** [comment]
@Rockkingston did you try this `pkg install php` ?
