### ISSUE TITLE
libgcrypt  dependencies    gpgv  ??

### ISSUE THREAD

**Issue by CMingTseng** [termux/termux-packages#4603]
Dear Sir i want build our Prefix package

first i need build basic deb files to create bootstrap file

1 month ago i pass

but   now  i get  error

when run generate-bootstraps.sh

the error message show 

[*] Extracting 'libgcrypt'...
[*] Downloading 'gpgv'...
[*] package.deb Downloading 'gpgv'...
 
Yes .  something different !!

 i can not found gpgv package !!

i use ./build-package -a xx gpgv 

can not found any gpgv folder !!

THX

**Comment by xeffyr** [comment]
gpgv is part of gnupg package.
