### ISSUE TITLE
GSettings: No schemas installed

### ISSUE THREAD

**Issue by YanLiudchyk** [termux/termux-packages#4608]
**Problem description**
GSettings can't find installed schemas.
```
$ gsettings list-schemas
No schemas installed
```
I already tried running `glib-compile-schemas /data/data/com.termux/files/usr/share/glib-2.0/schemas`

**Steps to reproduce**
Run `gsettings list-schemas`

**Expected behavior**
GSettings should return all installed schemas

**Additional information**
```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.18.120-17009941 #2 SMP PREEMPT Fri Oct 4 22:02:21 KST 2019 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A605FN
```
[logcat.log](https://github.com/termux/termux-packages/files/3907488/logcat.log)
[strace.log](https://github.com/termux/termux-packages/files/3907489/strace.log)

**Comment by xeffyr** [comment]
Closing as **unreproducible**.
Check the content of directory
```
/data/data/com.termux/files/usr/share/glib-2.0/schemas
```
and make sure that something is available here.

![Screenshot_20191130-222743_Termux](https://user-images.githubusercontent.com/25881154/69905749-c8b25380-13c0-11ea-9ce0-3ce9ea366f37.jpg)
