### ISSUE TITLE
Error in "python3" or "pip"

### ISSUE THREAD

**Issue by torerobo** [termux/termux-packages#4610]
I tried to set "[Sherlock](https://github.com/sherlock-project/sherlock/)" to "Termux".  I used the standard 
"`python3 -m pip install -r requirements.txt`" (disconnected from the Internet, did it again).  Compilation Error ([LOG](https://pastebin.com/LLJpXJAM)).  This problem was also confirmed [here](https://github.com/sherlock-project/sherlock/issues/387).

**Comment by xeffyr** [comment]
Install libcrypt. Also make sure that **all packages are up-to-date**.
