### ISSUE TITLE
undefined reference to `__android_log_print'

### ISSUE THREAD

**Issue by frink** [termux/termux-packages#4611]
**Problem description**
Looks like compiling with Android via clang puts a shim in place for syslog. It's looking for liblog. But I cannot find the path to liblog nor an installation pkg. This seems to be something that is Android specific and well known and easy to fix. But I've tried everything I can think of... Any ideas? 

**Steps to reproduce**
compile something with syslog() calls

**Expected behavior**
Should compile fine...

**Additional information**
Post output of command `termux-info`.
```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
7.1.1
Kernel build information:
Linux localhost 3.14.0 #1 SMP PREEMPT Thu Nov 14 23:13:12 PST 2019 armv7l Android
Device manufacturer:
google
Device model:
ASUS Chromebook Flip C100PA
```

**Comment by Grimler91** [comment]
The library is in /system/lib. Add `-llog` to LDFLAGS and it will compile fine. It is done for quite a lot of packages: https://github.com/termux/termux-packages/search?q=%22-llog%22

**Comment by frink** [comment]
I'm still having some problems with it. I'm going to check my tooling and just compile a test without make.. Thanks.

**Comment by frink** [comment]
Any clue how to make this work with cmake...? Libwebsockets has a hellofa CMakeLists.txt  and nothing I do seems to be working! ~ Thanks.

**Comment by Grimler91** [comment]
Hm, yeah, it's a bit more complicated for a CMakeLists.txt. You probably need to patch it and add 
`target_link_libraries(binary-or-library-using-the-log-stuff -llog)` 
for the executable(s) or library(ies) that need the log functions. Might also already be an target_link_libraries for that specific exe/lib and you can then change it from 
`target_link_libraries(foo -lbar)` to `target_link_libraries(foo -lbar -llog)`.

**Comment by frink** [comment]
Thanks. I'll check into that...

**Comment by Grimler91** [comment]
`export LDFLAGS=" -llog"` should probably work though, that's what we do in https://github.com/termux/termux-packages/blob/master/packages/libwebsockets/build.sh

**Comment by frink** [comment]
I'm not familiar with the Termux package/build system. Couldn't find good docs on it. Is termux_step_pre_configure called before cmake or make or are you sidestepping cmake altogether?

**Comment by frink** [comment]
Running `export LDFLAGS=" -llog"` before the cmake solved the problem. THanks.

**Comment by Grimler91** [comment]
> I'm not familiar with the Termux package/build system. Couldn't find good docs on it. Is termux_step_pre_configure called before cmake or make or are you sidestepping cmake altogether?

Yes, configuring means either running `./configure`, `cmake .`, or some other variant, so pre_configure is run before cmake. 

The build system is pretty thoroughly described in https://github.com/termux/termux-packages/wiki/Building-packages
