### ISSUE TITLE
Pylint throws an error when evaluating import packages.

### ISSUE THREAD

**Issue by Fernal73** [termux/termux-packages#4612]
https://github.com/PyCQA/pylint/issues/3270

**Comment by Grimler91** [comment]
Please use the [bug report template](https://github.com/termux/termux-packages/issues/new?template=bug_report.md). How can I reproduce the issue?

**Comment by Fernal73** [comment]
All you have to do is run pylint against namedtuple.py to get the error.
The version number for pylint is specified in the referenced bug report.

**Comment by Grimler91** [comment]
I don't get any error on my aarch64 device. So, again, please use the bug report template and provide the requested information, like the output of `termux-info`.

**Comment by Fernal73** [comment]
Output of termux-info:

Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# sources.list.d/pointless.bak
deb https://its-pointless.github.io/files/ termux extras
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.18.31-perf-g89c85bf #1 SMP PREEMPT Tue Oct 22 13:55:14
WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Y1

If you still need the rest, you will have to wait since I'll have to
re-collate and aggregate the information and then put it in the desired
format. All this from my phone.

**Comment by xeffyr** [comment]
No errors, at all:

![Screenshot_20191202-132944_Termux](https://user-images.githubusercontent.com/25881154/69956225-14bbe000-1508-11ea-818e-71fe17b67bb4.jpg)

Since my CPU arch and repo versions same as yours, I guess problem is either in device or your Termux installation. Otherwise bug will be reproducible on all devices with similar properties.

**Comment by Fernal73** [comment]
That's no good at all.

This is my .pylintrc file:

[MASTER]

# A comma-separated list of package or module names from where C extensions
may
# be loaded. Extensions are loading into the active Python interpreter and
may
# run arbitrary code.
extension-pkg-whitelist=

# Add files or directories to the blacklist. They should be base names, not
# paths.
ignore=CVS

# Add files or directories matching the regex patterns to the blacklist. The
# regex matches against base names, not paths.
ignore-patterns=

# Python code to execute, usually for sys.path manipulation such as
# pygtk.require().
#init-hook=

# Use multiple processes to speed up Pylint. Specifying 0 will auto-detect
the
# number of processors available to use.
jobs=1

# Control the amount of potential inferred values when inferring a single
# object. This can help the performance when dealing with large functions or
# complex, nested conditions.
limit-inference-results=100

# List of plugins (as comma separated values of python modules names) to
load,
# usually to register additional checkers.
load-plugins=

# Pickle collected data for later comparisons.
persistent=yes

# Specify a configuration file.
#rcfile=

# When enabled, pylint would attempt to guess common misconfiguration and
emit
# user-friendly hints instead of false-positive error messages.
suggestion-mode=yes

# Allow loading of arbitrary C extensions. Extensions are imported into the
# active Python interpreter and may run arbitrary code.
unsafe-load-any-extension=no


[MESSAGES CONTROL]

# Only show warnings with the listed confidence levels. Leave empty to show
# all. Valid levels: HIGH, INFERENCE, INFERENCE_FAILURE, UNDEFINED.
confidence=

# Disable the message, report, category or checker with the given id(s). You
# can either give multiple identifiers separated by comma (,) or put this
# option multiple times (only on the command line, not in the configuration
# file where it should appear only once). You can also use "--disable=all"
to
# disable everything first and then reenable specific checks. For example,
if
# you want to run only the similarities checker, you can use "--disable=all
# --enable=similarities". If you want to run only the classes checker, but
have
# no Warning level messages displayed, use "--disable=all --enable=classes
# --disable=W".
disable=print-statement,
        parameter-unpacking,
        unpacking-in-except,
        old-raise-syntax,
        backtick,
        long-suffix,
        old-ne-operator,
        old-octal-literal,
        import-star-module-level,
        non-ascii-bytes-literal,
        raw-checker-failed,
        bad-inline-option,
        locally-disabled,
        file-ignored,
        suppressed-message,
        useless-suppression,
        deprecated-pragma,
        use-symbolic-message-instead,
        apply-builtin,
        basestring-builtin,
        buffer-builtin,
        cmp-builtin,
        coerce-builtin,
        execfile-builtin,
        file-builtin,
        long-builtin,
        raw_input-builtin,
        reduce-builtin,
        standarderror-builtin,
        unicode-builtin,
        xrange-builtin,
        coerce-method,
        delslice-method,
        getslice-method,
        setslice-method,
        no-absolute-import,
        old-division,
        dict-iter-method,
        dict-view-method,
        next-method-called,
        metaclass-assignment,
        indexing-exception,
        raising-string,
        reload-builtin,
        oct-method,
        hex-method,
        nonzero-method,
        cmp-method,
        input-builtin,
        round-builtin,
        intern-builtin,
        unichr-builtin,
        map-builtin-not-iterating,
        zip-builtin-not-iterating,
        range-builtin-not-iterating,
        filter-builtin-not-iterating,
        using-cmp-argument,
        eq-without-hash,
        div-method,
        idiv-method,
        rdiv-method,
        exception-message-attribute,
        invalid-str-codec,
        sys-max-int,
        bad-python3-import,
        deprecated-string-function,
        deprecated-str-translate-call,
        deprecated-itertools-function,
        deprecated-types-field,
        next-method-defined,
        dict-items-not-iterating,
        dict-keys-not-iterating,
        dict-values-not-iterating,
        deprecated-operator-function,
        deprecated-urllib-function,
        xreadlines-attribute,
        deprecated-sys-function,
        exception-escape,
        comprehension-escape
# syntax-error

# Enable the message, report, category or checker with the given id(s). You
can
# either give multiple identifier separated by comma (,) or put this option
# multiple time (only on the command line, not in the configuration file
where
# it should appear only once). See also the "--disable" option for examples.
enable=c-extension-no-member


[REPORTS]

# Python expression which should return a note less than 10 (10 is the
highest
# note). You have access to the variables errors warning, statement which
# respectively contain the number of errors / warnings messages and the
total
# number of statements analyzed. This is used by the global evaluation
report
# (RP0004).
evaluation=10.0 - ((float(5 * error + warning + refactor + convention) /
statement) * 10)

# Template used to display messages. This is a python new-style format
string
# used to format the message information. See doc for all details.
#msg-template=

# Set the output format. Available formats are text, parseable, colorized,
json
# and msvs (visual studio). You can also give a reporter class, e.g.
# mypackage.mymodule.MyReporterClass.
output-format=text

# Tells whether to display a full report or only the messages.
reports=no

# Activate the evaluation score.
score=yes


[REFACTORING]

# Maximum number of nested blocks for function / method body
max-nested-blocks=5

# Complete name of functions that never returns. When checking for
# inconsistent-return-statements if a never returning function is called
then
# it will be considered as an explicit return statement and no message will
be
# printed.
never-returning-functions=sys.exit


[BASIC]

# Naming style matching correct argument names.
argument-naming-style=snake_case

# Regular expression matching correct argument names. Overrides argument-
# naming-style.
#argument-rgx=

# Naming style matching correct attribute names.
attr-naming-style=snake_case

# Regular expression matching correct attribute names. Overrides
attr-naming-
# style.
#attr-rgx=

# Bad variable names which should always be refused, separated by a comma.
bad-names=foo,
          bar,
          baz,
          toto,
          tutu,
          tata

# Naming style matching correct class attribute names.
class-attribute-naming-style=any

# Regular expression matching correct class attribute names. Overrides
class-
# attribute-naming-style.
#class-attribute-rgx=

# Naming style matching correct class names.
class-naming-style=PascalCase

# Regular expression matching correct class names. Overrides class-naming-
# style.
#class-rgx=

# Naming style matching correct constant names.
const-naming-style=UPPER_CASE

# Regular expression matching correct constant names. Overrides
const-naming-
# style.
#const-rgx=

# Minimum line length for functions/classes that require docstrings, shorter
# ones are exempt.
docstring-min-length=-1

# Naming style matching correct function names.
function-naming-style=snake_case

# Regular expression matching correct function names. Overrides function-
# naming-style.
#function-rgx=

# Good variable names which should always be accepted, separated by a comma.
good-names=i,
           j,
           k,
           ex,
           Run,
           _

# Include a hint for the correct naming format with invalid-name.
include-naming-hint=no

# Naming style matching correct inline iteration names.
inlinevar-naming-style=any

# Regular expression matching correct inline iteration names. Overrides
# inlinevar-naming-style.
#inlinevar-rgx=

# Naming style matching correct method names.
method-naming-style=snake_case

# Regular expression matching correct method names. Overrides method-naming-
# style.
#method-rgx=

# Naming style matching correct module names.
module-naming-style=snake_case

# Regular expression matching correct module names. Overrides module-naming-
# style.
#module-rgx=

# Colon-delimited sets of names that determine each other's naming style
when
# the name regexes allow several styles.
name-group=

# Regular expression which should only match function or class names that do
# not require a docstring.
no-docstring-rgx=^_

# List of decorators that produce properties, such as abc.abstractproperty.
Add
# to this list to register other decorators that produce valid properties.
# These decorators are taken in consideration only for invalid-name.
property-classes=abc.abstractproperty

# Naming style matching correct variable names.
variable-naming-style=snake_case

# Regular expression matching correct variable names. Overrides variable-
# naming-style.
#variable-rgx=


[FORMAT]

# Expected format of line ending, e.g. empty (any line ending), LF or CRLF.
expected-line-ending-format=

# Regexp for a line that is allowed to be longer than the limit.
ignore-long-lines=^\s*(# )?<?https?://\S+>?$

# Number of spaces of indent required inside a hanging or continued line.
indent-after-paren=4

# String used as indentation unit. This is usually "    " (4 spaces) or
"\t" (1
# tab).
indent-string='    '

# Maximum number of characters on a single line.
max-line-length=80

# Maximum number of lines in a module.
max-module-lines=1000

# List of optional constructs for which whitespace checking is disabled.
`dict-
# separator` is used to allow tabulation in dicts, etc.: {1  : 1,\n222: 2}.
# `trailing-comma` allows a space between comma and closing bracket: (a, ).
# `empty-line` allows space-only lines.
no-space-check=trailing-comma,
               dict-separator

# Allow the body of a class to be on the same line as the declaration if
body
# contains single statement.
single-line-class-stmt=no

# Allow the body of an if to be on the same line as the test if there is no
# else.
single-line-if-stmt=no


[LOGGING]

# Format style used to check logging format string. `old` means using %
# formatting, while `new` is for `{}` formatting.
logging-format-style=old

# Logging modules to check that the string format arguments are in logging
# function parameter format.
logging-modules=logging


[MISCELLANEOUS]

# List of note tags to take in consideration, separated by a comma.
notes=FIXME,
      XXX,
      TODO


[SIMILARITIES]

# Ignore comments when computing similarities.
ignore-comments=yes

# Ignore docstrings when computing similarities.
ignore-docstrings=yes

# Ignore imports when computing similarities.
ignore-imports=no

# Minimum lines number of a similarity.
min-similarity-lines=4


[SPELLING]

# Limits count of emitted suggestions for spelling mistakes.
max-spelling-suggestions=4

# Spelling dictionary name. Available dictionaries: none. To make it working
# install python-enchant package..
spelling-dict=

# List of comma separated words that should not be checked.
spelling-ignore-words=

# A path to a file that contains private dictionary; one word per line.
spelling-private-dict-file=

# Tells whether to store unknown words to indicated private dictionary in
# --spelling-private-dict-file option instead of raising a message.
spelling-store-unknown-words=no


[STRING]

# This flag controls whether the implicit-str-concat-in-sequence should
# generate a warning on implicit string concatenation in sequences defined
over
# several lines.
check-str-concat-over-line-jumps=no


[TYPECHECK]

# List of decorators that produce context managers, such as
# contextlib.contextmanager. Add to this list to register other decorators
that
# produce valid context managers.
contextmanager-decorators=contextlib.contextmanager

# List of members which are set dynamically and missed by pylint inference
# system, and so shouldn't trigger E1101 when accessed. Python regular
# expressions are accepted.
generated-members=

# Tells whether missing members accessed in mixin class should be ignored. A
# mixin class is detected if its name ends with "mixin" (case insensitive).
ignore-mixin-members=yes

# Tells whether to warn about missing members when the owner of the
attribute
# is inferred to be None.
ignore-none=yes

# This flag controls whether pylint should warn about no-member and similar
# checks whenever an opaque object is returned when inferring. The inference
# can return multiple potential results while evaluating a Python object,
but
# some branches might not be evaluated, which results in partial inference.
In
# that case, it might be useful to still emit no-member and other checks for
# the rest of the inferred objects.
ignore-on-opaque-inference=yes

# List of class names for which member attributes should not be checked
(useful
# for classes with dynamically set attributes). This supports the use of
# qualified names.
ignored-classes=optparse.Values,thread._local,_thread._local

# List of module names for which member attributes should not be checked
# (useful for modules/projects where namespaces are manipulated during
runtime
# and thus existing member attributes cannot be deduced by static analysis.
It
# supports qualified module names, as well as Unix pattern matching.
ignored-modules=

# Show a hint with possible names when a member name was not found. The
aspect
# of finding the hint is based on edit distance.
missing-member-hint=yes

# The minimum edit distance a name should have in order to be considered a
# similar match for a missing member name.
missing-member-hint-distance=1

# The total number of similar names that should be taken in consideration
when
# showing a hint for a missing member.
missing-member-max-choices=1


[VARIABLES]

# List of additional names supposed to be defined in builtins. Remember that
# you should avoid defining new builtins when possible.
additional-builtins=

# Tells whether unused global variables should be treated as a violation.
allow-global-unused-variables=yes

# List of strings which can identify a callback function by name. A callback
# name must start or end with one of those strings.
callbacks=cb_,
          _cb

# A regular expression matching the name of dummy variables (i.e. expected
to
# not be used).
dummy-variables-rgx=_+$|(_[a-zA-Z0-9_]*[a-zA-Z0-9]+?$)|dummy|^ignored_|^unused_

# Argument names that match this expression will be ignored. Default to name
# with leading underscore.
ignored-argument-names=_.*|^ignored_|^unused_

# Tells whether we should check for unused import in __init__ files.
init-import=no

# List of qualified module names which can have objects that can redefine
# builtins.
redefining-builtins-modules=six.moves,past.builtins,future.builtins,builtins,io


[CLASSES]

# List of method names used to declare (i.e. assign) instance attributes.
defining-attr-methods=__init__,
                      __new__,
                      setUp

# List of member names, which should be excluded from the protected access
# warning.
exclude-protected=_asdict,
                  _fields,
                  _replace,
                  _source,
                  _make

# List of valid names for the first argument in a class method.
valid-classmethod-first-arg=cls

# List of valid names for the first argument in a metaclass class method.
valid-metaclass-classmethod-first-arg=cls


[DESIGN]

# Maximum number of arguments for function / method.
max-args=5

# Maximum number of attributes for a class (see R0902).
max-attributes=7

# Maximum number of boolean expressions in an if statement.
max-bool-expr=5

# Maximum number of branch for function / method body.
max-branches=12

# Maximum number of locals for function / method body.
max-locals=15

# Maximum number of parents for a class (see R0901).
max-parents=7

# Maximum number of public methods for a class (see R0904).
max-public-methods=20

# Maximum number of return / yield for function / method body.
max-returns=6

# Maximum number of statements in function / method body.
max-statements=50

# Minimum number of public methods for a class (see R0903).
min-public-methods=2


[IMPORTS]

# Allow wildcard imports from modules that define __all__.
allow-wildcard-with-all=no

# Analyse import fallback blocks. This can be used to support both Python 2
and
# 3 compatible code, which means that the block might have code that exists
# only in one or another interpreter, leading to false positives when
analysed.
analyse-fallback-blocks=no

# Deprecated modules which should not be used, separated by a comma.
deprecated-modules=optparse,tkinter.tix

# Create a graph of external dependencies in the given file (report RP0402
must
# not be disabled).
ext-import-graph=

# Create a graph of every (i.e. internal and external) dependencies in the
# given file (report RP0402 must not be disabled).
import-graph=

# Create a graph of internal dependencies in the given file (report RP0402
must
# not be disabled).
int-import-graph=

# Force import order to recognize a module as part of the standard
# compatibility libraries.
known-standard-library=

# Force import order to recognize a module as part of a third party library.
known-third-party=enchant


[EXCEPTIONS]

# Exceptions that will emit a warning when being caught. Defaults to
# "BaseException, Exception".
overgeneral-exceptions=BaseException,
                       Exc

**Comment by xeffyr** [comment]
I suggest you to start checking your configuration file. It is truncated and contains a lot forced line wraps. I'm not surprised that your pylint crashes.

**Comment by xeffyr** [comment]
If you still think that config file is correct, post it here either via attachment or with
```
curl --upload-file ~/.pylintrc https://linx.li/upload/
```

**Comment by Fernal73** [comment]
It's the same file I've been using for a couple of months now. It was
generated via pylint itself. It's not hand-crafted.

https://github.com/Fernal73/LearnPython3/blob/master/.pylintrc

**Comment by xeffyr** [comment]
With pylintrc from https://github.com/Fernal73/LearnPython3/blob/master/.pylintrc it works fine. So config should not be a problem.

**Comment by Fernal73** [comment]
Are you expecting me to debug this?
I'd rather not run pylint instead or revert back to python 3.7.


The closest I can find to this error is this:

https://bugzilla.redhat.com/show_bug.cgi?id=1717653

**Comment by Fernal73** [comment]
There's no fix on my Termux installation. Termux , like ArchLinux, has rolling updates. The only other alternative is to install a previous version via a build script. Do you have instructions for how to install a previous version of Python?

**Comment by xeffyr** [comment]
I did `pip install pylint` in a **clear** Termux installation and it works. Python version is the latest, v3.8.0.

Suggesting to reinstall python modules with `apt purge python && apt install python` (not just `apt install --reinstall`) and `rm -rf ~/.cache` before.

Module versions:
![Screenshot_20191204-152151_Termux](https://user-images.githubusercontent.com/25881154/70145933-dc540780-16a9-11ea-9408-8b284183197c.jpg)

**Comment by Fernal73** [comment]
That worked. Thank you very much.
I tried a reinstallation earlier. That didn't .
I still have the same problem with Arch Linux on Termux, however. I'll try
doing something similar with it as well.

**Comment by Fernal73** [comment]
I reinstalled python on Arch Linux but I had to delete all the packages
from /usr/lib/python3.8 for it to take effect.
Pylint works just fine now.

**Comment by Fernal73** [comment]
On installing prospector via pip , I was able to reproduce the error
importing the modules once more.

**Comment by Fernal73** [comment]
I receive the following error when installing pylint after installing
prospector:


ERROR: prospector 1.1.7 has requirement astroid==2.2.5, but you'll have
astroid 2.3.3 which is incompatible.
ERROR: prospector 1.1.7 has requirement pylint==2.3.1, but you'll have
pylint 2.4.4 which is incompatible.

I then have DistributionNotFound errors while running prospector.

**Comment by Fernal73** [comment]
Kindly reopen the issue this time for Prospector.

**Comment by Grimler91** [comment]
@Fernal73 those error messages are pretty clear, you need to install older versions of astroid and pylint. It has nothing to do with termux

**Comment by Fernal73** [comment]
Thanks, I'd rather wait for a later version of prospector.
Yeah, I wasn't sure about that. There's some time lag before packages are
available on Termux. I've posted to the pylint issue as well.

**Comment by Grimler91** [comment]
Prospector, astroid and pylint are python packages that you install through pip. We don't package or update those, we only deal with the packages that are installable through apt/pkg

**Comment by Fernal73** [comment]
Ok. I wasn't aware of that. When I referred to delayed packages, I was
referring to clang 10 not yet available on Termux. I was considering making
a package request but I'm not coding in C++ at the moment and might not be
able to provide a good enough reason for the Termux maintainers. I use
clang-format as a secondary formatter for java source. That's where I'm
coming from.

**Comment by Grimler91** [comment]
[Clang 10 has not been released](http://releases.llvm.org/), in which distro have you been using it? 

Only way getting it would be to build from git master, and we don't want to rebuild a package on each new commit so we stick to the official releases (or possibly release candidates)

**Comment by Fernal73** [comment]
I'm not using Clang 10 but I always find the Clang 10 documentation first
when I search online.
I'm using whatever's available on Termux and Arch Linux on Termux. I have
no interest in building anything on Termux.

**Comment by Fernal73** [comment]
I've closed the other two issues.

pip install prospector==1.2.0.dev3

Is the solution for now.
