### ISSUE TITLE
wget": cannot locate symbol "__aeabi_idiv0"

### ISSUE THREAD

**Issue by pianoslum** [termux/termux-packages#4615]
I downloaded and installed wget via `pkg install wget` and it won't start because of a linker error:

```
$ termux-info
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 3.4.113-ge13de1d9fed #1 SMP PREEMPT Wed Nov 13 16:22:17 CET 2019 armv7l Android
Device manufacturer:
Sony
Device model:
Xperia Z3 Compact
```

```
$ wget
CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget"... $
```

**Comment by HafizZiq** [comment]
Im facing similar issue with wget things

$ termux-info
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/pointless.list
deb [trusted=yes] https://its-pointless.github.io/files/ termux extras
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.4.113-LolZ-V10 #1 SMP PREEMPT Mon Aug 12 04:01:09 UTC 2019 armv7l Android
Device manufacturer:
samsung
Device model:
SM-N9005
$ wget https://its-pointless.github.io/pointless.gpg
CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__gnu_ldivmod_helper" referenced by "/data/data/com.termux/files/usr/bin/wget"...
$

**Comment by HafizZiq** [comment]
![Screenshot_20191228-125749](https://user-images.githubusercontent.com/46204743/71539075-c74d5a00-2971-11ea-8f11-b50a1497e745.jpg)

**Comment by SebastienKeroack** [comment]
I face this problem using LineageOS 17.
Termux==0.86, Android==10.

**Comment by pianoslum** [comment]
@SebastienKeroack Yes you're right, I should have mentioned that!
I also use Lineage.

**Comment by BlueMax** [comment]
On LOS17 the symbol is missing in `libc.so` and `libart.so`. The Termux buildbot is probably not yet prepared for Android 10 bionic/libc.

As a temporary workaround you can inject a lib providing the symbol:
1) find a lib (printed in red):
```
$ for lib in $(find /system -name \*.so); do if [[ $(nm -g $lib 2>/dev/null | grep __aeabi_idiv0) ]]; then echo -ne "\033[1;31m$lib\033[0m\n"; else echo $lib; fi; done
```
2) inject the lib (in my case `libclang_rt.ubsan_standalone-arm-android.so`):
```
$ LD_PRELOAD=/system/apex/com.android.media.swcodec/lib/libclang_rt.ubsan_standalone-arm-android.so wget
```

**Comment by cbonet-sw** [comment]
I encountered this problem with the error:

`CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget"...`

after upgrading from Android 9 to Android 10.

My solution was rebuilding the wget package from source for Android 10. If it's useful to anyone, the updated wget package is at
https://github.com/cbonet-sw/termux-bits

It got it working for me, and although I've not extensively tested it it worked fine what what I needed to do so far.

I'm new to building package for Termux, so if anyone would like to suggest (i) a more appropriate way of distributing this, or (ii) a way of convincing people that this binary doesn't contain malicious code then please get in touch.

**Comment by zhushuangjian** [comment]
After the phone upgrades Android 10 and runs for 4 to 5 hours, the app will flash back and cannot be restarted. The error message is similar to the following:
![image](https://user-images.githubusercontent.com/59001341/90211275-d3175f00-de22-11ea-8a20-8faeee85940b.png)

**Comment by zhushuangjian** [comment]
After the phone upgrades Android 10 and runs for 4 to 5 hours, the app will flash back and cannot be restarted. The error message is similar to the following:
[logcat.txt](https://github.com/termux/termux-packages/files/5072553/logcat.txt)

**Comment by cbonet-sw** [comment]
This appears (after a quick look) to be unrelated to Termux or indeed the Wget package running under Termux.
[Seems to be an app by company called Kedacom - IP Video, or something? Suggest you look for update to com.kedacom.truetouch.sky app or find an alternative for whatever you need.]

**Comment by pranshuthegamer** [comment]
im having the same symbol issue with clang and other programs

**Comment by pranshuthegamer** [comment]
problem is solved by upgrading using apt

**Comment by xtkoba** [comment]
This should no longer happen (as of 1.77.0 rev 1, built on Feb 7, 2021) now that `__aeabi_idiv0` is not referenced from `bin/wget`:

```
$ readelf -Wa bin/wget | grep __aeabi_idiv0
$
```

And I suppose this is not much relevant to recent "CANNOT LINK EXECUTABLE" issues due to NDK or toolchain update. This sort of issues should be treated on a case-by-case basis. If you encounter a similar problem, then please open a new issue. This specific issue for `wget` should be closed now.
