### ISSUE TITLE
Executing termux-api though php-fpm

### ISSUE THREAD

**Issue by iwkse** [termux/termux-packages#4616]
I'm having this issue executing termux-api functions.

Running nginx with php-fpm in termux, installed termux api from the
google play store and inside termux with pkg install termux-api

**Problem description**
Script never returns or return NULL.

**Steps to reproduce**
This php script to reproduce the issue:
```
<?php
  $base = '/data/data/com.termux/files/usr/bin/';
  $battery = shell_exec($base . 'termux-battery-status');
?>  
<html>
<head><title>Termux API</title></head>
<body>
<div id="battery"><?php echo $battery;?></div>
</body>
</html>
```
If I just use 'termux-battery-status' without $base the script returns
but $battery is NULL otherwise gateway timeout

**Expected behavior**
Having the result into the variable

**Additional information**
Post output of command `termux-info`.

```
$ termux-info 
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24 stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 4.1.18-g8173925 #1 SMP PREEMPT Sun Dec 3 01:47:17 CST 2017 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
EVA-L09
```
Depending on problem, additional information may be requested:

Nothing useful in logs.
The problem occurs only for php-fpm, with php from cli or php -S and apache2 it works as expected

[edit]
ps shows processes launched in php still in execution, so it's not terminating them

**Comment by RossComputerGuy** [comment]
Did you allow Termux:API to access the battery? Do you have the Termux:API app installed?

**Comment by iwkse** [comment]
Yes. I took as example termux-battery-status but it's not working for all termux API. As I said it works properly with everything but php-fpm

**Comment by Grimler91** [comment]
Does it work for other commands, like `echo`?

**Comment by iwkse** [comment]
Yes, it works for everything but termux-api

**Comment by xeffyr** [comment]
Unset environment variables can be a problem for things like `termux-api`. Particularly `ANDROID_DATA`, `ANDROID_ROOT`, `PREFIX`, `EXTERNAL_STORAGE`.

**Comment by xeffyr** [comment]
Try to execute `env` under `shell_exec` and check whether environment variables are set.

**Comment by iwkse** [comment]
Thanks, checked now and all such environment variables are not set.

**Comment by iwkse** [comment]
Awesome! it works with such environment variables set. Closing this issue, thanks a bunch :-)
