### ISSUE TITLE
command line at bottom of screen 

### ISSUE THREAD

**Issue by Duhjoker** [termux/termux-packages#4617]
Im using an alcatel 5041c Tetra that is rooted to use termux so i can install ubuntu 18. I installed today after the rooting procedure and the command line portion or typing area appears at the bottom of the screen only. There is no way to see what is being typed with out dropping the key board each time. Is there a way to fix this?

**Comment by xeffyr** [comment]
Screenshot with `the command line portion or typing area appears at the bottom of the screen only` is needed.

**Comment by xeffyr** [comment]
Closing issue due to lack of information.
