### ISSUE TITLE
USB Serial 

### ISSUE THREAD

**Issue by russellstrei** [termux/termux-packages#4618]
**Problem description**
Running on Samsung S5e Non-Root with Samsung Dex. Installed API, Requested permission to /dev/bus/usb/001/002 via termux-usb -r ..... [granted, says ].  upon loading minicom, i get permission denied.

**Steps to reproduce**
Steps to reproduce the behavior. 
load minicom with usb serial port connected.  fails

**Expected behavior**
I expect that i would be passed through to the usb serial port at 9600 baud as set in the defaults

**Additional information**
Post output of command `termux-info`.

Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.112-16982790 #2 SMP PREEMPT Thu Oct 17 19:12:11 KST 2019 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T720

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o [strace.log]  {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by RossComputerGuy** [comment]
Sounds like SELinux preventing minicom, there is no way to fix this without rooting the device. Also, please post the `termux-info` output in code blocks in the future.

**Comment by xeffyr** [comment]
This is not a bug.

USB API is limited and can be used only with libusb-based programs. You cannot obtain permission to have raw access to serial line character devices on Android.

https://wiki.termux.com/wiki/Termux-usb
