### ISSUE TITLE
Build-essential Clang-9.0.0 bug?

### ISSUE THREAD

**Issue by Alexei1981** [termux/termux-packages#4621]
I installed the build-essential package and tried to compile c ++ code with the -flto flag and the compiler produced this.  In a previous version of clang, this was not.

```
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/bin/../lib/LLVMgold.so: error loading plugin: dlopen failed: cannot locate symbol "__clear_cache" referenced by "/data/data/com.termux/files/usr/lib/libLLVM-9.so"...
clang-9: error: linker command failed with exit code 1
```

**Comment by tomkha** [comment]
and this also affects Rust https://github.com/termux/termux-packages/issues/4613

**Comment by Alexei1981** [comment]
I got this bug after I upgraded to the latest version of Clang.  Before that, everything worked fine.  And it’s already impossible to roll back to the previous version.

**Comment by pollen5** [comment]
Thank god i procrastinated to update llvm/clang

**Comment by its-pointless** [comment]
I had a look at using -flto and it didn't work
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/bin/../lib/LLVMgold.so: error loading plugin: dlopen failed: cannot locate symbol "__clear_cache" referenced by "/data/data/com.termux/files/usr/lib/libLLVM-9.so"...
LD_PRELOAD=/system/lib64/libcompiler_rt.so  g++ test.c -liconv -flto 
Worked though. 
Will sort it out.

**Comment by its-pointless** [comment]
Updated to libllvm 9.0.0-2 fixed it...
