### ISSUE TITLE
The following packages have unmet dependencies:  krb5 : Depends: libutil but it is not going to be installed  openssh : Depends: libutil but it is not going to be installed  python2 : Depends: libutil but it is not going to be installed  ruby : Depends: libutil but it is not going to be installed  util-linux : Depends: libutil but it is not going to be installed E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution

### ISSUE THREAD

**Issue by smir1998** [termux/termux-packages#4623]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by Grimler91** [comment]
https://github.com/termux/termux-packages/issues/4624
