### ISSUE TITLE
apt --fix-broken install doesn't work on this error

### ISSUE THREAD

**Issue by smir1998** [termux/termux-packages#4624]
If i try to install anything it shows these
The following packages have unmet dependencies:
 krb5 : Depends: libutil but it is not going to be installed
 openssh : Depends: libutil but it is not going to be installed
 python2 : Depends: libutil but it is not going to be installed
 ruby : Depends: libutil but it is not going to be installed
 util-linux : Depends: libutil but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution

**Comment by Grimler91** [comment]
Easiest fix would be to run `rm -rf $PREFIX` and then restart termux, this will remove all installed packages and give you a fresh installation. Files in $HOME are left intact though.

**Comment by xeffyr** [comment]
Seems like you somehow changed default main repository in `sources.list`. In such case only `rm -rf $PREFIX` will help. Packages from branches `master` and `android-5` are not interchangeable.
