### ISSUE TITLE
Bad System call with screen in package version 4.7.0-1

### ISSUE THREAD

**Issue by MathiasHabel** [termux/termux-packages#4627]
Hi all,

I have exactly the same problem when starting screen as described in Issue https://github.com/termux/termux-packages/issues/4414: it crashes with "Bad system call".

Logcat shows the same error message "Cause: seccomp prevented call to disallowed arm64 system call 144".

I have package version 4.7.0-1 installed, which is the most recent version as of the moment.

screen itself has version: "Screen version 4.07.00 (GNU) 02-Oct-19"

Mathias

**Comment by xeffyr** [comment]
Post output of `termux-info`.

**Comment by MathiasHabel** [comment]
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages-21 unstable main
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages-21 x11 main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-21 science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/ termux extras
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-21 root stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-21 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.148 #1 SMP PREEMPT Sat Nov 2 09:44:24 CST 2019 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
BKL-L09

**Comment by MathiasHabel** [comment]
sorry, made a mistake while commenting

**Comment by xeffyr** [comment]
You are using legacy repository for Android 5/6 devices which are not affected by this problem and relevant patch will not be applied.

Switch to appropriate repo with `termux-upgrade-repo`. `termux.net` will be [unsupported](https://github.com/termux/termux-packages/issues/4467) after 01.01.2020.
