### ISSUE TITLE
mv doesnt work

### ISSUE THREAD

**Issue by blaah2200** [termux/termux-packages#4630]
on ASUS Zenpad 7.0 C.

The command returns but nothing seems to happen.

**Comment by Grimler91** [comment]
What are you running exactly? 
What does "nothing seems to happen" mean?

**Comment by blaah2200** [comment]
> running exactly?

What do you mean.

**Comment by RossComputerGuy** [comment]
Like what was the way `mv` was invoked

**Comment by xeffyr** [comment]
@blaah2200 Post screenshot here with:

1. Directory content listing before using "mv".

2. Execute command `mv` with your arguments.

3. Do directory listing again.

So resulting image should look like
![Screenshot_20191206-172815_Termux](https://user-images.githubusercontent.com/25881154/70334359-fd555d80-184d-11ea-808d-e180f7bfd6ce.jpg)

If you can't do that for some reason, I'm closing this issue as *unreproducible* (see picture above - `mv` does not print any error).

**Comment by blaah2200** [comment]
@xeffyr 

![](http://0x0.st/zldY.png)

**Comment by xeffyr** [comment]
Ok, that's weird. Possibly issue is related to https://github.com/termux/termux-packages/issues/4217.
