### ISSUE TITLE
Weechat can't load python plugin

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#4633]
When I run weechat, I get the following message followed by an inability to run python scripts:

Error: unable to load plugin "/data/data/com.termux/files/usr/lib/weechat/plugins/python.so":  dlopen failed: cannot locate symbol "_Py_NoneStruct" referenced by "python.so"...

Please fix this error. Thank you.

**Comment by Grimler91** [comment]
What's your output of `termux-info`?

**Comment by IRISnoir** [comment]
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-21 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-21 science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages-21 unstable main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-21 root stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages-21 x11 main
Updatable packages:
All packages up to date
Android version:
5.1
Kernel build information:
Linux localhost 3.10.72 #1 SMP PREEMPT Tue Feb 16 18:23:49 CST 2016 armv7l Android
Device manufacturer:
Lenovo
Device model:
Lenovo TB3-710I

**Comment by IRISnoir** [comment]
The problem has been resolved. Thank you very much.
