### ISSUE TITLE
Missing header file "spawn.h"

### ISSUE THREAD

**Issue by dram** [termux/termux-packages#4634]
**Problem description**

When try to compiling C code using `posix_spawn()`, compiler complains with error: `'spawn.h' file not found`.

**Steps to reproduce**

Try following sample code:

```
% cat foo.c
#include <spawn.h>

int main() { }
```

Output:

```
% cc foo.c
foo.c:1:10: fatal error: 'spawn.h' file not found
#include <spawn.h>
         ^~~~~~~~~
1 error generated.
```

**Expected behavior**
Add `spawn.h` file to support `posix_spawn()` API.

BTW, when I grab `spawn.h` from https://android.googlesource.com/platform/bionic/+/refs/heads/master/libc/include/spawn.h, code using `posix_spawn()` can be compiled and run with no error.

**Comment by Grimler91** [comment]
Install `libandroid-spawn`.

**Comment by csqmdx** [comment]
and how to install  [libandroid-spawn](url)

**Comment by underhood** [comment]
Unable to lockate package `libandroid-spawn`

**Comment by RalfWerner** [comment]
`pkg in libandroid-spawn`
