### ISSUE TITLE
termux-brightness does not have permission.

### ISSUE THREAD

**Issue by divijish** [termux/termux-packages#4635]
using termux-brightness command returns {"error": "Please grant the following permission to use this command: android.permission.WRITE_SETTINGS"} and there is no option to grant this permission when I go to the Termux app in settings. I have granted all permissions to Termux:API

**Comment by xeffyr** [comment]
Android has a separate menu for `WRITE_SETTINGS` permission.

**Comment by khansaad1275** [comment]
> Android has a separate menu for `WRITE_SETTINGS` permission (it is considered as "special").

Can you please tell me how i can access that menu?

**Comment by xeffyr** [comment]
You should know more about your device than we. Location of this menu is device specific, seek under app info, permissions management or security menus.

On my device it can be opened from app info:
![Screenshot_20200324-121317_Settings](https://user-images.githubusercontent.com/25881154/77414191-49aab600-6dc9-11ea-91b6-f9750ffe9d51.jpg)

**Comment by hariom285** [comment]
You can simply grant the permission by opening your settings app and then go to
App management>permissions>subordinate permissions>other>modify system settings
And in the modify section simply click on the checkbox  in front of the icon of termux api
