### ISSUE TITLE
Can't install unstable-repo

### ISSUE THREAD

**Issue by divyakutty** [termux/termux-packages#4637]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by RossComputerGuy** [comment]
Could you please provide some information?

**Comment by xeffyr** [comment]
Absolutely correct, you no longer able to install `unstable-repo` and `x11-repo` on *legacy installations*. I have removed these packages to prevent newcomers using repositories that **will be deleted** after 01.01.2020.

https://github.com/termux/termux-packages/commit/a3ab0750e8fa3546ae6d1ddead7915376541d9b5

https://github.com/termux/termux-packages/commit/4fcc7a1269bea751050b77930b5da9f049c63b42

***

`unstable-repo` and `x11-repo` are available only for Android 7 and higer and only if you don't use legacy repository `termux.net` (or its mirror).

**Comment by divyakutty** [comment]
Could not find metasploit in termux
