### ISSUE TITLE
conda package manager

### ISSUE THREAD

**Issue by elehcim** [termux/termux-packages#464]
Hello, I'd like to try to install the [`conda`](http://conda.pydata.org/docs/) package manager. I'm trying to install it through pip (pip install conda). There are many other dependencies needed by conda. A lot of them can be installed via pip as well, but I'm stuck on the installation of `pycosat` with the following error:

```
running build_ext
    building 'pycosat' extension
    creating build/temp.linux-aarch64-3.5
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Os -fPIC -DPYCOSAT_VERSION="0.6.1" -I/data/data/com.termux/files/usr/include/python3.5m -c pycosat.c -o build/temp.linux-aarch64-3.5/pycosat.o
    In file included from pycosat.c:18:
    ./picosat.c:8245:10: fatal error: 'sys/unistd.h' file not found
    #include <sys/unistd.h>
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1
```

I'm not an expert of Android NDK. Do you think it's fixable? Is there a way to add the `sys/unistd.h` header file?
Thank you for this wonderful app

**Comment by fornwall** [comment]
Using `<sys/unistd.h>` does not work on Android. It seems to be a legacy path, I've submitted a pull request to `pycosat` at https://github.com/ContinuumIO/pycosat/pull/29.

**Comment by MaxGhenis** [comment]
Is there any known way to install `conda`?

Here were my steps using the recommendation from the [conda installation page](https://conda.io/docs/user-guide/install/linux.html):

    pkg install wget

(restart termux)

    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    bash Miniconda3-latest-Linux-x86_64.sh

(accept defaults)

> ...
> installing: python-3.6.4-hc3d631a_1 ...
> Miniconda3-latest-Linux-x86_64.sh: line 363: /data/data/com.termux/files/home/miniconda3/pkgs/python-3.6.4-hc3d631a_1/bin/python: No such file or directory

**Comment by Grimler91** [comment]
@MaxGhenis is you android device x86_64?  If not then that particular script isn't the way to go.

**Comment by MaxGhenis** [comment]
@Grimler91 yes I'm running a Pixelbook, and this installer worked via crouton.

**Comment by Hax4us** [comment]
What you mean by "did not work" ? Please explain your error or problem you are facing

**Comment by scottlittle** [comment]
@Hax4us, here's a snippet of installation and error:

... installing: sqlite-3.8.4.1-1 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-3.16.0-py27_0 ...
installing: pycrypto-2.6.1-py27_0 ...
Miniconda-3.16.0-Linux-armv7l.sh: line 265: /data/data/com.termux/files/home/miniconda/pkgs/python-2.7.10-0/bin/python: No such file or directory
ERROR:
cannot execute native linux-armv7l binary, output from 'uname -a' is:
Linux localhost 3.18.70-gabd44345f20f #1 SMP PREEMPT Wed Mar 14 20:59:04 UTC 2018 aarch64 Android
$

**Comment by sdrausty** [comment]
@scottlittle @Hax4us brought up a very important point.  Show your input and output.  What is going on?  

> What you mean by "did not work" ? Please explain your error or problem you are facing

You haven't even given us us a puzzle.  Just flashed wear so far...

**Comment by sdrausty** [comment]
@scottlittle better warmer ;}
> . Show your input and output. What is going on?

**Comment by sdrausty** [comment]
@scottlittle don't be bashful; send us a nice textwall plz

**Comment by Grimler91** [comment]
@scottlittle you have a aarch64 device so you shouldn't use a armv7l installation script.

**Comment by sdrausty** [comment]
@scottlittle that's vivid at first glance:
```
 linux-armv7l 
aarch64
```

32bit vs 64bit system hardware mixing issue it seems @Grimler91 The best way to explain this is if half your device breaks, it still works.  It unfixable at present; Have you though about qemu?

**Comment by Grimler91** [comment]
@sdrausty the termux-info output doesn't mention arm, only aarch64. I'm not familiar with pixel xl though, maybe it is one of those that mix arches.

**Comment by sdrausty** [comment]
@Grimler91 I have no clue; @scottlittle did not give us enough output.  All we know is that it is a 32bit vs 64bit setup, but whether this is hardware : unknown.  It took me a while to understand the motivation for the hardware software mix.  Turns out there are very good reasons to make the devices mixed.  Chip failure and 100% reliability are probably the top two reasons.  I'm not so sure about finances since Android is free.  But, on the other hand, firmware isn't.

**Comment by sdrausty** [comment]
This might simply be the effect of rooting an Android device too; Do you concur?

**Comment by scottlittle** [comment]
My device is not rooted.

**Comment by sdrausty** [comment]
:+1:

**Comment by xeffyr** [comment]
> installing: conda-3.16.0-py27_0 ...
installing: pycrypto-2.6.1-py27_0 ...
Miniconda-3.16.0-Linux-armv7l.sh: line 265: /data/data/com.termux/files/home/miniconda/pkgs/python-2.7.10-0/bin/python: No such file or directory

@scottlittle, you can't execute these binaries in Termux due to different ABI. GNU libc needed to run them.

**Comment by MaxGhenis** [comment]
Should I file a new issue for my [Pixelbook installation problem](https://github.com/termux/termux-packages/issues/464#issuecomment-381419586)? It seems like this discussion is for other device types.

**Comment by ameybhavsar24** [comment]
@MaxGhenis
```
ERROR: size of Miniconda3-latest-Linux-x86_64.sh should be     75257002 bytes
```
I'm getting this after following your steps.

**Comment by xeffyr** [comment]
@ameybhavsar24 You won't be able to use it. Termux doesn't support executables compiled for normal Linux distributions. It will just end with:
```
Miniconda3-latest-Linux-x86_64.sh: line 363: /data/data/com.termux/files/home/miniconda3/pkgs/python-3.6.4-hc3d631a_1/bin/python: No such file or directory
```
because of missing linker (/lib/ld-linux-x86-64.so.2).
