### ISSUE TITLE
needed support

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [termux/termux-packages#4641]
needed help!!
![](https://user-images.githubusercontent.com/58562742/70500047-896ccb00-1b55-11ea-9a14-046a1a32c637.jpg)

**Comment by RossComputerGuy** [comment]
Wpscan is a command used on Kali Linux, issue needs to be transfered to the root packages repo.

**Comment by xeffyr** [comment]
This is known issue with Ruby package, though it cannot be solved due to https://github.com/android/ndk/issues/201 which is a limitation of Android OS linker.
