### ISSUE TITLE
libgrpc conflicts with gflags

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-packages#4646]
**Problem description**

Dpkg produces the following error while installing both gflags and libgrpc:
```
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/libgrpc_1.25.0_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/lib/libgflags_nothreads.so', which is also in package gflags 2.2.2-6
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```

**Expected behavior**

Packages should be marked as conflicting or duplicate file should be removed from one of packages.

**Comment by fornwall** [comment]
So the grpc package currently bundles a copy of the gflags library? Perhaps it can be built to link against the system one.

**Comment by xeffyr** [comment]
gflags is now a dependency of libgrpc.
