### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by 0x-MRNOBODY-x0** [termux/termux-packages#4648]
My device is rooted and I have already used metasploit with termux package unstable-repo. I have to uninstall the termux and after I install it again, it saying the unstable- repo is not supporting. So I have to download a bash file to install metasploit.
After the installation I tried to run metasploit and it saying about a segmentation fault error. Please help me to fix this problem. I know this one isn't a metasploit error.

Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo

Report issues at https://termux.com/issues

$ ls
Metasploit_termux  metasploit-framework
$ cd metasploit-framework/
$ ls
CODE_OF_CONDUCT.md     app                           msfconsole
CONTRIBUTING.md        config                        msfd
COPYING                data                          msfrpc
Dockerfile             db                            msfrpcd
Gemfile                docker                        msfupdate
Gemfile.local.example  docker-compose.override.yml   msfvenom
Gemfile.lock           docker-compose.yml            plugins
LICENSE                documentation                 script
LICENSE_GEMS           external                      scripts
README.md              lib                           spec
Rakefile               metasploit-framework.gemspec  test
Vagrantfile            modules                       tools
$ ./msfconsole
Segmentation fault
$

**Comment by xeffyr** [comment]
Try this one:

[metasploit_5.0.56_android5_all.deb.gz](https://github.com/termux/termux-packages/files/3960686/metasploit_5.0.56_android5_all.deb.gz)

**Comment by 0x-MRNOBODY-x0** [comment]
Ok. Thank you for replying.

**Comment by 0x-MRNOBODY-x0** [comment]
what i need to do after unziping this?

**Comment by xeffyr** [comment]
```
curl -LO https://github.com/termux/termux-packages/files/3960686/metasploit_5.0.56_android5_all.deb.gz
gunzip metasploit_5.0.56_android5_all.deb.gz
dpkg -i metasploit_5.0.56_android5_all.deb
apt -f install
```

**Comment by 0x-MRNOBODY-x0** [comment]
Wow bro.. 
Thank you very much. It's working now.
