### ISSUE TITLE
Bag, docker in 600 lines of bash with proot.

### ISSUE THREAD

**Issue by hkoosha** [termux/termux-packages#4649]
**Package description**
Bag, docker in 600 lines of bash with proot.

Why? because it isolates many namespaces one uses in termux. they won't clash and termux won't become a big pile of convoluted, unrelated configurations and binaries. (well, the same reason docker is cool on a dev machine, this script is also cool in termux). 

**Link to home page and sources**
1. Home page: https://github.com/hkoosha/bag
2. Source code: https://github.com/hkoosha/bag

**Additional information**
Have you compiled or tried to compile the package on device?
I wrote it itself in termux. A simple version has been running for months on my device.
The bash coding style is not what I would call clean. I think I'll implement it in another language.

**Comment by hkoosha** [comment]
If you think this is a nice addition to termux, installable with `pkg`, I can create a package for it and make a PR.

**Comment by xeffyr** [comment]
This (and other proot'ed distro installators) is not going to be added.
