### ISSUE TITLE
Supporting aarch64 on devices with 32-bit Android but an aarch64 kernel

### ISSUE THREAD

**Issue by woachk** [termux/termux-packages#4651]
**Problem description**
Samsung ARM64 devices with 2GB of RAM and lower run using a 32-bit Android userspace.
That includes the Galaxy A10, released in 2019 on Android 9, despite using a Cortex-A73.

**Steps to reproduce**
Install Termux and see the used architecture.

**Expected behavior**
Aarch64 packages are installed.

**Additional information**
![Screenshot_20191213-192840_Termux](https://user-images.githubusercontent.com/24752637/70830664-0667a100-1df1-11ea-879f-69f20b676650.jpg)

Android version:
9
Kernel build information:
Linux localhost 4.4.111-16046393 #1 SMP PREEMPT Mon Nov 4 15:07:17 KST 2019 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A105FN

**Comment by xeffyr** [comment]
Sorry, but we do not shipping own *shared* libc and linker. All programs are linked against things available in `/system`.

You are limited to static linking only because your device does not provide 64bit linker & libc.
