### ISSUE TITLE
unable to find nmap-services resorting to data/data/com.name/files/usr/etc/services

### ISSUE THREAD

**Issue by mj-android-mj** [termux/termux-packages#4655]
hi, i try to recompile nmap but when i run nmap :` unable to find nmap-services resorting to data/data/com.name/files/usr/etc/services ` .
how can fix this. Thankful

**Comment by xeffyr** [comment]
Try to create a dummy file:
```
touch /data/data/com.name/files/usr/etc/services
```

Since Termux is not a Linux distribution and is not GNU libc-based, it does not have `/etc/services`.

**Comment by mj-android-mj** [comment]
thankful for replying. but i have some Question.
when i just run nmap without any options or any command for start network scaning, i have manoal. but i want to Scan somethings the output is `unable to find nmap-services resorting to data/data/com.name/files/usr/etc/services`.
 Is there a difference between nmap 7.80 and nmap 7.70 ? Because, the patch in belongs to 7.70, but i run recompile nmap 7.80 is that true?
 is there difference patch for these two versions?

**Comment by xeffyr** [comment]
Why it tried to access
```
data/data/com.name/files/usr/etc/services
```
instead of
```
/data/data/com.name/files/usr/etc/services
```
?

I'm suggesting to fix that issue before.
