### ISSUE TITLE
Package request: cadaver webdav program?

### ISSUE THREAD

**Issue by nerdhardest** [termux/termux-packages#4656]
The "cadaver" webdav program seems to be missing from the Termux repository.

There seems to be a comment regarding "cadaver" that it doesn't work with openssl 1.1.1.

I found building "cadaver" on x64 Linux with openssl 1.1.1 quite easy, and the "neon" library (using openssl) on which "cadaver" depends is still supported.

Is there any hope of including "cadaver" in Termux?

Thanks.

**Comment by Grimler91** [comment]
Which sources did you use to build it? 
No new releases have been done since 2009 so we might need to change to the sources you used then

**Comment by nerdhardest** [comment]
Hi Henrik:

Here are the magic incantations:

You need cadaver-0.23.3.tar.gz (the latest).

You do NOT want to use the neon library that is included with the
cadaver sources, but you instead want to use the latest neon:
neon-0.30.2.

You shouldn't need to build it, as it should already be there,
but if not, please build it with a longer timeout
(SOCKET_READ_TIMEOUT set to 240 seconds instead of 120 seconds).

In the cadaver directory, you need to edit the "configure"
script to replace "28 29" with "28 29 30".  This change will
allow the script to accept versions of neon up to 30.2.  This
change is ok, since there were no API changes between 29 and 30.

Then execute the configure script in the cadaver directory:

./configure --with-neon=yes

By specifying "yes", the configure script queries the existing
program "neon-config" in your machine to find out how to use
the existing neon library (which should be 0.30.2).

Use "man neon-config" if you need more info re neon-config.

then finally

make

Your new "cadaver" should now be executable.

Henry Baker

At 06:19 AM 12/15/2019, Henrik Grimler wrote:

**Comment by nerdhardest** [comment]
Hi Henrik:

I forgot to mention that my real goal would be to have
the "davfs2" work in Termux to *mount* a network WebDAV
file system in such a way that *any/every* Android app
could access it.

"cadaver" is basically a CLI front-end for the "neon"
library, so "neon" is doing most of the heavy lifting.

"davfs2" is based on the *same* "neon" library as "cadaver",
so getting "neon" to work with "cadaver" is a good step
towards getting "davfs2" to work.

I realize that getting "davfs2" to work might require
*root* privileges from the Android operating system, but
some of us want rooted Android systems for other reasons,
in any case.

"cadaver" won't require *root*, and so it may have to
suffice for non-rooted Android environments.

Henry Baker

At 06:03 PM 12/16/2019, Henry Baker wrote:

**Comment by torappinfo** [comment]
As for webdav mount, why not use rclone?
rclone supports webdav and mounting, so the only thing needed is a binary called fusermount for android.

**Comment by xeffyr** [comment]
> so the only thing needed is a binary called fusermount for android.

libfuse will not be available until pthreads incomplete implementation problem will be solved. Patches like https://github.com/termux/termux-root-packages/blob/master/disabled-packages/packages/libfuse/fsel.c.patch are actually break threading and causing whatever issues including [segfaults](https://github.com/termux/termux-root-packages/issues/30#issuecomment-430599334).

**Comment by nerdhardest** [comment]
Thanks for the suggestion re rclone!

Rclone has come up during my googling, and I've been meaning to look into it; I just moved it up in my list.

Perhaps even more importantly, I'd like to have *sshfs*.  I understand that with debian/termux it is possible to get close to this, but actually achieving it might require root, which is ok for some devices, but not others.

Unfortunately, getting mounted in termux doesn't necessarily make the file system accessible to the usual Android apps, which would be the eventual goal.

At 11:43 PM 12/18/2019, torappinfo wrote:

**Comment by MisterY** [comment]
> Unfortunately, getting mounted in termux doesn't necessarily make the file system accessible to the usual Android apps, which would be the eventual goal. 

Termux offers files through Storage Access Framework so they would be available to most modern apps. This seems to work well already, with local files.

**Comment by fancsali** [comment]
Just for the record, I tried to build in on my OnePlus 2.

Had to specify the architecture:
```
./configure --build=arm
```

Then, unfortunately `make` itself threw an error:
```
src/cadaver.c:859:5: warning: implicit declaration of function 'setlocale' is invalid in C99 [-Wimplicit-function-declaration]
    setlocale(LC_ALL, "");
    ^
src/cadaver.c:859:15: error: use of undeclared identifier 'LC_ALL'
    setlocale(LC_ALL, "");
              ^
```

I guess, I'll have to keep trying, but it's very odd. I would have thought, `autoconf` will take care of this, but for the moment, the build is stuck at this, even if I edit the source, and change the `#define HAVE_SETLOCALE 1` line to `0`.
