### ISSUE TITLE
Buffer is overwritten

### ISSUE THREAD

**Issue by he852100** [termux/termux-packages#4657]
The buffer is overwritten when docker is used(Occasional occurrence)

The problem was even worse when powershell was used

![Screenshot_20191216_014256](https://user-images.githubusercontent.com/26913892/70866528-d9102400-1fa5-11ea-8dab-af59156ff63e.jpg)

[video](https://youtu.be/PdIrVbwYMhU)

**Comment by xeffyr** [comment]
Closing since problem happens with TermuxArch packages and not ours.

**Comment by xeffyr** [comment]
Suggesting to check whether `$TERM` environment variable is set correctly.

**Comment by he852100** [comment]
@xeffyr I tried another one, and they had the same problem.
