### ISSUE TITLE
Package request: Homebrew

### ISSUE THREAD

**Issue by Daesthelos** [termux/termux-packages#4659]
**Package description**
Package installer, contains numerous helpful programs such as python3, wget, etc

**Link to home page and sources**
1. Home page: brew.sh

**Additional information**
Have you compiled or tried to compile the package on device?
* I tried to curl install and got the following error:
: from -e:204:in `<main>'
-e:204:in `chdir': No such file or directory @ dir_s_chdir - /usr (Errno::ENOENT)

**Comment by xeffyr** [comment]
Sorry, but Termux is not FHS-compatible and therefore cannot support Homebrew properly. Also, things like python, python2, wget, etc... are already packaged.

**Comment by xeffyr** [comment]
> from -e:204:in <main>' -e:204:in chdir': No such file or directory @ dir_s_chdir - /usr (Errno::ENOENT)

https://github.com/termux/termux-packages/issues/4659#issuecomment-566122197 answers why you have that error.

**Comment by xeffyr** [comment]
There many other issues preventing Homebrew packages from working properly - https://wiki.termux.com/wiki/Differences_from_Linux.

**Comment by Daesthelos** [comment]
To be honest, I was trying to install java but I saw the issue thread for it
