### ISSUE TITLE
Enable gnupg support in fwknop

### ISSUE THREAD

**Issue by quincunx** [termux/termux-packages#466]
Gnupg support seems to have been disabled to avoid too many dependencies, but gpg enabled would be an important feature in corporate environments.
The android app fwknop2 does not support gpg at all, so having it enabled in the termux package would bring this enhancement to android.

KR,
Christian

**Comment by fornwall** [comment]
Can you try out a build with gpg support? Which arch do you run (`dpkg --print-architecture`)?

**Comment by quincunx** [comment]
Yes, that would be possible, but I have to set up the build chain first.

dpkg --print-architecture
arm

**Comment by fornwall** [comment]
@quincunx You can try out a build with gpgme enabled at http://fornwall.net/fwknop_2.6.9-1_arm.deb:

    wget http://fornwall.net/fwknop_2.6.9-1_arm.deb
    apt install ./fwknop_2.6.9-1_arm.deb

Does that one work?

**Comment by quincunx** [comment]
Hi!

That package works quite well, thanks! I was able to send a gpg encrypted spa package and the server accepted it.

Thanks!

**Comment by fornwall** [comment]
@quincunx Great! The updated package with gnupg support is now available at version `2.6.9-1` in the apt package repository!

**Comment by shaheem007** [comment]
Unsupported file ./fwknop_2.6.9-1_arm.deb given on commandline

im runing arm
