### ISSUE TITLE
root problem with pkg install

### ISSUE THREAD

**Issue by roycebank** [termux/termux-packages#4665]
when i u0_a235
$ pkg install termux-api
-bash: /data/data/com.termux/files/usr/bin/pkg: Permission denied

when i root
# pkg install termux-api 
You should not use command 'apt' as root.
This is dangerous as may damage your Termux installation and data.

so i cant use pkg or apt on every user what should i do?

**Comment by Grimler91** [comment]
You have used apt as root at some point which has messed up file permissions. 

Easiest fix would be to run `rm -rf $PREFIX` (as root if necessary) and then restart termux. This will remove all installed packages and give you a fresh installation, but leave $HOME intact

**Comment by xeffyr** [comment]
Apt is now permanently locked against running as root.

If you use Termux from ADB or other root thing, you need to su back to Termux user in order to install package.

**Comment by xeffyr** [comment]
The error you have -
> $ pkg install termux-api
-bash: /data/data/com.termux/files/usr/bin/pkg: Permission denied

comes from messing up with root permissions.

**Comment by antonyenergy2** [comment]
> Apt is now permanently locked against running as root.
> 
> If you use Termux from ADB or other root thing, you need to su back to Termux user in order to install package.

How can I su to u0_a67 (my current) Termux user. Android su always exit with 255 exit code.

**Comment by agnostic-apollo** [comment]
>How can I su to u0_a67 (my current) Termux user. Android su always exit with 255 exit code.

You likely can run something like `su u0_a67 -p -c 'apt install termux-api'` at your own risk (haven't tested), assuming you have granted root access to current user via su manager and `su` binary is in `PATH`.

https://github.com/topjohnwu/Magisk/blob/master/docs/tools.md#su
