### ISSUE TITLE
metaspoit bundle gemfile problem in termux

### ISSUE THREAD

**Issue by adamzad** [termux/termux-packages#4666]
Plz help me I did install metaspoit  with this commands 
apt update 
apt upgrade
pkg install ruby and git and wget
pkg install unstable-repo
pkg install metasploit

Even when I try to install bundle I get "could not locate gem file"
![Screenshot_20191218-205244_Termux](https://user-images.githubusercontent.com/50003010/71124695-b409f400-21e5-11ea-8de9-f56919da4556.png)

**Comment by xeffyr** [comment]
Post output of `termux-info`.

**Comment by adamzad** [comment]
> Post output of `termux-info`.

![Screenshot_20191219-065300_Termux](https://user-images.githubusercontent.com/50003010/71148553-3d441980-222c-11ea-8692-fe956af12695.png)

**Comment by xeffyr** [comment]
Should be fixed with latest version.
