### ISSUE TITLE
llvm-dev package 

### ISSUE THREAD

**Issue by russelltg** [termux/termux-packages#467]
Hey! I am a developer developing a library that uses llvm, and it would be really nice not to have to provide my own llvm headers for the project. I know that the clang package provides llvm, but not the headers.

**Comment by tomaklutfu** [comment]
It seems clang-dev already has llvm headers.

**Comment by fornwall** [comment]
The clang package has now been split up. First, update to latest package versions with:

    apt update && apt upgrade

Now, the llvm headers can be installed with

    apt install libllvm-dev
