### ISSUE TITLE
Can't see input

### ISSUE THREAD

**Issue by dreinert95** [termux/termux-packages#4678]
Can't see what I'm typing into the Termux terminal. I'm using a Note 10+

**Comment by Grimler91** [comment]
Does it work if you open a new terminal? Try running reset (just type reset + enter).

**Comment by dreinert95** [comment]
[]https://photos.app.goo.gl/HVBEKJ1RgKF7v7Gw5 

I am new to termux so I apologize if it is a simple issue but this is what happens after I typed and executed reset. input still cannot be seen

**Comment by xeffyr** [comment]
@dreinert95 Have you tried a different keyboard ?

**Comment by dreinert95** [comment]
@xeffyr  no I haven't. I only have Samsung keyboard or Samsung/Google voice typing. is there a 3rd party keyboard I can install?

**Comment by xeffyr** [comment]
Try a one of these:

* https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin
* https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard

Samsung keyboards are known to have issues with Termux. There were reports at https://github.com/termux/termux-app/issues.

**Comment by dreinert95** [comment]
@xeffyr  hackers keyboard works. thanks for the help!

**Comment by dreinert95** [comment]
@Grimler91  thanks for your input and help!

**Comment by SANTHAN-KUMAR** [comment]
It is problem of keyboard,some keyboards didn't work for termux,try another keyboard.hope it helps you...
