### ISSUE TITLE
How to Build pip modules while build python or after built on Docker Image

### ISSUE THREAD

**Issue by canewsin** [termux/termux-packages#4679]
I was building individual packages via docker image and they are building successfully, my query is there are some native python pip modules compiling them on device is very slow, how to compile those pip packages on docker image using ndk instead on mobile device.

**Comment by Grimler91** [comment]
Pip/python doesn't really support cross compiling so there's no easy way to do this.

We [asciinema](https://github.com/termux/termux-packages/blob/master/packages/asciinema/build.sh), [borgbackup](https://github.com/termux/termux-packages/blob/master/packages/borgbackup/build.sh) and [electrum](https://github.com/termux/unstable-packages/blob/master/packages/electrum/build.sh) are three examples of python modules that we are building in the docker image
