### ISSUE TITLE
/**/usr/share/vim/vim82 files missing in vim-python_8.2.0000_aarch64.deb

### ISSUE THREAD

**Issue by davidsands** [termux/termux-packages#4680]
ok
**Problem description**
After upgrading vim-python to v8.2, vim's syntax files, etc. were missing, producing errors on start up.

**Steps to reproduce**
Install the vim-python v8.2 package

**Expected behavior**
Normality.

**Additional information**
Copied vim 8.1 supporting files to /**/usr/share/vim/vim82 and it worked. Checked deb and saw no tar for vim82 folder.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/4681
