### ISSUE TITLE
vim-runtime v8.2 is empty

### ISSUE THREAD

**Issue by davidsands** [termux/termux-packages#4681]
**Problem description**
After installing vim-python v8.2, rumtime files were missing, producing errors.   
  $ apt show vim-runtime
indicates the package is basically empty, unlike th 20M+ of the previous version.

**Steps to reproduce**
Install vim-python v8.2 clean.

**Expected behavior**
Normal vim.

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by xeffyr** [comment]
Fixed in `vim-runtime` v8.2.0000-2.
