### ISSUE TITLE
Can't find "php.ini"

### ISSUE THREAD

**Issue by feilongproject** [termux/termux-packages#4693]
I can't find "php.ini",where is?

**Comment by fdciabdul** [comment]
You have to create `php.ini` in $cd $PREFIX/lib/php

**Comment by fornwall** [comment]
Not knowing php much - is this something we should improve on the Termux side, having a stub php.ini?

**Comment by feilongproject** [comment]
> Not knowing php much - is this something we should improve on the Termux side, having a stub php.ini?

Maybe can :)

**Comment by signotorez** [comment]
perhaps we can do on build step "termux_step_post_make_install"
`cp php.ini-production $TERMUX_PREFIX/lib/php/`
