### ISSUE TITLE
You are using legacy Termux environment. Packages are unmaintained and will not receive any updates.

### ISSUE THREAD

**Issue by mohsan-604** [termux/termux-packages#4695]

**Comment by xeffyr** [comment]
I hope you understand that we are dropping support for Android 5/6 devices completely...

**Comment by mohsan-604** [comment]
> أتمنى أن تفهم أننا نسقط دعمًا لأجهزة Android 5/6 تمامًا ...

android j5   5.1.1

**Comment by xeffyr** [comment]
> android j5 5.1.1

So what ??? I just wrote above - we are dropping support for all OSes between 5.0-6.x.

**Comment by mohsan-604** [comment]
> _لا يوجد وصف المقدمة._

![Uploading Screenshot_٢٠١٩-١٢-٢٥-١٨-٠١-١٠.png…]()

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/4467 - everything here. No more updates & bugfixes for Android 5.x.x-6.x.x.
