### ISSUE TITLE
Rust to wasm process?

### ISSUE THREAD

**Issue by Choons** [termux/termux-packages#4696]
**Problem description**
Trying to learn Rust for WebAssembly but all the typical ways shown online to compile Rust projects to wasm don't work with the Termux Rust pkg. 

**Steps to reproduce**
Trying to build/compile without rustup, wasm-pack, cargo build target... 

**Expected behavior**
I expect a Rust pkg to have a way to get to WebAssembly wasm modules, but can't find instructions or figure out how with the Termux Rust pkg. What am I missing?

**Additional information**
Packages CPU architecture:
aarch64                                                                                          Subscribed repositories:
# sources.list                                                                                   deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)                                                     deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)                                                           deb https://dl.bintray.com/grimler/game-packages-24 games stable                                 Updatable packages:
clang/stable 9.0.1 aarch64 [upgradable from: 9.0.0-2]                                            libllvm/stable 9.0.1 aarch64 [upgradable from: 9.0.0-2]                                          lld/stable 9.0.1 aarch64 [upgradable from: 9.0.0-2]                                              llvm/stable 9.0.1 aarch64 [upgradable from: 9.0.0-2]                                             rust/stable 1.40.0 aarch64 [upgradable from: 1.39.0]                                             Android version:                                                                                 9                                                                                                Kernel build information:
Linux localhost 4.9.112-perf+ #1 SMP PREEMPT Mon Sep 23 14:39:29 CDT 2019 aarch64 Android        Device manufacturer:                                                                             motorola
Device model:                                                                                    moto g(7) optimo maxx(XT1955DL)

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
Install package `rust-std-wasm32`.

**Comment by Choons** [comment]
Brilliant! Once again, thank you guys so much for the Termux magix ;-)
