### ISSUE TITLE
pkg seafile-client don't work

### ISSUE THREAD

**Issue by coinabc123** [termux/termux-packages#4699]
Hey,

after i have installed the pkg seafile-client i tried to start it but i got only the error that python and the future package is missing.
So i installed python and the future package (with pip), but after that i got the error no module named seafile and this package i can't install

**Comment by xeffyr** [comment]
As for quick fix, try to do next (worked for me):

1. `pkg install python2`
2. `pip2 install future`
3. Edit file `$PREFIX/bin/seaf-cli` and replace `python` with `python2`.

**Comment by xeffyr** [comment]
Fixed in `7.0.4-1`.

**Comment by coinabc123** [comment]
ok now it works, thanks
