### ISSUE TITLE
building termux packages and docker

### ISSUE THREAD

**Issue by its-pointless** [termux/termux-packages#470]
Well having built a docker image via the Dockerfile and compiling i got several issues. 
First the easy to solve ones
setup-ubuntu.sh needs python-pip and intltool as both are used at some point. Other scripts might need changes as well. 

Also libgd does not compile correctly when using the result of the script. Generating toolchain from /root/lib/android-ndk does not seem to be able to compile libgd but using a non reduced full unziped ndk for the tool chain is able to compile libgd.

Now finally the issue that seems weird to me. radare2 will not compile and i tried on 2 different machines one via docker image another using debina via virtualbox. Both fail in the same place during the termux_set_make phase. Failing to compile  What solves this issue is clearing all the env settings and adding all the needed ones individually.

**Comment by fornwall** [comment]
This should now be fixed!

The docker image has been updated, so the script `./scripts/update-docker.sh` should be run to pull down this update.

Let me know if any build problem remains!
