### ISSUE TITLE
dpkg warning: symbolic link size has changed from X to Y 

### ISSUE THREAD

**Issue by AbdelrhmanHegazy** [termux/termux-packages#4700]
I have a dpkg: warning: symbolic link
and when I tried ls -la /data/data/com.termux/files/usr/lib/libintl.so
I got No such file or directory
My dpkg version Debian 'dpkg' package management program version 1.19.7 (aarch64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
My mobile phone is Oppo f11

**Comment by xeffyr** [comment]
> symbolic link size has changed from X to Y

As far I can tell, I observed that behaviour on Android 10 but no real issues were found. All symlinks pointed to the correct locations.

Most likely issue is kernel-related.

> I tried ls -la /data/data/com.termux/files/usr/lib/libintl.so
I got No such file or directory

Expected behaviour. This file is not available in Termux. At least in current package versions.

**Comment by AbdelrhmanHegazy** [comment]
My android version is 9 not 10

**Comment by xeffyr** [comment]
> dpkg: error processing package gvfs:arm64 (--configure):
dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs-fuse:
gvfs-fuse depends on gvfs (= 1.42.1-3); however:

Termux has `gvfs` ? I didn't remember that I had added that package.

What you are trying to do exactly ? To use Debian repository in Termux ?

**Comment by xeffyr** [comment]
If you has that issue under proot, check issues

* https://github.com/termux/proot/issues/84

* https://github.com/termux/proot/issues/87

If you have symlink and/or case-sensivity issues.

**Comment by AbdelrhmanHegazy** [comment]
I'm using https://github.com/Hax4us/Nethunter-In-Termux
