### ISSUE TITLE
A2sv pakage isn't existed

### ISSUE THREAD

**Issue by naix69** [termux/termux-packages#4701]
**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by Ethereum7** [comment]
> **Package description**
> Describe what this package do and why it should be available.
> 
> **Link to home page and sources**
> 
> 1. Home page:
> 2. Source code:
> 
> **Additional information**
> Have you compiled or tried to compile the package on device?
> 
> * If it didn't work then please provide the error you ran into
> * If it did work then please share any patches that you had to apply

[]()

**Comment by Ethereum7** [comment]
> **Package description**
> Describe what this package do and why it should be available.
> 
> **Link to home page and sources**
> 
> 1. Home page:
> 2. Source code:
> 
> **Additional information**
> Have you compiled or tried to compile the package on device?
> 
> * If it didn't work then please provide the error you ran into
> * If it did work then please share any patches that you had to apply

[@cointiger_en](https://salibra.com/p/cant-be-evil-sandbox-f0475feec4b9)

**Comment by xeffyr** [comment]
No, this really isn't going to be added. Reason: python package using external modules.
