### ISSUE TITLE
package: GNUnet

### ISSUE THREAD

**Issue by mehlon** [termux/termux-packages#4707]
**Package description**
GNUnet is a new protocol stack for distributed, secure and privacy-preserving applications.
Right now it offers a few services: chatting (CADET), filesharing, decentralized name system (GNS)
It's the transport protocol that [secushare](https://secushare.org/) will use when it's ready.

**Link to home page and sources**
1. Home page: https://gnunet.org/en/
2. Source code: https://git.gnunet.org/ (compile instructions at https://gnunet.org/en/install.html)

**Additional information**
Ubuntu and Debian don't have up-to-date packages of gnunet right now. NixOS and Arch Linux do.
I haven't tried compiling on Termux yet, because it couldn't find a few packages (libextractor, autopoint,  libglpk-dev, libopus-dev and some others). Some are probably not needed since they are meant for GNUnet conversation (voice).
I successfully compiled it in Ubuntu on [UserLAnd](https://github.com/CypherpunkArmory/UserLAnd). This worked reasonably well. 
* If errors occur, the log files can quickly fill up the device storage (at `$HOME/.cache/gnunet/*`). This happened to me twice, so logging should either be disabled or somehow limited in size.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install gnunet
```
