### ISSUE TITLE
Jupyter Lab build errors

### ISSUE THREAD

**Issue by StephanBeer** [termux/termux-packages#4708]
Hi there, is anyone playing/messing arround with jupyter notebook and especially jupyter lab?
Jupyter Lab runs fine when installing with 'pip install jupyter lab', also adding kernels(R, Octave) is no problem but when adding addons via the addon manager i get build errors

**Comment by StephanBeer** [comment]
~~~
 $ jupyter lab build
[LabBuildApp] JupyterLab 1.2.4
[LabBuildApp] Building in /data/data/com.termux/files/usr/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
KeyError: '@jupyterlab/google-drive'
See the log file for details:  /data/data/com.termux/files/usr/tmp/jupyterlab-debug-mva5jdxb.log
~~~

**Comment by StephanBeer** [comment]
~~~
[LabBuildApp] Building in /data/data/com.termux/files/usr/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v13.0.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/labapp.py", line 97, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/commands.py", line 458, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/commands.py", line 648, in build
    self._populate_staging(
[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/commands.py", line 1156, in _populate_staging
    data = self._get_package_template()

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/commands.py", line 1241, in _get_package_template
    data['jupyterlab']['mimeExtensions'].pop(item)

[LabBuildApp] KeyError: '@jupyterlab/google-drive'

[LabBuildApp] Exiting application: JupyterLab

**Comment by StephanBeer** [comment]
Tried building it under/with ~~~ proot --link2symlink~~~

**Comment by xeffyr** [comment]
What log file (`/data/data/com.termux/files/usr/tmp/jupyterlab-debug-mva5jdxb.log`) shows ?

**Comment by StephanBeer** [comment]
the error log file posted above is generated before running with symlink. WITH symlink there is a new error log file
~~~
14  ✘  proot --link2symlink        4s  /d/d/c/f/u/tmp
:/data/data/com.termux/files/usr/tmp $ jupyter lab build
[LabBuildApp] JupyterLab 1.2.4
[LabBuildApp] Building in /data/data/com.termux/files/usr/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
KeyError: '@jupyterlab/google-drive'
See the log file for details:  /data/data/com.termux/files/usr/tmp/jupyterlab-debug-jn7cv6pd.log
1|:/data/data/com.termux/files/usr/tmp $
~~~

**Comment by StephanBeer** [comment]
jupyterlab-debug-jn7cv6pd.log

**Comment by StephanBeer** [comment]
After reading https://github.com/jupyterlab/jupyterlab/issues/7095 i also removed the '/jupyter/lab/settings/build_config.json' file and started building again but then the npm dependencies errors came back.
~~~
[LabBuildApp] Building in /data/data/com.termux/files/usr/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v13.0.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-inter                    >
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Lockfile has incorrect entry for "@jupyterlab/nbconvert-css@~0.3.4". Ignoring it.
[3/5] Fetching packages...
error An unexpected error occurred: "EACCES: permission denied, copyfile '/data/data/com.termux/files/home/.cache/yarn/v4/.tmp/                    >
info If you think this is a bug, please open a bug report with the information provided in "/data/data/com.termux/files/usr/sha                    >
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_lo                    >
    yield

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/labapp.py", line 97, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/commands.py", line 458, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
~~~

**Comment by xeffyr** [comment]
Error is related to https://github.com/termux/termux-packages/issues/4664.

**Comment by xeffyr** [comment]
Now https://github.com/termux/termux-packages/issues/4664 is fixed.

`pkg upgrade` and try again.

**Comment by StephanBeer** [comment]
Yes the yarn problem seems to be fixed, but its not building because of unmet dependencies

.7                                                                  jupyterlab-debug-r5_rgya_.log
[LabBuildApp] Building in /data/data/com.termux/files/usr/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v13.0.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Lockfile has incorrect entry for "@jupyterlab/nbconvert-css@~0.3.4". Ignoring it.
[3/5] Fetching packages...
warning vscode-languageclient@5.2.1: The engine "vscode" appears to be invalid.
info fsevents@1.2.9: The platform "android" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @krassowski/jupyterlab-lsp@0.7.0" has unmet peer dependency "@jupyterlab/testutils@^1.2.2".
warning " > @krassowski/jupyterlab-lsp@0.7.0" has unmet peer dependency "codemirror@*".
warning "@jupyterlab/git > nbdime@5.0.1" has unmet peer dependency "codemirror@^5.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 42.92s.

[LabBuildApp] > node /data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
[LabBuildApp] yarn run v1.15.2
$ /data/data/com.termux/files/usr/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer
Done in 3.53s.

[LabBuildApp] > node /data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:624
    throw err;
    ^

Error: Command failed: /data/data/com.termux/files/usr/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:603:11)
    at Object.execFileSync (child_process.js:621:15)
    at Object.<anonymous> (/data/data/com.termux/files/usr/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1046:10)
    at internal/main/run_main_module.js:17:11 {
  status: null,
  signal: 'SIGKILL',
  output: [ null, null, null ],
  pid: 2649,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/labapp.py", line 97, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/commands.py", line 458, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/jupyterlab/commands.py", line 669, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

**Comment by StephanBeer** [comment]
Strange....doing the built in the jupyter lab browser UI went without errors

**Comment by sjatkins** [comment]
> Tried building it under/with
> 
> ```
> proot --link2symlink
> ```

what the heck is proot?  Please be a bit more explicit

**Comment by xeffyr** [comment]
>what the heck is proot?

On Android SELinux forbids use of hardlinks. With proot you can emulate them through symlinks (--link2symlink).
