### ISSUE TITLE
Error while compiling debianutils for Android 5

### ISSUE THREAD

**Issue by imprakharshukla** [termux/termux-packages#4719]
### **Problem description**

I am trying to compile all the packages for Android 5 but debianutils fails with the error mentioned below. I am running the docker image on a cloud server and have all the required environment variables in place.

### **Steps to reproduce**
Git clone the repository's android-5 branch, run the docker image and start the compiling with `sudo bash build-all.sh`

### **Additional information**
_**The error that I get is in the attached text file (since the formatting was absurd due to the presence of symbols at the starting of each line)**_

[debianutils_err.txt](https://github.com/termux/termux-packages/files/4010120/debianutils_err.txt)

**Comment by xeffyr** [comment]
1. Do not run build scripts under root (you will break your system during compilation of certain packages).

2. We no longer care about URL validity in `android-5` branch.

Try to find the necessary source archive in https://archive.org/download/termux-repositories-legacy/termux-package-sources-legacy-24.12.2019.tar or on the Internet.

**Comment by imprakharshukla** [comment]
Okay understood but for some reason I get permission denied while creating the debs directory if I'm not under root. Any help with that?

**Comment by xeffyr** [comment]
Make sure that `debs` directory is created in place where you have RW permissions and ownership is correct.

**Comment by imprakharshukla** [comment]
Thanks 😊
