### ISSUE TITLE
GD Extension missing in php 7.4.x

### ISSUE THREAD

**Issue by schwenkreis** [termux/termux-packages#4721]
Just upgraded from 7.3 and cannot install phpspreadsheet anymore. Composer install reports a missing ext-gd. Running php --info on 7.3.x shows the enabled GD, runnning it on the current 7.4 does not contain the gd extension.

**Comment by its-pointless** [comment]
i will get it fixed.

**Comment by its-pointless** [comment]
#4722 
if you want to download binaries now https://cirrus-ci.com/build/4885190862438400

**Comment by schwenkreis** [comment]
Thanks a lot for the speedy fixing. Unfortunately, composer install now complains about the next mssing extension: ext-zip. Here is a link to the composer.json of phpspreadsheet documenting all the needed extensions: https://github.com/PHPOffice/PhpSpreadsheet/blob/master/composer.json

Cheers
Friedemann

**Comment by shzkre** [comment]
Thx

**Comment by xeffyr** [comment]
Closing since missing "gd" extension is available.
Missing "zip" is tracked in https://github.com/termux/termux-packages/issues/4724.
