### ISSUE TITLE
gitea ignores all config file changes and only uses defaults

### ISSUE THREAD

**Issue by KoraggKnightWolf** [termux/termux-packages#4723]
**Problem description**

When installing gitea from the repo and making config file changes they are always entirely ignored. It runs in development mode despite even the default being changed to production when installing. Also the http address cannot be changed, even using the correct syntax as given via https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample

**Steps to reproduce**

1) pkg install gitea
2) cd $PREFIX/etc/gitea && nano app.ini
3) add this as example change the to config file:
[server]
HTTP_ADDR = 127.0.0.1
HTTP_PORT = 6000
4) save the changes and start gitea via command 'gitea' (without the '')

**Expected behavior**

Gitea applies config file changes made in the app.ini file

**Additional information**

Post output of command `termux-info`.

Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.111-16070901 #1 SMP PREEMPT Wed Nov 27 18:27:21 KST 2019 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A750FN

**Comment by xeffyr** [comment]
Gitea does not use configuration file unless the related option on the command line is specified.
Use wrapper `gitea-service.sh` instead of just `gitea`.

**This is not a bug.**

**Comment by KoraggKnightWolf** [comment]
I was editing the wrong configuration file, there was one in $PREFIX/etc/gitea/app.ini yet it wishes to use the one from $PREFIX/bin/custom/conf/app.ini why are both created on Termux? This was the source of my confusion and it takes the values of the latter configuration file that I have specified.

Regards,

Koragg

**Comment by xeffyr** [comment]
This is the official behaviour of `gitea`. Linux distributions manually specify the configuration file to use in their OpenRC or Systemd unit files.

**Comment by xeffyr** [comment]
I can try to add some tweaks like specified in https://docs.gitea.io/en-us/install-from-source/#changing-the-default-custompath-customconf-and-appworkpath.

**Comment by xeffyr** [comment]
Version `1.10.1-1` has default paths changed and now working without wrapper.

**Comment by KoraggKnightWolf** [comment]
Great thanks a lot! Confirmed that changes made in $PREFIX/etc/gitea are now accepted when just running gitea
