### ISSUE TITLE
php: zip extension is missing

### ISSUE THREAD

**Issue by hffariel** [termux/termux-packages#4724]
ZIP extension was available in 7.3.* versions but got removed in the latest 7.4.*,  can we make it back?

**Comment by xeffyr** [comment]
Fixed by https://github.com/termux/termux-packages/commit/5f8432a21f4526936d15b5bf9351ea63379ffdba.

**Comment by schwenkreis** [comment]
phpspreadsheet works now! Thanks a lot again for fixing this  so quickly and Happy New Year!
