### ISSUE TITLE
httpd wont load libphp7.so, error is:  cannot locate symbol "apr_pool_cleanup_null"

### ISSUE THREAD

**Issue by term-x** [termux/termux-packages#4726]
latest version of termux (downloaded Dec 30 2019) on Android 9

pkg install apache2
pkg install php-apache

$ httpd -v
Server version: Apache/2.4.41 (Unix)
Server built:   Dec 30 2019 00:10:20

$  apachectl start
httpd: Syntax error on line 179 of /data/data/com.termux/files/usr/etc/apache2/httpd.conf: Cannot load /data/data/com.termux/files/usr/libexec/apache2/libphp7.so into server: dlopen failed: cannot locate symbol "apr_pool_cleanup_null" referenced by "/data/data/com.termux/files/usr/libexec/apache2/libphp7.so"...

Two days ago I was able to install Termux and apache + php and everything was working just fine.  On those tablets, I see...

$ httpd -v
Server version: Apache/2.4.41 (Unix)
Server built:   Aug 17 2019 22:01:22

thanks

**Comment by canxx99** [comment]
Is the problem solved?

**Comment by xeffyr** [comment]
I have rebuilt the apache2 and some of its dependencies. It works for me now:
```
~ $ apachectl start
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
~ $ pidof httpd
29419 29407 29405 29402
```

I'm closing this.

**Comment by canxx99** [comment]
![Screenshot_20200102_001109](https://user-images.githubusercontent.com/52892904/71646159-69639e00-2cf4-11ea-90f3-5f9606418529.jpg)

normally works but when I add this again there is the same error

**Comment by canxx99** [comment]
old version how can I return?

**Comment by xeffyr** [comment]
Ah, I just didn't enabled it in httpd.conf. Error still happens.

**Comment by xeffyr** [comment]
It is possible to avoid that error with:
```
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libapr-1.so:/data/data/com.termux/files/usr/lib/libaprutil-1.so apachectl start
```
but there another problem happens:
```
[Wed Jan 01 23:30:09.281632 2020] [php7:crit] [pid 30106:tid 539363723720] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
AH00013: Pre-configuration failed
```

**Comment by canxx99** [comment]
yes it was working stably before
If there's a way back to the old version, I can use it.

**Comment by xeffyr** [comment]
There can be available older versions in repository, but officially Termux does not support downgrading due to rolling release update style.

I have pushed fix for that issue - https://github.com/termux/termux-packages/commit/5ee02df0800d889314f6ee3b11917415f063e343. Note that you will need to use `mod_mpm_prefork.so` to solve error regarding threaded MPM:
```
LoadModule mpm_prefork_module libexec/apache2/mod_mpm_prefork.so
LoadModule php7_module libexec/apache2/libphp7.so
#LoadModule mpm_worker_module libexec/apache2/mod_mpm_worker.so
```

**Comment by canxx99** [comment]
![Screenshot_20200102_024246](https://user-images.githubusercontent.com/52892904/71647536-9c645c80-2d09-11ea-993d-2279fc5e5a91.jpg)

sorry i get error again

**Comment by canxx99** [comment]
![Screenshot_20200102_024517](https://user-images.githubusercontent.com/52892904/71647554-f1a06e00-2d09-11ea-8c53-195e2a5c40b5.jpg)

**Comment by xeffyr** [comment]
I specially posted config regarding `mod_mpm*`:
```
LoadModule mpm_prefork_module libexec/apache2/mod_mpm_prefork.so
LoadModule php7_module libexec/apache2/libphp7.so
#LoadModule mpm_worker_module libexec/apache2/mod_mpm_worker.so
```

**Comment by canxx99** [comment]
couldn't fix but thanks for trying to help

**Comment by canxx99** [comment]
I managed to fix it
LoadModule mpm_worker_module libexec/apache2/mod_mpm_worker.so

started working when I deleted it
