### ISSUE TITLE
Package request: pdf2svg

### ISSUE THREAD

**Issue by hesamov** [termux/termux-packages#4727]
**Package description**
Coverts PDF to SVG graphics

**Link to home page and sources**
1. Home page: http://www.cityinthesky.co.uk/opensource/pdf2svg/
2. Source code: https://github.com/dawbarton/pdf2svg

**Additional information**
Used to compile just fine, but now running into issues with Cairo and Poppler. Not sure what's up. I have libcairo and poppler packages installed, but ./configure doesn't find them.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install pdf2svg
```
