### ISSUE TITLE
Mkvtoolnix

### ISSUE THREAD

**Issue by Z3wn** [termux/termux-packages#4731]
https://gitlab.com/mbunkus/mkvtoolnix

multiplex tool for matroska

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install mkvtoolnix
```

**Comment by yurikumo89** [comment]
Hey Can Anyone Tell Me How To Use This Tool On Termux
**__**

**Comment by ravener** [comment]
@yurikumo89 look into the tool yourself. We only provide the packages not support on how to use them.

**Comment by spookyahell** [comment]
Can somebody work on providing an update to this package?

**Comment by A-nglea** [comment]
Has this disappeared from the Termux pkg distro?

**Comment by twaik** [comment]
It is in x11-repo...

**Comment by A-nglea** [comment]
Magic!! Thank you!
