### ISSUE TITLE
How to install dart-sdk

### ISSUE THREAD

**Issue by aprilahijriyan** [termux/termux-packages#4732]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by xeffyr** [comment]
```
pkg install dart
```

**Comment by junaid0102** [comment]
how to build Android apk in termux?
