### ISSUE TITLE
A possible issue in perl (perlio.c.patch)

### ISSUE THREAD

**Issue by kaztost** [termux/termux-packages#4738]
**Problem description**

The patch https://github.com/termux/termux-packages/blob/master/packages/perl/perlio.c.patch can make an issue in the code

**Steps to reproduce**

The considered fragment of perlio.c is

>  int fd = -1;
     char tempname[] = "/tmp/PerlIO_XXXXXX";
     const char * const tmpdir = TAINTING_get ? NULL : PerlEnv_getenv("TMPDIR");
     SV * sv = NULL;
     int old_umask = umask(0177);
     if (tmpdir && *tmpdir) {
                /* if TMPDIR is set and not empty, we try that first */
                sv = newSVpv(tmpdir, 0);
                sv_catpv(sv, tempname + 4);
                fd = Perl_my_mkstemp_cloexec(SvPVX(sv));
     }

 

I think inserting the prefix in tempname makes "tempname + 4" wrong.

I do not know how exactly reproduce this issue runtime. 

```

```

**Comment by xeffyr** [comment]
Thanks, that should be fixed in 24856a6d688121cf9a9f1c93bf573e628913106f.
