### ISSUE TITLE
Package Request: Maxima

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#474]
I know that there is Maxima for Android is available, but having a terminal-based Maxima has many advantages over a GUI one and is more suitable, imho, for the real scientific work.

So, the first step to bring Maxima to Termux is to compile ECL ([https://common-lisp.net/project/ecl/main.html](https://common-lisp.net/project/ecl/main.html)). This is because GCL (GNU Common Lisp) cannot be compiled even in theory because of randomised sbrk() issue which requires kernel modification and so cannot be overcome in Termux.

So, I tried to compile ECL 16.1.2 under Termux and made some progress, which is documented on the ecl-devel list here:

[https://mailman.common-lisp.net/pipermail/ecl-devel/2016-September/011149.html](https://mailman.common-lisp.net/pipermail/ecl-devel/2016-September/011149.html)

I got stuck here:

```
/data/data/com.termux/files/home/Maxima/ecl-16.1.2/src/libffi/src/arm/sysv.S:399:2:
error: invalid instruction
 stmeqia r2, {r0, r1}
```

I don't know much about ARM architecture, so I don't know what to do next. Any ideas?

**Comment by tigran123** [comment]
The above was about compiling ECL under armv7l architecture on Nexus 10 (Android 5.1.1 --- I was wrong to say it was Android 6.0.1). But on Android 6.0.1 with aarch64 architecture (on UMI Super mobile) we get a different error:

```
In file included from /data/data/com.termux/files/home/Maxima/ecl-16.1.2/src/bdwgc/include/private/gc_priv.h:94:
/data/data/com.termux/files/home/Maxima/ecl-16.1.2/src/bdwgc/include/private/gcconfig.h:2035:19: error: redeclaration of '_end' with a different type: 'char []' vs 'int []'
      extern char _end[];
                  ^
/data/data/com.termux/files/home/Maxima/ecl-16.1.2/src/bdwgc/include/private/../gc.h:1622:30: note: previous declaration is here
  extern int __data_start[], _end[];
```

**Comment by tigran123** [comment]
Also, one can actually execute a precompiled binary `maxima.pie` taken from here:

[https://github.com/YasuakiHonda/Maxima-on-Android/tree/master/MaximaOnAndroid/assets](https://github.com/YasuakiHonda/Maxima-on-Android/tree/master/MaximaOnAndroid/assets)

But it is version 5.36.1 and it has some strange pre-compiled defaults (which hopefully can be overridden at run time, I'll see...)

**Comment by tigran123** [comment]
For those who wish to use Maxima 5.36.1 precompiled binary from Maxima on Android project, here are step-by-step installation instructions:

1. Copy `maxima.pie.zip` from [https://github.com/YasuakiHonda/Maxima-on-Android/tree/master/MaximaOnAndroid/assets](https://github.com/YasuakiHonda/Maxima-on-Android/tree/master/MaximaOnAndroid/assets) to `$PREFIX/bin` in Termux and run `termux-elf-cleaner` on it.

2. Create `$HOME/.maxima` directory and unpack `maxima-5.36.1.zip` (from the same URL as maxima.pie) in it.

3. Copy `init.lisp` from the same URL to `$HOME/.maxima` and rename it to be `maxima-init.lisp`.

4. Add the following line to the top of `$HOME/.maxima/maxima-init.lisp` as follows:

```
(setq *maxima-dir* "/data/data/com.termux/files/home/.maxima/maxima-5.36.1")
```

Also, search for the line containing `display2d` and change its value from `imaxima` to `true`:

```
(setq $display2d '$true)
```

That is it, now you can run `maxima` and load any packages --- it actually works!

But still, it would be very nice to be able to compile from sources, so the abovementioned problems with compiling ECL are still outstanding...

**Comment by tigran123** [comment]
Plotting via gnuplot with term set to png also works, BUT what is very odd is that the final output file `maxout.png` only gets created if you login via ssh from outside, but if you work locally then only the driver file `maxout.gnuplot` is created but invocation of gnuplot binary fails with `exec: No such file or directory` error. Very strange, I can't think of a reason at the moment. Any ideas?

**Comment by tigran123** [comment]
That stmeqia problem seems to be well-known and there is even a proposed fix:

[https://lists.freebsd.org/pipermail/freebsd-python/2015-July/008576.html](https://lists.freebsd.org/pipermail/freebsd-python/2015-July/008576.html)

[https://bugs.python.org/issue27627](https://bugs.python.org/issue27627)

[https://lists.freedesktop.org/archives/gstreamer-commits/2013-September/074531.html](https://lists.freedesktop.org/archives/gstreamer-commits/2013-September/074531.html)

I'll try it and see what happens :)

**Comment by tigran123** [comment]
When I said "everything works" I meant "everything except system() function" (and therefore invocation of gnuplot which relies on the same mechanism). I have asked the maintainer of Maxima on Android Yasuaki Honda for help (as he must have overcome the same issue as his maxima.pie 5.36.1 binary works fine):

[https://mailman.common-lisp.net/pipermail/ecl-devel/2016-September/011150.html](https://mailman.common-lisp.net/pipermail/ecl-devel/2016-September/011150.html)

I'll continue working on it today.

**Comment by dkochmanski** [comment]
@tigran123 how did you get rid of the `undefined tkill` problem?

**Comment by tigran123** [comment]
@dkochmanski That problem only occurs on aarch64 architecture (and Android 6.0.1), not armv7l (Android 5.1.1). I only managed to compile it on armv7l, see my post above. So, on Android 6.0.1 I just used the old 5.36.1 Maxima binary ("pie" format) from "Maxima on Android" project.

**Comment by espectalll** [comment]
Any updates on this? Has anyone packaged it on their own repository?

**Comment by tigran123** [comment]
I managed to get Wolfram Mathematica to work on any Android device, so the issue of getting Maxima on Android became no longer relevant :)

**Comment by espectalll** [comment]
I still am personally interested in Maxima because it's free software and it's being recommended for my Algebra studies, but glad it's no longer relevant for you

**Comment by its-pointless** [comment]
espectall you can compile it yourself just have to install ecl first which is available in my apt repo

**Comment by jimipb** [comment]
Any updates? I tried building it with esl from its-pointless' repo. I get an error bc atomic_ops.h isnt found, tho.

**Comment by tigran123** [comment]
It is no longer necessary, because one can run full Wolfram Mathematica 12.0.1 (and 11.2 which is better in some ways, e.g. for accessing offline data which in 12 was moved to "online-only") on Android. Just take the Raspberry Pi binaries, copy them in UserLAnd (for latest Android or GNURoot Debian) and it just works (just make the proper symlinks for shared libraries, add the arch to the exec scripts etc)

**Comment by tigran123** [comment]
@its-pointless What is the name of the package, containing ecl? I tried with `pkg install ecl` and it didn't work. And I do have package `numpy` installed, which means I have added your repository.

I have just now put together Maxima 5.41.0 for the latest (current) Termux and will now make it available, but if you are saying that there is ECL available and I could compile Maxima 5.44.0 against it, that would be even better.

(Yes I miss Maxima, even though I have Mathematica on my Android devices :)

**Comment by tigran123** [comment]
Here it is [http://www.bibles.org.uk/Maxima-5.41.0-Termux.tar.gz](http://www.bibles.org.uk/Maxima-5.41.0-Termux.tar.gz) Be careful when unpacking the archive -- it overrides `~/.profile`.

And here is how it looks
![](http://www.bibles.org.uk/screenshots/Maxima-in-Termux.jpg)

**Comment by tigran123** [comment]
Here it is [http://www.bibles.org.uk/Maxima-5.41.0-Termux.tar.gz](http://www.bibles.org.uk/Maxima-5.41.0-Termux.tar.gz)

Be careful when unpacking the archive as it overwrites your `~/.profile`.

And here is the screenshot:

![screenshot](http://www.bibles.org.uk/screenshots/Maxima-in-Termux.jpg)

**Comment by xtkoba** [comment]
Superseded by #8169. Please close.
