### ISSUE TITLE
upgrade php Can't print text

### ISSUE THREAD

**Issue by RcX-a11** [termux/termux-packages#4740]
just run simple code like
echo ("Welcome New PHP 7.4");
and not show anything :')

**Comment by RossComputerGuy** [comment]
Try without the parenthesis.

**Comment by xeffyr** [comment]
Issue is unconfirmed.
Make sure that **all packages are up-to-date**.

```
~ $ cat test2.php 
<?
echo("Hello world\n");
?>
~ $ php test2.php 
Hello world
```
