### ISSUE TITLE
My termux always CANNOT LINK EXECUTABLE "php": library "libicuio.so.65

### ISSUE THREAD

**Issue by AddblogMe** [termux/termux-packages#4741]
why every time i run termux this notification appears,I have reinstalled but it still happens like this
![Screenshot_2020-01-04-08-54-10-961_com termux](https://user-images.githubusercontent.com/47151864/71760037-b9f01c80-2ee9-11ea-8196-a2eac2221234.png)
, please help 🙏
CANNOT LINK EXECUTABLE "php": library "libicuio.so.65" not found

**Comment by RossComputerGuy** [comment]
What's the output of `termux-info`?

**Comment by tammy0049** [comment]
That was a same problem i have any one can help us

**Comment by tammy0049** [comment]
Help us

**Comment by tammy0049** [comment]
![Screenshot_20200104_151009](https://user-images.githubusercontent.com/59498134/71761312-59baa400-2f04-11ea-9570-30310af07a8b.jpg)
Mr.ross this is the info

**Comment by tammy0049** [comment]
I hope you help us

**Comment by diehard88** [comment]
@tammy0049 

```
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/ termux extras
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-21 root stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-21 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-21 games stable
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux kali 4.4.78-14803871 #1 SMP PREEMPT Thu Nov 29 19:38:27 KST 2018 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T830
$
```

```

```

**Comment by RossComputerGuy** [comment]
This looks to be an Android 8 aarch64 only issue so far I can see.

**Comment by Grimler91** [comment]
Temporary fix: `apt install libicu`

**Comment by tammy0049** [comment]
So how can fix it

**Comment by Grimler91** [comment]
It has been fixed in php 7.4.1-6: https://github.com/termux/termux-packages/commit/b12c9448b6ad8802f9c64387b2c93cdfccb4d60c, which should be available in a few minutes. 

Thanks for reporting!

**Comment by KARANAJDJEUEKSIDN** [comment]
l also had the problem  link executable php library libicuio.so.69  please help me

**Comment by KARANAJDJEUEKSIDN** [comment]
please help me

**Comment by KARANAJDJEUEKSIDN** [comment]
please help me

**Comment by KARANAJDJEUEKSIDN** [comment]
@Grimler91  please help me
