### ISSUE TITLE
what is the meaning of this👇

### ISSUE THREAD

**Issue by cim25** [termux/termux-packages#4742]
CANNOT LINK EXECUTABLE "php": library "libicuio.so.65" not found
Aborted

**Comment by xeffyr** [comment]
Post `termux-info` output.
And make sure that everything is up to date.

**Comment by cim25** [comment]
what do you mean how can i fix it

**Comment by xeffyr** [comment]
> what do you mean

??

> how can i fix it

**Upgrade your packages**. I didn't know why that is not understandable...

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/4741#issuecomment-570768212
