### ISSUE TITLE
files deleted with 'rm' still showing in the stock 'Files' app on Android 10

### ISSUE THREAD

**Issue by stuart-little** [termux/termux-packages#4743]
**Problem description**
I am on aarch64, running Android 10 and `termux 0.8.4`.

Android 10 apparently comes with a non-removable stock file manager called `Files`. A tab slides from the left hand side of the screen to reveal shortcuts, including one to the `Download` folder.

A file copied to the `Download` folder through the GUI file manager does not disappear from the `Files` view of the `Download` folder if removed with `termux`' `rm` command.

On the other hand, if I copy the file to `${HOME}/storage/downloads` in the terminal with `cp` and then remove it with `rm` these changes are reflected in `Files` just fine.

The terminal reports no difference in permissions between the two copy operations (GUI vs `cp`).

**Steps to reproduce**
(1) Copy some file to the 'Download' folder (the one linked to by `${HOME}/storage/downloads` after running `termux-setup-storage`) *in a GUI file manager*.

(2) Open `termux` and `rm` the file.

(3) In the `Files` app (stock file manager on Android 10, and as far as I can tell unremovable) the file is still present when opening the `Downloads` shortcut in the left hand tab.

**Expected behavior**
The file should be gone after issuing the `rm` command.

**Additional information**
```
Packages CPU architecture:                           aarch64
Subscribed repositories:                             # sources.list
deb https://termux.org/packages/ stable main
# sources.list.d/science.list.bak
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# sources.list.d/game.list.bak
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date                              Android version:
10
Kernel build information:                            Linux localhost 4.9.179-perf+ #1 SMP PREEMPT Sat Dec 14 20:49:05 CST 2019 aarch64 Android
Device manufacturer:                                 OnePlus
Device model:
ONEPLUS A6013
```
**Edit**

According to [this thread](https://forums.oneplus.com/threads/a-new-files-app-popped-up.1164470/), `Files` is Android 10's replacement of the download manager.

It would still be good to get to the bottom of the strange behavior.

**Comment by xeffyr** [comment]
This is issue of file manager and not Termux.

I also should note that file managers do not display the raw file system, instead they show what Android OS provides through storage access framework.

**Comment by Grimler91** [comment]
What happens if you try to open the file through the GUI after removing it in termux? I guess the file is deleted but android doesn't know it. 

Try running `termux-media-scan -r ~/storage/downloads` after rm and see if the file then disappears from the GUI

**Comment by stuart-little** [comment]
> What happens if you try to open the file through the GUI after removing it in termux? I guess the file is deleted but android doesn't know it.
> 

You are correct (I'd tried, but forgot to mention it): opening the file after deletion fails with an uninformative error. Ditto for renaming/moving it, etc.

So yes, `Files` is unaware of the deletion. *Other* file managers see it though. This happens specifically with this file manager.

> Try running `termux-media-scan -r ~/storage/downloads` after rm and see if the file then disappears from the GUI

It did, thank you!

---

P.S.

I did not have `Termux:API` installed, but I'll hold on to it now that I've tried it for this.

**Comment by stuart-little** [comment]
This is to report that the fix via 

```
termux-media-scan -r ~/storage/downloads
```
appears to have stopped working. Specifically, the files app (download manager) on Android 10 does not recognize filename changes made on the command line. I am doing the following:

- downloaded a pdf file to my Downloads folder, and named it `boo.pdf`
- renamed it to `bo\ o.pdf` (inserting a space) in `termux`, by navigating to `storage/download` and issuing a `mv` command

The native Android `Files` app now lists both files, `boo.pdf` and `bo o.pdf`. Further issuing a 

```
termux-media-scan -r ~/storage/downloads
```
does *not* fix this.
