### ISSUE TITLE
Package request: jpegoptim

### ISSUE THREAD

**Issue by Py5cr1pt** [termux/termux-packages#4745]
**Package description:**

jpegoptim - utility to optimize/compress JPEG files

**Source code:**

https://github.com/tjko/jpegoptim

**Comment by xeffyr** [comment]
Closing as package is already [available](https://github.com/termux/termux-packages/commit/21855fdbe28119b58b58f350c39059fc9da258da#diff-b3a119c70ea4abb75ae465f0c158509f).
```
pkg install jpegoptim
```
