### ISSUE TITLE
Lambda expressions are allowed only at source level 1.8 or above

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#4748]
**Description**
Lambda expressions are allowed only at source level 1.8 or above

**Steps to reproduce**
[`~/buildAPKs/build.github.bash termux`](https://github.com/BuildAPKs/buildAPKs.github/blob/master/build.github.bash)
Termux app, float and widget trigger this error.

**Expected behavior**
Compiles as expected.

**Additional information**
This appears to be a bug in `ecj` that was reported https://bugs.eclipse.org/bugs/show_bug.cgi?id=535969 here, and patched https://bugs.eclipse.org/bugs/show_bug.cgi?id=477894 here.

> Special handling for local classes inside a lambda was intentionally added on behalf of bug 427265.

> Verified with Eclipse 4.9 m2 Build id: I20180731-0800

As the current version is `Eclipse Compiler for Java(TM) v20190522-0428, 3.18.0, Copyright IBM Corp 2000, 2015. All rights reserved.`, is there a workaround for Lambda expressions when compiling Termux on device?

**Comment by xeffyr** [comment]
Lambda expressions were added in Java 8. There no way to use them below that version.
Our `ecj` enforces compatibility for Java 1.7 which is reasonable default for Android.

**Comment by SDRausty** [comment]
> Our ecj enforces compatibility for Java 1.7 

I found what you a referring to 
 https://github.com/termux/termux-packages/blob/master/packages/ecj/ecj and I would like to try changing the -7 to a -8 to see if Lambda expressions work when attempting to build https://github.com/termux/ on my smartphone.

I would like to only rebuild `ecj` on device using the minimum resources possible.  What is the simplest way of trying to compile `ecj` on device in Termux?

**Comment by xeffyr** [comment]
> What is the simplest way of trying to compile ecj on device in Termux?

1. No need to recompile. Edit the wrapper script:
```
cp $PREFIX/bin/ecj ~/
nano ~/ecj
```

2. Replace `-7` with `-8`.

3. Use custom wrapper instead original. Example: `$HOME/ecj MyClass.java`.

**Comment by SDRausty** [comment]
>> What is the simplest way of trying to compile ecj on device in Termux?

> No need to recompile

Thank you for this information @xeffyr.  This https://github.com/termux/termux-packages/wiki makes things a little bit easier.  

> Replace -7 with -8.

Replacing -7 with -8 in ~/ecj resolves the issue and  the error message has moved to:

```
The type java.lang.invoke.LambdaMetafactory cannot be resolved. It is indirectly referenced from required .class files
```

> referenced from required .class files

Do you know where the required .class files are referenced?

**Comment by pollen5** [comment]
Android does not have those files, Java 8 support is partial, i fixed it by using a mock package that provided those classes and use d8 to desugar them before runtime.
