### ISSUE TITLE
geoip2-database fails to build

### ISSUE THREAD

**Issue by 9001** [termux/termux-packages#4750]
**Problem description**
compilation fails because this link is invalid: https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

upstream has intentionally made it unavailable: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Steps to reproduce**
`./build-all.sh`

**Expected behavior**
build succeeds

**Additional information**
n/a

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/21110f6ab439f3a372b924821aa3dac6b93128ae (will reuse files from v20191221).
