### ISSUE TITLE
new session

### ISSUE THREAD

**Issue by remo7777** [termux/termux-packages#4752]
what happened when i open "new session" it login with `pwd` path of "old session"
it happened after new update of termux app

**Comment by remo7777** [comment]
![Screenshot_2020-01-06-11-13-15-88_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/28594846/71797798-9954cd80-3075-11ea-9251-c1ce9e09d1e7.png)

**Comment by RossComputerGuy** [comment]
I don't see any issues

**Comment by remo7777** [comment]
on new session pwd should $HOME, I guess

**Comment by RossComputerGuy** [comment]
Most terminal emulators I've seen spawns the shell on the last opened directory to make things easier, I suggest opening an issue suggesting the ability to disable this in the application repo.

**Comment by remo7777** [comment]
@RossComputerGuy i opened 5th new session still same 😭😭😭

**Comment by RossComputerGuy** [comment]
Yeah because that's a feature.

**Comment by remo7777** [comment]
![Screenshot_2020-01-06-12-01-59-63](https://user-images.githubusercontent.com/28594846/71799851-6a8e2580-307c-11ea-9429-757384e614ba.png)
Ah i read now the updates it mentioned on last line...👌👌
may it helpful for others so i close this issue...
