### ISSUE TITLE
Can't upgrade to new termux. Upgrade package not found

### ISSUE THREAD

**Issue by nstgc** [termux/termux-packages#4756]
I noticed the legacy warning in Termux (took me a while to notice). Searching Google taught me that the Android 5 branch is being discontinued. I also found https://github.com/termux/termux-app/issues/1393#issuecomment-568463887 which says how to upgrade. However, when I try `pkg install termux-upgrade-repo` the package is not found. I had previously been keeping termux up-to-date.

**Comment by xeffyr** [comment]
> However, when I try pkg install termux-upgrade-repo the package is not found.

Of course not found. Instead of `pkg install .....` you need just
```
termux-upgrade-repo
```
