### ISSUE TITLE
html2text

### ISSUE THREAD

**Issue by allan-371** [termux/termux-packages#4757]
**Package description**

html2text is an HTML to plain text converter.
html2text reads HTML documents from the command line (or from standard input), converts each one to a plain text string, and writes the output to file or terminal.

**Link to home page and sources**
1. Home page: http://www.mbayer.de/html2text/
2. Source code: http://www.mbayer.de/html2text/files.shtml

**Comment by remo7777** [comment]
> **Package description**
> 
> html2text is an HTML to plain text converter.
> html2text reads HTML documents from the command line (or from standard input), converts each one to a plain text string, and writes the output to file or terminal.
> 
> **Link to home page and sources**
> 
> 1. Home page: http://www.mbayer.de/html2text/
> 2. Source code: http://www.mbayer.de/html2text/files.shtml

`apt install python && pip install html2text`

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install html2text
```
