### ISSUE TITLE
rinetd

### ISSUE THREAD

**Issue by sudofox** [termux/termux-packages#4761]
rinetd is a TCP proxy. You can tell it to listen on interface A (or on all interfaces) on port B, and forward to IP C on port D. It's very simple and very useful.

**Link to home page and sources**
1. Home page: https://www.lenzg.net/rinetd/rinetd.html 
2. Source code: https://github.com/boutell/rinetd

**Additional information**
Have you compiled or tried to compile the package on device?

I have in the past but wasn't able to really get it working. I'm just now trying to find a package for it instead.

**Comment by xploitednoob** [comment]
my repo has this package
repo link: https://github.com/termdroid/packages
It will be added to termux official repo after some changes to the build.sh file

**Comment by xeffyr** [comment]
Added in https://github.com/termux/termux-packages/commit/66282c5bc180e7566734951a546e573eaf0f9158. Package for installation will be available shortly.
