### ISSUE TITLE
Backup and build all packages on device.

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#4765]
**Package description**

Backup and build all packages on device:  As https://wiki.termux.com/wiki/Backing_up_Termux has Termux system and backup information,  wouldn't it be nice to build any package on device in Termux in one tap.  Recovery, if necessary, one tap recovery in failsafe mode.

**Additional information**
> Have you compiled or tried to compile the package on device?

Yes.  Thank you for the https://github.com/termux/termux-packages/wiki page :1st_place_medal: 

> * If it didn't work then please provide the error you ran into.

As
```
$ ./build-package.sh cmatrix
cmatrix@2.0 built - skipping (rm /data/data/com.termux/files/home/.termux-build/.built-packages/cmatrix to force rebuild)
```
but
```
$ ./build-package.sh coreutils
coreutils@8.31-8 installed - skipping
```
* If it did work then please share any patches that you had to apply.

Shared https://github.com/termux/termux-packages/pulls/SDRausty

**Link to home page and sources**
1. Home page: https://sdrausty.github.io/
2. Source code: https://buildapks.github.io/

**Comment by xeffyr** [comment]
This is expected behaviour. If package is available in $PREFIX, it won't be built unless forced.
Also not all packages can be safely built on device with ./build-package.sh.

Example:
```
./build-package.sh -f <package names>
```

And please, the issue about on-device builds is https://github.com/termux/termux-packages/issues/4157.
