### ISSUE TITLE
GDB is not displaying source for program compiled with clang

### ISSUE THREAD

**Issue by ChoiChoongHo94** [termux/termux-packages#4768]
**Problem description**
please refer to below site:
https://www.reddit.com/r/termux/comments/eksa31/gdb_warning_dynamic_section_for/

**Additional information**
![termux-info](https://user-images.githubusercontent.com/32029458/71969640-6dd70c00-324a-11ea-8737-68a43c2689bd.jpg)

**Comment by xeffyr** [comment]
This is `clang` issue and not GDB's. Interesting that it not does happen when libc functions are not used (e.g. empty `main()` function, without puts/printf/others...).

***

GDB works fine with programs compiled with NDK on PC. E.g. debug build of coreutils under gdb:
![Screenshot_20200110-140741_Termux](https://user-images.githubusercontent.com/25881154/72152332-536c7200-33b3-11ea-9cbc-31d78dd44ddc.jpg)

![Screenshot_20200110-140821_Termux](https://user-images.githubusercontent.com/25881154/72152342-57988f80-33b3-11ea-8a3f-23f3d1445664.jpg)

**Comment by xeffyr** [comment]
Suggesting to try out `lldb` as alternative to `gdb`. It works well with Termux clang:
![Screenshot_20200110-142317_Termux](https://user-images.githubusercontent.com/25881154/72152863-eeb21700-33b4-11ea-94e1-8c37aa0003b2.jpg)

**Comment by ChoiChoongHo94** [comment]
Thank you!

`lldb` is a good alternative. I think I can use this for the time being.
But, It would be better if I can use the `g++` compiler in the future.

**Comment by shadmansaleh** [comment]
compile with -gdwarf-4 flag insted of -g and gdb will work fine .

**Comment by saurabhchardereal** [comment]
> compile with -gdwarf-4 flag insted of -g and gdb will work fine .

`clang` and `gcc` are both working fine with `-g`.

Also, @xeffyr, it seems this issue should be close now as `gdb` is now showing source code compiled with both clang and gcc.

**Comment by thunder-coding** [comment]
Since NDK r23, support for GDB has been ended and will be removed in next NDK release. From NDK changelog:
> Support for GDB has ended. GDB will be removed from the next release. Use LLDB instead. Note that ndk-gdb uses LLDB by default.

**Comment by Grimler91** [comment]
> Since NDK r23, support for GDB has been ended and will be removed in next NDK release. From NDK changelog:
> 
> > Support for GDB has ended. GDB will be removed from the next release. Use LLDB instead. Note that ndk-gdb uses LLDB by default.

That probably means that gdb will not be shipped with the ndk anymore, on device gdb should continue to work. 

In any case, closing since this does not seem to be an issue any more
