### ISSUE TITLE
Graphviz Python API does not render text correctly in graphical output

### ISSUE THREAD

**Issue by Fernal73** [termux/termux-packages#4769]
**Problem description**
Graphviz API in Python does not produce the desired graphic output. Characters are output as numerals instead.

**Steps to reproduce**
`pkg install graphviz`
`pip install graphviz`

```python

#!/usr/bin/env python
"""Graphviz test."""
from graphviz import Digraph


def main():
    """Execute main."""
    dot = Digraph(comment='The Round Table',
                  format='png',
                  node_attr={'shape': 'plaintext'})
    dot.node('A', 'King Arthur')
    dot.node('B', 'Sir Bedevere the Wise')
    dot.node('L', 'Sir Lancelot the Brave')

    dot.edges(['AB', 'AL'])
    dot.edge('B', 'L', constraint='false')
    print(dot.source)  
    dot.render('round-table.gv', view=False)


if __name__ == "__main__":
    main()
```
`chmod +744 graphviztest.py`
# source above
`./graphviztest.py

Output:
![round-table gv](https://user-images.githubusercontent.com/24714685/71971117-f2686100-322f-11ea-83ce-c695f11d5ab8.png)

**Expected behavior**
The PNG or PDF file must render correctly. 
It works as expected for Arch Linux on Termux.
![round-table gv](https://user-images.githubusercontent.com/24714685/71971202-23489600-3230-11ea-92fc-62ed56e8f077.png)

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# sources.list.d/pointless.bak
deb https://its-pointless.github.io/files/ termux extras
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.18.31-perf-g89c85bf #1 SMP PREEMPT Tue Oct 22 13:55:14 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Y1

```

**Comment by xeffyr** [comment]
I remember issue where text in X11 packages was rendered in same way with broken characters.
Should be fixed by adding any TTF font package.

**Comment by Fernal73** [comment]
I'm not familiar with font packages needed. Which one or ones do I need to install?

**Comment by xeffyr** [comment]
> That doesn't need any fonts to be installed.

Graphviz uses `pango` for text rendering.

**Comment by xeffyr** [comment]
> Which one or ones do I need to install?

`pkg install ttf-dejavu`

But I'm not adding font as dependency for `graphviz` because it works even without that package (related to https://github.com/termux/termux-packages/blob/master/packages/fontconfig/build.sh#L15 ?).

Files generated by script:
[round-table.gv.gz](https://github.com/termux/termux-packages/files/4035683/round-table.gv.gz)
![round-table gv](https://user-images.githubusercontent.com/25881154/71985299-05306500-3233-11ea-8d5d-17d655a5544a.png)

**Comment by Fernal73** [comment]
Installing the fonts worked for me. Installing pango uninstalled pango-x which supplies pango.

**Comment by Fernal73** [comment]
What do you mean by not adding the font as dependency? It's shown to not work without it. Are you suggesting that the fonts above are installed by default and that they somehow went missing from my installation? 
Also, shouldn't the same fonts or fonts that work with Graphviz be available in Termux Styles?

**Comment by Fernal73** [comment]
https://www.archlinux.org/packages/extra/x86_64/graphviz/

**Comment by xeffyr** [comment]
> It's shown to not work without it.

Ok, I will add.

> Are you suggesting that the fonts above are installed by default

By default the fonts from /system/fonts should be used (this is what happens on my device) because of configuration option in https://github.com/termux/termux-packages/blob/master/packages/fontconfig/build.sh#L15.

> Also, shouldn't the same fonts or fonts that work with Graphviz be available in Termux Styles?

Isn't TTF DejaVu font available in https://github.com/termux/termux-styling/blob/master/app/src/main/assets/fonts/DejaVu.ttf ?

**Comment by Fernal73** [comment]
Yes, dejavu-fonts are available in Styles.
That has no impact on GraphViz output at all, though.

**Comment by Fernal73** [comment]
List of fonts under /system/fonts on my system:

AndroidClock.ttf
CarroisGothicSC-Regular.ttf
ComingSoon.ttf
CutiveMono.ttf
DancingScript-Bold.ttf
DancingScript-Regular.ttf
DroidSans-Bold.ttf
DroidSans.ttf
DroidSansMono.ttf
MiLanProVF.ttf
MitypeClock.otf
MitypeClockMono.otf
MitypeMonoVF.ttf
MitypeVF.ttf
Miui-Bold.ttf
Miui-Light.ttf
Miui-Regular.ttf
Miui-Thin.ttf
MiuiEx-Bold.ttf
MiuiEx-Light.ttf
MiuiEx-Regular.ttf
NotoColorEmoji.ttf
NotoNaskhArabic-Bold.ttf
NotoNaskhArabic-Regular.ttf
NotoNaskhArabicUI-Bold.ttf
NotoNaskhArabicUI-Regular.ttf
NotoSansArmenian-Bold.ttf
NotoSansArmenian-Regular.ttf
NotoSansBalinese-Regular.ttf
NotoSansBamum-Regular.ttf
NotoSansBatak-Regular.ttf
NotoSansBengali-Bold.ttf
NotoSansBengali-Regular.ttf
NotoSansBengaliUI-Bold.ttf
NotoSansBengaliUI-Regular.ttf
NotoSansBuginese-Regular.ttf
NotoSansBuhid-Regular.ttf
NotoSansCJK-Regular.ttc
NotoSansCanadianAboriginal-Regular.ttf
NotoSansCham-Bold.ttf
NotoSansCham-Regular.ttf
NotoSansCherokee-Regular.ttf
NotoSansCoptic-Regular.ttf
NotoSansDevanagari-Bold.ttf
NotoSansDevanagari-Regular.ttf
NotoSansDevanagariUI-Bold.ttf
NotoSansDevanagariUI-Regular.ttf
NotoSansEthiopic-Bold.ttf
NotoSansEthiopic-Regular.ttf
NotoSansGeorgian-Bold.ttf
NotoSansGeorgian-Regular.ttf
NotoSansGlagolitic-Regular.ttf
NotoSansGujarati-Bold.ttf
NotoSansGujarati-Regular.ttf
NotoSansGujaratiUI-Bold.ttf
NotoSansGujaratiUI-Regular.ttf
NotoSansGurmukhi-Bold.ttf
NotoSansGurmukhi-Regular.ttf
NotoSansGurmukhiUI-Bold.ttf
NotoSansGurmukhiUI-Regular.ttf
NotoSansHanunoo-Regular.ttf
NotoSansHebrew-Bold.ttf
NotoSansHebrew-Regular.ttf
NotoSansJavanese-Regular.ttf
NotoSansKannada-Bold.ttf
NotoSansKannada-Regular.ttf
NotoSansKannadaUI-Bold.ttf
NotoSansKannadaUI-Regular.ttf
NotoSansKayahLi-Regular.ttf
NotoSansKhmer-Bold.ttf
NotoSansKhmer-Regular.ttf
NotoSansKhmerUI-Bold.ttf
NotoSansKhmerUI-Regular.ttf
NotoSansLao-Bold.ttf
NotoSansLao-Regular.ttf
NotoSansLaoUI-Bold.ttf
NotoSansLaoUI-Regular.ttf
NotoSansLepcha-Regular.ttf
NotoSansLimbu-Regular.ttf
NotoSansLisu-Regular.ttf
NotoSansMalayalam-Bold.ttf
NotoSansMalayalam-Regular.ttf
NotoSansMalayalamUI-Bold.ttf
NotoSansMalayalamUI-Regular.ttf
NotoSansMandaic-Regular.ttf
NotoSansMeeteiMayek-Regular.ttf
NotoSansMongolian-Regular.ttf
NotoSansMyanmar-Bold.ttf
NotoSansMyanmar-Regular.ttf
NotoSansMyanmarUI-Bold.ttf
NotoSansMyanmarUI-Regular.ttf
NotoSansNKo-Regular.ttf
NotoSansNewTaiLue-Regular.ttf
NotoSansOlChiki-Regular.ttf
NotoSansOriya-Bold.ttf
NotoSansOriya-Regular.ttf
NotoSansOriyaUI-Bold.ttf
NotoSansOriyaUI-Regular.ttf
NotoSansRejang-Regular.ttf
NotoSansSaurashtra-Regular.ttf
NotoSansSinhala-Bold.ttf
NotoSansSinhala-Regular.ttf
NotoSansSundanese-Regular.ttf
NotoSansSylotiNagri-Regular.ttf
NotoSansSymbols-Regular-Subsetted.ttf
NotoSansSymbols-Regular-Subsetted2.ttf
NotoSansSyriacEstrangela-Regular.ttf
NotoSansTagbanwa-Regular.ttf
NotoSansTaiLe-Regular.ttf
NotoSansTaiTham-Regular.ttf
NotoSansTaiViet-Regular.ttf
NotoSansTamil-Bold.ttf
NotoSansTamil-Regular.ttf
NotoSansTamilUI-Bold.ttf
NotoSansTamilUI-Regular.ttf
NotoSansTelugu-Bold.ttf
NotoSansTelugu-Regular.ttf
NotoSansTeluguUI-Bold.ttf
NotoSansTeluguUI-Regular.ttf
NotoSansThaana-Bold.ttf
NotoSansThaana-Regular.ttf
NotoSansThai-Bold.ttf
NotoSansThai-Regular.ttf
NotoSansThaiUI-Bold.ttf
NotoSansThaiUI-Regular.ttf
NotoSansTibetan-Bold.ttf
NotoSansTibetan-Regular.ttf
NotoSansTifinagh-Regular.ttf
NotoSansVai-Regular.ttf
NotoSansYi-Regular.ttf
NotoSerif-Bold.ttf
NotoSerif-BoldItalic.ttf
NotoSerif-Italic.ttf
NotoSerif-Regular.ttf
Roboto-Black.ttf
Roboto-BlackItalic.ttf
Roboto-Bold.ttf
Roboto-BoldItalic.ttf
Roboto-Italic.ttf
Roboto-Light.ttf
Roboto-LightItalic.ttf
Roboto-Medium.ttf
Roboto-MediumItalic.ttf
Roboto-Regular.ttf
Roboto-Thin.ttf
Roboto-ThinItalic.ttf
RobotoCondensed-Bold.ttf
RobotoCondensed-BoldItalic.ttf
RobotoCondensed-Italic.ttf
RobotoCondensed-Light.ttf
RobotoCondensed-LightItalic.ttf
RobotoCondensed-Regular.ttf

**Comment by Fernal73** [comment]
Fonts under usr/share/fonts/TTF:
DejaVuMathTeXGyre.ttf
DejaVuSans-Bold.ttf
DejaVuSans-BoldOblique.ttf
DejaVuSans-ExtraLight.ttf
DejaVuSans-Oblique.ttf
DejaVuSans.ttf
DejaVuSansCondensed-Bold.ttf
DejaVuSansCondensed-BoldOblique.ttf
DejaVuSansCondensed-Oblique.ttf
DejaVuSansCondensed.ttf
DejaVuSansMono-Bold.ttf
DejaVuSansMono-BoldOblique.ttf
DejaVuSansMono-Oblique.ttf
DejaVuSansMono.ttf
DejaVuSerif-Bold.ttf
DejaVuSerif-BoldItalic.ttf
DejaVuSerif-Italic.ttf
DejaVuSerif.ttf
DejaVuSerifCondensed-Bold.ttf
DejaVuSerifCondensed-BoldItalic.ttf
DejaVuSerifCondensed-Italic.ttf
DejaVuSerifCondensed.ttf
fonts.dir
fonts.scale

**Comment by Fernal73** [comment]
On Arch Linux:

The use/share/fonts directory has gsfonts installed.

A more suitable fix would be to have these fonts available on Termux as well. Ghostscript is available but not gsfonts (as a package).
