### ISSUE TITLE
Package Request: Github's hub

### ISSUE THREAD

**Issue by sodoku** [termux/termux-packages#477]
The hub cli from github makes it very simple to add pull requests from the terminal. You can also clone github repos using `author/repo` instead of `git@github.com:author/repo` which is less typing on a small keybord :)

There are binary releases for ARM at https://github.com/github/hub/releases

**Comment by sodoku** [comment]
Th binary (32bit ARM), seem to have problems with accessing the API:

> ~/hub/hub-linux-arm-v2.2.8/bin/hub issue
Get https://api.github.com/repos/easybib/office365-add-in/issues: dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:43301->[::1]:53: read: connection refused

**Comment by fornwall** [comment]
Thanks for the suggestion! The package can now be installed with `apt update && apt install hub`.

**Comment by sodoku** [comment]
Thank you for adding it so fast!
