### ISSUE TITLE
Cannot execute binary/No such file

### ISSUE THREAD

**Issue by RajaMBZ** [termux/termux-packages#4770]
I'm stuck, totally:

![Screenshot_20200108_195714_com termux](https://user-images.githubusercontent.com/34947728/71992948-18096080-3258-11ea-8cc1-afb90951c9cd.jpg)

Unable to run "jcli" file. I've tried everything and went through most of the previously reported similar issues, but no luck. Termux-exec, Termux-fix-shebang, nothing is helping.

Help will be greatly appreciated.

**Comment by xeffyr** [comment]
You cannot run binaries compiled for normal Linux distributions (i.e. ones based on GNU libc or Musl libc).

**Comment by xeffyr** [comment]
Install Ubuntu in chroot/proot like shown in https://wiki.termux.com/wiki/Ubuntu and you should be able to execute your binary inside it.

**Comment by RajaMBZ** [comment]
Alright, Thanks! I'll try that right away, and edit this comment with an update.
