### ISSUE TITLE
pkg upgrade gives me error, even after reinstalling termux

### ISSUE THREAD

**Issue by Abhilashamale** [termux/termux-packages#4775]
```
Setting up net-tools (1.60.2017.02.21-3) ...
Setting up inetutils (1.9.4-8) ...
Setting up busybox (1.31.1-4) ...

Configuration file '/data/data/com.termux/files/usr/var/service/ftpd/run'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** run (Y/I/N/O/D/Z) [default=N] ? Y
Y
Installing new version of config file /data/data/com.termux/files/usr/var/service/ftpd/run ...
Setting up command-not-found (1.45) ...
$

```

**Issue** - After reinstalling termux app and `pkg upgrade` I'm getting above error it seems if I choose `pkg upgrade -y` it works but if I choose `pkg upgrade` then `y` it failed to upgrade packages.

So my question is, why I'm getting this error even after reinstalling app again and how to solve it?

**Comment by Grimler91** [comment]
It's not an error. It is asking you if you want to keep the existing version of `$PREFIX/var/service/ftpd/run`, or if you want to install the new one in busybox 1.31.1-4. The difference probably comes from [this commit](https://github.com/termux/termux-packages/commit/5208bf2fb799777f184da9b480f28a86d7d616c1#diff-21f79205ec8983e61dc863ac9634a4e0) unless you have edited the run script yourself.
