### ISSUE TITLE
termbox

### ISSUE THREAD

**Issue by Cvar1984** [termux/termux-packages#4776]
**Package description**
Library for writing text-based user interfaces

**Link to home page and sources**
1. Home page:
2. Source code: https://github.com/nsf/termbox

**Additional information**
I have compile termbox in my device, and its fine

**Comment by ifurther** [comment]
It says "This library is no longer maintained."

**Comment by xeffyr** [comment]
> This library is no longer maintained.

https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests

Termbox readme: https://github.com/nsf/termbox#important

Leaving package for on-device compiling for now (if someone really needs it).
