### ISSUE TITLE
Import error while trying to run python file

### ISSUE THREAD

**Issue by yippiez** [termux/termux-packages#4778]
I have been getting this error while trying to run a python script:

`ImportError: dlopen failed: cannot locate symbol "getservbyport_r" referenced by "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pycares/_cares.cpython-38.so"...`

I have tried to reinstall cpython and pycare but nothing has worked so far.i have been getting missing module/other errors before this but i have fixed all of them.but i couldn't figure this one nor can find any other problem lime this.

### Error is from aiodns -> pycare -> cpython

(I have gevent installed which is the only solution to this problem that i found online)

**Comment by kcubeterm** [comment]
Maybe this link help you,[https://github.com/saghul/pycares/issues/78](https://github.com/saghul/pycares/issues/78)

**Comment by yippiez** [comment]
> Maybe this link help you,[saghul/pycares#78](https://github.com/saghul/pycares/issues/78)

I tried it but still getting the error even though i have commented out getservbyport.

**Comment by yippiez** [comment]
I figures it out pycare has a new config file for android after 3.0.0 so you have to change config_android instead of config_linux.

**Comment by 10ke5h** [comment]
Will you please elaborate it in detail...
I mean how should I change that file and I didn't found any file name config_android or config_linux...
Please help...

**Comment by xeffyr** [comment]
> Will you please elaborate it in detail...

Link to upstream issue isn't detail ? https://github.com/saghul/pycares/issues/78

> I didn't found any file name config_android or config_linux...

Because didn't searched. File is in pycares *source code*.

***

https://github.com/saghul/pycares/issues/78#issuecomment-445508989 well describes what should be done exactly.

**Comment by lok-esh** [comment]
Thanks

**Comment by xeffyr** [comment]
Have you tried to edit deps/c-ares/src/config_android/ares_config.h instead ?

**Comment by yippiez** [comment]
> 
> 
> Have you tried to edit deps/c-ares/src/config_android/ares_config.h instead ?

i changed this file to fix the problem

**Comment by lok-esh** [comment]
Thanks it worked for me
