### ISSUE TITLE
Package request: adb

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#478]
Deleted. There is a workaround for what I wanted which doesn't requite adb client :)

**Comment by gitawego** [comment]
can you tell me what`s the workground please ?

**Comment by tigran123** [comment]
The workaround the undocumented feature of UMI Super whereby the manufacturer allowed root without actually rooting the phone, i.e. adb daemon on the phone was running with superuser privileges and so by simply issuing `adb shell` you got a root shell and could remount the filesystem rw and copy su binary in place (and then use termux's tsu to use it). However, as of Android 7.0, unfortunately, they "fixed" it, i.e. adb is running with reduced privileges (just like on Nexus 10) and one cannot have superuser privileges without actually rooting the phone.

**Comment by tinydynamite00** [comment]
@tigran123 Do you happen to know why the <code>fastboot</code> binary (presumably adb's as well) was stripped from the <code>linux-utils</code> package? I was thinking one or more security vulnerabilities may have prompted the exclusions, but I have yet to find any documentation that either confirms my 'best guess' or defines more circumspect reasons for the removal of a once standard binary. 

Though, if security was the underlying cause, I can think of a few other binaries in common packages possibly equal in volatility to a misused fastboot command.

**Comment by tigran123** [comment]
@tinydynamite00 Usually, the "security vulnerabilities" is merely the excuse to cover up the activity of mass surveillance which is going on every single device in the world. This is why they introduced selinux intro Android (fortunately, not in Linux proper yet, but eventually it will come to Linux also, mark my word --- maybe in 30-45 years' time or even slightly sooner, judging by how fast these rats operate) --- so that a normal user cannot monitor the processes which collect the data about your location, activity etc and forward "to those concerned". Btw, I noticed that even tcpdump was patched recently. I haven't checked the actual code change (and that is what they rely on --- experienced people have NO time to do all this checking and stupid people wouldn't have a clue even if they did check) but kept the old binary "just in case". My assumption is that they made tcpdump to silently filter out all those packets which the user "is not supposed to know about".

**Comment by chameleonbr** [comment]
I was able to run ADB successfully by copying the files from the project Magisk ADB NDK https://github.com/Magisk-Modules-Repo/adb-Installer/tree/master/bin to /data/data/com.termux/files/usr/bin and change the adb file to:

```
#!/system/bin/sh
# adb: wrapper to run adb from terminal
# osm0sis @ xda-developers

dir="$(cd "$(dirname "$0")"; pwd)";

export HOME=/data/data/com.termux/files/home;
export TMPDIR=/data/data/com.termux/files/usr/tmp;
$dir/adb.bin "$@";
```
And run: 
chmod +x adb* 
chmod +x fastboot

When I try to connect adb to other android devices through WiFi works fine.
If ADB Wireless is active on the same device, adb will connect to that automatically.

**Comment by Auxilus** [comment]
@chameleonbr Can you help me with this? 
![screenshot_20180110-201221](https://user-images.githubusercontent.com/23075789/34778202-a5100d98-f642-11e7-919b-83d8112b7477.png)

**Comment by chameleonbr** [comment]
My steps:
1. Start Wireless adb
2. adb start-server
3. adb devices
return:
List of devices attached
emulator-5554	device

**Comment by Auxilus** [comment]
Wireless adb ? App?

**Comment by chameleonbr** [comment]
If I try connect to localhost:5555:

adb devices
List of devices attached
localhost:5555	offline
emulator-5554	device

**Comment by Quasic** [comment]
Here are my steps:

**Comment by Quasic** [comment]
My Android 5.1 actually says connection refused.

**Comment by dmarjanovic** [comment]
@chameleonbr steps worked wonderfully on OnePlus 5T Android 8.1.0.

Additional steps that worked for me:
1.connect via USB cable to computer
2.on computer in console type ```adb tcpip 5555``` in order to "start wireless adb"
3.in termux run ```adb tcpip 5555``` (not sure if required)
4.disconnect USB
5.in termux run ```adb devices``` and there is one device listed
4.in Termux run ```adb devices```

**Comment by MasterDevX** [comment]
Just decided to write a simple script to simplify ADB installation process, here it is: https://github.com/MasterDevX/Termux-ADB

**Comment by davidgro** [comment]
I'd like to request reopening this. In the meantime, I'll try MasterDevX's solution but really this should be available in a 'native to termux' package that will get updated along with the other packages, etc.

**Comment by xeffyr** [comment]
> I'd like to request reopening this

https://github.com/termux/termux-packages/issues/3660

**Comment by hggfg** [comment]
* daemon not running. starting it now at tcp:5038 *
error: could not install *smartsocket* listener: Address already in use
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon

Wht the problem??....pls help me pls

**Comment by HiFiiDev** [comment]
> I was able to run ADB successfully by copying the files from the project Magisk ADB NDK https://github.com/Magisk-Modules-Repo/adb-Installer/tree/master/bin to /data/data/com.termux/files/usr/bin and change the adb file to:
> 
> ```
> #!/system/bin/sh
> # adb: wrapper to run adb from terminal
> # osm0sis @ xda-developers
> 
> dir="$(cd "$(dirname "$0")"; pwd)";
> 
> export HOME=/data/data/com.termux/files/home;
> export TMPDIR=/data/data/com.termux/files/usr/tmp;
> $dir/adb.bin "$@";
> ```
> 
> And run:
> chmod +x adb*
> chmod +x fastboot
> 
> When I try to connect adb to other android devices through WiFi works fine.
> If ADB Wireless is active on the same device, adb will connect to that automatically.

Thanks for this using it and gave this post cred

https://github.com/HiFiiDev/TermuxEasyADB
