### ISSUE TITLE
为什么没有线程安全(zts)版本的PHP可供安装？

### ISSUE THREAD

**Issue by zeusliang** [termux/termux-packages#4780]
**Problem description**

为什么在termux中没有线程安全(zts)版本的PHP可供选择？
**Steps to reproduce**

**Expected behavior**

希望可以提供一个支持线程安全(zts)版本的PHP安装包，谢谢！
**Additional information**

```
<?php
echo "Hello PHP !";
?>
```
因为我没有电脑，所以喜欢在Termux上学习php。期待，有一个线程安全版本的PHP安装包出来！

**Comment by xeffyr** [comment]
Seems to be duplicate of https://github.com/termux/termux-packages/issues/892.
