### ISSUE TITLE
Passing Strings in MANPAGER Doesn't Work

### ISSUE THREAD

**Issue by JacobTDC** [termux/termux-packages#4781]
Passing strings in the `MANPAGER` variable doesn't work, for example:
```bash
$ export MANPAGER="sh -c 'col -bx | bat -l man -p'"
$ man 2 select
```
```
-bx: 1: -bx: Syntax error: Unterminated quoted string
```
This happens regardless of the shell I'm using, and even if I change the `sh` to `bash`, `dash`, or `fish`. For some reason, `man` doesn't understand strings and spaces in the `MANPAGER` variable.

**Comment by xeffyr** [comment]
> For some reason, man doesn't understand strings and spaces in the MANPAGER variable.

We use a different implementation of `man` - http://mdocml.bsd.lv instead of https://www.nongnu.org/man-db/ because it is lightweight.

Issue is not Termux-specific and happens in Alpine Linux too and possibly other distributions where mdocml is used.

**Comment by JacobTDC** [comment]
@xeffyr, then how would I make the above code work?

**Comment by xeffyr** [comment]
> then how would I make the above code work?

mdocml does very basic parsing of `MANPAGER`. It just splits arguments by space so calling `sh` here will not work.
