### ISSUE TITLE
Openbox obmenu

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-packages#4782]
**Package description**

**Link to home page and sources**
1. Home page: http://obmenu.sourceforge.net/
2. Source code: 

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by xeffyr** [comment]
>Home page: http://obmenu.sourceforge.net/
>> Dependecies
Python 2.3 or better, pygtk and pyglade.

Python packages using external dependency modules are not being added.

**Comment by xeffyr** [comment]
Duplicate of https://github.com/termux/x11-packages/issues/99.
