### ISSUE TITLE
Invalid checksum errors while compiling curl

### ISSUE THREAD

**Issue by imprakharshukla** [termux/termux-packages#4788]
**Problem description**
I just freshly cloned termux packages and initiated the package building with the included docker script. I am getting invalid checksum errors like these with curl - 

> Wrong checksum for https://curl.haxx.se/ca/cacert.pem:
Expected: 0d98a1a961aab523c9dc547e315e1d79e887dea575426ff03567e455fc0b66b4
Actual:   adf770dfd574a0d6026bfaa270cb6879b063957177a991d453ff1d302c02081f

Here's the .err output 
[curl_err.txt](https://github.com/termux/termux-packages/files/4050248/curl_err.txt)

**Steps to reproduce**
I have every required env variable in place. Just run the docker container (I am running that on Ubuntu 18.04 LTS) .Try to build with 

> bash build-package.sh -a aarch64 ack-grep espeak jupp libmsgpack stag acr exa kakoune ncurses starship algernon exiftool keybase libnettle ndk-multilib steghide antiword exiv2 keystone libnfs ndk-sysroot stfl apksigner fakeroot kona libnftnl ne stow apr fasd krb5 libnghttp2 net-tools strace apt fastmod kubectl libnl netsed swig aptly fcgi ldns libnpth ninja syncthing argp fcgiwrap less libogg nyancat tar arj fd leveldb liboggz ocrad teckit atomicparsley fdupes lhasa libopus oleo termimage attr fftw libandroid-glob libopusenc openal-soft termux-am autoconf figlet libandroid-shmem libpcap openssh termux-auth axel file libandroid-spawn libpipeline openssl termux-elf-cleaner bash findutils libandroid-support libpixman opusfile termux-exec binutils flex libassuan libpng ossp-uuid termux-keyring bison fortune libbsd libpopt p7zip termux-licenses blogc fsmon libbz2 libprotobuf par2 termux-tools bmon game-repo libc++ libsasl parallel teseq brotli gawk libcap libsigsegv patch timewarrior busybox gbt libcln libsndfile patchelf tinyproxy bvi gcal libconfig libsodium pcre tinyscheme c-ares gdbm libconfuse libsoxr pcre2 tmux c-toxcore geoip2-database  libcue libsqlite perl tokei ca-certificates getconf libcurl libtalloc pforth tor cabextract geth libdav1d libtermkey pick tracepath caddy gflags libdb libtiff pigz tree calcurse giflib libdispatch libtool pinentry tsocks capstone gifsicle libduktape libunibilium pkg-config tsu ccache git-lfs libedit libunistring  play-audio tty-clock cmark gkermit libelf libusb plzip ttyrec cmatrix glib libev libuuid potrace tweego codecrypt gnuit libevent libuv privoxy unicorn  colordiff gnupg libexif libvorbis procps unifdef command-not-found  google-glog libexpat libvpx progress unrar coreutils googletest libffi libvterm proot unstable-repo cowsay gotty libflac libwebp proxychains-ng unzip cppi gperf libgc libx264 psmisc utf8cpp crunch gpsbabel libgcrypt libx265 pulseaudio utf8proc cryptopp grep libgfshare libxapian pv utfdecode cscope gsl libgmp libxml2 pwgen valgrind ctags gtypist libgnutls libyaml qpdf vegeta cvs gumbo-parser libgpg-error libzmq quickjs vim daemonize gzip libgraphite libzopfli radare2 virustotal-cli darkhttpd hashdeep libiconv loksh ragel vttest dash help2man libicu lzip rclone vtutils dasm hexcurse libid3tag lzlib readline wget datamash hexedit libidn lzop redir wireguard-tools ddrescue hexyl libidn2 m4 redis wol debianutils heyu libisl make remind wren dialog hfsutils libjansson mbedtls resolv-conf wuzz dictd hoedown libjasper mdp restic x11-repo diffutils htop libjpeg-turbo memcached ripgrep xcb-proto direnv hugo libksba mg root-repo xorg-util-macros direvent hunspell-en-us libluajit micro samefile xorgproto diskus hunspell-ru liblz4 mime-support sc xtrans dos2unix hyperfine liblzma minicom science-repo xvidcore double-conversion indent liblzo miniupnpc secure-delete yajl doxygen inotify-tools libmaa mksh sed yasm dpkg ipcalc libmad mktorrent sensible-utils zile dtc ipfs libmaxminddb mlocate sharutils zip dte ired libmcrypt morse2ascii shellharden zlib dvtm jhead libmhash mpc silversearcher-ag zsh dx joe libmnl mtools sl zstd ecj jq libmp3lame multitail speexdsp zsync ed json-c libmpdclient nano sshpass erlang jsoncpp libmpfr ncdu ssss inetutils linux-utils git hashdeep

**Comment by Grimler91** [comment]
Thanks for reporting! [This means that ca-certificates should be updated](https://github.com/termux/termux-packages/blob/cfe2dc8ed7361ec4beb568fcd8099083c8c4c28c/packages/ca-certificates/build.sh#L6). I pushed an update in https://github.com/termux/termux-packages/commit/cfe2dc8ed7361ec4beb568fcd8099083c8c4c28c so it should now work again!
