### ISSUE TITLE
Error while compiling tweego 

### ISSUE THREAD

**Issue by imprakharshukla** [termux/termux-packages#4789]
**Problem description**
Tweego's repository has been moved to [GitHub](https://github.com/tmedwards/tweego) from [GitBucket](https://bitbucket.org/tmedwards/tweego) and this results in the tar not getting downloaded and throwing an error while compiling it.

**Additional information**
tweego.err has been attached [here](https://github.com/termux/termux-packages/files/4051404/tweego.txt)

These should be the new values to the variables, up-streaming to 2.1.0 -

> TERMUX_PKG_VERSION=2.1.0
TERMUX_PKG_SRCURL=https://github.com/tmedwards/tweego/archive/v$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=73c2f00e6b19bd7339b2c431a32f51f4514f7b32130dd5738ece6efbf0664343

**Comment by xeffyr** [comment]
Done in 8d6ab64535506b2cbaf892d708f86ac8ec6dafce.
