### ISSUE TITLE
ilibrarian selfhosted on android

### ISSUE THREAD

**Issue by fabsir** [termux/termux-packages#479]
I want to run iLibrarian on my galaxy s5 neo.I have already set up an working Server with DB access. But the problem are the executable binaries. The poppler-utils are not the problem but the ghostscript binary. I have first download the termux-packages-master and copied the ghostscript dir from disabled-packages into packages and run build-package.sh ghostscript in commandline. The output is:

`# ./build-package.sh ghostscript
mkdir: cannot create directory '/tmp/cg-8567': 
No such file or directory
 config.guess: cannot create a temporary directory in /tmp`

The sourcecode from this output is in file config.guess after line 99:

  `set_cc_for_build='
  trap "exitcode=\$?; (rm -f \$tmpfiles 2>/dev/null; rmdir \$tmp 2>/dev/null) && exit \$exitcode" 0 ;
  trap "rm -f \$tmpfiles 2>/dev/null; rmdir \$tmp 2>/dev/null; exit 1" 1 2 13 15 ;
     : ${TMPDIR=/tmp} ;
    { tmp='(umask 077 && mktemp -d "$TMPDIR/cgXXXXXX") 2>/dev/null' && test -n "$tmp" &&  test -d "$tmp" ; } ||# ./build-package.sh ghostscript
mkdir: cannot create directory '/tmp/cg-8567': 
No such file or directory
 config.guess: cannot create a temporary directory in /tmp
    { test -n "$RANDOM" &&    tmp=$TMPDIR/cg$$-$RANDOM && (umask 077 && mkdir $tmp) ; } ||
     { tmp=$TMPDIR/cg-$$ && (umask 077 && mkdir $tmp) && echo "Warning: creating insecure temp directory" >&2 ; } ||
    { echo "$me: cannot create a temporary directory in $TMPDIR" >&2 ; exit 1 ; } ;`       

Can you help me, please?

**Comment by Neo-Oli** [comment]
The problem is that you don't have permissions to `/tmp` in android. Termux uses `$PREFIX/tmp` (which is something like `/data/data/com.termux/files/usr/tmp`. You have to see if you can overwrite the $TMPDIR variable from the `build.sh` file, otherwise you will have to write a patch for the Makefile/configure file of Ghostscript and set in the correct path.

**Comment by sgeto** [comment]
`./configure TMPDIR=$PREFIX/tmp`
