### ISSUE TITLE
Error while compiling nocompress

### ISSUE THREAD

**Issue by imprakharshukla** [termux/termux-packages#4790]
**Problem description**
The **ncompress-4.2.4.6.tar.gz** sha256 checksum is incorrectly mentioned in the [build.sh](https://github.com/termux/termux-packages/blob/master/packages/ncompress/build.sh) file.

**Additional information**
The correct checksum of the file downloaded with the scripts is _112acfc76382e7b631d6cfc8e6ff9c8fd5b3677e5d49d3d9f1657bc15ad13d13_ and **not** _fb7b6a00060bd4c6e35ba4cc96a5ca7e78c193e6267487dd53376d80e061836b_

The link to the file downloaded - https://github.com/vapier/ncompress/archive/v4.2.4.6.tar.gz

**Comment by xeffyr** [comment]
Thanks, this probably related to tag update. The old one moved to https://github.com/vapier/ncompress/releases/tag/v4.2.4.6-old.

Fixed in 5cbc1e39a6de86874aad05efb98c98a4fe3e0e57.
