### ISSUE TITLE
termux-chroot should show error but doesn't

### ISSUE THREAD

**Issue by ronnac** [termux/termux-packages#4793]
I have a command (java) that produces a segmentation fault in termux but no output at all in termux-chroot.
The java command stems form the installjava package.
I have the same problem with a different command (more difficult to explain).

**Problem description**

**Steps to reproduce**

$ java
Segmentation fault
$ termux-chroot
$ java
$ termux-info
```
Packages CPU architecture:                     arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.111-16046393 #1 SMP PREEMPT Wed Oct 9 14:44:51 KST 2019 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A105FN
```
**Expected behavior**

The java command should produce the same error in termux-chroot. 

**Additional information**

```

```

**Comment by Grimler91** [comment]
"no output" sounds like an error as well, so the only difference is probably that it doesn't print "Segmentation fault" in the chroot case. Try running it under gdb and you'll probably see the seg fault in both cases. 

You can also check the return code of the process with `echo $?`.

**Comment by xeffyr** [comment]
> The java command stems form the installjava package.

We also don't know what is "installjava". This package is not provided by any of our repositories.
JDK variants which claim to be "Termux compatible" are just copies from Debian or extracted from other apps (e.g. from Jvdroid) and patched on binary level. They are not guaranteed to work properly.

FYI, to get JDK from Jvdroid work without segfault, you need to export `TMPDIR` environment variable.

**Comment by ronnac** [comment]
@Leonid,I tried your openjdk_9 for termux, but it slows down my phone tremendously.What works well is installing openjdk_8 in termux-ubuntu. However, I prefer a solution in termux directly.Could you direct me to instructions for the Jvdroid TMPDiR solution? I have no linux background, as you probably noticed.
-------- Original message --------From: Leonid Plyushch <notifications@github.com> Date: 13/01/2020  11:50  (GMT+01:00) To: termux/termux-packages <termux-packages@noreply.github.com> Cc: Nick Römer <nick.romer@advalvas.be>, Author <author@noreply.github.com> Subject: Re: [termux/termux-packages] termux-chroot should show error but doesn't (#4793) 
The java command stems form the installjava package.

We also don't know what is "installjava". This package is not provided by any of our repositories.
JDK variants which claim to be "Termux compatible" are just copies from Debian or extracted from other apps (e.g. from Jvdroid) and patched on binary level. They are not guaranteed to work properly.
FYI, to get JDK from Jvdroid work without segfault, you need to export TMPDIR environment variable.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/termux/termux-packages/issues/4793?email_source=notifications\u0026email_token=AHIFK3VROSSN6T6EUTTS5FTQ5RBOBA5CNFSM4KF6KVDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIYIJNQ#issuecomment-573605046",
"url": "https://github.com/termux/termux-packages/issues/4793?email_source=notifications\u0026email_token=AHIFK3VROSSN6T6EUTTS5FTQ5RBOBA5CNFSM4KF6KVDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIYIJNQ#issuecomment-573605046",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
