### ISSUE TITLE
please someone should help me with this error

### ISSUE THREAD

**Issue by kruz26** [termux/termux-packages#4797]
![Screenshot_20200114-121034](https://user-images.githubusercontent.com/59299820/72339835-5921ca80-36c7-11ea-9c9c-1ffa46efe307.png)

**Comment by xeffyr** [comment]
Do you have manually changed `sources.list` ? If so, revert back to
```
deb https://termux.org/packages/ stable main
```
Notice the slash at the end of URL - it is important.
