### ISSUE TITLE
ndk-build

### ISSUE THREAD

**Issue by HafizZiq** [termux/termux-packages#4799]
Any way/workaround to have ndk-build command in termux?
I need to build sqlite3 binary

**Comment by xeffyr** [comment]
> Any way/workaround to have ndk-build command in termux?

NDK is not available for ARM/AArch64 and is not being packaged for Termux anyway.

> I need to build sqlite3 binary

1. We have `clang` which is able to build sqlite3.
2. This binary is available in package `sqlite`.
