### ISSUE TITLE
Package request: grafana

### ISSUE THREAD

**Issue by labulaka521** [termux/termux-packages#4801]
**Package description**

**Link to home page and sources**
1. Home page:
https://grafana.com/
2. Source code:
https://github.com/grafana/grafana
**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by lbrito1** [comment]
Grafana [provides ARM binaries](https://grafana.com/grafana/download?platform=arm) in their download section. Could this be helpful at all for Termux?

I tried running those binaries on a phone with an armv7 CPU, and I ran into this known issue: https://github.com/grafana/grafana/issues/19585

**Comment by xeffyr** [comment]
@lbrito1 Binaries built for Linux will not work properly in Termux.

**Comment by dvinciguerra** [comment]
I make a try building from source and golang build part looks easy to do using source code...

But a had some problems about frontend assets build part (more exactly about nodejs min version required) =S

![image](https://user-images.githubusercontent.com/114177/115966695-28a12100-a505-11eb-91b9-1d92f0a52939.png)

**Comment by xtkoba** [comment]
If the problem was due to old version of Node.js, then it is likely to be resolved now that we have the latest Current version available (17.1.0 as of now).
