### ISSUE TITLE
Termux-wallpaper -l not working properly

### ISSUE THREAD

**Issue by Abhayvishnoi** [termux/termux-packages#4802]
So i am using termux-wallpaper -l -f filename
on android 9 it work fine for home screen wallpaper and also says successfully applied wallpaper for both home screen and lockscreen but the wallpaper on lockscreen is not changing what is the problem there is no error in the terminal it says successfully applied wallpaper but the wallpaper doesn't change on lockscreen

**Comment by ashishchikhale13** [comment]
same issue bro. is there anyone able to  solve this problem.
