### ISSUE TITLE
Termux extra-keys

### ISSUE THREAD

**Issue by wangxiaoerYah** [termux/termux-packages#4804]
**Problem description**

Does the symbol `'` in extra-keys not work?
Please help me achieve it.
Current preview:
![IMG_20200117_132954](https://user-images.githubusercontent.com/48443038/72586640-7952c300-392d-11ea-9fda-78c83507032f.jpg)

**Steps to reproduce**

My Code:
```
extra-keys = [\
[''']\
]

```
**Expected behavior**

I want to add `'` to the shortcut.
I expected extra-keys:
```
extra-keys = [\
[',','|','!','"',''','`','_','~','&'],\
['{','}','(',')','[',']','=','+',';'],\
['ESC','/','-',':','UP','END','PGUP','<','*'],\
['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN','>','#']\
]

```
`'`Fourth in the second line.

**Additional information**

Termux error:
```
Termux: Could not load the extra-keys property from the config: org.json.JSONException: 
Unterminated array at character 21 of
 [[','. I ','! ', ",", ".'_', '  -',' & '], [' {'!}, ",)'" I. ', = +' ,; 1. ['ESC', I ",-" UP ',' END ',' PGUP  ',' <', *'], ['TAB', 'CTRL', 'ALT', 'LEFT', 'DOWN', 'RIG HT', 'PGDN', '>', '#']]

```
Error image:
![IMG_20200117_132523](https://user-images.githubusercontent.com/48443038/72586479-e7e35100-392c-11ea-906b-32f808261c19.jpg)

**Comment by RossComputerGuy** [comment]
Try using `'\''` instead of `'''`

**Comment by wangxiaoerYah** [comment]
> Try using `'\''` instead of `'''`

Thank you for your reply, but it does not work.

**Comment by Grimler91** [comment]
`"'"` works so:

```
extra-keys = [\
[',','|','!','"',"'",'`','_','~','&'],\
['{','}','(',')','[',']','=','+',';'],\
['ESC','/','-',':','UP','END','PGUP','<','*'],\
['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN','>','#']\
]
```

should work.

**Comment by xeffyr** [comment]
> Thank you for your reply, but it does not work.

Use `'APOSTROPHE'` instead.
