### ISSUE TITLE
error: use of undeclared identifier 'LC_ALL' when compiling utimer

### ISSUE THREAD

**Issue by happysmash27** [termux/termux-packages#4805]
**Problem description**

I'm not sure if this is the correct place to post this, but utimer will not compile on Termux. The error is `error: use of undeclared identifier 'LC_ALL'`. A file in config.h has the line `#define LOCALEDIR "/data/data/com.termux/files/usr/lib/locale"` and I think the fact that this directory doesn't exist may have caused the error. How do I get this directory? 

**Steps to reproduce**

• Fix the intllib missing bug by doing the things related to perl and compiling and installing intllib (stupid mobile Waterfox keeps deleting old history so I can't find the bug page with the fix for it!)

• `./configure --prefix /data/data/com.termux/files/usr/`

• `make`

**Expected behavior**

After I install the dependencies and set the prefix correctly, compilation **just works**, like it does in Gentoo, so I can install my makeshift alarm clock which actually supports non-looping music and **not** sleep in and become late for school, like has occured today because most alarm clocks are completely inadequate. 

**Additional information**

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-21 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-21 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.4.113-lineageos-ga160ed5 #1 SMP PREEMPT Thu Nov 28 17:30:38 UTC 2019 armv7l Android
Device manufacturer:
OnePlus
Device model:
A0001
```

Also, it doesn't say this, but apparently Termux itself is now out of date today. I will upgrade it, recompile yet again, and report if the compilation works.

**Comment by happysmash27** [comment]
Huh, apparently this legacy environment thing is different than I expected. I am running `termux-upgrade-repo` now, and it is removing /usr/. That will be annoying.

**Comment by xeffyr** [comment]
Termux does not support locales.
This is why you got `The error is error: use of undeclared identifier 'LC_ALL'`.

**Comment by xeffyr** [comment]
Try to reconfigure program with `--disable-nls`.

**Comment by xeffyr** [comment]
```
--- utimer-0.4/src/utimer.c     2009-06-01 17:23:45.000000000 +0300
+++ utimer-0.4.mod/src/utimer.c 2020-01-17 19:20:44.203984855 +0200
@@ -167,26 +167,6 @@
   /* We cleanup at exit */
   g_atexit (clean_up);
   
-  /* Define localization */
-  ut_config.locale = setlocale (LC_ALL, "");
-  if (!ut_config.locale)
-  {
-    g_error (_("Error during setting current locale. Falling back to default locale."));
-    ut_config.locale = setlocale (LC_ALL, "C");
-    if (!ut_config.locale)
-    {
-      g_critical (_("Couldn't set any locale. Exiting..."));
-      exit (EXIT_FAILURE);
-    }
-  }
-  
-  /* i18n */
-  g_set_prgname (PACKAGE);
-  bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
-  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
-  textdomain (GETTEXT_PACKAGE);
-  
-  
   /* Set the function to call in case of receiving signals:
    * we need to stop the main loop to exit correctly, but
    * with error code!
```

```
$ ./utimer --countdown 2m
Time Remaining: 0 days 00:01:57.214 (117.214 seconds)
```

**Comment by happysmash27** [comment]
Thank you so much \^ω\^ ! I commented the entire thing out and it worked! Now I don't have to worry so much about alarm methods anymore!
