### ISSUE TITLE
Failed instaling parrot os on termux

### ISSUE THREAD

**Issue by prakashmanuel** [termux/termux-packages#4808]
/start-parrot.sh script
$ ./start-parrot.sh
proot warning: can't sanitize binding "parrot-fs/root": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/parrot-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by xeffyr** [comment]
Ensure that directory `/data/data/com.termux/files/home/parrot-fs` exists.
