### ISSUE TITLE
[Package request] task-spooler

### ISSUE THREAD

**Issue by JtokohZohl** [termux/termux-packages#4811]
**Package description**
task spooler is a Unix batch system where the tasks spooled run one after the other. The amount of jobs to run at once can be set at any time. 

**Link to home page and sources**
1. Home page: https://vicerveza.homeunix.net/~viric/soft/ts/
2. Source code: https://vicerveza.homeunix.net/~viric/soft/ts/ts-1.0.tar.gz

**Additional information**
A simple program with dependencies only libc. Present on many Linux distributions:
Debian: https://packages.debian.org/stable/task-spooler
Fedora: https://apps.fedoraproject.org/packages/task-spooler/overview/
Alpine: https://pkgs.alpinelinux.org/package/edge/testing/aarch64/ts
FreeBSD: https://www.freshports.org/sysutils/ts/

**Comment by xeffyr** [comment]
Already added as of https://github.com/termux/termux-packages/pull/4988 was merged.
```
pkg install task-spooler
```
