### ISSUE TITLE
Python depending on Clang

### ISSUE THREAD

**Issue by DMSalesman** [termux/termux-packages#4813]
Good day. I was about to upgrade Python 3, and I noticed that ~150MB were about to be occupied in my internal storage; I traced that massive increase in size to `clang` and `libllvm`.

Since when does `python` depend on those?

**Comment by xeffyr** [comment]
`clang` is added as "recommended" package to python.

You may uninstall it if not needed, however it is required for installation of any module with native extensions (e.g. lxml, pillow, numpy).

**Comment by DMSalesman** [comment]
Thanks for clarifying.
