### ISSUE TITLE
Bug with header path at libluajit_2.1.0~beta3-3

### ISSUE THREAD

**Issue by DanielTimLee** [termux/termux-packages#4814]
**Problem description**

With package `libluajit_2.1.0~beta3-3`,
the header path is located at `$TERMUX_PREFIX/include/luajit-2.0/`.

https://github.com/termux/termux-packages/blob/990ad4ba07d6c5db3dc624d60b959d76d05481f6/packages/libluajit/build.sh#L33-L34

The problem is current package version is `2.1` not `2.0`.
And when using `pkg-config`, it guides me to the path with `2.1` which doesn't exists.

**Steps to reproduce**

```sh
pkg install pkg-config libluajit
pkg-config --cflags luajit
# -I $PREFIX/include/luajit-2.1
```

**Expected behavior**

The package should install header to the location of 
`$TERMUX_PREFIX/include/luajit-2.1/` not `2.0`.

The package build script should be modified.

**Comment by Grimler91** [comment]
Fixed in https://github.com/termux/termux-packages/pull/4815, thanks for reporting!
