### ISSUE TITLE
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.

### ISSUE THREAD

**Issue by redlover73** [termux/termux-packages#4816]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by redlover73** [comment]
How do I correct

**Comment by Grimler91** [comment]
run `dpkg --configure -a` as it suggests, or reinstall termux-app.

**Comment by hackerorya** [comment]
Halpe me

**Comment by RossComputerGuy** [comment]
@hackerorya A solution was already given

> run `dpkg --configure -a` as it suggests, or reinstall termux-app.

**Comment by ashu123-design** [comment]
If we reinstall termux ..all the packages will be deleted na?

**Comment by Adarsh5152** [comment]
Ya
