### ISSUE TITLE
Requesting wrk

### ISSUE THREAD

**Issue by rhjdvsgsgks** [termux/termux-packages#4818]
**Package description**
wrk is a modern HTTP benchmarking tool capable of generating significant load when run on a single multi-core CPU. It combines a multithreaded design with scalable event notification systems such as epoll and kqueue.

**Link to home page and sources**
1. Home page:
2. [Source code](https://github.com/wg/wrk) 

**Additional information**
a small changes below can make it compile successfully, and it can perfectly working om termux
```diff
diff --git a/Makefile b/Makefile
index 0325481..bd817ed 100644
--- a/Makefile
+++ b/Makefile
@@ -76,7 +76,7 @@ $(ODIR)/%.o : %.c
 LUAJIT  := $(notdir $(patsubst %.tar.gz,%,$(wildcard deps/LuaJIT*.tar.gz)))
 OPENSSL := $(notdir $(patsubst %.tar.gz,%,$(wildcard deps/openssl*.tar.gz)))

-OPENSSL_OPTS = no-shared no-psk no-srp no-dtls no-idea --prefix=$(abspath $(ODIR))
+OPENSSL_OPTS = -llog no-shared no-psk no-srp no-dtls no-idea --prefix=$(abspath $(ODIR))

 $(ODIR)/$(LUAJIT):  deps/$(LUAJIT).tar.gz  | $(ODIR)
        @tar -C $(ODIR) -xf $<
```

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install wrk
```

**Comment by HackGod-RS** [comment]
how to use this give any example

**Comment by rhjdvsgsgks** [comment]
> how to use this give any example

[please read the document before asking](https://github.com/wg/wrk#basic-usage)
