### ISSUE TITLE
Package Request: mplayer

### ISSUE THREAD

**Issue by flipflop97** [termux/termux-packages#482]
Would it be possible to add mplayer to the termux repo? Since X isn't supported this would be with only aa (ASCII art) and caca (colored ASCII art) video output.

**Comment by its-pointless** [comment]
mpv is that basically...

**Comment by jyf007** [comment]
it can't play on android N

**Comment by tigran123** [comment]
The alternative is to ask for mpv to be recompiled with caca video output driver. Note that libcaca/libcaca-dev are included in Termux.

**Comment by Neo-Oli** [comment]
@tigran123 I opened a pull request for just that a few days ago.  #499

**Comment by tigran123** [comment]
@Neo-Oli Oh, I see. I didn't notice --- I only learned that such a thing as "libcaca" exists yesterday :)

**Comment by arno01** [comment]
Looks like it was dropped shortly after it was added :/ https://github.com/termux/termux-packages/commit/fd2b34d8467327bb416c9e9f7fd81f5d10f42ade#diff-31e775d74abd763b7da5eda9f8ce14d4L22

It says:
> Drop libcaca as dependency as mpv now has built in terminal output.

But I can't figure what's the flag to use the terminal output?
cc @fornwall

**Comment by xeffyr** [comment]
@arno01 You need to edit configuration file of **mpv**.
Make sure it looks like this:
```
[~]:$ cat $PREFIX/etc/mpv/mpv.conf 
ao=opensles
vid=tct
```

And then `mpv -vo tct yourvideo.mp4`

**Comment by arno01** [comment]
@xeffyr thanks a lot! I've been trying ``mpv --vo=tct video.mp4`` but apparently I was missing ``vid=tct`` in my ``mpv.conf``. Still makes me wonder why the latter would be required if I passed the first one with the argument.
