### ISSUE TITLE
pdfjam fails - unable to create temp file

### ISSUE THREAD

**Issue by davidpiano** [termux/termux-packages#4823]
I tried using pdfjam to join several PDF files into one. It didn't work, apparently because pdfjam is hard-coded to create its temp files in /var/tmp , which doesn't exist in the context of Termux. Is there a known workaround for things like this?

**Comment by Hax4us** [comment]
Here you can change the directory https://github.com/DavidFirth/pdfjam/blob/9664dd92ea9385f9e60a397561ec238305fcea92/bin/pdfjam#L185
From `tempfileDir='/var/tmp'` to `tempfileDir="$PREFIX/tmp`

**Comment by davidpiano** [comment]
Thank you! I should have known that.

At first, I didn't pay attention to single quote marks vs double ones, and I thought your solution didn't work. For any others reading, a heads-up - if you use $PREFIX inside single quotes, remember that it will be taken literally as a dollar sign and six letters rather than interpreted as the location you intended.

**Comment by davidpiano** [comment]
I'm not convinced that this report is a real bug, by the way. It looks like an error on my part. However, if it's being treated as a bug to be fixed, that's fine - I guess it will save a little time in the future.

**Comment by Grimler91** [comment]
Looks like the code needs to be patched (since it has hardcoded /var/tmp instead of using $TMPDIR), but if you have managed to get it working without patching it then maybe it falls back to $TMPDIR elsewhere

**Comment by davidpiano** [comment]
From what I've been able to find out:

1. The upstream developer was not interested in doing anything to his code.

2. This is easily fixable by changing a local config file as outlined above - as long as you know you need to do that.

**Comment by Grimler91** [comment]
I'll add a patch that fixes this. I'll probably wait until texlive 2020 is released though (in February) since updating texlive means that texlive and aaall subpackages are updated, and that means a lot of unnecessary downloads for just this patch

**Comment by davidpiano** [comment]
I certainly agree it's better to wait - I might be the only person in the world who had this problem and didn't know how easy it was to fix. :)
