### ISSUE TITLE
Error upgrading/installing Bison

### ISSUE THREAD

**Issue by marvin-littlewood** [termux/termux-packages#4827]
On Android 7 - with fully upgraded packages and up-to-date Termux.

**Problem description**

There was an error upgrading Bison, which was repeated when trying to install the package.

**Steps to reproduce**
``` $ pkg install bison ```

**Expected behavior**
No errors

**Additional information**
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  bison
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/442 kB of archives.
After this operation, 2179 kB of additional disk space will be used.
(Reading database ... 53263 files and directories currently installed.)
Preparing to unpack .../bison_3.5.1-1_aarch64.deb ...
Unpacking bison (3.5.1-1) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/bison_3.5.1-1_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/share/info/dir', which is also in package emacs 26.3-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/bison_3.5.1-1_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

**Comment by eladts** [comment]
Got the same error on Android 9.

If you get this error while upgrading multiple packages, it leaves the other upgraded packages in an incomplete state. To complete the upgrades of the other packages use the following command:

`dpkg --configure --pending`

**Comment by its-pointless** [comment]
This looks to be a packaging error. A version bump probably fixes it.

**Comment by eladts** [comment]
Can confirm the bison 3.5.1-3 updates correctly.
