### ISSUE TITLE
Package request: cfengine community

### ISSUE THREAD

**Issue by craigcomstock** [termux/termux-packages#4833]
**Package description**
CFEngine is a configuration management and automation framework that lets you securely manage your mission critical IT infrastructure.
I believe it would be wonderful to manage aspects of termux and android with CFEngine policy. Especially if that helps make the termux environment similar to your desktop/laptop environment for ease of use switching between these systems.
For starters I will work on the community edition. The enterprise edition can follow later.

**Link to home page and sources**
1. Home page: https://cfengine.com/
2. Source code: https://github.com/cfengine/core/ and https://github.com/cfengine/masterfiles/

**Additional information**
I have already built and tested this package from source on the device and it works fairly well.
I will be working to apply patches to core/libntech/masterfiles so that the termux package can simply be based on a standard release.

Here are my WIP branches which I will likely use as a basis for patches in the termux package.
https://github.com/craigcomstock/core/tree/termux
https://github.com/craigcomstock/libntech/tree/termux

**Comment by craigcomstock** [comment]
liblmdb is a dependency for cfengine so working on that first.

**Comment by craigcomstock** [comment]
Made some progress today. liblmdb is finished and available. Thanks @xeffyr for all the help.

For some reason I'm now stuck on a patch file I can't quite get right. It may be a problem upstream in cfengine core in that we likely don't support building in a separate build directory.

Will work on this more next week. Figured I'd leave off making a PR until it sort of works. :+1:

https://github.com/craigcomstock/termux-packages/tree/cfengine

**Comment by xeffyr** [comment]
I'm closing this because package `cfengine` is already available for installation.
