### ISSUE TITLE
liblmdb

### ISSUE THREAD

**Issue by craigcomstock** [termux/termux-packages#4834]
**Package description**
A Btree-based database management library modeled loosely on the BerkeleyDB API, but much simplified.
I am working on a cfengine package and need lmdb as a dependency.

**Link to home page and sources**
1. Home page: https://symas.com/lmdb/
2. Source code: https://github.com/LMDB/lmdb

**Additional information**
Have you compiled or tried to compile the package on device?
Yes. It works fine with one patch to the Makefile.
See this working branch: https://github.com/craigcomstock/termux-packages/tree/liblmdb

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install liblmdb
```
