### ISSUE TITLE
Dart x86_64 Build Broken

### ISSUE THREAD

**Issue by TheBrokenRail** [termux/termux-packages#4836]
**Problem description**
Dart 2.7.0 won't build for Android x86_64.

**Steps to reproduce**
Build Dart for x86_64.

**Expected behavior**
It builds.

**Additional information**
dart-lang/sdk#39838

**Comment by zorro** [comment]
@TheBrokenRail  I have submitted PR on dart repository. As a temporary solution I have created a patch on this repository. check https://github.com/zorro/termux-packages/blob/master/packages/dart/fix_x64.patch

**Comment by zorro** [comment]
@TheBrokenRail problem fixed in termux. I have submitted PR on dart's repository too. Waiting for merge

**Comment by xeffyr** [comment]
It is merged now.
