### ISSUE TITLE
Gitk : graphical representation of git

### ISSUE THREAD

**Issue by kcubeterm** [termux/termux-packages#4841]
Today ,i am practicing git cli from official manpages, and found a `gitk` alternative of `git log` , but it's not found in termux. Is it possible to run in termux.
#### Homepage of gitk.
No idea about of hompage, sorry

**Comment by xeffyr** [comment]
It is really part of `git` but disabled currently: https://github.com/termux/termux-packages/blob/master/packages/git/build.sh#L17

I can enable it since `tk` is available.

**Comment by kcubeterm** [comment]
O, thanks

**Comment by kcubeterm** [comment]
What is `tk` ?

**Comment by xeffyr** [comment]
```
TERMUX_PKG_DESCRIPTION="A windowing toolkit for use with tcl"
```

**Comment by xeffyr** [comment]
Git subpackages `git-gui` and `git-gitk` are now available.

**Comment by kcubeterm** [comment]
Very very thankful.

**Comment by kcubeterm** [comment]
One more error,
```
$ gitk
application-specific initialization failed: no display name and no $DISPLAY environment variable
Error in startup script: no display name and no $DISPLAY environment variable
    while executing
"load /data/data/com.termux/files/usr/lib/libtk8.6.so Tk"
    ("package ifneeded Tk 8.6.10" script)
    invoked from within
"package require Tk"
    (file "/data/data/com.termux/files/usr/bin/gitk" line 10)
```

**Comment by kcubeterm** [comment]
Okk, no issues, i forgot to run vnc, sorry
