### ISSUE TITLE
Package request: natpmpc

### ISSUE THREAD

**Issue by Austcool-Walker** [termux/termux-packages#4842]
libnatpnpc I have an Airport Extream Base station router and I would like to open ports for running network tasks from termux plug and play style.

**Comment by xeffyr** [comment]
I'm in doubt that `libnatpnpc` exists, at least Google show nothing about it.

If you seeking for **libminiupnpc**, please check the package `miniupnpc`. Otherwise post links to homepage/sources of needed package.

**Comment by Austcool-Walker** [comment]
> I'm in doubt that `libnatpnpc` exists, at least Google show nothing about it.
> 
> If you seeking for **libminiupnpc**, please use the package `miniupnpc`. Otherwise post links to homepage/sources of needed package.

http://miniupnp.free.fr/libnatpmp.html http://miniupnp.free.fr/ I'm referring and requesting both of these programs basically Ubuntu has both in there repos

**Comment by xeffyr** [comment]
Ok, thanks.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install natpmpc
```
