### ISSUE TITLE
taskwarrior segmentation fault

### ISSUE THREAD

**Issue by zmingee** [termux/termux-packages#4843]
**Problem description**
Running taskwarrior results in a segmentation fault

**Steps to reproduce**
1. `pkg up`
1. `pkg install taskwarrior`
2. Attempt command

**Additional information**
- Nexus 6 (shamu)
- Android 9 - LineageOS
- `armv7l`

Other packages work fine; `pkg up` succeeds, etc.

```
$ task
Segmentation fault
$ task sync
Segmentation fault
$ task ls
Segmentation fault
$ task config
Segmentation fault
$ task diag
Segmentation fault
```

**Comment by xeffyr** [comment]
Can't reproduce the issue on both AArch64 and ARM devices.

**Comment by zmingee** [comment]
Yes, I've updated all the packages with `pkg up`

I ran `task` with strace, does this help?
https://gist.github.com/zmingee/ffc3eb6981e5aa592ae51ddab41d7ffa

**Comment by zmingee** [comment]
Actually, I've figured it out after reviewing the strace a bit more. My config was attempting to load a taskwarrior theme that was causing a failure. Not sure why that would cause a segfault, but after commenting that line it works.

My apologies, thank you for the quick response!
