### ISSUE TITLE
Unable to Move file 

### ISSUE THREAD

**Issue by RahulandRh** [termux/termux-packages#4846]
Cannot Create new file , permission Error. 
Even i allow that 

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by kcubeterm** [comment]
Can you describe, from where to where,you try to move file, if you try to move file from home to any sdcard directory, make sure you have gave the storage permission to termux app, 

Start from here.
`termux-setup-storage`
Now give permission  and try again to move your file, if not succeed, please provide output of ` termux-info` command.

**Comment by Grimler91** [comment]
Closing due to lack of information (use the bug report template)

**Comment by RossComputerGuy** [comment]
Btw, might be released to #4217

**Comment by RahulandRh** [comment]
I Give the permission then i write this
mv cam1334.png /storage/dcim
but it show error

**Comment by Grimler91** [comment]
> I Give the permission then i write this 
> mv cam1334.png /storage/dcim 
> but it show error

That folder doesn't exist. You probably meant ~/storage/dcim.

**Comment by RahulandRh** [comment]
It exist
