### ISSUE TITLE
Ip issue

### ISSUE THREAD

**Issue by Islam788** [termux/termux-packages#4847]
See man when I tried to display my ip by the command <ifconfig> it's showing something different or I'm unable to identify my ip please help
![Screenshot_20200127_181130_com termux](https://user-images.githubusercontent.com/60348966/73216905-f0cdf100-417c-11ea-9da3-3cb68b29bf13.jpg)

**Comment by xeffyr** [comment]
Check out the `rmnet0` interface info. Lines you are seeking for starting with `inet` and `inet6`.
