### ISSUE TITLE
Package request: ssh-import-id

### ISSUE THREAD

**Issue by guoqiao** [termux/termux-packages#4848]
**Package description**

This package can import ssh public key for a user from github or launchpad:

```
ssh-import-id gh:guoqiao
ssh-import-id lp:guoqiao
```
Currently while using Termux as SSH server on mobile, we have to send our pub key to mobile, copy and paste it into `~/.ssh/authorized_keys`,  then we can ssh to mobile from computer.
With this package, we can make this process much simplier.

**Link to home page and sources**
1. Home page: https://code.launchpad.net/ssh-import-id
2. Source code: https://launchpad.net/ssh-import-id

**Comment by ifurther** [comment]
@guoqiao Is it the python module ?

**Comment by landfillbaby** [comment]
just run `pip install ssh-import-id` like it says in the readme, it worked in a venv on my phone just now
