### ISSUE TITLE
Can't install any package

### ISSUE THREAD

**Issue by MSGunter** [termux/termux-packages#485]
Hello, 

i've installed Termux today, but I can not install any package.
For example, I wanted to install fpc (free pascal compiler) but...

apt install fpc
The program 'apt' is not installed. Install it by executing:
apt install apt

**Comment by fornwall** [comment]
What is the output of `echo $PATH` and `ls $PREFIX/bin`?

**Comment by MSGunter** [comment]
`$ echo $PATH`
`/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets`

`$ $PREFIX/bin`
`-bash: /data/data/com.termux/files/usr/bin: Is a directory`

**Comment by Neo-Oli** [comment]
@MSGunter The second command should be:
`ls  $PREFIX/bin`

the `ls` is important

**Comment by MSGunter** [comment]
oh sorry, i didnt see it

`$ ls $PREFIX/bin`

`am                      dpkg-split
applets                 dpkg-trigger
apt                     env
apt-cache               getprop
apt-config              gpgv
apt-get                 ip
apt-key                 logcat
ash                     ping
bash                    ping6
busybox                 pm
chsh                    settings
dalvikvm                sh
dash                    su
df                      termux-fix-shebang
dpkg                    termux-open-url
dpkg-deb                termux-reload-settings
dpkg-divert             termux-setup-storage
dpkg-query`

**Comment by fornwall** [comment]
Hm, and running just `apt` does not work? What device is this, and which Android version? Custom ROM or rooted?

**Comment by MSGunter** [comment]
It's solved. I've forgotten the comand `apt update` ...
