### ISSUE TITLE
ClamAV: Failure updating the main database: TIMEOUT

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#4852]
I installed ClamAV (`pkg install clamav`) and did

`$ freshclam`

but when updating the main database it failed with a TIMEOUT message (67MiB/112MiB). It estimates about 100 seconds for the download but after about 60 seconds it fails as described.

I use ClamAV on the same network on GNU/Linux Mint, macOS via MacPorts and on Windows via WSL (_Windows Subsystem Linux_). On these systems I don't have issues.

Any suggestion? Thanks.

**Comment by xeffyr** [comment]
> it failed with a TIMEOUT message 
It estimates about 100 seconds for the download

More like a networking issue. You may need to change this line in `$PREFIX/etc/clamav/freshclam.conf`:
```
DatabaseMirror database.clamav.net
```

However the default one works for me:
![Screenshot_20200129-232109_Termux](https://user-images.githubusercontent.com/25881154/73398461-352cce80-42ee-11ea-9cfa-b7799af1022d.jpg)


>On these systems I don't have issues.

These systems check DB updates over DNS. Termux build applies `--disable-dns` for compatibility with Android OS. Issue may be here, but in such case can't be fixed.
