### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wuffeljunior90** [termux/termux-packages#4853]
**Problem description**

After updating Termux a few days ago, i can't use my scripts for clickbots anymore.
When i try to start the script then the above error comes up.

**Steps to reproduce**

Try with Doge: 

cd /sdcard/doge
$ python doge.py -phone number-
  File "doge.py", line 4
    m
     Z
      Z
     ^
SyntaxError: invalid syntax
$

**Expected behavior**

Can the scripts be used again in the future? Or can i copy old instances of the packages and pips?

**Additional information**

$ termux-info
Packages CPU architecture:
arm
Subscribed repositories:
 sources.list
deb https://termux.org/packages/ stable main
 game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
 science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.18.91-17281512 #1 SMP PREEMPT Wed Nov 13 13:34:23 KST 2019 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J330F

I'll attach the zip folder with the bots.
[clickbots.zip](https://github.com/termux/termux-packages/files/4132825/clickbots.zip)

--Sorry, haven't seen that this is the packages section.
--Can be moved

**Comment by Grimler91** [comment]
Clearly something is wrong with the doge.py script. That script isn't from termux so ask the script author for help troubleshooting it.
