### ISSUE TITLE
Opensshd issue

### ISSUE THREAD

**Issue by Minhajul788** [termux/termux-packages#4855]
When I tried to review the opensshd then I'm facing with an issue that is permission denied
$PREFIX/etc/ssh/sshd_config
bash: /data/data/com.termux/files/usr/etc/ssh/sshd_config: Permission denied
Anyone could tell me that how can I fix the issue 
![Screenshot_20200131_015645_com termux](https://user-images.githubusercontent.com/60433952/73491905-9f6c6e80-43d5-11ea-9586-22dbdca14733.jpg)

**Comment by xeffyr** [comment]
Correct way to print configuration is:
```
cat $PREFIX/etc/ssh/sshd_config
```
