### ISSUE TITLE
Package request: broot

### ISSUE THREAD

**Issue by neitsab** [termux/termux-packages#4858]
**Package description**

"Broot - A better way to navigate directories / A new way to see and navigate directory trees": an all-in-one solution improving user experience over `cd`, `ls`, `(nc)du`...

Discovered via the [HN frontpage](https://news.ycombinator.com/item?id=21998638) where it garnered an impressive 1448 points a few weeks ago, with the top comment saying:

> I'm one of those skeptic people who always criticize just because I'm a negative person. However... I LOVE THIS PROGRAM! I really, really, really love it!
> 
> I don't care if it's been done before. I don't care if <insert name here> exists and does a similar thing.
> 
> Awesome because:
>
> - short name (br in terminal, I'll remember that instantly)
> 
> - easy installation
> 
> - web page is awesome and shows you instantly how to best use this program
> 
> - help page in the program itself is awesome, clear and easy to navigate
> 
> - defaults are sensible and totally easy to get used to
> 
> - broot just WORKS! and it works well, I finally got rid of all the aliases around ls that I used in order to get info I want
> 
> Amazing job Denys, 10/10 for the web, program, documentation and examples!

**Link to home page and sources**
1. Home page: https://dystroy.org/broot
2. Source code: https://github.com/Canop/broot

**Additional information**
Have you compiled or tried to compile the package on device?

No

* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

I tried to run the supplied RPi binary but it was for 32-bit ARM. Upstream bug report requesting arm64 build: https://github.com/Canop/broot/issues/186

Thank you for your work!

**Comment by hnmn** [comment]
@neitsab  today i successfully compile broot 
I works fine

Broot needs rust compiler 
So install rust, rustc-dev 
And install broot using cargo
And add compile binaries to PATH 
and add broot's br function to .bashrc 

![Screenshot_2020-02-19-01-57-56-119_com termux](https://user-images.githubusercontent.com/26086203/74775336-7eec5180-52bb-11ea-979b-cef14ac39b9d.jpg)
![Screenshot_2020-02-19-01-58-18-901_com termux](https://user-images.githubusercontent.com/26086203/74775343-83186f00-52bb-11ea-93b4-93e7116dda93.jpg)

**Comment by Canop** [comment]
Oh, you didn't cross compile, you compiled directly on termux ?

**Comment by hnmn** [comment]
Yuh!  I just install rust And 
Cargo install broot

**Comment by hnmn** [comment]
Also i successfully compile RE-flex on termux
As u can seen in screenshot
But cannot bulid examples of RE-flex
I'm just noob if someone has time to 
Pack into .deb plz do 

But there is warning showing 

`unsupported flags DT_FLAGS_1=0x8000001`

**Comment by ryanerwin** [comment]
Thanks @hnmn worked great for me!

```
pkg install rust
cargo install broot
cp ~/.cargo/bin/broot ~/../use/bin
```
