### ISSUE TITLE
Wireguard indirectly requires root

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#4859]
**Problem description**
Wireguard itself doesn't require root technically, but a user must be able to create a new network interface in order to create a tunnel. This requires root. Therefor shouldn't the wireguard package be in the root-repo?

**Steps to reproduce**
1. install wireguard-tools package in Termux (root repo is not enabled)
2. Attempt the first step of the [Wireguard quickstart guide](https://www.wireguard.com/quickstart/) using this command: ` ip link add dev wg0 type wireguard`
3. recieve this error: `request send failed: Permission denied`

**Expected behavior**

wireguard-tools should be in the root-repo unless there is non-root way to create a network interface or if there is another use for Wireguard that I'm not aware of.

**Additional information**

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g606096e-dirty #1 SMP PREEMPT Tue Jan 17 18:10:20 KST 2017 armv7l Android
Device manufacturer:
LGE
Device model:
LGL84VL

```

**Comment by xeffyr** [comment]
That was already discussed. It also requires a custom kernel.

https://gitter.im/termux/dev/archives/2019/03/17:
> @Grimler91:
partly
it can be used to generate keypairs
and to control wg interface
