### ISSUE TITLE
Error sqlite3 and rb-inotify

### ISSUE THREAD

**Issue by user3710** [termux/termux-packages#486]
worked perfectly the instalation of ffi but now, I have the problem in two other gems:

Installing sqlite3 1.3.11 with native extensions

and

Installing rb-inotify 0.9.7
Gem :: Ext :: BuildError: ERROR: Failed to build gem native extension.

follows the whole code, I am now starting on schedule, so we still do not understand these minutiae and problems related problems.
sorry if I'm being boring

//
current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/ext/sqlite3
/data/data/com.termux/files/usr/bin/ruby -r
./siteconf20160929-15705-j9kt9q.rb extconf.rb
checking for sqlite3.h... no
sqlite3.h is missing. Try 'port install sqlite3 +universal',
'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
and check your shared library search path (the
location where your sqlite3 shared library is located).
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers. Check the mkmf.log file for more details. You may
need configuration options.

Provided configuration options:
--with-opt-dir
--without-opt-dir
--with-opt-include
--without-opt-include=${opt-dir}/include
--with-opt-lib
--without-opt-lib=${opt-dir}/lib
--with-make-prog
--without-make-prog
--srcdir=.
--curdir
--ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
--with-sqlite3-dir
--without-sqlite3-dir
--with-sqlite3-include
--without-sqlite3-include=${sqlite3-dir}/include
--with-sqlite3-lib
--without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which
can be found here:

/data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/extensions/arm-linux/2.3.0/sqlite3-1.3.11/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11 for
inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/extensions/arm-linux/2.3.0/sqlite3-1.3.11/gem_make.out

An error occurred while installing sqlite3 (1.3.11), and Bundler
cannot continue.
Make sure that gem install sqlite3 -v '1.3.11' succeeds before
bundling.//

Just an afterthought, the sqlite3 gem appears on the project Gemfile, but does not appear when I run the gem command list, and the bundle can not install it

**Comment by fornwall** [comment]
Run `apt install libsqlite-dev` before installing the sqlite3 gem, and run `apt install libffi-dev` before installing rb-inotify.

**Comment by user3710** [comment]
Now its run perfectly, thanks very much.

**Comment by fornwall** [comment]
@user3710 Nice!

**Comment by wptechprodigy** [comment]
Thanks @fornwall
