### ISSUE TITLE
Package request: blackbox

### ISSUE THREAD

**Issue by oxr463** [termux/termux-packages#4860]
**Package description**
Safely store secrets in Git/Mercurial/Subversion

**Link to home page and sources**
1. Home page: https://github.com/StackExchange/blackbox
2. Source code: https://github.com/StackExchange/blackbox

**Additional information**
Have you compiled or tried to compile the package on device?
Yes, no compilation necessary as it is just scripts.

**Comment by oxr463** [comment]
Depends on: https://github.com/StackExchange/blackbox/pull/294

**Comment by RossComputerGuy** [comment]
Note: there's a Makefile that can do the installing **but** there's no way to change the destination directory. Whoever adds this should also have `sed` change the paths to be right for the scripts.

**Comment by oxr463** [comment]
> 
> 
> Note: there's a Makefile that can do the installing **but** there's no way to change the destination directory. Whoever adds this should also have `sed` change the paths to be right for the scripts.

The linked PR above fixes that.

**Comment by RossComputerGuy** [comment]
I commented that like just as you were linking the PR.

**Comment by oxr463** [comment]
![Screenshot_20200131-134658](https://user-images.githubusercontent.com/43783393/73565771-4847b780-4430-11ea-989d-45f4d6cac0f7.png)

**Comment by xploitednoob** [comment]
Package Has Beed Added Close This Issue.
@xeffyr
