### ISSUE TITLE
Mpd error 

### ISSUE THREAD

**Issue by kcubeterm** [termux/termux-packages#4868]
mpd output,

```
$ mpd badboy.m4a                                                            exception: Error in badboy.m4a line 2
exception: nested: Invalid word character

```

I am aware of following issues,
https://github.com/termux/termux-packages/issues/3441

https://github.com/termux/termux-packages/issues/2142

**Comment by kcubeterm** [comment]
![Screenshot_2020-02-02-18-55-24-757_com termux](https://user-images.githubusercontent.com/50498359/73608830-a66dc980-45ed-11ea-9650-49a5bb632e35.jpg)

**Comment by xeffyr** [comment]
Are you sure that your m4a file is not corrupted ?

Issues https://github.com/termux/termux-packages/issues/3441 and https://github.com/termux/termux-packages/issues/2142 are not related to this one.

**Comment by kcubeterm** [comment]
Yes , i am , if my m4a file is corrupted, then it should not play with mpv  or my system music player,

**Comment by Nitroretro** [comment]
@kcubeterm You are using MPD incorrectly. The syntax looks like this:

```shell
mpd [options] [CONF_FILE]
```

You are specifying your `.m4a` file as a configuration file. Here's the [ArchWiki link for Music Player Daemon](https://wiki.archlinux.org/index.php/Music_Player_Daemon) for more information on how to use it (you will have change some stuff such as file paths).

**Comment by kcubeterm** [comment]
@Nitroreto thanks, i will see user manual later, but many of time i used mpd same as above then it's played. Maybe New version has new manual, anyway thanks
