### ISSUE TITLE
xz-utils：decompress is extremely slow with some file larger than 1M

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-packages#487]
It took forever to decompress file larger than 1M. (I aborted after several minutes).
Several seconds to decompress f1.xz:
$xz -l f1.xz
Strms  Blocks   Compressed Uncompressed  Ratio  Check   Filename
    1       1    884.4 KiB  3,283.6 KiB  0.269  CRC64   f1.xz

pretty slow to decompress f2.xz:
$ xz -l f2.xz
Strms  Blocks   Compressed Uncompressed  Ratio  Check   Filename
    1       1    889.2 KiB  4,034.1 KiB  0.220  CRC64   f2.xz

take eons to decompress f3.xz and larger ones I tried: (I aborted it)
$ xz -l f3.xz
Strms  Blocks   Compressed Uncompressed  Ratio  Check   Filename
    1       1  1,371.1 KiB  6,966.8 KiB  0.197  CRC64   f3.xz

The implementation of unxz is definitely wrong here.

**Comment by torappinfo** [comment]
BTW, my os is android 5.1
CPU is MTK.

**Comment by fornwall** [comment]
Could you link to a file which is unreasonable slow to decompress?

**Comment by torappinfo** [comment]
$ time xz -cdf -- cp.xz > /dev/null
real    6m57.164s
user    0m0.470s
sys     0m0.000s

The file is here:
https://drive.google.com/open?id=0ByDAivCLYrZEN1FOWHlHTnhSY2c

$ xz -l cp.xz
Strms  Blocks   Compressed Uncompressed  Ratio  Check   Filename
    1       1  1,450.4 KiB  8,113.1 KiB  0.179  CRC64   cp.xz

I tried more file, some larger files can be decompressed faster. Maybe this is the reality.

**Comment by torappinfo** [comment]
It seems reasonable to decompressing 3.7M file in 44s.

$ xz -l de.txt.xz
Strms  Blocks   Compressed Uncompressed  Ratio  Check   Filename
    1       1  3,701.2 KiB     15.1 MiB  0.240  CRC64   de.txt.xz
$ time xz -cdf -- de.txt.xz > /dev/null

real    0m44.551s
user    0m1.040s
sys     0m0.010s

**Comment by fornwall** [comment]
> $ time xz -cdf -- cp.xz > /dev/null
> real 6m57.164s
> user 0m0.470s
> sys 0m0.000s
>
> The file is here:
> https://drive.google.com/open?id=0ByDAivCLYrZEN1FOWHlHTnhSY2c

That's really strange - I tested it on three devices (the oldest being a Nexus 7 tablet from 2012) and all decompress the cp.xz file here under a second.

What is the output of running `dpkg --print-architecture`?

Which device is this exactly (can you find a link to device information online)?

**Comment by torappinfo** [comment]
$ dpkg --print-architecture
aarch64
The device is "360 f4", the CPU is MT6753 which is pretty fast.
Maybe this is a bug in MTK CPUs.

**Comment by torappinfo** [comment]
Move cp.xz to tmpfs, and run the command "xz -d cp.xz" multiple times,
Sometimes it is very fast, and the decompressed file is complete. Many times, it is very slow. When using strace, it is not as slow as 6m57s,
The only gap in the strace log:
10:59:19 write(6, "\n####counsel \n\n**counsel **\n\nUK "..., 8192) = 8192
11:02:08 write(6, ".t\314\254\311\232.rev.\311\231\313\210lu\313\220.\312\203\311\231n , US \313"..., 8192) = 8192

**Comment by torappinfo** [comment]
running "strace -t xz -d -k cp.xz 2>a.log" on tmpfs, whenever I run "less a.log",
the strace finished immediatey. If I never touch a.log, the strace command may hang for infinite long.

"xz -d cp.xz" is similar, It may hang for infinite long, but whenever I run "ls", it finishes immediately.

So, there seems to exist some "flush" issues here, it may relate to some kernel parameters that I changed:
echo "1000" > /proc/sys/vm/dirty_expire_centisecs
echo "2000" > /proc/sys/vm/dirty_writeback_centisecs

echo "90" > /proc/sys/vm/dirty_ratio
echo "60" > /proc/sys/vm/dirty_background_ratio

echo "1" > /proc/sys/vm/oom_kill_allocating_task

**Comment by torappinfo** [comment]
It seems the CPU cores went sleep before unxz finishes its job. 
If I keep pressing keys, unxz will finish soon.

**Comment by fornwall** [comment]
Does taking a wake lock avoid the CPU sleeping?

Take a wake lock by pulling down the notification bar, then pinch expand the notification and press the `WAKE` button.

I'm closing this issue as I don't think that, besides the above solution with a wake lock, there is anything else Termux as an app can do to keep the cores alive.
