### ISSUE TITLE
opengl glx not working?

### ISSUE THREAD

**Issue by d762** [termux/termux-packages#4872]
I successfully installed and ran xfce on chroot but when i tried to run an application i got the error: GLX extension not supported by display. This app is very important to me...:(

I havent installed any drivers but i did try freedreno but i ran into issues. Will installing it solve the problem? there is only libdrm of freedreno installed atm.

as feeedreno is kinda inactive git i will post my errors here about freedreno compilation problems if u want.

**Comment by RossComputerGuy** [comment]
What errors were printed to the console?

**Comment by d762** [comment]
So first i had: 

`gcc: error: unrecognized command line option ‘-mfloat-abi=soft’`

then i removed it but i got:

`ld --entry=_start -nostdlib --dynamic-linker /system/bin/linker -rpath /system/lib -L /system/lib test-varyings.o bmp.o -lC2D2 -lOpenVG -lEGL_adreno200 -lGLESv2_adreno200 -lOpenCL -lgsl -llog -lcutils -lstdc++ -lstlport -lm -ldl -lc -o test-varyings
ld: cannot find -lC2D2
ld: cannot find -lOpenVG
ld: cannot find -lEGL_adreno200
ld: cannot find -lGLESv2_adreno200
ld: cannot find -lOpenCL
ld: cannot find -lgsl
ld: cannot find -llog
ld: cannot find -lcutils
ld: cannot find -lstdc++
ld: cannot find -lstlport
ld: cannot find -lm
ld: cannot find -ldl
ld: cannot find -lc`

**Comment by RossComputerGuy** [comment]
Add `-rpath $PREFIX/lib` to after `-rpath /system/lib`.

**Comment by d762** [comment]
> Add `-rpath $PREFIX/lib` to after `-rpath /system/lib`.

I havent quite understand you or the command. I should add a prefix before /system/lib/ to link it to libs it can not find? These libs are in android system folder?

**Comment by RossComputerGuy** [comment]
Right now, its linking only /system/lib which contains android libraries. It will find more by adding the argument I told you to add.

**Comment by xeffyr** [comment]
There also `/system/vendor/lib` - for platform-specific libraries like libOpenCL.so.
If still libs not found, use `--library-path` or `-L` linker flag.

**Comment by d762** [comment]
thanks guys will add both.

**Comment by d762** [comment]
Somehow its not connecting to the system folder. 

So i added -L to gcc (both $PREFIX and vendor/lib). I did the same in the ld with addition to rpath for both as well. Libs were mostly in vendor/lib and vendor/lib/egl. 

same error even though libs are there.

**Comment by d762** [comment]
ld command:

ld --entry=_start -nostdlib --dynamic-linker /system/bin/linker -rpath /system/lib -rpath $PREFIX/lib -rpath /system/vendor/lib -L /system/lib -L /system/vendor/lib test-varyings.o bmp.o -lC2D2 -lOpenVG -lEGL_adreno200 -lGLESv2_adreno200 -lOpenCL -lgsl -llog -lcutils -lstdc++ -lstlport -lm -ldl -lc -o test-varyings`

gcc command

`gcc -L /system/lib -L /system/vendor/lib -L $PREFIX/lib`

**Comment by d762** [comment]
Buuumpppp...
