### ISSUE TITLE
Package `cec-utils`

### ISSUE THREAD

**Issue by i-demetriou** [termux/termux-packages#4876]
**Package description**
`cec-utils` allows you to control HDMI CEC enabled devices from your Linux machine. This opens up many opportunities for an android box connected to an HDMI TV with termux installed

**Link to home page and sources**
https://github.com/Pulse-Eight/libcec

**Additional information**
I didn't try to compile it myself

**Comment by 5p0ng3b0b** [comment]
```
#!/data/data/com.termux/files/usr/bin/sh
mkdir cectools; cd cectools
git clone https://github.com/Pulse-Eight/platform.git
cd platform; mkdir build; cd build
cmake ..
sed -i "s#/usr/local#$PREFIX#g" cmake_install.cmake
make
make install
cd ../..
git clone https://github.com/mdrjr/libcec.git
cd libcec
./bootstrap
./configure --enable-exynos --prefix=$PREFIX
make
make install
```

**Comment by xploitednoob** [comment]
>```
> git clone https://github.com/mdrjr/libcec.git
>```

Why Have You Used This One Instead Of This One
https://github.com/Pulse-Eight/libcec

**Comment by 5p0ng3b0b** [comment]
@xploitednoob 
I wonder. Have you tried compiling https://github.com/Pulse-Eight/libcec youself?

**Comment by xploitednoob** [comment]
> @xploitednoob
> I wonder. Have you tried compiling https://github.com/Pulse-Eight/libcec youself? ;-)

Yes I Have Tried.

**Comment by 5p0ng3b0b** [comment]
Well there is your answer then!

**Comment by xploitednoob** [comment]
> Well there is your answer then!

When i was building i didn't got any error

**Comment by 5p0ng3b0b** [comment]
You have to specify the com port that cec uses which will vary between devices.
