### ISSUE TITLE
Package Emacs

### ISSUE THREAD

**Issue by c4dr01d** [termux/termux-packages#4878]
Hello, the emacs package can using fully compiled emacs? I found when every time I start emacs it will load not compiled emacs lisp files. In the other platforms like Linux Deploy, they provide fully compiled emacs and bootstrap quickly, I don't know the maintainer can accept my advice, thanks.

**Comment by xeffyr** [comment]
Packaging dumped emacs currently is not possible until https://github.com/termux/termux-packages/pull/4622 will be solved.
