### ISSUE TITLE
termux does not have a release file

### ISSUE THREAD

**Issue by zahra-s** [termux/termux-packages#4879]
When trying to install git via Termux on my Chromebook, I received this bug:

 '``https://termux.org packages stable Release does not have a Release file`' 

What should I do?

**Comment by xeffyr** [comment]
This is not bug. Maybe you used `apt` or `pkg` while repo data was changing.

Retry now.

**Comment by zahra-s** [comment]
This happens whenever I try to install anything. Here's the full text:

![Screenshot 2020-02-06 at 8 11 50 AM](https://user-images.githubusercontent.com/60659863/73944860-e916f680-48b8-11ea-84d2-22576c26ea8b.png)

**Comment by xeffyr** [comment]
@zahra-s You have either problem with networking or something wrong with your installation.

Suggesting to run `pkg upgrade`, if still `SSL_ERROR_SYSCALL` then it is time to clear app data (or `rm -rf $PREFIX`) to recover installation.

**There no problems with repository.**

**Comment by zahra-s** [comment]
Issue was with the wifi. Thanks!

**Comment by Reikha838** [comment]
> @zahra-s You have either problem with networking or something wrong with your installation (e.g. dependency version mismatch).
> 
> Suggesting to run `pkg upgrade`, if still `SSL_ERROR_SYSCALL` then it is time to clear app data (or `rm -rf $PREFIX`) to recover installation.
> 
> **There no problems with repository.** (otherwise our bug tracker will be filled with those issues)

I already clear the data but still error

**Comment by Reikha838** [comment]
> @zahra-s You have either problem with networking or something wrong with your installation (e.g. dependency version mismatch).
> 
> Suggesting to run `pkg upgrade`, if still `SSL_ERROR_SYSCALL` then it is time to clear app data (or `rm -rf $PREFIX`) to recover installation.
> 
> **There no problems with repository.** (otherwise our bug tracker will be filled with those issues)

Can you help me

**Comment by agnostic-apollo** [comment]
>Can you help me

Your issue is likely not related to this issue. Check #6726 and install from F-Droid.
