### ISSUE TITLE
Package request: biber

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#4887]
@Grimler91 wrote

> We generally don't package python/perl/node/ruby/other packages if they are installable through another package manager 

As you can see from [#4871](https://github.com/termux/termux-packages/issues/4871#issuecomment-583614984), you cannot pretend an user does all the work I did today to get Biber in Termux+texlive, and without Biber, TeXLive is _crippled_ :-(

**Comment by eine** [comment]
IMHO, `biber` should be available in a "standard" texlive distribution, provided that the size is negligible compared to the environment itself. As @angelog0 said, biblatex and biber are required for multiple practical uses of texlive.

**Comment by Grimler91** [comment]
@eine as soon as someone figures out how to reliably cross-compile perl modules we can add it

**Comment by eine** [comment]
@Grimler91, note that I'm ok with using any external repository (as for GCC). Moreover, I'm still finding it difficult to believe that all these awesome tools are available on my smartphone. Hence, I wouldn't like to put any pressure at all. I just wanted to acknowledge that it should not be neglected.

**Comment by Grimler91** [comment]
I have added a package `biber` to the unstable repository which installs biber and dependencies in a postinst script. Please let me know if you run into any problems when installing it!

**Comment by angelog0** [comment]
@Grimler91 wrote:

> I have added a package `biber` to the unstable repository which installs biber and dependencies in a postinst script. Please let me know if you run into any problems when installing it!

Maybe I am wrong but it seems not *installing* binaries but *building* binaries.. I would prefer just a binary package...

Anyway thanks for adding this..

BTW, it seems to build 2.14 but will it [work](https://github.com/termux/termux-packages/issues/4871#issuecomment-583629144)?

**Comment by Grimler91** [comment]
@angelog0 yepp, it compiles/installs the dependencies and applies patches when necessary. 
Binary package will not be possible unless perl improves cross-compilation support. 

biber 2.14 works with biblatex 3.14, i.e. the version that can be installed through tlmgr. 
texlive-bibtexextra contains biblatex 3.12 so I guess that combination will not work.
