### ISSUE TITLE
Metasploit build is unstable.

### ISSUE THREAD

**Issue by H4ck3r404** [termux/termux-packages#4889]
Some time ago I was having a problem with only one module. Now command "reload_all" showed me that some other modules couldn't be loaded.
Note that it was after reinstalling termux with only metasploit packet.
I am using clear termux without any prefix changes.

**Comment by xeffyr** [comment]
Have you noticed that it is in [unstable-packages](https://github.com/termux/unstable-packages) ?
Also: https://github.com/termux/unstable-packages/issues/109. This package never will be stable.

**Comment by xeffyr** [comment]
And I should note that metasploit is not packaged but sideloaded. My package is just installer & startup script.
