### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by Edisoni** [termux/termux-packages#489]
![screenshot_2016-10-05-23-12-50](https://cloud.githubusercontent.com/assets/10086099/19129827/684d1de0-8b51-11e6-80e8-31d1c1e06b1c.jpg)
Android 5.0

**Comment by comp500** [comment]
The apt repositories also seem to be down, giving the error 409 (Conflict) on `wget http://apt.termux.com/dists/stable/InRelease`
I'm on android 6.0.1, but the 409 error happens on my desktop as well. This probably means that termux's servers are down.

**Comment by fornwall** [comment]
Looking into it.

**Comment by fornwall** [comment]
@Edisoni @comp500 Does it work for you now?

**Comment by comp500** [comment]
@fornwall It works great. Can't speak for the install, as I already have it installed, but apt packages now work. Thanks for the quick response.
