### ISSUE TITLE
Can't use any command with apt,pkg,dpkg

### ISSUE THREAD

**Issue by 0x-MRNOBODY-x0** [termux/termux-packages#4891]
:~# pkg update
Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:4 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:4 https://dl.bintray.com/grimler/game-packages-21 games Release
Get:6 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:6 https://dl.bintray.com/grimler/science-packages-21 science Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up termux-tools (0.75) ...
dpkg: error processing package termux-tools (--configure):
 unable to change ownership of target file '/data/data/com.termux/files/usr/etc/motd.dpkg-new': Operation not permitted
Errors were encountered while processing:
 termux-tools
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by xeffyr** [comment]
1. Do not use package manager as root. Easiest way to fix will be `rm -rf $PREFIX` and restart application.
2. Legacy repository (termux.net) is out of support.

**Comment by 0x-MRNOBODY-x0** [comment]
It will remove my all packages. Don't you have another option for this?
