### ISSUE TITLE
Horrorscope

### ISSUE THREAD

**Issue by leetcool** [termux/termux-packages#4896]
[horrorscope.zip](https://github.com/termux/termux-packages/files/4180058/horrorscope.zip)

**Package description**
Just a simple terminal horoscope cow, to view horoscope in *nix terminals.
Why is should be there? Well because reading your horoscope via terminal is fun. Being a linux user i stick with terminals all the time, what could be better than opening termux and typing "hs" (Preferred ELF name for easy use) to see how your day is going to be.

**Link to home page and sources**
1. Home page: https://leetcool.github.io/
2. Source code: https://github.com/leetcool/horrorscope

**Additional information**
Have you compiled or tried to compile the package on device? 
Yes.
* If it didn't work then please provide the error you ran into.
It Worked.
* If it did work then please share any patches that you had to apply.
It requires cowsay, curl & lolcat auto installation of these is available by package itself.

This is my first ever contribution to OSS world and i'm really excited about it. <3

**Comment by leetcool** [comment]
@xeffyr what's next? shall I just wait?

**Comment by xeffyr** [comment]
Sorry, but we are not packaging stuff which is not recognized across common Linux distributions.

I have also reviewed the https://github.com/leetcool/horrorscope/blob/master/horrorscope.cpp - the way how it works with its files really inacceptable... Why not to implement it as Bash script instead, if you relying on shell variables ($HOME) and commands.
