### ISSUE TITLE
build package failed with different TERMUX_PREFIX

### ISSUE THREAD

**Issue by privnote42** [termux/termux-packages#4897]
**Problem description**
build of many packages with build-package.sh failed, if TERMUX_PREFIX and TERMUX_ANDROID_HOME is changed.

```
builder@1f4e1c8f4eae:~/termux-packages$ ./build-package.sh htop

Building dependency libandroid-support if necessary...
libandroid-support@25-2 built - skipping (rm /data/data/.built-packages/libandroid-support to force rebuild)
Building dependency ncurses if necessary...
ncurses@6.1.20190928 built - skipping (rm /data/data/.built-packages/ncurses to force rebuild)
termux - building htop for arch aarch64...
configure: WARNING: unrecognized options: --disable-rpath, --disable-rpath-hack, --disable-nls, --enable-shared, --enable-static
checking build system type... x86_64-pc-linux-gnu
checking host system type... aarch64-unknown-linux-android
checking target system type... aarch64-unknown-linux-android
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for aarch64-linux-android-strip... aarch64-linux-android-strip
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for aarch64-linux-android-gcc... aarch64-linux-android-clang
checking whether the C compiler works... no
configure: error: in `/home/builder/.termux-build/htop/src':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Steps to reproduce**
1. change TERMUX_PREFIX and TERMUX_ANDROID_HOME
export TERMUX_PREFIX=/data/data/com.termuxFork.support/files/usr
export TERMUX_ANDROID_HOME=/data/data/com.termuxFork.support/files/home

2. build package in official termux docker container
https://github.com/termux/termux-packages/blob/master/scripts/Dockerfile
./build-package.sh htop

**Expected behavior**
build without errors; ./build-package.sh dash works for example

**Comment by Grimler91** [comment]
What's the actual error in `config.log`?

**Comment by xeffyr** [comment]
Idk what you did with build scripts or environment variables, but with following your steps I was able to build `htop` with custom prefix successfully.

My console log: https://linx.li/hkfsv0wj.txt

Things to check for you:

* Ensure that no changes done to Termux build scripts.
* Ensure that Docker image is up to date, clean and permissions in /data are not messed up.
* Ensure that package dependencies are built fully, e.g. never use `./build-package.sh -I` or `./build-package.sh -i` when custom prefix is used.
* TERMUX_PKG_API_LEVEL is not modified. For Termux master branch its value should be `24`.
