### ISSUE TITLE
Package request: Gnat

### ISSUE THREAD

**Issue by AnderRasoVazquez** [termux/termux-packages#49]
GNAT is a free-software compiler for the Ada programming language which forms part of the GNU Compiler Collection. It supports all versions of the language, i.e. Ada 2012, Ada 2005, Ada 95 and Ada 83.

**Comment by fornwall** [comment]
Thanks for the suggestion! I started a [wiki page to keep track of package suggestions](https://github.com/termux/termux-packages/wiki/Package-suggestions) and have added Gnat there!

**Comment by Neo-Oli** [comment]
Hi, I am re-opening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by xeffyr** [comment]
Gnat for Termux seems to be here: https://github.com/its-pointless/its-pointless.github.io

Regarding package request - it is very unlikely be implemented as part of [termux-packages](https://github.com/termux/termux-packages) since we already excluded GCC.

**Comment by eine** [comment]
> Regarding package request - it is very unlikely be implemented as part of [termux-packages](https://github.com/termux/termux-packages) since we already excluded GCC.

Would you mind elaborating? I just tried termux and I found that GCC is installed by default. However, gnat is not available.

**Comment by xeffyr** [comment]
> I just tried termux and I found that GCC is installed by default.

`gcc` is a symlink to `clang` unless you installed GCC from repository maintained by @its-pointless.
