### ISSUE TITLE
aapt consistently segfaults when building a new package

### ISSUE THREAD

**Issue by joakim-noah** [termux/termux-packages#490]
I try to package an apk using this command from #63, using the android.jar you gave me:
```
aapt package -M AndroidManifest.xml -S res -I /sdcard/Download/android.jar -F hello-jni.apk
```
This used to work but now it segfaults on all the NDK sample apps, probably related to the recent version bumps.

**Comment by fornwall** [comment]
Could you run `apt update && apt upgrade` and check if it works better in the latest version?

**Comment by joakim-noah** [comment]
Yes, it works now, thanks for fixing it.
