### ISSUE TITLE
Cannot write pendrive

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#4907]
It seems that Termux cannot write on an USB key. I see the key mounted under `/storage` but, removing or creating file, fails:

```
rm /storage/1234-ABCD/bar    # Permision denied
touch /storage/1234-ABCD/foo  # Permission denied
```

instead it can read files there:

```
cat /storage/1234-ABCD/foo
Hello!

```

Is the above to be expected?
Are there workarounds?

I tried (after installing the package)

termux-usb -l

but it seems to hangs (stopped with CTRL-C).

**Comment by xeffyr** [comment]
> Is the above to be expected?

This is expected. Android applies restriction for **raw** file system access to external storage devices.

> Are there workarounds?

You can write to Termux private directory on such storage. Its path
```
/storage/XXXX-XXXX/Android/data/com.termux/files
```
\- where `XXXX-XXXX` is string of random characters unique to your drive (file system UUID).

You may need to create this directory from file manager if it does not exist.

> termux-usb -l
but it seems to hangs

`termux-usb` is for different purposes.

**Comment by angelog0** [comment]
@xeffyr, if I understand, what you called `XXXX-XXXX` here is `2629-BD8F`. Indeed I see the pendrive  content with

`ls -lrt /storage/2629-BD8F/`

So, I just created `Android/data/...` etc. with file manager, under `/storage/2629-BD8F`.

Thanks.
