### ISSUE TITLE
Novnc: vnc client web application

### ISSUE THREAD

**Issue by kcubeterm** [termux/termux-packages#4919]
Benefits: termux user have not install third party vnc client apps, because it a web application,that can run in your web browser .
Source code: https://github.com/novnc/noVNC

I compiled it, it fully functional, there is no error.

**Comment by xeffyr** [comment]
This is not going to be packaged.

**Comment by kcubeterm** [comment]
Ok , because of licence.

**Comment by xeffyr** [comment]
> because of licence.

Because of package format.
Javascript and html stuff is not subject for packaging.

**Comment by kcubeterm** [comment]
Okay, thanks
