### ISSUE TITLE
Report on rebuilding termux-packages in FC23

### ISSUE THREAD

**Issue by banditos13** [termux/termux-packages#492]
Have troubles: apt asciinema clang corkscrew graphicsmagick mc mpv pastebinit php qalc ranger ruby w3m. Possible fixes in attach...
[fixes-termux-packages.txt](https://github.com/termux/termux-packages/files/515481/fixes-termux-packages.txt)

**Comment by fornwall** [comment]
Thanks!

I think the best way forward is to only officially support and recommend using Ubuntu (currently 16.04) for building packages - trying to support multiple build environments will just be too painful (several of the patches here would cause breakage on Ubuntu).

For other Linux distributions (and non-Linux platforms) the best way is to use the Docker setup - I have clarified the README with that, let me know if things can be improved!
