### ISSUE TITLE
love

### ISSUE THREAD

**Issue by TIBTHINK** [termux/termux-packages#4920]
**A simple package that gives you emotional speech**

The love program is your hello world on drugs
I've added in sleep functions and a typewriter effect
its meant to be run when you feel down
other than that it doesn't really have a reason other than to be fun

**Link to home page and sources**
1. Home page: https://tibthink.github.io/love/
2. Source code: https://github.com/TIBTHINK/love

**Additional information**
Have you compiled or tried to compile the package on device?
yes and it runs correctly, same goes for raspberry pi zero

**Comment by RossComputerGuy** [comment]
Isn't love a 2D game engine?

**Comment by TIBTHINK** [comment]
@RossComputerGuy ...apparently it is but is spelled löve

**Comment by pollen5** [comment]
That's pretty useless and didn't Termux had a rule not to request unpopular packages made by yourself?

**Comment by TIBTHINK** [comment]
@pollen5 I dont see any rules saying that at all, also sl is also pretty useless but is still in this repo

**Comment by pollen5** [comment]
Oh well i can't find the rule anymore probably removed.

**Comment by Grimler91** [comment]
It's not a rule. We have 300+ open issues though, useful or popular packages are more likely to get attention by a maintainer

**Comment by xeffyr** [comment]
This is not going to be packaged.

**Comment by TIBTHINK** [comment]
thank you xeffyr
