### ISSUE TITLE
pnpm permission denied

### ISSUE THREAD

**Issue by pollen5** [termux/termux-packages#4924]
pnpm is a package manager for Node.js that caches packages and uses hardlinks to reuse them allowing efficient use of storage space.

When i try to use it i get
```sh
pollen@localhost ~/buymystuff> pnpm install express --save
Packages: +52
++++++++++++++++++++++++++++++++++++++++++++++++++++
 ERROR  EACCES: permission denied, link '/data/data/com.termux/files/home/.pnpm-store/2/registry.npmjs.org/accepts/1.3.7/node_modules/accepts/package.json' -> '/data/data/com.termux/files/home/buymystuff/node_modules/.registry.npmjs.org/accepts/1.3.7/node_modules/_tmp_5949_4a47bc6e104aafa90833876a572be16f/package.json'
Resolving: total 52, reused 50, downloaded 0
```
I have no idea why, in regular Linux desktop it could be things like root owns the directory etc but Termux has a single user but none the less i tried using chmod and chown and failed.

What could be causing this permission error?

**Comment by xeffyr** [comment]
Launch it under `proot --link2symlink`.
Hardlinks are not allowed on Android.

**Comment by pollen5** [comment]
@xeffyr  that gives me
```
pollen@localhost ~/buymystuff>                                        proot --link2symlink pnpm install express --offline
proot info: vpid 1: terminated with signal 11
```
