### ISSUE TITLE
Package request: minidlna

### ISSUE THREAD

**Issue by ruoshan** [termux/termux-packages#4926]
**Package description**
Minidlna is a DLNA server. With this pkg, we can streaming movies to TV via Kodi or other clients.

**Link to home page and sources**
1. Home page: https://github.com/azatoth/minidlna
2. Source code: https://github.com/azatoth/minidlna

**Comment by soyleung** [comment]
Yeah, I like it

**Comment by soyleung** [comment]
Tks

**Comment by soyleung** [comment]
[2020/11/06 17:25:39] minidlna.c:528: No MAC address found.  Falling back to generic UUID.

**Comment by xeffyr** [comment]
> No MAC address found. Falling back to generic UUID.

Expected behavior on non-rooted modern Android OS.

**Comment by azevedogustavo** [comment]
> > No MAC address found. Falling back to generic UUID.
> 
> Expected behavior on non-rooted modern Android OS.

Install net-tools
apt install net-tools
