### ISSUE TITLE
Package request: d8

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#4927]
Android has a newer dex compiler called d8, it performs some desugaring on the bytecode which allows us to use more of Java 8+ features on Android.

It should be available on the sdk build tools path, there's no direct download link however.

**Comment by hnmn** [comment]
Why `d8` is in disabled packages ?
What's problem with `d8`?
@pollen5 how you install d8 can you explain?

**Comment by pollen5** [comment]
@hnmn I got a friend to download the jar in the link above and use it to dex the jar itself and he sent it to me then I ran it with dalvikvm

**Comment by Ratul-Learner** [comment]
> I asked a friend that has a computer to dex d8 for me and it's working great, found a lambda mock package so now ecj can also compile lambdas properly and d8 desugars it, i can enjoy full java 8 support now, would be nice if d8 also gets added and updated by termux

Can you please upload d8.dex in a cloud storage like mediafire or mega.nz and share the link please. I will be very thankful.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install d8
```

**Comment by CypherpunkSamurai** [comment]
@ravener Offtopic, but what commands did he run to dex the jar itself?

**Comment by ravener** [comment]
@CypherpunkSamura I gave him the following command ```sh
java -jar d8.jar --release --lib android.jar --min-api 28 --output d8.dex.jar d8.jar
```
For android.jar I linked https://dl.google.com/android/repository/platform-28_r06.zip to him

**Comment by CypherpunkSamurai** [comment]
@ravener Thanks I'll try that :)

also, can I use this for min api 19 or 24? I want the generated dex to be compatible on Kitkat or atleast Mashmello devices. Or atleast on my Nougat device.

I tried the latest d8 versions but getting desugar errors. Even adding `android.jar` and java home as `--lib` doesn't solve it :(

also do you have a discord? I'f you dont mind I'd not wanna spam this issue :P

What do you say?
(or maybe we should talk here for future visitors?).

**Comment by ravener** [comment]
> @ravener Thanks I'll try that :)
> 
> also, can I use this for min api 19 or 24? I want the generated dex to be compatible on Kitkat or atleast Mashmello devices. Or atleast on my Nougat device.

Probably I have no idea about the minimum requirements, I simply passed 28 because that's what I have.

> also do you have a discord? I'f you dont mind I'd not wanna spam this issue :P

Sure, Ravener#5796 or also on the Termux discord server.

**Comment by CypherpunkSamurai** [comment]
@ravener Thank you. I'll join soon.

**Comment by CypherpunkSamurai** [comment]
@ravener If you don't mind.

I made this [repl](https://replit.com/@CypherSamurai/d8dexer#download.sh) trying to dex d8 to api 19 (kitkat) as you can see there's errors when running it. Are we supposed to include some other java support libraries? AFAIK Java 9 support requires desugaring for lower versions.
