### ISSUE TITLE
Package request: GNU libjit

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#4928]
LibJIT is a library for writing generic just-in-time compilers.

Website: https://www.gnu.org/software/libjit/

I've tried compiling libjit along with lightning but failed but you guys seem to be good at compiling GNU packages so it will be nice to have these packages.

**Comment by xtkoba** [comment]
Unbuildable due to Clang/LLVM lacking `__builtin_apply{,_args}`.

LLVM has its own JIT framework.

I would say it has an extremely low priority to package this, if not labeled as "wontfix".

**Comment by ravener** [comment]
Understandable, honestly though, I have no need for this package anymore.
