### ISSUE TITLE
apt install ffmpeg leads to a 404 error

### ISSUE THREAD

**Issue by boddhissattva** [termux/termux-packages#493]
$ apt install ffmpeg
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libbz2 libopus libx264 xvidcore
The following NEW packages will be installed:
  ffmpeg libbz2 libopus libx264 xvidcore
0 upgraded, 5 newly installed, 0 to remove and 2 not upgraded.
Need to get 5595 kB/6094 kB of archives.
After this operation, 19.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] Err:1 http://termux.net stable/main arm ffmpeg arm 3.1.3-1
  404  Not Found [IP: 104.18.36.234 80]

**Comment by Neo-Oli** [comment]
Your package index is out of date. Run `apt update` to refresh it. after that you can `apt install ffmpeg` again.

**Comment by boddhissattva** [comment]
Indeed, it wasn't updated. I have installed Termux recently so that I didn't thought it was an update problem. Please apology for the inconveniance
