### ISSUE TITLE
Static libraries for -ldl -lpthread -lc

### ISSUE THREAD

**Issue by umarcor** [termux/termux-packages#4930]
While trying to build https://github.com/umarcor/mambo/tree/termux-gist, I found it complaining because `-ldl -lelf -lpthread -lc` could not be found. Since the tool is being statically compiled, it makes sense. However, I found `libelf-static` only. I could not find packages to install static versions for `-ldl`, `-lpthread` and/or `-lc`. Are these available? If not, is it possible to have them added?

Ref #4028

**Comment by xeffyr** [comment]
You can obtain them from package `ndk-multilib`. Note that static version of Bionic libc is generic and is not guaranteed to work with your Android OS version.

**Comment by umarcor** [comment]
> You can obtain them from package `ndk-multilib`. Note that static version of Bionic libc is generic and is not guaranteed to work with your Android OS version.

Thanks! That fixed the issue with `-ldl` and `-lc`. However, `-lpthread` is still not found. I created an empty lib with `ar cr libpthread.a` (https://stackoverflow.com/questions/57289494/ndk-r20-ld-ld-error-cannot-find-lpthread) and that let me build the tool. It produces a Segmentation fault, but I guess that's a different issue.

> Termux by itself uses libc/libdl provided in /system/lib(64).

Should I use these instead of the ones provided by `ndk-multilib`?

**Comment by Grimler91** [comment]
@umarcor the pthread functions are included in android's libc so you don't need `-lpthread`, just remove the flag.

**Comment by Saikatsaha1996** [comment]
Please help me
I got error
How can I slove
Please help 🙏😑
![Screenshot_2021-05-20-00-55-16-423_com termux-1](https://user-images.githubusercontent.com/72664192/122027620-e6031300-cde8-11eb-9431-82471f90b84b.jpg)
