### ISSUE TITLE
Add Beef Framework

### ISSUE THREAD

**Issue by aniketstark** [termux/termux-packages#4931]
Now days Metasploit Framework was available in unstable-repo
So can you please add Beef Framework in Termux Unstable-Repo
https://github.com/Hax4us/termux-tools/blob/master/README.md
This guy who ported beef Framework for termux

**Comment by xeffyr** [comment]
This will not be ported.

**Comment by xeffyr** [comment]
Duplicate of:
* https://github.com/termux/termux-packages/issues/4931
* https://github.com/termux/termux-packages/issues/4450
* https://github.com/termux/termux-packages/issues/3393
