### ISSUE TITLE
jo package request

### ISSUE THREAD

**Issue by badsmoke** [termux/termux-packages#4933]
**Package description**

This is jo, a small utility to create JSON objects

```
$ jo -p name=jo n=17 parser=false
{
    "name": "jo",
    "n": 17,
    "parser": false
}
or arrays

$ seq 1 10 | jo -a
[1,2,3,4,5,6,7,8,9,10]
```
**Link to home page and sources**
1. https://github.com/jpmens/jo
2. https://github.com/jpmens/jo

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did work then please share any patches that you had to apply.

compile is no problem

tar xvzf jo-1.3.tar.gz
cd jo-1.3
./configure --prefix=/data/data/com.termux/files/usr/bin
make check
make install

because there is no /usr folder in termux i only had to change the prefix

**Comment by xploitednoob** [comment]
package has been added. please close this issue.
https://github.com/termux/termux-packages/pull/4977
@xeffyr
