### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by Sasi-007** [termux/termux-packages#4934]
$ pip
No command pip found, did you mean:
 Command php in package php
 Command pil in package picolisp
 Command ip in package termux-tools
 Command zip in package zip

It showing error like this when we enter pip....

**Comment by xeffyr** [comment]
Because you don't have package `python` installed.

**Comment by mishraanuj205** [comment]
![Screenshot_2020-12-02-18-42-38-33](https://user-images.githubusercontent.com/44110170/100877014-34e0ff00-34ce-11eb-9a68-0231b88625db.png)

I have installed pip but its showing same problem

**Comment by WMCB-Tech** [comment]
Execute only `pip` command without `python`

**Comment by xeffyr** [comment]
@mishraanuj205 I see lots of issues on your screenshot.

1. Your bash.bashrc is messed up.
2. You attempting to install package as root.
3. Invalid command line syntax. (`python pip install ...`) - should be `pip install <package name>`.
4. `lolcat` is a Ruby package, so `gem install lolcat`. (@WMCB-Tech)

***

Do not bring up old issues, especially if your comment is basically offtopic.
