### ISSUE TITLE
It is very buggy.

### ISSUE THREAD

**Issue by StudioSSDD** [termux/termux-packages#4937]
When I write any command like cd /sdcard/download or any other 
When I write cd than it don't show anything written when I tap spacebar than it shows written char. Or any special scars or no.s are shown correctly Ik I'm not clear pls see the vid link below.
[See my unlisted YT vid. Pls](https://youtu.be/0oCnk1RK4fs)

**Comment by Grimler91** [comment]
Sounds like this issue with some samsung devices https://github.com/termux/termux-app/issues/686
