### ISSUE TITLE
command 'arm-linux-androideabi-clang' failed with exit status 1

### ISSUE THREAD

**Issue by ryan-byte** [termux/termux-packages#4938]
I'm trying to install sslstrip using 

> $pip install sslstrip

But I'm getting this error 
`error: command 'arm-linux-androideabi-clang' failed with exit status 1`
This is a screenshot of the issue 

![received_210301093699272](https://user-images.githubusercontent.com/52682606/74958618-8588df00-5409-11ea-9b56-619c56afbb3c.jpeg)
![received_223246168807904](https://user-images.githubusercontent.com/52682606/74958652-920d3780-5409-11ea-82bb-091c1e11579a.jpeg)
![received_3205184169509699](https://user-images.githubusercontent.com/52682606/74958693-9fc2bd00-5409-11ea-9e6a-46cbafe417a0.jpeg)

**Comment by fornwall** [comment]
Hello and thanks for reporting the issue!

It seems that sslstrip doesn't work with the current versions of OpenSSL which Termux usese. You need to take that up with the maintainer of sslstrip or find a more modern replacement.
