### ISSUE TITLE
compatibility with grml-zshrc for zsh

### ISSUE THREAD

**Issue by jensMF** [termux/termux-packages#494]
Hey there,

it would be really great, if the compatibility for the grml-zshrc [http://git.grml.org/?p=grml-etc-core.git;a=blob_plain;f=etc/zsh/zshrc;hb=HEAD](url) (more info: [https://grml.org/zsh/](url)) would be perfect.
At the moment I get these errors:
```
no deltochar available
no mathfunc available
```

thanks in advance :)

**Comment by fornwall** [comment]
Thanks - the `deltochar` and `mathfunc` modules are now available in the updated zsh package.

Install it with `apt update && apt upgrade`.

**Comment by jensMF** [comment]
Works great, thank you again!  :-)
