### ISSUE TITLE
texlive-tlmgr and its conflicts

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#4945]
Maybe I am wrong but it seems to remember that installing `texlive-tlmgr` after `texlive full` removes many TL packages because they conflicts with `texlive-tlmgr`. Meanwhile, waiting Biber I did a reset of Termux and did not reinstall any TL (waiting also to know if TL can be installed from local repo)

Now I just noticed that `pkg install texlive-full` prints:

```
[...]
Recommended packages:
  xorg-xauth texlive-tlmgr
[...]
```

this seems to contradict the previous conflict. Or not?

**Comment by Grimler91** [comment]
`texlive-full` conflicts with `texlive-tlmgr` (both packages provide texlive.tlpdb). Installing texlive-tlmgr removes texlive-full and you get an info message that you have packages (all texlive-* packages, dependencies of texlive-full) that were automatically installed. It shouldn't remove any packages except texlive-full. 

texlive-tlmgr is a recommended package for texlive, so it is listed as recommended package when installing texlive-full (but it won't be installed)

**Comment by angelog0** [comment]
@Grimler91 wrote:

> Installing texlive-tlmgr removes texlive-full [...]
> texlive-tlmgr is a recommended package for texlive, so it is listed as recommended package when installing texlive-full (but it won't be installed)

Sorry, but I find this contradictory and confusing... Anyway, thanks.
