### ISSUE TITLE
Backup /home after update that ruins all

### ISSUE THREAD

**Issue by Flashwalker** [termux/termux-packages#4946]
I recently broke my installation while just trying to upgrade packages. 

It's all about this: [#4129 update that ruins all](https://github.com/termux/termux-packages/issues/4129)  

I have no busybox now so how can i backup at least the /home in non rooted phone?

**Comment by xeffyr** [comment]
Open failsafe shell and `cp` or `mv` necessary files to `/sdcard/`. You can also check if `/system/bin/tar` is available in your ROM, so you can archive whole `$HOME`.

https://wiki.termux.com/wiki/Recover_a_broken_environment#Launching_a_Failsafe_Session

**Comment by Flashwalker** [comment]
Something wrong:
'ls: storage/shared/: Permission denied'

**Comment by xeffyr** [comment]
Enable storage permission for Termux app through Android settings.
