### ISSUE TITLE
golang on ChromeOs: go tool crashes with panic on system stack 

### ISSUE THREAD

**Issue by philips** [termux/termux-packages#496]
Version 54.0.2840.51 beta
Platform 8743.57.0 (Official Build) beta-channel veyron_minnie
ARC Version 3327608
Firmware Google_Veyron_Minnie.6588.197.0

golang/stable,now 2:1.7.1 arm [installed]

```
$ go
panic: nil
fatal error: panic on system stack
runtime: panic before malloc heap initialized

runtime stack:
fatal error: gentraceback before goexitPC initialization
runtime: panic before malloc heap initialized
panic during panic

runtime stack:
fatal error: gentraceback before goexitPC initialization
runtime: panic before malloc heap initialized
stack trace unavailable
$
```

**Comment by fornwall** [comment]
Seems to be ChromeOS-specific, I need to get a chromebook to test things.

**Comment by marineam** [comment]
There appears to be a seccomp filter blocking `sched_getaffinity` of all things and the go runtime assumes that syscall cannot fail in `runtime.getproccount`. strace reveals:

    sched_getaffinity(0, 8192, 0xbedf1c74) = -1 ENOSYS (Function not implemented)

And from `src/runtime/os_linux.go`:
```go
func getproccount() int32 {
        // This buffer is huge (8 kB) but we are on the system stack
        // and there should be plenty of space (64 kB).
        // Also this is a leaf, so we're not holding up the memory for long.
        // See golang.org/issue/11823.
        // The suggested behavior here is to keep trying with ever-larger
        // buffers, but we don't have a dynamic memory allocator at the
        // moment, so that's a bit tricky and seems like overkill.
        const maxCPUs = 64 * 1024
        var buf [maxCPUs / (sys.PtrSize * 8)]uintptr
        r := sched_getaffinity(0, unsafe.Sizeof(buf), &buf[0])
        n := int32(0)
        for _, v := range buf[:r/sys.PtrSize] {
                for v != 0 {
                        n += int32(v & 1)
                        v >>= 1
                }
        }
        if n == 0 {
                n = 1
        }
        return n
}
```

So indexing a slice by `-errno / sys.PtrSize` is not going to work out very well.

**Comment by marineam** [comment]
Upstream: https://go-review.googlesource.com/#/c/34794/

**Comment by fornwall** [comment]
@marineam Great, nice find!

The updated version `1.7.4-1` of the golang which contains the fix is now available as an update:

    apt update && apt upgrade
