### ISSUE TITLE
PHPredis

### ISSUE THREAD

**Issue by Kleinschmidts** [termux/termux-packages#4961]
The phpredis extension provides an API for communicating with the Redis key-value store.
Would be nice to have it available with php.
The redis server itself is fine and running:

    pkg list-all |grep -i redis
    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    redis/stable,now 5.0.7-1 arm [installed]

I am on Android 7.1.2 Lineagos.

https://github.com/phpredis/phpredis

I managed to compile it myself, but it seems not to be working ok.

    Android version:
    7.1.2
    Kernel build information:
    Linux localhost 3.4.112-Lineage-ge8d93e0 #1 SMP PREEMPT Sat Jan 12 14:54:25 UTC 2019 armv7l Android

**Comment by Kleinschmidts** [comment]
I just again compiled phpredis on the device, and this time it seems to work fine.

    wget https://github.com/phpredis/phpredis/archive/master.zip -O phpredis.zip
    unzip -o phpredis.zip
    mv phpredis-master phpredis
    cd phpredis
    phpize
    ./configure
    make
    make test
    cd modules/
    cp redis.so /data/data/com.termux/files/usr/lib/php

Add extension=redis.so in php.ini. Ready to go.
So the package request can be considered as low prio.
Thank you very much, again a quite noticeable performance improvement.

**Comment by xeffyr** [comment]
Package is available.

You can obtain it with these commands:
```
pkg install php-redis
```
