### ISSUE TITLE
Keyboard not showing on some applications

### ISSUE THREAD

**Issue by Ziggoto** [termux/termux-packages#497]
Some applications like htop needs to be controlled with keyboard but no keyboard button is shown when this application is open.

**Comment by tigran123** [comment]
You probably pressed Back and the keyboard disappeared. First of all, in htop you can perform many operations (that do not require typing some text) using mouse, i.e. using your fingers.

However, if you do really want the keyboard back just touch "Home" button and then touch Termux icon on your Home. It will switch back to Termux with the keyboard shown.

**Comment by fornwall** [comment]
@Ziggoto The easiest way to get the keyboard back is to use drawer (draw your finger in from the left) and press the keyboard button.
