### ISSUE TITLE
Package Request: SVGAlib

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [termux/termux-packages#4971]
**Package description**
graphics library. Pre-req of links browser with graphics enabled.

**Link to home page and sources**
1. Home page:  https://www.svgalib.org/
2. Source code:  https://www.svgalib.org/svgalib-1.4.3.tar.gz

**Additional information**
Have not tried to compile. Prereq for `links` browser with graphics enabled. Also allows numerous other package possibilities.

**Comment by xeffyr** [comment]
1. Links already has graphics mode enabled.
2. This package will not be added - Termux doesn't have VGA device. Don't forget that this app is just a terminal.
