### ISSUE TITLE
Package Request: GPM

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [termux/termux-packages#4972]
**Package description**
gpm - general purpose mouse
(allows mouse to function in framebuffer)

**Link to home page and sources**
1. Home page:  https://www.nico.schottelius.org/software/gpm/
2. Source code:  git://git.schottelius.org/gpm

**Additional information**
Have not tried to compile. Possibly not needed or desirable in Termux due to termux's built-in touch and gesture support emulating mouse ?

**Comment by xeffyr** [comment]
Closing as Termux doesn't have/use framebuffer.
