### ISSUE TITLE
(re)Package Request: links browser with --enable-graphics

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [termux/termux-packages#4973]
**Package description**
Re-package `links` browser with graphics support. Debian [packages](https://packages.debian.org/search?keywords=links2) `links2` with graphics support by default. Why doesn't Termux?

New build pre-reqs (links are to Termux-packages already in repo):
- [libpng](https://github.com/termux/termux-packages/tree/master/packages/libpng)
- [libtiff](https://github.com/termux/termux-packages/tree/master/packages/libtiff)
- svgalib (#4971)
- Xfree86 (Xorg? some implementation of Xlib)
- GPM (#4972) -- possibly not needed due to Termux's in-built touch mouse emulation

`./configure --enable-graphics`

enables optional `-g` runtime flag to enable graphics support.

**Link to home page and sources**
1. Home page:  http://links.twibright.com/
2. Build instructions:  http://links.twibright.com/download.php
3. Source code:  http://links.twibright.com/download/links-2.20.2.tar.gz

**Additional information**

I have not tried to compile it myself; yet. There is already a `links` package in the repositories. However, it is not built with graphical capability, whether X or framebuffer.

**Comment by xeffyr** [comment]
Done in https://github.com/termux/termux-packages/commit/893efbfdd0e6eda394ee1181255b9865f2023e95. Updated package will be available shortly.
