### ISSUE TITLE
Add new package request: xmake

### ISSUE THREAD

**Issue by waruqi** [termux/termux-packages#4974]
**Package description**

**Link to home page and sources**
1. Home page: https://xmake.io
2. Source code: https://github.com/xmake-io/xmake

**Additional information**
Have you compiled or tried to compile the package on device?

Yes, It has been compiled and works on device manually.

```console
$ cd xmake
$ make build
$ make install
```

* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by xploitednoob** [comment]
@waruqi can you please add error log

**Comment by waruqi** [comment]
> @waruqi can you please add error log

error log? Now xmake can compile and run normally on termux, and there is no error log.

**Comment by xploitednoob** [comment]
@waruqi got some error after installation
```
xploitednoob@termux [~]: xmake
error: /data/data/com.termux/files/usr/share/xmake/core/_xmake_main.lua: cannot load incompatible bytecode
```

**Comment by waruqi** [comment]
> @waruqi got some error after installation
> 
> ```
> xploitednoob@termux [~]: xmake
> error: /data/data/com.termux/files/usr/share/xmake/core/_xmake_main.lua: cannot load incompatible bytecode
> ```

Can you let me see the your installation command? only `cd xmake; make build; make install`?

**Comment by xploitednoob** [comment]
> > @waruqi got some error after installation
> > ```
> > xploitednoob@termux [~]: xmake
> > error: /data/data/com.termux/files/usr/share/xmake/core/_xmake_main.lua: cannot load incompatible bytecode
> > ```
> 
> Can you let me see the your installation command? only `cd xmake; make build; make install`?

```
mkdir xmake
wget https://github.com/xmake-io/xmake/releases/download/v2.3.1/xmake-v2.3.1.tar.gz
tar xvf xmake-*.gz
make build
make install
```

**Comment by waruqi** [comment]
It was because of a problem with the zip/tar.gz file I provided. Please wait for a while, I will update and fix them(zip/tar.gz) tomorrow.

**Comment by xploitednoob** [comment]
> It was because of a problem with the zip/tar.gz file I provided. Please wait for a while, I will update and fix them(zip/tar.gz) in these days.

can you specify the dependencies it needs to run

**Comment by waruqi** [comment]
> > It was because of a problem with the zip/tar.gz file I provided. Please wait for a while, I will update and fix them(zip/tar.gz) in these days.
> 
> can you specify the dependencies it needs to run

gcc, make, libreadline (optional)

**Comment by xploitednoob** [comment]
@waruqi you github code has problem. you included luajit.h on core/lcurses/lcurses.c
when i tried to make it can't find that header.

```
make xmake
make lcurses
compile.r lcurses.c
make[3]: *** [/data/data/com.termux/files/home/devel/xmake/core/suffix.mak:303: lcurses.o] Error 1
make[2]: *** [/data/data/com.termux/files/home/devel/xmake/core/suffix.mak:305: DEP_PROS_lcurses_all] Error 2
lcurses.c:68:10: fatal error: 'luajit.h' file not found
#include "luajit.h"
         ^~~~~~~~~~
1 error generated.
```

**Comment by waruqi** [comment]
> @waruqi you github code has problem. you included luajit.h on core/lcurses/lcurses.c
> when i tried to make it can't find that header.
> 
> ```
> make xmake
> make lcurses
> compile.r lcurses.c
> make[3]: *** [/data/data/com.termux/files/home/devel/xmake/core/suffix.mak:303: lcurses.o] Error 1
> make[2]: *** [/data/data/com.termux/files/home/devel/xmake/core/suffix.mak:305: DEP_PROS_lcurses_all] Error 2
> lcurses.c:68:10: fatal error: 'luajit.h' file not found
> #include "luajit.h"
>          ^~~~~~~~~~
> 1 error generated.
> ```

you need run 
```
git submodule update --init
```

the archive tar.gz will contain these module codes.

**Comment by waruqi** [comment]
I have update https://github.com/xmake-io/xmake/releases/download/v2.3.1/xmake-v2.3.1.tar.gz , you try it again.

**Comment by waruqi** [comment]
The new archive tar.gz is ok? @xploitednoob 

If it works, I need to update the it's shasum in other package repositories.

**Comment by xploitednoob** [comment]
> The new archive tar.gz is ok? @xploitednoob
> 
> If it works, I need to update it's shasum in other package repositories.

wait let me check

**Comment by waruqi** [comment]
ok

**Comment by xploitednoob** [comment]
> ok

Everything Is Okk. But Have To Add Some Patch. On Device Build Works. But Termux Docker Image Build Gives Binary  Error. Trying To Build Package Again. For Testing

Build That Has Binary Error: https://github.com/xploitednoob/termux-pentest/actions/runs/46074560

Build That Has Some Patches: https://github.com/xploitednoob/termux-pentest/actions/runs/46094189

**Comment by waruqi** [comment]
> > ok
> 
> Everything Is Okk. But Have To Add Some Patch. On Device Build Works. But Termux Docker Image Build Gives Binary Error. Trying To Build Package Again For Testing
> 
> Build That Has Binary Error: https://github.com/xploitednoob/termux-pentest/actions/runs/46074560

what error and patch? I have not seen any errors.

btw, xmake need not cmake, automake deps.

**Comment by xploitednoob** [comment]
@waruqi build was successful but it has an error.
```
arm-linux-androideabi-strip:./bin/xmake: File format not recognized
```
>btw, xmake need not cmake, automake deps.

and i just added them when the package is ready i will create a fresh pull requests and remove the extra dependencies.

here is the builded version of xmake for termux
arm: https://dl.bintray.com/xploitednoob/termux-pentest/arm/:xmake_2.3.1_aarch64.deb
aarch64: https://dl.bintray.com/xploitednoob/termux-pentest/aarch64/:xmake_2.3.1_aarch64.deb

install one of them and try to run `xmake`

**Comment by xeffyr** [comment]
@xploitednoob Your build is for Linux x86_64, not for Termux.
```
compile:
    plat:		linux
    arch:		x86_64
    host:		linux
    demo:		y
    prof:		n
    debug:		n
    small:		n
    ccache:		
    distcc:		
```

**Comment by waruqi** [comment]
It seems that the wrong arch is detected on ci, but it is ok on the device.

I uses `uname -m` to detect arch.

**Comment by xploitednoob** [comment]
> It seems that the wrong arch is detected on ci, but it is ok on the device.
> 
> I uses `uname -m` to detect arch.
> 
> ```
> ifeq ($(PLAT),linux)
> ARCHSTR 	:= $(shell uname -m)
> ARCH 		:= $(if $(findstring aarch64,$(ARCHSTR)),arm64,$(ARCH))
> ARCH 		:= $(if $(findstring arm64,$(ARCHSTR)),arm64,$(ARCH))
> ARCH 		:= $(if $(findstring armv7,$(ARCHSTR)),armv7,$(ARCH))
> ARCH 		:= $(if $(findstring arm,$(ARCHSTR)),arm,$(ARCH))
> endif
> ```

I Am Also Checking This Codes. Need Some Patches. So That It Detects The Correct Arch On CI. @xeffyr any ideas

**Comment by waruqi** [comment]
Is there an environment variable that can detect a valid arch?

**Comment by waruqi** [comment]
And I need also modify CC/AR/LD to arm-linux-androideabi-xx and aarch64-linux-android-xx for aarch64/arm

**Comment by waruqi** [comment]
I have restored xmake-v2.3.1.tar.gz and upload https://github.com/xmake-io/xmake/releases/download/v2.3.1/xmake-v2.3.1-termux_test.tar.gz for testing.

And I will try fix tar archive to support build xmake on termux/ci in these days.

**Comment by xploitednoob** [comment]
> I have restored xmake-v2.3.1.tar.gz and upload https://github.com/xmake-io/xmake/releases/download/v2.3.1/xmake-v2.3.1-termux_test.tar.gz for testing.
> 
> And I will try fix tar archive to support build xmake on termux/ci in these days.

Have You Made Any Changes????

**Comment by waruqi** [comment]
> > I have restored xmake-v2.3.1.tar.gz and upload https://github.com/xmake-io/xmake/releases/download/v2.3.1/xmake-v2.3.1-termux_test.tar.gz for testing.
> > And I will try fix tar archive to support build xmake on termux/ci in these days.
> 
> Have You Made Any Changes????

Please modify tar url to xmake-v2.3.1-termux_test.tar.gz, because other package repositories are using xmake-v2.3.1.tar.gz. This will affect the hash of the original package.

```
TERMUX_PKG_SRCURL=https://github.com/xmake-io/xmake/releases/download/v${TERMUX_PKG_VERSION}/xmake-v${TERMUX_PKG_VERSION}-termux_test.tar.gz
TERMUX_PKG_SHA256=9b42a9703e687fb2bdf199f5c69a177fc79cdcca9daae03cea546889a4a2b02c
```

**Comment by waruqi** [comment]
I printed all envs on termux/ci and I will improve makefile to support it. we can use $TERMUX_ARCH to detect correct arch.

```
  CCTERMUX_HOST_PLATFORM = "aarch64-linux-android24", 
  CC = "aarch64-linux-android-clang",
  CPP = "aarch64-linux-android-cpp",
  CFLAGS = "-fstack-protector-strong -Oz",
  ac_cv_func_sigsetmask = "no",
  PWD = "/home/builder/.termux-build/xmake/src",
  AS = "aarch64-linux-android-clang",
  TERMUX_ARCH = "aarch64",
  LDFLAGS = "-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now",
```

**Comment by waruqi** [comment]
@xploitednoob I have fixed compile problems on termux/ci. You can see https://github.com/waruqi/termux-pentest/runs/473957586?check_suite_focus=true

```
TERMUX_PKG_HOMEPAGE=http://xmake.io/
TERMUX_PKG_DESCRIPTION="A cross-platform build utility based on Lua"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="Rabby Sheikh @xploitednoob"
TERMUX_PKG_VERSION=2.3.1
TERMUX_PKG_REVISION=11
TERMUX_PKG_SRCURL=https://github.com/xmake-io/xmake/releases/download/v${TERMUX_PKG_VERSION}/xmake-v${TERMUX_PKG_VERSION}-termux_test2.tar.gz
TERMUX_PKG_SHA256=a74b3263c57f9d2b325800ff94f17371ffd8c3ab737617e5d32a9434b84be0c5
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="clang, make, readline"

termux_step_make() {
	make build
}
termux_step_make_install() {
	make install PREFIX="${TERMUX_PREFIX}"
}
```

btw, xmake use Apache-2.0 for license/TERMUX_PKG_LICENSE

**Comment by waruqi** [comment]
I have opened a pr for xmake. https://github.com/termux/termux-packages/pull/4982 

If it works on ci, I will update original tar archive.

**Comment by waruqi** [comment]
Seems everything works, I have updated the original package.

**Comment by waruqi** [comment]
this pr has been merged. https://github.com/termux/termux-packages/pull/4982

Thanks @xploitednoob :smile:
