### ISSUE TITLE
metasploit framework

### ISSUE THREAD

**Issue by i-am-aakash** [termux/termux-packages#4975]
I am unable to install metasploit framework on my android.
It is showing error "Failed writing recceived data to disk/application"

**Comment by xeffyr** [comment]
> It is showing error "Failed writing recceived data to disk/application"

This error literally contains zero information about real problem.

* Output of `termux-info`
* How you are installing metasploit ?
* Full console log during installation.

**Comment by i-am-aakash** [comment]
I was trying to get metasploit framework on my device using curl command
with a url but after hitting enter it gives the error as mentioned in the
previous message.

**Comment by xploitednoob** [comment]
@i-am-aakash please add full log and additional information.

**Comment by i-am-aakash** [comment]
This is what it is showing when I am trying to get metasploit framework.

**Comment by xploitednoob** [comment]
> This is what it is showing when I am trying to get metasploit framework.

where is the error log????

**Comment by i-am-aakash** [comment]
App is failing to write the recieved data on disk.

**Comment by kcubeterm** [comment]
Why not you just install it by termux repo,
```
pkg install unstable-repo
pkg install metasploit
```

**Comment by xploitednoob** [comment]
> App is failing to write the recieved data on disk.

You Might Don't Have The Write Permission. are you trying to install it manually or using pkg manager

Termux Already Has Metasploit On Unstable-Repo:
```
pkg up -y
pkg install unstable-repo
pkg install metasploit
```

**Comment by xploitednoob** [comment]
@i-am-aakash i think your problem is fixed

**Comment by i-am-aakash** [comment]
I will try the solution given by you...
And if there will be any querry then I will inform you...
For now thanks for your help..
