### ISSUE TITLE
'Cannot locate symbol "lzma_stream_decoder"' in MPV

### ISSUE THREAD

**Issue by tinydynamite00** [termux/termux-packages#498]
#498 
@fornwall `mpv` stopped working completely on an N6. I get _Cannot Link Executable_ upon launching the media player. Uninstall/reinstall `mpv` + `ffmpeg` doesn't help. I've 6.0.1 currently on G2 with `mpv` playing audio but between tracks the following error:
> [ao/opensles] Failed to Enqueue: 7

Could this be an issue with the recent update to `ffmpeg` or the OpenAL API? 
Attached is a terminal transcript from an `strace` immediately after `mpv` aborted and a file referencing the lzma lib error.

[20161010_MPV_lzma-stream-decoder-not-found.txt](https://github.com/termux/termux-packages/files/521029/20161010_MPV_lzma-stream-decoder-not-found.txt)

[20161010_strace-mpv-tXscript.txt](https://github.com/termux/termux-packages/files/521030/20161010_strace-mpv-tXscript.txt)

**Comment by fornwall** [comment]
The linker picks up `/system/lib(64(/liblzma.so` on devices having that library, and the `lzma_stream_decoder` doesn't seem to be available there.

The root problem is that `mpv` needs to link against `libOpenSLES.so` which in turn is linked against `libwilhelm.so` - and so it continues. And the Android linker does not support rpath.

**Comment by tinydynamite00** [comment]
I did notice `$PATH` you mention in the stack trace. Also looks like `selinux context` rejects/checks the linker several times if I'm reading that right. Wondering if this is native to source code of 7.0 as media was quite good on 6.0.1, Nexus 6 - custom builds mainly. 

I should note I'm running stock Nougat; systemless root; selinux=enforcing. (Could the linker issue - in part - be caused by the boot image hackery of this root method on 7.0? Maybe different behaviour from a custom kernel?)   
Will flash custom ROM later today; curious to see whether this software glitch persists short a pinch or two of Alphabet's proprietary blobs. Meanwhile, `play-audio` is a worthy replacement! 

I move to close #498 based on the system `.so` foo interference to which, as you say, some devices are prone. Will comment if a custom ROM affects any change.
