### ISSUE TITLE
Git delta

### ISSUE THREAD

**Issue by luisdavim** [termux/termux-packages#4991]
**Package description**

A syntax-highlighter for git and diff output.
It's written in Rust and they already provide arm builds.

**Link to home page and sources**
1. Home page: https://github.com/dandavison/delta
2. Source code: https://github.com/dandavison/delta

**Additional information**
I haven't tried yet but the github releases include arm builds.
There's also a cargo package https://crates.io/crates/git-delta

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install git-delta
```
