### ISSUE TITLE
[Package Request] bgrep

### ISSUE THREAD

**Issue by 5p0ng3b0b** [termux/termux-packages#4992]
**Package description**
bgrep is a grep for binary files

**Link to home page and sources**
1. Home page: https://github.com/tmbinc/bgrep
2. Source code: https://github.com/tmbinc/bgrep

**Additional information**
Compiled and installed with just one line of code!
`
curl -L 'https://github.com/tmbinc/bgrep/raw/master/bgrep.c' | gcc -O2 -x c -o $PREFIX/bin/bgrep -
`

**Comment by landfillbaby** [comment]
the original implementation is very buggy and barebones.
i think maybe we should use [mspkg's fork](https://github.com/mspkg/bgrep) or [bgrep2](https://github.com/udoprog/bgrep2)

**Comment by xeffyr** [comment]
https://github.com/mspkg/bgrep is an exact copy of https://github.com/rsharo/bgrep, so rsharo/bgrep will be used as new upstream.

**Comment by 5p0ng3b0b** [comment]
> the original implementation is very buggy and barebones.
> i think maybe we should use [rsharo's fork](https://github.com/rsharo/bgrep) or [bgrep2](https://github.com/udoprog/bgrep2)

bgrep2 then. The more functionality the better.
