### ISSUE TITLE
Pup

### ISSUE THREAD

**Issue by taylorwin** [termux/termux-packages#4995]
**Package description**
pup is a command line tool for processing HTML. It reads from stdin, prints to stdout, and allows the user to filter parts of the page using CSS selectors.
Inspired by jq, pup aims to be a fast and flexible way of exploring HTML from the terminal.
**Link to home page and sources**
1. https://github.com/ericchiang/pup
**Additional information**
I want to crawl the html and process the data.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install pup
```
