### ISSUE TITLE
Device's trying to rule with its system apps 

### ISSUE THREAD

**Issue by Judje34** [termux/termux-packages#4999]
$ *Root:pkg must install because system is trying 
to rule this device-important
*Root:pkg: command not found
$ *Root:pkg-is it possible?
*Root:pkg-is: command not found
$ *

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```$ *Root:pkg must install because system is trying 
to rule this device-important
*Root:pkg: command not found
$ *Root:pkg-is it possible?
*Root:pkg-is: command not found
$ *

```

**Comment by Judje34** [comment]
Does anyone out there able to explain me how to stop my Android vandetta, it rules every settings, change my decisions, system applications are impossible to stop and continue running their data collect, loading all the time, even when i stop them, and no way to find a trick to root this dirty HUAWEI Y6 2018 i am obligated to work with.
PLEASE, IF YOU KNOW A GOOD SOLUTION, LET ME KNOW... I'M OUTTA MYSELF!!!

**Comment by Judje34** [comment]
I have TERMUX now, but i can't get any manual to learn how it works, so if someone could help me out, I'll be very grateful and happy to help this person out...

**Comment by xeffyr** [comment]
We generally don't care about what is happening on your device...
