### ISSUE TITLE
LuaJIT package is incomplete (missing files)

### ISSUE THREAD

**Issue by sfzhi** [termux/termux-packages#5]
"luajit -b" does not work (produces an error message). It expects several *.lua files in $PREFIX/share/luajit-2.0.4/jit/, which are not installed. If I copy those files from another system manually, the broken functionality is restored. So it's probably just a matter of including the missing files into the luajit package.

**Comment by fornwall** [comment]
Thanks for the detailed explanation! Fixed in the luajit 2.0.4-1 package available from the apt repo now.
