### ISSUE TITLE
Ngrok

### ISSUE THREAD

**Issue by She-eng** [termux/termux-packages#5007]
Guys give me command line for pre connect to  TCP tunnel that I connected before.
I opened the ngrok docs but I didn't understand anything 😅

**Comment by xeffyr** [comment]
This is Termux packages bug tracker. Ngrok is not Termux package (and never be, as closed source & non-free) and thus **offtopic**.

Ngrok docs are quite clear. If you don't know how to run server, Ngrok is probably not for you...
