### ISSUE TITLE
libx265/stable 3.3 broke ffmpeg

### ISSUE THREAD

**Issue by null0nil** [termux/termux-packages#5008]
$ ffmpeg
CANNOT LINK EXECUTABLE "ffmpeg": cannot locate symbol "x265_api_get_179" referenced by "/data/data/com.termux/files/usr/lib/libavcodec.so"...

**Comment by xeffyr** [comment]
`pkg upgrade` and try again.

**Comment by null0nil** [comment]
It's working again.  Thanks!
