### ISSUE TITLE
/usr/bin/applets/crond  logs everything with E priority

### ISSUE THREAD

**Issue by PawelSuwinski** [termux/termux-packages#5010]
m8qlul / # mkdir /data/local/tmp/cron
    m8qlul / #
    m8qlul / # /system/xbin/crond -c /data/local/tmp/cron
    m8qlul / # logcat -t 10 -s crond
    m8qlul / # 3-05 12:50:32.452 20963 20963 I crond   : crond: crond (busybox 1.22.1 bionic) started, log level 8
    m8qlul / # pkill -15 crond
    m8qlul / #
    m8qlul / # /data/data/com.termux/files/usr/bin/applets/crond -c /data/local/tmp/cron
    m8qlul / # logcat -t 10 -s crond
    m8qlul / # 03-05 12:51:32.046 20969 20969 E crond   : crond (busybox 1.31.1) started, log level 8

  And in both situation real non-empty crontabs works fine, but termux crond everything log with E priority (?). Is it termux issue or busybox itself (?). 

Tested on two devices: 

- htc m8qlul: LOS 15.1-20181026-UNOFFICIAL-m8qlul, 3.10.108-g5285e19 aarch64 
- s3mini: LOS 14.1 novafusion 3.0.31-novafusion armv7l

Second one lacks system busybox with crond, just termux crond, but results the same.

**Comment by xeffyr** [comment]
This is Android OS issue, specifically how its syslog wrapper works.
