### ISSUE TITLE
Add "--with-modules" to emacs build.sh

### ISSUE THREAD

**Issue by ferfebles** [termux/termux-packages#5011]
Please, add "--with-modules" compile option to 'build.sh'. 

It allows the use of external libraries inside Emacs.

I've tested it in a Samsung SM-T580 (arm) with emacs-libvterm, that allows running a terminal inside Emacs. It works great

By the way, thanks for your work with termux packages. It allows me to have a really powerfull mobile development platform inside a tiny and cheap android tablet.

**Comment by Grimler91** [comment]
Done in https://github.com/termux/termux-packages/commit/7c639383e7fb796769f907bf350ff53ce8c03834, thanks for testing it before requesting!
