### ISSUE TITLE
Package request: i2pd

### ISSUE THREAD

**Issue by mehlon** [termux/termux-packages#5013]
**Package description**

i2pd is a C++ implementation of I2P.

I2P (Invisible Internet Protocol) is a universal anonymous network layer.
All communications over I2P are anonymous and end-to-end encrypted, participants don't reveal their real IP addresses.
**Link to home page and sources**
1. Home page: https://i2pd.website/
2. Source code: https://github.com/PurpleI2P/i2pd

**Additional information**
Have you compiled or tried to compile the package on device?
No. I haven't tried to compile it yet.
i2pd is available as an android app as well, but having it in Termux would be preferable.

**Comment by xploitednoob** [comment]
this package already have an apk release. so i think we skip this package. and @mehlon would you like to define which version do you need cli or gui

**Comment by xeffyr** [comment]
> so i think we skip this package

It is not necessary to skip package if it is available as Android app.

**Comment by xploitednoob** [comment]
> > so i think we skip this package
>
> It is not necessary to skip package if it is available as Android app.

Got It

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install i2pd
```
