### ISSUE TITLE
Pynacl was not installing

### ISSUE THREAD

**Issue by sahilhacker** [termux/termux-packages#5017]
![Screenshot_2020-03-08-21-29-02-66](https://user-images.githubusercontent.com/61943124/76166385-1db1f280-6184-11ea-9f0f-ab1c0a637492.png)
Plss help my termux couldnot install pynacl

**Comment by xeffyr** [comment]
I don't see any issue here. Installation of some python modules takes long time due to compilation of native extensions and that's normal that it will take ~10 min or more (depending on device).

**Comment by Grimler91** [comment]
See also previous issues, for example https://github.com/termux/termux-packages/issues/1881
