### ISSUE TITLE
pastebinit returns "Unknown website"

### ISSUE THREAD

**Issue by rhjdvsgsgks** [termux/termux-packages#5018]
**Problem description**

pastebinit returns `Unknown website, please post a bugreport to request this pastebin to be added (pastebin.com)`

**Steps to reproduce**

```bash
echo 1|pastebinit
Unknown website, please post a bugreport to request this pastebin to be added (pastebin.com)
```
**Expected behavior**

like what it should be done

**Additional information**

`pastebinit -l` says no supported pastebins here , but there are many pastebins config under `$PREFIX/etc/pastebin.d/`
```bash
ls $PREFIX/etc/pastebin.d/
dpaste.com.conf        paste.openstack.org.conf     paste2.org.conf
fpaste.org.conf        paste.pound-python.org.conf  pastebin.com.conf
p.defau.lt.conf        paste.ubuntu.com.conf        slexy.org.conf
paste.debian.net.conf  paste.ubuntu.org.cn.conf     sprunge.us.conf
```

**Comment by xeffyr** [comment]
Fixed now.
```
pkg upgrade
```
