### ISSUE TITLE
Package request: muchsync

### ISSUE THREAD

**Issue by matthiasbeyer** [termux/termux-packages#5020]
**Package description**

"muchsync - synchronize notmuch mail across machines"

**Link to home page and sources**
1. Home page: http://www.muchsync.org/
2. Source code: http://www.muchsync.org/muchsync.git

**Additional information**
* Have you compiled or tried to compile the package on device?: No.

---

Written in C++11, needs headers and libraries from notmuch, Xapian, SQLite3, and OpenSSL’s libcrypto for compiling, and for running ssh is required. 

All those things are already available on termux.

**Comment by xeffyr** [comment]
Closing since package is available.
