### ISSUE TITLE
Termux brokes after some commands

### ISSUE THREAD

**Issue by BruceMoustache** [termux/termux-packages#5022]
I run this commands and after that termux ndk-sysroot package brokes and I can't install any package
-------
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ apt install ndk-sysroot
Reading package lists... Done
Building dependency tree... Done
Package ndk-sysroot is not available, but is referred to by another pac
kage.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  zlib

E: Package 'ndk-sysroot' has no installation candidate
$ g++
The program g++ is not installed. Install it by executing:
 pkg install clang
$ pkg install vim clang
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package vim
E: Unable to locate package clang
$ pkg update
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRele
ase
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [53
44 B]
Get:6 https://dl.bintray.com/grimler/science-packages-24 science Releas
e [5348 B]
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable Release [
6061 B]
Get:7 https://dl.bintray.com/grimler/game-packages-24 games Release.gpg
 [475 B]
Get:8 https://dl.bintray.com/grimler/science-packages-24 science Releas
e.gpg [475 B]
Get:9 https://dl.bintray.com/termux/termux-packages-24 stable Release.g
pg [821 B]
Get:10 https://dl.bintray.com/grimler/game-packages-24 games/stable arm
 Packages [3764 B]
30% [Working]^[[A^[[B^[[B^[[B
Ign:11 https://dl.bintray.com/grimler/science-packages-24 science/stabl
e arm Packages
Get:12 https://dl.bintray.com/termux/termux-packages-24 stable/main arm
 Packages [114 kB]
Get:11 https://dl.bintray.com/grimler/science-packages-24 science/stabl
e arm Packages [5268 B]
Fetched 141 kB in 2min 20s (1009 B/s)
Reading package lists... Done
Building dependency tree... Done
11 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
The following packages will be upgraded:
  bash coreutils curl dpkg ed libcurl libgpg-error ncurses pcre
  readline termux-exec
11 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 4172 kB of archives.
After this operation, 184 kB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
$ pkg update
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRele
ase
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [53
44 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:6 https://dl.bintray.com/grimler/science-packages-24 science Releas
e [5348 B]
Hit:6 https://dl.bintray.com/grimler/science-packages-24 science Releas
e
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable Release [
6061 B]
Hit:4 https://dl.bintray.com/termux/termux-packages-24 stable Release
Reading package lists... Done
Building dependency tree... Done
11 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
The following packages will be upgraded:
  bash coreutils curl dpkg ed libcurl libgpg-error ncurses pcre
  readline termux-exec
11 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 4172 kB of archives.
After this operation, 184 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
ncurses arm 6.2.20200222 [488 kB]
Get:2 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
readline arm 8.0.4 [218 kB]
Get:3 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
bash arm 5.0.16 [792 kB]
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
coreutils arm 8.32 [715 kB]
Get:5 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
libcurl arm 7.69.0 [817 kB]
Get:6 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
curl arm 7.69.0 [148 kB]
Get:7 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
dpkg arm 1.20.0 [207 kB]
Get:8 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
termux-exec arm 0.5 [3108 B]
Get:9 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
libgpg-error arm 1.37 [94.7 kB]
Get:10 https://dl.bintray.com/termux/termux-packages-24 stable/main arm
 pcre arm 8.44 [653 kB]
Get:11 https://dl.bintray.com/termux/termux-packages-24 stable/main arm
 ed arm 1.16 [36.3 kB]
Fetched 4172 kB in 18s (222 kB/s)
(Reading database ... 3139 files and directories currently installed.)
Preparing to unpack .../ncurses_6.2.20200222_arm.deb ...
Unpacking ncurses (6.2.20200222) over (6.1.20190928) ...
Setting up ncurses (6.2.20200222) ...
(Reading database ... 3144 files and directories currently installed.)
Preparing to unpack .../readline_8.0.4_arm.deb ...
Unpacking readline (8.0.4) over (8.0.1) ...
Setting up readline (8.0.4) ...
(Reading database ... 3144 files and directories currently installed.)
Preparing to unpack .../archives/bash_5.0.16_arm.deb ...
Unpacking bash (5.0.16) over (5.0.11) ...
Setting up bash (5.0.16) ...
(Reading database ... 3144 files and directories currently installed.)
Preparing to unpack .../coreutils_8.32_arm.deb ...
Unpacking coreutils (8.32) over (8.31-8) ...
Setting up coreutils (8.32) ...
(Reading database ... 3140 files and directories currently installed.)
Preparing to unpack .../libcurl_7.69.0_arm.deb ...
Unpacking libcurl (7.69.0) over (7.68.0) ...
Setting up libcurl (7.69.0) ...
$ pkg install vim
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  vim-runtime
The following NEW packages will be installed:
  vim vim-runtime
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 5049 kB of archives.
After this operation, 25.0 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
vim-runtime all 8.2.0350 [4141 kB]
Get:2 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
vim arm 8.2.0350 [908 kB]
Fetched 5049 kB in 14s (348 kB/s)
Selecting previously unselected package vim-runtime.
(Reading database ... 3154 files and directories currently installed.)
Preparing to unpack .../vim-runtime_8.2.0350_all.deb ...
Unpacking vim-runtime (8.2.0350) ...
Selecting previously unselected package vim.
Preparing to unpack .../archives/vim_8.2.0350_arm.deb ...
Unpacking vim (8.2.0350) ...
Setting up vim-runtime (8.2.0350) ...
Setting up vim (8.2.0350) ...
update-alternatives: using /data/data/com.termux/files/usr/bin/vim to p
rovide /data/data/com.termux/files/usr/bin/editor (editor) in auto mode
$ pkg install clang
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  binutils libffi libllvm ndk-sysroot
The following NEW packages will be installed:
  binutils clang libffi libllvm ndk-sysroot
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 29.2 MB of archives.
After this operation, 149 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
binutils arm 2.34 [2153 kB]
Get:2 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
ndk-sysroot arm 20-7 [1574 kB]
Get:3 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
libffi arm 3.3 [31.0 kB]
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
libllvm arm 9.0.1-1 [24.8 MB]
Get:5 https://dl.bintray.com/termux/termux-packages-24 stable/main arm 
clang arm 9.0.1-1 [696 kB]
Fetched 29.2 MB in 7min 44s (62.9 kB/s)
Selecting previously unselected package binutils.
(Reading database ... 4546 files and directories currently installed.)
Preparing to unpack .../archives/binutils_2.34_arm.deb ...
Unpacking binutils (2.34) ...
Selecting previously unselected package ndk-sysroot.
Preparing to unpack .../ndk-sysroot_20-7_arm.deb ...
Unpacking ndk-sysroot (20-7) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cach
e/apt/archives/ndk-sysroot_20-7_arm.deb (--unpack):
 unable to open '/data/data/com.termux/files/usr/include/linux/netfilte
r_ipv6/ip6t_HL.h.dpkg-new': No such file or directory
Selecting previously unselected package libffi.
Preparing to unpack .../archives/libffi_3.3_arm.deb ...
Unpacking libffi (3.3) ...
Selecting previously unselected package libllvm.
Preparing to unpack .../libllvm_9.0.1-1_arm.deb ...
Unpacking libllvm (9.0.1-1) ...
Selecting previously unselected package clang.
Preparing to unpack .../archives/clang_9.0.1-1_arm.deb ...
Unpacking clang (9.0.1-1) ...
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/ndk-sysroot_20-
7_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an err
or code (1)
$ pkg install clang
Reading package lists... Done
Building dependency tree
Reading state information... Done
clang is already the newest version (9.0.1-1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libllvm : Depends: ndk-sysroot but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages 
(or specify a solution).
$ apt --fix-broken install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  ndk-sysroot
The following NEW packages will be installed:
  ndk-sysroot
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
Need to get 0 B/1574 kB of archives.
After this operation, 22.3 MB of additional disk space will be used.
Do you want to continue? [Y/n]
(Reading database ... 7007 files and directories currently installed.)
Preparing to unpack .../ndk-sysroot_20-7_arm.deb ...
Unpacking ndk-sysroot (20-7) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cach
e/apt/archives/ndk-sysroot_20-7_arm.deb (--unpack):
 unable to install new version of '/data/data/com.termux/files/usr/incl
ude/linux/netfilter_ipv6/ip6t_HL.h': No such file or directory
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/ndk-sysroot_20-
7_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an err
or code (1)
$

**Comment by Grimler91** [comment]
Closing in favour of https://github.com/termux/termux-packages/issues/5016
