### ISSUE TITLE
E: Unable to locate package ip 

### ISSUE THREAD

**Issue by mugiwara33** [termux/termux-packages#5024]
Hi Guys.
I try to apt install ip on Termux in android 8 rooted.
$ apt install ip
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ip.

Pls if u can help .

**Comment by RossComputerGuy** [comment]
Try `pkg install ip`.

**Comment by mugiwara33** [comment]
Same problem
...
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ip

**Comment by RossComputerGuy** [comment]
It looks like the package is not in the repos

**Comment by Grimler91** [comment]
Why do you expect there to be a package called "ip"?

**Comment by mugiwara33** [comment]
I installed wifite in kali termux
Its require ip that I should install it by apt install ip

**Comment by mugiwara33** [comment]
> It looks like the package is not in the repos

How can I solve it?

**Comment by mugiwara33** [comment]
Why u closed issue.
Is the problem solved ?????
