### ISSUE TITLE
Postgresql cluster

### ISSUE THREAD

**Issue by 4V4loon** [termux/termux-packages#5030]
I was trying to install Postgresql, and such error occurred:
`FATAL: could not create shared memory segment: Function not implemented 2020-03-13 22:40:18.098 +04 [25393] DETAIL: Failed system call was shmget(key=5432001, size=40, 03600). 2020-03-13 22:40:18.099 +04 [25393] LOG: database system is shut down pg_ctl: could not start server Examine the log output.`
Any solution? 
Thank you in advance for your help!

**Comment by xeffyr** [comment]
Could you try
```
pkg install libandroid-shmem
export LD_PRELOAD=$PREFIX/lib/libandroid-shmem.so:$LD_PRELOAD
```
before launching it ?

**Comment by 4V4loon** [comment]
Thanks for all. Service is running.
