### ISSUE TITLE
swaks

### ISSUE THREAD

**Issue by undrspecified** [termux/termux-packages#5038]
**Package description**

"Swaks is a featureful, flexible, scriptable, transaction-oriented SMTP test tool written and maintained by John Jetmore. It is free to use and licensed under the GNU GPLv2."

It's a nice commandline tool for debugging SMTP over TLS, and a whole bunch of other useful stuff.

**Link to home page and sources**
1. Home page: https://jetmore.org/john/code/swaks/
2. Source code: https://github.com/jetmore/swaks

**Additional information**
I have not compiled or tried to compile the package on my device.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install swaks
```
