### ISSUE TITLE
I have Linux and Termux but can't install anything with... 

### ISSUE THREAD

**Issue by Judje34** [termux/termux-packages#5041]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by RossComputerGuy** [comment]
Please use the template and not the title to describe your issue.

**Comment by Judje34** [comment]
No instructions with the app, nor with Linux, I'm à reddit member but I've always preferred learning on my own, than reading absolutely every available online explanations, even if I'm reading for a while but nothing's better than self learning practice for me. Thanks to give me advices and to avoid being chocked by my programmation level, I'm aware of this detail, thanks.

**Comment by RossComputerGuy** [comment]
Ok. Wdym? The title says " have Linux and Termux but can't install anything with..." so I have no idea what your asking. @xeffyr maybe this issue needs to be closed.

**Comment by RossComputerGuy** [comment]
@Grimler91 thanks
