### ISSUE TITLE
bash: cd: /sdcard/ltc: No such file or directory

### ISSUE THREAD

**Issue by theboycyti1** [termux/termux-packages#5046]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by theboycyti1** [comment]
I'm newbie help meeee huhuhu

**Comment by xeffyr** [comment]
> cd: /sdcard/ltc: No such file or directory

> https://www.tldp.org/LDP/Bash-Beginners-Guide/html/
