### ISSUE TITLE
Package request: BOINC

### ISSUE THREAD

**Issue by yjun123** [termux/termux-packages#5048]
**Package description**

Boinc is the Open-source software for volunteer computing and grid computing.
It lets you help cutting-edge science research using your computer (Windows, Mac, Linux) or Android device. BOINC downloads scientific computing jobs to your computer and runs them invisibly in the background. It's easy and safe.About 30 science projects use BOINC; examples include Einstein@Home, IBM World Community Grid, and SETI@home. These projects investigate diseases, study global warming, discover pulsars, and do many other types of scientific research.
 --- from the BOINC homepage,It describe what the BONC is.

as a BOINC volunteer and a linuxer,I want run BOINC on every my Linux device,But sadly,I can't find BOINC on termux offical repository,I hope Termux add it to the repository;Of course, BOINC support ARM and AArch,I run BONIC on my ARM single chip computer before,It's works!  

**Link to home page and sources**
1. Home page: https://boinc.berkeley.edu/
2. Source code: https://github.com/BOINC/boinc

**Additional information**

Yes! I have tried compiled BOINC on termux,smooth and quickly,although there is some error.LOL
I tried according to https://archlinuxarm.org/packages/aarch64/boinc-nox/files/PKGBUILD,
some steps:
```
# Don't force xss
sed -i 's/^  enable_xss="yes"$/  enable_xss="no"/' configure.ac
 ./_autosetup
PKG_CONFIG=/usr/bin/pkg-config ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --enable-libraries \
    --enable-unicode \
    --enable-shared \
    --enable-dynamic-client-linkage \
    --enable-client \
    --disable-server \
    --disable-static \
    --disable-manager \
    --with-ssl \
    --without-wxdir \
    --without-x \

  make
```

during the compling,there will find some dependency  lacked,just use `pkg install` to fix it.
But,there is still  something lacked,during the compiling,a error ocoured,
```
fatal error: 'sys/sem.h' file not found
```
I googled it and found the solution https://android.googlesource.com/platform/bionic/+/master/libc/include/sys/sem.h
add it to `$PREFIX/usr/include/sys`
It works! comipleing resumed !

Bad English,Thanks!

**Comment by Grimler91** [comment]
We have an old PR here: https://github.com/termux/termux-packages/pull/503

Don't know why it was closed

**Comment by Grimler91** [comment]
For sem.h you can also replace sys/sem.h with linux/sem.h, as done for example here:
https://github.com/termux/termux-packages/blob/f6b9fa665f36dd85daf8960dc2df264bd07a6a24/packages/qemu-system-x86_64-headless/0007-fix-sem.h-location.patch

**Comment by yjun123** [comment]
> We have an old PR here: #503
> 
> Don't know why it was closed

oh,Thanks!

**Comment by xeffyr** [comment]
```
synch.cpp:49:10: error: use of undeclared identifier 'semget'; did you mean 'memset'?
    id = semget(key, 1, IPC_CREAT|IPC_EXCL|0777);
         ^~~~~~
         memset
synch.cpp:28:12: note: 'memset' declared here
using std::memset;
           ^
synch.cpp:49:17: error: cannot initialize a parameter of type 'void *' with an lvalue of type 'key_t' (aka 'int')
    id = semget(key, 1, IPC_CREAT|IPC_EXCL|0777);
                ^~~
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/string.h:62:20: note: passing argument to parameter '__dst' here
void* memset(void* __dst, int __ch, size_t __n);
                   ^
synch.cpp:55:14: error: use of undeclared identifier 'semctl'
    retval = semctl(id, 0, SETVAL, s);
             ^
synch.cpp:64:10: error: use of undeclared identifier 'semget'; did you mean 'memset'?
    id = semget(key, 0, 0);
```

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/pull/5058

**Comment by yjun123** [comment]
> #5058

Awesome! Thanks for your job!

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install boinc
```

**Comment by truboxl** [comment]
BOINC on Termux is broken
Because BOINC have some `#ifdef ANDROID` in its source codes that causes Internet connectivity to be handled by Java UI, you won't be able to do anything
Suggest don't add this package
```
... [---] Suspending network activity - not connected to WiFi network
... [---] Exiting
```
If people really want to use BOINC on Termux, suggest install Linux from Anlinux, and install boinc-client from there. You can use remote access too which you can't from the current BOINC app.

**Comment by truboxl** [comment]
I also checked `boinctui` and getting
`CANNOT LINK EXECUTABLE "boinctui": library "libmenuw.so.6" not found`

**Comment by truboxl** [comment]
ok if boinc wants to be available in termux repo, please drop `-DANDROID` and `-llog` and other patches and patch `boinc/lib/synch.cpp`

`#ifndef ANDROID`

to

`#ifndef __ANDROID__`

for quick and dirty way to fix the internet connection and `sem.h` problems.
