### ISSUE TITLE
Doesn't work on Android 11 Developer Preview 2

### ISSUE THREAD

**Issue by NatoBoram** [termux/termux-packages#5051]
**Problem description**

```
exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]
```

**Steps to reproduce**

1. Open the app

**Expected behavior**

The app should open without throwing errors

**Additional information**

```

```

**Comment by xeffyr** [comment]
See https://github.com/termux/termux-app/issues/1072.
