### ISSUE TITLE
Package Request: lrzsz zssh

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#506]
I am unix Administrator ,I need legacy file transfer via ssh for low speed connection. so I try to build these two packages for it.

**Comment by jyf007** [comment]
although it's bad idea for transfer, it can pass through host-by-host connection.

**Comment by jyf007** [comment]
libandroid-glob can't use for build

**Comment by jyf007** [comment]
globbing.o: In function `glob_args':
/data/data/com.termux/files/home/zssh-1.5c/globbing.c:34: undefined reference to `glob'
/data/data/com.termux/files/home/zssh-1.5c/globbing.c:42: undefined reference to `globfree'
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by its-pointless** [comment]
You are building on device so it looks like its not linking libandroid-glob. In Makefile add -landroid-glob to libs =

**Comment by jyf007** [comment]
roid-glob
make: [Makefile:74: ztelnet] Error 1 (ignored)
ln zssh ztelnet
ln: failed to create hard link 'ztelnet' => 'zssh': Permission denied
make: *** [Makefile:75: ztelnet] Error 1                                                                            $ ./zssh
Segmentation fault (core dumped)
$ ./zssh --hel[
Segmentation fault (core dumped)
i had not changed the source code.but it fail.

**Comment by its-pointless** [comment]
Android can't do hard links.
Which cpu arch you using?

**Comment by its-pointless** [comment]
Just do
autoconf
./configure --prefix=/data/data/com.termux/files/usr LIBS="-landroid-glob"
make -j4 
make install

**Comment by jyf007** [comment]
hard link is not the problem,i want ask for Segmentation fault for using aarch64
 comment out line 53 and 55 in completion.c 
how to change it

**Comment by its-pointless** [comment]
https://github.com/its-pointless/lrzsz-apps
here

**Comment by jyf007** [comment]
I tried but zssh doesnot work and lrzsz package need change exec file name w/o l
