### ISSUE TITLE
bash-5.0 coming before $ sign

### ISSUE THREAD

**Issue by Ankit3k** [termux/termux-packages#5065]
**Problem description**

When I start my termux there is a word "**bash-5.0**" coming before "**$**" sign and that just irritating. Please help me removing that.

**Steps to reproduce**
 After starting termux and at all places before typing any commands.

**Expected behavior**
 There should be only "$" sign at starting after which we type our commands.
![Screenshot_2020-03-23-01-43-59-619_com termux](https://user-images.githubusercontent.com/60462097/77259493-d2c9cc00-6ca7-11ea-9e60-bc1ba64b9b37.jpg)

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/kuburan.list
deb [arch=all,aarch64] https://kuburan.github.io/files/ termux external
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.14.81-perf+ #1 SMP PREEMPT Fri Mar 6 14:28:03 CST 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 7 Pro

```

**Comment by xeffyr** [comment]
This is not a bug.

Seems like you edited/deleted one or more configuration files.

**Comment by xeffyr** [comment]
Does `$PREFIX/etc/bash.bashrc` exist ? If not, make sure it contains exactly
``` .bash
if [ -x /data/data/com.termux/files/usr/libexec/termux/command-not-found ]; then
	command_not_found_handle() {
		/data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"
	}
fi

PS1='\$ '
```

**Comment by armotodo** [comment]
lo elimine al presentar caracteres defectuosos


PREFIX/etc/bash.bashrc: No such file or directory

**Comment by armotodo** [comment]
process ID: 11075
While opening file "bash.bashrc"
      CANNOT BE FOUND
(1) Another program may be editing the sam
e file.  If this is the case,
    be careful not to end up with two diff
erent instances of the same
    file when making changes.  Quit, or co
ntinue with caution.
(2) An edit session for this file crashed.

    If this is the case, use ":recover" or
 "vim -r bash.bashrc"
    to recover the changes (see ":help rec
overy").
    If you did this already, delete the sw
ap file ".bash.bashrc.swp"
    to avoid this message.

Swap file ".bash.bashrc.swp" already exist
s!
[O]pen Read-Only, (E)dit anyway, (R)ecover
, (D)elete it, (Q)uit, (A)bort:

**Comment by armotodo** [comment]
Podrian indicarme por favor que debo hacer para restaurarlo

**Comment by armotodo** [comment]
<200b>if<200b> [ <200b>-r<200b> /data/data/com.termux/files/usr/etc/bash.bashrc ]<200b>;<200b> <200b>then<200b>
                        <200b>.<200b> /dat
a/data/com.termux/files/usr/etc/bash.bashr
c
                <200b>fi<200b>
                <200b>if<200b> [ <200b>-r<200b> /data/data/com.termux/files/usr/.bashrc ]<200b>;<200b> <200b>then<200b>
                        <200b>.<200b> /data/data/com.termux/files/usr/.bashrc                       <200b>fi<200b>                    <200b>fi<200b>                    <200b>fi

**Comment by irfhan727** [comment]
How to make it defoult
