### ISSUE TITLE
gsl is not compiled properly in Termux.

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#507]
If you try to compile and run any program that uses gsl library you will get an error:

```
$ ./test
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "cblas_sdsdot" referenced by "libgsl.so.19"...
```

This seems to be a known problem, see here:

[https://qnalist.com/questions/6297808/how-to-resolve-dependency-between-so-libraries-the-cannot-locate-symbol-cblas-sdsdot-referenced-by-libgsl-so-error](https://qnalist.com/questions/6297808/how-to-resolve-dependency-between-so-libraries-the-cannot-locate-symbol-cblas-sdsdot-referenced-by-libgsl-so-error)

See the session transcript below in order to reproduce:

```
$ cat test.c
#include <gsl/gsl_integration.h>

int main(int argc, char *argv[])
{
    gsl_integration_workspace_alloc(1000);
    return 0;
}
$ gcc -Wall -O3  -lgsl -lgslcblas -lm  test.c   -o test
$ ./test
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "cblas_sdsdot" referenced by "libgsl.so.19"...
$ ldd test
libgsl.so.19
libgslcblas.so.0
libm.so
libdl.so
libc.so
$ ls -l $PREFIX/lib/libgsl*
lrwxrwxrwx 1 u0_a119 u0_a119      16 Oct 15 16:47 /data/data/com.termux/files/usr/lib/libgsl.so -> libgsl.so.19.2.0
lrwxrwxrwx 1 u0_a119 u0_a119      16 Oct 15 16:47 /data/data/com.termux/files/usr/lib/libgsl.so.19 -> libgsl.so.19.2.0
-rwxr-x--- 1 u0_a119 u0_a119 1724888 Sep  5 23:06 /data/data/com.termux/files/usr/lib/libgsl.so.19.2.0
lrwxrwxrwx 1 u0_a119 u0_a119      20 Oct 15 16:47 /data/data/com.termux/files/usr/lib/libgslcblas.so -> libgslcblas.so.0.0.0
lrwxrwxrwx 1 u0_a119 u0_a119      20 Oct 15 16:47 /data/data/com.termux/files/usr/lib/libgslcblas.so.0 -> libgslcblas.so.0.0.0
-rwxr-x--- 1 u0_a119 u0_a119  173128 Sep  5 23:06 /data/data/com.termux/files/usr/lib/libgslcblas.so.0.0.0
```

**Comment by tigran123** [comment]
I forgot to mention that the above problem occurs on Android 5.1.1 on Nexus 10 (i.e. armv7l architecture). I'll try Android 6.0.1 on aarch64 now.

**Comment by fornwall** [comment]
Seems to be an issue with the Android linker (RTLD_GLOBAL not working) that was fixed in Android 6.0 - see https://github.com/android-ndk/ndk/issues/201.

**Comment by tigran123** [comment]
Ok, so could we not use the workaround suggested by Dmitry there?

**Comment by tigran123** [comment]
UPDATE: I have compiled libgsl-2.2.1 on Nexus 10 with this configure invocation:

```
./configure --prefix=$PREFIX GSL_LDFLAGS="-Lcblas/.libs/ -lgslcblas"
```

And the result is working fine. The programs link against it and run correctly. (Timing is 32ms vs 19ms on my UMI Super vs 10 ms on desktop). So, it is definitely possible to recompile and re-package gsl in a way that will work on Android 5.1.1 systems.

**Comment by fornwall** [comment]
> Ok, so could we not use the workaround suggested by Dmitry there?

I just wanted to write down the underlying reason for future reference.

I've applied the workaround now to an updated gsl package, so it should work also on Android 5 - thanks!
