### ISSUE TITLE
Programs compiled with clang 9.0.1-2 gives PIE error on arm

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#5076]
**Problem description**
Compiling a binary with clang 9.0.1-2 and trying to run it on arm gives

```sh
error: only position independent executables (PIE) are supported.
```
It works fine with 9.0.1-1 so problem should be related to the changed patch in https://github.com/termux/termux-packages/commit/cdd6a5b7f7f64ebd6f6b1d9ff14235fcaaa8086a.

**Steps to reproduce**
Create a file `test.c` with the content
```
int main()
{
  return 0;
}
```
and compile it with `clang -o test test.c` and then try to run it with `./test`.

**Expected behavior**
Program should run without problem.

**Additional information**
```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24 stable main
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://grimler.se/unstable-packages unstable stable
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 stable
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.4.113-Deathly-1.0 #1 SMP PREEMPT Fri Mar 20 22:55:45 CDT 2020 armv7l Android
Device manufacturer:
samsung
Device model:
SM-T800
```

**Comment by xeffyr** [comment]
It is related to this change:
``` diff
 bool Linux::isPIEDefault() const {
-  return (getTriple().isAndroid() && !getTriple().isAndroidVersionLT(16)) ||
+  return getTriple().isAndroid()  ||
           getTriple().isMusl() || getSanitizerArgs().requiresPIE();
 }
```

**Comment by buttaface** [comment]
Yes, the new clang should always be setting PIE as the default, rather than before when it would check the API version also. Can you check the linker flags both ways, ie with clang before and after this patch by passing the `-v` flag when compiling, and see what changed?

**Comment by buttaface** [comment]
Sorry, before it would always set PIE on Android, but now it checks the API version too. I figured since the API version will always be higher than 16, that's enough. But maybe there's some bug where it sometimes thinks the API is less than 16 when it isn't, I'll check.

**Comment by buttaface** [comment]
Got something for you to try, does changing the default target fix this? Try `clang -o test test.c --target=armv7a-linux-androideabi24` and see if it fixes it. If so, try `--target=armv7a-linux-androideabi15` and see if it breaks again.

**Comment by Grimler91** [comment]
@buttaface yeah, can also confirm that having a target > armv7a-linux-androideabi15 fixes it

**Comment by its-pointless** [comment]
Its almost like someone set it to pie as default for a reason...

**Comment by Grimler91** [comment]
@its-pointless are you saying that you are putting thought into patches rather than changing code by random until it works? :)

Looks like the PIE fix was moved from Gnu.cpp to Linux.cpp in https://github.com/termux/termux-packages/commit/2d124b6737dab1e87ff47153c8e3e231a42f4e5e#diff-f7787e82d99cdf6c449d2eb810779dda, do you remember if there was a particular reason for this change?
