### ISSUE TITLE
micro editor doesnt have proper version.

### ISSUE THREAD

**Issue by akowiz** [termux/termux-packages#5081]
When running ```micro -version```, micro returns 
```
Version: 0.0.0-unknown
Commit hash:
Compiled on March 01, 2020
```
The side effect is that it is impossible to install plugins in micro outside of the default plugins that come with the editor.

This is a known issue with the debian package (see https://github.com/zyedidia/micro/issues/1582 )

**Steps to reproduce**

```micro -version```

**Expected behavior**

It should return the correct version, git hash and date of compilation.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.10.84-13024869 #1 SMP PREEMPT Tue Feb 6 21:35:55 KST 2018 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T719Y
```

**Comment by utkarsh2102** [comment]
@akowizm @xeffyr, hi,
This has already been fixed in Debian around 2 weeks back :)

**Comment by SLAYER-CODE** [comment]
En realidad solo en termux esta fallando , Tienes que clonar los ficheros de la pagina oficial 
bueno no te olvides respaldar tus configuraciones en $HOME/.config/micro  #opcional
y desistala el micro con ...

apt-get remove micro 

git clone https://github.com/zyedidia/micro
cd micro
make build

./micro "archivo "   
 luego agregas la ruta de el archivo micro en  el bin
cp micro /usr/local/bin 
para que funcione en todos los directorios

Por ultimo comprueba si funciona
micro -version

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/d3d0e94b8c1664271cccd4b4a65be9f1782f839d.

Updated package version will be available shortly.
