### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Sandeep502698** [termux/termux-packages#5083]
**$
$ wget https://Auxilus.github.io/metasploit.sh
--2020-03-27 13:06:23--  https://auxilus.github.io/metasploit.sh
Resolving auxilus.github.io... 185.199.108.153, 185.199.111.153, 185.199.110.153, ...
Connecting to auxilus.github.io|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-27 13:06:24 ERROR 404: Not Found.**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by Grimler91** [comment]
You are trying to download something that does not exist

**Comment by Sandeep502698** [comment]
Yes sir
