### ISSUE TITLE
Loading problem

### ISSUE THREAD

**Issue by haffyjuff** [termux/termux-packages#5085]
![Screenshot_2020-03-27-22-52-09-42](https://user-images.githubusercontent.com/62766323/77785672-56a3ff80-707e-11ea-971f-2d2075765d47.png)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
Not a problem/bug.

Carefully read what package manager asks and pick variant appropriate for you.

**Comment by haffyjuff** [comment]
xeffyr can you solve this problem this process not going ahead it's stopped at 4%

**Comment by xeffyr** [comment]
> can you solve this problem

This is not problem at all !

Package manager asks you to whether replace config file or not. Decide what you want to do on your own. E.g. say "y".
