### ISSUE TITLE
Request: libunshield

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-packages#5086]
extracts cab and iss(installshield cab) files uses zlib and openssl 
Links:
Homepage:
https://github.com/twogood/unshield

src:https://github.com/twogood/unshield

Additional info
Tried to compile but got an linking error 
Here is the error I'm on Android 9

/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: CMakeFiles/unshield.dir/unshield.c.o: in function `main':
/data/data/com.termux/files/home/unshield/src/unshield.c:778: undefined reference to `libiconv_open'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/home/unshield/src/unshield.c:820: undefined reference to `libiconv_close'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: CMakeFiles/unshield.dir/unshield.c.o: in function `convert_encoding':
/data/data/com.termux/files/home/unshield/src/unshield.c:159: undefined reference to `libiconv'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/unshield.dir/build.make:106: src/unshield] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/unshield/build'
make[1]: *** [CMakeFiles/Makefile2:209: src/CMakeFiles/unshield.dir/all] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/unshield/build'
make: *** [Makefile:147: all] Error 2

**Comment by FreddieOliveira** [comment]
> /data/data/com.termux/files/home/unshield/src/unshield.c:159: undefined reference to `libiconv'

Did you try to install it `pkg install libiconv` and then compile again?

**Comment by strikersix23** [comment]
libiconv is already installed I triple checked I believe macros might be missing

**Comment by strikersix23** [comment]
As it is missing
libiconv_open
libiconv_close

Everything else compiles but it stops there

**Comment by strikersix23** [comment]
I got logs here:
[CMakeOutput.log](https://github.com/termux/termux-packages/files/4396610/CMakeOutput.log)

[CMakeError.log](https://github.com/termux/termux-packages/files/4396612/CMakeError.log)

**Comment by qwerty12** [comment]
Build it with `LDFLAGS=" -Wl,--no-as-needed -liconv" cmake ..`

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unshield
```
