### ISSUE TITLE
Bin/login cat: not found, Fix this

### ISSUE THREAD

**Issue by haffyjuff** [termux/termux-packages#5087]
![Screenshot_2020-03-28-06-24-02-05](https://user-images.githubusercontent.com/62766323/77811573-24fe5900-70bd-11ea-8b0b-dfe0204891fa.png)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
`rm -rf $PREFIX` and then reopen application.
