### ISSUE TITLE
Request: SQLCipher

### ISSUE THREAD

**Issue by nodefive** [termux/termux-packages#5096]
Would be nice to have SQLCipher binaries available from Termux's cli, currently I can only find the API provided by zetetic.

---

Decided to install it manually!

Anyway, I've compiled using:

```
apt install openssl
apt install c
apt install gcc
apt install build-essential
git clone https://github.com/sqlcipher/sqlcipher.git
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="../../usr/lib/libcrypto.so"
make
```

Edit the prefix in the Makefile from **/usr/local** to **/data/data/com.termux/files/usr/**
And install it in termux with a:

`make install`

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install sqlcipher
```
