### ISSUE TITLE
termux-change-repo 404 not found

### ISSUE THREAD

**Issue by signotorez** [termux/termux-packages#5097]
```sh
$ termux-change-repo
```
* official repositories selected
  - Changing main repository
  - Changing x11 repository

```sh
$ pkg up
```
`E: The repository 'https://dl.bintray.com/xeffyr/unstable-packages x11 Release' does not have a Release file.`
`N: Metadata integrity can't be verified, repository is disabled now.`
`N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).`

**Comment by xeffyr** [comment]
Sorry, there is a typo in `termux-change-repo` which picks wrong URL for X11 repo.

You can edit
```
$PREFIX/etc/apt/sources.list.d/x11.list
```
and reset it to:
```
deb https://dl.bintray.com/xeffyr/unstable-packages x11 main
```

**Comment by Grimler91** [comment]
Fixed in https://github.com/termux/termux-packages/commit/355c503fa05b669fdfce32523dac4a7b70151a3f, thanks for reporting!

**Comment by Sammyhills19** [comment]
Am facing the same problem. How do I fix it?

**Comment by RossComputerGuy** [comment]
@Sammyhills19 You'll have to manually edit the apt sources file to the source listed in @xeffyr's comment then run `pkg upgrade`

**Comment by xeffyr** [comment]
@RossComputerGuy URL listed here is outdated.

**Comment by RossComputerGuy** [comment]
Oh, oh yeah because of Bintray shutting down. Forgot about that lol.

**Comment by Sammyhills19** [comment]
How do I manually edit apt sources?

**Comment by RossComputerGuy** [comment]
Use a text editor such as Vim or nano, that's something that you can look online on how to do as well.

**Comment by RossComputerGuy** [comment]
Also, this is a good time to RTFM.

**Comment by xeffyr** [comment]
> Use a text editor such as Vim or nano

`apt edit-sources`

**Comment by Avetishacker** [comment]
Help me i cant fix it

**Comment by RB-DEV-2000** [comment]
> Oh, oh yeah because of Bintray shutting down. Forgot about that lol.

When it starts?

**Comment by RossComputerGuy** [comment]
It started on the 1st of May

**Comment by RB-DEV-2000** [comment]
Please help me im begginer

**Comment by xeffyr** [comment]
You're unable to update because `dl.bintray.com` has finished its service. It won't work anymore.

Do steps as in https://github.com/termux/termux-packages/issues/6726
