### ISSUE TITLE
Bad system call using ping6

### ISSUE THREAD

**Issue by ntremble** [termux/termux-packages#5099]
Attempting to use ping6 results in a bad system call error. This is on a Motorola XT1962-5 with Android 9 and all available updates. The networks (both cell and Wi-Fi) are IPv6 capable.
$ ping6 2403:5800:4100:xxxx:yyyy:e6ae:1976:zzzz
PING 2403:5800:4100:xxxx:yyyy:e6ae:1976:zzzz(2403:5800:4100:xxxx:yyyy:e6ae:1976:zzzz) 56 data bytes
Bad system call
$
$ ping6 google.com
PING google.com(syd15s04-in-x0e.1e100.net) 56 data bytes
Bad system call
$

**Comment by Grimler91** [comment]
`ping6` is just a wrapper around `/system/bin/ping6` (check with `more $(which ping6)`) so this is something you have to report to Motorola (or, if you use a custom ROM, to the creator of your ROM).
