### ISSUE TITLE
OpenGL without windowing system?

### ISSUE THREAD

**Issue by ebraminio** [termux/termux-packages#51]
I have no experience on any library could provide OpenGL without X or a windowing system. That is not therotically impossible AFAIK as OpenGL APIs don't care about windowing system anyway and some kind of directly writing into framebuffer perhaps is possible but I guess GLFW and freeglut libraries won't support us here. What library could be used for such thing? Is it something would be possible eventually or it is already possible in someway I am not aware of? Thank you

**Comment by fornwall** [comment]
Android uses EGL to interface between OpenGL and the windowing system, so that should probably be used if possible (never used that myself).

For windowed OpenGL rendering I'm planning to add a separate app which will support launching while specifying a shared library. At launch this app will `dlopen()` and call the shared library specified dynamically, enabling one to build and launch OpenGL ES-using programs.

**Comment by franciscod** [comment]
LÖVE (a Lua framework for building games) just released version 0.10.0, with an Android port! https://love2d.org/wiki/0.10.0
More info:
- https://love2d.org/forums/viewtopic.php?f=11&t=76979
- https://bitbucket.org/MartinFelis/love-android-sdl2

**Comment by franciscod** [comment]
Also there's this X11 server:
https://f-droid.org/repository/browse/?fdfilter=x11&fdid=au.com.darkside.XServer

**Comment by kazuoteramoto** [comment]
Something like [OSMesa](http://www.mesa3d.org/osmesa.html)?

A program that I have experience with that uses OSMesa is [asymptote](http://asymptote.sourceforge.net) to render 3d images.

I used asymptote in the past on android with osmesa, but using a chroot with Archlinux. Never tried it with termux.

**Comment by markus-zzz** [comment]
> For windowed OpenGL rendering I'm planning to add a separate app which will support launching while specifying a shared library. At launch this app will dlopen() and call the shared library specified dynamically, enabling one to build and launch OpenGL ES-using programs.

Has there been any progress on this? I could really use something like this so I would not mind giving it a go if it is not already in the works.

**Comment by BotellaA** [comment]
Does this other app exist? Is this opengl idea still active?
I would love to be able to use it!

**Comment by markus-zzz** [comment]
I did some work on this about a year ago. https://github.com/markus-zzz/vulkan/tree/master/soloader
