### ISSUE TITLE
Javac

### ISSUE THREAD

**Issue by parind** [termux/termux-packages#510]
How do I build javac in Termux. I saw it was in the disabled packages. What do I need to build it on Termux

**Comment by fornwall** [comment]
It's not something that has been done yet - you can track it at https://github.com/termux/termux-packages/issues/324. In the meantime you can:

1. Use ecj, the eclipse java compiler which works a lot like javac, to compile to java bytecode.
2. Use the [jack compiler](https://source.android.com/source/jack.html) to compile to dex code directly for running on Android.

**Comment by parind** [comment]
Thank you @fornwall for letting me know. I was aware of the New Jack & Jill Compilers but the thing I wasn't aware was that it was added to Termux days before. Keep up for the good work.
