### ISSUE TITLE
Arm-none-eabi-gcc with march

### ISSUE THREAD

**Issue by Ti64CLi** [termux/termux-packages#5100]
**Problem description**

I'm currently trying to install the Ndless SDK (https://github.com/ndless-nspire/Ndless/wiki/Ndless-SDK:-C-and-assembly-development-introduction) to build program for the Nspire calcs. 
After installing all the required packages, I start the build with ./build_toolchain.sh. 
But when it tries to compile Newlib, after building GCC (Step 1) it doesn't work. 
And for some Arm-none-eabi-gcc, I got a -march=armv7+fp which isn't in the .sh file so I was wondering why does Termux automatically add this -march option, and how can I remove it? 
Because of this I get warnings about conflicts between -mcpu=arm926ej-s and -march=armv7+fp, and the build cannot complete. 
At the end of the build Newlib, termux displays rm cannot complete because directory not empty. 

**Steps to reproduce**

Just try to install the ndless sdk, as said at https://github.com/ndless-nspire/Ndless/wiki/Ndless-SDK:-C-and-assembly-development-introduction

**Expected behavior**

It should build fine and display done at the end

**Additional information**

```
Packages CPU architecture:
aarch64                                                 
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list) 
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
Running as root. Cannot check package updates.
Android version:
9
Kernel build information:
Linux ANDRAX-Mobile-Pentest 4.4.153-perf+ #1 SMP PREEMPT Tue Jan 14 23:06:30 WIB 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 7
```

**Comment by Grimler91** [comment]
The instructions you are following are valid for GNU/Linux and macos, termux is not GNU/Linux so you will probably need to patch quite a lot of things to get that SDK working.

Have you installed GCC or are you compiling with clang?

> -mcpu=arm926ej-s and -march=armv7+fp

You can give -march and -mcpu values as flags to the compiler. See https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html for info on all flags and possible values.

> At the end of the build Newlib, termux displays rm cannot complete because directory not empty.

This sounds like an error in the script you are running.
Open an issue in ndless repository and ask for help there. Maybe even ask them to provide instructions for termux.

I will close this as I can not really see a termux-related problem but rather problems due to the script you are running not supporting android&termux.

I also notice 

> Running as root. Cannot check package updates.

Why are you running as root? That is not necessary unless you are using termux-root-packages tools. You can install packages and compile things just fine without root.

**Comment by Ti64CLi** [comment]
I know you closed this issue but I want to clear some points.
I installed Debian through termux and I'm using it to run my script.
And yes I installed GCC, not clang. 
For the -march and -mcpu conflicts, I meant that in the script build_toolchain.sh and the others there is no - march flag. So it is Termux or Debian through Termux that is adding it. 
So my very question was to know how to deal with this not wanted flag. 
And I didn't know for the root stuff, thanks for that precision.

**Comment by Grimler91** [comment]
If you have installed debian in termux then you have the standard glibc and the script should probably work. 

Termux is not involved at all in this case so the flags comes from the script or debian's gcc.

> For the rm error I don't think it's an error in my script.

It's not a termux error if you are running in debian (it's either an error in the ndless script or in debian) so nothing we in the termux repo can do to fix this

**Comment by xeffyr** [comment]
> So it is Termux or Debian through Termux that is adding it.

It is default GCC configuration, i.e. set as default during toolchain build time.

**Comment by Ti64CLi** [comment]
What do I have to edit?

**Comment by Ti64CLi** [comment]
> If you have installed debian in termux then you have the standard glibc and the script should probably work.
> 
> Termux is not involved at all in this case so the flags comes from the script or debian's gcc.
> 
> > For the rm error I don't think it's an error in my script.
> 
> It's not a termux error if you are running in debian (it's either an error in the ndless script or in debian) so nothing we in the termux repo can do to fix this

Thanks a lot for taking the time to answer me.

**Comment by Ti64CLi** [comment]
@xeffyr Up

**Comment by xeffyr** [comment]
@Ti64CLi Check output of
```
arm-none-eabi-gcc -c -Q --help=target | grep march
```

If there is really wrong architecture, e.g. `armv7+fp` or similar, try to edit the build script and add `-march` option with correct architecture which won't conflict with `-mcpu` to https://github.com/ndless-nspire/Ndless/blob/62bf99d4f1ae1a342bb1d234179f7cf36dcc2671/ndless-sdk/toolchain/build_toolchain.sh#L23.

**Comment by Ti64CLi** [comment]
@xeffyr Thanks a lot for your answers
