### ISSUE TITLE
URL not showing

### ISSUE THREAD

**Issue by AbirHasan2005** [termux/termux-packages#5103]
I was using shellphish tool and I requested for generating an URL. But the URL not showing.

**Comment by xeffyr** [comment]
Serveo is disabled because of you, phishers...
![Screenshot_2020-03-31_14-02-30](https://user-images.githubusercontent.com/25881154/78019466-6bbbaf80-7358-11ea-816e-c729a9109587.png)

URL will never be shown ;)

**Comment by xeffyr** [comment]
Even though there is mentioned that it disabled only for "few days", the real amount of time is unspecified and most likely forever.
