### ISSUE TITLE
metasploit: msfconsole startup script incorrect db management

### ISSUE THREAD

**Issue by ilyapashuk** [termux/termux-packages#5104]
in last version of metasploit package the msfconsole start script does automatic db startup and creation, if needed, if called as msfconsole.
this code restarts db on any msfconsole call, that can be unwanted in multi instance scenarios because can break existing connections.
you should check that the db not running already, by trying to request it with psql tool, and make this behavior manageable by, for example, that way
if [[ ! -e $PREFIX/etc/metasploit-noautodb ]]; then
echo automaticly starting the db, create file $PREFIX/etc/metasploit-noautodb to disable this
db restart code
fi

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/unstable-packages/commit/0722983892770929e4841174eea75d30d0bfb0a3.
