### ISSUE TITLE
Failed to connect to main.termux-mirror.ml

### ISSUE THREAD

**Issue by LyaNolya** [termux/termux-packages#5105]
$ pkg update
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:4 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:6 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:6 https://dl.bintray.com/grimler/science-packages-24 science Release
Err:1 https://main.termux-mirror.ml stable InRelease
   Failed to connect to main.termux-mirror.ml port 443: Connection timed out
Reading package lists... Done
Building dependency tree... Done
All packed are up to date.
W: Failed to fetch https://termux.org/packages/dists/stable/InRelease Failed to connect to main.termux-mirror.ml port 443: Connection timed  out
W: Some index files failed to download. They have been ignored , or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

UPD: There is still a problem when I write to the terminal the text is not displayed until I put a space or press enter

**Comment by Grimler91** [comment]
> UPD: There is still a problem when I write to the terminal the text is not displayed until I put a space or press enter

For keyboard problem see https://github.com/termux/termux-app/issues/686

**Comment by xeffyr** [comment]
> Failed to connect to main.termux-mirror.ml port 443: Connection timed out

Probably your ISP blocks CloudFlare CDN. If so, nothing can be done with that.
I have to use CDN to avoid big charges for traffic.

**Comment by uDude** [comment]
Yeah, No.  I use a vpn and just poped out from 4 different countries --- Every single one gave

Failed to fetch http://main.termux-mirror.ml/dists/stable/InRelease  403  Forbidden [IP: 13.248.148.254 80]

In dns, w are always mapped to ww38.  I've waited a year for a fix.

**Comment by xeffyr** [comment]
@uDude termux-mirror.ml has been shutdown on 5 Mar as part of switching to IPFS from plain web hosting. It also no longer controlled by me, so don't use it.

**Comment by m3rcyz** [comment]
> @uDude termux-mirror.ml has been shutdown on 5 Mar as part of switching to IPFS from plain web hosting. It also no longer controlled by me, so don't use it.

then what should i do to update termux, as it is not installing packages normally?

**Comment by Grimler91** [comment]
@m3rcyz switch to another mirror with `termux-change-repo`. Available mirrors are listed here: https://github.com/termux/termux-packages/wiki/Mirrors
