### ISSUE TITLE
dpkg: error processing archive openport_1.1.0-1_i386.deb (--install):  package architecture (i386) does not match system (arm) Errors were encountered while processing:  openport_1.1.0-1_i386.deb

### ISSUE THREAD

**Issue by Caleb2330** [termux/termux-packages#5106]
Open port is refusing to be installed manually

**Comment by RossComputerGuy** [comment]
Please use the issue template.

**Comment by Grimler91** [comment]
You cannot install debs for the wrong architecture (i386 instead of arm), and you also cannot install debs compiled for other distros as [termux is not a GNU/Linux system](https://wiki.termux.com/wiki/Differences_from_Linux)
