### ISSUE TITLE
Error While Updating.

### ISSUE THREAD

**Issue by Spoiled-Ops** [termux/termux-packages#5109]
I am getting the below error.
I have tried the gateways. But the same thing rises. 

I have tried these

`  mkdir -p $PREFIX/etc/apt/sources.list.d
echo 'deb https://cloudflare-ipfs.com/ipfs/QmVAkuhfFfLBeTKCYYXWBvb3WxgZqDvd8qd7cvQjyrSvhr/ stable main' \
> $PREFIX/etc/apt/sources.list.d/temp_outage.list `

[Err:14 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release   404  Not Found Reading package lists... Done E: The repository 'https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release' does not have a Release file. N: Updating from such a repository can't be done securely, and is therefore disabled by default. N: See apt-secure(8) manpage for repository creation and user configuration details.]()  Err:14 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release

  404  Not Found
Reading package lists... Done

**Comment by Grimler91** [comment]
Replace `https://dl.bintray.com/xeffyr/unstable-packages-24` with `https://dl.bintray.com/xeffyr/unstable-packages` in whatever file you have in `$PREFIX/etc/apt/sources.list.d/`

**Comment by xeffyr** [comment]
@Spoiled-Ops If mirror is not mentioned on https://github.com/termux/termux-packages/wiki/Mirrors, then it is no longer valid.

**Comment by Spoiled-Ops** [comment]
Issue Solved Thanks a Lot
