### ISSUE TITLE
mpv dosen't work on nougat

### ISSUE THREAD

**Issue by twosky2000** [termux/termux-packages#511]
mpv dosen't work on android n.
After i updatet my nexus 6p, i can't open audiostreams:
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/mpv": cannot locate symbol "lzma_stream_decoder" referenced by "/data/data/com.termux/files/usr/lib/libavcodec.so"...
Aborted

**Comment by its-pointless** [comment]
Well the easy solution is to simply not allow ffmpeg to link against termux lzma. Tested that and it works on my arm nougat test device.

**Comment by fornwall** [comment]
@twosky2000 @its-pointless Thanks - run `apt update && apt upgrade` to get the updated ffmpeg package!
