### ISSUE TITLE
404 error on one of the pkg repos' Release files

### ISSUE THREAD

**Issue by badprogramshere** [termux/termux-packages#5117]
Trying to install a package using pkg gives me an error involving a 404 Not Found in a Release file.
$ pkg update
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:4 https://dl.bintray.com/xeffyr/x11-packages-24 x11 InRelease
Get:5 https://dl.bintray.com/termux/termux-packages-24 stable Release [6061 B]
Hit:5 https://dl.bintray.com/termux/termux-packages-24 stable Release
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:8 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:8 https://dl.bintray.com/grimler/science-packages-24 science Release
Err:10 https://dl.bintray.com/xeffyr/x11-packages-24 x11 Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://dl.bintray.com/xeffyr/x11-packages-24 x11 Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

My version is 0.94 running on Android 9

**Comment by badprogramshere** [comment]
I realised that I had the X11 repo installed - I guess it's no longer being maintained

**Comment by Grimler91** [comment]
The URL was changed [a few months ago](https://github.com/termux/termux-packages/commit/bf7187f61260ff6589084c45b49c00cd4a789c5c#diff-2f383386333fd98db35bcd130bbc574e).
It is still maintained.
