### ISSUE TITLE
Package Request: libopencv-dev

### ISSUE THREAD

**Issue by rafis** [termux/termux-packages#512]
libopencv-dev please from 2.4.9 to 2.4.13, not 3.x branch.

**Comment by rafis** [comment]
I have found it is easy to compile by myself, so this is low priority:

    apt install cmake pkg-config
    apt install libjpeg-turbo-dev libpng-dev
    wget -O opencv-2.4.13.zip http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.13/opencv-2.4.13.zip/download
    unzip opencv-2.4.13
    cd opencv-2.4.13
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr/local -DWITH_GTK=OFF -DWITH_1394=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DWITH_JPEG=ON -DBUILD_JPEG=OFF ..

Now need to connect to camera somehow. I can use termux-api's `termux-camera-photo`, but it saves photo to a file which drains internal flash or MicroSD and overall this will be very slow. Need direct streaming from camera to OpenCV somehow.

**Comment by mgupte** [comment]
When I follow these steps to build on termux I get file not found for sysctl.h file.  Any idea?

**Comment by vishalbiswas** [comment]
@mgupte change the include directive from `#include <sysctl.h>` to `#include <linux/sysctl.h>`

**Comment by mgupte** [comment]
Tried this but it gives lot of errors while compiling system.cpp

**Comment by johncant** [comment]
I get

```
%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/algorithm.cpp.o            clang-5.0: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
In file included from /data/data/com.termux/files/home/opencv-2.4.13/modules/core/src/algorithm.cpp:43:                                            In file included from /data/data/com.termux/files/home/opencv-2.4.13/modules/core/src/precomp.hpp:48:                                              In file included from /data/data/com.termux/files/home/opencv-2.4.13/modules/core/include/opencv2/core/core.hpp:4921:                              /data/data/com.termux/files/home/opencv-2.4.13/modules/core/include/opencv2/core/operations.hpp:74:16: fatal error:                                      'ext/atomicity.h' file not found                 #include <ext/atomicity.h>                                ^~~~~~~~~~~~~~~~~                 1 error generated.                               make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:63: modules/core/CMa
```

Sorry, for above dump, I'll format it later

**Comment by siriuslzx** [comment]
> I have found it is easy to compile by myself, so this request is low priority:
> 
> ```
> apt install cmake pkg-config
> apt install libjpeg-turbo-dev libpng-dev
> wget -O opencv-2.4.13.zip http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.13/opencv-2.4.13.zip/download
> unzip opencv-2.4.13
> cd opencv-2.4.13
> mkdir build
> cd build
> cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr/local -DWITH_GTK=OFF -DWITH_1394=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DWITH_JPEG=ON -DBUILD_JPEG=OFF ..
> make && make install
> ```
> 
> Now need to connect to camera somehow. I can use termux-api's `termux-camera-photo`, but it saves photo to a file which drains internal flash or MicroSD and overall this will be very slow. Need direct streaming from camera to OpenCV `VideoCapture::open()` somehow.

excuse me, have you found a way to direct streaming from camera to OpenCV?

**Comment by wahyubram82** [comment]
@xeffyr :
I found [this](https://github.com/Yoline777/AidLearning?files=1):
it's using termux but have a great features like camera access (streaming), opencv, many  ML/DL framework already installed on it. even..., source list straight to debian.

can you learn it...., how it works and share to us how to do that....?

**Comment by xeffyr** [comment]
> can you learn it

It is just Termux-based app running Debian stretch inside proot.
Camera access is done via Android API and communication with framework is done over sockets. GUI seems printed via WebView.

Application is too far from production use. There even developer's ssh key was left as authorized (intentionally ???):
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLQgFhbmBNG+mxcldTQ8tufrQDsjlCA95KuN0uTxM8GAe8W2e2/5ddAZmJLNPHWvhLTevpUPW5V7qQVL9QH4isbSxX0+X3xtUrBmsn49blJrb3+1qbbhcayHcbi7cANpxnQT9jcdFpPW3VfuW4jQDcNwHtqJhSNdd3+KTYKSkd+IlrOvirVsMg/iHRwZU1ns4Y2KHHiwWiP4k85pTx0Lp3Bb4WeBU2Grs1foiJrZ/PjdPWqmbU3zVH5FqT0ES5kyq5PuIi/ugutuLrM6dV8NYIblGDK9YRc95AZbdoMAPYf4Xheq9KWXLeL2rNJSL/adEep2JygTxGZoVcn3mkYUzt sunyimac@billsdeMacBook-Pro.local
```

It also freeze my device on webview launch. Had to reboot after using it.

**Comment by fahadali32** [comment]
I got same error dlopen falied no what can i do please help me to fix it .....

**Comment by Paresh-Kumar-Hansda** [comment]
> I have found it is easy to compile by myself, so this request is low priority:
> 
> ```
> apt install cmake pkg-config
> apt install libjpeg-turbo-dev libpng-dev
> wget -O opencv-2.4.13.zip http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.13/opencv-2.4.13.zip/download
> unzip opencv-2.4.13
> cd opencv-2.4.13
> mkdir build
> cd build
> cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr/local -DWITH_GTK=OFF -DWITH_1394=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DWITH_JPEG=ON -DBUILD_JPEG=OFF ..
> make && make install
> ```
> 
> Now need to connect to camera somehow. I can use termux-api's `termux-camera-photo`, but it saves photo to a file which drains internal flash or MicroSD and overall this will be very slow. Need direct streaming from camera to OpenCV `VideoCapture::open()` somehow.

cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr/local -DWITH_GTK=OFF -DWITH_1394=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DWITH_JPEG=ON -DBUILD_JPEG=OFF ..                                 -- Detected processor: armv7l
-- Looking for ccache - not found
-- NEON is not supported by C++ compiler
-- FP16 is not supported by C++ compiler
-- Could NOT find OpenJPEG (minimal suitable version: 2.0, recommended version >= 2.3.1). OpenJPEG will be built from sources
-- OpenJPEG: VERSION = 2.3.1, BUILD = opencv-4.5.1-dev-openjp2-2.3.1
-- OpenJPEG libraries will be built from sources: libopenjp2 (version "2.3.1")
-- math lib 'libm' not found; floating point support disabled
CMake Error at cmake/android/OpenCVDetectAndroidSDK.cmake:49 (message):
  Android SDK: specify path to Android SDK via ANDROID_SDK_ROOT /
  ANDROID_HOME / ANDROID_SDK variables
Call Stack (most recent call first):
  cmake/android/OpenCVDetectAndroidSDK.cmake:172 (ocv_detect_android_sdk)
  CMakeLists.txt:723 (include)


-- Configuring incomplete, errors occurred!
See also "/data/data/com.termux/files/home/opencv/build/CMakeFiles/CMakeOutput.log".
See also "/data/data/com.termux/files/home/opencv/build/CMakeFiles/CMakeError.log".
$

**Comment by Paresh-Kumar-Hansda** [comment]
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr/local -DWITH_GTK=OFF -DWITH_1394=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DWITH_JPEG=ON -DBUILD_JPEG=OFF ..                                 -- Detected processor: armv7l
-- Looking for ccache - not found
-- NEON is not supported by C++ compiler
-- FP16 is not supported by C++ compiler
-- Could NOT find OpenJPEG (minimal suitable version: 2.0, recommended version >= 2.3.1). OpenJPEG will be built from sources
-- OpenJPEG: VERSION = 2.3.1, BUILD = opencv-4.5.1-dev-openjp2-2.3.1
-- OpenJPEG libraries will be built from sources: libopenjp2 (version "2.3.1")
-- math lib 'libm' not found; floating point support disabled
CMake Error at cmake/android/OpenCVDetectAndroidSDK.cmake:49 (message):
  Android SDK: specify path to Android SDK via ANDROID_SDK_ROOT /
  ANDROID_HOME / ANDROID_SDK variables
Call Stack (most recent call first):
  cmake/android/OpenCVDetectAndroidSDK.cmake:172 (ocv_detect_android_sdk)
  CMakeLists.txt:723 (include)


-- Configuring incomplete, errors occurred!
See also "/data/data/com.termux/files/home/opencv/build/CMakeFiles/CMakeOutput.log".
See also "/data/data/com.termux/files/home/opencv/build/CMakeFiles/CMakeError.log".
$

**Comment by Paresh-Kumar-Hansda** [comment]
Not working

**Comment by Fann-level-MAX** [comment]
> I get
> 
> ```
> Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/algorithm.cpp.o
>             clang-5.0: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
> In file included from /data/data/com.termux/files/home/opencv-2.4.13/modules/core/src/algorithm.cpp:43:                                            
> In file included from /data/data/com.termux/files/home/opencv-2.4.13/modules/core/src/precomp.hpp:48:                                              
> In file included from /data/data/com.termux/files/home/opencv-2.4.13/modules/core/include/opencv2/core/core.hpp:4921:
>                               /data/data/com.termux/files/home/opencv-2.4.13/modules/core/include/opencv2/core/operations.hpp:74:16: fatal error:
>                                       'ext/atomicity.h' file not found
>                  #include <ext/atomicity.h>
>                                ^~~~~~~~~~~~~~~~~                 1 error generated.                               make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:63: modules/core/CMa
> ```
> 
> I understand this is to do with different versions of the C++ standard library?

have you found the solution for it?
I'm facing with same problem here
