### ISSUE TITLE
How to install keras on termux

### ISSUE THREAD

**Issue by delmarocks** [termux/termux-packages#5120]
I'm trying to install keras on termux but failed due to h5py error as its package requirement. Does anyone solved it already?
![pip3 install h5py error](https://i.imgur.com/WYuR4sM.jpg)

**Comment by Grimler91** [comment]
Do you have libhdf5 installed?

**Comment by delmarocks** [comment]
@Grimler91 yes I have installed it as well as its static library

**Comment by delmarocks** [comment]
![](https://i.imgur.com/yi26ksI.jpg)

**Comment by Grimler91** [comment]
Your screenshot does not contain any information about the actual error. Please post (or upload somewhere) the full output, and provide the information requested in the [bug report template](https://github.com/termux/termux-packages/issues/new?template=bug_report.md)

**Comment by Grimler91** [comment]
The problem is probably that h5py does not support libhdf 1.12 yet: https://github.com/h5py/h5py/issues/1504

**Comment by KangKazumi** [comment]
Is there anyone having libhdf 1.10 deb.

**Comment by KangKazumi** [comment]
Is there anyone having libhdf 1.10 deb ?

**Comment by delmarocks** [comment]
> Your screenshot does not contain any information about the actual error. Please post (or upload somewhere) the full output, and provide the information requested in the [bug report template](https://github.com/termux/termux-packages/issues/new?template=bug_report.md)

[keras.log](https://github.com/termux/termux-packages/files/4444328/keras.log)

**Comment by delmarocks** [comment]
@Grimler91 where can i get the outdated version of libhdf

**Comment by Grimler91** [comment]
@KangKazumi @delmarocks you can download it here temporarily: https://grimler.se/dists/testing/misc/binary-aarch64/libhdf5_1.10.6_aarch64.deb (replace aarch64 by your arch if you are on another arch)

**Comment by delmarocks** [comment]
@Grimler91 thankyou for your response I'll try it out

**Comment by delmarocks** [comment]
@Grimler91 downgrading libhdf with your link successfully installed h5py as well as keras. Thankyou😊
![](https://i.imgur.com/hQyWDQo.jpg)

**Comment by KangKazumi** [comment]
@Grimler91 
I finally and successfully installed h5py !
Thanks a million for your help.（*＾ワ＾*）
