### ISSUE TITLE
msfconsole not open

### ISSUE THREAD

**Issue by royaldesigner** [termux/termux-packages#5126]
$ msfconsole
2020-04-05 18:08:58.007 IST [22569] LOG:  starting PostgreSQL 12.2 on arm-unknown-linux-androideabi, compiled by Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn), 32-bit
2020-04-05 18:08:58.011 IST [22569] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-04-05 18:08:58.018 IST [22569] LOG:  listening on Unix socket "/data/data/com.termux/files/usr/tmp/.s.PGSQL.5432"
2020-04-05 18:08:58.150 IST [22573] LOG:  database system was shut down at 2020-04-05 18:08:57 IST
2020-04-05 18:08:58.428 IST [22569] LOG:  database system is ready to accept connections
Traceback (most recent call last):
        16: from /data/data/com.termux/files/usr/opt/metasploit-framework/msfconsole:46:in `<main>'
        15: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        14: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        13: from /data/data/com.termux/files/usr/opt/metasploit-framework/config/boot.rb:28:in `<top (required)>'
        12: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        11: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        10: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:10:in `<top (required)>'
         9: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
         8: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
         7: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:10:in `block in <top (required)>'
         6: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/bundler.rb:149:in `setup'
         5: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:22:in `setup'
         4: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
         3: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
         2: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/bundler/rubygems_integration.rb:223:in `bin_path'
         1: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/rubygems.rb:252:in `bin_path'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /data/data/com.termux/files/usr/opt/metasploit-framework/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
$

**Comment by xeffyr** [comment]
Make sure that bundler of right version is installed
```
gem install --no-document --verbose bundler:1.17.3
```
