### ISSUE TITLE
Add metapackages (like build-essential)

### ISSUE THREAD

**Issue by mklein994** [termux/termux-packages#513]
Metapackages (https://help.ubuntu.com/community/MetaPackages) will make installing a lot of packages on a new device a lot easier. Along with build-essential (which of course would include clang, make, sed, gawk, etc.), we could also include categories such as editors, games, image manipulation tools, music players and so on.

**Comment by xeffyr** [comment]
Package is now available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install build-essential
```
