### ISSUE TITLE
Package request: Antibody

### ISSUE THREAD

**Issue by ibnishak** [termux/termux-packages#5130]
[Antibody ](https://github.com/getantibody/antibody ) is a plug in manager for zsh

Built successfully in zsh without issues or additional patches

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install antibody
```

**Comment by ibnishak** [comment]
Brilliant. Thanks a lot

**Comment by ibnishak** [comment]
Is there a guide to creating PRs towards termux packages?

**Comment by xeffyr** [comment]
Mostly https://github.com/termux/termux-packages/wiki/Creating-new-package however do not expect that packaging to Termux is a strightforward process. Termux isn't standard GNU/Linux system, there a lot of differences from typical Linux distro.
