### ISSUE TITLE
Feature: termux sdk

### ISSUE THREAD

**Issue by aristarh2704** [termux/termux-packages#5132]
I need  special toolchain for compiling new packages for termux. I think, it's possible create termux sdk, as package. just as it is done for android: android sdk is independent toolchain

**Comment by aristarh2704** [comment]
I know, that scripts in this repository download android ndk and paths it. I need a script, which do only it and nothing more

**Comment by Grimler91** [comment]
Do you want to compile program into .debs or just compile and install them? 

[build-package.sh](https://github.com/termux/termux-packages/blob/master/build-package.sh) already supports the latter for some packages, but compiling and installing most programs is very straightforward, just `./configure --prefix $PREFIX && make && make install` and you are done. 

For compiling into debs you can simply compile a program and then use [termux-create-package](https://github.com/termux/termux-create-package) to put them in a .deb. It will be possible to do this with build-package.sh as well once this PR is fixed&merged: https://github.com/termux/termux-packages/pull/5004.

termux-ndk, similar to android-ndk, does not make sense. An ndk is only used when compiling for another platform/architecture.
