### ISSUE TITLE
Duplicated package: 8086tiny

### ISSUE THREAD

**Issue by aristarh2704** [termux/termux-packages#5133]
buildorder.py returns "ERROR: Duplicated package: 8086tiny" on any building

**Comment by xeffyr** [comment]
This is not possible unless you did some modifications for build scripts or packages.

**Comment by aristarh2704** [comment]
I tried compile any package on clean repo, without changing on Ubuntu 20

**Comment by xeffyr** [comment]
> on Ubuntu 20

We expect Ubuntu 19.10 or 18.04 (in worst case). With all build environment dependencies installed (`./scripts/setup-ubuntu.sh`).

Use Docker image as only it guaranteed to work as expected.
