### ISSUE TITLE
Permission issues or support issues

### ISSUE THREAD

**Issue by Alan996** [termux/termux-packages#5139]
**When i start Ubuntu ,always have some problems in here or there .No1: using apt —fix-broken install command, will notify can’t connect snap store .i using Global proxy by Hong Kong .but it also can’t connect. And the process unable proceed. I discover a lot of this issue discussion in internet form china, if you read , thanks you to tell me**

**No2: after using termux-chroot Command, start Ubuntu will very slowly.. and notify :“ proot warning : can't sanitize binding "/sdcard": no such file or directory proot info : vpid 1: terminated with signal 4 “, is it possible can’t using termux-chroot before start ubuntu?**

**my device is xiaomi10 by android 10,and i slso try that in android8,they have same situation**

**no pic ,sorry**

```

```

**Comment by RalfWerner** [comment]
> to: No 2 ... very slowly

`termux-chroot` is a` proot` wrapper and I guess you start Ububntu with `proot` as well. But you should only use `proot` _**once.**_ I also had problems with tiled ones and you didn't need them.

**Comment by xeffyr** [comment]
> can’t connect snap store

Forget about using snap under proot. It will never work as requires *a true root access*.

> after using termux-chroot Command, start Ubuntu will very slowly

Yes, it will be slow as each `proot` nesting will slow down execution by n^2 times. You should either use `termux-chroot` or Ubuntu but not these 2 things in same session.

**Comment by Alan996** [comment]
okya😊2020年4月10日 20:30，Leonid Plyushch <notifications@github.com>写道：
Closed #5139.
