### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by nwf** [termux/termux-packages#514]
I attempted to build all packages inside docker and found that packages depending on libpng (thus far, `optipng` and `aapt`) died with

/data/data/com.termux/files/usr/lib/libpng.so: undefined reference to `frexp@LIBC'
/data/data/com.termux/files/usr/lib/libpng.so: undefined reference to `modf@LIBC'
/data/data/com.termux/files/usr/lib/libpng.so: undefined reference to `pow@LIBC'

Possibly something has changed upstream?

**Comment by fornwall** [comment]
Yes, there has been a change in that versioned symbols are stripped from system libraries before building packages.

You need to rebuild libpng so that it does not contain versioned symbols from libm - after that you should be able to build packages depending on it!
