### ISSUE TITLE
dpkg errors

### ISSUE THREAD

**Issue by premdev28** [termux/termux-packages#5146]
whe  i run apt update errors comes like
E: Could not open file /data/data/com.termux/files/usr/var/lib/dpkg/status - open (13: Permission denied)
E: Problem opening /data/data/com.termux/files/usr/var/lib/dpkg/status
E: The package lists or status file could not be parsed or opened.

**Comment by Grimler91** [comment]
Looks like you have used apt as root and messed up permission. Run `rm -rf $PREFIX` and restart the app to get a fresh PREFIX.
