### ISSUE TITLE
ssl-cert-check

### ISSUE THREAD

**Issue by EdoZullo** [termux/termux-packages#5147]
Hello, is possible to build a package of **ssl-cert-check**? I turn an unused device as a domotic HUB via termux, this little script can help to warn you when certificate expire so you can keep to access to your home remotly.
ssl-cert-check is a Bourne shell script that can be used to report on expiring SSL certificates.
https://github.com/Matty9191/ssl-cert-check

Thank you.

**Comment by xeffyr** [comment]
> is a Bourne shell script

And every requested script should be turned into package ?

**Comment by EdoZullo** [comment]
Maybe to help newbies.

**Comment by normanr** [comment]
What xeffyr maybe meant is that bash scripts don't need to be compiled (only bash does) and so they don't need their own package. Just download the script and run it directly.

**Comment by xeffyr** [comment]
I'd like to avoid having dedicated packages for scripts due to fact that we will start [packaing in APKs](https://github.com/termux/termux-app/pull/1427) soon in order to solve https://github.com/termux/termux-app/issues/1072.
