### ISSUE TITLE
modprobe not installed

### ISSUE THREAD

**Issue by premdev28** [termux/termux-packages#5150]
when i run airmon-ng commands it shows

Your kernel has module support but you don't have modprobe installed.
It is highly recommended to install modprobe (typically from kmod).
Your kernel has module support but you don't have modinfo installed.
It is highly recommended to install modinfo (typically from kmod).
Warning: driver detection without modinfo may yield inaccurate results.
Your kernel supports rfkill but you don't have rfkill installed.
To ensure devices are unblocked you must install rfkill

but  modprobe, modinfo are already in the /system/bin/

**Comment by Grimler91** [comment]
It's just a warning. If you have modprobe and friends in /system/bin you can run them from there.
