### ISSUE TITLE
Lag when typing 

### ISSUE THREAD

**Issue by jalalkun** [termux/termux-packages#5154]
**Problem description**
Just lag when typing ing termux

**Steps to reproduce**
I'm open termux
I typing ping drive.google.com but I'm typo in google, delete typo and continue typing and the result is bad

**Expected behavior**
Not lagging and not wrong typed 

**Additional information**
Device : Samsung A50s
Processor:  exynos 9611
Ram : 6
Storage: 128 
Android 10

I'm attached my record
https://drive.google.com/file/d/1L3OwJXeHZhAtSIWE7CkzXMu22_uLha6B/view?usp=drivesdk

**Comment by xeffyr** [comment]
I'm closing this issue as it has same origin as https://github.com/termux/termux-app/issues/686.
