### ISSUE TITLE
Can no longer cross compile

### ISSUE THREAD

**Issue by easyaspi314** [termux/termux-packages#5155]
**Problem description**

Likely regression caused by #5095.

Recent updates made cross compiling a lot more difficult than it was before, as `ld.lld` always tries to link `$PREFIX/lib/crtbegin_*.o` and `$PREFIX/lib/crtend_android.o`. 
```
ld.lld: error: /data/data/com.termux/files/usr/bin/../lib/crtbegin_static.o is incompatible with elf_i386
ld.lld: error: /data/data/com.termux/files/usr/bin/../lib/crtend_android.o is incompatible with elf_i386
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```
Now, the only way I managed to link a binary is to manually call `ld.lld` with the correct object file order, which is inconvenient to say the least.

**Steps to reproduce**
1. Install ndk-multilib
2. Create a simple C file.
```c
#include <stdio.h>
int main(void)
{
    puts("Hello, world!");
}
```
3. Cross compile using `ld.lld` (or `ld.bfd` for ARMv7 on AArch64)
```
clang --target=i686-linux-android -static -fuse-ld=$(which ld.lld) hello.c -o hello
```

**Expected behavior**

It compiles and links as it did in previous versions.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
Updatable packages:
libcairo/stable 1.16.0-6 aarch64 [upgradable from: 1.16.0-2]
pulseaudio/stable 13.0-1 aarch64 [upgradable from: 12.2-21]
Android version:
10
Kernel build information:
Linux localhost 4.4.200-g11566f2bfb0e #1 SMP PREEMPT Wed Jan 8 08:16:10 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 2 XL

```

**Comment by buttaface** [comment]
You're right. I think this is because while I tested building some basic ndk-multilib binaries, I didn't test that pull by building the libllvm Termux package from scratch. Rather I used the clang checkout for Swift that I already had built in my home directory, so an incremental rebuild was easy, but I see now that more linker paths may be added if the compiler is stored in the sysroot. Pull forthcoming, which I'll test with such a Termux package setup first.
