### ISSUE TITLE
watch does not show any Unicode characters

### ISSUE THREAD

**Issue by normanr** [termux/termux-packages#5158]
echo '£¢€¥^°%©®™✓' shows expected output
watch echo '£¢€¥^°%©®™✓' only shows ^%

Adding --enable-watch8bit to TERMUX_PKG_EXTRA_CONFIGURE_ARGS in https://github.com/termux/termux-packages/blob/master/packages/procps/build.sh should fix it (ref: https://bugs.archlinux.org/task/38614)

**Comment by Grimler91** [comment]
Thanks for researching it!
