### ISSUE TITLE
dpkg-deb error installing libgccjit-9-dev on top of libgccjit-8-dev

### ISSUE THREAD

**Issue by HafizZiq** [termux/termux-packages#5159]
any help regarding this?
Or the rules is can't flash new version on top of old one?

`u0_a229@localhost ~> pkg install libgccjit-9-dev -y`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`The following NEW packages will be installed:`
`  libgccjit-9-dev`
`0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.`
`Need to get 0 B/5097 kB of archives.`
`After this operation, 16.8 MB of additional disk space will be used.`
`Selecting previously unselected package libgccjit-9-dev.`
`(Reading database ... 34553 files and directories currently installed.)`
`Preparing to unpack .../libgccjit-9-dev_9.3.0_arm.deb ...`
`Unpacking libgccjit-9-dev (9.3.0) ...`
`dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/libgccjit-9-dev_9.3.0_arm.deb (--unpack):`
` trying to overwrite '/data/data/com.termux/files/usr/lib/libgccjit.so.0.0.1', which is also in package libgccjit-8-dev 8.4.0`
`dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)`
`Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/libgccjit-9-dev_9.3.0_arm.deb`
`E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)`
`u0_a229@localhost ~ [100]>`

`u0_a229@localhost ~ [100]> termux-info`
`Packages CPU architecture:`
`arm`
`Subscribed repositories:`
`# sources.list`
`deb https://termux.org/packages/ stable main`
`# science-repo (sources.list.d/science.list)`
`deb https://dl.bintray.com/grimler/science-packages-24 science stable`
`# game-repo (sources.list.d/game.list)`
`deb https://dl.bintray.com/grimler/game-packages-24 games stable`
`# unstable-repo (sources.list.d/unstable.list)`
`deb https://dl.bintray.com/xeffyr/unstable-packages unstable main`
`# root-repo (sources.list.d/root.list)`
`deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable`
`# sources.list.d/pointless.list`
`deb https://its-pointless.github.io/files/24 termux extras`
`# x11-repo (sources.list.d/x11.list)`
`deb https://dl.bintray.com/xeffyr/x11-packages x11 main`
`Updatable packages:`
`All packages up to date`
`Android version:`
`9`
`Kernel build information:`
`Linux localhost 3.4.113-LolZ-V14 #1 SMP PREEMPT Sun Feb 9 01:19:17 UTC 2020 armv7l Android`
`Device manufacturer:`
`samsung`
`Device model:`
`SM-N9005`
`u0_a229@localhost ~>`

**Comment by Grimler91** [comment]
You can't have both versions installed at the same time, choose one
