### ISSUE TITLE
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/http/client.rb:96: warning: deprecated Object#=~ is called on FalseClass; it always returns nil

### ISSUE THREAD

**Issue by Fawniaus** [termux/termux-packages#5160]
When i starts metasploit it show up to me,and when i use some module it show up again.How to fix this? And why to be this? Thanks you.
I use Vivo1906 android9 
I download metasploit by using cammand:pkg install metasploit
![Screenshot_20200414_114314](https://user-images.githubusercontent.com/43487032/79186966-2eb9e780-7e45-11ea-82bb-4b7785e6f712.jpg)
![IMG_20200414_114427](https://user-images.githubusercontent.com/43487032/79187016-514c0080-7e45-11ea-8f01-95a0f230e191.JPG)

**Comment by Grimler91** [comment]
Activerecord is not a termux packages so open an issue in the activerecord repository instead.
