### ISSUE TITLE
Cannot install LaTeX packages!

### ISSUE THREAD

**Issue by harieamjari** [termux/termux-packages#5167]
**Problem description**

I'm  trying to update a LaTeX package using the command `tlmgr update pdfpages` and this gives me an error, 
```
/data/data/com.termux/files/usr/bin/tlmgr.ln: unexpected return value from verify_checksum: -5
```

Following some instruction, I then entered this, `tlmgr --verify-repo=none update pdfpages` and gave me again an error,
``` 
tlmgr.ln: Remote repository is newer than local (2019 < 2020)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details. 
```

Following again a new [instruction](https://tex.stackexchange.com/questions/537376/tlmgr-unexpected-return-value-from-verify-checksum-5-for-main-repository). I downloaded update-tlmgr-latest.sh, executed `./update-tlmgr-latest.sh -- --update`, then again an error,
```
Verifying archive integrity... All good.
Uncompressing TeX Live Manager Updater-kP: No such file or directory
./update-tlmgr-latest.sh: 453: test: Illegal number: 635.2M
  100%
./runme.sh: Cannot find TeX Live root using kpsewhich --var-value=SELFAUTOPARENT.
./runme.sh: (no tlpkg/texlive.tlpdb and/or tlpkg/tlpobj/.)
./runme.sh: Please set your PATH as needed, otherwise it's hopeless.
```
ran `kpsewhich --var value=SELFAUTOPARENT` and got `/data/data/com.termux/files`.
If you're wondering how I got pdfpages, I manually installed it by generating .sty using `latex *ins` and moving it to the directory where LaTeX could locate.

I'm pissed off. What should I do??

**Additional information**

```
find: ‘/data/data/com.termux/files/usr/etc/apt/sources.list.d’: No such file or directory
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
All packages up to date
Android version:
6.0.1
Kernel build information:
Linux localhost 3.18.19-15382149 #1 SMP PREEMPT Mon Feb 11 15:53:09 KST 2019 armv7l Android
Device manufacturer:
samsung
Device model:
SM-G532F
```

**Comment by Grimler91** [comment]
This is because texlive 2020 was released, texlive 2019 can then no longer access CTAN. 

It is not possible to use `update-tlmgr-latest.sh` or to install texlive with the `install-tl` script due to termux not being supported by the texlive infrastructure.

I see that you are on android 6, this means that the only way for you to get a working texlive (without compiling texlive yourself) is to install `texlive-full` instead of `texlive` + `texlive-tlmgr`.

**Comment by harieamjari** [comment]
I would like to, but my memory is really low. =(

I'll just stick with manual installing. Anyway, thanks for your advice.

**Comment by angelog0** [comment]
@Grimler91 wrote:

> It is not possible to use `update-tlmgr-latest.sh` or to install texlive with the `install-tl` script due to termux not being supported by the texlive infrastructure.

Why do you not [submit ](https://www.tug.org/texlive/build.html) patches/binaries to the TeXLive people?

**Comment by Grimler91** [comment]
@angelog0 I don't want to commit to maintaining/rebuilding those binaries. If anyone else wants to do that then that would be great.
