### ISSUE TITLE
Process complete (Signal 31) error

### ISSUE THREAD

**Issue by mnnlkml** [termux/termux-packages#5168]
**Problem description**

I don't know what is that problem in termux app, it is appear ``` [Process complete (signal 31) - press Enter]``` when I press enter termux app is closed

**Platform**
Android OS 9
Xiaomi Redmi 8 MIUI 11.0.10.0
using default shell zsh
Termux App Version 0.94
**Additional information**

```
[Process completed (signal 31) - press Enter]
```
![Screenshot_2020-04-18-05-44-43-923_com termux](https://user-images.githubusercontent.com/43625186/79623046-ce25f580-8137-11ea-98b4-95017ab7da17.jpg)

**Comment by kcubeterm** [comment]
Related issue https://github.com/termux/termux-packages/issues/3997

**Comment by mnnlkml** [comment]
this error occur because I am installed ``fzf fuzzy finder``` and using with ```zsh```, to avoid this error go
>  .zshrc  
and remove 
> fzf 
config source line code that's it.
