### ISSUE TITLE
ftp client segfaults

### ISSUE THREAD

**Issue by BorisCarvajal** [termux/termux-packages#517]
ftp (inetutils package) segfaults right after log in to a server.
Getting a file with wget or curl works fine.

Andorid 6.0.1 aarch64

**Comment by fornwall** [comment]
It works for me testing on an Android 6 aarch64 device, using ftp.gnu.org and `get README`. Does that one work for you? If so, do you have another public server where it crashes?

**Comment by BorisCarvajal** [comment]
Indeed that server works, after entering "anonymous" it just connect without asking a pass.
But for example check ftp.ca.debian.org, it also ask for a dummy pass and then crash, maybe
that is related with the issue, I don't know.

**Comment by fornwall** [comment]
Thanks a lot - it seems like the password prompt was indeed the problem!

Update with `apt update && apt upgrade` and let me know if it works after that!

**Comment by BorisCarvajal** [comment]
Awesome, it works.
Thank you!!

**Comment by fornwall** [comment]
For reference: Submitted upstream at http://lists.gnu.org/archive/html/bug-inetutils/2016-10/msg00000.html
