### ISSUE TITLE
Social mapper

### ISSUE THREAD

**Issue by RohitAdhikari088** [termux/termux-packages#5173]
**Package description**

**Link to home page and sources**
1. Home page: https://github.com/Greenwolf/social_mapper
2. Source code:
https://github.com/Greenwolf/social_mapper?files=1
**Additional information**
Have you compiled or tried to compile the package on device?
Yes
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by Grimler91** [comment]
We generally do not package python modules.

It also depends on firefox, geckodriver and selenium, which we don't have and are unlikely to add
