### ISSUE TITLE
Package Request: tsocks

### ISSUE THREAD

**Issue by lioliy** [termux/termux-packages#518]
tsocks Overview
SOCKS servers are a form of proxy that are commonly used in firewalled LAN environments to allow access between networks, and often to the Internet. The problem is that most applications don't know how to gain access through SOCKS servers. This means that network based applications that don't understand SOCKS are very limited in networks they can reach. An example of this is simple 'telnet'. If you're on a network firewalled from the internet with a SOCKS server for outside access, telnet can't use this server and thus can't telnet out to the Internet. 

tsocks' role is to allow these non SOCKS aware applications (e.g telnet, ssh, ftp etc) to use SOCKS without any modification. It does this by intercepting the calls that applications make to establish network connections and negotating them through a SOCKS server as necessary.

**Comment by lioliy** [comment]
I use android toolchain and build success.Can you add this app to termux-package?

**Comment by fornwall** [comment]
A `tsocks` package is now available (for 64-bit arches only - 32-bit arches are waiting for a build issue to get fixed).

**Comment by Temuxuser2021** [comment]
torify w3n https://check.torproject.org
/data/data/com.termux/files/usr/bin/torify: torsocks not found in your PATH.  Perhaps it isn't installed?  (tsocks is no longer supported for security reasons.).           Why its sowing to me ??

**Comment by xeffyr** [comment]
@Temuxuser2021 Install `torsocks` package and use it instead. If you are on Android 8 or higher, use `proxychains` as torsocks doesn't work on this OS versions.
