### ISSUE TITLE
No package provides tlmgr

### ISSUE THREAD

**Issue by dkoao** [termux/termux-packages#5181]
After installing `texlive`, I tried to run `tlmgr` but Termux instructed me to install `tlmgr` using `pkg install texlive-tlmgr`, when I try to do that, I end with the following error:

```
Package texlive-tlmgr is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source
However the following packages replace it:
  texlive

E: Package 'texlive-tlmgr' has no installation candidate
```

**Comment by Grimler91** [comment]
I removed it (and have not updated the installation instructions on the wiki yet). I will add an installer package to the unstable-packages repository that can be used to install texlive through the native install-tl script and get tlmgr. 

So, it is not possible to install tlmgr for now.

**Comment by kurokirasama** [comment]
Sorry, where do I find a guide to install this?

**Comment by Grimler91** [comment]
@kurokirasama it is not possible yet, still looking at the best way to handle our custom binaries. Hopefully I'll upload a package during the weekend, or earlier

**Comment by Grimler91** [comment]
texlive-installer has now been added to the unstable-packages repository. It provides tlmgr. 

I have updated the wiki with more details on how it works: https://wiki.termux.com/wiki/TeX_Live
