### ISSUE TITLE
Ifconfig

### ISSUE THREAD

**Issue by Midlaj13** [termux/termux-packages#5188]
I can't use "ifconfig" command in my termux. I am using Android 10. Os there is any solution??

**Comment by Grimler91** [comment]
Many ROMs provide ifconfig in /system/bin/, have you checked there?

**Comment by xeffyr** [comment]
`ifconfig` is available through net-tools package. However on Android 10+ it is not usable without root even for getting info as access to kernel interfaces in /proc/net is restricted.

**Comment by RalfWerner** [comment]
I succeeded on Q10 (emulation) with `ip address` and `/system/bin/ip address` (`*/ip`)!

**Comment by xeffyr** [comment]
`ip` gets information through netlink instead of directly using `/proc/net`.

**Comment by RalfWerner** [comment]
Information may @Midlay13 help, if he/she is _not interested_ in `ifconfig` itself but in a value from it.

I differentiate between T28,T29 (Termux created with targetSdkLevel *) and Q10,R11 (Android version). The functions `ip` and` ps` are different in the four possible combinations and partly not available. But the discussion does not belong in this _issue! _
