### ISSUE TITLE
 Permission denied

### ISSUE THREAD

**Issue by hanxinhao000** [termux/termux-packages#5190]
+ mv /root/.termux-build/_cache/android-r20-api-24-v3-tmp /root/.termux-build/_cache/android-r20-api-24-v3
mv: cannot move '/root/.termux-build/_cache/android-r20-api-24-v3-tmp' to '/root/.termux-build/_cache/android-r20-api-24-v3': Permission denied

**Comment by hanxinhao000** [comment]
I'm running it as root

**Comment by RossComputerGuy** [comment]
Running what as root? Are you running your Android device rooted or is this building the packages as root?

**Comment by hanxinhao000** [comment]
this building the packages as root

**Comment by hanxinhao000** [comment]
build-all.sh

**Comment by RossComputerGuy** [comment]
I don't think your supposed to build the packages as root. Are you sure your following the documentation for building packages?

**Comment by hanxinhao000** [comment]
I'll try. Thanks

**Comment by hanxinhao000** [comment]
chmod: changing permissions of '/home/xinhao/.termux-build/algernon/build': Operation not permitted

**Comment by RossComputerGuy** [comment]
You have to run chmod as root (with sudo)

**Comment by hanxinhao000** [comment]
root:+ mv /home/xinhao/.termux-build/_cache/android-r20-api-24-v3-tmp /home/xinhao/.termux-build/_cache/android-r20-api-24-v3
mv: cannot move '/home/xinhao/.termux-build/_cache/android-r20-api-24-v3-tmp' to '/home/xinhao/.termux-build/_cache/android-r20-api-24-v3': Permission denied

no root:  chmod: changing permissions of '/home/xinhao/.termux-build/algernon/build': Operation not permitted

**Comment by hanxinhao000** [comment]
sudo proxychains4 ./build-all.sh

Result :mv: cannot move '/home/xinhao/.termux-build/_cache/android-r20-api-24-v3-tmp' to '/home/xinhao/.termux-build/_cache/android-r20-api-24-v3': Permission denied

**Comment by hanxinhao000** [comment]
I'm using a Windows child Linux

**Comment by RossComputerGuy** [comment]
You mean WSL?

**Comment by hanxinhao000** [comment]
y y y ye yeyes

**Comment by RossComputerGuy** [comment]
Please use a **real** Linux distro. That is basically a chroot for Linux but in Windows and isn't a good implementation.

**Comment by hanxinhao000** [comment]
Thank you for your patience, thank you

**Comment by hanxinhao000** [comment]
Let me try

**Comment by xeffyr** [comment]
Official build environment is `termux/package-builder` docker image. Alternate variant is VirtualBox with Ubuntu 19.10.

https://github.com/termux/termux-packages/wiki/Build-environment

***

Never run build script as root as it can destroy the operating system by installing stuff into /usr (I have observed this in some packages like `perl`).

**Comment by hanxinhao000** [comment]
ok,Thank you for your
