### ISSUE TITLE
Package Request: stuntman-client

### ISSUE THREAD

**Issue by mrghosh** [termux/termux-packages#5191]
Package: stuntman-client (1.2.7-1.1)
Test client for STUN (Session Traversal Utilities for NAT)

http://manpages.ubuntu.com/manpages/cosmic/man1/stunclient.1.html

**Comment by xeffyr** [comment]
Requires openssl-1.0.x but we have 1.1.x which results in lots of errors.

**Comment by xtkoba** [comment]
From `HISTORY`:

> Version 1.2.14 - Docker support and OpenSSL compile issue
