### ISSUE TITLE
setup-android-sdk.sh error installing

### ISSUE THREAD

**Issue by demianrey** [termux/termux-packages#5193]
Android version 9 whit root

**Problem description**
error installing script setup-android-sdk.sh

**Steps to reproduce**
![IMG_20200423_091931](https://user-images.githubusercontent.com/48655207/80109956-c3a69a00-8543-11ea-81a6-d1f593d4a904.jpg)

```

```

**Comment by RossComputerGuy** [comment]
That script is used by the builder and is meant to not be used on termux.

**Comment by Grimler91** [comment]
Yepp, and the android ndk only supports x86_64 so can't use it on android
