### ISSUE TITLE
Node.js 14

### ISSUE THREAD

**Issue by pollen5** [termux/termux-packages#5194]
Node.js 14 came out. When will the package in Termux get updated?

**Comment by ajithalti** [comment]
> Node.js 14 came out. When will the package in Termux get updated?

Does npm work fine for you? Now.

**Comment by pollen5** [comment]
@ajithalti no, npm segfaults. I'm wondering if Node.js 14 would solve that.

**Comment by danieldjewell** [comment]
> @ajithalti no, npm segfaults. I'm wondering if Node.js 14 would solve that.

Try reinstalling/upgrading node ... i was getting weird npm segfaults too and then reinstalled the node termux package and it went away? go figure

**Comment by xeffyr** [comment]
Updated in https://github.com/termux/termux-packages/commit/bedc372afcd74145961c9064e8879de49a53bcee.

**Comment by X7md** [comment]
![Screenshot_20201213-175618_Termux](https://user-images.githubusercontent.com/54203033/102015414-8dd15280-3d6c-11eb-95e5-22ae704d0d94.png)
Hi, how can I update nodejs ?
i try 
pkg update/ upgrade 
and
pkg install nodejs-lts

**Comment by kcubeterm** [comment]
@X7md You have to install nodejs in order to get node 14. Right now you have installed nodejs-lts. stay on that or install nodejs
`pkg in nodejs`

**Comment by xmmti** [comment]
> @X7md You have to install nodejs in order to get node 14. Right now you have installed nodejs-lts. stay on that or install nodejs
> `pkg in nodejs`
> 
> 

thanks, It's worked ❤️
