### ISSUE TITLE
Apt update apt upgrade not install properly

### ISSUE THREAD

**Issue by Huzaifarafiq01** [termux/termux-packages#5195]
![IMG_20200424_021303_922](https://user-images.githubusercontent.com/64229438/80149896-f635ae80-85a6-11ea-984b-307e72ea9bfd.jpg)

Please tell why this showing me error if i update or a upgrade apt please tell me.

**Comment by Grimler91** [comment]
Try switching the main repository over to another mirror by running `termux-change-repo` if you are still having problems. I can't reproduce any problem now
