### ISSUE TITLE
HOST_PKGCONFIG=      error

### ISSUE THREAD

**Issue by hanxinhao000** [termux/termux-packages#5196]
+ export LDFLAGS=-L/data/data/com.termux/files/usr/lib
+ LDFLAGS=-L/data/data/com.termux/files/usr/lib
+ export AS=aarch64-linux-android-clang
+ AS=aarch64-linux-android-clang
+ export CC=aarch64-linux-android-clang
+ CC=aarch64-linux-android-clang
+ export CXX=aarch64-linux-android-clang++
+ CXX=aarch64-linux-android-clang++
+ export AR=aarch64-linux-android-ar
+ AR=aarch64-linux-android-ar
+ export CPP=aarch64-linux-android-cpp
+ CPP=aarch64-linux-android-cpp
+ export LD=aarch64-linux-android-ld
+ LD=aarch64-linux-android-ld
+ export OBJCOPY=aarch64-linux-android-objcopy
+ OBJCOPY=aarch64-linux-android-objcopy
+ export OBJDUMP=aarch64-linux-android-objdump
+ OBJDUMP=aarch64-linux-android-objdump
+ export RANLIB=aarch64-linux-android-ranlib
+ RANLIB=aarch64-linux-android-ranlib
+ export READELF=aarch64-linux-android-readelf
+ READELF=aarch64-linux-android-readelf
+ export STRIP=aarch64-linux-android-strip
+ STRIP=aarch64-linux-android-strip
+ '[' false = false ']'
+ export PATH=/home/xinhao/.termux-build/_cache/android-r20-api-24-v3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
+ PATH=/home/xinhao/.termux-build/_cache/android-r20-api-24-v3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
+ export CC_FOR_BUILD=gcc
+ CC_FOR_BUILD=gcc
+ export PKG_CONFIG=/home/xinhao/.termux-build/_cache/android-r20-api-24-v3/bin/aarch64-linux-android-pkg-config
+ PKG_CONFIG=/home/xinhao/.termux-build/_cache/android-r20-api-24-v3/bin/aarch64-linux-android-pkg-config
+ export CCTERMUX_HOST_PLATFORM=aarch64-linux-android24
+ CCTERMUX_HOST_PLATFORM=aarch64-linux-android24
+ '[' aarch64 = arm ']'
+ LDFLAGS+=' -Wl,-rpath=/data/data/com.termux/files/usr/lib'
+ '[' aarch64 = arm ']'
+ '[' aarch64 = i686 ']'
+ '[' aarch64 = aarch64 ']'
+ export GOARCH=arm64
+ GOARCH=arm64
+ LDFLAGS+=' -Wl,--enable-new-dtags'
+ LDFLAGS+=' -Wl,--as-needed'
+ CFLAGS+=' -fstack-protector-strong'
+ LDFLAGS+=' -Wl,-z,relro,-z,now'
+ '[' false = true ']'
+ CFLAGS+=' -Oz'
+ export 'CXXFLAGS= -fstack-protector-strong -Oz'
+ CXXFLAGS=' -fstack-protector-strong -Oz'
+ export CPPFLAGS=-I/data/data/com.termux/files/usr/include
+ CPPFLAGS=-I/data/data/com.termux/files/usr/include
+ '[' '' '!=' '' ']'
+ export GOOS=android
+ GOOS=android
+ export CGO_ENABLED=1
+ CGO_ENABLED=1
+ export GO_LDFLAGS=-extldflags=-pie
+ GO_LDFLAGS=-extldflags=-pie
+ export 'CGO_LDFLAGS=-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now'
+ CGO_LDFLAGS='-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now'
+ export CGO_CFLAGS=-I/data/data/com.termux/files/usr/include
+ CGO_CFLAGS=-I/data/data/com.termux/files/usr/include
+ export ac_cv_func_getpwent=no
+ ac_cv_func_getpwent=no
+ export ac_cv_func_getpwnam=no
+ ac_cv_func_getpwnam=no
+ export ac_cv_func_getpwuid=no
+ ac_cv_func_getpwuid=no
+ export ac_cv_func_sigsetmask=no
+ ac_cv_func_sigsetmask=no
+ export ac_cv_c_bigendian=no
+ ac_cv_c_bigendian=no
+ termux_setup_standalone_toolchain
+ '[' false = false ']'
+ '[' '!' -d /home/xinhao/.termux-build/_cache/android-r20-api-24-v3 ']'
+ '[' '!' -f /data/data/com.termux/files/usr/lib/libutil.so ']'
+ export PKG_CONFIG_LIBDIR=/data/data/com.termux/files/usr/lib/pkgconfig
+ PKG_CONFIG_LIBDIR=/data/data/com.termux/files/usr/lib/pkgconfig
+ '[' false = false ']'
+ local _HOST_PKGCONFIG
++ which pkg-config
[proxychains] DLL init: proxychains-ng 4.14
+ _HOST_PKGCONFIG=

-----------------------------------------------------------------------------------------------------
And then it stops. What's the solution

environment: 

 ubuntu 19.04  [ run in VirtualBox]

**Comment by Grimler91** [comment]
Looks like you are missing necessary build tools. Have you run `setup-ubuntu.sh` as the instructions say? https://github.com/termux/termux-packages/wiki/Build-environment#host-os

**Comment by hanxinhao000** [comment]
Thank you for your

**Comment by hanxinhao000** [comment]
DEBIAN_FRONTEND=noninteractive:Command not found

**Comment by hanxinhao000** [comment]
setup-ubuntu.sh

**Comment by hanxinhao000** [comment]
All right, I'll get rid of it sudo ,3q
