### ISSUE TITLE
texlive-fontsextra hash sum mismatch

### ISSUE THREAD

**Issue by dkoao** [termux/termux-packages#5201]
When I run `pkg install texlive-fontsextra`, I get:

```
Err:1 https://grimler.se/termux-packages-24 stable/main aarch64 texlive-fontsextra all 20200406-1
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:ea40ffb17979c8470c494fe8e74960cc73a8933f1548a56ef98861e6ee1ac013
   - SHA1:f25431c14da9e28fdfa7a2d566ea9173abf15e68 [weak]
   - Filesize:495675798 [weak]
  Hashes of received file:
   - SHA256:180303138e5270cb51df980c6ab7cb1f78f869597517b058604bfd0e3595a92f
   - SHA1:606fcb533152600d73cdd77cb01d04be75d15860 [weak]
   - Filesize:8790016 [weak]
  Last modification reported: Sun, 12 Apr 2020 15:25:14 +0000
Fetched 8790 kB in 2min 21s (62.3 kB/s)
E: Failed to fetch https://grimler.se/termux-packages-24/all/texlive-fontsextra_20200406-1_all.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:ea40ffb17979c8470c494fe8e74960cc73a8933f1548a56ef98861e6ee1ac013
    - SHA1:f25431c14da9e28fdfa7a2d566ea9173abf15e68 [weak]
    - Filesize:495675798 [weak]
   Hashes of received file:
    - SHA256:180303138e5270cb51df980c6ab7cb1f78f869597517b058604bfd0e3595a92f
    - SHA1:606fcb533152600d73cdd77cb01d04be75d15860 [weak]
    - Filesize:8790016 [weak]
   Last modification reported: Sun, 12 Apr 2020 15:25:14 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Happy to provide more info if needed.

**Comment by xeffyr** [comment]
```
apt clean
apt update
```
and then reinstall package.

**Comment by dkoao** [comment]
> ```
> apt clean
> apt update
> ```
> and then reinstall package.

Tried that, but unfortunately the issue persists.

**Comment by RossComputerGuy** [comment]
Maybe your using the wrong mirrors

**Comment by xeffyr** [comment]
This is correct mirror.

**Comment by Grimler91** [comment]
I am looking at it, seems to be something wrong with the apt-mirror script I am using

**Comment by Grimler91** [comment]
Seems to be fixed now. I've taken the apt-mirror script from this repo: https://github.com/flavienbwk/apt-mirror-docker instead of the official, unmaintained, one: https://github.com/apt-mirror/apt-mirror. Also had to re-download the debs that were broken

**Comment by dkoao** [comment]
> Seems to be fixed now. I've taken the apt-mirror script from this repo: https://github.com/flavienbwk/apt-mirror-docker instead of the official, unmaintained, one: https://github.com/apt-mirror/apt-mirror. Also had to re-download the debs that were broken

Thank you so much! Will try re-downloading and report back.

**Comment by Grimler91** [comment]
@dkoao thanks for reporting!

**Comment by dkoao** [comment]
Re-installed and everything works fine now. Thanks again.
