### ISSUE TITLE
Its not give my to update and to install anything it's start yesterday at night plizzz help 

### ISSUE THREAD

**Issue by PANDAGAMINGYT** [termux/termux-packages#5202]
![Screenshot_2020-04-25-16-09-16-392_com termux](https://user-images.githubusercontent.com/25384627/80280804-24ce9900-870f-11ea-8f79-375366f8595a.jpg)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by Grimler91** [comment]
You can for some reason not connect to https://grimler.se. can you browse that site in your browser?

If it still does not work then run `termux-change-repo` and switch the main repo over to another mirror

**Comment by PANDAGAMINGYT** [comment]
I exit my whe i type termux-change-repo

בתאריך שבת, 25 באפר׳ 2020, 6:47 אחה״צ, מאת Henrik Grimler ‏<
notifications@github.com>:

**Comment by PANDAGAMINGYT** [comment]
Exit me when I type termux-change-repo

בתאריך יום א׳, 26 באפר׳ 2020, 4:04 לפנה״צ, מאת ישראל גלו ‏<
israelgalogalo@gmail.com>:
