### ISSUE TITLE
Unable  install python 

### ISSUE THREAD

**Issue by naika98** [termux/termux-packages#5204]
I Factory reset my mobile .Now i installed the turmax but now unable to install python . 
![Screenshot_20200425-193836_Termux](https://user-images.githubusercontent.com/56545146/80281964-615cbd80-872c-11ea-9f9a-f813644f9bd6.jpg)

**Comment by elkarouani** [comment]
The same story for me !!!

**Comment by Grimler91** [comment]
Please try again, should be fixed now

**Comment by elkarouani** [comment]
It works now, thanks
