### ISSUE TITLE
Package request: rtorrent

### ISSUE THREAD

**Issue by FreddieOliveira** [termux/termux-packages#5206]
## Package description
ncurses BitTorrent client based on LibTorrent from rakshasa #5205

## Link to home page and sources
1. Home page: https://github.com/rakshasa/rtorrent/wiki
2. Source code: https://github.com/rakshasa/rtorrent

##  Additional information
I was able to compile it and install from inside termux by simply:

```text
$ git clone https://github.com/rakshasa/rtorrent
$ cd rtorrent
$ ./autogen.sh
$ ./configure --prefix=/data/data/com.termux/files/usr/
$ make -j8
$ make install
```

Compiling it directly from the source requires the `automake`, `autoconf` and `libtool` in order to run the `autogen.sh`. In case of compiling one of the releases tarball, the `configure` script will already be present.

These are the libs it depends upon:

```text
libncursesw.so.6
libcurl.so
libtorrent.so.21
libc++_shared.so
libc.so
```

Everything I tested so far is working as expected. This is the list of files added to the system when installed:

```text
files
└── usr
    └── bin
        └── rtorrent

2 directories, 1 file
```

Here's the Ubuntu package page: https://packages.ubuntu.com/eoan/rtorrent

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install rtorrent
```

**Comment by cxyzzz** [comment]
> Package is now available.
> 
> You can obtain it with these commands:
> 
> ```
> pkg install rtorrent
> ```

could add with-xmlrpc-pc support?
