### ISSUE TITLE
Espeak which would directly speak by using Pulseaudio for Termux

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-packages#5213]
Dear specialists,
Mr fornwall has created Espeak package for Termux. Now it can only produce audio samples by sending them to .wav file.
How complex would be to recode Espeak so it would be fully compatible with Pulseaudio for Termux? My motivation is to have faster initialisation delay for speech. Sure, it would be necessary to make functioning Speech-dispatcher for Termux too.
I think, that longer initialisation delay of Espeak is being caused by Proot, because complexity of The app prevent C code to run so fast like if somebody would create it directly exclusively for Termux. Or do you think, that The chance, that The initialisation time would be much more shorter is very lov?
I think, that if Speech-dispatcher and Espeak would run directly from Termux, Linux distro which would be executed by Proot would have much more faster speech responsiveness.
I know, that it is not easy task. As A experienced programmers. How much time would take Espeak recoding for The most experienced of us?
Sure, I could also use Mbrola. I Am also redy to help you but if complex changes inside C sources are required, step by step guide from you would not be possible unfortunately for Me.
Thank you very much for yours discussion and help.

**Comment by xeffyr** [comment]
Probably once portaudio will be available in our repos.

**Comment by JanuszChmiel** [comment]
And do you think, that if Portaudio will be available on future, that Espeak
initialisation would run faster, because it would run directly from Termux?
I think, that apps which run directly from Termux shell should be atleast a
little faster than apps which uses Proot.
To be honest, Proot do not make issues even while listening high quality
audio or video on WEB sites.
Problem is in speech swynthesis in general.
I Am wondering, if some little C or C++ app would play very soft sound by
using Pulseaudio for Termux, if this background sound would make Espeak
initialisation faster.
I have also found out, that in Android 7, sound responsiveness have been
much more better. But 7.0 Huavei kernel have suffered because of wrong
Pokedata support so Proot had to perform high cost work around. So I had
very fast Espeak responsiveness, even may be equal or better than when
running Espeak with standard Linux on  some IBM/PC compatible computer.
But because of Pokedata wrong implementation, I had got very slow apps load
time to RAM. Orca screen reader initialisation has taken more than 10
seconds. There was many other issues thanks to slow file operations.
Very complex and strange informatic phenomenas.

**Comment by tomty89** [comment]
from what I can see here espeak supports pulseaudio natively

espeak-ng do it with a library in its own project called pcaudiolib apparently

**Comment by JanuszChmiel** [comment]
Thank you very much for yours analysis. 
The most unpleasant think is, that it would be very probably necessary to
deeply understand C language and may be, that many changes would had to be
performed from Espeak source or from portaudio.h.
Somebody even do his best to implement portaudio for Termux.
The good question is, if The reaction time between key press and getting
speech would be much more better while comparing with The situation, when
Espeak run by using Proot.
I do not want to overload some professional C developers here if their
complex work would not have The sense.

Unfortunately, I can not predict The result.
I only know, that yesterday, MR Samuel Thibauld, Experienced C programmer
have released new version of Speech-dispatcher. He has setup Audio latency
to 10 Milliseconds inside Speech-dispatcher source code to avoid Pulseaudio
cuttering.
But for now, AUR ARM64 repository for Arch Linux do not contain this
version. I must be patient.
Now, I Am using Speech-dispatcher and Espeak-ng which talk to Pulseaudio
which run in Termux by using Pulseaudio-alsa ArchLinux ARM64 package.
The sound quality is ideal and perfect even for long Internet radio
listening even on 220 KB/S streams. So I do not want to tell, that
Pulseaudio for Termux contain A bug. It is professionally programmed sound
server. I have even never noticed its internal crash even after several days
while this server have been randomly used.
I Am sad, that I did not studied informatic studies. And that I Am bothering
C programmers around The world with my plea.
I have even done my best to run real Pulseaudio sound server from Arch
Linuxd wich have streamed sound by using Simple protocol player. I have
successed.
But speech responsiveness have not been god, The reactivity have been not
good. Pulseaudio for Termu provides The best responsiveness.
Huavei 10 Mate lite had Android 7.0 before. This version has contained wrong
Pokedata implementation, but much better sound reactivity.
Now I have fast file load and save operations, because Android 8 for Huavei
10 Mate lite have introduced Pokedata repair. So Proot do not have to run
its high cost work around.
But as a shadow Effect, something have been changed deeply in Android kernel
so speech responsivenessw have been not good. More than one Second between
key press and getting feetback from Espeak.
So may be, that I will be forced to accept this sad fact. And may be, that I
will have to save some money for Blackview. But what if also their kernel
contain some sound issue.

**Comment by JanuszChmiel** [comment]
Arch Linux is so matured distro, that I can perfectly use VLC media player
with Orca screen reader and Espeak. VlC media player perfectly play live
streams and I can switch between opened app windows in background. No
crashes no unstability.
I write it to demonstrate, that if somebody would help with Espeak speech
responsiveness it would really have a sense. Because The Proot and Termux
development status allow users to run really many Linux apps without issues.
The Proot stability is so good, that it is even possible to let mate-session
to run in background for A whole night and user will not find his device or
Mate in unstable stage in The morning.
By other words, Proot is really virtualisation solution, which work. But
some sound issues with speech synthesis exist but it depend on Android
kernel and on its configuration while compiling it.
I can even use Seamonkey with all of its functions including E-mail. in 2017
I have always got bug from dependent .so library relate d to shared memory.
But now, somebody have recoded Seamonkey specifically to avoid shared memory
support. I do not know, if it was ARU Arch Linux packager or somebody else,
or if Proot developers have introduced this magic. Or Mr Rausty and his
colleagues.
By other words, thanks to VNC protocol it is possible to run many Linux apps
even if user do not see at all.
The author of Dbus have incorporated The command dbus-run-session which
greatly improved processes stability. Dbus-launch command did not brought so
rreliable results.
I Am ready to test and cooperate closely if somebody would try to customize
Espeak to work with Termux and Pulseaudio for Termux.

**Comment by xeffyr** [comment]
Espeak is now built with `pcaudiolib` (`pkg upgrade`), I have tested and it seems working as expected.
I'm closing this issue.

**Comment by JanuszChmiel** [comment]
Yes and it work like A charm. Thank you very much dear Mr Pliush. Thank you
for yours C knowledge and for yours time.
My notion have been correct. 
It is sad, that I can not redirect The Speech-dispatcher socket from running
Arch Linux to The place, where Espeak which run from Termux would receive
The data.
Because I know, that building Speech-dispatcher would be too much complex
work even for future.
But My notion have been correct. If app directly uses Pulseaudio from
Termux, delay do not exist at all
