### ISSUE TITLE
Package request: onionshare

### ISSUE THREAD

**Issue by mehlon** [termux/termux-packages#5214]
**Package description**

OnionShare is an open source tool for securely and anonymously sending and receiving files using Tor onion services. It works by starting a web server directly on your computer and making it accessible as an unguessable Tor web address that others can load in Tor Browser to download files from you, or upload files to you. It doesn't require setting up a separate server, using a third party file-sharing service, or even logging into an account.

OnionShare has a CLI-only version.
**Link to home page and sources**
1. Home page: https://onionshare.org/
2. Source code: https://github.com/micahflee/onionshare

**Additional information**
Have you compiled or tried to compile the package on device?

Yes, but: 
```
$ apt install -y python3-flask python3-stem python3-pyqt5 python3-crypto python3-socks python-nautilus tor obfs4proxy python3-pytest build-essential fakeroot python3-all python3-stdeb dh-python python3-flask-httpauth python3-distutils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-flask
E: Unable to locate package python3-stem
E: Unable to locate package python3-pyqt5
E: Unable to locate package python3-crypto
E: Unable to locate package python3-socks
E: Unable to locate package python-nautilus
E: Unable to locate package python3-pytest
E: Unable to locate package python3-all
E: Unable to locate package python3-stdeb
E: Unable to locate package dh-python
E: Unable to locate package python3-flask-httpauth
E: Unable to locate package python3-distutils
```

**Comment by xeffyr** [comment]
This is not going to be packaged:
1. Python packages are installable through `pip` (omit the `python-` prefix in name).
2. `pyqt5` is not installable but won't be available anyway.
3. `fakeroot` is not needed.
