### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by Kingbeingmad** [termux/termux-packages#5215]
I want to access the mysql.I installed mysql but when i try to access then it is asking for password but my phone is secured with pattern. How i access to mysql ????.help me!!!!!!
![Screenshot_20200427-103427](https://user-images.githubusercontent.com/64394788/80335737-dcc88700-8872-11ea-8a2d-c17620cd21d0.jpg)

**Comment by Grimler91** [comment]
Set the password as described in the wiki: https://wiki.termux.com/wiki/MariaDB
