### ISSUE TITLE
Unable to enter password 

### ISSUE THREAD

**Issue by Masterchiefhaze** [termux/termux-packages#5216]
Whenever I try to download a package from github it keeps asking me for my github login details. I am able to enter the username but I can't enter the password 
![Screenshot_20200427-160626](https://user-images.githubusercontent.com/64407165/80394220-16b08200-88a1-11ea-9dee-dc17f1e917d7.png)

**Comment by Grimler91** [comment]
The password is not echoed to the terminal, that is as it should be. If you are unable to clone the repo even though you have entered the correct password then that means that you have spelled the repo wrongly or that you don't have read rights to the repo (seems like you are trying to clone a private repo so I would guess the latter)
