### ISSUE TITLE
Package request: ghc / hugs

### ISSUE THREAD

**Issue by kmein** [termux/termux-packages#522]
I think it would be awesome to have a mobile Haskell REPL, which would allow more concise "pocket calculator" style calculations. Furthermore there aren't many packages for functional programming (only `tinyscheme` which is only cool when you like Lisp)...

**Comment by vishalbiswas** [comment]
`ghc` is in disabled-packages

**Comment by kmein** [comment]
(How) can it be enabled? And why is it disabled in the first place?

**Comment by fornwall** [comment]
@kmein Most packages in the disabled-packages/ folder doesn't build or work correctly. What's needed is for someone to look into building it - ghc is a rather complicated/big thing to build, so help is needed here.

**Comment by joakim-noah** [comment]
Dupe of #80.
