### ISSUE TITLE
Permission denied trying to install gobject-introspection

### ISSUE THREAD

**Issue by NTBBloodbath** [termux/termux-packages#5224]
**Problem description**
I'm trying to build gobject-introspection (I already installed all dependencies and modified certain things on `meson.build` file) using ninja and meson with termux-chroot, It was going great until it showed a Permission denied error...
```
PermissionError: [Errno 13] Permission denied: '/data/data/com.termux/files/lib'
```

**Changes to `meson.build`**
```
# commented this line ↓
# add_project_arguments(['-DHAVE_CONFIG_H'], language: 'c')

# Added these lines
add_global_link_arguments('-llog', language: 'cpp')
add_global_link_arguments('-latomic', language: 'cpp')
```

**Additional information**
```
Android version:
9
Kernel build information:
Linux localhost 3.18.134•Rattlesnake🐍-g35d9a0881406 #2 SMP PREEMPT Fri Feb 8 10:58:49 -02 2019 aarch64 Android
Device manufacturer:
motorola
Device model:
XT1676
```

**Comment by Grimler91** [comment]
`/data/data/com.termux/files/lib` should probably be `/data/data/com.termux/files/usr/lib`. I guess you have given the wrong `--prefix` or `--libdir` to meson?

**Comment by NTBBloodbath** [comment]
> `/data/data/com.termux/files/lib` should probably be `/data/data/com.termux/files/usr/lib`. I guess you have given the wrong `--prefix` or `--libdir` to meson?

Thanks for the reply, although I'm sorry to say that I'm already using `--prefix` with $PREFIX/lib (the complete path, I only shorten it here) and the same with `--libdir` but I'm getting the same result and so I opened the issue ... I can't find a way to make it change the path :s

**Comment by Grimler91** [comment]
What arguments exactly are you running meson with?

**Comment by NTBBloodbath** [comment]
> What arguments exactly are you running meson with? You mentioned termux-chroot in the first message, are you trying to run this in termux-chroot?

I'm running this (I already tried putting each argument separately too)
```
meson _build --prefix=/data/data/com.termux/files/usr/lib --libdir=/data/data/com.termux/files/usr/lib
```

And yeah, I was trying to install it by using `termux-chroot` but doesn't install... And if I try without `termux-chroot`, oddly I get the same error. I'm seeing `meson.build` to see if there is something that prevents changing the path by using arguments.

**Comment by Grimler91** [comment]
`--prefix=/data/data/com.termux/files/usr/lib` should be `--prefix=/data/data/com.termux/files/usr`

**Comment by NTBBloodbath** [comment]
> `--prefix=/data/data/com.termux/files/usr/lib` should be `--prefix=/data/data/com.termux/files/usr`

Oh, that's true!

However, I'm getting the same result 😕
Btw, I forgot to put that before, after these line the build crashes

```
Found pkg-config: /data/data/com.termux/files/usr/bin/pkg-config (0.29.2)

# A large meson error log

files = [f for f in os.listdir(d) if f.endswith('.so') and os.path.isfile(os.path.join(d, f))]
# After this message, it displays the error at lib path
```

I already think it must be something internal to the `meson.build` file, I will see if some statements are causing those troubles with `lib` path
