### ISSUE TITLE
How to solve Unable to locate package problem 

### ISSUE THREAD

**Issue by hydromaster685** [termux/termux-packages#5226]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by xeffyr** [comment]
You can solve it by:
* Running `apt update` before trying to install something.
* Checking the package name for typos.

However there can be a case when package really do not exist in our repository. If so, nothing can be done on your side. Existence of package can be checked by
```
apt update
apt search <package name>
```
