### ISSUE TITLE
Package request: youtube-dl

### ISSUE THREAD

**Issue by Xazax-hun** [termux/termux-packages#5228]
**Package description**
Youtube-dl is a lightweight way (no ads, no bloat, no GUI) to download YouTube videos to watch later. 

**Link to home page and sources**
1. Home page: https://youtube-dl.org/
2. Source code: https://youtube-dl.org/

**Additional information**
Have you compiled or tried to compile the package on device?
No.

**Comment by RossComputerGuy** [comment]
It's a python program so it won't be packaged.

**Comment by Grimler91** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/2494, https://github.com/termux/termux-packages/pull/636, https://github.com/termux/termux-packages/issues/2186

**Comment by ChiefMikeK** [comment]
## 👓  [Search results - YouTube-dl · PyPI](https://pypi.org/search/?q=YouTube-dl&o=)
