### ISSUE TITLE
 airmon-ng

### ISSUE THREAD

**Issue by premdev28** [termux/termux-packages#5229]
when i run airmon-ng in termux it doesn't run and shows an error that
Your kernel has module support but you don't have modprobe installed.
Your kernel has module support but you don't have modinfo installed.
Your kernel has module support but you don't have rfkill installed.

i try to install many times modprobe, modinfo and rfkill from github but not installed

please how can i solve this error

**Comment by Grimler91** [comment]
Those are info messages, not errors, so they can't cause airmon-ng to not run. 

Does your device support monitor mode or are you using a usb dongle? If the latter, has your kernel been compiled with the necessary drivers?

**Comment by xeffyr** [comment]
> i try to install many times modprobe, modinfo and rfkill

You **don't need these utilities**. Just your wi-fi drivers don't support monitor mode. In fact, nearly all Android devices lack its support.

The only way to use Aircrack-ng utilities is to have **USB wi-fi stick** and **special kernel**. Once you have the USB wi-fi stick, check the [XDA forums](https://forum.xda-developers.com/) about your  device whether official/unofficial nethunter kernel is available. If not, you will have to configure & build your own.
