### ISSUE TITLE
chmod +x /sdcard/meta-install.sh chmod: changing permissions of 'meta-install.sh

### ISSUE THREAD

**Issue by vino482** [termux/termux-packages#5232]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by xeffyr** [comment]
`chmod` doesn't work in /sdcard. That's file system limitation.

**Comment by Khulakpamzaid786** [comment]
I want to install chomd

**Comment by Yonle** [comment]
`chmod` is already installed. And you can't change file permission in Internal/External storage.

**Comment by Yonle** [comment]
Also:

```sh
cp /sdcard/meta-install.sh ~/
chmod +x ~/meta-install.sh
~/meta-install.sh
```
