### ISSUE TITLE
Failure installing TeXLive with the installer

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#5234]
Here is on android 8 with the last Termux.

I have seen you have released the TeXLive installer, so I tested it using the local repository `$PREFIX/opt/tlrepo` which is a mirror of remote `tlnet`:

```
termux-install-tl -repository $PREFIX/opt/tlrepo
  d - TEXDIR - /data/data/com.termux/files/usr/opt/tex_live
  r 
  i
```

It failed with:

```
[...]
Time used for installing the packages: 63:20

running mktexlsr
/data/data/com.termux/files/usr/opt/tex_live/texmf-dist ...  Can't
exec "mktexlsr": No such file or directory at
/data/data/com.termux/files/usr/opt/texlive/install-tl/tlpkg/TeXLive/TLUtils.pm
line 605. /data/data/com.termux/files/usr/opt/texlive/install-tl/install-tl:
command failed (status -1): mktexlsr
/data/data/com.termux/files/usr/opt/tex_live/texmf-dist: No such file
or directory
```

I do not like the installation in `TEXDIR=.../share/texlive`. In all systems on which I install TL I install in `.../opt/texlive` (here in .`../opt/tex_live` because the installer already uses texlive). I have also a `.bash_texlive` script sourced by `.bashrc` that sets the `PATH, INFOPATH, MANPATH` ecc. I enable this script after TL installation.

In the TEXDIR directory, after installation I should find something like

`.../tex_live/bin/custom`

when one uses `custom-bin` as in this case. Instead I do not find that.

With the texlive installer package I would not install `texlive-bin` as you have done (and in `..usr/bin/texlive`) I would temporary install them in ../tmp, than the custom-bin option should just copy them in `TEXDIR/bin/custom`. When I used custom binaries on other systems this is what ocurred...

**Comment by Grimler91** [comment]
Sorry, changing TEXDIR is not supported ([as mentioned in the instructions](https://github.com/termux/unstable-packages/blob/d1b90995db3feb956b816a16c8b484926a3bdc97/packages/texlive-installer/installer.sh#L9)).  Installing the binaries to `TEXMFROOT/bin/custom` will make apt unable to keep them up to date, and would give you two set of binaries, taking unnecessary disk space. Trying to get that to work in a good way is not worth the complexity IMO.

**Comment by Grimler91** [comment]
You could download `texlive-bin`, extract the binaries, use the install-tl script (instead of the wrapper) and install it to where ever you want. The binaries will then not receive updates and you have to apply some patches to fix paths manually.

**Comment by angelog0** [comment]
Everything would be a lot easier if you just send the files upstream.... ;-)
