### ISSUE TITLE
emacs 26.3-7 does not start - missing libs

### ISSUE THREAD

**Issue by pascalfleury** [termux/termux-packages#5236]
**Problem description**

Emacs does not find sime libs, e.g. libnettle.so.7

**Steps to reproduce**
On a fresh install of termux, just do
$ pkg install emacs
$ emacs
emacs-26.3-7 has been compiled with and now needs libnettle.so.7, however the latest version on my system is libnettle.so.8

I also made a symbolic link 
 libnettle.so.7 -> libnettle.so.8
which made emacs bump into another lib that also has a fresher version installed.

**Expected behavior**
emacs finds all its libs.

**Additional information**
I guess it only needs to be rebuilt with the new libs, and deployed. Emacs 27 is still some time in the future, so I think waiting for this is not a good solution.

**Comment by xeffyr** [comment]
See https://github.com/termux/termux-packages/issues/5235#issuecomment-622942935.
