### ISSUE TITLE
TeXLive installation (installer) does not work

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#5237]
OK, I have installed accepting the default TEXDIR. All post installation is done. Now PATH, MANPATH and INFOPATH are correctly set. I tried to test after restarting Termux but it fails:

```
$ latexmk -pdf tesi
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Apr. 2020, version: 4.69a.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "tesi.tex"'
------------
sh: 1: pdflatex: not found
Latexmk: fls file doesn't appear to have been made.
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 127
      Refer to 'tesi.log' for details
----------------------
This message may duplicate earlier message.
Latexmk: Failure in processing file 'tesi':
   (Pdf)LaTeX didn't generate the expected log file 'tesi.log'
----------------------
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
```

Indeed `which pdflatex` is empty...

On other systems (say GNU/Linux) `pdflatex` is a symlink to `pdftex`....

**Comment by Grimler91** [comment]
Weird, the pdflatex format should have been generated by [the installer](https://github.com/termux/unstable-packages/blob/d1b90995db3feb956b816a16c8b484926a3bdc97/packages/texlive-installer/installer.sh#L57)

What happens if you run
```sh
fmtutil-sys --byfmt pdflatex
```
?

**Comment by angelog0** [comment]
The output is 
[fmutil.output.gz](https://github.com/termux/termux-packages/files/4568113/fmutil.output.gz).

The issue is not the pdflatex format but the lack of `pdflatex` command which as I wrote on other systems is a symlink to `pdftex`.

If you read the output I sent, at the beginning it says

`remaking pdflatex with pdftex`

and then it uses

`fmtutil: running `pdftex -ini   -jobname=pdflatex -progname=pdflatex -translate-file=cp227.tcx *pdflatex.ini' ...`

For what I understand it is using `pdftex...` command in place of `pdflatex` so it does not fail even if `pdflatex` is lacking...

**Comment by angelog0** [comment]
It seems that also `latex' command is lacking:

`$ which latex`

is empty. Instead:

```
$ which latexmk
/data/data/com.termux/files/usr/bin/texlive/latexmk
```

On other systems, `latex` is a symlink to `pdftex`... I suspect similar issue for other commands...

**Comment by angelog0** [comment]
Ah, running `texlinks` creates those symlinks! I think you have to review the procedure of installing texlive with the installer. In same place `texlinks` is not run...

**Comment by Grimler91** [comment]
Thanks, should be fixed by https://github.com/termux/unstable-packages/commit/c32137bb7e9ccf33b173f6a1239889074c23d188
