### ISSUE TITLE
Node older version 11.15.0 for Eclipse Thiea and Code-Server IDEs

### ISSUE THREAD

**Issue by rohitranjan1991** [termux/termux-packages#5240]
**Package description**

**Link to home page and sources**
1. Home page: https://github.com/nodejs/node/tree/v11.x
2. Source code: https://github.com/nodejs/node/tree/v11.x

I am requesting for this package since both [Eclipse Theia](https://github.com/eclipse-theia/theia) and [Code-Server](https://github.com/cdr/code-server) requires 10<node<12 to run. They both are teh browser versions of the VSCode and i am sure it would be helpful to run have these working on termux directly since it will be super helpful to code in inside termux. Thanks in advance :-)

I tried downloading the [arm64 version](https://nodejs.org/download/release/v11.15.0/) and running it but it did not work.

![image](https://user-images.githubusercontent.com/4726622/80919477-b0879b80-8d87-11ea-8e73-4771863b1623.png)

**Comment by RossComputerGuy** [comment]
Try without `sh`

**Comment by Grimler91** [comment]
> Try without sh

Won't help unfortunately, it will fail in any case since termux's programs are compiled against android's libc while the nodejs releases are compiled against the gnu libc

**Comment by RossComputerGuy** [comment]
Oh, maybe `node-v10` could be a package that conflicts/replaces `node`.

**Comment by rohitranjan1991** [comment]
without sh also it does not work. as suggested, if we could have a node-v11. then that would solve the problem.

**Comment by cswl** [comment]
Node v11 is already EOLed.. `https://nodejs.org/en/about/releases/`

Maybe instead of adding arbitary version of Node to packages repo.. 
A packaged tar.gz that works just like downloaded versions .. from `nvm` `fnm`. would be better..

That would also allow to fine tune some minor  versions..   if need arises

**Comment by pollen5** [comment]
Code-Server's README says you need Node.js v12+ there is no reason for them to require older node versions.

**Comment by hnmn** [comment]
Hey  checkout this 
![Screenshot_2020-06-05-12-20-06-601_com android chrome](https://user-images.githubusercontent.com/26086203/83845891-53388e80-a727-11ea-802c-50412637633c.jpg)
![Screenshot_2020-06-05-12-22-29-840_com android chrome](https://user-images.githubusercontent.com/26086203/83845903-5af83300-a727-11ea-82ca-7275a7f1cb13.jpg)
