### ISSUE TITLE
Request include openjdk (openjdk8)

### ISSUE THREAD

**Issue by stevenleeS0ht** [termux/termux-packages#5241]
**Package description**

No need for extra description.

**Link to home page and sources**
1. Home page: https://openjdk.java.net/
2. Source code: https://hg.openjdk.java.net/jdk/jdk

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by RossComputerGuy** [comment]
Won't be added, look at past requests for this

**Comment by Grimler91** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/324
