### ISSUE TITLE
update netpbm

### ISSUE THREAD

**Issue by landfillbaby** [termux/termux-packages#5242]
| netpbm origin | version ATTOW |
| - | - |
| Termux current (stable) | r3096 10.73.17 |
| upstream super_stable | r3776 10.73.31 |
| upstream stable |  r3779 10.86.12 |

I'm not sure whether to stick to 10.73 or to stable, or even switch to advanced; either way it seems like a good idea to update.
Someone with write access to https://bintray.com/termux/upstream will have to do it.

**Comment by Grimler91** [comment]
Seems the super stable branch is [active now](https://sourceforge.net/projects/netpbm/files/super_stable/10.73.31/), so maybe we can switch to it

**Comment by hakymeh1356** [comment]
1234567890
