### ISSUE TITLE
About something for SSHFS

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#5244]
On other systems I have a local repo of `tlnet` on a MacBookPro machine then I mount that folder on a GNU/Linux machine by means of `sshfs` from `fuse` package, if I remember... In this way I have the local repo on one machine and maintain the TeXLive installation on multiple machines.

There is something like this in Termux?

Thanks.

**Comment by xeffyr** [comment]
libfuse is disabled packages (broken) and is not usable without root anyway.

**Comment by Grimler91** [comment]
You can always setup a small server with nginx, apache or some other program on the macbook and then use `-repository http://macbook.local.ip/` or similar when installing texlive

**Comment by angelog0** [comment]
Thanks for clarifications and suggestions, the sshfs-based solution seemed simpler to me because in the MacBook `Preferences`there is the remote loging enabled so that I can login with `ssh`..

BTW, I already installed TL with the installer using the local repo of `tlnet`, also the update with `tlmgr` works... thanks.
