### ISSUE TITLE
feature request for package: please add ability to use termux-usb with qemu

### ISSUE THREAD

**Issue by ilyapashuk** [termux/termux-packages#5249]
please add to qemu option like that: --device usb-host,desc=id
to add ability to use termux-usb devices with qemu without tricks like usbip.

**Comment by xeffyr** [comment]
I did some tests and it seems that way how `termux-usb` works is unsuitable for QEMU. Descriptor is passed by termux-usb as separate command line argument and QEMU treats it as disk image which results in "Could not open 7: no such file or directory".

Marking as "wontfix" until something will be done with `termux-usb` as I'm not going to change QEMU command line behaviour.
