### ISSUE TITLE
Installing/using python throws error, installing python2 throws segfault

### ISSUE THREAD

**Issue by cydhaselton** [termux/termux-packages#525]
Link to error details: http://pastebin.com/utLsdCkb
I've tried the following troubleshooting steps

1. Uninstaling and reinstalling
2. Setting PYTHONHOME and PYTHONPATH
3.  Updating as follows:
    * Closing Termux
    * updating it via Google Play
    * Running apt upgrade and installing all upgrades
    * re-installing python
None of the above has worked to resolve the issue

**Comment by vishalbiswas** [comment]
Can you describe ways to reproduce this? I have Python installed, and it's working correctly.

**Comment by cydhaselton** [comment]
Thanks for the interest @vishalbiswas...but I've already started over with Termux.

For future reference, anything using `python`...installation, running, running with various params, etc...would throw the error.
