### ISSUE TITLE
New sessions are starting in the same dir as last created session.

### ISSUE THREAD

**Issue by H4ck3r404** [termux/termux-packages#5259]
Idk if it should be considered as bug or just weird behavior. I'm posting this in case it was not seen before.

**Comment by Hax4us** [comment]
Yes It's normal behaviour see https://github.com/termux/termux-app/commit/e28be01dc23d480d3938ac26e7fc2cff39379c3e

**Comment by H4ck3r404** [comment]
Ok. Thanks for info.
