### ISSUE TITLE
entering "tsu" mode disables zsh

### ISSUE THREAD

**Issue by fireclouu** [termux/termux-packages#5266]
**Problem description**

after updating tsu package, whenever I enter tsu zsh no longer works, it was replaced by default hash (#) sign, tried zsh-ing inside tsu but still nothing.

**Steps to reproduce**

needs to have a zsh shell (in my case I had it modified to support p10k style), update tsu on latest revision (as of the writing of this report), enter `$ tsu` on command line, notice that zsh (specifically p10k) not working

**Expected behavior**

like the previous update, p10k should notify `root@localhost` on its tab, instead of single hash

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf-ge84d0a7 #1 SMP PREEMPT Mon Dec 23 16:17:26 CST 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 5A

```
I read `$ tsu --help` command and tried `$ tsu -s (path to zsh)` but still had the same issue

**Comment by Grimler91** [comment]
What is it that does not work with tsu? You mention that the PS1 is not what you want but is it something else that does not work with tsu + zsh?

**Comment by xeffyr** [comment]
@Grimler91 It doesn't set PATH at all if su is not from Magisk.

**Comment by xeffyr** [comment]
![VirtualBox_Android_08_05_2020_23_03_15](https://user-images.githubusercontent.com/25881154/81444635-258c1400-9180-11ea-85d7-85956a9a4932.png)

**Comment by cswl** [comment]
I've been working on this..

Sorry I didnt had a non Magisk binary to check..

Please mention me next time..  I've refacored and improved debugging v8.3.1 

PR incoming.
