### ISSUE TITLE
ALSA Error in Ubuntu chroot

### ISSUE THREAD

**Issue by KangKazumi** [termux/termux-packages#5269]
I use Ubuntu chroot.
I'm getting the following error message when I use espeak, `espeak "Hello World!"`

`ALSA lib confmisc.c:767:(parse_card) cannot find card '0'`
`ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory`
`ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings`
`ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory`
`ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name`
`ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory`
`ALSA lib conf.c:5181:(snd_config_expand) Evaluate error: No such file or directory`
`ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM sysdefault`
`...`

Using mpv and festival will also get ALSA errors. 
However, these tools work fine in termux.
Could anyone give me a hand ?

**Comment by xeffyr** [comment]
ALSA is not supported on most Android devices.

**Comment by kcubeterm** [comment]
Follow this tutorial for playing sound with chroot, https://hindux.github.io/play-audio-in-termux-chroot/
