### ISSUE TITLE
> @BlueMax

### ISSUE THREAD

**Issue by adhilroshan** [termux/termux-packages#5271]
> @BlueMax 
> Then easy :
> $ cd  ..
> $ cd usr/bin
> $ mv wget wgetc
> $ echo "$(LD_PRELOAD=/system/apex/com.android.media.swcodec/lib/libclang_rt.ubsan_standalone-arm-android.so wgetc $1 $2 $3 $4 $5)" >wget 
> $ chmod 755 wget wgetc

Not working 
I have the same problem not solved
**Please Find a solution for me**

_Originally posted by @adhilroshan in https://github.com/termux/termux-packages/issues/4861#issuecomment-626271829_

**Comment by kcubeterm** [comment]
Does that library exist on that path, in my device
 ```libclang_rt.ubsan_standalone-arm-android.so``` not exist on that path, maybe any similar library exist.

**Comment by Grimler91** [comment]
Please use the bug report template: https://github.com/termux/termux-packages/issues/new?template=bug_report.md
