### ISSUE TITLE
$ wget -O install-nethunter-termux https://offs.ec/2MceZWr
CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget"...

### ISSUE THREAD

**Issue by adhilroshan** [termux/termux-packages#5272]
`$ wget -O install-nethunter-termux https://offs.ec/2MceZWr`

```CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget"...```

``` $ termux-info

Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.177-18246680 #1 SMP PREEMPT Thu Mar 26 13:48:57 KST 2020 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A105F

#issueswithwget #android10

**Comment by Grimler91** [comment]
Looks like the same issue as https://github.com/termux/termux-packages/issues/4615, so let's track it in that issue. Also only seem to happen on some devices, I cannot reproduce

**Comment by adhilroshan** [comment]
> Looks like the same issue as https://github.com/termux/termux-packages/issues/4615, so let's track it in that issue. Also only seem to happen on some devices, I cannot reproduce

I think this issue is shown on android 10

**Comment by Grimler91** [comment]
I have android 10 as well so probably just happens with some manufacturers/some ROMS

**Comment by lolilp** [comment]
![Internet_map_1024](https://user-images.githubusercontent.com/68154681/97319050-8ec22980-187d-11eb-87f2-420e15a103c7.jpg)}
