### ISSUE TITLE
Directional keys

### ISSUE THREAD

**Issue by ProDigit** [termux/termux-packages#5280]
Termux takes control of my keyboard (replaces the standard keyboard), and there are no directional keys.
Most commands are copy paste, with a few parameters in between.
I have no way of moving the cursor left or right.
My keyboard does show up or down arrows.
What my Essential Phone with Android 10 has by default, is one can slide the finger over the space bar, to move the cursor left or right.
A possible solution without having to find space for more keys.
Another possibility is to have a third submenu under the key assigned for symbols vs alphabet.
Add some directional keys and numbers (10 key).

**Comment by kcubeterm** [comment]
If you are talking about termux virtual key then Directional keys are available in termux, check out https://wiki.termux.com/wiki/Touch_Keyboard


Use vpn in case of not opening that link.

**Comment by Grimler91** [comment]
The extra-keys are customisable, as explained in that wiki page. So you can add whichever keys you want
