### ISSUE TITLE
I installed Ubuntu in termux, on my Android 9 device, but it can't start

### ISSUE THREAD

**Issue by Seth-20** [termux/termux-packages#5283]
$ ./start-ubuntu.sh
bash: ./start-ubuntu.sh: No such file or directory

**Comment by xeffyr** [comment]
`cd` into directory where `./start-ubuntu.sh` is located.

**Comment by Seth-20** [comment]
It ran successfully the first time I installed it and I was even able to install R and python easily, but now can't be 'started'
