### ISSUE TITLE
Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

### ISSUE THREAD

**Issue by Parmanand47** [termux/termux-packages#5289]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by Parmanand47** [comment]
Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by xeffyr** [comment]
`apt install -f`

**Comment by Parmanand47** [comment]
A similar error is still coming.
