### ISSUE TITLE
img2txt (post Harfbuzz update) only supports BMP

### ISSUE THREAD

**Issue by tinydynamite00** [termux/termux-packages#529]
@fornwall Updated <code>harfbuzz</code> earlier today and tried to run <code>img2txt</code>, default options, arg pointing to a lo-res .png - no dice. Ran <code>strace</code> which at the end returned the following:

> write(2, "NOTE: This program has NOT been "..., 90NOTE: This program has NOT been built with 
> Imlib2 support. Only BMP loading is supported.

Expected result: <code>libcaca</code> support; already installed. 
EDIT: If BMP is meant to be the only supported file format, my apologies. However, not aware of (m)any people who solely keep BMP files on board Android. 

Full (relatively brief) strace attached
[upload_strace-img2txt_output_20161030.txt](https://github.com/termux/termux-packages/files/560910/upload_strace-img2txt_output_20161030.txt)

**Comment by fornwall** [comment]
I guess libcaca would need to be compiled against Imlib2 to support other image formats than BMP (and that harfbuzz doesn't have anything to do with this, right)?

**Comment by tinydynamite00** [comment]
Right, it's nothing to do with harfbuzz specifically. New libcaca user, (novice at compile/building, too) but as I understand the documentation Imlib2 appears to supply the loaders required for (insert image format) conversion to .caca files.

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/52c6c4d2b09713b31edd88ff597f8dee2233fcd6.
