### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by debian44** [termux/termux-packages#5292]
Sorry if this is unrelated its not Termux's problem but I have problems
In my country (Iran) Bintray server is very slow I should download packages through uncensored VPN(yet) or Tor(by bridge) so is there any mirror or something somewhere else.
Unfortunately termux.net was fast but its legacy environment repo

**Comment by Grimler91** [comment]
Mirrors are listed here: https://github.com/termux/termux-packages/wiki/Mirrors

You can use the script `termux-change-repo` (part of `termux-tools`) to switch mirrors.
