### ISSUE TITLE
pkg update && pkg upgrade error

### ISSUE THREAD

**Issue by deneuvez** [termux/termux-packages#5296]
i installed termux and doing the update and upgrade command, and this is happened
> The repository https://termux.org/packages stable Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

what should i do? im new to termux

**Comment by Grimler91** [comment]
Probably a temporary problem. If it still occurs then you can try switching to another mirror by running `termux-change-repo` and selecting something else than the official repository.

**Comment by xeffyr** [comment]
@deneuvez No need to report that error just once it occurred.

It is **expected** once per 24h as we need to periodically run cleanup script and rebuild repository metadata.
