### ISSUE TITLE
Hello please on my termux app if I wanna use storage on terms is telling me access denied please help me out

### ISSUE THREAD

**Issue by semviston** [termux/termux-packages#5303]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
`termux-setup-storage` or enable permission in android settings.

**Comment by xeffyr** [comment]
Writing to external sdcard is not possible. (don't look on file managers, SAF api can't be used with command line)

**Comment by semviston** [comment]
Okay thanks it work now
