### ISSUE TITLE
Package request: deno

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#5306]
Deno is a secure TypeScript runtime with V8 engine. Written in rust by the same creator as Node.js.

Recently version 1.0.0 was released so it's starting to become more stable.

GitHub: https://github.com/denoland/deno

**Comment by tomap** [comment]
Hi, I tried to compile deno from sources, and there was at least one error with package sys-info which does not seem to know termux env
I believe there is already an issue open, even if it's not exactly the same context:
https://github.com/FillZpp/sys-info-rs/issues/64

**Comment by kcubeterm** [comment]
Sys-info(0.8.0) is now compiled successfully.  But problem is rusty_v8 don't support arm64. 
https://github.com/denoland/rusty_v8/pull/270

**Comment by tomap** [comment]
Indeed

```
error[E0308]: mismatched types                                                             --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build.rs:148:18                                                             |                                                                                   148 | fn platform() -> &'static str {                                                       |    --------      ^^^^^^^^^^^^ expected `&str`, found `()`                             |    |                                                                                  |    implicitly returns `()` as its body has no tail or `return` expression         
error: aborting due to previous error                                                                                                                                           For more information about this error, try `rustc --explain E0308`.                     error: could not compile `rusty_v8`
```

**Comment by stupidestmodder** [comment]
any news on this???

**Comment by istomyang** [comment]
> Sys-info(0.8.0) is now compiled successfully. But problem is rusty_v8 don't support arm64.
> [denoland/rusty_v8#270](https://github.com/denoland/rusty_v8/pull/270)

Hey! Rusty_v8 supports arm64 since 0.20.0, maybe you can try. Compiling code for arm64 needs arm CPU like Raspberry Pi ,  I am a newbie and don't have that device. 😔

**Comment by tomap** [comment]
You can install rust on termux on your android device

Then clone the rusty_v8
Then runs cargo build -vv

It was failing lat time I checked

**Comment by LesVu** [comment]
I've managed to compile it on devices. It work without any problem.

**Comment by stupidestmodder** [comment]
> I've managed to compile it on devices. It work without any problem.

could you provide more info about it?

**Comment by LesVu** [comment]
@stupidestmodder u can try using my fork to build deno on device. It take around 40 minutes as i have prebuilt rusty_v8.

**Comment by LesVu** [comment]
@stupidestmodder if got this error
```
error[E0308]: mismatched types
   --> build.rs:157:18
    |
157 | fn platform() -> &'static str {
    |    --------      ^^^^^^^^^^^^ expected `&str`, found `()`
    |    |
    |    implicitly returns `()` as its body has no tail or `return` expression

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rusty_v8`
```
you can go modify the build.rs in ../.cargo/registry/src/github.com-1ecc6299db9ec823/v8-0.34.0/build.rs
and find this
```
fn platform() -> &'static str {
  #[cfg(target_os = "windows")]
  {
    "win"
  }
  #[cfg(target_os = "linux")]
  {
    "linux64"
  }
  #[cfg(target_os = "macos")]
  {
    "mac"
  }
}
```
change to
```
fn platform() -> &'static str {
  #[cfg(target_os = "windows")]
  {
    "win"
  }
  #[cfg(any(target_os = "linux", target_os= "android"))]
  {
    "linux64"
  }
  #[cfg(target_os = "macos")]
  {
    "mac"
  }
}
```
