### ISSUE TITLE
Solve dpkg installation library not found or dependency problems prevent configuration

### ISSUE THREAD

**Issue by javinwei** [termux/termux-packages#5314]
```
**When installing using `dpkg -i php-fpm_7.2.12_aarch64.deb`:
dpkg: dependency problems prevent configuration of php-fpm:
 php-fpm depends on php; however:
  Package php is not installed.**
```
```
**Then try `dpkg -i php_7.2.12_aarch64.deb` to install:
dpkg: Dependency issues prevent PHP configuration:
Php depends on libxml2; however:
The software package libxml2 is not installed.
Php depends on libgd; however:
The software package libgd is not installed.
Php depends on freetype; however:
The freetype package is not installed.**
```
![S00517-15283520](https://user-images.githubusercontent.com/2794847/82167975-057ef200-98f0-11ea-9cb3-75dfb89cbbc5.jpg)
```
Tell me I need to install:
depends on libxml2、libgd、freetype
```

**Problem description**

I tried to install again:
`pkg install libxml2 libgd freetype`
Did not install successfully, he prompted me
`Try 'apt --fix-broken install' with no packages`
I tried `apt --fix-broken install`
Use `dpkg -i php_7.2.12_aarch64.deb` to reinstall,
The installation was successful this time, but when I use `php -v` to view this problem
Prompt I can't find the library "libandroid-glob.so"
![S00517-15303877](https://user-images.githubusercontent.com/2794847/82167977-0879e280-98f0-11ea-95b4-a26c3f2788ed.jpg)

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by Grimler91** [comment]
This is why we use apt and not dpkg, it installs dependencies for you. 

I can't reproduce the libandroid-glob issue so I guess you either have lots of outdated packages, or that you are trying to install packages for android >= 7 on an android 5 or 6 device. The output of `termux-info` would help determine which it is.

**Comment by javinwei** [comment]
> 这就是为什么我们使用apt而不是dpkg的原因，它会为您安装依赖项。
> 
> 我无法重现libandroid-glob问题，所以我想您要么有很多过时的软件包，要么您正在尝试在android 5或6设备上安装android> = 7的软件包。的输出`termux-info`将帮助确定它是哪个。

thank
