### ISSUE TITLE
usr/bin/env bad interpreter No such file or directory with custom prefix

### ISSUE THREAD

**Issue by sohutek** [termux/termux-packages#5319]
I created a boostrap file with my own prefix. After that termux works well with "npm install package_name" or other commands. Nothing wrong happens at all. But when i go "npm install -g package_name". I can't call that package_name. Just a message "/data/data/com.my_package/files/usr/bin/nodemon: usr/bin/env: bad interpreter: No such file or directory". I must be missing something. Thanks for your helps.

**Comment by xeffyr** [comment]
Few things to look at:
* Ensure that all your packages are recompiled with appropriate prefix - you can't reuse existing Termux packages with a different one.
* termux-exec should be patched with appropriate prefix too: https://github.com/termux/termux-exec/blob/master/termux-exec.c#L14

**Comment by sohutek** [comment]
Oh. Thanks you so much. I tried but still got it. Maybe i missed some prefix in somewhere. Can you just tell me all the places i must change prefix.

**Comment by Grimler91** [comment]
@sohutek grep and sed can help you with that
