### ISSUE TITLE
Package Request: PlantUml

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#532]
I would like to see the fully functional PlantUml. It exists in a version for python2.7, but resources are limited and you need a connection to the internet to generate diagrams in addition only to generate PNG. I would be able to generate diagrams in SVG format or LATEX format. PlantUml is a java application that depends only on Graphviz.
http://plantuml.com/

**Comment by buribu** [comment]
I am not sure that this is possible for these reasons ...

https://github.com/plantuml/plantuml/issues/464
https://github.com/andob/android-awt/issues/7

So I will use plantweb

https://pypi.org/project/plantweb/

**Comment by xtkoba** [comment]
Now that we have `openjdk-17` available, I believe it is rather straightforward to package this.
