### ISSUE TITLE
Package Installation on External Storage

### ISSUE THREAD

**Issue by Devesh7272** [termux/termux-packages#5323]
I want to ***Install Packages on External Storage*** 
Can you please help me how to install package in *custom* folder in external storage

**Comment by Hax4us** [comment]
See https://github.com/termux/termux-packages/issues/808

**Comment by xeffyr** [comment]
Packages can be installed only in
```
/data/data/com.termux/files/usr
```
That's absolute restriction due to hardcoded paths in binaries.

Another issue is that external storage do not have necessary features: unix permissions (chmod), symlinks & sockets support.
