### ISSUE TITLE
Can't start from files on sdcard

### ISSUE THREAD

**Issue by nakanakaii** [termux/termux-packages#5324]
**Problem description**
I replaced the place of public_html to my sdcard so I can edit them easily. I double checked that I've sd card permission enabled and the file is compiled correctly in my computer.
After I started the server it doesn't show any error but it's reading files from the previous position.

**Expected behavior**
It must read the files on sdcard or anywhere you put the directory to.

**Additional information**
LG-Q710AL
ANDROID 8.1.9
KERNEL: 3.18.79+
Termux Version: 0.94

**Comment by RossComputerGuy** [comment]
You can't run executables on the SDcard due to SELinux restrictions.

**Comment by xeffyr** [comment]
> You can't run executables on the SDcard due to SELinux restrictions.

If more correctly - due to `noexec` mount option which should take action earlier than SELinux will do that.

**Comment by xeffyr** [comment]
Scripts can be executed on sdcard with interpreter, like here:
```
bash ./scriptname.sh
python ./scriptname.py
php ./scriptname.php
node ./scriptname.js
perl ./scriptname.pl
```
