### ISSUE TITLE
Package request: moria

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#533]
_From @notorand-it on October 17, 2016 14:36_

We already have rogue (through brogue) and angband.
See here: https://en.wikipedia.org/wiki/Moria_(video_game) for the info (just in case).
Debian's repo is here: https://packages.debian.org/search?keywords=moria

_Copied from original issue: termux/termux-app#179_

**Comment by Neo-Oli** [comment]
Are the sources mirrored somewhere? The ftp server seems do be broken for weeks now.

**Comment by notorand-it** [comment]
Try here:
https://packages.debian.org/jessie/moria

**Comment by vishalbiswas** [comment]
@Neo-Oli https://github.com/HunterZ/umoria

**Comment by notorand-it** [comment]
I would prefer Debian repo

**Comment by sdrausty** [comment]
Lost in a dungeon in Moria...

![screenshot_20170728-174536](https://user-images.githubusercontent.com/27742457/28737512-d33a2cde-73bc-11e7-9fa1-6d36af1145d7.png)

**Comment by notorand-it** [comment]
Yeah! My dreams came true!
