### ISSUE TITLE
An issue updating TeXLive with tlmgr

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#5330]
Since I installed TL from unstable with the installer it is the second time I use `tlmgr` to maintain updated the installation. The first time all was fine. Now I have got this message:

```
[ 70/112, 06:14/06:41] update: ptex2pdf [8k] (54191 -> 55219) ... Can't open perl script "/data/data/com.termux/files/usr/tlpkg/tlpostcode/ptex2pdf-tlpost.pl": No such file or directory
/data/data/com.termux/files/usr/bin/texlive/tlmgr: calling post action script tlpkg/tlpostcode/ptex2pdf-tlpost.pl did not succeed in /data/data/com.termux/files/usr/share/texlive, status 2 at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 1775.
```

maybe I am wrong, but if I remember, you put things in `PREFIX/opt` and not `PREFIX/usr`

Can I fix that? How?

**Comment by Grimler91** [comment]
Try running termux-patch-texlive. Looks like the texmf.cnf has been restored to the upstream version

**Comment by angelog0** [comment]
> Try running termux-patch-texlive. Looks like the texmf.cnf has been restored to the upstream version

OK, and after this, how to fix the postinst for ptex2pdf? Thanks.

**Comment by Grimler91** [comment]
Reinstalling ptex2pdf would be the easiest, but otherwise you can look for the postinst command(s) for ptex2pdf in the texlive.tlpdb file and run it manually as well

**Comment by angelog0** [comment]
I think there is an issue.

```
$ termux-patch-texlive
Checking if $PREFIX/opt/texlive/cjk-gs-integrate.pl.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/crossrefware.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/pdfjam.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/pedigree.pl.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/texconfig.sh.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/texdef.pl.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/texmf.cnf.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/tlmgr.pl.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/tlshell.tcl.diff can be applied.. Nope
```

So tried (this results from texlive.tlpdb):

```
$ find $PREFIX/ -name "ptex2pdf-tlpost.pl"
/data/data/com.termux/files/usr/share/texlive/tlpkg/tlpostcode/ptex2pdf-tlpost.pl

$ /data/data/com.termux/files/usr/share/texlive/tlpkg/tlpostcode/ptex2pdf-tlpost.pl
bash: /data/data/com.termux/files/usr/share/texlive/tlpkg/tlpostcode/ptex2pdf-tlpost.pl: Permission denied
```

and then tried

```
$ tlmgr --repository $PREFIX/opt/tlrepo install --reinstall ptex2pdf
tlmgr: package repository /data/data/com.termux/files/usr/opt/tlrepo (verified)
[1/1, ??:??/??:??] reinstall: ptex2pdf [8k]
Can't open perl script "/data/data/com.termux/files/usr/tlpkg/tlpostcode/ptex2pdf-tlpost.pl": No such file or directory
/data/data/com.termux/files/usr/bin/texlive/tlmgr: calling post action script tlpkg/tlpostcode/ptex2pdf-tlpost.pl did not succeed in /data/data/com.termux/files/home, status 2 at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 1775.
running mktexlsr ...
done running mktexlsr.
running mtxrun --generate ...
done running mtxrun --generate.
tlmgr: package log updated: /data/data/com.termux/files/usr/share/texlive/texmf-var/web2c/tlmgr.log
```

You should reopen this.

**Comment by angelog0** [comment]
BTW, I find a `texmf-var` folder under `$PREFIX`.

```
$ ls $PREFIX/texmf-var/
fonts luatex-cache
```

Is this to be expected? 

Shouldn't this new method of installing TL2020 use only `$PREFIX/share/texlive` and `$PREFIX/opt/texlive`?

**Comment by Grimler91** [comment]
I can't reproduce the issue after updating through tlmgr. 

If you run `kpsewhich -var-value TEXMFROOT` it should tell you
```
/data/data/com.termux/files/usr/share/texlive
```
But it will tell you 
```
/data/data/com.termux/files/usr
```
or something like that. 

What is TEXMFROOT set to in the file `$PREFIX/share/texlive/texmf-dist/web2c/texmf.cnf`?

If it is not set to `/data/data/com.termux/files/usr/share/texlive` then we need to figure out why the `$PREFIX/opt/texlive/texmf.cnf.diff` patch failed (please share the full file in that case), and if it is set to `/data/data/com.termux/files/usr/share/texlive` then we need to figure out where else your TEXMFROOT variable is set.

> BTW, I find a texmf-var folder under $PREFIX.

That texmf-var folder was probably created when you used tlmgr just now with TEXMFROOT set to $PREFIX. `TEXMF{SYS,}VAR` is set correctly in the texmf.cnf file so I do not know why else it would be created at least (the TEXMFLOCAL variable might need to be fixed though).

**Comment by angelog0** [comment]
@Grimler91 wrote:

> I can't reproduce the issue after updating through tlmgr.
> 
> If you run `kpsewhich -var-value TEXMFROOT` it should tell you
> 
> ```
> /data/data/com.termux/files/usr/share/texlive
> ```

the same I get here...

> 
> But it will tell you
> 
> ```
> /data/data/com.termux/files/usr
> ```
> 
> or something like that.

NO.. 

> 
> What is TEXMFROOT set to in the file `$PREFIX/share/texlive/texmf-dist/web2c/texmf.cnf`?

I find

`TEXMFROOT = /data/data/com.termux/files/usr/share/texlive`

> 
> If it is not set to `/data/data/com.termux/files/usr/share/texlive` then we need to figure out why the `$PREFIX/opt/texlive/texmf.cnf.diff` patch failed (please share the full file in that case), and if it is set to `/data/data/com.termux/files/usr/share/texlive` then we need to figure out where else your TEXMFROOT variable is set.

So it seems I have all OK... but here it does not work as expected... remember the first time I updated with `tlmgr` it worked just fine..

> > BTW, I find a texmf-var folder under $PREFIX.
> 
> That texmf-var folder was probably created when you used tlmgr just now with TEXMFROOT set to $PREFIX. `TEXMF{SYS,}VAR` is set correctly in the texmf.cnf file so I do not know why else it would be created at least (the TEXMFLOCAL variable might need to be fixed though).

The fact is that when I run `tlmgr'  its time stamp changes...


To restart fro scratch, how can I uninstall it? I started just installing the `texlive-installer` package...

**Comment by angelog0** [comment]
I remove that folder:

`rm -rf $PREFIX/texmf-var`

and then tried to reinstall the ptex2pdf package as above. It failed in the same way and that folder was recreated (only with luatex-cache folder)...

**Comment by Grimler91** [comment]
I've added a patch for `tlpkg/TeXLive/TLUtils.pm` in https://github.com/termux/unstable-packages/commit/3ce235fbdc81145986adb268f7ef653307369f2a. Try upgrading to texlive-installer 20200406-2 in 15 minutes or so when the build finishes, and then try `termux-patch-texlive`, and then reinstall ptex2pdf again. Should work now, probably. 

Have not found where TEXMFVAR is set to $PREFIX/texmf-var though, so that remains a mystery for now.

To reinstall completely you can either just run the installer again (it overwrites old files), or `rm -rf $PREFIX/share/texlive` and then run the installer.

**Comment by angelog0** [comment]
I reinstalled from scratch texlive after upgrading to the new version of the installer. ptex2pdf has been installed without issues. Anyway after the installation and executing `tlmgr option autobackup 0` I find `texmf-var` in $PREFIX. Now it only contains `fonts` folder.. It seems that it is tlmgr that creates this `texmf-var` folder in $PREFIX

**Comment by xeffyr** [comment]
Let's have one issue regarding "tlmgr update problems": https://github.com/termux/termux-packages/issues/5949
