### ISSUE TITLE
Mutt v 1.14.1 debug

### ISSUE THREAD

**Issue by imnisp** [termux/termux-packages#5332]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

Does anyone know who is the maintainer (who compiled it for termux) of mutt?

I am ammending this.. I see that Henrik Grimler is the compiler but I see no way to contact him.
I am hoping he reads this post.

The most recent version (1.14.1) hasnt been compiled with +debug and I would like this capability without compiling it myself.

Thank you for all feedback.

**Comment by Grimler91** [comment]
I have now uploaded a debug build here: http://grimler.se/dists/testing/debug/binary-aarch64/mutt-dbg_1.14.1_aarch64.deb, replace `aarch64` with your arch if you are on another arch

**Comment by imnisp** [comment]
Sir,
 thank you kindly for rebuilding mutt for me with +debug. This will definitely aid my efforts with
mutt. I will begin delving into setting up my own tool chain for my compile needs. Inquiry: Do you
think your future builds will keep the +debug option? Again, thank you for taking your time to
extend for me me this kindness.

Virtually,
Douglas McDowall

**Comment by Grimler91** [comment]
@imnisp we will not build mutt or other packages with debug symbols as it increases the package size and most people have no use for it anyways. So I would recommend you to look into compiling it yourself, either by cross kompilation or by compiling on device
