### ISSUE TITLE
How to install the R package lme4 ? 

### ISSUE THREAD

**Issue by lizquierdo** [termux/termux-packages#5341]
How to install the R package lme4 ? , I m new in linux. Tks in adv Luis

**Comment by kcubeterm** [comment]
https://github.com/termux/termux-packages/issues/3230#issuecomment-455404697

**Comment by lizquierdo** [comment]
I have installed R . The problem is with lme4 , it is not rbase, etc. I think it must be compiled but i dont know how

**Comment by Grimler91** [comment]
@lizquierdo have you tried the instructions in the readme? https://github.com/lme4/lme4/blob/master/README.md#installation

**Comment by Grimler91** [comment]
Closing since we have not heard from OP
