### ISSUE TITLE
"gdbus-codegen" not found

### ISSUE THREAD

**Issue by SpinningK** [termux/termux-packages#5342]
**Problem description**
I try to build libsecret from source code in termux. It reported that there is no executable named "gdbus-codegen". I found that "gdbus-codegen" is in glib. So I installed realitive packages by:

> pkg install glib

> pkg install glib-bin

After that ,there should be "gdbus-codegen" in my xxx/usr/bin, but I only found "gdbus" and other executable in package "glib".

**Comment by xeffyr** [comment]
Added in `glib-bin 2.64.3-1`.
