### ISSUE TITLE
I can't run apt update the host is error

### ISSUE THREAD

**Issue by Gar2007** [termux/termux-packages#5344]
`<!--`
IMPORTANT: we are not accepting issues about Termux
installations running on Android 5.x-6.x.
-->

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
> I can't run apt update the host is error

Then switch to mirror with utility `termux-change-repo`. We can't do anything with host as we do not own it.
