### ISSUE TITLE
Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by jonasyumi** [termux/termux-packages#5350]
i trird all tools and same error
- - - help guys [

**Comment by xeffyr** [comment]
That's not a Termux issue.

Check whether your `apktool` is up-do-date, can run on architecture of your host (yes, apktool contains `aapt` binaries which architecute-specific). Ensure that changes made to app are valid.

**Comment by Hax4us** [comment]
@jonasyumi you can try this https://GitHub.com/Hax4Us/Apkmod
