### ISSUE TITLE
Golang ide support?

### ISSUE THREAD

**Issue by DiskGetor** [termux/termux-packages#5356]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by xeffyr** [comment]
Is this a question or package request ? If second, then fill
```
Home page:
```
and
```
Source code:
```
appropriate to that package.

**Comment by kcubeterm** [comment]
Install vs code visual studio code in termux
```
pkg install build-essential
pkg install nodejs yarn
yarn global add code-server
code-server --auth none
```
and then browse http://localhost:8080

Afterthat install go extension in vs code,
you can learn vs code tutorial from youtube or other platforms
