### ISSUE TITLE
How to install Linux-header and kernel-devel ?

### ISSUE THREAD

**Issue by hessam94** [termux/termux-packages#5358]
Hello,
I have a bug on making Makefile and it seems I need to get linux-headers package / kernel devel. because(I did it on Linux and it resolved). Please let me know which package should I get, Or do i need to get the binaries of packages(please give me a link). I am running android x_86 on VM. 
So appreciate

**Comment by Grimler91** [comment]
The kernel is device specific so we cannot package the headers. You would have to download the kernel source code and patch the Makefile to find it

**Comment by hessam94** [comment]
Thanks but i am new to this area. Could you help me more. When i tried to install it on linux i didn't specified any version for device or any thing. What do you mean by getting source code of kernel and patch?So appreciate


Sent from Yahoo Mail for iPhone


On Tuesday, June 2, 2020, 12:26 AM, Henrik Grimler <notifications@github.com> wrote:




The kernel is device specific so we cannot package the headers. You would have to download the kernel source code and patch the Makefile to find it

**Comment by Grimler91** [comment]
Android and termux is not a GNU/Linux system so you cannot expect them to behave the same, especially not if you want to compile some kernel module or something. 

Headers are part of the source code, so if you want the kernel headers you need to download the kernel source code. If you are using android x86 then see their instructions: https://www.android-x86.org/source.html

To be honest I think you are out of your depth here, it would probably be better to learn more about the Linux basics before trying to achieve whatever it is you are trying to achieve. Chances are pretty high that the project you are trying to compile will not work on android anyways.

**Comment by hessam94** [comment]
Thanks a lot for your comments. Actually yes you right as i said I am new to low level. 
I was installing docker on android , got binaries and installed it. Now after the running docker daemon, i have an error "CGroup is not configured". So i searched and found that we can write some modules and enable the cGroup. by looking at config.gz I see that it is NOT enabled. that is my project. But here is my question, if you say i need to get kernel source I am afraid The headers which you say are inside the kernel MUST HAVE COME with installation which i did. you mean I installed the android but some part of kernel (headers) are not installed? if yes , why??? 
Thanks again for kindly help

**Comment by xeffyr** [comment]
@hessam94 Linux kernel used on Android is not standard. It's manufacturer-specific and you can't install it from package repository.

If you are running Android x86, then its kernel sources are hosted here:
https://osdn.net/projects/android-x86/scm/git/kernel/tree/

> So i searched and found that we can write some modules and enable the cGroup.

CGroups can't be built as module. They are core functionality of Linux kernel and can be only either enabled or disabled permanently. Kernel modules are also version-specific and not portable.

>The headers which you say are inside the kernel MUST HAVE COME with installation which i did.

Headers are part of kernel source bundle.

**Comment by xeffyr** [comment]
Issue is locked as it not related to Termux or its packages.
Discussions about ROMs, custom kernels, rooting are *offtopic* here.
