### ISSUE TITLE
Access to Termux without Password

### ISSUE THREAD

**Issue by gjstreicher** [termux/termux-packages#5360]
I have used the passwd command several times, setting new passwords on my device.

I am still able to access my device via ssh from my PC without a password.

This is very unsafe!

**Comment by RossComputerGuy** [comment]
Check your ssh config. Do you have an SSH key being used?

**Comment by xeffyr** [comment]
Do you have any details ?

Key-based authentication does not require any password. If you configured one, that's not a security issue. Also Termux password authentication is implemented in such way that it just cannot work without password, i.e. no password == lockdown.

Such serious issues like this one must come with enough proof, so we will be sure that it actually exists and will be able to find out why and where it happens. You haven't provided any details of your configuration (both client & server side) or at least logs.

**I can't reproduce the issue, so I'm closing this. At least until you provide something that will prove existence of issue.**
