### ISSUE TITLE
libllvm build problem - omp.h No such file or directory

### ISSUE THREAD

**Issue by araczkowski** [termux/termux-packages#5363]
**Problem description**
I'm trying to build libllvm using the termux fork and termux packages workflow
the build step failed with error:
```
cp: cannot stat '../src/projects/openmp/runtime/exports/common.min/include/omp.h': No such file or directory
##[error]Process completed with exit code 1.
```

Could you please point me to the right direction how to solve this problem? Thanks in advance.

**Steps to reproduce**
1. fork termux
2. add action "Packages"
3. bump libllvm revision to start the build action 

**Expected behavior**
build step passed

**Additional information**
you can see this here: https://github.com/araczkowski/termux-packages/runs/735649262?check_suite_focus=true

![image](https://user-images.githubusercontent.com/1263968/83685404-e7e8a280-a5e8-11ea-99b0-cd59646e8948.png)

**Comment by its-pointless** [comment]
same issue occured when i updated docker image. It is fixed in my r21b update.

**Comment by araczkowski** [comment]
thx @its-pointless, @xeffyr, the workflows to build packages are piece of art, amazing job, chapeau bas! :)
trying to merge r21b and build on my local docker, I will let you know if I will be able to see something
