### ISSUE TITLE
Termux plugin and MacroDroid

### ISSUE THREAD

**Issue by lawson85** [termux/termux-packages#5366]
Android 8 and Android 10. 
**Problem description**

Popup says no ~./termux/tasker directory
**Steps to reproduce**

Install the termux tasker plugin from F-Droid, install MacroDroid from play store, launch Macroroid and press add macro button then in the blue area press the plus button, use the magnifier glass to search for Tasker and select tasker plugin and cho
![termuxError](https://user-images.githubusercontent.com/52282566/83696420-5b43e180-a5f4-11ea-97bc-f3fa2632d3eb.jpg)
ose termux. then you get the popoup

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
You need to create that directory and then place your scripts in it. It is not being created automatically.
```
mkdir ~/.termux/tasker
```
