### ISSUE TITLE
CANNOT LINK EXECUTABLE "wget" 

### ISSUE THREAD

**Issue by MrIM81** [termux/termux-packages#5367]
`$ wget`
`CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget"...`

Maybe this issues only android 10

**Comment by Grimler91** [comment]
Yes, and only some android 10 ROMs. Reported before in https://github.com/termux/termux-packages/issues/5367, that issue has a workaround that can be used until it is properly fixed

**Comment by red-star-fighter** [comment]
Issue mentions itself
