### ISSUE TITLE
How to access official rust documentation locally?

### ISSUE THREAD

**Issue by hnmn** [termux/termux-packages#5371]
`rustup` is not available in termux so, how run documentation locally.
Which is available through `rustup doc` command?

**Comment by xeffyr** [comment]
If you have `rust` installed, the html files are accessible through `$PREFIX/share/doc/rust/html`.

You can launch a local web server to read them in your browser, for example:
```
python -m http.server --directory $PREFIX/share/doc/rust/html
```
then open `127.0.0.1:8000` in your browser application.

Having `rustup` in Termux is quite pointless, Termux is not a standard Linux distribution and most of its functionality will not work.

![Screenshot_20200606-152723_Chrome](https://user-images.githubusercontent.com/25881154/83944206-55bfe480-a80a-11ea-89bf-8408c34bb8ce.jpg)
