### ISSUE TITLE
Mosh throws error 'cannot locate symbol "_ZN6google8protobuf8internal..." '

### ISSUE THREAD

**Issue by SmilingWhaaale** [termux/termux-packages#5378]
I'm running on Android 7.0. I'm trying to connect to my phone from my laptop, using mosh. Connection fails with the error message
```
CANNOT LINK EXECUTABLE "mosh-server": cannot locate symbol "_ZN6google8protobuf8internal17UnknownFieldParseEjPNS1_29InternalMetadataWithArenaLiteEPKcPNS1_12ParseContextE" 
referenced by "/data/data/com.termux/files/usr/bin/mosh-server"
```

I've only been following the steps describe on [the wiki](https://wiki.termux.com/wiki/Remote_Access). I'm running from my laptop
```
mosh --ssh="ssh -p 8022" 192.168.*.*
```

The same error is raised if I try to connect from my phone to my laptop (although this time mosh-client raises the error instead of mosh-server).

I do have ```pkg upgrade``` before installing mosh.

**Comment by xeffyr** [comment]
Fixed now. `pkg upgrade`.
