### ISSUE TITLE
Failed to start deamon adb didnt afk problem in termux

### ISSUE THREAD

**Issue by rashidh12** [termux/termux-packages#5380]
Plz solve this problem
In termux i wish to prank my buddy
With PhoneSploit but it keep showing this
![Screenshot_2020-06-09-04-08-27](https://user-images.githubusercontent.com/65683120/84087129-21fdde00-aa07-11ea-9dec-09f50ce58241.png)
But l already downloaded the adb file
But stil not working if anyone solving
This problem really appreciated thank you

**Comment by xeffyr** [comment]
1. We are not solving issues of third-party programs & scripts.
2. We are not helping with hacking.
