### ISSUE TITLE
Package request: clang-tidy

### ISSUE THREAD

**Issue by davemackintosh** [termux/termux-packages#5381]
**Package description**
clang-tidy is a clang-based C++ “linter” tool. 

**Link to home page and sources**
1. Home page: [https://clang.llvm.org/extra/clang-tidy/](https://clang.llvm.org/extra/clang-tidy/)
2. Source code: [https://github.com/llvm/llvm-project/tree/master/clang-tools-extra/clang-tidy](https://github.com/llvm/llvm-project/tree/master/clang-tools-extra/clang-tidy)

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
I did try compiling on device but device did not have enough resources and would crash/reboot every time. Couldn't get any specific error out of it.
* If it did work then please share any patches that you had to apply.

**Comment by xeffyr** [comment]
Closing as clang-tidy is now part of clang package.
