### ISSUE TITLE
start-stop-daemon from BusyBox

### ISSUE THREAD

**Issue by ntbatch** [termux/termux-packages#5383]
Start-stop-daemon stop work after last update(BusyBox v1.31.1).
Any command for start or stop app is error. E.g.
start-stop-daemon -q -x crond -S
start-stop-daemon: unable to stat //crond (No such file or directory)

**Comment by xeffyr** [comment]
start-stop-daemon is no longer provided by busybox. It was replaced by version from dpkg which expects absolute paths to executables.
```
start-stop-daemon -S -d $PREFIX -x $PREFIX/bin/applets/crond
```
