### ISSUE TITLE
squid : Bad system call

### ISSUE THREAD

**Issue by nniixxoossccnn** [termux/termux-packages#5388]
**Problem description**

```
REDMI8A $ squid -z
Bad system call
```
**Steps to reproduce**

I am not very sure whether this problem exists in other mobile phone systems. I do not have other mobile phones to test this.

My system is MIUI 11.0.9 Android 9 arm32
My phone is redmi8a

**Comment by tathastu871** [comment]
use following
proot -0
squid -z
Close the issue it will work. As proot -0 will provide temp root privilege within termux environment

**Comment by nniixxoossccnn** [comment]
It work! , thanks
