### ISSUE TITLE
Package request: x3270 and friends

### ISSUE THREAD

**Issue by KalmanReti** [termux/termux-packages#539]
The friends are c3270 (which doesn't need an x server) and s3270 which doesn't display at all, just makes 3270 interaction available to scripts.

**Comment by Rudi9719** [comment]
Not to Necro, but I'd like this package as well :)

**Comment by alexolivan** [comment]
Would have been nice to have the x-window x3270 client not disabled (although I guess that would have stepped over the termux x apps) so we could run it on a termux desktop... c3270 on an xterm does the job... but x3270 would have been just awesome.

Incredible job though, thanks :-)
