### ISSUE TITLE
Termux license

### ISSUE THREAD

**Issue by JoyalMaxwel** [termux/termux-packages#5390]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by JoyalMaxwel** [comment]
Please give license

**Comment by RossComputerGuy** [comment]
It's called [`LICENSE.md`](https://github.com/termux/termux-packages/blob/master/LICENSE.md) and its in this repo. This is not an issue, please look next time for a file like this.

**Comment by JoyalMaxwel** [comment]
Thank you

**Comment by JoyalMaxwel** [comment]
Termux app is not allowed license

On 12-Jun-2020 8:34 am, "Tristan Ross" <notifications@github.com> wrote:
>
> It's called LICENSE.md and its in this repo. This is not an issue, please
look next time for a file like this.

**Comment by RossComputerGuy** [comment]
What does that mean? Where are you getting that from?

**Comment by JoyalMaxwel** [comment]
Kerala

**Comment by RossComputerGuy** [comment]
I'm not able to find a program called that so this issue will probably be closed and marked off topic.

![image](https://user-images.githubusercontent.com/19699320/84461722-ff93dc80-ac21-11ea-962f-76bbc2bcb85b.png)

**Comment by JoyalMaxwel** [comment]
How to license apply

**Comment by RossComputerGuy** [comment]
That still does not provide enough information

**Comment by Grimler91** [comment]
@JoyalMaxwel as @RossComputerGuy said, your question does not make sense. Use google translate if you have to. Closing this, edit it with more information if you want help
