### ISSUE TITLE
I am unable to get the colourful words in termux

### ISSUE THREAD

**Issue by amanthakur386** [termux/termux-packages#5394]

**Comment by RossComputerGuy** [comment]
Could you elaborate? With what programs are you trying to get colorful words?

**Comment by blackbird2386** [comment]
My problem is that when I see termux on some other android , I see the
words are colourful , like for ex- 0%[working] , this text is in the yellow
colour but in my termux , it is in black and white , everything is black
and white . I request you to help me with this problem.

**Comment by RossComputerGuy** [comment]
Oh, they probably installed some sort of shell theme. Ask what other people use instead of here please. This is more for bugs and package requests.

**Comment by Grimler91** [comment]
You can echo colorful words with something like `printf "\033[0;31mHello world\033[0m\n"`. I guess you want to customize the colors of the terminal though. You can do that with the [termux-styling](https://wiki.termux.com/wiki/Termux:Styling) app
