### ISSUE TITLE
tcpsvd command not found

### ISSUE THREAD

**Issue by shiva2232** [termux/termux-packages#5395]
tcpsvd command not found after installing  sv command and ftpd command(documentation from the termux official web page).
After this installation I can't create an FTP server by both methods. What the hell in the official website. Even I can't access old one too. 😠😡🤬

**Comment by xeffyr** [comment]
> documentation from the termux official web page

Current documentation page shows:
```
pkg install busybox termux-services
source $PREFIX/profile.d/start-services.sh
sv-enable ftpd
sv up ftpd
```

See https://wiki.termux.com/wiki/Remote_Access#FTP. Documentation is **changing** from time to time.

`tcpsvd` is no longer standalone Busybox applet.

**Comment by Praizleye** [comment]
So how do you connect via ftpd  and edit your files on your smart phone

**Comment by xeffyr** [comment]
I use SFTP (OpenSSH). Why? - Because OpenSSH is secure and common tool which I use for remote access.

***

If Busybox-based FTP is so important for you, then
```
pkg install busybox
busybox tcpsvd -vE 0.0.0.0 1024 busybox ftpd -w /
```
However Termux has other solutions for plain FTP.

**Comment by Praizleye** [comment]
Please can u explain how you serve your SFTP(openssh).

**Comment by kcubeterm** [comment]
>  Please can u explain how you serve your SFTP(openssh).
  
Start sshd and connect via it by sftp , by default termux sshd start on port 8022, 
now use sftp like this
```sftp -P 8022 localhost```

It will connect with your sshd servers and then you can edit, removed, get, upload etc with file.

In case if you wanna connect with it via remote network you have to foward 8022 TCP port

**Comment by shiva2232** [comment]
Finally I found few solution, 
`busybox tcpsvd  localhost:5555`
Only previous version needs
`tcpsvd localhost:5555`
Now we have to add, `busybox` before that.
and,
`sftp -P 6666 localhost`

Thanks for all :+1:
