### ISSUE TITLE
Package request: fbi

### ISSUE THREAD

**Issue by KalmanReti** [termux/termux-packages#540]
which is a frame-buffer image viewer. If feasible to port, it would allow quickly looking at an image before deciding whether or not to delete it from the command line. (Apologies if there is already a package which can do this; I looked but nothing immediately sprang out. Imagemagick's display claims to need an X server.)

**Comment by xeffyr** [comment]
Termux doesn't use framebuffer (/dev/fb0 or /dev/graphics/fb0) to render console output. So you can't use fbi and other framebuffer viewers.

Even if it possible to use fbi on android, it will require root as regular apps can't access framebuffer device:
```
herolte:/ $ ls -l /dev/graphics/fb0                                            
crw-rw---- 1 root graphics 29,   0 2018-06-29 10:30 /dev/graphics/fb0
```

**Comment by xeffyr** [comment]
Closing since this package is subject for https://github.com/termux/termux-root-packages.
