### ISSUE TITLE
Termux styling

### ISSUE THREAD

**Issue by blackbird2386** [termux/termux-packages#5400]
I recently purchased the termux styling but I do not understand how to access it . I do not get any colour ful syntax

**Comment by Grimler91** [comment]
Longpress, press more, press style and then select color or font

**Comment by blackbird2386** [comment]
Sir , I request you to please see this attached picture. Sir, I am unable
to get the colourful form of the highlighted words. I can see it colourful
in various platform but I am unable to get it.

I request you to please help me with this problem.

**Comment by Grimler91** [comment]
@blackbird2386 you have not attached any picture in the github issue

**Comment by Harshiv-Patel** [comment]
@blackbird2386 there you go :
[A short demo for accessing styling options](https://youtu.be/wWTI551im6U) 

Mind I just uploaded it so you'll have to watch it on a PC or download/pirate it with full quality to see finer details

**Comment by xeffyr** [comment]
@Harshiv-Patel Colored output is enabled by default, so `ls --color=auto` is redundant.

**Comment by xeffyr** [comment]
It is possible that on some devices Termux will be really black&white only, but that case isn't eligible for fixing because OS issue.
