### ISSUE TITLE
Worth creating PRs for anything here?

### ISSUE THREAD

**Issue by qwerty12** [termux/termux-packages#5403]
I've been using Termux for a while and in that time, I've packaged a fair few things up. These have all been built on my aarch64 Android 9 phone; I'll test in the Docker image before submitting anything. I would be happy to create issues/PRs for anything here that piques interest. I know asking to ask is frowned upon but I figured in this case that was preferable to an onslaught of PRs.

~~1. Not sure, but wouldn't it be best if in [packages/openssh/misc_c.patch](https://github.com/termux/termux-packages/blob/master/packages/openssh/misc_c.patch#L9)  `"*"` was `xstrdup`'d too?~~

2. Personal preference: I prefer GNU `which` to debianutils' Perl version. It links only to libc, can be configured to show you matching Bash aliases, and is [easily built](https://pastebin.com/raw/0P98vvp4). debianutils' build.sh would need [updating](https://pastebin.com/raw/yTMVcnw5) to rm its own `which`.

~~3. I have a libelf package (also: 180 is out) that matches the Arch package a bit more: libasm.so and libdw.so are present and the full headers and pkg-config files are installed. **But** to get libdw to build with Clang, I used [this](https://sourceware.org/legacy-ml/elfutils-devel/imported/msg03970.html) patch. This makes the libelf package itself depend on libblocksruntime (which I have a package for), which may be less than ideal. Saying that, it's only libdw.so - not libelf.so - that links to libBlocksRuntime.so.0~~

~~4. In the transmission package, some unimportant changes:
    *  `--disable-gtk` should be replaced with `--without-gtk`
    * I believe [this](https://github.com/transmission/transmission/blob/2ef07517b65e98c0c68bbff0ca2467434a1835d2/libtransmission/file-posix.c#L340) is fine on Android (not sure since which API level, however), just needs `-D_POSIX_C_SOURCE=200809L` in the CFLAGS for it to work
    * I'd consider this unofficial [patch](https://github.com/AndreyPavlenko/transmission/commit/0c1acda3e001fc23b33ebc760aee333ab6258171.patch)
    * [This](https://github.com/transmission/transmission/blob/master/libtransmission/platform.c#L652) needs the `@TERMUX_PREFIX@` treatment~~

~~5. I have [ctypes.sh](https://github.com/taviso/ctypes.sh) ("allows you to call routines in shared libraries from within bash") packaged with a couple of fixes; tests/structs.sh and tests/qsort.sh now succeed. However, for struct support, it requires the modified libelf package as per 3). I actually use this one to disable Wi-Fi power saving every 20 seconds without spawning anything.~~

~~6. I have a package for Samba 4.12.3 (and its build-deps rpcsvc-proto and perl-parse-yapp). However, I disable building many things (there's no `winbindd`), there's a *lot* of patches (most not mine, and the ones that are aren't well-written and probably buggy), I've not tested `nmbd` and if left running for two days, `smbd`'s CPU usage goes to 100%. 
Also, because I reused Berserker's patches, `smbd` thinks it's running as root. For sharing the internal and external memory card of your phone, that's not an issue, but there may be problems with anything else. And you'd ideally want to run `smbd` on a rooted phone so that port 445 is available to it. 
Mind you, even without root, over USB `smdb` makes for an excellent alternative to MTP for managing the internal memory of your phone ([this](https://www.nikhef.nl/~janjust/CifsOverSSH/Win10Loopback.html) but with `adb forward` instead of PuTTY). Maybe one for the unstable-repo?~~

~~7. I do have a working `ghc` 8.10.1 of sorts. It's a mess, and I'm using bad hacks to get the thing to build and start, and I don't think it can be packaged the way I've built it, but it's enough to build a statically-linked aarch64 API 28 shellcheck 0.7.1 binary in Termux itself (which is the *only* thing I wanted Haskell for). 
In shellcheck's case, you can run the official static aarch64 binary in `proot` but on some scripts, it breaks with "<stdout>: commitBuffer: invalid argument (invalid character)" - my native binary works fine.~~

Also, these may be useful to only me, but I have packages for:
- [alass](https://github.com/kaegi/alass) (automatically synchronise subtitles to movies)
- [as-tree](https://github.com/jez/as-tree) (`tree` that you can pipe into)
- broot ([existing issue](https://github.com/termux/termux-packages/issues/4858))
- [desed](https://github.com/SoptikHa2/desed) (interactive sed script debugger; I've not actually used it)
- [grex](https://github.com/pemistahl/grex) (generates a single regular expression from user-provided test cases)
- [massren](https://github.com/laurent22/massren) (mass rename files using your text editor)
- "lightweight speech recognition engine" [pocketsphinx](https://github.com/cmusphinx/pocketsphinx) (for [subsync](https://github.com/sc0ty/subsync) - no package for that, installed from `pip`)
- [vgrep](https://github.com/vrothberg/vgrep) (an easy to use front-end for (git) grep [and ripgrep]).

**Comment by xeffyr** [comment]
Sure, you can submit PRs for all these things.

> I have a package for Samba 4.12.3

> I do have a working ghc 8.10.1 of sorts.

This should go to https://github.com/termux/unstable-packages.

**Comment by qwerty12** [comment]
Great, I'll start today and get the easier ones out of the way :)

> I have a package for Samba 4.12.3
> This should go to https://github.com/termux/unstable-packages.

Can Samba's two additional build dependencies go into the main repository or should they also be in unstable-packages?

> I do have a working ghc 8.10.1 of sorts.

Sorry, my first comment was a bit too long so I left a lot of things out but I'll go into more detail here about GHC.

I don't actually have a package for `ghc`. I actually built GHC outside of the Docker container, using Ubuntu Focal's `ghc` and `llc-10`, a standalone toolchain directly from the latest NDK but linked against libiconv etc. as provided by Termux. 
My current install process is doing `make install DESTDIR`, running a horrible hack using patchelf to correct the bad RUNPATH, using patchelf to add NEEDED entries for libm.so to some Haskell libraries and then tarring the entire thing up and unpacking on my phone. 
My reason for building outside was that I was getting odd compilation errors that I hoped would go with a different toolchain. I haven't tested building it inside the container as of yet.

To cross-compile GHC, you need a working GHC on the host to build the stage 0 GHC. I used Ubuntu's. I won't put `sudo apt install ghc  happy alex && sudo apt build-dep ghc` inside a proposed build.sh but it's something I need to run before `build-package.sh`.

All that aside, the actual build process isn't too bad, actually. aarch64-linux-android is assumed everywhere, I'll do my best with that. There's a not-so-nice patch that adds specific `configure` arguments if stage > 0 (e.g. outisde of the container `--with-iconv-libraries=/data/data/com.termux/files/usr/lib` would cause stage 0 to fail, but is needed for every stage after that).

If I can't produce a package that at least builds in the Docker container locally, I'll write up a guide at least.

**Comment by xeffyr** [comment]
@qwerty12 GHC needs fix for `arm-unknown-linux-androideabi`.

**Comment by qwerty12** [comment]
@xeffyr I can get it to build, but `ghc` segfaults when I run it on my HTC M8:

```
thread #1, name = 'ghc', stop reason = signal SIGSEGV: address access protected (fault address: 0x843597b4)
    frame #0: 0x843597b4 ghc`base_GHCziEventziManager_new4_closure
ghc`base_GHCziEventziManager_new4_closure:
->  0x843597b4 <+0>: .long  0x83ed1418                ; unknown opcode
    0x843597b8 <+4>: andeq  r0, r0, r1 

ghc`base_GHCziEventziManager_new6_closure:
    0x843597bc <+0>: .long  0x83ea9a24                ; unknown opcode

ghc`r8TE_closure$def:
    0x843597c0 <+0>: .long  0x83ea9a8c                ; unknown opcode
```

I'll continue to see if I can do anything, but I can't promise anything.

**Comment by xeffyr** [comment]
Ok, then ARM can wait.

**Comment by xeffyr** [comment]
GHC i686 doesn't work, segmentation fault. `x86_64` build works without issues.

**Comment by qwerty12** [comment]
Sorry, no idea. Spent all day yesterday and some of this morning trying to get ARM to work; now I'm out of ideas.
