### ISSUE TITLE
Missing zlib support for OpenSSL

### ISSUE THREAD

**Issue by mrjk** [termux/termux-packages#5410]
**Problem description**
Missing zlib support for OpenSSL.

**Steps to reproduce**
```
openssl help |& grep zlib && echo success || echo fail
```
This is a self explanatory test I guess :)

**Expected behavior**
OpenSSL should be able to support zlib extension. The first usage is to be able to open Android Backup files. There are some other way to open those files, but none of them worked under termux.

**Additional information**
I guess the patch is as simple as this, but as I can't test and build the package on my phone, I don't want to make a PR:
```
$ git diff  packages/openssl/build.sh
diff --git a/packages/openssl/build.sh b/packages/openssl/build.sh
index 6e8cb1e3f..6c9d74263 100644
--- a/packages/openssl/build.sh
+++ b/packages/openssl/build.sh
@@ -37,8 +37,7 @@ termux_step_configure() {
    --openssldir=$TERMUX_PREFIX/etc/tls \
    shared \
    no-ssl \
-   no-comp \
-   no-dso \
+   zlib-dynamic \
    no-hw \
    no-srp \
    no-tests
```

**Comment by xeffyr** [comment]
Already fixed with https://github.com/termux/termux-packages/commit/ff3e4e80a7d5607f9d2df45d061a6b5351b5dcb0.

**Comment by mrjk** [comment]
Damn ... <3 Thank you so much :))
