### ISSUE TITLE
seems no common lisp package

### ISSUE THREAD

**Issue by sw2wolf** [termux/termux-packages#5415]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.
$ pkg search lisp
...
picolisp/stable 20.2.9 aarch64
  Lisp interpreter and application server framework

**Comment by Grimler91** [comment]
sbcl and clisp has been requested in https://github.com/termux/termux-packages/issues/183. ecl is available from its-pointless repo: https://wiki.termux.com/wiki/Package_Management#Community_repositories
