### ISSUE TITLE
package request: libsecret

### ISSUE THREAD

**Issue by zababurinsv** [termux/termux-packages#5416]
i need install npm install keytar on termux
But this library uses libsecret-1-dev
Install on Debian/Ubuntu
sudo apt-get install libsecret-1-dev 
But i don't have sudo on termux and i can't install this library
How can i use this ?

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by Grimler91** [comment]
Termux isn't ubuntu or debian so you don't need sudo.

You need to compile libsecret from source for now, until someone compiles the package for our repository

**Comment by zababurinsv** [comment]
> Termux isn't ubuntu or debian so you don't need sudo.
> 
> You need to compile libsecret from source for now, until someone compiles the package for our repository

How can i do this ? Is there any documentation ?

**Comment by Grimler91** [comment]
@zababurinsv https://gitlab.gnome.org/GNOME/libsecret/-/blob/master/README.md

**Comment by xeffyr** [comment]
Requires gobject-introspection which is not available as Termux package.

Meson is required too, but it can be just downloaded from https://github.com/mesonbuild/meson/releases/download/0.54.3/meson-0.54.3.tar.gz and added to PATH.

**Comment by xeffyr** [comment]
If you are trying to install code-server which requires **keytar** as npm dependency, then use
```
yarn global add code-server
```
That will eliminate requirement of `libsecret`.

<img src="https://user-images.githubusercontent.com/25881154/84954099-7129ca00-b0fd-11ea-9f69-334e8d68ce9e.jpg" width="320"/>

Build-time dependency `gobject-introspection` isn't going to be added, at least for now. Anyone who know how to properly **cross-**compile it is welcome to submit pull request.

**Comment by zababurinsv** [comment]
Thank yours very mach/ Yes i want install server-code and without auth it is work.

But for the system to be complete, this library is needed.

**Comment by kcubeterm** [comment]
Re-opening as libsecret is't available in termux.

**Comment by MisterY** [comment]
One apparent use is as a Git credentials helper ([source](https://www.softwaredeveloper.blog/git-credential-storage-libsecret)). I'd be quite interested in this.

**Comment by suhan-paradkar** [comment]
@kcubeterm I was able to compile libsecret natively on my device with a simple patch , but faced issues while doing the same in the build environment (docker image)....it has cross compilation issues...

**Comment by suhan-paradkar** [comment]
Well.. since gobject-introspection is now available...
Hence libsecret

**Comment by suhan-paradkar** [comment]
@xeffyr please close this

**Comment by nerd190** [comment]
This should be more than add a binary, it needs to populate files within `$PREFIX/share/doc/git/contrib/credential/libsecret`,
I am unable to use `libsecret` to store my `git` credentials as there is nothing to `make` :(

**Comment by sukulent** [comment]
Hello, I am unable to use libsecret with git.
Seems similar to @nerd190 's problem
Throws this error:

`/usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret get: 1: /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret: not found`
