### ISSUE TITLE
Alguém  me ajuda com esse erro pfvr!!!???

### ISSUE THREAD

**Issue by PlayerSolo** [termux/termux-packages#5419]
CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget"...

**Comment by xeffyr** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/4615.

**Comment by PlayerSolo** [comment]
> Duplicata de [# 4615](https://github.com/termux/termux-packages/issues/4615) .

**Comment by PlayerSolo** [comment]
Oque isso significa!?
;-;
