### ISSUE TITLE
Unable to run mpv (stack corruption detected on Galaxy S7)

### ISSUE THREAD

**Issue by ceebu** [termux/termux-packages#542]
I installed mpv but am unable to run it - I get "stack corruption detected" - Am on Galaxy s7 edge and not rooted. Not sure if this makes any difference, but I have setup the storage as well..

**Comment by fornwall** [comment]
Does it happen when just running `mpv`, or do you need to play a file?

If it happens only when playing a file, could you see if it happens with multiple files (different formats)?

**Comment by ceebu** [comment]
It happens when I just run the mpv  command. Ideally it should return a message with the command options,  but get stack corruption

**Comment by ceebu** [comment]
Is there any logging / troubleshooting that I can do to better understand why this error?

**Comment by amaurea** [comment]
I can get it to play audio and ascii video on a Samsung Galaxy S7 by running the executable directly:

     /data/data/com.termux/files/usr/libexec/mpv -vo=tct yuyuko.mp4

This skips the setup of LD_LIBRARY_PATH. I do however run with my own value of LD_LIBRARY_PATH, which is `/data/data/com.termux/files/home/local/lib:/data/data/com.termux/files/usr/lib
`. The first of these is an empty directory for now, and the last is shared with the path in the wrapper, so I guess there's something in `/system/lib64:/system/vendor/lib64` that breaks things.

**Comment by ceebu** [comment]
Thanks amaurea!  I was able to play using the direct file link as well. thanks for finding the cause and the workaround.. at least now, I can use mpsyt :-) :-)

**Comment by pranavg189** [comment]
Thanks amaurea! your solution helped me too :+1:

**Comment by fornwall** [comment]
@ceebu @amaurea @pranavg189 Does updating to the latest 0.24.0-1 version of mpv with `apt update && apt upgrade` fix the issue?

**Comment by amaurea** [comment]
@fornwall Yes, it fixes it. Thanks. (Any way of getting non-ascii video, by the way? E.g. directly on the phone where the sound ends up anyway)

**Comment by fornwall** [comment]
@amaurea Great, thanks! It's not currently possible, you have to use an external player for that now - but it may be in the future!
