### ISSUE TITLE
Package request: Findomain 

### ISSUE THREAD

**Issue by Edu4rdSHL** [termux/termux-packages#5423]
**Package description**

Findomain is the fastest subdomain enumerator and the only one written in Rust. Additionally it's one of the most loved tools because the automation that this provides.

**Link to home page and sources**
1. Home page: https://findomain.app
2. Source code: 
https://github.com/Edu4rdSHL/findomain

**Additional information**

Have you compiled or tried to compile the package on device?
* Yes, the package needs rust, perl and make - to compile. See https://github.com/Edu4rdSHL/findomain#installation-android-termux

**Comment by RupankarGhosh** [comment]
You can simply build it in your device....no need to add in official repo. Adding everything in the repository will make the repo.file huge to update everytime.
