### ISSUE TITLE
Error: dlopen failed: cannot locate symbol "__atomic_fetch_add_4" referenced by 

### ISSUE THREAD

**Issue by zababurinsv** [termux/termux-packages#5432]
I install gulp-sass and node-sass
run gulp task.
when I start the gulp I get the following error.

[03:52:02] Requiring external module @babel/register
Error: dlopen failed: cannot locate symbol "__atomic_fetch_add_4" referenced by "/data/data/com.termux/files/home/core/node_modules/node-sass/vendor/android-arm-83/binding.node"...
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at module.exports (/data/data/com.termux/files/home/core/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/data/data/com.termux/files/home/core/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module._compile (/data/data/com.termux/files/home/core/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core@1.0.0 gulp.watch.slyle: `gulp gulp.watch.style`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the core@1.0.0 gulp.watch.slyle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2020-06-22T00_52_08_536Z-debug.log

 on the computer, this code works.
 Internet tips do not help.
 How can I fix this error?

**Comment by Grimler91** [comment]
Try reinstalling node-sass after running `export LDFLAGS=-latomic`, this type of error happens on arm for some codes. See https://github.com/termux/termux-packages/issues/3092

**Comment by zababurinsv** [comment]
It is not working.

20-06-22T10_33_41_945Z-debug.log                           $ export LDFLAGS=-latomic                                  $ npm run gulp.watch.slyle                                                                                            > core@1.0.0 gulp.watch.slyle /data/data/com.termux/files/home/core                                                   > gulp gulp.watch.style                                                                                               [13:39:30] Requiring external module @babel/register       Error: dlopen failed: cannot locate symbol "__atomic_fetch_add_4" referenced by "/data/data/com.termux/files/home/core/node_modules/node-sass/vendor/android-arm-83/binding.node"...                                                            at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)                                           at Module.load (internal/modules/cjs/loader.js:1049:32)    at Function.Module._load (internal/modules/cjs/loader.js:937:14)                                                      at Module.require (internal/modules/cjs/loader.js:1089:19)                                                            at require (internal/modules/cjs/helpers.js:73:18)         at module.exports (/data/data/com.termux/files/home/core/node_modules/node-sass/lib/binding.js:19:10)                 at Object.<anonymous> (/data/data/com.termux/files/home/core/node_modules/node-sass/lib/index.js:14:35)               at Module._compile (internal/modules/cjs/loader.js:1200:30)                                                           at Module._compile (/data/data/com.termux/files/home/core/node_modules/pirates/lib/index.js:99:24)                    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)                                                npm ERR! code ELIFECYCLE                                   npm ERR! errno 1                                           npm ERR! core@1.0.0 gulp.watch.slyle: `gulp gulp.watch.style`                                                         npm ERR! Exit status 1
npm ERR!                                                   npm ERR! Failed at the core@1.0.0 gulp.watch.slyle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                               npm ERR! A complete log of this run can be found in:       npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2020-06-22T10_39_36_342Z-debug.log                           $

**Comment by Grimler91** [comment]
> npm run gulp.watch.slyle

Try reinstalling node-sass, as I said, rather than running gulp

**Comment by xeffyr** [comment]
Are you reinstalling modules from scratch or `./node_modules` is already available. It looks like something is not being rebuilt.

You are hitting Android linker's dlopen issue https://github.com/android-ndk/ndk/issues/201, one or more dependencies is not linked with library providing symbol "__atomic_fetch_add_4".

**Comment by zababurinsv** [comment]
./node_modules is already available. Now i can remove node_modules and reinstall all npm modules. 
Maby it is string export LDFLAGS=-latomic add to .profile ?

**Comment by zababurinsv** [comment]
I am delete node_modules delete package.lock.json
Add export 
![Screenshot_20200622-231313_Termux](https://user-images.githubusercontent.com/22741813/85331129-3b5e5a00-b4de-11ea-9d66-966e1ae67d60.jpg)

But there is still a mistake

Maybe i nshould add some othen flah ?

**Comment by zababurinsv** [comment]
Thanks. 
I created flag 
export LDFLAGS="-u__atomic_fetch_add_4 -latomic"
and node-sass to working
