### ISSUE TITLE
Python-apsw

### ISSUE THREAD

**Issue by scott8** [termux/termux-packages#5434]
**Package description**

**Link to home page and sources**
1. Home page: https://rogerbinns.github.io/apsw/
2. Source code: https://rogerbinns.github.io/apsw/download.html
3.  Build instructions: https://rogerbinns.github.io/apsw/build.html#recommended-build

**Additional information**
Have you compiled or tried to compile the package on device? Yes
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.
No patches.
Test did not work right but should be easily fixed.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests

```
pkg install python build-essential
pip install apsw
```
