### ISSUE TITLE
Termux "fatal error: 'Python.h' file not found" resolved

### ISSUE THREAD

**Issue by xKatooo** [termux/termux-packages#5436]
I have solved the problem "fatal error: 'Python.h' file not found" in Termux with the following: 

First go to the folder that contains Python.h in my case use 
```cd $PREFIX/include/Python3.8/``` 
and here copy the file Python.h and take it to include with 
```cp Python.h $PREFIX/include``` 

this solved the problem

PS: follow me

Ilu si much <3

**Comment by xeffyr** [comment]
Normal build systems (including `cython`) respect Python configuration print by 
```
python3.8-config --includes
python3.8-config --libs
python3.8-config --cflags
```
What you are doing I don't know and your workaround will cause more issues than solve.

**Comment by xKatooo** [comment]
> Normal build systems (including `cython`) respect Python configuration print by
> 
> ```
> python3.8-config --includes
> python3.8-config --libs
> python3.8-config --cflags
> ```
> 
> What you are doing I don't know and your workaround will cause more issues than solve.

True, sorry, please delete this UwU
