### ISSUE TITLE
Text not rendering until a space or special character is pressed 

### ISSUE THREAD

**Issue by inmanturbo** [termux/termux-packages#5437]
**Problem description**

Text in insert mode or something. I've tried resetting my keyboard settings. I have had turmux on this phone for a long time. I use it for testing remote access security from within the data center. And to get a secure shell when needed on the go.
**Steps to reproduce**

I'm  not sure how to reproduce it. Termux works fine on my tablet.
**Expected behavior**

Type into the terminal and text renders character by character as typed
**Additional information**

```
Cant type turmux-info
```
![Screenshot_20200623-082401_Termux](https://user-images.githubusercontent.com/47095624/85403726-ddf0fa00-b52b-11ea-9bd1-de89fdad1442.jpg)

**Comment by xeffyr** [comment]
Known issue, see https://github.com/termux/termux-app/issues/686.

**Comment by inmanturbo** [comment]
> Known issue, see [termux/termux-app#686](https://github.com/termux/termux-app/issues/686).

Thanks. On my phone, missed the open issue.
