### ISSUE TITLE
libespeak

### ISSUE THREAD

**Issue by mischievousdev** [termux/termux-packages#5438]
How do i install libespeak1?

**Comment by mischievousdev** [comment]
For pyttsx3

**Comment by xeffyr** [comment]
Try `pkg install espeak`.

**Comment by mischievousdev** [comment]
Yes i already done, but returns: `OSError: dlopen failed: library "libespeak.so.1" not found`

**Comment by rishi7980** [comment]
MY DEVICE NOT WORKING ls comend and cd comend

**Comment by mischievousdev** [comment]
Hello?

**Comment by Grimler91** [comment]
@mischievousdev please fill in the requested information in the [bug report template](https://github.com/termux/termux-packages/issues/new?template=bug_report.md), we need to know how to reproduce the issue and what your output of `termux-info` is

**Comment by xeffyr** [comment]
@Grimler91 This is not a bug. We just use espeak-ng instead of espeak. They have different library names.

**Comment by Grimler91** [comment]
Ah yes, nevermind

**Comment by mischievousdev** [comment]
So, how do i fix that??

**Comment by xeffyr** [comment]
> how do i fix that??

I can't suggest anything other than building libespeak from sources.

**Comment by mischievousdev** [comment]
how can i?? any resources??

**Comment by rishi7980** [comment]
I NEED SHARPSHOOTER CRACK APK YOU HELP ME PLEASE

**Comment by SDRausty** [comment]
> how can i?? any resources??

https://wiki.termux.com/wiki/Building_packages

**Comment by xtkoba** [comment]
Sounds like just a matter of naming convention that a shared library does not have a version suffix on Android.

I guess this may help:

```
cd $PREFIX/lib && ln -s libespeak-ng.so libespeak-ng.so.1
```
