### ISSUE TITLE
WHENEVER IT ASKS DO YOU WANT TO CONTINUE THATS HAPPEN!

### ISSUE THREAD

**Issue by erencq** [termux/termux-packages#5439]
**Problem description**
When termux asks : Do you want to continue ? [Y/n] im writing y and im accepting and it says ''Abort'' 
![image](https://user-images.githubusercontent.com/67325396/85409147-1d403a80-b56e-11ea-94ce-d9494776c156.png) also im using pc and idk why it happens all the time :(

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
Ensure you are using english `y`. If english `y` doesn't work, then you have a keyboard bug which inserts some invisible characters after `y` - in this case use non-interactive mode `apt upgrade -y`, `apt install -y`, etc.

**Comment by SDRausty** [comment]
@erencq just tap enter.  It should choose Y for you.

**Comment by xeffyr** [comment]
@SDRausty That may not work if keyboard doesn't send just `\n` on enter.

**Comment by IAMRKK03** [comment]
Not working tried everythin said above

**Comment by xeffyr** [comment]
@IAMRKK03 If even `-y` option (used like `apt upgrade -y`) doesn't work for you, then something wrong with your device.

*Perhaps I need to make a list of incompatible devices...*

**Comment by WMCB-Tech** [comment]
How about piping with `yes`

`yes | apt install <package>`
