### ISSUE TITLE
tigervnc not found

### ISSUE THREAD

**Issue by mandeep-sinng** [termux/termux-packages#5440]
i get error installing tigervnc(x11-repo is already installed)
`$ pkg search vnc
Sorting... Done
Full Text Search... Done
$`

`$ pkg install tigervnc
...
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package tigervnc
$`

**Comment by xeffyr** [comment]
https://github.com/termux/x11-packages/issues/222
