### ISSUE TITLE
ls and dir command are not working

### ISSUE THREAD

**Issue by debajiteziodutta** [termux/termux-packages#5442]
I am using Redmi Note 8 and here ls and dir command are not working. Here, the screenshot reference for the same.

![Screenshot_2020-06-24-00-26-10-318_com termux](https://user-images.githubusercontent.com/51490675/85445830-6a91cb80-b5b1-11ea-8680-cb27ff23065e.jpg)

**Comment by Grimler91** [comment]
Are you sure that your current directory is not empty?

(Try `ls -al`)

**Comment by debajiteziodutta** [comment]
Yes, the default "home" directory was empty, thanks.
