### ISSUE TITLE
{feature request} opengl es and vulkan support.

### ISSUE THREAD

**Issue by SamarJi** [termux/termux-packages#5443]
Description:-
Currently, termux doesn't support opengl es or vulkan. Or simply there is no direct support for video backend for termux. 

Why it is needed :-
I am running ubuntu on it (termux), but there is no GPU support to run 3d games.

Sorry, but this doesn't require any package , you may add a support customly.

Please

**Comment by RossComputerGuy** [comment]
There is freeglut https://github.com/termux/x11-packages/issues/78

**Comment by SamarJi** [comment]
Ok

**Comment by RossComputerGuy** [comment]
https://github.com/termux/x11-packages/issues/71 but I don't think there will be vulkan support

**Comment by SamarJi** [comment]
But, can it support opengl

**Comment by RossComputerGuy** [comment]
I don't think mesa has OpenGL enabled.

**Comment by SamarJi** [comment]
By default
Everything is disabled.
Can I enable it

**Comment by RossComputerGuy** [comment]
Mesa was configured at build time with GL disabled so you would need to rebuild mesa with GL enabled. https://github.com/termux/x11-packages/issues/121

**Comment by SamarJi** [comment]
I can rebuild it , but I don't know how to install.

While rebuilding, I will replace -disable with -enable

**Comment by SamarJi** [comment]
Like this

```
--enable-asm
--enable-gbm
--enable-egl
--enable-gles1
--enable-gles2
--enable-dri
--enable-dri3
--enable-llvm
--enable-glx=xlib
--with-platforms=x11
--without-dri-drivers
--without-gallium-driver
```

**Comment by RossComputerGuy** [comment]
Just note that tigervnc and other programs may break or OpenGL might not work because this is Android and not your normal Linux distro.

**Comment by SamarJi** [comment]
So, I never can get opengl in termux

**Comment by RossComputerGuy** [comment]
Maybe, I'm not sure but someone else probably knows.

**Comment by SamarJi** [comment]
I will try to rebuild it

But , how can I check whether it is worked or not.

Is there is command to check like
```
glxinfo

glxgears
```

**Comment by RossComputerGuy** [comment]
No, that's from mesa demos

**Comment by SamarJi** [comment]
I will build packages that requires to run 3d game in ubuntu for termux.

See what happens

**Comment by xeffyr** [comment]
There is a reason why I have disabled DRI & OpenGL (ES) in Mesa. It breaks things like tigervnc.

As there NO people in Termux dev team who can get it working, that request is a won'tfix and we won't work on OpenGL & Vulkan support.

As written in https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests:
> Package should NOT require hardware graphics acceleration or in any way access to GPU hardware device.

**Comment by SamarJi** [comment]
Ok

**Comment by xeffyr** [comment]
As @SamarJi have deleted all his comments, I'm deleting that issue as well.
