### ISSUE TITLE
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/qemu-x86_64": library "libm.so" not found

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#5444]
**Problem description**

I am trying to use qemu on an arm device and have this error: `CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/qemu-x86_64": library "libm.so" not found`

The proot statement is modified in file ~/arch64/startarch+arch64 as follows:
 `proot -q /data/data/com.termux/files/usr/bin/qemu-x86_64 --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch64 -b /data/data/com.termux/files/home/arch64/tmp:/dev/shm -b /data/data/com.termux/files/home/arch64/var/binds/fbindprocstat:/proc/stat -b /proc/self/fd/1:/dev/stdout -b /proc/self/fd/2:/dev/stderr -b "$ANDROID_DATA" -b /dev/ -b "$EXTERNAL_STORAGE" -b "$HOME" -b /proc/ -b /storage/ -b /sys/ -w "$PWD" /usr/bin/env -i HOME=/root TERM=xterm-256color  /bin/bash -l `

**Steps to reproduce**

1) Install Arch Linux x86_64 on arm7 smartphone: 
https://github.com/TermuxArch/TermuxArch

2) Install qemu:
qemu-common/stable,now 1:4.1.1-5 arm [installed]
qemu-user-x86_64/stable,now 1:4.1.1-5 arm [installed]
qemu-utils/stable,now 1:4.1.1-5 arm [installed]

**Expected behavior**

Arch Linux x86_64 works on an Android 9 arm7 smartphone.

**Comment by xeffyr** [comment]
I don't see `/system` bind-mount in your proot command line. Please understand that provided QEMU binary is not statically linked and therefore you should make Termux & Android environments available.

Add `-b /system` and `-b $PREFIX` to proot command line.

Error you got is not a bug.

**Comment by Harshiv-Patel** [comment]
On a different note, I tried building libbz2 for Android-5 branch( discontinued, I know), it gave somewhat similar link time error for it. Missing symbols for libc, stdio and something else.

It seemed like symbols were added at compile time, but absent in .a files.
Perhaps it was due to API level mismatch with the NDK configuration.(no solution yet, NDK r20 in use)

It could be something similar here. Not guaranteed though.

**Comment by xeffyr** [comment]
@Harshiv-Patel What you have has nothing to do error in https://github.com/termux/termux-packages/issues/5444#issue-644818210.

> library "libm.so" not found

**Comment by Harshiv-Patel** [comment]
Yes, I just saw that it's completely unrelated. I'll just delete the unnecessary comments.

**Comment by SDRausty** [comment]
> Error you got is not a bug.

I checked the Internet, wiki.termux.com and the wiki and issues here in hope of finding a resolution.  

> Add -b /system and -b $PREFIX to proot command line.

Thank you @xeffyr for sharing!  After adding this code, Arch Linux x86_64 appears to be working on arm7 as expected.
