### ISSUE TITLE
Error getting for apk binding using termux -apktool 

### ISSUE THREAD

**Issue by vishnuvardhan722** [termux/termux-packages#5447]
Error getting undefined method error  for apk binding  using termux -apktool getting invalid template error and undefined method error nill class in termux please give solution

**Comment by Grimler91** [comment]
apktool is not a termux package so there is nothing we can do from the termux side of things. Try opening an issue in the (termux-)apktool repository. See also https://github.com/termux/termux-packages/issues/5350
