### ISSUE TITLE
usage: command-not-found <command>

### ISSUE THREAD

**Issue by L4ncePreston** [termux/termux-packages#5448]
![Screenshot_2020-06-26-01-21-19-019_com termux](https://user-images.githubusercontent.com/67437111/85780449-d52c3e00-b74e-11ea-971f-c448d2e7c025.jpg)
![Screenshot_2020-06-26-01-40-11-981_com termux](https://user-images.githubusercontent.com/67437111/85780456-d6f60180-b74e-11ea-958e-573867ce7aed.jpg)
Hello everyone!
I have a bit annoying problem. I put the standart banner on termux. Today i downloaded the "ighack". After the downloading my banner name has broken. I desided to delete it and put a new one. After all this actions i can't put any banner. Maybe someone's know the solution.

**Comment by xeffyr** [comment]
> Today i downloaded the "ighack". After the downloading my banner name has broken.

Then ask ighack's author why your banner name is broken.
