### ISSUE TITLE
Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by zababurinsv** [termux/termux-packages#5449]
Good evening.
I have a gulp file that should keep track of changes.
When I run it, I get an error

`Error: ENOSPC: System limit for number of file watchers reached`

On Linux, this problem is solved by one team.

```
$ echo fs.inotify.max_user_watches = 524288 | sudo tee -a /etc/sysctl.conf
and
$ sudo sysctl -p
```

How do I increase the number of `max_user_watches` for a termux ?

**Comment by Grimler91** [comment]
If you are rooted you can run
```
sysctl -n -w fs.inotify.max_user_watches=524288
```

If you are not rooted there's nothing you can do AFAIK

**Comment by yozman** [comment]
is there any update ?

**Comment by RossComputerGuy** [comment]
@yozman What do you mean by that? There's nothing more the Termux developers can do about this issue. The solution already given by @Grimler91 is the best choice but requires a rooted device.

**Comment by xeffyr** [comment]
> is there any update ?

Solution or answer are given: https://github.com/termux/termux-packages/issues/5449#issuecomment-649954926 Issue is closed. No updates anymore.
