### ISSUE TITLE
PHP FFI

### ISSUE THREAD

**Issue by Cvar1984** [termux/termux-packages#5450]
**PHP Foreign Function Interface**

**Link to page**
[Documentation page](https://www.php.net/manual/en/class.ffi.php)

**Additional information**
Have you compiled or tried to compile the package on device? **Yes but that is painfull**

Im developing micro web apps using *PHP*, but there is some *C* libraries i need to bind on *PHP*,  so can i have *FFI* extension enabled on *PHP* at next update? And also `--with-phpdbg-readline`, because current *phpdbg* is not comfortable to use. Thanks

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/206b76f783a881143b3a72caeef6593d387b8829.

```
~ $ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
gd
gmp
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
zip
zlib
```
