### ISSUE TITLE
package request: z3

### ISSUE THREAD

**Issue by programmerjake** [termux/termux-packages#5453]
**Package description**
Z3 is a theorem prover from Microsoft Research.

It is a common dependency of lots of software that needs to do theorem proving

**Link to home page and sources**
1. Home page:
https://github.com/Z3Prover/z3/wiki
2. Source code:
https://github.com/Z3Prover/z3

**Additional information**
Have you compiled or tried to compile the package on device?
yes
* If it did work then please share any patches that you had to apply.
https://github.com/Z3Prover/z3/pull/4545

**Comment by programmerjake** [comment]
see also: #4138

**Comment by yubrajbhoi** [comment]
I am the one who wrote that original issue. Actually last time I gave up too easily. It is possible to compile version `4.8.7`. But the latest `4.8.8` doesn't work. I don't remember what the issue was but it may have something to do with atomics.
