### ISSUE TITLE
Can gnuplot draw pictures?

### ISSUE THREAD

**Issue by sw2wolf** [termux/termux-packages#5454]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by Grimler91** [comment]
gnuplot can do everything described in the gnuplot manual: http://www.gnuplot.info/docs_5.2/Gnuplot_5.2.pdf

**Comment by sw2wolf** [comment]
I mean to draw pictures under termux !

Regards!

**Comment by Grimler91** [comment]
Gnuplot is not like ms paint if that is what you are asking. You can visualize data, see the manual

**Comment by sw2wolf** [comment]
$pkg show gnuplot
Package: gnuplot
Version: 5.2.8
...
$maxima
 (%i1) plot2d(sin(x),[x,-%pi,%pi]);
(%o1)   [/data/data/com.termux/files/usr/tmp/maxout22142.gnuplot_pipes]
(%i2)          line 0: warning: this copy of gnuplot has no mouse support
WARNING: Plotting with an 'unknown' terminal.   No output will be generated. Please select a terminal with 'set terminal'.

I don't know which terminal i should use to see the drawn picture.

Regards!

**Comment by Grimler91** [comment]
```
set term dumb
```
or
```
set term png
set output "test.png"
```
Make the plot and then run, from the shell
```
termux-share test.png
```
To view it in your default android viewer

**Comment by sw2wolf** [comment]
thank you very much!Sent from my Huawei phone-------- Original message --------From: Henrik Grimler <notifications@github.com>Date: Sat, Jun 27, 2020, 2:42 PMTo: termux/termux-packages <termux-packages@noreply.github.com>Cc: sw2wolf <czsq888@163.com>, Author <author@noreply.github.com>Subject: Re: [termux/termux-packages] Can gnuplot draw pictures? (#5454)
set term dumb

or
set term png
set output "test.png"

Make the plot and then run, from the shell
termux-share test.png

To view it in your default android viewer
