### ISSUE TITLE
NetHunter Rootless Edition |||||| wget -O install-nethunter-termux https://offs.ec/2MceZWr

### ISSUE THREAD

**Issue by theknilesh** [termux/termux-packages#5456]
When i give this command in termux window an error ocurs like ,(given in the screen shot)

And then i searched a little bit on the internet about the error and i found that if i copy the " install-nethunter-termux " script into the home directory the it might solve the problem but when i try to scan for the file(install-nethunter-termux){it doesnt have an .sh extension too, so i change it to .sh but even after that} ,it doesnt shows up 
![IMG_20200628_132923](https://user-images.githubusercontent.com/67542664/85945508-dbdbd080-b95b-11ea-965c-379d62a40cb8.jpg)

Script Not showing

[Here is a Screen Recorde video of the problem script not showing.](https://www.mediafire.com/download/s5pci8xs16w09jw) 

Some more screen shots
![Screenshot_2020-06-27-17-07-44-997_com termux](https://user-images.githubusercontent.com/67542664/85945579-79370480-b95c-11ea-8031-52a8ad547477.jpg)
![Screenshot_2020-06-27-16-32-50-777_com mi android globalFileexplorer](https://user-images.githubusercontent.com/67542664/85945582-7cca8b80-b95c-11ea-854f-3f4aabf4e1b3.jpg)

Thankyou guys...
Help me please
I want to install Nethunter in Xiaomi Redminote 8 pro unrooted.

**Comment by xeffyr** [comment]
1. How this is related to **official** Termux packages ? We aren't working/fixing programs of third-parties.
2. We are not responsible for domain offs.ec. It is simply unresolvable:
; <<>> DiG 9.16.1-Ubuntu <<>> @8.8.8.8 offs.ec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 52611
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;offs.ec.			IN	A
```

**Comment by theknilesh** [comment]
HELP

**Comment by theknilesh** [comment]
It was a url shortner issue ... Which is no fixed.
