### ISSUE TITLE
How can I access redis in termux in my computer?

### ISSUE THREAD

**Issue by lirubao** [termux/termux-packages#5458]
As the title, Or open a designated port in termux to make it externally accessible?

**Comment by xeffyr** [comment]
> open a designated port in termux

`redis-server --port 7777`, then access Redis in Termux through your LAN IP of the device where Termux is running.

> make it externally accessible?

If you mean to have access over Internet - this is not recommended. However if you really need that - pick a one of variants listed at https://wiki.termux.com/wiki/Bypassing_NAT.
