### ISSUE TITLE
Package request: locale

### ISSUE THREAD

**Issue by Goodgithuber** [termux/termux-packages#546]
I cant see encoding that is not in unicode, specifically Chinese GB18030.
I am happy that Termux can open emacs or vim or whatever works in Termux but cant really use it bc i cant see the text.

I tried precede the command with LANG=zh_CN.GB18030, but it doesnt work i think it works only if u have locale installed, then use locale-gen to generate support for such encoding.

**Comment by fornwall** [comment]
The system with `locale-gen` only works with support from the system libc - which the Android libc (bionic) does not have. So unfortunately this will not work on Android.

I guess the best solution is to install and use `iconv` to convert other encodings than UTF-8 into UTF-8.
