### ISSUE TITLE
Package Request : zoneminder

### ISSUE THREAD

**Issue by rainbow-app** [termux/termux-packages#5461]
**Package description**
Video camera security and surveillance solution.
In termux, it would be the first (?AFAIK) server that can stream video from a mobile, anywhere (wide-open to the whole hostile internet).

**Link to home page and sources**
1. Home page: http://www.zoneminder.com
2. Source code: https://github.com/ZoneMinder/ZoneMinder/blob/master/README.md

**Additional information**
Have you compiled or tried to compile the package on device?
No

Zoneminder needs Video4Linux driver.

**Comment by xeffyr** [comment]
> Zoneminder needs Video4Linux driver.

Video4Linux in-kernel support is not available on all devices and its client software has build issues. Also check the https://github.com/termux/termux-packages/issues/5019#issuecomment-638785697.

Even though my device *has* V4L support, I won't bother to root it to test whether `zoneminder` will actually work. Leaving this and https://github.com/termux/termux-packages/issues/5019 (v4l-utils) issues for people who will be able to patch it and confirm that it works.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/5019#issuecomment-638785697
