### ISSUE TITLE
tty-solitaire bug patch

### ISSUE THREAD

**Issue by Rengaf05** [termux/termux-packages#5467]
Hey guys,
i was bored so i patched tty-solitaire.
i patched 2 major rendering bugs

![2020_07_02_033814](https://user-images.githubusercontent.com/37475635/86375429-eeb91280-bc85-11ea-8473-4b08b683951c.png)
1) when you move card, few parts bug
2) you cant see suits

after patch:
![Screenshot_2020-07-02-14-51-52](https://user-images.githubusercontent.com/37475635/86375601-393a8f00-bc86-11ea-81d6-f126df1c7dc8.png)

D = diamonds
H = hearts
S = spades
C = clubs

Download, patch and install with commands below:
```
wget -O tty-solitaire-v1.3.0.tar.gz https://github.com/mpereira/tty-solitaire/archive/v1.3.0.tar.gz
wget https://gist.githubusercontent.com/Rengaf05/1f834a9d6a2999931b0712444fcf45c8/raw/1248f9550220bbb5b8cfbf19079592d7c32cde16/tty-solitaire.patch
tar xvf tty-solitaire-v1.3.0.tar.gz
cd tty-solitaire-1.3.0
patch -p1 < ../tty-solitaire.patch
make && make install
```

Run the game with:
```
soli
```

**Comment by Grimler91** [comment]
Nice! Bug nr 2 was discussed a bit in https://github.com/termux/termux-packages/issues/1536, it only seem to happen on some android versions, so could you share your output of `termux-info`?

**Comment by Rengaf05** [comment]
Oh yeah i can share the output of termux-info, but i dont think its relevant. I posted this report just to help other people with the same problem :D
