### ISSUE TITLE
SWI-Prolog version 8.3.x

### ISSUE THREAD

**Issue by erlanger** [termux/termux-packages#5469]
Hi,

   Thank you so much for your work.

   Could you please use the odd minor versions (called development versions, but they are used in production by many) of SWI-Prolog? I am the one that did the port to termux. The current odd versions are numbered 8.3.x  

   The "stable" even-numbered versions (currently 8.2.x) become stale rather quickly and are not updated often except maybe during the 1-2 month window when a new "stable" release is made. Some times they are not updated in a whole year or even more, and this will make SWI-Prolog very weak for Android and not usable by those who use the odd-numbered "development" versions in production.

**Comment by xeffyr** [comment]
Ok, will do it shortly.

**Comment by xeffyr** [comment]
Done.

**Comment by erlanger** [comment]
Thanks! You're faster than a bullet :grin:
