### ISSUE TITLE
Package request: Newsbeuter

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#547]
I would really like to use newsbeuter on Termux. 
There is a pull request available by @bkutil at https://github.com/termux/termux-packages/pull/298, but it doesn't build (anymore?).

**Comment by bkutil** [comment]
It used to build back in June, I still have a working binary on a Nexus 7.

I'll try to find a few hours this weekend (12/13 Nov) to bring the PR back to a buildable state.

Some feedback - ideally, a checklist of requirements for it to be merged, or a 'not interested/won't be accepted' - on #298 would be great.

**Comment by fornwall** [comment]
@bkutil Sorry for dropping the ball with that PR!

Newsbeuter seems like a nice little package to have, so as soon that we get it building again I'll merge it (ping me).

You can also change the pull request to add the packages into the `disabled-packages/` folder (which are not built by default, can can contain packages that don't build) - I can then merge it and have a look myself what needs to be done.

**Comment by its-pointless** [comment]
issue is ncurses updated and so calling ndk's pkg-config --cflags ncursesw gives 
-D_XOPEN_SOURCE=500 -I/data/data/com.termux/files/usr/include
the xopen part screws cmath.
easiest way is to remove ncurses check from config.sh and add -lncurses to makefile
