### ISSUE TITLE
library "libz.so.1" not found

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-packages#5475]
i reinstall termux today, it has some odd thing when run apt-key add some error comes up.
i need updated  sources.list  follow the guide  on https://github.com/its-pointless/gcc_termux  to install r-base. i hate why i reinstall termux.

Could someone help to fix the issue library "libz.so.1" not found? Thanks your help.

$apt-key add pointless.gpg
CANNOT LINK EXECUTABLE "gpg": library "libz.so.1" not found

the version show below:
termux version 0.94 
android 10

**Comment by Harshiv-Patel** [comment]
Try
`ls $PREFIX/lib | grep libz.so`

If there exists a library like libz.so.1.2.11 or some similar version number,(it'll show in the output) simply link it

`ln -s $PREFIX/lib/libz.so.x.y.zz $PREFIX/lib/libz.so.1`

Mind the `x.y.zz` replace this xyzz with whatever version number you find on your setup

**Comment by xeffyr** [comment]
Closing as issue is unreproducible.

https://github.com/termux/termux-packages/issues/5476#issuecomment-656096673
