### ISSUE TITLE
Apache Unable to load PHP OPCache extension

### ISSUE THREAD

**Issue by user655362020** [termux/termux-packages#5482]
**Problem description**

Apache unable to load PHP OPCache extension. Verified using phpinfo(). When running phpinfo() in terminal I get ```Opcode Caching => Up and Running```

Relevant apache error_log
```PHP Warning:  Failed loading Zend extension 'opcache.so' (tried: /data/data/com.termux/files/usr/lib/php/opcache.so (dlopen failed: cannot locate symbol "PHP_MD5Update" referenced by "/data/data/com.termux/files/usr/lib/php/opcache.so"...), /data/data/com.termux/files/usr/lib/php/opcache.so.so (dlopen failed: library "/data/data/com.termux/files/usr/lib/php/opcache.so.so" not found)) in Unknown on line 0```
**Steps to reproduce**

Load php module in apache
Enable OPCache in php by editing php.ini and adding line ```zend_extension = opcache.so```

**Additional information**

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
7.1.1
Kernel build information:
Linux localhost 3.10.49-12378949 #1 SMP PREEMPT Mon Feb 19 17:29:10 KST 2018 armv7l Android
Device manufacturer:
samsung
Device model:
SM-T355Y
```

**Comment by Cvar1984** [comment]
> **Problem description**
> 
> Apache unable to load PHP OPCache extension. Verified using phpinfo(). When running phpinfo() in terminal I get `Opcode Caching => Up and Running`
> 
> Relevant apache error_log
> `PHP Warning: Failed loading Zend extension 'opcache.so' (tried: /data/data/com.termux/files/usr/lib/php/opcache.so (dlopen failed: cannot locate symbol "PHP_MD5Update" referenced by "/data/data/com.termux/files/usr/lib/php/opcache.so"...), /data/data/com.termux/files/usr/lib/php/opcache.so.so (dlopen failed: library "/data/data/com.termux/files/usr/lib/php/opcache.so.so" not found)) in Unknown on line 0`
> **Steps to reproduce**
> 
> Load php module in apache
> Enable OPCache in php by editing php.ini and adding line `zend_extension = opcache.so`
> 
> **Additional information**
> 
> ```
> Packages CPU architecture:
> arm
> Subscribed repositories:
> # sources.list
> deb https://termux.org/packages/ stable main
> # science-repo (sources.list.d/science.list)
> deb https://dl.bintray.com/grimler/science-packages-24 science stable
> # game-repo (sources.list.d/game.list)
> deb https://dl.bintray.com/grimler/game-packages-24 games stable
> Updatable packages:
> All packages up to date
> Android version:
> 7.1.1
> Kernel build information:
> Linux localhost 3.10.49-12378949 #1 SMP PREEMPT Mon Feb 19 17:29:10 KST 2018 armv7l Android
> Device manufacturer:
> samsung
> Device model:
> SM-T355Y
> ```

Are you sure have installed opcache.so?
`ls $(php-config --extension-dir)`

**Comment by user655362020** [comment]
> > **Problem description**
> > Apache unable to load PHP OPCache extension. Verified using phpinfo(). When running phpinfo() in terminal I get `Opcode Caching => Up and Running`
> > Relevant apache error_log
> > `PHP Warning: Failed loading Zend extension 'opcache.so' (tried: /data/data/com.termux/files/usr/lib/php/opcache.so (dlopen failed: cannot locate symbol "PHP_MD5Update" referenced by "/data/data/com.termux/files/usr/lib/php/opcache.so"...), /data/data/com.termux/files/usr/lib/php/opcache.so.so (dlopen failed: library "/data/data/com.termux/files/usr/lib/php/opcache.so.so" not found)) in Unknown on line 0`
> > **Steps to reproduce**
> > Load php module in apache
> > Enable OPCache in php by editing php.ini and adding line `zend_extension = opcache.so`
> > **Additional information**
> > ```
> > Packages CPU architecture:
> > arm
> > Subscribed repositories:
> > # sources.list
> > deb https://termux.org/packages/ stable main
> > # science-repo (sources.list.d/science.list)
> > deb https://dl.bintray.com/grimler/science-packages-24 science stable
> > # game-repo (sources.list.d/game.list)
> > deb https://dl.bintray.com/grimler/game-packages-24 games stable
> > Updatable packages:
> > All packages up to date
> > Android version:
> > 7.1.1
> > Kernel build information:
> > Linux localhost 3.10.49-12378949 #1 SMP PREEMPT Mon Feb 19 17:29:10 KST 2018 armv7l Android
> > Device manufacturer:
> > samsung
> > Device model:
> > SM-T355Y
> > ```
> 
> Are you sure have installed opcache.so?
> `ls $(php-config --extension-dir)`
```opcache.so```

**Comment by Grimler91** [comment]
> dlopen failed: library "/data/data/com.termux/files/usr/lib/php/opcache.so.so" not found

It seems to be looking for opache.so.so now, maybe your php.ini should contain 
```
zend_extension = opcache
```
instead of 
```
zend_extension = opcache.so
```
?

**Comment by Cvar1984** [comment]
> > dlopen failed: library "/data/data/com.termux/files/usr/lib/php/opcache.so.so" not found
> 
> It seems to be looking for opache.so.so now, maybe your php.ini should contain
> 
> ```
> zend_extension = opcache
> ```
> 
> instead of
> 
> ```
> zend_extension = opcache.so
> ```
> 
> ?

Php finding libs with ".so" and without ".so", i think that is optional.
The problem goes here
```
PHP Warning: Failed loading Zend extension 'opcache.so' (tried: /data/data/com.termux/files/usr/lib/php/opcache.so (dlopen failed: cannot locate symbol "PHP_MD5Update" referenced by "/data/data/com.termux/files/usr/lib/php/opcache.so"...),
```

**Comment by Grimler91** [comment]
@Cvar1984 you are right, thanks.

So this is essentially the same issue as #2479 so I'll close this in favour of that one so that we are tracking this in a single issue. One workaround is to `export LD_PRELOAD=$PREFIX/libexec/apache2/opache.so` before starting httpd.

I am using a [termux-services](https://wiki.termux.com/wiki/Termux-services) script for httpd containing
```
#!/data/data/com.termux/files/usr/bin/sh
export LD_PRELOAD=$PREFIX/libexec/apache2/mod_proxy.so
exec httpd -f $HOME/apache2/httpd.conf -DNO_DETACH 2>&1
```
to workaround a similar issue.
