### ISSUE TITLE
[Package request] clang-tools-extra

### ISSUE THREAD

**Issue by kb-1000** [termux/termux-packages#5483]
**Package description** clang-tools-extra contains extra clang tools, such as clangd, which is useful to get C++ completion in Neovim.

**Link to home page and sources**
1. Home page:
2. Source code: https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang-tools-extra-10.0.0.src.tar.xz

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

I didn't try it, however I don't see a reason why it wouldn't run, so I hope it does run. Please note that it requires to be compiled as part of Clang, so just add it as a libllvm subpackage.

**Comment by buttaface** [comment]
Added in #5495, upgrade to clang 10 and confirm.

**Comment by xeffyr** [comment]
Included in `clang` package.

**Comment by kb-1000** [comment]
It's working. Thanks!
