### ISSUE TITLE
How to access install hooks within package build scripts?

### ISSUE THREAD

**Issue by Yuriusu** [termux/termux-packages#5484]
The wiki only provide [build step hooks](https://github.com/termux/termux-packages/wiki/Creating-new-package#table-of-available-build-step-overrides) when writing build scripts. Are there any chance for install/uninstall hooks to be accessed? If so, that would we useful for running additional scripts upon installation, like setting up user-defined configurations, etc..

**Comment by xeffyr** [comment]
You are looking for termux_step_create_debscripts. Create this function and write scripts from it.

Valid script names are: preinst, postinst, prerm, postrm, .i.e. like in Debian.

Btw, termux-packages has LOTS of examples on this...

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/blob/master/packages/nano/build.sh#L33

**Comment by Yuriusu** [comment]
Cool. I hope this gets  included (at least a mention :laughing:) in the wiki though.
