### ISSUE TITLE
Android 10 removed write access on external SD card.

### ISSUE THREAD

**Issue by petkar** [termux/termux-packages#5486]
**Problem description**

Before the Android 10 update, I was able to download youtube-dl and spotdl content straight into the root of my SD Card (had rw access). I recall reading somewhere that full rw access to external storage was never supported (But I did have access on Android 9). I realized that this affected all apps (all apps lost rw access but retained read access), including file managers. But on the file manager, I was able to regain the lost permission through the Storage Access Framework (SAF). Would there be any way to invoke the SAF from Termux to gain full access to the external storage again? (The same way as the file managers did)

```

```

**Comment by xeffyr** [comment]
This is known issue which I mentioned at https://github.com/termux/termux-packages/wiki/Termux-and-Android-10#additional-android-10-issues.
> Would there be any way to invoke the SAF from Termux to gain full access to the external storage again? (The same way as the file managers did)

Generally, it is possible to regain the access, but partially. You will need to use a special utility to read or write a file through SAF. But you will not have access to storage in shell and here is why:
* Storage Access Framework is implemented purely through the virtual paths (URIs) generated and managed by Android API.
* Command line utilities are not using any of Android APIs. They are handled by Linux kernel which don't know anything about SAF.

Technically it is possible to access SAF with JNI but that will make utilities much slower and you will have to select storage directory on each command execution.  Patching to use JNI will also require huge amount of work which we are not able to handle.

Termux still can use `/storage/emulated/0/Android/data/com.termux` without needing the storage permission or SAF.
