### ISSUE TITLE
libffi upgrade broken by libgcrypt

### ISSUE THREAD

**Issue by stuart-little** [termux/termux-packages#5487]
**Problem description**

Trying to upgrade `libffi` fails and produces the error

```
Preparing to unpack .../libffi_3.3-1_aarch64.deb ...
Unpacking libffi (3.3-1) over (3.3) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/libffi_3.3-1_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/share/info/dir', which is also in package libgcrypt 1.8.5-2
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/libffi_3.3-1_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

**Steps to reproduce**

Assuming you have `libffi` installed, run `apt upgrade`.

**Expected behavior**

Normal error-free upgrade.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/science.list.bak
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# sources.list.d/game.list.bak
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
libffi/stable 3.3-1 aarch64 [upgradable from: 3.3]
Android version:
10
Kernel build information:
Linux localhost 4.9.179-perf+ #1 SMP PREEMPT Tue May 5 21:31:00 CST 2020 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6013

```

**Comment by buttaface** [comment]
Yeah, I just hit this too.

**Comment by landfillbaby** [comment]
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/libgcrypt_1.8.5-2_aarch64.deb (--unpack):
     trying to overwrite '/data/data/com.termux/files/usr/share/info/dir', which is also in package flex 2.6.4-2

**Comment by xeffyr** [comment]
> also everything is being bumped right now and there was no corresponding commit in the repo. what is happening?

Read this: https://github.com/termux/termux-packages/pull/5478#issue-444444361. Lots of packages are going to be rebuilt and is currently being done from non-master branch.

**Comment by xeffyr** [comment]
I guess all packages containing `info` documentation will conflict with each other currently. I can fix that for common/known packages, but I do not have full list of those installing the `usr/share/info/dir`.

**Comment by landfillbaby** [comment]
$ dpkg -S $PREFIX/share/info
    bash, gnupg, texinfo, libksba, readline, fftw, libffi, bison, libgmp, libgpg-error, coreutils, libnettle, libmpfr, libtool, gzip, gawk, libgnutls, libassuan, inetutils, automake, make, grep, libidn2, libunistring, gdbm, flex, m4, diffutils, findutils, gdb, libgcrypt, ed, tar, sed, binutils: /data/data/com.termux/files/usr/share/info
does this help?

**Comment by Grimler91** [comment]
Updates seem to be available now, I was at least able to upgrade my all packages on my two main devices without additional problems. 

Thanks for reporting @stuart-little and thanks for the list @landfillbaby
