### ISSUE TITLE
Package request: rmtrash and trash-cli

### ISSUE THREAD

**Issue by mirsella** [termux/termux-packages#5488]
rmtrash is a shell script which serves the purpose of moving files to trash instead of deleting. 
rmtrash work like rm, you can also use -rf. to restore file.
trash-cli is a dependencies of rmtrash, which give trash-list (list the trashed file and folders) and trash-restore (restore a certain file or directory) mainly.

https://github.com/PhrozenByte/rmtrash
https://github.com/andreafrancia/trash-cli

**Additional information**
trash-cli is in python repository, but it's simpler to have it in the repo, and for new people who don't know it's in python repo (it's not clearly cited on their github).
rmtrash is a simple shell script so no compilation or anything, just have wget it from the repo, chmod +x, and mv to /bin.
I currently use those on termux and on my main PC x86_64 I even have it aliased : rm='rmtrash'.

sorry for my English. thanks for your work

**Comment by xeffyr** [comment]
`pip install trash-cli` - to install the trash-cli
rmtrash is enough to just copy into `$PREFIX/bin`

We do not make packages of simple scripts or software which can be installed through language-specific package managers like `pip` or `gem`.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests
