### ISSUE TITLE
Update radare2 to 1.0

### ISSUE THREAD

**Issue by radare** [termux/termux-packages#549]
https://github.com/radare/radare2/releases/tag/1.0

**Comment by fornwall** [comment]
I tried building version 1.0.1, and I'm getting this error:

    src/binr/rasm2/rasm2.c:483: undefined reference to `r_asm_syntax_from_string'

Any hint what could be wrong?

**Comment by radare** [comment]
it's already defined in libr/asm/asm.c :? i'll release 1.0.2 because debian complained about another thing... do you know how can i reproduce this without the termux build system?

**Comment by radare** [comment]
r2 builds fine with sys/android.sh, so this shouldnt be a staticlinking issue. my guess is that is trying to link against the old r_asm

**Comment by fornwall** [comment]
I'll look into it more. The build doesn't use any script in sys/ currently, just `make` and `make install`.

**Comment by radare** [comment]
yeah that’s fine, i use the sys/* things for automating, but distros should just follow the ./configure ; make ; make install steps

if the build env is clean it should build. at least it does in our farm

**Comment by radare** [comment]
I have run the ndk script and then the docker image, but im having this error:

```
# ./build-package.sh packages/radare2/
Wrong NDK version - we need 13
```

**Comment by Neo-Oli** [comment]
@radare If you're using docker you don't need to run the ndk script. 
Have used the docker environment before? A few weeks ago the ndk version was updated. Try ruinning the ./scripts/update-docker.sh script.

**Comment by vishalbiswas** [comment]
It builds if you clean-rebuild it. After running `clean.sh` that undefined reference was solved.

**Comment by radare** [comment]
then it’s not a problem in my side, right? it’s ok to release 1.0.2 without any more change? (i have some fixes from other distros)

thanks!

**Comment by fornwall** [comment]
@radare Sure, go ahead with the 1.0.2 release - if we find any issue we can live with a patch until the next release!

**Comment by fornwall** [comment]
@vishalbiswas Thanks! Running `clean.sh` fixes the build. I guess building radare2 1.0 to install on a system where a previous version of radare2 was installed caused the issue (at least with the Termux build system).

**Comment by radare** [comment]
Done! https://github.com/radare/radare2/releases/tag/1.0.2

thanks!

**Comment by fornwall** [comment]
Done - version 1.0.2 of radare2 is now available in the apt repo:

    apt update && apt upgrade

Thanks for the heads up @radare!
