### ISSUE TITLE
libffi_3.3-1_aarch64.deb installation failed

### ISSUE THREAD

**Issue by remo7777** [termux/termux-packages#5490]
**Problem description**

after update upgrade i installed vim-python it shows libffi install problem. 
![Screenshot_2020-07-07-22-41-11-01_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/28594846/86818557-279d2100-c0a4-11ea-903c-f58a129cd52e.jpg)

**Additional information**

```
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf+ #2 SMP PREEMPT Tue Jun 9 21:01:44 CST 2020 aarch64 Android
Device manufacturer:
realme
Device model:
RMX1921
$
```

**Comment by landfillbaby** [comment]
do `pkg up` first, it should be fixed now

**Comment by remo7777** [comment]
> do `pkg up` first, it should be fixed now

ok i ll try.

**Comment by remo7777** [comment]
ah libgcrypt

**Comment by remo7777** [comment]
thank you brother

**Comment by JokerDonllie-420** [comment]
![Screenshot_2020-08-17-13-44-28-828_com termux](https://user-images.githubusercontent.com/67456616/90370807-8075b700-e05d-11ea-994a-d0476d497319.jpg)
Please help why this problem
