### ISSUE TITLE
Package Request:dgsh(Directed Graph Shell)

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#5492]
**Package description**

dgsh is an advanced shell for programming higly complex pipe constructs for data flow in shell scripting. And hence it is the most essential tool for programmers, scripters, and system administrators. Having it on termux is highly needed.

**Link to home page and sources**
1. Home page:https://www.spinellis.gr/sw/dgsh/
2. Source code:https://github.com/dspinellis/dgsh

**Additional information**
Have you compiled or tried to compile the package on device?
Developer have not made or compiled this shell for arm and aarch64 architecture.
Added some of commits with official developer. But some errors cant be resolved. Help needed.
https://github.com/dspinellis/dgsh/issues/113

However, source files needed to be patched for arm/aarch64 so that it can be used on termux.

Having dgsh in termux is the most prominent requirement right now and it will prove to be highly beneficial for complex shell scripting purposes.

* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by tathastu871** [comment]
Please do something for this package.

**Comment by tathastu871** [comment]
Added some of commits with official developer. But some errors cant be resolved. Help needed.

https://github.com/dspinellis/dgsh/issues/113

**Comment by tathastu871** [comment]
Has any of termux developers tried compiling it.

**Comment by tathastu871** [comment]
Added some of commits with official developer. But some errors cant be resolved. Help needed.

https://github.com/dspinellis/dgsh/issues/113

**Comment by Grimler91** [comment]
> Added some of commits with official developer. But some errors cant be resolved. Help needed.
> 
> [dspinellis/dgsh#113](https://github.com/dspinellis/dgsh/issues/113)

Open a PR with the build.sh so that we can see what you are doing and what error you run into

**Comment by tathastu871** [comment]
```
./lib/stdio-impl.h:66:22: error: field has incomplete type 'struct __sbuf'
lib/freading.c:40:14: error: incomplete definition of type 'struct __sFILE'
lib/freading.c:40:25: error: use of undeclared identifier '__SRD'
3 errors generated.
```

Help solve this error: 
Below may help
https://lists.gnu.org/archive/html/bug-gnulib/2018-05/msg00103.html

**Comment by xtkoba** [comment]
Did you have https://github.com/termux/termux-packages/blob/master/ndk-patches/bits-struct_file.h.patch applied?

**Comment by tathastu871** [comment]
> Did you have https://github.com/termux/termux-packages/blob/master/ndk-patches/bits-struct_file.h.patch applied?
there is no such header in my termux installation

**Comment by Grimler91** [comment]
The same patch as for gcal probably works: https://github.com/termux/termux-packages/blob/bf51d022eff247887d44f3ef2b9a5b801ccb3d1b/packages/gcal/gnulib.patch

**Comment by tathastu871** [comment]
But bits-struct_file.h is not in my termux include/bits folder. How to add it

**Comment by Grimler91** [comment]
> But bits-struct_file.h is not in my termux include/bits folder. How to add it? 

```
$ apt-file search struct_file.h
ndk-sysroot: /data/data/com.termux/files/usr/include/bits/struct_file.h
```

So install ndk-sysroot

**Comment by tathastu871** [comment]
```
make -C core-tools CFLAGS=""
make[1]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools'
make  all-recursive
make[2]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools'
Making all in src
make[3]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools/src'
Making all in .
make[3]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools'
make[3]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools'
Making all in tests
make[3]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools/tests'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools/tests'
make[2]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools'
make[1]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools'
cd core-tools/src && make build-install
make[1]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools/src'
mkdir -p ../../build/bin ../../build/libexec/dgsh
cp dgsh-monitor dgsh-httpval dgsh-readval dgsh-merge-sum ../../build/bin/
cp dgsh-tee dgsh-writeval dgsh-readval dgsh-monitor dgsh-conc dgsh-wrap dgsh-enumerate dgsh-pecho dgsh-fft-input dgsh-w dgsh-parallel perm ../../build/libexec/dgsh/
make[1]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/core-tools/src'
make -C unix-tools make MAKEFLAGS=
make[1]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools'
make -C bash CFLAGS=""
make[2]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools/bash'

	  ***********************************************************
	  *                                                         *
	  * GNU bash, version 4.3.46(1)-release (aarch64-unknown-linux-gnu)
	  *                                                         *
	  ***********************************************************

make[2]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools/bash'
make -C coreutils
make[2]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools/coreutils'
make  all-recursive
make[3]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools/coreutils'
Making all in po
make[4]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools/coreutils/po'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools/coreutils/po'
Making all in .
make[4]: Entering directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools/coreutils'
  CC       lib/freading.o
  CC       lib/freadseek.o
  CC       lib/freopen-safer.o
  CC       lib/ftoastr.o
  CC       lib/full-read.o
  CC       lib/full-write.o
  CC       lib/gethrxtime.o
  CC       lib/xtime.o
  CC       lib/getndelim2.o
lib/getndelim2.c:164:15: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
          if (GETNDELIM2_MAXIMUM < newsize - offset)
              ^~~~~~~~~~~~~~~~~~
lib/getndelim2.c:64:29: note: expanded from macro 'GETNDELIM2_MAXIMUM'
#define GETNDELIM2_MAXIMUM (PTRDIFF_MAX < SSIZE_MAX ? PTRDIFF_MAX : SSIZE_MAX)
                            ^~~~~~~~~~~
./lib/stdint.h:520:5: note: expanded from macro 'PTRDIFF_MAX'
    _STDINT_MAX (1, 64, 0l)
    ^~~~~~~~~~~~~~~~~~~~~~~
./lib/stdint.h:126:8: note: expanded from macro '_STDINT_MAX'
   ? ~ _STDINT_MIN (signed, bits, zero) \
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./lib/stdint.h:122:31: note: expanded from macro '_STDINT_MIN'
  ((signed) ? (- ((zero) + 1) << ((bits) ? (bits) - 1 : 0)) : (zero))
               ~~~~~~~~~~~~~~ ^
lib/getndelim2.c:166:44: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
              size_t newsizemax = offset + GETNDELIM2_MAXIMUM + 1;
                                           ^~~~~~~~~~~~~~~~~~
lib/getndelim2.c:64:29: note: expanded from macro 'GETNDELIM2_MAXIMUM'
#define GETNDELIM2_MAXIMUM (PTRDIFF_MAX < SSIZE_MAX ? PTRDIFF_MAX : SSIZE_MAX)
                            ^~~~~~~~~~~
./lib/stdint.h:520:5: note: expanded from macro 'PTRDIFF_MAX'
    _STDINT_MAX (1, 64, 0l)
    ^~~~~~~~~~~~~~~~~~~~~~~
./lib/stdint.h:126:8: note: expanded from macro '_STDINT_MAX'
   ? ~ _STDINT_MIN (signed, bits, zero) \
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./lib/stdint.h:122:31: note: expanded from macro '_STDINT_MIN'
  ((signed) ? (- ((zero) + 1) << ((bits) ? (bits) - 1 : 0)) : (zero))
               ~~~~~~~~~~~~~~ ^
2 warnings generated.
  CC       lib/gettime.o
  CC       lib/getugroups.o
  CC       lib/hard-locale.o
  CC       lib/hash.o
lib/hash.c:549:11: warning: implicit conversion from 'unsigned long' to 'float' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-const-int-float-conversion]
      if (SIZE_MAX <= new_candidate)
          ^~~~~~~~ ~~
./lib/stdint.h:543:20: note: expanded from macro 'SIZE_MAX'
# define SIZE_MAX  _STDINT_MAX (0, 64, 0ul)
                   ^~~~~~~~~~~~~~~~~~~~~~~~
./lib/stdint.h:130:71: note: expanded from macro '_STDINT_MAX'
     ((((zero) + 1) << ((bits) ? (bits) - 1 - (signed) : 0)) - 1) * 2 + 1)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
lib/hash.c:1079:15: warning: implicit conversion from 'unsigned long' to 'float' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-const-int-float-conversion]
          if (SIZE_MAX <= candidate)
              ^~~~~~~~ ~~
./lib/stdint.h:543:20: note: expanded from macro 'SIZE_MAX'
# define SIZE_MAX  _STDINT_MAX (0, 64, 0ul)
                   ^~~~~~~~~~~~~~~~~~~~~~~~
./lib/stdint.h:130:71: note: expanded from macro '_STDINT_MAX'
     ((((zero) + 1) << ((bits) ? (bits) - 1 - (signed) : 0)) - 1) * 2 + 1)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
2 warnings generated.
  CC       lib/hash-pjw.o
  CC       lib/hash-triple.o
  CC       lib/heap.o
  CC       lib/human.o
  CC       lib/i-ring.o
  CC       lib/idcache.o
  CC       lib/ino-map.o
  CC       lib/imaxtostr.o
  CC       lib/inttostr.o
  CC       lib/offtostr.o
  CC       lib/uinttostr.o
  CC       lib/umaxtostr.o
  CC       lib/ldtoastr.o
  CC       lib/linebuffer.o
  CC       lib/localcharset.o
  CC       lib/glthread/lock.o
In file included from lib/glthread/lock.c:23:
./lib/glthread/lock.h:147:17: warning: weak identifier 'pthread_cancel' never declared
#   pragma weak pthread_cancel
                ^
1 warning generated.
  CC       lib/long-options.o
  CC       lib/malloca.o
  CC       lib/math.o
  CC       lib/mbchar.o
  CC       lib/mbiter.o
  CC       lib/mbsalign.o
  CC       lib/mbscasecmp.o
  CC       lib/mbslen.o
  CC       lib/mbsstr.o
  CC       lib/mbswidth.o
  CC       lib/mbuiter.o
  CC       lib/memcasecmp.o
  CC       lib/memchr2.o
  CC       lib/memcmp2.o
  CC       lib/memcoll.o
  CC       lib/mgetgroups.o
  CC       lib/mkancesdirs.o
  CC       lib/dirchownmod.o
  CC       lib/mkdir-p.o
  CC       lib/modechange.o
  CC       lib/mpsort.o
  CC       lib/nproc.o
  CC       lib/openat-die.o
  CC       lib/openat-safer.o
  CC       lib/parse-datetime.o
./lib/parse-datetime.y:876:17: warning: absolute value function 'abs' given an argument of type 'long' but has parameter of type 'int' which may cause truncation of value [-Wabsolute-value]
  if (24 * 60 < abs (n_minutes))
                ^
./lib/parse-datetime.y:876:17: note: use function 'labs' instead
  if (24 * 60 < abs (n_minutes))
                ^~~
                labs
1 warning generated.
  CC       lib/physmem.o
  CC       lib/posixtm.o
  CC       lib/posixver.o
  CC       lib/printf-frexp.o
  CC       lib/printf-frexpl.o
  CC       lib/priv-set.o
  CC       lib/progname.o
  CC       lib/propername.o
  CC       lib/qcopy-acl.o
  CC       lib/qset-acl.o
  CC       lib/quotearg.o
  CC       lib/randint.o
  CC       lib/randperm.o
  CC       lib/randread.o
  CC       lib/rand-isaac.o
  CC       lib/read-file.o
  CC       lib/readtokens.o
  CC       lib/readtokens0.o
  CC       lib/root-dev-ino.o
  CC       lib/safe-read.o
  CC       lib/safe-write.o
  CC       lib/same.o
  CC       lib/save-cwd.o
  CC       lib/savedir.o
  CC       lib/savewd.o
  CC       lib/se-context.o
  CC       lib/se-selinux.o
  CC       lib/settime.o
  CC       lib/sig-handler.o
  CC       lib/sockets.o
  CC       lib/stat-time.o
  CC       lib/statat.o
  CC       lib/mkstemp-safer.o
  CC       lib/strftime.o
  CC       lib/striconv.o
  CC       lib/strnlen1.o
  CC       lib/strintcmp.o
  CC       lib/strnumcmp.o
  CC       lib/sys_socket.o
  CC       lib/tempname.o
  CC       lib/glthread/threadlib.o
  CC       lib/timespec.o
  CC       lib/glthread/tls.o
In file included from lib/glthread/tls.c:21:
./lib/glthread/tls.h:79:17: warning: weak identifier 'pthread_cancel' never declared
#   pragma weak pthread_cancel
                ^
1 warning generated.
  CC       lib/trim.o
  CC       lib/u64.o
  CC       lib/unicodeio.o
  CC       lib/unistd.o
  CC       lib/dup-safer.o
  CC       lib/fd-safer.o
  CC       lib/pipe-safer.o
  CC       lib/unistr/u8-mbtoucr.o
  CC       lib/unistr/u8-uctomb.o
  CC       lib/unistr/u8-uctomb-aux.o
  CC       lib/uniwidth/width.o
  CC       lib/userspec.o
  CC       lib/utimecmp.o
lib/utimecmp.c:292:36: warning: bitwise negation of a boolean expression; did you mean logical negation? [-Wbool-operation]
                time_t s = src_s & ~ (res == 2 * BILLION);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   !
lib/utimecmp.c:371:16: warning: bitwise negation of a boolean expression; did you mean logical negation? [-Wbool-operation]
      src_s &= ~ (res == 2 * BILLION);
               ^~~~~~~~~~~~~~~~~~~~~~
               !
2 warnings generated.
  CC       lib/utimens.o
  CC       lib/verror.o
  CC       lib/version-etc.o
  CC       lib/version-etc-fsf.o
  CC       lib/wctype-h.o
  CC       lib/write-any-file.o
  CC       lib/xmalloc.o
  CC       lib/xalloc-die.o
  CC       lib/xdectoimax.o
  CC       lib/xdectoumax.o
  CC       lib/xfreopen.o
  CC       lib/xfts.o
  CC       lib/xgetcwd.o
  CC       lib/xgetgroups.o
  CC       lib/xgethostname.o
  CC       lib/xmemcoll.o
  CC       lib/xnanosleep.o
  CC       lib/xprintf.o
  CC       lib/xreadlink.o
  CC       lib/xsize.o
  CC       lib/xstriconv.o
  CC       lib/xstrndup.o
  CC       lib/xstrtod.o
  CC       lib/xstrtoimax.o
  CC       lib/xstrtol.o
  CC       lib/xstrtoul.o
  CC       lib/xstrtol-error.o
  CC       lib/xstrtold.o
  CC       lib/xstrtoumax.o
  CC       lib/xvasprintf.o
  CC       lib/xasprintf.o
  CC       lib/yesno.o
  CC       lib/asnprintf.o
  CC       lib/asprintf.o
  CC       lib/at-func2.o
  CC       lib/calloc.o
  CC       lib/chdir-long.o
  CC       lib/euidaccess.o
  CC       lib/fclose.o
  CC       lib/fcntl.o
  CC       lib/fflush.o
  CC       lib/fnmatch.o
  CC       lib/freadahead.o
  CC       lib/freadptr.o
  CC       lib/frexp.o
  CC       lib/frexpl.o
  CC       lib/fseek.o
  CC       lib/fseeko.o
  CC       lib/fseterr.o
  CC       lib/fsusage.o
  CC       lib/fts.o
  CC       lib/futimens.o
  CC       lib/getcwd.o
  CC       lib/getcwd-lgpl.o
  CC       lib/getdtablesize.o
  CC       lib/getloadavg.o
  CC       lib/getpass.o
  CC       lib/getusershell.o
  CC       lib/group-member.o
  CC       lib/isapipe.o
  CC       lib/isnanf.o
  CC       lib/isnanl.o
  CC       lib/linkat.o
  CC       lib/mbrlen.o
  CC       lib/mbrtowc.o
  CC       lib/mktime.o
  CC       lib/mountlist.o
lib/mountlist.c:534:26: warning: implicit declaration of function 'makedev' is invalid in C99 [-Wimplicit-function-declaration]
            me->me_dev = makedev (devmaj, devmin);
                         ^
1 warning generated.
  CC       lib/nanosleep.o
  CC       lib/nl_langinfo.o
lib/nl_langinfo.c:151:1: error: redefinition of 'nl_langinfo'
nl_langinfo (nl_item item)
^
/data/data/com.termux/files/usr/include/langinfo.h:177:14: note: previous definition is here
static char *nl_langinfo(nl_item item)
             ^
lib/nl_langinfo.c:175:10: error: use of undeclared identifier 'GROUPING'
    case GROUPING:
         ^
lib/nl_langinfo.c:283:10: error: use of undeclared identifier 'INT_CURR_SYMBOL'
    case INT_CURR_SYMBOL:
         ^
lib/nl_langinfo.c:285:10: error: use of undeclared identifier 'MON_DECIMAL_POINT'
    case MON_DECIMAL_POINT:
         ^
lib/nl_langinfo.c:287:10: error: use of undeclared identifier 'MON_THOUSANDS_SEP'
    case MON_THOUSANDS_SEP:
         ^
lib/nl_langinfo.c:289:10: error: use of undeclared identifier 'MON_GROUPING'
    case MON_GROUPING:
         ^
lib/nl_langinfo.c:291:10: error: use of undeclared identifier 'POSITIVE_SIGN'
    case POSITIVE_SIGN:
         ^
lib/nl_langinfo.c:293:10: error: use of undeclared identifier 'NEGATIVE_SIGN'
    case NEGATIVE_SIGN:
         ^
lib/nl_langinfo.c:295:10: error: use of undeclared identifier 'FRAC_DIGITS'
    case FRAC_DIGITS:
         ^
lib/nl_langinfo.c:297:10: error: use of undeclared identifier 'INT_FRAC_DIGITS'
    case INT_FRAC_DIGITS:
         ^
lib/nl_langinfo.c:299:10: error: use of undeclared identifier 'P_CS_PRECEDES'
    case P_CS_PRECEDES:
         ^
lib/nl_langinfo.c:301:10: error: use of undeclared identifier 'N_CS_PRECEDES'
    case N_CS_PRECEDES:
         ^
lib/nl_langinfo.c:303:10: error: use of undeclared identifier 'P_SEP_BY_SPACE'
    case P_SEP_BY_SPACE:
         ^
lib/nl_langinfo.c:305:10: error: use of undeclared identifier 'N_SEP_BY_SPACE'
    case N_SEP_BY_SPACE:
         ^
lib/nl_langinfo.c:307:10: error: use of undeclared identifier 'P_SIGN_POSN'
    case P_SIGN_POSN:
         ^
lib/nl_langinfo.c:309:10: error: use of undeclared identifier 'N_SIGN_POSN'
    case N_SIGN_POSN:
         ^
16 errors generated.
make[4]: *** [Makefile:9354: lib/nl_langinfo.o] Error 1
make[4]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools/coreutils'
make[3]: *** [Makefile:11767: all-recursive] Error 1
make[3]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools/coreutils'
make[2]: *** [Makefile:6306: all] Error 2
make[2]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools/coreutils'
make[1]: *** [Makefile:90: make] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/dgsh_gm/dgsh/unix-tools'
make: *** [Makefile:81: unix-tools] Error 2
```

nl_langinfo related error

**Comment by tathastu871** [comment]
sed 's/#include <__config>/#include <c++\/v1\/__config>/' /data/data/com termux/files/usr/include/c++/v1/support/win32/locale_win32.h -i

locale_win32.h file has #include <__config> but it is not being found while compiling so change it to direct to exact path #include <c++/v1/config>


Another error xlocinfo.h defined in local_win32.h is not found in termux how to add it

**Comment by xtkoba** [comment]
Seems like the `nl_langinfo` errors occur when making coreutils. I wonder how our `coreutils` package is able to work this around.

**Comment by tathastu871** [comment]
Not full package. Incomplete binaries.
Dont just compile minimal installs  if it is not functional what is use of compilation

**Comment by tathastu871** [comment]
@xtkoba 
have you made PR for minimal install or fully patched both core tools and unix tools.
Seems many several  binaries are not installed.

Please dont close any issue merging incomplete minimal package build.sh.

**Comment by Grimler91** [comment]
@tathastu871 ???

> have you made PR for minimal install or fully patched both core tools and unix tools.
> Seems many several binaries are not installed.

All binaries that are built in a standard `configure && make && make install` are installed, see the [build script](https://github.com/termux/termux-packages/blob/master/packages/dgsh/build.sh). Looks like, from Makefile, that both "core-tools" and "unix-tools" are included per default.

How is anyone suppose to know that there are missing functionality or programs that you expected to be included?

> Please dont close any issue merging incomplete minimal package build.sh.

It was closed by the accepted PR.

> If its not fully functional what is need of partially compiling it.

What is not fully functional? Open a bug report and fill in the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=bug+report&template=01-bug-report.yml&title=%5BBug%5D%3A+) if something is not working.

> Once PR has merged no one will further maintain or try again to compile it again.

No, that's not how it works, if issues are reported then we tend to at least try to fix them. 

> Reopen isssue and let termux develpers compile if you dont have time.

xtkoba has contributed 160+ packages in the last couple of months, which is way more than other "termux developers". 

> Seems many several binaries are not installed

Open a bug report if there is an issue with the package. We don't know which "several binaries" you are referring to.

**Comment by tathastu871** [comment]
dgsh is a shell like bash. so just like therr is ksh bash sh tcsh binaries to invoke those repective shells.

some additional binaries are copied to $PREFIX/libexec/dgsh folder  

So  In TERMUX_POST_INSTALL commands to copy or symlink them to $PREFIX/bin


But, also dgsh binary is not installed.

**Comment by tathastu871** [comment]
> @tathastu871 ???
> 
> > have you made PR for minimal install or fully patched both core tools and unix tools.
> > Seems many several binaries are not installed.
> 
> All binaries that are built in a standard `configure && make && make install` are installed, see the [build script](https://github.com/termux/termux-packages/blob/master/packages/dgsh/build.sh). Looks like, from Makefile, that both "core-tools" and "unix-tools" are included per default.
> 
> How is anyone suppose to know that there are missing functionality or programs that you expected to be included?
> 
> > Please dont close any issue merging incomplete minimal package build.sh.
> 
> It was closed by the accepted PR.
> 
> > If its not fully functional what is need of partially compiling it.
> 
> What is not fully functional? Open a bug report and fill in the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=bug+report&template=01-bug-report.yml&title=%5BBug%5D%3A+) if something is not working.
> 
> > Once PR has merged no one will further maintain or try again to compile it again.
> 
> No, that's not how it works, if issues are reported then we tend to at least try to fix them.
> 
> > Reopen isssue and let termux develpers compile if you dont have time.
> 
> xtkoba has contributed 160+ packages in the last couple of months, which is way more than other "termux developers".
> 
> > Seems many several binaries are not installed
> 
> Open a bug report if there is an issue with the package. We don't know which "several binaries" you are referring to.

xtoba has contributed several packages. 
But he aim for minimal build alwys which sometimes are non functional.
He doesnt even test them. Just blindly compiling is not enough

**Comment by Grimler91** [comment]
I seriously recommend you to change your attitude. You seem to be disappointed that someone spent their time to create a port for a package you requested.

> But he aim for minimal build alwys which sometimes are non functional.
> He doesnt even test them. Just blindly compiling is not enough

That's quite a harsh statement(/insult), how do you know this? Test how? The programs that are included in dgsh seem to work fine when I run them.

Open-source is suppose to be a community effort, if something doesn't work then the thing to do is to report an issue, and hope that someone feels like spending time on it, or open a PR with a fix. 
Complaining about previous work/commits will not solve anything. No one owns you anything.

**Comment by wmcbtech30** [comment]
maybe understand the phrase called "Be grateful for what you have" because Termux is the only app to include these packages and port it on Android device

**Comment by tathastu871** [comment]
It wasn't mean to offend someone. sorry.i had been waiting for this package to complete my script that i wrote some time ago. thats why i requested. But when it was merged and still incomplete got frustrated. sorry

**Comment by tathastu871** [comment]
> I seriously recommend you to change your attitude. You seem to be disappointed that someone spent their time to create a port for a package you requested.
> 
> > But he aim for minimal build alwys which sometimes are non functional.
> > He doesnt even test them. Just blindly compiling is not enough
> 
> That's quite a harsh statement(/insult), how do you know this? Test how? The programs that are included in dgsh seem to work fine when I run them.
> 
> Open-source is suppose to be a community effort, if something doesn't work then the thing to do is to report an issue, and hope that someone feels like spending time on it, or open a PR with a fix. Complaining about previous work/commits will not solve anything. No one owns you anything.
It wasn't mean to offend someone. sorry.i had been waiting for this package to complete my script that i wrote some time ago. thats why i requested. It was also this another package i was compiling whose dependencies are not in termux. so i created build.sh fot all those dependencies too. But xtoba passed statement that dont add that many paclages to termux only try minimal base . So how can it be functional. 
thats why when dgsh was merged and still incomplete got frustrated. sorry

**Comment by xeffyr** [comment]
`build.sh` working for on-device builds may not work for cross-compilimg environment. That's the case of `dgsh`.

So:
> xtoba passed statement that dont add that many paclages

is what can be expected.

**Comment by tathastu871** [comment]
> `build.sh` working for on-device builds may not work for cross-compilimg environment. That's the case of `dgsh`.
> 
> So:
> 
> > xtoba passed statement that dont add that many paclages
> 
> is what can be expected.
Talking about another packge that i been workint on previously
those dependencies were importnt for package to work and all are compatible for cross compiling excpt one that was not for x86.
