### ISSUE TITLE
Libdb

### ISSUE THREAD

**Issue by m1234567890creator** [termux/termux-packages#5493]
Lately Termux isn't accepting some packages it shows it has an unmet dependencies (I don't know what it means)
I am trying to install Openssh but it isn't installing rather showing an message stated (The following packages have unmet dependencies:
 openssh : Depends: krb5 but it is not going to be installed                            E: Unable to correct problems, you have held broken packages.) Help me to solve the problem as I need libdb to run openssh.

**Comment by Grimler91** [comment]
Try `apt full-upgrade`. 

If that does not work then please show the output of `termux-info`.

**Comment by m1234567890creator** [comment]
It isn't working take a look at my terminal 
![Screenshot_20200708-142747_Termux](https://user-images.githubusercontent.com/57172044/86900408-edc22e00-c128-11ea-8657-8ddac83570f6.jpg)

**Comment by m1234567890creator** [comment]
> Try `apt full-upgrade`.
> 
> If that does not work then please show the output of `termux-info 

It apparently says that krb5 not installed so I try to install it then it shows krb5 depends upon libdb so I try to install that,but dosen't work and a comment pops up showing libdb is not a package it depends on another package. I also tried installing termux more then 50 times but it dosen't work.

**Comment by Grimler91** [comment]
Try `apt dist-upgrade`, and provide output of `termux-info`

**Comment by m1234567890creator** [comment]
![Screenshot_20200708-155254_Termux](https://user-images.githubusercontent.com/57172044/86907913-5b735780-c133-11ea-8a29-26be1b2dab1b.jpg)
I tried it too take a look.

**Comment by Grimler91** [comment]
Could you share the message you get when you try `pkg in libdb` as well?

**Comment by m1234567890creator** [comment]
> Could you share the message you get when you try `pkg in libdb` as well?

Sure!!!!!
![Screenshot_20200708-162247_Termux](https://user-images.githubusercontent.com/57172044/86910507-6d56f980-c137-11ea-926f-fde24c8a1adf.jpg)
And I am also facing problems in install nethunter too it shows the following script (CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget"...)

**Comment by Grimler91** [comment]
libdb has apparently only been uploaded for aarch64. I'll fix that shortly. 

The wget issue is tracked in: https://github.com/termux/termux-packages/issues/4615
There's a workaround given in that issue

**Comment by m1234567890creator** [comment]
> libdb has apparently only been uploaded for aarch64. I'll fix that shortly. 
> 
> The wget issue is tracked in: https://github.com/termux/termux-packages/issues/4615
> There's a workaround given in that issue

Thanks sir
