### ISSUE TITLE
Shellphish

### ISSUE THREAD

**Issue by vikram888** [termux/termux-packages#5494]
![Screenshot_2020-07-08-18-27-56-349_com termux](https://user-images.githubusercontent.com/67533403/86923896-4f47c400-c14c-11ea-9309-d78acdf1bad8.png)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by vikram888** [comment]
It does not create link to send victim

**Comment by xeffyr** [comment]
We are not fixing third-party scripts nor helping to Shellfish and other phishing/hacking tools.
