### ISSUE TITLE
curl does not start with dynamic linker error

### ISSUE THREAD

**Issue by inducer** [termux/termux-packages#55]
If I run `curl`, this is what I see:

```
CANNOT LINK EXECUTABLE: cannot locate symbol "Curl_raw_nequal" referenced by "curl"...
```

**Comment by fornwall** [comment]
Have you installed the curl Termux package (`apt install curl`)? It could be that you are trying to run a system curl binary.

If the problem persists after installing the curl Termux package (start a new session afterwards to ensure that bash does not use the system curl cached), could you attach the output of `which curl` and `uname -a` here?

**Comment by inducer** [comment]
That was it. I did `apt install curl`, but I didn't restart my session.

**Comment by fornwall** [comment]
Great that it works now! You can also use `hash -r` to clear the path cache in bash without starting a new session!
