### ISSUE TITLE
'GeoIP.h' file not found - not sure how to install libgeoip/geoip-api-c

### ISSUE THREAD

**Issue by danbrownlad** [termux/termux-packages#5500]
![Screenshot_20200708-215231_Termux](https://user-images.githubusercontent.com/67621864/86969310-8080be00-c165-11ea-9ba1-cdd78cf705b5.jpg)

I've tried sudo pip install geoip, pip install geoip, easy_install geoip ^^ , sudo easy_install geoip and all have the same error. I went into the folder directory  /data/data/com.termux/files/home/ (where all my user packages are installed) and went into /data/data/com.termux/files/home/geoip-api-c/libGeoIP ( a package I installed using git clone ) and GeoIP.h is in THAT directory. Where do I put GeoIP.h or how do I install the geoip-api-c so that I can successfully run pip install geoip without the above error? Thanks.

**Comment by xeffyr** [comment]
Try
```
pkg install build-essential autoconf automake git
git clone https://github.com/maxmind/geoip-api-c.git
cd geoip-api-c
git checkout v1.6.12
bash bootstrap
./configure --prefix=$PREFIX
make
make install
```
