### ISSUE TITLE
clang_10.0.0_aarch64.deb upgrade problem

### ISSUE THREAD

**Issue by remo7777** [termux/termux-packages#5506]
**Problem description**

when i upgraded packages and i faced problem for
clang_10.0.0_aarch64.deb
![Screenshot_2020-07-10-10-45-47-92_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/28594846/87119257-1bc77f80-c29b-11ea-8287-a2bc2e61f726.jpg)

**Steps to reproduce**

**Expected behavior**

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
clang/stable 10.0.0 aarch64 [upgradable from: 9.0.1-8]
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf+ #2 SMP PREEMPT Tue Jun 9 21:01:44 CST 2020 aarch64 Android
Device manufacturer:
realme
Device model:
RMX1921
```

**Comment by remo7777** [comment]
thank you, its fine now.

**Comment by buttaface** [comment]
I moved several LLVM files around between subpackages in #5136 (those same commits were merged later), but figured that since the LLVM packages would all be upgraded together that it wouldn't matter. If that's not the case, let me know if there's anything else I should add.
