### ISSUE TITLE
Text typing delay

### ISSUE THREAD

**Issue by arturonavlag** [termux/termux-packages#5509]
Hello 
I have been using Termux on a Galaxy Tab A SM-T510 for a few months now and had no problems until last week. Now when I write on the terminal the text I am writing does not appear in real time, instead it appears only after I type a 'space' and this is very problematic. I have tried re-installing the app but this has not helped.
I hope you can provide a solution.

Thank you

Arturo

**Comment by Grimler91** [comment]
Hey, sounds like this issue on some samsung devices: https://github.com/termux/termux-app/issues/686. You can work around it by installing another keyboard

**Comment by arturonavlag** [comment]
Thank you,

I will try that

**Comment by arturonavlag** [comment]
Update: it worked. I installed two different keyboards from P!ayStore and both solve the problem.

Thank you again
