### ISSUE TITLE
cronie doesn't have the proper environment variables set

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#5510]
**Problem description**
When a cronjob with cronie is run only the following environment variables are set 
```
USER=u0_a84
HOME=/data/data/com.termux/files/home
LOGNAME=u0_a84
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
LANG=en_US.UTF-8
SHELL=/data/data/com.termux/files/usr/bin/sh
PWD=/data/data/com.termux/files/home
```
Busybox's crond used to just set the enivronment variables that it was started with including the very important `BOOTCLASSPATH`, `ANDROID_DATA`, `LD_PRELOAD`, `$PREFIX`, `ANDROID_ROOT`, `TZ` and `TMPDIR` that some programs, most notably termux-api commands, require to run.

**Steps to reproduce**
Create a cronjob that runs any `termux-api` command like `termux-vibrate`.
To get environment variables create a cronjob containing `env > $HOME/environment` and read that file.

**Expected behavior**
The environment variables that termux programs need to run and are set by default should also be set in cronie cronjobs

**Comment by xeffyr** [comment]
Thanks, that should be fixed in https://github.com/termux/termux-packages/commit/3e2a16f43a344efab898ed68e89e77069128bedc.

**Comment by Neo-Oli** [comment]
Hmm... I can't actually get to run any cronjobs with this new version. Does it still work for you?

**Comment by xeffyr** [comment]
Ok, will check it. Also need to add `TZ` and `LD_PRELOAD` to kept variables list.

**Comment by Neo-Oli** [comment]
Nothing special in the logcat. It claims it is running the cronjobs but nothing is actually happening. When downgrading to `1.5.5` they run as expected. The logcat is the same for both versions.

**Comment by xeffyr** [comment]
@Neo-Oli I have found issue. We have regression in ndk-headers, someone removed patch for `_PATH_DEFPATH` which results in incorrect PATH setting for crond.

**Comment by xeffyr** [comment]
Works now, tested with crontab `* * * * * termux-notification -t "$(date)"`.

**Comment by Neo-Oli** [comment]
@xeffyr I can confirm that it works now. Thanks for looking into this.

**Comment by Shivam623** [comment]
Hi, I am using .bashrc file to put my environment variables and it is not working. What I am missing?

**Comment by xeffyr** [comment]
@Shivam623 You are missing that .bashrc is only for interactive shells. Try to put your variables into ~/.profile or ~/.bash_profile instead.

**Comment by Shivam623** [comment]
Hi @xeffyr , I tried putting in both of the file but it doesn't work on Termux. :(

**Comment by xeffyr** [comment]
https://stackoverflow.com/questions/2229825/where-can-i-set-environment-variables-that-crontab-will-use

**Comment by Shivam623** [comment]
haha! @xeffyr  I am on the same page, trying the suggestions. Fingers cross.

**Comment by Shivam623** [comment]
so, * * * * * .$HOME/.profile; python <<file path>>/.test.py 

this worked for me. Finally!

Thanks a lot @xeffyr
