### ISSUE TITLE
E: Unable to locate package <package-name>

### ISSUE THREAD

**Issue by KR1470R** [termux/termux-packages#5511]
I can't install any package. How to fix that?
<img width=400 height=350 src="https://user-images.githubusercontent.com/54418933/87170125-9adba880-c2d9-11ea-964a-3a413b53b5b3.jpg">

**Comment by xeffyr** [comment]
1. To install Python v3.x: `pkg install python`.
2. Package android-tools isn't available and most likely never be.
3. Package java is not available as well as JDK. Is JDK will be available for Termux or not, that's unknown.
4. To install `lolcat`: `pkg install ruby && gem install lolcat`.

**Comment by KR1470R** [comment]
Still i have error unable to locate package.

**Comment by KR1470R** [comment]
I was reinstall termux and that's working. Idk, maybe i with paсkages screwed up.

**Comment by jvaccaro** [comment]
Just installed Termux and every package I want to install is listed as "Unable to Locate" How do I get the repoisytory info updated. Am moderately familiar with Ubuntu and the apt family.
Any pointers or hints appreciated

**Comment by Zack-sys** [comment]
> I can't install any package. How to fix that?
> <img width=400 height=350 src="https://user-images.githubusercontent.com/54418933/87170125-9adba880-c2d9-11ea-964a-3a413b53b5b3.jpg">
> 
> 

Same problem too on how to locate package lolcat

**Comment by Zack-sys** [comment]
@KR1470R what command is locate package <package name>

**Comment by kcubeterm** [comment]
> Same problem too on how to locate package lolcat

Already mentioned in above comment, install lolcat via Ruby gem. https://github.com/termux/termux-packages/issues/5511#issuecomment-656754640
