### ISSUE TITLE
Termux - Error starting the Kex server

### ISSUE THREAD

**Issue by fredrock007** [termux/termux-packages#5512]
So more than 10 times have I attempted the **"nethunter kex kill"** and **restarted termux**, alas, there's still an _error starting the Kex server._ Does anyone have a solution for this? 

![WhatsApp Image 2020-07-10 at 17 54 16](https://user-images.githubusercontent.com/68115564/87174639-c2ca0c80-c2d7-11ea-964d-3962b2410db6.jpeg)

**Comment by Grimler91** [comment]
I don't know which script you are running but it is not a script we have created. This is hence off-topic here, ask for support in the repository where you got the script instead
