### ISSUE TITLE
Error occurred during initialization of VM

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#5516]
**Problem description**
Arch Linux in PRoot QEMU
```
$ java
Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes
$ archlinux-java status
Available Java environments:
  java-8-openjdk/jre (default)
$ ./lib/android-sdk/tools/bin/sdkmanager
Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes
```

**Steps to reproduce**
Install (proot+qemu) Arch Linux 86_64 in Termux on Android 9 arm7 

**Expected behavior**

sdkmanager works in proot qemu

**Additional information**

[`bash setupTermuxArch.bash h`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch.bash) has information how to install alternate system images via the copy system image feature.

**Comment by SDRausty** [comment]
This error `proot error: '/data/data/com.termux/files/home/arch64/usr/lib/ghc-8.10.1/bin/ghc-pkg' is a 64-bit program whereas this version of proot handles 32-bit programs only
proot error` keeps cropping up at times too;  for example:
```
$ pacman -S shellcheck
.
.
.
(2/2) Registering Haskell modules...
proot error: '/data/data/com.termux/files/home/arch64/usr/lib/ghc-8.10.1/bin/ghc-pkg' is a 64-bit program whereas this version of proot handles 32-bit programs only
proot error: '/data/data/com.termux/files/home/arch64/usr/lib/ghc-8.10.1/bin/ghc-pkg' is a 64-bit program whereas this version of proot handles 32-bit programs only
error: command failed to execute correctly
```
[Shellcheck](https://github.com/koalaman/shellcheck) works in Arch Linux aarch64.  Any help to resolve these errors in termux proot qemu is welcome.

**Comment by xeffyr** [comment]
1. Output of `uname -a` in Termux.
2. Output of `uname -a` in proot (Arch Linux).
3. Proot version.
4. What QEMU package are you using?
5. How much RAM your device have?

**Comment by SDRausty** [comment]
1. Linux localhost 4.4.146+ #1 SMP PREEMPT Mon May 4 12:21:35 CST 2020 armv7l Android
2. Linux localhost 4.4.146+ #1 SMP PREEMPT Mon May 4 12:21:35 CST 2020 x86_64 GNU/Linux
3. 5.1.0
built-in accelerators: process_vm = yes, seccomp_filter = yes
Visit http://proot.me for help, bug reports, suggestions, patchs, ...
Copyright (C) 2015 STMicroelectronics, licensed under GPL v2 or later.
4. qemu-common/stable,now 1:4.1.1-5 arm [installed]
qemu-user-x86_64/stable,now 1:4.1.1-5 arm [installed]
qemu-utils/stable,now 1:4.1.1-5 arm [installed]
5. Mem:    912916k total,   857772k used,    55144k free,    27416k bu
Swap:   456452k total,   339364k used,   117088k free,   355660k ca

**Comment by xeffyr** [comment]
> 912916k total, 857772k used

Here you have a problem. You won't be able to allocate 1 GB of RAM because that's even less than OS provides.

Unfortunately you need to seek for other solutions, probably try to add `-Xmx512M` to java command line. Or get the device with 2+ GB of RAM.

**Comment by SDRausty** [comment]
```
$ java -Xmx512M
Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes
```

**Comment by xeffyr** [comment]
Could you try `-XX:MaxMetaspaceSize=64m` option instead ?

**Comment by SDRausty** [comment]
Thank you; it's still the same:
```
$ java -XX:MaxMetaspaceSize=64m                           
Error occurred during initialization of VM                         
Could not allocate metaspace: 1073741824 bytes                     
$ java -XX:MaxMetaspaceSize=64m -Xmx512M                  
Error occurred during initialization of VM                         
Could not allocate metaspace: 1073741824 bytes
```

**Comment by SDRausty** [comment]
> get the device with 2+ GB of RAM.

The police took my devices back in March 2020 and once more in April. Many of them have more RAM. Do you know a good lawyer who defends hackers familiar with USA law?
