### ISSUE TITLE
Request for wkhtmltopdf

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#5517]
**Package description**

This package helps in converting html files into rendered pdf. It is a python package. It can easily be installed with pip install package. But when trying to use it in python it gives following error. Wkhtmtopdf executable not found. And i cross  verified that actual executable is not there after installation.

**Link to home page and sources**
1. Home page:https://wkhtmltopdf.org/
2. Source code:https://github.com/wkhtmltopdf/wkhtmltopdf

**Additional information**
Have you compiled or tried to compile the package on device?
Tried compiling but it requires package yaml and thats not available in termux either by pip or apt
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by Grimler91** [comment]
Requested before in https://github.com/termux/x11-packages/issues/51
