### ISSUE TITLE
Packages from itspointless repo and stable repo conflict for directories while installing

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#5518]
**Problem description**

Eg. If html2text is installed on termux them ocaml cannot be installed as it produces following error:trying to overwrite '/data/data/com.termux/files/usr/man/man1', which is also in package html2text 1:2.0.0
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe). And vice versa.

Such errors also occur with many other packages from different repo on termux
**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
This should be fixed in version `1:2.0.0-1`.
