### ISSUE TITLE
lua: io.popen

### ISSUE THREAD

**Issue by lyderic** [termux/termux-packages#552]
I don't know if this is a technical limitation or a compilation choice, but io.popen doesn't work on termux's lua.

Can it please be added?

Many thanks!

**Comment by fornwall** [comment]
Thanks - this has now been fixed in version `5.3.3-3` of the lua package, to which you can update with:

    apt update && apt upgrade

**Comment by lyderic** [comment]
Thanks Fredrick. You rock!
L.
