### ISSUE TITLE
Package request   ta-lib

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-packages#5522]
Package request : ta-lib

fail to install ta-lib by follow steps. 

wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar -zxvf ta-lib-0.4.0-src.tar.gz
cd ta-lib
./configure --prefix=$PREFIX -build=arm
make
make DESTDIR=$PREFIX install
pip install ta-lib

**Comment by ifurther** [comment]
@leechaowen please check the package.

**Comment by xeffyr** [comment]
Package is added, but has incorrect name - `talib` instead of `ta-lib`. I will rename it.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install ta-lib
```

**Comment by leechaowen** [comment]
Good. Thanks.

**Comment by jadevinicole** [comment]
Is this package not available for Termux version 0.83 running Android 6?  I tried installing it but it says package not found.

**Comment by xeffyr** [comment]
> Is this package not available for Termux version 0.83 running Android 6?

It is not available. Since 01.01.2020 Termux on Android 5.x - 6.x does not receive any new packages or updates.

**Comment by xeffyr** [comment]
If you need it on legacy Termux, try steps shown here https://github.com/termux/termux-packages/issues/5522#issue-655217869.

**Comment by jadevinicole** [comment]
Is there a workaround to install it?  I've been looking everywhere and can't find anything.

**Comment by xeffyr** [comment]
No workaround. Android 7 packages are not compatible with Android 6.

**Comment by jadevinicole** [comment]
Thanks.  After using a combination of the instructions you provided above and the instructions on this other thread: https://github.com/myfreess/Mytermuxdoc/issues/4#issuecomment-455048781, and a little google translate, I got it to install in Termux legacy.  Thanks again.
