### ISSUE TITLE
Compile MariaDB with LZ4 compression support

### ISSUE THREAD

**Issue by user655362020** [termux/termux-packages#5524]
**Description**
Currently mariadb only uses zlib compression which is cpu intensive. LZ4 is faster/uses less cpu.
**Additional information**
https://mariadb.com/kb/en/innodb-page-compression/

**Comment by fornwall** [comment]
@user655362020 If you update by running `pkg up` (which should get you version `10.5.4` of mariadb), is LZ4 compression enabled? If not, do you know the necessary build configuration?

**Comment by xeffyr** [comment]
Need liblz4 in dependencies and `-DGRN_WITH_LZ4=ON -DWITH_INNODB_LZ4=ON`.

**Comment by xeffyr** [comment]
Confirming that Innodb engine has LZ4 support now.
