### ISSUE TITLE
libLLVM-9.so not found on packages `ccls`

### ISSUE THREAD

**Issue by Cvar1984** [termux/termux-packages#5527]
**Problem description**

**error when installing ccls**

`CANNOT LINK EXECUTABLE "ccls": library "libLLVM-9.so" not found
Aborted`
```sh
patchelf --replace-needed libLLVM-9.so libLLVM-10.so $(which ccls)
```
```
CANNOT LINK EXECUTABLE "ccls": cannot locate symbol "_ZN4llvm24DisableABIBreakingChecksE" referenced by "/data/data/com.termux/files/usr/bin/ccls"...
```
> Looks like need to upgraded

Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf-g5c5b6e3 #1 SMP PREEMPT Tue Nov 5 23:37:25 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 5A
```

**Comment by ayushashi11** [comment]
i am facing the same issue but with rustc #5519

**Comment by xeffyr** [comment]
Closing as `ccls` is fixed now.
