### ISSUE TITLE
Package request: mono

### ISSUE THREAD

**Issue by NTBBloodbath** [termux/termux-packages#5529]
**Package description**
Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime which allow developers to easily create cross platform applications part of the .NET Foundation.

**Link to home page and sources**
1. Home page: https://www.mono-project.com/
2. Source code: https://github.com/mono/mono

**Additional information**
Someone could already compile it (along with MSBuild) without problems in Termux applying some patches. Below I leave the GH repository where he put the patches done and the installation instructions.

[termux-mono](https://github.com/IanusInferus/termux-mono)

**Comment by Grimler91** [comment]
Duplicate of https://github.com/termux/termux-packages/issues/40
