### ISSUE TITLE
termux-contact-list: return all phone numbers

### ISSUE THREAD

**Issue by rqcy** [termux/termux-packages#553]
Hi, it would be cool, if termux-contact-list could return all phone numbers instead of just a single phone number per contact.

**Comment by fornwall** [comment]
This issue was moved to termux/termux-api#73

**Comment by someoneb100** [comment]
Why is this closed? This would be quite usefull to do

**Comment by Neo-Oli** [comment]
@someoneb100 This issue was moved to termux/termux-api#73

**Comment by Gan890** [comment]
How can i use
