### ISSUE TITLE
add-apt-repository not found, need software-properties-common package,

### ISSUE THREAD

**Issue by hessam94** [termux/termux-packages#5530]
Hello, 
I need to use add-apt-repository, it seems there is solution to get software-properties-common but this package also not found. 
Would u update pkg list, or what is the alternative way? This is my running command: sudo add-apt-repository
"deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
Thanks

**Comment by xeffyr** [comment]
If you need `software-properties-common` within the Docker image, then execute:
```
sudo apt update
sudo apt install software-properties-common
```

**Comment by hessam94** [comment]
I need it to get and install docker, also running apt install software-properties-common shows that unable to locate packageI tried lots of ways so far,,, 


Sent from Yahoo Mail for iPhone


On Sunday, July 12, 2020, 3:33 PM, Leonid Pliushch <notifications@github.com> wrote:




If you need software-properties-common within the Docker image, then execute:
sudo apt update
sudo apt install software-properties-common
