### ISSUE TITLE
package containing ldd tool, Android 10

### ISSUE THREAD

**Issue by anton010** [termux/termux-packages#5531]
ldd is to show dependenties on libraries, was earlier on package libc-bin.

**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by Grimler91** [comment]
It is part of the binutils package

**Comment by anton010** [comment]
no, termux gives error message:
as well as for ldd as for libc.
and trying to install by pkg the package libc-bin also is not possible.
On Galaxy S10+ with android 10.
But many other SW I have succesfully installed.
I am very happy that the packet manager "pkg" works so fine.
greetings
Anton_Wessel@t-online.de <mailto:Anton_Wessel@t-online.de>



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: Henrik Grimler
Betreff: Re: [termux/termux-packages] package containing ldd tool, Android 
10 (#5531)
Datum: 12.07.2020, 22:28 Uhr
An: termux/termux-packages
Cc: anton010, Author



It is part of the binutils package

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/termux/termux-packages/issues/5531#issuecomment-657271127> 
, or unsubscribe

**Comment by xeffyr** [comment]
@anton010 Android (Termux) linker does not support listing the loaded dynamic libraries like on normal Linux distribution. So we use a wrapper around `objdump` utility to do that which results in a different output format.

Termux does not provide the libc-bin package and will not provide in future as it uses libc provided by Android OS.

**Comment by anton010** [comment]
Can you receive the prior and this message ?
Dince I cannot ise an Email address, can only use the bitton "Reply = send 
back"

===

Motivated by contact with you, I have examined:

(1)
Refering to packages, I have made a listing with pkg:
pkg list-installed
I have redirected into this file:

/data/data/com.termux/files/home/WEDIR_packages/we_pkg_list_installed

this I send you in attachment 1.

==

(2)
Also to packages, I have made a listing with pkg:
pkg list-all
I have redirected into this file:

/data/data/com.termux/files/home/WEDIR_packages/we_pkg_list_all

this I send you in attachment 2.

==

From both we can see that the package "libc++" is contained but the package 
"libc", resp. "libc-bin" is not contained.

(3)
looking for which files are in the installed package "libc++" I have made
pkg files libc++
and redirected to file

/data/data/com.termux/files/home/WEDIR_packages/we_pkg_files_libc++

this I send you in attachment 3.

===============

Now again I am suffering with the clipboard. So please give me a help.

On Galaxy S10+ I use the "Android Keyboard" by NextApps, downloaded from 
Googl Play Store.
This has many advanteges
There is a key "Select" (no note which code is sent).
Keys are
for Cut (ctrl-x)
for Copy (ctrl-y)
for Insert (ctrl-v)
and to select whole text (ctrl+a)

In all apps it works fine, and one is not dependent on the tears of 
Android.

The clipboard thus used is identical with the system clipboard.

But in termux:

The functions and keys of my keyboard do not work in termux.
I have to use the tears of Android.
Would be bad enough.

But though it seems to be the system clipboard, it is not the system 
clipboard.
Fortunatly in termux there are the functions
termux-clipboard-set
termux-clipboard-get
These allow to communicate withe other Apps.

But how can I paste on the position os the cursor ?

And I have succeeded, but it is very difficult when I have to mark a region 
of text and to bring this region to another App.

My way was:

first with the tears of Android copy the text to the special clipboard.
then within termux, open a command line. in this command line write the 
command
termux-clipboard-set.
and in this command line paste the texte grom the special clipboard on an 
appropriate point duitible to be piped tobthe command
termux-clipboard-set.

greetings
Anton_Wessel@t-online.de <mailto:Anton_Wessel@t-online.de>


###########


--- Original-Nachricht ---
Von: Anton Wessel
Betreff: AW: Re: [termux/termux-packages] package containing ldd tool, 
Android 10 (#5531)
Datum: 13.07.2020, 11:51 Uhr
An: termux/termux-packages


no, termux gives error message:
as well as for ldd as for libc.
and trying to install by pkg the package libc-bin also is not possible.
On Galaxy S10+ with android 10.
But many other SW I have succesfully installed.
I am very happy that the packet manager "pkg" works so fine.
greetings
Anton_Wessel@t-online.de <mailto:Anton_Wessel@t-online.de>




Gesendet mit der Telekom Mail App



--- Original-Nachricht ---
Von: Henrik Grimler
Betreff: Re: [termux/termux-packages] package containing ldd tool, Android 
10 (#5531)
Datum: 12.07.2020, 22:28 Uhr
An: termux/termux-packages
Cc: anton010, Author


It is part of the binutils package

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { " @context <mailto:@context> ": "<http://schema.org> ", " @type
<mailto:@type> ": "EmailMessage", "potentialAction": { " @type
<mailto:@type> ": "ViewAction", "target": "
<https://github.com/termux/termux-packages/issues/5531#issuecomment-657271127> 
", "url": "
<https://github.com/termux/termux-packages/issues/5531#issuecomment-657271127> 
", "name": "View Issue" }, "description": "View this Issue on GitHub", 
"publisher": { " @type <mailto:@type> ": "Organization", "name": "GitHub", 
"url": "<https://github.com> " } } ]




------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: Henrik Grimler
Betreff: Re: [termux/termux-packages] package containing ldd tool, Android 
10 (#5531)
Datum: 12.07.2020, 22:28 Uhr
An: termux/termux-packages
Cc: anton010, Author



It is part of the binutils package

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/termux/termux-packages/issues/5531#issuecomment-657271127> 
, or unsubscribe
