### ISSUE TITLE
Internal server error GitHub clone

### ISSUE THREAD

**Issue by abhishekchauhan-dev** [termux/termux-packages#5535]
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main           # x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/termuxblack.list
deb https://hax4us.github.io/TermuxBlack/ termuxblack main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:                                                   Linux localhost 3.18.120-perf-gd85b39b #1 SMP PREEMPT Fri May 8 17:16:24 CST 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 6 Pro
![IMG_20200713_114550_773](https://user-images.githubusercontent.com/66209860/87276819-ba9fe600-c4fe-11ea-90d8-fecdaec47bdf.jpg)

**Comment by Grimler91** [comment]
Either a temporary problem or a problem with "termuxblack". Has nothing to do with us in any case so closing as off-topic

**Comment by abhishekchauhan-dev** [comment]
Its GitHub server error
