### ISSUE TITLE
Package request: bashtop

### ISSUE THREAD

**Issue by NTBBloodbath** [termux/termux-packages#5537]
**Package description**
Bashtop is a resource monitor that shows usage and stats for processor, memory, disks, network and processes.

**Link to home page and sources**
1. Home page & Source: https://github.com/aristocratos/bashtop

**Additional information**
Bashtop is already compiled so you just need to clone the repository and do `make install`.

**Comment by xeffyr** [comment]
Contains `psutil` in Python module requirements, but we do not package them - https://github.com/aristocratos/bashtop/blob/master/requirements.txt#L1.

Also `psutil` dependency is known to have issues when accessing /proc/ entries on devices with SELinux - https://github.com/termux/termux-app/issues/1646#issue-655884769.
