### ISSUE TITLE
Invalid parameter when using vp8 but not when using vp9

### ISSUE THREAD

**Issue by belldandu** [termux/termux-packages#554]
![screenshot_20161116-212033](https://cloud.githubusercontent.com/assets/5639384/20373943/564035c0-ac43-11e6-9e44-15d2b4311faa.png)

There is a chance this is human error but i wanted to get another pair of eyes to make sure.

**Comment by belldandu** [comment]
Yeah this behavior does not happen on my ubuntu server.

**Comment by fornwall** [comment]
So, is the failing command the following?

    ffmpeg -i in.mp4 -c:v libvpx -b:v 2M -c:a libvorbis out.webm

Could you link to the input video file causing the problem (it doesn't happen for me when I try on another video file)?

Also, what is the CPU architecture of the device (what is the output of running `dpkg --print-architecture`)?

**Comment by fornwall** [comment]
Ok, the problem does not happen on `aarch64`, but on arm it can be reproduced:

    curl -o in.mp4 http://www.sample-videos.com/video/mp4/480/big_buck_bunny_480p_1mb.mp4
    ffmpeg -i in.mp4 -c:v libvpx -b:v 2M -c:a libvorbis out.webm

**Comment by fornwall** [comment]
Related link: https://bugs.chromium.org/p/webm/issues/detail?id=800

    The issue is that on android we soft enable realtime only.
    The failing tests are expecting modes other than realtime.

    You can enable non-realtime by setting --disable-realtime-only.

I guess the libvpx package needs to be built with `--disable-realtime-only`.

**Comment by fornwall** [comment]
The issue has now been fixed in version `1.6.0-2` of the libvpx package. Update with:

    apt update && apt upgrade

**Comment by belldandu** [comment]
Awesome
