### ISSUE TITLE
packages request: curl,bzip2,xz-utils

### ISSUE THREAD

**Issue by qianxin12568** [termux/termux-packages#5544]
**Package description**

hi there.
can you support: curl,bzip2,xz-utils package scripts?
All of them are Core utilities about create bootsrap file.
But they can not found in the packages folder.

thanks.

**Comment by kcubeterm** [comment]
Are you looking for build file (build.sh) ?, 
browse this repo for creating bootstrap file https://github.com/termux/termux-packaging

**Comment by qianxin12568** [comment]
@kcubeterm hello.I changed the application id.Now I want to use docker to build all packages which is required by bootstrap.

before,I think about: I must to build all depends packages of bootstrap,and then,create packages list file, and put it on my apt source.

modify the [generate-bootstraps.sh](https://github.com/termux/termux-packaging/blob/master/scripts/generate-bootstraps.sh) file , adjust the repo_base_url and other codes about my apt source repo..

last.use the termux-packaging shell script to build the bootstrap.

right? sorry...I do not sure about my idea is right or not. because I am not clear about the complex project...

Thanks...

**Comment by Grimler91** [comment]
`curl, `bzip2` and `xz-utils` are all subpackages, build the main package and you'll get the subpackages as well

* [curl](https://github.com/termux/termux-packages/blob/master/packages/libcurl/curl.subpackage.sh)
* [bzip2](https://github.com/termux/termux-packages/blob/master/packages/libbz2/bzip2.subpackage.sh)
* [xz-utils](https://github.com/termux/termux-packages/blob/master/packages/liblzma/xz-utils.subpackage.sh)

**Comment by qianxin12568** [comment]
@Grimler91  thanks.I have found them in the debs folder.
but.can you tell me what is their main package?I am confusion..

**Comment by xeffyr** [comment]
curl \-\-\> libcurl
bzip2 \-\-\> libbz2
xz-utils \-\-\> liblzma

**Comment by qianxin12568** [comment]
@xeffyr hi.I am Chinese.GOV has a GFW.Sometimes I can not running well the build-packages script.Such as the tor package.
I use your sript "build-packages.sh" to build tor.but network is blocked.If I use proxy to download,the script exist CA problem.
I want to ask that:`./scirpt/build/termux_download.sh` is working for download the libs ? I need to add `-k` before the curl command.

I readed the help infos about build-package.sh, it looks like need a flag to skip the CA check.

Even though it is unsafe.

thanks.

**Comment by xeffyr** [comment]
> I want to ask that:./scirpt/build/termux_download.sh is working for download the libs ?

This script is a wrapper for `curl`. It does these things:
1. Downloads package to specified destination.
2. Compares SHA-256 of downloaded file with given value.
3. If download failed, tries again after waiting.

It can be used to download any file.

> I use your sript "build-packages.sh" to build tor

If you have big trouble with downloading tor source code, then just
```
rm -f ./packages/apt/apt-transport-tor.subpackage.sh
```
\- in case if you building it only as dependency for apt.

> it looks like need a flag to skip the CA check

You may use whatever flags you want, but any unofficial changes to build system are out of support.

We will not add flags to skip CA certificate checking, otherwise https use for downloading sources will be useless. We prefer https for all downloaded files, no matter whether their integrity is checked through checksums or GPG signatures.

**Comment by qianxin12568** [comment]
> > I want to ask that:./scirpt/build/termux_download.sh is working for download the libs ?
> 
> This script is a wrapper for `curl`. It does these things:
> 
> 1. Downloads package to specified destination.
> 2. Compares SHA-256 of downloaded file with given value.
> 3. If download failed, tries again after waiting.
> 
> It can be used to download any file.
> 
> > I use your sript "build-packages.sh" to build tor
> 
> If you have big trouble with downloading tor source code, then just
> 
> ```
> rm -f ./packages/apt/apt-transport-tor.subpackage.sh
> ```
> 
> - in case if you building it only as dependency for apt.
> 
> > it looks like need a flag to skip the CA check
> 
> You may use whatever flags you want, but any unofficial changes to build system are out of support.
> 
> We will not add flags to skip CA certificate checking, otherwise https use for downloading sources will be useless. We prefer https for all downloaded files, no matter whether their integrity is checked through checksums or GPG signatures.

thank you very much.
> rm -f ./packages/apt/apt-transport-tor.subpackage.sh
I need it.You konw that is as dependency for apt.

again,thanks for your introduction.
