### ISSUE TITLE
package request: ntp

### ISSUE THREAD

**Issue by rybasd** [termux/termux-packages#5546]
NTP is a protocol designed to synchronize the clocks of computers over a network.

NTP version 4, a significant revision of the previous NTP standard, is the current development version. It is formalized by RFCs released by the IETF.

**Link to home page and sources**
1. Home page: http://www.ntp.org/index.html
2. Source code: http://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ntp-4.2/ntp-4.2.8p15.tar.gz

**Additional information**
I tried to compile it on device. (Samsung Galaxy Tab S6, android 10)
* If it didn't work then please provide the error you ran into.
Make told this:
`In file included from icom.c:14:
/data/data/com.termux/files/usr/include/unistd.h:386:25: error: static declaration of 'getpass' follows non-static declaration
static inline char* getpass(const char* prompt) {
                        ^`

**Comment by rybasd** [comment]
Compiled and installed chrony

**Comment by ChiefMikeK** [comment]
It probably would have been better to rename this to...  
  .
 **Package Request: chrony**  vs closing it ¿:neckbeard:?
