### ISSUE TITLE
missing package sys_msg & sys_shm already implements in bionic

### ISSUE THREAD

**Issue by yozman** [termux/termux-packages#5547]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

https://android.googlesource.com/platform/bionic/+/master/libc/bionic/sys_msg.cpp
https://android.googlesource.com/platform/bionic/+/master/libc/bionic/sys_shm.cpp

<https://android.googlesource.com/platform/bionic/+/master/docs/status.md>
```md
...
New libc functions in O (API level 26):

sendto FORTIFY support
__system_property_read_callback/__system_property_wait
legacy bsd_signal
catclose/catgets/catopen (adding <nl_types.h>)
ctermid
all 6 <grp.h>/<pwd.h> (get|set|end)(gr|pw)ent functions
futimes/futimesat/lutimes
getdomainname/setdomainname
getsubopt
hasmntopt
mallopt
mblen
4 <sys/msg.h> msg* functions
<langinfo.h> nl_langinfo/nl_langinfo_l
pthread_getname_np
2 new Linux system calls quotactl and sync_file_range
4 <sys/sem.h> sem* functions
4 <sys/shm.h> shm* functions
5 legacy <signal.h> functions: sighold/sigignore/sigpause/sigrelse/sigset
strtod_l/strtof_l/strtol_l/strtoul_l
<wctype.h> towctrans/towctrans_l/wctrans/wctrans_l
...
```

**Comment by xeffyr** [comment]
We are not going to use the API levels >24 for now. For certain packages compatible only with Android higher than 7.0 maybe, but not in mass.

**Comment by xeffyr** [comment]
Note that POSIX message queues support is available in the latest Bionic libc, but is disabled kernel level.

**Comment by xtkoba** [comment]
For future reference: `<sys/shm.h>` functionality is available with `libandroid-shmem` package.
