### ISSUE TITLE
[question] Is possible to perform apt install in terminal? 

### ISSUE THREAD

**Issue by heefan** [termux/termux-packages#555]
Hi, i would like to ask if possible to run `apt install` in android. 

For example, I enter android via 
`adb shell` and switch to root 

when I type `apt install wget`, I will get the error
```
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
W: No sandbox user '_apt' on the system, can not drop privileges
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (2)
```
so, is there a way to perform the `#apt install wget` in terminal ? 

Thanks

**Comment by fornwall** [comment]
Yes - just don't run it as root!

Everything Termux installs is done in an app-private folder without affecting the system, so there is no point running `apt` as root.
