### ISSUE TITLE
Clang upgrade with clangd already installed fails

### ISSUE THREAD

**Issue by shadmansaleh** [termux/termux-packages#5550]
**Problem description**

Today I ran apt-get update and apt-get upgrade to upgrade installed packages . After attemped upgrade clang is now broken . The apt process exited with broken pipe error , complaining about clangd being in two packages clang package and clangd package.
I think the problem is due to the fact clangd was recently moved in with package group clang/llvm but the old clangd package still remains . So apt is not replacing the $PREFIX/usr/bin/clangd and related files since it was installed from a defferent package . I tried apt-get remove clangd that didn't work
I'm pasting termux output in aditional info.

**Steps to reproduce**

upgrade to clang 10 while having clang and clangd installed

**Expected behavior**

Clang and Clangd both should be upgraded if Upgrade is available

**Additional information**

apt output on apt-get upgrade
```$ apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 clang : Depends: libllvm (= 9.0.1-7) but 10.0.0-1 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

apt output on command apt --fix-broken install suggested by apt

```$ apt --fix-broken install -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  clang
The following packages will be upgraded:
  clang
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
85 not fully installed or removed.
Need to get 0 B/18.6 MB of archives.
After this operation, 100.0 MB of additional disk space will be used.
(Reading database ... 44585 files and directories currently installed.)
Preparing to unpack .../clang_10.0.0-1_aarch64.deb ...
Unpacking clang (10.0.0-1) over (9.0.1-7) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/clang_10.0.0-1_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/bin/clangd', which is also in package clangd 9.0.1-3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/clang_10.0.0-1_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

Termux-info
```Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://main.termux-mirror.ml stable main
# science-repo (sources.list.d/science.list)
deb https://science.termux-mirror.ml science stable
# game-repo (sources.list.d/game.list)
deb https://games.termux-mirror.ml games stable
# unstable-repo (sources.list.d/unstable.list)
deb https://unstable.termux-mirror.ml unstable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://x11.termux-mirror.ml x11 main
Updatable packages:
clang/stable 10.0.0-1 aarch64 [upgradable from: 9.0.1-7]
Android version:
10
Kernel build information:
Linux localhost 4.4.177-18663293 #1 SMP PREEMPT Fri Jun 12 04:31:07 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-M205F
```

**Comment by Grimler91** [comment]
`apt remove clangd; apt install clang` should work, but yes, this should be fixed

**Comment by shadmansaleh** [comment]
I have already tried that but apt remove clangd does nothing and apt install clang fails as usual . But removing
$PREFIX/usr/var/lib/dpkg/clangd.list and $PREFIX/usr/var/lib/dpkg/clangd.md5sums does the job .
Anyone in similer situation try this
rm ~/../usr/var/lib/dpkg/clangd.* && apt upgtade :)

Hopefuly didn't break anything .

**Comment by Grimler91** [comment]
You are probably fine!

An updated libllvm should be available when the CI finishes building https://github.com/termux/termux-packages/commit/89457e666127dbc3f1c3cacdad208910e3a6f868
