### ISSUE TITLE
apt package: build.sh script queation

### ISSUE THREAD

**Issue by qianxin12568** [termux/termux-packages#5551]
Hi there.
I am sorry about asking this queation.But I am confusion.I recompiles those packages and install termux on my Android device.But,I need to replace the source.list file content.
So,I want to rebuild the apt package and rebuild bootstrap file.After all.My work is not valid.
I find the build.sh script and modify it.

path: `/home/builder/termux-packages/packages/apt/build.sh`

```shell
termux_step_post_make_install() {
        printf "# The main termux repository:\ndeb [trusted=yes] url ./\n" > $TERMUX_PREFIX/etc/apt/sources.list
        cp $TERMUX_PKG_BUILDER_DIR/trusted.gpg $TERMUX_PREFIX/etc/apt/

        # apt-transport-tor
        ln -sfr $TERMUX_PREFIX/lib/apt/methods/http $TERMUX_PREFIX/lib/apt/methods/tor
        ln -sfr $TERMUX_PREFIX/lib/apt/methods/http $TERMUX_PREFIX/lib/apt/methods/tor+http
        ln -sfr $TERMUX_PREFIX/lib/apt/methods/https $TERMUX_PREFIX/lib/apt/methods/tor+https

        # man pages
        mkdir -p $TERMUX_PREFIX/share/man/
        cp -Rf $TERMUX_PKG_BUILDER_DIR/man/* $TERMUX_PREFIX/share/man/
}
```

Maybe something wrong.my wrong.Can you give me some advices?thanks~

**Comment by xeffyr** [comment]
> deb [trusted=yes] url ./

As Debian documentation states, repository definition must be exactly in this format:
```
deb uri distribution [component1] [component2] [...]
```
No `./` at the end. See https://wiki.debian.org/DebianRepository/Format.

***

Btw, do you actually have own APT repository hosted somewhere ? If not, you won't be able to build bootstraps as scripts rely on  APT repository metadata.

**Comment by qianxin12568** [comment]
@xeffyr 
yes.I have my apt repos on my cloud vps.I have not created any gpg sig.
so I added `[trusted=yes]` to skip this safe problem.
If other shell script call this function,it should work well.right?
I just need it to preconfigure the source.list content.
thanks.
