### ISSUE TITLE
missing ffi feature for php

### ISSUE THREAD

**Issue by yozman** [termux/termux-packages#5552]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

<https://www.php.net/manual/zh/book.ffi.php>
could u please enable ffi feature for php v7.4 compile with `--with-ffi`

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/206b76f783a881143b3a72caeef6593d387b8829.

```
~ $ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
gd
gmp
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
zip
zlib
```
