### ISSUE TITLE
proot error: execve("/usr/bin/env"): Function not implemented

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#5554]
**Problem description**
proot error: execve("/usr/bin/env"): Function not implemented
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot --help`.
proot error: can't chmod '/data/data/com.termux/files/usr/tmp/proot-23885-5KfQsQ': No such file or directory
proot error: can't chdir to '/data/data/com.termux/files/usr/tmp': No such file or directory

**Steps to reproduce**
Install Arch Linux i686 or x86_64 and QEMU.  

**Expected behavior**
Arch Linux i686 and x86_64 run in QEMU on armv7l Android 10 with 2907792 kB RAM as expected.

**Additional information**
The command [`bash setupTermuxArch.bash bloom`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch.bash#L596&&#L600) attempts to install and configure alternate architectures of Arch Linux.

**Comment by SDRausty** [comment]
This is what is installed:
```
qemu-common/stable,now 1:4.1.1-5 arm [installed]
qemu-user-i386/stable,now 1:4.1.1-5 arm [installed]
qemu-user-x86_64/stable,now 1:4.1.1-5 arm [installed]
qemu-utils/stable,now 1:4.1.1-5 arm [installed]
```

PRoot init is `exec proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch -q /data/data/com.termux/files/usr/bin/qemu-x86_64 -b /dev/ashmem:/dev/ashmem -b /proc/self/fd/2:/dev/stderr -b /proc/self/fd/1:/dev/stdout -b /proc/self/fd/0:/dev/stdin -b /storage/:/storage/ -b /data/data/com.termux/files/home:/data/data/com.termux/files/home -b /sdcard:/sdcard -b /data/data/com.termux/files/usr:/data/data/com.termux/files/usr -b /proc/:/proc/ -b /vendor/:/vendor/ -b /system/:/system/ -b /data/data/com.termux/files/home/arch/tmp:/dev/shm -b /data/data/com.termux/files/home/arch/var/binds/fbindprocstat:/proc/stat -b /dev/:/dev/ -w "$PWD" /usr/bin/env -i HOME=/root TERM="$TERM" ANDROID_DATA=/data  /bin/bash -l`.  The error is the same with both i686 and x86_64 architectures.

**Comment by SDRausty** [comment]
```
[16:17arch]$ LD_PRELOAD= proot -0 -r . -b /dev -b /proc -b /sys -w / -q qemu-x86_64 /bin/su -lc 'ls -alh /'
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/qemu-x86_64": library "libm.so" not found
[16:17arch]$
[16:17arch]$ l bin/su
-rwsr-xr-x 1 u0_a258 u0_a258 67552 May 20 15:27 bin/su
```

**Comment by SDRausty** [comment]
Android 9 works in as expected with:
```
LD_PRELOAD= strace -vs5000 -o trace.txt proot -0 -r . -b /dev -b /proc -b /sys -b /data -b /system -w / -q qemu-x86_64 /bin/su -lc 'gzip --help'
```

**Comment by SDRausty** [comment]
Adding `-b /apex:/apex` got both Arch Linux i686 and x86_64 to boot on armv7, but there are errors:
```
pacman -Syu sed
:: Synchronizing package databases...                                  
error: failed retrieving file 'core.db' from mirrors.ocf.berkeley.edu : Could not resolve host: mirrors.ocf.berkeley.edu
```
An unresolved host that is resolved?
```
ping mirrors.ocf.berkeley.edu
PING fallingrocks.ocf.berkeley.edu (169.229.226.30) 56(84) bytes of data.
64 bytes from fallingrocks.ocf.berkeley.edu (169.229.226.30): icmp_seq=1 ttl=45 time=110 ms
```

**Comment by xeffyr** [comment]
@SDRausty You need a bit more configuration. Not just `-b /apex:/apex` on Android 10.

1. System partition:
```
-b /system:/system
```
2. Environment variables:
```
export ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
export ANDROID_ROOT=/system
```
3. Check the `/etc/resolv.conf`.
