### ISSUE TITLE
Full version of apksigner from Android SDK (#5553) is broken on arm7 Android 9 and Android 10

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#5555]
**Problem description**

Full version of apksigner from Android SDK (#5553) is broken on arm7 Android 9 and Android 10.

**Steps to reproduce**

Run [setup.buildAPKs.bash](https://github.com/BuildAPKs/buildAPKs/blob/master/setup.buildAPKs.bash) and `apksigner` fails.  

**Expected behavior**
```
Running zip -r -u com.example.SanAngeles.apk lib...
  adding: lib/ (stored 0%)
  adding: lib/armeabi-v7a/ (stored 0%)
  adding: lib/armeabi-v7a/libsanangeles.so (deflated 63%)
Signing com.example.SanAngeles.apk...
Creating new keystore (using 'android' as password and 'alias' as the key alias).
```
**Found behavior**
```
Running zip -r -u com.example.SanAngeles.apk lib...
Signing com.example.SanAngeles.apk...
buildAPKs build.one.bash WARNING:  ERROR 1 received by build.one.bash!
```

**Additional information**
~~`zip` also fails silently on Android 10.~~ Edit: `zip` was not installed

**Comment by xeffyr** [comment]
New apksigner version uses a **different command line format**. So, you'll have to update your scripts.

**Comment by SDRausty** [comment]
Thank you for the clarification.

**Comment by SDRausty** [comment]
Is there a `keytool` that runs in Termux?
