### ISSUE TITLE
Downloading Package is too long

### ISSUE THREAD

**Issue by BJS611** [termux/termux-packages#5558]
Please Fix This

✘  ~  pkg install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  c-ares
The following NEW packages will be installed:
  c-ares nodejs
0 upgraded, 2 newly installed, 0 to remove and 2 not upgraded.
Need to get 8223 kB/8332 kB of archives.
After this operation, 59.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 nodejs aarch64 14.4.0-1 [8223 kB]
Err:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 nodejs aarch64 14.4.0-1
  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/nodejs_14.4.0-1_aarch64.deb  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by Grimler91** [comment]
Problem is with your internet connection, nothing we can do.

You could try switching to a mirror with `termux-change-repo`.

**Comment by BJS611** [comment]
I can't connect because I use wifi and then I switch to mobile data all of a sudden that's the problem 

Failed to connect to mirrors.bfsu.edu.cn port 443: Connection timed out

**Comment by BJS611** [comment]
[*] BFSU mirrors selected                                                 Changing main repository
    Changing root repository                                          [*] Running apt update
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease Ign:2 https://dl.bintray.com/grimler/science-packages-24 science InRelease                                                                  Ign:3 https://dl.bintray.com/xeffyr/unstable-packages unstable InRelease                                                                    Ign:4 https://dl.bintray.com/xeffyr/x11-packages x11 InRelease
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:6 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]                                                           Hit:6 https://dl.bintray.com/grimler/science-packages-24 science Release
Err:9 https://mirrors.bfsu.edu.cn/termux/termux-packages-24 stable InRelease
  Failed to connect to mirrors.bfsu.edu.cn port 443: Connection timed out
Err:10 https://mirrors.bfsu.edu.cn/termux/termux-root-packages-24 root InRelease
  Failed to connect to mirrors.bfsu.edu.cn port 443: Connection timed out
Err:11 https://dl.bintray.com/xeffyr/unstable-packages unstable Release
  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds
Get:12 https://dl.bintray.com/xeffyr/x11-packages x11 Release [6055 B]
Hit:12 https://dl.bintray.com/xeffyr/x11-packages x11 Release
Reading package lists... Done
E: The repository 'https://dl.bintray.com/xeffyr/unstable-packages unstable Release' does no longer have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
