### ISSUE TITLE
mpv media keys

### ISSUE THREAD

**Issue by atomi** [termux/termux-packages#556]
mpv is working brilliantly. it's incredible. but one feature I think would be great is to provide media keys in the drop down that send prev+next+play/pause keys to mpv from android. I personally haven't the foggiest idea if this is even possible, but it would make mpv that much more amazing. 👍

**Comment by fornwall** [comment]
Special keys are sent to programs over the terminal using an escape sequence, such as `\e[A` for the up arrow. AFAIK there is not any assigned terminal escape sequences for media keys.

We could either just come up with something, that Termux and perhaps other terminals could start to implement. Or make special keys (such as media keys) configurable in which escape sequences they send.

**Comment by atomi** [comment]
> special keys (such as media keys) configurable

That sounds great but more of a follow up feature. The more important thing is being able to play/pause, next/prev the mpv from outside termux using the slide down menu or even the lock screen.

**Comment by fornwall** [comment]
Right, it takes changes on both the terminal side (to send escape sequences for media keys) and on the receiving side (mpv to recognize and act on the escape sequences).

**Comment by atomi** [comment]
Yeah. It might be worth testing mpv in termux accepts media keys though it could it be mpsyt that catches the escape sequences in this case. On my Linux Mint workstation media keys do trigger mpsyt to play/pause etc... and mvc as well when playing a standalone file.

**Comment by atomi** [comment]
I think this is what I had in mind https://github.com/Neo-Oli/Termux-Mpv

**Comment by atomi** [comment]
@fornwall I'm closing this issue. 

https://github.com/Neo-Oli/Termux-Mpv/issues/5 Solved this. Thanks!
