### ISSUE TITLE
Error changing Repository

### ISSUE THREAD

**Issue by BJS611** [termux/termux-packages#5560]
I changed the repo but still an error occurred
Even though my connection is very stable and good
[*] Official repositories selected
    Changing main repository
[*] Running apt update
Reading package lists... Done
E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again)
E: Unable to lock directory /data/data/com.termux/files/usr/var/lib/apt/lists/

**Comment by BJS611** [comment]
Err:9 https://dl.bintray.com/xeffyr/x11-packages x11 InRelease
  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds

**Comment by Grimler91** [comment]
> E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again)

You are probably using apt in another terminal window at the same time, can't do that.

> Err:9 https://dl.bintray.com/xeffyr/x11-packages x11 InRelease
> Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds

You need to switch all repositories using bintray, since it seems that you can't access it.
