### ISSUE TITLE
Is there a way to use netstat on Android 10?

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#5563]
Is there a way to use `netstat` on Android 10?

**Problem description**
The command `netstat` does not work as expected on Android 10.

**Steps to reproduce**
Run command `netstat`:
```
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
```

**Expected behavior**
Command `netstat` runs as expected.

**Comment by xeffyr** [comment]
No way, with no root.

Android 10 has restricted access to /proc/net for privacy reasons - to prevent reading the connection list (which contains accessed domains) by untrusted applications.
