### ISSUE TITLE
Error: file size mismatch

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#5565]
I tried to install termux/package-builder with [`udocker`](https://github.com/indigo-dc/udocker/issues/152) in [Arch Linux PRoot](https://termuxarch.github.io/TermuxArch/):
```
[user07:08udocker]$ udocker pull termux/package-builder
Downloading layer: sha256:692c352adcf2821d6988021248da6b276cb738808f69dcc7bbb74a9c952146f7
Downloading layer: sha256:97058a342707e39028c2597a4306fd3b1a2ebaf5423f8e514428c73fa508960c
Downloading layer: sha256:2821b8e766f41f4f148dc2d378c41d60f3d2cbe6f03b2585dd5653c3873740ef
Downloading layer: sha256:4e643cc37772c094642f3168c56d1fcbcc9a07ecf72dbb5afdc35baf57e8bc29
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Downloading layer: sha256:53198db09ad729f0f288caa2cfdd0388d52d32008f66d72949e687d5f4ce6c1b
Downloading layer: sha256:d7897a13e2ec9887d2b6974bf0330f4dc839f762f26c6f74d5c4cc9acadc8c5e
Error: in download: curl: (28) Operation timed out after 1800000 milliseconds with 2218816619 out of 2246119365 bytes received

Error: file size mismatch: /home/user/.udocker/layers/sha256:d7897a13e2ec9887d2b6974bf0330f4dc839f762f26c6f74d5c4cc9acadc8c5e 2246119365 -1
Error: no files downloaded
```
You might want to give `udocker` a try on device. Why did it error `Operation timed out after 1800000 milliseconds with 2218816619 out of 2246119365 bytes received` at the same bite twice? 

**more info**
```
[user08:31udocker]$ udocker images
REPOSITORY
hax4us/package-builder:latest                                .
k8spatterns/curl-jq:latest
```

**Comment by xeffyr** [comment]
udocker is not supported. Use normal implementation instead. Btw, third-party project bugs are out of Termux support and not eligible for fixing.

You have network timeout, so I'll suggest you to fix your network connection.

**Comment by xeffyr** [comment]
If running under QEMU, then timeouts are *normal* - emulator is slow and SSL handshakes often expire before download will actually starts.

**Comment by SDRausty** [comment]
@xeffyr the timeout is always the same
> at the same bite

> If running under QEMU

Success is in PRoot in Termux. Vanilla Termux errors, and does not pull any images at all:
```
[08:54udocker]$ udocker pull termux/package-builder
Info: udocker command line interface 1.1.4
Info: searching for udockertools 1.1.4
Error: delete outside of directory tree:  /data/data/com.termux/files/home/github/indigo-dc/udocker
.
.
Error: in download:
Error: image not found or not authorized
Error: no files downloaded
```

What command can be used to start either of the two images that did pull with [`udocker`](https://github.com/indigo-dc/udocker/issues/152) in Termux PRoot.

**Comment by SDRausty** [comment]
> Use normal implementation instead

What is this?  I read the issues.

**Comment by xeffyr** [comment]
> If running under QEMU, then timeouts are normal - emulator is slow and SSL handshakes often expire.

It is not possible to make QEMU faster.  Slow emulation is the source of timeout and that can't be fixed. Also this is a reason why it works without QEMU.

> Use normal implementation instead

This one - https://github.com/docker/docker-ce. How you will use it, that's beyond the Termux bugtracker scope.
