### ISSUE TITLE
Services script of Transmission overrides it's configuration

### ISSUE THREAD

**Issue by dpadar** [termux/termux-packages#5571]
Transmission's script for Termux-services have following line.
```
exec transmission-daemon -f -c ~/torrent/torrent-files -w ~/torrent/download 2>&1
```
This line is overriding `download-dir` and `watch-dir` settings set in `~/.config/transmission-daemon/settings.json` (which is default configuration file for Transmission).

**Comment by Grimler91** [comment]
Thanks! I have removed the extra args in https://github.com/termux/termux-packages/commit/75c235807c4ebe62228c70c64d42bf2d91993e70 so updated package should be available in 15 minutes or so.
