### ISSUE TITLE
NodeJS 14.4 crush

### ISSUE THREAD

**Issue by nagayev** [termux/termux-packages#5577]
**Problem description**
NodeJS v 14.4.0-1 crushed.
CANNOT LINK EXECUTABLE node:
library libicui18n.so.66 not found
**Steps to reproduce**

1. Install nodejs package
2. Run it

**Expected behavior**

Working copy of nodejs
**Additional information**

Termux version 0.95

**Comment by Grimler91** [comment]
What is your output of `termux-info`?

**Comment by nagayev** [comment]
@Grimler91
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/termux-root-packages-24 root/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Tue Jul 14 03:20:58 CST 2020 aarch64 Android
Termux-packages arch:
aarch64
Android version:
10
Device manufacturer:
Xiaomi
Device model:
Mi A3

**Comment by xeffyr** [comment]
> and list of updatable packages.

So what is the list of updatable packages? Why you didn't updated the packages if there updates are available?

I can't reproduce the issue.
![Screenshot_20200722-171916_Termux](https://user-images.githubusercontent.com/25881154/88187768-9ef3b880-cc3f-11ea-8051-457859f2a834.png)

**Comment by nagayev** [comment]
my output of 
<code>apt show nodejs</code>
$ apt show nodejs
Package: nodejs
Version: 14.4.0-1
Maintainer: Termux members @termux
Installed-Size: 58.7 MB
Depends: libc++, openssl, c-ares, libicu, zlib
Suggests: clang, make, pkg-config, python
Conflicts: nodejs-lts, nodejs-current
Breaks: nodejs-dev
Replaces: nodejs-current, nodejs-dev
Homepage: https://nodejs.org/
Download-Size: 8223 kB
APT-Manual-Installed: yes
APT-Sources: https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 Packages
Description: Platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications

**Comment by nagayev** [comment]
and my list of updatable packages
<details>
<summary>long list</summary>
Updatable packages:
apt/stable 1.4.9-29 aarch64 [upgradable from: 1.4.9-16]
bash/stable 5.0.18 aarch64 [upgradable from: 5.0.11]
binutils/stable 2.34 aarch64 [upgradable from: 2.33.1]
busybox/stable 1.32.0 aarch64 [upgradable from: 1.30.1-9]
bzip2/stable 1.0.8-6 aarch64 [upgradable from: 1.0.8-5]
c-ares/stable 1.16.1-1 aarch64 [upgradable from: 1.15.0-2]
ca-certificates/stable 20200626 all [upgradable from: 20190828]
clang/stable 10.0.0-2 aarch64 [upgradable from: 9.0.1-1]
command-not-found/stable 1.55 aarch64 [upgradable from: 1.39]
coreutils/stable 8.32-2 aarch64 [upgradable from: 8.31-8]
curl/stable 7.71.1 aarch64 [upgradable from: 7.66.0]
dash/stable 0.5.11.1 aarch64 [upgradable from: 0.5.10.2-2]
diffutils/stable 3.7-3 aarch64 [upgradable from: 3.7-2]
dos2unix/stable 7.4.1-1 aarch64 [upgradable from: 7.4.0-1]
dpkg/stable 1.20.5 aarch64 [upgradable from: 1.19.7-9]
ed/stable 1.16-1 aarch64 [upgradable from: 1.15]
ffmpeg/stable 4.3.1 aarch64 [upgradable from: 4.2.1-2]
findutils/stable 4.7.0-2 aarch64 [upgradable from: 4.7.0]
fontconfig/stable 2.13.1-6 aarch64 [upgradable from: 2.13.1-4]
freetype/stable 2.10.2 aarch64 [upgradable from: 2.10.1-1]
fribidi/stable 1.0.10 aarch64 [upgradable from: 1.0.7]
game-repo/stable 1.2 all [upgradable from: 1.1]
gawk/stable 5.1.0-1 aarch64 [upgradable from: 5.0.1-4]
gdbm/stable 1.18.1-3 aarch64 [upgradable from: 1.18.1-2]
git/stable 2.27.0-3 aarch64 [upgradable from: 2.24.0]
glib/stable 2.64.4 aarch64 [upgradable from: 2.62.3]
gpgv/stable 2.2.21 aarch64 [upgradable from: 2.2.17]
grep/stable 3.4-1 aarch64 [upgradable from: 3.3-2]
gzip/stable 1.10-4 aarch64 [upgradable from: 1.10-2]
harfbuzz/stable 2.6.8-2 aarch64 [upgradable from: 2.6.4]
inetutils/stable 1.9.4-10 aarch64 [upgradable from: 1.9.4-7]
libandroid-glob/stable 0.6-2 aarch64 [upgradable from: 0.6]
libandroid-support/stable 26 aarch64 [upgradable from: 25-2]
libass/stable 0.14.0-4 aarch64 [upgradable from: 0.14.0-1]
libbz2/stable 1.0.8-6 aarch64 [upgradable from: 1.0.8-5]
libc++/stable 21d-1 aarch64 [upgradable from: 20]
libcrypt/stable 0.2-3 aarch64 [upgradable from: 0.2-2]
libcurl/stable 7.71.1 aarch64 [upgradable from: 7.66.0]
libdav1d/stable 0.4.0-1 aarch64 [upgradable from: 0.4.0]
libffi/stable 3.3-2 aarch64 [upgradable from: 3.2.1-4]
libgcrypt/stable 1.8.6 aarch64 [upgradable from: 1.8.5]
libgmp/stable 6.2.0-1 aarch64 [upgradable from: 6.1.2-4]
libgnutls/stable 3.6.14-3 aarch64 [upgradable from: 3.6.11.1]
libgpg-error/stable 1.38 aarch64 [upgradable from: 1.36-1]
libgraphite/stable 1.3.14 aarch64 [upgradable from: 1.3.13-3]
libicu/stable 66.1-2 aarch64 [upgradable from: 65.1]
libidn2/stable 2.3.0-2 aarch64 [upgradable from: 2.3.0]
libllvm/stable 10.0.0-2 aarch64 [upgradable from: 9.0.1-1]
liblzma/stable 5.2.5-1 aarch64 [upgradable from: 5.2.4-7]
libmp3lame/stable 3.100-3 aarch64 [upgradable from: 3.100-2]
libmpfr/stable 4.0.2-3 aarch64 [upgradable from: 4.0.2-2]
libnettle/stable 3.6 aarch64 [upgradable from: 3.5.1-2]
libnghttp2/stable 1.41.0-1 aarch64 [upgradable from: 1.39.2]
libogg/stable 1.3.4-1 aarch64 [upgradable from: 1.3.4]
libopus/stable 1.3.1-4 aarch64 [upgradable from: 1.3.1-3]
libpng/stable 1.6.37-3 aarch64 [upgradable from: 1.6.37-2]
libsqlite/stable 3.32.3 aarch64 [upgradable from: 3.30.0]
libunistring/stable 0.9.10-4 aarch64 [upgradable from: 0.9.10-3]
libuuid/stable 1.0.3-4 aarch64 [upgradable from: 1.0.3-3]
libvorbis/stable 1.3.7 aarch64 [upgradable from: 1.3.6-2]
libvpx/stable 1.8.2-1 aarch64 [upgradable from: 1.8.1-1]
libx265/stable 3.3 aarch64 [upgradable from: 3.2.1]
libxml2/stable 2.9.10-3 aarch64 [upgradable from: 2.9.10]
make/stable 4.3-1 aarch64 [upgradable from: 4.2.1-3]
man/stable 1.14.5-2 aarch64 [upgradable from: 1.14.5-1]
nano/stable 4.9.3-4 aarch64 [upgradable from: 4.8]
ncurses/stable 6.2.20200222-1 aarch64 [upgradable from: 6.1.20190928]
ncurses-ui-libs/stable 6.2.20200222-1 aarch64 [upgradable from: 6.1.20190928]
ndk-sysroot/stable 21d aarch64 [upgradable from: 20-7]
net-tools/stable 1.60.2017.02.21-3 aarch64 [upgradable from: 1.60.2017.02.21-2]
openssl/stable 1.1.1g-4 aarch64 [upgradable from: 1.1.1d]
pcre/stable 8.44-1 aarch64 [upgradable from: 8.43-5]
pcre2/stable 10.35-1 aarch64 [upgradable from: 10.34]
procps/stable 3.3.16-2 aarch64 [upgradable from: 3.3.15-6]
psmisc/stable 23.3-2 aarch64 [upgradable from: 23.2-1]
python/stable 3.8.3-3 aarch64 [upgradable from: 3.8.2-2]
python2/stable 2.7.18-3 aarch64 [upgradable from: 2.7.17]
readline/stable 8.0.4-1 aarch64 [upgradable from: 8.0.1]
root-repo/stable 1.6 all [upgradable from: 1.5]
science-repo/stable 1.1 all [upgradable from: 1.0]
sed/stable 4.8-1 aarch64 [upgradable from: 4.7-1]
tar/stable 1.32-6 aarch64 [upgradable from: 1.32-4]
termux-exec/stable 0.5 aarch64 [upgradable from: 0.4-1]
termux-keyring/stable 1.4 all [upgradable from: 1.2]
termux-licenses/stable 2.0-1 all [upgradable from: 1.0]
termux-tools/stable 0.84 all [upgradable from: 0.71]
unzip/stable 6.0-7 aarch64 [upgradable from: 6.0-5]
util-linux/stable 2.35.2-1 aarch64 [upgradable from: 2.34-2]
xvidcore/stable 1.3.7 aarch64 [upgradable from: 1.3.5-1]
xz-utils/stable 5.2.5-1 aarch64 [upgradable from: 5.2.4-7]
yarn/stable 1.22.4-2 all [upgradable from: 1.22.4-1]
zlib/stable 1.2.11-5 aarch64 [upgradable from: 1.2.11-4]
zsh/stable 5.8-4 aarch64 [upgradable from: 5.7.1-1]
</details>

**Comment by Grimler91** [comment]
You need to upgrade your packages. Having outdated packsges is not guaranteed to work. Node does not work because the dependency libicu is older than the one it was compiled against.

`pkg upgr`.

**Comment by nagayev** [comment]
@Grimler91 Ok, thanks.
