### ISSUE TITLE
Package Request -> libraqm

### ISSUE THREAD

**Issue by N1NG4** [termux/termux-packages#5579]
I need LibRaqm Library for my Python Project. Then I searched it on Termux then there is no lib for this so I think this should be available in termux. It is very useful for complex text rendering. Raqm depends on the following libraries: FreeType, [HarfBuzz](http://harfbuzz.org/) , [FriBiDi](http://fribidi.org/) . That are Already in the Termux-Packages. So just need to add the LibRaqm Library. This is used in many of the python libraries. So I think you should add this package in your Termux packages. Here are some useful links for You ->
 [GitHub Link](https://github.com/HOST-Oman/libraqm)
 [Docs](http://host-oman.github.io/libraqm/)

**Comment by xeffyr** [comment]
Closing as `libraqm` is already available.
```
pkg install libraqm
```
