### ISSUE TITLE
Code-Server (VSCode)

### ISSUE THREAD

**Issue by alexanderadam** [termux/termux-packages#5581]
**Link to home page and sources**
1. Home page: https://coder.com/
2. Source code: https://github.com/cdr/code-server

**Additional information**

Currently I'm using [`code-server`](https://medium.com/samsung-internet-dev/developing-on-android-phones-visual-studio-code-on-dex-4c99d2e80e91) on Termux within [an Ubuntu chroot](https://github.com/Neo-Oli/termux-ubuntu) (the idea came from @adarosecannon's [medium post](https://medium.com/samsung-internet-dev/developing-on-android-phones-visual-studio-code-on-dex-4c99d2e80e91)).

What I did was:
[Making the Ubuntu chroot](https://github.com/Neo-Oli/termux-ubuntu#termux-ubuntu) (I used [the 20.04 branch](https://github.com/Neo-Oli/termux-ubuntu/pull/125) though). And the following steps within that chroot:

```bash
$ wget https://github.com/cdr/code-server/releases/download/3.4.1/code-server-3.4.1-linux-arm64.tar.gz
$ tar -xvf ./code-server-3.4.1-linux-arm64.tar.gz
$ rm ./code-server-3.4.1-linux-arm64.tar.gz
$ mv code-server-3.4.1-linux-arm64 /lib/code-server
$ ln -s /lib/code-server/bin/code-server /bin/code-server
$ apt-get install net-tools # it also works fine without net-tools but it gives some warnings
````

It works perfectly, but I have to maintain dependencies within the Ubuntu chroot now, too.
So it would be great if it would simply be natively available as a termux package.
[The releases](https://github.com/cdr/code-server/releases) contain a packaged node version, too in case that makes any difference.

This is how it looks like:

![Screenshot of Code-Server on Samsung DeX / VSCode](https://user-images.githubusercontent.com/372620/88267976-f17db500-ccd1-11ea-9c72-acc4bfeb7e06.jpg)

**Comment by Grimler91** [comment]
You can install it directly in termux with `yarn global add code-server`, discussed in this issue: https://github.com/termux/termux-packages/issues/5416.
We generally don't provide packages for things that can be installed through other package managers so I'll close this

**Comment by Hax4us** [comment]
In termux , `yarn add code-server`

**Comment by Hax4us** [comment]
@Grimler91 oops difference of couple of seconds

**Comment by Grimler91** [comment]
@Hax4us ;)

**Comment by AdaRoseCannon** [comment]
Nice, didn't know about that here are the official instructions from code-server: 

https://github.com/cdr/code-server/blob/master/doc/install.md#yarn-npm

**Comment by ppoffice** [comment]
I just created a step-by-step tutorial for installing code-server in Termux. I'm linking it here in case someone needs it:

https://gist.github.com/ppoffice/b9e88c9fd1daf882bc0e7f31221dda01
