### ISSUE TITLE
Installing apt update  && apt upgrade 

### ISSUE THREAD

**Issue by Pawansai74** [termux/termux-packages#5584]
I'm getting more issues in the above code I can't install it in my Android. 

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by kcubeterm** [comment]
What are the issues, reboot your phone and try again.

**Comment by Pawansai74** [comment]
I'm done reboot but till now I can't receive it

Päwäñ

**Comment by kcubeterm** [comment]
@Pawansai74 we are not god , please share output what you got when you run apt update .
