### ISSUE TITLE
Luarocks bugs 

### ISSUE THREAD

**Issue by amsitlab** [termux/termux-packages#5585]
**Problem description**
Luarocks detect my device as unix not linux (android 9)

**Steps to reproduce**
When I run ```luarocks install cqueues``` luarocks give me an notice, like ```Error: This rockspec for cqueues does not support unix platforms.```

**Expected behavior**
Platform should be detected as linux and not unix, I has read from https://luarocks.org/manifests/daurnimator/cqueues-20200603.53-0.rockspec at ```supported_platforms``` table section.

**Additional information**
- luarocks config:
```accept_unknown_fields = false
arch = "unknown"
cache_fail_timeout = 86400
cache_timeout = 60
check_certificates = false
cmake_generator = "Unix Makefiles"
config_files = {
   nearest = "/data/data/com.termux/files/home/.luarocks/config-5.3.lua",
   system = {
      file = "/data/data/com.termux/files/usr/etc/luarocks/config-5.3.lua",
      found = true
   },
   user = {
      file = "/data/data/com.termux/files/home/.luarocks/config-5.3.lua",
      found = true
   }
}
connection_timeout = 30
deploy_bin_dir = "/data/data/com.termux/files/usr/bin"
deploy_lib_dir = "/data/data/com.termux/files/usr/lib/lua/5.3"
deploy_lua_dir = "/data/data/com.termux/files/usr/share/lua/5.3"
deps_mode = "one"
disabled_servers = {}
export_path_separator = ":"
external_deps_dirs = {
   "/data/data/com.termux/files/usr/local",
   "/data/data/com.termux/files/usr"
}
external_deps_patterns = {
   bin = {
      "?"
   },
   include = {
      "?.h"
   },
   lib = {
      "lib?.a",
      "lib?.so",
      "lib?.so.*"
   }
}
external_deps_subdirs = {
   bin = "bin",
   include = "include",
   lib = "lib"
}
external_lib_extension = "so"
fs_use_modules = true
gcc_rpath = true
home = "/data/data/com.termux/files/home"
home_tree = "/data/data/com.termux/files/home/.luarocks"
homeconfdir = "/data/data/com.termux/files/home/.luarocks"
hooks_enabled = true
lib_extension = "so"
lib_modules_path = "/lib/lua/5.3"
link_lua_explicitly = false
local_by_default = false
local_cache = "/data/data/com.termux/files/home/.cache/luarocks"
lua_extension = "lua"
lua_found = {
   lua_bindir = "/data/data/com.termux/files/usr/bin",
   lua_dir = "/data/data/com.termux/files/usr",
   lua_interpreter = "lua",
   lua_version = "5.3"
}
lua_interpreter = "lua"
lua_modules_path = "/share/lua/5.3"
lua_version = "5.3"
major_version = "3.1"
obj_extension = "o"
processor = "aarch64"
program_series = "3.1"
program_version = "3.1.3"
rocks_dir = "/data/data/com.termux/files/usr/lib/luarocks/rocks-5.3"
rocks_provided = {
   bit32 = "5.3-1",
   lua = "5.3-1",
   utf8 = "5.3-1"
}
rocks_provided_3_0 = {
   bit32 = "5.3-1",
   lua = "5.3-1",
   utf8 = "5.3-1"
}
rocks_servers = {
   {
      "https://luarocks.org",
      "https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/",
      "http://luafr.org/moonrocks/",
      "http://luarocks.logiceditor.com/rocks"
   }
}
rocks_subdir = "/lib/luarocks/rocks-5.3"
rocks_trees = {
   {
      name = "user",
      root = "/data/data/com.termux/files/home/.luarocks"
   },
   {
      name = "system",
      root = "/data/data/com.termux/files/usr"
   }
}
runtime_external_deps_patterns = {
   bin = {
      "?"
   },
   include = {
      "?.h"
   },
   lib = {
      "lib?.so",
      "lib?.so.*"
   }
}
runtime_external_deps_subdirs = {
   bin = "bin",
   include = "include",
   lib = "lib"
}
static_lib_extension = "a"
sysconfdir = "/data/data/com.termux/files/usr/etc/luarocks"
target_cpu = "aarch64"
upload = {
   api_version = "1",
   server = "https://luarocks.org",
   tool_version = "1.0.0"
}
user_agent = "LuaRocks/3.1.3 unknown"
variables = {
   AR = "ar",
   BUNZIP2 = "bunzip2",
   CC = "gcc",
   CFLAGS = "-O2 -fPIC",
   CHMOD = "chmod",
   CMAKE = "cmake",
   CP = "cp",
   CURL = "curl",
   CURLNOCERTFLAG = "-k",
   CVS = "cvs",
   FIND = "find",
   GIT = "git",
   GPG = "gpg",
   GUNZIP = "gunzip",
   HG = "hg",
   ICACLS = "icacls",
   LD = "gcc",
   LIBFLAG = "-shared",
   LIB_EXTENSION = "so",
   LS = "ls",
   LUA = "/data/data/com.termux/files/usr/bin/lua",
   LUALIB = "liblua.so",
   LUA_BINDIR = "/data/data/com.termux/files/usr/bin",
   LUA_DIR = "/data/data/com.termux/files/usr",
   LUA_INCDIR = "/data/data/com.termux/files/usr/include",
   LUA_LIBDIR = "/data/data/com.termux/files/usr/lib",
   LUA_LIBDIR_FILE = "liblua.so",
   MAKE = "make",
   MD5 = "md5",
   MD5SUM = "md5sum",
   MKDIR = "mkdir",
   MKTEMP = "mktemp",
   OBJ_EXTENSION = "o",
   OPENSSL = "openssl",
   PWD = "pwd",
   RANLIB = "ranlib",
   RM = "rm",
   RMDIR = "rmdir",
   ROCKS_TREE = "/data/data/com.termux/files/usr/lib/luarocks/rocks-5.3",
   RSYNC = "rsync",
   RSYNCFLAGS = "--exclude=.git -Oavz",
   SCP = "scp",
   SCRIPTS_DIR = "/data/data/com.termux/files/usr/bin",
   SEVENZ = "7z",
   SSCM = "sscm",
   SVN = "svn",
   TAR = "tar",
   TOUCH = "touch",
   UNZIP = "unzip -n",
   WGET = "wget",
   WGETNOCERTFLAG = "--no-check-certificate",
   ZIP = "zip"
}
version_check_on_fail = true
web_browser = "xdg-open"
wrapper_suffix = ""
```

-  termux-info:

```Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.18.120-perf-gfca2d6e #1 SMP PREEMPT Fri Mar 27 00:11:59 WIB 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Mi A2 Lite
```

- luarocks install cqueues:
```Installing https://luarocks.org/cqueues-20200603.53-0.src.rock
Error: This rockspec for cqueues does not support unix platforms.```

**Comment by amsitlab** [comment]
It has fix.. When I create ~/.luarocks/config-5.3.lua file and write lua code, like:

````arch = "linux-aarch64"
platforms = {
	"linux",
}```

**Comment by dauuricus** [comment]
@localhost ~/luatest> luarocks install cqueues 20200726.53-0
Installing https://luarocks.org/cqueues-20200726.53-0.src.rock

Error: This rockspec for cqueues does not support unix platforms.

amazon Fire HD 10 10th
-----
Processor       : AArch64 Processor rev 2 (aarch64)
processor       : 0
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 26.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva
idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 26.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva
idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 26.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva
idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 26.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva
idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 4
model name      : ARMv8 Processor rev 2 (v8l)
BogoMIPS        : 26.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva
idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

processor       : 5
model name      : ARMv8 Processor rev 2 (v8l)
BogoMIPS        : 26.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva
idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

processor       : 6
model name      : ARMv8 Processor rev 2 (v8l)
BogoMIPS        : 26.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva
idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

processor       : 7
model name      : ARMv8 Processor rev 2 (v8l)
BogoMIPS        : 26.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva
idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2
----
Application version:
0.108
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.146+ #1 SMP PREEMPT Sat Apr 24 02:47:03 UTC 2021 armv8l Android
Device manufacturer:
Amazon
Device model:
KFMAWI

**Comment by dauuricus** [comment]
I create ~/.luarocks/config-5.3.lua

```
arch = "linux-aarch64"
platforms = {
        "linux",
}
```

```
]> vim ~/.luarocks/config-5.3.lua
u0_a185@localhost ~/luatest> luarocks install cqueues                                                       Installing https://luarocks.org/cqueues-20200726.53-0.src.rock

Warning: unmatched variable LUA_LIBDIR
luapath: /data/data/com.termux/files/usr/tmp/luapath-: unable to generate random suffix
luapath: /data/data/com.termux/files/usr/tmp/luapath-: unable to generate random suffix
luapath: /data/data/com.termux/files/usr/tmp/luapath-: unable to generate random suffix
luapath: /data/data/com.termux/files/usr/tmp/luapath-: unable to generate random suffix
cp /data/data/com.termux/files/usr/tmp/luarocks_cqueues-20200726.53-0-2705164/cqueues-rel-20200726/config.h.guess /data/data/com.termux/files/usr/tmp/luarocks_cqueues-20200726.53-0-2705164/cqueues-rel-20200726/config.h
cp /data/data/com.termux/files/usr/tmp/luarocks_cqueues-20200726.53-0-2705164/cqueues-rel-20200726/config.h /data/data/com.termux/files/usr/tmp/luarocks_cqueues-20200726.53-0-2705164/cqueues-rel-20200726/src/config.h
luapath: /data/data/com.termux/files/usr/tmp/luapath-: unable to generate random suffix                     mkdir -p /data/data/com.termux/files/usr/tmp/luarocks_cqueues-20200726.53-0-2705164/cqueues-rel-20200726/src/5.3                                                                                                        gcc -O2 -std=gnu99 -fPIC -g -Wall -Wextra -Wno-missing-field-initializers -Wno-initializer-overrides -Wno-unused -Wno-dollar-in-identifier-extension -O2 -fPIC -DLUA_COMPAT_APIINTCASTS  -D_REENTRANT -D_THREAD_SAFE -D_GNU_SOURCE -I"/data/data/com.termux/files/usr/include" -I"/data/data/com.termux/files/usr/include" -DCOMPAT53_PREFIX=cqueues -DCQUEUES_VENDOR='"quae@daurnimator.com"' -DCQUEUES_VERSION=20200726L  -c -o /data/data/com.termux/files/usr/tmp/luarocks_cqueues-20200726.53-0-2705164/cqueues-rel-20200726/src/5.3/cqueues.o /data/data/com.termux/files/usr/tmp/luarocks_cqueues-20200726.53-0-2705164/cqueues-rel-20200726/src/cqueues.c
/data/data/com.termux/files/usr/tmp/luarocks_cqueues-20200726.53-0-2705164/cqueues-rel-20200726/src/cqueues.c:47:10: fatal error: 'lua.h' file not found
#include <lua.h>                                                                                                     ^~~~~~~
1 error generated.                                                                                          make: *** [/data/data/com.termux/files/usr/tmp/luarocks_cqueues-20200726.53-0-2705164/cqueues-rel-20200726/src/GNUmakefile:88: /data/data/com.termux/files/usr/tmp/luarocks_cqueues-20200726.53-0-2705164/cqueues-rel-20200726/src/5.3/cqueues.o] Error 1
                                                                                                            Error: Build error: Failed building.
```

**Comment by dauuricus** [comment]
termux 's luarocks & lua5.3 losts 'lua.h' or ccan't find lua.h path.

so luarocks fails when installing common https / http request modules like 'lua-requests' , 'http', deps 'lua-cjson','cqueues'...

**Comment by amsitlab** [comment]
> termux 's luarocks, lua5.3 losts 'lua.h' or can't find lua.h path.
> 
> so luarocks fails when installing common https / http request modules like 'lua-requests' , 'http', deps 'lua-cjson','cqueues'...

Try to install lualib5.3 via apt, and install lua-requests with luarocks again. because lua.h is lualib5.* package,

**Comment by dauuricus** [comment]
ok.thanks.

but i 've alredy install liblua53 ... lualib5.3 ?
 
```
u0_a185@localhost ~> apt search liblua
Sorting... Done
Full Text Search... Done
liblua52/stable 5.2.4-5 arm
  Shared library for the Lua interpreter (v5.2.x)

liblua53/stable,now 5.3.5-6 arm [installed]
  Shared library for the Lua interpreter (v5.3.x)

liblua54/stable 5.4.3 arm
  Shared library for the Lua interpreter

libluajit/stable,now 1:2.1.0-beta3-2 arm [installed,automatic]
  Just-In-Time Compiler for Lua
```

**Comment by dauuricus** [comment]
it seems to be lua.h in `$PREFIX/include/lua.5.3`

but how to pass lua.h to luarocks correctly ?

**Comment by amsitlab** [comment]
Are you have `~/.luarocks/config-5.3.lua` file ?

**Comment by amsitlab** [comment]
> @amsitlab thanks.
> 
> but i 've alredy installed liblua53 ... lualib5.3 ?
> 
> ```
> u0_a185@localhost ~> apt search liblua
> Sorting... Done
> Full Text Search... Done
> liblua52/stable 5.2.4-5 arm
>   Shared library for the Lua interpreter (v5.2.x)
> 
> liblua53/stable,now 5.3.5-6 arm [installed]
>   Shared library for the Lua interpreter (v5.3.x)
> 
> liblua54/stable 5.4.3 arm
>   Shared library for the Lua interpreter
> 
> libluajit/stable,now 1:2.1.0-beta3-2 arm [installed,automatic]
>   Just-In-Time Compiler for Lua
> ```
> 
> **how to pass liblua53's PATH to luarocks for building `cqueues` ?**
> but where liblua53 is ?
> 
> ```
> u0_a185@localhost /d/d/c/f/usr [1]> tree $PREFIX/lib/lua                                   /data/data/com.termux/files/usr/lib/lua                                                    ├── 5.2
> └── 5.3
> ├── base64.so
> ├── cjson.so
> ├── compat53
> │   ├── string.so                                                                          
> │   ├── table.so                                                                           
> │   └── utf8.so                                                                            
> ├── des56.so                                                                               
> ├── gumbo                                                                                  
> │   └── parse.so                                                                           
> ├── lcurl.so                                                                               
> ├── lfs.so                                                                                 
> ├── lsqlite3.so                                                                            
> ├── md5                                                                                    
> │   └── core.so                                                                            
> ├── mime                                                                                   
> │   └── core.so                                                                            
> ├── socket                                                                                 
> │   ├── core.so                                                                            
> │   ├── serial.so                                                                          
> │   └── unix.so                                                                            
> ├── ssl.so                                                                                 
> └── xml                                                                                        
> └── core.so
> ```
> 
> ```
> u0_a185@localhost /d/d/c/f/usr> find $PREFIX/lib/lua liblua53                              
> /data/data/com.termux/files/usr/lib/lua                                                    
> /data/data/com.termux/files/usr/lib/lua/5.2                                                
> /data/data/com.termux/files/usr/lib/lua/5.3                                                
> /data/data/com.termux/files/usr/lib/lua/5.3/gumbo                                          
> /data/data/com.termux/files/usr/lib/lua/5.3/gumbo/parse.so                                 
> /data/data/com.termux/files/usr/lib/lua/5.3/compat53                                       
> /data/data/com.termux/files/usr/lib/lua/5.3/compat53/string.so                             
> /data/data/com.termux/files/usr/lib/lua/5.3/compat53/table.so                              
> /data/data/com.termux/files/usr/lib/lua/5.3/compat53/utf8.so                               
> /data/data/com.termux/files/usr/lib/lua/5.3/lfs.so                                         
> /data/data/com.termux/files/usr/lib/lua/5.3/lcurl.so                                       
> /data/data/com.termux/files/usr/lib/lua/5.3/des56.so                                       
> /data/data/com.termux/files/usr/lib/lua/5.3/md5                                            
> /data/data/com.termux/files/usr/lib/lua/5.3/md5/core.so                                    
> /data/data/com.termux/files/usr/lib/lua/5.3/lsqlite3.so                                    
> /data/data/com.termux/files/usr/lib/lua/5.3/ssl.so                                         
> /data/data/com.termux/files/usr/lib/lua/5.3/cjson.so                                       
> /data/data/com.termux/files/usr/lib/lua/5.3/mime                                           
> /data/data/com.termux/files/usr/lib/lua/5.3/mime/core.so                                   
> /data/data/com.termux/files/usr/lib/lua/5.3/socket                                         
> /data/data/com.termux/files/usr/lib/lua/5.3/socket/serial.so                               
> /data/data/com.termux/files/usr/lib/lua/5.3/socket/core.so                                 
> /data/data/com.termux/files/usr/lib/lua/5.3/socket/unix.so                                 
> /data/data/com.termux/files/usr/lib/lua/5.3/xml                                            
> /data/data/com.termux/files/usr/lib/lua/5.3/xml/core.so                                    
> /data/data/com.termux/files/usr/lib/lua/5.3/base64.so
>                                       
> find: ‘liblua53’: No such file or directory
> ```
> 
> ```
> u0_a185@localhost /d/d/c/f/usr> find $PREFIX/include lua | grep 'lua'                      
> /data/data/com.termux/files/usr/include/llvm/Transforms/Utils/Evaluator.h                  
> /data/data/com.termux/files/usr/include/llvm/Analysis/AliasAnalysisEvalu
> ator.h             
> /data/data/com.termux/files/usr/include/lua5.3                                             
> /data/data/com.termux/files/usr/include/lua5.3/lualib.h                                    
> /data/data/com.termux/files/usr/include/lua5.3/lua.hpp                                     
> /data/data/com.termux/files/usr/include/lua5.3/lua.h                                       
> /data/data/com.termux/files/usr/include/lua5.3/lauxlib.h                                   
> /data/data/com.termux/files/usr/include/lua5.3/luaconf.h                                   
> /data/data/com.termux/files/usr/include/luajit-2.1                                         
> /data/data/com.termux/files/usr/include/luajit-2.1/lualib.h                                
> /data/data/com.termux/files/usr/include/luajit-2.1/luajit.h                                
> /data/data/com.termux/files/usr/include/luajit-2.1/lua.hpp                                 
> /data/data/com.termux/files/usr/include/luajit-2.1/lua.h                                   
> /data/data/com.termux/files/usr/include/luajit-2.1/lauxlib.h                               
> /data/data/com.termux/files/usr/include/luajit-2.1/luaconf.h                               
> /data/data/com.termux/files/usr/include/clang/AST/EvaluatedExprVisitor.h                   
> /data/data/com.termux/files/usr/include/lua5.2                                             
> /data/data/com.termux/files/usr/include/lua5.2/lualib.h                                    
> /data/data/com.termux/files/usr/include/lua5.2/lua.hpp                                     
> /data/data/com.termux/files/usr/include/lua5.2/lua.h                                       
> /data/data/com.termux/files/usr/include/lua5.2/lauxlib.h                                   
> /data/data/com.termux/files/usr/include/lua5.2/luaconf.h
> ```
> 
> ```
> u0_a185@localhost /d/d/c/f/usr> tree $PREFIX/include/ | grep 'lua'                         │   │   ├── EvaluatedExprVisitor.h                                                         
> │   │   ├── AliasAnalysisEvaluator.h                                                       
> │   │   │   ├── Evaluator.h                                                                
> ├── lua5.2                                                                                 
> │   ├── lua.h                                                                              
> │   ├── lua.hpp                                                                            
> │   ├── luaconf.h                                                                          
> │   └── lualib.h                                                                           
> ├── lua5.3                                                                                 
> │   ├── lua.h                                                                              
> │   ├── lua.hpp                                                                            
> │   ├── luaconf.h                                                                          
> │   └── lualib.h                                                                           
> ├── luajit-2.1                                                                             
> │   ├── lua.h                                                                              
> │   ├── lua.hpp                                                                            
> │   ├── luaconf.h                                                                          
> │   ├── luajit.h                                                                           
> │   └── lualib.h
> ```

Are you have `~/.luarocks/config-5.3.lua` file ?

**Comment by dauuricus** [comment]
@amsitlab

yes, config-5.3.lua is here

```
u0_a185@localhost ~/luatest> tree  ~/.luarocks                        /data/data/com.termux/files/home/.luarocks                        
├── config-5.3.lua
├── lib
│   ├── lua
```
