### ISSUE TITLE
bad interpreter due to /bin, etc. not being present

### ISSUE THREAD

**Issue by michael-ts** [termux/termux-packages#559]
I'm trying to run "configure" but get the following error:

    -bash: ./configure: /bin/sh: bad interpreter: No such file or directory

Sure enough, because /bin doesn't exist!  Instead, sh is in /data/data/com.termux/files/usr/bin/sh.
I tried passing the configure script as an argument to the full path to sh.  But then I get the error:

    configure: error: cannot run /bin/sh ./config.sub

So the script itself is trying to invoke sh directory, but again, there is no bin directory so it is failing.

This is a big problem because I'm trying to configure and build some software that I didn't write myself and therefore it isn't a good solution to try to track down every reference like this and try to fix it.  However, it seems to be pretty common to assume that /bin exists, and that /bin/sh exists.   Since this apparently isn't the case with termux, this apparently is going to break a lot of stuff.

This error also appear to affect other things, such as the assumption that /tmp exists.

**Comment by tomaklutfu** [comment]
Look at #98 .

**Comment by fornwall** [comment]
Right - the absence of standard folders like `/bin` and `/usr/bin` is one of the biggest problems with Termux.

Unfortunately there is no bullet proof way around it, but you can look at the linked issue for the `termux-chroot` solution if that works for you, or perhaps use the `termux-fix-shebang` script.
