### ISSUE TITLE
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

### ISSUE THREAD

**Issue by White151** [termux/termux-packages#5592]
How can I do for that

**Comment by xeffyr** [comment]
Update your packages.
```
pkg upgrade
```

**Comment by White151** [comment]
And then how type?

**Comment by xeffyr** [comment]
`pkg upgrade` - to upgrade Termux packages, including Python dependencies. You should do that before installing any package as there no guarantee that package you installing will properly link with dependency versions already installed.

After upgrade, use `pip` as regular, i.e. `pip install ...`.
