### ISSUE TITLE
pip install errors cmake wheel

### ISSUE THREAD

**Issue by haareks** [termux/termux-packages#5594]
hello,

I try to install software with pip and get compiling issues.

CMake Error at /data/data/com.termux/files/usr/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):   The C++ compiler  "/data/data/com.termux/files/usr/bin/c++"    is not able to compile a simple test program.                                                                                                                 It fails with the following output:                                                                                                                             Change Dir: /data/data/com.termux/files/usr/tmp/pip-wheel-u_qsstl6/cmake/_skbuild/linux-armv8l-3.8/cmake-build/CMakeProject-build/CMakeFiles/CMakeTmp
...
An error occurred while building with CMake.

I installed cmake with pkg install cmake - still the same error.
then i installed cmake with pip install cmake without any luck.

any ideas how tp proceed?

thanks, help appreciated

**Comment by xeffyr** [comment]
Closing due to lack of information. Submitted piece of log says nothing about the issue cause.
