### ISSUE TITLE
nginx with root makes no access to localhost servers

### ISSUE THREAD

**Issue by bensh4** [termux/termux-packages#5598]
nginx with port > 1024 is working fine. I bind nginx to port 80 since I've root. Verified port status after running nginx at port 80. Seems listen success on port 80 by nginx. But, it will throw _403 Forbidden_
Changed /usr/nginix permission to 777 and /usr/share/ngnix to 777 with `chmod -R nginx` . Still it's _403 forbidden_ 

`ps aux | grep nginx` says nginx worker owned by nobody. (Screenshot attached). In short; while using port 80, it's 403 and with ports <1024 it's working. 
![IMG_20200726_221427_333.jpg](https://user-images.githubusercontent.com/22962287/88484660-caeba280-cf8d-11ea-9c6c-137eceecf580.jpg)

Since it's a Termux specific issue, I cannot report in nginx. I believe it's related with permission. A look at /var/log/nginx says; 

` error] 23422#23422: *4 " /usr/share/nginx/html/index.html" is forbidden (13: Permission denied), client: 2  `

**Comment by xeffyr** [comment]
I see nginx has dropped privileges to "nobody" user, this can be an answer why it has permission denied. Also do not forget that Android uses SELinux for access permission control and messing up with root leads to unexpected behavior.

`setenforce 0`, verify that files have `o+rw` access mode and try again.

**Comment by xeffyr** [comment]
Update:
Whole path must be readable by "nobody" user. So, you can't host files in $PREFIX or $HOME because `/data` is not readable.

**Comment by bensh4** [comment]
> Update:
> Whole path must be readable by "nobody" user. So, you can't host files in $PREFIX or $HOME because `/data` is not readable.
> 
> Using `user root;` fixes the problem too.

I think there's a misunderstanding. So, nginx cannot access files in /data ( $HOME or $PREFIX ) unless `setenforce 0` is set. Is that you mean? 
Thanks!

**Comment by xeffyr** [comment]
> So, nginx cannot access files in /data ( $HOME or $PREFIX ) unless setenforce 0 is set.

There multiple issues happening at the same time:
1. SELinux.
2. Nginx requires that each path component is accessible.

So even if No 1 is solved (`setenforce 0`), you have a second one which cannot be solved without breaking system access permissions. That's what I mean.

> And what you mean by saying; "Using user root; fixes the problem"
nginx is run by root.

Nope. It is being started with root to bind 80 port. Rest of time it is being run as user `nobody`. See the `$PREFIX/etc/nginx/nginx.conf` file.

Edit nginx.conf and replace `user nobody;` with `user root;`.

**Comment by xeffyr** [comment]
> As I mentioned, permission is 777

That doesn't matter as soon as /data, /data/data, /data/data/com.termux, /data/data/com.termux/files, and whole $PREFIX are not 777.

**Comment by xeffyr** [comment]
Running nginx as root is generally not supported in Termux. Termux is designed to be single-user only.

Want to have Nginx on port 80 - setup `iptables` rule for redirecting connections from port 80 to 8080 and there won't be any permission issues.

**Comment by bensh4** [comment]
> Running nginx as root is generally not supported in Termux. Termux is designed to be single-user only.
> 
> Want to have Nginx on port 80 - setup `iptables` rule for redirecting connections from port 80 to 8080 and there won't be any permission issues.

For Disabling SE, SE binaries are not installed BusyBox or its Pro version. And evenif I change user `nobody` to `root` in nginx config, it wouldn't remove the permission problem I believe🤔 . Since I've Ip6tables binary installed, I'll give a try with it. 
Thanks @xeffyr

**Comment by bensh4** [comment]
Update: A simple change in config `user root` fixed the permission issue. Ip6tables are also helpful. Anyways thanks @xeffyr
