### ISSUE TITLE
Error due to gcc symlink

### ISSUE THREAD

**Issue by Exaeta** [termux/termux-packages#560]
This build breaks ```./configure``` scripts that test for gcc but break when clang provides the gcc alias.

Remove the gcc symlink, **this is a bug**. Clang is **not** GCC and it is **not** compatible with GCC.

**Comment by fornwall** [comment]
Removing the gcc symlink would probably cause more problems (scripts assuming that gcc exists) than it would solve.

Note that Apple does the same thing (`gcc -> clang` symlink) on OS X/macOS, so portably configure scripts shouldn't assume that a `gcc` program really is gcc anyway, but need to invoke the C compiler to identify it.
