### ISSUE TITLE
Can neither run cargo nor rustc after installing rust package

### ISSUE THREAD

**Issue by raw-bacon** [termux/termux-packages#5603]
**Problem description**
On my FairPhone 3, when I run `pkg install rust`, I can download and install Rust, but upon running `cargo` or `rustc`, I get false feedback claiming that `The program rustc is not installed. Install it by executing: pkg install rust`. Other packages, e.g., `git`, work fine.

**Expected behavior**
Answer starting with `Usage: rustc [OPTIONS] INPUT` upon entering `rustc`, or `Rust's package manager` for `cargo`.

**Comment by kcubeterm** [comment]
It's work fine, I think you didn't Install it properly, install again

**Comment by raw-bacon** [comment]
I did multiple times; no luck so far. Also ran `pkg upgrade`, reinstalled Termux, uninstalled and reinstalled Rust, rebooted phone, and some permutations of the above steps. May have something to do with the Fairphone ...

**Comment by its-pointless** [comment]
Its currently building and should be fixed shortly

**Comment by raw-bacon** [comment]
#5604 fixed it.
