### ISSUE TITLE
Tap in mc doesn't work after packages update

### ISSUE THREAD

**Issue by jfriesse** [termux/termux-packages#5606]
**Problem description**
I've updated packages today (2020-07-28) and found it that taping in mc (midnight commander) no longer works as before. Before, it was possible to tap on mc interface and that was handled by mc nicely (like you could click to bottom bar to run function which are normally accessible by F1-F10 keys, click on file to move file selector on that file, ...). So basically mouse emulation was working, now it is not.

**Steps to reproduce**
* `pkg upgrade` - stable repo as of 2020-07-28
* `mc`
* tap somewhere
* Escape codes like `1;8M1;8m`, `5;17M5;17m` appears in command line
* pressing F1-F10 keys on keyboard (Hacker's keyboard) works as expected

**Expected behavior**
As at the beginning of 2020 (sadly I haven't updated for quite a long time, so beginning of 2020 is really rough estimation) - it is possible to tap in mc and it behaves like clicking by mouse.

**Additional information**
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf-gdbc2759-dirty #1 SMP PREEMPT Wed Oct 9 15:40:05 CST 2019 aarch64 Android
Device manufacturer:
LENOVO
Device model:
Lenovo TB-8704F
```

**Comment by xeffyr** [comment]
This is fixed now.
