### ISSUE TITLE
busybox vi Segmentation fault

### ISSUE THREAD

**Issue by T4Tea** [termux/termux-packages#5611]
**Problem description**

Return "Segmentation fault" when using ```busybox vi```.

**Additional information**

termux-info
```
deb https://termux.org/packages/ stable main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.112-perf+ #1 SMP PREEMPT Wed Jun 17 15:33:54 CST 2020 aarch64 Android
Device manufacturer:
nubia
Device model:
NX616J
```

**Comment by T4Tea** [comment]
busybox version: 
busybox/stable,now 1.32.0 aarch64 [installed]

**Comment by its-pointless** [comment]
looks to be the same issue that caused 0001-clang-fix.patch to be needed since adding `#pragma clang optimize off` to vi.c fixes it....
