### ISSUE TITLE
Unable to install packages and update && upgrade

### ISSUE THREAD

**Issue by BJS611** [termux/termux-packages#5617]
pkg upgrade
Reading package lists... Done
E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again)
E: Unable to lock directory /data/data/com.termux/files/usr/var/lib/apt/lists/
![Screenshot_2020-07-30-20-09-31-57_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/65802479/88926756-a3a01880-d2a0-11ea-9cd5-b5280f2ad04e.png)

**Comment by landfillbaby** [comment]
it says at the top that you have a suspended `pkg upgrade  -y` on job number 5, so that's most likely what's holding the lock. just do `fg 5`

**Comment by xeffyr** [comment]
Yes, it seems you have accidentally pressed `CTRL+Z` key combination during the package installation.

***

Closing as this is not a Termux issue.
