### ISSUE TITLE
[INFO] Main repository traffic quota is nearly exhausted

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-packages#5620]
~~Main repository has used 99% of the available monthly bandwidth (as of `31.07 22:20:06 UTC`) which is 64 terabytes and may get suspended by Bintray. Once that happen, you will observe HTTP 403 error when downloading from https://dl.bintray.com/termux/termux-packages-24/.~~

Consider use of mirrors, see the available at https://github.com/termux/termux-packages/wiki/Mirrors. Edit your `$PREFIX/etc/apt/sources.list` or use utility `termux-change-repo`.

~~Luckily traffic counter should be reset tomorrow.~~ *fixed temporarily*

***

Following measures were enabled to reduce load on Bintray repository:
* Automatic mirror selection when using `pkg`.
* CI caching of dependency deb files.
* Caching of downloaded deb files in Termux.

**Comment by buttaface** [comment]
Man, there has to be some way to raise money for this. Do you have stats on how much of that traffic is used by the top 10% of users? For example, I bet the CI is using the biggest chunk, maybe github actions can be set up with a Termux package archive, rather than downloading packages on each CI run?

For users, maybe `pkg` can keep a bandwidth count and show them a message to donate once they hit a certain high usage threshold. I've donated to @fornwall before, I'm sure others would too.

**Comment by kcubeterm** [comment]
> For example, I bet the CI is using the biggest chunk, 

Can GitHub actions cache help to save bandthwith 
https://github.com/actions/cache

**Comment by xeffyr** [comment]
> Do you have stats on how much of that traffic is used by the top 10% of users?

I'm in doubt that it is more than 100 - 300 GB max. Worldwide amount of downloads doubled in past few months.

I have only global stats but not specific for CI, yet it can be calculated if we know the IP addresses of CI VMs.

We can try to use Github Actions cache, but it won't help too much.

> For users, maybe pkg can keep a bandwidth count and show them a message to donate once they hit a certain high usage threshold.

For users, we can do these things:
* Automatically random mirror on the first `pkg` run.
* Use a local package cache.

**Comment by kcubeterm** [comment]
> We can try to use Github Actions cache, but it won't help too much.


Yea, but it can save workflows hr and time  atleast

> Automatically select random mirror on the first pkg run.

This would be nice.

**Comment by xeffyr** [comment]
> Yea, but it can save workflows hr and time atleast

Will save 1 min max. Network speed is about 1 GBps and most of packages do not have too much dependencies.

Most of time for small packages is spent on these 2 things:
* Freeing additional space by uninstalling utilities that are not needed - we need about 27 - 30 GB free in the CI VM.
* Downloading Docker image.

**Comment by buttaface** [comment]
>I'm in doubt that it is more than 100 - 300 GB max

Heh, this is impossible. :smile: If every user had an exact equal share of that 64 TB, then the top 10% of users would be using 6.4 TB. That is the floor, so we know mathematically it has to be more than that, since there's no way it's that equal.

If the mirrors were randomized, the odds of choosing a mirror should be based on the size of each mirror's traffic quota. Do you have those numbers?

**Comment by xeffyr** [comment]
> Heh, this is impossible.

See stats below:
![Снимок экрана от 2020-07-31 11-12-30](https://user-images.githubusercontent.com/25881154/89015061-25368b80-d31f-11ea-80bc-1ce7cd3c6584.png)

We have sudden increase of downloads which is pretty stable last days. That's definitely not CI.

> then the top 10% of users would be using 6.4 TB

India + Indonesia countries use 50% of all available bandwidth... lol

Also, average user reinstall Termux 2-4 times per day, according to my mirror's log.

> If the mirrors were randomized, the odds of choosing a mirror should be based on the size of each mirror's traffic quota.

That's generally unknown but here is some info about mirrors:
* `https://grimler.se/termux-packages-24` - IP belongs to https://misshosting.com/ but that hosting provides 5 TB bandwidth at max VPS price. Correct information is known only to @Grimler91.
* `https://main.termux-mirror.ml` - unmetered traffic, limited only by 100 Mbps link, which can be improved by use of CloudFlare which I have disabled currently.

**Comment by xeffyr** [comment]
To use a lot of traffic by CI (e.g. 8 TB), you have to download **whole** repository >1000 times.

**Comment by buttaface** [comment]
>We have sudden increase of downloads which is pretty stable last days

Wow, that's a giant jump in requests from July 6th, any idea why? A lot more installs of the Termux app that week? Any increase in hits to termux.com that would explain why? It looks like 64 TBs will not be enough in August.

>India + Indonesia countries use 50% of all available bandwidth

That is great to hear that Termux is being used so much in developing markets, as I've always felt that is a natural userbase for this app, but wasn't sure if they were aware of it.

>average user reinstall Termux 2-4 times per day

Wouldn't a reinstall only get the app and bootstrap packages from the Play Store so it doesn't affect this mirror bandwidth? Or are you just pointing out that you're detecting this weird installation behavior, even though it has nothing to do with using mirror bandwidth?  Why do you think they're reinstalling so much?

>Here is some info about mirrors

Has anybody from the Termux team reached out to other CDNs like CloudFlare to see if they'd sponsor more traffic? I can try doing that if you want.

>limited only by 100 Mbps link

That's a maximum monthly quota of 30 TBs per month if everybody spaced out their downloads perfectly and the host wasn't oversubscribing the network link, so probably more like 10% of that, or 3 TBs.

>To use a lot of traffic by CI (e.g. 8 TB), you have to download whole repository >1000 times

Still, I bet it is the largest single user of package download bandwidth, so we should use that CI caching scheme at some point.

**Comment by xeffyr** [comment]
> Wouldn't a reinstall only get the app and bootstrap packages from the Play Store so it doesn't affect this mirror bandwidth?

No, with in-APK bootstraps they do not affect our bandwidth at all.

> Or are you just pointing out that you're detecting this weird installation behavior, even though it has nothing to do with using mirror bandwidth?

That's all packages re-installations. Many users use Termux for running random scripts from the Internet, as result they either mess up their Termux or just find that script is not working. They are `rm -rf $PREFIX` or re-install the application and trying again. I saw exactly same downloaded package sets within same IPs.

Another case is that you may want to have clean Termux after testing some things - I have re-installed it 2 times last week due to this case. However I use custom bootstraps and this doesn't affect bandwidth too much.

> so we should use that CI caching scheme at some point.

Yes, I will look at configuring it.

**Comment by Grimler91** [comment]
> Wow, that's a giant jump in requests from July 6th, any idea why?

July 7th was when we [bumped lots of packages](https://github.com/termux/termux-packages/commit/d9fc030c877a84590c493173190c820d2483c727) to fix license problem, so that particular peak us probably due to that

**Comment by buttaface** [comment]
>They are rm -rf $PREFIX or re-install the application and trying again. I saw exactly same downloaded package sets within same IPs.

Hmm, we should use a local package cache in Termux then, preferably outside `$PREFIX`. I was surprised to find a while back that Termux doesn't cache the installed packages' .deb files locally, like Ubuntu does, though it makes sense given smaller phone storage years back. However, I now have 100+ GBs in my phone, so we could probably add that back and have users `autoclean` if they want that package cache wiped, plus maybe don't setup the cache if the device has less than 8-16GBs of storage?

I can look into adding that if you want.

**Comment by buttaface** [comment]
>so that particular peak us probably due to that

@Grimler91, no way, there has been a sustained doubling of requests for a month now: there's no chance that's because of that licensing change.

**Comment by xeffyr** [comment]
> we should use a local package cache in Termux then, preferably outside $PREFIX.

Yes, I'm thinking about using application cache directory for that, so it can be easily cleaned not just by `rm` but with Android settings or some "cleaner" applications.

> I was surprised to find a while back that Termux doesn't cache the installed packages' .deb files locally

That setup is kept from the time when Termux was used on low-end devices with Android 5 to have more free space.

> maybe don't setup the cache if the device has less than 8-16GBs of storage?

Need reliable way for checking available storage. Or just use `df` with a fallback with cache setup being disabled.

**Comment by buttaface** [comment]
Looks like I was partially wrong about the package cache, I see 23 out of my 116 installed packages are saved as .deb files in $PREFIX/var/cache/apt/archives. I wonder if `autoclean`, which I have run a couple times, only removes packages with outdated versions or even installed packages after some time limit. Looks like the cache location will just have to be moved and follow the rules we set for it, requiring patching dpkg?

**Comment by xeffyr** [comment]
@buttaface They get deleted once installed properly. This directory is always empty for me.

APT needs `APT::Keep-Downloaded-Packages="true"` option in order to keep downloaded debfiles.

**Comment by buttaface** [comment]
Alright, I'll look into patching apt to do what we want. Btw, I notice that the apt source version hasn't been updated in three years now, the source link doesn't work for me.

**Comment by buttaface** [comment]
I've put up #5625 with the patched `apt`, will update that pull with some `pkg` changes too. In the meantime, anyone can give me feedback on the `apt` changes.

**Comment by xeffyr** [comment]
Closing as Bintray quota is restored.

**Comment by buttaface** [comment]
How's the bintray traffic looking almost a third of the way through this month, not coming close to the quota again? The good news is that this is the most we'll ever need outside mirrors, since the Play Store will soon require installing all packages from there.

**Comment by xeffyr** [comment]
Yes, current traffic was reduced by ~1/3 but seems going to be reduced even more.
