### ISSUE TITLE
udocker issues with termux dockerimage .

### ISSUE THREAD

**Issue by kcubeterm** [termux/termux-packages#5631]
Sorry : maybe off-topic, 

I am able to run other dockerimage with udocker like kali, ubuntu etc, but can't run termux image(xeffyr/termux:latest)

```
$ ./udocker run --user=1000:1001  mytermux
Warning: non-existing user will be created
Error: command not found or has no execute bit set:  [u'/system/bin/sh', u'-c', u'/data/data/com.termux/files/usr/bin/login']

```
I want termux image because I want to host a application on heroku and that's can't possible without termux image or something similar to termux environment

**Comment by xeffyr** [comment]
My docker image supports only x86 CPUs.
