### ISSUE TITLE
wget hash sum mismatch

### ISSUE THREAD

**Issue by Keith-S-Thompson** [termux/termux-packages#5632]
**Problem description**
`pkg install wget` fails with a `Hash Sum Mismatch` error

**Steps to reproduce**
```
pkg install wget
```

**Expected behavior**
The `wget` package should be installed.

**Cause**
`https://termux.mentality.rip/termux-packages-24/arm/wget_1.20.3-2_arm.deb` is empty.

Several other `*.deb` files in that same directory are also empty:
```
aapt_7.1.2.33-10_arm.deb
apt-ftparchive_1.4.9-29_arm.deb
apt_1.4.9-29_arm.deb
command-not-found_1.55_arm.deb
ldc_1.22.0-3_arm.deb
wget_1.20.3-2_arm.deb
```

**Additional information**

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf-ge30d5c4 #1 SMP PREEMPT Tue Feb 5 04:51:33 CST 2019 armv7l Android
Device manufacturer:
motorola
Device model:
Moto G (5) Plus
```

**Output of `pkg install wget`:**
```
Checking availability of current mirror: ok                                                                                                        
Reading package lists... Done                                                                                                                      
Building dependency tree                                                                                                                           
Reading state information... Done                                                                                                                  
The following NEW packages will be installed:                                                                                                      
  wget                                                                                                                                             
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.                                                                                     
Need to get 206 kB of archives.                                                                                                                    
After this operation, 430 kB of additional disk space will be used.                                                                                
Err:1 https://termux.mentality.rip/termux-packages-24 stable/main arm wget arm 1.20.3-2                                                            
  Hash Sum mismatch                                                                                                                                
  Hashes of expected file:                                                                                                                         
   - SHA256:9fcb39a544028cac5acca72cdceafddaaaf9a2ef86e7921647d368a3f777140f                                                                       
   - SHA1:35070bc0badb1e18dafbd1f82b0dd249ac17bca2 [weak]                                                                                          
   - Filesize:205510 [weak]                                                                                                                        
  Hashes of received file:                                                                                                                         
   - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855                                                                       
   - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]                                                                                          
   - Filesize:0 [weak]                                                                                                                             
  Last modification reported: Sun, 19 Apr 2020 18:21:55 +0000                                                                                      
E: Failed to fetch https://termux.mentality.rip/termux-packages-24/arm/wget_1.20.3-2_arm.deb  Hash Sum mismatch                                    
   Hashes of expected file:                                                                                                                        
    - SHA256:9fcb39a544028cac5acca72cdceafddaaaf9a2ef86e7921647d368a3f777140f                                                                      
    - SHA1:35070bc0badb1e18dafbd1f82b0dd249ac17bca2 [weak]                                                                                         
    - Filesize:205510 [weak]                                                                                                                       
   Hashes of received file:                                                                                                                        
    - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855                                                                      
    - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]                                                                                         
    - Filesize:0 [weak]
   Last modification reported: Sun, 19 Apr 2020 18:21:55 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by buttaface** [comment]
We recently had some problems with hitting the traffic quota on the main package host, so we had the `pkg` script use mirrors too, but it looks like this mirror has some problems. The good news is that the hash is stopping bad packages from getting installed, the bad news is that one of the approved mirrors is putting out such empty files.

As a workaround, you could try editing the file `~/../usr/etc/apt/sources.list` to change the mirror URL there to `https://dl.bintray.com/termux/termux-packages-24`, then run `TERMUX_PKG_NO_MIRROR_SELECT=true pkg install wget`. Let me know if that fixes it for you.

**Comment by Keith-S-Thompson** [comment]
OK, this is odd. I just tried `pkg install wget` *without* first updating `sources.list`, and it worked.

My `sources.list` file was updated about 2 hours ago, and looks like this:
```
deb https://main.termux-mirror.ml/ stable main
```

I didn't (deliberately) modify it.

**Comment by buttaface** [comment]
Yes, that makes sense: [we rotate the mirrors that your `pkg` script tries every couple hours based on availability and other measures](https://github.com/termux/termux-packages/blob/master/packages/termux-tools/pkg#L62), so it looks like you were properly rotated out. :smile:

I will leave this bug report open till we get our mirrors fixed, thanks for reporting.

**Comment by xeffyr** [comment]
Looks like server was rebooted during mirror sync or mirroring software was interrupted in a different way.

There few other zero-length packages on https://termux.mentality.rip/termux-packages-24/.

We can just bump affected packages and they will be redownloaded by mirrors.

**Comment by xeffyr** [comment]
> As a workaround, you could try editing the file ~/../usr/etc/apt/sources.list

We have script `termux-change-repo`, so no need to edit files manually. `TERMUX_PKG_NO_MIRROR_SELECT=true` is still needed to prevent mirror change, if selected manually.

**Comment by xeffyr** [comment]
I'm closing this as bumped packages are available at https://termux.mentality.rip/termux-packages-24/. However old empty files are still available as no automatic cleanup seems performed.

**Comment by Grimler91** [comment]
I have the same problem with my mirror (where I use ftpsync). 

I wrote an [ugly python script](https://gitlab.com/Grimler/dotfiles/-/blob/dd00dce43a2b9bced507c5c795e653e3235f867b/dot_local/bin/executable_check-deb-hashes.py) to compare the hashes of the debs with the hash in the Packages files and delete debs that don't match. 

So far I have just been running it every now and then, but I should perhaps setup a timer to run it every 6 hours or something (just need to make sure it is not run at the same time as the mirror update script)

**Comment by ako123456** [comment]
> **Problem description**
> `pkg install wget` fails with a `Hash Sum Mismatch` error
> 
> **Steps to reproduce**
> 
> ```
> pkg install wget
> ```
> 
> **Expected behavior**
> The `wget` package should be installed.
> 
> **Cause**
> `https://termux.mentality.rip/termux-packages-24/arm/wget_1.20.3-2_arm.deb` is empty.
> 
> Several other `*.deb` files in that same directory are also empty:
> 
> ```
> aapt_7.1.2.33-10_arm.deb
> apt-ftparchive_1.4.9-29_arm.deb
> apt_1.4.9-29_arm.deb
> command-not-found_1.55_arm.deb
> ldc_1.22.0-3_arm.deb
> wget_1.20.3-2_arm.deb
> ```
> 
> **Additional information**
> 
> ```
> Packages CPU architecture:
> arm
> Subscribed repositories:
> # sources.list
> deb https://termux.mentality.rip/termux-packages-24/ stable main
> # game-repo (sources.list.d/game.list)
> deb https://dl.bintray.com/grimler/game-packages-24 games stable
> # science-repo (sources.list.d/science.list)
> deb https://dl.bintray.com/grimler/science-packages-24 science stable
> Updatable packages:
> All packages up to date
> Android version:
> 8.1.0
> Kernel build information:
> Linux localhost 3.18.71-perf-ge30d5c4 #1 SMP PREEMPT Tue Feb 5 04:51:33 CST 2019 armv7l Android
> Device manufacturer:
> motorola
> Device model:
> Moto G (5) Plus
> ```
> 
> **Output of `pkg install wget`:**
> 
> ```
> Checking availability of current mirror: ok                                                                                                        
> Reading package lists... Done                                                                                                                      
> Building dependency tree                                                                                                                           
> Reading state information... Done                                                                                                                  
> The following NEW packages will be installed:                                                                                                      
>   wget                                                                                                                                             
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.                                                                                     
> Need to get 206 kB of archives.                                                                                                                    
> After this operation, 430 kB of additional disk space will be used.                                                                                
> Err:1 https://termux.mentality.rip/termux-packages-24 stable/main arm wget arm 1.20.3-2                                                            
>   Hash Sum mismatch                                                                                                                                
>   Hashes of expected file:                                                                                                                         
>    - SHA256:9fcb39a544028cac5acca72cdceafddaaaf9a2ef86e7921647d368a3f777140f                                                                       
>    - SHA1:35070bc0badb1e18dafbd1f82b0dd249ac17bca2 [weak]                                                                                          
>    - Filesize:205510 [weak]                                                                                                                        
>   Hashes of received file:                                                                                                                         
>    - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855                                                                       
>    - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]                                                                                          
>    - Filesize:0 [weak]                                                                                                                             
>   Last modification reported: Sun, 19 Apr 2020 18:21:55 +0000                                                                                      
> E: Failed to fetch https://termux.mentality.rip/termux-packages-24/arm/wget_1.20.3-2_arm.deb  Hash Sum mismatch                                    
>    Hashes of expected file:                                                                                                                        
>     - SHA256:9fcb39a544028cac5acca72cdceafddaaaf9a2ef86e7921647d368a3f777140f                                                                      
>     - SHA1:35070bc0badb1e18dafbd1f82b0dd249ac17bca2 [weak]                                                                                         
>     - Filesize:205510 [weak]                                                                                                                       
>    Hashes of received file:                                                                                                                        
>     - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855                                                                      
>     - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]                                                                                         
>     - Filesize:0 [weak]
>    Last modification reported: Sun, 19 Apr 2020 18:21:55 +0000
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```

snapchat.com/Newpassword/delan.kh

**Comment by ako123456** [comment]
help
