### ISSUE TITLE
[QUESTION] Using port 80/443 on Apache in Termux, will the package run as root ?

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-packages#5643]
I use the webserver in Termux as well, with Apache, PHP and MySQL, successfully, it works flawlessly.
I use port 8080 (and 8443) to prevent running Apache and PHP as root (I am rooted, but do not have root enabled in Termux).

When I use the 'low' ports 80 and 443, restart Apache, then Magisk will probably trip and prompt and when I consent, will Apache and PHP then run as root ? In that case, it is insecure, which I don't want. Or will it still (and Termux itself) run as 'Termux user (u_aXXXX)' ?

Before I try out I want to know experiences (if any) from others.

**Comment by freebrowser1** [comment]
Thanks, I read the other topics.

> Pretty sure it will run as the user you have specified in the config file.
So I have to add 

User u0_a250
Group u0_a250

and Listen 80  (instead of 8080)

in httpd.conf ?

I notice from these topics that Apache will only *start* as root to bind port 80 and then run as Termux user (which I hope) ?
On other platforms (macOS and Linux) it works that way, uses the Apache user but runs on port 80.

**Comment by xeffyr** [comment]
Confirming that
```
<IfModule unixd_module>
User u0_aX
Group u0_aX
</IfModule>
```
working.
