### ISSUE TITLE
Unable to install pandas

### ISSUE THREAD

**Issue by abhi5794** [termux/termux-packages#5648]
**Problem description**
When I try to install yfinance using pip, the pandas installation dumps with the below error. This has kept me up for a week.
Any help would be greatly appreciated. I have done nearly 10 clean installs. I have tried installing the numpy from its-pointless, then pip installing pandas after running setupgcc-9. Also, I was able to find the Python.h, when I ran a search. Running

`SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.`
link to the complete error : https://gist.github.com/abhi5794/728e16393a25b20837bca81fc5d2f734 

Below is the pkg list

Listing... Done
apt/stable,now 1.4.10-2 aarch64 [installed]
bash/stable,now 5.0.18 aarch64 [installed]
binutils/stable,now 2.35 aarch64 [installed,automatic]
bzip2/stable,now 1.0.8-6 aarch64 [installed]
ca-certificates/stable,now 20200722 all [installed]
clang/stable,now 10.0.1-1 aarch64 [installed]
command-not-found/stable,now 1.55-1 aarch64 [installed]
coreutils/stable,now 8.32-2 aarch64 [installed]
curl/stable,now 7.71.1 aarch64 [installed]
dash/stable,now 0.5.11.1 aarch64 [installed]
debianutils/stable,now 4.11-1 aarch64 [installed]
dialog/stable,now 1.3-20200327-0 aarch64 [installed]
diffutils/stable,now 3.7-3 aarch64 [installed]
dos2unix/stable,now 7.4.1-1 aarch64 [installed]
dpkg/stable,now 1.20.5 aarch64 [installed]
ed/stable,now 1.16-1 aarch64 [installed]
fftw/stable,now 3.3.8-2 aarch64 [installed]
findutils/stable,now 4.7.0-2 aarch64 [installed]
freetype/stable,now 2.10.2 aarch64 [installed]
libpng/stable,now 1.6.37-3 aarch64 [installed]
libsodium/stable,now 1.0.18-2 aarch64 [installed,automatic]
libsqlite/stable,now 3.32.3 aarch64 [installed,automatic]
libssh2/stable,now 1.9.0-2 aarch64 [installed]
libtirpc/stable,now 1.2.6-1 aarch64 [installed]
libunistring/stable,now 0.9.10-4 aarch64 [installed,automatic]
libxml2/stable,now 2.9.10-3 aarch64 [installed]
libxslt/stable,now 1.1.34-1 aarch64 [installed]
libzmq/stable,now 4.3.2-2 aarch64 [installed]
lsof/stable,now 4.93.2 aarch64 [installed]
make/stable,now 4.3-1 aarch64 [installed,automatic]
nano/stable,now 5.0 aarch64 [installed]
ncurses/stable,now 6.2.20200725 aarch64 [installed]
ncurses-ui-libs/stable,now 6.2.20200725 aarch64 [installed,automatic]
ndk-sysroot/stable,now 21d aarch64 [installed,automatic]
net-tools/stable,now 1.60.2017.02.21-3 aarch64 [installed]
openssl/stable,now 1.1.1g-4 aarch64 [installed]
patch/stable,now 2.7.6-3 aarch64 [installed]
pcre/stable,now 8.44-1 aarch64 [installed]
pinentry/stable,now 1.1.0-4 aarch64 [installed,automatic]
pkg-config/stable,now 0.29.2 aarch64 [installed]
procps/stable,now 3.3.16-2 aarch64 [installed]
psmisc/stable,now 23.3-2 aarch64 [installed]
python/stable,now 3.8.5 aarch64 [installed]
readline/stable,now 8.0.4-1 aarch64 [installed]
resolv-conf/stable,now 1.2-1 aarch64 [installed,automatic]
science-repo/stable,now 1.1 all [installed]
sed/stable,now 4.8-1 aarch64 [installed]
setup-scripts/termux,now 2.7.0 all [installed,automatic]
tar/stable,now 1.32-6 aarch64 [installed]
termux-am/stable,now 0.3 all [installed]
termux-exec/stable,now 0.5 aarch64 [installed]
termux-keyring/stable,now 1.4 all [installed]
termux-licenses/stable,now 2.0-1 all [installed]
termux-tools/stable,now 0.93 all [installed]
unzip/stable,now 6.0-7 aarch64 [installed]
util-linux/stable,now 2.35.2-1 aarch64 [installed]
xz-utils/stable,now 5.2.5-1 aarch64 [installed]
zlib/stable,now 1.2.11-5 aarch64 [installed]

pip list 
`Package         Version                                 --------------- -------                                 dateutils       0.6.8                                   lxml            4.5.2
nsetools        1.0.11                                  pip             20.2.1                                  python-dateutil 2.8.1                                   pytz            2020.1                                  setuptools      47.1.0                                  six             1.15.0                                  wheel           0.34.2
`

termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
sources.list
deb https://termux.org/packages/ stable main
game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Fri Nov 8 00:25:05 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 5 Pro

```

```

**Comment by Grimler91** [comment]
You need to show us the full error output, not just the two last lines

**Comment by abhi5794** [comment]
The verbose version is in the link https://gist.github.com/abhi5794/728e16393a25b20837bca81fc5d2f734

**Comment by Grimler91** [comment]
@abhi5794 more verbose than `pip -v` is probably not necessary. 

Your gist there does not contain any errors. I am guess you forgot to redirect stderr to the log file.

**Comment by abhi5794** [comment]
@Grimler91  Sorry, my bad, I have updated the file. Will that help? I redirect the stderr, back to the file, 2>&1 .

**Comment by Grimler91** [comment]
Right now you are getting problems because You are using GCC and have not run `setup-patchforgcc` so the system header files fails to compile with GCC. So either switch back to using clang with `setupclang` or run `setup-patchforgcc`

**Comment by abhi5794** [comment]
@Grimler91  That worked, thank you very much, I can finally get some sleep. The first one worked `setup-pathforgcc` , `setupclang` failed to install pandas for some reason. Just for my knowledge, does `setup-pathforgcc`, register the path of where C sits? Sorry for the noob question. Googling did not make it any clearer.

**Comment by xeffyr** [comment]
`setup-patchforgcc` makes $PREFIX/include compatible with GCC.

**Comment by abhi5794** [comment]
@xeffyr Thank you, it is clear now
