### ISSUE TITLE
Package request: libzim

### ISSUE THREAD

**Issue by sobaee** [termux/termux-packages#5649]
**Package description**
This package is very important so I can use kiwix for python, and I can use pyglossary plugin

**Link to sources:
Source code: https://github.com/openzim/libzim
Source code for python: https://github.com/openzim/python-libzim

**Additional information**
I tried to compile this package using the method and installed all dependencies with no benefit

**Comment by buttaface** [comment]
Available now, `pkg install libzim`, reopen if there's a problem.
