### ISSUE TITLE
CANNOT LINK EXECUTABLE "termux-elf-cleaner": library "libc++_shared.so" not found

### ISSUE THREAD

**Issue by SteelDualMassWheel** [termux/termux-packages#5650]
**Problem description**
Hello, I have problem with termux-elf-cleaner:

$ termux-elf-cleaner /data/data/com.termux/files/usr/lib/libcrypto.so.1.1
CANNOT LINK EXECUTABLE "termux-elf-cleaner": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
Aborted
$

After that, I found that using unset LD_PRELOAD and then running the termux-elf-cleaner will give different error:

$ termux-elf-cleaner /data/data/com.termux/files/usr/lib/libcrypto.so
CANNOT LINK EXECUTABLE "termux-elf-cleaner": library "libc++_shared.so" not found
Aborted
$

which i didn't find any solution to. I would like to know how to make termux-elf-cleaner work without this error.

**Steps to reproduce**
//run:

unset LD_PRELOAD

//then run

termux-elf-cleaner /data/data/com.termux/files/usr/lib/libcrypto.so

**Expected behavior**

termux-elf-cleaner working correctly, which would lead to not seeing: 
WARNING: linker: /data/data/com.termux/files/home/cpp/a.out: unsupported flags DT_FLAGS_1=0x8000001
when executing simple c++ program ( in my case ).

**Additional information**
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-g0bde30b #2 SMP PREEMPT Mon Oct 8 13:33:13 CST 2018 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
AGS-W09

```

**Comment by SteelDualMassWheel** [comment]
**Problem description**


**Steps to reproduce**


**Expected behavior**


**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-g0bde30b #2 SMP PREEMPT Mon Oct 8 13:33:13 CST 2018 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
AGS-W09

```

**Comment by Grimler91** [comment]
> CANNOT LINK EXECUTABLE "termux-elf-cleaner": library "libc++_shared.so" not found

Have you backed up and restored an installation for android 5&6 on your android 7 device or something? I do not see how that error can happen without messing a lot with installation. 

Try removing $PREFIX to get a fresh installation, run:

```
rm -rf $PREFIX
```
and then restart the app and reinstall all packages

**Comment by xeffyr** [comment]
It also looks like mixing AArch64 and ARM binaries, which would not happen without tampering $PREFIX either by installing packages manually from debfiles or copying from another device.

**Comment by SteelDualMassWheel** [comment]
> > CANNOT LINK EXECUTABLE "termux-elf-cleaner": library "libc++_shared.so" not found
> 
> Have you backed up and restored an installation for android 5&6 on your android 7 device or something? I do not see how that error can happen without messing a lot with installation.
> 
> Try removing $PREFIX to get a fresh installation, run:
> 
> ```
> rm -rf $PREFIX
> ```
> 
> and then restart the app and reinstall all packages

Ok this worked, i can use termux-elf-cleaner without any error, however warning still appear when ./a.out simple c++ program. I read that the warning "WARNING: linker: /data/data/com.termux/files/home/cpp/a.out: unsupported flags DT_FLAGS_1=0x8000001" will disappear if I use the termux-elf-cleaner on files /data/data/com.termux/files/usr/lib/libcrypto.so ; libcrypto.so.1.1 ; libssl.so and libssl.so.1.1 .

**Comment by xeffyr** [comment]
> will disappear if I use the termux-elf-cleaner on files /data/data/com.termux/files/usr/lib/libcrypto.so

No, they won't disappear. You have read about specific case when they were shown during `apt` execution - in this case they were happened due to unsupported entries in ELF shared object headers and only on Android 5.x (and maybe 6.x).

In your case you should run `termux-elf-cleaner` on your program binary and do not touch anything in $PREFIX.

**Comment by SteelDualMassWheel** [comment]
Oh, I understand. So I will have to run termux-elf-cleaner on every executable program that i will write in order not to see warning, is that correct?
I would rather not see these warning and not have to execute additional command every time I want to run a c++ program. Is this possible?

**Comment by xeffyr** [comment]
> So I will have to run termux-elf-cleaner on every executable program that i will write in order not to see warning, is that correct?

Correct. That's the purpose of `termux-elf-cleaner` - to remove ELF executable sections which are not supported by Android dynamic linker.

> I would rather not see these warning and not have to execute additional command every time I want to run a c++ program. Is this possible?

That depends on your OS. What Android version you are running? I don't see any warnings when running my executables, however my Android version is 9.

Patching `clang` to avoid these warnings will potentially lead to undesired consequences.

**Comment by SteelDualMassWheel** [comment]
I included my android version in **Additional information**, my android version is 7.0, i am using clang++ command to compile and ./a.out to execute if that helps. I cannot try using g++ to check if i get the same result as g++ is more than 5GB and I don't have enough internal storage. If you know any other c++ compiler I can check if the warning appear there too.

**Comment by Grimler91** [comment]
g++, from GCC, is not 5 GB, GCC is only a few 100 mb
