### ISSUE TITLE
What should I do ？

### ISSUE THREAD

**Issue by 26chk** [termux/termux-packages#5652]
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does no longer have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
![Screenshot_20200806_123006](https://user-images.githubusercontent.com/61009000/89491458-eeaab600-d7e1-11ea-8ac1-0ca89c3dfd13.jpg)

**Comment by SDRausty** [comment]
@26chk you can start by searching [here](https://github.com/termux/termux-packages/issues?q=is%3Aissue+no+longer+have+a+Release+file); maybe you might find an answer to the question.

**Comment by Grimler91** [comment]
Fixed now, thanks for reporting!
