### ISSUE TITLE
Possible cause: repository is under maintenance or down (wrong sources.list URL?).

### ISSUE THREAD

**Issue by potatonc** [termux/termux-packages#5653]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
```

**Comment by joshcangit** [comment]
> ```
> E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
> N: Metadata integrity can't be verified, repository is disabled now.
> N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
> ```

Yes, I've checked that repository. It is missing a **Release** file but the **Release.gpg** file is still there.

**Comment by potatonc** [comment]
> > ```
> > E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
> > ```
> 
> > N: Metadata integrity can't be verified, repository is disabled now.
> 
> > N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
> 
> Yes, I've checked that repository. It is missing a **Release** file but the **Release.gpg** file is still there.

Then how do I do a 'pkg update and pkg upgrade'?, because the log is there when I want to do an 'update and upgrade'

**Comment by potatonc** [comment]
> > ```
> > E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
> > ```
> 
> > N: Metadata integrity can't be verified, repository is disabled now.
> 
> > N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
> 
> Yes, I've checked that repository. It is missing a **Release** file but the **Release.gpg** file is still there.

I have reinstalled the Termux app but the logs are still there and I can't do the 'update and upgrade'.

**Comment by joshcangit** [comment]
You have to get rid of the `game-repo` package.

```
apt purge game-repo -y
```

Then updating will work properly again.

**Comment by potatonc** [comment]
> You have to get rid of the `game-repo` package.
> 
> ```
> apt purge game-repo -y
> ```
> 
> Then updating will work properly again.

Wow, you are the best. now I can do 'update', thank you so much.

**Comment by joshcangit** [comment]
BTW, you can make sure packages from that repository are not installed.

```
pkg list-all 2>&0 | grep "/game"
```

**Comment by potatonc** [comment]
> BTW, you can make sure packages from that repository are not installed.
> 
> ```
> pkg list-all 2>&0 | grep "/game"
> ```

I did, and this is the output :
```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```
BTW, Is the game-repo condition like that on all Android termux?

**Comment by joshcangit** [comment]
> BTW, Is the game-repo condition like that on all Android termux?

Yes, this would be the case since it is a problem with [that repository](https://dl.bintray.com/grimler/game-packages-24/) and not with the app itself.

@Grimler91 will have to restore that missing file for it to work again.

**Comment by potatonc** [comment]
> > BTW, Is the game-repo condition like that on all Android termux?
> 
> Yes, this would be the case since it is a problem with [that repository](https://dl.bintray.com/grimler/game-packages-24/) and not with the app itself.
> 
> @Grimler91 will have to restore that missing file for it to work again.

I hope @ grimler91 can quickly recover those files.

oh ya, sorry I can not help answer the issue that you open on #5655 

And I am very grateful because you can solve my problem.

**Comment by Grimler91** [comment]
Fixed now, by regenerating the metadata for the repository. 
Second time that the Release file disappears without explanation. I will contact bintray about it.

**Comment by kennyendowed** [comment]
go here to download
 https://f-droid.org/packages/com.termux/

**Comment by 111Comander-w** [comment]
> **Problem description**
> 
> **Steps to reproduce**
> 
> **Expected behavior**
> 
> **Additional information**
> 
> ```
> E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
> N: Metadata integrity can't be verified, repository is disabled now.
> N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
> ```

Hi. If you always get this error just go to termux and type
"apt upgrade" and when it finishes, you are ready with you termux. I also did this and my termux is now working fine

**Comment by 111Comander-w** [comment]
Just type "apt upgrade"

**Comment by Mustafa0123959304** [comment]
apt upgrade
Dos not working 
Show me 
dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.

**Comment by acphack** [comment]
> You have to get rid of the `game-repo` package.
> 
> ```
> apt purge game-repo -y
> ```
> 
> Then updating will work properly again.

This doesn't solved my issue. Please help.
I cleared data and put this command but not able to update; upgrade after that.

**Comment by 111Comander-w** [comment]
Its ok friend, i will try to solveSent from my Samsung Galaxy smartphone.
-------- Original message --------From: acphack ***@***.***> Date: 29/07/2021  1:01 pm  (GMT+05:30) To: termux/termux-packages ***@***.***> Cc: 111Comander-w ***@***.***>, Comment ***@***.***> Subject: Re: [termux/termux-packages] Possible cause: repository is under
  maintenance or down (wrong sources.list URL?). (#5653) 

You have to get rid of the game-repo package.
apt purge game-repo -y

Then updating will work properly again.

This doesn't solved my issue. Please help.
I cleared data and put this command but not able to update; upgrade after that.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/termux/termux-packages/issues/5653#issuecomment-888872894",
"url": "https://github.com/termux/termux-packages/issues/5653#issuecomment-888872894",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xeffyr** [comment]
@acphack See pinned issue: https://github.com/termux/termux-packages/issues/6726

**Comment by 111Comander-w** [comment]
Don't worry we will try to solve it...

**Comment by gerrishons** [comment]
apt upgrade works
