### ISSUE TITLE
How listen port 80, 443 with termux ?

### ISSUE THREAD

**Issue by zababurinsv** [termux/termux-packages#5654]
I don't have root.

I install nginx and i can't listen port 80 and 443.

Do I have the ability to somehow change this without adding a root permission ?

**Comment by xeffyr** [comment]
> I don't have root.

If no root, then you can't bind low ports. That's a general Linux restriction: all ports from 1 to 1023 are privileged and requires either root permission, specifically its capability `CAP_NET_BIND_SERVICE`.
