### ISSUE TITLE
Problem adding mirror repository

### ISSUE THREAD

**Issue by joshcangit** [termux/termux-packages#5655]
I tried changing to a mirror from @xeffyr for the games repository but it won't work.

```
W: GPG error: https://games.termux-mirror.ml games Release: The following signatures were invalid: BADSIG 5AAAC9E0A46BE53C Henrik Grimler <henrik@grimler.se>
E: The repository 'https://games.termux-mirror.ml games Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
```

It still expects a signature from @Grimler91 where the main repository for games reside.

Issue #5653 shows that repository is missing the **Release** file so it can't be used.

**Comment by joshcangit** [comment]
> I tried changing to a mirror from @xeffyr for the games repository but it won't work.
> 
> ```
> W: GPG error: https://games.termux-mirror.ml games Release: The following signatures were invalid: BADSIG 5AAAC9E0A46BE53C Henrik Grimler <henrik@grimler.se>           E: The repository 'https://games.termux-mirror.ml games Release' is not signed.                                 N: Metadata integrity can't be verified, repository is disabled now.                                            N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
> ```
> 
> It still expects a signature from @Grimler91 where the main repository for games reside.
> 
> Issue #5653 shows that repository is missing the **Release** file so it can't be used.

**Comment by Grimler91** [comment]
Fixed now, thanks for reporting!

**Comment by joshcangit** [comment]
It seems that switching mirrors is only possible for the main repository.

**Comment by Grimler91** [comment]
Switching, preferably with the `termux-change-repo` tool, is possible for all repositories. Mark the ones you want to switch by marking them and pressing space in the tool.

Problem here was that the Release file was deleted from the main repository for unknown reasons. The mirrors then mirror that repository so that the problem propagates. I resigned the repo to re-create the Release file.

**Comment by Marcoslaurenz** [comment]
I am getting this error help me please:


The repository 'https://main.termux-mirror.ml stable Rel 
N: Metadata integrity can't be verified, repository is disable now

N: Possible case: repository is under maintenance or down (wrong source.list URL?).

**Comment by WMCB-Tech** [comment]
See above messages for solution

> Switching, preferably with the `termux-change-repo` tool, is possible for all repositories. Mark the ones you want to switch by marking them and pressing space in the tool.

**Comment by danigilment** [comment]
> Fixed now, thanks for reporting!

Now  again same problem in termux

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/6726
