### ISSUE TITLE
Use of "switcher" from package boinc triggers seccomp

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-packages#5668]
**Problem description**

```
$ switcher --help
Bad system call
```

Strace:
```
rt_tgsigqueueinfo(2941, 2941, SIGSYS, {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x73e84c0ba8, si_syscall=__NR_setgroups, si_arch=AUDIT_ARCH_AARCH64}) = 0
```

**Comment by xeffyr** [comment]
Intended behavior as switching uids/gids is the purpose of this utility.

As boinc works fine, I'm closing this issue.

**Comment by truboxl** [comment]
I think I will make a PR to remove switcher, it really isn't used on Android but for macOS

**Comment by truboxl** [comment]
How is the patch file generated? `git diff` seems to produce a different header..

**Comment by Grimler91** [comment]
@truboxl `git diff` headers work as well, the alternative is `diff -u`
