### ISSUE TITLE
qiskit

### ISSUE THREAD

**Issue by haareks** [termux/termux-packages#5676]
Hello,

I have trouble installing pip install qiskit .

there are several issues, including cmake and I thunk scipy.

could someone have a look at this, please?

**Comment by kcubeterm** [comment]
Have u installed cmake already, if not , Install it and provide full log or output.

**Comment by haareks** [comment]
> Have u installed cmake already, if not , Install it and provide full log or output.

https://quantumcomputing.stackexchange.com/questions/13141/problem-with-installing-qiskit-on-android-with-termux-emulator

here another thread with installation output.

User jack woehr tried to built newest cmake, but got stuck at the point that scipy couldnt find libblas.so in /usr/lib

is it working in your termux, kcubeterm?

**Comment by xeffyr** [comment]
Scipy, openblas are available in https://github.com/its-pointless/its-pointless.github.io.

**Comment by buttaface** [comment]
That log from your stackexchange link probably shows the libc++ package isn't installed:
```
/data/data/com.termux/files/usr/bin/c++ -g -static-libstdc++ -static-libgcc -lrt  CMakeFiles/cmTC_793bc.dir/testCXXCompiler.cxx.o -o cmTC_793bc
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: cannot find -lc++_shared
```

**Comment by xeffyr** [comment]
> probably shows the libc++ package isn't installed

Static libc++ isn't installed.
