### ISSUE TITLE
E: Unable to locate package pdfjam

### ISSUE THREAD

**Issue by karim4648** [termux/termux-packages#5679]
pkg install pdfjam
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pdfjam

**Comment by xeffyr** [comment]
`pkg install texlive-bin`

**Comment by Grimler91** [comment]
Also need to install texlive-binextra (or texlive-installer and then pdfjam through tlmgr), texlive-bin provides a symlink

**Comment by karim4648** [comment]
pdfjam ERROR: LaTeX package pdfpages.sty is not installed

**Comment by karim4648** [comment]
> `pkg install texlive-bin`

after install facing problem
pdfjam ERROR: LaTeX package pdfpages.sty is not installed
