### ISSUE TITLE
neovim: Using python3 or python2 does not work on arm

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#568]
Setup:

    apt install neovim python python2
    pip2 install neovim
    pip3 install neovim

Now, from inside neovim try:

    py3 print('hello')
    py print 'hello'

This fails on arm with something like

    function provider#python3#Call[9]..remote#host#Require[13]..provider#pythonx#Require, line 15
    Vim(if):Channel was closed by the client
    Failed to load python3 host. You can try to see what happened by starting nvim with
    $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host
    stderr is available in messages.

It works on an aarch64 device.

**Comment by rmolin88** [comment]
@fornwall @mklein994 Thanks for the support.

**Comment by fornwall** [comment]
Perhaps the issue is with msgpack on arm?

**Comment by christianrondeau** [comment]
Hey, just tried this and it works for me. Either something changed since then or the issue is specific to certain setups. 

    apt install python python-dev python2 python2-dev neovim
    pip2 install neovim
    pip3 install neovim

Then both commands work in `nvim`:

    py3 print('hello')
    py print 'hello'

**Comment by mklein994** [comment]
So I've got good and bad news (so far). Python3 works :D but python2 still gives an error. I'll try clearing caches and trying again. Thanks for the heads up!

**Comment by fornwall** [comment]
Great!

I suspect the update of libmsgpack to version 2.1.5, which contains fixes for arm, solved this problem.
