### ISSUE TITLE
Also need to install texlive-binextra (or texlive-installer and then pdfjam through tlmgr), texlive-bin provides a symlink

### ISSUE THREAD

**Issue by karim4648** [termux/termux-packages#5681]
pdfjam ERROR: LaTeX package pdfpages.sty is not installed

my requirment
pdfjam page1.pdf page2.pdf --nup 2x1 --landscape --outfile Page1+2.pdf

**Comment by karim4648** [comment]
my requirment 
using pdfjam package in termux app
multiple pages in single page pdf in pdf file
in termux app only 
any solution please help me

**Comment by Grimler91** [comment]
If you installed via texlive-installer install pdfpages via tlmgr.

If you installed texlive-binextra, install texlive-latexrecommended to get pdfpages.

**Comment by karim4648** [comment]
> If you installed via texlive-installer install pdfpages via tlmgr.
> 
> If you installed texlive-binextra, install texlive-latexrecommended to get pdfpages.

i tried but below one shows

pkg install texlive-bin
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
texlive-bin is already the newest version (20200406-5).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
$ tlmgr install pdfpages
The program tlmgr is not installed. Install it by executing:
 pkg install texlive-bin
this shows how to fix this detail one by one commands please
