### ISSUE TITLE
Php-apache memery limi exceeded

### ISSUE THREAD

**Issue by bsde1234** [termux/termux-packages#5682]
When I run a file I get error like 
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs
```
How to fix

**Comment by Grimler91** [comment]
See for example https://stackoverflow.com/questions/17818080/fatal-error-allowed-memory-size-of-67108864-bytes-exhausted-tried-to-allocate
