### ISSUE TITLE
crond does not run in foreground

### ISSUE THREAD

**Issue by Fhugem** [termux/termux-packages#5685]
crond used to work fine for me using the command -f, now that it had some changes to it doesn't run a script in foreground using -n. It works fine in the bg tho

**Comment by xeffyr** [comment]
> it doesn't run a script in foreground using -n

1. Which script?
2. Are you using `cronie` as crond daemon provider?
3. How you starting it?

If you use package `cronie` for crond, then to run in foreground you need to launch it as `crond -n`. Cronie does not provide option `-f` at all.

**Comment by Fhugem** [comment]
> > it doesn't run a script in foreground using -n
> 
> 1. Which script?
> 2. Are you using `cronie` as crond daemon provider?
> 3. How you starting it?
> 
> If you use package `cronie` for crond, then to run in foreground you need to launch it as `crond -n`. Cronie does not provide option `-f` at all.

Well in an older version, in my case version 0.94, it uses the option -f to run in foreground and it works fine. However on the version now it does not. I have tested it with a simple task */1 * * * * echo "test" and started cronie with crond -n.

**Comment by xeffyr** [comment]
Ok, cronie doesn't have this feature. It sends everything to syslog (Android log). So, if you want to see the output of your command, check the output of `logcat | grep -i crond`.

**Comment by xeffyr** [comment]
If really need output to console, try with debugging flags: `crond -n -x sch`.
