### ISSUE TITLE
Update 0.95 to 0.96 messed up on F-droid

### ISSUE THREAD

**Issue by mtersch** [termux/termux-packages#5686]
Just upgraded from 0.95 to 0.96 from F-droid repository. When starting up, error message that 'cat' and some other binary could not be found; only option was to press <Enter> which closes Termux. (Forgot to note/screenshot exact error message...sorry.)
Workaround: uninstall & reinstall; lost workdir with soft-links into filesystem in the process...

Will report this issue on F-droid issue tracker as well (as it might be issue in build by F-droid?)

**Comment by xeffyr** [comment]
You have issue described at https://github.com/termux/termux-app/issues/1703, ways for workaround also shown here.

As of Termux v0.96, we no longer support running packages installed from https://termux.net - they are intended for use with Android 5.x - 6.x which is not supported anymore.
