### ISSUE TITLE
teleconsole

### ISSUE THREAD

**Issue by Creator54** [termux/termux-packages#5689]
**Package description**
Provides a simple way of sharing terminal sessions

**Link to home page and sources**
1. Home page:https://github.com/gravitational/teleconsole
2. Source code:https://github.com/gravitational/teleconsole

**Additional information**
Have you compiled or tried to compile the package on device? 
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by xeffyr** [comment]
See my answers in https://github.com/termux/termux-packages/issues/5689 regarding this project. As soon as it uses SSH links or private repository submodules, it is not eligible for packaging.

**Comment by ifurther** [comment]
Maybe wait it upgrade it, it will fix this problem.

**Comment by Grimler91** [comment]
Looks like the missing gitmodule is for the "enterprise" version of teleport, so it should be possible to build teleconsole with slightly fewer features without that module if I understand the docs correctly:   https://github.com/gravitational/teleport/blob/master/docs/4.3/index.md#teleport-enterprise

I haven't found other distros building it from source though (checked debian and archlinux).

**Comment by xeffyr** [comment]
@Grimler91 There is some info on how to build `teleconsole` with manual cloning of `teleport`: https://github.com/termux/termux-packages/wiki/Termux-and-Android-10. I'll try that variant.

**Comment by xeffyr** [comment]
With manual clone more progress, but fails anyway:
```
# github.com/gravitational/teleconsole/lib
lib/identity.go:114:2: undefined: native.PrecalculatedKeysNum
lib/identity.go:115:30: not enough arguments in call to native.New
	have ()
	want ("context".Context, ...native.KeygenOption)
lib/identity.go:115:30: multiple-value native.New() in single-value context
lib/identity.go:136:6: undefined: "github.com/gravitational/teleport/lib/utils".IsFile
```

**Comment by ifurther** [comment]
The teleport should change version.
`git clone --depth 1 --branch v2.0.0-alpha.4 https://github.com/gravitational/teleport.git`
But old version don't support arm64

**Comment by xeffyr** [comment]
`pkg install teleport-tsh`.

**Comment by CypherpunkSamurai** [comment]
> `pkg install teleport-tsh`

How do i compile teleconsole?

Building it returns error in the code.

`teleconsole $ go build .
# github.com/gravitational/teleport/vendor/github.com/mattn/go-sqlite3
sqlite3-binding.c:111991:38: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775806 to 9223372036854775808 [-Wimplicit-int-float-conversion]
sqlite3-binding.c:111993:46: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775806 to 9223372036854775808 [-Wimplicit-int-float-conversion]
# github.com/gravitational/teleconsole/lib
lib/identity.go:114:2: undefined: native.PrecalculatedKeysNum
lib/identity.go:115:30: not enough arguments in call to native.New
        have ()
        want ("context".Context, ...native.KeygenOption)
lib/identity.go:115:30: multiple-value native.New() in single-value context
lib/identity.go:136:6: undefined: "github.com/gravitational/teleport/lib/utils".IsFile`
