### ISSUE TITLE
Busybox 'date' applet doesn't work correctly

### ISSUE THREAD

**Issue by jschultz** [termux/termux-packages#569]
Hello,

Hoping this is the right place to be reporting this issue. I noted while porting some personal scripts to termux that the 'date' applet packaged with Termux seems not to work correctly:

> busybox date -d 1480292026 -D %s
> date: invalid date '1480292026'

If I instead call a busybox executable downloaded from https://busybox.net/downloads/binaries/latest/busybox-armv7l:

> ~/bin/busybox date -d 1480292026 -D %s
> Mon Nov 28 00:13:46 UTC 2016

Thanks in advance...

**Comment by fornwall** [comment]
This is the right place indeed to report! I'm able to reproduce the problem.

**Comment by fornwall** [comment]
The following program fails on Android:

```C
#define _XOPEN_SOURCE
#include <stdio.h>
#include <string.h>
#include <time.h>

int main(void)
{
        struct tm tm;
        char buf[255];

        memset(&tm, 0, sizeof(struct tm));
        if (strptime("1480292026", "%s", &tm) == NULL) {
                fprintf(stderr, "strptime() failed\n");
                return 1;
        }
        strftime(buf, sizeof(buf), "%d %b %Y %H:%M", &tm);
        puts(buf);
        return 0;
}
```

**Comment by fornwall** [comment]
Busybox uses strptime(3) for parsing the date using the specified format. On Android (with the default libc, which Termux uses) this function does not support %s, which is a glibc extension.

I've created an issue to consider supporting %s in Android at https://code.google.com/p/android/issues/detail?id=229155 - closing this issue in favour of that one.

**Comment by jschultz** [comment]
Thanks for the prompt attention.
In the meantime I notice that the correct result can be obtained with:

> busybox date -d \@1480292026

In fact this works even better than the executable from busybox.net because it correctly detects the local timezone.
