### ISSUE TITLE
Unable to check system information

### ISSUE THREAD

**Issue by Durgesh8530** [termux/termux-packages#5691]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

``` termux is unable to check my system information like: battery status , camera information,etc please help

**Comment by xeffyr** [comment]
Fill the template normally. Your issue description says literally nothing about its problem and source.

If you have trouble with Termux:API, make sure you checked the page https://wiki.termux.com/wiki/Termux:API and installed BOTH **application** and **package** (termux-api).
