### ISSUE TITLE
ufetch

### ISSUE THREAD

**Issue by Creator54** [termux/termux-packages#5698]
**Package description**
A minimal fetch to display system info

**Link to home page and sources**
1. Home page: https://github.com/jschx/ufetch
2. Source code: https://github.com/jschx/ufetch

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by xeffyr** [comment]
Ufetch is fine-tuned for specific distributions. It does not have support for Android or Termux and I won't bother implement such.

We have a `screenfetch` which already has support for Android.
