### ISSUE TITLE
Mongo db error🙂

### ISSUE THREAD

**Issue by amm834** [termux/termux-packages#5699]
![Screenshot_2020-08-17-09-03-15-66_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/65492233/90352276-d734be00-e068-11ea-9997-bfc3f122853e.jpg)

**Problem description**

When I install this (non-root)
I get
CANNOT LINK EXECUTABLE "mongo": library "libicudata.so.66" not found.
**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
Write issues to https://github.com/termux/termux-packages/issues/249.
MongoDB is not Termux official package.

**Comment by xeffyr** [comment]
Or even better, write to https://github.com/its-pointless/its-pointless.github.io/issues which belongs to repo where it is distributed.
