### ISSUE TITLE
Npm not work at sdcard even though access to storage.

### ISSUE THREAD

**Issue by amm834** [termux/termux-packages#5705]
**Problem description**

I create Vue app in my internal storage not working 🤧
But work in $HOME directory.
when i use it in storage
I get npm errors
<code>
vue create testApp
</code>
So i get following errors
npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ../@babel/parser/bin/babel-parser.js
npm ERR! dest /storage/emulated/0/www/test/node_modules/.bin/parser
npm ERR! errno -1
npm ERR! Error: EPERM: operation not permitted, symlink '../@babel/parser/bin/babel-parser.js' -> '/storage/emulated/0/www/test/node_modules/.bin/parser'
npm ERR!  [OperationalError: EPERM: operation not permitted, symlink '../@babel/parser/bin/babel-parser.js' -> '/storage/emulated/0/www/test/node_modules/.bin/parser'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, symlink '../@babel/parser/bin/babel-parser.js' -> '/storage/emulated/0/www/test/node_modules/.bin/parser'] {
npm ERR!     errno: -1,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'symlink',
npm ERR!     path: '../@babel/parser/bin/babel-parser.js',
npm ERR!     dest: '/storage/emulated/0/www/test/node_modules/.bin/parser'
npm ERR!   },
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../@babel/parser/bin/babel-parser.js',
npm ERR!   dest: '/storage/emulated/0/www/test/node_modules/.bin/parser',
npm ERR!   parent: 'test'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2020-08-18T22_04_47_144Z-debug.log
 ERROR  command failed: npm install --loglevel error

**Steps to reproduce**

**Expected behavior**

![Screenshot_2020-08-19-04-48-27-59_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/65492233/90571614-22b9aa00-e1d8-11ea-9b2d-9837fabeff86.jpg)

**Additional information**

```

```

**Comment by RossComputerGuy** [comment]
Android is designed to block file execution on the SDcard, this cannot be circumvented. Issue us not directly Termux related so it will be closed.

**Comment by xeffyr** [comment]
Use NPM in Termux home directory.

Shared storage does not support features used by NPM, e.g. symlinks and file permissions. This is not Termux issue.

**Comment by amm834** [comment]
Thanks
