### ISSUE TITLE
200819 14:21:24 mysqld_safe A mysqld process already exists!

### ISSUE THREAD

**Issue by amm834** [termux/termux-packages#5706]
**Problem description**

#Mariadb Error
200819 14:21:24 mysqld_safe A mysqld process already exists
and cannot kill process.
**Steps to reproduce**

Hello here I get some error and I am fixing but not working!
I am not fresh user of mariadb.
When I uninstalled and install again from play store.I get many errors from Mariadb in Termux.
My code step is:<hr>
<code>apt update && apt upgrade -y <br>
pkg install mariadb<br>
mysql<br></code>
<pre>ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/data/data/com.termux/files/usr/tmp/mysqld.sock' (2)</pre>
<b>I know this error and  I solved by using following </b>
<code>
cd '/data/data/com.termux/files/usr' ; /data/data/com.termux/files/usr/bin/mysqld_safe --datadir='/data/data/com.termux/files/usr/var/lib/mysql'
</code>
Second one is:<br>
<code>cd $PREFIX/etc/init.d/ </code>
<code>./mysql start</code>
<b>I tried them by uninsall and insatll termux in two times.</b>
What ever way i use first time <code>mysql</code> is start.And i can access all of db.
And then i quick from mariadb and i kill my db process by using
<code>pkill mysqld </code>
It cannot be done now.
So i use many linux killing process but they always show to me
<pre>No Process Found</pre>
So I logout from termux by using
<code>logout</code>
And open again and try them.But I cannot get them.
I used termux for 3 months with a little problem I have been shown above,but now this db problem I am not done cleaning yet.So I need help from termux app developers and  pkg writers.Please help me.I also want to get back of <code style="color:red;">mariadb</code>
back.I am finding my errors in mysql/localhost.log
I have not been seen just like this.Help me and please remove lastest commit and recommit back of low version of mariadb.
Thanks.
**Expected behavior**

**Additional information**

```
Phone Version
Model : Oppo A5 2020
Version: 10.0
RAM:4GB
ROM:128GB
No Root
```
![Screenshot_2020-08-19-14-45-32-88](https://user-images.githubusercontent.com/65492233/90609863-aac89f80-e22a-11ea-994a-54070adaa96b.jpg)

**Comment by Grimler91** [comment]
So have you checked the pid of the process and tried to kill it that way? Run `ps x`. 

If the process name/pid is correct and it still does not work then try specifying signal 9, `pkill -9`.

> please remove lastest commit and recommit back of low version of mariadb

I do not see any valid reason for downgrading the package.

**Comment by amm834** [comment]
> So have you checked the pid of the process and tried to kill it that way? Run `ps x`.
> 
> If the process name/pid is correct and it still does not work then try specifying signal 9, `pkill -9`.
> 
> > please remove lastest commit and recommit back of low version of mariadb
> 
> I do not see any valid reason for downgrading the package.

I have been tried Not work
![Screenshot_2020-08-19-15-41-46-01_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/65492233/90615722-85d82a80-e232-11ea-8445-d76046ba4960.jpg)
![Screenshot_2020-08-19-15-41-49-07_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/65492233/90615745-8b357500-e232-11ea-81a9-e2c50e6bff91.jpg)
When I am sing old version I use 
<code>pkill mysqld </code>
The first photo should show <code>$</code>
But not.Ibtried all of linux command that kill mysql db.They ever said No Process is Running!
Help me plz

**Comment by amm834** [comment]
I did but I am not so remember.
<code>kill $(ps aux | grep '[m]ysql' | awk '{print $2}')</code>
Thank for replying to me.
