### ISSUE TITLE
Package request: libimobiledevice and usbmuxd

### ISSUE THREAD

**Issue by TheWeirdDev** [termux/termux-packages#5707]
**Package description**

A cross-platform FOSS library written in C to communicate with iOS devices natively.
The library implements the native protocols needed to communicate with services running on iOS devices. Due to the reimplemention it does not depend on using or bundling any existing libraries from Apple.
It has already been built and run on Linux, Mac, Windows, Android and embedded ARM SoCs.

**Link to home page and sources**
1. Home page: [libimobiledevice.org](https://libimobiledevice.org/)
2. Source code: [libimobiledevice](https://github.com/libimobiledevice/libimobiledevice)  and  [usbmuxd](https://github.com/libimobiledevice/usbmuxd)

**Additional information**
Have you compiled or tried to compile the package on device? **No**

**Comment by ifurther** [comment]
It should need "pthread".

**Comment by TheWeirdDev** [comment]
Yes, running ldd on linux x64 binaries shows it depends on pthread. Is this a problem?

**Comment by ifurther** [comment]
I add the patch, and resolve this problem. Sorry

**Comment by TheWeirdDev** [comment]
OK, Thanks.

**Comment by normanr** [comment]
@TheWeirdDev I'm curious as to what this is needed for. Do you have root on the Android device? Otherwise you may find the libusb can't access the usb device directly and may need some work-arounds (or fixes along the lines of those proposed in https://github.com/termux/termux-api/issues/349) in order to work as expected.

**Comment by TheWeirdDev** [comment]
@normanr I usually run `idevicediagnostics ioregentry AppleARMPMUCharger` on my PC to get the battery diagnostics of my iOS devices. I wanted to do this using my android phone (It has root access) but it didn't work. Probably because it's an old phone with a loose usb socket.

**Comment by FukkenShit** [comment]
Is it intended to connect over wifi?

**Comment by gbu117** [comment]
Given libimobiledevice is now on the non-root repos, but doesn't seem to work without root (forgive me me if I am missing something here - usbmuxd refuses to start for me, but if someone has it working please let me know) it would be great if it eventually worked without root with an integration into an adjusted libusb and usbmuxd that took advantage of Android's USB APIs and then allowed a move in the future to include the rest of the libimobiledevice suite such as ideviceactivation and idevicerestore on the non-root repos.
