### ISSUE TITLE
Add sudo

### ISSUE THREAD

**Issue by flipflop97** [termux/termux-packages#571]
On a rooted system, the only way to execute commands as root (afaik) is using su, which forces a sh shell and other environment. It would be nice to see sudo appear in the repo to be able to use all available commands as root.

**Comment by AlexMikhalev** [comment]
workaround 
create sudo bash script with 
`su -c "$*" `

**Comment by flipflop97** [comment]
@AlexMikhalev Yes, that allows me to execute built in commands in android, but not the full commands installed via the termux apt. So it's not a full solution.

    > clang
    clang-3.9: error: no input files
    
    > su -c "clang"
    sh: clang: not found

**Comment by sp4rkie** [comment]
I even haven't installed su on my regular pc. Instead I always use my 'pp.c'. Just do
```
make pp
chmod 4755 pp    # as root
chown root.root pp    # as root
```
pp.c:
```
main(argc, argv)
    char **argv;
{
    int off = 0;
    char *str = "the force will be with you. always.\n";

    if (setgid(0) || setuid(0)) perror(*argv);
    if (*(argv + 1)) {
        if (strcmp(*(argv + 1), "-q")) {
            write(2, str, strlen(str));
        } else {
            ++off;
        }
        if (execvp(*(argv + 1 + off), argv + 1 + off)) {
            perror(*argv);
            exit(2);
        }
    } else {
        exit(1);
    }
}
```

**Comment by xeffyr** [comment]
sudo is available as `tsudo` from `tsu` package: https://github.com/termux/termux-packages/blob/master/packages/tsu/build.sh
