### ISSUE TITLE
Wren wrong executable

### ISSUE THREAD

**Issue by nbvdkamp** [termux/termux-packages#5712]
**Problem description**

In wren update 0.3.0 the CLI/REPL was moved into a [separate repository](https://github.com/wren-lang/wren-cli/). The executable currently included in the termux package is wren_test, this can be built from the main wren repo and can run basic wren scripts but can't access, for example, the io module included in the CLI tool.

I think the executable in the module should be the CLI / REPL tool because it's far more useful standalone than wren_test.

I currently don't have access to a PC but I might be able to open a PR for it in about a week.

**Comment by buttaface** [comment]
My fault, I updated wren to 0.3.0 and figured it was the same thing. I'll look at it.

**Comment by buttaface** [comment]
@nbvdkamp, wren has been split into two packages now, `libwren` with the libraries and `wren` with the command-line interpreter, let us know if this fixes it for you.

**Comment by nbvdkamp** [comment]
Yep, works perfectly now. Thanks!
