### ISSUE TITLE
The link provided is not working 

### ISSUE THREAD

**Issue by Prajwalbujji** [termux/termux-packages#5717]
![Screenshot_2020-08-21-12-07-40-21](https://user-images.githubusercontent.com/70006309/90860081-0029bb80-e3a7-11ea-9587-650f1421cea6.jpg)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by Grimler91** [comment]
This is not a termux issue as ngrok is not a package we provide.
