### ISSUE TITLE
mpv: CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by rqcy** [termux/termux-packages#572]
I get the following error when starting mpv:

```
$ mpv
CANNOT LINK EXECUTABLE: cannot locate symbol "avcodec_send_packet" referenced by "/data/data/com.termux/files/usr/libexec/mpv"...
page record for 0xb6e0404c was not found (block_size=64)
```

**Comment by fornwall** [comment]
@rqcy Can you run `apt update && apt upgrade` to ensure that you have the latest version of packages and try again?

**Comment by rqcy** [comment]
> @rqcy Can you run `apt update && apt upgrade` to ensure that you have
> the latest version of packages and try again?

Yes, I did and the problem persists.


$ apt show mpv
Package: mpv
Version: 0.22.0-2
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 1130 kB
Depends: ffmpeg, openal-soft
Homepage: https://mpv.io/
Download-Size: 368 kB
APT-Manual-Installed: yes
APT-Sources: http://termux.net stable/main arm Packages
Description: Command-line media player

**Comment by fornwall** [comment]
@rqcy Which device are you running and on which Android version? Are you running a custom rom?

**Comment by rqcy** [comment]
> @rqcy Which device are you running and on which Android version? Are
> you running a custom rom?

Nexus 4

Android 6.0.1

CyanogenMod 13.0 NIGHTLY from November

**Comment by strangel8p** [comment]
I'm getting the same error every time I try to launch mpv on Android 7.1.1 (CM 14.1). Attached are the relevant strace and catlog outputs.

[avcodec_send_packet_strace.txt](https://github.com/termux/termux-packages/files/679738/avcodec_send_packet_strace.txt)
[avcodec_send_packet_logcat.txt](https://github.com/termux/termux-packages/files/679739/avcodec_send_packet_logcat.txt)

**Comment by boay** [comment]
simmilar error:

-phone galaxy gt-i9505 ; -os  android 6-0.1 -cm 13.0-20161218-NIGHTLY-jfltexx

when i set mpv as videoplayer in mpsyt it responds:

CANNOT LINK EXECUTABLE: cannot locate symbol "avcodec_send_packet" referenced by "/data/data/com.termux/files/usr/libexec/mpv"...
page record for 0xb6dfe04c was not found (block_size=64)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/mps_youtube/commands/config.py", line 60, in setconfig
    message = config[key.upper()].set(val)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/mps_youtube/config.py", line 138, in set
    checked = self.check_fn(value)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/mps_youtube/config.py", line 247, in check_player
    util.load_player_info(player)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/mps_youtube/util.py", line 388, in load_player_info
    g.mpv_version = _get_mpv_version(player)
  File "/data/data/com.termux/files/usr/lib/python3.5/site-packages/mps_youtube/util.py", line 406, in _get_mpv_version
    o = subprocess.check_output([exename, "--version"]).decode()
  File "/data/data/com.termux/files/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/data/data/com.termux/files/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mpv', '--version']' returned non-zero exit status 1

**Comment by fornwall** [comment]
@rqcy @f0random @boay Does updating to the latest 0.24.0-1 version of mpv with `apt update && apt upgrade` fix the issue?

**Comment by f0random** [comment]
No, the problem persists on 0.24.0-1 for me

**Comment by fornwall** [comment]
@f0random Sorry, there was a mistake in the last update, can you try updating again (this time to 0.24.0-2) and see if that helps? Thanks for the help!

**Comment by f0random** [comment]
It works beautifully, thanks for your work

**Comment by rqcy** [comment]
Yes, it works now!

Thank you!

**Comment by ejaquay** [comment]
$ apt
CANNOT LINK EXECUTABLE "apt": cannot locate symbol "_Unwind_Resume" referenced by "/data/data/com.termux/files/usr/bin/apt"...
Aborted 

$ termux-info
Aborted     <-----------!
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.71-13527040 #1 SMP PREEMPT Wed May 16 17:00:07 KST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SAMSUNG-SM-G930A
Ph$

Now what?

**Comment by fornwall** [comment]
@ejaquay Run:

```sh
busybox wget http://termux.net/dists/stable/main/binary-aarch64/apt_1.4.8-5_aarch64.deb
dpkg -i apt_1.4.8-5_aarch64.deb
```

This fixes apt. Then run `pkg up` to retrieve the latest packages!

**Comment by jaikumarxD** [comment]
CANNOT LINK EXECUTABLE: cannot locate symbol "avcodec_alloc_frame" referenced by "/system/lib64/libffscanner_plugin.so"...
page record for 0x7f9ad0e390 was not found (block_size=64)



I'm running on marshmallow os and my phone is not rooted please help me with this

**Comment by GMANNMODS** [comment]
CANNOT LINK EXECUTABLE "cat": cannot locate symbol "iconv_open" referenced by "/data/data/com.termux/files/usr/bin/coreutils"...
Aborted

**Comment by GMANNMODS** [comment]
If anyone can help with the above issue I would greatly appreciate it... I'm running samsung smg930v NOT rooted kali linux nethunter installed... the problem happened after trying to install the metasploit framework... if that helps? Please help.

**Comment by GMANNMODS** [comment]
Oh I'm on 8.0 oreo

**Comment by yudi1999** [comment]
 php
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"...

**Comment by yudi1999** [comment]
 php
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"...
How to fix it?

**Comment by suresmart** [comment]
how to fix (cannot link executable:cannot locate symbol iconv_open referenced by php....)

**Comment by fornwall** [comment]
@yudi1999 @GMANNMODS Run `pkg up` to update packages!
