### ISSUE TITLE
Package request: dvisvgm

### ISSUE THREAD

**Issue by podsvirov** [termux/termux-packages#5722]
**Package description**

DVI to SVG converter

`dvisvgm` is a utility for TeX/LaTeX users.

It converts DVI, EPS, and PDF files to the XML-based scalable vector graphics format SVG.

The latest releases support standard DVI files (version 2) as well as DVI output created by pTeX in vertical mode (version 3), and XeTeX (versions 5 to 7, also known as XDV)

**Link to home page and sources**
1. Home page: https://dvisvgm.de/
2. Source code: https://github.com/mgieseki/dvisvgm

**Additional information**

I am a new user of the project and have not tried to compile any package yet.

But I am using a `texlive` distribution from `science-packages` and it looks great!

The `dvisvgm` package can be a great addition to get your documents in scalable vector graphics format.

**Comment by podsvirov** [comment]
Cc: @Grimler91

**Comment by podsvirov** [comment]
@ Grimler91, thanks for the quick response!

I tested this and it works great for me.

**Comment by Grimler91** [comment]
@podsvirov thanks for verifying!
