### ISSUE TITLE
CANNOT LINK EXECUTABLE "msgmerge": library "libomp.so" not found

### ISSUE THREAD

**Issue by chetnuy** [termux/termux-packages#5725]
**Problem description**

CANNOT LINK EXECUTABLE "msgmerge": library "libomp.so" not found
On Android 9

**Steps to reproduce**

~ $ msgmerge
CANNOT LINK EXECUTABLE "msgmerge": library "libomp.so" not found

**Expected behavior**

**Additional information**

~ $ apt show gettext-static
Package: gettext-static
Version: 0.21
Maintainer: Termux members @termux
Installed-Size: 1896 kB
Depends: gettext (= 0.21)
Homepage: https://www.gnu.org/software/gettext/
Download-Size: 351 kB
APT-Manual-Installed: yes
APT-Sources: https://termux.mentality.rip/termux-packages-24 stable/main aarch64 Packages
Description: Static libraries for gettext

~ $ apt show gettext
Package: gettext
Version: 0.21
Maintainer: Termux members @termux
Installed-Size: 15.0 MB
Depends: libc++, libiconv, pcre, liblzma, libxml2, libcroco, ncurses, libunistring, zlib
Breaks: gettext-dev
Replaces: gettext-dev
Homepage: https://www.gnu.org/software/gettext/
Download-Size: 1674 kB
APT-Manual-Installed: no
APT-Sources: https://termux.mentality.rip/termux-packages-24 stable/main aarch64 Packages
Description: GNU Internationalization utilities
```

```

**Comment by buttaface** [comment]
I updated gettext recently, looking into it.

**Comment by buttaface** [comment]
Fixed, reopen if any problems remain after updating.
