### ISSUE TITLE
Package: python add IPV6

### ISSUE THREAD

**Issue by beango1** [termux/termux-packages#573]
python and python3 is compiled without IPV6.  Consider changing the compile switch to leave IPV6 in.

**Comment by beango1** [comment]
i.e.: remove the switch --disable-ipv6 in the build.sh file
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" --build=$TERMUX_HOST_TUPLE --disable-ipv6 --with-system-ffi --without-ensurepip" #

**Comment by fornwall** [comment]
Thanks! The `--disable-ipv6` flag has been removed and updated packages are available:

- python version 3.5.2-6
- python2 version 2.7.12-4

Run `apt update && apt upgrade` to install updated packages.
