### ISSUE TITLE
[package request] OVMF  firmware for QEMU

### ISSUE THREAD

**Issue by oofnikj** [termux/termux-packages#5730]
**Package description**
TianoCore OVMF firmware for running EFI images with `qemu-system-x86_64`. This package would be equivalent to the Debian package `ovmf`, or the Arch Linux package `edk2-ovmf`.

Debian source package reference: https://packages.debian.org/source/sid/edk2
Arch PKGBUILD reference: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ovmf-git

**Link to home page and sources**
1. Home page: https://github.com/tianocore/tianocore.github.io/wiki
2. Source code: https://github.com/tianocore/edk2

**Additional information**
I tried to create a build manifest `packages/ovmf/build.sh` based on the Arch PKGBUILD as a reference and compile it in the docker builder image. There are some dependencies which are unavailable in the builder image which I installed manually: `nasm acpica`

But when I try to build it I get an error about the license probably because "BSD-2-Clause-Patent" is not in the default list of licenses:
```
builder@2de96385b476:~/termux-packages$ ./build-package.sh ovmf
termux - building ovmf for arch aarch64...
ERROR: No LICENSE file was installed for ovmf
```

Unsure how to proceed. Thanks for any help.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install ovmf
```
