### ISSUE TITLE
Package Request: mruby

### ISSUE THREAD

**Issue by go2null** [termux/termux-packages#5733]
**Package description**
mruby is a lightweight version of Ruby, made specifically for embedded systems. 

**Link to home page and sources**
1. Home page: https://mruby.org/
2. Source code: https://github.com/mruby/mruby

**Additional information**
* https://github.com/mruby/mruby/wiki/Supported-Platforms
* https://github.com/mruby/mruby/blob/master/doc/guides/compile.md

**Comment by kcubeterm** [comment]
I encountered following error while building with termux build system, 
```
aarch64-linux-android-ld: -Wl,-rpath=/data/data/com.termux/files/usr/lib: unknown option
```
This issue occurred only with build system (android toolchain)  whereas while building in termux this don't happens.
