### ISSUE TITLE
apt-shot (adds synaptic screenshot feature to termux / any cmd line) 

### ISSUE THREAD

**Issue by hltdev8642** [termux/termux-packages#5741]
**Package description**

Like in synaptic package manager, gets a screenshot for requested package and gives user prompt to either:
   (1) View in the terminal (using termimage)
   (2) View in external application (using xdg-open)

**Link to home page and sources**
1. Home page:
    https://gitlab.com/hltdev8642/apt-shot
2. Source code:
    https://gitlab.com/hltdev8642/apt-shot

**Additional information**

*Have you compiled or tried to compile the package on device?*
   Yes 

*If it didn't work then please provide the error you ran into.*

Works out-of-box, assuming you can install termimage (deliberately pick an in-terminal image viewer that is available on the main termux mirror, and used the more generic xdg-open for external viewing for maximum compatability). I have used it on other architectures too with no issues, as it's basically just a script that uses a few other (already available) packages to run.

**Additional information**

 I did read that you don't want to integrate any single-script packages to the main repository, however it does use several non-preinstalled/native binaries/scripts, so i was not too sure if it meets the criteria or not. I apologize if it doesn't as I wanted to at least try and share it anyways, since constantly having to reopen the browser to look up what a program will look like has always been a hassle (I've found) on a smartphone. This saves time, and is a relatively simple supplement to give apt the feature that comes built in with synaptic :-)  (however even synaptic doesn't view the screenshots in the terminal without an xwindow)

**Have you compiled or tried to compile the package on device?**

Yes seems to work without noticeable bugs or issues.

*If it didn't work then please provide the error you ran into.*
N/A

**Comment by xeffyr** [comment]
Packages consisting of simple script are not being accepted.
Also note that soon we switching to custom package management - https://github.com/termux/termux-packages/wiki/Termux-and-Android-10#how-this-issue-is-going-to-be-solved.

**Comment by hltdev8642** [comment]
> Packages consisting of simple script are not being accepted.
> Also note that soon we switching to custom package management - https://github.com/termux/termux-packages/wiki/Termux-and-Android-10#how-this-issue-is-going-to-be-solved.

@xeffyr, 
Its not completely relevant but if you don't mind my asking, is there a specific forum/location you can recommend for sharing 
scripts/programs such as this? 

I have made quite a few scripts/programs  that (I think at least) are pretty useful and would really like to increase my "online presence" somehow. (as I am graduating next semester with a BS in compsci and figure it would be helpful for experience)(and of course also, for that "warm fuzzy feeling inside" :-])

If  you don't have time to answer this then I completely understand. 

Termux has been a priceless gem for my daily workflow for years now, so at minimum I'd at least take the chance to say thank you! (for an app I often install on a new device before I even finish activating my simcard Lol 😂)

**Comment by xeffyr** [comment]
You can share scripts in https://www.reddit.com/r/termux/.
