### ISSUE TITLE
mosh command lacks upstream options

### ISSUE THREAD

**Issue by ssb22** [termux/termux-packages#5743]
Android 10, Termux 0.98, `pkg upgrade` done today.
The `mosh` command lacks some of upstream's options, including `--no-ssh-pty` (which is necessary when connecting to servers that run Dropbear instead of OpenSSH, see discussion on https://github.com/mobile-shell/mosh/issues/819 ) and `--experimental-remote-ip` (which is necessary when using mosh in conjunction with a background ssh with ControlPath, see discussion on https://github.com/mobile-shell/mosh/issues/24 ).  It appears that the upstream Perl script has been replaced by a binary, and not all options are supported by that binary.

Might it be possible to at least add support for `--no-ssh-pty`?  as looking at the upstream perl script, it seems this just causes the `-tt` option to be omitted from ssh options.  I'm not sure where to find the source for Termux's mosh binary, but I expect it should be straightforward to add that option.

`--experimental-remote-ip` on the other hand is more complex.  One option might be to depend on `perl` and run the upstream perl script, although some paths etc might still need changing.  But I suspect on an Android device the need for `--no-ssh-pty` to connect to Dropbear servers is likely more common than the need for `--experimental-remote-ip` to work with ControlPath, so implementing just `--no-ssh-pty` would at least help in most of these odd cases and should be relatively easy.

Thanks.

**Comment by xeffyr** [comment]
Have you tried `mosh.pl` instead of `mosh`.

**Comment by ssb22** [comment]
Thanks, I didn't realise `mosh.pl` was there.  Yes it works with `mosh.pl` (if I do `pkg install perl` first of course).  So perhaps all that needs to happen is for the "Unrecognised option" message from the `mosh` binary to add a hint that `mosh.pl` exists, for the benefit of users like me who didn't notice☺

**Comment by Vivraan** [comment]
@xeffyr Off-topic, but mosh complains that it only supports UTF-8 locales, and complains that Termux's default (en_US.UTF8) provides US-ASCII, and I've read from Issues that locale-gen isn't supported. How should I fix this?

**Comment by xeffyr** [comment]
@Vivraan Neither `mosh user@ipaddr` or `mosh.pl user@ipaddr` complain about UTF-8 error for me. I can successfully connect to remote host.

Ensure that both sides have UTF-8 locale and in Termux `LANG` is set to `en_US.UTF-8` exactly.

**Comment by Vivraan** [comment]
@Xeffyr Remote has `en_IN.UTF-8` locale correctly set, and Termux has `en_US.UTF-8` exactly.

**Comment by ssb22** [comment]
@Vivraan try `LC_ALL=en_IN.UTF-8  mosh.pl` (works for me with `en_GB` when the server doesn't have US locale)

**Comment by Vivraan** [comment]
> @Vivraan try `LC_ALL=en_IN.UTF-8 mosh.pl` (works for me with `en_GB` when the server doesn't have US locale)

I'll try `en_US.utf8` first.

**Comment by Vivraan** [comment]
I'll open another issue for this.

**Comment by xtkoba** [comment]
This is no longer an issue. The `--no-ssh-pty` option is enabled in our current `mosh` package.
