### ISSUE TITLE
Pandas installation error via pip

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#5744]
**Problem description**

```
https://termbin.com/uyuc
```
**Steps to reproduce**

```
LDFLAGS=" -lm -lcompiler_rt" pip3 install pandas --log t.log --no-use-pep517 --no-binary :all:
```
**Expected behavior**

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
libuv/stable 1.39.0 aarch64 [upgradable from: 1.38.1]
Android version:
10
Kernel build information:
Linux localhost 4.4.177-18671722 #1 SMP PREEMPT Wed Jul 8 15:57:59 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A750F

```
I have used --no-use-pep517 and --no-binary because pandas wheel fails to build as pandas did not follow pep517

**Comment by xeffyr** [comment]
It is just not compatible with Python 3.8 as uses some deprecated things.
You can try to install it from git, maybe with editing its setup files to remove `-Werror`.

**Comment by tathastu871** [comment]
> It is just not compatible with Python 3.8 as uses some deprecated things.
> You can try to install it from git, maybe with editing its setup files to remove `-Werror`.

I would try that. 
It seems that even when cython is installed it shows no module cython and failed to cythonize

**Comment by tathastu871** [comment]
> It is just not compatible with Python 3.8 as uses some deprecated things.
> You can try to install it from git, maybe with editing its setup files to remove `-Werror`.

Did not work. Pandas got install and import pandas has no error but no submodules. pandas show no attribute for all submodules. Non functional

**Comment by Grimler91** [comment]
@tathastu871 maybe open an issue in the pandas repository, would not surprise me if there are even open bug reports about python3.8 in their repository.

**Comment by tathastu871** [comment]
> @tathastu871 maybe open an issue in the pandas repository, would not surprise me if there are even open bug reports about python3.8 in their repository.

Already opened

**Comment by tathastu871** [comment]
> @tathastu871 maybe open an issue in the pandas repository, would not surprise me if there are even open bug reports about python3.8 in their repository.

Temporary solution:
Pandas 1.0.5 an older version seems to be working.

Still looking for workaround to use latest 1.1.1 version

**Comment by tathastu871** [comment]
> @tathastu871 maybe open an issue in the pandas repository, would not surprise me if there are even open bug reports about python3.8 in their repository.

Its not about python version. mainly related to api deprecation and non compatibility between pandas version > 1.0.5 and aarch64 architecture maybe with termux too because pandas 1.0.5 work properly with python3.8

**Comment by xeffyr** [comment]
> mainly related to api deprecation and non compatibility between pandas version > 1.0.5 and aarch64 architecture

No, it throws same error for x86 32bit Termux and I'm sure it will be same for x86_64 and ARM Termux, didn't tested.

**Comment by xeffyr** [comment]
Same on x86_64:
<details>
<summary>Failure log (click to expand)</summary>
<pre>
  building 'pandas.io.sas._sas' extension
  creating build/temp.linux-x86_64-3.8/pandas/io
  creating build/temp.linux-x86_64-3.8/pandas/io/sas
  x86_64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DNPY_NO_DEPRECATED_API=0 -I/data/data/com.termux/files/usr/tmp/pip-build-env-efbdeefr/overlay/lib/python3.8/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.8 -c pandas/io/sas/sas.c -o build/temp.linux-x86_64-3.8/pandas/io/sas/sas.o -Werror
  pandas/io/sas/sas.c:19940:3: error: 'tp_print' is deprecated [-Werror,-Wdeprecated-declarations]
    0, /*tp_print*/
    ^
  /data/data/com.termux/files/usr/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
      Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
      ^
  /data/data/com.termux/files/usr/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  pandas/io/sas/sas.c:20129:3: error: 'tp_print' is deprecated [-Werror,-Wdeprecated-declarations]
    0, /*tp_print*/
    ^
  /data/data/com.termux/files/usr/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
      Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
      ^
  /data/data/com.termux/files/usr/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  pandas/io/sas/sas.c:20248:3: error: 'tp_print' is deprecated [-Werror,-Wdeprecated-declarations]
    0, /*tp_print*/
    ^
  /data/data/com.termux/files/usr/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
      Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
      ^
  /data/data/com.termux/files/usr/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  pandas/io/sas/sas.c:20509:3: error: 'tp_print' is deprecated [-Werror,-Wdeprecated-declarations]
    0, /*tp_print*/
    ^
  /data/data/com.termux/files/usr/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
      Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
      ^
  /data/data/com.termux/files/usr/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  pandas/io/sas/sas.c:20655:3: error: 'tp_print' is deprecated [-Werror,-Wdeprecated-declarations]
    0, /*tp_print*/
    ^
  /data/data/com.termux/files/usr/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
      Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
      ^
  /data/data/com.termux/files/usr/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  5 errors generated.
  building 'pandas._libs.json' extension
  creating build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson
  creating build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/python
  creating build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/lib
  x86_64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/src/ujson/python -Ipandas/_libs/src/ujson/lib -Ipandas/_libs/src/datetime -I/data/data/com.termux/files/usr/tmp/pip-build-env-efbdeefr/overlay/lib/python3.8/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.8 -c pandas/_libs/src/ujson/python/ujson.c -o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/python/ujson.o -D_GNU_SOURCE -Werror
  x86_64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/src/ujson/python -Ipandas/_libs/src/ujson/lib -Ipandas/_libs/src/datetime -I/data/data/com.termux/files/usr/tmp/pip-build-env-efbdeefr/overlay/lib/python3.8/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.8 -c pandas/_libs/src/ujson/python/objToJSON.c -o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/python/objToJSON.o -D_GNU_SOURCE -Werror
  x86_64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/src/ujson/python -Ipandas/_libs/src/ujson/lib -Ipandas/_libs/src/datetime -I/data/data/com.termux/files/usr/tmp/pip-build-env-efbdeefr/overlay/lib/python3.8/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.8 -c pandas/_libs/src/ujson/python/date_conversions.c -o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/python/date_conversions.o -D_GNU_SOURCE -Werror
  x86_64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/src/ujson/python -Ipandas/_libs/src/ujson/lib -Ipandas/_libs/src/datetime -I/data/data/com.termux/files/usr/tmp/pip-build-env-efbdeefr/overlay/lib/python3.8/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.8 -c pandas/_libs/src/ujson/python/JSONtoObj.c -o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/python/JSONtoObj.o -D_GNU_SOURCE -Werror
  x86_64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/src/ujson/python -Ipandas/_libs/src/ujson/lib -Ipandas/_libs/src/datetime -I/data/data/com.termux/files/usr/tmp/pip-build-env-efbdeefr/overlay/lib/python3.8/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.8 -c pandas/_libs/src/ujson/lib/ultrajsonenc.c -o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/lib/ultrajsonenc.o -D_GNU_SOURCE -Werror
  x86_64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/src/ujson/python -Ipandas/_libs/src/ujson/lib -Ipandas/_libs/src/datetime -I/data/data/com.termux/files/usr/tmp/pip-build-env-efbdeefr/overlay/lib/python3.8/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.8 -c pandas/_libs/src/ujson/lib/ultrajsondec.c -o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/lib/ultrajsondec.o -D_GNU_SOURCE -Werror
  x86_64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/src/ujson/python -Ipandas/_libs/src/ujson/lib -Ipandas/_libs/src/datetime -I/data/data/com.termux/files/usr/tmp/pip-build-env-efbdeefr/overlay/lib/python3.8/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.8 -c pandas/_libs/tslibs/src/datetime/np_datetime.c -o build/temp.linux-x86_64-3.8/pandas/_libs/tslibs/src/datetime/np_datetime.o -D_GNU_SOURCE -Werror
  x86_64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/src/ujson/python -Ipandas/_libs/src/ujson/lib -Ipandas/_libs/src/datetime -I/data/data/com.termux/files/usr/tmp/pip-build-env-efbdeefr/overlay/lib/python3.8/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/include/python3.8 -c pandas/_libs/tslibs/src/datetime/np_datetime_strings.c -o build/temp.linux-x86_64-3.8/pandas/_libs/tslibs/src/datetime/np_datetime_strings.o -D_GNU_SOURCE -Werror
  x86_64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -landroid-support -L/home/builder/.termux-build/_cache/android-r21d-api-24-v3/sysroot/usr/lib64 -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -landroid-support -L/home/builder/.termux-build/_cache/android-r21d-api-24-v3/sysroot/usr/lib64 build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/python/ujson.o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/python/objToJSON.o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/python/date_conversions.o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/python/JSONtoObj.o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/lib/ultrajsonenc.o build/temp.linux-x86_64-3.8/pandas/_libs/src/ujson/lib/ultrajsondec.o build/temp.linux-x86_64-3.8/pandas/_libs/tslibs/src/datetime/np_datetime.o build/temp.linux-x86_64-3.8/pandas/_libs/tslibs/src/datetime/np_datetime_strings.o -L/data/data/com.termux/files/usr/lib -lpython3.8 -o build/lib.linux-x86_64-3.8/pandas/_libs/json.cpython-38.so
  error: command 'x86_64-linux-android-clang' failed with exit status 1
</pre>
</details>

**Comment by xeffyr** [comment]
Seems to be related to https://github.com/cython/cython/issues/3474.

**Comment by xeffyr** [comment]
Successfully installed pandas with CFLAGS:
```
$ export CFLAGS="-Wno-deprecated-declarations -Wno-unreachable-code"
$ pip install pandas
Collecting pandas
  Using cached pandas-1.1.1.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Processing ./.cache/pip/wheels/df/b2/64/111c431ca7f7d49afb42126b7351fe1a4894803d75026360de/numpy-1.19.1-cp38-cp38-linux_x86_64.whl
Collecting pytz>=2017.2
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: pandas
  Building wheel for pandas (PEP 517) ... done
  Created wheel for pandas: filename=pandas-1.1.1-cp38-cp38-linux_x86_64.whl size=26279133 sha256=e99561561fc4a2b5465f9397a3775a9e3de25212eca84adb912cf069183bcd50
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/76/eb/34/f05e707dd6da05d95fd42fc4b37caafff0ab5f6e5bbfda7bfa
Successfully built pandas
Installing collected packages: numpy, pytz, six, python-dateutil, pandas
Successfully installed numpy-1.19.1 pandas-1.1.1 python-dateutil-2.8.1 pytz-2020.1 six-1.15.0
```

Importing works fine:
```
$ python
Python 3.8.5 (default, Jul 24 2020, 12:36:40) 
[Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> help(pandas)
Help on package pandas:

NAME
    pandas

DESCRIPTION
    pandas - a powerful data analysis and manipulation library for Python
    =====================================================================
    
    **pandas** is a Python package providing fast, flexible, and expressive data
    structures designed to make working with "relational" or "labeled" data both
    easy and intuitive. It aims to be the fundamental high-level building block for
    doing practical, **real world** data analysis in Python. Additionally, it has
    the broader goal of becoming **the most powerful and flexible open source data
    analysis / manipulation tool available in any language**. It is already well on
    its way toward this goal.
...
```

I'm closing the issue.

**Comment by msurendranath** [comment]
Struggling for the last 2 weeks for this on Oneplu7pro with Termux. This post helped me to successfully install pandas. Another issue cropped up as well for which solution was provided by python build process.

**Comment by ronnac** [comment]
Solved my problem, too. Thanks!

**Comment by anzhi0708** [comment]
Installed using `export CFLAGS="-Wno-deprecated-declarations -Wno-unreachable-code"` but could not import, throws error telling me something was broken. Tried to build from source code, but multiple errors showed up like `code will never be executed` or `Unreachable code`. Armv7 32bit with numpy scipy matplotlib jupyter libgfortran5 gcc-10 clang cython installed.

**Comment by Nai-mul** [comment]
export CFLAGS="-Wno-deprecated-declarations -Wno-unreachable-code"
~ $ pip install pandas

import numpy
  ModuleNotFoundError: No module named 'numpy'

but i have installed numpy 1.20.3

**Comment by Forneck** [comment]
I got the same error, got numpy installed through page install but numpy fails to detect it. Anyone found a solution for this?

**Comment by anzhi0708** [comment]
```
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                       #
#   How I installed Pandas on a 32 bit armv7l Android   #
#                                                       #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

apt install build-essential
apt install git make

apt install libcompiler-rt  

# pytz is pandas's dependency，
# cython is also required

pip install pytz cython
pip install setuptools --upgrade

#  Installing Pandas

# # 1: Using pip
# ** Note: *No output* will be shown on terminal **
# ** and you need to wait for 1-2 hours **
# ** depend on your phone's hardware **

export CFLAGS=" -Wno-deprecated-declarations -Wno-unreachable-code" 
export LDFLAGS=" -lm -lcompiler_rt"
pip install pandas

#  # 2: Download source code and compile it by yourself
# There will be a LOT of outputs on your terminal so you
# will get a general idea how things went
# it's more comforting sometimes

cd $PREFIX/lib/python3.9/site-packages/
git clone https://github.com/pandas-dev/pandas.git
cd pandas
export CFLAGS=" -Wno-deprecated-declarations -Wno-unreachable-code" 
export LDFLAGS=" -lm -lcompiler_rt"
make
# Now take a nap
# Do not delete the source code folder after you're done

# By the way
# if you failed installing pyzmq, type: CC=clang && pip install pyzmq

# I originally posted my article here: https://zhuanlan.zhihu.com/p/146555866
```
