### ISSUE TITLE
Ifconfig permission denied 

### ISSUE THREAD

**Issue by Mahroof313** [termux/termux-packages#5748]
I need one help that 
Ifconfig command is not running in my phone it showing
![Screenshot_20200828_080318](https://user-images.githubusercontent.com/70357348/91514940-a4f74c00-e905-11ea-9f9b-e26a3c1ede56.jpg)

Warning: cannot open /proc/net/dev (Permission denied). Limited output.lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536        inet 127.0.0.1  netmask 255.0.0.0        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)rmnet0: flags=193<UP,RUNNING,NOARP>  mtu 1400        inet 100.102.150.188  netmask 255.255.255.255        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

**Comment by xeffyr** [comment]
Modern Android OS versions restrict access to `/proc/net`. You need to root your device to use `ifconfig` now.

That's a won'tfix as Termux can't overcome the SELinux restrictions.

**Comment by Mahroof313** [comment]
Why it restricted. It have any problems? -------- Original message --------From: Leonid Pliushch <notifications@github.com>Date: Fri, 28 Aug, 2020, 5:21 pmTo: termux/termux-packages <termux-packages@noreply.github.com>Cc: Mahroof313 <mahroofmajju313@gmail.com>, Author <author@noreply.github.com>Subject: Re: [termux/termux-packages] Ifconfig permission denied  (#5748)
Modern Android OS versions restrict access to /proc/net. You need to root your device to use ifconfig now.
That's a won'tfix as Termux can't overcome the SELinux restrictions.

**Comment by xeffyr** [comment]
> Why it restricted. It have any problems?

Access to /proc/net was restricted because it allows any application to read the list of IPs/domains you visiting and send this data to third-parties. So that's a privacy hole and Android 10+ has fixed it.

**Comment by Mahroof313** [comment]
Finally rooter is not safe is it? And is the rooter must to use termux? -------- Original message --------From: Leonid Pliushch <notifications@github.com>Date: Fri, 28 Aug, 2020, 8:37 pmTo: termux/termux-packages <termux-packages@noreply.github.com>Cc: Mahroof313 <mahroofmajju313@gmail.com>, Author <author@noreply.github.com>Subject: Re: [termux/termux-packages] Ifconfig permission denied  (#5748)

Why it restricted. It have any problems?

Access to /proc/net was restricted because it allows any application to read the list of IPs/domains you visiting and send this data to third-parties. So that's a privacy hole and Android 10+ has fixed it.
