### ISSUE TITLE
Package request : Httpie

### ISSUE THREAD

**Issue by pelaio** [termux/termux-packages#5749]
**Package description**
HTTPie (pronounced aitch-tee-tee-pie) is a command-line HTTP client. Its goal is to make CLI interaction with web services as human-friendly as possible. HTTPie is designed for testing, debugging, and generally interacting with APIs & HTTP servers. The http & https commands allow for creating and sending arbitrary HTTP requests. They use simple and natural syntax and provide formatted and colorized output.

**Link to home page and sources**
Home page: https://httpie.org/
Source code: https://github.com/httpie/httpie

**Comment by xeffyr** [comment]
`pip install httpie` doesn't work?
We do not package python modules, especially which can be easily installed with `pip`.
