### ISSUE TITLE
Support for launching Android apps from the command line

### ISSUE THREAD

**Issue by nonnymoose** [termux/termux-packages#575]
I just installed Termux today, and was blown away as well. :)

I installed python, then youtube-dl, then mps-youtube and was very impressed. Unfortunately, I don't seem to be able to play youtube videos using mpsyt.

Do you think you could add support (probably in the api package) for launching Android apps via the command-line in Termux?

Then I could have mpsyt launch the vlc app.
**And that would be absolutely amazing.** :)

If I'm stupid and there's already a solution to _my_ problem, could you try to add such a feature anyway? It'd be really useful for scripting.

**Comment by Neo-Oli** [comment]
You should be able to open videos with termux-share

`termux-share video.mp4`

**Comment by nonnymoose** [comment]
@Neo-Oli That should work in almost all cases.
(Except for mine, ufortunately.)
How can I attempt to share a url? None of my usual url-sharing programs are coming up. ;)

**Comment by fornwall** [comment]
@nonnymoose Does `termux-open-url` work for opening an URL?

Perhaps these two tools could be consolidated into one.

**Comment by nonnymoose** [comment]
@fornwall  Thanks, that worked perfectly!

**Comment by jatinkrmalik** [comment]
Perfect solution! But just wanted to know how can I open my File explorer (Solid file explorer in my case) from the terminal itslef. I tried doing `termux-open --chooser ./` but it didn't work.

**Comment by nonnymoose** [comment]
@newtontechkid They were asking about launching an _Android_ file manager, not one in termux.
