### ISSUE TITLE
Htop not working

### ISSUE THREAD

**Issue by lavish440** [termux/termux-packages#5750]
Htop stopped working after today's update. 
Here is the output

    $htop

    htop 3.0.0 aborting. Please report bug at https://htop.dev
    Aborted

**Comment by xeffyr** [comment]
`rm -rf ~/.config/htop` and try again.
Also note that `htop` doesn't work on most devices due to SELinux.

**Comment by lavish440** [comment]
> `rm -rf ~/.config/htop` and try again.
> Also note that `htop` doesn't work on most devices due to SELinux.
> 
> P.S. I don't have any issues with it. (Lineage OS / Android 10 / AArch64)

The path doesn't exist.

**Comment by lavish440** [comment]
It was working perfectly until today I updated htop. 
OS - Android 10
Phone- Xiaomi Mi 9 (K20)

**Comment by xeffyr** [comment]
Then post log file of `strace`:
```
strace -fv -o htop.log -s 2000 htop
```
and send htop.log to some pastebin.

**Comment by lavish440** [comment]
> Then post log file of `strace`:
> 
> ```
> strace -fv -o htop.log -s 2000 htop
> ```
> 
> and send htop.log to some pastebin.

Here is the log.

**Comment by xeffyr** [comment]
It crashes for you after trying to access `/proc/stat`.
```
4050  openat(AT_FDCWD, "/proc/stat", O_RDONLY) = -1 EACCES (Permission denied)
4050  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xc0} ---
```
As I wrote - it doesn't work (may open but not work!!!) on most devices. Without `/proc/stat` it can't get CPU statistics to display. That's generally unsupported behavior which we tried to patch it in 2.2.0 so it can at least open, not sure whether this is possible on v3.0.0. Maybe it is more dependent on `/proc/stat` now.

**Comment by xeffyr** [comment]
> As I wrote - it doesn't work (may open but not work!!!) on most devices

See https://github.com/termux/termux-packages/issues/4826 to know what I mean exactly.

**Comment by xeffyr** [comment]
Changed it to give more descriptive message instead of just crash. Rest is wontfix.

**Comment by Querela** [comment]
Only asking:
Is it possible to downgrade the version back to 2.2.something, so it will at least work for most of not all users that use current Android versions?
And just have the 3.0.0 version in the root repository?

I do not want to wrongly state that most users of Termux have root or not. But having a package in the base repository that requires root to work/access resources makes no sense to me. For this the root repository exists, doesn't it? Or is it an issue of having the wrong Android version? (Stock on Xiaomi Mi 9)

---

> Also note that htop **doesn't work** on **most devices** due to SELinux.

^ I assume the new version?

> * Root:     pkg install root-repo

---

My main use-case was the better process listing (hierarchy, stats etc.) and easier killing of processes.
And in the old version most things worked as far as I can remember.

**Comment by xeffyr** [comment]
@Querela Ok, we can have 2 versions of htop. Something like `htop` in root-repo and `htop-legacy` (v2.x) in normal.

**Comment by Querela** [comment]
Thanks, and that's even better as it's clear what's happening. :-)

(And much thanks for bringing the software (not just htop) to Termux in the first place.)
