### ISSUE TITLE
cu (uucp) package request

### ISSUE THREAD

**Issue by inkstain** [termux/termux-packages#5751]
**Package description**

`cu`

Serial cli terminal app that typically is bundled in uucp package

Very useful for scripting projects!

**Link to home page and sources**
1. Home page: https://www.airs.com/ian/uucp.html
2. Source code: ftp://ftp.gnu.org/pub/gnu/uucp/uucp-1.07.tar.gz

> Not sure if the above are the best resources for this. 

**Additional information**

There used to be a termux package (I do not recall if it was just `cu` or the entire `uucp` but for some reason it was pulled. I have a largish number of scripts I use on my desktop that I ported many over to the phones for quick use, many rely on cu and after I was recently forced to reinstall termux on my older phone I no longer have cu. Newer phone never had it.

Thanks!

**Comment by buttaface** [comment]
Available now, `pkg install uucp`, reopen if there's a problem.
