### ISSUE TITLE
Package Request: netcat-openbsd

### ISSUE THREAD

**Issue by dkoao** [termux/termux-packages#5754]
**Package description**
netcat-openbsd is a very useful tool for all sorts of networking magic, for example, it can be used as an HTTP client, or as an SSH ProxyCommand ([The Tor Project recommends netcat-openbsd as the netcat variant of choice to use with SSH](https://trac.torproject.org/projects/tor/wiki/doc/TorifyHOWTO/ssh)).

**Link to home page and sources**
1. Home page: https://packages.debian.org/sid/netcat-openbsd
2. Source code: https://salsa.debian.org/debian/netcat-openbsd (Upstream: https://github.com/openbsd/src/tree/master/usr.bin/nc)

Here's how it's packaged among distributions:

- Arch Linux: https://github.com/archlinux/svntogit-community/blob/packages/openbsd-netcat/trunk/PKGBUILD

- Alpine Linux: https://git.alpinelinux.org/aports/tree/main/netcat-openbsd?h=master

**Additional information**
Have you compiled or tried to compile the package on device? No.

**Comment by normanr** [comment]
See https://github.com/termux/termux-packages/issues/162 for history. It seems that the openbsd-netcat was more work to package than ncat from nmap.

**Comment by 157255** [comment]
> **وصف الحزمة**
> netcat-openbsd هي أداة مفيدة جدًا لجميع أنواع سحر الشبكات ، على سبيل المثال ، يمكن استخدامها كعميل HTTP ، أو كبروتوكول SSH ProxyCommand ( [يوصي مشروع Tor بـ netcat-openbsd باعتباره البديل netcat المفضل للاستخدام مع SSH](https://trac.torproject.org/projects/tor/wiki/doc/TorifyHOWTO/ssh) ).
> 
> **الارتباط بالصفحة الرئيسية والمصادر**
> 
> 1. الصفحة الرئيسية: https://packages.debian.org/sid/netcat-openbsd
> 2. كود المصدر: https://salsa.debian.org/debian/netcat-openbsd (Upstream: https://github.com/openbsd/src/tree/master/usr.bin/nc )
> 
> إليك كيفية تعبئتها بين التوزيعات:
> 
> * قوس Linux: https://github.com/archlinux/svntogit-community/blob/packages/openbsd-netcat/trunk/PKGBUILD
> * Alpine Linux: [https://git.alpinelinux.org/aports/tree/main/netcat-openbsd؟](https://git.alpinelinux.org/aports/tree/main/netcat-openbsd?h=master)
> 
> **معلومات إضافية**
> هل جمعت أو حاولت تجميع الحزمة على الجهاز؟ لا.

ما بيشتغل معي

**Comment by dkoao** [comment]
Thank you so much for adding this package! I appreciate this a lot.
