### ISSUE TITLE
Package request: more-itertools

### ISSUE THREAD

**Issue by normanr** [termux/termux-packages#5756]
**Package description**
Python package with more routines for operating on iterables, beyond itertools

**Link to home page and sources**
1. Home page: https://more-itertools.rtfd.io/
2. Source code: https://github.com/more-itertools/more-itertools
3. Debian package: https://packages.debian.org/source/buster/more-itertools

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

I have not. I expect the Debian package will work without any complications because the package is also available via pip.

**Comment by Grimler91** [comment]
Hi, 

We generally do not package python programs that can be installed through pip (or other package managers like cpan, gem, npm), mostly because we do not have the manpower to maintain a lot of packages. 

If more-itertools requires lots of patches to install and/or work in termux then this could be reconsidered.

**Comment by normanr** [comment]
ack, I used pip to install it and it works great. Perhaps some documentation could be updated to mention that pip is preferred to packaging? (I've always thought the Debian preferred packaging to pip, so it would be nice to call out the termux is the opposite).

**Comment by xeffyr** [comment]
> Perhaps some documentation could be updated to mention that pip is preferred to packaging?

* https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests
* https://wiki.termux.com/wiki/Package_Management#Package_requests

**Comment by normanr** [comment]
Those are great links, could you add them to [.github/ISSUE_TEMPLATE/package_request.md](../edit/master/.github/ISSUE_TEMPLATE/package_request.md)
