### ISSUE TITLE
Make ./build-package.sh download and not build from source dependencies by default?

### ISSUE THREAD

**Issue by doronbehar** [termux/termux-packages#5760]
I'd like to contribute a certain package to this collection. I noticed when running:

```
./scripts/run-docker.sh ./build-package.sh -a arm gitstatus
```

That it downloaded llvm's source code, as well as binutils and zlib and built them and installed them for the architecture I requested. It surprises me that there's no binary cache for that - I would like to spare my old PC from building such software.

**Comment by doronbehar** [comment]
It is possible, I didn't read the wiki page well. I'm surprised though that this isn't the default..

**Comment by xeffyr** [comment]
This shouldn't be default.
