### ISSUE TITLE
Issues having local wifi connection (with no internet) and GSM (with internet)

### ISSUE THREAD

**Issue by jah0wl** [termux/termux-packages#5762]
**Problem description**

Using node.js on Termux, I am connecting to a WebSocket over internet via GSM and to a WiFi LED controller via local AP with no internet connection using datagram. The ws connection works well, but the connection to the LED seems not to work. ITOH, if my AP has the internet connection, I can connect to the LED controller without problems. As well as broadcast operations to 255.255.255.255 are not working having the GSM and WiFi (with no internet connection) connected. With nodejs on Windows, work as expected.

**Steps to reproduce**

Connected on GSM, the ws is ok and the datagram doesn't connect. Once I take the GSM down, the ws disconnect (as expected) and the datagram now connects.

**Expected behavior**

**Additional information**

It Seems that has some issues routing when needs to use different network adapters. Using only one for everything seems to work fine.
```

```

**Comment by xeffyr** [comment]
Sorry, but Termux doesn't manage networking on devices. It is just an application. Network routing, iptables, etc is configured by Android OS.

Nothing can be done on Termux side.
