### ISSUE TITLE
Não consigo baixar nada o npm

### ISSUE THREAD

**Issue by theryston** [termux/termux-packages#5764]
**Problem description** 
Não então em qualquer progeto de dígito npm install (nome do módulo) e da erro

**Additional information**
Já baixei o nodejs

```
![Screenshot_20200902-134018_Termux](https://user-images.githubusercontent.com/69520844/92011749-e6329600-ed21-11ea-9083-9d186b5f9d19.jpg)

```

**Comment by kcubeterm** [comment]
Don't performing things in external or /sdcard directory, move ur projects in termux home directory and then try.

And please use English, if u don't know , use Google translator

**Comment by theryston** [comment]
sorry for writing in portuguese (although i know english).

But thank you very much I managed to install the node modules !!!
