### ISSUE TITLE
Package: Deno

### ISSUE THREAD

**Issue by d3ck** [termux/termux-packages#5776]
**Package description**
Deno is a simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust.

**Link to home page and sources**
1. Home page: https://deno.land/
2. Source code: https://github.com/denoland/deno

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by kcubeterm** [comment]
Close this issue: https://github.com/termux/termux-packages/issues/5306

**Comment by aarav19** [comment]
E: Unable to locate package git
$ git clone https://github.com/evait-security/weeman.git
The program git is not installed. Install it by executing:
 pkg install git
$ pkg install git
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package git
$ locate pkg
The program locate is not installed. Install it by executing:
 pkg install mlocate
$ pkg install mlocate
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package mlocate
$

**Comment by aarav19** [comment]
E: Unable to locate package git
$ git clone https://github.com/evait-security/weeman.git
The program git is not installed. Install it by executing:
 pkg install git
$ pkg install git
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package git
$ locate pkg
The program locate is not installed. Install it by executing:
 pkg install mlocate
$ pkg install mlocate
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package mlocate
$
i cannot locate my mlocate ..
