### ISSUE TITLE
pandas 1.1.1 for Python 3.8.5 does not build

### ISSUE THREAD

**Issue by stuart-little** [termux/termux-packages#5778]
**Problem description**

I am on `Android 10` `aarch64`, trying to install [Pandas 1.1.1](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html)  with `pip`. 

The installation fails in the wheel-building phase. You can see the full output [in this pastebin](https://termbin.com/vye6) .

**Steps to reproduce**

Run

```
pip install pandas
```

**Expected behavior**

Installed `Pandas` package.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/science.list.bak
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# sources.list.d/game.list.bak
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.179-perf+ #1 SMP PREEMPT Fri Jul 17 19:30:50 CST 2020 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6013

```
---
The pastebin lines are gigantic. As a short summary, I'm seeing numerous instances of 

```
pandas/_libs/indexing.c:2758:3: error: 'tp_print' is deprecated [-Werror,-Wdeprecated-declarations]
```
and 

```
pandas/_libs/algos.c:81785:3: error: code will never be executed [-Werror,-Wunreachable-code]
```
In fact, [here](https://termbin.com/nayo) is a much smaller pastebin of just the log files containing `error:`. They are all more or less variants of the two above.

**Comment by xeffyr** [comment]
Read https://wiki.termux.com/wiki/Python#Python_module_installation_tips_and_tricks - you need extra CFLAGS.

This is **upstream issue**. See https://github.com/cython/cython/issues/3474 and https://github.com/pandas-dev/pandas/issues/33239. Nothing to do with Termux.

**Comment by stuart-little** [comment]
Thank you, and apologies for not looking into it more carefully beforehand:

```
export CFLAGS="-Wno-deprecated-declarations -Wno-unreachable-code"
pip install pandas
```
worked fine.
