### ISSUE TITLE
I accidentally turned off the data when I was downloading Kali Linux in termux but when I turned it on the downloading process not restarted i searched many times on internet but I can't find how to restart the installation process

### ISSUE THREAD

**Issue by 1572007** [termux/termux-packages#5780]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by Grimler91** [comment]
See for example https://stackoverflow.com/questions/19728930/how-to-resume-interrupted-download-automatically-in-curl
