### ISSUE TITLE
CANNOT LINK EXECUTABLE Error

### ISSUE THREAD

**Issue by DiscordGalaxyCookie** [termux/termux-packages#5781]
I Was Working On A Discord JavaScript Bot And This Is What The Terminal Said "CANNOT LINK EXECUTABLE "/data/data/com.astrosohu/files/usr/bin/bash": library "libreadline.so.8" not found"

>
![Screenshot_2020-09-06-23-49-17](https://user-images.githubusercontent.com/70880201/92356825-9d6d3b00-f09b-11ea-800b-bd99481f8eda.jpg)
![Screenshot_2020-09-06-23-49-20](https://user-images.githubusercontent.com/70880201/92356831-9e9e6800-f09b-11ea-9146-bef1e542f0e4.jpg)

**Comment by Grimler91** [comment]
Well either the [rpath compiled into bash](https://github.com/termux/termux-packages/blob/145bdc4830b5d8e93184a8b1f1d7d3b4de9254f3/scripts/build/termux_step_setup_toolchain.sh#L27) is wrong, or you have not re-compiled libreadline against your new prefix.

Hard for us to know as we don't know anything about your setup or what you have done..
