### ISSUE TITLE
E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by phamt8611** [termux/termux-packages#5782]
Hi everyone, I am using proot-distro, the distribution I am using is Ubuntu-20.04.

When I "apt install xfce4", running for a long time, this error appears, does anyone know how to handle it?

E: Sub-process / usr / bin / dpkg returns error code (1)

**Comment by Grimler91** [comment]
Please provide more information, use the bug-report template: https://github.com/termux/termux-packages/issues/new?template=bug_report.md

**Comment by xeffyr** [comment]
https://github.com/termux/proot-distro/issues/11
