### ISSUE TITLE
matplotlib 3.3.1 does not build with python 3.8.5 and pip

### ISSUE THREAD

**Issue by stuart-little** [termux/termux-packages#5787]
**Problem description**

I am trying to install `matplotlib 3.3.1` with `pip` (`aarch64` and `Android 10`) following the special instructions [here](https://wiki.termux.com/wiki/Python#Python_module_installation_tips_and_tricks). 

The recommended
```
export LDFLAGS=" -lm -lcompiler_rt"
pip install matplotlib
```

fails with [this](https://termbin.com/qi9m) full output. Summary: multiple errors of the form

```
build/temp.linux-aarch64-3.8/src/checkdep_freetype2.o: file not recognized: file format not recognized
```

and

```
build/temp.linux-aarch64-3.8/src/_contour.o: file not recognized: file format not recognized
```

and 

```
build/temp.linux-aarch64-3.8/src/qhull_wrap.o: file not recognized: file format not recognized
```

**Steps to reproduce**

Simply run

```
export LDFLAGS=" -lm -lcompiler_rt"
pip install matplotlib
```
after ensuring you have `freetype` and `libpng` installed.

**Expected behavior**

`matplotlib` installed successfully.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/science.list.bak
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# sources.list.d/game.list.bak
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.179-perf+ #1 SMP PREEMPT Fri Jul 17 19:30:50 CST 2020 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6013
```

**Comment by Grimler91** [comment]
Currectly testing on my android 10, aarch64 device. Have you tried without setting LDFLAGS?

**Comment by stuart-little** [comment]
@Grimler91 I had tried without `LDFLAGS` before and did again now: the result is the same, with full log [here](https://termbin.com/5t0xk).

As you can see, again errors of the type

```
build/temp.linux-aarch64-3.8/src/_ttconv.o: file not recognized: file format not recognized
```

**Comment by Grimler91** [comment]
I can't reproduce it unfortunately, and I haven't seen this type of error before. You could maybe try git clone'ing the matplotlib repository and building from the source

**Comment by stuart-little** [comment]
I've done just that: cloned their repo and tried again, with absolutely no change.

Opened an [issue](https://github.com/matplotlib/matplotlib/issues/18443#issue-697163699) there too.

**Comment by stuart-little** [comment]
An update:

Inspired by [other reports](https://github.com/numba/llvmlite/issues/54) of similar errors apparently resulting from `LLVM` choking on `-flto`, I installed the `binutils-gold` package and did

```
export LDFLAGS=" -lm -lcompiler_rt -fuse-ld=gold"
```
before trying again. The original errors are gone now! Instead, I have [new ones](https://termbin.com/zfar):

```
/data/data/com.termux/files/usr/bin/ld.gold: error: build/temp.linux-aarch64-3.8/src/checkdep_freetype2.o:1:3: invalid character                               /data/data/com.termux/files/usr/bin/ld.gold: error: build/temp.linux-aarch64-3.8/src/checkdep_freetype2.o:1:3: syntax error, unexpected $end                   /data/data/com.termux/files/usr/bin/ld.gold: error: build/temp.linux-aarch64-3.8/src/checkdep_freetype2.o: not an object or archive                            /data/data/com.termux/files/usr/bin/ld.gold: error: build/temp.linux-aarch64-3.8/src/mplutils.o:1:3: invalid character                                         /data/data/com.termux/files/usr/bin/ld.gold: error: build/temp.linux-aarch64-3.8/src/mplutils.o:1:3: syntax error, unexpected $end
```
etc. etc.

**Comment by stuart-little** [comment]
It [appears](https://github.com/matplotlib/matplotlib/issues/18443#issuecomment-689899263) to have been resolved:

`LLVM` has [issues](https://llvm.org/docs/GoldPlugin.html) with `LTO`, so as instructed in the other thread, after cloning the [matplotlib repo](https://github.com/matplotlib/matplotlib) I added a `setup.cfg` file in the main directory containing the line

```
enable_lto = False
```
and then ran
```
pip install .
```
in that directory. Still curious as to how this works fine for you @Grimler91

**Comment by Grimler91** [comment]
I'm using clang as well. Did not have to set LDFLAGS at all for it to compile. 

Maybe it is a different somewhere else in the environment. I have not tried in a fresh installation.

**Comment by stuart-little** [comment]
I see. Well, it sounds like we won't sort out that matter, but as far as this issue goes I think it's resolved and can be closed: 

The solution above, that I was pointed to by the folks at [matplotlib](https://github.com/matplotlib/matplotlib), seems to indicate it was the `-flto` flag that was at fault.

Whether or not there should be a note on this in [the wiki](https://wiki.termux.com/wiki/Python#Python_module_installation_tips_and_tricks), I don't know. But consider that the wiki is already a bit misleading on `matplotlib`: it lists a bunch of flags, and you didn't have to set those at all..

**Comment by Grimler91** [comment]
Yeah, setting this as an enhancement issue until the wiki has been updated
