### ISSUE TITLE
jack error

### ISSUE THREAD

**Issue by Orpidus** [termux/termux-packages#579]
In using a CM 12.1 ROM and have recently installed jack. Whenever i try to run it, it shows "Aborted" and exits. All other packages are working correctly. Another thing I've noticed is even if I don't specify a file it still throws the same error.

**Comment by fornwall** [comment]
As [jack is deprecated and is on its way out](https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html) we're dropping the jack package from Termux, so closing the issue.

The best available tool for java on Termux is currently the `ecj` java compiler to compile .java source code to .class files, and then using the `dx` file to transform from .class to dex format.

**Comment by someoneb100** [comment]
I am sorry for asking for a tutorial, but i searched the web, found nothing, then tried countless times to get it on my own, but all failed.

Could someone please post how to compile and run a simple HelloWorld.java using `ecj` and `dx`? Again i am sorry for asking trivial things...

**Comment by sdrausty** [comment]
@someoneb100 A new repository at https://github.com/sdrausty/buildAPKs is open with instructions at https://sdrausty.github.io/buildAPKs/ and scripts https://github.com/sdrausty/buildAPKs/tree/master/scripts/build that build Android apps on devicei (a smartphone or tablet) in Termux.

Enjoy this project! Your feedback is welcome at either the wiki at https://github.com/sdrausty/buildAPKs/wiki the issues pages at https://github.com/sdrausty/buildAPKs/issues or through the code itself using `git` of course at https://github.com/sdrausty/buildAPKs/pulls

You can find hello world in https://github.com/sdrausty/buildAPKsTutorials/tree/6a6468e122d6a1c14d84849ed7d48e75934892ac/helloWorlds or with `ack ello |grep orld` in ~/buildAPKs Good Luck 😉

![screenshot_20170726-001641](https://user-images.githubusercontent.com/27742457/28698902-4ab5170a-7314-11e7-978a-811001a3c7c6.png)
