### ISSUE TITLE
Assembly running on x64arm gives segfault

### ISSUE THREAD

**Issue by suryapoojary-x** [termux/termux-packages#5793]
**Problem description**

Assembly program compiles and links correctly but when executed it throws a segfault.

![Screenshot_20200910-223701.png](https://user-images.githubusercontent.com/46720215/92769411-92c1e700-f3b6-11ea-992b-178fd2363f8d.png)
**Steps to reproduce**

as <filename> -o <filename>.o

ld <filename>.o -o  binary

./binary ; echo $?

**Expected behavior**

Expected to get the output.

**Additional information**

```
$ termux-info
Packages CPU architecture:                    aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
command-not-found/stable 1.56 aarch64 [upgradable from: 1.55-1]
curl/stable 7.72.0 aarch64 [upgradable from: 7.71.1]                                        dash/stable 0.5.11.2 aarch64 [upgradable from: 0.5.11.1]
debianutils/stable 4.11.1 aarch64 [upgradable from: 4.11-1]
gpgv/stable 2.2.23 aarch64 [upgradable from: 2.2.21]
libcurl/stable 7.72.0 aarch64 [upgradable from: 7.71.1]
libgpg-error/stable 1.39 aarch64 [upgradable from: 1.38]
nano/stable 5.2 aarch64 [upgradable from: 5.0]
termux-tools/stable 0.94 all [upgradable from: 0.93]
util-linux/stable 2.36 aarch64 [upgradable from: 2.35.2-1]
Android version:
10
Kernel build information:
Linux localhost 4.4.232pe-whyded+ #1 SMP PREEMPT Fri Aug 21 12:13:06 UTC 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 5 Pro
$


```

**Comment by xeffyr** [comment]
You have not posted your code, so I'm closing that.

**Comment by xeffyr** [comment]
If you mean
```
.global _start

_start:

mov x0,#1

ret
```
\- that would not work. You have to do `exit` system call instead of ret.

**Comment by xeffyr** [comment]
See https://stackoverflow.com/questions/19014568/assembly-segmentation-fault-after-making-a-system-call-at-the-end-of-my-code - exactly your issue.
> You can't ret from start; it isn't a function and there's no return address on the stack.
