### ISSUE TITLE
Flutter sdk for Termux

### ISSUE THREAD

**Issue by mukhtharcm** [termux/termux-packages#5798]
**Package description**

**Link to home page and sources**
1. Home page:flutter.dev
2. Source code:https://github.com/flutter/buildroot/pull/390

**Additional information**
Have you compiled or tried to compile the package on device? **NO**
* If it did not work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

Flutter sdk for termux. a PR is open for merging building arm64 as a flutter sdk host at https://github.com/flutter/buildroot/pull/390 .
So it should be possible to build flutter for termux.

**Comment by NTBBloodbath** [comment]
Something new? The PR referenced there was already merged 1 month ago 🤔

**Comment by lycstar** [comment]
> Something new? The PR referenced there was already merged 1 month ago 🤔

Any progress? I also want to know how to compile it, because I have prepared the tool chain for compiling Android on termux

**Comment by AurelienKun** [comment]
I would be very interested in this too. Any update ?

**Comment by dev-bz** [comment]
> I would be very interested in this too. Any update ?

now dart sdk is readied for  flutter.

**Comment by Achraf-cyber** [comment]
It will be very wonderful to get flutter on both arm and arm64 android device

**Comment by lycstar** [comment]
Do not know how to compile flutter engine to make gen_ snapshot(have Linux arm64 version but not ternux) binary tool can work on termux directly.

**Comment by dev-bz** [comment]
> Do not know how to compile flutter engine to make gen_ snapshot(have Linux arm64 version but not termux) binary tool can work on termux directly.

for install flutter, first is fetch flutter.git to local, then replace it's dart-sdk with dart-sdk in the termux .
```
rm -r flutter/bin/cache/dart-sdk
ln -s $PREFIX/lib/dart-sdk flutter/bin/cache/dart-sdk
```
the gen_ snapshot will work.
even now, there's more flutter runtime error needs to fix. such as `shared.sh` `platform.dart`.

**Comment by tempaccforissue** [comment]
Any update? I'm also interested in it. But mine device is 32 bit.

**Comment by tempaccforissue** [comment]
@mukhtharcm why you closed it? Is Flutter SDK available in Termux? What is the update?

**Comment by dev-bz** [comment]
> @mukhtharcm why you closed it? Is Flutter SDK available in Termux? What is the update?

Hi! The dart for flutter SDK can't work in 32bit, and flutter SDK only work by `git clone`.

**Comment by susandahal** [comment]
Any updates for this one? Is flutter sdk available for termux now?

**Comment by dev-bz** [comment]
> Any updates for this one? Is flutter sdk available for termux now?

![Screenshot_2023-07-14-09-17-37-183_com.termux.jpg](https://github.com/termux/termux-packages/assets/32380878/047381a0-e6b0-47e2-8f02-f0db4ee4c7b7)

Two ways to get it.
1. use proot-distro environment
2. As figure, replace dart-sdk's folder pointing to termux version, and modify flutter_tools's source `platform.dart`, return 'linux' when 'android', because flutter don't know Android platform.

**Comment by susandahal** [comment]
> 

I got proot method to work. But can't get it to run natively on termux. Have you actually successfully run it natively on termux?

**Comment by dev-bz** [comment]
> > 
> 
> I got proot method to work. But can't get it to run natively on termux. Have you actually successfully run it natively on termux?

I once successfully compiled the Flutter project binary and packaged it as an APK in a different way, but now that `dart` has been updated many times, there seem to be some new issues, which I have not tested for the time being. At a minimum, the previous method can run the `flutter doctor` detection environment.

![Screenshot_2023-07-14-10-21-05-696_com.termux.jpg](https://github.com/termux/termux-packages/assets/32380878/fa9a2054-032c-41fe-bc27-fed758cfba3b)

**Comment by susandahal** [comment]
> 

Can you guide me through it? What changes did you do before compiling the flutter project? Did you compile flutter engine too?

**Comment by dev-bz** [comment]
> > 
> 
> Can you guide me through it? What changes did you do before compiling the flutter project? Did you compile flutter engine too? 
> 
> Also can you give the compiled flutter package?

The `impellerc` (part of flutter engine) only run on linux_arm64, so now proot is only way.

**Comment by susandahal** [comment]
> > > 
> > 
> > 
> > Can you guide me through it? What changes did you do before compiling the flutter project? Did you compile flutter engine too?
> > Also can you give the compiled flutter package?
> 
> The `impellerc` (part of flutter engine) only run on linux_arm64, so now proot is only way.

Oh. But how did you manage to get flutter doctor to run with 3.10?

**Comment by mdHABIBURRAHMANHABIB1** [comment]
Flutter SDK hotReload is support . And also Flutter DevTool Support for Termux.

https://github.com/bdloser404/Fluttermux

check this.

**Comment by susandahal** [comment]
> Now Flutter SDK Latest is supported on Termux Natively. Also Fluttermux Comes with
> 
> * Flutter Devtool
> * Flutter HotReload
> * adb connection
> 
> https://github.com/bdloser404/Fluttermux
> 
> check this out.

Yes. My name is in the credits too😁😁

**Comment by TomJo2000** [comment]
The repo mentioned in above two comments appears to be either malware, or elsewise not what it purports to be.

The repository purports to host a "powerful bash script tailored to simplify the installation and setup of Flutter within your Termux".

In fact it only hosts a README, `init.vim`, `install.sh` and a 41.1KB binary blob titled `fluttermux`.
Some crude analysis in Ghidra suggests it is trying to siphon off `argv[0]` and `$_`, though I can not discern to what end.

I'd like to request a Maintainer to remove the previous two comments linking the suspicious repository,
the same user also appears to have a similarly suspicious repository targeting Arch Linux proot distros under Termux and no other GitHub repositories or contributions.

**Comment by susandahal** [comment]
> 

That binary is created from bash script using shc. That script uses arguments to get user input like install or patch and others. init.vim is just the neovim config preconfigured for flutter env. Install.sh checks if the required packages are installed

**Comment by susandahal** [comment]
Also i don't understand about how it is related to arch linux. It doesn't touch arch linux. The binary/bash script just patches the flutter and dart binaries according to need

**Comment by thunder-coding** [comment]
Your mentioned repository has been removed as it posses the risk of containing a malware. Also @susandahal If you want your binary to be trusted kindly also release fhe corresponding sources for them so that others can compile it

**Comment by bdloser404** [comment]
> > That binary is created from bash script using shc.
> 
> `shc` doesn't make script smaller or faster. This is a packer that is used to wrap script by some binary code in order to hide its contents from eyes.
> 
> Packed script distributed in a public Git repository in open source community is a red flag, no matter whether your binary is actually good. It could be okay if the binary origin can be tracked down to some trusted place such as well-known developer organization. But random user and with a packed Bash script looks indeed suspiciously.
> 
> Just don't do that. We don't like encrypted/packed/closed-source stuff to be advertised here. If you want to help by providing an installer script, please don't hide its contents. Otherwise keep your "know-how" for yourself.
> 
> Publishing decoded `fluttermux` script: [fluttermux.txt](https://github.com/termux/termux-packages/files/12575771/fluttermux.txt) _(no malicious functionality and as we see, the`shc` is not a right tool to protect know-how)_


-  Fluttermux is free 
- And perfect Flutter Development Environment Tools for Termux ever dade. 
- and I know this shc can be decrypt easily. 
-  **we are Using Browser to Browse internet do we need to know Browser app source code for it? So use Fluttermux For Setup Flutter Development Environment on Termux.**
- And there already proved that Fluttermux has no Malicious Functionality.  

~Developer of Fluttermux

**Comment by bdloser404** [comment]
This issue is **Flutter SDK for Termux** 

~ Issue fixed by Flutttermux. then why you delete fluttermux repo url that sent as solution?
