### ISSUE TITLE
Failure updating TeXLive installation

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#5799]
Today:

```
$ tlmgr --repository $PREFIX/../tlrepo update --list
[ ... no issues ... ]

$ tlmgr --repository $PREFIX/../tlrepo update --self
[ ... no self update ... ]
[ ... no issues ... ]

$ tlmgr --repository $PREFIX/../tlrepo update --all
[ ... no issues ...]
running mktexlsr ...
done running mktexlsr.
running mtxrun --generate ...
done running mtxrun --generate.
Cannot open /data/data/com.termux/files/usr/texmf-dist/web2c/updmap.cfg for writing: No such file or directory at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 3207.
```

So I tried:

```
$ termux-patch-texlive
Checking if $PREFIX/opt/texlive/TLUtils.pm.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/cjk-gs-integrate.pl.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/crossrefware.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/pdfjam.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/pedigree.pl.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/texconfig.sh.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/texdef.pl.diff can be applied.. Yes
Checking if $PREFIX/opt/texlive/texmf.cnf.diff can be applied.. Yes
Checking if $PREFIX/opt/texlive/tlmgr.pl.diff can be applied.. Nope
Checking if $PREFIX/opt/texlive/tlshell.tcl.diff can be applied.. Nope
```

and then

```
$ tlmgr --repository $PREFIX/../tlrepo update --all
tlmgr: package repository /data/data/com.termux/files/tlrepo (verified)
tlmgr: no updates available
tlmgr: Your installation is set up to look on the disk for updates.
To install from the Internet for this one time only, run:
  tlmgr -repository http://mirror.ctan.org/systems/texlive/tlnet ACTION ARG...
where ACTION is install, update, etc.; see tlmgr -help if needed.

To change the default for all future updates, run:
  tlmgr option repository http://mirror.ctan.org/systems/texlive/tlnet
```

How to fix this?

**Comment by Grimler91** [comment]
Does `updmap-sys` give you that error?

What is the output of 
```
(cd $PREFIX/share/texlive; patch -Np1 -i $PREFIX/opt/texlive/TLUtils.pm.diff)
```
?

**Comment by angelog0** [comment]
@Grimler91 wrote:

> Does updmap-sys give you that error?

I don't know. I have copy/pasted the output of post install step and it doesn't say from which the last line (`Cannot open...`) comes out...

This is the output:

```
$ (cd $PREFIX/share/texlive; patch -Np1 -i $PREFIX/opt/texlive/TLUtils.pm.diff)
patching file tlpkg/TeXLive/TLUtils.pm
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file tlpkg/TeXLive/TLUtils.pm.rej
```
I need a command to fix the post install step...

**Comment by Grimler91** [comment]
> I don't know. I have copy/pasted the output of post install step and it doesn't say from which the last line (Cannot open...) comes out...

Yeah, but if you run `updmap-sys` manually, do you get the same error message in that case?

**Comment by angelog0** [comment]
I get this:

```
$ updmap-sys
updmap will read the following updmap.cfg files (in precedence order):
  /data/data/com.termux/files/usr/share/texlive/texmf-dist/web2c/updmap.cfg
updmap may write changes to the following updmap.cfg file:
  /data/data/com.termux/files/usr/share/texlive/texmf-config/web2c/updmap.cfg
dvips output dir: "/data/data/com.termux/files/usr/share/texlive/texmf-var/fonts/map/dvips/updmap"
pdftex output dir: "/data/data/com.termux/files/usr/share/texlive/texmf-var/fonts/map/pdftex/updmap"
dvipdfmx output dir: "/data/data/com.termux/files/usr/share/texlive/texmf-var/fonts/map/dvipdfmx/updmap"
updmap [ERROR]: The following map file(s) couldn't be found:
updmap [ERROR]:         NotoMath.map (in /data/data/com.termux/files/usr/share/texlive/texmf-dist/web2c/updmap.cfg)
updmap [ERROR]:         josefin.map (in /data/data/com.termux/files/usr/share/texlive/texmf-dist/web2c/updmap.cfg)
updmap [ERROR]:         spectral.map (in /data/data/com.termux/files/usr/share/texlive/texmf-dist/web2c/updmap.cfg)
updmap [ERROR]: Did you run mktexlsr?

        You can disable non-existent map entries using the option
          --syncwithtrees.
```

**Comment by angelog0** [comment]
OK, for sanity check I re-run manually:

```
mktexlsr
[...]
mtxrun --generate
[...]

updmap-sys
[...]
```

and in the output I do not see error messages...

Now, what else?

Thanks

**Comment by Grimler91** [comment]
These errors:
> updmap [ERROR]: The following map file(s) couldn't be found:
> updmap [ERROR]:         NotoMath.map (in /data/data/com.termux/files/usr/share/texlive/texmf-dist/web2c/updmap.cfg)
> updmap [ERROR]:         josefin.map (in /data/data/com.termux/files/usr/share/texlive/texmf-dist/web2c/updmap.cfg)
> updmap [ERROR]:         spectral.map (in /data/data/com.termux/files/usr/share/texlive/texmf-dist/web2c/updmap.cfg)
> updmap [ERROR]: Did you run mktexlsr?
> 
>         You can disable non-existent map entries using the option
>           --syncwithtrees.

Can probably be fixed with `updmap-sys --syncwithtrees`.

I managed to re-produce the error by running `tlmgr install --reinstall metapost`. This runs updmap internally (I think) and gives the error message.

I'll track down where the error comes from and add a new patch for it. I think document compilation should work without errors for you until then.

**Comment by Grimler91** [comment]
Alright, so problem happens if kpathsea (containing texmf.cnf) is updated. `termux-patch-texlive` solves the problem and running `tlmgr update --all` a second time should then update the rest of the packages and finish without errors. 

I do not see any way to prevent this (other than not using tlmgr), and it isn't fatal as running tlmgr after termux-patch-texlive fixes it, so closing

**Comment by angelog0** [comment]
> Alright, so problem happens if kpathsea (containing texmf.cnf) is updated. `termux-patch-texlive` solves the problem and running `tlmgr update --all` a second time should then update the rest of the packages and finish without errors.
> 

I already did this... see my [OP](https://github.com/termux/termux-packages/issues/5799#issue-700522245) and it does not run the post install steps. On GNU/Linux and macOS it runs `mktexlsr`, `mtxrun --generate`, `updmap-sys` and **a lot** of `fmtutill ...` commands ...

So, there was 256 packages upgraded, corectly decompressed but for which the postinstall steps were not run completely. Even if I can build documents the installation is substantially _broken_ ...

> I do not see any way to prevent this (other than not using tlmgr), and it isn't fatal as running tlmgr after termux-patch-texlive fixes it, so closing

**Comment by angelog0** [comment]
As I suspected, now the installation is **totally** broken because i cannot rebuild my documents ... the skipped postinstall steps caused this (on GNU/Linux and macOS there are not problems)




> I do not see any way to prevent this (other than not using tlmgr), and it isn't fatal as running tlmgr after termux-patch-texlive fixes it, so closing

There is a way, send your binaries to upstream so that TeXLive add termux as another system....

**Comment by Grimler91** [comment]
> As I suspected, now the installation is totally broken because i cannot rebuild my documents ... the skipped postinstall steps caused this (on GNU/Linux and macOS there are not problems)

Can you provide some information about where/why it fails? I guess there is some postinstall command required as you said, so should be possible to fix the installation by running appropriate postinstall steps. Could add those steps to the end of termux-patch-texlive.

> There is a way, send your binaries to upstream so that TeXLive add termux as another system....

This page has some information about how to build binaries: https://www.tug.org/texlive/build.html. It is not very clear but I think they want static binaries (which would makes sense, they do not want the binaries to break if a dependency is updated), while we use shared binaries in termux. If someone wants to volunteer, build static binaries, send them to upstream and maintain them then they are very welcome to do so!

**Comment by Grimler91** [comment]
Looks like tlmgr at least supports pinning a package to a specific repository: https://www.tug.org/texlive/doc/tlmgr.html#Pinning

Might be possible to setup a repository with kpathsea (and other packages with config files) and then pin those package to that repository.

**Comment by angelog0** [comment]
After running

`fmtutil-sys --all`

it seems I can rebuilt my documents.

**Comment by xeffyr** [comment]
Let's have one issue regarding "tlmgr update problems": https://github.com/termux/termux-packages/issues/5949
