### ISSUE TITLE
Package Request: inxi

### ISSUE THREAD

**Issue by Mhowser** [termux/termux-packages#5802]
**Package description**

inxi is a full featured CLI system information tool.

**Link to home page and sources**
1. Home page: http://smxi.org/docs/inxi.htm
2. Source code: https://github.com/smxi/inxi

**Additional information**
TBD

**Comment by xeffyr** [comment]
Do you have any information about usability of `inxi` n Termux?

As I see, it too much relies on external utilities like `hddtemp`, `iproute2`, `lm-sensors`, etc. Some of them are not available in Termux, some work only with root permissions.

**Comment by Mhowser** [comment]
The devoper of inxi is in need of information and data on ARM devices, see https://github.com/smxi/inxi/issues/167

**Comment by xeffyr** [comment]
![Screenshot_20200914-140046_Termux](https://user-images.githubusercontent.com/25881154/93078300-ec663200-f692-11ea-978f-007aefe04acb.png)

***

Ok, will add it. However we tend not to package single scripts.

**Comment by Mhowser** [comment]
Thank you!

**Comment by xeffyr** [comment]
Closing as package is already available.

You can obtain it with these commands:
```
pkg install inxi
```
