### ISSUE TITLE
Package Request: tmpmail

### ISSUE THREAD

**Issue by NTBBloodbath** [termux/termux-packages#5809]
**Package description**
tmpmail is a command line utility that allows you to create a temporary email address and receive emails to the temporary email address. It uses 1secmail's [API](https://www.1secmail.com/api/) to receive the emails.

**Link to source code**
1. Source code: https://github.com/sdushantha/tmpmail

**Additional information**
You only have to modify a variable within the executable to adjust the path of tmp to the path of Termux's tmp (adding `$PREFIX` to the String).

**Comment by Hax4us** [comment]
It's just a shell script. i don't think it would be packaged.
