### ISSUE TITLE
What I type does not appear on the screen untill I press enter

### ISSUE THREAD

**Issue by bertus68** [termux/termux-packages#5812]
I have used termux before on smartphone and tablet without this problem.
Now I installed the APP on the Samsung Note 20 and before I see what I type I have to press "enter".
Could it be due to the Keyboard?

**Comment by Grimler91** [comment]
It is a samsung problem: https://github.com/termux/termux-app/issues/686.
A workaround, released as part of termux-app 0.99, is described in https://github.com/termux/termux-app/issues/686#issuecomment-681026810
