### ISSUE TITLE
Error upgrading Emacs package

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#5817]
This error occurred:

```
[...]
Setting up emacs (27.1) ...
Loading loadup.el (source)...
dump mode: pdump
Using load-path (/data/data/com.termux/files/usr/share/emacs/27.1/lisp)
Loading emacs-lisp/byte-run...
Loading emacs-lisp/backquote...
Loading subr...
[...]
Loading leim/leim-list.el (source)...
Waiting for git...
Error running git rev-parse: (file-missing "Searching for program" "No such file or directory" "git")
Waiting for git...
Error running git rev-parse --abbrev-ref: (file-missing "Searching for program" "No such file or directory" "git")
Finding pointers to doc strings...
Finding pointers to doc strings...done
Pure-hashed: 15190 strings, 4357 vectors, 38401 conses, 4041 bytecodes, 226 others
Dumping under the name emacs.pdmp
dumping fingerprint: a284d4697aa0d4f0234f229f64201a500532b2958b9df7dbb408e31ae92cdfbf
Dump complete
Byte counts: header=80 hot=6912968 discardable=112080 cold=3086568
Reloc counts: hot=378732 discardable=4368
Adding name emacs-27.1.1
Adding name emacs-27.1.1.pdmp
Setting up command-not-found (1.57) ...
Processing triggers for man (1.14.5-2) ...
```

Maybe it is not a fatal error but anyway it seems to demonstrate that Emacs package requires `git` which here is not installed:

```
$ which git
$ git
The program git is not installed. Install it by executing:
 pkg install git
```

**Comment by angelog0** [comment]
BTW, how to fix this Emacs upgrade? Just wait you add `git` as dependency and a new Emacs upgrade or what else?

**Comment by Grimler91** [comment]
Hm, if you start emacs right now, does it start fast (without loading lots of files) or does it load lots of files (as before)?

27.1 allows us to dump emacs which makes it start way faster. It looks like the dumping succeeded anyways (emacs.pdmp was created), but I guess some startup files were not loaded/dumped.

Could you please check if this finishes without similar errors/warnings: 
```
pkg in git
cd $PREFIX/share/emacs/27.1/lisp
LC_ALL=C $PREFIX/bin/emacs -batch -l loadup --temacs=pdump
mv $PREFIX/bin/emacs*.pdmp $PREFIX/libexec/emacs/27.1/*-linux-android*/
```

**Comment by xeffyr** [comment]
`git rev-parse` won't work here anyway. It requres a full git repo to be present as dumping normally done during build time.

**Comment by angelog0** [comment]
@Grimler91, it seems to start a bit faster...

Given the comment of @xeffyr , I would wait before to test what you suggest. If `git` is a dependency of Emacs, I would wait for this fix instead to install it directly.

**Comment by angelog0** [comment]
BTW, why do you not `dump` it when building the binaries? I monthly build Emacs from master on GNU/Linux, macOS and Windows and all these builds **dump** while building not when I install the resulting package (usually a `tar.xz` or `.7z` archive)

```
[...]
Does Emacs support the portable dumper?                 yes
Does Emacs support legacy unexec dumping?               no
Which dumping strategy does Emacs use?                  pdumper
[...]
GEN      ../etc/DOC
rm -f emacs.exe && cp -f temacs.exe emacs.exe
LC_ALL=C ./temacs -batch  -l loadup --temacs=pdump
Loading loadup.el (source)...
dump mode: pdump
[...]
```

Notice that my builds do not use git, maybe because I use as source https://git.savannah.gnu.org/cgit/emacs.git/snapshot/emacs-master.tar.gz ?

Maybe you should use https://git.savannah.gnu.org/cgit/emacs.git/snapshot/emacs-27.1.tar.gz as source ...

**Comment by angelog0** [comment]
@Grimler91 , are you building with `make bootstrap`? As you can see, In my build this command

```
LC_ALL=C ./temacs -batch  -l loadup --temacs=pdump
```

is run while building not in a postinstall step.

`make bootstrap` is the recommended way to build Emacs.

**Comment by Grimler91** [comment]
> @Grimler91, it seems to start a bit faster...

Seems that emacs works as it should then :+1:

Looking at the source-code there's not really any convenient way to disable the attempt to get the version from git, and given @xeffyr's comment adding git as a dependency would not make a difference anyways. Emacs also reports the correct version so everything seem to work, I don't think we'll do anything about those messages in the postinst script. 

 > BTW, why do you not dump it when building the binaries?

It does not work when cross-compiling unfortunately, temacs cannot be executed in our ubuntu x86_64 docker image as it is compiled for aarch64 (or some other arch). Trying to use a host-built temacs gives an error when trying to run emacs on device (due to it containing x86_64 instructions which cannot be understood on aarch64/arm), so only way to dump emacs for us is hence to do it on device, I at least have not found a way to dump emacs during the cross-compilation.

> are you building with make bootstrap? 

Yeah, we are compiling a bootstrap-emacs on the host and using that in the build: https://github.com/termux/termux-packages/blob/f7ac2094bb9dbd3facfe5d8d1fbbd1c75e7a422d/packages/emacs/build.sh#L93

**Comment by angelog0** [comment]
Just for completeness, 

I installed git and then uninstalled and reinstalled (cleanly) emacs. Now it does not display those error messages but just 

```
[...]
Loading tooltip...
Loading leim/leim-list.el (source)...
Waiting for git...
Waiting for git...
Finding pointers to doc strings...
Finding pointers to doc strings...done
[...]
```
exactly as in my build logs on other systems I cited. It seems _to want_ git for some reason.

Anyway I find that `$PREFIX/libexec/emacs/27.1/*-linux-android*/` folder contains an unresolved symlink,

```
emacs-27.1.1.pdmp -> /data/data/com.termux/files/usr/bin/emacs.pdmp
```
`emacs.pdmp` does not exist in `$PREFIX/bin`.

BTW, how to uninstall a package, purging it, on Termux?

**Comment by angelog0** [comment]
That symlink does not exist in. the build on Windows etc..

**Comment by xeffyr** [comment]
>  It seems to want git for some reason.

Extracting version/commit info from the source tree.

**Comment by xeffyr** [comment]
See https://github.com/emacs-mirror/emacs/blob/d0e2a341dd9a9a365fd311748df024ecb25b70ec/lisp/version.el#L114.
