### ISSUE TITLE
conflict installation gst-plugins-base with mesa

### ISSUE THREAD

**Issue by cadanganrendy** [termux/termux-packages#5818]
here is the log

Preparing to unpack .../gst-plugins-base_1.18.0_aarch64.deb ...
Unpacking gst-plugins-base (1.18.0) ...
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/gst-plugins-base_1.18.0_aarch64.deb (--unpack):
trying to overwrite '/data/data/com.termux/files/usr/include/GL/glext.h', which is also in package mesa 17.3.9-31
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
/data/data/com.termux/cache/apt/archives/gst-plugins-base_1.18.0_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by buttaface** [comment]
I'll look into it.

**Comment by tathastu871** [comment]
remove mesa from stable repo. If it gets accidently installed entire system breaks and we had to reinstall

**Comment by xeffyr** [comment]
@tathastu871 Then I need to remove **whole** x11 repository.

**Comment by xeffyr** [comment]
Regarding the fix, GL directory in includes should be removed from gst-plugins.

**Comment by xeffyr** [comment]
Fix applied in https://github.com/termux/termux-packages/commit/68559d9456ace0e90d33e7e46a78287aa9b802ad, updates will be available soon.
