### ISSUE TITLE
Error in python with termux-chroot

### ISSUE THREAD

**Issue by AdrMXR** [termux/termux-packages#5821]
python does not let me do an `os.system ('clear')` when starting` termux-chroot`, I get the error shown in the image Why does this happen? I hope you can help me.

![119703879_1248625385516405_1187677344459783949_n](https://user-images.githubusercontent.com/54054887/93557728-586dc200-f941-11ea-8279-cd83e84110f8.jpg)

**Comment by xeffyr** [comment]
Python for some reason uses /system/bin/sh instead of Termux shell (bash/dash).

**Comment by xeffyr** [comment]
Have checked Python stdlib - that's not a bug.

`os.system` uses `system()` function from libc and this one uses `/system/bin/sh` shell. That's cannot be changed.

Use `subprocess` module instead.
