### ISSUE TITLE
Failed To Start Apache2

### ISSUE THREAD

**Issue by BJS611** [termux/termux-packages#5822]
Can you help me please??

sysctl apache2 start
c: cannot stat /proc/sys/apache2: error code 2
c: cannot stat /proc/sys/start: error code 2

Thanks.

**Comment by ifurther** [comment]
Why do you use `sysctl` ?

**Comment by BJS611** [comment]
> Why do you use `sysctl` ?

Is there any other way?

**Comment by ifurther** [comment]
apachectl start ?

**Comment by BJS611** [comment]
> apachectl start ?
It's not works

apachectl start
httpd: Syntax error on line 535 of /data/data/com.termux/files/usr/etc/apache2/httpd.conf: Include/IncludeOptional: No matches for the wildcard '*.conf' in '/data/data/com.termux/files/usr/etc/apache2/conf.d', failing

**Comment by ifurther** [comment]
Sorry it has error. I am fixing now.

**Comment by RexZombie** [comment]
still having same error :(

**Comment by RexZombie** [comment]
Hi! will the fix work if i changed the index file from html to php extension?
<IfModule dir_module>
  DirectoryIndex index.php
</IfModule>

**Comment by BJS611** [comment]
> Hi! will the fix work if i changed the index file from html to php extension?
> 
> DirectoryIndex index.php

Hello!
Bisa kah kau beritahu dimana direktori itu?
Thanks

**Comment by BJS611** [comment]
> Hi! will the fix work if i changed the index file from html to php extension?
> 
> DirectoryIndex index.php

Hello!
Can you tell me where that directory is?
Thanks

**Comment by kcubeterm** [comment]
In configuration file.

Default configuration file is
`/data/data/com.termux/files/usr/etc/apache2/http.conf`

**Comment by BJS611** [comment]
> In configuration file.
> 
> Default configuration file is
> `/data/data/com.termux/files/usr/etc/apache2/http.conf`
> 
Hello! Hmn, i don't know why, but in my Termux, http.conf named httpd.conf, then I changed the named to http.conf and try apachectl and failed.


![Screenshot_2020-09-23-13-27-34-66.png](https://user-images.githubusercontent.com/65802479/93974848-a4d15b80-fda0-11ea-95b4-92ede5abc53b.png)

**Comment by kcubeterm** [comment]
@BJS611  that's httpd.conf, 
By mistake I wrote http.conf.

**Comment by BJS611** [comment]
> @BJS611  that's httpd.conf, 
> By mistake I wrote http.conf.

Not problem 😊

**Comment by BJS611** [comment]
Please, this problem is not resolved, don't close it.🙏

**Comment by xeffyr** [comment]
> his problem is not resolved

**Solved**. https://github.com/termux/termux-packages/commit/c9a66eea6d6dc61612b3e836d85b99f6715f9e94

Upgrade your packages!

***
![Screenshot_20200926-190406_Termux](https://user-images.githubusercontent.com/25881154/94344878-1c1a2000-002b-11eb-8048-6b24c08628a8.png)

***

Please note that issues about messed up configurations are **out of scope** for resolving by Termux maintainers. Better to reinstall package and start from scratch in this case.
```
apt purge apache2
apt install apache2
```

**Comment by BJS611** [comment]
> > his problem is not resolved
> 
> **Solved**. https://github.com/termux/termux-packages/commit/c9a66eea6d6dc61612b3e836d85b99f6715f9e94
> 
> Upgrade your packages!
> 
> ***
> ![Screenshot_20200926-190406_Termux](https://user-images.githubusercontent.com/25881154/94344878-1c1a2000-002b-11eb-8048-6b24c08628a8.png)
> 
> ***
> 
> Please note that issues about messed up configurations are **out of scope** for resolving by Termux maintainers. Better to reinstall package and start from scratch in this case.
> ```
> apt purge apache2
> apt install apache2
> ```

Thank you, this solves my problem😀
