### ISSUE TITLE
Rsync is built without ipv6 support

### ISSUE THREAD

**Issue by iteratee** [termux/termux-packages#5826]
**Problem description**

Rsync is built without support for ipv6. It forces the -4 flag 
**Steps to reproduce**

rsync --debug=cmd -6 user@host:path path
will print
ssh -4 user@host rsync ...
**Expected behavior**

rsync --debug=cmd -6 user@host:path path
should print
ssh -6 user@host rsync ...
**Additional information**

rsync version is 3.2.3, and rsync --version shows it was compiled without ipv6 support.

**Comment by tomty89** [comment]
Probably something like this needs to be done for Android/Bionic:
https://git.samba.org/rsync.git/?p=rsync.git;a=commit;h=8a68cad1f77ac40f3834f7449ef794e37cba7914

Ref.: https://android.googlesource.com/platform/bionic/+/master/libc/include/netinet/in6.h

**Comment by alexzhang** [comment]
I was able to get rsync to compile with IPv6 support simply by adding the following lines to `include/features.h`.
```
#define __GLIBC__ 2
#define __GLIBC_MINOR__ 33
```

This fools the preprocessor into believing that the latest version of glibc is available, and allows rsync's `configure.ac` to autodetect the IPv6 stack as `ipv6type=linux-glibc`. The build then proceeds normally with IPv6 support.

**Comment by smiba** [comment]
Submitted a patch based on the knowledge gained by @alexzhang

**Comment by Grimler91** [comment]
Should be fixed now, thanks for reporting and the patch!
