### ISSUE TITLE
Emacs slide behaviour desapear

### ISSUE THREAD

**Issue by PillFall** [termux/termux-packages#5827]
**Problem description**
I won't be able to swipe in the new version of emacs, it recognize as key down and key up presses

**Steps to reproduce**
Start emacs and swipe up and down

**Expected behavior**
It suppose to act like if I was scrolling with the mouse wheel

**Additional information**
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Fri Nov 8 00:25:05 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 5
```

**Comment by Grimler91** [comment]
I can't reproduce the issue, scrolling by swiping up or down works fine on my devices in emacs 27.1

**Comment by hnmn** [comment]
> I can't reproduce the issue, scrolling by swiping up or down works fine on my devices in emacs 27.1

Yes is scrolling but not like a using mouse
Is just jump like one page to another 

Also in latest emacs touch is not working like in 
Vim

**Comment by PillFall** [comment]
Yeah, I mean, when you touch, before it act like a mouse click. And you can go to any part in the screen just by touching.

**Comment by PillFall** [comment]
I'm not an English speaker, so sorry for the bad English.

When you use emacs 26, you could touch whatever in the screen, and it acts as expected, a `<mouse-1>` button press (aka mouse left click), then emacs put the point at the touched location. Also, when you swipe the screen, it acts like the computer mouse wheel, when you open emacs in window mode, It scroll the frame downwards or upwards, and leave the point wherever it was.

Now, with emacs 27, the mouse button presses disappeared, and when you swipe the screen it behaves as if you press the `down` or `up` key.

**Comment by PillFall** [comment]
Also, I recently realize that plug in a external mouse doesn't work, so you can't click anywhere

**Comment by RecentlyRezzed** [comment]
As a workaround and a demo of the behaviour of the previous version, you can install emacs-x.

**Comment by PillFall** [comment]
I recently discover that activating xterm-mouse-mode returns the previous behaviour in the new version of emacs. I think it could be used as a workaround.

**Comment by RecentlyRezzed** [comment]
Thank you for pointing me in the right direction, PillFall! The scrolling didn't work for me until I've added the following to my .emacs file:
(xterm-mouse-mode t)
(global-set-key [mouse-4] '(lambda ()
                             (interactive)
                             (scroll-down 1)))
(global-set-key [mouse-5] '(lambda ()      
                             (interactive)
                             (scroll-up 1)))

**Comment by PillFall** [comment]
@RecentlyRezzed Yeah, sorry, I forgot to mention that

I put in my `.emacs`
```lisp
(xterm-mouse-mode t)
(global-set-key [mouse-4] #'scroll-down-line)
(global-set-key [mouse-5] #'scroll-up-line)
```
