### ISSUE TITLE
Text duplication when typing 

### ISSUE THREAD

**Issue by rapastranac** [termux/termux-packages#5830]
Every time I write anything,  it doesn't show whatever I type, it shows it only after pressing space,  but this comes with a duplication of whatever was already written.  Samsung galaxy S9 user.

**Comment by xeffyr** [comment]
Create & edit file `~/.termux/termux.properties` by putting this content:
```
enforce-char-based-input = true
```
Then restart application.

***

That's keyboard bug which doesn't understand `InputType.TYPE_NULL` (generic input method) and not Termux.
