### ISSUE TITLE
No scala package for termux? 

### ISSUE THREAD

**Issue by SteelDualMassWheel** [termux/termux-packages#5832]
I wanted to install scala on termux, but command "pkg install scala" doesn't work. Does termux support scala programming language? If so, what is the name of the package? I tried searching for it on google, but without success.

**Comment by xeffyr** [comment]
As JDK is not available, Scala is not available too.

**Comment by SDRausty** [comment]
@SteelDualMassWheel scala is available in Termux PRoot:
```
community/scala 2.13.3-1
    A Java-interoperable language with object-oriented and functional features
community/scala-docs 2.13.3-1
    Scala documentation
community/scala-sources 2.13.3-1
    Scala sources
```
The Arch Linux x86 and Arch Linux x86_64 architectures have the scala of packages available readily.

**Comment by SDRausty** [comment]
After further testing of this issue @SteelDualMassWheel  this is what I have found:

> Does termux support scala programming language? 

Yes it is available, but as @xeffyr stated, "Scala is not available [as a Termux package.]"

> If so, what is the name of the package? 

The `scala` packages that I am currently testing in Arch Linux in Termux PRoot are called:
1. scala3
1. scala-dotty

![Screenshot_20201120-114230](https://user-images.githubusercontent.com/27742457/99825902-a6f83200-2b25-11eb-8471-e277919c0725.png)

The command `yay scala` in Arch Linux in Termux PRoot produces 241 package results:
`241 aur/tensorflow114-cuda 1.14.0-5 (+0 0.00) (Out-of-date: 2020-04-25)`
    `Library for computation using data flow graphs for scalable machine learning (with CUDA)`
⋮
`1 core/perl 5.32.0-3 (14.2 MiB 57.5 MiB) (Installed)
    A highly capable, feature-rich programming language`

These packages can be easily built on device with the Arch Linux command `yay` in Termux PRoot.
