### ISSUE TITLE
Please update the "dart" package.

### ISSUE THREAD

**Issue by Monoluxuria** [termux/termux-packages#5833]
As the title says the current version (2.7.2) of the dart package is outdated. Please update it to the latest stable (2.9.2).

**Comment by xXxrAinZyian** [comment]
> As the title says the current version (2.7.2) of the dart package is outdated. Please update it to the latest stable (2.9.2).

**Comment by xXxrAinZyian** [comment]
😉

**Comment by Grimler91** [comment]
I tried building 2.9.x a few days ago but building the sdk still fails due to (I think) it expecting python2 at /usr/bin/python but finding python3

**Comment by xeffyr** [comment]
Yes, all issues due to requirement of deprecated python2.

For now can suggest only patching it to call `python2` instead of `python` or temporarily modifying /usr/bin/python symbolic link during runtime (which may not be acceptable for people doing builds outside of Docker container).

**Comment by xeffyr** [comment]
Try `pkg upgrade`, it should be available now.
