### ISSUE TITLE
Please Upgrade Node Js lastest version 14.11.0

### ISSUE THREAD

**Issue by amm834** [termux/termux-packages#5835]
Current node version v12.18.3 is deprecated for some npm package.

**Comment by hnmn** [comment]
We have `v14.8.0` available in termux

I think you had `nodejs-lts` version installed
Try 
`pkg install nodejs`

**Comment by amm834** [comment]
> We have `v14.8.0` available in termux
> 
> I think you had `nodejs-lts` version installed
> Try
> `pkg install nodejs`

Yes I have been get 14.8.0
But some npm packages are deprecated.
Ex.mongo

**Comment by amm834** [comment]
![Screenshot_2020-09-21-13-06-01-97](https://user-images.githubusercontent.com/65492233/93738222-3eff9b00-fc0b-11ea-935a-2458037c967d.jpg)
I use node v14.8.0
But I get this.Not good idea😅.
Cuz nodejs v14.11.0 is available now.

**Comment by Grimler91** [comment]
> But some npm packages are deprecated.
> Ex.mongo

The deprecation warnings you are seeing means that the npm package uses deprecated functions/features. It cannot be fixed by upgrading nodejs (newer nodejs versions introduce more deprecations), it has to be fixed in the npm package.

**Comment by Hax4us** [comment]
@amm834 use it like 
`MongoClient.connect(url, {useUnifiedTopology: true}, (err, client) => { ...`

You will have to pass option `useUnifiedTopology: true`
