### ISSUE TITLE
Some commands are not working 

### ISSUE THREAD

**Issue by Pawansai74** [termux/termux-packages#5836]
Commands like apt-get update-y such commands are not working. 
How can I resolve my problem?

**Comment by xeffyr** [comment]
Closing as no information about the issue.

**Comment by kcubeterm** [comment]
I think command are not working because of typo. It should be  `apt-get update`  or `apt-get update -y`

Anyway, use `pkg`, 
```pkg upgrade```

**Comment by xeffyr** [comment]
`-y` is useless for `apt-get update` because `update` command doesn't take arguments.
