### ISSUE TITLE
Mirror Issue

### ISSUE THREAD

**Issue by nekunei** [termux/termux-packages#5838]
Well, I was facing some issue at my Termux. It doesn't let me install Some package. 

Like `openssh`

```bash
$ pkg install openssh
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openssh
```

Same as `apt` Does. Both doesn't let me install openssh at some Server. 

Yesterday, i can install `nodejs-lts` via `pkg`.

But now, I find nothing at `search`. Only get the v14:

```bash
$ pkg search nodejs
Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://dl.bintray.com/termux/termux-packages-24
Sorting... Done
Full Text Search... Done
nodejs/now 14.8.0-1 aarch64 [installed,local]
  Platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications
```

```bash
$ pkg search openssh
Checking availability of current mirror: ok
Sorting... Done
Full Text Search... Done
```

Only get nothing at `pkg`. Maybe i need manual installation.

Please fix it. Thanks.

**Comment by Grimler91** [comment]
Run `apt update` first and it will probably work

**Comment by xeffyr** [comment]
Package lists are stored in application cache. It it will be wiped by clicking relevant button in Android settings or by some cleaner application, you will have effect like shown in your post.

As already suggested, you can use `apt update` or `pkg update` to re-download lists.

**Comment by Adilabbasi42** [comment]
$ pkg upgrade
Checking availability of current mirror: ok
Hit:1 https://grimler.se/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

**Comment by xeffyr** [comment]
@Adilabbasi42 Rather than necrodigging, could you look the opened and pinned issues? Specifically this one: https://github.com/termux/termux-packages/issues/6726. It has solution for your issue.
