### ISSUE TITLE
Package-request fswebcam

### ISSUE THREAD

**Issue by Sant268** [termux/termux-packages#5839]
**Package description**
Usage of camera module via terminal

**Link to home page and sources**
1. Home page:http://manpages.ubuntu.com/manpages/bionic/man1/fswebcam.1.html
2. Source code:https://github.com/fsphil/fswebcam

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
No,did not work
* If it did work then please share any patches that you had to apply.

**Comment by xeffyr** [comment]
Any proof that it works in Termux?

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/5019#issuecomment-638785697 - regarding video4linux on Android.

**Comment by xeffyr** [comment]
Will reopen when someone made progress on V4L in Termux...
