### ISSUE TITLE
on the termux-emacs init file

### ISSUE THREAD

**Issue by Txellenne** [termux/termux-packages#584]
Hi, I'm trying termux-emacs with a physical keyboard & missed be able to use paredit when at editing lisp/scheme files. Would anyone know to give me a clue on this, please? I tried to [download the pkge](https://github.com/emacsmirror/paredit/blob/master/paredit.el) itself & building a kind of `init.file` which in turns called for it, but, here is when I found out that I had no access to my tablet's download files. Actually I'm confined to live in `~/data/data/com.termux/files/home` (& unable to find where at, still) (by the way, does anyone know where it is? (I confess starting to feel claustrophobic)). Well, don't get me wrong I love, at least, having Emacs at hand. I've even got realized there is a built-in lisp, scheme (among other emacs-mode) engines available to play with idea notes on fly but I wanted to also be able to use `paredit`. I'd appreciate any clue on this..

**Comment by fornwall** [comment]
You can run `termux-setup-storage`, which should setup a symlink to the downloads folder in `~/storage/downloads`. Read more at https://termux.com/storage.html.

Note that you can also use e.g. `curl` in Termux to download files directly.
