### ISSUE TITLE
Package-request: putty & putty-cli(without X)

### ISSUE THREAD

**Issue by sean0921** [termux/termux-packages#5842]
**Package description**

*putty*

Telnet/SSH client for X
 This is the Unix port of the popular Windows SSH client, PuTTY. It supports
 flexible terminal setup, mid-session reconfiguration using Ctrl-rightclick,
 multiple X11 authentication protocols, and various other interesting things
 not provided by ssh in an xterm.

- ps. with `pterm ‐ yet another X terminal emulator`

*putty-cli*

includes:
- plink - PuTTY link, command line network connection tool
- pscp - command-line SCP (secure copy) / SFTP client
- psftp - interactive SFTP (secure file transfer protocol) client
- puttygen - public-key generator for the PuTTY tools

**But Why?**

PuTTY use its own method for inplementing ssh/telnet/rsh/serial connection, not an "openssh/dropbear ssh" client with GUI, we should consider provide this simple choice for remote connection.

Also we can import existed complicated session file from other device to `${HOME}/.putty/sessions/<session name>` in Android termux device, to let remote connections visualized and managable.

**Link to home page and sources**
1. Home page: https://www.chiark.greenend.org.uk/~sgtatham/putty/
2. Source code: 
- git version: https://git.tartarus.org/simon/putty.git (`git clone <url>`), https://git.tartarus.org/?p=simon/putty.git (cgit web frontend)
- release version: [version 0.74](https://the.earth.li/~sgtatham/putty/latest/putty-0.74.tar.gz)

**Additional information**
Have you compiled or tried to compile the package on device?
* ~~If it did not work then please provide the error you ran into.~~
* If it did work then please share any patches that you had to apply.

*putty* (with gtk3 version)

not tested yet

*putty-cli* (without gtk3 version)

There's *no patch* for putty CLI tools, but with some tricky configuration in command line.

```
../configure --without-gtk ac_cv_func_futimes=no ac_cv_func_setpwent=no LIBS="-landroid-glob"
make && make install
```

`plink`, `puttygen`, `pscp`, `psftp` just works smoothly.

**Comment by xeffyr** [comment]
Does existing plink, pscp, psftp, puttygen work in cli?

Please note that I'd like to **avoid** duplicated packages, like `putty` + `putty-nox`, and will rather merge them than provide separately. Examples of "deduplicated" packages are `links`, `imagemagick`, `gnuplot`. So I will provide a separate package for putty only if pure command line usage support is available with `--without-gtk` being set.

**Comment by xeffyr** [comment]
> Does existing plink, pscp, psftp, puttygen work in cli?

Tested myself, they work. However pterm triggers seccomp and needs patching.

![Screenshot_20200923-185324_Termux](https://user-images.githubusercontent.com/25881154/94037614-36a38d80-fdce-11ea-8d0b-c2699727bca8.png)

Closing issue as wontfix - as I wrote above, no-Xorg/Xorg packages are going to be deduplicated.

**Comment by sean0921** [comment]
Thanks for your reply, I didn't notice that there have been a same package in specific repo, I'll check it more carefully next time.

**Comment by sean0921** [comment]
btw, I'm curious about the reason `vim` package can have three duplicated version: `vim`, `vim-python`, `vim-gtk3` (`x11-repo`).  Is it just a special case because `vim` is such a fundamental and popular package?

**Comment by xeffyr** [comment]
@sean0921 `vim` & `vim-python` were added at time when Termux had tendency to split anything like Debian, `vim-gtk3` is separate package because X11-related dependencies are in separate repo.

`vim` & `vim-python` likely to be merged in one package in future.

**Comment by xtkoba** [comment]
See also #8836.
