### ISSUE TITLE
How to build clinfo package?

### ISSUE THREAD

**Issue by sunmoon9898** [termux/termux-packages#585]
Hi,
My android samsung S6. 
My clinfo build.sh:

TERMUX_PKG_VERSION=1.0
TERMUX_PKG_HOMEPAGE=https://github.com/Oblomov/clinfo
TERMUX_PKG_DESCRIPTION="Tools for working with zip files"
TERMUX_PKG_SRCURL=https://github.com/Oblomov/clinfo/archive/master.zip
#TERMUX_PKG_DEPENDS="libandroid-support"
TERMUX_PKG_BUILD_IN_SRC=yes

termux_step_make () {
        prefix=$TERMUX_PREFIX LD="$CC $LDFLAGS" CC="$CC $CFLAGS $CPPFLAGS $LDFLAGS" PREFIX=$TERMUX_PREFIX make
}

termux_step_make_install () {
        prefix=$TERMUX_PREFIX make install

I copy  OpenCL lib from android phone's vendor/ folder  to ubuntu's data/data/com.termux/files/usr/lib, and then run ./build-package clinfo：

~/project/termux/termux-packages$ ./build-package.sh cli[550/1850]termux - building clinfo for arch aarch64...
aarch64-linux-android-gcc  -specs=/home/josh/project/termux/termux-packages/term
ux.spec -Os -I/data/data/com.termux/files/usr/include  -specs=/home/josh/project
/termux/termux-packages/termux.spec -L/data/data/com.termux/files/usr/lib -Wl,-r
path-link,/data/data/com.termux/files/usr/lib -Wl,-rpath-link,/home/josh/.termux
-build/_lib/toolchain-aarch64-ndk13-api21-v3/sysroot/usr/lib  -specs=/home/josh/
project/termux/termux-packages/termux.spec -Os -std=c99 -g -Wall -Wextra -pedant
ic -I/data/data/com.termux/files/usr/include  -c -o clinfo.o src/clinfo.c
aarch64-linux-android-gcc  -specs=/home/josh/project/termux/termux-packages/term
ux.spec -Os -I/data/data/com.termux/files/usr/include  -specs=/home/josh/project
/termux/termux-packages/termux.spec -L/data/data/com.termux/files/usr/lib -Wl,-r
path-link,/data/data/com.termux/files/usr/lib -Wl,-rpath-link,/home/josh/.termux
-build/_lib/toolchain-aarch64-ndk13-api21-v3/sysroot/usr/lib  -specs=/home/josh/
project/termux/termux-packages/termux.spec -L/data/data/com.termux/files/usr/lib
 -Wl,-rpath-link,/data/data/com.termux/files/usr/lib -Wl,-rpath-link,/home/josh/
.termux-build/_lib/toolchain-aarch64-ndk13-api21-v3/sysroot/usr/lib  clinfo.o  -
lOpenCL -ldl -o clinfo
/home/josh/.termux-build/_lib/toolchain-aarch64-ndk13-api21-v3/bin/../lib/gcc/aa
rch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: lib
hardware.so, needed by /data/data/com.termux/files/usr/lib/libOpenCL.so, not fou
nd (try using -rpath or -rpath-link)
home/josh/.termux-build/_lib/toolchain-aarch64-ndk13-api21-v3/bin/../lib/gcc/aa
rch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: lib
binder.so, needed by /data/data/com.termux/files/usr/lib/libOpenCL.so, not found
 (try using -rpath or -rpath-link)
/home/josh/.termux-build/_lib/toolchain-aarch64-ndk13-api21-v3/bin/../lib/gcc/aa
rch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: lib
c++.so, needed by /data/data/com.termux/files/usr/lib/libOpenCL.so, not found (t
ry using -rpath or -rpath-link)
/home/josh/.termux-build/_lib/toolchain-aarch64-ndk13-api21-v3/bin/../lib/gcc/aa
rch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: lib
ion.so, needed by /data/data/com.termux/files/usr/lib/libOpenCL.so, not found (t
ry using -rpath or -rpath-link)
/data/data/com.termux/files/usr/lib/libOpenCL.so: undefined reference to `strstr
@LIBC'
/data/data/com.termux/files/usr/lib/libOpenCL.so: undefined reference to `__stac
k_chk_guard@LIBC'
/data/data/com.termux/files/usr/lib/libOpenCL.so: undefined reference to `ftell@
LIBC'
.....

**Comment by xeffyr** [comment]
Closing because:
* outdated, NDK no longer provides GCC.
* probably better to use ocl-icd (https://github.com/OCL-dev/ocl-icd) like done by Debian or Arch Linux.
