### ISSUE TITLE
Arabic language

### ISSUE THREAD

**Issue by karim-menad** [termux/termux-packages#5855]
Is there any way to add arabic language to termux?
For exampel when we open nano editor  & type an arabic word it does not appear correctly.
![Screenshot_2020-09-27-13-36-04](https://user-images.githubusercontent.com/45332520/94365145-6ac8c800-00c6-11eb-8997-c5f7a32940ea.png)

**Comment by xeffyr** [comment]
Same as https://github.com/termux/termux-app/issues/1256. Pull requests are wanted to fix this.
