### ISSUE TITLE
Packages fail to update on a a freshly installed app.

### ISSUE THREAD

**Issue by Saniee** [termux/termux-packages#5858]
**Problem description**

Whenever I try to update my packages, it prints out -
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg received a segmentation fault.

**Steps to reproduce**

1. Install a fresh termux installation
2. Do pkg update

**Expected behavior**

It should update the packages.

**Additional information**

* Termux application version: 0.99
* Android OS version: 8.1.0

**Comment by xeffyr** [comment]
WIP (fix guide is incomplete)!

As `dpkg` is totally broken, you have no other way than to manually put fixed binary. Here is a short **how-to**:

Download binary of **correct** architecture:
```
# aarch64
curl -L --output dpkg.gz https://github.com/termux/termux-packages/files/5289292/dpkg-aarch64.gz
```

Decompress file, copy to PREFIX and chmod to `755`:
```
gunzip dpkg.gz
cp -f dpkg $PREFIX/bin/
chmod 755 $PREFIX/bin/dpkg
```
You should have `dpkg` working. Do `apt update` and `apt upgrade`.

***

Attachments:
[dpkg-aarch64.gz](https://github.com/termux/termux-packages/files/5289292/dpkg-aarch64.gz)

**Comment by xeffyr** [comment]
Closing as fixes already present in repository and workaround is provided above.

**Comment by llinfeng** [comment]
I find the following quote from the [FAQ](https://wiki.termux.com/wiki/FAQ) very helpful. It is from section "How do I fix a broken environment?". 

> In cases where environment was broken due to package manager failure or deletion of some important files, the easiest way of recovery will be to delete whole $PREFIX, restart Termux application and install packages from scratch.

In short, two steps to fix a broken `pkg`:
1. `rm -rf $PREFIX`, and
2. Restart Termux on the phone.
