### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by amer607** [termux/termux-packages#5870]
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by RossComputerGuy** [comment]
JS can already be ran using `node` (`pkg install nodejs`).

**Comment by kcubeterm** [comment]
and if you want lightweight than install quickjs
`pkg install quickjs`
