### ISSUE TITLE
@Syedaanis you haven't spelled tmvenom correctly..

### ISSUE THREAD

**Issue by Dollardollar** [termux/termux-packages#5872]
@Syedaanis you haven't spelled tmvenom correctly..
Hello sir, I am also facing that particular problem too, whenever I try to clone to GitHub it asks for username and password,, please help me in resolving the issue🙏

**Comment by Dollardollar** [comment]
I've got problems trying to install a tool in my termux, please help me....

**Comment by kcubeterm** [comment]
https://github.com/termux/termux-packages/issues/5873#issuecomment-702080597

**Comment by xeffyr** [comment]
> @Syedaanis you haven't spelled tmvenom correctly..

Wrong repo @Dollardollar!
