### ISSUE TITLE
Termux/uname/pswd

### ISSUE THREAD

**Issue by Dollardollar** [termux/termux-packages#5873]
It's asking for GitHub username and passwd. @charslan....
..yeah I've got that issue too

**Comment by kcubeterm** [comment]
**why git ask for username and password while cloning any GitHub repo**

Here is possible reason

* Either that repository is private or deleted from GitHub. if that link don't give you a 404 error in your browser,it means you own that repo. then just fill username and password of your GitHub.

* There must be a typo. Check your URL again

* You only clone a public repo or repo that you own.
