### ISSUE TITLE
Error dpkg during update

### ISSUE THREAD

**Issue by Cyberdr3am** [termux/termux-packages#5877]
**Problem description**

Hi, i can't update the packages inside the application because i have got an error.

W: APT had planned for dpkg to do more than it reported back (0 vs 84).
   Affected packages: apt:arm bash:arm clang:arm coreutils:arm dash:arm dpkg:arm grep:arm libllvm:arm liblua53:arm liblua:arm luv:arm neovim:arm netcat:arm nmap:arm openssh:arm python:arm resolv-conf:arm

I have try to find a solution but i can't fix it.

**Expected behavior**

**Additional information**

```

```

**Comment by Grimler91** [comment]
The output you provided does not show the actual error it seems so hard to tell what is going on.

Forcing a fresh installation by removing $PREFIX probably fixes it, i.e. run 
```
rm -rf $PREFIX
```
and restart the app. This removes all installed packages but keeps your files in $HOME. 

See also https://wiki.termux.com/wiki/Recover_a_broken_environment

**Comment by xeffyr** [comment]
This is not an error.

```
W: APT had planned for dpkg to do more than it reported back (0 vs 84).
```
is usually shown when some packages were uninstalled. I have that displayed frequently but didn't noticed any breakage.
