### ISSUE TITLE
Nothing happened

### ISSUE THREAD

**Issue by mwm1998** [termux/termux-packages#5878]
I did the copy from Android and opened Termux.  I see typing and commands but I am not seeing my program loaded.
thanks
Michael Morton
mwm11998@Zohomail.com

**Comment by Grimler91** [comment]
I have no idea what you are doing, what you are seeing or what you expect to happen. Please provide the information requested in the [bug report template](https://github.com/termux/termux-packages/issues/new?template=bug_report.md)
