### ISSUE TITLE
Problem while running a github script 

### ISSUE THREAD

**Issue by sillentkiller420** [termux/termux-packages#5891]
is:issue is: while trying to run https://github.com/KevinLage/YouTube-Live stream-Blotter in termux android it ask for github username and password. When I enter username it don't type anything in password. Please help

**Comment by Grimler91** [comment]
The repository https://github.com/KevinLage/YouTube-Live does not exist or is a private repository.

It does not echo your password when you enter it so sounds like everything works as it should
