### ISSUE TITLE
package request: meson

### ISSUE THREAD

**Issue by RossComputerGuy** [termux/termux-packages#5893]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Link to home page and sources**
1. Home page: mesonbuild.com
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by Grimler91** [comment]
Do you get any errors with `pip3 install meson`?

**Comment by RossComputerGuy** [comment]
No, I never knew it was on pip

**Comment by Grimler91** [comment]
Great! Closing as we generally do not package python modules

**Comment by Gravelman-Root** [comment]
;-)))
i
 still learning emacs....
im about 6 months away from new subjects....
g
