### ISSUE TITLE
[Package Request] K9s, Kubernetes CLI 

### ISSUE THREAD

**Issue by Ludea** [termux/termux-packages#5910]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Link to home page and sources**
1. Home page: https://k9scli.io/
2. Source code: https://github.com/derailed/k9s

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

There is an arm64 binaries

**Comment by Grimler91** [comment]
Should be available once the CI build finishes: https://github.com/termux/termux-packages/runs/1230132258
