### ISSUE TITLE
please provide me apktool for termux

### ISSUE THREAD

**Issue by buddheshwar** [termux/termux-packages#5913]
![Screenshot_20201009-162303_Termux](https://user-images.githubusercontent.com/72606739/95575393-4537a900-0a4c-11eb-8682-c7be50579b1b.jpg)

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
1. Duplicate(regarding apktool request): https://github.com/termux/termux-packages/issues/1286
2. Apkmod is not a Termux package and never be. (note: apktool != apkmod)
