### ISSUE TITLE
Im Run Qemu in Termux Is Crash!

### ISSUE THREAD

**Issue by PC1266** [termux/termux-packages#5916]
My Version Android 10 Samsung A31 Im Run Qemu In 
Termux Is Crash (App Close Auto.) Help me I Can't Run Emu Pc.

**Comment by RossComputerGuy** [comment]
That doesn't explain much, how exactly are you running QEMU?

**Comment by PC1266** [comment]
@RossComputerGuy Use For Run Pc In Android.

Qemu-system-x86_64 

Me Open Wait a minute And then App Termux Is Crash!

**Comment by RossComputerGuy** [comment]
What do you mean by "App Termux is crash"? Your saying Termux itself crashes or QEMU crashes?

**Comment by PC1266** [comment]
@RossComputerGuy App Termux Crash!

**Comment by RossComputerGuy** [comment]
If you can capture a log of the Termux app running over ADB and send it here then that can help a lot.

**Comment by RossComputerGuy** [comment]
Enable developer mode, connect your phone to a computer, install the Android SDK tools, then use `adb logcat`

**Comment by PC1266** [comment]
Ok

**Comment by xeffyr** [comment]
Seems like out-of-memory condition. If so - won'tfix from our side since user error. Watch out for given command line options! QEMU won't give you emulated system with better hardware properties than host device.

**Comment by Gravelman-Root** [comment]
is running qemu in termux redundant.....?
will it overload the ram?

**Comment by xeffyr** [comment]
Not redundant if you know how to use it. If you just copy-pasted its command from the Internet without verifying whether options are applicable for your device, yes it may crash Termux.

**Comment by Gravelman-Root** [comment]
Thanks!!!
gs
