### ISSUE TITLE
Please provide me keytool for termux its not in path

### ISSUE THREAD

**Issue by buddheshwar** [termux/termux-packages#5921]
![Screenshot_20201010-204716_Termux](https://user-images.githubusercontent.com/72606739/95658738-3f1ff600-0b3a-11eb-9d43-a5e0437c0eba.jpg)

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by kcubeterm** [comment]
Install java and keytool from third party, https://github.com/MasterDevX/Termux-Java

Since it requires proot in order to work, take a look of this issue as well https://github.com/MasterDevX/Termux-Java/issues/3

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/5913#issuecomment-706118171
