### ISSUE TITLE
improve exiting termux

### ISSUE THREAD

**Issue by cauerego** [termux/termux-packages#5922]
# description
exiting termux can cause a bind error if there's a process running on an open port.

# steps
have some service running in a termux session which uses local ports (in my case, it was jekyll).

then exit termux without stopping or killing the service's process. (in my case, i do it by using EXIT button, under termux running notification, as to close all sessions at once).

next time you try to run the same service on the same port, you'll get a [bind error](https://hea-www.harvard.edu/~fine/Tech/addrinuse.html) (which supposedly [can be fixed](https://stackoverflow.com/a/15199016/274502) with `SO_REUSEADDR`) such as this: 

`jekyll 3.9.0 | Error:  Address already in use - bind(2) for 127.0.0.1:4000
`

# expected
termux could kill the running process before exiting itself.

edit: that was just an instance. i just need an easy way to FORCE QUIT termux, from the android perspective, and quit everything. to save battery. per android design, that's what i expected from the EXIT button under notification. more over, looks like there's no way to kill that process that was left open by EXIT other than FORCE QUIT (perhaps this should be a second issue on its own?).

**Comment by Grimler91** [comment]
Could maybe add a "kill all processes" buttom, but exiting termux should not kill all processes running in the background, that's not how it works on a normal GNU/Linux system.

Note that you can kill the old jekyll process with `pkill jekyll`, or `kill <PID>`.

**Comment by Grimler91** [comment]
Could maybe add a "kill all processes" buttom, but exiting termux should not kill all processes running in the background, that's not how it works on a normal GNU/Linux system.

Note that you can kill the old jekyll process with `pkill jekyll`, or `kill <PID>`.

**Comment by xeffyr** [comment]
Sending `KILL` (9) signal during Termux shut down has bad side effects:
* **Data loss.** For example, many text editors handle SIGHUP when terminal is closed and force-save changes to disk (e.g. `.swp` file in vim and `.save` in nano). SIGKILL terminates program immediately without giving chance for graceful shutdown.
* **Left garbage files.** Unix sockets, lock files or pidfiles can be left in file system and some programs which do not support concurrent execution may refuse to start until these files are deleted.

***

If you really want to close all processes, try this:
```
killall -9 -u $(id -un)
```
That command will terminate all processes within Termux user id, including application itself.

**Comment by cauerego** [comment]
> Could maybe add a "kill all processes" buttom,
sure! that works. ideally with a good distance from the "EXIT" button. to the right side of "release wakelock" is fine by me.

> that's not how it works on a normal GNU/Linux system.
i never knew that.

 
> Note that you can kill the old jekyll process with `pkill jekyll`, or `kill <PID>`.
nope. i don't think we can find the PID or even using `killall jekyll` doesn't work. just tried it. at least killall brings a clear "can't find process" error message.

> If you really want to close all processes, try this:

also didn't work. `Cannot find user u0_a281`

please, do take my "expected" result with a grain of salt. perhaps there's another signal you could send that makes sense. QUIT? i don't know.

if nothing else, the TERMINATE ALL button is good enough for me...

even further, i'll be more than happy if there's a command to just "FORCE QUIT" termux from within.

what bothers me is my current best way to fix this is going to APP INFO and "killing" everything from there. i'll edit op to better reflect this.

**Comment by xeffyr** [comment]
> nope. i don't think we can find the PID or even using killall jekyll doesn't work.

Daemonized processes are often make PID 1 (/init) their parent and became invisible for Termux because /proc is mounted with hidepid option.

> also didn't work. Cannot find user u0_a281

Interesting how we'll send signal to processes in this case... Android "force-stop" works on much higher privilege level than regular application.

**Comment by cauerego** [comment]
not follownig what's hidepid or why the process would turn into PID 1...

but i hope the issue is clear now!

do you think it's even a termux issue?or, rather, an issue that could and should be fixed in termux?

**Comment by xeffyr** [comment]
> not follownig what's hidepid

hidepid - see https://man7.org/linux/man-pages/man5/proc.5.html (mount options)

> why the process would turn into PID 1

Read carefully, I didn't wrote that it would turn into PID 1 but their PPID.

In Termux, typical process tree looks like on this screenshot:
![Screenshot_20201012-212853_Termux](https://user-images.githubusercontent.com/25881154/95779098-16caff80-0cd2-11eb-9280-f67cf442e188.png)

You may see entries with question marks, they are unknown processes which exist but cannot be identified due to `hidepid` mount option. Termux can see only processes owned by its user id (`id -u`) when they are within same session (not terminal session!).

Certain programs execute fork() + [setsid()](https://man7.org/linux/man-pages/man2/setsid.2.html) + fork() system calls when daemonizing to move into new session and never be able to regain controlling terminal. This seems cause process to have parent process id (PPID) `1` which corresponds to `/init`, according to `ps` & `pstree` under ADB.
