### ISSUE TITLE
I tried many time but i can't solve this in my termux please solve that issue......please show me step to solve it...

### ISSUE THREAD

**Issue by buddheshwar** [termux/termux-packages#5925]
![20201011_114814](https://user-images.githubusercontent.com/72606739/95671699-afb92800-0bb7-11eb-9a51-74665143f44b.jpg)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by Hax4us** [comment]
you modified `apk.rb` in wrong way hence you are facing this type of error. Reinstall metasploit or replace old `apk.rb`
