### ISSUE TITLE
Apktool not work after download apktool.2.4.1.jar version...please help me..

### ISSUE THREAD

**Issue by buddheshwar** [termux/termux-packages#5926]
![20201011_130509](https://user-images.githubusercontent.com/72606739/95672976-76d28080-0bc2-11eb-9075-21db09468b0c.jpg)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by OldiLo** [comment]
Your have java in termux?

**Comment by xeffyr** [comment]
@buddheshwar Time to understand that we are not providing any help with third-party packages (JDK, Apktool) and hacking tools (msfvenom).
