### ISSUE TITLE
my termux can't compile java this type error please solve it....

### ISSUE THREAD

**Issue by ROLNO0020** [termux/termux-packages#5937]
![20201013_100125](https://user-images.githubusercontent.com/72780685/95816132-f9328000-0d3b-11eb-8999-60b03c0c4bf3.jpg)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by RossComputerGuy** [comment]
@xeffyr This looks like the same guy under a different account name, setup looks exactly the same.

**Comment by ROLLNO0020** [comment]
> @xeffyr This looks like the same guy under a different account name, setup looks exactly the same.

I use T-Header tool 

> @xeffyr This looks like the same guy under a different account name, setup looks exactly the same.

I use T-Header tool  https://github.com/remo7777/T-Header

**Comment by Grimler91** [comment]
@ROLNO0020 your questions are barely related to termux. They are also badly written and gives the impression that you have just copy-pasted some instructions online. 

You also have not filled in the bug report template. If you cannot even bother to do that then why should any one bother helping you.
