### ISSUE TITLE
What commands are installed in Termux by default? 

### ISSUE THREAD

**Issue by T-vK** [termux/termux-packages#5939]
I  have created a Termux package which depends on the following executables:
'bash' 'git' 'wget' 'tr' 'sed' 'cut' 'grep' 'head' 'tail' 'printf' 'cat' 'sort' 'rev' 'xxd'

I have added those as dependencies for my package, but when I install it can't find tr, head, tail, printf, cat, sort, rev, and xxd.

Obviously that's because there are are no packages with those names. 
How do I figure out which packages these executables actually belong to?
Or are they all installed in Termux by default?

**Comment by Grimler91** [comment]
You can run `$PREFIX/libexec/termux/command-not-found cmd` to see which package provides `cmd`. It works for all packages that were present in the [last command-not-found list generation](https://github.com/termux/command-not-found/commit/f00fbdd6c8b08e3754c5f1dde71c7e186ba90b8c). It does not work for commands that are built into the shell though, but your list does not seem to contain any of those.

The packages that are installed by default are listed in the [generate-bootstraps.sh(https://github.com/termux/termux-packaging/blob/5a375fbd21b370ab504ede8d7a6f220e1346c648/scripts/generate-bootstraps.sh#L312) script].
