### ISSUE TITLE
libgcrypt 1.7.4+ causes segmentation fault in Profanity

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#594]
Profanity segfaults when an otr session is started.
bt: 
```
#0  0x0000007fb7464ff8 in ?? () from /data/data/com.termux/files/usr/lib/libgcrypt.so
#1  0x0000007fb586aa60 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

Is this possibly related to #587 since it was last updated at the same time?

This feature has definitely worked before.

**Comment by fornwall** [comment]
Could you give steps how to reproduce this (as I've never used profanity or otr sessions before)?

I may be unable to look into this before I'm back from a trip at 19:th december, but will look into the issue then.

**Comment by Neo-Oli** [comment]
I've been trying to find an easier isolated testcase. but couldn't find one.

1. register at any of [these](https://xmpp.net/directory.php) services
2. launch profanity
3. `/account add me`
4. `/account set me jid <username>@service.tld`
5. `/account set me server <server>`
6. `/connect me`
7. `/otr gen`

= Segfault

If you already have a keypair, every other `/otr` command causes a segfault (`/otr myfp`)

**Comment by Neo-Oli** [comment]
I rebuild and downgraded to libgcrypt 1.7.3 and the problem vanished. Rebuilding 1.7.4 doesn't fix it like it did in  #587

**Comment by fornwall** [comment]
Thanks! The issue seems to be with libgcrypt 1.7.4. I've reverted back to 1.7.3 for now (the package v

**Comment by Neo-Oli** [comment]
Apparently libgcrypt was just updated to [1.7.5](https://lists.gnupg.org/pipermail/gnupg-announce/2016q4/000399.html). I built and tested it, but the error persists.

**Comment by fornwall** [comment]
I'm reopening the issue as we still have a problem in that we cannot update libgcrypt to 1.7.5.

From the [libgcrypt 1.7.5 release announcement](https://lists.gnupg.org/pipermail/gnupg-announce/2016q4/000399.html):

   - More ARMv8/AArch32 improvements for AES, GCM, SHA-256, and SHA-1.
   - Add ARMv8/AArch32 assembly implementation for Twofish and Camellia.
   - Add bulk processing implementation for ARMv8/AArch32.

Perhaps any of the above changes causes the issue?
