### ISSUE TITLE
Problem with pip in Termux

### ISSUE THREAD

**Issue by YorkIsMine** [termux/termux-packages#5940]
I installed termux and downloaded python. But when I want to install some python package via pip termux print, that pip command not found

**Comment by xeffyr** [comment]
Seems like something failed when you installed `python` package. Utility `pip` usually is being installed by postinst script automatically. If not, install it manually with:
```
python3 -m ensurepip --upgrade --default-pip
```

**Comment by YorkIsMine** [comment]
> Seems like something failed when you installed `python` package. Utility `pip` usually is being installed by postinst script automatically. If not, install it manually with:
> 
> ```
> python3 -m ensurepip --upgrade --default-pip
> ```

I have a pip directiory, but not pip file
