### ISSUE TITLE
Nim tools

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#5945]
Just installed nim but it doesn't come with tools it's supposed to come with.

Things like `nimpretty`/`nimsuggest` etc.

`koch` can build them but the files aren't even bundled with the termux package so it can't find them
```
✘  ~/n/  koch tools
/data/data/com.termux/files/usr/bin/nim c -o:bin/nimsuggest -d:release -d:danger  nimsuggest/nimsuggest.nim
oserr.nim(94)            raiseOSError
Error: unhandled exception: No such file or directory
Additional info: "nimsuggest" [OSError]
FAILURE
```

**Comment by citpaingoo** [comment]
`abs_path = os.path.abspath(os.path.dirname(__file__))'
