### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by rayonLucid** [termux/termux-packages#5947]
I was trying to run this command

$ python visit_msg_join_wd.py
Then I got the error message

XXX lineno: 15, opcode: 53
Traceback (most recent call last):
  File "/storage/emulated/0/cryatalbot/visit_msg_join_wd.py", line 2, in <module>
File "<zen_ezz>", line 15, in <module>
SystemError: unknown opcode

What did I do wrong that's causing this error?

**Comment by xeffyr** [comment]
Few things that you should be aware of:
* This script is not part of Termux packages, so you will not get help for it there.
* You have not provided the script *source code* or at least link to its repository.
* The message you posted provide very few information about the issue. Not very helpful.

Termux maintainers will not bother debug third party scripts.

***

It seems you are trying to run byte-compiled script which was made for older python version. I'm suggesting you to stop use `coin clickbot scripts`, especially closed-source. 99% of them is scam, all profit goes to their author.
