### ISSUE TITLE
PR: Syncthing

### ISSUE THREAD

**Issue by gerroon** [termux/termux-packages#595]
Hi

Can we please have Syncthing in the repo?

thanks

**Comment by Neo-Oli** [comment]
Similar with python and pip you can install go packages with go get:
1. `apt install golang git #git is a requirement of syncthing`
2. add `export GOPATH=$HOME/.go` to your .bash_profile (or your shell's equivalent)
3. `go get github.com/syncthing/syncthing/cmd/...`

This should install syncthing on termux (with some [caveats](https://forum.syncthing.net/t/why-does-syncthing-use-such-a-strange-building-system/1004/10)). I am not a user of it myself, but I was able to open the webinterface without problems.

**Comment by gerroon** [comment]
I get "no buildable go source files"

**Comment by Neo-Oli** [comment]
Yeah sorry about that. Turns out they broke something with the go get-able version and it only works after you regularly build syncthing.
so you need to `cd ~/.go/src/github.com/syncthing/syncthing` and run `go run build.go` after that the binaries will be in the bin subdirectory.

**Comment by gerroon** [comment]
ohh well, thanks for your help. Still it will be better if this package is in the repo ;)

**Comment by Neo-Oli** [comment]
I agree

**Comment by Neo-Oli** [comment]
I'm closing this. Syncthing is available now. Install it with `packages install syncthing`

**Comment by gerroon** [comment]
Thanks
