### ISSUE TITLE
I want to install a library for Steam

### ISSUE THREAD

**Issue by reb00tproject** [termux/termux-packages#5957]
I want to install a server for Rust, but I do not have basic packages installed 
writes:
# sudo apt-get install lib32gcc1
You should not use command 'apt-get' as root.
This is dangerous as may damage your Termux installation and data.
#

When you start SteamCMD:
# cd ~/steamcmd
# ls
linux32  steamcmd.sh  steamcmd_linux.tar.gz
# ./steamcmd.sh
./steamcmd.sh: line 37: /data/data/com.termux/files/home/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
#
___________________________________________________
Yes, yes, many can say that Steam to Rust's server may not start on my phone.
Phone characteristics:
Xiaomi Mi 6
128 GB, RAM 6 GB

**Comment by Grimler91** [comment]
Several things to unpack here.

* termux != ubuntu, we do not have the same packages. lib32gcc1 does not exist.

* You should not use apt as root. There is no reason for doing that, /data/data/com.termux/files/usr is writeable without root.

* "cannot execute binary file: Exec format error" means that you are trying to run a program compiled for x86 on an arm device. This simply will not work. You can only run programs compiled for the arm and against android's libc.
