### ISSUE TITLE
Package request: Translate Shell

### ISSUE THREAD

**Issue by thetoolz** [termux/termux-packages#5962]
Translate Shell (formerly Google Translate CLI) is a command-line translator powered by Google Translate (default), Bing Translator, Yandex.Translate, and Apertium.

It gives you easy access to one of these translation engines in your terminal

https://github.com/soimort/translate-shell

**Comment by kcubeterm** [comment]
It is already available in termux. Install it by 
```
pkg install translate-shell

```
