### ISSUE TITLE
Disturbed

### ISSUE THREAD

**Issue by jkelly2477** [termux/termux-packages#5963]
Using termux for I guess about six months now without too many problems I enjoy learning and everything on it every day because I'm new to it but I just recently ran across an issue of getting after I installed arch-linux. When trying to use Metasploit it keeps returning segmentation fault. So then I proceeded to clear all data and start over.. when attempting to install packages is what I received Progress: [  0%]
Progress: [  0%]/data/data/com.termux/files/usr/bin/pkg: line 127: 11834 Killed                  apt install "$@". How can I fix this?

**Comment by xeffyr** [comment]
Fixed in Ruby `2.7.2-2`.

Try
```
apt purge -y metasploit
apt update
apt upgrade -y
apt install metasploit
```

***

If using mirrors, Ruby `2.7.2-2` may not be available at the moment as mirror is not updated immediately, but you can switch to another repository with `termux-change-repo`.
