### ISSUE TITLE
lighttpd

### ISSUE THREAD

**Issue by jackiesparks** [termux/termux-packages#5964]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**
Lighttpd is a httpd server daemon that utiizes light weight server and infrastructured enviroments in order to reduce and increase typically video thruput that has a advanced json configuration that is modular and highly optimizable that take advantage of kernel FAM. It also enables PHP socket driven enhancements.

I believe this is a more acceptable for a tAmp( Termux Android Apache MySQL PHP) stack installation on mobile and lightweight SSD devices. Instead would be coined a tawmp stack or maybe something else.

**Link to home page and sources**
1. Home page: https://www.lighttpd.net
2. Source code: https://www.lighttpd.net/download/

**Additional information**
Have you compiled or tried to compile the package on device? Yes
* If it did not work then please provide the error you ran into. It mentioned to compile with no library dependecy checks inthe configure in order to comple the elf binary format file.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
Why you have submitted pull request without doing search before? Package is already available.
```
pkg install lighttpd
```
