### ISSUE TITLE
Package constantly upgradable

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#5972]
Anybody know what's going on with `nodejs-lts`? It shows as upgradable every other day. 
```
$ apt list --upgradable -a
Listing... Done
nodejs-lts/stable 12.18.3 aarch64 [upgradable from: 12.18.3]
nodejs-lts/stable,now 12.18.3 aarch64 [installed,upgradable to: 12.18.3]
```
I have `12.18.3` installed but it askes me to upgrade to `12.18.3`. If I do it it will go away (even if I do another `apt update`). But the same upgrade will show up a day or so later again.

**Comment by Grimler91** [comment]
Best guess would be that it switches between downloading from https://dl.bintray.com/termux/termux-packages-24/pool/n/nodejs-lts/ and https://dl.bintray.com/termux/termux-packages-24/aarch64/. The former folder should not be there and was probably created (and not removed) by bintray's metadata generation script. The pool folder has been present for a couple of months at least.

We can try bumping nodejs-lts and see if it helps.

**Comment by xeffyr** [comment]
@Grimler91 Best thing to do here is to delete and then re-submit the package.

**Comment by Grimler91** [comment]
@xeffyr alright, lets do that when the current build finishes

**Comment by Grimler91** [comment]
Nice, that worked, no more pool folder!
