### ISSUE TITLE
Add ghci

### ISSUE THREAD

**Issue by 0syf3r** [termux/termux-packages#5973]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

Since we have ghc now I think it should be pretty easy also add ghci.

**Comment by danwdart** [comment]
ghci comes in the ghc package, surely?

**Comment by danwdart** [comment]
Yes, ghc got removed.

**Comment by danwdart** [comment]
Sounds like #80 needs to be reopened.

**Comment by xeffyr** [comment]
Someone just need to fix https://github.com/termux/termux-packages/tree/master/disabled-packages/ghc. Package `ghc` was available previously (therefore https://github.com/termux/termux-packages/issues/80 shouldn't be reopened), but after NDK upgrade it became incompatible with current Clang / LLVM version.

**Comment by danwdart** [comment]
Fair enough. Maybe the incompatibility came because the termux version is on 8.10.1 and the latest is 9.2.1.

**Comment by danwdart** [comment]
Ended up putting https://github.com/termux/termux-packages/pull/7996 in - but that's as far as I currently know - I'm not sure if that will build yet.

**Comment by xtkoba** [comment]
Active.

**Comment by xerz-one** [comment]
Hey, what's the current situation? I find it baffling that `ghc` is available but it doesn't ship with `ghci` or `runghc`, any reasons for it?

**Comment by danwdart** [comment]
I think it just needs me to fix #7996 which I hadn't  gotten around to yet.

**Comment by danwdart** [comment]
Wait no, someone did #8436 instead to migrate a newer version. If that didn't contain ghci, maybe the author needs poking.

**Comment by danwdart** [comment]
Apparently that flag is for whether to compile dynamically.
