### ISSUE TITLE
Add neovim nightly to unstable package repo

### ISSUE THREAD

**Issue by Akianonymus** [termux/termux-packages#5985]
According to their roadmap, it will be a while till it gets stable.

So, just having in the unstable repo would be a lot of help.

**Comment by grejioh** [comment]
I am very looking forward to this package！

**Comment by numToStr** [comment]
I am excited to use the lua api. I hope neovim nightly to be available soon.

**Comment by reo101** [comment]
Very eager to try out native LSP and Treesitter. I've been trying to compile it for a few months myself but with no success. (Building inside proot is flawless tho)

**Comment by ShivamKumar2002** [comment]
Looking forward to it

**Comment by xtkoba** [comment]
The latest release 0.6.0 was made less than a month ago which is already packaged. Isn't it sufficient?

**Comment by xtkoba** [comment]
Available now.
