### ISSUE TITLE
How to setting php-pgsql ...

### ISSUE THREAD

**Issue by kusmantopratama** [termux/termux-packages#5988]
how to install and setting or make php-pgsql enable or work for php on termux .

**Comment by xeffyr** [comment]
```
pkg install php php-pgsql apr-util
echo "extension=pgsql.so" >> $PREFIX/lib/php.ini
```

![Screenshot_20201105-122106_Termux](https://user-images.githubusercontent.com/25881154/98228607-76c76580-1f61-11eb-848d-de141ff01f2c.png)

**Comment by kusmantopratama** [comment]
> ```
> pkg install php php-pgsql apr-util
> echo "extension=pgsql.so" >> $PREFIX/lib/php.ini
> ```
> 
> ![Screenshot_20201105-122106_Termux](https://user-images.githubusercontent.com/25881154/98228607-76c76580-1f61-11eb-848d-de141ff01f2c.png)

Thank you very much, its work perfectly
