### ISSUE TITLE
mpv ytdl://

### ISSUE THREAD

**Issue by atomi** [termux/termux-packages#599]
Just want to say mpv on nexus 7 works fine.

But would it be too much trouble to compile mpv with youtube-dl (ytdl://) support? Thanks.

```
$ uname -a
Linux localhost 3.4.0-gad29d11 #1 SMP PREEMPT Sat Jul 2 00:00:53 UTC 2016 armv7l Android

$ apt show mpv
Package: mpv
Version: 0.22.0-2
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 1130 kB
Depends: ffmpeg, openal-soft
Homepage: https://mpv.io/
Download-Size: 368 kB
APT-Manual-Installed: yes
APT-Sources: http://termux.net stable/main arm Packages
Description: Command-line media player
```

**Comment by pranavg189** [comment]
youtube-dl support would be great for mpv.....highly requested feature :+1:

**Comment by feserafim** [comment]
You can install youtube-dl by using pip:
```bash
$ pip install youtube_dl
```

If you don't have pip installed, you have install python:
```bash
$ apt install python
```

Greetings.

**Comment by pranavg189** [comment]
Hi @feserafim ,

What @atomi  and I meant was, if termux mpv is compiled with ytdl:// support, then you can play youtube video directly by specifying:

`mpv [URL of youtube video]`

Currently, the termux mpv package is built without lua support which is required for this feature to work.

Regards

**Comment by xeffyr** [comment]
Closing in favor of https://github.com/termux/termux-packages/issues/799.
