### ISSUE TITLE
Error running 'pkg update' after previously updating apt.

### ISSUE THREAD

**Issue by imnisp** [termux/termux-packages#5994]
I am on Android 7.x

**Problem description**

Last night apt was updated:
Preparing to unpack .../apt_2.1.11_aarch64.deb ...      Unpacking apt (2.1.11) over (1.4.10-6) ...              Setting up apt (2.1.11) ...

**Steps to reproduce**

Today when I attempt to 'pkg upgrade' I get the following:

@$ pkg update                                           Testing the available mirrors:                          [*] https://dl.bintray.com/termux/termux-packages-24: ok[*] https://grimler.se/termux-packages-24: ok           [*] https://main.termux-mirror.ml: ok                   [*] https://termux.mentality.rip/termux-packages-24: ok Picking mirror: https://termux.mentality.rip/termux-packages-24                                                 CANNOT LINK EXECUTABLE "apt": cannot locate symbol "glob" referenced by "/data/data/com.termux/files/usr/lib/libapt-pkg.so"...                                          /data/data/com.termux/files/usr/bin/pkg: line 127: 22948 Aborted                 apt update

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
> Today when I attempt to 'pkg upgrade' I get the following:

That's a known issue for `2.1.11` but 22 hours ago a `2.1.11-2` was released. So I don't know how you managed to get a broken one as it was deleted...

Install fixed version manually:
```
curl -LO https://dl.bintray.com/termux/termux-packages-24/aarch64/apt_2.1.11-2_aarch64.deb
dpkg -i apt_2.1.11-2_aarch64.deb
```
