### ISSUE TITLE
Postgres - add collation

### ISSUE THREAD

**Issue by kadeshar** [termux/termux-packages#5996]
Hi,
i tried add collation to installed postgres but without success. I wanna use collation (LC_COLLATE and LC_CTYPE) Polish_Poland.1250 to create new database. Is there possible in termux envoirment?

CREATE DATABASE "TestDB"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Polish_Poland.1250'
    LC_CTYPE = 'Polish_Poland.1250'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

**Comment by xtkoba** [comment]
Not possible, unfortunately. As I wrote before, Bionic libc does not have decent locale support.

Closing as answered.
