### ISSUE TITLE
golang: arm-linux-androideabi-gcc not found in $PATH

### ISSUE THREAD

**Issue by vainikkaj** [termux/termux-packages#6]
Package compilation fails with cgo

    $ go get -v -x github.com/onsi/ginkgo/ginkgo
    WORK=/data/data/com.termux/files/usr/tmp/go-build603239337
    runtime/cgo
    mkdir -p $WORK/runtime/cgo/_obj/
    mkdir -p $WORK/runtime/
    cd /data/data/com.termux/files/usr/lib/go/src/runtime/cgo
    CGO_LDFLAGS="-g" "-O2" "-lpthread" /data/data/com.termux/files/usr/lib/go/pkg/tool/linux_arm/cgo -objdir $WORK/runtime/cgo/_obj/ -importpath runtime/cgo -import_runtime_cgo=false -import_syscall=false -- -I $WORK/runtime/cgo/_obj/ -Wall -Werror cgo.go
    # runtime/cgo
    exec: "arm-linux-androideabi-gcc": executable file not found in $PATH

**Comment by fornwall** [comment]
Hi, this should be fix by the recent gcc and golang updates - execute `apt update && apt upgrade` to get them.

Re-open the issue if the problem still remains after the update!

**Comment by wari** [comment]
I have just installed termux and `apt update && apt upgrade && apt install golang`, and I still get this error.

**Comment by fornwall** [comment]
@wari Have you installed the`gcc` package?

That is needed when using cgo (but not by go in general, which is why the go package does not depend on it)!

**Comment by wari** [comment]
Thanks! That works.
