### ISSUE TITLE
g++ does not work

### ISSUE THREAD

**Issue by h-2** [termux/termux-packages#60]
First of all: wow, great app. First time my tablet is usable!!

I have installed g++ and nano to test some things, but I can't build a simple program:
```c++
#include <iostream>
int main()
{
    cout << "foobar\n";
    return 0;
}
```

Because I get undefined references to STL stuff. I saw that there is a libgnustl installed and I tried manually linking against that, but it didn't work either. Anything I am not doing right?

Thanks!

**Comment by h-2** [comment]
This is the full error:
ˋˋˋ
$ g++ -o test test.cpp
/data/data/com.termux/files/usr/tmp//cc7Vuucp.o: In function `main':
test.cpp:(.text+0x28): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
test.cpp:(.text+0x3c): undefined reference to `std::cout'
/data/data/com.termux/files/usr/tmp//cc7Vuucp.o: In function `__static_initialization_and_destruction_0(int, int)':
test.cpp:(.text+0x88): undefined reference to `std::ios_base::Init::Init()'
test.cpp:(.text+0xc8): undefined reference to `std::ios_base::Init::~Init()'
collect2: error: ld returned 1 exit status
ˋˋˋ

**Comment by fornwall** [comment]
If you replace `cout` with `std::cout` you should be able to compile the file with:

    g++ -lgnustl_shared -o test test.cpp

The reason you have to link against `libgnustl_shared.so` which Termux provides, is that you otherwise use the system C++ library, which on Android does not support the STL - see http://developer.android.com/ndk/guides/cpp-support.html.

**Comment by h-2** [comment]
I tried `-llibgnustl_shared` instead of `-lgnustl_shared` :facepalm: .

Thanks for the quick reply!

**Comment by fornwall** [comment]
Aha, great that it works for you now!
