### ISSUE TITLE
error while install opencv-python

### ISSUE THREAD

**Issue by luanon404** [termux/termux-packages#6002]
this is all packages i installed https://pastebin.com/UCYzxjPJ
i followed https://wiki.termux.com/wiki/Python but after done i couldn't find it in my pip list so i used `pip3 install opencv-python` and got this error https://pastebin.com/k7PTKuXk
any idea how to solve it?

**Comment by xeffyr** [comment]
Continue here: https://github.com/termux/termux-packages/issues/1992

opencv-python is not official Termux package.
