### ISSUE TITLE
Custom keyboard not working

### ISSUE THREAD

**Issue by wiwwo** [termux/termux-packages#6003]
Hi! With custom keyboard Big Button Keyboard Standard (`com.bitbutton`), only "Enter" key is recorgnized. I can type everything I want, nothing appears on screen abd nothing is typed at all.
Android (LineageOs) 7.1.2
Termux 0.101

**Comment by xeffyr** [comment]
Not all keyboards work out-of-box since Termux supports only generic input (character-by-character) and not the word-based.

See https://wiki.termux.com/wiki/Terminal_Settings, specifically this section: https://wiki.termux.com/wiki/Terminal_Settings#Workaround_for_some_keyboards_issues

**Comment by wiwwo** [comment]
Ok, so the solution is to put a setting into a (newly created) setting file...
How can one create this file without being able to use the keyboard at all?

**Comment by xeffyr** [comment]
There some ways:
* Use alternate text input: https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View
* Use a different keyboard
* Try to disable keyboard rich features like predictive input & autocorrection

**Comment by wiwwo** [comment]
I have noticed that clipboard works.
For those who can paste in terminal, you can copy this text

```
mkdir ~/.termux/ && echo "enforce-char-based-input = true" > ~/.termux/termux.properties

```
paste it into the terminal, and restart termux
