### ISSUE TITLE
gopass update, breaking changes

### ISSUE THREAD

**Issue by tetricky** [termux/termux-packages#6005]
Recent versions of gopass have breaking changes (new teams enhanced format only supported > 1.9.2), and a new format for secret storage. I use gopass for secret management for servers, and it would be a requirement for me to use termux to manage these (currently I am not doing, as a result).

Is there any prospect of an upgrade to gopass, to a more recent version, or should I consider this long term unsupported?

I appreciate this is somewhat niche, and do not expect support - I just want to qualify before eliminating this as a potential workflow.

Thanks
tet.

**Comment by Grimler91** [comment]
To clearify, you are requesting that gopass should be updated to 1.10.x (even though it has "breaking changes" as you put it)?

The package will be updated as soon as someone opens a PR to update it, or as soon as one of us spends some time on updating packages in the unstable repository.

**Comment by tetricky** [comment]
Clarification: gopass v1.10 has 'breaking changes' from the 1.9.x line. That is the structure used to store and access secrets is not compatible between versions. Also bugfixes inhibit cross-version workflows. Also necessary support for my specific use case. I have a need for 1.10.x features, that are not supported in the 1.9.x version. From the gopass CHANGELOG for 1.10.x

    [BREAKING] New secrets format
    [BUGFIX] Do not allow malformed secrets
    [FEATURE] Add summon provider

..plus various misc. issues.

**Comment by kcubeterm** [comment]
@tetricky gopass still not a part of termux repository , I think you have compiled it from source.

**Comment by tetricky** [comment]
https://github.com/termux/unstable-packages/tree/master/packages/gopass

**Comment by kcubeterm** [comment]
Alright, that's in unstable

**Comment by tetricky** [comment]
Correct.  There's no method to raise an issue anywhere other than here. There is a use case for this, particularly in server secret management from termux.

**Comment by kcubeterm** [comment]
> There's no method to raise an issue anywhere other than here

FYI : Reporting issues is disabled in unstable repo that's why you can't report issues there.

**Comment by tetricky** [comment]
I refer you to my initial post.

There is a potential use for gopass. It is a question, and request for clarification. Is there a possibility of a maintained package, or should this be considered long term unsupported?

I have no expectation or demand for 'action', just clarification.

"The package will be updated as soon as someone opens a PR to update it, or as soon as one of us spends some time on updating packages in the unstable repository." mechanism? likelihood?

The use case is as follows:

Go pass allows secret management in git. This allows for encrypted safe secret management without compromising those secrets and maintaining and distributing them safely across client devices. In conjunction with summon it also allows for configuration files (yaml) with embedded secrets, stored in git, passed encrypted, decrypted in place.

This enables secure server, cluster (kubernetes), container (docker), management remotely from termux. As well as useful normal password management from the command line. It would add utility where a computer/laptop is not accessible.

**Comment by Grimler91** [comment]
> There is a potential use for gopass. It is a question, and request for clarification. Is there a possibility of a maintained package, or should this be considered long term unsupported?

> I have no expectation or demand for 'action', just clarification.

We are currently 4 - 5 people trying to keep 1100+ packages up to date. Test-building, commiting and pushing updates takes some time and most often we tend to focus on keeping the packages in the main repository up to date.

Best way to get a specific package updated is to open a PR for it (see [Contributing.md](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#updating-packages)). Otherwise just wait until someone spends some time on updating the packages in unstable-packages.

**Comment by tetricky** [comment]
I appreciate the clarification.  I understand any project is the possible over the idiot ideas of randoms. No criticism implied. I was merely making the argument that there is a use case for gopass, which has some connection and use to the termux project.

**Comment by xeffyr** [comment]
I have read this issue and will update gopass soon.

@kcubeterm Issue reporting on unstable is disabled as it considered as "add-on" to main repo. Also unstable packages known to have issues unless specified otherwise.

**Comment by xeffyr** [comment]
Update has been pushed and new version of `gopass` should be available shortly: https://github.com/termux/unstable-packages/commit/9d0a5bfc9645a2a97075e576c41b9ddeb2db2851

@tetricky Could you confirm if `gopass` in Termux had ever worked at all? Last time I tried it, it failed at GPG key generation.

**Comment by tetricky** [comment]
I'm currently tied up working on other matters. Give me a few days, and I will test and report.

I have confirmed gopass is updated in termux packages (to 1.10.0 - not the current 1.10.1). This should support the mentioned features, and I will check the operation with gpg, and git, when I can put a bit of time to it.
