### ISSUE TITLE
Kill localhost process

### ISSUE THREAD

**Issue by lbh3110** [termux/termux-packages#6007]
Am unsure how to stop the localhost process everytime I open the termux app it seems to be still connected and still running.
Any ideas?

**Comment by Grimler91** [comment]
Which "localhost" process? 

Daemons and services can continue running in the background even if you close termux-app, this is intended.

**Comment by xeffyr** [comment]
@lbh3110 Use utilities like `kill`, `killall` or `pkill` to terminate running process.
