### ISSUE TITLE
very slow when typing hapoened after upfating

### ISSUE THREAD

**Issue by Oscar814** [termux/termux-packages#6009]

**Comment by Grimler91** [comment]
What do you mean with slow? What did you update? Please fill in the bug report template: https://github.com/termux/termux-packages/issues/new?template=bug_report.md

**Comment by Grimler91** [comment]
Maybe https://github.com/termux/termux-app/issues/686, which can be solved with https://github.com/termux/termux-app/issues/686#issuecomment-681026810.
