### ISSUE TITLE
Tab completion makes random characaters appear on enter.

### ISSUE THREAD

**Issue by neil-edelman** [termux/termux-packages#6011]
Tab completion very often makes seemingly random characters (but the same characters in the same spot on executing the same command) get mixed up on pressing enter on the end of the latest tab completion. The tab completion is fine until the user presses enter, then it (probably) fails.

**Comment by Grimler91** [comment]
Could you provide a screenshot of the problem, and your output of `termux-info`?
Is this with the touch keyboard or a hardware keyboard? How are you pressing tab, with vol up + t or by using the [extra-keys](https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row), or some other way?

**Comment by neil-edelman** [comment]
I am on a Samsung Galaxy 9, Android 10, patch Sept 1, 2020, and am using the Samsung keyboard OEM.

![Screenshot_20200717-171637_Termux](https://user-images.githubusercontent.com/774033/99159456-625b3980-26d4-11eb-858f-4dc4910be61e.png)

$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://main.termux-mirror.ml/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
gdk-pixbuf/stable 2.42.0 aarch64 [upgradable from: 2.40.0-2]
grep/stable 3.6 aarch64 [upgradable from: 3.5]
termux-tools/stable 0.97 all [upgradable from: 0.96]
Android version:
10
Kernel build information:
Linux localhost 4.9.186-18803994 #1 SMP PREEMPT Thu Aug 20 02:09:03 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G960W

**Comment by neil-edelman** [comment]
I am on a Samsung Galaxy 9, Android 10, patch Sept 1, 2020, and am using the on-screen Samsung keyboard OEM.

![Screenshot_20201114-234259_Termux](https://user-images.githubusercontent.com/774033/99159645-3b056c00-26d6-11eb-9cdc-89c4909ff575.png)

$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://main.termux-mirror.ml/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
gdk-pixbuf/stable 2.42.0 aarch64 [upgradable from: 2.40.0-2]
grep/stable 3.6 aarch64 [upgradable from: 3.5]
termux-tools/stable 0.97 all [upgradable from: 0.96]
Android version:
10
Kernel build information:
Linux localhost 4.9.186-18803994 #1 SMP PREEMPT Thu Aug 20 02:09:03 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G960W

**Comment by neil-edelman** [comment]
I observed it futher, and it's not just tab-completion. Every time I press space or enter, the terminal has a fairly high probability of inserting random, but seemingly deterministic characters, seemingly from my input buffer. It's variable lenght, but fairly close to the replaced text. It's most noticable on tab-completion.

**Comment by Grimler91** [comment]
Try the workaround for samsung keyboards described here: https://wiki.termux.com/wiki/Terminal_Settings#Workaround_for_some_keyboards_issues

**Comment by neil-edelman** [comment]
Yes, that sounds like exactly the problem. I couldn't reproduce it after the workaround, so I'm marking this closed. Thank you!
