### ISSUE TITLE
Promblem when doing update

### ISSUE THREAD

**Issue by zulcharis** [termux/termux-packages#6012]
Get:12 https://dl.bintray.com/xeffyr/x11-packages x11 Release.gpg [821 B]
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://main.termux-mirror.ml stable Release: The following signatures were invalid: BADSIG 5A897D96E57CF20C Termux Releases (Termux automatic builds) <contact@termux.com>
E: Release file for https://dl.bintray.com/grimler/game-packages-24/dists/games/Release is not valid yet (invalid for another 23h 42min 3s). Updates for this repository will not be applied.
E: Release file for https://dl.bintray.com/grimler/science-packages-24/dists/science/Release is not valid yet (invalid for another 23h 31min 29s). Updates for this repository will not be applied.
E: Release file for https://dl.bintray.com/xeffyr/x11-packages/dists/x11/Release is not valid yet (invalid for another 23h 31min 5s). Updates for this repository will not be applied.

How i can solved this problem? This happened when I did $ pkg update && pkg upgrade

**Comment by xeffyr** [comment]
I can't confirm the issue.
