### ISSUE TITLE
E: Unable to locate package python3

### ISSUE THREAD

**Issue by Pradeepking-hack** [termux/termux-packages#6018]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by Grimler91** [comment]
It's named python and not python3.
