### ISSUE TITLE
Package Request - Axel

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#602]
Axel.  This is a tiny download accelerator

https://github.com/eribertomota/axel

**Comment by mgsqz** [comment]
It will be very nice that add the axel package

**Comment by sdrausty** [comment]
> tiny download accelerator

```
$ pacman -Ss axel
community/axel 2.16.1-1
    Light command line download accelerator
community/haxe 3.4.4-1 (devel)
    Cross-platform toolkit and programming language
$ pacman -S axel
resolving dependencies...
looking for conflicting packages...

Packages (1) axel-2.16.1-1

Total Download Size:   0.04 MiB
Total Installed Size:  0.20 MiB

:: Proceed with installation? [Y/n]
```
Axel is available through Arch Linux in Termux PRoot https://sdrausty.github.io/TermuxArch/ today.

@mgsqz is is tiny as @ghost states.  Hopefully it is easy to package for Termux.

**Comment by mgsqz** [comment]
Sounds great!It is useful before termux package axel added.

**Comment by Hax4us** [comment]
https://github.com/termux/termux-packages/pull/2248 here is PR for this :)

**Comment by sdrausty** [comment]
Rapid prototyping to packaging overnight.  Awesome work @Hax4us, thank you :fast_forward:

**Comment by fornwall** [comment]
Thanks tp @Hax4us adding the package in https://github.com/termux/termux-packages/pull/2248 the package can now be installed with `pkg in axel`.
