### ISSUE TITLE
netcat-openbsd : "libbsd.so not found"

### ISSUE THREAD

**Issue by BlindB0** [termux/termux-packages#6020]
**Problem description**

Cannot run netcat-openbsd ("nc" command) after installation.
Get error: CANNOT LINK EXECUTABLE "nc": library "libbsd.so" not found
But libbsd.so exist in /data/data/com.termux/files/usr/lib/libbsd.so , 67824bytes
Android 9, last Termux, updated packages.
libbsd 0.10.0-1
netcat-openbsd 1.217-2-0

**Steps to reproduce**

1. pkg install netcat-openbsd
2. nc

**Comment by buttaface** [comment]
Simple, the nc binary doesn't have the Termux prefix in its runpath. Precisely where that's getting lost in the build, someone would have to dig into.
