### ISSUE TITLE
env: ‘python3’: Permission denied ERROR: Obtaining buildorder failed

### ISSUE THREAD

**Issue by luanon404** [termux/termux-packages#6021]
I am trying to install the python package manually, although I got some errors I fixed it when I get an error
`env: ‘python3’: There is no such file or folder`
I created the python3 directory in ../usr/bin, it worked, I didn't get the error anymore, but a new one came up
`env: ‘python3’: Permission denied
ERROR: Obtaining buildorder failed`
I tried to give permission to build-packages.sh file and python3 directory but still failed

**Comment by xeffyr** [comment]
Delete this `python3` folder you have created in `../usr/bin`. *Btw, making it is quite weird choice...Learn shell scripting!*

Install python package
```
apt install python
```

**Comment by luanon404** [comment]
> Delete this `python3` folder you have created in `../usr/bin`. _Btw, making it is quite weird choice...Learn shell scripting!_
> 
> Install python package
> 
> ```
> apt install python
> ```

new python is 3.9.0
but my program need python 3.8.0 to run

**Comment by xeffyr** [comment]
Ironically, to build python and in general to use our build environment, you need to have python installed.

So
```
apt install python
```
and continue!

**Comment by xeffyr** [comment]
Also, worth to check
1. https://github.com/termux/termux-packages/wiki/Build-environment
2. https://github.com/termux/termux-packages/wiki/Build-environment#termux - if building on device.

**Comment by kcubeterm** [comment]
> new python is 3.9.0
but my program need python 3.8.0 to run

@luanon404  You should Check here. https://github.com/Termux-pod/termux-pod.

**Comment by xeffyr** [comment]
@kcubeterm Downgrading it breaks some python packages provided by Termux, i.e. `asciinema`, `borg`, and others.
