### ISSUE TITLE
If i try to upgrade or to install new package it show error  '(invalid for another 1h 55min 6s). 

### ISSUE THREAD

**Issue by mikisol95** [termux/termux-packages#6023]
<!-- 
If i try to upgrade or to install new package it not work. It shows error like this

Release file for https://termux.org/packages/dists/stable/Release is not valid yet (invalid for another 1h 55min 6s). Updates for this repository will not be applied.
$

**Comment by mikisol95** [comment]
<!-- 
 It shows error like this

Release file for https://termux.org/packages/dists/stable/Release is not valid yet (invalid for another 1h 55min 6s). Updates for this repository will not be applied.
$

**Comment by Grimler91** [comment]
Same as https://github.com/termux/termux-packages/issues/6012. Try switching mirror with `termux-change-repo`.
