### ISSUE TITLE
Package request: mono c#

### ISSUE THREAD

**Issue by rc-chuah** [termux/termux-packages#6028]
**Package description**
Mono is a software platform designed to allow developers to easily create cross platform applications part of the .NET Foundation.

**Link to home page and sources**
1. Home page: https://www.mono-project.com
2. Source code: https://github.com/mono/mono

**Additional information**
* https://www.mono-project.com/download/stable/
* https://www.mono-project.com/docs/

**Comment by xeffyr** [comment]
Duplicate, use search!

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/40
