### ISSUE TITLE
Package request: PowerShell

### ISSUE THREAD

**Issue by rc-chuah** [termux/termux-packages#6029]
**Package description**
PowerShell Core is a cross-platform (Windows, Linux, and macOS) automation and configuration tool/framework that works well with your existing tools and is optimized for dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object models. It includes a command-line shell, an associated scripting language and a framework for processing cmdlets.

**Link to home page and sources**
1. Home page: https://docs.microsoft.com/en-gb/powershell/
2. Source code: https://github.com/PowerShell/PowerShell

**Additional information**
* https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.1
* https://docs.microsoft.com/en-gb/powershell/

**Comment by xeffyr** [comment]
Trouble with using search?

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/1729
