### ISSUE TITLE
The _imagingft C module is not installed in PIL

### ISSUE THREAD

**Issue by SuperBoyne** [termux/termux-packages#6032]
**Problem description**
When I try to use PIL to add text to images, the error says *The _imagingft C module is not installed*

**Steps to reproduce**
```
response = requests.get("https://raw.githubusercontent.com/SuperBoyne/bananabotfiles/main/win10bsod.png")
            img = Image.open(BytesIO(response.content))
            draw = ImageDraw.Draw(img)
            ImageDraw.Draw(img).text((100, 180), arg, (255, 255, 255), font=ImageFont.truetype("font.ttf", size=15))
            arr = BytesIO()
            img.save(arr, format='png')
            arr.seek(0)
```

**Expected behavior**
An edited image to pop out

**Additional information**
Used Python 3 for a Discord bot with image editing

**Comment by xeffyr** [comment]
`pkg install libfreetype` then reinstall `pillow` module. But ensure that `pip` won't reuse its cache before.

Not bug.

**Comment by SuperBoyne** [comment]
It says ```Unable to locate package libfreetype```

**Comment by WMCB-Tech** [comment]
try `pkg up`

**Comment by xeffyr** [comment]
Sorry, it is `pkg install freetype`

**Comment by SuperBoyne** [comment]
I used ```pkg up```, uninstalled and reinstalled PIL, and it worked! Thank you, I've spent hours looking for the solution!
