### ISSUE TITLE
Package Request : Rustscan

### ISSUE THREAD

**Issue by RupankarGhosh** [termux/termux-packages#6042]
_<ins>Description:</ins>_ 
Rustscan is a network scanning tool similar to nmap written in rust language. It supports general scripting engins like Python, Lua and shell.

_<ins>Link to source code </ins>_ 
[https://github.com/RustScan/RustScan](https://github.com/RustScan/RustScan)

**Comment by kcubeterm** [comment]
Package is now available. Can be Install via Package manager
