### ISSUE TITLE
Use p7zip fork instead source from original (dead) project

### ISSUE THREAD

**Issue by samoht0** [termux/termux-packages#6044]
Termux ships p7zip 16.02. The original project development is totally dead.
There's a fork trying to manage security and enhancements like new compression formats:
https://github.com/szcnick/p7zip
Development is active  with current commits. Latest release from june.

I'd like to suggest to change to that source.

**Comment by xeffyr** [comment]
Done in https://github.com/termux/termux-packages/commit/460e2ff7fe6cfd886c74c858aeb4a2156bec48d6.
