### ISSUE TITLE
Package request: Cordless

### ISSUE THREAD

**Issue by Midi-In** [termux/termux-packages#6048]
Description: Cordless is a CLI-based third party discord client.

Source code repository: https://github.com/Bios-Marcel/cordless

**Comment by WMCB-Tech** [comment]
Cool. I like it. Discord CLI

**Comment by Midi-In** [comment]
https://github.com/Bios-Marcel/cordless/compare/2020-11-22...master
Uhh, now this is unfortunate, and least expected

**Comment by WMCB-Tech** [comment]
bummer

**Comment by kcubeterm** [comment]
I think this issue should be close.
* Project will soon outdated.
* Discord don't allow third party client, and they ban users who use third party client.

* If user need they can compile with source.
