### ISSUE TITLE
Pygame not working

### ISSUE THREAD

**Issue by IshanKBG** [termux/termux-packages#6050]
I am not able to run pygame on Termux.Is there any trick to run on Termux
I saw a lot of people running pygame with the help of Termux.
Please help me if you know anything
I don't have a pc so I have no choice but rather practice pygame module on Termux.

**Comment by Grimler91** [comment]
Have a look at the [previous issues about pygame](https://github.com/search?q=org%3Atermux+pygame&type=issues). 

You have instructions that at least used to work in one of them: https://github.com/termux/termux-packages/issues/1411#issuecomment-723393020
