### ISSUE TITLE
suggestion: combine whatprovides and command-not-found

### ISSUE THREAD

**Issue by landfillbaby** [termux/termux-packages#6053]
if command-not-found relies on the same database as whatprovides, there'll be 1 less database to keep updated

**Comment by xeffyr** [comment]
It doesn't use same database.

**Comment by landfillbaby** [comment]
yes that's what i'm saying, we could rewrite command-not-found to use the whatprovides database

**Comment by kcubeterm** [comment]
Closing as per https://github.com/termux/termux-packages/issues/6053#issuecomment-731333710

**Comment by landfillbaby** [comment]
??? ok

**Comment by xeffyr** [comment]
command-not-found can switch to use whatprovides db. Right now it uses stuff embedded into `.h` files during compile time, that has number of issues such as static-only data (cannot be changed after package was built). Also it has data update related problems, where deleted packages are not being processed which leads to stale data present, e.g. https://github.com/termux/command-not-found/blob/master/termux-packages/commands-aarch64-e686fa9.h#L1311-L1314.

**Comment by twaik** [comment]
Closing since whatprovides is no longer available in our repos (but `apt-file` has `TERMUX_PKG_REPLACES="whatprovides"` in `build.sh`).
