### ISSUE TITLE
error build ctags version 0.0.20190412 

### ISSUE THREAD

**Issue by MohamedAhmedAliGpaly** [termux/termux-packages#6058]
packages : ctags 
Hi, I have a problem, which is that I cannot find version 0.0.20190412
https://github.com/universal-ctags/ctags/releases
You have modified the version to p5.9.20201115.0

My file log error Last Line  :   _buildall-aarch64/ctags.err

packcc: Cannot open file 'peg/varlink.peg' to read
make[2]: *** [Makefile:5188: peg/varlink.c] Error 2
make[1]: *** [Makefile:4380: all-recursive] Error 1
make: *** [Makefile:1135: all] Error 2

**Comment by xeffyr** [comment]
Sorry, but tag disappearance on upstream is not our problem. Seek on the Internet for v0.0.20190412.

**Comment by xeffyr** [comment]
If you mean to update the package, I'll look at this now.

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/aace105cb0d108c4280baaf4a950f952aced6c65, but please note that `./build-all.sh` is not being tested and we do not constantly checking the availability of upstream sources.

**Comment by MohamedAhmedAliGpaly** [comment]
Yes Sir, I meant that, and you did a great job. Now it's okay ,Thanks again
