### ISSUE TITLE
Package request: ed

### ISSUE THREAD

**Issue by ThoJer** [termux/termux-packages#606]
ed is the standard editor

**Comment by Neo-Oli** [comment]
I addad a Pull request for the ed package. It builds and seems to work, but I would appreciate someone that actually knows how to use ed to test it.

**Comment by ThoJer** [comment]
How can I test it?
'apt install ed' doesn't work yet.

**Comment by Neo-Oli** [comment]
Here are the compiled packages: 
[ed_1.13.tar.gz](https://github.com/termux/termux-packages/files/666411/ed_1.13.tar.gz)

You can install it by running 
```
 dpkg -i ed_1.13_`dpkg --print-architecture`.deb
```

**Comment by ThoJer** [comment]
After the first test, I see no unexpected behaviour.

**Comment by fornwall** [comment]
Great! The built package is now available in the apt repository.
