### ISSUE TITLE
CANNOT LINK EXECUTABLE "php": library "libtidy.so" not found

### ISSUE THREAD

**Issue by amm834** [termux/termux-packages#6061]
**Problem description**

When I upgrade by using
```
apt-get upgrade
```
Following command cannot execute and libtd.so file missing.
```
$php -v
CANNOT LINK EXECUTABLE "php": library "libtidy.so" not found
```

**Comment by xeffyr** [comment]
As temporary solution: `pkg install tidy`

**Comment by amm834** [comment]
> As temporary solution: `pkg install tidy`

Now it working
```
apt install tidy
```

**Comment by amm834** [comment]
When I test with my Apache Server I get some load module errors
So when upgraded this php 7.4 version
We need to reinstall 
```
pkg install php-apache
```
Again.If not install we cannot load module and get errors for php -7.
#Solution for php-7 Apache load module errors when upgraded php version 7.4.
