### ISSUE TITLE
QEMU Spice Support?

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/termux-packages#6062]
Hello is it possible to add SPICE Server and QXL Drivers to QEMU?

Now I've been trying to run QEMU Spice in termux but gaves me:
`spice support is disabled`

So is it possible to add it? because i could use QXL instead of standard vga Graphics + virtio drivers (so less overhead)

Just a suggestion,

**Comment by GoldenSkyWithGreenMeadows** [comment]
Why Not Use non-headless QEMU-SYSTEM-X86_64 Version 4.1.1 Instead it already has ALSA sound compiled and works for me in lieu of Spice. I hope this version atleast remains available even if SPICE is considered.

**Comment by GoldenSkyWithGreenMeadows** [comment]
Actually the non-headless appears to have been recently 
![Screenshot_20201123-030233_Termux](https://user-images.githubusercontent.com/74906263/99955132-aaafd280-2d38-11eb-9584-ae01deb1b518.jpg)
removed?

**Comment by WMCB-Tech** [comment]
@GoldenSkyWithGreenMeadows No. you have to enable x11-repo

Headless is for servers anyway

**Comment by GoldenSkyWithGreenMeadows** [comment]
I am sorry I am more a user vs contributer.

I have happily  been using the non-headless to run Windows 8.1 with Office 2016 Pro on a Samsung Galaxy Fold(Android Kernnel). This allowed me to give my Surface Laptop to my son for his School during this pandemic.

I really do hope QEMU-System-x86_64-headless with SPICE can be compiled into a future version for you. Although Personally I would perfer either the non-headless version back or a SPICEd up version would do. I actually need the error chimes the sound feedback gives.Take Care.

**Comment by RossComputerGuy** [comment]
GUI QEMU uses GTK and SDL, you can switch between using SDL or GTK

**Comment by GoldenSkyWithGreenMeadows** [comment]
I use Termux and the GUI pkg is no longer in the stable repo. It was pulled on the same day I posted the original comment above.

**Comment by xeffyr** [comment]
> I use Termux and the GUI pkg is no longer in the stable repo.

What is a "stable" repo? It is `termux-packages`? GUI build of qemu was never available in `termux-packages` but only its headless: https://bintray.com/termux/termux-packages-24/qemu-system-x86_64-headless

GUI variant is in `x11-repo`.

> It was pulled on the same day I posted the original comment above.

Maybe you have reset your Termux installation on the same day and x11-repo obviously was disabled. Re-enable it with `pkg install x11-repo`.

Nothing has been removed, package is still present at https://bintray.com/xeffyr/x11-packages/qemu-system-x86_64.

**Comment by tomty89** [comment]
I don't think SPICE vs GTK/SDL is a thing, but SPICE vs VNC. If it can be built/used on Termux, it does belong to the headless build.

**Comment by WMCB-Tech** [comment]
Yes, Spice is the new VNC Display method for qemu and less display overhead and supports native resolution resizing to guest

**Comment by mjuned47** [comment]
This can be closed, spice support has been added in headless qemu
