### ISSUE TITLE
bash: /bin/file: No such file or directory

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#6067]
**bash: /bin/file: No such file or directory**

**Run the command `file` to reproduce this error.**

**Expected behavior:**
> Usage: file [-bcCdEhikLlNnprsSvzZ0] [--apple] [--extension] [--mime-encoding]
            [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
            [-m <magicfiles>] [-P <parameter=value>] [--exclude-quiet]
            <file> ...
       file -C [-m <magicfiles>]
       file [--help]

**Additional information**
This error is present on both armv7 and aarch64 architectures.

**Comment by Grimler91** [comment]
Termux's file utility works fine for me. I guess you're running in a chroot. Please provide full instructions how to reproduce the error.

**Comment by xeffyr** [comment]
Ensure that package "file" is installed and PATH is set exactly to "$PREFIX/bin" ($PREFIX means here full path, not var).
```
pkg install file
export PATH=/data/data/com.termux/files/usr/bin
```

**Comment by SDRausty** [comment]
Here's more information about this error:
> Ensure that package "file" is installed

True enough, package file was not installed on both devices:
1. Before installing:
`which file
/bin/file`
1. After installing:
`which file
/data/data/com.termux/files/usr/bin/file`

PATH information: `/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/usr/sbin:/sbin:/bin`.

Evidently, Termux was using `/system/bin/file` (gleamed from Fail Safe session).  Is there a way Termux can check to see whether package `file` is installed?

**Comment by kcubeterm** [comment]
> . Is there a way Termux can check to see whether package file is installed?

`pkg list-installed`

**Comment by SDRausty** [comment]
Thank you @kcubeterm. I should have been more explicit when asking; Here's my question once more:

I had no idea that I was using the system command `file` and not the Termux command `file`.  Is there a way Termux can check for the user to see whether package `file` is installed when the user runs the command `file`?

**Comment by xeffyr** [comment]
> I had no idea that I was using the system command file and not the Termux command file.

Yeah, you had just discarded the purpose of `command-not-found` utility which is being used to handle cases when program is not installed.

> Is there a way Termux can check for the user to see whether package file is installed when the user initially runs the command file?

If user is not aware of side effects of changing default configuration, then user should not change it.

Termux default PATH is
```
/data/data/com.termux/files/usr/bin
```
which is reasonable and you should NEVER (!!!) append `/bin`, `/sbin` and other directories defined by FHS standard. Termux does not comply with it by design.

> Is there a way Termux can check for the user to see whether package file is installed when the user initially runs the command file?

Of course, it is. Just do not break your installation by tampering whatever dotfiles - if you want to do that, do not complain about problems there.

![Screenshot_20201123-143206_Termux](https://user-images.githubusercontent.com/25881154/99962365-bdf28a80-2d98-11eb-8da9-5d8318f3a608.png)

**Comment by xeffyr** [comment]
If you want to `/bin` be present, consider using `termux-chroot` tool from `proot` package.

**Comment by SDRausty** [comment]
> you should NEVER (!!!) append /bin, /sbin and other directories defined by FHS standard. Termux does not comply with it by design.

Thank you sharing about the limitations of modifying PATH and the potential consequences.  I had no idea that I was breaking my Termux by adding `/usr/sbin:/sbin:/bin` to PATH which created this topic.
