### ISSUE TITLE
Por q me sale este error

### ISSUE THREAD

**Issue by leon27-gif** [termux/termux-packages#6079]
No se pudo recuperar https://dl.bintray.com/termux/termux-packages-24/aarch64/python2_2.7.18-3_aarch64.deb Error al leer desde el servidor - leer (5: error de E / S) [IP: **.***.**.***  ***]
 E: No se pueden recuperar algunos archivos, tal vez ejecute apt-get update o intente con --fix-missing?

**Comment by kcubeterm** [comment]
**Use English**

as error is suggesting execute apt  with "--fix-missing" option.
