### ISSUE TITLE
extra-keys won't accept backslash

### ISSUE THREAD

**Issue by Sepero** [termux/termux-packages#6081]
Minor bug regarding termux.properties. Extra-keys doesn't seem to accept the backslash \ as a key. Example code below. Thank you for great app!

    {key: '/', popup: '\'}, \

**Comment by Sepero** [comment]
Expected behavior:
Sliding up on the / key will display \

Actual behavior:
Sliding up on the / key will displays an empty box

**Comment by kcubeterm** [comment]
From https://wiki.termux.com/wiki/Touch_Keyboard

**A note about backslash: this character has special meaning and you shouldn't use it directly to define a key. Use 'BACKSLASH' instead, otherwise properly escape it - `'\\\\'`.**

**Comment by Sepero** [comment]
Maybe I overlooked it in the docs! Thank you very much 😊
