### ISSUE TITLE
Unable to install Pandas for Python

### ISSUE THREAD

**Issue by anzhi0708** [termux/termux-packages#6083]
Hi there : )

So I have an **armv7** phone with **python 3.9** installed and already had `numpy` `scipy` `jupyter notebook` and `matplotlib` installed, they all worked fine. 

But `pip install pandas` throws me an error.

BTW, I also had `pytz` `python-dateutil` `wheel` `cython` `ninja` `six` `libgfortran5` `make` `cmake` `jsoncpp`and other stuff installed as well.

***error: command 'data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1***

I also tried to build pandas from source code, but here's some of the output:
```
[ 2/40] Cythonizing pandas/_libs/groupby.pyx
warning: pandas/_libs/groupby.pyx:1135:26: Unreachable code
```
```
pandas/_libs/algo.c:88761:3: error: code will never be 
      executed [-Werror, -Wunreachable-code]
```
```
1 error generated.
11 errors generated.
error: command 'data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1
```

I tried to use `export CFLAGS="-Wnoerror, -Wnounreachable-code"` then `pip install pandas` and tried to import pandas after installation, but python told me that some of its extensions was broken / missing. So it was not usable.

I ran `proot-distro login alpine` and successfully installed all these packages including `pandas` in Alpine, they all worked fine. But I don't really want to use Linux in Termux.

plz send help.

**Comment by Grimler91** [comment]
Remove the `,`, i.e. `export CFLAGS="-Wnoerror -Wnounreachable-code"`. If you looked into the new error you got after the export it would probably tell you that the compiler was broken, due to unknown CFLAGS.

**Comment by Grimler91** [comment]
Usually also good to start the flag string with space in case the build system concatenates it without adding a space, so
```
export CFLAGS=" -Wnoerror -Wnounreachable-code"
```

**Comment by xeffyr** [comment]
> -Wnoerror -Wnounreachable-code

```
-Wno-error -Wno-unreachable-code
```

**Comment by xeffyr** [comment]
> tried to import pandas after installation, but python told me that some of its extensions was broken / missing.

Then in addition to CFLAGS, you probably need to add some LDFLAGS. Which exactly thats isn't known, you have not provided the error message.

**Comment by anzhi0708** [comment]
@xeffyr 
Thanks!
```
export CFLAGS=" -Wno-deprecated-declarations -Wno-unreachable-code"
pkg install compiler-rt
export LDFLAGS=" -lm -lcompiler_rt"
make
```
worked.
