### ISSUE TITLE
PHP:7.4 to PHP8  package upgrade (Stable Released)

### ISSUE THREAD

**Issue by amm834** [termux/termux-packages#6084]
- Home Page
https://php.net

- Github
https://github.com/php/php-src

- Commit git
http://git.php.net/
http://git.php.net/?p=php-src.git;a=log

- Released Date
26 Nov 2020

- Version
PHP 8.0 (Stable)

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/89e6517268430947e65ce7b6bbfad49c7a82c575.

**Comment by amm834** [comment]
# Module Loading for apache2
```conf
###php8
LoadModule php_module libexec/apache2/libphp.so

<FilesMatch \.php$> 
   SetHandler application/x-httpd-php
</FilesMatch>
<IfModule dir_module>
    DirectoryIndex index.php
</IfModule>
```
Changed name libphp8.so -> libphp.so
Thank for php8 upgrade*
