### ISSUE TITLE
ctags will not upgrade

### ISSUE THREAD

**Issue by aquatix** [termux/termux-packages#6085]
**Problem description**

dpkg: error processing archive /data/data/com.termux/cache/apt/archives/ctags_1%3ap5.9.20201115.0_aarch64.deb (--unpack):
 parsing file '/data/data/com.termux/files/usr/var/lib/dpkg/tmp.ci/control' near line 5 package 'ctags':
 'Version' field value '1:p5.9.20201115.0': version number does not start with digit
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/ctags_1%3ap5.9.20201115.0_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

During `pkg up` (also with apt) the ctags package does not want to update because of an odd version number.

**Steps to reproduce**

pkg up with ctags installed. Probably also during new install.

**Expected behavior**

ctags installing correctly.

**Additional information**

```

```

**Comment by xeffyr** [comment]
Problem is that ctags is versioned like `p5.9.20201115.0`, `p` needs to be removed.

**Comment by xeffyr** [comment]
Pushed the fix in https://github.com/termux/termux-packages/commit/307b627e1a2c36cf09bd1d961934bdeeef394b9c, updated package should be available shortly (however, that depends on used mirror).
