### ISSUE TITLE
mariadb not installing via termux

### ISSUE THREAD

**Issue by dxwafi** [termux/termux-packages#6089]
![Screenshot_20201127-152335](https://user-images.githubusercontent.com/62784458/100441756-97985c00-30c4-11eb-8ccb-2b750bc47128.jpg)

i am running on Android 10.1 OnePlus 5t

**Problem description**

giving me that error can be checked in screenshot
**Steps to reproduce**

pkg install mariadb
**Expected behavior**

want to install maria db
**Additional information**

```

```

**Comment by Grimler91** [comment]
Looks like a network error. Try again, or connect to a wifi and then try again.

**Comment by dxwafi** [comment]
i tried four five times the same error happening

**Comment by kcubeterm** [comment]
@dxwafi Download mariadb with that link and install it manually via `dpkg -i debfile.deb`

**Comment by dxwafi** [comment]
> @dxwafi Download mariadb with that link and install it manually via `dpkg -i debfile.deb`

with which link?

**Comment by kcubeterm** [comment]
https://dl.bintray.com/termux/termux-packages-24/aarch64/mariadb_2:10.5.8_aarch64.deb

**Comment by dxwafi** [comment]
> https://dl.bintray.com/termux/termux-packages-24/aarch64/mariadb_2:10.5.8_aarch64.deb

![Screenshot_20201127-163434.jpg](https://user-images.githubusercontent.com/62784458/100447567-750b4080-30ce-11eb-986d-d427998bf725.jpg)



i downloaded and trying to install but its still not working...

**Comment by kcubeterm** [comment]
use dpkg here not pkg.
`dpkg -i DEBFILE.deb`

**Comment by xeffyr** [comment]
**Do not install packages as root!**

**Comment by dxwafi** [comment]
> use dpkg here not pkg.
> `dpkg -i DEBFILE.deb`

my frnd i did the same the word (d) is not visible
i copied your command and past it and didn't work

**Comment by kcubeterm** [comment]
@dxwafi , why are you performing with root. Do it with default user (without root)

**Comment by dxwafi** [comment]
> **Do not install packages as root!**

without root access you can not access storage

**Comment by dxwafi** [comment]
> @dxwafi , why are you performing with root. Do it with default user (without root) 

![Screenshot_20201127-170837.jpg](https://user-images.githubusercontent.com/62784458/100450409-362bb980-30d3-11eb-98c2-c382ff75afd4.jpg)


if i do it without root i have no permission to access storage so i have to go with root permission...

**Comment by kcubeterm** [comment]
> without root access you can not access storage

then first copy/move that deb  in $HOME with root and run dpkg with normal user

**Comment by xeffyr** [comment]
> if i do it without root i have no permission to access storage

Did you ever heard of `termux-setup-storage` or that you can grant storage permission in Android settings?

Termux is primarily designed for non-root users.

**Comment by dxwafi** [comment]
> > if i do it without root i have no permission to access storage
> 
> Did you ever heard of `termux-setup-storage` or that you can grant storage permission in Android settings?
> 
> Termux is primarily designed for non-root users.

thank you i forgot about that but it still didn't work...

![Screenshot_20201127-173636.jpg](https://user-images.githubusercontent.com/62784458/100452639-2ca45080-30d7-11eb-88bf-6688a57eb69b.jpg)

**Comment by xeffyr** [comment]
Ok, now do:
```
apt update
apt -f install
```

**Comment by dxwafi** [comment]
> Ok, now do:
> ```
> apt update
> apt -f install
> ```

![Screenshot_20201127-180309.jpg](https://user-images.githubusercontent.com/62784458/100454587-d3d6b700-30da-11eb-821a-a8c963fca567.jpg)


it making us tired 🤨🤨

**Comment by xeffyr** [comment]
> it making us tired

Not reading instructions and imaginating something that I didn't wrote make maintainers tired.

Again:
```
apt update
apt -f install
```
I somewhere mentioned the debfile in the last apt command??? Seems not.

**Comment by dxwafi** [comment]
> > it making us tired
> 
> Not reading instructions and imaginating something that I didn't wrote, make maintainers tired.
> 
> Again:
> ```
> apt update
> apt -f install
> ```
> I somewhere mentioned the debfile in the last apt command??? Seems not.

thank you buddy it worked and installed successfully 
🤗🤗
