### ISSUE TITLE
Number keyboard

### ISSUE THREAD

**Issue by natethefemboy8701** [termux/termux-packages#6090]
Hello termux team I really love your app but I was following a small tutorial on gitcloning with termux and after I finished I was unable to do anything because it kept giving me the number keyboard even after force quitting the app and even uninstalling and uninstalling the entire termux app I'd appreciate a little bit of help

**Comment by Grimler91** [comment]
I remember this used to happen to me some years ago on some ROM. Tilting the screen to change between portrait and landscape mode made it switch back, so please try that!

**Comment by Grimler91** [comment]
Is it a Samsung device? Could you print the output of `termux-info`?

**Comment by Gravelman-Root** [comment]
is there a way to copy my termux terminal to other devices?
G

**Comment by xeffyr** [comment]
That's all Samsung keyboard. Workaround is to enable specific setting as in https://wiki.termux.com/wiki/Terminal_Settings#Workaround_for_some_keyboards_issues.
