### ISSUE TITLE
`ghc-pkg`: library "libncursesw.so.6" not found

### ISSUE THREAD

**Issue by Meowcolm024** [termux/termux-packages#6092]
**Problem description**

The unstable package `ghc` (8.10.1) is installed via `apt install`, and I have installed `llvm` beforehand. `ghc-pkg` doesn't work as expected and throws an exception for missing file.

**Steps to reproduce**

1. install `ghc` using `apt install`

```
➜  ~ apt install ghc --fix-missing
```

2. run `ghc-pkg`

```
➜  ~ ghc-pkg
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/ghc-8.10.1/bin/ghc-pkg": library "libncursesw.so.6" not found: needed by main executable
```

**Expected behavior**

For just running `ghc-pkg` the expected output should be: *(On macOS 11.0.1 x86_64, version 8.8.4)*

```
➜  ~ ghc-pkg
ghc-pkg: missing command
For usage information see 'ghc-pkg --help'.
```

**Additional information**

The error output

```
➜  ~ ghc-pkg
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/ghc-8.10.1/bin/ghc-pkg": library "libncursesw.so.6" not found: needed by main executable
```

Other info:

```
Device: Oneplus 8 Pro (Snapdragon 865) 
OS: Android 11, Hydrogen OS 11.0.1.1IN11 (NOT rooted)
Termux version: 0.101
```

**Comment by HamzaMateen** [comment]
I just ran into the same issue :(

**Comment by vestineo** [comment]
You can do any of the two things. Either
1. LD_LIBRARY_PATH=$PREFIX/lib/ ghc-pkg
Or patch elf
2. patchelf --set-rpath $PREFIX/lib/ $PREFIX/lib/ghc-8.10.1/bin/ghc-pkg

**Comment by danwdart** [comment]
ghc seems missing from the unstable repo.

**Comment by chenyulue** [comment]
@vestineo 's first suggestion solved my issue.
