### ISSUE TITLE
Python 3.9 math library module termux

### ISSUE THREAD

**Issue by Dolfost** [termux/termux-packages#6093]
python 3.9 (termux), library math don't installing (pip install math shows me a ERROR) math is a built in module, but import math dont work too
Pip is a last ver.
Its no ip ban.
Installing error:
ERROR: Could not find a version that satisfies the requirement math (from versions: none)
ERROR: No matching distribution found for math

**Comment by Grimler91** [comment]
What error do you get if you try to import math?

**Comment by Grimler91** [comment]
Math is a built in module, as you said, so you can't install it through pip.

**Comment by Dolfost** [comment]
> What error do you get if you try to import math?

Code: 
import math
print(math.pi)

Error:
python math.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/math.py", line 1, in <module>
    import math
  File "/data/data/com.termux/files/home/math.py", line 2, in <module>
    print(math.pi)
AttributeError: partially initialized module 'math' has no attribute 'pi' (most likely due to a circular import)

Python3:

$ python3 math.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/math.py", line 1, in <module>
    import math
  File "/data/data/com.termux/files/home/math.py", line 2, in <module>
    print(math.pi)
AttributeError: partially initialized module 'math' has no attribute 'pi' (most likely due to a circular import)
$

**Comment by Grimler91** [comment]
Hm, weird, I cannot reproduce the issue. What is your output of `termux-info`?

**Comment by kcubeterm** [comment]
Basically, error due to your filename "math.py". 
Change this name to something else.

**Comment by kcubeterm** [comment]
@Dolfost 
See what happens when you import modules, it finds module in current directory first and math.py is available in your current directory and your math.py don't contains such functions. 
https://medium.com/python-features/what-happens-behind-the-scenes-when-we-import-a-module-in-python-2775da153790

**Comment by Dolfost** [comment]
> @Dolfost
> See what happens when you import modules, it finds module in current directory first and math.py is available in your current directory and your math.py don't contains such functions.
> https://medium.com/python-features/what-happens-behind-the-scenes-when-we-import-a-module-in-python-2775da153790

OHHH GOOOOOOD THANKS YOU HOLY WOMAN!
