### ISSUE TITLE
Could not build scikit-learn for armv7 python3.9 

### ISSUE THREAD

**Issue by anzhi0708** [termux/termux-packages#6094]
Hi there : )

I have `numpy` `pandas` `scipy` installed but failed to install sklearn, stuck at `_hierarchical.o.d` part.
![A3E7F652-FCDD-4234-8C33-6DED8BA1046E](https://user-images.githubusercontent.com/57821133/100522727-5d2ade00-31ee-11eb-9c9a-aa574de2f5ce.jpeg)

I have `threadpoolctl` `joblib 0.11` installed and did `export LDFLAGS=" -lm -lcompiler_rt"`. 

`pip install scikit-learn==0.19.2` won't work neither.

The architecture is ***armv7***.
Plz send help.

**Comment by Grimler91** [comment]
Your photo provides no information what so ever about the actual error. Post the full message, see the requested info in the [bug report template](https://github.com/termux/termux-packages/issues/new?template=bug_report.md)

**Comment by anzhi0708** [comment]
@Grimler91 Thanks for the reply.

I eventually installed it by `setupgcc-10 && setup-patchforgcc && pkg install build-essential` then `python setup.py install`. It did give me errors says "TypeError: expected string or bytes-like object" at the end of installation but I did see `scikit-learn 0.24.dev0` showed up in `pip list` and successfully imported in python.

Although `joblib` throws an error,
```
/data/data/com.termux/files/usr/lib/python3.9/site-packages/joblib/_multiprocessing_helpers.py:28: UserWarning: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770..  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
```

but sklearn works anyway. Guess I'll close this issue.
