### ISSUE TITLE
Unable to install python tried with multiple device

### ISSUE THREAD

**Issue by abasgames** [termux/termux-packages#6099]
**Problem description**

A clear and concise description of what the problem is.
You may post screenshots in addition to description.
Im unable to install Python

**Steps to reproduce**

Steps to reproduce the behavior. Please post all necessary
Open termux and tries to install python
commands that are needed to reproduce the issue.
Pkg update
Pkg install python

**Expected behavior**

I expected the pkg manager to install python

**Additional information**
[IP: 52.43.200.1 443]
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/arm/python_3.9.0_arm.deb  Error reading from server - read (5: I/O error) [IP: 52.43.200.1 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Post output of command 'termux-info' between '```' (code formatting).
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 3.10.108-g59686082149 #1 SMP PREEMPT Wed Mar 25 16:42:24 UTC 2020 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J700H

```

```

**Comment by Grimler91** [comment]
Looks like a network error. Try changing to a WiFi, or to mobile internet. You can also try downloading the package(s) through the web browser, by going to the link in the error message, and then install the downloaded deb(s) with `apt install path-to-deb(s).deb`

**Comment by kcubeterm** [comment]
As mentioned, download debfiles and then install it. 
```
wget https://dl.bintray.com/termux/termux-packages-24/arm/python_3.9.0_arm.deb
apt install ./python_3.9.0_arm.deb
``` 

Most of the users are reporting this error on different termux community, hope this would be fixed soon by bintary (as xeffyr guessed).

**Comment by xeffyr** [comment]
> hope this would be fixed soon by bintary

It may not be fixed by Bintray if that's ISP or country-specific issue.

Major CDNs, like CloudFlare (used by termux.net and termux-mirror.ml) or CloudFront (used by Bintray) are often subjects for restriction in countries with censorship events. That's, for example, an issue for Chinese and most of them have to use mirrors like https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-the-tsinghua-university-tuna-association.

**Comment by kcubeterm** [comment]
> It may not be fixed by Bintray if that's ISP or country-specific issue.

Well! Users are reporting suddenly. Maybe this is a bug of apt itself.
