### ISSUE TITLE
rappel Enhancement request 

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#6100]
Currently Rappel displays 4 registers per column. On Android termux with visible size font, the last row gets wrapped. Is it possible to display 2 register per column for a better register view on Termux Android screen

**Comment by kcubeterm** [comment]
I think this issue should be reported on [upstream](https://github.com/yrp604/rappel) 
If they add such options to optimise column it would be better for all types of system.

**Comment by kcubeterm** [comment]
Column can be adjust by zooming in/out terminal.

https://user-images.githubusercontent.com/50498359/103437352-c1f1b200-4c4c-11eb-9918-f9881551e70d.mp4
