### ISSUE TITLE
How to install git without any error

### ISSUE THREAD

**Issue by Mina93-min** [termux/termux-packages#6101]
pkg install php
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  fontconfig freetype giflib libffi libgd libicu
  libjpeg-turbo libpng libsqlite libtiff libwebp libxml2
  libxslt libzip oniguruma tidy ttf-dejavu
The following NEW packages will be installed:
  fontconfig freetype giflib libffi libgd libicu
  libjpeg-turbo libpng libsqlite libtiff libwebp libxml2
  libxslt libzip oniguruma php tidy ttf-dejavu
0 upgraded, 18 newly installed, 0 to remove and 0 not upgraded.
Need to get 22.7 MB of archives.
After this operation, 115 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libpng aarch64 1.6.37-3 [190 kB]
Get:2 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 freetype aarch64 2.10.4 [372 kB]
Get:3 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libxml2 aarch64 2.9.10-4 [827 kB]
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 ttf-dejavu all 2.37-8 [2468 kB]
Get:5 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 fontconfig aarch64 2.13.1-6 [103 kB]
Get:6 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 giflib aarch64 5.2.1-2 [17.0 kB]
Get:7 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libffi aarch64 3.3-2 [28.6 kB]
Get:8 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libjpeg-turbo aarch64 2.0.6 [262 kB]
Get:9 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libtiff aarch64 4.1.0-3 [504 kB]
Get:10 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libwebp aarch64 1.1.0-1 [194 kB]
Get:11 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libgd aarch64 2.3.0-1 [117 kB]
Get:12 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libicu aarch64 67.1 [8893 kB]
Get:13 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libsqlite aarch64 3.33.0 [543 kB]
Err:13 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libsqlite aarch64 3.33.0
  Error reading from server - read (5: I/O error) [IP: 3.126.159.175 443]
Get:14 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libxslt aarch64 1.1.34-1 [296 kB]
Get:15 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 libzip aarch64 1.7.3-1 [203 kB]
Get:16 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 oniguruma aarch64 6.9.6 [127 kB]
Get:17 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 tidy aarch64 5.7.28-2 [271 kB]
Get:18 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 php aarch64 7.4.12 [7326 kB]
Err:18 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 php aarch64 7.4.12
  Error reading from server - read (5: I/O error) [IP: 3.126.159.175 443]
Fetched 14.9 MB in 18min 0s (13.8 kB/s)
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/libsqlite_3.33.0_aarch64.deb  Error reading from server - read (5: I/O error) [IP: 3.126.159.175 443]
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/php_7.4.12_aarch64.deb  Error reading from server - read (5: I/O error) [IP: 3.126.159.175 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by xeffyr** [comment]
Seems like a mass problem with Bintray in some countries. Anyway, the solution could be a use of a network with different ISP, use of VPN/TOR or switching the mirror by using `termux-change-repo`.

Server-side issues of `https://dl.bintray.com` are not subject for fixing by @termux.
