### ISSUE TITLE
fzy: A better fuzzy finder

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-packages#6102]
requests).

**Package description**
Name            : fzy
Version         : 1.0-2
Description     : A better fuzzy finder
Architecture    : x86_64
URL             : https://github.com/jhawthorn/fzy
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : glibc
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Download Size   : 15.19 KiB
apply.

**Comment by kcubeterm** [comment]
Should be available soon 6caf104
