### ISSUE TITLE
R: x11 is not available 

### ISSUE THREAD

**Issue by anzhi0708** [termux/termux-packages#6107]
xfce4 is working fine, python's matplotlib is also working.
and after installing "xorgproto" package, `#include <X11/X.h>` is also working.
**But R says x11 is not available** and calling function `png('filename')` / `x11()` in R console reports "x11 is not available". 
I tried to call `x11()` method under xfce4 environment, still got no luck. Python's plotting module all worked fine tho.
I do have R package `Cairo` installed. But `capabilities()` returns:
```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
      FALSE       FALSE       FALSE       FALSE       FALSE       FALSE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS     profmem       cairo         ICU long.double     libcurl
      FALSE       FALSE       FALSE        TRUE       FALSE        TRUE
```
Both x11 and cairo are FALSE.
I have `libjpeg-turbo` `libtiff` `tk` and `libpng` installed cause matplotlib needs them. None of them is working in R I guess?
Please help. What am I missing here?

![Capture+_2020-12-01-07-35-07~2](https://user-images.githubusercontent.com/57821133/100674194-1da7f180-33a8-11eb-9916-aa7d24646b00.png)
![Capture+_2020-12-01-07-35-37~2](https://user-images.githubusercontent.com/57821133/100674236-2f899480-33a8-11eb-9723-9056f6c05e76.png)

**Comment by anzhi0708** [comment]
BTW, any R code (including a simple print helloworld code) crashes jupyter notebook, and makes IRkernel to reboot because x11 is needed for it and I dunno why.

**Comment by xeffyr** [comment]
As far I know, R is built without X11 support. It also not official Termux package.
