### ISSUE TITLE
mpv: scaletempo2

### ISSUE THREAD

**Issue by 532910** [termux/termux-packages#6108]
Please add scaletempo2 af support for mpv.

```
% mpv --af=scaletempo2
Option af: scaletempo2 doesn't exist
```

**Comment by Grimler91** [comment]
Bot has been a bit too eager to close issues. 

It would help if you provide more information about the request here though, what is scaletempo2? Is it another library that mpv should be linked against or does it just need a configure arg for mpv for support to be added? Do you have a link to the relevant website/source code?

**Comment by 532910** [comment]
scaletempo2 is supported now:
```
% =mpv -v --af=scaletempo2 storage/music/Set_Me_On_Fire.flac |& grep -i scal
[cplayer] Command line options: '-v' '--af=scaletempo2' 'storage/music/04 - Set Me On Fire.flac'
[cplayer]    libswscale      5.9.100
[cplayer] Setting option 'af' = 'scaletempo2=search-interval=20:window-size=10' (flags = 4)
[cplayer] Setting option 'af' = 'scaletempo2' (flags = 8)
[af]   scaletempo2 (scaletempo2.00)
[af] [scaletempo2] 44100Hz stereo 2ch s16
```

**Comment by 532910** [comment]
It works for me.
