### ISSUE TITLE
Package request: aerc

### ISSUE THREAD

**Issue by FriendlyNeighborhoodShane** [termux/termux-packages#6115]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

> aerc is an email client that runs in your terminal. It's highly efficient and extensible, perfect for the discerning hacker.

> Some of its more interesting features include:
>   - Editing emails in an embedded terminal tmux-style, allowing you to check on incoming emails and reference other threads while you compose your replies
>   - Render HTML emails with an interactive terminal web browser, highlight patches with diffs, and browse with an embedded less session
>   - Vim-style keybindings and ex-command system, allowing for powerful automation at a single keystroke
>   - First-class support for working with git & email

**Link to home page and sources**
1. Home page: https://aerc-mail.org
2. Source code: https://git.sr.ht/~sircmpwn/aerc

**Comment by xeffyr** [comment]
Package has been [added](https://github.com/termux/termux-packages/commit/dfc1afc380fab971f5cd8a8a73c4e8f0b2ef6c7d).

**Comment by FriendlyNeighborhoodShane** [comment]
Thanks!
