### ISSUE TITLE
tsu error: "env: inaccessible or not found"

### ISSUE THREAD

**Issue by DSolo03** [termux/termux-packages#6116]
![Screenshot_20201204-111426](https://user-images.githubusercontent.com/61384845/101139176-36bbd700-3622-11eb-9c27-0b2d5d4bcdef.jpg)

**Comment by xeffyr** [comment]
Ensure that path
```
/data/data/com.termux/files/usr/bin/env
```
is a valid symlink to `coreutils`

**Comment by xeffyr** [comment]
If `env` is present but still not found for some reason, please report issue to `tsu` upstream here: https://github.com/cswl/tsu.
