### ISSUE TITLE
Aspell ducts not installed

### ISSUE THREAD

**Issue by Bridouz** [termux/termux-packages#6125]
**Problem description**
Installed `aspell`, `aspell-en` and `aspell-fr`. The command `aspell dump dicts` should show english and french dicts.

**Steps to reproduce**
```
pkg install aspell aspell-en aspell-fr
aspell dump dicts
```

**Expected behavior**
```
$ aspell dump dicts
fr-40
fr
fr-60
fr-80
fr-lrg
fr-med
fr-sml
fr_CH-40
fr_CH-60
fr_CH
fr_CH-80
fr_CH-lrg
fr_CH-med
fr_CH-sml
fr_FR-40
fr_FR-60
fr_FR
fr_FR-80
fr_FR-lrg
fr_FR-med
fr_FR-sml
```

**Additional information**
AOSP 10, Termux freshly installed, don't work with or without root.

**Comment by xeffyr** [comment]
Should be fixed now.
