### ISSUE TITLE
pkg install mariadb

### ISSUE THREAD

**Issue by Daryl1903** [termux/termux-packages#6127]
$ apt update
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Ign:2 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Get:5 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Get:6 https://dl.bintray.com/termux/termux-packages-24 stable Release [8255 B]
Fetched 19.8 kB in 7s (2918 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
$ apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ pkg install mariadb
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libedit pcre2
The following NEW packages will be installed:
  libedit mariadb pcre2
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 28.8 MB/29.6 MB of archives.
After this operation, 413 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 mariadb aarch64 2:10.5.8 [28.8 MB]
Err:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 mariadb aarch64 2:10.5.8
  Error reading from server - read (5: I/O error) [IP: 52.38.145.242 443]
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/mariadb_2:10.5.8_aarch64.deb  Error reading from server - read (5: I/O error) [IP: 52.38.145.242 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
$

**Comment by kcubeterm** [comment]
Dublicate of #6089
