### ISSUE TITLE
texlive: xelatex fails with "bus error"

### ISSUE THREAD

**Issue by r4lv** [termux/termux-packages#6128]
Dear termux-packages team,

I am trying to run `xelatex` on a simple file. While `pdflatex` works fine, every time I run `xelatex` I get a *bus error*. Please let me know if you need more information.

**test.tex**

``` tex
\documentclass[a4paper]{article}
\begin{document}
$x^2$
\end{document}
```

**full output**

    ❯ xelatex test.tex
    This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/Termux) (preloaded format=xelatex)
     restricted \write18 enabled.
    entering extended mode
    (./test.tex
    LaTeX2e <2020-02-02> patch level 5
    L3 programming layer <2020-03-06>
    (/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/latex/base/articl
    e.cls
    Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
    
    (/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/latex/base/size10
    .clo))
    (/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/latex/l3backend/l
    3backend-xdvipdfmx.def) (./test.aux)
    (/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr
    .fd) [1zsh: bus error  xelatex test.tex
    xdvipdfmx:fatal: File ended prematurely

**Steps to reproduce**

I tried both `texlive-full` and also the manual installation using `texlive-installer`, I am getting the same error.

**Additional information**

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.111-17423164 #1 SMP PREEMPT Tue May 12 11:27:11 KST 2020 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T515
```

**Comment by Grimler91** [comment]
`zsh: bus error`, looks like some sort of error due to zsh. Try in bash and see if it works there.

If you have access to an adb shell you can also check if you get some additional information about the error from a logcat

**Comment by r4lv** [comment]
Dear Henrik,
thank you for your fast response. I also tried it in bash, the output is quite close:

    [...]
    (/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr
    .fd) [1Bus error
    xdvipdfmx:fatal: File ended prematurely

I do not have access to adb right now, but I tried debugging with gdb as suggested in https://github.com/termux/termux-packages/issues/1765:

``` text
(gdb) run
Starting program: /data/data/com.termux/files/usr/bin/texlive/xelatex test.tex

Program received signal SIGILL, Illegal instruction.
0xf6cee286 in ?? () from /data/data/com.termux/files/usr/lib/libcrypto.so.1.1
(gdb) bt
#0  0xf6cee286 in ?? () from /data/data/com.termux/files/usr/lib/libcrypto.so.1.1
#1  0xf6cee18c in ?? () from /data/data/com.termux/files/usr/lib/libcrypto.so.1.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

That doesn't make too much sense to me… Would a debug build of xelatex help?

**Comment by xeffyr** [comment]
> Program received signal SIGILL, Illegal instruction.
0xf6cee286 in ?? () from /data/data/com.termux/files/usr/lib/libcrypto.so.1.1

GDB doesn't work properly with CPUID-using programs/libraries, that's a well known issue.

Fix (in gdb shell):
```
handle SIGILL nostop
```

**Comment by tomty89** [comment]
https://en.m.wikipedia.org/wiki/Bus_error

I wonder if it's specific to arm/aarch64 (so sort of memory alignment requirement?). Speaking of that, why are you using arm Termux in an aarch64 system? (Or is it some odd hybrid?)

**Comment by xtkoba** [comment]
> Speaking of that, why are you using arm Termux in an aarch64 system? (Or is it some odd hybrid?)

See https://wiki.termux.com/wiki/FAQ#Why_my_Termux_is_32bit_while_CPU_supports_64bit

**Comment by xtkoba** [comment]
This does not seem to happen any longer:

```
$ xelatex test.tex
This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021/Termux) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>
(/data/data/com.termux/files/usr/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/data/data/com.termux/files/usr/texmf-dist/tex/latex/base/size10.clo))
(/data/data/com.termux/files/usr/texmf-dist/tex/latex/l3backend/l3backend-xetex
.def (|extractbb --version)) (./test.aux)
(/data/data/com.termux/files/usr/texmf-dist/tex/latex/base/ts1cmr.fd) [1]
(./test.aux) )
Output written on test.pdf (1 page).
Transcript written on test.log.
```

where the binary `bin/texlive/xetex` (symlinked from `xelatex`) derives from `texlive-bin_20210325-4_arm`:

```
$ file bin/texlive/xetex
bin/texlive/xetex: ELF shared object, 32-bit LSB arm, dynamic (/system/bin/linker), for Android 24, built by NDK r23b (7779620), stripped
```

I have no idea whether this was fixed upstream or just that the new toolchain has stopped miscompiling. But I suppose this can be closed now.
