### ISSUE TITLE
x11-repo installing

### ISSUE THREAD

**Issue by Dolfost** [termux/termux-packages#6129]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```
im try to install x11-repo
im have 9 android and roted divece
when im installing some pkg's i se error E: Unable to locate package xxx 
code x11 error:

$ pkg install x11-repo
Checking availability of current mirror: ok
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://its-pointless.github.io/files termux InRelease
Ign:4 https://dl.bintray.com/grimler/termux-root-packages-24 root InRelease
Get:5 https://cctools.info termux InRelease [8994 B]
Ign:6 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:7 https://its-pointless.github.io/files termux Release
Get:8 https://dl.bintray.com/termux/termux-packages-24 stable Release [8255 B]
Ign:9 https://its-pointless.github.io/files termux/extras i386 Packages
Get:10 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Ign:11 https://its-pointless.github.io/files termux/extras all Packages
Ign:12 https://its-pointless.github.io/files termux/extras aarch64 Packages
Get:13 https://dl.bintray.com/grimler/termux-root-packages-24 root Release [6185 B]
Ign:9 https://its-pointless.github.io/files termux/extras i386 Packages
Err:5 https://cctools.info termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8ED139655E265DBD
Get:14 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Ign:11 https://its-pointless.github.io/files termux/extras all Packages
Ign:12 https://its-pointless.github.io/files termux/extras aarch64 Packages
Ign:9 https://its-pointless.github.io/files termux/extras i386 Packages
Ign:11 https://its-pointless.github.io/files termux/extras all Packages
Ign:12 https://its-pointless.github.io/files termux/extras aarch64 Packages
Ign:9 https://its-pointless.github.io/files termux/extras i386 Packages
Ign:11 https://its-pointless.github.io/files termux/extras all Packages
Ign:12 https://its-pointless.github.io/files termux/extras aarch64 Packages
Ign:9 https://its-pointless.github.io/files termux/extras i386 Packages
Ign:11 https://its-pointless.github.io/files termux/extras all Packages
Ign:12 https://its-pointless.github.io/files termux/extras aarch64 Packages
Err:9 https://its-pointless.github.io/files termux/extras i386 Packages
  404  Not Found [IP: 185.199.108.153 443]
Ign:11 https://its-pointless.github.io/files termux/extras all Packages
Ign:12 https://its-pointless.github.io/files termux/extras aarch64 Packages
Reading package lists... Done
W: GPG error: https://cctools.info termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8ED139655E265DBD
E: The repository 'https://cctools.info termux InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

i think problem is in N: Possible cause: reposi... 
how i cam fix this?
```

**Comment by xeffyr** [comment]
> i think problem is in N: Possible cause: reposi... 
how i cam fix this?

How cctools.info appeared in your repositories? Remove it. Termux is not compatible with CCTools.

**Comment by amm834** [comment]
I see 404 Not found!
That means their is no route for your request.
That is the problem of Termux api.
That should fix by admin.

You should also try
```bash
pkg up || PKG upgrade
```
If not work and get same errors or not.
If you see 404 in future errors that is **problem** of Termux host or api.

**Comment by xeffyr** [comment]
@amm834 Look better and you will find problems besides 404...

**Comment by xeffyr** [comment]
> Ign:11 https://its-pointless.github.io/files termux/extras all Packages
Ign:12 https://its-pointless.github.io/files termux/extras aarch64 Packages
Ign:9 https://its-pointless.github.io/files termux/extras i386 Packages

Perhaps @Dolfost needs `rm -rf $PREFIX` to start from scratch...

**Comment by amm834** [comment]
> > i think problem is in N: Possible cause: reposi...
> > how i cam fix this?
> 
> How cctools.info appeared in your repositories? Remove it. Termux is not compatible with CCTools.

I see now 👀

**Comment by xeffyr** [comment]
In summary, there 2 problems happening:

1. Missing GPG key for verifying cctools.info repository, which belongs to CCTools app.
```
Err:5 https://cctools.info termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8ED139655E265DBD
```
That line should be deleted from sources.list because even if GPG key will be added to keyring, it won't be possible to successfully install any packages from this repo.

2. Invalid alternate architecture has been enabled for valid repo `https://its-pointless.github.io/files`:
```
Err:9 https://its-pointless.github.io/files termux/extras i386 Packages
```
`i386` is valid for Debian, but not for Termux. Moreover, Termux is neither Debian, Ubuntu or their derivative and guides for these distributions will not work for Termux. Also, any x86 package won't run on AArch64 device anyway - emulators needed.

**Comment by Dolfost** [comment]
hey guys! im visited cctools.info and downloaded cctols apk and plugin. and this helped me!!!! tigervnc installind dont says E: unable to locate pacakage now! and x11 repo was installed sucesfully

**Comment by RalfWerner** [comment]
> tigervnc install says E: unable to locate pacakage

@Dolfost Try `apt-get tigervnc-standalone-server` in debian/ubuntu-`proot` - see [here](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-594033201)
