### ISSUE TITLE
How to use mosquitto?

### ISSUE THREAD

**Issue by Nic2012** [termux/termux-packages#613]
Hi,
according to https://github.com/termux/termux-packages/pull/515 it seems the mqtt mosquitto https://mosquitto.org/ is available under apt list. If thats true, is it the broker or client? And how can I start and use it?

Best regards,
Nic

**Comment by fornwall** [comment]
The package named `mosquitto` is actually the clients, containing `mosquitto_pub` and `mosquitto_sub`. 

The package should probably be renamed to `mosquitto-clients` for sense and compatibility with debian&ubuntu.

**Comment by Nic2012** [comment]
Thanks for the answer, but I am more interested in the mosquitto broker. There is a big lack on an Android System. Do y have plans to support the broker, too or is that technically not possible?
Best regards,
Nic

**Comment by marksev1** [comment]
@fornwall would then this https://pypi.python.org/pypi/paho-mqtt/1.1 work with it? Would i be able to publish and subscribe stuff from for example "Termux-api" to mqtt?

**Comment by Nic2012** [comment]
@marksev1 The mosquitto stuff inside termux is a client and y mentioned paho class is also a client side implem. To pub or sub messages between each kind of client inside termux or outside a central mosquitto server or broker is needed. That I have requested for to have it in termux too.

**Comment by fornwall** [comment]
@Nic2012 As of version `1.4.10-1`, the mosquitto package now contains the broker. Let me know how it works!

**Comment by marksev1** [comment]
Awesome! I will test it too :D.

**Comment by Nic2012** [comment]
@fornwall 
It works! Yeah thats really awesome! I was able to connect the broker by another Android smartphone with the app MQTT Dashboard or MQTT Dash, both can be found in Google Play store.
By this solution you created the first mqtt broker for Android! That will give a great progress to MQTT in general. Thank you.

**Comment by vladosam** [comment]
It seems that mosquitto broker timestamp is off. It probably searches for /etc/timezone and that file doesn't exist on android. Can this be fixed somehow?
