### ISSUE TITLE
Please help me with this cannot install ubuntu

### ISSUE THREAD

**Issue by HappyN07** [termux/termux-packages#6135]
Cannot install Ubuntu
![Screenshot_2020-12-10-15-22-33-110_com termux](https://user-images.githubusercontent.com/75783581/101758150-041c4d80-3afe-11eb-9f09-2e4f22567a5d.jpg)

**Comment by WMCB-Tech** [comment]
It seems the script didn't update the links and the links has changed

Try an alternate solution like Andronix or `proot-distro`

**Comment by landfillbaby** [comment]
yeah just use proot-distro
