### ISSUE TITLE
qemu-user-i386 error

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#6141]
**The following packages will be upgraded:**
  `apt bash curl libcurl openssl pulseaudio qemu-user-i386`
> qemu-user-i386/stable,now 1:5.2.0-1 arm [installed]

**Newly arisen error:**
> proot info: vpid 1: terminated with signal 11

**Steps to reproduce:**
Install Arch Linux 32 on armv7l with qemu support.  Command [`setupTermuxArch v`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch) attempts to install and configure Arch Linux 32 on armv7l architecture.

**Expected behavior:**

PRoot with QEMU enabled run correctly like it did before this last upgrade.

**Comment by xeffyr** [comment]
I've just tested these binaries on armv7l device and it seems like QEMU is working fine:
* https://busybox.net/downloads/binaries/1.31.0-defconfig-multiarch-musl/busybox-i686
* https://busybox.net/downloads/binaries/1.31.0-defconfig-multiarch-musl/busybox-x86_64

I will not do tests "distribution-wide", considering as QEMU user mode is usually less stable that system variant and v5.2.0 upstream can have regressions.

Emulation errors are not subject for debugging & fixing by me. Complexity of QEMU's Tiny Code Generator is quite beyond my skills. Reverting to previous version will not be done as well.

Closing.

**Comment by SDRausty** [comment]
> Reverting to previous version will not be done as well.

The option `apt -o APT::Keep-Downloaded-Packages="true"` used to allow local rollback. Can it be re-implemented?

> considering as QEMU user mode is usually less stable that system variant

I have changed `qemu-i386` to `qemu-system-i386` in `exec proot -v 1 --kernel-release=4.9.117+ --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/x86 -b /data/data/com.termux/files/home/x86/var/binds/fbindprocpcidevices:/proc/bus/pci/devices -b /data/data/com.termux/files/home/x86/var/binds/fbindprocshmem:/proc/shmem -b /data/data/com.termux/files/home/x86/var/binds/fbindprocversion:/proc/version -q /data/data/com.termux/files/usr/bin/qemu-system-i386 -b /dev/ashmem:/dev/ashmem -b /proc/:/proc/ -b /vendor/:/vendor/ -b /system/:/system/ -b /proc/self/fd/2:/dev/stderr -b /proc/self/fd/1:/dev/stdout -b /proc/self/fd/0:/dev/stdin -b /dev/urandom:/dev/random -b /data/data/com.termux/files/usr:/data/data/com.termux/files/usr -b /proc/self/fd:/dev/fd -b /storage/:/storage/ -b /data/data/com.termux/files/home:/data/data/com.termux/files/home -b /sdcard:/sdcard -b /dev/:/dev/ -b /data/data/com.termux/files/home/x86/var/binds/fbindprocuptime:/proc/uptime -b /data/data/com.termux/files/home/x86/tmp:/dev/shm -b /data/data/com.termux/files/home/x86/var/binds/fbindprocstat:/proc/stat -b /sys/:/sys/ -w /root /usr/bin/env -i HOME=/root TERM="xterm-256color" TMPDIR=/tmp ANDROID_DATA=/data  /bin/bash -l`.

The result has this error; `qemu-system-i386: -U: invalid option`.  Advice regarding this new error is welcome.

**Comment by xeffyr** [comment]
> The option apt -o APT::Keep-Downloaded-Packages="true" used to allow local rollback.

Downloaded packages are kept in
```
/data/data/com.termux/cache
```
They are no longer stored in $PREFIX to be preserved when `termux-reset` was executed.

> The result has this error; qemu-system-i386: -U: invalid option.

@SDRausty `qemu-system-i386` emulates the full machine. It is not usable with `proot` and operates on disk images instead of file system.

Don't get me wrong, but I only pointed on that `qemu-i386` is known to have problems. I have not suggested to replace `qemu-i386` with `qemu-system-i386`.

**Comment by SDRausty** [comment]
> `qemu-system-i386` emulates the full machine. It is not usable with `proot` and operates on disk images instead of file system.

Can you share a link to a working disk image with the `qemu-system-i386` init code so that I can easily test this please?

**Comment by SDRausty** [comment]
>Downloaded packages are kept in
`/data/data/com.termux/cache`

> I've just tested these binaries on armv7l device and it seems like QEMU is working fine:

Thank you for this information and for taking the time to help diagnose this issue @xeffyr; It appears two factors were possibly involved in generating this error after updating packages:  
1. Android update
1. Termux app update

Both are now updated and the error is gone!  I have tried to determine the Termux app version from inside Termux with the hope of generating a Termux app version update check script when updating packages, and am unsuccessful.  

When updating the Termux packages,  is it also possible to check which version of Termux app is being used from within Termux?   Is there a Termux version number somewhere in PREFIX?

**Comment by xeffyr** [comment]
Start with these:
* x86 (32bit): https://dl-cdn.alpinelinux.org/alpine/v3.12/releases/x86/alpine-virt-3.12.2-x86.iso
* x86_64 (64bit): https://dl-cdn.alpinelinux.org/alpine/v3.12/releases/x86_64/alpine-virt-3.12.2-x86_64.iso

Boot downloaded image (basic):
```
qemu-system-i386 -m 512M -nographic -cdrom alpine-virt-3.12.2-x86.iso
```

Modified to boot from URL with no local image:
```
qemu-system-i386 -m 512M -nographic -boot d -drive file=https://dl-cdn.alpinelinux.org/alpine/v3.12/releases/x86/alpine-virt-3.12.2-x86.iso,readonly=on,media=cdrom
```
`CTRL+a x` to terminate VM.

![qemu](https://user-images.githubusercontent.com/25881154/101991910-789aec00-3cb8-11eb-9e58-a789bd9bad8c.png)

Extending command line by switching to VirtIO devices (rng, nic, drives), increasing TCG cache (e.g. by `-accel tcg,tb-size=512`), using musl-based & non-systemd distributions like Alpine Linux makes execution under QEMU faster.

***

Arch Linux can be booted too, yet it is slower and ISO will require many RAM (1-2 GB, maybe more). Probably will have issues with text-only mode and you will need a VNC.

**Comment by SDRausty** [comment]
> The results that I and gotten on my 1st attempt is amazing! Thank you u/xeffyr!

I really appreciate the clarity in your explanation.  I hope that you do not mind that I shared your wonderful example at https://www.reddit.com/r/termux/comments/kc1oit/humble_uxeffyr_writes_start_with_these/ Are these notes on our wiki, by the way?

**Comment by SDRausty** [comment]
https://github.com/termux/proot/issues/141
