### ISSUE TITLE
Octave 6.1 please

### ISSUE THREAD

**Issue by HJarausch** [termux/termux-packages#6147]
Please upgrade Octave to a recent version (6.1)

- [ x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Comment by xeffyr** [comment]
Sorry, but `octave` is not official Termux package.

You should ask about its update in https://github.com/its-pointless/its-pointless.github.io/issues.
