### ISSUE TITLE
Access to external SDCard revealing issues with Dropbear, Openssh, and termux-setup-storage.

### ISSUE THREAD

**Issue by DiagonalArg** [termux/termux-packages#6148]
I can break this up into 3 issues if needed, but it may be more coherent explaining them all together.
------------

**I first tried dropbear**.  I noted that when I ssh to the tablet via dropbear, I am root regardless of whether I `ssh <IP>`, `ssh user@<IP>` or `ssh root@<IP>`.  I found multiple issues:

1. It ignored authorized_users placed in $PREFIX/etc/dropbear or in ~/.ssh
2. I was unable to ssh-copy-id because of complaints regarding ownership of ~/.ssh, regardless of whether owned by root or user.
3. Even if I `su - user` after ssh'ing in, I was unable to use pkg due to permission problems.

**I switched to openssh**, though pkg demanded I uninstall dropbear.  This works fine, though now, however I `ssh` in, I am user and have to su to root.  This is a problem as I would like to `sshfs root@<IP>:/external.sdcard local-mount-folder`.  sshfs needs root to get access to r/w the external sdcard.  (wgreenhouse on IRC pointed out to me that [this patch](https://github.com/termux/termux-packages/blob/master/packages/openssh/auth.c.patch) ignores the user supplied.)

If I go back to dropbear, on the other hand, I can't use pkg, and in addition pkg doesn't allow me to install both.

**Finally, `termux-setup-storage`** is not producing ~/storage/external, even if run as root, nor does it create anything in my external sdcard's Android folder, though other apps, like f-droid, vlc and tor, do have directories there.  I have noted in the past that accessing that card via /storage/[UUID] allows me to read all directories but only write the top directory, *even if I am root*.  As user, I can't access it at all; though VLC and Kodi, once given permission, can read the subdirectoriees there.  That's a fuse overlay mount, and for r/w access to the whole thing, I need to be root and go via /mnt/media_rw/[UUID].

Thanks for your work, and let me know if you need anything else!

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.0.101 #2 SMP PREEMPT Fri Jul 13 09:49:42 EEST 2018 armv7l Android
Device manufacturer:
Barnes & Noble
Device model:
Barnes & Noble Nook Tablet
```

**Comment by xeffyr** [comment]
> first tried dropbear. I noted that when I ssh to the tablet via dropbear, I am root regardless of whether I ssh <IP>, ssh user@<IP> or ssh root@<IP>. I found multiple issues

Don't start `sshd` as root. This is not supported. Also: do not mess with root permission - if you doing so, please keep in mind that SELinux labels take priority over any ownership and files will deny access even if they are "chmod 777".

I don't have any issues with SSH.

> however I ssh in, I am user and have to su to root.

I don't understand where's the problem. Termux was designed for non-root users primarily.

> addition pkg doesn't allow me to install both

`pkg` as root will not work. `apt` will not work either. *Intended behavior to stop you from messing up permissions.*

> Finally, termux-setup-storage is not producing ~/storage/external, even if run as root, nor does it create anything in my external sdcard's Android folder

Then create it manually. Each link points to `/storage/[UUID]/Android/data/com.termux/files`.

One of reasons why `termux-setup-storage` probably did not worked are messed up permissions in $HOME.

***

Summary:
* Don't run servers as root - everything is patched for single-user non-root usage.
* Be very careful when making or modifying files as root.
* If strongly need root, put SELinux into permissive mode: `setenforce 0`.

**Comment by DiagonalArg** [comment]
> > first tried dropbear. I noted that when I ssh to the tablet via dropbear, I am root regardless of whether I ssh , ssh user@ or ssh root@. I found multiple issues
> 
> Don't start `sshd` as root. This is not supported. Also: do not mess with root permission - if you doing so, please keep in mind that SELinux labels take priority over any ownership and files will deny access even if they are "chmod 777".

Perhaps I had started dropbear as root, I actually don't remember.

> > however I ssh in, I am user and have to su to root.
> 
> I don't understand where's the problem. Termux was designed for non-root users primarily.

Fine, but if I `ssh root@tablet`, I'd like to be able to get to root for the reason I described.  (Using sshfs)
 
> > addition pkg doesn't allow me to install both
> 
> `pkg` as root will not work. `apt` will not work either. _Intended behavior to stop you from messing up permissions._

I do understand this.  What I was saying is that I am unable to install both openssh and dropbear.  pkg won't let me.

> > Finally, termux-setup-storage is not producing ~/storage/external, even if run as root, nor does it create anything in my external sdcard's Android folder
> 
> Then create it manually. Each link points to `/storage/[UUID]/Android/data/com.termux/files`.
> 
> One of reasons why `termux-setup-storage` probably did not worked are messed up permissions in $HOME.

I didn't change any permissions in $HOME/storage.  Nothing that should have effected termux-setup-storage.

> Summary:

> * If strongly need root, put SELinux into permissive mode: `setenforce 0`.

Thanks.
