### ISSUE TITLE
SSH: Permission denied (publickey,keyboard-interactive).

### ISSUE THREAD

**Issue by exeQutor** [termux/termux-packages#615]
Hi guys,

I followed all the steps from here: https://oliverse.ch/tech/2015/11/06/run-an-ssh-server-on-your-android-with-termux.html

And even the "**If it still doesn’t work**" section. But I'm still getting this error:

```
ssh 192.168.1.110 -p 8022 -i /home/exequtor/Documents/termux_rsa
Enter passphrase for key '/home/exequtor/Documents/termux_rsa': 
Permission denied (publickey,keyboard-interactive).
```

What do you think I did wrong?

**Comment by Neo-Oli** [comment]
Have you tried running sshd in debug mode?
```
killall sshd
sshd -d
```
What is it's output after trying to connect?

**Comment by exeQutor** [comment]
Sorry, don't know how to copy the text. But here's the screenshots:

![screenshot_2016-12-22-18-17-30-577](https://cloud.githubusercontent.com/assets/2444079/21422650/9e4ef472-c873-11e6-812b-1731e5c64b18.jpeg)
![screenshot_2016-12-22-18-17-42-499](https://cloud.githubusercontent.com/assets/2444079/21422651/9e4f4198-c873-11e6-8e15-25780fcaeefc.jpeg)
![screenshot_2016-12-22-18-17-53-571](https://cloud.githubusercontent.com/assets/2444079/21422652/9e50b640-c873-11e6-8a76-4f1eff798567.jpeg)

**Comment by Neo-Oli** [comment]
hmm it looks like it was just denied. Not a permission problem. When adding your key to to the authorized_keys file you need to add your public key. Did you perhaps add your private key by mistake?

**Comment by exeQutor** [comment]
I re-checked, but it's the public key. The one that starts with **ssh-rsa**.

**Comment by Neo-Oli** [comment]
It looks like your public and private key don't match up. Did you maybe generate the keys multiple times and mixed them up?

**Comment by exeQutor** [comment]
Hmmm. That might be the case. But anyway, instead, I copied my laptop's private and public keys to termux and added the said public key to the authorized_keys, and SSH is now working.

So yeah, my private and public keys basically didn't match up.

Thanks for your time, Oli!
