### ISSUE TITLE
how to install imagemagick in php?

### ISSUE THREAD

**Issue by hazmi-101** [termux/termux-packages#6152]
when I install with:
`pkg install imagemagick`
it works but when I run it via php it can't. how to configure this?

**Comment by ChiefMikeK** [comment]
🗣️ please ask for help @ [r/termux](https://www.reddit.com/r/termux/)
including the script or command line in your post.

**Comment by thunder-coding** [comment]
Closing in favour of #6343. Both issues are for same package, I wonder why didn't anyone else notice this
