### ISSUE TITLE
Apache2:libphp.so file missing !!!

### ISSUE THREAD

**Issue by amm834** [termux/termux-packages#6157]
# libphp.so file for PHP8 missing!

```bash
pwd
/data/data/com.termux/files/usr/libexec/apache2
```
It is missing.
libphp.so file should exist
at
```/data/data/com.termux/files/usr/libexec/apache2``` but it is missing.
Without libphp.so module PHP8 for Apache not running.

**Comment by kcubeterm** [comment]
Install php-apache

**Comment by kcubeterm** [comment]
@amm834 if you know the path then you can do reverse search with whatprovides.
![IMG_20201219_223946](https://user-images.githubusercontent.com/50498359/102695108-51f62b80-424b-11eb-832a-49f8fe7b71eb.jpg)
