### ISSUE TITLE
I'm having this error / E: Unable to locate package pakage name

### ISSUE THREAD

**Issue by erm14as** [termux/termux-packages#6159]
![20201220_114442](https://user-images.githubusercontent.com/69347834/102709156-c5825200-42b8-11eb-8614-30a08ce3bb3a.jpg)

This happens every  time when I try to install package  "E: Unable to locate package pkg name"
Pls fix it.

**Comment by Grimler91** [comment]
Fix what? We don't have an "adb" package so that error message is expected

**Comment by erm14as** [comment]
How am I going to install phonesploit then with out "adb"

**Comment by xeffyr** [comment]
@erm14as *How you are going to install phonesploit* - that's another question, neither related to this issue nor to the topic of Termux packages bug tracker.

All package requests are issues of the lowest priority. If you need `adb` "just now", consider submitting a pull request with all necessary patches and build script.
