### ISSUE TITLE
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by erm14as** [termux/termux-packages#6161]
![20201220_233057](https://user-images.githubusercontent.com/69347834/102723810-dd3ef200-431b-11eb-98cf-cc463cbd1f1d.jpg)

Pls how to fix
I am running termux on android 8.1

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
That's a side-loaded package and requires **a stable network** during installation.
