### ISSUE TITLE
[package request] Age/Rage

### ISSUE THREAD

**Issue by gbu117** [termux/termux-packages#6165]
Would be great to be able to run Age and/or Rage (rust port) encryption tool on Termux without the need for compilation which takes up a lot of space, especially for rage which can be observed when trying to install it using cargo.

Age:

https://github.com/FiloSottile/age

Rage:

https://github.com/str4d/rage

**Comment by xeffyr** [comment]
`age` has been added in https://github.com/termux/termux-packages/commit/8de05c84e7e2c3d68d1250afbd52216586e8d785 and soon will be available for installation.
