### ISSUE TITLE
fish_update_completions misses "manpath"

### ISSUE THREAD

**Issue by flasheater** [termux/termux-packages#617]
'fish_update_completions' is a special built-in function of fish that scans the man pages in order to provide completions.

Running it though, produces following exception: 
https://notehub.org/y4lcv

I have tried to set the MANPATH manually
```
set -Ux MANPATH "$PREFIX/share/fish/man:$PREFIX/share/man"
```
but it had seemingly no effect.

**Comment by fornwall** [comment]
Thanks for reporting!

This has been fixed in the `2.4.0-1` updated version of the fish package, to which you can update with `apt update && apt upgrade`.

**Comment by flasheater** [comment]
Thank you! Loving the hell out of Termux :)
