### ISSUE TITLE
mc breaks swiping when suspended

### ISSUE THREAD

**Issue by SharakPL** [termux/termux-packages#6173]
**Problem description**
When Midnight Commander is suspended, swiping is blocked. It simply outputs swipe calls to the console instead:

![Screenshot_20201224-092836](https://user-images.githubusercontent.com/5007456/103075087-32545f80-45cb-11eb-8e1c-65fb33cce861.png)

**Steps to reproduce**
1. `pkg install mc`
2. `mc`
3. hit CTRL + z
4. Try to swipe the view

**Expected behavior**
Correct swiping :)

**Additional information**

Android 10, all packages updated

**Comment by RalfWerner** [comment]
`mc+^z ` seems to be a known _problem._ I can track _yours_ on all of my devices. One workaround is _nomal_ quit/F10 after restarting `mc`. Maybe someone else has a better solution.

**Comment by SharakPL** [comment]
@RalfWerner no. The issue is not about getting out of mc. For that all you need is run `fg` command to bring back mc and hit quit/F10 as always. But this will simply stop mc process. The point here is to get rid of unwanted output from the console when mc is suspended.

**Comment by RalfWerner** [comment]
>  to get rid of unwanted output from the console

This is the result of an unresolved SIGNAL query! and is canceled with the "correct" close - therefore **"workaround"**
If you use `mc` often a separate shell in the DRAWER and the following keys are useful:
```
echo "extra-keys-style=arrows-all
shortcut.next-session=ctrl+n
extra-keys=[[{macro:CTRL,display='^'},TAB,LEFT,RIGHT,{key: UP,popup:PGUP},{key:DOWN,popup:PGDN},{key:ENTER,popup:{macro:'CTRL n',display:'next'}},{key:KEYBOARD,popup:DRAWER},{macro:'mc SPACE i ENTER',  display:mc,popup:F10},{display:X11,macro:'t SPACE 0 ENTER'}]]
">.termux/termux.properties
```

**Comment by SharakPL** [comment]
I'm only using Termux from Google Play for now :( Can someone confirm it's still there on latest Termux?
