### ISSUE TITLE
polybar

### ISSUE THREAD

**Issue by emirbyte** [termux/termux-packages#6175]
**Problem description**

**Steps to reproduce**
pkg install polybar

**Expected behavior**
it should install polybar

**Additional information**
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://main.termux-mirror.ml/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.112-perf-17034026 #1 SMP PREEMPT Tue May 19 14:14:47 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T290

```

```

**Comment by WMCB-Tech** [comment]
I don't understand what's the problem

Maybe you installed it but don't know how to use it
