### ISSUE TITLE
Package update list is borked

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [termux/termux-packages#6177]
E: Failed to fetch https://grimler.se/termux-packages-24/dists/stable/main/binary-arm/Packages.bz2  File has unexpected size (126887 != 125847). Mirror sync in progress? [IP: 185.76.64.26 443]
   Hashes of expected file:
    - Filesize:125847 [weak]
    - SHA256:5718dcae9b9c5fd16751846ebb02d0f80ed3e46adaa93d71ce5419c3557c5913
    - SHA1:01785b744c9e05dd5933e352bc4d3982abb94a5f [weak]
    - MD5Sum:e7e3dccf6294c623d0f0c3f3381e31b6 [weak]
   Release file created at: Thu, 24 Dec 2020 16:06:53 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by Grimler91** [comment]
Thanks for reporting, should work now again!
