### ISSUE TITLE
Rust 1.48.0 update fails

### ISSUE THREAD

**Issue by mklein994** [termux/termux-packages#6178]
**Problem description**

Updating rust from 1.46.0-2 to 1.48.0 fails.

**Steps to reproduce**

Immediately after running `apt update`:
```console
$ apt full-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  rust
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 86.0 MB of archives.
After this operation, 109 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 rust aarch64 1.48.0 [86.0 MB]
Err:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 rust aarch64 1.48.0
  Error reading from server - read (5: I/O error) [IP: 35.161.162.245 443]
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/rust_1.48.0_aarch64.deb  Error reading from server - read (5: I/O error) [IP: 35.161.162.245 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
$ apt full-upgrade --fix-missing
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  rust
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 86.0 MB of archives.
After this operation, 109 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 rust aarch64 1.48.0 [86.0 MB]
Err:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 rust aarch64 1.48.0
  Error reading from server - read (5: I/O error) [IP: 52.43.200.1 443]
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/rust_1.48.0_aarch64.deb  Error reading from server - read (5: I/O error) [IP: 52.43.200.1 443]
$
```

**Expected behavior**

Rust updates successfully.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
Updatable packages:
rust/stable 1.48.0 aarch64 [upgradable from: 1.46.0-2]
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Sat Sep 26 02:57:53 KST 2020 aarch64 Android
Device manufacturer:
LGE
Device model:
LM-G820
```

**Comment by Grimler91** [comment]
Looks like some sort of temporary error(?), works for me on android 10, aarch64. Try switching to another repo with the `termux-change-repo` tool if it persists

**Comment by xeffyr** [comment]
> Looks like some sort of temporary error

It is not temporary, it was already reported by some random users. That's something to do with Bintray.

**Comment by atharvadnaik** [comment]
I think clang 11.0.0-1 update broke the whole rust package...My problem solved after running pkg install clang rust instead of just pkg install rust

**Comment by mklein994** [comment]
Like @atharvadnaik said, I too had issues installing clang and friends, which was resolved by installing clang first (I believe with `--fix-broken`).

Switching mirrors worked for me; I updated rust using grimler.se and haven't had any problems since. The mirrors would have the same packages, right (if they're in sync)?

They're all distributed from the same build?

**Comment by xeffyr** [comment]
@mklein994 Mirrors replicate stuff from https://dl.bintray.com/termux/termux-packages-24/.

**Comment by ooshlablu** [comment]
I commented in the freenode channel yesterday, but I noticed the same behaviour. `rust` from the bintray repo repo was broken, with apt throwing an i/o error when the package appeared to be fully retrieved. Using the `termux.mentality.rip` repo appears to work perfectly fine.

**Comment by xeffyr** [comment]
Ok, I finally has managed to reproduce the `apt` issue myself.

Interesting that package can be downloaded successfully with `curl` and after that `apt` works fine somehow:
![Screenshot_20201229-172456_Termux](https://user-images.githubusercontent.com/25881154/103294618-e0606f00-49fa-11eb-953b-17e724046da7.png)

Seems like issue is with package caching as Bintray has to load it first to CDN - can be an answer why `apt` re-downloaded it without issues after download attempt with `curl`.

However even if Bintray is faulty, we literally have no alternatives which will be suitable for us. Mirrors are provided solely as "backup" and to reduce traffic on Bintray.

**Comment by vaultec81** [comment]
@xeffyr Why was this closed? I am having the same issue with all packages I attempt to install fail, I even get "Forbidden!" when going to https://dl.bintray.com/ on a normal windows 10 PC. 
Does anyone have a solution/work around for this?

**Comment by xeffyr** [comment]
This issue is not about "Forbidden" errors and considering that Bintray was a third-party SaaS service (and thus we have no control over its servers), it has to be closed anyway.
