### ISSUE TITLE
[Package Request]: libopenmpt

### ISSUE THREAD

**Issue by Midi-In** [termux/termux-packages#6179]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

An open source, high compatibility library and a CLI player for playing back popular sample-based tracker modules.

**Link to home page and sources**
1. Home page: https://lib.openmpt.org/libopenmpt/
2. Source code: https://lib.openmpt.org/libopenmpt/download/

**Additional information**
Have you compiled or tried to compile the package on device?
No
* If it did not work then please provide the error you ran into.

* If it did work then please share build steps and any patches that you had to apply.

**Comment by shoya0x00** [comment]
libopenmpt requires `libmpg123` library and it's not yet available in termux repo

**Comment by thibaultmeyer** [comment]
`libmpg3` is now available

**Comment by xeffyr** [comment]
No, it was only added to Git. Package is not available because of typo in `build.sh` (wondering how it got merged).
```
TERMUX_PKG_HOMEPAGE=hthttp://mpg123.org/
```

**Comment by kcubeterm** [comment]
libopenmpt is available ??

**Comment by xeffyr** [comment]
Now `libopenmpt` is available.
