### ISSUE TITLE
GoLang not installing

### ISSUE THREAD

**Issue by IshanKBG** [termux/termux-packages#6181]
Dear, Termux Team,
I have a bug to report
While installing GoLang package using `pkg install golang` or `apt install GoLang` the download gets stopped in halfway says error
```
Error reading from server - read (5: I/O error) [IP: 54.187.208.114 443]
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/golang_2:1.15.6-1_aarch64.deb  Error reading from server - read (5: I/O error) [IP: 54.187.208.114 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
I also tried fixing the issues by typing some commands but still not working 
I also have enough storage and internet.
If you know what's the reason please guide me.

**Comment by xeffyr** [comment]
Switch to a different repository host by using `termux-change-repo`.

We can't do anything with that, that's not our issue. Unstable connection (packet loss) or usage of Deep-Packet-Inspection by your ISP to monitor traffic could be a reason.

**Comment by sk0kanik** [comment]
downloading deb file using curl and installing using dpkg worked in my case
