### ISSUE TITLE
Python Matplotlib library issue

### ISSUE THREAD

**Issue by jamsahpe** [termux/termux-packages#6182]
Matplotlib library of python is giving error while installing it on termux how to fix it

**Comment by Grimler91** [comment]
See also: https://github.com/termux/termux-packages/issues/1629

**Comment by jamsahpe** [comment]
> Matplotlib library of python is giving error while installing it on termux how to fix it

    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-bn7wcxxa/kiwisolver_91140a8dc7d147f3b253c8ab2b75328e/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-bn7wcxxa/kiwisolver_91140a8dc7d147f3b253c8ab2b75328e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-uilt4_p4
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-bn7wcxxa/kiwisolver_91140a8dc7d147f3b253c8ab2b75328e/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-wheel-mfxqpe4i/cppy_907443607bea42a3a96c9473053877c8/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-wheel-mfxqpe4i/cppy_907443607bea42a3a96c9473053877c8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /data/data/com.termux/files/usr/tmp/pip-wheel-6d4n70de
           cwd: /data/data/com.termux/files/usr/tmp/pip-wheel-mfxqpe4i/cppy_907443607bea42a3a96c9473053877c8/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cppy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/data/data/com.termux/files/usr/tmp/tmp5ixbnojm', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-bn7wcxxa/kiwisolver_91140a8dc7d147f3b253c8ab2b75328e/setup.py", line 69, in <module>
        setup(
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/data/data/com.termux/files/usr/tmp/tmp5ixbnojm', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jamsahpe** [comment]
Help me
This is the error.




ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -c 'import sys,
setuptools, tokenize; sys.argv[0] =
'"'"'/data/data/com.termux/files/usr/tmp/pip-install-bn7wcxxa/kiwisolver_91140a8dc7d147f3b253c8ab2b75328e/setup.py'"'"';
__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-bn7wcxxa/kiwisolver_91140a8dc7d147f3b253c8ab2b75328e/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
egg_info --egg-base
/data/data/com.termux/files/usr/tmp/pip-pip-egg-info-uilt4_p4
         cwd:
/data/data/com.termux/files/usr/tmp/pip-install-bn7wcxxa/kiwisolver_91140a8dc7d147f3b253c8ab2b75328e/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import
sys, setuptools, tokenize; sys.argv[0] =
'"'"'/data/data/com.termux/files/usr/tmp/pip-wheel-mfxqpe4i/cppy_907443607bea42a3a96c9473053877c8/setup.py'"'"';
__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-wheel-mfxqpe4i/cppy_907443607bea42a3a96c9473053877c8/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
bdist_wheel -d /data/data/com.termux/files/usr/tmp/pip-wheel-6d4n70de
           cwd:
/data/data/com.termux/files/usr/tmp/pip-wheel-mfxqpe4i/cppy_907443607bea42a3a96c9473053877c8/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cppy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File
"/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/installer.py",
line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py",
line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command
'['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip',
'--disable-pip-version-check', 'wheel', '--no-deps', '-w',
'/data/data/com.termux/files/usr/tmp/tmp5ixbnojm', '--quiet',
'cppy>=1.1.0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File
"/data/data/com.termux/files/usr/tmp/pip-install-bn7wcxxa/kiwisolver_91140a8dc7d147f3b253c8ab2b75328e/setup.py",
line 69, in <module>
        setup(
      File
"/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/__init__.py",
line 164, in setup
        _install_setup_requires(attrs)
      File
"/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/__init__.py",
line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File
"/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/dist.py",
line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File
"/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py",
line 779, in resolve
        dist = best[req.key] = env.best_match(
      File
"/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py",
line 1064, in best_match
        return self.obtain(req, installer)
      File
"/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py",
line 1076, in obtain
        return installer(requirement)
      File
"/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/dist.py",
line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File
"/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/installer.py",
line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command
'['/data/data/com.termux/files/usr/bin/python3', '-m', 'pip',
'--disable-pip-version-check', 'wheel', '--no-deps', '-w',
'/data/data/com.termux/files/usr/tmp/tmp5ixbnojm', '--quiet',
'cppy>=1.1.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info
Check the logs for full command output.
