### ISSUE TITLE
Cannot install clangd because its.pointless.github.io is down

### ISSUE THREAD

**Issue by mebl** [termux/termux-packages#6186]
**Problem description**
I get an error message when running
`$ pkg install clangd`
or
`$ pkg install clangd --fix-missing`

**Steps to reproduce**
Run the commands above. Tried running 
`$ apt update && apt upgrade` as suggested in issue https://github.com/termux/termux-packages/issues/5014 but it doesn't seem to be related.

**Expected behavior**
Installation of clangd

**Additional information**
I get this error message

`
Err:1 https://its-pointless.github.io/files/24 termux/extras aarch64 clangd aarch64 9.0.1-3
  404  Not Found [IP: 185.199.111.153 443]
E: Failed to fetch https://its-pointless.github.io/files/24/dists/termux/extras/binary-aarch64/clangd_9.0.1-3_aarch64.deb  404  Not Found [IP: 185.199.111.153 443]
E: Internal Error, ordering was unable to handle the media swap
`

**Comment by Grimler91** [comment]
`clangd` is part of the `clang` package since half a year ago or something. It is not available from its-pointless repository. 

Maybe this is a caching issue, it is weird that apt on your device still thinks clangd exists.

its-pointless.github.io is not down, but that deb does not exist.

**Comment by mebl** [comment]
Thanks for the quick reply!
