### ISSUE TITLE
Installing Chatterbot (spacy)

### ISSUE THREAD

**Issue by Sakon13** [termux/termux-packages#6187]
Is there a way to install chatterbot on Termux. Whenever I try to install chatterbot it returns an error because it cannot install spacy properly
The Error↓
 `ERROR: Command errored out with exit status 1:                   command: '/data/data/com.termux/files/home/Black Rose/bin/python' '/data/data/com.termux/files/home/Black Rose/lib/python3.8/site-packages/pip' install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-mwtm_jpf/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'cython>=0.25' 'cymem>=2.0.2,<2.1.0' 'preshed>=3.0.2,<3.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.4.1,<7.5.0' 'blis>=0.4.0,<0.8.0' 'numpy>=1.15.0'                                                                     cwd: None                                                  Complete output (174 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/setuptools/                 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/setuptools/                 Collecting blis<0.8.0,>=0.4.0                                     Using cached blis-0.7.4.tar.gz (2.8 MB)
    Installing build dependencies: started                          Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started                    Getting requirements to build wheel: finished with status 'done'
    Installing backend dependencies: started
    Installing backend dependencies: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting cymem<2.1.0,>=2.0.2
    Using cached cymem-2.0.5-cp38-cp38-linux_aarch64.whl
  Collecting cython>=0.25
    Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached murmurhash-1.0.5-cp38-cp38-linux_aarch64.whl
  Collecting numpy>=1.15.0
    Using cached numpy-1.19.4-cp38-cp38-linux_aarch64.whl
  Collecting preshed<3.1.0,>=3.0.2
    Using cached preshed-3.0.5-cp38-cp38-linux_aarch64.whl
  Collecting setuptools
    Using cached setuptools-51.1.0-py3-none-any.whl (2.0 MB)
  Collecting thinc<7.5.0,>=7.4.1
    Using cached thinc-7.4.5.tar.gz (1.3 MB)
    Installing build dependencies: started
    Installing build dependencies: still running...
    Installing build dependencies: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: '/data/data/com.termux/files/home/Black Rose/bin/python' '/data/data/com.termux/files/home/Black Rose/lib/python3.8/site-packages/pip' install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-lazkaf5z/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'cython>=0.25' 'murmurhash>=0.28.0,<1.1.0' 'cymem>=2.0.2,<2.1.0' 'preshed>=1.0.1,<3.1.0' 'blis>=0.4.0,<0.8.0' 'numpy>=1.15.0'
         cwd: None
    Complete output (137 lines):
    Collecting blis<0.8.0,>=0.4.0
      Using cached blis-0.7.4.tar.gz (2.8 MB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Installing backend dependencies: started
      Installing backend dependencies: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'done'
    Collecting cymem<2.1.0,>=2.0.2
      Using cached cymem-2.0.5-cp38-cp38-linux_aarch64.whl
    Collecting cython>=0.25
      Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
    Collecting murmurhash<1.1.0,>=0.28.0
      Using cached murmurhash-1.0.5-cp38-cp38-linux_aarch64.whl
    Collecting numpy>=1.15.0
      Using cached numpy-1.19.4-cp38-cp38-linux_aarch64.whl
    Collecting preshed<3.1.0,>=1.0.1
      Using cached preshed-3.0.5-cp38-cp38-linux_aarch64.whl
    Collecting setuptools
      Using cached setuptools-51.1.0-py3-none-any.whl (2.0 MB)
    Building wheels for collected packages: blis
      Building wheel for blis (PEP 517): started
      Building wheel for blis (PEP 517): finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: '/data/data/com.termux/files/home/Black Rose/bin/python' '/data/data/com.termux/files/home/Black Rose/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py' build_wheel /data/data/com.termux/files/usr/tmp/tmp_2a9yzra
           cwd: /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c
      Complete output (102 lines):
      BLIS_COMPILER? None
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-3.8
      creating build/lib.linux-aarch64-3.8/blis
      copying blis/benchmark.py -> build/lib.linux-aarch64-3.8/blis
      copying blis/__init__.py -> build/lib.linux-aarch64-3.8/blis
      copying blis/about.py -> build/lib.linux-aarch64-3.8/blis
      creating build/lib.linux-aarch64-3.8/blis/tests
      copying blis/tests/test_dotv.py -> build/lib.linux-aarch64-3.8/blis/tests
      copying blis/tests/common.py -> build/lib.linux-aarch64-3.8/blis/tests
      copying blis/tests/test_gemm.py -> build/lib.linux-aarch64-3.8/blis/tests
      copying blis/tests/__init__.py -> build/lib.linux-aarch64-3.8/blis/tests
      copying blis/py.pyx -> build/lib.linux-aarch64-3.8/blis
      copying blis/cy.pyx -> build/lib.linux-aarch64-3.8/blis
      copying blis/cy.pxd -> build/lib.linux-aarch64-3.8/blis
      copying blis/__init__.pxd -> build/lib.linux-aarch64-3.8/blis
      running build_ext
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:78:1: error: inline assembly requires more registers than available
      "                                            \n\t"
      ^
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:78:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:78:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:78:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:78:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:78:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:78:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:78:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:1132:1: error: inline assembly requires more registers than available
      "                                            \n\t"
      ^
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:1132:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:1132:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:1132:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:1132:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:1132:1: error: inline assembly requires more registers than available
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:78:1: warning: inline asm clobber list contains reserved registers: X18 [-Winline-asm]
      "                                            \n\t"
      ^
      <inline asm>:1:1: note: instantiated into assembly here

      ^
      /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:78:1: note: Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
      "                                            \n\t"
      ^
      <inline asm>:1:1: note: instantiated into assembly here

      ^
      1 warning and 14 errors generated.
      Build options linux unix
      BUILD ARCH: cortexa57
      {'SHELL': '/bin/bash', 'TRAVIS_OSX_IMAGE': '', 'TRAVIS_JOB_WEB_URL': 'https://travis-ci.org/explosion/cython-blis/jobs/718174465', 'TRAVIS_REPO_SLUG': 'explosion/cython-blis', 'SUDO_GID': '0', 'TRAVIS_APT_PROXY': 'http://build-cache.travisci.net', 'ANSI_RED': '\\033[31;1m', 'rvm_prefix': '/home/travis', 'TRAVIS_CMD': 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./bin/generate-make-jsonl linux $BLIS_ARCH --export; fi', 'ANSI_CLEAR': '\\033[0K', 'TRAVIS_BUILD_ID': '718174460', 'TRAVIS_LANGUAGE': 'python', 'TRAVIS_TEST_RESULT': '', 'TRAVIS_TIMER_START_TIME': '1597496339808703115', 'APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE': '1', 'MY_RUBY_HOME': '/home/travis/.rvm/rubies/ruby-2.7.0', 'SUDO_COMMAND': '/usr/bin/bash /home/travis/build.sh', 'MYSQL_UNIX_PORT': '/var/run/mysqld/mysqld.sock', 'SUDO_USER': 'root', 'PERLBREW_HOME': '/home/travis/.perlbrew', 'TRAVIS_PULL_REQUEST_BRANCH': '', 'CONTINUOUS_INTEGRATION': 'true', 'RUBY_VERSION': 'ruby-2.7.0', 'PERLBREW_SHELLRC_VERSION': '0.88', 'PWD': '/home/travis/build/explosion/cython-blis/flame-blis', 'ANSI_RESET': '\\033[0m', 'LOGNAME': 'travis', 'TRAVIS_INTERNAL_RUBY_REGEX': '^ruby-(2\\.[0-4]\\.[0-9]|1\\.9\\.3)', 'TRAVIS_INFRA': 'unknown', 'TRAVIS_BUILD_NUMBER': '624', 'rvm_version': '1.29.10 (latest)', 'MANPATH': '/home/travis/.nvm/versions/node/v8.12.0/share/man:/home/travis/.kiex/elixirs/elixir-1.9.1/man:/usr/local/man:/usr/local/share/man:/usr/share/man', 'TRAVIS_EVENT_TYPE': 'api', 'TRAVIS_ARCH': 'aarch64', 'ANSI_YELLOW': '\\033[33;1m', 'container': 'lxc', 'PIP_PROGRESS_BAR': 'off', 'HOME': '/home/travis', 'TRAVIS_DIST': 'focal', 'LANG': 'C.UTF-8', 'TRAVIS_OS_NAME': 'linux', 'VIRTUAL_ENV': '/home/travis/virtualenv/python3.7.8', 'TRAVIS_ENABLE_INFRA_DETECTION': 'true', 'GIT_ASKPASS': 'echo', 'TRAVIS_TAG': '', 'TRAVIS_FILTERED': 'redirect_io', 'TRAVIS_COMMIT': 'cef3ec4fc5486458ddd6cd117513985ce3ad13f9', 'TRAVIS_TMPDIR': '/tmp/tmp.IwNDIYQhsz', 'PLAT': 'x86_64', 'TRAVIS_HOME': '/home/travis', 'TRAVIS_BRANCH': 'master', 'TRAVIS_SUDO': 'true', 'TRAVIS_BUILD_DIR': '/home/travis/build/explosion/cython-blis', 'TRAVIS_PYTHON_VERSION': '3.7', 'NVM_DIR': '/home/travis/.nvm', 'rvm_bin_path': '/home/travis/.rvm/bin', 'GEM_PATH': '/home/travis/.rvm/gems/ruby-2.7.0:/home/travis/.rvm/gems/ruby-2.7.0@global', 'GEM_HOME': '/home/travis/.rvm/gems/ruby-2.7.0', 'TRAVIS_SECURE_ENV_VARS': 'false', 'TRAVIS_TIMER_ID': '163ea0c0', 'TERM': 'xterm', 'UNICODE_WIDTH': '32', 'USER': 'travis', 'PIP_DISABLE_PIP_VERSION_CHECK': '1', 'TRAVIS_JOB_ID': '718174465', 'TRAVIS_CPU_ARCH': 'arm64', 'TRAVIS_PULL_REQUEST_SLUG': '', 'SHLVL': '1', 'NVM_CD_FLAGS': '', 'PAGER': 'cat', 'BLIS_ARCH': 'cortexa57', 'TRAVIS_JOB_NUMBER': '624.5', 'TRAVIS_ROOT': '/', 'TRAVIS_COMMIT_MESSAGE': "Don't try to export wheel from travis", 'TRAVIS_ALLOW_FAILURE': '', 'TRAVIS_APP_HOST': 'build.travis-ci.org', 'PS4': '+', 'ANSI_GREEN': '\\033[32;1m', 'TRAVIS_PULL_REQUEST_SHA': '', 'ELIXIR_VERSION': '1.9.1', 'TRAVIS_BUILD_STAGE_NAME': '', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'TRAVIS_PULL_REQUEST': 'false', 'TRAVIS_COMMIT_RANGE': '9ea1f52ce0327c4734cfddc5c06ffe6b43a3b3dc...cef3ec4fc5486458ddd6cd117513985ce3ad13f9', 'PATH': '/home/travis/virtualenv/python3.7.8/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.rvm/gems/ruby-2.7.0/bin:/home/travis/.rvm/gems/ruby-2.7.0@global/bin:/home/travis/.rvm/rubies/ruby-2.7.0/bin:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.kiex/elixirs/elixir-1.9.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/travis/.phpenv/bin:/home/travis/.rvm/bin', 'TRAVIS_INIT': 'systemd', 'CC': 'gcc', 'CI': 'true', 'SUDO_UID': '0', 'PERLBREW_ROOT': '/home/travis/perl5/perlbrew', 'NVM_BIN': '/home/travis/.nvm/versions/node/v8.12.0/bin', 'TRAVIS': 'true', 'MIX_ARCHIVES': '/home/travis/.kiex/mix/elixir-1.9.1', 'IRBRC': '/home/travis/.rvm/rubies/ruby-2.7.0/.irbrc', 'TRAVIS_BUILD_WEB_URL': 'https://travis-ci.org/explosion/cython-blis/builds/718174460', 'DEBIAN_FRONTEND': 'noninteractive', 'TRAVIS_JOB_NAME': '', 'rvm_path': '/home/travis/.rvm', 'OLDPWD': '/home/travis/build/explosion/cython-blis', 'HAS_JOSH_K_SEAL_OF_APPROVAL': 'true', '_': '/home/travis/virtualenv/python3.7.8/bin/python'}
      [COMMAND] gcc -c /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/config/cortexa57/bli_cntx_init_cortexa57.c -o /data/data/com.termux/files/usr/tmp/tmplwu04kd1/bli_cntx_init_cortexa57.o -O3 -ftree-vectorize -mtune=cortex-a57 -fPIC -std=c99 -fvisibility=hidden -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.7.0" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-cortexa57 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/3/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/include/linux-cortexa57
      [COMMAND] gcc -c /data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c -o /data/data/com.termux/files/usr/tmp/tmplwu04kd1/bli_gemm_armv8a_asm_d6x8.o -O3 -ftree-vectorize -mtune=cortex-a57 -march=armv8-a+fp+simd -mcpu=cortex-a57 -fPIC -std=c99 -fvisibility=hidden -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.7.0" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-cortexa57 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/3/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/include/linux-cortexa57
      Traceback (most recent call last):
        File "/data/data/com.termux/files/home/Black Rose/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/data/data/com.termux/files/home/Black Rose/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/data/com.termux/files/home/Black Rose/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-cmm1hjyt/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 216, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-cmm1hjyt/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-cmm1hjyt/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 284, in <module>
          setup(
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-cmm1hjyt/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/data/data/com.termux/files/usr/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/data/data/com.termux/files/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-cmm1hjyt/normal/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/data/data/com.termux/files/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "setup.py", line 105, in build_extensions
          objects = self.compile_objects(platform_name, arch, OBJ_DIR)
        File "setup.py", line 221, in compile_objects
          objects.append(self.build_object(env=env, **spec))
        File "setup.py", line 235, in build_object
          subprocess.check_call(command, cwd=BLIS_DIR)
        File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['gcc', '-c', '/data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c', '-o', '/data/data/com.termux/files/usr/tmp/tmplwu04kd1/bli_gemm_armv8a_asm_d6x8.o', '-O3', '-ftree-vectorize', '-mtune=cortex-a57', '-march=armv8-a+fp+simd', '-mcpu=cortex-a57', '-fPIC', '-std=c99', '-fvisibility=hidden', '-D_GNU_SOURCE', '-D_POSIX_C_SOURCE=200112L', '-DBLIS_VERSION_STRING="0.7.0"', '-DBLIS_IS_BUILDING_LIBRARY', '-Iinclude/linux-cortexa57', '-I./frame/3/', '-I./frame/ind/ukernels/', '-I./frame/3/', '-I./frame/1m/', '-I./frame/1f/', '-I./frame/1/', '-I./frame/include', '-I/data/data/com.termux/files/usr/tmp/pip-install-7xgi25r6/blis_81ba5759b547455d99b37bcb4dfa309c/blis/_src/include/linux-cortexa57']' returned non-zero exit status 1.
      ----------------------------------------
      ERROR: Failed building wheel for blis
    Failed to build blis
    ERROR: Could not build wheels for blis which use PEP 517 and cannot be installed directly
    WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
    You should consider upgrading via the '/data/data/com.termux/files/home/Black Rose/bin/python -m pip install --upgrade pip' command.
    ----------------------------------------
  ERROR: Command errored out with exit status 1: '/data/data/com.termux/files/home/Black Rose/bin/python' '/data/data/com.termux/files/home/Black Rose/lib/python3.8/site-packages/pip' install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-lazkaf5z/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'cython>=0.25' 'murmurhash>=0.28.0,<1.1.0' 'cymem>=2.0.2,<2.1.0' 'preshed>=1.0.1,<3.1.0' 'blis>=0.4.0,<0.8.0' 'numpy>=1.15.0' Check the logs for full command output.
  WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
  You should consider upgrading via the '/data/data/com.termux/files/home/Black Rose/bin/python -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: '/data/data/com.termux/files/home/Black Rose/bin/python' '/data/data/com.termux/files/home/Black Rose/lib/python3.8/site-packages/pip' install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-mwtm_jpf/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'cython>=0.25' 'cymem>=2.0.2,<2.1.0' 'preshed>=3.0.2,<3.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.4.1,<7.5.0' 'blis>=0.4.0,<0.8.0' 'numpy>=1.15.0' Check the logs for full command output.`

**Comment by kcubeterm** [comment]
Error due to blis. Install spacy as stated in pypi of blis.
```
BLIS_ARCH="generic" pip install spacy
```
