### ISSUE TITLE
State of voice call (ongoing , not answered (reason if possible), picked call  ,hung up)

### ISSUE THREAD

**Issue by aayushchowhan** [termux/termux-packages#6189]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
I don't understand what you are trying to request. Also your package request template is not filled properly.
