### ISSUE TITLE
package-request:apt-fast

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#6190]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

Its a wrapper to download and install apt packages fastly using aria2.
If it would be configured to use in termux then installing packages from termux repo will get faster.

**Link to home page and sources**
1. Home page:https://github.com/ilikenwf/apt-fast
2. Source code:https://github.com/ilikenwf/apt-fast

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
No, this is something that won't be done.

1. Initiating multiple connections break the purpose of CDN caching.
2. Using custom package downloaders also makes usage monitoring harder. In fact, I'm planning to restrict usage of something other than `apt` to ensure that packages are used exclusively by Termux app and not something else.
