### ISSUE TITLE
PHP7.3 I'd like not PHP8

### ISSUE THREAD

**Issue by gyurmogyuri** [termux/termux-packages#6192]
Hello, how can I install old version of php? Not have compatibility of "get_magic_quotes_gpc". So this because I need to change version back.
Do you have any idea?
Thanks,

**Comment by xeffyr** [comment]
You can get php v7.x from https://github.com/Termux-pod/termux-pod which is kept by @kcubeterm.

Termux does not provide a way to downgrade on its own.
