### ISSUE TITLE
alpha package not being purged when official version merged/uploaded (cfengine 3.17.0a1-termux -> cfengine 3.17.0)

### ISSUE THREAD

**Issue by craigcomstock** [termux/termux-packages#6193]
I submitted a PR for upgrading cfengine to 3.17.0 and it was merged.

When I go to install with `pkg install cfengine` though I get the previous version.

Looking at https://dl.bintray.com/termux/termux-packages-24/dists/stable/main/binary-arm/Packages I see both versions are still present. This seems incorrect.

```
Package: cfengine
Architecture: arm
Installed-Size: 4512
Maintainer: @cfengine
Version: 3.17.0
Homepage: https://cfengine.com/
Depends: liblmdb, openssl, libandroid-glob, pcre, libyaml, libxml2
Description: CFEngine is a configuration management technology.
Filename: arm/cfengine_3.17.0_arm.deb
SHA1: b8cd4ac8250d41945264e726edec013eb4486cc7
SHA256: cd966dd768c0372cdf88e1b809882abdbfad87bb94c1c5992b6e8413e8617c10
Size: 770930

Package: cfengine
Architecture: arm
Installed-Size: 4472
Maintainer: Termux members @termux
Version: 3.17.0a1-termux-0
Homepage: https://cfengine.com/
Depends: liblmdb, openssl, libandroid-glob, pcre, libyaml, libxml2
Description: CFEngine is a configuration management technology.
Filename: arm/cfengine_3.17.0a1-termux-0_arm.deb
SHA1: 5faf38d4e3b31ebe554129ef32b9ba101a61221b
SHA256: 5048e7b3f5f24677c8cde8b7d5a304e6c262835e30cea05503e9bfbda84cfc96
Size: 755316

Package: cfengine-static
Architecture: arm
Installed-Size: 4400
Maintainer: @cfengine
Version: 3.17.0
Homepage: https://cfengine.com/
Depends: cfengine (= 3.17.0)
Description: Static libraries for cfengine
Filename: arm/cfengine-static_3.17.0_arm.deb
SHA1: 875aa58f294abe634d53fc4bff8f29619b040dff
SHA256: fd89bd6ab6dcde76f04de34b7356b28306439f3dc5661c9de88b5a1aeb39a18d
Size: 1109634
```

I was trying to use https://semver.org/ style to label the alpha release but maybe this isn't quite correct or the upload step doesn't handle this situation yet?

Would a manual purge be in order of the 3.17.0a1-termux packages?

Or can you direct me to the script that could take a change to handle this situation when a PR is merged to master?

**Comment by xeffyr** [comment]
You have changed versioning scheme without bumping package epoch.

New version should be `1:3.17.0`. I will fix that manually.

**Comment by craigcomstock** [comment]
@xeffyr thanks! 

How would I have known to do this? Just wondering if I can help add to the docs somewhere? I don't see anything here: https://github.com/termux/termux-packages/wiki/Creating-new-package

Found it: https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md

thanks! :) Sorry I didn't see it. I didn't realize 3.17.0a1-termux -> 3.17.0 wouldn't be handled.

Got it.

**Comment by craigcomstock** [comment]
Thanks @xeffyr,  works!

```
Unpacking cfengine (1:3.17.0) over (3.17.0a1-termux-0) ...
Setting up cfengine (1:3.17.0) ...
```
