### ISSUE TITLE
[Package Request] hydroxide

### ISSUE THREAD

**Issue by Midi-In** [termux/termux-packages#6194]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

Hydroxide is a local ProtonMail proxy/gateway

**Link to home page and sources**
1. Home page: https://github.com/emersion/hydroxide
2. Source code: https://github.com/emersion/hydroxide

**Additional information**
Have you compiled or tried to compile the package on device?

Yes, resulted in a failure
* If it did not work then please provide the error you ran into.

After following the installation guide from the readme, the compilation process interrupted with following output:
![Screenshot_20201230-021705_1](https://user-images.githubusercontent.com/42059764/103323897-4245c680-4a45-11eb-99ae-2df795716775.png)

* If it did work then please share build steps and any patches that you had to apply.

**Comment by kcubeterm** [comment]
Update golang and then try, it should be compile successfully.

**Comment by Midi-In** [comment]
Golang had been freshly installed by me just for this occasion, so that's not the culprit, I'm afraid

**Comment by Grimler91** [comment]
@Midi-In weird, as @kcubeterm said that problem should have been [fixed](https://github.com/termux/termux-packages/blob/master/packages/golang/clang11-fix.patch) in golang version 2:1.15.6-3. Could you check which version you have installed? (With `apt show golang` for example)

**Comment by Midi-In** [comment]
I must have had an incorrect golang version installed, this worked perfectly now, no errors and the binary executes!

**Comment by Midi-In** [comment]
Closed by accident without thinking much - I still would love to see this precompiled and ready to install/update straight from the package manager

**Comment by xeffyr** [comment]
Added in https://github.com/termux/termux-packages/commit/a1bbdb4f9bc8ffc06eae7766b5cbcd02fb2adbb2. Soon it will be available for the installation.
