### ISSUE TITLE
package request: zlib seq stat

### ISSUE THREAD

**Issue by zoobab** [termux/termux-packages#62]
i am tryng to compile openwrt with termux, unfortunately i cannot find packages for zlib seq and stat.

**Comment by zoobab** [comment]
apt install coreutils solves seq and stat. So zlib is the only one still missing.

**Comment by fornwall** [comment]
The zlib library comes pre-installed on Android (in /system/lib(64)), so no need to install that.

The `ndk-sysroot` package (which `gcc` depends on) provides the `zlib.h` header file.

**Comment by fornwall** [comment]
Closing this issue - just re-open if there is anything more you need here!

**Comment by zoobab** [comment]
I will make an article on how to compile openwrt with termux, but the zlib is not found even if I install ndk-sysroot. Will investigate more.

**Comment by fornwall** [comment]
Do you have more information about how to reproduce this?

I can compile a simple C program linking against zlib using:

    apt install gcc
    curl -o zpipe.c http://www.zlib.net/zpipe.c
    gcc -lz zpipe.c

**Comment by zoobab** [comment]
I think openwrt requires a static version of zlib.a, like in debian:

https://packages.debian.org/wheezy/amd64/zlib1g-dev/filelist
/usr/lib/x86_64-linux-gnu/libz.a

The error message is:

Checking 'python'... ok.
Checking 'svn'... ok.
Checking 'git'... ok.
Checking 'file'... ok.
Checking 'openssl'... ok.
Checking 'ldconfig-stub'... ok.

Build dependency: Please install a static zlib. (Missing libz.a or zlib.h)
Prerequisite check failed. Use FORCE=1 to override.
make: *** [staging_dir/host/.prereq-build] Error 1

**Comment by fornwall** [comment]
Distributing static libaries are currently out of scope for Termux for now so closing this issue.

If you are still working on this and need zlib.a, I think a static zlib should be buildable without much problems inside Termux itself!
