### ISSUE TITLE
failed install golang package

### ISSUE THREAD

**Issue by wahyu6070** [termux/termux-packages#6200]
apt update
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Get:6 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable Release [8255 B]
Fetched 19.8 kB in 6s (3209 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
~ $ apt upgradr
E: Invalid operation upgradr
~ $ apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
~ $ apt install golang
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  golang
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 52.7 MB of archives.
After this operation, 357 MB of additional disk space will be used.
Err:1 https://termux.org/packages stable/main aarch64 golang aarch64 2:1.15.6-3
  Could not connect to termux.org:443 (104.31.90.132), connection timed out Could not connect to termux.org:443 (104.31.91.132), connection timed out Could not connect to termux.org:443 (172.67.193.33), connection timed out
E: Failed to fetch https://termux.org/packages/aarch64/golang_2:1.15.6-3_aarch64.deb  Could not connect to termux.org:443 (104.31.90.132), connection timed out Could not connect to termux.org:443 (104.31.91.132), connection timed out Could not connect to termux.org:443 (172.67.193.33), connection timed out
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
~ $

device : asus zenfone max pro m1
android version : 9.0
arch : arm64
clang : installed

**Comment by kcubeterm** [comment]
Can't reproduce.
Problems lies in your network. Make sure you have stable network.
