### ISSUE TITLE
hydra cannot be compiled in Termux

### ISSUE THREAD

**Issue by 26chk** [termux/termux-packages#6204]
installations running on Android 9

**Problem description**

hydra.c:1109:25: note: include the header <strings.h> or explicitly provide a declaration for 'index'
1 warning generated.
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-339d88.o: in function `fill_mem':
/data/data/com.termux/files/home/thc-hydra/hydra.c:1109: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-339d88.o: in function `hydra_increase_fail_count':
/data/data/com.termux/files/home/thc-hydra/hydra.c:1472: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/thc-hydra/hydra.c:1472: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-339d88.o: in function `process_proxy_line':
/data/data/com.termux/files/home/thc-hydra/hydra.c:2025: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/thc-hydra/hydra.c:2029: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-339d88.o:/data/data/com.termux/files/home/thc-hydra/hydra.c:2037: more undefined references to `index' follow
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:66: hydra] Error 1

**Steps to reproduce**

git clone --depth=1 https://github.com/vanhauser-thc/thc-hydra

cd thc-hydra

./configure

make

make install

**Comment by kcubeterm** [comment]
Need extra treatment. See https://github.com/termux/termux-packages/blob/master/packages/hydra/build.sh 

Or you can build hydra on your device using build system. [Wiki](https://github.com/termux/termux-packages/wiki/Building-packages)


```sh
pkg in build-essential ninja git

git clone https://github.com/termux/termux-packages

cd termux-packges

./build-package.sh hydra
```
After successful build, debfile will be available in `debs` directory and hydra available in your system.
