### ISSUE TITLE
Unable to locate package metasploit

### ISSUE THREAD

**Issue by Dj2o** [termux/termux-packages#6206]
What closed this package?
![Screenshot_20210101-201931](https://user-images.githubusercontent.com/64633599/103440378-1c9c0580-4c6f-11eb-81c8-363575bce8a8.png)

**Comment by kcubeterm** [comment]
Package policy has now changed, we no longer provide/maintain such package which is supposed to Phishing and pentesting. 

As a result metasploit no longer part of termux official packages. 

You are free to install it from third party.

**Comment by Grimler91** [comment]
Related commit: https://github.com/termux/unstable-packages/commit/a0bbde10d152190783c07e1719a4bc6a5ebf2109
