### ISSUE TITLE
[Package request] NeoMutt

### ISSUE THREAD

**Issue by FreddieOliveira** [termux/termux-packages#6207]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

## Package description

NeoMutt is a fork of Mutt. It was created when Richard Russon (@FlatCap) took all the old Mutt patches, sorted through them, fixed them up and documented them.

## Link to home page and sources

1. Home page: https://neomutt.org
2. Source code: https://github.com/neomutt/neomutt

## Additional information

Some patches are needed to be applied so it can execute correctly. Download the patches and execute the following steps:

```
git clone https://github.com/neomutt/neomutt
cd neomutt
patch autosetup/autosetup-config.guess autosetup-config.guess.patch
patch docs/config.c config.c.patch
patch mutt/file.c file.c.patch
patch autosetup/jimsh0.c jimsh0.c.patch
patch mutt_config.c mutt_config.c.patch
patch test/file/mutt_file_mkstemp_full.c mutt_file_mkstemp_full.c.patch
patch muttlib.c muttlib.c.patch
patch contrib/smime_keys smime_keys.patch
./configure --disable-gpgme --disable-idn --zstd --with-mailpath=$PREFIX/var/mail --sasl --ssl --gdbm --gss --prefix=$PREFIX
make -j8
make install
```

These are the libs it depends upon:

```
libgssapi_krb5.so.2
libkrb5.so.3
libk5crypto.so.3
libcom_err.so.3
libzstd.so.1
libgdbm.so.6
libz.so.1
libssl.so.1.1
libcrypto.so.1.1
libncursesw.so.6
libsasl2.so.3
libiconv.so
libdl.so
libc.so
```

[This](https://github.com/termux/termux-packages/files/5759631/files.txt) is the list of files added to the system after installed.

### Patches

[autosetup-config.guess.patch.txt](https://github.com/termux/termux-packages/files/5759615/autosetup-config.guess.patch.txt)
[config.c.patch.txt](https://github.com/termux/termux-packages/files/5759616/config.c.patch.txt)
[file.c.patch.txt](https://github.com/termux/termux-packages/files/5759617/file.c.patch.txt)
[jimsh0.c.patch.txt](https://github.com/termux/termux-packages/files/5759618/jimsh0.c.patch.txt)
[mutt_config.c.patch.txt](https://github.com/termux/termux-packages/files/5759619/mutt_config.c.patch.txt)
[mutt_file_mkstemp_full.c.patch.txt](https://github.com/termux/termux-packages/files/5759620/mutt_file_mkstemp_full.c.patch.txt)
[muttlib.c.patch.txt](https://github.com/termux/termux-packages/files/5759621/muttlib.c.patch.txt)
[smime_keys.patch.txt](https://github.com/termux/termux-packages/files/5759622/smime_keys.patch.txt)

**Comment by flatcap** [comment]
> all the old Mutt patches...

Once tidied, the important thing was to merge as many as possible.
If more than one packager was using a patch, it made sense to merge it (reducing their workload).

If this Package Request is granted, then I'll happily merge the `#ifdef __ANDROID__` changes.

I'll discuss the `/tmp` changes with the other devs.
Some other packagers have suggested similar changes, e.g. `/var/tmp`
No promises, but perhaps it could become a `configure` option.

---

btw, I think there are too many `/`s at the beginning of `/data/...` in `config.c.patch.txt`
```diff
-** used.  Failing that, then "\fC/tmp\fP" is used.
+** used.  Failing that, then "\fC//data/data/com.termux/files/usr/tmp/\fP" is used.
```

**Comment by xeffyr** [comment]
Added in https://github.com/termux/termux-packages/commit/763f9ebf7e070e999560a175060de76fee9d0a1d. Soon it will be available for the installation.

**Comment by FreddieOliveira** [comment]
Hey @flatcap, nice to see you here! When porting packages to Termux the majority of patches are fixing hardcoded paths, eg. in shebang. Instructing people to use env vars like $TMPDIR, $HOME, etc or adding a configure option for that would definitely help.

The other type of patches are disabling features not present in Android or adapting them. That's the `#ifdef __ANDROID__` part.

> btw, I think there are too many /s at the beginning of /data/... in config.c.patch.txt

Oops, you're right.

Happy new year, btw @flatcap @xeffyr
