### ISSUE TITLE
neovim + luajit

### ISSUE THREAD

**Issue by shadmansaleh** [termux/termux-packages#6212]
#### can neovim be compiled with luajit insted of lua5.3?

Acording to [Neovim FAQ](https://github.com/neovim/neovim/wiki/FAQ#why-embed-lua-instead-of-x)

I beleave neovim's standard is lua5.1 . And they prefare luajit . lua 5.3 and 5.1 aren't fully compatable . that causes some stuff wretten in lua break in termux version . Also I've seen some plugins use jit.os too . That absolutely cann't work without jit.

I donn't know if theres some problem in compiling with luajit . Both luajit and neovim are compiled for termux so it souldn't be an issue i think.

These 2 flags seems to be responsible .
```
-DPREFER_LUA=ON
-DLUA_INCLUDE_DIR=$TERMUX_PREFIX/include/lua5.3
```

**Comment by shadmansaleh** [comment]
Any comment on this anyone ??

**Comment by Grimler91** [comment]
Hi, please consider open a PR and we can see if simply adding those flags work, and you get a deb to test!

**Comment by shadmansaleh** [comment]
>Hi, please consider open a PR and we can see if simply adding those flags work, and you get a deb to test!

I actually currently donn't have access to a pc and I coouldn't get it it build neovim with current master on termux . That's why I thought it would have benn better if someone who could test it could make the changes . No matter I'll create a pr with relavent changes . Is it possible to extract the built deb from GithubCL?

**Comment by kcubeterm** [comment]
> I actually currently donn't have access to a pc and I coouldn't get

Hey, use cloudshell via web browser or by simply setup Google cloud SDK  in termux to access via termux.

**Comment by shadmansaleh** [comment]
>Hey, use cloudshell via web browser or by simply setup Google cloud SDK in termux to access via termux.

good idea . But can Google cloud SDK be installed in termux?

**Comment by kcubeterm** [comment]
> But can Google cloud SDK be installed in termux?

You need to manually download and setup SDK and you need python2.7 for that. For your convenience. 
https://gist.github.com/kcubeterm/7e2792366bd6e8c14064f7e2ac109cc7

**Comment by shadmansaleh** [comment]
>You have to manually download and setup SDK and you need python2.7 for that. For your convenience.
https://gist.github.com/kcubeterm/7e2792366bd6e8c14064f7e2ac109cc7

Thanks. I actually got an error installation 
`ERROR: (gcloud.components.update) The following components are unknown [anthoscli].`

But ssh works fine :)
