### ISSUE TITLE
How to connect to domain

### ISSUE THREAD

**Issue by bsde1234** [termux/termux-packages#6213]
I have a laravel app in termux with php, composer and mariadb. How to connect it to a domain?

**Comment by RossComputerGuy** [comment]
Look up registering a domain and how to connect an IP to it. Use your device's IP. I suggest making it so your device has a static IP address.

**Comment by bsde1234** [comment]
I have a domain with me and I know how to connect with domain from a hosting provider. But since it is localhost how to configuration esp. `a name` and `cname`. Link to docs will be usefull

**Comment by RossComputerGuy** [comment]
Get your device's public IP address and use that to point your domain to on your registrar's CPanel.

**Comment by xeffyr** [comment]
Locking issue as off-topic. There lots of information on the Internet what are `A` and `CNAME` records, how to configure them, etc.

In case of Termux, the main problem would be acquiring of the public IP.
