### ISSUE TITLE
[Question] How to make cava work with VLC?

### ISSUE THREAD

**Issue by FreddieOliveira** [termux/termux-packages#6216]
@Neo-Oli Is there any way to make C.A.V.A. work with VLC player, since its my default music player?

Currently I can only make it work when playing songs with cmus.

**Comment by Neo-Oli** [comment]
@FreddieOliveira I just tested it and it seems to work with VLC by default (now?). But it needs to be the VLC player installed by Termux. If you mean the VLC Player Android app, then it can't work.

**Comment by xtkoba** [comment]
Closing as answered.
