### ISSUE TITLE
failed install golang package

### ISSUE THREAD

**Issue by wahyu6070** [termux/termux-packages#6218]
ping google.com
PING google.com (216.239.38.120) 56(84) bytes of data.
64 bytes from any-in-2678.1e100.net (216.239.38.120): icmp_seq=1 ttl=115 time=24.4 ms
64 bytes from any-in-2678.1e100.net (216.239.38.120): icmp_seq=2 ttl=115 time=144 ms
64 bytes from any-in-2678.1e100.net (216.239.38.120): icmp_seq=3 ttl=115 time=30.3 ms
64 bytes from any-in-2678.1e100.net (216.239.38.120): icmp_seq=4 ttl=115 time=26.3 ms
64 bytes from any-in-2678.1e100.net (216.239.38.120): icmp_seq=5 ttl=115 time=34.8 ms
^Z
[1]+  Stopped                 ping google.com
~ $ apt install golang
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  binutils clang libffi libllvm ndk-sysroot
The following NEW packages will be installed:
  binutils clang golang libffi libllvm ndk-sysroot
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 52.7 MB/93.3 MB of archives.
After this operation, 605 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 golang aarch64 2:1.15.6-3 [52.7 MB]
53% [1 golang 1831 kB/52.7 MB 3%]               130 kB/s 6min 30s
Err:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 golang aarch64 2:1.15.6-3
  Error reading from server - read (5: I/O error) [IP: 44.241.119.237 443]
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/golang_2:1.15.6-3_aarch64.deb  Error reading from server - read (5: I/O error) [IP: 44.241.119.237 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by xeffyr** [comment]
Switch to a different host with `termux-change-repo`.

That's an issue with https://dl.bintray.com which is not a subject for fixing - we don't own or manage it and have to use the provided service quality, considering that we receive it for free.
