### ISSUE TITLE
top process monitor: key commands currently require ENTER

### ISSUE THREAD

**Issue by ronnac** [termux/termux-packages#6219]
**Problem description**

I am aware that top is a wrapper for /system/bin/top.
I wonder if this bug is related to the wrapper.
Description: after launching top one can use the cursor keys to navigate/change sort order as well as the keys q to quit and r to reverse the sort order.
These key commands do currently work, but only if one presses the Enter key afterwards. This is cumbersome.

**Steps to reproduce**

Run the top command. Press q then Enter. Top will quit.

**Expected behavior**

Top should quit immediately after pressing q.

**Additional information**

```

```

**Comment by Grimler91** [comment]
What's your output of `termux-info`?

I can reproduce the behaviour on my phone running Lineage OS 17.1, both when run from termux and when run from an `adb shell`. Since I get the same behaviour from `adb` it cannot be due to our wrapper script.

**Comment by ronnac** [comment]
Indeed! Thanks!
