### ISSUE TITLE
Cannot install any package

### ISSUE THREAD

**Issue by buntalol** [termux/termux-packages#6227]
![1609951789019](https://user-images.githubusercontent.com/54007202/103796630-c13f8e00-5047-11eb-937d-876b93b8d06e.jpg)
This happens when i try to apt update or anything like that. The same thing happens when i try installing anything using pkg install.

**Comment by xeffyr** [comment]
Something is wrong with your installation. [Back up](https://wiki.termux.com/wiki/Backing_up_Termux) $HOME and/or $PREFIX, then reset application data of Termux.
