### ISSUE TITLE
Can't install package!

### ISSUE THREAD

**Issue by Gameye98** [termux/termux-packages#6232]
![Screenshot_20210107_173255](https://user-images.githubusercontent.com/21236430/103870030-82c0d680-510e-11eb-9335-fe18d627cfdd.jpg)

I try to install ghostscript and texlive, its show error message which i never had before...

I've tried to update and --fix-missing
$ apt-get update --fix-missing

Still didn't solve the issue...

**Comment by xeffyr** [comment]
Switch to a different host with `termux-change-repo`.

That's an issue with https://dl.bintray.com which is not a subject for fixing - we don't own or manage it and have to use the provided service quality, considering that we receive it for free.
