### ISSUE TITLE
Cant install pygame

### ISSUE THREAD

**Issue by VladyslavRehan** [termux/termux-packages#6233]
Xiaomi mi a 1 (android 9) (root)
I know pygame not working without gui, im planning use kyvi to compile app to apk and imstall it...
Pip insntall pygame dont work, help
After this error i try to install numpy, installed successful, i think its problem not with pip. Sorry for my English...
Look:

~ $ cd
~ $ pip install pygame
Collecting pygame
  Using cached pygame-2.0.1.tar.gz (5.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-_ekvjb2b/pygame_d77a59731fcb4a689c04446f91de14b3/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-_ekvjb2b/pygame_d77a59731fcb4a689c04446f91de14b3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-2hgwf53e
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-_ekvjb2b/pygame_d77a59731fcb4a689c04446f91de14b3/
    Complete output (29 lines):

    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...

    /data/data/com.termux/files/usr/bin/sh: 1: sdl2-config: not found
    /data/data/com.termux/files/usr/bin/sh: 1: sdl2-config: not found
    /data/data/com.termux/files/usr/bin/sh: 1: sdl2-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-_ekvjb2b/pygame_d77a59731fcb4a689c04446f91de14b3/setup.py", line 318, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "/data/data/com.termux/files/usr/tmp/pip-install-_ekvjb2b/pygame_d77a59731fcb4a689c04446f91de14b3/buildconfig/config.py", line 221, in main
        deps = CFG.main(**kwds)
      File "/data/data/com.termux/files/usr/tmp/pip-install-_ekvjb2b/pygame_d77a59731fcb4a689c04446f91de14b3/buildconfig/config_unix.py", line 194, in main
        DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
      File "/data/data/com.termux/files/usr/tmp/pip-install-_ekvjb2b/pygame_d77a59731fcb4a689c04446f91de14b3/buildconfig/config_unix.py", line 39, in __init__
        self.ver = config[0].strip()
    IndexError: list index out of range

    Hunting dependencies...

    ---
    For help with compilation see:
        https://www.pygame.org/wiki/Compilation
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
~ $

**Comment by Grimler91** [comment]
`/data/data/com.termux/files/usr/bin/sh: 1: sdl2-config: not found`, so install sdl2. Lots of sdl stuff is listed in the list of dependencies: https://github.com/pygame/pygame#Dependencies.

**Comment by sweetman135** [comment]
Why doesn't Python install in my thermox?

**Comment by VladyslavRehan** [comment]
> Why doesn't Python install in my thermox?

Send error
