### ISSUE TITLE
missing dependencies for pygame

### ISSUE THREAD

**Issue by VladyslavRehan** [termux/termux-packages#6234]
xiaomi mi a1 android 9 root

Missing dependencies                                                                                                  Hunting dependencies...                                   
SDL     : found 2.0.10
FONT    : not found

IMAGE   : found                                            
MIXER   : found                                            
PNG     : found                                            
JPEG    : found                                            
SCRAP   : found                                            
PORTMIDI: not found

question: how install portmidi and font, help pls.
(sorry for troublemaking and my English)

**Comment by xeffyr** [comment]
https://www.reddit.com/r/termux/comments/ks6xi4/pygame_on_termux/giek6v4?utm_source=share&utm_medium=web2x&context=3
