### ISSUE TITLE
pyaudio installing

### ISSUE THREAD

**Issue by VladyslavRehan** [termux/termux-packages#6235]
xiaomi mi a 1 android 9 root
clang is already installed and updated
help

~ $ pip install pyaudio
Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Using legacy 'setup.py install' for pyaudio, since package 'wheel' is not installed.
Installing collected packages: pyaudio
    Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-oj59i_m3/pyaudio_f3d16bc818d1410f99d880e0eeef6c6d/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-oj59i_m3/pyaudio_f3d16bc818d1410f99d880e0eeef6c6d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-0ke6kogc/install-record.txt --single-version-externally-managed --compile --install-headers /data/data/com.termux/files/usr/include/python3.9/pyaudio
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-oj59i_m3/pyaudio_f3d16bc818d1410f99d880e0eeef6c6d/
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.9
    copying src/pyaudio.py -> build/lib.linux-aarch64-3.9
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-aarch64-3.9
    creating build/temp.linux-aarch64-3.9/src
    aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.9 -c src/_portaudiomodule.c -o build/temp.linux-aarch64-3.9/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found
    #include "portaudio.h"
             ^~~~~~~~~~~~~
    1 error generated.
    error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-oj59i_m3/pyaudio_f3d16bc818d1410f99d880e0eeef6c6d/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-oj59i_m3/pyaudio_f3d16bc818d1410f99d880e0eeef6c6d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-0ke6kogc/install-record.txt --single-version-externally-managed --compile --install-headers /data/data/com.termux/files/usr/include/python3.9/pyaudio Check the logs for full command output.
~ $

**Comment by xeffyr** [comment]
Get a portaudio from https://github.com/its-pointless/its-pointless.github.io

**Comment by VladyslavRehan** [comment]
i seem to have checked all the links there but found no answers ...

**Comment by xeffyr** [comment]
> checked all the links there but found no answers

I don't think so... https://github.com/its-pointless/its-pointless.github.io (readme) --> https://github.com/its-pointless/gcc_termux (again, read "readme"):
```
From now on im using apt for updates
add 
deb https://its-pointless.github.io/files/24  termux extras
(use https://its-pointless.github.io/files/21 if you are still using android 5 or 6)
file with .list suffix in $PREFIX/etc/apt/sources.list.d/
gpg key is https://its-pointless.github.io/pointless.gpg
if not installed install gnupg
apt-get install gnupg
apt-key add pointless.gpg will add the key to apt
apt-get update

or use https://its-pointless.github.io/setup-pointless-repo.sh
```
after setting up repo - `pkg in portaudio`.

Or just
```
curl -LO https://github.com/its-pointless/its-pointless.github.io/raw/master/files/24/dists/termux/extras/binary-aarch64/portaudio_20180920-1_aarch64.deb
apt install ./portaudio_20180920-1_aarch64.deb
```

**Comment by GiorgosXou** [comment]
https://stackoverflow.com/a/69114514/11465149
