### ISSUE TITLE
Termux asking for 2nd password 

### ISSUE THREAD

**Issue by CRIZEEE** [termux/termux-packages#6236]
When trying to ssh from android phone with termux to kali linux on raspberry pi 3b+ after asking me for a password of my kali user, termux is asking for another password for a username i never seen before. So i cant connect. The ssh is working well from a pc to rpi with putty, but i cant connect from the phone.
Galaxy A8, android v9.
Here's a screenshot of termux - i tried 3 different passwords i could think of (kali pass, root pass, phone pass) - no success. 
![20210107_184255](https://user-images.githubusercontent.com/77116463/103919058-44301980-5118-11eb-9f6c-b68f48527488.jpg)

Please help.
If any other details of my system are needed i will happily provide them.

**Comment by xeffyr** [comment]
You have entered a wrong password.

**Comment by xeffyr** [comment]
It also seems you have misplaced arguments. OpenSSH accepts arguments in the following format: `ssh [options] user@host`.

In your case, it should be: `ssh -J kali@192.168.0.104:22 192.168.0.104`, however there are few issues:
* Why doing `-J kali@192.168.0.104:22` ?
* `192.168.0.104` probably should be `kali@192.168.0.104`, otherwise Termux user name will be used (beginning with `u0`).

**Comment by CRIZEEE** [comment]
Thanks.
Xeffyr - when i try to login without -J or with it on the start, it gives a syntax error telling me to do differently. Anyway i did manage to solve it by adding this termux user to my kali and now its working, but i must say i still dont understand why i cant login directly to the kali user.. the app is insisting to log in with this random looking username.

**Comment by xeffyr** [comment]
>  the app is insisting to log in with this random looking username.

`ssh kali@192.168.0.104`. If you won't specify user, then actual user would be `$(id -un)`.

**Comment by asyrafasyraf** [comment]
Hack

**Comment by asyrafasyraf** [comment]
Hack
