### ISSUE TITLE
portmidi porttime

### ISSUE THREAD

**Issue by VladyslavRehan** [termux/termux-packages#6237]
Please add a PORTMIDI and PORTTIME packges. They are needed for installation pygame python library... Thank you in advance
(And yes, I did not read the rules of new package request...)

- [ ] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by VladyslavRehan** [comment]
https://github.com/philandstuff/portmidi

**Comment by xeffyr** [comment]
> They are needed for installation pygame python library... 

**Not needed!!!** And can't be added anyway - Termux doesn't support ALSA.

**Comment by xtkoba** [comment]
Packaged as `portmidi` with null backend.
