### ISSUE TITLE
export to PATH  does not work correctly

### ISSUE THREAD

**Issue by VladyslavRehan** [termux/termux-packages#6238]
I have my bash script in /data/data/com.termux/files/home/.scripts folder (yes, i was do for him chmod +x),
i want to run it from any folder in termux ... for that i do: " export PATH=$PATH:/home/user/scripts " and all works good, the system finds my script when I write its name and pass the parameters. But after restarting the termux, when i want to run my script again i get an error :
~ $ vncrestart 1
vncrestart: command not found

script:
#!/bin/bash

count=1                                              
for param in $@                                      
do
        echo "Loop #$count"
        echo "VNC server #$param restarting... "
        vncserver -kill :$param
        vncserver :$param -localhost
        echo "Restarted: $param"
        echo " "
        count=$(( $count+1 ))
done

(This script using "for" cycle killing vnc servers in $@ parameters and start they again, useful for me)

**Comment by Hax4us** [comment]
its intended behaviour & use `export` in your `bash.bashrc` file permanent solution

**Comment by VladyslavRehan** [comment]
> its intended behaviour & use `export` in your `bash.bashrc` file for permanent solution

THANKS FOR YOU,  ITS WORKS!
