### ISSUE TITLE
update pakage: update darkhttpd to v1.13

### ISSUE THREAD

**Issue by inet56** [termux/termux-packages#6239]
darkhttpd now sends viewport meta tag on directory listing, which make it more usable on mobile devices.

**Comment by inet56** [comment]
On Jan 7, I asked Emil Mikulic, darkhttpd's maintainer, to make a new release via email. On Jan 13, he replied -

> I should. Last release was in like 2016. I've been a bit short on time this past week but I'll get to it...

**Comment by inet56** [comment]
darkhttpd 1.13 has been released https://github.com/emikulic/darkhttpd/releases/tag/v1.13

**Comment by kcubeterm** [comment]
5e6023b
