### ISSUE TITLE
Pyzmq fails to install with libzmq available from arm repo

### ISSUE THREAD

**Issue by daviscyd** [termux/termux-packages#6241]
**Problem description**
Pyzmq install (`pip install pyzmq`) and/or build using termux libzmq from arm repo fails to use the installed library and instead attempts to build libzmq from bundled sources.  The libzmq build fails because the sources are not patched for Android use.  The installation fails because the test build and run  with the termux installed libzmq fails with the following:

`Error running version detection script:  "build/temp.linux-armv8l-3.9/scratch/vers": error: Android 5.0 and later only support position-independent executables (-fPIE).`

**Steps to reproduce**
1. Install all packages necessary for python package install (python, clang, etc)
2. Install libzmq and libzmq-static (as troubleshooting step) packages: `pkg install libzmq libzmq-static`
3. Attempt to install pyzma: `pip install pyzma`

**Expected behavior**
Python's pip should find and use the installed library 

**Additional information**
The libzmq available in the aarch64 repo works; the pyzmq is successful once it's installed (see [this open issue](https://github.com/zeromq/pyzmq/issues/1469) in the zeromq repo and [this thread](https://www.reddit.com/r/termux/comments/kscgfo/jupyter_install_issue_with_clang/) on the reddit forum)

**termux info**
```
~ $ termux-info
Packages CPU architecture:  
arm
Subscribed repositories:
# sources.list deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list) deb https://dl.bintray.com/grimler/game-packages-24 games stable               # science-repo (sources.list.d/science.list) deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.14.87+ #1 SMP PREEMPT Sat Dec 12 17:46:56 UTC 2020 armv8l Android
Device manufacturer:
Amazon
Device model:
KFONWI
```

**Comment by daviscyd** [comment]
UPDATE: I built a working libzmq on-device for arm; I can upload it and necessary files

**Comment by Grimler91** [comment]
@daviscyd how did you make it work, do you have a patch to share?

**Comment by bkt92** [comment]
@daviscyd so this is the problem with libzmq on termux, can you share the working library with me, I am using the same device Amazon fire 10.

**Comment by daviscyd** [comment]
@Grimler I added `-DZMQ_HAVE_ANDROID` to `CFLAGS` and `CPPFLAGS` and I added `&& !defined ZMQ_HAVE_ANDROID` to the configure script before the `<sys/types.h>` include (although that may not be needed)

I don't have a patch yet; I'd need to set up my device to create patches for termux which will take time.  In the meantime is there a quickstart link I could reference (for making termux patches)?  Alternatively I could upload a tarball of the build dir...which I still have.

**Comment by daviscyd** [comment]
@bkt92 
> @daviscyd so this is the problem with libzmq on termux, can you share the working library with me, I am using the same device Amazon fire 10.

[arm-libzmq.tar.gz](https://github.com/termux/termux-packages/files/5796533/arm-libzmq.tar.gz)

**Comment by landfillbaby** [comment]
i'm pretty sure the problem is that libzmq's build setup is based entirely on `$host_os` and not `$target_os`

**Comment by bkt92** [comment]
> @bkt92
> 
> > @daviscyd so this is the problem with libzmq on termux, can you share the working library with me, I am using the same device Amazon fire 10.
> 
> [arm-libzmq.tar.gz](https://github.com/termux/termux-packages/files/5796533/arm-libzmq.tar.gz)

Hey how to use it ? I am using "python setup.py configure --zmq=../.arm-libzmq"

But still failed: 

```
"Error running version detection script:
"build/temp.linux-armv8l-3.9/scratch/vers": error: Android 5.0 and later only support position-independent executables (-fPIE).
error: Error running version detection script:
"build/temp.linux-armv8l-3.9/scratch/vers": error: Android 5.0 and later only support position-independent executables (-fPIE).
```

Thank you !

**Comment by daviscyd** [comment]
@bkt92 Not sure what you're doing; after I built/installed libzmq on-device I was able to install jupyter by running `pip install notebook`

**Comment by bkt92** [comment]
I try two method but both doesn't working. 

From the library that you sent me I replace the old version of libzmq by copy it to the lib and include folder of termux and run the "pip install pyzmq" but it doesn't work. 

So next I try to build the pyzmq manually and point to the libzmq library manually using the guide from [zeromq](http://wiki.zeromq.org/bindings:python) but it also doesn't work seem like it still can not detect the library. 

I think about may I need to build the libzmq from source manually by myself

**Comment by xeffyr** [comment]
Provided `arm-libzmq.tar.gz` doesn't have pkgconfig files. That's why it can't be found even if installed. You need to rebuild it from scratch.

**Comment by bkt92** [comment]
> Provided `arm-libzmq.tar.gz` doesn't have pkgconfig file (`lib/pkgconfig/libzmq.pc`). That's why it can't be found even if installed. You need to rebuild it from scratch.

Can you help me how to build it I am stuck at _**./configuration**_  step, seem like autobuilt tool can not detect the target and generate the configuration file.

**Comment by daviscyd** [comment]
If you can wait until tomorrow I'll try re-running the install to an alt location, tarball and upload.

**Comment by bkt92** [comment]
> If you can wait until tomorrow I'll try re-running the install to an alt location, tarball and upload.

Thak you.

**Comment by daviscyd** [comment]
@bkt92 
./configure --prefix=/data/data/com.termux/files/home/.arm-libzmq
make install
tar -czf arm-libzmq-updated.tar.gz .arm-libzmq/
[arm-libzmq-updated.tar.gz](https://github.com/termux/termux-packages/files/5808418/arm-libzmq-updated.tar.gz)

**Comment by bkt92** [comment]
> @bkt92 
> ```
> ./configure --prefix=/data/data/com.termux/files/home/.arm-libzmq
> make install
> tar -czf arm-libzmq-updated.tar.gz .arm-libzmq/
> ```
> [arm-libzmq-updated.tar.gz](https://github.com/termux/termux-packages/files/5808418/arm-libzmq-updated.tar.gz)
> 

I give up, still not working, try many method even successfully build the libzmq to the usr folder it still not work.  Try install cython and manually successfully build pyzmq but can not import zmq (other error appear). 

Thank you for your help.

**Comment by daviscyd** [comment]
@bkt92 

> Try install cython and manually successfully build pyzmq but can not import zmq (other error appear).

Is the error related to `tipc`?

**Comment by bkt92** [comment]
> @bkt92
> 
> > Try install cython and manually successfully build pyzmq but can not import zmq (other error appear).
> 
> Is the error related to `tipc`?

something related to zmq_constants.h. I try to reproduce the error but fail now, and return to the old error:
"strlcpy (char *dest_, const char *src_, const size_t dest_size_)"

Not detected libzmq, even that I successfully build it from the source, and with or without overwrite the built files with your library.

![image](https://user-images.githubusercontent.com/3808392/104792723-f2e7f000-57d1-11eb-89d9-07a067693eed.png)

**Comment by daviscyd** [comment]
@bkt92 
Are you using the updated tarball I posted?
Did you uninstall the libzmq package before unpacking the tarball?

**Comment by bkt92** [comment]
> @bkt92
> Are you using the updated tarball I posted?
> Did you uninstall the libzmq package before unpacking the tarball?

Yep, I use the tarball that you post "arm-libzmq-updated.tar.gz" and uninstall the pkg libzmq too but still fails. What version of pyzmq you are using? first time I use the 20.0.0, they have just updated to 21.0.1 but nothing work. Still the same error. 

I am using the latest version of termux with python 3.9.1.

**Comment by daviscyd** [comment]
`pyzmq               20.0.0`
Have you tried uninstalling everything (python, libzmq, etc) and re-installing?

**Comment by bkt92** [comment]
> `pyzmq               20.0.0`
> Have you tried uninstalling everything (python, libzmq, etc) and re-installing?

Not yet, but I give up now. May be in future I will try again but not now. Thank you.

**Comment by mamins1376** [comment]
Is it possible to include the mentioned `pkg-config` file in the repo build? Will it solve the `strlcpy` error too?

**Comment by xeffyr** [comment]
> Is it possible to include the mentioned pkg-config file in the repo build?

It is already present.

**Comment by yubrajbhoi** [comment]
I was having this exact problem (`-fPIE` error) and simply setting up `CC` as `clang` instead of `arm-linux-androideabi-clang` fixed it for me. My exact command was `CC=clang python setup.py build`.

I noticed this when I tried to compile `pyzmq/buildutils/vers.c`.

**Comment by commander-cb** [comment]
currently compiling pyzmq     17.x.zip   17.3.1   arm
i know for a fact i had -jupyter -this working b4. i.e
looks like that worked ... yeah  ,., maybe yeah..
working fix
just use the 17.x.zip   ---   working but broken zmq

have jupyter running.
i think i could build jupyter from source now, and it would compile in the 17 pyzmq ....so i tjink this could be almost fixed

**Comment by thunder-coding** [comment]
This issue seems to have been fixed. For people who are wondering what's the fix, give a look at https://github.com/zeromq/pyzmq/issues/1469#issuecomment-842664166
