### ISSUE TITLE
[Package request] logrotate

### ISSUE THREAD

**Issue by sndpwrites** [termux/termux-packages#6242]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

Handy tool for keeping log files with timestamp, and essentially maintain rotation of log files. Logrotate can be useful to maintain logs for a variety of applications. For my own purpose, I use node-red and am trying to integrate a feature where I can track user behaviour and put it in a log file. I don't want this log file to grow large size and take up space on the phone, so it would be nice to use logrotate and periodically clean older files. I'm quite sure a lot of developers will find this package useful, as it applies to file handling in linux in general.

**Link to home page and sources**
1. Home page: https://github.com/logrotate/logrotate
2. Source code: https://github.com/logrotate/logrotate

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by shoya0x00** [comment]
@xeffyr close this issue. logrotate has been added.
