### ISSUE TITLE
gcc error

### ISSUE THREAD

**Issue by bi2b** [termux/termux-packages#6244]
**Problem description**

**Steps to reproduce**

when i try run this command ```gcc source.c -o source -m32 -static``` i got this error message

**Expected behavior**

**Additional information**

```
/data/data/com.termux/files/usr/bin/ld: cannot find -ldl
/data/data/com.termux/files/usr/bin/ld: cannot find -lc
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by xeffyr** [comment]
`libc.a` and `libdl.a` are not available by default. You can get these from package `ndk-multilib` however static linking with libc is not recommended.
