### ISSUE TITLE
termux.org currently down

### ISSUE THREAD

**Issue by gskriptor** [termux/termux-packages#6245]
Hey termux.org is currently down. Will you be back up anytime soon?

**Comment by xeffyr** [comment]
That's your network down or ISP blocks access to CloudFlare.

I don't see any issue.

**Comment by RossComputerGuy** [comment]
I'm experiencing a 404 error when connecting so this isn't just 1 person having a problem.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by xeffyr** [comment]
@RossComputerGuy termux.org is a metahost and may not be accessed directly from web browser. It exposes a single entry point `termux.org/packages` as redirection point to Bintray.

**Comment by RossComputerGuy** [comment]
Ah, I was not aware of that.

**Comment by gskriptor** [comment]
I installed termux on a rooted android via f-droid and when I try to update it I get errors. It tells me something wicked has happened while trying to access the URL. Is there perhaps some special configuration or actions that need to be taken when using the f-droid version on a rooted device? If not and it is indeed my ISP blocking cloudflare would changing my DNS resolve the issue?

**Comment by xeffyr** [comment]
> If not and it is indeed my ISP blocking cloudflare would changing my DNS resolve the issue?

Use of different nameserver will help if that's a DNS issue only. Otherwise you should switch to another mirror, preferrably to `grimler.se`, through utility `termux-change-repo`. Or try a VPN.

**Comment by WMCB-Tech** [comment]
Ok, i have the same issue as well, i have 10mbps network but today when i do `pkg up` it says `http://termux.org` is bad

![Screenshot_2021-01-14-08-23-51-99.jpg](https://user-images.githubusercontent.com/65075766/104528313-e0d74780-5641-11eb-8f14-80bf90b27c89.jpg)

**Comment by WMCB-Tech** [comment]
Hmm, i just saw this issue yesterday and i running "pkg up" works fine with
no bad mirrors, but maybe it has something to do with my network connection
