### ISSUE TITLE
[Package request] Add extension dblink in postgresql-contrib

### ISSUE THREAD

**Issue by mdouchin** [termux/termux-packages#6247]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Dblink** provides a way to connect to external PostgreSQL databases from a running database. It would allow for example to query a foreign PostgreSQL database from the PostgreSQL server installed in Termux. This would allow to do some synchronization between the Android termux PostgreSQL and another central database.

It is generally included in the postgresql-contrib package. At present on Termux, the contrib package includes hstore, pgcrypto, pg_stat_statements (see: https://github.com/termux/termux-packages/issues/740#issuecomment-285121055 ) and perhaps more (cannot find more info via google)

**Link to home page and sources**
1. Home page: https://www.postgresql.org/docs/current/contrib-dblink-function.html
2. Source code: https://doxygen.postgresql.org/dblink_8c_source.html

**Additional information**
Have you compiled or tried to compile the package on device?
-> not yet

**Comment by mdouchin** [comment]
I found the way to list all the available extensions in the termux PostgreSQL instance:

```
gis=# select * from pg_available_extensions ORDER BY name;
             name             | default_version | installed_version |                                                       comment                                                       
------------------------------+-----------------+-------------------+---------------------------------------------------------------------------------------------------------------------
 address_standardizer         | 3.1.0           |                   | Used to parse an address into constituent elements. Generally used to support geocoding address normalization step.
 address_standardizer_data_us | 3.1.0           |                   | Address Standardizer US dataset example
 citext                       | 1.6             |                   | data type for case-insensitive character strings
 fuzzystrmatch                | 1.1             |                   | determine similarities and distance between strings
 hstore                       | 1.7             | 1.7               | data type for storing sets of (key, value) pairs
 pageinspect                  | 1.8             |                   | inspect the contents of database pages at a low level
 pg_freespacemap              | 1.2             |                   | examine the free space map (FSM)
 pg_stat_statements           | 1.8             |                   | track planning and execution statistics of all SQL statements executed
 pg_trgm                      | 1.5             |                   | text similarity measurement and index searching based on trigrams
 pgcrypto                     | 1.3             |                   | cryptographic functions
 pgrowlocks                   | 1.2             |                   | show row-level locking information
 plpgsql                      | 1.0             | 1.0               | PL/pgSQL procedural language
 postgis                      | 3.1.0           | 3.1.0             | PostGIS geometry and geography spatial types and functions
 postgis_tiger_geocoder       | 3.1.0           |                   | PostGIS tiger geocoder and reverse geocoder
 postgis_topology             | 3.1.0           |                   | PostGIS topology spatial types and functions
 unaccent                     | 1.1             |                   | text search dictionary that removes accents
 uuid-ossp                    | 1.1             |                   | generate universally unique identifiers (UUIDs)
(17 lignes)
```

NB: I already managed to build and install postgis extension, this is why it appears in the list above. See https://github.com/termux/termux-packages/issues/1041

**Comment by Grimler91** [comment]
Should be part of postgresql 13.1-1, which will be available in roughly 15 minutes. Please test and let me know if you encounter any problems!

**Comment by mdouchin** [comment]
Thanks a lot ! I did not now the change would be so easy. I will propose a PR next time :-)
It works like a charm

**Comment by mdouchin** [comment]
@Grimler91 I juste created a PR for the addition of postgres_fdw https://github.com/termux/termux-packages/pull/6249
