### ISSUE TITLE
cant give termux a root

### ISSUE THREAD

**Issue by VladyslavRehan** [termux/termux-packages#6250]
my phone (9 android) is rooted by magisk
i want make super screen recorder as system app
i need su command but...

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
~ $ tsu
Permission denied
~ $ su
Permission denied
~ $

**Comment by xeffyr** [comment]
Post here output of
```
bash -x $PREFIX/bin/tsu
```

**Comment by VladyslavRehan** [comment]
> Post here output of
> ```
> bash -x $PREFIX/bin/tsu
> ```

Thanks!
