### ISSUE TITLE
Package request: Xvfb

### ISSUE THREAD

**Issue by jcsantosx** [termux/termux-packages#626]
Hello.
It's possible to integrate the Xvfb in termux packages?
I'm trying to upload some pictures using selenium(works on ubuntu), but xvfb it's not available to install on termux, so wondering if it's because some hardware limitation, there's an alternative, or because make non sence to integrate that package?

Thanks ;)

**Comment by vishalbiswas** [comment]
Do you still need it?
I have an xorg-server package with Virtual Frame Buffer. I don't think it should be in the main repo.
Would buildscripts should be enough or do you need deb packages?

**Comment by xeffyr** [comment]
xorg-xvfb is available here: https://github.com/xeffyr/termux-extra-packages.
