### ISSUE TITLE
swift: some binaries do not work on Android 11

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#6261]
**Problem description**

See screenshot below:
![Screenshot_20210116-213728~2](https://user-images.githubusercontent.com/25881154/104821526-29128780-5845-11eb-8913-a055bca8d143.png)

Package installation was done on clean Termux. However tried `apt install --reinstall swift` to ensure that all files are installed correctly.

**Steps to reproduce**

Just run `swift-package --help` on device with latest Android 11. You can try same with other utilities, e.g. `swift-build`.

*Issue is not reproducible on device with Android 10 or lower.*

**Expected behavior**

It should output help info.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.110-g64f65a9c744d-ab6960647 #2 SMP PREEMPT Mon Nov 9 10:19:29 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 5
```
 ***

Still present after v5.3.3 package update.

**Comment by AlSufyaniT1** [comment]
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.110-g64f65a9c744d-ab6960647 #2 SMP PREEMPT Mon Nov 9 10:19:29 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel

**Comment by buttaface** [comment]
Sounds like executables written in Swift are having problems running in Android 11. What about the ones written purely in C++, do the commands `swift --version` and `swift-demangle --help` run fine? I don't use Android 11 but will probably have access to a device running it in the next couple months, so I'll look into this then.

**Comment by xeffyr** [comment]
It works:
![Screenshot_20210119-233135](https://user-images.githubusercontent.com/25881154/105095641-9ecd5c00-5aae-11eb-89c0-0fc835b20b47.png)

**Comment by buttaface** [comment]
Probably related to [tagged pointers in Android 11](https://forums.swift.org/t/swift-runtime-error-running-on-android-sdk-30-arm64-v8a/45457), will look into it soon.

**Comment by buttaface** [comment]
I am unable to reproduce the problem on two Android 11 devices I just tried it on, both running the latest March 1st security update. Is it possible this is specific to the Pixel and some other devices that run in a more secure mode or something?

**Comment by xeffyr** [comment]
I have the latest security updates and still can reproduce.

I don't think that this is specific to Pixel devices only. It just AOSP and Gapps. But it is possible that other ROMs have different levels of security hardening. For example Lineage OS provides a lower security level to "assist power users".

**Comment by buttaface** [comment]
Yeah, even with stock Android on three different Samsung models I tried it on, the first two worked fine and the third now shows me the error. So it appears this is either haphazardly enforced on different devices or doesn't always trigger or something. I finally have a device I can consistently reproduce it on, so I will look into it.

**Comment by buttaface** [comment]
This is related to tagged pointers, which only appears to be enabled on some Android 11 devices. If we put in some Swift workaround upstream, maybe this can be fixed eventually.

**Comment by dev-bz** [comment]
![Screenshot_2022-01-16-18-49-07-030_com.termux.jpg](https://user-images.githubusercontent.com/32380878/149656892-6a88923f-ce3c-47f5-ad03-8cb0e1998ffb.jpg)
when disable 'tagged pointers', it works.

**Comment by buttaface** [comment]
Yep, I have a patch in progress to work around the issue, apple/swift#40779.

**Comment by buttaface** [comment]
@dev-bz, how did you disable tagged pointers? @MonsterDruide1 has been trying to do the same.

**Comment by dev-bz** [comment]
> @dev-bz, how did you disable tagged pointers? @MonsterDruide1 has been trying to do the same.
here the code and setup
```c
extern int android_mallopt(int opcode, void *arg, unsigned int arg_size);
void __attribute__((constructor)) my_init_hook() {
	int tmp = 0; // M_HEAP_TAGGING_LEVEL_NONE
	android_mallopt(8 /*M_SET_HEAP_TAGGING_LEVEL*/, &tmp, sizeof(tmp));
}
```
```sh
gcc lib.c -Os --shared -o $HOME/libdtp.so
echo LD_PRELOAD=\$LD_PRELOAD:\$HOME/libdtp.so >> $PREFIX/etc/bash.bashrc
```

**Comment by dev-bz** [comment]
#6261

**Comment by xeffyr** [comment]
Similar code is used to disable tagged pointers in OpenJDK. The problem is that it works only for Android 11. On Android 12 it doesn't have effect.
