### ISSUE TITLE
Service scripts using svlogger won't have logging if package is installed before termux-services

### ISSUE THREAD

**Issue by novirium** [termux/termux-packages#6264]
**Problem description**
When a package includes a service script for `termux-services` to use, it includes a logger run script at `$PREFIX/var/service/{pkg_name}/log/run`. By default, this is a symlink to `$PREFIX/share/termux-services/svlogger` (generated [here](https://github.com/termux/termux-packages/blob/fd4e0850927a191da677abf0c4e209b6a72cf8ea/scripts/build/termux_step_install_service_scripts.sh#L34)). If this target doesn't exist (by not having installed `termux-services` yet) then installing the package fails to create the (dangling) symlink. 

In this situation, the service itself is still capable of starting, but won't have the attached logger.

There is a workaround at the moment - reinstalling the package providing the service script _after_ installing the `termux-services` package will correctly add the `log/run` symlink.

**Steps to reproduce**
An example with the `openssh` package, which provides the `sshd` service:

Make sure `openssh` and `termux-services` packages are not installed and remove remaining sshd service scripts and log files:
```
apt purge openssh termux-services
rm -r $PREFIX/var/services/sshd
rm -r $PREFIX/var/log/sv/sshd
```

Install the `openssh` package:
```
pkg install openssh
```

Confirm that the `$PREFIX/var/service/sshd/log/run` symlink has not been installed (though the directory has been created).

Install the `termux-services` package:
```
pkg install termux-services
```
Restart Termux, enable the `sshd` service and confirm that the logger isn't running:
```
sv-enable sshd
sv status sshd
ls -l $PREFIX/var/log/sv
```

At this point, we can demonstrate the workaround by reinstalling the `openssh` package (the output will mention adding a new version of a config file to `/data/data/com.termux/files/usr/var/service/sshd/log/run`):
```
pkg reinstall openssh
```

Confirm that the logger is now working:
```
sv status sshd
tail $PREFIX/var/log/sv/sshd/current
```

**Additional information**
I'm not exactly sure if there's anything that can be done about this other than documenting the workaround somewhere - it appears to be an effect of declaring the symlink as a config file in the package, though I haven't confirmed that (and it _should_ be a config file, in case someone wants to change the logger). I expect this will be encountered by others using `termux-services` though, as installing `openssh` is often one of the first things people set up in Termux.

**Comment by Grimler91** [comment]
Big thanks for investigating this. I have not had time to look into it further but we should fix this somehow..
