### ISSUE TITLE
ho i can open all storage folders

### ISSUE THREAD

**Issue by VladyslavRehan** [termux/termux-packages#6268]
i want make automatizations of mods or templates installng for apps. using bash scripts. its work. bit i cant see all my phone folders. how i can get in, for example,  "Abdroid" folder?

~ $ ls
HelloVim.py           Scripts  go      storage
Programing_Languages  Termux   pipwin  updateAllPyLibs.sh
~ $ cd storage/
~/storage $ ls
dcim  downloads  movies  music  pictures  shared
~/storage $

and what happens if im create some folder or file in "storage" folder and delete termux. created folders and files detedes too?

sorry for my english...

**Comment by xeffyr** [comment]
1.
```
cd ~/storage/shared
ls
```

2.
```
cd /storage/emulated/0
ls
```

**Comment by VladyslavRehan** [comment]
> 1.
> ```
> cd ~/storage/shared
> ls
> ```
> 
> 2.
> ```
> cd /storage/emulated/0
> ls
> ```

"shared" folder! Yeeeah!
