### ISSUE TITLE
Flutter on Termux

### ISSUE THREAD

**Issue by IshanKBG** [termux/termux-packages#6276]
How do I run Flutter on Termux
I am unable to run it
Please add support for Further Web

**Comment by kcubeterm** [comment]
#5798

**Comment by lycstar** [comment]
> How do I run Flutter on Termux
> 
> I am unable to run it
> 
> Please add support for Flutter Web 

After my test, flutter support compiling web on termux, because the main content of the flutter web SDK is dart, but the flutter_tools package need to be fix a lot in advance
