### ISSUE TITLE
Beep causes an Earthquake

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#628]
I guess that someone considered this a feature, but to me this is obviously a bug. Pressing Backspace or doing anything else that results in a terminal beep (e.g. pressing 'u' in vi when there is nothing to undo) causes a terrible shake of the entire terminal area, which is very irritating to the eyes and is totally unnecessary because keyboard presses are bound to sounds and vibrate events anyway (unless disabled) and so the beep event is clearly perceptible without shaking the whole universe...

So, please provide a way to disable this "new feature" (this behaviour started with the Termux upgrade a couple of days ago).

**Comment by natebass** [comment]
@tigran123 Disable the bell by putting ```set bell-style none``` in your ~/.inputrc

**Comment by sp4rkie** [comment]
- Terminal configuration
https://termux.com/configuration.html

**Comment by natebass** [comment]
@sp4rkie Setting ```bell-character=ignore``` in ~/.termux/termux.properties does nothing for me. @tigran123 neovim doesn't shake, at least not for me. You could try that if it's driving you mad. What I said earlier only works for bash.

**Comment by sp4rkie** [comment]
@natebass: strange. I had the 'vibrate' problem a few days ago. That's why I remember the solution to the problem:-) After issueing 'termux-reload-settings' command setting 'bell-character=ignore' worked as documented for me.

**Comment by natebass** [comment]
Maybe it is because I am using the beta version of Termux. Are a lot of people disabling it? I heard someone else complain in the gitter chat. I personally like it for the shell, but I could see how it is annoying in vim with large walls of text shaking at their foundation. 🏠 ⚠️

**Comment by tigran123** [comment]
setting `bell-character=ignore` in ~/.termux/termux.properties made no difference --- it still shakes and I didn't forget to exit termux and restart it again. Adding `set bell-style none` to ~/.inputrc solved the problem in bash, but it still shakes in vi. So, I added 'set visualbell' to ~/.vimrc and now it is ok in vi. 

But the problem still occurs in ipython3.

Also, isn't it silly to have to tweak all the applications? The proper fix is for Termux to NOT shake on beep. So, what is documented in Termux's manual should work and it doesn't, which means it is clearly a bug.

**Comment by tigran123** [comment]
Actually, running `termux-reload-settings -h` suggests that the configuration file is ~/.config/termux/termux.properties but the documentation at [https://termux.com/configuration.html](https://termux.com/configuration.html) points to ~/.termux/termux.properties.

But neither of them work.

**Comment by tigran123** [comment]
Just tested with today's upgrade of Termux --- the bug is still there: both ~/.termux/termux.properties and ~/.config/termux/termux.properties files are ignored.

**Comment by fornwall** [comment]
Thanks for the feedback! I'll remove the experimental shaking-on-bell behaviour in a minor v0.46 update which will be available as an update in a couple of hours (or within a day on F-Droid).

**Comment by Neo-Oli** [comment]
Aww... was I the only one who actually liked the screen shaking feature? It would be nice to have it as an extra configuration option.
```
back-key=escape
bell-character=vibrate
bell-earthquake=on
```

**Comment by fornwall** [comment]
@Neo-Oli Oh, someone liked it :)? Could perhaps add it back as an `shake` option, that is allowing something like

    bell-character=shake

or

    bell-character=vibrate+shake

**Comment by fornwall** [comment]
@tigran123 About termux.properties: The correct path is `~/.termux/termux.properties`, I've updated the help message from `termux-reload-settings` now!

**Comment by tigran123** [comment]
The reason I disliked it on mobile (but not so much on tablet) is because on the mobile the keys are so small (unless I attach external keyboard) and I keep hitting the wrong keys and often the result is shaking, so the overall experience is one of almost continuous shaking :)

But on tablet (it being Nexus 10) the keys are big enough to not cause this trouble.

**Comment by tigran123** [comment]
Thank you, I have tested on both Android 6 and 5.1.1 --- the latest version of Termux doesn't vibrate any more.
