### ISSUE TITLE
bug: history not saved when exiting via notification 

### ISSUE THREAD

**Issue by MathJoDE** [termux/termux-packages#6285]
When exiting termux via the "Exit" button in the notification, the commands of the current session are not written to `~/.bash_history`.

**Comment by xeffyr** [comment]
This is not a bug. History is only saved on graceful shell exit, i.e. when shell is properly closed like **command** `exit` or CTRL-D. Button "exit" is not equivalent of these, it closes application regardless of running processes which lately can be killed by Android OS.

**Comment by MathJoDE** [comment]
Ah, I see. Thanks :)
