### ISSUE TITLE
Starting kali problem

### ISSUE THREAD

**Issue by MK0809Q** [termux/termux-packages#6288]
In my termux there is showing proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/kali-fs, cwd = /root, $PATH=(null))
fatal error: see `proot --help`. This error please tell me what should i do.

**Comment by xeffyr** [comment]
That's an issue of your Kali installation.

**Comment by MK0809Q** [comment]
Whats the solution of this ?
Please let me know fast

**Comment by xeffyr** [comment]
@MK0809Q This issue tracker is only about official Termux packages. Kali is off-topic here.

Please ask for support in repo where you got the instructions on how to install it.
