### ISSUE TITLE
Pkg update Ffsend

### ISSUE THREAD

**Issue by selvodka** [termux/termux-packages#6292]
https://github.com/timvisee/ffsend/releases/tag/v0.2.68

**Comment by kcubeterm** [comment]
Not available anymore 
1bfb88cdd0f632eaef10ec99ad15012c29c0bac7

**Comment by xeffyr** [comment]
Does it changed the backend? If it doesn't use `send.firefox.com` anymore but some different public host, I can add it back.

**Comment by kcubeterm** [comment]
Yea, backened has changed. Should be add it.
Thanks @selvodka

**Comment by kcubeterm** [comment]
Restored, cbe115d thanks @xeffyr
