### ISSUE TITLE
Nethunter problem

### ISSUE THREAD

**Issue by MK0809Q** [termux/termux-packages#6293]
Please tell me how to solve this issue
![Screenshot_2021-01-22-19-12-36-952_com google android youtube](https://user-images.githubusercontent.com/77783470/105498353-189b5a80-5ce6-11eb-9c58-6cbfbfa08487.jpg)

**Comment by xeffyr** [comment]
Nethunter issues, as well as any other issues of side projects, should be reported to their authors.
