### ISSUE TITLE
V105 FC's on a clean install

### ISSUE THREAD

**Issue by gossbill** [termux/termux-packages#6294]
**Problem description**

After wiping storage in Settings or uninstalling/reinstalling, the app won't open.

**Steps to reproduce**

The app won't open after any of the following:
1. Wipe storage in Settings>Apps>Termux
2. Uninstalling Termux and reinstalling it
3. Uninstalling Termux, installing Termux v104 and verifying the app opens (but NOT running pkg update), updating to Termux v105.

Note: if I install v104 and run 'pkg update' then I can upgrade to v105 without problems.

**Expected behavior**

App opens and shows the motd.

**Additional information**

Cannot run termux-info because app FC's

I'm running:
Los 17.1 (Android 10) on OnePlus 3T
I downloaded Termux v105 (and v104) from F-droid

Logcat attached:
[210123-081958-v105-inst.zip](https://github.com/termux/termux-packages/files/5858753/210123-081958-v105-inst.zip)

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app/issues/1896
