### ISSUE TITLE
enter key deletes space

### ISSUE THREAD

**Issue by MathJoDE** [termux/termux-packages#6295]
**Problem description**

If the last typed character was a space, pressing enter key deletes this char.
This causes trouble when editing commands consisting of multiple words in the middle.

**Steps to reproduce** (as shown in above screen record)
1. Enter any command consisting of at least two words.
2. Use the arrow keys to navigate back over a space char
3. press backspace key (i.e. remove the space)
4. press enter key (i.e. add the space again)

**Expected behavior**
The command is executed as typed in, _including_ the space.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
ed/stable 1.17 aarch64 [upgradable from: 1.16-1]
findutils/stable 4.8.0 aarch64 [upgradable from: 4.7.0-2]
libsqlite/stable 3.34.0-1 aarch64 [upgradable from: 3.34.0]
nano/stable 5.5 aarch64 [upgradable from: 5.4]
Android version:
7.0
Kernel build information:
Linux localhost 4.1.18-gff26384 #1 SMP PREEMPT Wed Jun 13 04:00:06 CST 2018 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
HUAWEI VNS-L31
```

https://user-images.githubusercontent.com/59893632/105613543-781b6800-5dc3-11eb-8019-560b885e189a.mp4

**Comment by xeffyr** [comment]
What keyboard? SwiftKey?

**Comment by MathJoDE** [comment]
Oh, tbh I didn't thought of that cause yet. :sweat_smile:

**Comment by MathJoDE** [comment]
Yes, SwiftKey was at fault.
