### ISSUE TITLE
Backspace issue on xterm-kitty

### ISSUE THREAD

**Issue by 0Karakurt0** [termux/termux-packages#6296]
Added fix in https://github.com/termux/termux-packages/commit/9568028c655ed4e13a67274ea80ac4de2886437a.

_Originally posted by @xeffyr in https://github.com/termux/termux-packages/issues/1061#issuecomment-507052990_

$TERM is xterm-kitty
And here are backspace and Delete
`~ $ vtshowkeys
0177 127 0x7F Delete			^?	 

0177 127 0x7F Delete			^?	 

0033  27 0x1B Escape '^[' or '\e'
0133  91 0x5B ASCII '['
0063  51 0x33 ASCII '3'
0176 126 0x7E ASCII '~'

0033  27 0x1B Escape '^[' or '\e'
0133  91 0x5B ASCII '['
0063  51 0x33 ASCII '3'
0176 126 0x7E ASCII '~'`

**Comment by 0Karakurt0** [comment]
TERM=vt100 solves it through

**Comment by xeffyr** [comment]
Terminfo `xterm-kitty` should be available in the latest version of `ncurses` package.
