### ISSUE TITLE
Session shortcuts are not working

### ISSUE THREAD

**Issue by joseanoxp** [termux/termux-packages#6297]
**Problem description**

The shortcuts are not working on my termux, I already read the Wiki just how to define the shortcuts but they are not working.

**Steps to reproduce**

CTRL + T, CTRL + 1/2 and CTRL + N

**Expected behavior**

I expected the shortcuts to work the same as the other times I set up and everything was fine.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf-ge9e6b4f #1 SMP PREEMPT Sun Jan 17 21:43:04 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 9S
```

**Comment by kcubeterm** [comment]
Specifying in `~/. termux/termux.properties` 
Here's wiki https://wiki.termux.com/wiki/Terminal_Settings
Read carefully.

Basically you just need to uncomment few lines from that filed

**Comment by joseanoxp** [comment]
@kcubeterm I know exactly how to do it, but the shortcuts are not working, I don't do this today, I changed my cell phone a few days ago and when configuring the termux I came across this, so I reported it.

**Comment by kcubeterm** [comment]
Could you share your termux.properties file.
