### ISSUE TITLE
Package Request : zlib1g & zlib1g-dev

### ISSUE THREAD

**Issue by Tanishq-Banyal** [termux/termux-packages#6298]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

zlib is a library implementing the deflate compression method found
in gzip and PKZIP. 

zlib1g-dev package includes the development support files for zlib1g.

zlib1g is a common compression library and is required for android app development on termux.

**Link to home page and sources**
1. Home page: http://zlib.net/
2. Source code: http://zlib.net/zlib-1.2.11.tar.gz
3. Deb packages: https://debian.pkgs.org/10/debian-main-arm64/zlib1g-dev_1.2.11.dfsg-1_arm64.deb.html

**Additional information**
Have you compiled or tried to compile the package on device?
* I didn't try

**Comment by kcubeterm** [comment]
Zlib is available in termux repo.

**Comment by Tanishq-Banyal** [comment]
> Zlib is available in termux repo.

But i need zlib1g-dev and zlib1g

because its required by buildozer.

**Comment by kcubeterm** [comment]
Install zlib and then Install buildozer. That's the package.

**Comment by Tanishq-Banyal** [comment]
> Install zlib and then Install buildozer. That's the package.

No, buildozer needs "dev" package for header files

**Comment by kcubeterm** [comment]
Header files is included. 
```sh
$ whatprovides -p zlib
zlib: /data/data/com.termux/files/usr/include/zconf.h
zlib: /data/data/com.termux/files/usr/include/zlib.h
zlib: /data/data/com.termux/files/usr/lib/libz.so
zlib: /data/data/com.termux/files/usr/lib/libz.so.1
zlib: /data/data/com.termux/files/usr/lib/libz.so.1.2.11
zlib: /data/data/com.termux/files/usr/lib/pkgconfig/zlib.pc
zlib: /data/data/com.termux/files/usr/share/doc/zlib/LICENSE
zlib: /data/data/com.termux/files/usr/share/man/man3/zlib.3.gz
```

**Comment by Tanishq-Banyal** [comment]
> Header files are included.
> 
> ```shell
> $ whatprovides -p zlib
> zlib: /data/data/com.termux/files/usr/include/zconf.h
> zlib: /data/data/com.termux/files/usr/include/zlib.h
> zlib: /data/data/com.termux/files/usr/lib/libz.so
> zlib: /data/data/com.termux/files/usr/lib/libz.so.1
> zlib: /data/data/com.termux/files/usr/lib/libz.so.1.2.11
> zlib: /data/data/com.termux/files/usr/lib/pkgconfig/zlib.pc
> zlib: /data/data/com.termux/files/usr/share/doc/zlib/LICENSE
> zlib: /data/data/com.termux/files/usr/share/man/man3/zlib.3.gz
> ```

But buildozer doesn't detect it
It only wants zlib1g not zlib

**Comment by kcubeterm** [comment]
Weird, when I did, buildozer get installed without any error with pip

**Comment by Tanishq-Banyal** [comment]
> Weird, when I did, buildozer get installed without any error with pip

Installation via pip goes fine for me too.

But it asks for zlib1g while building apk.
If not found, it fails to build.

**Comment by Tanishq-Banyal** [comment]
* I tried to install it manually using deb files with this command :-
```dpkg --add-architecture arm64 && mkdir -p ~/zlib-temp && cd ~/zlib-temp && curl http://ftp.br.debian.org/debian/pool/main/z/zlib/zlib1g-dev_1.2.11.dfsg-1_arm64.deb --output ./zlib1g-dev.deb && curl http://ftp.br.debian.org/debian/pool/main/g/glibc/libc6_2.28-10_arm64.deb --output ./libc6.deb && curl http://ftp.br.debian.org/debian/pool/main/z/zlib/zlib1g_1.2.11.dfsg-1_arm64.deb --output ./zlib1g.deb && curl http://ftp.br.debian.org/debian/pool/main/g/gcc-8/libgcc1_8.3.0-6_arm64.deb --output ./libgcc1.deb && curl http://ftp.br.debian.org/debian/pool/main/g/gcc-8/gcc-8-base_8.3.0-6_arm64.deb --output ./gcc-8-base.deb && curl http://ftp.br.debian.org/debian/pool/main/g/glibc/libc6-dev_2.28-10_arm64.deb --output ./libc6-dev.deb && curl http://ftp.br.debian.org/debian/pool/main/g/glibc/libc-dev-bin_2.28-10_arm64.deb --output ./libc-dev-bin.deb && curl http://ftp.br.debian.org/debian/pool/main/l/linux/linux-libc-dev_4.19.160-2_arm64.deb --output ./linux-libc-dev.deb && apt install ./libc-dev-bin.deb ./linux-libc-dev.deb ./gcc-8-base.deb ./libgcc1.deb ./libc6.deb ./libc6-dev.deb ./zlib1g.deb ./zlib1g-dev.deb && cd ~ && rm -rf ~/zlib-temp```

But i get error saying "unable to clean mess from /lib & /usr before installing new version err: read only directory"

**Comment by kcubeterm** [comment]
Linux debfile don't work with termux.and ask for help on buildozer forum. It's not our issues.

**Comment by Tanishq-Banyal** [comment]
> Linux debfile don't work with termux.and ask for help on buildozer forum. It's not our issues.

Ok. Maybe i can make it work using pRoot

Btw here is the error i get :-
```Preparing to unpack .../0-gcc-8-base.deb ...
Unpacking gcc-8-base:arm64 (8.3.0-6) ...
dpkg: error processing archive /data/data/com.termux/files/usr/tmp/apt-dpkg-install-v70FAq/0-gcc-8-base.deb (--unpack):
 unable to clean up mess surrounding './usr' before installing another version: Read-only file system
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libgcc1:arm64.
Preparing to unpack .../1-libgcc1.deb ...
Unpacking libgcc1:arm64 (1:8.3.0-6) ...
dpkg: error processing archive /data/data/com.termux/files/usr/tmp/apt-dpkg-install-v70FAq/1-libgcc1.deb (--unpack):
 unable to clean up mess surrounding './lib' before installing another version: Read-only file system
Selecting previously unselected package libc6:arm64.
Preparing to unpack .../2-libc6.deb ...
Unpacking libc6:arm64 (2.28-10) ...
dpkg: error processing archive /data/data/com.termux/files/usr/tmp/apt-dpkg-install-v70FAq/2-libc6.deb (--unpack):
 unable to clean up mess surrounding './etc/ld.so.conf.d' before installing another version: Read-only file system
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package zlib1g:arm64.
Preparing to unpack .../3-zlib1g.deb ...
Unpacking zlib1g:arm64 (1:1.2.11.dfsg-1) ...
dpkg: error processing archive /data/data/com.termux/files/usr/tmp/apt-dpkg-install-v70FAq/3-zlib1g.deb (--unpack):
 unable to clean up mess surrounding './lib' before installing another version: Read-only file system
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libc-dev-bin:arm64.
Preparing to unpack .../4-libc-dev-bin.deb ...
Unpacking libc-dev-bin:arm64 (2.28-10) ...
dpkg: error processing archive /data/data/com.termux/files/usr/tmp/apt-dpkg-install-v70FAq/4-libc-dev-bin.deb (--unpack):
 unable to clean up mess surrounding './usr' before installing another version: Read-only file system
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package linux-libc-dev:arm64.
Preparing to unpack .../5-linux-libc-dev.deb ...
Unpacking linux-libc-dev:arm64 (4.19.160-2) ...
dpkg: error processing archive /data/data/com.termux/files/usr/tmp/apt-dpkg-install-v70FAq/5-linux-libc-dev.deb (--unpack):
 unable to clean up mess surrounding './usr' before installing another version: Read-only file system
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libc6-dev:arm64.
Preparing to unpack .../6-libc6-dev.deb ...
Unpacking libc6-dev:arm64 (2.28-10) ...
dpkg: error processing archive /data/data/com.termux/files/usr/tmp/apt-dpkg-install-v70FAq/6-libc6-dev.deb (--unpack):
 unable to clean up mess surrounding './usr' before installing another version: Read-only file system
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../7-zlib1g-dev.deb ...
Unpacking zlib1g-dev:arm64 (1:1.2.11.dfsg-1) ...
dpkg: error processing archive /data/data/com.termux/files/usr/tmp/apt-dpkg-install-v70FAq/7-zlib1g-dev.deb (--unpack):
 unable to clean up mess surrounding './usr' before installing another version: Read-only file system```

**Comment by xeffyr** [comment]
1. zlib1g and zlib are same packages, just Debian prefers zlib1g but Termux isn't Debian and chooses real package names.
2. Termux can execute only packages compiled for itself. It can't run/install Debian or Ubuntu native packages.

**Comment by xeffyr** [comment]
To finally clear false expectations from what Termux can do: https://wiki.termux.com/wiki/Differences_from_Linux
