### ISSUE TITLE
Library "libqc-opt.so" missing reported by termux-open-url and termux-share

### ISSUE THREAD

**Issue by bohrshaw** [termux/termux-packages#631]
`termux-open-url google.com` echoes me:
 `CANNOT LINK EXECUTABLE: library "libqc-opt.so" not found`.

**Comment by truh** [comment]
Does it work if you run ``termux-open-url https://google.com/`` instead and does that resolve your issue?

**Comment by BohrShaw** [comment]
No. Still get the same error. I tried several more termux-* commands and they all reported the same error.

I'm on miui and Google play service is not installed. I suppose that some system dependency is missing but don't know which.

**Comment by vishalbiswas** [comment]
try the same thing but run following command before doing it.
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/vendor/lib:/system/lib`

**Comment by BohrShaw** [comment]
Thanks, it works with `export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib:/system/vendor/lib64:/system/lib64` in the bash profile.

But after `termux-chroot`, I still get the old error.

**Comment by xeffyr** [comment]
Should be fixed with `termux-am` package which was added in 0b470897d1f42ecf6272ffe6c9b7de88211388c1.
