### ISSUE TITLE
Crash while running code-server

### ISSUE THREAD

**Issue by mrfoxie** [termux/termux-packages#6316]
Android: 8.1.0
Termux: 0.101

**Problem description**
i installed nodejs latest version and then i used `npm install --global code-server` and its run perfectly and when i run code-server in my browser termux gets crashed after few minutes of used.

**Expected behavior**
Run vscode on Android device but termux get crashed whenever I try to run it. 

**Additional information**

```
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
apt/stable 2.1.15 aarch64 [upgradable from: 1.4.10-6]
bash/stable 5.1.4 aarch64 [upgradable from: 5.0.18-2]
ca-certificates/stable 20210125 all [upgradable from: 20200722]
command-not-found/stable 1.60 aarch64 [upgradable from: 1.57]
coreutils/stable 8.32-7 aarch64 [upgradable from: 8.32-4]
curl/stable 7.74.0 aarch64 [upgradable from: 7.72.0]
dash/stable 0.5.11.3 aarch64 [upgradable from: 0.5.11.2-2]
debianutils/stable 4.11.2 aarch64 [upgradable from: 4.11.1]
dos2unix/stable 7.4.2 aarch64 [upgradable from: 7.4.1-1]
dpkg/stable 1.20.5-5 aarch64 [upgradable from: 1.20.5-2]
ed/stable 1.17 aarch64 [upgradable from: 1.16-1]
findutils/stable 4.8.0 aarch64 [upgradable from: 4.7.0-2]
gpgv/stable 2.2.26 aarch64 [upgradable from: 2.2.23]
grep/stable 3.6 aarch64 [upgradable from: 3.4-1]
less/stable 563 aarch64 [upgradable from: 551-1]
libcurl/stable 7.74.0 aarch64 [upgradable from: 7.72.0]
libgcrypt/stable 1.8.7 aarch64 [upgradable from: 1.8.6]
libgmp/stable 6.2.1 aarch64 [upgradable from: 6.2.0-1]
libgpg-error/stable 1.41 aarch64 [upgradable from: 1.39]
libnghttp2/stable 1.42.0 aarch64 [upgradable from: 1.41.0-1]
libtirpc/stable 1.3.1 aarch64 [upgradable from: 1.2.6-1]
lsof/stable 4.94.0 aarch64 [upgradable from: 4.93.2]
net-tools/stable 2.10.0 aarch64 [upgradable from: 1.60.2017.02.21-3]
openssl/stable 1.1.1i aarch64 [upgradable from: 1.1.1h]
readline/stable 8.1.0 aarch64 [upgradable from: 8.0.4-1]
termux-am/stable 0.4 all [upgradable from: 0.3]
termux-exec/stable 1:0.8 aarch64 [upgradable from: 0.5]
termux-tools/stable 0.104 all [upgradable from: 0.94]
util-linux/stable 2.36.1 aarch64 [upgradable from: 2.36]
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf #1 SMP PREEMPT Sat Jul 4 23:29:07 CST 2020 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1801
```

**Comment by Grimler91** [comment]
Sounds like android kills it due to low memory, and in that case there's not much to do about it. A `logcat` from adb might tell you more.

Also: It seems that you have not upgraded your packages in 6 months or so. Please run `pkg upgrade` every now and then, there is no guarantee that packages (like node) work if their dependencies are outdated.

**Comment by mrfoxie** [comment]
Okay

**Comment by mrfoxie** [comment]
okay i got logcat but i cant understand it so i will manage it, but there is a problem in terminal it is not working and giving this error
![image](https://user-images.githubusercontent.com/25217451/106143454-cb613200-6198-11eb-9003-ad635122bd98.png)

**Comment by Grimler91** [comment]
If the logcat seem to indicate that android killed termux then you can look into disabling "battery optimization" and similar things for termux. 

Your screenshot does not show any error, just some filenames. In any case, if you get an error (or warning) then it is probably an issue in code-server rather than in some package in termux

**Comment by mrfoxie** [comment]
thank you @Grimler91 and I found a better solution for it I installed proot-distro, then install parrot distribution and then I used this `curl -fsSL https://code-server.dev/install.sh | sh` to install it and now it's working properly and I suggest that if someone is having same issues then suggest this following steps
```
apt update
apt install proot-distro
proot-distro install parrot-lts
proot-distro login parrot-lts
apt update && apt install nano -y
curl -fsSL https://code-server.dev/install.sh | sh
```

and then use `nano ~/.config/code-server/config.yaml` to set the password for code-server 


thank you
