### ISSUE TITLE
[Package Request] speedtest-cli

### ISSUE THREAD

**Issue by z751** [termux/termux-packages#632]
https://github.com/sivel/speedtest-cli

**Comment by fornwall** [comment]
I try to avoid packaging things easily installable using `pip`, and as the README there says you can install it with:

    pip install speedtest-cli

(Note that you need to run `apt install python` first to have `pip` available).

**Comment by Walkman100** [comment]
👍 thanks. command-not-found suggesting things installable by alternate package managers like pip would be useful

**Comment by MahirMammadlee** [comment]
I used this, but it showed me true download speed and high, wrong upload speed..
