### ISSUE TITLE
Building nodejs directly on termux

### ISSUE THREAD

**Issue by ParseThisCode** [termux/termux-packages#6320]
![Screenshot_20210128-154654](https://user-images.githubusercontent.com/76525814/106154863-5a158500-6180-11eb-83fa-c1a35e54bf64.png)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by Grimler91** [comment]
I guess you are trying to build some other version than we have in the repo. 

A patch fails to apply so you need to update it to work for that version.

**Comment by ParseThisCode** [comment]
How?

**Comment by Grimler91** [comment]
You have not given any details about what you are doing (what version of node are you trying to build? How are you building it, with build-package.sh from the master branch or build-on-device branch?) so it is impossible for anyone to tell you what changes the patch needs.

But generally
* look at the patch
* look at the file it fails to apply to
* change the patch to make it apply again, or delete it if it does not seem to be necessary anymore

**Comment by ParseThisCode** [comment]
OUTDATED
