### ISSUE TITLE
hydra cannot be compiled in Termux

### ISSUE THREAD

**Issue by 26chk** [termux/termux-packages#6321]
1 warning generated.
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-a8cac6.o: in function `fill_mem':
/data/data/com.termux/files/home/thc-hydra/hydra.c:1110: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-a8cac6.o: in function `hydra_increase_fail_count':
/data/data/com.termux/files/home/thc-hydra/hydra.c:1473: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/thc-hydra/hydra.c:1473: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-a8cac6.o: in function `process_proxy_line':
/data/data/com.termux/files/home/thc-hydra/hydra.c:2026: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/thc-hydra/hydra.c:2030: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-a8cac6.o:/data/data/com.termux/files/home/thc-hydra/hydra.c:2038: more undefined references to `index' follow
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:66: hydra] Error 1
![Screenshot_20210129_000042](https://user-images.githubusercontent.com/61009000/106164549-0d07d200-61c5-11eb-80c0-1af34e204738.jpg)

**Comment by Grimler91** [comment]
[See the CFLAGS used when we built the package](https://github.com/termux/termux-packages/blob/37375312b93aecee93d86392b8db6b9ab3359c84/packages/hydra/build.sh#L14)
