### ISSUE TITLE
Request for AVR

### ISSUE THREAD

**Issue by uriukti** [termux/termux-packages#6326]
Good day.  Please add the minimum possible utilities for working with AVR microcontrollers.  These utilities are widely known and used by many programmers.  A smartphone can be very handy today for this kind of work.  And it is already possible to flash via USB-OTG.  
Packages: gcc-avr, binutils-avr, avr-libc, avrdude, avra.

**Comment by Grimler91** [comment]
[Our clang can already build for AVR](https://github.com/termux/termux-packages/blob/fbe6659950a5e992bd012f1721255ca1e5b05e18/packages/libllvm/build.sh#L42), are there any other features in the other listed packages that you are after?

**Comment by uriukti** [comment]
Unfortunately I don't know clang, haven't used it.  But I am programming in assembly language.  And I can tell you what these utilities are.  gcc-avr - assembler for avr.  avra is an assembler compiler.  avrdude is a utility that works with all AVR microcontrollers known today, as well as with all known programmers for them.  It allows you to flash microcontrollers.  the rest of the packages contain what is needed for this work.  If your clang can do all of this, then I could use it too.  If not, could you add the missing piece?

**Comment by uriukti** [comment]
Unfortunately I don't know clang, haven't used it.  But I am programming in assembly language.  And I can tell you what these utilities are.  gcc-avr - assembler for avr.  avra is an assembler compiler.  avrdude is a utility that works with all AVR microcontrollers known today, as well as with all known programmers for them.  It allows you to flash microcontrollers.  the rest of the packages contain what is needed for this work.  If your clang can do all of this, then I could use it too.  If not, could you add the missing piece?

**Comment by Grimler91** [comment]
Thanks for the explanation! At least avrdude can be useful, but probably requires some quite heavy patching to work with libusb on non-rooted devices.

**Comment by uriukti** [comment]
Thank you so much !!!  If everything works out it could be very useful.  If it can help a little, then the ZFlasher app for android also works based on avrdude and does not require root.

**Comment by xtkoba** [comment]
The rest should be handled in #561. Thanks.
