### ISSUE TITLE
CANNOT LINK EXECUTABLE "qemu-system-x86_64": library "libpulsecommon-14.0.so" not found: needed by /data/data/com.termux/files/usr/lib/libSDL2_image-2.0.so.0.2.3 in namespace (default)

### ISSUE THREAD

**Issue by Mariaephilothea** [termux/termux-packages#6329]
I am trying to run Win10 on aarch64 android 11 Samsung Galaxy note 10+
and ran the following command: 

'qemu-system-x86_64 -m 960 -cdrom /sdcard/imgcache/Win10CDv2/Win10XPE.iso -vnc 127.0.0.1:2' 

and Termux returned the following:

CANNOT LINK EXECUTABLE "qemu-system-x86_64": library "libpulsecommon-14.0.so" not found: needed by /data/data/com.termux/files/usr/lib/libSDL2_image-2.0.so.0.2.3 in namespace (default)

please help.

**Comment by WMCB-Tech** [comment]
A workaround for that is to delete current qemu Installation and replace it with the following package:

`qemu-system-x86-64-headless`

**Comment by xeffyr** [comment]
Try `pkg upgrade`.

**Comment by xeffyr** [comment]
Closing as issue is fixed.
