### ISSUE TITLE
Build packages failed, like wget or mosquitto

### ISSUE THREAD

**Issue by wcc21320** [termux/termux-packages#633]
Hi, I'm trying to build a project after setup, but failed. Then I guess if it failed by my dirty environment; so I using docker to do it again. 
> ./scripts/run-docker.sh ./build-package.sh libandroid-support

Seems good, and the somethings created in deb/.
And then I try :

>  ./scripts/run-docker.sh ./build-package.sh libmosquitto

And I got the same error :

```
termux-packages-master $ ./scripts/run-docker.sh ./build-package.sh libmosquitto
Running container 'termux-package-builder' from image 'termux/package-builder'...
termux - building libmosquitto for arch aarch64...
make: Entering directory '/root/.termux-build/libmosquitto/src/lib'
aarch64-linux-android-gcc  -specs=/root/termux-packages/termux.spec -Os -I/data/data/com.termux/files/usr/include -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_SOCKS -DWITH_SRV -c mosquitto.c -o mosquitto.o
In file included from mosquitto.c:33:0:
./mosquitto_internal.h:27:27: fatal error: openssl/ssl.h: No such file or directory
 #  include <openssl/ssl.h>
                           ^
compilation terminated.
Makefile:51: recipe for target 'mosquitto.o' failed
make: *** [mosquitto.o] Error 1
make: Leaving directory '/root/.termux-build/libmosquitto/src/lib'
```

Another try for build "wget" will got : 
```
configure: error: Package requirements (openssl) were not met:

No package 'openssl' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

```

And in Docker image,  said "openssl" already the newtest :
```
root@9e7b7a3f5e30:~/termux-packages# apt-get install openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.0.2g-1ubuntu4.5).

```

Any suggestion will be good, thanks in advance.

**Comment by Neo-Oli** [comment]
Yes you need to build all your packages' dependencies first. And their dependencies as well. You can use the buildorder.py script for that 
```
for p in `./scripts/buildorder.py libmosquitto`; do ./scripts/run-docker.sh ./build-package.sh $p; done
```
After you did that at least once, you can then make changes to the buildscripts and run `build-package.sh` only for the changed package.

**Comment by fornwall** [comment]
@Neo-Oli @wcc21320 I've just pushed a change to `build-package.sh` to automatically build dependencies (if not already built).

With this, calling `./scripts/buildorder.py` oneself should no longer be necessary and build errors like this will hopefully not happen in the future!

**Comment by wcc21320** [comment]
That 's wonderful ! thank a lot.

**Comment by vishalbiswas** [comment]
@fornwall Noooooo! I have several packages whose dependencies are on a different branch. Now every time I'll try to build a package, it will fail because of buildorder.py.
Maybe you can modify buildorder.py to check for dependencies of only required packages recursively instead of going through all packages at once.
