### ISSUE TITLE
Package request: silicon

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#6331]
Silicon is a cli written in rust that renders source code in an image.

https://github.com/Aloxaf/silicon

I just stepped over this project and I don't know much if it will run on Termux and I barely have any storage space to install rust and play around with it so I'd like to see it packaged if possible.

**Comment by amm834** [comment]
> Silicon is a cli written in rust that renders source code in an image.
> 
> https://github.com/Aloxaf/silicon
> 
> I just stepped over this project and I don't know much if it will run on Termux and I barely have any storage space to install rust and play around with it so I'd like to see it packaged if possible.

You can install via cargo bcuz it is using rust lang.
```bash
pkg install rust
cargo install silicon
```

**Comment by ravener** [comment]
@amm834 yes i know but it'd be nice to have it as a package
