### ISSUE TITLE
Qemu headless curses: charset issues

### ISSUE THREAD

**Issue by easyaspi314** [termux/termux-packages#6332]
**Problem description**

I honestly don't know if this is a bug with Termux's terminal, iconv, QEMU, or ncurses.

In `qemu-system`'s `curses` backend, most low ASCII characters (`0x00-0x1f`) show up as random CJK characters:

![Screenshot_20210129-131307](https://user-images.githubusercontent.com/6258309/106311884-d61cd500-6233-11eb-8faf-47ba2b8bb663.png)

**Steps to reproduce**

The thing this most clearly affects is FreeDOS's `edit` program in color mode. It is 100% unusable.

However, for a standalone BIOS program, unzip the attached file (which has the source code as well for nasm and definitely not a modified Hello World example I found online), and run it like so:

```
qemu-system-{x86_64/i386} -display curses boot.bin
```
Either `qemu-system-x86_64` or `qemu-system-i386` will work, and headless is fine.

This will print bytes `0-255` to the console and hang. Hit Alt+2 and type `quit` to exit as it tells you to do.
[boot.zip](https://github.com/termux/termux-packages/files/5895505/boot.zip)

**Expected behavior**

Something like what the `-nographic` displays:

![Screenshot_20210129-131250](https://user-images.githubusercontent.com/6258309/106311840-c2716e80-6233-11eb-9bcd-953feae3f6c2.png)

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
libcairo/stable 1.16.0-7 aarch64 [upgradable from: 1.16.0-2]
pulseaudio/stable 14.2-2 aarch64 [upgradable from: 12.2-21]
Android version:
11
Kernel build information:
Linux localhost 4.4.223-g52750b8f2138-ab6846512 #1 SMP PREEMPT Fri Sep 18 09:49:34 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 2 XL

```

**Comment by easyaspi314** [comment]
I assume it might have something to do with the code [here](https://github.com/qemu/qemu/blob/3701c07e63bb945137bf80fe35e7058ad3784c45/ui/curses.c#L522) but I haven't tested it.

**Comment by xeffyr** [comment]
That's libiconv I guess. QEMU previously had error "Could not convert font glyphs from UCS-2" but it gone at some version update.

> Ctrl-A X doesn't work

Works for me...

**Comment by easyaspi314** [comment]
> Ctrl-A X doesn't work

Works for me...

Yeah I take it back. It is working now. 

It might have been a bad ncurses shutdown blocking keystrokes.

**Comment by easyaspi314** [comment]
Oh ho ho I found a clue...

![Screenshot_20210129-150505](https://user-images.githubusercontent.com/6258309/106322171-6b739580-6243-11eb-91b5-66e5b9bed8f2.png)

It seems that iconv is trying to convert from UCS-2 *big endian*.

Why? IDK.

**Comment by easyaspi314** [comment]
Nah, it appears to be a Termux issue.

![image](https://user-images.githubusercontent.com/6258309/106324347-f73af100-6246-11eb-8ba5-8d7cdb411206.png)

QEMU 4.2.1, glibc 2.31, Ubuntu Focal on WSL

**Comment by easyaspi314** [comment]
If I manually replace `UCS-2` with `UCS-2LE` in `ui/curses.c`, it works!

![Screenshot_20210129-163127](https://user-images.githubusercontent.com/6258309/106329458-77655480-624f-11eb-9c1e-196c263247ba.png)

**Comment by easyaspi314** [comment]
So, AFAIK, the issue is that glibc's `iconv` will treat `"UCS-2"` as native endianness, while libiconv will treat it as big endian. What a blatant inconsistency.

**Comment by xeffyr** [comment]
I guess this issue can be closed now. Package is now patched and seems working correctly.
