### ISSUE TITLE
Not connecting to any database (freezes in python).

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#6334]
**Problem description**
Is it possible that termux blocks the connections of the databases in python?, I try to connect to the database try using postgres, mysql, among others.  And it is the same problem, They fail to perform actions, it is frozen when using non-authentic databases in python.

**Steps to reproduce**

- `pkg install postgres`.
- `pkg install python`
- `pip install psycopg2`
- `python run.py` 
in run.py replace with the name of the file, with an example in the code of some non-authenticating database.

**Expected behavior**
that the database works and if it connects.

**Comment by RossComputerGuy** [comment]
Is the database running?

**Comment by LivestC** [comment]
> Is the database running?

Yes

**Comment by thunder-coding** [comment]
I suspect something's wrong with your Python code and not with Python. If this is not the case consider opening a new issue with a minimal reproduction sample
