### ISSUE TITLE
dosfstools: FAT filesystem tools

### ISSUE THREAD

**Issue by SergioFLS** [termux/termux-packages#6335]
- [☑] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

The package contains tools that can create (`mkfs.fat`), check (`fsck.fat`) and label (`fatlabel`) FAT filesystems.

There are packages that can create other filesystems (such as `util-linux`), but none for FAT.

**Link to home page and sources**
1. Home page: https://github.com/dosfstools
2. Source code: https://github.com/dosfstools/dosfstools

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

`$ ./configure`
![configure](https://user-images.githubusercontent.com/34007063/106348900-b7651f80-62c1-11eb-8012-437426f5faca.jpg)

`$ make` (not full output! couldn't fit it in one semi-readable screenshot)
![make](https://user-images.githubusercontent.com/34007063/106348942-f5fada00-62c1-11eb-872d-53411ec8cf21.jpg)

**Comment by thibaultmeyer** [comment]
Hello,

is `libiconv` installed ?

**Comment by SergioFLS** [comment]
> Hello,
> 
> is `libiconv` installed ?

Yes, `iconv` and `libiconv` are installed.
Even with these packages installed, the compilation progress still fails, though.
![iconv version](https://user-images.githubusercontent.com/34007063/106364036-08a5fb00-6324-11eb-8c14-7cb1fa9300b1.jpg)

**Comment by thibaultmeyer** [comment]
the problem seems to be known: https://github.com/dosfstools/dosfstools/issues/50

**Comment by thibaultmeyer** [comment]
Can compile by adding these lines on `dosfstools-4.1/src/charconv.c`

```c
#define libiconv_open iconv_open
#define libiconv_close iconv_close
#define libiconv iconv
```

**Comment by SergioFLS** [comment]
> the problem seems to be known: https://github.com/dosfstools/dosfstools/issues/50
> 
> ```
> i passed the libiconv.a externally when configuring and after the errors are gone .
> and whare can i get libudev for mkfs.fat
> ```

using `LIBS=/data/data/com.termux/files/usr/lib/libiconv.a ./configure` seems to compile successfully too

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install dosfstools
```
