### ISSUE TITLE
Hydra cannot be compiled in Termux

### ISSUE THREAD

**Issue by 26chk** [termux/termux-packages#6337]
These are my compilation steps：

git clone --depth=1 https://github.com/vanhauser-thc/thc-hydra

cd thc-hydra

CFLAGS+=" -Dindex=strchr -Drindex=strrchr -DLIBOPENSSL -DNO_RINDEX -DHAVE_MATH_H -DHAVE_PCRE -DLIBSSH"

export MANDIR=/share/man/man1

export XLIBS="-lcrypto -lssl -lpcre -lssh"

cat Makefile.am | sed 's/^install:.*/install: all/'  >> Makefile

Finally it got an error:-(

![Screenshot_20210130_213648](https://user-images.githubusercontent.com/61009000/106357807-48300f80-6343-11eb-957b-119929d8889b.jpg)

**Comment by xeffyr** [comment]
use `export CFLAGS`, not the CFLAGS+=.
