### ISSUE TITLE
Segfault while running mpv

### ISSUE THREAD

**Issue by mindbound** [termux/termux-packages#634]
When I execute either `mpv` or `mpv --version`, it segfaults. Latest Termux and mpv, Android 6.0.1, Galaxy Tab A SM-T550.

**Comment by its-pointless** [comment]
Going to need a tad more info. I don't even know what arch that uses.

**Comment by mindbound** [comment]
CPU: ARM Cortex-A53 quad-core, using ARMv8-A architecture, GPU: Adreno 306, supports up to OpenGL 3.0, RAM: 1.5 GB. Please let me know if there's anything else I should add.

**Comment by vishalbiswas** [comment]
First, `apt install ltrace strace`
Then paste output of both `ltrace mpv` and `strace mpv`. Use a paste site as the 2nd one will have quite a bit (or should I say bytes) of data.

**Comment by mindbound** [comment]
`ltrace mpv`: https://0bin.net/paste/WX9OlXZUAcoX3G9B#Jq4joV6nllAdR6dDI7iow-8WFgU72qJzDUvxLBexDbU
`strace mpv`: https://0bin.net/paste/-4OhD-79n2FvC6AN#C1ShtNvvvQUK11tA9-lWgUwf3prl+qkZ1b8GNYv1mPC

**Comment by its-pointless** [comment]
Is there a libvendorconn.so in the /system/lib64/ dir?

**Comment by mindbound** [comment]
I can't find libvendorconn.so in any of those places. To be fair, this can be seen in the `strace` output as well:
```openat(AT_FDCWD, "/data/data/com.termux/files/usr/lib/libvendorconn.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/vendor/lib/libvendorconn.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/system/lib/libvendorconn.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/data/data/com.termux/files/usr/lib/libvendorconn.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/vendor/lib/libvendorconn.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/system/lib/libvendorconn.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by mindbound** [comment]
I installed Termux from Google Play. Output from `dpkg --print-architecture` is just `arm`, whereas /system/lib64 contains only a single file, libSecMMCodec.so.

**Comment by vishalbiswas** [comment]
It may be possible that your os reports arm as first arch and aarch64 as second, which may have led the app to download arm bootstrap instead of aarch64 one.
@fornwall Is this the case? How is the arch decided when downloading bootstrap zip?

**Comment by fornwall** [comment]
@vishalbiswas The arch is decided using [Build.SUPPORTED_ABIS](https://developer.android.com/reference/android/os/Build.html#SUPPORTED_ABIS), taking the first element since:

> The most preferred ABI is the first element in the list

A guess would be that while the CPU supports 64-bit, Samsung only has a 32-bit userland on the device available. This is indicated by:

> /system/lib64 contains only a single file, libSecMMCodec.so

If the device had a complete&working 64-bit userland there would be a lot more files there.

**Comment by alive4ever** [comment]
When running mpv command, I got the following message
```
~$ mpv
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/mpv": cannot locate symbol "avcodec_send_packet" referenced by "/data/data/com.termux/files/usr/libexec/mpv"...
```
Not sure if this is related to this bug or a different issue.

**Comment by alive4ever** [comment]
It seems that my issue has been reported #572

**Comment by pranavg189** [comment]
I have a similar problem on my Samsung Galaxy Grand running Cyanogenmod 12.1:

here is the strace on my mobile: http://pastebin.com/7yqsjZgB

**Comment by pranavg189** [comment]
I think the problem here is similar to #122.

**Comment by pranavg189** [comment]
I found a solution to the above problem. Just use the link to the direct binary `data/data/com.termux/files/usr/libexec/mpv`
instead of the wrapper shell script provided in /usr/bin.

The solution is similar to #542.

This fixes the issue for me atleast. Now, mpv works flawlessly on my Samsung Galaxy Grand Duos running CyanogenMod 12.1. 

Cheers !!

**Comment by mindbound** [comment]
For me, running `data/data/com.termux/files/usr/libexec/mpv` fails with
```
CANNOT LINK EXECUTABLE: cannot locate symbol "png_set_seek_fn" referenced by "/system/lib/libskia.so"...
page record for 0×b6e4808c was not found (block_size=64)
```
The address referenced in the error message changes with each run.

**Comment by pranavg189** [comment]
I remember yesterday I had tried running it too and it gave me a segfault. But today mpv is running with no problem...I dont know how it got solved today...try installing play-audio package using apt...I installed it just now...maybe because of that....not sure :)

**Comment by mindbound** [comment]
Thanks, but I have that installed for some time now, with no effects on this issue.

**Comment by feserafim** [comment]
Thanks @pranavg189, executing `/data/data/com.termux/files/usr/libexec/mpv` solved the problem for me.

**Comment by fornwall** [comment]
@feserafim @mindbound Does updating to the latest 0.24.0-1 version of mpv with `apt update && apt upgrade` fix the issue?

**Comment by mindbound** [comment]
@fornwall It doesn't for me, mpv still crashes with the same errors as before.

**Comment by its-pointless** [comment]
try this http://pastebin.com/iHZTxcMp
see if it works?

**Comment by mindbound** [comment]
@its-pointless It fails with the same error as in https://github.com/termux/termux-packages/issues/634#issuecomment-277269542.

**Comment by its-pointless** [comment]
could you list all files in /system/lib and /system/vendor/lib ?

**Comment by mindbound** [comment]
/system/lib: https://drive.google.com/open?id=0BwKbG1Uij8iJZUZndDl2NXNWdVg0TGFQRUNEemlnc0RaZ1Aw
/system/vendor/lib: https://drive.google.com/open?id=0BwKbG1Uij8iJSzlNTjhpS1NTNHd3SHg3YnMwSjdRaHZmWXNN

**Comment by fornwall** [comment]
@mindbound Sorry, there was a mistake in the last update, can you try updating again (this time to 0.24.0-2) and see if that helps? Thanks for the help!

**Comment by mindbound** [comment]
@fornwall The update didn't help.

**Comment by mindbound** [comment]
Today I decided to reinstall mpc and look at it again. It still fails but this time it does so with a different error (when calling with the full path):

> CANNOT LINK EXECUTABLE: cannot locate symbol "ucnv_open_55" referenced by "/system/lib/libmedia.so".

**Comment by its-pointless** [comment]
Mindbound thats a library conflict issue. If you could provide a list of lib*.so files in /system/lib and /system/vendor/lib i can fix this issue.
Have you tried mpd + ncmpcpp instead of mpv same error?

**Comment by mindbound** [comment]
@its-pointless I added these lists a few comments a while ago (https://github.com/termux/termux-packages/issues/634#issuecomment-281525033). Also, since mpv is [also] a video player, I don't think mpd can be a replacement in this case.

**Comment by its-pointless** [comment]
i think i know whats happening. libav stuff links to libopus its loading your system lib and then dying because it can't resolv a symbol. 

exec this  mpv script replacement and tell if it works please? http://its-pointless.github.io/mpv

**Comment by mindbound** [comment]
It fails with a segfault. Please see the [strace dump](https://pastebin.com/7NDgfHmS).

**Comment by its-pointless** [comment]
could you use this instead  of strace?
its-pointless.github.io/tracefile 
tracefile mpv

**Comment by mindbound** [comment]
[There you go](https://pastebin.com/VGLMY2p0).

**Comment by vishalbiswas** [comment]
@mindbound run strace with `-y -f`

**Comment by mindbound** [comment]
https://pastebin.com/JSErZ23A

**Comment by xeffyr** [comment]
Issue seems not active since *19 May 2017*.

Is there anyone who experiencing it ?
