### ISSUE TITLE
Php imagick in termux missing… 

### ISSUE THREAD

**Issue by gyurmogyuri** [termux/termux-packages#6343]
### Package description
Imagick is a PHP extension to create and modify images using the ImageMagick library.
### Home page URL

http://pecl.php.net/imagick

### Source code URL

https://github.com/Imagick/imagick

### Packaging policy acknowledgement

- [ ] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No Response_

**Comment by thunder-coding** [comment]
I have updated the issue comment to match the bug report template to make things more organised. In case anyone is able to port the extension, PRs are welcome

**Comment by sk0kanik** [comment]
@gyurmogyuri @thunder-coding it is already available https://github.com/termux/termux-packages/blob/master/packages/php-imagick/

**Comment by thunder-coding** [comment]
Thanks for correcting me @sk0kanik. Stalebot is doing a great work in helping us dig old issues that need to be closed :)
