### ISSUE TITLE
whay ngrok don't work

### ISSUE THREAD

**Issue by inhdyaii** [termux/termux-packages#6344]
I install proot and termux-chroot but ngrok dosnt work

**Comment by WMCB-Tech** [comment]
what do you mean doesn't work? do you have further output to show what is happening?

**Comment by inhdyaii** [comment]
It used to work when writing termux-chroot && ./ngrok http 3333 but now it not works after I updated Termux

**Comment by inhdyaii** [comment]
![Screenshot_20210203-134933](https://user-images.githubusercontent.com/69579471/106743408-0515bb00-6627-11eb-9096-df13b70d0093.jpg)

**Comment by xeffyr** [comment]
> termux-chroot && ./ngrok

This is not how termux-chroot is supposed to work. Learn shell scripting to know why...

**Comment by xeffyr** [comment]
Correct usage:
```
termux-chroot
ngrok
```
Each commands are separate, no `&&`.

**Comment by inhdyaii** [comment]
A million thousand. Thank you. I do not know how to thank you for helping me. I have been searching for all for three days. I hope to reach the stage in which I am at your level.
