### ISSUE TITLE
I can't install mariadb

### ISSUE THREAD

**Issue by HG-Son** [termux/termux-packages#6346]
- [ ] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
1. Use of wrong template.
2. No error description. Which exactly error did you get when installing mariadb? "I can't install mariadb" is ambiguous.

**Comment by HG-Son** [comment]
Unable to locate package

**Comment by xeffyr** [comment]
If package manager can't locate package, then
```
apt update
pkg install mariadb
```

**Comment by HG-Son** [comment]
Ok, I'll check it out.

**Comment by HG-Son** [comment]
Thanks for the help....
