### ISSUE TITLE
I can't open jupyter notebook. Can anyone help me?

### ISSUE THREAD

**Issue by HG-Son** [termux/termux-packages#6347]
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
> I can't open jupyter notebook. Can anyone help me?

Can you be more specific on your issue? Add screenshots, logs, etc. Otherwise I will just close it as spam. Btw, you again used wrong template.

**This was last warning. Another issue providing zero information about the problem and you will get banned.**

**Comment by HG-Son** [comment]
Can't find the right browser

**Comment by xeffyr** [comment]
Yes, because you need to copy the link and open in normal Android browser.
