### ISSUE TITLE
[Bug] Termux packages not working under SU

### ISSUE THREAD

**Issue by soaringowl2145** [termux/termux-packages#635]
When I am using root with the su command, it seems that none of the add-on packages installed by apt-get are found. For example:

su
root@android:/ # openssl
sh: openssl: not found
127|root@android:/ #

When I do this NOT as root (standard user) it works:

openssl
OpenSSL>

**Comment by vishalbiswas** [comment]
This is intentional, to prevent users from messing with the termux filesystem. Also discussed in #601
