### ISSUE TITLE
Cannot install phyton series and git

### ISSUE THREAD

**Issue by Bagu55** [termux/termux-packages#6353]
I just downloaded trmux. and can't install python and git and there are some packages that i can't install.thx

**Comment by Grimler91** [comment]
Try `pkg update` first. If it does not help then we need more information, see the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=&template=bug_report.md).

**Comment by Bagu55** [comment]
I have done pkg update && pkg upgrade && apt update && apt upgrade install
root repo, unstable repo, but still cannot work install phyton series.

**Comment by Bagu55** [comment]
and what I want to ask is why does termux reconnect / return to the
beginning?

**Comment by Bagu55** [comment]
and what I want to ask is why does termux sometimes reconnect / return to
the beginning? enough happens every day

**Comment by kcubeterm** [comment]
Could you tell us about your device architecture. Or just paste output of
`termux-info`

**Comment by xeffyr** [comment]
> why does termux sometimes reconnect / return to the beginning? enough happens every day

What do you mean by reconnect / return to the beginning?

Also `phython` is a nonexistent package. There is a `python`.

**Comment by Bagu55** [comment]
Yes, return to the bgning.ok thx

**Comment by Bagu55** [comment]
like the start will start Temurx.

**Comment by xeffyr** [comment]
> like the start will start Temurx.

So you wondering why opening Termux app will start Termux?

**Comment by Bagu55** [comment]
~ $ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://unstable.termux-mirror.ml unstable main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://x11.termux-mirror.ml x11 main
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.18.31-perf-g0eab32e #1 SMP PREEMPT Sat Dec 9 01:50:23 CST
2017 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 5 Plus
~ $

**Comment by xeffyr** [comment]
@Bagu55 You still not provided the information about the issue. Instead you gave answers like
```
Yes, return to the bgning.ok thx
```
or
```
like the start will start Temurx.
```

If you fail to provide a *clear issue explanation*, like how to reproduce, screenshots, logs, etc, we will have to ignore further comments.

**Comment by Bagu55** [comment]
after a few hours I use termux (including running certain programs in
termux) not install pkg etc. every day, it will be interrupted (some of my
sessions are lost) and return to 1 session (like the beginning) that I call
reconecting

**Comment by xeffyr** [comment]
Ah then this is your device problem. You may try to enable wake lock (a button in app notification) though if your OS is a aggressive at power saving (typical on Huawei/Xiaomi devices), this may not help. Additional reason can be out-of-memory condition, where OS has to reclaim some RAM by terminating applications, another case on which you nearly have no control.

**Comment by Bagu55** [comment]
Ok, thanks.
