### ISSUE TITLE
Problem with chmod

### ISSUE THREAD

**Issue by John-L** [termux/termux-packages#6354]
![Screenshot_20210206-071045](https://user-images.githubusercontent.com/7512058/107118001-1986cd00-684c-11eb-81aa-dfe3ac15eaf3.png)
Seems simple enough...

Thanks in advance for any insight you can provide.

**Comment by kcubeterm** [comment]
That's not working here (internel storage) because internel storage mounts with noexec. You can even execute files in internel storage.

So move your file into somewhere in termux (home )directory  and then perform chmod
