### ISSUE TITLE
Android 10,unstable-repo has no installation candidate

### ISSUE THREAD

**Issue by skycat2216** [termux/termux-packages#6355]
As Title

I stuck on it 
I can't install unstable repo
It says:
Package unstable-repo is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'unstable-repo' has no installation candidate
But problem is 
I Running it on Android 10 

Phone model
Realme X50 4+128G

**Comment by xeffyr** [comment]
> I Running it on Android 10

The kind of environment (legacy / up-to-date current) matters, not the Android version.

If you are still using https://termux.net, then know it is 2 years as obsolete.
