### ISSUE TITLE
Package request: libapr1.0-dev

### ISSUE THREAD

**Issue by RussiaVk** [termux/termux-packages#6356]
to add tomcat apr mode support

**Comment by Grimler91** [comment]
What problem do you have with the [apr package](https://github.com/termux/termux-packages/tree/master/packages/apr)?

**Comment by Grimler91** [comment]
Closing, please provide more information if there is a problem. See the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=&template=bug_report.md) and [package request template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=&template=package_request.md)
