### ISSUE TITLE
zbar doesn't work !

### ISSUE THREAD

**Issue by 26chk** [termux/termux-packages#6357]
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
unstable-repo/stable 5.0 all [upgradable from: 4.1]
Android version:
9
Kernel build information:
Linux localhost 4.9.148 #1 SMP PREEMPT Fri May 22 18:59:13 CST 2020 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
VTR-AL00

Zbar:
CANNOT LINK EXECUTABLE "zbarimg": cannot locate symbol "MagickWandGenesis" referenced by "/data/data/com.termux/files/usr/bin/zbarimg"...

![Screenshot_20210206_230644](https://user-images.githubusercontent.com/61009000/107122012-644a2880-68d0-11eb-9fed-17bd05ae93f6.jpg)

**Comment by xeffyr** [comment]
Try `pkg upgrade`. Version `0.21.1-1` should run fine.

**Comment by 26chk** [comment]
> Try `pkg upgrade`. Version `0.23.1-1` should run fine.

Great，it work！
