### ISSUE TITLE
extend messages for "command not found" or pkg install if a program is not found

### ISSUE THREAD

**Issue by JensKorte** [termux/termux-packages#6358]
**Problem description**

I wanted to install youtube-dl, but it is not in the repo (because it is in PyPi...). When I just entered youtube-dl command not found didn't give a hint, that some packages never will be packaged. When I tried pkg install youtube-dl I didn't get a hint, that some programs won't be packaged or at least a hint to a wiki site, where more details are explained, where to search, when a program is not in the repos.
In the bug reports, I found the details.

**Expected behavior**

It would be nice, if somewhere at cnf or pkg install a hint shows a link of a wiki site or a text file in this github project, where more details about missing programs are. An extra program that searches through different sources would be the best, but could be too complicated.

From contributing.md for a wiki site:

> Packages must NOT be a part of language-specific ecosystem. These packages are installable through cpan, gem, npm, pip and similar.

As you can see in #5228 there are many duplicate package requests.

**Comment by xeffyr** [comment]
command-not-found is not supposed to search non-existent packages or something available somewhere in PyPI or Github. It tracks only what is available in the **official Termux apt repositories**, not something else.
