### ISSUE TITLE
Cannot install phyton series 

### ISSUE THREAD

**Issue by Bagu55** [termux/termux-packages#6359]
Android 7.1.2 (Nougat), MIUI 11
**Problem description**

**Steps to reproduce**
pkg install pyhton

**Expected behavior**

**Additional information**

```

```
I have done pkg update && pkg upgrade && apt update && apt upgrade install root repo, unstable repo,
but still canno work to install phyton and use it.
Thx

**Comment by xeffyr** [comment]
I know `python` and you can install it, but what is phython really IDK...
