### ISSUE TITLE
Package 'php' has no installation candidate

### ISSUE THREAD

**Issue by JuanPabloRios** [termux/termux-packages#6364]
I'm not able to install php.

![image](https://user-images.githubusercontent.com/38564511/107278684-6211d680-6a56-11eb-9bdb-9250e3816a34.png)
![image](https://user-images.githubusercontent.com/38564511/107278726-70f88900-6a56-11eb-8a71-8cbd16063d4f.png)

In a fresh new installation I run the commands
pkg update
pkg install php

**Expected behavior**
get php installation starting

**Additional information**
Android running in bluestacks emulator.
```

```

**Comment by xeffyr** [comment]
Intended behavior. Package is disabled for `x86_64` arch as problematic.
