### ISSUE TITLE
Collecting scikit-learn   Using cached scikit-learn-0.24.1.tar.gz (7.4 MB)   Installing build dependencies ... -

### ISSUE THREAD

**Issue by ugale-deepak3010** [termux/termux-packages#6365]
Collecting scikit-learn
  Using cached scikit-learn-0.24.1.tar.gz (7.4 MB)
  Installing build dependencies ... -

Stuck to load from some days I tried but not working

**Comment by xeffyr** [comment]
It may stuch at `Installing build dependencies ... -` for an hour, if your device is not that fast. It just builds native extensions for itself and dependencies on your device which is expected behavior.

**Comment by Grimler91** [comment]
Use the `-vvv` flag to get more output if you want to see the progress.
