### ISSUE TITLE
Termux app kill when NetHunter kex server start

### ISSUE THREAD

**Issue by fattain-naime** [termux/termux-packages#6366]
**Problem description**

I have install Termux v0.106 from f-Droid. And install Kali NetHunter Rootless by following the instructions [https://www.pastfutur.com/how-to-install-kali-nethunter-in-any-android-phone/](https://www.pastfutur.com/how-to-install-kali-nethunter-in-any-android-phone/)    everything look good but when i start kex vnc server by `kex &` it will start kex server but after 10 to 20 second the termux app stop and Kik me out from termux.

**Steps to reproduce**

I open termux and into NetHunter by `nh -r` and put `kex &` the kex vnc server start well. 
![Screenshot_20210209-200006940](https://user-images.githubusercontent.com/25886142/107377385-1d00a980-6b15-11eb-9252-9ae8eb5ba4a5.jpg)

I have updated termux by `apt-get update` `apt-get upgrade` `apt-get full-upgrade` also for NetHunter do same.  (Note: i was install apt by pkg install apt)

It was work well when i Install NetHunter in play store version of termux. Everything's was work well. In the 0.106 version i face the problem. 

**Expected behavior**

**Additional information**

```
~ $ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.184-🥵🥵🥵 #1 SMP PREEMPT Tue Oct 13 10:31:16 UTC 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Mi A3
~ $
```

**Comment by xeffyr** [comment]
That's a device-specific issue. Huawei/Xiaomi are known to have restrictions on background processes for "powersaving".

I can only suggest to:
* Enable wakelock.
* Exclude Termux app from power saving possible in battery menu.
* Visit https://dontkillmyapp.com/xiaomi and check out if there are options applicable to your device.

Nothing can be done on this from Termux side.

**Comment by fattain-naime** [comment]
> That's a device-specific issue. Huawei/Xiaomi are known to have restrictions on background processes for "powersaving".
> 
> I can only suggest to:
> 
> * Enable wakelock.
> * Exclude Termux app from power saving possible in battery menu.
> * Visit https://dontkillmyapp.com/xiaomi and check out if there are options applicable to your device.
> 
> Nothing can be done on this from Termux side.

I have already disable power saving or battery optimize. But nothing changes. I can provide a sort video for better understanding.

**Comment by xeffyr** [comment]
> But nothing changes.

Well, they not guarantee that app won't be killed if manufacturer decides to use own powersaving "features". Huawei, Xiaomi and probably OnePlus (though not enough reports/info on this one) are known to be problematic.

Again: nothing can be done on Termux side to change the behavior of the operating system.

**Comment by fattain-naime** [comment]
> > But nothing changes.
> 
> Well, they not guarantee that app won't be killed if manufacturer decides to use own powersaving "features". Huawei, Xiaomi and probably OnePlus (though not enough reports/info on this one) are known to be problematic.
> 
> Again: nothing can be done on Termux side to change the behavior of the operating system.

Thank you. Now i have to downgrade termux. Previous version that available in play store.
