### ISSUE TITLE
Termux unable to locate the package Npm

### ISSUE THREAD

**Issue by Shorata** [termux/termux-packages#6370]
hi termux expert.

i have a problem on termux, when im trying to install npm using '$pkg install npm' , but i always got
E : Unable to locate package npm

i've trying apt update and apt upgrade and it seems does noting, it still give me the same message when im trying to install npm again

please help me, i need this for my last hope

**Comment by xeffyr** [comment]
It is a part of nodejs package.

**Comment by Shorata** [comment]
> It is a part of nodejs package.

but when i try to $npm i

it give me alot of eror

**Comment by kcubeterm** [comment]
That's warning not error.

**Comment by Shorata** [comment]
so what can i do now?

**Comment by xeffyr** [comment]
Because you are using it wrong. Check out the Nodejs & NPM documentation on how to use it.
