### ISSUE TITLE
Android 11: zsh triggers fdsan

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-packages#6376]
**Problem description**

Zsh may trigger file descriptor sanitizer on Android 11 which result in crash.
![photo_2021-02-10_23-43-50](https://user-images.githubusercontent.com/25881154/107576708-2d3e8480-6bfa-11eb-9254-fce1272e2c5f.jpg)

**Steps to reproduce**

`zsh -c ls` or other similar command.

**Additional information**

Specific to Android 11+.

Related issues:
* https://github.com/termux/termux-packages/issues/6251
* https://github.com/termux/termux-packages/issues/5980
* https://github.com/termux/termux-packages/issues/5790

**Comment by Grimler91** [comment]
Here's the gdb backtrace for `zsh -c ls`

```c
(gdb) r
Starting program: /data/data/com.termux/files/usr/bin/zsh -c ls
fdsan: attempted to close file descriptor 11, expected to be unowned, actually owned by FILE* 0xb6bde00c

Program received signal SIGABRT, Aborted.
0xb6b589e8 in fdsan_error(char const*, ...) () from /apex/com.android.runtime/lib/bionic/libc.so
(gdb) bt
#0  0xb6b589e8 in fdsan_error(char const*, ...) () from /apex/com.android.runtime/lib/bionic/libc.so
#1  0xb6b586fe in android_fdsan_close_with_tag () from /apex/com.android.runtime/lib/bionic/libc.so
#2  0xb6b58d6e in close () from /apex/com.android.runtime/lib/bionic/libc.so
#3  0x7f5fbee2 in zclose (fd=11) at utils.c:2152
#4  0x7f58ff70 in closem (how=1, all=0) at exec.c:4425
#5  0x7f597dae in execcmd_exec (state=0xbefff3f8, eparams=0xbefff1b4, input=0, output=0, how=18, last1=1, close_if_forked=-1) at exec.c:4164
#6  0x7f594b72 in execpline2 (state=0xbefff3f8, pcode=131, how=18, input=0, output=0, last1=1) at exec.c:1934
#7  0x7f58ec28 in execpline (state=0xbefff3f8, slcode=3074, how=18, last1=1) at exec.c:1664
#8  0x7f58e0c4 in execlist (state=0xbefff3f8, dont_change_job=0, exiting=1) at exec.c:1419
#9  0x7f58db6e in execode (p=0xb6c61558, dont_change_job=0, exiting=1, context=0x7f686d32 "cmdarg") at exec.c:1198
#10 0x7f58da88 in execstring (s=0xbefff66d "ls", dont_change_job=0, exiting=1, context=0x7f686d32 "cmdarg") at exec.c:1164
#11 0x7f5afa28 in init_misc (cmd=0xbefff66d "ls", zsh_name=0xbefff666 "zsh") at init.c:1383
#12 0x7f5b0c08 in zsh_main (argc=3, argv=0xbefff504) at init.c:1767
#13 0x7f5783ce in main (argc=3, argv=0xbefff504) at ./main.c:93
```

**Comment by xeffyr** [comment]
Fixed.

**Comment by rikvanderkemp** [comment]
Although this is a closed issue. I just had similar issues using emacs in a freshly installed termux.

Could this be related? 

![Screenshot_20210406-230947_Termux.jpg](https://user-images.githubusercontent.com/347308/113778871-3301a380-972d-11eb-9842-5b31df735621.jpg)

Android version 11
Termux version 0.101
Default shell (bash)

**Comment by xeffyr** [comment]
emacs issue (https://github.com/termux/termux-packages/issues/6592) is still opened. I didn't patched this package.
