### ISSUE TITLE
Signature Failure

### ISSUE THREAD

**Issue by arunhimani** [termux/termux-packages#6377]
Err:1 http://mirror.fsmg.org.nz/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Fetched 30.5 kB in 3s (9305 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://mirror.fsmg.org.nz/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
W: Failed to fetch http://mirror.fsmg.org.nz/kali/dists/kali-rolling/InRelease  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
![Screenshot_20210211_142337](https://user-images.githubusercontent.com/78751481/107616825-c9a56d00-6c74-11eb-87a2-5c483f53bd10.jpg)

**Comment by Grimler91** [comment]
This is not a termux issue. We do not control kali repositories.
