### ISSUE TITLE
Failed to fetch some archives 3 times.

### ISSUE THREAD

**Issue by Haiz14** [termux/termux-packages#6379]
Thanks for the app and packages.  

While downloading rust PKG with   ```pkg install rust``` it shows this error (written below) after 80 something percent. I tried downloading 3 times today and 2 times yesterday.

 Error ```Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/rust_1.49.0_aarch64.deb  Error reading from server - read (5: I/O error) [IP: 52.89.173.169 443]  

Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?```  

To reproduce: just type "pkg install rust" 
 Termux version 0.106 downloaded from f-droid

**Comment by Grimler91** [comment]
For some reason you cannot access the bintray server. Try through a(nother) wifi, or switching repo with `termux-change-repo`.

**Comment by xeffyr** [comment]
@Grimler91 That's a Bintray hosting issue which does not related to client network quality. I have it sometimes as well.

**Comment by Haiz14** [comment]
Thanks @xeffyr  how long did you wait. I am a beginner currently and any error takes the life out of me.
