### ISSUE TITLE
julia language

### ISSUE THREAD

**Issue by l1t1** [termux/termux-packages#6380]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [ x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

a high performance language like python
**Link to home page and sources**

1. Home page: https://julialang.org/
2. Source code:  https://github.com/JuliaLang/julia

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
Available in community repo: https://wiki.termux.com/wiki/Package_Management#Community_repositories

**Comment by l1t1** [comment]
sorry, could you tell me the package name and install method?

**Comment by xeffyr** [comment]
```
curl -LO https://its-pointless.github.io/setup-pointless-repo.sh
bash setup-pointless-repo.sh
apt update
apt install julia
```

**Comment by l1t1** [comment]
thanks a lot
