### ISSUE TITLE
Rust Lang update from version 1.49.0  to 1.50.0

### ISSUE THREAD

**Issue by amm834** [termux/termux-packages#6381]
There is no  `rustup` tool chain in termux.
So , I can't update it.

**Resource Link **
https://blog.rust-lang.org/2021/02/11/Rust-1.50.0.html

**Comment by buttaface** [comment]
It wouldn't work anyway, as [updating Rust for Termux often requires tweaking or small patches](https://github.com/termux/termux-packages/commits/master/packages/rust). Feel free to submit a pull if you want it updated, these packages are maintained by the community.

**Comment by amm834** [comment]
When I upgraded the rust package it is still 1.49.0.

```sh
~ rustc --version
rustc 1.49.0

~ cargo --version
cargo 1.49.0
```

**Comment by Grimler91** [comment]
@amm834 all mirrors have not been updated yet.

**Comment by amm834** [comment]
> @amm834 all mirrors have not been updated yet.

Aww ok
