### ISSUE TITLE
Neovim cannot load a Lua module with a C library on Android

### ISSUE THREAD

**Issue by kanreki** [termux/termux-packages#6383]
Neovim's help text says that Lua version 5.1 is built in. And [this FAQ](https://github.com/neovim/neovim/wiki/FAQ#why-lua-51-instead-of-lua-53) seems to say that this cannot easily be changed.

However, a few points seem to indicate version 5.3:

- the TERMUX_PKG_DEPENDS and LUA_INCLUDE_DIR in the build.sh of Termux's neovim package name version 5.3
- if I run `:lua print(_VERSION)` from within a running Neovim, it says "Lua 5.3"
- some library facilities newly introduced in Lua 5.3 seem to be present (e.g., `string.pack` or `table.move`)

**Problem description:**

I was hoping to use the "lsqlite3" LuaRocks package in Neovim. But when I try to "require" it, I get this error:

```
dlopen failed: cannot locate symbol "lua_rotate" referenced by "/data/data/com.termux/files/usr/lib/lua/5.3/lsqlite3.so".
```
I know that `lua_rotate` was also introduced in Lua version 5.3, which is what makes me wonder about the version question.

The `lsqlite3` package does work if I invoke it outside of Neovim, in a (mostly) plain Lua 5.3 installation (I did need to create a symlink as described in #5958).

**Steps to reproduce**
Install packages neovim, lua53, and luarocks.

Install the following symlink:

```
% ls -l $PREFIX/bin/lua
lrwxrwxrwx 1 u0_a67 u0_a67 18 Feb  7 12:42 /data/data/com.termux/files/usr/bin/lua -> lua5.3
```

Install the "lsqlite3" package as follows:

```
% luarocks install lsqlite3
```
From within a running Neovim, issue the command `:lua s=require("lsqlite3")`

**Expected behavior**
The "require" call should load and return the module, and not fail with an error.

**Additional information**

```
% termux-info
Packages CPU architecture:
i686
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
Updatable packages:
git/stable 2.30.1 i686 [upgradable from: 2.30.0]
termux-tools/stable 0.107 all [upgradable from: 0.104]
Android version:
9
Kernel build information:
Linux localhost 3.18.0-20591-gf51c8e8d99f2 #1 SMP PREEMPT Thu Feb 4 19:48:24 PST 2021 i686 Android
Device manufacturer:
Google
Device model:
HP Chromebook 13 G1
```

**Comment by xeffyr** [comment]
dlopen issue can be related to https://github.com/android/ndk/issues/201.

**Comment by kanreki** [comment]
Duplicate of android/ndk#201

**Comment by kanreki** [comment]
Thank you, @xeffyr
