### ISSUE TITLE
possibility to downgrade ruby to 2.7

### ISSUE THREAD

**Issue by calheiros** [termux/termux-packages#6391]
After updating ruby ​​to 3.0.0 many tools stopped working  due to lack of support.

**metasploit**:
![20210212_130908](https://user-images.githubusercontent.com/20629241/107792292-b9a09280-6d33-11eb-851e-f407fd27edf0.jpg)

 **wpscan**: 
![20210212_130852](https://user-images.githubusercontent.com/20629241/107792207-9d9cf100-6d33-11eb-9cf9-1c2c949c611e.jpg)

Updating ruby ​​only caused me disadvantages so far.

Additional information:
```
termux-info
Packages CPU architecture:                        
arm                                               
Subscribed repositories:                          
# sources.list
deb https://termux.org/packages/ stable main 
# game-repo (sources.list.d/game.list)            
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# unstable-repo (sources.list.d/unstable.list)
deb https://ipfs.io/ipns/k51qzi5uqu5dj05z8mr958kwvrg7a0wqouj5nnoo5uqu1btnsljvpznfaav9nk unstable main
# sources.list.d/holehan.list
deb https://termux.holehan.org/ termux extras     
# sources.list.d/termuxblack.list
deb https://hax4us.github.io/TermuxBlack/ termuxblack main                                          
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.186-20807053 #1 SMP PREEMPT Wed Jan 20 00:14:52 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A015M

```

**Comment by xeffyr** [comment]
So far I see things which were recently purged from unstable-repo.

You can try to compile ruby2.7 on your own.

***

Eventually, everyone will switch to 3.0.0. https://github.com/rapid7/metasploit-framework/issues/14666

**Comment by Hax4us** [comment]
@calheiros i uploaded ruby 2.x temporary in https://github.com/hax4us/Termuxblack
you can install it from there

**Comment by calheiros** [comment]
@Hax4us thank you man I will try.

**Comment by Advaithvp** [comment]
THANKS A LOT MAN @Hax4us
