### ISSUE TITLE
grep not working on non-ascii characters

### ISSUE THREAD

**Issue by happyme531** [termux/termux-packages#6401]
**Problem description**

**Steps to reproduce**

1. Execute these commands  
```
echo '123' |grep '1'
echo 'アイウ' |grep 'ア'
echo '😁😂😃' |grep '😁'
echo '♤♤♤' |grep '♤'
echo '一二三' |grep '一'
```
2. Only 123 is printed.  

**Expected behavior**

Got all the strings printed.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.112-perf #1 SMP PREEMPT Wed Feb 19 12:58:15 KST 2020 aarch64 Android
Device manufacturer:
LGE
Device model:
LM-G710
```

**Comment by WMCB-Tech** [comment]
it should be work fine with `-P` flag if emojis

![Screenshot_2021-02-14-18-17-06-60.jpg](https://user-images.githubusercontent.com/65075766/107873918-d365e500-6ead-11eb-9938-c8039c8f3a49.jpg)

According to `man grep`

> Interpret PATTERNS as Perl-compatible regular expressions (PCREs).  This option is experimental when combined with the -z (--null-data) option, and grep -P may warn of unimplemented features.

**Comment by happyme531** [comment]
Well, grep -P works fine.  
Although on ubuntu it works without -P flag.
