### ISSUE TITLE
 Google from the terminal 

### ISSUE THREAD

**Issue by selvodka** [termux/termux-packages#6407]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description
 Google from the terminal 

**Link to home page and sources**

1. Home page: https://github.com/jarun/googler/
2. Source code: https://github.com/jarun/googler/

**Comment by RossComputerGuy** [comment]
It's a python program, won't be added

**Comment by landfillbaby** [comment]
pkg i python clang
    pip install googler
