### ISSUE TITLE
ERROR: Unable to find executable (YouCompleteMe)

### ISSUE THREAD

**Issue by widhisec** [termux/termux-packages#6408]
I want to install this, how come there is a problem like this, please translation
![IMG_20210215_234140](https://user-images.githubusercontent.com/39062772/107973402-c2b98a00-6fe7-11eb-84d2-c46a14aab79b.jpg)

**Comment by RossComputerGuy** [comment]
Install NodeJS and NPM

**Comment by xeffyr** [comment]
`pkg install nodejs`
