### ISSUE TITLE
Strange error in vim

### ISSUE THREAD

**Issue by coolplay** [termux/termux-packages#641]
I like termux and sometimes need to ssh into my Android device to modify scripts in Vim. Every time I hit `i` to enter insert mode, strange characters pop up at the bottom, as shown below:
![hit_i](https://cloud.githubusercontent.com/assets/3982705/21581229/c9e0b7cc-d063-11e6-998e-0a7d51e31130.png)
And when I hit `ESC` to switch to normal mode, strange characters also appear at the top of screen, which looks like this:
![hit_esc](https://cloud.githubusercontent.com/assets/3982705/21581230/cdcdaab6-d063-11e6-878b-c96b91c71b28.png)

Any idea what is going on here? Many thanks!

**Comment by fornwall** [comment]
Which terminal emulator are you using?

I guess the problem is that `$PREFIX/share/vim/vimrc` sets the following to enable cursor shapes:

    let &t_SI = "\<Esc>[6 q"
    let &t_SR = "\<Esc>[4 q"
    let &t_EI = "\<Esc>[2 q"

and that the terminal emulator in your screenshot does not support setting cursor shapes? Perhaps it's saftest not setting these by default.

**Comment by fornwall** [comment]
This has now been fixed in the latest package version of vim - update to it with:

    apt update && apt upgrade

**Comment by coolplay** [comment]
OK, that fixes the problem. BTW, I use [Guake](http://guake.org/) terminal.
