### ISSUE TITLE
Package request: nasm

### ISSUE THREAD

**Issue by Cvar1984** [termux/termux-packages#6414]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [ ✅] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

A cross-platform x86 assembler with an Intel-like syntax
**Link to home page and sources**

1. Home page: [home](https://nasm.us)
2. Source code: [git repo](https://github.com/netwide-assembler/nasm)

**Additional information**
Have you compiled or tried to compile the package on device?

**I never try to compile nasm on termux**

**Comment by buttaface** [comment]
Added with #6434.
