### ISSUE TITLE
Mirror Issue

### ISSUE THREAD

**Issue by MysteryBoyxD** [termux/termux-packages#6420]
I'm trying to install packages but I couldn't. Here's what happens everytime.... 

When I try pkg install python. Here's the error which comes with every trial of installing any package. 
![Screenshot_2021-02-18-15-39-18-75](https://user-images.githubusercontent.com/77355077/108341256-7e083b80-71ff-11eb-91b7-0b1ece40771c.jpg)
Availability of every mirror shows bad. 

I tried apt update too. Throws error. (apt upgrade works fine though.) 
![Screenshot_2021-02-18-15-38-04-23](https://user-images.githubusercontent.com/77355077/108341485-b27bf780-71ff-11eb-91ad-34c3ade33bd4.jpg)

I tried pkg update as well. Same as apt update it doesn't work. 
It's worked few days ago. I tried uninstalling and reinstalling termux, but it shows all this. Am I missing something or it's a bug?

**Comment by WMCB-Tech** [comment]
Termux Repositories have been moved from bintray to ipfs, and it seems your Installation is fairly outdated, you may change repo using `termux-change-repo` and try `grimler.se` or TUNA mirrors then update your Installation

**Comment by xeffyr** [comment]
@WMCB-Tech OP doesn't have access to **every** repository, including Bintray and `grimler.se`.

Clearly device networking issue. Closing.
