### ISSUE TITLE
Package request: hwloc

### ISSUE THREAD

**Issue by purofle** [termux/termux-packages#6422]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

**Link to home page and sources**

1. Home page: https://www.open-mpi.org/projects/hwloc/
2. Source code: https://download.open-mpi.org/release/hwloc/v2.3/hwloc-2.3.0.tar.gz

**Additional information**
Have you compiled or tried to compile the package on device?
No

**Comment by Saikatsaha1996** [comment]
I am install successfully hwloc package in termux..
But lf you want to install this package .. u must be rooted...

After that..
git clone https://github.com/open-mpi/hwloc.git
./autogen.sh

./configure --prefix=$PREFIX
make -j$(nproc)
make install -j$(nproc)
