### ISSUE TITLE
Package request: ascii manpage

### ISSUE THREAD

**Issue by eda-abec** [termux/termux-packages#6423]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description
Not really a package, only a manpage for ASCII - can be a useful reference.

**Link to home page and sources**
1. Home page: https://man7.org/linux/man-pages/man7/ascii.7.html
2. Source code: https://www.kernel.org/doc/man-pages/download.html

**Additional information**
Have you compiled or tried to compile the package on device?
No.

**Comment by xeffyr** [comment]
```
pkg install manpages
man ascii
```
