### ISSUE TITLE
debootstrap dies

### ISSUE THREAD

**Issue by ghistes** [termux/termux-packages#6424]
Hi,

I am running termux 0.106 installed from F-Droid on my Motorola G8 (Android 10).

I have tried to setup a debian-environment like so:

    debootrap --arch=arm64 --exclude=systemd stable debian-stable http://ftp.debian.org/debian

But after installing some packages debootstrap exits with this error:

I: Extracting libacl1...
E: Tried to extract package, but file already exists. Exit...

The exact same error happens when I try to install debian testing - it seems to me debootrap is somehow broken.

**Comment by ghistes** [comment]
No. This error occured on a brand new installation on a new phone.
When I delete the directory (or try another directory to install in) and try again it runs into this problem again.
On my phone 100% reproducible.

**Comment by WMCB-Tech** [comment]
I've never encountered this before but it i was able to reproduce it and yeah got the same error, the debootstrap log shows that the tar cannot change mode and fails

![Screenshot_2021-02-20-10-40-03-92.jpg](https://user-images.githubusercontent.com/65075766/108580803-11875c80-7325-11eb-82e8-60ecb6118ddc.jpg)

**Comment by alou-S** [comment]
Funnily enough I have the exact same error which trying to set up Debian.
![image](https://user-images.githubusercontent.com/73123610/108604403-ba8c9080-73d3-11eb-95db-1befd04150d1.png)

Command used
`debootstrap stable ./debian-rootfs http://deb.debian.org/debian/`

Termux v0.106 
Samsung M01 
Android 10

**Comment by ghistes** [comment]
This is the error that shows up in the debootstrap log:

    tar: ./usr/lib/aarch64-linux-gnu/libacl.so.1: Cannot change mode to rwxr-xr-x: Operation not permitted
    tar: Exiting with failure status due to previous errors

**Comment by xeffyr** [comment]
> tar: ./usr/lib/aarch64-linux-gnu/libacl.so.1: Cannot change mode to rwxr-xr-x: Operation not permitted

Then this is related to https://github.com/termux/termux-packages/issues/5932. Closing as duplicate.

Can be workarounded by modifying distribution configs of `debootstrap` like shown in https://github.com/termux/termux-packages/issues/5932#issuecomment-709259667, but unfortunately the next error will arise, now with `initctl`.
