### ISSUE TITLE
Squid doesn't work in Termux

### ISSUE THREAD

**Issue by wuchuwei** [termux/termux-packages#6427]
termux version :0.106
The child thread receives a kill signal

2021/02/20 21:13:57.946| 24,9| src/sbuf/MemBlob.cc(82) ~MemBlob: destructed, this=0x786fad7840 id=blob569 capacity=40 size=6                                   2021/02/20 21:13:57.946| 24,7| src/sbuf/SBuf.cc(865) reAlloc: SBuf112 new store capacity: 40              2021/02/20 21:13:57.946| 28,3| src/acl/InnerNode.cc(57) lineParse: looking for ACL all                    2021/02/20 21:13:57.946| 28,9| src/acl/Acl.cc(96) FindByName: ACL::FindByName 'all'                       2021/02/20 21:13:57.946| 45,9| src/cbdata.cc(256) cbdataInternalAlloc: Allocating 0x786fa93318            Segmentation fault

**Comment by wuchuwei** [comment]
my system is android 10

**Comment by xeffyr** [comment]
Have you done any manual configuration or it crashes with default config?

**Comment by wuchuwei** [comment]
I use the default configuration.

> 您是否进行了任何手动配置，否则使用默认配置会崩溃？

**Comment by wuchuwei** [comment]
All processes cannot run in Deamon mode.
Squid -N works just fine

**Comment by xtkoba** [comment]
Please share the `termux-info` output.

**Comment by xtkoba** [comment]
This issue is marked as obsolete. Please open a new issue if you encounter similar problem. Thanks.
