### ISSUE TITLE
grep and sed stopped handling non-ASCII patterns

### ISSUE THREAD

**Issue by bigConifer** [termux/termux-packages#6429]
**Problem description**
When running `grep` or `sed` with patterns containing a non-ASCII character, then no matches will be found in the text.
The same issue was reported in [#6401](https://github.com/termux/termux-packages/issues/6401) last week.
So I've checked old versions and found that this bug was introduced in termux v0.92 (almost exactly one year ago). 
In prior versions it worked as expected!

**Steps to reproduce**
<p>
  <img src="https://user-images.githubusercontent.com/64743731/108609719-1f45ec00-73d0-11eb-9a62-c1fc295cbf10.jpg" width="45%" />
  <img src="https://user-images.githubusercontent.com/64743731/108609739-4d2b3080-73d0-11eb-99bd-371287ac8a00.jpg" width="45%" /> 
  </br></br>
  I've executed these commands each in a clean Termux <b>without upgrading the packages</b> (resp. only with <code>perl</code> installed).
</p>

**Expected behavior**
In other environments `grep` and `sed` have no problems with non-ASCII characters inside regular expressions. 
Workarounds using `perl` or perl-regexp are normally not necessary and in some cases not feasible at all.

**Additional information**
```
LANG=en_US.UTF-8

Packages architecture: 
arm
Android version: 
9
```

**Comment by bigConifer** [comment]
Maybe it was caused by a commit like this [970391d](https://github.com/termux/termux-packages/commit/970391d6abfb4efc1bde95bc1865d50a2894eb07) (build-essential: keep bare minimum in dependencies & move others to recommends).

**Comment by xeffyr** [comment]
> Maybe it was caused by a commit like this 970391d (build-essential: keep bare minimum in dependencies & move others to recommends).

Nothing to do with `build-essential` package. This package and its dependencies are not involved into cross-compilation.

**Comment by landfillbaby** [comment]
it's a gnulib issue... looking into it...

**Comment by bigConifer** [comment]
@xeffyr, @landfillbaby, not sure if this one is related, but what about  https://github.com/termux/termux-packages/commit/b20be8a11576b65584eebfd17feda1025f4b1f1f (docker image: install locales and configure en_US.UTF-8 as default)?
Is there a reason, why the locale was changed back and forth (https://github.com/termux/termux-packages/commit/88183689efb3715ac0192006cabad6337dea2588, https://github.com/termux/termux-packages/commit/65512d6058693505a3615418bdc21de6b3c485cd)?

**Comment by bigConifer** [comment]
@xtkoba, I think at least https://github.com/termux/termux-packages/issues/6341 can be closed if no one else is able to reproduce it.

**Comment by xtkoba** [comment]
I have noticed that this behavior disappears from `sed` when `configure`d with `--host=aarch64-linux` (instead of `--host=aarch64-linux-android`).

There are several confvars that may be guessed differently for `*-android` host.

For `sed`:

```
$ grep -A 1 -- -android sed-4.8/configure | grep -v "# Guess "
            linux*-android*) gl_cv_func_memchr_works="guessing no" ;;
--
           *-android*)    gl_cv_func_ungetc_works="guessing yes" ;;
--
          *-android*)    gl_cv_pthread_rwlock_rdlock_prefer_writer="guessing no" ;;
--
              linux*-android*) gl_cv_func_wcrtomb_works="guessing no";;
--
           *-android*) # implemented using dup3(), which fails if oldfd == newfd
             gl_cv_func_dup2_works="guessing no" ;;
--
              linux*-android*) gl_cv_func_setlocale_works="guessing no";;
```

For `grep`:

```
$ grep -A 1 -- -android grep-3.7/configure | grep -v "# Guess "
          linux*-android*) gl_cv_func_memchr_works="guessing no" ;;
--
           linux*-android*)      gl_cv_func_snprintf_retval_c99="guessing yes";;
--
           linux*-android*)      gl_cv_func_snprintf_truncation_c99="guessing yes";;
--
         *-android*) # implemented using dup3(), which fails if oldfd == newfd
           gl_cv_func_dup2_works="guessing no" ;;
--
          *-android*)    gl_cv_pthread_rwlock_rdlock_prefer_writer="guessing no" ;;
--
              linux*-android*) gl_cv_func_wcrtomb_works="guessing no";;
--
              linux*-android*) gl_cv_func_setlocale_works="guessing no";;
--
           linux*-android*) gl_cv_func_snprintf_size1="guessing yes" ;;
--
           linux*-android*) gl_cv_func_printf_positions="guessing yes";;
```

I guess some of them affect the behavior. I'm going to narrow them down.
