### ISSUE TITLE
This is mistake?  tor does not work help

### ISSUE THREAD

**Issue by VZLOMSHIKSAN4EK** [termux/termux-packages#6433]
after entering the command 
$ tor
Feb 21 12:08:30.377 [notice] Tor 0.4.4.7 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1i, Zlib 1.2.11, Liblzma 5.2.5, and Libzstd N/A.
Feb 21 12:08:30.377 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 21 12:08:30.380 [notice] Configuration file "/data/data/com.termux/files/usr/etc/tor/torrc" not present, using reasonable defaults.
Feb 21 12:08:30.391 [notice] Opening Socks listener on 127.0.0.1:9050
Feb 21 12:08:30.391 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
Feb 21 12:08:30.391 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
Feb 21 12:08:30.391 [err] Reading config failed--see warnings above.

does it work? or not? please tell me!

**Comment by VZLOMSHIKSAN4EK** [comment]
Or tell me who knows ..

**Comment by xeffyr** [comment]
Seems like you are starting another instance or it's port is already in use by something else.

Normally you should see this when it is running:
![Screenshot_20210221-122824](https://user-images.githubusercontent.com/25881154/108622277-548a2280-7440-11eb-8d00-749acb7a87a3.png)

**Comment by VZLOMSHIKSAN4EK** [comment]
then what instance do you need to run? and tell me how to run correctly?

**Comment by xeffyr** [comment]
Force stop Termux app, just to ensure that no other `tor` instances are running. Then ensure you are not running Orbot, Tor Browser or similar application. And only then open Termux and type `tor`.

**Comment by VZLOMSHIKSAN4EK** [comment]
![IMG_20210221_131747](https://user-images.githubusercontent.com/75779087/108623354-4ab7ed80-7447-11eb-8da4-66aff30b8aae.jpg)
strangely, I went out and went back to the termux and entered the command tor and it all worked, so it should be?
