### ISSUE TITLE
Package request Vala Compiler

### ISSUE THREAD

**Issue by radare** [termux/termux-packages#644]
There's clang and glib already packaged, so valac should build fine without any other dependency.

link to source http://download.gnome.org/sources/vala/0.34/vala-0.34.4.tar.xz

**Comment by vishalbiswas** [comment]
Compiles on device. But, I don't think there's s need for this package.

**Comment by radare** [comment]
Why not? It is as important as any other compiler, do you want to remove go and gcc too?

**Comment by vishalbiswas** [comment]
gcc is not available. Go has more demand.
Vala is mostly focussed on Gtk.
I added the package, but I'm not sure if its perfect. Never really used it myself before now.

**Comment by fornwall** [comment]
@radare I also thought vala was mostly for Gtk, but do you now of command-line using it?

**Comment by radare** [comment]
yes, valabind, frida, posixvala, gtkaml, libgee, tiv (terminal image viewer), ...

i have also written a bunch of gstreamer tools and plugins in vala too

**Comment by radare** [comment]
You can use vala without glib or without gtk. Vala is just a c# like language that transpiles to c. There are commandline tools and libraries written in it. I use vala since the very first days and i think its a neat language and compiler, having less demand than go doesnt sounds like a reason for not including it.

The package looks good to me. Thanks! Lets see if it gets merged

**Comment by fornwall** [comment]
@radare Ok thanks for the info. The valac package is now available in the package repository.

I guess we should look at adding a gstreamer package?

**Comment by radare** [comment]
i’ve pinged some fluendo peeps for that, yeah it will be great :)

**Comment by radare** [comment]
Uhm, looks like the package is missing some dependencies: clang, pkg-config, glib-dev

**Comment by fornwall** [comment]
@radare Thanks, the dependencies has been added in the updated `0.34.4-1` version of the package!

**Comment by vishalbiswas** [comment]
I usually check packages.ubuntu.com and packages.archlinux.org for dependencies of a package. 
Both didn't list these (or gcc) as required or optional dependencies.

**Comment by radare** [comment]
try to compile a hello world in vala:

```
void main() {
  stdout.printf(“Hello World\n”);
}
```

vala needs pkg-config for its —pkg and to be able to link against glib, also the generated code is compiled with a C compiler, so clang is needed. Debian doesnt adds those as dependencies because valac can be used as a C preprocessor, this is… just using valac -C to create C code out of the Vala one and then manually call gcc on that.

I guess that reduces the amount of packages needed to add in the the build system when packaging stuff, but from the user point of view, those packages will be needed to build anything generated by vala. it depends on how we see vala in termux… as a compiler or a preprocessor..
