### ISSUE TITLE
pip install numpy i facing this problems

### ISSUE THREAD

**Issue by sahads** [termux/termux-packages#6440]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by sahads** [comment]
$ pip install numpy
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/d2/48/f445be426ccd9b2fb64155ac6730c7212358882e589cd3717477d739d9ff/numpy-1.20.1.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmp2mglcho1
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-kzpvg02l/numpy
    Complete output (217 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_mt19937.pyx
    Processing numpy/random/_generator.pyx
    Processing numpy/random/_philox.pyx
    Processing numpy/random/_bounded_integers.pyx.in
    Processing numpy/random/_common.pyx
    Processing numpy/random/_sfc64.pyx
    Processing numpy/random/bit_generator.pyx
    Processing numpy/random/_pcg64.pyx
    Processing numpy/random/mtrand.pyx
    Cythonizing sources
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['/data/data/com.termux/files/usr/lib']
      NOT AVAILABLE

    atlas_blas_threads_info:

**Comment by RossComputerGuy** [comment]
Check the closed issues before just opening a new issue. You need to install the libraries it says that aren't installed.

**Comment by sahads** [comment]
how i install that libraries
command please.

**Comment by sahads** [comment]
![Uploading Screenshot_2021-02-22-11-02-02.png…]()

**Comment by sahads** [comment]
help why this happening

**Comment by RossComputerGuy** [comment]
You need to use `pkg install` to install the libraries the error message references.

**Comment by sahads** [comment]
what is the diffrence from "pip" "pkg"

**Comment by RossComputerGuy** [comment]
`pip` is for Python, `pkg` is a frontend to `apt` that makes package installing actually work

**Comment by sahads** [comment]
pkg install numpy working.
but still not works pip install numpy.
i want numpy for instabot package.

**Comment by RossComputerGuy** [comment]
Well you need to install the dependencies that numpy needs which isn't available from `pip`.

**Comment by sahads** [comment]
always this

**Comment by sahads** [comment]
what is the depwndies
how to solve

**Comment by sahads** [comment]
pkg install worked

**Comment by RossComputerGuy** [comment]
The dependencies are shown in the error message.

**Comment by sahads** [comment]
you know this package "pip install instabot"

numpy in instabot package

no way to get numpy dependies ?

**Comment by RossComputerGuy** [comment]
Well, idk what to do then. You'll have to figure it out yourself.

**Comment by landfillbaby** [comment]
```bash
curl -LO https://its-pointless.github.io/setup-pointless-repo.sh
bash setup-pointless-repo.sh
pkg i numpy```

**Comment by sahads** [comment]
i need numpy in pip.

pkg install numpy working

but pip install numpy not working

**Comment by landfillbaby** [comment]
if it's because you're using a venv, just copy it from your $PREFIX/lib/python3.9/site-packages over into the venv's site-packages

**Comment by sahads** [comment]
what i copied bro idont understand

and i am superuser
i can manage termux files

**Comment by sahads** [comment]
and mine python 3.8

**Comment by sahads** [comment]
i got this zip file
where i extract this zip

**Comment by landfillbaby** [comment]
oh ok, that's your problem then. unless you have a specific reason to stay on 3.8, run `pkg up` to update to 3.9.1 (although i've just submitted an update to 3.9.2 so maybe wait)
if you do need to stay on 3.8 then run `pkg i numpy=1.19.0` because that's the last version its-pointless built for 3.8
