### ISSUE TITLE
从 0.105版本后，无法使用termux播放音频  Cannot use termux to play audio after version 0.105

### ISSUE THREAD

**Issue by xc1984759471** [termux/termux-packages#6444]
**Problem description**

当我启动termux的pulseaudio时，使用linux系统连接时，系统会识别为伪输出，播放音频完全无声
使用play-audio播放音频，就会提示“CANNOT LINK EXECUTABLE "play-audio": cannot locate symbol "CrcGenerateTable" referenced by "/system/lib64/libunwindstack.so"...”
When I start pulseaudio of termux, when I use the linux system to connect, the system will recognize it as a DUMMY output, and the playback audio is completely silent
Use play-audio to play audio, it will prompt "CANNOT LINK EXECUTABLE "play-audio": cannot locate symbol "CrcGenerateTable" referenced by "/system/lib64/libunwindstack.so"..."

**Additional information**

* Termux application version:0.105 and above
* Android OS version:10 (MIUI 12)
* Device model:Redmi Note 7 Pro

**Comment by ChiefMikeK** [comment]
## Please update to latest_release_version _0.108_ ⤵

- [Termux | F-Droid](https://f-droid.org/en/packages/com.termux/)

**Comment by xc1984759471** [comment]
Tried, this bug is found from 0.105 to 0.108

**Comment by xeffyr** [comment]
"bug" is not related to application version.

Seems you have set LD_LIBRARY_PATH at some point. That variable is not supported anymore, since we started to use API level 24 to compile packages long time ago. Remove all occurrences of that variable in your she'll configuration files.

![Screenshot_20210225-114750](https://user-images.githubusercontent.com/25881154/109135024-51a07200-775f-11eb-875a-b6f4a5105e2a.png)

**Comment by ChiefMikeK** [comment]
## Please ask for assistance with troubleshooting on Reddit  
then close this after you have an answer 🖒
- https://www.reddit.com/r/termux/  
- ¿ "`I use the linux system to connect`" ?   
- which linux disto are you using 
- Google translate can help with your Japanese Kanji to English text _copy-paste_

**Comment by xc1984759471** [comment]
非常感谢，已经解决，经过检查后发现LD_LIBRARY_PATH确实有所变动，执行unset LD_LIBRARY_PATH就解决了
Thank you very much. It has been resolved. After checking, it is found that LD_LIBRARY_PATH has indeed changed. Executing unset LD_LIBRARY_PATH will solve it.
