### ISSUE TITLE
Request package: Bleachbit

### ISSUE THREAD

**Issue by Gurren-Joestar** [termux/termux-packages#6448]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

GUI cleaner lightweight sofware with CLI capabilities

**Link to home page and sources**

1. Home page: https://www.bleachbit.org/
2. Source code: https://github.com/bleachbit/bleachbit

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
error binding text domain                               Traceback (most recent call last):                        File "/data/data/com.termux/files/home/bleachbit/bleachbit/__init__.py", line 216, in <module>                    locale.bindtextdomain('bleachbit', locale_dir)      OSError: [Errno 22] Invalid argument                    Traceback (most recent call last):                        File "/data/data/com.termux/files/home/bleachbit/bleachbit.py", line 43, in <module>                              import bleachbit.GUI                                  File "/data/data/com.termux/files/home/bleachbit/bleachbit/GUI.py", line 25, in <module>                          from bleachbit import GuiBasic                        File "/data/data/com.termux/files/home/bleachbit/bleachbit/GuiBasic.py", line 28, in <module>                     import gi                                           ModuleNotFoundError: No module named 'gi'
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
Won'tfix: we tend not to add python packages, especially referencing modules which can't be packaged (here: python-gobject).
