### ISSUE TITLE
Package or service request: Docker

### ISSUE THREAD

**Issue by sobaee** [termux/termux-packages#6449]
Since it's possible to have docker in termux by using qemu and alpine linux, I thought you may do something to convert docker for us to be able to use it in termux for aarch64 system.
You did that before sometime with "libzim" and it was only available with linux x86-64.

Could you please try with docker!!

**Comment by xeffyr** [comment]
Docker is already available in `root-repo`. Note that it will require a custom kernel with necessary drivers enabled.

Some info about using Docker on Android (Termux): https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27

**Comment by sobaee** [comment]
One question my dear developer:

Should I root my device to have custom kernel with necessary drivers enabled?

And is this custom kernal available for samsung note 8 android pie?

**Comment by Grimler91** [comment]
@sobaee did you read the guide? The fifth sentence starts with "Bear in mind that you'll have to root your phone", so yes, you need to root your device.

There are many available custom kernels for your device over at [xda](https://forum.xda-developers.com/f/samsung-galaxy-note-8-roms-kernels-recoveries.6801). Pick one and download the sources, do the modifications in mentioned in the guide and then compile it. There are many guides available online for how to compile kernels that you can look at.
