### ISSUE TITLE
Package request: blades

### ISSUE THREAD

**Issue by mumu-lhl** [termux/termux-packages#6451]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

Blazing fast dead simple static site generator

**Link to home page and sources**

1. Home page: https://www.getblades.org/
2. Source code: https://github.com/grego/blades

**Additional information**
Have you compiled or tried to compile the package on device?
* I did not encounter any problems when compiling the package.

**Comment by amm834** [comment]
```bash
pkg install rust
```
Export `cargo` path
```bash
nano .zshrc
```
Add
```
export PATG=$HOME/.cargo/bin:$PATH
```
Restart by
```bash
source .zshrc
# install blades
cargo install blades
```

**Comment by thunder-coding** [comment]
From CONTRIBUTING.md

> Packages must NOT be a part of language-specific ecosystem. These packages are installable through cpan, gem, npm, pip and similar.

You can now close this issue @mumu-lhl
