### ISSUE TITLE
install pip

### ISSUE THREAD

**Issue by momo0515** [termux/termux-packages#6454]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [ ] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

installing pip
**Link to home page and sources**

1. Home page:pip
2. Source code:pkg install pip

*unable to locate pakage pip

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by WMCB-Tech** [comment]
Pip is already available with the package `python`
