### ISSUE TITLE
Info: "E: Repository .. changed its .. value from 'Bintray' to .."

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#6455]
Now that we are moving away from bintray apt will notify you that the repository metadata information changed, and ask if you accept the changes. Please press yes to be able to receive updates in the future.

The full message might look something like:

```
E: Repository 'https://grimler.se/termux-root-packages-24 root InRelease' changed its 'Origin' value from 'Bintray' to 'termux-root-packages-24 root'
E: Repository 'https://grimler.se/termux-root-packages-24 root InRelease' changed its 'Label' value from 'Bintray' to 'termux-root-packages-24 root'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N] 
```

Apt will ask you once for each repository that has had its information changed.

**Comment by agnostic-apollo** [comment]
Change repo mirror.

https://github.com/termux/termux-packages/wiki/Package-Management
