### ISSUE TITLE
Unable to locate iwconfig



### ISSUE THREAD

**Issue by jomarreyes** [termux/termux-packages#6456]
![Screenshot_20210225_210354.jpg](https://user-images.githubusercontent.com/79584461/109158460-5b9d9180-77ae-11eb-9128-2048222e5c0d.jpg)

hey guys can you help me this problem 

Thank youuu

**Comment by jomarreyes** [comment]
I cant install iwconfig even i always use apt update for solve problem but after i apt update then i install iwconfig is not working and show the unable to locate package.

Can you teach me how to solve this problem?

**Comment by xeffyr** [comment]
Should be in wireless-tools in root-repo.

**Comment by Grimler91** [comment]
There is no package called iwconfig. There is a program called iwconfig in the package wireless-tools though.

**Comment by jomarreyes** [comment]
but i try apt install wireless-tools nothing happened and show the unable to locate package bro can you teach me how to solve the problem

**Comment by Grimler91** [comment]
See root-repo README: https://github.com/termux/termux-root-packages#subscribing-to-the-repository
