### ISSUE TITLE
[Question] Which package will let me run lspci?

### ISSUE THREAD

**Issue by krafi99** [termux/termux-packages#6459]
_As the title says_

**Comment by RossComputerGuy** [comment]
PCI devices aren't available on Android. They are common on x86 devices and since most Android devices are ARM, you won't need PCI. `pciutils` is the package that will have the command your looking for.

**Comment by xeffyr** [comment]
> PCI devices aren't available on Android.

This is not true.

You can get lspci command from `busybox`.
```
pkg install busybox
busybox lspci
```

**Comment by WMCB-Tech** [comment]
Not all devices will be able to use `lspci` command if SELinux was enforced
