### ISSUE TITLE
Error in starting up mining process

### ISSUE THREAD

**Issue by ochochevictor** [termux/termux-packages#6464]
I installed all the packages necessary and then I inputted the cd/bot...... line to link it to telegram and begin mining Bitcoin but it brought up an error message saying the hostname is not recognized. I attached a picture confirming this claim
![Screenshot_20210227-120526](https://user-images.githubusercontent.com/69669232/109388106-57d05300-7905-11eb-8915-d70b3e54ba3e.png)

**Comment by xeffyr** [comment]
No help with mining and clickbots here.
