### ISSUE TITLE
My Termux CANNOT LINK EXECUTABLE "php": library "libicuio.so.67" not found

### ISSUE THREAD

**Issue by REXX-dev** [termux/termux-packages#6470]
![Screenshot_20210301-032735](https://user-images.githubusercontent.com/79816772/109440656-fbd50e00-7a6d-11eb-90ee-0f6c9dbc68a0.jpg)

Any helpp ??

**Comment by Grimler91** [comment]
Make sure all your packages are up to date

**Comment by REXX-dev** [comment]
yes but i want to downgrade to php 7 ?

**Comment by Grimler91** [comment]
If you want another version then you need to compile that version yourself, either on device, or cross-compiling from our docker image

**Comment by TechniQTeam** [comment]
I think the issue has not been resolved yet because the same error appears even after compiling the desired PHP version by ourselves.

**Comment by xeffyr** [comment]
> I think the issue has not been resolved yet because the same error appears

Doesn't appears. You either compiled it in a wrong way or mean something different by "compiling".

**Comment by TechniQTeam** [comment]
Can you please Share the following 32-bit Library Dependencies needed for PHP7_i686: libicudata.so.67, libicui18n.so.67, libicuio.so.67 and libicuuc.so.67. 

My Termux needs the above 32-bit Library Dependencies for i686 architecture to install as well as run PHP7_i686 Successfully. Please help. Where can I find the required Library Dependencies for i686 architecture?

**Comment by harusakura924** [comment]
I also encountered this [problem](https://github.com/Termux-pod/termux-pod/issues/4).
I hope that termux can be upgraded and installed, and you can choose the version yourself, which will be more friendly.
