### ISSUE TITLE
Package request: usbutils

### ISSUE THREAD

**Issue by RussiaVk** [termux/termux-packages#6472]
I installed aircrack-ng and try run , it say : Please install lsusb from your distro's package manager. lsusb seem belong to package usbutils

**Comment by Saidsaib** [comment]
J'ai fait, qu'est-ce que je fais maintenant


في الاثنين، 1 مارس، 2021 09:09 RussiaVk <notifications@github.com> كتب:

**Comment by xeffyr** [comment]
You do not need usbutils to use aircrack-ng.

Everything you need: usb wifi stick, custom kernel with necessary drivers (for mac80211 stack and usb wifi stick chipset) and rooted device of course.

Use of airmon-ng is not necessary to get monitor mode. Utilities `iw` or `iwconfig` working flawlessly to enable it in case if any of mentioned requirements are met.
