### ISSUE TITLE
Why the built package can't work in the docker?

### ISSUE THREAD

**Issue by wingfancy** [termux/termux-packages#6474]
I built 'nano' binary with the command below in "termux/package-builder" docker:
```
 ./build-package.sh -a i686 nano
```
And I tried to run this binary but failed:
```
builder@8f1e13e3618b:/data/data/com.termux/files/usr/bin$ sudo ./nano
sudo: unable to execute ./nano: No such file or directory
```
And with the 'ldd' command to check this binnary:
```
builder@8f1e13e3618b:/data/data/com.termux/files/usr/bin$ ldd nano
./nano: error while loading shared libraries: /lib/i386-linux-gnu/libc.so: invalid ELF header
```
May I get your help on this issue? Thanks in advance.

**Comment by xeffyr** [comment]
Docker provides Ubuntu 20.04 amd64 installation. This is not Termux, neither this is Android. Obviously, built packages will not work here whenever the target CPU architecture matches the host one or not.

Termux build environment has not passed full bootstrap cycle like the typical one of the normal Linux distribution.

**Comment by xeffyr** [comment]
More details on Termux vs Linux distribution differences: https://wiki.termux.com/wiki/Differences_from_Linux

**Comment by wingfancy** [comment]
I see. Thanks so much for your info.
