### ISSUE TITLE
Basic problem regarding the application

### ISSUE THREAD

**Issue by ComeradeCharon** [termux/termux-packages#6476]
![Screenshot_20210301-212007_Termux](https://user-images.githubusercontent.com/79714322/109524702-d2040180-7ad6-11eb-8fa3-c82fd9961f8d.jpg)

**Comment by RossComputerGuy** [comment]
Try a different keyboard, if I remember correctly then some people using Samsung's keyboard have had issues before.

**Comment by ComeradeCharon** [comment]
Sir, 
Whenever I try to open the application it doesn't shows me the full keyboard though which I can write commands.....
It shows numeric keyboard...
Also I'm not able to install 'sh' package, whenever I try to do so it shows - couldn't locate package , error.....


Please help me to fix this problem...
Regards,
Termux user

**Comment by ComeradeCharon** [comment]
> Try a different keyboard, if I remember correctly then some people using Samsung's keyboard have had issues before.

Yeah....I'm using Samsung keyboard....

**Comment by RossComputerGuy** [comment]
That's why using a different keyboard can fix this. If your using Samsung's keyboard, you could have odd issues for whatever reason. In my experience, GBoard (Google's keyboard) and Hacker Keyboard has worked.

**Comment by xeffyr** [comment]
Keyboard bug.

Workarounds:
a. Open web browser and tap on address field, then go back to Termux.
b. Swipe to right "extra keys row" (widget with up/down arrows) and tap on it.
Both cases will reset keyboard type to default.

Persistent workaround as in https://wiki.termux.com/wiki/Terminal_Settings#Workaround_for_some_keyboards_issues:
```
mkdir -p ~/.termux
echo "enforce-char-based-input = true" >> ~/.termux/termux.properties
```
and restart the application.
