### ISSUE TITLE
can't read obb and data

### ISSUE THREAD

**Issue by superbonaci** [termux/termux-packages#6477]
**Problem description**

Trying to compress /sdcard/ with tar to external storage:
```
tar: Removing leading `/' from member names
tar: Removing leading `/' from member names
tar: /sdcard/./Android/obb: Cannot open: Permission denied
tar: /sdcard/./Android/data: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
```
I've run already `termux-setup-storage` and confirmed yes.

**Steps to reproduce**

1. cd to external storage
2. tar -cvf storage.tar /sdcard/.

**Expected behavior**

Work with all files.

**Additional information**

Android 11 on Galaxy S10

**Comment by superbonaci** [comment]
Note with other apps I can copy all of those files no root.

**Comment by agnostic-apollo** [comment]
It is expected behaviour on android 11, apps can no longer access `Android/data` and `Android/obb` directories of other apps (without extra permissions). Check termux/termux-app#1952 for details.

**Comment by superbonaci** [comment]
I see. Termux doesn't have the option to access those files because it's targeting Android 9 (API 28) instead of Android 12 (API 32).
So you are basically switching one functionality by another. Which is worse?

**Comment by agnostic-apollo** [comment]
No. Access is denied by default on android 11, regardless of target sdk. It's a new privacy feature by android OS. However, apps targeting sdk 29 (android 10) and below can temporarily bypass it by asking permission for `Android/data` using a SAF popup. When playstore mandates that all apps target sdk 30 in ~nov this year, even that access will be revoked.

For `Android/obb`, an app can get access by requesting `REQUEST_INSTALL_PACKAGES` in its `AndroidManifest.xml` which currently termux is not doing but can be considered. The user would explicitly need to grant the permission to termux by going to Termux `App Info` in Android Settings -> `Advance` -> `Install unknown apps`. Directory can be accessed with shell as well including creating new files, likely access of files of other apps is available as well, will need a game or something to test.

And we are not switching anything currently, targeting newer api versions increases restrictions, but still do plan on targeting sdk 30 in future. And android 12 was just released as preview, normal apps aren't targeting it.

**Comment by superbonaci** [comment]
Can't I just compile Termux myself modifying the target for 11 and get the job done?

**Comment by xeffyr** [comment]
@superbonaci Termux is broken on Android 10+. See issue #1072 which **is not resolved**.

**Comment by superbonaci** [comment]
@xeffyr can't we just blacklist unsupported packages? I don't use texlive.

**Comment by Grimler91** [comment]
Link was suppose to be https://github.com/termux/termux-app/issues/1072.

**Comment by agnostic-apollo** [comment]
>Can't I just compile Termux myself modifying the target for 11 and get the job done?

Targeting higher sdk versions doesn't allow access to `Android/data`. Targeting android 11 will even make the current SAF loophole useless.

**Comment by xeffyr** [comment]
@superbonaci Sorry, I have referenced wrong issue. Should be 1072 of termux-app, https://github.com/termux/termux-app/issues/1072, which is about limits on arbitrary code execution in application data.

**Comment by superbonaci** [comment]
You don't have to make the app Google Play Store compliant. Android plans to support third party stores, and if not provide the app here or website. Google may even forbid to publish entirely apps that are not 100% GUI-only, at least that's the direction that Android and iOS are taking.

Termux is meant more for advanced users which is not the point of end user stores.

**Comment by xeffyr** [comment]
@superbonaci Whenever Termux is compliant or not, SELinux works outside of Google Play and outside of any Google Services. Once Termux starts to target SDK 29, a newer SELinux policy takes action and restricts usage of `execve()` system call on application data preventing possibility of execution of binaries like `bash` and so on. *Key word here is "application data". You are not restricted if your code is placed into read-only location managed by Android OS, such as APK file.*
