### ISSUE TITLE
Termux Error: CANNOT LINK EXECUTABLE "php": library "libicuio.so.67" not found

### ISSUE THREAD

**Issue by TechniQTeam** [termux/termux-packages#6478]
I want php version 7 instead of 8 on my Termux. The error appears after downgrading php version from php 8 to php7 on termux. The issue has not been resolved yet because the same error appears even after compiling the desired PHP version by myself.

**Comment by xeffyr** [comment]
You have compiled it in a wrong way, e.g. against older libicu.

If compiling from termux-packages, then you need to revert single commit instead of using `git reset`.

**Comment by TechniQTeam** [comment]
I have compiled php7.4.12 from https://github.com/Termux-pod/termux-pod. What should I do against older libicu. Can you please explain the proper way to compile php7.4.12 manually ??

**Comment by xeffyr** [comment]
> I have compiled php7.4.12 from

Downloaded... Compilation means building the package from source code.

As https://github.com/Termux-pod/termux-pod has nothing to do with official Termux, your issue will not be solved. *Downgrading packages voids warranty.*

Termux is rolling release and downgrading a specific package without downgrading all dependencies is not possible.

**Comment by TechniQTeam** [comment]
It's OK. But how can I downgrade to the package php7 as well as the required dependencies from the source code, as php7 has not been listed on termux-packages although the package libicu is there.

**Comment by xeffyr** [comment]
@TechniQTeam You need to use our build environment and compile php from source.

Here are some how-tos:
* https://github.com/termux/termux-packages/wiki/Build-environment - setting up build environment.
* https://github.com/termux/termux-packages/wiki/Building-packages - building packages.

I would not provide details about setting up Docker on Linux machine (PC, VPS or finally Github Actions if can't have one of the first two) as well as details about how to revert git commits and similar. If you can't setup build environment for whatever reason, ask @kcubeterm to provide fresh php7 in https://github.com/Termux-pod/termux-pod.

**Comment by TechniQTeam** [comment]
Can you please Share the following 32-bit Library Dependencies needed for PHP7_i686: libicudata.so.67, libicui18n.so.67, libicuio.so.67 and libicuuc.so.67. 

My Termux needs the above 32-bit Library Dependencies for i686 architecture to install as well as run PHP7_i686 Successfully. Please help. Where can I find the required Library Dependencies for i686 architecture?
