### ISSUE TITLE
Package request: Gitflow

### ISSUE THREAD

**Issue by lleo0h** [termux/termux-packages#6480]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

**Link to home page and sources**

1. Home page: https://github.com/petervanderdoes/gitflow/
2. Source code: https://github.com/petervanderdoes/gitflow-avh/archive/1.12.3.zip

**Additional information**
Have you compiled or tried to compile the package on device?
- No.

**Comment by Grimler91** [comment]
Already available from unstable-repo:  https://github.com/termux/unstable-packages/tree/master/packages/gitflow-avh
