### ISSUE TITLE
can not change to rwx mode

### ISSUE THREAD

**Issue by shiv123shiv123** [termux/termux-packages#6487]
I try to install linux distribution on termux but when downloading .tar file decompressed then all file throw an error that "can not change to rwx mode", please solve this issue as soon as possible. Thanks
![Screenshot_20210220-085522_Termux](https://user-images.githubusercontent.com/79347263/110130500-14875000-7def-11eb-9e88-89daaa74db03.jpg)

**Comment by xeffyr** [comment]
Duplicate of https://github.com/termux/proot/issues/150.

**Comment by muchlis11** [comment]
application to hack anything huh

Pada tanggal Jum, 5 Mar 2021 22:12, Leonid Pliushch <
notifications@github.com> menulis:
