### ISSUE TITLE
build scripts pollute build host

### ISSUE THREAD

**Issue by dead10ck** [termux/termux-packages#6488]
**Problem description**

Hi, I'm pretty new to building packages for termux, and I'm still trying to get my bearings. So I'm sorry if I'm just missing something, or if this has already been discussed (I was not able to find previous discussion).

From what I'm gathering by running the build scripts, reading through the developer wiki, and from taking a poke through some of the shell scripts, it seems like the build process intentionally installs files into `$TERMUX_PREFIX`, which essentially gets hard-coded to `/data/data/com.termux/files`, i.e. the root of the Termux file system. This happens *before* the debian files are actually constructed. From using the default scripts, the behavior I've observed when running `build-package.sh` on my Android device is that `make install` will actually install the files into the device's file system. I noticed that the script that actually assembles the debian files will cd into the massage directory first and tar everything up in there, so I was confused; but on closer inspection of the developer wiki, it seems like it installs everything into the root first, and then copies those files back into the massage directory before massaging and then assembling the debian file from there.

Excuse me for saying so, but this seems rather... backward. Especially when you consider that the data massaging takes place after the files have already been put in the file system.

From my own experience with build systems on Linux distros, and from within my own company, the standard practice is usually not to touch the build host's system files, but instead to put everything into a temporary build directory that acts as a root. So instead of putting things into `/usr/local/bin`, you put them into something like `$BUILD_DIR/debroot/usr/local/bin`, and then you assemble the debian file using `$BUILD_DIR/debroot` as the "fake root" of the debian file's data. This way, the host machine's file system is not polluted with the install files.

**Steps to reproduce**

Make a minimal termux package `build.sh` script with no overridden functions.

**Expected behavior**

A debian file gets produced, and no system files are modified or installed.

**Comment by xeffyr** [comment]
$TERMUX_PREFIX, i.e. `/data/data/com.termux/files/usr` is a system root which is required to store dependencies. This directory is referred everywhere: from the `--prefix=$TERMUX_PREFIX` configure script option to CFLAGS, CPPFLAGS (`-I $TERMUX_PREFIX/include`) and LDFLAGS (`-L $TERMUX_PREFIX/lib`) compiler variables. You can look the build scripts for specific information. Just putting everything into temporary directories will not work. All built files must be installed.

Termux is built entirely through cross-compilation. We can't reuse host dependencies installable through `apt` (CPU architecture, libc ABI and installation prefix mismatch). We can't use Termux apt to conveniently install cross-compiled package. Anyway even if we can, it would have same effect as `make install`.

To avoid host file system being "polluted" with build artifacts, use our Docker image `termux/package-builder`.

***

Now regarding on-device builds: that's a known issue that your installation will be messed up when using `build-package.sh`. It is addressed by https://github.com/termux/termux-packages/pull/5004 (WIP).

**Comment by dead10ck** [comment]
Usually package managers have facilities for distinguishing build dependencies from runtime dependencies. In debians, this would be the [`Build-Deps` et al.](https://www.debian.org/doc/debian-policy/ch-relationships.html#relationships-between-source-and-binary-packages-build-depends-build-depends-indep-build-depends-arch-build-conflicts-build-conflicts-indep-build-conflicts-arch) property in the control file. These packages get installed when building the debian file, but not when a target device installs the finished package.

As for cross-compiling, it is possible to install foreign architecture packages on the build host for this exact purpose. See https://wiki.debian.org/CrossCompiling.

**Comment by Grimler91** [comment]
> In debians, this would be the Build-Deps et al. properties in the control file.

We have TERMUX_PKG_BUILD_DEPENDS for build (but not runtime) dependencies. This is [not saved to the control file](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_create_debfile.sh#L10,L27) though, as we do not have the `apt source` functionality anyways. 

> From my own experience with build systems on Linux distros, and from within my own company, the standard practice is usually not to touch the build host's system files

As Leonid said, the [build-on-device branch](https://github.com/termux/termux-packages/tree/build-on-device) addresses this and makes builds install to `$TERMUX_PKG_MASSAGEDIR/$PREFIX` instead of `$PREFIX`. It works but we need to go through all packages and verify and/or fix so that they use `$TERMUX_PKG_MASSAGEDIR/$PREFIX` instead.

> As for cross-compiling, it is possible to install foreign architecture packages on the build host for this exact purpose. See https://wiki.debian.org/CrossCompiling.

Making it possible to (cross-)compile packages safely both on device and in the docker image in a chroot would be nice, it was discussed a bit in the [build-on-device PR](https://github.com/termux/termux-packages/pull/5004#issuecomment-593608411). It probably makes sense to first fix so all packages respect `DESTDIR`, and then look at this.

**Comment by dead10ck** [comment]
> We have TERMUX_PKG_BUILD_DEPENDS for build (but not runtime) dependencies. This is [not saved to the control file](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_create_debfile.sh#L10,L27) though, as we do not have the `apt source` functionality anyways.

Ah, thanks for pointing this out! I'll make use of this in the future. As for using it in the control file, yeah, it would be nice, but also probably would require figuring out how to cross-compile with foreign arch packages to be useful for anything.

> As Leonid said, the [build-on-device branch](https://github.com/termux/termux-packages/tree/build-on-device) addresses this and makes builds install to `$TERMUX_PKG_MASSAGEDIR/$PREFIX` instead of `$PREFIX`. It works but we need to go through all packages and verify and/or fix so that they use `$TERMUX_PKG_MASSAGEDIR/$PREFIX` instead.

Ah cool, I'll take a look at that PR. That sounds exactly like what I was asking for anyway. 🙂

> Making it possible to (cross-)compile packages safely both on device and in the docker image in a chroot would be nice, it was discussed a bit in the [build-on-device PR](https://github.com/termux/termux-packages/pull/5004#issuecomment-593608411). It probably makes sense to first fix so all packages respect `DESTDIR`, and then look at this.

Sounds like a good approach. After I get my bearings in that PR, if I find myself with spare time, perhaps I can help with this effort.
