### ISSUE TITLE
Could Not Get Lock Bug

### ISSUE THREAD

**Issue by HackerMacaco** [termux/termux-packages#6489]
Please, I Can't Get Others Packages 

Error : Waiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is held by process 29459 (dpkg) and sometimes with (apt)

Please, i need help!!!

**Comment by WMCB-Tech** [comment]
You need to close another apt instance, maybe


```
killall -9 apt 
```

and try again, or fully restart termux and try again
