### ISSUE TITLE
mpv: reenable libcaca

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#649]
Is there a good reason for removing libcaca support? I prefer the caca output to tct because it's faster, especially over ssh.

**Comment by vishalbiswas** [comment]
And it looks way better
I prefer actual ascii to just solid blocks

**Comment by xeffyr** [comment]
Done in https://github.com/termux/termux-packages/commit/6e700dc3841066013c4270de737415ab09df541f.
