### ISSUE TITLE
XML-Parser

### ISSUE THREAD

**Issue by avpanov** [termux/termux-packages#6492]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [ ] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

XML-Parser

**Link to home page and sources**

1. Home page:
2. Source code:

https://metacpan.org/pod/XML::Parser

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

I have tried to build it in a recent termux installation. The output is below:

-------------------
$ perl Makefile.PL EXPATLIBPATH=/usr/lib EXPATINCPATH=/usr/include
"/home/.cpan/build/XML-Parser-2.46-0/assertlibwIuFb5gd": error: Android 5.0 and later only support position-independent executables (-fPIE).

Expat must be installed prior to building XML::Parser and I can't find
it in the standard library directories. Install 'expat-devel' (or
'libexpat1-dev') package with your OS package manager. See 'README'.

Or you can download expat from:

http://sourceforge.net/projects/expat/

If expat is installed, but in a non-standard directory, then use the
following options to Makefile.PL:

    EXPATLIBPATH=...  To set the directory in which to find libexpat

    EXPATINCPATH=...  To set the directory in which to find expat.h

For example:

    perl Makefile.PL EXPATLIBPATH=/home/me/lib EXPATINCPATH=/home/me/include

Note that if you build against a shareable library in a non-standard location
you may (on some platforms) also have to set your LD_LIBRARY_PATH environment
variable at run time for perl to find the library.

-------------------
This small package is a requirement for intltool. Intltool (standalone or bundled) is required to build many packages.

I tried it to build on Huawei Mediapad T5 tablet (Android 8.0, 64 bit). Also I tried various CFLAGS and LDFLAGS with options like -fPIE.

**Comment by Hax4us** [comment]
Some lines from **Termux Policy On Package Request** 

**Packages must NOT be a part of language-specific ecosystem. These packages are installable through cpan, gem, npm, pip and similar.**

btw in cpan do `install XML::Parser`

**Comment by avpanov** [comment]
Okay, you mean that perl package is broken in termux-packages is broken as it cannot install this simple package from CPAN. See the first message:
--------------------
"/home/.cpan/build/XML-Parser-2.46-0/assertlibwIuFb5gd": error: Android 5.0 and later only support position-independent executables (-fPIE).
--------------------
Setting -fPIE does not help.

**Comment by Grimler91** [comment]
@avpanov you need to add -fpie to CFLAGS (or another suitable compiler flag). You might need to patch the perl package in case it does not respect environmental variables. 

It is not perl that is broken, that perl package is just not set up for compilation on android.
