### ISSUE TITLE
FLTK toolkit not available in GNU Octave

### ISSUE THREAD

**Issue by apandada1** [termux/termux-packages#6494]
**Problem description**

I installed GNU Octave from the [its-pointless](https://github.com/its-pointless/gcc_termux) repositories, and the packages `fltk`, `fltk-static` from the Termux repositories. Octave does not show `fltk` in available graphics toolkits, only `gnuplot` is available.
```
apt search fltk
Sorting... Done
Full Text Search... Done
fltk/x11,now 1.3.5-17 arm [installed]
  Graphical user interface toolkit for X

fltk-static/x11,now 1.3.5-17 arm [installed]
  Static libraries for fltk

```

```
octave:1> available_graphics_toolkits 
ans =
{
  [1,1] = gnuplot
}
```

**Steps to reproduce**

Install GNU Octave from its-pointless repo (beware of [this](https://github.com/its-pointless/gcc_termux/issues/112) bug, in case you are using Android 10), and then install `fltk` with `pkg install fltk`. Check the output of `available_graphics_toolkits` in Octave.

**Expected behavior**

Octave should show both `fltk` and `gnuplot` in the output of `available_graphics_toolkits`, and the user should be able to switch between the two.
This feature works in Octave 6.1 in my computer running Manjaro.

**Additional information**

```
$ termux-info
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://ipfs.io/ipns/k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4 x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.190-perf-gb3c173e #1 SMP PREEMPT Mon Feb 1 23:49:30 CST 2021 armv8l Android
Device manufacturer:
Xiaomi
Device model:
M2006C3MI
```

Although `octave` is not in the default termux repositories, `fltk` is, and that is why I decided to post the issue here.

**Comment by xeffyr** [comment]
GNU octave is not official Termux package. It is provided in community repository by @its-pointless, so please open the issue in appropriate repository.
