### ISSUE TITLE
How to display the character chr(200413) ?

### ISSUE THREAD

**Issue by zameax** [termux/termux-packages#6496]
How to display the character chr(200413) ?
when I copy the ordinary char of chr(200413) and paste it to termux's cmdline, the char always is chr(65533),it sames that termux does not support cjk-E in utf-8 mode to paste to its bash cmdline or to display it?
example: echo "𰻝"
ps: "𰻝" == chr(200413) in python3

**Comment by agnostic-apollo** [comment]
The`U+30EDD` character is outside the [Basic Multilingual Plane](https://en.wikipedia.org/wiki/Unicode#Code_planes_and_blocks) range and may not display properly on devices. Does it display properly in your browser or text editor apps on your phone?

**Comment by ChiefMikeK** [comment]
download a font that has this character block and give termux access to it  
[Unicode character ranges and the Unicode fonts that support them](http://www.alanwood.net/unicode/fontsbyrange.html#u2b740 )

**Comment by ChiefMikeK** [comment]
I'm not sure if either of those have been updated yet to newer unicode block

- CJK Unified Ideographs Extension D  👀 U+2B740 – U+2B81F   (177984–178207)

**BabelStone Han, HanaMin Regular**

**Comment by agnostic-apollo** [comment]
The `U+3*` characters were added in [CJK Unified Ideographs Extension G](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs_Extension_G).

**Comment by ChiefMikeK** [comment]
> The `U+3*` characters were added in [CJK Unified Ideographs Extension G](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs_Extension_G).

I just checked and    **BabelStone Han** has been updating fairly frequently here's the link to character strings as of last weeks update
- https://www.babelstone.co.uk/CJK/IDS.TXT

**Comment by agnostic-apollo** [comment]
> I just checked and **BabelStone Han** has been updating fairly frequently here's the link to character strings as of last weeks update
> 
> * https://www.babelstone.co.uk/CJK/IDS.TXT

That should probably work. The **Character Repertoire** section mentions that the **Extension G** range is `30000..3134F` and `+30EDD` character is within it. However, the current total coverage for **Extension G** is `50%` and total G-Source coverage (i.e chinese characters) is only `32%` so there would still be issues with other characters.

https://www.babelstone.co.uk/Fonts/Han.html

Anyways, closing since not directly a Termux issue.

**Comment by ChiefMikeK** [comment]
If you still are unable to input the data after installing the font then please change the title of this issue to⤵️

## Unicode Tertiary Ideographic Plane (TIP), Input

**Comment by agnostic-apollo** [comment]
Check Termux:Styling wiki for info on how termux fonts work. Basically, place the custom downloaded `.ttf` font file at `/data/data/com.termux/files/home/.termux/font.ttf` and reload termux.

https://wiki.termux.com/wiki/Termux:Styling
