### ISSUE TITLE
recode - - character set conversion utility

### ISSUE THREAD

**Issue by juren53** [termux/termux-packages#6497]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description
Free `recode' converts files between character sets and usages.  When
 exact transliterations are not possible, it may get rid of the
 offending characters or fall back on approximations.  This program
 recognizes or produces nearly 300 different character sets and is able
 to transliterate files between almost any pair.  Most RFC 1345
 character sets, and all `libiconv' character sets, are supported.

**Link to home page and sources**

1. Home page: https://github.com/pinard/Recodec/blob/23f330016de6af17a1d76b2750961a5845dfa88a/Recode/builtin.py

**Comment by RossComputerGuy** [comment]
Python programs won't be added to the package repo.

**Comment by juren53** [comment]
More info at:  https://github.com/rrthomas/recode/blob/master/HACKING.org

**Comment by juren53** [comment]
OK.  good to know

**Comment by Grimler91** [comment]
If there are termux specific issues that prevents installation through pip then we can consider packaging it. Otherwise please install through pip
