### ISSUE TITLE
No 'slabtop' found after install the package 'procps'

### ISSUE THREAD

**Issue by zhanweiw** [termux/termux-packages#6499]
We can find the 'slabtop' from https://gitlab.com/procps-ng/procps
But after I installed the 'procps' package in termux, I can't find the 'slabtop' command. Any idea on this? Thanks in advance.

**Comment by WMCB-Tech** [comment]
The package you're pointing is `procps-ng` which termux provides `procps` and not `procps-ng`

**Comment by WMCB-Tech** [comment]
Oh i see, that's why `top` uses Android's `top`
