### ISSUE TITLE
Package request: Avahi

### ISSUE THREAD

**Issue by regagain** [termux/termux-packages#65]
Avahi is a free zero-configuration networking (zeroconf) implementation, including a system for multicast DNS/DNS-SD service discovery.

**Comment by fornwall** [comment]
Thanks for the suggestion! I started a [wiki page to keep track of package suggestions](https://github.com/termux/termux-packages/wiki/Package-suggestions) and have added Avahi there!

**Comment by blacknosugar** [comment]
I'd like to second the request for Avahi. I'm using Termux with Unison to sync files from my MacBook to my phone. It would be awesome to be able to configure Unison to sync on hostname.local instead of an ever changing local IP address.

I went insane trying to find a solution including porting Avahi to Termux, making use of Android NDS, making use of jmDNS etc. I'm way out of my depth here. Sorry to be of no use here.

Is it maybe easier to cross compile the dns-sd tool for Android from here: http://www.opensource.apple.com/source/mDNSResponder/mDNSResponder-320.10.80/ ??

dns-sd is included in OSX and I can easily register a service with it. Avahi might be superior, but we could use dns-sd until somebody had time to port it.

**Comment by Neo-Oli** [comment]
Hi, I am re-opening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by axujen** [comment]
seconding this request, for me without avahi theres no point in running a linux env on an android phone since they're so elusive constantly changing its IP all the time.

**Comment by Skehmatics** [comment]
further bumping this request. Avahi would be incredibly useful

**Comment by tulakalbeyo** [comment]
bampu! this would be so very useful. please make it hapen :-)

**Comment by wxl** [comment]
Yeah, this would be very nice. Alternately issue #182 suggests just dns-sd alone. Either option would be really nice.

**Comment by axujen** [comment]
just adding that [optware-ng](https://github.com/Optware/Optware-ng) packages an arm version of [avahi](http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabihf/avahi_0.6.31-3_arm.ipk) that works pretty well on android, so technically it is possible to get avahi working under android

**Comment by shawnl** [comment]
BTW Android 5 has zeroconf/mDNS https://developer.android.com/training/connect-devices-wirelessly/nsd.html

**Comment by sdrausty** [comment]
It looks like Avahi is currently available in Termux through Arch Linux PRoot.  This script is designed to install Arch Linux in just a few keystrokes. Tapping this link https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh will transfer `setupTermuxArch.sh` to your device. Simply run `bash setupTermuxArch.sh` to install Arch Linux in Termux.  To install use `pacman -S avahi` and this will install Avahi on device.  

![screenshot_20171130-001646](https://user-images.githubusercontent.com/27742457/33415366-024e86b0-d564-11e7-9c2f-13a5fd12c4c3.png)

**Comment by msdos** [comment]
This would indeed be really useful, some machines in my lan keeps changing ips because I don't have an option in my router to bind specific ips to MAC addresses.

**Comment by xeffyr** [comment]
>  I don't have an option in my router to bind specific ips to MAC addresses.

@msdos Android support assigning of static ip to device (and non-android devices probably too).

**Comment by ToRvaLDz** [comment]
@sdrausty I successfully installed avahi on termuxarch anyway I cannot get it running:

`
[root15:09run]$ avahi-daemon
Failed to create runtime directory /run/avahi-daemon/.
[root15:09run]$ ls -la
total 16
drwxr-xr-x  4 root root 4096 Mar 14 14:46 .
drwx------ 19 root root 4096 Mar 14 15:08 ..
drwxr-xr-x  2 root root 4096 Mar 14 14:46 avahi-daemon
drwx------  3 root root 4096 Mar 14 13:47 systemd
[root15:09run]$ 

`

**Comment by old-square-eyes** [comment]
I am looking for a mDNS solution also

**Comment by rien333** [comment]
@SDRausty 
> It looks like Avahi is currently available in Termux through Arch Linux PRoot. This script is designed to install Arch Linux in just a few keystrokes. To install use `pacman -S avahi` and this will install Avahi on device.

This command downloads it (and the nessecary packages), but that doesn't mean that it works, right? The official arch linux way (according to the arch wiki) is to manage avahi with systemd. The proot environment has no systemd, however.  If I run the daemon outside of systemd I get the following error: 

```bash
$ avahi-daemon
Failed to create runtime directory /run/avahi-daemon/.
```

**Comment by espenseventyr** [comment]
Hello, anyone found a solution?

**Comment by eadmaster** [comment]
`libnss-mdns` would also be nice to have if you have to connect from an android client the other way around.

**Comment by shawnl** [comment]
Android has native zeroconf since 5 IIRC.

**Comment by eadmaster** [comment]
i've tried pinging my pc via the ".local" mDNS name and it is not working in Termux, in fact it seems [only available in some apps](https://stackoverflow.com/questions/30449988/how-to-enable-mdns-support-in-android-browser-address-bar), not @ system-level like in vanilla linux.

**Comment by shawnl** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1011340

**Comment by RossComputerGuy** [comment]
>  Opened 6 years ago Updated 1 year ago 

> Assignee: lassey → nobody

I don't think it's going to be implemented.

**Comment by shawnl** [comment]
It will be if you do it. (But as part of the new Firefox Focus/Fenix).

**Comment by razzfox** [comment]
A potential alternative is to use the zeroconf python module. This repo has a simple example to create a service:
https://github.com/jstasiak/python-zeroconf

**Comment by eadmaster** [comment]
> A potential alternative is to use the zeroconf python module. This repo has a simple example to create a service:
https://github.com/jstasiak/python-zeroconf

Nice finding... i've recently also found this app as alternative:  [SSHelper](https://arachnoid.com/android/SSHelper/).

**Comment by shawnl** [comment]
Android has its own implementation of the Bonjour (the RFC spec calls it Zeroconf, and there id an excelente YouTube presentacion by its inventor, an Apple employee, in which all his enthusiasm, and belief that it would have been better than USB which happened instead, is warranted), and from the best of my knowledge that implementation is sound.

If you are using the Android platform you should probably use their implementation, otherwise you should use some other platform, and not something as hacky as Termux.

**Comment by spacehobo** [comment]
> If you are using the Android platform you should probably use their implementation, otherwise you should use some other platform, and not something as hacky as Termux.

Absolutely!  So: how?  The "implementation" appears to be nothing but raw API functions, without any apps to drive them.

**Comment by shawnl** [comment]
El lun., 7 jun. 2021 12:17, Abolish ICE ***@***.***> escribió:

> If you are using the Android platform you should probably use their
> implementation, otherwise you should use some other platform, and not
> something as hacky as Termux.
>
> Absolutely! So: how? The "implementation" appears to be nothing but raw
> API functions, without any apps to drive them.
>
You just stated the Free Software manifesto.

**Comment by xtkoba** [comment]
Seems like we need to package `libdaemon` first.
