### ISSUE TITLE
aspell gives incompatible hash function

### ISSUE THREAD

**Issue by yesco** [termux/termux-packages#6500]
Just installed aspell on termux with the english packages and it doesn't like the compiled database it seems.

~ $ echo "fish" |aspell -a
Error: The file "/data/data/com.termux/files/usr/lib/aspell-0.60/en-common.rws" is not in the proper format. Incompatible hash function.
~ $ pkg list-installed | grep aspell                        
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

aspell-en/stable,now 1:2020.12.07 all [installed]
aspell/stable,now 0.60.8 aarch64 [installed]

This seems relevant:
https://github.com/arnested/drupal-spell/issues/2 (but not drupal related)

**Comment by ShengliangD** [comment]
I'm facing the same problem. Any solution yet?
