### ISSUE TITLE
Package request: germanium

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#6505]
https://github.com/matsuyoshi30/germanium

It's just a Go package so it should be an easy addition.

If anyone else is interested the arm64 binaries from the releases works perfectly out of the box on termux.

**Comment by amm834** [comment]
It is just `Go` package.
You can use it via `Go`.

```bash
pkg install golang
git clone https://github.com/matsuyoshi30/germanium
cd germanium && go install
```

**Comment by ravener** [comment]
@amm834 again, yes I know. You don't have to teach me. I already have it working.
