### ISSUE TITLE
Error when setting nushell to login shell

### ISSUE THREAD

**Issue by noalias** [termux/termux-packages#6506]
**Problem description**

When I set nushell to login shell using chsh, an error was reported.

![Screenshot_20210312_153706](https://user-images.githubusercontent.com/42366661/110910701-ab529000-834c-11eb-92bf-2eb92f93dfaf.jpg)

**Comment by WMCB-Tech** [comment]
It seems chsh may have problems when setting a default shell sometimes, try this method

Bash
```
echo "exec nushell" >> ~/.bashrc
```

ZSH
```
echo "exec nushell" >> ~/.zshenv
```

**Comment by xeffyr** [comment]
That's because nushell doesn't implement option "-l" typically used by other shells to enable login mode. We can add an exception for nushell to the Termux login script.

For now you can start a custom shell by exec'ing it from the rc file (zshrc, bashrc, as suggested in previous comment).

**Comment by noalias** [comment]
Thank you!
