### ISSUE TITLE
error processing archive

### ISSUE THREAD

**Issue by 1094** [termux/termux-packages#6508]
Are you not accepting issues about installing Termux or issues about installing packages via Termux? If it's the first and not the second, continue. If it's the second or both, let me know and I'll delete this.

**Problem description**
![Screenshot_20210312-195529](https://user-images.githubusercontent.com/31363848/111013412-3193c400-8397-11eb-888a-9b2700aee644.png)

**Steps to reproduce**
After installing `vim` I attempted to install `git`. I got the same error seen in the screenshot. Then I ran `rm -rf $PREFIX` as seen in Issue 5047. Then I ran `app update && app upgrade` and `apt install git openssh`.
I also tried installing root-repo, that returned the same error.

**Expected behavior**
I expected it to download and install the requested packages.

**Additional information**

![IMG_20210312_200346_373](https://user-images.githubusercontent.com/31363848/111013766-96035300-8398-11eb-99da-a5da60d38155.JPG)
```

```

**Comment by WMCB-Tech** [comment]
Seems you have a legacy environment which is currently unsupported 

***

However you may try resetting your `$PREFIX` and do `apt clean` and try again, see if it helps

**Comment by 1094** [comment]
> Seems you have a legacy environment which is currently unsupported
Should I delete the issue?
> However you may try resetting your `$PREFIX` and do `apt clean` and try again, see if it helps
It didn't, but I guess I can run `vim` without the plugins.

**Comment by WMCB-Tech** [comment]
> Should I delete the issue?

Probably not as termux devs may close it instead to reference this 

> It didn't, but I guess I can run vim without the plugins.

Huh, i guess it may be plugins issue that cause dpkg error

**Comment by Grimler91** [comment]
Don't think we have seen that particular variant of dpkg error. I would try manually downloading the .debs (through your browser), and then install them through apt and or dpkg to see if that works. After removing $PREFIX again

The error is probably device specific

**Comment by bentuk114** [comment]
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/lsof_4.94.0_aarch64.deb  Could not open file /data/data/com.termux/cache/apt/archives/partial/lsof_4.94.0_aarch64.deb - open (2: No such file or directory)
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/nano_5.5_aarch64.deb  Could not open file /data/data/com.termux/cache/apt/archives/partial/nano_5.5_aarch64.deb - open (2: No such file or directory)
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/aarch64/net-tools_2.10.0_aarch64.deb  Could not open file /data/data/com.termux/cache/apt/archives/partial/net-tools_2.10.0_aarch64.deb - open (2: No such file or directory)
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/all/science-repo_1.2_all.deb  Could not open file /data/data/com.termux/cache/apt/archives/partial/science-repo_1.2_all.deb - open (2: No such file or directory)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by bentuk114** [comment]
![Screenshot_2021-03-13-19-07-11-88](https://user-images.githubusercontent.com/80580623/111029482-65222d00-842f-11eb-9fc2-9697e5351885.png)

**Comment by bentuk114** [comment]
![Uploading Screenshot_2021-03-14-04-31-44-89.png…]()

**Comment by 1094** [comment]
> Huh, i guess it may be plugins issue that cause dpkg error, does dpkg working again if those plugins are removed/disabled?

The plugins haven't been installed yet (they are installed by vim-plug, via git (which can't be installed), inside of Vim. They shouldn't have anything to do with the pkg installer.

**Comment by 1094** [comment]
> Don't think we have seen that particular variant of dpkg error. I would try manually downloading the .debs (through your browser), and then install them through apt and or dpkg to see if that works. After removing $PREFIX again
> 
> The error is probably device specific

I thought about doing this, but I didn't see any deb files in the different folders (which probably means I'm not understanding something--I'm used to Arch). Can download the packages from this repo or?

**Comment by tvfmmfvt** [comment]
Hi.

**Comment by tvfmmfvt** [comment]
Lololol not merging v continue hi bye .

**Comment by xeffyr** [comment]
Try
```
mkdir -p /data/data/com.termux/cache/apt/archives
```
and then run package installation.

And ensure that your OS doesn't do any storage "optimizations", aka automatic cache cleaning, and all "cleaners" are either disabled or uninstalled. Automatic application cache cleaning is unexpected behavior of the OS.

Closing for now.

**Comment by xeffyr** [comment]
From last screenshot it is shown as issue of Android 6.0. This OS version is not supported anymore.
