### ISSUE TITLE
QEMU package naming issue

### ISSUE THREAD

**Issue by blochl** [termux/termux-packages#6521]
**Problem description**

The package name `qemu-system-x86-64-headless` implies that it includes only the x86-64 emulation. While in fact, it includes the following targets:
* aarch64-softmmu
* arm-softmmu
* i386-softmmu
* riscv32-softmmu
* riscv64-softmmu
* x86_64-softmmu

**Steps to reproduce**

N/A

**Expected behavior**

If the package includes all these targets, it should be called just `qemu` or `qemu-headless`. Another possibility is to split it into two packages: one, `qemu-system-x86-64-headless` for x86-64 emulation only, which is likely to be the most popular emulation, and another, `qemu-arch-extra` (for example) for the other architectures.

**Additional information**

N/A

```

```

**Comment by WMCB-Tech** [comment]
Probably split QEMU package is preferred so i can choose what to install rather than installing qemu with all architectures bundled which it may not be used and may take up storage space for some devices

***

Maybe adding an optional metapackage or transitional package would be okay so if users want to install qemu with all the architectures, they can install the qemu (headless/non-headless) metapackage as you suggest,

**Comment by RossComputerGuy** [comment]
Most, or all, distros that have QEMU include all of them together. I think being able to run `pkg install qemu` to get everything makes it much easier if you want multiple targets.

**Comment by blochl** [comment]
> Most, or all, distros that have QEMU include all of them together. I think being able to run `pkg install qemu` to get everything makes it much easier if you want multiple targets.

Well, Debian, for example, provides one package for all, but also has packages for every architecture. You can check it like this:
```bash
curl -L 'https://packages.debian.org/testing/allpackages?format=txt.gz' 2>/dev/null | zcat | grep '^qemu-system'
```
In Arch, the package `qemu` provides only the x86-64 emulation, while the package `qemu-arch-extra` provides the other architectures: https://archlinux.org/packages/?q=qemu . Etc.

As Termux is intended mainly for mobile devices, where storage might be limited, but is maintained not by a huge enough community to support a separate package for every architecture, I think that the Arch approach might be the best.

One thing is certain though: if the package contains emulations for several architectures, it should not be called "qemu-system-**x86-64**-headless". :)

**Comment by xeffyr** [comment]
I can't reproduce the issue. Package includes only one target binary. See screenshot below.
![Screenshot_20210318-101642](https://user-images.githubusercontent.com/25881154/111594002-36130f00-87d3-11eb-9cd2-7cf04e05c7f3.png)

**Comment by blochl** [comment]
Hmm... so how one can explain lines 25-27 in the package's build.sh?

https://github.com/termux/termux-packages/blob/32e3c9e9e5f866f809b359e7402f8b7d25eb3914/packages/qemu-system-x86-64-headless/build.sh#L25-L30

**Comment by xeffyr** [comment]
Yes, all QEMU components are built at same time. But later during packaging (i.e. when deb files are created) they are split between subpackages.

Don't look just at build.sh, there also \*.subpackage.sh files.
