### ISSUE TITLE
Unbound variable $CC......in termux_setup_rust

### ISSUE THREAD

**Issue by tuwile** [termux/termux-packages#6522]
**Problem description**

I was trying to build a package......but github actions ran into an error stating:

![Screenshot_2021-03-16-20-07-11-508](https://user-images.githubusercontent.com/73517616/111328004-2af29e80-866e-11eb-96e9-408fa3a1ab77.jpeg)

I do not know what this variable $CC is on `line 29` of `termux_setup_rust.sh` script

![Screenshot_2021-03-16-20-14-53-529](https://user-images.githubusercontent.com/73517616/111328548-a05e6f00-866e-11eb-8498-c05ba65466f0.jpeg)

How should I fix it?

**Comment by xeffyr** [comment]
Misuse of termux_step_host_build.

**Comment by xeffyr** [comment]
`termux_step_host_build` is used as intermediate step to compile host build tools and not the actual package.
