### ISSUE TITLE
golang: UTC always used as default timezone regardless of system settings

### ISSUE THREAD

**Issue by ilyapashuk** [termux/termux-packages#6523]
**Problem description**

apps using golang time package always uses UTC as local timezone and ignores system settings, but other apps like date tool works fyne
**Steps to reproduce**

build and run code like this:
package main
import "log"
func main() {
log.Fatal("test")
}
**Expected behavior**

logs should be in user's localtime
**Additional information**

```

```
android 9, samsung galaxy a 30, go 1.16
and time package should by default import "time/tzdata" because there is not any tzdata files in your environment

**Comment by xeffyr** [comment]
Please use search, that's a known issue introduced on upstream and still not resolved by Golang team. It affects a whole Android OS target.

https://github.com/golang/go/issues/20455

**Comment by ilyapashuk** [comment]
yes, but you at least are able to:
patch time package to don't ignore TZ envvar on android target
do some analog of this on termux app startup:
export TZ="$(getprop persist.sys.timezone)
populating tz envvar for all apps, that will simplify a lot of things
