### ISSUE TITLE
Using the C language, it does not print.

### ISSUE THREAD

**Issue by LivestC** [termux/termux-packages#6524]
**Problem description**
For some reason using gcc and clang to compile and run a C file, it doesn't print the text. (But if it works with most other languages)

**Steps to reproduce**
1. Create a file called `test.c`
2. Integrate this code into your file
```
// test.c

#include <stdio.h>

int main() {
    printf("Hello world!\n");
    return(0);
}
```
3. `gcc test.c` or `clang test.c`

**Excepted behavior**
Let it print `Hello world!`, Or another impression.

**Additional information**
• I am learning C / C++, and I would not like to use another compiler to do it, Termux is very suitable and interface that I like. (I know the syntax but not enough the functions)
• Look for questions waiting for a solution to this problem, but none of them work for me.
• If we use C++: We have many problems.

```
// main.c utf-8

#include <stdio.h>

int main() {
    printf("Hello world!\n");
    return(0);
}

```

**Comment by ravener** [comment]
gcc is a compiler. It compiles it but won't run it. By default the output file is `a.out` check your files with `ls` and run it via `./a.out`

**Comment by LivestC** [comment]
> gcc/clang is a compiler. It compiles it but won't run it. By default the output file is `a.out` check your files with `ls` and run it via `./a.out` 

It did not help me, It still does not print.

**Comment by ravener** [comment]
@LivestC really? Do you not get anything when you run `./a.out`?

**Comment by LivestC** [comment]
> @LivestC really? Do you not get anything when you run `./a.out`? If you are sure it's not your mistake, feel free to reopen this so someone else can review

Thanks! I was able to fix the problem, now I have a problem compiling cpp (I already had it) but I'll explain it in another proposal.
