### ISSUE TITLE
Package request: mailutils

### ISSUE THREAD

**Issue by SuperTux20** [termux/termux-packages#6530]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

> Mailutils is a swiss army knife of electronic mail handling. It offers a rich set of utilities and daemons for processing e-mail.
> All Mailutils programs are able to operate on mailboxes of any existing format, ranging from standard UNIX maildrops, through maildir and up to remote mailboxes, which are transparently accessed using IMAP4, POP3 and SMTP.

(this description was taken from the home page)
Another notable thing it can do, and what made me think of it in the first place, is that Cron will send messages to the system mailbox upon executing a job containing the command output so you can determine whether it worked or not.

**Link to home page and sources**

1. Home page: https://mailutils.org/
2. Source code: https://mailutils.org/download.html

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

No, I have not tried to compile it. I've had terrible luck with compiling any Linux software, regardless of what it is.

**Comment by suhan-paradkar** [comment]
I was able to compile mailutils natively on termux.. I will pull a PR soon

**Comment by kcubeterm** [comment]
Closing as package is available https://github.com/termux/termux-packages/pull/6788
