### ISSUE TITLE
Please add libx265 option to ffmpeg

### ISSUE THREAD

**Issue by wrsg** [termux/termux-packages#655]

**Comment by fornwall** [comment]
Thanks for the suggestion! The ffmpeg package has been updated to build with libx265 in version 3.2.2, update to it with

    apt update && apt upgrade

Note that I haven't tested if myself, so let me know if something is broken!

**Comment by wrsg** [comment]
It does work, but is painfully slow (Nexus 6 on Android 7.1.1) not sure if that's because of Android just being slow in general for these tasks. It took 1705 seconds to encode a 12mb mp4 into a mkv containing a x265, using libopus and libx265, file size reduced to 2.5mb.
