### ISSUE TITLE
Package request: libmagic and libgumbo

### ISSUE THREAD

**Issue by sobaee** [termux/termux-packages#6550]
Packages:
libmagic and libgumbo

These packages are dependencies for zim-tools especially  "zimwriterfs" part.

This is the github site of "zim-tools":
https://github.com/openzim/zim-tools

You could find more details about these dependencies and about "zim-ttols" in the previous page.

Thanks a lot.

**Comment by xeffyr** [comment]
libmagic: part of `file` package.

libgumbo: `gumbo-parser` package.

**Comment by sobaee** [comment]
Thanks a lot
