### ISSUE TITLE
termux xfce4 desktop kivy critical window

### ISSUE THREAD

**Issue by Sahil-pixel** [termux/termux-packages#6552]
**Problem description**
I have install termux in android 8 and xfce4 desktop and vnc viewer 
in that case i can run python tkinter well but after installation kivy 
when i am running simple kivy app it showing there is no window provider 
see the link below
 https://groups.google.com/forum/embed/#!topic/kivy-users/MPJsu3lzkDw

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by rakslice** [comment]
As noted in the FAQ for this error in Kivy (https://kivy.org/doc/master/faq.html?highlight=faq#unable-to-get-a-window-abort), the SDL2-based provider requires OpenGL 2.1. This simply something that the Xvnc you are trying to use it with simply doesn't do.
