### ISSUE TITLE
exa tool

### ISSUE THREAD

**Issue by thorfinn-karlsefni** [termux/termux-packages#6555]
**Problem description**

I think that exa color functionality doesn't work. 
**Steps to reproduce**
exa command only, by default, it might color the output files.

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
You either don't use exa or use it in some wrong way or your color scheme doesn't support colors.

![Screenshot_20210322-233154](https://user-images.githubusercontent.com/25881154/112061363-111df380-8b67-11eb-9b0f-6ee53dd6179c.png)

Closing as false bug.
