### ISSUE TITLE
Promote gopass from termux/unstable-packages to termux/termux-packages

### ISSUE THREAD

**Issue by dominikschulz** [termux/termux-packages#6561]
Hi,

I'm the maintainer of [gopass](https://github.com/gopasspw/gopass). It's only available in the unstable-packages repo at 
 https://github.com/termux/unstable-packages/tree/master/packages/gopass.

I belive this package is in good shape - at least in my experience it works well in termux - so I wonder what it would take to promote it to the regular package repository?

We want to actively support and promote using `gopass` on Android via termux.

**Comment by xeffyr** [comment]
If you confiriming that it works well, then I will move it to this repo. That's all what is needed.

**Comment by xeffyr** [comment]
Package should be now available for installation from the main repo.
