### ISSUE TITLE
Lua interpreter is failing for luarocks

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#6562]
After moving to seperate lua packages (lua52, lua53, lua54) each of them packages the interpreter with their respective versions e.g `lua5.2` so there's no central `lua` executable which fails for some packages like `luarocks`
```
$ luarocks --help
Failed to execute process '/data/data/com.termux/files/usr/bin/luarocks'. Reason:
The file '/data/data/com.termux/files/usr/bin/luarocks' specified the interpreter '/data/data/com.termux/files/usr/bin/lua', which is not an executable command.
```

**Comment by suhan-paradkar** [comment]
Even I get the same issue but solved it by creating a symlink gor lua at $PREFIX/bin to lua5.3

**Comment by suhan-paradkar** [comment]
You may also see #6015

**Comment by ravener** [comment]
Apparently this was just a duplicate of #6015 which has been fixed, closing this now.
