### ISSUE TITLE
hostbuild PATH problem

### ISSUE THREAD

**Issue by vishalbiswas** [termux/termux-packages#657]
There's a huge bug in the hostbuild step.
If the configure script checks for clang instead of gcc and if its not installed on the host machine, it will catch clang from android toolchain and try to compile hostbuild with it.
We need to delay appending `$TERMUX_STANDALONE_TOOLCHAIN/bin` to the PATH until after hostbuild or restore original PATH for hostbuild.

**Comment by fornwall** [comment]
Thanks! I've rewritten `build-package.sh` a bit, hopefully it should be less hacky now.

The hostbuild step is done before setting up an android toolchain.

As it was a bigger rewrite of build-package.sh let me know if you encounter anything broken!
