### ISSUE TITLE
error on android 7

### ISSUE THREAD

**Issue by lythatda1997** [termux/termux-packages#6570]
![Screenshot_20210327-192833_F1  @VM](https://user-images.githubusercontent.com/81241248/112720720-a6880180-8f32-11eb-8c82-6db46916a61b.jpg)
![Screenshot_20210327-192833_F1 VM](https://user-images.githubusercontent.com/81241248/112720737-c4edfd00-8f32-11eb-8a1c-4e184400a01b.jpg

$ pkg upgrade
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: ok
[*] https://grimler.se/termux-packages-24: bad
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Get:2 https://termux.mentality.rip/termux-packages-24 stable InRelease [14.0 kB]
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Get:5 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release.gpg [475 B]
Err:2 https://termux.mentality.rip/termux-packages-24 stable InRelease
  At least one invalid signature was encountered.
Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release.gpg [475 B]
Ign:6 https://dl.bintray.com/grimler/game-packages-24 games Release.gpg
Ign:7 https://dl.bintray.com/grimler/science-packages-24 science Release.gpg
Reading package lists... Done
W: GPG error: https://termux.mentality.rip/termux-packages-24 stable InRelease: At least one invalid signature was encountered.
E: The repository 'https://termux.mentality.rip/termux-packages-24 stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://dl.bintray.com/grimler/game-packages-24 games Release: At least one invalid signature was encountered.
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://dl.bintray.com/grimler/science-packages-24 science Release: At least one invalid signature was encountered.
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by Grimler91** [comment]
Can you visit the URLs in your browser? Since both bintray and termux.mentality.rip fails it is probably some problem on your end

**Comment by lythatda1997** [comment]
I still access the normal URL

**Comment by sendev1** [comment]
I am seeing the same error in android 10.. ap get update does not work

**Comment by xeffyr** [comment]
`termux-change-repo` to switch repository. Pick a one that will work for you and use `pkg` instead of `apt` directly.

***

Btw, screenshot on top post seems to be from F1 VM application. Neither F1 VM, VMOS and other ~~fake~~"virtualizers" are guaranteed to run Termux properly. One of known issues is failure during gpg signature verification.

**Comment by Luisagerlo** [comment]
En este video se explica la solución: https://youtu.be/cxqMBQ_R23A
