### ISSUE TITLE
scikit learn error on Android 11

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#6575]
I could successfully install scikit-learn version 
0.22.2.post1

But when I open the python interpreter and type

>>> import sklearn 

I get the following error:

ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/1618 and https://github.com/termux/termux-packages/issues/570

Hopefully sklearn works even though it prints that error. It is not something we can fix.
