### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zubok333** [termux/termux-packages#6577]
![Screenshot_2021-03-29-17-56-53-538_com.termux.jpg](https://user-images.githubusercontent.com/81566456/112856221-3a370a80-90b8-11eb-94e7-dc3730ab5d28.jpg)

**Comment by Grimler91** [comment]
I can't see any errors here.

**Comment by xeffyr** [comment]
It shows error because installed a placeholder package (i.e. empty). Re-installation won't help there.
