### ISSUE TITLE
zsh/system module missing

### ISSUE THREAD

**Issue by r0bobo** [termux/termux-packages#659]
I tried installing [zplug](https://github.com/zplug/zplug) but got error: `failed to load module: zsh/system`. If i run `zmodload zsh/system` in zsh i also get the same error. Is this module missing because of limitations with android or can it be included somehow?

**Comment by fornwall** [comment]
Thanks for reporting! I've updated the zsh package to version `5.3.1-1` where the system module has been added. Could you try updating to it with

    apt update && apt upgrade

and check if things work better?

**Comment by r0bobo** [comment]
It works now. Thank you!
