### ISSUE TITLE
Still issues upgrading packages?

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#6590]
I flagged a similar issue some week ago (#6532). 

I continue to see a low rate of updates. In about 10 days just `emacs` and `rclone`. 

Now I see you have released a new version of `git`, `2.3.1` (22 hours ago), but here, after 22 hours:

```
$ pkg upgrade
Testing the available mirrors:
[*] https://termux.org/packages: ok
[*] https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx: bad
[*] https://termux.mentality.rip/termux-packages-24: ok
[*] https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx: ok
[*] https://grimler.se/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Hit:1 https://grimler.se/game-packages-24 games InRelease
Hit:2 https://grimler.se/science-packages-24 science InRelease
Hit:3 https://its-pointless.github.io/files/24 termux InRelease
Get:4 https://ipfs.io/ipns/k51qzi5uqu5dj05z8mr958kwvrg7a0wqouj5nnoo5uqu1btnsljvpznfaav9nk unstable InRelease [14.0 kB]
Get:5 https://termux.mentality.rip/termux-packages-24 stable InRelease [14.0 kB]
Get:6 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 Packages [240 kB]
Fetched 268 kB in 9s (31.0 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ git --version
git version 2.31.0

$ dpkg -l | grep git
ii  git                2.31.0         aarch64      Fast, scalable, distributed revision control system
```

**Comment by xeffyr** [comment]
https://termux.mentality.rip/termux-packages-24 is a mirror. Mirrors may be updated less frequently and have older package versions.

> I continue to see a low rate of updates.

Send pull requests to have more frequent updates.

**Comment by xeffyr** [comment]
Perhaps termux.mentality.rip is being mirrored from 10.via0.com IPFS gateway which has problem with certificates currently.

@a1batross Could you reconfigure it to mirror from either https://termux.org/packages or grimler.se ?

**Comment by a1batross** [comment]
@xeffyr 
holy Celestia why a simple thing like mirroring something is so complex. 😫 

I'm actually mirroring it from IPFS directly. 
I wrote a script: https://git.mentality.rip/a1batross/gist/src/branch/master/ipfs-get-repos.sh that does `ipfs get` on a repo and then rsync's changed files, thus HTTP access will be faster than any IPFS operation.

Am I doing something wrong? How am I supposed to just make IPFS pull new files? Of course, without getting it frozen, like it does right now for me.

**Comment by angelog0** [comment]
With `termux-change-repo` I chose `grimler.se` for all groups (package, games etc.). Let's see if things work better now.

**Comment by a1batross** [comment]
@xeffyr changed back to apt-mirror from grimler.se.

**Comment by angelog0** [comment]
I wrote

> With termux-change-repo I chose grimler.se for all groups (package, games etc.). Let's see if things work better now.

It seems no...  

I just did another `pkg upgrade` and, to catch the last upgrade for p7zip, I had to re-run `termux-change-repo` to re-set the `grimler.se` mirrors for all repositories (Main, Games, Science, Unstable).  `termux-change-repo` always proposes to edit Main repository and always proposes _Official repositories_ for mirror to use even if one previously had chosen another mirror (for example `grimler.se`).

**Comment by Grimler91** [comment]
p7zip was updated just a few hours ago. All mirrors are not updated instantly, might take several hours or up to a day before updates appear, see [mirror wiki page](https://github.com/termux/termux-packages/wiki/Mirrors).

If you want to lock to a specific repo you can add `export TERMUX_PKG_NO_MIRROR_SELECT=1` to your .bashrc.

**Comment by angelog0** [comment]
@Grimler91 wrote:

> If you want to lock to a specific repo you can add export TERMUX_PKG_NO_MIRROR_SELECT=1 to your .bashrc.

Does it mean that the changes done with `termux-change-repo` are only temporary? valid for that session? and that each time  they are re-set to defaults (unless one adds that environment variable in .bashrc)?

**Comment by Grimler91** [comment]
`pkg` chooses a new mirror (randomly) every 6 h, or earlier if the mirror cannot be reached (see [`pkg`](https://github.com/termux/termux-packages/blob/16b0fabfcdb5dbf857ebfef64980e1dacb2e08ca/packages/termux-tools/pkg#L43)). 

With 

> The termux-change-repo tools also defaults to the official repos,

I meant that everytime you run `termux-change-repo` the default mirror is pre-selected in the tool, that does not mean that the pre-selected mirror is used though

**Comment by sweetman135** [comment]
Hello my friendI have not been able to install Python 3 yet, it gives an error, my Android phone is 8, please help meارسال شده از دستگاه Galaxy من
-------- پیام اصلی --------از: Henrik Grimler ***@***.***> تاریخ: ۲۰۲۱/۴/۴  ۲۰:۱۳  (GMT+03:30) گیرنده: termux/termux-packages ***@***.***> گیرنده کپی: Subscribed ***@***.***> موضوع Re: [termux/termux-packages] Still issues upgrading packages? (#6590) 
pkg chooses a new mirror (randomly) every 6 h, or earlier if the mirror cannot be reached (see pkg).
With

The termux-change-repo tools also defaults to the official repos,

I meant that everytime you run termux-change-repo the default mirror is pre-selected in the tool, that does not mean that the pre-selected mirror is used though

**Comment by Grimler91** [comment]
@sweetman135 Open a new issue and fill in the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=&template=bug_report.md)
