### ISSUE TITLE
I can't download nodejs 

### ISSUE THREAD

**Issue by YazzDev** [termux/termux-packages#6591]
There is the message : 
E: The repository 'https://main.termux-mirror.ml stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by xeffyr** [comment]
termux-mirror.ml should not be used anymore.

Use `termux-change-repo` to switch repository. Use `pkg` when installing packages (checks repository before use).
