### ISSUE TITLE
I am getting this error:

### ISSUE THREAD

**Issue by Marcoslaurenz** [termux/termux-packages#6593]
The repository 'https://main.termux-mirror.ml stable Rel 
N: Metadata integrity can't be verified, repository is disable now

N: Possible case: repository is under maintenance or down (wrong source.list URL?).

**Comment by xeffyr** [comment]
termux-mirror.ml should not be used anymore.

Use `termux-change-repo` to switch repository. Use `pkg` when installing packages (checks repository before use).

**Comment by Marcoslaurenz** [comment]
> termux-mirror.ml ya no deben usarse.
> 
> Utilí conmutar repositorio. Utilí con la instalación de paquetes (comprueba el repositorio antes de usarlos).`termux-change-repo``pkg`

thanks brother I made it

**Comment by maska228** [comment]
> termux-mirror.ml should not be used anymore.
> 
> Use `termux-change-repo` to switch repository. Use `pkg` when installing packages (checks repository before use).

Sorry for necro, but `termux-change-repo` doesnt work for me ,_,

**Comment by xeffyr** [comment]
@maska228 Use `termux-change-repo` to change the **all available repositories** to Grimler's mirror. All means all available on the first menu of `termux-change-repo` and **not** the first one only.

https://github.com/termux/termux-packages/issues/6726 contains all the information with examples on how to use `termux-change-repo`.

**Comment by maska228** [comment]
> @maska228 Use `termux-change-repo` to change the **all available repositories** to Grimler's mirror. All means all available on the first menu of `termux-change-repo` and **not** the first one only.
> 
> https://github.com/termux/termux-packages/issues/6726 contains all the information with examples on how to use `termux-change-repo`.

Thanks!
