### ISSUE TITLE
conio.h for Termux

### ISSUE THREAD

**Issue by CharlesB-eng** [termux/termux-packages#6595]
I'm trying to build a simple calculator, but the compiler needs conio.h.  Does anyone know which package to install?  Thanks!

**Comment by Grimler91** [comment]
Is it this one https://en.wikipedia.org/wiki/Conio.h? Seem to be ms-dos only, and then you'll unfortunately not find it in any repos here.

**Comment by CharlesB-eng** [comment]
Thank you for your help!
