### ISSUE TITLE
Update RGBGS to the latest version.

### ISSUE THREAD

**Issue by Marquessmark11** [termux/termux-packages#6599]
Hi so I was trying to compile pokered on a phone (for the lulz) and also because I cant compile it on any other device. I honestly have no idea how to compile RGBDS for and on termux so I cant do that. So at any time I really dont mind, please update RGBDS to 0.4.2 or newer

**Comment by Marquessmark11** [comment]
when I say rgbgs I mean rgbds oops

**Comment by Grimler91** [comment]
? It already is [0.4.2](https://github.com/termux/termux-packages/blob/fee131542cb788a7ddadfea908ec326c22dded8d/packages/rgbds/build.sh#L5), which is the [latest released version](https://github.com/gbdev/rgbds/releases/tag/v0.4.2).
