### ISSUE TITLE
failed to get home directory

### ISSUE THREAD

**Issue by Hemendra-corder** [termux/termux-packages#6602]
failed to get home directory, using $HOME instead err="user: Current requires cgo or $USER set in environment" $HOME=/data/data/com.termux/files/home

How do I solve this?

**Comment by RalfWerner** [comment]
> How do I solve this?

Problem description ...
Steps to reproduce ...
Expected behavior ...
Additional information ...

**Comment by xeffyr** [comment]
> Current requires cgo or $USER set in environment

```
export USER=$(id -un)
```

**Comment by Hemendra-corder** [comment]
I still do not understand how to solve it, can you tell me the steps.

**Comment by xeffyr** [comment]
Solution is already posted: https://github.com/termux/termux-packages/issues/6602#issuecomment-814826660.
