### ISSUE TITLE
Requesting New Package Speech Dispatcher

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#6606]
## Requesting New Package Speech Dispatcher
*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [√] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

Speech Dispatcher project provides a high-level device independent layer for access to speech synthesis through a simple, stable and well documented interface.

**Link to home page and sources**

1. Home page: https://freebsoft.org/speechd
2. Source code: https://github.com/brailcom/speechd

**Additional information**
Have you compiled or tried to compile the package on device?

Yes, in [TermuxArch](https://termuxarch.github.io/TermuxArch/) with the command `yay speech-dispatcher --noconfirm` which builds the Arch Linux Speech Dispatcher package on device in Termux PRoot.

Speech Dispatcher also installs as an Arch Linux package without the need to compile and appears to function with [TDSR (A console screen reader for macOS and Linux)](https://github.com/tspivey/tdsr) on device in Termux PRoot:
```
[user18:24tdsr]$ ./tdsr
[user@localhost tdsr]$
```

**Comment by thunder-coding** [comment]
Package already available as `speechd`.

Closing

**Comment by SDRausty** [comment]
>Package already available as `speechd`.

Thank you.
