### ISSUE TITLE
500  Internal Server Error [IP: 209.94.90.1 443]

### ISSUE THREAD

**Issue by Gustavo404** [termux/termux-packages#6607]
**Problem description**

Hello, I'm having problems with termux, more specifically with packages, There are several packages that I can't install for days ... when I try to install, I get a 500 (http?) Error exact output; "500 Internal Server Error [IP: 209.94.90.1 443]" I use a Xiaomi Redmi Note 9 Pro (aarch64 android 10) this error happens to me with several packages, I don't seem to have any pattern usually happens when I try to use "wildcards" (*) as; *make*, *lib*, *open* and *tool* but it also happens when I install common packages, like; openssl-static and netcat-openbsd...

**Steps to reproduce**

```
apt install *lib*
```
or
```
pkg install *lib*
```
or
```
apt-get install *lib*
```
(the package manager makes no difference)

**Expected behavior**

normally, what should happen in the example given, is that the libs found by the wildcards (or the packages entered manually) are installed

**Additional information**

```
Do you want to continue? [Y/n] y
Get:90 https://ipfs.io/ipns/k51qzi5uqu5dj05z8mr958kwvrg7a0wqouj5nnoo5uqu1btnsljvpznfaav9nk unstable/main aarch64 libisofs-static aarch64 1.5.4-1 [522 kB]
Err:2 https://dweb.link/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable/main aarch64 libgnutls-static aarch64 3.6.15
  500  Internal Server Error [IP: 209.94.90.1 443]
Err:108 https://ipfs.io/ipns/k51qzi5uqu5dj05z8mr958kwvrg7a0wqouj5nnoo5uqu1btnsljvpznfaav9nk unstable/main aarch64 libsixel-static aarch64 1.8.6-3
  500  Internal Server Error [IP: 209.94.90.1 443]
Err:1 https://k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx.ipns.dweb.link stable/main aarch64 libgmime-static aarch64 3.2.7-2
  500  Internal Server Error [IP: 209.94.90.1 443]
60% [Connected to dweb.link (209.94.90.1)] [Connected to ipfs.io (209.94.90.1)]^C
```
*comments:*
> *not all packages have this problem.*
> *this problem is not common in the most used packages, like python and man.*

*photo*
![Screenshot_2021-04-08-02-14-19-233_com termux](https://user-images.githubusercontent.com/60305898/113977879-3d956900-9811-11eb-8083-a98ccc7e5a2a.jpg)
Thanks!

**Comment by WMCB-Tech** [comment]
Try changing the repo with `termux-change-repo` and choose working repos

**Comment by Gustavo404** [comment]
> Try changing the repo with `termux-change-repo` and choose working repos

thank you so much!!! you solved 4 of my problems, I was also having problems with x11-repo, Unstable-repo and other things related to repositories, this solved the problem perfectly! in case someone is watching this, *just access the menu, and browse as on the computer (using the space bar to check options) and test the repositories until it works.* thank you!
![Screenshot_2021-04-08-03-14-03-065_com.termux.jpg](https://user-images.githubusercontent.com/60305898/113983927-84d32800-9818-11eb-9c8e-c3916a517701.jpg)

**Comment by Grimler91** [comment]
> usually happens when I try to use "wildcards" (*) as

Please don't install `*lib*` and similar. That just a waste of your own disk space (I seriously doubt you have use of all libraries), and more importantly a waste of the limited repository bandwidth. 

If you really feel that you want to install "everything" in case you might need later then instead create a local mirror on some device or computer, to which you sync the repos with aptly (or over ipfs). You can then sync this mirror every now and then and set your termux device to install from the local repository.

**Comment by Gustavo404** [comment]
> > usually happens when I try to use "wildcards" (*) as
> 
> Please don't install `*lib*` and similar. That just a waste of your own disk space (I seriously doubt you have use of all libraries), and more importantly a waste of the limited repository bandwidth. 
> 
> If you really feel that you want to install "everything" in case you might need later then instead create a local mirror on some device or computer, to which you sync the repos with aptly (or over ipfs). You can then sync this mirror every now and then and set your termux device to install from the local repository.

yes, I understand that, "lib" is actually an example of what the libs I use would be, and about limit bandwidth ... thanks for saying, maybe I'm hurting the server with this.
