### ISSUE TITLE
Make comand-not-found optional for bash

### ISSUE THREAD

**Issue by jspricke** [termux/termux-packages#661]
Hi,

could we make the command-not-found optional for bash, so it doesn't need to be installed? I could provide a patch for the bashrc (test for the executable first), but I didn't found if there is actually support for a recommends field in termux. What do you think?

**Comment by xeffyr** [comment]
Done in https://github.com/termux/termux-packages/commit/c4fde3b66cd6f73fd17e7a3bb1adebcae78111f0.

**Comment by r12622** [comment]
(bash InstallTools.sh: command not found)
Why iit shows????
