### ISSUE TITLE
E: Unable to locate package

### ISSUE THREAD

**Issue by Gustavo404** [termux/termux-packages#6610]
**Problem description**

Hi, me and some friends are having a certain problem, more specifically with *unstable-repo packages.* The problem in this case is when we try to install tools that exist in unstable-repo, however, when we try to install tools like sqlmap, hashcat or hydra, we have an error that says;
```
E: Unable to locate package sqlmap
````
![Screenshot_2021-04-08-13-12-33-566_com termux](https://user-images.githubusercontent.com/60305898/114070251-ce9a2d80-986d-11eb-83d8-ef2977a0de42.jpg)
(sqlmap is just an exemple)

we already tried to change the repositories with termux-change-repo but it doesn't fix the problem with unstable-repo tools.
it's a confusing problem, there are more than 5 of us and we've been trying to solve it for a long time, and we haven't been able to.

**Steps to reproduce**

with termux correctly installed and updated:
(unstable-repo already installed)
```
apt install sqlmap
```
"sqlmap" is just an example, it can be exchanged for other packages like hydra, hashcat, among other Unstable-repo tools

**Expected behavior**

normally what should happen, is the tool to be downloaded and installed

**Additional information**

Unstable-repo Instaled:
```
~ $ apt list unstable-repo
Listing... Done
unstable-repo/stable,stable,now 6.0 all [installed]
~ $
```

termux says the command exists
```
~ $ hashcat
The program hashcat is not installed. Install it by executing:
 pkg install hashcat
~ $ sqlmap
The program sqlmap is not installed. Install it by executing:
 pkg install sqlmap
~ $ hydra
The program hydra is not installed. Install it by executing:
 pkg install hydra
```

failed attempt to install the tools
```
~ $ apt install sqlmap
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package sqlmap
~ $ apt install hashcat
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package hashcat
~ $ apt install hydra
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package hydra
~ $
```

**our cell phones**

*Xiaomi:*
```
Redmi Note 9Pro
Android10
aarch64

Redmi 9c
Android10
armv8l
```

*Samsung:*
```
A20
Android10
aarch64

S10
Android10
aarch64

J2
Android7.1.1
amrv71

J2
Android8.1.0
amrv81
```
we tested on all cell phones, the error appears on all

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/FAQ#Where_are_Metasploit_and_Hydra_packages

I won't add back these packages. Do it on your own.
