### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by NehalSinghal** [termux/termux-packages#6621]
Hi, 

This link https://wiki.termux.com/wiki/Building_packages is no longer functional.

**Comment by agnostic-apollo** [comment]
Entire wiki is down at the moment. It's being looked into.

**Comment by NehalSinghal** [comment]
Ok. Thanks. :)

**Comment by agnostic-apollo** [comment]
welcome!

**Comment by xeffyr** [comment]
Seems to be working now.
