### ISSUE TITLE
Python Install is missing almost all modules for Android

### ISSUE THREAD

**Issue by OgSouth** [termux/termux-packages#6622]
pkg install python-tkinter
Checking availability of current mirror: ok
Ign:1 https://main.termux-mirror.ml stable InRelease
Hit:2 https://grimler.se/termux-root-packages-24 root InRelease
Ign:3 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:4 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
Err:6 https://main.termux-mirror.ml stable Release
  Redirection from https to 'http://ww38.main.termux-mirror.ml/dists/stable/Release' is forbidden
Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Hit:7 https://dl.bintray.com/grimler/science-packages-24 science Release
Reading package lists... Done
E: The repository 'https://main.termux-mirror.ml stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
This is what I get trying to install all my modules. I've looked everywhere online, tried everything. Lost an entire day programming. 😞

**Comment by ravener** [comment]
Use `termux-change-repo` and select the grimler.se mirror, the termux-mirror.ml might be down

**Comment by OgSouth** [comment]
Thanks that's exactly what it was. I went to that mirror and it's malicious, it keeps trying to install things and I keep getting redirected to other malicious website's

**Comment by Grimler91** [comment]
termux-mirror.ml was removed [two months ago](https://github.com/termux/termux-packages/commit/b373b3dfff980d5103f8b5122c0b81b0d9faae20#diff-926df3194e5f727be3fefbac2278032a4b2331fa147ddb70c3898602a23765a4), it is no longer a valid mirror

**Comment by OgSouth** [comment]
Oh ok can you remove that from Termux. I'm old user but been out the game for awhile and just started back into programming after 4 years, I just had to factory Data reset my phone. Apps kept installing on my home screen after I went to link. Thank you btw

**Comment by WMCB-Tech** [comment]
> Oh ok can you remove that from Termux. I'm old user but been out the game for awhile and just started back into programming after 4 years,

Outdated versions of termux will still have that mirror, so updating your Termux periodically will keep you up to date and adjusts the working repos

**Comment by xeffyr** [comment]
> so updating your Termux periodically will keep you up to date and adjusts the working repos

Briefly:
* App from F-Droid.
* `pkg upgrade` on regular basis.
