### ISSUE TITLE
debloat 

### ISSUE THREAD

**Issue by ajra28** [termux/termux-packages#6626]
**Problem description**
Screenshot_2021-04-13-20-42-11-808_com termux](https://user-images.githubusercontent.com/67515980/114554262-1a4b3d80-9c99-11eb-8c68-4dd01d529d56.jpg)

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
Bug reports about application misuse as well as about third-party tools are not accepted.

**Comment by ajra28** [comment]
appreciate you bro, i dont have any idea about termux im just follow on youtube tutorial video^^
only i want is to uninstall trash system application
I've done to my phone
 root 
magisk
