### ISSUE TITLE
READ ERROR: "END OF FILE"

### ISSUE THREAD

**Issue by ANDROIDonFIRE** [termux/termux-packages#6628]
Hello

Info:
Im "fooling" around with my Android phone and wanna add it as worker for pool-mining.
But i get READ ERROR: "END OF FILE when trying to use my fav pools.

xmr.pool.gntl.co.uk:10009
xmr.pool.gntl.co.uk:20009
xmr.pool.gntl.co.uk:30009

But it works fine from other miner pools like:

pool.supportxmr.com:3333

Can you maybe help me understand what the problem is?
(see uploaded pictures) https://ufile.io/f/d2wgj

Many thx

**Comment by Grimler91** [comment]
Ask the author of whatever program you are using for help. Closing since this does not seem to be termux related

**Comment by ANDROIDonFIRE** [comment]
READ ERROR: "END OF FILE"

I fucked up!!!!!!!....... he he he.... 
FIX = START ALL OVER if you get this error, YOU HAVE MADE A FUCK UP IN COMMAND OR WALLET ADDRESS....(was in my case).

**Comment by WMCB-Tech** [comment]
bruh, you didn't provide enough information about your problem, and neither this is a termux problem
