### ISSUE TITLE
Linking problem with urcu lib

### ISSUE THREAD

**Issue by depler** [termux/termux-packages#6629]
Trying to build https://github.com/urcu/userspace-rcu with:

```
git clone https://github.com/urcu/userspace-rcu/ --branch v0.12.0
./bootstrap
./configure --prefix=/data/data/com.termux/files/usr
make -j

```
Everything goes fine until linking stage:

```
make[5]: Entering directory '/data/data/com.termux/files/home/userspace-rcu/doc/examples/hlist'
  CCLD     cds_hlist_add_head_rcu
/data/data/com.termux/files/usr/bin/ld: warning: liburcu-common.so.6, needed by ../../../src/.libs//liburcu.so, not found (try using -rpath or -rpath-link)
/data/data/com.termux/files/usr/bin/ld: ../../../src/.libs//liburcu.so: undefined reference to `urcu_memb_reader'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [../Makefile.examples.template:20: cds_hlist_add_head_rcu] Error 1
make[5]: Leaving directory '/data/data/com.termux/files/home/userspace-rcu/doc/examples/hlist'
make[4]: *** [Makefile:15: all] Error 2
make[4]: Leaving directory '/data/data/com.termux/files/home/userspace-rcu/doc/examples/hlist'
```
Is it really linking problem or source code need to be fixed?

**Comment by Grimler91** [comment]
That's a problem in the automake and/or autoconf scripts.

0.12.0 is old. Any particular reason why you are building from that version, instead of the newer ones where they might have fixed the problem?

**Comment by depler** [comment]
I've tried latest version first - same error. The reason to use older version instead of latest is to reduce dependency from the very new autoconf/automake, which probably can break compilation (good old stable). Anyway this is not version problem.

**Comment by Grimler91** [comment]
Right. Consider sending a bug report to the urcu maintainers. Since we don't have the package in our repositories it's not something we can fix
