### ISSUE TITLE
Adding dictionary library to sdcv

### ISSUE THREAD

**Issue by harieamjari** [termux/termux-packages#6630]
So currently, I have installed `sdcv` package on termux, but when tried searching for a word, it gives me an error:
```
$ sdcv word
Nothing similar to word, sorry :(
```

It turns out, I needed to download libraries for `sdcv` according to https://askubuntu.com/questions/191125/is-there-an-offline-command-line-dictionary

Since `/usr/share/stardict/dic/` doesn't exist on termux, I resorted to using `$PREFIX/share/stardict/dic` and installed the dictionary there, but still, `sdcv` isn't picking up:

 ```
 $ sdcv word
Nothing similar to word, sorry :(
```

Nor when I tried to list dictionaries:
```
$ sdcv -l
Dictionary's name   Word count
$
```

### Steps to reproduce
First  download the dictionary: https://web.archive.org/web/20140917131745/http://abloz.com/huzheng/stardict-dic/dict.org/stardict-dictd_www.dict.org_gcide-2.4.2.tar.bz2

Then:
```
mkdir -p $PREFIX/share/stardict/dic/
tar -xvjf downloaded.tar.bz2 -C $PREFIX/share/stardict/dic
```

**Comment by harieamjari** [comment]
Here's what's inside of my `dic` dir:
```
$ pwd                                                                                   /data/data/com.termux/files/usr/share/stardict/dic                                      $ ls                                                                                    stardict-dictd_www.dict.org_gcide-2.4.2

```

**Comment by xeffyr** [comment]
@harieamjari Try to move files from `stardict-dictd_www.dict.org_gcide-2.4.2` to `/data/data/com.termux/files/usr/share/stardict/dic`.

**Comment by harieamjari** [comment]
As I glance in the `man`, hoping a hint would come, the options, `--data-dir` seems to fit to what could solve my problem :

```
$ sdcv --help
...
Application Options:
  -2, --data-dir=path/to/dir     use this directory as path to stardict data directory
```
And, as I used the it:
```
$ sdcv --data-dir=$PREFIX/share/stardict/dic noun
Found 1 items, similar to noun.
-->dictd_www.dict.org_gcide
-->Noun

Noun \Noun\ (noun), n. [OF. noun, nun, num, non, nom, F. nom,
   fr. L. nomen name. See {Name}.] (Gram.)
   A word used as the designation or appellation of a creature
   or thing, existing in fact or in thought; a substantive.
   [1913 Webster]

   Note: By some grammarians the term noun is so used as to
         include adjectives, as being descriptive; but in
         general it is limited to substantives.
         [1913 Webster]
```
It finally worked!
