### ISSUE TITLE
Can this package be ported to Termux?

### ISSUE THREAD

**Issue by MrAdityaAlok** [termux/termux-packages#6631]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [ x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

[Pluseaudio-android](https://github.com/pelya/pulseaudio-android) which outputs through `Android native openSLS`, currently which I think termux one cannot do.
**Link to home page and sources**

1. Home page: https://github.com/pelya/pulseaudio-android
2. Source code: https://github.com/pelya/pulseaudio-android

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.
No, didn't try. I was trying to use other apps to enhance music, from play store, but as pluseaudio of termux do not output through openSLS I could not get it work.

**Comment by xeffyr** [comment]
> which outputs through Android native openSLS, currently which I think termux one cannot do.

Never heard about openSLS but only OpenSLES. Our PulseAudio port supports OpenSLES and AAudio. People here successfully use `mpv`, `cmus` and other PulseAudio-dependent packages.

Please note that PulseAudio from proot'ed (chroot'ed) distributions will not work on Android.

> but as pluseaudio of termux do not output through openSLS I could not get it work.

You either using it wrong or get a some issue with player or sound file cannot be decoded properly.

**Comment by MrAdityaAlok** [comment]
> Never heard about openSLS but only OpenSLES

Sorry, Sir that was a typo 😄

>Our  PulseAudio port supports OpenSLES and AAudio

I ment that when I use apps like [BassBoot](https://play.google.com/store/apps/details?id=audio.sound.effect.bass.virtrualizer.equalizer) from PlayStore, audio played using `cmus`, unlike to `termux-media-player` and `play-audio`  is not enhanced(or captured) by it

**Comment by MrAdityaAlok** [comment]
I got it working via mpd and thank you for help.
