### ISSUE TITLE
zsh module cannot be found with apt install

### ISSUE THREAD

**Issue by fmv1992** [termux/termux-packages#664]
I cannot install the zsh package:
```
-bash-4.4$ apt update && apt install zsh ; apt --version
Hit:1 http://mirrors.tuna.tsinghua.edu.cn/termux stable InRelease
Reading package lists... Done                                    
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package zsh
apt 1.2.12 (aarch64)
```
I'm running the termux from F-Droid 0.46
Do you need further information to help me on this issue?

**Comment by fornwall** [comment]
Could you try running `apt update && apt install zsh` again to see if it was a temporary problem with the mirrors.tuna.tsinghua.edu.cn mirror?

**Comment by fmv1992** [comment]
I just did but got the same results.
Can I use another mirror in the meantime? If so how can I do that? (Google
gives me nothing)

**Comment by fornwall** [comment]
I don't know of another mirror, but could you try the original repository at `http://termux.net`?

**Comment by fmv1992** [comment]
I have tried but got the same:
```
-bash-4.4$ apt update && apt install zsh
Hit:1 http://termux.net stable InRelease
Hit:2 http://mirrors.tuna.tsinghua.edu.cn/termux stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package zsh
```

Any other work arounds?

**Comment by fmv1992** [comment]
Is there any workaround this issue like manual installing or other mirror?

If so can you point me in the right direction?

**Comment by fornwall** [comment]
Could you try to reinstall the system packages?

Run `rm -Rf $PREFIX`, then exit all terminal sessions and restart the app. A new environment should now be installed, start by updating it with:

    apt update && apt upgrade

Can you then install zsh with

    apt install zsh

?

**Comment by fmv1992** [comment]
@fornwall ,

that worked great! I can install zsh now! Thanks : )

**Comment by fornwall** [comment]
@fmv1992 Great! Let me know if you encounter any problems again!

**Comment by rjchaniya** [comment]
How to storage setup in internal storage use

**Comment by rjchaniya** [comment]
pkg install pyathon
Hit:1 https://termux.net stable InRelease
Reading package lists... Done                    Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pyathon

**Comment by rjchaniya** [comment]
Any package not install because this problem
E: Unable to locate package pyathon

**Comment by xeffyr** [comment]
> pkg install pyathon
E: Unable to locate package pyathon

@rjchaniya *Pyathon* is not a package, check this: https://en.wikipedia.org/wiki/Pyathon

Probably you want a **python** ? If so - use `pkg install python`.
