### ISSUE TITLE
muchsync needs hardlinks

### ISSUE THREAD

**Issue by matthiasbeyer** [termux/termux-packages#6644]
So, I am using `muchsync` on my termux and it sometimes complains about permission denied when trying to create hardlinks.

I've seen the [previous discussion](https://github.com/termux/termux-app/issues/837) on the subject and thus I contacted the maintainer of the project whether it would be possible to use symlinks or copies instead of hardlinks.

They answered that symlinks are not a good idea because of the target file vanishing might be a problem, but copies would be an option. This would waste disk-space, but I suppose that's an tradeoff I can agree to when in turn being able to use `muchsync` properly on Android.

What do you think? Would such an option help? Would it be a better idea to make this a compiletime flag or a runtime argument/option?

**Comment by xeffyr** [comment]
A build-time option to enable use of file copies instead of hardlinks would be nice.

The only workaround for now is to run shell under proot with hardlink to symlink conversion functionality enabled.
```
~ $ proot --link2symlink bash
~ $ #your_commands_here
```

**Comment by matthiasbeyer** [comment]
Yeah, I know about `proot` but it only "kindof" works for me and often `proot` just fails. Also, symlinks are not the best solution here. So I guess I'll ping the maintainer and ask for a build-time option on this.

Thanks for your support!
