### ISSUE TITLE
Cant install python

### ISSUE THREAD

**Issue by ak420314** [termux/termux-packages#6646]
![Uploading  #Screenshot_20210417-210855.jpg…]()

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```
![Screenshot_20210417-210855](https://user-images.githubusercontent.com/82718412/115118537-4e886c00-9fc1-11eb-9a78-fb0776d5212f.jpg)

**Comment by xeffyr** [comment]
Run `pkg update` (or `apt update`) and then try `pkg install git python` to install Git and Python.

Package `hydra` has been removed intentionally.

**Comment by ak420314** [comment]
> Run `pkg update` (or `apt update`) and then try `pkg install git python` to install Git and Python.
> 
> Package `hydra` has been removed intentionally.
Oh tank u bro
