### ISSUE TITLE
unable to locate package putty error

### ISSUE THREAD

**Issue by qlife1146** [termux/termux-packages#6653]
I tried to install putty on termux.
However, an error called 'E:unable to location package putty' occurs.
I have also tried package update. Still, the problem is not solved.

**Comment by xeffyr** [comment]
Putty is X11 package, so enable corresponding repository (`pkg install x11-repo`) and then
```
pkg install putty
```

**Comment by qlife1146** [comment]
I tried it.

**Comment by qlife1146** [comment]
> Putty is X11 package, so enable corresponding repository (`pkg install x11-repo`) and then
> 
> ```
> pkg install putty
> ```

I tried it

**Comment by xeffyr** [comment]
Have you tried to do `pkg install x11-repo` before?

**Comment by qlife1146** [comment]
> Have you tried to do `pkg install x11-repo` before?

wow... thx so much

**Comment by qlife1146** [comment]
> Have you tried to do `pkg install x11-repo` before?

Does putty work only in the gui environment?

**Comment by WMCB-Tech** [comment]
Yes, you should run it under VNC/XSDL
