### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by Suryapardana** [termux/termux-packages#6656]
(node:3818) UnhandledPromiseRejectionWarning: Error: marker was not found
    at decodeScan (/data/data/com.termux/files/home/botol/node_modules/jpeg-js/lib/decoder.js:344:15)

**Comment by xeffyr** [comment]
a. Error is somewhere in your code.
b. Your program is not compatible with our Nodejs version.

***

*This is Termux Packages issue tracker. Please do not submit here issues related to your own code or third-party packages.*

**Comment by Suryapardana** [comment]
Ok
