### ISSUE TITLE
Issue with updating packages

### ISSUE THREAD

**Issue by n0w0nd3r** [termux/termux-packages#6658]
Ign:1 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease
Err:2 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 104.21.61.185 443]
Hit:3 https://grimler.se/game-packages-24 games InRelease
Hit:4 https://grimler.se/science-packages-24 science InRelease
Reading package lists... Done
E: The repository 'https://termux.org/packages stable Release' no longer has a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by n0w0nd3r** [comment]
Edit: this only happens when using apt

**Comment by xeffyr** [comment]
Can't confirm issues with 10.via0.com.
![Screenshot_20210420-161949](https://user-images.githubusercontent.com/25881154/115402720-5845e580-a1f4-11eb-964d-aafd16116a11.png)
