### ISSUE TITLE
pip install package fails and behaves weirdly in termux.

### ISSUE THREAD

**Issue by aahnik** [termux/termux-packages#6664]
**Expected behavior:** 

- `pip install <package>` should install the latest stable version of a package from PyPI (python package index)
-  the package concerned is [`tgcf`](https://github.com/aahnik/tgcf) . It is published to PyPI. It installs properly in Ubuntu and windows. 
-  The installation fails in termux

**Steps to reproduce**
- Make sure you have `python` installed in termux
- run `pip install --upgrade pip` to update pip
- In termux, run `pip install tgcf` 
- the latest version of `tgcf` (at the time I am writing) is `0.1.17`
- but `pip` installs an older version `0.0.1`

I also tried pinning the version. `pip install tgcf==0.1.17`. This leads to dependency conflicts.

the installation works smoothly in my Ubuntu development machine. I have successfully installed this on an isolated virtual environment. The installation also succeeds in a docker container running base image of `python:3.9`. The installation also succeeds in windows 10.

**Comment by Grimler91** [comment]
Please provide logs and the output of `termix-info`

**Comment by Grimler91** [comment]
Issue seem to be that cryptg 0.2.post2 cannot be installed for some reason.

Does tgcf require cryptg 0.2.post2 or would 0.2.post0 work as well?

**Comment by aahnik** [comment]
hi, @Grimler91, thanks for helping.

[full logs in termux](https://gist.github.com/aahnik/9d5490f142d49cf30241934c110db62b)

**Comment by aahnik** [comment]
```shell
Collecting tgcf
  Downloading tgcf-0.1.17-py3-none-any.whl (10 kB)
  Downloading tgcf-0.1.16-py3-none-any.whl (10 kB)
  Downloading tgcf-0.1.15-py3-none-any.whl (10 kB)
  Downloading tgcf-0.1.6-py3-none-any.whl (5.7 kB)
  Downloading tgcf-0.0.1-py3-none-any.whl (6.5 kB)
```

## this the weird thing. `pip` tries to install all versions of `tgcf`.❗

I observed a similar error, on alpine linux, with another package of mine. (that also had cryptg as deps)

**Comment by aahnik** [comment]
More logs for debugging.

[Installing in a virtual environment in Ubuntu](https://gist.github.com/aahnik/4498744420bcf9c5bd99e732a1d310cb)

[Installing inside a docker container running python:3.9 base image](https://gist.github.com/aahnik/97daa448e7b4fb5004b2b62a99ecdb39)

**Comment by aahnik** [comment]
hi @Grimler91 , from some discussions with other people, I realized that the problem is most probably being caused by `cryptg` which requires a compilation step.

This is not an issue in Ubuntu, Debian, windows, mac, etc. but in alpine and termux, something is failing. thus cryptg could not be installed.

When will termux support such libraries ?

my package depends on telthon, which depends on cryptg. I want to use cryptg as deps, as it gives performance boost. 

![image](https://user-images.githubusercontent.com/66209958/115670165-bc88b680-a366-11eb-9d36-4ce6c65d48ee.png)

any way that termux could support pip packages that have c deps ?

**Comment by landfillbaby** [comment]
after replicating this in a venv on my own device, i tried `pip install tgcf==0.1.17` to force it to not install older versions. the error that showed up was
`Could not find a version that satisfies the requirement cryptg<0.3,>=0.2.post2 (from tgcf)`
https://pypi.org/simple/cryptg/ says that the latest version is 0.2.post2
so i looked at https://pypi.org/simple/cryptg/ that pip uses internally.
there is no source package for cryptg. only precompiled x86(64) binaries.
this is the source of the problem!

**Comment by aahnik** [comment]
> this is the source of the problem!

that is true.

`cryptg` is a `c` library. 

how can this problem be resolved ?

**Comment by landfillbaby** [comment]
`pip install -U wheel&&pip install https://github.com/cher-nov/cryptg/archive/refs/tags/0.2.post2.tar.gz` doesn't work either, due to a missing "share/tiny-AES-c/aes.h"

**Comment by landfillbaby** [comment]
ah. it's because it's a git submodule.
`git clone --depth=1 --recurse-submodules --branch=0.2.post2 https://github.com/cher-nov/cryptg.git && pip install ./cryptg/ && rm -rf ./cryptg/` works

**Comment by Grimler91** [comment]
So the fix to make tgcf installable through pip would be for cryptg/pypi to also provide source archive for the post2 release, and not only pre-compiled binaries. Unfortunately that is not something we control so users need to use @landfillbaby's workaround to install cryptg before installing tgcf.

**Comment by aahnik** [comment]
I followed @landfillbaby s instructions. now, I am getting errors in the installation of Pillow! (which earlier used to succeed in termux)

[Logs](https://gist.github.com/aahnik/9cbc4c08c3e56992af03e4c3fee349e2) for pillow installation.

---------


just a question, typing in my android is cumbersome. I want to test my packages in termux. but want to use my computer's keyboard. 

can I ssh into my termux, from my computer's terminal? can you please please give a link to the article/docs?

**Comment by landfillbaby** [comment]
pillow is just saying you don't have libjpeg installed
`pkg i libjpeg-turbo`

**Comment by Grimler91** [comment]
For ssh see https://wiki.termux.com/wiki/Remote_Access#SSH. 
See also this blog post for how to ssh over adb, for less lag when device sleeps: https://glow.li/posts/access-termux-via-usb/

**Comment by aahnik** [comment]
hi @Grimler91 , thanks for the links. i started sshd successfully. and also set a password. but how do I access it from  my computer ?

I ran `sshd` in termux.

and in my computer,
```shell
$ ssh u0_a561@192.168.1.5
```

it is giving, `ssh: connect to host 192.168.1.5 port 22: Connection refused`

**Comment by aahnik** [comment]
For my purpose, I think I can use termux docker. I hope it gives a similar environment.

If my package works successfully in termux docker, can I hope that it will work fine in termux ?

**Comment by Grimler91** [comment]
@aahnik you also need to run `passwd` and set a password in termux. Alternatively (more secure), you can transfer ~/.ssh/id_rsa.pub from your computer to termux and append it to (or create) ~/.ssh/authorized_keys. 

After that you should be able to be able to log in with `ssh -p 8022 192.168.1.5` (if your termux device has ip 192.168.1.5). 8022 is the port sshd in termux is listening to, and needs to be 
specified when ssh'ing.

termux-docker probably works for testing your package, as long as internet connection and so on seem to work when using your package in it.

**Comment by aahnik** [comment]
I had already set a password. I mentioned this in my last comment.
