### ISSUE TITLE
PDFtk

### ISSUE THREAD

**Issue by mondalex** [termux/termux-packages#6666]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [✓] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

PDFtk Server is a command-line tool for working with PDFs. It is commonly used for client-side scripting or server-side processing of PDFs.

**Link to home page and sources**

1. Home page: https://www.pdflabs.com/tools/pdftk-server/
2. Source code: https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk-2.02-src.zip

**Additional information**
Have you compiled or tried to compile the package on device? No
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by rikhwanto** [comment]
I checked it up, but it seems that this package is very old and it needs `libgcj` to build which doesn't seem to be available anymore

**Comment by xeffyr** [comment]
It needs JRE which is not available as Termux package.

**Comment by xtkoba** [comment]
Now that we have `openjdk-17`, I suppose it is not very difficult to package this.

Note that we should use the one from https://gitlab.com/pdftk-java/pdftk/, as does the Arch build script in the previous comment.
