### ISSUE TITLE
Error on installing Python

### ISSUE THREAD

**Issue by xer0wastaken** [termux/termux-packages#6667]
Hi there, I'm having a strange issue where whenever I enter ”install pkg python", I get a strange error message that keeps popping up after the y/n prompt, this is a copy and pasted version of it:

Err:1 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable/main aarch64 libsqlite aarch64 3.34.0-1
  404  Not Found [IP: 172.67.212.200 443]
E: Failed to fetch https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx/pool/main/libs/libsqlite/libsqlite_3.34.0-1_aarch64.deb  404  Not Found [IP: 172.67.212.200 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Any help is appreciated, thanks!

**Comment by WMCB-Tech** [comment]
Try doing `pkg update` and try again

if still doesn't work, change working mirrors with `termux-change-repo` and try again

**Comment by xer0wastaken** [comment]
Thanks that worked!

**Comment by Nathan03459** [comment]
Fb
