### ISSUE TITLE
Issues with loading zsh-syntax-highlighting

### ISSUE THREAD

**Issue by mindbound** [termux/termux-packages#667]
When installing [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting), it fails on loading Termux with "_zsh_highlight_load_highlighters:12: no matches found: /data/data/com.termux/files/home/zsh-syntax-highlighting/highlighters/*/".

I installed zsh-syntax-highlighting as per the [installation guide](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md), the main directory is `$HOME/zsh-syntax-highlighting`. The `zsh-syntax-highlighting.zsh` file is sourced at the end of `.zshrc`. Please advise.

**Comment by fornwall** [comment]
Could you write the exact commands you run to setup zsh-syntax-highlighting (and note if you are running under oh-my-zsh)?

**Comment by mindbound** [comment]
I am running under oh-my-zsh (specifically, under the https://github.com/4679/oh-my-termux fork). My installation procedure looks like this:
```
$ cd $HOME
$ git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
$ echo "source $HOME/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> $HOME/.zshrc
$ exit
```

After restarting Termux, I get the aforementioned errors.

**Comment by r0bobo** [comment]
Try installing zsh-syntax-highlighting with [zplug](https://github.com/zplug/zplug). That works with no issues for me.

**Comment by mindbound** [comment]
That did resolve the issue, thank you.

**Comment by dan-santana** [comment]
I'm not sure if it happens to be the same cause, but `unsetopt CASE_GLOB` on my `.zshrc` was responsible for not allowing the glob pattern (`/data/data/com.termux/files/home/zsh-syntax-highlighting/highlighters/*/`) to be expanded when sourcing `zsh-syntax-highlighting.zsh`.

Didn't check the source code, but I suppose the internal implementation on zsh does some kind of progressive checking on all parent directories on the path, but stops on the first "permission denied", which should occur on `/data` on Android. Should be easily reproduced on GNU/Linux with the following:
```zsh
cd $HOME
sudo chmod 751 /home
unsetopt CASE_GLOB
echo $PWD/*
```

It seems @BrainDamage and @Neo-Oli also noticed this on IRC, but no solution/workaround was found (dicussion: https://gitter.im/termux/termux?at=57b1b3a6bc5c9ca6689705b4).
