### ISSUE TITLE
[question] run pkg upgrade without any prompting

### ISSUE THREAD

**Issue by aahnik** [termux/termux-packages#6675]
![image](https://user-images.githubusercontent.com/66209958/115951066-5fbf0480-a4fc-11eb-90a4-cb2db78a8f79.png)

I would love to say Y to all questions. I don't want any prompt.

What to do ?

```
pkg upgrade -y
```
?

the help of pkg upgrade didn't help.

**Comment by WMCB-Tech** [comment]
Here's how you can skip that with 2 variants

* *Never ask you for your confirmation and keep old config files when upgrading packages*
```
pkg upgrade -o Dpkg::Options::="--force-confold" --force-yes -y
```

* *Never ask you for your confirmation and install new config files (This will overwrite your modified config file from the packages you installed*
```
pkg upgrade -o Dpkg::Options::="--force-confold" --force-yes -y
```

**Comment by xeffyr** [comment]
> I would love to say Y to all questions. I don't want any prompt.

Sometimes you will definitely want to read the prompts as in other case package manager will overwrite your configs with the defaults.

**Comment by aahnik** [comment]
I have not done any config. I just want the packages to be updated, after I install termux in my phone.

If packages are not up to date, sometimes I get other errors.

**Comment by aahnik** [comment]
any idea how to resolve this issue

![image](https://user-images.githubusercontent.com/66209958/115954565-64d97f00-a50f-11eb-811e-0537cb345d26.png)


from my idea, this issue occurred because the user did not press anything for a long time ?
