### ISSUE TITLE
Termux loses parent directories and current directory

### ISSUE THREAD

**Issue by Fernal73** [termux/termux-packages#6677]
**Problem description**
```
 $ npm install -g node-fetch
internal/bootstrap/switches/does_own_process_state.js:129
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at process.cwd (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:92:19)
    at new <anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/npm.js:58:19)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/npm.js:48:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```
Error installing node-fetch package on Termux.

Also , this error on executing termux-info:

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```
Both work when `cd ..` is invoked and commands executed.

**Steps to reproduce**
See above.

**Expected behavior**
Package must install.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# sources.list.d/pointless.bak
deb https://its-pointless.github.io/files/ termux extras
# x11-repo (sources.list.d/x11.list)
deb https://ipfs.io/ipns/k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4 x11 main
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.18.31-perf-g89c85bf #1 SMP PREEMPT Tue Oct 22 13:55:14 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Y1

```

**Comment by xeffyr** [comment]
I can't confirm that.

Please ensure that your Termux installation is sane and shell startup files (profile, zshrc, bashrc, etc) are correct and do not overwrite $PWD, $HOME is present and is existing directory with correct ownership and selabels, etc.

Error is on your side. If you believe that it isn't, then provide a complete strace log:
```
strace -fv -s 2000 -o strace.log npm install -g node-fetch
```

![Screenshot_20210424-185733](https://user-images.githubusercontent.com/25881154/115964929-6dda4880-a52f-11eb-955d-287620ac5117.png)

**Comment by Fernal73** [comment]
I'm not sure.
I've seen this happen when the current directory has inadvertently been
deleted. That causes Termux to not find the directory. That's
understandable.
I don't think that's what occured in this instance.

Steps to reproduce something similar:

1) Create a new directory in a branch under than main (say development)
2) cd to newdir
3) add a file
4) git add
5) git commit
6) git push to origin
7) git checkout main
8) git merge --no-edit development

Bingo!
fatal: Unable to read current working directory: No such file or directory

My workaround: Add file from parent directory in this instance.

**Comment by xeffyr** [comment]
That's expected behavior in case of `git`. When you are updating the file tree (say switching to branch), current directory will be deleted if does not exist in a branch you switched too. `git` doesn't care whether this is current working directory or not.

**Comment by Fernal73** [comment]
Apparently, that is what happened except I don't recall doing those git
steps.
I'll let you know if it occurs again.
Thanks.

**Comment by Fernal73** [comment]
Apparently, there's no easy way to add a new directory to another branch from within the directory.
https://stackoverflow.com/questions/3216360/merge-update-and-pull-git-branches-without-using-checkouts/4157106#4157106

**Comment by Fernal73** [comment]
Is the directory to be lost when done in another window created using Ctrl T? I do the above git steps from the parent directory that exists in both branches, commit my changes and push to Github for both branches. I switch to the other window which has the new directory created and bang! The directory no longer exists. I can cd up one level and then cd back and the directory is found once more!

**Comment by Fernal73** [comment]
Similar error discovered [here](https://github.com/joefitzgerald/go-plus/issues/249):

**Comment by Grimler91** [comment]
> Is the directory to be lost when done in another window

If you are in a directory and that directory is deleted from another shell then you get 
```
ls: reading directory '.': No such file or directory
```
From bash when running ls, since the current directory does not exist anymore. This happens on desktop GNU/Linux as well, so not termux specific

**Comment by Fernal73** [comment]
Error no such file or directory, uv_cwd #249

While installing an npm package.

As far as I know, I did not delete the directory. I did have two terminals open on the same directory.
