### ISSUE TITLE
: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

### ISSUE THREAD

**Issue by Sai-kali-G** [termux/termux-packages#6678]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by Sai-kali-G** [comment]
: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by suhan-paradkar** [comment]
Even I am facing issues with ipfs either unstable or x11 repo

**Comment by MTSYuki** [comment]
Just updated successfully on my phone the repository right now at 15:28 GMT.
Try update again later or run `termux-change-repo`.

**Comment by xeffyr** [comment]
> Even I am facing issues with ipfs either unstable or x11 repo

As stated in https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-xeffyr:
```
Primary node can be shutdown during night times (22:00 - 09:00 UTC).
```
which effectively means that if content is not cached on gateway, it would be inaccessible during the mentioned period. Stable 24x7 service is not possible at the moment.

**Comment by oysqurany** [comment]
Possible cause: repository is under maintenance or down (wrong sources.list URL?).
Please solve this problem.

**Comment by xeffyr** [comment]
@oysqurany Please visit https://github.com/termux/termux-packages/issues/6726 and follow instructions under the title `"What you should do as Termux user"`.
