### ISSUE TITLE
feature request: UTF-8 supported ftpd

### ISSUE THREAD

**Issue by Jimmy-Z** [termux/termux-packages#668]
Actually took me a while to figure out what exactly should I fire. By default busybox supports UTF-8 but very limited, for example `ls` will show `à` fine but `中文`(literally "Chinese" in Chinese) will show up as `??` instead. this could be solved by installing coreutils, then use GNU ls instead of busybox ls.

I've checked the busybox package provided by debian, it also behave like this. But currently there is no replacement for busybox ftpd in termux.

* option 1: provide a busybox package compiled with wider UTF-8 support, more specifically, these two settings under "Busybox Library Tuning":
    * "Range of supported Unicode characters", default 767, set it to 0 to disable the check.
    * "Allow wide Unicode characters on output", disabled by default.
* option 2: provide another ftpd package like vsftpd.

**Comment by fornwall** [comment]
Thanks a lot for reporting the issue!

This has now been fixed in version `1.26.2-1` of the busybox package, to which one can update with

    apt update && apt upgrade

**Comment by Jimmy-Z** [comment]
Great!
