### ISSUE TITLE
`ps aux` shows 1970 in the START column

### ISSUE THREAD

**Issue by bpsib** [termux/termux-packages#6687]
**Problem description**
Typing `ps` (from package `procps`) shows `1970` as the start time (under the `START` column) when typing `ps aux`

**Steps to reproduce**
1. Install package `procps` (`pkg install procps`)
2. Type `ps aux`
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
u0_a160   1846  0.0  0.4 4405508 28956 ?       Sl    1970   0:16 com.termux.api
u0_a160   5099  0.0  0.0  12040  1916 pts/22   Ss+   1970   0:02 /data/data/com.termux/files/usr/bin/bash -l
...
```

**Expected behavior**
`ps aux` show show the time/date correctly (or not show the time/date at all if it's a permission issue that can't be solved).

**Additional information**

```
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.9.97 #1 SMP PREEMPT Thu Nov 29 14:55:45 CST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
HUAWEI
Device model:
CLT-L09
```

**Comment by xeffyr** [comment]
> or not show the time/date at all if it's a permission issue that can't be solved

a. Column can't be empty.
b. Will break the tool for root users.
