### ISSUE TITLE
perl build fails

### ISSUE THREAD

**Issue by joeyh** [termux/termux-packages#669]
in docker: bash -x ./build-package.sh perl

    + cd /root/.termux-build/perl/src
    + termux_step_post_make_install
    + cd /data/data/com.termux/files/usr/share/man/man1
    + rm perlbug.1 c2ph.1
    + ln -s perlthanks.1 perlbug.1
    + ln -s pstruct.1 c2ph.1
    + perl -p -i -e s@-specs=/home/fornwall/dc/termux.spec@@g /data/data/com.termux/files/usr/lib/perl5/5.24.0/aarch64-linux/Config_heavy.pl
    /root/termux-packages/packages/perl/build.sh: line 72: /usr/bin/perl: No such file or directory

I don't understand this error, since /usr/bin/perl does exist..

**Comment by joeyh** [comment]
Commented out that line, and it built successfully.

**Comment by fornwall** [comment]
Thanks for reporting - this should now be fixed!
