### ISSUE TITLE
pkg upgrade issue

### ISSUE THREAD

**Issue by pinguftw2** [termux/termux-packages#6691]
`pkg upgrade`

Checking availability of current mirror: ok
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden
Get:1 https://k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx.ipns.dweb.link stable InRelease [14.0 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by xeffyr** [comment]
Use `termux-change-repo` to switch on another repository.

Bintray-based repositories (dl.bintray.com) are going down permanently.

**Comment by pinguftw2** [comment]
I tried `termux-change-repo` but it does not work

**Comment by xeffyr** [comment]
It didn't worked because you most likely used it in a wrong way.

First you need to select repository with which you have problems and only then pick mirror.

**Comment by xeffyr** [comment]
https://user-images.githubusercontent.com/25881154/116244521-ad43a780-a770-11eb-88c6-054fb1950bfd.mp4
