### ISSUE TITLE
I am getting error every time.. 

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-packages#6692]
**Problem description
Android 11
Miui 12
pkg update -y
pkg upgrade -y
Getting error every time....I don't know why..
Please help
![Screenshot_2021-04-26-23-31-32-231_com termux](https://user-images.githubusercontent.com/72664192/116129946-4da1b980-a6e8-11eb-8d2b-b3c6c4214092.jpg)
![Screenshot_2021-04-26-23-35-01-866_com termux](https://user-images.githubusercontent.com/72664192/116129919-45e21500-a6e8-11eb-8019-a7c8c322bbc4.jpg)

**Comment by xeffyr** [comment]
Try `apt update` before `pkg upgrade -y`. If error is still occurs, try selecting a different mirror with `termux-change-repo`.
