### ISSUE TITLE
Package Error

### ISSUE THREAD

**Issue by KentLavi** [termux/termux-packages#6693]
Hello, I recently tried an `apt update` command on my termux, but when I run some commands it gets all errors, when I run the `apt update` command an error appears as below:

`$ apt update
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:2 https://dl.bintray.com/grimler/science-packages-24 science InRelease                                      
Err:3 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Ign:4 https://main.termux-mirror.ml stable InRelease    Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden                                        
Err:6 https://main.termux-mirror.ml stable Release
  Redirection from https to 'http://ww38.main.termux-mirror.ml/dists/stable/Release' is forbidden
Reading package lists... Done                           
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file. 
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.                                                    N: Metadata integrity can't be verified, repository is disabled now.                                            
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).                           
E: The repository 'https://main.termux-mirror.ml stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).`

And when I run an install command like `pkg install php` it shows an error like this:

`$ pkg install php                                       
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done                        
E: Unable to locate package php`

how do i fix this?

**Comment by xeffyr** [comment]
To fix, use `termux-change-repo` and switch to different mirror. Then `pkg upgrade`.

**Comment by awoimbee** [comment]
I just reinstalled termux from the play store (v0.101 from 2020/09/29) and had this issue.
The main repo is still configured to be on Bintray (https://github.com/termux/termux-packages/issues/6348).
How am I supposed to know that I need to run `termux-change-repo` ? Spending 15-20min looking at issues on github isn't a solution, the app is **broken** in its current state.

**Comment by agnostic-apollo** [comment]
@awoimbee Updates have not been released on playstore since last year since we can't push them because termux-app does not comply with current play store polices. You should move to F-Droid releases instead. There is no reasonable way for us to notify users about this other than them checking our communities, wiki or github.

Check https://github.com/termux/termux-app#google-playstore-deprecated

**Comment by gsmitheidw** [comment]
@agnostic-apollo Is there a recommended method to switch to F-Droid from PlayStore without re-installation and broken plugins?
In previous phones I'd used F-Droid but on this occasion, regrettably I used PlayStore

**Comment by agnostic-apollo** [comment]
@gsmitheidw Yes, for Termux app, you can follow the [Backing Up Termux](https://wiki.termux.com/wiki/Backing_up_Termux) instructions to preserve all your data during shifting. The plugins don't store any critical data that I know of and should be safe to uninstall. Only termux `~/` and `$PREFIX` is important to backup. However, you would still need to uninstall all playstore apks and reinstall from F-Droid, no way around that (without root).

https://github.com/termux/termux-app#installation

**Comment by Tayaga334** [comment]
> To fix, use `termux-change-repo` and switch to different mirror. Then `pkg upgrade`.

What did you meab “switch to different mirror”?

**Comment by Tayaga334** [comment]
“mean”

**Comment by Tayaga334** [comment]
> To fix, use `termux-change-repo` and switch to different mirror. Then `pkg upgrade`.

By the way, it's not work at all, still met same error.

**Comment by agnostic-apollo** [comment]
Switch all mirrors #6726

**Comment by RB-DEV-2000** [comment]
Not working at all

**Comment by xeffyr** [comment]
Do exactly as in mentioned issue https://github.com/termux/termux-packages/issues/6726.

https://user-images.githubusercontent.com/25881154/116244521-ad43a780-a770-11eb-88c6-054fb1950bfd.mp4

***

dl.bintray.com has gone forever and can't be fixed. Bintray is owned and managed by JFrog Inc. and not by Termux. They shut down service as has been announced.
