### ISSUE TITLE
Could we build mirror for termux-packages?

### ISSUE THREAD

**Issue by huiyiqun** [termux/termux-packages#67]
[We](http://mirrors.tuna.tsinghua.edu.cn/) maintain a mirror site which provide service for Chinese users.

Could we mirror termux-package?

**Comment by fornwall** [comment]
Sounds like a nice service!

The apt repository is available at http://apt.termux.com/dists/stable/, what can I do to help you maintain a mirror?

**Comment by huiyiqun** [comment]
We could mirror the packages via https directly, but it better if you could provide rsync service which is used by many repositories.

**Comment by fornwall** [comment]
Ok, will look into the possibility of setting up an rsync service at apt.termux.com soon!

**Comment by bigeagle** [comment]
Hey, we've finished syncing using HTTP. the mirror url is https://mirrors.tuna.tsinghua.edu.cn/termux/

**Comment by fornwall** [comment]
Great work! Then I'll skip setting up rsync for now!

**Comment by helloqiu** [comment]
I find ```apt-mirror``` is a good choice to create a mirror.
But termux-packages doesn't have ```Packages.gz``` nor ```Packages.bz2```.So I hack the apt-mirror and here is [it](https://gist.github.com/helloqiu/278ce7668011e3bbafa1223374379c31).
I don't know perl so it can log many warnings.
But it works. :)

**Comment by hosiet** [comment]
@fornwall Rsync is way much better and safer than http/https. Could you please set up rsync daemon?

Once set up, [we](https://mirrors.ustc.edu.cn) would be happy to mirror termux packages.
