### ISSUE TITLE
Text Not Showing Up

### ISSUE THREAD

**Issue by hashshadyy** [termux/termux-packages#6700]
when i type things in the console they dont show up until i press space, put a period, or a slash.

**Comment by xeffyr** [comment]
That's keyboard bug, not Termux bug. You need to turn on the option shown in https://wiki.termux.com/wiki/Terminal_Settings#Workaround_for_some_keyboards_issues.

See video how to do that with alternate text input field which should work for broken keyboards:

https://user-images.githubusercontent.com/25881154/116405360-3b369580-a838-11eb-845e-018c91922d16.mp4

You will need to restart Termux app once this option is enabled.
