### ISSUE TITLE
Mirror under construction and missing sign

### ISSUE THREAD

**Issue by gituser-007-etc** [termux/termux-packages#6702]
E: The repository 'https://science.termux-mirror.ml science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by gituser-007-etc** [comment]
E: The repository 'https://science.termux-mirror.ml science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by gituser-007-etc** [comment]
i changed to different mirrors, same everywhere

**Comment by xeffyr** [comment]
> i changed to different mirrors

You haven't done this properly. You should change the "science repo", not the main one.

https://github.com/termux/termux-packages/issues/6691#issuecomment-827583397
