### ISSUE TITLE
ghostscript 9.53.2 build failed

### ISSUE THREAD

**Issue by stesen** [termux/termux-packages#6704]
**ghostscript 9.53.2 build failed**

**Steps to reproduce**
./build-package.sh -a arm ghostscript

**Expected behavior**
build fail

**Additional information**

> arm-linux-androideabi-clang  -DHAVE_MKSTEMP -DHAVE_FILE64 -DHAVE_FSEEKO -DHAVE_MKSTEMP64 -DHAVE_FONTCONFIG -DHAVE_LIBIDN -DHAVE_SETLOCALE   -DHAVE_BSWAP32 -DHAVE_BYTESWAP_H -DHAVE_STRERROR -DHAVE_ISNAN -DHAVE_ISINF  -DHAVE_PREAD_PWRITE=1 -DGS_RECURSIVE_MUTEXATTR=PTHREAD_MUTEX_RECURSIVE -O2 -DNDEBUG -I/data/data/com.termux/files/usr/include  -Wall -Wstrict-prototypes -Wundef -Wmissing-declarations -Wmissing-prototypes -Wwrite-strings -fno-strict-aliasing -Werror=declaration-after-statement -fno-builtin -fno-common -Werror=return-type -DHAVE_STDINT_H=1 -DHAVE_DIRENT_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYS_TIMES_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIBDL=1 -DGX_COLOR_INDEX_TYPE="unsigned long long" -D__USE_UNIX98=1   -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -Oz -DHAVE_RESTRICT=1 -DUSE_LIBICONV_GNU -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include -fno-strict-aliasing -DHAVE_POPEN_PROTO=1    -I./obj -I/home/stesen/.termux-build/ghostscript/src/base -I/home/stesen/.termux-build/ghostscript/src/devices  -DWHICH_CMS="lcms2mt" -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -Oz -DHAVE_RESTRICT=1 -DUSE_LIBICONV_GNU -I/data/data/com.termux/files/usr/include/freetype2 -I/data/data/com.termux/files/usr/include/libpng16 -I/data/data/com.termux/files/usr/include -DSHARE_FT=1 -o ./obj/fapi_ft_1.o -c /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c
> In file included from /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:28:
> /home/stesen/.termux-build/ghostscript/src/base/gserrors.h:159:9: warning: '__printflike' macro redefined [-Wmacro-redefined]
> #define __printflike(fmtarg, firstvararg) \
>         ^
> /home/stesen/.termux-build/_cache/android-r21d-api-24-v3/bin/../sysroot/usr/include/sys/cdefs.h:93:9: note: previous definition is here
> #define __printflike(x, y) __attribute__((__format__(printf, x, y)))
>         ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:137:5: error: expected function body after function declarator
>     FF_realloc(FT_Memory memory, long cur_size, long new_size, void *block)
>     ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:236:34: error: use of undeclared identifier 'file_default_buffer_size'
>                                  file_default_buffer_size, &ps, pfn.iodev,
>                                  ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:259:20: error: use of undeclared identifier 'FF_stream_read'
>     ftstrm->read = FF_stream_read;
>                    ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:260:21: error: use of undeclared identifier 'FF_stream_close'
>     ftstrm->close = FF_stream_close;
>                     ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:314:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>         FF_free(s->ftmemory, a_face->ft_inc_int);
>         ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:350:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>         FF_free(s->ftmemory, a_inc_int_info->glyph_data);
>         ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:509:13: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>             FF_free(s->ftmemory, i);
>             ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:524:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>         FF_free(s->ftmemory, a_inc_int);
>         ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:572:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>         FF_free(s->ftmemory, s->bitmap_glyph);
>         ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:577:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>         FF_free(s->ftmemory, s->outline_glyph);
>         ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:825:21: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>                     FF_free(s->ftmemory, bmg);
>                     ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:834:21: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>                     FF_free(s->ftmemory, olg);
>                     ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:928:25: error: use of undeclared identifier 'FF_free'
>     s->ftmemory->free = FF_free;
>                         ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:929:28: error: use of undeclared identifier 'FF_realloc'
>     s->ftmemory->realloc = FF_realloc;
>                            ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:1123:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>         FF_free(s->ftmemory, s->bitmap_glyph);
>         ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:1128:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>         FF_free(s->ftmemory, s->outline_glyph);
>         ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:1253:21: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>                     FF_free(s->ftmemory, own_font_data);
>                     ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:1287:21: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>                     FF_free(s->ftmemory, own_font_data);
>                     ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:1305:17: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>                 FF_free(s->ftmemory, own_font_data);
>                 ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:1315:17: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>                 FF_free(s->ftmemory, own_font_data);
>                 ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:1762:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>         FF_free(s->ftmemory, s->outline_glyph);
>         ^
> /home/stesen/.termux-build/ghostscript/src/base/fapi_ft.c:1767:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
>         FF_free(s->ftmemory, s->bitmap_glyph);
>         ^
> 17 warnings and 6 errors generated.
> make: *** [/home/stesen/.termux-build/ghostscript/src/base/lib.mak:1336: obj/fapi_ft_1.o] Error 1
>

**Comment by stesen** [comment]
I'm trying to fix in
#https://github.com/termux/termux-packages/pull/6705

**Comment by Grimler91** [comment]
What distro are you using? It works in ubuntu (and the docker image).

**Comment by xeffyr** [comment]
@Grimler91 I ran into that error few times when I haven't executed `./clean.sh`.

**Comment by Grimler91** [comment]
I think I have only seen it when building outside the docker image, on arch

**Comment by stesen** [comment]
> What distro are you using? It works in ubuntu (and the docker image).

```
cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Pop!_OS 20.10"
```


haven't tested in docker

**Comment by stesen** [comment]
> @Grimler91 I ran into that error few times when I haven't executed `./clean.sh` (using Docker image).

stiil met the error after run `./clean.sh` .

I'm moving to docker now
