### ISSUE TITLE
dropbear: segfault during an incoming connection

### ISSUE THREAD

**Issue by drygdryg** [termux/termux-packages#6706]
**Problem description**
I have configured Dropbear according to the [wiki](https://wiki.termux.com/wiki/Remote_Access#Dropbear), and when connecting from my PC via OpenSSH, I get an error on the server side:
![image](https://user-images.githubusercontent.com/43933400/116592980-46b5b980-a929-11eb-82de-d3193943e40a.png)

**Steps to reproduce**
Install and configure Dropbear, according to the [Termux wiki article](https://wiki.termux.com/wiki/Remote_Access#Dropbear). Connect to the server using OpenSSH client.

**Expected behavior**
Dropbear should accept the connection and the SSH session should be open.

**Comment by Grimler91** [comment]
Can't reproduce on aarch64 or arm. Also looks weird that the user is nonexistent/null, I don't get that. 

What is your output of termux-info?

**Comment by xeffyr** [comment]
@Grimler91 I can reproduce it. Just do Dropbear setup steps as in Wiki and then connect with OpenSSH client.

It seems to be happening due to null pointer dereference because `ses.authstate.pw_name` seems to be null.

> Password auth succeeded for '(null)'

**Comment by drygdryg** [comment]
> What is your output of termux-info?

```
Application version:
0.112
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.9.262-greenforce-g18d3ea8987ea-dirty #1 SMP PREEMPT Tue Mar 23 23:46:28 MSK 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 5A
```
I also observe this issue when connecting from Termux via Dropbear SSH client:
`$ ssh 127.0.0.1 -p 8022`
or
`$ ssh root@127.0.0.1 -p 8022`

**Comment by Jaimy85** [comment]
Have the same issue with Android 11 phone:
```Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
golang/stable 2:1.17 aarch64 [upgradable from: 2:1.16.7]
Android version:
11
Kernel build information:
Linux localhost 4.14.190-21840848-abA715FXXU5BUF1 #1 SMP PREEMPT Wed Jun 9 18:27:09 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A715F
```
Works on Android 9 VM:

```
Application version:
0.117
Packages CPU architecture:
x86_64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.19.110-android-x86_64-g066cc1d #1 SMP PREEMPT Wed Mar 25 11:32:46 CST 2020 x86_64 Android
Device manufacturer:
innotek GmbH
Device model:
VirtualBox
```

**Comment by DUOLabs333** [comment]
I have the same problem as well. Don't know if it depends on what repository you use though.

**Comment by xtkoba** [comment]
Seems like depending on Android version?

**Comment by xtkoba** [comment]
Not failing until segfault seems to be due to <a href="https://github.com/termux/termux-packages/blob/994d9934727884c3f86027c607954631125ab002/packages/dropbear/svr-authpasswd.c.patch">`svr-authpasswd.c.patch`</a>, which completely removes the logic for checking `valid_user` from `svr_auth_password()`. Note that <a href="https://github.com/termux/termux-auth/blob/9fff2f3677c44e764c8ff3dcb28a38f042480158/termux-auth.c#L94">`termux_auth()`</a> ignores user name.

**Comment by xtkoba** [comment]
So we should ignore the user name when fulfilling `struct passwd` and instead rely on the current uid. This should cause no problem because the `dropbear` package in Termux is configured as non-multiuser.
