### ISSUE TITLE
When i run command pip install cryptography in termux

### ISSUE THREAD

**Issue by lusifer123** [termux/termux-packages#6707]
When i run command `pip install cryptography` it throw error. 
Please help me to fix this.

`WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cryptography/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cryptography/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cryptography/                 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cryptography/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cryptography/
Could not fetch URL https://pypi.org/simple/cryptography/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/cryptography/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping                                        ERROR: Could not find a version that satisfies the requirement cryptography (from versions: none)
ERROR: No matching distribution found for cryptography`

**Comment by xeffyr** [comment]
`pkg upgrade` before attempting to install something, including installations over `pip`.

**Comment by lusifer123** [comment]
> `pkg upgrade` before attempting to install something, including installations over `pip`.

Already did that
