### ISSUE TITLE
postgresql can't start a server on Android 10

### ISSUE THREAD

**Issue by chenyulue** [termux/termux-packages#6710]
I have followed the steps to setup the postgresql shown [here](https://wiki.termux.com/wiki/Postgresql). When I start a server by 

```shell
pg_ctl -D $PGDATA start
```

The shown information in the terminal tells me that the server started. However, when I check it by 

```shell
pg_ctl -D $PGDATA status
```

It tells me "pg_ctl: so server running".

I repeat the same steps on my another cellphone with the android version of 7.1.1, and every thing works well.

Actually, on my cellphone with the android version of 10, `sshd` also can't start a server, but `sshd -d` works. In contrast, on my cellphone with the android version of 7.1.1, `sshd` also works fine.

I don't know whether this is a bug of postgresql or just related to something in the os of the specific version.

**Comment by Grimler91** [comment]
Maybe something (like another postgresql and another sshd process) are already running and using those ports? 

Does `netstat -tulpn` or `ps aux` show any running processes that might interfere?

**Comment by chenyulue** [comment]
No, there are no processes using the ports. The information displayed are:

```shell
~ $ netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
netstat: no support for `AF INET (tcp)' on this system.
~ $ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
u0_a273  30373  0.0  0.0  37308  5560 pts/0    S<s   1970   0:00 /data/data/com.termux/files/usr/
u0_a273  30547  1.0  0.0  35512  4176 pts/0    R<+   1970   0:00 ps aux
```

This information shows that no processes take the ports.

**Comment by xeffyr** [comment]
> No, there are no processes using the ports.

Because netstat doesn't work on Android 10+.

**Comment by xeffyr** [comment]
How you verified that server does not work? You can't connect or it just is not shown by `ps`?

**Comment by chenyulue** [comment]
@xeffyr 
`pg_ctl -D $PGDATA status` shows "pg_ctl: so server running", and `nmap localhost` only shows:

```shell
PORT        STATE           SERVICE
80/tcp      open            http
```

While in my phone with android 7.1.1, `nmap localhost` shows:

```shell
PORT        STATE           SERVICE
80/tcp      open            http
5432/tcp  open            postgresql
8022/tcp  open            oa-system
```

And I cannot connect to the server, either.

**Comment by chenyulue** [comment]
After some search, this may be due to [https://source.android.com/setup/start/android-10-release#background_apps_launching](https://source.android.com/setup/start/android-10-release#background_apps_launching).

**Comment by xeffyr** [comment]
@lasorda Off-topic, but anyway you are looking for https://wiki.termux.com/wiki/Termux-services, if need to start `sshd` when Termux is opened.

**Comment by spz2020** [comment]
em .....

**Comment by spz2020** [comment]
reopen it
