### ISSUE TITLE
apk compiling script

### ISSUE THREAD

**Issue by wmartinmimi** [termux/termux-packages#6714]
i want to add this into the termux wiki

it is because compiling apk projects are difficult and searching in the wiki about apk building will only give me buildApk, which has no information about how to compile my own apk project

i only want to help other android java coders, please don't think this as an advertisement

**Link to home page and sources**

1. Home page: i don't have one, but it has a README.md...
2. Source code: https://github.com/wmartinmimi/compile-apk

it is a bash script for compiling apk projects,
compatible with the projects of ant,  JavaNIDE, and some old gradle projects
(compatible with most projects that does not need gradle)

this bash script is created to simplify the build process.

the script uses packages aapt, ecj, and dx

call the script at the apk project root
with one argument of the location of android.jar

also note i may not be able to actively maintain this script, but i will try my best

**Comment by wmartinmimi** [comment]
also this is my first time trying to publicly publish a code, please tell me what i did wrong if i did done something wrong

**Comment by xeffyr** [comment]
Please understand that Wiki is a place for Termux usage tips and tricks. This is not a place for promoting own projects, scripts and so on.

If you want to share your stuff, please do this on community pages like https://www.reddit.com/r/termux/. But doing so in official documentation and bug tracker is strongly discouraged.

**Comment by wmartinmimi** [comment]
thanks for explaining :)

**Comment by Sajjadalrawy** [comment]
لم اقوم بعمل اي شي من هاذه

في الأحد، ٢ أيار، ٢٠٢١ ٥:٥٦ م martinmimi ***@***.***> كتب:
