### ISSUE TITLE
rustc is not compatible with libllvm12

### ISSUE THREAD

**Issue by BrunoDSL** [termux/termux-packages#6717]
**Problem description**
 
Attempting to run rustc on the latest version of termux results in the error `CANNOT LINK EXECUTABLE "rustc": library "libLLVM-11.so" not found` . After checking the package lists, the one offered in the repo is version 12 and only that.

**Steps to reproduce**

- Install the latest version of termux
- Install rust
- Attempt to run `rustc`

**Expected behavior**

Either a version of rust that is compatible with libllvm12 shoud be provided or a way to install version 11.

**Additional information**

```
Application version:
0.112
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 3.10.108-NPD26.48-24-1 #1 SMP PREEMPT Fri Apr 30 07:52:41 CEST 2021 armv7l Android
Device manufacturer:
Motorola
Device model:
Moto G Play
```

**Comment by xeffyr** [comment]
Known issue and it will be fixed in next build (https://github.com/termux/termux-packages/commit/40dda773cbe6fe8fbd0af23b1fe6090e25eafca8).
