### ISSUE TITLE
Repo seems to be down

### ISSUE THREAD

**Issue by NONAN23x** [termux/termux-packages#6723]
Updating the apt returns a 403 error and says repo might be down, also unstable-repo cannot install metasploit
![Screenshot_2021-05-03-11-11-26-147_com termux](https://user-images.githubusercontent.com/61901753/116844366-8cf86a80-ac00-11eb-8158-6567784741b2.jpg)

**Comment by WMCB-Tech** [comment]
Change repo with `termux-change-repo` and select `grimler.se` and upgrade all packages

> also unstable-repo cannot install metasploit

Metasploit is removed from Termux Repositories
