### ISSUE TITLE
Nethunter isse

### ISSUE THREAD

**Issue by monster55555** [termux/termux-packages#6729]
$ nethunter
proot error: execve("/usr/bin/env"): Function not implemented
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot --help`.
proot error: can't chmod '/data/data/com.termux/files/usr/tmp/proot-31947-b8UfZX': Function not implemented
proot error: can't chdir to '/home/kali': Function not implemented
$

**Comment by xeffyr** [comment]
NetHunter issues are not Termux issues. Don't report NetHunter issues here.

**Comment by xeffyr** [comment]
You may look https://github.com/Termux/proot/issues for proot-related problems/bugs.
