### ISSUE TITLE
Apt update problem

### ISSUE THREAD

**Issue by mukesh7766063808** [termux/termux-packages#6735]
![IMG_20210504_162432](https://user-images.githubusercontent.com/82068975/116995008-243fe980-acf7-11eb-817e-7aa42449eb45.jpg)

How to solve apt update forbidden problem ?

How to solve issue ?

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/6726

**Comment by mukesh7766063808** [comment]
When it will start.

**Comment by Grimler91** [comment]
@mukesh7766063808 you need to change to another mirror. See instructions in issue I linked.

**Comment by mukesh7766063808** [comment]
What is meaning of mirror here ?
Image showing mirror or repository.

**Comment by xeffyr** [comment]
Here is a video showing what you need to do.

https://user-images.githubusercontent.com/25881154/116244521-ad43a780-a770-11eb-88c6-054fb1950bfd.mp4

`dl.bintray.com` repository has gone and will not be available anymore. Use `termux-change-repo` to pick something else. If you still have issues, then you either picked the invalid repo or changed only main one.

***

> What is meaning of mirror here ?

Mirror = repository copy but on alternate host.

**Comment by WMCB-Tech** [comment]
Mirror is an alternate link for the repository, so if one mirror is down the  you choose an alternative working mirror

choose the `grimler.se` mirror repository  (main,science,games,x11,unstable,root)

**Comment by mukesh7766063808** [comment]
Thank you.

**Comment by AndreaCallia** [comment]
I tried all possoble mirrors, but it always says `403 Forbidden`. I attach here the output on the case of the Grimler mirror.

```
[*] Official repositories selected
    Changing main repository
    Changing game repository
    Changing science repository
[*] Running apt update
Err:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
  403  Forbidden [IP: 18.193.131.58 443]
Err:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
  403  Forbidden [IP: 18.193.131.58 443]
Get:1 https://k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx.ipns.dweb.link stable InRelease [14.0 kB]
Reading package lists... Done  
E: Failed to fetch https://dl.bintray.com/grimler/game-packages-24/dists/games/InRelease  403  Forbidden [IP: 18.193.131.58 443]
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games InRelease' is no longer signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: Failed to fetch https://dl.bintray.com/grimler/science-packages-24/dists/science/InRelease  403  Forbidden [IP: 18.193.131.58 443]
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science InRelease' is no longer signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
```

**Comment by xeffyr** [comment]
Don't select "Official repositories selected". Select repositories by Grimler instead.

https://user-images.githubusercontent.com/25881154/116244521-ad43a780-a770-11eb-88c6-054fb1950bfd.mp4
