### ISSUE TITLE
Termux repository under maintenance (changing repo dosent help) 

### ISSUE THREAD

**Issue by BillyQuinlan** [termux/termux-packages#6739]
Whenever I try to run the apt update && apt upgrade && apt install python ffmpeg && pip install YouTube-dl command in termux I get the following screen
![Screenshot_20210504-131430_Termux](https://user-images.githubusercontent.com/83666863/117050171-ac63c600-acda-11eb-9a2e-19baf4fbffe1.jpg)
 I tried changing my repository and I got this screen
![Screenshot_20210504-131358_Termux](https://user-images.githubusercontent.com/83666863/117050347-dc12ce00-acda-11eb-8d0e-4be6d1d16d2d.jpg)
 This happened after I tried to install YouTube-dl in termux following [This tutorial ](https://www.reddit.com/r/Piracy/comments/baufql/youtubedl_the_easy_way_on_android/)  I have used it before and it worked however, on my new phone (same model as my old one) when I installed it everytime I tried to download a Video from Instagram it would give me an error (it worked downloading on everywhere else) so I tried to unistall it and do it again. To uninstall it all I did was unistall the app and then when I tried to reinstall it and try again I got this issue. I'm not good at the termux, coding thing and was following that guide so idk what I should do.

**Comment by agnostic-apollo** [comment]
Also change `science` and `game` repos. Check #6726
