### ISSUE TITLE
var/log/installer/initial-status.gz is missing

### ISSUE THREAD

**Issue by gsauthof** [termux/termux-packages#674]
For getting a list of manually installed packages doing something like

    apt list --installed | grep -v automatic

or using the output of `dpkg --get-selections` minus auto-installed packages listed in  `usr/var/lib/apt/extended_states` are good approximations.

But this list still includes the pre-installed packages, i.e. the ones that are part of the base system.

What is missing is something like `var/log/installer/initial-status.gz` (available e.g. on Ubuntu) that could be used to filter the above described package list more.

**Comment by lucasrangit** [comment]
You could create this manually on non-Ubuntu debian system by running the following after you've built your root file system and installed any system packages.

    gzip -c --best /var/lib/dpkg/status > /var/log/installer/initial-status.gz

I found this to be the only way on Debian to have a complete snapshot of the status of packages right after system installation.
