### ISSUE TITLE
pkg update / apt update not working showing Forbidden

### ISSUE THREAD

**Issue by MDisHere** [termux/termux-packages#6743]
Hey there I'm new in Termux and still learning about it.
So, today I accidentally uninstall Termux and reinstall it after few minutes but
When I try to **update** or **upgrade** it by using command lines
 **pkg update** or **apt update** it showing some errors like link "forbidden" and 
"Wrong Source list" something like this.

[apt update](https://drive.google.com/file/d/1JXtcHyVaenXKgkDf4cGrE_zFjhMgRBA6/view?usp=drivesdk)

[pkg update](https://drive.google.com/file/d/1JmrC68yefq9mi1EC-DqPfqOsI4P5KH12/view?usp=drivesdkl)

**NOTE: I don't know how to attach an image with this so I have give u the link please check it out
and help me**

Please anybody help me to fix this issue, I really don't know what to do know

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/6726

**Comment by MDisHere** [comment]
Thank You so much sir

**Comment by Hemanth226** [comment]
Please fix this

**Comment by WMCB-Tech** [comment]
@Hemanth226 Solution is already given above

---

If you're still on Google play, it's highly advisable to migrate to F-Droid as newer versions of Termux has bintray-less repositories set

**Comment by Hemanth226** [comment]
TQ,sir you mean download F-Droid version

**Comment by Hemanth226** [comment]
Any link is provided

**Comment by MDisHere** [comment]
@WMCB-Tech where I will get F-Droid version of Termux can u please tell me sir

**Comment by WMCB-Tech** [comment]
~~Hmm, the OP deleted his message~~

@MDisHere See https://github.com/termux/termux-app#installation

**Comment by unknow2403** [comment]
whay not working update ?

Pada tanggal Rab, 5 Mei 2021 04:52, MDisHere ***@***.***>
menulis:
