### ISSUE TITLE
Not getting move access in storage ( I'm using f1vm to get root access)

### ISSUE THREAD

**Issue by mohitpatil30501** [termux/termux-packages#6746]
Hi guyz, Mohit here
I not have rooted my device and not want to do it, So for that I'm using f1vm (http://f1vm.com/)  which supports to root access.
When I termux in my original android it went good, but when I use it in f1vm there are some error like 
1. I can't able to move any file .
2. apt update gives me error like repository is under maintenance 
3. pkg install <package> can't able to work properly
And many more....

If you have any idea about this please let me know
And 
If you want any output or any info about issue in brief to solve please tell me.
I can definitely drop that here. 

Thank You
Keep learning, Keep Growing, Love Coding

**Comment by xeffyr** [comment]
1. F1VM doesn't give you real root access. It is aka `proot -0` or `fakeroot`, but not more.
2. Termux doesn't support F1VM Android runtime, so whatever issues are expected. In your case `apt-key` fails and this is a known issue, but it is a wontfix.

**Comment by mohitpatil30501** [comment]
> 1. F1VM doesn't give you real root access. It is aka `proot -0` or `fakeroot`, but not more.
> 2. Termux doesn't support F1VM Android runtime, so whatever issues are expected. In your case `apt-key` fails and this is a known issue, but it is a wontfix.

Can you suggest me other way, Because I'm new in this.
Just started engineering in computer so can you help me...?

Because I don't want to root my mobile currently...

**Comment by xeffyr** [comment]
I can only suggest to use Termux on normal Android OS. Without these fake VMs, known as VMOS or F1VM - these two are same and they are not virtual machines unlike their description states.

Every root method which claims to work without rooting device is either limited in functionality (works within virtual environment only without affecting device state) or totally fake (just user id change). If you wish to perform any action shown in https://wiki.termux.com/wiki/Getting_started#Is_root_required, you will need to root device. No other way.

**Comment by mohitpatil30501** [comment]
Thank You 😊

**Comment by Aziris256** [comment]
Hi members, I have some question about termux.
If I have a virtual space like x8 sandbox app.
Can i use termux like a rooted user in that virtual space?

**Comment by twaik** [comment]
No.

**Comment by Aziris256** [comment]
Hi
