### ISSUE TITLE
What is that issue and how to resolve it please help me  in this issue

### ISSUE THREAD

**Issue by MrDeadpool05** [termux/termux-packages#6752]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

**Link to home page and sources**

1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.
![Screenshot_2021-05-05-22-47-37-932_com termux](https://user-images.githubusercontent.com/48741393/117182515-102de200-adf4-11eb-902a-e61fa97c8c2c.jpg)
![Screenshot_2021-05-05-22-47-49-978_com termux](https://user-images.githubusercontent.com/48741393/117182520-12903c00-adf4-11eb-9396-2bb73d6a840d.jpg)
![Screenshot_2021-05-05-22-47-55-669_com termux](https://user-images.githubusercontent.com/48741393/117182523-1328d280-adf4-11eb-90d6-b70f08545d24.jpg)

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/6752

**Comment by MrDeadpool05** [comment]
How I resolve this issue I didn't understand what is happening I want to install it in my android device help me

**Comment by MrDeadpool05** [comment]
Or provide complete guide if u can

**Comment by Grimler91** [comment]
Sorry, I meant to link to https://github.com/termux/termux-packages/issues/6726, you have a video with exact steps there
