### ISSUE TITLE
Not taking command of pkg update and pkg upgrade

### ISSUE THREAD

**Issue by blackdevil123446** [termux/termux-packages#6754]
Hello sir ,
In my termux its not taking pkg update && pkg upgrade -y && pkg install wget curl openssh git -y this command and showing the error of server is in maintenance or down,
 but it is installing the cmatrix and python 
Can you pls help me  how to resolve this problem.
Thank you 
![Screenshot_2021-05-06-08-26-31-381_com termux](https://user-images.githubusercontent.com/83741711/117235670-c6211c80-ae44-11eb-9a76-5e97deb070e5.jpg)

**Comment by WMCB-Tech** [comment]
See https://github.com/termux/termux-packages/issues/6726
