### ISSUE TITLE
Packages not working

### ISSUE THREAD

**Issue by 5H460N** [termux/termux-packages#6757]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```
apt update && apt upgrade
Get:1 https://k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx.ipns.dweb.link stable InRelease [14.0 kB]
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Get:3 https://k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx.ipns.dweb.link stable/main aarch64 Packages [242 kB]
Ign:4 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:5 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Err:6 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by xeffyr** [comment]
Please follow instructions listed in https://github.com/termux/termux-packages/issues/6726
