### ISSUE TITLE
Help again this time! 

### ISSUE THREAD

**Issue by Tayaga334** [termux/termux-packages#6759]
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
![Edited_20210506_201932](https://user-images.githubusercontent.com/83761784/117304917-75dba600-aea8-11eb-8906-a390ca803372.jpg)

**Comment by xeffyr** [comment]
See https://github.com/termux/termux-packages/issues/6726 for instructions how to fix that.

**Comment by Tayaga334** [comment]
> See #6726 for instructions how to fix that.

“Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease                           Err:2 https://dl.bintray.com/grimler/game-packages-24 games Release                               403  Forbidden
Get:3 https://grimler.se/termux-packages-24 stable InRelease [13.1 kB]
Get:4 https://grimler.se/science-packages-24 science InRelease [13.3 kB]                        Get:5 https://grimler.se/termux-packages-24 stable/main all Packages [22.6 kB]                  Get:6 https://grimler.se/termux-packages-24 stable/main arm Packages [276 kB]                   Get:7 https://grimler.se/science-packages-24 science/stable all Packages [20.4 kB]
Get:8 https://grimler.se/science-packages-24 science/stable arm Packages [28.7 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).”
-I still have that error

**Comment by Tayaga334** [comment]
![Uploading Edited_20210506_204108.jpg…]()

**Comment by xeffyr** [comment]
Then you doing something wrong. You need to change all repositories, not the main one only. Do exactly as on this video:

https://user-images.githubusercontent.com/25881154/116244521-ad43a780-a770-11eb-88c6-054fb1950bfd.mp4

And use app from F-Droid, not Google Play.
