### ISSUE TITLE
Kali linux doesn't install on my device 

### ISSUE THREAD

**Issue by atulbhagat** [termux/termux-packages#6763]
![Screenshot_2021-05-07-01-07-48-008_com termux](https://user-images.githubusercontent.com/83800050/117397593-1ae29700-af1a-11eb-84ef-d0a8a1f3c5eb.jpg)
After download it shows rootfs corrupted 
Please help to fix this issue.

**Comment by xeffyr** [comment]
Termux packages have nothing to do with Kali Linux. Report issues to author of Kali Linux installer instead.
