### ISSUE TITLE
ffmpeg 4.4 stream_loop -1 not working

### ISSUE THREAD

**Issue by samierkkila** [termux/termux-packages#6765]
**Problem description**
ffmpeg stream does not start when using stream_loop -1 together with filter_complex overlay. With stream_loop 0 stream is ok, but of course doesn't update the overlay.

How to reproduce:

'ffmpeg',
'-thread_queue_size', '1024', 
'-i', 'rtsp://...',
'-f', 'image2',
'-stream_loop', '-1',
'-i', 'picture.png',
'-filter_complex', 'overlay=(main_w-overlay_w)/2:main_h*0.1-overlay_h',
'-acodec','aac',
'-ar', '44100',
'-ab', '128k',
'-f', 'flv',
'-g', '30',
'-vcodec', 'libx264',
'-preset', 'ultrafast',
'-crf', '30',
'rtmp://...'

In single line:

ffmpeg -thread_queue_size 1024 -i rtsp://... -f image2 -stream_loop -1 -i picture.png -filter_complex "overlay=(main_w-overlay_w)/2:main_h*0.1-overlay_h" -acodec aac -ar 44100 -ab 128k -f flv -g 30 -vcodec libx264 -preset ultrafast -crf 30 rtmp://...

ffmpeg version 4.4 is the problem. Works fine on ffmpeg 4.3.2.

**Expected behavior**
Should loop overlay infinitely as it does in ffmpeg 4.3.2 and earlier.

**Additional information**
Is it possible to downgrade to ffmpeg 4.3.2...
```

```

**Comment by samierkkila** [comment]
Problem fixed by entering:
-r 15 -loop 1
instead of:
stream_loop -1

**Comment by xtkoba** [comment]
Closing as resolved.
