### ISSUE TITLE
error installing cmake

### ISSUE THREAD

**Issue by bi2b** [termux/termux-packages#6771]
i got this error while trying to install cmake by executing pkg install cmake
`Err:1 https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable/main arm libuv arm 1.40.0
  404  Not Found [IP: 209.94.90.1 443]
Err:2 https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable/main arm cmake arm 3.19.6
  404  Not Found [IP: 209.94.90.1 443]
E: Failed to fetch https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx/pool/main/libu/libuv/libuv_1.40.0_arm.deb  404  Not Found [IP: 209.94.90.1 443]
E: Failed to fetch https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx/pool/main/c/cmake/cmake_3.19.6_arm.deb  404  Not Found [IP: 209.94.90.1 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by xeffyr** [comment]
Repository provides `cmake` of version `3.20.2`. Version `3.19.6` is not available, so your error is expected.

`pkg update`
