### ISSUE TITLE
I was trying to clone my github but its not allowing me to write my password

### ISSUE THREAD

**Issue by fizzy199** [termux/termux-packages#6772]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [ ] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

**Link to home page and sources**

1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
> I was trying to clone my github but its not allowing me to write my password

That means you have a typo in URL or cloning a private repository. If you are cloning a private repository, you need to specify access token instead of password.

Refer to Github documentation as this issue has nothing to do with Termux (and issue template is wrong btw).
