### ISSUE TITLE
speedtest-cli unusable/errors out with 'UnicodeEncodeError:'

### ISSUE THREAD

**Issue by mcurly** [termux/termux-packages#6780]
**Problem description**

After installing latest python from termux package repository, and installing `speedtest-cli`, from then on, issuing `speedtest-cli` command ends up with a traceback pointing to an `UnicodeEncodeErrorr: `

**Steps to reproduce**

`pkg it python`
`pip list`
`Package    Version`
`---------- -------`
`pip        21.1.1`
`setuptools 56.0.0`

Then installing `speedtest-cli` with command: `pip install --upgrade speedtest-cli` checking out if it got installed with

```
pip list
Package       Version
------------- -------
pip           21.1.1
setuptools    56.0.0
speedtest-cli 2.1.3
```

then, trying to use it...

`speedtest-cli`

Yields:

```
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/speedtest-cli", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/speedtest.py", line 1990, in main
    shell()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/speedtest.py", line 1876, in shell
    speedtest = Speedtest(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/speedtest.py", line 1095, in __init__
    self.get_config()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/speedtest.py", line 1125, in get_config
    uh, e = catch_request(request, opener=self._opener)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/speedtest.py", line 730, in catch_request
    uh = _open(request)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/speedtest.py", line 537, in http_open
    return self.do_open(
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 1294, in _send_request
    self.putheader(hdr, value)
  File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 1226, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2122' in position 39: ordinal not in range(256)
```

**Expected behavior**
 a working internet speedtest with ping/icmp latency and downloading and uploading speeds.

**Additional information**
 
```termux-info
Application version:
0.112
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.232-QuicksilveR™-v2.5-lineage/1fb40505 #1 SMP PREEMPT Tue May 4 12:45:18 PDT 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8T
```

**Comment by kcubeterm** [comment]
Can't reproduce. Do you still getting the same error.

**Comment by suhan-paradkar** [comment]
Even I can't reproduce the issue... I am at the same pip version

**Comment by mcurly** [comment]
@kcubeterm , @kcubeterm and @xeffyr  thanks.

After being notified of your contributions and the issue that I reported was closed, and having noticed that pip had been updated yesterday I can't no longer reproduce the issue. I must also note that I don't have lineage os 18.1 installed. Instead of that I have latest stable MIUI.eu  for my redmi note 8t willow, which is Android 10, instead of Android 11 from that unofficial lineage os.

Sorry for this late report and I agree that the issue should be closed, at least for now.

Thanks to all of you.

**Comment by mcurly** [comment]
@kcubeterm , @kcubeterm and @xeffyr  thanks.

After being notified of your contributions and the issue that I reported was closed, and having noticed that pip had been updated yesterday I can't no longer reproduce the issue. I must also note that I don't have lineage os 18.1 installed. Instead of that I have latest stable MIUI.eu  for my redmi note 8t willow, which is Android 10, instead of Android 11 from that unofficial lineage os.

Sorry for this late report and I agree that the issue should be closed, at least for now.

Thanks to all of you.

**Comment by mcurly** [comment]
@kcubeterm , @kcubeterm and @xeffyr  thanks.

After being notified of your contributions and the issue that I reported was closed, and having noticed that pip had been updated yesterday I can't no longer reproduce the issue. I must also note that I don't have lineage os 18.1 installed. Instead of that I have latest stable MIUI.eu  for my redmi note 8t willow, which is Android 10, instead of Android 11 from that unofficial lineage os.

Sorry for this late report and I agree that the issue should be closed, at least for now.

Thanks to all of you.

**Comment by kcubeterm** [comment]
Github issue or did intentionally ? @mcurly

**Comment by mcurly** [comment]
> Github issue or did intentionally ? @mcurly

Sorry. I don't know exactly what happened.

I was constantly receiving a message stating that I could not comment that time so I kept on trying and that was the result I somehow inadvertently spammed this thread and I apologize again for that.

Sorry
