### ISSUE TITLE
How to use python-dev

### ISSUE THREAD

**Issue by dumb-stuff** [termux/termux-packages#6798]
**Problem description**

So I want to use python-dev and I know that it is already installed but how do I gonna execute it?
**Steps to reproduce**

Actually not issue but it is question
**Expected behavior**

Execute with command python-dev or something
**Additional information**

**Comment by WMCB-Tech** [comment]
It's a package only with development headers and files, but `*-dev` packages no longer included, seems you have fairly outdated termux installation

See https://wiki.termux.com/wiki/No_more_-dev_packages

**Comment by dumb-stuff** [comment]
@WMCB-Tech I mean how to execute it in termux because I know that dev package is merged but I just want to know how to execute the dev package like if I want to launch python dev so I need to type ```bash 
python3-dev (example)
```
etc.

**Comment by WMCB-Tech** [comment]
@dumb-stuff `python-dev` binaries contains:

```
python3-config
python3m-config
```

But those are included in the main `python` package

You can query files by extracting the deb package and see what's inside of it, by doing

```
dpkg -x package.deb packageroot
```

**Comment by xeffyr** [comment]
> So I want to use python-dev and I know that it is already installed but how do I gonna execute it?

You can execute binaries. Dev package doesn't provide binaries, so *can you execute it*? Obviously no.

Dev packages provide only static libraries and headers and they used by compiler to build native extensions for Python modules.  Providing information on what are Python modules, what are native extensions, how to build them, etc, is beyond the scope of Termux issue tracker. Internet has a complete information on such topic. For example, header files are important for working with Cython, learn more at https://cython.org/.
