### ISSUE TITLE
php not working after downgrade to 7.4.12

### ISSUE THREAD

**Issue by sahads** [termux/termux-packages#6801]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```
![Screenshot_20210514-133414](https://user-images.githubusercontent.com/79436659/118241374-aed3d600-b4b9-11eb-8f37-3aa94fa5f32e.jpg)

showing like this

**Comment by Grimler91** [comment]
Having old versions of only some programs does not work. You either need to downgrade php and all its dependencies, or keep all packages at the latest available versions.
