### ISSUE TITLE
I tried to put login/pass in the url `git clone https://user:name@server.com/git/repo` and I still get authentication failed, so this is not a keyboard issue. The same command on my PC works fine

### ISSUE THREAD

**Issue by hackneyyard** [termux/termux-packages#6802]
I tried to put login/pass in the url `git clone https://user:name@server.com/git/repo` and I still get authentication failed, so this is not a keyboard issue. The same command on my PC works fine

_Originally posted by @JulienMaille in https://github.com/termux/termux-packages/issues/1751#issuecomment-405111916_

**Comment by hackneyyard** [comment]
i said "cloning to repo"
but it is not working

**Comment by Grimler91** [comment]
Maybe something is wrong with your internet connection, or maybe you have written url wrong.

If you think something is wrong on termux's end, then open a bug report and fill in the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=&template=bug_report.md).
