### ISSUE TITLE
(some) golang packages cannot be built

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#6803]
**Problem description**

Some golang packages cannot be built anymore, supposedly after a golang update. They give an error looking something like:

```
no required module provides package foobar: go.mod file not found in current directory or any parent directory; see 'go help modules'
```
So far I have had problems with these packages:
```
gbt
gotty
keybase
rush
shell2http
```
but there are probably more.

**Steps to reproduce**

Try to build any of the packages above in the docker image.

**Expected behavior**

Packages should be buildable.

**Comment by kcubeterm** [comment]
`go mod init $PKG_name`
`go mod tidy` 
 Helped me to build rush successfully in ubuntu. Didn't tested in docker.

**Comment by Grimler91** [comment]
`go mod init $PKG_name` seem to be the fix indeed, thanks

**Comment by Grimler91** [comment]
With `go mod init keybase; go mod tidy`, `keybase` still fails with

```
go: keybase/go/kbfs/libkbfs imports
	github.com/vividcortex/ewma: github.com/vividcortex/ewma@v1.2.0: parsing go.mod:
	module declares its path as: github.com/VividCortex/ewma
	        but was required as: github.com/vividcortex/ewma
```
but the others work.

**Comment by thunder-coding** [comment]
Facing similiar errors while building `proton-bridge`. `go mod tidy` fixed it

**Comment by Grimler91** [comment]
Closing, most packages have been fixed.
