### ISSUE TITLE
Micro editor crashes when Ctrl+X is pressed

### ISSUE THREAD

**Issue by suhan-paradkar** [termux/termux-packages#6805]
**Problem description**

**Steps to reproduce**

While editing a file with micro , press Ctrl+X
It crashes and there is no way out except
closing the session from the notification panel or from long press menu.

**Expected behavior**

It either must send micro to background, or ask a prompt to close it as it does when Ctrl+Q is pressed, but not crash
**Additional information**

```
Application version:
0.112
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# sources.list.d/termuxblack.list
deb https://hax4us.github.io/TermuxBlack/ termuxblack main
# sources.list.d/abhacker.repo.list
deb [arch=all,aarch64] https://abhackerofficial.github.io/abhacker.repo/ abhacker main
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
# sources.list.d/holehan.list
deb https://termux.holehan.org/ termux extras
# sources.list.d/paradkar.repo.list
deb [arch=all,aarch64] https://suhan-paradkar.github.io/ termux extras
# x11-repo (sources.list.d/x11.list)
deb https://termux.com/x11-packages-bin x11 main
# unstable-repo (sources.list.d/unstable.list)
deb https://termux.com/unstable-packages-bin unstable main
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #2 SMP PREEMPT Sat Apr 3 00:49:44 CST 2021 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH2083
```

**Comment by xeffyr** [comment]
I can't reproduce the issue.

Do you use any customizations or plugins for `micro`? Ctrl-X cuts the line, It doesn't move editor to background or triggers crash.

**Comment by suhan-paradkar** [comment]
@xeffyr I have rhe following plugins installed

```
status (1.0.0)
autoclose (1.0.0)
comment (1.0.0)
diff (1.0.0)
ftoptions (1.0.0)
linter (1.0.0)
literate (1.0.0)
```

**Comment by leapofazzam123** [comment]
Looks like i tries to copy the line while cutting the line (for some reason), as i do ctrl-x, the line was in my clipboard

**Comment by xeffyr** [comment]
Cut line means exactly copy the line to clipboard deleting it from text. Issue probably happens when one or more [plugins](https://github.com/termux/termux-packages/issues/6805#issuecomment-841760696) installed and/or when certain Termux packages are installed (`termux-api`?).

**Comment by thunder-coding** [comment]
As @xeffyr said, this seems to be due to some plugins installed. I can't reproduce here
