### ISSUE TITLE
Help me fix this error! 

### ISSUE THREAD

**Issue by Tayaga-334** [termux/termux-packages#6811]
qemu-system-x86_64: cannot set up guest memory 'pc.ram': Out of memory

**Comment by suhan-paradkar** [comment]
> qemu-system-x86_64: cannot set up guest memory 'pc.ram': Out of memory

Fo you have enough device storage?

**Comment by Tayaga-334** [comment]
> > qemu-system-x86_64: cannot set up guest memory 'pc.ram': Out of memory
> 
> Do you have enough device storage?

27,89 GB/32,00 GB

**Comment by Tayaga-334** [comment]
> > qemu-system-x86_64: cannot set up guest memory 'pc.ram': Out of memory
> 
> Do you have enough device storage?

But now is 15,66 GB/32,00 GB.

**Comment by Tayaga-334** [comment]
> > qemu-system-x86_64: cannot set up guest memory 'pc.ram': Out of memory
> 
> Do you have enough device storage?

But after i reinstalled the app, and open again, download those qemu, I still got that error.

**Comment by suhan-paradkar** [comment]
Can you send the command that you have passed?

**Comment by WMCB-Tech** [comment]
Make sure you also have sufficient ram as well not only the device's internal storage memory,

**Comment by xeffyr** [comment]
Specify lower ram allocation. Pick a value below 40% of your device's memory.

Example: if your device has 4gb of RAM, you should specify `-m 1536M`, if it has 2gb - `-m 768M` and so on.
