### ISSUE TITLE
How to Install Info Pages by Hand

### ISSUE THREAD

**Issue by ThoJer** [termux/termux-packages#682]
Is there an 'official' way to Install Info Pages by Hand?

**Comment by fornwall** [comment]
If you have an `*.info` file, you can install it using install-info (https://www.gnu.org/software/texinfo/manual/texinfo/html_node/Invoking-install_002dinfo.html), like with

    install-info ed.info $PREFIX/share/info/dir

The `install-info` program is available from the `texlive` package:

    apt install texinfo
