### ISSUE TITLE
Installing python isn't working

### ISSUE THREAD

**Issue by ACE1774** [termux/termux-packages#6823]
> Cannot install packages such as pip, rsa and many more.

btw, pip is part of `python`.
```
pkg install python
```
isn't working ???

_Originally posted by @xeffyr in https://github.com/termux/termux-packages/issues/3742#issuecomment-488304796_

**Comment by Grimler91** [comment]
? Maybe you are experiencing https://github.com/termux/termux-packages/issues/6726

**Comment by ACE1774** [comment]
Already done this.

**Comment by xeffyr** [comment]
Then do
```
pkg update
pkg install python
```

**Comment by ACE1774** [comment]
check your mail. please
