### ISSUE TITLE
Apt update problem

### ISSUE THREAD

**Issue by speedyboy6** [termux/termux-packages#6824]
I can't do apt update
When I do apt update it says
$ apt update && apt upgrade
Reading package lists... Done
E: Could not get lock /data/data/com.termux/files/usr/var/lib/apt/lists/lock - open (11: Try again)
E: Unable to lock directory /data/data/com.termux/files/usr/var/lib/apt/lists/
$

Pls.. help

**Comment by xeffyr** [comment]
You have package manager running in another session.

Termux, specifically `apt` package manager, doesn't support parallel package installations.

**Comment by speedyboy6** [comment]
Can you pls.. tell me I can I solve this problem?
I am new to this
