### ISSUE TITLE
QEMU slow emulation (upstream issue)

### ISSUE THREAD

**Issue by mjuned47** [termux/termux-packages#6830]
Hey !
I found bug/issue of slow emulation on Recent versions of QEMU ( 5.x or more )

Issue :
  Bug on QEMU 5.x or more
  Guest : Windows XP (32bit) (Probably all 32bit Guest OS)
  Tested Same WinXP with QEMU 4.2 and there was no such lag and slow emulation problem (mouse pointer lags)

Environment :
  Tested this bug with QEMU 5.2 on Native Termux and Proot/chroot Linux (Ubuntu) and found same result (slow emulation)
  Tested Same WinXP with QEMU 4.2 on Native Termux and Proot/chroot Linux and found no such lag and slow emulation issue

Fix :
This issue was because of this commit 
https://gitlab.com/qemu-project/qemu/-/commit/b55f54bc965607c45b5010a107a792ba333ba654

Undo this commit to fix this :
Edit cpu.c file(QEMU-5.x/6.0) , find this line and undo this commit

I have tested this fix and it works fine now !

**Comment by suhan-paradkar** [comment]
> Undo this commit to fix this :
Edit cpu.c file(QEMU-5.x/6.0) , find this line and undo this commit

I have tested this fix and it works fine now !


It would be better if you open a Pull Request doing the same @mjuned47

**Comment by mjuned47** [comment]
Alright i will do it !

**Comment by xeffyr** [comment]
If you have found bug in QEMU, please report issue to QEMU developers. As I do not know what consequences would be of reverting this commit, e.g. emulation instability, I won't implement such change as QEMU patch.

Can you prove that suggested change is safe? - Please provide a qualified description on how this affects QEMU internally, so I can be sure that nothing will be broken. Please note that "it cause slow emulation" is not a *qualified description*.

For now I'm closing this issue.

**Comment by mjuned47** [comment]
I have booted Guest os (WinXP). And experienced stable emulation, no lag , working as it was.
If you say , i can provide video on booting xp with my changes of qemu

**Comment by xeffyr** [comment]
@mjuned47 I don't need video or something like "I booted x/y/z without lag and so on".

I have asked you to provide the **qualified description** about your change. If you don't know anything about how QEMU works, I won't revert https://gitlab.com/qemu-project/qemu/-/commit/b55f54bc965607c45b5010a107a792ba333ba654.

**Comment by xeffyr** [comment]
Ok, I have found https://gitlab.com/qemu-project/qemu/-/issues/286. Let's see comments from QEMU developers, which solution the would propose.

**Comment by mjuned47** [comment]
I was going to send you this link. https://gitlab.com/qemu-project/qemu/-/issues/286 and i did changes from this link.

Sorry i can't provide you "qualified description" as I'm not developer. I can only tell that this changes works for me.

I did open this issue #6651 but it was closed by you commenting that "something heavy is running in background" and "incorrect shut down".

I thought reporting this issue and test to you so that you could understand this issue properly and can do something about this bug/issue.
Thank you for reopening and considering this issue seriously.

**Comment by WMCB-Tech** [comment]
Hi, i have patched QEMU within that Implementation and decided to create debfiles, created from docker termux package builder

I tested Windows XP 32-bit (SP3) full, untrimmed and it's fast with no noticable lag (barely a little bit)

Attachments:
QEMU 32-bit: https://cdn.discordapp.com/attachments/712954974983684137/858598684580773929/qemu-system-i386_15.2.0-6_aarch64.deb

QEMU 64-bit: https://cdn.discordapp.com/attachments/712954974983684137/858598685482942504/qemu-system-x86-64_15.2.0-6_aarch64.deb

Though only for arches with arm64, but you could test this version of qemu see if running 32-bit guests are fast

**Comment by mjuned47** [comment]
Update : they have fixed this issue and update will be released In next month with QEMU 6.1 version.
I will update quickly after release

**Comment by xeffyr** [comment]
QEMU has been updated to v6.1.0 in commit https://github.com/termux/termux-packages/commit/5afbf21f917af51a19b25c70638b191b10785287. Will be available shortly for installation (packages.termux.org) and within hours on mirrors.
