### ISSUE TITLE
 ncurses-ui-libs : Depends: ncurses (= 6.2.20200725-2) but 6.2.20200725-3 is to be installed

### ISSUE THREAD

**Issue by lindadoudou** [termux/termux-packages#6832]
**Problem description**

![image](https://user-images.githubusercontent.com/13118142/118776471-9e0cd100-b8ba-11eb-8ccd-be0047d23f3a.png)

try to install python via pkg failed, error message : ` ncurses-ui-libs : Depends: ncurses (= 6.2.20200725-2) but 6.2.20200725-3 is to be installed`

**Steps to reproduce**

`pkg install python`

**Expected behavior**

install python via pkg 

**Additional information**

* Termux application version:
* Android OS version:
* Device model:
![image](https://user-images.githubusercontent.com/13118142/118776623-c4327100-b8ba-11eb-98a6-29d8453c933f.png)

**Comment by shankerwangmiao** [comment]
We have finished sync from ifs upstream. Grateful if @lindadoudou could verify that the package can be successfully installed now, please.

**Comment by lindadoudou** [comment]
![image](https://user-images.githubusercontent.com/13118142/119920445-f15bdf00-bf9e-11eb-8b1c-624d94a52d30.png)
I have been successfully install python via apt on termux.
Thank you so much. :heart:
