### ISSUE TITLE
still not working.

### ISSUE THREAD

**Issue by ACE1774** [termux/termux-packages#6838]
Then do
```
pkg update
pkg install python
```

_Originally posted by @xeffyr in https://github.com/termux/termux-packages/issues/6823#issuecomment-843981131_

**Comment by Grimler91** [comment]
We have no idea what is happening on your device. We cannot help you if you do not provide any information. If you want help then fill in [the bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=&template=bug_report.md)

**Comment by ACE1774** [comment]
I sent a mail to xeffyr but termux deleted my comment. 
![Screenshot_20210520-141846_Termux](https://user-images.githubusercontent.com/84329812/118967050-da5a3300-b987-11eb-9a82-7dcc263f0115.jpg)

**Comment by Grimler91** [comment]
You still have not filled in the bug report template. Why should we use our time to help you if you do not even take the time to fill in the template?

You won't get any response over email, sending emails are a waste of everyone's time as an answer there would not benefit other people looking for answers to the same or a similar questions.

From your screenshot I cannot see any issues. It tells you that python is already installed and that there is no package named pip, which is correct, pip is part of `python`.

**Comment by ACE1774** [comment]
already filled your form pip is not working just want a solution if you
can't help fine.
Thank you for your precious time.

**Comment by dj308668** [comment]
Change the repo
