### ISSUE TITLE
Install failed in AVD

### ISSUE THREAD

**Issue by wcchh** [termux/termux-packages#684]
Hi, I try to install just built mosquitto debs on AVD but failed. 
ABI: x86_64
> error processing archive mosquitto_1.4.10_aarch64.deb (--install): package architecture (aarch64) does not match system (x86_64)

ABI: x86
> error processing archive mosquitto_1.4.10_aarch64.deb (--install): package architecture (aarch64) does not match system (x86)

ABI: armeabi-v7a
> error processing archive mosquitto_1.4.10_aarch64.deb (--install): package architecture (aarch64) does not match system (arm)

But it succeed to install on real phone.

I wish to know how to test them on AVD, that will be more smooth for my work.
Any suggestion will be nice!

**Comment by vishalbiswas** [comment]
You need to compile the package for the arch of your avd

**Comment by wcchh** [comment]
Yah! I tried another avd with arm64 : arm64-v8a, then it works ! Thanks.

Do we have the frag to specify abi type to build? or only aarch64?

**Comment by vishalbiswas** [comment]
When building `./build-package.sh -a <arch> <package-name>` will let you do that. Alternatively, you can also set `TERMUX_ARCH` to your desired one.
Run `./build-package.sh` without any options to see all available options.

**Comment by wcchh** [comment]
Got it and thanks a lot!
