### ISSUE TITLE
How can you make pacman not conflict with termux? 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-packages#6842]
**Problem description**

Hello, a friend @Maxython a compiled pacman for termux, is there any way that pacman packages do not conflict with those of termux?, or if possible, an alternative file system? 

![Screenshot_20210520-154606](https://user-images.githubusercontent.com/64093255/119047508-9fee9700-b983-11eb-95c5-a48cd68a39f1.png)

**Comment by Maxython** [comment]
The first solution is to remove all packages except the system ones. To do this, also need to configure pacman so that it does not install the termux system packages.

**Comment by Yisus7u7** [comment]
It may be, as it would be very difficult to have to be compiling packages

**Comment by Yisus7u7** [comment]
@WMCB-Tech

**Comment by Maxython** [comment]
I agree

**Comment by Grimler91** [comment]
You can't really use two independent package managers.

To use pacman you should port and build the core packages with pkgbuild, create a minimal bootstrap, and then remove $PREFIX and replace it with your bootstrap.
To do that you would need to adapt termux's build script to generate something that pacman recognizes, instead of a deb.

**Comment by WMCB-Tech** [comment]
You might use pacman for development-use cases only like creating a pacman-based package for arch

**Comment by Yisus7u7** [comment]
If I know that, but well, very soon I'll get a computer, with manjaroo, is it possible to use the termux build environment to make packages for pacman that work in termux?

**Comment by Maxython** [comment]
Who cares, here's the [repository](https://github.com/Maxython/pacman-for-termux)

**Comment by xeffyr** [comment]
Does it work at all? What's the point of installing Arch Linux packages outside chrooted environment?

What about hardcoded paths & system calls blocked by seccomp? Also: https://wiki.termux.com/wiki/Differences_from_Linux

![Screenshot_20210521-143129](https://user-images.githubusercontent.com/25881154/119131022-9cb9e080-ba41-11eb-8cbf-f0c744d00a65.png)

**Comment by Maxython** [comment]
This pacman is just being developed and is not fully configured for the termux environment.  And this is exactly what I am doing.

**Comment by Yisus7u7** [comment]
As I said before, the best solution so far is to compile packages.

**Comment by xeffyr** [comment]
@Yisus7u7 Yes, packages should be either recompiled or re-packed from .deb to .pkg.tar.xz format (note that it is not a just tarball).

**Comment by Yisus7u7** [comment]
@xeffyr One question, if I extract the files from the deb packages they make in termux, and pack them in a pacman package, will it work?

**Comment by Yisus7u7** [comment]
That is, for example, I unzip the wget deb file, and those files that contained the packaging in .pkg.tar.xz, will it work?

**Comment by Yisus7u7** [comment]
For example, I unzip the wget deb package, and the files that had that package organized them into a package .pkg.tar.xz, would it work?

**Comment by suhan-paradkar** [comment]
> For example, I unzip the wget deb package, and the files that had that package organized them into a package .pkg.tar.xz, would it work? 

You  need to reorganize those package configuration files ...

**Comment by Yisus7u7** [comment]
> > Por ejemplo, descomprimo el paquete wget deb y los archivos que tenían ese paquete los organizaron en un paquete .pkg.tar.xz, ¿funcionarían?
> 
> Necesita reorganizar esos archivos de configuración de paquetes ...

I know that, but would it work?

**Comment by Maxython** [comment]
And can this be done on termux?

**Comment by Grimler91** [comment]
> I know that, but would it work?

Just re-organizing would not work. You would need to translate all the [control fields](https://github.com/termux/termux-packages/blob/800a5cdedae700bc334d6f698dbe93b9623847c3/scripts/build/termux_step_create_debfile.sh#L18,L27) into whatever values/format the pkg.tar.xz uses (and probably not all have an equivalent), and the debscripts [(for example)](https://github.com/termux/termux-packages/blob/2aa72560a7dc4cd12c45df587edf579c3735bdd6/packages/openssh/build.sh#L101,L112)

**Comment by Yisus7u7** [comment]
Oh ok

**Comment by Yisus7u7** [comment]
Well, I'll wait for time to pass, as I don't have pc, at the moment I can't start compiling, but one last question, can I use that environment that you use to compile packages on a pc to make packages for pacman?

**Comment by xeffyr** [comment]
> can I use that environment that you use to compile packages on a pc to make packages for pacman

Modify the termux-packages build system first, to make it creating pacman packages instead of apt/dpkg format. Compiling is not big issue, you can do that on Github Actions or some packages even can be compiled on device.

**Comment by Yisus7u7** [comment]
Yes, I can use make pkg, but can I use the termux build environment on my own cell phone?

**Comment by xeffyr** [comment]
Yes, you can use it on Android device: https://github.com/termux/termux-packages/wiki/Build-environment#termux. Though certain packages are problematic for on-device build.

**Comment by Yisus7u7** [comment]
Ok, tanks you!
