### ISSUE TITLE
Help wanted 

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-packages#6862]
Android 11
Termux environment 
Getting error when want to install cgminer 
https://github.com/JordanRulz/cgminer
Getting error pthread cancel
![Screenshot_2021-05-26-21-34-07-056_com termux](https://user-images.githubusercontent.com/72664192/119775484-49cca700-bee1-11eb-977a-a50833e31b53.jpg)

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/search?q=pthread_cancel for patches that solve the same error for other packages
