### ISSUE TITLE
Apache 2.4.47 downgraded to 2.4.46 after update

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-packages#6867]
**Problem description**
When I did an `apt update` and `apt upgrade` I saw that Apache was *down*graded from 2.4.47 to 2.4.46.

In the meantime I changed the repo because I had to do as bintray was down : `termux-change-repo` followed by an `apt upgrade` of which the latter indeed updated a few packages without errors, so that worked fine.

A few days later I did an upgrade and noticed that Apache was downgraded, others were upgraded normally.

**Comment by suhan-paradkar** [comment]
Its done on purpose after apache was downgraded by upstream due to a major bug

**Comment by kcubeterm** [comment]
Expected behaviour. https://github.com/termux/termux-packages/commit/17313f23576785e1cddfbacbd9bb5e5f3889a487
