### ISSUE TITLE
nokogiri gem install probelm

### ISSUE THREAD

**Issue by robertvalik** [termux/termux-packages#69]
When trying to install gollum

       gem install gollum

One of the dependencies fails. I get this error in /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/extensions/x86-linux/2.2.0/nokogiri-1.6.6.4/mkmf.log:

        cat mkmf.log
        "i686-linux-android-gcc -o conftest -I/data/data/com.termux/files/usr/include/ruby-2.2.0/i686-linux-android -I/data/data/com.termux/files/usr/include/ruby-2.2.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.2.0 -I. -I/data/data/com.termux/files/usr/include   -specs=/home/fornwall/dc/termux.spec -march=i686 -msse3 -mstackrealign -mfpmath=sse -Os -fPIC  conftest.c  -L. -L/data/data/com.termux/files/usr/lib -L. -specs=/home/fornwall/dc/termux.spec -L/data/data/com.termux/files/usr/lib -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby  -lgmp -ldl -lm   -lc "
        i686-linux-android-gcc: error: /home/fornwall/dc/termux.spec: No such file or directory
        checked program was:
        /* begin */
        1: #include "ruby.h"
        2:
        3: int main(int argc, char **argv)
        4: {
        5:   return 0;
        6: }
        /* end */

**Comment by fornwall** [comment]
Thanks, it was a mistake in the configuration of the x86 ruby package which now has been fixed (run `apt update && apt upgrade` to get the updated ruby x86 package)!

After installing the following packages:

    apt install ruby-dev libxml2-dev libxslt-dev pkg-config make gcc

I can now install nokogiri with:

    gem install nokogiri -- --use-system-libraries

The reason that `--use-system-libraries` is needed is that otherwise nokogiri tries to build a bundled version of libxml2, which won't work due to scripts there assuming that `/bin/` exists (which it doesn't on Android). Linking against the system libraries should however be fine and just save space, since the libxml2 package in Termux contains the patches from upstream that nokogiri wants!

**Comment by themastersunil** [comment]
Anyone can help me? To install gems
$ gem install nokogiri -- --use-system-libraries
ERROR: While executing gem ... (Errno::EACCES)
Permission denied @ rb_sysopen - /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.0/.autotest

**Comment by Auxilus** [comment]
Try `rm -r /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.0` then `apt update && apt upgrade`
`gem install nokogiri -- --use-system -libraries`
If it fails , and if you have rooted then try to run it under root authority

**Comment by Ahmedroid** [comment]
For all who have a problem in nokogiri error !!!! 
Just type
gem install pkg-config
Then 
bundle install 

Enjoy

**Comment by technicalverma** [comment]
<body>
i am aman
</body>

**Comment by jakoma1** [comment]
1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
$

**Comment by jigarpunadiya** [comment]
jakoma1 

Im also having the same issue

**Comment by bebo74** [comment]
And i am
