### ISSUE TITLE
Remove netcat dependency for nmap so nmap can coexist with netcat-openbsd

### ISSUE THREAD

**Issue by Hackerpcs** [termux/termux-packages#6921]
As the title says, `netcat-openbsd` (#5754) can't be installed along with `nmap` because `netcat` which is gnu-netcat (#162) is a dependency for `nmap`

**Comment by xeffyr** [comment]
> because netcat which is gnu-netcat

This is actually ncat which is part of nmap package.

**Comment by Hackerpcs** [comment]
So it can't be separated to be able to use both `netcat-openbsd` and `nmap` ?

**Comment by xeffyr** [comment]
It can be.

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/commit/bd7dd8a9b34caeb6b7393f53c7d1fe65c9917652.
