### ISSUE TITLE
Update and upgrade isuue

### ISSUE THREAD

**Issue by Mahroof313** [termux/termux-packages#6923]
When i run the command apt update & & apt upgrade command then shows like

The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4
E: The repository 'https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

What is the problem

**Comment by xeffyr** [comment]
> E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.

For this repo solution can be found there: https://github.com/termux/termux-packages/issues/6726

> W: GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4

Remove this repository or add the gpg key:
```
pkg install -y gnupg
curl -fsSL https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master/gushmazuko-gpg.pubkey | gpg --dearmor | tee $PREFIX/etc/apt/trusted.gpg.d/gushmazuko-repo.gpg
```
Read the instructions next time - https://github.com/gushmazuko/metasploit_in_termux#how-to.

**Comment by Mahroof313** [comment]
![Screenshot_20210530_002126](https://user-images.githubusercontent.com/70357348/120081805-05a5f600-c0dd-11eb-8202-c3d1acab7a7a.jpg)
@xeffyr
Not solved

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/6726 describes why repository shows `403 Forbidden` and how to solve it. Just read instructions carefully. I won't copy-paste it there. Another instruction variant is https://github.com/termux/termux-app/issues/1980#issuecomment-850811656.

If you still have the issue, then you missed something.
