### ISSUE TITLE
Clang missing libxml2.so on x86_64 architecture

### ISSUE THREAD

**Issue by neiviv-ui** [termux/termux-packages#6926]
Hi, I wanted to test clang on different devices for some reasons, and it appeared that on x86_64 (emulated) devices, libxml2.so didn't exist in /system/lib*. I have tried on Anbox and PrimeOS and the same error occurs.
Of course `pkg install libxml2` solves the problem, so I was wondering if we should add it as a dependency for clang.
Have a good day.

**Comment by Grimler91** [comment]
What did you run and what error did you get exactly?

What is your output of `termux-info`?

I used clang successfully on x86_64 a couple of days ago, and I can't see a dependency on libxml2.so when I checked the clang program and libraries now, so please let us know how to reproduce the issue.

> libxml2.so didn't exist in /system/lib*

All of termux's packages are in /data/data/com.termux/files/usr/, not /system

> I have tried on Anbox and PrimeOS and the same error occurs.

Probably an issue with anbox and primeos rather than termux

**Comment by neiviv-ui** [comment]
Thanks for your quick response.
Actually I didn't explain very well what I meant:
I know that termux doesn't install to /system/lib*, but I said this because on all the phones I tried with, libxml2.so was in /system/lib*, and not in /data/data/com.termux/files/usr, which for me meant that it was pre-compiled (in the stock ROM), explaining why I didn't need to install libxml2.

So, when I tried on PrimeOS and Anbox, and saw that it wasn't in the stock ROM (by that, I mean in /system/lib*), I thought than since most of the phones already included it, it had been forgotten as a dependency.
This is the reason of my first message, sorry for not being clear the first time.

Actually, I agree with you that it is probably more a PrimeOS and Anbox problem than a termux one, but it's an interesting question: "Are we supposed to set as a dependencie a necessary librairie that already exists but only on some phones ?", or maybe all phones include the same librairies in /system/lib*, and PrimeOS and anbox just suck.

Anbox's output of termux-info:
> Application version:
0.113
Packages CPU architecture:
x86_64
Subscribed repositories:
sources.list
deb https://termux.org/packages/ stable main
science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
7.1.1
Kernel build information:
Linux anbox 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC  x86_64 Android
Device manufacturer:
unknown
Device model:
Anbox


PrimeOS' one:
> Application version:
0.113
Packages CPU architecture:
x86_64
Subscribed repositories:
sources.list
deb https://k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx.ipns.dweb.link/ stable main
game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 4.14.15-primeos #4 SMP PREEMPT Fri Mar 8 12:45:59 IST 2019 x86_64 Android
Device manufacturer:
QEMU
Device model:
Standard PC (i440FX + PIIX, 1996)

(I am using PrimeOS on a Virtual machine).

About the error, for example if I try to compile this sample program by running `gcc foo.c -o foo`:
>#include <stdio.h>
int main(void) {
	printf("Hello world!");
	return 0;
}

I get the following error on both PrimeOS and Anbox:
>CANNOT LINK EXECUTABLE "gcc": library "libxml2.so" not found

followed by, on PrimeOS:
>Aborted

and on Anbox:
>Aborted (core dumped)

In fact, even running `gcc` returns exactly the same error.

Running `pkg install libxml2` solves the problem, even if when I run the compiled binary, I get the following warning :
>WARNING: linker: /data/data/com.termux/files/home/foo: unsupported flags DT_FLAGS_1=0x8000001

but if I remember correctly, it is just because of the android version, and termux-elf-cleaner should remove the warning.

**Comment by Grimler91** [comment]
>  saw that it wasn't in the stock ROM (by that, I mean in /system/lib*)

Right, probably a coincidence. All termux packages should only use things in /data/data/com.termux/files/usr, except for android's libc, and very rarely things like media libraries 

I see now that libLLVM.so is linked to libxml2.so, so we should add a dependency there indeed, thanks for reporting.

Should be fixed in https://github.com/termux/termux-packages/commit/5cd3d276eca5d9a5f4a8fe73c0774793bb10a799.
