### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by sirajuddinj7** [termux/termux-packages#6929]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by sirajuddinj7** [comment]
repository is under maintenance or down (wrong sources.list URL?).

**Comment by niraj69** [comment]
Can't able to run any command 
Showing 403 forbidden

**Comment by sirajuddinj7** [comment]
Yes

**Comment by agnostic-apollo** [comment]
Check #6726
