### ISSUE TITLE
My termux problem

### ISSUE THREAD

**Issue by MrKechik** [termux/termux-packages#6933]
![Screenshot_2021-06-01-09-00-14-26_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/85141822/120252818-2b3b2700-c2b8-11eb-9467-187a29f28c7f.jpg)

**Comment by WMCB-Tech** [comment]
Check
https://github.com/termux/termux-packages/issues/6726

**Comment by MrKechik** [comment]
How,,  to check

**Comment by WMCB-Tech** [comment]
Read the first comment in this issue 
#6726

***

If you're still on Google Play version of Termux, strongly suggest to move to F-Droid, but will require full uninstall, instructions are given above
