### ISSUE TITLE
Upgrade && update

### ISSUE THREAD

**Issue by maheshwar2003** [termux/termux-packages#6934]
apt upgrade && update 
Is not working

**Comment by Pritam2726** [comment]
Same problem

**Comment by maheshwar2003** [comment]
Try  after turning on and off aeroplane mode and then try again it worked![Screenshot_2021-06-01-09-34-13-68.jpg](https://user-images.githubusercontent.com/85145720/120264953-8d962680-c2bc-11eb-949d-9b56e6c68f29.jpg)

**Comment by Pritam2726** [comment]
Ok Thanke you 👍
