### ISSUE TITLE
The computer domain name could not be resolved

### ISSUE THREAD

**Issue by Kicha7669** [termux/termux-packages#6936]
I am having this issue whenever I try to connect vnc server 

I installed Termux and I want to use Ubuntu in it so I set up all things , now whenever I try to connect to vnc server it says, 
The computer domain name could not be resolved.

Here are some screenshots
![Screenshot_20210601-124431](https://user-images.githubusercontent.com/85155918/120282996-546baf80-c2d8-11eb-90dd-9a4d76a721fb.png)
![Screenshot_20210601-124413](https://user-images.githubusercontent.com/85155918/120283006-56357300-c2d8-11eb-83f0-d8fff268938c.png)

**Comment by Yonle** [comment]
Are you sure your connection is `localhost:5900`? If you connect to `remote-desktop:5900`, It won't work.

**Comment by xeffyr** [comment]
Connect to `localhost:5901`.
