### ISSUE TITLE
termux packages failed to download ..need help

### ISSUE THREAD

**Issue by nati69** [termux/termux-packages#6937]
pkg install nmap
Checking availability of current mirror: ok
Get:1 https://dl.kcubeterm.me/termux-packages-24 stable InRelease [10.6 kB]
Hit:2 https://grimler.se/game-packages-24 games InRelease
Hit:3 https://grimler.se/science-packages-24 science InRelease
Get:4 https://dl.kcubeterm.me/termux-packages-24 stable/main i686 Packages [243 kB]
Err:4 https://dl.kcubeterm.me/termux-packages-24 stable/main i686 Packages
  File has unexpected size (242346 != 242924). Mirror sync in progress? [IP: 172.67.165.185 443]
  Hashes of expected file:
   - Filesize:242924 [weak]
   - SHA512:a8df4e4006e3ba9a8c2c9ef104aeb69cecbe98fd88173c0c3a5af85bca55ade7125abe62ee3375866ad063e547804862e13c75e57f8e080a8f892158ab248993
   - SHA256:9b7f8f26151e92f822d9185e25e499176d6163989aba053619c3f09538fa2e95
   - SHA1:b3404f1a6526290933d5e2af6f9313cbf1ab085b [weak]
   - MD5Sum:94a9c9b5a26cd735aaf24c323a73708e [weak]
  Release file created at: Mon, 31 May 2021 04:43:35 +0000
Reading package lists... Done
E: Failed to fetch https://dl.kcubeterm.me/termux-packages-24/dists/stable/main/binary-i686/Packages.bz2  File has unexpected size (242346 != 242924). Mirror sync in progress? [IP: 172.67.165.185 443]
   Hashes of expected file:
    - Filesize:242924 [weak]
    - SHA512:a8df4e4006e3ba9a8c2c9ef104aeb69cecbe98fd88173c0c3a5af85bca55ade7125abe62ee3375866ad063e547804862e13c75e57f8e080a8f892158ab248993
    - SHA256:9b7f8f26151e92f822d9185e25e499176d6163989aba053619c3f09538fa2e95
    - SHA1:b3404f1a6526290933d5e2af6f9313cbf1ab085b [weak]
    - MD5Sum:94a9c9b5a26cd735aaf24c323a73708e [weak]
   Release file created at: Mon, 31 May 2021 04:43:35 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by xeffyr** [comment]
Try `termux-change-repo` for switching "Main" repository to Grimler's one.

@kcubeterm Are there sync issues on dl.kcubeterm.me?

**Comment by kcubeterm** [comment]
Stopped it until fixed. So that pkg dont choose this mirror.

**Comment by kcubeterm** [comment]
Thanks for reporting. It looks fine now.

**Comment by Sandra-Yap** [comment]
it work..thanks
