### ISSUE TITLE
mutt gpg.rc example for gpg2

### ISSUE THREAD

**Issue by sirmacik** [termux/termux-packages#694]
#697 

Hey guys!

Since termux appears to support gpg1 and gpg2 listing below should probably go as separate file in $PREFIX/share/examples/mutt/. Here goes working gpg.rc file for gpg2

```
set pgp_decode_command="gpg2 %?p?--passphrase-fd 0 --pinentry-mode=loopback?  --no-verbose --batch --output - %f"
set pgp_verify_command="gpg2 --no-verbose --batch --output - --verify %s %f"
set pgp_decrypt_command="gpg2 %?p?--passphrase-fd 0 --pinentry-mode=loopback? --no-verbose --batch --output - %f"
set pgp_sign_command="gpg2 --no-verbose --batch --output - %?p?--passphrase-fd 0 --pinentry-mode=loopback? --armor --detach-sign --textmode %?a?-u %a? %f"
set pgp_clearsign_command="gpg2 --no-verbose --batch --output - %?p?--passphrase-fd 0 --pinentry-mode=loopback? --armor --textmode --clearsign %?a?-u %a? %f"
set pgp_encrypt_only_command="pgpewrap gpg2 --batch --quiet --no-verbose --output - --encrypt --textmode --armor --always-trust -- -r %r -- %f"
set pgp_encrypt_sign_command="pgpewrap gpg2 %?p?--passphrase-fd 0 --pinentry-mode=loopback? --batch --quiet --no-verbose --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust -- -r %r -- %f"
set pgp_import_command="gpg2 --no-verbose --import -v %f"
set pgp_export_command="gpg2 --no-verbose --export --armor %r"
set pgp_verify_key_command="gpg2 --no-verbose --batch --fingerprint --check-sigs %r"
set pgp_list_pubring_command="gpg2 --no-verbose --batch --quiet --with-colons --with-fingerprint --list-keys %r"
set pgp_list_secring_command="gpg2 --no-verbose --batch --with-colons --with-fingerprint --list-secret-keys %r"
```

Cheers!
Marcin

**Comment by Neo-Oli** [comment]
Another possibility would be this. It omits the --pinentry-mode=loopback in favor of using the gpg-agent. It has the advantage that if the keyring is already unlocked, it will not have to be unlocked again when mutt starts.

```
set pgp_use_gpg_agent=yes
set pgp_decode_command="gpg2 %?p?--passphrase-fd 0? --no-verbose --batch --output - %f"
set pgp_verify_command="gpg2 --no-verbose --batch --output - --verify %s %f"
set pgp_decrypt_command="gpg2 --passphrase-fd 0 --no-verbose --batch --output - %f"
set pgp_sign_command="gpg2 --no-verbose --batch --output - --passphrase-fd 0 --armor --detach-sign --textmode %?a?-u %a? %f"
set pgp_clearsign_command="gpg2 --no-verbose --batch --output - --passphrase-fd 0 --armor --textmode --clearsign %?a?-u %a? %f"
set pgp_encrypt_only_command="pgpewrap gpg2 --batch --quiet --no-verbose --output - --encrypt --textmode --armor --always-trust --encrypt-to $pgp_sign_as -- -r %r -- %f"
set pgp_encrypt_sign_command="pgpewrap gpg2 --passphrase-fd 0 --batch --quiet --no-verbose --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust --encrypt-to $pgp_sign_as -- -r %r -- %f"
set pgp_import_command="gpg2 --no-verbose --import -v %f"
set pgp_export_command="gpg2 --no-verbose --export --armor %r"
set pgp_verify_key_command="gpg2 --no-verbose --batch --fingerprint --check-sigs %r"
set pgp_list_pubring_command="gpg2 --no-verbose --batch --with-colons --list-keys %r"
set pgp_list_secring_command="gpg2 --no-verbose --batch --with-colons --list-secret-keys %r"
```

**Comment by sirmacik** [comment]
Can you paste your gpg-agent. config supporting this solution?

**Comment by Neo-Oli** [comment]
@sirmacik I have no gpg-agent config except that I launch "gpg-connect-agent updatestartuptty /bye" before launching mutt to update the tty that the pinentry pops up (Perhaps that could be integrated into the commands). Setting up the gpg-agent to work well is a pain anyway, because it really matters which tty the pinentry pops up because it is displayed in curses rather than on the xserver in termux. Therefore "gpg-connect-agent updatestartuptty /bye" needs to be called before every gpg2 command. 

I think your solution is the better one to include as a default example. But if you use Gnupg for other things than mutt (as ssh-agent and pass for example) mine might be better suited. 

I have to have aliases for all commands that require ssh (because my ssh key is stored in Gnupg) and for gpg2.
alias ssh="gpg-connect-agent updatestartuptty /bye;ssh"
alias gpg2="gpg-connect-agent updatestartuptty /bye;gpg2"

**Comment by sirmacik** [comment]
Hm, file I've sent does seem to be working without the need to retype my password every time. I'm working with three accounts and I need to type the password only when gpg-agent session ends. `default-cache-ttl` is the only setting in my gpg-agent.conf

**Comment by Neo-Oli** [comment]
Weird. When I use yours I have to type my password for every mutt session.

**Comment by sirmacik** [comment]
Are you sure there is everything alright with your gpg-agent config? The need for running that command seems really weird.

**Comment by Neo-Oli** [comment]
Ah, I see, what happens is the first gpg message of mutt asks me to "Enter PGP passphrase:", if I just press enter here it also gets unlocked.

By the way set `pgp_use_gpg_agent=yes` should still work without doing the update command. Did this not work for you?

**Comment by sirmacik** [comment]
There isn't any difference in my setup after setting this line .

**Comment by sirmacik** [comment]
I've found out wthat's the matter Turns out I've had this line added to my setup years ago, elswhere. That's why it's missed in proposed file but apparently should be added. For the final suggestion about that I'd look into other distros gpg.rc that are distributed with mutt.
