### ISSUE TITLE
Metadata integrity can't be verified, repository is disabled now

### ISSUE THREAD

**Issue by nati69** [termux/termux-packages#6944]
pkg update
Checking availability of current mirror: ok
Hit:1 https://abhackerofficial.github.io/abhacker.repo abhacker InRelease
Hit:3 https://grimler.se/game-packages-24 games InRelease
Hit:4 https://grimler.se/termux-root-packages-24 root InRelease
Hit:5 https://termux.com/unstable-packages-bin unstable InRelease
Hit:6 https://grimler.se/science-packages-24 science InRelease
Hit:8 https://termux.com/x11-packages-bin x11 InRelease
Hit:2 https://packages.termux.org/apt/termux-main stable InRelease
Get:7 https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease [7397 B]
Err:7 https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4
Reading package lists... Done
W: GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4
E: The repository 'https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?)

**Comment by xeffyr** [comment]
Read https://github.com/gushmazuko/metasploit_in_termux#how-to. If not working, report the issue to its owner.

We are not fixing issues in third party repositories.
