### ISSUE TITLE
libtoolize not found 

### ISSUE THREAD

**Issue by geezuh** [termux/termux-packages#695]
this is bring run within termux-chroot btw.

~/src/rtorrent# apt install libtool              
Reading package lists... Done                    
Building dependency tree                         
Reading state information... Done
libtool is already the newest version (2.4.6-4). 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.                                    
~/src/rtorrent# ./autogen.sh                     
aclocal...
autoheader...                                    
libtoolize... libtoolize nor glibtoolize not found

**Comment by fornwall** [comment]
@geezuh If you are still having this problem: Does running e.g. `libtoolize --help` work?

**Comment by geezuh** [comment]
I just checked, and libtoolize --help notified me that i didn't have sed.
It also looks like I didn't have grep. 
autogen.sh runs as expected now.

Now configure is throwing errors, but I'm not sure that's a Termux issue.
File this one under user error.

**Comment by fornwall** [comment]
> I just checked, and libtoolize --help notified me that i didn't have sed.
> It also looks like I didn't have grep.
> autogen.sh runs as expected now.

Did you install the `grep` and `sed` packages for it to work? If so, perhaps the `libtool` package should bring in those packages as dependencies.

**Comment by geezuh** [comment]
Yes, I did. 
That would probably help prevent others from having this issue.

**Comment by Auxilus** [comment]
@geezuh `libtoolize --he` gives sed error cz by default termux uses sed provided by busybox which has path
`/data/data/com.termux/files/usr/bin/applets/sed`
You need to do `pkg install sed`

**Comment by StefanL** [comment]
Quick fix (user) is to edit the libtoolize script and add the correct path (see post above) on line 49 for the sed program. Longterm fix (developer) is to push a new version with the fixed path.

**Comment by fornwall** [comment]
Thanks - the updated version 2.4.6-5 of the libtool package now depends on sed and grep.
