### ISSUE TITLE
emcc: unable to find python in $PATH

### ISSUE THREAD

**Issue by neo-expert** [termux/termux-packages#6951]
**Problem description**
after installing emscripten with

    apt install emscripten

the emcc command throws this error:

    unable to find python in $PATH

but python is working (python version: 3.9.5)

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.113-21644994 #1 SMP PREEMPT Fri May 7 12:58:22 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G970F


```

**Comment by truboxl** [comment]
Try `emcc.py`?

I can't replicate the problem from my device. Anyone can help confirm?
```
Application version:
0.113
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.kcubeterm.me/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.177-20443966 #1 SMP PREEMPT Mon Apr 26 14:16:10 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A307GN
```
```
~ $ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.23 (b15ca40ca02f469de3bf9a4de67a2655aede8974)
clang version 13.0.0
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/lib/emscripten-llvm/bin
~ $ emcc.py -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.23 (b15ca40ca02f469de3bf9a4de67a2655aede8974)
clang version 13.0.0
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/lib/emscripten-llvm/bin
```
```
~ $ file `which python`
/data/data/com.termux/files/usr/bin/python: symbolic link to python3.9
~ $ file `which python3`
/data/data/com.termux/files/usr/bin/python3: symbolic link to python3.9
~ $ file `which python3.9`
/data/data/com.termux/files/usr/bin/python3.9: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped
```

**Comment by neo-expert** [comment]
emcc.py works better but still throws the error while compiling.
I found out that emcc is actually under 
 
    /data/data/com.termux/files/usr/lib/emscripten/emcc

and is a shell script. 

Somehow in this script nothing get stored in the PYTHON variable. To check that I just added some echos to it:

if [ -z "$PYTHON" ]; then
  PYTHON=$EMSDK_PYTHON                               fi

echo $PYTHON                                         
if [ -z "$PYTHON" ]; then
  PYTHON=$(which python3 2> /dev/null)
fi

echo $PYTHON

if [ -z "$PYTHON" ]; then
  PYTHON=$(which python 2> /dev/null)
fi
echo $PYTHON

Now emcc prints 3 empty lines and the same error. But in the shell itself the assignment works:

➜  PYTHON=$(which python3 2> /dev/null)
➜  echo $PYTHON
/data/data/com.termux/files/usr/bin/python3
➜

**Comment by neo-expert** [comment]
somehow when I change the shell script interpreter in the first line to

    #!/bin/zsh
    
the script works better, but throws the error again by compiling.

**Comment by Grimler91** [comment]
I also cannot reproduce the issue.

> somehow when I change the shell script interpreter in the first line to `#!/bin/zsh`

What shell are you normally using?

Try removing the error redirections to /dev/null and see if it prints some error messages (remove `2> /dev/null`)

**Comment by neo-expert** [comment]
Oh, thanks, it prints now:

 
   /data/data/com.termux/files/usr/lib/emscripten/emcc: 21: which: not found

But I can use "which" in the shell.
I am using zsh (oh-my-zsh)

**Comment by neo-expert** [comment]
at least in zsh, but in sh "which" is not working. Can I install "which"?

**Comment by neo-expert** [comment]
ah solved this by installing the package "debianutils", not sure why it was not installed, sometimes I do "apt autoremove" maybe it removed debianutils?

**Comment by Grimler91** [comment]
> I do "apt autoremove" maybe it removed debianutils?

I guess so, seems likely. Maybe adding the dependency would be a good idea
