### ISSUE TITLE
Termux issues 

### ISSUE THREAD

**Issue by AngelesA4** [termux/termux-packages#6953]
No me permite actualizar termux (apt update && apt upgrade) ni buscar nada.

![Screenshot_20210604-105431_Termux](https://user-images.githubusercontent.com/85354256/120814101-ea941580-c524-11eb-9d23-dd5ad4600bc8.jpg)

**Comment by xeffyr** [comment]
1. Open https://github.com/termux/termux-packages/issues/6726.

2. Read everything under "What you should do as Termux user" label and follow instructions. *Read carefully!*

3. If it still doesn't work, repeat the step 2.
