### ISSUE TITLE
Can't update packages

### ISSUE THREAD

**Issue by parkyrosh** [termux/termux-packages#6954]
When i am trying  to "pkg update" and "pkg upgrade" its showing server under maintenance
![Screenshot_2021-06-04-22-05-47-90](https://user-images.githubusercontent.com/74543153/120834722-0af1bd80-c581-11eb-8a32-0a0c82222c09.jpg)

**Comment by xeffyr** [comment]
1. Open https://github.com/termux/termux-packages/issues/6726. *Lots of issues have been submitted regarding this, but I won't repost instructions for everyone individually.*

2. Read everything under "What you should do as Termux user" label and follow instructions. *Read carefully!*

3. If it still doesn't work, repeat the step 2 (it is very easy to miss the details when following instructions).
