### ISSUE TITLE
rclone bash autocompletion can't be configured

### ISSUE THREAD

**Issue by crisalis2** [termux/termux-packages#6955]
**Problem description**

rclone has an option to configure autocompletion with the command "rclone genautocomplete bash", but when I ran that on Termux, it failed with "/etc/bash_completion.d/rclone: no such file or directory".
Creating that file under /data/data/com.termux/files/usr/etc/bash_completion.d/ or installing the bash-completion package didn't make any difference.

**Steps to reproduce**

Install rclone, run "rclone genautocomplete bash" and see it fail.

**Expected behavior**

I run "rclone genautocomplete bash", it succeeds and I can start using tab autocompletion with rclone on Termux.

**Additional information**
No root here.

**Comment by Sukesharch** [comment]
U
