### ISSUE TITLE
Run Magisk SU in termux-chroot?

### ISSUE THREAD

**Issue by SoumyBhow** [termux/termux-packages#6957]
I'm exploring Termux on my OnePlus 7 Pro running Android 10 a bit and i wanted to see if I could install [Skyscraper](https://github.com/muldjord/skyscraper) into Termux. I've installed all seemingly necessary packages, ran "termux-chroot" and "unset LD_PRELOAD" and followed the installation instructions. At the end it says
> No superuser binary detected. Are you rooted?

I am rooted with Magisk 23.0. I also saw issue [#2100](https://github.com/termux/termux-packages/issues/2100) but i don't really understand what I have to do. If I run the given command ($ARGS="$ARGS -b /sbin:/sbin -b /root:/root"), it says that

> bash: = -b /sbin:/sbin -b /root:/root: No such file or directory

Is there a way to run su in chroot, or perhaps another way to install Skyscraper if it's possible to begin with?

Thanks in advance

**Comment by ChiefMikeK** [comment]
Any and all questions should not be asked here !
reddit/r/Termux is the place where these are 2b-discussed :neckbeard: 
# [reddit: the front page of the internet](https://www.reddit.com/r/Termux )

**Comment by SoumyBhow** [comment]
I sincerely apologize. Closing this issue. Sorry for the trouble.
