### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by Ravigktp** [termux/termux-packages#6961]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```
[*] Verifying integrity of rootfs...

sha512sum: kalifs-arm64-full.tar.xz: No such file or directory
kalifs-arm64-full.tar.xz: FAILED open or read
sha512sum: WARNING: 1 listed file could not be read
 Rootfs corrupted. Please run this installer again or download the file manually

**Comment by xeffyr** [comment]
Report the issue to repository where you got this Kali (or Kali Nethunter?) installer.
