### ISSUE TITLE
Package Problem

### ISSUE THREAD

**Issue by Kuba112811** [termux/termux-packages#6962]
I have problems from commands `Apt` `Pkg` and other that install apps. The example if i say `pkg search Ubuntu` then i see following error `E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).` Please help.

**Comment by xeffyr** [comment]
1. Open https://github.com/termux/termux-packages/issues/6726 (pinned, btw). *Lots of issues have been submitted regarding this, but I won't repost instructions for everyone individually.*

2. Read everything under "What you should do as Termux user" label and follow instructions. *Read carefully!*

3. If it still doesn't work, repeat the step 2 (it is very easy to miss the details when following instructions).
