### ISSUE TITLE
CANNOT LINK EXECUTABLE "cmake": Getting error with cmake

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-packages#6963]
CANNOT LINK EXECUTABLE "cmake":

![Screenshot_2021-06-06-01-27-20-576_com termux](https://user-images.githubusercontent.com/72664192/120903885-86796a80-c666-11eb-98e3-76fbc0412977.jpg)

**Comment by widhisec** [comment]
> CANNOT LINK EXECUTABLE "cmake":
> 
> ![Screenshot_2021-06-06-01-27-20-576_com termux](https://user-images.githubusercontent.com/72664192/120903885-86796a80-c666-11eb-98e3-76fbc0412977.jpg)

apt upgrade
