### ISSUE TITLE
bash: ./wifi-hacker.sh: Permission denied

### ISSUE THREAD

**Issue by aksxy** [termux/termux-packages#6964]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```bash: ./wifi-hacker.sh: Permission denied

**Comment by WMCB-Tech** [comment]
Do `bash wifi-hacker.sh` instead

**Comment by aksxy** [comment]
~/blackeye-im $ ./tmxsp.sh
bash: ./tmxsp.sh: Permission denied 


How to solve I this problem

**Comment by WMCB-Tech** [comment]
I already stated the solution above, and please do back-reading of messages
