### ISSUE TITLE
 games  unstable InRelease Hit:7 https://packages.termux.org/apt/termux-x11 x11 InRelease Reading package lists... Done E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file. N: Metadata integrity can't be verified, repository is disabled now. N: Possible cause: repository is under maintenance or down (wrong sources.list URL?). E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file. N: Metadata integrity can't be verified, repository is disabled now. N: Possible cause: repository is under maintenance or down (wrong sources.list URL?). $

### ISSUE THREAD

**Issue by Vawnhoang** [termux/termux-packages#6965]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

$ pkg update
Checking availability of current mirror: ok
Hit:1 https://termux.mentality.rip/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden
Hit:6 https://packages.termux.org/apt/termux-unstable unstable InRelease
Hit:7 https://packages.termux.org/apt/termux-x11 x11 InRelease
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

**Comment by agnostic-apollo** [comment]
Check #6726.
