### ISSUE TITLE
Failed to run g-ir-scanner

### ISSUE THREAD

**Issue by leapofazzam123** [termux/termux-packages#6970]
**Problem description**

g-ir-scanner states that there is no module named "girscanner._girscanner' found

**Steps to reproduce**

1. Run `g-ir-scanner`

**Expected behavior**

It should work fine

**Additional information**

```
Application version:
0.113
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
Updatable packages:
composer/stable 2.1.1 all [upgradable from: 2.1.0]
curl/stable 7.77.0-3 aarch64 [upgradable from: 7.77.0-2]
libcurl/stable 7.77.0-3 aarch64 [upgradable from: 7.77.0-2]
termux-tools/stable 0.124 all [upgradable from: 0.123-3]
Android version:
10
Kernel build information:
Linux localhost 4.9.190+ #2 SMP PREEMPT Mon Oct 19 13:04:42 CST 2020 aarch64 Android
Device manufacturer:
INFINIX MOBILITY LIMITED
Device model:
Infinix X680B

```

**Comment by thunder-coding** [comment]
We don't have any package named `g-ir-scanner`.

If you did download the binary/tried to build the package, give some additional information about the package

**Comment by WMCB-Tech** [comment]
That's the part of `gobject-introspection`

**Comment by leapofazzam123** [comment]
> We don't have any package named `g-ir-scanner`.
> 
> If you did download the binary/tried to build the package, give some additional information about the package

It's the part of gobject-introspection

**Comment by leapofazzam123** [comment]
Have you heard of gobject?

**Comment by suhan-paradkar** [comment]
I don't know why.. but I don't get that error...![Screenshot_2021-06-08-18-50-41-39.jpg](https://user-images.githubusercontent.com/76830230/121192557-af7a4500-c88a-11eb-9f97-80835e3f7056.jpg)

**Comment by leapofazzam123** [comment]
Even when reinstalling gobject-introspection, it still doesn't work

**Comment by Yisus7u7** [comment]
I can confirm the same error

![Screenshot_20210922-133825](https://user-images.githubusercontent.com/64093255/134402370-1f80d522-c29c-4623-8fbd-25b7769cda3a.png)

Now I understand why pygtk doesn't work.

**Comment by xeffyr** [comment]
`x86_64` shouldn't have effect on loading of shared object, at least that didn't happened in context of Python 3.8 / 3.9 and package `borgbackup`.

**Comment by xtkoba** [comment]
The latest action for borgbackup (https://github.com/termux/termux-packages/actions/runs/1310038539) has shared objects named e.g.

```
chunker.cpython-310-x86_64-linux-gnu.so
```

thus the `x86_64-linux-gnu` part should be irrelevant. But it is odd to me that the so file built for python3.10 is annotated as `cpython-38` and not `cpython-310`.

Anyway, by using the `strace` command it should be made clear whether the python interpreter is actually able to find the so file.

**Comment by xtkoba** [comment]
Note that when a Python extension does not have `libpython*` as `DT_NEEDED`, then it may be affected by https://github.com/android/ndk/issues/201.

**Comment by xtkoba** [comment]
With the PR applied, the extension shared library is named
```
giscanner/_giscanner.cpython-310-x86_64-linux-gnu.so
```
in which `x86_64-linux-gnu` should not matter according to https://github.com/termux/termux-packages/issues/6970#issuecomment-938155763. Could anyone confirm that it works?

https://github.com/termux/termux-packages/actions/runs/1494689992

**Comment by xtkoba** [comment]
Nope, it may not work. `borgbackup` seems to work because the full name (e.g. `chunker.cpython-310-x86_64-linux-gnu.so`) is specified in loading scripts.

**Comment by xtkoba** [comment]
Renamed to `giscanner/_giscanner.cpython-310.so`. It should work.
