### ISSUE TITLE
Package request: rdrview

### ISSUE THREAD

**Issue by mglh** [termux/termux-packages#6975]
## Requesting new package

- [X] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description:

_**Firefox Reader View as a command line tool**_

_Command line tool to extract the main content from a webpage, as done by the "Reader View" feature of most modern browsers. It's intended to be used with terminal RSS readers, to make the articles more readable on web browsers such as lynx. The code is closely adapted from the Firefox version and the output is expected to be mostly equivalent._

### Home page and sources:

1. Home page: _**See below**_
2. Source code: _**https://github.com/eafer/rdrview**_

### Dependencies:

1. libcurl
2. libxml2
2. libseccomp

**Comment by thunder-coding** [comment]
The `libseccomp` package needs to be ported first before working on this package: https://github.com/seccomp/libseccomp

**Comment by suhan-paradkar** [comment]
libseccomp..is already present.... if I am not wrong....

**Comment by thunder-coding** [comment]
> libseccomp..is already present.... if I am not wrong....


Nope it isn't

**Comment by Grimler91** [comment]
We have it in the root repo: https://github.com/termux/termux-root-packages/tree/master/packages/libseccomp

**Comment by Durgarao1432** [comment]
Hello.
I have termux app . But use chestunte error vastunnai.
Daniki yem cheyali sir

**Comment by msoose** [comment]
How to link dependency for `libseccomp` across repositories?

**Comment by xeffyr** [comment]
It is in root repo because it is a dependency of root package and nothing else from termux-packages requires it. Feel free to move it to main repo.

**Comment by msoose** [comment]
not sure what the preferred method is for this, #7442 open to add to main repo, then just naught it out of root repo?

**Comment by tathastu871** [comment]
```
TERMUX_PKG_HOMEPAGE=https://github.com/eafer/rdrview
TERMUX_PKG_DESCRIPTION="Firefox Reader View as a command line tool"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_SRCURL=https://github.com/eafer/rdrview.git
TERMUX_PKG_DEPENDS="libcurl, libseccomp, libxml2"
termux_step_pre_configure() {
	cd ${TERMUX_PKG_SRCDIR} && sed -i 's|PREFIX = /usr/local|PREFIX = /data/data/com.termux/files/usr/bin|' Makefile
}
```
But it wasnt cloning showing wrong version v

**Comment by xtkoba** [comment]
```bash
TERMUX_PKG_GIT_BRANCH=master
```

**Comment by tathastu871** [comment]
> ```shell
> TERMUX_PKG_GIT_BRANCH=master
> ```

Will you make PR for that.

**Comment by xtkoba** [comment]
Yeah, I will try it.

**Comment by tathastu871** [comment]
> Yeah, I will try it.

Sir if you have some time can you add new packages mentioned in https://github.com/termux/termux-packages/issues/8314 build.sh were given and tested once. I tried making PR but i am new to git and dont know how to merge and commit and everything getting mess.

So please if you can add them. Thanks in advance

**Comment by xtkoba** [comment]
Unfortunately I am not good at handling Git either, and actually in the past several PRs were closed due to me messing them up. I did not know about force-push until very recently, and even now I do not know about almost any feature of Git.

So it would be better if you could make PRs for yourself. I can instead advise you about the contents of the PRs.

**Comment by tathastu871** [comment]
> Unfortunately I am not good at handling Git either, and actually in the past several PRs were closed due to me messing them up. I did not know about force-push until very recently, and even now I do not know about almost any feature of Git.
> 
> So it would be better if you could make PRs for yourself. I can instead advise you about the contents of the PRs.

How can i make individual PR for individual commits.
Righ now whenever i git push all commits get merged to Same PR

**Comment by xtkoba** [comment]
Going off-topic. Please open a new discussion: https://github.com/termux/termux-packages/discussions/new

**Comment by tathastu871** [comment]
> Going off-topic. Please open a new discussion: https://github.com/termux/termux-packages/discussions/new

Just in case you have time try adding those packages.You seem to have more experience in resolving build erros as you have added many packages.
[#29](https://github.com/termux/termux-packages/issues/8314)
