### ISSUE TITLE
Can't import function 'link' from module 'os' 

### ISSUE THREAD

**Issue by duka97** [termux/termux-packages#6976]
**Problem description**
Python says that the function 'link' does not exist & errors when trying to call it

**Steps to reproduce**
`~ $ python`
`Python 3.9.5 (default, May  5 2021, 12:32:19)`
`[Clang 9.0.8` `(https://android.googlesource.com/toolchain/llvm` `project` `98c855489 on linux`
`Type "help", "copyright", "credits" or "license" for more` `information. `
`>>> from os import`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`ImportError: cannot import name 'link' from 'os'` `(/data/data/com.termux/files/usr/lib/python3.9/os.py)`

**Expected behavior**
The os module to be imported properly with all it's functions

**Additional information**
`Application version:`
`0.113`
`Packages CPU architecture:`
`aarch64`
`Subscribed repositories:`
`# sources.list`
`deb https://packages.termux.org/apt/termux-main/` `stable main`
`# science-repo (sources.list.d/science.list)`
`deb https://packages.termux.org/apt/termux-science` `science stable`
`# sources.list.d/cctools.list`
`deb https://cctools.info termux cctools`
`# x11-repo (sources.list.d/x11.list)`
`deb https://packages.termux.org/apt/termux-x11 x11` `main`
`# game-repo (sources.list.d/game.list)`
`deb https://packages.termux.org/apt/termux-games` `games stable`
`Updatable packages:`
`All packages up to date`
`Android version:`
`9`
`Kernel build information:`
`Linux localhost 4.4.111-21427293 #1 SMP PREEMPT Tue` `Apr 6 19:35:29 KST 2021 aarch64 Android`
`Device manufacturer:`
`samsung`
`Device model:`
`SM-G950F`
![Screenshot_20210608-232229_Termux](https://user-images.githubusercontent.com/44834754/121259893-ed8a5f80-c8b0-11eb-8d54-36e4838ec963.jpg)

**Comment by Grimler91** [comment]
Android does not support hard links. Use os.symlink instead

**Comment by duka97** [comment]
> Android does not support hard links. Use os.symlink instead

Sorry didn't know 
Thanks
What about os.confstr?

**Comment by Grimler91** [comment]
Also missing, see https://android.googlesource.com/platform/bionic/+/master/docs/status.md
