### ISSUE TITLE
Pkg upgrade not working

### ISSUE THREAD

**Issue by rrarararraa** [termux/termux-packages#6978]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```
Pkg upgrade not work please solve

**Comment by leapofazzam123** [comment]
What

**Comment by rrarararraa** [comment]
> Whatfor telegram scrap (pkg upgrade). Not work

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/6726
