### ISSUE TITLE
Hydra

### ISSUE THREAD

**Issue by evildevill** [termux/termux-packages#6996]
## I'm not able to use hydra please add hydra into termux

**Comment by suhan-paradkar** [comment]
> ## I'm not able to use hydra please add hydra into termux

Nope...not possible

**Comment by WMCB-Tech** [comment]
We don't provide packages for hacking tools anymore, and other pentesting tools such as metasploit, sqlmap

So you either:
* compile it yourself
* setup a distro and install hydra there

**Comment by layaachmad** [comment]
please note that Hacking packages are forbidden to request!
