### ISSUE TITLE
Package Request: `perl-cgi`

### ISSUE THREAD

**Issue by thunder-coding** [termux/termux-packages#6999]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

### Package description

Handle Common Gateway Interface requests and responses

**Link to home page and sources**

 https://github.com/leejo/CGI.pm

**Additional information**

`perl-cgi` is required by `git instaweb`. In case of unavailability, git instaweb will return a '500: Internal server error' without any logs.
More information here https://bbs.archlinux.org/viewtopic.php?id=203412

Have you compiled or tried to compile the package on device?
I don't have much knowledge about the perl ecosystem, that's why I didn't attempt to do so.

**Comment by suhan-paradkar** [comment]
I don't think this will be added...for 2 reasons:
1- Its a perl module....
2- It is deprecated

**Comment by thunder-coding** [comment]
That depreciated thing was really a nice catch @suhan-paradkar.

Anyways I wonder what will Git do to ensure working of `git instaweb`

**Comment by suhan-paradkar** [comment]
@thunder-coding I guess you can open a issue at git instaweb tho

**Comment by thunder-coding** [comment]
> @thunder-coding I guess you can open a issue at git instaweb tho

I am afraid to open up issues on Git Mailing list. I never know how they work

**Comment by Hax4us** [comment]
@thunder-coding  `perl-cgi` can be install by `cpan CGI`
