### ISSUE TITLE
golang: https fetch fails when downloading packages

### ISSUE THREAD

**Issue by vainikkaj** [termux/termux-packages#7]
It seems that package downloading fails from golang.org

    $ go get -d -v golang.org/x/tools/cmd/oracle
    Fetching https://golang.org/x/tools/cmd/oracle?go-get=1
    https fetch failed.
    import "golang.org/x/tools/cmd/oracle": https fetch: Get https://golang.org/x/tools/cmd/oracle?go-get=1: dial tcp: lookup golang.org on [::1]:53: read udp [::1]:44269->[::1]:53: read: connection refused
    package golang.org/x/tools/cmd/oracle: unrecognized import path "golang.org/x/tools/cmd/oracle"

and also from other non-github sites.

    $ go get -u -v github.com/rogpeppe/godef
    github.com/rogpeppe/godef (download)
    Fetching https://9fans.net/go/acme?go-get=1
    https fetch failed.
    import "9fans.net/go/acme": https fetch: Get https://9fans.net/go/acme?go-get=1: dial tcp: lookup 9fans.net on [::1]:53: read udp [::1]:56304->[::1]:53: read: connection refused
    package 9fans.net/go/acme: unrecognized import path "9fans.net/go/acme"

For reference, this is the output for running the previous command outside Termux:

    $ go get -u -v github.com/rogpeppe/godef                                                                                                                                                                            -( 23:40:52 ma elo 17 )->
    github.com/rogpeppe/godef (download)
    Fetching https://9fans.net/go/acme?go-get=1
    Parsing meta tags from https://9fans.net/go/acme?go-get=1 (status code 200)
    get "9fans.net/go/acme": found meta tag main.metaImport{Prefix:"9fans.net/go", VCS:"git", RepoRoot:"https://github.com/9fans/go"} at https://9fans.net/go/acme?go-get=1
    get "9fans.net/go/acme": verifying non-authoritative meta tag
    Fetching https://9fans.net/go?go-get=1
    Parsing meta tags from https://9fans.net/go?go-get=1 (status code 200)
    9fans.net/go (download)
    Fetching https://9fans.net/go/plan9?go-get=1
    Parsing meta tags from https://9fans.net/go/plan9?go-get=1 (status code 200)
    get "9fans.net/go/plan9": found meta tag main.metaImport{Prefix:"9fans.net/go", VCS:"git", RepoRoot:"https://github.com/9fans/go"} at https://9fans.net/go/plan9?go-get=1
    get "9fans.net/go/plan9": verifying non-authoritative meta tag
    Fetching https://9fans.net/go?go-get=1
    Parsing meta tags from https://9fans.net/go?go-get=1 (status code 200)
    Fetching https://9fans.net/go/plan9/client?go-get=1
    Parsing meta tags from https://9fans.net/go/plan9/client?go-get=1 (status code 200)
    get "9fans.net/go/plan9/client": found meta tag main.metaImport{Prefix:"9fans.net/go", VCS:"git", RepoRoot:"https://github.com/9fans/go"} at https://9fans.net/go/plan9/client?go-get=1
    get "9fans.net/go/plan9/client": verifying non-authoritative meta tag
    Fetching https://9fans.net/go?go-get=1
    Parsing meta tags from https://9fans.net/go?go-get=1 (status code 200)

**Comment by fornwall** [comment]
Does this work better after the update to version 1.5rc1-1 of the golang package?

**Comment by vainikkaj** [comment]
Yes, there's now `WARNING: linker: go has text relocations` messages but downloading seems to work.

**Comment by fornwall** [comment]
Great! Unfortunately the text relocation warning will be there until the following issue is fixed in go itself: https://github.com/golang/go/issues/9210

**Comment by franciscod** [comment]
The text relocation warning is still there and the linked issue is now closed. On this comment https://github.com/golang/go/issues/9210#issuecomment-148561361 a "gomobile" tool is mentioned (!)

**Comment by fornwall** [comment]
The golang issue is fixed for go 1.6, which will hopefully soon be available in beta form!

**Comment by fornwall** [comment]
@franciscod @robertvalik I've updated the `golang` package to `1.6beta1` which should fix the relocations warnings - try it out and raise a new issue if there is anything broken!

**Comment by franciscod** [comment]
recompiled a package of mine that gave warnings earlier: silently compiled ok!
