### ISSUE TITLE
Permission denied for files copied or created in home folder using MiXplorer

### ISSUE THREAD

**Issue by Mark-Joy** [termux/termux-packages#7002]
**Problem description**
In MiXplorer (with root access), create or copy any file to home folder. Permission 777 is granted automatically by MiX. Owner is UID of termux app.
Example:
`-rwxrwxrwx 1 u0_a485 u0_a485   62 Jun 14 06:14 hello2`

Open termux (home folder)
```
~ $ whoami
u0_a485
~ $ cat ./hello2
cat: ./hello2: Permission denied
~ $ ./hello2
bash: ./hello2: Permission denied
~ $ tsu u0_a485
:/data/data/com.termux/files/home $ cat hello2
#!/data/data/com.termux/files/usr/bin/bash
echo Hello World!!
```

**Steps to reproduce**
As above steps. In below clip, I also compare files `hello2` with `hello`. File `hello` is created by `nano` in termux

https://user-images.githubusercontent.com/22109528/121828161-f7fd8c80-cce8-11eb-80ae-2697c503a21f.mp4

**Expected behavior**
Files should be accessed or executed without `tsu`

**Comment by agnostic-apollo** [comment]
Likely issue is wrong [selinux context](https://github.com/termux/termux-app/issues/2080#issuecomment-846575028) of file.

Check with `/system/bin/ls -lZ hello2` under root (tsu) shell. Termux `ls` will just show `?` instead of context since its [not supported](https://github.com/termux/termux-packages/issues/544#issuecomment-436998591). Restore context with `/system/bin/restorecon -v hello2`.

**Comment by Mark-Joy** [comment]
It works. Thank you.
So is it MiXplorer causing the issue?
How to fix it without calling `restorecon` on every files?
```
.../files/home # /system/bin/ls -lZ hello2
-rwxrwxrwx 1 u0_a485 u0_a485 u:object_r:app_data_file:s0:c247,c257,c512,c768 62 2021-06-14 06:14 hello2
.../files/home # /system/bin/ls -lZ hello
-rwx------ 1 u0_a485 u0_a485 u:object_r:app_data_file:s0:c229,c257,c512,c768 62 2021-06-14 06:14 hello

.../files/home # /system/bin/restorecon -v hello2       SELinux: Loaded file_contexts
SELinux:  Relabeling /data/data/com.termux/files/home/hello2 from u:object_r:app_data_file:s0:c247,c257,c512,c768 to u:object_r:app_data_file:s0:c229,c257,c512,c768.
.../files/home # exit
exit
~ $ ./hello2
Hello World!!
~ $
```

**Comment by agnostic-apollo** [comment]
Report the issue to MiXplorer dev, maybe he can add support/option for running `restorecon` automatically on file creation/pasting or inheriting it from parent directory.
