### ISSUE TITLE
Cgicc library fails at configuration step while building.

### ISSUE THREAD

**Issue by Fernal73** [termux/termux-packages#7005]
**Problem description**
Unable to install GNU CGI C++ library. Configure fails.

**Steps to reproduce**
Download the latest version of cgicc library from 
ftp://ftp.gnu.org/gnu/cgicc/ and follow the steps to install the library:
```
$tar xzf cgicc-X.X.X.tar.gz 
$cd cgicc-X.X.X/
$./configure --prefix=/usr 
$make
$make install
```

**Expected behavior**
Library should be installed as expected.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# sources.list.d/pointless.bak
deb https://its-pointless.github.io/files/ termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.18.31-perf-g89c85bf #1 SMP PREEMPT Tue Oct 22 13:55:14 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Y1

```

**Comment by Grimler91** [comment]
What error do you get? What makes you think this is a termux issue, and not a cgicc issue (that should be reported to the cgicc developers)?

**Comment by xeffyr** [comment]
> and not a cgicc issue (that should be reported to the cgicc developers)?

This can be a missing dependency issue as well, but again this doesn't mean that a **bug report** should be submitted for `termux-packages`.

**Comment by Fernal73** [comment]
```
~/cgicc-3.2 $ ./configure --prefix=/usrchecking for a BSD compatible install... /data/data/com.termux/files/usr/bin/install -c
checking whether build environment is sane... yes
checking for mawk... no
checking for gawk... gawk
checking whether make sets ${MAKE}... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for g++... g++
checking for C++ compiler default output... a.out
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for executable suffix...
checking for object suffix... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for a BSD compatible install... /data/data/com.termux/files/usr/bin/install -c
checking build system type... WARNING: linker: /data/data/com.termux/files/home/cgicc-3.2/dummy-14752: unsupported flags DT_FLAGS_1=0x8000001
support/config.guess: unable to guess system type

This script, last modified 2001-09-04, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

    ftp://ftp.gnu.org/pub/gnu/config/

If the version you run (support/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2001-09-04

uname -m = aarch64
uname -r = 3.18.31-perf-g89c85bf
uname -s = Linux
uname -v = #1 SMP PREEMPT Tue Oct 22 13:55:14 WIB 2019

/usr/bin/uname -p = unknown
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              =
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = aarch64
UNAME_RELEASE = 3.18.31-perf-g89c85bf
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT Tue Oct 22 13:55:14 WIB 2019
configure: error: cannot guess build type; you must specify one
```

**Comment by Fernal73** [comment]
> Termux prefix is: `/data/data/com.termux/files/usr`, not `/usr` or `/usr/local`. Invalid prefix can also lead to configure issues.

This doesn't work.

**Comment by Fernal73** [comment]
> What error do you get? What makes you think this is a termux issue, and not a cgicc issue (that should be reported to the cgicc developers)?

I don't know. It's my first time building a package from source on Termux. But since the library has been around for eons really, I assume this script has been thoroughly tested and vetted on usual Unix and Linux suspects.

**Comment by Grimler91** [comment]
> support/config.guess: unable to guess system type
> 
> This script, last modified 2001-09-04, has failed to recognize the operating system you are using. 

Run `autoreconf -vfi` so that it updates the config.guess to a newer one

**Comment by Grimler91** [comment]
> > Termux prefix is: `/data/data/com.termux/files/usr`, not `/usr` or `/usr/local`. Invalid prefix can also lead to configure issues.
> 
> This doesn't work.

What does "this doesn't work" mean? Doesn't work in what way?

As xeffyr said you need to use `/data/data/com.termux/files/usr` for prefix, `/usr` will give permission denied when trying to install

**Comment by Fernal73** [comment]
> 
> As xeffyr said you need to use `/data/data/com.termux/files/usr` for prefix, `/usr` will give permission denied when trying to install

Actually, it didn't. It appears to pick up the correct prefix from Termux. If I had to specify the prefix that way, wouldn't I have to do the same in my script shebangs as well?

**Comment by Fernal73** [comment]
```
~/cgicc-3.2 $ make                     Making all in cgicc
make[1]: Entering directory '/data/data/com.termux/files/home/cgicc-3.2/cgicc'
Makefile:255: .deps/MStreamable.Plo: No such file or directory
make[1]: *** No rule to make target '.deps/MStreamable.Plo'.  Stop.
make[1]: Leaving directory '/data/data/com.termux/files/home/cgicc-3.2/cgicc'
make: *** [Makefile:159: all-recursive] Error 1
```

Above error while executing `make`.

**Comment by Fernal73** [comment]
My bad. I had downloaded the old version 3.2. 
The installation works with 3.2.19. thanks.
