### ISSUE TITLE
Python support in Ledger

### ISSUE THREAD

**Issue by thinlines** [termux/termux-packages#7006]
Hi! Package `ledger` seems to be compiled without Python support. Issue #4348 asked for Python 2 support for `ledger`, but Python 2 was being phased out, so the issue was closed. The current version of `ledger` now supports Python 3.

Can we build `ledger` with Python support now?

To add python support, a build option needs to be added. I asked on the `ledger` IRC, and this is probably what needs to be changed in `packages/ledger/build.sh`:

```
--- packages/ledger/build.sh	2021-06-14 19:00:14.941032910 +0800
+++ packages/ledger/new-build.sh	2021-06-14 19:02:38.651032855 +0800
@@ -3,15 +3,16 @@
 TERMUX_PKG_LICENSE="BSD 3-Clause"
 TERMUX_PKG_MAINTAINER="@termux"
 TERMUX_PKG_VERSION=3.2.1
-TERMUX_PKG_REVISION=3
+TERMUX_PKG_REVISION=4
 TERMUX_PKG_SRCURL=https://github.com/ledger/ledger/archive/v${TERMUX_PKG_VERSION}.tar.gz
 TERMUX_PKG_SHA256=92bf09bc385b171987f456fe3ee9fa998ed5e40b97b3acdd562b663aa364384a
-TERMUX_PKG_DEPENDS="boost, libc++, libedit, libmpfr, libgmp"
+TERMUX_PKG_DEPENDS="boost, libc++, libedit, libmpfr, libgmp, python"
 TERMUX_PKG_BREAKS="ledger-dev"
 TERMUX_PKG_REPLACES="ledger-dev"
 TERMUX_PKG_BUILD_DEPENDS="utf8cpp"
 # See https://gitlab.kitware.com/cmake/cmake/issues/18865:
 TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
 -DBoost_NO_BOOST_CMAKE=ON
+-DUSE_PYTHON=ON
 -DUTFCPP_PATH=$TERMUX_PREFIX/include/utf8cpp
 "
```

Thanks so much!

**Comment by thunder-coding** [comment]
@thinlines Would you like to do a PR?

**Comment by thinlines** [comment]
Sure, I can do that!

On June 14, 2021 11:00:30 PM GMT+08:00, YAKSH BARIYA ***@***.***> wrote:
***@***.*** Would you like to do a PR?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/termux/termux-packages/issues/7006#issuecomment-860754942

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
