### ISSUE TITLE
Termux-API: Not working

### ISSUE THREAD

**Issue by xx-Anonymous** [termux/termux-packages#7008]
[Boring]

Hi, a few months ago I downloaded Fdroid to get a more updated version of Termux, but it didn't install on my phone.
And a few weeks ago I tred downloading/installing Termux from Fdroid again, and it worked (suprisingly).

[Issue]

I using Termux:Float and it's working fine, but I can't copy/paste with a standard method.And I saw there is a walk-around with Termux-API.
I installed it from Fdroid, also installed the `termux-api` package in Termux.

But when I ran a bunch of `termux-api`commands the process just hangs.

It's probably worth noting that I tried downloading Termux-API from Google Play Store and it doesn't install.I tried downloading dummy apps and they installed fine.

I ran a `termux-info`...
Hope it's safe to show.
![Screenshot_20210613-201853](https://user-images.githubusercontent.com/76891810/121940072-00d47980-cd4e-11eb-826d-1419e6363f86.png)

Any immediate fixes?

**Comment by agnostic-apollo** [comment]
Check [Installation](https://github.com/termux/termux-app#Installation) for why installation wad failing.

As for `termux-api`, "a bunch of `termux-api` commands" is not a good description of a problem. Detail which commands you ran.

**Comment by xx-Anonymous** [comment]
Well I ran `termux-clipboard-get`, `termux-battery-status` and the last command I ran `termux-location` hanged for a few seconds and suprisingly enough asked for permissions, I allowed it but it's still failing.

**Comment by xx-Anonymous** [comment]
Nevermind I gave the app `Start--Up` permissions to run at boot and that fixed it.

![Screenshot_20210613-211804](https://user-images.githubusercontent.com/76891810/121947872-da670c00-cd56-11eb-895f-657997082085.png)
![Screenshot_20210613-211810](https://user-images.githubusercontent.com/76891810/121947900-e226b080-cd56-11eb-8acf-61e27b2784de.png)
