### ISSUE TITLE
How to install YouCompleteMe With Termux?

### ISSUE THREAD

**Issue by widhisec** [termux/termux-packages#7022]
https://github.com/ycm-core/YouCompleteMe
I tried to install this after installing it failed, is there another way to use this

**Comment by Grimler91** [comment]
Failed how exactly? What did you run? What was the full output that you got?

**Comment by widhisec** [comment]
have tried :YcmRestartServer, but to no result -- it

> Failed how exactly? What did you run? What was the full output that you got?

**Comment by widhisec** [comment]
<a href="https://ibb.co/cNTHnVn"><img src="https://i.ibb.co/cNTHnVn/IMG-20210618-035616.jpg" alt="IMG-20210618-035616" border="0"></a>
help me
