### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Frigginbully** [termux/termux-packages#7025]
Whenever i'm trying pkg-upgrade at some point it fails and shows 403 error in one of the repositories. Can't install anything and whatever I'm typing it's not showing until I'm putting a space.

**Comment by GuardianLiarus** [comment]
can confirm, i can't upgrade termux either

**Comment by thunder-coding** [comment]
Can you share your `termux-info` output

**Comment by xeffyr** [comment]
Follow instructions from https://github.com/termux/termux-packages/issues/6726.

**Comment by GuardianLiarus** [comment]
> Follow instructions from #6726.

worked on one of my devices but the other one has 403 even after switching to the grimler repo :/

**Comment by thunder-coding** [comment]
What version of Android are you using on both the devices

Remember that Termux is now only supported on Android 7.0+

**Comment by GuardianLiarus** [comment]
> What version of Android are you using on both the devices
> 
> Remember that Termux is now only supported on Android 7.0+

Android 7 on the device it worked, android 11 on the one where it didn't work,

I just reinstalled from Fdroid and it all works now, sorry for the trouble, and thanks for the help !
