### ISSUE TITLE
Typo in a library file causing some programs not to work

### ISSUE THREAD

**Issue by nisheri-ascar** [termux/termux-packages#7029]
**Problem description**
Hi, i was about to create a desktop environment  using lxqt, suddenly it wont start. I checked what was the problem and it was a library named `libicui18n.so.69`, lxqt was expecting `68` on it but the installed library is `69`. Also it seems not just lxqt is affected, also xfce4-terminal and qterminal
 

**Steps to reproduce**
Install lxqt
Type `lxqt-session &`

**Expected behavior**
It should start normally.

**Additional information**

```
CANNOT LINK EXECUTABLE "lxqt-session": library "libicui18n.so.68" not found
Aborted
```

**Comment by suhan-paradkar** [comment]
Its not a typo... It's because libicu has been updated.... can you try it after creating a symlink??
Try
```
cd $PREFIX/lib
ln -s libicui18n.so.69 libicui18n.so.68
```

**Comment by nisheri-ascar** [comment]
@suhan-paradkar thanks for the response. i tried making symlinks, though new errors appears. And i literally have no idea what is this

``` CANNOT LINK EXECUTABLE "lxqt-session": cannot locate symbol u_strToUpper_68 referenced by /data/data/com.termux/files/usr/lib/libQt5Core.so.5.12.11 ... Aborted ```

I think this should be on different issue.

**Comment by xeffyr** [comment]
Major version updates for libicu means ABI change. Symlinking won't work there which also the reason why library changed its filename.

**Comment by thunder-coding** [comment]
Looks like we should update Termux users about potential updates for libraries and big packages somewhere so that they don't panik for such errors

**Comment by nisheri-ascar** [comment]
The issue seems to be fixed now, thanks for all the responses.
