### ISSUE TITLE
Openssl-tool not found by apt

### ISSUE THREAD

**Issue by andresitodeguzman** [termux/termux-packages#703]
Did the apt-get update but still can't be found.
![screenshot_2017-01-28-10-15-14](https://cloud.githubusercontent.com/assets/10202948/22393504/b97062a4-e542-11e6-8c37-b18feca065ae.png)

**Comment by its-pointless** [comment]
Was recently upgraded 
apt update  ?

**Comment by andresitodeguzman** [comment]
@its-pointless did apt-update already. also other packages shows 404.

**Comment by vishalbiswas** [comment]
Try `apt update`

**Comment by andresitodeguzman** [comment]
@vishalbiswas did that and showed more 404s like vim.

**Comment by andresitodeguzman** [comment]
Seems like the update is missing for my arch. I am using an Zenfone (Intel processor). Probably there's an ARM but for intel seems missing that's why its throwing up a 404. 
![screenshot_2017-01-28-10-45-03](https://cloud.githubusercontent.com/assets/10202948/22393938/7936969e-e54d-11e6-86c3-dadc8b9b62dd.png)

**Comment by vishalbiswas** [comment]
No, the files are there. If you manually browse to https://termux.net/dists/main/binary-i686 you can see the packages. You just have the old InRelease file. For ex: openssl-tool was upgraded from 1.0.2j to 1.0.2k. But apt-get is still trying 1.0.2j which is not available.
Do `rm $PREFIX/var/lib/apt/lists/*` and then `apt update`

**Comment by andresitodeguzman** [comment]
@vishalbiswas still got a 404 
![screenshot_2017-01-28-15-00-18](https://cloud.githubusercontent.com/assets/10202948/22394977/8a403342-e56a-11e6-969f-8c83eb062247.png)

**Comment by fornwall** [comment]
@andresitodeguzman Are you sure that you are running `apt update` before running `apt upgrade`? If so, can you paste the output of `apt update`?

**Comment by andresitodeguzman** [comment]
Got it working now thanks for the reply.
