### ISSUE TITLE
I cant type password

### ISSUE THREAD

**Issue by Goodrol6** [termux/termux-packages#7038]
Im want to start up the vnc server but it doesnt let me type the password
./start-kali.sh
vncserver-start
Password:            <------ there i cant type

**Comment by xeffyr** [comment]
Passwords are not echoed to display, neither dots or "*" are shown.

**Comment by Goodrol6** [comment]
> Passwords are not echoed to display, neither dots or "*" are shown.

It doesnt let me type
i cant type anything

**Comment by leapofazzam123** [comment]
> > Passwords are not echoed to display, neither dots or "*" are shown.
> 
> It doesnt let me type
> i cant type anything

Are you an idiot or something

**Comment by Goodrol6** [comment]
> > > Passwords are not echoed to display, neither dots or "*" are shown.
> > 
> > 
> > It doesnt let me type
> > i cant type anything
> 
> Are you an idiot or something

Maybe you just toxic and im new

**Comment by xeffyr** [comment]
> It doesnt let me type

When you type password, **it won't be shown**. This is **expected behavior** for all standard password prompts in Termux & Linux distro console.
