### ISSUE TITLE
Nexphisher

### ISSUE THREAD

**Issue by Desxhwcke** [termux/termux-packages#7039]
**Problem description**

**Steps to reproduce**
After setting up the nexphisher, then I select Facebook then I select ngrok,then I was given the phishing link then after some times it's wipe out and goes to the begin or homemenu

**Expected behavior**

**Additional information**

```

```

**Comment by agnostic-apollo** [comment]
We do not provide support for hacking/phishing tools.

https://wiki.termux.com/wiki/FAQ#Where_are_Metasploit_and_Hydra_packages
