### ISSUE TITLE
Package Request: rclone

### ISSUE THREAD

**Issue by szhu** [termux/termux-packages#704]
http://rclone.org/

Edit: It's not really documented on the home page, but the correct download link for Android is https://github.com/ncw/rclone/issues/674#issuecomment-244797942

**Comment by Neo-Oli** [comment]
Note, that you can already quite easily install rclone in Termux.
Add this to yout `.bash_profile` to setup yout gopath. :
```
export GOPATH=$HOME/.go
PATH=$GOPATH/bin:${PATH}
```
Then you can run 
```
apt update && apt install golang git
go get -u github.com/ncw/rclone
```

**Comment by szhu** [comment]
Can I uninstall golang after I compile?

**Comment by szhu** [comment]
Just tried your tip above. The `go get -u github.com/ncw/rclone` line froze for me.

**Comment by Neo-Oli** [comment]
That's normal. Compiling it takes a while and go get works in complete silence. If you want to see what's going on run `go get -v -u github.com/ncw/rclone`
