### ISSUE TITLE
Does mupdf package work?

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#7041]
I installed the `mupdf` package but it does not seem to work. Trying 

```
mupdf foo.pdf
```

prints that `mupdf` command does not exist!

**Comment by xeffyr** [comment]
Mupdf package consists only of library.

**Comment by darmawan1122d** [comment]
![Screenshot_2021-06-23-18-52-37-65](https://user-images.githubusercontent.com/80916865/123092769-0b30fa80-d455-11eb-986d-c32dbe8b9fe5.jpg)
whyy??

**Comment by Grimler91** [comment]
@darmawan1122d change the repos as described in the README [here](https://github.com/termux/game-packages-21-bin) and [here](https://github.com/termux/science-packages-21-bin).

**Comment by angelog0** [comment]
@xeffyr wrote;

> Termux mupdf package consists only of library.

Then you should change the name, `mupdf-lib`, `mupdf-src` etc. otherwise it is confusing.

**Comment by xeffyr** [comment]
MuPDF is the original name of package and it **won't be changed**. Tools are available in package `mupdf-tools` which is a subpackage.

**Comment by Mark-Joy** [comment]
@xeffyr there are no libmupdf.so and libmupdf-third.so /usr/lib folder. Only .h files are in include folder

**Comment by buribu** [comment]
To display the text of a pdf document you can use : 

     lesspipe.sh foo.pdf|less

lesspepi.sh is part of the lazyread package.

**Comment by xeffyr** [comment]
Package consists only of static library. It is put into mupdf-static which really should be merged with mupdf.

**Comment by Mark-Joy** [comment]
@xeffyr 
Thank you for supporting this package
Is it possible to provide shared libs?
I would like to use it as a dependency of pymupdf. As I understand python module can only link against shared lib?
