### ISSUE TITLE
Why bother so much?

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#706]
Actually, there is a Debian package web for downloading all source code:

ftp.debian.org/debian/pool/main/(first letter of package or lib+first letter of the name of library)/(package name)

Why would we still need to have a build.sh for all packages?

Thanks

**Comment by vishalbiswas** [comment]
termux is a highly customized platform. Those build.sh files describe the steps needed to build a package for termux. Android libc (bionic) is not compatible with glibc. So, it is needed to customize the build process and thats what the build.sh script does.
Just read some of them (ffmpeg recommended) to get an idea of their purpose.
