### ISSUE TITLE
Some commands not working in root termux

### ISSUE THREAD

**Issue by Bruno-Codes** [termux/termux-packages#7075]
Some commands like pkg, vncserver, etc not working in termux.
I tried to login to ubuntu with proot-distro

**Comment by RossComputerGuy** [comment]
Ok, could you please post the errors your getting?

**Comment by WMCB-Tech** [comment]
> Some commands like pkg, vncserver, etc not working in termux.
I tried to login to ubuntu with proot-distro

Expected Behavior, they aren't supposed to be run as root

both `pkg` and `proot-distro` commands **do not** run as root

Suggestions:
* Run them as regular user
* suggesting to use chroot instead of proot, or run proot-distro as non-rooted shell

**Comment by BadWolves420** [comment]
my name is Heather and whoever has sent you all this information for termux

 has been hacking my account please disregard anything from them anymore
please if you can try to notify me when they have tried to contact you or
when my email has contacted you thank you
