### ISSUE TITLE
Pkg install forbidden problem

### ISSUE THREAD

**Issue by mukesh7766063808** [termux/termux-packages#7076]
When I am installing apt update and Apt upgrade .
Showing error.

**Comment by jpie726** [comment]
Same issue here
![Screenshot_20210629-212114](https://user-images.githubusercontent.com/53590846/123892336-03bf9480-d920-11eb-91fa-d7cc1a20abb2.png)

**Comment by thunder-coding** [comment]
Duplicate #6726
