### ISSUE TITLE
httpie

### ISSUE THREAD

**Issue by GitHubNeko** [termux/termux-packages#7077]
1. Home page:https://github.com/httpie/httpie#installation

2. Source code:https://github.com/httpie/httpie/archive/refs/tags/2.4.0.tar.gz

**Comment by Yonle** [comment]
![What](https://cdn.discordapp.com/emojis/805730315284250645.png?size=4096)

**Comment by thunder-coding** [comment]
Isn't it already available through `pip`?
https://github.com/httpie/httpie#windows-etc

**Comment by Yonle** [comment]
Well, Probably Package request

**Comment by Yonle** [comment]
Yet. It's already available through `pip`

**Comment by thunder-coding** [comment]
If there are problems with `httpie` installed on Termux, we may patch it. But if it works fine, then there's no need
