### ISSUE TITLE
Clang c99 features error

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-packages#7079]
Showing 

How to enable c99 features in clang?
I ask Sgminer developer he told me this error for your clang compiler not c99 standard..
Checking c99 features ..... No
And got error for c99 features
Any solution for this ?
![Screenshot_2021-06-29-02-47-25-248_com termux](https://user-images.githubusercontent.com/72664192/123929869-d7058e80-d9ac-11eb-87fa-e4ea33e19b70.jpg)
![Screenshot_2021-06-30-14-04-36-319_com termux](https://user-images.githubusercontent.com/72664192/123929902-dcfb6f80-d9ac-11eb-9acf-f35f5befb8c0.jpg)

**Comment by xeffyr** [comment]
1. Yes, you can't use `c++11` standard when compiling the C code. This option is valid only for C++.
2. `PTHREAD_CANCEL_*` is not available on Android, this issue is not specific to Termux but for everything that uses official Android NDK toolchain. You will need to patch the source code to omit such calls like we do for some packages.

**Comment by Saikatsaha1996** [comment]
> 1. Yes, you can't use `c++11` standard when compiling the C code. This option is valid only for C++.
> 2. `PTHREAD_CANCEL_*` is not available on Android, this issue is not specific to Termux but for everything that uses official Android NDK toolchain. You will need to patch the source code to omit such calls like we do for some packages.
> 
> P.S. Miners on Android devices are useless. Will damage battery by overheating more quickly then you will get "profit" (if even will be able to mine something).

I don't want to mine with my mobile
Just for testing purpose...

I am not miner .. but just want to use my OpenCL gpu as mine purpose...just trying... ..
And also I haven't any knowledge about c and c++ code

But if you have some solution please tell me 
If you give me solution and I get success , I feel really too much happy...


But for your fast support and reply I am happy..
Thank you @xeffyr
