### ISSUE TITLE
can not complete Kali Linux mobile download

### ISSUE THREAD

**Issue by Momo8609** [termux/termux-packages#7081]
Hello, I was trying to install Kali Linux mobile, unrooted version. But, when it gets to the end, it says can not complete download, file is corrupted, checksums do not match.  How do I go about fixing this, so that I may start using Kali? 
Thank you for your help and time.
Best Regards
Charity

**Comment by xeffyr** [comment]
Neither Kali Linux nor various its installers claiming to be compatible with Termux are actual Termux packages. Please report issue to the author of script you are using.

This repository as well as everything under https://github.com/termux is only about official Termux applications and packages. We will not review, debug and fix any third-party scripts.
