### ISSUE TITLE
Packaging request：dust

### ISSUE THREAD

**Issue by GitHubNeko** [termux/termux-packages#7082]
Description：Another more intuitive du command

home：https://github.com/bootandy/dust

Source code ：https://github.com/bootandy/dust/releases/tag/v0.6.0

**Comment by xeffyr** [comment]
Package will be available shortly.

Note that `dust` is not the first alternative to `du` available in our repository. We already have:
* `duc`
* `diskus`
* `tin-summer`

https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests
> Packages must NOT duplicate functionality of the already present ones.
