### ISSUE TITLE
Package request：dog

### ISSUE THREAD

**Issue by GitHubNeko** [termux/termux-packages#7087]
**I have read [Termux policy on package requests]**

**Package description**
dog is a command-line DNS client, like dig. It has colourful output, understands normal command-line argument syntax, supports the DNS-over-TLS and DNS-over-HTTPS protocols, and can emit JSON.

**Link to home page and sources**
1. Home page:https://dns.lookup.dog
2. Source code:https://github.com/ogham/dog

**Comment by leapofazzam123** [comment]
What
