### ISSUE TITLE
Unable to install Linux 

### ISSUE THREAD

**Issue by Beast1234567890** [termux/termux-packages#7090]
## Requesting new package
termux-setup-storage
pkg install wget

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

**Link to home page and sources**

1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by Grimler91** [comment]
? maybe you are experiencing https://github.com/termux/termux-packages/issues/6726

**Comment by thunder-coding** [comment]
> ? maybe you are experiencing https://github.com/termux/termux-packages/issues/6726

Seems like he is first time using GitHub, not his fault.

**Comment by Skime24** [comment]
Let chat on Facebook search for Skesh Mesh or WhatsApp me on this number
+2349077106540

**Comment by Skime24** [comment]
Still not working can you chat me up on WhatsApp +2349077106540
