### ISSUE TITLE
Neovim 0.5 released

### ISSUE THREAD

**Issue by fagcinsk** [termux/termux-packages#7093]
Neovim 0.5 released, please update version =)
https://github.com/neovim/neovim/releases/tag/v0.5.0

**Comment by raprocks** [comment]
I have been trying to compile neovim0.5 since 1 month niw with no luck
One time it compiled but gave error everytime it started which was prolly happening fue to something in tthe compiling steps. Will be great to see this on the repo.

**Comment by pandas-id** [comment]
when will this be finished? I can't wait to use it

**Comment by shadmansaleh** [comment]
@pandas-id when someone manages to get a working build . You can try yourself too :]
