### ISSUE TITLE
Unable to install wget

### ISSUE THREAD

**Issue by Beast1234567890** [termux/termux-packages#7094]
## Requesting new package
termux-setup-storage
pkg install wget

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [ ] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

$ pkg install wget
Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package wget
$ wget -O install-nethunter-termux https://offs.ec/2MceZWr
The program wget is not installed. Install it by executing:
 pkg install wget
$ pkg instsll wget
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package wget
**Link to home page and sources**

1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by RossComputerGuy** [comment]
Related to #6726

**Comment by notdadroid** [comment]
E: Unable to locate package wget

**Comment by Jooh1** [comment]
Please just help me solve the problem
