### ISSUE TITLE
Package request: ldc

### ISSUE THREAD

**Issue by joakim-noah** [termux/termux-packages#71]
ldc is a compiler for the D programming language, that uses llvm as its backend and comes standard in the Arch package repository and some other distros.  I've put all [the information necessary to build it from source with Android support on the D wiki](http://wiki.dlang.org/Build_LDC_for_Android).  There are only a couple changes from your standard setup:
1. llvm has to be built from source and slightly tweaked to turn off TLS for Android.
2. The libconfig library is needed.
3. You'll have to build from the git commit listed there, as I haven't built from the last source release in a bit and the git commit after that broke TLS in ldc.

I haven't actually tried cross-compiling the ldc compiler itself for Android, but I did build it natively _on_ Android using Termux and that worked fine, so simply supplying the usual CFLAGS/CXXFLAGS/LDFLAGS to the NDK compiler should work when cross-compiling ldc itself.  I had to add two small tweaks when natively compiling ldc, which I'll share.

I'd submit a PR, but I don't use Ubuntu.  If you prefer a PR and think your build scripts would work on Arch without much effort, I'll look into that.

**Comment by fornwall** [comment]
If you prefer a PR and think your build scripts would work on Arch without much effort,
    I'll look into that.

If you're willing to try out building packages on Arch I'm ready to help! It shouldn't be that many large changes required, but perhaps some small annoying ones :).

A starting point could be [ubuntu-setup.sh](https://github.com/termux/termux-packages/blob/master/ubuntu-setup.sh) for installing dependencies and setting up the ` /data/data/com.termux/files/usr`, perhaps a similar `arch-setup.sh` can be added? You can create a new issue for general Arch support when building.

As for a ldc package, would building a shared `llvm 3.7` package that would be used by both `clang` and `ldc` work (are the llvm patches needed for ldc suitable for that)? Currently llvm gets installed as part of clang, but that could be split out into a separate package if it would be useful.

**Comment by joakim-noah** [comment]
OK, I'll look into submitting a PR for ldc.

As for a standalone llvm package, I could modify my small patch that turns off TLS so that it's activated by a flag, which only ldc would use.  llvm 3.8 will have emulated TLS, so it will be obsoleted by that soon anyway.

I'll look into both and get back to you.

**Comment by joakim-noah** [comment]
Alright, finally looking into writing a PR for ldc, thanks for the libconfig packages.

I notice that you enable the `CMAKE_CROSSCOMPILING` flag with both the clang and disabled llvm packages, but that doesn't actually appear to be used, ie the stuff it puts in the `NATIVE/` directory. I ask because the cmake files for ldc call `llvm-config` to get the right flags, but there isn't a proper host llvm-config I can use.  The separate host build you do first can be made to build one, but it won't provide the proper flags.  Any idea what's going on there?

**Comment by fornwall** [comment]
Great! Are you basing the ldc work on llvm 3.8 (or is it possible to do)? I'm hoping to upgrade to llvm 3.8 shortly after release.

About cmake, I see that [If CMAKE_SYSTEM_NAME is preset, the CMake variable CMAKE_CROSSCOMPILING is automatically set to TRUE](http://www.vtk.org/Wiki/CMake_Cross_Compiling), so explicitly setting `CMAKE_CROSSCOMPILING` could be removed (but it will still be set automatically if I read the above correct).

About `llvm-config`, I'm not sure what the best solution is here. Perhaps introduce a "fake" llvm-config script used by the ldc build which outputs the correct value (perhaps by inspecting the llvm-config output on device)? It's a bit ugly, but would only be needed to be updated on each llvm update.

**Comment by joakim-noah** [comment]
Are you planning to separate llvm and clang into two termux packages?  I'm using llvm 3.7.1 right now, 3.8 should work fine too.

I'd rather build a host `llvm-config` that will provide the right flags for the target, which I think is the whole point of `CMAKE_CROSSCOMPILING` building the tools again in a separate `NATIVE/` directory.  I'll see if I can get that to work, and fall back to your suggestion if I can't.

**Comment by fornwall** [comment]
> Are you planning to separate llvm and clang into two termux packages? 

Yes! Perhaps the `subpackage.sh` mechanism can be used to extract the llvm parts from the clang build, see e.g. [packages/gcc/g++.subpackage.sh](https://github.com/termux/termux-packages/blob/master/packages/gcc/g%2B%2B.subpackage.sh).

> I'd rather build a host llvm-config that will provide the right flags for the target, which I think is the whole point of CMAKE_CROSSCOMPILING building the tools again in a separate NATIVE/ directory. I'll see if I can get that to work, and fall back to your suggestion if I can't.

Sounds good! Is the NATIVE/ directory is something specific for clang/llvm in how it uses CMAKE_CROSSCOMPILING or a general cmake concept?

**Comment by joakim-noah** [comment]
That directory is specific to llvm, as [cross-compiling invokes this cmake file, which creates the directory](https://github.com/llvm-mirror/llvm/blob/master/cmake/modules/CrossCompile.cmake#L57).
