### ISSUE TITLE
Rails does not work with ruby 2.4.0?

### ISSUE THREAD

**Issue by dancinglightning** [termux/termux-packages#710]
Hi 
Great, just great. 

And very up to date, with Ruby a bit too much so. 
In Ruby 2.4 there was a change to the way integers are handled internally. No problem for Ruby code. 
But all Ruby c extensions will need updating. A basic rails system needs about 60 gems,  4 of which have c  extensions. 
I got them all to compile, but the process segfaults. Most likely because of that integer change. 
I'm currently compiling Ruby 2.3.3 to confirm, and will update this tomorrow. 
But if this is so, could you do a package for it? 

Thanks for termux

Torsten

**Comment by fornwall** [comment]
I was just able to get Rails 5.0.1 up and running with Ruby 2.4.0 in Termux using the following steps:

```sh
apt update && apt upgrade
apt install clang libsqlite-dev libxslt-dev make pkg-config ruby-dev
gem install nokogiri -- --use-system-libraries
gem install rails
rails new blog
cd blog
termux-fix-shebang bin/rails
sed -i  '/tzinfo-data/d' Gemfile
echo "gem 'tzinfo-data'" >> Gemfile
bundle update
bin/rails server
```

Does a simple `rails new` project as above fail to run also for you, or do you require a more complete project to cause the segfault?

**Comment by dancinglightning** [comment]
good going. I didn't know about the ruby-dev. 
I can confirm your results rails5 works. 
My app was rails 4.2.7 and that being old must have different issues.
Upgrading is a bit more than i'm prepared to attempt on this device.
But i will give the 4.2 another go. definately the ruby2.4 assumption was wrong. I'll post later how it went.

But rails5 on android. wow. you shoukd let people know.

**Comment by dancinglightning** [comment]
So whatever I do,  4.2.7.1 segfaults. 
There is ison 1.8.6 in there as a candidate, but since it just stops I really don't know what to do. 
The app is here https://github.com/webdev-camp/webdev.camp
But I'm happy with the result that rails 5 works, so I'll close this. 
Torsten
