### ISSUE TITLE
the -m32 flag in clang crashes.

### ISSUE THREAD

**Issue by havanchuong** [termux/termux-packages#7100]
**I am trying to compile a 32bit executable but my device is aarch64.  I used g++ -m32 ... and got the following error**
`/sdcard/cpp $ g++ -m32 test.cpp -o test32
/data/data/com.termux/files/usr/bin/ld: cannot find crtbegin_dynamic.o: No such file or directory
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /data/data/com.termux/files/usr/lib/libc++_shared.so when searching for -lc++_shared
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /system/lib64/libc++_shared.so when searching for -lc++_shared
/data/data/com.termux/files/usr/bin/ld: cannot find -lc++_shared
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /data/data/com.termux/files/usr/lib/libc++_shared.so when searching for -lc++_shared
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /system/lib64/libc++_shared.so when searching for -lc++_shared
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /data/data/com.termux/files/usr/lib/libcompiler_rt-extras.a when searching for -lcompiler_rt-extras
/data/data/com.termux/files/usr/bin/ld: cannot find -lcompiler_rt-extras
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /data/data/com.termux/files/usr/lib/libgcc_real.a when searching for -lgcc_real
/data/data/com.termux/files/usr/bin/ld: cannot find -lgcc_real
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /data/data/com.termux/files/usr/lib/libcompiler_rt-extras.a when searching for -lcompiler_rt-extras
/data/data/com.termux/files/usr/bin/ld: cannot find -lcompiler_rt-extras
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /data/data/com.termux/files/usr/lib/libgcc_real.a when searching for -lgcc_real
/data/data/com.termux/files/usr/bin/ld: cannot find -lgcc_real
/data/data/com.termux/files/usr/bin/ld: cannot find crtend_android.o: No such file or directory
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)`

**My g++ version**
`/sdcard/cpp $ g++ -v
clang version 12.0.0
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin`

**What is the solution to this problem?.  Thank you**

**Comment by xeffyr** [comment]
Expected behavior. Termux doesn't support "multiarch" natively. You need to use clang in "cross-compiler' mode.

```
pkg install ndk-multilib lld
```

Then use clang as:
```
clang --target=armv7-linux-androideabi -fuse-ld=lld ...
```
