### ISSUE TITLE
Problem in using and executing packages...

### ISSUE THREAD

**Issue by ComeradeCharon** [termux/termux-packages#7106]
Hey guys,
I have been trying since many days to run the commands like metasploit framework, instahack, wifiphisher, routersploit and many more......in termux
There is always some kind of error and one of the most common error is - "unable to locate package". Whenever I try to execute any package, I go through the complete process of installing the package and I successfully install the packages without any kind of error but at the time of using and executing the package I'm stuck. So guys I want your help so that I can move further......
![20210705_220401.jpg](https://user-images.githubusercontent.com/79714322/124500535-9313ee80-dddd-11eb-8913-21012648e409.jpg)

**Comment by Grimler91** [comment]
> metasploit framework, instahack, wifiphisher, routersploit

We do not have any of those "hacking" packages, see https://wiki.termux.com/wiki/FAQ#Where_are_Metasploit_and_Hydra_packages.

If you think there is an issue with a package that we do have then please fill in the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=&template=bug_report.md)

**Comment by ComeradeCharon** [comment]
Yeah... but when I use TUANB4DUT.sh package it shows almost 200+ packages including routersploit, metasploit,  wifiphisher etc......

**Comment by Grimler91** [comment]
Ask the author of the script for help, it is not a termux package.
