### ISSUE TITLE
Building Emacs from master on Termux

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#7117]
Usually I do a montly build of Emacs master for GNU/Linux (+nox for WSL2), macOS, Windows, so tried also on Termux.

I did a build of Emacs from master (28.0.50, 20210706_170617, commit-1431fd91b4). I had to install only `texinfo` package and built with these steps (by means of a script):

```
./autogen.sh

./configure --prefix="${PREFIX}/opt/emacs-nox \
         --without-pop \
         --without-selinux \
         --with-modules \
         --with-x=no 

    patch src/filelock.c ~/emacs-build/src-filelock.c.patch
    patch src/emacs.c ~/emacs-build/disable-fdsan.patch
    patch src/fileio.c ~/emacs-build/src-fileio.c.patch

    make
```

Here:

```
gcc -v
clang version 12.0.0
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
Found candidate GCC installation: /data/data/com.termux/files/usr/bin/../lib/gcc/aarch64-linux-android/10.3.0
Found candidate GCC installation: /data/data/com.termux/files/usr/bin/../lib/gcc/aarch64-linux-android/11.1.0
Found candidate GCC installation: /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/10.3.0
Found candidate GCC installation: /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/11.1.0
Selected GCC installation: /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/10.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

The resulting buid seems to work (I use the same `init.el` file I use for your emacs-27, which is almost the same I use for nox builds on WSL2 and MSYS2) . As you know, Emacs 28 introduces the support of Menu in TTY which can be handled with mouse and in the `init.el` I have

```
(require 'mouse)
(require 'mwheel)
(unless window-system
  (xterm-mouse-mode t)
  (mouse-wheel-mode t))
```

This does not work very well because with the mouse I can open the menu on the menubar (File, Edit, ..., Help) but cannot open the menu items ( I have to use the arrow keys and ENTER). When I select text dragging the mouse with left button pressed the text appears selected only when I release the left button.

Anyway, the build is successful with only three of your patches. I think I need some other because Termux uses `$PREFIX`. I see you use something this

```
-			  "/tmp"))))
+			  "@TERMUX_PREFIX@/tmp"))))
```

but the question is: Does it depend on your build system? In other words, should I use

```
@TERMUX_PREFIX@/tmp
```

or

```
$PREFIX/tmp
```

or what else?

Why some of your patches are named `beforehostbuild`? BTW, the `server.el` and `term.el` does not apply...

I attach the build log in case you are interested..  It shows also a number of warnings..

[termux-emacs-master-nox-x86_64-20210706_170617-release-build.log.gz](https://github.com/termux/termux-packages/files/6776093/termux-emacs-master-nox-x86_64-20210706_170617-release-build.log.gz)

**Comment by xeffyr** [comment]
> Does it depend on your build system?

Yes, `@TERMUX_PREFIX@` is expanded to the full prefix path when patch is being applied. Patches are preprocessed with `sed`.

If you are building package outside of our build system, you will need to manually type a full prefix path, i.e.:
```
/data/data/com.termux/files/usr
```

`$PREFIX` is environment variable. Don't use it in string data if you are not sure whether it will be expanded properly or won't be changed in specific cases. In fact, Termux packages normally do not reference `$PREFIX` variable.

> Why some of your patches are named beforehostbuild?

These patches are applied for host builds, i.e. compiling for host environment (Ubuntu x86_64). Normal patches are applied only when cross-compiling, since may not be applicable for host builds.

**Comment by angelog0** [comment]
@xeffyr wrote

> If you are building package outside of our build system, you will need to manually type a full prefix path, i.e.:
> `/data/data/com.termux/files/usr`

Uhg! I suspected that..  but just a moment.. I use a (bash) script to do the build. Can I define some variable in the script to avoid that?

> These patches are applied for host builds, i.e. compiling for host environment (Ubuntu x86_64). Normal patches are applied only when cross-compiling, since may not be applicable for host builds.

That is not clear. In short, I want to build Emacs with 

```
## Start Termux and in the Emacs source tree
## Start the build script:

./autogen
.configure ....

## Apply patches

make
```

which patches I have to apply before `make`? Thanks.

**Comment by Grimler91** [comment]
> I use a (bash) script to do the build. Can I define some variable in the script to avoid that?

You can sed those template vars and apply the patches as the [build system does](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_patch_package.sh#L14,L20), so 
```sh
sed -e "s%\@TERMUX_PREFIX\@%${PREFIX}%g" name-of-patch | patch -Np1
```
should do it.

> That is not clear. In short, I want to build Emacs with

Most likely you have the highest chance of success when applying both the .patch and .patch.beforehostbuild patches. Some might not be needed when not cross-compiling though, depends on the package and the patch

**Comment by angelog0** [comment]
@Grimler91, I did something like that, roughly

```
sed -i.bkp -e '|@TERMUX_PREFIX@|/data/data/com.termux/files/usr|g' *.patch*
```

In any case, thanks for all the valuable suggestions!

**Comment by angelog0** [comment]
I have built Emacs master using a script which creates a `.7z` package of the binaries and installed these binaries on another device with Termux (I did the same with TeX Live!). 

The device on which I have built Emacs master has android 11 while the 2nd device on which I installed the binaries has Android 8.1. 

Now on this 2nd device trying to start Emacs 28 fails with

```
CANNOT LINK EXECUTABLE "/data/data/..../emacs-nox/bin/emacs": cannot locate symbol "getrandom" referenced by "/daa/data/..../emacs-nox/bin/emacs-28.0.50"...
```

Is it caused by a not installed library on this 2nd device, or the binaries built on android 11 are incompatible with Android 8.1?

TIA

**Comment by Grimler91** [comment]
> or the binaries built on android 11 are incompatible with Android 8.1

The system libraries, like libc.so, on android 11 has more features than your libc on the android 8 device. 
Emacs (and texlive) runs lots of tests when configuring to check what features are available, so the resulting binaries might cause problems on another device with another android version.
To make it work I guess you would need to run the configure script on the android 8 device, and then manually change the configure settings to match it when compiling on the android 11 device. So, for this particular error for example you probably want to configure with `./configure [...] ac_cv_func_getrandom=no`, which would then disable the use of getrandom.

It would be way safer/easier to cross-compile your programs from the docker image, the resulting binaries are suppose to be safe for all android >= 7 devices in that case (at the cost of some features being disabled on the newer versions)
