### ISSUE TITLE
simh with libslirp

### ISSUE THREAD

**Issue by naY9yjoS6ZqhOd35sIFH** [termux/termux-packages#7118]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***
i want simulate vax computer
### Package description
simh
a simulator for historic computer systems, as well as papers and reflections on the history of computing.

**Link to home page and sources**
1. Home page:
http://simh.trailing-edge.com/
https://gitlab.freedesktop.org/slirp/libslirp
2. Source code:
http://simh.trailing-edge.com/sources/simhv311-0.zip
https://github.com/simh/simh
https://gitlab.freedesktop.org/slirp/libslirp

**Additional information**
Have you compiled or tried to compile the package on device?
* simh doesn't build with slirp, qemu is build with slirp

**Comment by ifurther** [comment]
Is it has license file?

**Comment by naY9yjoS6ZqhOd35sIFH** [comment]
which one? the simh or libslirp?

**Comment by xeffyr** [comment]
@ifurther It's BSD.

**Comment by ifurther** [comment]
But simh has some code belong GPL

**Comment by xeffyr** [comment]
@ifurther Where are you looking? The source code archive from home page or repository on Github?

**Comment by ifurther** [comment]
I looked from Github, such as "AltairZ80/altairz80_cpu_nommu.c"

**Comment by naY9yjoS6ZqhOd35sIFH** [comment]
finally,i think use github one is correct
