### ISSUE TITLE
Mutt $PREFIX/etc/mime.types does not exist. 

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#712]
According to `man mutt` mutt looks for $PREFIX/etc/mime.types for default mime.types. That file doesn't exist. `$PREFIX/ete/mime.types.dist` however does, is distributed by mutt, and seems to have the right content. This causes mutt not to find `mime.types` and send out all attachments as `application/octed-stream`. This causes some clients (Outlook) to be unable to read attachments I send. 

```
$ man mutt | grep mime.types
       ~/.mime.types
       /data/data/com.termux/files/usr/etc/mime.types
$ ls $PREFIX/etc/mime*
/data/data/com.termux/files/usr/etc/mime.types.dist
```
Maybe there is some step missing during installation?

Temporary workaround: 
`cp $PREFIX/etc/mime.types.dist ~/.mime.types
`

**Comment by fornwall** [comment]
Thanks! The mutt build only installs `etc/mime.types.dist`.

We're now (https://github.com/termux/termux-packages/commit/670821324245826de7aca2f4ac6c631817239fd3) moving that to `etc/mime.types` in the updated `1.7.2-3` version of the package!

**Comment by Neo-Oli** [comment]
Thanks. I just realized (sorry for not catching this earler) that the same applies to `$PREFIX/etc/Muttrc` which is `$PREFIX/etc/Muttrc.dist`. Altough this files is probably much less important. The man page also makes reference to `$PREFIX/etc/mailcap` altough no `mailcap.dist` exists.

**Comment by fornwall** [comment]
Aha, I've pushed another update `1.7.2-4` which fixes `etc/Muttrc`.

`etc/mailcap` sounds interesting, to configure e.g. opening images in an external image viewer, but needs some investigation!

**Comment by Neo-Oli** [comment]
Thanks!
Most of my ~/.mailcap entries look like this:
```
application/pdf;                open %s  
```
~/bin/open
```
#!/data/data/com.termux/files/usr/bin/bash
f=$@
name=`basename "$f"`
name="$(echo $name | tr " " "_")"
ln -sfn "`readlink -e \"$f\"`" ~/www/$name
termux-open-url "https://localhost:8443/$name"
echo "Press enter to continue"
read void
rm ~/www/"$name"
```
I run a lighttpd server on Port 8080/8443 for the www directory, so this works quite well. Images it displays in the browser, other files it downloads to /sdcard/Downloads and opens them in whatever application cares for it.

I also have 
```
text/html;    w3m %s;nametemplate=%s.html                                                                                                             
text/html;    w3m -dump %s; nametemplate=%s.html; copiousoutput
```
Which renders all html mails with w3m and displays them straight in mutt. 
But I think most mutt users have these things configured anyway. All tutorials mention them. There isn't really a way to use mutt without copying some configuration file together
