### ISSUE TITLE
Ruby: Jekyll install error.

### ISSUE THREAD

**Issue by De4ce** [termux/termux-packages#713]
u0_a99@corsica:/ $ su
root@corsica:/ # gem install jekyll
Building native extensions.  This could take a while...
/data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/ext/builder.rb:76: warning: Insecure world writable dir /data/data/com.termux/files/usr/bin in PATH, mode 040777
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/ffi-1.9.17/ext/ffi_c
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20170130-25745-j6qztj.rb extconf.rb
/data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:1551: warning: Insecure world writable dir /data/data/com.termux/files/usr/bin in PATH, mode 040777
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... no
creating extconf.h
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/ffi-1.9.17/mkmf.log

current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/ffi-1.9.17/ext/ffi_c
make "DESTDIR=" clean

current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/ffi-1.9.17/ext/ffi_c
make "DESTDIR="
Configuring libffi
/data/data/com.termux/files/usr/bin/sh: 4: /usr/bin/env: not found
make: *** [libffi.mk:7: "/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/ffi-1.9.17/ext/ffi_c/libffi-arm-linux-androideabi"/.libs/libffi_convenience.a] Error 127

make failed, exit code 2

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/ffi-1.9.17 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/ffi-1.9.17/gem_make.out1|root@corsica:/ #

**Comment by Neo-Oli** [comment]
1. Do not `su`. It's not helpful and causes problems.
2. Install libffi-dev, clang, ruby-dev and make. `apt update && apt install libffi-dev clang ruby-dev make
3. Now you can do `gem install jekyll`

**Comment by natebass** [comment]
@Neo-Oli I proposed an addition to the "Troubleshooting" section in the Jekyll docs with your solution. Could you look it over?

**Comment by Neo-Oli** [comment]
@natebass It's good. I gave it a review. ;)
