### ISSUE TITLE
Installation of Man not possible 

### ISSUE THREAD

**Issue by Claus5607** [termux/termux-packages#7130]
pkg install man
Checking availability of current mirror:
bad
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package man

**Comment by Yonle** [comment]
Hey @Claus5607. Please Check [this] issue(https://github.com/termux/termux-packages/issues/6726)

**Comment by Claus5607** [comment]
tank's for your issue link.  I didn't know that the service is down
