### ISSUE TITLE
tor can't complete connect

### ISSUE THREAD

**Issue by salimicali** [termux/termux-packages#7131]
target : android 10 arm

 tor freeze on
[notice] Bootstrapped 10% (conn_done): Connected to a relay.

While the pc version runs properly .

**Comment by xeffyr** [comment]
> While the pc version runs properly .

Are your PC and Termux device connected to same network, so you can be sure that problem is not with ISP? Have you tried using bridges?

On Android 11 (AArch64) it connects without issues.
![Screenshot_20210711-201137](https://user-images.githubusercontent.com/25881154/125204142-6dc32c80-e284-11eb-86ff-d32d50bcc042.png)

Could be ARM-specific issue in your case, but I don't have such device to test.

**Comment by Grimler91** [comment]
Works fine on my android 11 arm device as well

**Comment by xeffyr** [comment]
Then OP's issue is either with networking or Tor somehow picked guard/relay node which was down.

**Comment by salimicali** [comment]
mobile and pc version run on same network and isp
I changed the ROM, but this is the result

**Comment by Grimler91** [comment]
@salimicali please fill in the [bug report template](https://github.com/termux/termux-packages/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and provide more info about your device, ROM and termux version

**Comment by salimicali** [comment]
Bug / Problem

tor can't complete (100%) connect (freeze on 10%)

While the pc version runs properly .(without bridge)

(mobile and pc version run on same network and isp)


target test on :
j5lte
Linux kernel 3.10.108
termux version 0.116
Tor version 0.4.5.7
------------------------------------
roms:
 lineageos 14(android 7),
bootleggers (android 10)
-------------------------------------
tor output:

Jul 12 01:14:06.894 [notice] Tor 0.4.5.7 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1k, Zlib 1.2.11, Liblzma 5.2.5, Libzstd N/A and Unknown N/A as libc.
Jul 12 01:14:06.900 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jul 12 01:14:06.901 [notice] Read configuration file "/data/data/com.termux/files/usr/etc/tor/torrc".                                                 Jul 12 01:14:06.912 [notice] I think we have 4 CPUS, but only 2 of them are available. Telling Tor to only use 2. You can override this with the NumCPUs option
Jul 12 01:14:06.913 [notice] Opening Socks listener on 127.0.0.1:9050
Jul 12 01:14:06.913 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
Jul 12 01:14:06.000 [notice] Parsing GEOIP IPv4 file /data/data/com.termux/files/usr/share/tor/geoip.
Jul 12 01:14:08.000 [notice] Parsing GEOIP IPv6 file /data/data/com.termux/files/usr/share/tor/geoip6.
Jul 12 01:14:09.000 [notice] Bootstrapped 0% (starting): Starting
Jul 12 01:14:12.000 [notice] Starting with guard context "default"
Jul 12 01:14:12.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Jul 12 01:14:12.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay

**Comment by salimicali** [comment]
I found the problem :
tor need a "special user" to access files with ownership permission.

 termux use the default Android user and does not support the Ubuntu systemd service 

For this reason, tor required make 'tor user' but can't created during installing
