### ISSUE TITLE
apksigner: no File.toPath() error

### ISSUE THREAD

**Issue by canandlamp** [termux/termux-packages#7132]
~/.../build/output $ apksigner sign --ks-type PKCS12 --ks /storage/emulated/0/canandlamp-release-key.keystore.new --in app-unsigned-debug.apk --out test-signed.apk
Keystore password for signer #1:
Exception in thread "main" java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:362)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)

_Originally posted by @canandlamp in https://github.com/termux/termux-packages/issues/5747#issuecomment-877899567_

**Comment by canandlamp** [comment]
why are old versions in repository not available if the "improved" code is apt to such hangups?

**Comment by Hax4us** [comment]
what's your android version ?

**Comment by canandlamp** [comment]
7

**Comment by Hax4us** [comment]
yes then error makes sense now , as it will not work in Android < 8 
`java.nio.file` was added in API level 26 ( Oreo )

**Comment by canandlamp** [comment]
is there a repository with previous versions? it used to work fine on this phone

**Comment by xeffyr** [comment]
Why no old versions? Server disk space optimization. Our hosting capabilities are **limited**. We are not Debian.

**Comment by xeffyr** [comment]
We can provide `apksigner-old` package, at least until complete JDK will be packaged.

**Comment by xeffyr** [comment]
`apksigner-old` has been [added](https://github.com/termux/termux-packages/commit/4b763b814060c89a05711ec51881b390f7dee40d) and will be available for installation shortly.

**Comment by canandlamp** [comment]
thanks.  works great with the old style java keystore, but the new style wasn't recognized.  sufficient for what's at hand here. thanks again

**Comment by Nemris** [comment]
@xeffyr I just noticed the new `apksigner`, but it seems the OpenJDK pulls in a ton of dependencies such as `cups`. Is there any way to skip those?

**Comment by xeffyr** [comment]
You really don't have extra 11MB for cups? Most of space is taken by JDK which takes 300 MB when installed.

**Comment by Nemris** [comment]
I ended up upgrading - but still, I'm kind of curious about why `cups` would be needed.

**Comment by Grimler91** [comment]
libcups is listed as a build dependency in [archlinux](https://archlinux.org/packages/extra/x86_64/jdk-openjdk/), so maybe the dependency can be moved to TERMUX_PKG_BUILD_DEPENDS? (I have not tested the build yet)

**Comment by xeffyr** [comment]
This is already done in latest rebuild: https://github.com/termux/termux-packages/blob/ed2f9246959a1cfc2601f599dcfd5068656cb541/packages/openjdk-17/build.sh#L9-L11

OpenJDK uses it internally for some functions even in headless build. So `cups` is still a dependency, even though indirect.
