### ISSUE TITLE
Cloning & installing locally errors

### ISSUE THREAD

**Issue by jackmcd101** [termux/termux-packages#7135]
I tried to clone & install https://github.com/niftycomedians/contracts locally on my Google Chromebook via Termux terminal but got these errors. Is there something that I’m doing wrong?
![997B935C-6DCE-4E6E-B707-252E8080D471](https://user-images.githubusercontent.com/59311318/125317121-c1765a00-e306-11eb-97c3-85bc69152432.jpeg)

**Comment by Grimler91** [comment]
You have encountered this issue: https://github.com/termux/termux-packages/issues/6726 see instructions there on how to solve it
