### ISSUE TITLE
Deprecated warnings/errors on truffle install

### ISSUE THREAD

**Issue by jackmcd101** [termux/termux-packages#7136]
Ran $ npm install -g truffle but got a lot of deprecated warnings & errors
![159BB83D-1C18-4D1A-9D09-9BF32AEE354E](https://user-images.githubusercontent.com/59311318/125338541-520c6480-e31e-11eb-8e35-8dd689f2a91c.jpeg)
![EAB8A085-45ED-475E-B505-B540F45FCD7F](https://user-images.githubusercontent.com/59311318/125338544-533d9180-e31e-11eb-93ca-f30647a9b563.jpeg)
![41D8D251-6011-4670-A9DA-41F5528D6ED2](https://user-images.githubusercontent.com/59311318/125338546-53d62800-e31e-11eb-999c-cba3d41edb00.jpeg)
![FC2AA21D-E6B4-4450-90DD-E753AE47C979](https://user-images.githubusercontent.com/59311318/125338550-546ebe80-e31e-11eb-90c4-be3688931dd6.jpeg)

**Comment by xeffyr** [comment]
All of these warning have no any relation to Termux. Most of them provide links with details.

Regarding last error - install `python` and `build-essential`. This is needed for `gyp` and native extensions.
