### ISSUE TITLE
Adding repositories (sources.list) and archives error

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#714]
I wanted to get some packages like hping .So I added a Debian repositories along with deb-src..
But the command apt-get update is just ignores it and gives me some errors...(I was installing aarch64 )
Please help me ....
Thanks

**Comment by Neo-Oli** [comment]
There is no way to make normal Debian packages work in Termux. Termux'  packages are specifically patched, compiled and most importantly, prefixed (`/data/data/com.termux/files/usr/bin` as opposed to `/bin`) for Android.

**Comment by Auxilus** [comment]
So are there any plans of including hping hydra msfconsole to termux ??

**Comment by Neo-Oli** [comment]
First I've heard of them. You're welcome to open package requests for them. You can also use the build environment to package them yourself. Some packages are very easy to compile for Termux, others require a lot of patches. If you manage to build them you can contribute them to the repository.

**Comment by Auxilus** [comment]
How can I do it .?  Is there any tutorials?
I'd absolutely love to do that

PS : I have knowledge in coding stuff...

**Comment by Neo-Oli** [comment]
There's a bit of a readme here: https://github.com/termux/termux-packages/blob/master/README.md
It boils down to:
1. clone this repository. 
2. add a folder to ./packages
3. Write build.sh script (I'd suggest you look at a few of the easy ones like [tty-clock](https://github.com/termux/termux-packages/tree/master/packages/tty-clock)
4. ./scripts/run-docker.sh ./build-package.sh <your package name>
5. add necessary patches (you'll mostly need to patch stuff in the makefile, like hard references to `/bin/sh`). >ou need to look at the error messages and fix stuff. Create patches (download source, `git init`, `git add --all`, `git commit -m "0"`, make changes, `git diff > ~/termux-packages/packages/yourpackage/<reasonable name>.patch`
Once it builds successfully it will have created a folder ./debs. You need to build for the arch of your android device. 
6. Copy the corresponding `<package>-version.deb` over to your device and install it with `dpkg -i <file>.deb`
7. Test on device
8. Submit a pull request with your package folder to this repository.

**Comment by Auxilus** [comment]
Sorry , it's getting insane ..Will you put a link for a video? If not then will you please patch hping , hydra,msfconsole for me??I am in so much need of 'em..thnks

**Comment by natebass** [comment]
@Auxilus Don't worry, I find it hard too :) It is a good opportunity to learn, @Neo-Oli's instructions are excellent. I might even try myself...
