### ISSUE TITLE
Termux are you rooted ?

### ISSUE THREAD

**Issue by byilmaz98** [termux/termux-packages#7144]
Hi, I installed termux on my mobile phone, tried to install python3, but every time I put " sudo python3 setup.py install " it tells me "No superuser binary detected. Are you rooted?" says. gives the message. Am I doing something wrong or is there a way to bypass this?
![image](https://user-images.githubusercontent.com/87454324/125711418-64bd5257-e194-4ef7-882f-b905da062be9.jpeg)

**Comment by NightOwl89** [comment]
No not yet i been trying different things but nothing i just have to wait
when i get home

**Comment by byilmaz98** [comment]
Remove "sudo" from command. problem solved

**Comment by Grimler91** [comment]
Yeah, termux is designed to work on non-rooted devices, so there is no reason to use sudo, ever. Only exception being some of the packages in root-repo that require root to function properly

**Comment by c00lpython** [comment]
So, for sudo python OneShot/oneshot.py -i wlan0 —iface-down -K
No superuser binary detected.
Are you rooted?
~ $ y
No command y found, did you mean:
 Command [ in package coreutils
 Command k in package kona
 Command o in package orbiton
 Command q in package q-dns-client
 Command X in package xorg-server from the x11-repo repository
 Command ya in package yazi
 Command yq in package yq
Idk
