### ISSUE TITLE
Possible cause: repository is under maintenance or down (wrong sources.list URL?).

### ISSUE THREAD

**Issue by Begomzapivom** [termux/termux-packages#7147]
**Problem description**
Hi! Problems with installing the distribution, please help.

**Steps to reproduce**

**Expected behavior**

**Additional information**

```
$ pkg install proot-distro
...
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
```

**Comment by agnostic-apollo** [comment]
Why are you putting dots where the actual error is shown and then asking for help?

Anyways, check #6726
