### ISSUE TITLE
stream audio to multiple devices 

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#7148]
## Requesting streaming audio to multiple devices via the command line in native Termux

- [√] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***
How to split and stream audio to multiple devices from one device via cli in native Termux is sought (a one tap config and setup script is wanted).  Please imagine a small group of people with some of them who have Termux installed on their Android smartphones who *wanna jam 2da same song* from every available Android smartphone high fidelity speaker.

Ffmpeg and [pulseadio work well in vanilla Termux](https://github.com/termux/termux-packages/issues/821#issuecomment-554599481_). Good job Termux! These commands work quickly and well on one device in native Termux to listen to a song:

    pulseaudio -D
    play output.mp3

How to channel audio from one device to many of them  simultaneously easily is pursued. What is the simplest way to stream audio to multiple devices? I would like one and more Android devices to play the right channel, and one and more Android devices to play the left channel of the same song from the command line in native Termux.

**Comment by xeffyr** [comment]
Please continue on same thread on Reddit: https://www.reddit.com/r/termux/comments/olklw3/requesting_streaming_audio_to_multiple_devices_in/

This is Termux bug tracker and not general discussion forum.
