### ISSUE TITLE
Function missing:makecontext

### ISSUE THREAD

**Issue by mjuned47** [termux/termux-packages#7160]
makecontext function is Missing and it is required to build library.
Is this available on termux ?

**Comment by xeffyr** [comment]
`makecontext` is not available for Android NDK.

You will need to implement it on your own, unless this is a system call or a function that uses system calls disallowed by seccomp.

**Comment by mjuned47** [comment]
Im building one package.
It has different file for different architecture and it compile according to architecture
How can i mention on build.sh that if it is aarch64 architecture then specify aarch64 files to include and compile?

**Comment by mjuned47** [comment]
You get check this :
https://github.com/lpcdma/coroutine_android

It has makecontext and other functions implemented for android
