### ISSUE TITLE
 packet capture issue 

### ISSUE THREAD

**Issue by slythno** [termux/termux-packages#7161]
![IMG_20210718_133628](https://user-images.githubusercontent.com/87435145/126060498-345155ef-f556-46d5-ace7-827c20c2b336.jpg)
How to install wlan0 extension properly do i have to build kernel ? My device is rooted and currently i'm running Android 10

**Comment by xeffyr** [comment]
> How to install wlan0 extension properly do i have to build kernel ?

You need:
* MAC80211 stack.
* USB Wi-Fi stick. Yes, external wifi module as internal won't work in 99.99% of cases.
* Drivers for your USB Wi-Fi stick chipset.

***

https://wiki.termux.com/wiki/Hacking

With use of Aircrack-NG software, you are on your own. We will not provide any help regarding customizing or compiling kernel, chosing right USB wifi sticks and software usage.
