### ISSUE TITLE
Unable to install lxml using pip2

### ISSUE THREAD

**Issue by Ak-Tools** [termux/termux-packages#7172]
pip2 install lxml
Collecting lxml
  Using cached https://files.pythonhosted.org/packages/e5/21/a2e4517e3d216f0051687eea3d3317557bde68736f038a3b105ac3809247/lxml-4.6.3.tar.gz
Installing collected packages: lxml
  Running setup.py install for lxml ... |

Then it stopped here. Please help!

And THANKS IN ADVANCE

**Comment by xeffyr** [comment]
> Running setup.py install for lxml ... |
Then it stopped here.

It will hang there for about 15 minutes, maybe more depending on device.

This is because Termux is not a standard platform and prebuilt wheels aren't available. Modules with their native extensions are built on device.

**Comment by ChiefMikeK** [comment]
[lxml · PyPI](https://pypi.org/project/lxml/ ) 
```
Requires: Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*
```  
Termux python pkg is newer the 3.4 🥇
