### ISSUE TITLE
How to fix that error

### ISSUE THREAD

**Issue by Tayaga-334** [termux/termux-packages#7178]
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/qemu-system-i386-headless_1%3a5.2.0-6_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by thunder-coding** [comment]
You can always comment on the same #7177. Please do not create a different issue

**Comment by Tayaga-334** [comment]
> You can always comment on the same #7177. Please do not create a different issue

I can’t wait that everyone is offline

**Comment by xeffyr** [comment]
> I can’t wait that people is offline

And I can't wait until people will start submit issues properly.

Your log at https://github.com/termux/termux-packages/issues/7178#issue-951510898 literally says nothing about the problem because is truncated.
