### ISSUE TITLE
rbedrock

### ISSUE THREAD

**Issue by Zeyrox1090** [termux/termux-packages#7181]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description
rbedrock is an extension package for R that supports the analysis and management of Minecraft (Bedrock Edition) worlds. This includes Windows 10, Pocket Edition, XBox, and PS4 versions of the game. It does not include Minecraft: Java worlds.

**Link to home page and sources**

1. Home page:https://github.com/reedacartwright/rbedrock
2. Source code:https://github.com/reedacartwright/rbedrock/archive/refs/tags/v0.1.0.zip

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment]
Needs R which isn't packaged for Termux (officially).
