### ISSUE TITLE
Package request: HEIC image converter (libheif or imagemagick)

### ISSUE THREAD

**Issue by Efreak** [termux/termux-packages#7184]
## Requesting new package

- [+] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description
Binaries for heif-convert and heif-enc for converting images to/from the high efficiency image format, used standard on some Android phones.

**Link to home page and sources**

1. Home page: http://www.libheif.org/
2. Source code: https://github.com/strukturag/libheif

**Additional information**
Have you compiled or tried to compile the package on device?
* The library compiles just fine on my phone by running `./autogen.sh && make -j4 install`
* The resulting binary did not convert an heif file saved by my camera, likely it needed one of the third party libraries (those require extra build steps)
* As an alternative, I think there's an heif plugin for imagemagick, which would allow using `convert`. This is also acceptable.
* Third party dependencies: libaom is needed for some features; meson is required for another optional features, other optional build dependencies are included, though I haven't tried building with them.

**Comment by landfillbaby** [comment]
just added libheif, and imagemagick support for it

**Comment by somu1795** [comment]
Awesome!
