### ISSUE TITLE
Library missed

### ISSUE THREAD

**Issue by Kin-Yon** [termux/termux-packages#7185]
I updated it from play store and it says library missed

**Comment by xeffyr** [comment]
> I updated it from play store

Please read the https://github.com/termux/termux-packages/issues/6726. Whole, especially statement about Play Store version deprecation.

> it says library missed

Context?!

This "it says" doesn't really say anything about the problem. When you report the issue, you should include the whole error message as well as the context (i.e. what has been done to get it).

Anyway, regarding Play Store and repository issues, - https://github.com/termux/termux-packages/issues/6726.

**Comment by Kin-Yon** [comment]
Sorry 

Its says

CANNOT LINK EXECUTABLE "data/data/com.termux/files/usr/bin/bash": library "libandroid-support.so" not found
