### ISSUE TITLE
Endless loading fakeroot.

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#7197]
## Hi all
While trying to compile a package for pacman in pure termux, a bug was noticed.  Fakeroot can get caught in a loop while accepting commands.  Also it doesn't respond to `ctrl+c` and `ctrl+x` commands, the only way to exit is to restart termux.  This happens with certain commands.  Example:
```
[[ -z "$(echo $LD_LIBRARY_PATH | grep fakeroot)" ]]
```

**Comment by xeffyr** [comment]
Possibly related to https://github.com/termux/termux-packages/issues/3148.

**Comment by Maxython** [comment]
So I set up fakeroot to proot and it works.  To do this, I changed the last condition in line 170.
```bash
if test -z "$*"; then
  export FAKEROOTKEY=$FAKEROOTKEY
  export LD_LIBRARY_PATH="$PATHS"
  #export LD_PRELOAD="$FAKEROOT_LIB"
  #FAKEROOTKEY=$FAKEROOTKEY  LD_PRELOAD="$FAKEROOT_LIB" ${SHELL:-/data/data/com.termux/files/usr/bin/sh}
  proot -0
  RESULT=$?
else
  export FAKEROOTKEY=$FAKEROOTKEY
  export LD_LIBRARY_PATH="$PATHS"
  #export LD_PRELOAD="$FAKEROOT_LIB"
  #FAKEROOTKEY=$FAKEROOTKEY  LD_PRELOAD="$FAKEROOT_LIB" "$@"
  proot -0 "$@"
  RESULT=$?
fi
```

**Comment by Maxython** [comment]
I also found the reason for the error, the infinite loop is due to the `libfakeroot.so` library, which is specified as `FAKEROOT_LIB=libfakeroot.so`.

**Comment by xeffyr** [comment]
> So I set up fakeroot to proot and it works.

And made it barely useless, `proot -0` is not same as `fakeroot`. The difference is that `proot -0` assigns `root` regardless of given `chown` value.

> the infinite loop is due to the libfakeroot.so library,

This is not reason. Error doesn't happen on devices with Android 7.0. It also unreproducible on [termux-docker](https://github.com/termux/termux-docker).

**Comment by Maxython** [comment]
> And made it barely useless

Maybe, but so far the temporary solution suits me.

> This "loop" doesn't happen on devices with Android 7.0

I have this happening on android 11 aarch64.

**Comment by rendiix** [comment]
any progress on this issues?
