### ISSUE TITLE
Unable to create a directory in termux

### ISSUE THREAD

**Issue by Ak-Tools** [termux/termux-packages#7205]
i recently tried to create a directory like

~ $ mkdir /test
mkdir: cannot create directory ‘/test’: Read-only file system

i tried fsck.

~ $ fsck -n -f
fsck 1.46.2 (28-Feb-2021)
WARNING: couldn't open /data/data/com.termux/files/usr/etc/fstab: No such file or directory
 
but it also shows another error 

plz help!!

and if your answer is remove '/'  from  '/test' then sorry but i wanted to create a directory like that....

THANKS IN ADVANCE.....

**Comment by agnostic-apollo** [comment]
The `/` is `rootfs` and is mounted read only. You can mount it as read/write if you have `root` access and then create directories in it with `root`.

If your device is not rooted, then just create a directory in termux home, which is the default directory working directory termux should start in unless changed. Run `pwd` to get current directory. Run `mkdir -p test` to create directory in current directory.

https://github.com/termux/termux-packages/wiki/Termux-file-system-layout#home-directory
