### ISSUE TITLE
Package request : ncrack

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#721]
Please release the ncrack package from nmap developers..

**Comment by Auxilus** [comment]
@fornwall @Neo-Oli You may close this issue...
I've got an alternative for this package..

**Comment by BKubi** [comment]
@Auxilux What is the name of the alternative package

**Comment by Auxilus** [comment]
I got hydra and found NSE scripts in nmap .... 😃

**Comment by BKubi** [comment]
can you give details to how you found the NSE scripts in nmap

**Comment by Auxilus** [comment]
[https://www.google.co.in/url?sa=t&source=web&rct=j&url=https://nmap.org/nsedoc/&ved=0ahUKEwj_ssa4qojSAhUDqo8KHbYOAgkQFghFMAU&usg=AFQjCNHtH-jnHXiwX9E53LV0A-M2Ge58TQ&sig2=-plf1sD5nkDm4789p2HR7g](url)

Use `--script=SCRIPTNAME` in nmap
