### ISSUE TITLE
Setting Manpages Sections order

### ISSUE THREAD

**Issue by isrgish** [termux/termux-packages#7213]
**Problem description**
When I run man for any command I get section 1p manpage instead of section 1 manpage. When I delete the mandoc.db file, I do get section, but I the following error.
`man: outdated mandoc.db lacks man(1) entry, run makewhatis /data/data/com.termux/files/home/ext4-fs/termux/usr/share/man`.
How can I force `makewhatis` to use section 1?
what's more even if I run `man 1 man` I still get section 1p.

![Screenshot_2021-07-30-10-13-00-130](https://user-images.githubusercontent.com/35469435/127666695-f5af49da-7adc-4182-b5d7-9c3a34c221f0.jpeg)

![Screenshot_2021-07-30-10-12-36-479](https://user-images.githubusercontent.com/35469435/127666722-1b140415-e271-4267-999f-d82d4ea72383.jpeg)

**Steps to reproduce**
1. `rm /data/data/com.termux/files/usr/share/man/mandoc.db`
2. `makewhatis /data/data/com.termux/files/usr/share/man`
3. `man man` or `man 1 man`

**Expected behavior**
I would expect to get the manpage for section 1. I'm getting the page for 1p.

**Additional information**
termux-info output
```Application version:
0.113
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable                                  Updatable packages:
All packages up to date                                                                            Android version:
10
Kernel build information:
Linux localhost 4.9.190+ #1 SMP PREEMPT Wed Jan 27 19:05:33 CST 2021 aarch64 Android
Device manufacturer:
LENOVO
Device model:
Lenovo TB-8705F

**Comment by agnostic-apollo** [comment]
What's the output of `ls /data/data/com.termux/files/usr/share/man/man1 | grep man`?

**Comment by isrgish** [comment]
> What's the output of `ls /data/data/com.termux/files/usr/share/man/man1 | grep man` ?


    demandoc.1.gz
    man.1.gz
    mandoc.1.gz
    manifest.1.gz
    mkmanifest.1.gz
    pod2man.1.gz

Now this is very interesting since when I don't have a mandoc.db file, `man` finds all section 1 pages. For example I tried `man find` and I got section 1 for find.

**Comment by xeffyr** [comment]
Issue is **unreproducible**. See video below. Note that I do not mess with $PREFIX in any way like moving it somewhere else from its standard location.

https://user-images.githubusercontent.com/25881154/127773160-04b1c481-ad61-4b65-b9ff-b233149f4700.mp4

**Comment by isrgish** [comment]
I just tried again to run `man man` and I got the correct section 1 page. This was after I deleted the `mandoc.db` and I didn't run `makewhatis`. I came back today and there is a new `mandoc.db` file and it works correctly.
Does termux automatically run something to make this `mandoc.db` file? If yes what? To me it seems that when I run it I get an incorrect file. But when it's run by termux it's fine.

**Comment by xeffyr** [comment]
Termux runs `makewhatis -Q` whenever you install or update package containing manuals. Note that path is not specified. You can try to re-run this command manually.

**Comment by isrgish** [comment]
I will try this.

**Comment by thunder-coding** [comment]
This issue is not reproducible by anyone else so closing this
