### ISSUE TITLE
Installing an custom apt

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#722]
I've got sqlmap in Python running and functioning on my termux ..But each time I have to run it through python2 sqlmap.py -u .......  How can I install it as an apt ..So that I can run it only by command sqlmap.?

**Comment by Auxilus** [comment]
[http://downloads.sourceforge.net/sqlmap/sqlmap-0.9.tar.gz ](url)

**Comment by vishalbiswas** [comment]
Install sqlmap using pip2
`pip2 install sqlmap`
Then you can use it just as you require.

**Comment by Auxilus** [comment]
Worked thanks..
But how do I use any bash shell script as a package or apt?

**Comment by vishalbiswas** [comment]
run termux-fix-shebang with it as the argument

**Comment by Auxilus** [comment]
I don't understand..Will you please give an example?

**Comment by Auxilus** [comment]
Say I wanna run boot.sh with only boot as a new package

**Comment by vishalbiswas** [comment]
That is a longer process. I was referring to that sqlmap example. You had to use `python sqlmap` because of the incompatible shebang.
Checkout termux-create-package for creating packages
