### ISSUE TITLE
apt update and most of other commands with apt do not work and give errors

### ISSUE THREAD

**Issue by mehdirasulov** [termux/termux-packages#7220]
So i have recently installed termux(on samsung galaxy Note 9 if that could help). I really like the idea of linux terminal on android but after installation i started having some issues with this app. For some time no package managers like apt pkg and etc were working for me but somehow after several reinstalls problem with pkg was partially solved.  But whatever i wouldn't do, apt rarely ever worked for me. It worked only ones when i was installing sl ( just for fun ). In any other cases like installing some package like docker or apt update it was giving this errors: 

apt update error: 

$ apt update
Hit:1 https://termux.mentality.rip/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease                                                           Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release                                                               403  Forbidden
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden                                                Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

docker installation error:

$ apt-get install docker.io -y
Reading package lists... Done
Building dependency tree                                        Reading state information... Done
E: Unable to locate package docker.io
E: Couldn't find any package by glob 'docker.io'
E: Couldn't find any package by regex 'docker.io'

**Comment by agnostic-apollo** [comment]
#6726
