### ISSUE TITLE
where do I get ashmem_create_region() and friends

### ISSUE THREAD

**Issue by rkitover** [termux/termux-packages#7222]
Hi, I don't see this in the headers or import libraries, and it's supposed to be in the ndk, where do I get this?

**Comment by xeffyr** [comment]
This function is by NDK libraries. It is in `libcutils` which is part of AOSP source tree: https://android.googlesource.com/platform/system/core/+/refs/heads/master/libcutils/ashmem-dev.cpp#365

**Comment by rkitover** [comment]
Would it be worthwhile to package this libcutil for termux? Or to make it part of ndk-sysroot?

**Comment by truboxl** [comment]
I think when something is part of AOSP, it usually needs root privileges...
You can try linking with `libandroid-shmem`:
https://github.com/termux/libandroid-shmem/blob/7f2448e175075e2ab62b69bd8bb672a67123bb7f/shmem.c#L115-L143

**Comment by xeffyr** [comment]
> You can try linking with libandroid-shmem:

ashmem_create_region is declared as static and is not in [exports](https://github.com/termux/libandroid-shmem/blob/master/exports.txt).

libandroid-shmem is a Sys V shared memory emulator. It doesn't provide ashmem functionality even though uses it internally.

**Comment by truboxl** [comment]
Oh right. Sorry. Then probably need to make your own function or stick with using the exports.
