### ISSUE TITLE
Error compile c++

### ISSUE THREAD

**Issue by A91K3C1l** [termux/termux-packages#7223]
Hi everyone I want to ask for help why can't i compile main.cpp file in my termux android 6.0 aarch64 here's a screenshot
![Screenshot_2021-08-01-07-36-07-41](https://user-images.githubusercontent.com/59974186/127755765-b45b98d0-2306-4346-aa48-4b3c3a685c0f.png)

**Comment by Grimler91** [comment]
See for example https://stackoverflow.com/questions/14620435/c-error-undefined-reference-to-main#14620598
