### ISSUE TITLE
Only working command is java ( openjdk-17 )

### ISSUE THREAD

**Issue by masrur10rahman** [termux/termux-packages#7224]
**Problem description**

Commands other than `java` produces a `libdl.so.2` error.

I've tried all other jdk commands but they show error like this :
```
Error: Unable to load main class com.sun.tools.{command}.Main in module jdk.compiler
        java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/opt/openjdk/lib/libnio.so: dlopen failed: library "libdl.so.2" not found: needed by /data/data/com.termux/files/usr/lib/libnet.so in namespace (default)
```

I've tried out openjdk from  [termux-ndk](https://github.com/Lzhiyong/termux-ndk) which works pretty decent

*My Device info*
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24 stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 main
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# sources.list.d/list.list
deb https://termux.xeffyr.ml/ extra main x11
# unstable-repo (sources.list.d/unstable.list)
deb https://grimler.se/unstable-packages unstable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.113-21183318 #1 SMP PREEMPT Fri Jun 4 20:29:11 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-M215F
```

**Comment by xeffyr** [comment]
Which package you have used to install jdk? I can't reproduce the issue.

**Comment by xeffyr** [comment]
`/data/data/com.termux/files/usr/opt/openjdk/lib/libnio.so` is linked against `libdl.so` and not the `libdl.so.2`. Check sanity of your Termux installation, possibly your openjdk is mixed with some custom variant.

**Comment by masrur10rahman** [comment]
I just changed my termux-repo, ran `pkg update && pkg upgrade` and openjdk-17 was automatically installed.

I ran `./java --version`, it was ok. But checking version of other commands threw that error. Compiling java code also throws same error.

**Comment by xeffyr** [comment]
Try `pkg remove libnet`.

**Comment by masrur10rahman** [comment]
`libnet` was not installed automatically, so I installed it now. But there is a new error showing : 
```
Error: Unable to load main class com.sun.tools.javac.Main in module jdk.compiler
        java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/opt/openjdk/lib/libnio.so: dlopen failed: cannot locate symbol "initInetAddressIDs" referenced by "/data/data/com.termux/files/usr/opt/openjdk/lib/libnio.so"...
```

**Comment by xeffyr** [comment]
You shouldn't install it. If it was not installed, you need to `rm` it. As I wrote previously
> Check sanity of your Termux installation, possibly your openjdk is mixed with some custom variant.

**Comment by masrur10rahman** [comment]
So, finally it worked. I re-removed `libnet` and checked if there was any library remaining related to that. Maybe I installed that before and it was not properly removed at the time of uninstalling  that time. Now it works absolutely fine.

Thanks :)

**Comment by Manamama** [comment]
Still good advice AD 2024! https://github.com/termux/termux-packages/issues/7224#issuecomment-890478800


So reproducible.
