### ISSUE TITLE
Provider "jrt" not found

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#7233]
**Problem description**
Provider "jrt" not found

**Steps to reproduce**
```
pkg install openjdk-17 ecj
cat <<- EOF > Hello.java
public class Hello {
	public static void main(String[] args) {
		System.out.println("Hello World!");
	}
}
EOF
ecj Hello.java
```

**Expected behavior**
The command `ecj` worked as expected until the last termux-packages update.

**Additional information**
Does this error have anything to do with `openjdk-17/stable,now 17.0-8 aarch64 [installed,automatic]`?
<!--
Post output of command 'termux-info' between '```' (code formatting).

```

```-->

**Comment by xeffyr** [comment]
**Please provide the exact command triggering the issue!** If you are sure that it is triggered by `ecj`, then provide full command line of `ecj` with arguments.

I won't let my device act as CI for third-party scripts, especially if this particular case (buildAPKs) write files to $PREFIX and tries to request permission for shared storage.

**Comment by xeffyr** [comment]
> Please provide the exact command triggering the issue! 

Nvm, updated your post.

**Comment by xeffyr** [comment]
As temporary fix, run `unset JAVA_HOME` before running `ecj`. It just conflicts with JDK installation.

**Comment by SDRausty** [comment]
> **Please provide the exact command triggering the issue!** If you are sure that it is triggered by `ecj`

`Provider "jrt" not found` is the whole error message.

> then provide full command line of `ecj` with arguments.

`ecj -d obj -sourcepath . ./src/com/commonsware/android/readwrite/ReadWriteFileDemo.java ./gen/com/commonsware/android/readwrite/R.java` is an example command line with `ecj` that triggers this error; Using `unset JAVA_HOME` resolves this error.

**Comment by SDRausty** [comment]
Closing issue since the `unset JAVA_HOME` fix resolves this issue.
