### ISSUE TITLE
Php does not execute

### ISSUE THREAD

**Issue by RoyalSuraj2001** [termux/termux-packages#7238]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double" referenced by "/data/data/com.termux/files/usr/bin/php"...
$

**Comment by agnostic-apollo** [comment]
Run `pkg install php` #7235

**Comment by xeffyr** [comment]
Run `pkg upgrade`. Make sure your `php` package version is `8.0.6-1`.
