### ISSUE TITLE
Bug report : hydra

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#724]
When I used hydra against Gmail on SMTP.gmail.com on port 465..It completes the task with different login: password pair each time...

But it works fine with normal SMTP ,FTP ,http , SSL..

**Comment by fornwall** [comment]
I suspect your issue is not Termux-specific, in which case you should raise the issue with the hydra project, https://github.com/vanhauser-thc/thc-hydra. You're welcome to raise this issue again if you find out that this is a Termux-specific one!
