### ISSUE TITLE
can't play any video with mpv-x

### ISSUE THREAD

**Issue by piyushgarg** [termux/termux-packages#7242]
**Problem description**

Not able to play any video using 
~ $ env DISPLAY=:1 mpv -vo=x11 -v  "https://live-indiatvnews.akamaized.net/indiatv-origin/live2/chunks.m3u8"

**Steps to reproduce**
pkg install x11-repo
pkg install mpv-x
env DISPLAY=:1 mpv -vo=x11 -v  "https://live-indiatvnews.akamaized.net/indiatv-origin/live2/chunks.m3u8"

**Expected behavior**
The video along with audio should be played using the mobile screen

**Additional information**

termux-info 
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.206-perf+ #1 SMP PREEMPT Sun Mar 7 03:24:59 UTC 2021 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(7)

mpv debug log

~ $ env DISPLAY=:1 mpv -vo=x11 -v  "https://live-indiatvnews.akamaized.net/indiatv-origin/live2/chunks.m3u8"
[cplayer] Command line options: '-vo=x11' '-v' 'https://live-indiatvnews.akamaized.net/indiatv-origin/live2/chunks.m3u8'
[cplayer] mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Jun 20 07:42:04 UTC 2021
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.70.100
[cplayer]    libavcodec      58.134.100
[cplayer]    libavformat     58.76.100
[cplayer]    libswscale      5.9.100
[cplayer]    libavfilter     7.110.100
[cplayer]    libswresample   3.9.100
[cplayer] FFmpeg version: 4.4
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/data/data/com.termux/files/usr --disable-gl --enable-jpeg --enable-lcms2 --enable-libarchive --enable-lua --enable-pulse --enable-openal --enable-caca --disable-alsa --enable-x11 --disable-wayland
[cplayer] List of enabled features: 52arch android asm build-date caca cplayer cplugins debug-build drm ffmpeg glibc-thread-name glob glob-posix gpl iconv jpeg lcms2 libarchive libass libavdevice libdl libm linux-fstatfs linux-input-event-codes lua openal opensles optimize posix posix-or-mingw pthreads pulse stdatomic vt.h x11 zlib
[cplayer] Reading config file /data/data/com.termux/files/usr/etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /data/data/com.termux/files/usr/etc/mpv/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'ao' = 'opensles' (flags = 4)
[cplayer] Setting option 'vo' = 'x11' (flags = 8)
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Waiting for scripts...
[osd/libass] libass API version: 0x1501000
[osd/libass] libass source: tarball: 0.15.1
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 2.3.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Done loading scripts.
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[ffmpeg] Opening https://live-indiatvnews.akamaized.net/indiatv-origin/live2/chunks.m3u8
[cplayer] Set property: shared-script-properties -> 1
[osd/libass] libass API version: 0x1501000
[osd/libass] libass source: tarball: 0.15.1
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 2.3.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Set property: shared-script-properties -> 1
[ffmpeg] Mime-type: 'application/x-mpegURL'
[demux] Trying demuxers for level=normal.
[lavf] Found 'hls' at score=100 size=233.
[ffmpeg/demuxer] hls: Skip ('#EXT-X-VERSION:3')
[ffmpeg/demuxer] hls: Opening 'https://live-indiatvnews.akamaized.net/indiatv-origin/live2/l_7805593_62724063_10454.ts' for reading
[ffmpeg/demuxer] hls: Opening 'https://live-indiatvnews.akamaized.net/indiatv-origin/live2/l_7805593_62730063_10455.ts' for reading
[lavf] avformat_find_stream_info() finished after 0 bytes.
[demux] Detected file format: hls (libavformat)
[demux] Stream is not seekable.
[cplayer] Opening done: https://live-indiatvnews.akamaized.net/indiatv-origin/live2/chunks.m3u8
[cplayer] Running hook: ytdl_hook/on_preloaded
[lavf] select track 0
[lavf] select track 1
[cplayer]  (+) Video --vid=1 (h264 854x480 25.000fps)
[cplayer]  (+) Audio --aid=1 (aac 2ch 44100Hz)
[vo/x11/x11] X11 opening display: :1
[vo/x11/x11] couldn't open the X11 display (:1)!
[cplayer] Error opening/initializing the selected video_out (--vo) device.
[lavf] deselect track 0
[cplayer] Video: no video
[ad] Codec list:
[ad]     aac - AAC (Advanced Audio Coding)
[ad]     aac_fixed (aac) - AAC (Advanced Audio Coding)
[ad] Opening decoder aac
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: aac (AAC (Advanced Audio Coding))
[af] User filter list:
[af]   (empty)
[cplayer] Starting playback...
[cplayer] EOF code: 6  
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[cplayer] finished playback, something happened (reason 4)
[cplayer] 
[cplayer] Exiting... (Errors when loading file)
[cplayer] Set property: shared-script-properties -> 1

**Comment by xeffyr** [comment]
> The video along with audio should be played using the mobile screen

Nope, it shouldn't. That's a program for X11 graphical environment and nothing will be displayed on Android screen.

See https://wiki.termux.com/wiki/Graphical_Environment on how to setup it.
