### ISSUE TITLE
Possible script typo that could cause issues over the time.

### ISSUE THREAD

**Issue by Martinvlba** [termux/termux-packages#7244]
Found weird thing among here https://github.com/termux/termux-packages/blob/2b49c79c210c72c9a152c1d0a963dc932ded217b/scripts/build/termux_step_setup_toolchain.sh#L22

This seems to casue some issues for me with bash compile in docker env where it started using host gcc and throws error

changing it to $CC seems to fix the issue

Could be just a issue for me but never know.

**Comment by Grimler91** [comment]
In the docker image it should be gcc, i.e. a compiler that compiles for the host (see for example [this](https://stackoverflow.com/a/40954603)). Changing to $CC would be incorrect since it is then the cross-compiler. 

Some projects do not handle this variable correctly. When you say bash compile you mean that you are trying to compile bash? That has worked before, are you trying to compile a new version of bash or something?

**Comment by Martinvlba** [comment]
https://pastebin.com/MXfcjYt7

**Comment by Martinvlba** [comment]
Also all scripts are same as current termux-packages beside modified prefix path in properties.sh

**Comment by Grimler91** [comment]
This is with `./build-package.sh bash` I suppose? Try if it works after `./clean.sh`, and/or when downloading dependencies instead, with `./build-package.sh -i bash`.

I just tried both build commands, and both work for me (I am not in the latest docker image though, updating now)

**Comment by xeffyr** [comment]
> works in latest docker image as well.

Confirming that it works, even with modified prefix:
```
diff --git a/scripts/properties.sh b/scripts/properties.sh
index 01e321170..f526233e8 100644
--- a/scripts/properties.sh
+++ b/scripts/properties.sh
@@ -14,7 +14,7 @@ else
 fi
 
 # Termux packages configuration.
-TERMUX_APP_PACKAGE="com.termux"
+TERMUX_APP_PACKAGE="hilled.pwnterm"
 TERMUX_BASE_DIR="/data/data/${TERMUX_APP_PACKAGE}/files"
 TERMUX_CACHE_DIR="/data/data/${TERMUX_APP_PACKAGE}/cache"
 TERMUX_ANDROID_HOME="${TERMUX_BASE_DIR}/home"
```

**Comment by Martinvlba** [comment]
Okay, could be just something with my environment i guess then. But thanks for testing.
