### ISSUE TITLE
Provide shared library (libmupdf.so) in mupdf package

### ISSUE THREAD

**Issue by Mark-Joy** [termux/termux-packages#7247]
## Requesting new package
`mupdf` package has mostly header files with no library. 
`mupdf-static` package provides only static libs.
Please support shared library (libmupdf.so) in mupdf.
It is needed for `PyMuPDF` - Python binding with support for `MuPDF`.

***

### Package description

MuPDF is a lightweight open source software framework for viewing and converting
PDF, XPS, and E-book documents.
See the documentation in docs/index.html for an overview.
Build instructions can be found in docs/building.html.

**Link to home page and sources**

1. Home page: https://mupdf.com/
2. Source code: [mupdf-1.18.0-source.tar.gz](https://mupdf.com/downloads/archive/)

**Additional information**
Have you compiled or tried to compile the package on device?

Yes

* If it did work then please share build steps and any patches that you had to apply.

Compile using below command:
`make XLIBS=-llog HAVE_X11=no HAVE_GLUT=no prefix=$PREFIX shared=yes `

**Comment by xeffyr** [comment]
Try `pkg upgrade` to install `1.18.0-1`. It should be already available on packages.termux.org and a bit later on mirrors.

**Comment by Mark-Joy** [comment]
One issue when run `mupdf-tools`
```
λ [~] $ muraster
CANNOT LINK EXECUTABLE "muraster": library "build/shared-release/libmupdf.so" not found
λ [~] $ mutool
CANNOT LINK EXECUTABLE "mutool": library "build/shared-release/libmupdf.so" not found
```
Possible fix is to copy latest `Makefile` and `Makerules` from: https://github.com/ArtifexSoftware/mupdf

Reference: [Don't hardwire path to $OUT in when linking against shared library.](https://github.com/ArtifexSoftware/mupdf/commit/7e6d92e63e31b55a397a5c7e9f37f92e74834524#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52)

**Comment by xeffyr** [comment]
This should be fixed in next update by https://github.com/termux/termux-packages/commit/ed992bc0b99335e9840e576ca8b2438c523169eb.

**Comment by Mark-Joy** [comment]
@xeffyr 
Somehow `mupdf-static` package was removed.
`PyMuPDF` needs `libmupdf-third.a` to compile, which is part of `mupdf-static`
Could both `mupdf` (shared lib) package and `mupdf-static` package be supported on Termux?
