### ISSUE TITLE
mosh-client 1.2.6 gives bus error

### ISSUE THREAD

**Issue by rajeevn1** [termux/termux-packages#725]
Mosh does not connect. Nexus 5x with 7.1.1

**Comment by fornwall** [comment]
As a check, does the problem remain after updating to latest package versions with `apt update && apt upgrade`?

**Comment by rajeevn1** [comment]
Yes, the problem remains

**Comment by lfourquaux** [comment]
Same here: mosh-client fails with a bus error.  This is on Nexus 5, Android 6.0.1, termux and packages up-to-date as of today (2017-02-03).
This is a recent change, mosh was ok a few weeks ago.

**Comment by fornwall** [comment]
@rajeevn1 @lfourquaux Does running `apt update && apt dist-upgrade` solve anything?

If the problem remains after that, can you run `apt list --installed | grep protobuf` and paste the output here?

**Comment by sedlund** [comment]
Same bus error (core dumped) after a conecting to mosh-server.

Here is output requested above:

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.                                                                   
libprotobuf/stable,now 3.2.0 arm [installed,automatic]
protobuf/stable,now 3.2.0 arm [installed]

**Comment by lfourquaux** [comment]
As I said, all packages were up to date. `apt update && apt dist-upgrade` today updated a few irrelevant packages. `mosh-client` still fails with bus error.

    $ apt list --installed | grep protobuf
    
    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    
    libprotobuf/stable,now 3.2.0 arm [installed,automatic]

**Comment by fornwall** [comment]
@lfourquaux @sedlund Thanks for your help with this issue!

I pushed an update of mosh to version 1.3.0-rc2, could you run `apt update && apt upgrade` again and see if this update fixes the issue?

I think this commit: https://github.com/mobile-shell/mosh/commit/0ceb4f26f4bf10656ea55f72e2388159c761d737, included in 1.3.0-rc2, should be fixing the issue.

**Comment by lfourquaux** [comment]
Indeed, it does fix this issue (at least, for me).  Well done!

**Comment by rajeevn1** [comment]
Yes. It fixed the issue for me too. Thanks
