### ISSUE TITLE
Mount fails because it can't find /etc/fstab

### ISSUE THREAD

**Issue by delight-aug** [termux/termux-packages#7256]
**Problem description**

`mount` exits with `mount: bad /etc/fstab: No such file or directory`

**Steps to reproduce**

`mount -t iso966 alpine-virt-3.14.0-aarch64.iso install-iso/`

**Expected behavior**

Mount insides of `alpine-virt-3.14.0-aarch64.iso` at `install-iso` (`/data/data/com.termux/files/home/storage/documents/virt/install-iso`) 

**Additional information**

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/termux-packages-24/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.205-g06e048269450 #1 SMP PREEMPT Tue Aug 3 06:24:11 UTC 2021 aarch64 Android
Device manufacturer:
Sony
Device model:
I4113
```

**Comment by xeffyr** [comment]
Is your device rooted?

Is your kernel has `iso966` module built in?

**Comment by delight-aug** [comment]
> Is your device rooted?

No. Do I have to root the device? It's no problem for me. 

> Is your kernel has `iso966` module built in?

I can't tell. There is no `module` directory inside `/system/lib` or `/system/lib64`. What are the other ways to find this out? BTW, I've tried mounting one directory at another, and it gave the same error.

**Comment by xeffyr** [comment]
> No. Do I have to root the device?

Well, that explains why mount attempted to use fstab in your case.

Mount of arbitrary file systems isn't possible without root and mounting file systems defined by fstab needs `mount` binary to be setuid root which obviously requires device to be rooted.

Termux is regular Android application. It doesn't have privileges for manipulating system state.

> There is no module directory inside

`cat /proc/filesystems` is enough to see what is supported.

Standard kernel used by Android doesn't have support of ISO file system.
