### ISSUE TITLE
Hi how can i get rid of this bash-5.1$? Its really annoying and i cant tell whenever i enter root mode..how do i get rid of it and restore $ back?

### ISSUE THREAD

**Issue by Ghostretri** [termux/termux-packages#7257]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```
![Screenshot_20210805-020130_Termux](https://user-images.githubusercontent.com/88169029/128266247-0901d18e-ed12-4de6-8eec-2cd1fc4253c4.jpg)

**Comment by agnostic-apollo** [comment]
That's the [`$PS1`](https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html). Override it in `~/.bashrc`.

For root issue, check https://github.com/agnostic-apollo/sudo#ps1
