### ISSUE TITLE
libc --> bionic

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#726]
How to replace a dependent libc6 with bionic when writing build.sh for a Debian package? Thanks.

**Comment by tomaklutfu** [comment]
Bionic libc is already in android system so you can  just remove it from dependencies . If some feature of libc6 is not in bionic then you need to either have patch for it or if defined in one of termux's own lib (I think they are named libandroid*) add it to dependencies.

**Comment by Wetitpig** [comment]
Thanks

**Comment by Wetitpig** [comment]
How about other libc (e.g. libc0.1). Are they also replaced by bionic?

**Comment by tomaklutfu** [comment]
They both look like libc implentation from packege info but I don't know how they differ. I think you can safely remove any libc dependency since android has only bionic libc and it is available in all devices.

**Comment by Wetitpig** [comment]
So how about patches due to difference in c libraries?

**Comment by fornwall** [comment]
@Wetitpig You can see the README for some information, and look at patches in other packages for inspiration.

**Comment by adhityapratama** [comment]
@fornwall [ERROR] The 'getdtablesize' function is not found in [libc.so]

In Wpscan installation. Help me. give answer ??

**Comment by tomty89** [comment]
https://github.com/aosp-mirror/platform_bionic/commit/462abab12b074c62c0999859e65d5a32ebb41951
