### ISSUE TITLE
pkg upgrade 

### ISSUE THREAD

**Issue by refziet** [termux/termux-packages#7260]
pkg upgrade
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Get:1 https://termux.mentality.rip/termux-packages-24 stable InRelease [14.0 kB]
Get:2 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 Packages [256 kB]
Ign:3 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:4 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:5 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Err:6 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

**Comment by agnostic-apollo** [comment]
Check #6726

**Comment by refziet** [comment]
thanks, sorry

Il giorno gio 5 ago 2021 alle ore 09:19 agnostic-apollo <
***@***.***> ha scritto:
