### ISSUE TITLE
Why i am unable to install lemon

### ISSUE THREAD

**Issue by Mrkhan041** [termux/termux-packages#7263]
## Requesting new package

- [ ] I have read [Termux packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

***

### Package description

**Link to home page and sources**

1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.
![Screenshot_20210805-220839_Termux](https://user-images.githubusercontent.com/88504212/128387934-09040568-8a18-4148-baa0-05855b643ff1.jpg)
![Screenshot_20210805-220836_Termux](https://user-images.githubusercontent.com/88504212/128387959-a4123cc6-3c1e-423c-a24e-8b5d4b834f49.jpg)

**Comment by Grimler91** [comment]
Well report it in the repository where you got lemon, and/or notify @Hax4us
