### ISSUE TITLE
libicui18n.so.68

### ISSUE THREAD

**Issue by leon12171** [termux/termux-packages#7275]
cannot link executable "node": library "libicui18n.so.68" not found termux
command "npm"

**Comment by xeffyr** [comment]
Have you tried `pkg upgrade`?

**Comment by staryzin** [comment]
> Have you tried `pkg upgrade`?

Obrigadooo!! me salvou, i love you

**Comment by fhatur12** [comment]
> Have you tried `pkg upgrade`?

Thankss lord😍😍😍
