### ISSUE TITLE
Unable to use php

### ISSUE THREAD

**Issue by Ak-Tools** [termux/termux-packages#7280]
![Screenshot_2021-08-07-09-14-56-59](https://user-images.githubusercontent.com/84968965/128586915-e2738a07-bbe3-47b0-9d00-cd6fd1bd3f38.png)

Can Anyone tell me what was wrong with the php.

**Comment by thunder-coding** [comment]
`pkg update`.
You have do not have latest libffi required by php. 
See #7238

**Comment by Grimler91** [comment]
`pkg upgrade`, as mentioned the dependencies are outdated
