### ISSUE TITLE
python modules error

### ISSUE THREAD

**Issue by Ak-Tools** [termux/termux-packages#7298]
Recently i'm creating an small python project for Android termux. the project is based on ai's like google assistant in termux. my 50% work has done and i also using the script for a long time but after trying an random script from internet without reading it. i'm unable to use my project. it showing me an error on modules.

import os

from os import system, path

import random

from gtts import gTTS

import time

import sounddevice as sd

import soundfile as sf

import os.path

from pydub import AudioSegment

import telebot

from telethon.sync import TelegramClient

from telethon.tl.types import InputPeerUser, InputPeerChannel

from telethon import TelegramClient, sync, events

Here is an list of modules used in the project.
And the error is given below.

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/ai/text.py", line 38, in <module>
    import sounddevice as sd
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/sounddevice.py", line 58, in <module>
    from _sounddevice import ffi as _ffi
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/_sounddevice.py", line 2, in <module>
    import _cffi_backend
ImportError: dlopen failed: cannot locate symbol "ffi_type_sint64" referenced by "/data/data/com.termux/files/usr/lib/python3.9/site-packages/_cffi_backend.cpython-39.so"...

Can anyone help me in this case.

**Comment by thunder-coding** [comment]
That seems to be problem with outdated `libffi`. Try `pkg update`.

And a really big warning.
**Never run some random scripts from internet as they can be malicious, unless you know what' it's doing and understand it**

**Comment by xeffyr** [comment]
`pkg upgrade` and then re-install `cffi` module with pip (don't forget to clean pip cache).

**Comment by Ak-Tools** [comment]
Thanks @thunder-coding and @xeffyr  for your reply. But tried pkg upgrade and reinstalled the cffi module, But it doesn't help...

**Comment by thunder-coding** [comment]
> Thanks @ thunder-coding and @ xeffyr  for your reply. But tried pkg upgrade and reinstalled the cffi module, But it doesn't help...

Did you clear pip cache?
`pip cache purge`

**Comment by Ak-Tools** [comment]
yes i do that But, isn't solved. I think i have to reinstall termux and then again install all packages and modules.
