### ISSUE TITLE
gdb problems: Ctrl-c doesn't work and can't load symbols from libc and three other system libraries

### ISSUE THREAD

**Issue by joakim-noah** [termux/termux-packages#73]
Ctrl-c to halt a program works fine from the Termux shell, but stops working in gdb.  Easy to check with a test program with a while(1) loop, can kill it from the command-line but cannot stop it in gdb.

Gdb can't seem to load symbols from the following system libraries, when run on a test program:
```
setpgrp failed in child: No such process
warning: Could not load shared library symbols for libc.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for libm.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for libstdc++.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for libnetd_client.so.
Do you need "set solib-search-path" or "set sysroot"?
```
I just tried "set sysroot" with /system and /system/lib, made no difference.  Not sure this matters that much, but maybe gdb can be configured to load those symbols?

Spun this issue off from #63.

**Comment by fornwall** [comment]
Some resources on the gdb package:

- [Current patches for the gdb package](https://github.com/termux/termux-packages/tree/master/packages/gdb) - many of them done just to get it compiling.

- https://code.google.com/p/android/issues/detail?id=86712 - issue about upcoming NDK version (the one after r10e) which should make building gdb from upstream cleaner without hacks.

- [build-gdbserver.sh](https://android.googlesource.com/platform/ndk/+/master/build/tools/build-gdbserver.sh) from the NDK.

**Comment by joakim-noah** [comment]
I'll take a look, see what I can find.

**Comment by fornwall** [comment]
The system shared libraries should now be found after updating the gdb package to `7.10.1-1`.

**Comment by fornwall** [comment]
The `setpgrp failed in child: No such process` error has been fixed, and it was this error which made e.g. Ctrl-c not working.

Update to the latest gdb package (`7.10.1-2`) with `apt update && apt upgrade` and re-open if any issue remain!

**Comment by joakim-noah** [comment]
Yep, verified that both are fixed now, thanks. :)

On the system libraries, isn't there a way to configure gdb, whether at compile-time or run-time, so that it looks there, without having to hard-code those paths as you did?  I'd think that'd be more maintainable, though maybe it doesn't work right, like the gdb command I tried above.
