### ISSUE TITLE
Package request: timg terminal image viewer

### ISSUE THREAD

**Issue by hzeller** [termux/termux-packages#7301]
## Requesting new package

- [x] I have read [Termux packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

***

### Package description
[timg](https://github.com/hzeller/timg) is a terminal image and video viewer that uses Unicode block characters to display images (alternatively can show these in high resolution if kitty or iterm2 protocol is implemented).

Images are shown nicely in termux with it.

**Link to home page and sources**
1. Home page:  https://timg.sh/ (same as github)
2. Source code: https://github.com/hzeller/timg/

**Additional information**

* Have you compiled or tried to compile the package on device?

Personally I did not, but as the author of timg, I received an issue ( https://github.com/hzeller/timg/issues/61 ) with the request to get it into termux; that user did compile timg successfully for termux, but would've liked smaller dependencies. I added a way to have a low-dependency (reduced feature) timg.

* If it did work then please share build steps and any patches that you had to apply.
Adding @bropines to this thread who did successfully compile timg.

**Comment by xeffyr** [comment]
Have you tried `termimage`? It uses Unicode block character by default too.

**Comment by bropines** [comment]
They are really similar, but this package cannot play videos, and timg has this capability.

**Comment by hzeller** [comment]
I don't know termimage, but it looks like it does half-block pixels but not the quarter block rendering that timg provides (thus higher horizontal spacial resolution). In general it does not seem to have any of the useful features of timg as a daily driver, such as showing images in a grid or using custom background color patterns etc.

(disclaimer: I am the author of timg so I know a lot more about the features of timg than termimage)

**Comment by xeffyr** [comment]
> They are really similar, but this package cannot play videos

As far I understand, with reduced dependencies `timg` can't play videos as well.

Package has been added, `pkg install timg`. It is available on main repository server now and should be delivered to mirrors in few hours. I have used flags as in https://github.com/hzeller/timg/issues/61#issuecomment-894712931.

**Comment by hzeller** [comment]
yes, if ffmpeg video decoding is disabled at build time, it won't be able to play videos.

**Comment by bropines** [comment]
Так. Как оказывается все нужные зависимости были, но я их не нашел под стандартными названиями. В итоге все нужные зависимости для программы есть, за исключением openslide. Я написал порядок установки, который можно поставить в скрипт установки. Все зависимости кроме openslide имеются в крупных пакетах таких как ffmpeg, поэтому его тоже надо ставить. 
Вот скрипт:
`apt install cmake git clang pkg-config
apt install libjpeg-turbo libexif ffmpeg graphicsmagick

git clone https://github.com/hzeller/timg.git
cd timg
mkdir build
cd build

cmake ../ -DWITH_VIDEO_DECODING=on - DWITH_OPENSLIDE_SUPPORT=off -DWITH_GRAPHICSMAGICK=on -DWITH_TURBOJPEG=on -DWITH_STB_IMAGE=off
make`
