### ISSUE TITLE
build-package.sh on android

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#731]
When I run the above script to test build a package, I don't have permission to access /data/$TERMUX_ARCH. 

How to solve the problem? Thanks

**Comment by Neo-Oli** [comment]
run `./scripts/setup-ubuntu.sh` to set up a build environment on your local Ubuntu 16.10. 
If you don't have an ubuntu 16.10 i suggest you use docker.
sudo apt install docker.io
`./scripts/run-docker ./build-package.sh <package>`

**Comment by Wetitpig** [comment]
I will try. Thanks.

**Comment by fornwall** [comment]
@Wetitpig To clarify, build-package.sh does not currently support building on-device, but needs a development environment setup (through
