### ISSUE TITLE
[Bug]: 2.0.0 Disabling old style v1.x proot-distro plug-in

### ISSUE THREAD

**Issue by Leif-W** [termux/termux-packages#7328]
### Problem description

proot-distro 2.0.0 clobbers 1.x plug-in scripts, leaving large orphaned distros.  I had ubuntu-21.04 installed yesterday with proot-distro 1.x and today it is inaccessible.  proot-2.0.0 inexplicably removed ubuntu-21.04 as an install option, also hindering use of the remove command.

### What steps will reproduce the bug?

1) Start with proot-distro 1.x
2) `proot-distro list` to see `ubuntu-21.04` among options
3) `proot-distro install ubuntu-21.04`
4) `proot-distro login ubunto-21.04` to verify versions
5) `pkg up` or other method to upgrade to proot-distro 2.0.0
6) See note about 1.x style plug-in disabled
7) `proot-distro list` no longer shows `ubuntu-21.04` as an option
8) `proot-distro login ubuntu-21.04` broken
9) `proot-distro remove ubuntu-21.04` broken

### What is the expected behavior?

Respect user with 900+ MB installed distro, to reuse distro, not have it orphaned and wasting space, or forced to download another 500MB distro, or forced to downgrade distro.  Detect installed distros.  If plug-in script format has changed, then update (convert, replace, regenerate, etc) old scripts.  If old scripts still work, then don't disable.  If ubuntu-21.04 omitted by accident, fix it.  If omitted for a specific reason, alert user.  Give user the information, option to choose action, etc.

### System information

```
Application version:
0.117                                                                                           Packages CPU architecture:
aarch64                                                                                         Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 main
# unstable-repo (sources.list.d/unstable.list)
deb https://grimler.se/unstable-packages unstable main
Updatable packages:
All packages up to date
Android version:
11                                                                                              Kernel build information:
Linux localhost 4.19.113-21564965 #1 SMP PREEMPT Wed Jul 21 11:13:37 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N986U1
```

**Comment by xeffyr** [comment]
Intended behavior. Versioned distributions will no longer be available. Plug-in format has been changed and it is not possible to use old ones anymore.

As already stated in https://github.com/termux/proot-distro/pull/109.

**Comment by xeffyr** [comment]
You can rename distributions in `$PREFIX/var/lib/proot-distro/installed-rootfs`.

Detection isn't possible by design. Rootfs directory is bound to file name of plug-in. It has never been planned to implement a metadata db for tracking the installed distributions or in any other way making script logic more complex.

**Comment by Leif-W** [comment]
Intended to leave large orphaned distros, got it.  Thanks for that.

**Comment by xeffyr** [comment]
`proot-distro` doesn't attempt to remove nor attempts to rewrite someting (including plug-ins) on its own. Plug-ins from v1.x were renamed by changing file extension to hide them, as attempt to use may lead to errors at least in cases when installing distribution.

If distribution is installed, you can `cd` into `$PREFIX/etc/proot-distro` and enable again needed plug-in:
```
cd $PREFIX/etc/proot-distro
mv ubuntu-20.04.sh.bak ubuntu-20.04.sh
```
Or you can rename rootfs instead to match the new plug-in name:
```
cd $PREFIX/var/lib/proot-distro/installed-rootfs
mv ubuntu-20.04 ubuntu
```

Otherwise `rm -rf` everything that you don't need.
