### ISSUE TITLE
[Bug]: proot-distro cannot start

### ISSUE THREAD

**Issue by GitHubNeko** [termux/termux-packages#7329]
### Problem description

When I finished updating proot-distro, I wanted to log in to nethunter, but it gave this error

Output：
Error: missing plugin for distribution 'nethunter'.

### What steps will reproduce the bug?

proot-distro login nethunter

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.117`  
**VERSION_CODE**: `117`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `true`  
**APK_RELEASE**: `Github Debug Build`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

## Termux:API App Info

**APP_NAME**: `Termux:API`  
**PACKAGE_NAME**: `com.termux.api`  
**VERSION_NAME**: `0.48`  
**VERSION_CODE**: `48`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `true`  
**APK_RELEASE**: `Github Debug Build`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `4.9.148`  
**SDK_INT**: `28`  
**RELEASE**: `9`  
**ID**: `HUAWEIVTR-AL00`  
**DISPLAY**: `VTR-AL00 9.1.0.228(C00E80R1P12)`  
**INCREMENTAL**: `9.1.0.228C00`  
**SECURITY_PATCH**: `2020-05-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `HUAWEI`  
**BRAND**: `HUAWEI`  
**MODEL**: `VTR-AL00`  
**PRODUCT**: `VTR-AL00`  
**BOARD**: `VTR`  
**HARDWARE**: `hi3660`  
**DEVICE**: `HWVTR`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Github

[Termux](https://github.com/termux/termux-app)  
[Termux:API](https://github.com/termux/termux-api)  
[Termux:Boot](https://github.com/termux/termux-boot)  
[Termux:Float](https://github.com/termux/termux-float)  
[Termux:Styling](https://github.com/termux/termux-styling)  
[Termux:Tasker](https://github.com/termux/termux-tasker)  
[Termux:Widget](https://github.com/termux/termux-widget)  
[termux-packages](https://github.com/termux/termux-packages)  

### Email

[termuxreports@groups.io](mailto:termuxreports@groups.io)  

### Reddit

[r/termux](https://www.reddit.com/r/termux)  

### Wiki

[Termux Wiki](https://wiki.termux.com)  
[Termux](https://github.com/termux/termux-app/wiki)  
[termux-packages](https://github.com/termux/termux-packages/wiki)  
##

**Comment by GrpeApple** [comment]
At 12c0c02465682e6906e6c33ac5397c12acc902e7, the "hax stuff" (nethunter) was exterminated on `proot-distro`, and this issue should not be here.

**Comment by layaachmad** [comment]
**NetHunter was removed from proot-distro**
