### ISSUE TITLE
[Package]: CC65

### ISSUE THREAD

**Issue by CrypticEnter** [termux/termux-packages#7340]
### Package description

cc65 is a complete cross development package for 65(C)02 systems, including a powerful macro assembler, a C compiler, linker, librarian and several other tools.

### Home page URL

https://cc65.github.io/

### Source code URL

https://github.com/cc65/cc65

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

There seems to be instructions on how to build it for Android already:
https://github.com/cc65/wiki/wiki/Android

**Comment by Grimler91** [comment]
Added in https://github.com/termux/termux-packages/pull/7423 thanks to @omecamtiv
