### ISSUE TITLE
[Bug]: Mosquitto (v. 2.0.11) does not read in the default configuration file mosquitto.conf upon startup

### ISSUE THREAD

**Issue by yasurok** [termux/termux-packages#7354]
### Problem description

Mosquitto (v. 2.0.11) does not read in the default configuration file mosquitto_conf upon startup. It needs to be explicitly specified with the -c option.

### What steps will reproduce the bug?

Just run 'mosquitto -v' and see if your own configurations in /data/data/com.termux/files/usr/etc/mosquitto/mosquitto.conf are reflected.

### What is the expected behavior?

Mosquitto reads in /data/data/com.termux/files/usr/etc/mosquitto/mosquitto.conf and apply the configurations in there.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.180 #3 SMP PREEMPT Tue Feb 16 14:14:47 UTC 2021 armv8l Android
Device manufacturer:
Amino
Device model:
Amigo7xJP
```

**Comment by xeffyr** [comment]
This actually the behavior defined by upstream. Please read the manual page on what it states about configuration file and `-c` option.

**Comment by olivluca** [comment]
Shouldn't the service file then specify the configuration file?

i.e. [this line ](https://github.com/termux/termux-packages/blob/5a02b5237eafe864f45557dcd53f2b903d4e53d1/packages/libmosquitto/build.sh#L18) should be

`TERMUX_PKG_SERVICE_SCRIPT=("mosquitto" 'exec mosquitto -c /data/data/com.termux/files/usr/etc/mosquitto/mosquitto.conf 2>&1')`
