### ISSUE TITLE
The file is exist but it keeps saying that "no such file or directory"

### ISSUE THREAD

**Issue by wooilok123** [termux/termux-packages#7360]
The file is exist but it keeps saying that "no such file or directory"
Can anyone help me out with this? thanks

![WhatsApp Image 2021-08-20 at 12 38 48 AM](https://user-images.githubusercontent.com/68337442/130109542-9aaa59bf-f574-4aba-84e5-c97c99bb97b6.jpeg)

_Originally posted by @wooilok123 in https://github.com/termux/termux-packages/discussions/7359_

**Comment by Grimler91** [comment]
You are trying to run something that is not compiled for android. See info in https://wiki.termux.com/wiki/Differences_from_Linux
