### ISSUE TITLE
[Bug]: qemu-system-aarch64 is broken

### ISSUE THREAD

**Issue by ulist** [termux/termux-packages#7363]
### Problem description

If i run `.../files/home # qemu-system-aarch64    -m 512M -cpu cortex-a57  -nographic -M virt` nothing shows up and i have to kill qemu it freezes 
Here is a strace log 
[log.txt](https://github.com/termux/termux-packages/files/7018842/log.txt)
I dont have this issue with qemu-system-x86_64
I need qemu aarch64 to build something require higher kernel 

### What steps will reproduce the bug?

.

### System information

termux-info:

```
~ $ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.10.108-DarkJoker360+ #2 SMP PREEMPT Mon Apr 19 15:27:08 EDT 2021 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
CAM-L21
```

**Comment by Yonle** [comment]
Well. I guess you need it's bios or something called `pflash` to work. You can get the bios/pflash by installing `ovmf` package and adding `-bios $PREFIX/share/edk2/.....fd` flag in the end of qemu-system-aarch64 command

**Comment by Yonle** [comment]
Also this is not a bug since you didn't load any of it's bios anymore. So it does not return any output at both serial console and monitor.

**Comment by ulist** [comment]
```
.../files/home # qemu-system-aarch64  -m 512M -nographic -cdrom /storage/87C1-0805/alpine-virt-3.12.7-aarch64.iso   -machine virt-3.1 -bios /data/data/com.termux/files/usr/share/edk2.git/aarch64/
QEMU_EFI-pflash.raw       QEMU_VARS.fd
QEMU_EFI.fd               vars-template-pflash.raw
.../files/home # qemu-system-aarch64  -m 512M -nographic -cdrom /storage/87C1-0805/alpine-virt-3.12.7-aarch64.iso   -machine virt-3.1 -bios /data/data/com.termux/files/usr/share/edk2.git/aarch64/QEMU_EFI-pflash.raw
```
Same it freezes

**Comment by Yonle** [comment]
Use `QEMU_EFI.fd` instead

**Comment by ulist** [comment]
Same

**Comment by Yonle** [comment]
Hmm. Try use `-M virt` instead of `-machine virt-3.1`

**Comment by ulist** [comment]
Now it work with -cpu option but it gives alot of output

**Comment by ulist** [comment]
![IMG_٢٠٢١٠٨٢٠_٠٧٠٣٥٧](https://user-images.githubusercontent.com/39057208/130177356-0869dc5d-51f9-4251-a1d2-bf2876963326.jpg)
