### ISSUE TITLE
exec("/data/data/com.termux/files/usr/bin/login"): Permission denied  [Process completed (code 1) - press Enter] please solve this [Bug]: 

### ISSUE THREAD

**Issue by SAC-h** [termux/termux-packages#7369]
### Problem description

When I open the app terminal Iam facing the big problem please solve this and it showing me this 
      exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

            PLEASE SOLVE

### What steps will reproduce the bug?

Don't no but it is not opening the terminal app

### What is the expected behavior?

I aspect that open the terminal app please

### System information

termux-info:

(```  I can't understand what you are saying which system
```)

**Comment by Grimler91** [comment]
Reinstall the app, or [launch a fail-safe terminal](https://wiki.termux.com/wiki/Recover_a_broken_environment) and fix the problem. Since you are not saying what you did to cause the issues it is hard to know what you need to do from a fail-safe session to fix it.

Reinstalling the app is the easiest fix.

**Comment by GrpeApple** [comment]
> ### Problem description
> 
> When I open the app terminal Iam facing the big problem please solve this and it showing me this
> exec("/data/data/com.termux/files/usr/bin/login"): Permission denied
> 
> [Process completed (code 1) - press Enter]
> 
> ```
>         PLEASE SOLVE
> ```
> 

Permission denied probably means that it has not enough permissions: `chmod +rx`

> ### System information
> 
> termux-info:
> 
> (``` I can't understand what you are saying which system

It was referring to what version of your Android version is.

**Comment by SAC-h** [comment]
I just enter in termux and it is stuck I just restart my phone then I came in and I open the termux it is showing me 
This exec("/data/data/com.termux/files/usr/bin/login"): Permission denied [Process completed (code 1) - press Enter] please solve this

**Comment by agnostic-apollo** [comment]
Post output of `stat /data/data/com.termux/files/usr/bin/login` from failsafe session.
