### ISSUE TITLE
Unable to use the sqlite3 node package on 32-bit arm

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#737]
Install deps with:

    apt install clang make nodejs-dev libuv-dev

Then

    npm install sqlite3

The resulting `sqlite3` binary segfaults on 32-bit arm (but works on 64-bit).

**Comment by bryanjhv** [comment]
Just to add something, I forgot to mention: also a change to `-fPIC` is needed in `cflags` (before `ldflags`).

**Comment by thunder-coding** [comment]
Closing this since this is an npm package issue and not a problem with Nodejs itself. Issues with npm packages should be reported upstream instead. Also this issue is bit old now, if this is still reproducible open up a issue upstream
