### ISSUE TITLE
[Bug]: Problem in VNC view through KeX

### ISSUE THREAD

**Issue by ZeeshanBillal** [termux/termux-packages#7370]
### Problem description

In termux, I'm not able to view in VNC after updating all packages through the KeX

### What steps will reproduce the bug?

After entering into termux and set up a KeX passwd for user it's Ok.
But when I want to enter to VNC it blow error message.
vncserver: No matching VNC server running for this user!
vncserver: No matching VNC server running for this user!

Error starting the KeX server.
Please try "nethunter kex kill" or restart your termux session and try again.

### System information

termux-info:

```

```
vncserver: No matching VNC server running for this user!
vncserver: No matching VNC server running for this user!

Error starting the KeX server.
Please try "nethunter kex kill" or restart your termux session and try again.

**Comment by xeffyr** [comment]
That's not Termux issue.
