### ISSUE TITLE
[Bug]: Unable to play recorded audio in termux

### ISSUE THREAD

**Issue by Ak-Tools** [termux/termux-packages#7372]
### Problem description

~ $ termux-microphone-record -d -f filename.mp3 -l 5 && play filename.mp3
Recording started: /data/data/com.termux/files/home/filename.mp3      Max Duration: 00:05
play WARN mp3-util: MAD lost sync
play WARN mp3-util: MAD lost sync
play FAIL formats: can't open input file `filename.mp3':

### What steps will reproduce the bug?

Try to update termux-microphone-record

### What is the expected behavior?

~ $ play 9790.mp3

9790.mp3:

 File Size: 4.32k     Bit Rate: 32.0k
  Encoding: MPEG audio
  Channels: 1 @ 16-bit
Samplerate: 24000Hz
Replaygain: off
  Duration: 00:00:01.08

In:0.00% 00:00:00.00 [00:00:01.08] Out:0     [      |      ]        ClIn:31.6% 00:00:00.34 [00:00:00.74] Out:8.19k [ -====|====- ]        ClIn:63.2% 00:00:00.68 [00:00:00.40] Out:16.4k [ -====|====- ]        ClIn:94.8% 00:00:01.02 [00:00:00.06] Out:24.6k [   ===|===   ]        ClIn:97.8% 00:00:01.06 [00:00:00.02] Out:25.3k [      |      ]        Clip:0
Done.
~ $

### System information

termux-info:

Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# sources.list.d/gushmazuko.list
deb https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
autoconf/stable 2.71-1 all [upgradable from: 2.71]                    binutils/stable 2.37-1 aarch64 [upgradable from: 2.36.1]
harfbuzz/stable 2.9.0 aarch64 [upgradable from: 2.8.2]
imagemagick/stable 7.1.0.4-9 aarch64 [upgradable from: 7.1.0.4-5]     proot/stable 5.1.107-42 aarch64 [upgradable from: 5.1.107-41]
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.82-perf+ #2 SMP PREEMPT Sat Mar 6 01:27:24 CST 2021 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH1901

**Comment by Ak-Tools** [comment]
Please help me.....

**Comment by Ak-Tools** [comment]
Hello! why My issue is not solving...

**Comment by xeffyr** [comment]
@Ak-Tools Do not expect that your issue will be solved immediately.

**Comment by Ak-Tools** [comment]
@xeffyr i know but i uploaded this yesterday and since no response on this.

**Comment by xeffyr** [comment]
So? You still need wait. I do not work on Termux 24x7 but rather in my spare time as well as other maintainers. 

Why you assume that file in in MP3 format? On my device `termux-microphone-record` records in m4a or something like. Check your file format and recode into supported by `play` utility.

**Comment by Houin2** [comment]
I have this problem, the audio does not sound at all in termux, much less in emulators like mobox and darkos 😭 I tried to solve it, I have been trying for more than 3 days and I couldn't winlator, use winealsa and The sound works, it only happens to me in termux. 
My device is not android, it is harmonyos 3.0 compatible with android 12 matepad 11 stereo sound the tablet runs mobox darkos normal performance in games less audio Any solution ? I'm not the only one who read similar comments 🥲
