### ISSUE TITLE
[Package]: dmidecode

### ISSUE THREAD

**Issue by DmitrySandalov** [termux/termux-packages#7385]
### Package description

 Dmidecode reports information about the system's hardware as described in the
 system BIOS according to the SMBIOS/DMI standard.
 
 This information typically includes system manufacturer, model name, serial
 number, BIOS version, asset tag as well as a lot of other details of varying
 level of interest and reliability depending on the manufacturer. This will
 often include usage status for the CPU sockets, expansion slots (e.g. AGP, PCI,
 ISA) and memory module slots, and the list of I/O ports (e.g. serial, parallel,
 USB).
 
 Beware that DMI data have proven to be too unreliable to be blindly trusted.
 Dmidecode does not scan the hardware, it only reports what the BIOS told it to.

### Home page URL

https://www.nongnu.org/dmidecode/

### Source code URL

https://download.savannah.gnu.org/releases/dmidecode/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Did not try to compile it on device.

**Comment by Grimler91** [comment]
Does your android device have `/sys/firmware/dmi`? If not then there's no information for dmidecode to parse

**Comment by DmitrySandalov** [comment]
Right... No `/sys/firmware/dmi`, just a regular smartphone, without BIOS. Closing the issue then?

(Wanted to get screen and brand info, smth. like `sudo dmidecode | grep -A3 '^System Information'`)

**Comment by Grimler91** [comment]
You can get quite a lot of information with `hwinfo`, from the root repo. The amount of information might vary depending on how old the kernel is though

**Comment by bt4ibwem8** [comment]
@Grimler91 
hi, you know about some tool from Termux which tells me if my RAM is DDR3 or DDR4? in `hwinfo --memory` i do not see this information.
