### ISSUE TITLE
[Bug]: zsh is missing  zsh/param/private module

### ISSUE THREAD

**Issue by AliTajelsir** [termux/termux-packages#7391]
### Problem description

- `zsh 5.8-7` package is missing `zsh/param/private` module. So it can't be managed with [znap](https://github.com/marlonrichert/zsh-snap) pluging manager.

### What steps will reproduce the bug?

- Install [znap](https://github.com/marlonrichert/zsh-snap) pluging manager
- Source the plugin
- Error due to absent `zsh/param/private` module
- Further details are found in issue #https://github.com/marlonrichert/zsh-snap/issues/107

### What is the expected behavior?

- Installing and sourcing the plugin should work correctly.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.205-g67ef830 #0 SMP PREEMPT Mon Aug 23 00:42:44 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Mi Max 3
```

**Comment by Grimler91** [comment]
Should be added in https://github.com/termux/termux-packages/commit/1ff378008f2b0a13450553e512b8c95eca0e4de7, please let us know if it works after you've updated to 5.8-8 (should be available in a few minutes on main repo, and within a few hours on mirrors)

**Comment by AliTajelsir** [comment]
> Should be added in [1ff3780](https://github.com/termux/termux-packages/commit/1ff378008f2b0a13450553e512b8c95eca0e4de7), please let us know if it works after you've updated to 5.8-8 (should be available in a few minutes on main repo, and within a few hours on mirrorback.

OK I'll report back
Tanks for your hardwork!

**Comment by AliTajelsir** [comment]
The plugin is working fine now. Thanks for the help!
