### ISSUE TITLE
[Bug]: lxappearance does not run

### ISSUE THREAD

**Issue by AspirusFromScratch** [termux/termux-packages#7392]
### Problem description

lxappearance does not run with no errors

### What steps will reproduce the bug?

run the lxappearance program 

### What is the expected behavior?

lxappearance should run

### System information

termux-info:

```
Application version:
0.113
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.18.120-perf-ge48a7e0 #1 SMP PREEMPT Wed Nov 4 13:03:30 CST 2020 armv8l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 6 Pro

```

**Comment by xeffyr** [comment]
Closing due to incorrectly filled bug report.

Reports containing zero information about the problem have no value as literally tell us nothing. When submitting the bug report, please attach logs.

**Comment by AspirusFromScratch** [comment]
what logs, after running lxappearance literally no logs come up

**Comment by xeffyr** [comment]
`strace` log?

`echo $DISPLAY`?

That's at least.
