### ISSUE TITLE
[Bug]: Cannot search for packages or download from F-droid

### ISSUE THREAD

**Issue by jukhamil** [termux/termux-packages#7419]
### Problem description

I downloaded Termux from the Play store and when I try to search for common packages with apt-get or pkg it says package not found.

I tried to install Termux from F-Droid but F-droid crashed and now it cannot even be re-opened.

Does anyone know why these things might be happening?

Why are there installation problems from both locations?

### Steps to reproduce the behavior.

Download Termux from Play store and try apt-get install vim.

Try to install Termux from F-droid.

### System information

* Termux application version: latest
* Android OS version: 11
* Device model: Motorola G8

**Comment by Grimler91** [comment]
termux from play store is outdated, see https://github.com/termux/termux-packages/issues/6726.

Can't reproduce any issue with F-droid, works here, if F-droid crashed then that sounds like an F-droid issue. Try removing F-droid and install again.

**Comment by agnostic-apollo** [comment]
Or download apk from site https://f-droid.org/en/packages/com.termux/
