### ISSUE TITLE
[Bug]: openssh - gpg-agent forwarding not working

### ISSUE THREAD

**Issue by gweiss76** [termux/termux-packages#7426]
### Problem description

Dear maintainer of the openssh package.
I'm using a hardware smartcard (yubikey) for ssh authentication and gpg encryption on my desktop. I want to use these capabilities in termux (by ssh'ing from my desktop to termux).

Using ssh-agent forwarding works already out of the box.
However when trying to do gpg-agent forwarding (https://wiki.gnupg.org/AgentForwarding) it fails with "Server has disabled streamlocal forwarding".

From looking into the openssh sourcecode and patches to the termux-build i suspect it to be privsep and|or the fact not running the server part as UID 0 (serverloop.c, line: 868 and below).

I have written a small patch to the openssh termux build which removes the "permission checking" section. This allows me to use gpg-agent forwarding.

I have not checked this for security or other sideeffects so please do not apply this patch without further inspection.
However it would be cool if gpg-agent forwarding could be made working in a future build of openssh for termux.

### What steps will reproduce the bug?

- Configuring ssh to do gpg-agent forwarding.
- ssh to termux
- gpg will not decrypt files (using smartcard from host)

### What is the expected behavior?

gpg in termux can use the gpg-agent on the host for crypto operations

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
openssh/stable 8.6p1 aarch64 [upgradable from: 8.6p1]
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Mon Aug 9 02:54:33 UTC 2021 armv8l Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8T
```

**Comment by gweiss76** [comment]
[serverloop.c.patch.txt](https://github.com/termux/termux-packages/files/7072502/serverloop.c.patch.txt)

**Comment by Grimler91** [comment]
Could you open a PR to add the patch for easier inspection/review? We are already disabling privsep in other places, since termux is designed for non-root and single user, so I am sure it would be fine where you need it as well

**Comment by Grimler91** [comment]
We can hopefully just remove the `(pw->pw_uid != 0 && !use_privsep)` checks, should probably keep 
```
options.allow_streamlocal_forwarding & FORWARD_REMOTE) == 0 
|| !auth_opts->permit_port_forwarding_flag 
|| options.disable_forwarding
```
