### ISSUE TITLE
Package request for customizing terminal

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#743]
Can you add an entire package to customize the colours and themes for termux?
Here are files to start with ..

[https://github.com/4679/oh-my-termux]

Maybe name it as 
Termux-customize-themes

**Comment by vishalbiswas** [comment]
There are already a wide range of themes and colours to choose from. You need to have the Termux::Styling app installed, then you can change themes and fonts by long pressing termux console.

**Comment by Auxilus** [comment]
Ok got it
