### ISSUE TITLE
Building package from a git master ..

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#744]
I have a git repository for crunch 
How do I build the custom package from it
(It has a Makefile file)

**Comment by Grimler91** [comment]
Generally, you do something along these lines:
1. git clone to your device 
2. cd to cloned directory
3. run make (or possible ./configure or ./reautoconf first)
4. Note the error and fix it
Repeat step 3 - 4 until no more errors

**Comment by fornwall** [comment]
Look at how e.g. the pforth package does it (by downloading a specific commit).
