### ISSUE TITLE
[Bug]: Runit needs a patch

### ISSUE THREAD

**Issue by suhan-paradkar** [termux/termux-packages#7453]
### Problem description

running runit produces the following
![Screenshot_2021-09-02-16-14-59-53](https://user-images.githubusercontent.com/76830230/131830890-ccc8b14c-1df8-4627-a933-61c53d2af162.jpg)

Looks like it needs to be run under process 1

Possible solutions:
* Patch to run under a different process
* Move the package to root-repo

### What steps will reproduce the bug?

```
pkg i runit
runit
```

### What is the expected behavior?

That it runs properly

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #2 SMP PREEMPT Fri Jul 2 00:39:41 CST 2021 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH2083

```

**Comment by Grimler91** [comment]
It is made for being the first process that runs after the kernel runs possible initramfs scripts and finishes mounting partitions, and runit then starts all other processes that are needed to get a working system. See http://smarden.org/runit/replaceinit.html for how it is suppose to be used. 

In termux we are not using it, we are just using runsvdir, sv and friends. I should probably remove runit from the package to not cause confusion.
