### ISSUE TITLE
[Feature]: Submit apps to the apt repo

### ISSUE THREAD

**Issue by pranshuthegamer** [termux/termux-packages#7456]
### Feature description

I want there to be a way to submit programs for the termux repository

### Additional information

thats it really.
I just wanna add godot server to the thing

**Comment by Grimler91** [comment]
Open a PR to add a build.sh script which builds the package from source. Pre-compiled packages are not accepted into the official repositories.

See https://github.com/termux/termux-packages/wiki/Creating-new-package, https://github.com/termux/termux-packages/wiki/Building-packages, https://github.com/termux/termux-packages/wiki/Build-environment for how to add and build packages
