### ISSUE TITLE
[Package]: b3sum

### ISSUE THREAD

**Issue by megapro17** [termux/termux-packages#7457]
### Package description

A command line utility for calculating BLAKE3 hashes, similar to Coreutils tools like b2sum or md5sum.

### Source code URL

https://github.com/BLAKE3-team/BLAKE3/tree/master/b3sum

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Can be installed from cargo, but it's nicer to have separate package. If nobody is interested I'll do it for myself (if I can)

**Comment by MedzikUser** [comment]
To close

**Comment by megapro17** [comment]
Lol i forgot about it, thanks
