### ISSUE TITLE
`python` should refer to python2

### ISSUE THREAD

**Issue by Julian** [termux/termux-packages#747]
It's the general upstream recommendation that `python` continue to refer to Python 2, followed by all distributions (and operating systems) pretty much other than Arch (which many consider to be a mistake). `python3`is the widely used name for that version.

Many shebangs assume as such, and despite the fact that pip will rewrite shebang lines, slightly solving the problem, many users (including me :) are generally used to typing `python` to refer to python2, and `python3` to refer to python3.

**Comment by Auxilus** [comment]
There is no way to refer py2 as Py..
You have to mention #!/bin/python2 only..

**Comment by Julian** [comment]
By "there is no way" do you mean "it is intentionally this way"?

Because the problematic lines are:

https://github.com/termux/termux-packages/blob/9760338bc23817955c554453329397ff9fffe560/packages/python2/build.sh#L60-L66

and

https://github.com/termux/termux-packages/blob/master/packages/python/build.sh#L65

termux should not be swapping around the binary names in that way.

If it's intentional for whatever reason, feel free to close out. Appreciated.

**Comment by Neo-Oli** [comment]
Note: This has already been discussed in https://github.com/termux/termux-packages/issues/295

**Comment by Julian** [comment]
Ah, thanks. I looked but didn't find that.

I'll close this, though I think @fornwall is incorrect, and speculate (with some intuition) that `python` will never refer to Python 3, the problem isn't adoption there it's just that there's no real benefit to changing a versionless name.

But it does seem intentional -- thanks for the link.
