### ISSUE TITLE
[Package]: nmcli

### ISSUE THREAD

**Issue by AbdullahBinJahed** [termux/termux-packages#7470]
### Package description

network manger as i understand

### Source code URL

https://github.com/NetworkManager/NetworkManager

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xeffyr** [comment]
1. Root package.
2. Even if used as root, it will conflict with Android OS network management subsystem.

**Comment by xeffyr** [comment]
There no practical reason of using it with Termux.

**Comment by AbdullahBinJahed** [comment]
@xeffyr also unrelated but how can i use SDL2 with C++ to draw graphics on Termux ?
[click here](https://github.com/Lzhiyong/termux-sdl/issues/6#issuecomment-912966756)
i asked him ... but he isn't responding anymore

**Comment by xeffyr** [comment]
> just there is no practical use of it ?

As already said in message [above](https://github.com/termux/termux-packages/issues/7470#issuecomment-912989471) - * it will conflict with Android OS network management subsystem*. Moreover, networking can be controlled with `/system/bin/svc`. If really need manual control - `wpa-supplicant` from root-repo will help.

Also, this is a root package and thus not suitable to be requested in https://github.com/termux/termux-packages.

> also unrelated but how can i use SDL2 with C++ to draw graphics on Termux ?

Yes, Termux packages `sdl` and `sdl2` in x11-repo. Needs X11 environment though, https://wiki.termux.com/wiki/Graphical_Environment.

> click here
i asked him ... but he isn't responding anymore

I don't know what is that and can't say whether shipped SDL packages work with this project.

SDL is 100% working with X11 output.

**Comment by AbdullahBinJahed** [comment]
@xeffyr Yeah ... i could run it ... talk about embarrassing ... hehe ... sorry for that
