### ISSUE TITLE
[Package]: libsixel

### ISSUE THREAD

**Issue by Edx09** [termux/termux-packages#7472]
### Package description

Library for displaying pictures in the terminal

### Source code URL

https://github.com/saitoha/libsixel

### Packaging policy acknowledgement

- [x] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I couldnt install it because i havent rooted my phone.
But build succeeded without errors.

**Comment by xeffyr** [comment]
Already packaged in unstable-repo.
```
pkg install unstable-repo
pkg install libsixel
```

Termux doesn't support sixel graphics output.
