### ISSUE TITLE
[Bug]: WARNING: linker: /data/data/com.termux/files/home/xmrig-master/build/xmrig: unsupported flags DT_FLAGS_1=0x8000001

### ISSUE THREAD

**Issue by AsepSarZ** [termux/termux-packages#7475]
### Problem description

![Screenshot_20210905_122020](https://user-
images.githubusercontent.com/90125367/132116629-a5c96d4d-bccb-4eec-969d-53665fb23b36.jpg)
Im not understand please help me

### What steps will reproduce the bug?

WARNING: linker: /data/data/com.termux/files/home/xmrig-master/build/xmrig: unsupported flags DT_FLAGS_1=0x8000001

### System information

termux-info:

```

```
WARNING: linker: /data/data/com.termux/files/home/xmrig-master/build/xmrig: unsupported flags DT_FLAGS_1=0x8000001

**Comment by xtkoba** [comment]
Older versions of Android do not recognize `DF_1_PIE` flag (0x08000000) in `DT_FLAGS_1`, the flag that indicates that the file is a position-independent executable (PIE). The warning message is just a warning, and there is no problem if you ignore it.

If you feel annoyed with the warning message, then you can use termux-elf-cleaner (https://github.com/termux/termux-elf-cleaner).

**Comment by buttaface** [comment]
I had to recently use termux-elf-cleaner when testing Swift executables against Android 7: use [the same steps shown there to clean your locally-built executables](https://github.com/buttaface/swift-android-sdk/blob/8c615750c1760a9467da6e553d94855503e02bd9/.github/workflows/sdks.yml#L286), if you don't want the warning.
