### ISSUE TITLE
[Package]: watchexec

### ISSUE THREAD

**Issue by notudope** [termux/termux-packages#7484]
### Package description

Executes commands in response to file modifications

### Home page URL

https://watchexec.github.io

### Source code URL

https://github.com/watchexec/watchexec

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Tested in **Redmi Note 9 Pro (Android 11)**

Successfully a installation using `cargo install watchexec-cli`. Works perfectly as screenshot below:

![Screenshot_2021-09-07-22-47-42-917_com rhmsoft edit pro](https://user-images.githubusercontent.com/87937979/132382111-35526926-28c2-48c6-be1a-ef4e0dbd11a6.jpg)

**Comment by xeffyr** [comment]
Package is now available in `packages.termux.org` repo and should be within hours on mirrors.

You can obtain it with these commands:
```
pkg install watchexec
```

**Comment by notudope** [comment]
> Package is now available in `packages.termux.org` repo and should be within hours on mirrors.
> 
> You can obtain it with these commands:
> 
> ```
> pkg install watchexec
> ```

thanks 🙏
