### ISSUE TITLE
[Package]: bk

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#7489]
### Package description

bk is a terminal EPUB reader, written in Rust.

### Source code URL

https://github.com/aeosynth/bk

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

In python there is the epy-reader but this study ( https://www.researchgate.net/publication/320436353_Energy_efficiency_across_programming_languages_how_do_energy_time_and_memory_relate ) says that python consumes a lot of energy.

**Comment by tathastu871** [comment]
Instead use pip3 install epy-reader
it is lightweight and more feature rich

**Comment by buribu** [comment]
> Instead use pip3 install epy-reader it is lightweight and more feature rich

@tathastu871 When ordering this package, the factors considered were to make it better known and save memory and energy. In the additional information you can see that the program you suggested does not meet the requirements as it depends on a virtual machine.

**Comment by tathastu871** [comment]
i have a epub and it opens well with epy-reader. But same epub fails with bk and epr-reader programs.
Hence i recommended to use epy and while using epy i haven't felt any kind of memory related lags. bk doesnt open all epubs it has lot of errors.

**Comment by buribu** [comment]
Possibly he's just less tolerant of a poorly structured epub. Here for me it works normally.

**Comment by buribu** [comment]
https://www.zdnet.com/article/python-programming-why-it-hasnt-taken-off-in-the-browser-or-mobile-according-to-its-creator/
