### ISSUE TITLE
OpenSSH: "Operation not permitted" errors when using find command

### ISSUE THREAD

**Issue by rhaglennydd** [termux/termux-packages#749]
I have sshd running in Termux and am able to ssh into it from my PC (using Windows 10's Ubuntu subsystem). For the most part everything's normal, but every time I use the "find" command I get a bunch of "Operation not permitted" errors for every matched directory, and at the end I get the message "Failed to restore initial working directory: Operation not permitted". This seems to happen no matter what directory I'm in, regardless of that directory's permissions, even if I tell it to only match files and limit the depth to 1 (preventing recursion). When I run the same commands locally from Termux I get no errors, so I don't understand what the issue is.

The home directory's permissions are 0755, and the owner and group are "u0_a74", if that matters. I don't specify a username when I execute ssh, but I've tried using u0_a74 and that doesn't make a difference. What's strange is that despite the issues with "find", I can do other things like edit files with vim or list directory contents with "ls" and there are no permissions issues. Frustrated, I turned off sshd in Termux and executed "find" locally to recursively change the permissions of every subdirectory of home (except of course .ssh) to 0777, then I turned sshd back on and reconnected from my PC. The problem is still there!

I have sshd running with maximum debug output (-ddd), but I'm not noticing any obvious errors in the output (although I confess I don't understand everything that's displayed). What exactly is "find" doing that is not permitted in SSH? To be clear, I'm not having it execute any commands with -exec, I'm just listing files. I thought the answer might be it's trying to get stat info on every file, but no, when I manually "stat" the directories that give errors I get normal output, even as an SSH user.

I might as well mention that my Termux .bash_profile automatically executes termux-chroot (the code checks the value of $HOME first to prevent an infinite loop). Seems a stretch that that would cause problems in SSH but not as a normal Termux user, but thought I'd mention it just in case.

**Comment by rhaglennydd** [comment]
Sample transcript from Ubuntu on Windows:

    [REDACTED USERNAME]@[REDACTED COMPUTER NAME]:~$ ssh -p 8022 [REDACTED SERVER IP]    
    The authenticity of host '[[REDACTED SERVER IP]]:8022 ([[REDACTED SERVER IP]]:8022)' can't be established.    
    ECDSA key fingerprint is [REDACTED].    
    Are you sure you want to continue connecting (yes/no)? yes    
    Warning: Permanently added '[[REDACTED SERVER IP]]:8022' (ECDSA) to the list of known hosts.    
    Environment:    
      USER=u0_a74    
      LOGNAME=u0_a74    
      HOME=/data/data/com.termux/files/home    
      PATH=/home/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets    
      MAIL=/var/mail/u0_a74    
      SHELL=/data/data/com.termux/files/usr/bin/bash    
      LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib    
      ANDROID_ROOT=/system    
      ANDROID_DATA=/data    
      EXTERNAL_STORAGE=/storage/emulated/legacy    
      LANG=en_US.UTF-8    
      PREFIX=/data/data/com.termux/files/usr    
      SSH_CLIENT=[REDACTED CLIENT IP] 50342 8022    
      SSH_CONNECTION=[REDACTED CLIENT IP] 50342 [REDACTED SERVER IP] 8022    
      SSH_TTY=/dev/pts/1    
      TERM=xterm    
    bash-4.4$ find . -mindepth 1 -maxdepth 1 -type f    
    find: ‘./.ssh’: Operation not permitted    
    find: ‘./storage’: Operation not permitted    
    find: ‘./.w3m’: Operation not permitted    
    ./.python_history    
    find: ‘./.config’: Operation not permitted    
    ./.bash_history    
    ./.viminfo    
    ./.bashrc    
    find: ‘./Mail’: Operation not permitted    
    find: ‘./.gnupg’: Operation not permitted    
    ./.lesshst    
    find: ‘./.weechat’: Operation not permitted    
    ./.wcalc_history    
    find: ‘./tmp’: Operation not permitted    
    ./.lynxrc    
    ./sent    
    ./postponed    
    ./.profile    
    ./.bash_profile    
    find: ‘./bin’: Operation not permitted    
    ./.selected_editor    
    ./a.out    
    find: ‘./.timewarrior’: Operation not permitted    
    ./.gitconfig    
    find: Failed to restore initial working directory: Operation not permitted    
    bash-4.4$ ll -d storage .w3m .config Mail .gnupg .weechat tmp bin .timewarrior    
    drwxrwxrwx 3 u0_a74 u0_a74 4.0K Jan 12 18:53 .config/    
    drwxrwxrwx 4 u0_a74 u0_a74 4.0K Feb  3 22:26 .gnupg/    
    drwx------ 4 u0_a74 u0_a74 4.0K Feb  5 00:45 .timewarrior/    
    drwxrwxrwx 2 u0_a74 u0_a74 4.0K Jan 14 22:25 .w3m/    
    drwxrwxrwx 5 u0_a74 u0_a74 4.0K Jan 14 22:22 .weechat/    
    drwxrwxrwx 2 u0_a74 u0_a74 4.0K Feb  3 04:06 Mail/    
    drwxrwxrwx 2 u0_a74 u0_a74 4.0K Feb  3 22:42 bin/    
    drwxrwxrwx 2 u0_a74 u0_a74 4.0K Jan 12 18:20 storage/    
    drwxr-xr-x 3 u0_a74 u0_a74 4.0K Feb  5 00:49 tmp/    
    bash-4.4$ stat storage .w3m .config Mail .gnupg .weechat tmp bin .timewarrior    
      File: storage    
      Size: 4096            Blocks: 8          IO Block: 4096   directory    
    Device: b31dh/45853d    Inode: 303484      Links: 2    
    Access: (0777/drwxrwxrwx)  Uid: (10074/  u0_a74)   Gid: (10074/  u0_a74)    
    Access: 2017-01-12 18:20:57.821695575 -0800    
    Modify: 2017-01-12 18:20:58.552408465 -0800    
    Change: 2017-02-03 23:10:56.299367815 -0800    
     Birth: -    
      File: .w3m    
      Size: 4096            Blocks: 8          IO Block: 4096   directory    
    Device: b31dh/45853d    Inode: 303317      Links: 2    
    Access: (0777/drwxrwxrwx)  Uid: (10074/  u0_a74)   Gid: (10074/  u0_a74)    
    Access: 2017-01-14 22:25:03.007738563 -0800    
    Modify: 2017-01-14 22:25:03.007738563 -0800    
    Change: 2017-02-03 23:10:56.299367815 -0800    
     Birth: -    
      File: .config    
      Size: 4096            Blocks: 8          IO Block: 4096   directory    
    Device: b31dh/45853d    Inode: 311778      Links: 3    
    Access: (0777/drwxrwxrwx)  Uid: (10074/  u0_a74)   Gid: (10074/  u0_a74)    
    Access: 2017-01-12 18:53:33.329508077 -0800    
    Modify: 2017-01-12 18:53:33.329508077 -0800    
    Change: 2017-02-03 23:10:56.299367815 -0800    
     Birth: -    
      File: Mail    
      Size: 4096            Blocks: 8          IO Block: 4096   directory    
    Device: b31dh/45853d    Inode: 311364      Links: 2    
    Access: (0777/drwxrwxrwx)  Uid: (10074/  u0_a74)   Gid: (10074/  u0_a74)    
    Access: 2017-02-03 04:06:12.373718130 -0800    
    Modify: 2017-02-03 04:06:12.373718130 -0800    
    Change: 2017-02-03 23:10:56.299367815 -0800    
     Birth: -    
      File: .gnupg    
      Size: 4096            Blocks: 8          IO Block: 4096   directory    
    Device: b31dh/45853d    Inode: 303264      Links: 4    
    Access: (0777/drwxrwxrwx)  Uid: (10074/  u0_a74)   Gid: (10074/  u0_a74)    
    Access: 2017-01-14 21:39:51.641305885 -0800    
    Modify: 2017-02-03 22:26:02.265646528 -0800    
    Change: 2017-02-03 23:10:56.299367815 -0800    
     Birth: -    
      File: .weechat    
      Size: 4096            Blocks: 8          IO Block: 4096   directory    
    Device: b31dh/45853d    Inode: 303293      Links: 5    
    Access: (0777/drwxrwxrwx)  Uid: (10074/  u0_a74)   Gid: (10074/  u0_a74)    
    Access: 2017-01-14 22:20:40.972094034 -0800    
    Modify: 2017-01-14 22:22:38.977220986 -0800    
    Change: 2017-02-03 23:10:56.309377581 -0800    
     Birth: -    
      File: tmp    
      Size: 4096            Blocks: 8          IO Block: 4096   directory    
    Device: b31dh/45853d    Inode: 319647      Links: 3    
    Access: (0755/drwxr-xr-x)  Uid: (10074/  u0_a74)   Gid: (10074/  u0_a74)    
    Access: 2017-02-05 00:48:39.339865497 -0800    
    Modify: 2017-02-05 00:49:01.091086201 -0800    
    Change: 2017-02-05 00:49:01.091086201 -0800    
     Birth: -    
      File: bin    
      Size: 4096            Blocks: 8          IO Block: 4096   directory    
    Device: b31dh/45853d    Inode: 319589      Links: 2    
    Access: (0777/drwxrwxrwx)  Uid: (10074/  u0_a74)   Gid: (10074/  u0_a74)    
    Access: 2017-02-03 22:42:41.030324983 -0800    
    Modify: 2017-02-03 22:42:55.714651155 -0800    
    Change: 2017-02-03 23:10:56.529592424 -0800    
     Birth: -    
      File: .timewarrior    
      Size: 4096            Blocks: 8          IO Block: 4096   directory    
    Device: b31dh/45853d    Inode: 319642      Links: 4    
    Access: (0700/drwx------)  Uid: (10074/  u0_a74)   Gid: (10074/  u0_a74)    
    Access: 2017-02-05 00:45:47.131857686 -0800    
    Modify: 2017-02-05 00:45:47.131857686 -0800    
    Change: 2017-02-05 00:45:47.131857686 -0800    
     Birth: -    

Corresponding Termux transcript:

    $ sshd -ddd     
    debug2: load_server_config: filename /data/data/com.termux/files/usr/etc/ssh/sshd_config     
    debug2: load_server_config: done config len = 152     
    debug2: parse_server_config: config /data/data/com.termux/files/usr/etc/ssh/sshd_config len 152    
    debug3: /data/data/com.termux/files/usr/etc/ssh/sshd_config:1 setting PasswordAuthentication no     
    debug3: /data/data/com.termux/files/usr/etc/ssh/sshd_config:2 setting UsePrivilegeSeparation no    
    debug3: /data/data/com.termux/files/usr/etc/ssh/sshd_config:3 setting PubkeyAcceptedKeyTypes +ssh-dss     
    debug3: /data/data/com.termux/files/usr/etc/ssh/sshd_config:4 setting Subsystem sftp /data/data/com.termux/files/usr/libexec/sftp-server     
    debug1: sshd version OpenSSH_7.4, OpenSSL 1.0.2k 26 Jan 2017     
    debug1: private host key #0: ssh-rsa SHA256:[REDACTED]     
    debug1: private host key #1: ssh-dss SHA256:[REDACTED]     
    debug1: private host key #2: ecdsa-sha2-nistp256 SHA256:[REDACTED]    
    debug1: private host key #3: ssh-ed25519 SHA256:[REDACTED]     
    debug1: rexec_argv[0]='/data/data/com.termux/files/usr/bin/sshd'     
    debug1: rexec_argv[1]='-ddd'     
    debug2: fd 3 setting O_NONBLOCK     
    debug3: sock_set_v6only: set socket 3 IPV6_V6ONLY     
    debug1: Bind to port 8022 on ::. Server listening on :: port 8022.     
    debug2: fd 4 setting O_NONBLOCK     
    debug1: Bind to port 8022 on 0.0.0.0.     
    Server listening on 0.0.0.0 port 8022.    
    debug3: fd 5 is not O_NONBLOCK     
    debug1: Server will not fork when running in debugging mode.    
    debug3: send_rexec_state: entering fd = 8 config len 152     
    debug3: ssh_msg_send: type 0     
    debug3: send_rexec_state: done    
    debug1: rexec start in 5 out 5 newsock 5 pipe -1 sock 8     
    debug1: inetd sockets after dupping: 5, 5 Connection from [REDACTED CLIENT IP] port 50342 on [REDACTED SERVER IP] port 8022     
    debug1: Client protocol version 2.0; client software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8     
    debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8 pat OpenSSH_6.6.1* compat 0x04000000     
    debug1: Local version string SSH-2.0-OpenSSH_7.4     
    debug1: Enabling compatibility mode for protocol 2.0     
    debug2: fd 5 setting O_NONBLOCK     
    debug3: list_hostkey_types: ssh-dss key not permitted by HostkeyAlgorithms     
    debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519     
    debug3: send packet: type 20     
    debug1: SSH2_MSG_KEXINIT sent     
    debug3: receive packet: type 20     
    debug1: SSH2_MSG_KEXINIT received     
    debug2: local server KEXINIT proposal     
    debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1     
    debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519     
    debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com     
    debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com     
    debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1     
    debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1     
    debug2: compression ctos: none,zlib@openssh.com     
    debug2: compression stoc: none,zlib@openssh.com     
    debug2: languages ctos:     
    debug2: languages stoc:     
    debug2: first_kex_follows 0     
    debug2: reserved 0     
    debug2: peer client KEXINIT proposal     
    debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1     
    debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-rsa,ssh-dss     
    debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se     
    debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se     
    debug2: MACs ctos: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96     
    debug2: MACs stoc: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96     
    debug2: compression ctos: none,zlib@openssh.com,zlib     
    debug2: compression stoc: none,zlib@openssh.com,zlib     
    debug2: languages ctos:     
    debug2: languages stoc:     
    debug2: first_kex_follows 0     
    debug2: reserved 0     
    debug1: kex: algorithm: curve25519-sha256@libssh.org     
    debug1: kex: host key algorithm: ecdsa-sha2-nistp256     
    debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none     
    debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1-etm@openssh.com compression: none     
    debug1: expecting SSH2_MSG_KEX_ECDH_INIT     
    debug3: receive packet: type 30     
    debug3: send packet: type 31     
    debug3: send packet: type 21     
    debug2: set_newkeys: mode 1     
    debug1: rekey after 4294967296 blocks     
    debug1: SSH2_MSG_NEWKEYS sent     
    debug1: expecting SSH2_MSG_NEWKEYS     
    debug3: receive packet: type 21     
    debug1: SSH2_MSG_NEWKEYS received     
    debug2: set_newkeys: mode 0     
    debug1: rekey after 4294967296 blocks     
    debug1: KEX done     
    debug3: receive packet: type 5     
    debug3: send packet: type 6     
    debug3: receive packet: type 50     
    debug1: userauth-request for user [REDACTED CLIENT USERNAME] service ssh-connection method none     
    debug1: attempt 0 failures 0     
    debug2: parse_server_config: config reprocess config len 152     
    debug2: input_userauth_request: setting up authctxt for [REDACTED CLIENT USERNAME]     
    debug2: input_userauth_request: try method none     
    Failed none for [REDACTED CLIENT USERNAME] from [REDACTED CLIENT IP] port 50342 ssh2     
    debug3: userauth_finish: failure partial=0 next methods="publickey,keyboard-interactive"     
    debug3: send packet: type 51     
    debug3: receive packet: type 50     
    debug1: userauth-request for user [REDACTED CLIENT USERNAME] service ssh-connection method publickey     
    debug1: attempt 1 failures 0     
    debug2: input_userauth_request: try method publickey     
    debug1: userauth_pubkey: test whether pkalg/pkblob are acceptable for RSA SHA256:[REDACTED]     
    debug1: temporarily_use_uid: 10074/10074 (e=10074/10074)     
    debug1: trying public key file /data/data/com.termux/files/home/.ssh/authorized_keys     
    debug1: fd 8 clearing O_NONBLOCK     
    debug1: matching key found: file /data/data/com.termux/files/home/.ssh/authorized_keys, line 1 RSA SHA256:[REDACTED]     
    debug1: restore_uid: (unprivileged)     
    debug3: send packet: type 60     
    debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa     
    Postponed publickey for [REDACTED CLIENT USERNAME] from [REDACTED CLIENT IP] port 50342 ssh2     
    debug3: receive packet: type 50     
    debug1: userauth-request for user [REDACTED CLIENT USERNAME] service ssh-connection method publickey     
    debug1: attempt 2 failures 0     
    debug2: input_userauth_request: try method publickey     
    debug3: userauth_pubkey: have signature for RSA SHA256:[REDACTED]     
    debug1: temporarily_use_uid: 10074/10074 (e=10074/10074)     
    debug1: trying public key file /data/data/com.termux/files/home/.ssh/authorized_keys     
    debug1: fd 8 clearing O_NONBLOCK     
    debug1: matching key found: file /data/data/com.termux/files/home/.ssh/authorized_keys, line 1 RSA SHA256:[REDACTED]     
    debug1: restore_uid: (unprivileged)     
    debug2: userauth_pubkey: authenticated 1 pkalg ssh-rsa     
    Accepted publickey for [REDACTED CLIENT USERNAME] from [REDACTED CLIENT IP] port 50342 ssh2: RSA SHA256:[REDACTED]     
    debug3: send packet: type 52     
    debug3: notify_hostkeys: key 0: ssh-rsa SHA256:[REDACTED]     
    debug3: notify_hostkeys: key 1: ssh-dss SHA256:[REDACTED]     
    debug3: notify_hostkeys: key 2: ecdsa-sha2-nistp256 SHA256:[REDACTED]     
    debug3: notify_hostkeys: key 3: ssh-ed25519 SHA256:[REDACTED]     
    debug3: notify_hostkeys: sent 4 hostkeys     
    debug3: send packet: type 80     
    debug1: Entering interactive session for SSH2.     
    debug2: fd 8 setting O_NONBLOCK     
    debug2: fd 9 setting O_NONBLOCK     
    debug1: server_init_dispatch     
    debug3: receive packet: type 90     
    debug1: server_input_channel_open: ctype session rchan 0 win 1048576 max 16384     
    debug1: input_session_request     
    debug1: channel 0: new [server-session]     
    debug2: session_new: allocate (allocated 0 max 10)     
    debug3: session_unused: session id 0 unused     
    debug1: session_new: session 0     
    debug1: session_open: channel 0     
    debug1: session_open: session 0: link with channel 0     
    debug1: server_input_channel_open: confirm session     
    debug3: send packet: type 91     
    debug3: receive packet: type 80     
    debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_reply 0     
    debug3: receive packet: type 98     
    debug1: server_input_channel_req: channel 0 request pty-req reply 1     
    debug1: session_by_channel: session 0 channel 0     
    debug1: session_input_channel_req: session 0 req pty-req     
    debug1: Allocating pty.     
    debug1: session_pty_req: session 0 alloc /dev/pts/1     
    debug3: send packet: type 99     
    debug3: receive packet: type 98     
    debug1: server_input_channel_req: channel 0 request env reply 0     
    debug1: session_by_channel: session 0 channel 0     
    debug1: session_input_channel_req: session 0 req env     
    debug2: Ignoring env request LANG: disallowed name     
    debug3: receive packet: type 98     
    debug1: server_input_channel_req: channel 0 request shell reply 1     
    debug1: session_by_channel: session 0 channel 0     
    debug1: session_input_channel_req: session 0 req shell     
    Starting session: shell on pts/1 for u0_a74 from [REDACTED CLIENT IP] port 50342 id 0     
    debug2: fd 5 setting TCP_NODELAY     
    debug3: ssh_packet_set_tos: set IP_TOS 0x10     
    debug2: channel 0: rfd 12 isatty     
    debug2: fd 12 setting O_NONBLOCK     
    debug3: fd 10 is O_NONBLOCK     
    debug3: send packet: type 99     
    debug1: Setting controlling tty using TIOCSCTTY.

**Comment by fornwall** [comment]
Hm, interesting, I'm not able to reproduce.

Is it only with find that you notice a problem, or with any other program as well?

**Comment by rhaglennydd** [comment]
I only see the problem with find, at least so far. But since you can't reproduce it I'm now thinking maybe the issue is that my version of OpenSSH is out of date. I'm using version 6.6, the default version that comes with Ubuntu 14.04 (the Ubuntu version that Windows 10 currently supports on its Linux subsystem). I can try upgrading it through a PPA and see if that fixes things.

**Comment by rhaglennydd** [comment]
No luck finding an Ubuntu PPA that distributes SSH 7.4 for Trusty. I would have to build it from source. In the meantime, since I also have Git Bash for Windows, I thought I'd see if I get the same problems using their SSH binary. Unfortunately, I do. Now, the SSH binary I have on Git Bash is version 7.3. Could this problem really be due to being even slightly behind Termux's version? I really doubt it's because I have Windows as I've never had this problem connecting to other (non-Termux) servers. Then again, I just looked into those servers and they're running SSH 5.3(!). Anyway, I'm going to try to compile 7.4 from source for Ubuntu on Windows and see if that fixes it.

**Comment by rhaglennydd** [comment]
So it seems the issue has been solved. I've been too busy to build the latest OpenSSH on my Ubuntu on Windows, but there was a recent update to Termux's packages that included updates to libssh and proot. The proot update has caused termux-chroot to go tits up on my device (I'll be filing an issue for that separately) so I've had to remove it from my .bash_profile. I don't know if doing that is what fixed things or if the libssh update fixed it. Sorry, I probably should have tried taking out termux-chroot to begin with to see if that would affect anything, that would have made it easier to narrow down the original source of the problem.

**Comment by rhaglennydd** [comment]
So now that proot is working on my device again, I've put termux-chroot back in my .bash_profile and the problem has returned, go figure. The good thing is I now know for certain that it's proot that causes this (or at least the way termux-chroot runs proot). Again, it only does this for the find command, and again only when I'm SSHing into Termux, not as a local Termux user. So there is some sort of conflict between proot and ssh, but I wish I knew what it was. I would hate to have to permanently remove termux-chroot from .bash_profile. It's obviously handy to have the proper Linux paths automatically setup when I launch the app, and not having them available as an SSH user is unacceptable.

**Comment by michalbednarski** [comment]
You've probably nested `termux-chroot`: you say that you've checked if `termux-chroot` was already launched by checking `$HOME`, which `sshd` replaces so `termux-chroot` is launched again.

Replace that condition with e.g.
`if ! [ -e /share ] ; then`

Nesting `proot` will degrade performance exponentially and may cause incompatibilities like in this case

**Comment by rhaglennydd** [comment]
Thank you, testing for the existence of /share instead of the value of $HOME fixed it!
