### ISSUE TITLE
[Package]: VTM

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#7490]
### Package description

Terminal multiplexer with TUI window manager and multi-party session sharing

### Home page URL

https://vtm.netxs.online/

### Source code URL

https://github.com/netxs-group/VTM

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

This is visually amazing, almost a Compiz Fusion in text mode.

**Comment by xeffyr** [comment]
Package is now available in `packages.termux.org` repository and should be within hours on mirrors.

You can obtain it with these commands:
```
pkg install vtm
```

*Package is available only for 64 bit devices currently.*
