### ISSUE TITLE
[Bug]: newsboat crashes while processing certain feed

### ISSUE THREAD

**Issue by mglh** [termux/termux-packages#7498]
### Problem description

Feed:
https://www.goingelectric.de/forum/feed/topics

Error Message:
stack corruption detected (-fstack-protector)

### What steps will reproduce the bug?

Just "reload".

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Mon May 6 16:27:58 2019 aarch64 Android
Device manufacturer:
Sony
Device model:
H4113
```

**Comment by Grimler91** [comment]
Still an issue? I was able to reproduce it, but now it works, so I guess that the issue was with one of the entries that have been removed from the feed now. I'll open an issue in the newsboat repo with backtrace and the broken .xml file in any case

**Comment by xeffyr** [comment]
Possibly related to 93f4fbb30ff8a58bb1553b5c7659a3909feaf7c5.

**Comment by Grimler91** [comment]
Looks pretty identical indeed. I suppose you removed the patch after https://github.com/newsboat/newsboat/commit/1e36d490d08010e9cbb025ed029bdbca495d7d82. 

Bash, readline and a bunch of other software makes sure [MB_LEN_MAX is at least 16](https://git.savannah.gnu.org/cgit/readline.git/tree/rlmbutil.h#n68), maybe newsboat should have a similar check (could open an issue in the newsboat repo to discuss it)

**Comment by Minoru** [comment]
Hi, Newsboat maintainer here :wave: I suspect this is fixed by https://github.com/newsboat/newsboat/pull/1747.

**Comment by Grimler91** [comment]
@Minoru Hi, yes, that commit fixes it as well (for the example feed above). Thanks for the info, I have replaced the patched used.
