### ISSUE TITLE
HELP!!!!! /usr moved

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#750]
I have renamed the /usr directory to /usr1. Now no programs are working. How to solve this problem? Thanks!!!!

**Comment by Auxilus** [comment]
Have you tried renaming it back to usr?

**Comment by Auxilus** [comment]
Make sure that the bin folder in ur usr1 is containing the shell command scripts

**Comment by Wetitpig** [comment]
no. The move command requires a library, where the library's path is set to /usr

**Comment by Wetitpig** [comment]
Solved.
