### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jjjdddrrr** [termux/termux-packages#7501]
### Problem description

In Python, the termux.UI.toast method displays a proper toast but throws a TypeError exception. However, termux-toast works normally.

  from termux import UI
  from os import system
  system('termux-toast this works')
  UI.toast('shows toast but fails')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/termux/UI.py", line 169, in toast
    return execute(f'termux-toast {options} "{text}"')['output']
TypeError: tuple indices must be integers or slices, not str

### What steps will reproduce the bug?

In Termux Python...

  from termux import UI
  UI.toast('shows toast but fails')

### What is the expected behavior?

Expect a toast (which is shown) but without throwing an exception.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.66-perf-gc8b1dc7 #1 SMP PREEMPT Wed Sep 5 12:54:25 CST 2018 aarch64 Android
Device manufacturer:
asus
Device model:
ASUS_Z012DC
```

**Comment by Grimler91** [comment]
The python bindings for termux-api is not something we have written or have control over. Report the issue to the author of the python package (I guess it is [this one](https://github.com/shajul/termux-api))
