### ISSUE TITLE
[Bug]: Backpace adds spaces for ssh session from Alacritty

### ISSUE THREAD

**Issue by DusanLesan** [termux/termux-packages#7511]
### Problem description

After I ssh into the environment run by Termux, I see backspace key adding spaces instead of removing text. The problem is only visual since the text is correct after pressing enter. I have tried this on st and Alacritty and only Alacrity is causing this problem. The [issue](https://github.com/termux/termux-packages/issues/1061) like this used to exist for termite and maybe the solution can be similar. Exporting TERM to be vt100 fixes the issue temporarily.

### What steps will reproduce the bug?

- SSH into the device running Termux
- Enter any command
- Press backspace key

### What is the expected behavior?

The backspace should do as backspace does

### System information

termux-info:

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://main.termux-mirror.ml/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.9.276-perf-gd8994453fb6b #1 SMP PREEMPT Sat Aug 7 02:41:36 UTC 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
POCO F1
```

**Comment by suhan-paradkar** [comment]
Looks like a problem with registering (im)proper keycodes, what do you think @xeffyr ??

**Comment by DusanLesan** [comment]
Well the issue was with either my shell or apk source. I was not aware of play store thing. Got it from fdroid now and it is ok. Closing the issue

**Comment by DusanLesan** [comment]
Spoke too soon. Sorry for this. It did work but stopped after exit and ssh again

**Comment by Grimler91** [comment]
Could you try running `infocmp > alacritty.terminfo` in alacritty, scp the file to termux, and then run `tic -x alacritty.terminfo` in termux? After that restart the shell and it hopefully works.

If it works, please share the alacritty.terminfo file here so that we can add it to ncurses

**Comment by xeffyr** [comment]
Compiling https://github.com/alacritty/alacritty/blob/master/extra/alacritty.info (terminfo) should be sufficient.
