### ISSUE TITLE
[Package]: linux-headers

### ISSUE THREAD

**Issue by fawtlet** [termux/termux-packages#7514]
### Package description

A package providing the Linux kernel header

I need a kernel-headers package for versions `4.14` and `4.19`

I was trying to install pynput in Termux via pip... But these include files are missing
`linux/input.h` and `linux/input-event-codes.h`

I did the same process within the proot-distro, and it worked

But I would like to do this directly from Termux without relying on proot-distro

### Home page URL

idk

### Source code URL

Idk

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xeffyr** [comment]
`ndk-sysroot` already includes Linux kernel headers.

Kernel headers from https://www.kernel.org/ won't be packaged for reasons:
1. Android devices run different kernel versions (3.x - 4.x).
2. Headers from https://www.kernel.org/ do not match the Linux kernel used on Android.

Fact that accessing Linux input character devices require root is another story...

**Comment by xeffyr** [comment]
> But these include files are missing
linux/input.h and linux/input-event-codes.h

Both are present.

![Screenshot_20210912-195125](https://user-images.githubusercontent.com/25881154/132996035-0d0bc471-3003-4369-b204-511f9c508727.png)
