### ISSUE TITLE
[Bug]: 'cpu-features.h' not found

### ISSUE THREAD

**Issue by pranshuthegamer** [termux/termux-packages#7515]
### Problem description

fatal error: 'cpu-features.h' file not found

This error is thrown when i try to compile godot server for aarch64

### Steps to reproduce the behavior.

Prerequisites:
Python 3.5+
SCons (installed with pip)
Make

Steps:
* Download Godot 3.3-stable.tar.xz from github
* extract and cd into directory
* run `scons -j8 platform=server tools=no target=release`

### What is the expected behavior?

it should compile into /bin folder.

### System information

* Termux application version: Latest as of sep 3 2021
* Android OS version: 10
* Device model: redmi y3

**Comment by xtkoba** [comment]
`cpu-features.h` could be found at <a href="https://android.googlesource.com/platform/ndk/+/refs/heads/master/sources/android/cpufeatures/cpu-features.h">ndk/sources/android/cpufeatures/cpu-features.h</a>

See also https://github.com/bazelbuild/bazel/issues/8753

**Comment by thunder-coding** [comment]
NDK seems to have deprecated `cpu-features` library, https://developer.android.com/ndk/guides/cpu-features

Closing this. Probably you also need to move to https://github.com/google/cpu_features
