### ISSUE TITLE
[Package]: wapm (at least wasm runtime)

### ISSUE THREAD

**Issue by rambip** [termux/termux-packages#7516]
### Package description

This should enable anyone to downlad easily a web-assembly binary and run it.
Idealy, the wapm packet manager is able to install a package from an official package list.
But any webassembly runtime would already be really cool.

### Home page URL

https://github.com/wasmerio/wasmer

### Source code URL

https://github.com/wasmerio/wasmer

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by truboxl** [comment]
I have made some progress...
Although wapm unlikely to happen anytime soon...
https://github.com/wasmerio/wapm-cli/issues/214

**Comment by leapofazzam123** [comment]
I've successfully compiled wasmer on Termux, might add it to termux-packages

**Comment by rambip** [comment]
I also have Nix-on-droid installed on my device.
They have a huge quantity of precompiled software on their repository, I don't know about wasmer.
If you succesfully compiled it, it would be nice to gather your efforts with the nix people !
At least publish the exact way you compiled it so that someone can write a nix expression to compile it in a deterministic way

**Comment by rambip** [comment]
https://search.nixos.org/packages?channel=21.05&show=wasmer&from=0&size=50&sort=relevance&type=packages&query=Wasmer

In fact someone already did it recently !
Look at what architectures are supported ...
