### ISSUE TITLE
[Bug]: grep can not regex Chinese characters.

### ISSUE THREAD

**Issue by zixijian** [termux/termux-packages#7517]
### Problem description

`echo 中文 | grep 中文`
there is noting happen,it shuld be print 中文.
This caused me to delete a large number of files by mistake when I used grep -v whitelist to delete files.

### Steps to reproduce the behavior.

`echo 中文 | grep 中文`

### What is the expected behavior?

Under normal Ubuntu, grep can be matched to Chinese.

### System information

* Termux application version:0.117
* Android OS version:11
* Device model:Redmi Note 9 Pro(gauguin).

**Comment by Grimler91** [comment]
Most likely same issue as in https://github.com/termux/termux-packages/issues/51711

**Comment by zixijian** [comment]
> Most likely same issue as in https://github.com/termux/termux-packages/issues/51711

404..

**Comment by Grimler91** [comment]
> > Most likely same issue as in https://github.com/termux/termux-packages/issues/51711
> 
> 404..should be #5171

Thanks. As mentioned in the issue grep works fine if compiled on device, so there has to be some configure option causing it

**Comment by zixijian** [comment]
> > > Most likely same issue as in https://github.com/termux/termux-packages/issues/51711
> > 
> > 
> > 404..should be #5171
> 
> Thanks. As mentioned in the issue grep works fine if compiled on device, so there has to be some configure option causing it

ok,I tried to compile the latest version in Termux，but  failed.
I have used the version 3.1 version in Ubuntu, and after recompilation, it can work normally.
