### ISSUE TITLE
[Bug]: node does not report a error

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#7534]
### Problem description

In termux, nodejs does not report any error such as typeerror, syntaxerror, and more so like that. 

### What steps will reproduce the bug?

* Write `console.log(a)` without doubletick in `index.js` file
* Run it with `node index.js`

### What is the expected behavior?

In termux:
![Screenshot_2021_0915_075511](https://user-images.githubusercontent.com/63401712/133353759-25aa6f2a-77cd-4cf3-a4ef-c3432ee7b9b8.png)
In proot:
![Screenshot_2021_0915_080417](https://user-images.githubusercontent.com/63401712/133353781-49bfa363-3c65-44f8-8575-f2eba4ba2030.png)

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.77+ #1 SMP PREEMPT Thu Jul 15 19:11:41 CST 2021 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1820

```

**Comment by Yonle** [comment]
Related Issues: #7531

**Comment by thunder-coding** [comment]
This can be fixed by setting `v8_android_log_stdout` to true in `tools/v8_gypfiles/toolchain.gypi`

**Comment by thunder-coding** [comment]
nodejs-lts doesn't have this issue, so for workaround for sometime till the fix gets merged, you can switch to nodejs-lts which will give you latest 14.x of nodejs 🙂

**Comment by thunder-coding** [comment]
This isn't fixed, the logs are still written to Android log instead of stdout. This should be reopened
