### ISSUE TITLE
[Bug]: installing global packages in nodejs v16.9.1 with npm in broken

### ISSUE THREAD

**Issue by ELWAER-M** [termux/termux-packages#7540]
### Problem description

can't install global packages in nodejs (v16.9.1) with npm
when i trying to do that a got errors 
i tried more than one package and i still getting errors
(this problem happened to my friend too)

![Screenshot_20210915-123012_Termux](https://user-images.githubusercontent.com/71197008/133421844-d8ba1e19-2d72-4dfd-9ac3-fd4045af04e7.jpg)
![Screenshot_20210915-121118_Termux](https://user-images.githubusercontent.com/71197008/133422995-22f1f8e5-5b99-41cd-9ee0-6bee7e0c9476.jpg)

### What steps will reproduce the bug?

in nodejs v14.17.6
![Screenshot_20210915-124721_Termux](https://user-images.githubusercontent.com/71197008/133422450-a1720b8f-5e5f-48f4-ada3-deea3b6233fa.jpg)
![Screenshot_20210915-124648_Termux](https://user-images.githubusercontent.com/71197008/133422770-f7d5817d-5f34-475d-8bb2-4bdaf085fc12.jpg)

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:                                 aarch64                                                    Subscribed repositories:
# sources.list                                             deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)                     deb https://packages.termux.org/apt/termux-games games stable                                                         # science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable                                                     Updatable packages:                                        All packages up to date                                    Android version:                                           11                                                         Kernel build information:                                  Linux localhost 4.4.177-21848546 #1 SMP PREEMPT Tue Jun 8 18:55:47 KST 2021 aarch64 Android
Device manufacturer:
samsung                                                    Device model:
SM-A205F
```

**Comment by thunder-coding** [comment]
Seems like an upstream issue https://github.com/npm/cli/issues/3645

**Comment by Yonle** [comment]
Also this issue has nothing related with `nodejs`. You may use `yarn` by installing it through `pkg`/`apt` by doing `pkg install yarn && yarn global add yarn`.

**Comment by ELWAER-M** [comment]
its workung fine in v14.17.6
but in v16.9.1 its not

**Comment by Yonle** [comment]
By the way, when you got that error, nodemon is already in your termux system.
![Screenshot_2021_0915_180707](https://user-images.githubusercontent.com/63401712/133423129-9c461f67-de4d-4615-ac8c-9fe22de69c74.png)
So this is npm issue, not nodejs.

**Comment by Yonle** [comment]
Keep in mind that the preinstalled npm at both `nodejs` and `nodejs-lts` has a big difference.

**Comment by Yonle** [comment]
Maybe reinstalling npm would solve the issue:
```sh
curl -sL https://npmjs.com/install.sh | sh
```

**Comment by ELWAER-M** [comment]
> By the way, when you got that error, nodemon is already in your termux system.
> ![Screenshot_2021_0915_180707](https://user-images.githubusercontent.com/63401712/133423129-9c461f67-de4d-4615-ac8c-9fe22de69c74.png)
> So this is npm issue, not nodejs.

(i have reinstalled termux before this) so nodemon command not installed

**Comment by ELWAER-M** [comment]
> Maybe reinstalling npm would solve the issue:
> 
> ```shell
> curl -sL https://npmjs.com/install.sh | sh
> ```

i did

i think the problem from nodejs
cuz in v14.17.6 its fine

**Comment by thunder-coding** [comment]
>i think the problem from nodejs
cuz in v14.17.6 its fine

node 14.17.6 comes with npm 6.14.15 while node 16.9.1 comes with 7.21.1

**Comment by Yonle** [comment]
Maybe doing this:
```sh
for i in $(ls -A /data/data/com.termux/files/usr/lib/node_modules/); do if [ $i != "npm" ]; then rm -rf /data/data/com.termux/files/usr/lib/node_modules/$i; fi; done
```
After npm reinstallation? Then reinstall `nodemon` ?

**Comment by thunder-coding** [comment]
> Maybe doing this:
> 
> ```shell
> for i in $(ls -A /data/data/com.termux/files/usr/lib/node_modules/); do if [ $i != "npm" ]; then rm -rf /data/data/com.termux/files/usr/lib/node_modules/$i; fi; done
> ```
> 
> After npm reinstallation? Then reinstall `nodemon` ?

This will break npm itself as npm also has a bunch of dependencies which will be removed by the command you gave

**Comment by ELWAER-M** [comment]
> Maybe doing this:
> 
> ```shell
> for i in $(ls -A /data/data/com.termux/files/usr/lib/node_modules/); do if [ $i != "npm" ]; then rm -rf /data/data/com.termux/files/usr/lib/node_modules/$i; fi; done
> ```
> 
> After npm reinstallation? Then reinstall `nodemon` ?

i removed node_modules libs but i still getting the same error

**Comment by Yonle** [comment]
Hm. This can due to upstream issue. Like what @thunder-coding suggested before, Use `yarn` for temporary time.

**Comment by Yonle** [comment]
> > Maybe doing this:
> > ```shell
> > for i in $(ls -A /data/data/com.termux/files/usr/lib/node_modules/); do if [ $i != "npm" ]; then rm -rf /data/data/com.termux/files/usr/lib/node_modules/$i; fi; done
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After npm reinstallation? Then reinstall `nodemon` ?
> 
> This will break npm itself as npm also has a bunch of dependencies which will be removed by the command you gave

You forgot to read:
```
# Delete other global package except npm
if [ $i != "npm" ]; then
```

**Comment by ELWAER-M** [comment]
i'm gonna to use `yarn` until the problem is resolved

**Comment by truboxl** [comment]
npm can be downgraded, maybe you can try that?
https://www.npmjs.com/package/npm?activeTab=versions

Example:
`npm i -g npm@latest-6`
