### ISSUE TITLE
[Bug]: openssh install fails

### ISSUE THREAD

**Issue by danintel** [termux/termux-packages#7542]
### Problem description

See transcript ....

* Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ ls
$ sftp dano@drydog.com
The program sftp is not installed. Install it by executing:
 pkg install openssh
$ pkg install openssh
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://grimler.se/termux-packages-24
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:2 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:3 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Err:4 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden
Get:5 https://grimler.se/termux-packages-24 stable InRelease [16.8 kB]
Get:6 https://grimler.se/termux-packages-24 stable/main arm Packages [264 kB]
Get:7 https://grimler.se/termux-packages-24 stable/main all Packages [20.4 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$ sftp
The program sftp is not installed. Install it by executing:
 pkg install openssh
$ lsb_release -a
No command lsb_release found, did you mean:
 Command lrelease in package qt5-tools from the x11-repo repository
$ uname -a
Linux localhost 4.14.186-22302286 #1 SMP PREEMPT Tue Aug

### What steps will reproduce the bug?

pkg install openssh # on fresh termux install 

### What is the expected behavior?

Successful install

### System information

termux-info:

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
apt/stable 2.3.9 arm [upgradable from: 1.4.10-6]
bash/stable 5.1.8 arm [upgradable from: 5.0.18-2]
ca-certificates/stable,stable 20210603 all [upgradable from: 20200722]
command-not-found/stable 1.63 arm [upgradable from: 1.57]
coreutils/stable 8.32-8 arm [upgradable from: 8.32-4]
curl/stable 7.79.0 arm [upgradable from: 7.72.0]
dash/stable 0.5.11.5 arm [upgradable from: 0.5.11.2-2]
debianutils/stable 4.11.2 arm [upgradable from: 4.11.1]
dialog/stable 1.3-20210621-0 arm [upgradable from: 1.3-20200327-0]
diffutils/stable 3.8 arm [upgradable from: 3.7-3]
dos2unix/stable 7.4.2 arm [upgradable from: 7.4.1-1]
dpkg/stable 1.20.9-5 arm [upgradable from: 1.20.5-2]
ed/stable 1.17 arm [upgradable from: 1.16-1]
findutils/stable 4.8.0 arm [upgradable from: 4.7.0-2]
game-repo/stable,stable 2.0 all [upgradable from: 1.2]
gpgv/stable 2.3.2-1 arm [upgradable from: 2.2.23]
grep/stable 3.7-1 arm [upgradable from: 3.4-1]
gzip/stable 1.11-3 arm [upgradable from: 1.10-4]
inetutils/stable 1.9.4-11 arm [upgradable from: 1.9.4-10]
less/stable 590 arm [upgradable from: 551-1]
libandroid-support/stable 28-2 arm [upgradable from: 28]
libcurl/stable 7.79.0 arm [upgradable from: 7.72.0]
libgcrypt/stable 1.9.3 arm [upgradable from: 1.8.6]
libgmp/stable 6.2.1 arm [upgradable from: 6.2.0-1]
libgpg-error/stable 1.42 arm [upgradable from: 1.39]
libnghttp2/stable 1.44.0 arm [upgradable from: 1.41.0-1]
libtirpc/stable 1.3.1 arm [upgradable from: 1.2.6-1]
lsof/stable 4.94.0 arm [upgradable from: 4.93.2]
nano/stable 5.8 arm [upgradable from: 5.2]
ncurses/stable 6.2.20200725-5 arm [upgradable from: 6.2.20200725]
net-tools/stable 2.10.0 arm [upgradable from: 1.60.2017.02.21-3]
openssl/stable 1.1.1l arm [upgradable from: 1.1.1h]
pcre/stable 8.45 arm [upgradable from: 8.44-1]
procps/stable 3.3.17-1 arm [upgradable from: 3.3.16-2]
psmisc/stable 23.4 arm [upgradable from: 23.3-2]
readline/stable 8.1.1 arm [upgradable from: 8.0.4-1]
science-repo/stable,stable 2.0 all [upgradable from: 1.1]
tar/stable 1.34 arm [upgradable from: 1.32-6]
termux-am/stable,stable 0.4 all [upgradable from: 0.3]
termux-exec/stable 1:0.9 arm [upgradable from: 0.5]
termux-keyring/stable,stable 2.3 all [upgradable from: 1.4]
termux-tools/stable,stable 0.135 all [upgradable from: 0.94]
util-linux/stable 2.37 arm [upgradable from: 2.36]
Android version:
11
Kernel build information:
Linux localhost 4.14.186-22302286 #1 SMP PREEMPT Tue Aug 10 16:19:16 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A326U
```

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/6726
