### ISSUE TITLE
[Package]: make-guile

### ISSUE THREAD

**Issue by mbakhterev** [termux/termux-packages#7552]
### Package description

GNU Make with Guile scripting support.

### Home page URL

https://www.gnu.org/software/make/

### Source code URL

https://ftp.gnu.org/gnu/make/make-4.3.tar.lz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Debian has package make-guile https://packages.debian.org/sid/make-guile. I hope this will help. It depends on more recent guile-3.0, but i have successfully built Make with guile support from source under Termux with current Guile version 2.2.7. So, i think, there should not be any problem to package it.

Thanks in advance!

**Comment by JOUKIR-999** [comment]
./install

**Comment by mbakhterev** [comment]
> ./install

Yes, of course. But it would be nice to have it prebuilt and keept updated
