### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by hassnainmughal** [termux/termux-packages#7554]
Hello
From last night until now, Thermox has been facing an error for me
Please help me
My Android version is 10 and the name of the phone is Huawei Nova 5T
![Screenshot_20210911_053937_com termux](https://user-images.githubusercontent.com/90487160/132931931-043056e3-cec1-49d5-a54b-4fb70b97fa71.jpg)

_Originally posted by @Dashing961 in https://github.com/termux/termux-packages/discussions/7509_

**Comment by xeffyr** [comment]
Do not install Termux from Google Play Store. Use F-Droid instead.

https://github.com/termux/termux-app#installation
