### ISSUE TITLE
Package request : hashcat

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#756]
Please add hashcat package..

**Comment by vishalbiswas** [comment]
hashcat requires OpenCL. Not all phones come with an OpenCL lib.
pocl looks like a good alternative.

**Comment by Auxilus** [comment]
Is it in repo?

**Comment by Auxilus** [comment]
Pick?

**Comment by Auxilus** [comment]
*pocl

**Comment by Auxilus** [comment]
@vishalbiswas Can you build hashcat?

**Comment by vishalbiswas** [comment]
I meant pocl as an opencl implementation.

**Comment by Auxilus** [comment]
Yeah I got that...Can I just `git clone` hashcat and exec by `make`? Would it work?

**Comment by vishalbiswas** [comment]
read BUILD.md from hashcat's repp and try it

**Comment by Auxilus** [comment]
Already on it...

**Comment by Auxilus** [comment]
https://github.com/termux/termux-packages/pull/1764  I had to download openCL headers manually, but eventually it works

**Comment by huitc** [comment]
Who can provide detailed teaching to me t.t

**Comment by xeffyr** [comment]
@huitc I have replied to you here: https://github.com/termux/termux-packages/pull/1764

**Comment by xeffyr** [comment]
Closed in https://github.com/termux/termux-packages/pull/1764#issuecomment-460623854.
**Works only on some devices/ROMs due to problems with OpenCL !**

**Comment by huitc** [comment]
@empt1xo wtf? \./

**Comment by huitc** [comment]
nice~! =,= @@

**Comment by huitc** [comment]
ok now thx~! (^W^)))))))))))))))))
