### ISSUE TITLE
[Bug]: Neovim latest CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by raprocks** [termux/termux-packages#7564]
### Problem description

Neovim does not run and throws an error which says
```CANNOT LINK EXECUTABLE "nvim": cannot locate symbol "uv_try_write2" referenced by "/data/data/com.termux/files/usr/lib/libluv.so"...```

### What steps will reproduce the bug?

Installing latest neovim 5.0.0-2 and running it.

### What is the expected behavior?

Neovim runs as usual

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.279-darkonah #1 SMP PREEMPT Mon Aug 9 08:00:06 UTC 2021 aarch64 Android
Device manufacturer:
asus
Device model:
Zenfone Max Pro M1
```

**Comment by keiviv** [comment]
@thunder-coding wonder how it passed the checks.

**Comment by thunder-coding** [comment]
Output of `nm -D $PREFIX/lib/libuv.so | grep uv_try_write`

```
0000000000019cdc T uv_try_write
0000000000019cd0 T uv_try_write_cb
```

The libuv.so library is missing `uv_try_write2` function

**Comment by thunder-coding** [comment]
Got it!!

The official repositories somehow didn't pick up the latest `libuv` 1.42.0 version, so the package including it's dependent packages are broken. (Probably the debs weren't uploaded somehow) Also libprotobuf needs to be rebuilt since it was again revisioned in other PR.

:)

**Comment by raprocks** [comment]
So this is an issue, right? I thought updating to android 11 broke it 😂

**Comment by Grimler91** [comment]
Hopefully fixed when build in https://github.com/termux/termux-packages/commit/53a98c76ea04098890dae6090a0c2ff6ae0b2198 finishes

**Comment by thunder-coding** [comment]
Fixed 👍.

nvim functions when updating from official repos

**Comment by raprocks** [comment]
![Screenshot_20210920-134244_Termux](https://user-images.githubusercontent.com/52972480/133973180-e99f0988-5bc6-4629-89e3-f64fe8dbb527.png)
Fixed guys! Thank you so much for the hard work you guys do!

**Comment by caoti** [comment]
Works fine also for me. Thank you very much for your fast reaction.
