### ISSUE TITLE
[Bug]: neovim: CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by masterjavaofficial** [termux/termux-packages#7569]
### Problem description

~ $ nvim
CANNOT LINK EXECUTABLE "nvim": cannot locate symbol "uv_try_write2" referenced by "/data/data/com.termux/files/usr/lib/libluv.so"...

### What steps will reproduce the bug?

```pkg install neovim -y```
```nvim hello.txt```

### What is the expected behavior?

Neovim should open successfully.

### System information

termux-info:

```
Application version:
0.117                                             Packages CPU architecture:                        arm
Subscribed repositories:                          # sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb http://packages.termux.org/apt/termux-games/ games stable                                       # science-repo (sources.list.d/science.list)      deb http://packages.termux.org/apt/termux-science/ science stable
# x11-repo (sources.list.d/x11.list)
deb http://packages.termux.org/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.193-perf-ge92ac2c #1 SMP PREEMPT Mon May 17 22:07:35 CST 2021 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 8A
```

**Comment by Grimler91** [comment]
This was reported in https://github.com/termux/termux-packages/issues/7564 and fixed in https://github.com/termux/termux-packages/commit/53a98c76ea04098890dae6090a0c2ff6ae0b2198. Updated package should be available on the mirror you are subscribed to within a few hours
