### ISSUE TITLE
Package request : dnsenum

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#757]
Please add dnsenum package..
Thanks

**Comment by fornwall** [comment]
It's a single perl script, https://github.com/fwaeytens/dnsenum/blob/master/dnsenum.pl - we try to avoid packaging these kinds of things to avoid having to maintain too many small packages.

**Comment by eleanorMarquez** [comment]
how i can install in package of dnsenum in termux cuz im not use by the normal line that's pkg dnsenum someone there can help me?
