### ISSUE TITLE
mirror.astra.in.ua for termux

### ISSUE THREAD

**Issue by ispastra** [termux/termux-packages#7574]
### Problem description

hello.
we could be your mirror on mirror.astra.in.ua
rsync://termux.astra.in.ua/termux
http://termux.astra.in.ua/
https://termux.astra.in.ua/
rsync one per 4 hours 

### What steps will reproduce the bug?

hello.
we could be your mirror on mirror.astra.in.ua
rsync://termux.astra.in.ua/termux
http://termux.astra.in.ua/
https://termux.astra.in.ua/
rsync one per 4 hours 

### System information

hello.
we could be your mirror on mirror.astra.in.ua
rsync://termux.astra.in.ua/termux
http://termux.astra.in.ua/
https://termux.astra.in.ua/
rsync one per 4 hours

**Comment by xeffyr** [comment]
Thanks, I will add this to our mirrors list.

However I noticed a one minor issue with extra files, e.g.
* https://termux.astra.in.ua/apt/termux-main/aarch64/
* https://termux.astra.in.ua/apt/termux-main/filelist

These normally shouldn't be present under http://termux.astra.in.ua/apt/termux-main.
