### ISSUE TITLE
[Package]: mupdf-static: static library of mupdf

### ISSUE THREAD

**Issue by Mark-Joy** [termux/termux-packages#7583]
### Package description

Somehow `mupdf-static` package was removed (last time I checked, it existed on Termux 1-2 months ago)
PyMuPDF needs libmupdf-third.a to compile, which is part of `mupdf-static`
Could both `mupdf` (shared lib) package and `mupdf-static` package be supported on Termux?

### Home page URL

https://mupdf.com/

### Source code URL

https://github.com/ArtifexSoftware/mupdf

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Mark-Joy** [comment]
Since version 1.18.0, mupdf no longer provides `libmupdf-third.so`. PyMuPDF seems to work fine without it. To get PyMuPDF installed successfully, just create a symlink: 
```
cd $PREFIX/lib/
ln -s libmupdf.so libmupdf-third.so 
```

**Comment by robertkirkman** [comment]
> PyMuPDF needs libmupdf-third.a to compile

Were you able to compile PyMuPDF after the inclusion of `mupdf-static`?

This issue reports that PyMuPDF is still unavailable:

- #18393
