### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by D-baj** [termux/termux-packages#7586]
### Problem description

![IMG_20210922_154926](https://user-images.githubusercontent.com/75845910/134312809-d40cfb4d-f772-4768-8d44-65dc54be1ed6.jpg)

I want to install and run the Imagemagick Package, but when I enter the Convert command an error will appear as shown in the picture

![IMG_20210922_155714](https://user-images.githubusercontent.com/75845910/134314040-31ba52d2-6bd5-4c84-a345-f6518651a993.jpg)

This is an error message found during the ImageMagick installation, and actually not only imagemagick has experienced an error like that mpd package is the same as such. 

For that I asked for help to finish it 🙏🏻🙏🏻🙏🏻

Thanks 🙏🏻

### Steps to reproduce the behavior.

Installing end runing imagemagick

### What is the expected behavior?

CANNOT LINK EXECUTABLE "convert": "/data/data/com.termux/files/usr/lib/libx265.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)

### System information

* Termux application version: 0.117
* Android OS version: 10 armv8l
* Device model: Xiaomi redmi 9c

**Comment by Grimler91** [comment]
I can reproduce it on arm, by running `gdk-pixbuf-query-loaders --update-cache` (as in the screenshot)

**Comment by D-baj** [comment]
> Is the Xiaomi redmi 9c an arm or aarch64 device? (Your output of `termux-info` can provide the answer)

![Screenshot_2021-09-22-16-26-50-782_com termux](https://user-images.githubusercontent.com/75845910/134318798-4e67019a-a215-4fb8-b952-3bfb2b4fbeaf.jpg)

**Comment by xtkoba** [comment]
Probably caused by a change in https://github.com/termux/termux-packages/commit/d165314e3d5cc2076a37bcc91b3a1277a82b2ee5 in which `-mfpu=neon` is specified for `ARM_ARGS`.

It seems that the configure arg `-DENABLE_ASSEMBLY=OFF` is needed for arm-neon as well as for i686.

**Comment by tomty89** [comment]
Actually the cause was probably due to the fact that [this](https://bitbucket.org/multicoreware/x265_git/src/f0c1022b6be121a753ff02853fbe33da71988656/source/CMakeLists.txt#lines-353) was never true because of the `ARM_ALIASES` issue I mentioned in #7561. With [this fix](https://github.com/termux/termux-packages/pull/7561/files#diff-b2d1190a9892ee2cb196282ab97dbaa40ef7694706564b06918d86bc0025c91aR9-R10) getting things "on track" again, the fact that we need `ENABLE_ASSEMBLY=OFF` for arm surfaces.

**Comment by jeevatattva** [comment]
Can a check be put in place, to look out for this warning, so as to avoid issues in future?
[/home/builder/.termux-build/_cache/android-r21d-api-24-v5/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.real: warning: shared library text segment is not shareable](https://github.com/termux/termux-packages/pull/7561/checks?check_run_id=3646916996#step:3:620) .

**Comment by Grimler91** [comment]
@jeevatattva ndk r23 changes so that this situation gives an error instead, so lets just try to speed up fixing all [build issues with ndk r23]() imo. See https://github.com/termux/termux-packages/pull/7407
