### ISSUE TITLE
git clone issue

### ISSUE THREAD

**Issue by kdlegacy** [termux/termux-packages#7600]
how do I get a git clone .....coz now I entered a git clone from nowhere.... I Waz asked username en password....entered them but the it ended error .....so any1 to help mi on this please?????

**Comment by Grimler91** [comment]
Usually means that you have entered the wrong url. Maybe you miss-spelled something.

**Comment by kdlegacy** [comment]
so how do I get the right url......this z wat exactly am requesting......

**Comment by SDRausty** [comment]
>how do I get a git clone

`git clone https://github.com/termux/termux-packages`

To get a faster and smaller clone, you can use:
`git clone --depth 1 https://github.com/termux/termux-packages --single-branch`

> Waz asked username en password

Check for typos your command.

**Comment by xeffyr** [comment]
> so how do I get the right url

You can get the right url by carefully copying it without truncating any part. Better to copy it directly from browser address line.

If you are copying the url from some tutorial, then remember that things often disappear from the Internet. Git repositories are not exception.

**Comment by kdlegacy** [comment]
but really I think am the one with the problem ......am trying to install
all pkgs ....so cud u plz send mi some ov the commands ...,..align them so
that I can follow step by step en install all pkgs
