### ISSUE TITLE
[Bug]: No finch binary in the finch package.

### ISSUE THREAD

**Issue by mdmisch** [termux/termux-packages#7601]
### Problem description

There is no `finch` binary in the `finch` package. According to what I see in #95, it was there in the past.

### What steps will reproduce the bug?

```
~ $ pkg install finch
...
~ $ finch
The program finch is not installed. Install it by executing:
 pkg install finch
~ $ dpkg-query -L finch|grep finch
/data/data/com.termux/files/usr/share/doc/finch
/data/data/com.termux/files/usr/share/doc/finch/LICENSE
```

### What is the expected behavior?

The `finch` binary should be available in the `finch` package. It should be possible to run this command from terminal.

### System information

IMO not required for this bug. I manually checked contents of https://packages.termux.org/apt/termux-main/pool/main/f/finch/finch_2.14.4_aarch64.deb, and there is no `finch` binary in the package.

**Comment by mdmisch** [comment]
The 2.14.4-1 build has the same problem.

**Comment by Grimler91** [comment]
Right, I just checked that package was not empty, my bad

**Comment by Grimler91** [comment]
Seems like finch, the program, needs [libgnt](https://keep.imfreedom.org/libgnt/libgnt)

**Comment by tathastu871** [comment]
> Seems like finch, the program, needs [libgnt](https://keep.imfreedom.org/libgnt/libgnt)

```
TERMUX_PKG_HOMEPAGE=
TERMUX_PKG_DESCRIPTION=
TERMUX_PKG_LICENSE=
TERMUX_PKG_LICENSE_FILE=
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=2.14.3
TERMUX_PKG_SRCURL=https://sourceforge.net/projects/pidgin/files/libgnt/${TERMUX_PKG_VERSION}/libgnt-${TERMUX_PKG_VERSION}.tar.xz/download
TERMUX_PKG_SHA256=57f5457f72999d0bb1a139a37f2746ec1b5a02c094f2710a339d8bcea4236123
TERMUX_PKG_DEPENDS="meson, ninja, glib, ncurses*, gtk-doc, libxml*, gobject*, python2*, xsltproc, docbook*"
termux_step_pre_configure() {
	cd ${TERMUX_PKG_SRCDIR} && sed "s|ncurses_sys_prefix = '/usr|ncurses_sys_prefix = '/data/data/com\.termux/files/usr|g" meson.build -i
}
```
meson install fails due to gtk-doc helper scripts.
There is no option to disable-docs during build
