### ISSUE TITLE
Latest proot (5.1.102) breaks termux-chroot

### ISSUE THREAD

**Issue by rhaglennydd** [termux/termux-packages#761]
Since updating to the latest proot, I can't use `termux-chroot` anymore. I just get a segfault message and no altered environment:

    proot info: vpid 1: terminated with signal 11

I am using a Samsung Galaxy S4 with Lollipop 5.01. This is what `uname -a` gives me:

     Linux localhost 3.4.0-6185444 #1 SMP PREEMPT Wed Nov 30 21:31:59 KST 2016 armv7l Android

I went so far as to uninstall and reinstall the app, but that didn't fix it.

EDIT: More detail. I'm not familiar with how proot works, but looking at the termux-chroot code I took a stab at manually running a simplified version of the proot command that the script runs:

    $ proot -b /bin:$PREFIX/bin /bin/bash -l
    proot warning: can't sanitize binding "/bin": No such file or directory
    proot error: '/bin/bash' not found (root = /, cwd = /data/data/com.termux/files/home, $PATH=(null)) 
    fatal error: see `proot --help`. 

Whoops, but that at least shows it doesn't always segfault. After figuring out that I needed to swap /bin with $PREFIX/bin, it gave me the segfault message again.

**Comment by fornwall** [comment]
@rhaglennydd Does running

    PROOT_NO_SECCOMP=1 termux-chroot

work?

**Comment by fornwall** [comment]
Ah, I can reproduce the issue on a 32-bit arm device, it may be a general problem with the updated proot package on 32-bit arm.

**Comment by fornwall** [comment]
Hm, it doesn't seem to be a problem with the proot update itself. If I build the old proot version it segfaults as well.

So, it should be something that has changed in the termux build setup? First suspect was the switch clang->gcc, but even building the old proot version with gcc causes the issue.

**Comment by fornwall** [comment]
Hm, the previous working version of proot was built 2016-08-30, some the change causing the issue has probably been made after that.

**Comment by fornwall** [comment]
Found it! The error goes away if removing `-mthumb` from CFLAGS when building, which was added rather recently on arm.

**Comment by fornwall** [comment]
@rhaglennydd This has now been fixed in version 5.1.103 of the proot package, to which you can update to with

    apt update && apt upgrade

Thanks a lot for reporting!
