### ISSUE TITLE
Ant is broken

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#7622]
Package `ant` is totally broken.

It existed before we even had `openjdk-17` package, but no idea if it even had any purpose or if anyone even tested it. I say we should look back into it now.

So basically
```
~  ant
/data/data/com.termux/files/usr/bin/ant: 41: /data/data/com.termux/files/usr/bin/ant: ANT_HOME: parameter not set
 ✘  ~  nvim $PREFIX/bin/ant
 ~  ant
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getParentFile()' on a null object reference
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:179)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
 ✘  ~ 
```

The first error is a dumb one, the script does `set -e -u`

The `-u` flag causes the program to error when an undefined shell variable is accessed, which makes no sense because those conditions check if a variable is not set in order to set it.

In the second line I invoke nvim to edit it and remove that `set -e -u` line and try again.

Now a Java error happens, no idea why but I'm gonna put the blame on dalvikvm, it's still running through dalvik, I say we should give it a try with the `openjdk-17` package now. This package will be much more useful with the openjdk package and a good alternative to gradle for some, so this should be re-packaged properly.

**Comment by ravener** [comment]
Installing through the official method, works perfectly.

**Comment by SDRausty** [comment]
>Installing through the official method, works perfectly.

This is good news;  Can you share your command history, including the build please?

**Comment by ravener** [comment]
@SDRausty no build is required, just download the archive from the official Apache Ant website, unzip it and run the bin/ant file, everything is all set.

**Comment by xeffyr** [comment]
That's all because `ant` package is built for Dalvikvm:
```
        mkdir -p $TERMUX_PREFIX/share/ant/lib

        for jar in ant ant-launcher; do
                $TERMUX_D8 \
                --classpath $ANDROID_HOME/platforms/android-$TERMUX_PKG_API_LEVEL/android.jar \
                --release \
                --min-api $TERMUX_PKG_API_LEVEL \
                --output $TERMUX_PREFIX/share/ant/lib/${jar}.jar \
                        lib/${jar}.jar
        done

        install $TERMUX_PKG_BUILDER_DIR/ant $TERMUX_PREFIX/bin/ant
        perl -p -i -e "s%\@TERMUX_PREFIX\@%${TERMUX_PREFIX}%g" $TERMUX_PREFIX/bin/ant
```

It should be built via same approach as Kotlin and other packages using OpenJDK.

**Comment by SDRausty** [comment]
Thank you for this information.
