### ISSUE TITLE
can not type git hub password in blue staks

### ISSUE THREAD

**Issue by eden14** [termux/termux-packages#7623]
### Problem description

I install bluestaks5 and root it with BSTweaker6 and install termux. I wanted to git clone some pkg that id want my github user name. I type it, but I can't type my password!!!
not in physical keyboard and not in android keyboard 

### What steps will reproduce the bug?

cannot typing password

### System information

termux-info:

```

```
latest version in googleplay

**Comment by Grimler91** [comment]
Password characters are not echoed back. Just type your password and press enter. 

(Though if github asks for your username and pw then you have probably put the wrong url)

**Comment by eden14** [comment]
I type it and enter it. But its not worked
It said: fatal...

در تاریخ پنجشنبه ۳۰ سپتامبر ۲۰۲۱،‏ ۱۱:۲۲ Henrik Grimler <
***@***.***> نوشت:

**Comment by xeffyr** [comment]
I don't think GitHub allows password authentication for external apps anymore. Try personal access token instead.
