### ISSUE TITLE
[Package]: Apktool 

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#7632]
### Package description

Provide apktool as java is released its useful for reverse engineering apk . I tried to install manually but it is un able to compile apk after decompiling it i tried with all apks
```
burt exception
```
* I used the following
 ```
apt-get update 
rm $PREFIX/bin/apktool
rm $PREFIX/bin/apktool.jar
apt install openjdk-17 -y 
apt install wget -y
wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.6.0.jar -O $PREFIX/bin/apktool.jar
chmod +r $PREFIX/bin/apktool.jar
wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O $PREFIX/bin/apktool
chmod +x $PREFIX/bin/apktool
wget https://raw.githubusercontent.com/T-Dynamos/T-Dynamos/main/bin/apktool -O $PREFIX/bin/apktool-update
```
I also fixed shebang line of apktool binary file it works it decompile but unable to compile
### Home page URL

https://github.com/iBotPeaches/Apktool

### Source code URL

https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.6.0.jar

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by rendiix** [comment]
@T-Dynamos try this [termux-apktool](https://github.com/rendiix/termux-apktool)

**Comment by T-Dynamos** [comment]
Bro how i thank to you i didn't know 

![Screenshot_2021-10-05-21-12-36-838_com termux](https://user-images.githubusercontent.com/68729523/136057170-82fabad1-6292-43b4-bf13-dda6ec6a148f.jpg)
Thanks from my core of heart

**Comment by rendiix** [comment]
> @rendiix Is it an architeture problem in the default apktool? Can you show how to build this version?

since official aoktool doesn't provide aapt/aap2 for android, you need to build aapt first then replace original aapt.

**Comment by T-Dynamos** [comment]
It works you should include in main repo

**Comment by xeffyr** [comment]
It is not included? https://packages.termux.org/apt/termux-main/pool/main/a/apktool/apktool_2.6.0_aarch64.deb

**Comment by T-Dynamos** [comment]
When you added i don't came to know 😂

**Comment by T-Dynamos** [comment]
![Screenshot_2021-12-18-21-26-22-385_com termux](https://user-images.githubusercontent.com/68729523/146647345-acc83b4a-09b8-4b7f-a7cf-760c0e4801b2.jpg)
I was just randomly checking my tools working with dependices . It just suddenly strike to my mind to try install apktool and checked this issue

**Comment by xeffyr** [comment]
> I also wanted to know that why previous versions are removed of packages we can't even downgrade python version to 3.9

Why no old versions:
* Old version of package means we will have to store old versions of all dependencies as well.
* Keeping the old versions will cause repository to grow. Keeping only the last N versions of packages will do not provide guarantee that you will be able to install specific version (like `python` v3.9). Sometimes we do rebuilds and each one counts as new package version.
* The server given to us is free and therefore is limited on resources, specifically on HDD which has size of 32 GB.

**Comment by thunder-coding** [comment]
Locking the conversation since things are going off-topic here
