### ISSUE TITLE
[Bug]: psycopg2

### ISSUE THREAD

**Issue by beastzx18** [termux/termux-packages#7639]
### Problem description

I am trying to download psycopg2 through pip version 3, but its giving me some errors, please tell me the solution if you have otherwise solve it if you don't know solution of this problem.

### What steps will reproduce the bug?

pip3 install psycopg2

it directly gives me the following error:

pg_config executable not found.

### System information

termux-info:

```
0.117
```

**Comment by xtkoba** [comment]
This is because `pg_config` is removed:

https://github.com/termux/termux-packages/blob/master/packages/postgresql/build.sh#L76

**Comment by xeffyr** [comment]
`pg_config` is present in package `postgresql`. The following command will make it available:
```
pkg install postgresql
```

***

@xtkoba `termux_step_post_massage` affects only system root inside build environment. Nothing to do with actual package data delivered to users.

**Comment by Th1ago0** [comment]
Install proot-distro, login in ubuntu, and run this code:

sudo apt-get install python3-psycopg2
