### ISSUE TITLE
mpv: CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "av_audio_fifo_peek" referenced by "libavfilter.so"... 

### ISSUE THREAD

**Issue by De4ce** [termux/termux-packages#765]
u0_a99@corsica:/ $ mpv
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "av_audio_fifo_peek" referenced by "libavfilter.so"...
1|u0_a99@corsica:/ $

**Comment by its-pointless** [comment]
its loading /vendor/lib/libavfiler.so before our ffmpeg libs which mpv was linked against.
This script fixes that http://pastebin.com/SK4AKuM1

**Comment by fornwall** [comment]
@De4ce Does updating to the latest 0.24.0-1 version of mpv with `apt update && apt upgrade` fix the issue?
