### ISSUE TITLE
GCC in Termux

### ISSUE THREAD

**Issue by a1batross** [termux/termux-packages#767]
Hi there.

Yes, I know that GCC was replaced by Clang, but is there anyone keeps backup of real GCC packages? Or any source code, from I can get working compiler at least 4.8 version and full support of Hard Float ABI.

Thanks in advance.

P.S. Sorry me, if I posted this question in wrong repository.

**Comment by its-pointless** [comment]
I guess im the guy to deal with this. 
Hard float isn't supported by android anymore so that is a minor thing. Anyway check my gcc_termux repo ... some minor script things i spent 2 minutes doing might not work. 

But if you are after ndk you can compile it yourself.

**Comment by a1batross** [comment]
@its-pointless Yay, thanks! 

I started to search it by myself, cloning a repo, creating a branch on a point of history before removing GCC.

Hard float is not removed. Even Google can't just remove an ABI, so I use just older NDKs on my PC. Works perfectly, I don't know why they think about Hard float as a "buggy, glitchy" and so on. The main rule is just to keep every binary in same ABI.

**Comment by a1batross** [comment]
Solved.
