### ISSUE TITLE
[Bug]: /root/.termux-build/libx11/src/src/Font.c:44:10: fatal error: 'sys/shm.h' file not found

### ISSUE THREAD

**Issue by zxq432** [termux/termux-packages#7671]
### Problem description

/root/.termux-build/libx11/src/src/Font.c:44:10: fatal error: 'sys/shm.h' file not found
#include <sys/shm.h>
         ^~~~~~~~~~~
1 error generated.
make[3]: *** [Makefile:1204: Font.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/root/.termux-build/libx11/build/src'
make[2]: *** [Makefile:1261: all-recursive] Error 1

### What steps will reproduce the bug?

on x86_64 gentoo cross build package qemu-system-x86-64-headless

./build-package.sh qemu-system-x86-64-headless

### What is the expected behavior?

build successfully

### System information

termux-info:

```

```

**Comment by zxq432** [comment]
patch: 
[libx11-build.sh.patch.txt](https://github.com/termux/termux-packages/files/7288894/libx11-build.sh.patch.txt)
```
--- packages/libx11/build.sh.bk	2021-10-06 03:47:05.604275342 +0800
+++ packages/libx11/build.sh	2021-10-06 03:40:10.390325650 +0800
@@ -6,7 +6,7 @@
 TERMUX_PKG_VERSION=1.7.2
 TERMUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libX11-${TERMUX_PKG_VERSION}.tar.bz2
 TERMUX_PKG_SHA256=1cfa35e37aaabbe4792e9bb690468efefbfbf6b147d9c69d6f90d13c3092ea6c
-TERMUX_PKG_DEPENDS="libandroid-support, libxcb"
+TERMUX_PKG_DEPENDS="libandroid-support, libxcb, libandroid-shmem"
 TERMUX_PKG_BUILD_DEPENDS="xorgproto, xorg-util-macros, xtrans"
 TERMUX_PKG_RECOMMENDS="xorg-xauth"
 TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--enable-malloc0returnsnull"
```

**Comment by xeffyr** [comment]
```
./build-package.sh qemu-system-x86-64-headless
```

works without the issue for me, though I will add the patch anyway. https://github.com/termux/termux-packages/commit/bbd02a56a969ca56818e86269d90e5cefbf1ed2a

Reminding that only supported build environment is `termux/package-builder` Docker image.

**Comment by zxq432** [comment]
it's a gentoo x86_64 host, not Docker image.
