### ISSUE TITLE
[Package]: box86 and box64

### ISSUE THREAD

**Issue by sukualam** [termux/termux-packages#7672]
### Package description

Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM (host system needs to be 32bit little-endian).

Box64 lets you run x86_64 Linux programs (such as games) on non-x86_64 Linux systems, like ARM (host system needs to be 64bit little-endian).

### Source code URL

https://github.com/ptitSeb

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Im noob to compile and edit things (source code,etc). So, It would be cool if someone compile it and available on termux package. Thx you.

**Comment by truboxl** [comment]
While the idea is nice,
box86 mainly cater towards users of ARM Linux system trying to run x86 Linux software (and that both are using glibc)

A theoretical (bionic C) box86 unlikely benefits
as there aren't many users of ARM Android system that want to run exceedingly rare x86 Android software

It's better to use "proot + Linux distro + box86" or just cross compile the software to ARM Android

**Comment by HoshiYamazaki** [comment]
It can be also used for Wine, and then steam and various of games, unless there is graphical acceleration.
So, the idea is still consistent.
