### ISSUE TITLE
Vim shortcut or screen gesture to enter into --INSERT-- mode in vim

### ISSUE THREAD

**Issue by GreenJoey** [termux/termux-packages#769]
Can you add screen gesture or shortcuts to enter into vim's **--INSERT--** mode. If there is already a shortcut or screen gesture then please tell that. I am new to termux

**Comment by Auxilus** [comment]
Just type `i` when you enter vim file...

**Comment by fornwall** [comment]
Right, you are going to use the keyboard to use the insert mode anyway, so just using `i` as normal should work. Let me know if you have a compelling use case why a screen gesture would be better!

**Comment by GreenJoey** [comment]
Do you mean the `:i` ???? I am new vim anyway

**Comment by vishalbiswas** [comment]
No, just press `i`. It will put you in insert mode.

**Comment by GreenJoey** [comment]
But how will I exit from the INSERT mode???

**Comment by Grimler91** [comment]
@GreenJoey google for a vim cheat sheet. These issues aren't termux related. 
See for example http://vimsheet.com

**Comment by notyoravggeek** [comment]
I got a silly solution for exiting vim from insert mode, you can use an app called Hacker's Keyboard. It provides a laptop keyboard layout. I find it useful.
