### ISSUE TITLE
[Bug]: Bochs "Bus error" in 32-bit ARM device.

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#7695]
### Problem description

**_Very important! Read carefully #7645, [https://github.com/termux/x11-packages/issues/454](https://github.com/termux/x11-packages/issues/454), [https://github.com/termux/x11-packages/issues/451](https://github.com/termux/x11-packages/issues/451), [https://github.com/termux/x11-packages/issues/448](https://github.com/termux/x11-packages/issues/448) and [https://github.com/termux/x11-packages/issues/447](https://github.com/termux/x11-packages/issues/447)!_**

**_To @xeffyr, @Grimler91 and more contributors: do not close bug report then I am deleted account. I'm not like register to online resource, and I am like deleting account in potentially unused sites._**

### What steps will reproduce the bug?

Steps in previous bug reports.

### System information

In my previous bug reports.

**Comment by xtkoba** [comment]
A bus error on 32-bit ARM Android is typically caused by an unaligned memory access, and that seems to be the case here due to an upstream discussion: https://sourceforge.net/p/bochs/discussion/39592/thread/2c606cce7d/

**Comment by xtkoba** [comment]
BTW, this issue should belong to https://github.com/termux/x11-packages/.
