### ISSUE TITLE
[Bug]: Fix ADB functionality for package 'fdroidcl' in unstable-repo

### ISSUE THREAD

**Issue by Deadpool2000** [termux/termux-packages#7702]
### Problem description

fdroidcl is not working on termux due to lack of ADB functionality.

### What steps will reproduce the bug?

To fix this issue, first we need to install 'android-tools' package by typing -

`apt install android-tools`

It will fix ADB problem and we can install any package from fdroid to our device through command-line.

![Screenshot_20211008-194709](https://user-images.githubusercontent.com/32305505/136573035-976ef084-aa6d-457d-b687-1acab446f2d0.png)

### System information

termux-info:

version - 0.101
arch - aarch64

**Comment by xeffyr** [comment]
This is not a bug and yes, if you can connect through adb in loopback mode, you can use `android-tools` package.
