### ISSUE TITLE
Core libgit2 library???

### ISSUE THREAD

**Issue by GreenJoey** [termux/termux-packages#771]
Can anyone package the libgit2 core library for Termux. It works flawlessly on Termux with just one trivial warning. I have using and will be try to provide the build.sh!!! Please help me!!

**Comment by fornwall** [comment]
A libgit2 package has now been added! Run

    apt update && apt install libgit2-dev

to install the library (including the development headers which you probably want - if you only want the shared library you can `apt install libgit2`).
