### ISSUE TITLE
[Bug]: gettext  configure.ac:25: error: AC_INIT should be called with package and version arguments

### ISSUE THREAD

**Issue by zxq432** [termux/termux-packages#7717]
### Problem description

upstream [https://savannah.gnu.org/bugs/?59929](https://savannah.gnu.org/bugs/?59929)
```
configure.ac:25: error: AC_INIT should be called with package and version arguments
gl_AM_INIT_AUTOMAKE is expanded from...
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:25: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
```

### What steps will reproduce the bug?
on gentoo x86_64 host.
./build-package.sh gettext

### System information

termux-info:

```

```

**Comment by zxq432** [comment]
patch:
[Uploading build.sh.patch.txt…]()
[Uploading use-acinit-for-libtextstyle.patch.txt…]()

**Comment by Grimler91** [comment]
gentoo is not a supported build environment. There are no issues building gettext in termux's docker image, so there is no reason to add the patches.

If you feel strongly about it and want gentoo to be supported then please collect fixes for all packages, create a setup-gentoo.sh script (similar to [setup-ubuntu.sh](https://github.com/termux/termux-packages/blob/master/scripts/setup-ubuntu.sh)), and open a single PR to add support
