### ISSUE TITLE
[Package]: no-more-secrets

### ISSUE THREAD

**Issue by NMrocks** [termux/termux-packages#7718]
### Package description

(Description copied from GitHub repo)
This project provides a command line tool called nms that recreates the famous data decryption effect seen on screen in the 1992 hacker movie Sneakers. For reference, you can see this effect at 0:35 in [this movie clip](https://www.youtube.com/watch?v=F5bAa6gFvLs&t=35).

![The program in action](https://user-images.githubusercontent.com/66912344/136684114-012fdffd-b42b-4120-894a-268efc8b2b02.gif)

This command works on piped data. Pipe any ASCII or UTF-8 text to nms, and it will apply the Hollywood effect, initially showing encrypted data, then starting a decryption sequence to reveal the original plain-text characters.

### Source code URL

https://github.com/bartobri/no-more-secrets

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I tried to compile this package on my Android 11 (LineageOS 18.1) aarch64 phone, and it compiles successfully. `make install` however, does not work (because of hard-coded directories in the makefile) and you have to manually move the executable to Termux's `/usr/bin` directory (for it to be accessible from the $PATH variable), and optionally, also move the man file to `/usr/share/man/man6`. Here is the process:
```sh
$ git clone https://github.com/bartobri/no-more-secrets  # clone the repo
Cloning into 'no-more-secrets'...
•••
Resolving deltas: 100% (598/598), done.
$ cd no-more-secrets  # cd into the project directory
$ make  # compile
•••
$ cp ./bin/nms $HOME/../usr/bin  # copy the executable to /usr/bin
$ cp ./nms.6 $HOME/../usr/share/man/man6  # copy the man file
```
After this, the program can be called by either directly running `nms` or piping the output of another program to nms, like so:
```sh
$ nms  # asks for user input
$ ls -asl | nms -a  # applies the effect to the output of the ls command
```
This progran has no dependencies except for a compiler to build it, for which you can install `clang` (`pkg install clang` to install) and `make` (`pkg install make`)

**Comment by buttaface** [comment]
Added in #7748.

**Comment by NMrocks** [comment]
Sorry for sending a second message, but after using the version on the repos it seems the binary in the repo is compiled with the ncurses option (`make nms-ncurses`) which lacks a lot of the features the OG version has. On the GitHub repo the author writes:
> Install with Ncurses Support
> If your terminal does not support ANSI/VT100 escape sequences, the effect may not render properly. This project provides a ncurses implementation for such cases.

But Termux does support ANSI escapes

Here is what the original version looks like: https://imgur.com/a/cNQpiHO

Here is what the ncurses version on the repo looks like: https://imgur.com/a/YQwJkHq

**Comment by buttaface** [comment]
Alright, if you want to modify the package to not use ncurses, submit a patch.
