### ISSUE TITLE
[Package]: wxWidgets

### ISSUE THREAD

**Issue by nisheri-ascar** [termux/termux-packages#7729]
### Package description

wxWidgets is a cross-platform C++ GUI library that is required by several programs to get working

### Home page URL

https://www.wxwidgets.org/

### Source code URL

https://github.com/wxWidgets/wxWidgets/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by tathastu871** [comment]
wxwidgets is available to use on proot distros in termux. then it must run directly on termux too.

**Comment by xtkoba** [comment]
This is a blocker of aMule packaging (#8063; closed too early I suppose.)

There are several attempts to build wxWidgets on Termux: termux/x11-packages#39, termux/x11-packages#112 and termux/x11-packages#408. Notably there seems to be at least <a href="https://github.com/termux/x11-packages/issues/408#issuecomment-894480913">one succeessful attempt</a>.

It is true that there is sometimes a significant gap between on-device building and cross building. But I believe it is worth trying to do it.
