### ISSUE TITLE
Compile error tinc vpn

### ISSUE THREAD

**Issue by perry-amsterdam** [termux/termux-packages#773]
Hi,

I am trying to compile tinc vpn software.

My build.sh is :

 ~/termux-packages-master/packages/tinc $ cat build.sh 
TERMUX_PKG_HOMEPAGE=http://tinc-vpn.org/
TERMUX_PKG_DESCRIPTION="tinc is a Virtual Private Network (VPN) daemon that uses tunnelling and encryption to create a secure private network between hosts on the Internet."
TERMUX_PKG_DEPENDS="liblzo, libandroid-support"
#TERMUX_PKG_CONFLICTS=""
TERMUX_PKG_VERSION=1.1pre14
TERMUX_PKG_SRCURL=http://tinc-vpn.org/packages/tinc-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=e349e78f0e0d10899b8ab51c285bdb96c5ee322e847dfcf6ac9e21036286221f
TERMUX_PKG_FOLDERNAME=tinc-${TERMUX_PKG_VERSION}
TERMUX_PKG_EXTRA_CONFIGURE_ARGS=""

termux_step_pre_configure() {
        LDFLAGS+=" -llog -landroid"
}

But i get de the following error:

  CC       openssl/rsa.o
  CCLD     sptps_keypair
  CCLD     sptps_test
  CCLD     sptps_speed
/home/perry/.termux-build/_lib/toolchain-aarch64-ndk13-api21-v10/bin/aarch64-linux-android-ld: error: cannot find -lrt
clang38: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:795: recipe for target 'sptps_speed' failed
make[2]: *** [sptps_speed] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/perry/.termux-build/tinc/build/src'
Makefile:376: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/perry/.termux-build/tinc/build'
Makefile:317: recipe for target 'all' failed
make: *** [all] Error 2

I neede some help ?

Greetings from Amsterdam, Perry

**Comment by fornwall** [comment]
Android does not have a separate librt, it's built into libc.

So you need to patch the project to to remove the `-lrt` from it's Makefile.

**Comment by fornwall** [comment]
@perry-amsterdam You're welcome to join https://gitter.im/termux/termux to discuss and get more help!
