### ISSUE TITLE
[Package]: VirglRenderer

### ISSUE THREAD

**Issue by Quackdoc** [termux/termux-packages#7744]
### Package description

Could we get virglrenderer with experimental vulkan support? using vtest + shared /tmp we would be able to get gles support in a proot environment. and if gpu supports it, even vulkan support.

### Source code URL

https://gitlab.freedesktop.org/virgl/virglrenderer

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by tathastu871** [comment]
Requires libudev. Not possible without systemd
