### ISSUE TITLE
[Bug]: dog can't run

### ISSUE THREAD

**Issue by GitHubNeko** [termux/termux-packages#7745]
### Problem description

Cannot run with the **dog** command

### What steps will reproduce the bug?

apt install dog
dog MX google.com

### What is the expected behavior?

thread 'main' panicked at 'Failed to get nameserver: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/requests.rs:88:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    17223 abort      dog MX google.com

### System information

Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
git/stable 2.33.1 aarch64 [upgradable from: 2.33.0-1]
Android version:
9
Kernel build information:
Linux localhost 4.9.148 #1 SMP PREEMPT Thu Apr 15 06:23:15 CST 2021 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
VTR-AL00

**Comment by xeffyr** [comment]
Should be fixed in `0.1.0-1` which is available on packages.termux.org and soon will be on mirrors.

**Comment by GitHubNeko** [comment]
There is still a little mistake

thread 'main' panicked at 'Invalid HTTPS nameserver', dns-transport/src/https.rs:55:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    13041 segmentation fault  dog -H google.com
