### ISSUE TITLE
How to get intltool(0.35+) in termux？

### ISSUE THREAD

**Issue by urain39** [termux/termux-packages#776]
i want to build a tool need intltool >= 0.35

**Comment by its-pointless** [comment]
You need to use perl and cpan. upgrade using `cpan -u` first then cpan install XML::Parser. Then download intltool src. I had to edit configure so it so it detected XML:Paser. 
./configure --prefix=/data/data/com.termux/files/usr 
Etc etc 
still not entirely clean
