### ISSUE TITLE
[Bug]: Running PHP pages hangs until Termux gets focus

### ISSUE THREAD

**Issue by juppwerner** [termux/termux-packages#7761]
### Problem description

I installed Apache and PHP (8).
I can start apache and run some php pages.
When a new page is opened, the progress bar in the local browser hangs until the termux app gets focus again.
Then going back to the browser, the page continues to load.

This behavior is the same when running a PHP app with the PHP standalone webserver (php -S 0.0.0.0:8080).

### What steps will reproduce the bug?

Install php-apache
Configure Apache to run PHP scripts
Start apache: apachectl start

### What is the expected behavior?

All PHP pages in a local browser should run without pausing the page loading

### System information

termux-info:

```
Application version:
unsupported

Updatable packages:
All packages up to date
Android version:
10

Kernel build information:
Linux 4.14.116
Device manufacturer:
HUAWEI
Device model:
JSN-L21
```

**Comment by johnmcgary** [comment]
Cuento con el mismo error en el moto g8 power. configure los módulos de Apache instale MariaDB y php en su version 8 De ahi todo parece normal hasta que habro el navegador en localhost:8080 y la pagina se mantiene en blanco y no carga 
y si ejecuto phpmyadmin en 0.0.0.0:4444 si me carga.
Nose a que de se deba el error  en la pc me funciona bien 
Estoy seguro que muchos usuarios van a tener ese error 
Puede que se deba al php.ini ya que no exite y ay que configurarlo pero no estoy seguro
