### ISSUE TITLE
[Bug]: Can't use tlmgr from texlive

### ISSUE THREAD

**Issue by YijunYuan** [termux/termux-packages#7775]
### Problem description

The TexLive is installed by `apt install texlive-full`
```
~ $ tlmgr
The program tlmgr is not installed. Install it by executing:
 pkg install texlive-bin
~ $ whereis tlmgr
tlmgr: /data/data/com.termux/files/usr/bin/texlive/tlmgr
~ $ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/data/data/com.termux/files/usr/bin/texlive
~ $
```
Even if I `cd` into the folder `/data/data/com.termux/files/usr/bin/texlive` and run `.\tlmgr`, it shows that
```
bash: ./tlmgr: No such file or directory
```

`texlinks` doesn't help.

### What steps will reproduce the bug?

As described above.

### System information

Termux version: latest.
Android version: 11.

**Comment by SDRausty** [comment]
@Grimler91 I was having difficulty installing Texlive too.  As far as I can tell, `tlmgr` issues are laiden upstream as well. Hence I recently created [\_ADDtlmgrinstaller_](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L1653).  Installing Arch Linux in Termux PRoot is not required to use it.   The command `setupTermuxArch bloom` will deposit `tlmgrinstaller` as a `tlmgr` bash script on device.

I have been testing this script extensively, and it seems to work just as well over the Intranet as well as the Internet.  Thank you for receeding my ban at Github.  Can you receed my ban Termuxwide please?  Including Gitter dev?

**Comment by Grimler91** [comment]
Termux already has the `texlive-installer` package, sounds like your script serves the same purpose

**Comment by SDRausty** [comment]
>already has the `texlive-installer` package, 

Yes, and so does Arch Linux.  I was not able to easily install Tex using any of the packaged methods, including ctan's unix installer, hence `tlmgrinstaller` was made:
![Screenshot_20220220-193956](https://user-images.githubusercontent.com/27742457/154872232-35d10dec-33e2-49ae-9554-b38dabb1fad7.png)


There is a `infrastructure-only scheme (no TeX at all)` option which only installs 7MB that was very helpfull for testing.
