### ISSUE TITLE
[Bug]: add gnustep for objc backend in nim

### ISSUE THREAD

**Issue by antonl05** [termux/termux-packages#7779]
### Problem description

the nim compiler supports the objective-c backend, but its linker dependencies (gnustep-base) isnt included.
adding gnustep-base into list of dependencies would be helpful for objective c backend

### What steps will reproduce the bug?

linker fails when trying to compile using the objectivec backend, it wont link until gnustep-base is installed

### What is the expected behavior?

gnustep-base needs to be installed for objectivec to work correctly

### System information

logically applies to all termux version

**Comment by xtkoba** [comment]
I wonder if this is virtually a package request.

**Comment by antonl05** [comment]
> I wonder if this is virtually a package request.

We just need to add gnustep into nims package dependencies.
Gnustep aldready exists

**Comment by xtkoba** [comment]
I cannot find one. What is it named?
