### ISSUE TITLE
[Bug]: neovim v0.5.1 not supper python3.10

### ISSUE THREAD

**Issue by zhlmnet** [termux/termux-packages#7780]
### Problem description

0 ## Python 3 provider (optional)
 21   - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
 22   - ERROR: Python provider error:
 23     - ADVICE:
 24     ¦ - provider/pythonx: Could not load Python 3:
 25     ¦   ¦ /data/data/com.termux/files/usr/bin/python3 is Python 3.10 and cannot provide Python >= 3.3.
 26     ¦   ¦ /data/data/com.termux/files/usr/bin/python3.10 is Python 3.10 and cannot provide Python >= 3.3.
 27     ¦   ¦ python3.9 not found in search path or not executable.
 28     ¦   ¦ python3.8 not found in search path or not executable.
 29     ¦   ¦ python3.7 not found in search path or not executable.
 30     ¦   ¦ python3.6 not found in search path or not executable.
 31     ¦   ¦ /data/data/com.termux/files/usr/bin/python is Python 3.10 and cannot provide Python >= 3.3.
 32   - INFO: Executable: Not found

### What steps will reproduce the bug?

new install termux 
pkg install python neovim
pip install neovim
open nvim to input :checkhealth provider

### System information

termux-info:

```

```Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.113-perf-g8a4d27132867 #1 SMP PREEMPT Thu Aug 12 01:56:07 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2105K81AC

**Comment by xtkoba** [comment]
Should be already fixed by https://github.com/termux/termux-packages/commit/f0cad6edc66490a12a8717a111c932ef144ad166 (update to 0.6.0).

**Comment by NoobDecompiler** [comment]
I need python3.10.1 .deb file.please help me
