### ISSUE TITLE
[Bug]: WARNING: linker: Warning: "/data/data/com.termux/files/usr/lib/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#7789]
### Problem description

When I execute pkg upgrade -y, an error occurs with apt

### What steps will reproduce the bug?

pkg upgrade -y && apt

### What is the expected behavior?

WARNING: linker: Warning: "/data/data/com.termux/files/usr/lib/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)

### System information

Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.148 #1 SMP PREEMPT Sat Sep 25 12:11:21 CST 2021 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
VTR-AL00

**Comment by agnostic-apollo** [comment]
Known issue, will be fixed as updates roll out in coming days. People should avoid updating packages for next few days until ndk upgrade is complete, or expect issues if you do.

https://github.com/termux/termux-packages/pull/7339#issuecomment-948966194

**Comment by NoNameMan1231** [comment]
Yes .. same thing happened to me!

**Comment by PUTONA7040300** [comment]
[Go](https://stackexchange.com/users/29248699?tab=inbox)

**Comment by PUTONA7040300** [comment]
Warning: Undefined array key 16 in /data/data/com.termux/files/home/Card-Number/CMQyGnfN on line 44
