### ISSUE TITLE
Frotz should depend on curl?

### ISSUE THREAD

**Issue by Quasic** [termux/termux-packages#779]
The zgames script for frotz uses curl to fetch games. I tried wget, which works for some of them, but doesn't do https. I don't know if this means frotz should depend on curl, or if the script should check for curl, but thought I'd ask.

**Comment by Quasic** [comment]
wget fails if redirected to https, such as with Adventure, and gets a 403 on Zork II and III. I tried catching these and echoing a message to apt install curl to download this game, but for all I know, there are other problems with wget. There is a message that curl is not found, which isn't hard to figure out, and curl isn't huge, so maybe it's fine as is.

**Comment by ElTopo** [comment]
wget from busybox is not compiled with ssl so it does not support https.

however, you can install the real wget package (apt install wget), it does support https.

**Comment by Quasic** [comment]
Installing curl seemed the best option for me. I was just wondering if the package could be improved, but it's not a priority. Thanks!

**Comment by fornwall** [comment]
@Quasic Thanks, this is now fixed in the latest 2.44-1 version of the frotz package!

Let me know if you have some other games that could be added to the list in zgames so that people can easily try them out!
