### ISSUE TITLE
[Bug]: WARNING: linker: Warning: "/data/data/com.termux/files/usr/lib/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#7815]
### Problem description

This error `WARNING: linker: Warning: "/data/data/com.termux/files/usr/lib/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)` appeared after upgrading today.

### What steps will reproduce the bug?

Install [TermuxArch](https://github.com/TermuxArch/TermuxArch) with QEMU support; `setupTermuxArch qemu`.

### What is the expected behavior?

This error in not present: `WARNING: linker: Warning: "/data/data/com.termux/files/usr/lib/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)`

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf+ #1 SMP PREEMPT Fri Jul 30 02:50:38 CDT 2021 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g stylus
```

**Comment by PUTONA7040300** [comment]
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf+ #1 SMP PREEMPT Fri Jul 30 02:50:38 CDT 2021 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g stylus
