### ISSUE TITLE
Mpv: [ao/opensles] Failed to Enqueue: 7

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#783]
mpv frequenty prints this warning (`[ao/opensles] Failed to Enqueue: 7`), especially when skipping around. 
mpv otherwise seems to be working for me.

### Workaround
`mpv --msg-level=ao=fatal`
This will suppress errors in the `ao`-module

**Comment by its-pointless** [comment]
that is annoying but it doesn't happen using openal nearly as much. Its largely a product of androids high latency and in general annoying  audio.

**Comment by Neo-Oli** [comment]
@tomty89 cool.
