### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'symbol'

### ISSUE THREAD

**Issue by lyonkvalid** [termux/termux-packages#7832]
### Problem description

I'm trying to install Pillow using Python3 on termux , I'm getting this error installing cryptography using pip3 tooo.

`python -m pip install Pillow
Collecting Pillow
  Using cached Pillow-8.4.0.tar.gz (49.4 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /data/data/com.termux/files/usr/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-lefrl14u/pillow_22c02c64e9e84fd5810f7a95a933800c/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-lefrl14u/pillow_22c02c64e9e84fd5810f7a95a933800c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-pyx5vgss
       cwd: /data/data/com.termux/files/usr/tmp/pip-install-lefrl14u/pillow_22c02c64e9e84fd5810f7a95a933800c/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 12, in <module>
      from setuptools.extension import Extension
    File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/extension.py", line 7, in <module>
      from setuptools.dist import _get_unpatched
    File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/dist.py", line 16, in <module>
      import pkg_resources
    File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pkg_resources.py", line 29, in <module>
      import symbol
  ModuleNotFoundError: No module named 'symbol'`

### What steps will reproduce the bug?

pip install cryptography, pip install Pillow , pip install diffi

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.190+ #2 SMP PREEMPT Wed Dec 23 13:18:42 CST 2020 armv7l Android
Device manufacturer:
TECNO MOBILE LIMITED
Device model:
TECNO KC8

```

**Comment by yeyuchen198** [comment]
I get the same problem when I try to "pip install channels", because channels depends on cryptography, and cryptography seems need rust!
so I do the next is following:
pkg update
pkg upgrade
pkg install rust
pip install channels

Finally get success, my Termux App version is 0.117, Python version is 3.10, Android version is 10.0
![Screenshot_20211121_222501](https://user-images.githubusercontent.com/89305403/142766196-2ef394b9-333e-4770-af25-5543acaf8972.jpg)

**Comment by fran6120** [comment]
> `Collecting cryptography Using cached cryptography-35.0.0.tar.gz (559 kB) Installing build dependencies ... error ERROR: Command errored out with exit status 1: command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/tmp/pip-standalone-pip-4v4wtgn6/**env_pip**.zip/pip install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-wmzw44rw/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' cwd: None Complete output (74 lines): Collecting setuptools>=40.6.0 Using cached setuptools-58.3.0-py3-none-any.whl (946 kB) Collecting wheel Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB) Collecting cffi>=1.12 Using cached cffi-1.15.0.tar.gz (484 kB) Preparing metadata (setup.py): started Preparing metadata (setup.py): finished with status 'done' Collecting setuptools-rust>=0.11.4 Downloading setuptools_rust-0.12.1-py3-none-any.whl (22 kB) Collecting pycparser Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB) Collecting semantic-version>=2.6.0 Downloading semantic_version-2.8.5-py2.py3-none-any.whl (15 kB) Collecting toml>=0.9.0 Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB) Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed. Installing collected packages: toml, setuptools, semantic-version, pycparser, wheel, setuptools-rust, cffi Running setup.py install for cffi: started Running setup.py install for cffi: finished with status 'error' ERROR: Command errored out with exit status 1: command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-gochg9jj/cffi_27442ba7062e43c3b5a59b89603b0707/setup.py'"'"'; **file**='"'"'/data/data/com.termux/files/usr/tmp/pip-install-gochg9jj/cffi_27442ba7062e43c3b5a59b89603b0707/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-d9y0yg30/install-record.txt --single-version-externally-managed --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-wmzw44rw/overlay --compile --install-headers /data/data/com.termux/files/usr/tmp/pip-build-env-wmzw44rw/overlay/include/python3.10/cffi cwd: /data/data/com.termux/files/usr/tmp/pip-install-gochg9jj/cffi_27442ba7062e43c3b5a59b89603b0707/ Complete output (48 lines): /data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: cannot find -lgcc /data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: cannot find -lgcc clang-12: error: linker command failed with exit code 1 (use -v to see invocation) Note: will not use '__sync_synchronize()' in the C code ***** The above error message can be safely ignored.
> 
> ```
>   running install
>   running build
>   running build_py
>   creating build
>   creating build/lib.linux-armv7l-3.10
>   creating build/lib.linux-armv7l-3.10/cffi
>   copying cffi/__init__.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/api.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/commontypes.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/cparser.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/error.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/lock.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/model.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/pkgconfig.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/recompiler.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/verifier.py -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/_embedding.h -> build/lib.linux-armv7l-3.10/cffi
>   copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.10/cffi
>   running build_ext
>   building '_cffi_backend' extension
>   creating build/temp.linux-armv7l-3.10
>   creating build/temp.linux-armv7l-3.10/c
>   arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -DUSE__THREAD -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/python3.10 -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.10/c/_cffi_backend.o
>   In file included from c/_cffi_backend.c:7939:
>   In file included from c/cffi1_module.c:20:
>   c/call_python.c:211:5: warning: "no definition for read_barrier(), missing synchronization for multi-thread initialization in embedded mode" [-W#warnings]
>   #   warning "no definition for read_barrier(), missing synchronization for\
>       ^
>   1 warning generated.
>   arm-linux-androideabi-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -landroid-support -L/home/builder/.termux-build/_cache/android-r23b-api-24-v1/sysroot/usr/lib -march=armv7-a -Wl,--fix-cortex-a8 -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -landroid-support -L/home/builder/.termux-build/_cache/android-r23b-api-24-v1/sysroot/usr/lib build/temp.linux-armv7l-3.10/c/_cffi_backend.o -L/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr/lib -lffi -lpython3.10 -o build/lib.linux-armv7l-3.10/_cffi_backend.cpython-310.so
>   /data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: cannot find -lgcc
>   /data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: cannot find -lgcc
>   clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
>   error: command '/data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1
>   ----------------------------------------
> ```
> 
> ## ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-gochg9jj/cffi_27442ba7062e43c3b5a59b89603b0707/setup.py'"'"'; **file**='"'"'/data/data/com.termux/files/usr/tmp/pip-install-gochg9jj/cffi_27442ba7062e43c3b5a59b89603b0707/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-d9y0yg30/install-record.txt --single-version-externally-managed --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-wmzw44rw/overlay --compile --install-headers /data/data/com.termux/files/usr/tmp/pip-build-env-wmzw44rw/overlay/include/python3.10/cffi Check the logs for full command output.
> WARNING: Discarding https://files.pythonhosted.org/packages/10/91/90b8d4cd611ac2aa526290ae4b4285aa5ea57ee191c63c2f3d04170d7683/cryptography-35.0.0.tar.gz#sha256=9933f28f70d0517686bd7de36166dda42094eac49415459d9bdf5e7df3e0086d (from https://pypi.org/simple/cryptography/) (requires-python:>=3.6). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/tmp/pip-standalone-pip-4v4wtgn6/**env_pip**.zip/pip install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-wmzw44rw/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.`
> 
> Getting this error after doing what you recommended



I get the same issue trying to install cryptography==35.0.0 with `error: Don't know the correct rust target for system type arm-unknown-linux-androideabi. Please set the CARGO_BUILD_TARGET environment variable.`

with `export CARGO_BUILD_TARGET=armv7-linux-androideabi` i get ` error: cargo failed with code: 101`

all packages are up to date:

 ```
~ $ pkg install libllvm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libllvm is already the newest version (13.0.0-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

finally, could you install it?

i think so it only fails on armv7l arch

**Comment by xtkoba** [comment]
No response from author for 4 months. Closing.

**Comment by Paradox0100** [comment]
this works for linux go to https://pypi.org/ and download the package you want, unzip it. Go to the directory for the unziped package containing setup.py and run 'sudo python3 setup.py install'
