### ISSUE TITLE
[Bug]: Security - unofficial mirror url loading in Google Play version

### ISSUE THREAD

**Issue by wbrinksma** [termux/termux-packages#7834]
### Problem description

This is my first post in a repository's issues section. If I did something wrong or there is room for improvement, please let me know.

I am unsure if this report valid for this platform, but I wanted to address this issue here because I feel it has potential to lead to problems in the future. I have not used Termux for quite a while, but always loved the project and today came back to it. I unwittingly installed it from Google Play (I did not read the description) and quickly ran into errors. This is not the problem I want to address however, because after reading up on the situation, I noticed some changes in the official mirrors. What alarmed me was that _https://main.termux-mirror.ml_ was not official anymore, yet my output of _pkg upgrade_ listed it as _ok_. The danger lies in the fact that the Google Play version of Termux seemingly accepts information from an untrusted web server somewhere.

This situation threw me on a little tangent to figure out how the mirror could be listed as _ok_. It seems _termux-mirror.ml_ was bought up by a company which aggregates popular domain names and sells them. The reason the code that checks for valid mirrors marks this one as _ok_ is because when it is checking, the _--location_ flag makes it accept a redirect to a page which advertises the fact the domain is for sale. This page gives status code 200, so according to the checker, all is well. This could provide a nice attack vector in the future, because the version of included programs such as _curl_ will become more and more out of date. If a flaw is found in the way it handles HEAD requests, the Termux application in the Play Store is at serious risk, especially because every new install of the Google Play version will at some point connect to the old mirror address.

In contrast, the availability checker does figure out nicely that Bintray is not valid anymore, although the fact that the Bintray repository is not valid - but still included - could also be seen as the same issue as described above, albeit a less impactful one for now.

(As a side note, the IP _termux_mirror.ml_ points to has been reported in the last few months for malicious activity. This might not be that alarming because it looks like the IP belongs to a server which hosts a very large number of sites, but it still felt worth mentioning.)

### What steps will reproduce the bug?

For new users, running ```$ pkg upgrade``` reproduces this behavior.

### What is the expected behavior?

I feel the application in the Play Store should not include these mirrors, because they are not officially controlled anymore. I am not sure if remedying this is possible however, because of the Android 10 problems. I read in the deprecation notice that the Google Play version would at some point be removed. I feel that might be the best solution to prevent problems in the future, however it is currently still up. Is there a roadmap of the phase out and is it happening soon?

### System information

I uninstalled the app already because of the reason mentioned above, but it is the old Google Play version.

**Comment by thunder-coding** [comment]
Mistakenly unpinned, sorry

**Comment by xtkoba** [comment]
This is a pinned issue.

**Comment by Alejandro0019** [comment]
> ### Descripción del problema
> Esta es mi primera publicación en la sección de problemas de un repositorio. Si hice algo mal o hay margen de mejora, házmelo saber.
> 
> No estoy seguro de si este informe es válido para esta plataforma, pero quería abordar este problema aquí porque siento que tiene el potencial de generar problemas en el futuro. No he usado Termux durante bastante tiempo, pero siempre me encantó el proyecto y hoy volví a él. Sin saberlo, lo instalé desde Google Play (no leí la descripción) y rápidamente me encontré con errores. Sin embargo, este no es el problema que quiero abordar, porque después de leer sobre la situación, noté algunos cambios en los espejos oficiales. Lo que me alarmó fue que _https://main.termux-mirror.ml_ ya no era oficial, pero mi resultado de la _actualización de pkg_ lo enumeró como _correcto_ . El peligro radica en el hecho de que la versión Google Play de Termux aparentemente acepta información de un servidor web que no es de confianza en alguna parte.
> 
> Esta situación me llevó por la tangente para descubrir cómo el espejo podría aparecer como _correcto_ . Parece _que termux-mirror.ml_ fue comprado por una empresa que agrega nombres de dominio populares y los vende. La razón por la que el código que busca espejos válidos marca este como _correcto_ es porque cuando está verificando, el indicador de _ubicación_ hace que acepte una redirección a una página que anuncia el hecho de que el dominio está a la venta. Esta página da el código de estado 200, por lo que según el verificador, todo está bien. Esto podría proporcionar un buen vector de ataque en el futuro, porque la versión de programas incluidos como _curl_quedará cada vez más desfasado. Si se encuentra una falla en la forma en que maneja las solicitudes de HEAD, la aplicación Termux en Play Store corre un grave riesgo, especialmente porque cada nueva instalación de la versión de Google Play en algún momento se conectará a la antigua dirección espejo.
> 
> Por el contrario, el verificador de disponibilidad se da cuenta de que Bintray ya no es válido, aunque el hecho de que el repositorio de Bintray no sea válido, pero aún esté incluido, también podría verse como el mismo problema que se describe anteriormente, aunque menos impactante para ahora.
> 
> (Como nota al margen, la IP a la que apunta _termux_mirror.ml_ ha sido reportada en los últimos meses por actividad maliciosa. Esto podría no ser tan alarmante porque parece que la IP pertenece a un servidor que aloja una gran cantidad de sitios, pero aún así se sintió digno de mencionar.)
> 
> ### ¿Qué pasos reproducirán el error?
> Para los nuevos usuarios, la ejecución `$ pkg upgrade`reproduce este comportamiento.
> 
> ### ¿Cuál es el comportamiento esperado?
> Siento que la aplicación en Play Store no debería incluir estos espejos, porque ya no están controlados oficialmente. Sin embargo, no estoy seguro de si es posible remediar esto debido a los problemas de Android 10. Leí en el aviso de desaprobación que la versión de Google Play se eliminaría en algún momento. Siento que podría ser la mejor solución para prevenir problemas en el futuro, sin embargo, actualmente todavía está activo. ¿Existe una hoja de ruta para la eliminación y está ocurriendo pronto?
> 
> ### Información del sistema
> Ya desinstalé la aplicación por el motivo mencionado anteriormente, pero es la versión anterior de Google Play.

**Comment by taibgamer0** [comment]
Please fix apt update &&  apt upgrade

**Comment by evrial** [comment]
Well that's pathetic that playstore is abandoned, that's a loss of good app

**Comment by truboxl** [comment]
The only up to date mirror repo included in Google Play version is mirrors.tuna.tsinghua.edu.
One can termux-change-repo to that mirror, apt upgrade, then change back to packages-cf.termux.org.

Though it's better to just uninstall and install from F-Droid with how much termux-app has improved since then.

**Comment by evrial** [comment]
f-droid is garbage

**Comment by Iclo30** [comment]
Isn't the DNS automatic. And if the DNS is bought by someone and the person can't afford the web address it becomes locked making whatever server invalid including the app

**Comment by Iclo30** [comment]
> The only up to date mirror repo included in Google Play version is mirrors.tuna.tsinghua.edu. One can termux-change-repo to that mirror, apt upgrade, then change back to packages-cf.termux.org.
> 
> Though it's better to just uninstall and install from F-Droid with how much termux-app has improved since then.

Just delete this shit

**Comment by buttaface** [comment]
Looks like [google will soon remove Termux from the Play store](https://arstechnica.com/gadgets/2022/05/apple-and-googles-outdated-apps-ban-would-cut-each-store-by-a-third/).

**Comment by Iclo30** [comment]
Any idea when

**Comment by agnostic-apollo** [comment]
From Nov 1, 2022, termux app shouldn't be installable on Android `>= 10` from playstore.

https://www.xda-developers.com/google-play-store-outdated-apps-policy

**Comment by FrhnAndi** [comment]
can anyone help me with this problem, I think it's because every time I paste the URL an error occurs, please help

![IMG_20220923_142509](https://user-images.githubusercontent.com/114212320/191903885-681030f2-8eef-46ac-a7de-7056d1002505.jpg)

**Comment by Midris204** [comment]
I remember exactly when I noticed this issue two years ago when my accounts and devices were hacked.  
Since that time , I have not been able to find a solution to the problem. Rather, I have come to believe that this version whitch is ( not updated and is not certfied ( is a hacking application and all the applications in it are injected applications )

**Comment by kristibektashi** [comment]
The app is still installable from the Play Store in Android 14 as of February 18 2024

**Comment by Busbenz** [comment]
![Screenshot_20240329-213529](https://github.com/termux/termux-packages/assets/164065013/e8533e57-bbf3-4c06-9d5d-1e2ee79b92ea)
    Please help me this is my problem

**Comment by tutacat** [comment]
The Termux app is still shown on normal publix search on google play store, Google has not changed anything, and since @fornwall has not modified it more or made it clearer, people will still find or use it. Especially since the old mirror domain is dead, the warning will not show because ir can't be updated by default.

**Comment by agnostic-apollo** [comment]
It's at least not installable on Android `>= 10` from playstore since some x months.

**Comment by deltragon** [comment]
Is this information still accurate? I can both find and install Termux on Google Play on Android 13, although I did have it installed previously.
It also says there was an update on June 4th on the Play Store...

**Comment by finagolfin** [comment]
See termux/termux-app#4000

**Comment by Grimler91** [comment]
@deltragon as far as I know the bootstraps of playstore app is still old and contain outdated mirrorlist, so yeah, issue is still relevant. See also https://github.com/termux/termux-app/discussions/4000

**Comment by fornwall** [comment]
@deltragon The packages on the new Google Play build are actually now up-to-date (see https://github.com/termux-play-store/termux-packages) and using a secure repository on [termux.net](https://termux.net/dists/stable/InRelease).

See https://github.com/termux-play-store for more information about the new Termux build on Google Play.
