### ISSUE TITLE
[Bug]: Problems in Lua package

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/termux-packages#7847]
### Problem description

I made package manager using Lua , but Lua no support ".." symbol. But this symbol work with other devices.

https://user-images.githubusercontent.com/87801676/138626307-a6d9f866-c30d-4892-898c-b03321812e19.mp4

### What steps will reproduce the bug?

Every time I run my project

### What is the expected behavior?

It should ask me to input the apps to installed. But now it goes directly to `apt install`

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.19.95-perf+ #1 SMP PREEMPT Wed Sep 8 18:31:36 CST 2021 aarch64 Android
Device manufacturer:
vivo
Device model:
V2027

```

**Comment by IIILI7III** [comment]
apt update
apt upgrade
apt install lua54
