### ISSUE TITLE
error: Unable to locate package

### ISSUE THREAD

**Issue by brumka** [termux/termux-packages#785]
Termux v0.46
Android 7.1.1

```
$ apt install dnsutils
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package dnsutils

```

what do I do wrong?

**Comment by Neo-Oli** [comment]
Run `apt update` first.

**Comment by brumka** [comment]
@Neo-Oli   Many thanks, that did the trick

suggestion - how about friendlier error messages (suggestions?) to avoid the confusion?  Or, alternatively, a page with basic troubleshooting/tips'n'tricks steps?
