### ISSUE TITLE
[Bug]: lld fails to link Pillow because of a bug upstream in that Python package

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-packages#7861]
### Problem description

ldd.ld fails in android 11

ld.lld: error: /system/lib/libdl.so is incompatible with aarch64linux                                                 ld.lld: error: /system/lib/libc.so is incompatible with aarch64linux                                                  ld.lld: error: /system/lib/libdl.so is incompatible with aarch64linux

Issues compiling pillow for python

### What steps will reproduce the bug?

pip install pillow

### What is the expected behavior?

Successful compilation 

### System information

Application version:                                       0.117                                                      Packages CPU architecture:                                 aarch64                                                    Subscribed repositories:                                   # sources.list                                             deb https://termux.mentality.rip/termux-main/ stable main  # game-repo (sources.list.d/game.list)                     deb https://packages.termux.org/apt/termux-games games stable                                                         # science-repo (sources.list.d/science.list)               deb https://packages.termux.org/apt/termux-science science stable                                                     # x11-repo (sources.list.d/x11.list)                       deb https://packages.termux.org/apt/termux-x11 x11 main    Updatable packages:                                        All packages up to date                                    Android version:                                           11                                                         Kernel build information:                                  Linux localhost 4.19.152-perf-22330356-abA426USQU3AUH3 #1 SMP PREEMPT Mon Aug 16 18:26:07 KST 2021 aarch64 Android    Device manufacturer:                                       samsung                                                    Device model:                                              SM-A426U

**Comment by r0xtar** [comment]
> > `/system/lib`用于 32 位二进制文​​件。对于 64 位，`/system/lib64`应改为使用。
> > good
> > use  LDFLAGS="-L/system/lib64/" CFLAGS="-I/data/data/com.termux/files/usr/include/" pip install Pillow  to install

Thanks, It worked.
I was also facing this same problem.
![IMG_20211030_081246](https://user-images.githubusercontent.com/72034576/139517622-3a695b6b-3520-4b1a-a99e-e7b74b928dae.jpg)

**Comment by landfillbaby** [comment]
yeah instead of using my fork just do that
`LDFLAGS=-L/system/lib64 pip install Pillow`

**Comment by AhmadNaruto** [comment]
try : 
LDFLAGS="-L/system/lib64/" CFLAGS="-I/data/data/com.termux/files/usr/include/" pip install Pillow

its success for me

**Comment by xtkoba** [comment]
Note that we now have a package for this: `python-pillow`.
