### ISSUE TITLE
[Bug]: (*p->engine)->CreateAudioPlayer(p->engine, &p->player, &audio_source, &audio_sink, 2, iid_array, required): 9

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#7866]
### Problem description

OpenSLES error occured when playing wav audio. Rarely happend to me before

```
(*p->engine)->CreateAudioPlayer(p->engine, &p->player, &audio_source, &audio_sink, 2, iid_array, required): 9
```

On logcat:

```
10-27 17:24:03.732  6344  6344 I VivoDaemonServiceApp: hasClip=true,count=1,clipdata=ClipData { text/plain <10-27 17:24:03.726> {T:(*p->engine)->CreateAudioPlayer(p->engine, &p->player, &audio_source, &audio_sink, 2, iid_array, required): 9} }
10-27 17:24:03.733  6344  6344 D VivoDaemonServiceApp: copied text: (*p->engine)->CreateAudioPlayer(p->engine, &p->player, &audio_source, &audio_sink, 2, iid_array, required): 9
10-27 17:24:03.733  1592  1592 I VivoDaemonServiceApp: hasClip=true,count=1,clipdata=ClipData { text/plain <10-27 17:24:03.726> {T:(*p->engine)->CreateAudioPlayer(p->engine, &p->player, &audio_source, &audio_sink, 2, iid_array, required): 9} }
10-27 17:24:03.733  1592  1592 D VivoDaemonServiceApp: copied text: (*p->engine)->CreateAudioPlayer(p->engine, &p->player, &audio_source, &audio_sink, 2, iid_array, required): 9
```

### What steps will reproduce the bug?

Unreproduceable on most cases. However, `mpv [some wav file]`

### What is the expected behavior?

mpv plays the sound

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.77+ #1 SMP PREEMPT Thu Jul 15 19:11:41 CST 2021 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1820
```

**Comment by tomty89** [comment]
So it's unreproducible with the same file that triggered the problem?

`9` is apparently `SL_RESULT_CONTENT_UNSUPPORTED`. Sounds a bit like your device (or OS build) having problem supporting certain spec of PCM, but in that case the problem should be reproducible (well, except maybe it's triggered by certain spec change; like it only has problem handling a "player creation" with a spec that is different from the last one, or something like that)

Btw as per the error message, you are having problem with the ao driver in mpv, which, unlike the pulseaudio output module, is not a part of Termux. (Though I was the same last person that did a major polishment / rewrite to it.)

**Comment by Yonle** [comment]
Well, i don't think that it's the issue of my OS, Since openal is working properly. 

Other WAV file can played as what i wish. Anyways, Here's the WAV file that i try: https://cdn.discordapp.com/attachments/844736898449539125/903625555944038440/websdr_recording_start_2021-10-29T12_39_21Z_15852.0kHz.wav

**Comment by tomty89** [comment]
Probably because your file has a sample rate lower than 8KHz (according to ffprobe it's 7119Hz). See https://android.googlesource.com/platform/frameworks/wilhelm/+/master/src/data.cpp#384

There's no code in the opensles ao that guards the sample rate to use. We can probably add something like:
```
ao->samplerate = MPMIN(MPMAX(ao->samplerate, 8000), 192000);
```

Meanwhile you can have e.g. `audio-samplerate=48000` in `/data/data/com.termux/files/usr/etc/mpv/mpv.conf` as a workaround.
