### ISSUE TITLE
libcompiler-rt package is missing memory sanitizer library components (cannot compile with -fsanitize=memory)

### ISSUE THREAD

**Issue by Oblomov** [termux/termux-packages#7877]
### Problem description

While trying to debug an issue with some personal code, I tried to build it using the memory sanitizer (-fsanitze=memory flag). This fails at the linking stage with the error:

ld.lld: error: cannot open /data/data/com.termux/files/usr/lib/clang/13.0.0/lib/android/libclang_rt.msan-aarch64-android.a: No such file or directory
ld.lld: error: cannot open /data/data/com.termux/files/usr/lib/clang/13.0.0/lib/android/libclang_rt.msan_cxx-aarch64-android.a: No such file or directory

dpkg -L libcompiler-rt confirms that, while other sanitizers (asan, ubsan, tsan, scudo, etc) are present, the msan component is missing, while the header interface file 

/data/data/com.termux/files/usr/lib/clang/13.0.0/include/sanitizer/msan_interface.h

is present.

### What steps will reproduce the bug?

Trying to build anything with memory sanitizer will fail, e.g.

     printf '\043include <cstdio>\nint main() { puts("hello world"); }' | clang -x c++ - -fsanitize=memory

(compar with `-fsanitize=address`)

### What is the expected behavior?

The program should build correctly.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.113-user+ #1 SMP PREEMPT Thu Aug 26 09:49:57 CDT 2021 aarch64 Android
Device manufacturer:
motorola
Device model:
motorola one vision
```

**Comment by xtkoba** [comment]
This is not our issue. Thanks.
