### ISSUE TITLE
Update all packages

### ISSUE THREAD

**Issue by rgh36167** [termux/termux-packages#788]
Is there a place to discuss simple scripts to keep all packages inside termux updated? Things get involved once `pip` and possibly other package managers enter the scene.. I assume many users create very similar solutions and could share some inspiration?

**Comment by fornwall** [comment]
The following resources exists for Termux-related discussions:

- Google+ community at https://termux.com/community
- A chat, either using IRC in #termux on freenode or https://gitter.im/termux/termux (they are mirrored).
- A newly started mail list at https://groups.io/g/termux/
