### ISSUE TITLE
termux-tools: termux-change-repo is not changing repo.

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#7889]
### Problem description

I tried to change repo with `termux-change-repo` command by termux-tools. After checking on `$PREFIX/apt/sources.list` and `$PREFIX/apt/sources.list.d/*`, The mirror is still pointing to main repositories that located at packages.termux.org.

### What steps will reproduce the bug?

* `termux-change-repo`
* Each repositories, Use other mirror than main ones, Like Librehat ones

### What is the expected behavior?

The repo is changed

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.77+ #1 SMP PREEMPT Thu Jul 15 19:11:41 CST 2021 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1820
```

**Comment by Grimler91** [comment]
Works fine for me, please make an [asciinema](https://asciinema.org/) recording of what you are doing

**Comment by Yonle** [comment]
Sure. Here you go: https://asciinema.org/a/445624

**Comment by sk0kanik** [comment]
@Yonle Pressing Enter key will not work. Select repo from gui screen.

**Comment by xeffyr** [comment]
Use space to select the repo and mirror before pressing enter.

**Comment by Yonle** [comment]
May i ask, why we need to press SPACE so it work?

**Comment by Grimler91** [comment]
Basically because this is how `dialog` works. Press "enter" for `OK` or `Cancel`, and "space" for toggling options in the list. There is a small note about space at the top of the window: 

![image](https://user-images.githubusercontent.com/18900601/139532378-f84d30c8-6bf5-415f-83e9-fbf43752cbae.png)

**Comment by Craglitch** [comment]
> Use space to select the repo and mirror before pressing enter.

Thanks
