### ISSUE TITLE
[Bug]: Where is the unstable-packages

### ISSUE THREAD

**Issue by GitHubNeko** [termux/termux-packages#7893]
### Problem description

Why are unstable-packages missing ?
https://github.com/termux/unstable-packages

### What steps will reproduce the bug?

None

### What is the expected behavior?

None

### System information

Termux info：0.117
Android Version：9

**Comment by xeffyr** [comment]
It has been merged with main repo (termux-packages).

**Comment by GitHubNeko** [comment]
> 它已与主存储库（termux-packages）合并。

Do I still need to install it ?

**Comment by xeffyr** [comment]
You don't need to install anything.
