### ISSUE TITLE
[Bug]:ClareFlare maybe reset by connection.

### ISSUE THREAD

**Issue by huidaoweilai2019** [termux/termux-packages#7896]
### Problem description

default mirror
https://packages.termux.org/apt/termux-main/
be replaced with
https://packages-cf.termux.org/apt/termux-main/

### What steps will reproduce the bug?

https://packages-cf.termux.org/apt/termux-main/ maybe reset by connection.

### What is the expected behavior?

speed is not reduced because of ClareFlare in specific area even reset by connection.

### System information

termux-info:

```

```

**Comment by xeffyr** [comment]
Won'tfix. If CloudFlare endpoint doesn't work for you, it doesn't mean not working for others. The only possible reasons are:
* Your network has high threat score. (likely)
* Your ISP doesn't like CloudFlare. (unlikely, but happens in some countries)

**Comment by xeffyr** [comment]
Use `termux-change-repo` to switch to another mirror.
