### ISSUE TITLE
pip install lmxl  failed 

### ISSUE THREAD

**Issue by weishaofei** [termux/termux-packages#7906]
### Problem description

pip install lxml
Collecting lxml
  Using cached lxml-4.6.3.tar.gz (3.2 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: lxml
  Building wheel for lxml (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /data/data/com.termux/files/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-fni8nv1h/lxml_a1f745616a0246e8bff62259cb13ba0e/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-fni8nv1h/lxml_a1f745616a0246e8bff62259cb13ba0e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /data/data/com.termux/files/usr/tmp/pip-wheel-pc7de9ny
       cwd: /data/data/com.termux/files/usr/tmp/pip-install-fni8nv1h/lxml_a1f745616a0246e8bff62259cb13ba0e/
  Complete output (111 lines):
  Building lxml version 4.6.3.
  Building without Cython.
  Building against libxml2 2.9.12 and libxslt 1.1.34
  Building against libxml2/libxslt in the following directory: /data/data/com.termux/files/usr/lib
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.10
  creating build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/__init__.py -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/builder.py -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/sax.py -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-aarch64-3.10/lxml
  creating build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-aarch64-3.10/lxml/includes
  creating build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-aarch64-3.10/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-aarch64-3.10/lxml/html
  creating build/lib.linux-aarch64-3.10/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-aarch64-3.10/lxml/isoschematron
  copying src/lxml/etree.h -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/etree_api.h -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/lxml.etree.h -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-aarch64-3.10/lxml
  copying src/lxml/includes/__init__.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-aarch64-3.10/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-aarch64-3.10/lxml/includes
  creating build/lib.linux-aarch64-3.10/lxml/isoschematron/resources
  creating build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/rng
  creating build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/xsl
  creating build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-aarch64-3.10/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-aarch64-3.10
  creating build/temp.linux-aarch64-3.10/src
  creating build/temp.linux-aarch64-3.10/src/lxml
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.10 -c src/lxml/etree.c -o build/temp.linux-aarch64-3.10/src/lxml/etree.o -w
  CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
  building 'lxml.objectify' extension
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.10 -c src/lxml/objectify.c -o build/temp.linux-aarch64-3.10/src/lxml/objectify.o -w
  CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
  building 'lxml.builder' extension
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.10 -c src/lxml/builder.c -o build/temp.linux-aarch64-3.10/src/lxml/builder.o -w
  CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
  building 'lxml._elementpath' extension
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.10 -c src/lxml/_elementpath.c -o build/temp.linux-aarch64-3.10/src/lxml/_elementpath.o -w
  CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
  building 'lxml.html.diff' extension
  creating build/temp.linux-aarch64-3.10/src/lxml/html
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.10 -c src/lxml/html/diff.c -o build/temp.linux-aarch64-3.10/src/lxml/html/diff.o -w
  CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
  building 'lxml.html.clean' extension
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.10 -c src/lxml/html/clean.c -o build/temp.linux-aarch64-3.10/src/lxml/html/clean.o -w
  CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
  building 'lxml.sax' extension
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.10 -c src/lxml/sax.c -o build/temp.linux-aarch64-3.10/src/lxml/sax.o -w
  CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
  Compile failed: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
  creating data
  creating data/data
  creating data/data/com.termux
  creating data/data/com.termux/files
  creating data/data/com.termux/files/usr
  creating data/data/com.termux/files/usr/tmp
  cc -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -I/usr/include/libxml2 -c /data/data/com.termux/files/usr/tmp/xmlXPathInit5ru63da7.c -o data/data/com.termux/files/usr/tmp/xmlXPathInit5ru63da7.o
  CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/cc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************
  error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for lxml

### What steps will reproduce the bug?

pkg upgrade
pkg install python
pip install cython
pkg install libxml2 libxslt
pkg install -y python ndk-sysroot clang make libjpeg-turbo
pkg install clang
pip install lxml

then the last step failed

### What is the expected behavior?

I can install lxml successfully.

### System information

termux-info:
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
apt/stable 2.3.11-3 aarch64 [upgradable from: 2.3.6]
ca-certificates/stable 1:2021-10-26-0 all [upgradable from: 20210525]
command-not-found/stable 1.66 aarch64 [upgradable from: 1.62]
coreutils/stable 9.0 aarch64 [upgradable from: 8.32-7]
curl/stable 7.79.1 aarch64 [upgradable from: 7.77.0-3]
dash/stable 0.5.11.5 aarch64 [upgradable from: 0.5.11.3]
debianutils/stable 5.5 aarch64 [upgradable from: 4.11.2]
dialog/stable 1.3-20210621-0 aarch64 [upgradable from: 1.3-20210530-0]
diffutils/stable 3.8 aarch64 [upgradable from: 3.7-3]
ed/stable 1.17-4 aarch64 [upgradable from: 1.17]
gpgv/stable 2.3.2-1 aarch64 [upgradable from: 2.3.1-1]
grep/stable 3.7-1 aarch64 [upgradable from: 3.6]
gzip/stable 1.11-3 aarch64 [upgradable from: 1.10-4]
less/stable 590 aarch64 [upgradable from: 563]
libandroid-support/stable 28-2 aarch64 [upgradable from: 28]
libc++/stable 23b-3 aarch64 [upgradable from: 21d-1]
libcurl/stable 7.79.1 aarch64 [upgradable from: 7.77.0-3]
libgnutls/stable 3.6.16 aarch64 [upgradable from: 3.6.15-3]
libidn2/stable 2.3.2 aarch64 [upgradable from: 2.3.0-2]
libnettle/stable 3.7.3 aarch64 [upgradable from: 3.7.2]
libnghttp2/stable 1.46.0 aarch64 [upgradable from: 1.43.0]
libtirpc/stable 1.3.1-2 aarch64 [upgradable from: 1.3.1]
nano/stable 5.9 aarch64 [upgradable from: 5.7]
openssl/stable 1.1.1l aarch64 [upgradable from: 1.1.1k-2]
pcre/stable 8.45 aarch64 [upgradable from: 8.44-1]
termux-keyring/stable 2.3 all [upgradable from: 1.9]
Android version:
11
Kernel build information:
Linux localhost 4.19.113-perf-g3dd0f3f1fb5d #1 SMP PREEMPT Sat Sep 18 23:52:47 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2012K11AC

**Comment by Grimler91** [comment]
Update your packages, `pkg upgr`
