### ISSUE TITLE
[Bug]: enchant package doesn't work

### ISSUE THREAD

**Issue by mazhe1988** [termux/termux-packages#7908]
### Problem description

I have aspell ,hunspell and en_US dictionaries installed, and I try to install enchant package. After installed, Try to run: 'enchant-lsmod-2 -lang'  it shows no dictionary for en_US.  I mannully install the enchant tar ball file from their [github.](https://github.com/AbiWord/enchant/tags) Then the command working now. 

### What steps will reproduce the bug?

~$ package install aspell
~$ package install hunspell
~$ package install enchant
~$ enchant-lsmod-2 -lang

### What is the expected behavior?

~$ enchant-lsmod-2 -lang
en_US (aspell)

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
Updatable packages:
libicu/stable 70.1 aarch64 [upgradable from: 69.1-2]
libvte/x11 1:0.62.2-5 aarch64 [upgradable from: 1:0.62.2-4]
qt5-qtbase/x11 5.12.11-4 aarch64 [upgradable from: 5.12.11-3]
texlive-bin/stable 20210325-4 aarch64 [upgradable from: 20210325-3]
Android version:
11
Kernel build information:
Linux Pixel-2-XL 4.4.283-lineage-gb72b369040eb #1 SMP PREEMPT Thu Oct 14 09:57:09 UTC 2021 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 2 XL
```

**Comment by Maxython** [comment]
This problem appeared due to the termux compiler.  The number of files varies.  

#### Compilation
![Screenshot_20211101-223103_Termux](https://user-images.githubusercontent.com/60917834/139730792-cd74cce8-b331-444c-b833-83c65e8623ef.jpg)

#### Original (deb)
![Screenshot_20211101-223116_Termux](https://user-images.githubusercontent.com/60917834/139730948-b6dfdebf-d72a-4e58-9912-a91f43adc14f.jpg)

Need to edit the `build.sh` file to compile correctly.

**Comment by xtkoba** [comment]
> This problem appeared due to the termux compiler. The number of files varies.

I think that is not the point. The difference in the `lib` dir is due to static libraries excluded, plus the naming convention of shared libraries on Android.

**Comment by xtkoba** [comment]
But yeah, we need to edit the `build.sh`, because currently it depends only on `glib`, whereas it should depend (at least at build time) on `aspell` and `hunspell`.

**Comment by Maxython** [comment]
I found a problem and a solution.  The compiler splits the "compilation output" into two packages.  
![Screenshot_20211102-000004_Termux](https://user-images.githubusercontent.com/60917834/139744217-8a5d533d-0bc6-4b4a-877a-ec68f2d0eeec.jpg)
The package with the word "static" is the missing files for enchant to work properly. You can install this package by running the following command:  
```
pkg ins enchant-static
```

It seems to me that it would be logical to disable the separator, so as not to do unnecessary actions.
