### ISSUE TITLE
Samsung Galaxy Note N7000 is unsupported? why?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [termux/termux-packages#791]
I see the message from Play Market that my device is unsupported.

**Comment by vitaly-zdanevich** [comment]
Sorry incorrect repository.

**Comment by fornwall** [comment]
@vitaly-zdanevich For your information, Termux requires Android 5.0 or later.

This is unlikely to change, as Termux packages depends on low level system libraries and implementation details which makes it hard to support earlier Android versions simultaneously.
