### ISSUE TITLE
depot_tools

### ISSUE THREAD

**Issue by essential-existence** [termux/termux-packages#7913]
### Package description

Tools for working with Chromium development. It requires python 2.7 or 3.8 for python 3 support.

### Home page URL

https://chromium.googlesource.com/chromium/tools/depot_tools

### Source code URL

https://chromium.googlesource.com/chromium/tools/depot_tools.git/+archive/refs/heads/main.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by thunder-coding** [comment]
`depot_tools` can be used by just cloning the repo from chromium.googlesource.com and removing some Linux binaries like `gn` or `ninja`. Both `ninja` and `gn` are available in the Termux repositories since a while. 

Also I don't think anyone here is in need of `depot_tools`.

**Comment by essential-existence** [comment]
the problem is that gclient and fetch are not responding. Perhaps they are needed in the patch.

**Comment by thunder-coding** [comment]
Although the `gclient` and `fetch` from `depot_tools` are buggy, there is no scope that the package will be added to Termux. If you are able to fix these issues, consider sharing the patches with the community.

I feel you should go through the comments as here https://aur.archlinux.org/packages/depot-tools-git/

Especially this one

>Installers beware! This package is a fiasco and the upstream Git repository basically has bunch of binary blobs in it that do strange things. I'm working on cleaning up the packaging some but the upstream behavior is egregious. Wash your /opt/depot_tools directory out with soap and bleach when done.
