### ISSUE TITLE
[Package]: Snapcast server

### ISSUE THREAD

**Issue by guerman5** [termux/termux-packages#7929]
### Package description

Snapcast is a multispeaker client-server audio system, where all clients are time synchronized with the server to play perfectly synced audio.
One of the most generic ways to use Snapcast is in conjunction with the music player daemon (MPD)

Termux already has mpd player package, snapcast server package would be the cherry on top. 
Although currently you can use mpd's httpd to broadcast over wifi, every player is for himself. With mpd+snapcast you turn your phone hotspot into a radio! 
You get together with your friends and run mpd+snapcast in termux, then only ask them to install the snapcast client. All phones will play in unison and become a surround system. They can remote control mpd server too

https://play.google.com/store/apps/details?id=de.badaix.snapcast
https://apps.apple.com/us/app/snapcast-client/id1552559653

### Home page URL

https://github.com/badaix/snapcast

### Source code URL

https://github.com/badaix/snapcast.git

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Have you tried to compile it on device?
I successfully compiled it on RPi and Arch following guidelines. Snapcast developer used to have android server version, but discontinued on 0.13.0. I tried to compile old release but unsuccesful :(. its beyond my capabilities.
I think termux uses a different approach, since its meant to be run from console as any linux.

mpd.conf only needs to output to fifo file, snapcast takes it from there.
'audio_output {
type            "fifo"
name            "ncpmcpp visualizer & snapfifo"
path            "@TERMUX_PREFIX@/var/run/mpd.fifo"
format          "44100:16:2"
enabled		"yes"
}'

**Comment by tathastu871** [comment]
Requires: https://github.com/google/oboe

**Comment by xtkoba** [comment]
`oboe` is not required if the environment pretends not to be Android, as the author of this issue said:

> I think termux uses a different approach, since its meant to be run from console as any linux.

We can use the `pulse` backend instead of `oboe`.
