### ISSUE TITLE
[Package]: nodejs - previous version

### ISSUE THREAD

**Issue by anonimo82** [termux/termux-packages#7930]
### Package description

Nodejs v14

### Source code URL

https://github.com/nodejs/node

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

code-server requires node v14 to install, while in the latest lts we have v16.
Please, provide a package for v14 too (maybe you can name it nodejs-old?)

Thanks in advance for any help

**Comment by thunder-coding** [comment]
I don't think there is any Linux distribution that maintains 3 different versions of nodejs. Nodejs requires 2+ hours to build on CI and is a pain to keep it up to date. Also code-server can be installed by using the `FORCE_NODE_VERSION` environment variable.

```sh
FORCE_NODE_VERSION=<current major node version> yarn global add code-server
```

I would recommend using `nodejs-lts` instead of `nodejs` for more stable experience

If you have any other reason to also keep v14 legacy version of node, consider commenting

**Comment by anonimo82** [comment]
Yes, I'm using lts
Tried your way, doesn't work

**Comment by anonimo82** [comment]
Yes, I'm using lts.
Tried with FORCE_NODE_VERSION=16 yarn global add code-server, no luck

**Comment by thunder-coding** [comment]
Weird, I am currently having working code-server with nodejs v17, reinstalled a few days ago when updating nodejs to v17. Probably it's an upstream issue. Also I have updated the previous comment to also pass `--ignore-engines` to yarn, consider trying to check whether it works

Also nodejs has ended active LTS for v14 and entered maintenance only release (i.e. only critical bug fixes and security patches).

**Comment by anonimo82** [comment]
Here is my output:
https://pastebin.com/kCe0TqFb

**Comment by thunder-coding** [comment]
Install `binutils` to be able to use the `ar` command. The same solution as of https://github.com/termux/termux-packages/discussions/7914#discussioncomment-1575734

**Comment by anonimo82** [comment]
Yes, it now works.
Thanks a lot!

**Comment by thunder-coding** [comment]
> Yes, it now works.
> Thanks a lot!

Also consider posting the fix to the upstream issue so that others can also benifit 🙃

**Comment by anonimo82** [comment]
Yes, how?

**Comment by anonimo82** [comment]
I'm having issues installing svg extension (from jock), either from marketplace or with vsix

**Comment by RoyGalaxy** [comment]
Can you please downgrade the node package to v14 or provide us with something through which we can install v14 of node in termux. I want to install code-server which requires v14 but i can't. They told me that nodejs doesn't support v16

**Comment by anonimo82** [comment]
@RoyGalaxy I've been able to install it, but I had troubles with extensions.
Just install binutils and follow the instructions from @thunder-coding

**Comment by H4M5TER** [comment]
Currently VSCode is using Electron 13.5.1 and Node.js 14.16.0, and code-server is bound with it.
I wonder how to compile node 14 for termux manually.
```
pkg install binutils git build-essential python2
git clone -b v14.x --depth 1 https://github.com/nodejs/node
python2 ./configure
make -j4
```
The commands above failed with something like `can't find 'execinfo.h'`.
Any ideas?

**Comment by H4M5TER** [comment]
I tried `FORCE_NODE_VERSION=16 yarn global add code-server --ignore-engines` and it worked.
Though it's comfusing that
```
FORCE_NODE_VERSION=16
yarn global add code-server --ignore-engines
```
not working.

**Comment by xeffyr** [comment]
@H4M5TER It doesn't work because `FORCE_NODE_VERSION=16` is not exported. Using it as a prefix before command will cause it being exported to subprocess. But it won't be exported if used standalone or without `export` keyword. That's how shell working.

**Comment by H4M5TER** [comment]
Thank you for answering that @xeffyr
