### ISSUE TITLE
[Bug]: Build Emacs 27.2 from current docker image

### ISSUE THREAD

**Issue by lajapriv** [termux/termux-packages#7942]
### Problem description

I did a build of Emacs from current docker image (DIGEST:sha256:5ffbf24cc86c). This is what I get when I try to install it:

```

dpkg -i Sync/emacs_27.2-5_aarch64.deb
(Reading database ... 30632 files and directories currently installed.)
Preparing to unpack Sync/emacs_27.2-5_aarch64.deb ...
Unpacking emacs (27.2-5) over (27.2-5) ...
Setting up emacs (27.2-5) ...
Warning: arch-independent data dir '/data/data/com.termux/files/usr/share/emacs/27.2/etc/': Invalid argument
Warning: Lisp directory '/data/data/com.termux/files/usr/share/emacs/27.2/lisp': Invalid argument
Error: /data/data/com.termux/files/usr/share/emacs/27.2/etc/charsets: Invalid argument
Emacs will not function correctly without the character map files.
Please check your installation!
mv: cannot stat '/data/data/com.termux/files/usr/bin/emacs*.pdmp': No such file or directory
dpkg: error processing package emacs (--install):
 installed emacs package post-installation script subprocess returned error exit status 1
Processing triggers for man (1.14.5-2) ...
Errors were encountered while processing:
 emacs
```

### What steps will reproduce the bug?

Biuld emacs pkg from docker image.

### What is the expected behavior?

Working emacs app.

### System information

termux-info:

```
termux-info
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.205-21567889 #1 SMP PREEMPT Tue May 11 12:52:25 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T835

```

**Comment by Grimler91** [comment]
I can reproduce it. Errors come from postinst script, command for [dumping emacs](https://github.com/termux/termux-packages/blob/master/packages/emacs/build.sh#L131) seem to no longer work for some reason

**Comment by Grimler91** [comment]
I get the same error when building on device, both with 27.2 and from the master branch.

The warning and error comes from [file-accessible-directory-p](https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/src/fileio.c#L2987) that is suppose to make sure the directory is read&writable. "Invalid argument" seems like a weird error to get from this function.

**Comment by Grimler91** [comment]
Seems like it comes from faccessat: https://github.com/emacs-mirror/emacs/blob/master/src/fileio.c#L162, will test if ac_cv_func_faccessat=no helps

**Comment by Grimler91** [comment]
Should be fixed by https://github.com/termux/termux-packages/commit/369d15f4ef9f0db258949d251194f4a8f991bd08
