### ISSUE TITLE
[Bug]: Tesseract won't work after update 5.0.0-rc1-0

### ISSUE THREAD

**Issue by Kapideveloper** [termux/termux-packages#7953]
### Problem description

Tesseract is no longer working on termux after update 5.0.0-rc1-0, and version 4.1.1 has been removed from termux repo. it's impossible to use that package or even downgrading to 4.1.1.

Even after reinstalling it, it doesn't work.

### What steps will reproduce the bug?

Any tesseract command

### What is the expected behavior?

**Without installing zstd, i got the following error:**
```
CANNOT LINK EXECUTABLE "tesseract": library "libzstd.so.1" not found
```
**After installing zstd:**
```
CANNOT LINK EXECUTABLE "tesseract": cannot locate symbol "__extenddftf2" referenced by "/data/data/com.termux/files/usr/lib/libtesseract.so"...
```

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.288-BAALAM-1.5 #1 SMP PREEMPT Thu Oct 28 20:51:11 CDT 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
POCO F1
```

**Comment by Grimler91** [comment]
Seems de need to link it against whatever library that provides `__extenddftf2` as well

**Comment by buttaface** [comment]
I looked into it and that `__extenddftf2` symbol comes from the libm math library. Either that's a new dependency of this package or maybe something changed with the recent NDK 23 update.

**Comment by Grimler91** [comment]
Not sure why it isn't found by tesseract. `__extenddftf2` seem to come from `static_cast<long double>()` in [src/ccstruct/quadlsq.cpp](https://github.com/tesseract-ocr/tesseract/blob/60fd2b4abaa9c5c5c42d32db57576bc95d28a78a/src/ccstruct/quadlsq.cpp#L65). 

Compiling a minimal boiled down version of that file:
```c++
#include "stdio.h"
int main() {
  double x = 2;
  long double y = static_cast<long double>(x);
  printf("%Lf\n", y);
}
```
with clang++ gives a working program, in which __extenddftf2 is used.

With a debug build of tesseract I end up with another symbol not found:
```
$ tesseract
CANNOT LINK EXECUTABLE "tesseract": cannot locate symbol "__kmpc_global_thread_num" referenced by "/data/data/com.termux/files/usr/lib/libtesseract.so"...
```

Switching to building with cmake instead of configure and make seems to workaround the problem, so I suggest we do that as a simple way out

**Comment by Grimler91** [comment]
Should work in 5.0.0-rc1-2, which will be available when build for https://github.com/termux/termux-packages/commit/790148396721443576e8fd32e034a2a8051c3281 finishes (or within a couple of hours on mirrors). Please let me know if it does not work after upgrading on your device.

**Comment by Grimler91** [comment]
For the record, even building on device with the Makefile gives an undefined symbol error:

```
CANNOT LINK EXECUTABLE "tesseract": cannot locate symbol "__aarch64_ldadd8_relax" referenced by "/data/data/com.termux/files/usr/lib/libtesseract.so"...
```

Also looks like we need to fix the NEON check stuff for i686, I am on it.

**Comment by Kapideveloper** [comment]
> Should work in 5.0.0-rc1-2, which will be available when build for [7901483](https://github.com/termux/termux-packages/commit/790148396721443576e8fd32e034a2a8051c3281) finishes (or within a couple of hours on mirrors). Please let me know if it does not work after upgrading on your device.

Stills not working
Now i get this error when trying to read an image:

```
Error opening data file ./eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.```

**Comment by Grimler91** [comment]
@Kapideveloper what do I run to reproduce the issue?

**Comment by Kapideveloper** [comment]
> @Kapideveloper what do I run to reproduce the issue?

Try to read any image using ocr

i've used that command:

```
tesseract code.png stdout```

**Comment by Kapideveloper** [comment]
> @Kapideveloper what do I run to reproduce the issue?

@Grimler91
I've almost fixed that bug by exporting the TESSDATA_PREFIX to the right directory, using
```export TESSDATA_PREFIX=../usr/share/tessdata``` at home directory.

but it doesn't work if i navigate to another directory, like a folder.

![Screenshot_20211109-221409818](https://user-images.githubusercontent.com/88977720/141031729-3d7e3fe4-a772-4167-8738-7d7ed272cad8.jpg)

**Comment by sk0kanik** [comment]
> but it doesn't work if i navigate to another directory, like a folder.
> 
Use absolute path `export TESSDATA_PREFIX=$PREFIX/share/tessdata`

**Comment by Kapideveloper** [comment]
> > but it doesn't work if i navigate to another directory, like a folder.
> 
> Use absolute path `export TESSDATA_PREFIX=$PREFIX/share/tessdata`

Thanks! It did work :^)

**Comment by Kapideveloper** [comment]
> > but it doesn't work if i navigate to another directory, like a folder.
> 
> Use absolute path `export TESSDATA_PREFIX=$PREFIX/share/tessdata`

For some reason, the terminal just forgets the tessdata_prefix if i restart it.
after restarting the terminal, i always need to run the command again to make tesseract work again

**Comment by sk0kanik** [comment]
> > > but it doesn't work if i navigate to another directory, like a folder.
> > 
> > 
> > Use absolute path `export TESSDATA_PREFIX=$PREFIX/share/tessdata`
> 
> For some reason, the terminal just forgets the tessdata_prefix if i restart it. after restarting the terminal, i always need to run the command again to make tesseract work again

You can add this line to ~/.profile file. `echo "export TESSDATA_PREFIX=$PREFIX/share/tessdata" >> ~/.profile`
so that you will not need run it manually

**Comment by Kapideveloper** [comment]
> > > Use absolute path `export TESSDATA_PREFIX=$PREFIX/share/tessdata`
> > 
> > 
> > For some reason, the terminal just forgets the tessdata_prefix if i restart it. after restarting the terminal, i always need to run the command again to make tesseract work again
> 
> You can add this line to ~/.profile file. `echo "export TESSDATA_PREFIX=$PREFIX/share/tessdata" >> ~/.profile` so that you will not need to run it everytime you open terminal.

Didn't work

**Comment by sk0kanik** [comment]
> > > For some reason, the terminal just forgets the tessdata_prefix if i restart it. after restarting the terminal, i always need to run the command again to make tesseract work again
> > 
> > 
> > You can add this line to ~/.profile file. `echo "export TESSDATA_PREFIX=$PREFIX/share/tessdata" >> ~/.profile` so that you will not need to run it everytime you open terminal.
> 
> Didn't work

Close and reopen terminal. if still not working, what is your output of `cat .profile && ps -p $$` command.

**Comment by Grimler91** [comment]
Added with a configure flag in https://github.com/termux/termux-packages/commit/8b314cbf99bbdd9ff106c9264300377a5f3dd57d, so in 5.0.0-rc1-3 there should be no need to set the path in .profile or similar
