### ISSUE TITLE
wa-sticker-formatter

### ISSUE THREAD

**Issue by Oreki-san** [termux/termux-packages#7959]
### Problem description

Termux isn't supporting wa-sticker-formatter
Error with sharp see(https://sharp.pixelplumbing.com/install) prebuilts aren't for armv7

### Steps to reproduce the behavior.

npm i sharp 

### System information

* Termux application version: 0117
* Android OS version:11
* Device model:realme 7 pro max

**Comment by Grimler91** [comment]
We generally do not package things that can be installed through other package managers like npm.

What error do you get when you try to install it?

**Comment by X7md** [comment]
try install it through pnpm, instead of npm.

I think nodejs-lts have some issues with npm.

[pnpm installation guide](https://pnpm.io/installation#using-a-standalone-script)

**Comment by Oreki-san** [comment]
> We generally do not package things that can be installed through other package managers like npm.
> 
> What error do you get when you try to install it?

![Uploading Screenshot_2021-11-11-12-29-52-85_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by Oreki-san** [comment]
> We generally do not package things that can be installed through other package managers like npm.
> 
> What error do you get when you try to install it?

![Screenshot_2021-11-11-12-29-52-85_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/77143046/141254138-3800890f-8e16-43cb-95fe-6345d14359c7.jpg)

**Comment by Oreki-san** [comment]
> try install it through pnpm, instead of npm.
> 
> I think nodejs-lts have some issues with npm.
> 
> [pnpm installation guide](https://pnpm.io/installation#using-a-standalone-script)

![Screenshot_2021-11-11-12-33-14-56_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/77143046/141254238-4ab2c804-8964-4593-afaf-993fb5bf2432.jpg)
I did ``pnpm i sharp``

**Comment by X7md** [comment]
You need to have `libvips` & `node-gyp`.

I try but I have another issues with `node-gyp`.

**Comment by Oreki-san** [comment]
> You need to have `libvips` & `node-gyp`.
> 
> I try but I have another issues with `node-gyp`.

Yes there are error with 'node-gyp` too

**Comment by truboxl** [comment]
```
pkg install glib libvips nodejs-lts
CXXFLAGS="-I$PREFIX/include/glib-2.0 -I$PREFIX/lib/glib-2.0/include" npm i sharp
```

If there's any extra deps needed, please follow the build error message and install them then rerun npm command.
