### ISSUE TITLE
[Bug]: WARNING: linker: Warning: unable to normalize ""

### ISSUE THREAD

**Issue by Learn-Termux** [termux/termux-packages#7968]
### Problem description

Using Any Commends
Shows ```WARNING: linker: Warning: unable to normalize ""```

### What steps will reproduce the bug?

Using Any Commends 
( like : ls,cd,apt,pkg etc ,...)

### What is the expected behavior?

![Screenshot_20211112-185558](https://user-images.githubusercontent.com/91124025/141474339-e2f38c24-3c90-4087-89c3-f93ff6c1ae53.jpg)
![Screenshot_20211112-185527](https://user-images.githubusercontent.com/91124025/141474359-4aa47b9a-b8ed-461f-8c0c-abcc99552192.jpg)

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
7.1.1
Kernel build information:
Linux localhost 3.18.31-13696519 #1 SMP PREEMPT Wed Dec 2 15:12:08 KST 2020 armv7l Android
Device manufacturer:
samsung
Device model:
SM-J250F
```

**Comment by buttaface** [comment]
Huh, haven't seen that one, and [I run a CI on Android 7 x86_64](https://github.com/buttaface/swift-android-sdk/runs/4188132920?check_suite_focus=true#step:3:1482). Maybe specific to arm, @Grimler91?

**Comment by Grimler91** [comment]
I haven't seen this on arm android 11, can perhaps flash android 7 in a new days and investigate

**Comment by thunder-coding** [comment]
Seems to be a similar problem as highlited here https://github.com/iBotPeaches/Apktool/issues/1491#issuecomment-358045207

I could reproduce using the following on my aarch64 Android 11 device
```sh
$ LD_LIBRARY_PATH=" " <Any command>
```

**Comment by buttaface** [comment]
Nice find, @thunder-coding.

@Learn-Termux, can you check if `LD_LIBRARY_PATH` is set incorrectly for you, by running `env | grep LD_LIBRARY_PATH`? If that isn't set, install the `llvm` package and check the runpath for binaries like `ls` with `llvm-readelf -d $PREFIX/bin/ls | grep runpath`. If either has an empty path, that is the problem.

**Comment by buttaface** [comment]
Closing since no response in a month.
