### ISSUE TITLE
[Bug]: Unstable-Repo not installing

### ISSUE THREAD

**Issue by Unknownman21229** [termux/termux-packages#7970]
### Problem description

I can't do "pkg install unstable-repo"

### What steps will reproduce the bug?

Write "pkg unstable-repo"

### What is the expected behavior?

It working

### System information

termux-info:

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://main.termux-mirror.ml/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
8.0.0
Kernel build information:
Linux localhost 4.4.23+ #1 SMP PREEMPT Wed Sep 30 11:01:01 CST 2020 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
PRA-LX1
```

**Comment by sk0kanik** [comment]
Unstable-repo has been merged with main repo.

**Comment by Unknownman21229** [comment]
> Unstable-repo has been merged with main repo.

But how do i install tcc then? it says to use unstable-repo

**Comment by sk0kanik** [comment]
> > Unstable-repo has been merged with main repo.
> 
> But how do i install tcc then? it says to use unstable-repo

[tcc has been disable](https://github.com/termux/termux-packages/commit/23e4884159ec4b3e0b2527ad4e8279775d31888f).
And from your `termux-info` output, it seems you are using dl.bintray.com [which is down](https://github.com/termux/termux-packages/issues/6726).
