### ISSUE TITLE
[Bug]: ImportError: libopenblas.so.0

### ISSUE THREAD

**Issue by olav2021** [termux/termux-packages#7971]
### Problem description

Proot ubuntu python and julia has ImportError: libopenblas.so.0 issues.

### What steps will reproduce the bug?

trying to install matplotlib...

### System information

termux-info:

armv81

```

**Comment by Grimler91** [comment]
Please fill in the bug report template.

If you have a package issue in some proot distro then there's nothing we can do from termux's side
