### ISSUE TITLE
[Package]: py3-pyscard

### ISSUE THREAD

**Issue by songwutk** [termux/termux-packages#7984]
### Package description

https://github.com/LudovicRousseau/pyscard

smartcard library for python

### Home page URL

https://pyscard.sourceforge.io/

### Source code URL

https://github.com/LudovicRousseau/pyscard

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by thunder-coding** [comment]
The package you are requesting is written in Python

From https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy

> Not installable through cpan, gem, npm, or pip

> These packages should be installable through cpan, gem, npm, pip and so on.

**Comment by songwutk** [comment]
Thanks.

**Comment by songwutk** [comment]
How about https://github.com/aodstudio/thai-smartcard-reader ?

**Comment by Grimler91** [comment]
> How about https://github.com/aodstudio/thai-smartcard-reader ?

Install it through npm as per the [installation instructions](https://github.com/aodstudio/thai-smartcard-reader#install-dependencies). Note that you will need a rooted device to (potentially) be able to use a card reader with termux.
