### ISSUE TITLE
mpv: enable lua support

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#799]
Lua support is [explicitly disabled](https://github.com/termux/termux-packages/blob/master/packages/mpv/build.sh#L22) in mpv, but mpv has a great library of user created scripts that enhance the functionality.
Is there a reason for it to be disabled?
If it's just to keep dependencies small maybe we can have a mpv-lua subpackage (like vim-python).

**Comment by atomi** [comment]
related to #599

**Comment by fornwall** [comment]
The latest update of the mpv package, version 0.24.0-3, has lua support enabled. I haven't tried it myself - does it work ok?

**Comment by Neo-Oli** [comment]
Doesn't seem to work yet. 
```
$ mpv
[osc] Only Lua 5.1 and 5.2 are supported.
[osc] Could not load lua script @osc.lua
[ytdl_hook] Only Lua 5.1 and 5.2 are supported.
[ytdl_hook] Could not load lua script @ytdl_hook.lua
[navigator] Only Lua 5.1 and 5.2 are supported.
[navigator] Could not load lua script /data/data/com.termux/files/home/.config/mpv/scripts/navigator.lua
```
Seems mpv doesn't [support lua 5.3.x](https://github.com/mpv-player/mpv/blob/master/player/lua.c#L374) yet   and does so on [purpose](https://github.com/mpv-player/mpv/commit/9b59c175e389e0a0561312139c0861eba37e4719). https://github.com/mpv-player/mpv/issues/1729

It seems that there is a rift in the Lua language and maybe we should add lua 5.2 to the repository (similar to python2)

**Comment by Neo-Oli** [comment]
Maybe it would be better to disable LUA support again until a solution is found.

**Comment by vishalbiswas** [comment]
@Neo-Oli it was already disabled in https://github.com/termux/termux-packages/commit/f53cdcbe4cc1ebd56528a8cad61f69fb38002695

**Comment by Neo-Oli** [comment]
@vishalbiswas Ah, I see. But the package has not been version bumped and rebuilt since. The version in the repository still has Lua.

**Comment by fornwall** [comment]
@Neo-Oli Thanks, I've bumped the mpv revision now with the lua removal.

As for solving the issue, if there is no plan in having lua 5.3 supported in mpv, perhaps we can build and link lua 5.2 statically as part of mpv? The lua code is rather small to embed inline, and as long as no more package uses older lua versions we don't need it as a separate package with a shared library.

**Comment by xeffyr** [comment]
I have enabled Lua support for [x11-packages/mpv-x](https://github.com/termux/x11-packages/tree/master/packages/mpv-x).
Liblua v5.2 currently located in [x11-packages/liblua52](https://github.com/termux/x11-packages/tree/master/packages/liblua52).

**Comment by xeffyr** [comment]
Closing since Lua support is enabled on master (android-7) branch.

**Comment by 5c0tt-b0t** [comment]
@xeffyr @Neo-Oli I have no problems running lua scripts for mpv, but I cant run javascript ones. Is it possible to use javascript like I can with lua? I saw mpv can be compiled with or without javascript/lua support so was wondering if it was compiled to use one, not the other?
