### ISSUE TITLE
[Package]: update tsu to version 8.6.0

### ISSUE THREAD

**Issue by Mark-Joy** [termux/termux-packages#7999]
### Package description

`tsu` is already presented in Termux repositories as version 8.5.1
It is version 8.6.0 from May-31-2020, which supports 'sudo -E' option.
I already asked them to do [an official release tag](https://github.com/cswl/tsu/issues/85) on Sep-21 but there is no answer.

So can we directly update `tsu` to 8.6.0 on Termux repo? 

### Home page URL

https://github.com/cswl/tsu

### Source code URL

https://github.com/cswl/tsu

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by RuddroDewan1994** [comment]
Setting up tsu (8.6.0-1)
