### ISSUE TITLE
In ubuntu-setup.sh, curl should be added as a dependency

### ISSUE THREAD

**Issue by ttsiodras** [termux/termux-packages#8]
You are using it to fetch the sources, but haven't installed it during `ubuntu-setup.sh`.

**Comment by ttsiodras** [comment]
Other than that, the install of the build toolchain went without a hitch for me - I just did my first successful compilation (`build-package.sh file`). 

I am now trying to build a package (i.e. a `build.sh` file) for ffmpeg :-)

Many thanks for your excellent work.

**Comment by fornwall** [comment]
Thanks a lot!
