### ISSUE TITLE
Package request: ghc (Glasgow Haskell Compiler)

### ISSUE THREAD

**Issue by 0Petya** [termux/termux-packages#80]
It would be very nice if we could get <a href="https://www.haskell.org/ghc/">GHC</a> with this.

**Comment by sleibrock** [comment]
As far as I know, GHC doesn't support Termux's LLVM.
https://github.com/termux/termux-packages/commit/94fc63465bbc476ff7a2fb03fd7efe8d37e0438a

**Comment by Oh-Petya** [comment]
Well that's really unfortunate...

**Comment by fornwall** [comment]
The next version of ghc [seems to be using llvm 3.7](https://ghc.haskell.org/trac/ghc/ticket/10953), which seems to be planned for _[Release candidate by mid-December 2015. Release in January 2016](https://ghc.haskell.org/trac/ghc/wiki/Status/GHC-8.0.1)_.

**Comment by Oh-Petya** [comment]
Oh man. I hope you can get it then. It would be amazing to have portable GHC in my pocket at all times.

**Comment by Neo-Oli** [comment]
Hi, I am re-opening this issue. Package requests will now be labeled and tracked as an issue.

**Comment by Luke-Nukem** [comment]
I second this request. It would be a lovely tool to have on the go :+1:

**Comment by goodmind** [comment]
:+1:

**Comment by kozross** [comment]
Consider me a third for this request. Really wanna have an on-the-go GHCi especially.

**Comment by 5hubh4m** [comment]
I would love to have ghc on my phone and tablet. Please consider doing this.

**Comment by robertkluin** [comment]
I am attempting to build 7.10.3 using the Docker build method.  Has anyone made it past the iconv portion of the build?

**Comment by fornwall** [comment]
I've updated the disabled ghc package at

https://github.com/termux/termux-packages/tree/master/disabled-packages/ghc

That is probably the best starting point. Start by building the dependencies:

    for p in libandroid-support libgnustl ncurses clang; do ./build-package.sh $p; done

Then try to build the ghc package with

    ./build-package.sh disabled-packages/ghc

Modify the `build.sh` file in `disabled-packages/ghc` and patch files as needed. I have left a note with the current status where the build fails at the top of `disabled-packages/ghc/build.sh`.

**Comment by dasie** [comment]
I'm very interested as well !!
I want to change my android device in quantum simulator !! http://www.mathstat.dal.ca/~selinger/quipper/

**Comment by linuxcaffe** [comment]
I would very much like to have hledger (http://hledger.org) running in termux. Would it be possible to run a compiled binary in termux, even without ghc? Currently, the "easy way" to install hledger (and hledger-ui, and hledger-web) is using stack.. does this make it any more feasible?

**Comment by fwrs** [comment]
I'd like to mention that debian repositories contain ghc precompiled for arm64 which can be ran using application called 'GNURoot'

**Comment by wende** [comment]
Love the idea. I'd like to know what's the current status on this?

**Comment by jajpater** [comment]
Wow, I'd like to git-annex

**Comment by kozross** [comment]
There are now [binary cross-compiler distributions][1] for GHC, which might be a thing that we could use.

[1]: http://hackage.mobilehaskell.org/

**Comment by vatsman** [comment]
any updates on this?
right now i'm using [android-termux-hugs](https://github.com/trenttobler/android-termux-hugs) to use Haskell but its missing quite a lot of functionality that GHC/GHCi provides.

**Comment by viking66** [comment]
Thanks to @t184256 and his [script](https://github.com/t184256/nix-in-termux) for running nix in termux, I was able to get GHC running. Once you have nix available, you can run ```nix run nixpkgs.haskellPackages.ghc``` to get shell with GHC/GHCi.

**Comment by pianycist** [comment]
Has there been any progress on the possibility of fontforge in termux? It can be compiled without X, and many of its dependencies are flexible, according to the documentation.

**Comment by k1m190r** [comment]
Used Debian installed with a command from: "AndroNix - Linux on Android without root". Once installed `./start-ubuntu.sh`  then `apt-get install ghc` and voila `gchi` available.

**Comment by xeffyr** [comment]
Package is now available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install ghc
```

Available only for AArch64 currently.

Thanks to @qwerty12.
