### ISSUE TITLE
Three Step Create

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#800]
If I can run ./configure, make and then create the package through the termux-create-package script, does it mean that I can submit it to pull request? Thanks.

**Comment by mklein994** [comment]
**Short answer**: no.

**Long answer**: kind of. It's good that it compiles directly on the device, but that creates a compiled package; the build scripts describe the instructions to reproduce that. The build.sh scripts found in [packages](https://github.com/termux/termux-packages/tree/master/packages) are designed to be cross-compiled from a Linux-based PC using a patched Android NDK (See the [README](https://github.com/termux/termux-packages/tree/master/README.md) for details). If you want to know what's going on under the hood, take a look at [build-package.sh](build-package.sh). Feel free to ask questions on [Gitter](https://gitter.im/termux/termux).

**Comment by Wetitpig** [comment]
So patch files may still be required?

**Comment by Neo-Oli** [comment]
> So patch files may still be required?
If it compiles fine on Termux with ./configue;make it is likely that it won't require any additional patches. So you'd just have to write a minimal build.sh (like the [bs1770gain](https://github.com/termux/termux-packages/tree/master/packages/bs1770gain) package for example). You can then test it (on a linux machine) with `./scripts/run-docker.sh ./build-package.sh <your package name>`. You can then copy the *.deb file of your package in the `./debs` directory to your termux and install it with `apt install ./<package>.deb`. If it works you can submit the `build.sh` as a pull request.

**Comment by Wetitpig** [comment]
But I only have at most ubuntu 16.04

**Comment by Neo-Oli** [comment]
That is fine. You just need to install docker (`sudo apt install docker.io`). You could do this on any System where docker runs. The `./scripts/run-docker.sh` will set up a jailed ubuntu 16.10, install all the libraries and set up the build environment (in a virtual-machine like image) and build your package.

**Comment by Wetitpig** [comment]
Ok. Thanks. I will try first.
