### ISSUE TITLE
x11-repo package: libgl1-mesa-dev

### ISSUE THREAD

**Issue by masterjavaofficial** [termux/termux-packages#8005]
### Package description

I saw another issue created 2 years back on the same package, and two packages named libglu and libglu-dev was [added](https://github.com/termux/termux-packages/issues/2019#issuecomment-423941880) in response to that. But where are those now? I can't find them using apt.

### Source code URL

*

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

*

**Comment by xtkoba** [comment]
I believe it is now named <a href="https://github.com/termux/x11-packages/tree/master/packages/glu/">glu</a>.

**Comment by masterjavaofficial** [comment]
> I believe it is now named [glu](https://github.com/termux/x11-packages/tree/master/packages/glu/).

Ahh, you saved my day.
