### ISSUE TITLE
[BUG] Clang crashes with return code 1 

### ISSUE THREAD

**Issue by pokemaniac05** [termux/termux-packages#8007]
## Problem description 
Every time I run `clang` or `aarch64-linux-android-clang` (or their `cc`/`gcc` equivalents) with or without arguments, I get exit code 1 and the following output in `stderr`:`CANNOT LINK EXECUTABLE "clang": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...` I tried to install gcc using an unofficial repo, but I can't install a lot of python modules that rely on clang (using python installed with `pkg install python` from this repo). So I would like that this bug were resolved. 
## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.117`  
**VERSION_CODE**: `117`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

## Termux:API App Info

**APP_NAME**: `Termux:API`  
**PACKAGE_NAME**: `com.termux.api`  
**VERSION_NAME**: `0.49`  
**VERSION_CODE**: `49`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

## Termux:Boot App Info

**APP_NAME**: `Termux:Boot`  
**PACKAGE_NAME**: `com.termux.boot`  
**VERSION_NAME**: `0.7`  
**VERSION_CODE**: `7`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

## Termux:Float App Info

**APP_NAME**: `Termux:Float`  
**PACKAGE_NAME**: `com.termux.window`  
**VERSION_NAME**: `0.14`  
**VERSION_CODE**: `14`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

## Termux:Styling App Info

**APP_NAME**: `Termux:Styling`  
**PACKAGE_NAME**: `com.termux.styling`  
**VERSION_NAME**: `0.29`  
**VERSION_CODE**: `29`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

## Termux:Widget App Info

**APP_NAME**: `Termux:Widget`  
**PACKAGE_NAME**: `com.termux.widget`  
**VERSION_NAME**: `0.12`  
**VERSION_CODE**: `12`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.14.116`  
**SDK_INT**: `29`  
**RELEASE**: `10`  
**ID**: `HUAWEIART-L29`  
**DISPLAY**: `ARTH-L29 10.1.0.217(C432E2R2P1)`  
**INCREMENTAL**: `10.1.0.217C432`  
**SECURITY_PATCH**: `2020-10-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `HUAWEI`  
**BRAND**: `HUAWEI`  
**MODEL**: `ART-L29`  
**PRODUCT**: `ART-L29`  
**BOARD**: `ART-L29`  
**HARDWARE**: `kirin710`  
**DEVICE**: `HWART-H`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`

**Comment by Grimler91** [comment]
Upgrade tour packades, `pkg upgr`
