### ISSUE TITLE
[Bug]: I would like syncthing to start it at startup

### ISSUE THREAD

**Issue by free-150** [termux/termux-packages#8018]
### Problem description

hi
I would like syncthing to start it at startup. I have tried to do it as the documentation said  
#5122
But it doesn't work
Things I've made sure to do:
-  I installed both Termux and Termux:Boot from F-Droid.
- Click the Termux:Boot launcher to "activate" it.
- `chmod u+x ~/.termux/boot/start-syncthing`&`chmod u+x $PREFIX/var/service/syncthing/run`
- Added both Termux and Termux:Boot to the "No battery optimizations" list,  

I would then create an executable script at $PREFIX/var/service/syncthing/run with the content
```sh
#!/data/data/com.termux/files/usr/bin/sh

syncthing -logflags 0 2>&1
```
Create the ~/.termux/boot/ directory.
Put `start-syncthing`scripts you want to execute inside the ~/.termux/boot/ directory
```sh
#!/data/data/com.termux/files/usr/bin/sh
source /data/data/com.termux/files/usr/etc/profile.d/start-services.sh
```

### What steps will reproduce the bug?

i would like syncthing to start it at startup

### What is the expected behavior?

i would like syncthing to start it at startup

### System information

termux-info:

```
Termux application version: 0117
Termux:boot version: 0.7
Android OS version:11
Device model:MI9 MIUI12.5
```

**Comment by agnostic-apollo** [comment]
An issue on termux/termux-boot#71, a discussion in termux-packages #8017 and now another issue! What the hell is wrong with you?
