### ISSUE TITLE
xdg-open crashes termux when url is used

### ISSUE THREAD

**Issue by atomi** [termux/termux-packages#802]
termux 0.47

ie:    
```
xdg-open 'https://www.youtube.com/watch?v=DekuSxJgpbY'
```

**Comment by its-pointless** [comment]
same here...

**Comment by vishalbiswas** [comment]
Seems like a problem with parsing the data in the intent by Termux::API
`logcat | grep termux` -> http://pastebin.com/E9vHTuRU

**Comment by fornwall** [comment]
Thanks!

The issue affected all Android versions earlier than 7.0 when opening an URL, fixed in version 0.48 (commit https://github.com/termux/termux-app/commit/11ed7e45d8df561c246fb12c356e0bb11aeda812) which should be available as an update shortly.
