### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by weishaofei** [termux/termux-packages#8037]
### Problem description

Building wheel for cryptography (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /data/data/com.termux/files/usr/bin/python /data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /data/data/com.termux/files/usr/tmp/tmpb746pjig
       cwd: /data/data/com.termux/files/usr/tmp/pip-install-swglmmmn/cryptography_970da5ae59ec421fb7060d4d06f52806
  Complete output (156 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv8l-3.10
  creating build/lib.linux-armv8l-3.10/cryptography
  copying src/cryptography/__about__.py -> build/lib.linux-armv8l-3.10/cryptography
  copying src/cryptography/__init__.py -> build/lib.linux-armv8l-3.10/cryptography
  copying src/cryptography/exceptions.py -> build/lib.linux-armv8l-3.10/cryptography
  copying src/cryptography/fernet.py -> build/lib.linux-armv8l-3.10/cryptography
  copying src/cryptography/utils.py -> build/lib.linux-armv8l-3.10/cryptography
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat
  copying src/cryptography/hazmat/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat
  copying src/cryptography/hazmat/_oid.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat
  creating build/lib.linux-armv8l-3.10/cryptography/x509
  copying src/cryptography/x509/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/x509
  copying src/cryptography/x509/base.py -> build/lib.linux-armv8l-3.10/cryptography/x509
  copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-armv8l-3.10/cryptography/x509
  copying src/cryptography/x509/extensions.py -> build/lib.linux-armv8l-3.10/cryptography/x509
  copying src/cryptography/x509/general_name.py -> build/lib.linux-armv8l-3.10/cryptography/x509
  copying src/cryptography/x509/name.py -> build/lib.linux-armv8l-3.10/cryptography/x509
  copying src/cryptography/x509/ocsp.py -> build/lib.linux-armv8l-3.10/cryptography/x509
  copying src/cryptography/x509/oid.py -> build/lib.linux-armv8l-3.10/cryptography/x509
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/backends
  copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends
  copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings
  copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/_asymmetric.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/_cipheralgorithm.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/_serialization.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ed25519.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ed448.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/poly1305.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/x448.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/backends/openssl
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings/openssl
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/types.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/asymmetric
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/ciphers
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/kdf
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/pkcs7.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/serialization
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-armv8l-3.10/cryptography/hazmat/primitives/twofactor
  running egg_info
  writing src/cryptography.egg-info/PKG-INFO
  writing dependency_links to src/cryptography.egg-info/dependency_links.txt
  writing requirements to src/cryptography.egg-info/requires.txt
  writing top-level names to src/cryptography.egg-info/top_level.txt
  reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs/_build'
  warning: no previously-included files found matching 'vectors'
  warning: no previously-included files matching '*' found under directory 'vectors'
  warning: no previously-included files matching '*' found under directory '.github'
  warning: no previously-included files found matching 'release.py'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'dev-requirements.txt'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files found matching 'mypy.ini'
  warning: no previously-included files matching '*' found under directory '.zuul.d'
  warning: no previously-included files matching '*' found under directory '.zuul.playbooks'
  adding license file 'LICENSE'
  adding license file 'LICENSE.APACHE'
  adding license file 'LICENSE.BSD'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
  copying src/cryptography/py.typed -> build/lib.linux-armv8l-3.10/cryptography
  creating build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-armv8l-3.10/cryptography/hazmat/bindings/_rust
  running build_ext
  running build_rust
  
      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation/ for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq/
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation/#rust
  
      Python: 3.10.0
      platform: Linux-4.9.190-perf-g1aba9b2-armv8l-with-libc
      pip: n/a
      setuptools: 59.2.0
      setuptools_rust: 1.0.0
      =============================DEBUG ASSISTANCE=============================
  
  error: Don't know the correct rust target for system type arm-unknown-linux-androideabi. Please set the CARGO_BUILD_TARGET environment variable.
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

### What steps will reproduce the bug?

pip install cryptography

### System information

Application version:
0.114
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/termux-packages-24 stable main
# game-repo (sources.list.d/game.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.190-perf-g1aba9b2 #1 SMP PREEMPT Mon Aug 2 23:19:47 CST 2021 armv8l Android
Device manufacturer:
Xiaomi
Device model:
M2006C3LC

**Comment by Grimler91** [comment]
> error: Don't know the correct rust target for system type arm-unknown-linux-androideabi

Do you have rust installed?

**Comment by weishaofei** [comment]
yes I installed

pkg install rust

**Comment by sk0kanik** [comment]
Try this:
run `rustc -vV`
example output:

 rustc 1.56.1
 binary: rustc
 commit-hash: unknown
 commit-date: unknown
 host: aarch64-linux-android
 release: 1.56.1
 LLVM version: 13.0.0

here, aarch64-linux-android is rust target in this case. It may be different for you. then use it and run
`export CARGO_BUILD_TARGET=aarch64-linux-android && pip install cryptography`

**Comment by xtkoba** [comment]
I guess the target should be `armv7-linux-androideabi` for arm.

**Comment by weishaofei** [comment]
> I guess the target should be `armv7-linux-androideabi` for arm.

You are amazing!
I run rustc -vV in my another device and it is armv7-linux-androideabi
rustc 1.56.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: armv7-linux-androideabi
release: 1.56.1
LLVM version: 13.0.0

then I run 
export CARGO_BUILD_TARGET=armv7-linux-androideabi && pip install cryptography
It works,too.

**Comment by sk0kanik** [comment]
@weishaofei could you close this issue?

**Comment by Dan1jel** [comment]
> Try this:
> run `rustc -vV`
> example output:
> ```
>  rustc 1.56.1
>  binary: rustc
>  commit-hash: unknown
>  commit-date: unknown
>  host: aarch64-linux-android
>  release: 1.56.1
>  LLVM version: 13.0.0
> ```
> here, aarch64-linux-android is rust target in this case. It may be different for you. Use it and run
> `export CARGO_BUILD_TARGET=aarch64-linux-android && pip install cryptography`

Wow thank you so much, don't know how long I've been looking for this answer. This solved my issue with Cryptography, huge thanks!
