### ISSUE TITLE
Programms linked to libx265 stopped working after last update (ffmpeg)

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#804]
ffmpeg and programms depending on ffmpeg (I've found mpv and bs1770gain) aren't working anymore after the update of libx265 (https://github.com/termux/termux-packages/commit/8a778f708c3243ef7e4fd7a164ee860e1eb2ad50). 
```
$ ffmpeg -v
CANNOT LINK EXECUTABLE "ffmpeg": cannot locate symbol "x265_api_get_102" referenced by "/data/data/com.termux/files/usr/lib/libavcodec.so"...
zsh: abort (core dumped)  ffmpeg -v
134 $ bs1770gain -v
CANNOT LINK EXECUTABLE "bs1770gain": cannot locate symbol "x265_api_get_102" referenced by "/data/data/com.termux/files/usr/lib/libavcodec.so"...
zsh: abort (core dumped)  bs1770gain -v
134 $ mpv -v
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/mpv": cannot locate symbol "x265_api_get_102" referenced by "/data/data/com.termux/files/usr/lib/libavcodec.so"...
Aborted (core dumped)

```

**Comment by fornwall** [comment]
Thanks! Seems libx265 updates are not binary compatible. I`ve bumped the ffmpeg package revision and rebuilt ffmpeg now.

The latest version `3.2.4-1` of ffmpeg, now available in the repo, should fix the issue!

**Comment by nico202** [comment]
Hi, I get
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/ffmpeg": cannot locate symbol "x265\
_api_get_116" referenced by "/data/data/com.termux/files/usr/lib/libavcodec.so"...

**Comment by fornwall** [comment]
@nico202 Thanks, I'm rebuilding ffmpeg now and will push an update shortly, hold on...

**Comment by fornwall** [comment]
@nico202 It should be fixed now after you update the installed packages!

**Comment by nico202** [comment]
Yes! Thanks:)

Il 15 luglio 2017 15:22:23 CEST, Fredrik Fornwall <notifications@github.com> ha scritto:
>@nico202 It should be fixed now after you update the installed
>packages!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/termux/termux-packages/issues/804#issuecomment-315533707

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.
