### ISSUE TITLE
[Package]: myMPD

### ISSUE THREAD

**Issue by sandorex** [termux/termux-packages#8051]
### Package description

Web interface for mpd, there is no GUIs for mpd in the package repository and this seems like most modern one and hasn't been that hard to get to work properly

### Home page URL

https://jcorporation.github.io/myMPD

### Source code URL

https://github.com/jcorporation/myMPD

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I have compiled and ran it successfully on a aarch64 device
The full details can be found in the discussion https://github.com/jcorporation/myMPD/discussions/612

I have fixed lua option with help from the author so it has no problems running in termux but it does require `devel` branch at the moment (rel commit https://github.com/jcorporation/myMPD/commit/791e12ffacda6ced0a08602890f43fb7c0f62ea9)

**Comment by jcorporation** [comment]
I am the author of myMPD if I can help don't hesitate to conact me.

**Comment by tathastu871** [comment]
> I am the author of myMPD if I can help don't hesitate to conact me.

getent not found
