### ISSUE TITLE
[Package]: pass-otp / pass-extension-otp

### ISSUE THREAD

**Issue by webctrl** [termux/termux-packages#8056]
### Package description

A pass (https://www.passwordstore.org/) extension for managing one-time-password (OTP) tokens.

Allows two-factor identification (2FA) codes to be generated in Termux instead of using another app like 'Google Authenticator'.

### Source code URL

https://github.com/tadfisher/pass-otp

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Is something wrong with the [pass-otp package](https://github.com/termux/termux-packages/tree/master/packages/pass-otp) we already have?

**Comment by webctrl** [comment]
Now I feel very stupid. I did look (twice). I'm going to blame lack of sleep.

Sorry.
