### ISSUE TITLE
[Bug]: pass-otp "this version of `which' is deprecated"

### ISSUE THREAD

**Issue by webctrl** [termux/termux-packages#8057]
### Problem description

When running the command "pass otp" the following error is displayed :

"/data/data/com.termux/files/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead."

Also "pass otp --version" returns 1.1.1 (on Termux, but also on Arch Linux), however the latest release seems to be 1.2.0 (2018-11-15). I'm guessing this is a mistake in pass-otp itself rather than this package?

### What steps will reproduce the bug?

Run command "pass otp"

### System information

termux-info:

```
Application version:
0.114
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.146+ #1 SMP PREEMPT Thu Oct 7 02:04:32 UTC 2021 armv8l Android
Device manufacturer:
Amazon
Device model:
KFMAWI
```

**Comment by xeffyr** [comment]
That's an issue of utility `which` that was deprecated in debianutils package upstream.
