### ISSUE TITLE
Package request: microphone access

### ISSUE THREAD

**Issue by vlad3-3-3** [termux/termux-packages#806]
Is there any way to access the Android microphone? Why is the alsa-lib disabled (it should contain arecord..)?

**Comment by vishalbiswas** [comment]
arecord is in alsa-utils
kernel-space alsa support seems to be missing from the Android kernel (at least from mine). That's why the package is disabled and will probably be removed as it was only added as a dependency for openjdk-9

**Comment by vlad3-3-3** [comment]
So is there any other way to access the microphone? Maybe through the termux-api? (should I ask there?)

**Comment by fornwall** [comment]
@vlad3-3-3 It should be possible to write a command line app using OpenSL ES (the native audio api on android) to record audio. It's not done yet as people don't normally use Android on the command line :), but if anyone wants to help out perhaps this link can be useful: https://audioprograming.wordpress.com/2012/03/03/android-audio-streaming-with-opensl-es-and-the-ndk/

**Comment by fornwall** [comment]
Closing this. For termux-api features, see

- https://github.com/termux/termux-api/issues/74 for recording to a file
- https://github.com/termux/termux-api/issues/55 for streaming audio
