### ISSUE TITLE
[Bug]: Aria2 cannot access SD card

### ISSUE THREAD

**Issue by geol** [termux/termux-packages#8062]
### Problem description

aria2 cant download files to SD card while the permission to SD card was granted. please check the picture.
![Screenshot_20211126-034037_Termux~01](https://user-images.githubusercontent.com/2117430/143495086-62c3f0d6-2736-449e-96e6-554994dda55a.png)

### What steps will reproduce the bug?

add a magnet link on webui, after seconds it stop downloading and said the dir was read-only system.
![Screenshot_20211126-040013_浏览器~01](https://user-images.githubusercontent.com/2117430/143495417-16500598-9e91-4f13-baf9-bfd64b409f1d.png)

### System information

termux-info:

```

```
Application version:                                                                         0.117
Packages CPU architecture:                                                                   arm                                                                                          Subscribed repositories:                                                                     # sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/termux-packages-24 stable main               # game-repo (sources.list.d/game.list)                                                       deb https://mirrors.tuna.tsinghua.edu.cn/termux/game-packages-24 games stable                # science-repo (sources.list.d/science.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/science-packages-24 science stable           Updatable packages:                                                                          All packages up to date                                                                      Android version:
10                                                                                           Kernel build information:                                                                    Linux Galaxy-TabPro 3.4.113-g03a5349a4fd0 #1 SMP PREEMPT Tue Jan 14 22:24:48 +03 2020 armv7l Android
Device manufacturer:                                                                         samsung                                                                                      Device model:                                                                                SM-T320

**Comment by Grimler91** [comment]
Is `$HOME` expanded by aria2? Does it work if you put `/data/data/com.termux/files/home` instead in your config?

**Comment by geol** [comment]
> Is `$HOME` expanded by aria2? Does it work if you put `/data/data/com.termux/files/home` instead in your config?

Thank you for reminding, now all the problems solved.
