### ISSUE TITLE
[Package]: aMule

### ISSUE THREAD

**Issue by geol** [termux/termux-packages#8063]
### Package description

i cant find some other downloaders on android can download e2dk link and i just need it.

### Home page URL

http://www.amule.org/

### Source code URL

https://sourceforge.net/projects/amule/files/aMule/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
aMule depends on wxWidgets without which no interface is built.

wxWidgets is not yet packaged, but seems to be buildable: https://github.com/termux/x11-packages/issues/112

**Comment by geol** [comment]
> aMule depends on wxWidgets without which no interface is built.
> 
> wxWidgets is not yet packaged, but seems to be buildable: [termux/x11-packages#112](https://github.com/termux/x11-packages/issues/112)

too difficult for me, but thank you!

**Comment by hqy6** [comment]
Please add it, it is very useful.
