### ISSUE TITLE
[Bug]: Unable to fully install or remove a file

### ISSUE THREAD

**Issue by H1DD3N-M0NK3Y** [termux/termux-packages#8067]
### Problem description

This is going to be the first time I'm gonna do anything on GitHub so, sorry in advance if anything seems missing or too less info is being provided. So, every time I run PKG updat or PKG upgrade, there is one file from a GitHub clone that neither gets fully installed or removed. Each time, it says error 404 when it sends an HTTP request and "Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code" appears at the end. This causes trouble updating other packages like python. I had cloned the wrong repo by mistake, and since then this issue appears.
![Screenshot_20211126-194653~2](https://user-images.githubusercontent.com/95088389/143594454-37357997-49b6-4f54-8cb4-f689992711ff.png)

### What steps will reproduce the bug?

Running PKG updated or PKG upgrade.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# sources.list.d/gushmazuko.list
deb https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
7.1.1
Kernel build information:
Linux localhost 3.18.41+ #1 SMP PREEMPT Mon Dec 25 10:00:59 CST 2017 aarch64 Android
Device manufacturer:
lenovo
Device model:
Lenovo K8 Note

```

**Comment by Grimler91** [comment]
Seems something is wrong with the msf package that you have installed from a non-official repo. Uninstall the package (and perhaps unsubscribe from the repo) to solve it
