### ISSUE TITLE
Laravel error because new package php 8.1 

### ISSUE THREAD

**Issue by bhiantara** [termux/termux-packages#8071]
### Problem description

![IMG_20211127_103153](https://user-images.githubusercontent.com/28755414/143665503-28ec4d0e-3f3f-4abf-9ec4-e7c27a842ef0.jpg)
Today i got problem on my laravel project because update pakage from php 8.0 => php 8.1
how to downgrade php 8.0 or please roleback update package to 8.0 again. Because the php 8.1 have some problem with framework.

### What steps will reproduce the bug?

During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible w
  ith ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange]

### System information

termux-info:

```
During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible w
  ith ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange]

```

**Comment by sk0kanik** [comment]
Note: You can still install php 8.0 from [github artifacts](https://github.com/termux/termux-packages/actions/runs/1492293861). Termux is a rolling distro and it is recommended [to backup termux](https://wiki.termux.com/wiki/Backing_up_Termux) before package upgrade.

**Comment by sk0kanik** [comment]
Note: You can still install php 8.0 from [github artifacts](https://github.com/termux/termux-packages/actions/runs/1492293861). Termux uses rolling-release and it is recommended to [backup termux](https://wiki.termux.com/wiki/Backing_up_Termux) before package upgrade.

**Comment by bhiantara** [comment]
> Note: You can still install php 8.0 from [github artifacts](https://github.com/termux/termux-packages/actions/runs/1492293861). Termux uses rolling-release and it is recommended to [backup termux](https://wiki.termux.com/wiki/Backing_up_Termux) before package upgrade.

finally, thankyou.
