### ISSUE TITLE
[Bug]: InRelease is not valid yet

### ISSUE THREAD

**Issue by zgh-yuanshang** [termux/termux-packages#8077]
### Problem description

E:Release file for https://packages.termux.org/apt/termux-main/dists/stable/InRelease is not valid yet (invalid for another 2d 11h 47min 23s). Updates for this repository will not be applied

### What steps will reproduce the bug?

pkg upgrade or any install

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Works fine here, sounds like the time&date settings on your device might be wrong?

**Comment by zgh-yuanshang** [comment]
@Grimler91 Thank you. I just swiped my phone. I had a problem synchronizing time

**Comment by h93910** [comment]
yeah man , synchronizing time resolve this
