### ISSUE TITLE
Install package on external storage (sdcard)

### ISSUE THREAD

**Issue by rornor** [termux/termux-packages#808]
Hi,

on Android 6 I formatted my sdcard to be used as internal storage. This feature is far from clear to me, but  Termux is installed in internal memory, w/o ability to move it to external storage, like other regular apps. I can move Termux:Api or Termux:Widget to external storage, but not Termux itself.
Installing packages just extends the amount of memory Termux uses in internal storage.

I've read https://termux.com/storage.html and run the command `termux-setup-storage` to enable these permissions.

Now I'm wondering two things:

1. Can I instruct Termux to use external storage for packages?
2. Can I install Python package in external storage? For example I tried `pip install package --user` but I still get this into external memory storage.

Thanks :)

**Comment by Wetitpig** [comment]
According to my understanding, no programs can be executed on external storage. Therefore, no packages can be installed in external storage.

Check this: http://android.stackexchange.com/questions/50775/android-shell-script-permissions

**Comment by rornor** [comment]
It seems that the question in the link refers to regular portable sdcard install, but I guess same applies for sdcard formatted as internal storage. 

In the meantime I created directory "python" in my sdcard home, then:

```
user@localhost:~/storage$ ln -s /storage/emulated/0/python python
user@localhost:~/storage$ export PYTHONUSERBASE=~/storage/python
user@localhost:~/storage$ pip install requests --user
```

resulting in:

```
Collecting requests
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 211kB/s
Installing collected packages: requests
Exception:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pip/wheel.py", line 329, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
PermissionError: [Errno 1] Operation not permitted
```

**Comment by DoktorStein** [comment]
External sdcard is mounted with -noexec flag, so it cannot exec/preserve times of files, even if the file is chmod'ed with x flag. If the device is rooted, try remounting without -noexec.

**Comment by rornor** [comment]
Device is not rooted. I was trying to reach boundaries, after I realized that I can even install numpy and jupyter on my phone. So that's it I guess. More then enough, even for those with low internal memory

**Comment by navix78** [comment]
how to download python3.6 for termux?

**Comment by vishalbiswas** [comment]
@navix78 `pkg install python` will install python3.6 and `pkg install python2` will install python2.7
