### ISSUE TITLE
Package Request: Csol

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#8080]
Package description

Csol is a superset of card games. It includes several modalities like tty-solitaire, klondike, eightoff, freecell ... tty-solitaire is a package already available, but it had problems in some devices with respect to the display of utf-8 characters. Csol "solves this problem" with the $ csol -t ascii option.

Link to sources

Source code: https://github.com/nielssp/csol

Additional information
The program compiled nomatically and worked with some visualization bugs depending on the chosen modality.

I used only the default instructions for compiling.

cmake.
make
./csol

**Comment by xtkoba** [comment]
Yeah, we see `ncurses` non-ASCII characters issues here and there. Forcing (or defaulting to) `-t ascii` option sounds like a nice workaround.
