### ISSUE TITLE
Cavez-of-phear weirdness

### ISSUE THREAD

**Issue by Quasic** [termux/termux-packages#8081]
**Problem description**
Similar to termux/termux-packages#2900, when I run phear, it repeats keystrokes, so after pressing right, the character goes right until it hits the wall. Upon exiting, it runs commands from bash history.

**Steps to reproduce**
Also similar to termux/termux-packages#2900, this may very well be unconfirmed by others.

**Expected behavior**
When I play on another device, it doesn't repeat keystrokes or bash commands.

**Additional information**
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.35 termux/game-packages#1 SMP PREEMPT Thu Oct 11 15:07:31 CST 2018 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.2
Device manufacturer:
LGE
Device model:
LG-SP200

This device is 64 bit without /system/lib64

I might try to get strace, logcat, etc. after setting up something of a sandbox...

**Comment by xtkoba** [comment]
Smells similar to #2497 in that `ncurses` does not handle non-ASCII characters correctly on Android 7 (or earlier). May be a red herring of course, but...

**Comment by Quasic** [comment]
I did have that problem with ttysolitaire, before the patch, IIRC.

**Comment by Quasic** [comment]
I tried mdp with the sample, and it also doesn't display the Unicode on this device.

**Comment by Quasic** [comment]
The game seems better, but it still repeats keystrokes and runs bash commands in version 0.5.3-3. I had a similar issue happen on an unrelated system when I tried to paste a multiline bash command into a terminal. It mangled the command, then started running commands from history. I hope the game works for others.

**Comment by Quasic** [comment]
I found another update available and tried it. It shows an opening screen, now. I discovered that it doesn't get the commands it tries to run from.bash_history, but from some kind of keyboard buffer. It's fairly playable, albeit challenging, as long as I close it with SIGINT (Ctrl+C) so it doesn't replay the keyboard buffer.
