### ISSUE TITLE
Package Req | Hollywood Terminal 1.6 | find a Workaround

### ISSUE THREAD

**Issue by roshanravan** [termux/termux-packages#809]
Can you please add this package:
https://www.bleepingcomputer.com/forums/t/562363/hollywood-terminal-16-impress-your-friends/

**Comment by roshanravan** [comment]
Is it even possible to run byobu on Termux?

**Comment by roshanravan** [comment]
for the record this is the workaround, install Ubuntu from this guide: https://wiki.termux.com/wiki/Ubuntu

run Ubuntu in Termux:
./ubuntu_directory/start-ubuntu.sh

Installing Hollywood Terminal:
apt-get update
apt-get install hollywood
follow the installation and options for language, to run hollywood just type hollywood and voi·la you have Hollywood hacker Terminal in your Android Device thanks to Termux

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install hollywood
```

**Comment by roshanravan** [comment]
> Package is now available.
> 
> You can obtain it with these commands:
> 
> ```
> pkg install hollywood
> ```
WoW thanks for the update, 
I actually did wrote a tutorial in xda using Ubuntu:
https://forum.xda-developers.com/general/general/root-fake-hollywood-hacker-screen-termux-t4027429
But the built-in package is much easier,

**Comment by roshanravan** [comment]
Can you also add this package like Hollywood?
https://github.com/yaronn/blessed-contrib

**Comment by xeffyr** [comment]
npm stuff is not subject for packaging.

**Comment by roshanravan** [comment]
> npm stuff is not subject for packaging.
Oh I didn't know, so Even it's not possible to run npm stuff in Ubuntu chroot for Termux?

**Comment by xeffyr** [comment]
Nodejs packages should be installed with `npm` inside Termux. We do not package them in \*.deb for several reasons.
