### ISSUE TITLE
[Package]: Neovim 0.6

### ISSUE THREAD

**Issue by reo101** [termux/termux-packages#8099]
### Package description

Neovim 0.6 released.
[https://github.com/neovim/neovim/releases/tag/v0.6.0](https://github.com/neovim/neovim/releases/tag/v0.6.0)

Would love to see the termux package updated soon

### Home page URL

https://neovim.io/

### Source code URL

https://github.com/neovim/neovim/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by sk0kanik** [comment]
Already done : f0cad6e . It should be available on repo soon.
