### ISSUE TITLE
Color scheme error while running local package

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#810]
I have a small script which have some colors in it 
I used \e[92;1m to get bold and green text ..
But if I run the script as local package then it just prints the color code without changing text color...

Check this and tell me what should I use instead 
http://pastebin.com/KDnSkyA6

**Comment by Neo-Oli** [comment]
`echo -e` is not posix compliant. Your script probably comes from a system where `sh` is bash. On Termux `sh` is dash, which is more purely posix. Try launching your script with bash by either running `bash <script name>` or by adding `#!/data/data/com.termux/files/usr/bin/bash` on the very first line of the script.

**Comment by Auxilus** [comment]
Ok thanks ...I'll try

**Comment by Auxilus** [comment]
Thanks a lot ...It fixed the issue...
