### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "php": cannot locate symbol "__extenddftf2" referenced by "/data/data/com.termux/files/usr/bin/php"... Aborted

### ISSUE THREAD

**Issue by farhankp1202** [termux/termux-packages#8105]
### Problem description

# Termux

When going to run the PHP program from Termux (when executing the "`$ php`" command) an error occurred which I don't know why, the error message:

`CANNOT LINK EXECUTABLE "php": cannot locate symbol "__extenddftf2" referenced by "/data/data/com.termux/files/usr/bin/php"...`
`Aborted`

PHP version : `8.1.0`

`$ termux-info`

Application version:
`0.117`
Packages CPU architecture:
`aarch64`
Subscribed repositories:
sources.list
`deb https://packages.termux.org/apt/termux-main/ stable main`
science-repo (sources.list.d/science.list)
`deb https://packages.termux.org/apt/termux-science science stable`
game-repo (sources.list.d/game.list)
`deb https://packages.termux.org/apt/termux-games games stable`
Updatable packages:
`All packages up to date`
Android version:
`8.1.0`
Kernel build information:
`Linux localhost 3.18.71-perf-g5c5b6e3 #1 SMP PREEMPT Tue Nov 5 23:37:25 WIB 2019 aarch64 Android`
Device manufacturer:
`Xiaomi`
Device model:
`Redmi 5A`

### What steps will reproduce the bug?

I don't know how to fix it, can you guys help me?

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf-g5c5b6e3 #1 SMP PREEMPT Tue Nov 5 23:37:25 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 5A
```

**Comment by xtkoba** [comment]
Seems like the same as #8029.

**Comment by kekecoder** [comment]
I was having this issue too when I upgraded to the latest release of PHP, it turns out that the Termux version I was using was downloaded from Google playstore, all i did was to uninstalled it, downloaded the latest version from F-Droid, it worked fine for me.
