### ISSUE TITLE
[Bug]: `avahi-daemon` doesn't seem to respect the `--no-drop-root` option completely

### ISSUE THREAD

**Issue by spacehobo** [termux/termux-packages#8111]
### Problem description

Thanks to #65 being closed out, we now have an avahi package that includes a daemon that should not require root to operate.  The standard method for running avahi as a normal user is to use the `--no-drop-root` flag.  

You can see the effect of this at https://github.com/lathiat/avahi/blob/master/avahi-daemon/main.c#L1644

In particular, the function `drop_root()` is not meant to be called if this option is provided on the command line.  However, when I run this under termux, it prints `Failed to find user 'avahi'.` and exits 255.  The `drop_root()` function is the only block of code that could print this error message, indicating that somehow it is not respecting the `--no-drop-root` option on the command line.

### What steps will reproduce the bug?

```
pkg install avahi
avahi-daemon --no-drop-root
```

You should see it complain that it cannot find the user `avahi` (which won't exist in any way `getpwnam()` can find, under termux).

### What is the expected behavior?

A running avahi-daemon, telling the local network that we're localhost.local or similar (depending on configuration).

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.9.290-perf-g3d062cf9c496 #1 SMP PREEMPT Sat Nov 27 04:05:33 UTC 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
POCO F1

```

**Comment by xtkoba** [comment]
Yeah, it is surprising that a package for daemons originally supposed to run as root does not have any patches other than for hardcoded paths.

**Comment by spacehobo** [comment]
I don't think it needs patches, but somehow the binary in the termux archives isn't doing what that code I linked do seems to do.

**Comment by spacehobo** [comment]
As further evidence, if I don't specify `--no-drop-root`, I then get this error message: https://github.com/lathiat/avahi/blob/master/avahi-daemon/main.c#L1597

So why would it pass the `if(config.drop_root)` test only a hundred lines down?

**Comment by xtkoba** [comment]
> it prints `Failed to find user 'avahi'.` and exits 255. The `drop_root()` function is the only block of code that could print this error message,

This is not correct. The `make_runtime_dir()` function also could.
