### ISSUE TITLE
[Package]: apkeep

### ISSUE THREAD

**Issue by Hainish** [termux/termux-packages#8113]
### Package description

[`apkeep`](https://github.com/EFForg/apkeep) is a command-line tool for downloading APK files from various sources.  Written in async Rust, this tool prioritizes simplicity of use, memory safety, reliability, and speed.  It currently supports downloading apks from the Google Play Store (with credentials), APKPure, and F-Droid.  The project was introduced by EFF in September.

I have it cross-compiling to `aarch64-linux-android` and `armv7-linux-androideabi`, see https://github.com/EFForg/apkeep/blob/master/build-remote.sh.

### Source code URL

https://github.com/EFForg/apkeep

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Let me package this. So far successfully built on device (Android 8.1.0 aarch64).
