### ISSUE TITLE
locate: can not stat () `/data/data/com.termux/files/usr/var/mlocate/mlocate.db': No such file or directory

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#8115]
Just installed mlocate and I get this:
```
apt install mlocate
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  mlocate
0 upgraded, 1 newly installed, 0 to remove and 166 not upgraded.
Need to get 39.2 kB of archives.
After this operation, 143 kB of additional disk space will be used.
Get:1 https://termux.mentality.rip/termux-packages-24 stable/main arm mlocate arm 0.26-4 [39.2 kB]
Fetched 39.2 kB in 1s (63.9 kB/s)
Selecting previously unselected package mlocate.
(Reading database ... 61363 files and directories currently installed.)
Preparing to unpack .../mlocate_0.26-4_arm.deb ...
Unpacking mlocate (0.26-4) ...
Setting up mlocate (0.26-4) ...
Processing triggers for man (1.14.5-2) ...
 ~  locate lol.js
locate: can not stat () `/data/data/com.termux/files/usr/var/mlocate/mlocate.db': No such file or directory
```

**Comment by xtkoba** [comment]
Try running

```
$ updatedb
```

**Comment by tigran123** [comment]
Isn't it a bad idea? What if the user has 1TB of data with 10 million files? Will the installation complete within a few seconds or take hours? Actually, I was surprised at how fast updatedb does it's job in the recent versions (i.e. in the past 5-10 years or so). I remember it taking many many minutes in the days of IDE disks with 30-40MB/s speed (and even in those days I had many gigabytes of books and now they are counted in terabytes :)

**Comment by Grimler91** [comment]
I am also a bit opposed to automatically generating it, the database anyways have to be updated every now to be reliable, so users need to know about the updatedb command. 

This isn't the first bug report about this though, so I generating it on the first installation (but not on upgrades) could be reasonable

**Comment by xtkoba** [comment]
Maybe it is sufficient to present a message about `updatedb` command on the first installation? (An idea borrowed from Gentoo Portage.)

**Comment by xtkoba** [comment]
And / Or make the message from `locate` command more friendly than "`mlocate.db`: No such file or directory".

**Comment by ravener** [comment]
@tigran123 i'm not sure about TBs of data but it wasn't bad for me and the database file is 6mb in total. 

But also it seems it only indexed my termux (root=/data/data/com.termux/files) by default, so i guess all the big files on your phone won't count by default and it is highly unlikely for an average user to have Terabytes on a phone. 

@Grimler91 right that makes sense but atleast a message though would suffice I suppose.

**Comment by tigran123** [comment]
Termux is used not only on the phones, but on big tablets also. And on my tablet there is more than 1TB of data (books, kiwix databases, classical music collections, etc) as I like to keep the "best part of the internet" always with me offline.

Thank you for the information about it indexing only com.termux/files -- I will have to configure it to index the mounted external storage as well.

**Comment by xtkoba** [comment]
Can anyone take care of this: https://github.com/termux/termux-packages/pull/8190#discussion_r765717443
