### ISSUE TITLE
mailutils: Multiple Hardcoded path

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#8117]
The `mailutils` package is looking up for mail at `/var/mail` instead of `$PREFIX/var/mail`, which lead into `No such file or directory` error:

```
~ $ mail
Cannot open mailbox /var/mail/u0_a203: No such file or directory
No mail for u0_a203
```

**Comment by xtkoba** [comment]
Other possible hardcoded paths found by `strings`:

```
/bin/cat
/bin/sh
/nonexisting
/tmp/mailutils.%s.%lu
/usr/bin/gdb
/usr/bin/more
/usr/local/etc/mailcap:/usr/etc/mailcap:/etc/mailcap:/etc/mail/mailcap:/usr/public/lib/mailcap
/usr/sbin/sendmail
/var/lock/subsys/mail
/var/mail/${user}
```

**Comment by thunder-coding** [comment]
I found that all the paths are defined in `paths` file, `./configure`ing seems to generate `./include/confpaths.h` which includes the paths as defined in the paths file.

**Comment by Yonle** [comment]
> I found that all the paths are defined in `paths` file, `./configure`ing seems to generate `./include/confpaths.h` which includes the paths as defined in the paths file.

In `paths` comment, There also mentions that:
```
(1) If the user specifies --with-path-foo, that value is used.
```

And now i'm unsure at this point, Right now, in `configure`, there's a flag called `--disable-rpath`:
```
--disable-rpath         do not hardcode runtime library paths
```

**Comment by thunder-coding** [comment]
rpath is forwarded to the linker, (`ld`). It just tells the linker that the library will be available that this location at runtime. I don't this will fix this problem

**Comment by Yonle** [comment]
Well then i guess we're gonna made a patch
