### ISSUE TITLE
Package Request: ripgrep

### ISSUE THREAD

**Issue by kutsan** [termux/termux-packages#812]
But probably depends on it #261.

**Comment by kellpossible** [comment]
pretty sure you can build ripgrep for android on ubuntu without that dependency, might give it a crack soon.

**Comment by kutsan** [comment]
@kellpossible How? It would be awesome.

**Comment by Memorion** [comment]
This should be possible with the steps described in https://blog.rust-lang.org/2016/05/13/rustup.html 
I just tried and had some trouble with the linker and macOS as the host, but I'm not that motivated to investigate further sorry!

**Comment by its-pointless** [comment]
Its available on my repo as well as rustc for termux see gcc_termux.
For now rust stuff ia not going into main repo but may change in future.

**Comment by kutsan** [comment]
@its-pointless That's great, I got ripgrep working. Any change for https://github.com/termux/termux-packages/issues/2301?

**Comment by its-pointless** [comment]
No. That requires  dealing with a library (users) that doesn't work with
android.

**Comment by fornwall** [comment]
ripgrep can now be installed with `pkg install ripgrep`!
