### ISSUE TITLE
[Bug]: swift cannot locate symbyol '_Unwind_Resume'

### ISSUE THREAD

**Issue by slaide** [termux/termux-packages#8130]
### Problem description

when i try to run any program from the swift package (e.g. swift, swiftc, swift-build), i get an error that says:
 $ swift-build
CANNOT LINK EXECUTABLE "swift-build": cannot locate symbol "_Unwind_Resume" referenced by "/data/data/com.termux/files/usr/lib/swift/android/libswift_Concurrency.so"...
(the 'swift-build' part of the message changes accordingly with a different program, the rest stays the same)

### What steps will reproduce the bug?

Fresh termux install, ($pkg update,) install the swift package, run any program from that package, observe error message (tried it on two different samsung devices, both running android 10)

### System information

$ termux-info
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
\# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
\# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
\# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.205-21567889 #1 SMP PREEMPT Tue May 11 16:40:57 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T830

**Comment by buttaface** [comment]
What version of Swift are you running: `swift --version`? Also, what NDK version: `pkg search ndk-sysroot`? I use Swift all the time on aarch64 without a problem, so this is unusual.

**Comment by buttaface** [comment]
I think this is a bug in the Swift package build that only shows up on Android 7-10, which I didn't notice since I've only been using Android 11 and 12 lately.

Please paste the output of these commands after installing the `llvm` package:
```
swift --version -disallow-use-new-driver
llvm-readelf -sW /system/lib64/libc.so | grep _Unwind_Resume
```
Thanks for reporting, I will look into it.

**Comment by slaide** [comment]
~ $ swift --version -disallow-use-new-driver
Swift version 5.5.1 (swift-5.5.1-RELEASE)
Target: aarch64-unknown-linux-android24
~ $ llvm-readelf -sW /system/lib64/libc.so | grep _Unwind_Resume
[blank. Takes a second, then shows new command prompt] 

On Fri, Dec 3, 2021, at 6:34 PM, buttaface wrote:
> 
> 
> I think this is a bug in the Swift package build that only shows up on Android 7-10, which I didn't notice since I've only been using Android 11 and 12 lately.
> 
> Please paste the output of these commands after installing the `llvm` package:
> 
> `swift --version -disallow-use-new-driver
> llvm-readelf -sW /system/lib64/libc.so | grep _Unwind_Resume
`

**Comment by xtkoba** [comment]
Seems to be exactly the case mentioned in https://github.com/termux/termux-packages/issues/8029#issuecomment-975021716.

For a package with a simple build system I would fix this by

```bash
LDFLAGS+=" -l:libunwind.a"
```

but I doubt if this just works with `swift`.

**Comment by buttaface** [comment]
Thanks, the Swift build uses a custom CMake configuration though, so the reason is probably different. I'll need to dig into the linker flags used and figure it out, [probably just forgot to add it here](https://github.com/termux/termux-packages/blob/master/packages/swift/swift-ndk-23.patch#L187).

**Comment by xtkoba** [comment]
Another possibility is that `-unwindlib=none` or `-unwindlib=libgcc` is specified implicitly or explicitly, which is incorrect. If so, we have to explicitly specify `-unwindlib=libunwind` (along with `-rtlib=compiler-rt`).

**Comment by xtkoba** [comment]
FYI, `_Unwind_*` are defined in `lib/libunwind.a` which comes from `ndk-sysroot_23b-2`:

```
$ readelf -Wa lib/libunwind.a | egrep '^ +[0-9]+:.*[0-9] _Unwind_'
    33: 0000000000000000    28 FUNC    GLOBAL HIDDEN    18 _Unwind_DeleteException
    34: 0000000000000000   100 FUNC    GLOBAL HIDDEN    12 _Unwind_ForcedUnwind
    35: 0000000000000000    44 FUNC    GLOBAL HIDDEN    19 _Unwind_GetGR
    36: 0000000000000000    48 FUNC    GLOBAL HIDDEN    23 _Unwind_GetIP
    37: 0000000000000000    52 FUNC    GLOBAL HIDDEN    14 _Unwind_GetLanguageSpecificData
    38: 0000000000000000    52 FUNC    GLOBAL HIDDEN    16 _Unwind_GetRegionStart
    39: 0000000000000000   216 FUNC    GLOBAL HIDDEN     4 _Unwind_RaiseException
    40: 0000000000000000   136 FUNC    GLOBAL HIDDEN     8 _Unwind_Resume
    41: 0000000000000000     8 FUNC    GLOBAL HIDDEN    21 _Unwind_SetGR
    42: 0000000000000000    16 FUNC    GLOBAL HIDDEN    25 _Unwind_SetIP
    27: 0000000000000000   116 FUNC    GLOBAL HIDDEN    12 _Unwind_Backtrace
    28: 0000000000000000   104 FUNC    GLOBAL HIDDEN    10 _Unwind_FindEnclosingFunction
    29: 0000000000000000   120 FUNC    GLOBAL HIDDEN    14 _Unwind_Find_FDE
    30: 0000000000000000    48 FUNC    GLOBAL HIDDEN    16 _Unwind_GetCFA
    31: 0000000000000000    72 FUNC    GLOBAL HIDDEN     6 _Unwind_GetDataRelBase
    33: 0000000000000000    60 FUNC    GLOBAL HIDDEN    18 _Unwind_GetIPInfo
    34: 0000000000000000    72 FUNC    GLOBAL HIDDEN     8 _Unwind_GetTextRelBase
    37: 0000000000000000   100 FUNC    GLOBAL HIDDEN     4 _Unwind_Resume_or_Rethrow
```

**Comment by buttaface** [comment]
Yeah, I use the Swift-forked clang 10 to compile the Swift standard library and concurrency runtime, because the NDK clang doesn't have their needed modifications, but their clang 10 doesn't have the compiler-rt change needed for NDK 23.

I think I had this unwind flag added for my local builds but forgot to upstream it for this Termux package build, and since the official package worked fine on my local Android 11, I didn't notice: will look into it and update.

**Comment by buttaface** [comment]
Fix has been pushed in the new Swift 5.5.1-3 package, @slaide, please try it out.

**Comment by slaide** [comment]
~ $ swift
error: unableToFind(tool: "lldb")
~ $ cat test.swift
print("hello")
~ $ swift test.swift
hello
~ $ swift --version
Swift version 5.5.1 (swift-5.5.1-RELEASE)
Target: aarch64-unknown-linux-android24
~ $ pkg search swift
Checking availability of current mirror: ok
Sorting... Done
Full Text Search... Done
[..]
swift/stable,now 5.5.1-3 aarch64 [installed]
  Swift is a high-performance system programming language
~ $ lldb
The program lldb is not installed. Install it by executing:
pkg install lldb

**Comment by slaide** [comment]
with lldb installed:
~ $ swift
error: LLDB isn't configured with REPL support for any languages.
~ $ lldb --version
lldb version 13.0.0
~ $ pkg search lldb
Checking availability of current mirror: ok
Sorting... Done
Full Text Search... Done
lldb/stable,now 13.0.0-3 aarch64 [installed]
  LLVM-based debugger

**Comment by buttaface** [comment]
Looks good: we don't support the Swift REPL, which is what your `swift` alone command invokes, because that requires building the Swift-forked lldb, which I haven't tried to get working. You can try building executables instead, with `swiftc test.swift; ./test` or [this file](https://github.com/apple/swift/blob/main/test/Interpreter/async.swift) that exercises Swift's new concurrency runtime, `swiftc -parse-as-library async.swift; ./async`.

Of course, building and testing Swift packages works too:
```
pkg install git
git clone https://github.com/apple/swift-nio.git
cd swift-nio
swift build -j 9
swift test -j 9 --parallel
```

**Comment by buttaface** [comment]
Appears to work fine for you now, let us know if anything else broke.
