### ISSUE TITLE
Failure upgrading liblua52

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#8133]
There is this message:

```
[...]
update-alternatives: error: alternative path /data/data/com.termux/files/usr/bin/lua.5.2 doesn't exist
update-alternatives: error: alternative path /data/data/com.termux/files/usr/bin/lua.5.2 doesn't exist
dpkg: error processing package liblua52 (--configure)
[...]
```

On 

```
0.117
aarch64
Android 8.1.0
```

**Comment by angelog0** [comment]
Now `pkg upgrade` says I have a package not fully installed... How to fix this?

**Comment by xtkoba** [comment]
My fault. Will be fixed soon.

**Comment by Grimler91** [comment]
`touch $PREFIX/bin/lua.5.2 $PREFIX/bin/luac.5.2` works as a workaround if problem persist even when trying to install lua 5.2.4-7

**Comment by angelog0** [comment]
@Grimler91 wrote

> `touch $PREFIX/bin/lua.5.2 $PREFIX/bin/luac.5.2` works as...

After @xtkoba fix, I did another `pkg upgrade` and all seems to work, no error from dpkg. Anyway, the folders you cite do not exist in my installation:

```
$ ls -lrt $PREFIX/bin/lua*
ls: cannot access '/data/data/.../usr/bin/lua*': No such file or directory
```
