### ISSUE TITLE
Terminal transcript

### ISSUE THREAD

**Issue by freebold84** [termux/termux-packages#8134]
You are going to install Kali Nethunter In Termux Without Root ;) Cool

find: ‘/data/data/com.termux/files/home/arch/apex’: Permission denied
find: ‘/data/data/com.termux/files/home/arch/storage’: Permission denied
find: ‘/data/data/com.termux/files/home/arch/system’: Permission denied
find: ‘/data/data/com.termux/files/home/arch/vendor’: Permission denied
find: ‘/data/data/com.termux/files/home/arch/data/data/com.termux/files/usr’: Permission denied
find: ‘/data/data/com.termux/files/home/arch/data/data/com.termux/files/home’: Permission denied
 [*] Checking host architecture ...
 [*] Updating apt cache...
 [*] Checking for all required tools...
  • proot is OK
  • tar is OK
  • axel is OK
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be REMOVED:
  kali-anonsurf
The following packages will be upgraded:
  apt bash command-not-found dialog git grep liblua52 liblua53 libsqlite
  lua53 mailutils ndk-sysroot nodejs php ruby ruby-ri samba sed sqlite
  util-linux vim-python vim-runtime xxhash zsh
24 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/47.2 MB of archives.
After this operation, 1024 kB of additional disk space will be used.
(Reading database ... 112234 files and directories currently installed.)
Removing kali-anonsurf (1.2.2.2) ...
dpkg: error processing package kali-anonsurf (--remove):
 cannot remove '/usr': Read-only file system
dpkg: too many errors, stopping
Errors were encountered while processing:
 kali-anonsurf
Processing was halted because there were too many errors.
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
~/Nethunter-In-Termux $

**Comment by freebold84** [comment]
data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
This is what I need fixed please someone how do I fix it

**Comment by sk0kanik** [comment]
Kali Nethunter is not a package Termux provides.
