### ISSUE TITLE
texlive upgrade to 2021

### ISSUE THREAD

**Issue by leomayer** [termux/termux-packages#8141]
**Problem description**
Current version of LaTeX installation is based on 2020. Current version for 2021 is already available. 

**Steps to reproduce**
Check https://tug.org/texlive/

**Expected behavior**
If I run apt upgrade I would expect that the installation would upgrade.

**Comment by xtkoba** [comment]
Use `texlive-installer`.

**Comment by xtkoba** [comment]
Removal done by commit https://github.com/termux/termux-packages/commit/7b355a29d05fa8570c2d9e25b55d135db96d6725. Closing.
