### ISSUE TITLE
[Package]: lua-language-server

### ISSUE THREAD

**Issue by Iamafnan** [termux/termux-packages#8149]
### Package description

Please add support for lua-language-server in arm architecture devices

### Home page URL

https://github.com/sumneko/lua-language-server

### Source code URL

https://github.com/sumneko/lua-language-server

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Please suggest a patch to fix the [build issues on arm](https://github.com/termux/termux-packages/blob/master/packages/lua-language-server/build.sh#L12-L14) and it will be added

**Comment by shadmansaleh** [comment]
@Grimler91 arm support has already been added https://github.com/actboy168/bee.lua/commit/9132c7ecb4a68c40d52a6d750308237bf054feb6#diff-2c10c19c53b479640faaf36f431774686d66b02c43f4939c79b029df462b7551

**Comment by MrAdityaAlok** [comment]
@shadmansaleh I have already updated in #8493. But it has yet not been merged. @Grimler91 please merge it.

**Comment by shadmansaleh** [comment]
Ohh I missed that pr . I was actually getting ready tos end a pr myself https://github.com/shadmansaleh/termux-packages/pull/18 :D . Thanks @MrAdityaAlok .

**Comment by thunder-coding** [comment]
> @shadmansaleh I have already updated in #8493. But it has yet not been merged. @Grimler91 please merge it.

Thanks for attracting attention towards the PR, merged!

**Comment by Iamafnan** [comment]
Thanks you all of you for adding support for arm 😄
