### ISSUE TITLE
Package request: links2

### ISSUE THREAD

**Issue by alive4ever** [termux/termux-packages#816]
I would love to see [links2](https://packages.debian.org/sid/links2) packaged for termux.

It's an alternative to ``elinks``, which hasn't had any stable release since 2012.

Thanks.

**Comment by fornwall** [comment]
From https://github.com/termux/termux-packages/pull/597:

> Hm, links2 seems a bit dead/stagnant as a project, and contains no issue tracker or open forum to open issues against. I'm a bit hesitant to add these kind of projects - does it bring any advantages over w3m or lynx?

Let me know if you need links2 over w3m or lynx!

**Comment by alive4ever** [comment]
I still prefer ``links2`` over ``elinks``, since the links2 default configuration is safer than elinks default.
``links2`` will warn on invalid certificates, whereas ``elinks`` will [gladly accept invalid certificates](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740981).

``links2`` also has better support for latest tls libraries.

``w3m`` is out of option, since mouse tracking only works when ``TERM=xterm``. ``lynx`` is also out of option, since mouse tracking has to be expicitly enabled from command line ``-use_mouse``. ``lynx`` also doesn't support frames, which ``links2`` and ``elinks`` support.

It would be better to offer alternatives for browsers, since ``links2`` is very lightweight and doesn't require much resources to build and maintain. Compare it to ``emacs`` as reference.

**Comment by alive4ever** [comment]
I pointed wrong Debian package as reference. The package should be [``links``](https://packages.debian.org/sid/links), which is ``links2`` without graphics support.
