### ISSUE TITLE
[Bug]: `libandroid-support` not taking effect unless linked against main executable

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#8162]
### Problem description

This was originally found in #5124, where `mediainfo` is linked against `libzen.so`, which is linked against `libandroid-support.so`, which `mediainfo` itself is not linked against. In this case, any function called from `libzen.so` is not wrapped by `libandroid-support.so`.

### What steps will reproduce the bug?

A self-contained example:

```
$ cat foo.c
#include <stdio.h>
void foo(void) { puts("foo"); }

$ cat foo_wrapper.c
#include <stdio.h>
void foo(void) { puts("foo_wrapper"); }

$ cat bar.c
void foo(void);
void bar(void) { foo(); }

$ cat main.c
void bar(void);
int main(void) { bar(); }

$ $CC foo.c -shared -o libfoo.so

$ $CC foo_wrapper.c -shared -o libfoo_wrapper.so

$ $CC bar.c -shared -o libbar.so -L. -lfoo_wrapper

$ $CC main.c -o main -L. -lbar -lfoo

$ LD_LIBRARY_PATH=. ./main
foo
```

### What is the expected behavior?

```
$ LD_LIBRARY_PATH=. ./main
foo_wrapper
```

### System information

Tested on Android 8.1.0 aarch64

**Comment by Grimler91** [comment]
Should the function in foo_wrapper.c take precedence? Seems logical that functions in libfoo overrides functions in libfoo_wrapper in this case, since it is linked later. I also get the same behaviour when testing on archlinux.

Programs that link against libkrb5.so would have to link against libresolv-wrapper as well, and be careful to link in the right order:
```
$ $CC main.c -o main -L. -lbar -lfoo_wrapper -lfoo
$ LD_LIBRARY_PATH=. ./main
foo_wrapper
```
(same works on archlinux as well)

**Comment by xtkoba** [comment]
Let me revise the example to better describe the situation:

```
$ cat foo.c
#include <stdio.h>
void foo(void) { puts("foo"); }
void baz(void) {}

$ cat foo_wrapper.c
#include <stdio.h>
void foo(void) { puts("foo_wrapper"); }

$ cat bar.c
void foo(void);
void bar(void) { foo(); }

$ cat main.c
void bar(void);
void baz(void);
int main(void) { bar(); baz(); }

$ $CC foo.c -shared -o libfoo.so

$ $CC foo_wrapper.c -shared -o libfoo_wrapper.so

$ $CC bar.c -shared -o libbar.so -L. -lfoo_wrapper

$ $CC main.c -o main -Wl,--as-needed -L. -lbar -lfoo_wrapper -lfoo

$ LD_LIBRARY_PATH=. ./main
foo
```

Here, `-Wl,--as-needed` is the culprit. `main.c` itself does not have any reference to `libfoo_wrapper.so`, which is not recorded as `DT_NEEDED` in the executable.

**Comment by xtkoba** [comment]
`-Wl,--as-needed` comes from

https://github.com/termux/termux-packages/blob/9457852c41fe429708d83cce5447f69dfe88713d/scripts/build/termux_step_setup_toolchain.sh#L72

**Comment by xtkoba** [comment]
And then it is followed by `-landroid-support`:

https://github.com/termux/termux-packages/blob/9457852c41fe429708d83cce5447f69dfe88713d/scripts/build/termux_step_setup_toolchain.sh#L90

**Comment by xtkoba** [comment]
It would be prefeable if `-landroid-support` is automatically appended to `LDFLAGS` for a package which indirecly depends on `libandroid-support` through its dependencies. I don't know whether it is possible.

**Comment by Grimler91** [comment]
That is a better example, thanks, running it on desktop linux and in termux prints `foo` so it at least works the same with both linkers. 

Explicitly linking packages if libandroid-support is found in any dependency sounds like a plan. I think we used to make all packages depend on libandroid-support, [before the libiconv package was added](https://github.com/termux/termux-packages/commit/52198eee5d01a682c210f4261d4a449c3480307e)
