### ISSUE TITLE
Hm, this seems to happen a lot recently. I just explicitly evicted the cloudflare cache (again) - can you try running `apt update` again?

### ISSUE THREAD

**Issue by goravsha** [termux/termux-packages#8163]
~ $ apt update                                    Ign:1 https://packages.termux.org/apt/termux-main stable InRelease                                  Ign:1 https://packages.termux.org/apt/termux-main stable InRelease
Ign:1 https://packages.termux.org/apt/termux-main stable InRelease
Err:1 https://packages.termux.org/apt/termux-main stable InRelease
  Could not connect to packages.termux.org:443 (139.178.84.102), connection timed out Could not connect to packages.termux.org:443 (139.178.84.82), connection timed out Could not connect to packages.termux.org:443 (139.178.84.50), connection timed out Could not connect to packages.termux.org:443 (147.75.35.206), connection timed out Could not connect to packages.termux.org:443 (139.178.84.74), connection timed out                                 Reading package lists... Done                     Building dependency tree... Done
Reading state information... Done                 All packages are up to date.
W: Failed to fetch https://packages.termux.org/apt/termux-main/dists/stable/InRelease  Could not connect to packages.termux.org:443 (139.178.84.102), connection timed out Could not connect to packages.termux.org:443 (139.178.84.82), connection timed out Could not connect to packages.termux.org:443 (139.178.84.50), connection timed out Could not connect to packages.termux.org:443 (147.75.35.206), connection timed out Could not connect to packages.termux.org:443 (139.178.84.74), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.  

Hi I am new here to learn but unable to update and getting this above error.  Please tell me how to solve this.
Even I tried to change repo by using termux-change-repo command still not able to update and install any pkg.

**Comment by Grimler91** [comment]
Something seem to be wrong with your internet connection, or/and packages.termux.org is blocked in your country/on your network/by your internet provider. Switching to another mirror hopefully helps. 

Not really anything to be done from termux's side of things.

**Comment by goravsha** [comment]
> Something seem to be wrong with your internet connection, or/and packages.termux.org is blocked in your country/on your network/by your internet provider. Switching to another mirror hopefully helps.
> 
> Not really anything to be done from termux's side of things.

Thank you for your help. I tried the all mirror

> Something seem to be wrong with your internet connection, or/and packages.termux.org is blocked in your country/on your network/by your internet provider. Switching to another mirror hopefully helps.
> 
> Not really anything to be done from termux's side of things.

Thank you for the help. I tried the all mirrors by switching them but still not working. Thank you!

**Comment by sk0kanik** [comment]
>  I tried the all mirrors by switching them but still not working. Thank you!

Is your phone's settings preventing termux app from accessing internet?

**Comment by goravsha** [comment]
> > I tried the all mirrors by switching them but still not working. Thank you!
> 
> Is your phone's settings preventing termux app from accessing internet?

No, I checked it, It's not preventing termux app from accessing internet. Termux app is having full permission of internet with wifi & mobile data internet.

**Comment by Grimler91** [comment]
Can you visit the url in android's browser?

Can you access internet through other programs than apt in termux?

What kind of device are you using? (See requested information in [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=bug+report&template=01-bug-report.yml&title=%5BBug%5D%3A+))

**Comment by goravsha** [comment]
> Can you visit the url in android's browser?
> 
> Can you access internet through other programs than apt in termux?
> 
> What kind of device are you using? (See requested information in [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=bug+report&template=01-bug-report.yml&title=%5BBug%5D%3A+))

I clear the all data of termux app in the phone setting and started again finally it's working fine. You guys are awesome. Thank you so much all of you for assisting quickly.😊
