### ISSUE TITLE
[Package]: tsmuxer and tsmuxergui

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#8165]
### Package description

tsMuxer is a Transport Stream muxer. Remux/mux elementary streams, EVO/VOB/MPG, MKV/MKA, MP4/MOV, TS, M2TS to TS to M2TS. Supported video codecs H.264/AVC, H.265/HEVC, VC-1, MPEG2. Supported audio codecs AAC, AC3 / E-AC3(DD+), DTS/ DTS-HD. Ability to set muxing fps manually and automatically, Ability to change level for H.264 streams, Ability to shift a sound tracks, Ability to extract DTS core from DTS-HD, Ability to join files.

### Home page URL

https://www.videohelp.com/software/tsMuxeR

### Source code URL

https://github.com/justdan96/tsMuxer

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

build.sh
```
TERMUX_PKG_HOMEPAGE=https://www.videohelp.com/software/tsMuxeR
TERMUX_PKG_DESCRIPTION="tsMuxer is a Transport Stream muxer."
TERMUX_PKG_LICENSE="Apache License 2.0"
TERMUX_PKG_VERSION=nightly-2021-12-05-02-09-30
TERMUX_PKG_SRCURL=https://github.com/justdan96/tsMuxer/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=676f7741fb897ec53a975fcb6a0c4d5466d680a12e82b54b39cbf48d91bb14fb

echo ${TERMUX_PKG_SRCDIR}
termux_step_configure() {

	cd ${TERMUX_PKG_SRCDIR}
	rm -rf build
	mkdir build 
	cd build
	cmake ../ -G Ninja -DTSMUXER_GUI=ON 
	ninja

}
termux_step_make_install() {
	cp ${TERMUX_PKG_SRCDIR}/build/tsMuxer/tsmuxer /data/data/com.termux/files/usr/bin/tsmuxer
	cp ${TERMUX_PKG_SRCDIR}/build/tsMuxerGUI/tsMuxerGUI /data/data/com.termux/files/usr/bin/tsmuxergui
}
```

Above script builds both console and gui application of tsmuxer and installs them. This is my first build script, i have tested it and it works.
But still

Termux developers test the script and both console and gui version are independent of each other so add it to main repo or x11-repo. or seperately

**Comment by xtkoba** [comment]
As for the GUI version, you may want to open a separate package request in https://github.com/termux/x11-packages/issues.

This may be off-topic but I suppose that the GUI version and the non-GUI version are not independent of each other, but rather they conflict with each other, just like mpv{,-x} or emacs{,-x}.

I think I can take care of packaging the non-GUI version only.

**Comment by tathastu871** [comment]
> As for the GUI version, you may want to open a separate package request in https://github.com/termux/x11-packages/issues.
> 
> This may be off-topic but I suppose that the GUI version and the non-GUI version are not independent of each other, but rather they conflict with each other, just like mpv{,-x} or emacs{,-x}.
> 
> I think I can take care of packaging the non-GUI version only.

it is not necessary to install gui version. cli version is  standalone and independent

**Comment by tathastu871** [comment]
Hey seems like tsmuxer build.sh is in repo. but not available through apt install

**Comment by tathastu871** [comment]
> As for the GUI version, you may want to open a separate package request in https://github.com/termux/x11-packages/issues.
> 
> This may be off-topic but I suppose that the GUI version and the non-GUI version are not independent of each other, but rather they conflict with each other, just like mpv{,-x} or emacs{,-x}.
> 
> I think I can take care of packaging the non-GUI version only.

Hey seems like tsmuxer build.sh is in repo. but not available through apt install
