### ISSUE TITLE
Hash sum mismatch doing apt update

### ISSUE THREAD

**Issue by x2k13** [termux/termux-packages#817]
As of yesterday, after upgrading v0.46 to v0.48, apt update throws an error:

apt update
Get:1 http://termux.net stable InRelease [1666 B]
Get:2 http://termux.net stable/main all Packages [3692 B]
Get:3 http://termux.net stable/main arm Packages [49.2 kB]
Ign:3 http://termux.net stable/main arm Packages
Get:3 http://termux.net stable/main arm Packages [218 kB]
Err:3 http://termux.net stable/main arm Packages
  Hash Sum mismatch
Fetched 220 kB in 1s (133 kB/s)
Reading package lists... Done
E: Failed to fetch http://termux.net/dists/stable/main/binary-arm/Packages  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by fornwall** [comment]
Can you try running `apt clean && apt update` and see if it works now? Could be a http caching issue (the termux.net repository uses Cloudflare as a caching proxy/CDN.

**Comment by x2k13** [comment]
Thanks for the quick response. I did that already before I opened the issue. Did it again a minute ago and it worked. Looks like cloudflare (pest) has/had trouble keeping up with repository changes.

**Comment by fornwall** [comment]
Great!

Yes, it's a recurring problem with cache eviction for the Package index files not working reliably without delay. I'll look at other options in the future.
