### ISSUE TITLE
clang strange errors with standard C Headers!!!

### ISSUE THREAD

**Issue by GreenJoey** [termux/termux-packages#818]
Today I was learning about _Complex and complex numbers in C when I tried an experiment in C and I wrote this code:

`#include <stdio.h>
    #include <math.h>

int main(){
    printf('%lf', sqrt(-1));
    return 0;
}`
After saving it I ran `cc div.c` and I got this error (SC1).
I then ran `cc div.c -v` and I found that through clang was looking in all the standard directories for headers it still can't find the sqrt function.
(SC2)

**Comment by GreenJoey** [comment]
![SC2](https://cloud.githubusercontent.com/assets/19374280/23584748/9b32e5cc-0190-11e7-9ffa-62d445bf3931.png)
![SC2](https://cloud.githubusercontent.com/assets/19374280/23584750/b179681a-0190-11e7-8010-54d396f9d011.png)
![SC1](https://cloud.githubusercontent.com/assets/19374280/23584760/f754bd76-0190-11e7-903a-038bf3a480b2.png)

**Comment by vishalbiswas** [comment]
In android math.h functions exist in separate lib (libm). Add a `-lm` option to compile with math lib.
BTW, replace the single quotes with double quotes in printf.

**Comment by AbdullahBinJahed** [comment]
> In android math.h functions exist in separate lib (libm). Add a `-lm` option to compile with math lib.
> BTW, replace the single quotes with double quotes in printf.

Thanks man : )
