### ISSUE TITLE
[Bug]: pkg it's not updating

### ISSUE THREAD

**Issue by tonho991** [termux/termux-packages#8185]
### Problem description

There is an error installing packages and updating pkg.
![Screenshot_20211208-170745](https://user-images.githubusercontent.com/67771574/145284955-1c32999e-6e09-4172-b55e-2840140fa718.png)

### What steps will reproduce the bug?

When trying to install packages

### What is the expected behavior?

Install the packages

### System information

termux-info:

```
Version: 0.117
Installed in: FDroid
Android: 8.1
Brand: Motorola (Moto e5 play)
```

**Comment by tonho991** [comment]
I managed to fix it. I cleaned up the Termux data, and used ```pkg upgrade```

**Comment by Grimler91** [comment]
For the record, this happens when termux-keyring is outdated, it then doesn't contain the key for my mirror. Other mirrors work fine though, so 
```
# Switch all repos to anything except grimler
termux-change-repo
pkg upgrade
```
Should do the trick as well, after that all mirrors will work again
