### ISSUE TITLE
[Bug]: clang: ld: command not found

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#8191]
### Problem description

Spun off from #8183.

The `clang` package does not install `$PREFIX/bin/ld`.

Currently `bin/ld` is provided by the `binutils` package, which installs `ld.bfd` under the name of `ld`. But `clang` package does not depend on `binutils`. Note that Clang/LLVM on Termux is configured to use `lld` as the default linker, so it should not have any dependency on `binutils`.

I suggest that `bin/ld` be a symbolic link managed by update-alternatives, pointing either `bin/lld` or `bin/ld.bfd` (renamed from `bin/ld` in `binutils`).

### What steps will reproduce the bug?

```
pkg install clang
ld
```
produces

```
bash: ld: command not found
```

### What is the expected behavior?

```
ld: error: no input files
```

### System information

Tested on Android 8.1.0 aarch64.

**Comment by xtkoba** [comment]
I assume this can be closed with `binutils-is-llvm` being packaged. Thanks.

**Comment by MangeshBaghe** [comment]
![Uploading Screenshot_20240724_073504.jpg…]()
ld: error: no input files
