### ISSUE TITLE
[Bug]: pm results in error msg

### ISSUE THREAD

**Issue by fxmbsw7** [termux/termux-packages#8218]
### Problem description

i tried out of couriosity pm cause id need a few features but it returned constant error msg

cmd: Failure calling service package: Failed transaction (2147483646)

any solution ?

### Steps to reproduce the behavior.

pm on the shell, no args, respectivly any arg to it, results in that

### What is the expected behavior?

no constant fail of service msg i guess

### System information

* Termux application version: 0.117
* Android OS version: 11 rm.ui 2
* Device model: realme gt 5g

**Comment by Grimler91** [comment]
pm is just a [wrapper around /system/bin/pm](https://github.com/termux/termux-packages/blob/master/packages/termux-tools/build.sh#L29). Can you run /system/bin/pm from an adb shell without the error, or is pm giving an error then as well?

**Comment by fxmbsw7** [comment]
i cannot test, no handy computer connection currently
i just guess i can but i dunno, sorry cant test

**Comment by WMCB-Tech** [comment]
without a computer you can use `pm` command via wireless debugging in developer options if you're on Android 11

**Comment by ELWAER-M** [comment]
you can't use `pm` without root access or using `adb shell`
![Screenshot_20211213-022836_Termux](https://user-images.githubusercontent.com/71197008/145736048-511a3474-0369-4f3e-9c70-57ca13855908.jpg)

**Comment by agnostic-apollo** [comment]
Standard android restriction since like Android 8 I think. As mentioned, use root or adb.  Not a termux issue.
