### ISSUE TITLE
[Bug]: Basic xfce environment is broken- no panel, terminal, etc...

### ISSUE THREAD

**Issue by StevenAlexander44** [termux/termux-packages#8219]
### Problem description

Almost no apps directly related to xfce will open- like the panel, and terminal. Thunar works, but I haven't yet tried any other apps.

### What steps will reproduce the bug?

pkg i x11-repo
pkg i xfce4 xfce4-goodies tigervnc
echo "xfce4-session &
xhost + &" > .vnc/xstartup
vncserver :1

### What is the expected behavior?

Hopefully xfce4-panel, and the environment as a whole, will work as intended.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.71-perf+ #1 SMP PREEMPT Mon Mar 23 15:01:48 KST 2020 armv7l Android
Device manufacturer:
LGE
Device model:
LML413DL
```

**Comment by StevenAlexander44** [comment]
Possible problem (error during install)
Copied from my /data/data/com.termux/files/usr/var/log/apt/term.log
```
Setting up gdk-pixbuf (2.42.6-1) ...
g_module_open() failed for /data/data/com.termux/files/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tiff.so: dlopen failed: library "libzstd.so.1" not found
```

**Comment by xtkoba** [comment]
As for `gdk-pixbuf`, `lib/libzstd.so.1` belongs to the `zstd` package.

**Comment by thunder-coding** [comment]
This should now have been fixed. Just move to Cloudflare Proxy using `termux-change-repo` and update your packages. I do not use packages form the x11-repo, so I can't test.

In case you test it, make sure you report whether it has been fixed
