### ISSUE TITLE
[Bug]: wget is not copied to github action

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#8223]
### Part of the error:
```
/home/builder/.termux-build/wget/src/lib/freading.c:41:14: error: incomplete definition of type 'struct __sFILE'
  return (fp_->_flags & __SRD) != 0;
          ~~~^
/home/builder/.termux-build/_cache/android-r23b-api-24-v5/bin/../sysroot/usr/include/stdio.h:61:8: note: forward declaration of 'struct __sFILE'
struct __sFILE;
       ^
1 error generated.
```
[action link](https://github.com/Maxython/termux-packages-pacman/actions/runs/1571538694)

### What steps will reproduce the bug?

empty commit

### What is the expected behavior?

successful compilation

### System information

this is github action

**Comment by Grimler91** [comment]
Looks like it needs the same type of patch as gcal: https://github.com/termux/termux-packages/blob/bf51d022eff247887d44f3ef2b9a5b801ccb3d1b/packages/gcal/gnulib.patch
