### ISSUE TITLE
clang error -> segmentation fault in g++

### ISSUE THREAD

**Issue by piyushkinge** [termux/termux-packages#823]
Cannot compile c++ programs in new clang package 3.9.1-3. it's giving segmentation fault

**Comment by Wetitpig** [comment]
Can you give us the code

**Comment by piyushkinge** [comment]
Yes sure wait

**Comment by piyushkinge** [comment]
#include<stdio.h>
#include<iostream>

using namespace std;

int main(){
int i,j,k,n,m,l,h;

cout<<"Enter how many numbers you have: ";
cin>>n;
int z = n;

int a[n];
for(i=0;i<n;i++)
	{
cout<<"Enter number "<<i+1<<" = ";
cin>>a[i];
}
//bubble sort
for(j=0;j<n-1;j++)
{
for(k=0;k<n-1-j;k++)
{
if(a[k+1] < a[k])
swap(a[k+1],a[k]);
}
}
cout<<"\n\nEnter number you want to search: ";
cin>>k;

//binary search
l=0;
h= z-1;
m = (l+h)/2;

int flag = 1;
while(flag)
{
	
			if(a[m] == k)
			{
			cout<<"\n\nPosition of the entered no is : "<<m+1<<endl;
			break;
			}

			else if(a[m]<k)
			{
			l = m+1;
			m = (l+h)/2;
			}



			else if(a[m]>k)
			{
			h = m-1;
			m = (l+h)/2;
			}

	if(l>h)
	{
	flag = 0;
	}

}

if(flag == 0)
{
cout<<"\nSorry...the entered number is not there in the database..."<<endl;
}
return 0;
}

**Comment by piyushkinge** [comment]
Even a hello world code is giving error...
Try running below code

#include<stdio.h>
#include<iostream>

using namespace std;

int main()
{

cout<<"Hello world ";

return 0;
}

**Comment by piyushkinge** [comment]
It's iostream there after #include... Don't know why it's not getting posted here

**Comment by Wetitpig** [comment]
I have no problems running the program with `#include <iostream>`

**Comment by piyushkinge** [comment]
It compiles without any problem
But shows segmentation fault in my device
It worked well on previous release i.e 3.9.1-2.

**Comment by piyushkinge** [comment]
![screenshot_2017-03-06-17-42-48](https://cloud.githubusercontent.com/assets/23546470/23609591/c0be34e0-0294-11e7-95a4-671aca5a6fcf.png)
![screenshot_2017-03-06-17-42-52](https://cloud.githubusercontent.com/assets/23546470/23609602/cda12546-0294-11e7-8485-474fa80bc82f.png)
![screenshot_2017-03-06-17-38-09](https://cloud.githubusercontent.com/assets/23546470/23609615/db976926-0294-11e7-81c7-0084ea186e5c.png)


Have a look at these screenshots...

**Comment by mawatech** [comment]
I can reproduce it with the short program.
Here is a strace log:
https://gist.github.com/a522f92d19f51986e0d0a071a98d557f

**Comment by piyushkinge** [comment]
Sorry i don't understand anything about that log...
Just tell me if there is any way i can downgrade the clang?

**Comment by mawatech** [comment]
The log doesn't help you, but hopefully the package maintainer :-)

**Comment by piyushkinge** [comment]
Ohk.. Thanks..

**Comment by Wetitpig** [comment]
Are you using ARM machine?

**Comment by mawatech** [comment]
```
$ uname -a
Linux localhost 3.18.19+ #1 SMP PREEMPT Tue Dec 6 15:46:33 CST 2016 aarch64 Android
```

**Comment by Wetitpig** [comment]
I mean @piyushkinge.

**Comment by piyushkinge** [comment]
Yeah.. It's arm64

**Comment by Wetitpig** [comment]
Can you run `g++ -S bs.cpp`  and post the results?

**Comment by fornwall** [comment]
Thanks for reporting! This is actually a problem with the `libgnustl_shared.so` shared library in the latest version of the `libgnustl` package - I'm looking at it, it should be fixed in a moment.

**Comment by fornwall** [comment]
This should now be fixed in version 14-1 of the libgnustl package. Run `apt update && apt upgrade` to receive the update.

Thanks for reporting1

**Comment by piyushkinge** [comment]
![screenshot_2017-03-07-05-10-46](https://cloud.githubusercontent.com/assets/23546470/23635260/
9f02296e-02f4-11e7-9888-1c2ec26caca1.png)
Got it...!
Thanks man...

**Comment by piyushkinge** [comment]
![screenshot_2017-03-07-05-10-46](https://cloud.githubusercontent.com/assets/23546470/23635641/efceca1c-02f6-11e7-9726-1054a0e10589.png)

**Comment by webbery** [comment]
I meet the same problem. Following is my code and env:
![图片](https://user-images.githubusercontent.com/5257853/61677182-25c23c80-ad31-11e9-8ef3-b7d79f7c2788.png)
If I remove line of "cout" and use printf, it works fine.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/3990
