### ISSUE TITLE
[Bug]: librsvg relies on __multf3

### ISSUE THREAD

**Issue by easyaspi314** [termux/termux-packages#8235]
### Problem description

librsvg fails to load because it can't find some libgcc symbols, because it appears to use `long double`.

### What steps will reproduce the bug?

Well I noticed this when `gdk-pixbuf` was updated.

I have literally just updated my phone to 12, so I don't know if this is an Android 12 issue or not.
```
Preparing to unpack .../gdk-pixbuf_2.42.6-2_aarch64.deb ...
Unpacking gdk-pixbuf (2.42.6-2) over (2.42.6-2) ...
Setting up gdk-pixbuf (2.42.6-2) ...
g_module_open() failed for /data/data/com.termux/files/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: dlopen failed: cannot locate symbol "__multf3" referenced by "/data/data/com.termux/files/usr/lib/librsvg-2.so".
```

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.14.234-gb1e89e69b2d0-ab7709096 #1 SMP PREEMPT Tue Sep 7 06:24:27 UTC 2021 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 4a
```

**Comment by alive4ever** [comment]
Some programs are affected, for example links web browser.

```
~ $ links
CANNOT LINK EXECUTABLE "links": cannot locate symbol "__multf3" referenced by "/data/data/com.termux/files/usr/lib/librsvg-2.so"...
```

**Comment by xtkoba** [comment]
I suppose this may be fixed with `librsvg 2.52.1-2`, which does not seem to be uploaded yet.

**Comment by xtkoba** [comment]
Ah, the problem seems to be that `librsvg` fails to build.

**Comment by Grimler91** [comment]
Upstream issue regarding build failure: https://gitlab.gnome.org/GNOME/librsvg/-/issues/820

**Comment by Grimler91** [comment]
The arm error in https://github.com/termux/termux-packages/runs/4517220605 is identical to the error message in https://gitlab.gnome.org/GNOME/librsvg/-/issues/820 (with ndk r21)

**Comment by xtkoba** [comment]
Built successfully for aarch64 by disabling static. You can download the package archive from https://github.com/termux/termux-packages/actions/runs/1576840012.

Still working on for arm.
