### ISSUE TITLE
[Bug]: librsvg does not compile for aarch64 and arm format (github action)

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#8239]
### Problem description

[action link](https://github.com/Maxython/termux-packages-pacman/actions/runs/1576717260)

### What steps will reproduce the bug?

Updating package files ([link to commit](https://github.com/Maxython/termux-packages-pacman/commit/f81e8f114ee8c3ffe5ba0a5cf46661bb76493e2f))

### What is the expected behavior?

Successful compilation

### System information

This is a github action

**Comment by xtkoba** [comment]
This blocks #8235.

**Comment by Grimler91** [comment]
Lets track it in https://github.com/termux/termux-packages/issues/8235
