### ISSUE TITLE
[Bug]: pulseaudio won't compile, invalid directory (github action)

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#8248]
### Problem description

In build.sh, the directory is invalid, causing the error.  
[github action](https://github.com/Maxython/termux-packages-pacman/runs/4502374880?check_suite_focus=true)
[line build.sh](https://github.com/termux/termux-packages/blob/master/packages/pulseaudio/build.sh#L40)

### What steps will reproduce the bug?

Empty commit

### What is the expected behavior?

Successful compilation

### System information

This is a github action

**Comment by xtkoba** [comment]
`libaaudio.so`s are now placed at:

```
$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/26/libaaudio.so
$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/26/libaaudio.so
$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android/26/libaaudio.so
$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android/26/libaaudio.so
```

**Comment by Ladla-saith** [comment]
What I Doo🙄
