### ISSUE TITLE
Packages for Python and Ruby libraries with C extensions???

### ISSUE THREAD

**Issue by GreenJoey** [termux/termux-packages#827]
Can any one build and maintain Python and Ruby libraries that has C extensions. These libraries have external C dependencies which are not detected gems and pip also these packages take a lot of to compile from source and a binary package with all the dependencies resolved with a nice additions for Termux and Python and Ruby developers???

**Comment by fornwall** [comment]
As a general rule no - it would be a big overhead having to maintain hundreds of Python and Ruby libraries.

Individual exceptions can always be made for noteworthy libraries on a case by case basis.

**Comment by GreenJoey** [comment]
I asking for the note worthy ones only. Libraries like numpy, scipy, scikylearn, Cython from Python and libraries like nokogiri and Puma from Ruby

**Comment by its-pointless** [comment]
i have numpy and scipy https://github.com/its-pointless/gcc_termux
But only because scipy requires a fortran compiler.
