### ISSUE TITLE
[Bug]: Checking availability of current mirror: ok Reading package lists... Done Building dependency tree... Done Reading state information... Done qt5-qttools is already the newest version (5.12.11-3). qt5-qttools set to manually installed. You might want to run 'apt --fix-broken install' to correct these. The following packages have unmet dependencies:  xournal : Depends: poppler but it is not going to be installed E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

### ISSUE THREAD

**Issue by Dwebb22** [termux/termux-packages#8275]
### Problem description

Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
qt5-qttools is already the newest version (5.12.11-3).
qt5-qttools set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 xournal : Depends: poppler but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

### What steps will reproduce the bug?

idk

### What is the expected behavior?

pkg install

### System information

termux-info:

```

```
termux terminal, basic

**Comment by xtkoba** [comment]
Try

```
$ apt --fix-broken install
```

**Comment by xtkoba** [comment]
Seems like `poppler 21.08.0-2` is not available. Maybe hitting #8157? Then I will try to rebuild it.

**Comment by xtkoba** [comment]
Now `poppler` is successfully rebuilt. Please try again and report back whether the issue is solved.

**Comment by muyiboysaka123** [comment]
Muyideen
