### ISSUE TITLE
[Package]: Tizonia

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#8284]
### Package description

A powerful cloud music player for the Linux terminal, with support for Spotify (Premium), Google Play Music (free and paid tiers), SoundCloud, YouTube, TuneIn and iHeart radios, Plex servers and Chromecast devices.
The world's first implementation of OpenMAX IL 1.2.

### Home page URL

https://tizonia.org

### Source code URL

https://github.com/tizonia/tizonia-openmax-il

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by tathastu871** [comment]
Dependencies:
```
mpg123 mpg123-static boost boost-static python libsqlite libsqlite-static sqlite dbus dbus-static libev libmad liboggz liboggz-static libopus libopus-static opusfile opusfile-static
```
Missing dependencies:
```
log4c 
```
Installing missing dependencies:
```
wget http://prdownloads.sourceforge.net/log4c/log4c-1.2.4.tar.gz && tar xvf log4c-1.2.4.tar.gz && rm log4c-1.2.4.tar.gz && cd log4c-1.2.4 && ./configure --prefix=$PREFIX && make -j8 && make install

```
Steps:
```
wget https://github.com/tizonia/tizonia-openmax-il/archive/refs/tags/v0.22.0.tar.gz
tar xvf v0.22.0.tar.gz && rm v0.22.0.tar.gz
cd tizonia-openmax-il-0.22.0
meson build
```
Errors:
```
meson.build:90:0: ERROR: Invalid version of dependency, need 'uuid' ['>=2.19.0'] found '1.0.3'.
```

**Comment by buribu** [comment]
duplicate #2152
