### ISSUE TITLE
[Package]:  mlt framework &   jack1 & jack2

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#8289]
### Package description

Jack-Audio Connection Kit

### Home page URL
https://www.mltframework.org/;
https://www.jackaudio.org

### Source code URL
https://github.com/mltframework/mlt/;
https://github.com/jackaudio/jack2/; https://github.com/jackaudio/jack1/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by BeatVids** [comment]
Hi @tathastu871, is MLT working on Termux for you?
