### ISSUE TITLE
Re-enable libunwind package

### ISSUE THREAD

**Issue by qmfrederik** [termux/termux-packages#829]
There's a libunwind package in the Termux sources but it is currently disabled because of build issues

libunwind/libunwind#6 was just merged which should fix building libunwind on Android.

An example of how libunwind can be compiled using the NDK is here:
[`build-android-rootfs.sh:150`](https://github.com/dotnet/coreclr/blob/master/cross/build-android-rootfs.sh#L150)

The libunwind package would be used by .NET Core which relies on Termux packages for its Android build.

**Comment by fornwall** [comment]
@qmfrederik Two things:

1. Do you want to have a snapshot of latest git master for libunwind, or should 1.2 be used with https://github.com/libunwind/libunwind/pull/6 applied? I'm fine with tracking git master so we can easier pickup fixes if you are.

2. I'm hitting another issue when building:

```
/home/builder/.termux-build/libunwind/src/src/coredump/_UCD_create.c:299:22: error: incomplete definition of type
      'struct non_existent'
  return ui->prstatus->pr_pid;
         ~~~~~~~~~~~~^
/home/builder/.termux-build/libunwind/src/src/coredump/_UCD_internal.h:93:12: note: forward declaration of 'struct non_existent'
    struct PRSTATUS_STRUCT *prstatus; /* points inside note_phdr */
           ^
/home/builder/.termux-build/libunwind/src/src/coredump/_UCD_internal.h:82:25: note: expanded from macro 'PRSTATUS_STRUCT'
#define PRSTATUS_STRUCT non_existent
                        ^
/home/builder/.termux-build/libunwind/src/src/coredump/_UCD_create.c:304:22: error: incomplete definition of type
      'struct non_existent'
  return ui->prstatus->pr_cursig;
         ~~~~~~~~~~~~^
/home/builder/.termux-build/libunwind/src/src/coredump/_UCD_internal.h:93:12: note: forward declaration of 'struct non_existent'
    struct PRSTATUS_STRUCT *prstatus; /* points inside note_phdr */
           ^
/home/builder/.termux-build/libunwind/src/src/coredump/_UCD_internal.h:82:25: note: expanded from macro 'PRSTATUS_STRUCT'
#define PRSTATUS_STRUCT non_existent
```

Do you have any idea about a fix for this?

**Comment by vishalbiswas** [comment]
@fornwall elf_prstatus is in linux/elfcore.h
Cannot include it. Might want to copy over struct definition.

**Comment by qmfrederik** [comment]
@fornwall Yeah, what @vishalbiswas said - can you try with these configure flags:

```
--disable-tests --disable-coredump
```

and see if you can get it to compile?

**Comment by qmfrederik** [comment]
@fornwall and to your first question :), I would go for master - there's https://github.com/libunwind/libunwind/pull/6 and https://github.com/libunwind/libunwind/commit/cf6382643efd133e617c2cf1dba7e53868ccd690 which are required for libunwind to work on Android, both are not included in the last release.

**Comment by fornwall** [comment]
@qmfrederik Thanks, `--disable-coredump` made it build!

A libunwind package, built from the [current git master](https://github.com/libunwind/libunwind/commit/2b8ab794b3a636c05396fdbaebbba25d8aa4722a), is now available in the apt package repository. Create an issue if it needs updating or fixing!

**Comment by qmfrederik** [comment]
Thanks!

**Comment by zorrobyte** [comment]
Still broken @fornwall 
1 warning and 1 error generated.
make[2]: *** [Makefile:3862: mi/backtrace.lo] Error 1
1 error generated.
In file included from mi/dyn-cancel.c:26:
In file included from ../include/libunwind_i.h:51:
In file included from ../include/libunwind.h:7:
../include/libunwind-aarch64.h:195:2: error: unknown type name '__sigset_t'; did you mean 'sigset_t'?
        __sigset_t uc_sigmask;
        ^~~~~~~~~~
        sigset_t
/data/data/com.termux/files/usr/include/asm-generic/signal.h:79:3: note: 'sigset_t' declared here
} sigset_t;
  ^

when trying with configure flags, after renaming sigset, it still errors
./configure --prefix=/data/data/com.termux/files/usr --disable-tests --disable-coredump

fpreg.lo mi/Lset_caching_policy.lo mi/Lset_cache_size.lo  aarch64/Lapply_reg_state.lo aarch64/Lreg_states_iterate.lo aarch64/Lcreate_addr_space.lo aarch64/Lget_proc_info.lo aarch64/Lget_save_loc.lo aarch64/Lglobal.lo aarch64/Linit.lo aarch64/Linit_local.lo aarch64/Linit_remote.lo aarch64/Lis_signal_frame.lo aarch64/Lregs.lo aarch64/Lresume.lo aarch64/Lstash_frame.lo aarch64/Lstep.lo aarch64/Ltrace.lo aarch64/getcontext.lo libunwind-dwarf-local.la libunwind-elf64.la -lc -lgcc_s -llzma 
libtool: link: gcc -shared  -fPIC -DPIC  .libs/os-linux.o mi/.libs/init.o mi/.libs/flush_cache.o mi/.libs/mempool.o mi/.libs/strerror.o aarch64/.libs/is_fpreg.o aarch64/.libs/regname.o mi/.libs/backtrace.o mi/.libs/dyn-cancel.o mi/.libs/dyn-info-list.o mi/.libs/dyn-register.o mi/.libs/Ldyn-extract.o mi/.libs/Lfind_dynamic_proc_info.o mi/.libs/Lget_accessors.o mi/.libs/Lget_proc_info_by_ip.o mi/.libs/Lget_proc_name.o mi/.libs/Lput_dynamic_unwind_info.o mi/.libs/Ldestroy_addr_space.o mi/.libs/Lget_reg.o mi/.libs/Lset_reg.o mi/.libs/Lget_fpreg.o mi/.libs/Lset_fpreg.o mi/.libs/Lset_caching_policy.o mi/.libs/Lset_cache_size.o aarch64/.libs/Lapply_reg_state.o aarch64/.libs/Lreg_states_iterate.o aarch64/.libs/Lcreate_addr_space.o aarch64/.libs/Lget_proc_info.o aarch64/.libs/Lget_save_loc.o aarch64/.libs/Lglobal.o aarch64/.libs/Linit.o aarch64/.libs/Linit_local.o aarch64/.libs/Linit_remote.o aarch64/.libs/Lis_signal_frame.o aarch64/.libs/Lregs.o aarch64/.libs/Lresume.o aarch64/.libs/Lstash_frame.o aarch64/.libs/Lstep.o aarch64/.libs/Ltrace.o aarch64/.libs/getcontext.o  -Wl,--whole-archive ./.libs/libunwind-dwarf-local.a ./.libs/libunwind-elf64.a -Wl,--no-whole-archive  -lc -lgcc_s -llzma  -g -O2 -nostartfiles -nostdlib   -Wl,-soname -Wl,libunwind.so.8 -o .libs/libunwind.so.8.0.1
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: cannot find -lgcc_s
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:3271: libunwind.la] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/libunwind/src'
make[1]: *** [Makefile:4009: install] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/libunwind/src'
make: *** [Makefile:602: install-recursive] Error 1
