### ISSUE TITLE
[Package]: lnav

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#8293]
### Package description

Log file navigator

### Home page URL

https://lnav.org

### Source code URL

https://github.com/tstack/lnav

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by tathastu871** [comment]
While compiling make step throws
```undeclared identifier inflatePrime. Did you mean inflateInit.``` 
Tried declaring 
```ZEXTERN int ZEXPORT inflatePrime OF((z_streamp strm, char * bits, unsigned char value));```
But then it says undefined symbol inflatePrime. #include <zlib.h>, #import "zlib.h" are also defined. 
Help needed.

**Comment by xtkoba** [comment]
`inflatePrime` is defined in `lib/libz.so`:

```
$ readelf -Wa lib/libz.so|grep inflatePrime
    83: 0000000000006c28   148 FUNC    GLOBAL DEFAULT   11 inflatePrime@@ZLIB_1.2.2.4
```
