### ISSUE TITLE
python package doesn't include pyvenv

### ISSUE THREAD

**Issue by nyuszika7h** [termux/termux-packages#83]
Since version 3.3, Python comes with `pyvenv`, but it's not included in the Termux package. It could be a separate package too, but it would be nice if you could include it, though I can use `virtualenv` for now.

**Comment by fornwall** [comment]
I've updated the python package to keep pyvenv in version 3.5.1-1 of the package. Could you update with

    apt update &&apt upgrade

and check out of it works ok?

**Comment by nyuszika7h** [comment]
It works, thanks!

**Comment by hastebrot** [comment]
Seems the update with `apt update && apt upgrade` which updated the package Python 3.5.1 to 3.5.1-1 causes `ranger` to not work anymore.

~~~
$ ranger
...
ImportError: No module named 'ranger'
~~~

Will try to reinstall ranger.

**Comment by fornwall** [comment]
@hastebrot Thanks for the information! There's a bug in the python package, which has a trigger to cleanup __pycache__ folders on each upgrade/uninstall of the package, which unfortunately removes too much causing e.g. ranger needing to be re-installed after an update of python.

I create https://github.com/termux/termux-packages/issues/87 for that!
