### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "gcc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...

### ISSUE THREAD

**Issue by ravi123-lab** [termux/termux-packages#8300]
### Problem description

CANNOT LINK EXECUTABLE "gcc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...

### What steps will reproduce the bug?

CANNOT LINK EXECUTABLE "gcc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...

### System information

termux-info:

```

```
CANNOT LINK EXECUTABLE "gcc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...

**Comment by xtkoba** [comment]
Update dependencies, including `libc++`.
