### ISSUE TITLE
[Package]: libcddb

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#8305]
### Package description

```
TERMUX_PKG_HOMEPAGE=http://libcddb.sourceforge.net/
TERMUX_PKG_DESCRIPTION="Libcddb is a C library to access data on a CDDB server"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_VERSION=1.3.2
TERMUX_PKG_SRCURL=http://prdownloads.sourceforge.net/libcddb/libcddb-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=35ce0ee1741ea38def304ddfe84a958901413aa829698357f0bee5bb8f0a223b
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--disable-static --build=aarch64-unknown-linux-gnu"
```

Please someone test and pull PR. 
When i normally install it works but using above script it fails throwing ./config.status: 1324: shift: can't shift that many.

### Home page URL

http://libcddb.sourceforge.net/

### Source code URL

http://prdownloads.sourceforge.net/libcddb/libcddb-1.3.2.tar.bz2

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
`shift: can't shift that many.` should be resolved by

```bash
termux_step_pre_configure() {
	autoreconf -fi
}
```

See also https://bugs.gentoo.org/show_bug.cgi?id=528012.
