### ISSUE TITLE
[Bug]: Termux-API programs are all freezing

### ISSUE THREAD

**Issue by Miepee** [termux/termux-packages#8320]
### Problem description

Whenever executing any programs from the termux-api package (for example `termux-battery-status`, or `termux-brightness 100`) the application freezes and has to be killed via CTRL+C.

### What steps will reproduce the bug?

- download the package via `pkg install termux-api`
- execute a binary that this package provides (i.e. `termux-clipboard-get`)

### What is the expected behavior?

The applications should not freeze, but execute their behaviour *or* provide an error message.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 4.1.18-g1b717f5 #1 SMP PREEMPT Tue Dec 4 14:20:03 CST 2018 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
BLN-L21
```

EDIT: new to this, i just saw that [termux-api-issues](https://github.com/termux/termux-api/issues) exists, should i close it here and reopen it there instead?
EDIT 2: Apparently there are already [two](https://github.com/termux/termux-api/issues/369) open [issues](https://github.com/termux/termux-api/issues/466) for these.

**Comment by xeffyr** [comment]
`termux-api` is not standalone package. It just a CLI frontend for https://f-droid.org/en/packages/com.termux.api/.

**Comment by Miepee** [comment]
Ah I see
The wiki stated this:
> In Google Play Store, besides installing the Termux app, also install "Termux:API" app. This solves the hanging issue described below on Android 7. 

This made it seem like the Termux:API was only required for the GPS version. Thanks for clarifying, worked for me now!

**Comment by xeffyr** [comment]
Someone deleted the "installation" section on Wiki: https://wiki.termux.com/index.php?title=Termux:API&curid=17&diff=6456&oldid=6425. I will resolve that issue later.

**Comment by WMCB-Tech** [comment]
> Ema is the name individuals use to call me and I completely adore this name. Invoicing is what he does for a residing. What he loves performing is performing archery and he'll be starting some thing else alongside with it. I currently live in Florida. Check out the newest information on his web site: https://woori88.com

> Here is my web page ... 바카라

should the wiki is restricted public edits for everyone? seems some people vandalize it

**Comment by agnostic-apollo** [comment]
Yeah, this kinda thing is dangerous and random people can put dangerous commands in. It should definitely be restricted. Anyways, I'll slowly be phasing out the wiki and moving everything to github pages, starting with next `termux-app` release for some stuff, with support for local documentation viewing, so should ultimately solve such issues.

**Comment by anonghuser** [comment]
there should really be a note somewhere about needing to install an extra app, either upon installing the package, or upon trying to run programs from it when the app is missing.
