### ISSUE TITLE
[Bug]: binutils: gas outpus empty elf data if the first line is a comment

### ISSUE THREAD

**Issue by Alto1772** [termux/termux-packages#8330]
### Problem description

GNU assembler breaks if the first line is a comment and in the first column only the # character, without any whitespaces before it. It does not include the `#NOAPP` or `#APP` directives.

A solution/patch for this is to change the input buffer length from 32768 `(32 * 1024)` to 4096 `(4 *1024)` in gas/input-file.c and gas/app.c.

### What steps will reproduce the bug?

- Run the command `as test.s` with the file test.s below.
```
# A comment
.section .data
.word 0x12345678
.byte 0x98, 0x76, 0x54, 0x32
```
- Gas issues a warning that is in EOF without newline in the first comment despite having more contents in the next line.
```
test.s: Assembler messages:
test.s: Warning: end of file in comment; newline inserted
```
- And the generated elf file's sections are empty:
```
$ readelf -x .data a.out
Section '.data' has no data to dump.
```

### What is the expected behavior?

```
$ readelf -x .data a.out

Hex dump of section '.data':
  0x00000000 78563412 98765432                   xV4..vT2
```

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
termux-api/stable 0.57 aarch64 [upgradable from: 0.56]
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Wed Nov 3 11:07:51 CST 2021 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
JNY-LX1

```

_I think it only affects on my device, not sure about the others._

**Comment by xeffyr** [comment]
GAS comments are architecture-dependent. For ARM or AArch64 use `@`.

Character `#` has special meaning in assembly syntax.

**Comment by xeffyr** [comment]
Sorry, `@` is comment character only for ARM 32bit. I will merge the [PR](https://github.com/termux/termux-packages/pull/8331) if it really fixes the issue. Wondering if that's known upstream issue.
