### ISSUE TITLE
Package request : cling 

### ISSUE THREAD

**Issue by hnmn** [termux/termux-packages#834]
Interactive c++ intepreter

**Comment by pschwede** [comment]
It's binary packages are > 300MB, are you sure about your request?

**Comment by hnmn** [comment]
Yes @pschwede , if you build it show me

**Comment by wangmu0579** [comment]
Jupyter Notebook can be installed in Termux.
Its quite good if cling can combine with Jupyter. 
THanks.

**Comment by wangmu0579** [comment]
Build Cling success but execute still have problem. Maybe valuable try to use termux build packages tool chain.
clang-tblgen  cling  llvm-lit  llvm-tblgen
%n@%m:%~%# ./cling
WARNING: linker: /data/data/com.termux/files/home/GitHub/cling-build/builddir/bin/cling: unused DT entry: type 0xf arg 0x275d2e
In file included from input_line_1:1:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/new:88:
/data/data/com.termux/files/usr/bin/../include/c++/v1/__config:169:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ int a = 5;
[cling]$ a;
[cling]$ a
Segmentation fault
%n@%m:%~%#

**Comment by Manouchehri** [comment]
@hnmn What was the reason this ticket was closed? Isn't `cling` still broken?

**Comment by hnmn** [comment]
@Manouchehri 
issue was steal 2 years so i just closed it
and 
i didn't know about cling is broken or not 
if you want we can reopen it
