### ISSUE TITLE
[Bug]: cadaver and gauche packages do not compile (github action)

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#8342]
### Problem description

[Action cadaver](https://github.com/Maxython/termux-packages-pacman/actions/runs/1622489742)  
[Action gauche](https://github.com/Maxython/termux-packages-pacman/actions/runs/1622489737)

### What steps will reproduce the bug?

Auto update from main repo

### What is the expected behavior?

successful compilation

### System information

this is github action

**Comment by Grimler91** [comment]
Well clearly some commits are missing from your repo: https://github.com/termux/termux-packages/commit/332d24ba2b1f8abf8cd10c63ec90d6aa076ab80e, https://github.com/termux/termux-packages/commit/db9805f21f75e5704b1e0f7fafa8b481698980ed

**Comment by Grimler91** [comment]
The libneon commit is there, but was added after cadaver

**Comment by Grimler91** [comment]
And the gauche commit is some variant of the one in termux-packages, where the failing patch wasn't updated

**Comment by Maxython** [comment]
Ok, thank
