### ISSUE TITLE
[Package]: cdrtools

### ISSUE THREAD

**Issue by KhaeWa** [termux/termux-packages#8344]
### Package description

Original cdrtools supporting CD, DVD and BluRay burning.

### Source code URL

http://cdrtools.sourceforge.net/private/cdrecord.html

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Related to (or possibly a duplicate of) #7465.
