### ISSUE TITLE
[Package]: wavpack

### ISSUE THREAD

**Issue by KhaeWa** [termux/termux-packages#8346]
### Package description

Audio compression format with lossless, lossy and hybrid compression modes.

### Home page URL

http://www.wavpack.com/

### Source code URL

http://www.wavpack.com/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by tathastu871** [comment]
Requires uchardet from itspointless repo
```
TERMUX_PKG_HOMEPAGE=https://github.com/flacon/flacon
TERMUX_PKG_DESCRIPTION="Audio File Encoder. Extracts audio tracks from an audio CD image to separate tracks."
TERMUX_PKG_LICENSE=LGPL-2.1
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=8.2.0
TERMUX_PKG_SRCURL=https://github.com/flacon/flacon/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=7fd0f97f9bca87c5ec0f7eee30c6480b9cc51c8c60f79d9726ed09db756c60b9
TERMUX_PKG_DEPENDS="qt5-qtbase, qt5-qttools, uchardet, uchardet-static, taglib"
TERMUX_PKG_FORCE_CMAKE=true
```
Tested on aarch64 on device build ---works

**Comment by xtkoba** [comment]
@tathastu871 That should go to another issue.

**Comment by tathastu871** [comment]
> @tathastu871 That should go to another issue.

Sorry, corrected
