### ISSUE TITLE
postges-dev or python-psycopg2 

### ISSUE THREAD

**Issue by zcattacz** [termux/termux-packages#835]
It would be nice to have tool like pgcli running on the phone. With which you can inspect database on the run. The auto completion features will be really handy on small devices. But most Python postgesql tools use psycopg2 package for better performance , which requires binary packages from postgesql.

**Comment by fornwall** [comment]
There is already a `postgresql-dev` package available!

If you install that, and the necessary other packages (hopefully the below should be enough):

    packages install postgresql-dev python-dev make clang

you should be able to install psycopg2 with

    pip install psycopg2

**Comment by zcattacz** [comment]
thanks thats really good news. is it really nucessary to depend on postgresql ?

**Comment by fornwall** [comment]
@zcattacz Currently the postgresql package is not split up into the having the client library in a separate package, so you need the full postgresql package (around 17 MB).

Are you going to use pgcli for a non-local database?

**Comment by zcattacz** [comment]
yeah... i guess its not good to run a full fledged database on my phone? i used to try ssh. but since the server is running windows. the cygwin based ssh environment feels so laggy on every shell command, i give them up all together.
ok i will install both.

@fornwall, do you think it possible to install packages from debian-armel repositories?
which debian version is mosrlikely to be abi compatible ?  i just noticed that none of the ecc ciphers seems to be supported in the ssh package in termux.

**Comment by fornwall** [comment]
@zcattacz Ok, interesting use case! We may split up the client side of postgresql from the server side to save some space (running a database server on your phone would only be for exploration/development).

About installing debian packages: It will not work, due to differences in paths, libc, linker and shared libraries. However, for ssh it shouldn't be necessary - ECC should already be available in the current ssh package (see `ssh -Q kex`), unless I'm missing something.

**Comment by zcattacz** [comment]
sorry, my bad. it works now. i have no idea why though.
the administrator updated the server key from rsa to ed25519. so i updated mine too. i have both rsa and ed25519 key in termux. yesterday. ssh asks about password for the rsa key. when i just press enter to skip, it failed directly. now it falls back to ed25519 key as expected.
thanks

**Comment by emptix0** [comment]
@fornwall thanks

**Comment by emptix0** [comment]
@fornwall thanks

**Comment by illvart** [comment]
> There is already a `postgresql-dev` package available!
> 
> If you install that, and the necessary other packages (hopefully the below should be enough):
> 
> ```
> packages install postgresql-dev python-dev make clang
> ```
> 
> you should be able to install psycopg2 with
> 
> ```
> pip install psycopg2
> ```

```sh
pkg install postgresql python make clang
pip3 install psycopg2
``
