### ISSUE TITLE
i use weechat a lot and i have a bluetooth-keyboard so i implemented some changes [enhancement]

### ISSUE THREAD

**Issue by taschendieb** [termux/termux-packages#836]
no bluetooth-keyboard present and softkeyboard not visible -> single tap means show softkeyboard
no bluetooth-keyboard present and softkeyboard visible -> single tap means scan for urls list them to choose wich to open in browser

bluetooth-keyboard present and softkeyboard not visible -> single tap always means scan for urls list them to choose wich to open in browser / softkeyboard is always hidden

**Comment by fornwall** [comment]
Have you implemented the changes yourselves? If so, you can share the code!

You can do that against the https://github.com/termux/termux-app repo, which contains the app itself - this repo is only for packages.
