### ISSUE TITLE
Package request : glances

### ISSUE THREAD

**Issue by ybudimirov** [termux/termux-packages#837]
Could you please add glances (https://github.com/nicolargo/glances) to termux-packages.

I have tried install it via pip:
apt update
apt upgrade
apt install clang python python-dev
pip install glances

Glances works but have issues with text:

Screenshot: https://cloud.githubusercontent.com/assets/12114831/23835256/cd7a7360-076c-11e7-84e2-142749fb2e57.png

**Comment by fornwall** [comment]
Thanks! As a general principle we try to avoid packaging things installable through pip, to avoid the maintenance overhead.

As for the rounding issues I think you should report them to the https://github.com/nicolargo/glances project!
