### ISSUE TITLE
[Package]: gnucobol

### ISSUE THREAD

**Issue by Melind4** [termux/termux-packages#8379]
### Package description

A free/libre COBOL compiler

### Home page URL

https://gnucobol.sourceforge.io/

### Source code URL

https://sourceforge.net/p/gnucobol/code/HEAD/tree/tags/gnucobol-3.1.2/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

there is a mirror on github -> https://github.com/paulsmith/gnucobol
https://www.techrepublic.com/article/cobol-programmers-are-in-demand-to-fight-the-coronavirus-pandemic/

**Comment by tathastu871** [comment]
build.sh (Not complete)
```
TERMUX_PKG_HOMEPAGE=https://www.gnu.org/software/gnucobol/
TERMUX_PKG_DESCRIPTION="Free COBOL Compiler"
TERMUX_PKG_LICENSE=GPL-3.0
TERMUX_PKG_LICENSE_FILE=COPYING
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=3.1.2
_REAL_VERSION="$(cut -f1,2 -d '.' <<< ${TERMUX_PKG_VERSION})"
TERMUX_PKG_SRCURL=https://sourceforge.net/projects/gnucobol/files/gnucobol/${_REAL_VERSION}/gnucobol-${TERMUX_PKG_VERSION}.tar.gz/download
TERMUX_PKG_SHA256=f38c60b38a9e404bcba709b61b46f2bafa146b5f3dd90a94b2a70f5cea2f6297
TERMUX_PKG_DEPENDS="libgmp, libxml2, cJson, flex, flex-gstatic, bison, ncurses*, libiconv, help2man"
termux_step_pre_configure() {
	cd ${TERMUX_PKG_SRCDIR} && autoreconf -vfi
}
```
@xtkoba 
Please review the script manually make install works. But when building using Termux-build system it fails showing missing folder

**Comment by xtkoba** [comment]
@tathastu871 Not my job.

**Comment by tathastu871** [comment]
> @tathastu871 Not my job.
You were making more PR in last few days. Thats why i referred you. sorry
