### ISSUE TITLE
hunspell doesn't start

### ISSUE THREAD

**Issue by Mihara** [termux/termux-packages#838]
```
[@localhost:~] $ hunspell
Can't open affix or dictionary files for dictionary named "en_US".
[@localhost:~] 1 $ apt list | grep hunspell

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

hunspell/stable,now 1.6.0 aarch64 [installed]
hunspell-dev/stable 1.6.0 aarch64
hunspell-en-us/stable,now 2017.03.03 all [installed]
```
It worked fine before, though telling you when exactly did it stop would be a problem. As you can see, the dictionary *is* installed, and I just reinstalled them both just in case. No dice.

Setting `DICPATH=/data/data/com.termux/files/usr/share/hunspell` does *not* improve the situation.

**Comment by fornwall** [comment]
Thanks a lot for reporting!

This has now been fixed in version `2017.03.03-1` of the `hunspell-en-us` package, which is available as an update in the apt package repository.
