### ISSUE TITLE
[Bug]: npm install Exit handler never called!

### ISSUE THREAD

**Issue by BennettChina** [termux/termux-packages#8387]
### Problem description

I use `npm install` and I get this:

```
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-12-29T01_28_01_927Z-debug.log
```

when I ignore it and run `npm run serve`, I get this: 

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/data/data/com.termux/files/home/Adachi-BOT/...'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)                                   at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {         code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### What steps will reproduce the bug?

- run `npm i`
- run `npm run serve`

### What is the expected behavior?

✔ All packages installed (590 packages installed from npm registry, used 23s(network 8s), speed 3.32MB/s, json 516(3.12MB), tarball 23.35MB)

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64                                                 Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)                  deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)            deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:                                     All packages up to date
Android version:
11
Kernel build information:
Linux localhost 5.4.86-qgki-g35572e50a678 #1 SMP PREEMPT Wed Oct 27 03:18:25 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2102K1AC
```

I use `nodejs-lts`
- node: `v16.13.1`
- npm: `8.1.2`

I try use `nodejs`, but I still get it.
- node: `v17.3.0`
- npm: `8.3.0`

**Comment by vishalbiswas** [comment]
Try with `npm install --foreground-scripts`, it will show the real error.

For more info, see https://github.com/npm/statusboard/issues/395#issuecomment-1003256492

**Comment by BennettChina** [comment]
> Try with `npm install --foreground-scripts`, it will show the real error.
> 
> For more info, see [npm/statusboard#395 (comment)](https://github.com/npm/statusboard/issues/395#issuecomment-1003256492)

```
[##################] | reify:typescript: timing reifyNo
> puppeteer@10.0.0 install
> node install.js

/data/data/com.termux/files/home/Adachi-BOT/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: Unsupported platform: android
```

Can this problem be solved?

**Comment by WMCB-Tech** [comment]
> Error: Unsupported platform: android

interesting error at the end, this could be probably fixed by force adding support for android, could you run `npm` again but with `--force`?

**Comment by BennettChina** [comment]
> > Error: Unsupported platform: android
> 
> interesting error at the end, this could be probably fixed by force adding support for android, could you run `npm` again but with `--force`? not sure how this helps but probably it's my guess

I run `npm install --force`, but it's not ok. 

![image](https://user-images.githubusercontent.com/48208644/147805543-4d4c6c65-9413-4756-b3d2-71e3ca98acc3.png)

![image](https://user-images.githubusercontent.com/48208644/147805516-6ebf4cee-2d89-45fc-b9ad-3e0ab6262d3b.png)

**Comment by thunder-coding** [comment]
> Try with `npm install --foreground-scripts`, it will show the real error.
> 
> For more info, see [npm/statusboard#395 (comment)](https://github.com/npm/statusboard/issues/395#issuecomment-1003256492)

This `--foreground-scripts` hack seems to be a new one and probably means that npm doesn't handle script execution of postinstall, preinstall and etc properly. If this is the catch, then we have got a clue on the npm exit code problem. Thanks for sharing this here

**Comment by vishalbiswas** [comment]
> > Try with `npm install --foreground-scripts`, it will show the real error.
> > 
> > For more info, see [npm/statusboard#395 (comment)](https://github.com/npm/statusboard/issues/395#issuecomment-1003256492)
> 
> This `--foreground-scripts` hack seems to be a new one and probably means that npm doesn't handle script execution of postinstall, preinstall and etc properly. If this is the catch, then we have got a clue on the npm exit code problem. Thanks for sharing this here
> 
> So for a temporary workaround until the problem is fixed upstream it would make sense to set `foreground-scripts` to true in post install step of nodejs, what do you say?

This slows down script execution quite a lot.
 Maybe upstream should add a message saying "Run with --foreground-scripts to debug" if any operation fails with this generic error

**Comment by truboxl** [comment]
It doesnt work for me. There is no noticeable change in the logging when installing emscripten after specifying `foreground-scripts true`.

**Comment by Wetitpig** [comment]
This seems to be a general problem of `npm` on all platforms.

One of the "solutions" which I have tested seems to be downgrading `npm` to version 6: https://github.com/npm/cli/issues/3577. I have not tested other methods mentioned on the page.

**Comment by vishalbiswas** [comment]
Or use yarn. That works well, too.

**Comment by thunder-coding** [comment]
> It doesnt work for me. There is no noticeable change in the logging when installing emscripten after specifying `foreground-scripts true`.

That's probably because the package-lock.json file for emscripten is generated with node 12.13.0 which ships with npm v6. Deleting the package-lock.json and doing just `npm install` works for v8 and should also for v7

**Comment by rodrigogs** [comment]
Apparently, you are trying to install puppeteer on termux. It will never work since termux has no chromium support. Remove puppeteer dependency and it should work.

**Comment by BennettChina** [comment]
> Apparently, you are trying to install puppeteer on termux. It will never work since termux has no chromium support. Remove puppeteer dependency and it should work.

`puppeteer` is the core dependency in this project. Maybe this project cannot be run directly on termux.

**Comment by rodrigogs** [comment]
If you really need puppeteer for this project, you might want to check this: https://github.com/rishabhrpg/puppeteer-on-termux
