### ISSUE TITLE
[Package]: Update dart sdk to latest stable version - 2.15.1

### ISSUE THREAD

**Issue by Mause** [termux/termux-packages#8389]
Can you please update the dart sdk to the latest stable version?

**Comment by feedSh** [comment]
What?😳😳😳😳😳😳

در تاریخ چهارشنبه, دسم ۲۹, ۲۰۲۱،‏ ۸:۱۸ قبل‌ازظهر Elliana May <
***@***.***> نوشت:

**Comment by dev-bz** [comment]
Me too, I wish to build 'gen-snapshot' with -arch arm64c as this might be useful for flutter engine
