### ISSUE TITLE
[Bug]: its showing issue when it installs any package and takes long time and it does not install the package

### ISSUE THREAD

**Issue by Sinumallu** [termux/termux-packages#8393]
### Problem description

its showing issue like this please solve this👉$ update && upgrade
No command update found, did you mean:
 Command lupdate in package qt5-tools from the x11-repo repository
$ apt update && upgrade
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  502  Bad Gateway
Get:1 https://packages.termux.org/apt/termux-main stable InRelease [14.0 kB]
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  502  Bad Gateway
Get:6 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages [326 kB]
Ign:6 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages
Get:6 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages [389 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

### What steps will reproduce the bug?

by installing the package

### What is the expected behavior?

it have to be fast and quick instalation

### System information

termux-info:

```

```

**Comment by Sinumallu** [comment]
please solve this quick

**Comment by thunder-coding** [comment]
Duplicate #6726
