### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Austcool-Walker** [termux/termux-packages#8399]
### Problem description

_chromium packages in proot segfault_

### What steps will reproduce the bug?

running ubuntu lxde desktop in termux with vnc or xserver app then running a chromium based browser or program with --no-sandbox

### What is the expected behavior?

the chromium based program or browser should open and give a warning that security will be less with the --no-sandbox flag but still will work fine...

### System information

termux-info:

```
~ $ termux-info
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.18.120 #1 SMP PREEMPT Mon Sep 7 17:13:02 EDT 2020 armv7l Android
Device manufacturer:
samsung
Device model:
SM-T380
~ $
```
info on how the fix the bug by building a new termux proot package can be found in this reddit thread here!
https://www.reddit.com/r/termux/comments/rra4im/-/hqfxuti

**Comment by xeffyr** [comment]
\-\-\> https://github.com/termux/proot/issues/107
