### ISSUE TITLE
Pulseaudio and zsh: insecure directories

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#840]
Pulseaudio creates the following folder if it doesn't already exist: `/data/data/com.termux/files/usr/share/zsh/site-functions`. But zsh needs the permissions on this folder to be 755 as opposed to the 770 that it has when Pulseaudio creates it. Otherwise it will print the following message each time `compinit`is called (which is routinely done in .zshrc's). 
```
$ zsh
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]?
```

 `chmod -R 755 $PREFIX/share/zsh/site-functions` fixes the problem locally, but it would be nice if Pulseaudio could create that directory with the correct permissions, or if zsh could create this directory on installation, so packages don't need to create it themselves. 

@ackalker

**Comment by fornwall** [comment]
Perhaps we can solve this generally in the build-package.sh script by using this simple rule when massaging what to include in packages:

1. Folders: 700
2. Executable files: 700
3. Non-executable files: 600

I guess zsh would be ok with 700 as well and not require 755?

Motivation:

- In general, the group permission doesn't matter as there is a one-to-one correspondence between users and groups on Android, AFAIK. So we could have the same group permission as user permission, but there is no point and e.g. zsh considers it insecure as noted here.

- We do not want any world-readable, writeable or executable files by default.

**Comment by Neo-Oli** [comment]
> I guess zsh would be ok with 700 as well and not require 755?
I just tested it with that directory and it seems fine with it.

**Comment by fornwall** [comment]
World readable, writeable or executable permissions are now removed in `build-package.sh`, so this fixes the problem for all packages built from now on (the pulseaudio package mentioned here has been revision-bumped so the problem is fixed there).
