### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GusZimgeneers** [termux/termux-packages#8404]
### Problem description

App Systemizer 
1 - Systemize Installed Apps (Listed)

No list of installed apps is displayed.  Not able to search by label either - not found.

Please help.

### What steps will reproduce the bug?

App Systemizer 
1 - Systemize Installed Apps (Listed)

No list of installed apps is displayed.  Not able to search by label either - not found.

Please help.

### System information

termux-info:

```

```

**Comment by spz2020** [comment]
hello see it https://github.com/termux/termux-packages/issues/6726

**Comment by spz2020** [comment]
open Settings>Apps> is Termux in it?

**Comment by xeffyr** [comment]
I don't know what is that `App Systemizer` you are talking about, but really that's not Termux package and never was a part of Termux project at all.
