### ISSUE TITLE
Unable to install F-droid version of termux.

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#8407]
Hello, probably not the proper place for this but hoping someone will be able to help me. My wife's Sony Xperia has the out of date Google play version of termux. I've backed it up and uninstalled it. I've then tried to install the F-droid version.  Both from F-droid directly and also by extracting my APK file. Both fail. Something like 'unable to install termux as name conflicts with an existing package'.
I assume it's Google play complaining or something like that
 Help appreciated.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation
