### ISSUE TITLE
ERROR: Wrong NDK version - we need 14

### ISSUE THREAD

**Issue by perry-amsterdam** [termux/termux-packages#841]
Hi,

I just did a new checkout, when i try to build a package.
Before it workerd, now i get the following build error:

./build-package.sh tinc
ERROR: Wrong NDK version - we need 14

Greetings Perry

**Comment by fornwall** [comment]
You need to install an updated NDK installation:

    rm -Rf $HOME/lib/android-ndk
    ./scripts/setup-android-sdk.sh

The above assumes that you haven't customized the NDK installation directory by setting the `NDK` environment variable - if so you should remove that one instead, `rm -Rf $NDK`.
