### ISSUE TITLE
[Package]: 24

### ISSUE THREAD

**Issue by dggame110** [termux/termux-packages#8410]
### Package description

N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

### Home page URL

https://termux.com/issues

### Source code URL

https://termux.com/issues

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

help me for this problem

**Comment by Grimler91** [comment]
https://github.com/termux/termux-packages/issues/6726
