### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "rustc"

### ISSUE THREAD

**Issue by hxse** [termux/termux-packages#8415]
### Problem description

When i run `rustc`, i get an error:
`CANNOT LINK EXECUTABLE "rustc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/librustc_driver-36225454e842a7c9.so"...`

### What steps will reproduce the bug?

pkg install rust
rustc

### System information

termux-info:

```
~ $ pkg install rust
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
rust is already the newest version (1.57.0).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
```
```
~ $ rustc
CANNOT LINK EXECUTABLE "rustc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/librustc_driver-36225454e842a7c9.so"...
Aborted

```

**Comment by xtkoba** [comment]
Did you update `libc++`?

**Comment by Grimler91** [comment]
> and 37 not upgraded.

Upgrade tour packages as @xtkoba said
