### ISSUE TITLE
[Bug]: Traceback (most recent call last):   File "/data/data/com.termux/files/usr/bin/login.py", line 10, in <module>     filepass = open("/data/data/com.termux/files/usr/share/login/.pass", "r") FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/share/login/.pass'

### ISSUE THREAD

**Issue by Hackster-Shah** [termux/termux-packages#8422]
### Problem description

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/login.py", line 10, in <module>
    filepass = open("/data/data/com.termux/files/usr/share/login/.pass", "r")
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/share/login/.pass'

### What steps will reproduce the bug?

When I enter the password 

### What is the expected behavior?

![Screenshot_2022-01-02-10-20-18-92](https://user-images.githubusercontent.com/96966302/147867000-3fe1d90a-6ad0-47e5-810c-fcf5ae342223.png)
When I enter password

### System information

termux-info:

```Android 7.1.1 oppo a83


```3/32

**Comment by sk0kanik** [comment]
It is not enter passward to access Termux. Surely you are using Third Party scripts. You should report it to the author of those scripts. It is not a problem from Termux side.

**Comment by sk0kanik** [comment]
You do not need to enter passward to access Termux. Surely you are using Third Party scripts. You should report it to the author of those scripts.

**Comment by Hackster-Shah** [comment]
I'm using this script
$ pkg install python2
$ pkg install git python
$ git clone https://github.com/RazorKenway/Termux-login.git
$ cd Termux-login
$ bash setup.sh

**Comment by Hackster-Shah** [comment]
Tell me what I can do.

**Comment by Hackster-Shah** [comment]
What I've to do?

**Comment by Hackster-Shah** [comment]
Now

**Comment by Hackster-Shah** [comment]
$ pkg install python2
$ pkg install git python
$ git clone https://github.com/RazorKenway/Termux-login.git
$ cd Termux-login
$ bash setup.sh

I'd used this script

**Comment by Hackster-Shah** [comment]
Thanks 😇

**Comment by sk0kanik** [comment]
> What I've to do?

@Hackster-Shah You can try this.
Open Termux in failsafe mode and run this
```
.. $ cd Termux-login
.. $ sh uninstall.sh
```

**Comment by Hackster-Shah** [comment]
I don't know about failsafe mode

**Comment by sk0kanik** [comment]
> I don't know about failsafe mode

@Hackster-Shah
https://wiki.termux.com/wiki/File:Termux-failsafe-recover.mp4

**Comment by Hackster-Shah** [comment]
This fail-safe mode option is not available on my device

**Comment by Hackster-Shah** [comment]
I'm using oppo a83 v7.1.1
3ram 32rom
