### ISSUE TITLE
[Package]: Update boost, ncmpcpp  and mpd 

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#8433]
### Package description

- [ ] boost 1.77.0-2 -> 1.78.0
- [x] ncmpcpp 0.8.2-22 -> 0.9.2
- [x] mpd 0.22.8-6 -> 0.23.5

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Note that we have to take extra care when bumping `boost`. Reverse dependencies can be easily broken.

**Comment by buribu** [comment]
> Note that we have to take extra care when bumping `boost`. Reverse dependencies can be easily broken.

It's true... this has already happened here. I solved it by creating a symbolic link with the name of the previous version of a library.
