### ISSUE TITLE
[Bug]: gnupg: pinentry-curses broken, pinentry-tty unavailable

### ISSUE THREAD

**Issue by rpxn** [termux/termux-packages#8437]
### Problem description

gnupg with pinentry-curses repeated prompts for a password, and no pinentry-tty is included with the package.

### What steps will reproduce the bug?

gpg -c somefile

### What is the expected behavior?

prompts and accepts password

### System information

termux-info:

```
Application version:
0.114
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.190-perf+ #1 SMP PREEMPT Fri Dec 10 18:38:29 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
GM1910
```

**Comment by Grimler91** [comment]
Works fine here on aarch64, android 11. It prompts for the password twice as it should.

Do you get any error message/warnings with the --verbose and --debug flag?
```
gpg --verbose --debug advanced -c somefile
```

**Comment by xeffyr** [comment]
If password is less than 8 characters, it will restart prompt. If terminal screen is too small, pintentry will omit all informational messages and will restart silently.

Resize the terminal screen to have more columns (80 recommended, though text will be small).

**This is not a bug!!!**

I've recorded the issue for better understanding:

https://user-images.githubusercontent.com/25881154/147916382-d687deb5-ded4-46dd-a6c0-c4544768e4d3.mp4

**Comment by rpxn** [comment]
Thanks for detailed explanation. It was indeed too short a password.
