### ISSUE TITLE
Unable to install 'pillow' module

### ISSUE THREAD

**Issue by prabhu1122** [termux/termux-packages#8442]
![Screenshot_2022-01-04-03-09-53-982_com termux](https://user-images.githubusercontent.com/31845530/147983444-d96af960-61e0-44ac-821f-180a9a0ab804.jpg)
![Screenshot_2022-01-04-03-09-39-714_com termux](https://user-images.githubusercontent.com/31845530/147983451-bf0e3b2b-e5ad-4247-aecc-8a14c4c1b9c5.jpg)
@phhusson

**Comment by phhusson** [comment]
Sounds like a typo? What does this have to do with me?

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/Python

You need build-essential, libjpeg-turbo and libpng packages in order to install Pillow module.
