### ISSUE TITLE
[Bug]: gettext: cannot locate symbol "__lttf2" referenced

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#8452]
### Problem description

In the gettext package, `msg*` commands do not work, and the following error is displayed on startup.
```bash
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/msgattrib": cannot locate symbol "__lttf2" referenced by "/data/data/com.termux/files/usr/lib/libgettextlib.so"...
```
Not working commands:
```
/data/data/com.termux/files/usr/bin/msgattrib
/data/data/com.termux/files/usr/bin/msgcat
/data/data/com.termux/files/usr/bin/msgcmp
/data/data/com.termux/files/usr/bin/msgcomm
/data/data/com.termux/files/usr/bin/msgconv
/data/data/com.termux/files/usr/bin/msgen
/data/data/com.termux/files/usr/bin/msgexec
/data/data/com.termux/files/usr/bin/msgfilter
/data/data/com.termux/files/usr/bin/msgfmt
/data/data/com.termux/files/usr/bin/msggrep
/data/data/com.termux/files/usr/bin/msginit
/data/data/com.termux/files/usr/bin/msgmerge
/data/data/com.termux/files/usr/bin/msgunfmt
/data/data/com.termux/files/usr/bin/msguniq
```

### What steps will reproduce the bug?

Running commands `msg*`

### What is the expected behavior?

Successful execution

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Server = https://s3.amazonaws.com/termux-main.pacman/aarch64
[x11]
Server = https://s3.amazonaws.com/termux-x11.pacman/aarch64
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.190-20995430-abT860XXU3CUB7 #2 SMP PREEMPT Thu Feb 25 18:11:04 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T860
```

**Comment by thunder-coding** [comment]
This seems to be device specific problem, I can't reproduce this.

Also `__lttf2` is defined in libc.so

```
$ nm /system/lib64/libc.so | grep __lttf2
00000000000b3578 t __lttf2
```
I also checked `/system/lib/libc.so` and it didn't include the symbol

**Comment by Grimler91** [comment]
It's probably the same as https://github.com/termux/termux-packages/issues/8029, so probably if we rebuild the package we get the same error

**Comment by xtkoba** [comment]
It turns out that `__lttf2` was leaking from `libunistring.so` (built with older NDK). Rebuilding both `libunistring` and `gettext` with current NDK fixes the issue (PR #8457).

**Comment by Maxython** [comment]
The error has not disappeared, apparently these are problems already in my compiler.
```zsh
➜  ~ pacman -Q gettext libunistring
gettext 0.21-4                                                                                                                  
libunistring 0.9.10-5
➜  ~ msgcat                                                                                                                        
CANNOT LINK EXECUTABLE "msgcat": cannot locate symbol "__lttf2" referenced by "/data/data/com.termux/files/usr/lib/libgettextlib.so"...
```

**Comment by Grimler91** [comment]
@Maxython how did you build the packages?

Re-building both packages from docker image worked for me, lttf2 is no longer undefined in libgettextlib.so
(libunistring 0.9.10-5 is missing from termux's repos at the moment though, re-building it now)

**Comment by Maxython** [comment]
> @Maxython how did you build the packages?
> 
> Re-building both packages from docker image worked for me, lttf2 is no longer undefined in libgettextlib.so (libunistring 0.9.10-5 is missing from termux's repos at the moment though, re-building it now)

My auto-update first updated the gettext directory and then libunistring.

**Comment by Grimler91** [comment]
> My auto-update first updated the gettext directory and then libunistring.

That explains it then. Seems like it would be better to make your updater apply and build new commits in the same order as they are in termux-packages

**Comment by Dx-Fahim** [comment]
Fahim
