### ISSUE TITLE
[Package]: coin-or Osi

### ISSUE THREAD

**Issue by Melind4** [termux/termux-packages#8459]
### Package description

Open Solver Interface

### Source code URL

https://github.com/coin-or/Osi

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

It is not possible to install coinor-clp without it.

coinor-clp: It depends: libcoinor-osi but it is not installable

**Comment by Grimler91** [comment]
Should be fixed once https://github.com/termux/termux-packages/actions/runs/1659310642 finishes
