### ISSUE TITLE
[Package]: CoinUtils

### ISSUE THREAD

**Issue by Melind4** [termux/termux-packages#8460]
### Package description

COIN-OR Utilities

### Source code URL

https://github.com/coin-or/CoinUtils

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

It is not possible to install coinor-clp without it.

coinor-clp: Depends: libcoinor-utils but it is not installable

**Comment by Grimler91** [comment]
Should be fixed once this build finishes: https://github.com/termux/termux-packages/actions/runs/1659303250

CI build script has an issue with building&uploading dependencies, sometimes
