### ISSUE TITLE
Help installing python libzim 1.0.0 in termux

### ISSUE THREAD

**Issue by sobaee** [termux/termux-packages#8478]
Hello dear developer

I failed to install python-libzim 1.0.0 in termux mobile

Termux use libzim library 7.0.0, python 3.9.0

Please help with any information could help

It gives me this error:

ERROR: Could not find a version that satisfies the requirement libzim==1.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.3.post0, 0.1, 1.0.0)
ERROR: No matching distribution found for libzim==1.0

(Termux maybe able to install python libzim 0.0.1 put this one is very old and no one is using it right now)

I also tried gcc cctools that let termux able to build libraries using gcc, but it's failed either

Please help

**Comment by sobaee** [comment]
Finally 
I managed this by using ubuntu amd64 in termux then install python-libzim 1.0.0 in python 3.9.
build python 3.9 for ubuntu 18.04 by this:

https://www.makeuseof.com/install-python-ubuntu/

This is the tutorial video how to install ubuntu x86 but use it to install amd64 not i686 (x86):
https://m.youtube.com/watch?v=Ucc1sNqIoc8

**Comment by Grimler91** [comment]
Probably the lack of installable versions has to do with that [libzim doesn't really support arm/aarch64](https://github.com/openzim/libzim/issues/396)

**Comment by sobaee** [comment]
> Probably the lack of installable versions has to do with that [libzim doesn't really support arm/aarch64](https://github.com/openzim/libzim/issues/396)

That was my issue there in the github page of the libzim developer.

The developer mentioned something about "Run on architecture", I really didn't get what he was meant by this!!
Is it about running of x86 commands or softwares (that are not compatible with arch platforms) in arch platforms or something like this?
However, I believe that python-libzim is only compatible with x86-x64 GNU linux (amd64) not for x86

Run on architecture page:
https://github.com/marketplace/actions/run-on-architecture

Iam not familiar with 'docker' things and with all these staff of run-on-architecture. 

It's very complicated steps for me as a beginner.

I hope that termux developer just think about making a ready to install python-libzim package (apt install python-libzim) as a solution for  beginner users.

**Comment by xtkoba** [comment]
That is not likely to happen. `python-libzim` should be managed by pip.

A possibility is that someone ("a second its-pointless") would make a pre-built binary package and distribute it personally.

**Comment by sobaee** [comment]
> That is not likely to happen. `python-libzim` should be managed by pip.
> 
> A possibility is that someone ("a second its-pointless") would make a pre-built binary package and distribute it personally.

the error:

pip install libzim==1.0                     Collecting libzim==1.0                            Using cached libzim-1.0.0.tar.gz (8.1 MB)       Installing build dependencies ... error         ERROR: Command errored out with exit status 1:   command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/tmp/pip-standalone-pip-i360ac3k/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-3r8l335l/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 35.0.2' 'wheel >= 0.29.0' twine 'cython >= 0.29.22,<3.0'                   cwd: None                                  Complete output (234 lines):                    Collecting setuptools>=35.0.2                     Using cached setuptools-60.5.0-py3-none-any.whl (958 kB)                                      Collecting wheel>=0.29.0                          Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)                                        Collecting twine                                  Using cached twine-3.7.1-py3-none-any.whl (35 kB)                                             Collecting cython<3.0,>=0.29.22                   Using cached Cython-0.29.26-py2.py3-none-any.whl (983 kB)                                     Collecting readme-renderer>=21.0                  Using cached readme_renderer-32.0-py3-none-any.whl (16 kB)                                    Collecting colorama>=0.4.3                        Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)                                      Collecting pkginfo>=1.8.1                         Using cached pkginfo-1.8.2-py2.py3-none-any.whl (26 kB)                                       Collecting tqdm>=4.14                             Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)                                         Collecting keyring>=15.1                          Using cached keyring-23.5.0-py3-none-any.whl (33 kB)                                          Collecting requests-toolbelt!=0.9.0,>=0.8.0       Using cached requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)                             Collecting requests>=2.20                         Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)                                     Collecting importlib-metadata>=3.6                Using cached importlib_metadata-4.10.0-py3-none-any.whl (17 kB)                               Collecting rfc3986>=1.4.0                         Using cached rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)                                       Collecting zipp>=0.5                              Using cached zipp-3.7.0-py3-none-any.whl (5.3 kB)                                             Collecting jeepney>=0.4.2                         Using cached jeepney-0.7.1-py3-none-any.whl (54 kB)                                           Collecting SecretStorage>=3.2                     Using cached SecretStorage-3.3.1-py3-none-any.whl (15 kB)                                     Collecting docutils>=0.13.1                       Using cached docutils-0.18.1-py2.py3-none-any.whl (570 kB)                                    Collecting bleach>=2.1.0                          Using cached bleach-4.1.0-py2.py3-none-any.whl (157 kB)                                       Collecting Pygments>=2.5.1                        Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)                                        Collecting certifi>=2017.4.17                     Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)                                  Collecting charset-normalizer~=2.0.0              Using cached charset_normalizer-2.0.10-py3-none-any.whl (39 kB)                               Collecting idna<4,>=2.5                           Using cached idna-3.3-py3-none-any.whl (61 kB)                                                Collecting urllib3<1.27,>=1.21.1                  Using cached urllib3-1.26.8-py2.py3-none-any.whl (138 kB)                                     Collecting packaging                              Using cached packaging-21.3-py3-none-any.whl (40 kB)                                          Collecting webencodings                           Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)                                  Collecting six>=1.9.0                             Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)                                          Collecting cryptography>=2.0                      Using cached cryptography-36.0.1.tar.gz (572 kB)                                                Installing build dependencies: started          Installing build dependencies: finished with status 'done'                                      Getting requirements to build wheel: started    Getting requirements to build wheel: finished with status 'done'                                Preparing metadata (pyproject.toml): started    Preparing metadata (pyproject.toml): finished with status 'done'                              Collecting cffi>=1.12                             Using cached cffi-1.15.0-cp310-cp310-linux_aarch64.whl                                        Collecting pyparsing!=3.0.5,>=2.0.2               Using cached pyparsing-3.0.6-py3-none-any.whl (97 kB)                                         Collecting pycparser                              Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)                                     Building wheels for collected packages: cryptography                                              Building wheel for cryptography (pyproject.toml): started                                       Building wheel for cryptography (pyproject.toml): finished with status 'error'                  ERROR: Command errored out with exit status 1:                                                   command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/tmp/tmpvp5indw4_in_process.py build_wheel /data/data/com.termux/files/usr/tmp/tmps47k4tia                      cwd: /data/data/com.termux/files/usr/tmp/pip-install-ld05810w/cryptography_f8a55322d2d24eca804d4b11f2c28c2c                                Complete output (157 lines):                    running bdist_wheel                             running build                                   running build_py                                creating build                                  creating build/lib.linux-aarch64-3.10           creating build/lib.linux-aarch64-3.10/cryptography                                              copying src/cryptography/__about__.py -> build/lib.linux-aarch64-3.10/cryptography              copying src/cryptography/__init__.py -> build/lib.linux-aarch64-3.10/cryptography               copying src/cryptography/exceptions.py -> build/lib.linux-aarch64-3.10/cryptography             copying src/cryptography/fernet.py -> build/lib.linux-aarch64-3.10/cryptography                 copying src/cryptography/utils.py -> build/lib.linux-aarch64-3.10/cryptography                  creating build/lib.linux-aarch64-3.10/cryptography/hazmat                                       copying src/cryptography/hazmat/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat                                                 copying src/cryptography/hazmat/_oid.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat     creating build/lib.linux-aarch64-3.10/cryptography/x509                                         copying src/cryptography/x509/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/x509     copying src/cryptography/x509/base.py -> build/lib.linux-aarch64-3.10/cryptography/x509         copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-aarch64-3.10/cryptography/x509                                     copying src/cryptography/x509/extensions.py -> build/lib.linux-aarch64-3.10/cryptography/x509                                                   copying src/cryptography/x509/general_name.py -> build/lib.linux-aarch64-3.10/cryptography/x509                                                 copying src/cryptography/x509/name.py -> build/lib.linux-aarch64-3.10/cryptography/x509         copying src/cryptography/x509/ocsp.py -> build/lib.linux-aarch64-3.10/cryptography/x509         copying src/cryptography/x509/oid.py -> build/lib.linux-aarch64-3.10/cryptography/x509          creating build/lib.linux-aarch64-3.10/cryptography/hazmat/backends                              copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends                               copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends                             creating build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings                              copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings                               creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                            copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                           copying src/cryptography/hazmat/primitives/_asymmetric.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                        copying src/cryptography/hazmat/primitives/_cipheralgorithm.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                   copying src/cryptography/hazmat/primitives/_serialization.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                     copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                               copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                      copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                             copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                               copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                            copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                            copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives                           creating build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                      copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl               copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                   copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                   copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl            copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                     copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                     copying src/cryptography/hazmat/backends/openssl/ed25519.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                copying src/cryptography/hazmat/backends/openssl/ed448.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                  copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl            copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                 copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                   copying src/cryptography/hazmat/backends/openssl/poly1305.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl               copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                  copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                 copying src/cryptography/hazmat/backends/openssl/x448.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                   copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl                   creating build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/openssl                      copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/openssl               copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/openssl           copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/openssl                creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric                 copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric     copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric           copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric          copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric           copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric      copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric        copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric      copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric          copying src/cryptography/hazmat/primitives/asymmetric/types.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric        copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric        copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric       copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric         creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers                    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers           copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers               copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers         copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers               copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers              creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf                        copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf                   copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf                  copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf                       copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf                      copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf                     copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf                     copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf                    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization              copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization                                               copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization                                                   copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization                                                 copying src/cryptography/hazmat/primitives/serialization/pkcs7.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization                                                  copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/twofactor                  copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/twofactor       copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/twofactor           copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/twofactor           running egg_info                                no previously-included directories found matching 'docs/_build'                                 warning: no previously-included files found matching 'vectors'                                  warning: no previously-included files matching '*' found under directory 'vectors'              warning: no previously-included files matching '*' found under directory '.github'              warning: no previously-included files found matching 'release.py'                               warning: no previously-included files found matching '.coveragerc'                              warning: no previously-included files found matching 'codecov.yml'                              warning: no previously-included files found matching '.readthedocs.yml'                         warning: no previously-included files found matching 'dev-requirements.txt'                     warning: no previously-included files found matching 'tox.ini'                                  warning: no previously-included files found matching 'mypy.ini'                                 warning: no previously-included files matching '*' found under directory '.zuul.d'              warning: no previously-included files matching '*' found under directory '.zuul.playbooks'      writing manifest file 'src/cryptography.egg-info/SOURCES.txt'                                   copying src/cryptography/py.typed -> build/lib.linux-aarch64-3.10/cryptography                  creating build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/_rust                        copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/_rust                  copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/_rust                      copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/_rust                      copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/_rust                      running build_ext                                                                                   =============================DEBUG ASSISTANCE=============================                      If you are seeing a compilation error please try the following steps to                         successfully install cryptography:              1) Upgrade to the latest pip and try again. This will fix errors for most                          users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip                          2) Read https://cryptography.io/en/latest/installation/ for specific                               instructions for your platform.              3) Check our frequently asked questions for more information:                                      https://cryptography.io/en/latest/faq/                                                       4) Ensure you have a recent Rust toolchain installed:                                              https://cryptography.io/en/latest/installation/#rust                                                                                         Python: 3.10.1                                  platform: Linux-4.19.113-22299651-aarch64-with-libc                                             pip: n/a                                        setuptools: 60.5.0                              setuptools_rust: 1.1.2                          =============================DEBUG ASSISTANCE=============================                                                                  error: can't find Rust compiler                                                                 If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.                                                                             To update pip, run:                                                                                 pip install --upgrade pip                                                                   and then retry package installation.                                                            If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.                                                                                        This package requires Rust >=1.41.0.            ----------------------------------------        ERROR: Failed building wheel for cryptography                                                 Failed to build cryptography                    ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects                                      ----------------------------------------      WARNING: Discarding https://files.pythonhosted.org/packages/88/92/e2d876c474fa59e900196ac7cffd703b882d5b4920d1b2291dcdceb8a359/libzim-1.0.0.tar.gz#sha256=e6fa778639dd1db93b442094d0a7375093f74445c263a625176c234ede210db6 (from https://pypi.org/simple/libzim/) (requires-python:>=3.6). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/tmp/pip-standalone-pip-i360ac3k/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-3r8l335l/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 35.0.2' 'wheel >= 0.29.0' twine 'cython >= 0.29.22,<3.0' Check the logs for full command output.                                             ERROR: Could not find a version that satisfies the requirement libzim==1.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.3.post0, 0.1, 1.0.0)        ERROR: No matching distribution found for libzim==1.0

**Comment by sobaee** [comment]
I tried with updated "pip", and tried with "rust"

And also it gives error.

If you need the log message of the error after installing the updated pip and rust I will post it.

**Comment by sobaee** [comment]
Also I'm not sure if python-libzim 1.0.0 is supporting python 3.10 that termux is using right now, because in releases page of python-libzim they only mentioned it support python 3.9!!

https://github.com/openzim/python-libzim/releases/tag/v1.0.0

**Comment by xtkoba** [comment]
Are you able to install `cryptography`? We have some issues (or questions) regarding this. For the solution please <a href="https://github.com/termux/termux-packages/issues?q=is%3Aissue+cryptography">search here (including closed ones)</a>.

**Comment by sobaee** [comment]
> Are you able to install `cryptography`? We have some issues (or questions) regarding this. For the solution please [search here (including closed ones)](https://github.com/termux/termux-packages/issues?q=is%3Aissue+cryptography).

Thanks

I'm gonna try to install cryptography successfully, and then run: pip install python-libzim==1.0 again and I let you know

**Comment by sobaee** [comment]
Successfully installed cryptography, 

$LD_LIBRARY_PATH and $PATH are in the right place

Now I get this error:

ERROR: Command errored out with exit status 1:   command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /data/data/com.termux/files/usr/tmp/tmp8wqc2upw         cwd: /data/data/com.termux/files/usr/tmp/pip-install-j8nc4r1u/libzim_9fa60a4ecb294db9afc9e407bacfc346                                      Complete output (2 lines):                      [!] The libzim library cannot be found.         Please verify that the library is correctly installed and can be found.                         ----------------------------------------      WARNING: Discarding https://files.pythonhosted.org/packages/88/92/e2d876c474fa59e900196ac7cffd703b882d5b4920d1b2291dcdceb8a359/libzim-1.0.0.tar.gz#sha256=e6fa778639dd1db93b442094d0a7375093f74445c263a625176c234ede210db6 (from https://pypi.org/simple/libzim/) (requires-python:>=3.6). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /data/data/com.termux/files/usr/tmp/tmp8wqc2upw Check the logs for full command output.                                   ERROR: Could not find a version that satisfies the requirement libzim==1.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.3.post0, 0.1, 1.0.0)        ERROR

**Comment by sobaee** [comment]
I don't know if it's compatible only with python 3.9,

 Or if it's a problem that it can't find libzim.so.7 or libzim7.so in termux lib folder (because in termux lib folder we have only libzim.so for libzim version 7.0.0)

What do you think?

**Comment by sobaee** [comment]
I have noticed in Google search that:

![Screenshot_20220109203528](https://user-images.githubusercontent.com/65910585/148693716-beb72fab-520f-40e3-9c95-d373bb0077ee.jpg)

So it may only work with python 3.9!!

**Comment by xtkoba** [comment]
It is possible that the logic for `find_library` defined in `lib/python3.10/ctypes/util.py` is just incompatible with Termux. I would either hack it or modify the `setup.py` in python-libzim to bypass the library checking.

I don't believe python-libzim is incompatible with Python 3.10.

**Comment by sobaee** [comment]
> It is possible that the logic for `find_library` defined in `lib/python3.10/ctypes/util.py` is just incompatible with Termux. I would either hack it or modify the `setup.py` in python-libzim to bypass the library checking.
> 
> I don't believe python-libzim is incompatible with Python 3.10.

Thanks
I appreciate that

**Comment by xtkoba** [comment]
Ah, have you installed `binutils`? Apparently `find_library` depends upon it.

**Comment by sobaee** [comment]
> Ah, have you installed `binutils`? Apparently `find_library` depends upon it.

Well done 🥳🥳🥳🥳🥳

You are my hero

I can't thank you enough

I love you bro

**Comment by sobaee** [comment]
Thanks to @xtkoba 

Here is what I did:

apt install rust binutils libzim

pip install wheel cython

export CARGO_BUILD_TARGET=aarch64-linux-android && pip install cryptography

export PATH='/data/data/com.termux/files/usr/bin'

export LD_LIBRARY_PATH='/data/data/com.termux/files/usr/lib'

pip install libzim==1.0
