### ISSUE TITLE
Patch for Go breaks os/user without cgo

### ISSUE THREAD

**Issue by fd0** [termux/termux-packages#848]
Hi,

a user just reported that [restic](https://restic.github.io) cannot be built with the termux Go package: https://github.com/restic/restic/issues/886

We're using a custom `build.go` program which, among others, disables cgo by setting the environment variable `CGO_ENABLED=0`. This is broken on termux, this simple program will work with cgo, but not without:

```go
package main
import "fmt"
import "os/user"
func main() {
    u, e := user.Current()
    fmt.Printf("%v %v\n", u, e)
}
```

```
$ go run foo.go
&{10094 10094 u0_a94  /data/data/com.termux/files/home} <nil>

$ CGO_ENABLED=0 go run foo.go
# os/user
../usr/lib/go/src/os/user/lookup.go:9: undefined: current
../usr/lib/go/src/os/user/lookup.go:15: undefined: lookupUser
../usr/lib/go/src/os/user/lookup.go:21: undefined: lookupUserId
../usr/lib/go/src/os/user/lookup.go:27: undefined: lookupGroup
../usr/lib/go/src/os/user/lookup.go:33: undefined: lookupGroupId
../usr/lib/go/src/os/user/lookup.go:38: undefined: listGroups
```

I highly suspect that this is caused by this patch: https://github.com/termux/termux-packages/blob/master/packages/golang/src-os-user.patch

**Comment by fornwall** [comment]
Thanks a lot for reporting! This should now be fixed in a `2:1.8-1` update of the golang package.

Let me know if the problem remains!

**Comment by fornwall** [comment]
What is happening here is that os/user is by default using unimplemented stubs on android in go: https://golang.org/src/os/user/lookup_android.go

Termux patches away this to enable os/user to work, but the previous patch only fixed the cgo variant. It should now also work without cgo.

**Comment by fd0** [comment]
Works, thanks!
