### ISSUE TITLE
[Package]: mdbook-toc

### ISSUE THREAD

**Issue by Melind4** [termux/termux-packages#8480]
### Package description

A preprocessor for mdbook to add inline Table of Contents support.

### Source code URL

https://github.com/badboy/mdbook-toc

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
mdbook-toc, and most other mdbook addons that you have requested, are available through rust's package manager `cargo`. Have you tried installing them through `cargo`?

Relevant packaging policy section:

> Not installable through cpan, gem, npm, or pip
>
> These packages should be installable through `cpan`, `gem`, `npm`, `pip` and so on.
>
> Packaging modules for Perl, Ruby, Node.js, Python is problematic, especially when it comes to cross-compiling native extensions.

I think an exception can be made for the main package, `mdbook`, but these addons (seem to be hundreds of them) would be more convenient to install through cargo if possible.

**Comment by Melind4** [comment]
These packages are present in the repositories of void linux and nixos distributions. They are relatively small. They are part of an effort to add more documentation resources. Installing with Cargo would consume a lot of time and space on a local device. These are not script packages.

**Comment by Grimler91** [comment]
> These packages are present in the repositories of void linux and nixos distributions

Not really relevant

> They are relatively small.

If they are relatively small then installing with cargo should not consume a lot of time or space

My main objection is that someone has to maintain these packages. If you are planning to use the packages regularly and volunteer to maintain them, then sure, we can add them. 
If not, then it seems better to let users install the latest guaranteed-to-be-up-to-date version of all the addons through cargo

**Comment by buribu** [comment]
Although plug-ins are small when compiled, they sometimes require downloading and building many dependencies. If you think about the scope of the application... for example, it's useful for people who write documents in markdown, not necessarily for the rust ecosystem. Then, the user would have to install the rust and use Cargo, even if he is a javascript programmer or a software engineer. I mentioned these distributions because they, like the termux community, use github in the same way. There are only 6 plugins, not hundreds...

**Comment by Melind4** [comment]
Although plug-ins are small when compiled, they sometimes require downloading and building many dependencies. If you think about the scope of the application... for example, it's useful for people who write documents in markdown, not necessarily for the rust ecosystem. Then, the user would have to install the rust and use Cargo, even if he is a javascript programmer or a software engineer. I mentioned these distributions because they, like the termux community, use github in the same way. There are only 6 plugins, not hundreds...
