### ISSUE TITLE
[Package]: action-mdbook

### ISSUE THREAD

**Issue by Melind4** [termux/termux-packages#8485]
### Package description

Github action to setup mdbook and optional the linkcheck, mermaid, toc or open-on-gh plugins

### Home page URL

https://github.com/marketplace/actions/mdbook-action-with-plugins

### Source code URL

https://github.com/jontze/action-mdbook

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xeffyr** [comment]
Sorry, but GitHub Actions can't be requested as package.
