### ISSUE TITLE
[Package]: nsis

### ISSUE THREAD

**Issue by Haiz14** [termux/termux-packages#8488]
### Package description

NSIS

Descrption: Nullsoft Scriptable Install System (NSIS) is a script-driven installer authoring tool for Microsoft Windows backed by Nullsoft, the creators of Winamp. NSIS is released under a combination of free software licenses, primarily the zlib license.[2] It has become a widely used alternative to commercial proprietary products like InstallShield, with users including Amazon.com, Dropbox, Google, Ubisoft, FL Studio, BitTorrent, and McAfee.

Why 

One should be able to make windows installer for a python application using pynsist ( which requires nsis ).

License: Zlib license

Installed size : 858 (the raw PKG information didn't describe in what units it's measured and orignal size )

### Home page URL

https://nsis.sourceforge.io/

### Source code URL

https://www.ubuntuupdates.org/package/core/impish/universe/base/nsis

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
I wonder if this is useful (or rather usable) without MinGW toolchain.
