### ISSUE TITLE
[Package]: mdbook-katex

### ISSUE THREAD

**Issue by Melind4** [termux/termux-packages#8489]
### Package description

A preprocessor for mdBook, rendering LaTex equations to HTML at build time.

### Source code URL

https://github.com/lzanini/mdbook-katex

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Cannot be packaged as no license is specified.

**Comment by Melind4** [comment]
Inside the Cargo.toml file on line 7 it indicates license="MIT".

**Comment by xtkoba** [comment]
MIT license needs copyright information.

**Comment by Melind4** [comment]
Now the license has been added.
