### ISSUE TITLE
NGROK

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#8495]
### Package description

ngrok provides a real-time web UI where you can introspect all HTTP traffic running over your tunnels

### Home page URL

https://ngrok.com/

### Source code URL

https://github.com/inconshreveable/ngrok

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by sk0kanik** [comment]
#4354

**Comment by xeffyr** [comment]
@dipayand Why you are toggling the check box for packaging policy if you seem didn't read it? Ngrok is **closed source** proprietary thing since the protocol version 2.x.

https://github.com/inconshreveable/ngrok is legacy repository and 1.x endpoints are shut down.

**Comment by dipayand** [comment]
I am sorry. I will keep this in mind. I found a work around though
