### ISSUE TITLE
[Package]: python-libzim 1.0.0

### ISSUE THREAD

**Issue by sobaee** [termux/termux-packages#8512]
### Package description

This package needed for using zim reader and writer for those who are interested in kiwix. It Stores any website on mobile phone or computer, for offline viewing using kiwix app.

### Home page URL

https://www.kiwix.org/en/

### Source code URL

https://github.com/openzim/python-libzim

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information
I know we already have libzim c++ library 7.0.0 package in termux if we run apt install libzim, but it's not enough to deal with zim files. So there is a real need of python-libzim as a separated package to be installed directly in termux by apt install python-libzim

This package prerequisite python 3.9 to work (I think it's non compatible with python 3.10!!) And for linux amd64 it will be installed without the need to have c++ libzim library pre-installed. But this is not the case if you have aarch64 platform like termux.

it was impossible for me to build python-libzim for aarch64 termux inspect of ten times trying.

In the past and for old c++ libzim (6.3) of termux, python 3.8 there was an ability to install python-libzim 0.0.1, but this one is very old and not needed anymore. We were able to install it by apt install libzim then pip install libzim. But now this will fail always.

Thanks

**Comment by xtkoba** [comment]
What steps did you take to try to install `python-libzim`? The description in #8478 is insufficient as it does not show what commands did you issue at all. And you should not truncate the log messages.

**Comment by sobaee** [comment]
Thanks to @xtkoba

I managed to install python-libzim 1.0.0 in termux.

Here is what I did:

apt install rust binutils libzim

pip install wheel cython

export CARGO_BUILD_TARGET=aarch64-linux-android && pip install cryptography

export PATH='/data/data/com.termux/files/usr/bin'

export LD_LIBRARY_PATH='/data/data/com.termux/files/usr/lib'

pip install libzim==1.0
