### ISSUE TITLE
gnupg: unable to search and receive keys

### ISSUE THREAD

**Issue by alive4ever** [termux/termux-packages#852]
``gpg`` is unable to retrieve public keys from hkp keyserver due to missing ``$TERMUX/usr/libexec/gpgkeys_curl``

```
~ $ gpg --search-keys 0x62F25B592B6F76DA
gpg: searching for "0x62F25B592B6F76DA" from hkp server keys.gnupg.net
gpg: unable to execute program `/data/data/com.termux/files/usr/libexec/gnupg/gpgkeys_curl': No such file or directory
gpg: no handler for keyserver scheme `hkp'
gpg: keyserver search failed: keyserver error
```

**Comment by alive4ever** [comment]
It seems that ``gnupg-curl`` is available to provide hkp keyserver access. Closing.

**Comment by Skilly** [comment]
Installing the missing package resolves the issue:
`pkg install gnupg-curl`

**Comment by superlex** [comment]
Thanks @alive4ever and @Skilly .
Is it possible to add gnupg-curl to dependencies of gnupg?

**Comment by Prowerdev** [comment]
Hi @Skilly , when I try to do
 pkg install gnupg-curl
I get an error saying 'pkg command not found'
can you please guide me, why I am getting this. I am using mac and terminal

**Comment by Neo-Oli** [comment]
@Prowerdev If you're using a Mac this guide will not apply to you. This issue is about Termux; a linux environment for Android. `pkg` is Termux specific.

**Comment by Prowerdev** [comment]
@Neo-Oli Thanks for the reply.

**Comment by AI-Pranto** [comment]
`gpg --recv-key 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65` gives following error

```
gpg: keyserver receive failed: General error
```
And `pkg install gnupg-curl` gives  `E: Unable to locate package gnupg-curl` error. Is there anything I am done wrong?

**Comment by xeffyr** [comment]
@AI-Pranto Need `--keyserver pool.sks-keyservers.net`.
```
gpg --keyserver pool.sks-keyservers.net --recv-key 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
gpg: /data/data/com.termux/files/home/.gnupg/trustdb.gpg: trustdb created
gpg: key 16530D5E920F5C65: public key "Repo Maintainer <repo@android.kernel.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by AI-Pranto** [comment]
Thanks @xeffyr. One more question, How can I install gfortran compiler?

**Comment by xeffyr** [comment]
>How can I install gfortran compiler?

It is a part of gcc package from https://github.com/its-pointless/its-pointless.github.io. See https://wiki.termux.com/wiki/Package_Management#By_its-pointless on how to enable community repository.

**Comment by AI-Pranto** [comment]
I did it. But It shows `gfortran: command not found`. It suggests me to install clang. Anything I am missing @xeffyr ?

**Comment by xeffyr** [comment]
If you have installed `gcc-9` then do `setupgcc-9`. That's unofficial repository and gcc here conflicts with clang.

Ask on https://github.com/its-pointless/its-pointless.github.io/issues if you need more details on how to work with packages from this repository.
