### ISSUE TITLE
[Bug]: build-package.sh (when re-compiling a specific package) and clean.sh does not work on termux

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#8523]
### Problem description

Hi all.  
I noticed one strange thing about the compiler.  When a package is compiled and when you repeat the compilation of the same package, the compiler does not start and `clean.sh` stops working with it (if you run the compiler for another package, it works).  
**For example curl:**  
![Screenshot_20220110-223849_Termux](https://user-images.githubusercontent.com/60917834/148829721-39e4b503-e8bf-466a-86ac-5637bedf17f3.jpg)

I've debugged scripts and noticed one common line that might be the cause:

- [build-packages.sh](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_setup_build_folders.sh#L5)
- [clean.sh](https://github.com/termux/termux-packages/blob/master/clean.sh#L38)

Because of this, you have to manually remove `~/.termux-build` in order for the compiler to work again.

### What steps will reproduce the bug?

`build-package.sh` - recompiling specific packages
`clean.sh` - after compiling certain packages

### What is the expected behavior?

successful work

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Server = https://s3.amazonaws.com/termux-main.pacman/aarch64
[x11]
Server = https://s3.amazonaws.com/termux-x11.pacman/aarch64
[root]
Server = https://s3.amazonaws.com/termux-root.pacman/aarch64
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.190-20995430-abT860XXU3CUB7 #2 SMP PREEMPT Thu Feb 25 18:11:04 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T860
```

**Comment by thunder-coding** [comment]
Well there is a small workaround for this bug `rm -rf ~/.termux-build/<package-name>/{src,build}`

**Comment by Maxython** [comment]
> Well there is a small workaround for this bug `rm -rf ~/.termux-build/<package-name>/{src,build}`. This fixes this weird behaviour until building again

Probably just add `||  true` on those lines.
