### ISSUE TITLE
[Package]: git-repo (repo)

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#8525]
### Package description

*Repo is a tool built on top of Git. Repo helps manage many Git repositories, does the uploads to revision control systems, and automates parts of the development workflow.*  

It would be helpful to have this package on termux.

### Home page URL

https://gerrit.googlesource.com/git-repo/

### Source code URL

https://github.com/GerritCodeReview/git-repo

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by sk0kanik** [comment]
Isn't it a portable python script?

**Comment by xeffyr** [comment]
Its a single-script package.

https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy
