### ISSUE TITLE
heroku cli

### ISSUE THREAD

**Issue by dekubi** [termux/termux-packages#853]
Having a heroku cli addition to the ruby,node and python will really boost mobile dev.
Counting on everyone in this amasing community. Thanks

**Comment by BKubi** [comment]
@fornwall Any updates concerning the build of heroku-cli

**Comment by fornwall** [comment]
I have never used heroku myself, so this would require someone else to look into! Marking this as `help wanted`.

**Comment by timolehto** [comment]
Was just quickly experimenting with this and ran into
```
bash: bin/run: /usr/bin/env: bad interpreter: No such file or directory
```

**Comment by BKubi** [comment]
@fornwall @timolehto I have figured it out and you can do same just follow this https://github.com/BKubi/hello-world/blob/master/README.md

**Comment by timolehto** [comment]
@BKubi I gave it a spin, but could not get it to work. The install fails with:
ˋˋˋ
/usr/local/lib/heroku/install: line 28:  9847 Illegal instruction     $INSTALLPATH version  
ˋˋˋ
I think this is likely due to the fact that my Pixel is arm v8 64 and there’s some binary dependency to arm v7 32bit in the prebuilt binary. I couldn’t figure out any working url to download arm v8 64 compatible binary.

I was also wondering do you have custom nodejs installed or how does it work, because it looks like heroku depends on node > 7, but termux node pacakge is < 7 and the node swap you do would make heroku run on node 6.xx.x

Also the symlinking to the heroku executable is not necessary as the install script copies it there anyway overwriting such links.

Also looks like termux wget is without ssl support so I had to switch to curl instead.

**Comment by bitcoinmeetups** [comment]
Yes, Heroku on Termux could also be useful.

**Comment by Rudloff** [comment]
heroku-cli seems to run fine from Git.
The only thing I add to patch is this:
```diff
diff --git a/vendor/github.com/kardianos/osext/osext_procfs.go b/vendor/github.com/kardianos/osext/osext_procfs.go
index d59847e..1318041 100644
--- a/vendor/github.com/kardianos/osext/osext_procfs.go
+++ b/vendor/github.com/kardianos/osext/osext_procfs.go
@@ -16,7 +16,7 @@ import (
 
 func executable() (string, error) {
        switch runtime.GOOS {
-       case "linux":
+       case "android":
                const deletedTag = " (deleted)"
                execpath, err := os.Readlink("/proc/self/exe")
                if err != nil {
```

**Comment by fornwall** [comment]
@Rudloff Great! I've added a PR at https://github.com/kardianos/osext/pull/26 to handle `"android"` just like linux in that switch.

**Comment by fornwall** [comment]
> Also looks like termux wget is without ssl support so I had to switch to curl instead.

@timolehto The `wget` available by default on Termux is a lightweight version from [busybox](https://busybox.net/) which does not support https - run `packages install wget` to install the normal, fully-featured GNU wget (though I prefer curl personally).

**Comment by Rudloff** [comment]
What is the policy for packaging Go libraries?
Heroku CLI includes all these dependencies in their repository:
```
github.com/heroku/cli/vendor/github.com/ansel1/merry
github.com/heroku/cli/vendor/github.com/dghubble/sling
github.com/heroku/cli/vendor/github.com/dickeyxxx/golock
github.com/heroku/cli/vendor/github.com/dickeyxxx/netrc
github.com/heroku/cli/vendor/github.com/dickeyxxx/speakeasy
github.com/heroku/cli/vendor/github.com/go-errors/errors
github.com/heroku/cli/vendor/github.com/google/go-querystring/query
github.com/heroku/cli/vendor/github.com/kardianos/osext
github.com/heroku/cli/vendor/github.com/kr/binarydist
github.com/heroku/cli/vendor/github.com/lunixbochs/vtclean
github.com/heroku/cli/vendor/github.com/mitchellh/ioprogress
github.com/heroku/cli/vendor/github.com/stvp/rollbar
github.com/heroku/cli/vendor/github.com/texttheater/golang-levenshtein/levenshtein
github.com/heroku/cli/vendor/github.com/ulikunitz/xz
github.com/heroku/cli/vendor/github.com/ulikunitz/xz/internal/hash
github.com/heroku/cli/vendor/github.com/ulikunitz/xz/lzma
github.com/heroku/cli/vendor/golang.org/x/crypto/ssh/terminal
```

I guess it would be cleaner to create a package for each of them but it might be a lot of work.

**Comment by fornwall** [comment]
@Rudloff Go programs are normally built into a single statically linked binary containing all dependencies, so no need to create a separate package for each dependency.

**Comment by Rudloff** [comment]
It seems Heroku switched to a full JS CLI tool, which is way easier to port. However, I think it requires Node 7 which is not available in Termux yet.

**Comment by TheDiamondYT1** [comment]
@vishalbiswas Maybe your next porting attempt?

**Comment by CowDink** [comment]
@dekubi I got 
cp: '/usr/local/lib/heroku/bin/heroku' and '/usr/local/bin/heroku' are the same file

**Comment by christianrondeau** [comment]
@Rudloff @TheDiamondYT1 seems like node 8 is there : https://github.com/termux/termux-packages/pull/1179

Npm is still broken on Termux though, so you'll need yarn if you want it installed. See https://github.com/npm/npm/issues/17480 for more details. 

    curl -o- -L https://yarnpkg.com/install.sh | bash
    termux-fix-shebang /data/data/com.termux/files/home/.yarn/bin/yarn
    yarn global add heroku-cli

**Comment by fornwall** [comment]
The `nodejs` package is now at the current LTS version 8.9.0. Also, there is a `yarn´ package, which can be installed with `pkg install yarn`.
