### ISSUE TITLE
[Package]: TypeScript

### ISSUE THREAD

**Issue by ExtinctDrift19** [termux/termux-packages#8531]
### Package description

add TypeScript for termux these are functional extensions Javascript developer Microsoft 

### Home page URL

https://www.typescriptlang.org/

### Source code URL

https://github.com/microsoft/TypeScript/#readme

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

information wikipedia TypeScript link https://en.m.wikipedia.org/wiki/TypeScript

**Comment by ExtinctDrift19** [comment]
link https://en.m.wikipedia.org/wiki/TypeScript

**Comment by buribu** [comment]
npm install typescript --save-dev

**Comment by ExtinctDrift19** [comment]
help command TypeScript

**Comment by ExtinctDrift19** [comment]
TypeScript version no dev version stable TypeScript

**Comment by buribu** [comment]
Anyway, you already understand that it is only necessary to install nodejs to have access to TypeScript.

**Comment by ExtinctDrift19** [comment]
Okay

**Comment by ExtinctDrift19** [comment]
Help command TypeScript for termux
