### ISSUE TITLE
[Mirror]: New mirror addition request for termux.sahilister.in 

### ISSUE THREAD

**Issue by sahilister** [termux/termux-packages#8535]
### Package description

Please add the new mirror by [me](https://sahilister.in) on https://termux.sahilister.in/apt/

Updates once per 6 hours.
Repository 	sources.list entry
Main 	deb https://termux.sahilister.in/apt/termux-main stable main
Root 	deb https://termux.sahilister.in/apt/termux-root root stable
X11 	deb https://termux.sahilister.in/apt/termux-x11 x11 main

As there were only package request and bug report templates, using this for mirror addition.

**Comment by xeffyr** [comment]
Thanks
