### ISSUE TITLE
Package request: apache

### ISSUE THREAD

**Issue by Serkan-devel** [termux/termux-packages#855]
Would like to run a webserver on localhost.

But compatibility of running a webserver on flask would be also nice

**Comment by vishalbiswas** [comment]
nginx is coming this week. Just need to test it some more.

**Comment by fornwall** [comment]
There is already https://github.com/termux/termux-packages/issues/255 for tracking nginx, let's keep this one for apache.

**Comment by jrwr** [comment]
Ill take a look into apache, wanted to get into porting apps, this would be a good start

**Comment by JetBalsa** [comment]
Here is a makefile patch to get the gen_test_char to behave 

```
--- httpd-2.4.25/server/Makefile.in     2013-10-02 07:20:14.000000000 -0500
+++ httpd-2.4.25/server/Makefile_new.in 2017-03-20 00:50:39.045401978 -0500
@@ -25,10 +25,10 @@

 gen_test_char_OBJECTS = gen_test_char.lo
 gen_test_char: $(gen_test_char_OBJECTS)
-       $(LINK) $(EXTRA_LDFLAGS) $(gen_test_char_OBJECTS) $(EXTRA_LIBS)
+       gcc -Wall -O2 -DCROSS_COMPILE $(top_srcdir)/server/gen_test_char.c -s -o $(top_srcdir)/server/gen_test_char

 test_char.h: gen_test_char
-       ./gen_test_char > test_char.h
+       $(top_srcdir)/server/gen_test_char > $(top_srcdir)/server/test_char.h

 util.lo: test_char.h



```

and my current build.sh

```
TERMUX_PKG_HOMEPAGE=http://httpd.apache.org/docs/2.4/install.html
TERMUX_PKG_DESCRIPTION="Apache2 Web Server"
TERMUX_PKG_VERSION=2.4.25
TERMUX_PKG_SRCURL=http://mirror.jax.hugeserver.com/apache/httpd/httpd-2.4.25.tar.gz
TERMUX_PKG_DEPENDS="apr, apr-util, pcre, libandroid-support, libandroid-shmem, libcrypt, libxml2"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS=" --with-installbuilddir=$TERMUX_PKG_TMPDIR ac_cv_file__dev_zero=yes ac_cv_func_setpgrp_void=yes apr_cv_process_shared_works=no apr_cv_tcp_nodelay_with_cork=yes ac_cv_sizeof_struct_iovec=8 ap_cv_void_ptr_lt_long=4"
```

Compile gets pretty far, but its stopping at a strange place with no warning now. 
[Here is my build log/output](http://pastebin.com/raw/rCWc2FMD)

**Comment by vishalbiswas** [comment]
@JetBalsa libcrypt

**Comment by JetBalsa** [comment]
Is that what is missing? as you can see its in the pkg depends

**Comment by vishalbiswas** [comment]
@JetBalsa I was referring to your gitter response. Anyways, you haven't done `2>&1` so the log doesn't include any errors.
I have actually created an apache2 package built on top of yours. But I'm stuck at some places:
1. `make install` doesn't overwrite all files and there is no uninstall recipe.
2. The dir layout system is quite confusing and there is no predefined one to match Termux.

**Comment by JetBalsa** [comment]
Cool, I propose a little prefix edit and move the whole thing into
/opt/apache2 that way its self contained. should be dead easy to make any
uninstall scripts/scripts we would need

**Comment by JetBalsa** [comment]
Also, what changes where needed to get it to compile

**Comment by vishalbiswas** [comment]
@JetBalsa https://github.com/vishalbiswas/termux-packages/blob/apache2/packages/apache2/build.sh

**Comment by JetBalsa** [comment]
Ya, I would selfcontain Apache somewhere, I propose $TERMUX_PREFIX/opt

**Comment by Serkan-devel** [comment]
Ok, I'm now not anymore interrested in apache any more.
I used `python -m http.server 8000` to run a quick webserver.

But including apache-bench (`apache-utils`)would be nice though.

**Comment by vaites** [comment]
I have a working build script. Apache builds OK but fails to load because of an error on apr-util I think: `undefined symbol: apr_crypto_block_cleanup`

**Comment by vishalbiswas** [comment]
@vaites I have one, too. Mine says `Cannot locate symbol "apr_palloc" referenced by "mod_authn_file.so"`
