### ISSUE TITLE
[Bug]: apt update failed

### ISSUE THREAD

**Issue by foremtehan** [termux/termux-packages#8558]
### Problem description

I wanted to install tor on fresh termux installation but didnt work

### What steps will reproduce the bug?

apk update
pkg install tor

![image](https://user-images.githubusercontent.com/53290883/149400655-832bc61f-4070-4493-8132-19d3edc39b67.png)
![image](https://user-images.githubusercontent.com/53290883/149400698-388ddf3f-973d-4919-b684-3e8040edec16.png)

### System information

termux-info:

```
Lenovo Tab 7305x Android 9
```

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#google-play-store-deprecated
