### ISSUE TITLE
[Host downtime] Scheduled server upgrade 2022.01.15 | packages.termux.org

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-packages#8562]
In order to continue handle package requests and automated update submissions, we need more disk space on the server.

We can migrate to the server with following stats:
* 16 vCPU
* 32 GiB RAM
* 64 GiB disk space

So server will be 2x bigger than current one. Currently we use 18 GiB of disk by both system and package repositories.

Upgrading server will require to shut down the current one which means that **packages.termux.org will not be usable during that time**. Use `termux-change-repo` to pick the mirror.

***

To maintainers: GitHub actions uploads will be disabled at this time.

**Comment by buttaface** [comment]
It looks like we only need the extra disk space: couldn't we just ask for more disk on the current server? I have no idea why we'd need 16 CPUs and 32 GBs of RAM: my experience with serving TBs of traffic in the past is that it only requires bandwidth and disk space. You could serve it off a phone SoC for how much compute/memory you need.

**Comment by xeffyr** [comment]
Server configuration is bound to "cores". The more cores we have, the more disk space is available. FossHost panel is not so fancy at server management as ones of major hosting providers.

**Comment by buttaface** [comment]
Do you ever run `top` on the current file server to see how much CPU and RAM it is actually using? Back when I used to set up file servers that put out TBs of traffic 15-20 years ago, I used to be able to serve TBs off a single core and 512 MBs of RAM by using light web servers like lighttpd or nginx, so 8 cores and 16 GBs of RAM still sounds like complete overkill to me.

I'd talk to the FOSSHost people and see if they'll create a custom small plan, just with extra disk space, as many hosts are happy to do. Of course, some hosts highly overprovision their servers, so while they claim 8 cores on a shared server, you won't really see that if all your neighbors on the same server get busy too. If that's the case here, doesn't matter, but if they're actually provisioning 8 cores for us, it's a complete waste.

**Comment by xeffyr** [comment]
Serving packages doesn't consume much CPU. But `aptly` during package parsing is.

**Comment by buttaface** [comment]
OK, I was just talking about file serving, have no experience with apt package updates.

**Comment by xeffyr** [comment]
Everything on packages.termux.org has been done & seems working.
