### ISSUE TITLE
libclang_rt.profile-aarch64-android.a

### ISSUE THREAD

**Issue by smetsjp** [termux/termux-packages#857]
Hi,

I am trying to rebuild python2.7 inside termux using SlapOS buildout. However, I get an error that states that the linker can not find  libclang_rt.profile-aarch64-android.

Do you have any idea why termux's clang does not provide libclang_rt.profile-aarch64-android.a ? Do you have any suggestion to include  libclang_rt.profile-aarch64-android ?

I have included an except of compilation logs.

SlapOS uses rpath (which is not supported by bionic) but this is unrelated to this issue (rpath will just be ignored).

Regards,

JPS.

`gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -L/data/data/com.termux/files/home/slapos/rebootstrap/parts/zlib/lib -L/data/data/com.termux/files/home/slapos/rebootstrap/parts/readline/lib -L/data/data/com.termux/files/home/slapos/rebootstrap/parts/libexpat/lib -L/data/data/com.termux/files/home/slapos/rebootstrap/parts/libffi/lib -L/data/data/com.termux/files/home/slapos/rebootstrap/parts/ncurses/lib -L/data/data/com.termux/files/home/slapos/rebootstrap/parts/bzip2/lib -L/data/data/com.termux/files/home/slapos/rebootstrap/parts/gdbm/lib -L/data/data/com.termux/files/home/slapos/rebootstrap/parts/openssl/lib -L/data/data/com.termux/files/home/slapos/rebootstrap/parts/sqlite3/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/zlib/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/readline/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/libexpat/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/libffi/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/ncurses/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/bzip2/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/gdbm/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/openssl/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/sqlite3/lib -L/data/data/com.termux/files/home/slapos/rebootstrap/parts/gettext/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/gettext/lib -Wl,-rpath=/data/data/com.termux/files/home/slapos/rebootstrap/parts/file/lib -fprofile-generate  Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/parsetok.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Objects/obmalloc.o Python/mysnprintf.o Python/pyctype.o Parser/tokenizer_pgen.o Parser/printgrammar.o Parser/pgenmain.o -ldl  -o Parser/pgen
/data/data/com.termux/files/usr/bin/ld: cannot find /data/data/com.termux/files/usr/bin/../lib/clang/3.9.1/lib/linux/libclang_rt.profile-aarch64-android.a: No such file or directory
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by fornwall** [comment]
Hm, what exactly is libclang_rt.profile-aarch64-android.a? Is it part of compiler-rt?

**Comment by smetsjp** [comment]
On a debian system, it would belong to libclang-common-3.5-dev for example

**Comment by smetsjp** [comment]
Since I have no time to handle this, I would be happy to get some (paid) help. It is blocking me in porting SlapOS to Android using Termux.

**Comment by its-pointless** [comment]
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/9919477a935af2c13ba87bc9418bc95df5ead6fa/clang-2468363/lib64/clang/3.8/lib/linux/libclang_rt.profile-aarch64-android.a

downloadable https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/9919477a935af2c13ba87bc9418bc95df5ead6fa/clang-2468363/lib64/clang/3.8/lib/linux.tar.gz

**Comment by fornwall** [comment]
@smetsjp The NDK packages a version of it - could you try out https://fornwall.net/tmp/libclang_rt.profile-aarch64-android.a and see if it works?

**Comment by smetsjp** [comment]
Thank you for the help and suggestion. I am trying. I am also adding compiler-rt to libllvm package

**Comment by smetsjp** [comment]
Using the file provided by @fornwall leads to another compilation error:
`/data/data/com.termux/files/home/slapos/rebootstrap/parts/python2.7__compile__/Python-2.7.13/Objects/obmalloc.c:202:` undefined reference to `__llvm_profile_instrument_target'

I will now try with my patched clang package

**Comment by vishalbiswas** [comment]
You probably could have avoided this by disabling tests.

**Comment by xeffyr** [comment]
Closing as this is part of package `libcompiler-rt`.
