### ISSUE TITLE
Some problems with Slash'em Extended

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#8571]
Ever since the release of slex on Termux, I've noticed a few problems: 

- The inability to enter wizard mode. I used the username "wizard" but the game still doesn't allow it.
- On the "Restore old game file?" screen. Pressing "Destroy old game" y, then j, then you get to p which you can't press but you can press cancel, which will destroy the game for some reason.
- On the "Do you want your posessions identified?" screen, pressing n works just as well as pressing y which just prints it anyway

Hope I'm not being nitpicky. There might be some other problems that haven't been found out later in the game

**Comment by xtkoba** [comment]
PRs are welcome.
