### ISSUE TITLE
[Bug]: Something wrong with apt's signature verification

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#8574]
### Problem description

Here's the problem

```
Hit:1 https://grimler.se/termux-packages-24 stable InRelease
Hit:2 https://grimler.se/game-packages-24 games InRelease
Hit:3 https://grimler.se/termux-root-packages-24 root InRelease
Hit:4 https://grimler.se/science-packages-24 science InRelease
Hit:5 https://grimler.se/unstable-packages unstable InRelease
Hit:6 https://grimler.se/x11-packages x11 InRelease
Err:5 https://grimler.se/unstable-packages unstable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://grimler.se/unstable-packages unstable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
W: Failed to fetch https://grimler.se/unstable-packages/dists/unstable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

### What steps will reproduce the bug?

I used apt update and saw it but I think any apt commands that sends a request will do

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24 stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://grimler.se/unstable-packages unstable main
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.152-perf+ #1 SMP PREEMPT Thu Nov 11 13:42:11 CST 2021 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH2127
```

**Comment by backlight-rn** [comment]
Download and install latest version of termux-keyring:

```bash
curl -LO https://grimler.se/termux-packages-24/pool/main/t/termux-keyring/termux-keyring_2.4_all.deb

dpkg -i termux-keyring_2.4_all.deb

apt update

apt dist-upgrade -yq
```

**Comment by Grimler91** [comment]
Thanks for reporting

> Download and install latest version of termux-keyring:

Issue in this case is the opposite, the unstable-packages repo was signed with the old key instead of the new one. Has been fixed now.

Note that unstable-repo, science-repo and game-repo are empty, their packages have been moved to the main repo, so no need to be subscribed to those repos.

**Comment by agnostic-apollo** [comment]
> Note that unstable-repo, science-repo and game-repo are empty, their packages have been moved to the main repo, so no need to be subscribed to those repos.

Shouldn't we be able to solve this issue by deleting the repo sources via `apt` or `termux-app` update?

**Comment by Grimler91** [comment]
> Shouldn't we be able to solve this issue by deleting the repo sources via apt or termux-app update?

Having {science,game,unstable}-repo is not really an issue, they won't do anything, only downside is that `apt update` takes a bit longer. 

For fresh installations they won't be present, they aren't pulled into the bootstrap anymore. 
@xeffyr went for [REPLACES + PROVIDES for unstable-repo](https://github.com/termux/termux-packages/blob/master/packages/apt/build.sh#L13-L14), @xeffyr was there an issue when BREAKS was specified? 

With REPLACES + CONFLICTS they should be automatically uninstalled
