### ISSUE TITLE
[Bug]: When adding LD LIBERTY PATH in bashrc getting error

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-packages#8575]
### Problem description

When adding LD LIBERTY PATH in bashrc getting error

### What steps will reproduce the bug?

I added in ~/.bashrc
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/system/vendor/lib64:/system/vendor/lib64/egl

Getting error like this

![Screenshot_2022-01-15-11-30-12-299_com termux](https://user-images.githubusercontent.com/72664192/149611533-6a43860f-197c-4849-8649-5ac1ebd1f3bb.jpg)

### System information

Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.113-perf-g62242b28117e #1 SMP PREEMPT Thu Sep 23 22:26:01 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2007J3SP

**Comment by xeffyr** [comment]
You shouldn't add `LD_LIBRARY_PATH` in global way. It overrides built-in library search path defined by Android OS and one that is compiled into Termux binaries and cause stuff to break.

Specify it in this way instead:
```
LD_LIBRARY_PATH=/your/path ./binary
```
Or use wrappers.

**Comment by Saikatsaha1996** [comment]
> You shouldn't add `LD_LIBRARY_PATH` in global way. It overrides built-in library search path defined by Android OS and one that is compiled into Termux binaries and cause stuff to break.
> 
> Specify it in this way instead:
> 
> ```
> LD_LIBRARY_PATH=/your/path ./binary
> ```
> 
> Or use wrappers.

Oky

**Comment by Saikatsaha1996** [comment]
> You shouldn't add `LD_LIBRARY_PATH` in global way. It overrides built-in library search path defined by Android OS and one that is compiled into Termux binaries and cause stuff to break.
> 
> Specify it in this way instead:
> 
> ```
> LD_LIBRARY_PATH=/your/path ./binary
> ```
> 
> Or use wrappers.

But with another device not facing problem why ?

**Comment by Grimler91** [comment]
> But with another device not facing problem why ?

We don't know anything about your devices or environment so impossible to say. 
Maybe the other one is older or has an older termux installation and therefore relies on LD_LIBRARY_PATH already

**Comment by Saikatsaha1996** [comment]
> > But with another device not facing problem why ?
> 
> We don't know anything about your devices or environment so impossible to say. Maybe the other one is older or has an older termux installation and therefore relies on LD_LIBRARY_PATH already

Actually i am really confused because 2 another device
One android 10 & one android 11
Android 10 working properly with export LD LIBERTY PATH
But android 11 device cannot
Getting error.. and also yesterday i am not facing any problem with LD LIBERTY PATH in bashrc.. but facing problem from now.. i uninstalled and reinstalled same problem..

**Comment by Saikatsaha1996** [comment]
> > > But with another device not facing problem why ?
> > 
> > 
> > We don't know anything about your devices or environment so impossible to say. Maybe the other one is older or has an older termux installation and therefore relies on LD_LIBRARY_PATH already
> 
> Actually i am really confused because 2 another device One android 10 & one android 11 Android 10 working properly with export LD LIBERTY PATH But android 11 device cannot Getting error.. and also yesterday i am not facing any problem with LD LIBERTY PATH in bashrc.. but facing problem from now.. i uninstalled and reinstalled same problem..

And in 2 device already installed 0.118

**Comment by Saikatsaha1996** [comment]
> > But with another device not facing problem why ?
> 
> We don't know anything about your devices or environment so impossible to say. Maybe the other one is older or has an older termux installation and therefore relies on LD_LIBRARY_PATH already
Easy worked yesterday
All problem from today..
![IMG_20220115_132409](https://user-images.githubusercontent.com/72664192/149614326-dc13d3ab-7325-4d97-90ca-09ff30805c4c.jpg)

**Comment by Saikatsaha1996** [comment]
> > But with another device not facing problem why ?
> 
> We don't know anything about your devices or environment so impossible to say. Maybe the other one is older or has an older termux installation and therefore relies on LD_LIBRARY_PATH already

Problem solved 100% sure this problem with another PKG.. just now i installed build-essential and clang and added bashrc also working fine..

**Comment by agnostic-apollo** [comment]
>LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/system/vendor/lib64:/system/vendor/lib64/egl

Since the `termux-app` does not set `LD_LIBRARY_PATH` since a long time ago, the `$LD_LIBRARY_PATH` would expand to an empty string and the variable will be incorrectly set without termux library path prefix. Run `echo "$LD_LIBRARY_PATH"` and see what the value is. And as advised, best not set the variable globally and try to use a wrapper like [`tudo` path command](https://github.com/agnostic-apollo/tudo#path), which will automatically set variable according to location of binary.

**Comment by Saikatsaha1996** [comment]
> 

So i need to set R8?
>>> todo /system/vendor/lib64:/system/vendor/lib64/egl

**Comment by agnostic-apollo** [comment]
> So i need to set R8?
> 
> > > > todo /system/vendor/lib64:/system/vendor/lib64/egl

Read my comment and links provided and try to understand and follow it and then come back with a better question if needed.

Termux does not officially support setting custom LD_LIBRARY_PATH, so any modifications you do, you are on your own and termux won't provide support for any issues.

**Comment by Saikatsaha1996** [comment]
> > So i need to set R8?
> > > > > todo /system/vendor/lib64:/system/vendor/lib64/egl
> 
> Read my comment and links provided and try to understand and follow it and then come back with a better question if needed.
> 
> Termux does not officially support setting custom LD_LIBRARY_PATH, so any modifications you do, you are on your own and termux won't provide support for any issues.

Oky thank you
