### ISSUE TITLE
lighttpd

### ISSUE THREAD

**Issue by apolbox-project** [termux/termux-packages#858]
How start lighttpd, sorry newbie hehehe

**Comment by apolbox-project** [comment]
i'll try bro :)

**Comment by apolbox-project** [comment]
what if the error can be no such file or directory?

**Comment by vishalbiswas** [comment]
I assume that you save the file as lighttpd.conf
If you save it with another name, use `lighttpd -f <your config filename>`
Replace `your config filename` with the name of the actual file you saved your config in.

**Comment by apolbox-project** [comment]
I mean how do I install lighttpd and how to configure once installed?

**Comment by vishalbiswas** [comment]
`apt install lighttpd`

**Comment by apolbox-project** [comment]
continue ?

**Comment by vishalbiswas** [comment]
and then just follow my initial replies

**Comment by apolbox-project** [comment]
thanks i will try

**Comment by apolbox-project** [comment]
Error this bro :

$ lighttpd -f lighttpd.conf
2017-03-21 00:21:30: (/home/fornwall/.termux-build/lighttpd/src/src/configfile.c.1186) opening configfile  lighttpd.conf failed: No such file or directory

**Comment by vishalbiswas** [comment]
You need to create and save a lighttpd.conf file with the content from my 1st reply.

**Comment by apolbox-project** [comment]
where to save a file lighttpd.conf bro ?

**Comment by fornwall** [comment]
@apolbox-project I'm closing this as it's not really a Termux issue. I think the best forum to discuss and get help with lighttpd is the dedicated forum for it at https://redmine.lighttpd.net/projects/lighttpd/boards/2.

There is also a Termux Google+ community at https://termux.com/community where you can get help!
