### ISSUE TITLE
[Package]: xh (currently still blocked)

### ISSUE THREAD

**Issue by alexanderadam** [termux/termux-packages#8588]
### Package description

`xh` is a friendly and fast tool for sending HTTP requests. It reimplements as much as possible of [HTTPie's](https://httpie.io/) excellent design, with a focus on improved performance.

### Source code URL

https://github.com/ducaale/xh#xh

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by alexanderadam** [comment]
It would be wonderful to have it in Termux but it seems that [it is currently still relying on `/etc/resolv.conf`](https://github.com/ducaale/xh/issues/212#issuecomment-997446288) and therefore not yet possible to make it work.

**Comment by xeffyr** [comment]
Number of Termux packages are patched to use `/data/data/com.termux/files/user/etc/resolv.conf` instead. I think this one we can patch as well.

**Comment by ducaale** [comment]
@xtkoba Thanks for making xh available in `termux-packages`. May I ask how was xh was patched to read from `/data/data/com.termux/files/user/etc/resolv.conf`?
