### ISSUE TITLE
[Package]: outfieldr

### ISSUE THREAD

**Issue by alexanderadam** [termux/termux-packages#8591]
### Package description

A [TLDR](https://github.com/tldr-pages/tldr) client in Zig.

### Source code URL

https://gitlab.com/ve-nt/outfieldr#a-tldr-client-in-zig

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Depends on zig (#4760).

**Comment by xtkoba** [comment]
Or maybe we only need `termux_setup_zig` for packaging purposes.
