### ISSUE TITLE
[Bug]: termux-open apk Package installer crash

### ISSUE THREAD

**Issue by joshcangit** [termux/termux-packages#8640]
### Problem description

Using `termux-open` for .apk files will cause Package installer, _com.google.android.packageinstaller_, to crash.

Using the Package installer from the file manager works.

### What steps will reproduce the bug?

1. Download apk file, e.g. Chromium
> If inside an archive, need to unzip that file to get apk
2. Run `termux-open --content-type 'application/vnd.android.package-archive' *.apk`

![Screenshot_20220117-004539_Termux](https://user-images.githubusercontent.com/33022160/149669829-4a31b7fa-bff0-4bd0-a367-3649fe2da129.png)

### What is the expected behavior?

![Screenshot_20220117-003349_Package installer](https://user-images.githubusercontent.com/33022160/149669871-465c627e-782d-4069-8ba8-9209ab06df9f.png)

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages-cf.termux.org/apt/termux-science science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# game-repo (sources.list.d/game.list)
deb https://packages-cf.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.113-22340597 #1 SMP PREEMPT Wed Oct 20 14:36:17 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G973F
```

**Comment by agnostic-apollo** [comment]
Check changelog for `termux-app` `v0.118.0`. That may be the issue.

https://github.com/termux/termux-app/releases/tag/v0.118.0

> **!** Only allow `ContentProvider` access if `allow-external-apps` is set to true. **The `termux-open` commands will now silently fail if value is not set to `true`.** An error notification will be added in future versions. The caller app like `QuickEdit` may still show a flash error. Check https://github.com/termux/termux-tasker#allow-external-apps-property-optional on info on how to change the value. ([`dcedf394`](https://github.com/termux/termux-app/commit/dcedf394))

`com.google.android.packageinstaller` is broken if its crashing due to permission denial and issue should be reported to google.

Run `adb logcat -d > logcat.txt` after crash and find exact exception.

**Comment by joshcangit** [comment]
Thanks, setting `allow-external-apps` to `true` worked.
Not sure if this isn't needed without Termux:Tasker but I'm fine with this.

**Comment by agnostic-apollo** [comment]
Welcome. It's needed for a few things besides `termux-tasker`, docs need to be written.

Did u manage to get the exception thrown? Although, can get it myself if needed.
