### ISSUE TITLE
[Bug]: mpd not running after termux update packages

### ISSUE THREAD

**Issue by schwyzz** [termux/termux-packages#8641]
### Problem description

mpd not running after termux update packages:

### What steps will reproduce the bug?

[code]
~ $ pkg update
~ $ mpd
CANNOT LINK EXECUTABLE "mpd": cannot locate symbol "avio_read_partial" referenced by "/data/data/com.termux/files/usr/bin/mpd"...
[/code]

### System information

termux-info:
0.118.0.118 f-droid

**Comment by Grimler91** [comment]
What is your output of `termux-info`?

**Comment by schwyzz** [comment]
termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf+ #1 SMP PREEMPT Thu Nov 25 02:10:42 CST 2021 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(8)

**Comment by schwyzz** [comment]
if it's important i've done it before
[code]
pkg install proot-distro
pkg install git
git clone https://github.com/termux/proot-distro
cd proot-distro
./install.sh
proot-distro install debian
proot-distro login debian
apt install xorg openbox
[/code]

and after that did the following
[code]
proot-distro remove debian
[/code]

**Comment by schwyzz** [comment]
Thank you all
