### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#8646]
### Problem description

This upgrade:-
apt/stable 2.3.14 aarch64 [upgradable from: 2.3.13-4]
ffmpeg/stable 5.0 aarch64 [upgradable from: 4.4.1-1]
libexpat/stable 2.4.3 aarch64 [upgradable from: 2.4.2]
python/stable 3.10.2 aarch64 [upgradable from: 3.10.1]

Breaks vlc (it's-pointless repo build)
Most likely the ffmpeg upgrade.

### What steps will reproduce the bug?

Perform the upgrade and then open a stream in vlc. VLC no longer plays streams but will play files.

### What is the expected behavior?

No issues, streams should play as prior to the upgrade.

### System information

Termux (Terminal emulator with packages) - https://f-droid.org/packages/com.termux

**Comment by xtkoba** [comment]
We cannot fix issues for its-pointless repo.

You may want to make a package request for `vlc` here.
