### ISSUE TITLE
[Feature]:  any plan termux release a LTS version

### ISSUE THREAD

**Issue by haolongzhangm** [termux/termux-packages#8649]
### Feature description

as some LINUX released version, always have LTS version, 
for example, ubuntu 20.04, when do apt upgrade, will do not do tools MINOR upgrade,
for example , do not do python3.8 ----> python3.9

but at termux env  always do this upgrade!!!!, which is not friendly for user

### Additional information

nothing

**Comment by wmcbtech30** [comment]
They prefer rolling release model is to save disk space on their servers and less maintenance on packages with specific versions. and some people prefers latest versions of packages than outdated ones, thus Termux is not a linux distribution

You can ignore updates though with `apt-mark hold` and/or create your own community repository

**Comment by Grimler91** [comment]
That would mean more work when fixing bugs or security issues, and would increase disk space usage on server by up to a factor of 2. 

There are no such plans at the moment.

**Comment by xeffyr** [comment]
Termux is a rolling release distribution. Think of it as Arch Linux, but with `apt` package manager or Debian Sid. Rolling release model significantly reduces load put on maintainers giving chance to provide a reasonable packaging & service quality by small teams.

Don't compare Termux to major distributions like Ubuntu. They are driven by hundreds or thousands maintainers and have no more than 2-5 packages per maintainer. Termux has 50+ which makes it unlikely to be suitable for providing long term support releases.

Another issue is server disk space. Termux for now has to use free hosting providers which do not provide flexible resource plans. Having double disk space usage by just a repository copy is unwanted. For same reason we discard old package versions.

***

Consider creating community repositories rather relying on us. One can create something like "termux-python", an apt repository that will provide various Python versions compatible with currently available dependencies in official main repo.
