### ISSUE TITLE
[Package]:  apk-parser 

### ISSUE THREAD

**Issue by ExtinctDrift19** [termux/termux-packages#8650]
### Package description

APK parser lib, for decoding binary XML files, getting APK meta info. Full information https://github.com/hsiafan/apk-parser

### Source code URL

https://github.com/hsiafan/apk-parser

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by buribu** [comment]
This is in maven. https://mvnrepository.com/artifact/net.dongliu/apk-parser/2.6.10
