### ISSUE TITLE
[Package]: btfs2

### ISSUE THREAD

**Issue by simbadMarino** [termux/termux-packages#8663]
### Package description

Decentralized file system integrating with TRON network and Bittorrent network

### Home page URL

https://www.bittorrent.com/btfs/

### Source code URL

https://github.com/bittorrent/go-btfs

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Hello, trying to compile BTFS 2.0 on termux is not straight forward due to some karalabe/usb configuration steps , I needed to specify the CC (which i read in the wiki is not allowed,but didn't have other choice) and rename the binary file before installing on termux PREFIX/bin.

I already have the build.sh file but don't have access  to make the push  myself yet (Interested on actively maintain this package to support the termux project).

[build.txt](https://github.com/termux/termux-packages/files/7884999/build.txt)

**Comment by xtkoba** [comment]
As for `karalabe/usb` it would be sufficient to backport https://github.com/karalabe/usb/pull/28. Note that it is a little bit tricky to patch as the target source code is retrieved during the build steps.

**Comment by simbadMarino** [comment]
Thanks @xtkoba for the heads up and for adjusting  the build script!🙃
