### ISSUE TITLE
[Bug]: deb.kcubeterm.me is going 523 error.

### ISSUE THREAD

**Issue by Bidyut1154** [termux/termux-packages#8671]
### Problem description

the GitHub release (deb.kcubeterm.me) is going a 523 server error, while trying to run `apt update`
Screenshot:
![Screenshot_2022-01-18-15-30-55-108_com termux](https://user-images.githubusercontent.com/97286540/149915110-983f5ef3-2826-4700-a414-986f1e8a7315.png)

### What steps will reproduce the bug?

Running apt update

### What is the expected behavior?

The GitHub release should work

### System information

termux-info:

```
Application version:
0.116
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://deb.kcubeterm.me/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://deb.kcubeterm.me/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.18.31-perf-gf2fd6b0 #1 SMP PREEMPT Wed Jun 5 18:40:35 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 4A
```

**Comment by thunder-coding** [comment]
Ping @kcubeterm
