### ISSUE TITLE
[Bug]: mdns-scan doesn't seem to install anything

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#8674]
### Problem description

I haven't used mdns-scan before, so I could be completely wrong. It seems installing Termux's mdns-scan doesn't install any executable. However, it's [manpage](https://manpages.ubuntu.com/manpages/bionic/man1/mdns-scan.1.html) seems to imply there is, specifically:
`mdns-scan  does  not terminate on its own behalf. It scans for services continuously until the user kills it by pressing C-c.`

This log shows no new executable in $PREFIX/bin/ :

~ $ ls -1 $PREFIX/bin/ | wc -l
1258

~ $ pkg in mdns-scan
Checking availability of current mirror: ok                                             Reading package lists... Done
Building dependency tree... Done                                                        Reading state information... Done
The following NEW packages will be installed:                                             mdns-scan
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/16.2 kB of archives.                                                    After this operation, 81.9 kB of additional disk space will be used.
Selecting previously unselected package mdns-scan.                                      (Reading database ... 44201 files and directories currently installed.)
Preparing to unpack .../mdns-scan_0.5-1_arm.deb ...                                     Unpacking mdns-scan (0.5-1) ...                                                         Setting up mdns-scan (0.5-1) ...                                                        

~ $ ls -1 $PREFIX/bin/ | wc -l                                                           
1258

### What steps will reproduce the bug?

pkg in mdns-scan

### What is the expected behavior?

An mdns-scan executable in $PATH

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g606096e-dirty #1 SMP PREEMPT Tue Jan 17 18:10:20 KST 2017 armv7l Android
Device manufacturer:
LGE
Device model:
LGL84VL

```

**Comment by Grimler91** [comment]
It is installed to `$PREFIX/mdns-scan` instead of `$PREFIX/bin/mdns-scan` apparently

**Comment by Grimler91** [comment]
Should be fixed by https://github.com/termux/termux-packages/commit/b0d17bb59edbbb3902f9632090885062ede92d10. I see that error came from one of [my commits](https://github.com/termux/termux-packages/commit/869edf8bf10bf10d4bd406ed6e80f3a296c70176) :flushed:

**Comment by sudomain** [comment]
That was quick. Thank you!
