### ISSUE TITLE
[package request] fdm - a program designed to fetch mail from POP3 or IMAP servers, or stdin

### ISSUE THREAD

**Issue by timoc** [termux/termux-packages#868]
fdm is a program designed to fetch mail from POP3 or IMAP servers, or receive
local mail from stdin, and deliver it in various ways.

from:
https://github.com/nicm/fdm

sup would be nice too:
http://supmua.org/

**Comment by vaites** [comment]
You can fetch mail with getmail package. 

Sup is programmed in Ruby so you can install now with `gem install sup`

**Comment by timoc** [comment]
Does getmail work with google?

**Comment by vaites** [comment]
Sure, any POP3 or IMAP enabled server, with or without SSL...
