### ISSUE TITLE
[Bug]: ncmpcpp does not do the lyric fetch.

### ISSUE THREAD

**Issue by bilrou** [termux/termux-packages#8691]
### Problem description

If the id3tag of a file is correct when pressing the letter `L` it normally does the lyric fetch.
This feature has not worked. I imagine the lyric server APIs are outdated.. Could anyone update or patch the current files related to lyric fetch?

### What steps will reproduce the bug?

mpd
ncmpcpp
Any music file. that contains valid id3tags.
Press screen `l` with the selected file.

### What is the expected behavior?

download the lyric corresponding to the music file to the ~/.lyric directory and display the lyrics in the program's interface.

### System information

termux-info:

```
armv7l
```

**Comment by xtkoba** [comment]
This seems to have been fixed <a href="https://rybczak.net/ncmpcpp/">upstream</a>. So it is probably sufficient to update our `ncmpcpp` package to the latest release (version 0.9.2 as of now).
