### ISSUE TITLE
Apt update error

### ISSUE THREAD

**Issue by MrNobody0007** [termux/termux-packages#8700]
### Problem description

Why I'm getting error while doing apt update.
Like this. 
![Screenshot_20220120_195838](https://user-images.githubusercontent.com/98104714/150361534-72d641a7-e30b-40de-98ad-c389b378937a.jpg)
Pls help me with this.

### What steps will reproduce the bug?

I don't know! 

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/6726
