### ISSUE TITLE
[Bug]: dgsh package

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#8702]
### Problem description

1). Actual shell **dgsh** binary not installed anywhere on device.
dgsh is a shell like bash. so just like therr is ksh bash sh tcsh binaries to invoke those repective shells.

2)Some additional binaries are copied to $PREFIX/libexec/dgsh folder

So In TERMUX_POST_INSTALL commands to copy or symlink them to $PREFIX/bin

### What steps will reproduce the bug?
```
dgsh
dgsh -c '{{ echo hello & echo world & }} | paste'
```
command not found

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
libgnutls/stable 3.6.16-2 aarch64 [upgradable from: 3.6.16-1]
Android version:
10
Kernel build information:
Linux localhost 4.4.177-22371317 #1 SMP PREEMPT Tue Sep 28 16:35:24 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A750F

```

**Comment by tathastu871** [comment]
in build.sh in PRE_CONFIGURE STEP
Replace 
```
touch ../.config
	mkdir -p m4
	autoreconf -fi
```
with 
cd $TERMUX_PKG_SRCDIR && make config

**Comment by dspinellis** [comment]
What is the output of the building and installation process?

**Comment by Grimler91** [comment]
@dspinellis hi, issue seem to mainly be that we need additional configure args (and possibly some patches) since we are cross-compiling, so need to change our build recipe to do the same things as `make config` but with our extra args.

In our current build script here only core-tools is built, so dgsh for example is missing.

(log from current core-tools build can be seen [here](https://github.com/termux/termux-packages/runs/4817175369?check_suite_focus=true))

**Comment by dspinellis** [comment]
To clarify: *dgsh* is based on a modified version of some tools (bash, coreutils, diffutils, grep), which are then installed in distinct paths.  I assume any additional flags and configuration args used for the original *temux* build of these packages would need to be applied here as well.

**Comment by tathastu871** [comment]
add 
TERMUX_PKG_DEPENDS="libtool, texinfo, help2man, bison check, xz-utils, gettext, rsync"

**Comment by Grimler91** [comment]
@tathastu871 yes, those, or most of those, are needed to build the package, TERMUX_PKG_DEPENDS contains runtime dependencies though, build tools shouldn't be in that list. 

The tools are installed on the build host through the [setup-ubuntu.sh script](https://github.com/termux/termux-packages/blob/master/scripts/setup-ubuntu.sh)

**Comment by tathastu871** [comment]
> @tathastu871 yes, those, or most of those, are needed to build the package, TERMUX_PKG_DEPENDS contains runtime dependencies though, build tools shouldn't be in that list.
> 
> The tools are installed on the build host through the [setup-ubuntu.sh script](https://github.com/termux/termux-packages/blob/master/scripts/setup-ubuntu.sh)

Yes but make config checks for rsync nd fails if not found

**Comment by tathastu871** [comment]
any progress in it dgsh package. issue been stale and closed???

**Comment by Grimler91** [comment]
Doesn't seem like anyone has looked at it, no. I spent some time on it, but patching the all bundled dependencies and configure steps was not trivial. Package is in disabled-packages for now
