### ISSUE TITLE
[Package]: systrace

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#8706]
### Package description

[Capture a system trace on a device](https://developer.android.com/topic/performance/tracing/on-device)

> Command line

> Run the following commands in a terminal window to generate an HTML report from the trace file:

> `cd /path-to-traces-on-my-dev-machine && \
  systrace --from-file trace-file-name{.ctrace | .perfetto-trace}`

I would like to run the command `systrace  --from-file tracefile.perfetto-trace` in native Termux on device.

### Home page URL

https://github.com/catapult-project/catapult/tree/master/systrace

### Source code URL

https://chromium.googlesource.com/catapult/+/refs/heads/main/systrace/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

official site: https://chromium.googlesource.com/catapult/+/refs/heads/main/systrace/

**Comment by Grimler91** [comment]
I guess this would require root

**Comment by SDRausty** [comment]
> I guess this would require root

Possibly not as the Android system does the tracing.  Simple file conversion is desired to resolve this issue.

The command `~ $ cat downloads/trace-minsk-RPCS31.Q2-109-21-3-1-2022-01-19-23-03-16.perfetto-trace` makes my Android humm nicely;  I would like to read this file in plain text format:
![Screenshot_20220121-025021](https://user-images.githubusercontent.com/27742457/150487672-5ec7856e-7613-4cc4-9484-9973ae36df7e.png)

**Comment by Grimler91** [comment]
So package request is only for program to view already captured traces?

**Comment by SDRausty** [comment]
I have tried `cuol https://raw.githubusercontent.com/catapult-project/catapult/master/systrace/bin/systrace`;  Followed by:

```
  ~ $ python systrace downloads/trace-minsk-RPCS31.Q2-109-21-3-1-2022-01-19-23-01-41.perfetto-trace                     
Traceback (most recent call last):                           
File "/data/data/com.termux/files/home/systrace", 
line 13, in <module>                                                  
from systrace import run_systrace                      
ModuleNotFoundError: No module named 'systrace'
```

**Comment by SDRausty** [comment]
> So package request is only for program to view already captured traces?

Yes, only for program to view already captured traces.

**Comment by xeffyr** [comment]
> Traceback (most recent call last):                           
File "/data/data/com.termux/files/home/systrace", line 13, in <module> from systrace import run_systrace                      
ModuleNotFoundError: No module named 'systrace'

```
git clone --depth=1 https://github.com/catapult-project/catapult
cd catapult/systrace
python bin/systrace
```

`systrace` is not a standalone script. It also depends on `adb`.

**Comment by xeffyr** [comment]
Check out https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy on what it is saying about Python things.

**Comment by SDRausty** [comment]
> Not installable through cpan, gem, npm, or pip

```
pip search systrace
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.
pip {download,install} systrace                                                 ERROR: Could not find a version that satisfies the requirement systrace (from versions: none)
ERROR: No matching distribution found for systrace
```

The command `systrace` does not seem to be installable with `pip`.  If it is already available in Termux, do you know where it is located @xeffyr?

**Comment by xeffyr** [comment]
@SDRausty Read commands **[above](https://github.com/termux/termux-packages/issues/8706#issuecomment-1018340625)**.

> If it is already available in Termux as stated

Package policy only stats what is eligible for packaging. Termux server disk space is not made from rubber.
