### ISSUE TITLE
megacmd "CANNOT LINK EXECUTABLE" error

### ISSUE THREAD

**Issue by flesti** [termux/termux-packages#8708]
CANNOT LINK EXECUTABLE "mega-cmd-server": cannot locate symbol "MEGAjvm" referenced by  "/data/data/com.termux/files/usr/lib/libmega.so"...
Unable to connect to service: error=2
Please ensure mega-cmd-server is running

termux-info:
Application version:
0.118.0
Packages CPU architecture:
aarch64
...
Android version: 12
Kernel build information:
Linux localhost 5.10.90-v8-g8eb17f0ef62c #1 SMP PREEMPT Fri Jan 14 11:31:47 EET 2022 aarch64 Android
Device manufacturer:
Raspberry
Device model:
Raspberry Pi 4

Same error with  a generic Android 10 tablet.

**Comment by Grimler91** [comment]
Rebuilding was not enough.

**Comment by flesti** [comment]
Indeed it wasn't. And I see quite a few of that error in the Issues section for various reasons, but too technical for me to understand.

**Comment by flesti** [comment]
works on android 10 tablet but not on lineage 19 raspberry with exact same error

**Comment by thunder-coding** [comment]
> works on android 10 tablet but not on lineage 19 raspberry with exact same error

Make sure you are using synced mirrors. and you have updated your packages
