### ISSUE TITLE
[Package]: update mupdf to 1.19.0

### ISSUE THREAD

**Issue by Mark-Joy** [termux/termux-packages#8710]
### Package description

Please update mupdf to 1.19.0
https://github.com/ArtifexSoftware/mupdf/tags

### Home page URL

https://mupdf.com/

### Source code URL

https://github.com/ArtifexSoftware/mupdf

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
I believe this is safe to bump. The sole reverse dependency of `mupdf` in our repos, namely `k2pdfopt`, indeed does not link against it.

Note that I do not at all care about third-party repos, including its-pointless repo.

**Comment by Mark-Joy** [comment]
@xtkoba 
Thank you for the update.
However tesseract version is not updated to 5.0.0-rc3-1
causing the build to fail
```
λ [~] $ pkg search tesseract
Checking availability of current mirror: ok
Sorting... Done
Full Text Search... Done                                    tesseract/stable,now 5.0.0-rc3-0 aarch64 [installed]
  Tesseract is probably the most accurate open source OCR engine available                                                                                                          tesseract-static/stable 5.0.0-rc3-0 aarch64
  Static libraries for tesseract                            
λ [~] $
```

**Comment by Mark-Joy** [comment]
I think it got updated just now. Thank you.
