### ISSUE TITLE
Process

### ISSUE THREAD

**Issue by Kendra-pokhrel12** [termux/termux-packages#8715]
![Screenshot_20220122_164420](https://user-images.githubusercontent.com/87001386/150636152-c2466835-b0fc-4e3b-a532-148a0ed3bab1.jpg)
Yesh so it shows this everytime idk what this is I am new to this thing and if y'all could please help me🥺

**Comment by Yonle** [comment]
You can't use `apt` when it's running on other session. 

In other word, You can't run two `apt` instance at once.

**Comment by Kendra-pokhrel12** [comment]
Yeah thanks man
