### ISSUE TITLE
[Package] : Update nmap

### ISSUE THREAD

**Issue by backlight-rn** [termux/termux-packages#8723]
### Package description

Nmap 7.92 has been released

### Home page URL

https://nmap.org

### Source code URL

https://github.com/nmap/nmap

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by thunder-coding** [comment]
I had initially tried to package nmap 7.92 earlier, but failed caused it contained lots of hard coded paths. I will see if I can get this done
