### ISSUE TITLE
[Package]: add toybox for termux 

### ISSUE THREAD

**Issue by ExtinctDrift19** [termux/termux-packages#8728]
### Package description

used in android toybox full information link https://www.landley.net/toybox

### Home page URL

http://www.landley.net/toybox

### Source code URL

https://github.com/landley/toybox.git

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
`toybox` lies in disabled-packages as of now.

**Comment by ExtinctDrift19** [comment]
why is the package disabled toybox

**Comment by ExtinctDrift19** [comment]
it is possible to include a package toybox for termux

**Comment by Grimler91** [comment]
What features of toybox are you looking for that are missing from busybox?

**Comment by ExtinctDrift19** [comment]
toybox addiction android in use this box

**Comment by ExtinctDrift19** [comment]
I asked the android developers to add busybox link https://issuetracker.google.com/issues/215403271

**Comment by agnostic-apollo** [comment]
Android `/system/bin/*` binaries are mostly provided by `toybox`, although not the latest version.

https://android.googlesource.com/platform/system/core/+/master/shell_and_utilities/README.md

**Comment by ExtinctDrift19** [comment]
used in termux as an addiction toybox or busybox

**Comment by ExtinctDrift19** [comment]
in the last version, which box is used and the android instead of toybox

**Comment by Grimler91** [comment]
Doesn't seem like you have any particular reason for why toybox should be added. 

Use busybox and/or /system/bin/* tools instead.
