### ISSUE TITLE
[Bug]: termux-open never loads photo

### ISSUE THREAD

**Issue by mcriley821** [termux/termux-packages#8733]
### Problem description

Termux 0.118 never loads photos when opened with `termux-open image.png`
Image 1:
![Screenshot_20220123-152704_Gallery](https://user-images.githubusercontent.com/73201124/150704143-54b26457-fda5-4c16-8ff0-52e61f0c1d5b.jpg)

However, Termux 0.117 loads just fine.
`termux-open image.png`
Image 2:
![Screenshot_20220123-162422_Gallery](https://user-images.githubusercontent.com/73201124/150704210-00a4c952-7948-47f7-861d-15c8f00117ea.jpg)

### What steps will reproduce the bug?

Simply try to open a photo using `termux-open` 

### What is the expected behavior?

The photo loads completely like in image 2

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 5.4.86-qgki-22916894-abG998USQS4BULC #1 SMP PREEMPT Tue Dec 21 20:57:18 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G998U
```

**Comment by agnostic-apollo** [comment]
> **!** Only allow `ContentProvider` access if `allow-external-apps` is set to true. **The `termux-open` and `xdg-open` commands will now silently fail if value is not set to `true`.** An error notification will be added in future versions. The caller app like `QuickEdit` may still show a flash error. Check https://github.com/termux/termux-tasker#allow-external-apps-property-optional on info on how to change the value. ([`dcedf394`](https://github.com/termux/termux-app/commit/dcedf394))

https://github.com/termux/termux-app/releases/tag/v0.118.0
