### ISSUE TITLE
[Bug]: Error using PHP7, returning error msg: cannot locate symbol "ffi_type_double"

### ISSUE THREAD

**Issue by brnyza** [termux/termux-packages#8737]
### Problem description

I need to work with PHP7, I have some devices configured with it in the past, and it is working until now.
But for new devices, I can't configure PHP7.

Tried with Termux v0.118 | v0.117 | v0.116

apachectl start

httpd: Syntax error on line 67 of /data/data/com.termux/files/usr/etc/apache2/httpd.conf: Cannot load libexec/apache2/libphp7.so into server: dlopen failed: cannot locate symbol "ffi_type_double" referenced by "/data/data/com.termux/files/usr/libexec/apache2/libphp7.so"...

### What steps will reproduce the bug?

apt install php-apache
Downgrade to php7 (using these files: https://github.com/Termux-pod/termux-pod and these files https://github.com/rdhoni/php7)
Then we get the error.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Android version:
11
Kernel build information:
Linux localhost 4.14.186-perf-g88a3791dd00c #1 SMP PREEMPT Sat Oct 16 23:21:36 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2004J19C

```

**Comment by sk0kanik** [comment]
Termux-pod/termux-pod and rdhoni/php7 are old and unrelated to this official package repo. Termux official repo also has php7. 

```shell
$ apt search php7
Sorting... Done
Full Text Search... Done
php7/stable,now 7.4.27 arm [installed]
  Server-side, HTML-embedded scripting language
php7-apache/stable 7.4.27 arm
  Apache 2.0 Handler module for PHP
php7-fpm/stable 7.4.27 arm
  FastCGI Process Manager for PHP
php7-pgsql/stable 7.4.27 arm
  PostgreSQL modules for PHP
```

**Comment by Grimler91** [comment]
Closing since we don't have any control over https://github.com/Termux-pod/termux-pod or https://github.com/rdhoni/php7. This issue tracker is for issues with packages from termux's repositories

**Comment by xeffyr** [comment]
> Closing since we don't have any control over https://github.com/Termux-pod/termux-pod

This repository is managed by @kcubeterm. So at least one of us still has control. But yeah, we now have `php7` available via `pkg` and don't need any external repository to install it.
