### ISSUE TITLE
How to initiate the build-package.sh script through another script?

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#874]
I want to automate the process of building packages.

Currently, I build dockers by running: ` docker build -t termux/package-builder . `

Then I run the following script: ` bash scripts/install-all.sh $index `

Where index is an arbitrary number.

The script install-all.sh is as follows:

```
case $1 in
1) package="aapt"
2) package="dx"
...
esac

./build-package.sh $package
```

But it returned an error:
```
ERROR: NDK not pointing at a directory!
ERROR: NDK not pointing at a directory!
ERROR: NDK not pointing at a directory!
ERROR: NDK not pointing at a directory!
ERROR: NDK not pointing at a directory!
ERROR: NDK not pointing at a directory!
ERROR: NDK not pointing at a directory!
ERROR: NDK not pointing at a directory!
ERROR: NDK not pointing at a directory!
ERROR: NDK not pointing at a directory!
```

What should I do? Thanks

**Comment by fornwall** [comment]
Are you running your `scripts/install-all.sh` inside the container or outside?

You need to ensure that the `NDK` environment variable (default value is `${HOME}/lib/android-ndk` if you don't define it yourself) points at a directory where the Android NDK is installed.

If you run inside the Docker container it should already have that setup.
