### ISSUE TITLE
After upgrade, avahi-daemon fails to connect to socket

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#8757]
After upgrade, avahi-daemon seems to be broken:

```
$ avahi-daemon
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
dbus_bus_get_private(): Failed to connect to socket /data/data/com.termux/files/usr/var/run/dbus/system_bus_socket: No such file or directory
WARNING: Failed to contact D-Bus daemon.
avahi-daemon 0.8 exiting.
```

Which also affects avahi-browse:

```
$ avahi-browse -a
Failed to create client object: Daemon not running
```

_Originally posted by @sudomain in https://github.com/termux/termux-packages/issues/8688#issuecomment-1019606112_

**Comment by xtkoba** [comment]
To restore the previous (pre D-Bus) behavior:

```bash
sed -e 's:^#enable-dbus=yes$:enable-dbus=no:' $PREFIX/etc/avahi/avahi-daemon.conf
```

which obviously kills the D-Bus features for Avahi. Just a workaround.

**Comment by xtkoba** [comment]
From `$PREFIX/share/dbus-1/system.conf`:

```xml
  <!-- Run as special user -->
  <user>messagebus</user>
```

replace `messagebus` with the Termux user (obtained by e.g. `/system/bin/whoami`).

From `$PREFIX/etc/dbus-1/system.d/avahi-dbus.conf`:

```xml
  <!-- Only root or user avahi can own the Avahi service -->
  <policy user="avahi">
    <allow own="org.freedesktop.Avahi"/>
  </policy>
```

replace `avahi` with the Termux user.

Launch `dbus-daemon`:

```
$ dbus-daemon --system
```

Replace the line `enable-dbus=no` in `$PREFIX/etc/avahi/avahi-daemon.conf` with `enable-dbus=yes` (or just comment it out).

Then `avahi-daemon` should launch with D-Bus support.

**Comment by sudomain** [comment]
Is root required? I upgraded and did the 2 replacements with the `whoami`output, but I get this:

```
$ dbus-daemon --system
dbus-daemon[10634]: Failed to start message bus: Failed to bind socket "/data/data/com.termux/files/usr/var/run/dbus/system_bus_socket": No such file or directory
```

**Comment by sudomain** [comment]
Is root required? I upgraded and did the 2 replacements with the `whoami`output, but I get this:

```
$ dbus-daemon --system
dbus-daemon[10634]: Failed to start message bus: Failed to bind socket "/data/data/com.termux/files/usr/var/run/dbus/system_bus_socket": No such file or directory
```

**Comment by xtkoba** [comment]
Though not tested:

```bash
mkdir -p $PREFIX/var/run/dbus
```

Root should not be required.

**Comment by sudomain** [comment]
It complains about an unknown group "netdev" but otherwise seems to run:
```
$ dbus-daemon --system
dbus[29106]: Unknown group "netdev" in message bus configuration file
~ $ pgrep -a dbus
29107 dbus-daemon --system
```

Commenting out the netdev section removed the error.

dbus-daemon seems to be working fine on my Android 7 but seems to get killed shortly after on my Android 11 device, so I can't test avahi-browse until I get access to another machine with avahi

**Comment by sudomain** [comment]
Avahi-daemon is working on my Android 7 (tested with `mdns-scan` on my android 11 device). Any idea what's killing `dbus-daemon --system` on my Android 11 device though? It's a Pixel 2 and I have battery "optimizations" disabled. It's running at least for a few milliseconds as evidenced by:

```
$ dbus-daemon --system ; pgrep -a dbus
3862 dbus-daemon --system
```

**Comment by xtkoba** [comment]
@sudomain That is another and separate issue. Please open a new issue for that, if it is not yet resolved. Make sure to include your termux-info. Thanks.
