### ISSUE TITLE
[Package]: The GHCup-hs Haskell installer

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-packages#8758]
### Package description

GHCup-hs is an installer for the general purpose language [Haskell](https://www.haskell.org/). 

Visit the [documentation](https://www.haskell.org/ghcup/) for installation instructions.

### Home page URL

https://www.haskell.org/

### Source code URL

https://gitlab.haskell.org/haskell/ghcup-hs

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

THANK YOU TERMUX! Haskell works like a magical musical charm in [TermuxArch](https://github.com/TermuxArch/TermuxArch) on device:

a) [haskell github](https://github.com/search?l=Haskell&o=desc&q=haskell&s=stars&type=Repositories)

b) [haskell music](https://m.youtube.com/results?sp=&search_query=Haskell+music)

c) [haskell tutorial](https://m.youtube.com/results?sp=&search_query=haskell+tutorial)

Enjoy 🎼 🎵 🎶

**Comment by xeffyr** [comment]
Literally same issue as with `rustup`. Those installers aren't working with custom distributions. They are pretty much useless unless have added upstream support for Termux and supply compatible toolchain binaries.

**Comment by SDRausty** [comment]
Termux succeeded with https://github.com/termux/termux-packages/issues/202 and this issue was related to porting libraries and adding upstream support  into the Termux environment.

GHCup-hs works flawlessly in https://github.com/TermuxArch/TermuxArch  THANK YOU TERMUX!

Did you know that Haskell can play music from code:
https://www.ecosia.org/videos?q=haskell%20music

Can anybody else try it?  I would like to hear your opinion about the way Haskell makes music from code in Termux please.

**Comment by SDRausty** [comment]
> They are pretty much useless unless have added upstream support for Termux and supply compatible toolchain binaries.

It appears upstream might be listening to some of our requests here in Termux too.

_Originally posted by @SDRausty in https://github.com/termux/termux-packages/issues/2678#issuecomment-1022092138_

Can Termux reach out to upstream more agressively to make our simple wants more known like in https://github.com/termux/termux-packages/issues/202 please?

**Comment by SDRausty** [comment]
> Literally same issue as with `rustup`. Those installers aren't working with custom distributions. They are pretty much useless unless have added upstream support for Termux and supply compatible toolchain binaries.

Has anyone asked upstream whether they know:
a) that Termux exists
b) and more importantly, Termux users wanna wanna and we do sincerely wanna wanna give, but unless upstream adds support for Termux; i.e.  Can you please consider in resolving some of our closed items at this git repository that simply do not work, and possibly easily can work, but might never work in native Termux unless a specialist becomes aware of our situation?

**Comment by SDRausty** [comment]
> Literally same issue as with `rustup`.

It appears to work in [TermuxArch](https://github.com/TermuxArch) on aarch64 0.118.0 F-Droid Android smartphone:
![Screenshot_20220128-040338](https://user-images.githubusercontent.com/27742457/151518226-dd6cce69-448a-4ef5-ae3f-01199191e171.png)

If you would like to give me a few command to try with `rustup` in Termux @xeffyr , I am all ears.

**Comment by SDRausty** [comment]
> [Can this issue be reopened please?](https://www.reddit.com/r/termux/comments/sozs75/package_request_the_ghcuphs_haskell_installer/)

> It appears to work in [TermuxArch](https://github.com/TermuxArch) on aarch64 0.118.0 F-Droid Android smartphone

**Comment by Grimler91** [comment]
Termux needs binaries compiled for termux and linked against android's libc. GHCup-hs (and rustup, and tlmgr, and ...) doesn't provide binaries for termux, so no, I don't see any way that this package can work

**Comment by SDRausty** [comment]
Pardon me for asking; Why are my comments minimized in this issue?
