### ISSUE TITLE
[package request] PyInstaller

### ISSUE THREAD

**Issue by necopinus** [termux/termux-packages#876]
Package request for [PyInstaller](http://www.pyinstaller.org/)...

Why not just install it using pip? Because if binaries compiled with PyInstaller are to work under Termux, they need to use a non-standard temp location, and to do that you need to modify PyInstaller's source. Quick-and-dirty build that works...
```
pip2 download pyinstaller
tar -xjvf PyInstaller-3.2.1.tar.bz2
cd PyInstaller-3.2.1
sed -i'' -e 's#"/usr/tmp"#"/data/data/com.termux/files/usr/tmp"#g' bootloader/src/pyi_utils.c
CFLAGS="-I/data/data/com.termux/files/usr/include/libandroid-support" LDFLAGS="-landroid-support" pip2 install .
```
I'm sure there's a more elegant way to handle `pyi_utils.c` though.

Motivation? [GAM on Termux!](https://groups.google.com/forum/#!topic/google-apps-manager/SyINM0mO4KI)

**Comment by fornwall** [comment]
Looking at [pyi_utils.c](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_utils.c#L279), it seems to check for the TMPDIR environment variable.

@necopinus Does setting TMPDIR with `export TMPDIR=$PREFIX/tmp` work before installing PyInstaller using pip?

I think we should start setting TMPDIR in Termux, as it (hopefully) fixes this and other problems).

**Comment by fornwall** [comment]
Ah, I see there is also a `libandroid-support´ part, so TMPDIR is only part of the problem. Is that for iconv?

**Comment by necopinus** [comment]
Heh... I'd initially tested this by running `TMPDIR=$PREFIX/tmp ... pip2 install ...`, which didn't work. But it _does_ work when I run `export TMPDIR=$PREFIX/tmp` first. So never mind about my `sed` line, but I 100% support having Termux start setting `TMPDIR`.

As far as `libandroid_support` goes, it's actually to work around a compile error related to `langinfo.h` (`CFLAGS`) and a `nl_langinfo` reference (`LDFLAGS`)... I think both are generally part of `libc`. There might be an `iconv` error further down, but if so these two flags solve both problems. :-)

**Comment by EralpCelebi** [comment]
I just wanted to know if this issue is going to get solved (I am asking because I don't have the knowledge that you guys have )  because if not I will take an easier path by using cpython and gcc.

**Comment by empt1xo** [comment]
yeah, can anyone help me with how to install PyInstaller with Python3 ?
