### ISSUE TITLE
[Build System]: Dependencies are not uploaded when also rebuilding reverse deps

### ISSUE THREAD

**Issue by thunder-coding** [termux/termux-packages#8773]
### Problem description

When rebuilding reverse dependencies along with package with considerable amount of deps, the package is built but not uploaded.

Instances where this gave a lot of problems:-

- https://github.com/termux/termux-packages/pull/7529
*Add more*

### What steps will reproduce the bug?

1. Update a package with a considerable amount of dependencies (eg. libuv)
2. Revbump reverse dependencies of the package
3. Now push the changes to master branch

### What is the expected behavior?

All packages (including dependencies) should be uploaded

### System information

*Unrelated*

**Comment by Martinvlba** [comment]
Also can confirm this issue

**Comment by thunder-coding** [comment]
Can this have been caused due to https://github.com/termux/termux-packages/commit/c1971731f84dd1789dfed513ee8ee4cf34fd6c6a.

This regex is out of my brain now. Probably @xeffyr (the author of the regex) can shed some light here
