### ISSUE TITLE
[Bug]: can not run package update

### ISSUE THREAD

**Issue by weishaofei** [termux/termux-packages#8778]
### Problem description

[*] Termux primary host (USA) selected
    Changing main repository
[*] Running apt update
Ign:1 https://packages.termux.org/apt/termux-main stable InRelease
Err:2 https://packages.termux.org/apt/termux-main stable Release
  Cannot initiate the connection to packages.termux.org:443 (5.102.168.153). - connect (13: Permission denied) Cannot initiate the connection to packages.termux.org:443 (5.102.168.154). - connect (13: Permission denied) Cannot initiate the connection to packages.termux.org:443 (5.102.168.155). - connect (13: Permission denied) Cannot initiate the connection to packages.termux.org:443 (5.102.168.156). - connect (13: Permission denied) Cannot initiate the connection to packages.termux.org:443 (5.102.168.157). - connect (13: Permission denied)              Reading package lists... Done                           E: The repository 'https://packages.termux.org/apt/termux-main stable Release' does not have a Release file.    N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.

### What steps will reproduce the bug?

I just reinstall it and when I run package update, it show me wrong logs

### System information

Application version:
0.118.0                                                 Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.19.113-perf-gf3cdf73f75e6 #1 SMP PREEMPT Thu Dec 30 00:15:15 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2012K11AC

**Comment by agnostic-apollo** [comment]
packages.termux.org is working fine for me. Switch to a different mirror with `termux-change-repo` like it says and try that.

**Comment by SDRausty** [comment]
> packages.termux.org is working fine for me. 

Ditto, it works as expected.  Thsnk you!

**Comment by SDRausty** [comment]
> packages.termux.org is working fine for me. 

Ditto, [`au`](https://github.com/WAE/au/blob/master/au) works as expected.  Thank you!

**Comment by weishaofei** [comment]
> packages.termux.org is working fine for me. Switch to a different mirror with `termux-change-repo` like it says and try that.

I try this and get the same error, then I uninstall Termux and FDroid， then I reinstall them， and it works now, thanks for your reply

**Comment by yn0793** [comment]
Check network permission of the plugins.
