### ISSUE TITLE
mpv failed to open file

### ISSUE THREAD

**Issue by huangyg11** [termux/termux-packages#878]
run `mpv /path/to/file.mp4` , output : 

> Playing: /path/to/file.mp4
>  (+) Video --vid=1 (*) (h264)
>  (+) Audio --aid=1 --alang=und (*) (aac)
> Error opening/initializing the selected video_out (--vo) device.
> Video: no video
> 
> 
> Exiting... (Errors when loading file)

run `mpv --vo help`, output

> Available video outputs:
>   null           : Null video output
>   image          : Write video frames to image files
>   tct            : true-color terminals

I have installed the latest termux and get mpv from apt after update.

My phone is one plus one, android 6.0.1

**Comment by vishalbiswas** [comment]
Native video output is not available in Termux. You can use `-vo tct` for true color terminal output.
