### ISSUE TITLE
luarocks not working [Bug]: 

### ISSUE THREAD

**Issue by rtm562** [termux/termux-packages#8780]
### Problem description

luarocks not working 
Doesn't work with lua53 and lua54
`/data/data/com.termux/files/usr/bin/lua: ...rmux/files/usr/share/lua/5.3/luarocks/core/sysdetect.lua:172: attempt to index a nil value
stack traceback:
        ...rmux/files/usr/share/lua/5.3/luarocks/core/sysdetect.lua:172: in upvalue 'detect_elf_system'
        ...rmux/files/usr/share/lua/5.3/luarocks/core/sysdetect.lua:248: in function <...rmux/files/usr/share/lua/5.3/luarocks/core/sysdetect.lua:242>
        (...tail calls...)
        ...rmux/files/usr/share/lua/5.3/luarocks/core/sysdetect.lua:407: in function 'luarocks.core.sysdetect.detect'
        ...com.termux/files/usr/share/lua/5.3/luarocks/core/cfg.lua:600: in function 'luarocks.core.cfg.init'
        ...a/com.termux/files/usr/share/lua/5.3/luarocks/loader.lua:19: in main chunk
        [C]: in function 'require'
        /data/data/com.termux/files/usr/bin/luarocks:8: in main chunk
        [C]: in ?`

### What steps will reproduce the bug?

run luarocks

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
Updatable packages:
termux-tools/stable 0.159 all [upgradable from: 0.158]
Android version:
7.1.2
Kernel build information:
Linux localhost 3.4.67 #1 SMP PREEMPT Sat Sep 20 15:43:00 CST 2014 armv7l Android
Device manufacturer:
LENOVO
Device model:
Lenovo A3500-H

```

**Comment by ramonrwx** [comment]
I had this same problem and fixed it by changing the line `248` of the `sysdetect.lua`

```bash
cd /data/data/com.termux/files/usr/share/lua/5.3/luarocks/core
```
```bash
vim sysdetect.lua
```
on the line `248` change:
``` lua
File: sysdetect.lua
──────────────────────────────────────────
 248   │    local system = detect_elf_system(fd, hdr, sections)
```
to:
```lua
File: sysdetect.lua
──────────────────────────────────────────
 248   │    local system = "linux"
```

**Comment by rtm562** [comment]
> 

Thank you very much friend, everything is working.
