### ISSUE TITLE
[Package]: timewarrior

### ISSUE THREAD

**Issue by Melind4** [termux/termux-packages#8784]
### Package description

Timewarrior - Commandline Time Tracking and Reporting

### Home page URL

https://timewarrior.net/

### Source code URL

https://github.com/GothenburgBitFactory/timewarrior

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Is there an issue with the package we have? https://github.com/termux/termux-packages/tree/master/packages/timewarrior
