### ISSUE TITLE
[Package]: LevelDB

### ISSUE THREAD

**Issue by dbahero** [termux/termux-packages#8788]
### Package description

LevelDB is a fast key-value storage library written at Google that provides an ordered mapping from string keys to string values.                                                

### Source code URL

https://github.com/google/leveldb

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Already packaged under the name of `leveldb`. If you have trouble with this package, then please open a new issue. Thanks.
