### ISSUE TITLE
how to start dockers

### ISSUE THREAD

**Issue by Angel0726** [termux/termux-packages#8797]
```bash
pkg install runc root-repo
pkg install docker
```
i install dockers. i can use `docker -v`， but i can't use `docker pull`
```bash
~ $ docker -v
#     Docker version v20.10.2-ce, build
~ $ docker pull hell
#     Using default tag: latest
#     Cannot connect to the Docker daemon at unix:///data/docker/run/docker.sock. Is the docker daemon running?
```

**Comment by Grimler91** [comment]
Start the docker daemon first, and run it as root. See https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27#3-running

**Comment by Angel0726** [comment]
> Start the docker daemon first, and run it as root. See https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27#3-running


it's necessary  to  compile the phone's kernel ？

**Comment by SDRausty** [comment]
> it's necessary to compile the phone's kernel ？

No, compile kernels is fun to do though.

**Comment by wmcbtech30** [comment]
> > Start the docker daemon first, and run it as root. See https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27#3-running
> 
> it's necessary to compile the phone's kernel ？

@Angel0726 Recompile it with necessary features enabled required for docker (full cgroups, namespaces. etc), if you haven't compiled a kernel for your device before then it's best to toy around and compile it. you could look online for phone-specific kernel compilation instructions as well as root
