### ISSUE TITLE
[Package Request] sc

### ISSUE THREAD

**Issue by atomi** [termux/termux-packages#880]
`sc`: Terminal based spreadheet calc `apt-get install sc`

or sc-im https://github.com/andmarti1424/sc-im

**Comment by atomi** [comment]
open issue here https://github.com/termux/termux-packages/issues/246

**Comment by Wetitpig** [comment]
Done. In #2183

**Comment by sdrausty** [comment]
@atomi `sc` is available via https://sdrausty.github.io/TermuxArch/ today.
```
pacman -S sc
resolving dependencies...
looking for conflicting packages...

Packages (1) sc-7.16-6

Total Download Size:   0.14 MiB
Total Installed Size:  0.36 MiB

:: Proceed with installation? [Y/n]
```

Package request: sc +1
Reasons: small size and terminal based

**Comment by atomi** [comment]
Yes I saw. And thanks.
