### ISSUE TITLE
[Package]: add flatpack for termux 

### ISSUE THREAD

**Issue by ExtinctDrift19** [termux/termux-packages#8803]
### Package description

full information https://flatpak.org/

### Home page URL

https://flatpak.org/

### Source code URL

https://github.com/flatpak/flatpak

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by dbahero** [comment]
#1278
