### ISSUE TITLE
[Package]: snapcast client

### ISSUE THREAD

**Issue by headmidtail** [termux/termux-packages#8814]
### Package description

Additional to the snapcast-server [#7929](https://github.com/termux/termux-packages/issues/7929) the snapcast client would be appreciated. Especially because the Snapcast APP is not compatible with the snapcast-server plugin which is (newly) included in music player daemon (MPD).

### Home page URL

https://github.com/badaix/snapcast

### Source code URL

https://github.com/badaix/snapcast.git

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

The snapcast-server [#8301](https://github.com/termux/termux-packages/pull/8301) was already added, but unfortunately without the client part. Might be there is a technical reason for that?

**Comment by xtkoba** [comment]
`snapcast-client` was not then added as it was not requested.

As I wrote in the referenced issue, a point is that we have to pretend not to be Android to build this.

**Comment by headmidtail** [comment]
Many thanks!
