### ISSUE TITLE
[Bug]: cliaoke send 'alsa' and 'alsa_seq' as parameter to fluidsynth

### ISSUE THREAD

**Issue by bilrou** [termux/termux-packages#8825]
### Problem description

In this code file there are 2 problems:

```https://github.com/jessfraz/cliaoke/blob/master/karaoke/play_linux.go```
line 12
```soundfontPath = /usr/share/sounds/sf2/FluidR3_GM.sf2"```change to                                             ```soundfontPath = "/data/data/com.termux/files/usr/share/soundfonts/FluidR3_GM.sf2"```                                                                                 line 17 change alsa for pulseaudio --exit-idle-time=-1
```cmd := exec.Command(fluidsynthBinary, "-a", "alsa", "-m", "alsa_seq", "-l", "-i", soundfontPath, localmid)```

### What steps will reproduce the bug?

cliaoke one

### System information

termux-info:

```
armv7l
```

**Comment by bilrou** [comment]
This sounfont file doesn't come with fluidsynth, but I could find it here:
https://github.com/urish/cinto/blob/master/media/FluidR3%20GM.sf2

**Comment by xtkoba** [comment]
Any specific reason to use `$PREFIX/share/soundfonts/FluidR3_GM.sf2` instead of `$PREFIX/share/sounds/sf2/FluidR3_GM.sf2`?

As for `FluidR3_GM.sf2` not being packaged, I am going to add a post-install notice.

**Comment by bilrou** [comment]
> Any specific reason to use `$PREFIX/share/soundfonts/FluidR3_GM.sf2` instead of `$PREFIX/share/sounds/sf2/FluidR3_GM.sf2`?

It wasn't my idea. This version of fluidsynth required this specific directory the first time I added a .sf2 file

**Comment by xtkoba** [comment]
I see. Let's just align with the version of `fluidsynth` we use.
