### ISSUE TITLE
[Package]: putty-tools

### ISSUE THREAD

**Issue by lars18th** [termux/termux-packages#8836]
### Package description

The "putty-tools" package includes the very usefull tool "psusan". Read more about this tool at https://www.mankier.com/1/psusan

This package is available in recent Debian/Ubuntu distributions. It isn't the same as the putty package, nor the pterm.

### Home page URL

https://packages.debian.org/sid/putty-tools

### Source code URL

http://deb.debian.org/debian/pool/main/p/putty/putty_0.76.orig.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Currently part of `putty` package in the `x11` repo. It may be a good idea to subpackage those tools to avoid installing unnecessary dependencies.

**Comment by lars18th** [comment]
> Currently part of `putty` package in the `x11` repo. It may be a good idea to subpackage those tools to avoid installing unnecessary dependencies.

Yes, I agree with that. Because to execute the `psusan` we don't need at all the `x11` base packages, nor the basic PuTTY tools.
I hope some one will spplit it.

Thank you!

**Comment by lars18th** [comment]
Thank you @xtkoba for the PR #593 . I hope it will be merged soon. However, one question: Why it continues to be in the "x11-packages" section if these tools are terminal only?

**Comment by Grimler91** [comment]
> However, one question: Why it continues to be in the "x11-packages" section if these tools are terminal only?

Our build system is currently not flexible enough to put subpackages in another section

**Comment by lars18th** [comment]
> > However, one question: Why it continues to be in the "x11-packages" section if these tools are terminal only?
> 
> Our build system is currently not flexible enough to put subpackages in another section

OK, my only concern if this package could be installed without installing _anything_ related to X11 support.

**Comment by Grimler91** [comment]
@lars18th after PR has been merged it won't depend on anything x11 related, but the x11-repo package needs to be installed so that apt is subscribed to the x11 repository

**Comment by lars18th** [comment]
> after PR has been merged it won't depend on anything x11 related, but the x11-repo package needs to be installed so that apt is subscribed to the x11 repository

Ok, that's a very minor problem. Thank you very much!

**Comment by lars18th** [comment]
Hi,

Interesting use of this package discussed here: https://github.com/termux/termux-app/discussions/2565
