### ISSUE TITLE
Can't do apt update

### ISSUE THREAD

**Issue by Titely** [termux/termux-packages#884]
Hello ! I haven't used my tablet for about two weeks, and when I wanted to do `apt update` with termux, it failed. Here's the result of the command:
```
$ apt update
Get:1 http://termux.net stable InRelease [1666 B]
Get:2 http://termux.net stable/main all Packages [3848 B]
Ign:2 http://termux.net stable/main all Packages
Get:3 http://termux.net stable/main aarch64 Packages [51.3 kB]
Ign:3 http://termux.net stable/main aarch64 Packages
Get:2 http://termux.net stable/main all Packages [12.2 kB]
Err:2 http://termux.net stable/main all Packages
  Hash Sum mismatch
Fetched 12.2 kB in 1s (8280 B/s)
Reading package lists... Done
E: Failed to fetch http://termux.net/dists/stable/main/binary-all/Packages  Hash Sum mismatch
E: Failed to fetch http://termux.net/dists/stable/main/binary-aarch64/Packages  Writing more data than expected (51316 > 51308) [IP: 104.18.36.234 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
I tried to reinstall termux but nothing changed, any idea ?

**Comment by Titely** [comment]
I've also tried different solutions found in other issues

**Comment by fornwall** [comment]
Hm, this seems to happen a lot recently. I just explicitly evicted the cloudflare cache (again) - can you try running `apt update` again?

**Comment by Titely** [comment]
I tried `apt clean` and `apt update`, but unfortunately I have the same problem

**Comment by fornwall** [comment]
Still having this problem?

**Comment by Titely** [comment]
No it's working now, thank you =)

**Comment by Siapran** [comment]
Hi, I'm having similar issues recently, and I haven't been able to resolve them using the issue tracker.
apt gives me the following output:
```
-bash-4.4$ apt clean
-bash-4.4$ apt update
Get:1 http://termux.net stable InRelease [1666 B]
Get:2 http://termux.net stable/main all Packages [3760 B]
Ign:2 http://termux.net stable/main all Packages
Get:3 http://termux.net stable/main arm Packages [51.2 kB]
Ign:3 http://termux.net stable/main arm Packages
Get:2 http://termux.net stable/main all Packages [11.8 kB]
Err:2 http://termux.net stable/main all Packages
  Writing more data than expected (12245 > 11847) [IP: 104.18.36.234 80]
Get:3 http://termux.net stable/main arm Packages [227 kB]
Err:3 http://termux.net stable/main arm Packages
  
Fetched 229 kB in 1s (190 kB/s)   
Reading package lists... Done
E: Failed to fetch http://termux.net/dists/stable/main/binary-all/Packages  Writing more data than expected (12245 > 11847) [IP: 104.18.36.234 80]
E: Failed to fetch http://termux.net/dists/stable/main/binary-arm/Packages  
E: Some index files failed to download. They have been ignored, or old ones used instead.
-bash-4.4$ apt --version
apt 1.2.12 (arm)
```

I haven't tried to reinstall termux yet, because I have some data that would take some time to backup.

**Comment by fornwall** [comment]
@Siapran Can you try running `apt update` again?

**Comment by Siapran** [comment]
It does seem to work now, thank you.

**Comment by godenji** [comment]
Same problem here on Nexus 5X running 7.1.1

Does the phone need to be rooted to install/update packages, or is this the Cloudflare cache issue referred to above?

**Comment by fornwall** [comment]
@godenji Root is _not_ required! It's probably the http caching issue - try again.

**Comment by godenji** [comment]
@fornwall that was it, caching issue, all set now, thanks ;-)

**Comment by dhenisusanto** [comment]
E: Sub-process https received signal 4.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
$ Method https has died unexpectedly!

**Comment by dhenisusanto** [comment]
Help me
