### ISSUE TITLE
Rails new not working with rails 7 (LoadError: dlopen failed: library "libm.so.6" not found in nokogiri . )

### ISSUE THREAD

**Issue by surya-bug** [termux/termux-packages#8851]
when I run rails new <project name> . It starts installing the gems normally but it exits with an error which points at LoadError: dlopen failed: library "libm.so.6" not found in nokogiri . 

Please find the attached screenshots for your reference. ![Screenshot_2022-01-31-13-19-54-834_com.termux.jpg](https://user-images.githubusercontent.com/77871514/151757515-15347781-3786-458d-917b-7a856d37aeac.jpg)

![Screenshot_2022-01-31-13-20-13-088_com.termux.jpg](https://user-images.githubusercontent.com/77871514/151757535-940cadd0-44ee-468a-ae54-7d0adf903cf2.jpg)

**Comment by sk0kanik** [comment]
#8583

**Comment by surya-bug** [comment]
Closing the issue as it's a duplicate of #8583
