### ISSUE TITLE
I am having issues with PKG upgrade in termux. 


### ISSUE THREAD

**Issue by Rehan587** [termux/termux-packages#8856]
![Screenshot_2022_0131_223914.jpg](https://user-images.githubusercontent.com/84271835/151839959-a3001082-2c95-43d9-824f-70373355a92c.jpg)

Pls help.

Here is my device info.

Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main stable main
# sources.list.d/hax4us_pentesting.list
deb https://hax4us.github.io/termux-x/ pentesting main
# sources.list.d/gushmazuko.list
deb https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.186-g4f65b02ee-dirty #1 SMP PREEMPT Thu Dec 16 18:28:32 CST 2021 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1915

**Comment by xtkoba** [comment]
Reads `EXPKEYSIG` for https://hax4us.github.io/termux-x/.

**Comment by Rehan587** [comment]
> Reads `EXPKEYSIG` for https://hax4us.github.io/termux-x/.

I tried the steps there but it shows that the apt-key is deprecated.. pls help.

**Comment by Hax4us** [comment]
@Rehan587 Now i don't Maintain it  use new repo
https://github.com/Hax4us/TermuxBlack

And yes don't open issues regarding external repositories here :) Thanks
