### ISSUE TITLE
The device is not a tty

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#886]
When I run the run-docker.sh

The response is like that:
`
the input device is not a TTY
`

Why would this happen?

**Comment by NobbZ** [comment]
Your terminal isn't recognized as a tty device. 

Perhaps it might work by simply setting `TERM=xterm`.

If on windows git bash or msys, it might help to prefix the command by winpty. 

If these options don't help, please provide more detailed information.

**Comment by fornwall** [comment]
@Wetitpig Which operating system are you using? Are you running `scripts/run-docker.sh` from the terminal`

**Comment by Wetitpig** [comment]
Yes. I am running `scripts/run-docker.sh` from a bourne shell, which doesn't support bash.
