### ISSUE TITLE
groovysh and libjansi incompatible 

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#8861]
### Problem description

groovysh broken after upgrade

Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path: /usr/java/packages/lib:/lib:/usr/lib, /data/data/com.termux/files/usr/tmp/libjansi-64-8461255553170192958.so: dlopen failed: "/data/data/com.termux/files/usr/tmp/libjansi-64-8461255553170192958.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183) (Possible cause: can't load AMD 64 .so on a AARCH64 platform)]

### What steps will reproduce the bug?

type groovysh

### System information

Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# sources.list.d/termuxblack.list
deb https://hax4us.github.io/TermuxBlack/ termuxblack main
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.113-22384011 #1 SMP PREEMPT Tue Dec 7 15:09:17 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-M315F

**Comment by Grimler91** [comment]
It seem to download a x86_64 libjansi instead of using the one in $PREFIX. 

I don't get the same error as you though (on aarch64, android 11), for me it gives a prompt and seemingly works even though it complains about the libjansi lib:

```
groovysh
Failed to load native library:jansi-2.4.0-ccc22f7a69256198-libjansi.so. osinfo: Linux/arm64
java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/tmp/jansi-2.4.0-ccc22f7a69256198-libjansi.so: dlopen failed: library "libc.so.6" not found: needed by /data/data/com.termux/files/usr/tmp/jansi-2.4.0-ccc22f7a69256198-libjansi.so in namespace (default)
WARNING: java.lang.System::setSecurityManager is deprecated and will be removed in a future release.
Groovy Shell (4.0.0, JVM: 17-internal)
Type ':help' or ':h' for help.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
groovy:000>
```

**Comment by xtkoba** [comment]
The failure shown in <a href="https://github.com/termux/termux-packages/issues/8861#issuecomment-1026578038">Grimler91's comment</a> seems to be the same as #8439 and a similar solution will apply.

The main issue needs more investigation.

**Comment by xtkoba** [comment]
As a result of a workaround I got the following:

```
$ groovysh
WARNING: java.lang.System::setSecurityManager is deprecated and will be removed in a future release.
@|green Groovy Shell|@ (4.0.0, JVM: 17-internal)
Type '@|bold :help|@' or '@|bold :h|@' for help.
-------------------------------------------------------------------------------
groovy:000> 
```

Ugly but not unusable.

**Comment by mbohun** [comment]
I just ran into this same issue today:

```
[mbohun@danctnix uniprot_org_get_taxonomy.gist]$ groovysh
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp -Dawt.useSystemAAFontSettings=gasp 
Jun 26, 2023 12:42:53 AM org.apache.groovy.groovysh.Main setTerminalType
WARNING: ansi will be disabled because an error occurred while installing ansi: Could not load library. Reasons: [no jansi in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib, /tmp/libjansi-64-12955420002396811992.so: /tmp/libjansi-64-12955420002396811992.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a AARCH64 platform)]
Groovy Shell (4.0.12, JVM: 20.0.1)
Type ':help' or ':h' for help.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
groovy:000> 
```

This is on PineTab2, running:
```
[mbohun@danctnix ~]$ uname -a
Linux danctnix 6.3.0-5-danctnix #1 SMP PREEMPT_DYNAMIC Mon Jun 12 06:40:39 UTC 2023 aarch64 GNU/Linux
```
```
[mbohun@danctnix ~]$ tmux -V
tmux 3.3a
```
