### ISSUE TITLE
Error 502, bad gateway - Can't install and package

### ISSUE THREAD

**Issue by Pedram987** [termux/termux-packages#8865]
Hi I can't install any PKG, I get 502 error while installing 
![Screenshot_2022-02-01-12-25-54-747_com termux](https://user-images.githubusercontent.com/66957090/151939318-9be8aa70-9e94-4521-b783-27e7fbdaf337.jpg)
I copied the address to open it on browser, same error on browser too

**Comment by thunder-coding** [comment]
Duplicate #6726
