### ISSUE TITLE
[Package]: libbthread

### ISSUE THREAD

**Issue by j0hnd3v** [termux/termux-packages#8871]
### Package description

bionic library that provide some missing posix threading function.

### Source code URL

https://github.com/tux-mind/libbthread

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Not working, according to https://github.com/termux/termux-packages/issues/4378#issuecomment-538683862.

**Comment by xtkoba** [comment]
Duplicate of #234.
