### ISSUE TITLE
[Bug]: github action: libgnustep-base does not compile for x86_64

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#8874]
### Problem description

https://github.com/Maxython/termux-packages-pacman/runs/5018309095?check_suite_focus=true

### What steps will reproduce the bug?

update

### What is the expected behavior?

empty commit

### System information

It is github action

**Comment by xtkoba** [comment]
This is because the build system (`gnustep-make`) pollutes `LD_LIBRARY_PATH`. The `build.sh` for `libgnustep-base` already has a workaround for `$CPP`, `$CC`, and `$CXX`, but apparently it is not enough.
