### ISSUE TITLE
[Bug]: lldb unable to launch process

### ISSUE THREAD

**Issue by shadmansaleh** [termux/termux-packages#8880]
### Problem description

On arm android-11 devices if you you try to debug using lldb it fails to launch process . I have also tried on aarch64 androd-10 there it worked fine.

This bug might be arm specific/android 11 specific or something else I'm not sure.

### What steps will reproduce the bug?

1. get a test c program. for example:
    `test.c`:
```c
#include <stdio.h>

int main() {
  printf("Hello world");
  for (int i=1; i<=10; i++)
    printf("Num: %d\n", i);
  return 0;
};
```
2. compile the file with clang
```sh
clang -g test.c -o test
```
3. open it with `lldb`
```sh
lldb test
```
4. run it under lldb
```
run
```

`lldb` fails to launch process and throws following error
```
error: failed to launch or debug process
```

### What is the expected behavior?

The test program should run under debugger(lldb).

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 3.10.108-g2a746c1bc1a-dirty #18 SMP PREEMPT Fri Jan 21 01:32:22 GMT 2022 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J700H
```

**Comment by xtkoba** [comment]
FYI, there was a similar report in another issue: https://github.com/termux/termux-packages/issues/4282#issuecomment-916651936.

(Note that #4282 itself is not necessarily relevant to this.)

**Comment by shadmansaleh** [comment]
Now thinking about it this might not be arm specific . The aarch64 device I tried on was running Android 10 stock samsung rom . And the arm one is running Android 11 lineageOS . So this might be cause because of android version difference too . I

**Comment by xtkoba** [comment]
Possibly related upstream issue (for i686): https://github.com/llvm/llvm-project/issues/45197

**Comment by xtkoba** [comment]
This cannot be fixed on our side. Thanks.

**Comment by TomJo2000** [comment]
Resolved as of LLVM 20 (perhaps earlier).
- 32 Bit builds of `lldb` have been reenabled in #25750
