### ISSUE TITLE
Is lfortran package working?

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#8884]
First, tried an interactive usage:

```
$ lfortran
Interactive prompt requires the LLVM backend to be enabled. recompile with 'WITH_LLVM=yes'.
```

then a batch mode:

```
$ lfortran pi_grec_mc.f90 -o pi_test
 Compiling Fortran files to [...] requires the LLVM backend to be enabled. recompile with 'WITH_LLVM=yes'.
```

What am I missing?

Termux is 0.118 version, with all updates.

**Comment by xtkoba** [comment]
Try `--backend=cpp`:

```
$ lfortran --backend=cpp hello.f90
```

**Comment by angelog0** [comment]
OK, that works. Is this the normal way to use it....?

Besides that, almost nothing useful is implemented..  I get many `This BLA BLA is not implemented...`

**Comment by Grimler91** [comment]
> OK, that works. Is this the normal way to use it....?

Until compilation errors for llvm backend are solved, yes.

> Besides that, almost nothing useful is implemented.. I get many `This BLA BLA is not implemented...`

See the lfortran webpage for info about what is currently supported: https://lfortran.org/

**Comment by xtkoba** [comment]
Apparently LFortran only supports LLVM 11: https://fortran-lang.discourse.group/t/lfortran-minimum-viable-product-mvp/1922.

With LLVM 13.0.1 (the latest `libllvm` package) I have the following error:

```
In file included from /var/tmp/lfortran-v0.14.0/src/lfortran/codegen/evaluator.cpp:53:
/var/tmp/lfortran-v0.14.0/src/lfortran/codegen/KaleidoscopeJIT.h:22:10: fatal error: 'llvm/ExecutionEngine/Orc/LambdaResolver.h' file not found
#include "llvm/ExecutionEngine/Orc/LambdaResolver.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by xtkoba** [comment]
So I would say this should go upstream. We cannot do anything about this. Please open a new issue to make a request for enabling LLVM support when it is ready upstream. Thanks.

**Comment by SDRausty** [comment]
>this should go upstream. We cannot do anything about this. 

Upstream helped with [povray's](https://github.com/termux/termux-packages/issues/202) [boost libs](https://github.com/termux/termux-packages/issues?q=is%3Aissue+boost), hopefully LLVM support will come quicker.  In the meantime fortran is prolific in TermuxArch:

There are 81 `yay fortran` results in x86_64 on aarch64 Android:
![Screenshot_20220318-134238](https://user-images.githubusercontent.com/27742457/159055729-758759c5-8194-49dd-a513-5da8e75ac392.png)

**Comment by xtkoba** [comment]
Seems like now it is ready: #13669.

(I reuse this issue as I am a moderator of Termux project. Usually a new issue should be opened, as mentioned above.)

**Comment by xtkoba** [comment]
#13669 has been merged.
