### ISSUE TITLE
[Package]: Aidl for arm64 and armv7la

### ISSUE THREAD

**Issue by freindlytech** [termux/termux-packages#8886]
### Package description

Aidl  is a build tool for making apps in android and it's very useful for Android developers but it's not launched for arm64 but one guy named Lzhiyong already launched it for arm64 and armv7la for sdk31  but I don't know when he stop updating it so I request termux developer to add aidl(sdk32)  in termux and keep 
Updating it and thanks for aapt2 also Sir 🙏🙏 , You are really helpful sir ☺️

### Home page URL

https://android.googlesource.com/platform/frameworks/base/+/1a008c1/tools

### Source code URL

https://android.googlesource.com/platform/frameworks/base/+/1a008c1/tools/aidl/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I Don't have pc to Compile it and don't know how to compile it for arm64 and armv7la 😅😅

**Comment by xtkoba** [comment]
Thank you for the packaging request. We will handle it. It may take a considerable time to package it, so please be patient. No more "please package" message without any useful information is needed (for that purpose just "+1" the package description). Thank you.
