### ISSUE TITLE
[Bug]: Got a Error When Using aapt2 with gradle

### ISSUE THREAD

**Issue by freindlytech** [termux/termux-packages#8887]
### Problem description

Termux recently added aapt2 Support and I use aapt2 in gradle to make apk and got a error 
![Screenshot_20220203-095959](https://user-images.githubusercontent.com/94637042/152281818-d4360e0f-e3a7-48f8-bc01-3ba84ff25283.png)
I didn't get error if I use  Lzhiyong aapt2 Here is the link https://github.com/Lzhiyong/sdk-tools but the guy is giving sdk31 aapt2 and maybe he didn't update it so I use termux aapt2 , Plz Fix this error.
I want aapt2 from this site for arm64 and armv7la
https://maven.google.com/web/m_index.html?q=aapt2#com.android.tools.build:aapt2
I am 80% sure this site aapt2 will fix the error if you guys launched it for arm64 from this site 

### What steps will reproduce the bug?

Running The Gradle Will Reproduce Error

### What is the expected behavior?

The Expected Behaviour is Gradle runs successfully

### System information

termux-info:

```

```

**Comment by deenu713** [comment]
I got the same error. Please fix this issue.

**Comment by xtkoba** [comment]
Thank you for the bug report. We will investigate it. It may take a considerable time to solve this issue, so please be patient. No more "please fix" message without any useful information is needed (for that purpose just "+1" the problem description). Thank you.

**Comment by Lzhiyong** [comment]
> Thank you for the bug report. We will investigate it. It may take a considerable time to solve this issue, so please be patient. No more "please fix" message without any useful information is needed (for that purpose just "+1" the problem description). Thank you.

I'm glad to see that Termux officially supports `build-tools`.
the main reason for this problem is the problem of `StringPiece` and `String` conversion.
we just need to patch `androidfw`, see [https://github.com/Lzhiyong/sdk-tools/patches/StringPiece.h.patch](https://github.com/Lzhiyong/sdk-tools/blob/master/patches/StringPiece.h.patch)

**Comment by Lzhiyong** [comment]
@xtkoba @agnostic-apollo @Grimler91 ...
The xeffyt has left the termux dev team or changed the github nickname? 
the `tagged pointer` problem of openjdk has not been solved yet, but I found that this account does not exist anymore, someone knows?

**Comment by agnostic-apollo** [comment]
Xeffyr has left termux github org and deleted related accounts including reddit.

**Comment by xtkoba** [comment]
Just that the version of our `aapt2` is too low to work with recent Gradle plugin. <a href="https://developer.android.com/studio/releases/build-tools?hl=en">Support for AAPT2 daemon mode has been added since Build Tools Revision 26.0.2.</a>

Any known reason we stick to `7.1.2_r33`?

**Comment by Grimler91** [comment]
> Any known reason we stick to 7.1.2_r33?

I suppose because android 7/api level 24 is the lowest version we support, though 7.1 corresponds to api level 25. 
Using build tools revision 26 or higher seems reasonable. If it causes issues we can add an "aapt-legacy" package for lower android versions

**Comment by mr-from-us** [comment]
I also get the same error I want to use latest gradle plugin but not working 😭😭 , Just Waiting For The Developer To Update aapt2 and keep updating it

**Comment by freindlytech** [comment]
You must Have To Update to 7.3.0-alpha01(it provide support for sdk32 which is the latest ) to fix the error in aapt2 with gradle and keep updating it with this site aapt2 version https://maven.google.com/web/m_index.html?q=aapt2#com.android.tools.build:aapt2 
 to fix future error .

**Comment by freindlytech** [comment]
@xtkoba 
Buddy I reinstalled gradle and termux  and use aapt: 12.0.0.27  and Successfully build ,ThanksYou So so much you helped a lot , Buddy Plz Keep Updating aapt2 when google updates it and thanks a lot.

Here is the Build Successful Screenshot.

![Screenshot_20220209-194641](https://user-images.githubusercontent.com/94637042/153220314-47b99af0-571a-4008-98c5-65c8b4806bb3.png)

**Comment by chemseddine201** [comment]
same error appeared to me caused by antivirus on windows 10, solved after stopping antivirus.
