### ISSUE TITLE
[Bug]: id3v2 is broken

### ISSUE THREAD

**Issue by sp4rkie** [termux/termux-packages#8889]
### Problem description

id3v2 is broken. Simply calling:

        id3v2

produces:

        CANNOT LINK EXECUTABLE "id3v2": cannot locate symbol "uncompress" referenced by "/data/data/com.termux/files/usr/lib/libid3-3.8.so"...

### What steps will reproduce the bug?

install the package:

        apt install id3v2
type:

        id3v2

### What is the expected behavior?

id3v2 should link against libid3-3.8.so and resolve all symbols

### System information

termux-info:
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.148-perf+ #1 SMP PREEMPT Tue Sep 3 19:28:08 2019 aarch64 Android
Device manufacturer:
Sony
Device model:
G8441

all packages/apps on most recent versions installed from F-Droid
```

```

**Comment by sp4rkie** [comment]
you're faster than light :-)  tnx for fixing

**Comment by Grimler91** [comment]
@sp4rkie you are welcome

@thunder-coding saw now that you assigned it to yourself, sorry for double-work. 

Probably a good idea to use the assign functionality more, I'll try to become better at that
