### ISSUE TITLE
[Package]: add lfortran for termux 

### ISSUE THREAD

**Issue by ExtinctDrift19** [termux/termux-packages#8892]
### Package description

Full information https://lfortran.org/

### Home page URL

https://lfortran.org/

### Source code URL

https://gitlab.com/lfortran/lfortran

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by buribu** [comment]
#8831
