### ISSUE TITLE
php 7.1.3 gettype(-1) returns "double" instead of "integer" when built with clang

### ISSUE THREAD

**Issue by vdb** [termux/termux-packages#890]
Android package php 7.1.3. Command ``php -r "echo gettype(-1);"`` returns ''double", should be "integer". This breaks programs that rely on correct type value. I've checked php7.1.3 amd64 package on ubuntu and return value is "integer" as expected.

**Comment by vishalbiswas** [comment]
For me, it returns `integer` as expected

**Comment by Grimler91** [comment]
It works as expected on my arm device. Which arch are you using?

**Comment by vdb** [comment]
uname -a:
Linux localhost 3.18.20-ge45c102 #1 SMP PREEMT aarch64 Android

**Comment by vdb** [comment]
CPU: Qualcomm Snapdragon 430 MSM8937

**Comment by mawatech** [comment]
Same for me:

$ uname -a
Linux localhost 3.18.19+ #1 SMP PREEMPT Tue Dec 6 15:46:33 CST 2016 aarch64 Android
$ php -r "echo gettype(-1);"
double$
$

**Comment by fornwall** [comment]
Hm, so it seems to be a problem at least for 64-bit arm, and working on 32-bit arm.

**Comment by Neo-Oli** [comment]
That's really annoying. It means that functions like `substr($str,-1);` don't work, which breaks a hell of a lot of programs.

**Comment by Neo-Oli** [comment]
I tried running Ubuntu on aarch64 (using proot on termux) with version 7.0.15 and it works as expected returning `integer`. I compiled the same version of php for termux and the issue remains. So either it's a termux specific issue or debian/ubuntu have a fix in their arm64 package.

**Comment by its-pointless** [comment]
compiling with gcc fixes this on arm64

**Comment by Neo-Oli** [comment]
I tried building it with gcc, and it does indeed fix the problem.

**Comment by its-pointless** [comment]
The tricky bit now is getting a test case or something so the ndk guys can fix it.
https://github.com/android-ndk/ndk etc ...

**Comment by fornwall** [comment]
Wow, building with clang causes this? Interesting!

**Comment by fornwall** [comment]
The `7.1.5` update of the php package is built with gcc and should have the problem fixed.

We still need to find the reason why the problem occurs when built with clang as [gcc is planned to be removed from the NDK](https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md), but we can build with gcc for now to have a working package, and await further updated PHP and NDK versions to see if they fix the problem.

**Comment by fornwall** [comment]
Just tried again with PHP v7.1.6 and clang from NDK r15 - still same problem.

**Comment by its-pointless** [comment]
Time to post issue on ndk ?

**Comment by fornwall** [comment]
This turned out to be a bug in php (inline aarch64 assembly) fixed in https://github.com/php/php-src/commit/8c8679207ae5ada8751288e75b78c928a4d34d1d.

This fix has been backported to the newly released 7.1.7 version of the php package, which is now built with clang.
