### ISSUE TITLE
[Package]: python-pip

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#8916]
### Package description

A collection of pip packages installer for python3

### Home page URL

pip.pypa.io/en/stable

### Source code URL

https://github.com/pypa/pip

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by sk0kanik** [comment]
Isn't it already included with python?

**Comment by kcubeterm** [comment]
When you install python in termux, pip install automatically. So you don't require python-pip like standard Linux.
