### ISSUE TITLE
[Bug]: lua51, libtiledb, libtvision and oorexx

### ISSUE THREAD

**Issue by j0hnd3v** [termux/termux-packages#8934]
### Problem description

Although the issues were closed 18 hours ago there are no packages for lua51, libtiledb, libtvision and oorexx in the repository.

**Comment by Grimler91** [comment]
Built "manually" in https://github.com/termux/termux-packages/actions/runs/1803168849. For some reason CI doesn't seem to have picked up that those packages changed
