### ISSUE TITLE
[Package]: add nsnake

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#8943]
### Package description

A classic snake game in terminal

### Home page URL

https://github.com/alexdantas/nSnake

### Source code URL

https://github.com/alexdantas/nSnake

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Already packaged.
