### ISSUE TITLE
[Bug]: Nsnake more levels redirects to worst website

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#8944]
### Problem description

Nsnake is a good snake game. When it click on download more levels, it redirects to the worst website from http://nsnake.alexdantas.net/ to https://www.sona9.com/... virus. Can you please update link to download more levels? 

### What steps will reproduce the bug?

1.type nsnake
2. level select
3. click on more levels

### What is the expected behavior?

The more levels should be more clearly

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
That is indeed not great. Thanks for reporting!
