### ISSUE TITLE
[Package]: ClickHouse

### ISSUE THREAD

**Issue by dbahero** [termux/termux-packages#8947]
### Package description

 ClickHouse® is a free analytics DBMS for big data                                                                           

### Home page URL

https://clickhouse.com/

### Source code URL

https://github.com/ClickHouse/ClickHouse

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Duplicate of #6372.
