### ISSUE TITLE
[Package]: debezium

### ISSUE THREAD

**Issue by dbahero** [termux/termux-packages#8949]
### Package description

debezium - Change data capture for a variety of databases.
Please log issues at                        https://issues.redhat.com/browse/DBZ.

### Home page URL

https://debezium.io/

### Source code URL

https://github.com/debezium/debezium

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Available at <a href="https://search.maven.org/search?q=g:io.debezium">Maven Central Repository</a>. Any specific reason we should package this?
