### ISSUE TITLE
[New Mirror] HIT

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#8953]
|  Repository   | sources.list entry  |
|  ----  | ----  |
| [Main](https://github.com/termux/termux-packages)  | `deb https://mirrors.hit.edu.cn/termux/apt/termux-main stable main` |
| [Root](https://github.com/termux/termux-root-packages)  | `deb https://mirrors.hit.edu.cn/termux/apt/termux-root root stable` |
| [X11](https://github.com/termux/x11-packages)  |`deb http://mirrors.hit.edu.cn/termux/apt/termux-x11 x11 main` |

The mirror is in Harbin,Heilongjiang,China.It runs ngnix and supports both IPv4 and IPv6 as well as both http and https.

**Comment by Grimler91** [comment]
Thank you! We are getting quite a few Chinese mirrors. I think it is time to update pkg to make it possible to cycle through a subset of mirrors (like all the ones in China for example), will try to look at that and add the mirror in the same update
