### ISSUE TITLE
[Bug]: Error while trying to compile Python 3.10.2

### ISSUE THREAD

**Issue by eakteam** [termux/termux-packages#8957]
### Problem description

`rxvt-unicode-9.26.tar.bz2` doesn't exist on Fossies it is replace with `rxvt-unicode-9.30.tar.bz2](https://fossies.org/linux/misc/rxvt-unicode-9.30.tar.bz2/)`

```
curl: (22) The requested URL returned error: 410 Gone
Failed to download https://fossies.org/linux/misc/rxvt-unicode-9.26.tar.bz2
```

I recommend to change it to `http://dist.schmorp.de/rxvt-unicode/Attic/rxvt-unicode-9.26.tar.bz2` if just want to keep the same version.

### What steps will reproduce the bug?

Try to compile Python

### System information

Ubuntu x64

**Comment by eakteam** [comment]
Also another bug after managing to download and compile correct `rxvt-unicode-9.26.tar.bz2`.

It fails at Sqlite with : 

```
/root/.termux-build/libsqlite/src/sqlite3.c:35487:8: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Werror,-Wint-conversion]
  zErr =
       ^
1 error generated.
make: *** [Makefile:537: sqlite3.lo] Error 1
```

**Comment by Grimler91** [comment]
libsqlite builds fine in our docker image based on ubuntu 20.04 or 21.10, consider using the docker image instead of building straight on your machine.

To build python faster you can also do `./build-package.sh -i python`, it then downloads the dependency debs instead of building them from source. It is a lot faster

**Comment by eakteam** [comment]
I am using docker image based on ubuntu 20.04 and also just tried with `-i` option and it fails with : 

```
crypto/comp/c_zlib.c:35:11: fatal error: 'zlib.h' file not found
# include <zlib.h>
          ^~~~~~~~
1 error generated.
make[1]: *** [Makefile:2167: crypto/comp/c_zlib.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/root/.termux-build/openssl/src'
make: *** [Makefile:174: all] Error 2
```

**Comment by eakteam** [comment]
@Grimler91 
The following command are which i run on Ubuntu : 

```
apt update
apt install docker.io git
usermod -aG docker root
systemctl enable docker
systemctl start docker
git clone https://github.com/termux/termux-packages
cd termux-packages
sudo ./scripts/run-docker.sh
sudo ./scripts/setup-android-sdk.sh
sudo ./build-package -a all python or sudo ./build-package -a all -i python
```

In both ways it fails.....

**Comment by Grimler91** [comment]
Instead of 
```
sudo ./scripts/run-docker.sh
sudo ./scripts/setup-android-sdk.sh
sudo ./build-package -a all python or sudo ./build-package -a all -i python
```
you can do just
```
sudo ./scripts/run-docker.sh ./build-package.sh -i -a all python
```

I can't reproduce the zlib error either (tested building for all arches this time). Try without root, delete docker image and start over

**Comment by eakteam** [comment]
It says `ERROR: NDK not pointing at a directory!` if i don't run `sudo ./scripts/setup-android-sdk.sh`

**Comment by Grimler91** [comment]
I just downloaded docker image, and the ndk&sdk is installed as it should to it. If you try to run build-package.sh as root then it will complain that the ndk cannot be found (so don't run as root). ./scripts/setup-android-sdk.sh also should not be run as root
