### ISSUE TITLE
[Bug]: the new visualizer ncmpcpp

### ISSUE THREAD

**Issue by schwyzz** [termux/termux-packages#8965]
### Problem description

After updating the latest, the new visualizer hangs and the program freezes.

### What steps will reproduce the bug?

This happens after a few songs.

### System information

termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
sources.list

deb https://termux.librehat.com/apt/termux-main/ stable main
game-repo (sources.list.d/game.list)

deb https://packages.termux.org/apt/termux-games games stable
science-repo (sources.list.d/science.list)

deb https://packages.termux.org/apt/termux-science science stable
root-repo (sources.list.d/root.list)

deb https://packages.termux.org/apt/termux-root root stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf+ https://github.com/termux/termux-packages/issues/1 SMP PREEMPT Thu Nov 25 02:10:42 CST 2021 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(8)

**Comment by xtkoba** [comment]
What package is this about?

**Comment by wmcbtech30** [comment]
would display size causing this or bad configuration? I get occasional freezes with this program on debian sid as well when bad configuration to mpd/ncmpcpp was set

**Comment by xtkoba** [comment]
Also check the content of commit https://github.com/termux/termux-packages/commit/a085200bf7e2c823b804f7269192e925df4e5417. This is not just a version bump from 0.8.2 to 0.9.2 but some patches are added / modified, including for `config` file, due to deprecation of some variable for configuration.

**Comment by xtkoba** [comment]
I mean we have modified the config file and the modification may contain bugs.
