### ISSUE TITLE
[Bug]: ifconfig and npm not working please help!!!

### ISSUE THREAD

**Issue by Jogulal** [termux/termux-packages#8967]
### Problem description

ifconfig and npm not working please help!!!

### What steps will reproduce the bug?

ifconfig and npm not working please help!!!

### What is the expected behavior?

ifconfig and npm not working please help!!!

### System information

termux-info:

```

```
ifconfig and npm not working please help!!!

**Comment by thunder-coding** [comment]
How will we help if you don't share enough details on:-
1. What problem you faced?
2. Steps to reproduce the problem.
3. What you actually want to happen
