### ISSUE TITLE
[Package]: homebrew

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/termux-packages#8969]
### Package description

The missing package manager for macOS (or Linux)

### Home page URL

https://brew.sh/

### Source code URL

https://github.com/Homebrew/brew

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
How are you envisioning that homebrew can be useful in termux?

**Comment by NoNameMan1231** [comment]
It is install at $HOME instead of /usr

**Comment by wmcbtech30** [comment]
There was an attempt
https://github.com/termux/termux-packages/issues/2071

**Comment by Grimler91** [comment]
Yeah, so just porting homebrew will not make it possible to install those packages, as discussed in https://github.com/termux/termux-packages/issues/2071 and https://github.com/termux/termux-packages/issues/4659. [Android/termux isn't linux](https://wiki.termux.com/wiki/Differences_from_Linux), closing as I don't see how homebrew would be useful
