### ISSUE TITLE
openfoam: Package version 2106-1 will not work with boost 1.78.0

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#8973]
If you are using `openfoam`, please do not update your `boost` to 1.78.0 before `openfoam` version 2106-2 (or later) is prepared.

I am planning to update Boost to version 1.78.0 (#8433). Updating Boost requires reverse dependencies to rebuild, because `DT_SONAME`s for Boost libraries include the version number (e.g. `libboost_system.so.1.78.0`).

The problem is that it takes several hours to build `openfoam`, and that we will not build `boost` and `openfoam` simultaneously. It is expected that the dependency of `openfoam` can be temporarily broken after updating `boost`.

EDIT: Fix typo.

**Comment by Grimler91** [comment]
I have had only 3 (apt) downloads of openfoam from my mirror in the last 30 days, so I don't think a temporary breakage will cause trouble for a lot of people :)

**Comment by xtkoba** [comment]
Now `openfoam` package version 2112 is available, built against `boost` 1.78.0.
