### ISSUE TITLE
[Enhancement] sc-im, optionals features.

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#8982]
### Package description

I think it is a good idea to rebuild sc-im for supporting  yours optionals features. #enhancement                     
- libxls (for xls import support)
- libxlsxwriter  (for xlsx export support) 
- libxml-2.0 and libzip (for xlsx/ods import support)  
- lua (for Lua scripting)

### Source code URL

https://github.com/andmarti1424/sc-im

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Would you like to open a PR to try to enable the features? I am guessing it just needs adding `libxls` and the other dependencies to `TERMUX_PKG_DEPENDS`

**Comment by buribu** [comment]
It would be necessary to look at what is written in the makefile. It may be that just enabling deps is insufficient if the program has to be linked with a library.
