### ISSUE TITLE
sigtimedwait not supported in the Termux headers (supported on devices since api 23)

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#899]
_From @abijahm on March 28, 2017 15:26_

am trying to compile nimlang on android i get an error

undefined reference to sigtimedwait

_Copied from original issue: termux/termux-app#288_

**Comment by fornwall** [comment]
_From @MeinFuehrer on March 28, 2017 22:31_

Were you following these instructions?

http://stisa.space/articles/compile-nim-on-android/

**Comment by fornwall** [comment]
_From @abijahm on March 29, 2017 5:35_

yah i followed the instruction they solve the issue with glob.h  it seems that the function sigtimedwait is not in the signal.h included in termux , could you have the solution to this

**Comment by fornwall** [comment]
_From @MeinFuehrer on March 29, 2017 15:2_

Those instructions are out of sync in two respects, namely, `aarch64` is already a supported target and it's not reveant anyway as we're trying to compile for `armhf`.

Might be a good idea posting a build log in the Nim forum.

**Comment by fornwall** [comment]
`sigtimedwait` is in the unified headers, marked as supported from api level 23.

**Comment by MineFuehrer** [comment]
I believe the issue has already found a satisfactory fix on the Nim side.

**Comment by fornwall** [comment]
@MineFuehrer Great! I'll keep this open issue until sigtimedwait has been fixed.

**Comment by MineFuehrer** [comment]
You mean a different approach from https://github.com/nim-lang/Nim/pull/5646 ?

**Comment by fornwall** [comment]
Right - that workaround should work, but a proper solution here would mean that no workaround is needed! For that the plan is:

1. Wait for NDK r15, which hopefully should have ironed out the issues with unified headers.
2. Switch to providing the unified headers in Termux.

We will then have sigtimedwait (and another couple of missing functions) in the headers and libc.

**Comment by fornwall** [comment]
I'm closing this now, as Termux has switched to the unified headers.

By default the C compiler in Termux targets API level 21, so `sigtimedwait` is not exposed by `signal.h`. By compiling with `-D__ANDROID_API__=23` this function is exposed.
