### ISSUE TITLE
[Package]: flac

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#8994]
### Package description

FLAC is an audio coding format for lossless compression of digital audio, developed by the Xiph.Org Foundation, and is also the name of the free software project producing the FLAC tools, the reference software package that includes a codec implementation

### Home page URL

https://xiph.org/flac/

### Source code URL

https://github.com/xiph/flac

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Already packaged (named `flac`).
