### ISSUE TITLE
[Package]: WasmEdge

### ISSUE THREAD

**Issue by hangedfish** [termux/termux-packages#8997]
### Package description

WasmEdge is a lightweight, high-performance, and extensible WebAssembly runtime for cloud native, edge, and decentralized applications. It powers serverless apps, embedded functions, microservices, smart contracts, and IoT devices.

WasmEdge is a CNCF Sandbox project now.

WasmEdge support Android now.

### Home page URL

https://wasmedge.org/

### Source code URL

https://github.com/WasmEdge/WasmEdge

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

# WasmEdge Runtime
* [Android](https://wasmedge.org/book/en/os/android.html#android)
* [Build from source for Android platforms](https://wasmedge.org/book/en/extend/build_for_android.html#build-from-source-for-android-platforms)

**Comment by truboxl** [comment]
Need more justification as we have node and wasmer already

**Comment by hangedfish** [comment]
> Need more justification as we have node and wasmer already

## Compared with node

WasmEdge is much smaller and faster than node.

Meantime, WasmEdge provides excellent support for JavaScript including ES6 and NPM modules, async networking, the fetch API, React SSR, and even mixing Rust code with JS code.

## Compared with Wasmer

1. WasmEdge supports some non-standard but important extensions. For example, it supports non-blocking network sockets, WasmEdge-bindgen for complex data passing, and Tensorflow / AI inference. Those features could enhance Wasm apps in Android. For example, developers could use WasmEdge to develop AI inference app and networking app on Andriod.
2. Android is frequently used in Edge Computing. WasmEdge is the runtime that provides the best integration with various edge-optimized k8s distributions. See more details here: https://wasmedge.org/book/en/kubernetes.html In fact, WasmEdge is itself an **OCI container** that can be managed by container tools — neither node nor wasmer is a container.
3. Through the AOT compiler, WasmEdge is one of the fastest WebAssembly runtime on market.
4. WasmEdge is written in C++, and hence it is easy to support customized hardware and software drivers on IoT devices.
