### ISSUE TITLE
more resources on cross-compiling

### ISSUE THREAD

**Issue by jaromil** [termux/termux-packages#9]
hi there, I'm the developer of ZShaolin

you may want to include it in the resources section, we have our own build toolchain based on crosstools-ng which may come handy for someone studying the field, plus our own build script

this is just an heads up as a zshaolin user signaled termux. I am studying your system and wouldnt exclude the possibility of joining efforts in the future

happy hacking!

**Comment by jaromil** [comment]
Here is our toolchain, an alternative to the NDK to compile all binaries fully static (including libc) https://files.dyne.org/zshaolin/toolchains/arm-dyne-gcc_64bit-x-arm7a-21jan12.tar.gz

**Comment by fornwall** [comment]
Thanks for the information! Some clarifying questions:

So the linked toolchain is a modified version of crosstools-ng? Are the modifications to the toolchain still available anywhere (is it possible to rebuild the modified toolchain)?

The repository git://code.dyne.org/zshaolin.git then contains patches and scripts to use this toolchain to build different programs and libraries? What is the relationship between that repository and the one at github (https://github.com/dyne/ZShaolin)? Is the github repo only for the Android app itself?

**Comment by jaromil** [comment]
I understand your concerns. First of all: ZShaolin's builds are not easily replicable as the builds and patches are not well automatized, documented and organized enough. I would have been motivated to do more in that direction if for instance more developers would get involved or F-Droid would have included the app, but they didn't as they do not support custom toolchains, so then priorities have changed. This is one of the main reasons I admire your effort on termux, whose builds seem to be well replicable.

The ZShaolin toolchain is produced using crosstools-ng in April 2012, the config file is included. There is no modification applied to crosstools-ng itself.

The git repository contains patches and scripts to use this toolchain (and the NDK in some cases) to build different programs and libraries. Both git repos are the same, we keep a mirror of dyne.org software repos on our own server.

The git repos are for the build scripts and patches and for the Android app. The upstream app sources we use are mirrored on our fileserver and downloaded automatically by the scripts.

**Comment by fornwall** [comment]
Ok, that clears things up!

On a related issue, do you know how to handle licensing of patches and build scripts? Is it a sensible thing to say "all patches and build scripts are under the MIT license"?

Or perhaps "Patches and build script are under the respective licenses of their projects" (so e.g. bash patches are under the same license as bash, and python patches are under the same license as python)?

I would like to avoid having to do manual work for each patched package, if possible.

**Comment by jaromil** [comment]
I think either would work, but with the latter you need to make sure that the project's license is retrievable and somehow included. I'd rather go for the first solution and license all your patches under a license of your choice which is anyway compatible with others, then include that license in the root. (of course IANAL)
