### ISSUE TITLE
termux float crashing

### ISSUE THREAD

**Issue by ottaky** [termux/termux-packages#90]
Just updated termux float via the play store and it crashes on startup. Not sure if this due to a bug in the update as I use the app infrequently (it may have been broken prior to the update)

Nexus 5, Android 6.0, Build MRA58N

Logcat:

    12-12 20:44:38.621   782  1801 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=com.termux.window cmp=com.termux.window/.TermuxFloatActivity bnds=[540,1097][774,1359] (has extras)} from uid 10022 on display 0
    12-12 20:44:38.681   782  1801 I ActivityManager: Start proc 28589:com.termux.window/u0a172 for activity com.termux.window/.TermuxFloatActivity
    12-12 20:44:38.959 28589 28611 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
    12-12 20:44:39.001 28589 28589 D AndroidRuntime: Shutting down VM
    12-12 20:44:39.008 28589 28589 E AndroidRuntime: FATAL EXCEPTION: main
    12-12 20:44:39.008 28589 28589 E AndroidRuntime: Process: com.termux.window, PID: 28589
    12-12 20:44:39.008 28589 28589 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.termux.window.TermuxFloatService: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@4408b87 -- permission denied for this window type
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at android.app.ActivityThread.-wrap4(ActivityThread.java)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime: Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@4408b87 -- permission denied for this window type
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at com.termux.window.TermuxFloatView.launchFloatingWindow(TermuxFloatView.java:140)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at com.termux.window.TermuxFloatService.onCreate(TermuxFloatService.java:72)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
    12-12 20:44:39.008 28589 28589 E AndroidRuntime:        ... 8 more

**Comment by fornwall** [comment]
Thanks, this has been fixed in an update to Termux:Float which has been uploaded to Google Play, and should be available in a few hours max.

It was a compatibility problem with [the new stricter security](http://www.androidpolice.com/2015/09/07/android-m-begins-locking-down-floating-apps-requires-users-to-grant-special-permission-to-draw-on-other-apps/) for floating apps, which forces a user to add a special permission in the system for enabling apps to draw over others.

This was not a problem before since Termux itself was not marked as targeting Android 6, so the system treated the app as a legacy app without applying the new security model to it. Termux however started to target Android 6 in the latest update, which broke the floating add-on.

**Comment by ottaky** [comment]
Thanks @fornwall. Just updated Termux::Float through the app store, granted it permission to draw over other apps and it is now working as intended. Good work!
