### ISSUE TITLE
android 12 termux root@localhost:~# [Process completed (signal 9) - press Enter]

### ISSUE THREAD

**Issue by vipin01234** [termux/termux-packages#9003]
### Problem description

root@localhost:~#
[Process completed (signal 9) - press Enter]
![Screenshot_20220211-151121_Termux](https://user-images.githubusercontent.com/99474113/153569320-fa0899d4-7e3f-4b6d-83a7-074ebcd2b812.jpg)

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
I can't see a termux issue here, and bug report template isn't filled in

**Comment by wmcbtech30** [comment]
@vipin01234 Check
https://github.com/termux/termux-app/issues/2366#issuecomment-955149284
https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8
