### ISSUE TITLE
[Bug]: youtubedr stopped downloading videos from youtube. 

### ISSUE THREAD

**Issue by snooppr** [termux/termux-packages#9004]
### Problem description

`$ youtubedr download "https://youtu.be/TgDlBrcXkEA"`
0.00 b / 0.00 b 0 % [--------------] 0s ] 0.00 b/s

### What steps will reproduce the bug?

The package youtubedr worked fine before.

### System information

v0.118

**Comment by snooppr** [comment]
False alarm problem. everything works on other Termux devices.

**Comment by rachel7l77** [comment]
hi, 
I have the same problem. Do you know how to fix it on the original terminal?

**Comment by snooppr** [comment]
@rachel7l77 hi

This package has been abandoned for a long time and is not supported (developers should cut it out of the repository so as not to confuse users).  Instead of this package, there is a working analogue/package: yt-dlp.

`
wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O ../usr/bin/yt-dlp
chmod a+rx ../usr/bin/yt-dlp
bash
yt-dlp url
`
