### ISSUE TITLE
[Package]: postgresql 14.2

### ISSUE THREAD

**Issue by l1t1** [termux/termux-packages#9005]
### Package description

Object-relational SQL database

### Home page URL

https://www.postgresql.org/

### Source code URL

https://ftp.postgresql.org/pub/source/v14.2/postgresql-14.2.tar.bz2

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
This will be the first package update that requires `libandroid-posix-semaphore` to be added in `TERMUX_PKG_BUILD_DEPENDS`.

Note that if `libandroid-posix-semaphore` is added in `TERMUX_PKG_DEPENDS` (and is linked against), it may make possible to remove `USE_UNNAMED_POSIX_SEMAPHORES=1` from `TERMUX_PKG_EXTRA_CONFIGURE_ARGS`.
