### ISSUE TITLE
[Bug]: install -m 755 /dev/null /usr/local/bin/udevadm dpkg --configure -a

### ISSUE THREAD

**Issue by Anishgamer777** [termux/termux-packages#9009]
### Problem description

Setting up nodejs (17.5.0) ...
CANNOT LINK EXECUTABLE "node": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/node"...
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs
$[

### What steps will reproduce the bug?

Idk

### What is the expected behavior?

Dont now

### System information

termux-info:

```
ADROID 9

```

**Comment by xtkoba** [comment]
Update your `libc++` package.
