### ISSUE TITLE
getresuid() not implemented in Android runtime for Chrome OS

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#901]
_From @qntmpkts on August 27, 2016 22:46_

Since this doesn't seem to happen on non-Termux, reporting here.

When running gist -l username, I get the following error:

```
/data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/gist-4.5.0/lib/gist.rb:462:in `system': Function not implemented - getresuid(2) (Errno::ENOSYS)
    from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/gist-4.5.0/lib/gist.rb:462:in `which'
    from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/gist-4.5.0/lib/gist.rb:523:in `legacy_private_gister?'
    from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/gist-4.5.0/lib/gist.rb:531:in `should_be_public?'
    from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/gist-4.5.0/bin/gist:153:in `<top (required)>'
    from /data/data/com.termux/files/usr/bin/gist:23:in `load'
    from /data/data/com.termux/files/usr/bin/gist:23:in `<main>'
```

![screenshot 2016-08-27 at 17 23 40](https://cloud.githubusercontent.com/assets/19355612/18030414/1e0e232c-6c7b-11e6-8ff2-8316947acd25.png)

_Copied from original issue: termux/termux-app#147_

**Comment by fornwall** [comment]
Initial check to make sure: Run `apt update && apt upgrade` to ensure that you test against the latest package versions. If the problem remains after that:

Could you provide the output of running `dpkg --print-architecture` and `uname -a`? Also, which device and Android version do you run?

This issue may be the same root cause: https://github.com/termux/termux-packages/issues/380

I've tested with a arm-on-android6, aarch64-on-android6 and x86_64-on-android7, and it works for me there, so it may depend on device, arch and/or android version.

**Comment by fornwall** [comment]
@qntmpkts Also, can you test if `ruby -e 'system("echo hi")'` is enough for you to reproduce a problem (that is, if `system()` in ruby does not work on your setup at all)?

**Comment by fornwall** [comment]
_From @qntmpkts on August 28, 2016 16:53_

Preface: running on Chrome OS's Android (ARC) implementation.

This is with the latest ruby, gist, and updates.

dpkg --print-architecture gives:

```
i686
```

uname -a gives

```
Linux localhost 3.14.0 #1 SMP PREEMPT Tue Aug 16 22:06:59 PDT 2016 i686 Android
```

Curiously, ruby -e 'system("echo hi")' gives:

```
-e:1:in `system': Function not implemented - getresuid(2) (Errno::ENOSYS)
    from -e:1:in `<main>'
```

**Comment by fornwall** [comment]
It seems like a bug or missing feature in the android runtime for chrome os. I wonder where to report bugs against that component?

@qntmpkts Can you try compile and run the following C program for a minimal test case?

``` C
#include <stdio.h>
#include <unistd.h>

int main() {
        uid_t ruid, euid, suid;
        if (getresuid(&ruid, &euid, &suid) == 0) {
                printf("ruid=%d, euid=%d, suid=%d\n", ruid, euid, suid);
        } else {
                perror("getresuid");
        }
        return 0;
}
```

**Comment by fornwall** [comment]
_From @qntmpkts on August 28, 2016 19:47_

Yeah, result is as expected:

![screenshot 2016-08-28 at 14 42 28](https://cloud.githubusercontent.com/assets/19355612/18036345/ca854510-6d2d-11e6-8b15-e61547027ec6.png)

For now, I submitted feedback with Ctrl+Alt+i to the devs. There should be another way to submit feedback, but I seem to have misplaced the link. Will ping detail when I find it.

Edit: ARC Version 3215306.

**Comment by fornwall** [comment]
@qntmpkts Thanks, let me know if you find out something, or if a Chrome OS update resolves the issue!

**Comment by fornwall** [comment]
_From @qntmpkts on September 1, 2016 0:23_

Official bug reports may be entered here: https://bugs.chromium.org/p/chromium/issues/list

Latest version of ARC on Dev Channel (ver. 3230769) still does not have getresuid.

**Comment by fornwall** [comment]
Ok, I filed a bug there at https://bugs.chromium.org/p/chromium/issues/detail?id=643119.

**Comment by fornwall** [comment]
@qntmpkts Can you try out a build of ruby where the usage of getresuid() has been disabled:

```
wget http://fornwall.net/ruby_2.3.1-5_i686.deb
apt install ./ruby_2.3.1-5_i686.deb
```

**Comment by fornwall** [comment]
_From @qntmpkts on September 1, 2016 23:27_

The same error occurs in gist using the getresuid-disabled build of ruby.

**Comment by qntmpkts** [comment]
Update:
**ruby -e 'system("echo hi")'** now gives:

> hi

But **gem install gist** now gives:

> ERROR:  While executing gem ... (TypeError)
>     no implicit conversion of nil into String

I thought doing **gem update --system 2.3.1** would solve this, but then I get:

> Updating rubygems-update
> ERROR:  Error installing rubygems-update:
>         Unable to resolve dependency: user requested 'rubygems-update (= 2.3.1)'
> ERROR:  While executing gem ... (NoMethodError)
>     undefined method `version' for nil:NilClass

So I can't install the gems. Do I need a newer ruby install since stable is at 2.4.1 now?

**Comment by qntmpkts** [comment]
After installing a clean new ruby through apt, this issue is now resolved. I don't know when this got patched.

ARC version: 3872362
Platform: 9334.33.0 (Official Build) beta-channel samus
Firmware: Google_Samus.6300.174.0

**Comment by fornwall** [comment]
@qntmpkts Thanks for the information!

For my understanding: Is it working with the default ruby package (where `ruby --version` should say something like `ruby 2.4.1p111`), or on the custom package linked to above?

**Comment by qntmpkts** [comment]
Working with the following: **ruby -v**

> ruby 2.4.1p111 (2017-03-22 revision 58053) [i686-linux-android]

**Comment by fornwall** [comment]
Great, thanks! Closing this issue then.

**Comment by jenningsanderson** [comment]
I'm getting this issue now with `ruby 2.5.1p57 (2018-03-29 revision 63029) [i686-linux-android]` Any suggestions? Anyone else having this issue if they upgrade to the latest Ruby? 

I could try downgrading to ruby 2.4.1p111? @fornwall, what's the best way to install a specific ruby version within Termux? (I'm failing at building from source?)
