### ISSUE TITLE
[Bug]: Issues updating TeXLive

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#9010]
After rsyncing my local repo:

```
rsync --delete -avc REMOTEREPO ~/local/tlrepo/
```

I did

```
tlmgr --repository ~/local/tlrepo update --list
tlmgr --repository ~/local/tlrepo update --self

## ...old suggestion: run this before --all
termux-patch-texlive

tlmgr --repository ~/local/tlrepo update --all
tlmgr: package repository /data/data/com.termux/files/usr/LocalApps/tlrepo (verified)
[  1/328, ??:??/??:??] update: aalok [6k] (59602 -> 61719) ... done
[  2/328, 00:02/12:04:54] update: acmart [39k] (61233 -> 61919) ... done
[  3/328, 00:05/04:05:08] update: acro [43k] (57447 -> 61762) ... done
[...]
[275/328, 14:16/14:26] update: xetex [8k] (61114 -> 61937) ... Can't open perl script "/data/data/com.termux/files/usr/tlpkg/tlpostcode/xetex.pl": No such file or directory
/data/data/com.termux/files/usr/bin/texlive/tlmgr: calling post action script tlpkg/tlpostcode/xetex.pl did not succeed in /data/data/com.termux/files/usr/share/texlive, status 2 at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 1889.
done
[276/328, 14:19/14:29] update: xindex [33k] (60997 -> 61937) ... done
[...]
[327/328, 15:54/15:54] update: collection-publishers [2k] (61397 -> 61731) ... done
[328/328, 15:57/15:57] update: collection-xetex [1k] (59742 -> 61886) ... done
running mktexlsr ...
done running mktexlsr.
running mtxrun --generate ...
done running mtxrun --generate.
Cannot open /data/data/com.termux/files/usr/texmf-dist/web2c/updmap.cfg for writing: No such file or directory at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 3333.
```

Is there some fix to this?

**Comment by Grimler91** [comment]
Have you tried running 
```
termux-patch-texlive
tlmgr update --all
```
again? 

It complains about paths in TLUtils.pm, so [that diff](https://github.com/termux/termux-packages/blob/master/packages/texlive-installer/TLUtils.pm.diff) probably needs to be applied again

**Comment by angelog0** [comment]
@Grimler91, I did that but it say there are not updates.. I have lost the post actions in the previous `tlmgr update --all`... So how can I get that? On macOS and GNU/Linux it runs many `fmtutils...` commands...

**Comment by angelog0** [comment]
It seems that these issues are recurrent; see #5949 (it looks the same to me). 

Maybe you have to fix something to avoid this..

BTW, I get

```
$ $PREFIX/share/texlive/tlpkg/tlpostcode/xetex.pl
bash: /data/data/..../share/texlive/tlpkg/tlpostcode/xetex.pl: Permission denied
```

The `.pl` files there are **all** `rw-------`. Shouldn't they have also the `x` permission?

**Comment by Grimler91** [comment]
> It seems that these issues are recurrent; see #5949 (it looks the same to me).

Yes, looks like the same issue

> Maybe you have to fix something to avoid this..

Not really, upgrading some packages break our texlive until it is patched again. I don't have a fix for that.

> BTW, I get
> 
> ```
> $ $PREFIX/share/texlive/tlpkg/tlpostcode/xetex.pl
> bash: /data/data/..../share/texlive/tlpkg/tlpostcode/xetex.pl: Permission denied
> ```
> 
> The `.pl` files there are **all** `rw-------`. Shouldn't they have also the `x` permission?

Aha, the file also doesn't have a shebang, seems like proper way to run that post installation action is 

```
perl tlpostcode/xetex.pl install $PREFIX/share/texlive/
```

> I have lost the post actions in the previous tlmgr update --all... So how can I get that? 

Reinstalling the individual packages that failed in their post installation scripts would work. That the post actions are "lost" could be considered a bug with tlmgr (apt/dpkg for example stop at errors, while tlmgr report an error but happily considers the package correctly installed afterwards)

> On macOS and GNU/Linux it runs many fmtutils... commands...

`fmtutil-sys --all` after patching texlive should regenerate format files

**Comment by angelog0** [comment]
@Grimler91 
> Reinstalling the individual packages that failed 

I have lost post actions for **ALL** updates (328 packages). As I [flagged](https://github.com/termux/termux-packages/issues/9010#issue-1134196663) (see the output) the post actions stopped just after the packages were installed:

```
[...]
[328/328, 15:57/15:57] update: collection-xetex [1k] (59742 -> 61886) ... done
running mktexlsr ...
done running mktexlsr.
running mtxrun --generate ...
done running mtxrun --generate.
Cannot open /data/data/com.termux/files/usr/texmf-dist/web2c/updmap.cfg for writing: No such file or directory at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 3333.
```

**Comment by Grimler91** [comment]
> I have lost post actions for **ALL** updates (328 packages).

From the output you posted I can only see that post installation action for xetex failed:

> ```
> [275/328, 14:16/14:26] update: xetex [8k] (61114 -> 61937) ... Can't open perl script "/data/data/com.termux/files/usr/tlpkg/tlpostcode/xetex.pl": No such file or directory
/data/data/com.termux/files/usr/bin/texlive/tlmgr: calling post action script tlpkg/tlpostcode/xetex.pl did not succeed in /data/data/com.termux/files/usr/share/texlive, status 2 at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 1889.
done
> ```

The stuff that is suppose to run at the end:

```
running mktexlsr ...
done running mktexlsr.
running mtxrun --generate ...
done running mtxrun --generate.
Cannot open /data/data/com.termux/files/usr/texmf-dist/web2c/updmap.cfg for writing: No such file or directory at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 3333.
```

should be 
```
mktexlsr
mtxrun --generate 
updmap-sys
fmtutil-sys
```

so running those commands after `termux-patch-texlive` should make everything work again
