### ISSUE TITLE
[Package]: Zipalign For arm64 and armv7la

### ISSUE THREAD

**Issue by freindlytech** [termux/termux-packages#9014]
### Package description

Zipalign is android sdk build tools For Optimizing apk files and For Uploading Apps to Play Store the app must be zipaligned , but the zipalign is not available for arm64 and armv7la  and many guys Don't Have Pc , one guy named Lzhiyong provided it for arm64 and armv7la here - https://github.com/Lzhiyong/sdk-tools
But I want this tool updated everytime when google updates it So I request Termux Developers to provide it and keep updating it

### Home page URL

https://android.googlesource.com/platform/build.git/+/refs/tags/android-platform-12.0.0_r4/tools

### Source code URL

https://android.googlesource.com/platform/build.git/+/refs/tags/android-platform-12.0.0_r4/tools/zipalign/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I Don't Have Pc and I don't know how to compile it 😅😅

**Comment by xtkoba** [comment]
Part of `aapt` package.

**Comment by freindlytech** [comment]
Ok
