### ISSUE TITLE
[Package]: add sdkman for termux 

### ISSUE THREAD

**Issue by ExtinctDrift19** [termux/termux-packages#9019]
### Package description

sdkman info package manager 

### Home page URL

https://sdkman.io/

### Source code URL

https://github.com/sdkman/sdkman-cli

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by codespearhead** [comment]
@ExtinctDrift19 Is this issue really completed?

I don't seem to find sdkman on termux repositories and [perhaps that's not even possible to run it on Termux](https://github.com/sdkman/sdkman-cli/issues/840#issuecomment-743170660).

**Comment by Lagunix** [comment]
> @ExtinctDrift19 Is this issue really completed?

Just do it:
pkg install git
pkg install wget
pkg install curl
pkg install kona
pkg install bsdtar
pkg install zip
pkg install unzip
curl -s "https://get.sdkman.io?rcupdate=false" | bash
That's all you need for install sdkman in Termux.

**Comment by wviana** [comment]
Just running the install script don't actually works. 

Here is a thread where we were able to make it work. 

https://github.com/termux/termux-app/discussions/3830#discussioncomment-9992013
