### ISSUE TITLE
scp of a large (>2GB) file fails

### ISSUE THREAD

**Issue by alisdt** [termux/termux-packages#902]
Hi,

When attempting to scp a large file (>2GB) I get

[1]+  Stopped

as if I had suspended it, and then when I type

fg

I get

[1]+  Aborted

I haven't identified the exact threshold of file size -- in the case of this file, splitting it into 100MB chunks seemed to work, and I could scp them successfully.

**Comment by alisdt** [comment]
I should note that

* The ssh connection was successfully established
* An empty file with the correct filename was left on the destination server

**Comment by fornwall** [comment]
Is this on a 32-bit system? What does `uname -a` output?

Perhaps related:
- https://code.google.com/p/android/issues/detail?id=64613
- https://groups.google.com/a/chromium.org/forum/#!topic/net-dev/A6wbkF_AVKU

From the last link above:
```_FILE_OFFSET_BITS is a no-op on Android. on LP32 off_t is always 
32-bit, and you need off64_t for 64-bit offsets. (on LP64, off_t and 
off64_t are both the same type.) 

depending on what API level you're targeting, bionic has most of the 
64-bit functions. so you can use lseek64 with off64_t (on both LP32 
and LP64). we're missing some of the stdio functions, though, because 
BSD's stdio assumed off_t was 64-bit and that's our ABI now. 

because we don't have the full set of functions (and because LP64 is 
happening right now so we have bigger fish to fry) we haven't bothered 
adding _FILE_OFFSET_BITS since it would be kind of a lie anyway. this 
will be kind of sad, though, because it will probably mean use of 
off64_t in LP64 for anyone who wants to be source compatible with LP32 
(but still support 64-bit offsets).```

**Comment by alisdt** [comment]
Ah, I'm so used to 64-bit environments I hadn't thought to check!

$ uname -a
Linux localhost 3.4.0-perf-g8dd021d #1 SMP PREEMPT Thu Mar 2 11:30:20 SGT 2017 armv71 Android

So, it's 32 bit.

**Comment by Wetitpig** [comment]
So the largest file size available would be 2^31 - 1 = 2147483647 bytes

**Comment by LTCNugget** [comment]
@alisdt @fornwall Shouldn't this issue be closed?

**Comment by fornwall** [comment]
@LTCNugget The problem remains, but should be fixed when Termux switches to using unified headers (hopefully when ndk r15 is out), after which scp needs to be rebuilt. So I'm leaving this issue open until this is fixed in scp.

**Comment by fornwall** [comment]
Version `7.5p1-2` of the openssh package, now available as an update, should support 64-bit file sizes also on 32-bit platforms - let me know if there are any problems!

**Comment by smu** [comment]
Should this be fixed?
I got the same error message recently:

```
 $ scp server:~/largefile .
protocol error: size out of range
```

```
$ apt-cache show openssh
Package: openssh
Architecture: i686
Installed-Size: 4028
Maintainer: Fredrik Fornwall @fornwall
Version: 7.9p1
...
```

````
localhost ~/storage/downloads :: $ uname -a
Linux localhost 3.18.0-18126-g0d4ac83af53d #1 SMP PREEMPT Wed Oct 3 23:37:19 PDT 2018 i686 Android
```

**Comment by xeffyr** [comment]
@smu Yeah, on 32bit Termux the issue still **not fixed**.

**Comment by edenist** [comment]
I can confirm also that on an up-to-date 32bit termux [and scp package], this issue is still not fixed. You can use rsync to get around it providing your remote system has rsync installed as well.
