### ISSUE TITLE
Uninstalled libandroid-support

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#903]
I uninstalled libandroid-support accidentally while testing a shell script. How to reinstall it? Thanks!

**Comment by fornwall** [comment]
Does this work?

For arm (check with `uname -m` if you are unsure which arch you are running):

    busybox wget http://termux.net/dists/stable/main/binary-arm/libandroid-support_14_arm.deb
    dpkg -i libandroid-support_14_arm.deb

For aarch64:

    busybox wget http://termux.net/dists/stable/main/binary-aarch64/libandroid-support_14_aarch64.deb
    dpkg -i libandroid-support_14_aarch64.deb
