### ISSUE TITLE
[Wiki]: add `libandroid-posix-semaphore` to "Common porting problems"

### ISSUE THREAD

**Issue by GalaxySnail** [termux/termux-packages#9036]
[This page](https://github.com/termux/termux-packages/wiki/Common-porting-problems) said named semaphores are unimplemented on Android. Now we have [`libandroid-posix-semaphore`](https://github.com/termux/termux-packages/tree/master/packages/libandroid-posix-semaphore), which can be mentioned here.

By the way, it is better to add the link of "Common porting problems" to the ["Termux uses Bionic libc"](https://wiki.termux.com/wiki/Differences_from_Linux#Termux_uses_Bionic_libc) section.

**Comment by wmcbtech30** [comment]
I have mentioned it in https://github.com/termux/termux-packages/wiki/Common-porting-problems/93c8b03b54fc42491edb687bf9877a964409a4f9. let me know if there's something missing with the change

**Comment by GalaxySnail** [comment]
Everything is fine, thanks!
