### ISSUE TITLE
[Bug]: packages.termux.org shut down and cloudflare got 526 errot

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9044]
### Problem description

packages.termux.org is currently down and packages-cf.termux.org has 526 error.
![Screenshot_2022-02-16-21-01-37-748_com termux](https://user-images.githubusercontent.com/99074262/154298574-535d77e5-a458-4a1b-9a22-b7f7022f5ad9.png)
![Screenshot_2022-02-16-21-01-57-012_com termux](https://user-images.githubusercontent.com/99074262/154298589-59800e32-8290-4127-bb36-40fcf9611b53.png)

### What steps will reproduce the bug?

1. termux-change-repo
2. pick main repos
3. select on packages and packages-cf
4. see error

### What is the expected behavior?

packages.termux.org and packages-cf.termux.org is working currently

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.18.31-perf-gf2fd6b0 #1 SMP PREEMPT Wed Jun 5 18:40:35 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 4A

```

**Comment by agnostic-apollo** [comment]
We are testing some stuff. Switch to a different mirror with `termux-change-repo`. https://packages-cf.termux.org may be down for a while if needed.

https://gitter.im/termux/dev?at=620d174a41e3293d65f69c6d
