### ISSUE TITLE
blogc build fails due to source not available

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#905]
The `blogc` package used https://travis-distfiles.rgm.io/blogc/blogc-0.12.0.123-acf1/blogc-0.12.0.123-acf1.tar.xz for downloading the source - this link no longer works.

Also, the project homepage https://blogc.rgm.io/ seems to be down.

@rafaelmartins What is the status here?

**Comment by rafaelmartins** [comment]
Sorry @fornwall this is the result of a bad webserver migration. Everything will be back online tonight and I'll update you here :(

**Comment by rafaelmartins** [comment]
Downloads fixed already, you should be able to build. Website will follow soon.

**Comment by fornwall** [comment]
No problem - great that it works now!

**Comment by arietal** [comment]
termux - building blogc for arch aarch64...                                     Downloading https://travis-distfiles.rgm.io/blogc/blogc-0.12.0.123-acf1/blogc-0.12.0.123-acf1.tar.xz                                                              % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                  Dload  Upload   Total   Spent    Left  Speed     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  curl: (51) SSL: certificate subject name (mallu.rafaelmartins.com) does not match target host name 'travis-distfiles.rgm.io'                                    Download of https://travis-distfiles.rgm.io/blogc/blogc-0.12.0.123-acf1/blogc-0.12.0.123-acf1.tar.xz failed (attempt 1/6)

reopen?

**Comment by rafaelmartins** [comment]
@arietal the package is disabled. I have a new PR to re-enable blogc and version bump it, now with a tarball hosted on github, that should fix all the issues. maybe @fornwall could take a look at it? 

#1903
