### ISSUE TITLE
build-package.sh fails in clean docker image (termux-elf-cleaner missing)

### ISSUE THREAD

**Issue by bchallenor** [termux/termux-packages#906]
With a clean docker image, `/home/builder/.termux-build/_cache/termux-elf-cleaner` does not exist, and `build-package.sh` does not create it. I think this is because `/home/builder/termux-packages/packages/termux-elf-cleaner/termux-elf-cleaner.cpp` is also missing.

I worked around this by cloning `termux-elf-cleaner` manually, and then running `g++ -std=c++11 -Wall -Wextra -pedantic -Os termux-elf-cleaner.cpp -o /home/builder/.termux-build/_cache/termux-elf-cleaner`.

**Comment by fornwall** [comment]
Thanks, fixed!
