### ISSUE TITLE
[Package]: bsdgames

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9060]
### Package description

This is a collection of some of the text-based games and amusements that have been enjoyed for decades on unix systems.

### Home page URL

https://wiki.linuxquestions.org/wiki/BSD_games

### Source code URL

https://github.com/vattam/BSDGames

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
`make: *** No rule to make target '/data/data/com.termux/files/home/BSDGames-master/temp-dictionary', needed by 'boggle/mkdict/dictionary'.  Stop.`
