### ISSUE TITLE
Package request: phantomjs

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#908]
Hello,

It would be nice to have a headless browser: http://phantomjs.org/

**Comment by lopugit** [comment]
Do you mean through npm? Me too :)

**Comment by huangyg11** [comment]
I tried to compile it myself, but don't know where to start.

**Comment by gergelypolonkai** [comment]
This is a hard one as it builds its own Qt version. I started modifying the Qt build scripts, but it’s a real PITA.

**Comment by maddalakum** [comment]
Hi could you please give me the package name phantomjs in termux and how to to install it that would me helpfull

**Comment by maddalakum** [comment]
It showing the below error [
![img_20170908_025935](https://user-images.githubusercontent.com/25227751/30186156-f7ff3316-9441-11e7-9a67-28addedf28a1.jpg)
](url)

**Comment by maddalakum** [comment]
Hi Can any one Solve this Error

**Comment by danielmmf** [comment]
To ai tbm

**Comment by maddalakum** [comment]
I did'nt get it what is ai tbm ??

**Comment by vsdigitall** [comment]
PLEASE include this package in Termux

**Comment by LikeaNachozBR** [comment]
maddalakum , it is in portuguese. "Tou(Estou) aí tbm(também)" means something like "I am also like that" / "I also want to do that"

**Comment by maddalakum** [comment]
Ohh okay :)

**Comment by Rudloff** [comment]
I tried to build phantomjs 2.1.1 but gave up for now because I'm stuck with some QT-specific errors I don't understand.

Here is what I patched so far in case someone wants to take over:
```diff
diff --git a/build.py b/build.py
index bf06752d..e9ec3f0d 100755
--- a/build.py
+++ b/build.py
@@ -263,6 +263,7 @@ class PhantomJSBuilder(object):
             "-no-dbus",
             "-no-opengl",
             "-no-audio-backend",
+            "-no-largefile",
             "-D", "QT_NO_GRAPHICSVIEW",
             "-D", "QT_NO_GRAPHICSEFFECT",
             "-D", "QT_NO_STYLESHEET",
@@ -270,7 +271,11 @@ class PhantomJSBuilder(object):
             "-D", "QT_NO_STYLE_CLEANLOOKS",
             "-D", "QT_NO_STYLE_MOTIF",
             "-D", "QT_NO_STYLE_PLASTIQUE",
-            "-D", "QT_NO_PRINTPREVIEWDIALOG"
+            "-D", "QT_NO_PRINTPREVIEWDIALOG",
+            "-D", "Q_OS_ANDROID",
+            "-D", "_POSIX_THREAD_PRIORITY_SCHEDULING=-1",
+            "-I", "/data/data/com.termux/files/usr/include/libandroid-support",
+            "-l", "android-support"
         ]
         configure.extend(self.platformQtConfigureOptions())
         if self.options.qt_config:
```

**Comment by sdrausty** [comment]
```
[02:24 home ]$ pacman -Ss phantom
community/phantomjs 2.1.1-9
    Headless WebKit with JavaScript API
```
Package seems to be available through https://sdrausty.github.io/TermuxArch/ on device.  

![screenshot_20171123-212948](https://user-images.githubusercontent.com/27742457/33193286-84fae6ea-d095-11e7-9ba3-68fdb81c2774.png)

**Comment by bit-garden** [comment]
So close. I tried the Arch version too. I am getting illegal instruction as an error. From what I'm reading, this has happened to other applications on the Pi due to compiling the wrong arm version instructions. This may be an error with he build script itself.

**Comment by sdrausty** [comment]
@bit-garden correct me if I'm wrong.  You have installed Arch Linux in Termux, but phantomjs produces errors.  Can you post a screenshot?   Are these errors related to `pip install` or running `phantomjs`?

**Comment by bit-garden** [comment]
I don't have my phone at the moment for a screenshot. I did this the way you listed in your screenshot. 
```
pacman -S phantomjs
```
It installed without errors, but when I tried to run it, it simply exited with a message `Illegal instruction`

It seems like a similar issue to this https://github.com/nodejs/node/issues/283 which could be the install script doesn't support the version of arm I'm on(nexus 6, should be armv7) or the script isn't detecting properly. When I get my phone back, I'll try a few things.

**Comment by vishalbiswas** [comment]
@Rudloff what errors? I'm working on Qt but tools are not working.
Did you try to cross compile?

**Comment by Rudloff** [comment]
For now, I only tried running phantomjs' build script from Termux itself.
I got errors about some QT classes missing although they were clearly in the QT source folder and I don't know enough about QT to debug this.

**Comment by maddalakum** [comment]
You might have an idea about kali linux . I have it in my mobile and i downloaded phantomjs standalone package and its working good if im working in that os .  Can any one solve ? [
![screenshot_20180214-110531](https://user-images.githubusercontent.com/25227751/36189215-181b09ec-1177-11e8-906e-217eb65d8233.png)
](url)

**Comment by cherryleafroad** [comment]
I got it working by installing archtermux, downloading the arch binary from [here](https://phantomjs.barnabycolby.io) (the package was removed from archarm, don't know why), and installing the dependencies listed [here](https://aur.archlinux.org/packages/phantomjs/)

**Comment by Hax4us** [comment]
@maddalakum u can't use proot things outside of proot it means you can not run any Kali Linux program from outside so it is not error and should be close :)

**Comment by cyberb** [comment]
Looks like there is a qt build for termux (https://github.com/termux/x11-packages/blob/master/packages/qt5-base/build.sh) so maybe at some point someone can port a build script for phantomjs

**Comment by IamPARANOID** [comment]
> Looks like there is a qt build for termux (https://github.com/termux/x11-packages/blob/master/packages/qt5-base/build.sh) so maybe at some point someone can port a build script for phantomjs

Well, those patches are certainly useful, in getting a little further building this highly defective source.

After applying those patches, reminding the linker that ``-latomic`` does actually exist (contrary to what it would like you to think) in the .pri files, and having to use ``termux-fix-shebang`` to even be able to get the initial errors, I am left with this devastating malfunction:


```
ssl/qsslcertificate_openssl.cpp:63:30: error: member access into incomplete
      type 'X509' (aka 'x509_st')
        return qHashBits(x509->sha1_hash, SHA_DIGEST_LENGTH, seed);
                             ^
/data/data/com.termux/files/usr/include/openssl/ossl_typ.h:120:16: note: 
      forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
ssl/qsslcertificate_openssl.cpp:87:68: error: member access into incomplete
      type 'X509' (aka 'x509_st')
            QByteArray::number(qlonglong(q_ASN1_INTEGER_get(d->x509->...
                                                                   ^
/data/data/com.termux/files/usr/include/openssl/ossl_typ.h:120:16: note: 
      forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
ssl/qsslcertificate_openssl.cpp:96:45: error: member access into incomplete
      type 'X509' (aka 'x509_st')
        ASN1_INTEGER *serialNumber = d->x509->cert_info->serialNumber;
                                            ^
/data/data/com.termux/files/usr/include/openssl/ossl_typ.h:120:16: note: 
      forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
ssl/qsslcertificate_openssl.cpp:232:32: error: member access into incomplete
      type 'X509' (aka 'x509_st')
    X509_PUBKEY *xkey = d->x509->cert_info->key;
                               ^
/data/data/com.termux/files/usr/include/openssl/ossl_typ.h:120:16: note: 
      forward declaration of 'x509_st'
typedef struct x509_st X509;
               ^
ssl/qsslcertificate_openssl.cpp:236:29: error: member access into incomplete
      type 'EVP_PKEY' (aka 'evp_pkey_st')
    if (q_EVP_PKEY_type(pkey->type) == EVP_PKEY_RSA) {
                            ^
/data/data/com.termux/files/usr/include/openssl/ossl_typ.h:93:16: note: 
      forward declaration of 'evp_pkey_st'
typedef struct evp_pkey_st EVP_PKEY;
               ^
ssl/qsslcertificate_openssl.cpp:240:36: error: member access into incomplete
      type 'EVP_PKEY' (aka 'evp_pkey_st')
    } else if (q_EVP_PKEY_type(pkey->type) == EVP_PKEY_DSA) {
                                   ^
/data/data/com.termux/files/usr/include/openssl/ossl_typ.h:93:16: note: 
      forward declaration of 'evp_pkey_st'
typedef struct evp_pkey_st EVP_PKEY;
               ^
ssl/qsslcertificate_openssl.cpp:245:36: error: member access into incomplete
      type 'EVP_PKEY' (aka 'evp_pkey_st')
    } else if (q_EVP_PKEY_type(pkey->type) == EVP_PKEY_EC) {
                                   ^
/data/data/com.termux/files/usr/include/openssl/ossl_typ.h:93:16: note: 
      forward declaration of 'evp_pkey_st'
typedef struct evp_pkey_st EVP_PKEY;
               ^
ssl/qsslcertificate_openssl.cpp:250:36: error: member access into incomplete
      type 'EVP_PKEY' (aka 'evp_pkey_st')
    } else if (q_EVP_PKEY_type(pkey->type) == EVP_PKEY_DH) {
                                   ^
/data/data/com.termux/files/usr/include/openssl/ossl_typ.h:93:16: note: 
      forward declaration of 'evp_pkey_st'
typedef struct evp_pkey_st EVP_PKEY;
               ^
8 errors generated.
make[2]: *** [Makefile:21907: .obj/qsslcertificate_openssl.o] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/phantomjs/src/qt/qtbase/src/network'
```

My research concludes that it is attempting to include a dead, no longer used version of openssl (1.0.0?), which is seemingly not available in the Termux repos.

There is a proposed solution here:
https://stackoverflow.com/questions/35488166/error-compiling-qt5-with-openssl-linked
But as a commenter noted, it does not indeed help.
Unless of course I applied said fix incorrectly, by adding:
``LIBS += -L/data/data/com.termux/files/usr/include/openssl/ -lssl -lcrypto -l`` 
to ``src/qt/qtbase/src/network/ssl/ssl.pri``.

Do you fine people have any suggestions as to how to proceed?

**Comment by IamPARANOID** [comment]
Similar unresolved (and not replyable to) issue:
https://github.com/ariya/phantomjs/issues/15181#issue-270404412

**Comment by droidhackhd** [comment]
pkg install phantomjs not locate

try to download but after extrating

phantomjs-2.1.1-linux-x86_64.tar.bz2

In termux i got files
Names 

ChangeLog    README.md  examples
LICENSE.BSD  bin        third-party.txt


I am trying to run thirparty package with requirement phantomjs still showing same error kindly help 

I am missing something

**Comment by AlvesUeliton** [comment]
1. pkg install Ruby
2. gem update --system
3. gem install phantomjs

**Comment by RossComputerGuy** [comment]
@droidhackhd You shouldnt use x86-64 packages on ARM devices, besides that I don't know what the issue is.

**Comment by IamPARANOID** [comment]
I was able to compile the latest dev version on Termux, after compiling libssl1.0.0s for it, and manually patching several source files.
Some of the patches for qt5 base were very helpful:
https://github.com/termux/x11-packages/tree/master/packages/qt5-base
Also, ``sed`` is your friend.

I could probably upload it as a repo or something if that would help anyone, but I'm not sure how well that works after you have compiled it?

**Comment by sungshon** [comment]
@IamPARANOID

> I could probably upload it as a repo or something if that would help anyone, but I'm not sure how well that works after you have compiled it?

I am interested, it would be great if you would upload it to a repo. I just hit my head on this, as many others have in the last 3+ years and probably many more will in the future.

**Comment by jaruba** [comment]
@IamPARANOID I'm interested too.

**Comment by SwapnilSoni1999** [comment]
So anyone got anything?

**Comment by xloem** [comment]
Here's a list containing many other headless browsers and libraries: https://github.com/dhamaniasad/HeadlessBrowsers adding any one of these would give people a way to port everything that has a headless browser as a dependency.

**Comment by xtkoba** [comment]
Package requests should not be tagged as wontfix by Stale bot.

**Comment by jimmywarting** [comment]
PhantomJS is pretty much dead now.
It's a old headless browser that no real user have ever used and was solo created for developers to automate & scrape stuff.
it don't get any more updates and are now archived/suspended for a long time now

ppl should just stop using it and switch to something like puppeteer instead.

**Comment by xtkoba** [comment]
In x11-packages due to dependency on `qt5-*`. Thanks.
