### ISSUE TITLE
Bug run npm start / node . / pkg install npm

### ISSUE THREAD

**Issue by MRR004** [termux/termux-packages#9087]
CANNOT LINK EXECUTABLE "node": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/node"...

Bug on android 11

**Comment by xtkoba** [comment]
Update your `libc++` package.

**Comment by MRR004** [comment]
How to do it?

**Comment by sk0kanik** [comment]
> How to do it?

``pkg upgrade``

**Comment by MRR004** [comment]
![Screenshot_2022-02-22-18-05-54-172_com termux](https://user-images.githubusercontent.com/99880352/155120119-433fc723-791f-4bf0-9bbc-f04562ec4fd4.jpg)

Solution?

**Comment by Maxython** [comment]
Reinstall termux system.  To do this, run this command `rm -fr $PREFIX`, then close termux completely and open it again.

**Comment by thunder-coding** [comment]
> Reinstall termux system. To do this, run this command `rm -fr $PREFIX`, then close termux completely and open it again.

Also you are using legacy version of Termux from Play Store, consider moving to F-Droid

**Comment by MRR004** [comment]
$ pkg install nodejs
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  c-ares libicu
Suggested packages:
  clang make pkg-config python
The following NEW packages will be installed:
  c-ares libicu nodejs
0 upgraded, 3 newly installed, 0 to remove and 46 not upgraded.
Need to get 17.3 MB of archives.
After this operation, 87.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://packages.termux.org/apt/termux-main stable/main aarch64 c-ares aarch64 1.18.1 [118 kB]
Get:2 https://packages.termux.org/apt/termux-main stable/main aarch64 libicu aarch64 70.1 [9272 kB]
Get:3 https://packages.termux.org/apt/termux-main stable/main aarch64 nodejs aarch64 17.5.0 [7942 kB]
Fetched 17.3 MB in 10s (1688 kB/s)
Selecting previously unselected package c-ares.
(Reading database ... 3457 files and directories currently installed.)
Preparing to unpack .../c-ares_1.18.1_aarch64.deb ...
Unpacking c-ares (1.18.1) ...
Selecting previously unselected package libicu.
Preparing to unpack .../libicu_70.1_aarch64.deb ...
Unpacking libicu (70.1) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_17.5.0_aarch64.deb ...
Unpacking nodejs (17.5.0) ...
Setting up libicu (70.1) ...
Setting up c-ares (1.18.1) ...
Setting up nodejs (17.5.0) ...
CANNOT LINK EXECUTABLE "node": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/node"...
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
$

**Comment by MRR004** [comment]
![Uploading Screenshot_2022-02-23-12-21-02-269_com.termux.jpg…]()

**Comment by MRR004** [comment]
![Screenshot_2022-02-23-12-21-02-269_com termux](https://user-images.githubusercontent.com/99880352/155265649-f3acbd68-a198-429b-8b89-fafed1bb36cc.jpg)

**Comment by sk0kanik** [comment]
>The following NEW packages will be installed: c-ares libicu nodejs 0 upgraded, 3 newly installed, 0 to remove and 46 not upgraded. 

46 not upgraded? Termux team will not fix issues caused by those old packages. run ``pkg up`` to upgrade them.

**Comment by MRR004** [comment]
> > The following NEW packages will be installed: c-ares libicu nodejs 0 upgraded, 3 newly installed, 0 to remove and 46 not upgraded.
> 
> 46 not upgraded? Termux team will not fix issues caused by those old packages. run `pkg up` to upgrade them.

============================================

$ pkg up
Checking availability of current mirror: ok
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Hit:1 https://packages.termux.org/apt/termux-main stable InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  502  Bad Gateway
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  502  Bad Gateway
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

**Comment by thunder-coding** [comment]
See #6726. We are not going to support Play Store users of Termux for it's outdated
