### ISSUE TITLE
[Bug]: Legacy Environment (unmaintained pkg) 

### ISSUE THREAD

**Issue by Vicaries** [termux/termux-packages#9090]
### Problem description

I can't update packages of install new ones

### What steps will reproduce the bug?

Everytime I try to install a new package

### What is the expected behavior?

![2022_02_20_11_01_59](https://user-images.githubusercontent.com/100097910/154866560-c3e88ff3-16e5-4543-82bf-7187cceeb0a6.jpg)
Unmaintained packages and failure to receive updates 

### System information

termux-info:

```

```

**Comment by wmcbtech30** [comment]
If bintray repo source package installation is the problem. try replacing it with new ones and run `apt update`:

```bash
echo "deb https://termux.org/science-packages-21-bin science stable" > $PREFIX/etc/apt/sources.list.d/science.list
echo "deb https://termux.org/game-packages-21-bin games stable" > $PREFIX/etc/apt/sources.list.d/game.list
apt update
```

**Comment by Herzogs** [comment]
check this [link](https://github.com/termux/termux-packages/issues/4467) which says that Android 5 and 6 packages will no longer be updated.
