### ISSUE TITLE
[Package]: some java code launcher

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#9093]
### Package description

Java code/package launcher.

### Source code URL

*

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Now Java code is launched like this
```
#!/data/data/com.termux/files/usr/bin/sh
export CLASSPATH=$(pm path com.termux.termuxam|cut -d: -f2)
unset LD_LIBRARY_PATH LD_PRELOAD
exec /system/bin/app_process / com.termux.termuxam.Am "$@"
```

It works, but if apk has native code sometimes it fails to be launched with error `No implementation found for ...` (https://github.com/termux/termux-x11/issues/56). 
Idea is simple:
1. When there are native libraries in apk launcher should unpack/copy them to special folder in `$PREFIX/libexec/$package_name...`. If those libraries exist it should replace them (only if apk file is newer then libraries).
2. After initializing it's base it should create [BaseDexClassLoader](https://cs.android.com/android/platform/superproject/+/master:libcore/dalvik/src/main/java/dalvik/system/BaseDexClassLoader.java;drc=bc983130d9c2bce47758ee7a2e581b9b011c4856;l=150) instance (maybe using reflection, I am not sure it is a part of Android SDK). It will let us specify native library path for our launcher.
3. Finally launch specified entry point function.

This way it should keep ABI and let us mix native code with Java.

**Comment by OMDBC** [comment]
Eow

**Comment by twaik** [comment]
@OMDBC And?
