### ISSUE TITLE
Weird behaviour on tct output (issue clone)

### ISSUE THREAD

**Issue by H4ck3r404** [termux/termux-packages#9097]
https://github.com/mpv-player/mpv/issues/9894

**Comment by Grimler91** [comment]
As already said in the [linked issue](https://github.com/mpv-player/mpv/issues/9894#issuecomment-1046663740) you haven't provided any information so not sure what you want us to do here. 

Fill in the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=bug+report&template=01-bug-report.yml&title=%5BBug%5D%3A+).

**Comment by H4ck3r404** [comment]
Nevermind - dark mode rom issue.
