### ISSUE TITLE
Package request: headless chromium

### ISSUE THREAD

**Issue by jackbrycesmith** [termux/termux-packages#910]
I believe building this package would provide at least the same benefits as requested in #908, probably usurping it in the long run.

**Comment by marksteward** [comment]
I'm for this too. It's possible to use chromium-browser in ubuntu with proot, but native chrome would be ideal.

The .apk is usually accessible in /system/app/Chrome - I wonder if it would be possible to create an intent that just starts headless on a fixed port.

**Comment by christianrondeau** [comment]
Looks like chromedriver itself exists and is supported: http://chromedriver.chromium.org/getting-started/getting-started---android

**Comment by SwapnilSoni1999** [comment]
So anyone found anything?

**Comment by amitkhare** [comment]
Anyone came up with any solution?

**Comment by yubrajbhoi** [comment]
https://github.com/rishabhrpg/puppeteer-on-termux
Not really a complete solution because it requires an Alpine VM under proot.
Anyone here managed to compile any browser engine (like webkit) in Termux?

**Comment by SunPodder** [comment]
Available in [TUR](https://github.com/termux-user-repository/tur)

@xtkoba completed
