### ISSUE TITLE
[Package]:  melonjs

### ISSUE THREAD

**Issue by rBok6** [termux/termux-packages#9104]
### Package description

melonJS 2 is a modern version of the melonJS game engine. It has been rebuilt almost entirely using ES6 class, inheritance and semantic, and is bundled using Rollup to provide modern features such as transpiling and tree-shaking.

### Source code URL

https://github.com/melonjs/melonJS

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
```
$ npm install melonjs
```

**Comment by rBok6** [comment]
> ```
> $ npm install melonjs
> ```

Yeah, I tried that after pkg install didn't find the package. I also checked for installed packages and I can't see melonjs anywhere. Since npm install seemed to work, where did the package get installed?

**Comment by wmcbtech30** [comment]
without specifying `-g` flag in `npm` it would have been placed somewhere in `node_modules` directory, to populate it on `PREFIX` which install some files somewhere in `$PREFIX` allowing to be recognized easily, use `npm install melonjs -g` to globally install it on `PREFIX`
