### ISSUE TITLE
[Package]: yt-dlp-ffmpeg

### ISSUE THREAD

**Issue by asdfugil** [termux/termux-packages#9115]
### Package description

ffmpeg for yt-dlp. Some sites provides media that is broken in some ways and a special ffmpeg is needed.

This should NOT replace the normal ffmpeg.

### Home page URL

https://github.com/yt-dlp/FFmpeg-Builds

### Source code URL

https://github.com/yt-dlp/FFmpeg-Builds

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
It seems sufficient to backport the following commit:

https://github.com/FFmpeg/FFmpeg/commit/68595b46cb374658432fff998e82e5ff434557ac

**Comment by asdfugil** [comment]
I suppose so since this is the error I have
```
[webm @ 0x77b9266a00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 12140 >= 9226
av_interleaved_write_frame(): Invalid argument
```
