### ISSUE TITLE
[Package]: Kotlin/Native, harbour, cabal-install, podman, libbthread, openj9, cockroachDB, arnagoDB, darling, Chatel, juila, tinygo, notcurses, keydb, ravendb, gnuprolog

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9119]
please add Kotlin/Native, harbour, cabal-install, podman, libbthread, openj9, cockroachDB, arnagoDB, darling, chapel, juila, tinygo, notcurses, keydb, ravendb, gnuprolog packages.

**Comment by bidyut1153** [comment]
please add Kotlin/Native, harbour, cabal-install, podman, libbthread, openj9, cockroachDB, arnagoDB, darling, chapel, juila, tinygo, notcurses, keydb, ravendb, gnuprolog packages including haxe, pueue, btop, bottom, and box86 and box64

**Comment by wmcbtech30** [comment]
Please post your package request issue in an appropriate manner

**Comment by Grimler91** [comment]
And use search to check for already existing package requests, several of those are duplicates..

**Comment by Grimler91** [comment]
@bidyut1153 use search and stop wasting our time.

* harbour has already been requested: https://github.com/termux/termux-packages/issues/8921
* podman has already been requested: https://github.com/termux/termux-root-packages/issues/126
* libbthread has already been requested: https://github.com/termux/termux-packages/issues/8871
* openj9 has already been requested: https://github.com/termux/termux-packages/issues/8869
* cockroachdb has already been requested; https://github.com/termux/termux-packages/issues/8863
* darling has already been requested: https://github.com/termux/termux-packages/issues/8835
* chapel has already been requested: https://github.com/termux/termux-packages/issues/8824
* juila (typo of julia I suppose) has already been requested: https://github.com/termux/termux-packages/issues/58
* tinygo has already been requested: https://github.com/termux/termux-packages/issues/8819
* notcurses has already been requested: https://github.com/termux/termux-packages/issues/8860
* keydb has already been requested: https://github.com/termux/termux-packages/issues/8793
* ravendb has already been requested: https://github.com/termux/termux-packages/issues/8785
* gnuprolog has already been requested: https://github.com/termux/termux-packages/issues/8781
* haxe has already been requested: https://github.com/termux/termux-packages/issues/8617
* pueue has already been requested: https://github.com/termux/termux-packages/issues/8599
* btop has already been requested: https://github.com/termux/termux-packages/issues/8566
* bottom has already been requested: https://github.com/termux/termux-packages/issues/8565
* box86 has already been requested: https://github.com/termux/termux-packages/issues/7672
* box64 has already been requested: https://github.com/termux/termux-packages/issues/7672
