### ISSUE TITLE
mktextfm fails because mktexdir is not found

### ISSUE THREAD

**Issue by ysalmon** [termux/termux-packages#913]
Hi,
when compiling a document with XeLaTeX, I encounter the above described problem. Indeed, the texlive package in termux does not seem to include mktexdir, and there does not seems to be a package within texlive to install it, as it is a base component.

**Comment by Grimler91** [comment]
Hi @ysalmon, glad to hear that you use texlive in termux. I haven't encountered this error but I'm able to reproduce it. 

Seems to be a shebang issue. Please run 
    
    termux-fix-shebang $PREFIX/opt/texlive/2016/texmf-dist/web2c/mktex{nam,dir}

and see if this solves the problem. In that case i can add a patch to the installation script.

**Comment by ysalmon** [comment]
That fixed it ; thanks a lot. And thanks to everybody for including texlive in termux ! It works very well.

**Comment by fornwall** [comment]
Thanks to @Grimler91 this and other issues are now resolved in the updated `20160523b-2` version of the texlive package now available in the apt repository.
