### ISSUE TITLE
[Bug]: main repo packages.termux.org is down

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#9133]
### Problem description

Starting earlier this morning there is some issue with our fosshost host. If you are subscribed to the main repository, then trying to `pkg install` or `pkg upgrade` gives an error looking something like

```
pkg install termux-tools
Ign:2 https://packages.termux.org/apt/termux-main stable InRelease
Ign:3 https://packages.termux.org/apt/termux-root root InRelease
Ign:4 https://packages.termux.org/apt/termux-x11 x11 InRelease
Ign:2 https://packages.termux.org/apt/termux-main stable InRelease
Ign:3 https://packages.termux.org/apt/termux-root root InRelease
Ign:4 https://packages.termux.org/apt/termux-x11 x11 InRelease
Ign:2 https://packages.termux.org/apt/termux-main stable InRelease
Ign:3 https://packages.termux.org/apt/termux-root root InRelease
Ign:4 https://packages.termux.org/apt/termux-x11 x11 InRelease
Err:2 https://packages.termux.org/apt/termux-main stable InRelease
  Could not handshake: The TLS connection was non-properly terminated. [IP: 5.102.168.157 443]
Err:3 https://packages.termux.org/apt/termux-root root InRelease
  Could not handshake: The TLS connection was non-properly terminated. [IP: 5.102.168.157 443]
Err:4 https://packages.termux.org/apt/termux-x11 x11 InRelease
  Could not handshake: The TLS connection was non-properly terminated. [IP: 5.102.168.157 443]
Reading package lists... Done                        
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://packages.termux.org/apt/termux-main/dists/stable/InRelease  Could not handshake: The TLS connection was non-properly terminated. [IP: 5.102.168.157 443]
W: Failed to fetch https://packages.termux.org/apt/termux-root/dists/root/InRelease  Could not handshake: The TLS connection was non-properly terminated. [IP: 5.102.168.157 443]
W: Failed to fetch https://packages.termux.org/apt/termux-x11/dists/x11/InRelease  Could not handshake: The TLS connection was non-properly terminated. [IP: 5.102.168.157 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

To be able to update/install anything before this is fixed you need to switch to another mirror, run `termux-change-repo` and switch all repos over to another mirror (not main one or the cloudforge one).

If you are subscribed to the (obsolete and empty) repositories unstable-repo, science-repo or game-repo you might need to uninstall them also with `apt remove unstable-repo science-repo game-repo`

## Walkthrough on to change to working mirror with `termux-change-repo`

1. Select one or more repositories for which you want to change mirror by tapping "space" and navigating over list by up/down arrow keys. Tap enter to confirm the choice.

![change-repo1](https://user-images.githubusercontent.com/18900601/155493129-513cbc55-cbe7-4452-86bb-c45af9544722.png)

2. Pick a mirror, it is recommended to begin with mirror hosted by Grimler. Same as previously, navigate over list by arrow keys, pick mirror by space key and confirm choice by pressing "enter".

![change-repo2](https://user-images.githubusercontent.com/18900601/155493177-4557157a-58af-4b83-bbee-dfd47187cd2c.png)

### What steps will reproduce the bug?

Trying to use pkg/apt while subscribed to the main repo

### What is the expected behavior?

pkg/apt should successfully access the repo

### System information

Happens for all devices that are subscribed to the main repo.

**Comment by buttaface** [comment]
Thanks for the update, I appear to have hit this with my Swift CI. Who is in touch with Fosshost? Did we hit our bandwidth quota?

**Comment by Grimler91** [comment]
I've opened a support ticket with them now. There's some issue with the machine, I managed to log in before and saw lots of messages like
```
Message from syslogd@termux at Feb 24 08:32:50 ...
 kernel:[3447416.295267] watchdog: BUG: soft lockup - CPU#11 stuck for 35s! [swapper/11:0]
```
After trying to restart and force-reset the machine it became completely unresponsive

**Comment by agnostic-apollo** [comment]
@buttface you should really join our termux_dev gitter/matrix channel.

https://gitter.im/termux/dev

https://matrix.to/#/#termux_dev:gitter.im

**Comment by xtkoba** [comment]
@Gucci12-cpu Sorry for your inconvenience. We are working on it. You can follow the instructions as described in the description to temporarily work it around.

**Comment by Gucci12-cpu** [comment]
Muchas gracias por responder a mi inquietud. Alguien que me guíe para configurar correctamente la app?

**Comment by Grimler91** [comment]
@Gucci12-cpu see Walkthrough in first post

**Comment by Grimler91** [comment]
Fosshost is up again.

**Comment by xtkoba** [comment]
Seems to be happening now again. (Not sure if appropriate to reopen.)

**Comment by Grimler91** [comment]
Hm, someone has messed with some settings. repos are accessable through https://packages-cf.termux.org/, but not packages.termux.org

**Comment by Grimler91** [comment]
Will check with fosshost why it was modified before restoring

**Comment by Grimler91** [comment]
Restored by fosshost staff.

**Comment by DUOLabs333** [comment]
This is happening again.

**Comment by theotheroracle** [comment]
currently experiencing this
```
W: Failed to fetch https://packages-cf.termux.org/apt/termux-main/dists/stable/InRelease  Something wicked happened resolving 'packages-cf.termux.org:https' (7 - No address associated with hostname)
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
