### ISSUE TITLE
Python opencv error

### ISSUE THREAD

**Issue by zhangshengsheng** [termux/termux-packages#9134]
### Problem description

pkg install opencv
ModuleNotFoundError: No module named 'cv2'

https://wiki.termux.com/wiki/Python
ModuleNotFoundError: No module named 'cv2'

https://github.com/termux/termux-packages
ModuleNotFoundError: No module named 'cv2'

#1992 
None of them help me

### What steps will reproduce the bug?

。

### System information

termux-info:

```

```

**Comment by xtkoba** [comment]
I have reopened #1992. Please migrate there.
