### ISSUE TITLE
Can you please upload packages to grimler.se instead of packages.termux.org?

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9138]
If `yes`, then you upload packages to `grimler.se`

**Comment by ravener** [comment]
grimler.se is paused pending the OpenSSL updates I believe, see #9050

**Comment by Grimler91** [comment]
> If `yes`, then you upload packages to `grimler.se`

We can, but why? All/most mirrors are configured to mirror packages.termux.org, so changing main host would be a hazzle for everyone. If we get any indication that the outage will last a long time, then we can look at changing to another main host

> grimler.se is paused pending the OpenSSL updates I believe, see #9050

It's not paused yet, but will be for a while once that PR is merged
