### ISSUE TITLE
[Package]: podman

### ISSUE THREAD

**Issue by codebam** [termux/termux-packages#9141]
### Package description

Podman (the POD MANager) is a tool for managing containers and images, volumes mounted into those containers, and pods made from groups of containers. Podman is based on libpod, a library for container lifecycle management that is also contained in this repository. The libpod library provides APIs for managing containers, pods, container images, and volumes.

---

Adding this to Termux would allow users to easily run

`podman run -it -v /sdcard:/mnt:z archlinux /bin/bash`

to start any OCI container with sdcard mounted at `/mnt` (or wherever you want to mount it)

This could even be used to bootstrap Termux instead of maintaining packages cross compiled with the ndk

### Home page URL

https://podman.io/

### Source code URL

https://github.com/containers/podman

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by buribu** [comment]
#8909
