### ISSUE TITLE
Problema con codigos!

### ISSUE THREAD

**Issue by Gucci12-cpu** [termux/termux-packages#9142]
### Problem description

Quien me puede regalar los comando para configurar termux es que los que siempre utilizo no me funcionan. O me informa como puedo solucionar el problema.

### What steps will reproduce the bug?

.

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
You haven't filled in the bug report template, and I no one on the termux team speaks spanish as far as I know

**Comment by SDRausty** [comment]
use the reverse translation function

write short sentences

tap the double arrow until the translations match

please

usar la función de traducción inversa

escribe oraciones cortas

toque la doble flecha hasta que las traducciones coincidan

por favor

ref https://translate.google.com/

**Comment by SDRausty** [comment]
```diff
+please

+use the reverse translation function

+write short sentences

+tap the double arrow until the translations match

+reference https://translate.google.com/

-por favor

-usar la función de traducción inversa

-escribe oraciones cortas

-toque la doble flecha hasta que las traducciones coincidan

-referencia https://translate.google.com/
```

**Comment by Zurki23** [comment]
![Screenshot_20220501-133951_Termux.jpg](https://user-images.githubusercontent.com/88460297/166144281-a14ccf0b-8ed5-4223-b0bd-1e48649019fd.jpg)
