### ISSUE TITLE
[Bug]: Issues with org.jansi:jansi, load library error

### ISSUE THREAD

**Issue by KKD4yv1d** [termux/termux-packages#9146]
### Problem description

When i make a jar with maven, the maven output works perfectly with org.jansi, but my jar have org.jansi library and give me an error saying:
```console
$ java -jar target/Solymus-1.0-SNAPSHOT.jar
/data/data/com.termux/files/usr/tmp/jansi-2.4.0-307bf3dd386c2858-libjansi.so.lck (No such file or directory)
[12:30:35] [INFO]: This need have ANSI!
```

and the output doesn't have any color

### What steps will reproduce the bug?

1. Compile a jar with maven that have org.jansi library
2. Try to execute it and saw if output has colors

### What is the expected behavior?

The output have colors

### System information

termux-info:

```
uname -a: Linux localhost 4.4.177-22602103 #1 SMP PREEMPT Tue Jan 18 22:28:08 KST 2022 aarch64 Android
Termux Version: 0.118
Android Version: Android 11
Phone: Samsung Galaxy a30
maven --version:
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /data/data/com.termux/files/usr/opt/maven
Java version: 17-internal, vendor: N/A, runtime: /data/data/com.termux/files/usr/opt/openjdk
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.4.177-22602103", arch: "aarch64", family: "unix"
```

**Comment by xtkoba** [comment]
You may need to add an option such as

```
-Dlibrary.jansi.path="$PREFIX/lib
```

so that JVM can find `libjansi.so`.

**Comment by KKD4yv1d** [comment]
Now it's giving another error
```console
$ java -jar target/Solymus-1.0-SNAPSHOT.jar -Dlibrary.jansi.path="$PREFIX/lib"
Failed to load native library:jansi-2.4.0-bab4688fdcda54d6-libjansi.so. osinfo: Linux/arm64
java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/tmp/jansi-2.4.0-bab4688fdcda54d6-libjansi.so: dlopen failed: library "libc.so.6" not found: needed by /data/data/com.termux/files/usr/tmp/jansi-2.4.0-bab4688fdcda54d6-libjansi.so in namespace (default)
[04:42:06] [INFO]: This need have ANSI!
```
I used `apt-get install libc*` and tried again, but that doesn't worked

**Comment by xtkoba** [comment]
The root cause should be the same as #8439, that is, jansi tries to load a bundled native library which is built for GNU/Linux, incompatible with Android.

We need to somehow tell jansi to load the appropriate native library that comes from our `libjansi` package.

According to <a href="https://github.com/fusesource/jansi/tree/jansi-2.4.0/src/main/java/org/fusesource/jansi/internal/JansiLoader.java">the source</a>, it should be sufficient to use the system property `library.jansi.path`. Also `java.library.path` is used as a last resort.

I have no idea why this does not work if it really does not. Could you post the `strace -f` output of the command?

**Comment by KKD4yv1d** [comment]
> The root cause should be the same as #8439, that is, jansi tries to load a bundled native library which is built for GNU/Linux, incompatible with Android.
> 
> We need to somehow tell jansi to load the appropriate native library that comes from our `libjansi` package.
> 
> According to [the source](https://github.com/fusesource/jansi/tree/jansi-2.4.0/src/main/java/org/fusesource/jansi/internal/JansiLoader.java), it should be sufficient to use the system property `library.jansi.path`. Also `java.library.path` is used as a last resort.
> 
> I have no idea why this does not work if it really does not. Could you post the `strace -f` output of the command?

Here is the `strace -f` output
[`strace -f` output](https://paste.gg/p/anonymous/e82521b0d86d438d8f08d2e99b1fbfd5)
I uploaded on paste.gg because its a big output, more than 1MB of text

**Comment by xtkoba** [comment]
From strace log:

```
[pid  9343] newfstatat(AT_FDCWD, "/data/data/com.termux/files/home/.local/lib/libjansi.so", 0x78306828c8, 0) = -1 ENOENT (No such file or directory)
```

So a workaround might be to

```bash
ln -s $PREFIX/lib/libjansi.so /data/data/com.termux/files/home/.local/lib/libjansi.so
```

**Comment by KKD4yv1d** [comment]
Oh, this is weird, the output has colors now, but this error continues appearing:
```console
$ java -jar target/Solymus-1.0-SNAPSHOT.jar
Failed to load native library:jansi-2.4.0-63e24096043023fc-libjansi.so. osinfo: Linux/arm64
java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/tmp/jansi-2.4.0-63e24096043023fc-libjansi.so: dlopen failed: library "libc.so.6" not found: needed by /data/data/com.termux/files/usr/tmp/jansi-2.4.0-63e24096043023fc-libjansi.so in namespace (default)
```

**Comment by xtkoba** [comment]
Then you can safely ignore that error.

**Comment by KKD4yv1d** [comment]
Okay, i will close this issue, thanks for the fast responses

**Comment by pikriawan** [comment]
Install libjansi.
```bash
pkg install libjansi
```
Then run with an option
```bash
-Dlibrary.jansi.path="$PREFIX/lib/libjansi"
```
