### ISSUE TITLE
[Package]: Update command-not-found

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9147]
### Package description

Suggest installation of packages in interactive shell sessions

### Home page URL

https://github.com/termux/command-not-found

### Source code URL

https://github.com/termux/command-not-found

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Please update command-not-found to 1.74

**Comment by Grimler91** [comment]
Any particular reason it should be updated?
Feel free to open a PR to update it. Otherwise it will be done when I have some time to spend on it.

**Comment by SDRausty** [comment]
>when I have some time 

Can updating be automated via workflows?
