### ISSUE TITLE
[Package]: tldr-pages

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9148]
### Package description

The tldr-pages project is a collection of community-maintained help pages for command-line tools

### Source code URL

https://github.com/tldr-pages/tldr

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Looks to me like tldr-pages is installable through npm and/or pip. Any reason that does not work?

As per the package policy we do generally not package stuff that can be installed through another package manager
