### ISSUE TITLE
[Package]: terminalizer

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9150]
### Package description

Record your terminal and generate animated gif images

### Home page URL

https://terminalizer.com/

### Source code URL

https://github.com/faressoft/terminalizer

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Looks like it is installable through npm. Any particular reason you can't install it through npm?

Note that the packaging policy, which you have read, says

> Not installable through cpan, gem, npm, or pip
>
> These packages should be installable through `cpan`, `gem`, `npm`, `pip` and so on.
