### ISSUE TITLE
Nmap libssl issue 

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#9155]
### Problem description

CANNOT LINK EXECUTABLE "nmap": library "libssl.so.1.1" not found: needed by main executable

### What steps will reproduce the bug?

type nmap

### System information

Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/termuxblack.list
deb https://hax4us.github.io/TermuxBlack/ termuxblack main
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.113-22384011 #1 SMP PREEMPT Tue Dec 7 15:09:17 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-M315F

**Comment by thunder-coding** [comment]
See #9050. Wait for OpenSSL 3 rebuilds to complete
