### ISSUE TITLE
Package request: micro

### ISSUE THREAD

**Issue by sarimak** [termux/termux-packages#916]
There is a great text editor with user experience very similar to Github Atom which is already fully working in Termux - including scroll by finger and select by shift + arrow, https://github.com/zyedidia/micro . It's a Go program and can be compiled just by running make. Could it be packaged, please? For users not comfortable with vim there is not a good programming editor available via Termux repo yet.

**Comment by fornwall** [comment]
Thanks - a `micro` package is now available, install it with:

    packages install micro

**Comment by sarimak** [comment]
Thank you! Installed via apt, works like a charm. Maybe a screenshot of micro with syntax-highlighted code in split-screen could be added to the animated gif on Termux home to demonstrate how capable Termux already is.
