### ISSUE TITLE
Vim hangs when stopping using Ctrl+Z

### ISSUE THREAD

**Issue by arfanamd** [termux/termux-packages#9162]
## Problem description

Vim hangs when stopping using ctrl+z.

## What steps will reproduce the bug?

1. Open vim
2. Press ctrl+z

## What is the expected behavior?

Vim should stop without hanging.

## System information

```
Application version: 
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Android version:
7.1.2
Device manufacturer:
Xiaomi
Device model:
Redmi 3
```
## Vim version

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 23 2022 13:24:48)
Included patches: 1-4450
```

**Comment by xtkoba** [comment]
Can confirm.

Interestingly, this does not happen when `vim` is invoked under `strace`.

**Comment by SDRausty** [comment]
multiple `fg`s + `CTRL z`s seem to work to restore sessions

**Comment by Leif-W** [comment]
The recently landed (within past 1+ hours) vim update seems to open a sub-shell rather than suspend to existing shell, requiring logout of subshell, rather than `fg`, to return to vim.  I am guessing this is the first patch to mitigate/workaround, until the proper fix lands.  Thanks for this, and look forward to it.

**Comment by SDRausty** [comment]
@Leif-W please update

**Comment by xtkoba** [comment]
Proper fix is now merged upstream: https://github.com/vim/vim/commit/cbef12e60b2c5a4f026172ab9873deaab2e70cf2. I am going to backport it asap.
