### ISSUE TITLE
CANNOT LINK EXECUTABLE "rsync": library "libcrypto.so.1.1" not found: needed by main executable

### ISSUE THREAD

**Issue by Noexpert** [termux/termux-packages#9167]
### Problem description

I'm opening a new issue as advised by:
https://github.com/termux/termux-packages/issues/9050#issuecomment-1052154502

`rsync` fails with
`CANNOT LINK EXECUTABLE "rsync": library "libcrypto.so.1.1" not found: needed by main executable`

I've reinstalled cleanly several times from F-Droid.

### What steps will reproduce the bug?

execute `rsync`

### What is the expected behavior?

`rsync` should complete

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.190-perf+ #1 SMP PREEMPT Fri Nov 19 18:57:45 KST 2021 aarch64 Android
```

**Comment by 16to** [comment]
you can try `pkg install openssl-1.1` and `pkg up`，I fixed
