### ISSUE TITLE
I met an unexpected error:(process completed signal 9 press enter)when im running kali nethunter.My phone is android 12 samsung a52.

### ISSUE THREAD

**Issue by Kekw02** [termux/termux-packages#9173]
![Screenshot_20220227-222614_Termux](https://user-images.githubusercontent.com/100523743/155886555-9f916aff-d725-4748-8e98-38dee3c3cdcc.jpg)

**Comment by xtkoba** [comment]
Invalid as we do not package Kali NetHunter.

**Comment by sk0kanik** [comment]
[#9003 (comment)](https://github.com/termux/termux-packages/issues/9003#issuecomment-1036060185)

**Comment by sk0kanik** [comment]
termux/termux-app#2366
