### ISSUE TITLE
Bug : CANNOT LINK EXECUTABLE "php": cannot find "libssl.so" from verneed[2] in DT_NEEDED list for "/data/data/com.termux/files/usr/bin/php"

### ISSUE THREAD

**Issue by BeaBamboo2009** [termux/termux-packages#9175]
### Problem description

I wanna prank my friend using termux spam chat
I did all the step to install it
But when i wanna use it
It's says : CANNOT LINK EXECUTABLE "php": cannot find "libssl.so" from verneed[2] in DT_NEEDED list for "/data/data/com.termux/files/usr/bin/php"
Can anyone help?

### What steps will reproduce the bug?

The bug will not reproduce

### What is the expected behavior?

I expect it to launch itu bomwhatsapp menu

### System information

termux-info:

```Android version:
9
Kernel build information:
Linux localhost 3.18.120-21534220 #2 SMP PREEMPT Mon Apr 19 13:44:17 KST 2021 armv7l Android
Device manufacturer:
samsung
Device model:
SM-J415F

```

**Comment by xtkoba** [comment]
Update your `openssl` package.

**Comment by BeaBamboo2009** [comment]
> Update your `openssl` package.
Alr i'll try
