### ISSUE TITLE
[Bug]: Mariadb database install error with stack corruption detected

### ISSUE THREAD

**Issue by c4dr01d** [termux/termux-packages#9187]
### Problem description

At post install mariadb package when install system database generate this error:
Initializing mysql data directory...                          Installing MariaDB/MySQL system tables in '/data/data/com.termux/files/usr/var/lib/mysql' ...                               stack corruption detected (-fstack-protector)
Aborted                                                       cat: write error: Broken pipe
cat: write error: Broken pipe
cat: write error: Broken pipe                                 
Installation of system tables failed!  Examine the logs in
/data/data/com.termux/files/usr/var/lib/mysql for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /data/data/com.termux/files/usr/bin/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /data/data/com.termux/files/usr/bin/mariadbd --skip-grant-tables --general-log &

and use the command line tool /data/data/com.termux/files/usr/bin/mariadb
to connect to the mysql database and look at the grant tables:

    shell> /data/data/com.termux/files/usr/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /data/data/com.termux/files/usr/var/lib/mysql that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss

Please check all of the above before submitting a bug report
at https://mariadb.org/jira

### What steps will reproduce the bug?

pkg install mariadb

### What is the expected behavior?

Install mariadb and database normally

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 5.4.86-qgki-g9ccef2df83e2 #1 SMP PREEMPT Thu Nov 25 20:53:25 CST 2021 aarch64 Android
Device manufacturer:
HONOR
Device model:
NTH-AN00
```

**Comment by manfrom** [comment]
I'm also having the same issue,I've tried the method in  #5738 but it doesn't solve my problem

**Comment by xtkoba** [comment]
```
Thread 1 "mariadbd" received signal SIGABRT, Aborted.
0x0000007fb7b22658 in abort () from target:/system/lib64/libc.so
(gdb) bt
#0  0x0000007fb7b22658 in abort () from target:/system/lib64/libc.so
#1  0x0000007fb7b7dd30 in __stack_chk_fail () from target:/system/lib64/libc.so
#2  0x000000555692b0cc in my_md5 (digest=<optimized out>, buf=<optimized out>, len=4455) at /home/builder/.termux-build/mariadb/src/mysys_ssl/my_md5.cc:92
#3  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Comment by xtkoba** [comment]
https://github.com/MariaDB/server/commit/c9beef43154a199bfcd9f71049c011a2ed77ca74

https://jira.mariadb.org/browse/MDEV-25785

Apparently MariaDB 10.6.x does not support OpenSSL 3.0.
