### ISSUE TITLE
2022-02-27 22:41:46 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.db' doesn't exist 2022-02-27 22:41:46 0 [ERROR] Aborting Warning: Memory not freed: 280

### ISSUE THREAD

**Issue by ReisoAphi** [termux/termux-packages#9194]
![Screenshot_2022-02-27-22-36-27-0333039368](https://user-images.githubusercontent.com/87125229/155920425-931ba486-096b-47db-aecd-101dd6eb4c35.png)

could you please help me with this issue ?

**Comment by ReisoAphi** [comment]
never mind, I just changed repo and it worked, but I have another issue that I'm going to post on as a different one

**Comment by dincodekar** [comment]
Same problem please help
