### ISSUE TITLE
Execution failure on running 'netcat' (nc)

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#9198]
Since last update:-
netcat
CANNOT LINK EXECUTABLE "netcat": library "libssl.so.1.1" not found: needed by main executable
u0_a247@localhost:~$ nc
CANNOT LINK EXECUTABLE "nc": library "libssl.so.1.1" not found: needed by main executable

**Comment by xtkoba** [comment]
Can't reproduce for me. `netcat-openbsd` (version `1.217-2-2`) should not depend on OpenSSL.

**Comment by macerg** [comment]
Installing netcat-openbsd (version 1.217-2-2) should not depend on OpenSSL. after removing netcat fixed issue for me.

**Comment by macerg** [comment]
I've installed netcat-openbsd after uninstalling netcat and that fixed it for me. Thanks.On 28 Feb 2022 13:38, xtkoba ***@***.***> wrote:
Can't reproduce for me. netcat-openbsd (version 1.217-2-2) should not depend on OpenSSL.
