### ISSUE TITLE
Package request: caddy

### ISSUE THREAD

**Issue by huiyiqun** [termux/termux-packages#92]
> Caddy is an alternative web server that is easy to configure and use. 

It's available for android according [here](https://github.com/mholt/caddy/wiki/Running-Caddy-on-Android)

**Comment by fornwall** [comment]
You can use the caddy static binary directly, so there doesn't seem much point in packaging it from what I can tell.

    curl -o caddy.tar.gz -L https://github.com/mholt/caddy/releases/download/v0.8.0/caddy_linux_arm.tar.gz
    tar xf caddy.tar

After creating a `Caddyfile` with `tls off` I'm able to serve up my `$HOME` folder by executing `./caddy`!
