### ISSUE TITLE
[Bug]: Mariadb: mysql db not created during install

### ISSUE THREAD

**Issue by mzwach** [termux/termux-packages#9202]
### Problem description

Hi,

on some devices I have the problem during the last days, that during 

apt install mariadb

the mysql database is not installed properly, so I cannot login with a user, nor with root.

All my measures to get access, like:
- using mysql_install_db, mysql_upgrade
- starting mysql with --skip-grant-tables
     is ok, but then even    grant privileges;     fail, since no mysql database is availabe.
do not work.

I dont know where to search or how to solve that problem.
I have found some problems in github, saying that the installation script has some issues. But I dont know whether my problem is related to it. I have some devices, where it works perfectly!!

Here is my termux-info output:

<img width="734" alt="Bildschirmfoto 2022-02-28 um 13 09 00" src="https://user-images.githubusercontent.com/65561205/155981170-f625a9e4-181a-4c22-835b-768d0946dab6.png">

### What steps will reproduce the bug?

uninstall termux
install termux via f-droid
run:

apt update
apt install mariadb

mariadbd-safe

afterwards it is not possible to login via:

mysql 
nor
mysql -u root

### What is the expected behavior?

installation procedure should initialize the mysql user / rights database

### System information

termux-info:

```
termux-info
Application version:
0.118 0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
debhttps://packages. termux.org/apt/termux-main/stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.152-perf-23447145-abT500XXU3BVA4 #1 SMP PREEMPT Tue Jan 18 19:07:32 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T500
```

**Comment by ReisoAphi** [comment]
Im also habing the same issue, still trying to figure it out.

anything will be helpful

**Comment by Oleg231-debug** [comment]
Try that
1. mysqld &
2. mysql -u $(whoami)
3. ALTER USER root@localhost IDENTIFIED VIA mysql_native_password;
4. flush privileges;
5. exit
6. mysql -u root
After that, you can login as root@localhost and setup the password
8.

**Comment by iMampi** [comment]
> thank you for your input. No, it did not help, since the initial setup during apt install was not creating any user! But the source code change of xtkoba worked perfect!! 

Hello, can you elaborate how you solved your problem with the source code change please?
