### ISSUE TITLE
[Feature]: dpkg-scanpackages,

### ISSUE THREAD

**Issue by zairullahdev** [termux/termux-packages#9203]
### Feature description

I need it, i don't wanna use proot-distro, because it's very troublesome, please because I'm need this to make my repository

### Additional information

No,only Debian based distro has this feature

**Comment by wmcbtech30** [comment]
I made an attempt enabling it but needs perl modules to work which we don't allow packaging it (#8334)

**Comment by tathastu871** [comment]
build.sh for dpkg has entry for removing the dpkg-scan package binary just delete that entry and it will be available to use when we install dpkg

**Comment by xtkoba** [comment]
Apparently it is allowed to invoke `cpan` in `postinst` script, if it resolves the dependency.

```bash
cpan -fi Locale::gettext
```

(Test fails due to missing `locale` command.)
