### ISSUE TITLE
 [Bug]: borgbackup 1.1.17-5 | multiple `ImportError` errors

### ISSUE THREAD

**Issue by xfzv** [termux/termux-packages#9207]
### Problem description

Since the last few days, I'm getting the following error whenever I run just `borg` or with any option such as `borg --version` for instance:

```sh
$ borg
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/archiver.py", line 40, in <module>
    from .algorithms.checksums import crc32
ImportError: cannot import name 'crc32' from 'borg.algorithms.checksums' (/data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/algorithms/checksums.cpython-310-x86_64-linux-gnu.so)
```

I tried the following, to no avail:

```sh
pkg uninstall borgbackup
pkg install borgbackup       # The install completes without any issue
pkg reinstall borgbackup
```

I also tried clearing Termux cache and storage in Android Settings and I'm not getting the same errors this time around:

```sh
$ borg
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/archiver.py", line 38, in <module>
    from . import helpers
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/helpers.py", line 76, in <module>
    import borg.crypto.low_level
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/crypto/low_level.py", line 9, in <module>
    __bootstrap__()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/crypto/low_level.py", line 7, in __bootstrap__
    mod = importlib.util.module_from_spec(spec)
ImportError: dlopen failed: cannot find "libcrypto.so" from verneed[0] in DT_NEEDED list for "/data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/crypto/low_level.cpython-310-x86_64-linux-gnu.so"
```

### What steps will reproduce the bug?

1. Install [Termux 0.118.0 from F-Droid](https://f-droid.org/repo/com.termux_118.apk)
2. Run `pkg install borgbackup`
3. Run `borg`
4. The second error reported appears every time

### What is the expected behavior?

Any `borg` command should work without any error

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.14.267-GulchR~GaltsGulchR.v2.15 #1 SMP PREEMPT Tue Feb 22 11:39:11 EST 2022 aarch64 Android
Device manufacturer:
OnePlus
Device model:
GM1913
```

**Comment by xtkoba** [comment]
Update your `openssl` package. And PLEASE report back if the situation changes OR NOT.

**Comment by xfzv** [comment]
> Update your `openssl` package. And PLEASE report back if the situation changes OR NOT.

:thinking: 


I have openssl 3.0.1, which is the [latest](https://github.com/termux/termux-packages/blob/aa4df8ad44fba800fe6bbf41f1b6ac85a329caa7/packages/openssl/build.sh#L5).

```sh
$ pkg show openssl

Package: openssl
Version: 3.0.1
Maintainer: @termux
Installed-Size: 6648 kB
Depends: ca-certificates, zlib
Conflicts: libcurl (<< 7.61.0-1)
Breaks: openssl-tool (<< 1.1.1b-1), openssl-dev
Replaces: openssl-tool (<< 1.1.1b-1), openssl-dev
Homepage: https://www.openssl.org/
Download-Size: 1575 kB
APT-Manual-Installed: yes
APT-Sources: https://termux.mentality.rip/termux-main stable/main aarch64 Packages
Description: Library implementing the SSL and TLS protocols as well as general purpose cryptography functions
```

```sh
$ termux-info
[...]
Updatable packages:
All packages up to date
```

**Comment by xtkoba** [comment]
Can confirm the first error reported by the author:

```
$ borg
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/archiver.py", line 40, in <module>
    from .algorithms.checksums import crc32
ImportError: cannot import name 'crc32' from 'borg.algorithms.checksums' (/data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/algorithms/checksums.cpython-310-x86_64-linux-gnu.so)
```

I believe the second error (after clearing Termux cache and storage) is not much relevant to the first one, and I'm not going to investigate it (the second one) further.

**Comment by pabl0** [comment]
Seeing the same on my slightly unusual use case where I run "borg serve" on an Android device.

Will #9234 fix this?

BTW I am wondering why the .so's are "linux-x86_64" on aarch64?

**Comment by thunder-coding** [comment]
> Will #9234 fix this?

No, it's just a workaround when libraries in /system/lib or /system/lib64 have DT_RUNPATH entry in elf data.

> BTW I am wondering why the .so's are "linux-x86_64" on aarch64?

If this is the case, then that's the problem

**Comment by xtkoba** [comment]
I believe this issue is triggered by updating NDK to r23. OpenSSL update is just a red herring.

**Comment by pabl0** [comment]
To clarify, I think the actual libraries are compiled for correct ARM architecture, the name is just weird.

```
~ $ file /data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/algorithms/checksums.cpython-310-x86_64-linux-gnu.so
/data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/algorithms/checksums.cpython-310-x86_64-linux-gnu.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
~ $ ldd /data/data/com.termux/files/usr/lib/python3.10/site-packages/borgbackup-1.1.17-py3.10-linux-x86_64.egg/borg/algorithms/checksums.cpython-310-x86_64-linux-gnu.so
libpython3.10.so.1.0
libc.so
```

**Comment by xtkoba** [comment]
The name of native extensions should not be relevant, or at least was not relevant before NDK r23. It is because we do not setup crossenv for building python packages. Yeah, it would be nice if we could fix it, but it is not relevant to this specific issue, I believe.

**Comment by xtkoba** [comment]
Not much relevant but I would like to mention that `borgbackup` is currently one of the packages that fails to autoupdate, and I am planning to overhaul it. It may be that it is fixed by updating to the latest (upstream) version, or not.

**Comment by xtkoba** [comment]
When locally built using crossenv, borgbackup 1.1.17 seems to work properly. So I believe this can be fixed somehow.

Unfortunately, updating to 1.2.0 is not easy or even impossible due to dependency on other external python package, namely msgpack.

Also there is a question: why in the first place is this packaged as a Termux package? Is `pip install borgbackup` not sufficient?

**Comment by Maxr1998** [comment]
> Unfortunately, updating to 1.2.0 is not easy or even impossible due to dependency on other external python package, namely msgpack.

What's the specific issue with msgpack? Wouldn't it be possible to package this for Termux too? I.e., as `python-msgpack`?
 
> Also there is a question: why in the first place is this packaged as a Termux package? Is `pip install borgbackup` not sufficient?

It looks like pip install works as well, but supposedly having python programs compiled/packaged and provided by the distribution and thus managed by the main package manager like on Arch or Ubuntu is preferable from a system management standpoint. On the other hand, Termux doesn't install as root and isn't a full Linux distribution.
