### ISSUE TITLE
Add it on a store

### ISSUE THREAD

**Issue by Nerd00F** [termux/termux-packages#9209]
Update the app on play store too, or maybe put it on the aurora store.

**Comment by Grimler91** [comment]
It's not that simple. See https://github.com/termux/termux-packages/wiki/Termux-and-Android-10

**Comment by Nerd00F** [comment]
@Grimler91 even in the aurora store there is this problem?

**Comment by Grimler91** [comment]
Apps cannot be uploaded to aurora store. Aurora store downloads apps from google play.

**Comment by Nerd00F** [comment]
Oh ok

**Comment by Mrnouvelle00225** [comment]
Le mar. 1 mars 2022 à 01:04, Alan Christian ***@***.***> a
écrit :
