### ISSUE TITLE
Package request: squeezelite

### ISSUE THREAD

**Issue by zuglufttier** [termux/termux-packages#921]
Now that there is support for cmus (#209), it should be possible to add support for squeezelite from @ralph-irving: https://github.com/ralph-irving/squeezelite

Squeezelite is a very nice software which would transform any android device supported by termux into a fully capable squeezebox.

**Comment by zuglufttier** [comment]
Added a bounty: https://www.bountysource.com/issues/44054818-package-request-squeezelite

**Comment by jbdelisle** [comment]
Hi,

Not sure whether this is the proper place, but in case this can help I managed to compile and run squeezelite on termux, with the following steps:
- Install dependencies:
`pkg install pulseaudio libmad mpg123`
- Install build-dependencies:
`pkg install git make clang`
- Get squeezelite source code:
`git clone https://github.com/ralph-irving/squeezelite.git`
`cd squeezelite`
- Modify makefile (it seems that faad is not available on termux):
`sed Makefile.pulse -e 's/-DPULSEAUDIO/-DPULSEAUDIO -DNO_FAAD/g' > Makefile.termux`
- Compile:
`make -f Makefile.termux`
- Run (for some reason it needs "-d all=info" to work???):
`./squeezelite-pulse -d all=info`

Can this be easily turned into a package (I have no experience in packaging for termux)?

**Comment by xtkoba** [comment]
(In reply to https://github.com/termux/termux-packages/issues/921#issuecomment-991379402:) In general, creating a package for Termux is not very difficult if you have knowledge of Bash script. You can learn how to write package scripts by reading existing ones, along with <a href="https://github.com/termux/termux-packages/wiki/Creating-new-package">the official document</a>. It is true that from time to time we are put cross-build specific obstacles that do not arise when building on device. But let's try anyway.
