### ISSUE TITLE
Error with installing lolcat. (Duplicate issue but the previous one was closed without proper solution)

### ISSUE THREAD

**Issue by Rehan587** [termux/termux-packages#9225]
So I upgraded my packages today, then tried installing lolcat, then suddenly for some reason I get this error.

```
ERROR:  While executing gem ... (Gem::Exception)
    OpenSSL is not available. Install OpenSSL and rebuild Ruby (preferred) or use non-HTTPS sources
```

Here is my termux-info output

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable main
# sources.list.d/termuxblack.list
deb https://hax4us.github.io/TermuxBlack/ termuxblack main
# sources.list.d/gushmazuko.list
deb https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.186-g4f65b02ee-dirty #1 SMP PREEMPT Thu Dec 16 18:28:32 CST 2021 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1915
```

![Screenshot_2022_0301_103242.jpg](https://user-images.githubusercontent.com/84271835/156108175-caa203ff-1b8c-40ae-9a29-80775d43428f.jpg)

I have installed Openssl already and i had it before as well, it was working fine before the upgrade.

Pls help.

**Comment by xtkoba** [comment]
Just can't reproduce for me:

```
$ gem install lolcat
Fetching lolcat-100.0.1.gem
Fetching optimist-3.0.1.gem
Fetching manpages-0.6.1.gem
Fetching paint-2.2.1.gem
Successfully installed paint-2.2.1
Successfully installed optimist-3.0.1
Successfully installed manpages-0.6.1
Successfully installed lolcat-100.0.1
Parsing documentation for paint-2.2.1
Installing ri documentation for paint-2.2.1
Parsing documentation for optimist-3.0.1
Installing ri documentation for optimist-3.0.1
Parsing documentation for manpages-0.6.1
Installing ri documentation for manpages-0.6.1
Parsing documentation for lolcat-100.0.1
Installing ri documentation for lolcat-100.0.1
Done installing documentation for paint, optimist, manpages, lolcat after 1 seconds
4 gems installed
```

**Comment by Grimler91** [comment]
Also can't reproduce, maybe same issue as in https://github.com/termux/termux-packages/issues/9174.
Try installing in verbose mode and see if you get more info:
```
gem install --verbose lolcat
```

**Comment by Rehan587** [comment]
> Also can't reproduce, maybe same issue as in https://github.com/termux/termux-packages/issues/9174.
> Try installing in verbose mode and see if you get more info:
> ```
> gem install --verbose lolcat
> ```

I think i have messed up my environment somewhere. Going to reinstall everything now 😅, maybe that could fix the issue altogether.

**Comment by xtkoba** [comment]
Also make sure that all packages are up to date. Note that dependencies are not automatically updated when updating a single package. I believe that the combination of `ruby` version `3.1.0-2` and `openssl` version `3.0.1-1` should work fine.

**Comment by Rehan587** [comment]
So apparently, the issue was with the Ruby version i was using. I was using Ruby 2.7.0 earlier which caused the issue.

As soon as I installed the latest version of Ruby, it worked just fine.


Thanks everyone for helping out :).

(I'm sorry if I made any sort of mistake, im not a native English speaker).
