### ISSUE TITLE
[Bug]: Separate package for boost libraries

### ISSUE THREAD

**Issue by alive4ever** [termux/termux-packages#9228]
### Problem description

Currently, boost's installed size is **very large** (almost 200MB).

```
$ apt show boost
Package: boost
Version: 1.78.0
Maintainer: @termux
Installed-Size: 192 MB
Depends: libc++, libbz2, libiconv, liblzma, zlib
Breaks: libboost-python (<= 1.65.1-2), boost-dev
Replaces: libboost-python (<= 1.65.1-2), boost-dev
Homepage: https://boost.org
Download-Size: 10.7 MB
APT-Manual-Installed: no
APT-Sources: https://packages-cf.termux.org/apt/termux-main stable/main aarch64 Packages
Description: Free peer-reviewed portable C++ source libraries
```

The only package on my system which depends on `boost` is `ncmpcpp`.

`ncmpcpp` actually uses only  a few boost libraries: filesystem, locale, program_options, and thread.

```
$ ldd $(which ncmpcpp) | grep boost
libboost_filesystem.so.1.78.0
libboost_locale.so.1.78.0
libboost_program_options.so.1.78.0
libboost_thread.so.1.78.0
```

Total size of those `boost` libraries is less than 1 MB
```
$ ldd $(which ncmpcpp) | grep boost | xargs -I %% ls -l $PREFIX/lib/%% | awk '{ du += $5 } END {print du }' | numfmt --to iec
946K
```
It would be nice to have separate package for boost libraries.

### What steps will reproduce the bug?

```
$ ldd $(which ncmpcpp) | grep boost
```
Only a few boost libraries is required for ncmpcpp runtime.

``` sh
$ apt show boost
```
Look at installed size: almost 200MB.

### What is the expected behavior?

Separate packages for `boost`, so that ncmpcpp can be installed without pulling **huge** `boost` dependency.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.9.297-Arrow-LA.UM.10.6.2.r1-00600-89xx.0 #1 SMP PREEMPT Thu Jan 27 14:59:24 UTC 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 4
```

**Comment by alive4ever** [comment]
After some digging, I found that `boost` shared object files are occupying less than 7MB.

```
dpkg -L boost | grep \.so\$ | xargs -I %% stat -Lc %s %% | awk '{ sum += $1 } END { print sum }' | numfmt --to iec
6.8M
```

With this finding, an easier solution would be creating separate packages for libraries and headers. So if a program only depends on the libraries, installing the program will not pull those headers.

**Comment by truboxl** [comment]
Return of `boost-dev`?

**Comment by Grimler91** [comment]
boost-headers sounds good, I was thinking of boost-libs, but -headers will make it easier to handle the boost dependency for other packages (add boost to TERMUX_PKG_DEPENDS and boost-headers to TERMUX_PKG_BUILD_DEPENDS)
