### ISSUE TITLE
[Package]: tenki

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9230]
### Package description

A weather manager for tenki

### Home page URL

https://github.com/dmpop/tenki

### Source code URL

https://github.com/dmpop/tenki

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Haiz14** [comment]
```
It's built as a website, so you would need to set up a webserver and host the files on it, then access it through that. That's the case with the vast majority of PHP applications, because fundamentally PHP is a web language
```

A quick answer.
