### ISSUE TITLE
[Bug]: repository is under maintenance or down

### ISSUE THREAD

**Issue by Aritmistri4555** [termux/termux-packages#9232]
### Problem description

$ pkg install root-repo
Checking availability of current mirror: ok
Get:1 https://grimler.se/termux-packages-24 stable InRelease [16.8 kB]
Err:1 https://grimler.se/termux-packages-24 stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B
Reading package lists... Done
W: GPG error: https://grimler.se/termux-packages-24 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B
E: The repository 'https://grimler.se/termux-packages-24 stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

### What steps will reproduce the bug?

Plese help me

### System information

termux-info:

```

```
Android realme6i

**Comment by Grimler91** [comment]
Switch to another mirror with `termux-change-repo` and update your packages. See instructions in for example https://github.com/termux/termux-packages/issues/6726
