### ISSUE TITLE
[Package]: Hping3

### ISSUE THREAD

**Issue by nityanand86876** [termux/termux-packages#9238]
### Package description

this package is used to ddos any ip and do many more thing .
it is avaliable in most of the linux ditributions such as ubuntu, kali linux, debian etc.

### Source code URL

https://packages.debian.org/stretch/hping3

### Packaging policy acknowledgement

- [x] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by ELWAER-M** [comment]
i think you didn't

![Screenshot_20220301-170124_Kiwi Browser](https://user-images.githubusercontent.com/71197008/156193098-05771463-4573-4bac-a468-97c7a16da129.jpg)

![Screenshot_20220301-170104_Kiwi Browser](https://user-images.githubusercontent.com/71197008/156193128-11006d11-2a9c-4528-8602-ff9c5338611e.jpg)

**Comment by Grimler91** [comment]
It's also [already available](https://github.com/termux/termux-root-packages/tree/master/packages/hping3).
