### ISSUE TITLE
Package request: Mop

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#924]
Mop is a command-line utility that displays continuous up-to-date information about the U.S. markets and individual stocks.

![screenshot](https://cloud.githubusercontent.com/assets/782908/24973268/8c12af10-1f94-11e7-89b6-1031317e1471.png)

https://github.com/mop-tracker/mop

**Comment by xeffyr** [comment]
Package is outdated and not working:
```
Error fetching market data...
Unable to parse http://money.cnn.com/data/markets/

Error fetching stock quotes...
Get http://download.finance.yahoo.com/d/quotes.csv?s=AAPL+C+GOOG+IBM+KO+ORCL+V&f=sl1c1p2oghjkva2r2rdyj3j1: dial tcp: lookup download.finance.yahoo.com: No address associated
```
