### ISSUE TITLE
[Bug]: PIP modules installation doesn't works.

### ISSUE THREAD

**Issue by hackersspaceoff** [termux/termux-packages#9240]
### Problem description

Whenever I try to install any python module with
"pip install module_name" it gives a error as shown below. 
It says it's unavailable.

### What steps will reproduce the bug?

pip install requests

### What is the expected behavior?

Install The Request module

### System information

termux-info:

```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because t
```

**Comment by xtkoba** [comment]
What version of `python` and `openssl` are you using?

**Comment by xtkoba** [comment]
The combination of `openssl_3.0.1-1` and `python_3.10.2-5` should work fine. Update them if not yet.

**Comment by hackersspaceoff** [comment]
i am really sry for this opening of the issue. it was just a simple error and needed just a pkg upgrade.
