### ISSUE TITLE
Package request tintin++

### ISSUE THREAD

**Issue by DorienCragen** [termux/termux-packages#925]
http://tintin.sourceforge.net/

**Comment by DorienCragen** [comment]
Tintin is most powerfull mud client allows you to play muds. Have build in map engine, triggers aliases sunstitutions, basicly it has own scripting language similar to zMud, im sure this may have many fallowers

**Comment by jammet** [comment]
Yes. Either this or tinyfugue would be a great help.

**Comment by its-pointless** [comment]
got a pull request up for this. Tiny fugue is in disabled-packages/tf but it doesn't compile. This does.

**Comment by fornwall** [comment]
Thanks to @its-pointless a `tintin++` package is now available! Install with

    packages install tintin++
