### ISSUE TITLE
[Package]: rig

### ISSUE THREAD

**Issue by Bouboulov** [termux/termux-packages#9251]
### Package description

RIG stands for Random Identity Generator. It is a free replacement for a shareware program out there called 'fake'. Basically its single purpose in life is to generate random, yet real-looking, personal data.

### Home page URL

http://rig.sourceforge.net/

### Source code URL

https://sourceforge.net/projects/rig/files/rig/1.11/rig-1.11.tar.gz/download

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I tried to compile it but it failed. There's no traditional configure file etc. and i'm a beginner.

It's said in the README just "make install" but I got this : 
```
make install 
install -g 0 -m 755 -o 0 -s rig /usr/local/bin
install: cannot create regular file '/usr/local/bin': No such file or directory
make: *** [Makefile:14: install] Error 1
```

Anyway it's just for fun, not priority stuff but I thought it would be nice to have it !

**Comment by xtkoba** [comment]
It seems like just a matter of hardcoded paths, one of <a href="https://github.com/termux/termux-packages/wiki/Common-porting-problems">Common porting problems</a>.
