### ISSUE TITLE
[Bug]: a very large number of failed compilations in termux-package-pacman

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#9255]
### Problem description

For some reason, repo termux-package-pacman has a lot of compilation failures and these errors are compiler related.

[List of failures](https://github.com/Maxython/termux-packages-pacman/actions?query=is%3Afailure)

Can you now update the main repository less often, there is a suspicion that this thing will be with all packages.

### What steps will reproduce the bug?

Auto update repository

### What is the expected behavior?

Successful compilation

### System information

This is github actions

**Comment by xtkoba** [comment]
There seem to be defects in package building logic wrt platform-independent packages. Pre-built packages marked as platform-independent seem to be unavailable for archs other than aarch64.

**Comment by xtkoba** [comment]
Note that `boost-headers` is annotated as platform-independent, while its "superpackage" `boost` is not:

```
Downloading dependency boost-headers@1.78.0-1 if necessary...
Download of boost-headers@1.78.0-1 from https://packages-cf.termux.org/apt/termux-main failed, building instead
boost@1.78.0-1 built - skipping (rm /data/data/.built-packages/boost to force rebuild)
```
