### ISSUE TITLE
[Package]: mencoder/mplayer

### ISSUE THREAD

**Issue by OilSubjectLoss7** [termux/termux-packages#9258]
### Package description

Great alternative to vlc and mpv also it can encode old subtitles. Please also add dvdauthor

### Home page URL

https://packages.debian.org/search?keywords=mencoder

### Source code URL

https://packages.debian.org/search?keywords=mencoder

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Please keep one package request per issue.

What do "old subtitles" mean?

**Comment by xtkoba** [comment]
Ref #482
