### ISSUE TITLE
Permission issues with npm, yarn, and directories

### ISSUE THREAD

**Issue by schniedan** [termux/termux-packages#926]
Hi, 

this project is awesome! I have to get my head around a few more things. I can see this turning my nice little HP G1 into a development machine with everything I need for my little react app :)

Following this tutorial, I'm trying to get node/yarn (and others) up and running:
https://hackernoon.com/code-a-react-website-on-your-android-smartphone-or-tablet-like-you-never-imagined-3e56c534f6e7

For yarn, I get the attached error:
[yarn-error-log.txt](https://github.com/termux/termux-packages/files/917971/yarn-error-log.txt)

When going for an npm install for a more complex package.json, I get many 
error tar.unpack untar error /data/data/com.termux/files/home/.npm/...*..
I tried setting HOME and TMP to other directories (../storage/downloads e.g.) to see if the permissions are better there, but that didn't help.
Additionally, there are many 
4484 verbose optional SKIPPING OPTIONAL DEPENDENCY:
4484 verbose optional Please try running this command again as root/Administrator.

See more details in attached npm log: 
[npm-debug-log.txt](https://github.com/termux/termux-packages/files/918009/npm-debug-log.txt)

Any idea how I could get around that? Do you need further information? I'm on latest termux and ChromeOS: 
Version 58.0.3029.51 beta (64-bit)
Platform 9334.33.0 (Official Build) beta-channel chell
ARC Version 3872362
Firmware Google_Chell.7820.253.0

Many thanks in advance, 
Andreas

**Comment by vishalbiswas** [comment]
Does that path reside on external storage?
What is the filesystem on that path?
npm log says it failed on utime syscall.
Try with your termux home a d temp directories.

**Comment by schniedan** [comment]
It's all internal storage. Thanks heaps for your help. /data/data/com.termux/files/home/projects/my-app works a lot better. The yarn install- and create-react-app scripts worked except for a gitignore error in the very last step that seems ignorable. The code still compiles and the server 'seems' to start. I'm getting the success message that my server should be reachable on http://localhost:3000. But my chromebook Chrome won't access the page. I'm getting a connection refused. I changed the node server to listen on 127.0.0.1 instead but that is not working either.

As I was typing this, I came up with the idea of hitting it with curl from within termux. And that works!

Have you experienced this before? The host chrome os not being able to reach servers started in termux through localhost? Want me to chuck this into a separate issue thread? I looked at a few things in chromium feeds but some old DNS flags etc. don't exist anymore that could have fixed it.

This is still really awesome, thanks for this little linux-in-an-app!

**Comment by vishalbiswas** [comment]
@schniedan this means that android apps in chromebooks are running in a container, separate from the OS. I don't have a chromebook myself, but you should be able to get the ip address of the container interface. Are you able to execute shell commands outside of termux? If yes, see if the container network interface is exposed by running `ifconfig`.

**Comment by schniedan** [comment]
I can call ifconfig from the chromeos system view, see screenshot below. But that doesn't seem to give anything away about the container. The bridge br0 isn't it.
![Uploading Screenshot 2017-04-14 at 19.37.10.png…]()

**Comment by schniedan** [comment]
Boom, got it!
su > ifconfig inside termux tells you that it is actually connected to that 192.168.254.* brigde-subnet.
http://192.168.254.2:3000/ takes me to my react app!
Sweet, thanks for the container hint.

**Comment by schniedan** [comment]
This works really nicely now. I have another thing that would greately improve workefficiency with this on Chromebooks but it's really offtopic for this one. So I'll close this one and open a dedicated one. Thanks for your help!

**Comment by liuchang0920** [comment]
ifconfig does the job. saves me lot of time on this. Thanks.

**Comment by ElNuru247** [comment]
$ create-react-app my-app
bash: /data/data/com.termux/files/usr/bin/create-react-app: Permission denied



Please why do i get the above error when i try to create a react app on termux?

**Comment by sdrausty** [comment]
@ElNuru247 thank you for your post.  A little more information is requested.  Use `termux-info` and help us figure out what might be happening.  My second question to you is simple.  Did you root your precious smartphone?
