### ISSUE TITLE
[Bug]: curl error after openssh install

### ISSUE THREAD

**Issue by OmiSummy** [termux/termux-packages#9260]
### Problem description

CANNOT LINK EXECUTABLE "curl": library "libssl.so.1.1" not found

### What steps will reproduce the bug?

$ curl
curl: try 'curl --help' or 'curl --manual' for more information
$ apt update
$ apt install openssh
$ curl
CANNOT LINK EXECUTABLE "curl": library "libssl.so.1.1" not found

### What is the expected behavior?

$ curl
curl: try 'curl --help' or 'curl --manual' for more information

### System information

termux-info:0.118.0

```

```

**Comment by Grimler91** [comment]
Upgrade your packages, `pkg upgrade`.

**Comment by OmiSummy** [comment]
Isn't this a bug?

Of course,when I install libcurl libssh2,the problem will be
 disappear.

But I can find libssl.so.1.1 in /data/user/0/com.termux/files/usr/lib/openssl-1.1/

**Comment by OmiSummy** [comment]
> Upgrade your packages, `pkg upgrade`.

$ find /data/user/0/com.termux/ -name "libssl.so.1.1"

/data/user/0/com.termux/files/usr/lib/openssl-1.1/libssl.so.1.1

**Comment by OmiSummy** [comment]
Bad:
~ $ apt show curl -a                                    Package: curl
Version: 7.81.0-2
Essential: yes
Maintainer: @termux
Installed-Size: 340 kB
Depends: libcurl (= 7.81.0-2)
Homepage: https://curl.se/
Download-Size: 170 kB
APT-Sources: https://packages.termux.org/apt/termux-main stable/main aarch64 Packages
Description: Command line tool for transferring data with URL syntax

Package: curl                                           Version: 7.81.0
Status: install ok installed
Essential: yes                                          Maintainer: @termux
Installed-Size: 340 kB
Depends: libcurl (= 7.81.0)
Homepage: https://curl.se/
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /data/data/com.termux/files/usr/var/lib/dpkg/status
Description: Command line tool for transferring data with URL syntax


Success:
~ $ apt show curl -a
Package: curl
Version: 7.81.0-2
Essential: yes
Maintainer: @termux
Installed-Size: 340 kB
Depends: libcurl (= 7.81.0-2)
Homepage: https://curl.se/
Download-Size: 170 kB
APT-Manual-Installed: yes
APT-Sources: https://packages.termux.org/apt/termux-main stable/main aarch64 Packages
Description: Command line tool for transferring data with URL syntax

**Comment by thunder-coding** [comment]
You broke your environment because you did a partial upgrade. See #7050 on how to recover from a broken environment

**Comment by cheungchingli** [comment]
> 



> You broke your environment because you did a partial upgrade. See #7050 on how to recover from a broken environment

What do you mean？

**Comment by thunder-coding** [comment]
> What do you mean？

Update your packages
```
$ pkg up
```
