### ISSUE TITLE
Can't run Tor (Could not bind to 127.0.0.1:9050: Address already in use.)

### ISSUE THREAD

**Issue by 411A** [termux/termux-packages#9264]
Hi, I was using **Orbot**, after uninstalling it, tried to test Tor using Termux (`pkg install tor`) but receiving this error.
Uninstalled & reinstalled the package (also restarted the phone).
packages are up-to-date (both `apt` & `pkg up`).
```tor
Mar 02 16:44:21.772 [notice] Tor 0.4.6.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 3.0.1, Zlib 1.2.11, Liblzma 5.2.5, Libzstd N/A and Unknown N/A as libc.
Mar 02 16:44:21.772 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Mar 02 16:44:21.772 [notice] Read configuration file "/data/data/com.termux/files/usr/etc/tor/torrc".
Mar 02 16:44:21.774 [notice] Opening Socks listener on 127.0.0.1:9050
Mar 02 16:44:21.775 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
Mar 02 16:44:21.775 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
Mar 02 16:44:21.775 [err] Reading config failed--see warnings above.```

**Comment by Grimler91** [comment]
Error means what it says, something is already using port 9050. Most likely tor in another session, or another app like orbot.

`netstat -tulpn` in termux can show if some program in termux is using it. If not, then it must be some other app

**Comment by 411A** [comment]
> Error means what it says, something is already using port 9050. Most likely tor in another session, or another app like orbot.
> 
> `netstat -tulpn` in termux can show if some program in termux is using it. If not, then it must be some other app

didn't used Orbot as VPN, just entered the proxy to Telegram then removed the proxy and uninstalled the Orbot.
AFAIK there aren't any app that are using this addresse, though using that command returned empty result because don't have the root permission.

**Comment by Grimler91** [comment]
> are there any command to change the port?

Yes, edit the config file `$PREFIX/etc/tor/torrc`. See also `man tor`.

**Comment by 411A** [comment]
Unfortunately even changing the port didn't help.
though there's no other sessions as I know.
```Mar 02 17:27:56.000 [warn] It looks like another Tor process is running with the same data directory.  Waiting 5 seconds to see if it goes away.
Mar 02 17:28:01.000 [err] No, it's still there.  Exiting.```
one last question: is there any command to kill all tor sessions? tried this: `killall tor`, but nothing happened.
I think I should go back to Orbot...

**Comment by Grimler91** [comment]
Clearly tor is running in another termux session. What's the output of `pstree`?

**Comment by 411A** [comment]
thanks! it resolved now... didn't know about `termux-services`. yeah it was running...<br>
fixed using `sv down tor`.

**Comment by Grimler91** [comment]
`sv down tor` stops the service, but it will start again when phone is rebooted. `sv-disable tor` will stop and disable it

**Comment by 411A** [comment]
I think the problem is because of `zsh`.
after running the Tor and breaking it using `Ctrl + Z`, I've run all the killing commands, still getting the same error.
the `pstree` shows this output:
```
╭─ ~ ─────────────────────────────────────────────  18:30:44
╰─❯ pstree
?─┬─?───zsh─┬─pstree
  │         └─tor
  ├─runsvdir───runsv───svlogd
  ├─runsvdir───runsv
  ├─zsh───gitstatusd-linu───16*[{gitstatusd-linu}]
  └─2*[zsh]
```

**Comment by Grimler91** [comment]
> after running the Tor and breaking it using `Ctrl + Z`

Bring it to foreground, with `fg`, and stop it with `ctrl + c`
