### ISSUE TITLE
I can't install python when I run pkg install python it says python not found [Bug]: 

### ISSUE THREAD

**Issue by afarPython** [termux/termux-packages#9265]
### Problem description

I can't install python because it says python is invalid

### What steps will reproduce the bug?

Pkg install python

### What is the expected behavior?

Won't install

### System information

termux-info:

```pkg install python' '' 

```

**Comment by Grimler91** [comment]
You haven't provided any info so not really anything to do here. Maybe try switching mirror with `termux-change-repo`.
