### ISSUE TITLE
Latex

### ISSUE THREAD

**Issue by 134sofiane** [termux/termux-packages#927]
Hello everyone
I installed texlive via apt install texlive, I have a file.tex , but when I write to termux :  pdflatex file.tex , it says: No command 'pdflatex' found,

Please how can I run the file.tex?

**Comment by buribu** [comment]
Try this
export PATH=$PATH:/data/data/com.termux/files/usr/opt/texlive/2016/bin/custom
export TMPDIR=/data/data/com.termux/files/usr/tmp/

or run script in

/data/data/com.termux/files/usr/etc/profile.d/texlive.sh

**Comment by Grimler91** [comment]
Did you get any errors during the installation? 

If @buribu's suggestion doesn't work, try running `termux-install-tl` and post the log here.

**Comment by 134sofiane** [comment]
Thank you @buribu  it worked well :) , thank you @Grimler91,
Now I have a new question : if I need to install a package , how can I install it?

**Comment by buribu** [comment]
To install package on texlive try:
tlmgr install packagename

To search package try:
tlmgr search packagename

**Comment by Grimler91** [comment]
And to find the name of the packages that provides some file: 
`tlmgr search --global --file SomeFile.sty`

**Comment by 134sofiane** [comment]
Thank you very very much. Good day
