### ISSUE TITLE
[Bug]: no repository 

### ISSUE THREAD

**Issue by DadioRoot** [termux/termux-packages#9273]
### Problem description

apt update
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Hit:4 https://packages.termux.org/apt/termux-root root InRelease
Err:5 https://dl.bintray.com/grimler/game-packages-24 games Release
  502  Bad Gateway
Err:6 https://dl.bintray.com/grimler/science-packages-24 science Release
  502  Bad Gateway
Get:7 https://packages.termux.org/apt/termux-x11 x11 InRelease [7857 B]
Get:1 https://packages.termux.org/apt/termux-main stable InRelease [14.0 kB]
Get:8 https://packages.termux.org/apt/termux-x11 x11/main aarch64 Packages [88.1 kB]
Get:9 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages [364 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$ https://termux.com/issues
bash: https://termux.com/issues:

### What steps will reproduce the bug?

I really don't know what would help I'm pretty new to everything 

### What is the expected behavior?

I was just trying to do an update

### System information

termux-info:

```

```apt update
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Hit:4 https://packages.termux.org/apt/termux-root root InRelease
Err:5 https://dl.bintray.com/grimler/game-packages-24 games Release
  502  Bad Gateway
Err:6 https://dl.bintray.com/grimler/science-packages-24 science Release
  502  Bad Gateway
Get:7 https://packages.termux.org/apt/termux-x11 x11 InRelease [7857 B]
Get:1 https://packages.termux.org/apt/termux-main stable InRelease [14.0 kB]
Get:8 https://packages.termux.org/apt/termux-x11 x11/main aarch64 Packages [88.1 kB]
Get:9 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages [364 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$ https://termux.com/issues
bash: https://termux.com/issues:

**Comment by xtkoba** [comment]
#6726
