### ISSUE TITLE
[Bug]: Can not installing any packages 

### ISSUE THREAD

**Issue by fahim9876** [termux/termux-packages#9275]
### Problem description

Hey,I can not install any kind of packages.Like ubuntu,python etc.
![Screenshot_20220303-173142_Termux](https://user-images.githubusercontent.com/94130776/156556506-02f0ea2b-038c-4f95-8b67-a45794066789.jpg)

### What steps will reproduce the bug?

Please solve the problem.

### What is the expected behavior?

I need this solution ...

### System information

termux-info:

```

```

**Comment by thunder-coding** [comment]
The error says it all. 

First run
```
$ dpkg --configure -a
``` 
and then ` pkg up`
