### ISSUE TITLE
[Package]: add onefetch

### ISSUE THREAD

**Issue by ExtinctDrift19** [termux/termux-packages#9277]
### Package description

full information https://github.com/o2sh/onefetch

### Source code URL

https://github.com/o2sh/onefetch

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Git repository summary on your terminal

**Comment by thunder-coding** [comment]
Package already available. Added in #9186
