### ISSUE TITLE
[Bug]: Missing TeXlive Full group of packages

### ISSUE THREAD

**Issue by PillFall** [termux/termux-packages#9295]
### Problem description

I recently bought a new phone, and I won't be able to install in the new one all the packages that I generally use. As the TeXlive Full group.

### What steps will reproduce the bug?

After fresh installing Termux, try to `pkg install texlive-full`

### What is the expected behavior?

Install all the TeXlive related packages as the wiki says

https://wiki.termux.com/wiki/TeX_Live

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.113-perf-gcbf97e8a8dcd #1 SMP PREEMPT Mon May 17 02:11:53 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2012K11AG
```

**Comment by xtkoba** [comment]
`texlive-full` is removed in commit 7b355a29d05fa8570c2d9e25b55d135db96d6725. Use `texlive-installer` instead.

**Comment by PillFall** [comment]
I try and use all the available mirrors and with none of the I be able to download TeXlive

**Comment by PillFall** [comment]
> `texlive-full` is removed in commit [7b355a2](https://github.com/termux/termux-packages/commit/7b355a29d05fa8570c2d9e25b55d135db96d6725). Use `texlive-installer` instead.

Oh, thanks, I didn't notice that

**Comment by Grimler91** [comment]
Wiki has been updated to no longer mention texlive-full, thanks

**Comment by PillFall** [comment]
I got another question, after I install `texlive-installer` I won't be able to use any of the executables, as `xelatex` or so

**Comment by Grimler91** [comment]
`texlive-installer` is just an installation script, so you need to follow the printed instructions to actually install texlive (run `termux-install-tl`)

**Comment by PillFall** [comment]
Yeah, I refer after running the `termux-install-tl` (I get no errors in the installation), I can see that I have `latex`, `fmtutil`, and other executables, but not `xelatex`, or `lualatex`.
