### ISSUE TITLE
Mutt doesn't support SASL

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#93]
Hi, opening the editor works great now. Thanks.I am however still unable to send mails with gmail. I get the following error: "SMTP authentication requires SASL". I read that USE_SASL needs to be specified during compilation and mutt -v shows that it's not available.

**Comment by fornwall** [comment]
Thanks! I've updated the mutt package to build with SASL support in version `1.5.24-2` of the package, which you should be able to update to with:

    apt update && apt upgrade

I verified that I can send a mail using gmail, let me know if you find anything broken!

**Comment by Neo-Oli** [comment]
Thanks. I am also able to send mails now.
