### ISSUE TITLE
[Package]: Cloudflare Tunnel

### ISSUE THREAD

**Issue by DarremMolko** [termux/termux-packages#9301]
### Package description

"**Cloudflare Tunnel** is tunneling software that lets you quickly secure and encrypt application traffic to any type of infrastructure, so you can hide your web server IP addresses, block direct attacks, and get back to delivering great applications."

### Home page URL

https://www.cloudflare.com/products/tunnel

### Source code URL

https://github.com/cloudflare/cloudflared

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

As suggested in Discord I'm opening this package request again, it was requested by me before (here: https://github.com/termux/termux-packages/issues/8868), and it was closed because they had licensing issues, but just a little while after that they changed their license to Apache 2.0. I hope this makes it a valid request.

**Comment by xtkoba** [comment]
Yes, it seems to be valid. :+1:
