### ISSUE TITLE
Access to home files from outside the app container without root

### ISSUE THREAD

**Issue by schniedan** [termux/termux-packages#931]
Hi, 
is there a way to get access to the files in /data/data/com.termux/files/home/ from outside the app (and outside its' container as well) without root access to the filesystem?
Context: I have a react.js development environment up and running in /data/data/com.termux/files/home/.../someapp.../ on my chromebook. Given the fact that the chromebook can run sophisticated code editors I would like to access the files from the host system. 
Symbolic links don't work because it would circumvent the whole permission scheme. And I can't seem to fine a fileexplorer that gives me access outside the numb downloads directory level.
Any ideas?
Cheers, 
Andreas

**Comment by fornwall** [comment]
Android apps using the Storage Access Framework (which I know that at least [Turbo Editor](https://play.google.com/store/apps/details?id=com.maskyn.fileeditor) supports) can access and edit files under $HOME, but I guess that doesn't help with non-android chromebook apps.

Can you access shared storage from Termux (see [termux.com/storage.html](https://termux.com/storage.html), though I don't know how that translates when running inside a chromebook)? If so you could perhaps setup the the development environment there.

**Comment by darthwalsh** [comment]
I used termux to run a git clone in ~/storage/downloads and it seems to be working fine, even though git gave a warning about not being able to protect .git/config.

For anybody else trying this, the link is now https://wiki.termux.com/wiki/Internal_and_external_storage
