### ISSUE TITLE
[Package]: DVDAuthor

### ISSUE THREAD

**Issue by OilSubjectLoss7** [termux/termux-packages#9316]
### Package description

For tagging and dumping dvd files. Please...

### Home page URL

https://github.com/ldo/dvdauthor

### Source code URL

https://github.com/ldo/dvdauthor

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
`libdvdread`is not packaged in any of our official repos.
