### ISSUE TITLE
[Bug]: aapt failed to build resources (buildAPKs).

### ISSUE THREAD

**Issue by Anonymous2716** [termux/termux-packages#9324]
### Problem description

When building an app from github repo aapt returns XML error that cannot be resolved : 

````./build.repo.bash https://github.com/rkkr/simple-keyboard
Processing https://github.com/rkkr/simple-keyboard in directory ~/buildAPKs/sources/github.com/rkkr/simple-keyboard:
Cloning into 'simple-keyboard'...
remote: Enumerating objects: 1025, done.
remote: Counting objects: 100% (1025/1025), done.
remote: Compressing objects: 100% (807/807), done.
remote: Total 1025 (delta 533), reused 429 (delta 126), pack-reused 0
Receiving objects: 100% (1025/1025), 818.61 KiB | 624.00 KiB/s, done.
Resolving deltas: 100% (533/533), done.

BuildAPKs build.repo.bash prep.bash: Processing elements in directory /data/data/com.termux/files/home/buildAPKs/sources/github.com/rkkr/simple-keyboard: Please wait...
Deleted directory '/data/data/com.termux/files/home/buildAPKs/sources/github.com/rkkr/simple-keyboard/.git '.
BuildAPKs build.repo.bash prep.bash /data/data/com.termux/files/home/buildAPKs/sources/github.com/rkkr/simple-keyboard: DONE
Found 0 APK files in ~/buildAPKs/sources/github.com/rkkr/simple-keyboard/.

Activating wake lock: DONE
Searching for job directories in /data/data/com.termux/files/home/buildAPKs/sources/github.com/rkkr/simple-keyboard: Please be patient...

Beginning build in ~/buildAPKs/sources/github.com/rkkr/simple-keyboard/app/src/main/:
AlphabetShiftState.java
AndroidManifest.xml
AppearanceSettingsFragment.java
ApplicationUtils.java
......
.sym_keyboard_zwnj_lxx_light.png sym_keyboard_zwnj_lxx_light.png
sym_keyboard_zwnj_lxx_system.xml
themes-common.xml themes-lxx-dark-border.xml themes-lxx-dark.xml themes-lxx-light-border.xml themes-lxx-light.xml themes-lxx-system-border.xml themes-lxx-system.xml
aapt: started...
Signal generated aapt build.one.bash build.one.bash: EXITING... buildAPKs signal 220 received by build.one.bash in /data/data/com.termux/files/home/buildAPKs/sources/github.com/rkkr/simple-keyboard/app/src/main by build.one.bash. More information in /data/data/com.termux/files/home/buildAPKs/var/log/stnderr.in.dir.simple-keyboard.log file.
Running: VAR="$(grep -C 2 -ie error -ie errors "/data/data/com.termux/files/home/buildAPKs/var/log/stnderr.in.dir.simple-keyboard.log")" && VAR="$(grep -v -- <<< $VAR)" && head <<< $VAR && tail <<< $VAR
Failed to generate resource table for split ''
res/values-v31/colors.xml:23: error: Error: No resource found that matches the given name (at 'background_lxx_system' with value 'https://github.com/android:color/system_neutral1_100'). Failed to generate resource table for split '' res/values-v31/colors.xml:23: error: Error: No resource found that matches the given name (at 'background_lxx_system' with value 'https://github.com/android:color/system_neutral1_100').
Completing tasks...
Completed tasks in ~/buildAPKs/sources/github.com/rkkr/simple-keyboard/app/src/main/.

Build time: 2 seconds Releasing wake lock: DONE
To always have wake lock set to on: touch ~/buildAPKs/var/lock/set.lock
Found 0 APK files in ~/buildAPKs/sources/github.com/rkkr/simple-keyboard/.

```


### What steps will reproduce the bug?

XML references like this 
```<color name="language_on_spacebar_text_color_lxx_system">@android:color/system_accent1_800</color>```

### What is the expected behavior?

build successfully.

### System information

termux-info:

```
❯ termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.astra.in.ua/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/x11-packages x11 main
# sources.list.d/termux-desktop-xfce.list
deb [trusted=yes arch=all] https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce extras
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.146 #2 SMP PREEMPT Wed Sep 9 18:47:45 CST 2020 aarch64 Android
```

**Comment by Grimler91** [comment]
Please share a code snippet that reproduces the problem, preferably that doesn't require buildAPKs, so that we can be sure that issue is with aapt and not buildAPKs

**Comment by SDRausty** [comment]
>Please share a code snippet that reproduces the problem, preferably that doesn't require buildAPKs, so that we can be sure that issue is with aapt and not buildAPKs

`aapt package -c en -f --generate-dependencies -J gen --min-sdk-version 14 -M AndroidManifest.xml --target-sdk-version 23 --replace-version -S res --version-code 1646910589 --version-name rkr.simplekeyboard.inputmethod.1646910589`

`Failed to generate resource table for split ''
res/values-v31/colors.xml:23: error: Error: No resource found that matches the given name (at 'background_lxx_system' with value '@android:color/system_neutral1_100').`

To reproduce this code:
`cd /data/data/com.termux/files/home/buildAPKs/sources/github.com/rkkr/simple-keyboard/app/src/main`

Add `set -x` in file `~/buildAPKs/scripts/bash/build/build.one.bash` and run file `build.one.bash` in the `main` directory.

>we can be sure that issue is with aapt 

After upgrading `aapt`, building https://github.com/rkkr/simple-keyboard began to fail.  Similar repositories that used to build, no longer build properly in Termux.  Thank you for sharing this newly arisen error @Anonymous2716.

Can `aapt2` be used instead of `aapt`?  If so, what would the `aapt2` command line look like?

**Comment by SDRausty** [comment]
>code snippet that reproduces the problem

`aapt package -J gen -M AndroidManifest.xml -S res`

`Failed to generate resource table for split ''
res/values-v31/colors.xml:23: error: Error: No resource found that matches the given name (at 'background_lxx_system' with value '@android:color/system_neutral1_100').`

**Comment by SDRausty** [comment]
> preferably that doesn't require buildAPKs, so that we can be sure 

Since command ~/buildAPKs/build.repo.bash was added on April 1st 2021 which enables building just one repository, and this command was also tested extensively with https://github.com/search and https://gitlab.com/explore/ successfully buildAPKs was burdened with `openjdk-17/stable` a 100mb dounload and now `aapt` is broken.  A 100+mb download is not:
>The minimal install size to start building your first apps is about 10MB.

Why the sudden change from 10MB to more than 110MB?

Why is progress by and for Termux users muffled by Termux?

> Could you help please?

EXAMPLE USAGE: build.repo.bash https://github.com/BuildAPKs/buildAPKs.entertainment

If you find repo candidates for inclusion, please share an address to the sourcecode here in this topic.

_Originally posted by @SDRausty in https://github.com/BuildAPKs/buildAPKs/issues/18#issuecomment-811978422_

**Comment by agnostic-apollo** [comment]
`system_neutral1_100` was added in API `31`, possible issue could be using older sdk to compile.

https://developer.android.com/reference/android/R.color#system_neutral1_100

https://github.com/rkkr/simple-keyboard/blob/94/app/src/main/res/values-v31/colors.xml#L23

https://github.com/rkkr/simple-keyboard/blob/94/app/build.gradle#L4

**Comment by Anonymous2716** [comment]
Yes . the java code throws error too which is could be solved by using SDK 32 compilation.

**Comment by xtkoba** [comment]
Are the following changes made to `aapt` relevant?

https://github.com/termux/termux-packages/blob/7e94d3e2e7ae85fabef5605cbd98ca3f67c27215/packages/aapt/build.sh#L244-L252

https://github.com/termux/termux-packages/blob/7e94d3e2e7ae85fabef5605cbd98ca3f67c27215/packages/aapt/aapt-Main.cpp.patch#L24-L25

I do not understand these changes at all.

**Comment by agnostic-apollo** [comment]
Yes, `28` should have been bumped to `31` as well. `addPackageInclude` is equivalent of `-I base-package` option. The `resources.arsc` in the `android,jar` would be of older sdk, hence resources are not found.

https://cs.android.com/android/platform/superproject/+/android-12.0.0_r32:frameworks/base/tools/aapt/Main.cpp;l=431

And `sdk` `32` (Android `12L`) sources should be available as well now.

https://cs.android.com/android/platform/superproject/+/android12L-platform-release:frameworks/base/tools/aapt/Main.cpp

**Comment by xtkoba** [comment]
OK, I will work on it. Thanks!

**Comment by agnostic-apollo** [comment]
Goodluck. Welcome!

**Comment by Anonymous2716** [comment]
```1. WARNING in /data/data/com.termux/files/home/main/java/rkr/simplekeyboard/inputmethod/keyboard/KeyboardView.java (at line 512)
        invalidate(x, y, x + key.getWidth(), y + key.getHeight());
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method invalidate(int, int, int, int) from the type View is deprecated
----------
----------
2. WARNING in /data/data/com.termux/files/home/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyboardRow.java (at line 30)
        import rkr.simplekeyboard.inputmethod.keyboard.Keyboard;
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import rkr.simplekeyboard.inputmethod.keyboard.Keyboard is never used
----------
----------
3. ERROR in /data/data/com.termux/files/home/main/java/rkr/simplekeyboard/inputmethod/keyboard/KeyboardSwitcher.java (at line 94)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                         ^

```90 more warnings and one info was generated  ... This is also termux package related . would be nice if update.

**Comment by vertuaq** [comment]
Signal generated aapt build.one.bash build.one.bash: EXITING... how can I fix this I'm issue I'm trying to build am apk with buildAPKs but it keeps showing me an error all my builds fail not 1 is built ? What can I do to fix it also

**Comment by Anonymous2716** [comment]
@vertuaq you must post the errors
