### ISSUE TITLE
[Bug]: Can't Install Pip

### ISSUE THREAD

**Issue by YellowStar11** [termux/termux-packages#9329]
### Problem description

I'm trying to install pip. It appears like this:
pkg install pip
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package pip

### What steps will reproduce the bug?

Pkg install pip 

### What is the expected behavior?

No response 

### System information

termux-info:

0.118.0

**Comment by agnostic-apollo** [comment]
`pip` is automatically installed with `python`.

https://wiki.termux.com/wiki/Python#Package_management

**Comment by lifeModder19135** [comment]
Have you tried with apt?

**Comment by agnostic-apollo** [comment]
Termux does not have a separate `pip` package.

**Comment by lifeModder19135** [comment]
You might already have it. Pip usually comes bundled with python, in Linux at least. Try running

`python3  -m  pip install   —upgrade pip`

Another way to find out is to use findutils to locate your site packages. 

`find / -type d -name site*packages -print  -exec ‘ls -a. |  grep pip ’`

it is usually either in /user/local/lib/python*/site-packages/ or in    ${HOME}/.local/lib/python*/site-packages/ and it will either be a source file or a wheel.

If none of this works, there is one cheeky option left ( unless you have `which` installed)

create a v.env with `python3 -m venv ggg && cp -a -t /choose/a/writable/dir/in/path   ./ggg/lib/pip*  `

**Comment by lifeModder19135** [comment]
That is what I figured. I gave them some options. It took forever to type because I’m pecking away on an android phone with one finger.Anyway it’s just as well. Having a separate installation just to save a few letters in the invitation doesn’t really make sense on android IMO

**Comment by lifeModder19135** [comment]
@op set a bash alias if you need to.
