### ISSUE TITLE
libgpg-error output doesn't work correctly on all cases

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#933]
This sample program:

```C
#define GPGRT_ENABLE_ES_MACROS
#include <gpg-error.h>
int main() { es_putc('A', es_stdout); }
```

built with

    apt install -y clang libgpg-error-dev && clang test.c -lgpg-error && ./a.out

fails to produce output on some configurations:

- Working (output produced): aarch64 (tested on Android 7.0 and 7.1 devices)
- Not working (no output produced): 32-bit arm (tested on an Android 6.0)

There are two local patches ([tools-gpgconf.c](https://github.com/termux/termux-packages/blob/master/packages/gnupg2/tools-gpgconf.c.patch), [g10-gpg.c](https://github.com/termux/termux-packages/blob/master/packages/gnupg2/g10-gpg.c.patch)), but a proper analysis and fix would be great and would open up transitioning to gnupg2 fully and drop gnupg1 support.

**Comment by yumaokao** [comment]
Tested on some configurations:

- Working: i686 (tested on Android 7.1 emulator)
- Not working: aarch64 (tested on an Android 6.0 device)

**Comment by fornwall** [comment]
Hm, a current theory would be that the problem is with Android versions prior to 7.0.

**Comment by yumaokao** [comment]
It looks like "atexit()" is the difference.  

Both of devices register do_deinit with atexit()
` atexit(do_deinit) `

However only on the working one, do_deinit() is called which flush the stream out.

**Comment by yumaokao** [comment]
Further check in atexit(do_deinit), should correct previous information.

Add two lines,`fprintf(stderr)` and `abort()` in the very beginning of `do_deinit()`,
Only on the working one(Android 7), could see the message from `fprintf(stderr)`.

Both of them (Android 7, Android 6) are aborted, which means `do_deinit()` does been called.

**Comment by yumaokao** [comment]
libgpg-error uses `__attribute__ ((__constructor__))` to register `do_deinit` atexit.

With a break point set at `do_deinit`
On Android 6 at this point, there is no any **fd** in /proc/PID/fd/.
On Android 7, **stdin, stdout and stderr (0, 1, 2)** are all still there.

It's also worth mentioning that if call functions to register atexit explicitly (i.e. not through __constructor__),
standard fds won't disappear even on Android 6.

**Comment by fornwall** [comment]
The PR by @yumaokao (https://github.com/termux/termux-packages/pull/1017) is now live in version `1.27-1` of libgpg-error.

The workarounds have been removed in the `gnupg2` package now at version `2.1.21` as they should no longer be necessary even on Android < 7.

**Comment by yumaokao** [comment]
It's `malloc_fini_impl()` in bionic who closes standard fds. Which is used for malloc leakage debugging.

In Android M, call flow to `malloc_fini_impl` will be registered to **atexit** *after* `do_deinit` decorated with **__constructor__**.
In Android N, registering `malloc_fini_impl` to **atexit** looks like an optional debug mode.
