### ISSUE TITLE
[Bug]: github actions: haskell packages not compiling

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#9334]
### Problem description

A very large number of unsuccessful compilations.
[link](https://github.com/Maxython/termux-packages-pacman/actions?query=is%3Afailure)

### What steps will reproduce the bug?

auto-update and empty comets

### What is the expected behavior?

successful compilation

### System information

This github actions

**Comment by UNKNOWNADWAITH** [comment]
The nethunter rootles is not working in termux .please update the termux or please make change in the nethunterk code

**Comment by Grimler91** [comment]
Should be fixed by https://github.com/termux/termux-packages/pull/9333 I believe
