### ISSUE TITLE
Clang error[Bug]: 

### ISSUE THREAD

**Issue by RohitVermaOP** [termux/termux-packages#9336]
### Problem description

clang arm assembler 

### What steps will reproduce the bug?

clang --target=armv7a-none-linux-android -fno-integrated-as -c pixman-arm-neon-asm.S

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64                                                Subscribed repositories:
# sources.list                                         deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11                                                     Kernel build information:                              Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Feb 10 17:02:37 CST 2022 aarch64 Android                         Device manufacturer:
realme
Device model:
RMX2151
```

**Comment by Grimler91** [comment]
Share what output you get, and a file that gives the error. No one can run `clang --target=armv7a-none-linux-android -fno-integrated-as -c pixman-arm-neon-asm.S` without `pixman-arm-neon-asm.S`.

**Comment by RohitVermaOP** [comment]
![Uploading Screenshot_2022-03-09-17-32-51-81_84d3000e3f4017145260f7618db1d683.jpg…]()

File link :
https://drive.google.com/file/d/14_aiChJvL2uv7k08oXbwlVGOQqc4OwH5/view?usp=drivesdk

**Comment by xtkoba** [comment]
With `-fno-integrated-as` option `clang` invokes `$PREFIX/bin/as` as the assembler which is not configured for cross building.

A workaround is to remove `-fno-integrated-as` option. If it does not work then you may have to build `binutils` targeting `armv7a` by yourself.
