### ISSUE TITLE
[Package]:srt2vob

### ISSUE THREAD

**Issue by OilSubjectLoss7** [termux/termux-packages#9339]
### Package description

Converts srt files into vobsub(idx,sub) files

### Home page URL

https://code.google.com/archive/p/srt2vob/

### Source code URL

https://code.google.com/archive/p/srt2vob/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Everything was going wrong, it's an old code

**Comment by xtkoba** [comment]
REJECTED as per packaging policy:

> We will not accept outdated, dead projects as well as projects which do not have active community.

Try fixing it for yourself if you wish to use it.
