### ISSUE TITLE
Package request: Shellinabox

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#934]
Shell In A Box implements a web server that can export arbitrary command line tools to a web based terminal emulator. This emulator is accessible to any JavaScript and CSS enabled web browser and does not require any additional browser plugins.
![preview](https://cloud.githubusercontent.com/assets/782908/25071463/a80666ec-228e-11e7-8ee8-00e8e1c7aebe.gif)
https://github.com/shellinabox/shellinabox

**Comment by HarrySystems** [comment]
Any news about this issue?
Is there any way I can help make shellinabox available for termux?

**Comment by tomty89** [comment]
Seems like it's a maintenance fork of a inactive project (which no longer gets much maintenance either?).
Doesn't stop you from compiling on site though.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install shellinabox
```
