### ISSUE TITLE
[Bug]:ImageMagick,GraphicMagick,Wand.Image.Magick

### ISSUE THREAD

**Issue by OilSubjectLoss7** [termux/termux-packages#9354]
### Problem description

The draw,text,font,stroke outline doesn't work, i only tested on wand.py but it's definitely on pkg's end.

### What steps will reproduce the bug?

Through wand.py  draw.stroke_outline

### What is the expected behavior?

Text with outline

### System information

`````

`````

**Comment by Grimler91** [comment]
You will need to provide more info than that. 

How do I reproduce the issue? What is wand.py? It's not something that termux provides. 
What output do you get? Share terminal output or a screenshot.
Paste your output of `termux-info` under `System information`.

**Comment by xtkoba** [comment]
Does not make sense to me either. With the `convert` command coming from `imagemagick_7.1.0.16-2_aarch64` I can produce the following image:

![stroke_outline](https://user-images.githubusercontent.com/69125751/157853329-87d84f88-22d8-4466-a7c3-70ec22294b17.png)

with the following command line:

```bash
convert -size 360x96 xc:yellow -font /system/fonts/DroidSans.ttf -pointsize 96 \
-fill white -stroke black -strokewidth 16 -draw "text 16,80 'Termux'" \
-stroke none -draw "text 16,80 'Termux'" stroke_outline.png
```

(Example borrowed and modified from https://legacy.imagemagick.org/Usage/draw/.)

**Comment by xtkoba** [comment]
No response from author. Closing.
