### ISSUE TITLE
Unnecessary variables.

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#936]
In build-package.sh, line 227 & 228:

```
export TERMUX_TAR="tar"
export TERMUX_TOUCH="touch"
```

Are these variables necessary? Can we just substitute it directly into the script?

**Comment by vishalbiswas** [comment]
Well, they were significant when we used to support builders on OS X

**Comment by Wetitpig** [comment]
So not needed now right?

**Comment by fornwall** [comment]
Right, they can be removed now that OS X support directly has been dropped (OS X users can still use Docker to build).
