### ISSUE TITLE
[Bug]: intltool: should not build on device

### ISSUE THREAD

**Issue by mguinhos** [termux/termux-packages#9360]
### Problem description

Compilation of intltool on device is slow and expensive

### What steps will reproduce the bug?

```bash
pkg install intltool -y
```

![image](https://user-images.githubusercontent.com/43307018/157816550-12449310-f715-41ec-ab13-02e555772da4.png)

### What is the expected behavior?

The package must must install without compiling on device

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.kcubeterm.com/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.87-22307827 #1 SMP PREEMPT Wed Sep 8 10:55:38 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N981B
```

**Comment by thunder-coding** [comment]
I am against the idea to disable on-device compilation of heavy packages. On-device builds may be used to detect problems that occur only during cross compilation as well as for other variety of reasons. The most I can agree on is to issue a warning for such packages

**Comment by xtkoba** [comment]
@thunder-coding, that is not the point. The author means that `intltool` invokes `cpan` in the `postinst` script:

https://github.com/termux/termux-packages/blob/7a359b68f33cd83e8a521298407530c01cad325e/packages/intltool/build.sh#L12-L22

**Comment by Grimler91** [comment]
This would require porting (at least) LWP::UserAgent, Encode::Locale, File::Listing, HTTP::Date, Time::Zone. 

I don't think this would be worth the effort considering that:

* intltool is more or less obsolete, in favor of gettext
* perl modules are generally annoying to cross-compile
* `cpan install XML::Parser` works without issues

intltool should depend on make and clang though, those are needed for successful installation.

**Comment by xtkoba** [comment]
Also should depend on `libexpat`.
