### ISSUE TITLE
[Package]: whatscli

### ISSUE THREAD

**Issue by Bouboulov** [termux/termux-packages#9371]
### Package description

A command line interface for whatsapp, based on go-whatsapp and tview.

### Home page URL

https://github.com/normen/whatscli

### Source code URL

https://github.com/normen/whatscli

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
The author of `whatscli` seems to put it under MIT license, but I cannot find any copyright information in the tarball (other than a third-party one in `qrcode/qrcode.go`.) We cannot legally package this as of now, maybe.

**Comment by Bouboulov** [comment]
OK then.
