### ISSUE TITLE
[Bug]: Deprecated keyring 

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#9372]
### Problem description

W: https://its-pointless.github.io/files/24/dists/termux/InRelease: Key is stored in legacy trusted.gpg keyring (/data/data/com.termux/files/usr/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

### What steps will reproduce the bug?

Run apt upgrade.

### What is the expected behavior?

Process runs without warning message.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.org/apt/termux-root root stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.org/apt/termux-x11 x11 main
Updatable packages:
ffmpeg/stable 5.0-1 aarch64 [upgradable from: 4.4.1-1]
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Fri Sep 17 17:16:18 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003
```

**Comment by wmcbtech30** [comment]
You should report it to it's pointless repository since we don't maintain third party repositories

***

Warning should be ignored

**Comment by macerg** [comment]
Ok.

**Comment by angelog0** [comment]
@wmcbtech30 wrote

> You should report it to it's pointless ..

but [there](https://github.com/its-pointless/gcc_termux/issues/142) none answers. The last commit was on June 2021... Are they still _alive_?

upgrading Termux still produces that warning..

**Comment by macerg** [comment]
Yes, I have reported this on the it's pointless repository. It appears to be dead though. No-one responds to anything.

**Comment by 2096779623** [comment]
`mv $PREFIX/etc/apt/trusted.gpg $PREFIX/etc/apt/trusted.gpg.d/its-ponitless.gpg`
`pkg up -y`
