### ISSUE TITLE
[Package]: socat

### ISSUE THREAD

**Issue by reikred** [termux/termux-packages#9378]
### Problem description

I was unable to install socat from the standard termux repos. Where am I supposed to get it from?

I tried also finding some socat.deb package that would work. That also did not go so well, as shown below

...
~ $ uname -a
Linux localhost 3.18.120-perf-g197239455137-04290-gfb8faa3398e9 #1 SMP PREEMPT Thu Apr 23 11:51:22 CDT 2020 armv7l Android
~ $

~ $ pkg install ~/downloads/socat_1.7.4.1-3_arm64.deb 
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'socat:arm64' instead of '/data/data/com.termux/files/home/downloads/socat_1.7.4.1-3_arm64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 socat:arm64 : Depends: libc6:arm64 (>= 2.17) but it is not installable
               Depends: libssl1.1:arm64 (>= 1.1.0) but it is not installable
               Depends: libwrap0:arm64 (>= 7.6-4~) but it is not installable
E: Unable to correct problems, you have held broken packages.
~ $ 
...

I guess I do not understand what I am doing wrong. Can anyone set me on the right track?

### What steps will reproduce the bug?

See above

### What is the expected behavior?

Getting socat installed

### System information

termux-info:

...
~ $ termux-info
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.18.120-perf-g197239455137-04290-gfb8faa3398e9 #1 SMP PREEMPT Thu Apr 23 11:51:22 CDT 2020 armv7l Android
Device manufacturer:
motorola
Device model:
moto g(6)
...

**Comment by xtkoba** [comment]
This is because 32-bit builds for `socat` is disabled:

https://github.com/termux/termux-packages/blob/45d78b44aa80bcf512d9307a9bde0de513cafbab/packages/socat/build.sh#L12-L13

**Comment by reikred** [comment]
Note to self: moto-g6 has armv71, which is 32-bit. 

On my other 64-bit phone, socat did get installed okay.

**Comment by reikred** [comment]
Wow, now I can install socat! Thanks!

**Comment by romanlapa** [comment]
Hi! Is there a chance that you can explain how do I install it now? `apt-get install socat` returns "Unable to locate package socat". Should I do it in some other way?

**Comment by Grimler91** [comment]
@romanlapa should be available for all architectures in main repo. What repo are you subscribed to?

**Comment by romanlapa** [comment]
> @romanlapa should be available for all architectures in main repo. What repo are you subscribed to?

That's a tough question to be honest. How do I check it and how can I add it? I am using termux as a part of a project that I just recently started working on.

pkg install socat returns: Hit:https://packages.androidide.com/apt/termux-main. So I gues project has it's own repo for termux dependencies.

Yet I need socat, to test a concept. 

Can I just add a repo somehow to termux and try it on my device?

**Comment by romanlapa** [comment]
> We do not have any mirrors in our mirrorlist with domain https://packages.androidide.com, so you are not using official termux app.
> 
> From where did you install "termux"? Whatever build you are using has made their own changes to packages, and reporting issues here is off-topic as there is nothing we can do to fix 3rd party apps

It's a part of https://github.com/AndroidIDEOfficial/AndroidIDE. 

> off-topic as there is nothing we can do to fix 3rd party apps
Fair enough. I guess I can install a standalone termux app and use it from there with `apt edit-sources` .

Thanks!

**Comment by Grimler91** [comment]
> It's a part of https://github.com/AndroidIDEOfficial/AndroidIDE.
> 
> > off-topic as there is nothing we can do to fix 3rd party apps
> 
> Fair enough. I guess I can install a standalone termux app and use it from there with `apt edit-sources` .

Assuming these are the [build recipes for that app](https://github.com/AndroidIDEOfficial/terminal-packages) (last updated 6 months ago) then it will not be possible to apt edit-sources as that app uses [a different PREFIX](https://github.com/AndroidIDEOfficial/terminal-packages/blob/master/scripts/properties.sh#L33). To get socat in that app you will have to build it from source
