### ISSUE TITLE
Unable to login to Github via Termux

### ISSUE THREAD

**Issue by Kalmai221** [termux/termux-packages#9380]
### Problem description

I am unable to sign into Github in Termux to be able to create and push Github Repositories. It also wouldn't let me type my password. 

### What steps will reproduce the bug?

Do git init

### What is the expected behavior?

Username for 'https://github.com': Kalmai221
Password for 'https://Kalmai221@github.com':
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.190+ #1 SMP PREEMPT Thu Feb 10 17:13:38 CST 2022 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH2185
```

**Comment by agnostic-apollo** [comment]
Go to the link provided and read.

**Comment by MedzikUser** [comment]
I recommend generating an ssh key and using it
