### ISSUE TITLE
How to create a mirror for Termux's apt repository?

### ISSUE THREAD

**Issue by hmsjy2017** [termux/termux-packages#9383]
I checked the documentation in detail and didn't find the rsync address for the Termux apt repository. Could you tell me how to create a mirror of it?

**Comment by Grimler91** [comment]
Rsync is currently not available for the main repository, but syncing can be done with tools like [aptly](https://www.aptly.info/doc/aptly/mirror/) or [apt-mirror.pl](https://github.com/kimmel/apt-mirror-fork)

**Comment by Noble12345** [comment]
Jaspernation command

**Comment by Noble12345** [comment]
Command

**Comment by Grimler91** [comment]
Steps for rsync, apt-mirror and aptly are now outlined in https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories
