### ISSUE TITLE
sys/limits.h

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#939]
I got this error even after building libandroid-support:

`grep: /data/data/com.termux/files/usr/include/sys/limits.h: No such file or directory`

Any ideas? Thanks!

**Comment by fornwall** [comment]
When do you get that error?

The platform headers are in `$TERMUX_STANDALONE_TOOLCHAIN/sysroot/usr/include/`.

**Comment by Wetitpig** [comment]
Oh. Not in the $TERMUX_PREFIX directory?

Then are the other headers also in this directory?

**Comment by fornwall** [comment]
- The headers provided by the NDK toolchain (that is, basic OS/POSIX headers), exposing functionality in the Android base system, are in the toolchain dir as shown above.

- The headers for additional packages not part of the Android platform (that is, everything else, e.g. png/openssl/curl/...), are under `$TERMUX_PREFIX/include`.

**Comment by Wetitpig** [comment]
Thanks!
