### ISSUE TITLE
[Bug]: rtorrent won't start

### ISSUE THREAD

**Issue by Bobabadabouskie** [termux/termux-packages#9406]
### Problem description

rtorrent won't start with error "cannot link executable"

https://imgur.com/a/TbMJ9ze

### What steps will reproduce the bug?

Not sure exactly. I get an error on a fresh install, after updating. My device is a Samsung Galaxy Note 8(SM-950U), Android version 9

### What is the expected behavior?

rtorrent starts and runs without issue 

### System information

termux-info:

```
$ termux-info
Application version:
0.118.0
Packages CPU architecture:                                 aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.153-23487843 #2 SMP PREEMPT Wed Feb 2 18:33:51 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N950U
```

**Comment by xtkoba** [comment]
Please refrain from using external uploader services and instead attach every necessary file here.

The issue itself will be fixed shortly.
