### ISSUE TITLE
[Bug]: old tool still running in new session

### ISSUE THREAD

**Issue by Saif8847** [termux/termux-packages#9419]
### Problem description

Please help me out whenever i open or start new session still old tool like $ zphisher: is running ??? How to fix every  time i have to close all sessions and restart app

### What steps will reproduce the bug?

Do not know

### What is the expected behavior?

working fine but annoyong

### System information

termux-info:

```

```~/seeker $ termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.186-01657-g9821cae2a290-dirty #1 SMP PREEMPT Sat Dec 18 19:59:31 CST 2021 aarch64 Android
Device manufacturer:
TECNO MOBILE LIMITED
Device model:
TECNO CH6h
~/seeker $

**Comment by xtkoba** [comment]
It's normal for daemon processes. Ask the maintainer of the tool how to stop it or try

```
$ pkill process_name_of_the_tool
```

**Comment by Saif8847** [comment]
Bro still waiting for your reply

**Comment by sk0kanik** [comment]
zphisher is a phishing tool. Before using it you should read https://wiki.termux.com/wiki/Hacking
> "if you decide to use Termux for hacking purposes, you agree that you are on your own. We will not assist you in fixing issues, whether or not related to your activity. Termux staff and community are not responsible for all your hacking troubles, lost data, broken devices and other damage caused by your usage of Termux."
