### ISSUE TITLE
[Bug]: ruby 2.7.0   dlopen failed: library "libssl.so.1.1" not found

### ISSUE THREAD

**Issue by zswlxx** [termux/termux-packages#9422]
### Problem description

> gem sources -l                                                                                  
ERROR:  Loading command: sources (LoadError)
	dlopen failed: library "libssl.so.1.1" not found - /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/openssl.so
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

### What steps will reproduce the bug?

pkg update
gem sources -l  

### What is the expected behavior?

gem sources -l  

### System information

termux-info:

```
termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/termux-packages-24 stable main
Updatable packages:
ruby/stable 3.1.0-2 aarch64 [upgradable from: 2.7.2]
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Mon Dec 13 11:44:35 CST 2021 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
VOG-AL10

```

**Comment by xtkoba** [comment]
Update your `ruby` package.
