### ISSUE TITLE
[Bug]: pulseaudio It doesn't work 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-packages#9443]
### Problem description

Pulseaudio does not work

### What steps will reproduce the bug?

![Screenshot_20220317-081917](https://user-images.githubusercontent.com/64093255/158817601-36324b71-a87d-4c35-8def-4eba6fada52f.png)

### What is the expected behavior?

```bash
W: [pulseaudio] core.c: Failed to allocate shared posix-shm memory pool. Falling back to a normal memory pool.
E: [pulseaudio] ltdl-bind-now.c: Failed to open module /data/data/com.termux/files/usr/lib/pulse-14.2/modules/module-sles-sink.so: dlopen failed: cannot locate symbol "ucnv_open_58" referenced by "/system/lib/libmedia.so"...
E: [pulseaudio] module.c: Failed to open module "module-sles-sink".
```

Because of this, the audio does not work, it is broken. 

### System information

termux-info:

```
Application version:
0.118.0+b94dc7e
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.71-perf-gb847930 #1 SMP PREEMPT Fri Sep 27 14:15:01 CDT 2019 armv7l Android
Device manufacturer:
motorola
Device model:
moto e5 cruise
```

**Comment by xtkoba** [comment]
Do you set `LD_LIBRARY_PATH`? (Smells somewhat similar to #9174.)

**Comment by Yisus7u7** [comment]
> Do you set `LD_LIBRARY_PATH`? (Smells somewhat similar to #9174.)

![Screenshot_20220317-083726](https://user-images.githubusercontent.com/64093255/158820483-7f9fdb9e-b837-4f9a-af9f-d741ab94e4ee.png)

**Comment by Yisus7u7** [comment]
> 

Thanks, it works!
