### ISSUE TITLE
Package request: Electrum

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#945]
Electrum is a bitcoin wallet. It's about the only maintained bitcoin wallet available in terminal.
You can run a text-only mode with `--gui=text`. But it doesn't work on Termux. I tried installing it with pip2. The program checks for "$ANDROID_DATA" and tries to do additional stuff (I guess in case it's run as part of the official Android app). 
`unset ANDROID_DATA` just leads to exceptions.

**Comment by bitcoinmeetups** [comment]
I second this. Electrum on Termux would be cool. I think Vishal may know how to do it.

**Comment by Neo-Oli** [comment]
This should work for installing Electrum with pip. 
```
wget -N https://github.com/spesmilo/electrum/archive/master.tar.gz #or the current stable
tar -xf *.tar.gz
cd electrum-*
find -type f| xargs sed "s|'ANDROID_DATA' in os.environ|False|g" -i
pip2 install .
```
Now you can create a wallet with `electrum create` and start the gui with `electrum --gui=text`

Unfortunately the Text Gui is full of bugs at the moment (https://github.com/spesmilo/electrum/issues/2354), with crashes being frequent. I did however manage to scan the QR code at a train station ticket machine and charge my wallet. I was also able to make a payment to @fornwall. So the basic functionality works. 

I'd still like to see it as a package in termux so it's easier to install.

**Comment by vishalbiswas** [comment]
I have no idea how to package python-based programs. So, I'm posting steps required to install this:

1) Clone the electrum repo.
`git clone https://github.com/spesmilo/electrum`
2) Change to cloned directory
`cd electrum`
3) Install dependencies
`pip2 install dnspython pyaes ecdsa requests six pbkdf2 jsonrpclib`
`apt install protobuf`
4) Compile protobuf description file
`protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto`
5) Apply this patch
```patch
diff --git a/electrum b/electrum
index b9ab196..39f3784 100755
--- a/electrum
+++ b/electrum
@@ -1,4 +1,4 @@
-#!/usr/bin/env python2
+#!/data/data/com.termux/files/usr/bin/env python2
 # -*- mode: python -*-
 #
 # Electrum - lightweight Bitcoin client
@@ -46,7 +46,7 @@ if jnius:
 script_dir = os.path.dirname(os.path.realpath(__file__))
 is_bundle = getattr(sys, 'frozen', False)
 is_local = not is_bundle and os.path.exists(os.path.join(script_dir, "setup-release.py"))
-is_android = 'ANDROID_DATA' in os.environ
+is_android = False

 # move this back to gui/kivy/__init.py once plugins are moved
 os.environ['KIVY_DATA_DIR'] = os.path.abspath(os.path.dirname(__file__)) + '/gui/kivy/data/'
diff --git a/lib/bitcoin.py b/lib/bitcoin.py
index 6863a2f..f39b241 100644
--- a/lib/bitcoin.py
+++ b/lib/bitcoin.py
@@ -264,7 +264,7 @@ def i2o_ECPublicKey(pubkey, compressed=False):
 ############ functions from pywallet #####################

 def hash_160(public_key):
-    if 'ANDROID_DATA' in os.environ:
+    if False:
         from Crypto.Hash import RIPEMD
         md = RIPEMD.new()
     else:
diff --git a/lib/util.py b/lib/util.py
index 2c2201c..c65a348 100644
--- a/lib/util.py
+++ b/lib/util.py
@@ -150,7 +150,7 @@ class DaemonThread(threading.Thread, PrintError):
             self.running = False

     def on_stop(self):
-        if 'ANDROID_DATA' in os.environ:
+        if False:
             import jnius
             jnius.detach()
             self.print_error("jnius detach")
@@ -237,13 +237,13 @@ def android_check_data_dir():
     return data_dir

 def get_headers_path(config):
-    if 'ANDROID_DATA' in os.environ:
+    if False:
         return android_headers_path()
     else:
         return os.path.join(config.path, 'blockchain_headers')

 def user_dir():
-    if 'ANDROID_DATA' in os.environ:
+    if False:
         return android_check_data_dir()
     elif os.name == 'posix':
         return os.path.join(os.environ["HOME"], ".electrum")
```
6) Install electrum
`python2 ./setup.py install`
7) Run with
`electrum --gui=text`

**Comment by its-pointless** [comment]
Iv got (bad) ways of distributing pythion modules. As far as i can work out there is no real clean method.

**Comment by bitcoinmeetups** [comment]
It would be good if Electrum were a package for easier installation

**Comment by Kylelyle** [comment]
git clone https://github.com/pyca/pynacl && cd pynacl # replace all occurences of /bin/sh with /data/data/com.termux/files/usr/bin/sh find . -type f -not -path '*/\.*' -exec sed -i 's%/bin/sh%/data/data/com.termux/files/usr/bin/sh%g' {} \; #replace python with python2 for python2 python setup.py install

**Comment by xeffyr** [comment]
Package available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install electrum
```
