### ISSUE TITLE
[Bug]: github actions: gst-plugins-bad not compiling

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#9459]
### Problem description

```
/home/builder/.termux-build/_cache/android-r23b-api-24-v8/bin/../sysroot/usr/include/GLES3/gl3platform.h:28:10: fatal error: 'KHR/khrplatform.h' file not found
#include <KHR/khrplatform.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
[493/728] Compiling C object sys/nvcodec/libgstnvcodec.so.p/gstnvenc.c.o
ninja: build stopped: subcommand failed.
```
[action](https://github.com/Maxython/termux-packages-pacman/actions/runs/2002809337)

### What steps will reproduce the bug?

Auto update

### What is the expected behavior?

Successful compilation

### System information

This is github action.

**Comment by xtkoba** [comment]
I wonder if `gst-plugins-bad` should move to x11 repo.
