### ISSUE TITLE
ImageMagick stopped working 

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/termux-packages#9470]
### Problem description

After an update today, ImageMagick stopped working 

### What steps will reproduce the bug?

When I type `magick` command 

![Screenshot_2022_0320_144045](https://user-images.githubusercontent.com/87801676/159151401-11524f6b-cec7-4c25-a48d-ddfe4ba83808.jpg)

### What is the expected behavior?

It would show options 

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main/ stable main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.19.95-perf+ #1 SMP PREEMPT Thu Jan 13 11:39:56 CST 2022 aarch64 Android
Device manufacturer:
vivo
Device model:
V2027
```

**Comment by xtkoba** [comment]
Ah I should have taken care of leaked libunwind symbols also, not only compiler-rt builtins.

Simply rebuilding `libheif` once again should fix the issue, but it is highly probable that other packages are also affected. I will look into this soon.
