### ISSUE TITLE
Why SBCL only exists in disabled-packages, how to install it with apt?

### ISSUE THREAD

**Issue by muyinliu** [termux/termux-packages#948]
I'm glad that Emacs can run on Android with Termux, but I find that SBCL can not be install through command `apt install sbcl`. Why?

**Comment by fornwall** [comment]
The `disabled-packages/` folder in general is for packages which doesn't build or work yet, so the packages are not available for installation. So for SBCL to progress someone needs to spend time on getting it to work (you can track https://github.com/termux/termux-packages/issues/183 for progress on that).

**Comment by francogrex** [comment]
I also vote for SBCL on termux!
