### ISSUE TITLE
CANNOT LINK EXECUTABLE "gtk-query-immodules-3.0": cannot locate symbol "__floatunsitf" referenced by "/data/data/com.termux/files/usr/lib/libgtk-3.so"...

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#9487]
In the last update, I ran `apt upgrade` and got this:

```
Setting up imagemagick (7.1.0.16-3) ...
Setting up tigervnc (1.10.1-22) ...
Setting up pulseaudio-glib (14.2-8) ...
Setting up sdl2 (2.0.20-2) ...
Setting up qt5-qtlocation (5.15.3) ...
Setting up qt5-qtmultimedia (5.15.3) ...
Setting up qt5-qtsensors (5.15.3) ...
Setting up pulseaudio-static (14.2-8) ...
Setting up qemu-system-x86-64 (1:6.1.0-9) ...
Processing triggers for man (1.14.5-3) ...
Processing triggers for gdk-pixbuf (2.42.6-3) ...
Processing triggers for gtk3 (3.24.24-6) ...
CANNOT LINK EXECUTABLE "gtk-query-immodules-3.0": cannot locate symbol "__floatunsitf" referenced by "/data/data/com.termux/files/usr/lib/libgtk-3.so"...
Aborted
Processing triggers for gtk2 (2.24.32-35) ...
Processing triggers for desktop-file-utils (0.26-7) ...
Processing triggers for shared-mime-info (2.1-6) ...

```﻿

**Comment by Yonle** [comment]
Doing `apt reinstall gtk3` reproducing the issue

![Screenshot_2022_0321_064744](https://user-images.githubusercontent.com/63401712/159191261-30d57911-e1a5-40b2-9c6b-c0af409186f8.png)

**Comment by xtkoba** [comment]
Due to `gtk3` depending on `fontconfig`:

```
$ readelf -Wa lib/libgtk-3.so|grep '(NEEDED)'|grep fontconfig
 0x0000000000000001 (NEEDED)             Shared library: [libfontconfig.so]
```

Just rebuilding `gtk3` should fix the issue.

I expect that this can affect other packages that link against `libfontconfig.so` but do not include `fontconfig` in `TERMUX_PKG_DEPENDS`. I did not care for those packages.

**Comment by xtkoba** [comment]
To search for aarch64 binaries that rely on (previously) leaked builtins:

```bash
for f in $(find . ! -name '*.a'); do if readelf -Wa $f 2>/dev/null | \
grep " UND __.*[icf][234]$
 UND __aarch64_
 UND __atomic_
 UND __float.*f$
 UND __fix.*i$"; then echo === $f ===; fi; done
```

Note that there can be false positives.

Honestly I cannot do the exhaustive search. I need your help. Thanks!

**Comment by mguinhos** [comment]
This is very urgent, some xfce4 packages install are broken due to this! Cant we revert the gtk3 update?

**Comment by xtkoba** [comment]
@mguinhos Simply rebuilding the affected packages should fix the issue. Please tell me which packages are affected, or alternatively make PRs to revbump those packages. Thanks!

**Comment by mguinhos** [comment]
Okay!

**Comment by mguinhos** [comment]
What caused this symbols to be inserted in the executables? Just a wrong config in the termux-packages build system?

**Comment by xtkoba** [comment]
Older NDK did. Now I am trying to purge them all.

**Comment by xtkoba** [comment]
The specific issue for `gtk3` should be fixed with version `3.24.24-7`. Please wait for the package to be uploaded.

**Comment by st0rmc4non** [comment]
Now I see

**Comment by xtkoba** [comment]
OK, `gtk3` version `3.24.24-7` has been uploaded to packages.termux.org. If you encounter a similar problem after updating your `gtk3` package, then feel free to open a new issue. Thanks.
