### ISSUE TITLE
termux-open / xdg-open: support for apk files? 

### ISSUE THREAD

**Issue by conrad-heimbold** [termux/termux-packages#949]
When downloading / building / editing apk files inside termux' home directory, it would be cool; if you could also open them afterwards inside there via xdg-open or termux-open . 

For example, I just had to zipalign com.termux.window_9.apk from F-Droid, because I couldn't install it directly from F-Droid. 

Thanks in advance!

**Comment by fornwall** [comment]
Opening an .apk with xdg-open/termux-open seems to work already for Android 7.0 or later, see http://stackoverflow.com/questions/39147608/android-install-apk-with-intent-view-action-not-working-with-file-provider where a possible workaround for previous android versions is mentioned (use file uri).
