### ISSUE TITLE
finch has no protocol plugins installed

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#95]
Hi. I tried to run finch but it gives me the following error. 
![capture](https://cloud.githubusercontent.com/assets/7983745/11871038/e8f3f7b4-a4cc-11e5-908b-38bef905cb6d.PNG)

I don't think these plugins are supposed to be missing. I installed finch on ubuntu and it came with a whole lot of protocols. I also didn't find a way to install them manually.

**Comment by fornwall** [comment]
Under `$PREFIX/lib/purple-2/` there are a bunch of shared libraries available:

    libaim.so
    libicq.so
    libirc.so
    [...]

I guess these are the protocol plugins. Using `strace` on finch shows that the process opens these files, but for some reason it doesn't load the plugins (perhaps `dlopen` fails)?

**Comment by fornwall** [comment]
Using debug logging, `finch -d > log.txt`, reveals:

    plugins: probing /data/data/com.termux/files/usr/lib/purple-2/libirc.so
    plugins: /data/data/com.termux/files/usr/lib/purple-2/libirc.so is not loadable:
                 dlopen failed: cannot locate symbol "purple_find_conversation_with_account"
                 referenced by "libirc.so"...

**Comment by fornwall** [comment]
The code that fails is in `libpurple/plugin.c`:

    /*
     * We pass G_MODULE_BIND_LOCAL here to prevent symbols from
     * plugins being added to the global name space.
     *
     * G_MODULE_BIND_LOCAL was added in glib 2.3.3.
     */
     plugin->handle = g_module_open(filename, G_MODULE_BIND_LOCAL);

It uses [glib dynamic module loading](http://developer.gimp.org/api/2.0/glib/glib-Dynamic-Loading-of-Modules.html).

**Comment by Neo-Oli** [comment]
I also get the error "WARNING: linker: Unsupported flags DT_FLAGS_1=0x9" when I launch finch. Maybe this is related?

**Comment by Neo-Oli** [comment]
The "WARNING: linker: Unsupported flags DT_FLAGS_1=0x9" has since been resolved by I think 035e27f, but the problem still persists.

**Comment by fornwall** [comment]
@Neo-Oli Try now how finch works!

**Comment by Neo-Oli** [comment]
It now is able to load 3 protocols, simple, irc, and gadu-gadu. But it's still unable to load some of the more important protocols, like xmpp.
```
(12:58:46) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/libxmpp.so
(12:58:46) plugins: /data/data/com.termux/files/usr/lib/purple-2/libxmpp.so is not loadable: dlopen failed: library "libjabber.so.0" not found
```
Can these libraries not be loaded, or are they simply missing?

**Comment by fornwall** [comment]
> It now is able to load 3 protocols, simple, irc, and gadu-gadu. But it's still unable to load some of the more important protocols, like xmpp.
>
> Can these libraries not be loaded, or are they simply missing?

They were only in `$PREFIX/lib/purple-2`, where the Android linker could not find them. I put symlinks to them in `$PREFIX/lib` so they should work - install the updated `2.10.12-2` package and try again!

**Comment by Neo-Oli** [comment]
That's great, now I can see them all. I however still can't connect to any of my accounts because all of them require TLS/SSL.
`09:10:08 jabber: No libpurple TLS/SSL support found.`

```
$ grep 'ssl\|tls' log.txt
(09:10:03) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/ssl-gnutls.so
(09:10:03) plugins: /data/data/com.termux/files/usr/lib/purple-2/ssl-gnutls.so is not loadable: dlopen failed: cannot locate symbol "purple_ssl_get_ops" referenced by "/data/data/com.termux/files/usr/lib/purple-2/ssl-gnutls.so"...
(09:10:03) plugins: probing /data/data/com.termux/files/usr/lib/purple-2/ssl.so
(09:10:03) plugins: /data/data/com.termux/files/usr/lib/purple-2/ssl.so is not loadable: dlopen failed: cannot locate symbol "purple_plugins_get_loaded" referenced by "/data/data/com.termux/files/usr/lib/purple-2/ssl.so"...
(09:10:04) certificate: CertificatePool x509, tls_peers requested but not found.
(09:10:04) certificate: CertificatePool tls_peers registered
(09:10:04) certificate: CertificateVerifier x509, tls_cached requested but not found.
(09:10:04) certificate: CertificateVerifier tls_cached registered
(09:10:04) sslconn: Unable to initialize SSL.
```

**Comment by fornwall** [comment]
@Neo-Oli Ok, a fix for ssl was now done - update again :)!

**Comment by Neo-Oli** [comment]
@fornwall That's great. Now I can finally connect to Google Talk properly, and do not have to rely on Python Hangups (which is unstable, at best). 

At the moment I am trying to compile the otr plugin, which is apparently a whole other can of worms.  
`/data/data/com.termux/files/usr/bin/ld: cannot find -lpthread`

But I am happy that there is now a solution for xmpp on termux.
