### ISSUE TITLE
[Bug]: findutils does not work with -fstype since 4.9.0

### ISSUE THREAD

**Issue by gustav-b** [termux/termux-packages#9506]
### Problem description

Since `findutils` was [upgraded to 4.9.0](https://github.com/termux/termux-packages/commit/c440298f3d3e9ff015795a9b59f82a7741110390), `find` exits with an error whenever an `-fstype` argument is given.

### What steps will reproduce the bug?

Run `find` with an `-fstype` argument, the value given to it doesn't matter:

```sh
$> find . -fstype f2fs
find: Cannot read mounted file system list
```
![Screenshot_20220321-213704](https://user-images.githubusercontent.com/368219/159361142-74decf6b-79e6-4f6a-a1f3-70c626552810.png)

### What is the expected behavior?

I expect `find` to list the files without an error, as it did in 4.8.0.

![Screenshot_20220321-213610](https://user-images.githubusercontent.com/368219/159361224-1796f306-8bcf-4b0e-bc51-5f630306ba0b.png)

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.astra.in.ua/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 5.10.43-android12-9-00001-g3b35c4eea2da-ab7739787 #1 SMP PREEMPT Thu Sep 16 20:17:47 UTC 2021 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 6
```

**Comment by Grimler91** [comment]
Seem to be a new issue with 4.9.0. Building 4.9.0 on device still returns `Cannot read mounted file system list`, but 4.8.0 built on device works
