### ISSUE TITLE
Why is the library missing?

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#951]
Even after building `libbz2` and installing `libbz2-1.0`, I still got this error:

`/root/.termux-build/_lib/toolchain-i686-ndk14-api21-v17/bin/i686-linux-android-ld: error: cannot find -lbz2`

Why can't the linker find the library? Thanks!

**Comment by fornwall** [comment]
Can you give more steps how to reproduce your problem? What commands are you running?

**Comment by Wetitpig** [comment]
I have run the `setup-ubuntu.sh` and installed libbz2-1.0 with libbz2-dev.

Then I started running `build-all.sh`, with a new package being tested. The package's dependencies include libbz2. It is a crucial part and must not be disabled. When `build-package.sh` tried to buils the package, the package failed.

**Comment by Wetitpig** [comment]
Problem solved by using: `-l:$PREFIX/lin/libbz2.so`.
