### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "shellcheck": library "libHSprocess-1.6.13.2-ghc8.10.7.so" not found: needed by main executable

### ISSUE THREAD

**Issue by errr-maxx** [termux/termux-packages#9510]
### Problem description

`shellcheck` output:
`CANNOT LINK EXECUTABLE "shellcheck": library "libHSprocess-1.6.13.2-ghc8.10.7.so" not found: needed by main executable`

### What steps will reproduce the bug?

Run `shellcheck`

### What is the expected behavior?

No link errors

### System information

termux-info:

```
Application version:
0.118.0+caa13b7
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Feb 10 17:02:37 CST 2022 aarch64 Android
Device manufacturer:
realme
Device model:
RMX2155
```

**Comment by Grimler91** [comment]
I can't reproduce the issue on my aarch64 device. 

What does `find $PREFIX/lib -name libHSprocess-1.6.13.2-ghc8.10.7.so` return?

What does `readelf -Wa $PREFIX/bin/shellcheck | grep PATH` return?

**Comment by errr-maxx** [comment]
`find $PREFIX/lib -name libHSprocess-1.6.13.2-ghc8.10.7.so` returns nothing

`readelf -Wa $PREFIX/bin/shellcheck | grep PATH` outputs: `0x000000000000001d (RUNPATH)            Library runpath: [/home/builder/.termux-build/shellcheck/src/dist/build:/data/data/com.termux/files/usr/lib:/data/data/com.termux/files/usr/lib/aarch64-android-ghc-8.10.7:/data/data/com.termux/files/usr/lib/ghc-8.10.7/process-1.6.13.2:/data/data/com.termux/files/usr/lib/ghc-8.10.7/parsec-3.1.14.0:/data/data/com.termux/files/usr/lib/ghc-8.10.7/directory-1.3.6.0:/data/data/com.termux/files/usr/lib/ghc-8.10.7/filepath-1.4.2.1:/data/data/com.termux/files/usr/lib/ghc-8.10.7/stm-2.5.0.1:/data/data/com.termux/files/usr/lib/ghc-8.10.7/unix-2.7.2.2:/data/data/com.termux/files/usr/lib/ghc-8.10.7/time-1.9.3:/data/data/com.termux/files/usr/lib/ghc-8.10.7/mtl-2.2.2:/data/data/com.termux/files/usr/lib/ghc-8.10.7/transformers-0.5.6.2:/data/data/com.termux/files/usr/lib/ghc-8.10.7/text-1.2.4.1:/data/data/com.termux/files/usr/lib/ghc-8.10.7/template-haskell-2.16.0.0:/data/data/com.termux/files/usr/lib/ghc-8.10.7/ghc-boot-th-8.10.7:/data/data/com.termux/files/usr/lib/ghc-8.10.7/binary-0.8.8.0:/data/data/com.termux/files/usr/lib/ghc-8.10.7/containers-0.6.5.1:/data/data/com.termux/files/usr/lib/ghc-8.10.7/bytestring-0.10.12.0:/data/data/com.termux/files/usr/lib/ghc-8.10.7/pretty-1.1.3.6:/data/data/com.termux/files/usr/lib/ghc-8.10.7/deepseq-1.4.4.0:/data/data/com.termux/files/usr/lib/ghc-8.10.7/array-0.5.4.0:/data/data/com.termux/files/usr/lib/ghc-8.10.7/base-4.14.3.0:/data/data/com.termux/files/usr/lib/ghc-8.10.7/integer-gmp-1.0.3.0:/data/data/com.termux/files/usr/lib/ghc-8.10.7/ghc-prim-0.6.1:/data/data/com.termux/files/usr/lib/ghc-8.10.7/rts:/data/data/com.termux/files/usr/lib]`

**Comment by Grimler91** [comment]
Seems that your ghc-libs package is broken then, the file is in that package:

```
$ apt download ghc-libs
$ dpkg -c ghc-libs_8.10.7_aarch64.deb | grep libHSprocess-1.6.13.2-ghc8.10.7.so
-rwx------ builder/builder   294952 2022-03-09 03:36 ./data/data/com.termux/files/usr/lib/ghc-8.10.7/process-1.6.13.2/libHSprocess-1.6.13.2-ghc8.10.7.so
```

Try reinstalling it

**Comment by errr-maxx** [comment]
`dpkg -c ghc-libs_8.10.7-1_aarch64.deb | grep libHSprocess-1.6.13.2-ghc8.10.7.so` returns nothing for me

Reinstalling didn't work

**Comment by hantraxer0craft** [comment]
I have the same problem in my arm64 phone

**Comment by Grimler91** [comment]
Aha, my bad, I haven't upgraded to 8.10.7-1, libraries seem to be missing from that version indeed (ping @MrAdityaAlok)
