### ISSUE TITLE
Emacs: error "Failed select: Invalid argument".

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#952]
I upgraded emacs to 25.2 and am now unable to use it. The error appears only on my (arm) tablet though, emacs (25.2) on my (arm) phone works fine. 

I'm unable to use the minibuffer and have to use the menu buttons to exit. See the screenshot below: 

![screenshot_2017-04-22-11-36-34_downsized](https://cloud.githubusercontent.com/assets/18900601/25303683/5bd11960-2758-11e7-854d-9b81edf535a5.png)

The messages are:

```
Loading buff-menu...done
Loading emacs-lisp/float-sup...done
Loading vc/vc-hooks...done
Loading vc/ediff-hook...done
Loading uniquify...done
Loading electric...done
Loading emacs-lisp/eldoc...done
Loading cus-start...done
Loading tooltip...done
Loading /data/data/com.termux/files/usr/share/emacs/25.2/lisp/leim/leim-list.el (source)...done
Finding pointers to doc strings...done
Loading /data/data/com.termux/files/usr/share/emacs/25.2/lisp/emacs-lisp/site-init.el (source)...done
xterm--query: Failed select: Invalid argument
Failed select: Invalid argument [324 times]
M-[ > is undefined
Failed select: Invalid argument [1911 times]
user-error: Minibuffer window is not active
Failed select: Invalid argument [1014 times]
Making completion list...
completing-read-default: Failed select: Invalid argument [1632 times]
apply: Failed select: Invalid argument [891 times]
Grep exited abnormally with code 2
Failed select: Invalid argument [7883 times]
Making completion list...
completing-read-default: Failed select: Invalid argument [2973 times]
apply: Failed select: Invalid argument [328 times]
Failed select: Invalid argument [5 times]
Grep exited abnormally with code 2
Failed select: Invalid argument [4233 times]
Failed select: Invalid argument
```

What I've tried so far:

- removing all my custom settings in ~/.emacs.d/ 
- restarting tablet
- uninstalling and installing emacs
- downgrading emacs to 25.1

But with no success. 
Please let me know if I can provide anymore information.

**Comment by Grimler91** [comment]
I guess I'm alone with this problem. At least I finally have a reason to learn vim...

**Comment by fornwall** [comment]
I'm unable to reproduce this - any help from someone more knowledgeable in emacs would be appreciated!

**Comment by Grimler91** [comment]
The problem persists after reinstallation of termux as well, so it can't be due to any local termux settings. 

I'm using a samsung s2 (T800) tablet with (custom rom) android 5.0.2.

**Comment by stuart-little** [comment]
I am encountering the same issue on an Allview A5 Quad Plus with Android 5.1. I cannot see a list of all of the messages, as they flash very quickly in a minibuffer at the bottom of the screen. What I can confirm though is that emacs gets stuck in an unusable state (displaying "failed select: invalid argument" in the minibuffer), puts my phone into an endless vibration mode, and renders all of termux unresponsive. 

Reinstalling either emacs or termux did not fix the problem. 

On the other hand, the same emacs 25.2 package runs fine in termux on an old Nexus 4 running LineageOS 14.1 (based on Android 7.1.1).

**Comment by vishalbiswas** [comment]
I'm affected, too. Looks like a Lollipop issue.

@stuart-little you can `Ctrl-Z` and kill emacs manually.

**Comment by Grimler91** [comment]
@stuart-little Pressing the minibuffer a couple of times and then pressing enter brings up the message log. (Or something like that, can't remember exactly how)

@vishalbiswas ctrl + z does not work, I think that whatever is jamming emacs sends a command in between so the commands turns into Ctrl + "some other signal" + z

Also, as Stuart said, if vibration (hapatic feedback) is enabled, the tablet vibrates conatantly and becomes  unresponsive and has to be restarted (exiting/killing termux doesn't work).

**Comment by vishalbiswas** [comment]
@Grimler91 I can actually `Ctrl+Z` even with continuous vibration feedback

**Comment by stuart-little** [comment]
Ctrl+Z does work, thank you! Actually, it's a bit embarrassing I hadn't tried it; I do use it in terminals generally..

In any event, other attempts at fixing the problem have also not worked (commenting out various lines in loadup.el and other config files).

**Comment by vishalbiswas** [comment]
@stuart-little don't worry. I've already sent in #956

**Comment by fornwall** [comment]
Thanks to @vishalbiswas there is now an updated `25.2-1` version of the emacs package available which should fix this issue, just an `packages upgrade` away!

**Comment by stuart-little** [comment]
This fixed it for me. Thank you very much!
