### ISSUE TITLE
(gdb) Disassembly-Flavor Intel?

### ISSUE THREAD

**Issue by ChampionLeake** [termux/termux-packages#954]
I noticed when using the (gdb) there is no other way to change your disassembly-flavor to Intel. I've searched and navigated through the help command. 

Is there way to use the set disassembly-flavor Intel command like Unix on linux? The default debugging is a bit complicated and the Intel disassembly is more efficient for me. Please respond if anyone has any idea on how to set the disassembly tool to Intel

**Comment by fornwall** [comment]
AFAIK note you disassembly-flavor is only supported/defined on x86. If you are running on an arm device it's not supported. Could this be the case here?

**Comment by AbdulConsole** [comment]
Any Solution Yet?
