### ISSUE TITLE
No se puede conectar al servidor local a través del socket

### ISSUE THREAD

**Issue by gabrielorjuela09** [termux/termux-packages#9547]
### Problem description

El problema es queno me deja iniciar cuando pongo estos comandos comqmysql_upgrade,myqsl,mysql_install_db. segun por que no puede conectarse con el servidor local

### What steps will reproduce the bug?

ERROR 2002 (HY000): No se puede conectar al servidor local a través del socket '/data/data/com.termux/files/usr/var/run/mysqld.sock' (111)

### What is the expected behavior?

Que iniciará el servicio sin problema

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.190 #1 SMP PREEMPT Tue May 11 02:12:43 IST 2021 armv7l Android
Device manufacturer:
LGE
Device model:
LM-X525
```

**Comment by xtkoba** [comment]
Invalid because the description is not written in English.

**Comment by Grimler91** [comment]
Also seems like a duplicate of for example https://github.com/termux/termux-packages/issues/3750, based on error code
