### ISSUE TITLE
Can't install and update any package 

### ISSUE THREAD

**Issue by Aakashj4044** [termux/termux-packages#9564]
![Uploading Screenshot_20220325_214412.jpg…]()

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/6726

**Comment by Aakashj4044** [comment]
Thank you!

**Comment by Aakashj4044** [comment]
This problem can be solved one new problem face in ngrox i have sucessful
install ngrox but i sent a link victim error 3200 show please help me solve
this problem.....
Regards
Ethical_hacker.aakash
