### ISSUE TITLE
[Package]: whois

### ISSUE THREAD

**Issue by monoidic** [termux/termux-packages#9565]
### Package description

The whois client provided at https://github.com/rfc1036/whois is far superior to the one provided by inetutils. It is capable of providing whois information on domains under far more TLDs.
A small sample of domains for which the inetutils version of whois fails entirely while the improved version succeeds:
* internet.ee
* youtu.be
* sitt.link

It is maintained by a Debian developer and included in the repositories of major Linux distributions, and very small in package size. A quick `apt-file search bin/whois` on up-to-date Debian and Ubuntu machines seems to indicate that both of those distros only uses this verison of whois and not the inetutils version.

Alternatively, I noticed that the version of Busybox shipped with Termux is compiled with whois support. `busybox whois <domain>`, though a bit slow and with a couple of extra lines of unnecessary info, worked for the three test domains I listed above. Hence, I'd see removing the whoisbinary from inetutils and keeping a `whois -> busybox` symlink there instead as a preferred alternative to shipping the inetutils version of whois.

### Source code URL

https://github.com/rfc1036/whois

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
BTW, what is the best way to resolve the conflict with `inetutils`? There are several candidates: to remove, to rename (to what?), to use update-alternatives, ...

**Comment by monoidic** [comment]
Remove, as the `inetutils` variant is inferior to the requested variant and even the busybox module. It does not seem like Ubuntu or Debian even ships the `inetutils` variant at all.

**Comment by ChiefMikeK** [comment]
@xtkoba please update command-not-found. 
it is telling me to install inetutils!

**Comment by FreeGuye** [comment]
Use this _

pkg i whois

**Comment by FreeGuye** [comment]
> BTW, what is the best way to resolve the conflict with `inetutils`? There are several candidates: to remove, to rename (to what?), to use update-alternatives, ...

Use this _ 

pkg i whois
