### ISSUE TITLE
[Bug]: nsis: wrong prefix in buildscript

### ISSUE THREAD

**Issue by tempaccforissue** [termux/termux-packages#9583]
### Problem description

If I install `nsis` and run `makensis --help`, it shows:
`Error: reading stub "/data/data/com.termux/files/usr/opt/Stubs/zlib-x86-unicode"
Error initalizing CEXEBuild: error setting default stub`

Seems like the Stubs, Plugins and other necessary files need to be in the `$PREFIX/opt` directory instead of `$PREFIX/opt/nsis`. If I download and put those files in the `opt` directory, it runs successfully, but if those are in `opt/nsis`, then the error comes. I think it may be fixed by changing [this](https://github.com/termux/termux-packages/blob/61e350af627573c3c9255b701018bd3dfcf3c191/packages/nsis/build.sh#L25) line to
`PREFIX="$TERMUX_PREFIX/opt/nsis/nsis" \`
so that the Stubs and other required files can be placed in `opt/nsis` instead of `opt`

### What steps will reproduce the bug?

1. `apt install nsis -y`
2. `nsis --help`

### What is the expected behavior?

makensis should require Stubs, Plugins and other folders and files to be placed in
`/data/data/com.termux/files/usr/opt/nsis`
instead of
`/data/data/com.termux/files/usr/opt`

### System information

termux-info:

```
N/A
```

**Comment by xtkoba** [comment]
Fixed by commit e58d1df8afc6da2b1b1cb508e255944910856b62.

**Comment by tempaccforissue** [comment]
> Fixed by commit [e58d1df](https://github.com/termux/termux-packages/commit/e58d1df8afc6da2b1b1cb508e255944910856b62).

actually that didn't work. The issue persists.
