### ISSUE TITLE
[Bug]: Mencoder: Unable to convert/transcode/encode to other file format

### ISSUE THREAD

**Issue by OilSubjectLoss7** [termux/termux-packages#9588]
### Problem description

I always get an error or nothing when i try to attempt an encode/transcode operation to other file codec/format,
Copying or not changing the codec seems to work fine for a select few of format/codec like

> mpg

> vob

Like the one below:

`mencoder sample.mpg -o sample.vob -ovc copy`
`mencoder sample.vob -o sample.mpg -ovc copy`

Other format or codec are broken even with the codec untouched(`-ovc copy`)

### What steps will reproduce the bug?

Any of these produce the bugs

`mencoder sample.mkv -o sample.mpg -ovc lavc`
`mencoder sample.mkv -o sample.mpg -ovc x264`
`mencoder sample.mp4 -o sample.mpg -ovc lavc`
`mencoder sample.mp4 -o sample.mpg -ovc lavc`
`mencoder sample.mkv -o sample.vob -ovc x264`
`mencoder sample.mkv -o sample.vob -ovc lavc`

### What is the expected behavior?

Successful process, resulting a converted/transcoded/encoded files being outputted

From

> sample.mkv

> sample.mp4

To

> sample.mpg

> sample.vob

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Mon Feb 21 18:08:36 CST 2022 aarch64 Android
Device manufacturer:
Fairphone
Device model:
FP4
```

**Comment by xtkoba** [comment]
Please share the sample videos.

**Comment by OilSubjectLoss7** [comment]
> Please share the sample videos.

[samples.zip](https://github.com/termux/termux-packages/files/8358020/samples.zip)
