### ISSUE TITLE
[Bug]: Mencoder: Missing subtitle!

### ISSUE THREAD

**Issue by OilSubjectLoss7** [termux/termux-packages#9589]
### Problem description

muxing or soft embedding a vobsub(idx,sub) subtitile to a non-subbed video produce non-subbed video.

### What steps will reproduce the bug?

`mencoder -vobsub subtitle sample.mpg -o subbed_sample.mpg -ovc copy -oac copy -vobsubid 1`

Play the video, no subtitle.

### What is the expected behavior?

The process video to have subtitle inside.
A video with subtitle. A video with muxed or embedded vobsub subtitle inside

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Mon Feb 21 18:08:36 CST 2022 aarch64 Android
Device manufacturer:
Fairphone
Device model:
FP4
```

**Comment by xtkoba** [comment]
Please share the sample videos and subtitles.

**Comment by OilSubjectLoss7** [comment]
> Please share the sample videos and subtitles.

[samples.zip](https://github.com/termux/termux-packages/files/8358049/samples.zip)

**Comment by Rharfax** [comment]
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$

**Comment by xtkoba** [comment]
I doubt if this is specific to Android. I have the same result (subtitle missing from the output) on my GNU/Linux x86_64 environment (Gentoo).

Better report upstream if you are sure this is a bug.
