### ISSUE TITLE
Package request: obfsproxy

### ISSUE THREAD

**Issue by Hamza-Megahed** [termux/termux-packages#959]
hi,

since you added tor package, could you add obfsproxy package to enable bridge in tor ,or any other pluggable transport that works with tor 
Thank you

**Comment by Hamza-Megahed** [comment]
i did it with go 
go get git.torproject.org/pluggable-transports/meek.git/meek-client  for meek
go get git.torproject.org/pluggable-transports/obfs4.git/obfs4proxy for obfs3proxy
then copied them to /data/data/com.termux/files/usr/bin/
and i added this torrc

UseBridges 1
Bridge meek 0.0.2.0:1 url=https://d2zfqthxsdq309.cloudfront.net/ front=d19tqk5t6qcjac.cloudfront.net
ClientTransportPlugin meek exec /data/data/com.termux/files/usr/bin/meek-client

**Comment by tomty89** [comment]
Get `python-dev`.

**Comment by xeffyr** [comment]
Package `obfsproxy` is available via pip (python package manager).
Package `obfs4proxy` is available in [unstable-repo](https://github.com/termux/unstable-packages):
```
pkg install unstable-repo
pkg install obfs4proxy
```
