### ISSUE TITLE
Package request:openjdk-8-jdk

### ISSUE THREAD

**Issue by hepin1989** [termux/termux-packages#96]
I want to have this and then I could play with scala's repl.

**Comment by fornwall** [comment]
Hi and thanks for the suggestion! The openjdk package suggestion is noted on https://termux.com/package-suggestions.html as an input for future development - closing this issue.

**Comment by biwin** [comment]
what is the status of this request:question:

**Comment by Neo-Oli** [comment]
@biwin this probably should have been reopened when the package requests moved to issues. But https://github.com/termux/termux-packages/issues/324 covers this request as well now.

**Comment by GreenJoey** [comment]
PyPy JDK please

**Comment by sdrausty** [comment]
@hepin1989    Java is available through:
# [TermuxArch](https://github.com/sdrausty/TermuxArch)

Now you can install Arch Linux in Termux 📲 on your smartphone and tablet. More information at https://sdrausty.github.io/TermuxArch

Java is available through https://sdrausty.github.io/TermuxArch/ Just follow the easy install instructions at https://sdrausty.github.io/TermuxArch/docs/docs/install or simply copy and paste the following into your Termux window:

```
cd && git clone https://github.com/sdrausty/TermuxArch
./TermuxArch/setupTermuxArch.sh
```
Read more about the Arch Linux package manager at [duckduckgo arch+linux+install+java+pacman.](https://duckduckgo.com/?q=arch+linux+install+java+pacman&atb=v90-2__&t=cros&ia=qa)

To install java run `pacman -Syy; pacman -Su; pacman -S jdk8-openjdk`


![screenshot_20171109-220204](https://user-images.githubusercontent.com/27742457/32641053-cedfdcfe-c599-11e7-9c73-b185e70e9c6a.png)

**Comment by Fernal73** [comment]
@SDRausty So where's scala on Arch Linux on Termux?
