### ISSUE TITLE
package request: aubio

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9602]
### Package description

tool designed for the extraction of annotations from audio signals

### Home page URL

https://aubio.org/

### Source code URL

https://github.com/aubio/aubio

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Install through pip.
