### ISSUE TITLE
package request: gperf

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9603]
### Package description

A hash function generator

### Home page URL

https://www.gnu.org/software/gperf/

### Source code URL

https://github.com/yakaz/gperf

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Already packaged https://github.com/termux/termux-packages/tree/master/packages/gperf
