### ISSUE TITLE
openmp llvm

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9604]
### Package description

LLVM openmp library

### Home page URL

https://openmp.llvm.org/

### Source code URL

https://github.com/OpenMP/sources

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
We are already building [openmp as part of libllvm](https://github.com/termux/termux-packages/blob/master/packages/libllvm/build.sh#L25), and neither of the links contain buildable sources so I am not sure what is requested here.

ping @buttaface

**Comment by buttaface** [comment]
Should be working already, I tested it years back. Is it not working for you?

**Comment by xtkoba** [comment]
Not making sense to me either. `-fopenmp` should be working.
