### ISSUE TITLE
python3.9, 3.8 and 3.7

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9606]
### Package description

Python 3.10 has small issues, please add python3.9 python3.8 and python3.7 package

### Source code URL

_No Response_

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
As for all other packages we generally just provide the latest one. Having multiple versions means extra work for maintainers and "Python 3.10 has small issues" doesn't really sound like a large enough problem to motivate this.
