### ISSUE TITLE
[Bug]: downloading packages error

### ISSUE THREAD

**Issue by chopper-used** [termux/termux-packages#9608]
### Problem description

E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.                                  N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

### What steps will reproduce the bug?

pkg update

### What is the expected behavior?

Idk

### System information

termux-info:
Packages CPU architecture:                        arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-packages-24 stable main                                     # game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)      deb https://dl.bintray.com/grimler/science-packages-24 science stable                               Updatable packages:
apt/stable 2.4.1-2 arm [upgradable from: 1.4.10-2]bash/stable 5.1.16 arm [upgradable from: 5.0.18]
ca-certificates/stable 1:2022.02.01 all [upgradable from: 20200722]
command-not-found/stable 1.75 arm [upgradable from: 1.55-1]                                         coreutils/stable 9.0 arm [upgradable from: 8.32-2]
curl/stable 7.82.0 arm [upgradable from: 7.71.1]
dash/stable 0.5.11.5-1 arm [upgradable from: 0.5.11.1]
debianutils/stable 5.7 arm [upgradable from: 4.11-1]
dialog/stable 1.3-20220117-0 arm [upgradable from: 1.3-20200327-0]
diffutils/stable 3.8 arm [upgradable from: 3.7-3]
dos2unix/stable 7.4.2 arm [upgradable from: 7.4.1-1]
dpkg/stable 1.21.1-1 arm [upgradable from: 1.20.5]
ed/stable 1.18 arm [upgradable from: 1.16-1]
findutils/stable 4.9.0-1 arm [upgradable from: 4.7.0-2]
gawk/stable 5.1.1-1 arm [upgradable from: 5.1.0-1]
gpgv/stable 2.3.4 arm [upgradable from: 2.2.21]
grep/stable 3.7-2 arm [upgradable from: 3.4-1]
gzip/stable 1.11-3 arm [upgradable from: 1.10-4]
inetutils/stable 1.9.4-13 arm [upgradable from: 1.9.4-10]
less/stable 590 arm [upgradable from: 551-1]
libandroid-support/stable 28-2 arm [upgradable from: 28]
libc++/stable 23b-3 arm [upgradable from: 21d-1]
libcrypt/stable 0.2-5 arm [upgradable from: 0.2-3]
libcurl/stable 7.82.0 arm [upgradable from: 7.71.1]
libgcrypt/stable 1.9.4 arm [upgradable from: 1.8.6]
libgmp/stable 6.2.1-1 arm [upgradable from: 6.2.0-1]
libgpg-error/stable 1.43 arm [upgradable from: 1.38]
libmpfr/stable 4.1.0-1 arm [upgradable from: 4.1.0]
libnghttp2/stable 1.47.0 arm [upgradable from: 1.41.0-1]
libssh2/stable 1.10.0-2 arm [upgradable from: 1.9.0-2]
libtirpc/stable 1.3.2-1 arm [upgradable from: 1.2.6-1]
lsof/stable 4.94.0-1 arm [upgradable from: 4.93.2]
nano/stable 6.2 arm [upgradable from: 5.0]
ncurses/stable 6.3 arm [upgradable from: 6.2.20200725]
net-tools/stable 2.10.0 arm [upgradable from: 1.60.2017.02.21-3]
openssl/stable 3.0.2 arm [upgradable from: 1.1.1g-4]
pcre/stable 8.45-1 arm [upgradable from: 8.44-1]
procps/stable 3.3.17-1 arm [upgradable from: 3.3.16-2]
psmisc/stable 23.4 arm [upgradable from: 23.3-2]
readline/stable 8.1.1 arm [upgradable from: 8.0.4-1]
sed/stable 4.8-2 arm [upgradable from: 4.8-1]
tar/stable 1.34 arm [upgradable from: 1.32-6]
termux-am/stable 0.4 all [upgradable from: 0.3]
termux-exec/stable 1:0.9 arm [upgradable from: 0.5]
termux-keyring/stable 3.0 all [upgradable from: 1.4]
termux-licenses/stable 2.0-2 all [upgradable from: 2.0-1]
termux-tools/stable 0.168 all [upgradable from: 0.93]
util-linux/stable 2.37.4 arm [upgradable from: 2.35.2-1]
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Thu Jan 13 11:24:32 CST 2022 armv8l Android
Device manufacturer:
HUAWEI
Device model:
JAT-LX1

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation

https://github.com/termux/termux-app#google-play-store-deprecated
