### ISSUE TITLE
Issue with termux version of vim

### ISSUE THREAD

**Issue by Worldwalker23** [termux/termux-packages#9626]
When I open vim, every few seconds I get this:

Error detected while compiling CursorHold Auto
commands for "*"..function <SNR>13_SetupLazyloadMenus[1]..<SNR>13_SetupColorSchemes:
line   11:
E1256: String or function required for argumen
t 2

I've tried removing and reinstalling vim and vim-runtime. No joy. I've commented out any lines in my vimrc that use * and the lines that run pathogen. Any other ideas? It's not very usable this way.

**Comment by xtkoba** [comment]
Can't reproduce on my Android 8.1.0 aarch64 environment with `vim{,-runtime}` version `8.2.4450-2`.

**Comment by xtkoba** [comment]
Please provide your `termux-info` output when reporting a problem. It is not uncommon that a problem occurs only on specific versions of Android or architectures.

**Comment by Worldwalker23** [comment]
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf+ #1 SMP PREEMPT Mon Jan 31 02:57:24 CST 2022 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g power

**Comment by xtkoba** [comment]
Does anyone else reproduce this?

**Comment by thunder-coding** [comment]
> Does anyone else reproduce this?

I guess they are having some third-party plugins installed!
