### ISSUE TITLE
[Package]: anacron

### ISSUE THREAD

**Issue by Simon857s** [termux/termux-packages#9627]
### Package description

Anacron is a periodic command scheduler. It executes commands at intervals specified in days. Unlike cron, it does not assume that the system is running continuously.

An ideal partner for cron or termux-job-scheduler.

### Home page URL

https://sourceforge.net/projects/anacron/

### Source code URL

https://sourceforge.net/projects/anacron/files/latest/download

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Tried to build myself. Failed with this...
```~/tmp/anacron/anacron-2.3 $ make
cc -c -DSPOOLDIR=\"/var/spool/anacron\" -DRELEASE=\"2.3\" -DANACRONTAB=\"/etc/anacrontab\"  -Wall -pedantic -O2 gregor.c -o gregor.o
gregor.c:79:12: error: cannot assign to variable 'isleap' with const-qualified type 'const int'
    isleap = leap(year);
    ~~~~~~ ^
gregor.c:68:15: note: variable 'isleap' declared const here
    const int isleap; /* save three calls to leap() */
    ~~~~~~~~~~^~~~~~
1 error generated.
make: *** [Makefile:63: gregor.o] Error 1

**Comment by xtkoba** [comment]
See for example:

https://github.com/gentoo/gentoo/blob/3e44d897a842d588fb9a8ff755ef294ac4e21fcc/sys-process/anacron/files/anacron-2.3-compile-fix-from-debian.patch
