### ISSUE TITLE
How do I start crond on Termux?

### ISSUE THREAD

**Issue by bitcoinmeetups** [termux/termux-packages#963]
How do I start crond on Termux?

The usual ways don't seem to work.

**Comment by Grimler91** [comment]
As @Neo-Oli said in the google+ community, just typing `crond` should work. 

If not, what error do you get?

**Comment by Neo-Oli** [comment]
Closing this, since [the question was answered on Gitter.](https://gitter.im/termux/termux?at=590072ebcfec919272776ff7)
