### ISSUE TITLE
Enable wall in util-linux

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#964]
Hello,
Would it be possible to enable `wall` in the util-linux package?

**Comment by fornwall** [comment]
`wall` from util-linux will not work on Android.

However, to broadcast to Termux sessions I guess you could do something like this:

```sh
for p in `seq 100`; do if [ -w /dev/pts/$p ]; then printf "\n\nMESSAGE:\nHello world\n" > /dev/pts/$p; fi; done
```
