### ISSUE TITLE
[Package]: bitlbee

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9641]
### Package description

BitlBee brings IM (instant messaging) to IRC clients. It's a great solution for people who have an IRC client running all the time and don't want to run an additional XMPP/facebook/discord/whatever client.

### Home page URL

https://www.bitlbee.org

### Source code URL

https://github.com/bitlbee/bitlbee

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

It is same znc (znc is available in termux repo) please add bitlbee when we already have znc. Its very useful for irc users. Thank you

**Comment by khaalidrafi** [comment]
Please also add bitlbee-libpurple and some popular plugins such as purple-discord, purple-gowhatsapp etc.
