### ISSUE TITLE
[Package]: Iris

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9645]
### Package description

Iris is a tiny bit of shared message and file convention that pretends to be forum software.

### Home page URL

https://github.com/Calamitous/iris

### Source code URL

https://github.com/Calamitous/iris

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
```
$ gem install iris
```
