### ISSUE TITLE
[Package]: rxfetch-termux

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9649]
### Package description

rxfetch-termux is a Termux Fetch Fork of https://github.com/Mangeshrex/rxfetch

### Home page URL

https://github.com/mayTermux/rxfetch-termux

### Source code URL

https://github.com/mayTermux/rxfetch-termux

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
No license is specified. We cannot legally package this.

**Comment by aicynide** [comment]
The project is new, I think we can open a issue in that repo to ask the developer add a license

**Comment by Mangeshrex** [comment]
Hey, I've made a pull-request on the fork "rxfetch-termux" adding GPL license. Maybe you guys can try after the pr gets merged.

**Comment by aicynide** [comment]
@xtkoba sir, license merged
