### ISSUE TITLE
add package request: termloop game

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9654]
### Package description

A game engine from the terminal

### Home page URL

https://github.com/JoelOtter/termloop

### Source code URL

https://github.com/JoelOtter/termloop

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Not a standalone application. Use

```bash
go get github.com/JoelOtter/termloop
```
