### ISSUE TITLE
[Package]: Hydroxide

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9659]
### Package description

A third-party, open-source ProtonMail CardDAV, IMAP and SMTP bridge

### Home page URL

https://github.com/emersion/hydroxide

### Source code URL

https://github.com/emersion/hydroxide

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
We have already packaged this, named `hydroxide` in main repo.

**Comment by aicynide** [comment]
Oh sorry
