### ISSUE TITLE
add package request: metar

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9670]
### Package description

metar is a python package for interpreting METAR and SPECI coded weather reports

### Home page URL

https://github.com/python-metar/python-metar

### Source code URL

https://github.com/python-metar/python-metar

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Metar can be installed through pip. The [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) is quite clear that we don't provide packages for stuff that are available through other package managers, and I have pointed this out to you multiple times: https://github.com/termux/termux-packages/issues/9150, https://github.com/termux/termux-packages/issues/9602.

*Please read and make sure you understand the Packaging Policy before requesting packages.*
