### ISSUE TITLE
add package request: milib

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9671]
### Package description

Yet another Java library for Next Generation Sequencing (NGS) data processing

### Home page URL

https://github.com/milaboratory/milib

### Source code URL

https://github.com/milaboratory/milib

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Use <a href="https://mvnrepository.com/artifact/com.milaboratory/milib">Maven Repository</a>.
