### ISSUE TITLE
add package request: icu

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9673]
### Package description

This is the repository for the [International Components for Unicode](https://icu.unicode.org/).

### Home page URL

https://github.com/unicode-org/icu

### Source code URL

https://github.com/unicode-org/icu

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Also as pointed out before, search for previous issues or existing packages before opening package requests. We [already have icu](https://github.com/termux/termux-packages/tree/master/packages/libicu).
