### ISSUE TITLE
add package request: glowing-bear

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9675]
### Package description

Glowing Bear is a web frontend for the [WeeChat](https://weechat.org/) IRC client and strives to be a modern interface

### Home page URL

https://www.glowing-bear.org/

### Source code URL

https://github.com/glowing-bear/glowing-bear

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Can be installed through npm. You don't seem to understand the feedback I have provided in your previous package requests so I'll block you temporarily to try to get the point across
