### ISSUE TITLE
[Package]: add pidgin for termux 

### ISSUE THREAD

**Issue by ExtinctDrift19** [termux/termux-packages#9678]
### Package description

Pidgin is a chat program which lets you log into accounts on multiple chat networks simultaneously. This means that you can be chatting with friends on XMPP and sitting in an IRC channel at the same time.

Pidgin runs on Windows, Linux, and other UNIX-like operating systems. Looking for Pidgin for macOS? Try Adium!

Pidgin is compatible with the following chat networks out of the box: Jabber/XMPP, Bonjour, Gadu-Gadu, IRC, Novell GroupWise Messenger, Lotus Sametime, SILC, SIMPLE, and Zephyr. It can support many more with plugins.

Pidgin supports many features of these chat networks, such as file transfers, away messages, buddy icons, custom smileys, and typing notifications. Numerous plugins also extend Pidgin’s functionality above and beyond the standard features.

Pidgin is under constant development. Releases are usually frequent and driven by user contributions, such as issues and contributions.

Pidgin is free and contains no ads. All our code is open source and licensed under the GNU General Public License. This means you can get Pidgin’s underlying code and modify it to suit your needs, as long as you publish the changes you make for everyone to benefit from as well.

Pidgin is translated into many different languages, thanks to the generous contributions of our volunteer translators.

### Home page URL

https://pidgin.im/

### Source code URL

https://sourceforge.net/projects/pidgin/files/Pidgin/2.14.8/pidgin-2.14.8.tar.bz2/download

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
We already have `pidgin` packaged in x11 repo. We also have `finch` (ncurses version I suppose) packaged in main repo.
