### ISSUE TITLE
Package request: rxvt-unicode-terminfo

### ISSUE THREAD

**Issue by dan-santana** [termux/termux-packages#968]
The following terminfos are missing:
```
/usr/share/terminfo/r/rxvt-unicode
/usr/share/terminfo/r/rxvt-unicode-256color
```

They don't come in the `ncurses` package, instead they must be created from the rxvt-unicode source (http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.22.tar.bz2).

**Comment by de-vri-es** [comment]
Without terminfo for urxvt, ssh-ing into the termux environment using urxvt is a real pain. So this would really be useful.

**Comment by fornwall** [comment]
Thanks - rxvt-unicode  and rxvt-unicode-256color terminfos has been added in the updated version `6.0.20170610` of the ncurses package.

Let me know if there are any problems!

**Comment by de-vri-es** [comment]
Works like a charm, thanks!
