### ISSUE TITLE
Add overlay keyboard with Alt, Ctrl, Tab, arrow keys (and a few more keys)

### ISSUE THREAD

**Issue by indam** [termux/termux-packages#97]
Firstly, thanks for your great work.
I have a suggestion, you can add the TAB, ALT, and CTRL key into a popup keyboard for touch screen. Just like what JuiceSSH did. That will be more convenient than volume up and down.

Thanks.

**Comment by franciscod** [comment]
related? the tab key is mapped to the back key on your phone

**Comment by fornwall** [comment]
There will probably be something like the JuiceSSH keyboard soon!

![juicessh-keyboard](https://cloud.githubusercontent.com/assets/277251/11932245/3e3c369e-a7f4-11e5-86ad-6375851ca771.png)

**Comment by fornwall** [comment]
Closing this issue - you can track https://github.com/termux/termux-app/issues/12 for the additional keyboard!
