### ISSUE TITLE
Package request: gegl

### ISSUE THREAD

**Issue by supertobi** [termux/termux-packages#970]
GEGL is not only a library but even has a command line tool to do image processing:

Homepage:
http://gegl.org/

Code:
https://git.gnome.org/browse/gegl

**Comment by its-pointless** [comment]
Also added this 
But i need testing...

**Comment by bergie** [comment]
This would probably also make https://github.com/imgflo/imgflo possible on Termux

**Comment by its-pointless** [comment]
iv got a test version of imgflo up on my repo.  I havn't tested it yet though.

**Comment by fornwall** [comment]
Thanks to @its-pointless there is now a `gegl` package available - try it out with:

    packages install gegl
