### ISSUE TITLE
Package request: darktable-cli

### ISSUE THREAD

**Issue by supertobi** [termux/termux-packages#971]
darktable is an open source photography workflow application and raw developer. The program itself is not useful, but it has a command line tool that would be useful.

Homepage:
https://www.darktable.org/
https://www.darktable.org/usermanual/ch01.html.php#darktable_cli_commandline_parameters

Code:
https://github.com/darktable-org/darktable

**Comment by its-pointless** [comment]
it doesn't support 32bit and configure says
"could NOT find GTK3 (missing: GTK3_INCLUDE_DIRS GTK3_LIBRARIES) (Required"

**Comment by supertobi** [comment]
I talked to one of the developers and it is not possible to build darktable-cli without gtk. I think you can close this.
