### ISSUE TITLE
Add back binutils to build-essential

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-packages#9715]
The reason is ar is not included in llvm and is still needed

**Comment by Grimler91** [comment]
llvm-ar is included in llvm. Do you have a specific use-case where `llvm-ar` isn't enough?

**Comment by xrust27** [comment]
I just grabbed every tool I need to get what I need done

**Comment by strikersix23** [comment]
as this just a sugestion, most common build systems still look for ar and it is in binutils, as this is more of an ease of access problem. You can create a wrapper so python, make, and autotools can find it or have script to set the env for llvm-ar

**Comment by strikersix23** [comment]
Python wouldn't recognize llvm-ar as ar

**Comment by xtkoba** [comment]
For reference, I once tried tackling a similar problem for `ld`: #8191, #8192.

I wonder if `update-alternatives` can handle several commands at once.

**Comment by strikersix23** [comment]
Yeah I remember that this is more of an issue though because there's only a few ways to go that I know of. But most will cause a conflict. The easy route would do like pointless does with setup-scripts

**Comment by xtkoba** [comment]
`binutils-is-llvm` is meant mostly for users' convenience and I have no plan to make `build-essential` depend on it.
