### ISSUE TITLE
Package request: G'MIC

### ISSUE THREAD

**Issue by supertobi** [termux/termux-packages#972]
G'MIC includes a command-line interface gmic, to use the G'MIC image processing features from a shell. In this setting, G'MIC may be seen as a friendly companion to the ImageMagick or GraphicsMagick software suites

Homepage:
http://gmic.eu/

Code:
http://gmic.eu/download.shtml

**Comment by its-pointless** [comment]
I gmic to to my repo for testing.  its-pointless/gcc_termux for instructions.

**Comment by supertobi** [comment]
I was not able to find it. I've done:
--------------------------------------------
added a file with "deb [trusted=yes] https://its-pointless.github.io/files/  termux extras" to $PREFIX/etc/apt/sources.list.d/
downloaded the gpg key from https://its-pointless.github.io/pointless.gpg
installed gnupg with "apt-get install gnupg"
run "apt-key add pointless.gpg"
apt-get update
apt-chache search gmic
--------------------------------------------
No results

**Comment by its-pointless** [comment]
apt search instead of apt-cache search ?

**Comment by its-pointless** [comment]
Also you might need to 
export TMP=$PREFIX/tmp
or 
export TMPDIR=$PREFIX/tmp
something like that.

**Comment by supertobi** [comment]
I've removed the file in $PREFIX/etc/apt/sources.list.d/ an added a line to sources.list and now I was able to install it.

**Comment by vishalbiswas** [comment]
files in $PREFIX/etc/apt/sources.list.d/ should have `.list` extension, else they are not read.

**Comment by its-pointless** [comment]
i will give better instuctions in future.

Apart from that does gmic works right?

**Comment by supertobi** [comment]
@its-pointless Yes, it runns and the first tests are looking good.

**Comment by isaacullah** [comment]
I've just installed and will be testing soon. Note, here are the installation steps that eventually worked for me:
1. Get some needed tools. coreutils for the `mkdir`, gnugp for the signing key, and apt-transport-https to actually connect to the repo 
    `apt install coreutils gnugp apt-transport-https`
2. Make the `sources.list.d` directory
`mkdir $PREFIX/etc/apt/sources.list.d`
3. Write the needed source file
`echo "deb [trusted=yes] https://its-pointless.github.io/files/ termux extras" > pointless.list`
4. Download signing key from https://its-pointless.github.io/pointless.gpg to my downloads folder.
5. Run `termux-setup-storage` script if not already done
6. Install the signing key
`apt-key add storage/downloads/pointless.gpg`
7. Update apt 
`apt update`
8. Install GMIC
`apt install gmic`

**Comment by xeffyr** [comment]
gmic is available in repository. Just use `pkg install gmic`.

**Comment by supertobi** [comment]
I think we can close this. Feel free to reopen it, if something is missing.
