### ISSUE TITLE
[Bug]: openjdk-17: can't install the package

### ISSUE THREAD

**Issue by tempaccforissue** [termux/termux-packages#9733]
### Problem description

After `apt update && apt full-upgrade -y`, when I try to install `openjdk-17` by `apt install openjdk-17 -y`, it says the package is not available.

See:
![IMG_20220401_173637](https://user-images.githubusercontent.com/102426645/161256438-a3bd0b45-2ff0-4be2-ae4e-0563f3823b2d.jpg)

### What steps will reproduce the bug?

1. `apt update && apt full-upgrade -y`
2. `apt install openjdk-17 -y`

### What is the expected behavior?

It should be able to install the `openjdk-17` package.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.193-perf-g743cb02 #1 SMP PREEMPT Mon Oct 25 17:15:39 CST 2021 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 8A

```

**Comment by Grimler91** [comment]
Seems non-aarch64 debs are missing from packages.termux.org. A workaround until this has been fixed would be to switch to my grimler.se mirror with `termux-change-repo`

**Comment by Grimler91** [comment]
openjdk is now available from packages.termux.org as well
