### ISSUE TITLE
Create SSHd Logfile

### ISSUE THREAD

**Issue by nanderer** [termux/termux-packages#9734]
Hi,

could you create a SSHd Logfile at ``/data/data/com.termux/files/usr/var/log/`` by default? Its a security risk to have this not enabled by default imho.

Also maybe give me a hint how to configure one my own.

Also usual commands like ``who`` and ``last`` would be nice.

**Comment by Grimler91** [comment]
How are you currently running sshd?

With [termux-services](https://wiki.termux.com/wiki/Termux-services) you get logs in `$PREFIX/var/log/sv/sshd/current`. If you are running sshd "manually" you can use the `-E` option (see sshd --help)

**Comment by xtkoba** [comment]
`who` (from `coreutils`) and `last` (from `util-linux`) are explicitly disabled because they do not make much sense in Termux. Note that in Termux every process runs with the same UID, which leads to that anyone who logs in to a Termux system can manipulate any log file therein.
