### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ronnac** [termux/termux-packages#9738]
### Problem description

Scipy installation from itspointless: it installs into python3.9/site-packages, but default python is 3.10 now

### What steps will reproduce the bug?

pkg install scipy
python
>>> import scipy
Error module not found 

### What is the expected behavior?
python can correctly import scipy

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.177-21848546 #1 SMP PREEMPT Mon Aug 9 18:36:37 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A105FN
```

**Comment by Grimler91** [comment]
Nothing we can do about it here. Has already been reported numerous times in its-pointless repo, for example https://github.com/its-pointless/its-pointless.github.io/issues/89
