### ISSUE TITLE
[Package]: Pounce

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9740]
### Package description

pounce(1) is a multi-client, TLS-only IRC bouncer. It maintains a persistent connection to an IRC server, acting as a proxy and buffer for a number of clients. When a client connects, any messages received since it last disconnected will be relayed to it. Unlike some other bouncers, pounce uses a single buffer for all IRC messages, which acts as a queue from which each client reads messages independently.

### Home page URL

https://git.causal.agency/pounce/about/

### Source code URL

https://git.causal.agency/pounce

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Since libretls is merged its Time for pounce now https://github.com/termux/termux-packages/pull/9623

**Comment by Yonle** [comment]
As a note, pounce bouncer is not available at several distribution packages manager. Also it requires some patch so android could support it.

```
cc  bounce.o client.o config.o local.o ring.o server.o state.o xdg.o -lcrypt -L/data/data/com.termux/files/usr/lib -ltls -o pounce
ld.lld: error: undefined symbol: explicit_bzero
>>> referenced by bounce.c
>>>               bounce.o:(main)
>>> referenced by bounce.c
>>>               bounce.o:(main)
>>> referenced by client.c
>>>               client.o:(handlePass)
>>> referenced 2 more times
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:39: pounce] Error 1
```
