### ISSUE TITLE
[Package]: nzbget

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9760]
### Package description

Efficient Usenet downloader

### Home page URL

https://nzbget.net/

### Source code URL

https://nzbget.net/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Already packaged, named `nzbget` in main repo.

**Comment by aicynide** [comment]
Sorry
