### ISSUE TITLE
[Package]: etherpad

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9762]
### Package description

Etherpad: A modern really-real-time collaborative document editor.

### Home page URL

https://etherpad.org/

### Source code URL

https://github.com/ether/etherpad-lite

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Use npm.

**Comment by aicynide** [comment]
Sorry, didn't know it was in npm
