### ISSUE TITLE
[Package]: lclone

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9765]
### Package description

Modded rclone supporting rotating Google service accounts while copying and syncing files in google drive.

### Home page URL

https://github.com/l3uddz/rclone/tree/feat/sa-cycle

### Source code URL

https://github.com/l3uddz/rclone/tree/feat/sa-cycle

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
The description is insufficient to present substantial difference from `rclone`. No other distro packages this.
