### ISSUE TITLE
[Package]: sasync

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9766]
### Package description

SASYNC uses rclone and Google Service Accounts (SAs) to sync, copy or move files between rclone remotes.

### Home page URL

https://github.com/88lex/sasync

### Source code URL

https://github.com/88lex/sasync

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by T-Dynamos** [comment]
@xtkoba 
This also depends on `rclone`
So close it

**Comment by wmcbtech30** [comment]
and also a shell script wrapper of `rclone`

keep in mind that we do not serve duplicate functionality which can do the exact same job as the package opponent
