### ISSUE TITLE
[Package]: gclone

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9767]
### Package description

A modified version of the rclone Provide dynamic replacement sa file support for google drive operation

### Home page URL

https://github.com/donwa/gclone

### Source code URL

https://github.com/donwa/gclone

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
The description is insufficient to present substantial difference from `rclone`. No other distro packages this.
