### ISSUE TITLE
[Package]: fclone

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9768]
### Package description

Modified rclone with Enhancement for Google Drive

### Home page URL

https://github.com/mawaya/rclone

### Source code URL

https://github.com/mawaya/rclone

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by T-Dynamos** [comment]
I think so these are duplicate 
Of rclone

**Comment by xtkoba** [comment]
The description is insufficient to present substantial difference from `rclone`. No other distro packages this.
