### ISSUE TITLE
Problem opening file through Termux

### ISSUE THREAD

**Issue by mkhairulj** [termux/termux-packages#9773]
How to open existing file through Download? I shared a video of my problem, hope someone can help.

https://user-images.githubusercontent.com/24906913/161348213-96678ee0-6d50-47ce-8723-e95c95d7682a.mp4

**Comment by xtkoba** [comment]
I cannot figure out the content of the video. Please write down what you are trying to do.

Also please include your `termux-info` output.

**Comment by 2096779623** [comment]
```shell
termux-setup-storage
cd storage/downloads
ls
```
Then mv or cp to the home directory of Termux.

**Comment by Grimler91** [comment]
`nano /path/to/file` opens a specific file, if that's what you are asking

**Comment by mkhairulj** [comment]
> `nano /path/to/file` opens a specific file, if that's what you are asking

If open the file directly from Termux its work, here i try to open a file from 'Chrome>Download', when i click the downloaded file through 'Download', a termux pop-up show (please refer to picture A).
The pop-up gave me 3 options, 1. Open Directory, 2. Cancel, 3. Edit.

1. If i click on open directory, it will open Termux automatically and will display the location of the file. 
2. Cancel
3. If i click edit then an error pop-up show (please refer to picture B). How do I open the file I downloaded if this happens?

(For termux-info please refer to picture C)


A =
![Screenshot_2022_0403_020057](https://user-images.githubusercontent.com/24906913/161395684-8fcae4bd-cad4-4492-a264-752ae340c717.png)

B =
![Screenshot_2022_0403_021057](https://user-images.githubusercontent.com/24906913/161396027-b75f1365-20a5-4e72-8241-1cd06dc3c5c5.png)

C = 
![Screenshot_2022_0403_021650](https://user-images.githubusercontent.com/24906913/161396116-8865c729-d373-4691-9db7-0dba148a739a.png)

**Comment by mkhairulj** [comment]
> I cannot figure out the content of the video. Please write down what you are trying to do.
> 
> Also please include your `termux-info` output.

![Screenshot_2022_0403_021650](https://user-images.githubusercontent.com/24906913/161396142-bea50971-8f7c-4c65-bb0b-3c49768c1122.png)

**Comment by agnostic-apollo** [comment]
Should receive path in `$1` in `termux-file-editor`

https://wiki.termux.com/wiki/Intents_and_Hooks

**Comment by mkhairulj** [comment]
> 

Can you help me by filming a video showing a must thing need to do or has to be to solve my problem. Please?

**Comment by Grimler91** [comment]
Create a symlink as the popup suggests, for example `ln -s nano $PREFIX/bin/termux-file-editor`

**Comment by kali22k** [comment]
``

**Comment by PUNITHKUMAR1973** [comment]
I do can't run a file in termux I used termux-open main.exe

**Comment by TomJo2000** [comment]
> I do can't run a file in termux I used termux-open main.exe

This is a ***closed*** 2 year old issue.
Please do not [necro-bump](https://www.urbandictionary.com/define.php?term=necrobump) it.
You can open a new issue.

*However*, your problem is something different.
`.exe` files are **Windows** executables.
Not only is it not going to run on Android/Linux because of API incompatibility.
Though there is WINE for that potentially.
It is also most likely compiled for an x86_64 CPU which is not compatible with the, most likely, AArch64 CPU in your phone.
Thus you'd need an x86(_64) emulator such as Box64, which we do not package.
