### ISSUE TITLE
CANNOT LINK EXECUTABLE "./arm_compute_benchmark": library "libomp.so" not found: needed by main executable

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-packages#9774]
### Problem description

I just build Compute library PKG for my device
But when i trying to benchmark getting error 
CANNOT LINK EXECUTABLE "./arm_compute_benchmark": library "libomp.so" not found: needed by main executable

How can I solve?

![Screenshot_2022-04-02-04-10-21-668_com termux](https://user-images.githubusercontent.com/72664192/161351438-ad24fd97-32d9-4b9c-ab5d-ac61476dbd9e.jpg)

### What steps will reproduce the bug?

Nothing i don't know about it..

### System information

![Screenshot_2022-04-02-04-15-38-547_com termux](https://user-images.githubusercontent.com/72664192/161351414-b391ad9f-e85b-4b4e-83d8-81f8940c2c01.jpg)

**Comment by xtkoba** [comment]
Does

```bash
LDFLAGS+=" -fopenmp -static-openmp"
```

solve the problem for you?

**Comment by Saikatsaha1996** [comment]
> Does
> 
> ```shell
> LDFLAGS+=" -fopenmp -static-openmp"
> ```
> 
> solve the problem for you?

Ok trying

**Comment by Saikatsaha1996** [comment]
> Does
> 
> ```shell
> LDFLAGS+=" -fopenmp -static-openmp"

like this?
> ```
> 
> solve the problem for you?

![Screenshot_2022-04-02-04-33-44-093_com termux](https://user-images.githubusercontent.com/72664192/161352642-30fca8ef-9ad0-4978-80e4-e9ed8a61b59f.jpg)

**Comment by xtkoba** [comment]
No. Before building.

**Comment by Saikatsaha1996** [comment]
> No. Before building.

Okay trying

**Comment by Saikatsaha1996** [comment]
> No. Before building.

Can't build

![Screenshot_2022-04-02-04-39-07-306_com termux](https://user-images.githubusercontent.com/72664192/161352951-30761e10-d893-4c2f-b710-5d97c59867a5.jpg)

**Comment by xtkoba** [comment]
For SCons, try something like

```bash
scons LINKFLAGS="$LDFLAGS -fopenmp -static-openmp"
```

**Comment by Saikatsaha1996** [comment]
> For SCons, try something like
> 
> ```shell
> scons LINKFLAGS="$LDFLAGS -fopenmp -static-openmp"
> ```

![Screenshot_2022-04-02-04-53-22-675_com termux](https://user-images.githubusercontent.com/72664192/161353833-cdcac360-01de-452d-a416-4b9f69975488.jpg)

**Comment by xtkoba** [comment]
Adapt to the software by yourself.

**Comment by Saikatsaha1996** [comment]
> Adapt to the software by yourself.

How can I install any link?

**Comment by xtkoba** [comment]
What do you mean?

**Comment by Saikatsaha1996** [comment]
Ok i found solution.. in scons help 
disable openmp
