### ISSUE TITLE
[Package]: catimg

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#9786]
### Package description

🦦 Insanely fast image printing in your terminal

### Home page URL

https://posva.net/shell/retro/bash/2013/05/27/catimg

### Source code URL

https://github.com/posva/catimg/archive/refs/tags/2.7.0.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by T-Dynamos** [comment]
😗 Required ImageMagick
![Screenshot_2022-04-02-10-48-52-711_com termux](https://user-images.githubusercontent.com/68729523/161367793-fd7b5670-b0a1-48cb-8a58-63408beced4b.jpg)
