### ISSUE TITLE
Cannot run perl...

### ISSUE THREAD

**Issue by NickVendetta** [termux/termux-packages#979]
Welcome to Termux!

Online help:     https://termux.com/help
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   packages search <query>
Install a package: packages install <package>
Upgrade packages:  packages upgrade
Learn more:        packages help
$ cd /
$ ls
acct                     init.mt6582.usb.rc
cache                    init.project.rc
charger                  init.rc
config                   init.ssd_nomuser.rc
custom                   init.trace.rc
$ cd sdcarf
bash: cd: sdcarf: No such file or directory
$ cd sdcard
$ ls
10k_most_common.txt
Android
Audio
Contact
DCIM
Document
Download
HDC
LOST.DIR
Lenovo
Movies
Music
Pictures
SHAREit
Telegram
Video
WEPCrack.py
WhatsApp
admin-panel-finder
com.facebook.orca
com.kingroot.kinguser
com.kingstudio.purify
krsdk-b105006-stock-conf
mp3
niemlpscrk.sh
nifbpscrk.pl
niwbspscrk
niwppscrk
tencent
tmpCloseTime.dat
toprange
torshammer
trlocker_debug.txt
$ perl nifbpscrk.pl
Can't locate Net/SSLeay/Handle.pm in @INC (you may need to install the Net::SSLeay::Handle module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.24.1/arm-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.24.1 /data/data/com.termux/files/usr/lib/perl5/5.24.1/arm-android /data/data/com.termux/files/usr/lib/perl5/5.24.1 .) at nifbpscrk.pl line 2.
BEGIN failed--compilation aborted at nifbpscrk.pl line 2.
$

**Comment by its-pointless** [comment]
you need to install Net::SSLeay::Handle 

`apt install openssl-dev openssl-tool`
`cpan install Net::SSLeay::Handle `

**Comment by NickVendetta** [comment]
what should i choose after install net ssleay module?local::lib,sudo or manual?

**Comment by Grimler91** [comment]
@NickVendetta go for local::lib

**Comment by NickVendetta** [comment]
I followed all steps..and it failed...
Welcome to Termux!

Online help:     https://termux.com/help
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   packages search <query>
Install a package: packages install <package>
Upgrade packages:  packages upgrade
Learn more:        packages help
$ cd /
$ cd sdcard
$ ls
Android
Audio
Contact
DCIM
Document
Download
HT-WPS-Breaker
KingMaster
LOST.DIR
Lenovo
LesyncDownload
SHAREit
WEPCrack.py
WhatsApp
com.kingroot.kinguser
com.kingstudio.purify
goldeneye
hulk
katoolin
kickthemout
krsdk-b105006-stock-conf
niemlpscrk.sh
nifbpscrk.pl
niigpscrk
nijmpscrk.pl
nitwpscrk.py
niwbspscrk.py
niwppscrk.pl
sqlmap
tencent
theharvester
toprange
torshammer
uniscan
wpscan
xerxes
$ perl nifbpscrk.pl
Can't locate Net/SSLeay/Handle.pm in @INC (you may need to install the Net::SSLeay::Handle module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.24.1/arm-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.24.1 /data/data/com.termux/files/usr/lib/perl5/5.24.1/arm-android /data/data/com.termux/files/usr/lib/perl5/5.24.1 .) at nifbpscrk.pl line 2.
BEGIN failed--compilation aborted at nifbpscrk.pl line 2.
$

**Comment by Grimler91** [comment]
Did you run into any errors when installing `Net::SSLeay::Handle`?

**Comment by NickVendetta** [comment]
yes...its says make --not okay

**Comment by Grimler91** [comment]
Sounds like you should fix that error :)

**Comment by NickVendetta** [comment]
how to fix that error?_?...btw i dont understand what you say about 'Try executing it with the full path instead'...in cannot run root on termux issue...thanks for reply...

**Comment by Grimler91** [comment]
@NickVendetta You haven't shared the error so it's impossible for me to know how to fix it. 

If you type su (or tsu) and enter root mode and thereafter type `/data/data/com.termux/files/use/bin/python2 WEPCrack.py wlan0` instead of just `python2 WEPCrack.py wlan0` then your shell shouldn't complain about not finding python2

**Comment by NickVendetta** [comment]
ok got it...how to fix error when install Net::SSLeay::Handle?

**Comment by Grimler91** [comment]
@NickVendetta Share the error message.

**Comment by NickVendetta** [comment]
its says:operation not permitted

**Comment by davidbbisht** [comment]
Can't install NET::SSLeay::Handle it show error here is it
Running install for module 'Net::SSLeay::Handle'
Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/M/MI/MIKEM/Net-SSLeay-1.81.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring M/MI/MIKEM/Net-SSLeay-1.81.tar.gz with Makefile.PL
Unresolvable missing external dependency.
This package requires a C compiler.
NA: Unable to build distribution on this platform.
No 'Makefile' created  MIKEM/Net-SSLeay-1.81.tar.gz
  /data/data/com.termux/files/usr/bin/perl Makefile.PL -- NOT OK

**Comment by sdrausty** [comment]
```
$ apt install openssl-dev openssl-tool
Reading package lists... Done
Building dependency tree
Reading state information... Done
openssl-dev is already the newest version (1.0.2l-1).
openssl-tool is already the newest version (1.0.2l-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ cpan install Net::SSLeay::Handle
Reading '/data/data/com.termux/files/home/.cpan/Metadata'
  Database was generated on Tue, 15 Aug 2017 02:17:03 GMT
Net::SSLeay::Handle is up to date (0.61).
```
![screenshot_20170814-224628](https://user-images.githubusercontent.com/27742457/29300276-79d52296-8142-11e7-9f5f-d5136405f01d.png)

**Comment by davidbbisht** [comment]
No not installing net ssleay handle after apt install openssl-dev openssl-tool and also show same error
4:02 GMT
$ cpan install Net::SSLeay::Handle
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/data/data/com.termux/files/home/.cpan/Metadata'
  Database was generated on Mon, 14 Aug 2017 15:54:02 GMT
Running install for module 'Net::SSLeay::Handle'
Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/M/MI/MIKEM/Net-SSLeay-1.81.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring M/MI/MIKEM/Net-SSLeay-1.81.tar.gz with Makefile.PL
Unresolvable missing external dependency.
This package requires a C compiler.
NA: Unable to build distribution on this platform.
No 'Makefile' created  MIKEM/Net-SSLeay-1.81.tar.gz
  /data/data/com.termux/files/usr/bin/perl Makefile.PL -- NOT OK
$

**Comment by Grimler91** [comment]
@davidbbisht looks like you don't have a C-compiler. Install clang `pkg install clang`

**Comment by davidbbisht** [comment]
@Grimler91 after install C compiler that  show another error 
Running install for module 'Net::SSLeay::Handle'
Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/M/MI/MIKEM/Net-SSLeay-1.81.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring M/MI/MIKEM/Net-SSLeay-1.81.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Warning: Guessing NAME [Net-SSLeay] from current directory name.
Warning: NAME must be a package name
*** Found OpenSSL-1.0.2l installed in .
*** Be sure to use the same compiler and options to compile your OpenSSL, perl,
    and Net::SSLeay. Mixing and matching compilers is not supported.
Do you want to run external tests?
These tests *will* *fail* if you do not have network connectivity. [n] n
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Net::SSLeay
Writing MYMETA.yml and MYMETA.json
  MIKEM/Net-SSLeay-1.81.tar.gz
  /data/data/com.termux/files/usr/bin/perl Makefile.PL -- OK
Running make for M/MI/MIKEM/Net-SSLeay-1.81.tar.gz
  MIKEM/Net-SSLeay-1.81.tar.gz
  make -- NOT OK
  No such file or directory

**Comment by davidbbisht** [comment]
How can install local::lib ?
As shown
$ install local::lib
BusyBox v1.27.1 (2017-08-11 00:59:40 UTC) multi-call binary.

Usage: install [-cdDsp] [-o USER] [-g GRP] [-m MODE] [-t DIR] [SOURCE]... DEST

Copy files and set attributes

        -c      Just copy (default)
        -d      Create directories
        -D      Create leading target directories
        -s      Strip symbol table
        -p      Preserve date
        -o USER Set ownership
        -g GRP  Set group ownership
        -m MODE Set permissions
        -t DIR  Install to DIR
$

**Comment by davidbbisht** [comment]
Help me?

**Comment by sdrausty** [comment]
@davidbbisht `apt install make`

**Comment by davidbbisht** [comment]
Thanks it's work.

**Comment by davidbbisht** [comment]
@sdrausty sir, I want to some queries about termux.
So can u pls give me ur gmail id/account.?

**Comment by sdrausty** [comment]
@davidbbisht https://plus.google.com/109614420080028230010

**Comment by davidbbisht** [comment]
Hydra not proper working

**Comment by davidbbisht** [comment]
Sir, I have some queries so pls send me mail in my account davidbisht.bisht@gmail.com from ur e-mail id .

**Comment by davidbbisht** [comment]
And also learn from you.

**Comment by SantriInsyaf** [comment]
$ perl bot.pl
Can't locate HTTP/Response.pm in @INC (you may need to install the HTTP::Response module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.2/arm-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.26.2 /data/data/com.termux/files/usr/lib/perl5/5.26.2/arm-android /data/data/com.termux/files/usr/lib/perl5/5.26.2 .) at bot.pl line 4.
BEGIN failed--compilation aborted at bot.pl line 4.
How to fix this is?

**Comment by historyhacking** [comment]
I install tsu manual. 

$cat tsu > /data/data/com.termux/files/usr/bin/tsu
$ chmod 141 /data/data/com.termux/files/usr/bin/tsu
$ tsu
/data/data/com.termux/files/usr/bin/sh: 0: Can't open /data/data/com.termux/files/usr/bin/tsu

this is the result ... is my way wrong?

**Comment by Eli-the-Bearded** [comment]
The method in https://github.com/termux/termux-packages/issues/979#issuecomment-322363243 worked on my old device, but it is failing on my new one. 
```
$ cpan install Net::SSLeay::Handle
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/data/data/com.termux/files/home/.cpan/Metadata'
  Database was generated on Fri, 16 Nov 2018 16:17:03 GMT
Running install for module 'Net::SSLeay::Handle'
Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/M/MI/MIKEM/Net-SSLeay-1.85.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring M/MI/MIKEM/Net-SSLeay-1.85.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Warning: Guessing NAME [Net-SSLeay] from current directory name.
Warning: NAME must be a package name
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/openssl": cannot locate symbol "ENGINE_get_first" referenced by "/data/data/com.termux/files/usr/bin/openssl"...
*** OpenSSL version test failed
    (`' has been returned)
    Either you have bogus OpenSSL or a new version has changed the version
    number format. Please inform the authors!
Warning: No success on command[/data/data/com.termux/files/usr/bin/perl Makefile.PL]
  MIKEM/Net-SSLeay-1.85.tar.gz
  /data/data/com.termux/files/usr/bin/perl Makefile.PL -- NOT OK
$ pkg list-installed |grep -i ssl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

openssl/now 1.1.1-1 aarch64 [installed,upgradable to: 1.1.1-3]
openssl-dev/stable,now 1.1.1-3 aarch64 [installed]
openssl-tool/stable,now 1.1.1-3 aarch64 [installed]
$ pkg list-installed |grep -iE 'make|clang'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

clang/stable,now 7.0.0 aarch64 [installed]
make/stable,now 4.2.1-2 aarch64 [installed]
```

The error message suggests `openssl` has been wrapped with something since then.

**Comment by Eli-the-Bearded** [comment]
For the record, I got past that with a `pkg up`, so it must have been a weird incompatible binary / library state. But the compile for the Net::SSLeay still fails, now in a way that suggests SSL version differences. :^(
