### ISSUE TITLE
[New Mirror] CQUPT

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#9791]
|  Repository   | sources.list entry  |
|  ----  | ----  |
| [Main](https://github.com/termux/termux-packages)  | `deb https://mirrors.cqupt.edu.cn/termux/apt/termux-main stable main` |
| [Root](https://github.com/termux/termux-root-packages)  | `deb https://mirrors.cqupt.edu.cn/termux/apt/termux-root root stable` |
| [X11](https://github.com/termux/x11-packages)  |`deb http://mirrors.cqupt.edu.cn/termux/apt/termux-x11 x11 main` |

The mirror is in Chongqing,China.It runs ngnix and supports both IPv4 as well as both http and https.

[Node selection](https://github.com/CQUPTMirror/cqupt-mirrors-howto/tree/master/docs#%E8%B7%91%E7%9A%84%E6%9B%B4%E5%BF%AB)

**Comment by Grimler91** [comment]
Thanks, added
