### ISSUE TITLE
[New Mirror] DGUT

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#9792]
|  Repository   | sources.list entry  |
|  ----  | ----  |
| [Main](https://github.com/termux/termux-packages)  | `deb https://mirrors.dgut.edu.cn/termux/apt/termux-main stable main` |
| [Root](https://github.com/termux/termux-root-packages)  | `deb https://mirrors.dgut.edu.cn/termux/apt/termux-root root stable` |
| [X11](https://github.com/termux/x11-packages)  |`deb http://mirrors.dgut.edu.cn/termux/apt/termux-x11 x11 main` |

The mirror is in Guangdong,Dongguan,China.It runs ngnix and supports both IPv4 as well as https.

**Comment by Grimler91** [comment]
Thanks, added
