### ISSUE TITLE
[Package]: openexr

### ISSUE THREAD

**Issue by Randrianasulu** [termux/termux-packages#9794]
### Package description

OpenEXR provides the specification and reference implementation of the EXR file format, the professional-grade image storage format of the motion picture industry. 

### Home page URL

https://www.openexr.com/

### Source code URL

https://github.com/AcademySoftwareFoundation/openexr/archive/refs/tags/v3.1.4.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I tried older release 2.4.1 on arm7/android 10 device, it compiles and seems to work as part of our much larger video  editor project (cinelerra-gg)

**Comment by xtkoba** [comment]
You know, `openexr` 3.x is drastically different from previous versions and is known to break build of many packages in some distro. I would like to stick to 2.x unless other contributors take care of this.

**Comment by Randrianasulu** [comment]
2.x should be ok too
