### ISSUE TITLE
[Package]: twolame

### ISSUE THREAD

**Issue by Randrianasulu** [termux/termux-packages#9802]
### Package description

TwoLAME is an optimized MPEG Audio Layer 2 (MP2) encoder. 

### Home page URL

https://github.com/njh/twolame

### Source code URL

https://github.com/njh/twolame/archive/refs/tags/0.4.0.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

yet another dependency of cinelerra. I was surprized to find release from 2019

**Comment by Randrianasulu** [comment]
apparentky demand xmlto

https://www.linuxfromscratch.org/blfs/view/cvs/pst/xmlto.html

```
$ cat build.sh
TERMUX_PKG_HOMEPAGE=https://www.twolame.org                            TERMUX_PKG_DESCRIPTION="High quality MPEG Audio Layer II (MP2) encoder"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"                                        TERMUX_PKG_VERSION=0.4.0
TERMUX_PKG_REVISION=0                                                  TERMUX_PKG_SRCURL=https://github.com/njh/twolame/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=9f3f03bc9e1038d900f86002c7dce4b49109b3a61544800fc62d71dc51829f05
                                                                       termux_step_pre_configure() {
                ./autogen.sh
}
```

**Comment by xtkoba** [comment]
It is of no use pasting a partial `build.sh` here. You could submit a PR with a complete `build.sh` (and a patch set).

**Comment by Randrianasulu** [comment]
ok
