### ISSUE TITLE
[Package]: tinyemu

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#9815]
### Package description

A riscv64 tiny emulator

### Home page URL

https://bellard.org/tinyemu/

### Source code URL

https://bellard.org/tinyemu/tinyemu-2019-12-21.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

```
$ make
gcc -O2 -Wall -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -MMD -D_GNU_SOURCE -DCONFIG_VERSION=\"2019-12-21\" -DCONFIG_SLIRP -DCONFIG_FS_NET -DCONFIG_SDL -DCONFIG_RISCV_MAX_XLEN=128 -DCONFIG_X86EMU -c -o temu.o temu.c
In file included from temu.c:46:
In file included from ./virtio.h:141:
./fs.h:123:14: error: expected ';' at end of declaration list
    uint32_t st_atime_nsec;
             ^
/data/data/com.termux/files/usr/local/include/sys/stat.h:116:30: note: expanded from macro 'st_atime_nsec'
#define st_atime_nsec st_atim.tv_nsec
                             ^
In file included from temu.c:46:
In file included from ./virtio.h:141:
./fs.h:125:14: error: expected ';' at end of declaration list
    uint32_t st_mtime_nsec;
             ^
/data/data/com.termux/files/usr/local/include/sys/stat.h:117:30: note: expanded from macro 'st_mtime_nsec'
#define st_mtime_nsec st_mtim.tv_nsec
                             ^
In file included from temu.c:46:
In file included from ./virtio.h:141:
./fs.h:127:14: error: expected ';' at end of declaration list
    uint32_t st_ctime_nsec;
             ^
/data/data/com.termux/files/usr/local/include/sys/stat.h:118:30: note: expanded from macro 'st_ctime_nsec'
#define st_ctime_nsec st_ctim.tv_nsec
                             ^
3 errors generated.
make: *** [Makefile:129: temu.o] Error 1
$
```

**Comment by Yonle** [comment]
There also known multiple hardlinks. I've been patch them all. 

Patch file: https://yonle.host.oddprotocol.org/tinyemu_patch_hardlinks.patch

**Comment by wmcbtech30** [comment]
We already have QEMU package and it's architectural variants and `8086tiny`.

**Comment by xtkoba** [comment]
The same workaround should apply as https://github.com/termux/termux-packages/blob/41a4d4340b66b1caec02f7058963265f70499c27/packages/qemu-system-x86-64-headless/0003-fix-time_nsec-defs.patch.

**Comment by Yonle** [comment]
> The same workaround should apply as https://github.com/termux/termux-packages/blob/41a4d4340b66b1caec02f7058963265f70499c27/packages/qemu-system-x86-64-headless/0003-fix-time_nsec-defs.patch.

yep. that workaround is work as well
