### ISSUE TITLE
[Package]: e

### ISSUE THREAD

**Issue by bidyut1153-2** [termux/termux-packages#9820]
### Package description

All or almost all Unix editors support the syntax of "editor +42 file",

### Home page URL

https://github.com/kilobyte/e#readme

### Source code URL

https://github.com/kilobyte/e

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
It's a perl script consisting of 46 lines. Just download or copy paste the code to get it
