### ISSUE TITLE
[Package]: sixer

### ISSUE THREAD

**Issue by bidyut1153-2** [termux/termux-packages#9823]
### Package description

sixer is a tool adding Python 3 support to a Python 2 project

### Home page URL

https://github.com/vstinner/sixer

### Source code URL

https://github.com/vstinner/sixer

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
```bash
pip install sixer
```
