### ISSUE TITLE
[Package]: zzz

### ISSUE THREAD

**Issue by bidyut1153-2** [termux/termux-packages#9827]
### Package description

Simple and boring human readable data format for Zig.

### Home page URL

https://github.com/gruebite/zzz

### Source code URL

https://github.com/gruebite/zzz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by leapofazzam123** [comment]
It's just a package for zig and there's no point for adding it
