### ISSUE TITLE
[Package]: zig

### ISSUE THREAD

**Issue by bidyut1153-2** [termux/termux-packages#9828]
### Package description

A general-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.

### Home page URL

https://ziglang.org/

### Source code URL

https://github.com/ziglang/zig

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
We already have zig https://github.com/termux/termux-packages/tree/master/packages/zig
