### ISSUE TITLE
[Package]: cccc

### ISSUE THREAD

**Issue by bidyut1153-2** [termux/termux-packages#9829]
### Package description

CCCC: Source code counter and metrics tool for C++, C, and Java
Cachy: Cachy provides a simple yet effective caching library.

### Source code URL

https://github.com/sdispater/cachy and https://github.com/sarnold/cccc

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Cachy is a python package. We don't package python packages, install it through pip (as you have been repeatedly told). 

And please only request one package per "package request", possible exceptions would be if they are related, but that doesn't seem to be the case here
