### ISSUE TITLE
[Package]: curl7.7 and libcurl7.7

### ISSUE THREAD

**Issue by bidyut1153-2** [termux/termux-packages#9830]
### Package description

The website downloader for curl 7.7

### Home page URL

curl.se

### Source code URL

https://curl.se/download/curl-7.78.0.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
We don't provide old versions.
