### ISSUE TITLE
[Package]: tdlib-purple

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9835]
### Package description

libpurple Telegram plugin using tdlib

### Home page URL

https://github.com/ars3niy/tdlib-purple

### Source code URL

https://github.com/ars3niy/tdlib-purple.git

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Plugin for pidgin, bitlbee and other similar softwares.

I tried to build but got this error

```
CMake Error at /data/data/com.termux/files/usr/lib/cmake/Td/TdTargets.cmake:172 (message):
  The imported target "Td::tdutils" references the file

     "/data/data/com.termux/files/usr/lib/libtdutils.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/data/data/com.termux/files/usr/lib/cmake/Td/TdTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /data/data/com.termux/files/usr/lib/cmake/Td/TdConfig.cmake:3 (include)
  CMakeLists.txt:7 (find_package)
```

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last commit was 3 years ago so I consider this project is dead/frozen.
