### ISSUE TITLE
[Feature]: how can I install different versions of Python

### ISSUE THREAD

**Issue by yeyuchen198** [termux/termux-packages#9837]
### Feature description

The latest version of Python is 3.10+，it's too bad. Which can't use AES、rsa、rc4, it works when 3.9+.

Using Cipher functions like AES with Python 3.10+ will throw the error "PY_SSIZE_T_CLEAN macro must be defined for '#' formats".

### Additional information

I want to install Python3.9 like this:
apt install python=3.9.7

But it told me the version not found.
Another way to install Python3.9 is proot-distro install debian first, and then install Python in debian. However, it's much slower to run Python project in termux > debian / ubuntu than in termux itself.

**Comment by Grimler91** [comment]
For now only way would be to build it yourself. Adding additional python versions means more maintenance work, and more required disk space for mirrors.

Probably it is easier to fix whatever python module you are using to be compatible with python 3.10, maybe it already is if you check their development branch. Here's how pybluez seem to have fixed the same error: https://github.com/pybluez/pybluez/commit/cf6217c3e406be9271241d0f51867b7d19e9daf9

**Comment by yeyuchen198** [comment]
> 

okay, I found another way would be follow:
1.pkg uninstall python
2.wget https://raw.githubusercontent.com/Termux-pod/termux-pod/main/aarch64/python/python-3.9.7/python_3.9.7_aarch64.deb
3.dpkg -i ./python_3.9.7_aarch64.deb

By this way, Python3.9.7 could be installed, but the pip doesn't work because of SSL problem.

(See: https://github.com/Termux-pod/termux-pod)

**Comment by Grimler91** [comment]
Great, closing this issue then
