### ISSUE TITLE
[Package]: beecord

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9841]
### Package description

Bitlbee plugin for Discord

### Home page URL

https://github.com/sm00th/bitlbee-discord/

### Source code URL

https://github.com/sm00th/bitlbee-discord/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last commit was 3 years ago so I consider this project is dead/frozen.
