### ISSUE TITLE
[Package]: purple-hangout

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9847]
### Package description

Hangouts Plugin for libpurple

### Home page URL

https://github.com/EionRobb/purple-hangouts

### Source code URL

https://github.com/EionRobb/purple-hangouts

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last commit was 3 years ago so I consider this project is dead/frozen.
