### ISSUE TITLE
[Package]: bitlbee-facebook

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9848]
### Package description

Facebook protocol plugin for BitlBee

### Home page URL

https://github.com/bitlbee/bitlbee-facebook

### Source code URL

https://github.com/bitlbee/bitlbee-facebook

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by EllPrincipe** [comment]
_como assim?_

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Last commit was 3 years ago so I consider this project is dead/frozen.
