### ISSUE TITLE
[Package]: purple-matrix

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9849]
### Package description

Libpurple protocol plugin for matrix

### Home page URL

https://github.com/matrix-org/purple-matrix

### Source code URL

https://github.com/matrix-org/purple-matrix

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
> # Update 2022/04/11

> This project is essentially unmaintained. It may still work for you, in which case
good luck to you; however, it lacks many important features that are critical to a
modern Matrix client (not least of which is [end-to-end encryption support](https://github.com/matrix-org/purple-matrix/issues/18)).
>
