### ISSUE TITLE
[Package]: skypeweb

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9850]
### Package description

SkypeWeb Plugin for Pidgin

### Home page URL

https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb

### Source code URL

https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). 4 commits in the last two years so I consider this project is dead/frozen.
