### ISSUE TITLE
[Package]: tt-irc

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9852]
### Package description

Tiny Tiny IRC is an open source AJAX-powered chat platform

### Home page URL

https://git.tt-rss.org/fox/tt-irc.wiki.git/tree/Home.md

### Source code URL

https://git.tt-rss.org/fox/tt-irc.git/tree/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by T-Dynamos** [comment]
Also another x11

**Comment by aicynide** [comment]
Curious, how? Mind to explain?

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). Repository is unavailable, probably deleted. I consider the project is dead.
