### ISSUE TITLE
CANNOT LINK EXECUTABLE when i trying to generate tensorflow

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-packages#9867]
### Problem description

![Screenshot_2022-04-04-13-24-40-278_com termux](https://user-images.githubusercontent.com/72664192/161499405-59fb2a9c-c6fe-4ca8-a7e7-2c75bca9af5d.jpg)

### What steps will reproduce the bug?

I am trying to build tensorflow and and ArmNN library but getting error.. 

### System information

![Screenshot_2022-04-04-13-27-56-179_com termux](https://user-images.githubusercontent.com/72664192/161499650-d32c01f5-d89c-42d5-835c-9ce6d578adbd.jpg)

**Comment by xtkoba** [comment]
What is `armnn-tflite`?

**Comment by Grimler91** [comment]
Error is with your protobuf-host/bin/protoc, i.e. not a termux package. 
Try re-compiling it in case its dependencies has been updated. 

Closing since this is not a termux issue

**Comment by Saikatsaha1996** [comment]
> Error is with your protobuf-host/bin/protoc, i.e. not a termux package. Try re-compiling it in case its dependencies has been updated.
> 
> Closing since this is not a termux issue

Yes i build from Google protobuf..
So i should re-compile ?

**Comment by Saikatsaha1996** [comment]
> What is `armnn-tflite`?

Arm NN - tensorflow
