### ISSUE TITLE
Package request: Mercurial

### ISSUE THREAD

**Issue by abudden** [termux/termux-packages#987]
There's an existing package request for Mercurial support (#385); however, that issue has been closed and the resolution doesn't work for me.

That issue suggests:

~~~
apt install python2
pip2 install mercurial
hg --version
Mercurial Distributed SCM (version 3.9)
~~~

I tried this and got:

~~~
$ pip2 install mercurial
Collecting mercurial
  Downloading mercurial-4.2.tar.gz (5.3MB)
    100% |████████████████████████████████| 5.3MB 3.3MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/mercurial.egg-info
    writing pip-egg-info/mercurial.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/mercurial.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/mercurial.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/mercurial.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    Python headers are required to build Mercurial but weren't found in /data/data/com.termux/files/usr/include/python2.7/Python.h

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-7G11bg/mercurial/
~~~

Is there a fix or an alternative way of installing Mercurial?

**Comment by Grimler91** [comment]
`Python.h` is provided by the package python2-dev so try installing that:

    packages install python2-dev
    pip2 install mercurial

**Comment by abudden** [comment]
Brilliant, thank you.  I had to install `clang` as well (after an error message about `arm-linux-androideabi-gcc` not existing, but it appears to be working now.

**Comment by Grimler91** [comment]
Ah, great that it works! pip's error messages aren't always very helpful.

**Comment by adept** [comment]
Tried it just now, had to "pkg install python2 python2-dev clang crypt-dev" and then it worked
