### ISSUE TITLE
[Package]: Mcabber

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9873]
### Package description

mcabber is a small XMPP (Jabber) console client.

### Home page URL

https://mcabber.com/

### Source code URL

https://mcabber.com/hg/file/default/mcabber

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment]
Required loudmouth.

**Comment by twaik** [comment]
This project does not comply with our [packaging policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy). 4 commits in the last to years, the project is inactive.
