### ISSUE TITLE
[Package]: tiny

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9875]
### Package description

A terminal IRC client

### Home page URL

https://github.com/osa1/tiny

### Source code URL

https://github.com/osa1/tiny

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by khzmk** [comment]
This can be installed using cargo:

Install will fail when setting `--no-default-features` flag to use the termux openssl pkg, so don't use the flag. 

$ cargo install --git https://github.com/osa1/tiny

**Comment by twaik** [comment]
Not going to be packaged since it can be installed with cargo.
