### ISSUE TITLE
[Package]: elfeed

### ISSUE THREAD

**Issue by bidyut1153-2** [termux/termux-packages#9878]
### Package description

Elfeed is an extensible web feed reader for Emacs, supporting both Atom and RSS. I

### Home page URL

https://github.com/skeeto/elfeed

### Source code URL

https://github.com/skeeto/elfeed

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Install it through emacs's package manager.
