### ISSUE TITLE
[Package]: hash-slinger

### ISSUE THREAD

**Issue by bidyut1153-2** [termux/termux-packages#9880]
### Package description

This package contains various tools to generate special DNS records

### Home page URL

https://github.com/letoams/hash-slinger

### Source code URL

https://github.com/letoams/hash-slinger

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by T-Dynamos** [comment]
Required http://ftp.cn.debian.org/debian/pool/main/d/dnspython3/dnspython3_1.11.1-1.debian.tar.gz
