### ISSUE TITLE
CANNOT LINK EXECUTABLE "passwd": library "libcrypto.so.3" not found: needed by /data/data/com.termux/files/usr/lib/libtermux-auth.so in namespace (default)

### ISSUE THREAD

**Issue by cadasilv** [termux/termux-packages#9886]

**Comment by thunder-coding** [comment]
Update your packages, you seem to have done a partial upgrade.

```
$ pkg up
```

For recovering from a broken environment see #9050

**Comment by Kyawgyi388013** [comment]
$ pkg up

**Comment by Kyawgyi388013** [comment]
__found coreutils curl dash
  debianutils dialog diffutils dos2unix dpkg ed findutils
  gawk gpgv grep gzip inetutils less libandroid-support
  libassuan libc++ libcap-ng libcrypt libcurl libevent
  libexpat libgcrypt libgmp libgnutls libgpg-error
  libiconv libidn2 liblzma libmpfr libnettle libnghttp2
  libssh2 libtirpc libunistring lsof nano openssl pcre2
  procps psmisc pv readline sed tar termux-am
  termux-am-socket termux-exec termux-keyring
  termux-licenses termux-tools unbound unzip xxhash
  xz-utils zlib
62 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 16.6 MB of archives.
After this operation, 9482 kB of additional disk space will be used. @Kyawgyi388013

**Comment by TomJo2000** [comment]
Please just update all of your packages, that will resolve the issue.
