### ISSUE TITLE
Aircrack-ng for Termux.

### ISSUE THREAD

**Issue by NickVendetta** [termux/termux-packages#989]
Can Aircrack-ng be implemented in termux?

**Comment by Neo-Oli** [comment]
Duplicate of #371

**Comment by sumanmannna6111** [comment]
Need aircrack ng on termux

**Comment by vishalbiswas** [comment]
Not gonna happen. Aircrack-NG will only work on a select number of devices where following requirements are met:
* Root access
* WiFi adapter supports promiscuous mode
* WiFi module for that adapter supports promiscuous mode
* An OpenCL library. Currently, POCL is the best choice which doesn't compile.

As such, you are better off compiling Aircrack-NG on your own, if, your phone ships with a prebuilt OpenCL lib and meets all other requirements.

**Comment by Fahim43** [comment]
So give another something with out root

**Comment by vishalbiswas** [comment]
@Fahim43 If it were possible without superuser, why would anybody use aircrack?

**Comment by anonms1991** [comment]
Guys  pls help me to hack Wi-Fi by termux without root

**Comment by Funeoz** [comment]
search on YT, you will find good tutorials
