### ISSUE TITLE
[Bug]: Cannot install python

### ISSUE THREAD

**Issue by mdazizulbari** [termux/termux-packages#9891]
### Problem description

I on'y downloaded termux to learn web development in my android and I need to install Python for that. And I cannot install python.

### What steps will reproduce the bug?

fix the python package

### What is the expected behavior?

python package problem

### System information

termux-info:

```

```
$ pkg install python
Checking availability of current mirror: ok
Get:1 https://grimler.se/termux-packages-24 stable InRelease [16.8 kB]
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  502  Bad Gateway
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  502  Bad Gateway
Err:1 https://grimler.se/termux-packages-24 stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://grimler.se/termux-packages-24 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B
E: The repository 'https://grimler.se/termux-packages-24 stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

**Comment by xtkoba** [comment]
Or at least you should have read <a href="https://github.com/termux/termux-packages/issues/6726">this pinned issue</a>.

**Comment by Lucifer20703** [comment]
apt update && upgrade command not working please help me....![Screenshot_2022-04-15-16-40-33-376_com.termux.jpg](https://user-images.githubusercontent.com/103484114/163564427-ad44aa46-7b5a-457c-8c72-1ff89c317210.jpg)
