### ISSUE TITLE
[Bug]: Unknown alias: pgsql (Psych::BadAlias)

### ISSUE THREAD

**Issue by bugatro** [termux/termux-packages#9894]
### Problem description

After starting the metasploit database in termux,msfconsole command isnot working

### What steps will reproduce the bug?

~ $ msfconsole
/data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: pgsql (Psych::BadAlias)
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych.rb:370:in `load'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych.rb:671:in `block in load_file'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych.rb:670:in `open'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/psych.rb:670:in `load_file'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:194:in `init_db'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:285:in `get_db'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:201:in `block in db'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:200:in `db'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/ui/console/driver.rb:136:in `initialize'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `new'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `driver'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /data/data/com.termux/files/usr/bin/msfconsole:23:in `<main>'
~ $

### What is the expected behavior?

I expected it to start the metasploit console as before

### System information

termux-info:

```termux-info
Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# sources.list.d/termuxblack.list
deb https://hax4us.github.io/TermuxBlack/ termuxblack main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #2 SMP PREEMPT Mon Jul 5 19:35:15 CST 2021 armv7l Android
Device manufacturer:
INFINIX MOBILITY LIMITED
Device model:
Infinix X653C
~ $

```

**Comment by Grimler91** [comment]
metasploit is not a termux package. Report the issue where ever you got the program from
