### ISSUE TITLE
Crunch for Termux.

### ISSUE THREAD

**Issue by NickVendetta** [termux/termux-packages#990]
Can Crunch be implemented in termux?

**Comment by Neo-Oli** [comment]
Duplicate of #930

**Comment by Auxilus** [comment]
https://github.com/termux/termux-packages/pull/1766

**Comment by kerv94** [comment]
I don't quite understand can u use crunch in termux?

**Comment by kcubeterm** [comment]
@kerv94 yes you can use crunch in termux. 
But make sure you have enough space to keep crunch output.

**Comment by xeffyr** [comment]
> But make sure you have enough space to keep crunch output.

When you use it wisely, the output doesn't take much space.

Terabyte (or petabyte?) wordlists with content like
```
000000000000000000000000000000
000000000000000000000000000001
000000000000000000000000000002
<... skipped few thousands of lines ...>
000000000000000000019281928891
000000000000000000019281928892
000000000000000000019281928893
<... skipped a lot more ...>
999999999999999999999999999999
```
are useless and very ineffective. Wanna do stupid brute force, use specialized tools which do not require wordlists.
