### ISSUE TITLE
git-remote-https died of signal 6

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-packages#9900]
### Problem description

after boost* PKG install i am facing this problem..

![Screenshot_20220407-010945](https://user-images.githubusercontent.com/72664192/162058406-eb5030c4-d4c5-4aa3-920f-421a8f29f371.jpg)
![Screenshot_20220407-010850](https://user-images.githubusercontent.com/72664192/162058413-15f83634-1951-4993-b88f-02e9d3e163d4.jpg)

### What steps will reproduce the bug?

Nothing 

### System information

![Screenshot_20220407-010659](https://user-images.githubusercontent.com/72664192/162058339-49a45a1b-de56-4f9c-a494-dc11e70400a2.jpg)

**Comment by Saikatsaha1996** [comment]
Problem solved i am rooted that's why getting this error.. for SEI Linux..

**Comment by xtkoba** [comment]
I guess `/system/lib64/libcurl.so` is somehow referenced instead of `$PREFIX/lib/libcurl.so`. Maybe due to wrong `LD_LIBRARY_PATH`?


With the combination of `git_2.35.1-2` and `libcurl_7.82.0` I get the following:

```
$ ./libexec/git-core/git-remote-https
error: remote-curl: usage: git remote-curl <remote> [<url>]
```

while with a wrong `LD_LIBRARY_PATH`:

```
$ LD_LIBRARY_PATH=/system/lib64 ./libexec/git-core/git-remote-https
CANNOT LINK EXECUTABLE "./libexec/git-core/git-remote-https": cannot locate symbol "curl_global_sslset" referenced by "/data/data/com.termux/files/usr/libexec/git-core/git-remote-http"...
Aborted
```

(on Android 8.1.0, aarch64 userland, asus ASUS_X01AD.)

**Comment by T-Dynamos** [comment]
@xtkoba 
He is using virtual machine, I think so vmos pro?

**Comment by xtkoba** [comment]
@T-Dynamos If so, any difference?

**Comment by T-Dynamos** [comment]
![IMG_20220407_074848](https://user-images.githubusercontent.com/68729523/162107334-969dd536-0272-47c5-b4fc-5a5a8ea1559a.jpg)
But some roms don't have issue with `apt-key`

**Comment by xtkoba** [comment]
Oh, then we can close this immediately, isn't it?

**Comment by T-Dynamos** [comment]
Yes

**Comment by Saikatsaha1996** [comment]
> @xtkoba He is using virtual machine, I think so vmos pro? ![IMG_20220407_072329](https://user-images.githubusercontent.com/68729523/162104569-e48988de-4b5d-4d07-9ce2-fffb995b24dc.jpg)
> 
> 😂 Geek Rom

No i am useing mobile

**Comment by Saikatsaha1996** [comment]
> 

![Uploading IMG_20220407_114100.jpg…]()

**Comment by Saikatsaha1996** [comment]
> I guess `/system/lib64/libcurl.so` is somehow referenced instead of `$PREFIX/lib/libcurl.so`. Maybe due to wrong `LD_LIBRARY_PATH`?
> 
> With the combination of `git_2.35.1-2` and `libcurl_7.82.0` I get the following:
> 
> ```
> $ ./libexec/git-core/git-remote-https
> error: remote-curl: usage: git remote-curl <remote> [<url>]
> ```
> 
> while with a wrong `LD_LIBRARY_PATH`:
> 
> ```
> $ LD_LIBRARY_PATH=/system/lib64 ./libexec/git-core/git-remote-https
> CANNOT LINK EXECUTABLE "./libexec/git-core/git-remote-https": cannot locate symbol "curl_global_sslset" referenced by "/data/data/com.termux/files/usr/libexec/git-core/git-remote-http"...
> Aborted
> ```
> 
> (on Android 8.1.0, aarch64 userland, asus ASUS_X01AD.)

![IMG_20220407_114100](https://user-images.githubusercontent.com/72664192/162132097-8c1bfce9-9494-44d2-9be4-3839302ab84a.jpg)

**Comment by 0xj0hn** [comment]
same issue for me. any suggestions?

**Comment by xtkoba** [comment]
What is your `strace -f` output:

```bash
strace -f git [...]
```
