### ISSUE TITLE
Kali nethunter not closing after hitting ctrl+c in termux.

### ISSUE THREAD

**Issue by Aashutosh-kr** [termux/termux-packages#9905]
### Problem description

Kali nethunter not closing after hitting ctrl+c in termux but get stuck saying logout and not dispaly the usual termux prompt afterwards.
This happend everytime when I login to nethunter and used vncserver in it. But when I only use terminal it logouts normally.
I am using Kali nethunter minimal package with xfce desktop environment installed 

![Screenshot_2022-04-07-11-08-37-12_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/95764284/162129882-daa97bc5-cb6d-4e12-8a74-7119beedd50e.jpg)

### What steps will reproduce the bug?

1. login to Kali nethunter
2. Start vncserver on display :1 with `alias vnc='vncserver :1 -localhost no && export DISPLAY=:1'`
3. Killing it with `vncserver -kill :1`
4. Exit kali nethunter session using ctrl+d

### What is the expected behavior?

The expected behaviour is to exit out nethunter session and display the termux prompt.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
curl/stable 7.82.0-1 aarch64 [upgradable from: 7.82.0]
libcurl/stable 7.82.0-1 aarch64 [upgradable from: 7.82.0]
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf+ #2 SMP PREEMPT Fri Jan 21 10:32:38 CST 2022 aarch64 Android
Device manufacturer:
realme
Device model:
RMX2030

```

**Comment by MrAdityaAlok** [comment]
Nethunter is not provided by Termux, so closing it.

Although you can force close by viewing running processes from other session using `ps -aux` and `kill <nethunter pid>`
