### ISSUE TITLE
Input text issue

### ISSUE THREAD

**Issue by tanguinoche** [termux/termux-packages#992]
Hello,

I encounter some issue for some time,  my characters are replaced. For instance : 
I write "echo hello world"
And when I press Enter the line is replaced by "echo hhelloworld" and the ouput is indeed "hhelloworld".
Then I retry, I write "echo" and when I press the space, the line becomes "helloworldecho".
Then, I retry three times in a row and get the expected behavior.. but then I try other command lines, and the unexpected behavior happens again, like if some characters are still in the buffer..

Is someone had a similar issue ? I tried on another  app, and also reinstall app with the same phone, but result is still the same. Furthermore, termux worked properly few months ago. It seems something has been broken on my phone (S7, android 6.0.1). Any idea ?

Thank you

**Comment by vishalbiswas** [comment]
Probably related to the keyboard app you are using

**Comment by tanguinoche** [comment]
I use the native keyboard of the phone, and termux was working properly the first few months. ..

**Comment by fornwall** [comment]
@tanguinoche Can you try disabling predictive text and/or auto correction on on the stock Samsung keyboard you are using and see if that fixes the problem?

**Comment by tanguinoche** [comment]
Oh I don't why I didn't think about that ! It works much better thank you, I think it is ok when I write manually. Nevertheless, I still have the effect if I use the "tab bash autocomplete". I will try to change some keyboards parameters

**Comment by tanguinoche** [comment]
Ok, my keyboard was in french (azerty), I set it to English-US and everything seems working properly. Thank you for your help :-)

**Comment by Grimler91** [comment]
Closing this as it doesn't seem to be an issue any more.
