### ISSUE TITLE
[Package]: chibicc

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#9925]
### Package description

A small C compiler

### Source code URL

https://github.com/rui314/chibicc/archive/90d1f7f199cc55b13c7fdb5839d1409806633fdb.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by MrAdityaAlok** [comment]
@2096779623 
From packaging policy:
> Not serving duplicated functionality
> Please avoid submitting packages which duplicate functionality of already present ones.

We already have clang. Any good reason to include this...?

**Comment by 2096779623** [comment]
> @2096779623 From packaging policy:
> 
> > Not serving duplicated functionality
> > Please avoid submitting packages which duplicate functionality of already present ones.
> 
> We already have clang. Any good reason to include this...?

https://github.com/rui314/chibicc/#status

 4.7k stars , 419 forks.
I think a lot of people are using it.

**Comment by wmcbtech30** [comment]
Apart from popularity, any specific reason why it is better than clang? it's compile speed or any other features present missing from clang?

**Comment by 2096779623** [comment]
> Apart from popularity, any specific reason why it is better than clang? it's compile speed or any other features present missing from clang?

it is smaller than clang,chibicc's core value is its simplicity and the reability of its source code.
chibicc outputs a simple but nice error message when it finds an error in source code.

**Comment by xtkoba** [comment]
The priority is fairly low if not "wontfix", as it works only on x86_64 (IIRC).
