### ISSUE TITLE
[Bug]:  vlc 3.0.17.3-1 doesn't play streams.

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#9926]
### Problem description

Upgrade to vlc 3.0.17.3-1 from 3.0.14 has removed the capability to play streaming media, eg, the BBC world service stream:- http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_world_service.m3u8

### What steps will reproduce the bug?

Execute vlc http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_world_service.m3u8

### What is the expected behavior?

Should play audio.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.org/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Fri Sep 17 17:16:18 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003

```

**Comment by xtkoba** [comment]
From logcat:

```
11139 I VLC     : [00000072ca044950/2b83] adaptive demux: Changing stream format Unknown -> TS
11139 D VLC     : [00000072ca044950/2b83] main demux: creating demux: access='' demux='ts' location='' file='(null)'
11139 D VLC     : [00000072de4360d0/2b83] main demux: looking for demux module matching "ts": 47 candidates
11139 D VLC     : [00000072de4360d0/2b83] main demux: no demux modules matched
11139 E VLC     : [00000072ca044950/2b83] adaptive demux: Failed to create demuxer 0x0 TS
```

for which

https://github.com/termux/termux-packages/blob/3d8f12fdc7424d0ef06cd8e8d27a7572cb40d083/packages/vlc/build.sh#L25

should be the culprit. VLC requires `libdvbpsi` for demuxing TS.

I will work on it.

**Comment by macerg** [comment]
Thanks. Fast action as usual. Much appreciated.

**Comment by xtkoba** [comment]
No. It should go to another package, say `vlc-qt` (https://github.com/termux/x11-packages/issues/584).

**Comment by macerg** [comment]
Not sure whether work to resolve the issue is complete. Applied all updates but problem still exists. Will not play the BBC streams.

**Comment by Grimler91** [comment]
> Not sure whether work to resolve the issue is complete. Applied all updates but problem still exists. Will not play the BBC streams.

Are you sure you have `3.0.17.3-2` installed? It was made available from main repo like 5 minutes ago

**Comment by macerg** [comment]
Ok, I'll recheck..

**Comment by macerg** [comment]
The http interface problem has returned.
Yes, I am running 3.0.17.3-2

**Comment by macerg** [comment]
Ok now running 3.0.17.3

**Comment by macerg** [comment]
Confirmed, http interface problem has returned.
LC media player 3.0.17.3 Vetinari (revision 3.0.13-8-g41878ff4f2)
vlc: unknown option or missing mandatory argument `--http-password'
Try `vlc --help' for more information.

**Comment by macerg** [comment]
Ok, all seams well now. Thanks.
