### ISSUE TITLE
[Bug]: github action: pulseaudio does not compile for arm

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#9934]
### Problem description

https://github.com/Maxython/termux-packages-pacman/runs/5953879712?check_suite_focus=true

### What steps will reproduce the bug?

auto update

### System information

This is github action

**Comment by xtkoba** [comment]
From build log:

```
ERROR: lib/libwebrtc-util.so contains undefined symbol __aeabi_idiv
```
