### ISSUE TITLE
Undefined reference to symbols defined in `libandroid-posix-semaphore` or `libandroid-shmem`

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#9944]
For `libandroid-posix-semaphore` (#9559) and `libandroid-shmem` (#9560), we have modified public headers so that they do not declare some libc symbols but instead declare symbols prefixed by `libandroid_` defined in `libandroid-*` libraries.

The problem is that a shared library can reference those symbols yet does not link against respective libraries, with `ld` emitting no error.

I propose that those "undefined" symbols be trapped in `termux_step_massage`, in a similar way to compiler-rt builtin symbols. ~~This time we have to check `DT_NEEDED` fields for those libraries, as those symbols are always marked as `UND` regardless of `DT_NEEDED`.~~ [EDIT] It is not necessary to check `DT_NEEDED`. The `NOTYPE` type for a symbol should indicate its unresolvability.

**Comment by xtkoba** [comment]
@Grimler91 and I worked on existing packages for resolving undefined symbols defined in `libandroid-posix-semaphore`. If problem remains for any package, then please open a new issue for that (instead of reporting as a comment here).

**Comment by Saikatsaha1996** [comment]
@xtkoba i am getting same type error... If any solution available help appreciate.. thank you..


```
ld.lld: error: undefined symbol: pthread_mutexattr_setprotocol                                  >>> referenced by pulse.c:184 (dlls/winepulse.drv/pulse.c:184)                                  >>>               dlls/winepulse.drv/pulse.o:(pulse_process_attach)                             clang-14: error: linker command failed with exit code 1 (use -v to see invocation)              make: *** [Makefile:142895: dlls/winepulse.drv/winepulse.so] Error 1                            make: *** Waiting for unfinished jobs....                                                       dlls/dhtmled.ocx/edit.c:193:37: warning: incompatible pointer types passing 'LONG *' (aka 'int *') to parameter of type 'volatile long *' [-Wincompatible-pointer-types]                            LONG ref = InterlockedIncrement(&This->ref);                                                                                    ^~~~~~~~~~                                                  include/winnt.h:6352:47: note: passing argument to parameter here                               long      _InterlockedIncrement(long volatile*);                                                                                              ^                                                 dlls/dhtmled.ocx/edit.c:292:37: warning: incompatible pointer types passing 'LONG *' (aka 'int *') to parameter of type 'volatile long *' [-Wincompatible-pointer-types]                            LONG ref = InterlockedDecrement(&This->ref);                                                                                    ^~~~~~~~~~                                                  include/winnt.h:6348:47: note: passing argument to parameter here                               long      _InterlockedDecrement(long volatile*);                                                                                              ^                                                 ld.lld: error: undefined symbol: libandroid_shmget                                              >>> referenced by bitblt.c:1788 (dlls/winex11.drv/bitblt.c:1788)                                >>>               dlls/winex11.drv/bitblt.o:(create_surface)                                                                                                                                    ld.lld: error: undefined symbol: libandroid_shmat                                               >>> referenced by bitblt.c:1791 (dlls/winex11.drv/bitblt.c:1791)                                >>>               dlls/winex11.drv/bitblt.o:(create_surface)                                                                                                                                    ld.lld: error: undefined symbol: libandroid_shmctl                                              >>> referenced by bitblt.c:1803 (dlls/winex11.drv/bitblt.c:1803)                                >>>               dlls/winex11.drv/bitblt.o:(create_surface)                                    >>> referenced by bitblt.c:1808 (dlls/winex11.drv/bitblt.c:1808)                                >>>               dlls/winex11.drv/bitblt.o:(create_surface)                                                                                                                                    ld.lld: error: undefined symbol: libandroid_shmdt                                               >>> referenced by bitblt.c:1806 (dlls/winex11.drv/bitblt.c:1806)                                >>>               dlls/winex11.drv/bitblt.o:(create_surface)                                    >>> referenced by bitblt.c:1972 (dlls/winex11.drv/bitblt.c:1972)                                >>>               dlls/winex11.drv/bitblt.o:(x11drv_surface_destroy)                            clang-14: error: linker command failed with exit code 1 (use -v to see invocation)              winegcc: /data/data/com.termux/files/usr/bin/gcc failed                                         make: *** [Makefile:143559: dlls/winex11.drv/winex11.drv.so] Error 2                            2 warnings generated.                                                                           6 warnings generated.
```

**Comment by tomty89** [comment]
No it is not the same type of error. The problem you have is because `pthread_mutexattr_setprotocol()` won't be available on Android 8.1 or earlier. You need to make the build system of whatever you are building be aware of that, namely make sure `__ANDROID_API__` is defined and defined as `27` or less. (Assuming that actually prevents the build system from compiling the unsupported code. Otherwise you might even need to patch it out by some means.)

**Comment by Saikatsaha1996** [comment]
> No it is not the same type of error. The problem you have bumped into is due to the fact that `pthread_mutexattr_setprotocol()` isn't available on Android 8.1 or earlier. You need to make the build system of whatever you are building be aware of that, namely by making sure `__ANDROID_API__` is defined and defined as `27` or less. (Assuming that would actually prevent the build system from compiling the unsupported code. Otherwise you might even need to patch it out by some means.)

Another error solved 😔 but this one don't know how to solve

![Screenshot_2022-08-02-16-32-04-334_com termux](https://user-images.githubusercontent.com/72664192/182359594-0718f37a-3a7e-42a7-be8d-a1829462cec8.jpg)

**Comment by tomty89** [comment]
Still the same error (the other warnings are irrelevant). Please stop spamming irrelevant issue. If you want further help on how to building stuff yourself, consider https://gitter.im/termux/termux. (Nothing is guaranteed though.)

**Comment by xtkoba** [comment]
Presumably related issue: #14285. Workaround for `libandroid-execinfo` already added: fbaecc5c267ac42a433f75389307cb71510371fb.

**Comment by xtkoba** [comment]
BTW, I basically don't care for closed issues unless labeled as "wontfix". Opening a new issue (or discussion) is recommended.

**Comment by Saikatsaha1996** [comment]
> BTW, I basically don't care for closed issues unless labeled as "wontfix". Opening a new issue (or discussion) is recommended.

You can close.. i already solved this issue with another  tricks..

All issues solved.. now working with glibc..
