### ISSUE TITLE
[Package]: ssdeep

### ISSUE THREAD

**Issue by DreamOneX** [termux/termux-packages#9957]
### Package description

Fuzzy hashing API and fuzzy hashing tool

### Home page URL

https://ssdeep-project.github.io/ssdeep/index.html

### Source code URL

https://github.com/ssdeep-project/ssdeep/archive/refs/tags/release-2.14.1.tar.gz

### Packaging policy acknowledgement

- [x] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by T-DynamosFans** [comment]
![Screenshot_2022-04-10-18-01-01-086_com termux](https://user-images.githubusercontent.com/96837234/162618245-b9cdde8c-2856-4212-ac47-4f7b6bcff22a.jpg)
## Seems working
