### ISSUE TITLE
[Bug]: libusb: Pulls git "snapshot" instead of release tarball

### ISSUE THREAD

**Issue by tormodvolden** [termux/termux-packages#9962]
https://github.com/termux/termux-packages/blob/6ea230804d3022a256f30b2dd5065d5ca7286777/packages/libusb/build.sh#L6 
should refer to .tar.bz instead of .tar.gz

\*.tar.gz is something GitHub cooks up itself, unfortunately I haven't found a way to disable them*. They are just a git snapshot, without e.g. configure.

\*.tar.bz are the official release files, these are proper release tarballs including configure.

\*) https://github.com/github/feedback/discussions/6003

**Comment by xtkoba** [comment]
I see you are an upstream maintainer. Please feel free to submit a PR for this under your name. Thanks.

**Comment by tormodvolden** [comment]
I wouldn't be able to test it since I don't have the Termux build setup, and I generally don't like to submit untested PRs. Do you have automatic tests on PRs?

You can then also remove the termux_step_pre_configure() step. Maybe @Grimler91 or @librevm can take a look.
