### ISSUE TITLE
[Bug]: ncspot not working properly 

### ISSUE THREAD

**Issue by KKD4yv1d** [termux/termux-packages#9993]
### Problem description

I recently installed ncspot to listen my musics on termux, but when i press enter to play that music the program crashes

### What steps will reproduce the bug?

Open ncspot
Login on any acount
Try to play a music

### What is the expected behavior?

The program doesn't crash

### System information

termux-info:

```
Android Version: 11
Phone: Motorola One Fusion ( RPLS31.Q2-63-10-2-7 )
Termux version: 0.118.0
```

**Comment by T-Dynamos** [comment]
Mention device arch?

**Comment by Grimler91** [comment]
What does crash mean? What's the error message/backtrace?

Also paste your output of `termux-info`.

**Comment by KKD4yv1d** [comment]
The error doesn't have any message, the program only crashes without any error message, i can use strace on the process and paste the strace output here

Termux-info:
termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Mon Jan 31 00:50:56 CST 2022 aarch64 Android
Device manufacturer:
motorola
Device model:
motorola one fusion

**Comment by KKD4yv1d** [comment]
strace output: https://paste.gg/p/anonymous/70ab358472a54585b0e1810123849280/files/9eacb6a91b3d4b4bbec6a6937dea53e9/raw

**Comment by MrAdityaAlok** [comment]
Maybe it is related to https://github.com/hrkfdn/ncspot/issues/457. Updating should fix this. I will attempt updating this in morning...

**Comment by KKD4yv1d** [comment]
Okay, thanks by the responses ^^ have a good job
