### ISSUE TITLE
[Bug]: Cant install nodejs

### ISSUE THREAD

**Issue by luisdavim** [termux/termux-packages#9996]
### Problem description

I get the following error when trying to install `nodejs`

```console
$ apt install nodejs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/7984 kB of archives.
After this operation, 47.0 MB of additional disk space will be used.
Selecting previously unselected package nodejs.
(Reading database ... 44129 files and directories currently installed.)
Preparing to unpack .../nodejs_17.9.0_aarch64.deb ...
Unpacking nodejs (17.9.0) ...
Setting up nodejs (17.9.0) ...
CANNOT LINK EXECUTABLE "node": library "libicui18n.so.70" not found: needed by main executable
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Processing triggers for man (1.14.5-3) ...
Errors were encountered while processing:
 nodejs
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

### What steps will reproduce the bug?

Just try to install or upgrade the `nodejs` package: `apt install nodejs`

### What is the expected behavior?

`nodejs` should install without errors

### System information

termux-info:

```console
$ termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 5.10.43-android12-9-23981888-abX906BXXU1AVCD #1 SMP PREEMPT Thu Mar 31 08:58:45 UTC 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-X906B
```

**Comment by T-Dynamos** [comment]
I am unable to reproduce error , try with upgrading `libicu` then try

**Comment by xu3s** [comment]
![Screenshot_20220413-081115.png](https://user-images.githubusercontent.com/47383486/163079733-ce803ebd-4535-4a4e-a892-666e22293545.png)
I got the same issues, all package is upgraded

**Comment by xqwtxon** [comment]
We are same also also php and other commands packages are not working rn :(

**Comment by xqwtxon** [comment]
```log
CANNOT LINK EXECUTABLE "node": library "libicui18n.so.70" not found
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

**Comment by xqwtxon** [comment]
![IMG_20220413_103206](https://user-images.githubusercontent.com/100104970/163088159-6ce0a1a0-a9d5-4754-983d-4d84fe196134.jpg)
This what i got errors. This picture indicates the `termux-info`command.
![IMG_20220413_103428](https://user-images.githubusercontent.com/100104970/163088544-b61ec606-167b-4345-80b0-b96215548bc2.jpg)
![IMG_20220413_103428](https://user-images.githubusercontent.com/100104970/163088561-79f6e817-9f8c-437a-b480-cbb67fbb3d9b.jpg)

**Comment by xtkoba** [comment]
This is because DEB packages for `nodejs` version `17.9.0-1` are not uploaded (by CI) somehow. The same goes for `nodejs-lts` version `16.14.2-1`. Now I have manually rerun CI for those two packages, which will take several hours to complete. Thanks.

**Comment by thunder-coding** [comment]
> Now I have manually rerun CI for those two packages, which will take several hours to complete. Thanks.

Maybe just re-running the upload job too must have worked. Let me see if that does the trick, if it does I'll cancel the CI run triggered by you.

**Comment by DoveBoy** [comment]
@xtkoba How long does it take to recover?

**Comment by thunder-coding** [comment]
> @xtkoba How long does it take to recover?

Latest debs for nodejs and nodejs-lts should now be available from packages-cf.termux.org and grimler.se mirrors. Other mirrors may take some time to sync though

**Comment by Adityapro9** [comment]
> i am also trying
